### ISSUE TITLE
Stop music playback when app is closed and cleared from recent tasks

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#10]
### Description

A setting to stop music playback when app is closed and cleared from recent tasks

### Suggested Solution

A toggle option will be great 
![image](https://github.com/fast4x/RiMusic/assets/127825700/c212afe1-257e-41ac-89aa-5fc2ef72fa5c)
something like this

**Comment by fast4x** [comment]
Yes, it can be useful.
Thanks for the suggestion.

**Comment by dainvincible1** [comment]
> Yes, it can be useful. Thanks for the suggestion.

yes. please add it, if possible. thank you

**Comment by dainvincible1** [comment]
> Yes, it can be useful. Thanks for the suggestion.

@fast4x will we get to see this feature in the future? 😁

**Comment by dainvincible1** [comment]
> Sure, please tell me which device you use and which version of Android? 😋

@fast4x currently I'm using Android 11. And device is realme 5 pro. 
Thank you

**Comment by fast4x** [comment]
Implemented, available from version 0.6.4 ;)

**Comment by dainvincible1** [comment]
thank you :) 

> Implemented, available from version 0.6.4 ;)
