### ISSUE TITLE
Improve user created/imported playlist search icon

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1000]
### Description

When searched with keywords on Favorites (or other app provided playlist) the song amount shows correctly:

![Screenshot_20240304-130351.jpg](https://github.com/fast4x/RiMusic/assets/85461823/cd661416-f507-47b7-be9a-78f80ae16aeb)

But when searched on any user created/imported playlist it doesn't show the right amount:

![Screenshot_20240304-130929.jpg](https://github.com/fast4x/RiMusic/assets/85461823/53ab0061-72c8-44cc-89fa-d49191900472)

### Suggested Solution

Make user created/imported playlist search icon work similar to how app provided one does.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.26
Now work on #825
