### ISSUE TITLE
Random button on tabs as animated dice rolling 

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1001]
### Description

In my opinion the current random button on **Artists**, **Albums** tabs look like "shuffle" button. I know random button looks like this as well. And both "random" and "shuffle" are kinda similar term.
But still that button doesn't seem right to me as "random" button. 

### Suggested Solution

It'd probably look better if it was a dice. Which would animate rolling. That way it'd seem more like a random button.

Btw the placement and size of the button is currently great. But if you do change it to dice then probably would be better to increase the size just a little bit. And place it slightly on the right meaning at the "top center" of those two tabs.

### Additional Context

I actually really want this but probably many others won't like it so I want feedback about this idea.

**Comment by fast4x** [comment]
I like dice, I'll try to change it soon.

**Comment by fast4x** [comment]
Implemented icon shuffle replaced with dice, animation more professional require other work, in the future...

**Comment by dAtA-TRoN** [comment]
Great idea with the dice! -Love it.
