### ISSUE TITLE
Revamp of Search Page Layout

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1004]
### Description

The current layout of the search page in RiMusic proves to be uncomfortable and wastes unnecessary screen space. This leads to an inefficient user experience and impacts user satisfaction.

![Search Page (Current State)](https://github.com/fast4x/RiMusic/assets/71184627/28d88a81-a670-4af7-97fd-062d57369bf5)

### Suggested Solution

Mockup:

![Search Page (Redesigned)](https://github.com/fast4x/RiMusic/assets/71184627/09b02a98-f515-4d14-863d-4d1493f9e519)

1. Optimization of Space Utilization: By optimizing the space requirements, more text can be displayed at once, leading to a more efficient search experience.

2. Improvement of Arrangement: A redesigned arrangement of search filters and other elements can enhance user-friendliness and facilitate access to relevant information.

Before:
![Removing the old clear button](https://github.com/fast4x/RiMusic/assets/71184627/a9a580bb-361a-4454-a328-66ec6758d863)

After:
![1710082704091.png](https://github.com/fast4x/RiMusic/assets/71184627/f473cf25-d5e5-48f4-8444-a319dfb41d43)

### Additional Context

A redesigned layout of the search page would significantly improve the user experience by increasing search efficiency and enabling the display of more text at once. Feedback and suggestions for improvement are always welcome.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.26

**Comment by dAtA-TRoN** [comment]
> Implemented, available from version 0.6.26

Absolutely fantastic job! That was so desperately needed. If I hadn't brought it up, someone else would have surely asked for it soon. Or you would have just done it yourself. I think it was a very obvious area that needed attention.

I believe that implementing #941, if you intend to do so, will be considerably easier with this.
