### ISSUE TITLE
Text copying feature 

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1007]
### Description

I think throughout the whole app there's lots of things and we want to copy lots of them. For example song title, album title, artist name, artist description, lyrics etc.

### Suggested Solution

As the issue title says.

### Additional Context

I feel like this is gonna be hard and will cause other problems. So I'm not so sure if it is actually needed or not considering everything.

**Comment by dAtA-TRoN** [comment]
I sense it's might be veering into feature creep territory. I understand your perspective, but let's keep in mind that this is primarily a music app, not a text editing software. So, it might seem a bit odd if users could easily copy any text within the app. I mean, how would they do that without a long-press feature? And suddenly popping up a 'copy' option might not be the best approach. But hey, that's just my take on it, and I don't claim to have all the answers.

**Comment by dAtA-TRoN** [comment]
> Yeah I know all that. And it might really clash with many other actions. Like there are some features where you have to tap and hold. (for example song menu) So it'll clash.\n\nI knew this but yet created this issue. I certainly am so impatient. My bad.

I hope that didn't come across as preachy or anything like that. It was just my opinion, and sometimes it's intriguing to hear what others have to say about an idea.

**Comment by dAtA-TRoN** [comment]
> No. lol\nI myself knew all those things subconsciously yet wanting this feature. It's alright.

Alright, good, because that's really not what I meant 🙃.
