### ISSUE TITLE
Online search button of user created/imported playlists ain't working 

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1008]
### Steps to reproduce the bug

1. Go to user created/imported playlist
2. Tap on "online search" button

### Expected behavior

Search box appear

### Actual behavior

Black screen 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/85461823/fae7dc29-f6c9-4a2d-9475-f149c280eaff

### RiMusic version

0.6.25

### Android version

Android 11

### Additional information

Happens only with user created/imported playlists. App provided ones are alright.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.26

**Comment by fast4x** [comment]
Yes, it makes no sense to search online in a local playlist...
