### ISSUE TITLE
Sidebar missing when i have it at the Right

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1010]
### Steps to reproduce the bug

1. Go in the settings
2. Select the Sidebar to the Right
3. Go in a playlist (In my case is Liked)

### Expected behavior

Show the sidebar

### Actual behavior

sidebar is hidden

### Screenshots/Screen recordings

![Screenshot_20240310_213423](https://github.com/fast4x/RiMusic/assets/104271365/e184a881-7969-4aa4-931f-6962d1c93f6a)

### RiMusic version

0.6.25

### Android version

Android 14

**Comment by dAtA-TRoN** [comment]
fast4x has already taken care of it. Its status is "implemented".
