### ISSUE TITLE
[Feature]: Add old dark dynamic theme back as an option

### ISSUE THREAD

**Issue by Lasnick** [fast4x/RiMusic#1012]
### Description

Although the new amoled dynamic theme (Introduced in version 0.6.25) is cool, a option to enable the old colored-grey background would be better to me. Especially in the Player

The black on black can lead to poor contrast and the black doesn't look so good when you have something as colorful as a album cover on it. The cover will look a bit out of place

![Screenshot_20240310_224819](https://github.com/fast4x/RiMusic/assets/122399056/a287524f-1993-4d5c-8a73-64c60621227b)
[Poor contrast with pop-ups]

![Screenshot_20240310_225448](https://github.com/fast4x/RiMusic/assets/122399056/8ab2cd01-db2c-455d-afb6-a9f1b6e7b683)
['Out of place' album cover]

I know that this change stems from many requests, so I would want it to be purely optional

### Suggested Solution

- Extra option in the theme setting to enable the grey dynamic theme

![Screenshot_20240310_231611](https://github.com/fast4x/RiMusic/assets/122399056/f0fe9097-a315-4281-a037-90a601fd8a09)
[Dynamic darkmode in 0.6.24]

### Alternatives

One step more: 
- separate player-theme untied from the rest of the app

**Comment by fast4x** [comment]
Hi, it's just reverted like 0.6.24, and i have added new Pitch Black theme mode, all will be available in next version 0.6.26
