### ISSUE TITLE
Chinese Traditional is Simplified

### ISSUE THREAD

**Issue by yjctw** [fast4x/RiMusic#1013]
### Description

All UI and Lyrics are Simplified Chinese, and some Lyrics is wrong.
![Screenshot_20240311_115715](https://github.com/fast4x/RiMusic/assets/61110572/b79a726c-7cd0-4fda-8c4e-f08064d2f937)
![Screenshot_20240311_120253](https://github.com/fast4x/RiMusic/assets/61110572/33560373-4bb7-4d64-b969-472cdeba01de)

### Suggested Solution

Convert UI language and change lyrics source, like Netease.

**Comment by OrangeZXZ** [comment]
Maybe this is a bug or a error coming from the translator

**Comment by fast4x** [comment]
Go to Crowdin and check if translation is wrong.
