### ISSUE TITLE
Android miniplayer reopens even if im not listening

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1017]
### Steps to reproduce the bug

1. Listen to a song
3. Stop listening
2. Close the app
4. Close the android miniplayer
3. Wait

I also think that it is due to Invincible option

### Expected behavior

Not show if i stop listening

### Actual behavior

Shows automatically even if in pause

### Screenshots/Screen recordings

![Screenshot_20240311_085844_One UI Home](https://github.com/fast4x/RiMusic/assets/104271365/443539ee-cdec-4cbd-94d0-493ceab6dcf4)

### RiMusic version

0.6.25

### Android version

Android 14

**Comment by fast4x** [comment]
Background player show,  stop. ahahahah

**Comment by OrangeZXZ** [comment]
> Background player show,  stop. ahahahah

it is stopped but it reappears in the paused state not sure if the os or app is at fault

**Comment by OrangeZXZ** [comment]
> Background player is a system service... player must show...

even if i closed it completely and cleared the queue?

**Comment by fast4x** [comment]
yes

**Comment by OrangeZXZ** [comment]
Maybe i didn't explained well

If you listen to and song then pause it then quit the app delete the android player if the app is not force closed after a bit of time the notification reappears.

I shouldn't because im not listening and the app is closed

**Comment by OrangeZXZ** [comment]
> Maybe i didn't explained well
> 
> If you listen to a song then pause it then quit the app delete the android player if the app is not force closed after a bit of time the notification reappears.
> 
> I shouldn't because im not listening and the app is closed

It happens when i get outlook notifications maybe a android restart will patch this

**Comment by OrangeZXZ** [comment]
after restart the problem is worse it plays the old queue

https://github.com/fast4x/RiMusic/assets/104271365/eb0c7b38-0318-4c24-8a6a-28357be6e185

**Comment by OrangeZXZ** [comment]
> after restart the problem is worse it plays the old queue
> 
> https://github.com/fast4x/RiMusic/assets/104271365/eb0c7b38-0318-4c24-8a6a-28357be6e185

i disabled the persistent queue and the bug disappeared maybe it is related to that

**Comment by fast4x** [comment]
ok, maybe I have understand

**Comment by fast4x** [comment]
yes it's related

**Comment by Nikks84** [comment]
> after restart the problem is worse it plays the old queue
> 
>  Screen_Recording_20240311_143721_One.UI.Home_1.mp4

😂 same  Yes this is also happen in my case.
I had the feeling that this is happening with my own or else my system background player I only have some problem
