### ISSUE TITLE
[Feature]: automatically lower quality if high not available 

### ISSUE THREAD

**Issue by pordini** [fast4x/RiMusic#1018]
### Description

RiMusic stops playing and gives the error "Couldn't find a playable audio format". 
The issue was set to solved in https://github.com/fast4x/RiMusic/issues/382

### Suggested Solution

When selecting audio quality format High in Settings but high quality is not available, play the highest possible quality that is available.

### Alternatives

Alternatively, selecting audio quality format Automatic always plays the highest possible quality.
(If this is the current behaviour already, then having the option High and Automatic seems confusing.)

Additionally, if the track cannot be played it would be nice to have an "automatic skip on error" option or default so that the music continues. This woud be helpful when having the phone in a pocket or bag, especially when it is cold or raining (or both).

**Comment by dAtA-TRoN** [comment]
Ah, that's where it originates. Very good to know, and I fully agree with your suggestion!

**Comment by OrangeZXZ** [comment]
I think the automatic is already taking the best audio

But the option should be seen as a wall
(automatic but stops at the given quality)

**Comment by OrangeZXZ** [comment]
> I think the automatic is already taking the best audio
> 
> But the option should be seen as a wall and we should remove the automatic
> (automatic but stops at the given quality)

maybe also give a warning pop-up when there isn't a hight quality

**Comment by dAtA-TRoN** [comment]
> maybe also give a warning pop-up when there isn't a hight quality

Why do we need to be warned about it?

**Comment by OrangeZXZ** [comment]
> > maybe also give a warning pop-up when there isn't a hight quality
> 
> Why do we need to be warned about it?

That way the user knows but they will probably forget what quality it is 😅

**Comment by dAtA-TRoN** [comment]
> > > maybe also give a warning pop-up when there isn't a hight quality
> > 
> > Why do we need to be warned about it?
> 
> That way the user knows but they will probably forget what quality it is 😅

I think that would be a bit too much. The app isn't really aimed at audiophile individuals anyway. It can't even cater to them since the lossless formats are behind a paywall. So this app already plays music with a noticeable loss in quality anyway. So, having such a warning would be a bit excessive, I believe.

**Comment by fast4x** [comment]
Set automatic audio quality in settings.
