### ISSUE TITLE
App not opening links

### ISSUE THREAD

**Issue by minislel** [fast4x/RiMusic#1019]
### Steps to reproduce the bug

1. Set a default to open links in app (music.youtube.com)
2. Click on a link from messenger or other source

### Expected behavior

App should open the song from the link and maybe start playback

### Actual behavior

The app just opens on a last screen that it was left on

### RiMusic version

0.6.25

### Android version

Android 13 project elixir rom

### Additional information

Oneplus 8t

**Comment by OrangeZXZ** [comment]
> you should have this option in the app settings if not on android 12 or higher you should use LinkSheet witch is oppensource  and on Fdroid (this is an android isue not the app)

![SmartSelect_20240311_112049_Google.jpg](https://github.com/fast4x/RiMusic/assets/104271365/619d786f-2c4a-4ac5-82b3-b55058cb6a39)

**Comment by minislel** [comment]
I have this option enabled and the problem is st
![Uploading Screenshot_20240311-112437_Settings.png…]()
ill here

**Comment by minislel** [comment]
Here is the link to a screen recording showing the problem:
https://youtube.com/shorts/IY-a9jAKEbA

**Comment by OrangeZXZ** [comment]
> I have this option enabled and the problem is st
> ![Uploading Screenshot_20240311-112437_Settings.png…]()
> ill here

did you also enabled the links and disabled these links on your web browser and yt / yt music?

**Comment by OrangeZXZ** [comment]
> > I have this option enabled and the problem is st
> > ![Uploading Screenshot_20240311-112437_Settings.png…]()
> > ill here
> 
> did you also enabled the links and disabled these links on your web browser and yt / yt music?

![SmartSelect_20240311_112737_Settings.jpg](https://github.com/fast4x/RiMusic/assets/104271365/80a9576e-05b2-4f29-9039-c827cd2f40f7)

**Comment by minislel** [comment]
Yes, I did

**Comment by OrangeZXZ** [comment]
> Here is the link to a screen recording showing the problem: https://youtube.com/shorts/IY-a9jAKEbA

Oh i see then this is a Bug

**Comment by fast4x** [comment]
> Here is the link to a screen recording showing the problem:
> https://youtube.com/shorts/IY-a9jAKEbA

short link isn't supported for now, I'll add support.

**Comment by fast4x** [comment]
Link open from Link page in search?

**Comment by minislel** [comment]
> > > Here is the link to a screen recording showing the problem:
> > > https://youtube.com/shorts/IY-a9jAKEbA
> > 
> > 
> > short link isn't supported for now, I'll add support.
> 
> No. They screen recorded the bug and uploaded as short on YouTube to show us.

Exactly 💯

**Comment by minislel** [comment]
> Link open from Link page in search?

What do you mean

**Comment by fast4x** [comment]
I checked bug, i'ha added a fix and i think it work...
Available from version 0.6.26
