### ISSUE TITLE
Lag / Delay with switches

### ISSUE THREAD

**Issue by Quinxxxx** [fast4x/RiMusic#1021]
### Steps to reproduce the bug

1. Go to RiMusic settings
2. Find an option with a switch 
3. Toggle switch on

### Expected behavior

The switch should toggle on/off

### Actual behavior

The switch toggles on/off with either lag or some sort of short delay.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/88912716/5f6ed524-599e-4d49-9e26-ba7713571cd0

### RiMusic version

0.6.25

### Android version

Android 14

### Additional information

It seems to be an inconsistent issue that doesn't apply to all toggles.

**Comment by dAtA-TRoN** [comment]
This is not a bug, but rather normal behavior. The app operates in the background and loads the changes triggered by the switch.

**Comment by dAtA-TRoN** [comment]
This is not a bug, but rather normal behavior. The app operates in the background and loads the changes triggered by the switch.

**Comment by fast4x** [comment]
Delay generally is "applaying" in real time new settings...
