### ISSUE TITLE
Library enhancements

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1023]
### Description

I think library is a really important part of the app. So I always try to keep thinking of how it can be better. Here are some ideas I came up with. Sorry if some of these are unlikable. Also I intend to give more ideas about it in future.

### Suggested Solution

- Playlist adjustment buttons when tap and hold

Rename, Delete, Sort. To do each of those you have to enter playlist first.
So I think there should be a "tap and hold" feature to open playlist adjustment buttons pop-up from the library without opening any playlist.

- Separate playlist sorting

Each playlist can't be sorted separately. This makes us do extra work each time by change sorting each time we open different playlist. (Though I mostly just shuffle…I myself don't really use sorting inside playlist much…)

- Enqueue button

The enqueue button above playlist shouldn't be there. It should only appear when tapped on three dotted menu. Because I believe it's not really that necessary of a feature. At least not used often. 

- This space (not the whole) can be used, to place 2/3 most useful buttons:
![Screenshot_20240311-220946](https://github.com/fast4x/RiMusic/assets/85461823/2a9c601e-eba5-45c7-a08d-4c62814f490c)

For me those would be: Shuffle 🔀 and Search 🔎

### Additional Context

Should I make these tasks list? Or keep this way?

**Comment by fast4x** [comment]
All ok, except Separate playlist sorting because it's requires database modification, for now it's better not operate this, for maintaining maximum compatibility with ViMusic.

**Comment by fast4x** [comment]
Improved playlist in library, for now context menu in library will not develop.
Available from version 0.6.32
