### ISSUE TITLE
[Feature]: Synced lyrics sourced straight from YouTube Music

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#1024]
### Description

I know that there were few conversations about sources to find sources to add synced lyrics except KuGou and it seems that YouTube has brought in support for synced lyrics

### Suggested Solution

Source lyrics from YouTube music

**Comment by Nikks84** [comment]
It's possible?

**Comment by fast4x** [comment]
i don't know this, I'll check it

**Comment by fast4x** [comment]
I'll check

**Comment by fast4x** [comment]
Implemented, added new provider lyrics LrcLib.net.
Available from version 0.6.28.1

**Comment by VINULA2007** [comment]
@fast4x 
There are packages for unlimited YouTube and YouTube music given by many ISPs in my country and probably others 
So when I activate one of those packages on YouTube and YouTube music work
So lyrics won't work
That's why I asked to get lyrics straight from YouTube

**Comment by VINULA2007** [comment]
It works with YouTube only packages 🎊
Good job buddy

**Comment by VINULA2007** [comment]
Never mind
It doesn't work 😔

**Comment by fast4x** [comment]
it work or not?

**Comment by fast4x** [comment]
I'll check for YouTube specific lyrics synced

**Comment by VINULA2007** [comment]
> it work or not?
No
When I have a unlimited YouTube package (given by my ISP) I can only go to sites hosted by YouTube like YouTube iteself and YouTube music and ISP blocks access to other sites so lyrics sourced anywhere except YouTube doesn't work

**Comment by NikunjKhangwal** [comment]
I actually got synced lyrics. Also confirmed it from lrclib site.
![Screenshot_2024-04-02-08-59-26-528_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/99175083/b9524f20-c34f-42da-ba7e-20baef345d56)

**Comment by VINULA2007** [comment]
Oh
Then it's probably cause of my ISPs package that I mentioned above

**Comment by VINULA2007** [comment]
> Oh Then it's probably cause of my ISPs package that I mentioned above

Data is pretty expensive here
Also
![Screenshot_2024-04-02-09-17-39-029_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89296867/8b9fd6a3-0a3c-421f-a7f8-cda06ba355f4)
@NikunjKhangwal it works over normal data 
Thanks for the mention
