### ISSUE TITLE
[Feature]: Change highlighted lyric line position

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1025]
### Description

This is a small design change suggestion. Currently the highlighted line of lyrics is slightly on the upper part of the screen but i think it'll look more natural and will be easy to follow in exact middle.

### Suggested Solution

![IMG_20240312_001236](https://github.com/fast4x/RiMusic/assets/99175083/1dcb6b54-c61e-4087-ac6a-22bc8b62d81a)

**Comment by dAtA-TRoN** [comment]
Make sense to me.
