### ISSUE TITLE
Download music to your own files and a way to transfer playlist 

### ISSUE THREAD

**Issue by Mazzaick** [fast4x/RiMusic#1028]
### Description

I would really like if there a way to transfer playlist for youtube to rimusic. Cause when I search my playlist on rimusic there's is a lot like a lot of songs missing. And the other thing is to see if u guys could add an option to download music to your own phone ( like into your own files) 
Thanks for reading 

### Suggested Solution

I already said everything

**Comment by fast4x** [comment]
Hi, do you have a exported playlist file from Youtube Music?

**Comment by dAtA-TRoN** [comment]
> Hi, do you have a exported playlist file from Youtube Music?

I've created a demo playlist and utilized a third-party service to generate a CSV file from it. I'm confident that this service formatted the CSV correctly; otherwise, it wouldn't make sense. Although I initially planned to go through the official channel, using Google Checkout actually takes hours to days before you receive the files. If you're interested in knowing which third-party service I used, here's the link:

[TuneMyMusic](https://www.tunemymusic.com/de/transfer/youtube-to-file)

By the way: the dislike isn't from me 👀.

Playlist:

**Comment by fast4x** [comment]
Here we talk about playlists to import into RiMusic not to download files. RiMusic will never be a music downloader. I seem to have understood this, if instead the user talks about something else, this ticket can already be closed.

**Comment by sayyid5416** [comment]
> RiMusic will never be a music downloader.

I 100% agree with this. There are thousand ways to download videos/songs from youtube. If a video/music downloading to storage feature is added to the app, This app will be used by users for this feature solely, which is not a good thing for this app.

**Comment by Mazzaick** [comment]
> > Hi, do you have a exported playlist file from Youtube Music?
> 
> I've created a demo playlist and utilized a third-party service to generate a CSV file from it. I'm confident that this service formatted the CSV correctly; otherwise, it wouldn't make sense. Although I initially planned to go through the official channel, using Google Checkout actually takes hours to days before you receive the files -no joke. If you're interested in knowing which third-party service I used, here's the link:
> 
> [TuneMyMusic](https://www.tunemymusic.com/de/transfer/youtube-to-file)
> 
> Playlist: [YouTube_Music_(Demo_List).zip](https://github.com/fast4x/RiMusic/files/14567502/YouTube_Music_.Demo_List.zip)
> 
> When considering a music download feature, it might seem like a nice addition, but I wonder if this could potentially stir up a hornet's nest. While apps like "NewPipe" offer similar features, using a dedicated third-party app like RiMusic for such purposes might attract unwanted attention. There's a possibility that somewhere, a lawyer might feel compelled to put pen to paper in the darkest ink. Perhaps it's best to avoid this kind of functionality altogether. Just my two cents for the day 🤷🏻‍♂️.

U have a point

**Comment by Mazzaick** [comment]
> > Hi, do you have a exported playlist file from Youtube Music?
> 
> I've created a demo playlist and utilized a third-party service to generate a CSV file from it. I'm confident that this service formatted the CSV correctly; otherwise, it wouldn't make sense. Although I initially planned to go through the official channel, using Google Checkout actually takes hours to days before you receive the files -no joke. If you're interested in knowing which third-party service I used, here's the link:
> 
> [TuneMyMusic](https://www.tunemymusic.com/de/transfer/youtube-to-file)
> 
> Playlist: [YouTube_Music_(Demo_List).zip](https://github.com/fast4x/RiMusic/files/14567502/YouTube_Music_.Demo_List.zip)
> 
> When considering a music download feature, it might seem like a nice addition, but I wonder if this could potentially stir up a hornet's nest. While apps like "NewPipe" offer similar features, using a dedicated third-party app like RiMusic for such purposes might attract unwanted attention. There's a possibility that somewhere, a lawyer might feel compelled to put pen to paper in the darkest ink. Perhaps it's best to avoid this kind of functionality altogether. Just my two cents for the day 🤷🏻‍♂️.

Sorry for the late reply, I have my playlist already on cvc file. So how do I transfer that playlist to rimusic?

**Comment by Mazzaick** [comment]
> Hi, do you have a exported playlist file from Youtube Music?

Now I do 
Cvc file

**Comment by fast4x** [comment]
Upload here I'll check if possible to import

**Comment by dAtA-TRoN** [comment]
Was there something wrong with the CSV file I uploaded earlier 👀?

**Comment by fast4x** [comment]
I exported a playlist from the service, but the file it creates is incomplete because it does not contain song codes. Not uploadable in RiMusic.

**Comment by Mazzaick** [comment]
> I exported a playlist from the service, but the file it creates is incomplete because it does not contain song codes. Not uploadable in RiMusic.

Ok. Thanks anyway
