### ISSUE TITLE
[Feature]: sort favorites by artist (alphabetical)

### ISSUE THREAD

**Issue by Ao1Pointblank** [fast4x/RiMusic#1030]
### Description

The ability to sort favorited songs by artists is missing! (This is a feature in standard playlists)

### Suggested Solution

Please make the sorting options for Favorites playlist the same as standard playlists 

### Additional Context

![Screenshot_20240312-041115](https://github.com/fast4x/RiMusic/assets/88149675/3f0d1131-f69a-4862-b637-417b332f6ee6)

**Comment by fast4x** [comment]
ok thanks for request

**Comment by fast4x** [comment]
oh yes new ticket please

**Comment by fast4x** [comment]
Implemented, available from version 0.6.26
