### ISSUE TITLE
Dynamic theme background is switching between pure black and gray

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#1031]
### Steps to reproduce the bug

1. Activate dynamic theme
2. Play a song
3. Close the player

### Expected behavior

Should keep the black background 

### Actual behavior

Switches background between a gray one and a black one depending on the play state

### Screenshots/Screen recordings

Uploading Screenrecorder-2024-03-12-17-38-09-977.mp4…

### RiMusic version

0.6.25

### Android version

Android 14

**Comment by Nikks84** [comment]
Re upload video  So that it is easier to understand.

**Comment by VINULA2007** [comment]
https://github.com/fast4x/RiMusic/assets/89296867/f0086875-c792-465d-b534-d24fe97f3d53

**Comment by VINULA2007** [comment]
@fast4x did you fix it with #1012 ?

**Comment by fast4x** [comment]
Look my comment, it's just fixed in 0.6.26

**Comment by VINULA2007** [comment]
> Look my comment, it's just fixed in 0.6.26

OK 👍
