### ISSUE TITLE
lyrics Fullscreen window play button state is all over the place

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#1032]
### Steps to reproduce the bug

1. Play a song 
2. Open Fullscreen lyrics window 
3. Close it
4. Pause the song 
5. Reopen Fullscreen lyrics window 

### Expected behavior

Should show the button respective to the song playing state

### Actual behavior

Button shown is pretty random

### Screenshots/Screen recordings

Uploading Screenrecorder-2024-03-09-08-48-58-570.mp4…

### RiMusic version

0.6.25

### Android version

Android 14

**Comment by fast4x** [comment]
i not see, video uploaded is missing

**Comment by VINULA2007** [comment]
https://github.com/fast4x/RiMusic/assets/89296867/d8bc6d21-6a6e-4415-94e9-99382dbb46c5

**Comment by fast4x** [comment]
it's fixed and available from version 0.6.26

**Comment by VINULA2007** [comment]
Not fixed

https://github.com/fast4x/RiMusic/assets/89296867/733e172a-2e53-48f6-b8fd-32dfc598bf96

It shows pause in player and play in lyrics window

**Comment by fast4x** [comment]
Uhm, ok.

**Comment by VINULA2007** [comment]
https://github.com/fast4x/RiMusic/assets/89296867/7e268443-e8b8-475d-ac25-b7f966c5546a

Looks like a hard bug to fix

**Comment by fast4x** [comment]
Fixed, avaiable from version 0.6.29
