### ISSUE TITLE
App crash when I pause any song and leave the app in the recents, and when I open it again *after some time* the app opens , but when I tap on any song , it then crashes!! Not a bug , it happens everytime when I repeat the process , or maybe I don't know the correct definition of *what is a bug* 

### ISSUE THREAD

**Issue by Genuineuserhubro** [fast4x/RiMusic#1033]
### Steps to reproduce the bug

 pause any song and leave the app in the recents,
 open it again *after some time* 
the app opens  but
 tap on any song ,
 it then crashes!! 
  it *happens everytime* 

### Expected behavior

The paused music resets and when I tap on any song , I crashes.

### Actual behavior

I don't know man , you guys are the real deal you know 😹

### RiMusic version

Latest version 6.25 

### Android version

Android 13

**Comment by Vishcot** [comment]
@fast4x out of two i was able to record one repetitive crashing bug! 

Many times when i open app, 
library - favourites - i see all songs are showing as not downloaded which also indicates to me that it is going to get crash the on the next song click.
And just after clicking any song it crashes..
Then I reopen app and it shows all songs are downloaded well and then all songs plays well!

And now it is so much frequently happening..idk why.
Refer this vr below :

https://github.com/fast4x/RiMusic/assets/136909951/2dacfdca-5ea5-4548-89b4-7149ea223e02

I will try to record a search related to another crash bug also, if i would be able to predict specifically on which steps it is getting crashed.

_Originally posted by @Vishcot in https://github.com/fast4x/RiMusic/issues/982#issuecomment-1989348808_

**Comment by fast4x** [comment]
Please don’t get angry, have you enabled invincible service and disabled battery optimization ?

**Comment by Vishcot** [comment]
> Please don’t get angry, have you enabled invincible service and disabled battery optimization ?

Yeah, invincible service was on for me & battery optimisation was off as well.

&
Nobody's gonna get angry ever bro! Trust me! Even if you would kill me i am not gonna complain, you're doing amazing! Don't say this! Ask us, or at least ask me a thousand times! I would always answer humbly, your efforts are commendable! I am becoming fan of you day by day..🫡

**Comment by fast4x** [comment]
> @fast4x out of two i was able to record one repetitive crashing bug! 
> 
> Many times when i open app, 
> library - favourites - i see all songs are showing as not downloaded which also indicates to me that it is going to get crash the on the next song click.
> And just after clicking any song it crashes..
> Then I reopen app and it shows all songs are downloaded well and then all songs plays well!
> 
> And now it is so much frequently happening..idk why.
> Refer this vr below :
> 
> https://github.com/fast4x/RiMusic/assets/136909951/2dacfdca-5ea5-4548-89b4-7149ea223e02
> 
> I will try to record a search related to another crash bug also, if i would be able to predict specifically on which steps it is getting crashed.
> 
> _Originally posted by @Vishcot in https://github.com/fast4x/RiMusic/issues/982#issuecomment-1989348808_

So the problem may be the download service that doesn’t start properly. Thanks you gave me an important tip.

**Comment by Genuineuserhubro** [comment]
> Please don’t get angry, have you enabled invincible service and disabled battery optimization ?

In my case the songs are completely downloaded but the app still crashes , I think I should turn these on . I will let you know if it works. It feels good to have such a responsive developer 😄.

**Comment by fast4x** [comment]
My name is fast4x 😂😂

**Comment by rusunny123** [comment]
in the latest version ( 0.6.25 ) this problem is fixed...i had same type of problem before... Thanks Fast4x

**Comment by fast4x** [comment]
Ok perfect

**Comment by Genuineuserhubro** [comment]
> in the latest version ( 0.6.25 ) this problem is fixed...i had same type of problem before... Thanks Fast4x

Yes , same for me 🙂
