### ISSUE TITLE
songs with same name (from different artist) won't both appear in favorites

### ISSUE THREAD

**Issue by Ao1Pointblank** [fast4x/RiMusic#1034]
### Steps to reproduce the bug

Favorite two songs with the same name from different artists. 
Example: "Amnesia" by KMFDM and Miracle Of Sound

### Expected behavior

Both distinct songs should appear in the favorites playlist regardless of their titles. 

### Actual behavior

One song takes precedence and the other(s) don't show.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/88149675/b060b2c6-189a-4ba0-97ba-7029e2cec559

### RiMusic version

0.6.25

### Android version

14

### Additional information

I tried to rename one of the songs (assign custom local title), but it couldn't be confirmed and wouldn't save. I guess that will be another bug report. 

I also didn't test if this bug is case insensitive. 
(If Amnesia and AMNESIA are treated as distinct song titles)

**Comment by dAtA-TRoN** [comment]
Nice observation.

**Comment by fast4x** [comment]
WOW with compliments!
You have found two bugs, like special offer in supermarket 2x1 ahahahahaa 
Fixed available from version 0.6.26
