### ISSUE TITLE
Wait wait 

### ISSUE THREAD

**Issue by PIXIE-KEVIN** [fast4x/RiMusic#1038]
### Steps to reproduce the bug

Where is the old dynamic mode? I don't like the black mode. I wanted the old one. For God's sake, where is it? Brother, leave the dynamic mode separated from Black dynamic mode. For God's sake, leave the previous dynamic mode.

### Expected behavior

.

### Actual behavior

.

### RiMusic version

0.6.5

### Android version

Android 12

### Additional information

brother, dynamic mode is what many like but not black mode

**Comment by dAtA-TRoN** [comment]
It's already solved. Patience, wait for the next update.

**Comment by OrangeZXZ** [comment]
> ### Steps to reproduce the bug
> 
> Where is the old dynamic mode? I don't like the black mode. I wanted the old one. For God's sake, where is it? Brother, leave the dynamic mode separated from Black dynamic mode. For God's sake, leave the previous dynamic mode.
> 
> ### Expected behavior
> 
> .
> 
> ### Actual behavior
> 
> .
> 
> ### Screenshots/Screen recordings
> 
> _No response_
> 
> ### Logs
> 
> _No response_
> 
> ### RiMusic version
> 
> 0.6.5
> 
> ### Android version
> 
> Android 12
> 
> ### Additional information
> 
> brother, dynamic mode is what many like but not black mode

Already solved it only was a bug as expected when making updates every week 🤯
