### ISSUE TITLE
[Feature]: Miglioramento nella personalizazione dei colori

### ISSUE THREAD

**Issue by jaki444** [fast4x/RiMusic#104]
### Description

visto che sei italiano ti scrivo in italiano. Sarebbe bello offrire più personalizzazione riguardo l'aspetto grafico, una mia idea è oltre a scegliere il tema avere la possibilità di scegliere il colore tipo come in dynamic mode pero nella tema pureblack o modernblack.

### Suggested Solution

potresti aggiugere un selletore di colori. Anche per il colore dei pulsanti

**Comment by fast4x** [comment]
Ciao, si è un'ottima idea di cui si è parlato nell'area Discussioni.

**Comment by jaki444** [comment]
ok

**Comment by fast4x** [comment]
Ciao, prima di implementarlo, mi dai conferma? 
Vorresti poter scegliere Modalità tema > Chiaro, Scuro o Sistema anche con i temi PureBlack e ModernBlack?

**Comment by jaki444** [comment]
con entrambi scusa se ti rispondo ora ma lo ho letto ora

**Comment by OrangeZXZ** [comment]
Duplicate to #930 and #988

**Comment by fast4x** [comment]
Implemented customized colors theme, available from version 0.6.34
