### ISSUE TITLE
Icons and Animations in Font

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1042]
### Description

I have recently discovered that the loading animation on the boot of windows was always a font that changed characters very fast

![SmartSelect_20240312_210756_TikTok](https://github.com/fast4x/RiMusic/assets/104271365/1e42258c-ef19-4f8e-b3b8-adabcba708de)

It is made like this to work on any drivers and I think it is very clever

Some games also use fonts for icons instead of using images it alows easy use and optimisation (I think it is only a pain to implement and add icons)

### Suggested Solution

Maybe make a font with all the icons used and try to use it make separate font for animation when we would have that

### Additional Context

This is just an idea idk if it is realy practical since this is a android app and not windows

**Comment by OrangeZXZ** [comment]
This is the FlStudio font as an example how it should look (but with RiMusic Icons)

![SmartSelect_20240312_212137_TikTok.jpg](https://github.com/fast4x/RiMusic/assets/104271365/2f45ae19-c25d-436b-8827-b1605f4c11c0)

**Comment by OrangeZXZ** [comment]
> But that for what?

Instead of using images for the icons they could be text it is better maybe for the burger menu or the song name etc...

That way you can have something like this:

A (Filled disk icon) [Song Name] (variable)
B (Artists icons) [Artists] (variables)

It was just an idea maybe it is useless

**Comment by OrangeZXZ** [comment]
> > But that for what?
> 
> Instead of using images for the icons they could be text it is better maybe for the burger menu or the song name etc...
> 
> That way you can have something like this:
> 
> "A (Filled disk icon) [Song Name] (variable)"
> "B (Filled Artists icon) [Artists] (variables)"
> 
> It was just an idea maybe it is useless

You could also make all the text clickable + you used just one object for showing the icon and the name of the song (if you can use multiple fonts per line)

**Comment by fast4x** [comment]
Ahhhhhh i can try, I'm not sure it work on Kotlin.

**Comment by OrangeZXZ** [comment]
> Ahhhhhh i can try, I'm not sure it work on Kotlin.

It would be perfect for menus with options too
