### ISSUE TITLE
Missing "Go to Album" entry in context menu within playlists. Some albums fail to load.

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1043]
### Steps to reproduce the bug

1. Open the app and search for a song within a playlist where the "Go to Album" entry is missing from the context menu.

_If you can't find any:_
_an example song for this misconduct is "Emil Rottmayer - Descend"_

2. Attempt to navigate to the "Album" tab via "More of Artist" and select the album. Observe that the album does not load.

3. Search directly for the album and go to the "Song" tab. Notice that all tracks of the album are displayed and playable.

### Expected behavior

• The "Go to Album" entry should be available in the context menu of every song within a playlist (of course only if it is part of an album).

• The corresponding album should load when selected.

### Actual behavior

• The "Go to Album" entry is missing in the context menu of certain songs.

• The album does not load when selected via _Artist Page -> Album Tab -> Album_

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/71184627/ff522106-b7be-48f2-ae45-940151848aa1

The album used as an example in the video is listed without any issues on the official YouTube Music app. Additionally, it does not have any age restrictions:

![Screenshot_2024-03-13-05-18-05-15.jpg](https://github.com/fast4x/RiMusic/assets/71184627/4b9e4b60-790e-410c-bfc5-cea2c6c5a433)

### RiMusic version

0.6.25

### Android version

Android 13

### Additional information

I've noticed that in the context menu of certain songs in the RiMusic app, the "Go to Album" entry is missing. However, when I navigate to the "Album" tab via "More of Artist", the corresponding album is present. But when attempting to select the album, it fails to load. This issue occurs with all songs where the "Go to Album" entry is missing from the context menu. **Another observation is that if I search directly for the album and go to the "Song" tab, all tracks of the album are displayed and playable.**

**Comment by fast4x** [comment]
Go to album work with original songs because have album code. 
In this case, verify in player if song name have alert icon.

**Comment by dAtA-TRoN** [comment]
I can't see any alert icon:

![Screenshot_2024-03-13-06-13-57-83_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/ed049a91-446c-40a1-8aba-7e1dff9b26e7)

**Comment by fast4x** [comment]
So it occur from artist page after a search... ok

**Comment by dAtA-TRoN** [comment]
Right. In playlist song context menu:

More of 'artist'  -> Album Tab

Select the relevant album and it won't load.

**Comment by fast4x** [comment]
Nice, I'll check it

**Comment by dAtA-TRoN** [comment]
Right. In playlist song context menu:

More of 'artist'  -> Album Tab

Select the relevant album and it won't load.

You don't have to go through the playlist. You can also go directly to the artist overview.The playlist context menu only reveals the albums that have the corresponding error in that the "Go to Album" entry is missing.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.26

**Comment by dAtA-TRoN** [comment]
> Fixed, available from version 0.6.26

Wow, purely out of curiosity, could you please explain to me in one sentence, and in simple terms, what the problem was 😲?

**Comment by dAtA-TRoN** [comment]
> > Fixed, available from version 0.6.26
> 
> Wow, purely out of curiosity, could you please explain to me in one sentence, and for dummies, what the problem was 😲? By the way: you are awesome, dude! AWESOME 🤘🏼💪🏼👌🏼👏🏼🤙🏼!!!!

**Comment by dAtA-TRoN** [comment]
Thanks! You're doing God's work, man 👏🏼😀. Keep it going!

**Comment by fast4x** [comment]
> Thanks! You're doing God's work, man 👏🏼😀. Keep it going!

exaggerated

**Comment by fast4x** [comment]
Thanks

**Comment by dAtA-TRoN** [comment]
Unfortunately this bug still exists.

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/d9b0d2a8-4fa7-4cdf-9662-a03bc425be97

look...

**Comment by dAtA-TRoN** [comment]
Ok 😳. So what do we do now!?

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/9d58ba55-b774-499c-864e-265b1e875ee3

https://github.com/fast4x/RiMusic/assets/1484476/12196a3f-fff9-4665-b47c-60ee8ca1496c

**Comment by dAtA-TRoN** [comment]
Nothing has changed for me at all. Strange.

**Comment by dAtA-TRoN** [comment]
Could it have something to do with region settings?

**Comment by fast4x** [comment]
try to remove artist and readd it as preferite

**Comment by dAtA-TRoN** [comment]
> readd it as preferite

What do you mean with that?

**Comment by fast4x** [comment]
ago in home > Artists, remove from your preferite, search it and follow

**Comment by dAtA-TRoN** [comment]
> ago in home > Artists, remove from your preferite, search it and follow

I didn't subscribe to this artist. I just have songs from him in my playlists.

**Comment by dAtA-TRoN** [comment]
Can you tell me how to properly uninstall RiMusic? I just tried uninstalling and then reinstalling it, but I noticed that the settings were still saved.
