### ISSUE TITLE
I Request for two different releases, (Beta-Stable)

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#1047]
### Steps to reproduce the bug

Same as below.

### Expected behavior

@fast4x

I am experiencing issues with adding songs to my favorites. This is very frustrating for me. I am unable to add songs to my favorites anymore, and the "Play next in favorites" feature is not working as well. I am also encountering random crashes when I click on songs, search, or perform any action. At times, songs cannot be deleted, and using the "download all" button causes the entire player to hang until all songs are downloaded.

While I appreciate the quick implementation of new features and your active involvement, I believe that the rapid implementation without proper analysis is causing these bugs to surface. It is challenging to pinpoint why these issues are occurring.

### Actual behavior

Same as above..

### RiMusic version

0.6.25

### Android version

Android 14

**Comment by fast4x** [comment]
Dear, you have to be patient because bugs are part of the game, I’m sorry that you have problems, be patient a bit because the development flow is well defined, there are no new features but a gradual improvement overall.

I hope that much of what you report is resolved in the next version, not all.

**Comment by Vishcot** [comment]
> Dear, you have to be patient because bugs are part of the game, I’m sorry that you have problems, be patient a bit because the development flow is well defined, there are no new features but a gradual improvement overall.
> 
> I hope that much of what you report is resolved in the next version, not all.

@fast4x 

I agree that bugs are a part of the process, but I feel that if the implementation is rushed, it is necessary to separate the development stage from the stable public stage. This approach would involve transitioning the app from the beta version to the stable version once it appears stable after implementing new features. This way, users who prefer beta updates can continue to receive them, while those who only want a stable app can rely on the public stable release.

**Comment by fast4x** [comment]
You’re right, and that’s what I do in my job. RiMusic development for passion, is not a business job so a single stream for the moment is enough. Users need to have patience, the right patience required for a simple and little opensource project.

**Comment by Vishcot** [comment]
> You’re right, and that’s what I do in my job. RiMusic development for passion, is not a business job so a single stream for the moment is enough. Users need to have patience, the right patience required for a simple and little opensource project.

Ah, i see.
No issues..it was just my suggestion.
No issues at all..💯
