### ISSUE TITLE
I know I am petty 😅...

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1049]
### Description

"What should I do, I just noticed it 🤷🏻‍♂️😅."

### Suggested Solution

I believe that requires no further words.
Just take a look at the screenshot...

![ZomboDroid_13032024094905](https://github.com/fast4x/RiMusic/assets/71184627/b6e12ab7-4ebf-4d3d-885e-f286219ef946)

### Additional Context

Am I about to get kicked out now 😂👀!?

**Comment by fast4x** [comment]
Given look

**Comment by dAtA-TRoN** [comment]
Addendum:
I've taken a closer look now:

Only the first two top icons have rounded backgrounds. For the subsequent six icons, the background graphics suddenly resemble a pill shape. And as mentioned earlier, the search icon at the end appears square. It would be great if all the icons could have uniformly rounded backgrounds. This would standardize the design and simply look better.

![IMG_20240314_065249.jpg](https://github.com/fast4x/RiMusic/assets/71184627/bb607e27-007a-4d2b-942d-ee98bb184441)

**Comment by sayyid5416** [comment]
How did you even find it. I thought every icon had _**pill**_

**Comment by dAtA-TRoN** [comment]
> How did you even find it. I thought every icon had _**pill**_

My original response was kind of dry, so I asked ChatGPT to make it a bit more interesting. Well, now it's almost turned into a thriller 😂:

As I was browsing on my smartphone, it happened: My slightly tired thumb accidentally slid onto the search button and lingered there for a brief moment - and suddenly the rectangular monster appeared right before my eyes, disturbing my peace. This piqued my curiosity. I couldn't help but scrutinize the other buttons more closely...

**Comment by sayyid5416** [comment]
> My original response was kind of dry, so I asked ChatGPT to make it a bit more interesting. Well, now it's almost turned into a thriller 😂:
> 
> As I was browsing on my smartphone, it happened: My slightly tired thumb accidentally slid onto the search button and lingered there for a brief moment - and suddenly the rectangular monster appeared right before my eyes, disturbing my peace. This piqued my curiosity. I couldn't help but scrutinize the other buttons more closely...

I asked chatGPT to reply to this, and here's your reply 🤦:

"_Ah, the saga unfolds! Your journey into the labyrinth of UI anomalies sounds like a thriller indeed! The suspense builds as your thumb, weary yet determined, inadvertently awakens the rectangular beast from its digital slumber. With bated breath, you delve deeper, scrutinizing each icon as if they hold the key to unlocking a hidden realm. Bravo, my friend, for embarking on this exhilarating quest for UI perfection! Who knows what other mysteries await in the digital abyss? 🕵️‍♂️💻_"

**Comment by dAtA-TRoN** [comment]
Hahahaha that's so ridiculous 😂.
Brave new world.
