### ISSUE TITLE
[Feature]: Possibilita di aggiungere canzoni dai propi file.

### ISSUE THREAD

**Issue by jaki444** [fast4x/RiMusic#105]
### Description

Sarebbe bello se riuscissi a aggiungere la possibilita di mettere canzoni da dai propie file personali ed integrarli nelle playlist.

### Suggested Solution

Aggiungere un campo alla ricerca chiamato file personali, musica del dispositivo ecc...

**Comment by fast4x** [comment]
File del tipo MP3 o altro tipo?

**Comment by jaki444** [comment]
Si MP3 o WAV quelli base ecco.

**Comment by fast4x** [comment]
Ho aggiunto la musica dal dispositivo, prossime versioni completo il resto prima possibile.

**Comment by jaki444** [comment]
Grazie mille

**Comment by fast4x** [comment]
Implemented, available from version 0.6.13
