### ISSUE TITLE
Gradient Theme

### ISSUE THREAD

**Issue by col1iv** [fast4x/RiMusic#1051]
### Description

I love the dynamic theme on the app, but the pure black coloring on the player just makes it look a bit "dead."

### Suggested Solution

I have made an concept on PicsArt (lol) of how I think it should look :)
![Picsart_24-03-13_22-22-20-347](https://github.com/fast4x/RiMusic/assets/152646768/36a651aa-e1f3-45c0-b756-27870650728c)

### Alternatives

Maybe it could be optional? Like the pure dark amoled theme and this gradient theme!

### Additional Context

thx for making a great app lol

**Comment by dAtA-TRoN** [comment]
No lies, it looks pretty dope 🤙🏼.

**Comment by fast4x** [comment]
interesting

**Comment by fast4x** [comment]
Implemented gradient background in player, enable/disable by player appearance setting, default disabled.
Available from version 0.6.26

**Comment by fast4x** [comment]
It work in all themes...
