### ISSUE TITLE
Strange button rotation animation

### ISSUE THREAD

**Issue by 821938089** [fast4x/RiMusic#1054]
### Steps to reproduce the bug

Click the play button

### Expected behavior

only the play button rotation animation

### Actual behavior

The previous/next song buttons also rotating animation

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/8674809/f20a1dae-9a35-4095-a63f-a35c084a7acf

### RiMusic version

0.6.25

### Android version

Android 14

**Comment by Nikks84** [comment]
When you play or pause songs its rotating the buttons  this is also expected behavior not a bug
If you do not want, you can turn it off from the settings player appearance.

**Comment by dAtA-TRoN** [comment]
![IMG_20240314_051903.jpg](https://github.com/fast4x/RiMusic/assets/71184627/6bebfab9-8633-4549-ba4b-9982f47e961c)

**Comment by OrangeZXZ** [comment]
This is just a funny feature by default à lot of people dont like it personally i dont use it Maybe make it off by default?

**Comment by 821938089** [comment]
Okay, I think the damn option should be turned off by default.
Nonetheless, with this option turned on, I think only clicking the button will rotate it, not all buttons.

**Comment by dAtA-TRoN** [comment]
> I also think that only the button pressed should spin maybe it would make the feature better?

But you would hardly be able to see any of it because the animation would be covered by your own finger.

**Comment by OrangeZXZ** [comment]
> > I also think that only the button pressed should spin maybe it would make the feature better?
> 
> But you would hardly be able to see any of it because the animation would be covered by your own finger. But I know what you mean. Maybe if the buttons were bigger.

a longer animation can change that I think

**Comment by dAtA-TRoN** [comment]
> a longer animation can change that I think

Yeah, this could do the trick 🤷🏻‍♂️.
