### ISSUE TITLE
Incorrect display of the language setting in the settings after the app is installed for the first time

### ISSUE THREAD

**Issue by 821938089** [fast4x/RiMusic#1055]
### Steps to reproduce the bug

Install the app and open the settings

### Expected behavior

The language setting should be shown as the system language or the current language

### Actual behavior

The language setting are shown in English

### Screenshots/Screen recordings

![Screenshot](https://github.com/fast4x/RiMusic/assets/8674809/c9bccb8f-966d-4683-a5ba-d9f6bdfb3107)

### RiMusic version

0.6.25

### Android version

Android 14

**Comment by Nikks84** [comment]
When you install the app, the language selected by default English, you can change it later, from the language setting, I don't think this is a bug.

**Comment by dAtA-TRoN** [comment]
I think he actually wanted to point out a new feature: the default language should be based on the system language. And I think that's a good idea. Not everyone can speak English.

**Comment by Nikks84** [comment]
🤷🏻‍♂️ Maybe.

**Comment by dAtA-TRoN** [comment]
@821938089
Okay, so this feature is actually already present. What you mean is that there are still English text snippets in the headings of the various settings. I assume either the translation isn't quite complete yet, or, and I think this is more likely, there have been complications incorporating the special characters of your language into the headings. There probably needs to be some further adjustment to make it work properly. The developer should definitely look into that. Good point.

**Comment by dAtA-TRoN** [comment]
@821938089
Okay, so this feature is actually already present. What you mean is that there are still English text snippets in the headings of the various settings. Basically, it's because the translation hasn't advanced enough yet. This happens in my language too. Whenever there are new features, they're initially added in English to the app. Then, translators work on it, and it's usually translated in one of the next updates. So just be patient.

**Comment by 821938089** [comment]
@dAtA-TRoN 
You misunderstood me, I meant that it is not displayed correctly here.
![image](https://github.com/fast4x/RiMusic/assets/8674809/147fcaed-6863-4741-b659-cea7b36838cb)
This should not "English".

**Comment by dAtA-TRoN** [comment]
Oh, now I understand. Even though your language is selected, it still says that the language "English" would be selected, right? Yes, someone should definitely look into that.

**Comment by dAtA-TRoN** [comment]
> But I'm using the same version of the app. Why am I not having this bug?
> Nvm…probably because of Android version difference…


I have no idea, it's a mystery 😵‍💫😁.

**Comment by 821938089** [comment]
@dAtA-TRoN No, it's when you open the settings after installing the app for the first time, where it says "English", but that's not right.

**Comment by dAtA-TRoN** [comment]
> @dAtA-TRoN No, it's when you open the settings after installing the app for the first time, where it says "English", but that's not right.

So when you close right after installation and open it once again, then it's automatically corrected?

**Comment by dAtA-TRoN** [comment]
> Try changing it then.

"I've come to understand that while the app initially sets the correct system language upon installation, when accessing the options, it still displays the word 'English'."

**Comment by dAtA-TRoN** [comment]
No idea. I tried to understand him and gave up now.

**Comment by dAtA-TRoN** [comment]
It's okay, I just find the whole thing very confusing, and it's starting to annoy me. That's why I've decided to step back from this.

**Comment by fast4x** [comment]
This isn't a bug, first language must be set manually.
