### ISSUE TITLE
Incorrect background color for dynamic themes in dark mode

### ISSUE THREAD

**Issue by 821938089** [fast4x/RiMusic#1056]
### Steps to reproduce the bug

Play a random song

### Expected behavior

Background color should be relevant to the song cover

### Actual behavior

Background color changes to black

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/8674809/b10bc61e-d15c-4c2b-a928-90c8ce5f7d3c

### RiMusic version

0.6.25

### Android version

Android 14

### Additional information

Not quite sure if this is the expected behavior, but it's different from ViMusic and I'm not using the PureBlack theme, which I don't think should be black.
The background color before it starts playing is not black either.

The color of the buttons in the lower right corner also becomes incorrect during playback, making it difficult to make a distinction from the background.

![1](https://github.com/fast4x/RiMusic/assets/8674809/21a265e5-b4a6-44cf-a961-11c0b1bfd78c)
![2](https://github.com/fast4x/RiMusic/assets/8674809/fdb6ef1a-d6fa-428a-8190-2880920c85c4)

**Comment by dAtA-TRoN** [comment]
That's already fixed and will be included in tomorrow's update. Please check first if your issue has already been addressed before opening a new thread.

**Comment by 821938089** [comment]
Are you sure? I installed the latest CI build of the app and still have this problem.

**Comment by dAtA-TRoN** [comment]
> Are you sure? I installed the latest CI build of the app and still have this problem.

#1031
