### ISSUE TITLE
Different fonts for the top header and sidebar header in the settings

### ISSUE THREAD

**Issue by 821938089** [fast4x/RiMusic#1057]
### Steps to reproduce the bug

Open Settings

### Expected behavior

Use fonts consistent with sidebar headings

### Actual behavior

Different fonts for the top header and sidebar header in the settings

### Screenshots/Screen recordings

![Screenshot](https://github.com/fast4x/RiMusic/assets/8674809/ecf507e3-a603-4dbe-b9c2-2a50de0f41f8)

### RiMusic version

0.6.25

### Android version

Android 14

**Comment by dAtA-TRoN** [comment]
Please familiarize yourself with the app before opening numerous new threads here. Many of your concerns would have been self-explanatory if you had taken a closer look at the app beforehand.

![IMG_20240314_060301.jpg](https://github.com/fast4x/RiMusic/assets/71184627/4acf7826-eec4-49d0-811d-cf3de8f9d0aa)

**Comment by 821938089** [comment]
My font type setting is already Rubik and is not turned on to use the system fonts, the top title bar is still using the system fonts.

https://github.com/fast4x/RiMusic/assets/8674809/0bbd179d-d329-4ad7-a85a-b9565b780466

**Comment by dAtA-TRoN** [comment]
@821938089 

> My font type setting is already Rubik and is not turned on to use the system fonts, the top title bar is still using the system fonts.

Understood, that should be looked into.

However, please close all threads from your end that were unnecessary to keep it organized.

**Comment by dAtA-TRoN** [comment]
> Do you have \"Use system font\" turned on?

Good point, I hadn't considered that. He must have configured it that way.

**Comment by fast4x** [comment]
Improved text style in navigation tabs, there was something different.
Available from version 0.6.26

**Comment by 821938089** [comment]
After I updated 0.6.26.1, why is the sidebar using the system font as well? I want it to use the built-in fonts.

**Comment by fast4x** [comment]
I didn’t notice it
