### ISSUE TITLE
Enhancing RiMusic Settings with a Search Bar

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1059]
### Description

RiMusic already offers users a diverse range of settings, but navigating through them can sometimes be cumbersome. To streamline this process and elevate user experience, I propose integrating a search bar. With this feature, users can effortlessly locate specific settings instead of sifting through lengthy menus.

Mockup:

![IMG_20240314_174129](https://github.com/fast4x/RiMusic/assets/71184627/1b08358c-a343-4e8e-aeb2-1b0440db5c11)

### Suggested Solution

The search bar will be prominently positioned at the top of the settings page for easy access. It will boast real-time functionality, updating results dynamically as users type. Search results will promptly display relevant settings or options, enabling users to swiftly navigate to their desired items.

By implementing a search bar in RiMusic settings, we aim to enhance usability and simplify the user journey, particularly given the app's expanding feature set.

### Additional Context

The addition of a search bar in RiMusic settings will:

• Facilitate seamless navigation through settings.

• Improve discoverability of specific settings, especially within extensive lists.

• Enhance overall efficiency by reducing time spent navigating menus.

• Offer a more modern and intuitive user interface, aligning with industry standards and user expectations in the music streaming landscape.

**Comment by fast4x** [comment]
It's nice feature also requested by other tickets, but not simple to implement... i'll check simple solution...
Like always, big problem require simple solution. :)

**Comment by fast4x** [comment]
Implemented in ui and appearance settings, available from version 0.6.26

**Comment by dAtA-TRoN** [comment]
> Implemented in ui and appearance settings, available from version 0.6.26

https://github.com/fast4x/RiMusic/assets/71184627/bd7d55c6-2cd4-43b8-b753-c03234fa836c

**Comment by dAtA-TRoN** [comment]
> Implemented in ui and appearance settings, available from version 0.6.26

https://github.com/fast4x/RiMusic/assets/71184627/cdbc5e95-3c0d-4266-9557-0b8b6d77627a
