### ISSUE TITLE
Song from artist page is not adding to favorites list in Library 

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1061]
### Steps to reproduce the bug

1. Go to artist page from home
2. Select any artist
3. Go to songs section in artist page
4. Select any song and add to favorites
5. Then go to home
6. Then to library
7. Then to favorites. You may notice song is not added to favorites.
![IMG_20240315_000041](https://github.com/fast4x/RiMusic/assets/148480722/2196994d-79f4-4687-b060-e762f189c5ad)
![IMG_20240315_000114](https://github.com/fast4x/RiMusic/assets/148480722/b23963cb-82c2-4111-a107-7d2cc3fed861)

### Expected behavior

After clicking on favourite icon it should added to my favourite songs in library 

### Actual behavior

but not added

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/148480722/d5005206-ab30-4e59-b08c-a0d3aa8a6a90

### RiMusic version

0.6.25

### Android version

Android 13

**Comment by fast4x** [comment]
Fixed in next version 0.6.26

**Comment by SureshTimma** [comment]
Tq

**Comment by SureshTimma** [comment]
> Fixed in next version 0.6.26

Can you implement backup to Google drive? Bot theme(app settings) and songs

**Comment by fast4x** [comment]
I'm sorry but isn't planned develop any login.

**Comment by SureshTimma** [comment]
> I'm sorry but isn't planned develop any login.

Atleast add backup option for app theme and settings

**Comment by fast4x** [comment]
Yes

**Comment by SureshTimma** [comment]
> Yes

Is it possible to automatically backup to local device option?

**Comment by fast4x** [comment]
I'm not sure
