### ISSUE TITLE
Most of the featured playlist shows as null 0-0 songs 

### ISSUE THREAD

**Issue by RABINGG** [fast4x/RiMusic#1063]
### Steps to reproduce the bug

Goto a genre in the discovery page
Open some of the featured playlist
Most of them will result in this
I mostly go to tamil genre 

### Expected behavior

The songs in the Playlist should be shown 

### Actual behavior

The page shows as null 0-0 songs with a page loading animation

### Screenshots/Screen recordings

![image](https://github.com/fast4x/RiMusic/assets/100079543/4d17bae8-252d-4a94-b150-bc0ef2ea5e14)

### RiMusic version

0.6.25

### Android version

14

**Comment by SureshTimma** [comment]
Same here

**Comment by SureshTimma** [comment]
Almost all playlists in Telugu language displaying null error
![Screenshot_2024-03-16-12-49-26-47_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/148480722/9fd17b0b-2f29-428e-b645-04f77eb19dfc)

**Comment by fast4x** [comment]
I

Yes, page is loaded from YTM content using system language, I'll try another way. Can you share here a link to playlist with null trouble?

**Comment by SureshTimma** [comment]
> I
> 
> Yes, page is loaded from YTM content using system language, I'll try another way. Can you share here a link to playlist with null trouble?

https://youtube.com/playlist?list=RDCLAK5uy_n0a1W54UyoGGn07f8CqYeQoXt2bhmgRPM&playnext=1

**Comment by SureshTimma** [comment]
> 
I think all YouTube featured playlists @fast4x 

![IMG_20240316_145240.jpg](https://github.com/fast4x/RiMusic/assets/148480722/57a389bc-96cd-4651-9dbd-a5f8f9001fc3)

**Comment by fast4x** [comment]
ok

**Comment by fast4x** [comment]
Fixed, available from version 0.6.29
