### ISSUE TITLE
Adaptive width of labels in discovery page

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1066]
### Description

![Screenshot_2024-03-15-18-13-39-12_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/148480722/0b909d33-bf06-4ddc-be2a-10dc320401d9)

### Suggested Solution

Labels with few words also taking to much width. So it's difficult to navigating to all labels by swiping. 

Instead add adaptive width and scrolling down (not swiping left)

And another feature. In discovery page i couldn't find a single "new album" related to my interest or language of songs. Please make sure it will show new albums of my language or songs intrested

**Comment by sayyid5416** [comment]
**_fast4x_** I opened app on my phone, and it's showing exactly these albums as in ss. How these `New Albums` are chosen?

**Comment by fast4x** [comment]
It is a list that is composed by YTM

**Comment by SureshTimma** [comment]
> It is a list that is composed by YTM

Ok

**Comment by SureshTimma** [comment]
> **_fast4x_** I opened app on my phone, and it's showing exactly these albums as in ss. How these `New Albums` are chosen? 

Yes, that was my problem too

**Comment by fast4x** [comment]
Also here is a list created by YTM, does not create it RiMusic

**Comment by fast4x** [comment]
Discovery uses the system language.

**Comment by sayyid5416** [comment]
> > **_fast4x_** I opened app on my phone, and it's showing exactly these albums as in ss. How these `New Albums` are chosen?
> 
> Yes, that was my problem too

I don't think it will be solved without YouTube personalization, which means sending analytics data to YT _(and I don't think it's going to happen anytime soon)_ .
