### ISSUE TITLE
Icons are confusing, change stats icon from top

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1067]
### Description

![IMG_20240315_184236](https://github.com/fast4x/RiMusic/assets/148480722/f9c92083-d608-44f8-8a15-fb6f2793a52c)

### Suggested Solution

Icons are very confusing, please think for dny solution.

And remove stats icon from the top of icons. 

Icons changing positions in settings page, home page, artist page and home page

Please make permanent icons settle in one place and add other icons in their pages

**Comment by fast4x** [comment]
Stat icon where add?

**Comment by SureshTimma** [comment]
> Stat icon where add?

Into Library or settings page

**Comment by SureshTimma** [comment]
> Stat isn't a playlist, Library not right place

Atleast add below of all icons

**Comment by SureshTimma** [comment]
> Stat isn't a playlist, Library not right place

One more thing, there is a new app store indus app store by India. Do you want to publish this app there. It's free of charge i think

**Comment by SureshTimma** [comment]
> Stat isn't a playlist, Library not right place

Same logo for app and user interface, quick picks and quick pics settings are confusing
![IMG_20240315_191715.jpg](https://github.com/fast4x/RiMusic/assets/148480722/7f2191a4-b7d0-4bd0-863a-2f8699d10b35)

**Comment by SureshTimma** [comment]
> Stat isn't a playlist, Library not right place

![IMG_20240315_192620.jpg](https://github.com/fast4x/RiMusic/assets/148480722/efb46dd3-fa11-43a2-a373-98bf9de7027d)

Main heading should be settings and user interface should be as subscribed heading. Because we enter settings page from home

**Comment by SureshTimma** [comment]
> Stat isn't a playlist, Library not right place

Best place for stats icon will be the place between search and settings icon.

![IMG_20240315_193057.jpg](https://github.com/fast4x/RiMusic/assets/148480722/121a91b9-bdf8-4dd8-b8bc-49c40760de8e)

**Comment by dAtA-TRoN** [comment]
I wholeheartedly agree with the man. He addresses issues that have subtly bothered me as well, although I couldn't quite put my finger on them. In fact, I find every suggestion here to be excellent, and I believe they would significantly improve the app.

**Comment by SureshTimma** [comment]
> I wholeheartedly agree with the man. He addresses issues that have subtly bothered me as well, although I couldn't quite put my finger on them. In fact, I find every suggestion here to be excellent, and I believe they would significantly improve the app.

Thank you

**Comment by sayyid5416** [comment]
> > Stat isn't a playlist, Library not right place
> 
> Best place for stats icon will be the place between search and settings icon.

I think **_"between search and settings icon"_** would not be a great place. Icon should be in the **_navigation bar_**. I've two suggestions:

1. Adjust the **_padding/margin_** of the icon to match that of the other buttons in the navigation bar. Currently, it appears to have excess padding/margin like `settings` button, making it inconsistent with other buttons in navigation bar.

2. Consider **_relocating the icon_** to a position below either the `library` or `discover` button. This adjustment could enhance the visual hierarchy and flow of the navigation bar, ensuring that the icon is more seamlessly integrated into the overall design.

**Comment by fast4x** [comment]
But how much have you written? I don’t need a day to read and understand! ahahahaah

**Comment by sayyid5416** [comment]
> But how much have you written? I don’t need a day to read and understand! ahahahaah

true. will mind it in future 👍

**Comment by SureshTimma** [comment]
@fast4x 

Here you used album icon for song. Could you please change it to song icon![IMG_20240316_150353.jpg](https://github.com/fast4x/RiMusic/assets/148480722/703fcc23-9f98-45b7-a5ac-ffbc06ffc22b)

**Comment by dAtA-TRoN** [comment]
> Here you used album icon for song. Could you please change it to song icon

Man, how do you guys always notice stuff like that 🤔?

**Comment by fast4x** [comment]
Not because click on it go to album...

**Comment by sayyid5416** [comment]
> Not because click on it go to album...

Wow! I didn't even know this function existed.

**Comment by fast4x** [comment]
like on artist...

**Comment by SureshTimma** [comment]
> @fast4x 

Bro below app has cleanest ui so far now I'm Exploring different YouTube and Spotify clients. Don't mistaken me please. Copy any features useful for our app from their repo if you can and if you have time.

https://songtube.github.io/

**Comment by dAtA-TRoN** [comment]
I tried it. The music search didn't work. So I uninstalled it again.

**Comment by fast4x** [comment]
> > @fast4x 
> 
> Bro below app has cleanest ui so far now I'm Exploring different YouTube and Spotify clients. Don't mistaken me please. Copy any features useful for our app from their repo if you can and if you have time.
> 
> https://songtube.github.io/

The important thing is not to think that RiMusic becomes a clone of another software.

**Comment by sayyid5416** [comment]
> > > @fast4x
> > 
> > 
> > Bro below app has cleanest ui so far now I'm Exploring different YouTube and Spotify clients. Don't mistaken me please. Copy any features useful for our app from their repo if you can and if you have time.
> > https://songtube.github.io/
> 
> The important thing is not to think that RiMusic becomes a clone of another software.

I 100% agree with this.

**Comment by SureshTimma** [comment]
> I tried it. The music search didn't work. So I uninstalled it again.

Yes I accept but ui is clean. So I mentioned.

**Comment by SureshTimma** [comment]
> > > @fast4x 

> The important thing is not to think that RiMusic becomes a clone of another software.

Ok. But inspiring from others innovations is not a crime. Anyways I respect your hard bro.

**Comment by fast4x** [comment]
Of course, inspiring is not cloning.
