### ISSUE TITLE
Play icon loses it's background graphic when new gradient background is activated

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1070]
### Steps to reproduce the bug

1. Activate the new background gradient effect.

2. Navigate to the player.

3. Notice that the play icon loses its background graphic.

### Expected behavior

The play icon should retain its background graphic even when the new background gradient is activated in the player.

### Actual behavior

Upon activating the new background gradient effect, the play icon loses its background image within the player view, appearing as a standalone play icon without any background. This behavior persists as long as the background gradient effect is enabled.

### RiMusic version

0.6.26

### Android version

13

**Comment by fast4x** [comment]
Fixed, available from version 0.6.27
