### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Lllum** [fast4x/RiMusic#1071]
### Steps to reproduce the bug

Opening the app in general

### Expected behavior

The app isn't supposed to crash when I open it

### Actual behavior

It crashes everytime I open it 

### RiMusic version

0.6.26

### Android version

8.1.0

### Additional information

Whenever I open the app and click on Playlist, the app crashes while I'm scrolling down my Playlist.
It also crashes when a song is playing while my phone is off and then the song ends or I open my phone again.

**Comment by fast4x** [comment]
Yes bug confirmed, Soon I publish the new version

**Comment by dAtA-TRoN** [comment]
> Yes bug confirmed, Soon I publish the new version

And don't worry about the 'Go to album' thing. Somehow, it sorted itself out. Just wanted to let you know.

**Comment by fast4x** [comment]
Excellent! Thank you, obviously the code has been refreshed.

Download new version 0.6.26.1 critical bug out of memory fixed.

**Comment by dAtA-TRoN** [comment]
> Excellent! Thank you, obviously the code has been refreshed.
> 
> Download new version 0.6.26.1 critical bug out of memory fixed.
> 
> 

Will do. Thank you again for your work. The new update is great 😊.
