### ISSUE TITLE
UI is becoming more and more inconsistent day by day

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#1072]
### Description

There are too many inconsistent UI elements. I'm providing screenshots of few of those elements. 

---
### Items not properly aligned
![image](https://github.com/fast4x/RiMusic/assets/78584556/afa90b9b-250a-4707-a5bb-269d77aa81fa)

---
### Position of icons is different on different pages
![image](https://github.com/fast4x/RiMusic/assets/78584556/3a5e21fb-8f76-4294-975c-711e56c58436)
![image](https://github.com/fast4x/RiMusic/assets/78584556/21ec8fdf-6352-41bc-9ba0-6cd582b5efd7)
![image](https://github.com/fast4x/RiMusic/assets/78584556/447b4e95-ed42-492a-af78-dbd213b67edd)
![image](https://github.com/fast4x/RiMusic/assets/78584556/404eb666-0b20-40be-acbb-1ff0c803f19e)
![image](https://github.com/fast4x/RiMusic/assets/78584556/a09406cd-e2a4-4efa-bbbf-e5ad6b8f0021)
![image](https://github.com/fast4x/RiMusic/assets/78584556/cc431c2b-e399-44d1-8ba4-260322bc1e30)

### Suggested Solution

Icons position should be consistent in whole UI.

**Comment by OrangeZXZ** [comment]
I think im going to try rearage the UI and make some concept images

**Comment by sayyid5416** [comment]
> If you're talking about the dice on the "Artists" tab then I think it's alright. Because if it was a little small it won't (probably) look good. That's what I thought and I still think so.

In first screenshot, they are not aligned properly. Check the sort button and arrow icon on other ss for reference.

**Comment by sayyid5416** [comment]
![image](https://github.com/fast4x/RiMusic/assets/78584556/f7878a22-7e5c-48ba-87f0-362723162b87)
![image](https://github.com/fast4x/RiMusic/assets/78584556/78685e96-e365-435b-8131-11b26aa6a8ac)
![image](https://github.com/fast4x/RiMusic/assets/78584556/61bb4755-c5ef-463d-9d91-7de6b8876180)
![image](https://github.com/fast4x/RiMusic/assets/78584556/23ee1ce0-bf01-468a-98c6-5aef711e3ac4)
![image](https://github.com/fast4x/RiMusic/assets/78584556/b08bb8e5-a5d9-4840-a282-58e1cac3ab6a)
![image](https://github.com/fast4x/RiMusic/assets/78584556/064cf285-0209-4a9e-9480-e8de49d5fa58)
![image](https://github.com/fast4x/RiMusic/assets/78584556/1c96207f-cdab-46e8-9ed2-2e5fea79444e)

I'm talking about these icons. Look how inconsistent they are positioned.

**Comment by sayyid5416** [comment]
Yeah, it needs to be settled what goes where for the sake of consistency.
