### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Lllum** [fast4x/RiMusic#1074]
### Steps to reproduce the bug

Just click on the app, it shows the RiMusic logo and then crashes

### Expected behavior

The app should open to the UI of rimusic

### Actual behavior

It crashed when I opened it immediately 

### RiMusic version

0.6.26.1

### Android version

8.1.0

**Comment by Lllum** [comment]
https://github.com/fast4x/RiMusic/assets/156969262/1e939502-7b83-48e2-85f7-fd3a5a2002ab

**Comment by fast4x** [comment]
Confirm your version of android is 8?

**Comment by Lllum** [comment]
Yes

**Comment by Lllum** [comment]
> Confirm your version of android is 8?

Yes it's 8

**Comment by fast4x** [comment]
Ok maybe I understand, version before was ok?

**Comment by Lllum** [comment]
> Ok maybe I understand, version before was ok?

No the version before crashed while I was scrolling down my Playlist or just using the app in general

**Comment by fast4x** [comment]
Ok, I'll try all with your version, thanks for details.

**Comment by Lllum** [comment]
> Ok, I'll try all with your version, thanks for details.

Thank you so much :), also your app is great I don't even wanna try looking for temporary alternatives until this is fixed 😂

**Comment by fast4x** [comment]
Uhm nice.
If you want please try this custom version please https://rimusic.xyz/download

**Comment by Lllum** [comment]
> Uhm nice.
> If you want please try this custom version please https://rimusic.xyz/download

Just tried it, it's great.

**Comment by fast4x** [comment]
Perfect

**Comment by fleurc** [comment]
Hope this will be fixed on next release, I really love this app. I'm on Android 14 Samsung One UI 6.0, but this problem happens to me too.

Closes immediately once and stops the music, then I open it again and doesn't crash, feels very random as to when the crash happens.

**Comment by fast4x** [comment]
> Hope this will be fixed on next release, I really love this app. I'm on Android 14 Samsung One UI 6.0, but this problem happens to me too.
> 
> Closes immediately once and stops the music, then I open it again and doesn't crash, feels very random as to when the crash happens.

Try this custom version https://rimusic.xyz/download

**Comment by fleurc** [comment]
Thanks, will be testing throughout the week and answer if it worked well.

**Comment by fleurc** [comment]
> I have used the custom version, tho it hasn't crashed, no music played, it refused to start any song at all. So I'll install the old version again.

Discovered it was related to calls, being in a whatsapp call simply made the music refuse to play, I was very confused because that never stopped any other program before.

**Comment by fast4x** [comment]
it's ok

**Comment by fast4x** [comment]
Fixed and improved for android 8, available from version 0.6.27

**Comment by fleurc** [comment]
I've used it the custom version, I had until now 1 crash on Android 14. When trying to switch apps. Otherwise, the app has not crashed, not as often as it used to.

**Comment by fast4x** [comment]
Great, nice feedback, thanks.
