### ISSUE TITLE
[Feature]: Improvements in UI

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#1076]
### Description

- [x] Hide `Pinned Playlist` section from `Library` if no playlist is pinned.
- [x] Inside playlists, there a _**star shaped**_ icon to pin the playlist to `Pinned Playlist` section. Change that icon to something similar to _**a pin**_

**Comment by dAtA-TRoN** [comment]
Good points. Nice 📌!

**Comment by dAtA-TRoN** [comment]
> I think instead of doing that there should just be two small icons at the top.

Yes, that would also be my preferred approach, but I believe that's how it was before. And it was changed to these huge buttons for some reason, which I can't really understand.

Nevertheless, I stick to my statement that one will probably choose a previously created playlist more often than the two buttons mentioned.

**Comment by dAtA-TRoN** [comment]
> Those are like barricade in middle of the playlists.

I completely agree. However, I recall someone specifically requesting it, and then fast4x proceeded to implement it.

**Comment by fast4x** [comment]
I like the comparison and I always accept people’s opinions, then I evaluate the best solution as a compromise for everyone.

**Comment by fast4x** [comment]
Implemented, new playlist and import now are icon near title playlists section and star icon is pinned icon.
Available from version 0.6.27

**Comment by dAtA-TRoN** [comment]
> Implemented, new playlist and import now are icon near title playlists section and star icon is pinned icon.
> Available from version 0.6.27

https://github.com/fast4x/RiMusic/assets/71184627/881839c3-7bcb-44a6-93f7-b96f080cc78d

**Comment by sayyid5416** [comment]
> Implemented, new playlist and import now are icon near title playlists section and star icon is pinned icon. Available from version 0.6.27

Wow thanks for this. btw what about the empty "pinned playlist"?

**Comment by fast4x** [comment]
> > Implemented, new playlist and import now are icon near title playlists section and star icon is pinned icon. Available from version 0.6.27
> 
> Wow thanks for this. btw what about the empty "pinned playlist"?

if empty not show title...
