### ISSUE TITLE
Playback duration for changing recommendations in quick pics not working for 10 seconds

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1077]
### Steps to reproduce the bug

Playback duration for changing recommendations in quick pics not working for 10 seconds but it's working for default 20 seconds.
![IMG_20240316_102131](https://github.com/fast4x/RiMusic/assets/148480722/d2b32987-4323-4bf7-b25f-eb3fe87be86e)

### Expected behavior

After changing d
Playback duration to 10 seconds, quick pics should change after track change after 10 seconds.

### Actual behavior

But not changing after 10 seconds. But it's working fine for 20 seconds.

I didn't tried for other durations

### RiMusic version

0.6.26.1

### Android version

Android 13

**Comment by fast4x** [comment]
Fixed, available from version 0.6.27

**Comment by SureshTimma** [comment]
> Fixed, available from version 0.6.27

When will be the next update?

**Comment by Nikks84** [comment]
> > Fixed, available from version 0.6.27
> 
> When will be the next update?

This Friday
