### ISSUE TITLE
Improvements needed in Library Page

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1078]
### Description

![IMG_20240316_110845](https://github.com/fast4x/RiMusic/assets/148480722/3fa390c5-da42-4ee9-80c6-3e85f6ac8876)

### Suggested Solution

1. If there is no pinned playlists then there is no need to show pinned playlists heading. After adding any pinned playlists it should be appear.
2. It's not a better place to place No of playlist icon on top. Instead place it at the side of playlists heading.

**Comment by dAtA-TRoN** [comment]
Duplicate #1076

**Comment by dAtA-TRoN** [comment]
> > Instead place it at the side of playlists heading.
> 
> I don't get it.

Me neither. But I think basically it's a duplicate.

**Comment by SureshTimma** [comment]
Sorry, I didn't notice it as a duplicate before.

I am suggesting you that change position of "now of playlists icon"

![IMG_20240316_120934.jpg](https://github.com/fast4x/RiMusic/assets/148480722/c3c09bb9-e49a-4cfd-a309-fa42178b1bf7)

**Comment by dAtA-TRoN** [comment]
Ah okay. That should be changed.

**Comment by SureshTimma** [comment]
Ok.
