### ISSUE TITLE
[Feature]: Make Play Button style appear in gradient background

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1079]
### Description

So after the new update play button style doesn't work in new gradient background. Because now the color that play button used to have is used in the background.

### Suggested Solution

**How it looks like now**
![Picsart_24-03-16_11-26-30-419](https://github.com/fast4x/RiMusic/assets/99175083/71f7b5e8-e191-489f-ba57-329f2d90c40e)

**Suggested idea**
![Picsart_24-03-16_11-14-38-207](https://github.com/fast4x/RiMusic/assets/99175083/7024b7ec-e657-4622-9da3-3747bbf8ab7b)

**Explanation**
It's not pure white ofc but a blend of white and color of album cover just like it used to be in background when gradient is off. Also make sure to reduce the opacity a bit in white button because full opacity looked a bit weird when i was making this concept in Picsart. The opacity used here is 70% of original
![Picsart_24-03-16_11-25-13-481](https://github.com/fast4x/RiMusic/assets/99175083/0fc77ac5-f037-4b5d-b8b0-fe188afb101a)

**Comment by dAtA-TRoN** [comment]
Duplicate #1070

**Comment by NikunjKhangwal** [comment]
Well I've made the concept to explain it further. So am i allowed to keep this issue opened?

**Comment by dAtA-TRoN** [comment]
> Well I've made the concept to explain it further. So am i allowed to keep this issue opened?

100%. I just wanted to point out that the posts are related.

**Comment by sayyid5416** [comment]
### 2 more things:
- Current gradient is too harsh, I think it should be more subtle.
- Add a shadow or something similar behind the bottom bar. Currently it feels merged with rest of the background when gradient background is ON

**Comment by dAtA-TRoN** [comment]
> ### 2 more things:
> - Current gradient is too harsh, I think it should be more subtle.
> - Add a shadow or something similar behind the bottom bar. Currently it feels merged with rest of the background when gradient background is ON

Very good.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.27

**Comment by sayyid5416** [comment]
> Fixed, available from version 0.6.27

Can I try or I'll have to wait?

**Comment by NikunjKhangwal** [comment]
> Can I try or I'll have to wait?

The stable version will be released in a few days. You can try debug apk right now if you want to

**Comment by sayyid5416** [comment]
> > Can I try or I'll have to wait?
> 
> The stable version will be released in a few days. You can try debug apk right now if you want to

Where can I download it? also does it have a different package name or same one?

**Comment by NikunjKhangwal** [comment]
> Where can I download it? also does it have a different package name or same one?

Different package name:- https://github.com/fast4x/RiMusic/actions/runs/8345815345/artifacts/1339395640

**Comment by fast4x** [comment]
> > Fixed, available from version 0.6.27
> 
> Can I try or I'll have to wait?

wait please...

**Comment by sayyid5416** [comment]
> > Where can I download it? also does it have a different package name or same one?
> 
> Different package name:- https://github.com/fast4x/RiMusic/actions/runs/8345815345/artifacts/1339395640

I don't see any of the implemented changes in any artifacts from actions.

**Comment by NikunjKhangwal** [comment]
> I don't see any of the implemented changes in any artifacts from actions.

I think they're not implemented yet and fast4x just meant to say they will be available from next release. Either way RiMusic gets update every week so you don't have to wait for long.

**Comment by fast4x** [comment]
artifact include last released version...

**Comment by NikunjKhangwal** [comment]
My bad. I thought they're like Github actions which automatically build apk of last activity on repo.

**Comment by NikunjKhangwal** [comment]
@fast4x I wanted to give some suggestions. First is i think it's a good idea to update screenshots on your website and readme file. Currently all the screenshot showcase black theme and basic screens. Now that the app have grown so much you can show a lot of cool things this app can do like dynamic theme, gradient background, designs of timeline & play button etc. I think it'll attract more new users.

Secondly i wanted to ask if it's possible to create a new space for discussions, help and questions? So it doesn't populate the issues section because they're not actually any bug or feature request. Something like a Telegram group which is very common but there's other options like matrix group, discord server and even Github also supports basic discussions feature. I've seen a section for questions in github issues as well.

**Comment by fast4x** [comment]
> @fast4x I wanted to give some suggestions. First is i think it's a good idea to update screenshots on your website and readme file. Currently all the screenshot showcase black theme and basic screens. Now that the app have grown so much you can show a lot of cool things this app can do like dynamic theme, gradient background, designs of timeline & play button etc. I think it'll attract more new users.
> 
> Secondly i wanted to ask if it's possible to create a new space for discussions, help and questions? So it doesn't populate the issues section because they're not actually any bug or feature request. Something like a Telegram group which is very common but there's other options like matrix group, discord server and even Github also supports basic discussions feature. I've seen a section for questions in github issues as well.

For the site you’re right, it must be updated. You could tell me the screenshots to insert and then maybe I can update the site.

For the discussion section you can freely use the section on github Discussions.

**Comment by NikunjKhangwal** [comment]
Can you link discussions option here?
![IMG_20240320_121605](https://github.com/fast4x/RiMusic/assets/99175083/3985543b-2c21-478e-a14e-57be020d5352)

For the screenshot, I'll mention them in a while

**Comment by fast4x** [comment]
![Screenshot_2024-03-20-07-54-43-326_com.microsoft.emmx-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/91ae6523-f72d-4f11-952e-8735889272ae)

**Comment by NikunjKhangwal** [comment]
I know you can access them from here but majority of the normal users don't that's why i suggested it. You can see there's no new discussion or qna opened

**Comment by fast4x** [comment]
The threads have been created and once completed I closed them, so you can create and manage them.
