### ISSUE TITLE
[Feature]: Slightly increase the size of wavy circle play button

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1080]
### Description

The wavy circle play button is slightly smaller compared to others.

### Suggested Solution

For comparison:
![IMG_20240316_113958](https://github.com/fast4x/RiMusic/assets/99175083/86813a65-9627-4aa3-a6c7-32f4751e499d)

Increase the size a bit and make it the same as others so it doesn't look weird

**Comment by fast4x** [comment]
Implemented, available from version 0.6.27
