### ISSUE TITLE
Search Bars: Formatting Issues and design inconveniences

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1081]
### Steps to reproduce the bug

1. Notice that the main search bar is not formatted properly.

2. Compare the Main Search Bar with the new Settings Search Bar and notice that they are significantly different:

![Screenshot_2024-03-16-07-12-33-50_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/71184627/0e5f573a-fccc-4174-a7b1-bf7035202e49)

![Screenshot_2024-03-16-07-24-11-24_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/71184627/eb2b46bc-eb0a-4577-8d35-737e9cba007f)

### Expected behavior

Both search bars are formatted correctly and do not differ from each other in any way.

### Actual behavior

**Main Search Bar:**

1. The magnifying glass icon is too high.

2. The label "Search" is also too high.

3. The "X" for clearing the search text is too low.

**New Settings Search Bar:**

1. No "X" button

2. The coloring differs from that of the Main Search Bar

3. Font positioning, style and icon size do not match the main search bar 

### Additional Context

Both search bars should be formatted correctly, have the same functionality and should not differ from each other to contribute to a harmonious overall picture.

### RiMusic version

0.6.26.1

### Android version

13

**Comment by dAtA-TRoN** [comment]
> Btw I find the settings search bar better…

Okay, I'm not a fan of it. Looks old fashioned to me.

**Comment by dAtA-TRoN** [comment]
> And btw you've written versions wrong.

?

> Also I think the settings search bar is different for ModernBlack theme: Has sharp edges.

That should be changed.

**Comment by dAtA-TRoN** [comment]
> > And btw you've written versions wrong.
> 
> ? What do you mean? The version number of the app?
> 
> > Also I think the settings search bar is different for ModernBlack theme: Has sharp edges.
> 
> That should be changed.

**Comment by dAtA-TRoN** [comment]
> Check what you wrote on

Now I got it 💡. Changed!


> I disagree

A search bar with edges clearly contradicts the design language of the app.

**Comment by sayyid5416** [comment]
Inconsistencies are going out of hand as more features are added. I hope it's not too much burden on the developer 😅

**Comment by dAtA-TRoN** [comment]
> Inconsistencies are going out of hand as more features are added. I hope it's not too much burden on the developer 😅

**Comment by dAtA-TRoN** [comment]
> Inconsistencies are going out of hand as more features are added. I hope it's not too much burden on the developer 😅

It's alright if such inconsistencies arise, but it's best not to encourage them and instead stick to the intended design principles, in my view.

**Comment by fast4x** [comment]
It is normal to have bugs because they stimulate user thinking and allow you to create a common goal. 😂

**Comment by fast4x** [comment]
Improved
