### ISSUE TITLE
[Feature]: Waveform Bars Timeline

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1083]
### Description

A new style of timeline which uses waveform bars. It's very common in most music players i think.

### Suggested Solution

Example
![IMG_20240316_124044](https://github.com/fast4x/RiMusic/assets/99175083/648d9f7d-3b31-448c-ba8e-e045de1cf0cd)

**Comment by fast4x** [comment]
Yes its nice, but requires a lot of library with increase app size consistently. I'll try new way...

**Comment by VINULA2007** [comment]
Would be cool if it looked like the fatbar with indentation
It would surely look cool

**Comment by NikunjKhangwal** [comment]
I'm sharing some libraries I've found:
https://github.com/lincollincol/compose-audiowaveform
https://github.com/massoudss/waveformSeekBar
https://github.com/alxrm/audiowave-progressbar
https://github.com/ryanheise/just_waveform

**Comment by OrangeZXZ** [comment]
@fast4x i think this is already done?

**Comment by fast4x** [comment]
yep
