### ISSUE TITLE
[Feature]: Increase the size of cover art and texts on expanded lyrics screen

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1084]
### Description

The size of cover art and song/artist names are very small and there's a lot of empty space left

### Suggested Solution

Increase their size to better occupy the space. My concept:-
![IMG_20240316_130522](https://github.com/fast4x/RiMusic/assets/99175083/29dc60e0-4d40-404a-8cd3-6b26d5fc269a)

**Comment by NikunjKhangwal** [comment]
Btw sorry I've created a lot of feature requests at once. I've had these ideas for a long time but didn't had the time to tell them. All of these are low priority requests, take as much as time as you need. I've created seperate issues so you can track them seperatly and their discussions can be seperate.

**Comment by dAtA-TRoN** [comment]
> Increase their size to better occupy the space.

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/0d808eb6-7910-4696-a79e-d51453cc9273)

**Comment by fast4x** [comment]
No problem, thank you for create separately ticket, it's a good think

**Comment by fast4x** [comment]
Implemented, available from version 0.6.29

**Comment by sayyid5416** [comment]
Also something needs to be done regarding **_bottom empty space_**

**Comment by NikunjKhangwal** [comment]
What bottom empty space?

**Comment by sayyid5416** [comment]
![image](https://github.com/fast4x/RiMusic/assets/78584556/d870c2c8-aa41-43ed-802a-a5c742c93f8b)

☝️ This

**Comment by fast4x** [comment]
wait for next version

**Comment by NikunjKhangwal** [comment]
I see. I don't use gestures so it looks fine with navigation buttons

**Comment by fast4x** [comment]
![Screenshot_2024-04-05-08-48-49-337_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/1484476/ddbc40cc-9cb3-4e2e-b73c-b6c83e0f0aa4)

soon...

**Comment by NikunjKhangwal** [comment]
Look good. Just 2 things I'm noticing. First the image isn't a perfect square, maybe it's just this song. It's still looking better than before that's a good thing. Second is the image behind lyrics, is it temporary?

**Comment by fast4x** [comment]
I'll improve it 😊

**Comment by NikunjKhangwal** [comment]
Ofc you will, i trust you. No hurry 😇

**Comment by NikunjKhangwal** [comment]
It's a perfect shape now, thank you 🥳
