### ISSUE TITLE
Few inconsistencies I have noticed

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1085]
### Description

All of these below are from the latest version. I didn't analyze much this time because I don't really have time currently.

### Suggested Solution

- I think this should be there instead:

![Screenshot_20240316-114745.jpg](https://github.com/fast4x/RiMusic/assets/85461823/d67c805c-739e-4228-b6e2-9ba3103bf8a7)

Along with the "cross" icon. But don't place the icons too close.

- Similar to player menu playlist menu can't be closed with gesture. (I wonder if there are anymore menu with this problem!) Only possible by tapping on somewhere else than the menu. 

![Screenshot_20240316-120230.jpg](https://github.com/fast4x/RiMusic/assets/85461823/1f5a21bb-6739-4f42-99cc-4bee3a28c88a)

Both should have a better way to close.

- Instead of arrow button there should be something different to close player menu.

Because the arrow didn't really change anything much other than being there. 
Try one of these below things instead.

1. Place the arrow button at the bottom.
2. Implement gesture instead of arrow button.
3. Minimize/remove a few buttons (I'm sure there are a few that aren't so important or okay to minimize) from the menu so it'll be easier to close the menu.

- Playlists tile/images should be customizable.

1. Maybe implement something like this to adjust size:

![Screenshot_20240316-133428.jpg](https://github.com/fast4x/RiMusic/assets/85461823/7c3a09ce-c3c9-44af-ad16-2bdf792b6616)

2. And probably how many playlist on each column should be customizable as well.

3. And it'd be great if we could set custom playlist cover. (We can only for albums, not for playlists) This has been suggested several times already.

- This should be on "Quick Picks" settings not on "User Interface":

![Screenshot_20240316-135241.jpg](https://github.com/fast4x/RiMusic/assets/85461823/063ef1bc-5004-43f3-b747-8492b59575f2)

- "Default page" should only work when you enter the app after closing it. Not when using it. 

- Albums tab should have grid view. A button at the top to toggle to preferred view.

Few of those above probably has been suggested before but sorry I don't have much time to search and mention the og's. But I'll later if I can.

**Comment by dAtA-TRoN** [comment]
Your suggestions are fantastic, especially the notion of implementing a grid view for albums, which aligns with my own thoughts. However, I have some reservations regarding your initial point. From a practical standpoint, maximizing the space for the search bar is crucial to allow users to input sufficient text and have a comprehensive view. Moreover, there are aesthetic considerations; a uniformly elongated search bar, centrally positioned, adds to the overall visual appeal. While I appreciate the rationale behind separating the filter and back button, perhaps there's an alternative approach to achieve this. As for your proposal concerning the back button, I believe its drawbacks outweigh its benefits.
