### ISSUE TITLE
[Feature]: New compact playlist look

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1086]
### Description

The playlist started to be realy filled up that is why ive made this:
![image](https://github.com/fast4x/RiMusic/assets/104271365/424844b4-5094-4679-9ba3-3e212a192ba0)

I got a bit of inspiration from Youtube
- I moved a lot of butons at the top we can notice that I added the find song button next to the search icon also the search icon will become the search song in the playlist feature.
- I also moved the burger menu in the top right like on the player it could also be at the top of the playlist informations (i think it is a better choice)
- I moved the downloads butons also in the playlist informations since you download the playlist and it just feels normal (I think the best position would be in  the bottom right if you put the burger menu in the top right)
- To finish the shuffle is not next to the rearrange feature it looks so much  better without all the icons at the same place

### Suggested Solution

- Move search and find icons at the top right
- Move the burger menu at the top right of the playlist informations
- Move the download buttons in the bottom right of the playlist informations
- Move the shuffle next to the rearrange text because you have space now

### Additional Context

If you guys have new ideas to make this better pls tell me
Also if you want me to make another UI remake for other things

**Comment by OrangeZXZ** [comment]
Also the new lock icon in progress could be next to the burger menu imo

**Comment by sayyid5416** [comment]
Some inconsistencies related to these icons are also discussed in #1072
