### ISSUE TITLE
[Feature]: Customisable sidebar

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1087]
### Description

There are a lot of sidebar categories that i dont use and i would love to hide them like the default playlists
![image](https://github.com/fast4x/RiMusic/assets/104271365/80a6025b-e632-4ef0-ba25-a524fc4ec502)

I also think that the stats button should be an category it will look better and people who dont use can disable it

To finish when disabling playlists from the settings they are hidden but not in the side bar after you press on one

### Suggested Solution

- Make a categories chose option to disable/enable categories if we want
- Make the stat button a category with text when text categories is enabled
- Hide the playlist disabled from the sidebar

### Additional Context

For the stats i also think that the dates that were in the side bar could be presented like the playlist rearrange text
![image](https://github.com/fast4x/RiMusic/assets/104271365/d37ab493-8863-45f3-bfa8-42fa1f5cdae1)

**Comment by sayyid5416** [comment]
Also _**Allow users to rearrange items of the navigation bar (I think you call it Home)**_ in #852

**Comment by fast4x** [comment]
Implemented top bar navigation, available from version 0.6.29
