### ISSUE TITLE
[Feature]: Merge Settings

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1088]
### Description

I think some of the setting take a lot of place for nothing and they should be merged in a setting with pop-up
![image](https://github.com/fast4x/RiMusic/assets/104271365/f3044c0d-d877-4e02-82c3-9b74c34051d9)

### Suggested Solution

Make a pop-up for these settings:
- PLAYER ACTION BAR
- PLAYLISTS
- BACKROUND PLAYER
- QUICK PICKS (Show Related albums, Show similar artists, etc...)

That is how it should look like:
![image](https://github.com/fast4x/RiMusic/assets/104271365/20d97ed3-569d-4ce6-8acd-8ba457f2660e)

### Additional Context

I think that QUICK PICKS has a category for nothing and there should be a category named "COMPONENTS" for these tipes of settings maybe?

**Comment by fast4x** [comment]
Nice and simple to implement

**Comment by OrangeZXZ** [comment]
> Nice and simple to implement 

If you want to go beyond this you could try adding the rearrage system like on queues to change the order of the buttons and more

**Comment by OrangeZXZ** [comment]
@fast4x Sorry for pinging you, but I think this feature was forgotten about and could be an easy option to make settings less cluttered in the next update (since there are a lot of options now).

If you are busy with other things or don't want to implement it now, that's fine.

**Comment by fast4x** [comment]
keep it open
