### ISSUE TITLE
[Feature]: Bring back PureBlack with dynamic colors

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1089]
### Description

In the version 0.6.25 there was a bug that made the dynamic theme background Black but while using this i started to prefer this way because i have an Amoled phone

### Suggested Solution

Maybe add back as an option?

### Additional Context

Also what is the difference for PureBlack and ModernBlack?

**Comment by fast4x** [comment]
You can use it now, please set theme to dynamic and theme mode to pitch black.

**Comment by OrangeZXZ** [comment]
> You can use it now, please set theme to dynamic and theme mode to pitch black.

oh i see sorry for making this then

**Comment by fast4x** [comment]
No problem 😜

**Comment by OrangeZXZ** [comment]
> No problem 😜

Id dosen't work i added a new bug issue #1103
