### ISSUE TITLE
[Feature]: Add "Radio" Playback / Queue Generation Behaviour to Android Auto

### ISSUE THREAD

**Issue by Ultrabenosaurus** [fast4x/RiMusic#1091]
### Description

When using RiMusic on my phone (or YouTube Music via app / web) playing a song from search results, quick picks, last played, etc., will play that song and also populate the queue with a growing selection of tracks based on similarity, history, etc. However, in Android Auto, there is no Quick Picks tab and the Songs tab only shows a handful of tracks _(equivalent to the Songs screen in the app with the eye crossed out (I don't know what this means or is called))_ and tapping any of them will simply play that small list of songs, not generate a new queue of many tracks based on the starting song.

Android Auto mode also doesn't seem to have an equivalent to toggling that eye symbol on the Songs tab in the app, nor any long-press behaviour on songs nor a "Radio" button after starting playback to then have RiMusic generate a semi-random queue.

### Suggested Solution

Playback behaviour in Android Auto should be the same as when using the app directly on my phone, showing a Quick Picks screen as well as using the "Radio" behaviour to generate a queue of music after starting a track from my car's screen. 

### Alternatives

A Radio button on the playback UI in Android Auto, to discard the current queue and generate a new one from the currently playing track, would also be appreciated.

### Additional Context

I am using app version 0.6.25 installed from F-Droid using the IzzyOnDroid repo.

**Comment by fast4x** [comment]
Hi, try new 0.6.26.1 it's have a series of AA improvements. I'll try to implement what you have requested.

**Comment by Ultrabenosaurus** [comment]
> Hi, try new 0.6.26.1 it's have a series of AA improvements. I'll try to implement what you have requested.

I have updated to the latest release from Github. I'll try it on Android Auto tomorrow (it's night here now) and report back :+1:

**Comment by Ultrabenosaurus** [comment]
I tried it earlier and still get the same behaviour via Android Auto where it only plays from the few songs shown on screen before starting playback. If I tap on a track from the Songs tab the queue only contains those songs shown on screen, same with Library > Cached or Library > Top 30, etc. It does not generate a semi-random queue like it does when using the app directly on my phone.

**Comment by fast4x** [comment]
Ok ill improve it

**Comment by Ultrabenosaurus** [comment]
Thank you! :+1:

**Comment by fast4x** [comment]
Added play radio, available from version 0.6.33

**Comment by fast4x** [comment]
Implemented, available from version 0.6.60
