### ISSUE TITLE
[Feature]: Keyboard opens everytime when I go to settings

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#1095]
### Description

Keyboard pops up everytime when I go to settings obviously because there's now search but it kinda gets annoying 

### Suggested Solution

Make keyboard pop up only when the search bar is tapped

**Comment by VINULA2007** [comment]
And it pops up everytime I change a setting

**Comment by VINULA2007** [comment]
Sometimes does this too when I open the player while in settings before the keyboard pops up
![Screenshot_2024-03-16-20-36-34-118_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89296867/c908246b-0d3a-4c61-afdd-bff9301b6531)

**Comment by Nikks84** [comment]
See #1075

**Comment by fast4x** [comment]
Improved, available from version 0.6.27

**Comment by Nikks84** [comment]
> Improved, available from version 0.6.27

🫡🫡
