### ISSUE TITLE
[Feature]: quick pick from innertune 

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#1096]
### Description

I know this has next no chance on being implemented cause ViMusic and innertune are totally different but I kinda feel like innertune's quick picks are a bit better than on RiMusic 

### Suggested Solution

Implement innertune's quick picks from innertune or at least look into it

**Comment by SureshTimma** [comment]
@fast4x @VINULA2007 

Yes bro not only quick picks but also other features damn good.  Innertune has stopped updating their app. Please bro 🥺 make some changes to our app from the innertune please...

1. Bottom Navigation
2. Mood and geners in quick pics
3. History and stats icons placement
4. Placement of all settings under one settings icon

Please update these 4 please please please don't be mistaken.

![Picsart_24-03-16_22-39-13-296.jpg](https://github.com/fast4x/RiMusic/assets/148480722/397374a9-8886-43d5-b6cb-cf3ba25bd376)

![Picsart_24-03-16_22-38-08-822.jpg](https://github.com/fast4x/RiMusic/assets/148480722/f9d554fe-c1cb-49d9-8738-2f284e555c64)

![Screenshot_2024-03-16-22-39-23-52_f4703f2d42345ac28c56f11a6100c500.jpg](https://github.com/fast4x/RiMusic/assets/148480722/583c0a97-f7f3-45cc-a140-5acbe2e627cc)

**Comment by NikunjKhangwal** [comment]
@SureshTimma Wish i could help you but unfortunately I'm not a developer. I'm just a normal guy who like anything related to android. On a positive note, bottom navigation bar is already planned by @fast4x. We don't know when it'll come but someday surely just keep patience.

**Comment by SureshTimma** [comment]
> @SureshTimma Wish i could help you but unfortunately I'm not a developer. I'm just a normal guy who like anything related to android. On a positive note, bottom navigation bar is already planned by @fast4x. We don't know when it'll come but someday surely just keep patience.

I mentioned you because if many members agree with this @fast4x will love to do it. And with first preference.

**Comment by NikunjKhangwal** [comment]
> I mentioned you because if many members agree with this @fast4x will love to do it. And with first preference i thought.

I think it'll create unecessary pressure. We should just open issues about what we want. In the end it's developer choice for what he want to do with his app and what features he want to prioritise. Fast4x is already working extremely hard on the app and releasing a new version every week. You'll get the results eventually. Also Innertune is still working fine so keep using it as of now.

**Comment by SureshTimma** [comment]
> > I mentioned you because if many members agree with this @fast4x will love to do it. And with first preference i thought.
> 
> I think it'll create unecessary pressure. We should just open issues about what we want. In the end it's developer choice for what he want to do with his app and what features he want to prioritise. Fast4x is already working extremely hard on the app and releasing a new version every week. You'll get the results eventually. Also Innertune is still working fine so keep using it as of now.

That's also true! Yeah 😅 with excitement i have asked. I have been using YouTube music RVX since yesterday. But i knew this app from mixroot mod apks telegram channel. For trail i have installed this app. But itz crazy man. So this excitement. Sorry @fast4x if any wrong with me.

**Comment by fast4x** [comment]
Adding Mood and Genres in quick pics means removing the Discovery page. What worries me is the heaviness of the new Quick Pics page after joining them.

**Comment by SureshTimma** [comment]
> Adding Mood and Genres in quick pics means removing the Discovery page. What worries me is the heaviness of the new Quick Pics page after joining them.

Try Your best bro. If you are free.

**Comment by sayyid5416** [comment]
> Adding Mood and Genres in quick pics means removing the Discovery page. What worries me is the heaviness of the new Quick Pics page after joining them.

If you succeed, a smaller number of items on navigation bar will be easier to port navigation bar to bottom 😁.

**Comment by NikunjKhangwal** [comment]
> If you succeed, a smaller number of items on navigation bar will be easier to port navigation bar to bottom 😁.

+1 Good point
There's already a floating search bar and search tab can be removed from home. Stats and Settings can be moved to top right. If quick picks and discovery merged then app will be left with only 5 buttons which is ideal for bottom nav.

**Comment by Nikks84** [comment]
> @fast4x @VINULA2007 @NikunjKhangwal @dAtA-TRoN @sayyid5416
> 
> Yes bro not only quick picks but also other features damn good. Innertune has stopped updating their app. Please bro 🥺 make some changes to our app from the innertune please...
> 
> 1. Bottom Navigation
> 2. Mood and geners in quick pics
> 3. History and stats icons placement
> 4. Placement of all settings under one settings icon
> 
> Please update these 4 please please please don't be mistaken.
> 
> ![Picsart_24-03-16_22-39-13-296.jpg](https://private-user-images.githubusercontent.com/148480722/313419676-397374a9-8886-43d5-b6cb-cf3ba25bd376.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NTE2NjAsIm5iZiI6MTcxMDY1MTM2MCwicGF0aCI6Ii8xNDg0ODA3MjIvMzEzNDE5Njc2LTM5NzM3NGE5LTg4ODYtNDNkNS1iNmNiLWNmM2JhMjViZDM3Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QwNDU2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjY2NjQ3NjQ5ODA1NDEzNDRjZmQ5OGI0MjdhMTRkODJlZDdiZTJmN2E3ODYxNDBkNmY5NTgyOTE4YTg5ZGU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q8dA23FX_I7gfox5HPECzg_6dhySXPDLz072yFSJOnM)
> 
> ![Picsart_24-03-16_22-38-08-822.jpg](https://private-user-images.githubusercontent.com/148480722/313419677-f9d554fe-c1cb-49d9-8738-2f284e555c64.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NTE2NjAsIm5iZiI6MTcxMDY1MTM2MCwicGF0aCI6Ii8xNDg0ODA3MjIvMzEzNDE5Njc3LWY5ZDU1NGZlLWMxY2ItNDlkOS04NzM4LTJmMjg0ZTU1NWM2NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QwNDU2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzFiNDYwN2M0YzllZTViYjMwZTc2OWQ3MDFlZTdhOGY4Nzc1YmYwNjAxNjJhOTNmMTIxYzM2NTI4NDFiZTMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i5hoE32Bdnm8AfM5RCwlCz6A_8Af0-DmGfU4tygXhMY)
> 
> ![Screenshot_2024-03-16-22-39-23-52_f4703f2d42345ac28c56f11a6100c500.jpg](https://private-user-images.githubusercontent.com/148480722/313419675-583c0a97-f7f3-45cc-a140-5acbe2e627cc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NTE2NjAsIm5iZiI6MTcxMDY1MTM2MCwicGF0aCI6Ii8xNDg0ODA3MjIvMzEzNDE5Njc1LTU4M2MwYTk3LWY3ZjMtNDVjYy1hMTQwLTVhY2JlMmU2MjdjYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QwNDU2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmYxNzc5YmFkZjYxZTRkODA1MDZlNmRmYzlhNDc4Yjg2YzRjNjc3ZDkzMDdmMzQ0NzExZWI1NTYwMDAzNWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BSm9PHitikHLjVxVxFP4T2xlcmHTPqlMkLIJUIw05nI)

If you do this, I would also like to add this issue #985 in which I have said about changing the location of quick picks, then you can replace it with the search bar and not the app logo, it will be even better for us that we can access the search bar directly from the home screen or quick picks.
 And also i like the idea of an option navigation bar in to bottom.

**Comment by fast4x** [comment]
Some questions:
- What’s the history for?
- Why have the navigation bar at the bottom?
- Why change the scrolling type of settings? Innertune has it retractable while RiMusic uses it scrolling with a lot of research.

**Comment by fast4x** [comment]
> > If you succeed, a smaller number of items on navigation bar will be easier to port navigation bar to bottom 😁.
> 
> +1 Good point
> There's already a floating search bar and search tab can be removed from home. Stats and Settings can be moved to top right. If quick picks and discovery merged then app will be left with only 5 buttons which is ideal for bottom nav.

Floating buttons in home are in ViMusic mode...

**Comment by SureshTimma** [comment]
> Some questions:
> - What’s the history for?
> - Why have the navigation bar at the bottom?
> - Why change the scrolling type of settings? Innertune has it retractable while RiMusic uses it scrolling with a lot of research.
> 
> 

Bottom Navigation is for easy one hand usage.

**Comment by fast4x** [comment]
> > Some questions:
> > - What’s the history for?
> > - Why have the navigation bar at the bottom?
> > - Why change the scrolling type of settings? Innertune has it retractable while RiMusic uses it scrolling with a lot of research.
> > 
> > 
> 
> Bottom Navigation is for easy one hand usage. 

Have you tried with navigation bar to right with only icon?

**Comment by Nikks84** [comment]
1. No history option stats and history kind of similar things what are you listening in app he will available in stats.
2. Many people want it but even if it is not for me, it will be fine, but many people like it so it can be easy for them 
3. I am not in favour of it

**Comment by fast4x** [comment]
We could get the same result by adding the Yesterday tab in the statistics.

**Comment by Nikks84** [comment]
And yes, I definitely want that the search page can be like innertune, which we can access directly from the main page or quick picks

**Comment by fast4x** [comment]
> And yes, I definitely want that the search page can be like innertune, which we can access directly from the main page or quick picks 

Just now you can access it from home page.

**Comment by Nikks84** [comment]
![Screenshot_2024-03-17-14-36-23-81](https://github.com/fast4x/RiMusic/assets/160481076/da25c60f-ccfa-4f07-9f9d-3bbb27ecc79e)

 I mean this search bar it should appear instead of quick picks the same the above innertune ss and the icons that you have added under the search bar in this release should appear when we want to search.

**Comment by fast4x** [comment]
Question, why should I have it fixed in the home page when I can click on the icon and have so many search sections available?

**Comment by NikunjKhangwal** [comment]
> Floating buttons in home are in ViMusic mode...

Yeah i forgot since i only use Vi mode. You have to enable it in RiMusic mode as well for bottom nav.

**Comment by dAtA-TRoN** [comment]
> Question, why should I have it fixed in the home page when I can click on the icon and have so many search sections available?

Good question 👌🏼.

**Comment by Nikks84** [comment]
> Question, why should I have it fixed in the home page when I can click on the icon and have so many search sections available?

Ok It's fine as it is

**Comment by fast4x** [comment]
So it remains to try mood and genres in home and in the future have navigation at the bottom in addition to the current left and right (will also be available at the top)

**Comment by Nikks84** [comment]
Are you asking or telling?

**Comment by SureshTimma** [comment]
> > > Some questions:
> > > - What’s the history for?
> > > - Why have the navigation bar at the bottom?
> > > - Why change the scrolling type of settings? Innertune has it retractable while RiMusic uses it scrolling with a lot of research.
> > > 
> > > 
> > 
> > Bottom Navigation is for easy one hand usage. 
> 
> Have you tried with navigation bar to right with only icon?

Yes tried

**Comment by SureshTimma** [comment]
> So it remains to try mood and genres in home and in the future have navigation at the bottom in addition to the current left and right (will also be available at the top)

Yes, that will be perfect

**Comment by fast4x** [comment]
> Are you asking or telling? 

Not asking, just point remains to be done

**Comment by fast4x** [comment]
Implemented, Discovery and Quick Pics now in one page.
Available from version 0.6.27

**Comment by fast4x** [comment]
Friday
