### ISSUE TITLE
[Feature]: Add Youtube Music Playlist

### ISSUE THREAD

**Issue by NightFly88** [fast4x/RiMusic#1098]
### Description

Hello Fast4x (RiMusic)

Can an option be added to add playlist of youtube music to Rimusic,I have lots of songs I'd like to get from youtube music to Rimusic

Thanks

### Suggested Solution

I hope this option will be added

**Comment by fast4x** [comment]
Hello, there is a possibility but it requires some steps, you need to download two files, create a csv file to import in RiMusic. In a few days, I can give you a lift.

**Comment by NightFly88** [comment]
> Hello, there is a possibility but it requires some steps, you need to download two files, create a csv file to import in RiMusic. In a few days, I can give you a lift.

Okay,because it would be a great option

**Comment by xkill** [comment]
I tried to import a csv or txt with the songs of a playlist, but the app crash all the times

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/wiki/FAQs#what-is-the-csv-file-structure-for-importing-a-playlist-in-library

**Comment by NightFly88** [comment]
> https://github.com/fast4x/RiMusic/wiki/FAQs#what-is-the-csv-file-structure-for-importing-a-playlist-in-library

Thanks

**Comment by fast4x** [comment]
Hi you can do this:
- look at this https://mobiletrans.wondershare.com/playlist-transfer/export-youtube-music-playlist.html
- download YT/YTM songs codes by playlist from as explained https://takeout.google.com/
- create file from YouTube playlist from https://www.tunemymusic.com/it/transfer/youtube-to-file

Now you have

**Comment by SureshTimma** [comment]
Pin this!

**Comment by fast4x** [comment]
> @fast4x when i tried to importing file app closes automatically

Look at file structure for RiMusic import

**Comment by fast4x** [comment]
you can use excel, calc of libreoffice etc... save it in csv format with , separator and it's ok

**Comment by SureshTimma** [comment]
> you can use excel, calc of libreoffice etc... save it in csv format with , separator and it's ok

But i didn't get any meta id.

CSV File I get after conversion ![Screenshot_2024-03-20-23-46-36-90_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://github.com/fast4x/RiMusic/assets/148480722/a24194ee-bd57-460f-8269-0a512207a7a3)

But format you given ![Screenshot_2024-03-20-23-46-47-41_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://github.com/fast4x/RiMusic/assets/148480722/c9f84424-95fa-4e82-bc59-97db94a3dde4)

**Comment by fast4x** [comment]
> > you can use excel, calc of libreoffice etc... save it in csv format with , separator and it's ok
> 
> But i didn't get any media id.
> So all the list adds but songs not playing because of not having media id.
> @fast4x 
> 
> CSV File I get after conversion ![Screenshot_2024-03-20-23-46-36-90_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://github.com/fast4x/RiMusic/assets/148480722/a24194ee-bd57-460f-8269-0a512207a7a3)
> 
> But format you given ![Screenshot_2024-03-20-23-46-47-41_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://github.com/fast4x/RiMusic/assets/148480722/c9f84424-95fa-4e82-bc59-97db94a3dde4)
> 
> 

with phone it's a problem... use pc to edit file csv

**Comment by SureshTimma** [comment]
@fast4x im asking that i didn't find any media id
