### ISSUE TITLE
[Feature]: Port this stylish player design from Guitarist

### ISSUE THREAD

**Issue by rickdtc** [fast4x/RiMusic#11]
### Description

Guitarist-
https://github.com/Colorata/Guitarist

You could also make it optional of too cluttered

![Screenshot_20231006_232153](https://github.com/fast4x/RiMusic/assets/74096544/1ad98e6b-3265-4441-824c-5876dbaf336e)
![Screenshot_20231006_232148](https://github.com/fast4x/RiMusic/assets/74096544/d80728f4-4f28-4fac-9d82-36eee30715fc)

Also it would be great if you somehow add.the loop and loke buttons somewhere

### Suggested Solution

NA

**Comment by siggi1984** [comment]
> ### Description
> Guitarist- https://github.com/Colorata/Guitarist
> 
> You could also make it optional of too cluttered
> 
> ![Screenshot_20231006_232153](https://user-images.githubusercontent.com/74096544/273294268-1ad98e6b-3265-4441-824c-5876dbaf336e.jpg) ![Screenshot_20231006_232148](https://user-images.githubusercontent.com/74096544/273294278-d80728f4-4f28-4fac-9d82-36eee30715fc.jpg)
> 
> Also it would be great if you somehow add.the loop and loke buttons somewhere
> 
> ### Suggested Solution
> NA
> 
> ### Alternatives
> _No response_
> 
> ### Additional Context
> _No response_

The desing does not look bad. Would it me.gern times anscgauen. Where can you download the apk. Have not found anything.

**Comment by siggi1984** [comment]
The design does not look bad. Would like to have a look at it. Where can you download the apk. Have not found anything.

**Comment by rickdtc** [comment]
https://t.me/MaterialYouAppsChat/1/22414

A person in this channel had built this apk for testing

**Comment by fast4x** [comment]
It could be a possible theme, i don't think everyone will like it.

**Comment by rickdtc** [comment]
> It could be a possible theme, i don't think everyone will like it.

It could be an option, people can enable it if they like it.

**Comment by D4RKW1NT3R** [comment]
I like the idea of having themes, that would be awesome

**Comment by fast4x** [comment]
A new ModernBlack theme are ready from next version.

**Comment by fast4x** [comment]
I'm checking out Guitarist's controls

**Comment by fast4x** [comment]
I looked at the app, nice job.
I plan the development of skins for the player. 
Associated feature request #33

**Comment by ikanakova** [comment]
But does this mean that the original ViMusic skin will remain a choice? I like that much better than this one.

**Comment by fast4x** [comment]
@ikanakova 
The app remains as it is. The ability to customize the player page, can be added.

**Comment by fast4x** [comment]
Added waved progress bar on player.
Available from version 0.6.9

**Comment by rickdtc** [comment]
Let's go, thank you, also could we have an option to switch between different noe playing skins like retro in the future?

**Comment by fast4x** [comment]
Yes, there is this ticket and #33

**Comment by OrangeZXZ** [comment]
@fast4x i think this issue can be closed since the RiMusic UI has alot of this design maybe just add an "Wide Bar" button to be more similar
