### ISSUE TITLE
[Feature]: Ad Album Sorting option

### ISSUE THREAD

**Issue by Lio-gif** [fast4x/RiMusic#1101]
### Description

A Sorting option so all Songs from the Same Album are in one place but also that the Albums from the Same Artist are in one places

### Suggested Solution

Maybe Just add  IT to the Artist Sorting option

**Comment by fast4x** [comment]
You mean sort albums for artists in albums page?

**Comment by OrangeZXZ** [comment]
> You mean sort albums for artists in albums page?

he means sort songs in a playlist by album and artist

that way you have album A from artist A then Album B from artist A then Album A from artist B

**Comment by fast4x** [comment]
There is
![Screenshot_2024-03-17-08-51-14-387_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/941ac47d-15e2-4b53-a980-6f10e3dead16)

**Comment by Lio-gif** [comment]
Yeah but If you have a playlist with Different artists' albums are not at other albums from the Same artist

**Comment by fast4x** [comment]
Ok then sort by Artist+Album

**Comment by Lio-gif** [comment]
> Ok then sort by Artist+Album

Yeah

**Comment by fast4x** [comment]
Implemented, available from version 0.6.27
