### ISSUE TITLE
Dinamic theme is not compatible with Pich Black

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1103]
### Steps to reproduce the bug

1. Go in Settings > UI
2. Set UI as Dinamic
3. Set color as Pick Black
4. Modern black is automaticaly chosen and you cant use Dinamic

### Expected behavior

It should keep Dinamic

### Actual behavior

Modern Black is chosed automaticaly

### Screenshots/Screen recordings

![SmartSelect_20240316_194359](https://github.com/fast4x/RiMusic/assets/104271365/0f3d2978-6d31-44ac-9b1e-8504bb0e9919)

### RiMusic version

0.6.26.1

### Android version

Android 14

**Comment by OrangeZXZ** [comment]
I reselected Dinamic and it dose this

![Screenshot_20240316_195411.jpg](https://github.com/fast4x/RiMusic/assets/104271365/ebf96b3e-91e2-4d35-8527-a806de99298a)

![SmartSelect_20240316_195428.jpg](https://github.com/fast4x/RiMusic/assets/104271365/8da90ecd-e5ec-4e54-90aa-5cc3ed3b34a7)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.27
