### ISSUE TITLE
Place Songs and Video songs icons Side by side

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1107]
### Description

Please place Songs and Videos songs icons side by side. Because some songs not available as normal songs in YouTube, they are available as Video songs.

So navigation to songs to video songs is quite difficult crossing over albums and artists icons.

So please place them side by side or merge both format of songs in to one icon but add a filter or section or something else.
![IMG_20240317_090355](https://github.com/fast4x/RiMusic/assets/148480722/ccaed8a0-da78-4133-abb2-775e06904773)

### Suggested Solution

Place songs and video songs icons side by side upward along with playlists, if necessary.
At the end artists and albums.
![Picsart_24-03-17_09-08-08-306](https://github.com/fast4x/RiMusic/assets/148480722/576143bb-bd72-4dfa-864b-b00c54d74904)

**Comment by dAtA-TRoN** [comment]
I understand what you're getting at, but I don't think the idea is good. The current sorting, with songs first and then albums, is common and the default in most other music apps. Changing this could cause more confusion than it would be beneficial.

**Comment by SureshTimma** [comment]
> I understand what you're getting at, but I don't think the idea is good. The current sorting, with songs first and then albums, is common and the default in most other music apps. Changing this could cause more confusion than it would be beneficial.

Then merging is best option

**Comment by fast4x** [comment]
Merging songs and videos means deleting the video section. Not a good idea.

**Comment by SureshTimma** [comment]
> Merging songs and videos means deleting the video section. Not a good idea.

Ok
