### ISSUE TITLE
[BUG]: Rimusic instant crash

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#1109]
### Steps to reproduce the bug

Open app and it crash

### Expected behavior

Normally app open and don't crash

### Actual behavior

It open and crash

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/63956787/96d2aa3f-b24d-4ca8-b61f-e21356e421c7

### RiMusic version

0.6.26.1

### Android version

A7 EMUI 5.0.3 Huawei Nova

**Comment by fast4x** [comment]
Soon send custom version to try

**Comment by fast4x** [comment]
Try this custom please https://rimusic.xyz/download

**Comment by NEVARLeVrai** [comment]
> Try this custom please https://rimusic.xyz/download

I try after I finish eating

**Comment by fast4x** [comment]
Great, good lunch I’m having lunch too. 😜

**Comment by SureshTimma** [comment]
> > Try this custom please https://rimusic.xyz/download
> 
> I try after I finish eating 

@fast4x I'm unable to open link! India

**Comment by fast4x** [comment]
![app-release.zip](https://github.com/fast4x/RiMusic/files/14627812/app-release.zip)

Get from this zipped file.

**Comment by SureshTimma** [comment]
> ![app-release.zip](https://github.com/fast4x/RiMusic/files/14627812/app-release.zip)
> 
> Get from this zipped file.

Its 0.6.26.1 i have already installed it. Im asking about above link

**Comment by NEVARLeVrai** [comment]
> Great, good lunch I’m having lunch too. 😜

it working

**Comment by fast4x** [comment]
Wwwooowwwoooww

**Comment by NEVARLeVrai** [comment]
> Wwwooowwwoooww
 Ty
