### ISSUE TITLE
[Feature]: pinned playlist

### ISSUE THREAD

**Issue by Lio-gif** [fast4x/RiMusic#1110]
### Description

Change the Location of the pinned playlist

### Suggested Solution

Here
![IMG_20240317_124946](https://github.com/fast4x/RiMusic/assets/149175168/f8f684ea-ef8a-4e1f-ba4e-e747bfba69e2)

**Comment by Lio-gif** [comment]
Or Next to to favroits

**Comment by fast4x** [comment]
Do you mean to put a large button to display the playlists on a separate page such as your favorites or downloaded songs?

**Comment by Lio-gif** [comment]
No the playlist you pinned with the Star is there

**Comment by fast4x** [comment]
But pinned playlists can be many

**Comment by Lio-gif** [comment]
Yeah maybe Like you can Tap the Star to Times so ITS there and one time so ITS at pinned idk

**Comment by fast4x** [comment]
I'm sorry nut i don't understand.

**Comment by Lio-gif** [comment]
Sorry Like the Star to Pin the playlist you can Tap IT twice to Pin IT  ther and once tobpin IT where IT is now

**Comment by dAtA-TRoN** [comment]
🤔

**Comment by fast4x** [comment]
So if I click directly on the playlist icon twice, it becomes pinned and vice versa.

**Comment by Lio-gif** [comment]
> > So if I click directly on the playlist icon twice, it becomes pinned and vice versa.
> 
> I think I got what he means. He is saying tapping on the star.
> 
> ![Screenshot_20240317-184125.jpg](https://private-user-images.githubusercontent.com/85461823/313472096-10516078-c6cb-462a-a741-d24300220b97.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2Nzk4MjgsIm5iZiI6MTcxMDY3OTUyOCwicGF0aCI6Ii84NTQ2MTgyMy8zMTM0NzIwOTYtMTA1MTYwNzgtYzZjYi00NjJhLWE3NDEtZDI0MzAwMjIwYjk3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEyNDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMjZmZTUxMWUyMThhYWEwOWYwMDAxMGMzZGExYTQ1ZWJmODZjMjhhNDUzN2UwZTMwOTgzYWMxOWVjOGY3OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.baS3LTxzTdFzYeECS8FMInJ-JCd2a1A2jzouR4QuIYo)
> 
> He's trying to say…double tap on star icon should pin playlist at the top along with Favorites. And one tap should pin playlist where those are pinned as of now.

Yeah

**Comment by fast4x** [comment]
Double tap on star inside playlist not make sense.

**Comment by fast4x** [comment]
The idea is not bad but I see it here with a direct and quick double tap

![Screenshot_2024-03-17-14-58-19-978_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/24875d75-8ec5-4902-9fa1-86425a5b00fb)

**Comment by sayyid5416** [comment]
It's a bad idea in my opinion. I like current implementation better. Default playlist should stay differentiated than the pinned playlist.

**Comment by fast4x** [comment]
> It's a bad idea in my opinion. I like current implementation better. Default playlist should stay differentiated than the pinned playlist.

idea is for double tap...

**Comment by dAtA-TRoN** [comment]
> It's a bad idea in my opinion. I like current implementation better. Default playlist should stay differentiated than the pinned playlist.

I also think it's good the way it is now.

**Comment by dAtA-TRoN** [comment]
> It's a bad idea in my opinion. I like current implementation better. Default playlist should stay differentiated than the pinned playlist.

I also think it's good the way it is now.

**Comment by fast4x** [comment]
you mean go inside and click on star?

**Comment by sayyid5416** [comment]
> > It's a bad idea in my opinion. I like current implementation better. Default playlist should stay differentiated than the pinned playlist.
> 
> idea is for double tap...

single click = pin
double click = unpin

Thats simple and better.

**Comment by dAtA-TRoN** [comment]
Yep.

**Comment by fast4x** [comment]
> > > It's a bad idea in my opinion. I like current implementation better. Default playlist should stay differentiated than the pinned playlist.
> > 
> > idea is for double tap...
> 
> single click = pin
> double click = unpin
> 
> Thats simple and better.

From library single tap open playlist, isn't usable

**Comment by sayyid5416** [comment]
> > > > It's a bad idea in my opinion. I like current implementation better. Default playlist should stay differentiated than the pinned playlist.
> > > 
> > > 
> > > idea is for double tap...
> > 
> > 
> > single click = pin
> > double click = unpin
> > Thats simple and better.
> 
> From library single tap open playlist, isn't usable

By single or double click, OP meant for clicking the star/pin button.

**Comment by dAtA-TRoN** [comment]
> From library single tap open playlist, isn't usable

If it just has to be done because it has to, then why not do that?

![sketch1710688962104.png](https://github.com/fast4x/RiMusic/assets/71184627/a797861b-da67-4bc1-b443-c2d8a6ae21d0)

Maybe smaller stars or on the inside and not on the edge, but you get what I mean.

**Comment by fast4x** [comment]
Okay, we’re saying the same thing, fine.

**Comment by dAtA-TRoN** [comment]
> Okay, we’re saying the same thing, fine.

I think it's really not that bad.

**Comment by sayyid5416** [comment]
> > From library single tap open playlist, isn't usable
> 
> If it just has to be done because it has to, then why not do that?
> 
> ![sketch1710688962104.png](https://private-user-images.githubusercontent.com/71184627/313484507-a797861b-da67-4bc1-b443-c2d8a6ae21d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODk1MTMsIm5iZiI6MTcxMDY4OTIxMywicGF0aCI6Ii83MTE4NDYyNy8zMTM0ODQ1MDctYTc5WC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MGFkZDgwNDIzYzQ5Y2IzODZhZDZkNmY3NmE4OWE0MTQ3Nzg3Y2M1MzY1MWRhMjcwNmE3ZDAzZmUwZjc4NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wnal9YZFiIid3AmvuKD15hR6CbNgeo-8z3xtGGFc1xA)
> 
> Maybe smaller stars or on the inside and not on the edge, but you get what I mean.

Again, a bad idea. Simpler the UI, better it is. Why complicate it? When we already have a separate section for pinned playlist, then why merge it with default playlists?

**Comment by dAtA-TRoN** [comment]
I believe that the UI can also become too simple. This happens when you no longer know what to tap to do anything.

**Comment by sayyid5416** [comment]
> > Again, a bad idea. Simpler the UI, better it is. Why complicate it? When we already have a separate section for pinned playlist, then why merge it with default playlists?
> 
> I believe that the UI can also become too simple. This happens when you no longer know what to tap to do anything.

I think Default Special playlists (`Favorites`, `Cached`, `Downloaded`, `My Top`, `On Device`) should be in different space then any user created playlist.

**Comment by fast4x** [comment]
I think the most correct thing may be to add the pin icon in the library

**Comment by dAtA-TRoN** [comment]
> I think Default Special playlists (Favorites, Cached, Downloaded, My Top, On Device) should be in different space then any user created playlist.

![8jjrnj.jpg](https://github.com/fast4x/RiMusic/assets/71184627/d3f5a0e7-81dd-4789-9753-0e0aa1a1b619)

**Comment by fast4x** [comment]
We’re probably making a mistake.

**Comment by dAtA-TRoN** [comment]
> We’re probably making a mistake.

Finally someone says it 🙄.

**Comment by fast4x** [comment]
I consider the topic closed pending the next version. I have an additional idea to recover space in the library.
