### ISSUE TITLE
Improper My Top Playlist in Android Auto

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#1113]
### Steps to reproduce the bug

`My Top` playlist is showing up as `My Top 30` playlist with only _**30 songs**_, even though I've `My Top 100` playlist in my phone.

### Expected behavior

It should show `My Top 100` playlist _**(same as in phone)**_

### Actual behavior

It's showing `My Top 30` playlist in AA _**(it doesn't care what's in the phone)**_

### Version
- RiMusic 0.6.26
- Android 14

**Comment by fast4x** [comment]
For now i can increase to max of 200 like fixed number.

**Comment by sayyid5416** [comment]
> For now i can increase to max of 200 like fixed number.

I guess you misunderstood. Let me explain with example:
- If I set `My Top` to 30 in RiMusic: Android Auto shows `My Top 30`
- If I set `My Top` to 100 in RiMusic: Android Auto shows `My Top 30`
- If I set `My Top` to 200 in RiMusic: Android Auto shows `My Top 30`

Basically, Android Auto is not showing it properly.

**Comment by fast4x** [comment]
Yes i understand, for now i can rename it to My Top and show max 200 songs...

**Comment by sayyid5416** [comment]
Can't it behave like android app?

**Comment by fast4x** [comment]
Sure, I have a bug that I’m trying to fix and that blocks use of settings...

**Comment by sayyid5416** [comment]
> Sure, I have a bug that I’m trying to fix and that blocks use of settings...

Yes, this bug is 100% related to that. Until you found a fix for that bug, it's a good idea to make it `My Top` and showing max number of songs in it.

**Comment by fast4x** [comment]
Yes

**Comment by fast4x** [comment]
Isn't a bug, but AA limitation, I'll try a workaround.
