### ISSUE TITLE
Add refresh to Quick Pics

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1115]
### Description

The quick pics are currently suggesting from last played and most played songs.

### Suggested Solution

But i wish there should be another feature to refresh quick pics by swiping down on quick picks page. 

By refreshing quick picks should give new songs suggestions relative to our favourite songs list.

Discuss on it once! @fast4x and @all

**Comment by Nikks84** [comment]
Yes, it is in the planned, I think maybe it is working phase Will wait for it.

**Comment by fast4x** [comment]
This is implemented
