### ISSUE TITLE
App breaks after pausing a song, closing the app and then reopening the app

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1116]
### Steps to reproduce the bug

1. Play a song
2. Pause the song
3. Close app
4. Reopen app
5. Player disappears and the song can't be played unless specifically clicked on again

### Expected behavior

Player doesn't disappear and song can still be played again

### Actual behavior

Player disappears and song can't be played

### Screenshots/Screen recordings

Video of the bug: https://imgur.com/a/1AjEXIq

### RiMusic version

0.6.26.1

### Android version

Android 11

### Additional information

When the player disappears, it can be brought back by pressing the back button in the android navigation menu

**Comment by fast4x** [comment]
You use a custom rom?

**Comment by fast4x** [comment]
Do you have enabled invincible service and disable battery optimization?

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/wiki/FAQs#why-does-the-app-close-automatically-after-i-pause-it-for-a-while

**Comment by privacyfreak84** [comment]
> You use a custom rom?
No

**Comment by privacyfreak84** [comment]
> Do you have enabled invincible service and disable battery optimization?
Done both

**Comment by privacyfreak84** [comment]
Might be similar to #803 and #982

**Comment by fast4x** [comment]
I can not recreate the problem, but I improved some aspects I hope that in the next version there is no problem.
Available from version 0.6.27

**Comment by privacyfreak84** [comment]
> I can not recreate the problem, but I improved some aspects I hope that in the next version there is no problem.
> Available from version 0.6.27

Thanks! Hopefully it's resolved once and for all in 0.6.27. Closing

**Comment by privacyfreak84** [comment]
The issue persists 🙁

**Comment by fast4x** [comment]
I think it's now fixed, available from version 0.6.28
