### ISSUE TITLE
[Feature]: Background Progress Bar in Mini Player

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1117]
### Description

This request actually came from a different ViMusic fork called [ViTune](https://github.com/25huizengek1/ViTune). It has a background progress bar in mini player which looks pretty clean. Since it's also in Kotlin, you might be able to use it as reference.

### Suggested Solution

**This is how it looks like in ViTune:-**
![IMG_20240318_010000](https://github.com/fast4x/RiMusic/assets/99175083/0cf4b037-3554-4b97-aff6-b61903a387d0)
It also goes under device navigation bar which is something i don't like

**So here's my concept**
![Picsart_24-03-18_00-12-58-602](https://github.com/fast4x/RiMusic/assets/99175083/d2577c9e-e1a1-41c0-ad90-67d254836cb9)
Also it'll not create any overlapping problem if bottom navigation bar gets implement in RiMusic in future.

**Comment by OrangeZXZ** [comment]
I would love if it looked like on ViTune!
also the concept i dont like since that bottom bar is not filled as well

**Comment by NikunjKhangwal** [comment]
> I would love if it looked like on ViTune! also the concept i dont like since that bottom bar is not filled as well

Let see what fast4x prefer

**Comment by Vishcot** [comment]
Would seriously look so satisfying! @fast4x what do you think about it?

**Comment by fast4x** [comment]
I think it’s a nice idea

**Comment by Vishcot** [comment]
> I think it’s a nice idea

Would love to see this, if its possible 😀

**Comment by fast4x** [comment]
Implemented, available from version 0.6.27

**Comment by NikunjKhangwal** [comment]
It still blows my mind how talented you are. I've never seen any other developer implementing whole new features and fixing bugs this quickly. You understand the source code of your project way too well.

**Comment by fast4x** [comment]
> It still blows my mind how talented you are. I've never seen any other developer implementing whole new features and fixing bugs this quickly. You understand the source code of your project way too well.

Thank you, I can tell you that I study the code trying to find the best solution as quickly as possible at that time.
Thank you

**Comment by fast4x** [comment]
Implemented background progress bar also in player page, enable/disable by player appearance settings.
Available from version 0.6.27

**Comment by OrangeZXZ** [comment]
> Implemented background progress bar also in player page, enable/disable by player appearance settings.
> Available from version 0.6.27

what do you mean on player page? the background or the bottom bar?

**Comment by sayyid5416** [comment]
> > Implemented background progress bar also in player page, enable/disable by player appearance settings.
> > Available from version 0.6.27
> 
> what do you mean on player page? the background or the bottom bar?

in app settings

**Comment by fast4x** [comment]
> > Implemented background progress bar also in player page, enable/disable by player appearance settings.
> > Available from version 0.6.27
> 
> what do you mean on player page? the background or the bottom bar?

https://github.com/fast4x/RiMusic/assets/1484476/ba83010c-b6b8-4a24-9e93-9f7c08da323c

this... enable/disable in player appearance settings...

**Comment by OrangeZXZ** [comment]
> > > Implemented background progress bar also in player page, enable/disable by player appearance settings.
> > > Available from version 0.6.27
> > 
> > what do you mean on player page? the background or the bottom bar?
> 
> https://github.com/fast4x/RiMusic/assets/1484476/ba83010c-b6b8-4a24-9e93-9f7c08da323c
> 
> this... enable/disable in player appearance settings...

that looks cool but I think it could be a bit changed it the next update il do a issue after testing it also could you move the speed at the Top or bottom of the button maybe outside of it too if the dosen't bother you because it feels weird where it is actualy

**Comment by fast4x** [comment]
Yes no problem

**Comment by NikunjKhangwal** [comment]
Personally not a fan of it but I'm glad there's a option to disable it. I only want it in mini player

**Comment by OrangeZXZ** [comment]
> Personally not a fan of it but I'm glad there's a option to disable it. I only want it in mini player

yeah showing in miniplayer could be nice too but then you need to close the player to see it

**Comment by NikunjKhangwal** [comment]
> yeah showing in miniplayer could be nice too but then you need to close the player to see it

That's what i wanted honestly and that's how it works in ViTune. It's just a cool visual feature. Showing mini player on main player would make it cluttered and i can't think of any other idea. But as fast4x said this feature could evolve later.
