### ISSUE TITLE
La app se cierra

### ISSUE THREAD

**Issue by Isav08** [fast4x/RiMusic#1121]
### Steps to reproduce the bug

Se cierra.

### Expected behavior

Al presionar archivos del dispositivo se cierra la app.

### Actual behavior

Persistente bug.

### Screenshots/Screen recordings

![IMG_20240317_163510](https://github.com/fast4x/RiMusic/assets/163780688/0ed2d61b-4880-445c-af37-87c1ce668faa)
![Screenshot_20240317-163436](https://github.com/fast4x/RiMusic/assets/163780688/11c2fc6a-2314-4fec-a098-77a2f589a76a)

### RiMusic version

0.6.26.1

### Android version

Android 7.0

### Additional information

Este bug viene de versiones anteriores.

**Comment by fast4x** [comment]
https://rimusic.xyz/download try this custom version.

**Comment by Isav08** [comment]
> https://rimusic.xyz/download try this custom version.

Gracias, pero el problema persiste.

**Comment by fast4x** [comment]
When you open local files don’t ask you for access permissions to local files?

**Comment by Isav08** [comment]
> When you open local files don’t ask you for access permissions to local files?

Los permiso ya se los había otorgado antes, y el problema sigue igual.
![IMG_20240318_005538](https://github.com/fast4x/RiMusic/assets/163780688/ac51a44b-4528-40df-badc-2ed140e2ef6a)

**Comment by JZITNIK-github** [comment]
Lo siento, pero no tengo un teléfono con Android 7 en el que pueda probar este error. Sería realmente bueno si pudieras proporcionar algunos registros. Puedes usar alguna aplicación como SysLog para capturar logcat. ¿Este error comenzó con la última actualización o apareció antes?

PS for @fast4x : I don't think that the problem is with the commit where I used the MediaStora.Audio.Media.TITLE because as my last knowledge this property was there way before Android 7. So without logs I can't do much because I don't have Android 7 phone.

**Comment by fast4x** [comment]
@JZITNIK-github ok

**Comment by fast4x** [comment]
@Isav08 try this custom version please, download from website https://rimusic.xyz/download

**Comment by Isav08** [comment]
> Lo siento, pero no tengo un teléfono con Android 7 en el que pueda probar este error. Sería realmente bueno si pudieras proporcionar algunos registros. Puedes usar alguna aplicación como SysLog para capturar logcat. ¿Este error comenzó con la última actualización o apareció antes?
> 
> PS for @fast4x : I don't think that the problem is with the commit where I used the MediaStora.Audio.Media.TITLE because as my last knowledge this property was there way before Android 7. So without logs I can't do much because I don't have Android 7 phone.

Desconozco de que versión viene el error, pero las dos últimas versiones anteriores a esta ya estaba ese error.

[2024-03-19_09.48.zip](https://github.com/fast4x/RiMusic/files/14653023/2024-03-19_09.48.zip)

**Comment by Isav08** [comment]
> @Isav08 try this custom version please, download from website https://rimusic.xyz/download

Gracias, el primer bug persiste la app se cierra al entrar a archivos del dispositivo, pero el último bug ya fue arreglado y ya no se cierra al crear lista personalizada.

**Comment by Isav08** [comment]
Eh estado usando versiones anteriores y esto fue lo que paso:

Versión 0.6.9  
La app si me permitia entrar en archivos del dispositivo, pero no reproducía
![IMG_20240319_113634](https://github.com/fast4x/RiMusic/assets/163780688/bdeb80e5-4a96-474e-b9d1-454b0f09bf6a)
![IMG_20240319_113701](https://github.com/fast4x/RiMusic/assets/163780688/a9e15597-545e-41e1-b146-8f41f317e9fc)
![Screenshot_20240319-113052](https://github.com/fast4x/RiMusic/assets/163780688/26d5e551-7c4c-4e2b-be8c-6e4feab2e693)

Versión 0.6.10

La app si permitía entrar en archivos del dispositivo, pero al presionar a cualquier canción se cerraba.
![IMG_20240319_113736](https://github.com/fast4x/RiMusic/assets/163780688/f3010c44-c6a1-4c9e-baa5-c48d6885c99e)
![Screenshot_20240319-113545](https://github.com/fast4x/RiMusic/assets/163780688/5d2b7815-38ac-4508-b965-dbc1398326dc)

**Comment by fast4x** [comment]
Let me understand better, now you see the list of songs of the device or immediately crashes before you see the list?

**Comment by Isav08** [comment]
> Let me understand better, now you see the list of songs of the device or immediately crashes before you see the list?

En la version actual al presionar archivos del dispositivo la app se cierra inmediatamente, en la versiones antiguas como 0.6.9 la app no se cierra al presionar archivos del dispositivo y puedo ver la lista de canciones pero no reproduce y en la versión 0.6.10 puedo ver la lista pero al presionar cualquier canción se cierra.

**Comment by fast4x** [comment]
try this NEW custom version please, download from website https://rimusic.xyz/download

**Comment by Isav08** [comment]
> try this NEW custom version please, download from website https://rimusic.xyz/download


https://github.com/fast4x/RiMusic/assets/163780688/413a311d-7f15-49c5-abe0-88fbcfd7e473

**Comment by fast4x** [comment]
How many files do you have on your device? The error may be due to memory failure.

**Comment by Isav08** [comment]
> How many files do you have on your device? The error may be due to memory failure.

Pocos archivos, unas cuantas app y no mas de 20 archivos de audio. Tengo disponible 800 mb de espació,
El uso que le doy al celular es relativamente básico y no eh tenido ningún problema con el en ninguna otra aplicación.

**Comment by fast4x** [comment]
Re try new custom https://rimusic.xyz/download

**Comment by Isav08** [comment]
Ya lo probe de nuevo y el bug persiste.

https://github.com/fast4x/RiMusic/assets/163780688/f97cc154-524a-499a-9c56-6ccb035bf200


https://github.com/fast4x/RiMusic/assets/163780688/9b7c9de6-8672-4d0f-a58f-a3b1c6dafdcc

**Comment by fast4x** [comment]
It’s a permission issue, watch the first video and open the permission request that you can’t click.
Go to phone settings > apps > permissions

**Comment by fast4x** [comment]
I make new custom soon

**Comment by Isav08** [comment]
> It’s a permission issue, watch the first video and open the permission request that you can’t click. Go to phone settings > apps > permissions

En el primer vídeo decidí otorgarle los permisos al entrar a la app. Y en el otro antes de entrar.

**Comment by fast4x** [comment]
Soon i create a new version

**Comment by fast4x** [comment]
New custom version ready, please try https://rimusic.xyz/download

**Comment by Isav08** [comment]
> New custom version ready, please try https://rimusic.xyz/download


https://github.com/fast4x/RiMusic/assets/163780688/af5953c3-2ec8-4087-80af-4152cab0eafe

**Comment by Isav08** [comment]
> Hi, New custom version ready, please try https://rimusic.xyz/download
> 
> After this I have nothing more to do

El bug persiste, pero gracias por todo.

**Comment by fast4x** [comment]
I'm sorry I've to do all possible

**Comment by JZITNIK-github** [comment]
Probably fixed in upcoming release.

**Comment by Isav08** [comment]
> Probably fixed in upcoming release.

Solucionado funciona perfectamente:

![Screenshot_20240329-210915](https://github.com/fast4x/RiMusic/assets/163780688/962a5918-289a-4477-a461-e985b4ae889c)

**Comment by JZITNIK-github** [comment]
> Solucionado funciona perfectamente:

Awesome. Thanks for your patience.
