### ISSUE TITLE
Song name looks bad

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1122]
### Description

![IMG_20240318_104726](https://github.com/fast4x/RiMusic/assets/148480722/03587563-6f91-46c3-824a-f73a2840e0bb)

### Suggested Solution

Songs having albums looks ok. But songs having no albums or video songs from YouTube looks like this. Looks like a error. Please add any symbol for this also. And colour also different.

Another request, why video songs not playing?

**Comment by fast4x** [comment]
Ok soon i send custom version to try

**Comment by SureshTimma** [comment]
> Ok soon i send custom version to try

Ok

**Comment by fast4x** [comment]
My bad, color is deactivated because code of album isn't present.

**Comment by SureshTimma** [comment]
> My bad, color is deactivated because code of album isn't present.

Is it possible to get back album code?
