### ISSUE TITLE
Trying to customize an album bugs totally with no way to reset

### ISSUE THREAD

**Issue by Davutha** [fast4x/RiMusic#1123]
### Steps to reproduce the bug

Go to any album
Customize an album (the name, cover art, etc)
Close the app or go to any other menu

### Expected behavior

The album stays customized or at least resets to default 

### Actual behavior

The album name turns null and the cover art goes blank, and sometimes crashes the app

### Screenshots/Screen recordings

![Screenshot_2024-03-18-09-10-22-350_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/68203036/795102df-0abd-44d5-aaeb-e31da6c8643f)

### RiMusic version

0.6.26.1

### Android version

Android 13 (MIUI 14)

### Additional information

The issue was present before, but with this last update the issue got worse

**Comment by fast4x** [comment]
ok thanks

**Comment by fast4x** [comment]
not

**Comment by fast4x** [comment]
I need a few days

**Comment by Juggalage** [comment]
I find that I have the opposite problem of this. Sometimes an album/single will just show "null" info (album title, artist name, album art) but will have all the songs loaded. To fix this, I have to customize the album. With the new implementation of a swipe down to refresh for quick picks, I wonder if something similar for albums could fix this issue by giving the player another chance to load everything up.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.47
