### ISSUE TITLE
Import play lists fails

### ISSUE THREAD

**Issue by pst007x** [fast4x/RiMusic#1126]
### Steps to reproduce the bug

1. Select IMPORT PLAYLIST
2. Select YOUTUBE PLAYLIST.CSV
3. RiMusic app closes

### Expected behavior

Playlist should import

### Actual behavior

App closes

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/6573564/ca83e054-6fb5-44a4-8462-0328d36251b7

### RiMusic version

6.26.1

### Android version

Android 14

### Additional information

I have tried a text file too.

**Comment by fast4x** [comment]
Do you can upload a sample file you have used?

**Comment by pst007x** [comment]
[My YouTube Music Library.csv](https://github.com/fast4x/RiMusic/files/14642769/My.YouTube.Music.Library.csv)

**Comment by fast4x** [comment]
Your file does not have the compatible structure as written on the wiki.
https://github.com/fast4x/RiMusic/wiki/FAQs#what-is-the-csv-file-structure-for-importing-a-playlist-in-library

Also the file you created does not even contain song codes.

**Comment by pst007x** [comment]
O

> Your file does not have the compatible structure as written on the wiki. https://github.com/fast4x/RiMusic/wiki/FAQs#what-is-the-csv-file-structure-for-importing-a-playlist-in-library
> 
> Also the file you created does not even contain song codes.

Odd, that was exported from YT Music. Ok, I'll see if there is another way to export. Thanks
