### ISSUE TITLE
Selección desaparece al desplazar.

### ISSUE THREAD

**Issue by Isav08** [fast4x/RiMusic#1132]
### Steps to reproduce the bug

1- Seleccionar.
2- desplazar

### Expected behavior

Bug persistente.

### Actual behavior

Este bug viene de versiones anteriores.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/163780688/a8e7d668-423a-4e6d-80b7-5f87f6cafbc4

### RiMusic version

0.6.26.1

### Android version

Android 7.0

### Additional information

El bug solo desaparece la marcación pero no la cancela.
Y tal vez deberían agregar la opción 
de seleccionar todo.

**Comment by fast4x** [comment]
ok

**Comment by fast4x** [comment]
Fixed, available from version 0.6.27
