### ISSUE TITLE
Bollywood playlist

### ISSUE THREAD

**Issue by 3angl** [fast4x/RiMusic#1134]
### Steps to reproduce the bug

1. Go to search.
2. Search Bollywood songs
3. Click on Playlist option
4. Then further click on any playlist of Bollywood songs especially new Bollywood songs.
5. Here is main problem - only showing loading page.

### Expected behavior

Just want to open Bollywood songs playlist and play.

### Actual behavior

Only showing loading animation.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/164104174/f5cb9ab4-d453-463e-909a-a917606da971

### RiMusic version

0.6.24

### Android version

Android 13

**Comment by fast4x** [comment]
ok I'll try to check

**Comment by fast4x** [comment]
It seems to be fixed, available from version 0.6.29
