### ISSUE TITLE
[Feature]: Increase visibility of floating search button

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1139]
### Description

The floating search bar is not very visible specially when adapting a lighter color from song cover art. It's not a problem indoors but i tried this app outdoors for the first time today and it was barely visible.

### Suggested Solution

Either make the search button background slightly darker or add a thin outline around it.
![IMG_20240320_114321](https://github.com/fast4x/RiMusic/assets/99175083/2c96c1a9-f459-45a8-9bf8-e8cc1303bb51)

**Comment by fast4x** [comment]
Do you mean to add a darker background color?

**Comment by NikunjKhangwal** [comment]
Yes. Make it just slightly darker

**Comment by fast4x** [comment]
Improved, available from version 0.6.30
