### ISSUE TITLE
Search inconsistency in settings

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1140]
### Description

Just a little inconsistently i noticed. When you search for something in settings and toggle a button on or off sometimes the insertion point move in front of the text.
![IMG_20240320_122640](https://github.com/fast4x/RiMusic/assets/99175083/ab97cded-fe4f-47ab-b7cc-2d1cab741c74)

### Suggested Solution

Keep the insertion point where it was before changing the toggle

**Comment by fast4x** [comment]
In the next version it's just improved, wait for  it and try, thanks.

**Comment by NikunjKhangwal** [comment]
Hello, the new search icon is added but the bug i pointed out (insertion point moving in front of text) is still there.

**Comment by fast4x** [comment]
Hi, yes you’re right but with that search version I can’t fix it. It will be auto-rigged with the new research I’m developing.

**Comment by NikunjKhangwal** [comment]
Ah! Ok got it
