### ISSUE TITLE
Save to device downloads.

### ISSUE THREAD

**Issue by Genuineuserhubro** [fast4x/RiMusic#1143]
### Description

Although songs are saved for offline use but I request if there is an option to export or save the song in device downloads, it would be a great option to have as we would be able to use the music in different players and set it as a ringtone or whatever we like you know ... 

Please add this feature in the next update, blessings and thanks from my side. Hoping for a positive response 🙂.

### Suggested Solution

I don't know man , you can call me illiterate for this sheit ...

**Comment by ikanakova** [comment]
Songs are not downloaded, but cached for offline listening (more here https://github.com/fast4x/RiMusic/issues/993#issuecomment-1986922750) and I don't think download to file is planned.

**Comment by fast4x** [comment]
Sorry but the reason is simple, RiMusic is not a music downloader from YT/YTM

**Comment by dAtA-TRoN** [comment]
> ### Description
> 
> Although songs are saved for offline use but I request if there is an option to export or save the song in device downloads, it would be a great option to have as we would be able to use the music in different players and set it as a ringtone or whatever we like you know ... 
> 
> Please add this feature in the next update, blessings and thanks from my side. Hoping for a positive response 🙂.


Maybe you should take a moment to consider what you're talking about.

**Comment by Genuineuserhubro** [comment]
> > ### Description
> > Although songs are saved for offline use but I request if there is an option to export or save the song in device downloads
> 
> Maybe you should take a moment to consider what you're talking about.

😂😭 I just wanted a song for my morning alarm so I needed it . I thought if I could just simply download it and use it but , music doesn't show in the device downloads. 

Now you have it , the reason why asked it. 
Pheww I'm tired now 😮‍💨.
