### ISSUE TITLE
Some More Pety UI Changes 

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#1144]
### Description

1. Favourites Title is not aligned.
2. Some texts like total playtime inside the player look oddly placed in my opinion.
3. Some areas of app looks awful ( needs an upgraded look or removal. )

### Suggested Solution

1. I request to change the alignment of Favourites title to left if the player is right aligned.
![Screenshot_20240320-224009](https://github.com/fast4x/RiMusic/assets/136909951/ee9a96e0-343f-4915-babd-abd40b29bf83)

2. If possible please add a toggle to turn it off and onn as i will personally toggle it off always, and when it is toggled off, Name title and ❤️ (Favourite icon ) comes back to top, leaving only normal padding btw thumbnail's bottom and title :-
![Screenshot_20240320-224405](https://github.com/fast4x/RiMusic/assets/136909951/2f51821c-78f0-4346-8a99-91c90dc76712)

3. If possible please make it similar to the songs list or change the look of it as it doesn't match the dynamic color theme as well as other themes as well, also texts next to it, specifying total number of songs and total playtime aligned to left looks very much odd.
![Screenshot_20240320-223930](https://github.com/fast4x/RiMusic/assets/136909951/b19ce581-a587-4a9f-aff8-24cae5e8a50b)

In my opinion you can make it as similar to songs list similar like this:
![Screenshot_20240320-223912](https://github.com/fast4x/RiMusic/assets/136909951/26818aac-d91b-41b4-8a6f-96f38ab52792)

OR

I request you to make that greyish part at least compatible with themes (using the same color that is used in the queue list)..as in the whole theme it is the only area that looks the same and greyish always.

**Comment by fast4x** [comment]
Point 2 (in player appearance settings) and 3 implemented, available from version 0.6.27

**Comment by Vishcot** [comment]
> Point 2 (in player appearance settings) and 3 implemented, available from version 0.6.27
> 

What did u do with point number 3, made it dynamically themed or removed that portion?

**Comment by fast4x** [comment]
dynamically

**Comment by Vishcot** [comment]
> > Point 2 (in player appearance settings) and 3 implemented, available from version 0.6.27
> > 
> 
> First of all, thankyou so much for implementing things and crushing bugs so fast! ⏩
Btw
What did u do with point number 3, made it dynamically themed or removed that portion? 
>

**Comment by Vishcot** [comment]
> dynamically 

@fast4x as you've said you updated the dynamic theme color.
One more request if you like, and will be worthy change.

How would it look, if it looks like this : (sorry for bad editing skills 😔)

![Picsart_24-03-21_01-06-22-057.png](https://github.com/fast4x/RiMusic/assets/136909951/99ccc5ab-c03a-4da1-b596-e857eb846236)

**Comment by fast4x** [comment]
It's a good idea, as is icon buttons can move up, I'll try

**Comment by Vishcot** [comment]
> It's a good idea, as is icon buttons can move up, I'll try 

Yeah, the total number of songs and duration will also look good above album arts. 🫡🫡

**Comment by sayyid5416** [comment]
- Won't 10 album arts be too much 🤔 
- Also, empty space can be used like #1086

**Comment by Vishcot** [comment]
> - Won't 10 album arts be too much 🤔 
> - Also, empty space can be used like #1086 

Ohhh this is just awesome!
I agree! 👍💯
@fast4x please discard my drawing and please work on #1086 it is much better in looks! 🤠

**Comment by Vishcot** [comment]
> - Won't 10 album arts be too much 🤔 
> - Also, empty space can be used like #1086 

"I dislike the empty space in this area; all the other sections are overly cluttered with various icons, while this one is too sparse. That's why I prefer it to be done my way, although option #1086 is a valid suggestion, it's not quite what I had in mind."

Now, let's discuss with @fast4x how he would like to implement this."
