### ISSUE TITLE
App crashing in "Songs"

### ISSUE THREAD

**Issue by Tayurivv** [fast4x/RiMusic#1146]
### Steps to reproduce the bug

I open the application, go to the tab "Songs" After that I turn on any song from the list, the application crashes

### Expected behavior

I wish the songs worked properly

### Actual behavior

"Songs" crashing 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/164246093/e71726d2-efbc-4dd0-8866-41172de3ef74

### RiMusic version

0.6.26.1

### Android version

Android 12

### Additional information

I carried out tests, for example, I downloaded Vimusic, uploaded the database of my songs there, and everything worked well, I do the same thing in Rimusic, the same problem occurs the "songs" is crashing. I tried clearing all the application data, then it worked properly, the songs played perfectly. I think the problem is that I have too many songs. About 2000, and the application is apparently not optimized for that

**Comment by Tayurivv** [comment]
[test.zip](https://github.com/fast4x/RiMusic/files/14672212/test.zip)
If you need it, here is my data base with music

**Comment by fast4x** [comment]
Tomorrow i'll try it

**Comment by Tayurivv** [comment]
Thanks

**Comment by fast4x** [comment]
Hi, look video, restore is ok, attention your crash depend from rapid scrolling in songs page, because first time cover images cache will be downloaded when you scroll....
Scroll slowly... when images cache is completed will be ok

https://github.com/fast4x/RiMusic/assets/1484476/e0adf747-365c-4d01-af9c-61216e102fea

**Comment by Tayurivv** [comment]
I think the problem is that my phone can't handle a lot of songs. It needs to be optimized so that it loads only part of them. Here is the proof of my theory in the video. I scroll slowly, and it crashes not because of the scroll, but when I click on the song. Thanks in advance for your understanding. 

https://github.com/fast4x/RiMusic/assets/164246093/b9029699-7c70-42f0-b920-60e094aacad4

**Comment by Tayurivv** [comment]
That is, when I enter a search, I limit the number of songs, and it doesn’t crash. And when there are 5000 of them, the phone can’t stand it and crashes. Well, if anything, just add the ability to clear all songs in the next update please

**Comment by fast4x** [comment]
Maybe I've understand, is queue wich crash when songs number is high... I'll do fix it...

**Comment by fast4x** [comment]
Add limit queued songs from home songs.
Available from version 0.6.27
