### ISSUE TITLE
Unclear Linking and Unresponsive Buttons in Player View

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1152]
### Steps to reproduce the bug

1. Open the player view.

2. Tap once on the song title or artist name.

### Expected behavior

• Single tapping on the song title or artist name should redirect to the respective page.

• Tapping on the artist name should lead to the artist page, not to the song tab.

### Actual behavior

• Requires double tapping to be redirected.

https://github.com/fast4x/RiMusic/assets/71184627/9616b3b7-189c-423e-a8a2-7507dc822d3c

• Tapping on the artist name opens the song tab instead of the artist page.

### RiMusic version

0.6.26.1

### Android version

Android 13

### Additional information

The issue I have with this is twofold. Firstly, the need for double tapping creates a perception of unresponsiveness and diminishes the user experience. Secondly, when tapping on the artist name, instead of being directed to the artist page, the song tab is opened, which is confusing and counterintuitive. Improving the linking behavior to require only a single tap and ensuring that tapping on the artist name leads to the artist page would significantly enhance usability and user satisfaction.

**Comment by dAtA-TRoN** [comment]
A small addition:
Please align the song title and the artist name at the same level, as they are currently slightly misaligned. If possible, also enlarge the hitbox around the artist name to match the size of the hitbox around the song title.

![IMG_20240322_072902.jpg](https://github.com/fast4x/RiMusic/assets/71184627/383b6ece-e126-4edc-976a-4906514b3252)

**Comment by fast4x** [comment]
Single tapping on the song title ... isn't there a specific single song page...

**Comment by fast4x** [comment]
> A small addition:
> Please align the song title and the artist name at the same level, as they are currently slightly misaligned. If possible, also slightly enlarge the hitbox around the artist name to match the size of the hitbox around the song title.
> 
> ![sketch1711089243336.png](https://github.com/fast4x/RiMusic/assets/71184627/846ee75d-a168-4c55-9709-ab221ce0911c)

i can use same font and icon size of title

**Comment by dAtA-TRoN** [comment]
> Single tapping on the song title ... isn't there a specific single song page...

What precisely are you trying to convey? That tapping on the song title should direct to the single song page rather than the album overview? That, in my opinion, would be counterproductive. It seems more sensible to have the option to immediately see which other songs are on the album, rather than receiving an endless list of random songs by that artist. Or did I misinterpret?


> i can use same font and icon size of title 

Perhaps not; I believe that wouldn't complement the aesthetic well. However, I've also considered that there may be no other option than what you described. So, let's leave it as is. Nevertheless, it would be appreciated if you could align the song titles and artist names to the same level.

**Comment by fast4x** [comment]
Ok as before but aligned the name of the artist to the title

**Comment by dAtA-TRoN** [comment]
> Ok as before but aligned the name of the artist to the title

That would be great. It's just a small thing, but I don't know about you: for me, when I notice these little inconsistencies, I can't ignore them anymore 😅.

And what about the hyperlinks? Is my suggestion regarding them okay?

**Comment by fast4x** [comment]
On how to avoid double clicking on the title at the moment I can not do anything else sorry

**Comment by fast4x** [comment]
Also fixed artist page.
Available from version 0.6.27

**Comment by dAtA-TRoN** [comment]
> On how to avoid double clicking on the title at the moment I can not do anything else sorry

No problem. I wonder what the issue might be.

> Also fixed artist page.
> Available from version 0.6.27

Fast as always 😌👌🏼.

**Comment by fast4x** [comment]
> Fast as always 😌👌🏼.

Is that a flaw? ahahaha

**Comment by dAtA-TRoN** [comment]
> But tapping on the icons once does the same thing. 

Watch my video further up.

**Comment by dAtA-TRoN** [comment]
> I'm talking about the icons not the texts. Icons are just alternatives of the texts. So, the double tapping on the texts to redirect to respective pages is okay. Since the icons does the same thing with one tap.
> 
> I think it's even better that it has to be double tap on the texts because sometimes user might end up tapping on those texts accidentally and if that redirects to another page then that can irritate the user.

I didn't know that the icons are also buttons and that they behave differently, but it's good to know now, thank you. However, having two buttons for tag informations is strange and inconsistent. Additionally, I can't agree with the double tap feature; it goes against the app's design language. Double tapping isn't common in the app or in other apps I know (it's more of a Windows thing). It feels out of place and confusing. If people accidentally tap it, even better—they'll discover the feature exists.

**Comment by dAtA-TRoN** [comment]
> It's not that of a big deal. I'm pretty sure most users doesn't have problem with this. But I can be wrong.

I didn't claim it's a 'big deal.' It's just unpleasant and shouldn't be this way. And let's add that there haven't been 'big deals' for a long time when it comes to issues with the app. I think we're already dealing with the finer details.

**Comment by fast4x** [comment]
> I wasn't aware that the icons also function as buttons and exhibit different behaviors, but I appreciate knowing now, thank you. Nevertheless, having two buttons for each of the tag information options, each reacting differently to the same action, seems odd and inconsistent. Additionally, I disagree with the double-tap feature (bug?); it contradicts the app's design principles. Double-tapping isn't a common interaction within this app or other apps I'm familiar with (it's more characteristic of Windows, not Android). It feels out of place and confusing. If people accidentally tap it, even better—so they'll discover the feature exists.

Unfortunately, the double tap is triggered by the function of the scrolling text. In the future I modify that specific function and the problem is solved, takes some time and is scheduled later.

**Comment by dAtA-TRoN** [comment]
> Unfortunately, the double tap is triggered by the function of the scrolling text. In the future I modify that specific function and the problem is solved, takes some time and is scheduled later.

OK. thank you very much for the detailed explanation.

https://github.com/fast4x/RiMusic/assets/71184627/ad4bcc60-67ff-4d05-be73-6008834e0a4c

**Comment by sayyid5416** [comment]
> A small addition: Please align the song title and the artist name at the same level, as they are currently slightly misaligned. If possible, also slightly enlarge the hitbox around the artist name to match the size of the hitbox around the song title.
> 
> ![sketch1711089243336.png](https://private-user-images.githubusercontent.com/71184627/315908805-846ee75d-a168-4c55-9709-ab221ce0911c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMzA3NTYsIm5iZiI6MTcxMTEzMDQ1NiwicGF0aCI6Ii83MTE4NDYyNy8zMTU5MDg4MDUtODQ2ZWU3NWQtYTE2OC00YzU1LTk3MDktYWIyMjFjZTA5MTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE4MDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiOTY1YWMyMjZlYWU3OGRjMDdkMzA2ZjBmMjNmZWRiZDA4ZjBhMjYzZGU5MWRkMGI5ZWIyZjcwNGIzZmRjNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vx66Qe7twGP_7xcMf_wH_4o8SVec_NU9a6jd4tw-azQ)

was this not implemented in latest version which released today?

**Comment by fast4x** [comment]
what is not implemented?
![Screenshot_2024-03-22-19-08-13-036_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/40df90d4-a776-4600-ad18-c2c94c873002)

**Comment by sayyid5416** [comment]
> what is not implemented? ![Screenshot_2024-03-22-19-08-13-036_it.fast4x.rimusic.jpg](https://private-user-images.githubusercontent.com/1484476/316125864-40df90d4-a776-4600-ad18-c2c94c873002.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMzE2MjksIm5iZiI6MTcxMTEzMTMyOSwicGF0aCI6Ii8xNDg0NDc2LzMxNjEyNTg2NC00MGRmOTBkNC1hNZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMTgxNTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQ1NWQwMWVkZWUwODFhZjgyMjA4YTAxN2FkYjNjOWIzY2RhZmY2ZTBjZGFlYTMzZDQ2ZDAyMTgyMTRmZDUwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-W9kbXcvSXNwLFpP3jb_yyozLHnDZ2q25OB_ozQXHZU)


![image](https://github.com/fast4x/RiMusic/assets/78584556/b7ddd58a-1c73-4453-b331-a5f95cc3bcda)

Song and artist name are not aligned properly

**Comment by fast4x** [comment]
Some pixel? oooookk

**Comment by sayyid5416** [comment]
> Some pixel? oooookk

😅😅😅

**Comment by dAtA-TRoN** [comment]
> Some pixel? oooookk 

![IMG_20240322_192206.jpg](https://github.com/fast4x/RiMusic/assets/71184627/afcb6691-a20c-4bb2-8934-c8a9fd9a862a)

This is more than just “a few pixels” 😏...

**Comment by sayyid5416** [comment]
> > Some pixel? oooookk
> 
> ![IMG_20240322_192206.jpg](https://private-user-images.githubusercontent.com/71184627/316129520-afcb6691-a20c-4bb2-8934-c8a9fd9a862a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMzIxNzksIm5iZiI6MTcxMTEzMTg3OSwicGF0aCI6Ii83MTE4NDYyNy8zMTYxMjk1MjAtYWZjYjY2OTEtYTIwYy00YmIyLTg5MzQtYzhhOWZkOWE4NjJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE4MjQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NDEyYmUwYjdmYTFlNDZlZjNkYWY4OWY2NTJjZGFhZjJjYzcwZDRhMDA3MTRiOTE5ODkyNzg0Yzc3NDNjMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6wwqzJpoqhmX-6o0kOUORhzF-P_7mWXcgH18kXkXvwA)
> 
> This is more than just “a few pixels” 😏...

Please stop searching these small nuisances. I never noticed it, but now after looking at it, it's now impossible to ignore for me.

**Comment by dAtA-TRoN** [comment]
> Please stop searching these small nuisances. I never noticed it, but now after looking at it, it's now impossible to ignore for me.

![Screenshot_2024-03-22-19-31-37-91_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/fast4x/RiMusic/assets/71184627/947aca34-4afd-4e0d-b96a-9b218d59e889)

Haha, you talk like me. Well, what can I say? Misery loves company, right? 🤣

**Comment by fast4x** [comment]
What your job in your life? 
@dAtA-TRoN @sayyid5416

**Comment by fast4x** [comment]
You’re funny because you have fun, like me.

**Comment by sayyid5416** [comment]
> What your job in your life? @dAtA-TRoN @sayyid5416

I'm currently studying MBBS, but I also play around with python projects time to time _(I like it)_.

Trust me! I don't know Kotlin, otherwise I would've been spending a lot of time in this repo 😅

**Comment by fast4x** [comment]
Fixed, available from version 0.6.28
Soon custom version...

**Comment by fast4x** [comment]
Download custom version from website https://rimusic.xyz/download

**Comment by dAtA-TRoN** [comment]
![Face-Screaming-In-Fear-Emoji-on-transparent-background-PNG.png](https://github.com/fast4x/RiMusic/assets/71184627/2000a944-38b6-447f-921d-f8f486943d64)


You are too good to us!!
