### ISSUE TITLE
Queue Display for Easy Song Navigation in Player 

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#1154]
### Description

I just discovered an app with a beautiful queue system integrated into the main player. Take a look: The entire player interface is going to get a facelift, and I won't suggest implementing this, but it's a nice way to utilize the queue feature and get a view of the upcoming songs.

https://github.com/fast4x/RiMusic/assets/136909951/b7f126ce-4f0f-456d-b389-cf9991a28446

### Suggested Solution

@fast4x Can we use this as inspiration to display upcoming songs in the main player, maybe just 1 or 2 songs? Like this?

![Picsart_24-03-22_16-46-05-916.jpg](https://github.com/fast4x/RiMusic/assets/136909951/7daf2f64-22f7-4b34-9ae0-f2084c1576d8)

**Comment by Nikks84** [comment]
By the way which app is this?🤔

**Comment by Vishcot** [comment]
> By the way which app is this?🤔

Phonograph ( offline music player)

**Comment by fast4x** [comment]
Idea is nice but there is a problemi with space inside the player specially for devices with small screen size.

**Comment by Vishcot** [comment]
> Idea is nice but there is a problemi with space inside the player specially for devices with small screen size.
> 

What if, the down arrow & ri music icon is moved to the inside top with a light shadow behind like YTM.

Reference: 

![Picsart_24-03-22_17-45-17-597.jpg](https://github.com/fast4x/RiMusic/assets/136909951/af1304ad-8eda-4320-b44b-8b079f7add48)

**Comment by fast4x** [comment]
Idea continue to be interesting. I can try...

**Comment by Vishcot** [comment]
I believe it is going to be a very major upgrade on the player screen! 💪

**Comment by SureshTimma** [comment]
@fast4x when will be the update

**Comment by Vishcot** [comment]
> @fast4x when will be the update

Hie bro, as far as we all know, he cares for our requests more than we do.
Just have patience. He will implement and give us an update as early as possible and as better as he can! Trust me! ✅🙏🏻

**Comment by fast4x** [comment]
Building in progress...

**Comment by fast4x** [comment]
Hi, I’m considering how to implement it.

**Comment by Vishcot** [comment]
> Hi, I’m considering how to implement it.

I would always be here if you want to discuss anything.. 🙏🏻

**Comment by fast4x** [comment]
Implemented, show next 2 songs by default disabled, enable/disable from player appearance settings.
Available from version 0.6.28

**Comment by Vishcot** [comment]
> Implemented, show next 2 songs by default disabled, enable/disable from player appearance settings.
> Available from version 0.6.28

@fast4x thank you so much 👏👏
Can you show a glimpse of a new look? 😬

**Comment by fast4x** [comment]
![Screenshot_20240327_232831](https://github.com/fast4x/RiMusic/assets/1484476/04b90ac0-b898-4058-9b49-62d597a65582)

**Comment by sayyid5416** [comment]
Maybe instead of enable/disable switch, give option to show `0` or `1` or `2` songs.

**Comment by sayyid5416** [comment]
btw nice feature

**Comment by fast4x** [comment]
Ok, nice
