### ISSUE TITLE
[Feature]: Progress bar only on mini player

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#1158]
Add a setting to enable behavior of #1117 only in mini player.

**Comment by dAtA-TRoN** [comment]
![100.gif](https://github.com/fast4x/RiMusic/assets/71184627/8e9298fb-4720-435e-8397-13526acaecde)

...AND I NEED IT FAAAAST 😂😂😂😂😂!

**Comment by JZITNIK-github** [comment]
> ![100.gif](https://github.com/fast4x/RiMusic/assets/71184627/8e9298fb-4720-435e-8397-13526acaecde)
> 
> ...AND I NEED IT FAAAAST 😂😂😂😂😂!

I'll implement it.

**Comment by Nikks84** [comment]
Dev be like wait dor the next update😅😅

**Comment by JZITNIK-github** [comment]
> Dev be like wait dor the next update😅😅

You can build it from source if you want. You can also disable this feature until the next update.

**Comment by NikunjKhangwal** [comment]
Came to say it

**Comment by dAtA-TRoN** [comment]
> Came to say it

Another one...

https://github.com/fast4x/RiMusic/assets/71184627/9453b7f5-13d7-4f0f-a94b-0fe0ea96e31e

**Comment by fast4x** [comment]
Soon build a custom version...

**Comment by fast4x** [comment]
Implemented, official available from version 0.6.28

**Comment by fast4x** [comment]
Download custom version from website https://rimusic.xyz/download

**Comment by sayyid5416** [comment]
Looks nice. great work ❤️

**Comment by dAtA-TRoN** [comment]
> Implemented, official available from version 0.6.28

😌👌🏼

> Download custom version from website https://rimusic.xyz/download

Freaking amazing  😱!
