### ISSUE TITLE
[Visual Bug] Latest release - 0.6.27

### ISSUE THREAD

**Issue by marek-guran** [fast4x/RiMusic#1160]
### Steps to reproduce the bug

After update, the visuals are glitching as on screenshots.

### Expected behavior

No glitching.

### Actual behavior

Glitching

### Screenshots/Screen recordings

![Screenshot_20240322-182732](https://github.com/fast4x/RiMusic/assets/26904790/b4b8034c-cdb4-40d7-8009-1c2ff4328de5)
![Screenshot_20240322-182736](https://github.com/fast4x/RiMusic/assets/26904790/e261819b-9327-4fe7-bcaf-2e6053cfae19)

### RiMusic version

0.6.15

### Android version

14

**Comment by dAtA-TRoN** [comment]
Haha, I was just about to report that as well.

**Comment by JZITNIK-github** [comment]
I'm not sure what you mean by glitching. If you mean the background this is new feature. It's called a background progress bar and you can disable it in the player appearance settings.

**Comment by JZITNIK-github** [comment]
> > I'm not sure what you mean by glitching. If you mean the background this is new feature. It's called a background progress bar and you can disable it in the player appearance settings.
> 
> ![Screenshot_2024-03-22-18-49-28-21_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/48682504-6d92-4a1b-8661-0a5e8ae4db84)
> 
> It's cool, but it shouldn't actually happen in fullscreen, right?
> 
> 

It's coded this way. There is already a feature request. #1158 I'm just saying that you can disable it if you want.

**Comment by Vishcot** [comment]
> > I'm not sure what you mean by glitching. If you mean the background this is new feature. It's called a background progress bar and you can disable it in the player appearance settings.
> 
> ![Screenshot_2024-03-22-18-49-28-21_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/48682504-6d92-4a1b-8661-0a5e8ae4db84)
> 
> It's cool, but it shouldn't actually happen in fullscreen, right?
> 
> 

Yessssss! Only minimised will have this progress bar!

**Comment by fast4x** [comment]
> Haha, I was just about to report that as well.
> 
> ![IMG_20240322_184503.jpg](https://github.com/fast4x/RiMusic/assets/71184627/93b224a1-c1a8-4325-bd53-a4bee93c2e5d)

But you don’t like almost anything? 🤣🤣🤣🤣🤣

**Comment by dAtA-TRoN** [comment]
> But you don’t like almost anything? 🤣🤣🤣🤣🤣

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/0bff187f-30a6-4ff6-8afe-f401ea8af440)

THAT'S A WILD ACCUSATION!!

**Comment by fast4x** [comment]
just kidding! 😜😉😂

**Comment by Vishcot** [comment]
I don't know why, but for these fixes i just can't wait for a whole week.
Feels like as soon as 4x fixes this from the last update, he gives us an update without letting us wait for whole week 😔😔

**Comment by fast4x** [comment]
Implemented, hide multiplier indicator if not set.
Improved, available from version 0.6.28

**Comment by fast4x** [comment]
Also include new settings for enable/disable background progress in player/miniplayer/both

**Comment by fast4x** [comment]
Download custom version from website https://rimusic.xyz/download

**Comment by fast4x** [comment]
Fixed show speed moltiplier, available from version 0.6.28

**Comment by dAtA-TRoN** [comment]
> Fixed show speed moltiplier, available from version 0.6.28

That's brilliant. I actually wanted to start a thread about it myself. Is only the multiplier number hidden when it's set to 1x, so by default? In my opinion, that shouldn't even have been optional, but rather standard. But hey, I don't want to complain. Everyone should do as they please. But I'm glad that's coming. The app keeps getting better and better 🥳.

**Comment by fast4x** [comment]
Yes, moltiplier show only when is set greater or minor of 1.0x
