### ISSUE TITLE
[Feature]: Different icons for these

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#1161]
![image](https://github.com/fast4x/RiMusic/assets/78584556/4df4e9d6-59fa-47bc-809f-83d584327088)

**Comment by sayyid5416** [comment]
@ikanakova

**Comment by ikanakova** [comment]
I'll look into it next week.

I haven't downloaded the new version yet - is that the icon for playlists and featured?

**Comment by fast4x** [comment]
Done

**Comment by sayyid5416** [comment]
> I'll look into it next week.
> 
> I haven't downloaded the new version yet - is that the icon for playlists and featured?

yes

**Comment by ikanakova** [comment]
> Also, can you remove 'minus' sign from the middle of videos button, it would look better.

I think it's two movie frames on top of each other, but I'll redo the video icon because it really looks like a minus.

**Comment by ikanakova** [comment]
Something along the lines of:
<img src="https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/film.png" width="250">
or:
<img src="https://previews.123rf.com/images/pavlostv/pavlostv1806/pavlostv180600511/102793693-movie-icon-%E2%80%93-stock-vector.jpg" width="250">

**Comment by SureshTimma** [comment]
> <img src="https://previews.123rf.com/images/pavlostv/pavlostv1806/pavlostv180600511/102793693-movie-icon-%E2%80%93-stock-vector.jpg" width="250">

This one

**Comment by sayyid5416** [comment]
> > <img alt="" width="250" src="https://camo.githubusercontent.com/c115fc85fdaad6f9d9790445dabdae302070bc2abda9984140dc2e8ff5e70764/68747470733a2f2f70726576696577732e31323372662e636f6d2f696d616765732f7061766c6f7374762f7061766c6f737476313830362f7061766c6f7374763138303630303531312f3130323739333639332d6d6f7669652d69636f6e2d2545322538302539332d73746f636b2d766563746f722e6a7067">
> 
> This one

yes, looks great, but add some roundness instead of hard edges.

**Comment by ikanakova** [comment]
I'll probably make it like the current icon but instead of "minus" it will be play.

**Comment by ikanakova** [comment]
Featured playlist icon:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/7386daf6-ef8d-4ebc-bc6e-2f625857a5f1" width="25">

**Comment by ikanakova** [comment]
New video icon:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/feb895cb-925d-4802-b6e3-8bfdc143ce38" width="25">

**Comment by ikanakova** [comment]
#1218

**Comment by fast4x** [comment]
Implemented, available from version 0.6.28
