### ISSUE TITLE
Enable/disable for speed

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1162]
### Description

I don't find this feature much useful. 

### Suggested Solution

So I'd love if there was an option to disable this.

![Screenshot_20240322-235920](https://github.com/fast4x/RiMusic/assets/85461823/ce1ba31f-596b-40ff-8c8b-a9b3574a05f0)

### Additional Context

Also I think this shouldnt be visible: 
![Screenshot_20240323-000108](https://github.com/fast4x/RiMusic/assets/85461823/2e6c78b0-fc03-4bc7-a450-ece8ec350593)

**Comment by sayyid5416** [comment]
- I think feature should remain as it is, because it would appear only when holding the `play/pause` button.
- One improvement could be done: _**Do not show `1.0x` in the button when speed is not changed.**_ Basically, show speed multiplier only when speed or pitch is changed.

**Comment by NikunjKhangwal** [comment]
What do you guys think about it?
![Picsart_24-03-23_00-02-53-781](https://github.com/fast4x/RiMusic/assets/99175083/6029dd53-d80c-44b4-b5e0-f8ed21fb6b2f)

**Comment by NikunjKhangwal** [comment]
> There's already lots of digits around the player. So, I think this one is unnecessary.

Yup but i can't think of any other indicator for speed

**Comment by ikanakova** [comment]
I think this could be activated by pressing e.g. a time on the timeline. Definitely not to have another number unless it could be turned off in the settings.

**Comment by NikunjKhangwal** [comment]
> Read what sayyid wrote on his point 2.

That only fixes when you're not using it. The indicator still have to appear somewhere when you're using the feature

**Comment by NikunjKhangwal** [comment]
> Also. You can see the speed once you tap and hold play/pause button. Won't that be enough?

I'm on board with that idea but i don't know if others are going to like it.

**Comment by NikunjKhangwal** [comment]
Then fast4x should remove this indicator right now but save the code behind it. Only add it again with enable/disable through settings if someone ask for it. Right now most people seem to not want it.

**Comment by sayyid5416** [comment]
> Then fast4x should remove this indicator right now but save the code behind it. Only add it again with enable/disable through settings if someone ask for it. Right now most people seem to not want it.

I like it though 😉. Also it looks great right where it is _(atleast in rectangular play button)_. 
- Also design wise, this indicator is more meaningful inside play button than any other place because holding the play button changes the speed too.

**Comment by Vishcot** [comment]
> >  > Read what sayyid wrote on his point 2.
> > 
> > That only fixes when you're not using it. The indicator still have to appear somewhere when you're using the feature
> 
> Then maybe what you suggested is okay. I'm not sure how that'd look though. I mean the whole player. I think with all these icons and digits around its getting "crowded"? (I don't even know the right word…)

I also feel that the addition of icons and digits inside the player makes it look too cluttered. The player is losing its simplicity with all these changes, which go against what once was Vimusic's priority of being a simple yet powerful player. 😶

**Comment by Vishcot** [comment]
> > I also feel that the addition of icons and digits inside the player makes it look too cluttered. The player is losing its simplicity with all these changes, which go against what once was Vimusic's priority of being a simple yet powerful player. 😶
> 
> Same. It's getting really cluttered. Few of these digits should have toggle option I think. And btw the time between thumbnail and song title (which is called "total time of queue") has enable/disable in settings>Player Appearance. 

Yeah, i requested that feature to be on toggle basis. I hated it personally 😂😂

I don't know why, but I just can't wait a whole week for these fixes. It seems like as soon as 4x addresses the issues from the last update, he releases another update without making us wait a full week 😔😔.

**Comment by sayyid5416** [comment]
I've another idea:
- Add option to change speed/pitch from 3 dot menu on top-right corner. _**(Although I still think changing speed/pitch via holding play button is much more intuitive)**_
- and then show the multiplier indicator in here
![image](https://github.com/fast4x/RiMusic/assets/78584556/5a6548f9-0457-48d4-8bb9-25398f048d20)
but with solid bg, something like this
![image](https://github.com/fast4x/RiMusic/assets/78584556/4c1d6725-5021-439e-92cf-d1ff8cebce8c)

**Comment by fast4x** [comment]
Implemented, hide multiplier indicator if not set
Available from version 0.6.28

**Comment by fast4x** [comment]
Download custom version from website https://rimusic.xyz/download

**Comment by sayyid5416** [comment]
> Implemented, hide multiplier indicator if not set Available from version 0.6.28

It's still visible, and now it's below the pause icon

**Comment by fast4x** [comment]
Number indicator have . or , separator?

**Comment by sayyid5416** [comment]
> Number indicator have . or , separator?

It's `1.0x`

**Comment by fast4x** [comment]
Ok I've understand a problem, tomorrow new custom version.
