### ISSUE TITLE
App crashing in "favorites"

### ISSUE THREAD

**Issue by ThaMasEagle** [fast4x/RiMusic#1164]
### Steps to reproduce the bug

1. open app
2. Go to the library
3. go to Favorites 
4. select a song (over 4000 liked songs)

### Expected behavior

You fixed an issue App crashing in "Songs" #1146 but now you have not set a limit in favourites it crashes coz of too many songs liked, it crashes in favourites  because of many songs as while

### Actual behavior

must not crash

### RiMusic version

0.6.27

### Android version

Android 12

**Comment by fast4x** [comment]
Yes i'll fix it, thanks.

**Comment by ThaMasEagle** [comment]
No we should be thanking you man

**Comment by fast4x** [comment]
Fixed, soon i send you a custom version

**Comment by fast4x** [comment]
Download custom version from website https://rimusic.xyz/download

**Comment by SureshTimma** [comment]
> Download custom version from website https://rimusic.xyz/download

I opened rimusic.xyz where is the custom version?

**Comment by fast4x** [comment]
add /download in url 
![Screenshot_2024-03-23-08-36-41-294_com.microsoft.emmx.jpg](https://github.com/fast4x/RiMusic/assets/1484476/af56cac9-fe50-4872-abad-b8455d88c525)

**Comment by ThaMasEagle** [comment]
Thanks

**Comment by SureshTimma** [comment]
> add /download in url 

I'm unable to open this link. I'm from india. I tried with and without vpn.
![Screenshot_2024-03-23-15-24-28-79_1ed61f9b22eb550f606d96180a328dfb.jpg](https://github.com/fast4x/RiMusic/assets/148480722/2b03db0a-a0ec-4611-b152-e90d01ba5c4d)

**Comment by fast4x** [comment]
![app-release.zip](https://github.com/fast4x/RiMusic/files/14731264/app-release.zip)

Take it

**Comment by SureshTimma** [comment]
> ![app-release.zip](https://github.com/fast4x/RiMusic/files/14731264/app-release.zip)
> 
> Take it, is zipped 

Worked. Thank you.

**Comment by fast4x** [comment]
Good
