### ISSUE TITLE
Play Button styles doesn't work in ViMusic interface

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1167]
### Steps to reproduce the bug

1. Enable ViMusic Interface
2. Try all the play button styles

### Expected behavior

Styles should work

### Actual behavior

Only default style and wavy circle is working in ViMusic interface. Others make the play button look like default.

### RiMusic version

0.6.27

### Android version

Android 12

**Comment by fast4x** [comment]
Fixed, available from version 0.6.28

**Comment by fast4x** [comment]
Download custom version from website https://rimusic.xyz/download

**Comment by NikunjKhangwal** [comment]
Do the custom version have same signature as github release? Means I'll be able to update it later right?

**Comment by fast4x** [comment]
Same version same all

**Comment by fast4x** [comment]
> Do the custom version have same signature as github release? Means I'll be able to update it later right?

Update published every Friday

**Comment by NikunjKhangwal** [comment]
Understood 👍🏼

Just tried the custom version. I'm in love with background progress bar, it looks so good.

**Comment by fast4x** [comment]
It’s true I love it and I also use it in the player as well as in the mini player

**Comment by NikunjKhangwal** [comment]
Hello, just noticed disabling play button doesn't disable it in both ViMusic and RiMusic interface
