### ISSUE TITLE
Song locator on Albums 

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1169]
### Description

Some albums has has so many songs. Trying to find how far I've listened gets harder in larger albums.

### Suggested Solution

Implement song locator on Albums as well.

### Alternatives

Or maybe search button?

**Comment by KrisTamang** [comment]
It has in Ri Music themed but
because of bug you can access on some songs..!
In some songs you cant even locate artist

**Comment by fast4x** [comment]
Implemented, avaiblable from version 0.6.28

**Comment by fast4x** [comment]
Download custom version from website https://rimusic.xyz/download

**Comment by fast4x** [comment]
Is simple animation not playing state...

**Comment by fast4x** [comment]
I can change icon with another...

**Comment by fast4x** [comment]
Try to see what kind of icon you would like.

**Comment by fast4x** [comment]
Ok I try

**Comment by dAtA-TRoN** [comment]
Very nice addition but this feature seems to be broken. The indicator only appears, when I hit the 'orientation' button. Then it's there but won't move, if I skip the track. Check a look:

https://github.com/fast4x/RiMusic/assets/71184627/b7d0cd1d-d8b6-4be4-8c29-5f99372f9735

**Comment by fast4x** [comment]
Locator is not automatic, it is a manual function for now that only serves to mark the song playing.

**Comment by dAtA-TRoN** [comment]
> Locator is not automatic, it is a manual function for now that only serves to mark the song playing.

That may be, but it also doesn't work as intended. But AnyoneMouse is already writing a bug report.
