### ISSUE TITLE
erase instead hide songs

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1174]
### Steps to reproduce the bug

![IMG_20240323_032401](https://github.com/fast4x/RiMusic/assets/107674915/cd47fa8f-736d-4d18-81a9-e56bb2579b51)
Why songs i played (by mistake, didnt liked it) store as hidden song??

### Expected behavior

Just erase it from the history..!
And if i played that song again..!
Just act like i played new song

### Actual behavior

Works as hidden songs (not needed)

### RiMusic version

0.1.5

### Android version

9

**Comment by fast4x** [comment]
The hidden songs are those that have been played for the minimum time set in ui settings. 
I found no problems

**Comment by KrisTamang** [comment]
> The hidden songs are those that have been played for the minimum time set in ui settings. I found no problems

It will be better to give option..!
There are some of my favorite song but not showing

**Comment by KrisTamang** [comment]
> The hidden songs are those that have been played for the minimum time set in ui settings. I found no problems

Maybe it will fix ..some of artist and ablum not accessable

**Comment by fast4x** [comment]
> > The hidden songs are those that have been played for the minimum time set in ui settings. I found no problems
> 
> It will be better to give option..!
> There are some of my favorite song but not showing

ok I'll check for favorites

**Comment by fast4x** [comment]
Fixed favorites in home songs, available from version 0.6.28

**Comment by KrisTamang** [comment]
> Fixed favorites in home songs, available from version 0.6.28

Please remove hidden feature instead put erase..!
This sure gonna fix album and artist not accessable in some songs..!
