### ISSUE TITLE
Export playlist bug

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1175]
### Steps to reproduce the bug

![Screenshot_2024-03-23-03-06-01-530_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/107674915/4ae7f2a5-0d36-4d1a-a985-813ba18a4ccc)
I exported all my favorite songs as playlist

### Expected behavior

But album and artist is not accessable..!!
![Screenshot_2024-03-23-03-36-29-356_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/107674915/e62f3472-9993-459b-90e8-90c9d73e896c)

### Actual behavior

Artist and album not accesable

### RiMusic version

0.1.5

### Android version

9

**Comment by fast4x** [comment]
You have exported and reimported? And after album and artisti are inaccessible?

**Comment by KrisTamang** [comment]
> You have exported and reimported? And after album and artisti are inaccessible?

Yes

**Comment by fast4x** [comment]
It work for me, try with new version
