### ISSUE TITLE
[Feature]: Consider these Icons

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1176]
### Description

Hello Dev, I think some of icons in app are confusing. so i select a set of similar icons with their preferences. i will post them below consider once please...

### Suggested Solution

Song:
![Song](https://github.com/fast4x/RiMusic/assets/148480722/e39c10d6-9cd9-4ba0-9b44-e9b1a9411b77)
Artist:
![Artist](https://github.com/fast4x/RiMusic/assets/148480722/98963218-7a7b-4efa-9065-c36d7b31f8d9)
Album:
![Album](https://github.com/fast4x/RiMusic/assets/148480722/6ff6f357-b682-4b0b-a27c-ddefbc80adf1)
User Interface:
![User Interface](https://github.com/fast4x/RiMusic/assets/148480722/27b49cd1-5546-4a67-b10e-73ec30617483)
Miscellaneous:
![Miscellaneous](https://github.com/fast4x/RiMusic/assets/148480722/16c22f40-6f4a-4e71-b04d-77c168672713)
About:
![About](https://github.com/fast4x/RiMusic/assets/148480722/b238ec07-b865-44fb-a223-cf0d3fed60ba)

**Comment by fast4x** [comment]
Hi, are much black. Let’s see what thinks @ikanakova

**Comment by SureshTimma** [comment]
> Hi, are much black. Let’s see what thinks @ikanakova

Ok

**Comment by dAtA-TRoN** [comment]
I like this shit!

**Comment by SureshTimma** [comment]
> I like this shit!

You mean good or Bad?

**Comment by dAtA-TRoN** [comment]
> You mean good or Bad?

Good good 👌🏼👌🏼👌🏼!

**Comment by SureshTimma** [comment]
> > You mean good or Bad?
> 
> Good good 👌🏼👌🏼👌🏼!

Hmm

**Comment by NikunjKhangwal** [comment]
Can Sleep Timer icon get replaced with this?

![lunar-phase-outline-of-the-moon-shape-moon-207a4346e1fa747cb22cebb24de939a9](https://github.com/fast4x/RiMusic/assets/99175083/2b61e40e-be53-4e9c-87df-4c623673ce7a)

**Comment by ikanakova** [comment]
I'll fix the album icon.

I don't really like the song and artist icons. They're not consistent and the artist probably wouldn't look as good as the album does now. User interface I don't know what that icon means at all. I'll think about the app and miscellaneous some more.

**Comment by ikanakova** [comment]
> Can Sleep Timer icon get replaced with this?

There is a moon icon in the assets/ionicons folder that can be used.

**Comment by NikunjKhangwal** [comment]
> There is a moon icon in the assets/ionicons folder that can be used.

Just checked it. Personally i like the one i posted better because it's outlined and more rounder. Try it otherwise ionicons is still better than current alarm one.

**Comment by ikanakova** [comment]
>> There is a moon icon in the assets/ionicons folder that can be used.
> 
> Just checked it. Personally i like the one i posted better because it's outlined and more rounder. Try it otherwise ionicons is still better than current alarm one.

In RiMusic the icons used are filled and only rarely outline (for example undownloaded).

**Comment by NikunjKhangwal** [comment]
> In RiMusic the icons used are filled and only rarely outline (for example undownloaded).

Yeah makes sense. Can you fill the icon i posted if possible? I still like it's shape a bit better

**Comment by ikanakova** [comment]
Do you think one note is better than two for a song? It can swap the icon for the song, because it's in the ionicons folder too. I would leave the artist as it is.

**Comment by ikanakova** [comment]
>> In RiMusic the icons used are filled and only rarely outline (for example undownloaded).
> 
> Yeah makes sense. Can you fill the icon i posted if possible? I still like it's shape a bit better

Sure.

**Comment by dAtA-TRoN** [comment]
> I'll fix the album icon.
> 
> I don't really like the Song and Artist icons. They're not consistent and the Artist probably wouldn't look as good as the album does now. User interface I don't know what that icon means at all. I'll think About and Miscellaneous some more.

Hey, that's awesome, I'm stoked 🙏🏼! About the artist icon: I think one silhouette looks better than two. It just feels less cluttered and easier on the eyes, you know? It doesn't have to be exactly like the one shown above, but maybe give it some more thought?

**Comment by SureshTimma** [comment]
@fast4x @ikanakova @dAtA-TRoN @NikunjKhangwal 

Hi all, I have customised app Icons as per my taste. I will give you the apk link. Check once please... I have tried hard to make it better.

If you like it! I will pull request it!

Apk Link:
https://drive.google.com/file/d/1yXDwHr3KUy_DKqPQcKFAtjyR8PSoYLwO/view?usp=drivesdk

**Comment by dAtA-TRoN** [comment]
> @fast4x @ikanakova @dAtA-TRoN @NikunjKhangwal 
> 
> Hi all, I have customised app Icons as per my taste. I will give you the apk link. Check once please... I have tried hard to make it better.
> 
> If you like it! I will pull request it on GitHub.
> 
> Apk Link:
> https://drive.google.com/file/d/1yXDwHr3KUy_DKqPQcKFAtjyR8PSoYLwO/view?usp=drivesdk
> 
> 

Could you please post a jpeg of it?

**Comment by SureshTimma** [comment]
> > Hi all, I have customised app Icons as per my taste. I will give you the apk link. Check once please... I have tried hard to make it better.
> > 
> > If you like it! I will pull request it on GitHub.
> 
> Could you please post a jpeg of it?

Ok

**Comment by SureshTimma** [comment]
@fast4x @ikanakova @dAtA-TRoN @NikunjKhangwal 

![Screenshot_2024-03-23-15-25-18-64_d85e0fb0256522d570e0ba4254426be1.jpg](https://github.com/fast4x/RiMusic/assets/148480722/a973d9c0-15ac-4ad4-ab18-88ea7d64f8b3)

![Screenshot_2024-03-23-15-25-15-32_d85e0fb0256522d570e0ba4254426be1.jpg](https://github.com/fast4x/RiMusic/assets/148480722/dcee3cf3-8247-420e-8ed9-0345a3a3e11d)

![Screenshot_2024-03-23-15-25-09-32_d85e0fb0256522d570e0ba4254426be1.jpg](https://github.com/fast4x/RiMusic/assets/148480722/6cc60b1f-8202-456e-9570-5007fed7149e)

![Screenshot_2024-03-23-15-25-21-48_d85e0fb0256522d570e0ba4254426be1.jpg](https://github.com/fast4x/RiMusic/assets/148480722/881de6e9-2a72-4ea6-a14f-2e4da3310cbd)

![Screenshot_2024-03-23-15-25-42-08_d85e0fb0256522d570e0ba4254426be1.jpg](https://github.com/fast4x/RiMusic/assets/148480722/34e2c2c2-e9a5-4a73-8270-7954889f3af3)

![Screenshot_2024-03-23-15-25-31-18_d85e0fb0256522d570e0ba4254426be1.jpg](https://github.com/fast4x/RiMusic/assets/148480722/1a5d1e8d-23a7-49a7-84e9-c0cf5b1f40e4)

![Screenshot_2024-03-23-15-25-24-59_d85e0fb0256522d570e0ba4254426be1.jpg](https://github.com/fast4x/RiMusic/assets/148480722/2754bd50-ce0c-48bd-b2ba-f9dc242aa2d1)

**Comment by dAtA-TRoN** [comment]
I personally think it's excellent. Well done. If you could also pay a bit more attention to the consistency of the icon sizes relative to each other, that would be the icing on the cake.

![sketch1711188451134-01.jpeg](https://github.com/fast4x/RiMusic/assets/71184627/d0215bb8-38c1-4d10-a589-8eaddcb94b8c)

But be careful, I don't have anything to say about this matter. It's just my opinion, one among many. Let's see what ikonva has to say.

**Comment by SureshTimma** [comment]
> But be careful, I don't have anything to decide about this matter. It's just my opinion, one among many. Let's see what ikanakova and fast4x has to say about it.

Yes I took waiting for their reply...

**Comment by NikunjKhangwal** [comment]
I prefer older icons for Download, On Device and also sleep timer icon i posted. Mixed opinion on stats icon. For the rest, your new icons definitely look better

**Comment by ikanakova** [comment]
I personally don't like the inconsistency - outline / filled & different note shapes, but it's not up to me, it's up to fast4x to decide. But the artist icon has started to appeal to me 🙂 If fast4x prefers my icons (based on the ionicons), I will redesign the artist icon to be similar to this one.

**Comment by fast4x** [comment]
> I personally don't like the inconsistency - outline / filled & different note shapes, but it's not up to me, it's up to fast4x to decide. But the artist icon has started to appeal to me 🙂 If fast4x prefers my icons (based on the ionicons), I will redesign the artist icon to be similar to this one.

Hi @ikanakova i agree, i like ionicons and i have a preference for it. Redesigning of artist and artists icons are welcome.

**Comment by dAtA-TRoN** [comment]
Your icons are really nice as well. I don't want to interfere with that. Especially considering you've probably put a lot of effort into the app already. However, I'd like to share my thoughts on one small aspect. I feel that the checkmark, especially now that I see the new download icon in action, is a bit too delicate. What do you think? Perhaps it could be a bit bolder?

**Comment by fast4x** [comment]
Keep in mind that RiMusic may have different icons than many other apps, the gentle tick is an interesting and elegant look, which can make a difference.

**Comment by dAtA-TRoN** [comment]
I just find it a little hard to see. But hey, everything's cool. I just wanted it to get out of my chest.

**Comment by SureshTimma** [comment]
> > I personally don't like the inconsistency - outline / filled & different note shapes, but it's not up to me, it's up to fast4x to decide. But the artist icon has started to appeal to me 🙂 If fast4x prefers my icons (based on the ionicons), I will redesign the artist icon to be similar to this one.
> 
> Hi @ikanakova i agree, i like ionicons and i have a preference for it. Redesigning of artist and artists icons are welcome.
> 


Ok. 😔 I worked since morning to find icons and change in app code.

But thanks a lot. I'm new to code and learning Android studio and app development also. So your project helped me. Today i could able to learn about icons and drawable and app structure. Thank you.

But my request is please don't use same icon for two different features.

**Comment by dAtA-TRoN** [comment]
> But my request is please don't use same icon for two different features.

Can you briefly list where you discovered this?

**Comment by SureshTimma** [comment]
> > But my request is please don't use same icon for two different features.
> 
> Can you briefly list where you discovered this?

![Picsart_24-03-23_19-27-34-234.jpg](https://github.com/fast4x/RiMusic/assets/148480722/2124fd36-390d-44c7-bdfb-792f83d5e6d3)

![Picsart_24-03-23_19-25-59-864.jpg](https://github.com/fast4x/RiMusic/assets/148480722/9c5e7b96-ea5d-4fcb-bc9e-2312edf89cf7)

**Comment by sayyid5416** [comment]
Yes, icons for UI and misc needs to be changed.

**Comment by sayyid5416** [comment]
Also take a look at #1072

**Comment by ikanakova** [comment]
I'm getting a little lost. Could you please create where the same icons are for special issues - 1 for each case, so I don't forget something. (@fast4x if something is just about icon changes, feel free to automatically assign me.)

@SureshTimma Do you mind if I take inspiration from your icons?

I'll edit the download icon. @fast4x could you please open issue #953?

**Comment by SureshTimma** [comment]
> I'm getting a little lost. Could you please create where the same icons are for special issues - 1 for each case, so I don't forget something. (@fast4x if something is just about icon changes, feel free to automatically assign me.)
> 
> @SureshTimma Do you mind if I take inspiration from your icons?
> 
> I'll edit the download icon. @fast4x could you please open issue #953?

YouTube can use them freely

**Comment by ikanakova** [comment]
For User Interface, I would like an icon like this one:
<img src="https://cdn-icons-png.freepik.com/512/3159/3159310.png" width="250">
but instead of a PC, it would be a mobile phone and the brush will be filled.
What do you think?

**Comment by ikanakova** [comment]
Instead of the misc icon, I would change the equalizer icon to look something like this:
<img src="https://as2.ftcdn.net/v2/jpg/02/23/33/85/1000_F_223338561_vojS1hk7u50yG0pwYBfZlNnqRqjWRqjD.jpg" width="250">

**Comment by fast4x** [comment]
> I'm getting a little lost. Could you please create where the same icons are for special issues - 1 for each case, so I don't forget something. (@fast4x if something is just about icon changes, feel free to automatically assign me.)
> 
> @SureshTimma Do you mind if I take inspiration from your icons?
> 
> I'll edit the download icon. @fast4x could you please open issue #953?

Is impossible assign to you if you not have added comment....

**Comment by ikanakova** [comment]
>> I'm getting a little lost. Could you please create where the same icons are for special issues - 1 for each case, so I don't forget something. (@fast4x if something is just about icon changes, feel free to automatically assign me.)
>>
>> @SureshTimma Do you mind if I take inspiration from your icons?
>>
>> I'll edit the download icon. @fast4x could you please open issue #953?
> 
> Is impossible assign to you if you not have added comment....

I see, I don't know so many intricacies of github yet 😀

**Comment by ikanakova** [comment]
New Icon artist:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/1462bae4-3cad-4815-8e8a-061ff7132b2f" width="25">

**Comment by ikanakova** [comment]
New IU icon:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/01ca2280-8aab-41e5-a0da-e632c00738a7" width="25">

**Comment by ikanakova** [comment]
New equalizer icon:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/9fa4f811-49a8-4c03-b645-68bafcb0727a" width="25">

**Comment by ikanakova** [comment]
> > In RiMusic the icons used are filled and only rarely outline (for example undownloaded).
> 
> Yeah makes sense. Can you fill the icon i posted if possible? I still like it's shape a bit better

You mean like this?:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/8daf7e42-d8c3-4fb0-bc5a-058b36be2c44" width="25">

**Comment by NikunjKhangwal** [comment]
> > Yeah makes sense. Can you fill the icon i posted if possible? I still like it's shape a bit better
> 
> @NikunjKhangwal You mean like this?: <img alt="" width="25" src="https://private-user-images.githubusercontent.com/38765251/316478930-8daf7e42-d8c3-4fb0-bc5a-058b36be2c44.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjUxNjgsIm5iZiI6MTcxMTM2NDg2OCwicGF0aCI6Ii8zODc2NTI1MS8zMTY0Nzg5MzAtOGRhZjdlNDItZDhjMy00ZmIwLWJjNWEtMDU4YjM2YmUyYzQ0LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDExMDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZjYzYjAzYWQzOTg0NGFjOGI3ZGQxZDU5ZTJhNGQ2OGVlODNlNmY5YzczYzAyNGU4MTVlNTZjNWJjYmVkNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.74SEl9_5A2192-Q0bo_-aaScJQA4zB4QGzRWhKcDG6I">

Yup but it's not the icon i posted right?

**Comment by ikanakova** [comment]
> > > Yeah makes sense. Can you fill the icon i posted if possible? I still like it's shape a bit better
> > 
> > 
> > @NikunjKhangwal You mean like this?: <img alt="" width="25" src="https://private-user-images.githubusercontent.com/38765251/316478930-8daf7e42-d8c3-4fb0-bc5a-058b36be2c44.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjUxNjgsIm5iZiI6MTcxMTM2NDg2OCwicGF0aCI6Ii8zODc2NTI1MS8zMTY0Nzg5MzAtOGRhZjdlNDItZDhjMy00ZmIwLWJjNWEtMDU4YjM2YmUyYzQ0LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDExMDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZjYzYjAzYWQzOTg0NGFjOGI3ZGQxZDU5ZTJhNGQ2OGVlODNlNmY5YzczYzAyNGU4MTVlNTZjNWJjYmVkNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.74SEl9_5A2192-Q0bo_-aaScJQA4zB4QGzRWhKcDG6I">
> 
> Yup but it's not the icon i posted right?

If you fill in the icon you sent and leave the outline, it's the same one that's in the ionicons folder. I removed the outline from this one.

**Comment by ikanakova** [comment]
New sleep timer icon:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/76e57279-e8bb-4260-90dd-4a12e434886f" width="25">

**Comment by NikunjKhangwal** [comment]
Yes. I even made one myself because i was free today but man you're fast. 😅
![Picsart_24-03-25_16-50-18-686](https://github.com/fast4x/RiMusic/assets/99175083/15cd9a54-b84d-42b5-a417-d955f757ee5b)

**Comment by ikanakova** [comment]
#1218

**Comment by SureshTimma** [comment]
@ikanakova hi,
Check below screenshots once. These icons alignment is perfect now. If you want these icons i will upload XML files here...

![Screenshot_2024-03-26-10-23-21-85_016c0e824449847b840c4940e66fadfd.jpg](https://github.com/fast4x/RiMusic/assets/148480722/f82291a5-e964-47be-af18-10e3c621a17e)

![Screenshot_2024-03-26-10-23-26-99_016c0e824449847b840c4940e66fadfd.jpg](https://github.com/fast4x/RiMusic/assets/148480722/b2e1aede-b030-499b-805e-b19a966ed70d)

![Screenshot_2024-03-26-10-23-12-21_016c0e824449847b840c4940e66fadfd.jpg](https://github.com/fast4x/RiMusic/assets/148480722/6a703f96-682b-4d89-af68-c60dd1241315)

**Comment by dAtA-TRoN** [comment]
The album icon looks pretty dope.

![Screenshot_2024-03-26-06-18-24-61_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/fast4x/RiMusic/assets/71184627/bb56615a-16b8-499e-ad66-46c45bbb5630)

**Comment by NikunjKhangwal** [comment]
Man i love these icons. Much more roundier and

**Comment by NikunjKhangwal** [comment]
Man i love these icons. Much more roundier and simple.

**Comment by dAtA-TRoN** [comment]
> Man i love these icons. Much more roundier and simple.

fast4x might consider adding an option for RiMusic icon packs at some point and perhaps provide three packs by default immediately after installation. Maybe sometime in the distant future...

**Comment by fast4x** [comment]
![giphy (3).gif](https://github.com/fast4x/RiMusic/assets/1484476/ea0dfee0-a9c0-4471-8d1c-b2a2773ba0d9)

**Comment by ikanakova** [comment]
>@ikanakova hi,
>Check below screenshots once. These icons alignment is perfect now. If you want these icons i will upload XML files here...

I only add SVG icons. fast4x has the final say in this one.

**Comment by fast4x** [comment]
Today or tomorrow I'll add new icons, I'm sorry my work is pretty heavy these days.

**Comment by NikunjKhangwal** [comment]
Btw i found this collection of official Material icons by Google, free to use. These could be helpful in future so I thought i should share them here: https://fonts.google.com/icons
Here's the guide to use them: https://developers.google.com/fonts/docs/material_symbols

**Comment by sayyid5416** [comment]
> Btw i found this collection of official Material icons by Google, free to use. These could be helpful in future so I thought i should share them here: https://fonts.google.com/icons Here's the guide to use them: https://developers.google.com/fonts/docs/material_symbols

Wow they looks great. Can they be used with windows software, like with pyqt or pyside?

**Comment by fast4x** [comment]
Implemented, available from version 0.6.28
