### ISSUE TITLE
Older Wavy timeline looks better 

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1177]
### Description

![IMG_20240323_034906](https://github.com/fast4x/RiMusic/assets/107674915/53cd3062-5ed8-4f91-9317-0cc0f81453ef)

### Suggested Solution

Older looks better i guess..!

**Comment by fast4x** [comment]
Restored original, available from version 0.6.28
Soon i send you a custom version

**Comment by fast4x** [comment]
Download custom version from website https://rimusic.xyz/download
