### ISSUE TITLE
Player doesn't reapply system equalizer setting on app restart

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#1178]
### Steps to reproduce the bug

1. Open system equalizer from the app
2. Set a setting
3. Save and play a music
4. Restart the app
5. Play a music

### Expected behavior

The player should apply the equalizer setting automatically when a music plays after restart

### Actual behavior

Instead, the player doesn't apply the equalizer setting until I open the system equalizer via the app

### Screenshots/Screen recordings

https://drive.google.com/file/d/1EmZMu6y19wQN50mXBNJSE4h38nk05Kne/view?usp=drivesdk

### RiMusic version

0.6.27

### Android version

Android 13

**Comment by cMattw** [comment]
It also reapplies the equalizer setting when you pause and unpause the player after the app restart

**Comment by fast4x** [comment]
I'm sorry but it work, i have tested it in many cases and it work.

**Comment by cMattw** [comment]
> I'm sorry but it work, i have tested it in many cases and it work.

I see. I have also just tried it on my other device and it works fine. It seems to be a problem within my system
