### ISSUE TITLE
Change the playback speed no. from the play/pause button 

### ISSUE THREAD

**Issue by nelsonsiby2345** [fast4x/RiMusic#1179]
### Description

It's kinda miss matching the playback speed no. position 

### Suggested Solution

Maybe add the playback speed no. under the progress bar

**Comment by VINULA2007** [comment]
@fast4x 
![Screenshot_2024-03-23-11-57-12-149_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/89296867/2ca89f56-0341-4f75-8ee1-5439e71427d5)
Putting it there would look better in my opinion
 I thought it was a bug when I saw the current position lol

**Comment by fast4x** [comment]
Try please custom version, download from website https://rimusic.xyz/download

**Comment by nelsonsiby2345** [comment]
Thanks now it is ok

**Comment by fast4x** [comment]
Nice, thanks

**Comment by VINULA2007** [comment]
![Screenshot_2024-03-23-16-39-15-324_org mozilla firefox](https://github.com/fast4x/RiMusic/assets/89296867/1eb16a2e-3dd6-45eb-ab19-4d71af8b145c)
Why can't I go to the website?

**Comment by fast4x** [comment]
website is in Italy, maybe inaccessible from your location?

Take file ![app-release.zip](https://github.com/fast4x/RiMusic/files/14731339/app-release.zip)

**Comment by VINULA2007** [comment]
Thanks

**Comment by fast4x** [comment]
Yes, i think of adding custom version on GitHub project pagw.

Thanks

**Comment by fast4x** [comment]
Hi, can you try to load https://fast4x.github.io/RiMusic/ if open normally now?

**Comment by VINULA2007** [comment]
> Hi, can you try to load https://fast4x.github.io/RiMusic/ if open normally now?

It opens fine

**Comment by fast4x** [comment]
Ok i continue to move website or create a new one, thanks for feedback

**Comment by fast4x** [comment]
Website completed.

**Comment by VINULA2007** [comment]
> Website completed.

Looks like that website is heavy 
It takes a while to load and website acts sluggish when I scroll through it
 It could be because I use Firefox or the processer is too sluggish

**Comment by fast4x** [comment]
Site has few kb maybe the animation background can result slowly when load. I can try to investigate.

**Comment by VINULA2007** [comment]
> Site has few kb maybe the animation background can result slowly when load. I can try to investigate.

It loads instantly now 🎊
