### ISSUE TITLE
Downloaded songs folder not showing in library 

### ISSUE THREAD

**Issue by Nikks84** [fast4x/RiMusic#1180]
### Description

https://github.com/fast4x/RiMusic/assets/160481076/844872ec-ac9b-42a8-bc7c-eabab4e3430e

The downloaded song folder not showing in my case i don't know why I turned on all the options, still it is not visible, I checked in other device also, it is working properly.

### Suggested Solution

If anyone has any information about this, then tell me if I can get some help.

**Comment by NikunjKhangwal** [comment]
Can confirm. Not showing up in mine as well

**Comment by fast4x** [comment]
What version you use?

**Comment by Nikks84** [comment]
> What version you use? Try to close and reopen after activate options in settings.

Android version 10
Rimusic custom lestet version
I have yried but nothing happen same as previous

**Comment by fast4x** [comment]
I'll check it, in your are also missing cached ..  strange much strange

**Comment by Nikks84** [comment]
> I'll check it, in your are also missing cached .. strange much strange

Yes 😊

**Comment by fast4x** [comment]
I also realized that I have to move the settings of these folders to ui settings

**Comment by Nikks84** [comment]
It's good to put the request

**Comment by fast4x** [comment]
Have you disabled cache max size in settings?

**Comment by fast4x** [comment]
Maybe i've understand

**Comment by fast4x** [comment]
Fixed, available from version 0.6.28

**Comment by Nikks84** [comment]
> Have you disabled cache max size in settings?

Yes i have disabled but now enabled both showing
My bad I didn't know disabling it wouldn't show these folders  now working properly.
Thanx 👍🏻

**Comment by fast4x** [comment]
Good, in the next version you can disable cache and playlist show normally, I've fixed this.
