### ISSUE TITLE
pitch black mode has gone rouge 

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#1181]
### Steps to reproduce the bug

Turn on pitch black after turning on the dynamic theme

### Expected behavior

Background should be pitch black

### Actual behavior

It's doing exactly the opposite lol
The background becomes completely white

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/89296867/40e9b37d-1706-48ca-a6c3-9972ddb3f239

### RiMusic version

0.6.27

### Android version

Android 14

**Comment by fast4x** [comment]
Fixed, available from version 0.6.28
