### ISSUE TITLE
[Feature]: Some changes

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#1182]
### Description

1. This new feature called Background progress bar looks dope and good too but in miniplayer as it looks not so good in full player screen and also if I have turned off it than there is no progress bar.
![Screenshot_20240323-114208_RiMusic](https://github.com/fast4x/RiMusic/assets/120176369/23bb277c-6c42-461c-a1f5-0b39fee5650e)

2. Search bar is improved very much but it is not universal. So can u look into the solution. One suggestion is by me..
![Picsart_24-03-23_11-50-46-372](https://github.com/fast4x/RiMusic/assets/120176369/1d81c1de-bb8e-4080-b69d-3d074a037198)
The orange mark is the empty space and it can be filled by moving song list upward.

3. It is optional. This is my take on search bar
![Picsart_24-03-23_12-06-47-465](https://github.com/fast4x/RiMusic/assets/120176369/4c5a6738-bb43-4cfb-b053-4f3917e57dc4)

4. The integration of speed and temp need some work as 
![Screenshot_20240323-120706_RiMusic](https://github.com/fast4x/RiMusic/assets/120176369/f83f9b8b-0776-47e6-b183-c21b1b273f27)
Numbers are black in color and also range of speed and tempo is ver short because 1.1x feels like 1.5x
Please a input value option for speed and tempo in the future updates

### Suggested Solution

Ok bro

### Alternatives

..

### Additional Context

....

**Comment by NikunjKhangwal** [comment]
The background progress bar is already changed and you can select where you want to keep it from settings.
It'll be available on next release but until then download from official site:- http://rimusic.xyz/download/

**Comment by Logan7899** [comment]
![306359076-8bab10a5-c8df-4f3b-a141-195b1cac785a](https://github.com/fast4x/RiMusic/assets/120176369/e6f980f2-622a-40b6-87c1-96486336b52d)
@fast4x  this toolbar is inspired from yt music
If u can make it a bit wider and translucent and little bit move it down from its original position
I am sure that it will look dope in gradient background also

**Comment by Logan7899** [comment]
> ![306359076-8bab10a5-c8df-4f3b-a141-195b1cac785a](https://private-user-images.githubusercontent.com/120176369/316265405-e6f980f2-622a-40b6-87c1-96486336b52d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMjM5MTcsIm5iZiI6MTcxMTIyMzYxNywicGF0aCI6Ii8xMjAxNzYzNjkvMzE2MjY1NDA1LWU2Zjk4MGYyLTYyMmEtNDBiNi04N2MxLTk2NDg2MzM2YjUyZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QxOTUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjM4NDI0MTdkOWM4ZmIwNjM5YzUzOTg5NTQ2ZjZhOGQ1NjIyYzc1N2VlYTUzMDljNDhiZTU0YmQ2MGIzYjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RXlvJ-PpFx6ad3DxCyHnwba4S-9J8SJcx4V0vuy1M9c) @fast4x this toolbar is inspired from yt music If u can make it a bit wider and translucent and little bit move it down from its original position I am sure that it will look dope in gradient background also

Gradient theme ideas(Without White bar)
![Picsart_24-03-24_01-21-43-204](https://github.com/fast4x/RiMusic/assets/120176369/f4f8f8e0-3bc1-4db3-9082-fae26964ff5c)

With customized white bar
![Picsart_24-03-24_01-23-16-062](https://github.com/fast4x/RiMusic/assets/120176369/9b6606e0-a051-4efb-bed4-4cb5a1232abd)

**Comment by Logan7899** [comment]
Please comapare it

**Comment by fast4x** [comment]
This ticket for me is intended as done.
