### ISSUE TITLE
[Feature]: Grid style icons in Menu

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1184]
### Description

An option to change menu from list to grid. It'll be smaller and easier to use with one hand

### Suggested Solution

Something like this, the image is from Innertune

![IMG_20240323_114342](https://github.com/fast4x/RiMusic/assets/99175083/a6a8ef80-52c0-4b7a-8163-d282d297e55f)

**Comment by sayyid5416** [comment]
+1 _(making it optional seems like a good idea)_

**Comment by fast4x** [comment]
Implemented grid menu style grid and list, default is list.
Available from version 0.6.29

**Comment by NikunjKhangwal** [comment]
Lessgo!!! That was earlier than expected

**Comment by NikunjKhangwal** [comment]
Just tried it and it's awesome. Literally looks the same as Innertune. Amazing job 👌🏼

**Comment by sayyid5416** [comment]
yeah, I like it too.
