### ISSUE TITLE
[Feature]: way to load new suggestions to quick picks

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#1187]
### Description

Quick picks menu shows the same suggestions for a while which makes it obsolete for me atlest

### Suggested Solution

Add something like pull down to reload for it to refresh and make new suggestions

**Comment by dAtA-TRoN** [comment]
I personally don't like the Quick Pick thing at all. The suggestions are 99.99% irrelevant to me. Honest question: Does anyone here actually use it?

**Comment by Lllum** [comment]
> I personally don't like the Quick Pick thing at all. The suggestions are 99.99% irrelevant to me. Honest question: Does anyone here actually use it?

I do, I actually find it really useful and I've discovered lots of good songs out of it.

**Comment by VINULA2007** [comment]
> > I personally don't like the Quick Pick thing at all. The suggestions are 99.99% irrelevant to me. Honest question: Does anyone here actually use it?
> 
> I do, I actually find it really useful and I've discovered lots of good songs out of it.

I didn't find any good song from it 😅
I used innertune before and it's quick pick section was a bit more helpful at finding new songs

**Comment by VINULA2007** [comment]
> > I personally don't like the Quick Pick thing at all. The suggestions are 99.99% irrelevant to me. Honest question: Does anyone here actually use it?
> 
> I do, I actually find it really useful and I've discovered lots of good songs out of it.

I didn't find it much useful but
Innertune which is the player that I'm migrating from had a similar quick picks section and I found many good songs from it

**Comment by fast4x** [comment]
Implemented, new tips from Casual listened songs, available from version 0.6.30

**Comment by dAtA-TRoN** [comment]
> Implemented, new tips from Casual listened songs, available from version 0.6.30

You're on fire this week, aren't you!?
🔥👨🏻‍💼🔥

**Comment by fast4x** [comment]
Yes, like a poet when he begins to write.
