### ISSUE TITLE
[Feature]: Seperate icons for downloaded and cached songs.

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1189]
### Description

The songs here aren't exactly downloaded, they are just temporarily cached and will be replaced when cache limit runs out. They doesn't appear in downloaded window.
![Picsart_24-03-23_14-30-51-992](https://github.com/fast4x/RiMusic/assets/99175083/1586785c-fa98-46ff-b9f3-664883305ec6)

These are the songs that are actually downloaded
![IMG_20240323_143126](https://github.com/fast4x/RiMusic/assets/99175083/a9dc5231-2120-40ab-a95d-45bd3628590a)

### Suggested Solution

I've made this concept icon for cached songs so the old icon doesn't make them look like they're actually downloaded.
![Picsart_24-03-23_14-20-01-348](https://github.com/fast4x/RiMusic/assets/99175083/a356134d-2079-40ef-9a19-c089c9bf41c4)
Same icon but in png format:
![Picsart_24-03-23_14-20-01-348](https://github.com/fast4x/RiMusic/assets/99175083/22ce6389-6862-4559-981e-2a8421a30d46)

**Comment by NikunjKhangwal** [comment]
@ikanakova need your thoughts on this

**Comment by dAtA-TRoN** [comment]
In my view, the concept behind the displayed icon isn't bad, but there's a significant risk of confusion with the download icon. They're overly similar. The checkmark within the circle of the download symbol can be easily mistaken for the pointers of this cache symbol, particularly since these icons are often displayed at a small size. I believe they should be made slightly more distinct.

**Comment by NikunjKhangwal** [comment]
Genius, a hourglass icon didn't crossed my mind. I like your idea better. Let see what ikanakova have to say.

**Comment by dAtA-TRoN** [comment]
> Genius, a hourglass icon didn't crossed my mind. I like your idea better. Let see what ikanakova have to say.

While I don't profess to always have superior knowledge, I believe I articulated well the reasons behind my critique of your suggestion. Nonetheless, I must commend the quality of your icon; I genuinely thought it was pretty cool.
Yeah let's see what ikanakova has to say about it.

**Comment by ikanakova** [comment]
Rather, fast4x needs to say if it wants to distinguish between downloaded and cached tracks. Personally, I prefer it to be the same. For me, it's the same if it caches and downloads itself - I can play both offline. But if he wants (and still wants my icons), of course I will create an icon (with a hourglass).

**Comment by dAtA-TRoN** [comment]
I also don't necessarily need this distinction, but I understand why some folks might want it. Cache files are temporary, unlike downloaded ones, and some people like having control over their stuff. Even though I don't need it, if it does come around, I'd still want it done right.

**Comment by ikanakova** [comment]
As I wrote in the issue #925, I think it should be distinguished by playlists, but otherwise downloaded and cached songs should be the same.

**Comment by NikunjKhangwal** [comment]
I see them as "temporarily offline" vs "offline as long as i want." Downloaded songs are the ones that found their place in my library & I'm pretty much always going to listen. Cached songs are basically me trying new songs, songs I'm temporarily listening to, recommended songs etc

**Comment by fast4x** [comment]
In RiMusic the player cache is not temporary, because it can be emptied only from the RiMusic settings and not from the system cleaner. We can say that downloaded or cached is always downloaded. The difference lies in being downloaded by the player and not by the user.

That said then further differentiate the download type is a weighting that is useful for other apps not for RiMusic.

That said the hourglass icon can be useful as a replacement for the circular loader that is shown while the download is in progress

**Comment by dAtA-TRoN** [comment]
> In RiMusic the player cache is not temporary, because it can be emptied only from the RiMusic settings and not from the system cleaner. We can say that downloaded or cached is always downloaded. The difference lies in being downloaded by the player and not by the user.
> 
> That said then further differentiate the download type is a weighting that is useful for other apps not for RiMusic.
> 
> That said the hourglass icon can be useful as a replacement for the circular loader that is shown while the download is in progress
> 
> 

Thank you for the brief explanation. But I still have one burning question. What happens when you clear the cache? Does that also delete the downloads, or is there a difference?

**Comment by fast4x** [comment]
> > In RiMusic the player cache is not temporary, because it can be emptied only from the RiMusic settings and not from the system cleaner. We can say that downloaded or cached is always downloaded. The difference lies in being downloaded by the player and not by the user.
> > 
> > That said then further differentiate the download type is a weighting that is useful for other apps not for RiMusic.
> > 
> > That said the hourglass icon can be useful as a replacement for the circular loader that is shown while the download is in progress
> > 
> > 
> 
> Thank you for the brief explanation. But I still have one burning question. What happens when you clear the cache? Does that also delete the downloads, or is there a difference?

Simple, there are two separate buttons for clean cache type independently. 

Is nice this...

**Comment by dAtA-TRoN** [comment]
> Simple, there are two separate buttons for clean cache type independently.

Ooooh I see... No further questions, Your Honor 🙂‍↕️.

**Comment by fast4x** [comment]
> > Simple, there are two separate buttons for clean cache type independently.
> 
> Ooooh I see... No further questions, Your Honor 😁.

![giphy.gif](https://github.com/fast4x/RiMusic/assets/1484476/bd1c92c7-5ee8-4b3a-8573-b4cd21e61fe5)

**Comment by dAtA-TRoN** [comment]
lmao 🤣🤣🤣

**Comment by NikunjKhangwal** [comment]
> In RiMusic the player cache is not temporary, because it can be emptied only from the RiMusic settings and not from the system cleaner. We can say that downloaded or cached is always downloaded. The difference lies in being downloaded by the player and not by the user.
> 
> That said then further differentiate the download type is a weighting that is useful for other apps not for RiMusic.
> 
> That said the hourglass icon can be useful as a replacement for the circular loader that is shown while the download is in progress

Actually when i clear RiMusic cache from my device (not within app) the player cache songs get removed but downloaded songs remain. I also use cleaner apps like Sd Maid SE which are capable of doing it. This is what i meant to say, they differentiate by this aspect.

**Comment by NikunjKhangwal** [comment]
Just noticed clearing app cache also clears the cover art of downloaded songs. Not the song itself, songs still play fine. That means cover art of downloaded songs are temporary as well?

![IMG_20240324_104155](https://github.com/fast4x/RiMusic/assets/99175083/eb116f54-be92-4f47-a992-51f7ea5542de)

**Comment by fast4x** [comment]
Yes, image are cached in another cache and cleaner can delete.

**Comment by dAtA-TRoN** [comment]
> Yes, image are cached in another cache and cleaner can delete. 

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/45a9e912-76a4-48d0-9faf-daa0311947bb)

**Comment by fast4x** [comment]
Because images are classified as possible dirt if they are not photos.
![giphy (1).gif](https://github.com/fast4x/RiMusic/assets/1484476/10a031de-cb9e-4059-a77d-740022a5c42c)

**Comment by NikunjKhangwal** [comment]
Is this app behaviour or android behaviour?

**Comment by fast4x** [comment]
Android system cleaner.

**Comment by NikunjKhangwal** [comment]
Oh! So that means it can't be changed. Makes sense

**Comment by dAtA-TRoN** [comment]
> Because images are classified as possible dirt if they are not photos.

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/411b5566-ab91-4302-a87e-b3651018d1c1)

**Comment by ikanakova** [comment]
I think the system shouldn't delete cached songs or downloaded songs = they should behave the same in the background, the only difference would be what playlist they would be included in. For images, I don't care.

**Comment by ikanakova** [comment]
icon with hourglass added as download-progress in #1218

**Comment by fast4x** [comment]
Implemented, available from version 0.6.28
