### ISSUE TITLE
[Feature]: Pinch to zoom lyrics text size

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1191]
### Description

Ability to pinch for zooming in and out lyrics size as per user preference

### Suggested Solution

Something like this:

https://github.com/fast4x/RiMusic/assets/99175083/ddc8b1e7-6551-42dd-89a0-9bffe06a2538

### Additional Context

The last used size should be default for other songs as well

**Comment by fast4x** [comment]
Implemented, added font size menu in lyrics.
Available from version 0.6.28
