### ISSUE TITLE
can't play or download age restricted tracks 

### ISSUE THREAD

**Issue by notHaider** [fast4x/RiMusic#1192]
### Steps to reproduce the bug

1. go to any song which on YT music is age restricted (for example FUCKING YOUNG/PERFECT)
2. play the track

### Expected behavior

it's supposed to play the song 

### Actual behavior

it doesn't play the song and the progress bar just stays at the start

### Screenshots/Screen recordings

![Screenshot_20240323-111448_RiMusic](https://github.com/fast4x/RiMusic/assets/81862535/e2f36bb6-6bc2-4a3d-9a90-a72c9b5f9d57)

### RiMusic version

0.6.27

### Android version

Android 14

### Additional information

you can't download the song either

**Comment by dAtA-TRoN** [comment]
I don't think this is a bug. It could be that the API doesn't support it, Fast4X simply hasn't implemented it yet, or he's unaware of how to (which I find hard to believe). However, there have been frequent inquiries or problem reports regarding this. There seems to be some obstacle that may or may not be circumvented.

**Comment by DarkCrypt** [comment]
> It could be that the API doesn't support it

The API in use is the reason. Other apps play age restricted songs without issue.

**Comment by ikanakova** [comment]
>> It could be that the API doesn't support it
> 
> The API in use is the reason. Other apps play age restricted songs without issue.

As I wrote in issue #974 age-restricted videos are somehow handled by NewPipe, but I don't think this should be a priority because I think only a minority of music is age-restricted. So if it was complicated to implement, then age-restricted songs might not be supported by RiMusic.

**Comment by dAtA-TRoN** [comment]
> only a minority of music

Hip Hop isn't a minority.

**Comment by ikanakova** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/8102#issuecomment-1081085801 Wouldn't this help?

**Comment by DarkCrypt** [comment]
There's plenty of age restricted songs in different genres. Rap, Hip Hop, Rock, etc.

NewPipe Extractor, Piped API, and Invidious API are options that will play anything a user wants. Not real sure of other options at this time. I'm also not sure how complicated any of these are to implement.

I agree this doesn't necessarily need to be a priority. Like I said, there's plenty of other apps that users can use to play these songs. The fact is, if a user can't play the songs they want they'll disregard RiMusic and go elsewhere. They'll also continue to raise this issue constantly.

I'm not sure if the above link will help, hopefully? That thread is quite old.

**Comment by dAtA-TRoN** [comment]
> And are all hip hop songs on YouTube age-restricted?

No, but swear words are mainly prevalent in hip hop. Even the content you hear is often sanitized to appeal to a broader audience as a 'clean' version. It's not uncommon even in pop music nowadays for certain elements to be censored.

![proxy-image.gif](https://github.com/fast4x/RiMusic/assets/71184627/2ce592b8-fde3-41ec-9ea0-d0800412b632)
