### ISSUE TITLE
Error en la barra de progreso y  botón de velocidad 

### ISSUE THREAD

**Issue by julianM2000** [fast4x/RiMusic#1196]
### Steps to reproduce the bug

Error en la nueva versión, barra de reproducción 

### Expected behavior

Puedes dejarlo como estaba antes , se veía mejor así , con la barra como la de Youtube, 

### Actual behavior

cuando activo la nueva barra de progreso de canción 

### Screenshots/Screen recordings

![Screenshot_20240323-100521](https://github.com/fast4x/RiMusic/assets/68936429/c126941b-b3a8-4da0-95c8-50fde027ba64)

### RiMusic version

0.6.27

### Android version

Android 13

### Additional information

estaba mejor en la versión 26, aunque se que se puede desactivar la barra de progreso en ajustes pero el botón de velocidad de la música es tedioso tenerlo en el botón de play

**Comment by fast4x** [comment]
Progress length is not the same as timeline. For speed indicator tey custom version please, download from https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by julianM2000** [comment]
> La duración del progreso no es lo mismo que el cronograma. Para obtener la versión personalizada del indicador de velocidad, descárguelo desde https://github.com/fast4x/RiMusic/tree/master/customVersion

Muchas Gracias 🫂, pero siendo sincero estaba mejor como lo tenías en la versión anterior, no hay necesidad de poner el x1 , igual si lo agregas no hay problema, estás haciendo un gran trabajo amigo , sigue así eres grande 🫂

**Comment by fast4x** [comment]
Thanks, but now show only when speed is set greater or less 1
