### ISSUE TITLE
error in customization  

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1198]
hi @fast4x, i want to add firebase to the app for experimenting my self. im learning android development. but i had an error in that process. please say how to solve error. please.

[error.txt](https://github.com/fast4x/RiMusic/files/14733691/error.txt)
[build.gradle.txt](https://github.com/fast4x/RiMusic/files/14733692/build.gradle.txt)

**Comment by fast4x** [comment]
Ok but use of firebase isn't planned...

**Comment by fast4x** [comment]
Is an error in configuration of namespace

**Comment by SureshTimma** [comment]
> Ok but use of firebase isn't planned...

I'm not asking you to implement in App. But I'm experimenting. While I got error. You only solve it. Please

**Comment by SureshTimma** [comment]
> Is an error in configuration of namespace

How to solve it? In with file?

**Comment by fast4x** [comment]
Requires time to spend, I'm sorry, you can learn about it in forums, YouTube and other web resources. I'm sorry.

**Comment by SureshTimma** [comment]
> Requires time to spend, I'm sorry, you can learn about it in forums, YouTube and other web resources. I'm sorry.

Ok
