### ISSUE TITLE
Wrong cover art in notification and lock screen

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1199]
### Steps to reproduce the bug

Play any song in RiMusic and then switch to another song

### Expected behavior

The cover art should be the same as the main player

### Actual behavior

This is the original cover art
![IMG_20240324_103031](https://github.com/fast4x/RiMusic/assets/99175083/afcc259a-be51-41ae-b902-2bca33a963c5)

This is in notification
![IMG_20240324_103015](https://github.com/fast4x/RiMusic/assets/99175083/abdc753a-a2e4-4eed-9bd5-78f5e1cf0439)

This is on lock screen
![IMG_20240324_103049](https://github.com/fast4x/RiMusic/assets/99175083/7f735a25-e0e6-43bb-9a0d-ca1cc7f5359b)

The app takes cover art from any closest song and then show it for the current playing song.

### RiMusic version

0.6.27

### Android version

Android 12

### Additional information

This could be happening because of MIUI as well since miui use it's own notification style for music. But you have Xiaomi phone as well, can you take a look at it?

**Comment by fast4x** [comment]
Yes, I'll try with my Xiaomi.

**Comment by fast4x** [comment]
Tryed with two devices and it's ok...
![Screenshot_20240324_121923](https://github.com/fast4x/RiMusic/assets/1484476/8c52fa75-763a-4498-a5d7-536dbeaae0e7)

**Comment by NikunjKhangwal** [comment]
Not sure, happening in mine
