### ISSUE TITLE
Audio file not playing from "on device"

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#120]
### Steps to reproduce the bug

play audio from device

### Expected behavior

it should play the song

### Actual behavior

it shows error

### Screenshots/Screen recordings

![image](https://github.com/fast4x/RiMusic/assets/127825700/8b1b5568-b023-430b-8298-eca72fffa941)
![image](https://github.com/fast4x/RiMusic/assets/127825700/4250e594-4e5d-4380-a84c-ce6054239b82)

### RiMusic version

latest version

### Android version

android 11

**Comment by siggi1984** [comment]
I have the same problem.

Android 12

**Comment by smicrom22** [comment]
Idem Android 13

**Comment by smicrom22** [comment]
Et merci pour votre travail et pour cette application

**Comment by NEVARLeVrai** [comment]
> Et merci pour votre travail et pour cette application 

J'ai traduit l'application en français vu que tes français tu pourras me donner ton avis sur la prochaine maj

**Comment by fast4x** [comment]
Fixed, available from version 0.6.13

**Comment by MXC48** [comment]
> Fixed, available from version 0.6.13

unfortunately it still doesn't work for me in the latest version![Screenshot_20231212-194249_RiMusic.png](https://github.com/fast4x/RiMusic/assets/123580315/8b190f93-9a43-401e-ad7c-f823d6976214)

**Comment by MXC48** [comment]
> > Et merci pour votre travail et pour cette application 
> 
> J'ai traduit l'application en français vu que tes français tu pourras me donner ton avis sur la prochaine maj

Au niveau de la traduction ?

**Comment by fast4x** [comment]
> > > Et merci pour votre travail et pour cette application 
> > 
> > J'ai traduit l'application en français vu que tes français tu pourras me donner ton avis sur la prochaine maj
> 
> Au niveau de la traduction ?

Look, will be available on version 0.6.13..

**Comment by fast4x** [comment]
> > Fixed, available from version 0.6.13
> 
> unfortunately it still doesn't work for me in the latest version![Screenshot_20231212-194249_RiMusic.png](https://github.com/fast4x/RiMusic/assets/123580315/8b190f93-9a43-401e-ad7c-f823d6976214)
> 
> 

Look, will be available on version 0.6.13..

**Comment by MXC48** [comment]
> > > Fixed, available from version 0.6.13
> > 
> > unfortunately it still doesn't work for me in the latest version![Screenshot_20231212-194249_RiMusic.png](https://github.com/fast4x/RiMusic/assets/123580315/8b190f93-9a43-401e-ad7c-f823d6976214)
> > 
> > 
> 
> Look, will be available on version 0.6.13..

Sorry, I thought the current version was 0.6.13 😅

**Comment by fast4x** [comment]
Lol, next will be... 😋

**Comment by NEVARLeVrai** [comment]
> > > Et merci pour votre travail et pour cette application 
> > 
> > J'ai traduit l'application en français vu que tes français tu pourras me donner ton avis sur la prochaine maj
> 
> Au niveau de la traduction ?

Oui si y a pas de faute ou autre

**Comment by fast4x** [comment]
Fixed
