### ISSUE TITLE
[Feature]: Swipe down to close menu

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1201]
### Description

Make all the menu across app swipable so we can swipe them down to close them for easier one handed usage.

### Suggested Solution

These
![IMG_20240324_141228](https://github.com/fast4x/RiMusic/assets/99175083/d93a1301-3983-44a0-b6aa-6701c27f3e7f)

### Additional Context

Should be the same for grid style menu if they ever get implemented. As mentioned in #1184

**Comment by fast4x** [comment]
oh thanks
