### ISSUE TITLE
[Feature]: Automatically switch to synchronized/unsynchronized lyrics

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1202]
### Description

If a song doesn't have one kind of lyrics available but does have other one then automatically switch to it with a toast notification notifying user

### Suggested Solution

These ones
![IMG_20240324_141301](https://github.com/fast4x/RiMusic/assets/99175083/ee9b2285-c002-4a28-9899-24df6cce5cd0)
![IMG_20240324_141248](https://github.com/fast4x/RiMusic/assets/99175083/581281c9-f369-488a-86b7-bd0dffb4b8f6)

**Comment by jaki444** [comment]
#698  same identical request

**Comment by NikunjKhangwal** [comment]
Didn't saw it because of spelling. Thanks for pointing out

**Comment by fast4x** [comment]
Implemented click to switch lyrics type when not available.
Available from version 0.6.29
