### ISSUE TITLE
Audio Visualiser freezes

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#121]
### Steps to reproduce the bug

Use the Audio Visualiser

### Expected behavior

The Audio Visualiser sould keep playing

### Actual behavior

The Audio Visualiser freezes

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/104271365/835a8858-0db3-45cf-a649-22c9f756c352

### RiMusic version

0.6.9

### Android version

Android 13 with One UI 5.1

### Additional information

Also the background should be black like the lirics
And the Visualiser would be nice to change colors in Dynamic mode.
And to finish instead of using the microphone it would be bether to use the music cached db

**Comment by fast4x** [comment]
uhm I can see if possible with the current development version

Freeze are bug probably

**Comment by OrangeZXZ** [comment]
The bug is less present on android 14 with one UI 6

**Comment by NEVARLeVrai** [comment]
> The strange thing is that in the android emulator 13/14, the bug is not present.

I have also the issue on Android 12 MIUI 14

**Comment by OrangeZXZ** [comment]
> The strange thing is that in the android emulator 13/14, the bug is not present.

Maybe it's my phone that has a problem. Il try on other samsung devices that my family has.

**Comment by fast4x** [comment]
The bug is there, even on my phone, the strange thing is that I can’t play it in the android emulator.

**Comment by OrangeZXZ** [comment]
> The bug is there, even on my phone, the strange thing is that I can’t play it in the android emulator.

I think the phone security or something like that blocks because the app is from an "unknown persone" maybe in the emulator the security works differently

**Comment by fast4x** [comment]
Sure could be, I have to investigate, if you find any info let me know

**Comment by OrangeZXZ** [comment]
> Sure could be, I have to investigate, if you find any info let me know

Oh i think i found it my phone doesn't say that the mike is used
I don't know how it works but it needs mike privileges so i think this is the problem

![Uploading Screenshot_20231121_074619_Permission usage.jpg …]()

**Comment by NEVARLeVrai** [comment]
> > Sure could be, I have to investigate, if you find any info let me know
> 
> Oh i think i found it my phone doesn't say that the mike is used
> I don't know how it works but it needs mike privileges so i think this is the problem
> 
> ![Uploading Screenshot_20231121_074619_Permission usage.jpg …]()

Ur screenshot don't work

**Comment by NEVARLeVrai** [comment]
> > Sure could be, I have to investigate, if you find any info let me know
> 
> Oh i think i found it my phone doesn't say that the mike is used
> I don't know how it works but it needs mike privileges so i think this is the problem
> 
> ![Uploading Screenshot_20231121_074619_Permission usage.jpg …]()

Same but I don't see green microphones pop  up for the mic, like the mic it's not used

**Comment by fast4x** [comment]
uhm but the permissions are set as required. Check

**Comment by OrangeZXZ** [comment]
> uhm but the permissions are set as required. Check

I got an idea try using the share screen option in the update to see if it works but if it still freezing then there is an error elsewhere

**Comment by fast4x** [comment]
Today try ti get mic permission with another mode...
Thanks for suggestions

**Comment by fast4x** [comment]
Have you tryed add mic permission manually?

**Comment by OrangeZXZ** [comment]
> Have you tryed add mic permission manually?

yeah i did that

**Comment by fast4x** [comment]
> > Have you tryed add mic permission manually?
> 
> yeah i did that

And bug?

**Comment by NEVARLeVrai** [comment]
> > > Have you tryed add mic permission manually?
> > 
> > 
> > yeah i did that
> 
> And bug?

ys

**Comment by OrangeZXZ** [comment]
I played with my audio visualiser and i noticed that randomly he wasn't freezing but just after I taped the download button it started freezing:

- Could be because there are back processes that make it freez (downloading cache)

Also it dose it wen you skip songs:

- Maybe because it loads the images

Also it bugs less when songs take less space and wen listening to music videos:

- Maybe the cache that is loaded IRT (maybe loading directly the full song is a good option if this is not the case)

To finish it bugs less when listening to newer songs (not sure)

**Comment by OrangeZXZ** [comment]
Oh there is an extra space in there:
![image](https://github.com/fast4x/RiMusic/assets/104271365/fd310241-363b-445c-a4ac-271809ecc2f0)

**Comment by fast4x** [comment]
That’s very good news, thanks for your help!

**Comment by fast4x** [comment]
Fixed, available from version 0.6.11

**Comment by NEVARLeVrai** [comment]
> A this moment no other work is possible, in the future i'll try other solutions.

Still freezing after a while in 60hz or 144hz

**Comment by OrangeZXZ** [comment]
> Still freezing after a while in 60hz or 144hz

it is freezing less but that we dont have a choise for now

**Comment by fast4x** [comment]
In the future I would like to use a different solution in the hope that it will be more stable

**Comment by OrangeZXZ** [comment]
> In the future I would like to use a different solution in the hope that it will be more stable

I like the news choices that you've added (some are a bit too colored and misplaced but it is nice to have)
