### ISSUE TITLE
[Feature]: On device music

### ISSUE THREAD

**Issue by Lio-gif** [fast4x/RiMusic#1214]
### Description

Hi is IT posibel to edit the Tags of a music File so IT Shows the Artist Like normal and you can Go from the Song to the artist dident knew If IT is a Bug or feature

### Suggested Solution

Idk maybe Put the Tag as a Link or smth

**Comment by NikunjKhangwal** [comment]
It's not possible. Mainly because RiMusic is a online music streaming app first and local music isn't a priority so only some basic functionalities are added for local music.
