### ISSUE TITLE
Feature: please add a toggle for song time left

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1215]
### Description

@fast4x add a toggle for showing or hiding time left of a song.

And move position of speed to the current time left position.
![IMG_20240325_160300](https://github.com/fast4x/RiMusic/assets/148480722/bae47683-fef9-465f-8b64-0252f03f271e)

### Suggested Solution

Please...

**Comment by Vishcot** [comment]
@fast4x can you please toggle on and off for the above circle as well..
That it won't show if not toggled onn! 😬

**Comment by Vishcot** [comment]
> > @fast4x can you please toggle on and off for the above circle as well..
> > That it won't show if not toggled onn! 😬
> 
> Which Circle?

For which you've created an arrow for. 😂
