### ISSUE TITLE
[Feature]: Better playing screen when cover art isn't available

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1220]
### Description

Currently the entire area is empty when a song doesn't have cover art & it looks bad.

![IMG_20240325_215521](https://github.com/fast4x/RiMusic/assets/99175083/5b47f438-1668-49b6-8115-6c6752544805)

### Suggested Solution

Maybe add something like this, a square as defined by thumbnail size and roundness from settings with a medium sized app logo in middle

![IMG_20240325_215502](https://github.com/fast4x/RiMusic/assets/99175083/07f6e90d-b41c-4af5-867b-1d3761ae272d)

**Comment by ikanakova** [comment]
Perhaps instead of a logo, it would be better to show the artist and (if there is one) the album title.

**Comment by dAtA-TRoN** [comment]
Great addition 👏🏼.

**Comment by fast4x** [comment]
Amazing

**Comment by fast4x** [comment]
Implemented, available from version 0.6.28

**Comment by dAtA-TRoN** [comment]
> Implemented, available from version 0.6.28

![VAPORGRAM_IMG_1711480009661.png](https://github.com/fast4x/RiMusic/assets/71184627/f619365d-c42a-4d9a-b0e4-8d93ee619f3d)

**Comment by fast4x** [comment]
> > Implemented, available from version 0.6.28
> 
> ![VAPORGRAM_IMG_1711480009661.png](https://github.com/fast4x/RiMusic/assets/71184627/f619365d-c42a-4d9a-b0e4-8d93ee619f3d)

He’s more beautiful than me 🤣
