### ISSUE TITLE
Few inconsistencies of "Select" feature

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1223]
### Description

I think selection feature is overall "not so user friendly". So I have a few suggestions.

### Suggested Solution

- [ ] Tapping on back button should only end selection process. Not going to previous page. 
- [x] On the menu "Select" and "Uncheck" should be combined into one. Like "Select/Uncheck". Maybe this one would be hard to do as I remember there was a discussion about it before.
- [x] The name uncheck doesn't match. It should be deselect. 
- [x] When "Selection" is on there's slight padding between songs and that's most likely because of the "checkbox". I don't understand why is it like that but it doesn't look good to me.

**Comment by fast4x** [comment]
It solve with change translation

**Comment by fast4x** [comment]
> When "Selection" is on there's slight padding between songs and that's most likely because of the "checkbox". I don't understand why is it like that but it doesn't look good to me.

I can't improve it

Back button for now isn't implementable, i'm sorry.

Other done and available in version 0.6.28

**Comment by fast4x** [comment]
Thanks you
