### ISSUE TITLE
[Feature]: Show local music

### ISSUE THREAD

**Issue by Car0lina5** [fast4x/RiMusic#1227]
### Description

I would like to suggest that local songs also appear in the album section. If the application already does this, I would like help knowing how to do it.

### Suggested Solution

There could be an option to choose whether to show local albums or not.

**Comment by fast4x** [comment]
Local songs are in Library inside On device playlist 
![Screenshot_2024-03-26-00-51-41-768_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/40458831-0a6b-4b83-9b32-ee05496f5632)

**Comment by Car0lina5** [comment]
Thank you, I found them in this session. But I would like to know if it is possible to see my local albums in that part of the albums. I also noticed that even when downloading a song through the app, it wasn't in the albums part and it looks like it was a local song. Am I doing something wrong? I've seen all the options and haven't been able to resolve this.

**Comment by fast4x** [comment]
Not for now, RiMusic is an online player, the part of the songs and albums on the device has basic functions. When you download a song, you always find it in the same dive point you downloaded it and also in the Library inside the playlist
