### ISSUE TITLE
Cant Select Song in queue using select option

### ISSUE THREAD

**Issue by RABINGG** [fast4x/RiMusic#1230]
### Steps to reproduce the bug

1. Create a song queue
2. Open the tgree dot menu and click on select
3. Now select a song in the queue

### Expected behavior

The song should be checked in the checkbox

### Actual behavior

The song plays instead of selected. Only selects while perfectly clicking on the checkbox. This should be changed to select the song while select mode is enable instead of playing the song. 

### RiMusic version

0.6.27

### Android version

14

**Comment by fast4x** [comment]
Improved, available from version 0.6.28
