### ISSUE TITLE
[ feature ] Crossfade.

### ISSUE THREAD

**Issue by aRandomMenno** [fast4x/RiMusic#1233]
### Description

I don't really know how to explain it, but it is a pretty nice feature it is i I think the opposite of the pause between songs setting. I makes the end of the song fade out with the beginning of the next song.

### Suggested Solution

Idk. I think you should search it. Im not a developer for mobile apps.

**Comment by dAtA-TRoN** [comment]
Duplicate #980

**Comment by aRandomMenno** [comment]
Oh, I didn't notice that is issue, mb.

**Comment by dAtA-TRoN** [comment]
> Oh, I didn't notice that is issue, mb.

How could you? The original post is pretty poorly named.
