### ISSUE TITLE
Something wrong on notification bar like button

### ISSUE THREAD

**Issue by Nikks84** [fast4x/RiMusic#1234]
### Description

https://github.com/fast4x/RiMusic/assets/160481076/e800bff2-2945-493a-bf60-1b345bbd55db

I think there is no need to tell anything, you will understand by watching the video This issue is not new but it is not getting fixed  in previous release.

### Suggested Solution

See 👆🏻

**Comment by dAtA-TRoN** [comment]
Duplicate #1145

**Comment by fast4x** [comment]
Fixed, available from version 0.6.28

**Comment by dAtA-TRoN** [comment]
> Fixed, available from version 0.6.28

![giphy.gif](https://github.com/fast4x/RiMusic/assets/71184627/c4c0bff4-ead2-48ac-93ef-277416cc0796)

**Comment by Nikks84** [comment]
Notification like button fixed and work fine but now main player like button not working i have tried many time but nothing happen.

https://github.com/fast4x/RiMusic/assets/160481076/8cf72614-9e2a-4ad8-91dc-05329c25a181

**Comment by fast4x** [comment]
Massive intervention is needed for that, soon.
