### ISSUE TITLE
Bug di ri music latest version

### ISSUE THREAD

**Issue by ghyvpine** [fast4x/RiMusic#1238]
### Steps to reproduce the bug

1. I want to delete one of my songs
2. But I can't delete it
3. I used the slide action on the song title, then hit delete, but it still doesn't work

### Expected behavior

Repaired immediately

### Actual behavior

Hmm 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/143674859/b3210136-b5be-40ca-a728-ff98185e5cb7

### Logs

I dont have

### RiMusic version

Latest

### Android version

14

### Additional information

Hyper os earth

**Comment by fast4x** [comment]
I'll check immediately 😅

**Comment by fast4x** [comment]
Deactivated delete action in downloaded playlist, it can use classic download action in this playlist, beacuse it deleting nothing.
Available from version 0.6.28
