### ISSUE TITLE
Icon Mismatch Found

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1240]
### Description

![Screenshot_2024-03-27-11-42-01-298_it fast4x rimusic~2](https://github.com/fast4x/RiMusic/assets/148480722/1428e60c-44af-4424-a339-f9fa8aafa4e2)

### Suggested Solution

Please change change RIMusic icon to quick Pics icon there!

**Comment by fast4x** [comment]
Improved, available from version 0.6.28
