### ISSUE TITLE
Integrate YouTube & Google Podcast in App

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1245]
### Description

If possible please add YouTube and Google podcasts in the app please.

### Suggested Solution

.

**Comment by dAtA-TRoN** [comment]
Google Podcasts will soon be discontinued and integrated into YouTube Music. And YouTube itself is already integrated. When you mention explicitly being able to play videos in the RiMusic app, that, for my taste, would be going too far. Video is a completely different realm from music.

**Comment by SureshTimma** [comment]
> Google Podcasts will soon be discontinued and integrated into YouTube Music. And YouTube itself is already integrated. When you mention explicitly being able to play videos in the RiMusic app, that, for my taste, would be going too far. Video is a completely different realm from music.

I want audio format of podcasts in YouTube! 

YouTube podcasts are now available on YouTube music! Why not RIMusic.

No YouTube not integrated in Rimusic. I couldn't find any other videos then music videos!!

**Comment by dAtA-TRoN** [comment]
> No YouTube not integrated in Rimusic. I couldn't find any other videos then music videos!!

But it's called "Ri-M-U-S-I-C", not "Ri-V-I-D-E-O"!

![proxy-image.gif](https://github.com/fast4x/RiMusic/assets/71184627/8ed3262a-9f69-4bc7-93b6-f13a203b4354)

**Comment by ikanakova** [comment]
> No YouTube not integrated in Rimusic. I couldn't find any other videos then music videos!!
If you want a video, download e.g. [Newpipe](https://github.com/TeamNewPipe/NewPipe/).

**Comment by SureshTimma** [comment]
> > No YouTube not integrated in Rimusic. I couldn't find any other videos then music videos!!
> 
> If you want a video, download e.g. [Newpipe](https://github.com/TeamNewPipe/NewPipe/).

I don't want video but YouTube video podcasts as audio in RIMusic app

**Comment by dAtA-TRoN** [comment]
> I don't want video but YouTube video podcasts as audio in RIMusic app

But podcast is also not music. That dilutes the essence of RiMusic. Moreover, podcast players operate quite differently from music players. So, there's a whole different set of complexities involved.

**Comment by SureshTimma** [comment]
> > I don't want video but YouTube video podcasts as audio in RIMusic app
> 
> But podcast is also not music. That dilutes the essence of RiMusic. Moreover, podcast players operate quite differently from music players. So, there's a whole different set of complexities involved.
> 

Ok, Tq.
