### ISSUE TITLE
Incorrect behavior of "Show Search Tab in Home" setting

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#1248]
### Steps to reproduce the bug

1. Go to User interface settings
2. Enable "Show Search Tab in Home"
3. Search tab disappeared
4. Return to UI settings 
5. Disable "Show Search Tab in Home"
6. Search tab appeared

![1](https://github.com/fast4x/RiMusic/assets/76595855/c49d0c39-ceaf-41a5-a4c8-e5343ceadd48)

![2](https://github.com/fast4x/RiMusic/assets/76595855/20e37595-5bcc-44e6-adff-b2723ef67acc)

![3](https://github.com/fast4x/RiMusic/assets/76595855/61db64b0-8ee7-4a98-a9f3-60e122ca8e3c)

![4](https://github.com/fast4x/RiMusic/assets/76595855/33ead5a8-2613-4497-897a-12fa47fd55d6)

### Expected behavior

Expected that when the setting is turned on, the search tab will appear on the home screen and disappear when it is turned off

### Actual behavior

Setting behavior opposite of what is expected

### RiMusic version

0.6.27

### Android version

Android 13

### Additional information

Samsung Galaxy A51

**Comment by dAtA-TRoN** [comment]
It's not a bug, it's a feature:

![IMG_20240327_131241.jpg](https://github.com/fast4x/RiMusic/assets/71184627/a34b74bc-0878-47a6-8eb1-e9e5e6f77d0b)

**Comment by KOLIWAN** [comment]
Got it, thanks 😅 Feeling a little bit dumb
