### ISSUE TITLE
Redesigning Album/EP Page Layout

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1249]
### Description

The current design of the Album/EP Page underutilizes space, resulting in less text visibility and a cramped appearance. This proposal suggests a redesign to optimize space usage and improve user experience. By eliminating two buttons (as removing one renders the other redundant), we can unlock unused space. The "alternative Version" button appears unnecessary and could be removed. If deemed necessary, its functionality could be integrated into the three-dot menu. Other suggestions are welcome.

![3695b1fd-d517-4ddd-8c95-7ffb3ee3c62c.png](https://github.com/fast4x/RiMusic/assets/71184627/edb0a577-5e2a-4e22-8887-5ba31fac98ed)

### Suggested Solution

**1. Remove buttons:** Eliminate two buttons to free up space and declutter the interface.

![63143940-b211-4b40-904e-080624a00180.png](https://github.com/fast4x/RiMusic/assets/71184627/32a0bc03-3445-4180-afb6-f5d4474f2dda)

**2. Optimize layout:** Redesign the Album/EP Page layout to utilize available space efficiently, ensuring better text visibility and a more spacious appearance.

_Annotation: If required, move the 'Alternative Version' button functionality into the three-dot menu to streamline the interface._

![79c8dbfb-d4e7-4cb7-a7ed-0eeaeee618c7.png](https://github.com/fast4x/RiMusic/assets/71184627/b73e01a8-95bb-4ad0-8399-38e3696fe762)

_Notice: The second mention of the album title below the album art should be removed as it is redundant._

### Additional Context

The current design of the Album/EP Page is not optimal, as it leaves unused space and appears cramped. This proposal aims to enhance user experience by improving space utilization and decluttering the interface.

**Comment by fast4x** [comment]
Album contain songs list and "other album versions" not removable... look this...
![Screenshot_20240327_165722](https://github.com/fast4x/RiMusic/assets/1484476/05a543c6-827f-4f42-9913-b421546b9072)

**Comment by ikanakova** [comment]
Other version I use a lot. Definitely don't remove that unless hide it in three dots.

**Comment by dAtA-TRoN** [comment]
I'm currently away from home. I'll take some time to think about it later. I believe we all recognize the necessity of this renovation. Perhaps you might have some thoughts on the matter.

**Comment by dAtA-TRoN** [comment]
> Other version I use a lot. Definitely don't remove that unless hide it in three dots.

And what exactly does this button do every time I use it? It doesn't show me any results whatsoever.

**Comment by ikanakova** [comment]
> > Other version I use a lot. Definitely don't remove that unless hide it in three dots.
> 
> And what exactly does this button do? Every time I use it, it doesn't show me any results whatsoever.

For example, if I want to listen to the Let it be album by The Beatles in the original version I have to go to album Let it be (Super Deluxe) and there it is the classic Let it be album. (But I have RiMusic version 0.6.24 because F-Droid hasn't offered me a newer one yet.)

**Comment by dAtA-TRoN** [comment]
> Album contain songs list and \"other album versions\" not removable... look this...

"The Songlist button becomes unnecessary if the 'Other Versions' button is no longer there. Just for the record. From my point of view, the latter button should somehow be moved, perhaps as I suggested, into the three-dot menu."

**Comment by fast4x** [comment]
> > Album contain songs list and \"other album versions\" not removable... look this...
> 
> The Songlist button becomes unnecessary if the 'Other Versions' button is no longer there. Just for the record. From my point of view, the latter button should somehow be moved, perhaps as I suggested, into the three-dot menu.

Is not visible in dots menu...

**Comment by sayyid5416** [comment]
I think this empty space thing will automatically be solved with bottom navigation bar as suggested in #852

**Comment by fast4x** [comment]
> > > Other version I use a lot. Definitely don't remove that unless hide it in three dots.
> > 
> > And what exactly does this button do? Every time I use it, it doesn't show me any results whatsoever.
> 
> For example, if I want to listen to the Let it be album by The Beatles in the original version I have to go to album Let it be (Super Deluxe) and there it is the classic Let it be album as other version. (But I have RiMusic version 0.6.24 because F-Droid hasn't offered me a newer one yet.)

It's failed build for 0.6.26.1
https://f-droid.org/packages/org.exarhteam.iitc_mobile/

**Comment by dAtA-TRoN** [comment]
> Is not visible in dots menu...

What do you mean?

**Comment by fast4x** [comment]
> > Is not visible in dots menu...
> 
> What do you mean?

this...

Other version I use a lot. Definitely don't remove that unless hide it in three dots.

**Comment by dAtA-TRoN** [comment]
> Other version I use a lot. Definitely don't remove that unless hide it in three dots.

Ah, I see now. It's not about ditching this feature. Seems I underestimated its popularity. My aim is just to tweak the layout to make the most of the available space. I reckon nobody's against that, really. As for the execution, well, that's a different story. I just threw out the idea of shifting the button to the three-dot menu. I think it could work pretty well. But hey, open to other suggestions, of course.

**Comment by dAtA-TRoN** [comment]
So, I've given some more thought to the topic. Check a look:

![05988444-4823-4d67-853f-3f2d42f2c576.png](https://github.com/fast4x/RiMusic/assets/71184627/f7410077-4863-473e-a562-4a9c6428fd7e)

Yes, you've seen it right: the 'Download Cover' button is relocating to the 'Three Dots Menu'. In my humble opinion, it's finding a better home there, as it was always too in-your-face before. Not only was the button aesthetically challenged, but it also stole attention from the cover art. Stepping into its shoes is the ever-popular 'Alternative Versions' button:

![05988444-4823-4d67-853f-3f2d42f2c576.png](https://github.com/fast4x/RiMusic/assets/71184627/9ed768d1-ef86-454d-bce9-17dd5b4f34d0)

 I can hear your thoughts now: isn't it just as visually distracting as the other button? And to that, I say: yes, indeed... BUT here's the kicker: this new and improved 'Alternative Versions' button will only appear when there are actually alternative versions available. This comes with several perks: most of the time, it'll stay out of sight, giving you an uninterrupted view of the album cover. The second big advantage is that you can always tell at a glance whether there are different versions at all. Personally, what irked me most about this button was that I tapped on it in 99.99% of cases for nothing, dismissing it as useless. So, what do you think?

**Comment by fast4x** [comment]
It’s a good compromise.

**Comment by dAtA-TRoN** [comment]
> It’s a good compromise.

![proxy-image.gif](https://github.com/fast4x/RiMusic/assets/71184627/5efbdfe5-44e7-40a7-b3f8-a65f7cf7ac75)

Thank you!

**Comment by dAtA-TRoN** [comment]
> I see the Download Cover icon is not from Ionicons, so I'll add it. And I'll create an Alternative Versions icon too because I couldn't find it in Ionicons.

Very good. I love your enthusiasm 👌🏼.

**Comment by ikanakova** [comment]
Download Cover:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/9d6714eb-27b8-4fa5-ab96-0a1c4e8135a3" width="25">

Alternative Version:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/e7f6e57e-21c4-4a01-9254-1d4286000e50" width="25">

**Comment by ikanakova** [comment]
If a new icon is needed, please mention me. I try to read every issue, but sometimes I don't notice.

**Comment by ikanakova** [comment]
> Did you also go for the note on the new 'album' icon? Just thinking about keeping things consistent. It would be neat if the 'Alternative Versions' stack resembled the single album in some way. Does that make sense?

I agree, if the single icon is the disc, the album icon is the disc on the cover, this should be consistent with that:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/fa5255cc-ded0-435d-88ec-a2cb4eda43f4" width="25">

**Comment by dAtA-TRoN** [comment]
Wow, looks just perfect. Love it 👏🏻!

**Comment by sayyid5416** [comment]
Yes, Add those `download cover` buttons inside 3 dot context menu.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.28

**Comment by dAtA-TRoN** [comment]
> Implemented, available from version 0.6.28

You are a crazy man, dude.

![39 - Meme.gif](https://github.com/fast4x/RiMusic/assets/71184627/4b43d35b-0261-49c6-b89c-2bf69bb30bff)

**Comment by fast4x** [comment]
![giphy](https://github.com/fast4x/RiMusic/assets/1484476/f10b3b74-78ab-43f6-9fe8-df670c06803b)
Can be, dude.

**Comment by SureshTimma** [comment]
> Implemented, available from version 0.6.28

When will be the update?

**Comment by dAtA-TRoN** [comment]
> > Implemented, available from version 0.6.28
> 
> When will be the update?

Normally in a few hours.

**Comment by SureshTimma** [comment]
> > > Implemented, available from version 0.6.28
> > 
> > When will be the update?
> 
> Normally in a few hours at most.

I'm from India, it's midnight here. So asked!

**Comment by dAtA-TRoN** [comment]
> I'm from India, it's getting midnight here. So asked! 

And I was happy to answer your question.

I'm from Germany. 5:49 pm and it's rainy outside.

**Comment by ikanakova** [comment]
I'm from the Czech Republic and we had a beautiful sunny spring day here 🙂 (And I don't care that no one may have asked me 🤣🤣🤣)

**Comment by fast4x** [comment]
> > > > Implemented, available from version 0.6.28
> > > 
> > > When will be the update?
> > 
> > Normally in a few hours at most.
> 
> I'm from India, it's getting midnight here. So asked! 

Telugu translation is partially... delete it?

**Comment by fast4x** [comment]
Hi all, I'm from Italy, Sicily, now are 18:34 afternoon and it's a sunny day. I'm preparing to go Gym... 😂😂😂

**Comment by fast4x** [comment]
Implemented top bar navigation, available from version 0.6.29
