### ISSUE TITLE
Instead of custom version, Open beta testing

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1251]
### Description

Instead of custom version after release of new version, open beta testing. After every new feature added or modification or each day release one beta apk.

### Suggested Solution

This idea will works best! And gives best user experience per every official update.

**Comment by ikanakova** [comment]
The daily version can be downloaded from Actions. But it would be great if there was a weekly beta version that wasn't on F-Droid (or not on the official one, but could be its own F-Droid repository) and once in a while a stable version that was on the official F-Droid. Because F-Droid can't keep up with the weekly releases anyway.

**Comment by SureshTimma** [comment]
![Screenshot_2024-03-27-22-48-00-005_com.github.android.jpg](https://github.com/fast4x/RiMusic/assets/148480722/02195327-1b95-472d-832f-32dce0a05738)

What is meant by this?? Can I fork and develop new app??

**Comment by fast4x** [comment]
The idea of the beta version is not bad, but should necessarily replace the weekly release because it becomes unsustainable as a workload.

**Comment by fast4x** [comment]
> ![Screenshot_2024-03-27-22-48-00-005_com.github.android.jpg](https://github.com/fast4x/RiMusic/assets/148480722/02195327-1b95-472d-832f-32dce0a05738)
> 
> What is meant by this?? Can I fork and develop new app??

You have just forked RiMusic, so you can continue developing your version in your repository.

**Comment by fast4x** [comment]
Actually custom version it's not planned, is only courtesy for test specific bug...

**Comment by SureshTimma** [comment]
@fast4x why don't you post it on Play Store?

**Comment by ikanakova** [comment]
> @fast4x why don't you post it on Play Store?

Google and YouTube is one company that would definitely not like the fact that there is an alternative client that plays music from YouTube Music without ads and without paying. So not only would we soon be kicked out of Google Play, but it might have other unpleasant consequences. Plus, publishing on Google Play isn't free, and apps that aren't in a gray area like this one don't consider release on Google Play because of it, such as Breezy Weather.

**Comment by SureshTimma** [comment]
> > @fast4x why don't you post it on Play Store?
> 
> Google and YouTube is one company that would definitely not like the fact that there is an alternative client that plays music from YouTube Music without ads and without paying. So not only would we soon be kicked out of Play Store, but it might have other unpleasant consequences. Plus, publishing on Google Play isn't free, and apps that aren't in a gray area like this one don't consider release on Google Play because of it, such as Breezy Weather.

But songtube is already on Play Store!

**Comment by ikanakova** [comment]
> > > @fast4x why don't you post it on Play Store?
> > 
> > 
> > Google and YouTube is one company that would definitely not like the fact that there is an alternative client that plays music from YouTube Music without ads and without paying. So not only would we soon be kicked out of Play Store, but it might have other unpleasant consequences. Plus, publishing on Google Play isn't free, and apps that aren't in a gray area like this one don't consider release on Google Play because of it, such as Breezy Weather.
> 
> But songtube is already on Play Store!

If you mean this [app](https://github.com/SongTube/SongTube-App), it doesn't have an official version on Google Play. I'm sure there's a fake version of Newpipe and quite possibly ViMusic/RiMusic on Google Play as well.

**Comment by Vishcot** [comment]
> The daily version can be downloaded from Actions. But it would be great if there was a weekly beta version that wasn't on F-Droid (or not on the official one, but could be its own F-Droid repository) and once in a while a stable version that was on the official F-Droid. Because F-Droid can't keep up with the weekly releases anyway.

Why am I not able to download the daily version? Form actions. There is no downloadable file!

**Comment by ikanakova** [comment]
>> The daily version can be downloaded from Actions. But it would be great if there was a weekly beta version that wasn't on F-Droid (or not on the official one, but could be its own F-Droid repository) and once in a while a stable version that was on the official F-Droid. Because F-Droid can't keep up with the weekly releases anyway.
> 
> @ikanakova Why am I not able to download the daily version From actions? There is no downloadable file or atleast i am not familiar with where it can be placed.
> Please let me know..?
> From where i can download
> 
> screen-20240328-225840_1711646955109.mp4 🎥 View video 

It seems that app-debug.apk is not in Actions for everything.

**Comment by NikunjKhangwal** [comment]
A lot of new bugs occur with new features added and changes to codebase. I think a beta testing is really needed. Or maybe something similar to how [LinkSheet](https://github.com/LinkSheet/LinkSheet?tab=readme-ov-file#nightly-builds) does it. A nightly version is built automatically on every commit with Github actions. They use seperate repo for it, i dont know if that's necessary. Maybe release automatic builds in same repo but don't mark them as "latest". Put a warning that it's a testing release and keep releasing stable version every Friday just like usual.
