### ISSUE TITLE
Songs missing from playlist 

### ISSUE THREAD

**Issue by Mazzaick** [fast4x/RiMusic#1253]
### Description

I wanna fully switch to RiMusic but my playlist got songs missing.

### Suggested Solution

Ain't no developer. But if I just had the tool the transfer all my songs I would love it. 

### Additional Context

https://github.com/fast4x/RiMusic/assets/163065910/17d8fb9e-0683-4c16-88ba-83badc1d22c0

**Comment by fast4x** [comment]
Hi, you can import your playlist, look this
![2024-03-27_23h39_42](https://github.com/fast4x/RiMusic/assets/1484476/ae71565f-0b82-4449-9ed8-443283d6fc9a)

**Comment by fast4x** [comment]
I will try your playlist, can paste this url please?

**Comment by Mazzaick** [comment]
> I will try your playlist, can paste this url please?

https://music.youtube.com/playlist?list=PLAYwR3Y6i5hl8WhA_3R0LRpklNmwSJXJs&si=s8K5FIKEEfxQG8dj

That's the big one ⬆️


https://music.youtube.com/playlist?list=PLAYwR3Y6i5hkeU27uIEqiEW_4RNBxf96V&si=M-osJ-BWPykG_d73

This the small one ⬆️ 
I send both just in case

**Comment by Mazzaick** [comment]
> Hi, you can import your playlist, look this ![2024-03-27_23h39_42](https://private-user-images.githubusercontent.com/1484476/317537368-ae71565f-0b82-4449-9ed8-443283d6fc9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDQwOTIsIm5iZiI6MTcxMTYwMzc5MiwicGF0aCI6Ii8xNDg0NDc2LzMxNzUzNzM2OC1hZTcxNTY1Zi0wYjgyLTQ0NDktOWVkOC00NDMyODNkNmZjOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDUyOTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQ0MjdmMTM4NTIxNDkwOWQyZjEwMWU5M2E4Y2IxNzI5YWY2NTVkMmJmOTg3YTU1ODhlMzBkZWY0MWJiMjEwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kmnAzAyxRydDXPSqhYjxDs7lpl7B4wi2cCbjv1yeGTg)

Yea ik that but there songs missing.

**Comment by Mazzaick** [comment]
> Hi, you can import your playlist, look this ![2024-03-27_23h39_42](https://private-user-images.githubusercontent.com/1484476/317537368-ae71565f-0b82-4449-9ed8-443283d6fc9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDQxODMsIm5iZiI6MTcxMTYwMzg4MywicGF0aCI6Ii8xNDg0NDc2LzMxNzUzNzM2OC1hZTcxNTY1Zi0wYjgyLTQ0NDktOWVkOC00NDMyODNkNmZjOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDUzMTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzE2MGFlNjgwZmYwMzQwZDcwZGIzZmExN2RlZjBkOTVmMTQzZDYyYTFmMzc1N2M2Njc3M2U4NmUwMmYwOGU3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KYIsfKDB1NCfUghD6ni625uJlevqGTuaf0pc9un5EQE)

The original playlist has 939 songs
On rimusic appears only 497

**Comment by Jaydeehero** [comment]
I  suggest you try Musconvtool, If you're a music lover like me who enjoys experimenting with different streaming platforms, MusConvTool is a must-have tool in your arsenal. It's reliable, efficient, and takes the headache out of playlist management.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.38
