### ISSUE TITLE
[Feature]: Lofi theme option

### ISSUE THREAD

**Issue by ARBoyGo** [fast4x/RiMusic#1258]
### Description

Probably something new. I believe no one tried it. A option to play lofi theme. Since it's not core feature. I don't recommend. It'll be a plus. : ) 
You can see something similar dragos did in his EFY projects. https://efy.ooo/media.html

### Suggested Solution

Now we have option to change player action bar. A new option lofi theme, Inside it we have options to adjust volume of nature, rain. Etc.... Probably a new sheet.

**Comment by fast4x** [comment]
I honestly do not like, can you explain better what you mean by adjust nature?

**Comment by fast4x** [comment]
Efy is written in classic html/css/js so I can't porting in Kotlin because there is a lot of work.
