### ISSUE TITLE
[Feature]: downloaded songs folder

### ISSUE THREAD

**Issue by gun4qmm7h** [fast4x/RiMusic#1259]
### Description

When a song is downloaded it should show in amusic folder

### Suggested Solution

Show download songs

**Comment by ikanakova** [comment]
> When a song is downloaded it should show in amusic folder

No, it shouldn't, see https://github.com/fast4x/RiMusic/discussions/1226 and it's not planned #1143

**Comment by gun4qmm7h** [comment]
Would you be able to change that? I want to set my alarm to some music when waking up

**Comment by Nikks84** [comment]
> Would you be able to change that? I want to set my alarm to some music when waking up

Then download songs from Google The song you want to set in alarm

**Comment by ikanakova** [comment]
> > Would you be able to change that? I want to set my alarm to some music when waking up
> 
> Then download songs from Google The song you want to set in alarm

For downloading from Youtube you can use Newpipe (on Android), FreeTube (Windows, macOS, linux), youtube-dl, etc.
