### ISSUE TITLE
"My top" and "On device" still showing on the sidebar even though turned off in the settings

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1261]
### Steps to reproduce the bug

Open "Favorites" or "Downloaded"

### Expected behavior

Playlists that are turned off in the settings shouldn't show.

### Actual behavior

"My top" and "On device" showing on the sidebar when any other default/app provided playlist is opened.

### Screenshots

![Screenshot_20240328-132216](https://github.com/fast4x/RiMusic/assets/85461823/cd788004-abf9-4b9f-abc6-211bd8228b7d)

![Screenshot_20240328-132242](https://github.com/fast4x/RiMusic/assets/85461823/40f8c13d-8892-4bd5-940b-b366a76476d9)

### RiMusic version

0.6.27 (the latest custom version tho…I think)

### Android version

Android 11

### Additional information

Those playlists doesn't show on the library. Just inside playlist on sidebar just as it is in the ss.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.28, thanks
