### ISSUE TITLE
[Feature]: Option to remove songs from "SONGS" that were on the device

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#1262]
### Description

Option to remove "on device" songs from "SONGS". I'm not able to delete "on device" songs from "SONGS" even though I've deleted the song from my device.

https://github.com/fast4x/RiMusic/assets/127825700/e22c1ed9-fcc7-4e00-98b9-9c54916d2bc2

### Suggested Solution

An option to remove will be great

**Comment by fast4x** [comment]
Implemented, show/hide in home songs, available from version 0.6.28

**Comment by dainvincible1** [comment]
> Implemented, show/hide in home songs, available from version 0.6.28

thank you

**Comment by fast4x** [comment]
You are welcome
