### ISSUE TITLE
Add a button for quick access to system equalizer 

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#1269]
### Description

Add a button in the player action bar to quickly access the system equalizer. I just think it would be a good addition for convenience 

![IMG_20240328_235813](https://github.com/fast4x/RiMusic/assets/160244930/1621d951-a31a-4eb5-b1ba-485a4f0bc398)
something like this 

### Suggested Solution

There should be an option to enable a button for the system equalizer in the player action bar

**Comment by cMattw** [comment]
_this is definitely not related to an issue within my device, and absolutely not related to an issue I made not long ago_

**Comment by ikanakova** [comment]
If a button would be added, please an enable/disable option like lyrics etc in settings.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.28

**Comment by NightFly88** [comment]
> Implemented, available from version 0.6.28

If you add the equaliser, where does that leave the others button

**Comment by fast4x** [comment]
Choose the user which buttons to enable, depends on the size of the screen.

**Comment by NightFly88** [comment]
> Kies voor de gebruiker welke knoppen hij wil inschakelen, afhankelijk van de grootte van het scherm.

Okay
