### ISSUE TITLE
Implement automatic backup

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1276]
### Description

package it.vfsfitvnm.vimusic.ui.screens.settings

import android.annotation.SuppressLint
// ... other imports ...
import androidx.work.ExistingPeriodicWorkPolicy
import androidx.work.PeriodicWorkRequestBuilder
import androidx.work.WorkManager
import java.util.concurrent.TimeUnit

@SuppressLint("SuspiciousIndentation")
@OptIn(ExperimentalCoilApi::class)
@ExperimentalAnimationApi
@UnstableApi
@Composable
fun DataSettings() {
    // ... other variables ...

    // Automatic backup configuration (replace with your desired frequency)
    val backupFrequency = "daily" // Options: "daily", "weekly", "monthly"

    // ... other UI code ...

    // Helper function for database backup
    fun backupDatabase() {
        query {
            Database.checkpoint()
            // ... your existing backup logic with `backupLauncher` ...
        }
    }

    // Function to schedule backups
    fun scheduleBackups() {
        val backupWorkRequest = when (backupFrequency) {
            "daily" -> PeriodicWorkRequestBuilder<BackupWorker>(1, TimeUnit.DAYS).build()
            "weekly" -> PeriodicWorkRequestBuilder<BackupWorker>(7, TimeUnit.DAYS).build()
            "monthly" -> PeriodicWorkRequestBuilder<BackupWorker>(30, TimeUnit.DAYS).build()
            else -> return // Invalid frequency, skip scheduling
        }

        WorkManager.getInstance(context)
            .enqueueUniquePeriodicWork(
                "ViMusicBackup",
                ExistingPeriodicWorkPolicy.KEEP, // Keep existing backups
                backupWorkRequest
            )
    }

    // Trigger backup scheduling during UI initialization
    LaunchedEffect(Unit) {
        scheduleBackups()
    }
}

// Define a WorkManager worker for the backup process
class BackupWorker(context: Context, workerParameters: WorkerParameters) :
    CoroutineWorker(context, workerParameters) {

    override suspend fun doWork(): Result {
        // Access your 'backupDatabase' function here to perform the backup
        backupDatabase() 
        return Result.success()
    }
}

### Suggested Solution

 Enhancements and Considerations:
 * User Settings: Add user-facing controls within the Data Settings screen to adjust backup frequency or disable automatic backups.
 * Backup Location: Decide whether to save backups to internal storage (easier) or external/cloud storage (more resilience). Adjust code accordingly.
 * Error Handling: Implement error handling within the backup function and doWork() in the BackupWorker to gracefully handle potential failures.
 * Permissions: Ensure you have any necessary permissions for external storage access, specifically on Android 10 and above.
Explanation:
 * WorkManager: Android's recommended solution for background tasks like backups.
 * LaunchedEffect:  Triggers the scheduleBackups function once when the DataSettings composable enters the composition.
 * CoroutineWorker: Subclass for WorkManager tasks that can be executed as coroutines.
 * Customizable Frequency: The logic supports daily, weekly, and monthly backup options.
Remember:
 * Add the WorkManager dependency to your build.gradle:
   implementation("androidx.work:work-runtime-ktx:2.7.1") // Or the latest version

**Comment by dAtA-TRoN** [comment]
I don't understand anything 😀.

**Comment by ikanakova** [comment]
With backups to the cloud I think it will be problematic because of possible dependence on non-free services. The only open source cloud I know is Nextcloud, but it is self-hosted as far as I know, which is not very user friendly.

**Comment by ikanakova** [comment]
> I don't understand anything 😀.

I basically only understood the part about Backup Location 😀

**Comment by SureshTimma** [comment]
Sorry, I have requested Gemini advanced, that given me this. I have pasted it corrrectly. But github changed code structure. Because of quotes in code.

**Comment by SureshTimma** [comment]
I think we can implement automatic backup to local device....

**Comment by fast4x** [comment]
> Sorry, I have requested Gemini advanced, that given me this. I have pasted it corrrectly. But github changed code structure. Because of quotes in code.

Explain me better please about Gemini...

**Comment by DarkCrypt** [comment]
> > I don't understand anything 😀.
> 
> I basically only understood the part about Backup Location 😀

Hahaha! 🤣! I didn't understand anything either. I've been severely pissed off all week and this made me laugh hard. I really needed that. God bless you all.

**Comment by SureshTimma** [comment]
> > Sorry, I have requested Gemini advanced, that given me this. I have pasted it corrrectly. But github changed code structure. Because of quotes in code.
> 
> Explain me better please about Gemini...

That a Advanced AI Model by google

**Comment by JZITNIK-github** [comment]
Are automatic backups needed? Personally for me I just back up manually once in a month or something like that and I don't see the need for automatic backups. Also saving backups on your device doesn't make sense because when you lose or damage your phone the backup will still be lost. And saving it to a cloud is also problematic as ikanakova said that you would probably need a self hosted cloud or depend on non-free software.

**Comment by ikanakova** [comment]
> Are automatic backups needed? Personally for me I just backup manually once in a month or something like that and I don't see the need for automatic backups. Also saving backups on your device doesn't make sense because when you lose or damage your phone the backup will still be lost. And saving it to a cloud is also problematic as ikanakova said that you would probably need a self hosted cloud or depend on non-free software.

Good point. It's true that I don't even miss the automatic backup in this application.

**Comment by NikunjKhangwal** [comment]
I only need automatic backup to local storage and not necessarily cloud. I use [Round Sync](https://github.com/newhinton/Round-Sync) for backing up my encryption keys, game files and auto backups from other apps to the cloud storage of my choice.

**Comment by ikanakova** [comment]
I use Total Commander for Android with add-ons for OneDrive, Dropbox and Google Drive. But the Round Sync one looks interesting and is open source ♥️ But it's not on the F-Droid, which is a pity.

**Comment by NikunjKhangwal** [comment]
It is available in Izzy repo

**Comment by FelixSchrodinger** [comment]
> Are automatic backups needed? Personally for me I just backup manually once in a month or something like that and I don't see the need for automatic backups. Also saving backups on your device doesn't make sense because when you lose or damage your phone the backup will still be lost. And saving it to a cloud is also problematic as ikanakova said that you would probably need a self hosted cloud or depend on non-free software.

This feature would be a gamechanger but only if the app backs up regularly then potentially restores from the backup on each open of the app. Why? Cross-device sync. My TV, phone, tablet would all have the same playlists that way.

Plenty of free cloud options. Dropbox, Mega, OneDrive. I know it may be a pain to implement due to cloud login etc but the option to choose network storage, or device storage (which could be synchronised with cloud in other apps).
