### ISSUE TITLE
Album Page formatting is buggy

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1284]
### Steps to reproduce the bug

Go to album Page.

### Expected behavior

It should look great.

### Actual behavior

It doesn't.

### Screenshots/Screen recordings

![9835f322-022d-4359-a38a-25374e47c6a7.png](https://github.com/fast4x/RiMusic/assets/71184627/e2908381-5e99-4823-be2e-6cbeb0a831da)

### RiMusic version

0.6.28

### Android version

Android 13

### Additional information

Thanks for your hard work 🙏🏼!

**Comment by NikunjKhangwal** [comment]
At least your albums are loading. Mine seem to be broken

**Comment by NightFly88** [comment]
the album poster is too big,and on playback the poster is smaller,

**Comment by dAtA-TRoN** [comment]
> the album poster is too big,and on playback the poster is smaller,

Could you provide a screenshot?

**Comment by NightFly88** [comment]
> > the album poster is too big,and on playback the poster is smaller,
> 
> Could you provide a screenshot?

Cannot upload photo🤣🤣

**Comment by dAtA-TRoN** [comment]
> Cannot upload photo🤣🤣

![IMG_20240329_191646.jpg](https://github.com/fast4x/RiMusic/assets/71184627/2215fbf1-9577-4368-b280-67d0c08054ac)

**Comment by NightFly88** [comment]
It's not a big deal,slightly bigger 
![Picsart_24-03-29_19-21-59-553](https://github.com/fast4x/RiMusic/assets/163666747/e8045833-039b-42a4-a770-c7c1e527cbea)

🤣

**Comment by dAtA-TRoN** [comment]
> It's not a big deal,slightly bigger 🤣

Oh I see. I believe this is intentional because the new formatting of the album page provides more space for the album cover. However, you can adjust the size of the cover within the player View in the app settings if you wish so.

**Comment by NightFly88** [comment]
Only in picture 1 can you adjust the size

**Comment by dAtA-TRoN** [comment]
> Only in picture 1 can you adjust the size

Right, "player view"... -As I said 😛😄.

**Comment by NightFly88** [comment]
> > Only in picture 1 can you adjust the size
> 
> Right, "player view"... -As I said 😛😄.

😂

**Comment by fast4x** [comment]
![Screenshot_2024-03-29-19-41-54-165_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/8dee3c5c-8876-426a-be3a-5d0aa55a3898)

**Comment by fast4x** [comment]
![Screenshot_2024-03-29-19-41-54-165_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/8dee3c5c-8876-426a-be3a-5d0aa55a3898)

oookkk i can decrease it like in the player

**Comment by NightFly88** [comment]
> ![Screenshot_2024-03-29-19-41-54-165_it.fast4x.rimusic.jpg](https://private-user-images.githubusercontent.com/1484476/318117025-8dee3c5c-8876-426a-be3a-5d0aa55a3898.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MzgxNDUsIm5iZiI6MTcxMTczNzg0NSwicGF0aCI6Ii8xNDg0NDc2LzMxODExNzAyNS04ZGVlM2M1Yy04ODc2LTQyNmEtYmUzYS01ZDBhYTU1YTM4OTguanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjlUMTg0NDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTg5ZDIzNjMyODE3MGNjNTU4NmJlYjllYTIzZTYwNTJiNzRkOWJjNzgxZmExNjJhOTgzM2NiY2E4NGEzOTRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0DDcUh5WUunz61qvB3Jy8zDl0z9XLfEap_xGHcg4pmo)
> 
> oookkk i can decrease it like in the player

Yes thanks

**Comment by dAtA-TRoN** [comment]
> oookkk i can decrease it like in the player

Why not link the cover size to the player's set size? Asking for a friend 👀.

**Comment by fast4x** [comment]
Improved, available from version 0.6.29 and soon in custom version 0.6.28

**Comment by fast4x** [comment]
Download https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by sayyid5416** [comment]
![image](https://github.com/fast4x/RiMusic/assets/78584556/16e7c4fc-d141-425e-9421-d9f632f16661)

These icons were already so inconsistent, one more layout is added now lol #1072

**Comment by dAtA-TRoN** [comment]
> Improved, available from version 0.6.29 and soon in custom version 0.6.28

Wow, thank you so much for the hot fix. It's all running as it should now and in love with the new album page. Looks gorgeous! High five bro: 🥹🫸🏻🫷🏻👨🏻‍💼

**Comment by fast4x** [comment]
> ![image](https://github.com/fast4x/RiMusic/assets/78584556/16e7c4fc-d141-425e-9421-d9f632f16661)
> 
> These icons were already so inconsistent, one more layout is added now lol #1072 

How would you like them?

**Comment by NightFly88** [comment]
> Download https://github.com/fast4x/RiMusic/tree/master/customVersion

Wow that is fast,many thanks

**Comment by sayyid5416** [comment]
> > ![image](https://private-user-images.githubusercontent.com/78584556/318156992-16e7c4fc-d141-425e-9421-d9f632f16661.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTI1MzksIm5iZiI6MTcxMTc5MjIzOSwicGF0aCI6Ii83ODU4NDU1Ni8zMTgxNTY5OTItMTZlN2M0ZmMtZDE0MS00MjVlLTk0MjEtZDlmNjMyZjE2NjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA5NTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxM2ZiZTc4YjcxOTQwNDg2YTkzYWE5OGNkODA4ODRkNjI2N2QxNWViY2IxMDNkYjZiMDM0YTBkNDFhZjE5ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hpbNV48N1Qnev740njKBFHgxxB9zSHU2szxxAfR68Fs)
> > These icons were already so inconsistent, one more layout is added now lol #1072
> 
> How would you like them?

I don't have a personal preference regarding this, but as I pointed out in #1072, These icons are becoming more inconsistent.

Whatever be the solution, they should be consistent throughout the app.

**Comment by dAtA-TRoN** [comment]
> Wow that is fast,many thanks

He's not called fast4x for nothing 😬.
