### ISSUE TITLE
On device add to playlist bug

### ISSUE THREAD

**Issue by Lio-gif** [fast4x/RiMusic#1286]
### Steps to reproduce the bug

So when i add a on device Song to a playlist IT Shows the File Name without a Cover but on on device IT is the Tag Name of the Song this only Happens with one specific File 

### Expected behavior

IT Shows the tags

### Actual behavior

IT doesnt

### Screenshots/Screen recordings

Schould be Like this 
![Screenshot_2024-03-29-18-50-53-873_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/149175168/03238c58-b0a0-4183-b9c2-17ef8ffc8689)
 Is like this 
![Screenshot_2024-03-29-18-51-40-134_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/149175168/bb7dcffb-7df8-4fb1-b210-cfa7c378b066)

### RiMusic version

Newest

### Android version

Android 14

**Comment by fast4x** [comment]
@JZITNIK-github

**Comment by JZITNIK-github** [comment]
Is it doing this on just this song? Is it doing just with the newest version or was it doing in older versions?

@fast4x I think this is something similar to the previous issue where there was a problem with the song length not being in the DB.

**Comment by JZITNIK-github** [comment]
Is it doing this on just this song? Is it doing just with the newest version or was it doing in older versions?

@fast4x I think this is something similar to the previous issue where there was a problem with the song length not being in the DB.

**Comment by Lio-gif** [comment]
> Is it doing this on just this song? Is it doing just with the newest version or was it doing in older versions?
> 
> @fast4x I think this is something similar to the previous issue where there was a problem with the song length not being in the DB.

On the Last Version ist was the same also only for the new Body song

**Comment by JZITNIK-github** [comment]
> On the Last Version ist was the same also only for the new Body song

Ok I'm not sure if I understood correctly. So it is happening only in the newest version and was not happening before. Did I understand correctly?

**Comment by Lio-gif** [comment]
> > On the Last Version ist was the same also only for the new Body song
> 
> Ok I'm not sure if I understood correctly. So it is happening only in the newest version and was not happening before. Did I understand correctly?

The Bug also was in 0.6.27

**Comment by JZITNIK-github** [comment]
> > > On the Last Version ist was the same also only for the new Body song
> > 
> > Ok I'm not sure if I understood correctly. So it is happening only in the newest version and was not happening before. Did I understand correctly?
> 
> The Bug also was in 0.6.27

Thanks for the details. I'll look at it.

**Comment by JZITNIK-github** [comment]
Works fine for me. I created a file called `untitled.mp3` with some metadata title and artist and when I add it to a playlist I see it normally.

On device:
![Screenshot_20240329_221703.jpg](https://github.com/fast4x/RiMusic/assets/72742578/81e8a062-f25f-4223-aaa9-918f3a68059f)
Playlist:
![Screenshot_20240329_221738.jpg](https://github.com/fast4x/RiMusic/assets/72742578/57e7b431-77cc-4f45-bab6-6e19d4592796)

Could you please send me the file so I can try it on my device? But I think that the problem is that the song is corrupted in the local Database and it is showing the corrupted data. Because the playlist gets the data from DB but On Device page gets it directly from the storage.

**Comment by fast4x** [comment]
Also for me, it work.

**Comment by Lio-gif** [comment]
Mega Link: https://mega.nz/file/EXlnFSKR#heCWxAWZkyCIVL_3pPJnk2Tzl6n4okWMUsRYHOaosOQ

**Comment by JZITNIK-github** [comment]
Works fine for me.

**Comment by Lio-gif** [comment]
Hmm weird
