### ISSUE TITLE
The new album icon is displayed incorrectly

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1287]
### Steps to reproduce the bug

Just go and watch it in the App.

### Expected behavior

The CD within the frame should be displayed larger.

### Actual behavior

The CD is displayed too small.

### Screenshots/Screen recordings

![add2a113-f010-44e9-9cf4-b13542bfc853](https://github.com/fast4x/RiMusic/assets/71184627/b62c717b-26d2-49de-b25e-fe7bb298f2ea)

### RiMusic version

0.6.28

### Android version

Android 13

**Comment by dAtA-TRoN** [comment]
@ikanakova

**Comment by ikanakova** [comment]
That's on purpose, because it represents a cover with a picture of the disc on top. If it was bigger I think it would be confused with the single icon.

**Comment by dAtA-TRoN** [comment]
> That's on purpose, because it represents a cover with a picture of the disc on top. If it was bigger I think it would be confused with the single icon.

Oh, okay. I don't think it isn't as confusing as you think. Just look at my mockup. To be honest, I think the opposite is the case because the recognition value is reduced. It is no longer so easily associated with a CD. But hey, just my daily two cents 🤷🏻‍♂️.

**Comment by ikanakova** [comment]
>> That's on purpose, because it represents a cover with a picture of the disc on top. If it was bigger I think it would be confused with the single icon.
> 
> Oh, okay. I don't think it isn't as confusing as you think. Just look at my mockup. To be honest, I think the opposite is the case because the recognition value is reduced. It is no longer so easily associated with a CD. But hey, just my daily two cents 🤷🏻‍♂️.

OK, I'll improve it according to your suggestion.

**Comment by ikanakova** [comment]
>> OK, I'll improve it according to your suggestion.
> 
> Only if you want that too. Always remember, I'm not your God or something 😂.

I have absolutely no idea what to say to this except: 🤣😂🤣😂🤣😂🤣

**Comment by dAtA-TRoN** [comment]
> I have absolutely no idea what to say to this except: 🤣😂🤣😂🤣😂🤣

![proxy-image.gif](https://github.com/fast4x/RiMusic/assets/71184627/e38b1b91-46f3-43b4-9815-628f1392d00b)
