### ISSUE TITLE
[BUG] : Background player is too big 💀

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#1289]
### Steps to reproduce the bug

Just play a song in offline or online or from the device

### Expected behavior

Should have the good size, with like and download button 

### Actual behavior

It's a big player 💀, and like button is missing

### Screenshots/Screen recordings

![Screenshot_2024-03-29-19-44-41-205_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/83852cc7-682a-42ed-a1c2-a10289d45aa6)
![Screenshot_2024-03-29-19-44-03-908_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/9207e67d-aacf-4a8f-a9e5-cb2ba0bfea23)

### RiMusic version

0.6.28

### Android version

A12 MIUI14.0.4 MIXM

**Comment by NEVARLeVrai** [comment]
Update I closed ri music and re open and got fix by its self weird

**Comment by fast4x** [comment]
Oh my god!

**Comment by NEVARLeVrai** [comment]
> Oh my god!

Got fixed when I restarted app I don't know got the same reaction didn't know it can be big like that also 😭, I think maybe because I enable and disable some things on the player that caused this idk can't reproduce it

**Comment by fast4x** [comment]
Improved, available from version 0.6.29 and soon in custom version 0.6.28

**Comment by fast4x** [comment]
Download https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by BeInvisible07** [comment]
> Download https://github.com/fast4x/RiMusic/tree/master/customVersion

Is that beta or stable version?

**Comment by fast4x** [comment]
is a stable same version 0.6.28 with some fixes after release 0.6.28

**Comment by BeInvisible07** [comment]
> is a stable same version 0.6.28 with some fixes after release 0.6.28

![Screenshot_2024-03-31-01-01-48-947_com mi android globallauncher](https://github.com/fast4x/RiMusic/assets/152383072/339b6af6-f01f-48f0-9097-b9a080912d6f)
I am using this version but now i am facing low resolution image on background player (it looks very pixelated). is there any option to increase the resolution of image in background player?

**Comment by fast4x** [comment]
is strange, not anything for resolution in background player, is automatic. I'll check this

**Comment by NikunjKhangwal** [comment]
Imagine fast4x purposely doing it just for April Fools 😂

**Comment by fast4x** [comment]
😂😂😂
