### ISSUE TITLE
Feature Request: Time Capsule and Most Played Artist

### ISSUE THREAD

**Issue by ADIT011007** [fast4x/RiMusic#1290]
### Description

I would like to suggest implementing a 'Time Capsule' feature in the RI Music app, similar to Spotify's functionality. This feature would track users' monthly and yearly listening durations, display average listening times, highlight the preferred time of day for listening, such as mornings, afternoons, or evenings, and if possible, include a section showcasing the most played artist.
![Screenshot_2024-03-30-01-13-39-258_com spotify music](https://github.com/fast4x/RiMusic/assets/77261726/88cfc598-01fb-4d07-9d65-c2665bc17e57)

### Suggested Solution

The suggested solution involves incorporating a 'Time Capsule' feature within the RI Music app. This feature would track users' monthly and yearly listening durations, provide average listening times, indicate preferred listening times (morning, afternoon, evening), and ideally include a section displaying the most played artist. This comprehensive overview would enhance user engagement and provide valuable insights into their music consumption habits.

**Comment by fast4x** [comment]
Do you have look at statistics section in RiMusic?

**Comment by ADIT011007** [comment]
> Do you have look at statistics section in RiMusic?

Yeah I just found out after posting this. Sorry
