### ISSUE TITLE
Albums won't load

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1291]
### Steps to reproduce the bug

Open any album 

### Expected behavior

Should open without any problem.

### Actual behavior

Just keeps loading.

### Screenshots/Screen recordings

![Screenshot_20240330-014752](https://github.com/fast4x/RiMusic/assets/85461823/270c7ba5-693f-4736-ac31-ef772eb747b9)

https://github.com/fast4x/RiMusic/assets/85461823/bc11eb17-37c5-40d1-bad8-6c156b9d6076

### RiMusic version

0.6.28

### Android version

Android 11

### Additional information

Not just this album. None of the albums I try to open is loading.

**Comment by NightFly88** [comment]
Here too

**Comment by dAtA-TRoN** [comment]
Is that the case with multiple albums?

**Comment by dAtA-TRoN** [comment]
Have you tried clearing the app's cache on Android and closing it properly?

**Comment by fast4x** [comment]
> > Is that the case with multiple albums?
> 
> Yup. Since the last update I haven't been able to open any album other than the ones I have saved on Albums tab. I wonder why those open properly though…because of cache!?

I'll check it

**Comment by fast4x** [comment]
Fixed, available from version 0.6.29 and soon in custom version 0.6.28

**Comment by fast4x** [comment]
Download https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by fast4x** [comment]
Perfect thanks for feedback

**Comment by NikunjKhangwal** [comment]
I think a quick fix version should be released. Many people don't know about custom version and this is a major issue.
(nice music taste btw)

**Comment by fast4x** [comment]
OK, between today and tomorrow I will publish an official update. ❤️
