### ISSUE TITLE
Layout 

### ISSUE THREAD

**Issue by Priyamjainrg1** [fast4x/RiMusic#1292]
### Description

Please remove bottom toggles from player and shift it into 3dot or in thumbnail and add arrow there to represent that there is sequence of songs in queue. But GREAT WORK ❤️❤️❤️❤️

### Suggested Solution

![Screenshot_2024-03-30-01-31-57-363_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/165423711/9539d6bc-691a-44c4-9a5b-d65975307c04)

**Comment by dAtA-TRoN** [comment]
> Please remove bottom toggles from player and shift it into 3dot or in thumbnail

Why would you want that?

**Comment by dAtA-TRoN** [comment]
> Please remove bottom toggles from player and shift it into 3dot or in thumbnail

Why would you want that?

**Comment by dAtA-TRoN** [comment]
> You can turn off all those toggles from settings if you want.

But does that mean there's still a way to use these features somehow, or do they simply become unavailable? If it's the latter, then I think deactivated buttons should automatically migrate to the three-dot menu 🤔...

**Comment by dAtA-TRoN** [comment]
I completely agree with you.

**Comment by Priyamjainrg1** [comment]
Thanks for your support and your precious time. I think your team should work only for improvement and stability and  afterwards features can be added. Generally people like  more simplicity in app so that it will be easier to access things so that's why I am telling that removing items from there will more better THANKS

**Comment by dAtA-TRoN** [comment]
> I think your team should work only for improvement and stability and afterwards features can be added

Well, typically everything desired is installed first before focusing on the fine-tuning. That's actually the usual process. I understand your perspective, but minimalism is probably not the main goal here. Most people here definitely prefer more features, and we also keep coming up with new ideas 😅.

**Comment by ikanakova** [comment]
I can't speak for most people (although I doubt most people want simplicity), but what I like about RiMusic is that it can do a lot of things, but what I don't want to use I can disable in the settings. But if it had moved to a three-dot menu instead, that would probably be fine too. Or the option in the settings to disable or migrate to the 3 dots menu.

**Comment by sayyid5416** [comment]
there should a setting to control this behavior, because migrating all features to 3 dot menu will clutter it.

**Comment by Priyamjainrg1** [comment]
Thanks ❤️

**Comment by NikunjKhangwal** [comment]
A grid style menu like Innertune can reduce the clutter. I've made a issue about it

**Comment by sayyid5416** [comment]
> A grid style menu like Innertune can reduce the clutter. I've made a issue about it

Can you share a ss?

**Comment by NikunjKhangwal** [comment]
> Can you share a ss?

Check #1184

**Comment by sayyid5416** [comment]
looks great
