### ISSUE TITLE
Features 

### ISSUE THREAD

**Issue by Priyamjainrg1** [fast4x/RiMusic#1294]
### Description

My request to you sir that please make app easier to use because there are so many settings and there is no clearance that which settings is for what 

### Suggested Solution

Reduced useless settings like no of feeds and remove download and favourite button from notification it is blurred

**Comment by dAtA-TRoN** [comment]
> My request to you sir that please make app easier to use because there are so many settings and there is no clearance that which settings is for what

I think all of that will come eventually anyway. fast4x is working on the app all by himself, and Rome wasn't built in a day either. I'm sure the settings will be revised or restructured at some point. Don't be too pleased about the app offering so many features at the moment.

**Comment by Priyamjainrg1** [comment]
Thanks  ❤️

**Comment by fast4x** [comment]
Reduced useless settings like no of feeds and remove download and favourite button from notification it is blurred

Disable by settings...
