### ISSUE TITLE
Progress bar getting expanded when player is full screen 

### ISSUE THREAD

**Issue by ADIT011007** [fast4x/RiMusic#1295]
### Steps to reproduce the bug

1 : play any song 
2 : You will see a progress bar on bottom ( minimised player ) 
3 : click on it and u will see big red bar 

https://github.com/fast4x/RiMusic/assets/77261726/ff4dc7d2-76be-416e-8b2e-45434d7131c4

### Expected behavior

After following the steps u would see the progress bar getting expanded behind the player while the players is in full screen . As shown in the video 

### Actual behavior

The progress bar should not appear in background of player when in full screen 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/77261726/53af1798-1cef-42a4-8ce7-e4b0fe6eddd8

### RiMusic version

0.6.28

### Android version

Android 11

**Comment by dAtA-TRoN** [comment]
That's actually not a bug, but a feature. You can change it in the settings.

**Comment by fast4x** [comment]
yiu can disable progress bar in player appearance settings

**Comment by dAtA-TRoN** [comment]
> yiu can disable progress bar in player appearance settings 

FIRST 😆!!!

**Comment by ADIT011007** [comment]
> That's actually not a bug, but a feature. You can change it in the settings.
> 
> ![IMG_20240329_214630.jpg](https://private-user-images.githubusercontent.com/71184627/318135318-108b32ad-0f6c-4e7c-9d9a-10e7dbcc23fd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NDU2MzAsIm5iZiI6MTcxMTc0NTMzMCwicGF0aCI6Ii83MTE4NDYyNy8zMTgxMzUzMTgtMTA4YjMyYWQtMGY2Yy00ZTdjLTlkOWEtMTBlN2RiY2MyM2ZkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDIwNDg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNmEwODM4YjM3YTlkMzYwYmNhZjg2YTZiNTkwYTZmYzMwODQwZDhjM2UzOTVjYzBlMzAwY2RkNTBiNjRjZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._gUtoMX3xFQoA_Nj3AfbKw7r11orOy_LHIqMKokNA8U)

Thanks a lot 😊😊🙏🏼

**Comment by fast4x** [comment]
> > yiu can disable progress bar in player appearance settings 
> 
> FIRST 😆!!! 

You Win!! 😂🤣
