### ISSUE TITLE
Albums not working

### ISSUE THREAD

**Issue by alexandresique** [fast4x/RiMusic#1298]
### Steps to reproduce the bug

Moto g60: music albums do not load songs
![Screenshot_20240329-202455](https://github.com/fast4x/RiMusic/assets/111403789/d09c8411-7774-4181-b057-79837271f521)

### Expected behavior

Full

### Actual behavior

Full

### Screenshots/Screen recordings

Full

### Logs

Full

### RiMusic version

V0.6.28

### Android version

Android 12

### Additional information

Full

**Comment by fast4x** [comment]
Download https://github.com/fast4x/RiMusic/tree/master/customVersion

Fixed in custom version

**Comment by Mav729** [comment]
youtube featured are not loading since update 6.2.21

**Comment by fast4x** [comment]
download custom version it's fixed
