### ISSUE TITLE
Swipe to change song in now playing

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#13]
### Description

Would be cool if you could change the title on the "Now Playing" screen by swiping.

### Suggested Solution

*

**Comment by fast4x** [comment]
Can you insert some more details please?

**Comment by siggi1984** [comment]
Swipe left on the cover image for the next song, swipe right for the previous song.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.8

**Comment by OrangeZXZ** [comment]
> Implemented, available from version 0.6.8

the issue can be closed right? or maybe closing it after the update?

**Comment by fast4x** [comment]
It’s better after the release, so I have a trace for the release notes.
