### ISSUE TITLE
[Feature]: Icons

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#1300]
- `User interface`, `Miscellaneous` icon size not matching in settings page.
- `Artists` icon mismatch on home page and after searching for some artists.
- `Library` icon feels from different design language.
- `Miscellaneous` and `Equalizer` icons needs to be different.

**Comment by sayyid5416** [comment]
@ikanova

**Comment by sayyid5416** [comment]
@ikanakova

**Comment by ikanakova** [comment]
I'll look into it.

**Comment by ikanakova** [comment]
I think the equalizer icon (<img src="https://raw.githubusercontent.com/fast4x/RiMusic/master/assets/icons/equalizer.svg" width="20">) and the miscellaneous icon (<img src="https://raw.githubusercontent.com/fast4x/RiMusic/master/assets/ionicons/options.svg" width="20">) are probably swapped.

**Comment by ikanakova** [comment]
I'm planning to resize all SVG icons that are in the app, to make it easy to fast4x resize in the code. I hope it won't add too much work for him. I might even convert them to vector drawable, but I don't dare to modify them in code.

**Comment by ikanakova** [comment]
![image](https://c8.alamy.com/comp/RMAWTB/equalizer-icons-set-on-white-background-for-graphic-and-web-design-modern-simple-vector-sign-internet-concept-trendy-symbol-for-website-design-web-button-or-mobile-app-RMAWTB.jpg)

What do you think of the equalizer icon that's second from the right in the third row?

Although it might be a good icon for the visualizer.

Maybe if just resizing the existing equalizer icon would be enough?

**Comment by SureshTimma** [comment]
@ikanakova please change these icons! Please 🥺. Make sure all icons are same type. I have mentioned mistakes in below screenshots!

![Screenshot_2024-04-01-13-16-40-324_it.fast4x.rimusic~2.jpg](https://github.com/fast4x/RiMusic/assets/148480722/6fa6f5e2-c3a1-4db1-b172-724ae81a7f1f)

![Screenshot_2024-04-01-13-21-15-859_it.fast4x.rimusic~2.jpg](https://github.com/fast4x/RiMusic/assets/148480722/1c2c2fc9-1edb-452f-af4b-52cfc8f757ee)

![Screenshot_2024-04-01-13-22-38-612_it.fast4x.rimusic~2.jpg](https://github.com/fast4x/RiMusic/assets/148480722/c4c01f9e-4f75-48bd-9103-e4b58dcc0afc)

**Comment by ikanakova** [comment]
I wanted to use a solid cell phone icon, but I thought it didn't look right = you can't tell what it is.

The album icon is like that on purpose because it represents a cover with a picture of the disc X the single icon is just the disc.

**Comment by ikanakova** [comment]
The download icon and the sleep timer icon are that way because the users wanted them that way.

**Comment by ikanakova** [comment]
About icon can be changed to circle with _i_ inside - it is in assets/ionicons.

**Comment by SureshTimma** [comment]
> I wanted to use a solid cell phone icon, but I thought it didn't look right = you can't tell what it is.
> 
> The album icon is like that on purpose because it represents a cover with a picture of the disc X the single icon is just the disc.

Instead of the disc with album cover, only disc looks great. Please consider.

Please change the bedtime mood icon solid -> outline

**Comment by sayyid5416** [comment]
Were all the changes made?

**Comment by fast4x** [comment]
seems yes
