### ISSUE TITLE
Improved next songs in player

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#1302]
### Description

In my opinion, the current layout for the next song in player is too cluttered

### Suggested Solution

Change the layout of the next song in player

Something like this
![Untitled90_20240330100626](https://github.com/fast4x/RiMusic/assets/160244930/05fb7f8f-3eae-4f96-8e0f-27e96c96cdfc)

• Since there is a lot of empty space below the play/pause button, it should be moved there
• It doesn't need to show two songs
• Add `Up Next` text so the users know what it is, or perhaps a new icon

**Comment by cMattw** [comment]
![Untitled90_20240330103013.png](https://github.com/fast4x/RiMusic/assets/160244930/463d759b-6675-4fe5-9e53-838d97c5d79c)

or maybe something like this

**Comment by NikunjKhangwal** [comment]
Looks good in ViMusic style

**Comment by aneesh1122** [comment]
Implemented

https://github.com/fast4x/RiMusic/assets/45353488/916d13fa-9444-41d0-a154-2afb2773065e

Most of the chances are in Player modern.kt and you asked me to stop working on player.

So, should I do a pull request and you'll merge it manually or should I stash these files?
