### ISSUE TITLE
Can't load albums

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#1303]
### Steps to reproduce the bug

1. Search any album
2. Open it

### Expected behavior

The album of the artist should open

### Actual behavior

But instead it is showing only skeleton frame 

### Screenshots/Screen recordings

![Screenshot_20240330-075129_RiMusic](https://github.com/fast4x/RiMusic/assets/120176369/ed1f90f2-fa51-4d29-a613-062f80ca4477)

https://github.com/fast4x/RiMusic/assets/120176369/ee262f39-20a7-4a2e-bfd3-4493b06da637

### RiMusic version

0.6.28

### Android version

Android 14

**Comment by Nikks84** [comment]
See #1291

**Comment by fast4x** [comment]
Download https://github.com/fast4x/RiMusic/tree/master/customVersion

Fixed in custom version
