### ISSUE TITLE
Re-formating Custom Playlist Page (Library)

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1305]
### Description

Just look...

### Suggested Solution

...at the Mockup:

![14513a6f-eb3b-4fd2-bb89-de1161e905cc.png](https://github.com/fast4x/RiMusic/assets/71184627/c2d0b34c-ce40-49c4-9c73-39b5dd201c8c)

**Comment by dAtA-TRoN** [comment]
I just thought of something else. Now that we'll have more space in the future, could the tracks also be numbered?

**Comment by dAtA-TRoN** [comment]
I've had another idea. It would be helpful to number the songs in a playlist for easier navigation through longer lists. To avoid cluttering the layout, we could display these numbers as small overlays within each thumbnails. My mockup is just to demonstrate the concept. I understand that you might need to add a background to the numbers for better readability.

![eff21140-de4c-4ff5-86d0-55ec61e1fe3f.png](https://github.com/fast4x/RiMusic/assets/71184627/9346cf47-fa83-4973-9e1f-ebe71620f03f)

**Comment by sayyid5416** [comment]
I think this _**empty space in sidebar**_ could easily be solved by having an option to switch to bottom navigation bar.

**Comment by dAtA-TRoN** [comment]
> I think this _**empty space in sidebar**_ could easily be solved by having an option to switch to bottom navigation bar.

And what about those poor souls who prefer navigating with a sidebar? Should they just live with the empty space or what!? Quite heartless the way you think
🫵🏻😐...

**Comment by sayyid5416** [comment]
> > I think this _**empty space in sidebar**_ could easily be solved by having an option to switch to bottom navigation bar.
> 
> And what about those poor souls who prefer navigating with a sidebar? Should they just live with the empty space or what!? Quite heartless the way you think 🫵🏻😐...

😂😂 Well, by removing the sidebar you are already making it look like top navigation bar
![image](https://github.com/fast4x/RiMusic/assets/78584556/4e6ed79c-a5d6-42e5-871d-0310b7e95e36)

**Comment by dAtA-TRoN** [comment]
> 😂😂 Well, by removing the sidebar you are already making it look like top navigation bar

In the current implementation of the playlist view, there's no sidebar anyway, just an unnecessary symbol that does literally nothing but take up space. You can check for yourself. So, the current formatting doesn't make any sense, regardless of the navigation style 😛.

**Comment by sayyid5416** [comment]
> > 😂😂 Well, by removing the sidebar you are already making it look like top navigation bar
> 
> In the current implementation of the playlist view, there's no sidebar anyway, just an unnecessary symbol that does literally nothing but take up space. You can check for yourself. So, the formatting doesn't make any sense, regardless of the navigation style 😛.

I disagree, because it's currently consistent with the rest of the app. If this is implemented, it would become inconsistent just like search page and album page.

**Comment by dAtA-TRoN** [comment]
> I disagree, because it's currently consistent with the rest of the app.

![proxy-image.gif](https://github.com/fast4x/RiMusic/assets/71184627/a85cd107-ecc7-45f3-916b-74c2b30c8c93)

I consider prioritizing consistency over usability to be nonsense. Moreover, this change actually enhances consistency, as more pages now adopt a full-screen design, as you described. Space should be maximized wherever possible, especially when promoting accessibility. In this context, functionality takes precedence over design. Design should always follow functionality, not the other way around. If it doesn't, then the design is simply poor.

**Comment by sayyid5416** [comment]
> > I disagree, because it's currently consistent with the rest of the app.
> 
> I consider prioritizing consistency over usability to be nonsense. Moreover, this change actually enhances consistency, as more pages now adopt a full-screen design, as you described. Space should be maximized wherever possible, especially when promoting accessibility. In this context, functionality takes precedence over design. Design should always follow functionality, not the other way around. If it doesn't, then the design is simply poor.

With all that paragraph, you are describing a bottom/top navigation bar 😏 i.e Minimal space wasting, Maximum space utilized.

**Comment by dAtA-TRoN** [comment]
> With all that paragraph, you are describing a bottom/top navigation bar 😏 i.e Minimal space wasting, Maximum space utilized.

Of course, that's a valid point. However, it doesn't change the fact that sidebar navigation is indeed present. Combining sidebar navigation with top or bottom navigation could help me understand your concern better. Yet, the app has always been somewhat inconsistent in this regard. Its design has never solely focused on using the sidebar. Both vertical and horizontal controls have always been part of the app. So, if there's an "issue," if you will, it's been around for quite some time. Personally, I see sidebar navigation more as a nice addition, a Gimmick or an aesthetic feature (eye candy) compared to similar apps. But it's evident from the start, that this type of navigation may not necessarily offer the best user experience.

That's why I'm not against optional top or bottom navigation at all. On the contrary, I would welcome it since I myself prefer the classic navigation style. But until then, I'm more than willing to contribute to making the current usability of the app as pleasant as possible.

**Comment by sayyid5416** [comment]
One thing I've learnt over time is that if you keep ignoring consistency in any app design, it becomes an uncontrolled mess overtime.

For example, back button is present in top left corner throughout the app, but in new _**search**_ and _**album**_ page it's in the top-right corner, and that too not in perfect corner. This degrades the user experience for a person who prefers sidebar.

This is exactly the reason that top and side navigation bar should not be merged. Users can choose whichever they like.

Inconsistency always leads to degraded user experience over time if not controlled sooner.

**Comment by dAtA-TRoN** [comment]
What you're describing, I can fully endorse. However, not wanting to utilize the given space just to maintain a sidebar consisting of empty space, I consider bold.

As I said, from a design perspective, in my opinion, the app has long since gone down the drain. And that wasn't Daniel's fault, who merely forked it. The mistakes were made much earlier.

**Comment by dAtA-TRoN** [comment]
What you're describing, I can fully endorse. However, not wanting to utilize the given space just to maintain a sidebar consisting of empty space, I consider bold.

As I said, from a design perspective, in my opinion, the app has long since gone down the drain. And that wasn't Daniel's fault, who merely forked it. The mistakes were made much earlier.

**Comment by sayyid5416** [comment]
> As I said, from a design perspective, in my opinion, the app has long since gone down the drain. 

Maybe you are correct, or maybe not - I don't know that, but I know that app is consistent for the most parts. There are some inconsistencies _(many of which are pointed out time to time in issues)_, I think they could be resolved, but we should try to be considerate to not introduce any more inconsistencies.

**Comment by dAtA-TRoN** [comment]
> Maybe you are correct, or maybe not - I don't know that, but I know that app is consistent for the most parts.

I think the truth lies as always in between. Maybe you should create a report about the back buttons you mentioned, so they can be placed back on the correct side.

**Comment by dAtA-TRoN** [comment]
![Screenshot_2024-04-06-12-38-26-47_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/5fc1fba3-a32e-4482-af3e-2e41c9249ca8)

Please remove this and make it like the one shown above in my mockup.

**Comment by sayyid5416** [comment]
> ![IMG_20240406_123954.jpg](https://private-user-images.githubusercontent.com/71184627/320199081-173f1308-6590-4ea1-b484-5d5f96adbe0a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MDA1NjEsIm5iZiI6MTcxMjQwMDI2MSwicGF0aCI6Ii83MTE4NDYyNy8zMjAxOTkwODEtMTczZjEzMDgtNjU5MC00ZWExLWI0ODQtNWQ1Zjk2YWRiZTBhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDEwNDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NTNkY2Y5NzU5ZDdmNzRiODZiNWI1N2M0ZDhhZmY1NWFhZThmZmM3MmZmMDZiOTk1YWRmOWQzMDNjNWI5MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.esM-bSSfeyBGvAf3pN60i7utcZDe3QDxbJpTKioYS_k)
> 
> Please remove this and make it like the one shown above in my mockup.

Yeah removing it is good, but not like above mockup. Check #1389

**Comment by dAtA-TRoN** [comment]
> Yeah removing it is good, but not like above mockup. Check #1389

I'm fine with that.

**Comment by sayyid5416** [comment]
> it needs to be implemented universally.

I'm a fan of consistency, so it's a `+1` from me
