### ISSUE TITLE
Add suggest song button to playlist 

### ISSUE THREAD

**Issue by ADIT011007** [fast4x/RiMusic#1306]
### Description

There is a small button on top of playlist to add suggest songs to playlist as a shuffle song. There should be a button there on each suggested song that will quickly add that song to that same playlist 
![IMG_20240330_122151](https://github.com/fast4x/RiMusic/assets/77261726/f52d96fc-972c-4206-9e9b-eef291f06384)

### Suggested Solution

There should be a button that will add that suggested song to playlist , can be placed on end of that song name ( + ) like a plus icon

**Comment by dAtA-TRoN** [comment]
Can someone explain to me what exactly that means!?

**Comment by ADIT011007** [comment]
> Can someone explain to me what exactly that means!?

So basically what i mean is that when we switch on smart shuffle in the playlist. The songs only get played none of the suggestions get added in playlist until we open player and add it manually. Insted u can add a button besides the suggested song taht will one click add the song to the same playlist

**Comment by dAtA-TRoN** [comment]
Thanks, I guess I get it now 😅.

**Comment by ADIT011007** [comment]
> Thanks, I guess I get it now 😅.

Just let know if u want any more explanation. Sorry for rough explanation. I will try to help . Btw are u in dev team ?

**Comment by dAtA-TRoN** [comment]
> Just let know if u want any more explanation. Sorry for rough explanation. 

It's not about you, it's just that I haven't delved into the 'suggest a song' feature thoroughly yet. So, I don't have a precise idea of how it works. I was just curious about what you're describing here.

> Btw are u in dev team ?

No, I'm just a braggart.

**Comment by ADIT011007** [comment]
> > Just let know if u want any more explanation. Sorry for rough explanation.
> 
> It's not about you, it's just that I haven't delved into the 'suggest a song' feature thoroughly yet. So, I don't have a precise idea of how it works. I was just curious about what you're describing here.
> 
> > Btw are u in dev team ?
> 
> I'm just a pompous figurehead around here, nothing more!
> 
> ![proxy-image.gif](https://private-user-images.githubusercontent.com/71184627/318184766-c21f1c70-5f92-447a-b87d-7e27e4f729c8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MjQ3OTIsIm5iZiI6MTcxMTgyNDQ5MiwicGF0aCI6Ii83MTE4NDYyNy8zMTgxODQ3NjYtYzIxZjFjNzAtNWY5Mi00NDdhLWI4N2QtN2UyN2U0ZjcyOWM4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE4NDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMTE1NjEwMDA2MzlmYTc0YWE4YWNmNDRlZWFmNWZhYjRhOTdkODBhMTMxZjRiZWM5NzUwYzFlMTM1NGFhZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1mkmVy-s6WuLvg6TPDbnkKc5Fp1PpApVlkd2EYktl4) [ ![proxy-image.gif](https://private-user-images.githubusercontent.com/71184627/318184766-c21f1c70-5f92-447a-b87d-7e27e4f729c8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MjQ3OTIsIm5iZiI6MTcxMTgyNDQ5MiwicGF0aCI6Ii83MTE4NDYyNy8zMTgxODQ3NjYtYzIxZjFjNzAtNWY5Mi00NDdhLWI4N2QtN2UyN2U0ZjcyOWM4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE4NDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMTE1NjEwMDA2MzlmYTc0YWE4YWNmNDRlZWFmNWZhYjRhOTdkODBhMTMxZjRiZWM5NzUwYzFlMTM1NGFhZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1mkmVy-s6WuLvg6TPDbnkKc5Fp1PpApVlkd2EYktl4) ](https://private-user-images.githubusercontent.com/71184627/318184766-c21f1c70-5f92-447a-b87d-7e27e4f729c8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MjQ3OTIsIm5iZiI6MTcxMTgyNDQ5MiwicGF0aCI6Ii83MTE4NDYyNy8zMTgxODQ3NjYtYzIxZjFjNzAtNWY5Mi00NDdhLWI4N2QtN2UyN2U0ZjcyOWM4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE4NDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMTE1NjEwMDA2MzlmYTc0YWE4YWNmNDRlZWFmNWZhYjRhOTdkODBhMTMxZjRiZWM5NzUwYzFlMTM1NGFhZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1mkmVy-s6WuLvg6TPDbnkKc5Fp1PpApVlkd2EYktl4) [ ](https://private-user-images.githubusercontent.com/71184627/318184766-c21f1c70-5f92-447a-b87d-7e27e4f729c8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MjQ3OTIsIm5iZiI6MTcxMTgyNDQ5MiwicGF0aCI6Ii83MTE4NDYyNy8zMTgxODQ3NjYtYzIxZjFjNzAtNWY5Mi00NDdhLWI4N2QtN2UyN2U0ZjcyOWM4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE4NDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMTE1NjEwMDA2MzlmYTc0YWE4YWNmNDRlZWFmNWZhYjRhOTdkODBhMTMxZjRiZWM5NzUwYzFlMTM1NGFhZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1mkmVy-s6WuLvg6TPDbnkKc5Fp1PpApVlkd2EYktl4)
> 
> Edit: There is no "team". It's just fast4x. He does all the dirty work. Oh, and of course, ikanakova. He's the graphics dude here.

Ooo I see , sort sort
