### ISSUE TITLE
"Close background player" should only close "background player"

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1310]
### Description

Just simply what is mentioned in the title.

### Suggested Solution

I've seen even when I close the app the player is still in the notification panel:
![1711792727567.jpg](https://github.com/fast4x/RiMusic/assets/85461823/2e4d4147-d21e-440c-9df2-5db51975f460)

I thought I had "Close background player" turned on. But then I checked in the settings and it was turned off. (Probably because of last update it got turned off by default…this irritates me…I really hope in future updating to new version won't affect settings preferences.)

Then I turned on that option. But then when I closed and reopened the app the queue was dismissed. That shouldn't happen. Only background player should be dismissed by that action not queue.

### Additional Context

I have "persistent queue" turned on and other things I need to do (that are necessary to run the app without interruptions) those are done as well. 
![Screenshot_20240330-161557.jpg](https://github.com/fast4x/RiMusic/assets/85461823/ac4b656a-dc6e-48fd-afe7-6fa5e6bf06d8)

I think it's "close background player" options that is causing this problem. But sorry if I'm wrong.

**Comment by fast4x** [comment]
The two options do two very different things. The first one allows you to close the player if you close the app. The second one loads the playback queue into memory. The settings do not reset themselves unless there is a permissions issue.

**Comment by fast4x** [comment]
I'll check it
