### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1311]
The issue of Hindi and Indian language albums for some reason not opening has been known for a long a long time.
However, in another fork of ViMusic called ViTune, Indian language albums open with no problems.
I'm just curious as to why this is so, and if it can be fixed in RiMusic going forward.

Link to video demonstrating this: https://imgur.com/a/Knc8eG5

**Comment by privacyfreak84** [comment]
An issue about this has been made in the ViTune github. It also contains a fix, as far as I can see: https://github.com/25huizengek1/ViTune/issues/28

**Comment by fast4x** [comment]
Thanks i'll check it

**Comment by privacyfreak84** [comment]
> Thanks i'll check it
Thanks!

**Comment by Nikks84** [comment]
> Thanks i'll check it

Yes please

**Comment by fast4x** [comment]
Fixed, available from version 0.6.29
Thanks

**Comment by privacyfreak84** [comment]
Thanks! Closing

**Comment by Nikks84** [comment]
Thanx 👍🏻 its working fine 0.6.28.1
