### ISSUE TITLE
Add lrclib as a lyrics source

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1313]
[LRClib](https://lrclib.net/) had both synced and unsynced lyrics for a plethora of songs. Another fork of ViMusic called ViTune has this available as an option and it really is very useful.
It would be nice to have this as a source as it would save us lots of time hunting for synced lyrics

Video showcasing this in action: https://imgur.com/a/AunjhyH

**Comment by fast4x** [comment]
Implemented, added new provider lyrics LrcLib.net.
Available from version 0.6.28.1

**Comment by privacyfreak84** [comment]
Thank you!
