### ISSUE TITLE
Export downloaded songs to device storage/sd card 

### ISSUE THREAD

**Issue by Chickenshrimps** [fast4x/RiMusic#1314]
### Description

Love

### Suggested Solution

Export downloaded songs like in innertune app 

### Alternatives

None

### Additional Context

None

**Comment by fast4x** [comment]
RiMusic is not a music downloader but player with download feature for offline play.

**Comment by dAtA-TRoN** [comment]
What you describe is illegal.

https://github.com/fast4x/RiMusic/assets/71184627/e68ac700-d908-4e05-8f5b-7782c9afdbd5
