### ISSUE TITLE
Because the limit is Max 500 song in queue both in songs and favorites when pressing the shuffle button it also limit to only the first 500 songs 

### ISSUE THREAD

**Issue by ThaMasEagle** [fast4x/RiMusic#1316]
### Steps to reproduce the bug

1. Go to app
2. Go to songs or favourites
3. press the shuffle button-favourites

### Expected behavior

To reiterate, the expected behaviour is for the shuffle function to draw randomly from the entire collection of 4000 songs rather than primarily focusing on the initial first 500.

### Actual behavior

When utilizing the shuffle button, the expectation is for the system to randomly select songs from a pool of approximately 500. However, it seems that the shuffle function predominantly chooses from the initial/first 500 songs out of a total of 4000 available. This behaviour occurs consistently, resulting in a limited range of shuffled songs. i notice it even from the previous versions 

### RiMusic version

0.6.28

### Android version

Android 12

**Comment by fast4x** [comment]
You can set your size from settings. Default limit 500 is related to devices with small memory. By settings you can increase...

**Comment by ThaMasEagle** [comment]
no like when you press the shuffle button is must get 500 songs randomly from my list and not take the first 500 songs from my list and shuffle those ones

**Comment by fast4x** [comment]
I'll check it

**Comment by fast4x** [comment]
Improved, avaialble from version 0.6.29

**Comment by fast4x** [comment]
Availble from version 0.6.28.1, now...
