### ISSUE TITLE
Album's won't load

### ISSUE THREAD

**Issue by Juggalage** [fast4x/RiMusic#1317]
### Steps to reproduce the bug

Open any album or single

### Expected behavior

Album should open with no problem

### Actual behavior

Album does not load songs

![Screenshot_20240330-153029](https://github.com/fast4x/RiMusic/assets/32726906/6338f024-ffed-4b6b-b71b-8a1218e5e340)

![Screenshot_20240330-152742](https://github.com/fast4x/RiMusic/assets/32726906/361fbfc9-5a5e-4695-969c-31b25388c7c1)

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/32726906/27826f0d-6ea3-4080-bc7f-b24452b31a03

### RiMusic version

v0.6.28

### Android version

Android 14

### Additional information

Already downloaded the custom version and it fixed some albums but not others.

**Comment by fast4x** [comment]
For me it work perfectly with custom version
![Screenshot_2024-03-30-21-40-24-243_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/8fdc3ee5-920b-4ae8-a8d5-6ef8396c75ab)

![Screenshot_2024-03-30-21-39-45-636_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/c7a9fc07-f088-4337-a358-e04fffccca41)
