### ISSUE TITLE
New custom version some albums still ain't loading

### ISSUE THREAD

**Issue by NewManEr** [fast4x/RiMusic#1319]
### Steps to reproduce the bug

Hi, thanks a bunch for your app! Some albums won't load even on custom 0.6.28 version. Actually I managed to add it to favorites with all songs the first time. But when I clicked Load All Songs, all songs disappeared and just app shows me Null Songs. I've tried stop app and clear cache, remove and add again album. But app still shows Null Songs. On another device I have app 0.6.25 and everything's okey. Even in NewPipe on both devices everything's okey. So geoblock ain't problem here. Album link for example: https://music.youtube.com/playlist?list=OLAK5uy_mvVZFvYfflemv-7vCR3EIcRtMW7Ba5Rtw

### Expected behavior

It should work.

### Actual behavior

Nothing's happen. Null Songs.

### RiMusic version

0.6.28 Custom Version

### Android version

Android 11

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/7f74bc56-8c60-4ea8-9411-4779f1bf29fb

I'm sorry but it work for me

**Comment by NewManEr** [comment]
Okey, I understand. My screenrecording:
https://github.com/fast4x/RiMusic/assets/165528607/2a11555c-0ab8-46bc-8cdc-6fc14c8a3e26

Should I close the issue?

**Comment by fast4x** [comment]
No, I'll check it

**Comment by dainvincible1** [comment]
> Okey, I understand. My screenrecording: https://github.com/fast4x/RiMusic/assets/165528607/2a11555c-0ab8-46bc-8cdc-6fc14c8a3e26
> 
> Should I close the issue?

facing same issue

**Comment by 2StrokeDiesel** [comment]
Can second this, albums not working for me either

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/eda90fb4-ddb6-4c31-bff3-c28a1fc93142

I'm sorry but it work for me... i don't understand your bug

**Comment by 2StrokeDiesel** [comment]
Is it possible that a region is being blocked by YouTube, for example like a portion of the u.s?

**Comment by fast4x** [comment]
Yes

**Comment by dainvincible1** [comment]
i went back to the pervious version (v0.6.27), the albums are loading in that version but not in the latest version.

**Comment by fast4x** [comment]
Download new version 0.6.28.1

**Comment by 2StrokeDiesel** [comment]
> Download new version 0.6.28.1

This fixed it for me, all albums loading now.

**Comment by fast4x** [comment]
Thanks for feedback

**Comment by dAtA-TRoN** [comment]
It still happens to me:

https://github.com/fast4x/RiMusic/assets/71184627/ac75fb96-6127-4035-afee-5b324cb5f6f4

There was a way to fix these issues before the new "alternative Versions" button was introduced. You could simply tap on the old "alternative Versions" button and then, on the next page where it showed there was no other version, tap on the button for the individual tracks. That actually helped in loading the album normally again, even after restarting the app. Maybe this anecdote will help you in some way.

**Comment by dAtA-TRoN** [comment]
> It work now, available from version 0.6.31

Thank you. I hope that's true.
