### ISSUE TITLE
Second Wavy bar Option (Optional)

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#132]
### Description

With the release of One UI 6 on my phone I started to like they're wavy seekbar in the player.

![SmartSelect_20231121_064605](https://github.com/fast4x/RiMusic/assets/104271365/ad4e26d5-759b-4557-aef0-a6fdb91fa33f)

### Suggested Solution

Make the wavy on/off option into a multiple choise:
- Default (The static one)
- Android Wavy
- Samsung Wavy

### Alternatives

Instead of making yourself i dont know if its possible to have an api or a thing that takes the effect from the os if its present

### Additional Context

This is optional i know that im asking maybe too mutch

**Comment by fast4x** [comment]
Added selection timeline type on player settings.
Available from version 0.6.11
System timeline not recognized for your device One, sorry.
