### ISSUE TITLE
[Feature]: search songs using album's name

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1321]
### Description

I can easily search a song by its title or artist name in playlists. Wish it was possible to list all the songs from an album by writing album's name in the search bar

### Suggested Solution

Please make it possible to list out all the songs in the playlist when I write the name of the album in the search bar

**Comment by Nikks84** [comment]
Similar #941 
Everyone wants it, hope it is possible soon.....

**Comment by aneesh1122** [comment]
> Similar #941 Everyone wants it, hope it is possible soon.....

I was talking about searching within a playlist but your request is also good and useful.
