### ISSUE TITLE
widget

### ISSUE THREAD

**Issue by Stuid01** [fast4x/RiMusic#1323]
### Description

Maybe you could add a homescreen widget like the ones Spotify, Deezer and other platforms use

### Suggested Solution

Maybe you could add a homescreen widget like the ones Spotify, Deezer and other platforms use

**Comment by Stuid01** [comment]
Sorry, I didn't see that.

**Comment by KrisTamang** [comment]
It will be pretty sick if Rimusic got widgets..!

**Comment by fast4x** [comment]
Implemented available from version 0.6.51
