### ISSUE TITLE
[Feature]: Music Videos in Rimusic?

### ISSUE THREAD

**Issue by farzana840** [fast4x/RiMusic#1326]
### Description

I know this might sound weird but some please like me prefer to watch music videos along with listening to the music. YouTube music has this feature too. Inclusion of this  will make rimusic the one complete package. This hasn't has to be now. It can be done in phases. Good work tho

### Suggested Solution

Slowly rolling out video feature

**Comment by fast4x** [comment]
Hi, for the moment isn't planned.
Thanks.

**Comment by XxSlaDoidoxX** [comment]
I miss the seamless song/video switch from YT Music a bit, such a cool feature specially for podcasts. Nothing too incredible, but I hope it gets added in the future. Not a simple feature to develop though.

**Comment by fast4x** [comment]
Podcast work in progress...
