### ISSUE TITLE
Bug on dynamic theme 

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#1328]
### Steps to reproduce the bug

1. Activate dynamic theme with pitch black 
2. Play a song
3. Remove it by swipe down(or other ways possible)

### Expected behavior

Should still keep the pitch black background 

### Actual behavior

It switches to gray background 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/89296867/75912ac9-cb55-435d-bec6-36ce23089d40

### RiMusic version

0.6.28

### Android version

Android 14

**Comment by VINULA2007** [comment]
![Screenshot_2024-04-03-14-19-22-545_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89296867/31673fc5-ed2d-4587-b9ef-b232b88ad160)
Bugged out again
@fast4x

**Comment by fast4x** [comment]
Mode theme isn't totally applied in settings...

**Comment by VINULA2007** [comment]
> Mode theme isn't totally applied in settings...

Bug or have I messed up?

**Comment by fast4x** [comment]
Not bug...

**Comment by VINULA2007** [comment]
> > Mode theme isn't totally applied in settings...
> 
> Bug or have I messed up?

So pitch black is not pitch black?
And is pitch black = gray? 


https://github.com/fast4x/RiMusic/assets/89296867/f3db9fca-21d1-48fa-a14c-5db594ab5600

So this is normal?

**Comment by VINULA2007** [comment]
![Screenshot_2024-04-04-01-53-11-423_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89296867/21716f5a-44e5-434b-9761-3398a9ef46e3)
Btw what is this?

**Comment by fast4x** [comment]
> ![Screenshot_2024-04-04-01-53-11-423_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89296867/21716f5a-44e5-434b-9761-3398a9ef46e3)
> Btw what is this? 

Filter out on device songs

**Comment by VINULA2007** [comment]
Nope it's not fixed 


https://github.com/fast4x/RiMusic/assets/89296867/f474c826-0755-4482-bf67-34524c567ab9



Look at the background 
It alternates between gray and black

**Comment by fast4x** [comment]
So occur when mini player go out... ok try to investigate
