### ISSUE TITLE
Can u add support for addings songs from other music apps like Spotify gaana saavn

### ISSUE THREAD

**Issue by Mrick343** [fast4x/RiMusic#1329]
### Description

I previously used to listen music on blackhole app by Sangwan.. That app had a feature to search songs from other apps like YouTube or Spotify or gaana. Even it haa a feature to import playlist from those apps like YouTube Spotify..It will be very good if u can add those features is possible 

### Suggested Solution

I don't know about these things how to implement....I just suggested that if it's possible

**Comment by NightFly88** [comment]
> ### Description
> I previously used to listen music on blackhole app by Sangwan.. That app had a feature to search songs from other apps like YouTube or Spotify or gaana. Even it haa a feature to import playlist from those apps like YouTube Spotify..It will be very good if u can add those features is possible
> 
> ### Suggested Solution
> I don't know about these things how to implement....I just suggested that if it's possible
> 
> ### Alternatives
> _No response_
> 
> ### Additional Context
> _No response_

You mean this option at blackhole app seems like a great addition,
![Uploading Screenshot_20240401_162734.jpg…]()

**Comment by Mrick343** [comment]
> You mean this option at blackhole app seems like a great addition, ![Screenshot_20240401_162734](https://private-user-images.githubusercontent.com/163666747/318463618-cf036a81-93a3-45c3-b019-c74044c300a9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTYyMzYsIm5iZiI6MTcxMTk5NTkzNiwicGF0aCI6Ii8xNjM2NjY3NDcvMzE4NDYzNjE4LWNmMDM2YTgxLTkzYTMtNDVjMy1iMDE5LWM3NDA0NGMzMDBhOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxODI1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDFjNTJjMDI2NzZlNzgxNmVlMDI4MDFhZWI1M2FjMTM5MDM5YWU2YWVmMmQzODAxODA0MTc1NzQyYmUyODcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7R16x5LSY-eHhXAu0-FmXKlXNvp0LolMF8Z50fbAPvA)

yes

**Comment by fast4x** [comment]
Isn't possibile
