### ISSUE TITLE
Spelling mistake in Player Settings

### ISSUE THREAD

**Issue by alexoona** [fast4x/RiMusic#133]
### Steps to reproduce the bug

1. Open RiMusic
2. Open Settings
3. Open Player Settings
4. Wave timeline description contains spelling mistake.

### Expected behavior

It should show Wave Timeline description as "Enable the wavy timeline".

### Actual behavior

Wave timeline description is wrongly displayed as "Enabke the wavy timeline".

### Screenshots/Screen recordings

![Screenshot_2023-11-21-12-12-59-63](https://github.com/fast4x/RiMusic/assets/74307443/524f25d0-4a6a-46e8-aa7c-0cf6fa7aeee1)
![Screenshot_2023-11-21-12-34-44-40](https://github.com/fast4x/RiMusic/assets/74307443/4f467bab-070c-40b2-a3d4-fb226e7267b6)

### RiMusic version

0.6.9

### Android version

Android 10

**Comment by ikanakova** [comment]
@fast4x It has already fixed.

**Comment by alexoona** [comment]
Thank you.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.10
