### ISSUE TITLE
[BUG]: Search tab home

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#1332]
### Steps to reproduce the bug

When u enable search tab in home tab, it dispear from home screen, It’s not normal, it’s not supposed to be the other way.?

### Expected behavior

Appear in home screen when enabled 

### Actual behavior

It does the opposite 

### Screenshots/Screen recordings

![Screenshot_2024-04-01-12-29-21-295-edit_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/5c2a8e4f-27a4-45d1-8c5d-6de050345f5b)
![Screenshot_2024-04-01-12-29-34-705-edit_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/34bdd140-9964-4476-9bd5-89f8fd77ebbe)
![Screenshot_2024-04-01-12-28-17-511_com android chrome](https://github.com/fast4x/RiMusic/assets/63956787/aaadd835-fceb-4ff4-8cf3-8ac348fcabec)

### RiMusic version

0.6.28.1

### Android version

A12 MIUI 14

**Comment by fast4x** [comment]
if enable it search are moved to bar

**Comment by NEVARLeVrai** [comment]
> if enable it search are moved to bar

But "show search tab in home" mean home tab so why when enabled it dispear it's don't make sens ?

**Comment by NEVARLeVrai** [comment]
> Because is always in home but disappear from top and it move to navigation bar.

Yeah maybe translation is not the best choice, I will change it for something more understandable

**Comment by NEVARLeVrai** [comment]
> Because is always in home but disappear from top and it move to navigation bar.

Yeah maybe translation is not the best choice, I will change it for something more understandable
