### ISSUE TITLE
[Hight Importance]: Random songs when listening

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1333]
### Steps to reproduce the bug

1. Go on Liked songs
2. Play a song with arange filters
3. Random song plays instead of what you pressed

### Expected behavior

Play the song i presed

### Actual behavior

Plays a random song

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/104271365/49dea5f1-beee-4790-95d8-cd47ac27af12

### RiMusic version

0.6.28.1

### Android version

Android 14

**Comment by dainvincible1** [comment]
this is also happening in the songs from "SONGS" section 


https://github.com/fast4x/RiMusic/assets/127825700/c6e14fff-65da-450a-963f-d1e82ddb1745

**Comment by fast4x** [comment]
I'll check it soon, thanks

**Comment by fast4x** [comment]
I've found the bug in Home Songs but not in preferites...

https://github.com/fast4x/RiMusic/assets/1484476/3c91c7c6-0790-4bdf-98bb-5699edefed36

**Comment by fast4x** [comment]
Fixed in home songs and preferites, available now in custom version and from version 0.6.29

**Comment by OrangeZXZ** [comment]
> Fixed in home songs and preferites, available now in custom version and from version 0.6.29
> https://github.com/fast4x/RiMusic/tree/master/customVersion

It works
