### ISSUE TITLE
Songs are missing from playlist when opening it in RiMusic

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1334]
### Steps to reproduce the bug

1) go to search
2) choose 'go to link'
3) paste my playlist's link
4) playlist opens but songs are missing. There are 312 songs but only 198 songs are showing up

### Expected behavior

all the 312 songs in my playlist should appear in the list

### Actual behavior

only 198 songs are in the list

### RiMusic version

0.6.28.1

### Android version

Android 13

**Comment by fast4x** [comment]
Playlist link?

**Comment by aneesh1122** [comment]
https://www.youtube.com/playlist?list=PLAnme0ot1hod_g3wBzKdAoKhLhmVqm3Na

I've added some more songs and now there are 342 out of which only 100 songs appears.

**Comment by aneesh1122** [comment]
> Playlist link?

hey there, were you able to solve this problem?

**Comment by fast4x** [comment]
Fixed, available from version 0.6.30
