### ISSUE TITLE
Suporte ao login do YouTube 

### ISSUE THREAD

**Issue by MarcosV1998** [fast4x/RiMusic#1335]
### Description

Por favor poderiam adicionar o suporte a login do YouTube para poder ouvir as playlists e as músicas com curtidas do mesmo, grato pela atenção e parabéns aos envolvidos no desenvolvimento desse app maravilhoso ❤️

### Suggested Solution

Login no YouTube disponível

**Comment by fast4x** [comment]
Thanks a lot, YouTube login isn't planned to add in app. I'm sorry.

**Comment by ikanakova** [comment]
> Piped please

#278
