### ISSUE TITLE
Album art keep erasing 

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1336]
### Steps to reproduce the bug

Whenever i go offline and player songs.. it doesn't show album art..!
Only the songs that i played before i go offline..!
If possible please let it download album art when we download songs..!
And saves just like downloaded music not cached one..
![Screenshot_20240401-203015_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/69433c8d-6f44-46f0-b9e4-019a992d47f1)

### Expected behavior

Able to see album are eventhou i go offlinw

### Actual behavior

Album art keep erasing 

### RiMusic version

0.6.28.1

### Android version

13

**Comment by KrisTamang** [comment]
I have already reported this issue but its not fixed..!

**Comment by fast4x** [comment]
Album cache must be increase by settings. When offline and inages are not cached isn't available...

**Comment by KrisTamang** [comment]
> Album images cache must be increase by settings. When offline and inages are not cached isn't available...

I set it to 2gb..!
But its keep erasing
