### ISSUE TITLE
Audio Visualizer keeps freezing

### ISSUE THREAD

**Issue by AquamarineDreams** [fast4x/RiMusic#1340]
### Steps to reproduce the bug

Enable and open audio visualizer, in any mode. 

### Expected behavior

Visualizer working properly

### Actual behavior

Visualizer freezes after a few seconds

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/140275860/5dc86593-4c03-49fb-ac80-9fccb5231d1b

Bug reproduction

### RiMusic version

0.6.28.1

### Android version

Android 14

**Comment by AquamarineDreams** [comment]
I had to cut the video, but on the last second when visualizer reaches peak it froze.

**Comment by AquamarineDreams** [comment]
I had to cut the video, but on the last second when visualizer reaches peak it froze

**Comment by fast4x** [comment]
Yes it's a know bug

**Comment by fast4x** [comment]
Improved visualizer

**Comment by AquamarineDreams** [comment]
> Improved visualizer

![happy-cat-happy-happy-cat](https://github.com/fast4x/RiMusic/assets/140275860/5940ac0f-bb9b-4f87-aa7e-4120a67ced6f)
