### ISSUE TITLE
Source error

### ISSUE THREAD

**Issue by Michael-Willy** [fast4x/RiMusic#1342]
### Steps to reproduce the bug

1 - Reproduza a música
2 - Saia do aplicativo por algum tempo

### Expected behavior

Música continuar tocando

### Actual behavior

A música para e da um erro: "Source error"

### Screenshots/Screen recordings

![Screenshot_20240401-220419](https://github.com/fast4x/RiMusic/assets/153049118/0ac143ef-f288-40b7-8275-f5077c0f5bf1)

### Logs

.

### RiMusic version

Mais recente, não sei qual estou utilizando no momento

### Android version

Android 9 pie

### Additional information

.

**Comment by fast4x** [comment]
Enable invincible service in settings

**Comment by Michael-Willy** [comment]
Já ativei, ainda continua com o mesmo erro. E as vezes quando dou pause na
música(em segundo plano) o aplicativo fecha.

Em ter, 2 de abr de 2024 08:29, Rino Russo ***@***.***>
escreveu:

**Comment by fast4x** [comment]
it's a permission issue in your device.
