### ISSUE TITLE
Enqueue not working 

### ISSUE THREAD

**Issue by ADIT011007** [fast4x/RiMusic#1344]
### Steps to reproduce the bug

 1 : Play a song 
 2 : Hold any other random song from playlist or recommendations 
 3 : press enqueue 
4 : wait for that song to end or press next song button 

### Expected behavior

The expected behevior should be : the song we added to queue should play , but it doesn't play 

### Actual behavior

The actual behevior should be : the song we added to queue should play next  , but it doesn't play 

### RiMusic version

0.6.28.1

### Android version

Android 11

**Comment by fast4x** [comment]
Enqueue add songs to last, you must to use Play next ... not enqueue...

**Comment by ADIT011007** [comment]
But then how can I queue many songs ?

**Comment by fast4x** [comment]
So, you can use Select/Deselect many songs and after selected, click on enqueue.

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/5512e1bc-b30f-4d69-b065-becfe9f7b032
