### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by Lukilei** [fast4x/RiMusic#1345]
### Steps to reproduce the bug

Open app.

### Expected behavior

Should launch normally.

### Actual behavior

Uppon launch the app shows the opening screen and immediately after it shuts down. This has occured after an update via f-droid from v0.6.24 to v0.6.27, but updating to v0.6.28.1 also didn't change anything. I am using Lineage OS on an Unihertz Atom XL with Android 11.

### RiMusic version

0.6.27-0.6.28

### Android version

11

### Additional information

I would just downgrade, but that would mean that I have to uninstall the app right? If there is a way to retrieve app data without being able to open the app that would also be helpful.

**Comment by fast4x** [comment]
I need a log to understand

**Comment by fast4x** [comment]
You can just backup a database from settings, install another version and restore backup from database settings

**Comment by Lukilei** [comment]
There is no error page weirdly, it just shuts down. And I can't enter settings either because it shuts down immediatly.

**Comment by Lukilei** [comment]
I want to add that I can still get the notification widget, so it just seems to be the interface thats broken. Also thanks for your quick response!

**Comment by fast4x** [comment]
I can’t produce your problem I’m sorry

**Comment by Lukilei** [comment]
I understand, I think i'll try to downgrade it to v0.6.24 via adb and then go on from there.

**Comment by fast4x** [comment]
try to understand where it goes wrong

**Comment by Lukilei** [comment]
Ok, I have now created a backup and uninstalled the app, then installed the newest version and it's working fine. So the problem seems to have occured while updating. But for me this is solved. 

PS.: I just wanted to thank you for all the work you guys put into this project! Seeing this get updated so regularly is really crazy to me, whilst it also being free and foss. You guys are great!

**Comment by fast4x** [comment]
Thanks
