### ISSUE TITLE
Always shuffle

### ISSUE THREAD

**Issue by notaiva** [fast4x/RiMusic#1346]
### Steps to reproduce the bug

I dont know

### Expected behavior

Play the selected song

### Actual behavior

Shuffle Musics

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/68603279/e0ff3e35-3868-4eb1-8d02-5d1418380d87

### RiMusic version

0.6.28.1

### Android version

Android 14

### Additional information

It didn't happen in the previous update

**Comment by fast4x** [comment]
Fixed in home songs and preferites, available now in custom version and from version 0.6.29
https://github.com/fast4x/RiMusic/tree/master/customVersion
