### ISSUE TITLE
Statistics are displayed incorrectly

### ISSUE THREAD

**Issue by minislel** [fast4x/RiMusic#1348]
### Steps to reproduce the bug

Open statistics, then change from today, to week, month etc.

### Expected behavior

The app should display actual most popular song/artist/album

### Actual behavior

The latest are shown instead of the most played ones

### Screenshots/Screen recordings

![Screenshot_20240402-172349_RiMusic](https://github.com/fast4x/RiMusic/assets/43825985/6a79e84a-d94c-46b6-a4c2-11b8c4cc98d0)
![Screenshot_20240402-172343_RiMusic](https://github.com/fast4x/RiMusic/assets/43825985/5d6bb73e-13f8-4eb3-813b-e8b464ffb456)
![Screenshot_20240402-172341_RiMusic](https://github.com/fast4x/RiMusic/assets/43825985/b8400344-0285-4de8-96ed-6a44785ac4ae)

### RiMusic version

0.6.28.1

### Android version

Android 13

### Additional information

OnePlus 8t

**Comment by fast4x** [comment]
Isn't general most popular but specific from listen statistics

**Comment by minislel** [comment]
yeah i know, i meant most played, not most popular, my bad
