### ISSUE TITLE
Question regarding lrclib.net

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1349]
Are we supposed to be able to pick the lyrics from various options available on lrclib.net, or does the app automatically pick them for us?

If the latter is the case, I implore you to consider adding the option to choose lyrics from options. In ViTune, it is implemented in this manner

**Comment by fast4x** [comment]
Pick is under development... wait... soon...

**Comment by fast4x** [comment]
Implemented, available from version 0.6.29
