### ISSUE TITLE
Custom Album Covers and Music Informations

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#135]
### Description

I would like to change the cover or more of informations for music videos like the name the artist and the image

### Suggested Solution

Add an option to change song informations localy

### Additional Context

I would also like that the disk icon change into an Video icon when there's a music video playing.
And i don't like the fact that music videos and sometimes artists text is geting randomely colored in dynamic mode (this hapens alot on music videos when there are [ ])

**Comment by MattSolo451** [comment]
It would be useful to have such an option to be able to manually adjust the cover view from the video or add it yourself.  So far it scales very badly compared to the Harmony Music app. 
Here an example Harmony: 
![Screenshot_20231227-120644](https://github.com/fast4x/RiMusic/assets/70535762/b3ad62ef-9bd9-480d-b625-3883a9f93fc2)
And this is RiMusic:
![Screenshot_20231227-120639](https://github.com/fast4x/RiMusic/assets/70535762/82c25cbd-8412-4e9e-a7a6-c0c4209bd872)

**Comment by fast4x** [comment]
> It would be useful to have such an option to be able to manually adjust the cover view from the video or add it yourself.  So far it scales very badly compared to the Harmony Music app. 
> Here an example Harmony: 
> ![Screenshot_20231227-120644](https://github.com/fast4x/RiMusic/assets/70535762/b3ad62ef-9bd9-480d-b625-3883a9f93fc2)
> And this is RiMusic:
> ![Screenshot_20231227-120639](https://github.com/fast4x/RiMusic/assets/70535762/82c25cbd-8412-4e9e-a7a6-c0c4209bd872)
> 

Done just available improvement

**Comment by fast4x** [comment]
The cover loaded from the phone or from a website?

**Comment by OrangeZXZ** [comment]
> The cover loaded from the phone or from a website?

both would be cool but on the phone (if we dont need to keep the photo after using it) it would be cool

**Comment by fast4x** [comment]
The local image, is not moved with a backup... remains on the device....

**Comment by OrangeZXZ** [comment]
> The local image, is not moved with a backup... remains on the device....

i was saying that the image is saved on the cache that way we dont need to keep unessesary images in our gallery app

**Comment by fast4x** [comment]
Implemented update title, authors and cover from url, for now not loading local image.
If you want this feature, create new specific ticket for future :)

Available from version 0.6.19
