### ISSUE TITLE
On device music

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1351]
### Steps to reproduce the bug

Please remove those icon for on device music only..!
Cause its not accessable and it just ruin music player looks..!

### Expected behavior

Accessable 

### Actual behavior

Not accessable

### Screenshots/Screen recordings

![Screenshot_20240403-010156_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/3f243e8c-24cb-4f5e-9c70-af9baf65c96e)

### RiMusic version

0.6.28.1

### Android version

Android 13

**Comment by fast4x** [comment]
Implemented, available from version 0.6.29
