### ISSUE TITLE
Offline Album cover 

### ISSUE THREAD

**Issue by danxel347** [fast4x/RiMusic#1353]
### Steps to reproduce the bug

-

### Expected behavior

 When I'm away from home and playing music offline, I should be able to see the album covers of the ones I've downloaded initially.

### Actual behavior

 The album cover isn't showing for the artist whose music I downloaded, even though I have it in my image cache.
![Screenshot_20240402_152634](https://github.com/fast4x/RiMusic/assets/117977580/93f5422d-643f-43eb-88c6-98edfacff8fa)

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/117977580/d34b662b-811a-4ba2-a005-c881a2dff0bb

### RiMusic version

0.6.28.1

### Android version

Andriod 13

### Additional information

-

**Comment by fast4x** [comment]
I don’t know what you did, the cache works look

https://github.com/fast4x/RiMusic/assets/1484476/b61da8ef-315d-490c-ab52-e0f5ba5f3b3b
