### ISSUE TITLE
[Feature]: Saved translated letter

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1354]
### Description

"Right now we have lrclib as a library for synchronized lyrics, but how about adding the option to save the translation made by the translator as another type of lyric?"
![Screenshot_2024-04-02-12-42-52-995_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/f5967032-f1a5-4001-ae2d-7eb8220b80ed)

### Suggested Solution

In the case, like another idea that has already been mentioned, saving it in cache, or I don't know what other options could be available.

I feel like it would be good for those of us who listen to English-Spanish.

**Comment by JeePopuwu** [comment]
But if one doesn't have internet/data, or is in a place without the possibility of accessing the network. Like on a trip or something similar, it would be much better to already have the translation saved.

**Comment by fast4x** [comment]
Yeah, that’s a good explanation.

**Comment by JeePopuwu** [comment]
Thanks
