### ISSUE TITLE
Ideas copied or that I would like to be and would be fantastic idk[Feature]: 

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1356]
### Description

**Ideas on how the lyrics are displayed.**
![Picsart_24-04-02_19-05-18-086](https://github.com/fast4x/RiMusic/assets/159836335/3efa822f-e4c4-4cfd-a252-42a003d34451)
Unprofessional editing, I know lol.Here, the point I wanted to show is that the player should be in the center completely, and not above.
And
![Picsart_24-04-02_19-09-11-205](https://github.com/fast4x/RiMusic/assets/159836335/e177d269-15ec-4dd3-b2e0-0d0b9478672d)
That the large text in the lyrics matches its counterpart on the cover, and that the image above it is larger.
**Crossfade.**

This is an idea that has been requested for a long time, and I feel that it is the one that would make Rimusic the most competitive among all the branches of Vimusic.

### Suggested Solution

And that's it for the ideas for now haha. Anyway, they don't feel like implementing all at once, they're just to keep the ideas fresh.Thank you, seriously, your app is one of the best I've found.

**Comment by fast4x** [comment]
ImpIemented, i think I did what you asked.
Available from version 0.6.29

**Comment by NikunjKhangwal** [comment]
All of these ideas are suggested before :)

**Comment by JeePopuwu** [comment]
That's why I said copied, since I know they were previous ideas but to keep them fresh.

**Comment by fast4x** [comment]
Implemented crossfade songs effect, available from version 0.6.34
