### ISSUE TITLE
Albums show as "Unknown" 

### ISSUE THREAD

**Issue by Juggalage** [fast4x/RiMusic#1362]
### Steps to reproduce the bug

Go to albums tab

### Expected behavior

Albums should show up as normal

### Actual behavior

Albums show as blank, but when clicked on show "Unknown." 

### Screenshots/Screen recordings

![Screenshot_20240403-140429](https://github.com/fast4x/RiMusic/assets/32726906/6a450cdc-58c9-478a-9ab6-58e25464ff6d)
![Screenshot_20240403-140424](https://github.com/fast4x/RiMusic/assets/32726906/3ace7b89-4309-43a1-a808-f9598cdff8a5)

### RiMusic version

v0.6.28.1

### Android version

Android 14

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/b5dcc3a8-0214-4605-85e4-2ede75502f1d

retry

**Comment by Juggalage** [comment]
I was able to fix this and my previous bug report by clearing app data. Interestingly, restoring a previous backup brings the bugs back.

**Comment by fast4x** [comment]
I can't recreate it

**Comment by Juggalage** [comment]
It seems to happen somewhat randomly. I can go through some albums and have one not load, clear cache and data, and then the album will load perfectly but a different album won't.
