### ISSUE TITLE
[Feature]: Move it a little there, not symmetrically

### ISSUE THREAD

**Issue by Tayurivv** [fast4x/RiMusic#1363]
### Description

![Untitled56_20240403235550](https://github.com/fast4x/RiMusic/assets/164246093/00ee8585-82aa-45c8-b804-d91869947607)
This offended my friend, he is a perfectionist

### Suggested Solution

Well, move this slider a little in the playback speed change tab

**Comment by dAtA-TRoN** [comment]
Gosh, that post could've been mine 🤔!
