### ISSUE TITLE
[Add random songs] button not adding songs to queue

### ISSUE THREAD

**Issue by betmobil** [fast4x/RiMusic#1367]
### Steps to reproduce the bug

1. Open app and go to any playlist or favorites and enable [Add random songs] button (the one between [Delete downloads] and [Randomize and play] buttons).
2. New random songa show in the playlist
3. start the playlist from the first song or by random

### Expected behavior

Randomly added songs should be added to the queue with the songs already from the playlist/favorites 

### Actual behavior

Only songs already in playlist/favorites are queued (None of the random songs are queued)

### Screenshots/Screen recordings

- Button enabled and random song appearing (I started the favorites from the first song):
![1](https://github.com/fast4x/RiMusic/assets/107946762/f6af70f8-9eb0-4a13-b3a3-a38d110e9ab3)

- Random song missing in the place it was added in the favorites (And its not anywhere else in the queue nor is any other Random song) :

![2](https://github.com/fast4x/RiMusic/assets/107946762/b4257c4a-07b6-4af2-8a5b-1bd566def376)

### RiMusic version

0.6.28.1

### Android version

Android 13

### Additional information

- Poco X3 Pro
- MIUI Global 14.0.2
- All app permissions granted

**Comment by fast4x** [comment]
Are recommendations not songs to add in queue

**Comment by betmobil** [comment]
Understand. Its unclear its just recommendations since they are scattered all over the playlist and I wont be going to the end of it just to get a recommendation, but will just go to [Quick Pics] tab. Any possibilities of adding a feature where it adds the songs fully to Playlist?

**Comment by fast4x** [comment]
The recommended songs are scattered throughout the list randomly, just click on them to listen to them and then decide what to do.
