### ISSUE TITLE
Couldn't find an application to open documents 

### ISSUE THREAD

**Issue by NightFly88** [fast4x/RiMusic#1369]
How do I fix this message
Couldn't find an application to open documents ?
I have samsung a52s mobile

### Expected behavior

Nvt

### Actual behavior

Nvt

### Screenshots/Screen recordings

![Screenshot_20240401_172033](https://github.com/fast4x/RiMusic/assets/163666747/2c86d304-65c4-441c-8368-0417fcb1ea8b)

### RiMusic version

v0.6.28.1 

### Android version

Android 14

**Comment by fast4x** [comment]
What were you doing?

**Comment by NightFly88** [comment]
> What were you doing?

What do you mean,I've tried everything nothing helps

**Comment by fast4x** [comment]
Before the error which functions were you using? Which button did you press?

**Comment by NightFly88** [comment]
> Before the error which functions were you using? Which button did you press?

No button reinstall doesn't help either

**Comment by NightFly88** [comment]
Uploading Screen_Recording_20240404_194154_One UI Home.mp4…

**Comment by NightFly88** [comment]
https://github.com/fast4x/RiMusic/assets/163666747/846b80c5-f961-4a7f-aff7-5eeced903140

**Comment by NightFly88** [comment]
> ok I'll check import button

Okay

**Comment by fast4x** [comment]
I have added a specific message if error occurs, next version try and report your feedback about this.

**Comment by fast4x** [comment]
Available from version 0.6.29

**Comment by NightFly88** [comment]
Thank you I would test it in the next version

**Comment by NightFly88** [comment]
> Available from version 0.6.29

I keep getting this message what app should I download on.me samsung a52s?
![Screenshot_20240409_153306](https://github.com/fast4x/RiMusic/assets/163666747/9a65dbc6-a425-4d80-b153-2debd289ec33)
