### ISSUE TITLE
Update Dynamic Colors

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#137]
### Description

I think that sometimes the Dynamic colors are off like in this example:
![Screenshot_20231122_074018](https://github.com/fast4x/RiMusic/assets/104271365/433899e1-023d-43ba-aa37-2445bd7ae598)

It should be more like this on One UI 6:
![Screenshot_20231122_074023](https://github.com/fast4x/RiMusic/assets/104271365/bebf606c-2d20-4a80-98a1-db3631bf58ec)

### Suggested Solution

Make colors more vibrant and chose the right color (maybe do a selection of preferred colors where it chose the prefered one if it's similar to prevent multiple yellows or purples)

### Additional Context

Also the hearth icon in my opinion should be not filled until you tap it because the curent heart button is hard to know if it's already on
example:
![20231123_194405.jpg](https://github.com/fast4x/RiMusic/assets/104271365/4935a06b-096a-440b-83f5-01bf029a1af4)

Same gose to bottom butons but they are easier to know because they are white

Also the play button and other new ui (like the chose language pop-up is not Dynamicaly colored)

It would be also cool an Amoled Dynamic theme (optional)

**Comment by astro-ray** [comment]
Yes, I have noticed it as well
![Screenshot_20231225_122000.jpg](https://github.com/fast4x/RiMusic/assets/69363775/8259ca9f-9bb4-414a-a5bf-0ff6b5f9108f)

![Screenshot_20231223_004155.jpg](https://github.com/fast4x/RiMusic/assets/69363775/421aed8c-9161-4a7d-8357-d4eff812201d)

**Comment by fast4x** [comment]
Fixed and available on version 0.6.16.1
