### ISSUE TITLE
Importing a playlist adds only 1 song

### ISSUE THREAD

**Issue by VadosG** [fast4x/RiMusic#1370]
### Steps to reproduce the bug

1. Export playlist with more than 1 songs
2. Delete playlist from RiMusic
3. Import previously created playlist
4. Only 1 song will be imported

### Expected behavior

All songs must be imported

### Actual behavior

Only 1 song will be imported

### RiMusic version

0.6.28.1

### Android version

Android 13

**Comment by fast4x** [comment]
Upload file used please

**Comment by VadosG** [comment]
[RMPlaylist_TestList_20240404215504.csv](https://github.com/fast4x/RiMusic/files/14889604/RMPlaylist_TestList_20240404215504.csv)

**Comment by VadosG** [comment]
On version 0.6.30 the problem remains.

**Comment by fast4x** [comment]
A question, are the songs in the file already present in RiMusic on the songs page?

**Comment by VadosG** [comment]
Yes

**Comment by fast4x** [comment]
Ok i have understand what is the problem!!! I'll try to fix thanks

**Comment by fast4x** [comment]
Fixed, available from version 0.6.31
