### ISSUE TITLE
Issues picking song from favorites over 500 items

### ISSUE THREAD

**Issue by dollarSignUsername** [fast4x/RiMusic#1371]
### Steps to reproduce the bug

Go to favorites, see how many items there are in total. If below 500 it will work without issues, pick any song and it starts playing.
If it's above 500, it will play a random song from favorites (not the one you tap). Tapping the same item on the list will play a different random song from the list.

### Expected behavior

The funny part is that if you use filter to bring down visible number of songs to under 500, it will play what you tap on. I have not experienced this in previous versions.

### Actual behavior

Also, if you shuffle all from favorites, the que only has 500 songs, even if favorites has more

### RiMusic version

0.6.28.1

### Android version

14

**Comment by fast4x** [comment]
Try custom version it's just fixed
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by fast4x** [comment]
From settings you can set over 500 or unlimited.

**Comment by dollarSignUsername** [comment]
Got it, I didn't notice the setting. Custom version fixed the random song issue, thanks 👍

**Comment by fast4x** [comment]
![Screenshot_2024-04-05-00-32-28-729_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/82cf3ac4-2a29-4f40-89e5-59a3330e3986)

Ui settings

**Comment by cMattw** [comment]
> ![Screenshot_2024-04-05-00-32-28-729_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/82cf3ac4-2a29-4f40-89e5-59a3330e3986)
> 
> Ui settings 

horizontal tabs leaked

**Comment by fast4x** [comment]
Top bar... and now... also bottom bar... 😂

**Comment by fast4x** [comment]
![giphy.gif](https://github.com/fast4x/RiMusic/assets/1484476/ec4a7bac-b347-4b7f-b5de-3905211dcdc8)

**Comment by fast4x** [comment]
> > Top bar... and now... also bottom bar... 😂
> 
> Can it be changed to previous setup from the settings?

Of course, in the settings you have left, right, top and bottom
