### ISSUE TITLE
Adaptive App Icon for Material You

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1373]
![IMG_20240405_122948](https://github.com/fast4x/RiMusic/assets/71184627/04a2622e-6f5b-4e3b-84ea-37e9e9cc9e96)

### Description

I've noticed that the app icon doesn't change with different Material You system color schemes. It would be great if RiMusic could update its icon to match Google's Material You design style. This way, the icon would blend in better with the overall look and feel of the device.

### Suggested Solution

1. Look into Google's Material You guidelines for adaptive app icons.

2. Add the ability for RiMusic to generate adaptive icons that match different Material You color schemes.

### Additional Context

Making RiMusic's app icon adaptive would make it feel more integrated with the user's device, enhancing the overall experience and ensuring alignment with current Android design trends.

**Comment by ikanakova** [comment]
I have version 0.6.28.1 and the icon changes normally with the palette selected on my Samsung Galaxy A53.

**Comment by dAtA-TRoN** [comment]
> I have version 0.6.28.1 and the icon changes normally with the palette selected on my Samsung Galaxy A53.

Alright, that's strange. Maybe Samsung replicated and integrated the feature themselves? Or perhaps it's because my OnePlus 8 isn't the latest model anymore. I'll wait to see what fast4x has to say about it, whether the feature is actually already built-in natively.

**Comment by ikanakova** [comment]
> Alright, that's strange. Maybe Samsung replicated and integrated the feature themselves?

No, I don't think so. Because the icon fulfills everything in this guide: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by dAtA-TRoN** [comment]
![IMG_20240405_134744~2.jpg](https://github.com/fast4x/RiMusic/assets/71184627/d830a196-d557-47c7-ba98-5b2b44566e5c)

Thanks for pointing that out. I was able to check it myself just now. I had an old Samsung tablet lying around here, running LineageOS, so (almost) vanilla Android. And yes, I can confirm that RiMusic already has an adaptive icon. Cool, good to know. And perhaps it's about time for a new phone 🤔.

**Comment by dAtA-TRoN** [comment]
> No, I don't think so. Because the icon fulfills everything in this guide:

Cool, thanks for the context 👌🏼.
