### ISSUE TITLE
Album cover not displaying on songs 

### ISSUE THREAD

**Issue by Nathaniel466** [fast4x/RiMusic#1378]
### Steps to reproduce the bug

1. Open Rimusic
2. Search for "we don't trust you" 
3. Open album 
4. Play song 
5. Cover does not show
![Screenshot_2024-04-05-09-35-12-517_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/166153675/9b5e14c7-4e67-496f-b066-bd422176f72b)
![Screenshot_2024-04-05-09-35-07-787_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/166153675/cefffadc-c96a-4baa-a202-1c4aa1eb170d)

### Expected behavior

The cover should show when playing a song. 

### Actual behavior

The cover just shows the Rimusic logo.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/166153675/62e3d6ce-29fd-46af-96a5-9151fa8ec806

### RiMusic version

V0.6.28.1

### Android version

Android 14

### Additional information

I have tried changing the cover with another image still doesn't show. Other songs work for some reason like "2093" by yeat. Maybe it's a new recent song?

**Comment by dAtA-TRoN** [comment]
![Screenshot_2024-04-05-19-16-47-26_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/d6bb82f1-5446-496c-b44c-4e1cb2b20203)

It's not specific to the album.

**Comment by Nathaniel466** [comment]
Yes it works I can confirm. But it doesn't work for the explicit album. Also here's an idea make a E symbol like Spotify for explicit songs. Otherwise I guess I can deal with it.

https://github.com/fast4x/RiMusic/assets/166153675/60bf7761-1944-4918-b4e5-de4de05a5548

Here is the album try it on the Rimusic app:
https://music.youtube.com/playlist?list=OLAK5uy_nexYBihVfegVxOxvYnnhlZyTqLDW_wjY8

**Comment by dAtA-TRoN** [comment]
> Also here's an idea make a E symbol like Spotify for explicit songs.

Duplicate #1320
