### ISSUE TITLE
Just a short Question...

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1379]
What is this for!?

![IMG_20240405_200650.jpg](https://github.com/fast4x/RiMusic/assets/71184627/662b1f3e-379b-460d-8840-91314ffedc73)

**Comment by fast4x** [comment]
i have to look, but in artist or album?

**Comment by sayyid5416** [comment]
Featured playlists

**Comment by sayyid5416** [comment]
![Screenshot_2024-04-06-07-45-51-237_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/78584556/96c6d5f7-5238-467e-8913-66ab52f26781)
But what's this?

**Comment by dAtA-TRoN** [comment]
> Featured playlists

Oh, thanks. But who put it together? Have you ever seen a playlist like this before? And why is it only available through search? I'm still not quite getting it. Could you explain more clearly what makes it different from a regular playlist?

**Comment by sayyid5416** [comment]
They are playlists from _**YouTube Music**_

**Comment by dAtA-TRoN** [comment]
> They are playlists from YouTube Music

So, curated by YouTube Music itself, not by users?

**Comment by sayyid5416** [comment]
yes

**Comment by dAtA-TRoN** [comment]
> yes

I think this is another one of those icons that should only appear when there is something behind it.

**Comment by sayyid5416** [comment]
> > yes
> 
> I think this is another one of those icons that should only appear when there is something behind it.

Yeah, this feature would be great to have.

Show this only when featured playlists are available.

**Comment by fast4x** [comment]
> > ![Screenshot_2024-04-06-07-45-51-237_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/78584556/96c6d5f7-5238-467e-8913-66ab52f26781)
> > But what's this?
> 
> I wanna know as well. Because I didn't seem to find any difference tapping this.

It show/hide listened on-device songs in home songs

**Comment by dAtA-TRoN** [comment]
> Yeah, this feature would be great to have.
> 
> Show this only when featured playlists are available.

Then I hope that fast4x is reading along 😏.

**Comment by dAtA-TRoN** [comment]
> He is always reading…

Sounds like Sauron again...

**Comment by fast4x** [comment]
![giphy (1).gif](https://github.com/fast4x/RiMusic/assets/1484476/2f0fd67f-fb46-45cc-89eb-dbdaf96feab9)

LOL
