### ISSUE TITLE
The music queue isn't showing

### ISSUE THREAD

**Issue by AquamarineDreams** [fast4x/RiMusic#1383]
### Steps to reproduce the bug

Open any music and try to open the queue. 

### Expected behavior

Queue/playlist showing up. 

### Actual behavior

When I press the arrow button, or slide up, the queue doesn't shows up. 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/140275860/7eb93a0d-3d94-4292-b64e-afdc72dfc5f4

### RiMusic version

0.6.29

### Android version

Android 14

### Additional information

It was working just fine before I update.

**Comment by fast4x** [comment]
Please disable arrow button temporarily, I'll fix it soon. Thanks
![Screenshot_2024-04-06-00-40-56-578_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/b92d66d8-7d4e-4e17-aa07-f3e7c84ee58c)

**Comment by AquamarineDreams** [comment]
Ok, thank you

**Comment by fast4x** [comment]
Fixed, available from version 0.6.30
