### ISSUE TITLE
the tracklist button won't open 

### ISSUE THREAD

**Issue by HasakeKisaragi** [fast4x/RiMusic#1385]
### Steps to reproduce the bug

the up arrow that opens the track list can't open at all, the shuffle button can't really be turned off, the animated music visual always stops, opening the album cover lyrics becomes duplicated 

### Expected behavior

When the button is pressed, it displays text so you know its function 

### Actual behavior

This bug occurs on Samsung 

### Screenshots/Screen recordings

![17119302ggf52669-picsay](https://github.com/fast4x/RiMusic/assets/166180711/05856b58-dfca-46c6-b6de-ef70793e8d1d)

### RiMusic version

v0.6.29

### Android version

Android 14

### Additional information

I hope it will be fixed soon. This application is very good and has complete features, thank you very much

**Comment by fast4x** [comment]
Yes, disable temporary Arrow button please, I'll fix soon

**Comment by fast4x** [comment]
Fixed, available from version 0.6.30
