### ISSUE TITLE
[Crash] When trying to open Downloaded songs 

### ISSUE THREAD

**Issue by Corotyest** [fast4x/RiMusic#1386]
### Steps to reproduce the bug

1. Open the app 
2. Navigate to the library
3. Open Downloaded songs 

### Expected behavior

Open Downloaded songs tab

### Actual behavior

https://github.com/fast4x/RiMusic/assets/74837790/f9407c5e-58de-4754-8651-c3a9980f8ce6

### RiMusic version

0.6.29

### Android version

Android 11

**Comment by dAtA-TRoN** [comment]
https://github.com/fast4x/RiMusic/assets/71184627/b40eff3a-d0ec-48e7-a36f-2c09d5571b80

Can't confirm. Maybe your downloaded files are corrupted somehow. Have you tried deleting all downloads manually via the settings to get access again?
