### ISSUE TITLE
Cover art on Fullscreen lyrics is broken 

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#1388]
### Steps to reproduce the bug

Open full screen lyrics

### Expected behavior

Cover art is a small image rather than the blurred background (is it a feature? Looks wrong though)

### Actual behavior

There should be a blurred background 

### Screenshots/Screen recordings

![Screenshot_2024-04-06-08-45-04-891_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89296867/c632d219-d245-4841-acb3-cdb6e1478346)

### RiMusic version

0.6.28

### Android version

Android 14

**Comment by sayyid5416** [comment]
![image](https://github.com/fast4x/RiMusic/assets/78584556/1f833137-d50b-4c7a-84ea-961ab25cc03a)

Yes, it feels broken and very bad.

**Comment by JeePopuwu** [comment]
I agree, it should be black like before. It must have been an oversight, but there's no need to rush it.

**Comment by VINULA2007** [comment]
> I agree, it should be black like before. It must have been an oversight, but there's no need to rush it.

Bruh I forgot how it was beforehand
Thought it had a blurred background lol

**Comment by NikunjKhangwal** [comment]
If not blur then probably a gradient background. Maybe it'll be easier to implement because app already has gradient background for playing screen.

Something like:-
![IMG_20240406_093119](https://github.com/fast4x/RiMusic/assets/99175083/e91c85d1-0129-44f1-a015-74e6d5a0baf0)

**Comment by JeePopuwu** [comment]
> > Estoy de acuerdo, debería ser negro como antes. Debe haber sido un descuido, pero no hay necesidad de apresurarse.
> 
> Bruh, olvidé cómo era de antemano. Pensé que tenía un fondo borroso jajaja.

Well... it would be a good idea for it to be a blurry background, not a pixelated jpg xD.

**Comment by VINULA2007** [comment]
> > > Estoy de acuerdo, debería ser negro como antes. Debe haber sido un descuido, pero no hay necesidad de apresurarse.
> > 
> > 
> > Bruh, olvidé cómo era de antemano. Pensé que tenía un fondo borroso jajaja.
> 
> Well... it would be a good idea for it to be a blurry background, not a pixelated jpg xD.

Maybe a enlarged zoomed Fullscreen blurred background would look good

**Comment by VINULA2007** [comment]
> > > > Estoy de acuerdo, debería ser negro como antes. Debe haber sido un descuido, pero no hay necesidad de apresurarse.
> > > 
> > > 
> > > Bruh, olvidé cómo era de antemano. Pensé que tenía un fondo borroso jajaja.
> > 
> > 
> > Well... it would be a good idea for it to be a blurry background, not a pixelated jpg xD.
> 
> Maybe a enlarged zoomed Fullscreen blurred background would look good

But the good old black is fine
Lyrics are clearly visible and overall less buggy

**Comment by VINULA2007** [comment]
> > > > > Estoy de acuerdo, debería ser negro como antes. Debe haber sido un descuido, pero no hay necesidad de apresurarse.
> > > > 
> > > > 
> > > > Bruh, olvidé cómo era de antemano. Pensé que tenía un fondo borroso jajaja.
> > > 
> > > 
> > > Well... it would be a good idea for it to be a blurry background, not a pixelated jpg xD.
> > 
> > 
> > Maybe a enlarged zoomed Fullscreen blurred background would look good
> 
> But the good old black is fine Lyrics are clearly visible and overall less buggy


![Screenshot_2024-04-06-09-37-43-211_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89296867/577791b3-2e53-4a48-af93-4e8b6b8f5028)

**Comment by fast4x** [comment]
Sorry, i remove it

**Comment by fast4x** [comment]
Fixed, available from version 0.6.30
