### ISSUE TITLE
[Feature]: Position of settings in bottom bar

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#1389]
### Description

These buttons should be positioned in _**top-left**_ corner of the app when using _**bottom navigation bar**_:
- [x] `Settings` button, and 
- [x] `back` button

Benefits:
- Less cluttered navigation bar.
- Top icons and label would look more symmetric.

### Additional info:
- [x] Also move the `back` button from the **_Albums_** page to the **_top-left corner_** to make it more consistent.
- [x] Since `back` button will be moved to **_top-left corner_**, Playlists will have only one icon i.e `songs` icon. Remove it, because it's not really necessary.

**Comment by dAtA-TRoN** [comment]
Nice!

**Comment by dAtA-TRoN** [comment]
Nice!

**Comment by dAtA-TRoN** [comment]
![IMG_20240406_141324_098.jpg](https://github.com/fast4x/RiMusic/assets/71184627/76d76337-f1f7-455a-9096-78dd6e4c4724)

The stats have now moved to the top left corner on the library page due to the new update. However, if we want consistency with the settings icon, the stats should probably be moved elsewhere. I suggest giving them their own prominent place in the library. This would also fill the empty space and create a more uniform appearance. What do you think of the suggestion?

Additionally, it's important to address the formatting across the app as a whole. Each submenu seems to have its own rules in this regard.

**Comment by sayyid5416** [comment]
No, I don't agree with stats and search icon. 
- Best place for `search` icon is in **_top-right corner_**, and 
- Current location of `stats` icon feels natural.

Additionally:
- `Search` icon at **_top-right corner_** and `back` icon at **_top-left corner_** will align the top heading properly.

Note:
- Btw, when I meant to put `settings` and `back` button in **_top-left corner_**, I meant opposite to current search icon, and not where you have shown.

**Comment by dAtA-TRoN** [comment]
Oh now I see. Thanks for clarifying this.
I agree with that.

However, I have a different perspective on the stats icon. First, stats are essentially a set of playlists, so it would be logical to include it with the other playlists. Secondly, there's enough space to highlight this feature more prominently, so why shouldn't we take advantage of it. Additionally, it would create a cohesive look for the entire library page.

**Comment by sayyid5416** [comment]
Reasons we should not show `stats` as a special playlist like `downloaded`, `cached`, or `My Top`:
- All those special playlists essentially acts like one folder, while `stats` contains many more folders inside like _**today**_, _**weekly**_, _**monthly**_ etc.
- Opening those special playlist shows same type of navigation bar, while `stats` shows different types of items in navigation bar.
- Current location for `stats` seems natural.

**Comment by sayyid5416** [comment]
Btw I've created another request regarding improper spacings/margins #1391

**Comment by dAtA-TRoN** [comment]
All good and valid points you're making there, however, it's easy to circumvent them by simply demarcating the button of the stats with different colors like this (it's just an example, I'm no artist):

![sketch1712418132259.png](https://github.com/fast4x/RiMusic/assets/71184627/ad523eea-6401-4e88-bbcb-7c07363f96cd)

But don't worry, that's not the hill I want to die on.

**Comment by sayyid5416** [comment]
If you think this is a good idea, you should create a different issue, otherwise fast4x might get confused what this request is about and what's being discussed.

Although I don't personally like this idea of having stats in special playlist, but if you think it's a good idea, it's atleast worth discussing

**Comment by dAtA-TRoN** [comment]
> If you think this is a good idea, you should create a different issue, otherwise fast4x might get confused what this request is about and what's being discussed.
> 
> Although I don't personally like this idea of having stats in special playlist, but if you think it's a good idea, it's atleast worth discussing 

No, it's not that important to me. The current implementation is completely okay as it is.

**Comment by sayyid5416** [comment]
back button and settings button implemented in #1513. Only last task remained, @fast4x Can you look at it?

**Comment by fast4x** [comment]
Implemented, available from version 0.6.31
