### ISSUE TITLE
[Feature]: Not sorry

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1390]
### Description

I know I was the one who requested an improvement in the player's center. But it wasn't necessary to add a semi-pixelated cover, how it was is fine.
![Screenshot_2024-04-05-22-50-25-830_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/c1e873ea-7437-41d1-8d4a-cba56a5675cd)

### Suggested Solution

As long as the lyrics remain centered, everything is fine.
I'm sorry if I'm causing too many issues. Please, just the regular version, but centered. And regarding the rotated cover you mentioned, I agree, it should all be black; it doesn't look very aesthetic. Still, I apologize for all the trouble.

**Comment by sayyid5416** [comment]
You are correct, look at #1388

**Comment by dAtA-TRoN** [comment]
I would prefer it if there was no picture in the background at all. You can already see the album cover on top. Behind the text it just gets in the way and distracts. Simply making it opaque would be my solution.

**Comment by sayyid5416** [comment]
> I would prefer it if there was no picture in the background at all. You can already see the album cover on top. Behind the text it just gets in the way and distracts. Simply making it opaque would be my solution.

or some **_very subtle_** gradient

**Comment by JeePopuwu** [comment]
I agree with all of you.

**Comment by dAtA-TRoN** [comment]
> or some very subtle gradient

Fine by me, but the additional cover image in the background is, in my opinion, simply unnecessary. It's too much.

**Comment by sayyid5416** [comment]
> > or some very subtle gradient
> 
> Fine by me, but the additional cover image in the background is, in my opinion, simply unnecessary. It's too much.

100% agree.

**Comment by fast4x** [comment]
I'll remove it sorry

**Comment by dAtA-TRoN** [comment]
> I'll remove it sorry

We here in Germany say:
Trying is better than studying 🤷🏻‍♂️.

**Comment by fast4x** [comment]
Improved, available from version 0.6.30
