### ISSUE TITLE
[Feature]: Improve Left Margin

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#1391]
### Description

When using bottom navigation bar, many items seem too close to the left edge.
- Just check different pages of the app _(including settings page)_, and you will notice them.

For example:
![image](https://github.com/fast4x/RiMusic/assets/78584556/5457bde3-ac58-4f46-bfa1-193995faa2fc)

### Suggested Solution

Increase the padding or margin for these items

**Comment by NikunjKhangwal** [comment]
It's a new implementation, i think it'll get better with time :)

**Comment by sayyid5416** [comment]
Yes. That's why I'm reporting it, so developer could keep track of it easily.
