### ISSUE TITLE
[Feature]: Position of miniplayer

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#1392]
### Description

- [ ] Miniplayer should be above bottom navigation bar
![image](https://github.com/fast4x/RiMusic/assets/78584556/310a87e8-1da4-4ca9-90f6-90d0d5931a1e)

<br>

- [ ] Also, Add some sort of shadow or a solid line below bottom navigation bar, to make it differentiable from the rest of the app.

<br>

- [ ] **BUG:** On `Songs` page, _**Go to top**_ icon is hidden behind bottom navigation bar

**Comment by dAtA-TRoN** [comment]
> Also, Add some sort of shadow below bottom navigation bar, to make it differentiable from the rest of the app.

I agree. How about that?

![sketch1712379718085.png](https://github.com/fast4x/RiMusic/assets/71184627/a7d5fe03-8010-4982-b969-9508b068516c)

**Comment by sayyid5416** [comment]
![image](https://github.com/fast4x/RiMusic/assets/78584556/735f0f8f-dd5b-4994-be2d-1084233efe92)
Yes, too fancy.

2nd one would work, but is shadow that hard to implement?

**Comment by cMattw** [comment]
> > Also, Add some sort of shadow below bottom navigation bar, to make it differentiable from the rest of the app.
> 
> I agree. How about something like that?
> 
> ![sketch1712379718085.png](https://github.com/fast4x/RiMusic/assets/71184627/a7d5fe03-8010-4982-b969-9508b068516c)
> 
> Too fancy? How about that?
> 
> ![sketch1712379981769.png](https://github.com/fast4x/RiMusic/assets/71184627/57933527-ed59-49fe-be10-a66f7a94175e)

The first one actually looks good. I'd pay for that to actually be implemented (jk, I'm broke)

**Comment by dAtA-TRoN** [comment]
> 2nd one would work, but is shadow that hard to implement?

I don't know. It's just a mockup. It's just meant to give you an idea of where you want to go.

**Comment by NikunjKhangwal** [comment]
Another vote for 2nd concept. I think first looks good but it doesn't match the app style

**Comment by sayyid5416** [comment]
exactly, 1st one would be too much lol

**Comment by dAtA-TRoN** [comment]
> exactly, 1st one would be too much lol 

![proxy-image.jpg](https://github.com/fast4x/RiMusic/assets/71184627/69dff6d8-35f5-437d-bd34-696d4c41a6b3)

Well, the gist is that Google's tweaking its design language, rolling out these floating bars across its apps gradually. I think it could work if the bar were a bit thicker, with slightly larger icons. However, the clash between the gradual player bar and the round design of the icon bar might still be a visual hiccup. So, I'm inclined to think my second suggestion is the way to go.

**Comment by sayyid5416** [comment]
This change won't go well with the rest of the app.

**Comment by NikunjKhangwal** [comment]
Agreed. I'm personally not a fan of it either. I like all other material you design elements like square buttons with rounder corners, pill shaped on/off buttons & icons etc but not this.

**Comment by dAtA-TRoN** [comment]
> This change won't go well with the rest of the app.

I think so too.

**Comment by fast4x** [comment]
It's hard to implement for now.

**Comment by dAtA-TRoN** [comment]
> It's hard to implement for now. 

Then we have to wait.

**Comment by sayyid5416** [comment]
> It's hard to implement for now.

OK, then try to implement whatever is possible from the _**3 requested changes**_

**Comment by dAtA-TRoN** [comment]
@sayyid5416

Off topic:
What do you use to make these beautiful arrows? Is this a dedicated app or part of your firmware?

![320175914-310a87e8-1da4-4ca9-90f6-90d0d5931a1e.png](https://github.com/fast4x/RiMusic/assets/71184627/596f7f5b-d89c-4a44-b929-0f456eb1b034)

**Comment by fast4x** [comment]
> > It's hard to implement for now.
> 
> OK, then try to implement whatever is possible from the _**3 requested changes**_

Yes

**Comment by sayyid5416** [comment]
> @sayyid5416
> 
> Off topic: What do you use to make these beautiful arrows? Is this a dedicated app or part of your firmware?
> 
> ![320175914-310a87e8-1da4-4ca9-90f6-90d0d5931a1e.png](https://private-user-images.githubusercontent.com/71184627/320187970-596f7f5b-d89c-4a44-b929-0f456eb1b034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODcyNzYsIm5iZiI6MTcxMjM4Njk3NiwicGF0aCI6Ii83MTE4NDYyNy8zMjAxODc5NzAtNTk2ZjdmNWItZDg5Yy00YTQ0LWI5MjktMGY0NTZlYjFiMDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA3MDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3YzQ1OGU3NTc3ZGRjMzkzMjA5ZWQ4MTg1N2RlODQ0ODNkMjExMDk2YzM0MmZiMjU4M2UwMDYwYTQ1MDdjNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qOSyvC7HFymFfZZcvx-vpq1QrxQsUKVZjrkgHNzGYgo)

Telegram 😁

**Comment by dAtA-TRoN** [comment]
> Telegram 😁

https://github.com/fast4x/RiMusic/assets/71184627/6ea2d00f-1112-4c94-a856-8e278dbf8fdd

TELEGRAM!? -I would never have thought of that. Cool, thank you. Now I can delete a few apps right away 😂.
