### ISSUE TITLE
Items are below the bottom bar

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#1394]
### Steps to reproduce the bug

1. Use bottom bar
2. Go to playlists tab
3. Scroll down
4. The bottom bar is on top of the items 

### Expected behavior

The items should be adjusted to be on top of the bottom bar

### Actual behavior

The bottom bar is on top of the items

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/160244930/8fc27fe1-690b-432d-b81c-f09b93883979

### RiMusic version

0.6.29

### Android version

Android 13

### Additional information

This also happens inside the playlist itself, I cannot see or access the last song because the bottom bar is being overlaid on top of it

**Comment by NikunjKhangwal** [comment]
In ViMusic style, the floating search bar is covered by bottom nav as well. It needs to be moved up.

**Comment by sayyid5416** [comment]
3rd task on #1392 is related to it

**Comment by fast4x** [comment]
Fixed, available from version 0.6.31
