### ISSUE TITLE
[Feature]: Bottom Nav looks suggestion

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1399]
### Description

Just wnated to suggest a few things to make bottom nav look less cluttered.

### Suggested Solution

First is make the nav bar just slightly bigger to make space. Then move two words sentences in dual line when icon text are enabled. Move "picks" under "quick", same for "on device" and "my top ×" texts in library.

![IMG_20240406_111826](https://github.com/fast4x/RiMusic/assets/99175083/d8dc3c63-ef31-425d-a6d0-492bc02a6a77)

Also change some texts to make them shorter
Miscellaneous to Misc.
Downloaded to Downloads
Appearance to Looks

These changes will make icon texts look better and icon will be bigger too, currently they're too small

### Additional Context

If you don't want to make words take two lines then you probably have to make those words shorter as well.

Quick Picks:- Selection, Picks
My Top 20:- My Top or Top 20
On Device:- Local, Device

**Comment by NikunjKhangwal** [comment]
> I think it'd be better if the texts just won't show when Nav bar is set **top or bottom**. Or will that look bad?

You already have the option to turn text off from settings. These are suggestion for when texts is enabled

**Comment by fast4x** [comment]
> I think it'd be better if the texts just won't show when Nav bar is set **top or bottom**. Or will that look bad?

Icons is configurable bu settings

**Comment by NikunjKhangwal** [comment]
> I know about that option. But showing those texts while nav bar is top/bottom is just waste of space…I mean it can't really look good unless the texts/icons are too small. Even if that's the case it's not guaranteed to look good. At least I can't imagine.

I think you haven't tried a lot of apps. If search bar and back buttons gets moved to top there will be only 5 or 6 buttons left in navigation bar. 5 is usually the sweet spot because you get enough options and doesn't compromise looks but 6 is good too.

Here's Innertune
![IMG_20240406_123001](https://github.com/fast4x/RiMusic/assets/99175083/f8d50528-cb1b-402c-b28a-e04dcf190b1a)

Music You
![IMG_20240406_122950](https://github.com/fast4x/RiMusic/assets/99175083/d6e2f3f9-2ffb-40b0-ade6-bb5dc269c659)

Namida can show 6 but it automatically hides labels for tabs not currently active to save space
![IMG_20240406_122931](https://github.com/fast4x/RiMusic/assets/99175083/bb333808-cf42-431c-9102-20fb289d4383)

**Comment by NightFly88** [comment]
On my sqmsung a52s 
![Screenshot_20240406_090704](https://github.com/fast4x/RiMusic/assets/163666747/c7f0cf5a-b2fd-432d-b965-7b48f69348e4)

**Comment by NikunjKhangwal** [comment]
Actually even a lot of non-music apps i use also have 5 tabs in bottom.

![IMG_20240406_124144](https://github.com/fast4x/RiMusic/assets/99175083/45f7650f-7f57-41fe-a987-9b626cd36a71)

**Comment by fast4x** [comment]
I agree, but I ask you to "think" away from certain references such as apps that have been named as examples. The news, come thinking on their own... the result will be the "difference"...

**Comment by NikunjKhangwal** [comment]
I know, i just mentioned them for example. Because AnyoneMouse didn't knew about moving icons upwards so It was just a little misunderstanding.
