### ISSUE TITLE
Broken lyrics in full screen mode

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#1400]
### Steps to reproduce the bug

1. Play song
2. Open full screen lyrics (both synchronized/unsynchronized)
3. Press the button to skip to the next track
4. Lyrics are frozen from the previous song, as well as cover 

https://github.com/fast4x/RiMusic/assets/76595855/82819d72-c988-48dc-9ff2-a7dc6e280373

### Expected behavior

The lyrics should change with the song

### Actual behavior

The lyrics are frozen until you exit full screen

### RiMusic version

0.6.29

### Android version

Android 13

### Additional information

Samsung Galaxy A51

**Comment by aneesh1122** [comment]
Temporary solution : Pause the song and play it again. It will change the lyrics without exiting the full screen lyrics

**Comment by KOLIWAN** [comment]
3 versions passed, the bug is still here :(

**Comment by KOLIWAN** [comment]
Bug was fixed in the version 0.6.33, tnx
