### ISSUE TITLE
[Feature]: New icon for opening song lyrics on the full screen

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#1401]
### Description

Currently, one icon is used for two actions: opening lyrics to full screen and exiting full screen.
The current icon looks like an action to exit fullscreen mode (arrows inwards). I suggest adding an icon to open the full-screen lyrics with arrows pointing outwards.

![1](https://github.com/fast4x/RiMusic/assets/76595855/1d8d5051-7269-41b9-ba57-60f2e24ced56)

![2](https://github.com/fast4x/RiMusic/assets/76595855/9ba6c12f-958a-45a9-a3e9-a9d23606b449)

Current icon:
![minmax](https://github.com/fast4x/RiMusic/assets/76595855/47430369-fef8-4cfe-9498-a6a6d3aee910)

### Suggested Solution

I suggest an alternative, how the icon may look for unfolding the lyrics in full screen
![minmax2](https://github.com/fast4x/RiMusic/assets/76595855/cb2e967d-cecf-4d4f-b3fd-64eca856b63b)

**Comment by fast4x** [comment]
Nice

**Comment by dAtA-TRoN** [comment]
> Nice

Can you make it so that it can flip?

**Comment by dAtA-TRoN** [comment]
> Nice

Can you make it so that it can flip?

**Comment by sayyid5416** [comment]
@ikanokava

**Comment by sayyid5416** [comment]
@ikanakova

**Comment by ikanakova** [comment]
Sorry for the delay, I finally created the required icon #1725
