### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#1402]
### Steps to reproduce the bug

Missing translation in data and backup

### Expected behavior

Can you add it ? On crowdin 

### Actual behavior

.

### Screenshots/Screen recordings

![IMG_20240406_103639](https://github.com/fast4x/RiMusic/assets/63956787/3701642f-e5b2-449e-852c-536ec8e7f41f)

### RiMusic version

0.6.29

### Android version

A12 MIUI 14

**Comment by fast4x** [comment]
Fixed, i have added already translated string.
Available from version 0.6.30
