### ISSUE TITLE
[Feature]: Some small requests to enhance the app experience

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1404]
### Description

1) enable search in queue
2) enable shuffle in 'On device' page
3) enable searching of songs by their album
4) When I'm inside a folder of 'On device' and I press back button it takes me directly to Library. To properly go back I have to use in app 'Back' button.

### Suggested Solution

1) I know that I can simply search the song in the playlist and play it. The problem is if I select the song and play it, it replaces the previous queue.

2) 
![WhatsApp Image 2024-04-06 at 16 52 47_b4e5e63b](https://github.com/fast4x/RiMusic/assets/45353488/89c9f4e7-82bf-40b9-a5cd-d84defd775fb)
right now the shuffle button works only when there are songs listed. please enable this button for folders too.

3) I can search songs by their name or artist in the playlist but there are no results when I enter the name of the album. 

For example, I have 2 songs from the album 'Looking 4 Myself' in my playlist but when I write "Looking 4 Myself" in the playlist's search bar there are no results
![WhatsApp Image 2024-04-06 at 17 01 18_cc31bd0a](https://github.com/fast4x/RiMusic/assets/45353488/5501aaba-0a7a-49b1-8880-dcb3fffa3231)

See, I have 2 songs from that album.
![WhatsApp Image 2024-04-06 at 17 01 17_b4808157](https://github.com/fast4x/RiMusic/assets/45353488/071c26f6-5390-4584-ae43-380fd890ded4)

4) When I go back please take me to the previous folders instead of Library.

**Comment by aneesh1122** [comment]
@fast4x could you please try to implement the 3rd one at least? The rest of them can wait until the end if you wish.

**Comment by fast4x** [comment]
1. implemented

**Comment by aneesh1122** [comment]
> 1. implemented
> 
> 3. not possible

Thanks man :)

Any luck with the third one?

**Comment by fast4x** [comment]
Not yet, I must invent something

**Comment by aneesh1122** [comment]
> Not yet, I must invent something

Okay :)

![cat-computer.gif](https://github.com/user-attachments/assets/bde7439b-3128-4b56-ad01-2c52a97ae7bd)

**Comment by fast4x** [comment]
3. implemented

**Comment by aneesh1122** [comment]
> 3. implemented

Wow. Thanks dude :)

**Comment by fast4x** [comment]
3. implemented also search by album in home songs

**Comment by fast4x** [comment]
4. implemented

All avalable from version 0.6.47

**Comment by aneesh1122** [comment]
> 3. implemented also search by album in home songs

Thanks man :)

Could you please implement this also in playlists songs search?

**Comment by fast4x** [comment]
I'll look into if possible now...

**Comment by fast4x** [comment]
All done :)

**Comment by aneesh1122** [comment]
> All done :)

thanks man. I really needed this :)
