### ISSUE TITLE
Selected songs are deselected after scrolling down

### ISSUE THREAD

**Issue by u-daygupta** [fast4x/RiMusic#1408]
### Steps to reproduce the bug

1. Open a playlist
2. Start selecting/deselecting
3. Scroll past your selection

### Expected behavior

The songs stay selected

### Actual behavior

Songs get deselected as soon as they're scrolled past

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/121250333/e97b2a92-6885-4970-99e9-2abe049cf8a2

### RiMusic version

0.6.29

### Android version

Android 13

**Comment by aneesh1122** [comment]
@fast4x pls fix this

**Comment by fast4x** [comment]
Fixed, available from version 0.6.38
