### ISSUE TITLE
A certain track always stops working at a certain point

### ISSUE THREAD

**Issue by MrBoomDeveloper** [fast4x/RiMusic#1418]
### Steps to reproduce the bug

1. Open this track: [Resurrections on YouTube Music](https://music.youtube.com/watch?v=-YjgOzSQNQ0)
2. Listen until 9:31

### Expected behavior

It would just continue playin?

### Actual behavior

It returns an error

### Screenshots/Screen recordings

![Screenshot_20240407_084730](https://github.com/fast4x/RiMusic/assets/92123190/e9231dd7-7e9e-4844-8b24-c87d81a3a997)

### Logs

![Screenshot_20240407_085452](https://github.com/fast4x/RiMusic/assets/92123190/1cf8887e-8962-4402-ab5a-7bfb63466927)
![Screenshot_20240407_085503](https://github.com/fast4x/RiMusic/assets/92123190/43520e90-8157-46dd-b2f1-25d7047b529c)
![Screenshot_20240407_085434](https://github.com/fast4x/RiMusic/assets/92123190/d2848d81-6a24-4a96-9515-acb0c8826469)

### RiMusic version

0.6.29

### Android version

Android 13

### Additional information

Previously (around 0.6.20 it just crashed), but now the track just stops playing.

**Comment by fast4x** [comment]
Hi, nice info, I'll check it with your log, thanks you.

**Comment by fast4x** [comment]
I have try it but it work nice, i'm sorry.

**Comment by MrBoomDeveloper** [comment]
I downloaded the latest build from the actions and it is working!

**Comment by fast4x** [comment]
Thanks for feedback
