### ISSUE TITLE
Improve Icon Formatting and Placement in Navigation Bar

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1419]
### Description

The current navigation bar lacks consistency and proper formatting, resulting in icons being misaligned and disproportionate. This detracts from the user experience and overall aesthetic appeal. To address this issue, the following improvements are suggested:

### Suggested Solution

**1. Standardize Icon Sizes:** Ensure that all icons have consistent dimensions to create a cohesive visual appearance. This will enhance readability and usability.

**2. Optimize Spacing:** Adjust the spacing between icons and the edges of the navigation bar to be uniform and precise. Consistent spacing improves the visual balance and usability of the navigation bar.
 
**3. Arrange Icons Logically:** Rearrange the placement of icons in a logical order based on their functionality or importance. A logical arrangement enhances user intuition and navigation efficiency. 

### Mockup

_Before_
![ZomboDroid_07042024084718.jpg](https://github.com/fast4x/RiMusic/assets/71184627/5ec7017e-e02b-4bae-bd43-4ba6d2e5833b)
_After_

The same again with guidelines:

_Before_
![ZomboDroid_07042024084812.jpg](https://github.com/fast4x/RiMusic/assets/71184627/6feee848-da84-483b-8682-4d2b388f5fdb)
_After_

_Just for your information: the mockups were created by eye measurement. They are solely for demonstration purposes. Besides that note that the order of icons will eventually be adjustable manually at some point, so don't worry too much about it._

### Additional Context

Improving the navigation bar formatting and icon placement will contribute to a more polished and user-friendly interface. Consistency in design elements enhances brand identity and fosters positive user experiences.

**Comment by NikunjKhangwal** [comment]
Setting icon can be moved on top. No one uses settings daily after setting up once so it doesn't need to be in navigation bar.

**Comment by fast4x** [comment]
The bar is in development, it will be slightly larger, with slightly larger buttons and the search button will look like the original in ViMusic.

**Comment by fast4x** [comment]
> Setting icon can be moved on top. No one uses settings daily after setting up once so it doesn't need to be in navigation bar.

I’m trying to move it.

**Comment by NikunjKhangwal** [comment]
> the search button will look like the original in ViMusic.

Does that mean a floating search button even when you're using RiMusic interface?

**Comment by fast4x** [comment]
Yes I'm trying

**Comment by NikunjKhangwal** [comment]
I was just going to open a issue about it. This way we can remove search from nav bar as well making more space.
Very good decision 👌🏼

**Comment by dAtA-TRoN** [comment]
> Setting icon can be moved on top. No one uses settings daily after setting up once so it doesn't need to be in navigation bar.

I am 100% in favor of that.

**Comment by fast4x** [comment]
> I was just going to open a issue about it. This way we can remove search from nav bar as well making more space.
> Very good decision 👌🏼

Exactly, thanks.

Also I'm trying same logic with settings button...

**Comment by fast4x** [comment]
I also have a surprise, I’m trying a floating action bar... that could contain search, settings and more... activated with a long click... I really like the idea...

**Comment by dAtA-TRoN** [comment]
To fast4x: have you already received the new artist icon by @ikanakova? The current one is nothing less than terrible.

**Comment by dAtA-TRoN** [comment]
> I also have a surprise, I’m trying a floating action bar... that could contain search, settings and more... activated with a long click... I really like the idea...

![proxy-image.gif](https://github.com/fast4x/RiMusic/assets/71184627/2d77a1a4-2c6d-4f7f-975a-7c56e227af44)

Sounds very exciting to me.

**Comment by NikunjKhangwal** [comment]
Me too. Waiting to see how it turns out. 🤞🏼

**Comment by fast4x** [comment]
> To fast4x: have you already received the new artist icon by @ikanakova? The current one is nothing less than terrible.

oh oh I'm not sure, I'll check it..

**Comment by fast4x** [comment]
![giphy (2).gif](https://github.com/fast4x/RiMusic/assets/1484476/d5402dae-9df3-43c0-bcd5-2246a02ef0f2)

**Comment by fast4x** [comment]
Preview........

https://github.com/fast4x/RiMusic/assets/1484476/787ad815-183c-4df2-afd0-d4bfa486dbbd

**Comment by NikunjKhangwal** [comment]
> Preview........
This is actually pretty cool. Just one thing, new user wouldn't know settings is hidden behind search icon so you might need to add instructions

**Comment by dAtA-TRoN** [comment]
> Preview........

https://github.com/fast4x/RiMusic/assets/71184627/53d8a99b-7a7d-40a7-901f-be9f39b1ca0d

👏🏼😮

**Comment by sayyid5416** [comment]
That looks great.

Also add a setting to fix the icon in a specific position.

**Comment by fast4x** [comment]
![giphy (1)](https://github.com/fast4x/RiMusic/assets/1484476/16ba4e22-0754-4252-9248-9a91f9dac863)

**Comment by fast4x** [comment]
> > Preview........
> 
>  VID_20240408_025333_439.mp4 
> 😮👍🏼

![giphy (2)](https://github.com/fast4x/RiMusic/assets/1484476/6bde6811-cd32-4ad6-a84d-53fba6b39f94)

**Comment by fast4x** [comment]
Also added search in menu... 
Available from version 0.6.30

**Comment by NikunjKhangwal** [comment]
I agree with data-tron. Yes we can add search in navigation bar but adding extra button make it more cluttered, the same old argument. What you can do is keep the floating search button as it is now and add the extra action button above it (something like shown in picture). Currently action button will only contain settings but later you can extend the functionality of action button by adding more features like shuffle, loop, sleep timer & equalizer etc

![IMG_20240408_130233](https://github.com/fast4x/RiMusic/assets/99175083/c300819f-294a-42dc-b2f8-98c8fedc74e2)

**Comment by dAtA-TRoN** [comment]
> But... the user could get lost searching for settings. Now it has an action menu on any main page... Also you could add the search in the bar... then have two points for the search, one direct and one in the context

I would prefer it if you could make it optional: I find invoking the context menu by holding down the search button much more elegant. Having to tap twice to search feels like a step backward to me.

**Comment by NikunjKhangwal** [comment]
> Isn't necessary...
> 
>  Screen_recording_20240408_082030.mp4

I think he's talking about actual action button, not the sleep and search button. My suggestion is that make the action button movable by holding it, we'll move it where we want and it'll stay in the position after we release it. Dragging it like now has high chances of accidental touches.

**Comment by fast4x** [comment]
> I think he's talking about actual action button, not the sleep and search button. My suggestion is that make the action button movable by holding it, we'll move it where we want and it'll stay in the position after we release it. Dragging it like now has high chances of accidental touches.

Holding it can only be used to move or just to open if I have to keep single click as a direct search action..

**Comment by fast4x** [comment]
> > But... the user could get lost searching for settings. Now it has an action menu on any main page... Also you could add the search in the bar... then have two points for the search, one direct and one in the context
> 
> I would prefer it if you could make it optional: I find invoking the context menu by holding down the search button much more elegant. Having to tap twice to search feels like a step backward to me.

What optional...?

**Comment by fast4x** [comment]
> I agree with data-tron. Yes we can add search in navigation bar but adding extra button make it more cluttered, the same old argument. What you can do is keep the floating search button as it is now and add the extra action button above it (something like shown in picture). Currently action button will only contain settings but later you can extend the functionality of action button by adding more features like shuffle, loop, sleep timer & equalizer etc
> 
> ![IMG_20240408_130233](https://private-user-images.githubusercontent.com/99175083/320393667-c300819f-294a-42dc-b2f8-98c8fedc74e2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjMxNDksIm5iZiI6MTcxMjU2Mjg0OSwicGF0aCI6Ii85OTE3NTA4My8zMjAzOTM2NjctYzMwMDgxOWYtMjk0YS00MmRjLWIyZjgtOThjOGZlZGM3NGUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA3NTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNTRlMTI2NzFkMmM0NDYzODgzOTViZGY1NzNjMjQ0N2M3MTQyZTNlNWRhNGI1YTIxMTEzN2Q4Y2JjZTczZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXJODEqmzeL682RdaSDul7znShUvLnyBaFCmslGyezU)

i don't like...

**Comment by dAtA-TRoN** [comment]
Off topic: Look what I have here, a RiMusic wallpaper 😂...

![sketch1712389686503.png](https://github.com/fast4x/RiMusic/assets/71184627/db02c2aa-2992-4e0c-9bfc-d4bb7de157a9)

**Comment by NikunjKhangwal** [comment]
> Holding it can only be used to move

That's what i meant to say. Holding it only for positioning. Using it for search or settings will be still a single click

**Comment by fast4x** [comment]
Now

- single click open/close action menu
- long press move it
- added search icon in menu

It's a good compromise...

https://github.com/fast4x/RiMusic/assets/1484476/139f0af9-10b5-4824-8ea8-867fbe90b0b1

**Comment by fast4x** [comment]
I like much icon only navigation bar, it's beautifulll for me... Unlike many other apps...
![Screenshot_20240408_102218](https://github.com/fast4x/RiMusic/assets/1484476/6f26bd39-a22e-42cb-b983-fac4a3e15328)

**Comment by NikunjKhangwal** [comment]
> * single click open/close action menu
> * long press move it
> * added search icon in menu

Better than before. Also enable/disable in navigation bar already exist in settings. What do you mean by search icon in menu?

**Comment by fast4x** [comment]
> Better than before. Also enable/disable in navigation bar already exist in settings. What do you mean by search icon in menu?

Summing up... nothing new

**Comment by dAtA-TRoN** [comment]
> It's a good compromise...

But then the search functionality would be duplicated. Why not consider adding an option to put the settings icon into the navigation bar instead of the search button, so we could have a floating search button? That would be a compromise I could live with. I just need a floating search button 😭...

**Comment by fast4x** [comment]
@ikanakova icons have same size in app, but it show with padding like artists... can you look?

**Comment by fast4x** [comment]
> > It's a good compromise...
> 
> But then the search functionality would be duplicated. Why not consider adding an option to put the settings icon into the navigation bar instead of the search button, so we could have a floating search button? That would be a compromise I could live with. I just need a floating search button 😭...

But why do you want this mobile search button?
Don’t you think that the mobile menu can serve for much more beautiful functions? ahahahahah

**Comment by fast4x** [comment]
![giphy (3)](https://github.com/fast4x/RiMusic/assets/1484476/34567bd2-d959-48e4-819f-54ed5f706c90)

**Comment by dAtA-TRoN** [comment]
Listen up! The way you initially showed it was freaking awesome! Why not have the magnifying glass icon right on the button for search, and add a tiny extra symbol to hint the context menu? Or we could have an animation where holding down the magnifying glass draws a circle around it, to hint that there's more to it. Or how about a little arrow symbol above the magnifying glass? There's gotta be a way to make this happen! 😱 AHHHHHHHHHHRRRRRRGGGHHhhhhh...

**Comment by fast4x** [comment]
> > But why do you want this mobile search button?
> > Don’t you think that the mobile menu can serve for much more beautiful functions? ahahahahah
> 
> Listen up! The way you initially showed it was freaking awesome! Why not have the magnifying glass icon right on the button for search, and add a tiny extra symbol to hint the context menu? Or we could have an animation where holding down the magnifying glass draws a circle around it, to hint that there's more to it. Or how about a little arrow symbol above the magnifying glass? There's gotta be a way to make this happen! I bet you can smell my desperation 😱 AHHHHHHHHHHRRRRRRGGGHHhhhhh...

Okay, it’s official, I’m going crazy, and they’re going to admit me to a clinic, you’re going to visit me now and then? ahahahahahahah

Ok I will try to bring to the next level this amazing new floating menu icon....

**Comment by fast4x** [comment]
Done.


https://github.com/fast4x/RiMusic/assets/1484476/c5f302d0-e51e-4a74-a20c-d3e07c6aaaf4

**Comment by dAtA-TRoN** [comment]
> Okay, it’s official, I’m going crazy, and they’re going to admit me to a clinic, you’re going to visit me now and then? ahahahahahahah\n\nOk I will try to bring to the next level this amazing new floating menu icon....

Bro, sorry for bugging you about this, but hiding the search in a menu is seriously not cool. It doesn't make any sense since it's something we need so often. It's totally different with the settings button. It's fine if it's a bit more inconvenient to access since it's not something we use every few minutes. And yeah, give me the hospital address, I'll even bring flowers with me 💐😂.

**Comment by sayyid5416** [comment]
Looks nice. Will this search icon be shown in all places?

**Comment by NikunjKhangwal** [comment]
So can we now have my idea of adding more options behind this button in future?

**Comment by fast4x** [comment]
> Looks nice. Will this search icon be shown in all places?

In theory yes

**Comment by fast4x** [comment]
Now... added mini icon settings...
long press show menu, single execute single action... in this case search...

https://github.com/fast4x/RiMusic/assets/1484476/4ae6df24-0dea-4582-a05d-66e01705855e

**Comment by dAtA-TRoN** [comment]
> Now... added mini icon settings...
> long press show menu, single execute single action... in this case search...

😱😱😱 F***ING PERFECT!!!

**Comment by sayyid5416** [comment]
I think a white dot in place of setting icon will look simpler and better. Can you try it?

**Comment by dAtA-TRoN** [comment]
> I think a white dot in place of setting icon will look simpler and better. Can you try it?

But a white dot is not exactly the best clue. It could certainly be prettier than it is now, but in the Android world a dot represents a message that has not yet been read.

**Comment by dAtA-TRoN** [comment]
> I think a white dot in place of setting icon will look simpler and better. Can you try it?

But a white dot is not exactly the best clue. It could certainly be prettier than it is now, but in the Android world a dot represents a message that has not yet been read.

**Comment by dAtA-TRoN** [comment]
> So? Maybe settings is much nice
> ![Screenshot_20240408_113057](https://github.com/fast4x/RiMusic/assets/1484476/94bef4f1-371a-4d40-b4b9-e129b409fd4b)
> 

Looks better, I agree. BUT again: android uses dots to hint at temporary notifications and events. As soon as these are done, it disappears again. I think a white dot is not the right design language.

**Comment by fast4x** [comment]
> > So? Maybe settings is much nice
> 
> Looks better, I agree. BUT again: android uses dots to hint at temporary notifications and events. As soon as these are done, it disappears again. I think a dot is not the right design language.

I agree

**Comment by sayyid5416** [comment]
Yeah, you are right, dot represents something 'which needs attention'. We should try something else.

**Comment by dAtA-TRoN** [comment]
Why not color a corner of the app icon and overlay the settings symbol within it? That would help to differentiate it a bit more.

**Comment by NikunjKhangwal** [comment]
How about?

![Picsart_24-04-08_15-11-01-140](https://github.com/fast4x/RiMusic/assets/99175083/43f56ba6-e69d-4503-b2e4-e663d1fd71c3)

**Comment by fast4x** [comment]
> How about?
> 
> ![Picsart_24-04-08_15-11-01-140](https://private-user-images.githubusercontent.com/99175083/320432161-43f56ba6-e69d-4503-b2e4-e663d1fd71c3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1Njk2MDgsIm5iZiI6MTcxMjU2OTMwOCwicGF0aCI6Ii85OTE3NTA4My8zMjA0MzIxNjEtNDNmNTZiYTYtZTY5ZC00NTAzLWIyZTQtZTY2M2QxZmQ3MWMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA5NDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MGMwMTFkOGY1ZTljNzA3ODc4MmZiNDIwYTdmZTdhNjNhNTIwNzc4N2U0NjEyOTA2MWUzOWMxMzUzMTQ0NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zGehS18YfaoqbcxluUiVCs_5LSZXEFfmd2U0U2Wivyg)

i don't like

**Comment by NikunjKhangwal** [comment]
> i don't like

That's fine, your choice

**Comment by sayyid5416** [comment]
![image](https://github.com/fast4x/RiMusic/assets/78584556/f9f67495-9d38-47e5-b149-e8d2f501827a)

Looks bad I guess lol 😂

**Comment by fast4x** [comment]
![2024-04-08_11h46_38](https://github.com/fast4x/RiMusic/assets/1484476/4cb9d2f9-2851-4eb2-b6aa-0f31d3605f2e)

for me... this it's good choice... and compromise....

**Comment by sayyid5416** [comment]
> ![2024-04-08_11h46_38](https://private-user-images.githubusercontent.com/1484476/320433800-4cb9d2f9-2851-4eb2-b6aa-0f31d3605f2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1Njk5ODksIm5iZiI6MTcxMjU2OTY4OSwicGF0aCI6Ii8xNDg0NDc2LzMyMDQzMzgwMC00Y2I5ZDJmOS0yODUxLTRlYjItYjZhYS0wZjMxZDM2MDVmMmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMDk0ODA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzg2YmFiN2UwNDc3NmE2NjZhNDVjZDZiZDI2ZGZhMDFmNjEzYzU2ZmI2OWZiMjBkMWViMWYwZWZhZTU4ZDY3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RhgwZLPkHM_Cgp_wS9tgK-6s213A2gqMEGxCpCr82vM)
> 
> for me... this it's good choice... and compromise....

Yeah, its better than all the current ideas.

**Comment by sayyid5416** [comment]
maybe try fading that setting icon?

**Comment by dAtA-TRoN** [comment]
Why not something like this? Maybe smaller and better rounded, but I think you get what I'm getting at.

![sketch1712569916790.png](https://github.com/fast4x/RiMusic/assets/71184627/57aef1d2-2c9f-4968-bd7f-2919ad3ef0e3)

**Comment by sayyid5416** [comment]
![EeeeeeYikesGIF](https://github.com/fast4x/RiMusic/assets/78584556/869845e8-0c11-47b2-b2db-2d83b6335602)

sorry lol

**Comment by fast4x** [comment]
> Why not something like this? Maybe smaller and better rounded, but I think you get what I'm getting at.
> 
> ![sketch1712569916790.png](https://private-user-images.githubusercontent.com/71184627/320435987-57aef1d2-2c9f-4968-bd7f-2919ad3ef0e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzAzMDcsIm5iZiI6MTcxMjU3MDAwNywicGF0aCI6Ii83MTE4NDYyNy8zMjA0MzU5ODctNTdhZWYxZDItMmM5Zi00OTY4LWJkN2YtMjkxOWFkM2VmMGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA5NTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZjExNjdkMDIwODJmNTg4MjM3NjU4OWU5NzllOTQ2MzA3YjFkY2VmNjJjYzc5YWY3MzQ5YmQ2MTBlYzc4ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bsQkJsDWMHcdFwyliFPNHC_xu6PPYX_b4veVYEu3Wf0)
![giphy (4)](https://github.com/fast4x/RiMusic/assets/1484476/d9faae62-2256-4c6a-858a-f1b80b8eca90)

**Comment by dAtA-TRoN** [comment]
> ![EeeeeeYikesGIF](https://github.com/fast4x/RiMusic/assets/78584556/869845e8-0c11-47b2-b2db-2d83b6335602)
> 
> sorry lol

Ich finde es gut, da es das Zahnrad farblich absetzt von der Lupe. Wie gesagt, das war so auch nicht final. Nur eine Idee wie man es machen könnte.

**Comment by dAtA-TRoN** [comment]
> sorry lol

![proxy-image.gif](https://github.com/fast4x/RiMusic/assets/71184627/8ef8da48-48b2-4c73-9930-496a15f77889)

I think it's good because it visually contrasts the gear from the magnifying glass. As I said, that wasn't final either. Just an idea of how it could be done.

**Comment by NikunjKhangwal** [comment]
You mean?

![Picsart_24-04-08_15-36-18-684](https://github.com/fast4x/RiMusic/assets/99175083/2a4e8f24-18f8-46d4-bfaf-7089d6fda352)

**Comment by dAtA-TRoN** [comment]
> I think fading the gear icon could work _(in icon of fast4x )_

So let's see your mockup on this topic...

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/4109885e-2579-4094-bec7-7d873b29bb46)

**Comment by dAtA-TRoN** [comment]
> We don’t complicate things much...

So just do it your way -done!

**Comment by fast4x** [comment]
> > We don’t complicate things much...
> 
> So just do it your way -done!

Not in my way, we shared ideas

**Comment by sayyid5416** [comment]
### With 50% opacity
![a](https://github.com/fast4x/RiMusic/assets/78584556/85e44fea-16e4-486d-9bdf-0aed53c9802d)

<br>
OR
<br>

### With -100 brightness
![b](https://github.com/fast4x/RiMusic/assets/78584556/15cd35c9-b549-4156-b3d4-3450cb5386c1)

**Comment by dAtA-TRoN** [comment]
> Not in my way, we shared ideas

But you should ultimately decide what makes sense. Personally, I thought it was OK at the beginning.

**Comment by fast4x** [comment]
And it was actually done...

**Comment by fast4x** [comment]
> ### With 50% opacity
> ![a](https://private-user-images.githubusercontent.com/78584556/320444971-85e44fea-16e4-486d-9bdf-0aed53c9802d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzI1NzYsIm5iZiI6MTcxMjU3MjI3NiwicGF0aCI6Ii83ODU4NDU1Ni8zMjA0NDQ5NzEtODVlNDRmZWEtMTZlNC00ODZkLTliZGYtMGFlZDUzYzk4MDJkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEwMzExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZmZkY2ViOWE5ZTkxNTFiZThlYWE3ZGQxZTA1M2QyZDRjMmQwNGJmMjI1MGE3ZDMzODA1NTA4YWMyNDYzZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aTggUxQ6RQLHexWrrMcyjOZpCmJKB4NL_16QgOlvohA)
> 
> 
> OR
> ### With -100 brightness
> ![b](https://private-user-images.githubusercontent.com/78584556/320445308-15cd35c9-b549-4156-b3d4-3450cb5386c1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzI1NzYsIm5iZiI6MTcxMjU3MjI3NiwicGF0aCI6Ii83ODU4NDU1Ni8zMjA0NDUzMDgtMTVjZDM1YzktYjU0OS00MTU2LWIzZDQtMzQ1MGNiNTM4NmMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEwMzExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmOTU5YzNiODQ5MmU5MzFkOTc0Zjg1YzM0YjdkOTE5NDlhMWNlMTQyNGEzYjdiNmVlNmMyNDBlZWVmNDg1NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1LsMyX2lse1d5RwNMZKje6fOb3d8qX4lqEMJdAqHOpM)

The compromise for all ideas is white... which changes with the dynamic theme

**Comment by dAtA-TRoN** [comment]
![sketch1712572459536.png](https://github.com/fast4x/RiMusic/assets/71184627/1eb72a81-c4ff-4928-89ff-b36dba7c61ed)

🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣

**Comment by fast4x** [comment]
No OK I’ll go crazy 
![giphy (5)](https://github.com/fast4x/RiMusic/assets/1484476/21710964-b48f-4409-ae20-11a6e6ced8a5)

**Comment by sayyid5416** [comment]
> > ### With 50% opacity
> > ![a](https://private-user-images.githubusercontent.com/78584556/320444971-85e44fea-16e4-486d-9bdf-0aed53c9802d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzI1NzYsIm5iZiI6MTcxMjU3MjI3NiwicGF0aCI6Ii83ODU4NDU1Ni8zMjA0NDQ5NzEtODVlNDRmZWEtMTZlNC00ODZkLTNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZmZkY2ViOWE5ZTkxNTFiZThlYWE3ZGQxZTA1M2QyZDRjMmQwNGJmMjI1MGE3ZDMzODA1NTA4YWMyNDYzZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aTggUxQ6RQLHexWrrMcyjOZpCmJKB4NL_16QgOlvohA)
> > OR
> > ### With -100 brightness
> > ![b](https://private-user-images.githubusercontent.com/78584556/320445308-15cd35c9-b549-4156-b3d4-3450cb5386c1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzI1NzYsIm5iZiI6MTcxMjU3MjI3NiwicGF0aCI6Ii83ODU4NDU1Ni8zMjA0NDUzMDgtMTVjZDM1YzktYjU0OS00MTU2LWIzZDQtMzQ1MGNiNTM4NmMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDn0.1LsMyX2lse1d5RwNMZKje6fOb3d8qX4lqEMJdAqHOpM)
> 
> The compromise for all ideas is white... which changes with the dynamic theme

What do you mean by this I couldn't get you?

**Comment by dAtA-TRoN** [comment]
> No OK I’ll go crazy 

https://github.com/fast4x/RiMusic/assets/71184627/93a5f6d8-70a4-4670-b4d1-b409582f1ad0

**Comment by NightFly88** [comment]
> Je bedoelt?
> 
> ![Picsart_24-04-08_15-36-18-684](https://private-user-images.githubusercontent.com/99175083/320440150-2a4e8f24-18f8-46d4-bfaf-7089d6fda352.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MDE3ODcsIm5iZiI6MTcxMjYwMTQ4NywicGF0aCI6Ii85OTE3NTA4My8zMjA0NDAxNTAtMmE0ZThmMjQtMThmOC00NmQ0LWJmYWYtNzA4OWQ2ZmRhMzUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDE4MzgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYjZhMTQ3ODY3MmYwYTYwMTkxMTJmNGYwMjdiYjY2ZDZkYmI5ODllMGIyNWU3NjM3ZTAxMmU2OWEzNjExN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gIReMTm13mO09N1oqH971xkrsv9xWn2FJP3SSxBpXX0)

I love this

**Comment by sayyid5416** [comment]
> > ### With 50% opacity

> The compromise for all ideas is white... which changes with the dynamic theme

If you reduce opacity of gear icon programmatically, that icon would also react to changing dynamic theme.
