### ISSUE TITLE
[Feature]: Crossfade

### ISSUE THREAD

**Issue by farzana840** [fast4x/RiMusic#1421]
### Description

The Crossfade effect when switching from one song  to another is just bliss. 

### Suggested Solution

Would be great to have it rimusic

**Comment by KrisTamang** [comment]
Actually this might be useless cause artist/ mix & master put crossfade in most of the new song

**Comment by dAtA-TRoN** [comment]
Duplicate #980

**Comment by farzana840** [comment]
Ah sorry I'll close it

**Comment by farzana840** [comment]
.

**Comment by fast4x** [comment]
Implemented crossfade songs effect, available from version 0.6.34
