### ISSUE TITLE
Album art

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1424]
### Steps to reproduce the bug

Sorry to make this issue again but what is happening..!?

### Expected behavior

On offline mode i have downloaded songs and already loaded album art but..!

### Actual behavior

Load album art

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/107674915/58cb2b3e-9819-41a7-bdec-5a865f65ca05

### RiMusic version

0.6.29

### Android version

Android 13

**Comment by fast4x** [comment]
try to clean images cache please

**Comment by KrisTamang** [comment]
> try to clean images cache please

There is no option to clear only images..!

**Comment by fast4x** [comment]
Decrease to minimum, restart app increase size

**Comment by fast4x** [comment]
Implemented clear image cache by data settings, available from version 0.6.30

**Comment by KrisTamang** [comment]
> Implemented clear image cache by data settings, available from version 0.6.30

Instead of that ..
Please fix what is the problem i issued..!

**Comment by fast4x** [comment]
I can't reproduce your issue

**Comment by KrisTamang** [comment]
> I can't reproduce your issue

Briefly explanation of this issue is one song that album art isn't downloaded can cause others song album art not load properly..!
