### ISSUE TITLE
The texts of the buttons are mixed up

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#1426]
### Steps to reproduce the bug

1. Open the song
2. Tap cover to open the lyrics
3. Appears a message "synchronized lyrics are not available for this song" and a button "switch to synchronized lyrics" (same for unsynchronized)

https://github.com/fast4x/RiMusic/assets/76595855/660965de-e9a5-46ad-8270-4e24b32a0a67

### Expected behavior

Expected to see 
"synchronized lyrics are not available for this song" and a button "switch to **_unsynchronized_** lyrics"
and 
"unsynchronized lyrics are not available for this song" and a button "switch to **_synchronized_** lyrics"

### Actual behavior

Text on the buttons to switch to another type of lyrics are mixed up

### RiMusic version

0.6.29

### Android version

Android 13

### Additional information

Samsung Galaxy A51

**Comment by fast4x** [comment]
Fixed, available from version 0.6.30
