### ISSUE TITLE
Synchronized lyrics do not appear even if the lyrics exist in lrclib.net

### ISSUE THREAD

**Issue by AquamarineDreams** [fast4x/RiMusic#1433]
### Steps to reproduce the bug

Open synced lyrics of a music, I will use DARLING DANCE as an example.

### Expected behavior

Synced lyrics should work, because they exit at lrclib.net database. 
![IMG_20240407_212207](https://github.com/fast4x/RiMusic/assets/140275860/8845cdd8-695b-42cf-b291-835c6ff0c078)

### Actual behavior

They don't... 
![Screenshot_2024-04-07-21-14-33-942_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/140275860/6d66e6fd-3da3-451a-a89b-35e252e9193c)

### Screenshots/Screen recordings

At first I thought that the reason for that was because the app was searching for the translated title, which doesn't give any results 

![Img1](https://github.com/fast4x/RiMusic/assets/140275860/f2147b43-3847-4f7b-bba6-76f9f837cccf)

unlike the original title. 

![Img2](https://github.com/fast4x/RiMusic/assets/140275860/dfab1e8d-3ae6-4014-8372-894577197039)

But when I searched other musics (without a translated title) at lrclib.net, it showed results.

![Img3](https://github.com/fast4x/RiMusic/assets/140275860/ff4e5d01-5e6e-41c2-9372-8f28b5abf882)

I have no idea of why this is happening, so I reported it, since it is probably not intended. 

### RiMusic version

0.6.29

### Android version

Android 14

### Additional information

Btw, the synced lyrics are working perfectly fine in ViMusic

![Screenshot_2024-04-07-22-23-13-886_it vfsfitvnm vimusic](https://github.com/fast4x/RiMusic/assets/140275860/525fa41c-1148-4fd9-a493-83fe936932b4)

**Comment by AquamarineDreams** [comment]
Added additional information to the bug report

**Comment by fast4x** [comment]
Try to search with Pick..

**Comment by aneesh1122** [comment]
> Added additional information to the bug report

![Screenshot_2024-04-08-11-15-57-984_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/4775faaa-3c74-4671-9b7b-7c8153442767)
Working for me. Maybe something is wrong from your side

**Comment by AquamarineDreams** [comment]
It seems to be a problem in my end. It is somehow working now.

**Comment by AquamarineDreams** [comment]
Another example :D
30/04/14
App version 0.6.32 - latest
Android version: Android 14 - Xiaomi hyper OS

![IMG_20240430_222253](https://github.com/fast4x/RiMusic/assets/140275860/b7fe0a8f-b9d7-4e25-ba2e-d75614e8538c)

**Comment by aneesh1122** [comment]
My RiMusic couldn't find lyrics of both the songs either. It was able to find the lyrics of "Serenata Existencialista" in version 0.6.29 though so something definitely changed in this new version which is causing problems.

**Comment by AquamarineDreams** [comment]
> My RiMusic couldn't find lyrics of both the songs either. It was able to find the lyrics of "Serenata Existencialista" in version 0.6.29 though so something definitely changed in this new version which is causing problems.

I tried downloading version 0.6.29 to test if the lyrics would work. It didn't. Here's a video of me comparing both versions simultaneously.

https://github.com/fast4x/RiMusic/assets/140275860/8ac28c60-e3d0-491c-93ea-fded1c2ba3d1

Whatever is causing this issue, it isn't only on the newer versions

**Comment by aneesh1122** [comment]
> > My RiMusic couldn't find lyrics of both the songs either. It was able to find the lyrics of "Serenata Existencialista" in version 0.6.29 though so something definitely changed in this new version which is causing problems.
> 
> I tried downloading version 0.6.29 to test if the lyrics would work. It didn't. Here's a video of me comparing both versions simultaneously.
> 
> https://github.com/fast4x/RiMusic/assets/140275860/8ac28c60-e3d0-491c-93ea-fded1c2ba3d1
> 
> Whatever is causing this issue, it isn't only on the newer versions

Lrclib must have changed something then. The temporary workaround would be to let us search songs manually in lrclib within RiMusic

**Comment by AquamarineDreams** [comment]
I mean... If you want to, you can always manually copy and paste the lyrics from lrclib.net

https://github.com/fast4x/RiMusic/assets/140275860/4cd21dc2-fdd0-440d-b06c-da1b50415665

**Comment by aneesh1122** [comment]
> I mean... If you want to, you can always manually copy and paste the lyrics from lrclib.net
> 
> https://github.com/fast4x/RiMusic/assets/140275860/4cd21dc2-fdd0-440d-b06c-da1b50415665

Yeah but it would be quicker to search within app.

Also, RiMusic doesn't save lyrics. It keeps them in cache which will be removed automatically and you'll have to repeat the process.

I still don't know why RiMusic doesn't download lyrics.

**Comment by AquamarineDreams** [comment]
Yeah, that's exactly what we are reporting here and at #1675 . The search within the app isn't working. They don't need to implement a search within the app, because they already did. It just isn't working.

The workaround is to manually copy and paste the lyrics.

I also think that when you download a music it should download the cover and the lyrics too, instead of storing in cache.

Someone already suggested this #1684, so we just need to wait for them to implement it or not.

**Comment by aneesh1122** [comment]
> Yeah, that's exactly what we are reporting here and at #1675 . The search within the app isn't working. They don't need to implement a search within the app, because they already did. It just isn't working.
> 
> The workaround is to manually copy and paste the lyrics.
> 
> I also think that when you download a music it should download the cover and the lyrics too, instead of storing in cache.
> 
> Someone already suggested this #1684, so we just need to wait for them to implement it or not.

I was thinking of something like this
![Screenshot_2024-05-01-21-49-33-047_com.msob7y.namida-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/9b2ec461-0475-48fa-bba3-7e7f480e1810)

**Comment by AquamarineDreams** [comment]
Oh, I see. This would even be better than the search method currently implemented in the app. It would be very useful for those situations where the name of the song is slightly different from the one present on lrclib.net

You should suggest it on a new "issue report", they may implement it on a future update

**Comment by aneesh1122** [comment]
#1720

**Comment by fast4x** [comment]
Reproduced, ill fix it, thanks

**Comment by fast4x** [comment]
Fixed, available from version 0.6.33
