### ISSUE TITLE
Part of Quick picks stays at loading screen forever

### ISSUE THREAD

**Issue by felissedano** [fast4x/RiMusic#1434]
### Steps to reproduce the bug

Opening the Quick picks section only loads 3 rows of songs and the rest stays at loading screen. Restarting the app or using a different network didn't help.

### Expected behavior

Quick picks loading everything shortly after app opened.

### Actual behavior

Quick picks only loads partially and stays at loading animation for at least 15+ min (gave up after)

### Screenshots/Screen recordings

![quickpicks-notload](https://github.com/fast4x/RiMusic/assets/109383955/b369b28e-7f82-447f-b1c2-807eff463fd5)

### RiMusic version

0.6.29

### Android version

Android 10

**Comment by fast4x** [comment]
![Screenshot_2024-04-08-07-43-55-518_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/d735e072-4d7c-4ae0-afca-5a95a0104e39)

I'm sorry but it work for me
