### ISSUE TITLE
Player issue

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#1435]
### Steps to reproduce the bug

The bar is duplicated on top see screenshot

### Expected behavior

This should be there no?

### Actual behavior

The bar is duplicated on top

### Screenshots/Screen recordings

![Screenshot_2024-04-08-07-58-12-378-edit_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/4f5cdba6-1d5e-425e-bdc0-4deea4d4862b)

### RiMusic version

0.6.29

### Android version

A12 MIUI 14

**Comment by fast4x** [comment]
It's a feature,,,

**Comment by NEVARLeVrai** [comment]
> It's a feature,,,

I'm sorry but this look ugly on top 😅

**Comment by fast4x** [comment]
You are a first... remove it?

**Comment by NEVARLeVrai** [comment]
> You are a first... remove it?

Maybe only one who noticed maybe can u put a toggle to display this ?

**Comment by fast4x** [comment]
Other toggle for this isn't make sense... removed...
Available from version 0.6.30

**Comment by fast4x** [comment]
but no quiet is good, also i don't like it, removed.
