### ISSUE TITLE
Move statistic back to Navbar

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#1438]
### Description

Im looking for it, it's gone
Turns out _hidden_ inside **Library**

### Suggested Solution

Move statistic to Navbar (original position)

**Comment by fast4x** [comment]
Takes space, can I make it actionable from settings, what type of navigation bar do you use?
Top, bottom, left or right?
and you use only icon o mixed...?

**Comment by fast4x** [comment]
Ok will be enabled/disabled from settings

**Comment by faustaahmad** [comment]
> Takes space, can I make it actionable from settings, what type of navigation bar do you use? Top, bottom, left or right? and you use only icon o mixed...?

Do as you like, Im okay with anything
Still... if it's similar to "move search to navbar" options, would looks wierd due not respect "Navbar style" options (icon only or with text)

**Comment by fast4x** [comment]
in new version it's ok like dimensions

**Comment by dAtA-TRoN** [comment]
Just a general observation. I think people should have complete control over the nav bar. Being able to swap out, activate, or deactivate all icons as desired. They should also be able to determine the order themselves. But I believe that's already in planning anyway 🤔.

**Comment by dAtA-TRoN** [comment]
> Maybe create a new issue regarding that?

I don't think it's necessary. He most likely has already read it, and he's in the process of completely rebuilding the nav bar anyway. Therefore, I suggest we just wait and be surprised 🙂.

**Comment by dAtA-TRoN** [comment]
> > > Maybe create a new issue regarding that?
> > 
> > I don't think it's necessary. He most likely has already read it, and he's in the process of completely rebuilding the nav bar anyway. Therefore, I suggest we just wait and be surprised 🙂.
> 
> Yeah. But I think there being a separate issue about that might help him more with that? Though not sure if he actually needs that. I'm just saying.
> Waiting is good.

If you'd like, you can go ahead and submit a corresponding request. I'm a bit too lazy for that right now 😅.

**Comment by dAtA-TRoN** [comment]
> I'm lazy as well recently…I ain't even creating issue for the 164749 ideas I have in my mind 💀

Yes, I feel the same way. However, fast4x likely already has enough on his bucket list to fill two lifetimes by now.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.30

**Comment by sayyid5416** [comment]
> > I believe individuals should have full control over the navigation bar, allowing them to swap, activate, or deactivate icons as they see fit. They should also be able to arrange the icons in their preferred order. But I think you already had that on your radar 🤔.
> 
> Maybe create a new issue regarding that?

There is something similar in here #852
