### ISSUE TITLE
[Feature]: replacement of music search button

### ISSUE THREAD

**Issue by kris20030705** [fast4x/RiMusic#1440]
### Description

![Screenshot_20240408-181119_RiMusic~2](https://github.com/fast4x/RiMusic/assets/107674915/3b3f6028-fc32-4c72-af84-eadec1b7618e)

### Suggested Solution

Small search button for downloaded or available songs..!
And please add button to show 'on device music"
there .!
Btw whats that 
![Screenshot_20240408-181119_RiMusic~3](https://github.com/fast4x/RiMusic/assets/107674915/1a593c20-b009-49a2-bbc8-0a0b2a4b7932)

**Comment by dAtA-TRoN** [comment]
> As far as I remember fast4x said this button is for showing "on device" music.

Finally an answer to this riddle.

**Comment by fast4x** [comment]
> And please add button to show 'on device music"
there .!

is present in home songs...

**Comment by dAtA-TRoN** [comment]
Once this RiMusic is completed, it will be the swiss army knife of music streaming applications 💪🏼.

**Comment by KrisTamang** [comment]
Maybe they should put there shortcut icon to access on device music

**Comment by fast4x** [comment]
Every song you listen to, including the songs on your device, is included in the songs list at home. The button is used to show or hide from the list the local songs that are those present in the device (example MP3 downloaded from other apps or added from se card)

**Comment by fast4x** [comment]
> Maybe they should put there shortcut icon to access on device music

Shortcut is a duplicate action, can go in library clicking navigation bar.

**Comment by KrisTamang** [comment]
> > Maybe they should put there shortcut icon to access on device music
> 
> I'm now unsure what YOU mean by "on device music"

![Screenshot_20240409-002843_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/038c3894-0d20-4648-82c3-883917905fac)

**Comment by KrisTamang** [comment]
> Every song you listen to, including the songs on your device, is included in the songs list at home. The button is used to show or hide from the list the local songs that are those present in the device (example MP3 downloaded from other apps or added from se card)

I think its not showing..!
![20240409_003250-COLLAGE](https://github.com/fast4x/RiMusic/assets/107674915/c04be651-e574-4583-8607-b109025ca947)
I have over 300 songs..!

**Comment by fast4x** [comment]
> > Every song you listen to, including the songs on your device, is included in the songs list at home. The button is used to show or hide from the list the local songs that are those present in the device (example MP3 downloaded from other apps or added from se card)
> 
> I think its not showing..!
> ![20240409_003250-COLLAGE](https://github.com/fast4x/RiMusic/assets/107674915/c04be651-e574-4583-8607-b109025ca947)
> I have over 300 songs..!

You see them as you listen to them with RiMusic...

**Comment by dAtA-TRoN** [comment]
So is it the same as a song history?

**Comment by KrisTamang** [comment]
> > > Every song you listen to, including the songs on your device, is included in the songs list at home. The button is used to show or hide from the list the local songs that are those present in the device (example MP3 downloaded from other apps or added from se card)
> > 
> > 
> > I think its not showing..!
> > ![20240409_003250-COLLAGE](https://private-user-images.githubusercontent.com/107674915/320616883-c04be651-e574-4583-8607-b109025ca947.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MDM3NzgsIm5iZiI6MTcxMjYwMzQ3OCwicGF0aCI6Ii8xMDc2NzQ5MTUvMzIwNjE2ODgzLWMwNGJlNjUxLWU1NzQtNDU4My04NjA3LWIxMDkwMjVjYTk0Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxOTExMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2M2NWQ5NTM1MDFjOGU4YzA5MDJjNzI1OWZkYWVlYzcyNmQwZWViNmRjYzJjMWYwZTA4MDEwMzc0YjRiMGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kev2Sx1zLHG4L-IiejVDTAIQT06gSw5gZ1w70x9O7yw)
> > I have over 300 songs..!
> 
> You see them as you listen to them with RiMusic...

Its will be really cool if that icon only shows on device..!
