### ISSUE TITLE
[Feature]: Disable background progress bar

### ISSUE THREAD

**Issue by silvasch** [fast4x/RiMusic#1441]
### Description

Currently, there is no way to actually disable the background progress bar. You can only select "Minimized", "Player" and "Both". However, I would like to disable this behavior completely.

### Suggested Solution

Add an option to this setting called "Disabled" to completely disable the background progress bar.

**Comment by silvasch** [comment]
I quickly implemented this in a branch, and it is ready. I could immediately open a pull request.

**Comment by fast4x** [comment]
This is just implemented, in ui settings can select what type of progress bar do you want.

**Comment by silvasch** [comment]
Ok. Do you want to merge your implementation?

**Comment by fast4x** [comment]
But you want disable completly progress bar? os by player or miniplayer?

**Comment by fast4x** [comment]
Implemented, available from version 0.6.30

**Comment by silvasch** [comment]
I only want to disable the background progress bars:

![Screenshot_20240408-184641~2](https://github.com/fast4x/RiMusic/assets/128063006/3cee360c-40f9-4899-9ada-e7c75eea556b)
![Screenshot_20240408-184730~2](https://github.com/fast4x/RiMusic/assets/128063006/2e8d29f6-a865-4bd1-a492-02cad2bdfd08)

Currently, you can disable one of them, but not both of them.

**Comment by fast4x** [comment]
Ok, implemented
