### ISSUE TITLE
Adding playlist from youtube bug

### ISSUE THREAD

**Issue by sebbekm** [fast4x/RiMusic#1442]
### Steps to reproduce the bug

1. Go to 'youtube'
2. Open playlist
3. Click on 'share playlist'

### Expected behavior

I should be able to add the whole playlist.

### Actual behavior

When adding a playlist from youtube, only a part of the playlist can be added. (193 songs of 677)

### RiMusic version

0.6.29

### Android version

Android 13

### Additional information

I can add the whole playlist in similar apps (ViMusic, Innertune, SimpMusic, Harmony Music, Music You)

Here's the playlist:
https://youtube.com/playlist?list=PLJPgiltmVBUgFrORCH-wsIwb4-xl7atww&si=CCABalpoq2jGXtMX

It's not just that playlist though, other larger playlists has the same problem.

**Comment by aneesh1122** [comment]
[https://github.com/fast4x/RiMusic/issues/1334](url)

I'm facing the same problem

**Comment by aneesh1122** [comment]
#1334 

I'm facing the same problem

**Comment by fast4x** [comment]
Fixed, available from version 0.6.30

**Comment by fast4x** [comment]
There is still some problem but I will solve it, because it depends on some things being developed.
