### ISSUE TITLE
It looks stretched,some texts outside

### ISSUE THREAD

**Issue by NightFly88** [fast4x/RiMusic#1443]
### Steps to reproduce the bug

Since the last update with the new navigation bar see photo 

It looks stretched,some texts outside

Thanks

### Expected behavior

I hope Fix this problem 

### Actual behavior

Nvt

### Screenshots/Screen recordings

![Screenshot_20240408_211305](https://github.com/fast4x/RiMusic/assets/163666747/353a132b-df24-4eac-a1ca-87cd90ebb3a9)
![Screenshot_20240408_211313](https://github.com/fast4x/RiMusic/assets/163666747/41f65156-5b62-4a21-b67d-f26739008bc4)
![Screenshot_20240408_211238](https://github.com/fast4x/RiMusic/assets/163666747/04edbb8d-1716-4a4e-a380-8dc39d6c803e)

### RiMusic version

v0.6.29

### Android version

Android 14

**Comment by fast4x** [comment]
Hi, it has been improved in next version 0.6.30

**Comment by NightFly88** [comment]
Thank you
