### ISSUE TITLE
Playlist still shows on sidebar after turning off from library

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1444]
### Steps to reproduce the bug

1. Open "On device playlist"
2. Look at the sidebar.
3. See a playlist that shouldn't be visible.

### Expected behavior

Playlists that have been disabled to show on Library from setting shouldn't show.

### Actual behavior

"My top x" playlist still showing on the sidebar.

### Screenshots/Screen recordings

![Screenshot_20240409-010112](https://github.com/fast4x/RiMusic/assets/85461823/917e445f-9bcc-4eb2-8c5c-52870092b3a0)

### RiMusic version

0.6.29

### Android version

Android 11

**Comment by fast4x** [comment]
Fixed, available from version 0.6.30
