### ISSUE TITLE
add to queue but play it as next song

### ISSUE THREAD

**Issue by dzindra1** [fast4x/RiMusic#1447]
### Description

Would really liked if you could add something like play next song but it would stacked something like so when its playing random songs i would select multiple songs to play right after curent song.

### Suggested Solution

Basically option play next but they would play after eachother as i select them

**Comment by fast4x** [comment]
So, you want select position after inserting new queued songs..

**Comment by aneesh1122** [comment]
> So, you want select position after inserting new queued songs..

Instead of putting only one song to 'play next' he want to select multiple songs at once and put them in the 'play next'.

**Comment by aneesh1122** [comment]
Enquene puts selected songs at the end of the queue. He wants to add those selected songs just after the song which is currently playing.

**Comment by aneesh1122** [comment]
Something like this

1) Your queue
![1](https://github.com/fast4x/RiMusic/assets/45353488/935288a2-80dc-4501-9e1b-45cec56c0415)

2) you selected these 4 songs
![2](https://github.com/fast4x/RiMusic/assets/45353488/76977c3c-8079-4044-b535-db39d06cf61b)

3) you selected 'play next'
![3](https://github.com/fast4x/RiMusic/assets/45353488/8f1e2f9a-4448-4e52-9eb5-7b181258f3e3)

4) your final queue. the songs under red box are recently added songs which are just after currently playing song
![4](https://github.com/fast4x/RiMusic/assets/45353488/b1b3f257-4df5-4fd8-b7c6-a57e1aa58587)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.30
