### ISSUE TITLE
[Feature]: Music player for device music..!

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1448]
### Description

Just wanna request to make normal music player without YouTube api but with same looks and lyrics features..!
Btw RiMusic is pretty cool music player..!
But yt might make their api secure somedays and this app will be useless .
So, just how i used normal music player as my primary music player make this "RiMusic player" for on device only..!
I know we can use on device use in current version too but i am being specific for on device only with same features and looks..!
Thank you for reading so far and hope you got the point..!

### Suggested Solution

Music player only for on device music

**Comment by KrisTamang** [comment]
Music player that support mp3, m4a and ogg/opus..!

**Comment by cMattw** [comment]
this is more of a downgrade than an enhancement

**Comment by fast4x** [comment]
Hi, thanks for request but isn't planned.

**Comment by KrisTamang** [comment]
> this is more of a downgrade than an enhancement

Its not an enhancement but it can replace other music player as its looks is so cool.!

**Comment by NikunjKhangwal** [comment]
This is actually the most random issue I've seen here. Doesn't make sense tbh.
Btw you can try Namida if you want local player with many features & looks:-
https://github.com/namidaco/namida
