### ISSUE TITLE
Statistics are wrong

### ISSUE THREAD

**Issue by AquamarineDreams** [fast4x/RiMusic#1449]
### Issue

When I click that icon on my library to see my statistics, the list is completely wrong. The vast majority of the songs that I apparently listened to the most I just listened once.

![Screenshot_2024-04-08-20-10-49-210_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/140275860/a61fc2c5-a7ee-46ec-b6e7-218eee3c72c6)

![Screenshot_2024-04-08-20-07-43-903_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/140275860/adff3737-76dd-4918-82e2-a81becf835c7)

The top 10 seems about right though.

![Screenshot_2024-04-08-20-08-03-683_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/140275860/dd6bcd29-dbf5-4317-af00-8d20a99c4b95)

It matches the listening time for each music

![Screenshot_2024-04-08-21-24-14-056_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/140275860/b994cbbb-2ffa-406d-a9b7-1b6a8cd96350)

As you can see from my rather questionable musical taste, the most listened to stats are wrong when you compare it to the listening time of each song 

### RiMusic version

0.6.29

### Android version

Android 14

**Comment by AquamarineDreams** [comment]
All songs in the "most played of all time" menu I just listened once

**Comment by AquamarineDreams** [comment]
I don't really know if it's working as intended or not. I don't really get it

**Comment by AquamarineDreams** [comment]
Or the most recently listened songs

**Comment by dAtA-TRoN** [comment]
#1406

**Comment by fast4x** [comment]
Is your top 10 correct in your opinion?

**Comment by fast4x** [comment]
General songs list in home, it cannot be compared to the rest because it makes a simple mechanical sorting of the songs.

**Comment by AquamarineDreams** [comment]
I said I didn't really understand how statistics work. But, it doesn't seem right that a song I've only listened to once, and some songs I haven't even finished listening to, appear in the 'most listened to of all time' tab.

Could you explain what the parameters are for a song to appear in the statistics?

**Comment by AquamarineDreams** [comment]
Yes, the top 10 seems to be correct.

**Comment by 5wHN28Dg** [comment]
I can report this too, the statistics are wrong, I have listened to these songs only once and it was yesterday!
![Screenshot_20240420_205157](https://github.com/fast4x/RiMusic/assets/109148083/0a774793-6808-4a7d-95e0-8ca6e64eb835)

**Comment by AquamarineDreams** [comment]
Any updates on this?

**Comment by 5wHN28Dg** [comment]
> Any updates on this?

It seems there is as the daily, weekly, monthly statistics are not identical anymore, they aren't correct but...

**Comment by AquamarineDreams** [comment]
Yeah, they are still by 'recently heard', instead of 'most listened to'. Probably they are not going to fix this, unfortunately

**Comment by aneesh1122** [comment]
Hey @fast4x I'm also facing this problem. "Most played songs" shows the songs I recently heard.

"My top X" is working fine though
