### ISSUE TITLE
After new update, if ive listened to 1 or 2 songs in an album...all the songs of the album are showing in "songs" section

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#145]
### Steps to reproduce the bug

Listen to a song from an album
Then check "songs" section
All the songs in the albums getting added in the "songs" section

### Expected behavior

"songs" section should only show songs which ive listened to

### Actual behavior

It is showing all the songs from the album even if ive not listened to it

### Screenshots/Screen recordings

![image](https://github.com/fast4x/RiMusic/assets/127825700/36fd4e23-a501-402e-83de-46bfea527f37)
![image](https://github.com/fast4x/RiMusic/assets/127825700/df58175e-8b14-4c0b-9575-d54345dc6c55)
![image](https://github.com/fast4x/RiMusic/assets/127825700/988d56d0-5d05-4e83-8260-532ae16a45b7)

### RiMusic version

v0.6.10.1

### Android version

android 11

**Comment by fast4x** [comment]
Bug confirmed, fixing.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.11

**Comment by dainvincible1** [comment]
> Fixed, available from version 0.6.11

thanks
