### ISSUE TITLE
Introduce "Incognito Mode" for RiMusic's Statistics and (hopefully upcoming 😅?) Listening History

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1451]
### Description

This feature proposes adding an "Incognito Mode", allowing users to temporarily suspend the recording of both their listening habits statistics and their Listening History. The mode serves multiple purposes, including enabling users to enjoy their guilty pleasures without affecting their statistics and allowing others to play music from the same device without impacting personal statistics or the Listening History. When activated, Incognito Mode suspends the recording of statistics related to the user's listening activity and disables the Listening History feature.

### Suggested Solution

1. Implement a toggle switch within RiMusic's settings labeled "Incognito Mode."

2. When activated, this mode temporarily suspends the recording of statistics related to the user's listening activity and disables the Listening History feature.Provide two options for users:
**2.1 Immediate Control:** A simple on/off toggle switch for instant activation and deactivation of Incognito Mode.
**2.2 Session-based Control:** A setting to disable statistics recording and Listening History until the next restart of RiMusic, providing users with a more flexible approach.

### Additional Context

1. This feature allows users to indulge in their guilty pleasures without affecting their listening statistics, maintaining a pristine record for their preferred genres and artists.

2. Incognito Mode also enables users to share their music-playing device with others without worrying about their personal statistics or Listening History being influenced.

**Comment by aneesh1122** [comment]
Incognito mode? But this is a music app 😂

**Comment by dAtA-TRoN** [comment]
> Incognito mode? But this is a music app 😂

But I have provided reasons why this is beneficial 😛.

It's also possible to implement a local account system, enabling multiple users on the same device to have their own individual accounts. This prevents statistics, histories, and libraries from mixing together 🤔...

**Comment by aneesh1122** [comment]
> > Incognito mode? But this is a music app 😂
> 
> But I have provided reasons why this is beneficial 😛.
> 
> It's also possible to implement a local account system, enabling multiple users on the same device to have their own individual accounts. This prevents statistics, histories, and libraries from mixing together 🤔...

I don't think this app should be cluttered with so many not-so-essential options. The goal of this app is to be simple and user friendly. 

Btw you can always clone this app.

**Comment by dAtA-TRoN** [comment]
> not-so-essential

Even Spotify has something like that. It's not as edgy as you think.

> Btw you can always clone this app.

So, why aren't you the one creating your own minimalist version of RiMusic? I'm offering suggestions here, just like everyone else. Some of these suggestions will be approved and accepted, while others may not. However, I don't believe you have the ultimate decision-making authority in this matter.

**Comment by ikanakova** [comment]
I agree with @aneesh1122 on this one I don't think it's a good idea to overwhelm fast4x with requests. Especially when we know he's trying to comply most everything. And it seems to me that 99% of the requests here are written by like 3 people 🤣

**Comment by aneesh1122** [comment]
> Even Spotify has something like that. So it's not as 'edgy' as you might think.

Well, Spotify is a huge audio streaming service which does basic things right whereas RiMusic is an open source non-funding project which still needs some work to fix some basic things. Can't really compare them now, can we?

> Oh, is that so? Why aren't you then the one of us two creating your own minimalist version of RiMusic, hm?
C'mon man. Go to play store and download any app cloner and clone this app and use that one as incognito. This is all it takes.

Should he work on improving basic features or adding these advance features which you can easily achieve by cloning this app?

> However, I don't believe you have the ultimate decision-making authority in this matter. Deal with it.

I politely gave you a very logical solution to your problem but here you are talking like that. Don't get angry and take out your frustrations on random strangers on internet. Go out of your basement and meet new people and have some social life. Don't wake up everyday only to post new issues for RiMusic. Get a life.

**Comment by sayyid5416** [comment]
I agree with @aneesh1122

This feature is really not necessary in my opinion, but maybe in a long future when we have ability to login to the app 🤷‍♂️

**Comment by dAtA-TRoN** [comment]
> Especially when we know he's trying to comply most everything.

Fast4x is perfectly capable of speaking for himself as an adult. I trust his ability to assess and discern suggestions effectively.

>And it seems to me that 99% of the requests here are written by like 3 people 🤣

You can't fault those enigmatic three individuals you're referring to for having more ideas than the remaining 99%. However, it's true that not everyone is inclined to ponder deeply 😏.

**Comment by dAtA-TRoN** [comment]
> I agree with @aneesh1122
> 
> This feature is really not necessary in my opinion, but maybe in a long future when we have ability to login to the app 🤷‍♂️

Fair.

**Comment by fast4x** [comment]
#290

**Comment by ikanakova** [comment]
> You can't fault those enigmatic three individuals you're referring to for having more ideas than the remaining 99%.

I have a lot of ideas, but I always try to tell myself first: 1. do I really need this? and 2. can't I set it up differently? And in the meantime, someone else will request for it 🤣 And if they don't, I know no one else wants it but me...

> However, it's true that not everyone is inclined to ponder deeply 😏.

We all think differently and therefore want different things, and a lot of people are happy with what they have and don't request for more features because they like simple things.

**Comment by dAtA-TRoN** [comment]
> > You can't fault those enigmatic three individuals you're referring to for having more ideas than the remaining 99%.
> 
> I have a lot of ideas, but I always try to tell myself first: 1. do I really need this? and 2. can't I set it up differently? And in the meantime, someone else will request for it 🤣 And if they don't, I know no one else wants it but me...
> 
> > However, it's true that not everyone is inclined to ponder deeply 😏.
> 
> We all think differently and therefore want different things, and a lot of people are happy with what they have and don't request for more features because they like simple things.

Everything's fine. I actually meant that more with a wink. You and I actually get along quite well, and I wouldn't dare to want to change anything about that. However, every syllable of what I said about the other guy is true. He starts passive-aggressive drama here and then doesn't even have the guts to own up to it, but instead resorts to pathetic gaslighting attempts. I can't stand that. I'm a nice person, but I also expect others to treat me the same way. So, that's my final word on this matter.

**Comment by aneesh1122** [comment]
> I'm a nice person, but I also expect others to treat me the same way. So, that's my final word on this matter

Awww....anon wants people to treat him nicely even though anon starts shit first. I'll treat you the way I want and you'll just have to 
> Deal with it.

**Comment by fast4x** [comment]
Please rest assured, this must be a place of positive confrontation.

**Comment by dAtA-TRoN** [comment]
> Please rest assured, this must be a place of positive confrontation.

Yes, apologies to all bystanders who had to witness this shitshow here.

**Comment by fast4x** [comment]
Implemented pause listen history, available from version 0.6.47

@dAtA-TRoN where are you

**Comment by fast4x** [comment]
Ok I'll check it, yes, I remember the hospital, I hope you leave him soon, a hug.

**Comment by dAtA-TRoN** [comment]
> Ok I'll check it, yes, I remember the hospital, I hope you leave him soon, a hug.

Hugging back, see?
🫂
