### ISSUE TITLE
[Feature]: support for alternative versions of albums

### ISSUE THREAD

**Issue by xronin01** [fast4x/RiMusic#1452]
### Description

![Screenshot_20240409-085442_Mull](https://github.com/fast4x/RiMusic/assets/109928669/e8843f3d-2956-4ea6-9d86-25bec32abc3c)

### Suggested Solution

Is it possible to make these albums show in the default artist albums guide?

**Comment by fast4x** [comment]
Hi, is just implemented... look.
![Screenshot_2024-04-09-14-38-01-585_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/1484476/3a75bdb4-4a61-4e8d-b7de-f432d6f08254)

**Comment by xronin01** [comment]
> Do you want alternative version in the same page of album?

Yes, this way is more intuitive

**Comment by fast4x** [comment]
yes it seems make sense, thanks

**Comment by fast4x** [comment]
Implemented alternative versions at bottom page, available from version 0.6.33
