### ISSUE TITLE
[Feature]: Additional sorting options

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1453]
### Description

(Probably a low priority request)
The sorting options in app are limited right now, they could be expanded

### Suggested Solution

Add these sorting options:-

Album - Number of tracks, Total album duration, Artist
Artists - Numbers of tracks, Album count, Genre (if yt music api support it)
Favourites - Year
Playlist:- Date added, Year (Talking about track year, it already has album year)

Also add sorting options in "Downloaded" section as well.

**Comment by fast4x** [comment]
Implemented sort options in downloaded songs, available from version 0.6.32

**Comment by fast4x** [comment]
Implemented all possible,  albums sort by artist, num songs, total duration.
Artist and favorites can not implement other options for now.
Playlist have just date added, year isn't possible for now.

Available from version 0.6.38

**Comment by NikunjKhangwal** [comment]
That's fine. Basic sorting methods are here now. Thanks
