### ISSUE TITLE
[Feature]: Grid style albums and artists layout with 3 entries per row

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1454]
### Description

Option to make albums layout grid, just like artists tab have right now and make every row contain 3 entries. (Artists have two entry per row right now and there's a lot of empty space)
![IMG_20240409_223641](https://github.com/fast4x/RiMusic/assets/99175083/8a1bcb99-23eb-4495-9f8a-5d1586e6578a)

### Suggested Solution

Like this:-

![IMG_20240409_215334](https://github.com/fast4x/RiMusic/assets/99175083/c1590dc2-f4e6-4fbe-ae77-199a2940a61a)

![IMG_20240409_215120](https://github.com/fast4x/RiMusic/assets/99175083/f4644916-829c-4c54-891f-8a7009f2475b)

**Comment by dAtA-TRoN** [comment]
I'm quite sure that's a duplicate, but one with beautiful mockups 😁👍🏼.

**Comment by NikunjKhangwal** [comment]
It was about grid menu btw (also suggested by me)

**Comment by fast4x** [comment]
Improved albums and artists pages, for now three colums decrease art image size very small, so i have changed albums from list to grid style.
Available from version 0.6.30

**Comment by NikunjKhangwal** [comment]
@fast4x any updates on 3 entries per row? Personally i feel like the icons are too big in new update. They look good on their own but doesn't go well with rest of the app (For example thumbnails in quick picks, favourites, artist window are much smaller)
I've made these rough mock-ups and they look very good to me, we can ask for other's opinion.

![Picsart_24-04-27_09-36-53-345](https://github.com/fast4x/RiMusic/assets/99175083/c137f463-e6c2-4a48-a969-7a897026fee8)
---
![Picsart_24-04-27_09-38-39-093](https://github.com/fast4x/RiMusic/assets/99175083/18fc4b8e-04f9-4a69-ac4e-65de8e4cb1b2)

**Comment by dAtA-TRoN** [comment]
![20240427_074452.jpg](https://github.com/fast4x/RiMusic/assets/71184627/702b2276-4b6e-4708-81ce-a79951ac8043)

Yes, any updates on this, hm!?

**Comment by NikunjKhangwal** [comment]
> Will look good on Top and Bottom Navigation Bar.

Exactly
2 entries for side navs and 3 for top and bottom.

**Comment by fast4x** [comment]
In new version, size will be changed in Library from small, medium and big. In small config, we have 3 side.

**Comment by NikunjKhangwal** [comment]
Nice, As a side note add the changing button here so
1. User don't have to go to settings
2. Settings will be less cluttered because there's already a lot of options getting added
3. User can see changes live.

![IMG_20240427_141307](https://github.com/fast4x/RiMusic/assets/99175083/c4e9685a-03ec-4b19-a070-dc4b21657aa2)
