### ISSUE TITLE
Wrong song playing when clicking on songs.

### ISSUE THREAD

**Issue by r1chard3** [fast4x/RiMusic#1456]
### Steps to reproduce the bug

1. Go to the songs section.
2. Play any song

### Expected behavior

Clicked song should play.

### Actual behavior

Random song in library is playing.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/135221755/e4cfd064-d3e3-439d-b66d-a55f3472fb3d

### RiMusic version

v0.6.28.1

### Android version

Android 13

**Comment by fast4x** [comment]
Is fixed in version 0.6.29 update please
