### ISSUE TITLE
Formatting Issue in Top List Since Introduction of Bottom Nav Bar

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1457]
### Steps to reproduce the bug

1. Navigate to the top list.

2. Observe the formatting of the top tracks list.

3. Note that the bottom navigation bar now obscures the last track in the list.

### Expected behavior

The top list should display all tracks in full without any portion being obscured by the bottom navigation bar. The entire list, including the last track, should be visible and accessible to the user.

### Actual behavior

Since the introduction of the bottom navigation bar, the last track in the top list is fully obscured by the bar. As a result, the user is unable to view or access the last track, leading to a discrepancy where for example the top 50 list now consists of only 49 tracks instead of the expected 50. This issue is particularly noticeable in the top list because it is numerically ordered, highlighting the absence of the last track.

### Screenshots/Screen recordings

![IMG_20240409_211315_283](https://github.com/fast4x/RiMusic/assets/71184627/3c755f0e-0180-41e4-9f47-309c831181aa)

### RiMusic version

0.6.29

### Android version

Android 13

### Additional information

Similar issues may exist with other playlists, although they are less noticeable due to their lack of numbering.

**Comment by fast4x** [comment]
in 0.6.30 it's improved

**Comment by dAtA-TRoN** [comment]
I think unfortunately that hasn't been fixed yet. My top 50 list still only shows 49 tracks.

![Screenshot_2024-04-12-23-01-21-77_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/1ef0ed3b-66a9-4a3f-9788-8ed14eca1503)

**Comment by fast4x** [comment]
ok

**Comment by dAtA-TRoN** [comment]
> ok

As far as I can see, the formatting issues still exists in all playlists.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.31

**Comment by fast4x** [comment]
Yes, consistent with the time I have.
