### ISSUE TITLE
[Feature]: Optional Visualizer & Record Audio permission

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#146]
### Description

The Visualiser and associated Record Audio permission should be optional with the option to enable them in the Settings.

### Suggested Solution

By default, the Visualizer would be disabled and whoever enables it in the settings must grant the  Record Audio permission.

### Alternatives

If it is not possible to set this to be optional, it would be good to have it pop up after the app is installed that tells the user as soon as the application is launched that they must permit Record Audio because it is necessary for the visualizer.

### Additional Context

Record Audio permission, which must be enabled without further explanation for the app to work, may make the app untrustworthy to some people.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.11
