### ISSUE TITLE
Few inconsistencies of Artist page

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1460]
### Description

![1712720854745](https://github.com/fast4x/RiMusic/assets/85461823/96141b9e-1c73-4177-9067-1b7fbb4783b8)

- **One.** Too close to the Picture.
- **Two.** Should be slightly bigger text. Same for when it is shown beside "Albums" and "Singles"
![Screenshot_20240410-150155.jpg](https://github.com/fast4x/RiMusic/assets/85461823/ed6cb164-16fb-495c-9068-783fb6178616)
- **Three.** Named as "Overview" but is identical to "Quick Picks"

### Suggested Solution

1. Place the subscriber text a little farther.
2. Increase size.
3. Make different icon for one of these.

### Additional Context

Also I'd love if there was an option to show square Picture for artists. Maybe when tapped on the Picture open it (pop-up!?) as square image. ~Would be even better if there's a download button. But that's not really needed.~

And I'd like if the artist description was at the top just below number of subscribers. Maybe show first 2/3 lines and the rest expand with a "Read more" there.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.30
