### ISSUE TITLE
Download an album 

### ISSUE THREAD

**Issue by Zef126** [fast4x/RiMusic#1462]
### Steps to reproduce the bug

1. Go on an album 
2. Press one of the buttons about downloading 
3. The 2 button ask us if you would like to delete all downloads and you can't download your album in just one click 

### Expected behavior

A single button for deleting album tracks from your storage or downloading them

### Actual behavior

A window appears asking if you want to delete everything downloaded.

### Screenshots/Screen recordings

![Screenshot_2024-04-10-11-20-02-347_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/165058165/ff257b33-e5d0-4eb7-a161-a200c7dc75db)
![Screenshot_2024-04-10-11-20-54-240_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/165058165/4bcfd146-8e4f-42fc-b83f-87c02d44f3e7)
In both cases, I didn't download the album.
I first clicked on the first download button on the left and then on the second!
![IMG_20240410_112629](https://github.com/fast4x/RiMusic/assets/165058165/1fea3796-886f-4572-a045-4ae0e69d91e8)

### RiMusic version

Latest

### Android version

HyperOS

### Additional information

The button next to it that looks like a target doesn't work either... I don't know what it's supposed to do.
![IMG_20240410_112918](https://github.com/fast4x/RiMusic/assets/165058165/9668d05a-ba14-4e81-9658-53e1b12765a6)

**Comment by fast4x** [comment]
> The button next to it that looks like a target doesn't work either... I don't know what it's supposed to do.

Is locate now playing song...

**Comment by fast4x** [comment]
I don't reproduce your bug, look.

https://github.com/fast4x/RiMusic/assets/1484476/56369b3d-d411-4fa9-b2a1-b71d815b6677
