### ISSUE TITLE
Hide button not working..!

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1465]
### Steps to reproduce the bug

When tryna hide songs that i dont like but it is automatically closing..

### Expected behavior

Float hide menu unless i press something..!

### Actual behavior

Vanishing immediately..!

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/107674915/24893a4d-6f11-4f92-9cf1-ecd315788d78

### RiMusic version

0.6.29

### Android version

Android 13

**Comment by KrisTamang** [comment]
And please fix theme issue..!
I am currently using pitch black but its only work when i play song..!

**Comment by fast4x** [comment]
It is made on purpose...

**Comment by KrisTamang** [comment]
> It is made on purpose...

Which problem are you talking about??

**Comment by KrisTamang** [comment]
Okay it automatically got fixed i wiped and restore everything and now its woking properly..!
