### ISSUE TITLE
[Feature]: auto hide/close keyboard 

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1466]
### Description

https://github.com/fast4x/RiMusic/assets/107674915/5e0ba1bd-3c97-496a-b812-4ff1140df85b

Shown as video if i search any song after i searched..!
Keyboard isn't closing..!

### Suggested Solution

After playing searched song.. keyboard should close automatically..!

**Comment by KrisTamang** [comment]
Again, please fix theme issue..!
I am currently using pitch black but its only work when i play song..!
Otherwise normal dark mode works not pitch black

**Comment by fast4x** [comment]
It is made on purpose...

**Comment by KrisTamang** [comment]
> It is made on purpose...

Which one are you talking about??

**Comment by fast4x** [comment]
Implemented, available from version 0.6.30

**Comment by KrisTamang** [comment]
> Implemented, available from version 0.6.30

Implement it when i scroll, touch anywhere in song list or play song..!

**Comment by fast4x** [comment]
play a song

**Comment by KrisTamang** [comment]
> play a song

It will be better if touch anywhere on song list, scroll and play any song..!
If i search a song and i scroll it... keyboard will take half of the screen thats kinda looks weird

**Comment by fast4x** [comment]
The search bar will be changed and improved in the future.
