### ISSUE TITLE
Remove button for on device songs

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1467]
### Steps to reproduce the bug

I recently delete the song "2 soon by keshi" because it was in YouTube api but its keep showing in my song list..!
I have some songs that doesn't exist in youtube api..
So is it possible to remove deleted song..!

### Expected behavior

Available to remove deleted songs

### Actual behavior

Showing but null but i can play the song and i am able to play too..!

### Screenshots/Screen recordings

![Screenshot_20240410-231646_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/67a3fbe5-873c-4821-bc03-64d50f2199de)

### RiMusic version

0.6.29

### Android version

Android 13

**Comment by KrisTamang** [comment]
![Uploading Screenshot_20240410-231815_RiMusic.png…]()

**Comment by KrisTamang** [comment]
![Screenshot_20240410-231815_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/3fcdd8c0-32cf-4904-bee1-97b27997eb11)

**Comment by fast4x** [comment]
You have to hide it with longpress and click hide 

![Screenshot_20240410_221327](https://github.com/fast4x/RiMusic/assets/1484476/160486b3-9b6f-4c63-9576-5b21f90f8b17)

**Comment by KrisTamang** [comment]
![Screenshot_20240410-231815_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/b9228977-8e85-42d0-b3e3-241800a9f943)
Not showing

**Comment by KrisTamang** [comment]
> ![Screenshot_20240410-231815_RiMusic](https://private-user-images.githubusercontent.com/107674915/321392523-b9228977-8e85-42d0-b3e3-241800a9f943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3ODA3NjQsIm5iZiI6MTcxMjc4MDQ2NCwicGF0aCI6Ii8xMDc2NzQ5MTUvMzIxMzkyNTIzLWI5MjI4OTc3LThlODUtNDJkMC1iM2UzLTI0MTgwMGE5Zjk0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQyMDIxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2JmZDM3YTAwMWNkOThhZjJmYjFhZGFkZDM1NGI1YzA5NDU3NjY2MzQ0NzUwNjVhZTVhYjhmYjU4YjFlMzUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eR3-tsBIdvMI52fQBdXDYH5IPr9HNqGG7a9SZkYVjCI) Not showing

I played on device and delete it but it keep showing

**Comment by fast4x** [comment]
wait new release

**Comment by KrisTamang** [comment]
> wait new release

Please fix if on device music not found or deleted just remove from song list..!

**Comment by KrisTamang** [comment]
> wait new release

![Screenshot_20240414-212327_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/546e2b13-3e40-4cc0-8801-dcb20f86e0b5)
Just remove song from list if not found..
