### ISSUE TITLE
Hide bug

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1468]
### Steps to reproduce the bug

I wiped all my downloaded music
Just to show you

https://github.com/fast4x/RiMusic/assets/107674915/d113acc7-82b1-4f7a-abce-519a28dd75b8

I wiped all my downloaded music
Just to show you

### Expected behavior

I thought that button showing the song i played but not downloaded or hide..!
I am so confused 

### Actual behavior

Please remove the hide sh*t and give remove features..!
Or give both option.. i will happy use remove one..
I really want there only my favorite songs or there is option for on device music too (i liked that one)..!
I just wanted my song list look clean😩😞
Some might think this is the worst issue ever made but please i beg you..🥺

### Screenshots/Screen recordings

![Screenshot_20240410-232457_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/3c26b077-93c2-42e0-988d-0a726cf07001)
Please explain what does this do.!?😭😭

### RiMusic version

0.6.29

### Android version

Android 13

**Comment by fast4x** [comment]
It's normal when you use search and reproduce one song, start a radio play and relative songs are saved...

**Comment by KrisTamang** [comment]
> It's normal when you use search and reproduce one song, start a radio play and relative songs are saved...

Thats kinda messed up..!

**Comment by fast4x** [comment]
No, you are wrong to use RiMusic, that is the general list of all the songs and the show/hide button is only used to display or hide even the songs you have never heard...
Instead, you can find your favorite songs, downloaded or cached only in the Library

**Comment by KrisTamang** [comment]
> No, you are wrong to use RiMusic, that is the general list of all the songs and the show/hide button is only used to display or hide even the songs you have never heard... Instead, you can find your favorite songs, downloaded or cached only in the Library

Thats literally unnecessary feature 
It will be better if there was only song i payed before

**Comment by KrisTamang** [comment]
> It's normal when you use search and reproduce one song, start a radio play and relative songs are saved...

I beg you please remove that feature
Instead let that work as a history of song i played if i wanna remove from song there too then make it possible to remove from there too (and if i listen this song again.. summon the song in history again)

**Comment by fast4x** [comment]
History will be available to next release as separate feature.

**Comment by KrisTamang** [comment]
> History will be available to next release as separate feature.

I don't see ..!
Where it is??

**Comment by fast4x** [comment]
history is in quick pics
