### ISSUE TITLE
RiMusic downloads the whole playlist/album even after songs are selected

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1477]
### Steps to reproduce the bug

1. go to any album/playlist
2. choose select/deselect
3. select some songs from the album/playlist
4. tap 'download all' icon

### Expected behavior

Only the selected songs should be downloaded

### Actual behavior

every song in the album/playlist is downloaded

### RiMusic version

0.6.29

### Android version

Android 13

**Comment by NikunjKhangwal** [comment]
This is probably not a bug but more like a feature that was not implemented.

**Comment by fast4x** [comment]
Implemented in home songs, album and playlist

**Comment by aneesh1122** [comment]
> Implemented in home songs, album and playlist, available from versiin 0.6.38

Thanks fast4x 😊
