### ISSUE TITLE
[Feature]: Bring down options below album cover for easy one-hand use

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1478]
### Description

The options which contain download, shuffle etc are located above the album cover which makes it hard to reach while using mobile with one hand

### Suggested Solution

Please put those options below the album cover so that those options can be reached easily with our thumb

Before
![before](https://github.com/fast4x/RiMusic/assets/45353488/1a5810a4-d2ce-4eb4-a4d2-5de6858c219c)

After
![after](https://github.com/fast4x/RiMusic/assets/45353488/183066d4-71f4-4d5d-9eca-4a299638ef42)

**Comment by NikunjKhangwal** [comment]
Just like the library tabs. Very nice suggestion.
This should be done for artist overview page, singles and artist library page.
