### ISSUE TITLE
[Feature]: Small Improvements

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#148]
### Description

I had alot of Small Improvements in mind and i wanted to share!

### Suggested Solution

# Player : 

- **DONE** Artist Icon: Align the artist icon with the song icon to maintain consistency and visual balance.
![image](https://github.com/fast4x/RiMusic/assets/104271365/505ea1f4-f55a-43e7-8067-95158f47cc87)

- **DONE** Multiple Artist Icon: Replace the two separate icons for multiple artists with a single icon that clearly represents multiple artists. This will improve the visual clarity.
![image](https://github.com/fast4x/RiMusic/assets/104271365/27614a31-ec59-481a-b207-7cd8e26352a7)

- Song Icon: When listening to an music video instead of an song the icon should change from the disk to an video icon

- **DONE** Bottom Bar Size: Reduce the size of the bottom bar in the songs list to improve the overall layout.
![image](https://github.com/fast4x/RiMusic/assets/104271365/9cf56690-0c1a-43f3-b127-b29980fc85b0)

- Swiping Gestures: Enhance the swiping gestures to prevent accidental song changes. Implement clearer animations to indicate the intended actions.
![image](https://github.com/fast4x/RiMusic/assets/104271365/cb71e6e6-442f-410b-a67f-0ad362766e39)

- **DONE** Swiping Back Behavior: Instead of restarting the song, swiping back should directly go to the previous song.

- **DONE** Audio Visualizer Transparency: Add a transparent background to the audio visualizer, allowing the album art to be visible simultaneously.

- Audio Visualizer Colors: Implement dynamic color changes for the audio visualizer. Substitute by #186 

- **DONE** Lyrics Translation Button Placement: Reposition the lyrics translation button to the bottom left corner to prevent overlapping with error messages.

- **DONE** Audio Visualizer Fade-out: Make the audio visualizer fade out when viewing hidden song information (accessed by tapping and holding) to prevent overlapping

# Playlists : 
-  **DONE on librarys** Listening Time Sorting: When sorting songs by listening time in a playlist, display the actual listening time on each song, similar to the "Songs" category.

- **DONE** Downloaded Song Storage Usage: Include an option to view the storage space occupied by downloaded songs, providing users with insights into their music storage usage. ( Add it in the downloaded Playlist or in the Settings )

- **DONE** Cached Songs Playlist Visibility: Automatically hide the "In Cache" playlist when cached songs are disabled.

- Hide alarms and prevent duplicates: Hide the songs form the "In the Device" playlist when songs are not stored in the "Songs" folder in Android to prevent alarms and other audios to be shown.

# Listening Statistics :
- **DONE** Automatic Image Loading: Load automatically images in the listening statistics.

# Settings :
- **DONE**  Custom Cache Limit: Implement an option for users to manually enter their desired cache limit instead of being restricted to a predefined list. This provides greater flexibility and customization.
![Screenshot_20231128_124259_Settings.jpg](https://github.com/fast4x/RiMusic/assets/104271365/751011fb-f98e-429e-9158-38011f4f59ee)

# General : 
- **DONE**  Android 13-14 Predictive Back Gestures: Integrate support for Android 13-14 predictive back gestures to enhance the navigation experience and align with the latest Android versions.

- **DONE** "About RiMusic" Placement: Relocate the "About RiMusic" section from the beginning of the settings to a more suitable location, preventing it from appearing forcefully upon opening the settings menu.

### Additional Context

If you need more informations about the improvement dont hesitate to ask!

**Comment by ikanakova** [comment]
> Multiple Artist Icon: Replace the two separate icons for multiple artists with a single icon that clearly represents multiple artists. This will improve the visual clarity.

You mean an icon like this?
<img src="https://github.com/fast4x/RiMusic/assets/38765251/a1829bc2-d498-4059-8cbf-6f59414eda50" width="50" alt="artists">

**Comment by OrangeZXZ** [comment]
> > Multiple Artist Icon: Replace the two separate icons for multiple artists with a single icon that clearly represents multiple artists. This will improve the visual clarity.
> 
> You mean an icon like this?
> <img src="https://github.com/fast4x/RiMusic/assets/38765251/a1829bc2-d498-4059-8cbf-6f59414eda50" width="50" alt="artists">
> 

yes perfect

**Comment by ikanakova** [comment]
> > > Multiple Artist Icon: Replace the two separate icons for multiple artists with a single icon that clearly represents multiple artists. This will improve the visual clarity.
> > 
> > 
> > You mean an icon like this?
> > <img alt="artists" width="50" src="https://private-user-images.githubusercontent.com/38765251/285598230-a1829bc2-d498-4059-8cbf-6f59414eda50.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjQ4NjYsIm5iZiI6MTcwMDkyNDU2NiwicGF0aCI6Ii8zODc2NTI1MS8yODU1OTgyMzAtYTE4MjliYzItZDQ5OC00MDU5LThjYmYtNmY1OTQxNGVkYTUwLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE1MDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYWI0N2MyYmEyM2YwNjc2Yzg3NWRjNGMwMDkyYjY0MTAxZGZlNGI4MTg3NjNhNDBlNTQxN2U5NDYzOTU0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uvqFvSWj4jXi639zuVKYFgFTgZ01HU2WyT2o8lYzGG4">
> 
> yes perfect

Icon added to assets for possible use (see #150)

**Comment by fast4x** [comment]
Wow, amazing work

**Comment by OrangeZXZ** [comment]
Also new suggestions could these buttons be bigger?

![SmartSelect_20231128_124330.jpg](https://github.com/fast4x/RiMusic/assets/104271365/abf031ea-f3d9-43f1-a48a-af303c15a4bd)

**Comment by fast4x** [comment]
I don't understanding...

Listening Statistics :
Automatic Image Loading: Load automatically images in the listening statistics.

**Comment by OrangeZXZ** [comment]
> I don't understand...

![SmartSelect_20231129_185427.jpg](https://github.com/fast4x/RiMusic/assets/104271365/7a78d066-6942-4b8f-9f1f-d9702b6be3f6)
![Screenshot_20231129_185408.jpg](https://github.com/fast4x/RiMusic/assets/104271365/5f097cca-387c-4681-840b-2a698f46b0b8)

Images don't load automatically in this menu

**Comment by OrangeZXZ** [comment]
> Ahhh ok ok, the cause is the size of the image cache. 

I don't think that is the case because in Quick Pics the images loads

**Comment by fast4x** [comment]
I better check, if I’m not mistaken, on Quick Picks images are from the web not from the cache.

**Comment by fast4x** [comment]
Fixed, it's a bug

**Comment by OrangeZXZ** [comment]
> Give me an example, please.
> 
> Hide alarms and prevent duplicates: Hide the songs form the "In the Device" playlist when songs are not stored in the "Songs" folder in Android to prevent alarms and other audios to be shown.

![Screenshot_20231130_060616.jpg](https://github.com/fast4x/RiMusic/assets/104271365/39ea9d5c-da17-4d3c-aadb-fbb0ef0bcc61)

On Samsung There is an alarm folder for alarms and I can see the alarm in this menu

There is another folder called Songs where i could had my downloaded songs but i have nothing yet

**Comment by fast4x** [comment]
All items maked as **DONE** are implemented, available from version 0.6.11

**Comment by fast4x** [comment]
Thank you for these suggestions

**Comment by ikanakova** [comment]
What would you say about this new Listening Statistics icon?
<img src="https://github.com/fast4x/RiMusic/assets/38765251/0756c2cc-c4cf-496c-85f2-3351084fffed" width="50" alt="statistics">

**Comment by fast4x** [comment]
Maybe it's too large...

**Comment by ikanakova** [comment]
> Maybe it's too large...

Stejná šířka jako u [trending-up icon](https://github.com/fast4x/RiMusic/blob/master/assets/ionicons/trending-up.svg):
<img src="https://github.com/fast4x/RiMusic/assets/38765251/b5abd271-05af-4336-8119-530a37c87aa6" width="50">

**Comment by ikanakova** [comment]
>In my opinion this icon could be changed to to that Ionicons icon too

I don't know if people would understand that the chart means ranking by most played songs. I'd rather keep the original trending-up icon for sorting and the stat-chart for stats. In addition, it may be possible in the future to extend the statistics for things other than the most played.

**Comment by fast4x** [comment]
so? which we use?

**Comment by fast4x** [comment]
image link not work

**Comment by fast4x** [comment]
Changed

**Comment by fast4x** [comment]
An icon would be useful to identify **original** or **user content**.
To be displayed in the image of the song or album to distinguish the original from a version uploaded by a user on Youtube music or Youtube.

**Comment by OrangeZXZ** [comment]
> An icon would be useful to identify **original** or **user content**.
> To be displayed in the image of the song or album to distinguish the original from a version uploaded by a user on Youtube music or Youtube.

Maybe like an barred person icon to immediately see if the chanel is not the artist (instead of colored text or the icon disappearing

**Comment by OrangeZXZ** [comment]
I had an funny suggestion in my mind

Would be cool when you tap 10 times on the Rimusic icon at the top when listening it becomes the ViMusic icon until restart (A bit like the discord easteregg)

**Comment by ikanakova** [comment]
> An icon would be useful to identify original or user content.
To be displayed in the image of the song or album to distinguish the original from a version uploaded by a user on Youtube music or Youtube.

I think for the original the symbol [℗](https://en.wikipedia.org/wiki/Sound_recording_copyright_symbol) or [©](https://en.wikipedia.org/wiki/Copyright_symbol) or [®](https://en.wikipedia.org/wiki/Registered_trademark_symbol) could be used.

**Comment by OrangeZXZ** [comment]
A new inprouvement would be to hide some categories when there is nothing

Examples:
New albums of your artists:
![SmartSelect_20231202_121138.jpg](https://github.com/fast4x/RiMusic/assets/104271365/25229e38-69e0-42ab-ad8b-950cbfb7c854)

and Playlists:
![SmartSelect_20231202_121241.jpg](https://github.com/fast4x/RiMusic/assets/104271365/1c97aa85-e4b6-475a-b81f-5458cfe776e9)

**Comment by fast4x** [comment]
Yes It can improved

**Comment by fast4x** [comment]
Added improvement 

- for new albums, now is visible only for relative preferites artists
- many other on this ticket

Available from version 0.6.12

**Comment by OrangeZXZ** [comment]
Could Quick Picks be the default page when opening even when you close it without batery optimisations?

**Comment by ikanakova** [comment]
> Could Quick Picks be the default page when opening even when you close it without batery optimisations?

It would be great if the default page was optional.

**Comment by fast4x** [comment]
This setting is currently not possible because it requires an important update in the internal logic of RiMusic. It is in the pipeline though.

**Comment by fast4x** [comment]
Implemented custom cache on player
Available from version 0.6.12

**Comment by fast4x** [comment]
Implemented, Swiping Back Behavior: Instead of restarting the song, swiping back should directly go to the previous song
Available from version 0.6.13

**Comment by OrangeZXZ** [comment]
I think having the same setting in 2 categories is weird it could be moved only in UI

![SmartSelect_20231210_105741.jpg](https://github.com/fast4x/RiMusic/assets/104271365/7a7f5eaa-b5ba-452a-b205-4b049d8d87f6)

![SmartSelect_20231210_105753.jpg](https://github.com/fast4x/RiMusic/assets/104271365/b6458fd8-b63c-48db-baa0-1c5991e36f13)

**Comment by OrangeZXZ** [comment]
It would be nice an option to remove the "listen with" in the song settings because I dont use them and it takes unnecessary space

**Comment by fast4x** [comment]
Of course it’s planned, we talked about it

**Comment by OrangeZXZ** [comment]
> Of course it’s planned, we talked about it

my bad then

**Comment by NEVARLeVrai** [comment]
@fast4x did the visualizer freeze issue is in WIP ?

**Comment by fast4x** [comment]
Visualizer freeze, it's internal bug.

**Comment by faustaahmad** [comment]
I realize #384 are WIP here
> Swiping Gestures: Enhance the swiping gestures to prevent accidental song changes. Implement clearer animations to indicate the intended actions.
p.s. around 30° straight swipe up/down does change song (next/prev) also some kind of narrow curved `(` and `)` does change song too

**Comment by fast4x** [comment]
This ticket is very long, I close it as done because almost everything has been implemented. What is still missing is better to insert it in a new ticket
