### ISSUE TITLE
Add informative message for empty library page in RiMusic app

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1481]
### Description

Currently, the RiMusic app displays a helpful message when navigating to the album page of an artist who hasn't uploaded any releases yet. However, a similar informative message is missing on the library page when it's empty. This absence can lead to confusion for users. 

Additionally, the artist's image is displayed on the empty library page, which may give the impression of content when there isn't any.

![ZomboDroid_12042024114428](https://github.com/fast4x/RiMusic/assets/71184627/1906367a-a28c-49f7-9703-73da49b5357a)

### Suggested Solution

Implement a brief text message to inform users when the library page is empty, similar to the message displayed on the album page for artists without any album releases. This message should clarify why the page is empty and reassure users.

Also, ensure that the artist's image is not displayed on the empty library page to reinforce the impression of an empty page when there's no content.

### Additional Context

Providing consistent messaging across different pages of the app enhances user experience by reducing confusion and helping users understand the app's functionality better.

**Comment by fast4x** [comment]
But you mean library in search page ?

**Comment by dAtA-TRoN** [comment]
> But you mean library in search page ?

There you go:

https://github.com/fast4x/RiMusic/assets/71184627/16558d5a-45d7-4e19-a2af-3506eb0cbe10

By the way: apparently there's also the inconspicuous case where the artist's main page shows no releases at all. This means that there might be artists listed in YouTube Music who haven't uploaded anything yet, or as seen in my video clip, artists who have taken down their music afterwards (don't ask me why 🤷🏻‍♂️). I think there should be a corresponding text note on the artist's main page in such cases.

**Comment by fast4x** [comment]
perfect, thanks now i understand

**Comment by dAtA-TRoN** [comment]
> perfect, thanks now i understand 

Great 🙂.
