### ISSUE TITLE
More useful quick picks

### ISSUE THREAD

**Issue by Abhishekahhi-io** [fast4x/RiMusic#1482]
### Description

Use 5 most listened songs and randomly pick songs from this quick picks and add in quick picks. Not just use most listened 1 song for picking quick picks. Use more songs and randomly select some.

### Suggested Solution

Use 5 most listened songs and randomly pick songs from this quick picks and add in quick picks. Not just use most listened 1 song for picking quick picks. Use more songs and randomly select some.

**Comment by VINULA2007** [comment]
Refer #1187

**Comment by fast4x** [comment]
Implemented, new tips from Casual listened songs, available from version 0.6.30

**Comment by dAtA-TRoN** [comment]
WTF!?

![proxy-image.gif](https://github.com/fast4x/RiMusic/assets/71184627/be838b8a-2971-4863-b37f-ad637454e0ea)

**Comment by fast4x** [comment]
![giphy (8)](https://github.com/fast4x/RiMusic/assets/1484476/4bfc67a4-fb93-4e4b-be42-232f51a8b068)
