### ISSUE TITLE
A new 🌌 bug on Artists pages

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1487]
### Steps to reproduce the bug

1. Open any Artist
2. See an album or a single name that is long

### Expected behavior

Albums/Singles with long name shouldn't be expanded on the overview page. 

### Actual behavior

Long names of Albums, Singles are expanded which results in some space that looks odd.

### Screenshots/Screen recordings

![Screenshot_20240413-032236](https://github.com/fast4x/RiMusic/assets/85461823/520f9deb-ee05-4814-9fe5-830955e007fb)

While I actually do like seeing these names expanded but these spaces doesn't feel good.

### RiMusic version

0.6.30

### Android version

Android 11

**Comment by fast4x** [comment]
Fixed, available from version 0.6.31
