### ISSUE TITLE
[Feature]: replacement of history and statistics..!

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1488]
### Description

History and statistics should replace to navigate bar just shown as screenshot 
![Screenshot_20240413-032113_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/d9325f3a-425e-42ee-9abf-181fab396931)

### Suggested Solution

And remove logo from there too..
Its kinda look messy..!

**Comment by KrisTamang** [comment]
Or maybe inside library..

**Comment by KrisTamang** [comment]
> Sorry but…please no. These are already placed well.

Thats look pretty messed up🥲
Maybe bottom of that page will work but seriously it really ruined looks

**Comment by KrisTamang** [comment]
> Sorry but…please no. These are already placed well.

I really liked minimalist only "tips" on that page..!

**Comment by KrisTamang** [comment]
> > > Sorry but…please no. These are already placed well.
> > 
> > 
> > Thats look pretty messed up🥲
> > Maybe bottom of that page will work but seriously it really ruined looks
> 
> Then maybe these should be customizable through settings? I'm sure fast4x will read these convo decide wisely what to do.

Yeah he is working on customizable one..!
But its in beta..
I checked but nothing was new 
It say only download if you are invited to beta..

**Comment by NikunjKhangwal** [comment]
These looks good when bottom nav is enabled. Just doesn't work with side nav bars

**Comment by VINULA2007** [comment]
What about putting history and statics inside that double tap pop-up windows on search button 
It'll give a minimal sidebar and a minimal home page

**Comment by NikunjKhangwal** [comment]
Naah. That's for quick actions not for tabs

**Comment by VINULA2007** [comment]
> Naah. That's for quick actions not for tabs

I don't think history and statics are "tabs" 
There are more of a in-between 
And the pop up window feels lonely with only search and settings

**Comment by NikunjKhangwal** [comment]
I'm pretty sure many people will prefer easy access to them. Either way there's issue about making them optional so we're all good.

**Comment by NikunjKhangwal** [comment]
Nevermind, it's this one. I didn't bothered reading properly

**Comment by fofxox** [comment]
I would also like to see the History and Statistics move down below the search button.  Right now, they are hard to reach with a thumb.

**Comment by fast4x** [comment]
![Screenshot_20240413_183433](https://github.com/fast4x/RiMusic/assets/1484476/1606030d-385d-44cf-8296-fecc1317a879)

**Comment by fast4x** [comment]
![Screenshot_20240413_190315](https://github.com/fast4x/RiMusic/assets/1484476/65842b72-b406-42d5-991a-34de3947da4c)

**Comment by fast4x** [comment]
![Screenshot_20240413_190517](https://github.com/fast4x/RiMusic/assets/1484476/f813e9f1-57fd-474c-ba8c-80d632bb2eef)

with navigation to left, bar in quick pics now can disable by settings

**Comment by fast4x** [comment]
Implemented in new aspect
