### ISSUE TITLE
Hide window bug

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1489]
### Steps to reproduce the bug

I was just tryna hide songs i dont like..!

### Expected behavior

Hide window doesn't timeout unless i make any move

### Actual behavior

hide window disappearing instantly without any touch..

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/107674915/58411b9d-9291-48e0-b2c3-f5c64414b423

### RiMusic version

0.6.30

### Android version

Android 13

**Comment by fast4x** [comment]
Fixed, available from version 0.6.31
