### ISSUE TITLE
[Feature]: Unify download icons

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#149]
### Description

![unnamed](https://github.com/fast4x/RiMusic/assets/38765251/8b97c9e2-26e0-488e-aee8-de106281e594)

### Suggested Solution

I think the download icons should be unified.

### Alternatives

Or at least unify the icons in the top bar - if there is interest I will make svg of these icons again according to ionicons.

**Comment by ikanakova** [comment]
I think when someone wants to download a song/playlist - there should be an icon: <img src="https://unpkg.com/ionicons@7.1.0/dist/svg/download-outline.svg" width="20"> After download song / songs: <img src="https://unpkg.com/ionicons@7.1.0/dist/svg/download.svg" width="20">

And if he wants to delete it, he clicks on this icon: <img src="https://unpkg.com/ionicons@7.1.0/dist/svg/download.svg" width="20"> and after deleting it will be like this again: <img src="https://unpkg.com/ionicons@7.1.0/dist/svg/download-outline.svg" width="20">

**Comment by fast4x** [comment]
You are right!

**Comment by fast4x** [comment]
Implemented, available from version 0.6.11
