### ISSUE TITLE
simple page design concept

### ISSUE THREAD

**Issue by HasakeKisaragi** [fast4x/RiMusic#1490]
### Description

I suggest a slight redesign of the first page, make it a box and highlight the buttons, separate the settings button from the search,lyrics in mini player, more or less like this is what I suggest, thank you, in the future it will be possible to play videos & round blurred gradient backgrounds that move according to the album cover 

### Suggested Solution

![1712967474738](https://github.com/fast4x/RiMusic/assets/166180711/2aeb7a9b-eb19-4794-bbd6-6c1a05a24ecf)

https://github.com/fast4x/RiMusic/assets/166180711/008a0648-e054-4e7f-8f5b-5aca5ebc640a

**Comment by NikunjKhangwal** [comment]
I'm pretty sure most people aren't going to like highlight buttons. Lyrics will work in miniplayer but only for bigger screens. They'll look ugly in mobile. Settings in search was a decision because there was no good solution to the other problems (as of now)

**Comment by fast4x** [comment]
I don't like this aspect
