### ISSUE TITLE
Albums are misaligned

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1492]
### Steps to reproduce the bug

Go to albums page and compare it to artists

### Expected behavior

The albums should be in the center. Just like the artist

### Actual behavior

The albums are left aligned.
![IMG_20240413_090327](https://github.com/fast4x/RiMusic/assets/99175083/3a4c9a3a-8789-4c7d-aaf6-5d35522647f2)

Position them in center like artists
 
![IMG_20240413_090346](https://github.com/fast4x/RiMusic/assets/99175083/7c22f5f7-242c-472a-8339-e6588098422a)

### RiMusic version

0.6.20

### Android version

Android 12

**Comment by fast4x** [comment]
Fixed, available from version 0.6.31
