### ISSUE TITLE
Action button isn't staying in defined position

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1494]
### Steps to reproduce the bug

Hold action button to move it anywhere, double tap and go to settings and come back

### Expected behavior

Action button should stay in last position

### Actual behavior

It's position gets reset

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/99175083/96b63190-ac20-4923-b40a-54b7c825fa07

### RiMusic version

0.6.20

### Android version

Android 12

**Comment by dAtA-TRoN** [comment]
I've started a new thread in the 'Discussions' section where I critique the implementation of the new floating search button. I'm also addressing points you mentioned here. Feel free to check it out and share your thoughts.

**Comment by fast4x** [comment]
This isn't a bug...

**Comment by NikunjKhangwal** [comment]
What's happening then? Please explain a bit

**Comment by fast4x** [comment]
He wasn’t supposed to hold his position once he moved. This is because the user only moves it if it prevents them from reading or clicking on what is underneath.

**Comment by NikunjKhangwal** [comment]
Oh! I completely misunderstood the implementation then. Makes sense
