### ISSUE TITLE
[Feature]: long press to open Pop up window on Search button and stationary button 

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#1495]
### Description

Quick tap for search and long tap for pop up window makes more sense than a double tap
And the search button moving everywhere when I accidentally long press it is kinda annoying and it has no use anyways as it goes back to the same place when I switch to different pages

### Suggested Solution

Make search button stationary 
And make the pop up window open with a long press

**Comment by sayyid5416** [comment]
Yes, double tap doesn't feel natural for this.

**Comment by fast4x** [comment]
Removed double tap, it can moved with lon press now

**Comment by sayyid5416** [comment]
> Removed double tap, it can moved with lon press now. Stationery button not make a sense, it make more sense if disable it.

How about making it optional, that way those who likes moving it around can move it on long press, while those who make it stationary can access menu by long press.

**Comment by fast4x** [comment]
> > Removed double tap, it can moved with lon press now. Stationery button not make a sense, it make more sense if disable it.
> 
> How about making it optional, that way those who likes moving it around can move it on long press, while those who make it stationary can access menu by long press.

Yes it make sense

**Comment by fast4x** [comment]
It will be available only in vimusic mode ui like before
