### ISSUE TITLE
Wasted spaces in Click to switch to lyrics

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#1497]
### Steps to reproduce the bug

• Play a song that doesnt have any lyrics
• Activate lyrics (ex: tap on cover)
• Click to switch to lyrics appear with lots of wasted spaces

### Screenshots

![Screenshot_20240413-112442](https://github.com/fast4x/RiMusic/assets/45221211/520851f3-0bc5-4c5f-a74b-0685a4eafc65)

### RiMusic version

0.6.30

### Android version

Android 11

### Additional information

• Remove the wasted spaces in the middle of "... lyrics ... not available" and "click to ... lyrics"
• Remove additional spaces after "... lyrics<here>are not available ..." (afaik it has 2 spaces instead of 1)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.31
