### ISSUE TITLE
Settings not opening

### ISSUE THREAD

**Issue by Abhishekahhi-io** [fast4x/RiMusic#1499]
### Steps to reproduce the bug

Settings not opening. Please don't put settings together

### Expected behavior

Settings not opening. Please don't put settings together

### Actual behavior

Settings not opening. Please don't put settings together

### Screenshots/Screen recordings

![Screenshot_2024-04-13-11-58-59-353_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/118500229/5ed60f70-c6a7-4732-bb86-a2feeca1870b)
![Screenshot_2024-04-13-11-58-59-353_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/118500229/16746a34-abeb-4cb7-becb-6147e00d70e8)

### RiMusic version

0.6.30

### Android version

12

**Comment by dAtA-TRoN** [comment]
You have to double tap the new floating search button.

**Comment by Abhishekahhi-io** [comment]
> You have to double tap the new floating search button.

Thanks 🙌🏻

**Comment by jfmcbrayer** [comment]
It took me forever to work this out, since double tap is not a widely used or expected interaction on Android. If search is going to be stuck on the FAB and nowhere else, it needs to be reachable by single tap or at worst long press.

**Comment by dAtA-TRoN** [comment]
> It took me forever to work this out, since double tap is not a widely used or expected interaction on Android. If search is going to be stuck on the FAB and nowhere else, it needs to be reachable by single tap or at worst long press.

Don't worry, with the next update it will be gone again.
