### ISSUE TITLE
Download function

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#15]
### Description

Would it be possible to add a download function for songs, playlists and albums.

### Suggested Solution

The app already has a cache function - maybe you can use it for the download function somehow.

**Comment by fast4x** [comment]
Yes, there is a legal issue to consider since we are talking about music from YouTube.

**Comment by fast4x** [comment]
Maybe the feature could be called Song Backup and not Download... :)

**Comment by siggi1984** [comment]
So by downloading I don't mean saving the songs and playing them with an offline player.

It would also be fine if you can play the downloaded songs only in RiMusic. The app is not a download app but a music streaming app.

I try to explain it with an example: Let's say I'm traveling and have no internet on the way then I could only listen to the songs that are in the cache. But if I could download a collection of songs beforehand it would be very advantageous.

**Comment by fast4x** [comment]
This request requires more time, please wait.

**Comment by fast4x** [comment]
Download feature added, available from version 0.6.10.
At the moment there is a bug that does not allow to remove the download

**Comment by fast4x** [comment]
Fixed

**Comment by fast4x** [comment]
Improvements will be available to next version.
