### ISSUE TITLE
Album posters shows black posters

### ISSUE THREAD

**Issue by NightFly88** [fast4x/RiMusic#1500]
### Steps to reproduce the bug

In the latest version Album posters shows black posters see photo,

Thanks 

### Expected behavior

That it gets fixed

### Actual behavior

Nvt

### Screenshots/Screen recordings

![Screenshot_20240413_083224](https://github.com/fast4x/RiMusic/assets/163666747/f0efd6f4-0746-4b08-a63b-ff9f2c9366c9)
![Screenshot_20240413_083236](https://github.com/fast4x/RiMusic/assets/163666747/f2bc8fd3-5dfc-4c97-94d0-76a914cb4375)

### RiMusic version

v0.6.30

### Android version

Android 14

**Comment by NightFly88** [comment]
> Those are not "black posters" just empty spaces. See #1487

When I click on the album it opens the album

**Comment by NightFly88** [comment]
> Those are not "black posters" just empty spaces. See #1487

yes you are right thank you

**Comment by fast4x** [comment]
Fixed, available from version 0.6.31

**Comment by NightFly88** [comment]
Thanks
