### ISSUE TITLE
Improve default colors of dynamic theme

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#1501]
### Description

When using dynamic theme, and no song is playing, there are default colors for all items. They needs to be improved because:
- They look inconsistent, and
- Some are too dark shade.

### Suggested Solution

![image](https://github.com/fast4x/RiMusic/assets/78584556/ba024270-f9db-406a-a36d-7784cbd8c789)
<br>
![image](https://github.com/fast4x/RiMusic/assets/78584556/28b8eac1-8ee8-4a35-b16a-4347773fa7c4)
<br>
![image](https://github.com/fast4x/RiMusic/assets/78584556/54ed4fa2-c1ef-4692-a44f-f8f974fe956b)

**Comment by NightFly88** [comment]
the color changes every time you switch on a different number,

**Comment by sayyid5416** [comment]
> the color changes every time you switch on a different number,

by different number do you mean different song?

If yes, then I'm not talking about that. I'm talking about when no song is being played.

Btw, they still feel too dark even if some song is being played.

**Comment by NightFly88** [comment]
> > the color changes every time you switch on a different number,
> 
> by _'different number'_ do you mean different song?
> 
> If yes, then I'm not talking about that. I'm talking about when no song is being played.
> 
> Btw, they still feel too dark even if some song is being played.

yes I mean song🤣

**Comment by sayyid5416** [comment]
fast4x If you implement #1513, Make the colors a little subtle, and not this much dark wrt other UI.

**Comment by sayyid5416** [comment]
Now since #1513 is implemented. This request is redundant.
