### ISSUE TITLE
Few suggestions for improvement on player

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1503]
### Description

As many features keep getting implemented many inconsistency will arise along with them. That's natural. I have come up with some of the inconveniences I've noticed. I'll be adding those below.

### Suggested Solution

- [x] This part is unnecessary I think (Not sure if others agree though): ![Screenshot_20240413-042339.jpg](https://github.com/fast4x/RiMusic/assets/85461823/6569b6fa-3102-4ace-9e58-06c9990399cc)
- [x] This gap looks bigger: ![1712960843767.jpg](https://github.com/fast4x/RiMusic/assets/85461823/40204b1a-4820-499e-a788-e4fc8757cd15)

- [ ] Some of these buttons shouldn't always be visible here based on some things: ![1712962162081.jpg](https://github.com/fast4x/RiMusic/assets/85461823/1e384db5-45ed-4729-9277-23f612809a57) For example I have Sleep timer button enabled so that shouldn't be visible on the menu for me.

- [ ] If lyrics gets scrolled down like in this video (I'll attach below) it isn't visible and has to scroll back up for few seconds. It doesn't bother me much but would bother some others for sure. Especially it happening on the player lyrics. Full screen lyrics being like that ain't much of a problem. https://github.com/fast4x/RiMusic/assets/85461823/98a8cb67-8faf-4a61-920f-512de0045d04
- [x] Song title is bigger than it supposed to be: ![1712995001450.jpg](https://github.com/fast4x/RiMusic/assets/85461823/bcdd5ea2-53d2-431f-acc7-5f79bb807e4b)

Nevermind these below ones because seems like I mistook, didn't give much thought:
~~- [ ] This icon is unnecessary: ![Screenshot_20240413-044435.jpg](https://github.com/fast4x/RiMusic/assets/85461823/cedf5fb7-4d35-4b9c-a8cb-a54d7421f66e)~~
~~- [ ] I thought tapping on shuffle button turns "shuffle" on or off but seems like it only shuffles to another song. I remember I used to turn off shuffle tapping on that so I'm guessing it's just a bug?~~

### Additional Context

I might add more things on the comments later if I find anything more.

**Comment by fofxox** [comment]
I like the tiny clock icon next to the remaining queue time.  It helped me understand what that section actually is, the first time I used the app.

**Comment by faustaahmad** [comment]
If it's actually a button
"switch to ... lyrics" would be appropriate
The problem it's a line of words, so user wont expect to click that line to switch lyrics
I did a small adjustment to english wording for the line (crowdin)
"click this to switch to ... lyrics"

**Comment by faustaahmad** [comment]
You can disable that timer icon in player appearance settings
"Show total queue duration"

**Comment by fast4x** [comment]
@AnyoneMouse shuffle is one mode action not on or off, it shuffle songs one time wheb click

**Comment by fast4x** [comment]
Increased text size for artist and album, available from version 0.6.37
