### ISSUE TITLE
[Feature]: Add an option to set the floating button to the left or disable it

### ISSUE THREAD

**Issue by fofxox** [fast4x/RiMusic#1505]
### Description

The floating button resets to the bottom-right corner each time I open the app.

### Suggested Solution

Let me keep the button always on the left side.  When floating button is disabled, the settings button should return where it used to be in older versions.

**Comment by fast4x** [comment]
What type of navigation bar type you use ?

**Comment by fofxox** [comment]
Left side navigation bar, but I would not like to change it. Hopefully I can set up the floating button position independently of the nav bar

-------- Original Message --------

**Comment by fast4x** [comment]
Would you like to move the button to a position and keep it fixed until you move it again?

**Comment by fofxox** [comment]
That would be useful, but I would also like to disable the floating button.  The "double tap for settings" is hard to get right every time, and I don't think new users will know how to use it.

**Comment by fast4x** [comment]
Like before will be available only in vimusic ui mode
