### ISSUE TITLE
Duplicate menu buttons in landscape mode

### ISSUE THREAD

**Issue by fofxox** [fast4x/RiMusic#1507]
### Steps to reproduce the bug

Enable "show menu button" on the bottom player action bar.

Rotate the screen to landscape.

### Expected behavior

Only one menu button shows up

### Actual behavior

There are two menu buttons that do the same thing.  One that I manually enabled, and one that only shows up in landscape mode.

### Screenshots/Screen recordings

![Screenshot_20240413_050914](https://github.com/fast4x/RiMusic/assets/130255231/54548c1d-ac68-4e2c-9117-e3c571b060a5)
![Screenshot_20240413_050921](https://github.com/fast4x/RiMusic/assets/130255231/faf85928-5fc3-4316-bd77-af9396c46187)

### RiMusic version

0.6.30

### Android version

Android 14

**Comment by fast4x** [comment]
Fixed, available from version 0.6.31
