### ISSUE TITLE
Songs are missing in playlist imported from YouTube

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1508]
### Steps to reproduce the bug

1. Copy playlist link
2. Paste it in 'go to link'

### Expected behavior

All the songs should appear in the list

### Actual behavior

Only 100 songs appear

### RiMusic version

0.6.30

### Android version

Android 13

### Additional information

This bug was fixed in this latest version but it looks like it's still not fixed

https://music.youtube.com/playlist?list=PLAnme0ot1hod_g3wBzKdAoKhLhmVqm3Na&si=f1W0dWPz5Y3ArE--

349 tracks. Only 100 appears

When I first added the playlist all the songs except 3-4 songs appeared. When I synced the playlist for 3-4 times the list reduced to 100 and after that it never added all the songs

**Comment by sebbekm** [comment]
I have the same problem when syncing a playlist. Sometimes it works as expected, other times it just syncs 100 songs and I have to manually add the playlist again

**Comment by aneesh1122** [comment]
> I have the same problem when syncing a playlist. Sometimes it works as expected, other times it just syncs 100 songs and I have to manually add the playlist again

Initially most of the songs were imported successfully. Songs disappeared after I synced it for a few times. Now I'm not able to get back those songs no matter how many times I sync or manually add that playlist.

**Comment by fast4x** [comment]
Improved, available from version 0.6.31

**Comment by NightFly88** [comment]
I have the same problem, I add a song and it is nowhere and not visible

**Comment by fast4x** [comment]
Can you add here a link to this playlist?
