### ISSUE TITLE
Extra Padding due to Character length in names of Playlists

### ISSUE THREAD

**Issue by Sofia-0fficial** [fast4x/RiMusic#1509]
### Steps to reproduce the bug

![Screenshot_2024-04-13-19-22-08-00](https://github.com/fast4x/RiMusic/assets/166928115/ce32e2c8-ac00-4b22-bf92-ce7d038dbf24)

### Expected behavior

Large titles should be forced on the next line.

### Actual behavior

Extended the padding to adjust the length of title of play list.

### Screenshots/Screen recordings

![Screenshot_2024-04-13-19-22-08-00](https://github.com/fast4x/RiMusic/assets/166928115/2abf6130-d129-4028-b6ae-7ae04eb79a27)
![Screenshot_2024-04-13-19-46-31-27](https://github.com/fast4x/RiMusic/assets/166928115/dda56c06-0865-4937-b712-075dd1bf313a)

### RiMusic version

0.6.30

### Android version

Android 12

**Comment by fast4x** [comment]
Fixed, available from version 0.6.31

**Comment by Sofia-0fficial** [comment]
Well that was fast .

And thanks Keep up the good work ❤️
