### ISSUE TITLE
[Part 1] : Weird Home UI and improvements to make

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1513]
### Description

I was inactive for a bit and when i came back the UI changed so much.
Honestly i hate the changes but i got some improvements that can make the new UI very cool!

If some of my ideas dont suit someone tastes dont hesitate to communicate we can find a in between.
Also sorry if my editing is poor because i'm rushing this a bit.

### Suggested Solution

1. Top UI on the home screen
I think that the logo shouldn't be centered but should depend on the right and left setting also the big buttons dont respect the rest of the UI
Curent :
![image](https://github.com/fast4x/RiMusic/assets/104271365/e4324ffd-f861-4693-9ae3-11a9d7f0c371)
Idea :
![image](https://github.com/fast4x/RiMusic/assets/104271365/911d14d6-ca82-4716-a287-f60a47b25387)

2. Popup button
Get rid of the popup button or maybe add it as an accessibility option to easily open things
Context :
![image](https://github.com/fast4x/RiMusic/assets/104271365/d6a48d05-5043-4cec-8a09-44bacfc0f7a4)

3. Separate some options
Make an option for choosing between left bar, bottom bar, top bar
The Right bar option will be replaced by a Left Handed option that will just flip some UI elements (If the bottom bar or top bar is selected then the icons order will be swapped)
Concept :
![image](https://github.com/fast4x/RiMusic/assets/104271365/c79b7b16-c0c1-4eeb-a427-1e9f0157fa5e)

### Additional Context

This is the part 1 because i have ideas for the search and albums, likes, etc... too!

Also sorry that i rushed this is pretty late for me and i have a lot of school work ask me any question if you didn't understood something or you want a new idea for something specific

**Comment by fast4x** [comment]
Your concept is cool!

**Comment by sayyid5416** [comment]
I like the idea 🤝

**Comment by fast4x** [comment]
I can to develop it? 😂😂😂😂

**Comment by dAtA-TRoN** [comment]
It's cool.

**Comment by fast4x** [comment]
I think to make it available only in RiMusic ui mode...

**Comment by dAtA-TRoN** [comment]
> I think to make it available only in RiMusic ui mode...

https://github.com/fast4x/RiMusic/assets/71184627/cb7e6069-63d2-4581-a81a-727bbb5a9491

**Comment by dAtA-TRoN** [comment]
Still waiting for [Part 2].

Promising the moon and delivering moon dust 🌙😏...

**Comment by fast4x** [comment]
Wait....

**Comment by dAtA-TRoN** [comment]
> Wait....

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/c4f5ebc6-16c0-4e9e-941e-d052bdf2d633)

**Comment by fast4x** [comment]
![giphy (3).gif](https://github.com/fast4x/RiMusic/assets/1484476/71283c1f-b2df-4ac9-8802-fa31f8b724f1)

**Comment by NikunjKhangwal** [comment]
I like the idea of pop-up but can somebody explain where search button will be located with these changes?

**Comment by sayyid5416** [comment]
top-right corner

**Comment by NikunjKhangwal** [comment]
Is floating search button going to stay or not? Will it be optional? I love having search right on thumb position.

**Comment by sayyid5416** [comment]
Most probably, it will be removed. Or maybe fast4x could make it available.

**Comment by OrangeZXZ** [comment]
> Is floating search button going to stay or not? Will it be optional? I love having search right on thumb position.

I think the floating icon should be an accessibility option that help people access easily buttons that are at the top

But maybe a setting to move the top bar down would be a idea (if you dont mid having the logo bellow

**Comment by sayyid5416** [comment]
> But maybe a setting to move the top bar down would be a idea

It would be bad design wise, specially when using bottom navigation bar.

**Comment by NikunjKhangwal** [comment]
I hope it stays and becomes optional. I'll hate moving my thumb on top of screen everytime for searching something when it's so easy now.

**Comment by fast4x** [comment]
Develpement started... :)

**Comment by OrangeZXZ** [comment]
> Development started... :)

You should send pictures from time to time to prevent extra work and to discus if we are keeping things

**Comment by NikunjKhangwal** [comment]
Living by the name 👌🏼

**Comment by dAtA-TRoN** [comment]
> Development started... :)

![_7e0056b4-a686-4c44-9917-d9f092d96117.jpeg](https://github.com/fast4x/RiMusic/assets/71184627/dca9947e-8d33-42cd-a946-708f2e3d7d51)

**Comment by fast4x** [comment]
Preview...

https://github.com/fast4x/RiMusic/assets/1484476/5b5c3593-b505-41d0-bbef-0796c16fd855

**Comment by OrangeZXZ** [comment]
> Preview...

This looks already verry cool imo!

I just think that the title is a bit off for now maybe try removing some space or maybe make it go to the left to match other text element

Also imo the title of the page could stay at the top when the top bar is hidden to always know where we are

Also the RiMusic logo is just an image or it changes colors?

That's a lot of "Also" 😂

**Comment by OrangeZXZ** [comment]
> I just think that the title is a bit off for now maybe try removing some space or maybe make it go to the left to match other text element

It could also just replace the RiMusic logo if the text is at the left (The icons stays)

**Comment by fast4x** [comment]
icon remain green and text change color based on theme...

**Comment by OrangeZXZ** [comment]
> icon remain green and text change color based on theme...

Maybe it could be cool to have the icon it change with the theme like before but we should have more peoples accept my idea

**Comment by fast4x** [comment]
Of course, it require a new logo with dynamic color. Waiting for other user...

**Comment by fast4x** [comment]
Also navigation may be improved later

**Comment by fast4x** [comment]
> I hope it stays and becomes optional. I'll hate moving my thumb on top of screen everytime for searching something when it's so easy now.

it show in ViMusic ui mode

**Comment by fast4x** [comment]
> Most probably, it will be removed. Or maybe fast4x could make it available _(as optional)_.

it show in ViMusic ui mode

**Comment by OrangeZXZ** [comment]
> it show in ViMusic ui mode

ViMusic had an floating icon? or is it temporary

**Comment by fast4x** [comment]
Not floating, fixed...like before

**Comment by sayyid5416** [comment]
Are there 2 search button on purpose?

**Comment by OrangeZXZ** [comment]
> Are there 2 search button on purpose?

There is an option to add the search in the bar too

**Comment by OrangeZXZ** [comment]
I noticed the bottom bar is at the top of the miniplayer that should be changed I think

**Comment by dAtA-TRoN** [comment]
> I noticed the bottom bar is at the top of the miniplayer that should be changed I think

Lol I think sayyid5416 said the same thing and I agree. Fast4x said it's difficult to implement at the moment.

**Comment by sayyid5416** [comment]
Oh man there are so many issues, some duplicates, some opposite to each other, they are being missed. What a mess! 😅

**Comment by fast4x** [comment]
> Are there 2 search button on purpose?

Only one in top bar, floating search goodbye, it's available fixed for RiMusic ui mode.

**Comment by fast4x** [comment]
> > I noticed the bottom bar is at the top of the miniplayer that should be changed I think
> 
> Lol I think sayyid5416 said the same thing a few days earlier and I agree. fast4x said it's difficult to implement at the moment, so we have to wait I guess.

Yes i confirm, for now not possible.

**Comment by NikunjKhangwal** [comment]
> it show in ViMusic ui mode

Nice. I use Vi mode

**Comment by NightFly88** [comment]
> Preview...
> 
>  Screen_recording_20240414_220919.mp4

Wow i love this

**Comment by sayyid5416** [comment]
> Maybe i can anticipate the functionality that allows you to keep the same actions in all pages. If confirmed, the user may have the same menu on all pages.

that would be great

**Comment by OrangeZXZ** [comment]
> Maybe i can anticipate the functionality that allows you to keep the same actions in all pages. If confirmed, the user may have the same menu on all pages.

if the top bar can be everywhere instead of playing, playlists, settings like on youtube it would be awesome

**Comment by OrangeZXZ** [comment]
> development continue... the test on the new navigation is promising...
> 
> https://github.com/fast4x/RiMusic/assets/1484476/d1ea8a5d-7740-4d27-a768-b1cefd0c23fa
> 
> 

In my opinion it only needs the logo change colors and the pop-up for the settings to be dinamic

**Comment by fast4x** [comment]
@ikanakova

**Comment by fast4x** [comment]
> and the pop-up for the settings to be dinamic

what you mean for dynamic?

**Comment by OrangeZXZ** [comment]
> > and the pop-up for the settings to be dinamic
> 
> what you mean for dynamic?

The white pop-up when you press the top right icon should change colors to match the UI

**Comment by fast4x** [comment]
> > > and the pop-up for the settings to be dinamic
> > 
> > 
> > what you mean for dynamic?
> 
> The white pop-up when you press the top right icon should change colors to match the UI

ahhhhhhhh ok yes ogf course

**Comment by fast4x** [comment]
Preview back button always on top...

https://github.com/fast4x/RiMusic/assets/1484476/dfbcaf41-d0a5-46f1-86e7-8046e383e11f

**Comment by OrangeZXZ** [comment]
> Preview back button always on top...
> 
> https://github.com/fast4x/RiMusic/assets/1484476/dfbcaf41-d0a5-46f1-86e7-8046e383e11f
> 
> 

hmmm not sure about having it at the top right because every app has it at the top left maybe it can replace or add nex to the logo?

Also on youtube the search bar is in the top bar maybe doing same thing?

IDK maybe someone as another opinion

**Comment by OrangeZXZ** [comment]
Forget about what i said i think we can center the logo and put the back button at the left

**Comment by fast4x** [comment]
Meanwhile now is all dynamic...

https://github.com/fast4x/RiMusic/assets/1484476/8fdfd3f7-ee92-4720-bf5a-9ff4eec79e31

**Comment by OrangeZXZ** [comment]
> Meanwhile now is all dynamic...
> 
> https://github.com/fast4x/RiMusic/assets/1484476/8fdfd3f7-ee92-4720-bf5a-9ff4eec79e31
> 
> 

I think the text can stay white or black bug good job

**Comment by fast4x** [comment]
Fixed topbar navigation... can be activated by settings, I would fix it by default...

https://github.com/fast4x/RiMusic/assets/1484476/3e4c9b9d-ad5f-4683-8f53-bbf5898903de

**Comment by sayyid5416** [comment]
Looking great 🔥 Finally all inconsistent back buttons could be removed

**Comment by fast4x** [comment]
Yes absolutely, work in progress for migration.

**Comment by NikunjKhangwal** [comment]
> This will also keep the same look as the player (but with the full logo) If this is the case maybe peoples will like the minimal icon more maybe a setting to switch between full logo and minimal icon
> Edit : Keeping the full logo outside of the player and the minimal logo in player is the best option imo

How about replacing "Music" with the respective tab name? Like "Quick Picks", "History" etc.

**Comment by dAtA-TRoN** [comment]
> How about replacing \"Music\" with the respective tab name? Like \"Quick Picks\", \"History\" etc.

It makes sense, as not everyone uses 'quick picks' as the default page anyway. So, there's no need for the RiMusic logo to greet you on some random page. So it seems somewhat nonsensical.

**Comment by dAtA-TRoN** [comment]
> > How about replacing \"Music\" with the respective tab name? Like \"Quick Picks\", \"History\" etc.
> 
> It makes sense, as not everyone uses 'quick picks' as the default page anyway. So, there's no need for the RiMusic logo to greet you on some random page. It seems somewhat nonsensical.

Unless the 'RiMusic' logo shifts accordingly, depending on the selected homepage. I think that would be rather neat. Below that, the page name could still be included. Perhaps the RiMusic logo doesn't need to be displayed as prominently in that scenario 🤔.

**Comment by OrangeZXZ** [comment]
> It makes sense, as not everyone uses 'quick picks' as the default page anyway. So, there's no need for the RiMusic logo to greet you on some random page. It seems somewhat nonsensical.

This logo is more decorative and for branding (like youtube) it always stays at the top it could be nice to have the category name but what animation on switch, do we have enough space?

Apps like youtube dont say what page you are in because it is easely visible and there is the text at the bottom of the icon

**Comment by dAtA-TRoN** [comment]
> This logo is more decorative and for branding (like youtube) it always stays at the top it could be nice to have the category name but what animation on switch, do we have enough space?

I have no idea, but I wouldn't want to lose the 'RiMusic' logo either. What do you think of my idea for it to move along? So it changes depending on which homepage you have set?

**Comment by fast4x** [comment]
Be careful the idea is good, but there is a risk that RiMusic becomes a copy of another app and I don’t want that.

**Comment by fast4x** [comment]
The name of the page could be written under RiMusic with a small font.

**Comment by dAtA-TRoN** [comment]
> The name of the page could be written under RiMusic with a small font.

And what do you think about the idea that the RiMusic logo moves with the selected default page? This way, you'll also be greeted appropriately when opening the app, even if Quick Picks isn't the default page. Plus, it would highlight the newly selected default page as well.

**Comment by OrangeZXZ** [comment]
> And what do you think about the idea that the RiMusic logo moves with the selected default page? This way, you'll also be greeted appropriately when opening the app, even if Quick Picks isn't the default page. Plus, it would highlight the newly selected default page as well.

what do you mean i didn't quite understood

**Comment by NikunjKhangwal** [comment]
> The name of the page could be written under RiMusic with a small font.

Yeah i guess that might work too.

**Comment by dAtA-TRoN** [comment]
> what do you mean i didn't quite understood

Currently, the 'RiMusic' logo only appears on the quick picks page, as it's the official default page of RiMusic. However, if you change the 'default page' in the settings, the app will no longer display the RiMusic logo upon opening. I believe it would be beneficial if the logo dynamically appeared on whichever page is selected as the homepage. Not only would that be a cool detail, it would also better highlight the self-selected default page. Does that make sense?

**Comment by OrangeZXZ** [comment]
> > what do you mean i didn't quite understood
> 
> Currently, the 'RiMusic' logo only appears on the quick picks page, as it's the official default page of RiMusic. However, if you change the 'default page' in the settings, the app will no longer display the RiMusic logo upon opening. I believe it would be beneficial if the logo dynamically appeared on whichever page is selected as the homepage. Not only would that be a cool detail, it would also better highlight the self-selected default page. Does that make sense?

I thought that the top bar was always active

**Comment by dAtA-TRoN** [comment]
> I thought that the top bar was always active (the one with the logo)

lol, I just noticed that now. So, forget what I said 😅.

**Comment by fast4x** [comment]
Implemented, available new navigation system in version 0.6.31
Preview...
[Screen_recording_20240416_185522.webm](https://github.com/fast4x/RiMusic/assets/1484476/89be41a9-124f-40e1-8b34-29fb7b2660cc)

**Comment by sayyid5416** [comment]
Wow, looking great.
![JagyasiniSinghAwesomeGIF](https://github.com/fast4x/RiMusic/assets/78584556/274524de-3e27-4e8e-bf8b-a56f094e61c0)

Can you share ss of player page?

**Comment by fast4x** [comment]
> Wow, looking great. ![JagyasiniSinghAwesomeGIF](https://private-user-images.githubusercontent.com/78584556/322936336-274524de-3e27-4e8e-bf8b-a56f094e61c0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODc2NDEsIm5iZiI6MTcxMzI4NzM0MSwicGF0aCI6Ii83ODU4NDU1Ni8zMjI5MzYzMzYtMjc0NTI0ZGUtM2UyNy00ZThlLWJmOGItYTU2ZjA5NGU2MWMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE3MDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZDE4ODdhZjg2YzI1NDVmYzhhZDExNGZhMTc3MGFiYmMyMzc1ZmUxODMxMTM5ZGQzMzYxM2QyOTRiMjVlZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.POsfrloVF9A4YOkBaiWFfwfts3fyigffkhS5i5bMPDg) [ ![JagyasiniSinghAwesomeGIF](https://private-user-images.githubusercontent.com/78584556/322936336-274524de-3e27-4e8e-bf8b-a56f094e61c0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODc2NDEsIm5iZiI6MTcxMzI4NzM0MSwicGF0aCI6Ii83ODU4NDU1Ni8zMjI5MzYzMzYtMjc0NTI0ZGUtM2UyNy00ZThlLWJmOGItYTU2ZjA5NGU2MWMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE3MDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZDE4ODdhZjg2YzI1NDVmYzhhZDExNGZhMTc3MGFiYmMyMzc1ZmUxODMxMTM5ZGQzMzYxM2QyOTRiMjVlZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.POsfrloVF9A4YOkBaiWFfwfts3fyigffkhS5i5bMPDg) ](https://private-user-images.githubusercontent.com/78584556/322936336-274524de-3e27-4e8e-bf8b-a56f094e61c0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODc2NDEsIm5iZiI6MTcxMzI4NzM0MSwicGF0aCI6Ii83ODU4NDU1Ni8zMjI5MzYzMzYtMjc0NTI0ZGUtM2UyNy00ZThlLWJmOGItYTU2ZjA5NGU2MWMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE3MDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZDE4ODdhZjg2YzI1NDVmYzhhZDExNGZhMTc3MGFiYmMyMzc1ZmUxODMxMTM5ZGQzMzYxM2QyOTRiMjVlZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.POsfrloVF9A4YOkBaiWFfwfts3fyigffkhS5i5bMPDg) [ ](https://private-user-images.githubusercontent.com/78584556/322936336-274524de-3e27-4e8e-bf8b-a56f094e61c0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODc2NDEsIm5iZiI6MTcxMzI4NzM0MSwicGF0aCI6Ii83ODU4NDU1Ni8zMjI5MzYzMzYtMjc0NTI0ZGUtM2UyNy00ZThlLWJmOGItYTU2ZjA5NGU2MWMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE3MDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZDE4ODdhZjg2YzI1NDVmYzhhZDExNGZhMTc3MGFiYmMyMzc1ZmUxODMxMTM5ZGQzMzYxM2QyOTRiMjVlZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.POsfrloVF9A4YOkBaiWFfwfts3fyigffkhS5i5bMPDg)
> 
> Can you share ss of player page?

Player is the same... full page without top bar...

**Comment by sayyid5416** [comment]
Can you increase left and right margin of these colored headings - they look very close to the edge of screen.

![image](https://github.com/fast4x/RiMusic/assets/78584556/da949b34-5b87-4cd0-b38c-e9062bcd5424)

![image](https://github.com/fast4x/RiMusic/assets/78584556/fec4900e-ec78-459c-8157-ec781003d168)

**Comment by privacyfreak84** [comment]
Will the floating search button stay (I love that)

**Comment by OrangeZXZ** [comment]
> Will the floating search button stay (I love that)?

maybe not the next update...

**Comment by NikunjKhangwal** [comment]
Fast4x said it'll stay in ViMusic mode

**Comment by OrangeZXZ** [comment]
> Fast4x said it'll stay in ViMusic mode 

I think he is talking about the floating button at the bottom right but not the movable one

**Comment by NikunjKhangwal** [comment]
> I think he is talking about the floating button at the bottom right but not the movable one

That's not what "floating" means. It's a fixed button in navigation bar. If that's the case then he also has the wrong idea about it.

**Comment by OrangeZXZ** [comment]
>  > I think he is talking about the floating button at the bottom right but not the movable one
> 
> That's not what "floating" means. It's a fixed button in navigation bar. If that's the case then he also has the wrong idea about it.

no im just wrong sorry

**Comment by NikunjKhangwal** [comment]
No worries

**Comment by fast4x** [comment]
"Fixed" search button remain available only in ViMusic mode.

**Comment by NikunjKhangwal** [comment]
> "Fixed" search button remain available only in ViMusic mode.

Just to confirm again, you're talking about this right?

![IMG_20240419_172259](https://github.com/fast4x/RiMusic/assets/99175083/0bf63072-ff3b-402d-a708-c4cade83f1ad)

**Comment by fast4x** [comment]
Also

**Comment by NikunjKhangwal** [comment]
Also what? Sorry, i didn't get it

**Comment by OrangeZXZ** [comment]
> Also what? Sorry, i didn't get it

this search icon is an setting you could have both (floating and in bar)

**Comment by NikunjKhangwal** [comment]
> this search icon is an setting you could have both (floating and in bar)

Ok that's nice 👌🏼
