### ISSUE TITLE
Search button popup can be placed outside of screen safe space

### ISSUE THREAD

**Issue by headquarter8302** [fast4x/RiMusic#1518]
### Description

See bottom right
![Screenshot_20240414_094720](https://github.com/fast4x/RiMusic/assets/65797058/378bcf56-97a6-4a28-b256-d56453452842)

I was able to drag the search popup outside of the usable screen space, beyond the safe space of a touch screen.

### Suggested Solution

Limit the position of the draggable popup to just inside the user's screen space, preferably having a bit of space preventing it from touching the edge at all

### Additional Context

I wasn't able to open the settings menu until I searched here in issues, the double click to open the settings must be either communicated clearly to the user, or maybe take a completely different direction

**Comment by fast4x** [comment]
will be removed, take a look this #1513
