### ISSUE TITLE
["bug"/improvement] Skip song on error

### ISSUE THREAD

**Issue by aRandomMenno** [fast4x/RiMusic#1519]
### Description

When playing a song, sometimes it says something like original media of song deleted however it then just stops playback.

### Suggested Solution

So I suggest that when it stops it actually just skips that song. And plays the next one.
Extra: you can also make it so somewhere (idk where) you can see which songs were skipped because of this with the "error" message.

**Comment by OrangeZXZ** [comment]
I think you could add a timer before directly skipping the song (3 or 5 seconds) that way we know if a song is not playing
