### ISSUE TITLE
[Part 2] : Enchantements to the search page

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1520]
### Description

The search page is not bad like this but it could get an upgrade.

This is an extension for this issue : #1513

### Suggested Solution

1. Top Icons
The top icons always stay up regardless of what setting you chose
I think that it should switch between left bar, right bar, bottom and top bar depending on the setting
Also the back icon should be at the top right it is the most logical placement and the search icon at the left is useless
Concept :
![image](https://github.com/fast4x/RiMusic/assets/104271365/0f9724a9-6917-400b-9c22-3e48b8a5b8b6)

2. Icons missing on search results
On recent searches we have a clock icon but on propositions we dont have any
YouTube is using a search icon and i think RiMusic should too
Context :
![image](https://github.com/fast4x/RiMusic/assets/104271365/db6a784e-ea54-47d6-a81f-92141530523c)
Concept :
![image](https://github.com/fast4x/RiMusic/assets/104271365/5ed6a016-1e06-40ec-b539-e33870001ef9)

### Additional Context

I will maybe do a part 3 that talks about the playlists and play screen

This part is pretty short since it already is almost perfect in my opinion

**Comment by dAtA-TRoN** [comment]
![proxy-image(2).gif](https://github.com/fast4x/RiMusic/assets/71184627/847ca0d2-2690-42c5-8e88-ebf5dffdcfc0)

**Comment by NikunjKhangwal** [comment]
Search bar on top and icons on bottom will create a displacement gap. You have to tap on bottom to press any icon and then on top to write something. Also search automatically triggers the keyboard so those icons will be hidden under it. Additional work is needed for icons to respect keyboard position.
I would say keep top search bar and icons for bottom nav as well unless it's properly implemented.

**Comment by OrangeZXZ** [comment]
> Search bar on top and icons on bottom will create a displacement gap. You have to tap on bottom to press any icon and then on top to write something. Also search automatically triggers the keyboard so those icons will be hidden under it. Additional work is needed for icons to respect keyboard position.
> I would say keep top search bar and icons for bottom nav as well unless it's properly implemented.

Then for now just dont use bottom icons in this menu until they show on top of the keyboard?

**Comment by sayyid5416** [comment]
Good concept. One suggestion:
- back button should be consistent with back button position in the rest of the app.

**Comment by OrangeZXZ** [comment]
> Good concept. One suggestion:
> - back button should be consistent with back button position in the rest of the app.

Yes i agree it is not reachable but every app has them there

But maybe add an option to move the top bar at the bottom would be nice for an accessibility category in the settings

**Comment by sayyid5416** [comment]
Take a look at #1389, maybe you would like some ideas from there.

**Comment by NikunjKhangwal** [comment]
> Then for now just dont use bottom icons in this menu until they show on top of the keyboard?

Exactly

**Comment by fast4x** [comment]
Implemented, based on new navigation system, available from version 0.6.31

**Comment by fast4x** [comment]
> Take a look at #1389, maybe you would like some ideas from there.

Done

**Comment by NikunjKhangwal** [comment]
So just what i said icons are hidden under keyboard and there's a gap between search box and previous entries.

**Comment by fast4x** [comment]
Screenshot please.

**Comment by NikunjKhangwal** [comment]
Here

![IMG_20240420_122832](https://github.com/fast4x/RiMusic/assets/99175083/cf7dfce5-cb7d-4aab-9cd5-48bcfc660a07)
