### ISSUE TITLE
[Part 3] : Enhancements for playlists

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1523]
### Description

Playlists changed a bit and i find them good enough but i can still propose some changes.

This is an extension for issue #1513 and #1520

### Suggested Solution

1. Local Playlists arent like YouTube Playlists
I think that all playlists should have the same aspect and i think the best aspect to keep is the one we have on liked.
You can try to use the same code for all playlists that way we have less non similar menues.
Context :
![image](https://github.com/fast4x/RiMusic/assets/104271365/18b7b13a-d6d8-44ef-b582-6b5f6e62d6d3)
Concept Ideas :
![image](https://github.com/fast4x/RiMusic/assets/104271365/7846fcb5-c873-4dc4-bbad-4a2438a29f43)
Concept : 
![image](https://github.com/fast4x/RiMusic/assets/104271365/3ab6a9b3-6836-4fde-b46b-1abe2ba644ec)

2. Download icon position
I dont hate the curent icon placement but i think there are other options to consider to make the text less moved apart
Curent : 
![image](https://github.com/fast4x/RiMusic/assets/104271365/89e58099-3b2e-4bff-88d3-3a0889670a33)
Concept :
Its logical to put next to the time because you are downloading the time (technically)
![image](https://github.com/fast4x/RiMusic/assets/104271365/9ffccc94-5da6-4940-9c52-bbe39dde5f77)
![image](https://github.com/fast4x/RiMusic/assets/104271365/de003ef5-5a0f-4cef-ab62-53883b02dbb8)

3. Names on quick picks
Artists have centered names but not albums
curent :
![image](https://github.com/fast4x/RiMusic/assets/104271365/f013806a-89fa-49ea-b1d7-f71c940211a7)
concept :
![image](https://github.com/fast4x/RiMusic/assets/104271365/bb143fc8-16d6-4f64-832b-f83cc328d6bb)

### Additional Context

Sorry for all the mistakes in the writing i rush this too much and i shouldn't but i would never finish these if not

Also thinking about the part 4 (last part) i will discus about the player

**Comment by dAtA-TRoN** [comment]
I must disagree with the idea of not displaying album art in playlists. Album art is very helpful for orientation and locating individual tracks. While minimalism is nice, in my opinion, design is once again prioritized over practicality. I don't like that at all. Otherwise, good ideas again.

...waiting for [Part 4].

**Comment by OrangeZXZ** [comment]
> I disagree with the notion of omitting album art from playlists. Album art plays a crucial role in orientation and identifying individual tracks, especially when I'm unfamiliar with their titles. It's the covers that guide me through the playlist. While minimalistic design has its appeal, I feel that prioritizing it over practicality undermines the user experience. Overall, I appreciate your other nice ideas here.
> 
> ...waiting for [Part 4].

We could have the album covers and the hearth at the middle on top that way we can easily see that is the liked playlist

**Comment by dAtA-TRoN** [comment]
> We could have the album covers and the hearth at the middle on top that way we can easily see that is the liked playlist

Couldn't care less about anything else, but for heaven's sake, don't you dare take away the cover. And yes, numbering is absolutely crucial! I've been missing it painfully for so long. Where on earth is [Part 4] 🤔😁!?

**Comment by fast4x** [comment]
I agree on the covers, the playlist without covers is like the head of a bald 😜😜😂😂😂

**Comment by dAtA-TRoN** [comment]
> like the head of a bald

What kind of ludicrous remark is that? 😶 🤣🤣🤣🤣🤣"

**Comment by fast4x** [comment]
Because I’m bald, my hair would look better! 😂😂😂😂😂 The playlist with the covers is nice.

**Comment by OrangeZXZ** [comment]
> I agree on the covers, the playlist without covers is like the head of a bald 😜😜😂😂😂

My bad the numbers is only for albums but i referred as online playlists

**Comment by sayyid5416** [comment]
I've mixed feelings about some of these, but I'll just wait and watch on this

**Comment by fast4x** [comment]
Implemented, available from version 0.6.31

**Comment by fast4x** [comment]
Share, number position and follow in't usable in playlist like favorites or downloaded etc....
