### ISSUE TITLE
[Part 4] : Enhancements for play menu

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1524]
### Description

There are lots of tiny changes to make to the play menu to make it more professional.

This is an extension for issue #1523 and #1520 and #1513

### Suggested Solution

1. Play menu look and dark dinamic colors
Curent :
![image](https://github.com/fast4x/RiMusic/assets/104271365/251ecec7-7d79-4291-8c48-8a243ff3642a)
Concept :
![image](https://github.com/fast4x/RiMusic/assets/104271365/5e05fb6f-48f6-450a-b48a-244fe1c2870b)

2. Next Songs
The current next songs is pretty bad
I find it more logical to have the previous song and next song shown at the bottom of the skip and unskip buttons
Or maybe to replace the skip and unskip buttons (i like this idea less)
Concept 1 :
![image](https://github.com/fast4x/RiMusic/assets/104271365/9476f8ce-7312-4e3b-9186-590d04b651d5)
Concept 2 :
![image](https://github.com/fast4x/RiMusic/assets/104271365/6ea1014c-e39f-49ea-ae5b-ec6a68840104)

3. Bring back the horizontal player
Before a horizontal player was possible but now you cant it disable automatically
Just bring it back when you flip the phone

4. The arrow on the burger menu
The arrow in the burger menu feels verry weird vit should be removed the burger menu should have a maximum height at the opening then move up if we scroll to take less space
Curent :
![image](https://github.com/fast4x/RiMusic/assets/104271365/7cb3aa4c-6756-42c4-9b34-4cb7d3021e40)
Concept :
![image](https://github.com/fast4x/RiMusic/assets/104271365/086c082a-4d8b-4100-95a7-3c0aefa3f042)

I also had a completely new design idea (Inspired out of TikTok) :
![image](https://github.com/fast4x/RiMusic/assets/104271365/db06f4a5-0c79-4b31-adb3-4681872865f7)

5. Song informations at the top of the queue
Add some space a pill or arrow if no pill (in yellow on the image) also add bellow this the same song informations as the burger menu (like on youtube) this menu should be colored on the dark mode in my opinion like on youtube music
The pill bellow should be removed since the bottom bar is not a pull menu
The up button should always be on when not at the top and should show colored at the top of the bottom bar
![image](https://github.com/fast4x/RiMusic/assets/104271365/f2ec3906-4ffc-481a-ac1f-c915531d29ae)

### Additional Context

Sorry for all the mistakes in the writing i rush this too much and i shouldn't but i would never finish these if not

This is the and of the parts I'm still going to make issues but separated for tiny things i just wanted to give the UI a new and cool look because the curent UI was going the wrong way

**Comment by OrangeZXZ** [comment]
I forgot to add one thing

When we double tap the cover a heart should appear and disappear to easily know that the action is taken
![image](https://github.com/fast4x/RiMusic/assets/104271365/175530bb-85e9-4ffc-bacc-46724216e812)

**Comment by sayyid5416** [comment]
1. In `point 1`, I agree with everything other than this
![image](https://github.com/fast4x/RiMusic/assets/78584556/24a6cb63-12d1-4ae2-9c02-ca1f75dc0242)

**Comment by OrangeZXZ** [comment]
> 1. In `point 1`, I agree with everything other than this
> ![image](https://github.com/fast4x/RiMusic/assets/78584556/24a6cb63-12d1-4ae2-9c02-ca1f75dc0242)
> 

I toughts that the pressing animation should match the button you dont feel the same?

**Comment by sayyid5416** [comment]
Play button animation, and shape should be bigger than both other buttons _(same as now)_

**Comment by NikunjKhangwal** [comment]
Replacing skip buttons with next songs will look ugly imo. Also there's already a issue about adding some lyric line in the empty space below buttons. #1397
Nice suggestions about the menu. I've suggested swipe down to close menu's before, more space for closing menu will not be needed then. Also there's a new Grid style menu if you haven't checked it out yet. It's exactly the size you mentioned here.

**Comment by sayyid5416** [comment]
> ![image](https://github.com/fast4x/RiMusic/assets/78584556/77bc049d-ef76-446e-9ac8-05234cced8ff)

100%

**Comment by OrangeZXZ** [comment]
> Also there's a new Grid style menu if you haven't checked it out yet. It's exactly the size you mentioned here.

I didn't knew what that meant it think it looks better I will use that

**Comment by NikunjKhangwal** [comment]
Go to settings > Menu style

**Comment by OrangeZXZ** [comment]
> For point 2 I'd like if only song name shows there without cover art. And replacing with skip/unskip button is a bad idea I think.

the namem and time bellow the buttons could be nice

**Comment by fast4x** [comment]
This is too old
