### ISSUE TITLE
[Feature]: Properly Label Settings 

### ISSUE THREAD

**Issue by Glich440** [fast4x/RiMusic#1525]
### Description

A few settings have a "default" option that's actually not default

### Suggested Solution

Rename options to properly indicate which one is the default

**Comment by faustaahmad** [comment]
Few? Afaik just two options
If you have better wording, please share your thoughts
• Default page
Default keep last page/tab even when app force closed
• Play Button
Default ViMusic style

**Comment by Glich440** [comment]
An example is the theme

**Comment by fast4x** [comment]
I don't understand

**Comment by Glich440** [comment]
Ok, I just rechecked the settings and it seems I imagined it, sorry for the incovienence
