### ISSUE TITLE
A Thought-Provoking Proposal for a Radical Overhaul of App Navigation

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1528]
### Description

I find the current implementation of the main navigation rather lacking. It's confusing for several reasons: Firstly, the navigation bar changes depending on the context, and secondly, it often disappears entirely. In my opinion, this is a peculiar design choice. I believe the main navigation should remain accessible at all times and should not change regardless of where you are in the app.

### Examples

**1. The Artist Tab:** When selecting an artist in the Artist main navigation tab, not only does the main navigation change by hiding two icons and adding a new one, but the meaning behind the symbols also suddenly changes without any visual alteration. While the symbols represent the same functions, they are now context-specific to the selected artist. This behavior dilutes the clarity of the main navigation bar and introduces a sense of inconsistency into the app's navigation.

![ZomboDroid_15042024094611](https://github.com/fast4x/RiMusic/assets/71184627/7b1c18c7-1a64-4c2a-8809-bd7684556e7e)

**2. The Library Tab:** When a playlist is selected within the Library Tab, the main navigation bar undergoes significant changes, with entirely different symbols appearing. Even a trust symbol now signifies something entirely different (the double-note symbol). This all feels very confusing, restless, and overloaded.

![ZomboDroid_15042024094746](https://github.com/fast4x/RiMusic/assets/71184627/ac098d15-6a2d-48ce-978e-8b5f544ca7ea)

**3. Other observations:** Within Albums, History, Statistics, and Search, the main navigation bar is completely absent.

![ZomboDroid_15042024102615](https://github.com/fast4x/RiMusic/assets/71184627/b70e473d-41c6-4d46-a53c-51a8bc82e4d6)

I understand that the app navigation is intentionally designed as it currently stands, but I believe it might be worth reconsidering. It would be a monumental task, requiring a reevaluation of many aspects, but ultimately, if the main navigation bar remained consistent and accessible from anywhere within the app, the app would be much clearer and easier to navigate. I open this up for discussion on how exactly to achieve this and what changes would be necessary. Also, I'm curious to hear if my suggestions make sense to you. Looking forward to your comments.

**Comment by fast4x** [comment]
I agree almost with everything, I point out that the "top or bottom navigation bar" contains the same bar entries when it is left or right, so it is consistent with all positions.
For the rest, major restructuring is needed to make everything more coherent.

**Comment by fast4x** [comment]
![giphy](https://github.com/fast4x/RiMusic/assets/1484476/85ec8b7a-04e9-43c8-87dd-499628898392)

**Comment by dAtA-TRoN** [comment]
> I agree almost with everything, I point out that the \"top or bottom navigation bar\" contains the same bar entries when it is left or right, so it is consistent with all positions.\nFor the rest, major restructuring is needed to make everything more coherent.

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/bc5009de-46b3-4266-b315-6ef67411b6e2)

Dude, I swear, it would be so awesome if we could pull this off. A fixed, unchanging navigation bar (I don't care where on the screen, but it should be fixed in itself), always accompanying throughout the entire app, that would be amazing and would seriously elevate the app, finally putting an end to all the quirks it currently has. I'm aware that it'll take some serious brainstorming to figure out how to achieve this, considering some icons would need a new home, but I'm confident we can do it. I already have a few ideas on this. But hey, to everyone else reading this: feel free to pitch in.

**Comment by dAtA-TRoN** [comment]
So here is the plan:

**Artist Page**

![sketch1713757501499.png](https://github.com/fast4x/RiMusic/assets/71184627/fa0b8d73-21e5-4926-ba5d-d7985874a736)

_Replace without substitution._

---

**Album Page**

![sketch1713757573699.png](https://github.com/fast4x/RiMusic/assets/71184627/dac979f7-20f3-459f-9ef7-5eed932250a2)

_Replace without substitution._

---

**Standard Playlists**

![sketch1713757626691.png](https://github.com/fast4x/RiMusic/assets/71184627/ad5958d7-8622-4456-8b8b-65b7dcb10c65)

_Replace without substitution._

---

**Custom Playlist**

![sketch1713757715499.png](https://github.com/fast4x/RiMusic/assets/71184627/251c3f09-8efe-4467-873f-9d9ee4837d6e)

_Replace without substitution._

---

**Search Page**

![sketch1713758076017.png](https://github.com/fast4x/RiMusic/assets/71184627/9edf7808-5d81-4322-a9f3-8ffa868f631d)

_Exchange -bring controls up._

---

**Search Page** (after search performed)

![sketch1713758373271.png](https://github.com/fast4x/RiMusic/assets/71184627/84ed736d-123e-4a0d-8dde-9fd225a01421)

_Exchange -bring controls up._

---

**History Page**

![sketch1713758455909.png](https://github.com/fast4x/RiMusic/assets/71184627/46256356-1aab-446e-9173-f14c88b12050)

_Add navigation bar._

---

**Statistic Page**

![sketch1713759162080.png](https://github.com/fast4x/RiMusic/assets/71184627/26b68912-0927-49cb-a283-d92e49f9e141)

_Exchange -bring controls up._

---

**Settings**

![sketch1713759819788.png](https://github.com/fast4x/RiMusic/assets/71184627/b2b31f3d-59b7-4649-81cf-14dea4a45ee0)

_Exchange -bring controls up._

**Comment by dAtA-TRoN** [comment]
Hey, I wanted to take a moment to share a few thoughts on #1528 alongside #1315 again.

These two are pretty crucial, in my opinion, and tackling them together is key to sorting out ReMusic's navigation.

Let's start with #1528. Right now, the big navigation headache stems from this. It's essential for users to lean on the main navigation bar no matter where they find themselves within the app. That bar should always be there, doing what it does best: staying consistent and easily accessible at the screen's edge. I've already gone into detail about this in #1528, but there's another point I want to stress. Imagine if, after the revamp, the navigation bar checks all the boxes we've discussed. Then, all tab buttons also double as 'Home' buttons for each tab individually. It means that no matter where you are in the app, if you want to go back to the main page of that section or to the main page of any other section, you can simply tap on the corresponding tab button. However, currently, you can only access the main pages from the top level, which is not ideal and makes navigation unnecessarily difficult.

Now onto #1315:
This suggestion is also important because it addresses a significant flaw in ReMusic's navigation: the ability to navigate back sensibly within tabs. Initially, I thought this issue was only related to the chosen Default Page. However, it's just even more complicated when you switch the Default Page, which adds to the confusion. Let me illustrate: go to Artist Main Tab > Artist > Songs 'View all'. When you hit the back button once on the Songs 'View all' Page, you expect to return to > Artist, but instead, you end up back at the Artist Main Tab, which is unexpected. The same issue occurs with > Albums 'View all' and > Singles 'View all'. It's also frustrating when you're in > Albums 'View all' or > Singles 'View all', and after selecting an album or single to view its song list, hitting back doesn't take you to > Albums 'View all' or > Singles 'View all' as expected, but back to > Artist. This inconsistency shouldn't be happening.

So, there you have it. I felt it was crucial to bring up these issues again because they seriously affect app usability, therefore it would be great if these problems could be fixed.

**Comment by fast4x** [comment]
You did well to talk about it, are important reasoning that can be taken into consideration later, because the current navigation that is based on that of ViMusic I’m migrating and is not simple.
I have to be careful not to lose compatibility with ViMusic mode, in the meantime migrate navigation means to set up all those features you described.

**Comment by privacyfreak84** [comment]
> because the current navigation that is based on that of ViMusic I’m migrating and is not simple

Why? ViMusic's navigation is perfect!

**Comment by fast4x** [comment]
ViMusic navigation is OLD much OLD architecture. Already now RiMusic has a hybrid navigation that will soon be modernized arriving at a modern navigation system and backwards compatible with ViMusic.

**Comment by dAtA-TRoN** [comment]
Thank you for your response! I know, I've been harping on about this for a while now 😅. But I truly believe fixing these issues would be a game-changer for RiMusic's user experience. And when you mentioned that the code is getting a bit outdated, well, I had a hunch already. How else could these quirky bugs happen, right? But I'm glad you brought it up; it confirms my suspicions. Well, I guess all we can do now is wait. But hey, my suggestions here are pretty reasonable, don't you think?
