### ISSUE TITLE
Smart Recommendations

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#153]
### Description

I think it would be could do add a feature like in spotify where it adds occasionally similar songs in your Playlists to discover while listening

### Suggested Solution

Add an option while listening to show similars songs occasionally in your Playlist (Also add an sparkles ✨️ icon next to the song name to not confuse the user)

**Comment by fast4x** [comment]
I don’t know about this feature in Spotify, but does it add the song to the playlist, or does it show in the playlist without actually adding it?

**Comment by OrangeZXZ** [comment]
> I don’t know about this feature in Spotify, but does it add the song to the playlist, or does it show in the playlist without actually adding it?

The songs are added only in the listening list not the playlist itself
https://community.spotify.com/t5/Your-Library/Introducing-Smart-Shuffle/td-p/5516566#:~:text=When%20Smart%20Shuffle%20is%20on,symbol%20next%20to%20the%20track.

**Comment by fast4x** [comment]
Perfect, thanks

**Comment by OrangeZXZ** [comment]
> The songs are added only in the listening list not the playlist itself https://community.spotify.com/t5/Your-Library/Introducing-Smart-Shuffle/td-p/5516566#:~:text=When%20Smart%20Shuffle%20is%20on,symbol%20next%20to%20the%20track.

I think we would need an icon for that

**Comment by fast4x** [comment]
Nice

**Comment by ikanakova** [comment]
> I think we would need an icon for that

Like this?
<img src="https://github.com/fast4x/RiMusic/assets/38765251/c18a08ee-2b53-4985-9877-401e7691edfc" width="50" alt="smart_shuffle">

If you like it, I'll add it to assets folder.

**Comment by OrangeZXZ** [comment]
> Like this? <img alt="smart_shuffle" width="50" src="https://private-user-images.githubusercontent.com/38765251/290141097-c18a08ee-2b53-4985-9877-401e7691edfc.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjAyMjQsIm5iZiI6MTcwMjQ1OTkyNCwicGF0aCI6Ii8zODc2NTI1MS8yOTAxNDEwOTctYzE4YTA4ZWUtMmI1My00OTg1LTk4NzctNDAxZTc2OTFlZGZjLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA5MzIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZDIzNjdmMTllNTFjNTI4Mjg4MjEwNjgzN2Y3YWU1ZTA2MGNjOGY3OTcyNDAyYWVhMWJjMTM1YWQ3ZWY4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sTxCZqr7eNTJJBs3cDJWoi8OMkbjBDB1KtoXn2n2ycQ">
> 
> If you like it, I'll add it to assets folder.

Yes its perfect buy idk why it bugs on my navigator
![image](https://github.com/fast4x/RiMusic/assets/104271365/6fcb7312-6eb8-401e-aa55-9e6d233c763e)

**Comment by ikanakova** [comment]
> Yes its perfect buy idk why it bugs on my navigator

Interesting, it's also displaying strangely in my new window... But only when I open it from Github...

**Comment by ikanakova** [comment]
In pull request #218 icon looks normal.

**Comment by ikanakova** [comment]
It occurred to me that if smart suggestions are ever implemented, they could replace the start radio function, which as I mention in #377 doesn't work properly for me anyway and hasn't since ViMusic (and not just for Czech songs).

**Comment by OrangeZXZ** [comment]
> It occurred to me that if smart recommendations are ever implemented, they could replace the start radio function, which as I mention in #377 doesn't work properly for me anyway and hasn't since ViMusic (and not just for Czech songs).

Yeah the radio is cool but it shows only some songs and after some time they repeat

It is cool when listening to a song we searched or in the Quick Pics but in an playlist the smart recommendation would be bether i think

**Comment by fast4x** [comment]
The smart playlist is an important goal, on which I am putting ideas in order.

**Comment by fast4x** [comment]
Sorry, smart recommandations, not smart playlist...

**Comment by fast4x** [comment]
Implemented, available from version 0.6.19

**Comment by fast4x** [comment]
I really like this feature, congratulations my fellow travelers. Thank you.

**Comment by Carter0108** [comment]
What happened to this feature? It seems to have disappeared since the redesign.

**Comment by fast4x** [comment]
yes, improvements under development
