### ISSUE TITLE
Missing Audio Format (Can't play a song)

### ISSUE THREAD

**Issue by MrBoomDeveloper** [fast4x/RiMusic#1531]
### Steps to reproduce the bug

Open this song: https://music.youtube.com/watch?v=Q3UoAMcbUuU

### Expected behavior

It would play normally

### Actual behavior

It doen't play

### Screenshots/Screen recordings

![Screenshot_20240415_195031](https://github.com/fast4x/RiMusic/assets/92123190/2c09ebca-ca37-4d7d-bc5d-12df05add13d)

### RiMusic version

The latest from actions: https://github.com/fast4x/RiMusic/actions/runs/8690087556

### Android version

Android 13

**Comment by fast4x** [comment]
Set quality audio format in ui settings, automatically can not find the right quality, it can happen for some songs
