### ISSUE TITLE
[Feature]: Import from InnerTune

### ISSUE THREAD

**Issue by kacperwyczawski** [fast4x/RiMusic#1532]
### Description

It would be nice if importing playlists from [z-huang/InnerTune](https://github.com/z-huang/InnerTune) was possible.

### Suggested Solution

I'm not familiar with Kotlin or mobile development in general, so unfortunately I don't have a solution. But InnerTune's backup/export feature could be used. Code related to backup seems to be [here](https://github.com/z-huang/InnerTune/blob/6660e8b774303d2464f06b7c09f0768ecb19c014/app/src/main/java/com/zionhuang/music/viewmodels/BackupRestoreViewModel.kt#L31)

**Comment by cMattw** [comment]
This would be a good enhancement to gather more users from other music players. I personally came from innertune and I had to manually and painfully import my playlists to rimusic. If this was implemented, it would be so much more convenient for new incoming users to rimusic

**Comment by kacperwyczawski** [comment]
> This would be a good enhancement to gather more users from other music players. I personally came from innertune and I had to manually and painfully import my playlists to rimusic. If this was implemented, it would be so much more convenient for new incoming users to rimusic

I fully agree. I'm in process of moving my library to RiMusic right now.

It would be a lot easier if InnerTune used some kind of plain text format.

**Comment by fast4x** [comment]
I've started to develop a special version of original InnerTune with RiMusic compatible playlist export functionality

**Comment by fast4x** [comment]
Unfortunately isn't possible, sorry
