### ISSUE TITLE
Song and album name font

### ISSUE THREAD

**Issue by col1iv** [fast4x/RiMusic#1534]
### Description

Are we ever going to get the player font to use the other two fonts the app has to select?

### Suggested Solution

![Screenshot_20240415_162316](https://github.com/fast4x/RiMusic/assets/152646768/af64e59d-75f7-43de-b932-5833eea55793)

**Comment by fast4x** [comment]
I don't understand, sorry.

**Comment by col1iv** [comment]
As you probably know, there is a setting to use two fonts and the system font inside the app. I have selected to use one of the two customizable fonts on the app but they do not apply to the song name and album name at the player screen. It would be cool to see them with the fonts if it's possible.

**Comment by fast4x** [comment]
Thanks for details, I'll check it.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.32

**Comment by col1iv** [comment]
Thank you!!
