### ISSUE TITLE
Tittle and authors

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1537]
### Steps to reproduce the bug

For instance, if you go to a song by an artist, its layout will indicate that the album is not there.

### Expected behavior

It should display the name of the author and the artist in the player; 

### Actual behavior

however, it shows that it is not the case with the new songs, and with the old ones, it does not show the album.

### Screenshots/Screen recordings

![Screenshot_2024-04-12-17-52-00-390_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/8d7fb95b-8702-4098-8f49-1bf5feb0c81b)
![Screenshot_2024-04-12-17-51-54-075_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/009a0e40-961c-4303-952b-ba057e5d1ba7)
![Screenshot_2024-04-15-16-15-06-963_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/9c9ecb8d-3799-43a8-9bcf-f2bae10e16cb)

### RiMusic version

0.6.30

### Android version

Android 13

**Comment by fast4x** [comment]
Fixed, available from version 0.6.32
