### ISSUE TITLE
Enhancing Main Navigation Bar Clarity with Color Highlighting

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1540]
### Description

![ZomboDroid_16042024104954](https://github.com/fast4x/RiMusic/assets/71184627/bdb26c79-6f6f-4cb7-a656-59f2b78c58ae)

![ZomboDroid_16042024105044](https://github.com/fast4x/RiMusic/assets/71184627/5d1524d2-5918-4cce-a05c-09360baa51d1)

The main navigation bar of the RiMusic app should be highlighted with color to ensure a clear distinction of the control elements from other ordinary buttons within the app. This suggestion aims to enhance user experience and increase usability.

⚠️ **Please note that the attached mockups serve as examples only and ARE NOT to be understood as final designs.** ⚠️

### Suggested Solution

To highlight the main navigation with color, I suggest dynamically adjusting the background color of the main navigation bar to match the selected theme.

### Additional Context

The change aims to improve user-friendliness by making the main navigation bar stand out distinctly from other interface elements.

**Comment by dAtA-TRoN** [comment]
> I can imagine others liking it. But I personally don't so I'd like if it's implemented it is optional.
> Or wait, is it again only for dynamic theme? In any case, if it's implemented for all the themes I'd like it to be optional for ModernBlack theme at least. 

Don't worry, it's just an example, as I mentioned before. The main point is simply to make the main navigation bar visible, as it often gets lost among all the other icons. If you have any ideas on how to solve it better, feel free to share.

**Comment by sayyid5416** [comment]
No please, this request hurts.

**Comment by dAtA-TRoN** [comment]
> No please, this request hurts.

Sure, here's a more polished version:

"Lol don't act like that, you yourself advocated for wanting the bar to be highlighted in color, remember?"

**Comment by dAtA-TRoN** [comment]
> a better approach would be using shadow as suggested in #1437 

See.

**Comment by fast4x** [comment]
I like the idea, shadow is nice but i think is for future... color of navigation buttons is pretty.

**Comment by dAtA-TRoN** [comment]
> I like the idea, shadow is nice but i think is for future... color of navigation buttons is pretty.

Thanks, fast4x, but perhaps we should brainstorm a bit more on this until everyone's satisfied, don't you think?

**Comment by fast4x** [comment]
Of course, I respect everyone’s ideas, I have to summarize all the ideas. Adding the background does not change the current characteristics of those accustomed to a uniform background. Those who use a dynamic theme would see the difference. I like the idea...

**Comment by dAtA-TRoN** [comment]
> Of course, I respect everyone’s ideas, I have to summarize all the ideas. Adding the background does not change the current characteristics of those accustomed to a uniform background. Those who use a dynamic theme would see the difference. I like the idea...

But I use the 'material you' design. Could I see the difference too 🥲?

**Comment by dAtA-TRoN** [comment]
> Of course, I respect everyone’s ideas, I have to summarize all the ideas. Adding the background does not change the current characteristics of those accustomed to a uniform background. Those who use a dynamic theme would see the difference. I like the idea...

But I use the 'material you' design. Could I see the difference too 🥲?

**Comment by sayyid5416** [comment]
OK, I get your point, it's not that bad _(atleast until drop shadow is implemented 😄)_. But if you plan to implement it:
- Do not make it this much round as shown.
- Make the color subtle, not too contrasty to take away the attention.

**Comment by dAtA-TRoN** [comment]
> OK, I get your point, it's not that bad _(atleast until drop shadow is implemented 😄)_. But if you plan to implement it:
> - Do not make it this much round as shown.
> - Make the color subtle, not too contrasty to take away the attention.

I mentioned earlier that this is just a mockup to illustrate my point, and it's not the final design. I didn't mean to be too insistent. I simply noticed an issue that needs addressing -there are pages in the app where the navigation bar can't be distinguished from the standard controls, which isn't ideal. So feel free to share your ideas; let's see where it takes us. fast4x quickly agreed, and it seemed like he already had a good idea about it. But hey, if you have time, create a mockup too. Perhaps your solution is way better. Just make sure to consider all positions of the navigation bar, as that's the tricky part -bringing it all together.

**Comment by sayyid5416** [comment]
> there are pages in the app where the navigation bar can't be distinguished from the standard controls, which isn't ideal.

That's why I opened #1437 

<br>

> But hey, if you have time, create a mockup too. Perhaps your solution is way better.

I would still bet my money on drop shadow, as its subtle, looks professional, and superior _(design wise - my opinion btw 😉)_

> Just make sure to consider all positions of the navigation bar

Drop shadow can be added in all positions btw 😅

**Comment by dAtA-TRoN** [comment]
I've also mentioned to you before that I think the idea of using drop shadow is really cool. I'm just wondering how exactly you plan to implement that on a sidebar. With the sidebar I've designed, it wouldn't work as Google envisions it. Because it would look strange if you just drew a shadow around it. That's why I asked you for a mockup.

**Comment by sayyid5416** [comment]
I'll share some mockups as soon as I got time.

**Comment by dAtA-TRoN** [comment]
> I'll share some mockups as soon as I got time.

Cool.

**Comment by sayyid5416** [comment]
@dAtA-TRoN Added 2 mockups in #1437

**Comment by dAtA-TRoN** [comment]
> @dAtA-TRoN Added 2 mockups in #1437 

Man, this looks awesome 🔥!

We've only touched on the light theme up to now, so we still need to cover the black/pitch-black theme. If you have any suitable ideas for that... The colored themes don't really require any additional explanation. I believe they function more or less automatically.

**Comment by fast4x** [comment]
> But I use the 'material you' design. Would I be able to see the difference too

slightly,
