### ISSUE TITLE
On device music

### ISSUE THREAD

**Issue by kris20030705** [fast4x/RiMusic#1542]
### Steps to reproduce the bug

I deleted songs from my phone storage

### Expected behavior

Expected to remove from song list..!

### Actual behavior

But keep showing as Local music not found..!

### Screenshots/Screen recordings

![Screenshot_20240416-202041_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/06f870f6-b7c5-4eea-9b7a-4a106e78fbdf)
![Screenshot_20240416-202038_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/191e9675-3e35-4e71-b800-c06049513b32)

### RiMusic version

0.6.30

### Android version

Android 13

**Comment by fast4x** [comment]
Implemented delete song from songs, automatic deletion isn't planned.
