### ISSUE TITLE
My Top-X-Playlist extension

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#1544]
### Description

A My Top X playlist already exists, but it only covers the entire period. It would be cool to have an implementation like ViTune where you can set the period of the playlist, e.g. the last 24 hours, week, month, 1 year, entire period. Would such an implementation be possible with RiMusic.

### Suggested Solution

.

**Comment by fast4x** [comment]
But it's same as statistics...

**Comment by siggi1984** [comment]
> But it's same as statistics...

Yes, similar, but this way you would have an automatic playlist to listen to.

**Comment by sayyid5416** [comment]
It's a good idea, but what will be the use of statistics then?

**Comment by fast4x** [comment]
> It's a good idea, but what will be the use of statistics then?

I think isn't necessary...

**Comment by sayyid5416** [comment]
you mean you will remove statistics?

**Comment by sayyid5416** [comment]
If you implement this:
- It will conflict with Android Auto implementation of My Top playlist.
- It will make it even more hard to implement #926 _(I personally think #926 would be a great and unique feature to have.)_

**Comment by sayyid5416** [comment]
> > > you mean you will remove statistics?
> > 
> > 
> > yes
> 
> Why is that? I would've liked statistics…though it has always been buggy as @Lukilei mentioned on #1527
> 
> Is it not possible (currently?) to fix that bug? I don't mean to bother you but I've always liked statistics. Statistics helps me understand what I like/do/need etc.

Removing it specially after implementing new top header feels like a bummer to me
![ElmoShrugGIF](https://github.com/fast4x/RiMusic/assets/78584556/d11be88e-635e-4ef8-a8ec-e1c45442ed1a)

**Comment by fast4x** [comment]
Each of us has a different idea of how statistics work. So it’s not worth keeping them in my opinion.

**Comment by fast4x** [comment]
You can share your idea...

**Comment by fast4x** [comment]
Your idea is interesting.
Don’t worry, you’re not giving lessons, you’re just showing your idea and thank you. Usually, if a topic is confusing it does not change. On this topic there are several ideas, often opposed. In my opinion, statistics make sense if there are many who use them, then you can actually understand what the path is.

**Comment by fast4x** [comment]
Thanks you

**Comment by siggi1984** [comment]
Bro, I'm reopening my request. I hope you'll reconsider and take over the "My Top X" from ViTune. Personally, I find the integrated playlist very good and useful. I think other RiMusic users would agree with me too.

**Comment by fast4x** [comment]
I'll check it

**Comment by fast4x** [comment]
> Bro, I'm reopening my request. I hope you'll reconsider and take over the "My Top X" from ViTune. Personally, I find the integrated playlist very good and useful. I think other RiMusic users would agree with me too.

In your opinion, what is the strength of the top x of ViTune?

**Comment by siggi1984** [comment]
> > Bro, I'm reopening my request. I hope you'll reconsider and take over the "My Top X" from ViTune. Personally, I find the integrated playlist very good and useful. I think other RiMusic users would agree with me too.
> 
> In your opinion, what is the strength of the top x of ViTune?

You would always have an automatically generated (without the user having to do anything) playlist with your favorite songs within 24 hours, 1 week, 1 month, 6 months, the entire period. I think it's brilliant.

**Comment by fast4x** [comment]
Ok, thanks for details...

**Comment by fast4x** [comment]
Implemented, available from version 0.6.44

**Comment by siggi1984** [comment]
Thanks Bro, very cool.
