### ISSUE TITLE
Update Button Style for Standard Playlists

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1546]
### Description

The current button style for the standard playlists in the Library Section of RiMusic looks outdated and does not align with the overall color scheme. The gray background feels out of place and lacks coherence with the app's design language. I propose updating the button style to utilize dynamic theme and Material You color gradients for the backgrounds. This change will not only enhance the visual appeal but also provide a cohesive look throughout the app.

![ZomboDroid_16042024084112](https://github.com/fast4x/RiMusic/assets/71184627/8b544e06-f8d0-45d2-b589-33c21fe5e16e)

![ZomboDroid_17042024060609](https://github.com/fast4x/RiMusic/assets/71184627/2d0db6b0-13ca-450d-87b7-21a1bf2f5ae3)

![ZomboDroid_17042024062952](https://github.com/fast4x/RiMusic/assets/71184627/1102bd41-2646-424d-b723-5c47a234d5b2)

![ZomboDroid_17042024065717](https://github.com/fast4x/RiMusic/assets/71184627/af3e78a2-1e64-4a4c-a432-40aabf1bfb63)

![ZomboDroid_17042024071727](https://github.com/fast4x/RiMusic/assets/71184627/d3176bcc-2066-4e6c-9cfe-b91679252233)

_Workflow: I just used a simple diagonal A/B color gradient:_

![Screenshot_2024-04-17-07-46-42-41_d69861e062f2821f00d6b38f4b252f2a-01.jpeg](https://github.com/fast4x/RiMusic/assets/71184627/6f9b3cf5-3967-4a10-af8b-7e89406afb51)

### Suggested Solution

Implement dynamic theme and Material You color gradients for the backgrounds of standard playlist buttons. These gradients will adapt dynamically, ensuring a consistent and visually pleasing appearance across different themes and color schemes.

### Additional Context

It's worth noting that while my mockups may not be perfect and might appear slightly dark, these potential adjustments should be considered during the implementation of this feature to ensure optimal visual representation.

**Comment by dAtA-TRoN** [comment]
Please apply the same procedure to the genre buttons in the Quick Picks tab:

![Screenshot_2024-04-17-08-09-45-78_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/616e4582-1f69-421b-9b5e-5979e69f739a)

**Comment by sayyid5416** [comment]
Nice request, one suggestion: 
- gradient in mockups look too harsh. It should be subtle in my opinion.

**Comment by NightFly88** [comment]
looks nice, much better

**Comment by privacyfreak84** [comment]
Idk, I prefer the classic grey color. I like it's plainness

**Comment by dAtA-TRoN** [comment]
Update - on the right end is the new variant with a softened gradient:

![ZomboDroid_18042024074441.jpg](https://github.com/fast4x/RiMusic/assets/71184627/1a2b11d5-f6cf-485b-9aaf-b37535508496)

And this is a variation of the new variant with white icons:

![sketch1713419024321.png](https://github.com/fast4x/RiMusic/assets/71184627/9c76e078-25d5-481e-975a-f257cb2e79c1)

**Comment by sayyid5416** [comment]
light mode?

**Comment by dAtA-TRoN** [comment]
> light mode?

I would prefer it like this in 'material you'. I think for the light mode, the colors should be much more pastel.

**Comment by fast4x** [comment]
I prefer not change it...

**Comment by dAtA-TRoN** [comment]
> I prefer not change it...

Okay, thanks for your feedback.
