### ISSUE TITLE
Make button colors in player white

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1547]
Currently, in the player, the buttons have a colored background, and the icon of the button is a lighter variant of the background color.

I personally prefer the buttons to be white, as they are in ViMusic. I feel that this design looks less aggressive and more laid back than the current one.

How it looks in RiMusic: https://imgur.com/a/LD0jRdB
How it looks in ViMusic: https://imgur.com/a/uSYs6Rs

**Comment by dAtA-TRoN** [comment]
I agree. Either white or a much brighter dynamic color (almost white).

**Comment by privacyfreak84** [comment]
> Or maybe there can be an option with few common colors. Like green, blue, black, red, yellow etc. (You might think the more color the better but actually it's "the more color the more confusion on what should be picked and thus waste of time") I'd prefer green or blue color. But in ModernBlack theme I haven't found anything yet that doesn't look good to me. Not any color.

I'm OK with this as long as white is an option

**Comment by dAtA-TRoN** [comment]
> Sorry for not including white color on my explanation. I almost forgot.

It's all good man. I didn't even notice.

**Comment by dAtA-TRoN** [comment]
> > > Sorry for not including white color on my explanation. I almost forgot.
> > 
> > It's all good man. I didn't even notice.
> 
> I wasn't talking to you…but got it.

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/052f1251-4928-44eb-b612-3691b06b2bbe)

**Comment by fast4x** [comment]
I can set White in ViMusic mode

**Comment by fast4x** [comment]
ok

**Comment by fast4x** [comment]
A question, do you think the ViMusic user prefers RiMusic without the new top bar or with the new top bar?

**Comment by privacyfreak84** [comment]
> A question, do you think the ViMusic user prefers RiMusic without the new top bar or with the new top bar?

The new bar with history and statistics? I prefer it the old way

**Comment by fast4x** [comment]
Now white in ViMusic mode, it could be changed color in dynamic theme...
Available from version 0.6.32

**Comment by privacyfreak84** [comment]
So can we change the color in RiMusic UI when using dynamic theme?

**Comment by fast4x** [comment]
Yes it change according to the text color used in dynamic theme.

**Comment by privacyfreak84** [comment]
Oh... I was thinking that we could choose from different color options. This sounds much like how it currently works

**Comment by fast4x** [comment]
Color is based on theme colors...

**Comment by privacyfreak84** [comment]
So the way it currently works on dynamic theme

**Comment by privacyfreak84** [comment]
So.... Will we able to choose the button colors in dynamic theme ourselves?

**Comment by fast4x** [comment]
Not, color is dynamic.

**Comment by privacyfreak84** [comment]
So will there ever be options for player button colors in the future?

**Comment by fast4x** [comment]
maybe along with some other color configuration

**Comment by privacyfreak84** [comment]
Ok

**Comment by privacyfreak84** [comment]
So... why does this issue have an implemented label again?

**Comment by fast4x** [comment]
Because in ViMusic mode color is white...

**Comment by privacyfreak84** [comment]
Hmm... ok

**Comment by privacyfreak84** [comment]
Any plans to implement this?

**Comment by fast4x** [comment]
wait new version, i don't remember now if just developed

**Comment by privacyfreak84** [comment]
Ok

**Comment by privacyfreak84** [comment]
> Any plans to implement this (at least as an option)?

...

**Comment by fast4x** [comment]
under development

**Comment by dAtA-TRoN** [comment]
...but I want them PINK 😤!!!

🏃🏼‍♂️💨🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by fast4x** [comment]
and I would like it soft yellow with green stripes along with rounded squares and a star in the middle
🤣🤣🤣🤣

**Comment by dAtA-TRoN** [comment]
> and I would like it soft yellow with green stripes along with rounded squares and a star in the middle
> 🤣🤣🤣🤣

Tsk, always these people with their special requests 🙂‍↔️.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.37

**Comment by privacyfreak84** [comment]
Thanks!
