### ISSUE TITLE
Automatically filter out certain type of songs from "My top X" playlist

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1548]
### Description

Maybe make it optional. Since not everyone will have any problem with it. But sometimes we listen to long music and some of them even makes it to top of list. If the amount is more than a few it can be bothersome.

### Suggested Solution

Idk about others but I have listened to few long music (I'm not saying song because those are actually rain sounds) for long and those have been included on the said playlist. It'd be better if there was an automatic filter for long songs. Maybe initially for songs longer than 30 minutes?

### Alternatives

I think actually you can filter out other songs as well. For example filter out duplicate songs based on listening time/how many plays. 

### Additional Context

I think this suggestion isn't that important. You surely have better priorities right now.

**Comment by sayyid5416** [comment]
Nice request. But add this feature in the queues to filter out long songs from any queue.

- 5 min,
- 10 min,
- 15 min,
- 30 min, 
- etc

**Comment by sayyid5416** [comment]
> > instead of `My Top`
> 
> While I agreed before but now that you added this I don't think so…it should be "also" not "instead". Because I'd like to use that `My Top X` playlist as well but with those long songs it's kinda inconvenient.

When you play `My Top`, songs will be played in a **_queue_**. You can set the **_limit_** in **_queue_**! That's why if it's implemented in **_queue_**, it will no longer be required in `My Top`.

**Comment by sayyid5416** [comment]
> > > > instead of `My Top`
> > > 
> > > 
> > > While I agreed before but now that you added this I don't think so…it should be "also" not "instead". Because I'd like to use that `My Top X` playlist as well but with those long songs it's kinda inconvenient.
> > 
> > 
> > When you play `My Top`, songs will be played in a **_queue_**. You can set the **_limit_** in **_queue_**! That's why if it's implemented in **_queue_**, it will no longer be required in `My Top`.
> 
> I don't quite understand. What about the songs/music that has already been listened a lot? You will still have to remove/hide some of those manually from `My Top X` playlist.

No, that's not what I meant.

1. What you want to implement in My top X, I want the same to be implemented in the queue.

2. If you have enabled it, songs which are larger than the time specified will be filtered out from every queue.

3. What it means is if you play a song from anywhere including my top those songs will be filtered out automatically, because you have enabled it in queue.

4. Basically it is the same functionality, just not restricted only to my top, but available everywhere in the app.

**Comment by fast4x** [comment]
Implemented, in queue and my top available from version 0.6.38
