### ISSUE TITLE
Adapt app to use monet theming 

### ISSUE THREAD

**Issue by abdulkarimx1** [fast4x/RiMusic#1554]
### Steps to reproduce the bug

App ui is showing in different colors than monet, which makes user interface a bit weird 

### Expected behavior

Ability to add a monet theme support to the app so it follows system accent colors 

### Actual behavior

It's showing all in red which makes a little strain because of the vibrant colors
![Screenshot_20240418-143443_RiMusic](https://github.com/fast4x/RiMusic/assets/105733146/74cfa7a2-525d-4b2f-85c9-b5040c58813f)

### RiMusic version

Latest 

### Android version

Android 14

**Comment by abdulkarimx1** [comment]
![Screenshot_20240418-142906_RiMusic](https://github.com/fast4x/RiMusic/assets/105733146/7f56a40b-d985-4e54-b48c-ddd314c507a4)
 
Also this

**Comment by fast4x** [comment]
Hi, monet is available with Material You theme, set it settings.
