### ISSUE TITLE
Can't find the settings

### ISSUE THREAD

**Issue by ABHIRAJ770** [fast4x/RiMusic#1559]
### Steps to reproduce the bug

Open the app and there will be a settings button so tap on jt

### Expected behavior

Settings button should have been there 

### Actual behavior

The gear like setting icon is with search but I can't open the settings. Like I don't any option to go to settinf

### Screenshots/Screen recordings

![Screenshot_20240418-235204](https://github.com/fast4x/RiMusic/assets/128519244/edb43d39-53c8-41ae-8e0b-57456ae6dc57)
![Screenshot_20240418-235209](https://github.com/fast4x/RiMusic/assets/128519244/5022da2c-160e-4660-be34-4032d88c1b63)

### RiMusic version

0.6.30

### Android version

11

**Comment by aneesh1122** [comment]
Double tap the search icon

**Comment by fast4x** [comment]
In new version it will be removed
