### ISSUE TITLE
[Feature]: Force album version of the song instead of music video

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1563]
### Description

If you have YT Premium and you play a **music video** in YT music and switch to audio, YT Music will play the album version of the song.

Is it possible to have something like that in RiMusic? In RiMusic or Youtube Revanced Music it always plays the audio-only stream of the music video

### Suggested Solution

Just see if it's possible to force album version of the songs

**Comment by fast4x** [comment]
Actually isn't possible.
