### ISSUE TITLE
MENU SOBRE DIFICULDADE EM ENCONTRAR 

### ISSUE THREAD

**Issue by flaviorrr** [fast4x/RiMusic#1565]
### Steps to reproduce the bug

O botão busca está juntamente com o sobre e configuração ficando difícil acionar o mesmo, nas versões anteriores ficava no topo o que torna bem mais fácil.

### Expected behavior

Colocar o menu configuração no topo como antigamente.

### Actual behavior

Ficará melhor de entender e encontrar no topo.

### Screenshots/Screen recordings

![Screenshot_20240419-170245](https://github.com/fast4x/RiMusic/assets/91763312/c64f78b2-afb6-48c5-a463-268c3823a2b5)

### RiMusic version

6.030

### Android version

Android 13

**Comment by dAtA-TRoN** [comment]
Espera pela próxima atualização. Tudo vai mudar.

**Comment by fast4x** [comment]
New version released
