### ISSUE TITLE
"Show search in navigation bar" doesn't work

### ISSUE THREAD

**Issue by fofxox** [fast4x/RiMusic#1566]
### Steps to reproduce the bug

Enable 0.6.31's new options, "Show search in navigation bar" and "Show statistics in navigation bar"

### Expected behavior

Search and statistics options show up in the nav bar

### Actual behavior

Those buttons never become available, whether the option is on or off

### Screenshots/Screen recordings

![Screenshot_20240419_180452](https://github.com/fast4x/RiMusic/assets/130255231/be2be661-2c33-4e3e-94d2-6d46506d6243)

### RiMusic version

0.6.31

### Android version

Android 14

**Comment by fast4x** [comment]
Are only available in ViMusic ui mode. While in RiMusic is just visible in the new top bar. Navigation bar isn't top bar...
