### ISSUE TITLE
[Feature]: Option to remove settings from navigation bar

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1568]
### Description

Since Settings is already available in new top menu, it isn't necessary to have it in navigation bar.

### Suggested Solution

Add an option to disable it. This issue is extension of #1493

**Comment by NikunjKhangwal** [comment]
Yes

**Comment by NikunjKhangwal** [comment]
@fast4x Why already implemented tag? Am i missing something here?

**Comment by fast4x** [comment]
Not same, include pinned if you have pinned playlists...

**Comment by fast4x** [comment]
> @fast4x Why already implemented tag? Am i missing something here?

it show and it's necessary in ViMusic mode

**Comment by NikunjKhangwal** [comment]
> it show and it's necessary in ViMusic mode

But you can access Settings from this new bar in vimusic mode as well

![IMG_20240505_130947](https://github.com/fast4x/RiMusic/assets/99175083/d3670a1a-f2d4-4a58-88bd-27c6a8ccfa5e)

**Comment by fast4x** [comment]
Floating search icon was requested by ticket, and top bar not show in ViMusic mode...

**Comment by NikunjKhangwal** [comment]
> Floating search icon was requested by ticket, and top bar not show in ViMusic mode...

I'm not talking about the floating search, I'm talking about the search icon in navigation bar.
Also top bar does appear in vimusic mode, the screenshot is taken with ViMusic mode enabled. Try it yourself 👀

**Comment by fast4x** [comment]
search icon show in left and right nav bar ..

**Comment by NikunjKhangwal** [comment]
We can optionally make it appear in bottom nav as well but that's not what the issue is about. It was about removing search icon because we can use search from top menu

![IMG_20240505_144836](https://github.com/fast4x/RiMusic/assets/99175083/8108672a-77e9-42c7-92bc-ad8160e675ab)

**Comment by fast4x** [comment]
it can disabled... settings remain for ViMusic mode with left and right nav bar

**Comment by NikunjKhangwal** [comment]
Then maybe only keep it for left and right nav and automatically disable it when bottom nav is selected?
