### ISSUE TITLE
Proposal to Adjust the Color Scheme of the New Menu Window

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1570]
### Description

![ZomboDroid_20042024045854](https://github.com/fast4x/RiMusic/assets/71184627/929d3dd8-6ec8-4309-90ca-513cf8a613a7)

The current color scheme of the new menu window presents several issues. Firstly, the window shares the same color as the background, causing it to blend in and become less noticeable. Secondly, the icons share the same color as the playlists icons. This distracts and somehow clashes, as the new menu window is not part of the playlists but rather part of the app navigation. So it would be beneficial to align the color scheme of the menu window with that of the navigation bar to ensure a coherent style.

### Suggested Solution

The colors of the new menu window should match those of the navigation bar. This adjustment will facilitate a unified and user-friendly navigation experience within the app. Specifically, both the icons and the background of the menu window should be adapted to match the color scheme of the navigation bar.

### Additional Context

The current color scheme of the menu window complicates navigation and impacts the user experience. By aligning it with the color scheme of the navigation bar, this issue can be addressed, and the app will achieve a more consistent visual style. This change enhances usability and contributes to making navigation within the app more intuitive.

⚠️ IMPORTANT ⚠️
This problem exists in all themes except the light theme and must be solved in different ways. I am just offering here a solution for the 'Dark Theme -Material You' combination.

I couldn't check the pitchblack theme because it seems to be broken.

**Comment by NikunjKhangwal** [comment]
Do you always use AI to write your issues?

**Comment by dAtA-TRoN** [comment]
> Do you always use AI to write your issues?

Yes.

**Comment by dAtA-TRoN** [comment]
> Do you always use AI to write your issues?

Yes, also to respond to longer comments.

**Comment by NikunjKhangwal** [comment]
I get lazy reading them tbh. Feels unnecessarily complex to me. 💀

**Comment by dAtA-TRoN** [comment]
> I get lazy reading them tbh. Feels unnecessarily complex to me. 💀

Cool, if you've already grasped it after the first sentence, then congratulations to you. On my end, I'm not keen on responding to hundreds of follow-up questions, so I'd rather write it out in detail once.

**Comment by dAtA-TRoN** [comment]
> I prefer "responding to hundreds of follow-up questions"
> 
> Sometimes your explanation goes over my head even though some of those are actually written pretty simply.

And now? I can't please everyone here.

**Comment by sayyid5416** [comment]
@dAtA-TRoN Add this line also: `Also add some margin to right side of it.`

**Comment by dAtA-TRoN** [comment]
>You don't have to please anyone. You only need to make sure the explanation you write is understandable to whom it is intended (I'm sure I'm using wrong word but I forgot what it actually should be…) for.

I always make sure that my explanations are understandable. I proceed as follows: First, I tell ChatGPT what I want, for example, I ask it to write a GitHub proposal for me. I also provide the structure, such as title, description, suggested solution, and additional context. Then, I describe roughly what I want. Next, I let GPT spit out a first draft. I read through it, correct it where necessary, and run the whole thing through again. Usually, that's sufficient. Then, I post it. Often, afterwards, I think of things to refine, so I edit it until I'm satisfied with the result.

>As far as I know most people prefer conversation rather than "long instructions".

I like both in combination, as conversations often seem more productive to me after long instructions.

**Comment by dAtA-TRoN** [comment]
> @dAtA-TRoN Add this line also: `Also add some margin to right side of it.` and `make it a little more round`

Since you mentioned it here, it has happened. fast4x reads everything, as you know. But yes, good point!

**Comment by sayyid5416** [comment]
> > @dAtA-TRoN Add this line also: `Also add some margin to right side of it.` and `make it a little more round`
> 
> Well, since you mentioned it here, it has happened. fast4x reads everything, as you know. But yes, good point!

I think writing the summary in main post is always a good idea, easy to track.

**Comment by dAtA-TRoN** [comment]
I think it's also the fascination of working with AI for me. I'm absolutely in love with technology. And when it comes to AI, I'm constantly amazed. It always blows my mind anew.

**Comment by sayyid5416** [comment]
@dAtA-TRoN Try this command next time, you'd be blown away: `Summarize all this in short`

**Comment by dAtA-TRoN** [comment]
> @dAtA-TRoN Try this command next time, you'd be blown away: `Summarize all this in short`

I already know that. I use it sometimes. But often GPT leaves out crucial things when I do this.

**Comment by sayyid5416** [comment]
![image](https://github.com/fast4x/RiMusic/assets/78584556/9d3e4375-c405-4fc3-8884-580d9c427616)

All this text seems too much, only title and ss were enough, maybe few texts for context, but hey.... maybe fast4x loves long texts

![ElmoShrugGIF](https://github.com/fast4x/RiMusic/assets/78584556/b093bd05-67c9-4345-8dcf-5e78f82fedda)

**Comment by dAtA-TRoN** [comment]
> maybe

Yeah, maybe...

**Comment by fast4x** [comment]
Improved, available from version 0.6.32

**Comment by sayyid5416** [comment]
> Improved, available from version 0.6.32

Padding?

**Comment by fast4x** [comment]
background changed...

**Comment by sayyid5416** [comment]
> background changed...

Nice, Some right padding, and slightly rounder corners would be great.
