### ISSUE TITLE
Not able to add albums to the playlist with grid menu style

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1571]
### Steps to reproduce the bug

1. Go to any album
2. Press 3 dots
3. Add to playlist

### Expected behavior

List of playlists should appear

### Actual behavior

List doesn't appear

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/45353488/e812dd5a-f348-4297-993b-f8cad1149972

### RiMusic version

0.6.31

### Android version

Android 13

**Comment by fast4x** [comment]
You mean with grid menu ..

**Comment by fast4x** [comment]
Fixed, available from version 0.6.32
