### ISSUE TITLE
Add 'Play next' in Swipe Right

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1572]
### Description

The 'Play next' button will be useful if added in left side of swipe. It will let us add the song next in queue quickly.

### Suggested Solution

Add the button next to 'Add to queue' in left swipe
![IMG_20240420_113039](https://github.com/fast4x/RiMusic/assets/45353488/6972f818-9432-41ce-bd78-50603c2fb788)

Also please increase the threshold for triggering 'swipe to action'. Most of the times I end up triggering the swipe while scrolling the playlist.

**Comment by fast4x** [comment]
to replace enqueue?

**Comment by aneesh1122** [comment]
> to replace enqueue?

No. Let them both be there. Put 'Play next' next to 'Enqueue'

Please also make it a little harder to swipe. I accidently swipe a lot while scrolling playlists.
