### ISSUE TITLE
Somes Issues

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#1576]
### Steps to reproduce the bug

First somes missing translation on crowdin 
![IMG_20240420_092602](https://github.com/fast4x/RiMusic/assets/63956787/b7ff84a6-59c1-4b3f-838b-19c8e8e5b7a7)
![IMG_20240420_092545](https://github.com/fast4x/RiMusic/assets/63956787/c670c8c6-0bc6-452c-a1b6-6af0e7196879)

And when u put bar on top or bottom the text is cut 
![IMG_20240420_092626](https://github.com/fast4x/RiMusic/assets/63956787/b29d99b4-5443-4c4f-a9b6-2c3c83829eb9)

### Expected behavior

.

### Actual behavior

.

### RiMusic version

0.6.31

### Android version

A12 MIUI 14

**Comment by NEVARLeVrai** [comment]
Also when  the bar is on top or bottom can you make the color not grey like that but like the background?

**Comment by fast4x** [comment]
Added missing translation, for now background isn't modifiable.

**Comment by fast4x** [comment]
Improved title on menu with icon and text, available from version 0.6.32
