### ISSUE TITLE
Inconsistencies and bugs that is bugging me after latest update 

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1577]
### Description

T.N. Now (actually for few weeks) that there are Left, Right, Top, Bottom nav bar positions you'll have to consider all of those positions while implementing new features. Otherwise in one nav bar a feature might look great while in another it might not even work. 
(I might be wrong about that though…🤔)

### Suggested Solution

- [ ] 1. Part of pages (Not just `Artist` page) getting blocked by the minimized player except in `bottom nav bar` mode:
![Screenshot_20240420-102520.jpg](https://github.com/fast4x/RiMusic/assets/85461823/8c916afa-06ba-4646-ba4c-19c3d0030163)
~~Btw #1573 probably reported this same thing!?~~ Nvm these doesn't seem related.

- [ ] 2. Move `Hide` button there:
![Screenshot_20240420-102818.jpg](https://github.com/fast4x/RiMusic/assets/85461823/6764679a-278f-4a02-bf42-45347881f4dc)
Would be a better place for it.

- [x] 3. Too close: ![Screenshot_20240420-103008.jpg](https://github.com/fast4x/RiMusic/assets/85461823/1516a4a6-46e3-4a0b-838a-0e8941cdf0ab)

- [x] 4. In `Songs` tab I have 1908 (had…now it's 1916) songs ![Screenshot_20240420-121239.jpg](https://github.com/fast4x/RiMusic/assets/85461823/36183e4f-8930-4d10-9aee-78cb1bf9b3fd) and whenever I try to play songs from there the app crashes. (Similar problem has been reported on #1146 and #1164.) I have tried using the `Max songs in queue` but results same even with that feature.

- [ ] 5. These should probably (I'm not sure that's why I added "probably") be better aligned with the overview icon/text for `right and left nav bar mode`:
![1713594099146.jpg](https://github.com/fast4x/RiMusic/assets/85461823/2d25b5e3-a971-40b6-9a27-48e8c41e91a4) Or place the nav bar below aligned with those buttons instead. 

- [ ] 6. This should be always centered:
![Screenshot_20240420-125749.jpg](https://github.com/fast4x/RiMusic/assets/85461823/3d947602-a8ac-4356-b03e-202b1f67dd83)

### Additional Context

I have written too much. I'll stop here for now.

**Comment by sayyid5416** [comment]
![image](https://github.com/fast4x/RiMusic/assets/78584556/c2aa5c06-dd49-4068-ad02-0ccdd8a007ce)

you mean centered in the top bar. If yes - It would look very bad. Current position looks good.

**Comment by sayyid5416** [comment]
- It's already consistent: logo and name on left, search and menu on right.
- Only thing inconsistent is left navigation bar _(which always will be)_
- Imagine: Remove left bar, and everything will look consistent and properly placed.
- Culprit is not logo, culprit in your case in left navigation bar.
- Logo would look worse when centered. (there's not even enough space, even if you try)

**Comment by sayyid5416** [comment]
- You totally misunderstood what I meant. I wasn't proposing to remove left navigation bar - that would be dumb as its unique and very convenient sometimes.
- What I meant was: Whole UI is shifted to right because of left navigation bar, which make this look inconsistent. I wasn't saying to remove it - I was just stating why it looks inconsistent.

<br>

> > Only thing inconsistent is left navigation bar (which always will be)
>
> I don't think so. Left navigation bar has been the most convenient to me always.

It **_IS_** **_inconsistent_** _(because, well you can see it is present only on one side)_ - There is nothing on right side to balance it. I never said it's not convenient. Inconsistent things can be convenient too.

<br>

## Better approach to solve this _(in my opinion)_:
Shift the navigation upwards so that Top bar is also shifted like rest of the UI.

![mockup](https://github.com/fast4x/RiMusic/assets/78584556/94140321-11c7-4840-b81a-ec6b9eca1f3a)

**Comment by sayyid5416** [comment]
Don't mind it but seriously, I don't like the look of this centered logo. Lets see what fast4x have to say about it. I still think `shifting the naviagtion bar (as shown in my mockup)` is still a better idea btw.

**Comment by sayyid5416** [comment]
> > > > Only thing inconsistent is left navigation bar (which always will be)
> > > 
> > > 
> > > I don't think so. Left navigation bar has been the most convenient to me always.
> > 
> > 
> > It **_IS_** **_inconsistent_** _(because, well you can see it is present only on one side)_ - There is nothing on right side to balance it. I never said it's not convenient. Inconsistent things can be convenient too.
> 
> What do you mean by "because, well you can see it is present only on one side" it is literally `Left navigation bar` why would it need to be on any other side than left?
> 
> I'm not really that good in English I thought "consistent" and "convenient" are pretty much the same thing.
> 
> > ## Better approach to solve this _(in my opinion)_:
> > Shift the navigation upwards so that Top bar is also shifted like rest of the UI.
> > ![mockup](https://private-user-images.githubusercontent.com/78584556/324172262-94140321-11c7-4840-b81a-ec6b9eca1f3a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleDExMDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YWU2YzdlOTI3YmNmZDAxMTA0YzZmZDE0ZmE4MTc4ZmRlZWRiOWYzMTE3OTI4NzVmMmYwYTFiOGFhYmRmOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jU3iKKciBXTdgxten85faeY9ip-edmcoqOTQQNSkkLM)
> 
> This will be a troublesome to add newer features later. Because one navigation bar position having one thing different than the other three. As I mentioned in the description in this issue each navigation bar position should be considered for each feature.

Nothing will be different. Whole UI is shifted to right when using left nav bar, and to left when using right nav bar. This is still being done, but not for the top bar.

**Comment by sayyid5416** [comment]
The frame moving around is navigation bar. It's easier to implement this programmatically specially considering the possibilities of adding new features in future. 

I've shown all navigation bar positions in video i.e left, right, top, and bottom.

https://github.com/fast4x/RiMusic/assets/78584556/966f5d00-f65c-4613-8c12-a9f7ba2a9518

**Comment by sayyid5416** [comment]
> > The frame moving around is navigation bar. It's easier to implement this programmatically specially considering the possibilities of adding new features in future.
> > I've shown all navigation bar positions in video i.e left, right, top, and bottom.
> > 
> >   
> >     
> >     
> > 
> >     video.mp4
> 
> Whoa! Got it. I did see things like these (drag and drop) in lots of places. And I totally didn't consider the possibility of it working like this. I'm often stuck on my own opinions too much ig…I don't see countless other possibilities there might be. 😐

This is how I move around frames in my apps, most probably fast4x have implemented something similar to this.

**Comment by fast4x** [comment]
The crash is due to running out of ram because too many songs are loaded. Set a limit for the songs in the queue.

**Comment by fast4x** [comment]
Thank you for your approach
