### ISSUE TITLE
Tapping on logo reloads more interface layer

### ISSUE THREAD

**Issue by abdulkarimx1** [fast4x/RiMusic#1579]
### Steps to reproduce the bug

Open app 
Tap on logo on top left 

### Expected behavior

The app should be either refreshed or without an action when tapping the logo

### Actual behavior

It keeps adding home interface layers which cause the app to load heavy

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/105733146/00962a99-694a-44f4-b78d-420582917404

### RiMusic version

Latest

### Android version

Android 14

**Comment by sayyid5416** [comment]
- When not on homepage - It should bring the users to homepage
- When on homepage - It should not do anything

**Comment by abdulkarimx1** [comment]
> * When not on homepage - It should bring the users to homepage
> * When on homepage - It should not do anything

Exactly, but the current behavior is seen in the screen record, when in home screen, it keep loading stacks ( layers ) of the home screen everytime which make it lags and slow .

**Comment by fast4x** [comment]
Improved, available from version 0.6.32
