### ISSUE TITLE
🪄[Feature]: Android TV Support

### ISSUE THREAD

**Issue by DarkCrypt** [fast4x/RiMusic#158]
### Description

I installed the app on Android TV 10 and a lot of it works already. More support is needed since it's not specifically made for tv.

### Suggested Solution

It'd be cool if there was at least 1 open source music streaming app for Android TV.

### Alternatives

1. Spotify for tv.
2. Bluetooth.
3. Cast.

### Additional Context

None.

**Comment by OrangeZXZ** [comment]
This is not about android TV but i would love an version for my watch if it is possible in the future

**Comment by DarkCrypt** [comment]
There were some small attempts during ViMusic's development to support Android TV.

There's already a shortcut for tv but the logo needs updated.

**Comment by ikanakova** [comment]
> There's already a shortcut for tv but the logo needs updated.

I will study [TV app icon design guidelines](https://developer.android.com/design/ui/tv/guides/system/tv-app-icon-guidelines) and add to Assets banners and launcher icons in svg for Android TV and also for mobile.

**Comment by ikanakova** [comment]
Banner added #160. As for the icon, I think it can be used the same as for mobiles.

**Comment by DarkCrypt** [comment]
> ### Alternatives
> 
> 1. Spotify for tv.
> 2. Bluetooth.
> 3. Cast.

Adding (4) = Spotify for tv (Mod).

This mod works great.

**Comment by OrangeZXZ** [comment]
> Adding (4) = Spotify for tv (Mod).
> 
> This mod works great.

what d'où you mean by this?

**Comment by DarkCrypt** [comment]
> >Adding (4) = Spotify for tv (Mod).
>> 
> >This mod works great.
>
> what do you mean by this?

I'm trying to keep this thread as accurate as possible. The alternatives are a list that users would need to result to if Android TV isn't supported.

I added (4) because it's another alternative. I'm by no means trying to deter this feature from getting added, just trying to state the facts and be transparent.

I also said that this modded app works great because it does straight up. I was surprised to find this out.

**Comment by fast4x** [comment]
Tried in my TV, behaves quite well, must be improved the support to the navigation of the player. For the rest menus, playlists, tips and much more are usable without any particular problems.

**Comment by OrangeZXZ** [comment]
> Tried in my TV, behaves quite well, must be improved the support to the navigation of the player. For the rest menus, playlists, tips and much more are usable without any particular problems.

Android Auto could also be updated also how do we use it on TV?

And it would be possible to do something to work on an android watch?

**Comment by fast4x** [comment]
Added some optimization, available from version 0.6.12.

**Comment by NikunjKhangwal** [comment]
+1 for this. ViMusic had usable support for TV and since this one is a fork, it does too. Infact it works a bit better because of having the search bar on top instead of bottom so kudos for that. In VI Music, searching for something was really hard because the navigation to search button was clashing with scrolling list. Right now the only way to enjoy music on TV is using any old Spotify mod. It would be really cool to have another better alternative and this one is closest to become one. As others have already mentioned, most of the ui navigation is working fine right now. The bottom buttons on playing screen aren't working, that's the only problem. Other than that it probably needs some code optimizations for smoother experience.

**Comment by fast4x** [comment]
Hi, thanks for your positive feedback, the commitment is to make RIMusic optimized for TV in the best way.

**Comment by DarkCrypt** [comment]
All the same issues in v0.6.12. Unfortunately, with this version I can't reach the player buttons; play, pause, skip. Last version I could.

I'm thinking the slide up player design works great on mobile but not very tv friendly.

**Comment by peat80** [comment]
Just recently discovered this app.
It is definitively an improvement over vimusic on tv.

Almost everyrthing is reachable with remote exept:

The buttons of the miniplayer and FullscreenPlayer are not reachable with remote.

When searching the suggestions are not reachable (trapped on the blinking cursor). 

Also the banner icon shows just a white triangle on red background instead the nice new logo on my shieldtv launcher.

But the app is useable as it is and this is great.
I hope tv useability could be improved even more in the future.

Thanks for all the efforts. 😀👌

**Comment by fast4x** [comment]
Great important details, thank you for the positive feedback.

**Comment by DarkCrypt** [comment]
To expand on peat80's comment...

> The buttons of the miniplayer and FullscreenPlayer are not reachable with remote.

The miniplayer buttons are not reachable.

The Fullscreen player buttons are reachable with some technical navigation:

1. Play a song to open the Fullscreen player. (User cannot access buttons. The remote is still focused on previous screen instead of player).
2. Press back button on remote to minimize player.
3. Go to the main menu on the left, scroll down to reach the miniplayer and reopen to Fullscreen player.
5. Press down on remote 9 times. (This brings focus to the Fullscreen player. Now the bottom bar will be highlighted and clickable).
6. Press up on remote to reach player buttons.

Clicking the bottom bar within the Fullscreen player brings up the song que. After clicking this, user needs to press down on remote 9 times in order to obtain focus and select songs.

> When searching the suggestions are not reachable (trapped on the blinking cursor).

Same. Also, if user presses back on remote to close the keyboard it will not reopen. User is forced to back out and reopen search to use keyboard again.

> Also the banner icon shows just a white triangle on red background instead the nice new logo on my shieldtv launcher.

Same.
___
Separate issue: In-app updater not tv friendly.

It sends user to repo releases within browser for manual download and install. (Because of this I've been using ApkUpdater to obtain updates).

**Comment by LeonDayi** [comment]
Provide ViMusic upload support for Google Chromecast 2022 HD. @fast4x

**Comment by geonux** [comment]
RIMusic on Android TV meets a need not met by other tools. Even the music providers'application are pretty poor on this device. However, a TV is often connected to an amplifier, and is a perfect peripheral for listening to music. These applications shows almost only videos, doesn't handle recommendations, cannot search playlist, and/or do not have"radio" mode whereas the classic Android app are pretty well done.
So when I find RIMusic on FDroid and see that it works on Android TV, tried it out and saw what it did, I immediately loved it.

Of course, there was the problem of focus. That's fine. Thanks to the DarkCrypt trick, I was able to use the application.
But the update I made this evening, hoping that the hard work you're doing to RIMusic would have corrected this bug, breaks the magic combination described above.

The work is very good and relevant, how could we help you fix this problem on Android TV ?

**Comment by fast4x** [comment]
You mean the player I guess, that with the remote you can not use well.

These days I’m implementing several things that go in the direction of Android TV and Android Auto. To help me, if you are a developer you can try to implement It fast.

**Comment by DarkCrypt** [comment]
We can jam again with v0.6.24 and v0.6.25.

**Comment by peat80** [comment]
The (not reachable) fab from 0.6.30 removed the ability to reach the settings menu with remote. 😕

**Comment by fast4x** [comment]
you are right, I'll restore it for tv.

**Comment by peat80** [comment]
New top bar is reachable with remote. 😀👍

Would be even easier to reach if the search and menu button were on the left side (like the other buttons) and the rimusic logo were on the right.

Good job with the new update. 😀👍

**Comment by fast4x** [comment]
Nice feedback, i can also add option to move it

**Comment by peat80** [comment]
> Nice feedback, i can also add option to move it

Sounds good too.
Personally i woluld prefer to swap positions if the navbar is configured left and leave it as it is now when navbar is right. 😀👍

**Comment by fast4x** [comment]
Yes make sense.
