### ISSUE TITLE
[Feature]: Bring back floating search button for RiMusic UI

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1582]
### Description

Since the latest update (0.6.30), the RiMusic UI exclusively uses a search button that is in the top navigation bar. However, to me at least, the floating search button present in versions prior to 0.6.30 (except the multifunctional one in 0.6.29) is aesthetically better and more appealing. Thus, I suggest that it be brought back

### Suggested Solution

Bring single function floating search bar back

**Comment by sayyid5416** [comment]
**_If it's implemented_** - It should be `disabled` by default (because a search icon is already present in top bar).

**Comment by fast4x** [comment]
you mean you like the icon you could move?

**Comment by privacyfreak84** [comment]
> you mean you like the icon you could move?

No, like how it was like 4 versions ago. Unmovable and unifunctional

**Comment by fast4x** [comment]
is available on ViMusic mode

**Comment by KrisTamang** [comment]
> you mean you like the icon you could move?

![Screenshot_20240420-173857_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/62e0befd-64fa-423d-b5b3-04e2bac06eba)
He mean like this i guess(Vi music theme)
Thank you for vi based theme..!
This is just what i asked for..!
It would look really cool if the statistics was bottom left corner..!

**Comment by privacyfreak84** [comment]
> If it's implemented - It should be disabled by default (because a search icon is already present in top bar).

And if its enabled, the icon in the top bar should be disabled

**Comment by privacyfreak84** [comment]
> If it's implemented - It should be disabled by default (because a search icon is already present in top bar).

And if its enabled, the icon in the top bar should be disabled

**Comment by fast4x** [comment]
ok

**Comment by privacyfreak84** [comment]
Idea: There should be a setting to set where the search button is: on the top, navigation bar or floating

This way, there would be no more problems with the search button being in 2 places: on the top/ floating and in the navigation menu. Only one location would be selectable at a time

**Comment by fast4x** [comment]
You could move at will and stay in position.

**Comment by privacyfreak84** [comment]
Do you mean move the search button to a single location (out of multiple options) and have it stay there?

**Comment by privacyfreak84** [comment]
So a movable button that, after having moved it to a desired location, stays in a certain position unless specifically changed later (in the settings)?

**Comment by fast4x** [comment]
Yes but without a setting

**Comment by privacyfreak84** [comment]
So how will it be moved? By holding the button, like as in 0.6.29?

**Comment by fast4x** [comment]
Yes, in the future it stay in new position

**Comment by privacyfreak84** [comment]
Ok. Can there be an option to lock it in place though?

**Comment by fast4x** [comment]
we will see according to the result of the change in dev.

**Comment by privacyfreak84** [comment]
Change in dev? Are you going to stop working on this app?

**Comment by fast4x** [comment]
Absolutely no! I wanted to say that I will see to improve the behavior of the button in the future after some functions that are in development.

**Comment by privacyfreak84** [comment]
OK. Thank goodness!

**Comment by fast4x** [comment]
Implemented, now floating icon stay in the moved position, available from version 0.6.32

**Comment by privacyfreak84** [comment]
So is it movable or not?

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/21dcae6b-52f7-4a77-9661-6987b410cdb8

**Comment by privacyfreak84** [comment]
Looks good. But can the time required to hold the button in order to move it be increased to, say, 3 or 5 seconds? That way, it would be easier to avoid accidentally moving the button

**Comment by fast4x** [comment]
It does not happen accidentally, because it does not move with a click but with a long press managed by the system.

**Comment by privacyfreak84** [comment]
So how long must the press be currently to move the button

**Comment by privacyfreak84** [comment]
Closing as implemented

**Comment by fast4x** [comment]
at least 2 seconds fixed, so it’s just different from a simple tap...

**Comment by privacyfreak84** [comment]
Ok. 2 second sounds fine

**Comment by fast4x** [comment]
yes it's a standard time for general long press gesture.

**Comment by privacyfreak84** [comment]
Reopening as not implemented

**Comment by aneesh1122** [comment]
> Idea: There should be a setting to set where the search button is: on the top, navigation bar or floating
> 
> This way, there would be no more problems with the search button being in 2 places: on the top/ floating and in the navigation menu. Only one location would be selectable at a time

This is great. Just let us choose where we want the search button once and for all. There won't be any complications of having multiple search buttons then.

btw no matter what I choose, the search icon always remains on the top. The floating option is still missing though. Choosing to put the search icon in the navigation bar doesn't change anything

**Comment by fast4x** [comment]
> Reopening as not implemented

you mean to add setting and enable also in RiMusic ui mode?

**Comment by aneesh1122** [comment]
> > Reopening as not implemented
> 
> you mean to add setting and enable also in RiMusic ui mode?

Yeah. I never used ViMusic so I'm not sure how it is. Would be great to have floating search icon in RiMusic UI too

**Comment by sayyid5416** [comment]
> > > Reopening as not implemented
> > 
> > 
> > you mean to add setting and enable also in RiMusic ui mode?
> 
> Yeah. I never used ViMusic so I'm not sure how it is. Would be great to have floating search icon in RiMusic UI too

fast4x If it's implemented, make it disabled by default _(two options for same thing won't look great)_

**Comment by aneesh1122** [comment]
> > > > Reopening as not implemented
> > > 
> > > 
> > > you mean to add setting and enable also in RiMusic ui mode?
> > 
> > 
> > Yeah. I never used ViMusic so I'm not sure how it is. Would be great to have floating search icon in RiMusic UI too
> 
> two options for same thing won't look great

That's why I think this should be added in the option. only one search icon and we get to decide where to have it

https://github.com/fast4x/RiMusic/issues/1582#issuecomment-2067681226

**Comment by fast4x** [comment]
> > > > Reopening as not implemented
> > > 
> > > 
> > > you mean to add setting and enable also in RiMusic ui mode?
> > 
> > Yeah. I never used ViMusic so I'm not sure how it is. Would be great to have floating search icon in RiMusic UI too
> 
> fast4x If it's implemented, make it disabled by default _(two options for same thing won't look great)_

absolutely yes

**Comment by privacyfreak84** [comment]
> you mean to add setting and enable also in RiMusic ui mode?

Exactly

**Comment by fast4x** [comment]
Implemented, avaibla from version 0.6.33

**Comment by privacyfreak84** [comment]
Thank you!
