### ISSUE TITLE
Some Suggestions and changes..!

### ISSUE THREAD

**Issue by KrisTamang** [fast4x/RiMusic#1584]
### Description

Downloading music for offline should include album art and music itself..!
It will be really easy.. just with one click user shouldn't worry about downloading ablum art for every single by listening music.!
It will be pretty cool if it downloads lyrics too.. !

### Suggested Solution

![Screenshot_20240420-173715_RiMusic](https://github.com/fast4x/RiMusic/assets/107674915/f76d34c0-b6ba-4b96-b211-e1facd780b67)
And please make album art save as a data not cached. Its keep removing by itself..!
And implement that clear button on image caches for clearing "un-downloaded song's album art erase"
Hope you got the point..! Thank ya.!

**Comment by aneesh1122** [comment]
I was about to post the same Issue. The album cover for downloaded songs are not appearing in the player.

The album cover is downloaded since it's shown in the playlist. It is only after playing the song that the album cover disappears.

The album cover appears fine when the mobile is connected to the internet so I don't know what's happening.

**Comment by KrisTamang** [comment]
> I was about to post the same Issue. The album cover for downloaded songs are not appearing in the player.
> 
> The album cover is downloaded since it's shown in the playlist. It is only after playing the song that the album cover disappears.
> 
> The album cover appears fine when the mobile is connected to the internet so I don't know what's happening.

Yeah album art only shows if you play the song when you are offline and i think it is save as caches not data (just like music)

**Comment by KrisTamang** [comment]
Yeah album art only shows if you listen the song when you are offline and it is saving as caches (temporary) not like music itself..!
Hope to see fix as i mentioned..!

**Comment by aneesh1122** [comment]
> Yeah album art only shows if you listen the song when you are online and it is saving as caches (temporary) not like music itself..! Hope to see fix as i mentioned..!

I don't know how RiMusic download songs but when I use yt-dlp I can embed album art which makes it a part of the song. If RiMusic is also using yt-dlp then it should add code to embed thumbnails too.

**Comment by KrisTamang** [comment]
> > Yeah album art only shows if you listen the song when you are online and it is saving as caches (temporary) not like music itself..! Hope to see fix as i mentioned..!
> 
> I don't know how RiMusic download songs but when I use yt-dlp I can embed album art which makes it a part of the song. If RiMusic is also using yt-dlp then it should add code to embed thumbnails too.

Maybe they can fix it..!

**Comment by sayyid5416** [comment]
+1.
