### ISSUE TITLE
Make buttons on top navigation bar unclickable if already on page linked to by said buttons

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1585]
The new buttons on the top are clickable even when you are already in one of the locations to which the button links.
Ex: While searching for a song, the search button is still clickable.
In the home screen, the RiMusic button (which I believe should be removed) is still clickable. 

All of this causes lots of lag

Link to video demonstrating this:  https://imgur.com/a/NRIBaam

**Comment by fast4x** [comment]
Even if it remains clickable, what problems does it create?

**Comment by privacyfreak84** [comment]
Lots of lag, and it doesn't make much sense to have it clickable if you're on the even already

**Comment by EmmetSchuler** [comment]
Yeah, i tend to agree. Maybe hide the menu button if you are in a sub menu. 
Another issue that it can cause is having to go back through the same menu multiple times before reaching the home screen.

**Comment by fast4x** [comment]
Not, left arrow go back and title go to home...

**Comment by privacyfreak84** [comment]
True, but it all causes a lot of lag that doesn't go away until the app is force stopped in android settings

**Comment by privacyfreak84** [comment]
Thanks for implementing! Again, I hope that this to will increase the app's performance
