### ISSUE TITLE
Quick picks is taking time to load

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#1586]
### Steps to reproduce the bug

open quick picks, it is taking time to load after the latest update

(before the update, the quick pick issue #1553 was fixed automatically but after the update the quick pick is taking time to load)

### Expected behavior

it should not take time to load

### Actual behavior

it is taking time to load

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/127825700/cd0964cf-361d-4130-bde9-aea0da7494a5

https://github.com/fast4x/RiMusic/assets/127825700/e91d8396-11e6-4bbf-bac9-3a379340bd9e

### RiMusic version

0.6.31

### Android version

android 11

**Comment by aRandomMenno** [comment]
I think this is because youtube has butchered their API, they changed things. Youtube does not want applications to block ads. So they are trying to crack down on all adblocking methods first they tried browsers, now they're trying it with their API.

**Comment by privacyfreak84** [comment]
But it works with previous versions

**Comment by dainvincible1** [comment]
> I think this is because youtube has butchered their API, they changed things. Youtube does not want applications to block ads. So they are trying to crack down on all adblocking methods first they tried browsers, now they're trying it with their API.

but it was automatically fixed before the update (maybe youtube had fixed it cause it was issue from youtube's side)

**Comment by fast4x** [comment]
Actual quick pics page have multiple bugs, it occur for changed YTM api, next version will be restored classic quick pics maybe a new custom quck pics page....

**Comment by dainvincible1** [comment]
> Actual quick pics page have multiple bugs, it occur for changed YTM api, next version will be restored classic quick pics maybe a new custom quck pics page....

thank you
