### ISSUE TITLE
I have two requests

### ISSUE THREAD

**Issue by DarkblooM-IO** [fast4x/RiMusic#1587]
### Description

Feature 1 : enqueue artist : add all songs from an artist to the queue
Feature 2 : search in playlist : add a search bar to playlists to be able to search for songs within it

### Suggested Solution

­

**Comment by aneesh1122** [comment]
Feature 2 is already there
![Screenshot_2024-04-20-21-57-05-519_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/0eb992d4-2d37-4301-9eec-81a4b41863c9)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.32

**Comment by DarkblooM-IO** [comment]
> Feature 2 is already there ![Screenshot_2024-04-20-21-57-05-519_it.fast4x.rimusic-edit.jpg](https://private-user-images.githubusercontent.com/45353488/324191064-0eb992d4-2d37-4301-9eec-81a4b41863c9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTk0MzAsIm5iZiI6MTcxMzc5OTEzMCwicGF0aCI6Ii80NTM1MzQ4OC8zMjQxOTEwNjQtMGViOTkyZDQtMmQzNy00MzAxLTllZWMtODFhNGI0MTg2M2M5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE1MTg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNjk5MmQzODUzMGJmNjBkYzM4OTNhNjFlOGZlN2QyMTJkODRmZWIzODgyMjBiMGMwNGE4ZTJhOWY5MzJjODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4KmbZhKv8emQEMH0dVSYvKRJiZeQ-IH3d1dNmo8DURU)

Oh wow I never noticed the icon lmao sorry about that

**Comment by aneesh1122** [comment]
It is only adding 5 songs from the artist in the queue.

Also all the songs of the artist aren't appearing when I select `view all`
