### ISSUE TITLE
Importing playlist from youtube bug

### ISSUE THREAD

**Issue by sebbekm** [fast4x/RiMusic#1590]
### Steps to reproduce the bug

1. Go to 'youtube'
2. Open playlist
3. Press share and choose Rimusic

### Expected behavior

I should be able to import the whole playlist.

### Actual behavior

Importing a playlist from youtube still doesn't work like it should, only a part of the playlist is added.

This playlist has 2k+ songs but only 1060 songs are added:
https://youtube.com/playlist?list=PLJPgiltmVBUiX73tb2l9Nq_Nnw-oRA69b&si=9rLuaFG81G5a0rN6

1060 songs seems to be the upper limit because I have tried importing another playlist with 1,3k+ songs but only 1060 songs are added from that one aswell.

### RiMusic version

0.6.31

### Android version

Android 13

**Comment by aneesh1122** [comment]
YT has a playlist limit of 5000 videos. I thought that this app is creating playlist in our device so it should be unlimited.

**Comment by fast4x** [comment]
But what do you do with a playlist of 1000 songs and more? ahahahaha

**Comment by aneesh1122** [comment]
> But what do you do with a playlist of 1000 songs and more? ahahahaha

Me with a playlist having 813 songs
![741s.gif](https://github.com/fast4x/RiMusic/assets/45353488/db67fabe-c111-44db-93b5-f687a7433ea2)

I have added most of the songs I've liked since the year 2000 so 1000 songs ain't really much. Right? 😅

Seriously though, pls let us add unlimited songs or at the very least 5000 songs in a playlist

**Comment by fast4x** [comment]
Ok

**Comment by aneesh1122** [comment]
> Improved, available from version 0.6.32

Thanks man. What's the limit now?

**Comment by fast4x** [comment]
5000

**Comment by sebbekm** [comment]
> Improved, available from version 0.6.32

Awesome 👍

**Comment by sebbekm** [comment]
> But what do you do with a playlist of 1000 songs and more? ahahahaha

1000 songs ain't much haha
