### ISSUE TITLE
Equalizer [Feature]: 

### ISSUE THREAD

**Issue by Cuchurrumin19** [fast4x/RiMusic#1591]
### Description

¡Hola!
Debo mencionar que RiMusic es una increíble aplicación, la he estado usando últimamente y es simplemente genial.
Pero he notado que el ecualizador que tiene mi celular no funciona, el sonido no cambia aunque elija cualquier configuración.
Tuve que recurrir a uno (Ecualizador) externo, no sé si me pasa solo a mí o sea algún error de la app.

### Suggested Solution

Me gustaría que agregaran (Si se pudiera, claro está) un ecualizador dentro de la aplicación para así configurar el sonido a nuestro gusto.

**Comment by fast4x** [comment]
Hello thanks, the equalizer is operated by the system not by RiMusic, so I can not do anything else.

**Comment by Cuchurrumin19** [comment]
> Hello thanks, the equalizer is operated by the system not by RiMusic, so I can not do anything else.

Ya veo, entiendo.
¡Muchas gracias por la respuesta!
Y muchas felicidades por el gran trabajo que han hecho con la aplicación.
