### ISSUE TITLE
[Feature]: Auto detect links and support them in normal search

### ISSUE THREAD

**Issue by DucksInParks** [fast4x/RiMusic#1592]
### Description

Instead of users having to pick the links section for links to work, it'd be nice and easy to implement a feature that automatically detects YouTube links and plays them when they're searched.

Keeping the current tab would be nice, since people may not expect links to work in normal search.

### Additional Context

Thank you 🫡

**Comment by DucksInParks** [comment]
Currently, the normal behavior when a user puts a link in the normal search is for the app to crash.

**Comment by fast4x** [comment]
There's a Go to link tab in search tab without search. Just paste link and play it directly.

**Comment by fast4x** [comment]
![Screenshot_2024-04-21-00-20-59-917_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/6bb61f7e-e2ce-4a12-bc33-4abdf54c3418)

**Comment by DucksInParks** [comment]
I know, but it would be nice to be able to put the link in online search. It's also simple enough to detect a YouTube link and automatically play it. 

Having to pick this section isn't that big of a deal, but people expect links to open when put in search.
