### ISSUE TITLE
Ui

### ISSUE THREAD

**Issue by debarjun2004** [fast4x/RiMusic#1593]
### Description

Would you kindly relocate the UI buttons from the side to the bottom? (like Spotify, yt music) It would make one-handed use more convenient. Thanks ♥️

### Suggested Solution

And also there should be speak to search...

**Comment by dAtA-TRoN** [comment]
> Would you kindly relocate the UI buttons from the side to the bottom?

You can do this already:

![Screenshot_2024-04-21-06-42-02-00_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/efe369f2-97e2-4add-a432-1fe3b0977c7c)
