### ISSUE TITLE
Strange behaviors, Bugs and further Observations

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1594]
### Description

When selecting either 'Go to album' or 'More of Artist XY' from the three dots menu in the Player View, peculiar things occur. I'll describe each separately below:

### Observations

**1. 'Go to album' Observations**

When tapping on 'Go to album' from the three dots menu in the Player View, the following peculiarities occur:

1. The player does not minimize automatically to show the Album Page; it must be done manually. This should not be the case.

2. When manually minimizing the player, it leads to an Album Page with incorrect formatting. The new 'RiMusic logo header' along with the search & settings button is missing and so the formatting is broken, as the Album Name is displayed much too high.

![IMG_20240421_074923.jpg](https://github.com/fast4x/RiMusic/assets/71184627/63f37fd8-6cc9-4f1d-818b-5003a42801a6)

3. However, if 'Go to album' is not selected from the three dots menu but instead the icon shortcut is used, it leads to a correctly displayed album page.

![IMG_20240421_084546.jpg](https://github.com/fast4x/RiMusic/assets/71184627/83206035-bee8-4741-afa5-0affa99adba7)

**2. 'More of Artist XY' Observations**

When tapping on 'More of Artist XY' from the three dots menu in the Player View, the following peculiarity occur:

1. The player does not minimize automatically to show the Artist Page; it must be done manually. This should not be the case.

_I'll illustrate the next point using a specific album where I also noticed an inconsistent and buggy behavior:_

2. Select the album 'Exorcism' by 'Sidewalks and Skeletons'. Look at the song list. Song 2 and 3 each have an additional artist featured, but RiMusic has trouble displaying this correctly for one of the songs, not the other. The question is why:

**Song 2:** Shadow - Sidewalks and Skeletons & Goo Munday

![IMG_20240421_080721.jpg](https://github.com/fast4x/RiMusic/assets/71184627/efb8750a-4075-4231-816b-3498c9c88b08)

**Song 3:** Eternal Rest - Sidewalks and Skeletons & Cashforgold

![IMG_20240421_081045.jpg](https://github.com/fast4x/RiMusic/assets/71184627/687fbc74-61e5-44bf-ab4a-a125a12986c9)

---

### Another Bug

And finally, a significant bug I've noticed:

1. Open RiMusic

2. Play any song

3. Then, in the Player View, select 'More of Artist XY' from the three dots menu

4. Now scroll down on the Artist Page to the albums and select one

5. RiMusic crashes

https://github.com/fast4x/RiMusic/assets/71184627/b25d46d5-fd6e-4595-9d61-cddc1fc9c717

**Comment by privacyfreak84** [comment]
I too have noticed the album crash. Weird thing is that it doesn't appear to happen with all albums or artists

#1588

**Comment by dAtA-TRoN** [comment]
> I too have noticed the album crash. Weird thing is that it doesn't appear to happen with all albums or artists
> 
> #1588

I believe it only happens the way I described. I have tried other ways too, but have not been able to reproduce it in any other way.

**Comment by dAtA-TRoN** [comment]
> I too have noticed the album crash. Weird thing is that it doesn't appear to happen with all albums or artists
> 
> #1588

I believe it only happens the way I described. I have tried other ways too, but have not been able to reproduce it in any other way.

**Comment by fast4x** [comment]
Fixed album and artists crash, available from version 0.6.32

**Comment by dAtA-TRoN** [comment]
> Fixed album and artists crash, available from version 0.6.32

![proxy-image(2).gif](https://github.com/fast4x/RiMusic/assets/71184627/d5be140e-dd71-471c-9729-84f682214781)

**Comment by fast4x** [comment]
> I'd like to add one thing. Open an album, tap on three dots menu, you'll see the year is showing in the middle. Which doesn't look good because `Album title` and `Artist name` are on the left. ![Year in the middle](https://private-user-images.githubusercontent.com/85461823/324233091-29b37033-03e9-4871-9ddf-b4807d9f0e58.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTE1MDYsIm5iZiI6MTcxMzY5MTIwNiwicGF0aCI6Ii84NTQ2MTgyMy8zMjQyMzMwOTEtMjliMzcwMzMtMDNlOS00ODcxLTlkZGYtYjQ4MDdkOWYwZTU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA5MjAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNWRkYTAyYmRlYWJhYzc3ZWJmYmI0MDNlMGIwNmNkZGVjMDdiMzY4ZTA2NzA4NjE1OTg0MjA5MzMzNTY0MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ParCpjHvujscmt4iU4nPTVKkn6XdvSZ7wo6kFrkMDSU)

Fixed

**Comment by fast4x** [comment]
Completed, all fixed, available from version 0.6.32

**Comment by dAtA-TRoN** [comment]
> Completed, all fixed, available from version 0.6.32

Awesome 💪🏼!

**Comment by dAtA-TRoN** [comment]
> Seems like after latest update there's lots of inconsistencies and bugs. The one I mentioned on my comment in this issue there's another similar bug. I'll probably report that as well as some others (I'll try to report only a few important ones) in a new issue.

It's always best to keep fast4x in the loop about any bugs you encounter. Reporting each one allows him to prioritize them more effectively.

**Comment by fast4x** [comment]
> Seems like after latest update there's lots of inconsistencies and bugs. The one I mentioned on my comment in this issue there's another similar bug. I'll probably report that as well as some others (I'll try to report only a few important ones) in a new issue.

it's correct, bugs are normal event.
