### ISSUE TITLE
[Feature]: Android Auto: Brighter symbols in darkmode

### ISSUE THREAD

**Issue by martkol** [fast4x/RiMusic#1595]
### Description

Symbols should be brighter in darkmode

![screendump](https://github.com/fast4x/RiMusic/assets/55714786/057507c6-f3b8-4244-84a7-7d1beca28ae6)

### Suggested Solution

Brighter symbols

**Comment by fast4x** [comment]
@ikanakova can check this please? Thanks in advance.

**Comment by fast4x** [comment]
@ikanakova

**Comment by fast4x** [comment]
Fixed, available from version 0.6.33

**Comment by ikanakova** [comment]
Sorry, I didn't even notice you mentioned me. I've been little to hectic right now. I hope it will get better and I will have more time for RiMusic.
