### ISSUE TITLE
Quick Picks Reloading Too Often

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1598]
Every time we exit the settings, exit the search menu etc. quick picks reloads (and takes a lot of time to do so). This momentarily freezes the app and makes the entire experience of using the app less smooth.

Such was not the case in earlier versions of the app

**Comment by privacyfreak84** [comment]
A demonstration of this behavior is present in the video attached in #1599

**Comment by dAtA-TRoN** [comment]
Good point, I noticed that too.

**Comment by dAtA-TRoN** [comment]
Good point, I noticed that too.

**Comment by fast4x** [comment]
In 0.6.32 version will be like before.

**Comment by privacyfreak84** [comment]
Thanks!

**Comment by fast4x** [comment]
For now will be like before, I'm dev new quick pics page.
