### ISSUE TITLE
All menus visited in the app are stored in memory, resulting in lag and crashes when pressing the back button in the android navigation menu

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1599]
### Steps to reproduce the bug

Example:
1. Open app
2. Open settings
3. From there, open song search menu
4. From there, open settings
5. From there, open history
6. keep opening as many menus as required in a reasonable use case of this app
7. Click back button in android navigation menu repeatedly
8. It can be observed that pressing the back button simply brings you back to the menu you last visited

### Expected behavior

Pressing the back button takes you to home page eventually (page with quick picks) without cycling through every menu you've visited

### Actual behavior

Pressing the back button simply brings you back to the menu you last visited. This results in a lot of lag, and occasionally, crashes (see video attached:  in the end, the app crashes when I spam the back button)

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/90613992/86b56ae4-73ef-4a31-a761-6a80b4f4798d

### RiMusic version

0.6.31

### Android version

Android 11

### Additional information

I suggest a return to the old system of navigation (0.6.28). No such issues were present there. I don't think it needed replacing, nor do I think that anyone had a problem with it.

However, if we are to continue with this new navigation system, then I think it will require some refining (perhaps this warrants a new discussion or issue)

**Comment by dAtA-TRoN** [comment]
If I understand correctly, the app remembers the path of the previously opened page and keeps it in the memory. However, this causes the back button to not work as expected since you have to navigate back through the entire path, page by page. Yes, that's definitely an issue and should be fixed.

The following problem, while not exactly the same at its core, also relates to app navigation. Since fixing this bug is important to me, I'll mention it again here #1315 😁.

**Comment by fast4x** [comment]
Old navigation system isn't restorable because is story not the future. 
Back button have a single feature and it's "go to back or previously page". From anywhere you can click on logo or name and go to the home instantly.

**Comment by fast4x** [comment]
> If I understand correctly, the app remembers the path of the previously opened page and keeps it in the memory. However, this causes the back button to not work as expected since you have to navigate back through the entire path, page by page. Yes, that's definitely an issue and should be fixed.
> 
> The following problem, while not exactly the same at its core, also relates to app navigation. Since fixing this bug is important to me, I'll mention it again here #1315 😁.

back is back or previously page...

**Comment by fast4x** [comment]
Old navigation system isn't restorable because is story not the future. 
Back button have a single feature and it's "go to back or previously page". From anywhere you can click on logo or name and go to the home instantly.Max can i to do is hide back button in settings but is wrong way.

**Comment by dAtA-TRoN** [comment]
> back is back or previously page...

https://github.com/fast4x/RiMusic/assets/71184627/88f687d8-2f06-463e-bb17-70ba72852cb6

Well, isn't this a bit of a puzzling behavior, even if it dutifully does what it's supposed to? In my view, it suffices for the history page and the statistics page to be accessible via the back button just once. The app doesn't need to remember such a ridiculously long nonsensical path. Sure, you can always tap on the 'RiMusic Logo' to escape the eternal river of shame, but where's the ambition in that 😌🤌🏼? It doesn't have to be this way. Other apps recognize such things too. Yes, it's not necessary, but it would be more elegant. It might require a bit of extra effort, but it'll make things a tad prettier in the end 🙃.

**Comment by fast4x** [comment]
Improved, available from version 0.6.32

**Comment by dAtA-TRoN** [comment]
> Improved, available from version 0.6.32

Sounds great...
![proxy-image(2).gif](https://github.com/fast4x/RiMusic/assets/71184627/48b5249e-463f-4698-944a-f5bc8655cd97)

**Comment by privacyfreak84** [comment]
Thanks! I hope this will provide a performance boost (as performance has really dropped with this latest update).

**Comment by dAtA-TRoN** [comment]
> Thanks! I hope this will provide a performance boost (as performance has really dropped with this latest update).

I noticed that too.

**Comment by dAtA-TRoN** [comment]
> Thanks! I hope this will provide a performance boost (as performance has really dropped with this latest update).

I noticed that too.
