### ISSUE TITLE
Bottom of albums and artist overview is cut off

### ISSUE THREAD

**Issue by Juggalage** [fast4x/RiMusic#1601]
### Steps to reproduce the bug

Go to any album or artist

### Expected behavior

All songs should be visible

### Actual behavior

The last song of an album is hidden, and the singles or artist description are cut off.

### Screenshots/Screen recordings

![Screenshot_20240421-111247](https://github.com/fast4x/RiMusic/assets/32726906/ca1d6d3f-a3e6-48f7-9369-5222aea07d2f)
![Screenshot_20240421-111138](https://github.com/fast4x/RiMusic/assets/32726906/1c3f1a0f-3676-4255-b4e3-c1f7de7c175c)
![Screenshot_20240421-110853](https://github.com/fast4x/RiMusic/assets/32726906/73953c70-4042-4133-8ad3-9b7da67bbf80)

### RiMusic version

0.6.31

### Android version

Android 14

**Comment by dAtA-TRoN** [comment]
I guess it's fixed already and will be released with the next update.

**Comment by Juggalage** [comment]
> I guess it's fixed already and will be released with the next update.

Awesome, thanks for the quick update.
