### ISSUE TITLE
Few more inconsistencies/bug of v0.6.31

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1603]
### Description

Even though few of these are bugs I'm still adding these as feature request because idk why this sounds more right to me. I forgot what else I was gonna write here…anyway I'll add everything below now.

### Suggested Solution

- [x] Tab doesn't load where it was left off.
Tab automatically goes back to top when returned from another page even if it (tab) was previously scrolled down. Seems like I'm actually unable to word the problem properly so I added two short videos.

https://github.com/fast4x/RiMusic/assets/85461823/eea7391f-f535-45b2-9394-75695cb7878f

https://github.com/fast4x/RiMusic/assets/85461823/c16a3211-55fa-447c-abf0-a3377e35bd83

**Seems like this bug has been fixed already so I marked this done**

- [x] Year in the middle of Albums.
Year shows in the middle on `Albums` as well as on `Singles` inside of `Artist pages`. Maybe aligned with `Titles`. But still this doesn't look good at least not to me. But on `Overview` page (And `Albums tab`) this does look good. 
![Year in the middle again](https://github.com/fast4x/RiMusic/assets/85461823/77f9bbd7-dae3-4d4e-898d-e2e7bd203530)

- [x] Spaces.
Some probably won't have any problem with it but I find this space a bit too much: 
![1713726295588.jpg](https://github.com/fast4x/RiMusic/assets/85461823/2ecd349c-4400-469d-8d88-8068e6fb39fc)
Same with this: ![1713728463442.jpg](https://github.com/fast4x/RiMusic/assets/85461823/ce424436-e998-45fd-ae6b-2f6ec719b611)
I marked the clock icon because I think it's just unnecessary here and eating up space on the left. (I remember sayyid probably mentioned this on an issue before) As well as there (User added/imported playlists): ![Screenshot_20240422-013441.jpg](https://github.com/fast4x/RiMusic/assets/85461823/3e5e5bc6-708c-4160-8e29-9b07c12d59f2)

- [x] Album sidebar.
Place these icons/buttons beside the `Album title` horizontally. It'll save that long space on the left. Sounds like a bad idea to myself though. 💀 But you can do this same thing with `user added/imported playlists`. If this idea is actually alright and applicable.
![Screenshot_20240422-021625.jpg](https://github.com/fast4x/RiMusic/assets/85461823/9697732b-4da5-4b92-ab77-e0a8674b9d85)
Actually at first I was gonna suggest moving this bar below the Album cover… ![1713731362199.jpg](https://github.com/fast4x/RiMusic/assets/85461823/9bd19701-8864-4ca8-a2b1-8aa92a928ed8) but that's even worse idea.

### Additional Context

I always feel like "I wrote too much 😬"

**Comment by fast4x** [comment]
> I just noticed those sidebar buttons/icons aren't visible on right, bottom navigation bar. Is that intentional?

I don't understand

**Comment by aneesh1122** [comment]
> * Actually at first I was gonna suggest moving this bar below the Album cover
> * but that's even worse idea.
Why do you think it's even worse? It will be great for one-hand usage. easily reachable when icons are below album

**Comment by aneesh1122** [comment]
#1478 check this out. I've posted some screenshots.

**Comment by NikunjKhangwal** [comment]
> These: ![Screenshot_20240422-033523.jpg](https://private-user-images.githubusercontent.com/85461823/324283818-7f7a909f-f16c-4137-9ff8-21057fe2b5f0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDIwMTIsIm5iZiI6MTcxNTI0MTcxMiwicGF0aCI6Ii84NTQ2MTgyMy8zMjQyODM4MTgtN2Y3YTkwOWYtZjE2Yy00MTM3LTlmZjgtMjEwNTdmZTJiNWYwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA4MDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZjNhYTRkZTg3ZGQzOTFhM2QyNTE4M2MwOTMxYTk4MGU0OGQ0MDNlNDA1YTJjYWYyMmIwZjUzN2RjOTBiYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SVviwm0woTYaBJi5u73eJaRggMFlkwLLfr9qR0LPD-4)

Aren't these part of navigation bar?
Btw i also agree with buttons having below album, artist image. It's not a bad idea at all.

**Comment by aneesh1122** [comment]
> Btw i also agree with buttons below album, artist image

Already implemented

**Comment by NikunjKhangwal** [comment]
Yeah, just saw it. Nice addition
