### ISSUE TITLE
[Feature]: Adjust sensitivity of swipe to change song

### ISSUE THREAD

**Issue by Glich440** [fast4x/RiMusic#1605]
### Description

I often accidentally change the song accidentally while trying to swipe down, this seems like a common issue

### Suggested Solution

~~A slider in settings to modify the sensitivity of the gesture~~
**Reduce the sensitivity of the gesture**

### Alternatives

Entirely disabling the feature, but I quite like it

**Comment by Glich440** [comment]
> As for the feature you actually mentioned you can disable that from settings if you want. Go to `Settings`>`Player Appearance`>`Disable horizontal swipe` Keep that on to avoid that swiping feature.
It's an option but I actually quite like it, it's just too sensitive in my opinion

**Comment by dAtA-TRoN** [comment]
I don't think we need a new slider for everything right away. It would be sufficient if the sensitivity were adjusted a little.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.42
