### ISSUE TITLE
[Feature]: Retain translation status on the lyrics when maximized

### ISSUE THREAD

**Issue by Glich440** [fast4x/RiMusic#1607]
### Description

If the translation of lyrics is active in the small thumbnail form it doesn't retain translation when putting them in full screen

### Suggested Solution

Make both lyrics displays synchronize the status of the translation

**Comment by faustaahmad** [comment]
It'll be better if the translation itself are persistent
Example:
• Play song A > Get lyrics > Translate=True
• Play song B
• Play song A > Open lyrics (still translated)

Similar to how un/synchronized lyrics are using different lyrics
Save those translated strings
Press the switch will make translated lyrics dis/appear
Hold the switch will refresh the translated lyrics & make 'em appear

**Comment by fast4x** [comment]
Implemented, available from version 0.6.42
Use new full screen lyrics developed by @aneesh1122

**Comment by aneesh1122** [comment]
https://github.com/fast4x/RiMusic/assets/45353488/07c803d4-647f-4634-bc2e-74e722a37713

Lyrics remain translated even if you expand the lyrics or change the song
