### ISSUE TITLE
Translating while on Synchronized Lirics makes the app Lag and Crash

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#161]
### Steps to reproduce the bug

1. Listen to a song that has Synchronized Lyrics
2. Translate while using Synchronized Lyrics

### Expected behavior

It should translate withouth à problem or the button be disabled

### Actual behavior

Makes the app not usable for a big momment sometimes making crash

### Screenshots/Screen recordings

( I don't have enought 4G conection for a video )

### RiMusic version

6.10.1

### Android version

Android 13 and 12 ( also dose to my friend )

### Additional information

French and Romanian have the same bug

**Comment by fast4x** [comment]
Fixed and added new translations internal engine
Available from 0.6.11
