### ISSUE TITLE
Somes settings don't work ?

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#1612]
### Steps to reproduce the bug

Enabled show search bar in navigation bar with statistics and nothing change, don't appear in navigation bar
![Screenshot_2024-04-22-21-35-03-787_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/12d9d2d7-25c7-486b-ba32-68b967a0d469)

### Expected behavior

.

### Actual behavior

.

### RiMusic version

0.6.31

### Android version

A12 MIUI 14

**Comment by fast4x** [comment]
Navigation bar is used in ViMusic mode left and right position.

**Comment by NEVARLeVrai** [comment]
> Navigation bar is used in ViMusic mode left and right position.

Oh ok

**Comment by faustaahmad** [comment]
> Navigation bar is used in ViMusic mode left and right position.

Then add to description, example:
_"Statistic in ViMusic navigation bar"_

**Comment by NEVARLeVrai** [comment]
> > Navigation bar is used in ViMusic mode left and right position.
> 
> Then add to description, example:
> _"Statistic in ViMusic navigation bar"_

Okay
