### ISSUE TITLE
Ri music suggestion 

### ISSUE THREAD

**Issue by dimplelove09** [fast4x/RiMusic#1614]
### Description

You should add some features on the app it was not on your app
![Screenshot_20240423_102725](https://github.com/fast4x/RiMusic/assets/163330024/5d4dc5f4-a0e3-4773-9589-93dba543e18b)

### Suggested Solution

You should add short by in downloaded song  in library and download song stored there

**Comment by fast4x** [comment]
i don't understand, please explain better.

**Comment by fast4x** [comment]
Oh ok, I'm sorry, just implemented in 0.6.32

**Comment by dAtA-TRoN** [comment]
> > i don't understand, please explain better.
> 
> Only thing I can guess is he's asking for sorting on `Downloaded` playlist as well.

Lol, I could never have understood that 😀...
