### ISSUE TITLE
[Feature]: Remove unnecessary search buttons

### ISSUE THREAD

**Issue by kacperwyczawski** [fast4x/RiMusic#1616]
### Description

This search button seems to be useless, since search interface is already open:

![IMG_20240423_111733](https://github.com/fast4x/RiMusic/assets/97523625/5310c0a5-9065-4116-9388-bd2ceed5dd75)

And this one doesn't do anything:

![IMG_20240423_112008](https://github.com/fast4x/RiMusic/assets/97523625/47508a5b-a9eb-4314-904d-bd4bfa020104)

### Suggested Solution

I think that those buttons can be safely removed

### Alternatives

Alternatively, *RiMusic* logo could be hidden when searching. Then upper 🔍 button could be replaced by ✖️ button and the *RiMusic* could be replaced by search box

Something like this:

```
◀️ ( search text... ) ✖️ 🍔
 ▲                    ▲  ▲     
 │                    │  │     
 │                    │  └──── menu button (like before)
 │                    │        
 │                    └─────── clear button (instead of search button)
 │                      
 └──────────────────────────── back button (like before)
```

### Additional Context

And BTW, I really like new v0.6.31 top bar. Thanks for your hard work, guys.

**Comment by fast4x** [comment]
Improved, the search icon in the search field is just a form. In the top bar you have the back button to go back and the search icon is disabled if you are in the search mask.

Available from version 0.6.32

**Comment by sayyid5416** [comment]
There is also `point 1` in #1578

**Comment by kacperwyczawski** [comment]
Thanks!
