### ISSUE TITLE
[Feature]: Add toasts when holding buttons

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1617]
### Description

RiMusic has many options with many buttons. I don't know what half or them do (I know their functions are outlined in the wiki, but that's besides the fact).

I imagine I'm not the only one that thinks that this should be remedied.

### Suggested Solution

In many android apps, when a button is held (long pressed), a toast (a small message in the bottom of the screen that pops up in a bubble and contains some text) appears, explaining the button's function.

I believe that such a feature is greatly required in RiMusic, which has many buttons.

Toasts should be on the button present in all of the navigation bar pages (such as buttons present in the artists page, albums page, library page etc.) and also in artist pages.

When any button is held in the app, a small message should pop up in the bottom that shows the name of the feature.
![Screenshot_20240423-200409](https://github.com/fast4x/RiMusic/assets/90613992/ef492143-2613-4006-8aa1-ba3d0d97bfed)
![Screenshot_20240423-200452](https://github.com/fast4x/RiMusic/assets/90613992/f4975bda-2313-4015-b84e-0697de1b4fb4)
![Screenshot_20240423-200458_1](https://github.com/fast4x/RiMusic/assets/90613992/17928ef9-520c-4c58-9b3d-cef0228682a1)

**Comment by dAtA-TRoN** [comment]
Ah, a case of déjà vu! While I don't have a specific thread number handy, I do recall that the request for tooltips has popped up quite a few times. It seems to be quite the sought-after feature!

**Comment by privacyfreak84** [comment]
> It seems to be quite the sought-after feature!

I've been wanting it for months

**Comment by dAtA-TRoN** [comment]
> I've been wanting it for months

Well, that's just how it goes when an app is developed by just one person (though he accomplishes more than some larger teams do 🤔).

**Comment by dAtA-TRoN** [comment]
Haha, yeah, I totally get what you mean. I even dropped him a line once, suggesting a feature freeze since he's got so many ideas sitting in the backlog. Well, no response from him. Guess that tells us something, right? 

![proxy-image.png](https://github.com/fast4x/RiMusic/assets/71184627/6f70fdaf-d712-4e1b-8ca0-1cd8c8886250)

**Seems like he's up for the challenge!**

**Comment by fast4x** [comment]
![giphy (5).gif](https://github.com/fast4x/RiMusic/assets/1484476/ea27114f-535d-4364-abde-85cb0cc8b225)

My name is Fast ...... Fast4x... 😂😂

Don’t worry, I’m not overloaded, but I’m happy to program with you, you are fantastic.❤️❤️❤️

**Comment by dAtA-TRoN** [comment]
> ![giphy (5).gif](https://github.com/fast4x/RiMusic/assets/1484476/ea27114f-535d-4364-abde-85cb0cc8b225)
> 
> My name is Fast ...... Fast4x... 😂😂
> 
> Don’t worry, I’m not overloaded, but I’m happy to program with you, you are fantastic.❤️❤️❤️

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/028f3998-e391-4548-a37b-c286c0960c19)

**Comment by privacyfreak84** [comment]
Also, toasts should be on the button present in all of the navigation bar pages (such as buttons present in the artists page, albums page, library page etc.) and also in artist pages

**Comment by fast4x** [comment]
should be over all

**Comment by dAtA-TRoN** [comment]
> should be over all

Proposal: tooltips on/off 😏!?

**Comment by fast4x** [comment]
why?

**Comment by dAtA-TRoN** [comment]
> why?

You know when you hit that moment where you're like, "Yep, seen that icon a million times"? Those tooltips popping up out of the blue? Kinda unnecessary, right? I mean, I get it, some people might not understand, but personally, turning off help functions when they're no longer needed gives me a warm fuzzy feeling. It'd be nice if I could just flick a switch and say goodbye to those tooltips, you know? Just a thought!

**Comment by dAtA-TRoN** [comment]
> Can't relate. Not as though I'll always tap and hold each button/icon. (If one click on the buttons/icons will make the tooltips pop-up then that's another thing.)

Well, I often catch myself getting lost in the music, just tapping and holding everything in the app, you know, to play around with those delightful background effects. They're quite irresistible, aren't they 😅?

**Comment by dAtA-TRoN** [comment]
> 
> > Well, I often catch myself getting lost in the music, just tapping and holding everything in the app, you know, to play around with those delightful background effects. They're quite irresistible, aren't they 😅?
> 
> Again can't relate. 💀
> I don't use `visualizer` feature nor do I use those fancy `timelines`. I even kept background progress bar disabled. I use very few features. But I do go through pages time to time. Mostly checking different artists. 
> 
> And from these many features I use very few of them.

And what genres do you like to listen to?

**Comment by dAtA-TRoN** [comment]
> Pop and rock ig…I like both almost equally. I can't decide which one I like more. 

Cool, I also really like pop. Here, I'll leave you with my favorites playlist. Maybe you'll like some of it 🤷🏻‍♂️:

[dAtA-,TRoN's Favourite s](https://ultra-tron.DiskStation.me/drive/d/s/yCXmQAThJ8lCCvE4Kcrog8opLbbZ6Xbu/yR065U52BVJJEDE4KX3Js5kYWEX1vKC7-D7YgwL9VTws)

**Comment by fast4x** [comment]
I state that I am implementing a message bar. Unlike the current message that occasionally comes out, the bar is prettier, it will have an icon and display different types of messages. Danger, warning, information, help. It makes no sense to turn off the message because only in the case of help, for example on the meaning of the icon, will be displayed only by holding down the button.

For everything else, it will only appear when you need to communicate something, such as saved playlists or similar messages in the various sections of the app.

**Comment by dAtA-TRoN** [comment]
> New things interests me anyway.

And that's why I shared the playlist with you because you mentioned you were up for something new 😁.

**Comment by fast4x** [comment]
> > New things interests me anyway.
> 
> And that's why I shared the playlist with you because you mentioned you were up for something new 😁.

I import it and listening while developing! 😜

**Comment by dAtA-TRoN** [comment]
> I state that I am implementing a message bar. Unlike the current message that occasionally comes out, the bar is prettier, it will have an icon and display different types of messages. Danger, warning, information, help. It makes no sense to turn off the message because only in the case of help, for example on the meaning of the icon, will be displayed only by holding down the button.
> 
> For everything else, it will only appear when you need to communicate something, such as saved playlists or similar messages in the various sections of the app.
> 
> Will be pretty.

I find that completely reasonable, Mr. fast4x 👍🏼!

**Comment by fast4x** [comment]
> > New things interests me anyway.
> 
> And that's why I shared the playlist with you because you mentioned you were up for something new 😁.

It’s cool to share RiMusic playlists.

**Comment by dAtA-TRoN** [comment]
> I import it and listening while developing!

![proxy-image.jpg](https://github.com/fast4x/RiMusic/assets/71184627/bc236ea6-da09-4288-ad37-d3f3ed3cb3ae)

**Comment by fast4x** [comment]
Yes it's Great!
![Screenshot_2024-04-24-20-19-51-305_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/4667f56d-2479-4a8f-80fc-a7a762825148)

**Comment by dAtA-TRoN** [comment]
> Yes it's Great!\n

Hahaha I just saw now that you already got it 🤣🤣🤣."

**Comment by dAtA-TRoN** [comment]
> Yes it's Great!
> ![Screenshot_2024-04-24-20-19-51-305_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/4667f56d-2479-4a8f-80fc-a7a762825148)
> 
> 

I just saw now that you already got it 🤣🤣🤣.

**Comment by sayyid5416** [comment]
@dAtA-TRoN nice playlist 👌👌

Btw what category this song is: https://music.youtube.com/watch?v=odrhc32fiLo

**Comment by dAtA-TRoN** [comment]
> @dAtA-TRoN nice playlist 👌👌
> 
> Btw what category this song is: https://music.youtube.com/watch?v=odrhc32fiLo

Thank you! 😊 The track you sent me isn't on my playlist. Could you kindly provide the title and artist's name?

**Comment by sayyid5416** [comment]
> > @dAtA-TRoN nice playlist 👌👌
> > Btw what category this song is: https://music.youtube.com/watch?v=odrhc32fiLo
> 
> @sayyid5416 Thank you 😊! But the track you sent me isn't on my playlist. Could you kindly provide the title and artist's name?
> 
> ![Screenshot_2024-04-24-21-47-43-56_54f92cd6866f5233ab0db4392b806878.jpg](https://private-user-images.githubusercontent.com/71184627/325361465-c5131889-2b06-44c9-8847-60f32a3146f8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5OTMwMDQsIm5iZiI6MTcxMzk5MjcwNCwicGF0aCI6Ii83MTE4NDYyNy8zMjUzNjE0NjUtYzUxMzE4ODktMmIwNi00NGM5LTg4NDctNjBmMzJhMzE0NmY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDIxMDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyOWJlY2UwZGE5NGZkZGMzYjU3ZmRjYzU5ZTEzMGY5ZGRjMWQ3ZmJmZTM1NDlmYmJiNTFlNWI5MDY4NWM1OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1R8cKJMPaxFkkzjppQJrzDgyMBCWkUuDX97yi-GTcds)
> 
> Edit: Was it actually about a song from my playlist, or were you just seeking information about one of your own songs? If it's the latter, I'm afraid I don't have any expertise in that genre of music, apologies.

It was latter 😅

**Comment by aneesh1122** [comment]
I'm late to the party but a FAQ section of icons might be a better idea.

Long press can be used for other important purposes.

**Comment by fast4x** [comment]
In the faq there is an icon section, if you want you can update it.

The long press on the icon cannot have a function other than to indicate to the user what it is for.

Instead it makes sense if used in an object that is a song, an album, an artist and in the future there will be.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.32

**Comment by privacyfreak84** [comment]
Truly living up to your name. Thank you!
