### ISSUE TITLE
Quick picks and search not working 

### ISSUE THREAD

**Issue by Superstrikerz** [fast4x/RiMusic#1618]
### Steps to reproduce the bug

open Ri music 

### Expected behavior

it should show songs and searched song should appear

### Actual behavior

error has occured

### Screenshots/Screen recordings

![Screenshot_2024-04-23-22-53-53-18_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/164223399/bfdd73ec-2f75-4d6f-91fb-964d26d98909)

### RiMusic version

latest

### Android version

Android (

### Additional information

solve this

**Comment by dAtA-TRoN** [comment]
Dev knows it already and he's working on an entirely new quick pick tab/page/feature whatever...

**Comment by Superstrikerz** [comment]
sure
