### ISSUE TITLE
[Feature]: Album > Long press > open Menu

### ISSUE THREAD

**Issue by martkol** [fast4x/RiMusic#1619]
### Possibility to quickly add an album to the queue

Long press on an album in the list of albums opens the same menu as using the "three dots button" when the album is open.

### Suggested Solution

![ResizedImage_2024-04-23_21-35-37_8342](https://github.com/fast4x/RiMusic/assets/55714786/d9bd1c04-f8e1-41f5-bcd0-9a8d5a1c5adf)
_[Click on the three dots]_

![ResizedImage_2024-04-23_21-36-53_2059](https://github.com/fast4x/RiMusic/assets/55714786/c5b758dd-43c3-4595-ad1e-1609f9d8304b)
_[Long press on album]_

![Screenshot_20240423_200325_1](https://github.com/fast4x/RiMusic/assets/55714786/903fa2e0-d753-4b9f-bd9b-55bae033e1d9)
_[open the same menu]_

**Comment by sayyid5416** [comment]
+1.

- Also for `Artists` & `Playlists`

**Comment by fast4x** [comment]
> +1.
> 
> * Also for `Artists` & `Playlists`

Artists not have a menu like album or playlist

**Comment by fast4x** [comment]
Implemented menu with long press in albums, available from version 0.6.32

**Comment by sayyid5416** [comment]
> > +1.
> > 
> > * Also for `Artists` & `Playlists`
> 
> Artists not have a menu like album or playlist

Oh yeah, you are right 😁

Then any other places which have these 3 dots menu like playlists including special playlists like cached, downloaded

**Comment by martkol** [comment]
@fast4x @sayyid5416 
thank you.

Long press works well, except when you open an artist's page and switch to the albums, nothing happens when you long press on an album.

**Comment by fast4x** [comment]
> @fast4x @sayyid5416 
> thank you.
> 
> Long press works well, except when you open an artist's page and switch to the albums, nothing happens when you long press on an album.

Long press is available in home library... 

What can the context menu in an artist’s album list do?

**Comment by sayyid5416** [comment]
I think long press should work on all items which have context menu.

**Comment by martkol** [comment]
Let me give you an example. My son loves Paw Patrol radio plays. There are hundreds of episodes, which are displayed as albums. To add them to the playlist, you always have to open the album to add it to the playlist. The problem here is that if you then go back, you are not at the previous position. So it would be easier to display the "three dots" menu with a long press.
https://github.com/fast4x/RiMusic/assets/55714786/a082e0a1-2bdc-4744-afb6-4bdc454eaf2a

**Comment by fast4x** [comment]
I understand, also i'm a dad. 😊

**Comment by NikunjKhangwal** [comment]
> The problem here is that if you then go back, you are not at the previous position.

I was about to make a issue about it. I think this could be fixed too. The app always returns to artist's overview page.

**Comment by fast4x** [comment]
Added horizontal swipe in albums in search results page, bookmark and add in queue.
Available from version 0.6.47
@martkol now you can bookmark or add in queue directly from search result page for your son :)
