### ISSUE TITLE
Same song is looping (Playlist and Start radio)

### ISSUE THREAD

**Issue by delit** [fast4x/RiMusic#1621]
### Steps to reproduce the bug

I have this issue for a long time. 

Everytime I shuffle a playlist or start radio, the first song play just fine but then it loops and don't change song. If I hit next song it will play a different track, but now this song will be on repeat. 

### Expected behavior

Next song should play automatically. 

### Actual behavior

Song is on repeat until manuelly press next song. 

### RiMusic version

0.6.31

### Android version

Android 14

### Additional information

Pixel 8 Pro

**Comment by zaovb** [comment]
I am experiencing exactly the same bug.
