### ISSUE TITLE
Small, barely noticeable errors, xd

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1625]
### Steps to reproduce the bug

It happens when one goes to certain parts of the player. More specifically, between the queue and the artist's wiki.

### Expected behavior

They shouldn't be visible, but it happens, xd

### Actual behavior

Just small errors, but worth reporting, haha.

Plus, they're only visible if you have a keen eye.

Except for the queue one, as it obstructs certain buttons.

### Screenshots/Screen recordings

![Screenshot_2024-04-24-16-39-45-783_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/960d2239-d096-4fb5-a212-be2150eeaed7)
![Screenshot_2024-04-24-14-37-32-152_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/32c1a29e-53c1-42eb-9c1f-99ebbf663b71)

### RiMusic version

0.6.31

### Android version

Android 13

**Comment by fast4x** [comment]
Thanks for reporting it.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.32
