### ISSUE TITLE
music player crashes occasionally when switching between Mobile data and WiFi

### ISSUE THREAD

**Issue by 5wHN28Dg** [fast4x/RiMusic#1627]
### Steps to reproduce the bug

Switch between Mobile data and WiFi while listening to songs

### Expected behavior

The music player should not crash, it should continue playing and if it needs internet it should just pause the song and try to reconnect without crashing and if necessary there should be also a button for the user to tap to 'try again' to reconnect but I believe this whole thing should be fully automatic with no need for user intervention at all (most of the time), maybe you can add max number of automatic reconnection attempts after which user intervention maybe needed 'try again button' as it can really get in the way when listening to music while doing other things.

### Actual behavior

The music player crashes and closes and I have to click on/play the song again 

### Screenshots/Screen recordings

This is really starting to get on my nerves, it just crashed and as you can see the music player closed (it should be at the bottom of the screen but nope because it crashed again🫠)
![Screenshot_20240425_120934](https://github.com/fast4x/RiMusic/assets/109148083/e99dafba-7767-43b7-91ba-640fc1caceb8)

### RiMusic version

0.6.31

### Android version

Android 14

### Additional information

It would be quite annoying to capture it when it happens as sometimes it happens and sometimes it doesn't and as a result I try to be cautious and careful when switching between Mobile data and WiFi (I pause the song then turn off WiFi then turn on Mobile data then resume the song, this works most of the time but it is quite annoying to do this all the time) I shouldn't have to do this 99% of the time

**Comment by fast4x** [comment]
Interesting, I'll check it

**Comment by 5wHN28Dg** [comment]
Update it also crashes when the internet connection is unstable or weak, this just happened on mobile data as the signal was switching between 4G and 3G, this is really annoying because I started a radio but now the whole playlist is gone and it just happened again after switching back to WiFi
