### ISSUE TITLE
App crashes in local files section

### ISSUE THREAD

**Issue by Davutha** [fast4x/RiMusic#1628]
### Steps to reproduce the bug

Go to the local files section
Scroll down through the songs

### Expected behavior

Nothing should happen

### Actual behavior

The app crashes, even when it's not scrolling the app just crashes in the local files

### RiMusic version

0.6.31

### Android version

Android 13 (MIUI 14)

**Comment by Davutha** [comment]
there's no log files created by the app or duplicated/corrupted songs, maybe I should check if there's a log but I can't find it

**Comment by fast4x** [comment]
Fixed available from version 0.6.49
