### ISSUE TITLE
songs automatically changing itself while hearing

### ISSUE THREAD

**Issue by Superstrikerz** [fast4x/RiMusic#1629]
### Steps to reproduce the bug

hear some to 5 to 10 songs suddenly itself go for the next song without completing the previous one

### Expected behavior

full song need to be played

### Actual behavior

songs are changing itself without completing the previous one 

### RiMusic version

latest

### Android version

Android 9

### Additional information

this is frequenlty happening in all versions

**Comment by fast4x** [comment]
This occurs if a song go to error...
