### ISSUE TITLE
New albums from following artists.

### ISSUE THREAD

**Issue by Indelibleimprint** [fast4x/RiMusic#1630]
### Steps to reproduce the bug

1. Open up quick picks
2. Look for new releases
3. Only top songs played, bottom empty space where I figure they should be..☺️

### Expected behavior

I may be in the wrong spot, but I'm pretty sure when I suggested this feature you told me to look here as it was already implemented. I believe you 100% but it seems to not be working for me. 

### Actual behavior

![Screenshot_20240425-120530](https://github.com/fast4x/RiMusic/assets/116973282/a62c1d8f-c11d-49c6-b58f-6a4a4a8f093c)

### Screenshots/Screen recordings

![Screenshot_20240425-121325](https://github.com/fast4x/RiMusic/assets/116973282/fb737107-e551-41df-87b6-391ce5757bad)

### RiMusic version

v0.6.31

### Android version

Android 14

**Comment by fast4x** [comment]
In 0.6.31 version there are a limited quick pics page, wait for new release, thanks. 😊

**Comment by dAtA-TRoN** [comment]
> In 0.6.31 version there are a limited quick pics page, wait for new release, thanks. 😊

![proxy-image(3).gif](https://github.com/fast4x/RiMusic/assets/71184627/a1767565-e443-444a-ab2d-ef4627cf4629)
