### ISSUE TITLE
Album release year not left justified

### ISSUE THREAD

**Issue by Juggalage** [fast4x/RiMusic#1631]
### Steps to reproduce the bug

Go to any artist and click on albums or singles

### Expected behavior

Release year to be left justified with album title

### Actual behavior

Release year is centered on album title

### Screenshots/Screen recordings

![Screenshot_20240425-142200](https://github.com/fast4x/RiMusic/assets/32726906/bf5ba0d5-42a3-4eeb-9cce-0f9926fb5710)

### RiMusic version

V0.6.31

### Android version

Android 14

### Additional information

Not sure if this is deliberate or not, just an observation I made.

**Comment by fast4x** [comment]
Just fixed in new release 0.6.32
