### ISSUE TITLE
How to activate floating play button in RiMusic UI?

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1643]
Title

**Comment by fast4x** [comment]
Floating play button not exists...

**Comment by privacyfreak84** [comment]
So what was #1582 all about?

**Comment by fast4x** [comment]
search button is floating, long press move and it stay in new position...

**Comment by privacyfreak84** [comment]
But only on ViMusic mode. The issue, which seems to have been 'implemented', requests a floating search button option for the RiMusic UI

**Comment by fast4x** [comment]
like before floating icon is only in ViMusic mode
