### ISSUE TITLE
Increase speed of animations throughout the app

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1644]
With the latest update (0.6.32), all the animations in the app have become much slower. The snappiness that one once enjoyed in this app is now gone.

I suggest increasing the speed of all animations back to what they were in prior versions. This will restore the snappiness of the app and will improve it's smoothness

**Comment by fast4x** [comment]
is not slower but different, prior was slide and now is fade. I can add a setting to select what you prefer.

**Comment by sayyid5416** [comment]
Fade does look slower at the same speed though

**Comment by fast4x** [comment]
Ok I'll increase speed

**Comment by fast4x** [comment]
Increased speed, available from version 0.6.33

**Comment by privacyfreak84** [comment]
Thanks!
