### ISSUE TITLE
[Feature]: Decrease size of library, artists and album pages components

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1646]
### Description

Prior to version 0.6.32, the components of the artists, albums and library tabs in the navigation bar were of perfect size (in my opinion). Less scrolling was required to view all the information, and the design wasn't so aggressive.

With the latest update, however, all the main components in the aforementioned sections have received an increase in size. Personally, I an not a fan of this change.
More effort is required to see everything contained in these sections.

In previous versions, the way in which the albums, artists and library tabs were designed were designed were perfect. I don't think anyone had any problem with them. Hence, I don't see the point of this change.
![Screenshot_20240426-230947](https://github.com/fast4x/RiMusic/assets/90613992/39a6b3d6-ee3c-42a5-a6b7-f392bec9320e)

### Suggested Solution

Revert the latest changes made to these sections

**Comment by jaki444** [comment]
pls no i like the big size. Make the decrease size of library as an option in the settings

**Comment by privacyfreak84** [comment]
An option also works. Perhaps there can be a 'UI Scale' option that decides all this

**Comment by fast4x** [comment]
ok I'll add a setting..

**Comment by sayyid5416** [comment]
Yeah, +1 for this. I also liked the earlier size - although not too much of headache

**Comment by fast4x** [comment]
Implemented custom size in library, artists and albums, available from version 0.6.33

**Comment by privacyfreak84** [comment]
❤️
