### ISSUE TITLE
Can't search for anything in song search menu

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1647]
After searching for something in the song search page and receiving results, it is impossible to change the search term to something else as the search button in greyed out and dysfunctional.

If some don't want the search button itself to be present in the song search page after searching for something, then I think that a good alternative would be to allow searching by clicking the very text/search term.

Ex: Search for 'Jonkler's Ballad'. The search term ('Jonkler's Ballad') appears below the new menu with the search button and the settings, RiMusic logo etc.
If one wants to now search for 'Man's Response', it should be possible to search for it by clicking on 'Jonkler's Ballad.'

**Comment by fast4x** [comment]
![Screenshot_2024-04-26-21-15-09-331_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/252c6694-ef4e-445c-a52f-7a461e5bd848)

**Comment by fast4x** [comment]
this show when search this terms

**Comment by fast4x** [comment]
I don't understand, search work

**Comment by privacyfreak84** [comment]
OK, hold up; sending video

**Comment by fast4x** [comment]
If You are already in the search results, the button is disabled.

**Comment by privacyfreak84** [comment]
https://github.com/fast4x/RiMusic/assets/90613992/dc2a43c0-9e98-41d3-a851-4144c0458cee

In the end, I try to click in both the song name and search button, but to no avail

**Comment by privacyfreak84** [comment]
Seems to be fixed in #1676. Closing
