### ISSUE TITLE
Search and statistics button always stays at the top

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1657]
### Steps to reproduce the bug

1. Go to settings
2. Enable options to show search and statistics in the navigation bar

### Expected behavior

Both the icons should go to the navigation bar

### Actual behavior

It stays at the top.

### RiMusic version

0.6.32

### Android version

Android 13

### Additional information

Floating search button is also missing

**Comment by fast4x** [comment]
This is only specific for ViMusic ui mode. In RiMusic mode top bar have twice
