### ISSUE TITLE
Sorting options changes when 'Show folders' is enabled

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1658]
### Steps to reproduce the bug

1. Go to Settings and disable showing folders. These are the sorting options
![Screenshot_2024-04-27-07-14-07-819_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/645f2a71-1ce0-49e4-a7da-fd08bbd2e194)
2. Now enable showing folders. These are the sorting options
![Screenshot_2024-04-27-07-15-00-994_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/1798e160-f7cd-4960-baf1-efcec9269521)

### Expected behavior

Both the options should have the same sorting options

### Actual behavior

Different sorting options depending on enabling or disabling showing folders

### RiMusic version

0.6.32

### Android version

Android 13

### Additional information

Please have these sorting options
1. Title
2. Artist
3. Album
4. Date added
5. Duration

In 'on device's everytime

**Comment by fast4x** [comment]
I'm sorry but isn't possible.

**Comment by aneesh1122** [comment]
You've labelled it as completed. Have you implemented it? 😅

**Comment by fast4x** [comment]
> You've labelled it as completed. Have you implemented it? 😅 @fast4x 

Oh my God! Sorry

**Comment by fast4x** [comment]
Ahhh it's ok, i can't to do anything because in folder isn't available type of order requested.
