### ISSUE TITLE
'Go to playlist' icon available only from music player

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1660]
### Steps to reproduce the bug

1. Go to search and search any song
2. Long press any song
3. Go to 'Add to playlist'

### Expected behavior

'go to playlist' icon should appear next to the playlist

### Actual behavior

Icon is missing

https://github.com/fast4x/RiMusic/assets/45353488/283a7b3f-6d79-4da1-b5e1-f736bea8d9ad

### RiMusic version

0.6.32

### Android version

Android 13

### Additional information

Icon only appears when I'm playing a song in the music player and choose 'add to playlist'

https://github.com/fast4x/RiMusic/assets/45353488/29aa0f11-b5cd-4bfd-a0d3-1f50a5640623

**Comment by aneesh1122** [comment]
> Also that icon is missing when using `Add to playlist` from the `three dots menu`.

It works when you are adding a playlist using the `three dots menu`

You're right that it doesn't work while adding an album to a playlist using  `three dots menu`

**Comment by fast4x** [comment]
Fixed, available from version 0.6.33
