### ISSUE TITLE
'Already in the playlist' checkmark missing when adding songs from the player

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1661]
### Steps to reproduce the bug

https://github.com/fast4x/RiMusic/assets/45353488/5a8a3f55-be8f-49f7-9a69-930820a37df4

### Expected behavior

Checkmark should appear

### Actual behavior

Checkmark is missing

### RiMusic version

0.6.32

### Android version

Android 13

### Additional information

Checkmark appears while adding songs from the list

https://github.com/fast4x/RiMusic/assets/45353488/6a4c4922-a123-490d-a2d0-284fae251a77

**Comment by aneesh1122** [comment]
> You could've combined these two reports…but ig do it your way…how you feel better

Did that plenty of times before. What happens is one thing gets solved and the another one is forgotten. That's why I made different issues.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.33
