### ISSUE TITLE
[Feature]: Removal of bottom bar from playlists

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1662]
### Description

This doesn't have any purpose
![IMG_20240427_090428](https://github.com/fast4x/RiMusic/assets/45353488/47deff55-fe90-4185-86a5-6e1e656c2765)

### Suggested Solution

Please remove that bottom bar

**Comment by fast4x** [comment]
"bottom bar" is a section menu...

**Comment by aneesh1122** [comment]
> "bottom bar" is a section menu...

Sorry I didn't know what it is called.

Please consider removing it if it's not very important to have in the album and playlists page.

**Comment by sayyid5416** [comment]
I think this "bottom bar" should be hidden if it contains only one item which is currently opened. For example, it shows only playlist button when playlist is already opened - It should be hidden in this case.
