### ISSUE TITLE
[Feature]: Please remove bottom bar from the album page

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1663]
### Description

Please remove this
![0](https://github.com/fast4x/RiMusic/assets/45353488/d7ec2401-fd93-4353-a69d-e41cd0d4d233)

### Suggested Solution

![2](https://github.com/fast4x/RiMusic/assets/45353488/94477da8-ae2f-4785-95c5-7d1ffb57df3d)
or you can place this icon anywhere else you like

**Comment by fast4x** [comment]
"bottom bar" is a section menu...

**Comment by aneesh1122** [comment]
> "bottom bar" is a section menu...

Well, I just thought that removing it from the  album and playlists(especially) will make your app look more clean and have more screen space.

That section menu has no purpose inside a playlist and the only purpose it has inside an album can be accomplished in a cleaner way like I suggested.

The 'section menu + mini player' looks so big together.

Please think about it.
