### ISSUE TITLE
Need the ability to download audio tracks in mp3 format

### ISSUE THREAD

**Issue by qa117** [fast4x/RiMusic#1665]
### Description

We need the ability to download audio tracks not only to the cache, but also in mp3 format

### Suggested Solution

We need the ability to download audio tracks not only to the cache, but also in mp3 format

### Alternatives

this function has been successfully implemented in vk mp3 mod https://t.me/vkmp3mod

**Comment by dAtA-TRoN** [comment]
> We need the ability to download audio tracks not only to the cache, but also in mp3 format

![proxy-image(2).gif](https://github.com/fast4x/RiMusic/assets/71184627/1394fc2b-7abf-4025-ac53-80e4bbe83599)

**Comment by fast4x** [comment]
Isn't planned, i'm sorry.

**Comment by dAtA-TRoN** [comment]
Well, I love sharing my music straight from the RiMusic app, like with the 'NewPipe' app, if you catch my drift 🤫😏...
