### ISSUE TITLE
we need to know the bitrate of the audio  we are listening to

### ISSUE THREAD

**Issue by qa117** [fast4x/RiMusic#1666]
### Description

Bitrate, for example 320, 128, 96 kb/s

### Suggested Solution

It might look like this:

**Comment by qa117** [comment]
Oh! Thanks! It's working! I didn't know about it

27 апреля 2024 г. 06:14:28 UTC, AnyoneMouse ***@***.***> пишет:

**Comment by triggerfx** [comment]
Not working, for me a bottom menu opens with two controls and sliders, I don't know What they do
