### ISSUE TITLE
need the ability to add audio sources

### ISSUE THREAD

**Issue by qa117** [fast4x/RiMusic#1667]
### Description

Now the only source in the application is YouTube. I ask you to add at least one more source vk.com in this source a huge music database is provided for free. In addition, it is updated with new tracks every second.

### Suggested Solution

Now the only source in the application is YouTube. I ask you to add at least one more source vk.com in this source a huge music database is provided for free. In addition, it is updated with new tracks every second.

### Alternatives

Vk.com

**Comment by fast4x** [comment]
Confirm
