### ISSUE TITLE
Implement the modern player layout from Vitune

### ISSUE THREAD

**Issue by Toiletmason** [fast4x/RiMusic#1668]
### Description

It's a nice layout. 

### Suggested Solution

The dev is a working on both projects so it should be simple.

**Comment by fast4x** [comment]
Can you explain better why is modern?

**Comment by Toiletmason** [comment]
I don't think it's better. I like it more though.

**Comment by JeePopuwu** [comment]
> No creo que sea mejor. Aunque me gusta más. ![Captura de pantalla_20240427_114653.jpg](https://private-user-images.githubusercontent.com/23698116/326193317-cbc8cb0c-5ee4-4543-bc5d-8dfda07bd311.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNTc3MDQsIm5iZiI6MTcxNDI1NzQwNCwicGF0aCI6Ii8yMzY5ODExNi8zMjYxOTMzMTctY2JjOGNiMGMtNWVlNC00NTQzLWJjNWQtOGRmZGEwN2JkMzExLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDIyMzY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZjQ1ZTAxMDBkMWYwOGRiMjc1MTJjMzM1NjMwOTg5Nzc1ZWY2ZGNiNzNkNzNlOTVhOThkOTFhZTE2NjY0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S7VItyGwoLfjk9VLE2S0gVqpKPQC69Ps_kXva7KWo2s)

It looks WAY too minimalist, even for minimalist people. The current version is better.
