### ISSUE TITLE
Man, this arrow...

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1669]
### Check a look:
(better with audio 🔊😏)

https://github.com/fast4x/RiMusic/assets/71184627/4d6a8188-b624-405e-b125-bf92aed6a22c

### RiMusic version

0.6.32

### Android version

Android 13

**Comment by fast4x** [comment]
![giphy (7).gif](https://github.com/fast4x/RiMusic/assets/1484476/57c25aad-b6f7-440b-a481-d3a8ec9d64aa)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.33
