### ISSUE TITLE
Not all settings at the bottom readable

### ISSUE THREAD

**Issue by Simon-Sonnleitner** [fast4x/RiMusic#1670]
### Steps to reproduce the bug

1. Go to settings
2. Tab on miscellaneous 
3. Scroll down all the way

### Expected behavior

Invincible Service should be readable

### Actual behavior

It is covered by the music status bar

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/113847208/2aff2def-768d-4bb9-8e54-400f8f1589ab

### RiMusic version

0.6.32

### Android version

Android 14, One UI 6.1

### Additional information

Some contributors in the about sections are also covered

**Comment by fast4x** [comment]
ohhh ok ok

**Comment by fast4x** [comment]
Fixed, available from version 0.6.33
