### ISSUE TITLE
"No lyrics found" even when the lyrics are available in lrclib.net

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1675]
### Steps to reproduce the bug

1. Open [this](https://music.youtube.com/watch?v=PDh4wS1ZnqI) in RiMusic
2. Enable lyrics (shows that the lyrics are not available)
3. Select `Pick from Lrclib.net`
4. App says "No lyrics found"

### Expected behavior

Lyrics should appear. The lyrics are available in lrclib.net

Check it yourself
[Here](https://lrclib.net/search/Thumkeshwari)

### Actual behavior

Lyrics doesn't appear

### RiMusic version

0.6.32

### Android version

Android 13

### Additional information

Lyrics appear easily in another music app I use which also takes lyrics from lrclib

**Comment by AquamarineDreams** [comment]
I had this issue before #1433  and I'm having the same issue again. I have no idea what causes this because it doesn't seem to affect other users.

**Comment by aneesh1122** [comment]
Didn't you say it was working for you back then? 

btw could you please try my link and see if lyrics are showing or not.

**Comment by aneesh1122** [comment]
> I had this issue before #1433  and I'm having the same issue again. I have no idea what causes this because it doesn't seem to affect other users.

Didn't you say it was working for you back then? 

btw could you please try my link and see if lyrics are showing or not.

**Comment by AquamarineDreams** [comment]
Yes, I said it. For some reason it started working again after a few days, but today it stopped working again.

Sorry bro, but neither YouTube music or Rimusic found your song. Are you sure you typed the link correctly?

**Comment by AquamarineDreams** [comment]
Found the music. My client also couldn't find the synced lyrics.

**Comment by fast4x** [comment]
Reproduced, I'll fix it, thanks.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.33

**Comment by aneesh1122** [comment]
Hey @fast4x the lyrics are not appearing even in the latest version

https://github.com/fast4x/RiMusic/assets/45353488/9ba91148-d32a-4c56-bd6c-49aebf996880

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/ef0042c7-d358-495b-832c-d28124195737

**Comment by fast4x** [comment]
if your lyrics is present in LrcLib it will be found
https://github.com/fast4x/RiMusic/assets/1484476/8fa2f40f-699f-447f-b49b-b84f91ba36a2

**Comment by aneesh1122** [comment]
> https://github.com/fast4x/RiMusic/assets/1484476/ef0042c7-d358-495b-832c-d28124195737
> 
> 

Your spelling is wrong 😅

See this
https://github.com/fast4x/RiMusic/assets/45353488/a1976b83-b4cc-4bd0-a571-74e56924d7dc

**Comment by fast4x** [comment]
oh oh ok 😂😂

**Comment by AquamarineDreams** [comment]
@aneesh1122 

Found your problem. The music name needs to match the one in lrclib.net.

https://github.com/fast4x/RiMusic/assets/140275860/eb4d05f2-86bf-4df6-abe1-4b3caff075d5

Hope that helps

**Comment by aneesh1122** [comment]
> @aneesh1122 
> 
> Found your problem. The music name needs to match the one in lrclib.net.
> 
> https://github.com/fast4x/RiMusic/assets/140275860/eb4d05f2-86bf-4df6-abe1-4b3caff075d5
> 
> Hope that helps

The title actually has a result in lrclib. 
https://github.com/fast4x/RiMusic/assets/45353488/f5f22bd1-0eba-4060-9297-1ff5d8bb4b2d


I think it takes the combination of 'Title' + 'artists' and matches the song. This works most of the times but sometimes it doesn't.

Anyways, this problem will be solved when @fast4x implements that searching box so there's nothing to worry about.

**Comment by aneesh1122** [comment]
> oh oh ok 😂😂

you can solve this lyrics problem by doing this

1) search with 'title' 'artists'
2) if above doesn't give any results, search only 'title'

**Comment by Hyperjoker2511** [comment]
It didn't showing lyrics in lrclib
It says something error occured 
Im using latest version 0.6.67
