### ISSUE TITLE
Search icon is greyed out and not working

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1676]
### Steps to reproduce the bug

https://github.com/fast4x/RiMusic/assets/45353488/502610e5-f771-40c4-981d-5f945a5a44d8

### Expected behavior

Search icon should work

### Actual behavior

Search icon is not working

### RiMusic version

0.6.32

### Android version

Android 13

**Comment by aneesh1122** [comment]
#1647

**Comment by fast4x** [comment]
You are already in the search results, the button is disabled.

**Comment by aneesh1122** [comment]
> You are already in the search results, the button is disabled.

I haven't seen that happening in any of the music players app I've used. Search button works even after the search results in case I want to search again.

The workaround is to go back and search again.

If you don't think it's necessary please close the issue.

**Comment by fast4x** [comment]
ok I enable it

**Comment by aneesh1122** [comment]
> ok I enable it

thanks man

**Comment by faustaahmad** [comment]
Go back after search result
A bit wierd, still dont know why not implement the common search UI & UX like other apps does

**Comment by fast4x** [comment]
Enabled, available from version 0.6.33
