### ISSUE TITLE
Animation delay is causing unwanted actions 

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1677]
### Description

When you **go from one page to another** and **before the animation changes** you **try to do something on the newer page** the action **works according to the previous page** instead of the current page. 

### Suggested Solution

I hope I'm clear enough above. I'm in a hurry currently. 💀 I'll edit this and explain better when I can if needed.

### Additional Context

Shoot…seems like I accidentally tapped on "feature request"…its a habit…

**Comment by fast4x** [comment]
In next version delay is minimal

**Comment by fast4x** [comment]
You prefer fade or slide effects from one to other page?

**Comment by fast4x** [comment]
I'll add a option in settings for select effects... slide, fade and.... 😜

**Comment by fast4x** [comment]
Look...

https://developer.android.com/develop/ui/compose/animation/composables-modifiers?hl=it

**Comment by fast4x** [comment]
Implemented, available from version 0.6.33

**Comment by fast4x** [comment]
No solution because I see them all tickets, I follow the reports that you made a few weeks ago. Your work helps me to prepare tickets for priority so thank you, you can also prepare it in a few weeks, I already have tickets in development.
