### ISSUE TITLE
[Feature]: Make Floating search the same color as Play/Pause and go to top

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1678]
### Description

A bit of nitpicking here but floating search button is too dark imo and looks very out of the place

![IMG_20240428_111706](https://github.com/fast4x/RiMusic/assets/99175083/af92e0d0-9300-4a63-8f35-fcedcd0c8ac4)

### Suggested Solution

Make it adapt the same color as play/pause and "go to top" button

![IMG_20240428_110659](https://github.com/fast4x/RiMusic/assets/99175083/58fb1913-cada-4920-a9f7-33164621551e)
![IMG_20240428_110729](https://github.com/fast4x/RiMusic/assets/99175083/162bc3b3-0213-4d3b-b2c7-9e5fc7ba6718)
![IMG_20240428_110805](https://github.com/fast4x/RiMusic/assets/99175083/e4ded162-5b5b-43ee-92d6-988998da42d9)

### Additional Context

This is a extension of #1139
While the button visibility has definitely increased from that point, i think a good balance is needed.

**Comment by fast4x** [comment]
Improved, available from version 0.6.38
