### ISSUE TITLE
List menu in albums despite choosing grid

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1679]
### Steps to reproduce the bug

Enabled grid style menu from settings and open album's menu either from library or artist page

### Expected behavior

The menu should be grid just like the rest of the app

### Actual behavior

The menu is list only in albums, rest of the app is fine.

### RiMusic version

0.6.32

### Android version

Android 12

### Additional information

This might be a problem with just ViMusic mode but I'm not sure

**Comment by fast4x** [comment]
Fixed, available from version 0.6.33
