### ISSUE TITLE
Music recommendations 

### ISSUE THREAD

**Issue by debarjun2004** [fast4x/RiMusic#1685]
### Description

Please add an option for music language selection, don't really like Punjabi songs on my feed, but getting them..... 

### Suggested Solution

And also there is a bug in the favourites section, if i search something in the favourites area and among those results if I play a song, suddenly the result disappears, please fix that, wasn't there before

**Comment by NikunjKhangwal** [comment]
Related to #1188

**Comment by fast4x** [comment]
Implemented, available from version 0.6.44
