### ISSUE TITLE
Search bug in song tab

### ISSUE THREAD

**Issue by sebbekm** [fast4x/RiMusic#1686]
### Steps to reproduce the bug

1. Search for anything in the song tab
2. Go back and click on an older search or the search bar

### Expected behavior

I should be able to click on the search field or the search history without a random song starts playing instead

### Actual behavior

When searching for a song/artist in the song tab then going back to the search window to search for another song. Click anywhere and a song from the previous search results starts playing. Kinda hard to explain, I attached a video

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/99768781/45a45185-ddb3-4c84-ba5f-99b357f8e426

### RiMusic version

0.6.32

### Android version

Android 13

**Comment by aneesh1122** [comment]
#1677

he is going to make the animations faster. I think this will solve your problem
