### ISSUE TITLE
Bug visual 

### ISSUE THREAD

**Issue by Wadle44** [fast4x/RiMusic#1687]
### Steps to reproduce the bug

Quando faço alguma alteração visual, o tema muda para o pitch black, mas o selecionado e o modo escuro 

### Expected behavior

Alterações do player entre outras coisas mudam sem afetar o tema do app

### Actual behavior

Qualquer tipo de alteração visual altera o tema do app para o pitch black

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/168355504/762e223b-5535-4311-847d-bb01dcc8f5f8

### RiMusic version

0.6.32

### Android version

Android 13

**Comment by fast4x** [comment]
Improved available from version 0.6.60

**Comment by Wadle44** [comment]
Oh, estarei no aguardo!
