### ISSUE TITLE
Change arrows look to be more modern

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1689]
### Description

Ive noticed that apps like 𝕏 (Twitter), Youtube, Discord all have these full arrows for actions like :
- Back
- Go at the top/bottom

Arrows :
![Screenshot_20240428_021339_X](https://github.com/fast4x/RiMusic/assets/104271365/b46bf85c-4dfd-49a1-bf0b-2a517a3a7129)
![Screenshot_20240428_021345_YouTube](https://github.com/fast4x/RiMusic/assets/104271365/2ea3a92e-d6b8-423a-9d9f-c8c89b4bdedc)
![Screenshot_20240428_021350](https://github.com/fast4x/RiMusic/assets/104271365/49de9d0c-461b-49ee-b87c-2d203de72f00)

### Suggested Solution

Use a similar arrow in RiMusic to make the app more modern

### Alternatives

You could alson make some buttons a circle an more tiny (like discord dose) for the go at the top of the page or and some buttons that don't have a background

Context :
![Screenshot_20240428_021350](https://github.com/fast4x/RiMusic/assets/104271365/d765608f-18be-46d1-a3e8-d123f77ec834)
![SmartSelect_20240428_220732](https://github.com/fast4x/RiMusic/assets/104271365/4bca5ca1-e700-452b-ad33-11c94c226f98)
![SmartSelect_20240428_220724](https://github.com/fast4x/RiMusic/assets/104271365/4c0e1048-3ee0-46f9-b7d7-71df9307b446)

### Additional Context

Could someone say if they think the same for the circle buttons?

**Comment by fast4x** [comment]
Why a circle icon would be modern?

**Comment by OrangeZXZ** [comment]
> Why a circle icon would be modern?

RiMusic has a blocky button for "Go at the top" witch takes a lot of space, a tiny circle that has the size of the icon is used more op popular apps and is more hidden

Also RiMusic has some buttons that don't have a background like for example the top buttons (search and burger menu, back and burger menu in the player)

But maybe doing it directly without changing other aspects can make some inconsistency in the UI

Maybe a new issue with ideas could be better for this?

**Comment by NikunjKhangwal** [comment]
I would disagree

**Comment by fast4x** [comment]
Personally I think that the background on the buttons is an "ancient" concept. I just recommend not to "copy" from other apps that should be "more modern". In my opinion the concept of modernity is very subjective.
