### ISSUE TITLE
How I wish it looked:

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1692]
### Description

https://github.com/fast4x/RiMusic/assets/159836335/0334472c-a4f5-45d0-8ae9-5123a6b032f3

### Suggested Solution

I would like Rimusic to look like this in the future when all the main arrangements have been resolved, and these ideas might seem very Spotify-esque, but this is how I would like it to look.

What things can we observe in the videos (made by your humble servant XD)

**1) Video canvas:** This idea has been on the table during the last few videos, and I think it would be a good addition, although I'm not sure how easy or difficult it would be to implement.

**2) Crossfade:** This is an idea that I always bring up in some form. Here, I provide an example of how it would look (set to 6 seconds).

**3) The hearts I proposed in Miku style:** Here, I made a small edit of how they would look. It's of low quality because I'm not very good at combining colors.

Knowing that these are somewhat whimsical ideas, feel free to discard them if you wish, but if you do consider them, I would be very grateful.

**Comment by JeePopuwu** [comment]
Another thing, the canvas could be chosen by each person during playback.

**Comment by dAtA-TRoN** [comment]
I have to say that I don't like it at all. I think it's too distracting. So especially with the lyrics.

**Comment by JeePopuwu** [comment]
> He de decir que no me gusta nada. Creo que distrae demasiado. Especialmente con las letras.

For now, as I always said, it's just an idea on paper, it can be scrapped. It could also be that YouTube Music canvas is chosen.

It could be that people choose whether we have it or not, for my part, I would like to have it.

**Comment by fast4x** [comment]
Be careful not to turn RiMusic into another existing...

**Comment by JeePopuwu** [comment]
> Tenga cuidado de no convertir RiMusic en otro existente...

If Fast says it, I accept it; I think Rimusic should also have its own identity.

**Comment by fast4x** [comment]
Implemented crossfade songs effect, available from version 0.6.34
