### ISSUE TITLE
Icon Update 

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1693]
### Description

Now the words I used to represent my ideas will be centered as updates, as if it were Minecraft XD.

Right now, I have two ideas on the table.

It's about improving the icons of the songs obtained through regular YouTube (not from the YouTube Music catalog).

And these don't have any icons unlike the others. My idea would be to give them a special icon.

Example:

![Picsart_24-04-28_22-51-12-190](https://github.com/fast4x/RiMusic/assets/159836335/12c3d0e9-c295-469e-ba9a-31f98526eba3)

![Picsart_24-04-28_22-52-04-972](https://github.com/fast4x/RiMusic/assets/159836335/a246e8af-51b2-4318-9af0-728c59325fd2)

### Suggested Solution

I think the best icon for these songs is the YouTube icon XD (simple but effective).

![8d7fc059e903774cb1dc678e9b6c3700](https://github.com/fast4x/RiMusic/assets/159836335/95dc48bb-5363-4658-a840-00bea81372c2)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.33
