### ISSUE TITLE
Color's Update

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1695]
### Description

Right now, the colors of the application are composed quite well and accurately, but certain colors are missing in the app.

![Screenshot_2024-04-28-16-13-42-504_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/6a48035e-aadd-4f2d-95ab-a858d680fd81)
![Screenshot_2024-04-28-16-27-48-516_it fast4x rimusic]
(https://github.com/fast4x/RiMusic/assets/159836335/259f642d-f5db-4f9e-affe-c174916ec7dc)
![Screenshot_2024-04-28-17-07-20-077_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/81c39f66-6010-497d-ba5f-02c9335a7a88)

For example, its color doesn't correspond to any on its cover.

"An idea that formed in my mind is that the same app (Rimusic) takes the most prominent colors from the cover."

Here are examples of the possible colors that could be taken:

![20240428_233419](https://github.com/fast4x/RiMusic/assets/159836335/727e6ee5-6744-4fbb-a76c-84cd317dd3ab)
![20240428_233656](https://github.com/fast4x/RiMusic/assets/159836335/e0201ab2-6a42-4e01-8c9c-a915d483df15)
![20240428_233907](https://github.com/fast4x/RiMusic/assets/159836335/083423d6-692d-4c37-bf11-fbc26dfc868d)

### Suggested Solution

"In the hypothetical case that the cover is entirely white or black, it could take the second base color from the image, or simply place a brighter color in the player. 
For example: 

![Screenshot_2024-04-28-17-09-54-593_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/105f45a6-9dd3-4cb1-968b-00cc924d955f)
![20240428_234042](https://github.com/fast4x/RiMusic/assets/159836335/6a8129af-4070-4fa2-a056-44ef5408d1e3)

### Alternatives

This time I have absolutely no idea how to carry this out.

The closest thing I could say is for the app to detect the colors.

How? I don't know XDDDDDDD'NT

**Comment by JeePopuwu** [comment]
This idea also came up because this way the "Miku style" of using two colors could be easier to implement.

**Comment by fast4x** [comment]
Implemented customized colors theme, available from version 0.6.34

**Comment by JeePopuwu** [comment]
> Tema de colores personalizados implementado, disponible desde la versión 0.6.34

Fast for president
