### ISSUE TITLE
RiMusic is not streaming in highest quality available

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1698]
### Steps to reproduce the bug

1. Open [https://youtu.be/2LTdkTBsQ9Y](url) in RiMusic
2. Long press to check the streaming quality
![Screenshot_2024-04-29-14-44-11-412_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/45353488/b478f619-c24a-4768-bb37-0fdfb7ee3841)

### Expected behavior

![IMG-20240429-WA0000](https://github.com/fast4x/RiMusic/assets/45353488/d2d3e6f8-de06-4c5c-8aae-ecd14670b247)
It should stream the `Itag` 774
774 is the best free available audio stream.

### Actual behavior

RiMusic streams Itag 251 which is inferior to 774.

### RiMusic version

0.6.32

### Android version

Android 13

**Comment by fast4x** [comment]
Api in audio mode have max 251

**Comment by aneesh1122** [comment]
> Api in audio mode have max 251

Okay, so that's from YouTube's side. Got it. Hope YouTube updates its api soon.
