### ISSUE TITLE
Make RiMusic available in the share menu

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#17]
### Description

Make RiMusic available in the share menu.

### Suggested Solution

This would make it easier to share from the left.

**Comment by fast4x** [comment]
Add some more details, please

**Comment by siggi1984** [comment]
![215974370-b55fcab2-f799-4c6c-b49d-e49ebf654a1b](https://github.com/fast4x/RiMusic/assets/103368536/73fadf84-68e1-4ec0-8dd9-3c76ace2aa6c)


RiMusic should be offered here in this menu.

**Comment by fast4x** [comment]
Ah ok :)

**Comment by fast4x** [comment]
What would you like to share with RiMusic from the share menu?

**Comment by siggi1984** [comment]
YouTube-Music-Links, YouTube-Playlist, Videos etc. from other apps e.g. LibreTube

**Comment by fast4x** [comment]
Nice!

**Comment by fast4x** [comment]
Implemented, available from version 0.6.4 :)
