### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by carlospjr** [fast4x/RiMusic#1701]
### Description

    Search directly in a user library.

### Suggested Solution

Able to search the users playlists

### Alternatives

Able to search the users playlists

**Comment by fast4x** [comment]
hi, explain better please

**Comment by carlospjr** [comment]
For example, will be intersting if we able to exlplore a youtube music profile that we can view the playlists of him. Because exists profiles that have an a specific musical taste.

**Comment by dAtA-TRoN** [comment]
That doesn't sound well thought out.

**Comment by fast4x** [comment]
> For example, will be intersting if we able to exlplore a youtube music profile that we can view the playlists of him. Because exists profiles that have an a specific musical taste.

You can do this from Mood and Genres in Quick picks page...

**Comment by carlospjr** [comment]
I understood. I'ts has only a sugestion because I have some playlists and in some moments is not friendly share all time an playlist to Ri Music one by one.

If would is possible Id' can navigate in my own profile o another one that I wish and then able to salve this playlist in my librady, download, etc.

But dont worry I can do the share without problem. It was only a sugestion.

Thanks for your quickly anwser.

**Comment by fast4x** [comment]
Let me understand, what do you mean when you talk about profile from which to download the playlist? RiMusic has no user profiles...

**Comment by carlospjr** [comment]
Not having profiles after what they've shown me doesn't make much sense.

I also understand that there are no profiles for legal reasons, so it's better to share the playlists from YouTube Music directly to Ri Music, where it's safer.

My example is to do it as if it were in another neighboring app, to be able to see that person's musical tastes and be able to save them in my favorites or download them.

But since there are already flows, I think it's better not to have links with third-party profiles.

**Comment by dAtA-TRoN** [comment]
> RiMusic has no user profiles...

That's exactly what I don't understand either.

**Comment by dAtA-TRoN** [comment]
> RiMusic has no user profiles...

That's exactly what I don't understand either.

**Comment by AquamarineDreams** [comment]
@carlospjr

Let me get this straight. You want an easier way to transfer playlists and the musical taste from your yt/yt music profile to RiMusic. There isn't much that can be done to help you with this last one, but I think I can help you with the playlists. 

If you want to open your YouTube/YT music playlists in Rimusic, and save them to your library, you can do the following: Set your playlist to unlisted and, with the link search included in the app, open its link in Rimusic. Where you can easily import them into your library.

https://github.com/fast4x/RiMusic/assets/140275860/6c9de630-ff2f-49e7-819d-28514633b758

I don't know if that's what you wanted but I hope it helps.

**Comment by carlospjr** [comment]
> @carlospjr
> 
> Let me get this straight. You want an easier way to transfer playlists and the musical taste from your yt/yt music profile to RiMusic. There isn't much that can be done to help you with this last one, but I think I can help you with the playlists.
> 
> If you want to open your YouTube/YT music playlists in Rimusic, and save them to your library, you can do the following: Set your playlist to unlisted and, with the link search included in the app, open its link in Rimusic. Where you can easily import them into your library.
> 
>  Screenrecorder-2024-05-03-21-07-37-679.mp4 
> I don't know if that's what you wanted but I hope it helps.

Yeah! thats is it! I've tryed share from YT Music directly to Ri Music and works too.

Thanks a lot for advice!
