### ISSUE TITLE
Custom Version name

### ISSUE THREAD

**Issue by filipemanuelofs** [fast4x/RiMusic#1705]
### Description

"Custom version" implies that it is a different version of the original version, however, reading the explanation it is a version that is close to being released, it resembles a Beta or Release Candidate version, using software development jargon. 

### Suggested Solution

Wouldn't it be better to use one of these nomenclatures?
The term Beta is more widespread and the vast majority are perhaps more familiar with than Release Candidate.

### Alternatives

Beta Version, Release Candidate, etc.

**Comment by fast4x** [comment]
The beta version implies a regular release prior to the release of the production version. Currently the release is unique and weekly while the custom version is a version created by me to investigate some bugs.

**Comment by filipemanuelofs** [comment]
Got it!
