### ISSUE TITLE
Canciones/aleatorio, no funciona en Android Auto

### ISSUE THREAD

**Issue by Baviera10** [fast4x/RiMusic#1708]
### Steps to reproduce the bug

Go to canciones/Aleatorio en Android Auto y no funciona

### Expected behavior

Debería poner canciones aleatoriamente

### Actual behavior

Pone las canciones seguidas

### RiMusic version

0.6.32

### Android version

Android 14

### Additional information

Aplicación Genial!!

**Comment by fast4x** [comment]
I'll check it

**Comment by fast4x** [comment]
Fixed, available from version 0.6.33

**Comment by Baviera10** [comment]
Ok, thank you

**Comment by Baviera10** [comment]
Great!
