### ISSUE TITLE
Songs repetition

### ISSUE THREAD

**Issue by CiccioDerole** [fast4x/RiMusic#1709]
### Steps to reproduce the bug

1. Click on an artist
2. Go to "Songs" tab
3. Click on a song to start the queue

### Expected behavior

The queue should contain all the artist's songs without any repetition.

### Actual behavior

The queue contains only 5 or 6 songs which are repeated at least 2 times

### Screenshots/Screen recordings

![Screenshot_20240430-112103](https://github.com/fast4x/RiMusic/assets/127736920/01cb6295-1c14-43e5-9a5b-8eca85b083f7)

### RiMusic version

0.6.32

### Android version

Android 12

**Comment by fast4x** [comment]
If you enqueue... if you shuffle... not

**Comment by CiccioDerole** [comment]
> If you enqueue... if you shuffle... not

Yes but in previous versions it works correctly even when you enqueue

**Comment by fast4x** [comment]
i'll check it

**Comment by fast4x** [comment]
Fixed, available from version 0.6.33

**Comment by CiccioDerole** [comment]
This bug is still present in version 0.6.33. Please fix it🙏

**Comment by fast4x** [comment]
yes it's fixed

**Comment by CiccioDerole** [comment]
![Screenshot_20240504-230617](https://github.com/fast4x/RiMusic/assets/127736920/72589410-a0df-4b74-a8e1-5eef50e17eed)
I don't know why but I keep having this bug even in the latest version.
