### ISSUE TITLE
I want to add a random sorting order feature 🙏🏻

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#1710]
### Description

I want to add a random sorting order feature for the favorites list that will display different songs every time the list is opened, similar to how the shuffle songs function works. This will help us discover new songs or find the ones we love that may have been buried at the middle or lower middle of the list.

![Screenshot_20240430-163028](https://github.com/fast4x/RiMusic/assets/136909951/57ffee43-a701-4f63-8cc4-68bf75ad6c7c)

### Suggested Solution

Same..

**Comment by fast4x** [comment]
you can obtain same result with shuffle...

**Comment by Vishcot** [comment]
> you can obtain same result with shuffle...

Hey @fast4x, I can do that as well. But do you know why I asked about a random favorite "sort option"? It's because even though I have over 1000 favorite songs in my list, I always seem to encounter the same default songs every time I open my favorites or any other playlist. We end up selecting the same songs repeatedly because who wants to scroll through hundreds of songs before choosing one? 

I would like to request a feature where whenever I open my favorite playlist, I get to see a new list from my own favorites so that i have good options every time i open. I really love this idea!
Please consider this 🙏🏻

**Comment by fast4x** [comment]
Implemented random sorting icon in Favorites playlist, it can enable/disable by icon, when enabled, regular sorting will be auto randomized.
Available from version 0.6.34

**Comment by Vishcot** [comment]
> Implemented random sorting icon in Favorites playlist, it can enable/disable by icon, when enabled, regular sorting will be auto randomized.
> Available from version 0.6.34

Thankyou soooo sooooo much dev. 🔥🔥🔥🔥🔥
