### ISSUE TITLE
Swipe to Action Setting Not Disabling Swipe Functionality in Playlist

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1714]
### Steps to reproduce the bug

1. Go to the settings menu in the app.

2. Disable the "Swipe to action" option.

3. Navigate to the playlist section.

4. Attempt to swipe on a song entry in the playlist.

### Expected behavior

With the "Swipe to action" setting disabled, swiping gestures on song entries in the playlist should be disabled entirely. Users should not be able to swipe songs away or trigger any actions associated with swiping.

### Actual behavior

Even with the "Swipe to action" setting turned off, swiping gestures still function in the playlist. While the expected animation and functionality associated with swiping are not present, users are still able to swipe songs away without any indication, contrary to the disabled setting.

This behavior contradicts the expected functionality when the "Swipe to action" setting is disabled, leading to potential confusion and unintended actions for users who expect swiping to be disabled.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/71184627/cfd3ce46-6ed4-4d8d-aa2a-f51abd024234

### RiMusic version

0.6.32

### Android version

Android 13

**Comment by fast4x** [comment]
Swipe to action disabled enable horizontal swipe to delete from queue, is a feature.
Swipe to action is horizontal menu not gesture...

**Comment by dAtA-TRoN** [comment]
> Swipe to action disabled enable horizontal swipe to delete from queue, is a feature.
> Swipe to action is horizontal menu not gesture...

Oh, is that so. Then please add an animation for that. In its current state it doesn't look right.

**Comment by fast4x** [comment]
popup doesn’t make the gesture quick, it slows it down...

**Comment by dAtA-TRoN** [comment]
> popup doesn’t make the gesture quick, it slows it down...

No, you've misunderstood me: I'm not referring to a window, but rather to a passive message at the bottom of the screen, where you have a brief moment to undo the last action. Let me demonstrate using my Gallery app. Although it pertains to images, the principle remains the same:

https://github.com/fast4x/RiMusic/assets/71184627/275c4a11-a538-47de-8c08-da0371144a26
