### ISSUE TITLE
Enhance Queue View with Background Progress Bar

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1715]
### Description

When using the "Background Progress Bar" option, which displays the song progress graphically in the minimized player, it's currently not visible in the queue. It would be beneficial to extend this feature to the queue view as well. This enhancement would allow users to see the song progress directly within the queue, facilitating better decision-making regarding song selection.

### Suggested Solution

Integrate the background progress bar functionality into the queue display, enabling users to view the song progress alongside the queue items. This can be achieved by extending the existing functionality of the progress bar to the queue UI elements.

![IMG_20240501_090141](https://github.com/fast4x/RiMusic/assets/71184627/33458189-7390-4002-8f41-1cbf4b200fe5)

### Additional Context

This feature enhancement would provide users with a more comprehensive and intuitive music playback experience. It would streamline the process of monitoring song progress and selecting new songs, enhancing overall usability and convenience for users who frequently utilize the queue feature.

**Comment by aneesh1122** [comment]
That's not your playlist though. That's your queue 😅

**Comment by dAtA-TRoN** [comment]
> That's not your playlist though. That's your queue 😅

Ah, I see what you mean. English isn't exactly my native tongue, so please forgive any linguistic acrobatics that may ensue.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.33

**Comment by dAtA-TRoN** [comment]
> Implemented, available from version 0.6.33

![5gAA7.gif](https://github.com/fast4x/RiMusic/assets/71184627/563b57b3-f452-42df-8f80-da0c9e223b01)

**Comment by NikunjKhangwal** [comment]
It's kinda funny how i randomly came up with this "background progress bar" name (ViTune doesn't officially have any name of this or on/off functionality) and now it's a core feature of app. 😅

**Comment by fast4x** [comment]
It's a great functionality name... 😜

**Comment by dAtA-TRoN** [comment]
> It's a great functionality name... 😜

True. And thanks again for this feature here. It's actually very useful for me since I often linger in the queue, and at the end of a song, I like to make my next song choices manually as well.

**Comment by fast4x** [comment]
Thanks for the idea
