### ISSUE TITLE
What's the purpose of that space?

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#1716]
### Steps to reproduce the bug

1. Open any artists page.
2. Scroll to the bottom of overview page.
3. See the description 

### Expected behavior

Artist description taking the needed space.

### Actual behavior

Artist description is limited to certain part/side of the space. 

### Screenshots/Screen recordings

![Screenshot_20240429-193736](https://github.com/fast4x/RiMusic/assets/85461823/626c6266-afd1-4200-a8b4-a68c2fceac0f)

### RiMusic version

0.6.32

### Android version

Android 11

**Comment by fast4x** [comment]
I don't know, I'll check it

**Comment by fast4x** [comment]
Fixed, available from version 0.6.33
