### ISSUE TITLE
[Feature Request]: Only suggest songs that are not Cached/Downloaded.

### ISSUE THREAD

**Issue by aRandomMenno** [fast4x/RiMusic#1717]
### Description

Since I have been using this app for a long time I've build up approximately 3GB of cached music, however a lot of recommendations on the Quick Picks are already downloaded.

### Suggested Solution

I would like to see an option in settings so that only songs that are not yet cached/downloaded can be recommended, based on music you have played.

**Comment by fast4x** [comment]
Cached and downloaded songs are same icon. Cached by player set icon to downloaded...

**Comment by aneesh1122** [comment]
> Cached and downloaded songs are same icon. Cached by player set icon to downloaded...

He meant to say that he doesn't want to see those songs in his quick picks which he has already downloaded or cached.

**Comment by aRandomMenno** [comment]
> > Cached and downloaded songs are same icon. Cached by player set icon to downloaded...
> 
> He meant to say that he doesn't want to see those songs in his quick picks which he has already downloaded or cached.

I Indeed did mean that thank you.

**Comment by aRandomMenno** [comment]
Also fast4x could you in the future close the issue's that you have completed/implemented?
