### ISSUE TITLE
Quick pics refresh if you switch pages.

### ISSUE THREAD

**Issue by aRandomMenno** [fast4x/RiMusic#1719]
### Steps to reproduce the bug

1. Open the app, 
2. switch to another page, 
3. switch back,
4. Watch quick picks change.

### Expected behavior

1. Open the app, 
2. switch to another page, 
3. switch back,
4. Watch quick picks stay the same.

### Actual behavior

Quick picks get refreshed. 😭

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/109163471/61fb1008-5374-4c83-83f4-b108a7ba7106

### RiMusic version

6.32

### Android version

Android 14

**Comment by fast4x** [comment]
Casual song refresh anytime
