### ISSUE TITLE
Buggy Queue Behavior

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1728]
### Steps to reproduce the bug

Head over to the queue and tinker with it a bit. For instance, pull it halfway down and then let go. Give it a few tries, and you'll see what I mean. Things get pretty nasty, as demonstrated in this video -check a look:

https://github.com/fast4x/RiMusic/assets/71184627/ee17ece5-dfc2-43f3-8a12-97941235cce3

### Expected behavior

Even when fiddling around, a queue should do, what a queue normally do in this case.

### Actual behavior

The queue can just hang there in the middle. Sometimes you manage to get it back under control, and sometimes you just have to exit the screen altogether.

### RiMusic version

0.6.32

### Android version

Android 13

**Comment by fast4x** [comment]
But how did you find this bug? 😂😂

**Comment by dAtA-TRoN** [comment]
> But how did you find this bug? 😂😂

!? I don't see that this is normal behavior?

**Comment by dAtA-TRoN** [comment]
> But how did you find this bug? 😂😂

Whenever I listen to music, I find myself playing around with these animations. It's just a little quirk of mine 😅!
