### ISSUE TITLE
Error in Downloading songs greater than a certain limit (Not sure Size or Length of song)

### ISSUE THREAD

**Issue by abhisheksahnii** [fast4x/RiMusic#1730]
### Steps to reproduce the bug

Find a song either above 30+ minutes in length or considerably greater than 30+ MB. 

eg: 
1) https://www.youtube.com/watch?v=R9cAHnMtVSw&pp=ygUUanVrZWJveCBoaW5kaSBzb25ncyA%3D
2) https://www.youtube.com/watch?v=dGq_4-7sGNE

**Case 1:** 
1) When you click on download, it won't download and will go into a loop.
2) At the same time, Click on the download button for 4 to 5 more songs of the same length or size or above; All of them will go into the same error loop. 
3) You cannot download songs with normal length and size now. Hence, the above queue, in turn, affects all the queues waiting to be completed.

**Case 1 Result: Songs above 30+ minutes or bigger in download size will not be downloaded because of some unknown error at the backend.**

**Case 2:**
1) Delete all the downloaded songs from the library or ensure there is no other song in the queue for download.
2) Select any song with a normal length or size and click on download.

**Case 2 Result: The song will get downloaded normally.**

### Expected behavior

All the songs regardless of length or size should be able to download.

### Actual behavior

Songs are not getting downloaded.

### RiMusic version

Latest - 0.6.32

### Android version

Andriod 14

**Comment by fast4x** [comment]
Try to decrease audio quality format

**Comment by abhisheksahnii** [comment]
configured the audio quality to LOW in settings, still same issue.

**Comment by Anekbecomeek** [comment]
Facing similar issue, does anyone find a workaround

**Comment by MaxXor** [comment]
Same result here... would love to download a full album for offline playback.

**Comment by AstroLightz** [comment]
It seems to be a size thing since even 10-11 min songs fail to download, even on Low.
