### ISSUE TITLE
Icon on notifications player are big on Hyper OS

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#1731]
### Steps to reproduce the bug

![Screenshot_2024-05-02-10-51-27-126_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/247061d9-41e9-4696-a185-59bd870733bb)

### Expected behavior

I think it must be hyper OS, I don't think should be big like that 

### Actual behavior

It's too big 

### RiMusic version

0.6.32

### Android version

A14 Hyper OS 1.5 CN

**Comment by fast4x** [comment]
ahahahahaa nice, I'll check it

**Comment by fast4x** [comment]
I'm sorry but is just minimum size...

**Comment by NEVARLeVrai** [comment]
> I'm sorry but is just minimum size...

Can you try with other icons who are smaller ? And send me a custom so i can try

**Comment by NEVARLeVrai** [comment]
> I'm sorry but is just minimum size...

U can't ?

**Comment by fast4x** [comment]
After release of version 0.6.33 I'll create a custom version for you for try a possible fix .. ok?

**Comment by NEVARLeVrai** [comment]
> After release of version 0.6.33 I'll create a custom version for you for try a possible fix .. ok?

Okay, maybe it's only due to my hyper os rom since it's a CN rom and a custom rom. Yeah I modded my phone because my mi 10T is eol and wanted to try somes port of hyper os for my phone

**Comment by fast4x** [comment]
Hello, try this custom version... if it's ok..
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by NEVARLeVrai** [comment]
> Hello, try this custom version... if it's ok..
> https://github.com/fast4x/RiMusic/tree/master/customVersion

The buttons are offset and even bigger 😅

**Comment by fast4x** [comment]
interesting, tomorrow i do other custom
