### ISSUE TITLE
How to import playlist

### ISSUE THREAD

**Issue by Divytech** [fast4x/RiMusic#1732]
### Steps to reproduce the bug

Library > import playlist 

### Expected behavior

The app should support json file to be imported as playlist 

### Actual behavior

Mostly app support .json file to import playlist but it doesn't support .json file

### RiMusic version

0.6.32

### Android version

Android 14

**Comment by fast4x** [comment]
Import only RiMusic exported file format. Take a look here. https://github.com/fast4x/RiMusic/wiki/FAQs#what-is-the-csv-file-structure-for-importing-a-playlist-in-library

**Comment by fast4x** [comment]
Another way is to export any file from RiMusic and get format.
