### ISSUE TITLE
[Feature]: Song info, and album description

### ISSUE THREAD

**Issue by AquamarineDreams** [fast4x/RiMusic#1735]
### Description

When opening a song in Rimusic, you can't see things like release date, number of views, and credits. Since all of those informations are available on yt music, probably it wouldn't be hard to implement.

![IMG_20240502_122504](https://github.com/fast4x/RiMusic/assets/140275860/905ee4a1-411a-4d92-a856-41693c929e9e)

Also, when opening a album, you can't read it's description.

![IMG_20240502_122654](https://github.com/fast4x/RiMusic/assets/140275860/f7a06443-99af-4487-a096-0a614ff23a9c)

### Suggested Solution

Probably adding a info button with all the song's info would be enough. The same can be said for the album description.

### Additional Context

I understand if you don't want to add the like/view counter, but I think the song information is necessary.

**Comment by AquamarineDreams** [comment]
An option to play the music video would also be nice. But I don't see that as necessary.

**Comment by fast4x** [comment]
Added album info if available, available from version 0.6.33

**Comment by fast4x** [comment]
I'm sorry isn't stable I'll check it better.

**Comment by AquamarineDreams** [comment]
@fast4x

Sorry, could you tell me how I can access song/album info?

**Comment by fast4x** [comment]
Isn't stable, will be in the next release if ok

**Comment by fast4x** [comment]
Implemented, available from version 0.6.34

**Comment by AquamarineDreams** [comment]
Thank you so much

**Comment by fast4x** [comment]
Info album and artist are just implemented... also missed buttons in menu...

**Comment by AquamarineDreams** [comment]
> Info album and artist are just implemented... also missed buttons in menu...

Sorry, didn't really understand what you mean. Did I missed something?

**Comment by fast4x** [comment]
Descriptions in albums and artists are visible if available...
![Screenshot_2024-05-31-21-31-16-123_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/0f296681-5e9b-420d-a928-bb867a3b7509)

**Comment by AquamarineDreams** [comment]
> Descriptions in albums and artists are visible if available...

![IMG_20240531_163614](https://github.com/fast4x/RiMusic/assets/140275860/831bc067-6928-4413-b153-715b3eb14a7b)

Apparently it isn't working on all songs

![IMG_20240531_163904](https://github.com/fast4x/RiMusic/assets/140275860/5e076f1f-318a-41cf-96d0-7c7b36e83f2a)
