### ISSUE TITLE
Refresh isn't refreshing

### ISSUE THREAD

**Issue by AquamarineDreams** [fast4x/RiMusic#1736]
### Steps to reproduce the bug

Refresh quick pics page

### Expected behavior

The page refreshs and new songs are suggested 

### Actual behavior

Nothing happens 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/140275860/06ae9abf-2438-4601-86d3-04551f4d361e

### RiMusic version

0.6.32 - Latest 

### Android version

Android 14 - HyperOS

**Comment by fast4x** [comment]
Refresh of existing data occur in case of

1. quick pics not loaded correctly
2. in casual song mode

**Comment by AquamarineDreams** [comment]
That makes sense. My bad
