### ISSUE TITLE
[Feature]: EDITAR PLAYLIST 

### ISSUE THREAD

**Issue by Cron0s99** [fast4x/RiMusic#1738]
### Description

Al momento de editar una playlist falta la función de cambiar el orden de las canciones a como el oyente quiera tenerlas ordenadas como en Youtube músic.
![Screenshot_20240502-224118](https://github.com/fast4x/RiMusic/assets/168798911/84ff5d85-924b-48ca-b32c-d7e4fceeae1e)

### Suggested Solution

La función de cambiar el orden de las canciones en una playlist es muy God y necesaria

### Alternatives

Pues alternativa a esa función no hay xd

**Comment by fast4x** [comment]
Ho, is just implemented, set order to Position and order type Ascended.
![Screenshot_2024-05-03-07-51-16-575_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/2b1b2500-f0c0-4e28-ba23-4d39b5943d0e)

**Comment by Cron0s99** [comment]
No me refiero a un orden ascendente o descendente, me refiero a un orden libre de mover cualquier canción a cualquiera posición. Justo como en la imagen.
![Screenshot_20240502-224118~3](https://github.com/fast4x/RiMusic/assets/168798911/d87a3a3c-b2d9-41ce-a503-1185c46608c0)

**Comment by fast4x** [comment]
In your opinion, what is the difference between a queue and a playlist?

**Comment by Cron0s99** [comment]
No entiendo, las listas de reproducción no son las mismas  playlist?
![Screenshot_20240503-011651-850](https://github.com/fast4x/RiMusic/assets/168798911/7a78c156-827e-45f7-a604-422466a4e30d)

**Comment by Cron0s99** [comment]
![Screenshot_20240503-012621-094](https://github.com/fast4x/RiMusic/assets/168798911/aa896ee8-c2da-453f-8018-d9403612a378)
![327656030-2b1b2500-f0c0-4e28-ba23-4d39b5943d0e](https://github.com/fast4x/RiMusic/assets/168798911/57149201-598d-4faa-96d2-976085de083d)
por qué no me sale igual?

**Comment by fast4x** [comment]
arrow down is descendent and arrow up ascendent... set it ascendent and show lock/unlock reordering

**Comment by Cron0s99** [comment]
Definitivamente no entiendes cuál es la funcion de editar el orden de las canciones de la playlist libremente como en Youtube músic, poner la cancion que yo quiera arriba o abajo sin importar las canciones que haya agregado antes...en un orden ascendente o descendente ya que las ordena segun las canciones que hayas agregado recientemente : /

**Comment by fast4x** [comment]
RiMusic isn't YT Music...

**Comment by fast4x** [comment]
Thanks

**Comment by fast4x** [comment]
Great

**Comment by Armoa** [comment]
Entendido, gracias
