### ISSUE TITLE
Ability to play explicit/ [E] tagged songs

### ISSUE THREAD

**Issue by anxiouslelimo** [fast4x/RiMusic#1740]
### Description

Currently the app doesn't play [E] tagged song.

### Suggested Solution

A workaround to play such songs.

**Comment by fast4x** [comment]
Why not play? explicit is marked
![Screenshot_2024-05-03-07-56-37-970_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/a9780dfe-bedb-4f88-ac91-1f22be71d8b2)
