### ISSUE TITLE
App schließt sich nicht

### ISSUE THREAD

**Issue by Chungaa** [fast4x/RiMusic#1747]
### Steps to reproduce the bug

If you simply want to close the app, it won't close. No matter what you do.

### Expected behavior

Bug

### Actual behavior

Bug

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/109001366/cccf0a0d-f607-453f-9abb-42dcec1e8912

### Logs

No logs

### RiMusic version

0.6.32

### Android version

Android 13

### Additional information

My Phone Realme GT neo 2 Android 13

**Comment by fast4x** [comment]
![Screenshot_2024-05-04-03-28-32-658_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/9869a2f6-d78e-4453-a68b-c7c207988294)

Enable...

**Comment by Chungaa** [comment]
I have tried it but again it does not work for me.

**Comment by fast4x** [comment]
have closed and reopened?
