### ISSUE TITLE
I love the update but I think there are some small bugs xD.

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1751]
### Steps to reproduce the bug

It should work fine, but I suppose being so new, it has this small glitch.

### Expected behavior

Hopefully, the issues can be resolved soon.

### Actual behavior

In regards to the new addition of musical notes to discover or not, in my case, they all show up as negative (as shown in the image). Also, again, the 'scroll to top' icon overlaps with the listing bar.

### Screenshots/Screen recordings

![Screenshot_2024-05-03-16-41-32-087_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/6d72cc9c-1fc4-4879-ba52-934136d466bb)
![Screenshot_2024-05-03-16-43-40-561_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/38e79c27-cef7-4361-a105-469e7dd3ceca)
![Screenshot_2024-05-03-16-52-07-464_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/38bdc93d-d75e-44eb-93f6-2a1d5f412ff3)

### RiMusic version

0.6.33

### Android version

Android 13

### Additional information

I should clarify that I didn't quite understand the function of the notes as I saw them in passing xD. But aside from these two things, BEAUTIFUL UPDATE, good translation into Spanish, better optimization, and it looks much more beautiful.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.34
Thanks for appreciation

**Comment by aneesh1122** [comment]
> Fixed, available from version 0.6.34
> Thanks for appreciation

Please use that 'crossed melody' icon only for songs hidden by us manually.

The original request suggested to use it for songs we heard for 2-3 times and didn't select 'like'

I think that crossed melody icon should only be for hidden songs

**Comment by fast4x** [comment]
For now isn't possible

**Comment by aneesh1122** [comment]
> For now isn't possible 

So If I listened to a song for 2-3 times and didn't select 'liked' it will automatically be hidden?

**Comment by fast4x** [comment]
No, there isn't this fetaure... you want this?

**Comment by aneesh1122** [comment]
> No, there isn't this feature... you want this?

No. I want to manually hide songs.

#1609 wanted songs which are listened to 2-3 times and not 'liked' to be considered hidden. I don't agree with this solution.

I requested to keep the 'slashed musical notes' icon only for songs we have hidden.

If that's what you're planning too then please go ahead.

**Comment by fast4x** [comment]
No, there isn't this fetaure... you want this?I repeat, for now hidden and never listened is same...

**Comment by aneesh1122** [comment]
> No, there isn't this fetaure... you want this?I repeat, for now hidden and never listened is same...

Have something like this
![Screenshot_2024-05-04-16-40-46-940_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/6485040a-1d23-42e0-a33f-21df52be3a08)

The first song is 'never listened' and the second song is 'hidden'
It will be easy to distinguish between hidden and never listened songs.

I personally don't think 'never listened' songs need any indicator but if you want to have the indication this should be the way to do it.

**Comment by fast4x** [comment]
> > No, there isn't this fetaure... you want this?I repeat, for now hidden and never listened is same...
> 
> Have something like this
> ![Screenshot_2024-05-04-16-40-46-940_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/6485040a-1d23-42e0-a33f-21df52be3a08)
> 
> The first song is 'never listened' and the second song is 'hidden'
> It will be easy to distinguish between hidden and never listened songs.
> 
> I personally don't think 'never listened' songs need any indicator but if you want to have the indication this should be the way to do it.

Please create a ticket for this feature, thanks.

**Comment by drybin24** [comment]
Correct me if I'm wrong, hidden songs aren't skippable now, they are just marked with crossed-eye icon and that's it, right?

**Comment by aneesh1122** [comment]
> Correct me if I'm wrong, hidden songs aren't skippable now, they are just marked with crossed-eye icon and that's it, right?

I just installed the previous version and even there hidden songs are not getting skipped

I'm not sure what's the purpose of hiding a song

**Comment by drybin24** [comment]
their purpose is... to be skippable 😁

**Comment by drybin24** [comment]
> > Correct me if I'm wrong, hidden songs aren't skippable now, they are just marked with crossed-eye icon and that's it, right?
> 
> I just installed the previous version and even there hidden songs are not getting skipped
> 
> I'm not sure what's the purpose of hiding a song

purpose of it is... to skip the songs 😁

**Comment by drybin24** [comment]
their purpose is... to be skippable 😁

I mean, I personally hide those songs that I know I will never add in my Favorite playlist

**Comment by fast4x** [comment]
> > Correct me if I'm wrong, hidden songs aren't skippable now, they are just marked with crossed-eye icon and that's it, right?
> 
> I just installed the previous version and even there hidden songs are not getting skipped
> 
> I'm not sure what's the purpose of hiding a song

I don't remember that are skippable...

**Comment by drybin24** [comment]
> > > Correct me if I'm wrong, hidden songs aren't skippable now, they are just marked with crossed-eye icon and that's it, right?
> > 
> > I just installed the previous version and even there hidden songs are not getting skipped
> > 
> > I'm not sure what's the purpose of hiding a song
> 
> I don't remember that are skippable...

that's what I asked for in https://github.com/fast4x/RiMusic/issues/1609 : hidden=skippable
