### ISSUE TITLE
Player redesigned

### ISSUE THREAD

**Issue by col1iv** [fast4x/RiMusic#1753]
### Description

Made a few tweaks on the player screen :)
![Picsart_24-05-03_20-25-30-682](https://github.com/fast4x/RiMusic/assets/152646768/517aa792-ca3e-4f39-860a-921d1f382552)

### Suggested Solution

1 - Interactive buttons (download, playlist, share, maybe comments or user reviews? (likes and dislikes) inspired by Youtube Music.

2 - Lower bar only showing the lyrics section and queue section.

**Comment by dAtA-TRoN** [comment]
It's a bit crowded, isn't it? All those elements seem to disrupt the player's lovely design. And as for that Lyrics button taking center stage, it's a head-scratcher to me.
