### ISSUE TITLE
Show my top 10 bug

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#1754]
### Steps to reproduce the bug

1. Go to settings - UI - library
2. The option Show My Top 10 displayed incorrectly (%s instead of 10)

![Screenshot_20240504_114938](https://github.com/fast4x/RiMusic/assets/76595855/dcb39ff3-17a4-4439-be65-20f7fce41301)

In the library everything is OK 

![Screenshot_20240504_114950](https://github.com/fast4x/RiMusic/assets/76595855/9b4deb23-f9fc-436f-af99-b60fb21e0fd9)

### Expected behavior

Expected to see "Show My Top 10" option instead of "Show My Top %s" 

### Actual behavior

It shows me %s :)

### RiMusic version

0.6.33

### Android version

Android 13

### Additional information

Samsung Galaxy A51

**Comment by fast4x** [comment]
Fixed, available from version 0.6.34
