### ISSUE TITLE
Incorrect icon in fullscreen lyrics

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#1755]
### Steps to reproduce the bug

1. Open lyrics
2. Incorrect icon on the button to exit fullscreen mode

### Expected behavior

It is expected to see an icon with outward arrows to open fullscreen mode, and an icon with inward arrows to exit fullscreen mode.

### Actual behavior

The icon for exiting full-screen mode with the arrows pointing outwards, as for entering full-screen mode.

![Screenshot_20240504_120201](https://github.com/fast4x/RiMusic/assets/76595855/cad2595f-a176-475a-a984-5b36bb989b87)

### RiMusic version

0.6.33

### Android version

Android 13

### Additional information

The new icon was implemented in #1725, it was a new idea from #1401. But the new icon fully replaced the old one :) The new icon should only be applied to enter full-screen mode

**Comment by fast4x** [comment]
Icon is only one for maximize and redo... improved size, available from version 0.6.34
