### ISSUE TITLE
Synchronized lyrics visual bug

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#1756]
### Steps to reproduce the bug

1. Go to the song without available synchronized lyrics  
2. Try to open synchronized lyrics
3. Appears message "Lyrics not found on LrcLib.net, try on KuGou.com"
4. Appears message "Lyrics found on KuGou.com"

https://github.com/fast4x/RiMusic/assets/76595855/33ce7ca3-d906-43cb-9997-5729322eed4d

### Expected behavior

Expected to see a message "Lyrics WAS NOT found on KuGou.com"

### Actual behavior

Wrong message appears

### RiMusic version

0.6.33

### Android version

Android 13

**Comment by AquamarineDreams** [comment]
When there are no results on a standalone Lrclib.net search it also says "lyrics found" instead of not found

https://github.com/fast4x/RiMusic/assets/140275860/42342a9c-1626-4d28-bbdb-c1442ffc2909

**Comment by aneesh1122** [comment]
Am I the only one who doesn't like these toasts? It was way better how it was before imo.

**Comment by fast4x** [comment]
> Am I the only one who doesn't like these toasts? It was way better how it was before imo.

info is good...

**Comment by fast4x** [comment]
Improved, available from version 0.6.34
