### ISSUE TITLE
Bugs in the last few releases 

### ISSUE THREAD

**Issue by Atmosujk** [fast4x/RiMusic#1759]
### Steps to reproduce the bug

1. Settings-> Player Appearances , Settings -> About
2. Artist -> Select Artist -> Back Button, Library -> Select Playlist -> Back Button
3. Go to a playlist -> Mark/ Select some songs -> Scroll up until the marked songs are not visible -> Scroll down again and look at the songs marked earlier
4. Settings -> User Interface -> Theme : Default -> Theme mode : Light
5. Look for artists with songs that only have a little more (I took sweet ARMS as an example) -> Songs -> Play one of the songs
![Screenshot_20240504-110834](https://github.com/fast4x/RiMusic/assets/168883218/adf5def4-376c-44c8-b6b2-60b4a8e8ac70)
![Screenshot_20240504-110858](https://github.com/fast4x/RiMusic/assets/168883218/c637c81b-d7e8-4e2f-8dd0-3d785683b1b3)

### Expected behavior

1. If the navigation bar is at the bottom, that's fine
![Screenshot_20240504-102118](https://github.com/fast4x/RiMusic/assets/168883218/c9406835-9789-42dc-ae39-ddf4de4b3993)
![Screenshot_20240504-102110](https://github.com/fast4x/RiMusic/assets/168883218/b969bba4-cf39-451f-9af9-44501f2bf42a)
2. After pressing the back button the position should be in the last position
![Screenshot_20240504-103346](https://github.com/fast4x/RiMusic/assets/168883218/5168264e-9e96-405b-bd70-f38152f6c958)
![Screenshot_20240504-103357](https://github.com/fast4x/RiMusic/assets/168883218/e3ea9ed0-c553-41ea-891f-3fb881cc2ff6)
![Screenshot_20240504-103346](https://github.com/fast4x/RiMusic/assets/168883218/4dfcfd5e-3b58-4372-babb-e3d5dfe00dbc)
3. The marks on the songs remain
4. The Music text on RiMusic is clearly visible in light mode, like in dark mode
![Screenshot_20240504-110018](https://github.com/fast4x/RiMusic/assets/168883218/09de74b5-d709-4a6b-ad62-cdcf1b28a862)
5. It's clear that the artist only has 14 songs, and I hope that when I play one of the songs the number of songs in the playlist remains at 14 songs.

### Actual behavior

1.  If the navigation bar is not at the bottom , the bottom part of Player Appearances and About does not appear completely (cut off)
![Screenshot_20240504-101836](https://github.com/fast4x/RiMusic/assets/168883218/5c4b7d14-6d76-4e13-ad29-89206f6bb8bd)
![Screenshot_20240504-101828](https://github.com/fast4x/RiMusic/assets/168883218/d1a0ab93-2803-407e-b3de-3e7b167b28bd)
2. Return to the top position
![Screenshot_20240504-103404](https://github.com/fast4x/RiMusic/assets/168883218/7c51cf2c-5deb-4f6f-8324-3f91b1362207)
3. The marks disappears
![Screenshot_20240504-104054](https://github.com/fast4x/RiMusic/assets/168883218/ca625ccb-72b3-4094-b8b3-442f6ddf22b4)
![Screenshot_20240504-104659](https://github.com/fast4x/RiMusic/assets/168883218/fc38f45e-6cfd-412f-b233-11eeb1f86aef)
![Screenshot_20240504-104724](https://github.com/fast4x/RiMusic/assets/168883218/23626f8f-44fc-49c5-a71c-93255e2a08d3)
4. The Music text on the RiMusic logo is not visible at all
![Screenshot_20240504-110218](https://github.com/fast4x/RiMusic/assets/168883218/cc7033d7-58ca-4159-9c4c-943aa4a6db7e)
5. It's becomes 36 songs, and there are the same songs
![Screenshot_20240504-111344](https://github.com/fast4x/RiMusic/assets/168883218/6f8a49be-3f1b-4fe4-9d1c-b312e28a1295)

### RiMusic version

0.6.33 by fast4x

### Android version

Android 13

### Additional information

I am very grateful to the developers for continuing the ViMusic project with additional new features. Thank you very much.
Because there were lots of bugs in the latest version, I decided to return to version 0.6.29 where problems 1,2,4,5 did not occur in that version, for problem number 2 I think from the start until now not fixed yet.
Sorry if maybe my language is not understandable, because I used Google translate to write this

**Comment by fast4x** [comment]
Ok will do my best, thanks

**Comment by fast4x** [comment]
1,2,4,5 fixed, remain only 3 that will be solved in future

**Comment by Atmosujk** [comment]
Terimakasih banyak
