### ISSUE TITLE
[Feature]: ah brother, before it weighed 3mb, now 30mb is no longer the only app.

### ISSUE THREAD

**Issue by PIXIE-KEVIN** [fast4x/RiMusic#176]
### Description

Before it was fine with 3MB, the essence of the app was lost. The idea is to implement things but when you add such an amount of weight it no longer makes you want to download it.

I say this in constructive criticism. This you already have an app, a very complete modification because the need to add more weight to the app just to place it for effect.

I hope you take my comment in a good way, the essence of the app is that it weighs 3 or 4 MB, going beyond that loses its essence.

### Suggested Solution

.

**Comment by dd-dreams** [comment]
That's actually what I thought. I've forked the repo to remove some uneccessary features like the visualizer/equalizer. 
Don't see who actually uses them. Right now the app got bigger because of the libraries.

**Comment by fast4x** [comment]
Hello, are Google’s MLKIT libraries that seem can’t be compressed... unfortunately...

**Comment by fast4x** [comment]
The visualizer effect has no weight, it was inside 4 MB

**Comment by fast4x** [comment]
I will consider using another system to translate lyrics

**Comment by dd-dreams** [comment]
You're not supposed to use this library. This is a library that contains ML models. You should use some API like google translate but it doesn't offer great privacy which I actually don't think it matters since it isn't exposing any sensitive/identifiying data.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.12

MLkit was a test...

**Comment by OrangeZXZ** [comment]
To me it's not really an problem (it now takes 3GB) but i understand peoples not wanting all that unnecessary space

**Comment by fast4x** [comment]
Unfortunately there was the problem of some Google libraries that added weight for no reason and were recognized as Trojans. So I removed them using other
