### ISSUE TITLE
Ability to Play Age Restricted Songs

### ISSUE THREAD

**Issue by anxiouslelimo** [fast4x/RiMusic#1760]
### Description

Unable to play age restricted songs like https://music.youtube.com/watch?v=2o9aoL0NWpw

### Suggested Solution

A workaround to play such songs.

### Alternatives

A solution is possible since innertune does play such songs. Some userscripts are also available. Hopefully you can find a workaround

**Comment by AquamarineDreams** [comment]
A little off topic here, but I have several songs in my playlists that on YT Music are marked as explicit, and they play normally. I tried to play your song on my client, and, it gave me an error. I don't know what the difference is between the songs that make mine play and yours don't. Hopefully someone will figure it out and fix it.
Also, in a other bug report someone with, I think, the same issue as you, posted a print, and on that print of Rimusic, the song had the "[E]" tag. My client doesn't have the "[E]" tag on explicit songs. I don't know if that's normal, but is additional information.
