### ISSUE TITLE
Some playlists takes a long time to load

### ISSUE THREAD

**Issue by anxiouslelimo** [fast4x/RiMusic#1761]
### Steps to reproduce the bug

1. Search for pop
2. Go to featured playlists tab
3. Open playlist '00s Pop or '00s Pop Divas

### Expected behavior

The playlists should load instantaneously 

### Actual behavior

It takes a long time to load

### RiMusic version

0.6.33

### Android version

Android 11

**Comment by fast4x** [comment]
Yes and it is not solvable, you have to wait...
