### ISSUE TITLE
My Top %s 10

### ISSUE THREAD

**Issue by fofxox** [fast4x/RiMusic#1763]
### Steps to reproduce the bug

Visit the library's Top 10 list

### Expected behavior

The list used to be called My Top 10

### Actual behavior

The text changed in 0.6.33 to become My Top %s 10

### Screenshots/Screen recordings

![Screenshot_20240504_021553](https://github.com/fast4x/RiMusic/assets/130255231/7ff6c0e4-c051-4732-a4b3-95a13a069f01)

### RiMusic version

0.6.33

### Android version

Android 14

**Comment by aRandomMenno** [comment]
Same.
![Screenshot_20240504-101916.png](https://github.com/fast4x/RiMusic/assets/109163471/eb33a264-f992-4dc2-8b16-5c8991a48b5a)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.34
