### ISSUE TITLE
[Feature]: Library page changes

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1764]
### Description

This is how library page looks like now
![Screenshot_2024-05-04-09-38-09-278_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/cbabea57-56c2-4415-849a-eda6f45e7e5b)

### Suggested Solution

This is my requested changes
![Screenshot_2024-05-04-09-38-09-278_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/f350b620-0704-46ef-9f26-9b5791db3d29)

1) Remove extra 'Playlists (0)' section
2) Library should also have 'Hidden' section to list all the songs we have hidden in case we want to revisit all the songs we have hidden.

**Comment by fast4x** [comment]
Remove extra 'Playlists (0)' section
Isn't extra because it includes pinned playlists

**Comment by dAtA-TRoN** [comment]
> Remove extra 'Playlists (0)' section
> Isn't extra because it includes pinned playlists 

This section should only appear when you have some playlists pinned. Otherwise, it's clutter.

**Comment by dAtA-TRoN** [comment]
> Library should also have 'Hidden' section to list all the songs we have hidden in case we want to revisit all the songs we have hidden.

Far too unimportant to be featured so prominently.

**Comment by aneesh1122** [comment]
> > Library should also have 'Hidden' section to list all the songs we have hidden in case we want to revisit all the songs we have hidden.
> 
> Far too unimportant to be featured so prominently.

Hey, it's fine as long as I can get a list of all the hidden songs so that I can see all the hidden songs and 'unhide' some songs if I want

**Comment by dAtA-TRoN** [comment]
> Hey, it's fine as long as I can get a list of all the hidden songs so that I can see all the hidden songs and 'unhide' some songs if I want

I believe the feature itself is perfectly fine. However, the prominent placement you intend to give it isn't appropriate.

**Comment by aneesh1122** [comment]
> > Hey, it's fine as long as I can get a list of all the hidden songs so that I can see all the hidden songs and 'unhide' some songs if I want
> 
> I believe the feature itself is perfectly fine. However, the prominent placement you intend to give it isn't appropriate.

Well, it looked cool to me and there's a vacant space there and hidden songs are actually a part of our database so I thought it made sense to have it in the library.

At the end of the day, @fast4x gets to make the decision. I'll be fine with whatever he decides.

**Comment by fast4x** [comment]
I wonder where to put the function if not in the library?

**Comment by dAtA-TRoN** [comment]
> Well, it looked cool to me and there's a vacant space there and hidden songs are actually a part of our database so I thought it made sense to have it in the library.

And yet it's something that won't be given much thought. Most people, in fact, won't think about it at all. So it's just there, wasting valuable space that perhaps another, better function could occupy.

I mean, how often does it happen that I suddenly want to listen to songs I don't want to hear? In my case, that never happens. Such a feature, in my opinion, is only useful if you accidentally marked a track as hidden and need to correct that mistake. But it's such a niche problem that it definitely doesn't need to be presented so prominently.

**Comment by fast4x** [comment]
I find it interesting because lately I really liked going to look for songs that I had never listened to or that I had hidden.

**Comment by aneesh1122** [comment]
> > Well, it looked cool to me and there's a vacant space there and hidden songs are actually a part of our database so I thought it made sense to have it in the library.
> 
> And yet it's something that won't be given much thought. Most people, in fact, won't think about it at all. So it's just there, wasting valuable space that perhaps another, better function could occupy.
> 
> I mean, how often does it happen that I suddenly want to listen to songs I don't want to hear? In my case, that never happens. Such a feature, in my opinion, is only useful if you accidentally marked a track as hidden and need to correct that mistake. But it's such a niche problem that it definitely doesn't need to be presented so prominently.

Well, I want the option to see the list and unhide songs I want to. I can change my decision anytime and I want the option to do that.

So, I disagree with you. Even if you, or most people, won't even think about it, I want the freedom to choose what to hide or to unhide later if I wish to do so.

**Comment by dAtA-TRoN** [comment]
> I wonder where to put the function if not in the library?
> 
> 

I would put it somewhere in the settings.

**Comment by aneesh1122** [comment]
> > I wonder where to put the function if not in the library?
> > 
> > 
> 
> I would put it somewhere in the settings.

Nope. 'Settings' is not a place to put any of your songs catalogue. Settings should only have options like 'do you want this enabled?' or 'do you want this changed?'

I don't see why you are so much against adding it in the library. You don't want that? Don't use that. Let others who want to use that, use that.

**Comment by aneesh1122** [comment]
> > I don't see why you are so much against adding it in the library.
> 
> I've explained this already. It's a niche issue that would receive undue attention and waste valuable space better used for future features. I just advocate against cluttering the library with unnecessary items.

Let @fast4x add it wherever he wants to.

You can just ignore it if you don't want to use it if he decides to add it in the library.

I think the way I requested it to be implemented is perfect but fast4x is the one who gets to decide at the end.

**Comment by fast4x** [comment]
Will be enable by settings who want

**Comment by dAtA-TRoN** [comment]
Such discussions here are very important to make the best possible decision. Don't take it personally.

**Comment by dAtA-TRoN** [comment]
> Will be enable by settings who want

Great decision.

**Comment by fast4x** [comment]
It's same

**Comment by aneesh1122** [comment]
> Finally I have version 0.6.36 🙂 👍 And I want to ask if in the next versions there will be pinned playlists like before above the other playlists (maybe as an option...), because this way as a separate tab I really don't like it 😔

https://github.com/fast4x/RiMusic/issues/1812#issuecomment-2120289956

**Comment by ikanakova** [comment]
> > Finally I have version 0.6.36 🙂 👍 And I want to ask if in the next versions there will be pinned playlists like before above the other playlists (maybe as an option...), because this way as a separate tab I really don't like it 😔
> 
> [#1812 (comment)](https://github.com/fast4x/RiMusic/issues/1812#issuecomment-2120289956)

This would be great, but for now I'd be fine if it was like it used to be:
![313484507-a797861b-da67-4bc1-b443-c2d8a6ae21d0](https://github.com/fast4x/RiMusic/assets/38765251/8bee807c-693d-49cf-aa09-b34566bf0872)
instead of the way it is now:
![unnamed](https://github.com/fast4x/RiMusic/assets/38765251/4b05e5ae-1d94-4a83-961a-17d9d703608b)

**Comment by aneesh1122** [comment]
> > > Finally I have version 0.6.36 🙂 👍 And I want to ask if in the next versions there will be pinned playlists like before above the other playlists (maybe as an option...), because this way as a separate tab I really don't like it 😔
> > 
> > [#1812 (comment)](https://github.com/fast4x/RiMusic/issues/1812#issuecomment-2120289956)
> 
> [This](https://github.com/fast4x/RiMusic/issues/1812#issuecomment-2120002089) would be great, but for now I'd be fine if it was like it used to be:
> ![313484507-a797861b-da67-4bc1-b443-c2d8a6ae21d0](https://github.com/fast4x/RiMusic/assets/38765251/8bee807c-693d-49cf-aa09-b34566bf0872)
> instead of the way it is now:
> ![unnamed](https://github.com/fast4x/RiMusic/assets/38765251/4b05e5ae-1d94-4a83-961a-17d9d703608b)
> 
> 

For me

Designed playlist page > present playlist page > old playlist page

**Comment by ikanakova** [comment]
> > > > Finally I have version 0.6.36 🙂 👍 And I want to ask if in the next versions there will be pinned playlists like before above the other playlists (maybe as an option...), because this way as a separate tab I really don't like it 😔
> > > 
> > > 
> > > [#1812 (comment)](https://github.com/fast4x/RiMusic/issues/1812#issuecomment-2120289956)
> > 
> > 
> > [This](https://github.com/fast4x/RiMusic/issues/1812#issuecomment-2120002089) would be great, but for now I'd be fine if it was like it used to be:
> > ![313484507-a797861b-da67-4bc1-b443-c2d8a6ae21d0](https://private-user-images.githubusercontent.com/38765251/335466378-8bee807c-693d-49cf-aa09-b34566bf0872.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDQ3MDEsIm5iZiI6MTcxNzE0NDQwMSwicGF0aCI6Ii8zODc2NTI1MS8zMzU0NjYzNzgtOGJlZTgwN2MtNjkzZC00OWNmLWFhMDktYjM0NTY2YmYwODcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA4MzMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNDc1ODk4Y2FiMjJiOWRiNDRiZDMzZjNlNmE0YTVmNTFlZTA4YzBkMjkwOGE2ZTc2ZmE2OWVmNWI0MDZlMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.89o3zrUcDtnqLXbp42eEQhLE80SI4Rcxafy9yEFzKlI)
> > instead of the way it is now:
> > ![unnamed](https://private-user-images.githubusercontent.com/38765251/335466414-4b05e5ae-1d94-4a83-961a-17d9d703608b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDQ3MDEsIm5iZiI6MTcxNzE0NDQwMSwicGF0aCI6Ii8zODc2NTI1MS8zMzU0NjY0MTQtNGIwNWU1YWUtMWQ5NC00YTgzLTk2MWEtMTdkOWQ3MDM2MDhiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA4MzMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NGU2ZjIxMjNiYzNmYmFkZThmZjJmNDE3M2E0ZDdmNGNhN2QxNzEzMzQ2OGI3NWUyZThhNzkxYzBlZjNkMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1J655wVbAojHd1FZztrMFX6ctQo3GdA0Xy3ZkogskDo)
> 
> For me
> 
> Designed playlist page > present playlist page > old playlist page

I otherwise like the current Playlist page - moving favourites to Songs etc. I'd just like to be able to set it so that instead of toggling the Playlists and Pinned playlists tabs, they're below each other like before until being able to have pinned playlists among others just pinned up front.
