### ISSUE TITLE
some albums keep loading

### ISSUE THREAD

**Issue by NightFly88** [fast4x/RiMusic#1767]
### Steps to reproduce the bug

some albums keep loading for several days 

### Expected behavior

hope it can be resolved 

### Actual behavior

Nvt

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/163666747/3a20ec77-e666-4078-b990-5f9c327467a3

### RiMusic version

v0.6.33

### Android version

Android 14

**Comment by fast4x** [comment]
yes, would be solved in version 0.6.34

**Comment by NightFly88** [comment]
Thanks
