### ISSUE TITLE
[Crash]: When adding more than 3300 songs to a playlist. 🤭

### ISSUE THREAD

**Issue by aRandomMenno** [fast4x/RiMusic#1768]
### Steps to reproduce the bug

1. Have more than 3000 songs at the songs tab.
2. Add them to a playlist.
3. Wtach the app freeze and then crash after 5 seconds.

### Expected behavior

At step 3 it should complete adding the songs to the playlist.

### Actual behavior

It just crashes instead.

### Logs

(logfox crash report)
ANR in it.fast4x.rimusic (it.fast4x.rimusic/.MainActivity)
PID: 28980
Reason: Input dispatching timed out (808eab4 it.fast4x.rimusic/it.fast4x.rimusic.MainActivity (server) is not responding. Waited 5003ms for MotionEvent).
Parent: it.fast4x.rimusic/.MainActivity
ErrorId: 90efb236-c012-48f6-998d-8612045bed69
Frozen: false
Load: 1.56 / 3.2 / 3.46
----- Output from /proc/pressure/memory -----
some avg10=0.00 avg60=0.25 avg300=1.39 total=1699526133
full avg10=0.00 avg60=0.12 avg300=0.60 total=826822323
----- End output from /proc/pressure/memory -----
----- Output from /proc/pressure/cpu -----
some avg10=6.23 avg60=6.09 avg300=9.19 total=34449554643
----- End output from /proc/pressure/cpu -----
----- Output from /proc/pressure/io -----
some avg10=0.00 avg60=0.09 avg300=0.77 total=1143032425
full avg10=0.00 avg60=0.04 avg300=0.37 total=679824116
----- End output from /proc/pressure/io -----
CPU usage from 1ms to 13704ms later (2024-05-04 10:16:25.153 to 2024-05-04 10:16:38.856):
  22% 1465/system_server: 12% user + 10% kernel / faults: 17190 minor 337 major
  21% 544/surfaceflinger: 13% user + 7.5% kernel / faults: 266 minor 1 major
  13% 2381/com.android.systemui: 8.7% user + 4.9% kernel / faults: 8005 minor 184 major
  7.3% 553/android.hardware.composer.hwc3-service.pixel: 3.7% user + 3.5% kernel
  3.5% 3346/com.google.android.inputmethod.latin: 2.5% user + 0.9% kernel / faults: 17620 minor 130 major
  3% 29169/com.f0x1d.logfox: 2.4% user + 0.6% kernel / faults: 2027 minor
  2.9% 236/decon0_kthread: 0% user + 2.9% kernel
  2.8% 21179/com.google.android.gms.persistent: 1.9% user + 0.8% kernel / faults: 10206 minor 180 major
  2.3% 11993/com.google.android.googlequicksearchbox:interactor: 1% user + 1.2% kernel / faults: 2016 minor 2122 major
  0.5% 4138/app.lawnchair: 0.4% user + 0.1% kernel / faults: 2325 minor 213 major
21% TOTAL: 11% user + 7.7% kernel + 0.2% iowait + 1.2% irq + 0.3% softirq
CPU usage from 55ms to 580ms later (2024-05-04 10:16:25.207 to 2024-05-04 10:16:25.732):
  221% 1465/system_server: 121% user + 99% kernel / faults: 10932 minor 47 major
    77% 1969/HeapTaskDaemon: 57% user + 19% kernel
    48% 29435/AnrAuxiliaryTas: 15% user + 33% kernel
    26% 2212/CachedAppOptimi: 6.6% user + 19% kernel
    11% 2355/TaskSnapshotPer: 6.6% user + 4.4% kernel
    8.8% 3411/binder:1465_D: 2.2% user + 6.6% kernel
    6.6% 2041/android.bg: 4.4% user + 2.2% kernel
    6.6% 5196/binder:1465_1E: 4.4% user + 2.2% kernel
    4.4% 2027/android.io: 2.2% user + 2.2% kernel
    4.4% 2028/android.display: 2.2% user + 2.2% kernel
    4.4% 2029/android.anim: 2.2% user + 2.2% kernel
    2.2% 1465/system_server: 2.2% user + 0% kernel
    2.2% 1720/system_server: 0% user + 2.2% kernel
    2.2% 2026/android.ui: 2.2% user + 0% kernel
    2.2% 2049/OomAdjuster: 0% user + 2.2% kernel
    2.2% 2199/eduling.default: 2.2% user + 0% kernel
    2.2% 2224/InputDispatcher: 2.2% user + 0% kernel
    2.2% 2291/ConnectivitySer: 2.2% user + 0% kernel
    2.2% 2899/binder:1465_9: 2.2% user + 0% kernel
    2.2% 4514/binder:1465_12: 2.2% user + 0% kernel
  28% 544/surfaceflinger: 12% user + 16% kernel / faults: 62 minor
    10% 544/surfaceflinger: 6% user + 4% kernel
    4% 839/surfaceflinger: 0% user + 4% kernel
    2% 581/binder:544_1: 2% user + 0% kernel
    2% 584/RenderEngine: 2% user + 0% kernel
    2% 809/mali-cpu-comman: 2% user + 0% kernel
    2% 826/TimerDispatch: 0% user + 2% kernel
    2% 830/app: 0% user + 2% kernel
    2% 2837/binder:544_4: 0% user + 2% kernel
    2% 3377/binder:544_5: 0% user + 2% kernel
  18% 2381/com.android.systemui: 11% user + 6.8% kernel / faults: 197 minor 2 major
    4.5% 2381/ndroid.systemui: 2.2% user + 2.2% kernel
    2.2% 2579/wmshell.main: 0% user + 2.2% kernel
    2.2% 2583/wmshell.anim: 0% user + 2.2% kernel
    2.2% 2594/RenderThread: 2.2% user + 0% kernel
    2.2% 2817/ImageWallpaper: 0% user + 2.2% kernel
    2.2% 2844/mali-event-hand: 0% user + 2.2% kernel
    2.2% 2845/mali-mem-purge: 2.2% user + 0% kernel
    2.2% 7098/binder:2381_B: 0% user + 2.2% kernel
    2.2% 12405/binder:2381_E: 2.2% user + 0% kernel
  14% 4138/app.lawnchair: 9.5% user + 4.7% kernel / faults: 172 minor 7 major
    7.1% 4138/app.lawnchair: 4.7% user + 2.3% kernel
    7.1% 4198/RenderThread: 4.7% user + 2.3% kernel
    2.3% 27088/mali-event-hand: 2.3% user + 0% kernel
  8.1% 553/android.hardware.composer.hwc3-service.pixel: 4% user + 4% kernel
    6% 553/binder:553_3: 4% user + 2% kernel
    2% 576/DisplayHints: 2% user + 0% kernel
    2% 587/binder:553_1: 0% user + 2% kernel
  5.7% 84/kcompactd0: 0% user + 5.7% kernel
  5.7% 93/kswapd0: 0% user + 5.7% kernel
  3.8% 64/rcuop/6: 0% user + 3.8% kernel
  3.8% 236/decon0_kthread: 0% user + 3.8% kernel
  4% 476/logd: 0% user + 4% kernel
    2% 486/logd.writer: 0% user + 2% kernel
    2% 29247/logd.reader.per: 0% user + 2% kernel
  1.9% 49/rcuog/4: 0% user + 1.9% kernel
  1.9% 50/rcuop/4: 0% user + 1.9% kernel
  1.9% 103/dmabuf-deferred: 0% user + 1.9% kernel
  2% 477/lmkd: 0% user + 2% kernel
  2% 491/sugov:0: 0% user + 2% kernel
  2% 604/android.hardware.power-service.pixel-libperfmgr: 2% user + 0% kernel
    2% 3498/NodeLooperThrea: 0% user + 2% kernel
  2% 804/mali-gpuq-kthre: 0% user + 2% kernel
  2.1% 1028/android.hardware.sensors-service.multihal: 0% user + 2.1% kernel
  2.3% 2842/csf_sync_update: 0% user + 2.3% kernel
  2.3% 2847/csf_kcpu_0: 0% user + 2.3% kernel
  2.6% 11993/com.google.android.googlequicksearchbox:interactor: 0% user + 2.6% kernel / faults: 3 minor
  2.7% 16641/kworker/u16:30-gpu-dvfs-control: 0% user + 2.7% kernel
  2.7% 20728/kworker/4:3-memlat_wq: 0% user + 2.7% kernel
  2.7% 21179/com.google.android.gms.persistent: 0% user + 2.7% kernel / faults: 7 minor 4 major
  4% 29169/com.f0x1d.logfox: 4% user + 0% kernel / faults: 100 minor
    4% 29214/DefaultDispatch: 4% user + 0% kernel
48% TOTAL: 21% user + 24% kernel + 0.4% iowait + 1.2% irq + 0.4% softirq
Completed ANR of it.fast4x.rimusic in 13790ms, latency 0ms

### RiMusic version

0.6.33

### Android version

Android 14

**Comment by fast4x** [comment]
A playlist with 3000 songs not make much sense. Your log talk about timeout... reason would be your ram full...
