### ISSUE TITLE
Corners bug

### ISSUE THREAD

**Issue by CiccioDerole** [fast4x/RiMusic#1769]
### Steps to reproduce the bug

1. Set thumbnail roundness to Heavy or Medium or Light
2. Go to album tab
3. Set size to small or big

### Expected behavior

Album corners should be rounded.

### Actual behavior

The corners are rounded only if the size is medium

### Screenshots/Screen recordings

![Screenshot_20240504-122901](https://github.com/fast4x/RiMusic/assets/127736920/596a5b3e-ffbc-469f-b21a-f6e4d5c21ca4)
![Screenshot_20240504-122847](https://github.com/fast4x/RiMusic/assets/127736920/26f275f9-c02d-4127-b0a1-38530f2f1033)

### RiMusic version

0.6.33

### Android version

Android 12

**Comment by fast4x** [comment]
I''m sorry but i havnen't reproduced this ... for me work...

**Comment by CiccioDerole** [comment]
Maybe it is because I didn’t explain it clearly. I have just noticed that there is an option called thumbnail size but I wasn’t talking about it when I said to set the size to small. I wanted to say that you have to change the size from the new button in the album tab(the double-headed arrow).

**Comment by fast4x** [comment]
You mean shuffle button?

**Comment by CiccioDerole** [comment]
![Screenshot_20240504-230252](https://github.com/fast4x/RiMusic/assets/127736920/f0317a93-09c8-47e3-afed-c9c746185100)
This one

**Comment by fast4x** [comment]
must reduce the size?

**Comment by CiccioDerole** [comment]
As you can see in the last picture, if you click on this button and you set the size to small or big, the corners of album covers are not rounded.

**Comment by fast4x** [comment]
Look it's ok...

https://github.com/fast4x/RiMusic/assets/1484476/6afa3d3b-90b3-466f-a0ea-fdc076ac0c9f

**Comment by CiccioDerole** [comment]
https://github.com/fast4x/RiMusic/assets/127736920/5312525e-04ef-46ae-a49c-58a520dc3112

Here a video if you still don't understand. Look at the corners...

**Comment by fast4x** [comment]
pazzesco

**Comment by CiccioDerole** [comment]
I don't know what to say🤣
I will try not to notice it if it happens in the future

**Comment by fast4x** [comment]
I'll try to investigate

**Comment by CiccioDerole** [comment]
Grazie fra 😉

**Comment by fast4x** [comment]
Grazie a te fra 😂😜

**Comment by CiccioDerole** [comment]
Good news! I have tried setting the position of the navigation bar to bottom. It fixed the big size but the bug is still there for the small size. You can see it even in the video that you sent yesterday. Here a screenshot of it.
![Screenshot_20240505-105616_Chrome](https://github.com/fast4x/RiMusic/assets/127736920/3ade4731-0326-42da-8897-b8f2fc68732c)
These corners ar not as rounded as thei are in big and medium size. I hope you can notice it😁

**Comment by fast4x** [comment]
Sure but that’s right, a small size may not have the same rounding radius as a larger size.

**Comment by fast4x** [comment]
@CiccioDerole i have increased radius size...

**Comment by CiccioDerole** [comment]
I don't think the problem is radius size. It was prefect.

**Comment by CiccioDerole** [comment]
![prova](https://github.com/fast4x/RiMusic/assets/127736920/5edaeda5-6b83-4050-94c7-f016f9507af9)
I have reproduced the shape of the corners in red in this picture. As you can see the shape of the small one is strange because it is not like a circle. It seems like the corner has been cut by an horizontal bar.

**Comment by fast4x** [comment]
nice test
