### ISSUE TITLE
Settings bug

### ISSUE THREAD

**Issue by CiccioDerole** [fast4x/RiMusic#1770]
### Steps to reproduce the bug

1. Start the player
2. Go to settings
3. Go to Appearance or Data or Quick picks or About
4. Scrool down till the end of the page

### Expected behavior

There should be some extra space for the player (like in UI tab) to avoid that the player covers the last setting of the page.

### Actual behavior

It is impossible to access the last setting of the page, because it is hidden behind the player

### Screenshots/Screen recordings

![Screenshot_20240504-124641](https://github.com/fast4x/RiMusic/assets/127736920/44f3132d-fbb5-4118-8744-33e04f9e497e)

### RiMusic version

0.6.33

### Android version

Android 12

**Comment by Atmosujk** [comment]
![Screenshot_20240504-102110](https://github.com/fast4x/RiMusic/assets/168883218/691750f3-b13f-44a1-bd13-4c0683cfd196)
Yeah, i got the same problem but it doesn't happen if the navigation bar is at the bottom

**Comment by fast4x** [comment]
Fixed, available from version 0.6.34
