### ISSUE TITLE
[Feature]: different icons for 'Never listened' and 'Hidden'

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1771]
### Description

Right now both the hidden songs and never listened songs are indicated by the same icon. They are also treated equal. we should be able to differentiate between them.

### Suggested Solution

Please do something like this
![Screenshot_2024-05-04-16-40-46-940_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/4931e19f-4e19-4cf6-b233-7a4507c62dc7)
The first song is 'never listened' and the second song is 'hidden'
It will be easy to distinguish between hidden and never listened songs.

I personally don't think 'never listened' songs need any indicator but if you want to have the indication this should be the way to do it.

Also, when I click to hide 'hidden' songs, 'never listened' songs are also getting hidden. only hidden songs should hide

https://github.com/fast4x/RiMusic/assets/45353488/401bd3cd-8851-4380-963c-cb67aa75e0dc

**Comment by ikanakova** [comment]
Could both these icons be optional with distable options in the settings?

**Comment by aneesh1122** [comment]
> Could both these icons be optional with distable options in the settings?

Well, I don't like melody icon myself so if you ask me I want it to be removed. It's upto @fast4x though

Hide doesn't do anything except hide songs in the songs list. It still gets played from playlists and albums.

So, if both can be optional then pls that would be great
