### ISSUE TITLE
Gradient colour 

### ISSUE THREAD

**Issue by nelsonsiby2345** [fast4x/RiMusic#1772]
### Description

Changing the gradient background colour 

### Suggested Solution

Can you make the gradient background colour change according to the album cover it would be better if you do that

**Comment by dAtA-TRoN** [comment]
And please Mr. fast4x give us an option to use this also in material you. I miss my colors 🙃.

**Comment by fast4x** [comment]
Implemented, available form version 0.6.34

**Comment by fast4x** [comment]
> And please Mr. fast4x give us an option to use this also in material you. I miss my colors 🙃.

Already work in material because background color is based on system background

**Comment by dAtA-TRoN** [comment]
> Already work in material because background color is based on system background\nmaterial you not load from cover image...

That wasn't my point. On the one hand, I want the app to do exactly what you describe, but on the other hand, I would like an option just for the player colors to still match the album covers. Because as it is now, it's looking a little bit bland for me 🥲.

**Comment by fast4x** [comment]
You talk about changing color background always based on album cover?

**Comment by fast4x** [comment]
Isn't a problem, i can develop it instantly.. 😂

**Comment by dAtA-TRoN** [comment]
> You talk about changing color background always based on album cover?

I think it would be lovely if it were optional, as there are probably Pourists  out there who might not want that for their Material You theme. Or perhaps this feature should just be outsourced altogether and offered separately for all themes. So, each theme would have a default background color in the player that suits it. And for those who want to see colorful backgrounds there, dynamically adjusting to the currently playing song covers, they could simply enable that. If this sounds too much like a "special request" again, then just do it the way you envision. The main thing is that my player view in the Material You theme becomes beautifully colorful again 😅.

**Comment by fast4x** [comment]
Oh oh sounds good like Cover gradient, theme gradient, Fixed cover color, Dynamic cover color...

**Comment by dAtA-TRoN** [comment]
> Oh oh sounds good like Cover gradient, theme gradient, Fixed cover color, Dynamic cover color...

...or 'dynamic background colors' 🫨😅.

**Comment by fast4x** [comment]
It seems to be right 😜😂

**Comment by fast4x** [comment]
Implemented also custom background theme or cover with or without gradient

**Comment by dAtA-TRoN** [comment]
> Implemented also custom background theme or cover with or without gradient

![proxy-image(2).gif](https://github.com/fast4x/RiMusic/assets/71184627/27d9a41e-dcff-4788-8771-a2ffcfc86c93)
