### ISSUE TITLE
Playback issue on certain songs when offline

### ISSUE THREAD

**Issue by BobbyC06** [fast4x/RiMusic#1773]
### Steps to reproduce the bug

1. Download the song 'Intro' by Muse
2. Turn off Wi-Fi and Mobile Data
3. Go to Library, and then Downloads
4. Try and play the song

### Expected behavior

It will show a playback error, and will tell you to restart the app, you can turn the Wi-Fi on and off again which can fix it sometines.

### Actual behavior

Odds are, it will still show the playback error, unless it's a device specific issue.

### Screenshots/Screen recordings

![Screenshot_20240504_124306](https://github.com/fast4x/RiMusic/assets/168907930/13713fbd-8143-4465-a751-ae86b4b487f0)

### RiMusic version

0.6.33

### Android version

Android 14, One UI 6.0, April 2024 Security Patch

### Additional information

Device: Samsung Galaxy A52s (SM-A528B/DS)

**Comment by fast4x** [comment]
it occur if song aren't downloaded totally...

**Comment by BobbyC06** [comment]
That's strange, I've redownloaded the song, and I'm still having the same issue, maybe it's a device specific problem.
