### ISSUE TITLE
"page up" arrow behind the music player

### ISSUE THREAD

**Issue by AquamarineDreams** [fast4x/RiMusic#1775]
### Steps to reproduce the bug

Open any playlist and try to scroll up, you will notice, that the "page up" arrow,is behind the minimized player. Enable the floating icon, and _voilà_ now theres two arrows.

### Expected behavior

Arrow

### Actual behavior

Weird arrow

### Screenshots/Screen recordings

![IMG_20240504_115854](https://github.com/fast4x/RiMusic/assets/140275860/9e1be19e-b92b-40d5-bb4d-c30af32dac0d)

### RiMusic version

0.6.33 - latest

### Android version

Android 14 - HyperOS

**Comment by fast4x** [comment]
Fixed, available from version 0.6.34
