### ISSUE TITLE
Playlist doesn't load

### ISSUE THREAD

**Issue by dhevsabharish** [fast4x/RiMusic#178]
### Steps to reproduce the bug

1. Go to YouTube Music Library
2. Share Playlist
3. Choose RiMusic from the options

### Expected behavior

The playlist will load on the RiMusic app without any errors and this provides me the option to add the playlist to RiMusic Library

### Actual behavior

I just get a toast saying "RiMusic is loading". The playlist does not load. I have waited for over 5 mins but to no avail :(

The said playlist contains 350+ songs. I did not have this issue with playlists that had less than 100 songs

### Screenshots/Screen recordings

Uploading Screenrecorder-2023-12-04-20-03-37-573~3.mp4…

### RiMusic version

0.6.11

### Android version

Android 13

**Comment by dhevsabharish** [comment]
> Hi, can you give me the playlist link please?

https://music.youtube.com/playlist?list=PLonmB7H-wqgecw7kGQ64KpEcHWmTTjZyY&si=_5igdLTHE9Qfx6ab

**Comment by fast4x** [comment]
Thank you

**Comment by fast4x** [comment]
Yes, there is already in the next version

**Comment by ikanakova** [comment]
Same problem - RiMusic v0.6.13, Android 14, playlist: https://music.youtube.com/playlist?list=PLJevUfBwxpfw3HI3YynAOAYV_f9XWP8H4

**Comment by fast4x** [comment]
> Similar problem - I have the music.youtube.com links set to open in RiMusic. I click on the link, it opens the last tab in RiMusic but not the playlist - RiMusic v0.6.13, Android 14, playlist: https://music.youtube.com/playlist?list=PLJevUfBwxpfw3HI3YynAOAYV_f9XWP8H4

This now load, 
I’m sure it loads with fewer songs, but it doesn’t depend on the app.
