### ISSUE TITLE
Back action defaulting to Library

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1782]
### Steps to reproduce the bug

Go to settings
Set default page to Library

### Expected behavior

When you open any album or artist from navigation bar and go back the app automatically goes to library tab instead of album or artist respectively. It doesn't happen when quick picks is set to default. I think default tab should only work for opening the app for first time.

### Actual behavior

🔝

### RiMusic version

0.6.33

### Android version

Android 12

**Comment by NikunjKhangwal** [comment]
Update:- It's the same for when choosing quick picks as well. I missed the "default" option.
Either way i think this option should only work for opening the app and not always.

**Comment by fast4x** [comment]
Now default page have a bug I'll fix soon, it's related to new navigation system

**Comment by NikunjKhangwal** [comment]
Ok, makes sense 👍🏼
