### ISSUE TITLE
Text change and possible bug

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1783]
### Steps to reproduce the bug

Go to settings and check the settings mentioned below

### Expected behavior

The "move search shortcut to navigation bar" should be "Show search shortcut/button in navigation bar". It isn't moving or replacing any other icon.

Also the floating icon button isn't doing anything, the floating button stay enabled anyway. Probably a bug related to Vimusic mode.

![IMG_20240505_114407](https://github.com/fast4x/RiMusic/assets/99175083/3c8e7e11-f56e-4a82-b0fd-896515f12f7e)

### Actual behavior

.

### RiMusic version

0.6.33

### Android version

Android 12

**Comment by NikunjKhangwal** [comment]
Also this should be "menu" style

![IMG_20240505_110408](https://github.com/fast4x/RiMusic/assets/99175083/6347b801-0a75-4f23-94fc-d4f511b52900)

**Comment by Aparimit-Rathour** [comment]
hey, can you assign this to me. i think i can fix this

**Comment by NikunjKhangwal** [comment]
I think only the developer can do it. Wait for fast4x response.
Also can you fix the floating icon bug too?

**Comment by fast4x** [comment]
> Also this should be "menu" style
> 
> ![IMG_20240505_110408](https://github.com/fast4x/RiMusic/assets/99175083/6347b801-0a75-4f23-94fc-d4f511b52900)
> 

fix this is to correct translation in Crowdin

**Comment by fast4x** [comment]
> hey, can you assign this to me. i think i can fix this
> 

if you want fix something, you can clone repository, change code and send pull request.

**Comment by fast4x** [comment]
> Also this should be "menu" style
> 
> ![IMG_20240505_110408](https://github.com/fast4x/RiMusic/assets/99175083/6347b801-0a75-4f23-94fc-d4f511b52900)
> 

yes translation is wrong

**Comment by NikunjKhangwal** [comment]
Ok. I'll see and fix in crowdin

**Comment by faustaahmad** [comment]
What does Navigation bar style do? I didnt see any changes on my navigation bar

Also "Move search shortcut to navigation bar" is correct translation
ViMusic mode only, moving search shortcut from top right → Navigation bar

**Comment by NikunjKhangwal** [comment]
It's actually menu style which changes 3 dots menu to list or grid.

Move search is for side nav i guess
