### ISSUE TITLE
Button's are dis-positioned in landscape view on a tablet

### ISSUE THREAD

**Issue by Uneccessary** [fast4x/RiMusic#1784]
### Steps to reproduce the bug

1. Go to some Album, Playlist
2. See that the buttons are at the wrong position

### Expected behavior

The buttons are at the right position

### Actual behavior

Buttons are dis-positioned

### Screenshots/Screen recordings

![image22](https://github.com/fast4x/RiMusic/assets/145043411/ed8b6cf2-a3cd-43db-b100-c0559979f69b)

### RiMusic version

0.6.33

### Android version

Android 11

### Additional information

Ignore the other underlining it was a screenshot related to https://github.com/fast4x/RiMusic/issues/1763#issue-2278782017

**Comment by fast4x** [comment]
Fixed, available from version 0.6.34
