### ISSUE TITLE
[Feature]: QUESTION

### ISSUE THREAD

**Issue by PPereaC** [fast4x/RiMusic#1788]
### Description

Hello,

I'm writing this to ask if your app has a feature that allows me to play a selected song from a playlist without automatically queuing the rest of the songs. I would like to manually control what plays next or choose to shuffle. I'm just wondering if this functionality exists or if there's a way to set it up like this.

Thank you!

### Suggested Solution

:)

**Comment by aneesh1122** [comment]
Use 'play next' or 'Enqueue' if you want the song at the end of your current queue.

Shortcut to add songs to the queue
https://github.com/fast4x/RiMusic/assets/45353488/3699cb7d-ad2c-429c-ade2-d448adfbe83b

**Comment by fast4x** [comment]
No there isn't, i can implement

**Comment by PPereaC** [comment]
> Use 'play next' to add to the next of now playing or 'Enqueue' if you want the song at the end of your current queue.
> 
> Shortcut to add songs to the end of the queue https://github.com/fast4x/RiMusic/assets/45353488/3699cb7d-ad2c-429c-ade2-d448adfbe83b

Good alternative, but if it can be implemented better.
