### ISSUE TITLE
'go to playlist' not working

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1789]
### Steps to reproduce the bug

https://github.com/fast4x/RiMusic/assets/45353488/1a0e0afb-3b6d-48b0-bfba-f73d45eb1222

### Expected behavior

Playlist should open

### Actual behavior

Playlist isn't opening

### RiMusic version

0.6.33

### Android version

Android 13

**Comment by fast4x** [comment]
Fixed, available from version 0.6.34
