### ISSUE TITLE
LISTA DE MÚSICA NO SE MUESTRAN EN DIFERENTES ALBUMS

### ISSUE THREAD

**Issue by chatinteligence** [fast4x/RiMusic#1792]
### Steps to reproduce the bug

1- Búsqueda de álbum 
2- Acceder al álbum 
3- Despliegue de lista y no aparecen 

https://music.youtube.com/playlist?list=OLAK5uy_kzQXPwKBBrfnAVLYLGkR0tKekwwQiKHvI

### Expected behavior

![Screenshot_20240505_223434](https://github.com/fast4x/RiMusic/assets/147566193/3f1772a4-b6a6-470f-a65b-11abb984901c)

### Actual behavior

Ese error no solo en este álbum aparece sino en otros más , gracias 

### Screenshots/Screen recordings

![Screenshot_20240505_223434](https://github.com/fast4x/RiMusic/assets/147566193/865eb777-733f-4415-891c-4f17d9526d30)

### RiMusic version

0.6.33

### Android version

Android 14

### Additional information

Agradecería se pueda arreglar este error, en plataformas como SimpMusic aparecen correctamente, gracias y saludos 

![Screenshot_20240505_223636_SimpMusic](https://github.com/fast4x/RiMusic/assets/147566193/003e0555-d4c3-46ce-84d8-a2cea84b591c)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.34
