### ISSUE TITLE
Please implement 'right swipe to play next'

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1794]
### Description

Like this

https://github.com/fast4x/RiMusic/assets/45353488/19091f20-17a2-49e6-b6dc-d1c55daba558

### Suggested Solution

~~Swipe and hold can be used to add the song at the end of the queue~~
In short
1. Swipe and release : play next
~~2. Swipe and hold : add to the end of queue~~

**Comment by fast4x** [comment]
What's app in in video?

**Comment by aneesh1122** [comment]
> What's app in in video?

Spotify

**Comment by fast4x** [comment]
RiMusic have swipe to action menu...

**Comment by aneesh1122** [comment]
> RiMusic have swipe to action menu...

yeah but spotify's implementation is much better. It just needs a single swipe and song gets added to play next (1 step). the swipe gets closed automatically too

In RiMusic you have to do it in 3 steps
1) swipe right
2) select 'add to queue' and songs gets added at the end of the queue.
3) close the swipe (since it doesn't close itself)

My idea
- Swipe and release and song gets added to play next
and
- Swipe and hold and song gets added to the end of the queue

**Comment by Cuchurrumin19** [comment]
> ### Description
> Like this
> 
>  VID_20240506_013228.mp4 
> ### Suggested Solution
> Swipe and hold can be used to add the song at the end of the queue
> 
> In short
> 
> 1. Swipe and release : play next
> 2. Swipe and hold : add to the end of queue
> 
> ### Alternatives
> _No response_
> 
> ### Additional Context
> _No response_

Wow, I love this request

**Comment by AquamarineDreams** [comment]
> RiMusic have swipe to action menu...

Yeah, but it only works in user created playlists. It would be nice to have that feature in albums, and music search.

**Comment by aneesh1122** [comment]
> > RiMusic have swipe to action menu...
> 
> Yeah, but it only works in user created playlists. It would be nice to have that feature in albums, and music search.

The reason why it works only in user created playlists is because the left swipe has the option to delete songs too.

Fast4x has to create new swipe action for non-user created areas which doesn't have 'delete'

**Comment by fast4x** [comment]
Implemented, available from version 0.6.42

**Comment by aneesh1122** [comment]
> Implemented, available from version 0.6.42

Thanks man. Will this work everywhere like playlists, queue, albums and songs?

**Comment by fast4x** [comment]
yes in all
