### ISSUE TITLE
Add option to have only one search button

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1796]
Currently, if one so desires, they can have up to 3 search buttons in the application, namely one in the top UI, one on the side and a floating one.

This behavior seems unnecessary, as (in my opinion) one would have to use only one search icon.

There should be a setting to set where the search button is: on the top, navigation bar or floating

This way, there would be no more problems with the search button being in 2 (or even 3) places: on the top/ floating and in the navigation menu. Only one location would be selectable at a time.

Also, as a side note, some assistance with #1699 would really be appreciated. It's really getting on my nerves

**Comment by dAtA-TRoN** [comment]
This shouldn't be optional; it should simply be changed to avoid redundancy. Otherwise, you could argue that you'd need three parallel versions for all other buttons as well.

**Comment by privacyfreak84** [comment]
> This shouldn't be optional; it should simply be changed to avoid redundancy. Otherwise, you could argue that you'd need three parallel versions for all other buttons as well.

I don't get it

**Comment by dAtA-TRoN** [comment]
> I don't get it

What I mean is that it's irrational to have more than one search button, so the question of optionality regarding this doesn't even arise. In other words, I agree with you, but I'm even stricter because I believe there shouldn't be an option for more than one search button at a time as you mentioned. If such an option exists, there would ultimately be no excuse for not allowing every other button to be displayed multiple times simultaneously. Someone always insists, "But I urgently need that."

**Comment by fast4x** [comment]
The search buttons are two: 1float and 1 in the top bar. The third is shown if enabled and in ViMusic mode...

**Comment by privacyfreak84** [comment]
Yes... So there should be an option (or maybe it should be the default and only way, as dAtA-TRoN thinks (and an idea with which I agree)) to have only one search button present throughout the entire app

**Comment by privacyfreak84** [comment]
> The search buttons are two: 1float and 1 in the top bar. The third is shown if enabled and in ViMusic mode...

What I'm saying is that there should be only one search button in the app.

There should be an option to change the location of it.

It should be impossible to have more than one search button present in the UI

**Comment by fast4x** [comment]
Screenshot please . .. 😊

**Comment by privacyfreak84** [comment]
![Screenshot_20240507-194247](https://github.com/fast4x/RiMusic/assets/90613992/9ea095f1-a98f-4259-ba06-25071f9844fb)


There should be only one search button. The user should be able to choose its location
