### ISSUE TITLE
Search icon on navigation bar even if it is disabled

### ISSUE THREAD

**Issue by CiccioDerole** [fast4x/RiMusic#1797]
### Steps to reproduce the bug

1. Go to library page
2. Click on On device

### Expected behavior

On the navigation bar there should not be the search icon because it is disabled.

### Actual behavior

There is the icon. It only happens if you click on On Device.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/127736920/4c4740c2-c7cb-4220-9cb4-8ec9814261d2

### RiMusic version

0.6.33

### Android version

Android 12

**Comment by AquamarineDreams** [comment]
Search icon jumpscare
