### ISSUE TITLE
In the settings the name "player" is written in capital letters, different than others

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#18]
### Steps to reproduce the bug

Go to settings then see "player" 

### Expected behavior

"player" should be written like the others 
It should be written as "Player" and not "PLAYER" 

### Actual behavior

Only the player is written as PLAYER. Others dont have all capital letters 

### Screenshots/Screen recordings

![photo_2023-10-12_23-24-51](https://github.com/fast4x/RiMusic/assets/127825700/ca7758c6-8fc6-436c-8dfc-b6c74b880f4a)

### RiMusic version

latest version

### Android version

android 11

**Comment by siggi1984** [comment]
In the German language it is correct
![Screenshot_20231012-201736_2](https://github.com/fast4x/RiMusic/assets/103368536/2bfcb653-7369-4556-aa56-de82255b73e9)

**Comment by dainvincible1** [comment]
> In the German language it is correct ![Screenshot_20231012-201736_2](https://user-images.githubusercontent.com/103368536/274696874-2bfcb653-7369-4556-aa56-de82255b73e9.jpg)


ohh then i guess this is only there in english language

**Comment by fast4x** [comment]
Fixed, available from 0.6.4 version
Thanks! :)
