### ISSUE TITLE
App flagged as `Trojan` on Virustotal

### ISSUE THREAD

**Issue by SheAsuna** [fast4x/RiMusic#180]
### Steps to reproduce the bug

- Scan the latest version of the app
- v0.6.11
- Versions older than this isn't having the issue

### Expected behavior

It should not be flagged as `Trojan`

### Actual behavior

It gets flagged as `Trojan`

### RiMusic version

0.6.11

### Android version

Android 13

### Additional information

Also, the apk size is quite huge from the version `0.6.11`

Here's the scan result: https://www.virustotal.com/gui/file/906a4b2fbe9e0afa761940d62250f6fa58f169a02d4fff41cd80c1ee4d65e37b

**Comment by ikanakova** [comment]
This is probably a false positive because [TROJ_GEN is Windows](https://www.trendmicro.com/vinfo/us/threat-encyclopedia/malware/TROJ_GEN) only and this is an Android app.

**Comment by fast4x** [comment]
It may have been caused by the MLKit library used in that version. In the new version 0.6.12 there will not be so it should all come back as before.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.12

**Comment by fast4x** [comment]
Confirmed, new version 0.6.12 is detention virus free.
Link Scan
https://www.virustotal.com/gui/file/646e42b5e5a1aece868f7b6e71651b82ef5271318b2f439d8e12d54b5d5354a2?nocache=1
