### ISSUE TITLE
track changing when clicking on playlist

### ISSUE THREAD

**Issue by alexou2** [fast4x/RiMusic#1800]
### Steps to reproduce the bug

Play a song from your liked songs 
Go back and quickly click on a playlist (as in your finger doesn't contact the screen for long)
In my case, the bug doesn't happen eveey time. In that case, just go back and repeat step 2.

### Expected behavior

Open the playlist without changing the song

### Actual behavior

The song changes to a song in the playlist i clicked on and the playlist doesn't open

### Screenshots/Screen recordings

`https://photos.app.goo.gl/cYvBFAvHp4EXZHyp9`

### RiMusic version

0.6.32

### Android version

14

### Additional information

The bug also works when playing songs from a playlist and then clicking on my liked songs

**Comment by fast4x** [comment]
Not reproduced
https://github.com/fast4x/RiMusic/assets/1484476/4fe47467-3761-4dbe-87ab-da25e37092ed
