### ISSUE TITLE
Spotify playlist important 

### ISSUE THREAD

**Issue by Asur30** [fast4x/RiMusic#1801]
### Description

Please make a feature.. So that we can log into Spotify through this app and get our Spotify playlist listed on the playlist section 

### Suggested Solution

It should ask for login to spotify action at the first  so that it can sync our Spotify playlist into this app.. While using the music source from youtube music

**Comment by dAtA-TRoN** [comment]
Yeah, would be cool.

**Comment by 6XChen** [comment]
Hmm... Interseting 🤔

**Comment by fast4x** [comment]
> Yeah, would be cool. But I think logging into the Spotify account could be too complex. However, it would be sufficient if fast4x could make the Spotify playlist files readable for RiMusic, so they could be imported using the existing playlist import function.

Would be great but songs code is different from youtube music

**Comment by ikanakova** [comment]
> Would be great but songs code is different from youtube music

I think sites like Soundiiz do it by taking songs in a Spotify playlist and finding a match on YouTube by name and artist.

**Comment by ikanakova** [comment]
And I strongly disagree with Spotity logging in as well as YouTube logging in. For tracking, legality, etc.

**Comment by fast4x** [comment]
> And I strongly disagree with Spotity logging in as well as YouTube logging in. For tracking, legality, etc.

yes isn't planned

**Comment by aneesh1122** [comment]
[spotdl](https://github.com/spotDL/spotify-downloader) downloads from YouTube music using metadata from Spotify and it doesn't require you to login.

Pls see how it is fetching songs from YouTube music and try to implement it.

**Comment by fast4x** [comment]
isn't planned to develop anything for download anything

**Comment by aneesh1122** [comment]
> isn't planned to develop anything for download anything 

I'm not asking you to develop downloading songs.

Just see how it gets YouTube links for Spotify songs.

Before downloading, spotdl must search for the song. Right? So just see the process of obtaining the YouTube link for Spotify songs which you can later add in RiMusic playlist

**Comment by ikanakova** [comment]
It might help: https://github.com/sigma67/spotify_to_ytmusic - "A simple command line script to clone a Spotify playlist to YouTube Music."

**Comment by fast4x** [comment]
Impressed

**Comment by Aleks-Levet** [comment]
How's it going? If i can import my 500 song spotify playlist i will use rimusic as my main music servic3...

**Comment by fast4x** [comment]
You can transfer it to YouTube Music, after you can share it with RiMusic and import.
