### ISSUE TITLE
Back button doesn't close app.

### ISSUE THREAD

**Issue by FaqatZubair1** [fast4x/RiMusic#1802]
### Steps to reproduce the bug

Open the app
Hit the back button or use the gesture you use to go back
The app won't close

### Expected behavior

The app should close 

### Actual behavior

It doesn't close 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/161596117/80327e33-b03f-4600-9288-65cce7ae967c

### RiMusic version

0.6.33

### Android version

Android 14

**Comment by fast4x** [comment]
enable from settings

**Comment by FaqatZubair1** [comment]
Solved, but it shoukd be enabled by default. And if user wants he could disable it.

**Comment by fast4x** [comment]
> Solved, but it should be enabled by default. And if user wants he could disable it.

You are right

**Comment by fast4x** [comment]
Fixed, available from version 0.6.34
