### ISSUE TITLE
Ad Android Auto

### ISSUE THREAD

**Issue by Philcarbon52** [fast4x/RiMusic#1804]
### Description

Pouvez vous intégrer Rimusic dans Android Auto

### Suggested Solution

Je ne sais pas si c'est. Possible

**Comment by fast4x** [comment]
Il est déjà compatible avec Android Auto, vous devez l’activer dans les paramètres miscellaneous 
https://github.com/fast4x/RiMusic/wiki/FAQs#why-does-android-auto-not-see-rimusic
