### ISSUE TITLE
Feature: Crossfade - Gradual song transition

### ISSUE THREAD

**Issue by AquamarineDreams** [fast4x/RiMusic#1805]
**Edit:** Apparently the "gradual song transition" is originally called crossfade in english.

### Description

A few days ago, @stoneubi suggested the existence of a "DJ mode" [#1778]. The users, quickly realized, that this 'mode' could be implemented with two features present on Spotify. They being "gradual song transition", and "swipe to play next".
Since a new ticket was open for the "swipe to play next" feature [#1794], I thought it would be appropriate to do the same with "gradual song transition".

### Suggested Solution

So what is _gradual song transition_? Basically, with this feature enabled, the 1 - 10 last second of a song are merged with, the equivalent time, of the start of the next song. That is made by, gradually, turning down the volume of the song while rising the volume of the next song.

### Alternatives

That could be implemented with a slider, like in Spotify, or with a selection menu, like other items in Rimusic.

![IMG_20240507_163705](https://github.com/fast4x/RiMusic/assets/140275860/9a319f2c-3cc4-4c0e-ae42-f704b0c775b7)

**Comment by jaki444** [comment]
Nice idea would be really cool to have it on rimusic

**Comment by aneesh1122** [comment]
Add `crossfade` in title to make it more understandable to Spotify users

**Comment by AquamarineDreams** [comment]
> Add `crossfade` in title to make it more understandable to Spotify users

Done

**Comment by fast4x** [comment]
Implemented crossfade songs effect, available from version 0.6.34

**Comment by Vishcot** [comment]
@fast4x  I feel, you've only implemented fade song feature or it was a misunderstanding! 
We ( including me as well )asked crossfade as @AquamarineDreams said..gradual transition of songs i.e. last 10 seconds of one somg and first 10 seconds of next song fusioned together, with fading effect.

![Uploading Screenshot_20240516-203052.png…]()

**Comment by aneesh1122** [comment]
> @fast4x  I feel, you've only implemented fade song feature or it was a misunderstanding! 
> We ( including me as well )asked crossfade as @AquamarineDreams said..gradual transition of songs i.e. last 10 seconds of one somg and first 10 seconds of next song fusioned together, with fading effect.
> 
> ![Uploading Screenshot_20240516-203052.png…]()
> 

Right now it's not the priority. @AquamarineDreams can reopen this issue if he wants to. The priority is to make simple fade work now.

**Comment by AquamarineDreams** [comment]
>@fast4x I feel, you've only implemented fade song feature or it was a misunderstanding!
We ( including me as well )asked crossfade as @AquamarineDreams said..gradual transition of songs i.e. last 10 seconds of one somg and first 10 seconds of next song fusioned together, with fading effect.

I understand your comment, I will reopen the ticket
