### ISSUE TITLE
Same song multiply in queue when play directly from an artist page

### ISSUE THREAD

**Issue by Violet26Mistral** [fast4x/RiMusic#1806]
### Steps to reproduce the bug

1. Go to an artist page 
2. Open the "View all" on the overview page or the "Songs" tab.
3. Play one of the songs from there and open the queue.

### Expected behavior

It supposed to load and play all of the artist songs in order according to the artist listed songs

### Actual behavior

It didn't load all songs and repeated 2-3 of the same available song in queue.

### Screenshots/Screen recordings

![Screenshot_20240508_151633](https://github.com/fast4x/RiMusic/assets/102679500/3dfdb6f4-8a55-4917-bd46-96c363f6c745)
![Screenshot_20240508_150510](https://github.com/fast4x/RiMusic/assets/102679500/e699e5b2-333e-40a3-81b9-675ab7d74166)

### RiMusic version

0.6.33

### Android version

Android 7.1.2

**Comment by fast4x** [comment]
Just fixed and available from version 0.6.34
