### ISSUE TITLE
[Feature]: hide monthly playlists in Library

### ISSUE THREAD

**Issue by Ao1Pointblank** [fast4x/RiMusic#1807]
### Description

In my opinion, the toggle to disable monthly playlists (within the Quick Picks settings tab) should also affect the visibility of monthly playlists in Library also

### Suggested Solution

It may also be better to move this toggle outside of the quick picks settings tab and relocate it to UI, since it would then be affecting more than just Quick Picks

**Comment by fast4x** [comment]
Implemented show/hide monthly playlists in library from ui settings
Available from version 0.6.34
