### ISSUE TITLE
App crashes when trying to play long playlist. (add options less 500)

### ISSUE THREAD

**Issue by Cszyn** [fast4x/RiMusic#1808]
### Steps to reproduce the bug

1. import long ass playlist from YouTube.
2. try to swipe up
3. crash.

### Expected behavior

App doesn't crash.

### Actual behavior

Crash.

### Screenshots/Screen recordings

https://youtu.be/t5FojJnb2Po

### Logs

Don't know how to

### RiMusic version

0.6.32

### Android version

Androd 10 - MEUI 12

**Comment by Cszyn** [comment]
https://music.youtube.com/playlist?list=PL0eDCKMqthS9KEArlbQZr8FqsGw5FWaRu&si=Th-a4AekiO8twFN2
here is the playlist link for reproduction

**Comment by Cszyn** [comment]
When the song is downloaded and play outside the original playlist, it just works fine
https://youtu.be/ZWBDuns2mSU

**Comment by fast4x** [comment]
It's a problem related device ram because it try to add in queue 2.917 songs.
Set queue limit ui settings Max songs in queue

**Comment by Cszyn** [comment]
Sorry for the late reply, I'm not logged in my phone. The limit is set to 500 but still crashes

**Comment by Cszyn** [comment]
Is there a way to lower it to 50-100?

**Comment by fast4x** [comment]
I'll implement it

**Comment by fast4x** [comment]
Added options less 500, available from version 0.6.35

**Comment by Cszyn** [comment]
Thank you so much
