### ISSUE TITLE
App crashes when selecting 9th song in artist's song list

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#1809]
### Steps to reproduce the bug

1. Open the app.

2. Navigate to the "Artists" section.

3. Select the artist "Artist XY".

4. Select "Songs - view all".

5. Scroll down to the 9th song in the list.

6. Attempt to select the 9th song.

### Expected behavior

The app should play the selected song.

### Actual behavior

Upon selecting the 9th song in the list, the app crashes abruptly, leading to an unexpected termination of the application.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/71184627/cc10ffc7-4239-4aef-b306-e9cd7d0f180d

### RiMusic version

0.6.33

### Android version

Android 13

**Comment by fast4x** [comment]
Reproduced, nice this bug compliments! 😜🥳

**Comment by dAtA-TRoN** [comment]
> Reproduced, nice this bug compliments! 😜🥳

Thank you Sir 😎. However, I must confess, to my embarrassment, that I described it a bit misleadingly: I should have written that the app crashes starting from the 9th song. I've checked a few more songs after the 9th, and yes, crashes occur repeatedly.

**Comment by fast4x** [comment]
You have helped me in nice mode, I've found bug immediately.

**Comment by dAtA-TRoN** [comment]
> You have helped me in nice mode, I've found bug immediately.

Your name says it all once again 🍸😏!

**Comment by fast4x** [comment]
Fixed, available from version 0.6.34
