### ISSUE TITLE
Play Next Option Does Not work

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#1811]
### Steps to reproduce the bug

1. Goto favourites
2. Play song
3. Swipe right
4. Click on play next button
5. Check queue

https://github.com/fast4x/RiMusic/assets/136909951/74934b9c-6048-4d61-8352-fe0027a8e9a2

### Expected behavior

It should be added as a play next in queue 

### Actual behavior

But nothing happens at all by clicking.

### RiMusic version

0.6.33

### Android version

Android 14

**Comment by aneesh1122** [comment]
That's not your 'play next' button. That's your 'add to queue' button. Songs get added at the end of your queue.

**Comment by aneesh1122** [comment]
> > That's not your 'play next' button. That's your 'add to queue' button. Songs get added at the end of your queue.
> 
> Oh but, Why would anybody need that option? Who wants to add a song below to thousands of songs if he clicks on favourites as a playlist? 
> 
> I have always seen this button as a play next option (biggest examples : jiosaavn /Spotify / gaana etc).
> Then In my opinion, it's useless for many including myself. Hahaha 
> 
> @fast4x i Request: please replace this button behaviour to play next. 
> ( If you feel that it would be a great step! ) 

There are times when people have like 10 songs in their queue and want to listen to a song after all the songs in the queue are over. I agree that people use 'play next' more so it should be preferred.

Anyways, I've requested for #1794 which will solve this issue of yours.

**Comment by fast4x** [comment]
Action isn't play next but enqueue... so it add to the end of list...

**Comment by aneesh1122** [comment]
> Action isn't play next but enqueue... so it add to the end of list...

'Play next' is often used so I think that action should be used for Play next.

**Comment by aneesh1122** [comment]
> So replace enqueue with play next action?

for the meanwhile, yes. Until you implement #1794 this is the best approach imo.

Could you also please make the swipe close automatically after selecting the action? It stays open and we have to close it manually.

**Comment by Vishcot** [comment]
> So replace enqueue with play next action?

Yes please,
i too feel play next is more often used! As mentioned by @aneesh1122 too!

**Comment by Vishcot** [comment]
> > So replace enqueue with play next action?
> 
> for the meanwhile, yes. Until you implement #1794 this is the best approach imo.
> 
> Could you also please make the swipe close automatically after selecting the action? It stays open and we have to close it manually.

This too i have requested earlier..
It should always be one swipe at a time!
If you can do this too. Will be appreciated 😬

**Comment by fast4x** [comment]
Replaced enqueue with play next, available from version 0.6.34

**Comment by aneesh1122** [comment]
> Replaced enqueue with play next, available from version 0.6.34

Did you mean 0.6.35?

0.6.34 is already out

**Comment by fast4x** [comment]
excuse me, you are right,

**Comment by fast4x** [comment]
Custom version ready for download https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by aneesh1122** [comment]
> Custom version ready for download https://github.com/fast4x/RiMusic/tree/master/customVersion

thanks man. working great.

could you please also implement auto closing of swipe after action button is selected? Swipe remains open even after selecting action button.

**Comment by fast4x** [comment]
for now not possible
