### ISSUE TITLE
Android Auto, listas de reproducción 

### ISSUE THREAD

**Issue by Baviera10** [fast4x/RiMusic#1814]
### Description

En Android Auto no se dispone de escucha de canciones en aleatorio, si paras el coche y vuelves a la misma lista, vuelve a empezar la reproducción desde la primera cancion. V0.6.33

### Suggested Solution

Incluir icono de aleatorio en la página de las listas de reproduccion

### Alternatives

Que en Android Auto se escuchen las canciones dd las listas de reproduccion siempre en aleatorio

### Additional Context

La aplicación es magnífica, felicidades!!

**Comment by fast4x** [comment]
It's just implemented, you can found it in Songs page...

**Comment by Baviera10** [comment]
Yo hablo de escuchar una lista de reproducción de aleatorio, no todas las
canciones

**Comment by fast4x** [comment]
i don't understand, explain better please

**Comment by Baviera10** [comment]
Cuando se usa la Apple en Android Auto y se quiere escuchar una lista de
reproducción concreta, no existe la posibilidad de poner las canciones de
la lista en aleatorio.
Eso es un problema porque quedas obligado a oír siempre las primeras
canciones de la lista de reproducción.

Mi propuesta es que se incorpore el botón de aleatorio cuando se selecciona
una lista o que, por defecto, se ponga automáticamente la reproducción en
aleatorio cuando se selecciona una lista de reproducción.

**Comment by fast4x** [comment]
Ahhh ok ok now I've understand
