### ISSUE TITLE
song Title glitch

### ISSUE THREAD

**Issue by Grevellia123** [fast4x/RiMusic#1815]
### Steps to reproduce the bug

Go to search, search Wicked (feat. Mori Calliope), Click the title.

### Expected behavior

The title shouldn't be a glitch

### Actual behavior

There should be no glitches

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/134467260/d43816e3-ca9a-409d-aa81-0abfc93f3ccc

### RiMusic version

0.6.33

### Android version

Android 12

### Additional information

Poco M3, Android 12, MIUI 14.0.2

**Comment by fast4x** [comment]
Fixed, available from version 0.6.35
