### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by teacupmaps** [fast4x/RiMusic#1820]
### Description

![Screenshot_20240510-191310_Firefox](https://github.com/fast4x/RiMusic/assets/158172547/33e47a3b-6a80-4e7f-999f-d964cd1ac7dc)

### Suggested Solution

is this "cached songs"?

**Comment by ikanakova** [comment]
Yes, cached songs are songs automatically downloaded to cache by listening to them.

**Comment by fast4x** [comment]
ahahahaha yes congs = songs... i'm sorry
