### ISSUE TITLE
Can no longer bookmark albums in new design

### ISSUE THREAD

**Issue by Carter0108** [fast4x/RiMusic#1822]
### Steps to reproduce the bug

Go to any album page and there's no longer an option of adding it to your library.

### Expected behavior

Option to add album.

### Actual behavior

No button anymore.

### RiMusic version

0.6.34

### Android version

Android 14

**Comment by chatinteligence** [comment]
That's right, the option to save in the albums section with the icon no longer appears. 
![image](https://github.com/fast4x/RiMusic/assets/147566193/91b7e62e-d67c-4152-ba8a-df3c7c6fac79)

**Comment by fast4x** [comment]
I'll fix soon

**Comment by fast4x** [comment]
Fixed, available from version 0.6.35.
Maybe i'll make a custom version

**Comment by fast4x** [comment]
Custom version ready for download https://github.com/fast4x/RiMusic/tree/master/customVersion
