### ISSUE TITLE
Error de Colores en General Modo Dinamico

### ISSUE THREAD

**Issue by chatinteligence** [fast4x/RiMusic#1823]
### Steps to reproduce the bug

Paso 1: Aplicar Modo Dinámico
Paso 2: Abrir cualquier música.
Paso 3: Cambiar entre músicas

Espero y nada mas sea un error no muy complejo.

### Expected behavior

Mejora en la parte de cambio de color por musica. :)

### Actual behavior

El comportamiento actual que realiza es que no cambia con respecto a los colores que debería, espero sea un error mínimo
, ya que en la versión anterior no lo realizaba , saludos.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/147566193/16d25953-0391-4cdc-b9b1-9478bb60b8a8

### RiMusic version

V0.6.34

### Android version

Android 14

### Additional information

Agradecería mucho sobre este error, saludos!

**Comment by fast4x** [comment]
set your type of background color in appearance 
![Screenshot_2024-05-11-01-21-13-513_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/d30240a5-c829-4b80-93bf-6538c9a2e329)

**Comment by aneesh1122** [comment]
> set your type of background color in appearance 
> ![Screenshot_2024-05-11-01-21-13-513_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/d30240a5-c829-4b80-93bf-6538c9a2e329)
> 
> 

When we set the theme as 'dynamic' it takes colour from the album of playing colour.

The background colour is set as 'Gradient background from the theme' and the theme is dynamic which means the background should change with every song.

What's happening in the above video is the background is not changing according to the song. It is stuck in the colour of the previous song. If you minimise and maximise the song the background is changed. Background should be changed immediately after the song is changed.

**Comment by fast4x** [comment]
set background from cover in appearance

**Comment by aneesh1122** [comment]
> set background from cover in appearance ![Screenshot_2024-05-11-07-35-43-561_it.fast4x.rimusic.jpg](https://private-user-images.githubusercontent.com/1484476/329756671-cc9a3926-caeb-406f-be13-2829ab6aec9b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDYzMjksIm5iZiI6MTcxNTQwNjAyOSwicGF0aCI6Ii8xNDg0NDc2LzMyOTc1NjY3MS1jYzlhMzkyNi1jYWViLTQwNmYtYmUxMy0yODI5YWI2YWVjOWIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDU0MDI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQ2OTgyZDNhYWE0ZmEyY2QxYmE3ZDdjZjAxZDQyNDQ0MzRmNDM2ZWI5OGNiN2MwYzU4ZjFhZTdjMDNlZDU5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BfIOI3COoSNer8ba_1gvpCkN8n-5ed4iqSoR7PW4lAc)

background changes with no problem when `background from cover` is chosen but I don't like the way RiMusic chooses color. It's too bright for me.

More information here #1827

**Comment by fast4x** [comment]
set background from cover in appearance I'm sorry, founded

**Comment by fast4x** [comment]
Fixed, available from version 0.6.34

**Comment by fast4x** [comment]
Custom version ready for download https://github.com/fast4x/RiMusic/tree/master/customVersion
