### ISSUE TITLE
Errors I noticed x,d

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1825]
### Steps to reproduce the bug

This time there are two bugs that I noticed that are impossible not to notice (I should be beta-testing at this rate).

### Expected behavior

The expected behavior should be that crossfade smoothly transitions between songs, and the gradient doesn't get stuck on the previous song.

### Actual behavior

The first one, more superficial:

1. Bug with the gradient color. In this first case, when switching songs with the gradient enabled, the album cover's color doesn't change correctly and remains stuck. It starts working correctly again when the player is minimized.The second case:
2. Crossfade isn't working properly. In this second case, crossfade isn't working as it should. Instead of smoothly transitioning to the next song, it stays stuck on the current song until it finishes. Additionally, on my phone (Redmi Note 10 Pro), it causes the app to crash for some time, and I have to close the application.
 
Having here the example of how many seconds the application has:

![Screenshot_2024-05-10-18-28-09-678_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/a29c9ff2-e33b-4f9d-ab63-431451aac3c7)

And here's the example of how it should look from Spotify (the app where the crossfade idea originated), along with the number of seconds of crossfade it has (6 seconds, fewer than in the Rimusic app).

![Screenshot_2024-05-10-19-39-56-265_com spotify music](https://github.com/fast4x/RiMusic/assets/159836335/ee599f5d-98ba-40d2-86e0-004cefc25bb4)

https://github.com/fast4x/RiMusic/assets/159836335/4d7fd2c4-35f4-4880-9709-7ee49f28d089

### Screenshots/Screen recordings

1. 
![Screenshot_2024-05-10-18-21-38-847_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/2e99512c-e38a-4028-aaad-57c4b21951d0)
![Screenshot_2024-05-10-18-21-44-319_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/db854050-fe91-4e59-84f4-2de8c063bb5b)
![Screenshot_2024-05-10-18-21-51-838_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/ec91b21a-454f-4fbf-96d4-5175ac34519c)

2. https://github.com/fast4x/RiMusic/assets/159836335/0250e214-f9c8-4fc0-9c1f-02f0e0e34d6e

### RiMusic version

0.6.34

### Android version

Android 13

### Additional information

The most significant error that concerns me is the one with crossfade. I don't understand why the app crashes. I hope it's not a fundamental code error but something easy to address. 

For now, I have these options disabled to prevent app crashes. I love the new features (customized colors, gradient, crossfade), and I hope they can work correctly with the right fixes.

**Comment by JeePopuwu** [comment]
I'm sorry, I didn't notice that the Spotify example was poorly cropped. Here it is in better display:

https://github.com/fast4x/RiMusic/assets/159836335/2fb9b554-c94b-4727-a757-b37e790cd0b1

**Comment by JeePopuwu** [comment]
I just noticed that the color bug isn't just in gradient mode, but in all modes. XD

![Screenshot_2024-05-10-20-51-16-260_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/3e9cd28f-8909-4a88-94e9-e15a83b8fdd1)
![Screenshot_2024-05-10-20-51-22-525_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/0946b608-67fd-4266-8688-2ce56bc14bfe)
![Screenshot_2024-05-10-20-51-55-386_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/59f310d0-485a-47bb-b0a0-03762e153884)

**Comment by AquamarineDreams** [comment]
Yeah... I also experienced these bugs.

https://github.com/fast4x/RiMusic/assets/140275860/08c50813-e62d-4afd-8314-8d384157c2ac

**Comment by AquamarineDreams** [comment]
Crossfade doesn't crash on my device though. I'm using a Redmi Note 12s

**Comment by JeePopuwu** [comment]
> Sin embargo, Crossfade no falla en mi dispositivo. Estoy usando un Redmi Note 12s

Why does misfortune chase after me? x,,,d

**Comment by AquamarineDreams** [comment]
Lol, that's unfortunate.

It doesn't crash, but it also isn't working properly. Instead of 'crossfading' (Idk, probably not a word), it just slowly mutes the next song. Kinda funny actually, I spent 5 minutes checking my earphones.

**Comment by JeePopuwu** [comment]
> Jajaja, eso es desafortunado.
> 
> No falla, pero tampoco funciona correctamente. En lugar de "fundido cruzado" (no sé, probablemente ni una palabra), simplemente silencia lentamente la siguiente canción. En realidad, es un poco gracioso, pasé 5 minutos revisando mis auriculares.

The function needs to be polished more.

**Comment by aneesh1122** [comment]
![Screenshot 2024-05-11 123620](https://github.com/fast4x/RiMusic/assets/45353488/1d7469ff-5656-464a-8470-c962626e900e)

@fast4x this is the visual representation of crossfade. what you have implemented is simple fading and even that is buggy.

**Comment by fast4x** [comment]
Great, at the moment i can not do better.

**Comment by JeePopuwu** [comment]
> Genial, de momento no puedo hacerlo mejor.

My doubts are, what are your difficulties in bringing the crossfade function, not knowing code makes me curious.

**Comment by JeePopuwu** [comment]
> Great, at the moment i can not do better.

I asked Copilot (an AI) to make a basic example of how to do crossfade in Kotlin. It said it's very simple and wouldn't work perfectly, but an example is better than nothing. (I admit I know nothing about programming but I want to help as much as I can)

import android.media.MediaPlayer

class CrossfadePlayer(private val songs: List<String>) {
    private var currentPlayer: MediaPlayer? = null
    private var nextPlayer: MediaPlayer? = null

    fun playSong(index: Int) {
        currentPlayer?.release()
        currentPlayer = MediaPlayer.create(context, songs[index])
        currentPlayer?.setOnCompletionListener {
            playNextSong((index + 1) % songs.size)
        }
        currentPlayer?.start()
        prepareNextPlayer((index + 1) % songs.size)
    }

    private fun playNextSong(index: Int) {
        currentPlayer = nextPlayer
        currentPlayer?.setOnCompletionListener {
            playNextSong((index + 1) % songs.size)
        }
        currentPlayer?.start()
        prepareNextPlayer((index + 1) % songs.size)
    }

    private fun prepareNextPlayer(index: Int) {
        nextPlayer?.release()
        nextPlayer = MediaPlayer.create(context, songs[index])
        nextPlayer?.setVolume(0f, 0f)
        currentPlayer?.setNextMediaPlayer(nextPlayer)
        nextPlayer?.setOnPreparedListener {
            it.start()
            it.setVolume(1f, 1f)
        }
    }
}

**Comment by fast4x** [comment]
ask Copilot about Exoplayer not Mediaplayer

**Comment by JeePopuwu** [comment]
That's what Copilot wrote, I think I copied it a bit wrong xD.

**Comment by JeePopuwu** [comment]
![IMG_20240511_081824](https://github.com/fast4x/RiMusic/assets/159836335/495f0b25-d78b-4b06-9d4b-4a2dd8684bef)
![Screenshot_2024-05-11-08-17-45-227_com android chrome](https://github.com/fast4x/RiMusic/assets/159836335/87c02d7f-8b6a-48fa-9875-d283ffa8ebec)
![Screenshot_2024-05-11-08-17-50-373_com android chrome](https://github.com/fast4x/RiMusic/assets/159836335/81a2b287-07ff-426e-bfa0-38346b2bdd4b)

**Comment by fast4x** [comment]
in theory it is simple but in practice...

**Comment by JeePopuwu** [comment]
> en teoría es sencillo pero en la práctica...

Don't worry, there's no rush to bring the crossfade, for now, focus on the bugs that are there, I think that's enough. And thanks for really being so attentive to everything.

**Comment by fast4x** [comment]
Fixed background and gradients

**Comment by AquamarineDreams** [comment]
https://media.tenor.com/g16jQZqbvWoAAAAM/yippee-happy.gif

**Comment by AquamarineDreams** [comment]
![yippee-happy](https://github.com/fast4x/RiMusic/assets/140275860/2355f83a-c0bd-4553-b953-d86864277dfd)

**Comment by JeePopuwu** [comment]
> Fondo fijo y degradados.

Provide another example of how the AI would seemingly attempt to implement it.

![Screenshot_2024-05-11-14-35-39-914_com android chrome](https://github.com/fast4x/RiMusic/assets/159836335/ab6af061-0002-44c4-9121-a601f85d9656)
![Screenshot_2024-05-11-14-35-47-597_com android chrome](https://github.com/fast4x/RiMusic/assets/159836335/a56cb1dd-dde7-42e6-a613-1d7fc9f486ff)
![Screenshot_2024-05-11-14-35-55-038_com android chrome](https://github.com/fast4x/RiMusic/assets/159836335/deef3e64-7e08-4b4e-ae24-fe57d1727aa2)
![Screenshot_2024-05-11-14-36-03-277_com android chrome](https://github.com/fast4x/RiMusic/assets/159836335/40dd098c-4a9f-4bd6-914c-e2519555e626)

Don't take it too seriously, in fact, I feel like I'm bothering you with so much insistence on the crossfade x,DI'll stop bothering now.

**Comment by fast4x** [comment]
Custom version ready for download https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by AquamarineDreams** [comment]
![IMG_20240512_114303](https://github.com/fast4x/RiMusic/assets/140275860/82b21fc8-d43b-4156-8d3b-52c139dff706)

That's awesome, the gradients are way better now, and there are no glitched white colors like before.

**Comment by aneesh1122** [comment]
> ![IMG_20240512_114303](https://github.com/fast4x/RiMusic/assets/140275860/82b21fc8-d43b-4156-8d3b-52c139dff706)
> 
> That's awesome, the gradients are way better now, and there are no glitched white colors like before.

What's your theme and background?

**Comment by AquamarineDreams** [comment]
> > ![IMG_20240512_114303](https://private-user-images.githubusercontent.com/140275860/329857948-82b21fc8-d43b-4156-8d3b-52c139dff706.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjYxNDgsIm5iZiI6MTcxNTUyNTg0OCwicGF0aCI6Ii8xNDAyNzU4NjAvMzI5ODU3OTQ4LTgyYjIxZmM4LWQ0M2ItNDE1Ni04ZDNiLTUyYzEzOWRmZjcwNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxNDU3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTkwZThlY2RmZGY0ZTY1ODVjOWVmMWJiOGMzYWUyNjE2OWVkODMxMGFiYzdmY2IwMTE4MThlNGQ5MWRhZGM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V-rdtn3LaYR5tw6xQEcKGwBTxzZSRrAHHwLbVio5CRo)
> > That's awesome, the gradients are way better now, and there are no glitched white colors like before.
> 
> What's your theme and background?

Dynamic theme, and gradient from theme

**Comment by AquamarineDreams** [comment]
But, if you choose dynamic and gradient in the cover, you can get absolutely beautiful backgrounds depending on the song.

![IMG_20240512_115709](https://github.com/fast4x/RiMusic/assets/140275860/f3478693-c985-47c2-889e-2adc579ac814)

**Comment by AquamarineDreams** [comment]
Not all songs though, unfortunately

![IMG_20240512_120106](https://github.com/fast4x/RiMusic/assets/140275860/2aba9449-912c-4a75-b27f-bdf3293d9ce6)

**Comment by aneesh1122** [comment]
> > What's your theme and background?
> 
> Dynamic theme, and gradient from theme

What's your theme mode?

While you're checking that, restart your app and check if you are still getting black as upper gradient

**Comment by AquamarineDreams** [comment]
> What's your theme mode?
> 
> While you're checking that, restart your app and check if you are still getting black as upper gradient

Dark theme mode. Restarted the app, and now is a light shade of gray.

![Screenshot_2024-05-12-12-10-53-949_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/140275860/cd80dc36-604e-4a98-934d-3b0f182c8650)

Honestly I preferred the black as upper gradient, but it doesn't bother me at all. I'll probably use the gradient from cover, instead of gradient from theme, anyway. I really liked the effect it gives in the background of certain songs.

**Comment by aneesh1122** [comment]
> Dark theme mode. Restarted the app, and now is a light shade of gray.\n\n

Yeah it's buggy as hell. 

If you use 'pitch black' or any other black based theme, there won't be any background at all no matter what background you choose. 

I'm not getting the background gradient in my 'on device' songs

![Screenshot_2024-05-12-21-01-17-033_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/45353488/d25d44a8-f405-4238-a83c-16212ccfb477)

This is online streaming

![Screenshot_2024-05-12-21-01-33-995_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/45353488/7cf37f47-34ee-4f3f-a82f-89c9d797ffcf)

This is my 'on device' song.

Despite having the same album cover there are differences in the background.

There are bugs but if I report every background bug, fast4x will waste his whole weekend fixing them.

**Comment by aneesh1122** [comment]
> I'll probably use the gradient from cover, instead of gradient from theme, anyway. I really liked the effect it gives in the background of certain songs.

I'm using that as well but I also have to tolerate that greyish background in the whole interface.

![Screenshot_2024-05-12-21-09-50-698_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/387bb98e-dc6c-41fd-92bc-b4d01585eee0)

Only if there was a way to have this pure black.

If I use 'pitch black' I won't have the player background.

**Comment by AquamarineDreams** [comment]
> There are bugs but if I report every background bug, fast4x will waste his whole weekend fixing them.

Fr; the changes are great, the gradient and 'crossfade' (just 'fade' in the moment), are really good additions to the app. But, unfortunately, there are plenty of bugs with them, and, with only one person developing the app, means that either the app will take a long time to be polished, or the developer will take longer to add new stuff to it, or both.

Unfortunately, there isn't much that can be done to help with that. We need to deal with it.
