### ISSUE TITLE
Random Songs in favorites list has a Bug

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#1826]
### Steps to reproduce the bug

1. Goto favourites 
2. The list will already be well shuffled.
3. But after random actions will get shuffle again. Not everytime but randomly by clicks. 
4. Sometimes on different songs plays, sometimes swiping mini player or going to player screen.

https://github.com/fast4x/RiMusic/assets/136909951/d34ab363-395e-42d8-8678-395d2a287e0f

### Expected behavior

It should only randomly shuffled when we enter in the playlist or favourites tab..

### Actual behavior

It shuffles songs randomly by any action ( not showing a pattern )

### RiMusic version

0.6.34

### Android version

Android 14

**Comment by fast4x** [comment]
Not repriduced, shuffle occur everytime access favorites not on action play or other action.

**Comment by Vishcot** [comment]
> Not repriduced, shuffle occur everytime access favorites not on action play or other action.

Check this. 

Even after the list is loaded, when we click a song..it shuffles again.

https://github.com/fast4x/RiMusic/assets/136909951/6660ed05-7803-4d1a-9f44-fb962a79688d

**Comment by Cszyn** [comment]
> > Not repriduced, shuffle occur everytime access favorites not on action play or other action.
> 
> Check this.
> 
> Even after the list is loaded, when we click a song..it shuffles again.
> screen-20240511-225555_1.mp4

![MuMuPlayer_MdaM7r1pVR](https://github.com/fast4x/RiMusic/assets/147027531/bb771784-ce66-4e20-a023-65ce6aef2dcd)

Try to toggle that off

**Comment by Cszyn** [comment]
> > > Not repriduced, shuffle occur everytime access favorites not on action play or other action.
> > 
> > 
> > Check this.
> > Even after the list is loaded, when we click a song..it shuffles again.
> > screen-20240511-225555_1.mp4
> 
> ![MuMuPlayer_MdaM7r1pVR](https://private-user-images.githubusercontent.com/147027531/329808721-bb771784-ce66-4e20-a023-65ce6aef2dcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTUxOTAsIm5iZiI6MTcxNTQ1NDg5MCwicGF0aCI6Ii8xNDcwMjc1MzEvMzI5ODA4NzIxLWJiNzcxNzg0LWNlNjYtNGUyMC1hMDIzLTY1Y2U2YWVmMmRjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxOTE0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzY1NGRlYTBlN2UxOWRhZmVhMDZlNjQ0Zjc0NTg1ZjQyYTU1OTYxNDc0YzY4NWJmYjkxZTQ0OWMzZjc5MTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4J_UZwT-S-QBFIbEYwSSV54gHb5XsLUOKW6H7lF60Sw)
> 
> Try to toggle that off

![MuMuPlayer_VVc1c3Hwkt](https://github.com/fast4x/RiMusic/assets/147027531/065e4653-d894-49af-9209-8f6d0ca152ff)

Hold that bottom down and an info tip will pop up (very clever)

**Comment by Vishcot** [comment]
> > > Not repriduced, shuffle occur everytime access favorites not on action play or other action.
> > 
> > Check this.
> > 
> > Even after the list is loaded, when we click a song..it shuffles again.
> > screen-20240511-225555_1.mp4
> 
> ![MuMuPlayer_MdaM7r1pVR](https://github.com/fast4x/RiMusic/assets/147027531/bb771784-ce66-4e20-a023-65ce6aef2dcd)
> 
> Try to toggle that off

Why would i do so ? 
I asked about that feature haha! 

It's just shuffling songs two times
first when we open the favorites and second time when any song is clicked.
I only want, that it gets shuffled only when we enter into a playlist or favourites.

@fast4x

**Comment by Vishcot** [comment]
@fast4x it is a bug! Whenever i open playlist it comes shuffled then why it shuffles again when i play another song, same happens again when i come back from settings page! 
It should only be shuffled once i open favourites, not again when i play a song..
Isn't it so?

https://github.com/fast4x/RiMusic/assets/136909951/e23ae52a-d1b4-445e-9943-c1e878d93b59

**Comment by Vishcot** [comment]
> @fast4x it is a bug! Whenever i open playlist it comes shuffled then why it shuffles again when i play another song, same happens again when i come back from settings page! It should only be shuffled once i open favourites, not again when i play a song.. Isn't it so?
> 
>  screen-20240516-201854_1715870959803.mp4

That non animated part of the video is actually clicking a song.
Click a song and it just cut and shuffle itself again.

**Comment by fast4x** [comment]
Okay, don’t be mad, I’ll look ahead. :)

**Comment by fast4x** [comment]
Improved in new layout design, available from version 0.6.36
