### ISSUE TITLE
Wrong 'Gradient background from cover'

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1827]
### Steps to reproduce the bug

In background colors, choose `Gradient background from cover`

### Expected behavior

![Screenshot_2024-05-11-10-27-37-183_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/45353488/60cda450-708e-4641-9a2d-f02945e7b89a)

The gradient should go from album color to `Background 3` color

### Actual behavior

![Screenshot_2024-05-11-10-09-59-867_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/45353488/d80a82b3-3f42-41f4-9960-741decbc80a2)
I don't know how app is choosing color based on cover. It should be green

### RiMusic version

0.6.34

### Android version

Android 13

### Additional information

My custom theme settings
![Screenshot_2024-05-11-10-37-53-450_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/4e339548-a749-4f9e-95a6-bbef871b1102)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.34

**Comment by fast4x** [comment]
Fixed, available from version 0.6.35

**Comment by fast4x** [comment]
Custom version ready for download https://github.com/fast4x/RiMusic/tree/master/customVersion
