### ISSUE TITLE
Playback fades out to silence after a couple of songs

### ISSUE THREAD

**Issue by Carter0108** [fast4x/RiMusic#1833]
### Steps to reproduce the bug

Start a radio, listen to a couple of songs and then at the start of the next track it'll fade out

### Expected behavior

Playlists should keep playing

### Actual behavior

Song fades out and then won't start again until skipping forward or back a song.

### RiMusic version

0.6.34

### Android version

Android 14

**Comment by aneesh1122** [comment]
Disable crossfade. It's buggy right now.

**Comment by MrAshish74** [comment]
> ### Steps to reproduce the bug
> Start a radio, listen to a couple of songs and then at the start of the next track it'll fade out
> 
> ### Expected behavior
> Playlists should keep playing
> 
> ### Actual behavior
> Song fades out and then won't start again until skipping forward or back a song.
> 
> ### Screenshots/Screen recordings
> _No response_
> 
> ### Logs
> _No response_
> 
> ### RiMusic version
> 0.6.34
> 
> ### Android version
> Android 14
> 
> ### Additional information
> _No response_
Same Happening With Me

**Comment by fast4x** [comment]
Custom version ready for download https://github.com/fast4x/RiMusic/tree/master/customVersion
