### ISSUE TITLE
[Feature]: Blurred background

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1834]
### Description

Something like this

![player](https://github.com/fast4x/RiMusic/assets/45353488/e3e5a635-cfe5-4e67-b9d2-dc26df20e759)

and here's the lyrics page
![LYRICS](https://github.com/fast4x/RiMusic/assets/45353488/acf41cb8-c950-47a9-9260-a27c3f2376f7)

### Suggested Solution

1) Player
-take the album cover, stretch it to screen's ratio, blur it.
-put a stroke and outer glow around Album's cover

2) Lyrics
-put gradient blur to lyrics
-add a small glow to the active lyrics part

**Comment by dAtA-TRoN** [comment]
Mr. Fast4x, could you please make this a reality? I understand you may have turned down this idea before, but now that we have ample options for personalizing our player, this addition would complete the puzzle 🙏🏻.

It looks fresh, you have to admit.

**Comment by AquamarineDreams** [comment]
I would like this if you could enable it only at the lyrics, like yt music.

**Comment by JeePopuwu** [comment]
I would love to see something like that, I have something similar on my lock screen lol.

![Screenshot_2024-05-11-10-50-16-520_lockscreen](https://github.com/fast4x/RiMusic/assets/159836335/8ba2f8b9-b17e-434f-80ab-ebf0c6050b34)

**Comment by aneesh1122** [comment]
> I would love to see something like that, I have something similar on my lock screen lol.
> 
> ![Screenshot_2024-05-11-10-50-16-520_lockscreen](https://github.com/fast4x/RiMusic/assets/159836335/8ba2f8b9-b17e-434f-80ab-ebf0c6050b34)
> 

You have the screenshot of a song playing in apple music as your lockscreen?

**Comment by JeePopuwu** [comment]
> > Me encantaría ver algo así, tengo algo similar en mi pantalla de bloqueo jajaja.
> > ![Captura de pantalla_2024-05-11-10-50-16-520_lockscreen](https://private-user-images.githubusercontent.com/159836335/329798046-8ba2f8b9-b17e-434f-80ab-ebf0c6050b34.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDQwNjEsIm5iZiI6MTcxNTQ0Mzc2MSwicGF0aCI6Ii8xNTk4MzYzMzUvMzI5Nzk4MDQ2LThiYTJmOGI5LWIxN2UtNDM0Zi04MGFiLWViZjBjNjA1MGIzNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxNjA5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTdmZTVmOWJiYjBjMjQ2YjFlMjljNGM3NTM3MmVjZmViYTQ3MTkzNTdhMDJmZjdjMWVkZDUyNWRjMWE1ZTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SaOZdAwvOMmJytkFhvEqq20sUh90jgKgtxRLBAletnE)
> 
> ¿Tienes la captura de pantalla de una canción que se reproduce en Apple Music como pantalla de bloqueo?

No, what I have is that I have the lock screen configured so that when I touch its icon, it enlarges.

Like iOS, it's because of a Xiaomi theme.

![Screenshot_2024-05-11-11-19-47-104_lockscreen](https://github.com/fast4x/RiMusic/assets/159836335/dfd6a342-00da-4ce1-81d5-e188a97e8539)

**Comment by aneesh1122** [comment]
> > > Me encantaría ver algo así, tengo algo similar en mi pantalla de bloqueo jajaja.
> > > ![Captura de pantalla_2024-05-11-10-50-16-520_lockscreen](https://private-user-images.githubusercontent.com/159836335/329798046-8ba2f8b9-b17e-434f-80ab-ebf0c6050b34.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDQwNjEsIm5iZiI6MTcxNTQ0Mzc2MSwicGF0aCI6Ii8xNTk4MzYzMzUvMzI5Nzk4MDQ2LThiYTJmOGI5LWIxN2UtNDM0Zi04MGFiLWViZjBjNjA1MGIzNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxNjA5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTdmZTVmOWJiYjBjMjQ2YjFlMjljNGM3NTM3MmVjZmViYTQ3MTkzNTdhMDJmZjdjMWVkZDUyNWRjMWE1ZTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SaOZdAwvOMmJytkFhvEqq20sUh90jgKgtxRLBAletnE)
> > 
> > ¿Tienes la captura de pantalla de una canción que se reproduce en Apple Music como pantalla de bloqueo?
> 
> No, what I have is that I have the lock screen configured so that when I touch its icon, it enlarges.
> 
> Like iOS, it's because of a Xiaomi theme.
> 
> ![Screenshot_2024-05-11-11-19-47-104_lockscreen](https://github.com/fast4x/RiMusic/assets/159836335/dfd6a342-00da-4ce1-81d5-e188a97e8539)
> 

I don't understand. I need a video 😅

**Comment by JeePopuwu** [comment]
> > > > Me encantaría ver algo así, tengo algo similar en mi pantalla de bloqueo jajaja.
> > > > ![Captura de pantalla_2024-05-11-10-50-16-520_lockscreen](https://private-user-images.githubusercontent.com/159836335/329798046-8ba2f8b9-b17e-434f-80ab-ebf0c6050b34.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDQwNjEsIm5iZiI6MTcxNTQ0Mzc2MSwicGF0aCI6Ii8xNTk4MzYzMzUvMzI5Nzk4MDQ2LThiYTJmOGI5LWIxN2UtNDM0Zi04MGFiLWViZjBjNjA1MGIzNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxNjA5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTdmZTVmOWJiYjBjMjQ2YjFlMjljNGM3NTM3MmVjZmViYTQ3MTkzNTdhMDJmZjdjMWVkZDUyNWRjMWE1ZTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SaOZdAwvOMmJytkFhvEqq20sUh90jgKgtxRLBAletnE)
> > > 
> > > 
> > > ¿Tienes la captura de pantalla de una canción que se reproduce en Apple Music como pantalla de bloqueo?
> > 
> > 
> > No, lo que tengo es que tengo configurada la pantalla de bloqueo para que al tocar su icono se agrande.
> > Al igual que iOS, se debe a un tema de Xiaomi.
> > ![Captura de pantalla_2024-05-11-11-19-47-104_lockscreen](https://private-user-images.githubusercontent.com/159836335/329799732-dfd6a342-00da-4ce1-81d5-e188a97e8539.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTMwODcsIm5iZiI6MTcxNTQ1Mjc4NywicGF0aCI6Ii8xNTk4MzYzMzUvMzI5Nzk5NzMyLWRmZDZhMzQyLTAwZGEtNGNlMS04MWQ1LWUxODhhOTdlODUzOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxODM5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmVhMTVkZDQ0ODExNTE5MzlmNDgzNDkwNGYwYmFkZDNiZjhjM2Y4MDU3M2E3ZmE4NjQ1ZDFlOTg2NDE1N2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c_WkaFpjVoeLdExe0u8qqCBMoGb_E6BduuBpf2kvyCA)
> 
> No entiendo. Necesito un vídeo 😅

Basically, I just touched the cover and it switches to full screen, it's very useful and quite aesthetic.


https://github.com/fast4x/RiMusic/assets/159836335/1b1922e1-ecd9-46dd-a12f-cb4af6dcfbbb

**Comment by aneesh1122** [comment]
> > > > > Me encantaría ver algo así, tengo algo similar en mi pantalla de bloqueo jajaja.
> > > > > ![Captura de pantalla_2024-05-11-10-50-16-520_lockscreen](https://private-user-images.githubusercontent.com/159836335/329798046-8ba2f8b9-b17e-434f-80ab-ebf0c6050b34.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDQwNjEsIm5iZiI6MTcxNTQ0Mzc2MSwicGF0aCI6Ii8xNTk4MzYzMzUvMzI5Nzk4MDQ2LThiYTJmOGI5LWIxN2UtNDM0Zi04MGFiLWViZjBjNjA1MGIzNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxNjA5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTdmZTVmOWJiYjBjMjQ2YjFlMjljNGM3NTM3MmVjZmViYTQ3MTkzNTdhMDJmZjdjMWVkZDUyNWRjMWE1ZTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SaOZdAwvOMmJytkFhvEqq20sUh90jgKgtxRLBAletnE)
> > > > 
> > > > 
> > > > ¿Tienes la captura de pantalla de una canción que se reproduce en Apple Music como pantalla de bloqueo?
> > > 
> > > 
> > > No, lo que tengo es que tengo configurada la pantalla de bloqueo para que al tocar su icono se agrande.
> > > Al igual que iOS, se debe a un tema de Xiaomi.
> > > ![Captura de pantalla_2024-05-11-11-19-47-104_lockscreen](https://private-user-images.githubusercontent.com/159836335/329799732-dfd6a342-00da-4ce1-81d5-e188a97e8539.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTMwODcsIm5iZiI6MTcxNTQ1Mjc4NywicGF0aCI6Ii8xNTk4MzYzMzUvMzI5Nzk5NzMyLWRmZDZhMzQyLTAwZGEtNGNlMS04MWQ1LWUxODhhOTdlODUzOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxODM5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmVhMTVkZDQ0ODExNTE5MzlmNDgzNDkwNGYwYmFkZDNiZjhjM2Y4MDU3M2E3ZmE4NjQ1ZDFlOTg2NDE1N2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c_WkaFpjVoeLdExe0u8qqCBMoGb_E6BduuBpf2kvyCA)
> > 
> > No entiendo. Necesito un vídeo 😅
> 
> Basically, I just touched the cover and it switches to full screen, it's very useful and quite aesthetic.
> 
> 
> https://github.com/fast4x/RiMusic/assets/159836335/1b1922e1-ecd9-46dd-a12f-cb4af6dcfbbb
> 
> 

I've been using xiaomi mobile for almost 3 years and I didn't know you could customize the lock screen.

What theme are you using? I just found kittyUI v4. You're looking very different

**Comment by JeePopuwu** [comment]
Unfortunately, the blocking issue I had has already been deleted.

![Uploading Screenshot_2024-05-11-14-30-40-473_com.android.thememanager.png…]()

**Comment by fast4x** [comment]
![Screenshot_20240516_090610](https://github.com/fast4x/RiMusic/assets/1484476/3f3d4c0b-4c33-443a-b3f6-6b4f61f2ac36)

**Comment by aneesh1122** [comment]
> ![Screenshot_20240516_090610](https://private-user-images.githubusercontent.com/1484476/331083431-3f3d4c0b-4c33-443a-b3f6-6b4f61f2ac36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDcyMzQsIm5iZiI6MTcxNTg0NjkzNCwicGF0aCI6Ii8xNDg0NDc2LzMzMTA4MzQzMS0zZjNkNGMwYi00YzMzLTQ0M2EtYjNmNi02YjRmNjFmMmFjMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMDgwODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjY4NGI4OGZhZTFkNGJmMjQxYTRlNmQ2MjdiMjQ2OGY5Yzk0YzA3ZWI0ZWVmYjZkOTk4ODg1NTkxNmYyOTg0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gsT4uOLKhh4CqNyHlJ5H9AK-zRBENsS7EgZ85hn7Acc)

okay, first of all. Nice work there around control buttons.  That shadow effect around them looks great.

Wish you had done the same to album cover too.
![2024-05-16 13_22_38-331084039-f2b55e87-f55c-4398-b1ee-456a2f53bbea png ‎- Photos](https://github.com/fast4x/RiMusic/assets/45353488/23851c43-9f8a-4399-a14a-7e88d107420e)
See, this have irregular spreading shadow around them

![2024-05-16 13_22_56-331084039-f2b55e87-f55c-4398-b1ee-456a2f53bbea png ‎- Photos](https://github.com/fast4x/RiMusic/assets/45353488/e5c6e910-f92f-4887-9c27-3dc4783a53e6)
whereas the shadow around the cover is uniform.

Now, the background in your preview is a simple shade of uniform pink. I suggested to use the cover image, blur it and then use that as background.

**Comment by fast4x** [comment]
Done

https://github.com/fast4x/RiMusic/assets/1484476/3567ac7c-e7a6-4362-89ce-9c533697752a

**Comment by fast4x** [comment]
Improved player and background mode, available from version 0.6.35

**Comment by aneesh1122** [comment]
> Done
> 
>  Screen_recording_20240516_104558.mp4

Pls see this. Pls do something like this. Please use album cover and blur it and use it as background
![arewgaer](https://github.com/fast4x/RiMusic/assets/45353488/fd454046-3fc1-4deb-8682-67937e7f7759)

**Comment by fast4x** [comment]
Nice but actually blur isn't compatible with all devices, wait

**Comment by aneesh1122** [comment]
> Nice but actually blur isn't compatible with all devices, wait

Well, they can always use other backgrounds 😅

**Comment by fast4x** [comment]
I think we have... found solution for all devices... yeah!

https://github.com/fast4x/RiMusic/assets/1484476/66fa5e30-0301-4dae-ad8f-78261278c534

**Comment by fast4x** [comment]
Friday

**Comment by AquamarineDreams** [comment]
@fast4x Is this the same as #1843?

**Comment by aneesh1122** [comment]
> @fast4x Is this the same as #1843?

Entirely different things.

Here the cover is blurred and used.

There a moving gradient is made using colors from the album.

**Comment by AquamarineDreams** [comment]
Ok, got it 🙃

**Comment by aneesh1122** [comment]
Hey @fast4x , Saw this in an another issue so I thought of pointing it out since you'll publish the new update so it it's easy fix you can do it before you publish.

![vlcsnap-2024-05-17-12h36m15s926](https://github.com/fast4x/RiMusic/assets/45353488/4ea46f81-309b-4d9b-b563-8f616c6e2f46)

**Comment by NikunjKhangwal** [comment]
> No, what I have is that I have the lock screen configured so that when I touch its icon, it enlarges.
> 
> Like iOS, it's because of a Xiaomi theme.
> 
> ![Screenshot_2024-05-11-11-19-47-104_lockscreen](https://private-user-images.githubusercontent.com/159836335/329799732-dfd6a342-00da-4ce1-81d5-e188a97e8539.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMDU3NTYsIm5iZiI6MTcxNjAwNTQ1NiwicGF0aCI6Ii8xNTk4MzYzMzUvMzI5Nzk5NzMyLWRmZDZhMzQyLTAwZGEtNGNlMS04MWQ1LWUxODhhOTdlODUzOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwNDEwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDBmZDQxMTZlMTM3YmU4MTJmN2U1MGMyNTUwZjJiNDg1NGMzZjYxODZjNGQ5ZjlmODg4NjllYTk5OWI0MWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bnf8U3JNnf7at4ZZUKM4RC4eyQTSPQ1rbje4_eAHHsE)

What themes and components are you using? Need names of all of them.

**Comment by aneesh1122** [comment]
>  > No, what I have is that I have the lock screen configured so that when I touch its icon, it enlarges.
> > 
> > Like iOS, it's because of a Xiaomi theme.
> > 
> > ![Screenshot_2024-05-11-11-19-47-104_lockscreen](https://private-user-images.githubusercontent.com/159836335/329799732-dfd6a342-00da-4ce1-81d5-e188a97e8539.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMDU3NTYsIm5iZiI6MTcxNjAwNTQ1NiwicGF0aCI6Ii8xNTk4MzYzMzUvMzI5Nzk5NzMyLWRmZDZhMzQyLTAwZGEtNGNlMS04MWQ1LWUxODhhOTdlODUzOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwNDEwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDBmZDQxMTZlMTM3YmU4MTJmN2U1MGMyNTUwZjJiNDg1NGMzZjYxODZjNGQ5ZjlmODg4NjllYTk5OWI0MWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bnf8U3JNnf7at4ZZUKM4RC4eyQTSPQ1rbje4_eAHHsE)
> 
> What themes and components are you using? Need names of all of them.

Haiperios

**Comment by NikunjKhangwal** [comment]
> Haiperios

Thanks

**Comment by NikunjKhangwal** [comment]
The cover art doesn't appear for me. Are you using stock Mi music player?

**Comment by aneesh1122** [comment]
> The cover art doesn't appear for me. Are you using stock Mi music player?

well...I didn't have to do anything. It appeared just like that.

**Comment by NikunjKhangwal** [comment]
Ok. I'm on ancient device so that might be the case. But either way it'll be helpful later.
