### ISSUE TITLE
[Feature]: Have a rich presence for discord for songs. 

### ISSUE THREAD

**Issue by ZandrexV** [fast4x/RiMusic#1836]
### Description

It would be great if they put the option to see what you are listening to in the app like Spotify in Discord. (It doesn't have to be like this literally but something similar would be great.)
![20240511_113435](https://github.com/fast4x/RiMusic/assets/162504062/2cdaa060-d432-4145-8fff-e97f55922704)

### Suggested Solution

That, when you log into Discord in the RiMusic app, each song you play appears as a rich presence in Discord (that is, what you are listening to).

### Alternatives

(You can use KizzyRPC or another alternative to do it)

### Additional Context

I hope this help is important to you and will be added to the application soon!

**Comment by aneesh1122** [comment]
I don't think any kind of login is planned

**Comment by ZandrexV** [comment]
> No creo que esté previsto ningún tipo de inicio de sesión.

I meant that you can access RiMusic with a discord account.

**Comment by JeePopuwu** [comment]
> > No creo que esté previsto ningún tipo de inicio de sesión.
> 
> Quise decir que puedes acceder a RiMusic con una cuenta de Discord.

So you would have to log in with an account, it's the same situation. Fast already mentioned not including accounts now or in the future, sadly.

**Comment by Cszyn** [comment]
I'm pretty sure that it can be done without login implementation, but I also don't see the point of it when there is no desktop version available

**Comment by Cszyn** [comment]
But if you want RPC on desktop, this might interest you https://github.com/th-ch/youtube-music
![YouTube_Music_kiRa3t0ENa](https://github.com/fast4x/RiMusic/assets/147027531/0c01806e-d837-40ae-99da-78e8a0aeed15)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.52

**Comment by JeePopuwu** [comment]
> Implementado, disponible a partir de la versión 0.6.52

how did you do it??

**Comment by fast4x** [comment]
> > Implementado, disponible a partir de la versión 0.6.52
> 
> how did you do it??


Send status, song title, artist name, it's first simple  implementation, next will be improved.
