### ISSUE TITLE
Cannot Favorite an Album

### ISSUE THREAD

**Issue by Juggalage** [fast4x/RiMusic#1837]
### Steps to reproduce the bug

1. Go to any Artist
2. Open any Album

### Expected behavior

Should be some way to favorite an album so it shows up on our favorite tab

### Actual behavior

There isn't

### Screenshots/Screen recordings

![Screenshot_20240511-102223](https://github.com/fast4x/RiMusic/assets/32726906/3cd16a7d-8973-46e7-8ea0-68f3ab4919d2)
![Screenshot_20240511-102218](https://github.com/fast4x/RiMusic/assets/32726906/09c2e739-b4da-4514-8d66-80c499114967)

### RiMusic version

0.6.34

### Android version

Android 14

**Comment by fast4x** [comment]
Fixed, available from version 0.6.35

**Comment by fast4x** [comment]
Custom version ready for download https://github.com/fast4x/RiMusic/tree/master/customVersion
