### ISSUE TITLE
Gradient/NoGradient background for cover bug for covers

### ISSUE THREAD

**Issue by ZandrexV** [fast4x/RiMusic#1838]
### Steps to reproduce the bug

1. Activate and go to any track with the "gradient background for cover" or the "background for cover".

### Expected behavior

That the theme resembles the cover of the song or at least that the lyrics or description of the song can be seen.

### Actual behavior

The background looks all white and the lyrics/details of the song also look white and nothing is noticeable.

### Screenshots/Screen recordings

![Screenshot_20240511_133440](https://github.com/fast4x/RiMusic/assets/162504062/b2d6b601-287f-4fa5-aec5-4d0a144e3529)
![Screenshot_20240511_133446](https://github.com/fast4x/RiMusic/assets/162504062/0bc5b601-6c9d-4a57-ae6d-c6fe0554fe44)
![Screenshot_20240511_133453](https://github.com/fast4x/RiMusic/assets/162504062/26ef4400-464e-4bf5-992b-3c1dee2c93a9)

### RiMusic version

V0.6.34

### Android version

Android 11 - Android 6.0

**Comment by dAtA-TRoN** [comment]
Duplicate #1827

**Comment by fast4x** [comment]
Fixed, available from version 0.6.35

**Comment by fast4x** [comment]
Custom version ready for download https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by dAtA-TRoN** [comment]
Tested. Could you make the colors in material you theme more pop? It's a little too reserved for my taste. And the gradient doesn't go deep enough in my opinion. It ends too soon.

![Screenshot_2024-05-12-12-36-35-30_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/36d9d415-1673-4a17-8922-161abfa3d77b)
