### ISSUE TITLE
Can't tranlate japanese text

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#184]
### Steps to reproduce the bug

Listen an japanese song
Tap the lirics button (or in my case tap the album cover)
Tap the translation button

### Expected behavior

Translate and show

### Actual behavior

Doesn't show the translation

### Screenshots/Screen recordings

![VideoCapture_20231207-092211](https://github.com/fast4x/RiMusic/assets/104271365/2d14d8aa-256b-48dd-b585-6cfa6547f32c)
![VideoCapture_20231207-092221](https://github.com/fast4x/RiMusic/assets/104271365/c2e3b389-99ce-47db-8b5a-f2f07c8375ce)

### RiMusic version

0.6.11

### Android version

Android 14 with OneUI 6

**Comment by fast4x** [comment]
ok, I check it
