### ISSUE TITLE
Main page playlists bug

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#1840]
### Steps to reproduce the bug

When you open the main page, the monthly playlists are still as duplicated.
Also, the playlists header notes that there are 4 playlists, although there are actually 2 (are the monthly playlists counted? If so, then what's the point, since they're in a separate category above...). 
Also, what is the point of the two “Playlists” bars? Clicking on both hides your own playlists. Maybe it makes sense to keep just one?

![Screenshot_20240511_191105](https://github.com/fast4x/RiMusic/assets/76595855/3e5c8d4f-02ce-425a-9283-5a3fa0cf3ce8)

### Expected behavior

Monthly playlists are not duplicated, the number of your own playlists is displayed correctly, and one “Playlists” bar should probably be removed.

### Actual behavior

I wrote about it above.

### RiMusic version

0.6ю34

### Android version

Android 13

**Comment by fast4x** [comment]
disable creation by settings for now

**Comment by KOLIWAN** [comment]
> disable creation by settings for now

Yeah I disabled, but the existing duplicate didn't disappear

**Comment by fast4x** [comment]
Yes, delete it manually

**Comment by KOLIWAN** [comment]
> Yes, delete it manually

![lIfBXH](https://github.com/fast4x/RiMusic/assets/76595855/cedb7bdd-3bcd-4b82-a7dd-02650b6a5977)

**Comment by fast4x** [comment]
I've added a little fix, available from version 0.6.35
