### ISSUE TITLE
Dynamic theme malfunction

### ISSUE THREAD

**Issue by Cszyn** [fast4x/RiMusic#1841]
### Steps to reproduce the bug

1. Use tablet UI
2. Enable Dynamic theme
3. Select Background from theme in Background colors
4. Select wavy circle for play button
5. Encounter issue

### Expected behavior

Backgroud shoud countiuessly sync

### Actual behavior

Backwards, Play, Forwards, and bottom UI stay the same

### Screenshots/Screen recordings

https://youtu.be/XRfgqxsKBDs

### Logs

Can't because emulator

### RiMusic version

0.6.34

### Android version

Android 12 - MUMU player

**Comment by Cszyn** [comment]
Updated with a YouTube link

**Comment by Cszyn** [comment]
It was a duplicate

**Comment by Cszyn** [comment]
Never mind, just very similar to the issue with gradient backgrounds

**Comment by Cszyn** [comment]
![MuMuPlayer_y5LWtQJcix](https://github.com/fast4x/RiMusic/assets/147027531/c2d99bd6-52c9-4f2d-a275-29d062d760f2)

Turns out its not just the tablet ui

**Comment by fast4x** [comment]
Fixed, available from version 0.6.35

**Comment by fast4x** [comment]
Custom version ready for download https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Cszyn** [comment]
However, issue with #1827 does appear to be fixed
![BEn1lwocFK](https://github.com/fast4x/RiMusic/assets/147027531/8216f6e7-1bdd-478f-a36d-2495c9249cb3)

but the wavy circle still acts malfunctions

**Comment by aneesh1122** [comment]
> However, issue with #1827 does appear to be fixed ![BEn1lwocFK](https://private-user-images.githubusercontent.com/147027531/329843507-8216f6e7-1bdd-478f-a36d-2495c9249cb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTM3MDMsIm5iZiI6MTcxNTUxMzQwMywicGF0aCI6Ii8xNDcwMjc1MzEvMzI5ODQzNTA3LTgyMTZmNmU3LTFiZGQtNDc4Zi1hMzZkLTI0OTVjOTI0OWNiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMTMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzAzNWViZDVhMTc2NjljYjM3MmUzYzczMGM4OTY0NjIzZTk1MjQwZTRlMzdhZDY1ZWNhYzYyZDRiMDk2NjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yYvD85meoX0FARIASwM7qTHZear9c6G8dE_7DVKcLQU)
> 
> but the wavy circle still malfunctions

in these 2 screenshots I don't see wavy circle malfunctioning. The background is always consistent with cover image now.

**Comment by Cszyn** [comment]
> > However, issue with #1827 does appear to be fixed ![BEn1lwocFK](https://private-user-images.githubusercontent.com/147027531/329843507-8216f6e7-1bdd-478f-a36d-2495c9249cb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTM3MDMsIm5iZiI6MTcxNTUxMzQwMywicGF0aCI6Ii8xNDcwMjc1MzEvMzI5ODQzNTA3LTgyMTZmNmU3LTFiZGQtNDc4Zi1hMzZkLTI0OTVjOTI0OWNiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMTMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzAzNWViZDVhMTc2NjljYjM3MmUzYzczMGM4OTY0NjIzZTk1MjQwZTRlMzdhZDY1ZWNhYzYyZDRiMDk2NjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yYvD85meoX0FARIASwM7qTHZear9c6G8dE_7DVKcLQU)
> > but the wavy circle still malfunctions
> 
> in these 2 screenshots I don't see wavy circle malfunctioning. The background is always consistent with cover image now.

I have not used the wavy circle before, did it always have the black square behind it ?
![floorp_y46FiZt6aL](https://github.com/fast4x/RiMusic/assets/147027531/545bf9a7-4b17-4065-a1f0-85ebe0117b4c)

**Comment by aneesh1122** [comment]
> > > However, issue with #1827 does appear to be fixed ![BEn1lwocFK](https://private-user-images.githubusercontent.com/147027531/329843507-8216f6e7-1bdd-478f-a36d-2495c9249cb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTM3MDMsIm5iZiI6MTcxNTUxMzQwMywicGF0aCI6Ii8xNDcwMjc1MzEvMzI5ODQzNTA3LTgyMTZmNmU3LTFiZGQtNDc4Zi1hMzZkLTI0OTVjOTI0OWNiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMTMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzAzNWViZDVhMTc2NjljYjM3MmUzYzczMGM4OTY0NjIzZTk1MjQwZTRlMzdhZDY1ZWNhYzYyZDRiMDk2NjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yYvD85meoX0FARIASwM7qTHZear9c6G8dE_7DVKcLQU)
> > > but the wavy circle still malfunctions
> > 
> > 
> > in these 2 screenshots I don't see wavy circle malfunctioning. The background is always consistent with cover image now.
> 
> I have not used the wavy circle before, did it always have the black square behind it ? ![floorp_y46FiZt6aL](https://private-user-images.githubusercontent.com/147027531/329849212-545bf9a7-4b17-4065-a1f0-85ebe0117b4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTg5MTgsIm5iZiI6MTcxNTUxODYxOCwicGF0aCI6Ii8xNDcwMjc1MzEvMzI5ODQ5MjEyLTU0NWJmOWE3LTRiMTctNDA2NS1hMWYwLTg1ZWJlMDExN2I0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMjU2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGNiNmUwOGE4YzRlOGRlNGI3M2NiOWY0YzVkYjBhMzEzNjI3OTUxZGQ0NGNmZDEyMTRkOThkNmY4ZDUwMTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ldjoT_WT8BLHjcfZvLDDTge9q27qX7pysG6iZDpX0v4)

yeah. It's not black square though. It's just a darker shade of the bottom colour

**Comment by aneesh1122** [comment]
> I have not used the wavy circle before, did it always have the black square behind it ?
yeah. It's not black square though. It's just a darker shade of the bottom colour

btw what theme and background are you using? I don't have black as my upper gradient

**Comment by Cszyn** [comment]
> > I have not used the wavy circle before, did it always have the black square behind it ?
> > yeah. It's not black square though. It's just a darker shade of the bottom colour
> 
> btw what theme and background are you using? I don't have black as my upper gradient

sorry i wasn't near my pc. Gradient background from theme and the dynamic theme

**Comment by aneesh1122** [comment]
> > > I have not used the wavy circle before, did it always have the black square behind it ?
> > > yeah. It's not black square though. It's just a darker shade of the bottom colour
> > 
> > btw what theme and background are you using? I don't have black as my upper gradient
> 
> sorry i wasn't near my pc. Gradient background from theme and the dynamic theme

Restart your app and you'll lose that black gradient at the top

**Comment by Cszyn** [comment]
> > > > I have not used the wavy circle before, did it always have the black square behind it ?
> > > > yeah. It's not black square though. It's just a darker shade of the bottom colour
> > > 
> > > 
> > > btw what theme and background are you using? I don't have black as my upper gradient
> > 
> > 
> > sorry i wasn't near my pc. Gradient background from theme and the dynamic theme
> 
> Restart your app and you'll lose that black gradient at the top

i don't know it works just fine for me

**Comment by aneesh1122** [comment]
> > > > > I have not used the wavy circle before, did it always have the black square behind it ?
> > > > > yeah. It's not black square though. It's just a darker shade of the bottom colour
> > > > 
> > > > 
> > > > btw what theme and background are you using? I don't have black as my upper gradient
> > > 
> > > 
> > > sorry i wasn't near my pc. Gradient background from theme and the dynamic theme
> > 
> > 
> > Restart your app and you'll lose that black gradient at the top
> 
> i don't know it works just fine for me

do you still have upper black gradient even after properly closing and opening the app?

**Comment by Cszyn** [comment]
> > > > > > I have not used the wavy circle before, did it always have the black square behind it ?
> > > > > > yeah. It's not black square though. It's just a darker shade of the bottom colour
> > > > > 
> > > > > 
> > > > > btw what theme and background are you using? I don't have black as my upper gradient
> > > > 
> > > > 
> > > > sorry i wasn't near my pc. Gradient background from theme and the dynamic theme
> > > 
> > > 
> > > Restart your app and you'll lose that black gradient at the top
> > 
> > 
> > i don't know it works just fine for me
> 
> do you still have upper black gradient even after properly closing and opening the app?

Yes?

**Comment by aneesh1122** [comment]
> > > > > > > I have not used the wavy circle before, did it always have the black square behind it ?
> > > > > > > yeah. It's not black square though. It's just a darker shade of the bottom colour
> > > > > > 
> > > > > > 
> > > > > > btw what theme and background are you using? I don't have black as my upper gradient
> > > > > 
> > > > > 
> > > > > sorry i wasn't near my pc. Gradient background from theme and the dynamic theme
> > > > 
> > > > 
> > > > Restart your app and you'll lose that black gradient at the top
> > > 
> > > 
> > > i don't know it works just fine for me
> > 
> > 
> > do you still have upper black gradient even after properly closing and opening the app?
> 
> Yes?

you're lucky then. After restarting the app my upper gradient always becomes grey. It's happening with other guys too.

what's your theme mode? pitch black or dark?

**Comment by Cszyn** [comment]
> > > > > > > > I have not used the wavy circle before, did it always have the black square behind it ?
> > > > > > > > yeah. It's not black square though. It's just a darker shade of the bottom colour
> > > > > > > 
> > > > > > > 
> > > > > > > btw what theme and background are you using? I don't have black as my upper gradient
> > > > > > 
> > > > > > 
> > > > > > sorry i wasn't near my pc. Gradient background from theme and the dynamic theme
> > > > > 
> > > > > 
> > > > > Restart your app and you'll lose that black gradient at the top
> > > > 
> > > > 
> > > > i don't know it works just fine for me
> > > 
> > > 
> > > do you still have upper black gradient even after properly closing and opening the app?
> > 
> > 
> > Yes?
> 
> you're lucky then. After restarting the app my upper gradient always becomes grey. It's happening with other guys too.
> 
> what's your theme mode? pitch black or dark?

Dynamic on the custom version

**Comment by aneesh1122** [comment]
> > > > > > > > > I have not used the wavy circle before, did it always have the black square behind it ?
> > > > > > > > > yeah. It's not black square though. It's just a darker shade of the bottom colour
> > > > > > > > 
> > > > > > > > 
> > > > > > > > btw what theme and background are you using? I don't have black as my upper gradient
> > > > > > > 
> > > > > > > 
> > > > > > > sorry i wasn't near my pc. Gradient background from theme and the dynamic theme
> > > > > > 
> > > > > > 
> > > > > > Restart your app and you'll lose that black gradient at the top
> > > > > 
> > > > > 
> > > > > i don't know it works just fine for me
> > > > 
> > > > 
> > > > do you still have upper black gradient even after properly closing and opening the app?
> > > 
> > > 
> > > Yes?
> > 
> > 
> > you're lucky then. After restarting the app my upper gradient always becomes grey. It's happening with other guys too.
> > what's your theme mode? pitch black or dark?
> 
> Dynamic on the custom version

Theme : Dynamic
Theme mode : ?

**Comment by aneesh1122** [comment]
> oh. System = Dark

okay. ping me here again if you get your upper gradient as grey
