### ISSUE TITLE
Moving gradient background

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1843]
### Description

Yesterday I created a request for #1834 but this is much better. This not only takes multiple colors from cover but also creates a moving gradient.

### Suggested Solution

https://github.com/fast4x/RiMusic/assets/45353488/e5d5d81b-eb5b-4c95-88ba-52a63f16bccc

This is the app. It's also open source. [SaltPlayer on GitHub](https://github.com/Moriafly/SaltPlayerSource)

### Alternatives

Another Repo [amlv](https://github.com/dokar3/amlv)
and here is its kotlin code [FluidBg.kt](https://gist.github.com/KlassenKonstantin/d5f6ed1d74b3ddbdca699d66c6b9a3b2)

**Comment by fast4x** [comment]
Implemented fluid gradient backgrounds from theme and coverm available from version 0.6.35

**Comment by JeePopuwu** [comment]
> Implemented fluid gradient backgrounds from theme and coverm available from version 0.6.35

![b03eedc0129f8b4ce3ac52fb7ab1a736](https://github.com/fast4x/RiMusic/assets/159836335/e3d08db5-5357-4532-a02b-a05a0efd131b)
Is there something you don't do well?

**Comment by JeePopuwu** [comment]
> Implemented fluid gradient backgrounds from theme and coverm available from version 0.6.35

Could I ask with curiosity how you're doing, my good Fast with the Style Miku?

**Comment by fast4x** [comment]
I’m looking for the best and fastest solution to develop it.

**Comment by JeePopuwu** [comment]
> Estoy buscando la mejor y más rápida solución para desarrollarlo.

While you don't forget and give your best effort in it, it's more than enough.

**Comment by aneesh1122** [comment]
> Implemented fluid gradient backgrounds from theme and coverm available from version 0.6.35

Dude that just made my day. Tysm

**Comment by aneesh1122** [comment]
> Implemented fluid gradient backgrounds from theme and coverm available from version 0.6.35

Will this background be used for lyrics too?

**Comment by fast4x** [comment]
Not, i can try to add a setting for enable.

**Comment by aneesh1122** [comment]
> Not, i can try to add a setting for enable.

Please add an option. Lyrics will look beautiful with this fluid background

**Comment by dAtA-TRoN** [comment]
> Implemented fluid gradient backgrounds from theme and coverm available from version 0.6.35

![proxy-image(2).gif](https://github.com/fast4x/RiMusic/assets/71184627/f86ddf52-d6e2-4ec6-a51b-2e4df1e112e4)

>Is there something you don't do well?

Short answer: No.

Long answer: No, absolutely not.

**Comment by fast4x** [comment]
Preview...
![Screenshot_20240516_090610](https://github.com/fast4x/RiMusic/assets/1484476/f2b55e87-f55c-4398-b1ee-456a2f53bbea)

**Comment by aneesh1122** [comment]
> Preview...
> ![Screenshot_20240516_090610](https://github.com/fast4x/RiMusic/assets/1484476/f2b55e87-f55c-4398-b1ee-456a2f53bbea)
> 

That's not what I meant man. Look at this video. Same song but with a moving fluid gradient background. 

https://github.com/fast4x/RiMusic/assets/45353488/09546805-36dc-419e-9b34-9dcbec06881f

See how the background is changing

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/8ee26a37-4426-4898-8a1a-6c4c8a3e0e3f

Not seems to be more different...

**Comment by aneesh1122** [comment]
> 
> https://github.com/fast4x/RiMusic/assets/1484476/8ee26a37-4426-4898-8a1a-6c4c8a3e0e3f
> 
> Not seems to be more different...

Okay. Earlier you posted a photo so I couldn't see the moving gradient.

Can you try this one?
https://music.youtube.com/watch?v=W5JUyW-z-fQ

**Comment by fast4x** [comment]
Done

https://github.com/fast4x/RiMusic/assets/1484476/29fc4adf-8588-407d-ba9c-23790dff4363

**Comment by fast4x** [comment]
Improved player and background mode, available from version 0.6.35

**Comment by aneesh1122** [comment]
> Done
> 
>  Screen_recording_20240516_105225.mp4

your themes seems to be different so I'll wait for the release and try it myself and tell you how it is.
