### ISSUE TITLE
Missing album art on player for some albums

### ISSUE THREAD

**Issue by Carter0108** [fast4x/RiMusic#1845]
### Steps to reproduce the bug

Play any song from some albums and open the player

### Expected behavior

Should display album art

### Actual behavior

RiMusic logo is displayed instead

### Screenshots/Screen recordings

![Screenshot_20240512-113159](https://github.com/fast4x/RiMusic/assets/55948138/2148fd1d-03b0-40c3-87cf-123822046ca4)
![Screenshot_20240512-113202](https://github.com/fast4x/RiMusic/assets/55948138/48a71e05-9528-46f8-be44-280dbb9ad5c4)

### RiMusic version

0.6.34

### Android version

Android 14

### Additional information

As you can see from the example screenshots, the album art is present on the album page but not in the mini player or big player.

**Comment by aneesh1122** [comment]
https://github.com/fast4x/RiMusic/assets/45353488/3b8011bd-74b9-49ed-bb3d-5ca6a8c38c5f

Same album, same song. Working for me

**Comment by fast4x** [comment]
possible image cache saturation... clean or increase

**Comment by Carter0108** [comment]
> possible image cache saturation... clean or increase

I thought the same but it doesn't appear to be that. Currently sitting at 27MB of the 256MB cache. Deleting cache doesn't change anything. It's not just that album but that's the one I remember. I'll come across a few in radio mixes.

**Comment by Carter0108** [comment]
To add to this: if I clear app storage then the album art for this particular album reappears but after restoring my backup, it disappears again.
