### ISSUE TITLE
Background color is not changing in 'pitch black' theme mode

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1848]
### Steps to reproduce the bug

https://github.com/fast4x/RiMusic/assets/45353488/6bf60941-f0b2-4024-83ec-6082c4e82954

### Expected behavior

'Background from cover' should remain same for every theme since it depends only on cover image.

### Actual behavior

Background is not changing at all. It's always black

### RiMusic version

Latest custom version

### Android version

Android 13

**Comment by fast4x** [comment]
Isn't planned in pitch black mode... use other if you want it ..

**Comment by aneesh1122** [comment]
> Isn't planned in pitch black mode... use other if you want it ..

Okay

Could you please try to implement #1846?

This will give us endless possibilities.

My perfect combination is

Theme : Dynamic
Theme mode : Dark
Background 1 : Pure Black

As of right now when the custom theme is chosen we lose changing colors based on album cover
