### ISSUE TITLE
Play start lags heavily after last update

### ISSUE THREAD

**Issue by halnine** [fast4x/RiMusic#1852]
### Steps to reproduce the bug

Play any aong with The new version.
Until today's update playback was immediate, now it might take up to 20 seconds at times.

### Expected behavior

Immediate pmayback

### Actual behavior

Lag

### RiMusic version

0.6.34

### Android version

Android 13, MIUI 14

### Additional information

Adguard is installed. It didn't affect previous versions but I thought it was worth mentioning in case any change in server occurred in this version.

**Comment by fast4x** [comment]
Strange, anything was changed, try custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by kris20030705** [comment]
> Strange, anything was changed, try custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

Why don't you rename "Ri Music beta"
So, we don't have to delete the stable one..!

**Comment by fast4x** [comment]
Because isn't a beta release.
