### ISSUE TITLE
bug with background colors in the player 

### ISSUE THREAD

**Issue by WHONEYR** [fast4x/RiMusic#1854]
### Steps to reproduce the bug

skip the song without leaving the player 

### Expected behavior

the color should match the cover of the song being played 

### Actual behavior

the color follows the cover of the previous song 

### Screenshots/Screen recordings

![Screenshot_20240513_002703](https://github.com/fast4x/RiMusic/assets/168048677/f59106e3-3dac-4b53-97ac-6c4ced3a46c0)
![Screenshot_20240513_002746](https://github.com/fast4x/RiMusic/assets/168048677/7b7a4fa3-450f-4c60-866e-1dd263a3e03c)

### Logs

After updating the gradient background colors in the player, the app started to crash a lot on my device 

### RiMusic version

0.6.34

### Android version

Android 13

### Additional information

when the player is minimized this bug does not happen

**Comment by fast4x** [comment]
try custom release download https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by WHONEYR** [comment]
I saw later that they already reported this bug, but I don't know how to delete this report I made 🥲

(Just one question, do you remember what I said about songs with titles +18 not being possible to play? Do you have any updates on this?)

**Comment by fast4x** [comment]
Not for now

**Comment by fast4x** [comment]
Do you mean parental control over songs with explicit text?

**Comment by fast4x** [comment]
I'll develop soon

**Comment by aneesh1122** [comment]
> I saw later that they already reported this bug, but I don't know how to delete this report I made 🥲

Close the issue?

**Comment by fast4x** [comment]
I'll close it later

**Comment by aneesh1122** [comment]
> Do you mean parental control over songs with explicit text?

Explicit songs are played just fine.

There are songs which have  explicit words in the song's title. They won't be played.

For example [https://music.youtube.com/watch?v=KethaudydZk](this song) won't play in RiMusic because the title has the word 'cunt'
