### ISSUE TITLE
Album

### ISSUE THREAD

**Issue by SveinAu** [fast4x/RiMusic#1855]
### Steps to reproduce the bug

Can't add an album to my album list anymore. 

### Expected behavior

A box say add to album 

### Actual behavior

Nothing happening 

### Screenshots/Screen recordings

![Screenshot_20240513-061444](https://github.com/fast4x/RiMusic/assets/155201459/cb2f1fe8-106d-448e-8e80-068bcf739d6b)

### RiMusic version

0.6.34

### Android version

14

**Comment by aneesh1122** [comment]
Install the custom version

**Comment by carlospjr** [comment]
I used the custom version and now appears the "Favourite" button.

Thanks

> Install the custom version
