### ISSUE TITLE
[Feature]: Visualizer designs Concept

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#186]
### Description

Ive made 4 visualizers designs that respects the RiMusic UI

This inspired me to do it :
![Screenshot_20231206_191608](https://github.com/fast4x/RiMusic/assets/104271365/ee3322d6-2e79-4583-83b9-87da22f296b9)

### Suggested Solution

Design 1 (One Side Circular) :
![One Circular](https://github.com/fast4x/RiMusic/assets/104271365/83cdccdb-3e7c-446f-9548-8767537bd04a)

Design 2 (Double Side Circular) :
![Double Circular](https://github.com/fast4x/RiMusic/assets/104271365/fcd1cecf-d2b6-4c11-9fab-30fffda05da4)

Design 3 (One Side) :
![One Side](https://github.com/fast4x/RiMusic/assets/104271365/d6033c2c-2077-4e5a-a08a-64fc9fe604a2)

Design 4 (Double Side) :
![Double Side](https://github.com/fast4x/RiMusic/assets/104271365/eb98706f-3437-4631-92e0-f6769c5e63b5)

### Additional Context

The simple look will maybe give more performance and less bugs.

Also it could be possible to make a setting to indicate how much lines we want.

If there is another visualizer look idea i can do it.

**Comment by fast4x** [comment]
It’s a nice idea consistent with the work we’re doing together on RiMusic. 
Thanks

**Comment by fast4x** [comment]
I think this can be closed
