### ISSUE TITLE
Se cierra la aplicación cuando no hay conexión a internet y no deja reproducir música sin conexión 

### ISSUE THREAD

**Issue by julianM2000** [fast4x/RiMusic#1860]
### Steps to reproduce the bug

Se cierra sola y el degradado del player falla

### Expected behavior

No puedo escuchar música sin conexión 😿

### Actual behavior

Help :(

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/68936429/2e68e5e1-8e72-4528-af94-630fede22195

### RiMusic version

Versión libre la última 

### Android version

13

### Additional information

Se cierra sola cuando no estoy conectado a una red wifi , solo funciona con conexión, esto es con la versión libre que subiste hasta corregír lo del degradado 😮‍💨

**Comment by JeePopuwu** [comment]
Eres el tercer hispano que veo xdd

Esto poco a poco se va llenando waos

**Comment by fast4x** [comment]
Check if you use the background linked to the cover because there is currently a bug and if the connection is missing it crashes. Change background without cover and try again.

**Comment by julianM2000** [comment]
@fast4x gracias 🫂, ya se solucionó con eso

**Comment by fast4x** [comment]
Please in version 0.6.38, go to miscellaneous settings, enable debug, restart app, repeat crash action, after go again to settings, click on copy crash log and paste here

**Comment by JeePopuwu** [comment]
> En la versión 0.6.38, vaya a configuraciones varias, habilite la depuración, reinicie la aplicación, repita la acción de bloqueo, luego vaya nuevamente a la configuración, haga clic en copiar el registro de fallas y péguelo aquí.

Could you explain it to me in a video?  x,d
