### ISSUE TITLE
New interface for now playing 

### ISSUE THREAD

**Issue by nelsonsiby2345** [fast4x/RiMusic#1864]
### Description

Can you add a new interface for now playing

### Suggested Solution

![now-playing](https://github.com/fast4x/RiMusic/assets/111241904/3ecdb80c-a484-448f-8fe9-36d05c7b2ab6)
like this type of interface

**Comment by dAtA-TRoN** [comment]
What's work with the present one? It's highly customizable.

**Comment by JeePopuwu** [comment]
The current interface is very good both aesthetically and functionally, and it's also unique at the moment. One of the things Fast wanted to achieve was for it to be recognizable on its own.

Adding another one with a different style doesn't seem like a very good idea to me.

**Comment by JeePopuwu** [comment]
However, it wouldn't be bad to add another way to view the text, like in the second image, but it would mean changing things around.

In the end, I think it's best for Fast to make the decision.

**Comment by nelsonsiby2345** [comment]
The vi interface is not that great and the one I posted is look so good, I really like the song name and artist name on the centre without the album and artist icons next to it , it's look so clean and I posted that as a suggestion. My english is not that great  but I hope you understand it

**Comment by fast4x** [comment]
It's much Apple like...

**Comment by aneesh1122** [comment]
> I really like the song name and artist name on the centre without the album and artist icons next to it

This I agree with. Rest of the things not really. what do you think @fast4x ? Should title and the album be centered?

**Comment by fast4x** [comment]
Centered = ViMusic mode

**Comment by aneesh1122** [comment]
> Centered = ViMusic mode

Ohh. Neither used ViMusic nor used ViMusic mode ever before so I had no idea. Sorry about that.

**Comment by nelsonsiby2345** [comment]
> Centered = ViMusic mode

The vi music interface is not good like the ri music interface and I put it as a suggestion. It is your choice to do or not.  Anyway, I love this app ✌️

**Comment by fast4x** [comment]
Could be useful in advanced customization later

**Comment by nelsonsiby2345** [comment]
Thank you for hearing our requests and suggestions and giving us new updates every week. ❤️
