### ISSUE TITLE
[Feature]: Sharing Playlists

### ISSUE THREAD

**Issue by ansarimohammed422** [fast4x/RiMusic#1865]
### Description

We can only export playlist

### Suggested Solution

We cant share a playlist

### Alternatives

I want you to add support like sharing playlist to other app

**Comment by dAtA-TRoN** [comment]
This has been a very common request. The problem is that playlists don't follow a standardized format. Each app has its own system. Because of this, it's likely not possible.

**Comment by fast4x** [comment]
Actually you can export and share your exported playlist with any other RiMusic user. But a question is: do you want export to other app or from other app?

**Comment by ansarimohammed422** [comment]
I want to share playlist like youtube and youtube music

**Comment by fast4x** [comment]
Go to YouTube playlist click share a d select RiMusic

**Comment by aneesh1122** [comment]
> Go to YouTube playlist click share a d select RiMusic 

Is it possible to implement importing songs in RiMusic which have title, artist, album and duration?

**Comment by fast4x** [comment]
It's just implemented import playlist from YT/YT Music

**Comment by aneesh1122** [comment]
> It's just implemented import playlist from YT/YT Music

that's not what I meant.

there's a website called [Exportify](https://watsonbox.github.io/exportify/) which lets you export playlists from spotify. I can get Title, Album, Artists and duration from there and import it to RiMusic. RiMusic would take Title, Album, Artists and duration from .csv file, search for the song and then add the top result to the playlist.

is it possible to implement something like this?

**Comment by fast4x** [comment]
I do not think
