### ISSUE TITLE
Show images when you have no network

### ISSUE THREAD

**Issue by chatinteligence** [fast4x/RiMusic#1868]
### Description

It would be an improvement for when you want to play the music offline mode album images these can be seen, as currently you have to have internet to be displayed 
![imagen ri](https://github.com/fast4x/RiMusic/assets/147566193/6c1c950e-cd9d-4585-b9c0-0e0d15d02ee8)

### Suggested Solution

A serious solution would be to make it equally attractive with internet and without internet, greetings.

![image muestra](https://github.com/fast4x/RiMusic/assets/147566193/f5c88e2a-672d-4d5e-9fed-232cd2fde892)

**Comment by chatinteligence** [comment]
Hi friend @fast4x , don't forget about this improvement, maybe it's a good thing to implement, the improvement is to implement that when you run out of internet but keep the music or album cover.

Remember we appreciate you, you are an excellent programmer.

**Comment by fast4x** [comment]
Hi friend, I'll check it soon, thanks for appreciation.

**Comment by fast4x** [comment]
Improved image caching, available from version 0.6.37
