### ISSUE TITLE
[Feature]: Spacing and alignment improvements

### ISSUE THREAD

**Issue by DanielSevillano** [fast4x/RiMusic#187]
### Description

The app bar has no right margin, the action button is squished and the title isn't centered. I think this could be improved.

<img src="https://github.com/fast4x/RiMusic/assets/68847306/df93dbc6-a934-49f4-b0fd-0a7e55411b7e" width="200px"/>

### Suggested Solution

Adding some spacing on the right and centering the title would improve the look a lot, despite losing some space.

<img src="https://github.com/fast4x/RiMusic/assets/68847306/4adbec79-d9ed-480e-8f23-b8ced53e440c" width="200px"/>

### Additional Context

Additionally, I would remove the app bar icons background in the settings. It makes them look like buttons and it can be confusing.

<img src="https://github.com/fast4x/RiMusic/assets/68847306/3c3bc11b-48a2-441e-b6cd-fee6f8eb24d7" width="200px"/>

**Comment by DanielSevillano** [comment]
I think that everything has been fixed.

**Comment by fast4x** [comment]
Thanks for feedback
