### ISSUE TITLE
Synced lyrics

### ISSUE THREAD

**Issue by Nabil233** [fast4x/RiMusic#1871]
### Description

App is perfect. But Can you add synced like Spotify? And separate lyrics page like Spotify or apple music would be great 

### Suggested Solution

App is perfect. But Can you add synced like Spotify? And separate lyrics page like Spotify or apple music would be great

**Comment by fast4x** [comment]
Lyrics show with tap on album thumbnail in player and separate page show clicking on. full screen icon. 
![IMG_20240515_150209.jpg](https://github.com/fast4x/RiMusic/assets/1484476/9abb614c-8c55-4621-9ed3-8b8a4d3a79d9)

this is full lyrics page
![Screenshot_2024-05-15-15-00-14-450_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/14ad666c-9660-4550-aa8f-c53a2632872a)

**Comment by fast4x** [comment]
also you can switch sync and unsync lyrics by 3 dots menu icon 
![Screenshot_2024-05-15-15-05-10-524_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/b3bb4664-dbd7-4e5a-9ad6-f7a616c59cc4)

**Comment by Nabil233** [comment]
Thank you so much. By the couldn't understand that switching to sync and unsync lyrics... Can't find any toggle or button.... Or do I need to manually add time stamp from edit lyrics? Sorry for bothering you not a techy person 🥲. 
Btw you should create a discord and donation page. Your app is perfect 💗

**Comment by fast4x** [comment]
i develop for passion, thank you for appreciation.

After you tap on picture, the three dots icon show lyrics menu and can switch... edit, resync and more ...

![Screenshot_2024-05-15-15-15-01-290_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/c68503b5-53e3-4471-9b51-57754cad7a60)

![Screenshot_2024-05-15-15-15-30-376_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/5e3ed1bc-b929-4c47-a448-29b67f44567f)



![Screenshot_2024-05-15-15-15-48-576_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/89355ab1-b968-4979-8445-93f81ddb5656)

**Comment by aneesh1122** [comment]
> Thank you so much. By the couldn't understand that switching to sync and unsync lyrics... Can't find any toggle or button.... Or do I need to manually add time stamp from edit lyrics? Sorry for bothering you not a techy person 🥲. Btw you should create a discord and donation page. Your app is perfect 💗

1) select "Show synchronized lyrics" to switch to sync lyrics. If you want to switch to unsync lyrics , tap on "Show unsynchronized lyrics".
2) RiMusic fetches synced lyrics online so you don't have to edit anything to add time stamp.
3) You can use "edit lyrics" if you feel the lyrics are wrong and correct it yourself.
4) "copy lyrics" will copy the fetched lyrics to your mobile's clipboard

**Comment by Nabil233** [comment]
Thank you sooo muchhh. I'm definitely suggesting your app to all of my friends. Open discord asap and donation page tooo. 
Praying for your success 🫶
