### ISSUE TITLE
[Feature]: auto remove none downloaded song from downloads playlist

### ISSUE THREAD

**Issue by Cszyn** [fast4x/RiMusic#1872]
### Description

Disclaimer: I'm currently using the custom version, so I have no idea if this is a bug or missing feature.
I accidentally downloaded 200 songs from a playlist and went to delete all downloaded songs. But when clicking on the downloads playlist it's all still in there (but not downloaded)

### Suggested Solution

Automatically remove not downloaded songs

### Additional Context

Somewhat low priority so take your time

**Comment by fast4x** [comment]
From playlist click remove download as in screenshot.
![Screenshot_2024-05-16-00-50-03-172_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/8d901793-b463-4664-86c7-1805132f27cd)

**Comment by Cszyn** [comment]
Forgor to close this 💀
