### ISSUE TITLE
Duplicate monthly playlist

### ISSUE THREAD

**Issue by fofxox** [fast4x/RiMusic#1874]
### Steps to reproduce the bug

Export database, uninstall/reinstall RiMusic, import database into a fresh new app.
A second copy of "April 2024" appears.
Try to rename the playlist, see the "Cannot rename" toast pop-up notification.
A third copy of "April 2024" appears.

### Expected behavior

Only one playlist each month

### Actual behavior

Many of the same playlist

### Screenshots/Screen recordings

![Screenshot_20240515_214003](https://github.com/fast4x/RiMusic/assets/130255231/b956a6fa-f3a7-4dea-982a-c8dbfadbab5f)

### RiMusic version

0.6.34

### Android version

Android 14

**Comment by fast4x** [comment]
Today I'll check

**Comment by fast4x** [comment]
I think it's now fixed, available from version 0.6.35
