### ISSUE TITLE
The app doesn't announce album art for system

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1875]
### Steps to reproduce the bug

I'm using Nova Launcher to show media widget in app drawer and Smartspacer to show it on home screen. For some reason the album art from RiMusic doesn't appear for both apps. I've tried it with 3 other music apps including Spotify and they all work fine so this is a confirmed RiMusic issue. It looks like RiMusic handles album art different from other apps.

Here's music playing from RiMusic for Nova:
![IMG_20240515_104155](https://github.com/fast4x/RiMusic/assets/99175083/135c6f40-21ab-4a15-b2fd-62bf9ee6566d)

For Smartspacer:-
![IMG_20240516_093643](https://github.com/fast4x/RiMusic/assets/99175083/43d09e42-ea8a-4988-a55f-8c653eaa6d83)

A different music player:-
![IMG_20240516_123954](https://github.com/fast4x/RiMusic/assets/99175083/65d80380-35f7-4d49-b7a6-bcf848e18952)

### Expected behavior

The album art should appear

### Actual behavior

Art not appearing

### RiMusic version

0.6.34

### Android version

Android 12

**Comment by NikunjKhangwal** [comment]
Forgot to post this. Spotify showing up in smartspacer:-

![IMG_20240516_124808](https://github.com/fast4x/RiMusic/assets/99175083/beb4b772-91a7-4a6d-ac3c-d22036cb0365)

**Comment by fast4x** [comment]
Nova launcher isn't a standard launcher, I'll check it in the future not now.

**Comment by NikunjKhangwal** [comment]
@fast4x Is this one accidentally closed? It's not fixed yet.

**Comment by fast4x** [comment]
no, isn't a bug, not reproduced

**Comment by NikunjKhangwal** [comment]
Did you tried with smartspacer?

**Comment by fast4x** [comment]
I not support other products

**Comment by NikunjKhangwal** [comment]
This is a rimusic issue but ok
Other apps were mentioned just to confirm it.

**Comment by fast4x** [comment]
I haven't reproduced so i can't solve it

**Comment by NikunjKhangwal** [comment]
Ok 👍
