### ISSUE TITLE
[Feature]: Option to disable crossfade for albums

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1876]
### Description

Some albums have their own seamless transition between songs. Having crossfade enabled blends them and you can't hear or notice the instrument switch. Disabling crossfade completely isn't an option because it's a nice feature for normal songs.

### Suggested Solution

Add an option to disable crossfade for albums only. It'll be temporarily disabled when a song is played from album window instead of something else (like search result, quick picks etc)

**Comment by NikunjKhangwal** [comment]
That's a different thing. Also how's crossfade going to work with delay?

**Comment by fast4x** [comment]
Will be fade effect, and is possibile to disable from settings.
![Screenshot_20240516_105609](https://github.com/fast4x/RiMusic/assets/1484476/5039edaa-28f7-4e4e-a239-699b2648df4d)

**Comment by fast4x** [comment]
Fade it's applied to all songs without distintion, enable/disable for all

**Comment by aneesh1122** [comment]
> ### Description
> Some albums have their own seamless transition between songs. Having crossfade enabled blends them and you can't hear or notice the instrument switch. Disabling crossfade completely isn't an option because it's a nice feature for normal songs.
> 
> ### Suggested Solution
> Add an option to disable crossfade for albums only. It'll be temporarily disabled when a song is played from album window instead of something else (like search result, quick picks etc)
> 
> ### Alternatives
> _No response_
> 
> ### Additional Context
> _No response_

dude, crossfade isn't even working. Hell, even the normal fade is buggy right now. songs keep fading out randomly.

**Comment by fast4x** [comment]
Of course, bug it's forever... LOL

**Comment by NikunjKhangwal** [comment]
A different thing but ok no big deal.

**Comment by NikunjKhangwal** [comment]
I don't get mad 😆
I was referring to my initial request about album disable not the bug
