### ISSUE TITLE
Bottom of the Albums tab is cut off

### ISSUE THREAD

**Issue by Juggalage** [fast4x/RiMusic#1879]
### Steps to reproduce the bug

Scroll to the bottom of the Albums tab of the library.

### Expected behavior

Every album should be fully visible. 

### Actual behavior

Bottom of the row is cut off. 

### Screenshots/Screen recordings

![Screenshot_20240516-140541](https://github.com/fast4x/RiMusic/assets/32726906/4c1b7462-16a3-450b-bdb1-f9d25c954a92)

### RiMusic version

v0.6.34 custom version

### Android version

Android 14

**Comment by fast4x** [comment]
Fixed, available from version 0.6.35
