### ISSUE TITLE
Can't fetch Album Art 

### ISSUE THREAD

**Issue by Moodzz1** [fast4x/RiMusic#1880]
### Steps to reproduce the bug

N/A

### Expected behavior

Other apps should be able to detect the album art belonging to Currently playing song.

### Actual behavior

Other apps (such as kizzy) are not able to detect the album art for currently playing song.

### RiMusic version

0.6.34

### Android version

Android 14

**Comment by fast4x** [comment]
Explain better please

**Comment by Moodzz1** [comment]
Some apps are unable to grab the album art of whatever song is playing. I have seen this issue with a music widget and another example is with [kizzy](https://github.com/dead8309/Kizzy)'s RPC where the album art of a song isn't displayed (YTM doesn't have this issue)

**Comment by fast4x** [comment]
RiMusic work across YT/YTM api, it show wich is published by api.
