### ISSUE TITLE
Songs not being added to favorites, but show heart icon in them.

### ISSUE THREAD

**Issue by Fre148** [fast4x/RiMusic#1882]
### Steps to reproduce the bug

1. Open RiMusic
2. Search for any song, click the heart icon
3. Go yo "Favorites" list
4. Song does not appear on favorites. 
5. Search for selected song again, heart icon is pressed

### Expected behavior

Song gets added to favorites and appears in the list. 

### Actual behavior

The song does not get added even if the heart icon is pressed. In the image, I wanted to add "Stairway to Heaven" and after doing so it does not appear on the list.

### Screenshots/Screen recordings

![Screenshot_20240516-195454](https://github.com/fast4x/RiMusic/assets/103809993/efae9f00-d60d-4646-b19a-3cea359c33e7)
![Screenshot_20240516-195458](https://github.com/fast4x/RiMusic/assets/103809993/9c080edd-aeda-442c-af0b-ebd4cdc8d2ef)
![Screenshot_20240516-195719~2](https://github.com/fast4x/RiMusic/assets/103809993/2d98003f-9db3-463f-9b1b-8e15567e4f33)

### RiMusic version

0.6.34

### Android version

Android 14

### Additional information

Couldn't upload video recording because of size limit :(

**Comment by fast4x** [comment]
It work
https://github.com/fast4x/RiMusic/assets/1484476/fcd0844d-cb96-4090-a101-e0a83d33f40d

**Comment by Fre148** [comment]
You're right! It was something with my list filters. Thanks for reaching out and sorry for bothering!!

**Comment by fast4x** [comment]
> You're right! It was something with my list filters. Thanks for reaching out and sorry for bothering!!

you are welcome, thanks
