### ISSUE TITLE
Playlists are opened twice when playlists are opened from 'go to playlist'

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1883]
### Steps to reproduce the bug

https://github.com/fast4x/RiMusic/assets/45353488/41d366cd-d0b7-479d-afb0-78dce4fa8161

### Expected behavior

Only one page of playlist should open

### Actual behavior

2 pages of the same playlist overlaps

### RiMusic version

0.6.35 custom

### Android version

Android 13

**Comment by fast4x** [comment]
navigation system permit multiple page open.

**Comment by aneesh1122** [comment]
> navigation system permit multiple page open.

Okay. It doesn't affect the experience. I just thought it would slow down weak mobiles so I reported this bug.

**Comment by fast4x** [comment]
Thanks
