### ISSUE TITLE
The original video source of this song has been deleted - Go to link not working for all links

### ISSUE THREAD

**Issue by FelixSchrodinger** [fast4x/RiMusic#1884]
### Steps to reproduce the bug

1. Open browser, test link from YouTube app:

https://youtu.be/7lZ9X7Vu3AA

Next is the mobile browser link:

https://youtu.be/7lZ9X7Vu3AA?si=6OkBMgv0F8t7_ffk

Desktop link:

https://youtu.be/7lZ9X7Vu3AA?si=l6fKw5mkceoHHixD

Open RiMusic, go to search. Tap "Go to link" from the left pane and paste any of the 3 links in and tap search.

### Expected behavior

By praying to the gods and the hard work of the contributors... should work.

### Actual behavior

The player pops up and a head² emoji with an awkard smile is there, along with an error message saying:

"The original video source of this song has been deleted" 

### Screenshots/Screen recordings

![Screenshot_20240517_110347](https://github.com/fast4x/RiMusic/assets/41850969/242e1c57-7fd7-4666-acf6-d82a3ccf2f65)

### RiMusic version

0.6.34 - LATEST

### Android version

Android 14

### Additional information

Using a Galaxy Fold 5 , One UI 6.1 . The Fold5 is armv7 compatible (I've seen some of the latest phones won't work without armv8 libs). 

I don't know if some results are filtered out to try keep RiMusic relevant to only music. I tried a stand-up comedia video link and that didnt work (Its not music obviously, just a test). If results are filtered for relevance, can you guys implement something to ignore the filtering when using the "Go to link" feature. If a user pastes a link, they obviously dont want it to be filtered out.

Appreciate what you guys do. Not a complaint in any way. Love this app.

**Comment by fast4x** [comment]
Not possible, RiMusic work across api and if return a limitations of songs it is inevitable.

**Comment by FelixSchrodinger** [comment]
> Not possible, RiMusic work across api and if return a limitations of songs it is inevitable.

Even when I search the exact name fully or use a direct link it hits an API limit? It's the top result on YT when I search for it. Maybe I'm misunderstanding the API you use

**Comment by MrX-Ninja** [comment]
Bro I was facing same kind of issues in ViTune , Vi music app , well I don't have any solution for this but I have one option

Download YouTube Music ReVanced + Micro G you can stream easily in background I hope it helps .

https://objects.githubusercontent.com/github-production-release-asset-2e65be/534657560/4551719f-c607-4da3-9b89-7d48a808e41c?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250120%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250120T042652Z&X-Amz-Expires=300&X-Amz-Signature=d612a9ff192b257de65218fbdc0ecc899a72a3a76f0ae099712577f8c9208e76&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dmusic-revanced-extended-v7.16.53-arm-v7a.apk&response-content-type=application%2Fvnd.android.package-archive
