### ISSUE TITLE
Where's the save album button in the latest version?

### ISSUE THREAD

**Issue by suckingtentacles** [fast4x/RiMusic#1887]
### Steps to reproduce the bug

So I just updated the app to to the latest version and I got confused because there's no button to add the album like in the previous version, or am I just stupid and couldn't see it 😭😭😭

![Screenshot_20240517_235540_it fast4x rimusic_edit_798513675740653](https://github.com/fast4x/RiMusic/assets/144319707/fe906f58-221a-48f7-8081-07475a23043d)

### Expected behavior

In the previous version the button to add the album to your collection is on top of the album cover. 

![Screenshot_20240517_235600](https://github.com/fast4x/RiMusic/assets/144319707/3fccac3f-a606-4158-8a52-f439c54d8290)

### Actual behavior

I just want to ask where's this button moved to now 🙏🏻

### RiMusic version

0.6.34

### Android version

Android 10

**Comment by ikanakova** [comment]
Duplicity to #1822 #1837 #1855

**Comment by dAtA-TRoN** [comment]
Yeah where is it, huh 😤!?

**Comment by fast4x** [comment]
it's just fixed and available on version 0.6.35
