### ISSUE TITLE
Album bookmark

### ISSUE THREAD

**Issue by maelz95** [fast4x/RiMusic#1888]
### Steps to reproduce the bug

On the new version I can't find the bookmark logo to add an album. I can find it in the older versions. In the screenshots I attached, one is from my tablet (bookmark is shown) V.0.6.29, the other on my phone on the new version (bookmark hiden).

### Expected behavior

-

### Actual behavior

-

### Screenshots/Screen recordings

![20240517_200339](https://github.com/fast4x/RiMusic/assets/47143840/ce3e8750-56e5-4ab0-8fa2-49e6e56d8381)
![Screenshot_20240517_200450](https://github.com/fast4x/RiMusic/assets/47143840/4a536bbe-58c1-4f03-a9e5-87255faaf426)

### RiMusic version

0.6.34

### Android version

Android 14

**Comment by maelz95** [comment]
Find the solution (install custom version).

**Comment by fast4x** [comment]
it's just fixed and available in version 0.6.35
