### ISSUE TITLE
Cant play the song "Fearless" by 'Lost Sky'

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [fast4x/RiMusic#1889]
### Steps to reproduce the bug

1.Go to Lost Sky and Play it. 
2.See app tells you to restart and boom get stuck in a loop

https://github.com/fast4x/RiMusic/assets/112297620/8898bbdc-ce99-43b2-97d6-11cf4c6ce0cd

### Expected behavior

It should play Fearless song by Lost Sky

### Actual behavior

It never plays the song

### Screenshots/Screen recordings

Uploading Screenrecorder-2024-05-17-23-36-19-500.mp4…

### RiMusic version

0.6.34

### Android version

MIUI 11 A10

### Additional information

I dont know why but it doesnt play that songs only till now

**Comment by ALMIGHTY-VC** [comment]
Sorry wanted to tell that i only have encountered that problem with that song only

**Comment by RedNas74** [comment]
Just tried it out for the heck of it, but for me the song plays no problem.

**Comment by ALMIGHTY-VC** [comment]
Okay when im on sufficient internet then will try the custom version

> Just tried it out for the heck of it, but for me the song plays no problem.
