### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#1890]
### Description

Hola! ¡¿Qué tal?!, sugiero está idea ya que sería muy indispensable para este reproductor, el audio no es malo pero el formato mp3/mp4 son algo del pasado, ¿Por qué no llevarlo a otro nivel?, es decir, mejoren la calidad de audio a un formato HD puesto que se aprecian detalles tan envolventes en el audio y son una mejor experiencia para el usuario, sin más que decir espero tomen en cuenta mi sugerencia, ¡gracias!

### Suggested Solution

N/A

### Alternatives

N/A

### Additional Context

N/A

**Comment by fast4x** [comment]
RiMusic work with HD audio quality, set it from UI settings Audo quality.
