### ISSUE TITLE
[Feature]:  controls on the queue view

### ISSUE THREAD

**Issue by claxcian** [fast4x/RiMusic#1891]
### Description

It's convenient to have forward or backward or play/stop controls while one is viewing the queue
![Screenshot_20240517_180212](https://github.com/fast4x/RiMusic/assets/46830063/cd25029b-543e-4759-b9c3-fa04abff1069)

### Suggested Solution

View attachment

**Comment by dAtA-TRoN** [comment]
At least Play/Pause.

**Comment by claxcian** [comment]
No rewind forward like spotify
![Screenshot_20240517_183651_Spotify](https://github.com/fast4x/RiMusic/assets/46830063/e4d8ea1c-018e-4cef-8f8c-fb10e6f6b0f9)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.36

**Comment by NikunjKhangwal** [comment]
The floating mini player was smart. Really solved a lot of problems

**Comment by dAtA-TRoN** [comment]
> The floating mini player was smart. Really solved a lot of problems

100% agreed 😌.

**Comment by claxcian** [comment]
Cool thanks
