### ISSUE TITLE
Mini player is not closing

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1892]
### Steps to reproduce the bug

https://github.com/fast4x/RiMusic/assets/45353488/39b10803-5f8c-4038-9452-12fb8e73ea30

### Expected behavior

Player should close

### Actual behavior

Player not closing

### RiMusic version

0.6.34

### Android version

Android 13

### Additional information

This happens when music is paused, app is minimised and opening the app after some time like half an hour

**Comment by fast4x** [comment]
Improved and available from version 0.6.36
