### ISSUE TITLE
"No music" icon shows on every piece of music

### ISSUE THREAD

**Issue by fofxox** [fast4x/RiMusic#1895]
### Steps to reproduce the bug

Search for music

### Expected behavior

Most songs should not have the "no music" icon in the corner

### Actual behavior

Every song has it in the corner

### Screenshots/Screen recordings

![Screenshot_20240517_182814](https://github.com/fast4x/RiMusic/assets/130255231/8a1aa694-4d70-4238-a510-9968a0713af0)

### RiMusic version

0.6.35

### Android version

Android 14

**Comment by fast4x** [comment]
icon show on every song wich are not listened...

**Comment by fofxox** [comment]
I am seeing the icon on songs I have listened to many times.

**Comment by fast4x** [comment]
listened time is saved online if up to limit set in settings... check it

**Comment by fast4x** [comment]
Removed icon
