### ISSUE TITLE
Botones de play personalizados 

### ISSUE THREAD

**Issue by chatinteligence** [fast4x/RiMusic#1897]
### Description

Considero que pueda ser personalizado el botón play, ya que en la versión 6.34 tenía buena pinta, sin embargo en esta versión no logra convencer del todo para algunos temas. 
![Screenshot_20240517_174459](https://github.com/fast4x/RiMusic/assets/147566193/84368378-ade3-4a75-bcbf-29902d7d1c80)

De igual manera cambiar la velocidad un poco más lenta la del fondo ya que está bien el efecto sin embargo, la velocidad si es rápida 

### Suggested Solution

Sería una solución poder tener los botones un poco más personalizados para ya sea darle con fondo o sin fondo, como la versión anterior que traía buena pinta

**Comment by fast4x** [comment]
set type in appearance settings 
![Screenshot_2024-05-18-07-52-23-454_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/1484476/5eaa5580-b6eb-44a8-9009-4982e21b324c)

**Comment by chatinteligence** [comment]
Hola Consideraba algo como en la versión anterior, casi algo como lo que pone el #1908 , ya que igual pintaba excelente en algunos temas el botón como lo era antes, te agradezco, saludos.

**Comment by fast4x** [comment]
Change buttons type in settings, in version 0.6.36

**Comment by chatinteligence** [comment]
![image](https://github.com/fast4x/RiMusic/assets/147566193/085b6d8f-4535-4d79-9e9b-b311586ccd0f)
