### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#1898]
### Description

Suggestion to make rounding of the lyrics window, right now you can see that the corners of it are straight, it doesn't look very pretty.

![Screenshot_20240518_121353](https://github.com/fast4x/RiMusic/assets/76595855/b6869806-716a-4dec-ae19-637b7c2a61aa)

Also the shadow of the album cover is flat at the top and bottom, also not very pretty. I suggest making a smoother transition.

![Screenshot_20240518_121401](https://github.com/fast4x/RiMusic/assets/76595855/a8e9501c-5a00-4051-ae75-4044e320e4ff)

### Suggested Solution

Make smoother...

**Comment by JeePopuwu** [comment]
that is already implemented, you just have to go to configuration

![Screenshot_2024-05-17-22-25-22-246_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/28eaf283-c934-426d-86aa-af78455aa4aa)
![Screenshot_2024-05-17-22-25-29-373_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/cdcee15f-3b09-4edc-9ec7-203e1dbab9f0)

**Comment by aneesh1122** [comment]
> that is already implemented, you just have to go to configuration
> 
> ![Screenshot_2024-05-17-22-25-22-246_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/28eaf283-c934-426d-86aa-af78455aa4aa)
> ![Screenshot_2024-05-17-22-25-29-373_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/cdcee15f-3b09-4edc-9ec7-203e1dbab9f0)
> 

Did you read the whole issue properly?

The corners are sharp **when the lyrics are enabled**

**Comment by fast4x** [comment]
Done, available from version 0.6.36
