### ISSUE TITLE
Show background color in Lyrics bug

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#1899]
### Steps to reproduce the bug

1. Enable option "Show background color in Lyrics" in settings
2. Background colors in lyrics don't appear 🤔

https://github.com/fast4x/RiMusic/assets/76595855/7d46e7a5-14ab-4a30-8e7c-a11847d587a7

### Expected behavior

Expected to see background colors in lyrics

### Actual behavior

Background colors option in settings does nothing :(

### RiMusic version

0.6.35

### Android version

Android 13

**Comment by NikunjKhangwal** [comment]
Working here but it's like a solid color instead of blurred and mess up the text color too making the lyrics unreadable.

![IMG_20240518_085453](https://github.com/fast4x/RiMusic/assets/99175083/d189adce-3621-4401-8868-8b9ebff70f03)

**Comment by aneesh1122** [comment]
> Working here but it's like a solid color instead of blurred and mess up the text color too making the lyrics unreadable.
> 
> ![IMG_20240518_085453](https://github.com/fast4x/RiMusic/assets/99175083/d189adce-3621-4401-8868-8b9ebff70f03)
> 

I'm the one who requested this and I asked for the background in the full screen mode 😅

**Comment by fast4x** [comment]
yes is a solid color for now soon I'll add other background
