### ISSUE TITLE
If possible please reduce the font size of song name and artist name in the player 

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#19]
### Description

 The player doesnt show full name of the artist or song name if the name is big so if possible please reduce the font size of the song name and artist name
![IMG_20231013_085516](https://github.com/fast4x/RiMusic/assets/127825700/4076a2b9-df45-4c4a-8c06-ef24f70d7176)
![IMG_20231013_085453](https://github.com/fast4x/RiMusic/assets/127825700/4aadbdd0-1e95-42b1-a727-a770c8e6f6ed)

### Suggested Solution

Reduction of the font size will most probably solve it

### Alternatives
Adding marque

**Comment by fast4x** [comment]
Ok

**Comment by fast4x** [comment]
Font size decreased, but on the length of the title, it is truncated, it's normal.

**Comment by siggi1984** [comment]
> Font size decreased, but on the length of the title, it is truncated, it's normal. Available from 0.6.5 version

Regarding the display of the track length, I find Harmony Music's solution very good.

Maybe you have a look at it.

https://github.com/anandnet/Harmony-Music

**Comment by fast4x** [comment]
Yes, it's a good solution

**Comment by fast4x** [comment]
Implemented scrolling text for title and artists labels on player.
Available from version 0.6.6
