### ISSUE TITLE
small window

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1900]
### Steps to reproduce the bug

go to the player, look at the bottom of it, and you will notice the detail

### Expected behavior

The expected behavior would be for all player content to be clean, 

### Actual behavior

but there is a small part where the back tab detail is filtered.

### Screenshots/Screen recordings

![Screenshot_2024-05-17-21-58-36-868_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/fb519766-b6ea-4a54-9f3a-5ef9e96ffefd)

### RiMusic version

0.6.35

### Android version

Android 13

**Comment by aneesh1122** [comment]
> ### Steps to reproduce the bug
> 
> go to the player, look at the bottom of it, and you will notice the detail
> 
> ### Expected behavior
> 
> The expected behavior would be for all player content to be clean, 
> 
> ### Actual behavior
> 
> but there is a small part where the back tab detail is filtered.
> 
> ### Screenshots/Screen recordings
> 
> ![Screenshot_2024-05-17-21-58-36-868_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/fb519766-b6ea-4a54-9f3a-5ef9e96ffefd)
> 
> 
> ### Logs
> 
> _No response_
> 
> ### RiMusic version
> 
> 0.6.35
> 
> ### Android version
> 
> Android 13
> 
> ### Additional information
> 
> _No response_

This happens only when swiping up and down. Right?

**Comment by JeePopuwu** [comment]
> > ### Pasos para reproducir el error.
> > Ve al reproductor, mira la parte inferior y notarás el detalle.
> > ### Comportamiento esperado
> > El comportamiento esperado sería que todo el contenido del reproductor esté limpio,
> > ### Comportamiento real
> > pero hay una pequeña parte donde se filtra el detalle de la pestaña trasera.
> > ### Capturas de pantalla/Grabaciones de pantalla
> > ![Captura de pantalla_2024-05-17-21-58-36-868_it fast4x rimusic](https://private-user-images.githubusercontent.com/159836335/331762201-fb519766-b6ea-4a54-9f3a-5ef9e96ffefd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMDk3MDYsIm5iZiI6MTcxNjAwOTQwNiwicGF0aCI6Ii8xNTk4MzYzMzUvMzMxNzYyMjAxLWZiNTE5NzY2LWI2ZWEtNGE1NC05ZjNhLTVlZjllOTZmZmVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwNTE2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjZjY2JhNzViOTlmYjE5NmI3NTAzMTg2MWRmM2FmYWUwMDQ4ZmFkYmMxZjBkMThjYTg4MTM0ZmUxNDU5ZDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GLCSMGD7-oZ33WmAI4btGO3S6vs-ZsCa42IGOs0Eb3s)
> > ### Registros
> > _Ninguna respuesta_
> > ### Versión RiMusic
> > 0.6.35
> > ### versión de Android
> > androide 13
> > ### Información adicional
> > _Ninguna respuesta_
> 
> Esto sucede solo al deslizar el dedo hacia arriba y hacia abajo y cuando tienes una cubierta borrosa como fondo. ¿Bien?

I thinks so
