### ISSUE TITLE
blurred cover background issue

### ISSUE THREAD

**Issue by Marcelo1565** [fast4x/RiMusic#1901]
### Description

If the background is white, the letters and options barely appear.

### Suggested Solution

Perhaps, highlight the letters, or the option to add background to the letters.

### Alternatives

Change the color of the letters depending on whether the cover is more white.

**Comment by fast4x** [comment]
letter color is based on theme... use dynamic or other

**Comment by veloal** [comment]
it is not the theme, but the theme mode.

https://github.com/fast4x/RiMusic/assets/170187968/0ffb41d7-e482-44e4-8f20-66345e2de0ef

as @Marcelo1565 says, maybe highlight the letters or put shadow (white, black,...) 

great job!!!
