### ISSUE TITLE
[Feature]: Option to replace "Songs" with "Favourites"

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1902]
### Description

I basically don't use the songs section of app at all. It's the only redundant button in navigation bar for me while i use others daily. 

![IMG_20240518_095307](https://github.com/fast4x/RiMusic/assets/99175083/a153c309-cd6a-4f41-8be4-0845436b02be)

### Suggested Solution

Can you implement a option to replace the songs section with favourites from library? It'll be much easier to access favourites this way.

**Comment by fast4x** [comment]
i can add a filter icon in songs section...

**Comment by fast4x** [comment]
maybe i can try to change... if not possible I'll add filter..

**Comment by NikunjKhangwal** [comment]
Ok
If it's easier then don't change the icons for now. Only try replacing the click action of those two. Icons can be improved later as long as the functionality works.

**Comment by aneesh1122** [comment]
#1812 asked for something similar.

Instead of only favourites he suggested to move everything to the songs section.

**Comment by fast4x** [comment]
No, absolutely, isn't planned.

**Comment by aneesh1122** [comment]
> No, absolutely, isn't planned.

But you said you liked everything in his suggestions 😅

One of them was to move everything from the library and put it in songs and the Library would have only playlists

**Comment by NikunjKhangwal** [comment]
This one is added too. Implemented tag is needed.

**Comment by fast4x** [comment]
yes thanks
