### ISSUE TITLE
[Feature]: Fluid gradient background behind action bar

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1903]
### Description

Love the new fluid gradient background. It's basically a upgrade to old gradient background while still not making it too messy. The only thing I'm missing is the action bar background doesn't have gradient so it doesn't look seamless.

### Suggested Solution

Expand fluid gradient to show up behind action bar as well just like old gradient does.

![IMG_20240518_100646](https://github.com/fast4x/RiMusic/assets/99175083/13448516-2363-42d7-82d4-2736db74a264)

**Comment by fast4x** [comment]
Improved, available in version 0.6.36

**Comment by NikunjKhangwal** [comment]
Thanks.
Definitely a big improvement over last one. Now at least it changes color too. Keep improving it further 💚

![IMG_20240524_225654](https://github.com/fast4x/RiMusic/assets/99175083/a00e9c91-6846-4d9b-a686-d6b92cb3387a)
