### ISSUE TITLE
[Feature]: Add Artists and Album button in menu from library

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1904]
### Description

When you play a song from library (Favourites, Playlists, Cached, Downloaded) and click on 3 dots menu, it doesn't show album and artists option. While the same song played from search, album and artist page does.

![IMG_20240518_101510](https://github.com/fast4x/RiMusic/assets/99175083/a7f4add8-b946-4e8e-a7bb-0ce5931f4450)

### Suggested Solution

Add album and artists option in library items as well.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.36

**Comment by aneesh1122** [comment]
@NikunjKhangwal you know that you can go to artists or albums page by simply touching the artist's name or song's name respectively in the player. right?

**Comment by NikunjKhangwal** [comment]
I know but the touch area of artist is small and closer to timeline in vimusic style. Also now you don't have to be on playing screen and it was easy to implement so i suggested it.

**Comment by NikunjKhangwal** [comment]
@fast4x I also got this crash when clicking on artist name from playing screen. Please take a look

`FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 12918
java.lang.ClassCastException: b3.d cannot be cast to b3.p
	at C0.l.n1(SourceFile:95)
	at H5.h.v(SourceFile:11)
	at O5.a.l(SourceFile:9)
	at k6.w.v(SourceFile:7)
	at f6.a.l(SourceFile:23)
	at O5.a.l(SourceFile:32)
	at f6.I.run(SourceFile:95)
	at androidx.compose.ui.platform.d0.t0(SourceFile:7)
	at androidx.compose.ui.platform.c0.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
	Suppressed: k6.h: [androidx.compose.ui.platform.D0@1ab1145, J.g@577909a, u0{Cancelling}@313adcb, d0@45709a8]`

**Comment by aneesh1122** [comment]
> @fast4x I also got this crash when clicking on artist name from playing screen. Please take a look
> 
> `FATAL EXCEPTION: main
> Process: it.fast4x.rimusic, PID: 12918
> java.lang.ClassCastException: b3.d cannot be cast to b3.p
> 	at C0.l.n1(SourceFile:95)
> 	at H5.h.v(SourceFile:11)
> 	at O5.a.l(SourceFile:9)
> 	at k6.w.v(SourceFile:7)
> 	at f6.a.l(SourceFile:23)
> 	at O5.a.l(SourceFile:32)
> 	at f6.I.run(SourceFile:95)
> 	at androidx.compose.ui.platform.d0.t0(SourceFile:7)
> 	at androidx.compose.ui.platform.c0.run(SourceFile:3)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:210)
> 	at android.os.Looper.loop(Looper.java:299)
> 	at android.app.ActivityThread.main(ActivityThread.java:8280)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
> 	Suppressed: k6.h: [androidx.compose.ui.platform.D0@1ab1145, J.g@577909a, u0{Cancelling}@313adcb, d0@45709a8]`

Does it happen with every song? If not, mention the name of the song or link where you are facing this problem

**Comment by NikunjKhangwal** [comment]
> Does it happen with every song? If not, mention the name of the song or link where you are facing this problem

It's possibly a UI related bug, doesn't have anything to do with specific song.

**Comment by aneesh1122** [comment]
>  > Does it happen with every song? If not, mention the name of the song or link where you are facing this problem
> 
> It's possibly a UI related bug, doesn't have anything to do with specific song.

Not crashing in my case. Maybe clear your cache or reinstall. Might be because of your mobile too.

Let's see what fast4x says.

**Comment by fast4x** [comment]
Hi, i haven't reproduced this bug, it work. Add link to song please.

**Comment by NikunjKhangwal** [comment]
I don't remember now. Well it happened once so no big deal. Ignore it for now.

**Comment by NikunjKhangwal** [comment]
I don't remember now. Well it happened once so no big deal. Ignore it for time being.
