### ISSUE TITLE
[Feature]: Changes in lyrics screen

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1909]
### Description

![Lyrics 2](https://github.com/fast4x/RiMusic/assets/45353488/c96fc2fd-c7e6-4522-a01a-ccf58a31b412)
![331777716-0fde398f-5dcf-41c9-a0d8-fe7c919592d0](https://github.com/fast4x/RiMusic/assets/45353488/aaa0c04d-0cb0-472a-8294-01964f90098d)

### Suggested Solution

This way it looks better. You can either add glow or outline. Both will be fine

**Comment by aneesh1122** [comment]
#1903 #1901 #1900 #1899 #1898

**Comment by aneesh1122** [comment]
#1899 #1898

**Comment by NikunjKhangwal** [comment]
You can already change the lyrics size from that Aa button and make cover art corners round from settings.

**Comment by aneesh1122** [comment]
> You can already change the lyrics size from that Aa button and make cover art corners round from settings.

look at the left side of the first photo. that's the biggest you can make them. I suggested to make them bigger.

Cover art corners are rounded when lyrics are not enabled. enable the lyrics and you'll understand what I'm saying

**Comment by NikunjKhangwal** [comment]
Oh! Ok, Makes sense
Tbh i never noticed the corners with lyrics enabled because i always play lyrics in fullscreen

**Comment by fast4x** [comment]
Background will not removed, will be an option same blurred or other type

**Comment by aneesh1122** [comment]
> Background will not removed, will be an option same blurred or other type

okay. do you like rest of the things?

**Comment by fast4x** [comment]
yes

**Comment by aneesh1122** [comment]
> yes

If I may suggest one more, please also consider having this as one of the background options
![Screenshot_2024-05-11-17-06-55-643_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/45353488/77a8fe6d-11d5-407c-acba-1220fb89a113)
