### ISSUE TITLE
Problems in player

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1910]
### Steps to reproduce the bug

Bug 1:
Player buttons were changed in appearance with the latest update (0.6.35). They now have a black shadow and are no longer round even when the default play button is selected.
The new play button looks significantly less visually appealing (to me; some might like it). I suggest adding an option to use the old play button (the round one without a shadow).

Bug 2:
The player (and also the entire app) is extremely laggy when on the 'Quick Picks' tab. This has been the case since many versions ago when the new quick picks page was added.
On other tabs, such as songs and the settings page, performance is fine. I request a fix to this issue as it has been bothering me for a long time.

Bug 3:
In the player, at the bottom, occasionally a small part of the page being the player can be seen (highlighted in screenshot).

### Expected behavior

App isn't laggy, player buttons are round and without a shadow

### Actual behavior

App is laggy, player buttons are square even when the default play button is selected. There is no option to disable shadow

### Screenshots/Screen recordings

![Screenshot_20240518-140551](https://github.com/fast4x/RiMusic/assets/90613992/d2a3586b-5ba1-4bd9-a4bb-360a2a84f91e)

This demonstrates the issue at the bottom of the player and the issue with player buttons.

https://github.com/fast4x/RiMusic/assets/90613992/c36731b3-88db-49d1-a1e6-b632ce91210f

And this demonstrates the issue of lag, which primarily occurs in the quick picks tab, but also somewhat (to a lesser extent) in other tabs. All is well in the settings page.

### RiMusic version

0.6.35

### Android version

Android 11

**Comment by privacyfreak84** [comment]
And again, some assistance with #1693 would be really appreciated

**Comment by Lolozweipunktnull** [comment]
I also think that the player buttons should go back to the previous design for some themes. I can see that they are necessary for the new themes (e.g. the blurred cover), but for the "traditional" older themes it destroys the minimalist look. This is also the case for the "gradient background from theme" theme. Also, the shadow around the cover isn't needed for these themes.

**Comment by fast4x** [comment]
> I also think that the player buttons should go back to the previous design for some themes. I can see that they are necessary for the new themes (e.g. the blurred cover), but for the "traditional" older themes it destroys the minimalist look. This is also the case for the "gradient background from theme" theme. Also, the shadow around the cover isn't needed for these themes.

make sense, ok

**Comment by privacyfreak84** [comment]
@fast4x So will this be implemented?

**Comment by fast4x** [comment]
yes much of your reported changes will be done.

**Comment by fast4x** [comment]
Bug 1, implemented Player controls type, you can change buttons type from appearance settings.
Available from version 0.6.35

Bug 2, no reproduced laggy or any other bug in quick pics
Bug3, will be fixed with other implementations

**Comment by privacyfreak84** [comment]
> Bug 2, no reproduced laggy or any other bug in quick pics

That's odd. Still, any idea what could be causing it? It happened specifically after the new quick picks page was implemented.

Thanks for implementing the rest of the changes!
