### ISSUE TITLE
[Feature]: ViMusic style player adjustments

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1912]
### Description

Currently the items in vimusic player are slightly on the upper side. The artwork is almost touching the status bar. (It's also touching the camera notch of my phone which i can't show in screenshot)
Ofc i can make the artwork smaller but then everything becomes small (for example timeline) and i love the bigger artwork more.

How it looks now & My suggestion:-
![Picsart_24-05-18_15-21-47-296](https://github.com/fast4x/RiMusic/assets/99175083/e5450a9e-2693-49e9-a223-f751c5d211d8)

### Suggested Solution

Move artwork, song name, timeline and control buttons slightly on the lower side so it looks better.

![IMG_20240518_151647](https://github.com/fast4x/RiMusic/assets/99175083/e0da71d7-5f29-4942-9a6c-63cffdf28b2f)

**Comment by ALMIGHTY-VC** [comment]
Judging by how your seeing buttons if u try the full screen mode of hyperos and force the app to use full screen u might take it down a lil

**Comment by ALMIGHTY-VC** [comment]
See here i use full screen in my miui 11 and i have a water drop notch but yeah it stays below the water drop
![Screenshot_2024-05-22-08-42-59-585_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/112297620/5f1343f9-5f4c-45db-aa92-19f849dde493)

**Comment by NikunjKhangwal** [comment]
Just noticed the implemented tag. Problem solved :)

**Comment by ALMIGHTY-VC** [comment]
> Just noticed the implemented tag. Problem solved :)

Yes then u can now freely thank the dev and close this thread so others which need the fixing can be shown

**Comment by NikunjKhangwal** [comment]
> Yes then u can now freely thank the dev and close this thread so others which need the fixing can be shown

Threads only gets closed when the release is actually out for everyone. There's a reason why dev tag these labels so he can keep track of issues and filter things out. (I'm old user here)
