### ISSUE TITLE
[Feature]: Podcast

### ISSUE THREAD

**Issue by irondave** [fast4x/RiMusic#1913]
### Description

Since YouTube Music is become a centralized destination for podcasts can you add this features too?
A dedicated podcast tab and the possibility to switch between audio and video versions of shows would be nice.
Thank you for your work.

### Suggested Solution

A dedicated podcast tab and the possibility to switch between audio and video versions of shows.

**Comment by dAtA-TRoN** [comment]
In my opinion, that would dilute the original idea of RiMusic too much. Additionally, RiMusic does not function like a podcast player.

**Comment by fast4x** [comment]
Thanks for idea is ok, but not planned, i agree with @dAtA-TRoN @ikanakova

**Comment by irondave** [comment]
Okey dokey... Thanks for answer

**Comment by fast4x** [comment]
Work in progress...

**Comment by fast4x** [comment]
Implemented podcasts in search page, available from version 0.6.44
