### ISSUE TITLE
[Feature]: Custom Adjustment

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [fast4x/RiMusic#1922]
### Description

The problem is that the ui elements it works for some phones and for some not so is there a way to adjust ui elements manually. 
![Screenshot_2024-05-18-22-47-57-810_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/112297620/bda16540-567c-4cc7-9231-45776a7aee08)
Like here the search button is at a weird position compared to my device screen but since it has not been reported by anyone then i thought its due to my device so want to manually implement the ui elements

### Suggested Solution

An option to pick and change the position to ui buttons if possible

### Alternatives

Sorry currently none

### Additional Context

Extra info:-  my screen size is 6.26 inches
Aspect ratio:-19:9

THANKS FOR READING

**Comment by aneesh1122** [comment]
You can drag the search button wherever you want. Hold the search button and place it where you want and it will stay there

**Comment by ALMIGHTY-VC** [comment]
> You can drag the search button wherever you want. Hold the search button and place it where you want and it will stay there

Oh thanks bro🙏
