### ISSUE TITLE
Bug teks

### ISSUE THREAD

**Issue by Grevellia123** [fast4x/RiMusic#1923]
### Steps to reproduce the bug

Click the song Title, after that click the download button 
![Screenshot_2024-05-19-00-19-55-977_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/134467260/789d9c0f-1baa-42a9-99b4-25f7a9baae36)

### Expected behavior

I've never downloaded that song but why does the text appear "are you sure you want to delete download"

### Actual behavior

Text like that shouldn't appear because I haven't downloaded the song

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/134467260/0d65a5a6-9ed0-4d29-bb25-35cd13b0c7d0

### 

> ****

### RiMusic version

0.6.35

### Android version

Android 12

### Additional information

Poco M3
MIUI 14.0.2

**Comment by aneesh1122** [comment]
"Download all" and "Delete all" have different icons.

What you've opened is a "single" which is treated as albums so it will show both the icons.

So, not a bug.

**Comment by fast4x** [comment]
Hold on icon will show popup info.
