### ISSUE TITLE
New feature for downloaded songs

### ISSUE THREAD

**Issue by Criis25** [fast4x/RiMusic#1925]
### Description

A convenient feature for downloaded songs is that they are separated by album into independent folders and not in a list with all the others.

### Suggested Solution

Simply separate the downloads by album and each album has different folders and they are not all in the same list, only separated by album

**Comment by fast4x** [comment]
Downloaded songs isn't a separate entity. If you want see downloaded song in one album, go to album and look downloaded icon in every songs...
Also you can download all not downloaded songs in one album.
