### ISSUE TITLE
[Feature]: sync configuration across multiple devices

### ISSUE THREAD

**Issue by cicerolps** [fast4x/RiMusic#1927]
### Description

I think could be a easy and useful implementation.

Pair multiple devices and sync configuration across all them

Almost like Syncthing, whiteout a user account

### Suggested Solution

Syncthing could do this if the file data was saved in a public folder on the device

**Comment by dAtA-TRoN** [comment]
Cool idea. I would love to be able to update my tablet through my phone and vice versa without having to fumble with importing and exporting playlists. Such a feature would be a great added value for RiMusic and would set it apart. From my layman’s perspective, this seems reasonably achievable. Perhaps it could be done via Bluetooth. The import/export process could then be initiated manually or set to occur on a predetermined schedule. All RiMusic would need to do is automate the import/export tasks and transfer the data between devices. I understand this would be a significant undertaking and not something that can be programmed quickly. However, I believe it would be well worth the effort, as it would greatly enhance the app.

**Comment by aneesh1122** [comment]
[Harmony Music](https://github.com/anandnet/Harmony-Music) uses [Piped](https://github.com/TeamPiped/Piped) for playlist integration. What changes you make in harmony app is changed in original piped playlist too. Changes made in playlist from Piped website is auto-synced in harmony music.

Piped is also privacy friendly. The whole point of Piped is to not give any data to google.

**Comment by fast4x** [comment]
Started development of piped account and synchronization 🎉

**Comment by dAtA-TRoN** [comment]
> Started development of piped account and synchronization 🎉

https://github.com/fast4x/RiMusic/assets/71184627/693fb115-dd1f-4ac6-b017-bf1ac3b912d1

**Comment by fast4x** [comment]
Implemented piped playlists syncronization, available from version 0.6.39

**Comment by dAtA-TRoN** [comment]
Wow 😮.
