### ISSUE TITLE
Audio y Crossfade.

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#1932]
### Description

La calidad de audio es buena pero enserio deberían mejorarla ya que los grabes se notan bastante y estaría perfecto que existiera un balance en el audio, se que hay un apartado para mejorar la calidad pero incluso si le pongo en la calidad mas baja y alta se notan mucho, me gustaría que el audio sea tipo HD 😔

### Suggested Solution

N/A

### Alternatives

N/A

### Additional Context

N/A

**Comment by fast4x** [comment]
The audio is hd type but depends on the YTM api so it is not manageable by RiMusic independently, at most you can set the quality level in the settings.
