### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Yokcerpr** [fast4x/RiMusic#1935]
### Steps to reproduce the bug

Bueno lo primero fue que active unas opciones y lo que paso es que salí de la aplicación y como yo hago ejercicio cuando pongo mi temporizador o subo volumen con la app reproduciendo la canción se me lagea demasiado el teléfono y cheque y si era la aplicación por qué las demás apps m van bien hasta pienso que tiene virus 

### Expected behavior

Bueno lo que quisiera es que no me pasará ese error de lag en todo mi teléfono hasta creo que es virus pero no por que la app me aparece bien en Xiaomi y creo es por las descargas

### Actual behavior

Sucedió esto desde la versión 0.6.33 y 34 

### RiMusic version

0.6.34

### Android version

Android 14

### Additional information

Ayúdenme con este error la verdad me encanta esta aplicación solo es eso que se lagea cuando salgo y me da tristeza es buena app solo chequen eso a lo mejor es mi versión de android 14 o no se

**Comment by fast4x** [comment]
RiMusic has no virus, I can advise you not to use effects on the player, the timer slowdown did not come out during development.
