### ISSUE TITLE
Toggle the bar at the bottom of the player on and off 

### ISSUE THREAD

**Issue by zippostar** [fast4x/RiMusic#1940]
### Description

can you install this?

### Suggested Solution

can you install this?

**Comment by fast4x** [comment]
You mean this?
![Screenshot_2024-05-19-12-15-45-273_it.fast4x.rimusic.debug-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/29f658da-6d3f-4e3e-8978-7ecff807c203)

**Comment by fast4x** [comment]
you can disable next and previous songs...
other will be develped in the future with new players...
