### ISSUE TITLE
Bug in Player Appearance

### ISSUE THREAD

**Issue by BeInvisible07** [fast4x/RiMusic#1943]
### Steps to reproduce the bug

Play any songs

### Expected behavior

Need minimalistic look

### Actual behavior

New look of **Player Appearance** is so funky.

### Screenshots/Screen recordings

1.New look of **Player Appearance** is so funky & pls remove the background shadow for player menu button and album cover image in **light mode** but it looks good in **dark mode**.
![Screenshot_2024-05-19-16-44-15-175_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/152383072/d8c0c31d-6b31-4e08-a703-5a259933df3d)
2.And some times the album cover image is not showing up correctly in notification player menu 
![Screenshot_2024-05-19-17-02-50-329_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/152383072/934bd131-6c85-4397-a731-aa0dac0d02a8)

### RiMusic version

0.6.35

### Android version

Android 12

**Comment by privacyfreak84** [comment]
I want this + #1908, #1909 and #1910 to be resolved. It really does bother me

**Comment by fast4x** [comment]
In new version 0.6.35 will be a setting for change controls type Modern or Essential (no shadow, previous style)

**Comment by BeInvisible07** [comment]
> In new version 0.6.35 will be a setting for change controls type Modern or Essential (no shadow, previous style)

Bro but now I am missing **album cover image in notification shade player** & i have also noticed now that there was **little gap** in player bottom menu.
![Screenshot_2024-05-20-00-17-14-268_com android chrome](https://github.com/fast4x/RiMusic/assets/152383072/bbc43594-9466-4a2f-b246-bc42a474281b)
![IMG_20240520_001848](https://github.com/fast4x/RiMusic/assets/152383072/2ae80970-f8a5-4cca-b729-dd54c797562a)

**Comment by fast4x** [comment]
I know

**Comment by BeInvisible07** [comment]
> I know

Okay 👍
