### ISSUE TITLE
[Feature]: New navigation bar and floating player

### ISSUE THREAD

**Issue by odamaasio** [fast4x/RiMusic#1946]
### Description

Something that bothers not only me but also other people is where the navigation bar is present and where the player is.
People who use the navigation bar at the bottom of the app, most likely got better used to the bottom bar of Spotify.
![Screenshot_20240519-113227_Spotify](https://github.com/fast4x/RiMusic/assets/169945653/c16ddaa0-df02-4137-a878-76aa5e01365c)
Not only with this but also with a floating player.

### Suggested Solution

The solution I bring is to place the navigation bar below the floating player. And the navigation bar should be a little transparent and the player have rounded edges.
![688](https://github.com/fast4x/RiMusic/assets/169945653/83468264-336b-410c-9c7a-3b7e85f70901)

**Comment by fast4x** [comment]
look #1812

**Comment by dAtA-TRoN** [comment]
@ Mr fast4x

If you finally get the minimized player above the navigation bar, I will never make a request again (well, I can probably hold out for 4 weeks 😅).

**Comment by fast4x** [comment]
I'm not Mandrake magician https://en.m.wikipedia.org/wiki/Mandrake_the_Magician 😂😂😂😂

**Comment by dAtA-TRoN** [comment]
> I'm not Mandrake magician https://en.m.wikipedia.org/wiki/Mandrake_the_Magician 😂😂😂😂

Well, at least no one has ever seen the two of you together in the same room, right 😏!?

**Comment by fast4x** [comment]
> @ Mr fast4x
> 
> If you finally get the minimized player above the navigation bar, I will never make a request again (well, I can probably hold out for 4 weeks 😅).

#1812
![giphy (1)](https://github.com/fast4x/RiMusic/assets/1484476/c576ce7f-ee9b-49f7-87ee-d9443dfb67c8)

**Comment by dAtA-TRoN** [comment]
Don't tell me you actually did it 😱.

**Comment by fast4x** [comment]
oh oh it seems yes.... 
![giphy.gif](https://github.com/fast4x/RiMusic/assets/1484476/58714331-9915-4738-9b81-ea019816c0c0)

🥳

**Comment by aneesh1122** [comment]
> @ Mr fast4x
> 
> If you finally get the minimized player above the navigation bar, I will never make a request again (well, I can probably hold out for 4 weeks 😅).

You for the next 4 weeks
![b16.jpg](https://github.com/fast4x/RiMusic/assets/45353488/9a31fe10-26d3-403a-b24c-5872b41e3f4d)

**Comment by fast4x** [comment]
![giphy (1).gif](https://github.com/fast4x/RiMusic/assets/1484476/850e3fb8-25bb-4f38-b77e-89fc0a415ddb)

**Comment by ikanakova** [comment]
I think dAtA-TRoN has another plan in mind:

![time machine](https://media1.giphy.com/media/oNhAOVr7eLynu/giphy.gif?cid=6c09b952llhbnsszaim83z1slwr9e1kjhuw8sfshfvb6jp60&ep=v1_internal_gif_by_id&rid=giphy.gif&ct=g)

🤣🤣🤣

**Comment by fast4x** [comment]
![giphy (2).gif](https://github.com/fast4x/RiMusic/assets/1484476/38879ff5-b475-439e-9c1e-1626fe143570)

**Comment by dAtA-TRoN** [comment]
> You for the next 4 weeks

> I think dAtA-TRoN has another plan in mind:

Literally Me, when I get an amazing new idea by tomorrow:

https://github.com/fast4x/RiMusic/assets/71184627/c40da3dc-c384-4b2f-a3e6-d4bc1278968c

**Comment by aneesh1122** [comment]
> > You for the next 4 weeks
> 
> > I think dAtA-TRoN has another plan in mind:
> 
> Literally Me, when I get an 'amazing new idea' by tomorrow:
> 
> https://github.com/fast4x/RiMusic/assets/71184627/c40da3dc-c384-4b2f-a3e6-d4bc1278968c

More like this
![of959.jpg](https://github.com/fast4x/RiMusic/assets/45353488/1c913bca-29d6-458f-8ca8-c33bc2b033aa)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.36

**Comment by dAtA-TRoN** [comment]
Could you fine-tune it and give it a frosted glass effect? The sharp shapes behind the navbar negatively impact the readability of the icons.

**Comment by aneesh1122** [comment]
> Could you fine-tune it and give it a frosted glass effect? The sharp shapes behind the navbar negatively impact the readability of the icons.
> 
>  YouCut_20240522_100145819.mp4

I say let the come first and try it yourself. The screenshot you've seen actually made the icons a little transparent too. maybe that's why you're not able to read it.

btw your 'frosted glass effect' defeats the whole purpose of making it transparent.

**Comment by dAtA-TRoN** [comment]
> I say let the update come first and try it yourself. The screenshot you've seen actually made the icons a little transparent too. maybe that's why you're not able to read it.\n\nbtw your 'frosted glass effect' defeats the whole purpose of making it transparent.

If it compromises the readability of the app's MAIN NAVIGATION, I can do without it. In my opinion, a frosted glass effect would be a good compromise, as it subtly hints at what's behind while enhancing the overall appearance by creating an illusion of increased visibility. This way, you get the best of both worlds: preserving readability and improving the overall aesthetic.

**Comment by aneesh1122** [comment]
> > I say let the update come first and try it yourself. The screenshot you've seen actually made the icons a little transparent too. maybe that's why you're not able to read it.\n\nbtw your 'frosted glass effect' defeats the whole purpose of making it transparent.
> 
> If it compromises the readability of the app's **main navigation**, I can do without it. In my opinion, a frosted glass effect would be a good compromise, as it subtly hints at what's behind while enhancing the overall appearance by creating an illusion of increased visibility. This way, you get the best of both worlds: preserving readability and improving the overall aesthetic.

Nah. That example you posted is too opaque for me. Make that frosted glass effect transparent then maybe I'll like it.

I'll still wait for the update to come before asking for that though.

**Comment by dAtA-TRoN** [comment]
> Nah. That example you posted is too opaque for me. Make that frosted glass effect transparent then maybe I'll like it.\n\nI'll still wait for the update to come before asking for that though.

That was merely an example, and the only thing I could find quickly to illustrate my point. However, I wholeheartedly agree with you. I also believe it should be much more transparent. I trust fast4x to naturally integrate things in a way that ultimately aligns.

**Comment by fast4x** [comment]
For now i prefer not to touch before new layout version...

**Comment by dAtA-TRoN** [comment]
> For now i prefer not to touch before new layout version...

Then it would be wonderful if you could at least make it optional. I find it much clearer the way it was before.
