### ISSUE TITLE
[Feature]: Adjust the rendering of video thumbnails

### ISSUE THREAD

**Issue by Cszyn** [fast4x/RiMusic#1947]
### Description

I have been trying out [SpMp](https://github.com/toasterofbread/spmp) and their video thumbnail rendering/scaling is very impressive, I'm wondering if something similar can be implemented/adjusted as well. I'm aware that Ri is not a focused on video playback, but I think this would be a huge QOL improvement for many users

![Screenshot_2024-05-19-18-36-47-866_it fast4x rimusic__1716136413359](https://github.com/fast4x/RiMusic/assets/147027531/27a3c868-9e2c-46a2-96fe-d1c7b48e305c)
![Screenshot_2024-05-19-18-37-14-951_it fast4x rimusic__1716136413343](https://github.com/fast4x/RiMusic/assets/147027531/b27950eb-5115-4017-86d7-be32ca0ea9b5)
![Screenshot_2024-05-19-18-39-31-108_it fast4x rimusic__Screenshot_2024-05-19-18-39-35-536_com toasterofbread spmp](https://github.com/fast4x/RiMusic/assets/147027531/d10366de-8319-4e3f-9446-139a4d60fd2e)

### Suggested Solution

I have no knowledge on graphic design, so I can't say much about a solution itself

### Additional Context

I like Ri's UI a lot, but this does bug me every time I play a video.

**Comment by fast4x** [comment]
Improved quality, available from version 0.6.36

**Comment by Cszyn** [comment]
![spmp__symphony__rimusic](https://github.com/fast4x/RiMusic/assets/147027531/ad252e83-f596-4ee8-a805-18794d6365c0)

The quality did noticeably improve, but the scaling is still off by a good chunk. 1. image is once more [SpMp](https://github.com/toasterofbread/spmp) the second is [symphony](https://github.com/zyrouge/symphony) local music player song downloaded with Seal. and the third is obviously Ri

**Comment by fast4x** [comment]
Do you can link this song please?

**Comment by Cszyn** [comment]
> Do you can link this song please?
https://music.youtube.com/watch?v=YUobVENA0DE

**Comment by Cszyn** [comment]
> > Do you can link this song please?
> > https://music.youtube.com/watch?v=YUobVENA0DE

But any video shoud produce the same result of black bars appearing

**Comment by fast4x** [comment]
I'll check method to expand picture, thanks

**Comment by bbyeen** [comment]
> I'll check method to expand picture, thanks

If it's not priority I can take a look at it.

**Comment by fast4x** [comment]
Ok, but after release...37 because source is much modified.
