### ISSUE TITLE
[Feature]: Add 'Favorite' icon on songs

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1949]
### Description

Since melody icon is removed now #1895 adding favorite icon on songs will be great. It will be easy to spot liked songs while searching or browsing the app

### Suggested Solution

![Screenshot_2024-05-20-01-06-15-837_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/365d25a3-4cc3-4bac-ae89-228291f1b22d)

**Comment by fast4x** [comment]
Yes is nice

**Comment by aneesh1122** [comment]
> Yes is nice 

Thanks. I knew you would like it 

*pun intended*

**Comment by aneesh1122** [comment]
Hey, a little change in the request.

Please add the heart icon such that half of the heart is out of the album cover. It will be much easier to notice the heart icon.

**Comment by fast4x** [comment]
Implemented available from version 0.6.36

**Comment by aneesh1122** [comment]
Thanks man. you're the best
