### ISSUE TITLE
Save album covers

### ISSUE THREAD

**Issue by Snyret** [fast4x/RiMusic#195]
### Description

Add the option to save images in the app.

### Suggested Solution

Add it on the more options section.

**Comment by fast4x** [comment]
Can you explain better

**Comment by fast4x** [comment]
Ah ok thanks

**Comment by OrangeZXZ** [comment]
@fast4x since we can get the album cover link i think this is almost done you could try

I think just opening the image link is enough (maybe google has some settings that ads itself to the link to automatically download an image link)

**Comment by fast4x** [comment]
Yes, good idea, show link to download image... nice...

**Comment by OrangeZXZ** [comment]
> or clicking in image cover download it...

maybe not it will make accidental downloads

**Comment by fast4x** [comment]
ahahah the best, we add an icon

**Comment by fast4x** [comment]
Implemented, for now quality isn't max possible, in the future will be better possible.
Available from version 0.6.26

**Comment by sayyid5416** [comment]
> Implemented, for now quality isn't max possible, in the future will be better possible. Available from version 0.6.26

I think if this is going to be implemented it should be inside 3 dots menu.

**Comment by OrangeZXZ** [comment]
> > Implemented, for now quality isn't max possible, in the future will be better possible. Available from version 0.6.26
> 
> I think if this is going to be implemented it should be inside 3 dots menu.

maybe next to the edit buttons and only on the album page?

**Comment by NikunjKhangwal** [comment]
Is it only available for album covers or singles as well?

**Comment by fast4x** [comment]
Albums and artists cover, would you like the function in other places?

**Comment by sayyid5416** [comment]
> Albums and artists cover, would you like the function in other places?

Can this download button be added inside some context menu. It doesn't look good where it is now.

**Comment by fast4x** [comment]
Inside a menu requires more click to save...

**Comment by OrangeZXZ** [comment]
> Inside a menu requires more click to save...

i think it isn't that bad there but it is just off-placed (for me it isn't in the corner)

**Comment by sayyid5416** [comment]
> Inside a menu requires more click to save...

Yes, but how often people save these album or artist covers? It should not be upfront.

For ex: _**change album cover**_ is placed in context menu.

**Comment by fast4x** [comment]
> > Inside a menu requires more click to save...
> 
> i think it isn't that bad there but it is just off-placed (for me it isn't in the corner)

I did it on purpose, I can move it to the corner

**Comment by fast4x** [comment]
> > Inside a menu requires more click to save...
> 
> Yes, one extra click, but how often people save these album or artist covers? It should not be upfront.
> 
> For ex: _**change album cover**_ is placed in context menu.

i can add also in context menu.

**Comment by sayyid5416** [comment]
> > > Inside a menu requires more click to save...
> > 
> > 
> > Yes, one extra click, but how often people save these album or artist covers? It should not be upfront.
> > For ex: _**change album cover**_ is placed in context menu.
> 
> i can add also in context menu.

I think a function is is used very rarely **_should not_** be upfront. It should be **_only_** in the context menu. _(Obviously if it's not your personal preference)_

**Comment by fast4x** [comment]
This function is used much time...

**Comment by sayyid5416** [comment]
> This function is used much time...

If that's so, then I can't really complain 😅

**Comment by fast4x** [comment]
I add, the quality of the saved file is quite poor, sooner or later someone will ask to increase it.

**Comment by OrangeZXZ** [comment]
> This function is used much time...

Honestly i don't use it because i can find just by searching on google and adding the HD parameter but I can see why people will use them il also try to think a way of implementing this without complainis

**Comment by NikunjKhangwal** [comment]
> Albums and artists cover, would you like the function in other places?

Yes for single trackes as well. So basically make it available for every song. If youtube music allow it ofc. You can add the button in three dots menu or this screen:- 
![IMG_20240316_171010](https://github.com/fast4x/RiMusic/assets/99175083/d6e18ee6-8a59-4117-8413-19a4f9063b72)

**Comment by NikunjKhangwal** [comment]
Same here. It's very low quality, almost unusable. Also downloading pic should be added in songs & artists as well.

**Comment by fast4x** [comment]
yes confirm quality is much poor, in future can try to improve
