### ISSUE TITLE
Two back buttons in ViMusic mode

### ISSUE THREAD

**Issue by Nathaniel466** [fast4x/RiMusic#1951]
### Steps to reproduce the bug

Open Rimusic 
Go to library 
Click on favourites

### Expected behavior

One back button should appear 

### Actual behavior

Two back buttons showed up instead of one kinda annoying 

### Screenshots/Screen recordings

![Screenshot_2024-05-19-13-56-52-143_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/166153675/3bd901de-b5b0-49dd-aa95-a2eb64b0fa69)

### RiMusic version

V0.6.35

### Android version

Android 14

### Additional information

Did I turn on some other setting?

**Comment by fast4x** [comment]
So in ViMusic mode

**Comment by fast4x** [comment]
Fixed, available from version 0.6.36

**Comment by ALMIGHTY-VC** [comment]
> Fixed, available from version 0.6.36

I think it would have been better to make the green one to discover page and the colourless one to just one action back

**Comment by fast4x** [comment]
In new version, library it's different from previous because have new layout #1812
