### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by iamraj-patel** [fast4x/RiMusic#1953]
### Description

Please make this type of application for iOS devices as well 🙏🙏

### Suggested Solution

Please make this type of application for iOS devices as well 🙏🙏

**Comment by JeePopuwu** [comment]
I think you don't understand the meaning of moderated app

**Comment by NikunjKhangwal** [comment]
iOS is terrible. Apple have so many restrictions, they'll never allow something like this. Specially when they offer their own streaming service as Apple Music, it'll hurt their business. iOS doesn't even have a good local music player yet.

**Comment by fast4x** [comment]
Unfortunately at the moment it is not possible, maybe in the future when Apple will change approach to the business? Sorry friend.
Use an Android device and enjoy RiMusic.

**Comment by dAtA-TRoN** [comment]
> Unfortunately at the moment it is not possible, maybe in the future when Apple will change approach to the business? Sorry friend.
> Use an Android device and enjoy RiMusic.

Polite as usual.

![4oov7m-01.jpeg](https://github.com/fast4x/RiMusic/assets/71184627/68bb6b0a-3b80-4af6-b2ae-c6b90c8a8787)

**Comment by fast4x** [comment]
> > Unfortunately at the moment it is not possible, maybe in the future when Apple will change approach to the business? Sorry friend.
> > Use an Android device and enjoy RiMusic.
> 
> Polite as usual.
> 
> ![4oov7m-01.jpeg](https://github.com/fast4x/RiMusic/assets/71184627/68bb6b0a-3b80-4af6-b2ae-c6b90c8a8787)

Thanks

**Comment by Karrq** [comment]
An ipa release would be enough - doesn't need to be on the store

**Comment by fast4x** [comment]
Ipa release? It's possible to install app outside store? I don't know ...

**Comment by mustard007** [comment]
Yep, with developer access and external tool you can install an ipa. (I know spotube app make it)

**Comment by fast4x** [comment]
Interesting, thanks

**Comment by n3rdcub** [comment]
> Interesting, thanks 

At risk of necroing, check out https://www.appdb.to
It's one of the best methods to sideload iOS apps _without_ requiring another PC or weekly syncs. It'll also contain information and tools how to get started creating your own .ipa.

Also, there really isn't an iOS .ipa currently available? 
There's a fake website then pretending to offer an iOS version. You might want to look into getting them taken down. Https://www.rimusic.pro
