### ISSUE TITLE
Add sound normalizer

### ISSUE THREAD

**Issue by Dantoza** [fast4x/RiMusic#1954]
### Description

When i listen to music and i turn 60 db cap on my headphones, some songs are fine, while some are very quiet.

### Suggested Solution

Add a sound normalizer(like spotify)

**Comment by fast4x** [comment]
From ui settings find loudness normalization
![Screenshot_2024-05-20-20-53-23-771_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/820a0f9b-a3f7-4b3e-b298-20e82c039b54)
