### ISSUE TITLE
[Feature]: Importing songs to 'Favorites'

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1955]
### Description

So I finally transferred my liked songs from spotify to RiMusic and I wanted to transfer those songs to my RiMusic 'Favorites'.

### Suggested Solution

Treat 'Favourites' as a playlist where you can import/add songs into it or export songs to an another playlist. Basically how songs can be added to/from different playlists.

**Comment by fast4x** [comment]
Export preferites it's just released

**Comment by aneesh1122** [comment]
> Export favourites it's just released

I want to add multiple songs to favorites at once

**Comment by aneesh1122** [comment]
> Export favourites it's just released

![IMG_20240521_115549.jpg](https://github.com/fast4x/RiMusic/assets/45353488/92e18dc0-e833-4cec-935f-439a32d2e565)

Add 'favorites' here above 'Pinned Playlists'

**Comment by aneesh1122** [comment]
> Export favourites it's just released

Add 'Favorites' Above 'Pinned Playlists' like this
![new list](https://github.com/fast4x/RiMusic/assets/45353488/74d1eb1a-eaf4-4088-991b-f643f43fbc3f)

and when the song is already in 'Favorites' show it like this
![new list 2](https://github.com/fast4x/RiMusic/assets/45353488/103cc7e7-391f-490d-88bc-5805545ce58b)

**Comment by fast4x** [comment]
Woukd can also do this without using playlist logic. You select the songs and mark them as your favorite.

**Comment by fast4x** [comment]
> > Would can also do this without using playlist logic. You select the songs and mark them as your favorite.
> 
> That will also be good but right now select/deselect is not working #1813
> 
> There is also no option to select all.

be quiet I'll fix it

**Comment by dAtA-TRoN** [comment]
> Would can also do this without using playlist logic. You select the songs and mark them as your favorite.

Best way to do it, in my opinion. Favourites should not behaving like any other playlist. It's more of an 'on the go' thing. Otherwise this feature makes no sense.

**Comment by aneesh1122** [comment]
> > Would can also do this without using playlist logic. You select the songs and mark them as your favorite.
> 
> Best way to do it, in my opinion. Favourites should not behaving like any other playlist. It's more of an 'on the fly' thing. Otherwise this feature becomes redundant.

Spotify doesn't agree with you.

-You can add multiple songs at once
-You can delete multiple songs at once
-You can add songs from 'liked' to other playlists(you can do that in RiMusic too with some extra steps)

Now you may ask why do I want to transfer multiple songs to my 'Favorites'. It's because playlists are limited to 5000 songs whereas favorites are unlimited.

I'm not going to force fast4x to add something he doesn't want to buy I disagree that 'Favorites' shouldn't be used as one of the playlists. As a user we should have full control over our collection, including favorites.

**Comment by dAtA-TRoN** [comment]
> Spotify doesn't agree with you.

Bullshit. I already agreed with fast4x position. And which of your mentioned points does he not address in his response!?

**Comment by aneesh1122** [comment]
> I already agreed with fast4x position

so did I because he is the developer of this app and he knows best. I still think it's completely logical to consider 'Favorites' as one of the playlists since it's a part of our collections.

> Then it would be much more logical to lift the limit of the other playlists rather than going through the detour of the favorites list
> And why would you need an extra favorites list then if any other playlist could do the job just as well? That's what I mean by redundant.

It's much easier to add songs to 'Favorites'. Can be done from notification bar or from player so it's very convenient. It's also unlimited. It can be my ultimate collection.

I have like 1500 songs imported from spotify and I want to add them in my favorites list. I also want the freedom to delete multiple songs from favorites if I wish to do so. Right now I have to open every song in player and unlike.

all these problems can be solved if 'favorites' is treated as one of the playlists like spotify does.

As I said, I'll agree with fast4x's final decision because he knows best. I don't have to agree with you though.

**Comment by dAtA-TRoN** [comment]
> I don't have to agree with you though.

You do it automatically, because like you, I stand behind what fast4x said.

**Comment by aneesh1122** [comment]
> > I don't have to agree with you though.
> 
> You do it automatically, because like you, I stand behind what fast4x said.

Well, whatever helps you sleep at night

**Comment by fast4x** [comment]
My point of view is this: in the new logic of RiMusic the list of favorite songs is a section of the general list of songs.
The structural changes of the next version are so many and deep that I can not focus on anything else at the moment.

On one thing I’m sure though, expanding the functionality of favorite songs is an opportunity and so also importing songs into specific sections is a good opportunity.

Favorite songs can’t be treated like a playlist but having a number of features that help manage them better I find it an opportunity for RiMusic.

**Comment by aneesh1122** [comment]
> My point of view is this: in the new logic of RiMusic the list of favorite songs is a section of the general list of songs.
> The structural changes of the next version are so many and deep that I can not focus on anything else at the moment.
> 
> On one thing I’m sure though, expanding the functionality of favorite songs is an opportunity and so also importing songs into specific sections is a good opportunity.
> 
> Favorite songs can’t be treated like a playlist but having a number of features that help manage them better I find it an opportunity for RiMusic.
> 
> 

I'm not in hurry so please concentrate on the new changes you are implementing right now.

When you're done changing things, start changing favorites.

**Comment by dAtA-TRoN** [comment]
> Favorite songs can’t be treated like a playlist but having a number of features that help manage them better I find it an opportunity for RiMusic.

Nicely summarized 😗👌🏼!

**Comment by fast4x** [comment]
And meanwhile...

https://github.com/fast4x/RiMusic/assets/1484476/b777632e-6ff8-4f93-b52b-50de9d2daa5e

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/d16fc333-eff6-45c3-8ece-a4f1f477de6c

**Comment by aneesh1122** [comment]
> 
> https://github.com/fast4x/RiMusic/assets/1484476/d16fc333-eff6-45c3-8ece-a4f1f477de6c
> 
> 

Hey man, I got a new idea and I think you'll like it too. Should I post it here or create a new issue about it?

**Comment by fast4x** [comment]
> > Screen_recording_20240524_092955.mp4
> 
> Hey man, I got a new idea and I think you'll like it too. Should I post it here or create a new issue about it?

Hi, new specific...

**Comment by aneesh1122** [comment]
> > > Screen_recording_20240524_092955.mp4
> > 
> > Hey man, I got a new idea and I think you'll like it too. Should I post it here or create a new issue about it?
> 
> Hi, new specific...

On it

**Comment by fast4x** [comment]
Implemented add to playlist in context menu with selectable songs and import to preferites from exported file, available form version 0.6.56
