### ISSUE TITLE
A little Sugestion 

### ISSUE THREAD

**Issue by PabloMan47** [fast4x/RiMusic#1959]
### Description

The Blurred Background its a little bright, it must be darker, cuz the icons, progress bar and the tittle gets kinda lost on the player.

Now, the buttons and the bar from the bottom, it would be great to add an option to disable the background of them when the blurred background is enabled, cuz the black in them its kinda ugly

![Screenshot_20240521-123619](https://github.com/fast4x/RiMusic/assets/166191281/a07f4e61-d545-46fd-815b-cbe60fdb5815)

### Suggested Solution

I toked the BlackPlayer app as a example

![Screenshot_20240521-123657](https://github.com/fast4x/RiMusic/assets/166191281/2e45d1bc-2fd5-4abd-ab10-671522c8eb8d)

### Additional Context

That's all, the app it's growing and it's so cool to help to it

**Comment by aneesh1122** [comment]
I also think the background is bright and it needs to be darker but the screenshot you posted is too dark for me. You can barely make out what's in the background.

Somewhere in between the 2 would be good.

Maybe @fast4x can implement a 'blur amount' and 'dark shade' slider when the blur background is selected

Like this
![IMG_20240522_082216.jpg](https://github.com/fast4x/RiMusic/assets/45353488/346606ce-6162-4b16-9ec4-5e5a39f1352d)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.37
