### ISSUE TITLE
A little Sugestion x2 haha

### ISSUE THREAD

**Issue by PabloMan47** [fast4x/RiMusic#1961]
### Description

It would be great to add an option to disable the icons beside the tittle of the song and the name of the artist on the player

![IMG-20240521-WA0029](https://github.com/fast4x/RiMusic/assets/166191281/c9a4b753-02f3-4dd4-bb50-402de50f759c)

### Suggested Solution

Once again, I toked the BlackPlayer appa as a example 

![Screenshot_20240521-123843](https://github.com/fast4x/RiMusic/assets/166191281/8ba64d87-6bbd-4c87-b5e1-b0f17076bff8)

### Additional Context

That's all :D

**Comment by fast4x** [comment]
you can switch to ViMusic ui mode in settings...

**Comment by privacyfreak84** [comment]
> you can switch to ViMusic ui mode in settings...

But isn't that missing some features?

**Comment by fast4x** [comment]
Minus in the next version

**Comment by fast4x** [comment]
Implemented, available from version 0.6.47
