### ISSUE TITLE
App crashing randomly.

### ISSUE THREAD

**Issue by col1iv** [fast4x/RiMusic#1962]
### Steps to reproduce the bug

1. Clicked the random play at the downloads
2. Listened to the song until it randomly crashed

### Expected behavior

It should just play normally :(

### Actual behavior

It crashed in the middle of the song I was listening to.

### Screenshots/Screen recordings

[](url)

### RiMusic version

0.6.35

### Android version

Android 13

**Comment by fast4x** [comment]
device is offline?

**Comment by fast4x** [comment]
Please in version 0.6.38, go to miscellaneous settings, enable debug, restart app, repeat crash action, after go again to settings, click on copy crash log and paste here
