### ISSUE TITLE
[Feature]: Artist name under album name

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1964]
### Description

Try adding artist names under album names as i feel like there's already enough empty space for it.

![IMG_20240522_093104](https://github.com/fast4x/RiMusic/assets/99175083/47212d4c-da56-43c9-a242-ba1a8720624a)

### Suggested Solution

Maybe something like this with artists name in slightly thinner or smaller fonts

![IMG_20240522_093002](https://github.com/fast4x/RiMusic/assets/99175083/87504acb-59d8-4d9e-9658-b569be07f15d)

**Comment by fast4x** [comment]
Added, available from version 0.6.47
