### ISSUE TITLE
[Feature]: Controlling blur and dark amount

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1965]
### Description

This is a response to #1959

He requested to make the shade darker and I somewhat agree but it's too dark. So dark that I can barely see what's on the background. Please don't make it that dark

### Suggested Solution

![332638420-346606ce-6162-4b16-9ec4-5e5a39f1352d](https://github.com/fast4x/RiMusic/assets/45353488/6cb33bd0-32fb-40d4-ae3a-3a496e6be700)

Have a slider like this in settings whenever blur background is chosen. This way anyone can modify the blur and darkness the way they want. Everyone will be happy.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.37
for now removed darker control
