### ISSUE TITLE
without Crashea network

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1967]
### Steps to reproduce the bug

enter the application offline, play a gradient theme, it doesn't matter if the theme is system or deep black, enter a song with two different colors

### Expected behavior

would be expected to work fine offline

### Actual behavior

but the application crashes

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/159836335/be62f442-62be-4169-b06c-2500f1a8f8c6

### RiMusic version

0.6.35

### Android version

Android 13

### Additional information

I actually don't know why this happens, maybe it's because my phone is already three years old?  I don't know, but it's a bug that I would appreciate if it would be fixed.

**Comment by aneesh1122** [comment]
Duplicate #1937

**Comment by fast4x** [comment]
actually crash if you use gradient from cover...

**Comment by aneesh1122** [comment]
> actually crash if you use gradient from cover...

No fast, app crashes even if you use `Background from cover`

**Comment by fast4x** [comment]
yes ok something with cover.

**Comment by fast4x** [comment]
change background with other withous cover... when offline

**Comment by fast4x** [comment]
Improved image caching, available from version 0.6.37

**Comment by fast4x** [comment]
Please in version 0.6.38, go to miscellaneous settings, enable debug, restart app, repeat crash action, after go again to settings, click on copy crash log and paste here
