### ISSUE TITLE
Reorder current playlist

### ISSUE THREAD

**Issue by kapitan-Prodigy** [fast4x/RiMusic#1969]
### Steps to reproduce the bug

1. Open current order of Playlist
2. Hold the double line icon on side
3. Slide song all the way up

### Expected behavior

Scroll through songs in a faster pace

### Actual behavior

Freezes and keeps song in original order. 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/113864895/229380e8-1825-4eb6-997c-21346d9afccf

### RiMusic version

0.6.35

### Android version

Android 14

**Comment by JeePopuwu** [comment]
It also occurs to me

**Comment by aneesh1122** [comment]
#1817
