### ISSUE TITLE
Search icon

### ISSUE THREAD

**Issue by Snyret** [fast4x/RiMusic#197]
### Description

Another way to position the search icon, putting it in a place where left handed people could easily reach.

### Suggested Solution

![Screenshot_20231209_164824-720_1399](https://github.com/fast4x/RiMusic/assets/139090371/caf1d4f4-fa0d-4d86-8180-5c5cd324035c)
![Screenshot_20231209_170346-720_1421-720_1421](https://github.com/fast4x/RiMusic/assets/139090371/ad9ac5d1-4086-4128-858a-4dff759c79ff)

**Comment by sayyid5416** [comment]
It's already possible: `Settings > User Interface > Show search tab in home`

**Comment by OrangeZXZ** [comment]
> It's already possible: `Settings > User Interface > Show search tab in home`

@fast4x this could be closed
