### ISSUE TITLE
how to make youtube direct downloading link without trackers

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#1970]
### Description

i want to user youtube direct downloading url of a video to use in my app to play video in exo player. how to make without trackers. and app shouldnt be ban on playstore and there should be no harm to youtube channel

### Suggested Solution

please

**Comment by fast4x** [comment]
Look in the code for sample.

**Comment by aneesh1122** [comment]
YouTube has different video and audio streams. They are not merged initially. Either you'll get the url of the video stream or the audio stream.

There's a video stream which has audio but the quality is bad.

Why not use piped if you're really that concerned about privacy?
