### ISSUE TITLE
[BUG] Theme changes to pitch black when changing settings when using material you theme

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1976]
Duplicate of #1699, as that seems to have gotten no attention.

### Steps to reproduce the bug

1. Have dark mode enabled (not pitch black!)
2. Go to settings
3. Change, for example, navigation bar position
4. Theme changes to pitch black

### Expected behavior

The setting should change without changing the theme

### Actual behavior

The theme changes

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/90613992/4c752971-7e42-4e5d-9142-108fc4820d7c

### RiMusic version

0.6.32

### Android version

Android 11

### Additional information

I think this happens with many more settings, not just the ones I showcased

**Comment by Cszyn** [comment]
fixed. update to 35

**Comment by Cszyn** [comment]
> fixed. update to 35

Update to v 0.6.35

**Comment by privacyfreak84** [comment]
Issue still occurs

**Comment by Cszyn** [comment]
> Issue still occurs

that's weird, the issue is gone on my end. Mind telling me the phone manufacturer/ android fork?

**Comment by Cszyn** [comment]
EMUI/Huawei?

**Comment by privacyfreak84** [comment]
Samsung, One UI

**Comment by Cszyn** [comment]
I'll fire up an emulator and see, but it does not occur in Xiaomi HyperOS

**Comment by Cszyn** [comment]
> I'll fire up an emulator and see, but it does not occur in Xiaomi HyperOS

But it did happen on my Huawei p30 lite back in v6.32

**Comment by Cszyn** [comment]
> Also, the issue didn't occur a few months ago

Latest One ui?

**Comment by privacyfreak84** [comment]
No, One UI version 3.1

**Comment by Cszyn** [comment]
> I'll fire up an emulator and see, but it does not occur in Xiaomi HyperOS

I'll take that comment back. It still occurs on my Xiaomi 14 and MuMu emulator running android 14 and 12 respectably.

**Comment by aneesh1122** [comment]
> > I'll fire up an emulator and see, but it does not occur in Xiaomi HyperOS
> 
> I'll take that comment back. It still occurs on my Xiaomi 14 and MuMu emulator running android 14 and 12 respectably. 

It happens only when you select 'material you' as theme.

Is it happening for every theme in your case?

**Comment by Cszyn** [comment]
> No, One UI version 3.1

Wait, I did have the right idea. Turn off Material You and switch to Dynamic the issue shoud go away

**Comment by Cszyn** [comment]
> > > I'll fire up an emulator and see, but it does not occur in Xiaomi HyperOS
> > 
> > 
> > I'll take that comment back. It still occurs on my Xiaomi 14 and MuMu emulator running android 14 and 12 respectably.
> 
> It happens only when you select 'material you' as theme.
> 
> Is it happening for every theme in your case?

No. just Material You.

**Comment by aneesh1122** [comment]
> Duplicate of #1699, as that seems to have gotten no attention.
> 
> ### Steps to reproduce the bug
> 
> 1. Have dark mode enabled (not pitch black!)
> 2. Go to settings
> 3. Change, for example, navigation bar position
> 4. Theme changes to pitch black
> 
> ### Expected behavior
> 
> The setting should change without changing the theme
> 
> ### Actual behavior
> 
> The theme changes
> 
> ### Screenshots/Screen recordings
> 
> https://github.com/fast4x/RiMusic/assets/90613992/4c752971-7e42-4e5d-9142-108fc4820d7c
> 
> 
> 
> ### Logs
> 
> _No response_
> 
> ### RiMusic version
> 
> 0.6.32
> 
> ### Android version
> 
> Android 11
> 
> ### Additional information
> 
> I think this happens with many more settings, not just the ones I showcased

Add 'Material You' in your title

**Comment by Cszyn** [comment]
(in my opinion) It's probably a minor oversight and set to default to OLED black instead of the regular one.

**Comment by privacyfreak84** [comment]
> Turn off Material You and switch to Dynamic the issue shoud go away

What if I want to use material you?

**Comment by Cszyn** [comment]
> > Turn off Material You and switch to Dynamic the issue shoud go away
> 
> What if I want to use material you?

Wait a bit for Fast to notice. he do be coding ✍️✍️🔥🔥🔥

**Comment by privacyfreak84** [comment]
Hope he notices this time; last time, the issue went overlooked and for buried under hundreds of other issues

**Comment by privacyfreak84** [comment]
I do hope he notices soon

**Comment by privacyfreak84** [comment]
...

**Comment by kzhe2059** [comment]
This has happened to me even when not changing settings, just opening the app after a bit of not using it.

**Comment by privacyfreak84** [comment]
😢

**Comment by fast4x** [comment]
Improved available from version 0.6.60
