### ISSUE TITLE
Some nice tweaks? :)

### ISSUE THREAD

**Issue by DeadSecTr** [fast4x/RiMusic#1977]
### Description

It would be great if the mini player were above the tabs, as it would be more consistent since ending the song moves the position of the tabs down again.

And please add the option to remove/reorder tabs (Home/Songs/Albums...)
![Screenshot_20240523-213128](https://github.com/fast4x/RiMusic/assets/90558189/537b65ec-368c-4c5e-9f39-9c5ac70e7b76)

### Suggested Solution

That the mini player is over the tabs section and that we can sort/deactivate some tabs eg albums,artists...

**Comment by JeePopuwu** [comment]
The player on top of the interface will arrive tomorrow (very grateful)

**Comment by fast4x** [comment]
Yes, just implemented with a lot of fesature included player to top or bottom... when bottom, is aboce the navigation bar.
