### ISSUE TITLE
offline (Fallo)

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#1978]
### Steps to reproduce the bug

Cuando estoy inactivo a alguna red el reproductor va bien pero es temporal puesto que a la tercer canción de mis descargas aparece en la pantalla "Error" y me arroja al inicio del dispositivo, incluso reinicie este con fin de ver si era el dispositivo pero no.

### Expected behavior

Cuando no hay alguna red y reproduzco mis descargas deberia reproducirlas sin problema alguno.

### Actual behavior

Cuando no estoy conectado a una red y reproduzco mis descargas borra las carátulas y solo me permite reproducir tres canciones o más pero falla rápido.

https://github.com/fast4x/RiMusic/assets/170132242/e9b9d844-0d1f-480a-a6ae-2e7a3bc5b664

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/170132242/e9aeaecd-ca2d-4fdd-80ed-f8a63c9c33ff

### Logs

N/A

### RiMusic version

0.6.35

### Android version

Android 14

### Additional information

N/A

**Comment by fast4x** [comment]
Change background of player with options without cover... actually there is a bug in backgrouns from cover options...

**Comment by fast4x** [comment]
Improved image caching, available from version 0.6.37

**Comment by fast4x** [comment]
Please in version 0.6.38, go to miscellaneous settings, enable debug, restart app, repeat crash action, after go again to settings, click on copy crash log and paste here
