### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by rezalef** [fast4x/RiMusic#1979]
### Steps to reproduce the bug

No need to explain, it's completely Not working (with or without VPN)
I even deleted the app and reinstalled it.

### Expected behavior

Not working 

### Actual behavior

Not working 

### Screenshots/Screen recordings

![Screenshot_2024-05-24-08-55-26-806_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/161199089/fe6cc837-e4e7-46eb-a270-df4dad466b6b)

### RiMusic version

0.6.35

### Android version

Android 14 Hyper OS

**Comment by fast4x** [comment]
I don’t know what to tell you, I don’t have a problem with the data connection being active.

**Comment by ikanakova** [comment]
Could you write more details - do you use mobile data or wifi? does music.youtube.com work in your browser? Is nothing working or just a particular artist?

**Comment by fast4x** [comment]
have you visualizer enabled? there is a bug
