### ISSUE TITLE
Predictive Back Gesture doesn't work

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#198]
### Steps to reproduce the bug

Go in a menu then go back by using the swipe gesture with android 14

### Expected behavior

It should do this:
https://github.com/fast4x/RiMusic/assets/104271365/6af477ac-97d4-462a-945b-753b9e9873f8

### Actual behavior

But it dose this:
https://github.com/fast4x/RiMusic/assets/104271365/066ba060-e2cb-4a3e-b5d5-a5e55b27f5d3

### RiMusic version

0.6.12

### Android version

Android 14 with One UI 6

**Comment by fast4x** [comment]
Ok

**Comment by fast4x** [comment]
The event is managed, the animation at the moment cannot be handled that way.

**Comment by ikanakova** [comment]
I don't know if it's related to this, but on Android 14, at least in Rimusic 12 and 13, my android back button to close an app doesn't work.

**Comment by fast4x** [comment]
Yes Is It
