### ISSUE TITLE
[Feature]: Changes in the new mini player

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1980]
### Description

The new unreleased mini player looks great. I got these ideas as soon as I saw it. Hope you'll like it.

### Suggested Solution

1. Remove next/previous button from mini player and add like button
![vlcsnap-2024-05-24-13h26m45s869](https://github.com/fast4x/RiMusic/assets/45353488/57893de0-43b0-49c8-99ec-d1d3e5b3a125)

Songs will be changed by swiping player left/right for previous/next song respectively

2. Open queue directly from mini player by swiping up
![vlcsnap-2024-05-24-13h26m45s869 - Copy.jpg](https://github.com/fast4x/RiMusic/assets/45353488/459b773a-5073-4f0c-9301-1953cded3b68)

Player can be opened by tapping on the mini player.

3. Please try to make this transparent
![IMG_20240524_140116](https://github.com/fast4x/RiMusic/assets/45353488/8570c3e5-d509-4b83-8b85-44500cb84153)
The player will look better if it looks like it's floating in the air

**Comment by dAtA-TRoN** [comment]
...and please make all these changes optional. I'm not a fan of swiping. I like it the way it works right now.

**Comment by aneesh1122** [comment]
> ...and please make all these changes optional. I'm not a fan of swiping. I like it the way it works right now.

Well, new icons in the mini player can be made optional for those who want that like how button shadows is made optional.

Swiping mechanisms are too much of a change to make it completely optional. Left and right swipe exist even now and since that didn't bother you I think upper swipe won't bother you either.

**Comment by dAtA-TRoN** [comment]
> Left and right swipe exist even now and since that didn't bother you I think upper swipe won't bother you either.

How do you know what bothers me and what doesn't? Please stop making assumptions about people you don't know.

**Comment by JeePopuwu** [comment]
I would like the next song and previous song buttons to still remain, I like that better.  The specific reason is that I would feel that it would be a copy of Spotify, and with Spotify I already have that problem of having to slide instead of the buttons on the mini player

**Comment by aneesh1122** [comment]
> > Left and right swipe exist even now and since that didn't bother you I think upper swipe won't bother you either.
> 
> How do you know what bothers me and what doesn't? Please stop making assumptions about people you don't know.

I didn't hear you complaining about existing swiping mechanisms so far. It's only when I suggested something you started complaining about that.

Even now you can do left, right and up swipe. All I asked to do was change what 'up swipe' does and change mini player somewhat.

If you don't use swipe at all then you're fine anyways. If he removes the left/right button from mini player he will make it optional.

Since you didn't complain about swipes till now It was fair to assume it doesn't bother you.

**Comment by aneesh1122** [comment]
> I would like the next song and previous song buttons to still remain, I like that better.  The specific reason is that I would feel that it would be a copy of Spotify, and with Spotify I already have that problem of having to slide instead of the buttons on the mini player

The old buttons will still remain. If he implements my suggestion I want it to be optional so that people who want to use old buttons can still continue using it. We already have many options to change things according to our wishes.

In the unreleased version right swipe doesn't change the song. It likes the song. You want that? When people swipe right they expect to go back to the previous song. Since fast4x want to add 'like' button to the miniplayer I suggested this option.

**Comment by dAtA-TRoN** [comment]
> I didn't hear you complaining about existing swiping mechanisms so far. It's only when I suggested something you started complaining about that.\n\nEven now you can do left, right and up swipe. All I asked to do was change what 'up swipe' does and change mini player somewhat.\n\nIf you don't use swipe at all then you're fine anyways. If he removes the left/right button from mini player he will make it optional.\n\nSince you didn't complain about swipes till now It was fair to assume it doesn't bother you.

Even if you didn't see me complaining about it, you still shouldn't make assumptions about me. I don't owe you an explanation for how I come up with my suggestions. What I can tell you is that you seem a bit paranoid about this. Also, no one here is trying to dispute your ideas. I simply asked for it to be optional. So what's your problem!?

**Comment by fast4x** [comment]
Be quite please... all share your ideas... mini player advanced will be in the next next version...
Also, swipe is a gesture and iun the future other gestures will be developed with enabling/disabling logic.

**Comment by fast4x** [comment]
At this momento i have added swipe to right for add in favorites and swipe to left go to next only because next and previous buttons are visibles...
In other version mini player will be configurable with actions... sample... essential without swipe and only base buttons. Advanced or similar si swipe and other actions...

**Comment by aneesh1122** [comment]
> I simply asked for it to be optional. So what's your problem!?

You could have said that you wish to have the option to have next/previous buttons in the mini player but you went on about how swipes should be optional.

**Comment by fast4x** [comment]
@aneesh1122  The basic idea of this request I like

**Comment by aneesh1122** [comment]
> @aneesh1122  The basic idea of this request I like

I can only give you suggestions. You can implement any part of it as you wish. Your decision is final after all.

I just think that left swipe should always be used for going to the previous song and since you wanted to add 'like' button to the mini player I suggested this option.

The main reason behind this request is to implement 'swipe up' to open the queue since you can open the player by tapping on the mini player already.

**Comment by dAtA-TRoN** [comment]
> You could have said that you wish to have the option to have next/previous buttons in the mini player but you went on about how swipes should be optional.

Yes, and I might as well have wished for a yellow rubber duck as a play symbol. What concern is it of yours? Let's end this conversation here, as it clearly leads nowhere.

Edit - Just to clear the air so you can sleep well tonight: I have nothing personal against you. It just so happened that we’ve had differing opinions more often recently. I actually find many of your ideas quite cool. Are we good now? Can we be 'internet friends' again!?

**Comment by aneesh1122** [comment]
> > You could have said that you wish to have the option to have next/previous buttons in the mini player but you went on about how swipes should be optional.
> 
> Yes, and I might as well have wished for a yellow rubber duck as a play symbol. What concern is it of yours? Let's end this conversation here, as it clearly leads nowhere.
> 
> Edit - Just to clear the air so you can sleep well tonight: I have nothing personal against you. It just so happened that we’ve had differing opinions more often recently. I actually find many of your ideas quite cool. Are we good now? Can we be 'internet friends' again!?

All I want from you is to give me neutral  criticism. If there's something you liked you should mention that as well. You only focus on negatives and I agree that I shouldn't have assumed that everyone uses swipe mechanisms and that's my fault and my ideas won't be 100% perfect but you rejected my ideas as if everything is wrong about it.

**Comment by JeePopuwu** [comment]
don't fight 🤝🏻.  We are virtual friends who share their love for music and programming a beautiful app
