### ISSUE TITLE
No se si sea buena idea implementar este proveedor de letras u otros que existan para mejorar la búsqueda de letras

### ISSUE THREAD

**Issue by chatinteligence** [fast4x/RiMusic#1981]
### Description

Algunos desarrollos como simpmusic lo tienen implementado, 
musixmatch.com
anteriormente usaba el simpmusic pero desde que conocí tu desarrollo veo que eres un excelente programador con ideas innovadoras, te aplaudo por tu aportación

### Suggested Solution

Extraer letras de otros proveedores ya que hay algunas canciones que no obtienen las letras en los bancos actuales de letras, seria para una implementación futura.

**Comment by fast4x** [comment]
Thanks for the compliments, It’s planned to add more suppliers as long as they’re not commercial.

**Comment by chatinteligence** [comment]
ok ok excelente, Saludos!
