### ISSUE TITLE
Next musics are cut in half

### ISSUE THREAD

**Issue by AquamarineDreams** [fast4x/RiMusic#1982]
### Steps to reproduce the bug

Just downloaded the new update and quickly realized a small visual bug.

1. Open the player
2. Bottom of player is glitched

### Actual behavior

As you can see, the next musics of the queue are cut in half

### Screenshots/Screen recordings

![IMG_20240524_131810](https://github.com/fast4x/RiMusic/assets/140275860/55b79aa7-4c5d-4887-b4c7-5ffedb60f858)

### RiMusic version

0.6.36 - Latest

### Android version

Android 14 - HyperOS

### Additional information

New interface is looking good 👍

**Comment by AquamarineDreams** [comment]
> Songs are appearing fine for me as i use buttons instead of gestures. But to add up in this issue:
> 
> ![IMG_20240524_225230](https://private-user-images.githubusercontent.com/99175083/333680158-46f1a38d-627b-4693-b84a-2bc84b4a80a0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MDI4MDUsIm5iZiI6MTcxNjYwMjUwNSwicGF0aCI6Ii85OTE3NTA4My8zMzM2ODAxNTgtNDZmMWEzOGQtNjI3Yi00NjkzLWI4NGEtMmJjODRiNGE4MGEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDAyMDE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMjI3MzZlMmY1ZWQ0ZTY2MjRiZDU0ZDY4NWYzNDQ5MjM0ZDljYjg1MzZhNDM0Njg2YmI0MzI1ZmEzNzE3YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tGg-H57DRNv0QRefSxoXeU_1hNNZoNhwUeQrEeMdf8A)

Same 👍

**Comment by fast4x** [comment]
Fixed actions bar, available from version 0.6.37
