### ISSUE TITLE
UPSS! Algo paso con el responsivo visual

### ISSUE THREAD

**Issue by chatinteligence** [fast4x/RiMusic#1983]
### Steps to reproduce the bug
The new interface looks great, but...
When I open the music player, it does not display well on some devices apparently, Case in the S22.
![image](https://github.com/fast4x/RiMusic/assets/147566193/e3fa4edb-bd05-4f86-84f2-82e269fb6c84)

### Expected behavior

Improve the interface of the screen, in the bottom bar.
Remove the repeated "like" icon.
![image](https://github.com/fast4x/RiMusic/assets/147566193/88cbdc38-afd0-4957-a88c-d134fa9050fe)

### Actual behavior

Player failure

### RiMusic version

Ri Music v0.6.36

### Android version

Android 14

**Comment by aneesh1122** [comment]
That extra heart icon appears only in 'essential' control type

**Comment by fast4x** [comment]
Fixed actions bar, available from version 0.6.37
