### ISSUE TITLE
Error Visualizador

### ISSUE THREAD

**Issue by chatinteligence** [fast4x/RiMusic#1984]
### Steps to reproduce the bug

I am not a fan of this option but maybe other users are, I found a bug in the implementation

https://github.com/fast4x/RiMusic/assets/147566193/5fbe7657-7860-4412-be18-1cf64b80675f

### Expected behavior

I am not a fan of this option but maybe other users are, I found a bug in the implementation

### Actual behavior

I am not a fan of this option but maybe other users are, I found a bug in the implementation

### RiMusic version

Ri Music v0.6.36

### Android version

Android 14

**Comment by NightFly88** [comment]
i have the same problem

**Comment by fast4x** [comment]
disable visualizer for now

**Comment by NightFly88** [comment]
Yes I did that

**Comment by fast4x** [comment]
Fixed, available from version 0.6.37

**Comment by NightFly88** [comment]
Thanks
