### ISSUE TITLE
[CRITICAL] Crash when playing any song

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#1985]
### Steps to reproduce the bug

Oppen app the play a song

### Expected behavior

Play the song

### Actual behavior

Crash the app

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/104271365/5590e34b-51d8-46b6-ab88-aa4a41090116

### Logs

Can someone explain how to show only rimusic in adb logcat?

### RiMusic version

0.6.36

### Android version

Android 14

**Comment by fast4x** [comment]
your cache is full?

**Comment by fast4x** [comment]
have visualizer enabled with mic permission enabled?

**Comment by fast4x** [comment]
try delete player cache from settings

**Comment by OrangeZXZ** [comment]
> try delete player cache from settings 

I deleted all cash still crashing

**Comment by OrangeZXZ** [comment]
@fast4x the crash happens when you have a visualization enabled in settings

**Comment by fast4x** [comment]
ok I'll check visualizer permission

**Comment by fast4x** [comment]
Fixed, available from version 0.6.37
