### ISSUE TITLE
New quick picks menu extremely laggy

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#1986]
Its even laggier then the previous redesign

**Comment by NikunjKhangwal** [comment]
It's laggy for me too but just slightly, it's still very usable overall. I'm also on low end device so i guess that's the case.

**Comment by privacyfreak84** [comment]
Any tips on how to speed it up?

**Comment by NikunjKhangwal** [comment]
I guess try turning off monthly playlists or other options for now

**Comment by privacyfreak84** [comment]
> I guess try turning off monthly playlists or other options for now

Doesn't fix anything 🙁

**Comment by NikunjKhangwal** [comment]
Is your device low end?

**Comment by privacyfreak84** [comment]
Samsung galaxy a30s

**Comment by NikunjKhangwal** [comment]
Yup, that's even lower than mine. Also Exynos processors aren't the most efficient, specially in your case it's 5 years old

I guess you can try turning off specific sections from quick picks. Otherwise turning off quick picks completely is your best bet.

**Comment by aneesh1122** [comment]
If quick picks is really important to you then I think you should jump to a lighter app.

**Comment by privacyfreak84** [comment]
> Yup, that's even lower than mine. Also Exynos processors aren't the most efficient, specially in your case it's 5 years old

I think a new phone is long overdue. Thanks for the insight!
