### ISSUE TITLE
[Feature]: New Design for songs tabs

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1987]
### Description

First of all i wanted to say the new update redesign is amazing. The update also fixed or improved a lot of issues i had. There are a few visual glitches but that's expected in a complete redesign, I'll be opening issues about them.
Now that out of the way, as always things could be improved further. This request is about improving design of songs tabs. I feel like those tabs are the only part of app that looks different from rest of UI, specially in dark mode.

![IMG_20240524_233208](https://github.com/fast4x/RiMusic/assets/99175083/0a21705a-59da-4d5b-8442-cb83cd06ebd6)
![IMG_20240524_232828](https://github.com/fast4x/RiMusic/assets/99175083/8aae1824-8d16-4d4c-b29a-0f06bce93701)

### Suggested Solution

I suggest making them fully transparent with outlines so they perfectly blend with background.

Something like this:
![IMG_20240524_232715](https://github.com/fast4x/RiMusic/assets/99175083/64722257-19cf-424f-9ea1-bbe2eec753a1)

Same for dark mode:
![IMG_20240524_232731](https://github.com/fast4x/RiMusic/assets/99175083/49de8e7d-6466-4c07-bc25-3d4605905ac6)

The screenshots are from [Seal App](https://github.com/JunkFood02/Seal)

**Comment by fast4x** [comment]
Improved, available from version 0.6.37
