### ISSUE TITLE
Add play button for 'Modern' controls

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#1988]
### Description

Different play buttons are available only for essential controls. Please add play buttons for modern controls too.

### Suggested Solution

Please also add this button.
![IMG_20240524_234724](https://github.com/fast4x/RiMusic/assets/45353488/06341684-bf24-4686-ab64-291275de0b21)

It looks cool

### Additional Context

I can add .png transparent files for the requested play button if you want. Both with glow and without glow

**Comment by AquamarineDreams** [comment]
If you change the button style on "essential" mode, and then change to "modern" mode, your changes will be applied on it too.

![IMG_20240524_231818](https://github.com/fast4x/RiMusic/assets/140275860/80cfb20d-1abf-4fe2-8824-02869c14ecf6)

**Comment by aneesh1122** [comment]
@DeadSecTr you realise that this will be optional. Right?

Many of us are using 'Modern' controls and we don't want our button choices to be limited.

**Comment by aneesh1122** [comment]
> If you change the button style on "essential" mode, and then change to "modern" mode, your changes will be applied on it too.
> 
> 
> Examples of different play buttons on "modern" mode:
> 
> ![IMG_20240524_231818](https://github.com/fast4x/RiMusic/assets/140275860/80cfb20d-1abf-4fe2-8824-02869c14ecf6)
> 
> 

Interesting. So it's possible but not added in options.
