### ISSUE TITLE
bug list

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1989]
### Steps to reproduce the bug

I will mention all the bugs I have noticed in this update, luckily (unlike the others) I don't have Crash bugs, that's good

### Expected behavior

1. You should download the player and continue with your normal activity
2. should have the corresponding colors of the song in animated gradient
3. the player controls should be the same color
4. The player's tail when performing the down action must be completely lowered

### Actual behavior

1. **The app stops for a few seconds when you lower the mini player:** when it is completely lowered to disappear, it stops for a long period of time.
2. **The change of the songs leaves the previous color:** I legitimately don't know if this is a bug or it should really be like this, I think it is a bug since when I download the player and upload it again it is with the correct colors.
3. **The colors are split in half:** the color of the controls is there, and I think the cover is united
4. **the queue remains even when it is lowered:** the queue is working strangely right now, if it is lowered slowly it can still be left on the screen and still be used normally (which I find somewhat funny xd)

### Screenshots/Screen recordings

1.

https://github.com/fast4x/RiMusic/assets/159836335/a7d28897-1b1e-472f-aa26-b3cd2bc47dfb

2.

https://github.com/fast4x/RiMusic/assets/159836335/602036eb-8623-41d1-97e5-d0dcc2d63bc0

3.
![Screenshot_2024-05-24-11-51-27-046_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/6e4f5974-3669-4c8d-91af-3feb45884c7e)
4.

https://github.com/fast4x/RiMusic/assets/159836335/07bed46f-40ea-44a4-b3c7-e7f2899f7217

### RiMusic version

0.6.36

### Android version

Android 13

### Additional information

These errors that it presented are not very annoying, they do not bother that significantly so you can take your time to repair them quickly.  Very good update, I think it is one of the best I have seen so far.  Congratulations Fast

**Comment by aneesh1122** [comment]
1. Not happening in my case
2. Happens only when 'fluid background from theme' is selected
3. My navigation bar is half cropped. Looks like the new app has screen size problems and is not able to adapt to different screens.
4. Happening 👍

**Comment by rsssxd** [comment]
![Screenshot_20240525-002116](https://github.com/fast4x/RiMusic/assets/60405617/5b141cd5-eee1-4059-85c6-d69fb196ed62)

**Comment by fast4x** [comment]
Check these bugs in new verson, wait for 0.6.44
