### ISSUE TITLE
Weird Player spacing

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#199]
### Steps to reproduce the bug

Play an song

### Expected behavior

There must be a space at the top and bottom of the player to separates text and buttons (green lines)
There must be less spaces at the top and bottom of the player buttons (it is bether to have less space bottom that top (red lines)
![20231210_002219](https://github.com/fast4x/RiMusic/assets/104271365/2f4797c7-e716-4301-9605-0fb3250e1a6c)

There is an example of YT Music (green)
![20231210_002357](https://github.com/fast4x/RiMusic/assets/104271365/0f6d211c-2cce-4425-b198-7724bcf3181e)

### RiMusic version

0.6.12

### Android version

Android 14 with One UI 6

### Additional information

Im my opinion the album cover and name of the song should be atached up and the player buttons down (red arrows)

And the orage spaces should be intentical (that way the cover, text, barr centers to the screen)

Blue is the same as the orange one but it keeps the same size (that way the player buttons are reacheble and dont center to the screen)

example:
![Screenshot_20231210_003421](https://github.com/fast4x/RiMusic/assets/104271365/593ba2aa-1efa-4638-8eb8-6542444c9908)

Dont hesitate to ask questions if you didn't understood what i mean

**Comment by Enigma1309** [comment]
Also the font looks quite different in ViMusic player,
also there is no haptic segregation between the player and playlist 
see second screenshot https://github.com/fast4x/RiMusic/issues/174#issuecomment-1837511892

**Comment by fast4x** [comment]
That font is custom, not the default one, like this one.
![Screenshot_2023-12-10-09-15-26-583_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/adacf268-b9c7-4669-999a-9c5bce770200)

**Comment by fast4x** [comment]
Optimized...
![Screenshot_2023-12-10-10-53-38-519_it fast4x rimusic debug](https://github.com/fast4x/RiMusic/assets/1484476/15553d5a-ec55-4f6b-b88e-943dacfdab41)

**Comment by fast4x** [comment]
Available from version 0.6.13

**Comment by OrangeZXZ** [comment]
I like the spacing but some peoples with tiny screens could dislike it you could add an "Player Spacing" like the "font spacing" option
