### ISSUE TITLE
New ui bottom menu cut off

### ISSUE THREAD

**Issue by Cszyn** [fast4x/RiMusic#1993]
### Steps to reproduce the bug

Update to 6.36

### Expected behavior

The bottom section easily avaliable

### Actual behavior

It's cut off but still working

### Screenshots/Screen recordings

![Screenshot_2024-05-24-21-12-38-256_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/147027531/a6b27c32-52c0-4fd0-bba3-bf0b34b1cd8e)

### RiMusic version

0.6.36

### Android version

14

### Additional information

6.40 inch screen

**Comment by Cszyn** [comment]
Duplicate to #1989

**Comment by aneesh1122** [comment]
#1983
