### ISSUE TITLE
Piped Support Feature Request

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#2]
### Description

Would it be possible to support piped accounts and custom instances for library backups and then have your playlists cross-device? 

### Suggested Solution

This app looks great so far and I'd love to see it work as a replacement for any other proprietary music app.

**Comment by fast4x** [comment]
It's a good idea, I'll check in the next few weeks.
Thanks

**Comment by siggi1984** [comment]
Great, I'm looking forward to it now.

**Comment by fast4x** [comment]
Piped feature requires investment in a hardware infrastructure which is not currently foreseen. Still, it's a nice feature.

**Comment by siggi1984** [comment]
Pity

**Comment by fast4x** [comment]
Reopened for future

**Comment by siggi1984** [comment]
Alternatively maybe Invidious Support

**Comment by fast4x** [comment]
??

**Comment by siggi1984** [comment]
If Piped is not possible, Invidious would be an alternative.

https://invidious.io/

**Comment by fast4x** [comment]
Ok, I didn't understand

**Comment by fast4x** [comment]
Can you give me any indication how you expect this to work?
What would you like the app to do?
Thank you

**Comment by fast4x** [comment]
Would you like a function to listen to the song with Piped?
Like listen on Youtube or Youtube music ?

**Comment by fast4x** [comment]
Added List on Piped and Invidious

Waiting for your suggestions

**Comment by siggi1984** [comment]
> Can you give me any indication how you expect this to work? What would you like the app to do? Thank you

You should be able to log into your piped account and access your playlists. Create or synchronize new playlists.

**Comment by siggi1984** [comment]
> Would you like a function to listen to the song with Piped?
> Like listen on Youtube or Youtube music ?

This function would not be absolutely necessary as the current method works quite well. But it would be a plus in terms of data protection.

**Comment by ikanakova** [comment]
> > Would you like a function to listen to the song with Piped?
> > Like listen on Youtube or Youtube music ?
> 
> This function would not be absolutely necessary as the current method works quite well. But it would be a plus in terms of data protection.

Thanks to the "nuclear" app, I feel that data protection comes at the expense of efficiency, as the app takes an awfully long time to load songs.
