### ISSUE TITLE
Drowning icon

### ISSUE THREAD

**Issue by Grevellia123** [fast4x/RiMusic#2004]
### Steps to reproduce the bug

Click on the song

### Expected behavior

Icons are clearly visible

### Actual behavior

The icon instead sinks 
![IMG_20240525_055857](https://github.com/fast4x/RiMusic/assets/134467260/a93676db-7605-452f-b06e-fc8f27f5fad9)

### Screenshots/Screen recordings

![IMG_20240525_055857](https://github.com/fast4x/RiMusic/assets/134467260/3f82a226-2c08-4d58-a0ee-8ec43e6d0c62)

### RiMusic version

0.6.36

### Android version

Android 12

### Additional information

Poco m3

**Comment by fast4x** [comment]
Hi fix available soon

**Comment by fast4x** [comment]
Fixed actions bar, available from version 0.6.37
