### ISSUE TITLE
Player theme + drowning icon

### ISSUE THREAD

**Issue by col1iv** [fast4x/RiMusic#2005]
### Steps to reproduce the bug

1. Just by selecting the theme.

### Expected behavior

Normally the plain theme should change along with the song. 
The bottom player buttons a bit more higher.

### Actual behavior

![Screenshot_20240524_201421](https://github.com/fast4x/RiMusic/assets/152646768/33b880db-0626-4f8e-b185-ea0f462018f9)
![Screenshot_20240524_201413](https://github.com/fast4x/RiMusic/assets/152646768/7a9469ec-d28b-4c9a-871e-0809f7b8ced7)

### RiMusic version

0.6.36

### Android version

Android 13

**Comment by fast4x** [comment]
Hi fix available soon

**Comment by fast4x** [comment]
Fixed, available from version 0.6.37
