### ISSUE TITLE
Player not fully showing on my screen 

### ISSUE THREAD

**Issue by Lllum** [fast4x/RiMusic#2009]
### Steps to reproduce the bug

Play a song and open player

### Expected behavior

I'm supposed to see the bottom controls

### Actual behavior

The bottom controls are almost completely emerged in the bottom of my screen 

### Screenshots/Screen recordings

![Screenshot_20240525-082957](https://github.com/fast4x/RiMusic/assets/156969262/e481ae65-c263-4b7a-aecc-3c8b524a64fa)

### RiMusic version

0.6.36

### Android version

8

**Comment by fast4x** [comment]
Hi fix available soon

**Comment by dAtA-TRoN** [comment]
![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/a6aadafe-2ca1-4035-9e76-6b44a06562b0)

SAME HERE!!!

By the way: the new update is absolutely jaw-dropping. Brilliant. RiMusic keeps getting easier and more intuitive to use, and I must say, it really needed this improvement. Excellent work. I'm very impressed!

However, I do have one small complaint:

![Screenshot_2024-05-25-12-13-37-12_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/a6b0a807-ed81-431f-a637-93edf7047578)

The background color of the selected tab is almost impossible to see. Please improve this.

**Comment by fast4x** [comment]
under development...
