### ISSUE TITLE
Is there anyway to get this app via Fdroid?

### ISSUE THREAD

**Issue by Driftinginfinitely** [fast4x/RiMusic#201]
### Description

Is this app available via Fdroid? If not, is it likely to be available there in the future? 

### Suggested Solution

-

**Comment by fast4x** [comment]
Yes, Publication on FDroid is ongoing

**Comment by OrangeZXZ** [comment]
This issue can be closed because there is already an existing one:
https://github.com/fast4x/RiMusic/issues/9#issue-1920628593

**Comment by IzzySoft** [comment]
While on it, please check your Fastlane changelogs. Per definitionem, their maximal size is 500 characters each – `6.txt` has about 2k, that's 4 times as much, so it will be truncated midword at position 500. Those per-release changelogs should only hold the highlights, but you can include a link to the full changelog when needed.

While there, you might also wish to include an introducing paragraph at the start of `full_description.txt` – like what you have in your Readme, or even a bit more detailed.

Meanwhile, with the next sync around 7 pm UTC your app will [become available here](https://apt.izzysoft.de/packages/it.fast4x.rimusic/) in my repo, and look like this:

![image](https://github.com/fast4x/RiMusic/assets/6781438/69306af2-a5ea-4a21-9126-2756c70c3b0d)

Which also tells you about 2 current show-stoppers for inclusion with F-Droid, which does not allow proprietary components.

**Comment by fast4x** [comment]
> Già che ci sei, controlla i log delle modifiche di Fastlane. Per definizione, la loro dimensione massima è di 500 caratteri ciascuno - ha circa 2k, che è 4 volte tanto, quindi sarà troncato a metà parola alla posizione 500. Questi changelog per rilascio dovrebbero contenere solo i punti salienti, ma è possibile includere un collegamento al changelog completo quando necessario.`6.txt`
> 
> Mentre sei lì, potresti anche voler includere un paragrafo introduttivo all'inizio, come quello che hai nel tuo Readme, o anche un po' più dettagliato.`full_description.txt`
> 
> Nel frattempo, con la sincronizzazione successiva intorno alle 19:00 UTC, l'app lo farà [become available here](https://apt.izzysoft.de/packages/it.fast4x.rimusic/) nel mio repository e assomiglia a questo:
> 
> ![image](https://private-user-images.githubusercontent.com/6781438/290875633-69306af2-a5ea-4a21-9126-2756c70c3b0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTc0ODksIm5iZiI6MTcwMjY1NzE4OSwicGF0aCI6Ii82NzgxNDM4LzI5MDg3NTYzMy02OTMwNmFmMi1hNWVhLTRhMjEtOTEyNi0yNzU2YzcwYzNiMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTYxOTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2QxY2RkN2YyYjdmYjQ4NWIwNGY3M2QyMmE3YTEwMDgzZmFjYTYxNDQ2NzhhNzFmMWQ1ZDQ1ZWI3MTlmYTZlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZxofwbZ1ae5UUHr7GjomTAwwjzotEZTBJNPRHgwvHbg)
> 
> Che ti dice anche di 2 attuali show-stopper per l'inclusione con F-Droid, che non consente componenti proprietari.

Hi Izzy, thank you so much!
I will do the checks and accommodations you indicated, but Cronet is no longer there, I have removed it and replaced it with non-proprietary library.

**Comment by IzzySoft** [comment]
> I will do the checks and accommodations you indicated

Thanks a lot! Once in place, please give me a ping so I can cross-check and adjust here accordingly (e.g. enable pulling changelogs, trigger an update for fulldesc etc). My repo operates a little different from F-Droid.org :wink:

> Cronet is no longer there

My library scanner still detects it. Does the replacement use the same "signature" (like, packageName, directory structure etc) – and can you give a link to its sources? Same for GMS?

**Comment by fast4x** [comment]
> > I will do the checks and accommodations you indicated
> 
> Thanks a lot! Once in place, please give me a ping so I can cross-check and adjust here accordingly (e.g. enable pulling changelogs, trigger an update for fulldesc etc). My repo operates a little different from F-Droid.org :wink:
> 
> > Cronet is no longer there
> 
> My library scanner still detects it. Does the replacement use the same "signature" (like, packageName, directory structure etc) – and can you give a link to its sources? Same for GMS?

This is the library I use to translate lyrics. This may be reported.

https://github.com/therealbush/translator

**Comment by IzzySoft** [comment]
> This is the library I use to translate lyrics. This may be reported.

Nope. Reported is [Cronet](https://developers.google.com/android/reference/com/google/android/gms/net/package-summary) , which is detected by the path `/com/google/android/gms/net` (or the packageName `com.google.android.gms.net`). Your translator would be `/me/bush/translator` (`me.bush.translator`). That would be `NonFreeComp` as well as it has no license declared (and also `NonFreeNet` as it uses Google Translator APIs).

**Comment by fast4x** [comment]
ok I check better, thanks

**Comment by fast4x** [comment]
> > This is the library I use to translate lyrics. This may be reported.
> 
> Nope. Reported is [Cronet](https://developers.google.com/android/reference/com/google/android/gms/net/package-summary) , which is detected by the path `/com/google/android/gms/net` (or the packageName `com.google.android.gms.net`). Your translator would be `/me/bush/translator` (`me.bush.translator`). That would be `NonFreeComp` as well as it has no license declared (and also `NonFreeNet` as it uses Google Translator APIs).

Found It!
Isn't a library but two meta data in Android manifest

        <meta-data android:name="com.google.android.gms.car.application"
            android:resource="@xml/automotive_app_desc"/>

        <meta-data android:name="com.google.android.gms.car.notification.SmallIcon"
            android:resource="@drawable/app_icon" />

**Comment by IzzySoft** [comment]
It's not just an entry in the manifest. See here:

![image](https://github.com/fast4x/RiMusic/assets/6781438/decf4d56-068d-4192-9d06-171122b0abf3)

(smali generated by Apktool, showing the libraries) Could be "dragged in" as a dependency by some other library. To find out, you can use e.g. `gradle :app:dependencies`

**Comment by fast4x** [comment]
Thanks

**Comment by IzzySoft** [comment]
Yay, success! with the next sync, the `NonCreeComp` will be gone :partying_face:

**Comment by fast4x** [comment]
> Yay, success! with the next sync, the `NonCreeComp` will be gone :partying_face:

The repo has updated, the list of libraries does not contain Gms, but NonFreeComp remained.

Do I have to do something?

**Comment by IzzySoft** [comment]
> Do I have to do something?

Yes: Have patience for another ~4 hours :wink: As I wrote:

> with the next sync …

Syncs happen daily around 7 pm UTC (winter; in summer 6 pm UTC).

**Comment by fast4x** [comment]
Ahhhh ok i’m sorry

**Comment by IzzySoft** [comment]
No prob. The "small-print" gets each of us at least once :see_no_evil:

**Comment by fast4x** [comment]
Also published on F-Droid.

**Comment by IzzySoft** [comment]
> Also published on F-Droid.

Congrats to the listing! At this point apps are usually removed from my repo, after a decent overlap (of about 2 weeks). You're ready for that?

**Comment by fast4x** [comment]
I thought it was kept in your repo too. Can’t you keep it? I’d be honored!

**Comment by IzzySoft** [comment]
Default is removal. But as 1) your app is relatively small (< 5 MB APK-size), you 2) established reproducible builds and 3) explicitly requested it to stay, I've marked it for this exception so it will stay.

**Comment by fast4x** [comment]
Thank you very much

**Comment by Jose7723** [comment]
No puedo iniciar sesión en rimusic. Y no puedo reproducir nada. Ayuda porfa
