### ISSUE TITLE
Playlists aren't showing

### ISSUE THREAD

**Issue by Lllum** [fast4x/RiMusic#2011]
### Steps to reproduce the bug

Click the button to add a song to playlists 

### Expected behavior

It should show the list of playlists so I can select one to add the song to 

### Actual behavior

It dims the screen and doesn't pull up the list 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/156969262/826ccb8e-6ddc-4e35-86b7-65c1e6d3c893

### RiMusic version

0.6.36

### Android version

8

**Comment by fast4x** [comment]
Seem to be fixed, available from version 0.6.37
