### ISSUE TITLE
Fallas en la ultima version de RiMusic

### ISSUE THREAD

**Issue by Cristiam28** [fast4x/RiMusic#2013]
### Steps to reproduce the bug

1 reproducir música, 2 entrar a la lista de música. 

### Expected behavior

Debería abrir la lista de músicas para saber cuales están en la lista

### Actual behavior

Se sale de la aplicación y dice que esta presentando fallas

### RiMusic version

v0.6.36

### Android version

Android 13

**Comment by fast4x** [comment]
Fixed, available from version 0.6.37

Disable visualizer
