### ISSUE TITLE
Corrección estética 

### ISSUE THREAD

**Issue by julianM2000** [fast4x/RiMusic#2016]
### Steps to reproduce the bug

Reproductor, linea de degradado o fondo del reproductor está descuadrada 
![Screenshot_20240525-095850](https://github.com/fast4x/RiMusic/assets/68936429/ce343f2a-ab1a-4adb-996c-227e1cce0c8f)

### Expected behavior

no sé ve estéticamente bien

### Actual behavior

Fondo

### Logs

a

### RiMusic version

Última versión 

### Android version

13

### Additional information

Corrección estética, que la línea de fondo vaya a la par la barra de abajo

**Comment by fast4x** [comment]
Just fixed, download last version 0.6.36.1
