### ISSUE TITLE
Big & Biggest thumbnail size is same

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#2017]
### Steps to reproduce the bug

Change the thumbnail size to big and biggest

### Expected behavior

They should be different 

### Actual behavior

The size is same in ViMusic style. Idk about RiMusic music style, could be a issue there too.
Only the timeline gets a little bigger when switching to biggest. Thumbnail remains the same.

### RiMusic version

0.6.36.1

### Android version

Android 12

**Comment by aneesh1122** [comment]
Working properly in RiMusic mode

**Comment by fast4x** [comment]
Good, i'll check it in ViMusic mode

**Comment by NikunjKhangwal** [comment]
> Working properly in RiMusic mode.
> 
> Edit : working fine in ViMusic mode as well. Maybe reinstalling the app will fix your problem

Re-installed and choosed "Biggest" but now the app is stuck on biggest even when choosing big. Basically opposite of what was happening before. Although it's still better now that my problem is kind of solved temporarily but there's definitely a bug somewhere.

**Comment by NikunjKhangwal** [comment]
Ok it's happening when choosing essential controls
Just confirmed

**Comment by aneesh1122** [comment]
> Ok it's happening when choosing essential controls
> Just confirmed

The sizes do change. It's just that modern size /= essential size

Modern biggest > Essential biggest
Modern Big > Essential big

and so on.....

**Comment by NikunjKhangwal** [comment]
The modern biggest size was default biggest in previous versions.
I guess it became a feature request now.

**Comment by aneesh1122** [comment]
> The modern biggest size was default biggest in previous versions.
> I guess it became a feature request now.

I know that.

I just told you that essential's cover sizes are smaller than their modern counterparts.

**Comment by aneesh1122** [comment]
Maybe close this and make a new feature request with all the new details

**Comment by NikunjKhangwal** [comment]
Not needed imo, i will if fast4x needs it

**Comment by fast4x** [comment]
No new one, ok this

**Comment by aneesh1122** [comment]
@fast4x close this as completed
