### ISSUE TITLE
Please improve.

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#2019]
![ZomboDroid_25052024061525.jpg](https://github.com/fast4x/RiMusic/assets/71184627/475e6f1a-ebe0-47c1-b13a-c7dd90eea4a6)

Please ensure the navigation bar extends to the bottom of the screen. The current black line at the bottom doesn't look very nice.

### RiMusic version

0.6.36

### Android version

Android 13

**Comment by aneesh1122** [comment]
![Screenshot_2024-05-25-21-52-59-244_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/e326109f-fac9-4222-852f-72f390d8f5d7)

Sides of the mini player are also not transparent.

They are transparent in the queue page though.

**Comment by dAtA-TRoN** [comment]
> ![Screenshot_2024-05-25-21-52-59-244_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/e326109f-fac9-4222-852f-72f390d8f5d7)
> 
> Sides of the mini player are also not transparent.
> 
> They are transparent in the queue page though.

I realised that as well 🤔. I thought there was some reason for this and fast4x would take care of it later.

**Comment by fast4x** [comment]
Unfortunately they are bugs that I could not fix, I try in the coming days, I gave priority to crashes.

**Comment by dAtA-TRoN** [comment]
> Unfortunately they are bugs that I could not fix

You are not fast4x! Where is he? What have you done with him 🤬!?

**Comment by aneesh1122** [comment]
> Unfortunately they are bugs that I could not fix, I try in the coming days, I gave priority to crashes.

Could you please try making areas around the mini player transparent?

You made it transparent here in the queue page.
![Screenshot_2024-05-25-22-51-40-889_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/f73abb1c-6de7-4b23-b004-fe5e35189eb3)

**Comment by fast4x** [comment]
> > Unfortunately they are bugs that I could not fix
> 
> You are not fast4x! Where is he? What have you done with him 🤬!?

This week he worked fast6x for the amount of changes made. In other projects maybe they would be wanted Christmas!🥳😂

**Comment by fast4x** [comment]
> > Unfortunately they are bugs that I could not fix, I try in the coming days, I gave priority to crashes.
> 
> Could you please try making areas around the mini player transparent?
> 
> You made it transparent here in the queue page.
> ![Screenshot_2024-05-25-22-51-40-889_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/f73abb1c-6de7-4b23-b004-fe5e35189eb3)
> 
> 
> 

yes of course

**Comment by fast4x** [comment]
Implemented, available from version 0.6.37
