### ISSUE TITLE
1 degraded not responding

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#2022]
### Steps to reproduce the bug

go to gradient settings, tap theme gradient background.

### Expected behavior

should show the gradient that was chosen

### Actual behavior

does not show a gradient

### Screenshots/Screen recordings

![Screenshot_2024-05-25-11-39-54-931_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/15656fcf-8a69-4acd-bcca-c2999529ad5c)
![Screenshot_2024-05-25-11-39-45-799_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/7d7d355b-6443-41d5-aecf-7b7d2d89e8b2)

### RiMusic version

0.6.36.1 personality

### Android version

Android 13

**Comment by aneesh1122** [comment]
Did you ever get a gradient background with 'gradient background from theme'?

**Comment by JeePopuwu** [comment]
> ¿Alguna vez obtuviste un fondo degradado con "fondo degradado del tema"?

Si

**Comment by aneesh1122** [comment]
> > ¿Alguna vez obtuviste un fondo degradado con "fondo degradado del tema"?
> Yes

Ohh. I never got the gradient from that option.

I stopped using that a long time ago though. I always use cover blur background
