### ISSUE TITLE
release tag v0.6.36.1 points to the wrong commit

### ISSUE THREAD

**Issue by obfusk** [fast4x/RiMusic#2023]
### Steps to reproduce the bug

Release tag `v0.6.36.1` points to a much older commit (6e4ed980e1e82203aa42da50de561cb36f2cbdf6) than the actual code (b258f32eb5b514317beecd249690f71ece2fc0a3) for v0.6.36.1 (that the APK was correctly built from).

https://github.com/fast4x/RiMusic/compare/v0.6.36.1...b258f32eb5b514317beecd249690f71ece2fc0a3

### Expected behavior

Release tag matches source code used to build the APK.

### Actual behavior

Release tag doesn't match source code used to build the APK.

### RiMusic version

v0.6.36.1

### Android version

N/A

**Comment by dAtA-TRoN** [comment]
I don't know what that means, but it worries me 😐.

**Comment by JeePopuwu** [comment]
Que???

**Comment by obfusk** [comment]
What is means is that everything is fine if you download the APK from here or IzzyOnDroid.

But e.g. F-Droid won't see the new version since the commit the tag points to doesn't include the version bump.

And if anyone does build from the commit the tag points to you pretty much just get the same APK as v0.6.36 (with some translation updates). So you essentially just wouldn't get the updates from the new version.

**Comment by fast4x** [comment]
True, there was a problem when creating the tag, anyone is free to update to the latest version or wait for the ...37
