### ISSUE TITLE
Scroll to top behind search button + Device rotation issue

### ISSUE THREAD

**Issue by depthso** [fast4x/RiMusic#2028]
### Steps to reproduce the bug

To cause the scroll to top button issue, enable the bottom right search button feature, navigated to any collection of songs and scrolled down enough to trigger the scroll to top button to appear.

Secondly, when rotating the device from portrait to landscape, what ever page you are currently using will be redirected to the featured page. 

### Expected behavior

I expect the scroll to top button to apear on the left of the search button in a grid/list-like layout.

When rotating the physical device I would like it to retain the currently selected page. 

### Actual behavior

The scroll to top appears behind the search button therefore deemed unusable. 

### Screenshots/Screen recordings

![Screenshot_20240525-200139](https://github.com/fast4x/RiMusic/assets/86912923/60567b64-3c9b-4e2f-9c66-dff4b313d111)

### RiMusic version

0.6.36.1

### Android version

Android 14

### Additional information

I love this application

**Comment by aneesh1122** [comment]
Hold the search button and you can move and place it anywhere you like.

**Comment by depthso** [comment]
A new user would not know this like myself and should still expect this to not even happen even if having the ability to move the search button

**Comment by aneesh1122** [comment]
> A new user would not know this like myself and should still expect this to not even happen even if having the ability to move the search button 

Floating search button position possibilities are endless. It would be pointless to change other permanent buttons positions according to the changable floating search button.

**Comment by depthso** [comment]
I have had tried this and while it is a solution to the problem, the answer wasn't clear and should have a snap to grid positional placement. Furthermore there should be a system added in-place to prevent this happening such as moving any buttons to be pushed away from the location
