### ISSUE TITLE
Redundant Buttons in Player View after changing Controls Type

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#2034]
### Steps to reproduce the bug

1. Open RiMusic.

2. Navigate to Settings > Player Appearance > Controls Type.

3. Set the Controls Type to "Essential".

4. Go to the Player View.

### Expected behavior

The Player View should display only the essential controls without redundant extra buttons.

### Actual behavior

The Player View shows redundant repeat and like buttons next to the play button.

### Screenshots

![Screenshot_2024-05-26-06-00-41-48_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/71184627/28082766-d1e4-425f-a50b-06d8198a8cbb)

### Suggested Fix

Remove the redundant symbols on the left and right of the play button in the Player View **and make the remaining player controls larger, same as > Controls Type > Modern.**

### RiMusic version

0.6.36.1

### Android version

Android 13

**Comment by aneesh1122** [comment]
Those redundant buttons are a part of ViMusic UI. If you switch to ViMusic mode you'll find no 'like' button next to the song's name.

Essential is basically ViMusic's buttons and Modern is Rimusic's buttons.

**Comment by dAtA-TRoN** [comment]
> Those redundant buttons are a part of ViMusic Interface. If you switch to ViMusic mode you'll find no 'like' button next to the song's name.
> 
> Essential is basically ViMusic's buttons and Modern is Rimusic's buttons.
> 
> See #2018

Thank you for clearing that up. But if you're in RiMusic Mode and using this Controls Type, those buttons lose their purpose. So, it'd be wise to consider the steps I suggested.

**Comment by aneesh1122** [comment]
> > Those redundant buttons are a part of ViMusic Interface. If you switch to ViMusic mode you'll find no 'like' button next to the song's name.
> > 
> > Essential is basically ViMusic's buttons and Modern is Rimusic's buttons.
> > 
> > See #2018
> 
> Thank you for clearing that up. But if you're in RiMusic Mode and using the 'Essential' Controls Type, those buttons lose their purpose. So, it'd be wise to consider the steps I suggested.

If you ask me, both RiMusic and ViMusic mode should have their own essential or modern controls.

**Comment by dAtA-TRoN** [comment]
> If you ask me, both RiMusic and ViMusic mode should have their own essential or modern controls.

Perfect solution!

**Comment by aneesh1122** [comment]
> > If you ask me, both RiMusic and ViMusic mode should have their own essential or modern controls.
> 
> Perfect solution!

I even want that artist and song's icon to be removed or at least made an option in RiMusic mode but fast4x insists on using ViMusic mode if you don't want those icons.

**Comment by dAtA-TRoN** [comment]
> I even want that artist and song's icon to be removed or at least made an option in RiMusic mode but fast4x insists on using ViMusic mode if you don't want those icons.

I also think it would be better without the icons. It looks cleaner that way. If there's one thing I've learned about fast4x, it's that he's the last person you couldn't talk to again to change his mind if he sees any sense in it. Maybe we should both politely ask again. So, Mr. fast4x, if you're reading this (and I know you are), what do you think, huh!?

**Comment by aneesh1122** [comment]
> > I even want that artist and song's icon to be removed or at least made an option in RiMusic mode but fast4x insists on using ViMusic mode if you don't want those icons.
> 
> I also think it would be better without the icons. It looks cleaner that way. If there's one thing I've learned about fast4x, it's that he's the last person you couldn't talk to again to change his mind if he sees any sense in it. Maybe we should both politely ask again. So, Mr. fast4x, if you're reading this (and I know you are), what do you think, huh!?

Forget about it. I've deleted my comment. I'll continue using ViMusic mode. I just hope he will add the missing heart icon

**Comment by dAtA-TRoN** [comment]
> Forget about it. I've deleted my comment. I'll continue using ViMusic mode. I just hope he will add the missing heart icon\n\nThis is what I want to be universal in the app no matter what UI you choose.\n\nremove the artist and song icons\nput the song's and artist's name at centre\nmake the song's name bolder and a little bigger than the artist's name.

...and there you go again, barging right in. The previous solution was better because it didn't concern everyone. I can easily imagine you'll face pushback for your demands here, if not from other users, then perhaps from fast4x. You shouldn't always assume that your solution is the best. Others will probably be annoyed if the app changes too much without making new adjustments optional.

**Comment by dAtA-TRoN** [comment]
> Forget about it. I've deleted my comment. I'll continue using ViMusic mode. I just hope he will add the missing heart icon\n\nThis is what I want to be universal in the app no matter what UI you choose.\n\nremove the artist and song icons\nput the song's and artist's name at centre\nmake the song's name bolder and a little bigger than the artist's name.

...and there you go again, barging right in. The previous solution was better because it didn't concern everyone. I can easily imagine you'll face pushback for your demands here, if not from other users, then perhaps from fast4x. You shouldn't always assume that your solution is the best. Others will probably be annoyed if the app changes too much without making new adjustments optional.

**Comment by dAtA-TRoN** [comment]
...and there you go again, barging right in. The previous solution was better because it didn't concern everyone. I can easily imagine you'll face pushback for your demands here, if not from other users, then perhaps from fast4x. You shouldn't always assume that your solution is the best.

I believe the best, albeit most demanding, solution would be a fully customizable editor (including a preview mode) for the Player Page. This would allow users to mix and match elements to their liking. 'Modern' and 'Essential' modes could be easily selectable presets, along with a 'Custom' option. This way, everyone would be satisfied—except for fast4x, who has to program all this stuff 🤣.

**Comment by aneesh1122** [comment]
> > Forget about it. I've deleted my comment. I'll continue using ViMusic mode. I just hope he will add the missing heart icon\n\nThis is what I want to be universal in the app no matter what UI you choose.\n\nremove the artist and song icons\nput the song's and artist's name at centre\nmake the song's name bolder and a little bigger than the artist's name.
> 
> ...and there you go again, barging right in. The previous solution was better because it didn't concern everyone. I can easily imagine you'll face pushback for your demands here, if not from other users, then perhaps from fast4x. You shouldn't always assume that your solution is the best. Others will probably be annoyed if the app changes too much without making these new adjustments optional.

Well, I said what I want. I know it won't be changed so that's why I spoke my mind. I don't want fast4x to make it universal.

If we are talking about options. Maybe this can be implemented

1) toggle icons on/off
2) change songs and the artist's name's position between left and centre.

What I request fast4x is to make it universal to have the song's name 'bold' and 'bigger'. 

If people have problems with this then this can also be optional.

**Comment by aneesh1122** [comment]
> I believe the best, albeit most demanding, solution would be a fully customizable editor (including a preview mode) for the Player Page. This would allow users to mix and match elements to their liking. 'Modern' and 'Essential' modes could be easily selectable presets, along with a 'Custom' option. This way, everyone would be satisfied—except for fast4x, who has to program all this stuff

Yeah this is good.

We get to choose icons, names' position, button and cover image shadows etc

**Comment by dAtA-TRoN** [comment]
> Yeah this is good.\n\nWe get to choose icons, names' position, button and cover image shadows etc

Just like in Nova Launcher. Do you know the app?

**Comment by aneesh1122** [comment]
> > Yeah this is good.\n\nWe get to choose icons, names' position, button and cover image shadows etc
> 
> Just like in Nova Launcher. Do you know the app?

Tried a long time ago. I like simple things so went back to the stock launcher.

**Comment by dAtA-TRoN** [comment]
> Tried a long time ago. I like simple things so went back to the stock launcher.

I just wanted to talk about the editor views, because Nova Launcher does it exactly as I described: you have a large preview window, and below it you can adjust all sorts of settings and immediately see what changes. This is very cool and makes all these often cryptic settings very understandable, even for laypeople.

**Comment by aneesh1122** [comment]
> > Tried a long time ago. I like simple things so went back to the stock launcher.
> 
> I just wanted to talk about the editor views, because Nova Launcher does it exactly as I described: you have a large preview window, and below it you can adjust all sorts of settings and immediately see what changes. This is very cool and makes all these often cryptic settings very understandable, even for laypeople.
> 
> Possible settings for the RiMusic Player Page could include:
> 
> - Icons on/off
> - Font size
> - Font type
> - Font color
> - Drop shadow on/off
> - Positioning of various elements
> 
> Additionally, all other existing settings could be incorporated into this editor as well.

This seems too complicated to implement now.

Maybe we should focus on small things.

1) I want the 'like' icon so that icon should be made a part of the modern controls.

2) you want modern controls without shadows so you can ask for that.

**Comment by dAtA-TRoN** [comment]
> This seems too complicated to implement now.

That wasn't a demand; I was just thinking out loud.

**Comment by fast4x** [comment]
Great, I see with great pleasure that you are talking without fighting and I really like this.

For this and other reasons i want to make you happy and to thank you, I will begin to implement some basic functions that over time will allow you to improve and customize the controls of the player.

Patience, I will ask for help at fast6x to develop more quickly, but without caring eh...

If not, I’ll go completely crazy, at least for now I’m 30% crazy

🤣🤣🤣😂😂😂🤣🤣😂😂🤣🤣

**Comment by dAtA-TRoN** [comment]
> 30% crazy

...LIAR (110% at least) 😂😂😂!!!

But seriously (and I mean it!): don't overwork yourself with the stuff. Give yourself a break for a week or so where you don't do anything.

**Comment by aneesh1122** [comment]
> Great, I see with great pleasure that you are talking without fighting and I really like this.
> 
> For this and other reasons i want to make you happy and to thank you, I will begin to implement some basic functions that over time will allow you to improve and customize the controls of the player.
> 
> Patience, I will ask for help at fast6x to develop more quickly, but without caring eh...
> 
> If not, I’ll go completely crazy, at least for now I’m 30% crazy
> 
> 🤣🤣🤣😂😂😂🤣🤣😂😂🤣🤣
> 

Dude...I think we have awakened the true fast4x now.

Best mode activated 😂😂

**Comment by dAtA-TRoN** [comment]
@ aneesh1122

Yeah, he's like...

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/116670b4-e7fe-420a-a24a-cbf7747ef3f8)

**Comment by fast4x** [comment]
🤣🤣🤣🤣🤣🤣🤣🤣

**Comment by fast4x** [comment]
i.....
![giphy (3).gif](https://github.com/fast4x/RiMusic/assets/1484476/091065a4-03ee-4c41-8ee5-ecd1bbeede35)

**Comment by fast4x** [comment]
Implemented, controls and artist/album info in modern/essential type, can be used in both rimusic/vimusic mode.
So, can use how anyone want...
Available from version 0.6.37

**Comment by fast4x** [comment]
Other micro customizations for now isn't praticable...
