### ISSUE TITLE
Account e sync

### ISSUE THREAD

**Issue by LucaUni23** [fast4x/RiMusic#2036]
### Description

Hello, i'm Luca and i write because think sync with the device is a most good features.

### Suggested Solution

I use a tablet a lot and it would be really super to have everything already synchronized with the phone

### Additional Context

**Comment by fast4x** [comment]
I have in mind some system of synchronization between devices without login.

**Comment by aneesh1122** [comment]
> Hi Luca, i have in mind some system of synchronization between devices without login.

You can use piped for playlist sync. It's privacy friendly. It doesn't ask for anything except for username and password. No email id and personal details required.

Harmony music uses piped for playlist sync

**Comment by fast4x** [comment]
Ok piped, but require login and in RiMusic isn't planned any login system.

**Comment by aneesh1122** [comment]
> Ok piped, but require login and in RiMusic isn't planned any login system.

Okay. If you can come up with a solution of playlist sync without login then it will be great.

Piped is a great alternative if you need to login. Piped was developed to save yourself from Google tracking. Piped is privacy friendly just as much as RiMusic is.

You can add/delete songs from the playlist in RiMusic and it will be updated in piped at the same time.

**Comment by fast4x** [comment]
My is a test without login i don't know if it will fail.

**Comment by rishrust** [comment]
i was wrote a script which allows me to sync the music between two devices but the phone has to be rooted and on same wifi although  it is not a valid solution to this problem. https://github.com/rishrust/vi_uni
in next step i will be using firebase to sync the music.

**Comment by fast4x** [comment]
I am also oriented on synchronization between devices using wifi or bluetooth. Testing is ongoing...

**Comment by aneesh1122** [comment]
> I am also oriented on synchronization between devices using wifi or bluetooth. Testing is ongoing...

What if there are different users connected to the same wifi? 😅

**Comment by fast4x** [comment]
Well, we’ll see, maybe the WiFi explodes? 🤣🤣🤣🤣🤣

**Comment by aneesh1122** [comment]
> Well, we’ll see, maybe the WiFi explodes? 🤣🤣🤣🤣🤣

I don't want my mother to know what songs I'm listening to

Imagine she's browsing her favorites and finds "can't tame her by Zara Larsson" in her favorites. 😂

**Comment by fast4x** [comment]
> > Well, we’ll see, maybe the WiFi explodes? 🤣🤣🤣🤣🤣
> 
> I don't want my mother to know what songs I'm listening to
> 
> Imagine she's browsing her favorites and finds "can't tame her by Zara Larsson" in her favorites. 😂

Well, i'll try not to 🤣

**Comment by ikanakova** [comment]
>> Well, we’ll see, maybe the WiFi explodes? 🤣🤣🤣🤣🤣
> 
> I don't want my mother to know what songs I'm listening to
> 
> Imagine she's browsing her favorites and finds "can't tame her by Zara Larsson" in her favorites. 😂

And even worse, you'd find out what she's listening to 🤣😂😅

**Comment by NikunjKhangwal** [comment]
I agree some kind of synchronization is needed. I tried to suggest this app a lot of times on places like Reddit but lack of sync puts everyone off. Specially when every other major ytm client like Innertune and Simpmusic have it. People simply don't want the hassle to manually export and import data between their devices.

**Comment by fast4x** [comment]
I agree, but the price to pay is being tracked by a login.

**Comment by aneesh1122** [comment]
> I agree, but the price to pay is being tracked by a login.

Piped doesn't track anything. They are even in GitHub. Check it out yourself

[https://github.com/TeamPiped/Piped](here)

**Comment by fast4x** [comment]
I’m not talking about piped, all the related tickets are open, it means that sooner or later it will be implemented.

**Comment by fast4x** [comment]
Started development of piped account and synchronization 🎉

**Comment by fast4x** [comment]
Implemented piped playlists syncronization, available from version 0.6.39

**Comment by NikunjKhangwal** [comment]
Lessgo

![pokemon-pikachu](https://github.com/fast4x/RiMusic/assets/99175083/484fc227-55af-44ec-9fb1-35d6360d85f7)
