### ISSUE TITLE
App not visible in Android Auto

### ISSUE THREAD

**Issue by Clyde-Timonera** [fast4x/RiMusic#2037]
### Steps to reproduce the bug

1. Install RiMusic
2. Allow unknown sources in android auto
3. Find out that RiMusic is not there

### Expected behavior

It should show up in the android auto launcher just like vimusic and harmony music.

### Actual behavior

App is not visible there and only audio played from the phone app is heard.

### Screenshots/Screen recordings

![received_1981803438920084](https://github.com/fast4x/RiMusic/assets/78290310/5a44d818-da12-4f8f-8062-599af55265e3)

### RiMusic version

0.6.36.1

### Android version

Android 14

**Comment by dAtA-TRoN** [comment]
Maybe you have to apply android auto mode first in the settings 🤔!?

**Comment by birbou** [comment]
You have to enable it from the settings.
Open RiMusic go to settings > miscellaneous and activate android auto.

**Comment by orbistertius40** [comment]
Lastes version is installed at this time in my cellphone Google Pixel 8 Pro (updated) and we are.not able to find "Misc" option in Rimusic menj

**Comment by jiggie914** [comment]
This is still the case. Latest android 8.1.x and no app shows after enabling all mentioned above

**Comment by nathan450450** [comment]
Hey, i was able to make it show up in android auto- if you dont know how you need to google how to put android auto in developer mode on your phone, then there is another menu available in android auto settings-- select allow unknown sources and it works, feels and acts exactly like yt...
