### ISSUE TITLE
[Feature]: Add Filipino/Tagalog Language

### ISSUE THREAD

**Issue by Clyde-Timonera** [fast4x/RiMusic#2041]
### Description

I would love to have my native language added into this app to let my family members who aren't great english speakers also enjoy using this apps ui and navigation, I am also willing to help in the translation as I am a native speaker of Filipino (I do not know how to speak any other dialect of that language besides the normal dialect.)

### Suggested Solution

Add a custom language named either Filipino or Tagalog in crowdin with the locale code set as either fil-PH or tl-PH

### Alternatives

N/A

### Additional Context

N/A

**Comment by fast4x** [comment]
Hi thanks for your translation, I've added Filipino.

Good translation, remember you can translate also website.. always from crowdin.

**Comment by Clyde-Timonera** [comment]
Thank you for your assistance.

**Comment by fast4x** [comment]
I've added you in translator collaborators list in project page and in app.
Thanks to you for translation.

**Comment by Clyde-Timonera** [comment]
Hi, when is this getting added to the app? I have finished the translations.

**Comment by fast4x** [comment]
In next version 0.6.37 this week on Friday

**Comment by Clyde-Timonera** [comment]
Has the translations been approved? it appears as only 10% for me.

**Comment by fast4x** [comment]
i approve it now... but language it's just added in app..

**Comment by Clyde-Timonera** [comment]
Ok, thanks for updating the project status.

**Comment by fast4x** [comment]
Approved all 100% now...

**Comment by Clyde-Timonera** [comment]
Hi, I have corrected some typos.

**Comment by fast4x** [comment]
Ok I'll push before new version release.

**Comment by Clyde-Timonera** [comment]
Thank you so much for releasing the update!!! I'll remind my relatives to update their app so they can understand the navigation.
