### ISSUE TITLE
Can't find sorting option for playlists

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#2044]
### Description

Until recently we could sort playlists but after this or previous(?) update there's no sorting button up there.
![Screenshot_20240526-201055](https://github.com/fast4x/RiMusic/assets/85461823/a34b6f34-f97c-4c87-a1d2-856a9660801b)
There's the ascending/descending button but not the sorting button.

### Suggested Solution

Bring back the sorting button.

**Comment by aneesh1122** [comment]
Hold it
