### ISSUE TITLE
stop changing the UI every few weeks

### ISSUE THREAD

**Issue by airisama019** [fast4x/RiMusic#2045]
### Description

I've been using this for a few months and you've already change location of core UI elements 5 times

### Suggested Solution

stop being annyoing

**Comment by aneesh1122** [comment]
> stop being annyoing

**Comment by ikanakova** [comment]
When a user uses an application that is under development, they simply have to expect changes. You can go back to ViMusic, which doesn't change, but the developer doesn't give a damn about it, so it may not work at all soon either (if it still works...).

**Comment by dAtA-TRoN** [comment]
> ### Description
> 
> I've been using this for a few months and you've already change location of core UI elements 5 times
> 
> ### Suggested Solution
> 
> stop being annyoing
> 
> ### Alternatives
> 
> _No response_
> 
> ### Additional Context
> 
> _No response_

It's part of the process and we rise by making mistakes. Of course, this journey has its ups and downs, but anyone complaining now is welcome to downgrade to a version from two months ago. It's undeniable that the app is continuously improving.

**Comment by dAtA-TRoN** [comment]
> I kinda agree. Things are changing so fast on the app. While most things are still really easy to use/find some things are getting kinda complicated. And the rapid changes are bothering me as well.

Once the app is feature-complete, we should start revisiting and simplifying the settings. As the saying goes: things often get worse before they get better.

**Comment by dAtA-TRoN** [comment]
> You can go back to ViMusic, which doesn't change, but the developer doesn't give a damn about it, so it may not work at all soon either (if it still works...).

That was hell. Every week, I kept checking and hoping for a new update, but nothing ever came 🥲.

**Comment by ikanakova** [comment]
>> You can go back to ViMusic, which doesn't change, but the developer doesn't give a damn about it, so it may not work at all soon either (if it still works...).
> 
> That was hell. Every week, I kept checking and hoping for a new update, but nothing ever came 🥲.

I don't anymore. I've long forgotten about ViMusic. RiMusic is much better and especially fast4x is much better 🙂

**Comment by ikanakova** [comment]
> Things are changing so fast on the app.

You can't be surprised when RiMusic develops fast4x 😁
And for me, quick changes are far better than no changes...
But I think of myself as a flexible person, so I understand that inflexible people may have a problem with that...

**Comment by dAtA-TRoN** [comment]
> I don't anymore. I've long forgotten about ViMusic. RiMusic is much better and especially fast4x is much better 🙂

The instant I gave RiMusic a try, I couldn't help but delete ViMusic, laughing like a mad scientist the whole time.

**Comment by NikunjKhangwal** [comment]
It's basically a double edged sword. I understand the reasoning here. I've never seen any other app change as rapidly as RiMusic does and it's fair normal people who just want to get things done wouldn't like it. But at the same time RiMusic takes feedback better than anything, hence the changes. So the conflicts are inevitable. I would recommend using any other ytm app (there are dozens) or sticking to old versions as others suggested.

**Comment by airisama019** [comment]
ok got it
then let's just split this into stable and preview just like newpipe

**Comment by NikunjKhangwal** [comment]
> ok got it then let's just split this into stable and preview just like newpipe

There are plans to divide settings between normal and expert mode.
You can give your feedback here #2049

**Comment by Vishcot** [comment]
> I kinda agree. Things are changing so fast on the app. While most things are still really easy to use/find some things are getting kinda complicated. And the rapid changes are bothering me as well.

i too agree with this! 🙏🏻🙏🏻🙏🏻
