### ISSUE TITLE
Lyric Provider

### ISSUE THREAD

**Issue by Abilomp** [fast4x/RiMusic#2046]
### Description

Brother i have an idea.
We use kuguo and LCRB for lyric so i suggest you to change it to Bring MUXICMATH lyric Provider for lyric in RI music.
And also do like -
1. If we press on lyric it has 2 type ..(i) Synochorized Lyric and (ii) Unsynochroized..
2. So removed this two type.
3. And Make like this if we press on lyric it will show Synochorized lyric, if not found then Unsynochorized will select automatically..
4. So we don't need to tap on such options for lyric.

5.  Most important is please remove kugou and Lcrb .. instead of them add MUSICMATCH

### Suggested Solution

Removing of kugou and lcrb lyric Provider .. instead of them add Musixmatch as on Spotify and youtube music..

**Comment by Abilomp** [comment]
Please Remove kugou and Lcrb.
Add MUSICMATCH lyric Provider..
And when playing song on player the name of song must get bold and bigger..

**Comment by JeePopuwu** [comment]
> Elimine kugou y Lcrb. Agregue el proveedor de letras MUSICMATCH. Y cuando reproduzca una canción en el reproductor, el nombre de la canción debe aparecer en negrita y más grande.

I think you don't understand why those two libraries were chosen instead of musicxmatch.  The reason was that permits, contracts, etc. are needed.  and the current ones do not need it.  that's why they were chosen

**Comment by Abilomp** [comment]
Will there some way for it.
Please

**Comment by Abilomp** [comment]
Ok no problem but can you do this 
In song player make the name of song bold and Thick ..
Current it thin and small also not bold..

**Comment by aneesh1122** [comment]
Musixmatch requires the token to fetch lyrics. Any type of login/token is a huge no for RiMusic.

Also, lyrics won't load completely according to their official api documentation. Spotdl somehow downloads complete synced lyrics from musixmatch.

Regarding your 2nd request, I also want to put the name of the song and singers at the centre and make the song's name bold and big.

Hope fast4x will listen to you 😅

**Comment by fast4x** [comment]
I always listen, player will be further improved, at the moment I will add bold and increase the greatness of the character in the text of the album and the artist.

**Comment by fast4x** [comment]
Musicmatch isn't planner because have commercial licence.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.37

**Comment by fast4x** [comment]
Implemented also totally transparent background in action bar, enable in appearance settings, available from version 0.6.37

**Comment by aneesh1122** [comment]
> I always listen, player will be further improved, at the moment I will add bold and increase the greatness of the character in the text of the album and the artist.

Have you added bold to only the song's name or both the song and the artist's name?

It will look better if only the song's name is in bold I think

**Comment by privacyfreak84** [comment]
> I always listen

Then please do take a look at #1976

**Comment by Avi-GG** [comment]
Why the lyrics are npt at all in sync, they are totally out of sync, I tried every setting to do this
