### ISSUE TITLE
In now playing album view, there's no clear indication to jump to currently playing playlist view

### ISSUE THREAD

**Issue by sharunkumar** [fast4x/RiMusic#2047]
### Steps to reproduce the bug

1. Play any playlist

### Expected behavior

There should be a clear indicatory (like a drawer handle) to open the currently playing playlist in album view

### Actual behavior

Only a vaguely translucent bar at the bottom (it used to be proper in earlier viersions)

### Screenshots/Screen recordings

![image](https://github.com/fast4x/RiMusic/assets/715417/106ed47e-ebb5-4e2c-ba3a-22d4797e66ef)

### RiMusic version

0.6.36.1

### Android version

Android 14

### Additional information

This pill was there in the older version:

![image](https://github.com/fast4x/RiMusic/assets/715417/0456ef4b-4c43-48f0-afe6-0903c22f409c)

**Comment by aneesh1122** [comment]
Go to settings -> Player appearance and then select one of these options

![Screenshot_2024-05-26-23-37-12-733_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/d81269f4-7a2f-4df1-9ebb-e1e365edfd09)

You can swipe up the bottom bar to open up your queue

**Comment by sharunkumar** [comment]
> You can swipe up the bottom bar to open up your queue

the issue is not that I can't do this. its that its not clear at first. there used to be a pill to indicate the same. its a UI/UX issue

**Comment by aneesh1122** [comment]
> > You can swipe up the bottom bar to open up your queue
> 
> the issue is not that I can't do this. its that its not clear at first. there used to be a pill to indicate the same. its a UI/UX issue
> 
> @aneesh1122 I've updated the expected image in the issue

Well, dev is clearly going for a clean experience. A little tinkering here and there and some prior experiences with other music players will make anyone realise what  that bottom bar does. I'm waiting for dev to make that bottom bar completely transparent.

Anyways, dev knows that some people don't like new changes so he will give options to modify the app the way you like.

**Comment by fast4x** [comment]
Pill isn't necessary, enable arrow button in actions bar how @aneesh1122 say from appearance settings
![Screenshot_20240526_230809](https://github.com/fast4x/RiMusic/assets/1484476/50aa929c-43eb-4c5f-b18f-0474a598a309)
