### ISSUE TITLE
Clicking on the mini player after clicking into currently playing playlist, does nothing

### ISSUE THREAD

**Issue by sharunkumar** [fast4x/RiMusic#2048]
### Steps to reproduce the bug

1. Play a song in a playlist
2. Click on the mini player to open the album art view
3. Click on the bottom bar to open the currently playing playlist
4. Click on the mini player

### Expected behavior

It is returned to the album art view

### Actual behavior

Nothing happens

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/715417/c4a50e7c-368e-4a3a-a4d0-dcd032863846

### RiMusic version

0.6.36.1

### Android version

Android 14

**Comment by aneesh1122** [comment]
https://github.com/fast4x/RiMusic/assets/45353488/88ef81f5-a5a4-4d8f-a256-48f68f623488

![images.jpeg](https://github.com/fast4x/RiMusic/assets/45353488/faf5b7fd-1cc2-4484-9368-cf27bbe15589)

**Comment by sharunkumar** [comment]
> VID_20240526_234823.mp4 
> ![images.jpeg](https://private-user-images.githubusercontent.com/45353488/333901213-faf5b7fd-1cc2-4484-9368-cf27bbe15589.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDkwNTQsIm5iZiI6MTcxNjc0ODc1NCwicGF0aCI6Ii80NTM1MzQ4OC8zMzM5MDEyMTMtZmFmNWI3ZmQtMWNjMi00NDg0LTkzNjgtY2YyN2JiZTE1NTg5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxODM5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTI4N2M0NTNjY2FjZTA5ZTIxMjg5MTQ3OTdlNTBhMzQzYWJkZGU2OWQzZTllOWMzNDA3ODZlZGY1YWQ2YTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XOtDcw2RZx6R5mb98MDrT4aT05im4duOBOvoZUlrBZI)

![Untitled](https://github.com/fast4x/RiMusic/assets/715417/822946d8-7a02-42ab-b4fc-06150ecfd3d7)

**Comment by fast4x** [comment]
But excuse me, queue is open from player... so for show player... slide down queue... not make sense open player from queue...

**Comment by sharunkumar** [comment]
> But excuse me, queue is open from player... so for show player... slide down queue... not make sense open player from queue...

Pretty sure in the older version we were able to jump from list to album art using this

In one case it's working and one case it's not working

**Comment by fast4x** [comment]
click on miniplayer it's not enabled only in queue list...

**Comment by sharunkumar** [comment]
> click on miniplayer it's not enabled only in queue list... 

Yeah that's what I wanted to report... It can minimize the queue list instead of doing nothing

**Comment by aneesh1122** [comment]
> > But excuse me, queue is open from player... so for show player... slide down queue... not make sense open player from queue...
> 
> Pretty sure in the older version we were able to jump from list to album art using this
> 
> In one case it's working and one case it's not working

In the older versions the queue page didn't have the mini player. It is added in the latest update.
