### ISSUE TITLE
you miss the old menu and actions in the queue (Gestures)

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#2050]
### Description

Before the last update we had a very good and conceptual queue menu

### Suggested Solution

but not anymore, now we have the list one, and at the same time we lost the option to put the next song on the right and remove it from the list on the left.  I would like them to come back x,d
![Screenshot_2024-05-26-13-58-42-579_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/c5a549ec-3e4e-43d2-9fcc-e595f9ca2017)

**Comment by aneesh1122** [comment]
You need to post the old queue menu so that we can know what options you're interested in.

The swipe action option is removed now. Maybe it will be added later.

**Comment by fast4x** [comment]
you talk about swipe actions?

**Comment by JeePopuwu** [comment]
> ¿Hablas de acciones de deslizar o de gestos sin acciones?

The prime

**Comment by aneesh1122** [comment]
Now is the right time to mention #1794 😅

**Comment by fast4x** [comment]
> Now is the right time to mention #1794 😅

yes! I'll add to analysis of new gestures

**Comment by aneesh1122** [comment]
> > Now is the right time to mention #1794 😅
> 
> yes! I'll add to analysis of new gestures 

Please also look at this #1605

**Comment by fast4x** [comment]
Implemented, available from version 0.6.42
