### ISSUE TITLE
Floating action button overlaps the mini player's next button

### ISSUE THREAD

**Issue by sharunkumar** [fast4x/RiMusic#2051]
### Steps to reproduce the bug

1. Play a song in a playlist
2. Click on the mini player
3. Click on the action bar to open the currently playing playlist

### Expected behavior

Floating action should be placed above the mini player

### Actual behavior

It overlaps the mini player

### Screenshots/Screen recordings

![Screenshot_20240526_120640](https://github.com/fast4x/RiMusic/assets/715417/f37f421a-63d3-4a8c-a0f5-e81c38934adf)

### RiMusic version

0.6.36.1

### Android version

Android 14

### Additional information

You can also notice this in the video in #2048

**Comment by fast4x** [comment]
Implemented custom position for floating actions... hold on and move where you want...
