### ISSUE TITLE
[accessibility] Text / Player Controls barely visible when enabling album art blurred backdrop, when the album art is white

### ISSUE THREAD

**Issue by sharunkumar** [fast4x/RiMusic#2052]
### Steps to reproduce the bug

1. Enable setting for displaying blurred album art as background
2. Have dark / pure black theme for the app
3. Play a song with album art having lots of white color
4. Open the album art view by clicking the mini player

### Expected behavior

There should be contrast between text and player controls, and the album art

### Actual behavior

Can barely read the text

### Screenshots/Screen recordings

![Screenshot_20240526_121908](https://github.com/fast4x/RiMusic/assets/715417/f8a9ce01-b3c1-4731-964e-8537b789adca)

![Screenshot_20240526_122036](https://github.com/fast4x/RiMusic/assets/715417/a3dc488a-832c-490a-a164-6b6e2ea9bdb3)

![Screenshot_20240526_122312](https://github.com/fast4x/RiMusic/assets/715417/a3d55471-30a2-4c4d-8659-1efa12b72310)

### RiMusic version

0.6.36.1

### Android version

Android 14

**Comment by fast4x** [comment]
#1965 
Implemented blur controls, available from version 0.6.37

**Comment by sharunkumar** [comment]
![Screenshot_20240527_100125.png](https://github.com/fast4x/RiMusic/assets/715417/ddd5a8a8-c1e0-4e3b-9cea-8707ecc5d216)

Will this work in essential controls as well? 🤔

**Comment by fast4x** [comment]
yes
