### ISSUE TITLE
Favorites not in the good place

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#2056]
### Description

With the new update categories replaced some playlist

I don't hate it but the favorite playlist that i often used got moved in "songs" that makes the top right icons crowded and i losed the feature to easely download and change the order of the playlist

### Suggested Solution

Move the favorites playlist in a playlist section or as an category and add back download buttons and rearange by listening time, etc...

### Alternatives

I always used the music section as an history and i think the download and top playlist is great there

But maybe users will prefer the old look? (add a toggle option?)

**Comment by OrangeZXZ** [comment]
Just noticed that i can hold to change the order 😅

**Comment by aneesh1122** [comment]
> add back download buttons

The only thing I agree with

**Comment by dAtA-TRoN** [comment]
> > add back download buttons
> 
> The only thing I agree with

Yep, download-buttons for the favorite list should be a no-brainer.
