### ISSUE TITLE
Replace setting quick option

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#2059]
### Description

I just don't feel the need most of the peoples sett up rimusic an then don't use them anymore

### Suggested Solution

Bring back the back button or an X button

### Alternatives

Add an option to chose what to put (equalisator, etc...)

### Additional Context

![SmartSelect_20240527_075246](https://github.com/fast4x/RiMusic/assets/104271365/1f74f45e-abf0-4e09-b0fd-ce7d60cec5a2)

**Comment by AquamarineDreams** [comment]
Song info maybe?

**Comment by OrangeZXZ** [comment]
> Song info maybe? #1735

could be an option if he adds custom button

**Comment by fast4x** [comment]
Implemented, available from version 0.6.37
