### ISSUE TITLE
Holding the cover to see details doesn't work with 'on device' songs

### ISSUE THREAD

**Issue by Cszyn** [fast4x/RiMusic#2060]
### Description

I have started to download some of my library in FLAC and holding the cover art doesn't display the quality
![441454906_408632722158580_2675008886097646792_n](https://github.com/fast4x/RiMusic/assets/147027531/2874ba81-cc4c-45ad-b78c-f29b4112ea43)

### Suggested Solution

Fast, please fix.

**Comment by Cszyn** [comment]
I'll modify the post a bit when I get my hands on my pc the mobile ui is so bad.

**Comment by aneesh1122** [comment]
Hold the album cover

**Comment by Cszyn** [comment]
> Hold the album cover

OK the more I use this app the more I wish for a hint section Holly crap

**Comment by aneesh1122** [comment]
> > Hold the album cover
> 
> OK the more I use this app the more I wish for a hint section Holly crap

Reopen this issue. Holding the cover to see details doesn't work with 'on device' songs

**Comment by fast4x** [comment]
Implemented, available from version 0.6.37

**Comment by aneesh1122** [comment]
> Implemented, available from version 0.6.37

Fast4x to every bugs and requests today
![slap-everyone-slap-dad-the-slap.gif](https://github.com/fast4x/RiMusic/assets/45353488/26995a30-ba1d-4670-a26b-1bf794c6850d)

**Comment by fast4x** [comment]
![giphy (4).gif](https://github.com/fast4x/RiMusic/assets/1484476/a6c8305d-7e90-47c5-8378-17081ece3def)
