### ISSUE TITLE
player ui

### ISSUE THREAD

**Issue by teacupmaps** [fast4x/RiMusic#2062]
### Steps to reproduce the bug

open any song

### Expected behavior

as before the last update

### Actual behavior

on the picture below:
1) shadows cut off
2) very ugly shadow
3) row of random pixels??

### Screenshots/Screen recordings

![20240526_221352](https://github.com/fast4x/RiMusic/assets/158172547/7db616c2-062b-4fab-947a-ff29e3fe1178)

### RiMusic version

0.6.35

### Android version

Android 10

**Comment by fast4x** [comment]
3... is fixed from latest version 0.6.36.1

**Comment by aneesh1122** [comment]
> 3... is fixed from latest version 0.6.36.1

Please fix 1 🥺

**Comment by teacupmaps** [comment]
> You can deactivate the ugly shadows by going to settings -> 2nd tab -> Controls type and choose 'Essential'

where is it? i can't find it

**Comment by fast4x** [comment]
> > You can deactivate the ugly shadows by going to settings -> 2nd tab -> Controls type and choose 'Essential'
> 
> where is it? i can't find it

settings > player appearance > controls type

**Comment by fast4x** [comment]
Fixed 1, available from version 0.6.37
