### ISSUE TITLE
[Feature]: Navigation Bar Corner Style (Radius)

### ISSUE THREAD

**Issue by drago-bit** [fast4x/RiMusic#2065]
### Description

Having different styles to the top and bottom part of the **Navigation Bar** seems a bit inconvenient.

![RiMusic](https://github.com/fast4x/RiMusic/assets/170959159/71ef1f16-1713-4111-98a2-defbef0f0f23)

### Suggested Solution

It would be nice to have them both in the same style, like all the four corners have the same curvature as the bottom two.

### Alternatives

Alternatively, all the four corners can have zero radius too, but the suggested solution is better with the floating mini player.

### Additional Context

Thanks for the app by the way.

**Comment by fast4x** [comment]
It's just implemented in new ui layout... #1812
