### ISSUE TITLE
another player ui redesign by me hehe

### ISSUE THREAD

**Issue by col1iv** [fast4x/RiMusic#2069]
### Description

made an (other) player redesign

### Suggested Solution

![Picsart_24-05-27_18-54-50-338](https://github.com/fast4x/RiMusic/assets/152646768/882f563d-b342-4670-9e8a-5cb84277fe51)

**Comment by aneesh1122** [comment]
![giphy.gif](https://github.com/fast4x/RiMusic/assets/45353488/c9a52619-9f48-4cdb-a575-b6238ab8cbf6)

**Comment by JeePopuwu** [comment]
No
![FB_IMG_1716240199904](https://github.com/fast4x/RiMusic/assets/159836335/d455e839-c8b6-4822-89c8-a96395b4a1e0)

**Comment by fast4x** [comment]
I have two questions
- I don’t know what’s new?
- are you still useful?
