### ISSUE TITLE
[Feature]: Switching between interface should remember the interface specific settings

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#207]
### Description

When switching between RiMusic and ViMusic interface, the last used settings get reset.

### Suggested Solution

The settings should be remembered like the defined thumbnail size and timeline.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.13

**Comment by NikunjKhangwal** [comment]
I think newer updates messed something up. Switching between interfaces started reseting settings again.
