### ISSUE TITLE
Bring back old vi interface 

### ISSUE THREAD

**Issue by daavidfr** [fast4x/RiMusic#2073]
### Description

![Screenshot_2024-05-28-11-14-20-927_app vitune android](https://github.com/fast4x/RiMusic/assets/171004603/609563b1-06d0-469e-9dd6-f5333749ac90)
Can you bring back this vi interface

### Suggested Solution

Make the vi interface like this and make ri music interface with customisation and everything

**Comment by aneesh1122** [comment]
Interface in use -> ViMusic
Controls type -> essential

**Comment by fast4x** [comment]
In new version 0.6.37 you can change like you want.

**Comment by fast4x** [comment]
Friend, ViMusic is the inspiration not RiMusic.
You can get similar but not equal.

**Comment by fast4x** [comment]
next version you can get much similar with style essential for info album/artist and controls buttons.

you can use essential for info and modern for controls or viceversa.

**Comment by daavidfr** [comment]
> Friend, ViMusic is the inspiration not RiMusic. You can get similar but not equal.

Okay bro and one more thing can you make the font bold like in the screenshot i shared above

**Comment by fast4x** [comment]
just implemented in new version 

![Screenshot_2024-05-28-09-14-34-101_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/1484476/42e1e08a-7755-4b89-a120-d940460953dc)

**Comment by aneesh1122** [comment]
> just implemented in new version 
> 
> ![Screenshot_2024-05-28-09-14-34-101_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/1484476/42e1e08a-7755-4b89-a120-d940460953dc)
> 
> 

Please don't make artist's name also bold. Only song's name should be in bold

**Comment by dAtA-TRoN** [comment]
> Please don't make artist's name also bold. Only song's name should be in bold 🙏

I have to say that I don't like that either. This just screams for 'options' 🙃!

**Comment by fast4x** [comment]
> > just implemented in new version
> > ![Screenshot_2024-05-28-09-14-34-101_it.fast4x.rimusic.debug.jpg](https://private-user-images.githubusercontent.com/1484476/334305548-42e1e08a-7755-4b89-a120-d940460953dc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODgxODUsIm5iZiI6MTcxNjg4Nzg4NSwicGF0aCI6Ii8xNDg0NDc2LzMzNDMwNTU0OC00MmUxZTA4YS03NzU1LTRiODktYTEyMC1kOTQwNDYwOTUzZGMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMDkxODA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODgzYTk3NTQ4NDJlOGEyOTcyOGYwN2U1ZmQ1MzRkNWMyMDM3OWE1NDlkY2FmMWIwMmVlMmRiNTgwNTRkOTBmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2gD69c3WGGkE5T2AmetRmy0zDbXzkSUSs5Z-pAnisDE)
> 
> Please don't make artist's name also bold. Only song's name should be in bold 🙏

Done
![Screenshot_20240528_111754](https://github.com/fast4x/RiMusic/assets/1484476/19db9101-9182-4333-8845-2d35df523bff)

**Comment by ikanakova** [comment]
@shiva0508 I already answered you in #2079.

**Comment by shiva0508** [comment]
> @shiva0508 I already answered you in #2079.

thanks
