### ISSUE TITLE
[Feature]: Multiple colors in fluid background

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2074]
### Description

[kmpalette](https://github.com/jordond/kmpalette) is made in kotlin and can extract many colors from an image. 

Right now fluid background uses only one color. Fluid background will look great if multiple colors are used.

This is what it can do

![ios-demo](https://github.com/fast4x/RiMusic/assets/45353488/8f0ca29f-99bb-47d1-a530-3b99f0a9b0ea)

### Suggested Solution

you can get something like this

https://github.com/fast4x/RiMusic/assets/45353488/c0128412-1c09-4d28-9be7-005af4177ab3

The app is [SaltPlayer](https://github.com/Moriafly/SaltPlayerSource)

**Comment by AquamarineDreams** [comment]
Related to #1878

**Comment by fast4x** [comment]
Colors used are:

1. dominant from image 
2. background3 from theme (you can select in custom colors theme)
3. accent from theme

you would use only colors from image?

**Comment by fast4x** [comment]
> > i can add all colors
> 
> how many colors can you add in fluid gradient? Is 3 possible?

I think I can add all the colors of the universe hahahah joke obviously

**Comment by aneesh1122** [comment]
> > > i can add all colors
> > 
> > 
> > how many colors can you add in fluid gradient? Is 3 possible?
> 
> I think I can add all the colors of the universe hahahah joke obviously

Then please extract as many colors as possible from the album cover and use it. you have 10 colors in RiMusic. Please map the colors as you want. kmpalette gives you at most 7 colors. Every 7 colors will not be available everytime so code accordingly.

right now "Fluid gradient from cover" uses only 2 colors to form gradient

1) Dominant from image
2) Background 3

- Dominant color choosing can be improved since there are songs which doesn't have right dominant color. Examples
![331250949-92caf84a-e80c-4ed1-bd66-4e2edd0c81f2](https://github.com/fast4x/RiMusic/assets/45353488/5aa8e037-dc16-47da-8d39-4a555f55393d)

- Fluid gradient will look great if you use 3 colors.

**Comment by fast4x** [comment]
ok will be done

**Comment by JeePopuwu** [comment]
and I'm waiting for my little hearts and progress bars x,D.  Be careful, I love that they are implementing so many things and fixing the Bugs.

**Comment by fast4x** [comment]
> and I'm waiting for my little hearts and progress bars x,D.  Be careful, I love that they are implementing so many things and fixing the Bugs.

ticket number?

**Comment by JeePopuwu** [comment]
> > y estoy esperando mis corazoncitos y barras de progreso x,D. Ojo, me encanta que estén implementando tantas cosas y arreglando los errores.
> 
> ¿numero de ticket?

#1624

**Comment by aneesh1122** [comment]
@fast4x 

I got some new ideas. Please try if it's possible

1) when "fluid gradient background from cover" is chosen, take all the colors you'll get from kmpalette(max 7 colors, min 3 colors) and make fluid gradient using all the colors. It will not look messy because one color will be similar to another color anyways.

2) take colors for the dynamic theme like this
- Background 1 = Dominant from cover
- Background 3 = any color shade among Vibrant. Sometimes all the 3 vibrant colors won't be present so prioritise among Vibrant colors and select one of them.

Like if Vibrant is not available then select Dark vibrant or else select Light Vibrant.

I think this implementation will look good.

Sorry for being late and if you have already started working on it.

**Comment by aneesh1122** [comment]
Tried to replicate the different colors from album in fluid gradient using custom theme

https://github.com/fast4x/RiMusic/assets/45353488/f9f304cf-357b-41ff-a081-0d78ca11b085

![IMG_20240602_125126.jpg](https://github.com/fast4x/RiMusic/assets/45353488/b8293f2e-471a-445d-8928-6a0755403e2d)
