### ISSUE TITLE
[Feature]: Tapping on lyrics to seek

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#208]
### Description

You can only read the lyrics with current synchronized line but can't seek the song by pressing on a lyrics line.

### Suggested Solution

I'm not sure what provider this app is using for lyrics or is it even possible to implement but if it is, it would be a really nice qol update. Currently if you want to seek to a specific line in song, you have to go through the song progress bar (timeline) and match it with the lyrics.

### Additional Context

It's going to clash with the "Toggle Lyrics" setting, If it gets implemented. What you can do is make the lyrics toggle only when tapping on the left and right edge of the album art (the empty space) so both works.

**Comment by fast4x** [comment]
If I understand correctly, you would like to click on a line of text and advance the player to that point.

**Comment by NikunjKhangwal** [comment]
Yes, Exactly. Same way it works in apps like Spotify.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.21

**Comment by NikunjKhangwal** [comment]
Thanks a lot
