### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#2081]
### Steps to reproduce the bug

Same

### Expected behavior

I know it can be fixed that's why I don't worry so much xd

### Actual behavior

I just want to say that I do disconnect from the network the Crashea application in degraded mode on the move

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/159836335/e67062a2-8734-4809-a8c2-12cff7aad58a

### RiMusic version

0.6.36 Custom version

### Android version

Android 13

**Comment by fast4x** [comment]
try with last released version 0.6.36.1

**Comment by JeePopuwu** [comment]
> Pruebe con la última versión lanzada 0.6.36.1.

that's the one I have x,d, I just put it wrong sorry

**Comment by fast4x** [comment]
Improved image caching, available from version 0.6.37
