### ISSUE TITLE
"Chronic Bugs: Sharing Button Broken, Duplicate Fav Button, Quick Picks List Not Cached"

### ISSUE THREAD

**Issue by Official-Mlx** [fast4x/RiMusic#2085]
### Steps to reproduce the bug

Image of the first bug:
The share button does not work in this menu.
![Screenshot_2024-05-29-14-31-42-880_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/74877307/bddce7d5-e04c-4a70-81ba-5239973b2679)

Image of the second bug:
There is no need to have two favorite buttons.
![IMG_20240529_143428](https://github.com/fast4x/RiMusic/assets/74877307/9739fc35-ed8e-4f9a-92a0-fe25d7070b25)

Image of the third bug:
This section should be cached and not reloaded every time.
![IMG_20240529_143649](https://github.com/fast4x/RiMusic/assets/74877307/1f0bf34d-79c9-4de8-995f-6d62a9ab552e)

### Expected behavior

In the first bug, the sharing button should have the ability to share the link, in the second bug, the extra buttons should be removed, and in the third bug, this list should be cached.

### Actual behavior

‍

### RiMusic version

0.1.5

### Android version

10

**Comment by fast4x** [comment]
Duplicate like can be changed in the next version, you can select type of controls, infos and like icon type, go to artist/album from menu isn't planned.

**Comment by fast4x** [comment]
Fixed share action from menu in player, available from version 0.6.37
