### ISSUE TITLE
Add an Easter Egg to RiMusic

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#2086]
### Description

![sketch1716980334474](https://github.com/fast4x/RiMusic/assets/71184627/6d694edd-04cf-4c79-8a5b-3a8841366732)

I think it would be funny to have an Easter egg feature included. Similar to the hidden features in Android where tapping the version number multiple times unlocks a surprise, I propose something similar for RiMusic.

### Suggested Solution

An Easter egg could be activated by quickly tapping the "Ri" logo multiple times. The exact surprise—be it an animation, sound, mini-game, hidden message, or another playful feature—can be left to your creative mind.

### Additional Context

Easter eggs in apps provide a delightful, unexpected experience that can enhance user satisfaction and engagement. Using the "Ri" logo as the trigger keeps the feature hidden but easily accessible for those in the know. I believe this small addition could bring a lot of joy to users and add a unique charm to the RiMusic app.

**Comment by fast4x** [comment]
![giphy (5).gif](https://github.com/fast4x/RiMusic/assets/1484476/a7dfc60b-ef4b-4ffa-91b7-ffdf8d160d51)

**Comment by fast4x** [comment]
![giphy (6).gif](https://github.com/fast4x/RiMusic/assets/1484476/305ca879-e5c0-4f92-a4d1-dd3ba34a749d)

**Comment by fast4x** [comment]
![giphy (8).gif](https://github.com/fast4x/RiMusic/assets/1484476/103698c7-0926-471a-9071-cdb0c2fbd038)

**Comment by dAtA-TRoN** [comment]
https://github.com/fast4x/RiMusic/assets/71184627/345b0222-c3eb-410a-a85f-1cb00f9e5791

**Comment by dAtA-TRoN** [comment]
> ![giphy (8).gif](https://github.com/fast4x/RiMusic/assets/1484476/103698c7-0926-471a-9071-cdb0c2fbd038)
> 
> 

Could this be the secret ritual dance that fast4x performs whenever he accepts a proposal 🤔!?

**Comment by AquamarineDreams** [comment]
> > ![giphy (8).gif](https://private-user-images.githubusercontent.com/1484476/334794782-103698c7-0926-471a-9071-cdb0c2fbd038.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTY2MjMsIm5iZiI6MTcxNjk5NjMyMywicGF0aCI6Ii8xNDg0NDc2LzMzNDc5NDc4Mi0xMDM2OThjNy0wOTI2LTQ3MWEtOTA3MS1jZGIwYzJmYmQwMzguZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMTUyNTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzBkOWUyNWNmYWFjYmM3N2JhMTk2ZjZiMGQ1MjA0MTQ0NGI0ZTljMTUwZmE5NmIzNWQwZTI1Y2QzY2ZjMzdmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NpWWzPFJTZJDf9orNvie6VGZ0nB8zec7zeQIS7KdL9A)
> >       
> >         [
> >           
> >         
> >             ![giphy (8).gif](https://private-user-images.githubusercontent.com/1484476/334794782-103698c7-0926-471a-9071-cdb0c2fbd038.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTY2MjMsIm5iZiI6MTcxNjk5NjMyMywicGF0aCI6Ii8xNDg0NDc2LzMzNDc5NDc4Mi0xMDM2OThjNy0wOTI2LTQ3MWEtOTA3MS1jZGIwYzJmYmQwMzguZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMTUyNTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzBkOWUyNWNmYWFjYmM3N2JhMTk2ZjZiMGQ1MjA0MTQ0NGI0ZTljMTUwZmE5NmIzNWQwZTI1Y2QzY2ZjMzdmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NpWWzPFJTZJDf9orNvie6VGZ0nB8zec7zeQIS7KdL9A)
> >           ](https://private-user-images.githubusercontent.com/1484476/334794782-103698c7-0926-471a-9071-cdb0c2fbd038.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTY2MjMsIm5iZiI6MTcxNjk5NjMyMywicGF0aCI6Ii8xNDg0NDc2LzMzNDc5NDc4Mi0xMDM2OThjNy0wOTI2LTQ3MWEtOTA3MS1jZGIwYzJmYmQwMzguZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMTUyNTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzBkOWUyNWNmYWFjYmM3N2JhMTk2ZjZiMGQ1MjA0MTQ0NGI0ZTljMTUwZmE5NmIzNWQwZTI1Y2QzY2ZjMzdmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NpWWzPFJTZJDf9orNvie6VGZ0nB8zec7zeQIS7KdL9A)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/1484476/334794782-103698c7-0926-471a-9071-cdb0c2fbd038.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTY2MjMsIm5iZiI6MTcxNjk5NjMyMywicGF0aCI6Ii8xNDg0NDc2LzMzNDc5NDc4Mi0xMDM2OThjNy0wOTI2LTQ3MWEtOTA3MS1jZGIwYzJmYmQwMzguZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMTUyNTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzBkOWUyNWNmYWFjYmM3N2JhMTk2ZjZiMGQ1MjA0MTQ0NGI0ZTljMTUwZmE5NmIzNWQwZTI1Y2QzY2ZjMzdmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NpWWzPFJTZJDf9orNvie6VGZ0nB8zec7zeQIS7KdL9A)
> 
> Could this be the secret ritual dance that fast4x performs whenever he accepts a proposal 🤔!?

Tf 💀

**Comment by drago-bit** [comment]
I second this. The overall user experience will be delightful.

**Comment by ikanakova** [comment]
fast4x could save this for Easter 😄 Or Christmas - an Easter egg would be a cool Christmas 🎄 present 🎁

**Comment by fast4x** [comment]
> fast4x could save this for Easter 😄 Or Christmas - an Easter egg would be a cool Christmas 🎄 present 🎁

![giphy (9).gif](https://github.com/fast4x/RiMusic/assets/1484476/17cda91e-9b3a-41bb-85ab-f67fdaa24b80)

**Comment by aneesh1122** [comment]
@fast4x will implement it and he won't tell anyone after implementing it. 

Everyone will keep tapping the RiMusic logo after every update to see whether he added it 😂

**Comment by AquamarineDreams** [comment]
> @fast4x will implement it but he won't tell anyone after implementing it.
> 
> Everyone will keep tapping the RiMusic logo after every update to see whether he added it 😂

He will never close this ticket 😅

**Comment by drago-bit** [comment]
Can't wait to tap.

TAP-TAP ............

TAP-TAP ............

😅😁

**Comment by aneesh1122** [comment]
> ohhhhhh yyyeeessss 
> 
>  ![giphy (10).gif](https://github.com/fast4x/RiMusic/assets/1484476/99905285-3ae0-43cb-91f6-9e34d0371849)
> 
> 

Hell, don't even tell where you've hidden the Easter egg.

Implement it silently and add it in any random place, preferably a place most of the people don't visit. 😂

**Comment by fast4x** [comment]
🤣🤣🤣
![giphy (11).gif](https://github.com/fast4x/RiMusic/assets/1484476/766dd4a7-3a13-474a-add5-16817f27af9e)

**Comment by dAtA-TRoN** [comment]
> Data tron will either love it or hate it but it will keep him busy and that means less requests for you 😂😂

@ fast4x See, I know he hates me 🤣🤣!

**Comment by fast4x** [comment]
> > Data tron will either love it or hate it but it will keep him busy and that means less requests for you 😂😂
> 
> @ fast4x See, I know he hates me 🤣🤣!

but he loves you like all of us

![giphy (12).gif](https://github.com/fast4x/RiMusic/assets/1484476/ec7c5bd7-97cd-4f83-a33d-bb0ffb0bde71)

**Comment by dAtA-TRoN** [comment]
Hmm, I wonder what the Easter egg will be! Maybe a Snake clone where you play as fast4x, gobbling up GitHub tasks 🤔!?

![sketch1717006541289.png](https://github.com/fast4x/RiMusic/assets/71184627/cf3dd532-e944-4b8e-a575-43ab92f63a6c)

**Comment by fast4x** [comment]
![giphy (13).gif](https://github.com/fast4x/RiMusic/assets/1484476/3a57a557-bddb-44a8-911b-80de5f97e137)

**Comment by drago-bit** [comment]
> ![giphy (13).gif](https://github.com/fast4x/RiMusic/assets/1484476/3a57a557-bddb-44a8-911b-80de5f97e137)
> 
> 

What? Already? 🤩

**Comment by fast4x** [comment]
Implemented first easter egg... What is it? I don’t know 
Available from version 0.6.37 and other in future release... lol

**Comment by dAtA-TRoN** [comment]
> What is it? I don’t know

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/cab07608-8fc8-400c-b8ee-337337af0044)

**Comment by drago-bit** [comment]
Everyone, get ready your fingers.

Tap game begins. 🤩😎

**Comment by shiva0508** [comment]
i too found it, bit glitchy but liked it 
![image](https://github.com/fast4x/RiMusic/assets/164598229/a7005d6a-9af8-4848-8cba-e9b6ba3701c2)
