### ISSUE TITLE
Shake to Shuffle Next or All songs

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#2088]
### Description

We have a shake to skip feature, but I would love a shake to shuffle feature.

### Suggested Solution

Add a shake to shuffle option and make the shake to skip a multiple-choice setting.

### Alternatives

Make a second option that doesn't shuffle the current song.

### Additional Context

I can hold the up volume button to skip and the down volume button to unskip, but I don't have a fast way to shuffle the queue (I use shuffle often).

**Comment by AquamarineDreams** [comment]
Why do this makes so much sense in my mind?

**Comment by aneesh1122** [comment]
> Why do this makes so much sense in my mind?

Because when you shake your mobile you'll literally shake the songs too to rearrange them in random order? 😅
