### ISSUE TITLE
Add quick share button

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2089]
### Description

Those guys who use YouTube revanced may know this. In revanced you can enter the name of the app and it will use that app to download videos externally

![Screenshot_2024-05-29-21-01-59-845_app revanced android youtube](https://github.com/fast4x/RiMusic/assets/45353488/b7a8675f-9413-4c8a-baaf-584b165a7ebb)

https://github.com/fast4x/RiMusic/assets/45353488/e1a2d3dc-079b-413e-a411-08a0bf043975

As soon as you press 'download' button it quickly shares the link to an external app.
### Suggested Solution

Add 'quick share' buttons here

![Screenshot_2024-05-29-21-09-03-165_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/d6442e4f-30da-456b-a5a6-2ab28bcd2505)

![Screenshot_2024-05-29-21-07-58-437_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/84495af8-d0b2-4958-96b8-6797c2d68a1f)

### Additional Context

It can still be done by sharing the link from RiMusic to this YouTube downloading app but this quick button will act like a shortcut.

It won't be illegal because RiMusic would be only sharing the link. It can be used to share links to WhatsApp or some other app of the user's wish.

I want to do this but with a single tap button  shortcut

https://github.com/fast4x/RiMusic/assets/45353488/c8ed9f5e-85fa-4f15-9959-fb1657a989b5

**Comment by ikanakova** [comment]
But RiMusic doesn't download anything in the sense of storing it on the device (which is illegal), it downloads (like Spotify) to a cache for offline listening.

**Comment by aneesh1122** [comment]
> But RiMusic doesn't download anything in the sense of storing it on the device (which is illegal), it downloads (like Spotify) to a cache for offline listening.

And that's why I suggested to add the support of external downloader.

RiMusic won't download the song. It will simply share the song's link to an external downloader.

**Comment by ikanakova** [comment]
> > But RiMusic doesn't download anything in the sense of storing it on the device (which is illegal), it downloads (like Spotify) to a cache for offline listening.
> 
> And that's why I suggested to add the support of external downloader.
> 
> RiMusic won't download the song. It will simply share the song's link to an external downloader.

RiMusic already includes a share button. And I certainly don't think it's a good idea to add a special button for illegal downloads, even in another app.

**Comment by dAtA-TRoN** [comment]
A download function isn't advisable, even if it's outsourced. fast4x would be taking on too much risk.

**Comment by aneesh1122** [comment]
> > > But RiMusic doesn't download anything in the sense of storing it on the device (which is illegal), it downloads (like Spotify) to a cache for offline listening.
> > 
> > And that's why I suggested to add the support of external downloader.
> > 
> > RiMusic won't download the song. It will simply share the song's link to an external downloader.
> 
> RiMusic already includes a share button. And I certainly don't think it's a good idea to add a special button for illegal downloads, even in another app.

Well, revanced has it so I thought it wouldn't be illegal.

I know RiMusic includes a share button but it's much easier to just tap a button and download the song.

**Comment by aneesh1122** [comment]
> A download function isn't advisable, even if it's outsourced. fast4x would be taking on too much risk.

Let's name it 'quick share' then?

You can add any app you want like WhatsApp.

RiMusic would be only sharing the link.

**Comment by ikanakova** [comment]
>> A download function isn't advisable, even if it's outsourced. fast4x would be taking on too much risk.
> 
> Let's name it 'quick share' then?
> 
> You can add any app you want like WhatsApp.
> 
> RiMusic would be only sharing the link.

Somehow I don't understand the difference between Quick Share and the current Share button.

**Comment by dAtA-TRoN** [comment]
> Let's name it 'quick share' then?\n\nYou can add any app you want like WhatsApp.\n\nRiMusic would be only sharing the link.

Like I said, anything going in that direction, I wouldn't support. Besides, it would also be a pretty niche feature. But hey, you don't have to convince me. You just have to convince fast4x 🤷🏻‍♂️.

**Comment by aneesh1122** [comment]
> >> A download function isn't advisable, even if it's outsourced. fast4x would be taking on too much risk.
> > 
> > Let's name it 'quick share' then?
> > 
> > You can add any app you want like WhatsApp.
> > 
> > RiMusic would be only sharing the link.
> 
> Somehow I don't understand the difference between Quick Share and the current Share button.

Quick share : just one tap and the link will be shared to the pre-selected app. 1 step

Share : select share, search for the app, select the app. 3 steps(searching for the app  also takes time)

**Comment by aneesh1122** [comment]
> > Let's name it 'quick share' then?\n\nYou can add any app you want like WhatsApp.\n\nRiMusic would be only sharing the link.
> 
> Like I said, anything going in that direction, I wouldn't support. Besides, it would also be a pretty niche feature. But hey, you don't have to convince me. You just have to convince fast4x 🤷🏻‍♂️.

Fast4x won't be encouraging us to download songs. He will only let us share links quickly.

Now people can use it to share links to WhatsApp or any other app of their wish.

**Comment by dAtA-TRoN** [comment]
> Quick share : just one tap and the link will be shared to the pre-selected app. 1 step\n\nShare : select share, search for the app, select the app. 3 steps(searching for the app also takes time)

That's exactly how I understood it. But I still maintain that it would be an absolute niche feature. I don't think many people would use it. But as I said, I don't want to poison the well here. This is just my opinion. Maybe some people here see it differently.

**Comment by ikanakova** [comment]
> Quick share : just one tap and the link will be shared to the pre-selected app. 1 step
> 
> Share : select share, search for the app, select the app. 3 steps(searching for the app also takes time)

It seems like a useless feature to me. And I can't think of an app that would allow this... But as dAtA-TRoN says, it all depends on fast4x.

**Comment by aneesh1122** [comment]
@fast4x will you be able to add this 'quick share' button?

Pls give your opinion. I'll close the issue if you feel it's illegal.

IMO it would have been illegal if you were sharing the download link. The song's link is public.

**Comment by fast4x** [comment]
Follow my reasoning, RiMusic respects the copyright on everything including the songs that YT and YTM offer completely free of charge. RiMusic cannot contain facilitated sharing features that could be used as a shortcut to illegal downloading. 

RiMusic is a player that must respect the main source of the multimedia content it plays. It is absolutely not nice to encourage downloading content that can be listened to in a simple, legal and respectful way.

For these reasons I agree with others that RiMusic does not need to contain additional sharing links.

**Comment by AquamarineDreams** [comment]
That "quick share" already exist. It's called share 👍

Here's a video of me downloading a song with seal:

https://github.com/fast4x/RiMusic/assets/140275860/0bc98786-bc28-43f3-8ed9-d2cb4a2d7c06

> Well, revanced has it so I thought it wouldn't be illegal.
> 
> I know RiMusic includes a share button but it's much easier to just tap a button and download the song.
> 
> You don't even need to call it a 'download' button. Just call it a quick share button where we can define which app to use to quick share.
> 
> Link sharing isn't illegal. Right?

Btw is Youtube Vanced your standard for legality?

**Comment by AquamarineDreams** [comment]
@aneesh1122 
That "quick share" already exist. It's called share 👍

Here's a video of me downloading a song with seal:

https://github.com/fast4x/RiMusic/assets/140275860/c9011ff9-17c7-4a4e-8e6e-1b96987f50ab

> Well, revanced has it so I thought it wouldn't be illegal.
> 
> I know RiMusic includes a share button but it's much easier to just tap a button and download the song.
> 
> You don't even need to call it a 'download' button. Just call it a quick share button where we can define which app to use to quick share.
> 
> Link sharing isn't illegal. Right?

Btw is Youtube Vanced your standard for legality?

**Comment by aneesh1122** [comment]
> @aneesh1122 
> That "quick share" already exist. It's called share 👍
> 
> Here's a video of me downloading a song with seal:
> 
> https://github.com/fast4x/RiMusic/assets/140275860/c9011ff9-17c7-4a4e-8e6e-1b96987f50ab
> 
> > Well, revanced has it so I thought it wouldn't be illegal.
> > 
> > I know RiMusic includes a share button but it's much easier to just tap a button and download the song.
> > 
> > You don't even need to call it a 'download' button. Just call it a quick share button where we can define which app to use to quick share.
> > 
> > Link sharing isn't illegal. Right?
> 
> Btw is Youtube Vanced your standard for legality?

https://github.com/fast4x/RiMusic/issues/2089#issuecomment-2137776319
