### ISSUE TITLE
annoying pop up of lyrics 

### ISSUE THREAD

**Issue by BesidesManthan** [fast4x/RiMusic#2090]
### Description

When we switch to lyrics there is a pop up of lyrics found that In my opinion looks very bad if dev can remove it and make the player ui more like vi music the app will be the best out there 

### Suggested Solution

Simply removing the pop up of lyrics found And ui of either innertune or vi music can be adopted

**Comment by BesidesManthan** [comment]
Can you elaborate?

**Comment by aneesh1122** [comment]
> No

Well, I at least agree that either pop up toasts should be made optional or smaller. Small and subtle.

**Comment by BesidesManthan** [comment]
That's what I'm saying and reddit users report this too that somewhat the ui is kind of over quirky you can go see it yourself that's why I'm saying just removing the popup and making the interface more vi music like (it being the fork) makes it the best out there Reddit is like ground reporting for Android

**Comment by aneesh1122** [comment]
> making the interface more vi music like (it being the fork) makes it the best out there Reddit is like ground reporting for Android

Naah. As much as I respect ViMusic, it's history now.

You can still get the same ViMusic player UI but you'll not be able to evolve if you're stuck in past

**Comment by aneesh1122** [comment]
> That's what I'm saying and reddit users report this too that somewhat the ui is kind of over quirky you can go see it yourself that's why I'm saying just removing the popup and making the interface more vi music like (it being the fork) makes it the best out there Reddit is like ground reporting for Android 

Pls share the post's link.

**Comment by BesidesManthan** [comment]
Just type ri music on Android subreddit or simply reddit and see the first 10 to 12 posts

**Comment by BesidesManthan** [comment]
I love the app it's the best out there but all that makes it a dealbreaker for me is ui that's what I requested various comments can be found appreciating the app and at the same time talking how the ui can get some improvements and I also appreciate the bottom navigation bar too I love the app of you can please I'll still be a user though 


![Screenshot_20240530-000133](https://github.com/fast4x/RiMusic/assets/171177813/a07c94e2-f821-4f5a-b601-a27112f84c5e)

**Comment by aneesh1122** [comment]
> I love the app it's the best out there but all that makes it a dealbreaker for me is ui that's what I requested various comments can be found appreciating the app and at the same time talking how the ui can get some improvements and I also appreciate the bottom navigation bar too I love the app of you can please I'll still be a user though 
> 
> 
> ![Screenshot_20240530-000133](https://github.com/fast4x/RiMusic/assets/171177813/a07c94e2-f821-4f5a-b601-a27112f84c5e)
> 

The player UI can be made to look like ViMusic.

The overall UI though, will be difficult especially since the whole UI got changed(for the better).

Doesn't this look like ViMusic player to you?
![Screenshot_2024-05-30-00-24-02-814_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/64cef17f-23d9-499f-94da-8a9946072a03)

**Comment by JeePopuwu** [comment]
I went and found this
![Screenshot_2024-05-29-14-00-02-107_com android chrome](https://github.com/fast4x/RiMusic/assets/159836335/c6b910b5-1b1a-4ce1-90d9-d7da3657f5b0)

![Screenshot_2024-05-29-13-59-32-634_com android chrome](https://github.com/fast4x/RiMusic/assets/159836335/bdc2eaf4-432a-4f3d-99db-ba5da331e6c0)
and several said that they did not like the interface, but don't worry, the current interface is very good and unique of its kind, they are just not used to it, you leave your mark and make it unique.

**Comment by BesidesManthan** [comment]
The playbar can be moved more down with the buttons and the placement of the icon/thumbnail can be more like centred or say like 35 to 65 ratio in the screen like this hope you remove the lyrics pop up first that annoys the most I love how you talked it out usually dev take it as a disregard for their art but props to you man I hope you may work this all out 

Let me remind you again the. Ui improvement and the lyrics pop up to be removed is all that is needed
![Screenshot_20240530-004019](https://github.com/fast4x/RiMusic/assets/171177813/a1f3ab89-9d16-4a06-8fc2-6e3911c1041b)

**Comment by BesidesManthan** [comment]
> I went and found this ![Screenshot_2024-05-29-14-00-02-107_com android chrome](https://private-user-images.githubusercontent.com/159836335/334932625-c6b910b5-1b1a-4ce1-90d9-d7da3657f5b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMTAyNjYsIm5iZiI6MTcxNzAwOTk2NiwicGF0aCI6Ii8xNTk4MzYzMzUvMzM0OTMyNjI1LWM2YjkxMGI1LTFiMWEtNGNlMS05MGQ5LWQ3ZGEzNjU3ZjViMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQxOTEyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDQ3ZjU2MDA2MDgxNTZiMTgxNmZiNTVkYjU0NmJjZTk3MWU0YjI5Y2JlNTQ3ZGE0ZjFkYzgwMGQxM2NjOWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BaGbdO6VfxeaGWtRaO8fTWtvXQKkTjWqU1gx-L4aSbY)
> 
> ![Screenshot_2024-05-29-13-59-32-634_com android chrome](https://private-user-images.githubusercontent.com/159836335/334932613-bdc2eaf4-432a-4f3d-99db-ba5da331e6c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMTAyNjYsIm5iZiI6MTcxNzAwOTk2NiwicGF0aCI6Ii8xNTk4MzYzMzUvMzM0OTMyNjEzLWJkYzJlYWY0LTQzMmEtNGYzZC05OWRiLWJhNWRhMzMxZTZjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQxOTEyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDk1NmZiMmMwZmMzYzg4OTNiZjRlNTJlNDdiZDNhZDFjYTQyNjcwMDg2MmM3OTMwZjQ1NDhhOGYxMWFjYWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.om252XG3IjzfVZoyNmMYyVl7ALvbTSxGBoo9jdPMFcQ) and several said that they did not like the interface, but don't worry, the current interface is very good and unique of its kind, they are just not used to it, you leave your mark and make it unique.

sometimes uniqness isnt the requirement but awkward 
Like to the point it eats up the rest of uniqness (Which actually amazes people) that's a difference of opinion though btw you can add the option of choosing interface like not removing the first but changing can be left to the user using a switch button 
Thanks

**Comment by fast4x** [comment]
Hi, thanks for sharing the Reddit link, I didn’t know you were talking about RiMusic. The aspect of the player you want is quite easy to achieve because you have to consider that from the next version you can choose the type of album/artist information, the type of buttons and the type of icons for the like. I’ll tell you that I will add the possibility to invert the buttons with the information so that the user can customize the player even better for how best he likes it.

I add, the popup of lyrics serves to communicate to the user the outcome of lyrics, not everyone can like? No problem I add an option to disable it but by default it will be active.

Thank you for appreciating RiMusic and I hope that you will speak even better to Reddit’s friends.

Last thing, RiMusic was born from ViMusic but like all children it is correct that they take their own path and their own personality.

RiMusic is not ViMusic even if it was born from a fork.

**Comment by BesidesManthan** [comment]
_im just new to this coding shit and definitely I love the app let me give a advise that if you can import innertune or vi tune interface and have a option to switch between player interface that might just change the game currently you are the best and doing this might make you invincible that's what me and my buddies on reddit discussed 
And in all the talk if you felt anyway I disregarded or disrespected your app I'm sorry, no way I'll  disregarded the app I use the most I like use your app 5 hours a day at minimum btw I feel good that a dev had such patience and understood the problem I'll be waiting for the update btw no need to make it asap take your time go through the creative process and release it like in a month or so 
Thanks 
Regards 
A loyal user

**Comment by fast4x** [comment]
Thanks for the tips, maybe you didn’t notice that in the settings you can activate ViMusic mode, remove the top bar and select the left menu. This way you can use the look of ViMusic but with all new RiMusic features.

**Comment by BesidesManthan** [comment]
No I did notice it I am actually talking about the player interface here not the other or explore one

**Comment by fast4x** [comment]
Implemented swappable timeline with controls in player and enable/disable popup message in lyrics.
Available from version 0.6.37

Player skin, will be implemented in other version

**Comment by AquamarineDreams** [comment]
@fast4x What are you cooking with this update?

**Comment by dAtA-TRoN** [comment]
![proxy-image(2).jpg](https://github.com/fast4x/RiMusic/assets/71184627/fb60e93a-aeab-47c8-8f6c-7329ce431e25)

"Yeah, whatcha cookin' with this update? Whatcha cookin'?? Squawk!"
