### ISSUE TITLE
New player lyrics layout

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2094]
### Description

Something like this
![331801272-77a8fe6d-11d5-407c-acba-1220fb89a113](https://github.com/fast4x/RiMusic/assets/45353488/0aa999de-e9b7-42c7-affb-5c8455e2dc88)

### Suggested Solution

Remove this
![IMG_20240530_101117](https://github.com/fast4x/RiMusic/assets/45353488/64a64fd6-634e-49b4-bea7-a8fcc6584bc0)

And add this :

'Lyrics Background'
- none (default)
- coloured (already implemented)
- no album cover (my request)

Please also give an option to increase the font size even more.

Dark theme -> White lyrics
Light theme -> Black lyrics

**Comment by fast4x** [comment]
if i understand, you mean player without thumbnail border and without fullscreen lyrics.

**Comment by fast4x** [comment]
no album cover (my request)...
explain better please 

Text size is just implemented

**Comment by dAtA-TRoN** [comment]
> no album cover (my request)...
> explain better please 
> 
> Text size is just implemented 

![Screenshot_2024-05-30-07-21-30-30_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/45dc9a94-0863-4a2e-a4f9-e5facd6aa0e3)

I think that's what he meant by 'no album cover'.

**Comment by aneesh1122** [comment]
> no album cover (my request)...
> explain better please 
> 
> Text size is just implemented 

When you choose 'no album cover' or 'no thumbnail' then the thumbnail will be removed from the player.

The image I've posted above isn't in full screen. It is your player but I just removed the thumbnail.

![Screenshot_2024-05-30-10-51-12-858_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/52c177f7-4416-4ebf-8699-45f9b658c6d1)

Remove this

**Comment by aneesh1122** [comment]
> > no album cover (my request)...
> > explain better please 
> > 
> > Text size is just implemented 
> 
> ![Screenshot_2024-05-30-07-21-30-30_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/45dc9a94-0863-4a2e-a4f9-e5facd6aa0e3)
> 
> I think that's what he meant by 'no album cover'.

No. That's full screen mode. In the image I posted it's not in full screen mode.

**Comment by dAtA-TRoN** [comment]
Oh, I see. Sounds good to me as an option. As long as it is ensured that the font can be read properly on all background themes.

**Comment by aneesh1122** [comment]
> Oh, I see. Sounds good to me as an option. As long as it is ensured that the font can be read properly on all background themes. White text on a white background doesn't work for example.

If you're using 'blurred cover background' then from the next update there will be a dark shade to improve text visibility so lyrics visibility won't be a problem

**Comment by dAtA-TRoN** [comment]
> > Oh, I see. Sounds good to me as an option. As long as it is ensured that the font can be read properly on all background themes. White text on a white background doesn't work for example.
> 
> If you're using 'blurred cover background' then from the next update there will be a dark shade to improve text visibility so lyrics visibility won't be a problem

Yeah, but there are other options too. The font must work in every theme.

**Comment by aneesh1122** [comment]
> > > Oh, I see. Sounds good to me as an option. As long as it is ensured that the font can be read properly on all background themes. White text on a white background doesn't work for example.
> > 
> > If you're using 'blurred cover background' then from the next update there will be a dark shade to improve text visibility so lyrics visibility won't be a problem
> 
> Yeah, but there are other options too. The font has to work in every theme, not just in the blurred one.

I've never seen any other background options using white. Let this first be implemented then fast4x can fix visibility problems if there are any.

**Comment by fast4x** [comment]
It sound good with player skin mode under development...

**Comment by aneesh1122** [comment]
> It sound good with player skin mode under development...

This is how player lyrics and full screen lyrics can look after you implement it
![GridArt_20240530_112631537.jpg](https://github.com/fast4x/RiMusic/assets/45353488/28704a0e-5e0b-49a2-87fd-3f0e8fea3f3c)

Note : The full lyrics background will be what you choose as your player background. Fluid gradient, blurred cover, background from cover etc

**Comment by dAtA-TRoN** [comment]
> I've never seen any other background options using white.

So? What's with the normal bright theme?

**Comment by aneesh1122** [comment]
> > I've never seen any other background options using white.
> 
> So? What's with the normal bright theme?

That's not bright. That's the 'Light' theme.

Dark theme -> White lyrics
Light theme -> Black lyrics

**Comment by dAtA-TRoN** [comment]
> > > I've never seen any other background options using white.
> > 
> > So? What's with the normal bright theme?
> 
> That's not bright. That's the 'Light' theme.
> 
> Dark theme -> White lyrics
> Light theme -> Black lyrics

Here's the improved English translation:

Bright, light... -Whatever, it seems you've understood me, right? So if the black font also applies to the lyrics in light theme, then everything seems to be hunkydory 👌🏼.
