### ISSUE TITLE
Unable to Return to Player View from Queue by Tapping or Swiping the Minimized Floating Player

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#2095]
### Steps to reproduce the bug

1. Open RiMusic and start playing any media.

2. Switch from Player View to Queue.

3. Attempt to return to the Player View by tapping or swiping the minimized floating player.

### Expected behavior

Tapping or swiping the minimized floating player should bring the user back to the Player View directly.

### Actual behavior

Tapping or swiping the minimized floating player does not return the user to the Player View. Users must use the traditional methods (scrolling to the top or using the arrow button) to exit the Queue.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/71184627/fcff9740-d8c2-4dc6-b28a-aa68e2e2b5bf

### RiMusic version

0.6.36.1

### Android version

Android 13

**Comment by aneesh1122** [comment]
Tap the action bar when you're in queue to go back to the player.

Swipe down the floating player is used for closing the player

No action is assigned to tapping mini player when you're on the queue page.

**Comment by aneesh1122** [comment]
I agree that mini player should do the same thing everywhere so when you're in queue page then tapping mini player should take you back to the player.

Right now that thing is implemented in tapping the action bar.

**Comment by dAtA-TRoN** [comment]
> Tap the action bar when you're in queue to go back to the player.
> 
> Swipe down the floating player is used for closing the player
> 
> No action is assigned to tapping mini player when you're on the queue page.

Oh, I overlooked quite a few things. That's some very good points, thank you. I'll revise this task accordingly.

**Comment by aneesh1122** [comment]
> > Tap the action bar when you're in queue to go back to the player.
> > 
> > Swipe down the floating player is used for closing the player
> > 
> > No action is assigned to tapping mini player when you're on the queue page.
> 
> Oh, I overlooked quite a few things. That's some very good points, thank you. I'll revise this task accordingly.

Here's one more thing. You don't need the arrow button. Just tap on the action bar and it will open the queue page.

**Comment by dAtA-TRoN** [comment]
> Here's one more thing. You don't need the arrow button. Just tap on the action bar and it will open the queue page.

Yes, I would like that too, but it is difficult to explain this to new users. Therefore, I do not see a suitable way to remove the button.

**Comment by aneesh1122** [comment]
> > Here's one more thing. You don't need the arrow button. Just tap on the action bar and it will open the queue page.
> 
> Yes, I would like that too, but it is difficult to explain this to new users. Therefore, I do not see a suitable way to remove the button.

This need not be implemented. It's already implemented.

**Comment by aneesh1122** [comment]
> > This need not be implemented. It's already implemented.
> 
> Watch the video I posted. It doesn't work.

What doesn't work? You can open the queue by just tapping in the action bar.

Did you see this video? https://github.com/fast4x/RiMusic/issues/2048#issuecomment-2132306147

**Comment by dAtA-TRoN** [comment]
> > > This need not be implemented. It's already implemented.
> > 
> > Watch the video I posted. It doesn't work.
> 
> What doesn't work? You can open the queue by just tapping in the action bar.
> 
> Did you see this video? https://github.com/fast4x/RiMusic/issues/2048#issuecomment-2132306147

You can't return from the queue by tapping on the mini player.

**Comment by aneesh1122** [comment]
> > > > This need not be implemented. It's already implemented.
> > > 
> > > Watch the video I posted. It doesn't work.
> > 
> > What doesn't work? You can open the queue by just tapping in the action bar.
> > 
> > Did you see this video? https://github.com/fast4x/RiMusic/issues/2048#issuecomment-2132306147
> 
> You can't return to the player view from the queue by tapping on the mini player.

Are you getting confused?

I told you that you don't need the arrow button in the action bar which you're using to open the queue page because you can open the queue page by just tapping on the action bar.

**Comment by dAtA-TRoN** [comment]
@ fast4x Please allow users to return to the player view by tapping on the mini player in the queue view. Despite other available methods to achieve this, the mini player should behave consistently throughout the app. It would be illogical for it to lose its control options just because something else is displayed in the background. The mini player must remain independent and consistently retain its functionality. Anything else would be confusing.

**Comment by aneesh1122** [comment]
> > Are you getting confused?
> 
> 🖕🏼
> 
> >told you that you don't need the arrow button in the action bar which you're using to open the queue page because you can open the queue page by just tapping on the action bar.
> 
> That's not the point. Even if you could bring up the queue with the volume buttons on your phone, it would be irrelevant.

Fcuk off bit¢H. You clearly lack the basic comprehension ability.

I told you that you can OPEN UP the queue page already by tapping on the action bar since you're using the arrow to do that. Your reply "I would like that too" which implies you thought I'm asking you to put this in your request issue.

Then I told you that it's already implemented and you can tap the action bar to OPEN the queue and you replied "Watch the video I've posted. It doesn't work."

bit¢H I've been telling you that you can OPEN the queue page. O P E N. You got confused thinking that

1) I'm asking you to raise the request of implementing it. No, it's already implemented.
2) you thought I've been telling you about closing the queue page instead I was telling you about how you can O P E N the queue page.

**Comment by aneesh1122** [comment]
> 🖕🏼

You can take this and stick it where the sun don't shine

**Comment by aneesh1122** [comment]
Are you even human? All your messages look like they've been composed using chatGPT.

For bots like you there should be a Human verification captcha before posting to refrain chatGPT bots from posting here.

**Comment by dAtA-TRoN** [comment]
Hey @fast4x, could you please tell this weirdo here to behave? He just doesn't know how to act.

**Comment by aneesh1122** [comment]
Hey @fast4x tell this chatGPT bot to behave. He is the one who started all these by using '🖕🏼'

**Comment by dAtA-TRoN** [comment]
Yesterday, he managed to alienate another user (vishcot) here to the point where they deleted their post #2072.

**Comment by fast4x** [comment]
go to player from mini player make sense when will be implemented separate queue from player...

actually... queue is open from player ... slide down queue show again player ..

**Comment by dAtA-TRoN** [comment]
> go to player from mini player make sense when will be implemented separate queue from player...
> 
> actually... queue is open from player ... slide down queue show again player ..
> 

Hmm, I'm a bit lost with your response. Could you kindly simplify it for me 🙃?

**Comment by fast4x** [comment]
queue is always accessible only form player, so click on mini player inside queue to open player ... make not sense...

**Comment by dAtA-TRoN** [comment]
> queue is always accessible only from player, so click on mini player inside queue to open player ... make not sense...
> 
> 

Ah now I get it. I've noticed that I've instinctively tried to switch back to the player view like this several times before. But no biggie, feel free to wrap up the thread here if you prefer.
