### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [fast4x/RiMusic#2098]
### Steps to reproduce the bug

Check if there are liked songs folder there isnt and no option to like songs and swipe actions are not working too

### Expected behavior

The options should have been present

### Actual behavior

No options are present even the swipe controoa to delete and like it wont work

### Screenshots/Screen recordings

![Screenshot_2024-05-30-22-31-17-511_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/112297620/95bfd15f-af24-4430-91d7-537746866e51)
![Screenshot_2024-05-29-15-45-14-996_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/112297620/b31d9f2a-9313-4681-9cbf-32c5e1ac2111)

### RiMusic version

0.6.36.1

### Android version

10

### Additional information

The issue with this version

**Comment by fast4x** [comment]
I'm sorry but i don't understand.

**Comment by ikanakova** [comment]
> I'm sorry but i don't understand.

I think this is related to #2099 - missing favorite button ❤️

**Comment by aneesh1122** [comment]
1) liked songs are under 'songs' now
2) 'swipe to action' is removed for now. Will be implemented later
3) in the 2nd screenshot you have the 'like' button. In the 1st one you don't. This means you have to choose specific modes to get the 'like' button.
