### ISSUE TITLE
Like Button missing

### ISSUE THREAD

**Issue by Lo3933** [fast4x/RiMusic#2099]
### Steps to reproduce the bug

1. Play a song
2. Maximize player
3. Like button missing

### Expected behavior

Like button should be there

### Actual behavior

Like button is missing

### Screenshots/Screen recordings

![Screenshot_20240530_200152](https://github.com/fast4x/RiMusic/assets/114431129/c39ca62c-e920-4ff7-abc2-05988684e434)

### RiMusic version

v 0.6.36.1

### Android version

Android 14

**Comment by fast4x** [comment]
In new version can be select controls and infos type

**Comment by aneesh1122** [comment]
> In new version can be select controls and infos type

Me waiting for RiMusic's next update

![55-1.jpg](https://github.com/fast4x/RiMusic/assets/45353488/3f46e26e-4e36-4c7e-8569-30f6a0f13274)

When is it dropping? 😅

**Comment by fast4x** [comment]
today
