### ISSUE TITLE
It won't let me import local playlists

### ISSUE THREAD

**Issue by Blabla22bla** [fast4x/RiMusic#2100]
### Steps to reproduce the bug

Went to playlist and hit the square with the arrow in the corner

### Expected behavior

I guess it should let me import it

### Actual behavior

It doesn't let me import it, it shows the file but it doesn't let me click on it

### RiMusic version

0.6.36..1

### Android version

13

**Comment by fast4x** [comment]
i don't understand explain better

**Comment by NikunjKhangwal** [comment]
He's talking about this
![IMG_20240601_080701](https://github.com/fast4x/RiMusic/assets/99175083/e21ae9a2-cb37-4452-8a0b-e220e839c096)

**Comment by fast4x** [comment]
yes it requires csv file with field described in Wiki
