### ISSUE TITLE
download all songs button disappeared

### ISSUE THREAD

**Issue by teacupmaps** [fast4x/RiMusic#2106]
### Steps to reproduce the bug

1. ooen favorites

### Expected behavior

there is a download all button

### Actual behavior

no

### Screenshots/Screen recordings

![Screenshot_20240531-162132](https://github.com/fast4x/RiMusic/assets/158172547/b114e257-080d-4827-88ba-3f0fca977d0a)

### RiMusic version

0.6.36

### Android version

Android 10

**Comment by fast4x** [comment]
is in menu, last icon to right

**Comment by Vishcot** [comment]
![Screenshot_20240601-003750.png](https://github.com/fast4x/RiMusic/assets/136909951/0365190e-921b-4c90-b180-7dad0ab37724)

not showing up! as per your instructions!

**Comment by Vishcot** [comment]
@fast4x 

> ![Screenshot_20240601-003750.png](https://github.com/fast4x/RiMusic/assets/136909951/0365190e-921b-4c90-b180-7dad0ab37724)
> 
> not showing up! as per your instructions!

**Comment by fast4x** [comment]
ok I'll check it

**Comment by fast4x** [comment]
Fixed, available from version 0.6.38
