### ISSUE TITLE
(Player) Blurred Cover Background and Like Button

### ISSUE THREAD

**Issue by Syilo555** [fast4x/RiMusic#2107]
### Description

I like the blurred cover background but if a song cover has a lot of white or grey like in that screenshot, the song title and the artist name are kinda hard to see.

There are two like buttons if you can see in that screenshot. (Controls type: Essential, Interface in use: Rimusic)

![Screenshot_20240531-214353](https://github.com/fast4x/RiMusic/assets/167092738/49217f63-0170-41ad-8c7a-5b6d905a533f)

### Suggested Solution

Maybe add some shadows on the song title and the artist name (only for blurred cover background) or darken the background (i think this shoud be an option).

**Comment by fast4x** [comment]
try latest version, change background with  hold tap in player background
