### ISSUE TITLE
[Andoid Auto] - No album cover displayed in the player

### ISSUE THREAD

**Issue by Tos26** [fast4x/RiMusic#2108]
### Steps to reproduce the bug

Listen album on Android Auto

### Expected behavior

Cover album displayed on Android Auto.

### Actual behavior

There is no album cover displayed when connected to Android Auto (Version 11.9.641824-release)
No problem with ViMusic before the migration to RiMusic.

### RiMusic version

0.6.36

### Android version

Android 11

**Comment by fast4x** [comment]
Hi look this

https://github.com/fast4x/RiMusic/wiki/FAQs#why-does-it-no-longer-show-album-art-on-the-lockscreen-since-android-11

**Comment by Tos26** [comment]
Hello,

Maybe my explanation wasn't clear enough or I didn't understand your answer

I spoke about the album cover on the screen of my car with Android Auto. I have no issue on my phone.
I think there is a regression compared to ViMusic because I meet this behavior only with RiMusic.

**Comment by Tos26** [comment]
@fast4x : Any idea ?

**Comment by fast4x** [comment]
Much old your version, update to the latest

**Comment by Tos26** [comment]
Hi,

Tested with the last version from FDROID (0.6.44) and all the versions released since the 0.6.36: Always the same behavior, no cover displayed on the screen of the car:
![IMG20240801175116](https://github.com/user-attachments/assets/1ac76831-d434-447f-98d6-d3594fa4ee83)

Info: Android auto on my phone version 12.3.642624 which is the lastest on playstore

**Comment by hrmtn** [comment]
I have the same issue.

**Comment by Tos26** [comment]
It works from the version 0.6.48. Thanks for the job on this great app !!!
