### ISSUE TITLE
Play Button Themes

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#211]
### Description

It would be nice to have a option in the UI section to change the shape of the play button
That way the ViMusic Style can have the ViMusic Shape, RiMusic can have the cube shape

Also i liked the rectangle shape and it could be possible to add the android 13 weird circle shape

### Suggested Solution

Add an option to change the shape of the play button

**Comment by fast4x** [comment]
☺️

**Comment by OrangeZXZ** [comment]
> Can you give me an example of the circular shape of android 13?

![ic4UkWXiYSuo6cwT3LVovS.jpg](https://github.com/fast4x/RiMusic/assets/104271365/dd92da42-27a1-4c9d-9de9-054a51c13e06)

**Comment by fast4x** [comment]
Ahhhhhhhh ok

**Comment by fast4x** [comment]
Implemented Android 13 shape on play/pause button, with and without rotate effect
Available from version 0.6.13

**Comment by fast4x** [comment]
Added Play button types Square, Circular ribbed, Rectangular...
Available from version 0.6.13
