### ISSUE TITLE
Set language for translation

### ISSUE THREAD

**Issue by dreamAviator** [fast4x/RiMusic#2112]
### Description

It would be cool if you could select, to which language the lyrics get translated, and not only using the app language

### Suggested Solution

When you tap translate, select a language
Or in the settings a seperate option for the translation language

**Comment by AquamarineDreams** [comment]
Or hold the "translate button" to change the language

**Comment by dreamAviator** [comment]
Yeah good idea
And maybe if you just tap on it, it will use either the last selected or the default translation language

**Comment by Loughty** [comment]
I was about to make a issue for this, I don't realize that only have in english the lyrics translation until a friend (that I recommend RiMusic) ask me how to select the spanish language!

**Comment by fast4x** [comment]
Implemented, available from version 0.6.42

**Comment by dreamAviator** [comment]
Nice thank you
