### ISSUE TITLE
Transparent navigation bar, missing like button and dark shade

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2113]
### Description

Thanks for the update fast4x. Blur control works perfectly. Also thanks for implementing 'open queue directly from mini player'

Unfortunately there are still some minor things I want to request to be improved

### Suggested Solution

1) transparent navigation bar.

Please make it completely transparent. Make it as if it doesn't exist at all.
It's completely transparent when no buttons are selected in action bar. Please make it transparent like this everytime transparent action bar is selected even after options are selected.

![Screenshot_2024-05-31-22-54-25-699_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/aa9e5320-ea9c-4f93-828c-7c69c04e62c3)
How it's right now

![Screenshot_2024-05-31-22-54-45-241_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/9d762bed-60f8-4240-9d6d-06b24f7c80e4)
I want it to be like this always (plus options)

2) Like button is missing with essential info + modern controls

I suggest making like present everytime beside the title/artist in all the control modes. Maybe replace like in essential controls with radio or some other option
![IMG_20240531_230118](https://github.com/fast4x/RiMusic/assets/45353488/69927e2b-c5cc-4370-9065-b0f221ebab18)

3) dark shade

Dark shade doesn't seem to be working.
![Screenshot_2024-05-31-22-55-06-957_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/45353488/ed278b42-3cc6-4d66-80c8-bcfefd51e1ae)

4) Lyrics size
You said that the lyrics size is increased but I'm still getting the same size

**Comment by ikanakova** [comment]
>     2. Like button is missing with essential info + modern controls
> 
> 
> I suggest making like present everytime beside the title/artist in all the control modes. Maybe replace like in essential controls with radio or some other option ![IMG_20240531_230118](https://private-user-images.githubusercontent.com/45353488/335679839-69927e2b-c5cc-4370-9065-b0f221ebab18.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODEzMjgsIm5iZiI6MTcxNzE4MTAyOCwicGF0aCI6Ii80NTM1MzQ4OC8zMzU2Nzk4MzktNjk5MjdlMmItYzVjYy00MzcwLTkwNjUtYjBmMjIxZWJhYjE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE4NDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMWNlY2MxMTk5NWQ4NzA3ZWEwYTQzZTAwOWE5MTdhYmE1MDMyMzkzY2JlODRiODM4NTc0MjMxYjgyZWQ1MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-At4dstFTMKvV2spZOXJ5p01QQcujt50NmrZF9K4KSw)

👎

**Comment by aneesh1122** [comment]
> >     2. Like button is missing with essential info + modern controls
> > 
> > 
> > I suggest making like present everytime beside the title/artist in all the control modes. Maybe replace like in essential controls with radio or some other option ![IMG_20240531_230118](https://private-user-images.githubusercontent.com/45353488/335679839-69927e2b-c5cc-4370-9065-b0f221ebab18.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODEzMjgsIm5iZiI6MTcxNzE4MTAyOCwicGF0aCI6Ii80NTM1MzQ4OC8zMzU2Nzk4MzktNjk5MjdlMmItYzVjYy00MzcwLTkwNjUtYjBmMjIxZWJhYjE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE4NDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMWNlY2MxMTk5NWQ4NzA3ZWEwYTQzZTAwOWE5MTdhYmE1MDMyMzkzY2JlODRiODM4NTc0MjMxYjgyZWQ1MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-At4dstFTMKvV2spZOXJ5p01QQcujt50NmrZF9K4KSw)
> 
> 👎

Suggest the alternatives then? 'Like' button should be available in all the modes

**Comment by ikanakova** [comment]
> > > ```
> > > 2. Like button is missing with essential info + modern controls
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I suggest making like present everytime beside the title/artist in all the control modes. Maybe replace like in essential controls with radio or some other option ![IMG_20240531_230118](https://private-user-images.githubusercontent.com/45353488/335679839-69927e2b-c5cc-4370-9065-b0f221ebab18.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODEzMjgsIm5iZiI6MTcxNzE4MTAyOCwicGF0aCI6Ii80NTM1MzQ4OC8zMzU2Nzk4MzktNjk5MjdlMmItYzVjYy00MzcwLTkwNjUtYjBmMjIxZWJhYjE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE4NDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMWNlY2MxMTk5NWQ4NzA3ZWEwYTQzZTAwOWE5MTdhYmE1MDMyMzkzY2JlODRiODM4NTc0MjMxYjgyZWQ1MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-At4dstFTMKvV2spZOXJ5p01QQcujt50NmrZF9K4KSw)
> > 
> > 
> > 👎
> 
> Suggest the alternatives then? 'Like' button should be available in all the modes

You wrote about essential controls. In essential controls, the like button should stay where it is and only be displayed when the user wants it.

In other modes it can be in the toolbar next to the download button.

**Comment by aneesh1122** [comment]
> You wrote about essential controls. In essential controls, the like button should stay where it is and only be displayed when the user wants it.

And what about those guys who use essential title/album with modern controls?

I asked you for the solutions/suggestions.

If fast4x adds 'like' button beside the title/album then people will create new issues about multiple like buttons.

So what do you think would be the best solution?

**Comment by ikanakova** [comment]
> Naah. 'Like' button is an important part of every music player. It should be in the main player.

Maybe according to you, but I don't really consider the Like button as an important part of the player - to me it's Play/Pause, Previous, Next.

**Comment by ikanakova** [comment]
> > Maybe according to you, but I don't really consider the Like button as an important part of the player - to me it's Play/Pause, Previous, Next
> 
> Well, you don't but the majority of the people do. That's why all the music players have a 'like' button.
> 
> Anyways, you're not the only guy using this app so the app should be adjusted according to the majority of the people.
> 
> You also said you don't use the like button then why does it matter to you where it is placed?
> 
> Those who use the like button will understand why I'm asking for this.

Majority is mostly you, though, isn't it? You're forcing your opinions here, as if RiMusic was created mainly for you, but that's not true!

And I didn't say I don't use it, so don't use those argumentative fouls on me like you used on @dAtA-TRoN in https://github.com/fast4x/RiMusic/issues/1980#issuecomment-2129351825

**Comment by dAtA-TRoN** [comment]
> > > Maybe according to you, but I don't really consider the Like button as an important part of the player - to me it's Play/Pause, Previous, Next
> > 
> > Well, you don't but the majority of the people do. That's why all the music players have a 'like' button.
> > 
> > Anyways, you're not the only guy using this app so the app should be adjusted according to the majority of the people.
> > 
> > You also said you don't use the like button then why does it matter to you where it is placed?
> > 
> > Those who use the like button will understand why I'm asking for this.
> 
> Majority is mostly you, though, isn't it? You're forcing your opinions here, as if RiMusic was created mainly for you, but that's not true!
> 
> And I didn't say I don't use it, so don't use those argumentative fouls on me like you used on @dAtA-TRoN in https://github.com/fast4x/RiMusic/issues/1980#issuecomment-2129351825

I already told you, the guy doesn't know how to behave. It's funny how he's pissing off one person after another. First me, then Vishcot, and now you.
He's a problematic hothead and a bigot.

**Comment by ikanakova** [comment]
> What matters is what fast4x think about it. If you can't add anything to the suggestion then maybe you can waste your time in some other issue? You can certainly be more helpful than reacting with '👎'

Yes, you can only participate in RiMusic by suggesting something and when others don't like it, you elevate yourself above them and consider their opinion irrelevant. Really funny that you're attacking people here who have contributed 1000 times more to the development of RiMusic than you...

**Comment by ikanakova** [comment]
> > > > Maybe according to you, but I don't really consider the Like button as an important part of the player - to me it's Play/Pause, Previous, Next
> > > 
> > > 
> > > Well, you don't but the majority of the people do. That's why all the music players have a 'like' button.
> > > Anyways, you're not the only guy using this app so the app should be adjusted according to the majority of the people.
> > > You also said you don't use the like button then why does it matter to you where it is placed?
> > > Those who use the like button will understand why I'm asking for this.
> > 
> > 
> > Majority is mostly you, though, isn't it? You're forcing your opinions here, as if RiMusic was created mainly for you, but that's not true!
> > And I didn't say I don't use it, so don't use those argumentative fouls on me like you used on @dAtA-TRoN in [#1980 (comment)](https://github.com/fast4x/RiMusic/issues/1980#issuecomment-2129351825)
> 
> @ikanakova As I already told, the guy doesn't know how to behave. It's funny how he's pissing off one person after another. First me, then Vishcot, and now you. He's a problematic hothead and a bigot. He is also a control freak and tries to micromanage all decisions.

And I try to be a calm and patient person and get along with everybody...

**Comment by aneesh1122** [comment]
> > > > Maybe according to you, but I don't really consider the Like button as an important part of the player - to me it's Play/Pause, Previous, Next
> > > 
> > > Well, you don't but the majority of the people do. That's why all the music players have a 'like' button.
> > > 
> > > Anyways, you're not the only guy using this app so the app should be adjusted according to the majority of the people.
> > > 
> > > You also said you don't use the like button then why does it matter to you where it is placed?
> > > 
> > > Those who use the like button will understand why I'm asking for this.
> > 
> > Majority is mostly you, though, isn't it? You're forcing your opinions here, as if RiMusic was created mainly for you, but that's not true!
> > 
> > And I didn't say I don't use it, so don't use those argumentative fouls on me like you used on @dAtA-TRoN in https://github.com/fast4x/RiMusic/issues/1980#issuecomment-2129351825
> 
> @ikanakova As I already told, the guy doesn't know how to behave. It's funny how he's pissing off one person after another. First me, then Vishcot, and now you. He's a problematic hothead and a bigot. He is also a control freak and tries to micromanage all decisions.

C'mon now you coward. You blocked me. Behave like how blocked people do. Stay away from matters which concern me. For starters, stay away from this issue.

And where the hell did I try to micromanager anything? My job is only to suggest changes. I'm not the developer. Fast4x decides everything. If he wishes he could just close any created issue and I'll accept it.

**Comment by aneesh1122** [comment]
> you elevate yourself above them and consider their opinion irrelevant.

You considered my opinion irrelevant by replying with '👎'

And I elevated myself? I just asked for something which is missing. You're here talking about how like is not important and it can be sidelined in the action bar.

If fast4x thinks the best way to add 'like' button is to add it in the action bar then I'll accept it. I respect his opinions.

If fast4x says that the 'like' button will never be a part of 'Modern controls + Essential title' then I'll stop asking about it.

**Comment by ikanakova** [comment]
> > you elevate yourself above them and consider their opinion irrelevant.
> 
> You considered my opinion irrelevant by replying with '👎'
> 
> And I elevated myself? I just asked for something which is missing. You're here talking about how like is not important and it can be sidelined in the action bar.
> 
> If fast4x thinks the best way to add 'like' button is to add it in the action bar then I'll accept it. I respect his opinions.
> 
> If fast4x says that the 'like' button will never be a part of 'Modern controls + Essential title' then I'll stop asking about it.

It's probably not worth arguing with you. I was just expressing my opinion that I don't like your suggestion. I didn't say your opinions were irrelevant like you said about mine.

I trust that fast4x will not regard you as the supreme expert on everything you apparently consider yourself to be and will, as always, listen to the opinions of others.

**Comment by aneesh1122** [comment]
> I was just expressing my opinion that I don't like your suggestion.

You have a funny way of doing that. Maybe try this template the next time you give a 'suggestion'

I don't think this is a good idea because "state your reason". Maybe you can "state an alternative".

> I trust that fast4x will not regard you as the supreme expert on everything you apparently consider yourself to be and will, as always, listen to the opinions of others.

And I trust fast4x will not regard ANYONE as the supreme expert. Not even someone who *contributed* to this project before. I mean, all of us are contributing to this project with our ideas. You don't hear me praising myself.

I have immense respect for fast4x and if he thinks the 'like' button shouldn't be added then I'll agree with him and close this matter.
