### ISSUE TITLE
Go to top button position is changing position of search button too

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#2116]
### Steps to reproduce the bug

Move go to top button position, observe search button

### Expected behavior

Both of the buttons should stay where left off

### Actual behavior

Buttons position get changed

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/99175083/5890af46-1e7f-44ff-b2d0-24d7f2a8e5fc

### RiMusic version

0.6.37

### Android version

Android 12

**Comment by dAtA-TRoN** [comment]
@ikanakova Just so you know: I just wrote fast4x an email about this.

**Comment by ikanakova** [comment]
> @ikanakova Just so you know: I just wrote fast4x an email about this. I'm writing this to you here because I was blocked in the other thread.

I'm almost sorry I had this argument with him, but I just hate it when someone forces their opinions.

**Comment by dAtA-TRoN** [comment]
> I'm almost sorry I had this argument with him, but I just hate it when someone forces their opinions.

@ikanakova Everything's fine, I completely understand. That guy always does this. Either you play along, or he gets rude and obnoxious. But let's not dwell on this any further. fast4x should be aware of it now. Let's see what happens.

**Comment by dAtA-TRoN** [comment]
@ikanakova Let's delete this conversation. Because others don't know what this is about and might find it strange.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.38
