### ISSUE TITLE
No funciona agregar a playlist 

### ISSUE THREAD

**Issue by Isav08** [fast4x/RiMusic#2119]
### Steps to reproduce the bug

1-Ingresar a una lista de canciones
2-presionar botón de agregar a playlist

### Expected behavior

Que aparezcan la opciones correspondientes 

### Actual behavior

No funciona

### Screenshots/Screen recordings

![IMG_20240531_131301](https://github.com/fast4x/RiMusic/assets/163780688/24d3e9d7-43ea-4cbf-bb0b-b5f200874dbb)
![Screenshot_20240531-131137](https://github.com/fast4x/RiMusic/assets/163780688/2524254c-b875-4d42-a2b7-5fb07481d8e8)

### RiMusic version

0.6.37

### Android version

Android 7

**Comment by fast4x** [comment]
I can’t reproduce the problem
