### ISSUE TITLE
Thank you Dev 

### ISSUE THREAD

**Issue by BesidesManthan** [fast4x/RiMusic#2120]
### Description

As I asked for the customizations the dev was so nice to take the idea and give the output in like 3 days even aunder it thanks dev I respect your work and you I'll recommend the app to more and more people 

### Suggested Solution

🙏

**Comment by fast4x** [comment]
Thank you for your appreciation.

**Comment by BesidesManthan** [comment]
Now I can proudly say I use the best open source music streaming service out there with the best customizations 
and sorry to ask but can we use a feature to adopt player interface from other forms like innertune ? Btw that's not my opinion it's a reddit comment asking for it 
And yes I love the app

**Comment by fast4x** [comment]
You mean like this Innertune player?
![Screenshot_2024-05-31-20-55-51-301_com.zionhuang.music.jpg](https://github.com/fast4x/RiMusic/assets/1484476/25192c2a-bd37-49d4-b01a-a1d0ed7ad96e)

Actually from settings can change info artist/album, controls buttons, icons on action bar, you can customize much aspect much similar.

I can add specific features that actually RiMusic don't have...

Player skins are under development, so in the future release can customize almost all in the player.

Do not forget that you can use the theme with fully customizable colors.

**Comment by BesidesManthan** [comment]
Yess I mean like the screenshot actually the friend means it I'm now satisfied but ya we can't satisfy everyone but I'm happy that you are actually working on it too and gave us what we wanted best of luck for the future and if you need any kind of interface ui related looks based problems feel free to contact me I'll be there to help but yes I currently don't know how to code but I can make the app look more aesthetic/Pleasing or nice to use around

**Comment by fast4x** [comment]
Thanks, you can share your ideas whenever you want. Other collaborators can’t program but their ideas are more valuable, so it’s not a problem but a value.
