### ISSUE TITLE
Add an option,to see what song you are playing

### ISSUE THREAD

**Issue by NightFly88** [fast4x/RiMusic#2121]
### Description

Add an option,to see what song you are playing,see youtube music,you will then see a light gray color 

Thanks
![Screenshot_20240531_211001_YouTube Music](https://github.com/fast4x/RiMusic/assets/163666747/32d893bb-89e7-430d-aa82-23b318a3d116)

### Suggested Solution

would be great

**Comment by dAtA-TRoN** [comment]
I like this!

**Comment by fast4x** [comment]
Added locate now playing in home songs, available from version 0.6.38

**Comment by aneesh1122** [comment]
> Added locate now playing in home songs, available from version 0.6.38

Thanks for implementing this but I think he didn't mean this 😅

Like if you open an album or search a song from results and you play it, that song will be highlighted by a dark bar.
