### ISSUE TITLE
Fading songs issue

### ISSUE THREAD

**Issue by debarjun2004** [fast4x/RiMusic#2122]
### Steps to reproduce the bug

I enabled the fade songs option and set it on 3 seconds. 

### Expected behavior

The songs are not fading as it should be. 

### Actual behavior

what happens is the next song's first 3 seconds are being broken, sounds like a radio or smthn. 

### RiMusic version

0.6.37

### Android version

Android 13

**Comment by fast4x** [comment]
Ok, fade will be removed
