### ISSUE TITLE
When trying to import a playlist, the application closes

### ISSUE THREAD

**Issue by albertcorbett** [fast4x/RiMusic#2123]
### Steps to reproduce the bug

I exported a playlist that I created through the application, and used it as a base to create the others. However, when I try to import, the application closes and nothing imports. How do I import my playlists from YouTube?

### Expected behavior

Allow songs to be imported into an existing playlist or a new one

### Actual behavior

The app just closes and it doesn't matter

### RiMusic version

0.6.37

### Android version

12

### Additional information

Xiaomi Redmi Note 9S Global
Miui 14.0.3 Global

**Comment by fast4x** [comment]
It work, bug not reproduced.
File type is csv, look at this https://github.com/fast4x/RiMusic/wiki/FAQs#what-is-the-csv-file-structure-for-importing-a-playlist-in-library

**Comment by albertcorbett** [comment]
I did it this way, as follows in the attached example. But the problem is that when I import the PlayList, the application closes!

[2024DanilowMT.csv](https://github.com/user-attachments/files/15522270/2024DanilowMT.csv)

In the video, the first time I selected a playlist that already exists in the "Rock" application and it didn't import the songs either. The second time, I imported a playlist that doesn't exist "RTOEhrenfeld" and it didn't import either and the application closes when I choose the CSV file.


https://github.com/fast4x/RiMusic/assets/6977357/f33331bf-24bf-4d3f-81c5-00838222e1d8

**Comment by fast4x** [comment]
File it's ok, remove the first comma for each row... 
Comma is field separator and not use like initial field...

example correct field1,field2,
example wrong ,field1,field2

**Comment by albertcorbett** [comment]
The first "," is because the first "PlaylistBrowseId" field is blank. But ok, I removed the comma and the problem persists. Here's the error that appeared when I insisted.

[2024DanilowMT-2.csv](https://github.com/user-attachments/files/15522344/2024DanilowMT-2.csv)

![Screenshot_2024-06-01-12-37-34-200_com miui bugreport](https://github.com/fast4x/RiMusic/assets/6977357/6775edaa-a352-41ad-937e-ef7beb618824)

**Comment by fast4x** [comment]
excuse me you are right

send me log with crash with original file

**Comment by albertcorbett** [comment]
Ah yes, okay, I clicked send after taking the printout
