### ISSUE TITLE
Reproducir alguna cancion directamente de un álbum

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#2126]
### Steps to reproduce the bug

1. Dirígete a albumes.
2. Selecciona cualquier canción para reproducir.
3. Abre el apartado de este para ver la reproducción en curso.

### Expected behavior

1. Dirígete a álbumes, selecciona cualquier canción y verifica tu reproducción en curso.

### Actual behavior

1 Me dirijo a albumes, selecciono cualquier canción de mi agrado, abri a interfaz de reproducción en curso pero la carátula desaparece y me lanza a inicio.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/170132242/b278d3b8-a113-4fdd-bb1d-3475f1bdc164

### Logs

N/A

### RiMusic version

0.6.37

### Android version

Android 14 

### Additional information

N/A

**Comment by fast4x** [comment]
Use the play next works and the song will be added as next
