### ISSUE TITLE
Brasilian portuguese translation is wrong

### ISSUE THREAD

**Issue by AquamarineDreams** [fast4x/RiMusic#2127]
### Steps to reproduce the bug

1. Go to settings
2. Player settings
3. Open player background color

### Expected behavior

.

### Actual behavior

Translation is wrong

### Screenshots/Screen recordings

![IMG_20240531_191822](https://github.com/fast4x/RiMusic/assets/140275860/e5d60489-37d0-4738-a825-fd850b2746f4)

### RiMusic version

0.6.37 - Latest

### Android version

Android 14 - HyperOS

**Comment by AquamarineDreams** [comment]
Why aren't the menus translated with Google Translate, as the lyrics and some other UI elements. This way, the app could be translated to more languages, and the translations would be faster.

**Comment by AquamarineDreams** [comment]
*edited the image to keep consistency

**Comment by fast4x** [comment]
Please go to crowdin and correct it

**Comment by AquamarineDreams** [comment]
@fast4x My browser dies every time i try to create a pull request. Is it ok if I send the file (strings.xml) here?

**Comment by AquamarineDreams** [comment]
After 30 flipin minutes GitHub says that my pull request failed because I'm not a collaborator 👍

I'll send the file here because I'm out of options

 What was edited:

1. Translated some parts that needed translation;
2. Fixed wrong translations;
3. Edited some translated parts for parity reasons;
4. Edited some translated parts so it would work better in Brasilian Portuguese;

[values-pt-rBR.zip](https://github.com/user-attachments/files/15520211/values-pt-rBR.zip)

**Comment by fast4x** [comment]
ok for now, translation is manageable in Crowdin without private merge request. 
Link  to Crowdin https://crowdin.com/project/rimusic/invite?h=73f0e6b64be1c64a8aebd467d286cf851925330

**Comment by AquamarineDreams** [comment]
> ok for now, translation is manageable in Crowdin without private merge request. Link to Crowdin https://crowdin.com/project/rimusic/invite?h=73f0e6b64be1c64a8aebd467d286cf851925330

I think that I was able to upload the file successfully, but some of my changes weren't applied.

E.g. In these strings it's supposed to be "meses" instead of "mês". I'm 100% sure that I changed that.

![IMG_20240601_071548](https://github.com/fast4x/RiMusic/assets/140275860/a78eb521-604e-4e58-87af-a0964d0f486c)

**Comment by AquamarineDreams** [comment]
Did I send the file correctly?

**Comment by ikanakova** [comment]
> Did I send the file correctly?

Some new translations of Brasilian portuguese from Crowdin have been transferred, see #2109

If you mean the file you attached here, I can see it, but please use Crowdin, because uploading files to GitHub adds unnecessary fast4x work. It's easy to log into Crowdin with a GitHub account and edit translations there like the rest of us.

**Comment by fast4x** [comment]
> > Did I send the file correctly?
> 
> Some new translations of Brasilian portuguese from Crowdin have been transferred, see #2109
> 
> If you mean the file you attached here, I can see it, but please use Crowdin, because uploading files to GitHub adds unnecessary fast4x work. It's easy to log into Crowdin with a GitHub account and edit translations there like the rest of us.

Confirm, today other merge have been merged today from Crowdin in this language.
I agree, Crowdin is a first and unique way to translation... and fix in all languages.

**Comment by ikanakova** [comment]
> > > Did I send the file correctly?
> > 
> > 
> > Some new translations of Brasilian portuguese from Crowdin have been transferred, see #2109
> > If you mean the file you attached here, I can see it, but please use Crowdin, because uploading files to GitHub adds unnecessary fast4x work. It's easy to log into Crowdin with a GitHub account and edit translations there like the rest of us.
> 
> Confirm, today other merge have been merged today from Crowdin in this language. I agree, Crowdin is a first and unique way to translation... and fix in all languages.

And it doesn't matter if the translations on Crowdin are Approved or not, because everything translated is automatically pushed to Pull Requests on GitHub regardless of whether it's Approved or not.

**Comment by AquamarineDreams** [comment]
I sent the file on crowdin too. Or at least I thought I did. I tried to overwrite the crowdin file with my file. As I said, apparently, some changes were applied, others didn't.

> I think that I was able to upload the file successfully, but some of my changes weren't applied.
>
>E.g. In these strings it's supposed to be "meses" instead of "mês". I'm 100% sure that I changed that.
>
>![IMG_20240601_071548](https://github.com/fast4x/RiMusic/assets/140275860/a78eb521-604e-4e58-87af-a0964d0f486c)

**Comment by AquamarineDreams** [comment]
I honestly have no idea on how to upload my changes without changing every string individually. Again..

**Comment by ikanakova** [comment]
> I sent the file on crowdin too. Or at least I thought I did. I tried to overwrite the crowdin file with my file. As I said, apparently, some changes were applied, others didn't.

What do you mean?

No files are being overwritten on Crowdin. On Crowdin, you edit the text in the box:
![Screenshot 2024-06-01 at 15-37-51 strings xml - RiMusic - Crowdin translation](https://github.com/fast4x/RiMusic/assets/38765251/a9d6bc9b-762e-4a39-a44d-58ba6380403a)

**Comment by AquamarineDreams** [comment]
Well, I already have the strings.xml file with all my changes, and I didn't wanted to rewrite everything, so I tried uploading the fixed file.

![IMG_20240601_104448](https://github.com/fast4x/RiMusic/assets/140275860/aa238b0d-6654-4e2d-9f6c-1e179b6d5794)

I honestly don't know if this does what I thought it would do. Probably I'll need to edit each string individually.

**Comment by fast4x** [comment]
Not upload anything use only available text

**Comment by ikanakova** [comment]
> Well, I already have the strings.xml file with all my changes, and I didn't wanted to rewrite everything, so I tried uploading the fixed file.
> 
> ![IMG_20240601_104448](https://private-user-images.githubusercontent.com/140275860/335805229-aa238b0d-6654-4e2d-9f6c-1e179b6d5794.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTAwMjIsIm5iZiI6MTcxNzI0OTcyMiwicGF0aCI6Ii8xNDAyNzU4NjAvMzM1ODA1MjI5LWFhMjM4YjBkLTY2NTQtNGUyZC05ZjZjLTFlMTc5YjZkNTc5NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMzQ4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmQ2NGIxYzllNzM5OTNjMzI1ZTExNzMxZWMwZTJkOTE5MWU2MGQwZDZmNjcwZDM5NDMwZmRhZjRhYjQ4OTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Py0RqfWH8v29Dig1wO3ItAWwhbGGqYIlUbZCFCCU8ok)
> 
> I honestly don't know if this does what I thought it would do. Probably I'll need to edit each string individually.

I guess so, I don't know how fast4x has it set up - if others can upload strings.xml.

@fast4x I think maybe it's a bug in Crowdin: https://crowdin.com/project/rimusic/activity-stream?lang=63&translation_id=2882 Because "3 Meses" is suggested several times, but it's still "3 mês".

**Comment by ikanakova** [comment]
@AquamarineDreams I can see your suggestions already:
<img width="483" alt="Snímek obrazovky 2024-06-01 161806" src="https://github.com/fast4x/RiMusic/assets/38765251/cd15098e-73ed-4423-82c7-f6618ed01da2">

**Comment by AquamarineDreams** [comment]
Oh, that must be why the changes weren't applied. You need to approve they 😅

**Comment by ikanakova** [comment]
> Oh, that must be why the changes weren't applied. You need to approve they 😅

Better get fast4x to approve it. I only do proofreading in my native language, although I could do it in English too...

**Comment by AquamarineDreams** [comment]
So, in my opinion, there's no point in trying to convince him. At the end of the day it's his app, and he decides whether he wants to implement it or not, I just made a suggestion.¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯
Of course I would like if he implements it though

**Comment by fast4x** [comment]
i don't understand, what's would be implemented? all translations are approved.

**Comment by AquamarineDreams** [comment]
First of all, thanks 👍 
![IMG_20240603_170745](https://github.com/fast4x/RiMusic/assets/140275860/22ffbc87-a7c8-42ce-b8cf-30ce8b74f526)


> i don't understand, what's would be implemented? all translations are approved.

I was referring of approving my changes to the translation, since, apparently, they need to be manually approved

<img alt="Snímek obrazovky 2024-06-01 161806" width="483" src="https://private-user-images.githubusercontent.com/38765251/335807175-cd15098e-73ed-4423-82c7-f6618ed01da2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NDUyMzQsIm5iZiI6MTcxNzQ0NDkzNCwicGF0aCI6Ii8zODc2NTI1MS8zMzU4MDcxNzUtY2QxNTA5OGUtNzNlZC00NDIzLTgyYzctZjY2MThlZDAxZGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDIwMDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMTM1NGY3ODFhZDlmNDBiMjY5ZDY1MmRlNzU4NDdlMDM1Yjg4NDZjMGFiNThmNjUzMjg2NThkNTkyOWNlYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-pDkWgtpZgRSsTcmVd2r4NzuTK_tQIOD-LBxt6uehgQ">

**Comment by fast4x** [comment]
There were translations that haven’t been approved yet, and I’ve approved them now. excuse me.

**Comment by AquamarineDreams** [comment]
No worries bro
