### ISSUE TITLE
[Issue]:  player in landscape mode problem 

### ISSUE THREAD

**Issue by IvanMaksimovic77** [fast4x/RiMusic#2128]
### Description

Hi, it would be nice to change cover, buttons  and timeline size and position,  for example i would like to have bigger timeline and smaller cover

### Suggested Solution

Cover, timeline and buttons size and position (small, medium, big / left , right, centered)

**Comment by fast4x** [comment]
Thumbnail can set size from settings, other will be a feature in player skin

**Comment by IvanMaksimovic77** [comment]
> Thumbnail can set size from settings, other will be a feature in player skin

It does not change thumbnail size in landscape mod

**Comment by fast4x** [comment]
it's fixed in landscape

**Comment by IvanMaksimovic77** [comment]
![Screenshot_20240601-184436](https://github.com/fast4x/RiMusic/assets/161308507/f717bd9e-7014-402b-9935-3dfe2b0c6774)

**Comment by IvanMaksimovic77** [comment]
![Screenshot_20240601-184458](https://github.com/fast4x/RiMusic/assets/161308507/a18d64f5-8cc4-4385-bf48-db10765f1b07)

**Comment by IvanMaksimovic77** [comment]
Even the next song button is not showing caused by large thumbnail

**Comment by fast4x** [comment]
change title oh this ticket in issue player in landscape mode

**Comment by IvanMaksimovic77** [comment]
Ok, thank you

**Comment by IvanMaksimovic77** [comment]
The issue persist, tested on newest, 0.6.38

**Comment by IvanMaksimovic77** [comment]
Only in landscape

**Comment by fast4x** [comment]
ok I'll check it

**Comment by aneesh1122** [comment]
Fixed

Expanded
![Screenshot_2024-07-02-18-56-06-985_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/45353488/e8aa2328-3df4-45d0-ab50-77ddf5d0e712)

Medium
![Screenshot_2024-07-02-18-56-28-451_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/45353488/1ec9fbe3-97b8-4e52-a270-6170bde89f98)
