### ISSUE TITLE
Acción para reparar carátulas.

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#2130]
### Description

Deberían agregar una opción cuya función sea reparar carátulas de álbumes y canciones, tiene muchos fallos está app y por lo tanto está opción sería muy fundamental para así facilitar que el usuario no tenga dificultades.

### Suggested Solution

Agreguen está funcionalidad en ajustes para que el usuario descargue carátulas si se presentan problemas (Qué es muy a menudo)

### Alternatives

N/A

### Additional Context

N/A

**Comment by fast4x** [comment]
There is a bug on the covers that will be fixed
