### ISSUE TITLE
Broken Easter Egg

### ISSUE THREAD

**Issue by Th3-C0der** [fast4x/RiMusic#2131]
### Steps to reproduce the bug

Open Easter Egg By Clicking The RiMusic Logo Multiple Time, Then Start The Game And Start Playing 

### Expected behavior

It Should Work Like Normal Pacman Game

### Actual behavior

We Can Control The Pacman But It Collects Some Random Coins The Ghost Also Moves I Random Direction And You Can Die Without Even Getting Contact With Them. 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/152851285/7acb58eb-42f2-4363-b35b-ccd78ad0a067

### RiMusic version

0.6.37

### Android version

Android 14

### Additional information

Developers You Can Fix The Bug With The Game Or Try Some Other Better & Easier To Implement & Bug Free Easter Egg/Game. Overall the Easter egg idea was amazing i like it, keep it up 👍🏻✨.

**Comment by dAtA-TRoN** [comment]
Yes, unfortunately, I also have to report that the Easter egg is a bit buggy. It didn't load properly the first time for me, and I ended up with a black screen. I tried again and was then surprised with Pac-Man. Brilliant 😂! The warm-up with the text boxes before that is nice as well. A small suggestion for improvement: I would refer to 'clicking' as 'tapping' instead. However, the controls aren't working quite right. I think you'll need to take another look at that. But it's great that you've included it. A very charming little secret 😁.

**Comment by Th3-C0der** [comment]
What About A Whole Classic Pokemon Game :)
Like Pokemon Red/Blue/Yellow 😁

**Comment by dAtA-TRoN** [comment]
> What About A Whole Classic Pokemon Game :)\nLike Pokemon Red/Blue/Yellow 😁

Because copyright. Pacman is to my knowledge copyright free.

**Comment by dAtA-TRoN** [comment]
> tetris also?

No, I guess Tetris is fine because there are hundreds of versions of it out there.

**Comment by Th3-C0der** [comment]
What Is They Added Multiple Classic Retro Games 😂😁
Games Like Tetris, Pac Man, Mario, Sonic, Etc.

**Comment by dAtA-TRoN** [comment]
> All fine,that was a simple question...no request

I understood it that way as well. I was just sharing my general opinion on the matter. But even if it had been a request, that would have been perfectly fine, of course.
