### ISSUE TITLE
[Feature]: add 'like' in action bar

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2133]
### Description

I use 'Essential title/artist + modern controls' and I'm missing like button.

### Suggested Solution

Please add the 'like' button in action bar.

I would have preferred to have it in player but if there's no other way then please add it in navigation bar.

**Comment by fast4x** [comment]
it's duplicate action bar is limited

**Comment by aneesh1122** [comment]
> it's duplicate action bar is limited 

Please add 'like' button anywhere on the player screen from where it is easily accessible.

Or maybe limit the selections to 9. If I already selected 9 options in the action bar then I won't be able to select more options.

**Comment by fast4x** [comment]
No sorry are too many
