### ISSUE TITLE
[Feature]: Transparent action bar

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2134]
### Description

The newly implemented transparent action bar is not truly transparent.

![Screenshot_2024-06-01-11-09-48-100_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/fda35b1b-2caf-4094-9fc4-ef2d26c41276)

Please make it completely transparent.

### Suggested Solution

This is how action bar looks like when there are no options selected.

![Screenshot_2024-06-01-11-11-01-581_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/45353488/8dab0b77-a3ff-4aad-a99f-42b249cdc1d9)

No bar present.

So, please make transparent action bar look like this with options selected too

**Comment by fast4x** [comment]
for now isn't possible
