### ISSUE TITLE
[Feature]: Dark shade for blur cover background

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2135]
### Description

The blur control is working perfectly. Thanks @bbyeen and @fast4x . The dark shade doesn't seem to work though.
![335680143-ed278b42-3cc6-4d66-80c8-bcfefd51e1ae](https://github.com/fast4x/RiMusic/assets/45353488/e6fbd23d-14b5-4be8-ac5e-0cff2b24943b)

### Suggested Solution

Please take [this](https://music.youtube.com/watch?v=aYtQqvutB_k) song as a reference and add dark shade just enough amount to make things visible.

**Comment by veloal** [comment]
like this #1901? no?

with the blur control has improved, but it is still not appreciated correctly, title, singer,...

**Comment by aneesh1122** [comment]
> like this #1901? no?
> 
> with the blur control has improved, but it is still not appreciated correctly, title, singer,... 

Yeah

Dark theme needs dark shade and light theme needs light shade

**Comment by fast4x** [comment]
The player will not be improved more, it is not a priority its appearance, sorry

**Comment by aneesh1122** [comment]
> The player will not be improved more, it is not a priority its appearance, sorry

Okay
