### ISSUE TITLE
Option or ability for HQ audio downloads

### ISSUE THREAD

**Issue by TheGiggleNiggle** [fast4x/RiMusic#2136]
### Description

Hey dev(s). I've been absolutely loving the app so far and highly appreciate the fact that you are continuing to give us new updates every week.
But I've been wondering there was a possibility if you could make the downloads more HQ like 320kbps instead of the more inconsistent download quality 

### Suggested Solution

So basically in the settings give the user for low quality downloads or high quality audio downloads

**Comment by fast4x** [comment]
I'll check it if possible

**Comment by dAtA-TRoN** [comment]
Unfortunately, achieving higher audio quality seems unlikely as it's typically locked behind a paywall. RiMusic, to my knowledge, solely utilizes publicly accessible APIs. So let's appreciate the fact that this service is available to us at no cost, even if it doesn't offer high quality. Let's focus on the bright side, shall we 🙂?

**Comment by fast4x** [comment]
Confirmed, quality is maximum possible
