### ISSUE TITLE
all songs gone

### ISSUE THREAD

**Issue by gituser23234235234887** [fast4x/RiMusic#2137]
### Steps to reproduce the bug

update to 0.6.36 on fdroid

### Expected behavior

songs appear in (second) tab, "songs"

### Actual behavior

they dont appear

### RiMusic version

0.6.36 fdroid

### Android version

14

### Additional information

I updated to 0.6.36 on fdroid. all my songs were gone. the "quick pics" (first) tab showed me songs, but all other tabs showed empty. granted I didnt heart or download any songs, so I can only confirm second tab "songs" had no songs. I downgraded to 0.6.35 and imported my backup and the songs are back.

**Comment by fast4x** [comment]
Try install latest f-droid and restore backup
