### ISSUE TITLE
[Feature]: ability to move song to top of queue

### ISSUE THREAD

**Issue by gituser23234235234887** [fast4x/RiMusic#2138]
### Description

I think the ability to move a song to top of queue is good.

### Suggested Solution

ability to move songs to top of queue by holding on them or swiping on them.

### Additional Context

imagine you shuffle all thousands of your songs, and you like a few hundred of them. as you skim through your queue, you have to drag the songs you like to top of queue, and then swiping back down trying to remember how far down the queue you had gone. now if you had the ability to just hold on the song in the queue to move it to the top, placing it after current song, then it would all become hassle free and annoyance free.

**Comment by dAtA-TRoN** [comment]
Can't you just hit the 'play next' button in the context menu?
