### ISSUE TITLE
Fix the Layout of Show next song queue and Player action bar

### ISSUE THREAD

**Issue by Jetliarm** [fast4x/RiMusic#2139]
### Description

make it like minimal looking like grid style 
![received_1544217586517877](https://github.com/fast4x/RiMusic/assets/171421185/fc678cf3-f4f4-42d6-9105-d8e798b52427)
![received_3830457010570884](https://github.com/fast4x/RiMusic/assets/171421185/05bc1892-6050-4f37-8b80-7dc6eece8e65)

### Suggested Solution

"Add padding to the 'player action bar' icons and center them. Also, I want the layout of the 'show next song queue' box-type icon to be floating."

### Alternatives

Fix it

### Additional Context

thank you

**Comment by fast4x** [comment]
Action bar in player it's a full width bar
