### ISSUE TITLE
App Crashes 

### ISSUE THREAD

**Issue by Jetliarm** [fast4x/RiMusic#2143]
### Steps to reproduce the bug

1. I open the app.
2. I choose the song.
3. It crashes when it's in offline mode.

### Expected behavior

it automatically close the app

### Actual behavior

.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/171421185/a0860ab2-625f-429f-9e6e-75ef241721c9

### RiMusic version

0.6.37

### Android version

android 11

**Comment by fast4x** [comment]
In offline mode there is a bug with background from cover... change it in settings..

**Comment by fast4x** [comment]
Please in version 0.6.38, go to miscellaneous settings, enable debug, restart app, repeat crash action, after go again to settings, click on copy crash log and paste here

**Comment by fast4x** [comment]
Please in version 0.6.38, go to miscellaneous settings, enable debug, restart app, repeat crash action, after go again to settings, click on copy crash log and paste here
