### ISSUE TITLE
I'm back online so if you need any desing I'm there fast4x. Thanks for  the work you do for us. 

### ISSUE THREAD

**Issue by jaki444** [fast4x/RiMusic#2145]
### Description

Hi fast4x, thank you for all the work you are doing. I am freeing up my time. If you have ideas but don't know how to implement them I can help you out graphically. In a few days there will also be some proposals from me for features that are also new compared to other music apps. I am also tweaking some of the desing even though it is already more than fine now. So if you need anything graphically just ask I would be glad to. Anyway thank you very much dev you are the best.

### Suggested Solution

.

**Comment by fast4x** [comment]
Thanks jaki444, I am very focused on developing the many requests. I like that you have the pleasure of improving the app, so put your ideas into practice and then we’ll all talk about it as we have done so far. Thanks in advance
