### ISSUE TITLE
delay in loading the cover

### ISSUE THREAD

**Issue by veloal** [fast4x/RiMusic#2148]
### Steps to reproduce the bug

see screen recording. 

### Expected behavior

no delay. in previous versions this was not the case (at least I don't remember) 

### Actual behavior

delay in loading song, album, playlist cover artwork. does not always happen. 

### Screenshots/Screen recordings

example 1
https://github.com/fast4x/RiMusic/assets/170187968/78eca85d-48a6-4587-bd2a-b929bd385c8b
example 2
https://github.com/fast4x/RiMusic/assets/170187968/1d3ea127-a6ff-4b18-9d23-ccb13f810905

### RiMusic version

0.6.37

### Android version

9

**Comment by fast4x** [comment]
isn't a delay but loading improved...
