### ISSUE TITLE
[Feature]: Bluetooth FF & RW Support (Fast forward & Rewind)

### ISSUE THREAD

**Issue by Rodd15** [fast4x/RiMusic#2151]
### Description

Need Bluetooth FF & RW Support (Fast forward & Rewind). It can be useful while driving to skip to the good part of the song or to skip the beginning intro of a podcast or a documentary without touching the phone.

### Suggested Solution

Adding FF & RW like the Ymusic app did for youtube.

**Comment by fast4x** [comment]
you can connect phone in BT and control it from car steering command

**Comment by Rodd15** [comment]
> you can connect phone in BT and control it from car steering command

After reading your reply, I went back to test but it's still not working for me. I switched to Ymusic app and it works there with 5 seconds jump. I checked the settings page if I missing an option or something but it doesn't seem like that's the case :/

Everything else with my car Bluetooth works with RiMusic though. it's only the FF and RW are the only thing missing.

**Comment by fast4x** [comment]
Your car and Bluetooth system brand?

**Comment by Rodd15** [comment]
Toyota Camry 2018 with stock (Pioneer system) I also saw Broadcom under software info but I'm not %100 sure if the Bluetooth chipset made by them.

Using the "Bluetooth Devices info" App I got the following info...

Bluetooth Type: Classic - BR/EDR

Profiles Supported:
 OPP
 A2DP - SNK
 AVRCP
 Personal Area Networking(PAN) - 
 PANU 
 HFP

**Comment by fast4x** [comment]
Hello, try version 0.6.43 if work with your Bluetooth..

**Comment by fast4x** [comment]
Implemented podcasts in search page, available from version 0.6.44

**Comment by Rodd15** [comment]
Thanks for adding podcasts support! I'm looking forward to it when it becomes avaible!

As for version 0.6.43 it's still unfortunately doesn't support Bluetooth FF or RW for my car.

is there some anyway I could assist with this issue, like uploading any debugging logs or dig for more related info?

after testing a few other apps on Fdroid. I found "Pipepipe" and "Vidya Music" supports bluetooth FF and RW.  So being open source code, could they be useful to see what's done different on their end?

Thanks a ton for having a look at this!

**Comment by fast4x** [comment]
Ah ok I'll check in this app.
