### ISSUE TITLE
Playback error without network

### ISSUE THREAD

**Issue by chatinteligence** [fast4x/RiMusic#2154]
### Steps to reproduce the bug

The error occurs when disconnected from the network and without SIM data, giving a failure to play the downloaded music.

https://github.com/fast4x/RiMusic/assets/147566193/84875d68-ef30-4bd7-a4d6-c17d6128ca2c

### Expected behavior

The error occurs when disconnected from the network and without SIM data, giving a failure to play the downloaded music.

### Actual behavior

The error occurs when disconnected from the network and without SIM data, giving a failure to play the downloaded music.

### RiMusic version

6.37

### Android version

Android 14

**Comment by fast4x** [comment]
When offline change background type without cover... actually there is a bug in offline mode anche background based to cover.

**Comment by fast4x** [comment]
Improved, available from version 0.6.38
