### ISSUE TITLE
App crashes when maximizing player for a specific album by a specific artist

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#2155]
### Steps to reproduce the bug

1. Play any song from the album '**Privat Life**' by the artist '**Tamper**'.

2. When the song is running observe the Mini-Player at the bottom; the album cover is not displayed.

3. Attempt to maximize the player to switch to the Player-View.

### Expected behavior

• The app should smoothly transition to the Player-View without crashing. The album cover should be displayed in the Mini-Player, just like it is for other albums.

### Actual behavior

• The app crashes and closes completely when attempting to maximize the player for this specific album by Tamper. The album cover is also not displayed in the Mini-Player.

### RiMusic version

Android 13

### Android version

0.6.37

### Additional information

All other albums by Temper are running flawless.

**Comment by fast4x** [comment]
Add link please for artist and album

**Comment by dAtA-TRoN** [comment]
> Add link please for artist and album

There you go:
https://music.youtube.com/playlist?list=OLAK5uy_la0ZIvMgC_SxBBOPX-xmDLABmEWk7I7L8

**Comment by fast4x** [comment]
![Screenshot_2024-06-02-16-56-36-794_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/baf82581-f3d5-46c2-9c83-009430867769)

![Screenshot_2024-06-02-16-57-09-372_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/abea28e9-29b7-4c7c-8660-b0c7094cfa85)

**Comment by fast4x** [comment]
no crash

**Comment by dAtA-TRoN** [comment]
> no crash

https://github.com/fast4x/RiMusic/assets/71184627/2a068c25-ff05-4d4c-b51e-69d530d4f211

Damn, but I kind of suspected that 🙃.

**Comment by sebbekm** [comment]
I got the same bug. Try these songs:
Teamworx - Let it Sound
Kryder - Let's Begin
Will K - Guamo

I does not crash when just searching for the songs and playing them. You have to go via the artist page, then singles.

https://github.com/fast4x/RiMusic/assets/99768781/0c5c0138-da23-428f-8f29-41dd85e4962b

**Comment by dAtA-TRoN** [comment]
Is it possible to implement a functionality that initiates a refresh to fix problems like these? For example, deleting all album art, temporary files, caches, resetting settings, and then automatically restoring them. I understand that many of these actions can be done manually. I'm just wondering if there are things that only a 'refresh' function could accomplish. I mean there must be some reason why some people can see certain albums while others cannot.

**Comment by fast4x** [comment]
It’s possible of course, but I think that the availability of some content is limited upstream for language reasons. They are looking for a possible solution by adding the language of the contents according to the geographical area from which you connect. It might help, but I’m not sure.

**Comment by dAtA-TRoN** [comment]
> It’s possible of course, but I think that the availability of some content is limited upstream for language reasons. They are looking for a possible solution by adding the language of the contents according to the geographical area from which you connect. It might help, but I’m not sure.

Sure, here's the translation in a charming tone:

---

Sorry, I must have misspoken. I didn't mean visibility in general. I was referring specifically to those issues when albums don't load properly in RiMusic. You know, the "shaking hands" problems or whatever the correct term is. You know what I mean: you can see the album, but when you tap on it, it looks like it's loading, but nothing appears. Unfortunately, I've experienced this a few times in the relatively short period I've been using RiMusic. Often, these issues disappear after an update, only to pop up again somewhere else. I think it might be related to some temporary file remnants or something along those lines (you're the expert, not me 😃). That's actually what my question was about. If there were a general refresh function to fix these issues, that would be fantastic.

**Comment by fast4x** [comment]
ok

**Comment by fast4x** [comment]
Please in version 0.6.38, go to miscellaneous settings, enable debug, restart app, repeat crash action, after go again to settings, click on copy crash log and paste here
