### ISSUE TITLE
Global search doesn't work

### ISSUE THREAD

**Issue by expoal123** [fast4x/RiMusic#2156]
### Steps to reproduce the bug

I was searching for new songs and no result for all my searches. Even artist when I click artist no songs no albums no results

### Expected behavior

Usually showing 

### Actual behavior

No result on all searches online external not internal storage but online search

### Screenshots/Screen recordings

![Screenshot_2024-06-02-13-00-41-379_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/29067787/bd319329-b24a-43c6-abf7-bc8a24a6332c)

### RiMusic version

0.6.37

### Android version

Android 13

### Additional information

The search global not saved or cached but online search always shows no result , it's been 3 updates since than and no fixes. No albums no songs .

**Comment by fast4x** [comment]
![Screenshot_2024-06-02-17-18-11-121_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/de7bee78-0cf9-4fc0-ab24-59b1da986148)

**Comment by fast4x** [comment]
your geographic area?

**Comment by expoal123** [comment]
albania

**Comment by expoal123** [comment]
I see but mine still doesn't work?
