### ISSUE TITLE
App language does not change

### ISSUE THREAD

**Issue by duhow** [fast4x/RiMusic#2157]
### Steps to reproduce the bug

System language is Spanish.
App language is set to English.

But still app language appears in Spanish.

### Expected behavior

Change language to English.

### Actual behavior

![Screenshot_20240602_134852](https://github.com/fast4x/RiMusic/assets/1145001/83f12119-3810-418f-848b-72ad32d0e420)

### RiMusic version

v0.6.36

### Android version

14

**Comment by fast4x** [comment]
try change another language and after set your language again

**Comment by duhow** [comment]
That works as a workaround. 👍🏻
