### ISSUE TITLE
Forced stop while clearing cache from the recent apps menu

### ISSUE THREAD

**Issue by Official-Mlx** [fast4x/RiMusic#2158]
### Steps to reproduce the bug

![Screenshot_2024-06-02-18-45-38-962_com miui home](https://github.com/fast4x/RiMusic/assets/74877307/bbdc1ab4-f635-457c-ba54-ed28070786be)

Sometimes, after closing other apps, which does not lead to the current app being closed, the app is forcibly stopped. This action also occasionally happens unintentionally.

### Expected behavior

‍

### Actual behavior

‍

### RiMusic version

last version

### Android version

Android 10 Note 8 Pro

**Comment by fast4x** [comment]
disable close from settings

**Comment by fast4x** [comment]
Option is in app by first release...
