### ISSUE TITLE
Sois lo mejor!

### ISSUE THREAD

**Issue by Baviera10** [fast4x/RiMusic#2159]
### Description

Enhorabuena,  gracias por vuestro trabajo, esta app se ha convertido en mi app musical de referencia, Gracias!!!

### Suggested Solution

Yo la veo estupenda!

### Alternatives

Me doy de baja de spotfy

### Additional Context

Si necesitáis un betatester mas, estoy a vuestra disposicion

**Comment by fast4x** [comment]
Thanks a lot ❤️

**Comment by fast4x** [comment]
Whenever you want you can contribute with your ideas

**Comment by Baviera10** [comment]
Sure!
