### ISSUE TITLE
[Feature]: Add the ability to add whole albums to playlists

### ISSUE THREAD

**Issue by aaylnx** [fast4x/RiMusic#216]
### Description

Thank you very much for RiMusic! As far as I can tell (please correct me if I am wrong!), there is no way to add whole albums to playlists. Only individual songs can be added. It would be very nice to be able to add whole albums all at once rather than having to add every song indivdually.

### Suggested Solution

Have an icon (maybe a + icon?) which allows the use to add the album to a playlist.

**Comment by fast4x** [comment]
Hi, thank you for the positive feedback on RiMusic.
If i understand correctly, you want to add all the songs of an album in a playlist, not the album as a single song.

Correct?

**Comment by aaylnx** [comment]
Right. I want to be able to add all the songs on an album. Is there a way to do that right now? I can only see how to add them individually.

**Comment by aaylnx** [comment]
Awesome! Thank you.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.13

**Comment by aaylnx** [comment]
Thank you. The new feature works great!

**Comment by fast4x** [comment]
Thanks for feedback
