### ISSUE TITLE
Typing in the search field, Bible library search does not work

### ISSUE THREAD

**Issue by Beshardis** [fast4x/RiMusic#2161]
### Steps to reproduce the bug

I go into the input field in the search bar, where I'm going to find something. When the keyboard appears, I start typing, but when clicking on letters (symbols, I poke everything in a row), so nothing happens in the search field at all. Please pay attention and fix it somehow

### Expected behavior

ㅤ

### Actual behavior

ㅤ

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/171149808/64449fcb-c71e-45d7-9599-6da70b16e4a1

### Logs

ㅤ

### RiMusic version

0.6.37

### Android version

12

### Additional information

tablet: Huawei Matepad 11(2021) HarmonyOs 3.0
![Screenshot_20240602_222346_com android settings](https://github.com/fast4x/RiMusic/assets/171149808/8e77f654-aac9-45a1-8143-70c44a59fc1a)

**Comment by fast4x** [comment]
Not reproduced, check your device keyboard

**Comment by Beshardis** [comment]
There is no point in checking, since it worked fine on older versions of rimusic, and so does the rest of the system!

**Comment by fast4x** [comment]
search it's not modified... will be improved in the future

**Comment by Beshardis** [comment]
Although it's not very convenient, but you can still insert text, so take your time, do everything slowly!
I'm sorry, but something can be done about it, for some reason the navigation buttons overlap part of the lower screen and I can't use the functions.
![Screenshot_20240603_195442_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/171149808/32df0c84-d2c5-4780-83af-793ca4d8eea8)

**Comment by Beshardis** [comment]
Большое Спасибо!
