### ISSUE TITLE
Bluetooth Skip Not Working

### ISSUE THREAD

**Issue by jeffreyd00** [fast4x/RiMusic#2163]
### Steps to reproduce the bug

My Android 14 Píxel 6a is connected to my car stereo via Bluetooth. I have steering wheel controls in my car. Other apps, in fact all other audio apps I've used let me skip songs using the steering wheel control buttons. These however don't work with this app.

### Expected behavior

Connect to cars Bluetooth 
Press play or next on steering wheel 
Skips to next song

### Actual behavior

Nothing happens 

### RiMusic version

6.x.x

### Android version

Android 14

**Comment by fast4x** [comment]
Play/pause work?

**Comment by fast4x** [comment]
Bluetooth system in your car how years old is?

**Comment by jeffreyd00** [comment]
Hiya,
I don't have a play button on the steering wheel that being said the play
button on the head unit doesn't work either. I should say this... I tried
it the other day and the steering controls worked but only 1 time. They
never worked before or since.

I'm going to try resetting my Bluetooth connection to the car stereo and
will get back to you.

**Comment by fast4x** [comment]
Play/Pause is mute button in steering controls

**Comment by jeffreyd00** [comment]
I reset the bluetooth connection on my phone/car and the steering controls
still don't work. Is there anything you would like me to try to do to
diagnose the problem?

**Comment by fast4x** [comment]
Unfortunately no, as soon as I can deepen the problem

**Comment by jeffreyd00** [comment]
okay
