### ISSUE TITLE
Make your own internal equalizer (volume control)

### ISSUE THREAD

**Issue by Beshardis** [fast4x/RiMusic#2164]
### Description

The fact is that I don't have any equalizer on my device anymore, but to adjust the volume from the maximum to the minimum itself, as for example in innertune:
![Screenshot_20240603_005740_com zionhuang music](https://github.com/fast4x/RiMusic/assets/171149808/9a5491fb-b1aa-4831-8f2e-7bd59fcac20d)

### Suggested Solution

✦

### Alternatives

Since I stream or record from the screen, I would really like to have at least a volume slider from 0 to 100 and at the same time it only affected the application itself and also when recording the system sound, the recording application was also quieter or louder.

### Additional Context

I really adore your application and use it every day on my tablet and I would like people with large screens to also pay a little more attention to updates.
thanks

**Comment by fast4x** [comment]
Ok, i'll add volume control

**Comment by dAtA-TRoN** [comment]
Please make it optional.

**Comment by fast4x** [comment]
> Please make it optional.

it's not optional because it's same volume controls... not equalizer...

**Comment by Beshardis** [comment]
I would also like it to be possible to use a button in the form of a lock (or in the application settings) to prohibit recording system sound, where when recording any sound from rimusic it was not heard on the record (as in spotify), but when unblocked it is possible. 
Personally, for me, as a streamer, I would like to listen to any tracks with copyright, but at the same time so that it would not be heard by the audience. Unfortunately, there is no audio mixer on android. And vice versa, where it is necessary to show the songs, I do a quick unlock and everything becomes audible on the stream or recording!

This is really suitable for those people who want to record something, but so that the recording does not show how they listen to their favorite music!

**Comment by fast4x** [comment]
I’m sorry but I don’t think to implement it, there are many other things with more priority.

**Comment by Beshardis** [comment]
Of course! Don't worry, do everything moderately and relaxed!

**Comment by dAtA-TRoN** [comment]
> it's not optional because it's same volume controls... not equalizer...

I just don't like digital volume controls that you could accidentally press, that's all.

**Comment by fast4x** [comment]
can't, it's hidden ,😂

**Comment by dAtA-TRoN** [comment]
> can't, it's hidden ,😂

![proxy-image(2).gif](https://github.com/fast4x/RiMusic/assets/71184627/d85a9ee7-34a4-46ab-b467-bacacb2c9cef)

**Comment by fast4x** [comment]
Implemented app volume control in player by long tap play pause button, available from version 0.6.39

**Comment by fast4x** [comment]
Implemented also device volume...
