### ISSUE TITLE
Shuffle Button

### ISSUE THREAD

**Issue by isjustlucas** [fast4x/RiMusic#2166]
### Description

A button could be implemented to have random playback instead of having a button that plays directly, like on Spotify. When I want to listen randomly but click on a song I want, it remove the random queue.

### Suggested Solution

A button could be implemented to have random playback instead of having a button that plays directly, like on Spotify.

**Comment by Abilomp** [comment]
Exactly i also need it

**Comment by fast4x** [comment]
It's just implemented in Android Auto, but not because it's available on Spotify.
RiMusic isn't Spotify... :)

**Comment by ikanakova** [comment]
Besides, this option is already implemented (if I understand exactly what you want - I don't have Spotify and don't know it...) when you open the queue and press the Shuffle button.

And for the rest of us, the Shuffle button should remain with the function as it has always been - to play a random queue directly.
