### ISSUE TITLE
Just Wanna Be A Part Of Development :)

### ISSUE THREAD

**Issue by Th3-C0der** [fast4x/RiMusic#2168]
### Description

Hey, fast4x
I Have So Much Free Time Lately, & I Also Wanna Learn About Building Apps, & I Also Want To Help In Fixing And Implementing New Features In RiMusic , But I Don't Know How And Where To Start, So Can You Provide Will The Tools & Softwares I Will Need, So I Can Also Start Contributing To RiMusic.
& Thanks For Keeping RiMusic Up To Date With Updates Each Week 

### Suggested Solution

.

**Comment by fast4x** [comment]
Hello, you can download Android Studio, forkare the reporitory of RiMusic and decide what you want to develop among all the tickets present. First of all, however, you must have a good preparation in the development of Kotlin Compose applications. If you don’t think you have it, start studying and testing with the RiMusic code.

https://developer.android.com/studio
https://developer.android.com/develop/ui/compose

**Comment by Th3-C0der** [comment]
Thank You 😄
