### ISSUE TITLE
Compartir listas de reproducción

### ISSUE THREAD

**Issue by Baviera10** [fast4x/RiMusic#2169]
### Description

Incluir compartir en la exportación (WhatsApp, Telegram, mail, etc).

### Suggested Solution

Al pulsar exportar, que aparezca también.la opción de compartir

### Alternatives

No hay

### Additional Context

Compartir es usual y ahora hay que exportar al móvil y desde allí compartirlo.

**Comment by fast4x** [comment]
You can share your queue with export, look this

https://github.com/fast4x/RiMusic/assets/1484476/3be3b2ee-99d8-4110-85ff-6ad406ec8a69

**Comment by Baviera10** [comment]
Si, mi propuesta es una mejora para facilitar compartir listas de
reproducción más fácilmente que ahora

**Comment by fast4x** [comment]
How would you like it to work?

**Comment by Baviera10** [comment]
Glad to hear it! Thanks!!
