### ISSUE TITLE
[Feature]: Added a new height drop down menu i the app 

### ISSUE THREAD

**Issue by ankitkumar1302** [fast4x/RiMusic#2171]
### Description

# Request to Replace Dropdown Menu in Jetpack Compose

## Description

I would like to propose an enhancement to the project by replacing the existing dropdown menu with a new animated height dropdown menu implemented using a different library in Jetpack Compose. The current dropdown menu has some usability issues and aesthetic limitations that can be improved with a more modern and user-friendly design.

## Current Dropdown Menu

<p align="center">
  <img src="https://github.com/fast4x/RiMusic/assets/95230112/e2b881ea-88f3-4fc6-bfec-e1dfa3df988c" alt="Proposed Dropdown Menu" width="300">
</p>
[Describe or include a screenshot of the current dropdown menu]

## Proposed Dropdown Menu

Here is the new dropdown menu design that I propose:
<p align="center">
  <img src="https://github.com/saket/cascade/blob/trunk/demo.gif?raw=true" alt="Proposed Dropdown Menu" width="300">
</p>

### Key Improvements

1. **Improved Usability**: The new design offers better usability with clearer options and a more intuitive interface.
2. **Modern Aesthetics**: The updated look aligns better with modern UI/UX standards, enhancing the overall visual appeal.
3. **Smooth Animations**: The new dropdown uses animated height transitions for a smoother and more engaging user experience.
4. **Responsive Design**: The new dropdown is fully responsive and works seamlessly across different devices and screen sizes.

## Implementation Details

- **Jetpack Compose Updates**: Update the Jetpack Compose code to incorporate the new dropdown menu design and functionality.
- **Library Integration**: Use [cascade] https://github.com/saket/cascade for implementing the animated height dropdown menu.
- **Code Changes**:
  - Update the composable functions to include the new dropdown menu.
  - Ensure proper state management for the dropdown.
- **Testing**: Ensure thorough testing on various devices and Android versions to verify compatibility and performance.

### Suggested Solution

Using the library you can achieve this:-
https://github.com/saket/cascade

**Comment by dAtA-TRoN** [comment]
But why does it need to be so fancy and animated? It has very few options and no submenus. I just don't see the point.

**Comment by ankitkumar1302** [comment]
Yes you are right but in the future there can be more features and the menu is looking some way odd in this UI So it can be make the main screen more attractive

**Comment by dAtA-TRoN** [comment]
> Yes you are right but in the future there can be more features and the menu is looking some way odd in this UI So it can be make the main screen more attractive

Who knows? You might be right, and there could be more options in the window in the future. However, that makes your suggestion a bit premature for now, as nothing would change immediately. Perhaps it’s best to wait and make changes to the window when it truly makes sense. What do you think?

**Comment by ankitkumar1302** [comment]
Yes, It can feel premature and nothing changes immediately but it's a good idea that can be implemented simply or in a minimalistic way after that, the things can be added to the menu

**Comment by dAtA-TRoN** [comment]
> Yes, It can feel premature and nothing changes immediately but it's a good idea that can be implemented simply or in a minimalistic way after that, the things can be added to the menu

Without appropriate use cases, a lot of work could be in vain. Therefore, it makes sense to only implement something like this when there is a reasonable need, in my opinion.

**Comment by ankitkumar1302** [comment]
Ya, that can be but if something is pre-created like that, it can be beneficial not the whole drop menu is to be implemented but some UI design can be changed so It looks and feels good.

**Comment by Vishcot** [comment]
in my opinion we need this kind of a drop down menu for these options which feels cluttered! 

![Screenshot_20240607-215232.png](https://github.com/fast4x/RiMusic/assets/136909951/1a89fa5a-bc29-49e0-8c85-e168a91e3152)

**Comment by fast4x** [comment]
> Ya, that can be but if something is pre-created like that, it can be beneficial not the whole drop menu is to be implemented but some UI design can be changed so It looks and feels good.

This is slightly improved display of icons

**Comment by ankitkumar1302** [comment]
@fast4x yes it will 
So what you think? Can work on?

**Comment by fast4x** [comment]
For now not possible, in the future.
