### ISSUE TITLE
The "now playing" bar is covering up the search button

### ISSUE THREAD

**Issue by minislel** [fast4x/RiMusic#2172]
### Steps to reproduce the bug

Play something, go to overview on an artist page/quick picks

### Expected behavior

The search button should be raised

### Actual behavior

It's covered up

### Screenshots/Screen recordings

![Screenshot_20240603-162942_RiMusic](https://github.com/fast4x/RiMusic/assets/43825985/a1a8fff8-dacd-4cab-8fc1-2116fd6eb534)

### RiMusic version

0.6.37

### Android version

Android 13, oneplus 8t

**Comment by fast4x** [comment]
Tap and hold icon, move it to your preferites position
