### ISSUE TITLE
Can't click on the song because it's covered by the title

### ISSUE THREAD

**Issue by Grevellia123** [fast4x/RiMusic#2174]
### Steps to reproduce the bug

Click on the song and scroll down

### Expected behavior

You can click on the bottom song
![IMG_20240603_222829](https://github.com/fast4x/RiMusic/assets/134467260/bf3e73d2-d4d7-419e-b0b8-d3a4d2c835cb)

### Actual behavior

The bottom song can be clicked if it is not covered by the title 

### Screenshots/Screen recordings

Uploading VID_20240603_222625.mp4…

### RiMusic version

0.6.37

### Android version

Android 12

### Additional information

Poco m3

**Comment by fast4x** [comment]
Fixed, available from version 0.6.38
