### ISSUE TITLE
App crashes when opening player while playing any song from certain album

### ISSUE THREAD

**Issue by Juggalage** [fast4x/RiMusic#2181]
### Steps to reproduce the bug

Go to the album "Treason" by D.O.A
Start playing any song
Open player

### Expected behavior

Player opens like normal to favorite, skip song, etc.

### Actual behavior

App crashes

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/32726906/eba0a536-91aa-48f8-babd-63044968cdd7

### RiMusic version

0.6.37

### Android version

Android 14

**Comment by dAtA-TRoN** [comment]
...sounds suspiciously like #2255 🤔!?

**Comment by dAtA-TRoN** [comment]
It appears that this error is not easily reproducible. However, it indicates that there is an unusual issue in RiMusic that leads to these kinds of errors.

**Comment by fast4x** [comment]
I’m developing the internal log function, so you can activate it, use the app playing the error and sending me the log... all without having to install other apps to have the log.

**Comment by dAtA-TRoN** [comment]
> I’m developing the internal log function, so you can activate it, use the app playing the error and sending me the log... all without having to install other apps to have the log.

So you talking about...
![proxy-image(2).gif](https://github.com/fast4x/RiMusic/assets/71184627/e15fae41-ca1d-4910-bc9f-dd550c9b0a5b)

**Comment by id8547854** [comment]
Crash app if tap on player.
Android 11.

Link video ( big size )
[https://s3.filebin.net/filebin/f33932c4933ad1c12b2ad598dc3ec373ead51403d89b1f690481b82b03cd05f7/220dd95253907f3985ae485252892daf8897fe6628563585bec5ca76792fd787?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=7pMj6hGeoKewqmMQILjm%2F20240606%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240606T224036Z&X-Amz-Expires=60&X-Amz-SignedHeaders=host&response-cache-control=max-age%3D60&response-content-disposition=filename%3D%22record_06.07.2024_05.09.mp4%22&response-content-type=video%2Fmp4&X-Amz-Signature=723881387e671a298d80a14cac861c3e4c6fe001085e7d22b63027c94c4e39ab](url)

**Comment by fast4x** [comment]
Please in version 0.6.38, go to miscellaneous settings, enable debug, restart app, repeat crash action, after go again to settings, click on copy crash log and paste here
