### ISSUE TITLE
[Feature]:  Download feature

### ISSUE THREAD

**Issue by Lucky390163** [fast4x/RiMusic#2182]
### Description

A download feature for songs

### Suggested Solution

Please add a feature to download songs in Sd card or phone path in mp3 quality.Thanks.

### Alternatives

YT-dl and Seal Currently support download feature

### Additional Context

No

**Comment by JeePopuwu** [comment]
short answer: no.  
long answer: not planned

**Comment by ikanakova** [comment]
#1314 #1510 #1665 etc.

**Comment by Lucky390163** [comment]
Why Just why

**Comment by aneesh1122** [comment]
> short answer: no.  
> long answer: not planned

Your long answer has the same amount of  alphabets as "long answer" 😂😂

**Comment by ikanakova** [comment]
> Why Just why

I wrote you why:

> See #1314 #1510

**Comment by dAtA-TRoN** [comment]
By now, it might be time to pin a notice stating that this feature will not be available 🤔. The question comes up every two weeks.

**Comment by ikanakova** [comment]
> >Why Just why
> 
> https://github.com/fast4x/RiMusic/assets/71184627/79ff6ff3-cb07-475c-bf25-148d83a42808
> 
> 
> 
> By now, it might be time to pin a notice stating that this feature will not be available 🤔. The question comes up every two weeks.

And also pin that there will never be a Google/YouTube login.

**Comment by ikanakova** [comment]
> By now, it might be time to pin a notice stating that this feature will not be available 🤔. 

Or make a template like other apps on Github and whoever breaks he will automatically close the feature request. Pretty much every popular open-source app has this... But I think fast4x, if it ever does, will only do it when it too starts to get lost in the huge number of issues here...

**Comment by dAtA-TRoN** [comment]
> And also pin that there will never be a Google/YouTube login.

Ah, yes, that was the missing piece I couldn't recall!

**Comment by Abilomp** [comment]
And also against of youtube term and condition policies
