### ISSUE TITLE
[Feature]: Favorite button in Android Auto

### ISSUE THREAD

**Issue by Tre916** [fast4x/RiMusic#2183]
### Description

It'd be nice to have access to favorite songs in Android Auto. 

### Suggested Solution

Please implement a favorite toggle in the Android Auto interface.

Also, as it seems there's been lots of requests for new buttons. If possible maybe a settings option to enable/disable functions in AA? I only suggest this because Podcast Addict does this, but just a button would be appreciated.

**Comment by fast4x** [comment]
It's just implemented in library... 
![2024-06-04_23h01_46](https://github.com/fast4x/RiMusic/assets/1484476/8e3dbb03-eff6-429f-ae91-c1be7f517fea)

**Comment by fast4x** [comment]
Podcast work in progress...

**Comment by fast4x** [comment]
Implemented podcasts in search page, available from version 0.6.44
