### ISSUE TITLE
[Feature]: Make cue visible

### ISSUE THREAD

**Issue by christian179717** [fast4x/RiMusic#2188]
### Description

If you start playing a song, there's no way to see the queue or change the order of it.

### Suggested Solution

A button in the player where you can see and edit the queue.

**Comment by ikanakova** [comment]
> A button in the player where you can see and edit the cue.

If by "cue" you mean queue. Then you can swipe up from the player to get to the queue (you have to click the miniplayer to get to the player) or in Settings -> Player Appearance -> in the Player Action Bar section enable the Arrow button.

**Comment by christian179717** [comment]
Ah, thanks
