### ISSUE TITLE
App is closed 

### ISSUE THREAD

**Issue by Yxck9** [fast4x/RiMusic#2190]
### Description

When I'm enjoying the songs I recently downloaded, the app stops working 

### Suggested Solution

I don't now

**Comment by cMattw** [comment]
might be related to [#1937](https://github.com/fast4x/RiMusic/issues/1937)

**Comment by fast4x** [comment]
Please in version 0.6.38, go to miscellaneous settings, enable debug, restart app, repeat crash action, after go again to settings, click on copy crash log and paste here
