### ISSUE TITLE
Give option to edit search  instant of making new search for music 

### ISSUE THREAD

**Issue by Gauravchaubey66** [fast4x/RiMusic#2191]
### Description

Wherever some one search for any music and unfortunately it's searched wrong , typo mistake or want to add other things in search too then we have to search again instant of editing that search.
![Screenshot_20240607_011135](https://github.com/fast4x/RiMusic/assets/149640114/8eb44d04-eda8-4072-9ea4-3d86d679f8bf)

### Suggested Solution

After adding that feature user can directly edit their search terms or add new search terms without making new search again. 
As far I know this was available in older versions but not in latest one.

**Comment by fast4x** [comment]
in the future will be new search function

**Comment by aneesh1122** [comment]
You can do it this way

https://github.com/fast4x/RiMusic/assets/45353488/31e177f0-d3c3-42c7-b7e9-7cae67a1f371

**Comment by Gauravchaubey66** [comment]
Now working in my case.
https://github.com/fast4x/RiMusic/assets/149640114/1b38f41b-a7a9-455c-861f-9ccdca491cfa

**Comment by aneesh1122** [comment]
> Now working in my case.
> https://github.com/fast4x/RiMusic/assets/149640114/1b38f41b-a7a9-455c-861f-9ccdca491cfa
> 
> 

It works when you type the song's name and search. If you select the name from the drop down then it won't work

**Comment by Gauravchaubey66** [comment]
@aneesh1122 yeah but I was requesting for that feature. where we can edit our search.
what is your opinion on this feature.❓

**Comment by aneesh1122** [comment]
> @aneesh1122 yeah but I was requesting for that feature. where we can edit our search.
> what is your opinion on this feature.❓

I would like that and I'll be very happy if fast4x implements it. Until that time use the 'workaround' I gave.
