### ISSUE TITLE
'Date favourited' sorting in playlists

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2193]
### Description

Could you please add 'Date favourited' sorting in playlists also?

### Suggested Solution

I saved a playlist where the songs are frequently updated. I want to see in the top the songs I'm yet to 'like' so that I can discover new added songs.

This playlist is imported from Spotify so it follows Spotify order so it's not possible to sort it as 'date added'

**Comment by fast4x** [comment]
Sorry i can't

**Comment by aneesh1122** [comment]
> Sorry i can't 

It's okay. I know why. Thank you for all the things you've implemented in this app on my request.
