### ISSUE TITLE
Add a radio option in YouTube music playlist 

### ISSUE THREAD

**Issue by Chickenshrimps** [fast4x/RiMusic#2194]
### Description

![Screenshot_2024_0607_184443](https://github.com/fast4x/RiMusic/assets/108865702/1ca444c2-13b0-40db-8a60-260a9b3d3cbb)
Add a radio option in the playlist so that it can shuffle songs from YouTube music
The shuffle option present in the playlist shuffles songs directly from the YouTube App, which takes too much data from my Android phone. 

### Suggested Solution

A radio 📻 option on the navigation bar next to the shuffle option 

### Alternatives

A radio feature fetches songs directly from YouTube music app without taking too much of the data on Android 
![Screenshot_2024_0607_185041](https://github.com/fast4x/RiMusic/assets/108865702/0fff6fb4-ce75-4bf5-ab28-e33aee056465)

### Additional Context

Thanks for your support 💗💗

**Comment by fast4x** [comment]
Implemented, available from version 0.6.38

**Comment by Chickenshrimps** [comment]
> Implemented, available from version 0.6.38

It isn't working still fetches audios from YouTube. I want it directly from Yt Music
