### ISSUE TITLE
App not connecting to media

### ISSUE THREAD

**Issue by jssj0** [fast4x/RiMusic#2195]
### Steps to reproduce the bug

Simply opening the app.

### Expected behavior

The app should populate all appropriate areas after loading media.

### Actual behavior

The app opens and media does not load and there is no connection to source.

### Screenshots/Screen recordings

![Screenshot_20240607_100945](https://github.com/fast4x/RiMusic/assets/172048358/59f36d53-7b69-442b-81fd-4d0b6f153961)

### RiMusic version

0.6.37

### Android version

Android 13

### Additional information

I noticed this problem only this morning after I opened the app. The app was working normally the previous evening (Thursday, June 6, 2024).

**Comment by fast4x** [comment]
Not reproduced, check your configuration and data connection...

**Comment by jssj0** [comment]
Al configurations andl data connections operational except for RiMusic.

**Comment by jssj0** [comment]
Update...I fixed the issue. I have Duck Duck Go App tracking protection. Th VPN was blocking a configuration in RiMusic from external storage (SD Card). I switched Duck Duck Go back to internal storage and the issue cleared itself up. RiMusic now operating normally. Thank you for your help.

**Comment by fast4x** [comment]
Thanks for feedback
