### ISSUE TITLE
Monthly Playlists Generation

### ISSUE THREAD

**Issue by drago-bit** [fast4x/RiMusic#2196]
### Steps to reproduce the bug

Bug, possibly, but more like a question.
How long it will take the 'Monthly Playlist to generate? What's the time schedule?

### Expected behavior

Playlist should generate when the next month hits.

### Actual behavior

No playlist has been generated after seven days.

### RiMusic version

0.6.37

### Android version

Android 14

### Additional information

The option is enabled in the settings.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.38

**Comment by drago-bit** [comment]
> Fixed, available from version 0.6.38

Whoa, that was fast. 🤩
