### ISSUE TITLE
Dropdown menu for these icons, as it was implemented once, 

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#2198]
### Description

drop down menu for these icons 

![Screenshot_20240607-215232](https://github.com/fast4x/RiMusic/assets/136909951/8350ee58-b122-480a-9410-2dce908dea21)

### Suggested Solution

same

**Comment by Vishcot** [comment]
isn't it cluttered ?

**Comment by Vishcot** [comment]
@fast4x why ignoring? did i do something that is not acceptable ? you haven't even replied to many issues i opened..its been weeks!

**Comment by fast4x** [comment]
This isn't planned
