### ISSUE TITLE
Quick picks based on last song played

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#22]
### Description

Most of the times quick picks are not based on last song played. It'll be better if quick picks are based on last song played 

### Suggested Solution

Quick picks based on last song played

**Comment by fast4x** [comment]
Added section Tips on Quick picks.
Available from 0.6.5 version

**Comment by faustaahmad** [comment]
@fast4x Current behavior isnt by Last played song, but Last added song

**Comment by fast4x** [comment]
Hhmm I'll check
