### ISSUE TITLE
Default Recomandations

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#220]
### Description

Since ViMusic when your song has none recommendations the app puts default one that has nothing to do with your song

### Suggested Solution

Remove these default recommendations when the app dosent find recommendations

### Additional Context

![SmartSelect_20231214_175012](https://github.com/fast4x/RiMusic/assets/104271365/30ba9dd6-40e5-438e-95d4-4857ce1ede91)

**Comment by fast4x** [comment]
If I remove the default recommendation, no information will be displayed. Blank screen with only the most listened song.
