### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by AquamarineDreams** [fast4x/RiMusic#2201]
### Steps to reproduce the bug

**Probably not a bug**

Just opened Rimusic, and it told me that a new release was available. I went to download it, and there's nothing. Did it got deleted?

### Screenshots/Screen recordings

![IMG_20240607_144907](https://github.com/fast4x/RiMusic/assets/140275860/aaa85ae0-2987-4f54-a25e-94448101241b)

### Additional information

Probably not a bug, but what happened anyways?

**Comment by fast4x** [comment]
soon...

**Comment by fast4x** [comment]
Published..
