### ISSUE TITLE
I can't add to queue a especific song

### ISSUE THREAD

**Issue by PPereaC** [fast4x/RiMusic#2203]
### Steps to reproduce the bug

https://github.com/fast4x/RiMusic/assets/74180013/9358434b-bf59-46fc-9d15-307c6c76e6b3

### Expected behavior

In the last app version, I can't add any song to the queue. In previous versions you could add tapping in add to queue or add next song buttons.

I only want to play the songs I queue and not have all the songs in the playlist queued when I play one.

### Actual behavior

.

### RiMusic version

Last version

### Android version

Android 13

**Comment by fast4x** [comment]
from which section?

**Comment by PPereaC** [comment]
In my playlists

**Comment by PPereaC** [comment]
> from which section?

In my playlists

**Comment by fast4x** [comment]
Tap on song, auto queue songs... long tap play next or enqueu withoud queue other songs

**Comment by hashtagbrowns** [comment]
hello, i also have this problem, the problem is that long tapping to play next or enqueue without queuing other songs does not work in 0.6.38 (it worked for me before)

**Comment by PPereaC** [comment]
> hello, i also have this problem, the problem is that long tapping to play next or enqueue without queuing other songs does not work in 0.6.38 (it worked for me before)

Yes, that is the problem. It stopped working in the latest version.

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion
Try custom version

**Comment by fast4x** [comment]
Fixed, available from version 0.6.40, but can download now the custom version with bug fixed.
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by PPereaC** [comment]
> Fixed, available from version 0.6.40, but can download now the custom version with bug fixed. https://github.com/fast4x/RiMusic/tree/master/customVersion

@fast4x Thank you very much, really, you are amazing. Keep it up, it's incredible how the app is turning out.
