### ISSUE TITLE
Add next not working

### ISSUE THREAD

**Issue by claxcian** [fast4x/RiMusic#2204]
### Steps to reproduce the bug

When I wanto add next song at playlist not working

### Expected behavior

With new version 0.6.38

### Actual behavior

Always

### RiMusic version

0.6.38 and 0.6.39

### Android version

14

**Comment by fast4x** [comment]
it work look

https://github.com/fast4x/RiMusic/assets/1484476/ed7122a1-f19c-402b-95fc-afeddcfc0bb6

**Comment by PPereaC** [comment]
> it work look
> 
> https://github.com/fast4x/RiMusic/assets/1484476/ed7122a1-f19c-402b-95fc-afeddcfc0bb6
> 
> 

It's not working for me too. Inside of personal playlist.

**Comment by fast4x** [comment]
ok I'll check it in personal playlist

**Comment by claxcian** [comment]
--- 𝘾𝙡𝙖𝙪𝙙𝙞𝙤 𝘾𝙞𝙖𝙣𝙙𝙧𝙞𝙣𝙞 ---

Il Sab 8 Giu 2024, 00:00 Rino Russo ***@***.***> ha scritto:

**Comment by claxcian** [comment]
https://github.com/fast4x/RiMusic/assets/46830063/fb0d5868-f3b3-4e6e-8e0b-225a59493600
