### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#2205]
・Enable Quick Picks page
・Vietnamese (Lang settings)
・PARENTAL CONTROL
・Parental Control
・Prevent play songs with age limitation
・PLAYLIST \s (PLAYLIST TOP in settings)

### RiMusic version

0.6.37

**Comment by fast4x** [comment]
Fixed, i haven't found playlist top.
Available from version 0.6.39

**Comment by faustaahmad** [comment]
@fast4x near the end of UI settings
PLAYLIST TERATAS (PLAYLIST TOP in English)
![Screenshot_20240608-042916](https://github.com/fast4x/RiMusic/assets/45221211/cada6b33-cdd8-4bd9-9aff-4974f14f3fd3)

**Comment by faustaahmad** [comment]
Forgot to add this one
・BACKUP AND RESTORE (inside Data settings)

**Comment by fast4x** [comment]
Playlist top is ok, back... fixed.... thanks.. :)
