### ISSUE TITLE
Bottom right search/shuffle button displaying the wrong way

### ISSUE THREAD

**Issue by Azzoooo** [fast4x/RiMusic#2207]
### Steps to reproduce the bug

Go to any page where the bottom right button displays (e.g. home page, songs page, albums page and into any album or playlist).

### Expected behavior

The button should appear right on the top of the song bar

### Actual behavior

The button appears partially hidden under the song bar

### Screenshots/Screen recordings

![Screenshot_2024-06-07-23-00-01-769_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/131283264/fe74ea4f-ac29-45a8-af11-c0d0c9218f57)

### RiMusic version

0.6.38

### Android version

Android 13

**Comment by fast4x** [comment]
Tap and hold, move it where you want

**Comment by Azzoooo** [comment]
Thank you
