### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Lokotee** [fast4x/RiMusic#2210]
### Steps to reproduce the bug

Seleccione cualquier canción que no esté descargada y aparece una un error 

### Expected behavior

Debería de reproducir la canción 

### Actual behavior

En la imagen de la portada apareció un letrero " el identificador del video no se corresponde con el que se solicito" y no reproduce ninguna canción 

### Screenshots/Screen recordings

![Screenshot_20240607_215600](https://github.com/fast4x/RiMusic/assets/172095751/0c17d729-0992-4317-849b-6319bab8560f)

### RiMusic version

0.6.38

### Android version

Android 13

**Comment by fast4x** [comment]
Isn't an error but an alert because song id mismatch and can't reproduce it
