### ISSUE TITLE
Scrolling in queue that song got disappeared

### ISSUE THREAD

**Issue by Gauravchaubey66** [fast4x/RiMusic#2212]
### Steps to reproduce the bug

Play any music
Go to queue
Scroll down or up any song

### Expected behavior

"That should not disappeared"

### Actual behavior

"Got disappeared"

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/149640114/4ddb2bf5-fc4d-4747-99fe-654d3b15fef9

### RiMusic version

0.6.38

### Android version

Android 13

### Additional information

I raised this issue already and you marked it as fixed @fast4x but it's still in new version which is 0.6.38

**Comment by fast4x** [comment]
send new video

**Comment by Gauravchaubey66** [comment]
https://github.com/fast4x/RiMusic/assets/149640114/cfad575c-e791-4c2b-b45e-8839714674cf

Here you go previous video was also recorded on new version

**Comment by fast4x** [comment]
ok I'll check it better

**Comment by twistios** [comment]
I have the same problem.

**Comment by Gauravchaubey66** [comment]
> I have the same problem.

It will fix soon as @fast4x mentioned he will fix in next update ❤

**Comment by twistios** [comment]
It seems to be partly fixed in 0.6.39. The hole is still created but it only stays there while dragging. Once the song is released, it recovers after a short time.

**Comment by Gauravchaubey66** [comment]
> It seems to be partly fixed in 0.6.39. The hole is still created but it only stays there while dragging. Once the song is released, it recovers after a short time.

Overall all its seems fixed.👍

**Comment by twistios** [comment]
I am sorry I did not correctly explain what I meant. The hole is correct now but the song is invisible after being dragged out of screen and the dragged back. It gets visible on release.

**Comment by twistios** [comment]
> I am sorry I did not correctly explain what I meant. The hole is correct now but the song is invisible after being dragged out of screen and then dragged back. It then gets visible on release.

I think I am going to open a new issue about this.

**Comment by Gauravchaubey66** [comment]
> > I am sorry I did not correctly explain what I meant. The hole is correct now but the song is invisible after being dragged out of screen and then dragged back. It then gets visible on release.
> 
> I think I am going to open a new issue about this.
> 

In my case it's working fine so if you're getting still any issue attach a video lem me take a look bcz I am not facing any problem. Attach a video before opening new issue👍

**Comment by twistios** [comment]
It is a kind of different problem so thats why I opened an issue.
