### ISSUE TITLE
Dynamic Theme Problem

### ISSUE THREAD

**Issue by srozyy** [fast4x/RiMusic#2214]
### Steps to reproduce the bug

1) Settings
2) UI
3) User Interface → Theme → Choose: **Dynamic**

### Expected behavior

Please watch the video I shared → Actual behavior

### Actual behavior

https://github.com/fast4x/RiMusic/assets/172110441/10b59855-98cb-4721-bec1-39d766aff10c

The color problem occurs when the song is opened.

### RiMusic version

0.6.42

### Android version

14

### Additional information

The keep minimized option must be turned off in the UI settings.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.44
