### ISSUE TITLE
Enable Cache Folder option for Android 12 

### ISSUE THREAD

**Issue by Chickenshrimps** [fast4x/RiMusic#2218]
### Steps to reproduce the bug

Go to data tab 
Scroll to the Folder cache 

### Expected behavior

Support Android 12 

### Actual behavior

Not supporting Android 10+ devices 

### Screenshots/Screen recordings

![Screenshot_2024_0608_224640](https://github.com/fast4x/RiMusic/assets/108865702/95c9bde0-445c-4baf-b109-5e23171b2e48)

### RiMusic version

0.6.38

### Android version

Android 12

**Comment by fast4x** [comment]
Implemented cache system or private, private can't cleaned by the android system.
Available from version 0.6.39

**Comment by Abilomp** [comment]
Make all color independent like For Player interface should be independent,
And home screen also independent. color should not mixed with player and
home screen..
And also about the thumbnail roundness In player interface it should be
heavy round and in home screen,album, artist should be none roundness..
