### ISSUE TITLE
Nonfree deps for F-Droid build

### ISSUE THREAD

**Issue by linsui** [fast4x/RiMusic#2220]
### Steps to reproduce the bug

https://gitlab.com/fdroid/fdroiddata/-/jobs/7051219099

### Expected behavior

No nonfree libs are used.

### Actual behavior

There are nonfree libs.

### RiMusic version

0.6.38

### Android version

12

**Comment by fast4x** [comment]
my build is totally free, v4 is an update internal of GitHub workflow actions.

**Comment by fast4x** [comment]
Ok ok i understand, is a credentials libs for local storage credential, i will replace with other save credentials method.
Thanks

**Comment by fast4x** [comment]
Just removed...

**Comment by linsui** [comment]
Will you removed it in the next version? Should we simply skip this version?

**Comment by fast4x** [comment]
Yes, skip to next version

**Comment by linsui** [comment]
Thanks!

**Comment by fast4x** [comment]
Thanks to you

**Comment by fast4x** [comment]
Fixed, available from version 0.6.39
