### ISSUE TITLE
Floating button colliding with player when set on bottom

### ISSUE THREAD

**Issue by Kurrode** [fast4x/RiMusic#2221]

**Comment by fast4x** [comment]
Tap and hold icon, move it where you want

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/f6dba3d5-c319-4488-99c9-43c601ebf2e7

**Comment by sharunkumar** [comment]
@fast4x is there an option to turn off the floating search button? since we already have a search button at the top?

![image](https://github.com/fast4x/RiMusic/assets/715417/fd955756-9475-43bf-965c-8019233328c0)

**Comment by fast4x** [comment]
Yes

![Screenshot_2024-06-09-06-11-10-320_it.fast4x.rimusic.debug-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/167d07e4-a0a0-4cb8-8484-df8c8c398a6b)

**Comment by fast4x** [comment]
Search on top can't hide

**Comment by sharunkumar** [comment]
> Yes
> 
> ![Screenshot_2024-06-09-06-11-10-320_it.fast4x.rimusic.debug-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/167d07e4-a0a0-4cb8-8484-df8c8c398a6b)
> 
> 

I have that option disabled but I was still having the floating button (in my earlier screenshot)

![Screenshot_20240609_120121.png](https://github.com/fast4x/RiMusic/assets/715417/416798de-8f61-41c4-843d-dde3cc9952ae)

**Comment by fast4x** [comment]
Search icon on top bar is not floating icon ... it's fixed
