### ISSUE TITLE
'Play Next' not working as intended

### ISSUE THREAD

**Issue by sharunkumar** [fast4x/RiMusic#2224]
### Steps to reproduce the bug

- Play a playlist
- Open currently playing list view
- Long press a song 
- Click Play Next

### Expected behavior

Song is queued next to the currently playing song

### Actual behavior

Nothing happens

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/715417/bb8ca245-db6c-44c4-81fd-465f155265bc

### RiMusic version

0.6.38

### Android version

14

**Comment by fast4x** [comment]
playlist imported or created?

**Comment by Ao1Pointblank** [comment]
> playlist imported or created?

It doesn't work with either imported nor locally created for me, since the last update. Same with the Enqueue button.

**Comment by aneesh1122** [comment]
> playlist imported or created?

It's actually the queue

**Comment by fast4x** [comment]
Look it work

https://github.com/fast4x/RiMusic/assets/1484476/f6e64457-fb26-40d8-a711-34fdde5f4f35

**Comment by sharunkumar** [comment]
> playlist imported or created?

I just use the downloaded songs tab

**Comment by fast4x** [comment]
So not in playlist... but in home songs ..

**Comment by coke38** [comment]
I got the same bug, for me how I get it is :
- Go to songs
- Shuffle all songs
- Select a songs to play it next
- Nothing happens

It seems indeed that this behavior appears after the last update.

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion
Try custom version

**Comment by fast4x** [comment]
Fixed, available from version 0.6.40, but can download now the custom version with bug fixed.
https://github.com/fast4x/RiMusic/tree/master/customVersion
