### ISSUE TITLE
Playlist Shuffle Songs Not Working

### ISSUE THREAD

**Issue by hyperlogger64** [fast4x/RiMusic#2226]
### Steps to reproduce the bug

When you select 'Shuffle Song Position' in a playlist, the order is not shuffled.

1) Create a playlist
2) Ensure playlist order is set to unlocked and set to Position
3) Select option to 'Shuffle Song Position' and accept the modal warning
4) Observe the order not change

### Expected behavior

When 'Shuffle Song Position' is selected, the entire order of the playlist is randomly shuffled

### Actual behavior

This has mixed results. Sometimes I've noticed it moves a few songs around, but on subsequent Shuffles it returns the order back to original. Other times, nothing happens at all.

### RiMusic version

Latest Version (v0.6.38)

### Android version

Android 14

**Comment by fast4x** [comment]
maybe you mean manually reorder not warning?

**Comment by hyperlogger64** [comment]
No, that's a separate issue that I saw posted. When I create a playlist and then select Shuffle Songs from the options, nothing happens and the order remains the same. I can post a video if it helps, tested it on multiple devices with the same behavior.

**Comment by fast4x** [comment]
Translation is wrong, option is Reset song position... it's used when playlist have a issue and not be sorted...

**Comment by hyperlogger64** [comment]
https://github.com/fast4x/RiMusic/assets/172119544/bf648c0e-a0ce-404a-af2e-6e86c3fb8d8b

I'm not sure what you mean. Here is a video to demonstrate the issue. Note how it moves the position of a few songs and then by toggling the option again, the original order is restored. If you Shuffle again, the results is the same ordering as the first shuffle, which means there are only two possible outcomes. I think that this behavior goes against the convention of a traditional 'shuffle'.
