### ISSUE TITLE
Not getting any response from floating player within queue

### ISSUE THREAD

**Issue by Gauravchaubey66** [fast4x/RiMusic#2227]
### Steps to reproduce the bug

Play any music 
Open queue
Then tap on floating music player 

### Expected behavior

This should redirect to the music page  

### Actual behavior

Nothing happen when touching the floating player 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/149640114/a289732a-d0a7-4203-872f-89bc49274d6f

### RiMusic version

0.6.38

### Android version

Android 13

### Additional information

I am not sure that it's a bug or what but I should redirect on music page when clicked which is not helping only when we are in music queue.

**Comment by Gauravchaubey66** [comment]
I know there is a arrow to go on music page when we are within music queue but I think it's add little bit more interaction.

**Comment by aneesh1122** [comment]
> I know there is a arrow to go on music page when we are within music queue but I think it's add little bit more interaction.

Tap the bottom bar. It will re-open the player

**Comment by Gauravchaubey66** [comment]
> > I know there is a arrow to go on music page when we are within music queue but I think it's add little bit more interaction.
> 
> Tap the bottom bar. It will open the player

That is working already can you tell me that floating player in queue is not for redirecting in player. I think that add a little bit details.

**Comment by fast4x** [comment]
Tap on miniplayer from queue... not have any effect...

**Comment by fast4x** [comment]
would you to open player from queue?

**Comment by Gauravchaubey66** [comment]
> would you to open player from queue?

Yes I tried but there is not any effect after clicking on floating or mini player.

**Comment by Gauravchaubey66** [comment]
https://github.com/fast4x/RiMusic/assets/149640114/9ee5ebc9-6825-4c8e-b42b-2a4becb947b1

Here is a video for clear reference .

**Comment by aneesh1122** [comment]
> would you to open player from queue?

I think it would be great if tapping on the mini player opens the main player everywhere on the app.

Everyone's first instinct to open the player is to tap on the mini player.

To prevent future feature requests similar to this one, implementing 'touch mini player to open the main player' should be implemented since many people requested for the same

**Comment by aneesh1122** [comment]
> ok I'll add also in queue 

Thanks man

**Comment by Gauravchaubey66** [comment]
> > ok I'll add also in queue 
> 
> Thanks man

I should say thanks to @fast4x 😂

**Comment by fast4x** [comment]
Implemented, available from verson 0.6.39
Attention, is recursively action from queue...

**Comment by Gauravchaubey66** [comment]
@fast4x I believe that you should implement this it's removed 😊

**Comment by fast4x** [comment]
not remain so... from queue not open player

**Comment by Gauravchaubey66** [comment]
> not remain so... from queue not open player


Sorry,  I am unable to get your point what's your mean this will not required to implement or anything else 🥲
