### ISSUE TITLE
App cannot be terminated

### ISSUE THREAD

**Issue by Chungaa** [fast4x/RiMusic#2229]
### Steps to reproduce the bug

If you want to close the app, it doesn't work, no matter what you do.

https://github.com/fast4x/RiMusic/assets/109001366/2991daf9-de71-4914-852e-20ac594d3362

### Expected behavior

!

### Actual behavior

!

### Logs

!

### RiMusic version

0.6.38

### Android version

Android 13

### Additional information

!

**Comment by fast4x** [comment]
Enable

![Screenshot_2024-06-09-18-42-56-302_it.fast4x.rimusic.debug-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/6b40c1af-52cc-42ee-862d-70ef8c444f71)

**Comment by Chungaa** [comment]
Not working
![Screenshot_2024-06-09-18-49-26-31_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/109001366/a6e4fbb6-adbf-4bab-8b1d-000dde73bb71)

**Comment by Chungaa** [comment]
https://github.com/fast4x/RiMusic/assets/109001366/5cabc5bb-3866-4170-8644-455bc36e8ae6

Not working

**Comment by fast4x** [comment]
After enable must restart app

**Comment by Chungaa** [comment]
I have restart the App, but Not working.

**Comment by fast4x** [comment]
I'll create a custom version for debug your app.
