### ISSUE TITLE
App crashes whenever clicked "On Device" page.

### ISSUE THREAD

**Issue by koreji** [fast4x/RiMusic#2231]
### Steps to reproduce the bug

Click "On Device" page
Allow storage access
Then boom crash

### Expected behavior

App should shows the entire song collection from the device.

### Actual behavior

App crashes whenever I tried.

### Screenshots/Screen recordings

https://media.discordapp.net/attachments/817821376848724002/1249382300316074116/20240609221438.mp4?ex=66671970&is=6665c7f0&hm=11d0448ca796406f84ec39c071667a7d444db332af42ee5627814b35507cb92e&

### Logs

Crash log

2024-06-09T22:07:06.956:	java.lang.IllegalArgumentException: Invalid column bitrate
	 android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170) 
	 android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140) 
	 android.content.ContentProviderProxy.query(ContentProviderNative.java:423) 
	 android.content.ContentResolver.query(ContentResolver.java:944) 
	 android.content.ContentResolver.query(ContentResolver.java:880) 
	 android.content.ContentResolver.query(ContentResolver.java:836) 
	 G6.n.r(SourceFile:328) 
	 G6.n.g(SourceFile:13) 
	 r7.K.c(SourceFile:73) 
	 r7.f.c(SourceFile:18) 
	 r7.D.r(SourceFile:51) 
	 W6.a.m(SourceFile:9) 
	 o7.I.run(SourceFile:95) 
	 m.k.run(SourceFile:15) 
	 u7.i.run(SourceFile:3) 
	 u7.a.run(SourceFile:92) 

### RiMusic version

0.6.38

### Android version

Android 10

### Additional information

Everything works fine except this.

**Comment by fast4x** [comment]
Download custom version it's just fixed
