### ISSUE TITLE
proprietary components added

### ISSUE THREAD

**Issue by IzzySoft** [fast4x/RiMusic#2233]
### Steps to reproduce the bug

Look at the dependency tree

### Expected behavior

only FOSS libs reported

### Actual behavior

GMS inside

### Screenshots/Screen recordings

![image](https://github.com/fast4x/RiMusic/assets/6781438/45fd0811-2d9e-40ce-91e1-49f2abcd8504)

### RiMusic version

0.6.38

### Android version

n/a

### Additional information

I'll now also have to add the `NonFreeComp` anti-feature at IzzyOnDroid, as the app contains non-free components (GMS). If you didn't add that intentionally, maybe some new/updated component dragged it in. The only one I see added is [Android Jetpack Annotations](https://developer.android.com/jetpack/androidx/releases/annotation). Maybe `gradle :app:dependencies` helps you to find the culprit.

**Comment by fast4x** [comment]
Hi, I just removed that, it was android credentials manager...

**Comment by IzzySoft** [comment]
Thanks! Then it should be cleared up with the next release, excellent. And wow, linsui was faster reporting it :bowing_man: I'm closing this then as duplicate (cannot mark it such, but close I can).
