### ISSUE TITLE
Switched to ViMusic interface, now not able to switch to RiMusic

### ISSUE THREAD

**Issue by sharunkumar** [fast4x/RiMusic#2234]
### Steps to reproduce the bug

I tried switching to ViMusic UI for checking a something now I'm not able to switch back

1. Go to settings
2. UI Section
3. Change to ViMusic
4. Change back to RiMusic

### Expected behavior

RiMusic UI should be used

### Actual behavior

Stuck in ViMusic UI

### Screenshots/Screen recordings

![Screenshot_20240609_121334](https://github.com/fast4x/RiMusic/assets/715417/42f2c753-0a85-4b09-8be3-32643e44d7b4)

### RiMusic version

0.6.38

### Android version

14

**Comment by fast4x** [comment]
Change navigation bar position

**Comment by sharunkumar** [comment]
> Change navigation bar position 

Hmmm, so if this is a default setting for rimusic style (untouched by me) shouldn't it revert to bottom when switching from vimusic mode to rimusic mode? 🤔

**Comment by fast4x** [comment]
It’s partially managed the transition between rimusic and vimusic but not the other way around...
