### ISSUE TITLE
Fix the Layout of the History Page

### ISSUE THREAD

**Issue by Jetliarm** [fast4x/RiMusic#2237]
### Description

Hope you're good Can you fix the layout of the history page on our app? It's not really important, but it would make things look better.

### Suggested Solution

.

### Alternatives

.

### Additional Context

.
![orca-image--1685421108](https://github.com/fast4x/RiMusic/assets/171421185/b72c3b39-eb48-4acf-8e71-227901993f85)

**Comment by fast4x** [comment]
Fixed, avaiable from version 0.6.47
