### ISSUE TITLE
Frozen screen

### ISSUE THREAD

**Issue by kris20030705** [fast4x/RiMusic#2240]
### Steps to reproduce the bug

After keeping it in background and opening it again

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/107674915/4e1d9b02-ca86-4d0a-b3da-3e82c0e6d6d5

### RiMusic version

Latest

### Android version

Android 13

**Comment by fast4x** [comment]
Have you enabled invincible service in miscellaneous settings?

**Comment by kris20030705** [comment]
> Have you enabled invincible service in miscellaneous settings?

yes enabled
