### ISSUE TITLE
Since new UI app crashes on Android v7.1.2

### ISSUE THREAD

**Issue by pi99y** [fast4x/RiMusic#2243]
### Steps to reproduce the bug

Just running the app on Android v7.1.2 makes it crash.

### Expected behavior

It shouldn't crash.

### Actual behavior

After running the app I can see the interface for a split second then the Android's "app keeps stopping" message appears before I can interact with the app. Versions before the new UI (a few releases ago) worked fine. It started with the new UI and hasn't improved / changed in the last few releases.

### RiMusic version

0.6.38

### Android version

Android v7.1.2

**Comment by fast4x** [comment]
Download custom version and try again
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by pi99y** [comment]
Thanks for the answer @fast4x however there seems to be almost no difference, now it perhaps crashes half a second later, but pretty much in the same fashion. I also tried uninstalling beforehand but it made no difference.

**Comment by fast4x** [comment]
try set max number of song in queue and enable debug in miscellaneous settings.
After crash go to settings debug, click on copy crash log and paste here

**Comment by pi99y** [comment]
@fast4x unfortunately it crashes before I can get to settings

**Comment by fast4x** [comment]
Remove app, activate debug and try again

**Comment by pi99y** [comment]
@fast4x wait, this debug setting is not in the app but in Android?

**Comment by fast4x** [comment]
Inside app in settings > miscellaneous > bottom page, look
![Screenshot_20240613_182042](https://github.com/fast4x/RiMusic/assets/1484476/ac38fc72-91bc-49e5-aa91-12b9b502de2c)

**Comment by pi99y** [comment]
@pi99y The app crashes before I can open the settings. I can't reach that screen.

**Comment by fast4x** [comment]
Check permission in android app manager

**Comment by pi99y** [comment]
I enabled storage and microphone permissions (the only two that were available) but it made no difference.

**Comment by pi99y** [comment]
Yes, same. Does this by chance rely on google services? Because those are not installed, but it worked fine without them in older versions as reported.

**Comment by fast4x** [comment]
Yes, it can possible, wait new version 0.6.39, will be without google account manager.

**Comment by pi99y** [comment]
Great, thank you very much!

**Comment by pi99y** [comment]
Just some additional info: it works on Android 9 and MicroG instead of Google services. 🤞

**Comment by pi99y** [comment]
@fast4x unfortunately the new version v0.6.39 crashes in the same way - immediately on start, before I can interact with the app to change any settings.

I removed previous version before installing the new one.

Again, the app worked fine before the 'new UI' version so one of those changes makes it crash.

Thanks!

**Comment by pi99y** [comment]
@fast4x the new version 0.6.40 brought no changes, same behaviour and crash.
One thing I noticed is that the app crashes immediately if I remove internet access to it via firewall, but if the app has internet access, the app loads some things on the first page before it crashes, but still crashes within a second, so I can't change any settings...

@fast4x please reconsider the 'not a bug' tag... why do you think it's not a bug?

Thabk you
