### ISSUE TITLE
Floating search button is hidden by floating mini player

### ISSUE THREAD

**Issue by Gauravchaubey66** [fast4x/RiMusic#2246]
### Description

Floating search button is hidden by floating mini player I think it should be adjusted to prevent hidden by mini floating player.

### Suggested Solution

Just adjust the position a little bit up or change layout to prevent this one. It's a little details I know but it can be improve.😁
![Screenshot_2024_0610_203929](https://github.com/fast4x/RiMusic/assets/149640114/0d525c3c-b0c1-4734-8fae-32780ed726c8)

https://github.com/fast4x/RiMusic/assets/149640114/a699e175-b2fc-4e93-bd7a-c71f681f383b

**Comment by aneesh1122** [comment]
Hold the search button and place it anywhere you want

**Comment by Gauravchaubey66** [comment]
> Hold the search button and place it anywhere you want

Sorry 😁
