### ISSUE TITLE
enlarge video thumbnail when tapped or by default

### ISSUE THREAD

**Issue by ZandrexV** [fast4x/RiMusic#2247]
### Description

If I want to play a video, it comes out as is. Therefore, it would be better to enlarge it so that it can be seen better

### Suggested Solution

By touching it or by default, the image thumbnail appears square and not rectangular
Example:
![20240610_143513](https://github.com/fast4x/RiMusic/assets/162504062/507cb5de-71e7-4f32-8327-0b0c2d4dba12)

**Comment by fast4x** [comment]
Single tap = show lyrics not possible to use for other, set size from settings
