### ISSUE TITLE
[Feature]: Can we have player speed options like speed and pitch and volume booster like ymusic has?

### ISSUE THREAD

**Issue by Varniit-pro-90s** [fast4x/RiMusic#2248]
### Description

Can we have player speed options like speed and pitch and volume booster like ymusic has?

### Suggested Solution

Cant find any.

### Alternatives

Ymusic app.

### Additional Context

https://ymusic.io/

**Comment by aneesh1122** [comment]
Long press the play/pause button

**Comment by ZandrexV** [comment]
![Screenshot_20240610-174310](https://github.com/fast4x/RiMusic/assets/162504062/52aa8e09-0244-4c65-ace7-31be3fac21c3)

**Comment by fast4x** [comment]
Implemented also device volume...
