### ISSUE TITLE
When I stop the song and exit RiMusic, a notification appears that cannot be removed

### ISSUE THREAD

**Issue by ZandrexV** [fast4x/RiMusic#2249]
### Steps to reproduce the bug

1. Go to RiMusic and play a song 
2. Stop the song and exit the app 
3. A notification will appear that cannot be ignored unless you force the stop

### Expected behavior

That the notification can be obtained

### Actual behavior

cannot be removed

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/162504062/34315d74-8acc-406f-861b-723002e6784d

### RiMusic version

0.6.38

### Android version

Android 6.1

### Additional information

You can put an X button so you can skip the notification

**Comment by fast4x** [comment]
Enable close background player in ui settings...
