### ISSUE TITLE
[Feature]: To remove songs from download

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#225]
### Description

A feature to remove songs from download. 

### Suggested Solution

I think in the pervious versions we could remove downloaded songs by clicking on the download option.

**Comment by fast4x** [comment]
The function is there, if the icon does not turn off it might be:

1. the song is not downloaded but in the cache of the player
2. is just a refresh problem
3. the download cache is blocked

Close and reopen RIMusic to see if the song’s download icon is off.

**Comment by dainvincible1** [comment]
> The function is there, if the icon does not turn off it might be:
> 
> 1. the song is not downloaded but in the cache of the player
> 2. is just a refresh problem
> 3. the download cache is blocked
> 
> Close and reopen RIMusic to see if the song’s download icon is off.

after clearing the songs cache its gone from the "downloaded" section. 
but now when i download songs, it is not showing in the "downloaded" section even after closing and reopening the app


https://github.com/fast4x/RiMusic/assets/127825700/c9a8fbb1-4ea8-41a9-9b0c-7cd0fb40b74d

**Comment by dainvincible1** [comment]
> > The function is there, if the icon does not turn off it might be:
> > 
> > 1. the song is not downloaded but in the cache of the player
> > 2. is just a refresh problem
> > 3. the download cache is blocked
> > 
> > Close and reopen RIMusic to see if the song’s download icon is off.
> 
> after clearing the songs cache its gone from the "downloaded" section. but now when i download songs, it is not showing in the "downloaded" section even after closing and reopening the app
> 
>  video_2023-12-16_14-16-59.mp4

this issue is fixed.
