### ISSUE TITLE
'play next' button doesn't work after the update.

### ISSUE THREAD

**Issue by Plut0ishere** [fast4x/RiMusic#2252]
### Steps to reproduce the bug

1. play a playlist
2. long press on a song
3. click play next button

### Expected behavior

song is queued and will play after the current song finishes 

### Actual behavior

nothing happens

### RiMusic version

0.6.38

### Android version

Android 14

**Comment by fast4x** [comment]
Not reproduced, it seem to be fixed, available from version 0.6.39

**Comment by Plut0ishere** [comment]
> Not reproduced, it seem to be fixed, available from version 0.6.39

if u don't mind me asking, when is it dropping?

**Comment by CheeseFort** [comment]
I am experiencing this as well, it also affects the enqueue option. To be thorough I'll add that the same thing happens with an empty queue. Ie, when nothing is playing hitting play next or enqueue does not start playing the song.

**Comment by fast4x** [comment]
> > Not reproduced, it seem to be fixed, available from version 0.6.39
> 
> if u don't mind me asking, when is it dropping?

Friday

**Comment by fast4x** [comment]
@CheeseFort @Plut0ishere  play next not play but only add to next, same for enqueue.

Both do not start playback

**Comment by Ao1Pointblank** [comment]
> Not reproduced, it seem to be fixed, available from version 0.6.39

Issue still persists
