### ISSUE TITLE
[Feature]: Adding search intents

### ISSUE THREAD

**Issue by Warden20** [fast4x/RiMusic#2253]
### Description

Enabling the use of search intents by using a link like (https://www.music.youtube.com/results?search_query=%s) or ([https://music.youtube.com/search?q=${1}&utm_source=opensearch](https://music.youtube.com/search?q=$%7B1%7D&utm_source=opensearch)) and opening it in Rimusic instead of the browser.

### Suggested Solution

Support youtube music search links

### Additional Context

By enabling this integration, it could be used together with search applications or third party launchers, as in my case I use Kvaesitso. https://github.com/MM2-0/Kvaesitso
My idea is that I make a search for example Sweet Victory and the search opens directly in Rimusic facilitating its use.

**Comment by aneesh1122** [comment]
If you're using MIUI/Hyperos, do this

1) install [this](https://play.google.com/store/apps/details?id=com.ceyhan.sets)

2) open 'manage applications'

3) search for RiMusic

4) open 'open my default'

5) Choose 'Add link' and choose 'music.youtube.com'

**Comment by fast4x** [comment]
RiMusic is RiMusic, not ViTune... correct?

**Comment by Warden20** [comment]
Sorry, I fixed it.  I was talking about Rimusic

**Comment by Warden20** [comment]
I tried the solution to open links by default in rimusic through the operating system, this method works to open direct links to artists or albums, etc.. But it doesn't work for search, that's why I proposed to support search links like the ones I mentioned before.

**Comment by fast4x** [comment]
Implemented, work with share with RiMusic and from Go To Link page, available from version 0.6.44
