### ISSUE TITLE
Podcast 

### ISSUE THREAD

**Issue by Jacobo102** [fast4x/RiMusic#2254]
### Description

Add podcast 

### Suggested Solution

Podcasts updated every day 

### Alternatives

A section like yt music where you can listen to podcasts 

### Additional Context

Let there be podcasts of all kinds, example: horror, comedy, etc.

**Comment by ikanakova** [comment]
Duplicity to #1913

**Comment by fast4x** [comment]
I don't think, there are many feature to develop with much priority, i'm sorry

**Comment by fast4x** [comment]
Work in progress...

**Comment by fast4x** [comment]
Implemented podcasts in search page, available from version 0.6.44

**Comment by triggerfx** [comment]
> Implemented podcasts in search page, available from version 0.6.44

The podcasts "playlists" have a maximum of 100 songs, any fix for this?

**Comment by fast4x** [comment]
Soon
