### ISSUE TITLE
[Suggestion] Ability to remove/hide the toggles on the homescreen

### ISSUE THREAD

**Issue by RAiNYRENJi** [fast4x/RiMusic#2255]
### Description

I'm currently making the look of RiMusic on my phone more cleaner and less cluttered... But the app doesn't have an option to hide some of the options for the "For You", "Songs", "Artists", "Albums", and "Playlists" toggles.

![Screenshot_20240611_143024_edit_243924857184709](https://github.com/fast4x/RiMusic/assets/161404404/8516db3f-f5fc-4f6c-b567-d5849e344bad)

### Suggested Solution

Inside the "UI" category, have a option named "Navigation bar" and have toggles for the user to hide or not hide the navigation options, like here in this image, I want to only keep the "For You" and "Songs" options visible.
![Screenshot_20240611_145845_edit_245395090879981](https://github.com/fast4x/RiMusic/assets/161404404/3c13ced7-db7d-4882-96b8-c5a60b22f06b)

**Comment by aneesh1122** [comment]
You can disable 'For you' using this

![IMG_20240611_124754.jpg](https://github.com/fast4x/RiMusic/assets/45353488/62917078-7d5e-47a1-ad4d-04163ff97564)

The rest of the things can't be disabled

**Comment by fast4x** [comment]
It's a menu bar and isn't possible to remove
