### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ghyvpine** [fast4x/RiMusic#2257]
### Steps to reproduce the bug

I've downloaded a lot of songs, then I go to favorites, I set 1 song, I want to play 1 song and press play next, but when the previous song is finished, the next song is not the song I play next

### Expected behavior

Hehe

### Actual behavior

Hehe

### Screenshots/Screen recordings

Idk

### Logs

Idk

### RiMusic version

Latest

### Android version

Android 14 Qpr2 

### Additional information

Idk

**Comment by fast4x** [comment]
I'll check it soon

**Comment by fast4x** [comment]
It seem to be fixed available from version 0.6.39
