### ISSUE TITLE
[Feature]: Backup with cache

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [fast4x/RiMusic#2259]
### Description

Tried using adb not working please a option to backup cached songs so i can freshly install the new versions and also custom versions if the new one gives me issues.

### Suggested Solution

Option to backup the cache of cached songs along with other important info

### Alternatives

Found many apps like titanium backup but they need root to backup cache

**Comment by fast4x** [comment]
Hi, cache is managed by service player and it's crypted, not directly usable...
Cache backup is useless

**Comment by ALMIGHTY-VC** [comment]
> Hi, cache is managed by service player and it's crypted, not directly usable... Cache backup is useless

Oh thanks for informing then i think this is useless should i close this thread
