### ISSUE TITLE
Error in moods and genders

### ISSUE THREAD

**Issue by chatinteligence** [fast4x/RiMusic#2261]
### Steps to reproduce the bug

1- Open the application
2- Go to the animations and genres area
3- Enter and slide to the end
![NaHmXm08Uj](https://github.com/fast4x/RiMusic/assets/147566193/db1e9665-805d-48f0-a681-c05e91e112fc)

### Expected behavior

1- Open the application
2- Go to the animations and genres area
3- Enter and slide to the end

### Actual behavior

1- Open the application
2- Go to the animations and genres area
3- Enter and slide to the end

### RiMusic version

Ri Music v0.6.38

### Android version

Android 14

**Comment by fast4x** [comment]
Fixed, available from version 0.6.39
