### ISSUE TITLE
File Info, and Volume Control (Optional)

### ISSUE THREAD

**Issue by drago-bit** [fast4x/RiMusic#2264]
### Description

Since RiMusic support offline music as well, track information like, File Type, Bitrate, Hertz in the player would be a nice addition.

(Optional) A volume control would be preferable in the player itself, since it will be much easier to use it in a touch device rather than pressing the side buttons again and again, which will definitely impact the life time of the same.

### Suggested Solution

Attached a sample design in the screenshot.

![Screenshot_2024-06-12-10-51-27-763_com piyush music-edit](https://github.com/fast4x/RiMusic/assets/170959159/a092ac68-8ac1-46a2-a5cd-0a7d780f7ec0)

### Alternatives

The Volume Control can be made optional through the settings for those who dislike the idea.

### Additional Context

This is just a suggestion though, nothing of much importance. Thanks for the app. 🤩🥳

**Comment by fast4x** [comment]
This it's just implemented:

_**Since RiMusic support offline music as well, track information like, File Type, Bitrate, Hertz in the player would be a nice addition**_

**Comment by drago-bit** [comment]
> This it's just implemented:
> 
> _**Since RiMusic support offline music as well, track information like, File Type, Bitrate, Hertz in the player would be a nice addition**_

Oh yeah !! 🤩

So, no 'Volume Controls' then?

**Comment by fast4x** [comment]
Volume control will be added... soon...

**Comment by drago-bit** [comment]
> Volume control will be added... soon...
> 

Can't wait then. 🥳

**Comment by ALMIGHTY-VC** [comment]
Well i needed volume controla too good job buddy for presenting my request

**Comment by fast4x** [comment]
Implemented app volume control in player by long tap play pause button, available from version 0.6.39

**Comment by drago-bit** [comment]
> Implemented app volume control in player by long tap play pause button, available from version 0.6.39

Until Friday then. 😎

**Comment by fast4x** [comment]
Implemented also control on device volume...
