### ISSUE TITLE
[Feature]: To change our playlist cover pic

### ISSUE THREAD

**Issue by Squad8991** [fast4x/RiMusic#2265]
### Description

Add a feature to change our playlists cover pic

### Suggested Solution

like this
![image](https://github.com/fast4x/RiMusic/assets/158545574/9461cffd-be7c-49dd-af23-c46afa54fb66)

**Comment by ikanakova** [comment]
Related to #712, #2236

**Comment by dAtA-TRoN** [comment]
I have previously made a similar suggestion but couldn't locate it again. However, using custom images for playlists would be fantastic. It’s essential to me that these covers are included when sharing a playlist.

Please make it happen, Mr. fast4x 🛐.

**Comment by aneesh1122** [comment]
> Backup and Sharing: Ensure that these custom playlist covers are included within backups and when sharing a playlist

Pls also include all the app settings too in the backup @fast4x

**Comment by fast4x** [comment]
Will be possible for piped playlists.

**Comment by Squad8991** [comment]
what about our own created playlist?

**Comment by fast4x** [comment]
> what about our own created playlist?

for now isn't possibile, i'm sorry

**Comment by Squad8991** [comment]
No need to sorry,you are doing a good job
