### ISSUE TITLE
Can't reorder the songs in playlist

### ISSUE THREAD

**Issue by Squad8991** [fast4x/RiMusic#2266]
### Steps to reproduce the bug

Go to your playlist and try reorder the song

### Expected behavior

Song should be reorder

### Actual behavior

Song doesn't reorder

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/158545574/6d307916-b954-46db-8ca0-d68c432a7c4b

### RiMusic version

0.6.38

### Android version

Android 11

**Comment by fast4x** [comment]
Would be a issue in order number. Try shuffle numbers from menu and after try again.
![Screenshot_2024-06-12-13-49-51-212_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/37078e46-a8bd-48a5-8106-edb45129be80)
