### ISSUE TITLE
Missunderstanding

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#227]
### Description

Hi I remember asking to directly go back to the previous song when swiping on the album cover but not when you press the back button.

### Suggested Solution

When using the SWIPING gesture the song should go BACK withouth REPLAYING

But when we press the BACK BUTTON the song should REPLAY only if it was listened for some seconds

example on YTMusic:

https://github.com/fast4x/RiMusic/assets/104271365/6f1205cc-ce99-4258-9256-62024d0140f1

### Alternatives

Maybe add another feature to change that time before songs get replayed if you press the back button

example:
If you chose 60sec the song will be replayed if you go back only alfter this time (remember the swiping gesture never replays)

### Additional Context

Don't take this issue bad it's my fault that you misunderstood my old issue

**Comment by fast4x** [comment]
Lol, ok change it

**Comment by OrangeZXZ** [comment]
Oh yeah the feature could be an setting maybe peoples want the music to not start again when pressing this button

**Comment by fast4x** [comment]
Changed, available from version 0.6.14
