### ISSUE TITLE
Some songs don't load

### ISSUE THREAD

**Issue by assier08** [fast4x/RiMusic#2271]
### Steps to reproduce the bug

Go to an artist
Go to "Songs"
Scroll down

### Expected behavior

All songs should load correctly

### Actual behavior

At some point, when you scroll down, the songs don't charge, doesn't matter the time you wait

### Screenshots/Screen recordings

![Screenshot_2024-06-12-16-19-23-527_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/172515042/e3ec4d20-95e6-4cde-93d9-a99bb03f4756)

### RiMusic version

0.6.38

### Android version

Android 14

**Comment by aneesh1122** [comment]
I'm having the same problem https://github.com/fast4x/RiMusic/issues/1604

**Comment by assier08** [comment]
> I'm having the same problem #1604

It still happens to me with the most recent version, maybe it is a change in the YouTube Music code
