### ISSUE TITLE
[Feature]: Collab with moosync

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [fast4x/RiMusic#2273]
### Description

I think the collaboration with moosync can help open up new horizons for rimusic and make it a power packed all rounder in terms of music streaming because moosync offers custom modules to use various streaming services

### Suggested Solution

They are planning to make a android app too and with a app like rimusic i think they would be more than happy to code it. 

### Alternatives

If the collab isnt possible i am still happy to use rimusic and yeah the gradient background worh flow looks op

### Additional Context

Edit:- Added their repo link:-
https://github.com/Moosync/Moosync

**Comment by fast4x** [comment]
Collaborations are always be accepted, to manage functionality of streaming platforms, must provide access to that platform. Here, RiMusic does not provide for the development of an access except in particular cases such as the Piped world.

**Comment by ALMIGHTY-VC** [comment]
Okay got it thanks
