### ISSUE TITLE
 The application closes when trying to play songs that exceed number 500

### ISSUE THREAD

**Issue by Cuchurrumin19** [fast4x/RiMusic#2277]
### Steps to reproduce the bug

Hello!  My favorites list is more than 500 songs and I have noticed that the application closes when playing a song that is above that number

### Expected behavior

That songs can be played without limit.

### Actual behavior

It cannot be done because the application closes after number 500.

### RiMusic version

0.6.38

### Android version

Android 12

**Comment by fast4x** [comment]
Isn't a bug, it's memory full of your device...
