### ISSUE TITLE
Symmetrical placement for Speed and Pitch icons.

### ISSUE THREAD

**Issue by drago-bit** [fast4x/RiMusic#2278]
### Description

The speed and pitch reset button placement seems a bit down the respective sliders central line.

![Screenshot_2024-06-13-09-46-23-032_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/170959159/15e68be4-af38-405d-acc3-ee49c1ea66d1)

### Suggested Solution

Raise the icon position little higher, such that they will be symmetrical to their respective sliders.

### Alternatives

**Increase the visibility of the numbers underneath**, which will bring back the overall symmetry.

### Additional Context

Thanks for the app by the way.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.39

**Comment by aRandomMenno** [comment]
And additionally you could make it so when you touch the number on the left of the slider you could just type in a number with ome decimal point so you dont have to accurately slide the slider. 🙃

**Comment by fast4x** [comment]
Moving is better than writing... :)

**Comment by aRandomMenno** [comment]
> Moving is better than writing... :)

That is your opinion...

**Comment by fast4x** [comment]
Of course...
