### ISSUE TITLE
RiMusic

### ISSUE THREAD

**Issue by adrielmaxx** [fast4x/RiMusic#2279]
### Description

Hola, soy Cubano, acabo de instalar RiMusic pero no se me conecta ya probé con una VpN y tampoco estaba utilizando Deezer pero ya me dejo de funcionar por las nuevas condiciones de uso, necesito un nuevo reproductor de música online y que a su vez pueda descargar espero que RiMusic sea la solución. Gracias por su atención.
Saludos 

### Suggested Solution

Que pueda estar accesible para cuba

**Comment by fast4x** [comment]
Hello, try to activate the proxy from the miscellaneous settings. The list of usable proxies can be found here
https://geonode.com/free-proxy-list
