### ISSUE TITLE
[BUG]: Application language

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#228]
### Steps to reproduce the bug

settings language

### Expected behavior

we must see all the languages in the lists

### Actual behavior

we don't see all the languages in the lists

### Screenshots/Screen recordings

![image0](https://github.com/fast4x/RiMusic/assets/63956787/946cff5d-fd95-4c64-b305-453eb48d5f66)

### RiMusic version

0.6.13

### Android version

A12 MIUI 14

**Comment by fast4x** [comment]
Actually languages list contain only languages translated.

**Comment by NEVARLeVrai** [comment]
> Actually languages list contain only languages translated.

Pt not in

**Comment by fast4x** [comment]
You are right!

**Comment by fast4x** [comment]
Added pt, pt-br, or, id :)

**Comment by NEVARLeVrai** [comment]
Also system language choose Emojies french Instead of classic French

**Comment by NEVARLeVrai** [comment]
Also system language choose Emojies french Instead of classic French

**Comment by fast4x** [comment]
What's your region?

**Comment by NEVARLeVrai** [comment]
France

**Comment by fast4x** [comment]
Ok, I'll check it for solution to select correct language type

**Comment by fast4x** [comment]
@OrangeZXZ if you select system language, show romanian quit emojies?

**Comment by OrangeZXZ** [comment]
> @OrangeZXZ if you select system language, show romanian lang with emojies?

![Screenshot_20231217_003732_Settings.jpg](https://github.com/fast4x/RiMusic/assets/104271365/77be7673-b807-4638-bd87-99fe9ab95296)

![Screenshot_20231217_003714.jpg](https://github.com/fast4x/RiMusic/assets/104271365/07cdfa9c-e0d1-4212-bd5e-0682d72204b1)

Yes it choses the emojis version but in version 0.6.12 i had the choice between "Romanian(Romanian)" and "Romanian(Moldova)" when choosing Romanian but now it's not the case

**Comment by OrangeZXZ** [comment]
But @fast4x instead of having languages with emojies you can add an setting and use ionicons instead of emojies I think it would look bether

![Screenshot_20231217_004340.jpg](https://github.com/fast4x/RiMusic/assets/104271365/d0e40b35-abe7-4c8f-bbc7-b315202c7a92)

**Comment by fast4x** [comment]
Yes, we should make the emoji an option in settings, so as to separate it from the language selection code.
