### ISSUE TITLE
[Feature]: Download export option

### ISSUE THREAD

**Issue by Chickenshrimps** [fast4x/RiMusic#2280]
### Description

A new downloaded files export option in settings 

### Suggested Solution

This app does exactly that. 
Wanted it implemented in this app too
![Screenshot_20240613_080439](https://github.com/fast4x/RiMusic/assets/108865702/739ab38c-94cc-4cef-9c80-66a83f795b1a)

### Additional Context

Cache clear option after exiting the app

**Comment by fast4x** [comment]
Sorry, but isn't planned, RiMusic is a Music Player and not a downloader.

**Comment by Chickenshrimps** [comment]
Then plan it damn it

**Comment by cMattw** [comment]
> Then plan it damn it

what can you not understand in "RiMusic is a Music Player and not a downloader?"

**Comment by fast4x** [comment]
> Then plan it damn it

You don’t have to use RiMusic if you want to download pirate music.

**Comment by ikanakova** [comment]
> > Is it that hard to find issues where this is addressed and read that this will really never be in RiMusic? I have a feeling it's all illiterates asking for downloads...
> 
> I think it's high time fast pins an issue mentioning unplanned things and FAQs. This app is now reaching lots of people. And now issues will be created more often.

I agree and also make an issue template.
And maybe some volunteers to put issue tags - like duplicates and then the bot can close them :D
fast4x has better things to do than go through a million duplicate issues...
And there are the risk of losing feature requests with great ideas among them...

**Comment by fast4x** [comment]
People will never read even if the news gets on the front page. I like the idea of marking them as close is nice to collaborate for this.

**Comment by fast4x** [comment]
I ask you to also be kind to the lazy people because if they create a ticket it is because they have interest in the app.

**Comment by Chickenshrimps** [comment]
Yes
