### ISSUE TITLE
App never stops crashing after restarting device

### ISSUE THREAD

**Issue by Crowerade** [fast4x/RiMusic#2282]
### Steps to reproduce the bug

1. Open the app
2. Restart the device
3. Open the app
4. It crashes

### Expected behavior

The app should open normally.

### Actual behavior

The app crashes

### RiMusic version

0.6.38

### Android version

Android 13

**Comment by fast4x** [comment]
Acivate a debug in miscellanous setting, restart and try again.
After this, go to miscellaneous setting DEBUG  copy crash log and paste here, thanks.

**Comment by Crowerade** [comment]
> Acivate a debug in miscellanous setting, restart and try again.
> After this, go to miscellaneous setting DEBUG  copy crash log and paste here, thanks.

Do you mean in the app? I can't access it at all, it won't start...

**Comment by Crowerade** [comment]
I managed to get app files with ` adb ` from ` /data/data/it.fast4x.rimusic/ ` but I can't find a way to make the reinstalled app read them, everytime I insert ` databases ` it crashes again

**Comment by fast4x** [comment]
Insert database? You mean restore database and it crash after this? Restore is compatible only with ViMusic original...

**Comment by Crowerade** [comment]
No, I meant I copied the current ` databases ` folder that I found in ` /data/data/it.fast4x.rimusic/ `, uninstall the app and copy it in the newly created ` /data/data/it.fast4x.rimusic/ ` with ` adb ` on PC

**Comment by fast4x** [comment]
I don't think it work

**Comment by Crowerade** [comment]
I figured I had to uninstall the app since I can't launch it anyway but I want to keep ma data (especially my playlists and saved artists and albums)
