### ISSUE TITLE
[Feature]: Browse offline downloaded music tha same way it does for online music

### ISSUE THREAD

**Issue by ltcdatagonza** [fast4x/RiMusic#2284]
### Description

When you browse music, you can do it by artist, album, etc.
For downloaded offline and cached music, you only have a big list of tracks, and no way of choosing a downloaded album or an artist in particular.

### Suggested Solution

For example:
A checkbox that says "only offline music" and in the "music, songs, artists" sections only downloaded/cached music will appear.
I can only find the "cached" and "downloaded" option when "songs" is selected but it lists all the cached and downloaded songs mixed and no way to select them by artist or album.

**Comment by fast4x** [comment]
Album and artist page are online data, meanwhile cached and downloaded lists are only a list.
it can't show as albums or artists page.

if you want seen a downloaded song inside artist or album must go inside it.

**Comment by ltcdatagonza** [comment]
Oh, i thought cached/downloaded songs contained metadata and could be filtered by album and artist, since that information still appears.
Thanks for the answer.
