### ISSUE TITLE
bugs that I noticed

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#2289]
### Steps to reproduce the bug

should behave as usual

### Expected behavior

play next and playlists should work as usual

### Actual behavior

https://github.com/fast4x/RiMusic/assets/159836335/b6fa0f8a-72f4-44c2-bfb9-b23fe1fc36e7

When you enter the player again after a long period of time, nothing is loaded in the music folders unless you touch another

https://github.com/fast4x/RiMusic/assets/159836335/11bba062-0e9e-4555-a45c-5f8985712a6b

either in the queue within the player, or from the music list, the “play next” action cannot be performed

### RiMusic version

0.6.38

### Android version

Android 13

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion
Try custom version

**Comment by fast4x** [comment]
Fixed, available from version 0.6.40, but can download now the custom version with bug fixed.
https://github.com/fast4x/RiMusic/tree/master/customVersion
