### ISSUE TITLE
Syncing Spotify playlists

### ISSUE THREAD

**Issue by Pankajisyadav** [fast4x/RiMusic#2290]
### Description

Right now it has all the amazing features that I wanted and the ui is also very amazing. The flexibility of the design is amazing. But it would be even better if we could somehow sync our Spotify playlists on this app. That's all I need right now. Because there are so many songs that I have in my Spotify playlists so everytime I have to open Spotify to see which songs to listen to and then come back to this app to search and listen. It becomes a little inconvenient for users like me. It also becomes space taking that I have to keep Spotify too. I only want to keep this app on my phone for all music listening.

### Suggested Solution

Everything as above.

### Additional Context

I really hope this feature is added to this app other than that I don't think I need any other improvement in this it's already really good 😄

**Comment by ikanakova** [comment]
duplicity to #1801
