### ISSUE TITLE
[Feature]: Artists and Albums buttons in menu from search results

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#2291]
### Description

This is a extension of #1904

The artist and album only appear in menu if the song from search results is already added to favourites or cached. Or maybe more reasons I'm not aware of

![IMG_20240614_151736](https://github.com/fast4x/RiMusic/assets/99175083/5fcb67f8-cf16-4dd3-bc30-11a4777832e6)

### Suggested Solution

Make those two buttons appear normally. So we can jump to the album of a song or artist catalog directly

**Comment by fast4x** [comment]
Implemented, available from version 0.6.44

**Comment by NikunjKhangwal** [comment]
This doesn't seem to work. Is there any seperate setting for it?

![Screenshot_2024-07-20-13-55-43-088_it fast4x rimusic](https://github.com/user-attachments/assets/42c77c36-e74e-4709-807d-75d529216a24)
