### ISSUE TITLE
Play next not work 

### ISSUE THREAD

**Issue by ghyvpine** [fast4x/RiMusic#2296]
### Steps to reproduce the bug

I went to favorites , then I play one song, then I add a song to play next, but that song is not played

### Expected behavior

It should be like version 0.6.37 and earlier 

### Actual behavior

However, this still makes it difficult for me because I can't enter the song that will play next so I have to open my cellphone

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/143674859/d88e26fb-b54b-4a4b-a06e-fd814e9b360a

### Logs

I don't have one hehe

### RiMusic version

0.6.38 and 0.6.39

### Android version

Android 14 Qpr2 

### Additional information

There isn't any hehe

**Comment by claxcian** [comment]
Me too. Already reported [](https://github.com/fast4x/RiMusic/issues/2204)

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion
Try custom version

**Comment by ghyvpine** [comment]
Ok bro

**Comment by ghyvpine** [comment]
Works bro thanks very much

**Comment by claxcian** [comment]
Yes this works
--- 𝘾𝙡𝙖𝙪𝙙𝙞𝙤 𝘾𝙞𝙖𝙣𝙙𝙧𝙞𝙣𝙞 ---

Il Sab 15 Giu 2024, 19:14 ghyvpine ***@***.***> ha scritto:

**Comment by fast4x** [comment]
Great

**Comment by fast4x** [comment]
Fixed, available from version 0.6.40, but can download now the custom version with bug fixed.
https://github.com/fast4x/RiMusic/tree/master/customVersion
