### ISSUE TITLE
[Feature]: Make the position numbers in playlists optional

### ISSUE THREAD

**Issue by AstroLightz** [fast4x/RiMusic#2299]
### Description

The function to see the position of a song in a playlist is useful. However, I don't really need to use this feature, so it would be nice if I could toggle it in Settings.

Also, it is currently very slow. When I open playlists or the playlist menu, there is a delay of 0.5 to 1 second.

### Suggested Solution

Please add an option in the Settings to turn on or off the position number of a song in a playlist.

**Comment by fast4x** [comment]
Removed, available from version 0.6.40
