### ISSUE TITLE
More control options in the notification bar

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#23]
### Description

I would like to see the control options from screenshot 1 in the notification bar see screenshot 2.
![Screenshot_20231021-142416](https://github.com/fast4x/RiMusic/assets/103368536/c0ccb21f-d2b5-442b-8de6-f96c4eb78064)

![Screenshot_20231021-143237_One UI Home_1](https://github.com/fast4x/RiMusic/assets/103368536/c316935d-5623-47ce-b312-680a7daf89cf)

### Suggested Solution

If you listen to music and want to add the song just quickly to his eg: favorites. In this case, it would be a super relief and you would not have to go the detour to unlock the screen to gelagen in the APP.

**Comment by fast4x** [comment]
Implemented like button, available from version 0.6.17

**Comment by fast4x** [comment]
Available on version 0.6.16.1
