### ISSUE TITLE
Getting error "Couldn't find a playable audio format" when playing certain YouTube videos

### ISSUE THREAD

**Issue by sanga000** [fast4x/RiMusic#2301]
### Steps to reproduce the bug

Play certain songs that are YouTube videos, examples:
- https://music.youtube.com/watch?v=ACbSBiFo6-s
- https://music.youtube.com/watch?v=9DnXVDlxC-Q
- https://music.youtube.com/watch?v=JI0ptfrt5nU
- https://music.youtube.com/watch?v=G6eUtrOWUBs

Note that for the songs involved, they don't work for some uploaders while some other are fine despite being the exact same song with the exact same length. 

### Expected behavior

The song is played as normal

### Actual behavior

The song/video will not load and the message "Couldn't find a playable audio format" will appear.

### Screenshots/Screen recordings

![Screenshot_20240615_121646](https://github.com/fast4x/RiMusic/assets/26204896/53c62e42-fe49-4b10-a1b2-fdee8b9325e4)

### RiMusic version

0.6.39

### Android version

Android 13

### Additional information

This problem has been happening in the older versions as well, but more songs seem to be involved in the more recent versions.

I've found this old ticket over at ViMusic suggesting this happens to age restricted videos, however I've tried playing the videos on both YouTube and YouTube Music in an incognito browser without logging in and they're definitely playable.
https://github.com/vfsfitvnm/ViMusic/issues/1084

**Comment by fast4x** [comment]
Try to set audio quality automatic mode...

**Comment by sanga000** [comment]
Changing the quality to automatic doesn't seem to solve the issue

**Comment by fast4x** [comment]
Add link to song/video

**Comment by sanga000** [comment]
I've actually linked a few at the very top of the ticket. I used the YT music link but obviously they're YT videos.

I do remember some other songs having this problem as well but I can't remember which ones. I'll update if I can find them again

**Comment by fast4x** [comment]
Fixed, available from version 0.6.47
