### ISSUE TITLE
Piped playlist synchronization bug 

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#2302]
### Steps to reproduce the bug

After deleting a track/video from the Piped playlist, they are not deleted from the RiMusic playlist after synchronization. You have to delete them manually

### Expected behavior

After playlist was edited and some videos were removed, they had to be removed from RiMusic playlist

### Actual behavior

After synchronization, new songs added to RiMusic playlist, the deleted ones remain in the playlist. 

### RiMusic version

0.6.39

### Android version

Android 13

**Comment by fast4x** [comment]
Fixed, now sync remove deleted songs.. 
Available from version 0.6.40
