### ISSUE TITLE
Enqueue/Play next not working 

### ISSUE THREAD

**Issue by SacredGenius07** [fast4x/RiMusic#2306]
### Steps to reproduce the bug

1. Hold any song 
2. Click enqueue/play next 

### Expected behavior

Was supposed to add song to the queue or play the song after the one playing now.

### Actual behavior

Doesn't do anything.

### RiMusic version

v0.6.39 by fast4x

### Android version

12

**Comment by fast4x** [comment]
Do you have enabled Exclude songs with duration limit?

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion
Try custom version

**Comment by fast4x** [comment]
Fixed, available from version 0.6.40, but can download now the custom version with bug fixed.
https://github.com/fast4x/RiMusic/tree/master/customVersion
