### ISSUE TITLE
If transition effect is changing then it's changing theme also 

### ISSUE THREAD

**Issue by Gauravchaubey66** [fast4x/RiMusic#2319]
### Steps to reproduce the bug

1. Open setting 
2. Go to ui 
3. Change theme to material you
4. Then then transition effect to any other (expect selected one)

https://github.com/fast4x/RiMusic/assets/149640114/ffa8d9f7-7262-4a1e-bdc6-206b1ecd2293

### Expected behavior

There should be only change occurs in transition effect but it's changing the Theme also 

### Actual behavior

Changing trabsiton effect is also changing theme 

### Screenshots/Screen recordings

I tries with all combination and notices that it's only occurs with dynamic and material you thing.

### RiMusic version

0.6.39

### Android version

Android 13

**Comment by Gauravchaubey66** [comment]
Hey @fast4x here is another bug 🐛 which I found 😁

**Comment by twistios** [comment]
I am not 100% sure what this bug is about but the theme looks different on my device (maybe this is the point of it?). But I think I reproduced it on my physical device.

https://github.com/fast4x/RiMusic/assets/54811436/60d98b49-4a6e-4c13-b31a-7df7f7f77c4b

**Comment by Gauravchaubey66** [comment]
> I am not 100% sure what this bug is about but the theme looks different on my device (maybe this is the point of it?). But I think I reproduced it on my physical device.
> 
> https://github.com/fast4x/RiMusic/assets/54811436/60d98b49-4a6e-4c13-b31a-7df7f7f77c4b
> 
> This is using the "fresh" install on physical device via Android Studio.
> 

Thanks buddy actually it's a bug let me explain if we want to change theme that should change theme of the app in dark, light or whatever options that app has it has nothing to do with the animation chnage . and that thing is occurring here. I hope you get my point.

**Comment by twistios** [comment]
There is also a (strange) interaction between `material you` and `theme mode`. If you set `dark` theme and switch to different theme and then switch back it changes `theme mode` to `system`.

**Comment by twistios** [comment]
I just now tried to test this bug on my AVD but after suddenly it crashes/disappears/shuts down (the AVD).

**Comment by Gauravchaubey66** [comment]
> There is also a (strange) interaction between `material you` and `theme mode`. If you set `dark theme` and switch to different theme and then switch back it changes `theme mode` to `system`.

Yeah I noticed it too.😁 just open an another issue from your side.👍

**Comment by twistios** [comment]
I am now upgrading my emulator and other Android SDK and software tools, maybe it helps.

> I just now tried to test this bug on my AVD but suddenly it crashes/disappears/shuts down (the AVD).

**Comment by Gauravchaubey66** [comment]
> I just now tried to test this bug on my AVD but suddenly it crashes/disappears/shuts down (the AVD).

Crashes/disappears or shutdown maybe this is cause of AVD. I am unsure about it but I tried in 4 to 5 devices and it's occurring.

**Comment by twistios** [comment]
The errors I get are getting weirder by the minute. Finally my SDK and emulation was updated and then an unexpected reboot of my maschine happend when I was just starting the AVD again.

**Comment by twistios** [comment]
The effect of this bug depends on serval variables: Android System Theme (tested with light mode) and RiMusic Theme mode.
So here are two videos via my AVD.

1. Android Light mode and RiMusic Theme mode `system`
2. Android Light mode and RiMusic Theme mode `dark`

https://github.com/fast4x/RiMusic/assets/54811436/72a97cd3-7db9-48e3-9a3e-33e30b53934a

https://github.com/fast4x/RiMusic/assets/54811436/bd53aa84-2d50-4e86-b461-f413e5bdd7ad

**Comment by Gauravchaubey66** [comment]
https://github.com/fast4x/RiMusic/assets/149640114/aac17d04-a804-4317-8d7c-44691d79cfd9

**Comment by Gauravchaubey66** [comment]
https://github.com/fast4x/RiMusic/assets/149640114/d587b780-8bf7-4bf6-a93c-b00f24c7b6e2

**Comment by fast4x** [comment]
Fixed, available from version 0.6.44
