### ISSUE TITLE
[Feature]: Add Last.fm Scrobbling support

### ISSUE THREAD

**Issue by AlexIhmisviha** [fast4x/RiMusic#2320]
### Description

I don't know if there is a way to make it possible to scrobble directly within the app in RiMusic without having to resort to third-party tools like Pano Scrobbler.

### Suggested Solution

I imagine that Last.fm login could be accessed directly from the application or through a cookie, something like the defunct Freeza application did.

**Comment by Ao1Pointblank** [comment]
You can use the official lastfm app for this right now, but I would actually suggest the open source Pano Scrobbler

**Comment by Carter0108** [comment]
I'll piggyback off this and also suggest Listenbrainz scrobbling as well.

**Comment by fast4x** [comment]
Confirmed, it require login, for listening story yiu can use statistics and history inside RiMusic. 
Sorry, isn't planned login to payed service, you can use Piped https://piped video
