### ISSUE TITLE
Piped account 

### ISSUE THREAD

**Issue by Alanpa1** [fast4x/RiMusic#2322]
### Description

I want to know how to make pipe account and how to login

### Suggested Solution

Please help me with pipe account login system

**Comment by fast4x** [comment]
Explain better please, what you mean?

**Comment by KOLIWAN** [comment]
Go to this website https://piped.video/, sign up, choose an instance, and then use this credentials to log in to your Piped account in RiMusic.

**Comment by fast4x** [comment]
I thought he was talking about development 😂
