### ISSUE TITLE
[Feature]: Shazam or similar implemented

### ISSUE THREAD

**Issue by SerAn51** [fast4x/RiMusic#2327]
### Description

It would be a cool feature, but of course far from essential, to have an option like Shazam and then have the possibility to add the song to the favorites or into a playlist.

### Suggested Solution

Maybe with shazam API or another service that proposes directly the YT Music link.

**Comment by ikanakova** [comment]
This is a music listening app and it should stay that way. Soon you'll want RiMusic to be a browser or a text editor... If you want a music recognition app, you can download open source apps like Audile or Audire.

**Comment by SerAn51** [comment]
It was just an idea for a music-related thing, I thought it would be cool to not have to switch between apps. In fact I wrote that this is "far from essential", I didn't ask for something that has nothing to do with music like a text editor...
Btw, thanks for all the work.
