### ISSUE TITLE
"Play next" button/option not working

### ISSUE THREAD

**Issue by FireFlamesBoy** [fast4x/RiMusic#2328]
### Steps to reproduce the bug

1 In the "song" section of the main menu, click on a song in order to play it
2 long click/Click and hold in another song of the list.
3 The menu Will open 
4 Choose "Play next" option
5 Close the menu by clicking on the down arrow icon
6 Go to the next song by clicking on the "next" icon button
7 as you can notice on the screenshots i'm leaving available, the song playing next is not the one chosen by the user through the "play next" option in the menu opened when long clicking/clicking and holding on a song

### Expected behavior

When the user clicks the option, "play next", the app should leave the song in the next position of the queue

### Actual behavior

The song chosen with the "play next" button doesn't enter in the queue right after the current song
![1](https://github.com/fast4x/RiMusic/assets/172590670/ed98f51d-4389-44e5-bc66-c30cdb4dcb21)
![Imagem do WhatsApp de 2024-06-16 à(s) 14 09 23_cfe2a9a2](https://github.com/fast4x/RiMusic/assets/172590670/c60406c9-ab21-4e12-becf-7afb215e9ed4)
![Imagem do WhatsApp de 2024-06-16 à(s) 14 09 24_5fb1cb5f](https://github.com/fast4x/RiMusic/assets/172590670/905657ad-61f8-4c85-88e8-8df1d3422a2e)

![Imagem do WhatsApp de 2024-06-16 à(s) 14 09 24_f6c14d0f](https://github.com/fast4x/RiMusic/assets/172590670/19ac2fec-4e04-4892-9e24-716add6eb7e1)
![Imagem do WhatsApp de 2024-06-16 à(s) 14 09 25_8550184d](https://github.com/fast4x/RiMusic/assets/172590670/fd3c7b16-bb0a-4743-a3da-c3b4665da847)
![Imagem do WhatsApp de 2024-06-16 à(s) 14 09 25_f55b632a](https://github.com/fast4x/RiMusic/assets/172590670/0deb3dbf-7d55-4675-a86b-b21ac82ec808)
![Imagem do WhatsApp de 2024-06-16 à(s) 14 27 53_a36f9573](https://github.com/fast4x/RiMusic/assets/172590670/f6b4585b-0ba9-4c10-af9c-d9e4a45f34f0)

### RiMusic version

v0.6.39

### Android version

Android 12 (One Ui core 4.1) 

### Additional information

Samsung A01 - latest android update for this device

**Comment by FireFlamesBoy** [comment]
Hey guys, thanks for creating something so good and for free! you are amazing! 🙂

**Comment by fast4x** [comment]
Thanks, download custom version, play next and enqueue is fixed

**Comment by FireFlamesBoy** [comment]
omg! guys are so fast! not all heroes wear capes! :)
Thank you guys!

**Comment by fast4x** [comment]
Thanks to you

**Comment by Rajeshwarraj** [comment]
Installing That custom version doesn't work for me :(
