### ISSUE TITLE
Piped switch not selectable

### ISSUE THREAD

**Issue by DeadSecTr** [fast4x/RiMusic#2329]
### Steps to reproduce the bug

In settings,piped "button" is not clickable

### Expected behavior

That it works

### Actual behavior

Not working

https://github.com/fast4x/RiMusic/assets/90558189/783f96cc-6ce6-4037-9ae6-1bbeed914d42

### RiMusic version

Last Version

### Android version

Android 13

**Comment by fast4x** [comment]
What version of RiMusic? Download latest

**Comment by fast4x** [comment]
Fixed, available from version 0.6.40
