### ISSUE TITLE
can export but not import favorites

### ISSUE THREAD

**Issue by ghost** [fast4x/RiMusic#2332]
### Steps to reproduce the bug

the favorites screen has a button to export the list, but not a button to import those

### Expected behavior

i should be able to import favorites

### Actual behavior

importing the file on the playlist screen makes a new playlist instead of adding songs to favorites

### RiMusic version

0.6.36

### Android version

Android 10

**Comment by fast4x** [comment]
And for you it's a bug or feature request? sinceraly....

#1955 look... maybe would be a feature request? LOL...

**Comment by teacupmaps** [comment]
i filled in a form, and the tag "bug" here was added automatically

**Comment by fast4x** [comment]
No close please it will be developed

**Comment by teacupmaps** [comment]
you're right, it adds "enhancement if i use the other option
