### ISSUE TITLE
[Feature]: Auto-Download favorite tracks

### ISSUE THREAD

**Issue by Tre916** [fast4x/RiMusic#2334]
### Description

So, on a recent road trip something came up, quite frequently, losing signal completely kills the music and restarting a mix of all my favorite tracks is not so easy from the Android Auto interface, plus it ended up repeating songs I had already listened to on multiple occasions.

### Suggested Solution

I realized that I could potentially fix this by downloading all my favorite songs... but there's no easy way to do that. This would be great if un-favoriting something would remove the download too.

### Alternatives

Make it easier to manage (group add/remove songs) playlists and then I could possibly do this on a playlist.

**Comment by ikanakova** [comment]
I disagree with automatic downloads - a lot of people have expensive data and couldn't then mark anything as favorites on the data.
But if there is no download all button in favorites like in other playlists it would be nice if it was implemented.

**Comment by Tre916** [comment]
> I disagree with automatic downloads - a lot of people have expensive data and couldn't then mark anything as favorites on the data. 

I'd just like the option. I don't want to force anything on anyone. Sorry for not being clear. I had gone over it so many times in my head by the time I wrote it out I thought I had made that clear 😁

**Comment by ikanakova** [comment]
> > I disagree with automatic downloads - a lot of people have expensive data and couldn't then mark anything as favorites on the data. 
> 
> I'd just like the option. I don't want to force anything on anyone. Sorry for not being clear. I had gone over it so many times in my head by the time I wrote it out I thought I had made that clear 😁

I meant that it should be consistent throughout the app - download button (one song / all songs) / automatic download to cache when listening.

**Comment by fast4x** [comment]
I agree, automatica download not necessary, you have to click on single song or download all, but intentionally

**Comment by aneesh1122** [comment]
you have cached option in case you lose your internet connection. you can set the cache limit and all the songs you listen will be cached for you.

**Comment by Tre916** [comment]
> you have cached option in case you lose your internet connection. you can set the cache limit and all the songs you listen will be cached for you.

That's a bad solution to the issue. You can't pre-load a cache.

**Comment by aneesh1122** [comment]
> > you have cached option in case you lose your internet connection. you can set the cache limit and all the songs you listen will be cached for you.
> 
> That's a bad solution to the issue. You can't pre-load a cache.

You want to pre-load? Download the songs. You can download all of your favorite songs with one tap.

You want to have songs in case your internet is gone? Listen to the cached songs.

I don't even download songs because I always have cached songs when I'm offline

**Comment by Tre916** [comment]
> You want to pre-load? Download the songs. You can download all of your favorite songs with one tap.

How do I download all favorited songs with one tap?

**Comment by fast4x** [comment]
![Screenshot_2024-06-18-06-04-18-191_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/ac52a60c-2100-44b6-b8c8-ada4c93f2787)

**Comment by Tre916** [comment]
Is that in the latest version? Because I don't see that on mine, the f-droid version, v0.6.36.

**Comment by fast4x** [comment]
🥳
