### ISSUE TITLE
[Feature]: Move a song from Cache to local songs

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#2338]
### Description

It would be good if it would be possible to transfer a cached song to a local song.

### Suggested Solution

I don't know how caching of songs works in the app but it looks like it would be easy to convert it to a local file.

### Additional Context

Currently the download-button for cached songs does not exist.

**Comment by fast4x** [comment]
Not possible because cached is managed totally by player, not by RiMusic. Isn't export to external location. Remember, RiMusic isn't a music downloader but a simple streaming music player.

**Comment by aneesh1122** [comment]
Moving cached to downloaded would be possible? @fast4x

**Comment by fast4x** [comment]
Cached = downloaded but in non permanent location.

I'll check if possible to move from cache to cache

**Comment by fast4x** [comment]
Also... you can move cache location fro system to private and not will be cleaned by system.
![Screenshot_2024-06-17-19-44-28-825_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/0f93d676-7c6b-4c5e-aa6e-80fff12d307d)

**Comment by aneesh1122** [comment]
> Also... you can move cache location fro system to private and not will be cleaned by system. ![Screenshot_2024-06-17-19-44-28-825_it.fast4x.rimusic.jpg](https://private-user-images.githubusercontent.com/1484476/340403784-0f93d676-7c6b-4c5e-aa6e-80fff12d307d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDczOTcsIm5iZiI6MTcxODY0NzA5NywicGF0aCI6Ii8xNDg0NDc2LzM0MDQwMzc4NC0wZjkzZDY3Ni03YzZiLTRjNWUtYWE2ZS04MGZmZjEyZDMwN2QuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMTc1ODE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGUzNDVhNTAyOTYyNDEzZjNmYjYyNWFhMjEyNTAzMzI1MjYzZmFhNzE0YzQwYjliZmNhMmQ1MmY2NGExZjgxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VSUzk8LsCnXb26GRI7MWeVL0bu-H70BxvnN8T3BeATI)

the main difference for me between cached and downloaded is you can delete individual downloaded songs but you can't do that with cache. that's why I thought it would be a good idea to be able to convert cached to downloaded.
