### ISSUE TITLE
[Feature]: Premium Quality for premium accounts

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#2342]
### Description

Because there is no way to sign in with a premium account, premium users have to listen to standard qualities 

### Suggested Solution

Add the ability to sign in as premium

**Comment by OrangeZXZ** [comment]
Since you have the premium subscription, you can use YouTube Music.

RiMusic will not have YouTube account support because the whole concept is to listen without it. Plus, Google doesn't like apps that let you use their account (like Snaptube).

**Comment by VINULA2007** [comment]
> Since you have the premium subscription, you can use YouTube Music.
> 
> RiMusic will not have YouTube account support because the whole concept is to listen without it. Plus, Google doesn't like apps that let you use their account (like Snaptube).

K
Kinda drifted away from rimusic cause of it so just wanted ask if it's possible 😜

**Comment by OrangeZXZ** [comment]
> > Since you have the premium subscription, you can use YouTube Music.
> > 
> > RiMusic will not have YouTube account support because the whole concept is to listen without it. Plus, Google doesn't like apps that let you use their account (like Snaptube).
> 
> K
> Kinda drifted away from rimusic cause of it so just wanted ask if it's possible 😜

There is no problem in asking. I just wanted to inform you that it is very unlikely. If you have the money to support streaming services, then go for it!

**Comment by fast4x** [comment]
Not planned 🥳😂

**Comment by VINULA2007** [comment]
> > > Since you have the premium subscription, you can use YouTube Music.
> > > RiMusic will not have YouTube account support because the whole concept is to listen without it. Plus, Google doesn't like apps that let you use their account (like Snaptube).
> > 
> > 
> > K
> > Kinda drifted away from rimusic cause of it so just wanted ask if it's possible 😜
> 
> There is no problem in asking. I just wanted to inform you that it is very unlikely. If you have the money to support streaming services, then go for it!

It's just super cheap here
Only about 2 buck for both YouTube and YouTube music premium
