### ISSUE TITLE
Make the remaining timeline bar transparent 

### ISSUE THREAD

**Issue by Toiletmason** [fast4x/RiMusic#2345]
### Description

![ResizedImage_2024-06-17_13-02-06_3445](https://github.com/fast4x/RiMusic/assets/23698116/23501f1f-ec68-4213-9b5a-7b453a44b77b)

### Suggested Solution

Make it so that the bar is the same color a the background until time has elapsed which will then fill in the accent color.

### Additional Context

![ResizedImage_2024-06-17_16-04-42_4207.jpg](https://github.com/fast4x/RiMusic/assets/23698116/b0e200fd-08b0-43d6-be8b-bec03d46e820)

**Comment by dAtA-TRoN** [comment]
🎶Optional please!🎶

**Comment by aneesh1122** [comment]
@fast4x this was implemented in the last update. Close this
