### ISSUE TITLE
Missing featured playlist like yt music

### ISSUE THREAD

**Issue by aabensurc** [fast4x/RiMusic#2346]
### Description

Sería bueno que agreguen "featured playlists" así como las de la aplicación YouTube music, la aplicación "harmony music" sí las tiene, pero yo prefiero usar RiMusic

### Suggested Solution

Agreguen esas listas porfavor

**Comment by fast4x** [comment]
What's featured playlist?

**Comment by aabensurc** [comment]
I mean that the 'quick pick" screen shows less original yt music playlists than the users public ones. However, these yt playlists appears inside the genre items, so there'll no problem anymore. But, when I look for those yt playlists in the search bar, there are only user's playlists and I don't see the yt ones. I want to save them to my favorites playlists from that search screen. but I can't do it.

**Comment by fast4x** [comment]
I'll check it

**Comment by aabensurc** [comment]
Thank you, my friend

**Comment by aabensurc** [comment]
My friend, after a couple of hours using this app, a new tab("featured") appeared on the search screen with those yt playlist I mentioned in the last comment. Thank you. But it would be better if all the search results I'm looking for(songs, albums, artists, users playlists, yt playlist) appeared on a single screen as in Spotify and YouTube. Do you know what I mean? The other app "harmony music" have the same feature but I don't want to use it.
![Screenshot_2024-06-17-17-36-28-419_com anandnet harmonymusic](https://github.com/fast4x/RiMusic/assets/31977653/8b63ee9a-26bd-43c5-a30d-a1602d151c10)
![Screenshot_2024-06-17-17-36-39-840_com anandnet harmonymusic](https://github.com/fast4x/RiMusic/assets/31977653/9ccd6a8f-27fa-4b0f-8c4b-a53e3027b272)

**Comment by fast4x** [comment]
Do not always refer to other applications, discover RiMusic, you can get the same result simply by moving the menu up,down, right, left from the UI settings.
