### ISSUE TITLE
Login function 

### ISSUE THREAD

**Issue by Alisuuu** [fast4x/RiMusic#2348]
### Description

I love using this app, but due to the lack of a login function, I recommend others to friends, if they can add this function. Thanks 

### Suggested Solution

The function is useful for listening to YouTube playlists and having the history maintained in the app

### Alternatives

I don't know well

**Comment by JeePopuwu** [comment]
fast you will have to put under the title of the app that it will not get into accounts

**Comment by fast4x** [comment]
Hi, unique account login is PIPED, sorry.
