### ISSUE TITLE
Option to access any folder 

### ISSUE THREAD

**Issue by Johnzkn** [fast4x/RiMusic#235]
### Description

[Hello, I want to ask you to add the option to access the folders where the songs are separated within folders, the option to listen to the downloaded songs are completely random.](url)

### Suggested Solution

I need access to folders to listen to the songs downloaded in folders, each folder I have has different musical genres, so when I listen to my songs offline they are all messed up. I thank you for your attention ❤️

**Comment by fast4x** [comment]
Hi, thank you for your request.
Access to folders requires special permissions to read all folders/files on the device. 

I can try to add functionality so that I can be turned on or off. If enabled by settings, permissions are required. So who doesn’t need it, doesn’t activate it. Do you like it?

**Comment by Johnzkn** [comment]
It would be perfect that way, I like being able to listen to the downloaded songs.

**Comment by Johnzkn** [comment]
It would be perfect like that, I really like listening to downloaded music.

**Comment by OrangeZXZ** [comment]
I think that @fast4x could make possible to add songs from device into playlist that way we can separate them

or maybe just show the folders in the downloaded section as category

**Comment by fast4x** [comment]
Access any folder require rewrite on ondevice songs...

**Comment by sayyid5416** [comment]
@fast4x I suppose this has already been implemented

**Comment by fast4x** [comment]
not

**Comment by fast4x** [comment]
Not planned, it require dangerous permissions
