### ISSUE TITLE
Put the application on Accrescent

### ISSUE THREAD

**Issue by MXC48** [fast4x/RiMusic#2355]
### Description

Could you please put Rimusic on Accrescent? 
This store is very handy for updates, as they can be done in the background without any user action :)
![Screenshot_20240618-140713_Accrescent](https://github.com/fast4x/RiMusic/assets/123580315/f332f4fa-3ab4-4438-becf-2f26acf52c2f)
Accrescent app on android.

### Suggested Solution

Put the application on Accrescent : https://accrescent.app/

**Comment by fast4x** [comment]
Interesting, I'll check it, thanksfor suggestion

**Comment by fast4x** [comment]
i can't create a developer profile, it's only for invite

**Comment by MXC48** [comment]
> i can't create a developer profile, it's only for invite

You must send a request to this e-mail address: contact@accrescent.app

**Comment by fast4x** [comment]
Ok i've sent request now.

**Comment by imgalaxyhunter** [comment]
complete, can be closed
