### ISSUE TITLE
[FEATURE]: Listen together 

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#2356]
### Description

Friends who join a listen together can listen and add songs to the queue together, whether in-person or virtually.
![Screenshot_2024-06-18-15-20-33-751_com spotify music](https://github.com/fast4x/RiMusic/assets/63956787/f5881a08-b27f-4201-84ac-1f101bfeb5d8)

### Suggested Solution

Add listen together option like Spotify, but for free
When creating the app ask an username, for the host maybe the app can create an host session locally and send information to the other client ?

**Comment by fast4x** [comment]
An intermediate server is requested, not planned.

**Comment by NEVARLeVrai** [comment]
> An intermediate server is requested, not planned.

We can't Host locally on the one creating the session?, well after that it's not serious but it could be something interesting in the future

**Comment by NEVARLeVrai** [comment]
> An intermediate server is requested, not planned.

We can't Host locally on the one creating the session?, well after that it's not serious but it could be something interesting in the future

**Comment by fast4x** [comment]
Yes, the local server might work but in order to connect it would need an external service to the network and would be unsafe.
