### ISSUE TITLE
Now playing UI suggestion

### ISSUE THREAD

**Issue by Shivamhobbyist** [fast4x/RiMusic#236]
### Description

Plz remove all UI elements outside the redline on ss. examples  like Spotify and yt music
Dont make app edge to edge nowadays smartphone became longer and wider so its slightly hard to use phones with one hand

### Suggested Solution

![Screenshot_20231217_082917_@Shivam_hobbyist](https://github.com/fast4x/RiMusic/assets/78287172/9804999f-03ac-4b08-abdd-f562f6d10930)
![Screenshot_20231217_083129](https://github.com/fast4x/RiMusic/assets/78287172/8208180c-820f-423c-8932-1b54f044e062)

### Additional Context

And improve colours of faded song tittle and pause play button

**Comment by fast4x** [comment]
Interesting, thanks for the suggestion

**Comment by OrangeZXZ** [comment]
I remember suggesting one time to add space to edges because it is hard to reach with rounded borders on my phone but that didn't get added i look forward for this feature

**Comment by fast4x** [comment]
I not remember, ok

**Comment by fast4x** [comment]
Implemented, available from version 0.6.15
