### ISSUE TITLE
Fix Player UI

### ISSUE THREAD

**Issue by halith-smh** [fast4x/RiMusic#2361]
### Description

The Player UI looks broken, Kindly try to match like Spotify. The like icon is too small to interact with it.

We are expecting clean ui like this: 
![Screenshot_2024-06-19-10-19-01-12_0438eb925998df20b3482ec25499d226](https://github.com/fast4x/RiMusic/assets/126736160/a3396adf-f771-4b46-844b-985add1a9642)

Not this:
![Screenshot_2024-06-19-10-19-42-53_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/126736160/beebe0fa-6612-41eb-8d33-6a66730c0d18)

### Suggested Solution

Improve UI similar to Spotify player.

### Additional Context

I would also like to have **media player** icon in which device I am playing the song like Spotify.

**Comment by fast4x** [comment]
Change look by settings, select essentials or modern controls/info/background.

**Comment by halith-smh** [comment]
Is there is an way to import Spotify Playlists?

**Comment by fast4x** [comment]
Change look by settings, select essentials or modern controls/info/background.Not

**Comment by fast4x** [comment]
> Is there is an way to import Spotify Playlists?

Not

**Comment by fast4x** [comment]
You can export with external tools and import to RiMusic with file format that find in  wiki faq page

**Comment by KOLIWAN** [comment]
Why would RM have to look like Spotify? Spotify doesn't have the best UI at all. RM isn't perfect too but it's deeply customizable, not every player can offer something like this

**Comment by drago-bit** [comment]
There is nothing that looks broken in the UI. Besides, you can customise it in the settings. And still you want it to look like Spotify, better stick to that itself.
