### ISSUE TITLE
Play button bug

### ISSUE THREAD

**Issue by sebbekm** [fast4x/RiMusic#2367]
### Steps to reproduce the bug

1. Go to settings
2. Disable the play button

### Expected behavior

There should be no button. Only the play symbol?

### Actual behavior

There's still a button but black instead of grey

### Screenshots/Screen recordings

![Screenshot_20240620-110934](https://github.com/fast4x/RiMusic/assets/99768781/aa372c96-acf2-4c1c-bac6-b157b965b348)

### RiMusic version

0.6.39

### Android version

Android 13

### Additional information

Edit: This bug occurs only when using one of the black themes

**Comment by tayuriv** [comment]
![Screenshot_2024-06-20-15-18-18-285_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/121893457/cca84ac1-ca58-40c3-a98e-54cd9ec5e657)
I have similar problem

**Comment by aneesh1122** [comment]
How do you disable the play button? There is no such option.

You can select the 'disabled' button and it will remove the square.

![Screenshot_2024-06-20-16-49-07-135_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/1044aaaf-68b8-4228-8056-76e5cbda5417)

![Screenshot_2024-06-20-16-49-22-719_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/0e78f9da-f9bc-4fbb-8520-564a803ad67f)

I've implemented it myself so I'm sure it works.

**Comment by sebbekm** [comment]
I did some testing and the bug is only there when using one of the black themes!

**Comment by aneesh1122** [comment]
> I did some testing and the bug is only there when using one of the black themes!

Could you be more specific? Like which theme mode and which theme has this problem.

Maybe I'll be able to fix it

**Comment by sebbekm** [comment]
> > I did some testing and the bug is only there when using one of the black themes!
> 
> Could you be more specific? Like which theme mode and which theme has this problem.
> 
> Maybe I'll be able to fix it

Modern black and Pure black

**Comment by aneesh1122** [comment]
> > > I did some testing and the bug is only there when using one of the black themes!
> > 
> > 
> > Could you be more specific? Like which theme mode and which theme has this problem.
> > Maybe I'll be able to fix it
> 
> Modern black and Pure black

Fixed

> ![Screenshot_2024-06-20-15-18-18-285_it fast4x rimusic](https://private-user-images.githubusercontent.com/121893457/341373632-cca84ac1-ca58-40c3-a98e-54cd9ec5e657.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4OTE2MjAsIm5iZiI6MTcxODg5MTMyMCwicGF0aCI6Ii8xMjE4OTM0NTcvMzQxMzczNjMyLWNjYTg0YWMxLWNhNTgtNDBjMy1hOThlLTU0Y2Q5ZWM1ZTY1Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQxMzQ4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDBlYjQ1M2E1Zjc4ZGU0N2NiZmU4YTY0NTY0NjFmOGJlOWZjYTJkMjRmY2ViZGJkMmFlNTk5ZGE2MTcwNzM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kkBTVQLYGYQobESHF9AjOh8stJ4kh2j_fbQ5g_4g2bg) I have similar problem

That's how it is supposed to work.
