### ISSUE TITLE
Add "Bengali" Language in the crowdin site for bengali language contribution

### ISSUE THREAD

**Issue by AnnNaserNabil** [fast4x/RiMusic#2372]
### Description

There is no option for Bengali language in the crowdin to translate the resources in Bengali language. Bengali is one of the most spoken language. I want to contribute to this section. if its added, it would be great.

### Suggested Solution

Add a branch in crowdin for Bengali language.

**Comment by fast4x** [comment]
Hi, added, now you can start your translation. Thanks

**Comment by AnnNaserNabil** [comment]
All translation has been made.

**Comment by AnnNaserNabil** [comment]
Hello,
I am glad to tell you that I have completed all the Bengali translation
work and Would love it if you make it available for the public. I was
wondering if I can contribute more on this project?

I am working as an data science enthusiastic on my own. If RiMusic can
benefit me the analytics and future integration of some features by having
done some user and background location of the devices and all the state of
listening time and stuffs.

Cheers

Ann Naser Nabil

**Comment by fast4x** [comment]
Hi, congratulations on your work, it’s very interesting. RiMusic does not plan to "track" usage data, it is a free app that does not collect any kind of data about users.

You can contribute the way you like, you can develop, you can create wiki documentation pages, you can propose changes on RiMusic, you can look at the internal statistics section at RiMusic and maybe check if they are okay, what they might show more than now or change everything. 

Thanks for your support, my friend.

**Comment by AnnNaserNabil** [comment]
Thanks. I do use this on the regular basis, have you seen in the QUICK
PICKS >> MOOD AND GENERE  There are many missing songs. is it api issue or
anything elese?
