### ISSUE TITLE
Saved albums not loading at library

### ISSUE THREAD

**Issue by Davutha** [fast4x/RiMusic#2373]
### Steps to reproduce the bug

1. save an album
2. open the album section
3. select any album 
4. close the album 

### Expected behavior

the album art and name should load correctly at the menu

### Actual behavior

the album art gets bugged even when entering the album again
![Screenshot_20240620-122921](https://github.com/fast4x/RiMusic/assets/68203036/9ad729a6-8bb5-494c-b778-0d589c7c68d9)
![Screenshot_20240620-122848](https://github.com/fast4x/RiMusic/assets/68203036/298b8724-0a38-4ccb-8651-ce7a2415c4ae)

### RiMusic version

0.6.39

### Android version

Android 9

**Comment by twistios** [comment]
I am sorry, it looks like you were (I think) the first one to report this issue.

If it is the problem about the youtube API change then there will be a fix available today at v0.6.40.1 according to fast4x.
