### ISSUE TITLE
[Feature]: Confirmation before deletion of downloaded songs

### ISSUE THREAD

**Issue by nvllz** [fast4x/RiMusic#238]
### Description

I think having to confirm before deleting downloaded songs (tapping the download button on the already downloaded song) would prevent unintentional actions. There will probably only be a few times when you want to delete a song, and it's risky not to ask for confirmation for people with low mobile data plan or slow connection.

### Suggested Solution

Show a dialog with yes/no buttons asking if the user is sure they want to delete the downloaded song(s). If you have doubts that people would like it this way, make it a switch in the preferences.

**Comment by fast4x** [comment]
Yes, it is correct what you say, thank you for the evaluation.

**Comment by fast4x** [comment]
Implemented on remove all downloaded songs button.
Available from version 0.6.15
