### ISSUE TITLE
Carátulas álbumes u singles

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#2380]
### Steps to reproduce the bug

1. Ir a algun álbum o single.
2. Reproducirlo.
3. La carátula no carga correctamente.

### Expected behavior

1. Ir a un álbum o single.
2. Reproducir.
3. Las carátulas no desaparecen.

### Actual behavior

Cuando me dirijo a dicho apartado la carátula de el álbum o single desaparecen (Incluso si no está descargado desaparecen sin razón alguna, una vez descargado también realiza está acción)

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/170132242/df54ae28-649b-488d-8dff-4770ae07115b

### Logs

N/A

### RiMusic version

0.6.39

### Android version

Android 14

### Additional information

Necesito orientación para agregar carátulas manualmente, en si noté el apartado de editar portada pero he agregado enlaces de el álbum oficial desde Google, YTMusic o Spotify pero no realiza está acción correctamente, hace dos actualizaciones realiza este detalle y realmente me es molesto, agradecería mucho que la siguiente actualización arreglen este problema o que agreguen un apartado en el cual se pueda agregar una portada desde galería para que sea mas facil, gracias!

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
