### ISSUE TITLE
queue crash when locking screen or changing application

### ISSUE THREAD

**Issue by gituser23234235234887** [fast4x/RiMusic#2381]
### Steps to reproduce the bug

if I lock screen or change application, and then come back to rimusic, and then again lock screen or change application, the queue will crash, I can avoid this by pausing the music and playing it again.
This does not happen every time, and I do not know how much time have to have passed, but I have had this happen to me many times.

### Expected behavior

the music will continue playing in background

### Actual behavior

the music stops, cannot start it again or go to next or previous song in queue, or pull up the queue list. have to start a new queue.

### RiMusic version

0.6.39 fdroid

### Android version

14

**Comment by Ao1Pointblank** [comment]
seems to be the same as issues #2538 #2580 #2566 #2560 #2534
trying to recreate this while plugged into my PC and running ADB, i got several "pauses" that stopped the music. twice in the background, once while the app was in foreground. Perhaps fix https://github.com/fast4x/RiMusic/commit/7b7bae8f64543fe27bb882e1abccb4461e0ecd4c did resolve the issue of the queue being deleted, however the music does still hiccup a bit. 

adb logcat results (filtered with | grep "it.fast4x.rimusic"):
https://gist.github.com/Ao1Pointblank/b310d49fad8e14b4161327d1a1c8a16a
