### ISSUE TITLE
Playlist doesn't load

### ISSUE THREAD

**Issue by etken4** [fast4x/RiMusic#2388]
### Steps to reproduce the bug

1. Go to search 
2. Go to a random playlist
3. When clicked on a playlist it shows nothing

### Expected behavior

Playlist content should show

### Actual behavior

Playlist doesn't load

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/133025063/3eae2a3c-d6db-47a8-b0cd-22207c281848

![Screenshot_20240621_212839](https://github.com/fast4x/RiMusic/assets/133025063/38d582a0-225b-4178-869b-adcaea90c7f5)

### RiMusic version

0.6.39

### Android version

Android 14

**Comment by chris122380** [comment]
I am experiencing the same problem. I tried to import one of my new YouTube music playlists and end up with the same thing. 
![Screenshot_20240621-125405](https://github.com/fast4x/RiMusic/assets/2205798/f45dfb35-63d1-4d6f-9094-f03723fac956)

I wonder if this playlist sync issue is also related to this bug #2366. I am experiencing both of these issues.

**Comment by fast4x** [comment]
Is a changed api in Youtube Music, all app like RiMusic have same problem.

**Comment by chris122380** [comment]
Still an issue in 0.6.40.

**Comment by chris122380** [comment]
> Is a changed api in Youtube Music, all app like RiMusic have same problem.

It's not an issue with Newpipe or Harmony Music so it must be an issue with how RiMusic pulls the playlist.

**Comment by NikunjKhangwal** [comment]
Sharing #2064 in case it is related

**Comment by nutzlichsein** [comment]
same problem here. RiMusic 0.6.39![Screenshot_20240622-133904_RiMusic.png](https://github.com/fast4x/RiMusic/assets/141796411/a115e22f-c73c-4b36-85cc-a509c9ad2547)

**Comment by fast4x** [comment]
Work in progress, YouTube music have changed interface in albums and playlists. All app like RiMusic have same bug, I'm working on it.
