### ISSUE TITLE
Sleep timer values are out of order

### ISSUE THREAD

**Issue by nvllz** [fast4x/RiMusic#239]
### Steps to reproduce the bug

1. Play a song
2. Three-Dot Menu > Sleep Timer
3. Set the value greater than 25 min (which will be 1h 0m instead of 25+5=30m)
4. Start the timer

### Expected behavior

A sleep time value should increase by 5 to 60 (which changes to 1h 0m).

### Actual behavior

Now the app changes 30 minutes of sleep time to 1 hour. But this label value is misleading, and 1h 0m on a label results in 30 minutes of sleep.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/110673332/85e3ad29-b1df-40e3-8895-f857766ea8f7

### RiMusic version

0.6.13

### Android version

Android 13

**Comment by fast4x** [comment]
Thanks for your report.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.14
