### ISSUE TITLE
All songs dissapear in any album

### ISSUE THREAD

**Issue by User679292662** [fast4x/RiMusic#2390]
### Steps to reproduce the bug

1.-Open RiMusic and go to any album (Downloaded or online) 
2.-See the error
![Screenshot_20240621-122632](https://github.com/fast4x/RiMusic/assets/173496502/13fc91a1-282d-4c69-8da9-14742e75e46d)

### Expected behavior

The albums would open correcly

### Actual behavior

All songs dissapear in all the albums

### RiMusic version

0.6.39

### Android version

Android 11 Go

**Comment by chris122380** [comment]
Looks like a d to duplicate issue #2388

**Comment by fast4x** [comment]
Is a changed api in Youtube Music, all app like RiMusic have same problem.

**Comment by aneesh1122** [comment]
> Is a changed api in Youtube Music, all app like RiMusic have same problem.

Man you have no idea how much relieved I'm after hearing this.

I thought I changed something in the code which caused this 😅

**Comment by chris122380** [comment]
> Is a changed api in Youtube Music, all app like RiMusic have same problem.

It's not an issue with Newpipe or Harmony Music so it must be an issue with how RiMusic pulls the playlist.

**Comment by fast4x** [comment]
Work in progress, YouTube music have changed interface in albums and playlists. All app like RiMusic have same bug, I'm working on it.

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
