### ISSUE TITLE
Error in pitch black + dynamic mode

### ISSUE THREAD

**Issue by odamaasio** [fast4x/RiMusic#2391]
### Steps to reproduce the bug

https://github.com/fast4x/RiMusic/assets/169945653/6402f70e-e473-46ee-bb2e-fedcf37310ec

### Expected behavior

Pitch black mode should only be black with dynamic color, but when I leave the app it is not pitch black.

### Actual behavior

ㅤ

### RiMusic version

0.6.39

### Android version

Android 11

**Comment by fast4x** [comment]
Fixed, available from version 0.6.44
