### ISSUE TITLE
[Feature]: Customize cover for playlist

### ISSUE THREAD

**Issue by odamaasio** [fast4x/RiMusic#2392]
### Description

In almost all music services the user has the power to put an image of their storage as cover of a playlist created by him. This makes something special for the user, not to mention helping to differentiate the playlist from others.

### Suggested Solution

The power of the user to put an image from their storage as a cover of a playlist created by him.

**Comment by odamaasio** [comment]
@fast4x any new?

**Comment by fast4x** [comment]
Not
