### ISSUE TITLE
The album music list is no longer displayed.

### ISSUE THREAD

**Issue by chatinteligence** [fast4x/RiMusic#2394]
### Steps to reproduce the bug

The album music list is no longer displayed.
Failed a few moments ago in the previous version, 6.39, I thought it was part of the new update, but it remained the same.

https://github.com/fast4x/RiMusic/assets/147566193/eba913ff-6639-4ff3-8566-5c5ae4d9ecb1

### Expected behavior

The album music list is no longer displayed.
Failed a few moments ago in the previous version, 6.39, I thought it was part of the new update, but it remained the same.

### Actual behavior

The album music list is no longer displayed.
Failed a few moments ago in the previous version, 6.39, I thought it was part of the new update, but it remained the same.

### RiMusic version

Ri Music v0.6.39 y v0.6.40

### Android version

Android 14

**Comment by twistios** [comment]
This is a duplicate issue of #2388.

**Comment by fast4x** [comment]
Work in progress, YouTube music have changed interface in albums and playlists. All app like RiMusic have same bug, I'm working on it.

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
