### ISSUE TITLE
Reproducir álbum o single 

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#2397]
### Steps to reproduce the bug

1. Ir a un álbum o single.
2. Seleccionar cualquier álbum o single.
3. Desaparece portada.
4. No carga.

### Expected behavior

1. Ir a un álbum o single.
2. Seleccionar cualquier álbum o single.
3. No desaparecen portadas.
4. Carga correctamente 

### Actual behavior

Cuando me dirijo a algún álbum o single la portada desaparece y se queda congelado, no carga ninguna canción de dicho álbum o single.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/170132242/084cab81-ff13-41c8-9f4d-3b5554f8b867

### Logs

N/A

### RiMusic version

0.6.40

### Android version

Android 14 

### Additional information

Por favor mejoren estos detalles, es el mejor reproductor de música libre que he conocido, agradecido con todo lo que han ofrecido todo este tiempo pero estás acciones son molestas desde hace una actualización, gracias! 😔

**Comment by User679292662** [comment]
También me ocurre lo mismo,el creador dijo que eso está pasando porque Youtube Music cambió la API .

**Comment by Alaneeedu** [comment]
Ojalá se solucione este error lo más pronto posible:(

**Comment by fast4x** [comment]
Work in progress, YouTube music have changed interface in albums and playlists. All app like RiMusic have same bug, I'm working on it.

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
