### ISSUE TITLE
New Expanded Player view doesnt work

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#2399]
### Steps to reproduce the bug

Click the icon in player

### Expected behavior

I dont know

### Actual behavior

![Screenshot_20240622-041250](https://github.com/fast4x/RiMusic/assets/45221211/4b7371e8-687c-4525-bc45-64cab631e1ff)

### RiMusic version

0.6.40

### Android version

Android 11

**Comment by aneesh1122** [comment]
what doesn't work? expanded player brings down all the elements so that you can have cleaner view and bigger window for lyrics. post a screen record to explain your bug.

**Comment by faustaahmad** [comment]
The lyrics window doesnt get bigger as the thumbnail doesnt get bigger too
As you can see on the screenshot is the state after I click/activate Expanded Player, it's self explanatory

Landscape orientation is worse
![Screenshot_20240622-051704](https://github.com/fast4x/RiMusic/assets/45221211/d6a17830-1434-4e80-b382-ddefd482731b)
![Screenshot_20240622-051651](https://github.com/fast4x/RiMusic/assets/45221211/bee2beb4-187b-4065-af63-431f0a4cd36a)

**Comment by aneesh1122** [comment]
Disable 'show thumbnail' or disable 'show thumbnail' for lyrics' and then you'll have the  bigger lyrics window.

The lyrics window won't get bigger if you're using the old method.

Regarding landscape, it's not designed for that so I will disable it for landscape mode.

**Comment by faustaahmad** [comment]
Disabling "show thumbnail" make it works
But it looks worse with the shadow for me, perhaps add options to customize the shadow weight (I prefer it to be disabled though)

Here more screenshots of the behaviours
<table><tr>
<td colspan=2><img src="https://github.com/fast4x/RiMusic/assets/45221211/c6615b5e-3066-43d5-8080-f65969238afa"></img></td>
</tr><tr>
<td colspan=2><img src="https://github.com/fast4x/RiMusic/assets/45221211/6559d2ff-f7ff-45f8-b02b-d1f8961a31e5"></img></td>
</tr><tr>
<td colspan=2><img src="https://github.com/fast4x/RiMusic/assets/45221211/7aa74597-5880-4db8-8ea1-9f74f21c7587"></img></td>
</tr><tr>
<td><img src="https://github.com/fast4x/RiMusic/assets/45221211/d67bf6bc-69a1-4437-8398-22e6411f0217"></img></td>
<td><img src="https://github.com/fast4x/RiMusic/assets/45221211/eb60a713-5246-4196-b19e-bc1160be72ca"></img></td>
</tr></table>

Honestly, the modern Control style (non transparent navbar) should be transparent when background color are dynamic/blurred
But, I dont mind at all nor opening new issue for it

**Comment by aneesh1122** [comment]
Disable 'show thumbnail' or disable 'show thumbnail' for lyrics' and then you'll have the  bigger lyrics window.

The lyrics window won't get bigger if you're using the old method.

Regarding landscape, it's not designed for that so I will disable it for landscape mode.

What theme are you using? This is what I'm getting here

![Screenshot_2024-06-22-04-33-37-905_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/45353488/0a98195d-2da8-4015-b443-99c7014d7304)

Not the same song but I don't know which song you're listening too but the text's color shouldn't change.

**Comment by faustaahmad** [comment]
Here's the song
https://music.youtube.com/watch?v=c2UO1f1Lmz0
My font size is small, perhaps that's why the shadow looks wierd

**Comment by aneesh1122** [comment]
> Here's the song
> https://music.youtube.com/watch?v=c2UO1f1Lmz0
> My font size is small, perhaps that's why the shadow looks wierd
> I enabled "Show Thumbnail" for now, since it will disable shadow on the font style

Okay I understood what's the problem.

![Screenshot_2024-06-22-04-47-20-602_it.fast4x.rimusic.debug-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/cb956bc9-9997-409d-91c0-f55d520666fe)

Do this.

Cover color is not correctly assigned.

**Comment by aneesh1122** [comment]
![Screenshot_2024-06-22-05-03-03-732_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/45353488/81ab6769-2225-484e-b1ee-5871c0550cfb)

Disable thumbnail, enter landscape mode and enable lyrics. This is what you'll get.

**Comment by faustaahmad** [comment]
Still, it's just uncomfortable for me
The shadow just too thick

**Should I make new feature request & issue?**
Related to shadow when "Show Thumbnail" disabled, I mean this
Translated lyrics & text in the entire player doesnt respect the typeset (Lyrics color)

**Comment by aneesh1122** [comment]
> Still, it's just uncomfortable for me
> The shadow just too thick
> 
> **Should I make new feature request & issue?**
> Related to shadow when "Show Thumbnail" disabled, I mean this
> Translated lyrics & text in the entire player doesnt respect the typeset (Lyrics color)
> 

It was intentional to add text outline to improve visibility if you're using blurred song cover background.

If you use any other background there won't be any lyrics outline.

Sure you can create a new feature request. If enough people request to make the text outline optional I'll do it.

**Comment by drago-bit** [comment]
Well, the expanded view might not be buggy or not working, but it sure looks cluttered at the bottom. The button also overlaps the bar, which doesn't seem right at all.

Solution: Pull the buttons a bit on the upper side, so that it will give enough space to distinguish between the bottom bar 

![Screenshot_2024-06-22-10-29-06-809_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/170959159/7903a640-8274-447d-83b8-82a22f7680d5)

Another thing is that, with this new introduction, tapping on the album art to show lyrics doesn't work well. It seems really buggy. Have to tap multiple times, for both enabling and disabling the same.

@fast4x Kindly look into this.

**Comment by aneesh1122** [comment]
> Pull the buttons a bit on the upper side, so that it will give enough space to distinguish between the bottom bar

Already fixed that. The buttons will be lifted up a little if you've disabled transparent action bar.

Btw tapping on thumbnail to open lyrics working fine in my device
https://github.com/fast4x/RiMusic/assets/45353488/52eb43a8-4dcd-4f40-b6e5-5a0bcfb1ff21

**Comment by drago-bit** [comment]
> > Pull the buttons a bit on the upper side, so that it will give enough space to distinguish between the bottom bar
> 
> Already fixed that. The buttons will be lifted up a little if you've disabled transparent action bar.
> 
> Btw tapping on thumbnail to open lyrics working fine in my device
> 
> https://github.com/fast4x/RiMusic/assets/45353488/cf3833ed-ffdf-4cfd-ac0e-93e061ab02c9
> 
> 
> 
> 

Hiding/Disabling something to stop showing another thing doesn't mean it's fixed the issue. The bar is still there and the buttons are sitting on top of it. Besides, I like the bar without the transparency, maybe others are also out there.

Also, the latest update 0.6.40 is more than just buggy. The music struggles sometimes and is non responsive in lots of places. It also stops abruptly. Kindly note that, everything was working perfectly until the previous update.

Maybe, @fast4x can shed more light on this issue.

![Screenshot_2024-06-22-11-18-56-088_com.google.android.gm-edit.jpg](https://github.com/fast4x/RiMusic/assets/170959159/37a547c9-d5f6-443a-9fdd-a3ff7f2890c5)

**Comment by aneesh1122** [comment]
> Hiding/Disabling something to stop showing another thing doesn't mean it's fixed the issue. The bar is still there and the buttons are sitting on top of it. Besides, I like the bar without the transparency, maybe others are also out there.

It's fixed. You'll get the new changes in the next update.
![Screenshot_2024-06-22-11-28-27-319_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/45353488/a9b68def-899b-4501-9cf6-abaffc736131)

1)Made the text outline optional

2)Lifted the player timeline up when the  transparent action bar is disabled

**Comment by fast4x** [comment]
> > > Pull the buttons a bit on the upper side, so that it will give enough space to distinguish between the bottom bar
> > 
> > Already fixed that. The buttons will be lifted up a little if you've disabled transparent action bar.
> > 
> > Btw tapping on thumbnail to open lyrics working fine in my device
> > 
> 
> Hiding/Disabling something to stop showing another thing doesn't mean it's fixed the issue. The bar is still there and the buttons are sitting on top of it. Besides, I like the bar without the transparency, maybe others are also out there.
> 
> Also, the latest update 0.6.40 is more than just buggy. The music struggles sometimes and is non responsive in lots of places. It also stops abruptly. Kindly note that, everything was working perfectly until the previous update.
> 
> Maybe, @fast4x can shed more light on this issue.
> 
> ![IMG_20240622_114049.jpg](https://github.com/fast4x/RiMusic/assets/170959159/0995a6b7-9be3-4dfd-b5f7-5b5f4178471b)
> 
> 

Enable log debug in miscellaneous and paste here after crash

**Comment by drago-bit** [comment]
> > > > Pull the buttons a bit on the upper side, so that it will give enough space to distinguish between the bottom bar
> > > 
> > > Already fixed that. The buttons will be lifted up a little if you've disabled transparent action bar.
> > > 
> > > Btw tapping on thumbnail to open lyrics working fine in my device
> > > 
> > 
> > Hiding/Disabling something to stop showing another thing doesn't mean it's fixed the issue. The bar is still there and the buttons are sitting on top of it. Besides, I like the bar without the transparency, maybe others are also out there.
> > 
> > Also, the latest update 0.6.40 is more than just buggy. The music struggles sometimes and is non responsive in lots of places. It also stops abruptly. Kindly note that, everything was working perfectly until the previous update.
> > 
> > Maybe, @fast4x can shed more light on this issue.
> > 
> > ![IMG_20240622_114049.jpg](https://github.com/fast4x/RiMusic/assets/170959159/0995a6b7-9be3-4dfd-b5f7-5b5f4178471b)
> > 
> > 
> 
> Enable log debug in miscellaneous and paste here after crash

Opened a different ticket already, will update it there.

**Comment by faustaahmad** [comment]
> 1)Made the text outline optional
> 
> 2)Lifted the player timeline up when the transparent action bar is disabled

Try to add some blur to the Outline/Border to make it less sharp, like 0.4~0.6px blur
Just ignore this if it wasnt possible
Adding little bit of blur can make ~~subtitle~~ typeset blend a bit better to the background

Also since this Issue isnt a bug, should I close it?

**Comment by aneesh1122** [comment]
> Adding little bit of blur can make ~subtitle~ typeset blend a bit better to the background

and that's the reason why I added outline to the lyrics for blurred cover background in the first place. I wanted it to be properly visible. Also I've not added blur. It's a stroke/outline.

see, just try lyrics color = accent and see if you like it with outline. Don't use lyrics color = cover since I have to add a proper color palette to it.

anyways, I've added the choice to disable outline. Maybe in future I'll add a shadow option too.

**Comment by faustaahmad** [comment]
Alright, closing this issue since Expanded view does work under certain condition
"Show Thumbnail" set to OFF

**Comment by aneesh1122** [comment]
> Alright, closing this issue since Expanded view does work under certain condition "Show Thumbnail" set to OFF

you don't have to keep "show thumbnail" off always.

you can keep it on and keep "show thumbnail for lyrics" off to have clean lyrics background.

**Comment by drago-bit** [comment]
> It's fixed. You'll get the new changes in the next update.
> ![Screenshot_2024-06-22-11-28-27-319_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/45353488/a9b68def-899b-4501-9cf6-abaffc736131)
>
> 2)Lifted the player timeline up when the  transparent action bar is disabled

Guess this hasn't been implemented in the latest update 0.6.40.1, right?

**Comment by aneesh1122** [comment]
> > It's fixed. You'll get the new changes in the next update.
> > ![Screenshot_2024-06-22-11-28-27-319_it.fast4x.rimusic.debug.jpg](https://private-user-images.githubusercontent.com/45353488/341943054-a9b68def-899b-4501-9cf6-abaffc736131.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzI0MDMsIm5iZiI6MTcxOTIzMjEwMywicGF0aCI6Ii80NTM1MzQ4OC8zNDE5NDMwNTQtYTliNjhkZWYtODk5Yi00NTAxLTljZjYtYWJhZmZjNzM2MTMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDEyMjgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NjA0NjcxODAzN2YyYzQwM2FmZTBiNThiMWM1OGM2NmU0YmNhYThkMDhiYzE3YzBjOGJkYTFkNTliOTBjZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1dR-RHfb8iZpCehSoajUDvlAHKBuWNMQclbIM8YTJCM)
> > 2)Lifted the player timeline up when the  transparent action bar is disabled
> 
> Guess this hasn't been implemented in the latest update 0.6.40.1, right?

Nope. I've already created a pull request. It needs to be merged
