### ISSUE TITLE
Listening statistics

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#24]
### Description

I would find a listening statistic like Innertune's very interesting to track his listening statistics.

Mostly songs listened to within a week, within a month, within 6 months, within a year.

Most listened artist within a week, within a month, within 6 months, within a year.

Most listened album within a week, within a month, within 6 months, within a year.

### Suggested Solution

Should it be interesting for you and feasible.
You could have a look at it at Innertune.

https://github.com/z-huang/InnerTune

**Comment by fast4x** [comment]
Interesting

**Comment by fast4x** [comment]
Under development

**Comment by fast4x** [comment]
Implemented, available from version 0.6.7

**Comment by siggi1984** [comment]
The statistics section has turned out great.

**Comment by siggi1984** [comment]
But in my opinion, it doesn't really fit in here.

![Screenshot_20231103-212922](https://github.com/fast4x/RiMusic/assets/103368536/a6732d9b-302f-4df1-aae9-71760c161257)

**Comment by siggi1984** [comment]
I think it fits more in this area simply as a symbol but you have to decide 😊

![Lumii_20231103_214735875_1](https://github.com/fast4x/RiMusic/assets/103368536/73d02bea-8f12-4c3f-a9d5-0981f0bd9ffe)

**Comment by fast4x** [comment]
It would become like InnerTune, right?

**Comment by ikanakova** [comment]
I think the stats could be in Settings - Other.

**Comment by siggi1984** [comment]
In this respect, it would really look a bit like Innertune, but as already mentioned, the decision ultimately lies with the developer.

I think it's great how you respond to the wishes and requests of your users.
My respect.

**Comment by fast4x** [comment]
Thank you, I like to give answers based on user wishes.

@ikanakova  proposed to move it near with the settings, it seems to me a good idea, what do you think?

**Comment by fast4x** [comment]
Not in the settings, but like the settings button...

**Comment by ikanakova** [comment]
An icon between settings and quick picks would be great. I'll come up with one that combines the chart and music - I'll post a suggestion Sunday night or Monday when I get to the PC.

**Comment by siggi1984** [comment]
__

> An icon between settings and quick picks would be great. I'll come up with one that combines the chart and music - I'll post a suggestion Sunday night or Monday when I get to the PC.

That sounds like a pretty good solution.

**Comment by ikanakova** [comment]
My suggestion for an icon - a combination of pie chart and listening music:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/71b2180f-0949-4bd2-a89b-10325ef81808" alt="pie-chart-listen" width="100">

**Comment by ikanakova** [comment]
I am also attaching a version of sharp and outline for possible use.
[pie-chart-listen.zip](https://github.com/fast4x/RiMusic/files/13265967/pie-chart-listen.zip)

**Comment by fast4x** [comment]
Great work

**Comment by fast4x** [comment]
Reopened for adding new icons

**Comment by fast4x** [comment]
Implemented new icons statistics and settings.
