### ISSUE TITLE
[Feature]: More sleep timer options

### ISSUE THREAD

**Issue by nvllz** [fast4x/RiMusic#240]
### Description

The sleep timer is a cool feature, and even if only used occasionally, it can be very useful if it is sufficiently configurable.

### Suggested Solution

I'd like to be able to set a custom sleep time by tapping the time label in the sleep timer dialog. That way I could set the app to stop playing after 17 minutes instead of 15 or 20.

Additionally, I found an "end of a song" button in this kind of sleep timer dialogs in other music player apps very useful. Especially if you're listening to a long mix and want the app to set the sleep timer to the end of a currently playing song, so you don't have to manually calculate `remaining_time = song_time - elapsed_time` and can quickly set the timer.

**Comment by fast4x** [comment]
Great! Thanks for suggestion.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.20
