### ISSUE TITLE
The albums aren't showing new and old

### ISSUE THREAD

**Issue by claxcian** [fast4x/RiMusic#2404]
### Steps to reproduce the bug

Quando si apre un album non viene visualizzato 

### Expected behavior

Prima si riusciva a visualizzare gli album.

### Actual behavior

Ora non visualizza gli album e compare l'icona rimusic

### RiMusic version

0.6.40 ma anche con la precedente 

### Android version

Android 14

**Comment by chatinteligence** [comment]
please translate your comments into English, this is very useful for Fast4x

**Comment by twistios** [comment]
> please translate your comments into English, this is very useful for Fast4x

It seems like fast4x is actually an italian person, so this is not much of a problem for him I guess. But you are right that english is useful for other people like me.

**Comment by twistios** [comment]
This is a duplicate of #2388 I guess.

**Comment by claxcian** [comment]
Album are not show, new and old album

**Comment by fast4x** [comment]
Work in progress, YouTube music have changed interface in albums and playlists. All app like RiMusic have same bug, I'm working on it.

Italian, YouTube Music ha cambiato l'interfaccia per album e playlist, questo causa il problema sul caricamento. Tutte le app simili a RiMusic hanno lo stesso problema in questo momento.

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1

**Comment by claxcian** [comment]
Grande Rino
--- 𝘾𝙡𝙖𝙪𝙙𝙞𝙤 𝘾𝙞𝙖𝙣𝙙𝙧𝙞𝙣𝙞 ---

Il Lun 24 Giu 2024, 09:55 Rino Russo ***@***.***> ha scritto:

**Comment by fast4x** [comment]
Grazie Claudio

**Comment by claxcian** [comment]
Rino una volta mi avevi mandato il link di dive si trovano le versioni
giornaliere. È possibile?
--- 𝘾𝙡𝙖𝙪𝙙𝙞𝙤 𝘾𝙞𝙖𝙣𝙙𝙧𝙞𝙣𝙞 ---

Il Lun 24 Giu 2024, 11:55 Rino Russo ***@***.***> ha scritto:

**Comment by fast4x** [comment]
Non io, te lo aveva girato un utente, non sapendo che non ci sono versioni giornaliere.
