### ISSUE TITLE
[Feature]: Piped playlist import

### ISSUE THREAD

**Issue by Stuid01** [fast4x/RiMusic#2405]
### Description

Piped import support from Rimusic saves

### Suggested Solution

If it's not added already, you should make Rimusic imports usable in piped

**Comment by fast4x** [comment]
Hi, explain better please.

**Comment by aneesh1122** [comment]
> Hi, explain better please.

From what I understood he wants to upload RiMusic exported playlist csv in piped.

**Comment by fast4x** [comment]
Yiu can create a new playlist and add all songs. Automatically will be sync in piped...

**Comment by Stuid01** [comment]
I already did that to port my playlist to spotify, and it was tedious since my playlist currently has 130 songs in it, so i thought that using the CSV file from rimusic and loading it in piped would be a better time-effective solution

**Comment by aneesh1122** [comment]
> Yiu can create a new playlist and add all songs. Automatically will be sync in piped...

about that. I have a playlist with almost 1400 songs and when I added those songs to a piped playlist, the songs won't sync at all.

is there a limit to how many songs I can transfer at a time?

**Comment by leopoldhub** [comment]
> is there a limit to how many songs I can transfer at a time?

I don't think so, I have had the same issue with ~20 songs.
It seems that importing songs from other playlists doesn't trigger the sync for some reason.

Adding a song manually afterwards will only add that song and not the 20 others already in it.

**Comment by aneesh1122** [comment]
> Perhaps a \"manual sync\" button would be useful to ensure playlists are always up to date?

It's already there. It will remove your previously added 20 songs though since it fetches data from piped

**Comment by PPereaC** [comment]
Hello. I can't import my songs to a piped playlist. Can you tell me the way to sync my songs with piped? If you can explain it with a video or captures I really appreciate it. I already have my playlists in piped before I connect my piped account, but after doing the connection, the syncs playlists are empty.

**Comment by fast4x** [comment]
Wait for new version

**Comment by DKMellow** [comment]
Hello, sadly my piped playlists still don't sync after the update. Could you Pplease look more into it? just let me know if you need any logs, I can happily help.

**Comment by fast4x** [comment]
Disconnect account and connect again, try

**Comment by DKMellow** [comment]
What I tried so far is, reconnecting, changing instances while also transferring the playlist to said new instance, deleting the playlist while disconnected and then connecting, manual sync, clearing the cache of the app, and still no change.

**Comment by aneesh1122** [comment]
> What I tried so far is, reconnecting, changing instances while also transferring the playlist to said new instance, deleting the playlist while disconnected and then connecting, manual sync, clearing the cache of the app, and still no change.

I don't know how many songs you can transfer and sync at a time but if you transfer only one song at a time it will get synced

**Comment by DKMellow** [comment]
I am sorry, but what do you mean by transferring one song at a time?

**Comment by aneesh1122** [comment]
> I am sorry, but what do you mean by transferring one song at a time?

select one song, add it to piped playlist.

**Comment by fast4x** [comment]
is possible to select many songs at one time

**Comment by PPereaC** [comment]
> > is possible to select many songs at one time
> 
> I tried but sometimes 2 songs would get synced and sometimes 5. It's not consistent.
> 
> When I added 1400 songs none of the songs were synced

That's correct. It's not working when you try to sync multiple songs at the same time.

**Comment by PPereaC** [comment]
I'm connected to my piped account. And playlists appears empty.

![Screenshot_2024-06-26-15-40-24-353_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/74180013/193d1cc8-0d3f-433e-96b1-27161ecdbb4a)

![Screenshot_2024-06-26-15-41-02-867_com.brave.browser-edit.jpg](https://github.com/fast4x/RiMusic/assets/74180013/1e295ef4-6d56-4683-8cbf-19d8c8fbb345)

**Comment by fast4x** [comment]
Uhm ok, can export from piped a file json? attach here please

**Comment by fast4x** [comment]
Thanks

**Comment by PPereaC** [comment]
> Thanks

Thanks for your support 😄

**Comment by fast4x** [comment]
Fixed, there is a hidden bug in RiMusic sync response from piped server... thanks 
Available from version 0.6.41


https://github.com/fast4x/RiMusic/assets/1484476/54a8f169-2a32-491e-aeb2-21b3ce8f0c3d

**Comment by PPereaC** [comment]
> Fixed, there is a hidden bug in RiMusic sync response from piped server... thanks 
> Available from version 0.6.41
> 
> 
> https://github.com/fast4x/RiMusic/assets/1484476/54a8f169-2a32-491e-aeb2-21b3ce8f0c3d
> 
> 

Perfect!! Thank you very much for your support ❤️

**Comment by fast4x** [comment]
Thanks to you
