### ISSUE TITLE
Show custom toast repeatedly during swipe down

### ISSUE THREAD

**Issue by Official-Mlx** [fast4x/RiMusic#2412]
### Steps to reproduce the bug

Hello, when I swipe down, a custom toast is displayed about five times, and this number increases with subsequent attempts. This is very annoying.

![Screenshot_2024-06-22-08-13-59-592_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/74877307/9f4584ad-fccc-4d63-9bd0-f161179a69b3)

### Expected behavior

"Do not display the custom toast or show it only once."

### Actual behavior

‍

### RiMusic version

last version

### Android version

10

**Comment by KOLIWAN** [comment]
You can enable swiping down the player, so, technically, pop-up message won't appear anymore :)

**Comment by fast4x** [comment]
If you don’t like something it doesn’t mean it’s a bug. Enable swipe down and don’t get the popup.

**Comment by fast4x** [comment]
I respect your point, but RiMusic isn't other apps, it have a personality and smart toast is  one of differences.
