### ISSUE TITLE
RiMusic keeps crashing | 0.6.40 +

### ISSUE THREAD

**Issue by drago-bit** [fast4x/RiMusic#2414]
### Steps to reproduce the bug

Just running the app for a while address the issue.

### Expected behavior

Player should work as intended.

### Actual behavior

Player keeps crashing abruptly.

### Screenshots/Screen recordings

![IMG_20240622_114049](https://github.com/fast4x/RiMusic/assets/170959159/1b1e67f2-cb2c-4ae5-a885-1d9d2a4ab5f3)

### RiMusic version

0.6.40

### Android version

Android 14

### Additional information

As of now, within a span of couple hours, player has crashed itself multiple times.

**Comment by drago-bit** [comment]
java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 x5.a.r(SourceFile:38) 
	 V6.a.k(SourceFile:9) 
	 n7.J.run(SourceFile:95) 
	 C1.a.run(SourceFile:110) 
	 u7.j.run(SourceFile:3) 
	 u7.a.run(SourceFile:96)

**Comment by fast4x** [comment]
Restart device and try again

**Comment by drago-bit** [comment]
Nah, it doesn't work and crashed again.

Also, the album page doesn't load at all.

![Screenshot_2024-06-22-15-07-35-536_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/170959159/94da21f6-1808-439e-957e-b36aff3d7536)

**Comment by drago-bit** [comment]
Hear about the API change. So everything must have something to do with it. Will wait for the update then.

**Comment by fast4x** [comment]
Yes it's api change, work in progress

**Comment by asiantuntija** [comment]
I've been having these crashes also quite often, works fine if I don't mess too much with the UI and just listen stuff. Here's the error log from last few crashes

[RiMusic log b99416ea9a33.txt](https://github.com/user-attachments/files/16116494/RiMusic.log.b99416ea9a33.txt)

**Comment by fast4x** [comment]
You use a phisical device?

**Comment by asiantuntija** [comment]
> You use a phisical device?

Yes, Pixel 7a

**Comment by Abilomp** [comment]
Please update to 6.42 version

**Comment by asiantuntija** [comment]
Did a fresh install of 6.42 and still crashing

[RiMusic log cff7de121ca4.txt](https://github.com/user-attachments/files/16116608/RiMusic.log.cff7de121ca4.txt)

**Comment by asiantuntija** [comment]
So I did some more testing.

- the above crash happens always when I toggle lyrics on and leave them displayed on screen, doesn't matter if the lyrics are fullscreen or just on top of album cover, takes about a minute to crash
- if I toggle lyrics and move the app to background it doesn't crash
- if I toggle lyrics and go to another view in the app it also doesn't crash
- if I stay in the song view without lyrics it doesn't crash

**Comment by asiantuntija** [comment]
[RiMusic log d57ece320087.txt](https://github.com/user-attachments/files/16228409/RiMusic.log.d57ece320087.txt)
Crashing with 6.43 also, some SQL errors in the logs at least

**Comment by fast4x** [comment]
Crash occur with java.io.IOException: Too many open files
