### ISSUE TITLE
Albums do not load  

### ISSUE THREAD

**Issue by RouhT4ner** [fast4x/RiMusic#2415]
### Steps to reproduce the bug

The bug is shown when you open an album 

### Expected behavior

Show all album songs

### Actual behavior

Do not show album songs

### Screenshots/Screen recordings

![Screenshot_20240622_014024](https://github.com/fast4x/RiMusic/assets/173532150/72ab8d34-3b0b-44fa-80c7-0ccbf102c140)

### RiMusic version

0.6.40

### Android version

Android 14

**Comment by JPGuillemin** [comment]
confirmed here, both last 2 stable versions

**Comment by RouhT4ner** [comment]
> confirmed here, both last 2 stable versions

What could be happening to me?

**Comment by fast4x** [comment]
Work in progress, YouTube music have changed interface in albums and playlists. All app like RiMusic have same bug, I'm working on it.

**Comment by RouhT4ner** [comment]
> Work in progress, YouTube music have changed interface in albums and playlists. All app like RiMusic have same bug, I'm working on it.

thank you so much . excellent app

**Comment by fast4x** [comment]
Thanks

**Comment by JPGuillemin** [comment]
Bug also noticed in latest Innertune v0.6.5. So it's must likely be an API change.

**Comment by maszek** [comment]
I experience the same:

https://youtube.com/shorts/IVIwpQizKag?si=GxhlQE7mkF_FyWQG

I like the new interface, though.

**Comment by fast4x** [comment]
> Bug also noticed in latest Innertune v0.6.5. So it's  likely an API change.

Yes confirmed

**Comment by dAtA-TRoN** [comment]
This bug is sooo annoying...

![proxy-image(2).gif](https://github.com/fast4x/RiMusic/assets/71184627/45a38dfa-8e5d-4903-a5b3-4ed5ae9fa2dd)

**Comment by fast4x** [comment]
Work in progress...
![giphy (16).gif](https://github.com/fast4x/RiMusic/assets/1484476/57232676-19d9-42a4-b943-338ba2d24dae)

**Comment by curious-liberal** [comment]
I've also been experiencing this

**Comment by AdidasGamer** [comment]
Just to put one more detail
Playlists are loading empty too

**Comment by fast4x** [comment]
Work in progress, YouTube music have changed interface in albums and playlists. All app like RiMusic have same bug, I'm working on it.

**Comment by RouhT4ner** [comment]
How is the problem going?

**Comment by vitaminac** [comment]
Hi @RouhT4ner, we should not close this issue until the fix commit is upload. It will help people with similar problems to find the corect issue from Google. It will avoid people from opening duplicated issue if they know there is already one open.

**Comment by RouhT4ner** [comment]
Hello, how is the arrangement going?

**Comment by maszek** [comment]
> Fixed, available today from version 0.6.40.1

I'm afraid it still doesn't work for me 😥
Just installed the apk from GitHub.

![Screenshot_2024-06-24-10-57-36-84_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/990963/a6940bde-ea6e-4b79-a4b0-f47d2ce223d2)

![Screenshot_2024-06-24-10-57-15-83_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/990963/143888fc-a538-4153-9ca1-0ef7e3b9ec6a)

**Comment by fast4x** [comment]
It’s fixed that it doesn’t work yet, read the version, I said that I release it today in version 0.6.40.1, you just reinstalled version 0.6.40
