### ISSUE TITLE
Albums, featured and user playlist won't show any music in them, even though they show album covers on their thumbnail.

### ISSUE THREAD

**Issue by Stuid01** [fast4x/RiMusic#2416]
### Steps to reproduce the bug

1. Go to quick picks
2. open a random album or featured playlist

### Expected behavior

The music from the chosen album should show up

### Actual behavior

The music from the chosen album doesn't show up

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/165581024/94ea2214-04ea-4633-9f5c-d961ad7de582

### RiMusic version

v0.6.40

### Android version

android 13

**Comment by drago-bit** [comment]
Yes, it's happening with me as well.
