### ISSUE TITLE
Minimal Sleep timer UI

### ISSUE THREAD

**Issue by Shivamhobbyist** [fast4x/RiMusic#242]
### Description

Plz add thiss typ of UI its simple and minimal
Application ---- https://github.com/jhelumcorp/gyawun

https://github.com/fast4x/RiMusic/assets/78287172/28fc294b-07bb-45c4-ae5d-cb8317174967

### Suggested Solution

Xyz

### Alternatives

Xyz

### Additional Context

Xyz

**Comment by fast4x** [comment]
Hello, I evaluate the possibility of inserting it compatible with the features being developed.

Thanks for suggestion

**Comment by fast4x** [comment]
Implemented, available from version 0.6.14
