### ISSUE TITLE
Rimusic 

### ISSUE THREAD

**Issue by AlexNeves** [fast4x/RiMusic#2425]
### Steps to reproduce the bug

Ele não tá carregando quando faz busca de Álbum completo 

### Expected behavior

Rimusic 

### Actual behavior

Rimusic 

### Screenshots/Screen recordings

Rimusic 

### Logs

Rimusic 

### RiMusic version

0.6.40

### Android version

13

### Additional information

Rimusic

**Comment by fast4x** [comment]
Work in progress, YouTube music have changed interface in albums and playlists. All app like RiMusic have same bug, I'm working on it.

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
