### ISSUE TITLE
I can't an album of any artist 

### ISSUE THREAD

**Issue by kozmiccigarette** [fast4x/RiMusic#2427]
### Steps to reproduce the bug

1. Go to the page “quick picks”
2. Scroll to the recommended albums or new albums
3. I want open any album
4. Clik on the album thumbnail
5. The album is open, but don't charge content 

### Expected behavior

The content could be visible and disponible 

### Actual behavior

The page is empty 

### Screenshots/Screen recordings

![Screenshot_20240622_113703_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/172777121/2512a2b5-1761-4496-9077-e10db3026bf4)

### RiMusic version

0.6.40

### Android version

Android 10 

### Additional information

Is a huawei device, without Google Mobile Services

**Comment by fast4x** [comment]
Work in progress, YouTube music have changed interface in albums and playlists. All app like RiMusic have same bug, I'm working on it.

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
