### ISSUE TITLE
A feature is bugged

### ISSUE THREAD

**Issue by ghost** [fast4x/RiMusic#2429]
### Steps to reproduce the bug

There is an option in settings "show download button in lockscreen and notification area" but actually it shows the shuffle button not the download button. 

### Expected behavior

There should be the download button. 

### Actual behavior

But there is no download button, instead a shuffle button

### Screenshots/Screen recordings

![Screenshot_2024-06-23-01-06-02-19_91b67804b5fb3353a77fb824d6bb0b50 (1)](https://github.com/fast4x/RiMusic/assets/148379631/b103c799-aa5c-4148-a136-655a88cb7f0a)
![Screenshot_2024-06-23-01-06-10-06_91b67804b5fb3353a77fb824d6bb0b50 (1)](https://github.com/fast4x/RiMusic/assets/148379631/50b85363-15ee-4731-80b3-d06813cfefab)

### RiMusic version

0.6.40

### Android version

Android 13

**Comment by ikanakova** [comment]
I wonder if this might be related to PR #2075

**Comment by ikanakova** [comment]
The bug is still present in version 0.6.42.
