### ISSUE TITLE
problem when entering any album  

### ISSUE THREAD

**Issue by m3ru0** [fast4x/RiMusic#2430]
### Steps to reproduce the bug

I was saving a album and when I went to enter to download the songs, no content appeared within it.

### Expected behavior

the songs that should be on the álbum appear 

### Actual behavior

no content is shown within the álbum  

### Screenshots/Screen recordings

![Screenshot_20240623_000429](https://github.com/fast4x/RiMusic/assets/164958656/d5dc75cb-d214-47f8-a71b-bb7979f0c9ae)

### RiMusic version

0.6.40

### Android version

Android 13

**Comment by User679292662** [comment]
fast4x is working in it

**Comment by m3ru0** [comment]
okay, take your time, don't stress too much

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
