### ISSUE TITLE
Albums problem

### ISSUE THREAD

**Issue by Brocoliexe** [fast4x/RiMusic#2431]
### Steps to reproduce the bug

1. Go to a album.
2. When you open doesn't have any music and keeps loading.
![Screenshot_20240623-042140](https://github.com/fast4x/RiMusic/assets/173597170/d3e57bb4-5096-4efe-b77a-2c2e5f644bea)

### Expected behavior

That shows the music from the album.

### Actual behavior

Instead doesn't show anything.

### RiMusic version

0.6.40

### Android version

Android 10

**Comment by darkza** [comment]
same problem

**Comment by MXC48** [comment]
Same problem

**Comment by BrookEther** [comment]
Same issue

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
