### ISSUE TITLE
Playlist Bug

### ISSUE THREAD

**Issue by Cresh680** [fast4x/RiMusic#2433]
### Steps to reproduce the bug

1. Click Quick Picks 
2. Choose moods and genres 
3. Choose one and then select any Playlist that'd beeb made. 
4. Every Playlist is populating blank with zero songs in it. 

### Expected behavior

![Screenshot_20240623_083427](https://github.com/fast4x/RiMusic/assets/94272445/63017167-462c-4f33-9d7a-ef40afc0aea2)
![Screenshot_20240623_083433](https://github.com/fast4x/RiMusic/assets/94272445/098e8ba7-c16e-46ab-acc2-be1d2ffe565e)

### Actual behavior

When clicking on a Playlist it just populated empty instead of songs listed. 

### Screenshots/Screen recordings

![Screenshot_20240623_083427](https://github.com/fast4x/RiMusic/assets/94272445/9cfc5469-c790-48d4-b05a-0fe18d08092c)
![Screenshot_20240623_083433](https://github.com/fast4x/RiMusic/assets/94272445/9129e5a1-152c-4398-9100-a9b14d8e8214)

### RiMusic version

0.6.40

### Android version

Android version 14

**Comment by EmmetSchuler** [comment]
Can confirm this happens to me too. Also on android

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
