### ISSUE TITLE
Playlists and album not load the songs

### ISSUE THREAD

**Issue by Shadow7643** [fast4x/RiMusic#2435]
### Steps to reproduce the bug

1.Go to album or playlists 2. Not loading any song 3. See arror the album dosen't have any alternative version 
![Screenshot_2024-06-23-20-28-08-391_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/173625387/23d9afcf-5d1b-4367-925e-7157806353a5)

### Expected behavior

This should load songs from albums or playlists 

### Actual behavior

This should load song 

### RiMusic version

0.6.40

### Android version

Android 13

**Comment by Ao1Pointblank** [comment]
i synced my remote playlist and it got deleted lol
i don't think i can get it back until this is fixed.

**Comment by fast4x** [comment]
It's not deleted but unsynced... download latest version it's been fixed

**Comment by fast4x** [comment]
I'll check it
