### ISSUE TITLE
[Feature]: Connect to internet only if I play online music not every single music is played

### ISSUE THREAD

**Issue by pythonmkl** [fast4x/RiMusic#2437]
### Description

App keeps connecting to the internet to a 1e100.net Google site almost as every music is played. What information are you sending to Google? You should not send anything or even query anything when I play my music offline.
So remove that "functionality". If I download music, that is critical so access some site do download the music. But that is the only time it should access the networking.

### Suggested Solution

Remove constant connections to Google domain every time I play a new music.

**Comment by JeePopuwu** [comment]
my least schizophrenic friend

**Comment by Cszyn** [comment]
I don't get this one. 
"The app keeps connecting to the internet to a 1e100.net Google site almost as every music is played." the app need to connect to Google(YouTube) to play music (except offline/downloaded). 
"You should not send anything or even query anything when I play my music offline." Fair? But it's probably there to check (ping google) if you're connected to the internet or not. 
"If I download music, that is critical, so access some site to download the music. But that is the only time it should access the networking." so you want a solely offline music player with additional music downloading functionality. Ri was not made to be an offline player, tho.

**Comment by fast4x** [comment]
Maybe you have wrong app, RiMusic doesn’t send anything at all.
Download the app only from official sources.

**Comment by Cszyn** [comment]
I highly recommend https://github.com/Droid-ify/client it's an f-droid client with a ui that's not from the 2000s

**Comment by pythonmkl** [comment]
RiMusic connects to the internet every music is played. Just played one music, connects to 172.217.17.1:443 mad07s09-in-f1.1e100.net. Soon as I change music, connected again, maybe because it has no access but it does connects at least once. I don't know if after one connections it stops or not, don't have those logs and not going to let Google know what musics and when I'm listening to music.
When an app connects to internet, there is the app name on the log. It's not the OS trying to ping or any other app. It is RiMusic. 
If it is not RiMusic, there are some lib's app is using that are trying to get to Google and those should be removed.
My app as always comes from F-Droid. 
It is a great app don't get me wrong. It never connects to Google because my VPN Firewall won't allow it but still I don't want it to connect.

**Comment by pythonmkl** [comment]
> Maybe you have wrong app, RiMusic doesn’t send anything at all. Download the app only from official sources.

I know we all get things wrong sometimes, but when I see "RiMusic" on my logs, I'm 100% sure that it is that app, as many others, like 100% of all other apps connects to the Internet and get denied by my firewall.
It might be not the app code but some lib it uses, I get that, but that should be found and fixed.
I really like the app, have used many in the past but keep using this one and really want to continue to use it. Thanks.

**Comment by pythonmkl** [comment]
"the app needs to connect to Google(YouTube) to play music (except offline/downloaded)."
I have downloaded almost every music with the app. Then disconnect and play. That is offline music play.
Still, if I have wifi on, each music played it connects to Google, at least tries, because I have most of apps blocked. But I see the logs. So if the music is already downloaded, why connect to Google on each music play??

"Fair? But it's probably there to check (ping google) if you're connected to the internet or not."
If it is a "ping" it is done by RiMusic or some lib it uses. But it should not do it.

"so you want a solely offline music player with additional music downloading functionality. Ri was not made to be an offline player, tho."
Again, if music is already downloaded or on my device, it should never touch the internet, unless I asked to download.

**Comment by pythonmkl** [comment]
This is a privacy issue. But it will not be fixed, as the app checks if there is networking with InetAddress.getByName("google.com"). Also almost every music played, you tell google that you are playing the music. That is as bad as it gets. Still it is a trust issue with your users and some of us value privacy. If I use youtube or any google services, I'm aware of that, but an app that behind the scenes contacts google... no thanks.
Downloading music from youtube and other sites is a great option but not if you keep telling them when I play the musics.
Sadly, this is common behavior of almost every app. But there are really good open source music players, MonsterMusic is one of them, that it does not connect google for each music played.

**Comment by JeePopuwu** [comment]
> Este es un problema de privacidad, pero no se solucionará, ya que la aplicación comprueba si hay una conexión de red con InetAddress.getByName("google.com"). Además, casi todas las canciones que se reproducen le indican a Google que las estás reproduciendo. Eso es lo peor que puede pasar. Aun así, es un problema de confianza con los usuarios y algunos de nosotros valoramos la privacidad. Si uso YouTube o cualquier servicio de Google, lo sé, pero una aplicación que se pone en contacto con Google en segundo plano... no, gracias. Descargar música de YouTube y otros sitios es una gran opción, pero no si les sigues diciendo cuándo reproduzco la música. Lamentablemente, este es un comportamiento común de casi todas las aplicaciones. Pero hay reproductores de música de código abierto realmente buenos, MonsterMusic es uno de ellos, que no se conecta con Google para cada canción reproducida.

Yes baby, what else did the talking tree tell you?

**Comment by fast4x** [comment]
> This is a privacy issue. But it will not be fixed, as the app checks if there is networking with InetAddress.getByName("google.com"). Also almost every music played, you tell google that you are playing the music. That is as bad as it gets. Still it is a trust issue with your users and some of us value privacy. If I use youtube or any google services, I'm aware of that, but an app that behind the scenes contacts google... no thanks.
> Downloading music from youtube and other sites is a great option but not if you keep telling them when I play the musics.
> Sadly, this is common behavior of almost every app. But there are really good open source music players, MonsterMusic is one of them, that it does not connect google for each music played.

Let me point out a couple of things: calling Google.com is equivalent to viewing the Google web page to see if the device is online while maintaining compatibility with old devices. RiMusic does not have a Google login so it does not share any information. Also, ALL music that is played is provided by YouTube without any subscription and login.

Finally use the app that suits you best but without throwing shit on others for no reason. Or inform yourself better before saying emerite bullshit. Good listening.
