### ISSUE TITLE
Versiones alternativas 

### ISSUE THREAD

**Issue by Bruno2777** [fast4x/RiMusic#2439]
### Steps to reproduce the bug

Que tal, hace un mes aproximadamente instalé está aplicando, funcióno bastante bien hasta hace 1 semana.
Si no mal recuerdo en el apartado de biblioteca, en la sección de álbumes solo toque un álbum y de la nada se fue toda la información de el mismo, como si no existiera mostrándome abajo el nombre de "versiones alternativas", creí que era un simple error pero no fue asi, con todos los álbumes me pasó y tuve que crear una playlist aparte con la música y el nombre de el álbum aunque nisiquiera sea, es algo muy extraño

### Expected behavior

Debería abrir el álbum y mostrarne las canciones normalmente, poder reproducirlas y descargarlas

### Actual behavior

Se abre el álbum sin ningúna canción ni nombre y dice versiones alternativas 
![Screenshot_2024-06-23-18-20-25-731](https://github.com/fast4x/RiMusic/assets/173636499/1c2f6a6a-83e2-44d2-949d-95002b73c537)

### RiMusic version

La última a fecha 23/06/24

### Android version

Android 12

**Comment by Kou-tester** [comment]
me pasa exactamente lo mismo pero con los albums en si

**Comment by fast4x** [comment]
work in progress

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
