### ISSUE TITLE
Album name doesn't appear correctly on smart bluetooth speakers

### ISSUE THREAD

**Issue by LantashTheTokra** [fast4x/RiMusic#244]
### Steps to reproduce the bug

Connect to a smart bluetooth speaker like an Alexa or car

### Expected behavior

![PXL_20231217_215536315](https://github.com/fast4x/RiMusic/assets/84555704/384e6596-53b0-4979-82fe-e70b98d37736)
(Differt music app: shows album name instead of not supported)

### Actual behavior

![PXL_20231217_215308543](https://github.com/fast4x/RiMusic/assets/84555704/3b725db2-cee6-4dad-9b75-df9d70dfbcd5)

### RiMusic version

0.6.13

### Android version

Android 14

**Comment by fast4x** [comment]
Hi, name's album is too long?

**Comment by LantashTheTokra** [comment]
![PXL_20231217_222911698](https://github.com/fast4x/RiMusic/assets/84555704/cf6d156d-49f2-48ce-b55d-7c8527b89e7c)
No it's a problem with this app. This song renders correctly in the other app.

**Comment by LantashTheTokra** [comment]
derp

**Comment by fast4x** [comment]
The problem could be caused by the scrolling text used for title and artist. 
I added an option in settings > appearance > Disable scrolling text, turn on the option to restart RiMusic and try on the device if everything is ok.

Available from version 0.6.14
