### ISSUE TITLE
albums don't load

### ISSUE THREAD

**Issue by Kou-tester** [fast4x/RiMusic#2440]
### Steps to reproduce the bug

1.go to the "albums page"
2. the "albums" page loads
3. but when I enter an album the album does not load

### Expected behavior

I don't know what could cause this error itself.

### Actual behavior

This happens on other devices with the same version of the app and the same version of Android, in addition to being the same device, this being a Xiaomi 

### RiMusic version

version 0.6.40

### Android version

Android 14

**Comment by fast4x** [comment]
work in progress

**Comment by Asur30** [comment]
Yes it's the problem with oneplus devices too
Albums and play lists are unable to load

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
