### ISSUE TITLE
No aparecen ningún album

### ISSUE THREAD

**Issue by Yokcerpr** [fast4x/RiMusic#2442]
### Steps to reproduce the bug

Ninguno solo actualize la aplicación a su última versión 

### Expected behavior

Me imagino que debe pasar por los servidores o una jalada asi

### Actual behavior

Si

### Screenshots/Screen recordings

![Screenshot_2024-06-23-20-22-12-589_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/155603731/8eb6f350-5299-467c-aca3-48965ee11cd0)

### Logs

Si

### RiMusic version

0.6.40

### Android version

Android 14

### Additional information

Quisiera saber que es lo que está pasando no me aparece ningún album y apenas como el peso plumax saco un álbum quería verlo pero por más que quiera no me aparece ninguno ya hasta reinicie la app y nada

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
