### ISSUE TITLE
Eternal loading screen

### ISSUE THREAD

**Issue by r8dofdystopia** [fast4x/RiMusic#2443]
### Steps to reproduce the bug

1. Go to "Albums"
2. Click on a random album
3. See error

### Expected behavior

The album content should be displayed

### Actual behavior

Instead, it only shows loading (never loads) and you cannot see the content of the album.

### Screenshots/Screen recordings

![Screenshot_20240623-224938](https://github.com/fast4x/RiMusic/assets/173648377/a539ded6-f89c-45e4-92f8-e6424967ca2e)

### RiMusic version

0.6.39

### Android version

Android 10

### Additional information

This problem not only happens on any album, but also on any public playlist. For the same reason, it has also become impossible to open any YouTube link in RiMusic. I must assure you that this problem also occurs in the recent version (0.6.40), however, for my part I have decided to return to the version prior to that since the due update the player looks completely uneven (even in terms of font) and I didn't like it. Waiting for a solution, since I really love RiMusic. Thank you.

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
