### ISSUE TITLE
Error album

### ISSUE THREAD

**Issue by Nisselle** [fast4x/RiMusic#2444]
### Steps to reproduce the bug

1. Primer busque un artista.
2. Di click en la sección de Album
3. Luego presione el álbum que deseaba
4. No me sale ninguna canción de ningún album de ningún artista

### Expected behavior

Que salgan las canciones del álbum seleccionado

### Actual behavior

No salen las canciones de los albums, ni las carátulas de los mismos

### Screenshots/Screen recordings

![Screenshot_20240623-235607](https://github.com/fast4x/RiMusic/assets/173654765/eb678254-13d9-4555-9d43-d00e4a8249f0)
![Screenshot_20240623-235610](https://github.com/fast4x/RiMusic/assets/173654765/ca085fd1-983a-410f-8755-25529a3dab45)

### RiMusic version

0.6.40

### Android version

Android 11

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
