### ISSUE TITLE
Singles and Playlists are empty, tracks don't load in them

### ISSUE THREAD

**Issue by Slawa79** [fast4x/RiMusic#2445]
### Steps to reproduce the bug

I click on the Singles or Playlist icon , the playlist opens but does not contain tracks .

### Expected behavior

The Singles and Playlists section does not contain tracks

### Actual behavior

The playlist and singles sections do not contain tracks,

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/23304238/487975bf-fa0c-416f-947e-4484a707ceea

### Logs

there are no log files

### RiMusic version

RiMusic 0.6.40

### Android version

Android 13

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
