### ISSUE TITLE
No me cargan los álbumes 

### ISSUE THREAD

**Issue by Gmxo05** [fast4x/RiMusic#2446]
### Steps to reproduce the bug

Busqué un álbum y al momento de entrar no me carga, lleva así toda la tarde pensé que era mi red pero no 
![Screenshot_2024-06-24-01-00-33-968_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/173658761/baf96661-0913-4de8-9b01-f31aa5db06fa)
![Screenshot_2024-06-24-01-00-40-409_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/173658761/fef1a374-cd3a-42e5-be46-4e889850eac5)
Espero que puedan solucionarlo 

### Expected behavior

Debería poder cargar el álbum con normalidad cómo antes 

### Actual behavior

No carga el álbum y es con todos los álbumes 

### RiMusic version

Última versión 

### Android version

Android 13

**Comment by fast4x** [comment]
Fixed, available today from version 0.6.40.1
