### ISSUE TITLE
Slow and buggy Vizualizer

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#2448]
### Steps to reproduce the bug

Play a song, then use a visualizer.

### Expected behavior

The visualizer should be fast and precise, as it was back then.

### Actual behavior

The visualizer is slow and freezes immediately.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/104271365/de87449d-08a5-4732-be41-79f97e5078b1

For some reason, it isn't freezing when recording, but it is still slow.

### RiMusic version

0.6.40.1

### Android version

Android 14

### Additional information

I don't know if this is a bug or intentional. You can change this into a feature if it isn't.

**Comment by fast4x** [comment]
Yes visualizer is bugged, soon I'll check it

**Comment by fast4x** [comment]
Fixed and implemented new with dozens of visualizers, available from version 0.6.41

**Comment by OrangeZXZ** [comment]
> Fixed and implemented new with dozens of visualizers, available from version 0.6.41

dozens!? 🤯 Hyped to try all of them!

**Comment by fast4x** [comment]
and not necessary go to settings for change it... can select directly from player... next, previous... dozen effects...

**Comment by fast4x** [comment]
Look this sample... 🥳🥳
https://github.com/fast4x/RiMusic/assets/1484476/437caf66-46b0-4db9-a990-119e21df78fc

**Comment by aneesh1122** [comment]
> Look this sample... 🥳🥳
> https://github.com/fast4x/RiMusic/assets/1484476/437caf66-46b0-4db9-a990-119e21df78fc

This looks cool. I'll try to implement this with no thumbnail like how I made lyrics have no thumbnail
