### ISSUE TITLE
Songs in playlists and albums are not visible

### ISSUE THREAD

**Issue by Auserrum** [fast4x/RiMusic#2449]
### Steps to reproduce the bug

When opening playlists from search, their contents are not displayed. But if they are saved, the contents are displayed in the normal mode.

### Expected behavior

Tracks should be displayed correctly

### Actual behavior

This happened instead of the tracks being displayed correctly

### Screenshots/Screen recordings

![Screenshot_20240624-141134](https://github.com/fast4x/RiMusic/assets/145584656/95f8e8fe-67c8-4a09-a0e5-9b67475eb9a5)

### RiMusic version

0.6.39

### Android version

Android 14

**Comment by fast4x** [comment]
Download latest version 0.6.40.1 it's fixed
