### ISSUE TITLE
Lyrics is limited to thumbnail size

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2451]
### Steps to reproduce the bug

https://github.com/fast4x/RiMusic/assets/45353488/b1e50dd0-3c0d-43b3-a804-d3d04381769d

### Expected behavior

The lyrics should take all the available area

### Actual behavior

The lyrics are limited to thumbnail size.

The lyrics are expanded to the available area after the song is changed.

### RiMusic version

0.6.40.1

### Android version

Android 13 HyperOS

**Comment by ALMIGHTY-VC** [comment]
How are u getting such hazy lyrics it seems good i want it too bro care to teach me?

**Comment by aneesh1122** [comment]
> How are u getting such hazy lyrics it seems good i want it too bro care to teach me? 

You mean that glowing lyrics? I implemented it myself and did a pull request. It will be available to you all after fast4x merges my pull request.

If you're asking about removing album cover for lyrics, do this
![Screenshot_2024-06-24-20-56-09-820_it.fast4x.rimusic.debug-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/ded3267c-7a4b-4101-bcf2-ce9c56759111)

**Comment by ALMIGHTY-VC** [comment]
Oh thanks bro u have implemented very creative ideas in this version too 🙌👌

**Comment by aneesh1122** [comment]
> Oh thanks bro u have implemented very creative ideas in this version too 🙌👌

Thanks bro. Many more to come

**Comment by NikunjKhangwal** [comment]
Just out of curiosity since you already know programming, can't you fix it yourself? 🤔

**Comment by aneesh1122** [comment]
> Just out of curiosity since you already know programming, can't you fix it yourself? 🤔

I tried but I couldn't. It's funny that I'm reporting a bug about something I've implemented myself but there are things only fast4x can do 😅

**Comment by NikunjKhangwal** [comment]
> I tried but I couldn't. It's funny that I'm reporting a bug about something I've implemented myself but there are things only fast4x can do 😅

Ah! Beginners struggle. Fair enough

**Comment by aneesh1122** [comment]
> > I tried but I couldn't. It's funny that I'm reporting a bug about something I've implemented myself but there are things only fast4x can do 😅
> 
> Ah! Beginners struggle. Fair enough

https://github.com/fast4x/RiMusic/assets/45353488/4c8bc8ba-0d3a-401c-bc98-0053ecf99441

Bwahahahahaha

**Comment by NikunjKhangwal** [comment]
Now we're talking 👌🏼

**Comment by aneesh1122** [comment]
> Now we're talking 👌🏼

I'm thinking of making this the default option otherwise people won't even know about the new changes. Many are still using lyrics over thumbnail and are surprised when I tell them they can do this too.

**Comment by fast4x** [comment]
Available from version 0.6.41

**Comment by NikunjKhangwal** [comment]
> I'm thinking of making this the default option otherwise people won't even know about the new changes. Many are still using lyrics over thumbnail and are surprised when I tell them they can do this too.

Would be nice. I like it too as it's a good middle ground between fullscreen and thumbnail lyrics. Also it kinda solved two old requests i had which is having gradient behind lyrics and having timeline in fullscreen lyrics. I have minor problem tho. As i'm using button background, it's too close to the next songs strip. Can you increase the spacing?

![photo_2024-06-26_16-52-12](https://github.com/fast4x/RiMusic/assets/99175083/2198b8ef-c889-47d6-b531-bb1f3f840bbf)

**Comment by aneesh1122** [comment]
> > I'm thinking of making this the default option otherwise people won't even know about the new changes. Many are still using lyrics over thumbnail and are surprised when I tell them they can do this too.
> 
> Would be nice. I like it too as it's a good middle ground between fullscreen and thumbnail lyrics. Also it kinda solved two old requests i had which is having gradient behind lyrics and having timeline in fullscreen lyrics. I have minor problem tho. As i'm using button background, it's too close to the next songs strip. Can you increase the spacing?
> 
> ![photo_2024-06-26_16-52-12](https://github.com/fast4x/RiMusic/assets/99175083/2198b8ef-c889-47d6-b531-bb1f3f840bbf)
> 

There's a space when someone activates either the transparent action bar or modern controls because there were cases of overlapping or clipping.

In your case there is no overlapping and I have to give as much area as possible for the expanded player.

**Comment by NikunjKhangwal** [comment]
> There's a space when someone activates either the transparent action bar or modern controls because there were cases of overlapping or clipping.
> 
> In your case there is no overlapping and I have to give as much area as possible for the expanded player.

Ok, Fair enough
