### ISSUE TITLE
Menu button in player action bar is crashing the app

### ISSUE THREAD

**Issue by Anshuman2259** [fast4x/RiMusic#2453]
### Steps to reproduce the bug

Play a song
Click on the menu button at the bottom action bar (turn it on in the settings)
Then the app crashes

### Expected behavior

A menu of the song should have came 

### Actual behavior

But the app crashes 

### Screenshots/Screen recordings

![Screenshot_20240624-190233](https://github.com/fast4x/RiMusic/assets/76805993/153823b8-8c71-4652-adb9-650c4163f00c)

### Logs

Idk where to get em, sorry....

### RiMusic version

0.6.40.1

### Android version

10

**Comment by NikunjKhangwal** [comment]
Go to settings > Miscellaneous (5th option) > copy crash log on bottom

**Comment by Anshuman2259** [comment]
Now the app won't even open, it crashes as soon as it starts, I am using
Lenovo tab

**Comment by NikunjKhangwal** [comment]
I see. Let's wait and see what developer have to say.
