### ISSUE TITLE
App crashes when holding a song in songs tab

### ISSUE THREAD

**Issue by Anshuman2259** [fast4x/RiMusic#2454]
### Steps to reproduce the bug

open songs tab at the bottom
Hold any song
Then app crashes

### Expected behavior

I actually forgot what it used to do tho..

### Actual behavior

the app crashes 

### Screenshots/Screen recordings

![Screenshot_20240624-190537~2](https://github.com/fast4x/RiMusic/assets/76805993/d3646e6f-129f-47c9-9272-436a35646505)

### Logs

Idk where to get em, sorry....

### RiMusic version

0.6.40.1

### Android version

10

### Additional information

Using a tablet

**Comment by ALMIGHTY-VC** [comment]
Settings>miscellaneous>scroll to bottom>debug>enable debug logs
Next time it crashes
>copy crash log to clipboard and please paste it here

**Comment by Anshuman2259** [comment]
Now the app won't even open, it crashes as soon as it starts, I am using
Lenovo tab
