### ISSUE TITLE
Transparent Lyrics Backgrounr

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [fast4x/RiMusic#2455]
### Steps to reproduce the bug

1.Enable transparent lyrics background
2.toggle lyrics using button and thumbnail.

### Expected behavior

Hmm it doesnt work so i dont know what should i expect yeah but a transparent background instead of one looking like green screen

### Actual behavior

The lyrics inside thumbnail have background like green screen

### Screenshots/Screen recordings

![Screenshot_2024-06-24-20-50-57-546_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/112297620/df30097e-759c-4489-8488-f9335ff7c84c)

### RiMusic version

0.6.40.1

### Android version

MIUI 11 A10

### Additional information

Even though i know its minor issue and there are the ones which should we solved on priority basis i still just want to inform you and update me with the issue as per your convenience

New version's transparent timeline bar looks immersive

**Comment by aneesh1122** [comment]
Do what I told you to do previously to have transparent lyrics background.

You're doing it wrong

**Comment by ALMIGHTY-VC** [comment]
> Do what I told you to do previously to have transparent lyrics background.
> 
> You're doing it wrong

Hmm let me recheck what u told im sorry i dont even remember you telling me bout it

**Comment by aneesh1122** [comment]
> > Do what I told you to do previously to have transparent lyrics background.
> > 
> > You're doing it wrong
> 
> Hmm let me recheck what u told im sorry i dont even remember you telling me bout it

https://github.com/fast4x/RiMusic/issues/2488#issuecomment-2190702196

**Comment by ALMIGHTY-VC** [comment]
I

> Do what I told you to do previously to have transparent lyrics background.
> 
> You're doing it wrong

Te tell you the truth i think u didnt told me i searched transparent lyrics background and didnt got it but i tried every player background like :- blurred song cover, song cover, fluid gradient from cover and it always gave a green screen

**Comment by aneesh1122** [comment]
> I
> 
> > Do what I told you to do previously to have transparent lyrics background.
> > 
> > You're doing it wrong
> 
> Te tell you the truth i think u didnt told me i searched transparent lyrics background and didnt got it but i tried every player background like :- blurred song cover, song cover, fluid gradient from cover and it always gave a green screen

https://github.com/fast4x/RiMusic/issues/2451#issuecomment-2186844962

**Comment by ALMIGHTY-VC** [comment]
Oh got it thanks

**Comment by aneesh1122** [comment]
> I was wondering about match lyrics background with player option which came when u toggled show thumbnail for lyrics option but okay i got what i need thanks again aneesh bro

'Match lyrics background color with player' is an old setting and in the next update I've hidden this option if you disable 'show thumbnail for lyrics'.

Right now lyrics are restricted to the thumbnail shape but in the next version it will be unrestricted. Right now I suggest you to keep 'Thumbnail size = Expanded' before you disable 'Show thumbnail'
