### ISSUE TITLE
can't correct translation for enqueue

### ISSUE THREAD

**Issue by ghost** [fast4x/RiMusic#2456]
### Steps to reproduce the bug

1. open https://crowdin.com/editor/rimusic/all/en-uk?view=comfortable&filter=basic&value=0#q=enqueue
2. the translation is incorrect "Зачекайте"
3. try to change the translation to "Поставити у чергу"
4. Save

### Expected behavior

the translation is corrected

### Actual behavior

![Screenshot_20240624-191217_Firefox](https://github.com/fast4x/RiMusic/assets/158172547/9b309eae-be41-48d3-9b26-1ece9dc3b05a)

### RiMusic version

translation

### Android version

translation

**Comment by maboroshin** [comment]
The developer has approved the mistranslation. Your translation will be reflected if This approval is lost or your translation is approved.
Related: https://github.com/fast4x/RiMusic/issues/3483
