### ISSUE TITLE
Animated fake audio bar

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#2458]
### Description

The fake audio bar is cool, but imagine an animated one (technically makes it a fake visualizer)? Also, I had some minor changes for the current one.

### Suggested Solution

Sure, here's the corrected version of the input text:

Make a new option that makes the fake audio bar animated like the visualizer icon on the currently playing song.

Also, in my opinion, the static one should change when changing songs and not when you close and then open the player.

### Alternatives

Make the bar less "moovy" at the start and finish of the bar to feel like a fade.

### Additional Context

I dont think it needs more context.

**Comment by OrangeZXZ** [comment]
Also could you add a fake vizualizator option? (if it adapts to the bpm is enought for me) (if i need to do a new issue im happy to)

**Comment by fast4x** [comment]
Fixed and implemented new with dozens of visualizers, available from version 0.6.41

**Comment by fast4x** [comment]
Look this sample... 🥳🥳
https://github.com/fast4x/RiMusic/assets/1484476/437caf66-46b0-4db9-a990-119e21df78fc

**Comment by OrangeZXZ** [comment]
> Look this sample... 🥳🥳
> https://github.com/fast4x/RiMusic/assets/1484476/437caf66-46b0-4db9-a990-119e21df78fc
> 
> 

This look AWESOME (this is just one of them 🤯)

**Comment by fast4x** [comment]
> > Look this sample... 🥳🥳
> > https://github.com/fast4x/RiMusic/assets/1484476/437caf66-46b0-4db9-a990-119e21df78fc
> > 
> > 
> 
> This look AWESOME (this is just one of them 🤯)

36....
