### ISSUE TITLE
all songs from a playlist have no album

### ISSUE THREAD

**Issue by ghost** [fast4x/RiMusic#2459]
### Steps to reproduce the bug

1. export a playlist
2. clear app data
3. import the playlist
4. play any song

### Expected behavior

i can go ti the album

### Actual behavior

the album button is replaced with a youtube button, and the text is gray

![Screenshot_20240624-192704](https://github.com/fast4x/RiMusic/assets/158172547/f83bd6c3-2acb-4a49-85e8-192f6c514ebd)

when you play it from online search, it shows the album, but then if you add it to favorites and plqy it from there, it's with no album again

### RiMusic version

0.6.36

### Android version

Android 10

**Comment by wglee99** [comment]
Do try to update to the latest version. This could be due to the recent API changes from Youtube which led to issues with albums and playlists. Refer to #2449

**Comment by teacupmaps** [comment]
this is the latest version on f-droid. i downloaded the apk from github and it didn't fix that

**Comment by teacupmaps** [comment]
also i can't go to the author

**Comment by fast4x** [comment]
F-droid  isn't sync to latest github version, wait.

**Comment by teacupmaps** [comment]
i downloaded the apk from github, same
![Screenshot_20240626-155405](https://github.com/fast4x/RiMusic/assets/158172547/0c9c8c58-e7d3-492d-9ccb-cc3dcaa60335)

**Comment by fast4x** [comment]
Fixed available from version 0.6.55
