### ISSUE TITLE
Useless pause button

### ISSUE THREAD

**Issue by Aaniket7** [fast4x/RiMusic#2461]
### Steps to reproduce the bug

![Screenshot_20240624_222651](https://github.com/fast4x/RiMusic/assets/127947643/88daa50e-3193-4367-a7e9-ccefe86c7522)

### Expected behavior

That little useless pause button should be removed...its actually taking the looks of the player down😑

### Actual behavior

Useless extra pause button.

### Screenshots/Screen recordings

![Screenshot_20240624_222651](https://github.com/fast4x/RiMusic/assets/127947643/cee353f6-bb39-44e7-aaf9-49066038e772)

### RiMusic version

0.6.40.1

### Android version

Android 14

### Additional information

Please remove that extra paise button from main player.

**Comment by aneesh1122** [comment]
I think I can remove that. Should I? @fast4x

**Comment by fast4x** [comment]
> I think I can remove that. Should I? @fast4x 

ok but comment code not delete please

**Comment by aneesh1122** [comment]
> > I think I can remove that. Should I? @fast4x 
> 
> ok but comment code not delete please 

Okay I'll just disable it

**Comment by aneesh1122** [comment]
Done
![Screenshot_2024-06-24-23-25-20-580_it.fast4x.rimusic.debug-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/e7f00e80-cf24-4149-9d86-78d8ba776c01)

**Comment by aneesh1122** [comment]
> How can i activate it like you the full screen cover? @aneesh1122 
> 

https://github.com/fast4x/RiMusic/assets/45353488/adddab84-8af3-4293-951b-60bddb2f9ca1

**Comment by twistios** [comment]
It did not happen for me. Did it need a specific configuration?

**Comment by aneesh1122** [comment]
> It did not happen for me. Did it need a specific configuration?

Yeah. The configuration is "skip 5 days" 😂😂😂. JK

My implementation is merged now. You'll get it in the next update.

**Comment by twistios** [comment]
> > It did not happen for me. Did it need a specific configuration?
> 
> Yeah. The configuration is "skip 5 days" 😂😂😂. JK
> 
> My implementation is merged now. You'll get it in the next update.
I meant the additional pause button. I can only see a single one.

**Comment by aneesh1122** [comment]
> > > It did not happen for me. Did it need a specific configuration?
> > 
> > 
> > Yeah. The configuration is "skip 5 days" 😂😂😂. JK
> > My implementation is merged now.
> > You'll get it in the next update.
> 
> I meant the additional pause button. I can only see a single one.

oh. you'll have to disable 'show remaining song duration'

**Comment by Its-Tony** [comment]
Aneesh, Can you fork Blackhole repo(still available) or import from apk, RiMusic is good but there is need of JioSaavn API in RiMusic. I'm using both blackhole and Rimusic but blackhole offer some good features over RiMusic like downloading(m4a) with embedded lyrics and metadata, also 320kbps audio. Issue in current version of Blackhole is it shows lyrics in UTF-8(shows only English alphabet other language become distorted like a code or something).
![Screenshot_2024-06-24-20-38-30-615_com shadow blackhole](https://github.com/fast4x/RiMusic/assets/172184183/80477f7a-f662-495b-be32-656de62f34a5)

**Comment by aneesh1122** [comment]
> Aneesh, Can you fork Blackhole repo(still available) or import from apk, RiMusic is good but there is need of JioSaavn API in RiMusic. I'm using both blackhole and Rimusic but blackhole offer some good features over RiMusic like downloading(m4a) with embedded lyrics and metadata, also 320kbps audio. Issue in current version of Blackhole is it shows lyrics in UTF-8(shows only English alphabet other language become distorted like a code or something).
> ![Screenshot_2024-06-24-20-38-30-615_com shadow blackhole](https://github.com/fast4x/RiMusic/assets/172184183/80477f7a-f662-495b-be32-656de62f34a5)
> 

I don't know much about kotlin. The most I can do is change things related to UI.

JioSaavn API won't affect RiMusic's privacy so I think @fast4x can implement it.

He won't implement downloading songs though.

**Comment by Its-Tony** [comment]
Along with audio quality,Problem in RiMusic is that if we search playlist it mostly shows them from YouTube(videos) which has intro outro, sponsor ads. It need sponsorblock. JioSaavn API can be provided as optional feature.

**Comment by fast4x** [comment]
Yes it's planned, create a feature request please

**Comment by fast4x** [comment]
Done, available from version 0.6.41

**Comment by aneesh1122** [comment]
> Yes it's planned, create a feature request please

jiosaavn is planned? or sponsorblock?

**Comment by fast4x** [comment]
Sponsorblock

**Comment by aneesh1122** [comment]
> Along with audio quality,Problem in RiMusic is that if we search playlist it mostly shows them from YouTube(videos) which has intro outro, sponsor ads. It need sponsorblock. JioSaavn API can be provided as optional feature.

all the trending youtube playlists contains music videos. if you have youtube premium and you open a music video in YTM it will automatically start playing album audio version of it.

This is server sided so RiMusic can't do anything about it.

**Comment by aneesh1122** [comment]
> Sponsorblock

any plans for JioSaavn? 😅

**Comment by fast4x** [comment]
Sorry, not.

**Comment by Its-Tony** [comment]
New chart feature doesn't showing any data in India. Is it working for you? @aneesh1122 
@fast4x

**Comment by aneesh1122** [comment]
> New chart feature doesn't showing any data in India. Is it working for you? @aneesh1122 
> @fast4x 

Nope. I was about to create a new bug issue about it.

**Comment by fast4x** [comment]
![Screenshot_2024-06-29-07-29-51-703_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/cc8376cc-af3b-44ed-adc0-d08156cc4926)

**Comment by fast4x** [comment]
I'll build a custom version to check problems for India
