### ISSUE TITLE
need comments for translation

### ISSUE THREAD

**Issue by ghost** [fast4x/RiMusic#2464]
### Steps to reproduce the bug

translate rimusic on crowdin 

### Expected behavior

Excluded %s songs: is the %s a number or something else?
Apple: is this the fruit or the brand?
Large, Expanded: what noun is it used with?
Piped, PIPED: should be said that this is not an acronym or verb in past tense, but a website, or just made not translatable
Icon button player: what is this
Brilliant: does this mean excellent?
Breaked: is this a misspelling?

### Actual behavior

no comments for translators

### RiMusic version

translation

### Android version

translation

**Comment by fast4x** [comment]
%s will be replaced by number value...

**Comment by fast4x** [comment]
You can move parameter in any point... before, after, inside text

**Comment by teacupmaps** [comment]
i mean plural forms
"4 songs" is "4 піс**ні**"
"5 songs" is "5 піс**ень**"
maybe it needs to be "%d" instead of "%s" to work?

**Comment by teacupmaps** [comment]
mastodon example
![Screenshot_20240624-223333_Firefox](https://github.com/fast4x/RiMusic/assets/158172547/72e2e872-9268-42b8-a841-e103a7ce91dc)

**Comment by fast4x** [comment]
I'll check for plural

**Comment by teacupmaps** [comment]
also, is %s in "January %s", "February %s" the day or year? currently it's translated as if it was year
