### ISSUE TITLE
The app crashes after updating it.

### ISSUE THREAD

**Issue by AlexIhmisviha** [fast4x/RiMusic#2466]
### Steps to reproduce the bug

1- Updating The app to 0.6.40.1 via F-Droid or Github
2- Opening The App and sometimes only closes and sometimes outpost a Android Error

### Expected behavior

I guess I should just open and show the songs, AND conserve The preferences and quick picks info

### Actual behavior

Crashes after Opening The app.

### RiMusic version

0.6.40.1

### Android version

Android 14

### Additional information

The bug seems to be fixed after deleting the application data.

**Comment by fast4x** [comment]
If occur again, paste here the log

**Comment by Myckaaa** [comment]
![Screenshot_2024-06-25-11-01-32-670_com miui bugreport](https://github.com/fast4x/RiMusic/assets/173790380/d2b49aa7-2d71-4a2e-be8e-df26dca485e1)
Same error. App crashes every few minutes

**Comment by fast4x** [comment]
Paste here the crash log from miscellaneous settings... 
Enable debug in miscellaneous settings, restart app and after crash, go to miscellaneous and copy crash log.

**Comment by Myckaaa** [comment]
2024-06-25T13:07:58.765:	android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
	 android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method) 
	 android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(Unknown Source:30) 
	 android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(Unknown Source:16) 
	 android.database.sqlite.SQLiteStatement.executeInsert(Unknown Source:20) 
	 r3.i.b(SourceFile:3) 
	 l3.h.o(SourceFile:8) 
	 i6.o.C0(SourceFile:11) 
	 A6.T.c(SourceFile:131) 
	 G0.u.run(SourceFile:13) 
	 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1251) 
	 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:668) 
	 java.lang.Thread.run(Thread.java:1012)
