### ISSUE TITLE
Small weird UI elements

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#247]
### Description

There are 3 UI "glitches" that I hapened to notice

The New bar has a little bar at the tip:
![SmartSelect_20231218_063812](https://github.com/fast4x/RiMusic/assets/104271365/3fac72a2-3b01-467e-9f3a-124b0c7e6008)

The circle at the top right isn't round enought:
![SmartSelect_20231218_063839](https://github.com/fast4x/RiMusic/assets/104271365/b8109a96-2809-4caf-8a3a-2d5fd8a32d51)

There is this weird superposition when moving the bottom bar up:
![Screenshot_20231218_063947](https://github.com/fast4x/RiMusic/assets/104271365/44f0e180-409a-44f1-9d86-560d7f8a7dd7)

For some reason the audio visualizer is max out when there is not audio it should be at 0:
![Screenshot_20231218_065922.jpg](https://github.com/fast4x/RiMusic/assets/104271365/9166b9d9-8c90-41c9-a38e-b020ad669e4b)

### Suggested Solution

Remove the glitch on the new bar

Make the circle rounder or even romove the circle because it makes incosistent with the other buttons:
![SmartSelect_20231218_065229](https://github.com/fast4x/RiMusic/assets/104271365/9c7679b5-275a-4991-b8e7-e13f23e204f6)

Make the song list apear bellow the bottom bar like in this example i made on my phone:
![20231218_064134](https://github.com/fast4x/RiMusic/assets/104271365/c54a88fe-3a71-4b4d-bd1c-25f5aec5e6b3)

Make the audio visualizer go to 0 when there is no audio instead of 100

### Alternatives

I have an alternative animation for the bottom bar but i need to be on my PC to make it

### Additional Context

Ive seen a lot of issues lately don't discourage yourself do at your own paste!

**Comment by OrangeZXZ** [comment]
Oh yeah forgot to say but the lyrics background and audio visualiser background dosen't have the same opacity i think it should be darker on the audio visualizer

**Comment by NEVARLeVrai** [comment]
![IMG_20231218_073733.jpg](https://github.com/fast4x/RiMusic/assets/63956787/a94f44e7-2ee0-4384-adde-68e7f8c05d0a)

Also background is not dark on the whole album, when we have visualizer enabled

**Comment by fast4x** [comment]
It’s supposed to have bugs, it’s growing fast.

**Comment by fast4x** [comment]
Removed circle background
Available from version 0.6.14

**Comment by fast4x** [comment]
It is not at max without audio, it is a pie that is deformed when there is music...

**Comment by fast4x** [comment]
Removed little bar at the tip

**Comment by fast4x** [comment]
Visualizer improvements

**Comment by fast4x** [comment]
"There is this weird superposition when moving the bottom bar up"
I couldn’t reproduce the problem.

**Comment by OrangeZXZ** [comment]
> "There is this weird superposition when moving the bottom bar up" I couldn’t reproduce the problem.

you tried slowly pull up the bar without pressing any button?

**Comment by fast4x** [comment]
Try

**Comment by OrangeZXZ** [comment]
> Try

https://github.com/fast4x/RiMusic/assets/104271365/543e0484-5997-416f-8780-f74612b81bc4
