### ISSUE TITLE
1. Search Bars in Album and Artist page 2. Searching albums with artist name

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#2471]
### Description

After using the app for a long time now my list of artist and albums have gotten quite big. It's a pain trying to find a specific entry when it's situated somewhere in the middle.

### Suggested Solution

Add search bars in artist and albums page just like we have in songs for making the process easier. Additionally it would be cool if we can search by artist name in albums page.

![IMG_20240625_075644](https://github.com/fast4x/RiMusic/assets/99175083/a1464f80-7408-4fa6-9ee7-cf0722da9e2d)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.41
