### ISSUE TITLE
[Feature]: Option to disable play button shadows 

### ISSUE THREAD

**Issue by 4manog** [fast4x/RiMusic#2472]
### Description

![Screenshot_2024-06-25-11-33-43-349_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/173764311/fef620fb-e86b-4113-88d9-2cedc9f75b04)

### Suggested Solution

There should be an option to disable the play button shadow and the play button below the timeline bar.

**Comment by aneesh1122** [comment]
2nd is already implemented and will be available to you from the next update.

You can disable the shadows by choosing essential controls.

@fast4x could you please disable shadows for only disabled modern control?

**Comment by fast4x** [comment]
Not, because modern controls must have shadow, in the future would be added other controls type.

**Comment by fast4x** [comment]
Is possible swap timeline with controls from settings
