### ISSUE TITLE
Couldn't find a playable audio format

### ISSUE THREAD

**Issue by LEOSCHUMY** [fast4x/RiMusic#2475]
### Steps to reproduce the bug

1a. Search "MP2 - Entro il 23". ---> not found
1b Use YouTube link https://www.youtube.com/watch?v=K-HEq1qyQ3Y in "go to link" search
2. Click on the song 

### Expected behavior

Play song

### Actual behavior

Message "Couldn't find a playable audio format"

### Screenshots/Screen recordings

![Screenshot_20240625-142010_RiMusic](https://github.com/fast4x/RiMusic/assets/37011404/34397151-65f9-4963-a7f9-02a25c00b3c5)

### RiMusic version

0.6.40.1

### Android version

Android 14

**Comment by fast4x** [comment]
Fixed, available from version 0.6.41

**Comment by LEOSCHUMY** [comment]
Same issue in 0.6.41.
