### ISSUE TITLE
UI bug in Floating action button 

### ISSUE THREAD

**Issue by ankitkumar1302** [fast4x/RiMusic#2477]
# Bug Report

## Description
Start any music and there is overlap of a music bar and the search action button.

## Steps to Reproduce
1. Open the application.
2. Play any music.
3. Observe the overlap of the music bar and the search action button.

## Screenshot
![bug](https://github.com/fast4x/RiMusic/assets/95230112/808c2993-f4c7-490b-af3d-f7e67e26232f) 

Please address this issue to improve the user experience. Thank you!

## Expected Result
The music bar and the search action button should not overlap and should be clearly visible and accessible.

## Actual behaviour
The music bar overlaps with the search action button, causing a UI issue. 

### RiMusic version

Latest 

### Android version

**OS Version:** 10

**Comment by aneesh1122** [comment]
Hold the floating search icon and place it anywhere you want

**Comment by ankitkumar1302** [comment]
Okk thanks...
