### ISSUE TITLE
[Feature]: Unify UI settings

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#248]
### Description

Appearance settings are in Appearance, UI and Player. Timeline settings are duplicated in UI and Player.

### Suggested Solution

Appearance settings should be in one tab - for example UI with chapters Appearance, Player, Effects, etc.

Other settings related to UI/Player but not Appearance, e.g. App language would be in the second tab.

**Comment by ikanakova** [comment]
This is my suggestion:

- UI
    - LANGUAGES
                - App language
    - PLAYER PREFERENCES
                - Min listening time
                - Persistent queue
                - Resume playback
                - Close background player
                - Skip silence
                - Loudness normalization
                - Equalizer

- Appearance
    - UI
                - Interface in use
                - Theme
                - Theme mode
     - PLAYER
                - Thumbnail roundness / Thumbnail Size (I believe it's the same thing = duplicity in Appearance, UI and Player.)
                - Disable horizontal swipe
                - Timeline (duplicity in UI and Player)
                - Play button
                - Rotating buttons
                - Visualizer (duplicity in UI and Player)
                - Toggle lyrics
    - TEXT
                - Use system font
                - Apply font padding


Cache, Database, Other, About leave as is.

**Comment by fast4x** [comment]
Great, actually UI settings Is born like First release for ViMusic fan.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.14
