### ISSUE TITLE
Stuck in repeating one song all the time

### ISSUE THREAD

**Issue by christian179717** [fast4x/RiMusic#2480]
### Steps to reproduce the bug

Play one song, doesn't matter if started from playlist or searched for one and enqued then other songs.

### Expected behavior

Should jump to the next song after finishing the first one.

### Actual behavior

Repeats the first one forever.

### Screenshots/Screen recordings

![Screenshot_20240625_215523_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89655752/7e718816-a08b-46a7-aaaa-00fcda1b06f5)
![Screenshot_20240625_215531_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89655752/50bb42db-f8b4-4b94-8f0e-cababf0ebdd5)
I tried different settings here but no worked for me.

### RiMusic version

0.6.40.1

### Android version

Android 9

**Comment by ildar** [comment]
have the same glitch. Stuck on repeat.
how can I/we debug that? logs maybe? I can `sqlite` if relevant.

**Comment by faustaahmad** [comment]
Disable loop song

**Comment by christian179717** [comment]
Where can I do this?

**Comment by faustaahmad** [comment]
![](https://github.com/user-attachments/assets/b9744265-dfd2-4554-adf2-35029770436a)

**Comment by christian179717** [comment]
Look in the upper screenshots.
Even though it's deactivated, it stuck in repeating.

**Comment by faustaahmad** [comment]
Sorry, but could you atleast click the player loop button again? (Not in queue)
I dont think it's disabled (different color compared to expanded player and sleep button)
