### ISSUE TITLE
miscellaneous loads slowly

### ISSUE THREAD

**Issue by veloal** [fast4x/RiMusic#2483]
### Steps to reproduce the bug

go to settings, select the miscellaneous option and any other option. 

### Expected behavior

it should load as smoothly as the other options

### Actual behavior

the miscellaneous option does not load as smoothly as the others

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/170187968/6d23aa5d-e747-4a76-802f-98df4aac837b

### RiMusic version

0.6.40 and 0.6.41

### Android version

Android 9. EMUI 9

**Comment by fast4x** [comment]
Why is a bug for you?

**Comment by veloal** [comment]
> Why is a bug for you?
I don't know if this is really an error or not, but it didn't happen before. 

I upload videos with version 0.6.36.1 and version 0.6.40.1

I just uninstall and install the versions, only modifying the navigation bar. 


https://github.com/fast4x/RiMusic/assets/170187968/9461989b-ece0-4e42-a586-dd70fb0778e7


https://github.com/fast4x/RiMusic/assets/170187968/4d8a9046-e84a-42b5-95b7-c8a89183f5b8
