### ISSUE TITLE
Add two new sources option for synchronized lyrics as done in SongSync (https://apt.izzysoft.de/fdroid/index/apk/pl.lambada.songsync)

### ISSUE THREAD

**Issue by Wjxfi** [fast4x/RiMusic#2484]
Spotify and Netease

**Comment by aneesh1122** [comment]
Spotify lyrics are for premium users only. I don't think it fetches from Spotify anymore

**Comment by aneesh1122** [comment]
> > Spotify lyrics are for premium users only. I don't think it fetches from Spotify anymore
> 
> Not true @aneesh1122 
> SpotifyLyricsAPI is used
> It works

![Screenshot_2024-06-26-03-47-53-492_com.github.android-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/22932e7a-a5a5-4b0a-9b9b-8a82f466ef81)

Don't you need to login for this?

**Comment by fast4x** [comment]
Why fo you want lyrics from Spotify?

**Comment by fast4x** [comment]
Spotify require api key and code for songs aren't the same of YTM.
RiMusic work only with YT/YTM source...

**Comment by fast4x** [comment]
RiMusic can't use api key and trackers.
