### ISSUE TITLE
from synchronized lyrics to unsynchronized lyrics instead of error.

### ISSUE THREAD

**Issue by Wjxfi** [fast4x/RiMusic#2485]
If no synchronized songs are found, instead of showing an error message, show unsynchronized songs, and if they are not found, show nothing, just the cover art, without error messages and with saving the preference to show lyrics, synchronized or unsynchronized.

**Comment by fast4x** [comment]
Not planned

**Comment by fast4x** [comment]
Isn't not an error but an alert that inform user.

**Comment by jaki444** [comment]
one question: as the person asked, I don't understand why you don't like this idea, I get it, you are the programmer and you make your choices and we adapt, but I don't see where is the problem with putting in the settings auto-switch that if activated it allows you to set the preference of the lyrics(sinc or not sinc) and when it is activated if pressed the lyrics function make it show firstly that one chosen as preference, if it doesn't find it it shows the other and then if there is no other it doesn't show anything. Something like that is done by the vitune project(I think). Anyway you decide and we adapt, it's just to understand. Sorry if I sound rude.

PS: I downloaded vitune and it does a similar thing to what we would like that is to autochange if synchronized things are enabled.

**Comment by fast4x** [comment]
Ok right, I'll implement it

**Comment by fast4x** [comment]
Implemented, available from version 0.6.41

**Comment by jaki444** [comment]
great job fast4x. congratulations.

**Comment by aneesh1122** [comment]
Guys, there are times when it fetches lyrics from lrclib and if the first lyric found is unsynced one it shows that the synced lyrics are unavailable even though synced lyrics are available maybe at 2nd or 3rd position.

So, automatically switching to non synced lyrics will allow me to manually pick up synced lyrics from the list. Right?
