### ISSUE TITLE
Overlapping Artist and Title name

### ISSUE THREAD

**Issue by pijiey2** [fast4x/RiMusic#2488]
### Steps to reproduce the bug

When play the music, it's overlapping 

### Expected behavior

No overlapping 

### Actual behavior

The name and title of artist is overlapping as shown on the image 

### Screenshots/Screen recordings

![PXL_20240626_033726271](https://github.com/fast4x/RiMusic/assets/173869342/177c0b69-4c7a-4d22-8f3c-48ea4c36839d)

### RiMusic version

0.6.40.1

### Android version

13

### Additional information

Android car player, NWD_K2501(T5)

**Comment by aneesh1122** [comment]
It's not really overlapping. The title is getting on the status bar a little. Was this problem present in previous versions too?

Btw disable 'show thumbnail' from settings and then enable lyrics.

**Comment by pijiey2** [comment]
Ah yes yes, thats right, its not on the center, just more on the top. I'm not sure about the previous version since i just installed it today.

Sure, I'll try the new layout!

**Comment by aneesh1122** [comment]
> Ah yes yes, thats right, its not on the center, just more on the top. I'm not sure about the previous version since i just installed it today.
> 
> Sure, I'll try the new layout!

Installed it today? You should play with settings a little. You can make your player look very different. This is how I use it

![Screenshot_2024-06-26-09-47-43-752_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/45353488/04166011-5cfd-49f3-a763-9730d63461ac)

And here's the lyrics view

![Screenshot_2024-06-26-09-47-58-652_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/45353488/a11654f8-d0cd-49ac-bbc3-9fd92e734779)

**Comment by pijiey2** [comment]
Wow, that's look very different, aight, I'll try mess with the setting first, thanks man

**Comment by aneesh1122** [comment]
> Wow, that's look very different, aight, I'll try mess with the setting first, thanks man 

If you need help you can always ask me. I'll tell you what settings to change to achieve this look.

**Comment by pijiey2** [comment]
Yes, can you show me the setting to get that look? Its look amazing

**Comment by aneesh1122** [comment]
![IMG_20240626_101912.jpg](https://github.com/fast4x/RiMusic/assets/45353488/e38375a0-a70a-4c3c-9f05-29077a6a4965)

![IMG_20240626_101724.jpg](https://github.com/fast4x/RiMusic/assets/45353488/608838ee-b097-4eb8-b1eb-da84427ebcdf)

![IMG_20240626_101925.jpg](https://github.com/fast4x/RiMusic/assets/45353488/0ffd3591-0f66-4112-bc21-f6133d28c98d)

https://github.com/fast4x/RiMusic/assets/45353488/097524cf-8581-4073-8c94-bebb09f82047

**Comment by pijiey2** [comment]
I test with both devices, my phone and car. Here the ss.

![PXL_20240626_050450597~2](https://github.com/fast4x/RiMusic/assets/173869342/24c4aa37-2586-4474-ad1d-b26ab12a21c3)
I think it shift to the top a bit on my car

![Screenshot_20240626-130431](https://github.com/fast4x/RiMusic/assets/173869342/7344db4c-9e96-4447-a71b-3abd8d1f7ae9)
On my device, it looks great

**Comment by aneesh1122** [comment]
> I test with both devices, my phone and car. Here the ss.
> 
> ![PXL_20240626_050450597~2](https://private-user-images.githubusercontent.com/173869342/343015327-24c4aa37-2586-4474-ad1d-b26ab12a21c3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzk2ODQsIm5iZiI6MTcxOTM3OTM4NCwicGF0aCI6Ii8xNzM4NjkzNDIvMzQzMDE1MzI3LTI0YzRhYTM3LTI1ODYtNDQ3NC1hZDFkLWIyNmFiMTJhMjFjMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwNTIzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2RhOTBlM2I2ZmNhOGY4NzhiYjEwYTE1NWY1OGFkMzU2YmMzNDZkMWYzNmJlNmQ5NTRiZjM4OGQxODg4NzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6vaGnqIl_lYU0PasiqYlVSt8sDMK8RhRfj-LApZPTTg) I think it shift to the top a bit on my car
> 
> ![Screenshot_20240626-130431](https://private-user-images.githubusercontent.com/173869342/343015437-7344db4c-9e96-4447-a71b-3abd8d1f7ae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzk2ODQsIm5iZiI6MTcxOTM3OTM4NCwicGF0aCI6Ii8xNzM4NjkzNDIvMzQzMDE1NDM3LTczNDRkYjRjLTllOTYtNDQ0Ny1hNzFiLTNhYmQ4ZDFmN2FlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwNTIzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODM4ZGEyOTM0Nzg5YzQ0YTA5NTEzNzc2YTQ5Yjc4ZjU3ZGIzODliZTUyMDRjODc5N2U1NTliNjJkZDA3N2MxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ooeDe-rQRp2Eq1yvRcZS7ga3xZb0AtmBUHI6r2KuQR4) On my device, it looks great

android auto seems to have some padding issues.

@fast4x what do you think?

**Comment by pijiey2** [comment]
![PXL_20240626_053929132](https://github.com/fast4x/RiMusic/assets/173869342/320232cd-0639-4138-a625-b6d25f3061d2)

Yep, lyrics works  fine. Only the font and color looks a little weird 😅

![PXL_20240626_054557175](https://github.com/fast4x/RiMusic/assets/173869342/ace192de-7474-4d0f-abc4-853462551e5b)

Btw, my car player resolution is 1024x600

**Comment by fast4x** [comment]
But is Android Auto ir Android Automotive Os?

**Comment by pijiey2** [comment]
> But is Android Auto or Android Automotive Os?

I think it's called Android Head unit, not android auto

**Comment by aneesh1122** [comment]
> ![PXL_20240626_053929132](https://github.com/fast4x/RiMusic/assets/173869342/320232cd-0639-4138-a625-b6d25f3061d2)
> 
> Yep, lyrics works  fine. Only the font and color looks a little weird 😅
> 
> ![PXL_20240626_054557175](https://github.com/fast4x/RiMusic/assets/173869342/ace192de-7474-4d0f-abc4-853462551e5b)
> 
> Btw, my car player resolution is 1024x600

Increase the font size. Keep it at least 'heavy'

I've added an option to disable the text outline in the new version.

**Comment by pijiey2** [comment]
![PXL_20240626_055835499~2](https://github.com/fast4x/RiMusic/assets/173869342/6d573d41-3907-491d-ba20-e5b1105ba1d1)

I just used the expand button for now

![PXL_20240626_055851153](https://github.com/fast4x/RiMusic/assets/173869342/e31a5d9e-f65a-4b45-8a60-8a7e2fb4385b)

And change the font to Poppins, with large size. Looks better now except the color 😊

**Comment by aneesh1122** [comment]
> Looks better now except the color

Must be an issue with screen resolution. Don't worry, in the next version you can disable the black outline of lyrics.

Your mobile doesn't have this color problem. Right?

**Comment by pijiey2** [comment]
> > Looks better now except the color
> 
> Must be an issue with screen resolution. Don't worry, in the next version you can disable the black outline of lyrics.
> 
> Your mobile doesn't have this color problem. Right?

![Screenshot_20240626-141506](https://github.com/fast4x/RiMusic/assets/173869342/83791367-2d52-4546-bf5c-0038572ee317)

Yep. Looks fine here, white font with black outline

**Comment by aneesh1122** [comment]
Alright man, now you can disable the black outline.

Try it and let me know how it's looking now

**Comment by pijiey2** [comment]
> Alright man, now you can disable the black outline.
> 
> Try it and let me know how it's looking now

![PXL_20240629_060343012](https://github.com/fast4x/RiMusic/assets/173869342/9a8712ba-cacb-49eb-ba81-633bab0824f5)
![PXL_20240629_060448361](https://github.com/fast4x/RiMusic/assets/173869342/b16c419a-3bec-48e2-b6b3-ae5287c29e7e)
![Screenshot_20240629-140457](https://github.com/fast4x/RiMusic/assets/173869342/44942c21-a58a-4f4b-986f-409ef1663123)

Yep looking good now, but the expended toggle is missing after the update 😅

**Comment by aneesh1122** [comment]
> but the expended toggle is missing after the update

Yeah. I had to disable it for landscape mode. One guy created an issue that the 'expanded player' is not working. So I disabled it for landscape mode so that there won't be any useless issues.

btw you can enable glow. it will look good.

**Comment by pijiey2** [comment]
I see. Alright no problem. If the issues is solved later, please added back the expended toggle, because i used it to make the title and artist location center. 🫡 Not shift up to the navigation bar

**Comment by aneesh1122** [comment]
> I see. Alright no problem. If the issues is solved later, please added back the expended toggle, because i used it to make the title and artist location center. 🫡 Not shift up to the navigation bar

In the settings in the next update you can find a setting which will add extra space on the top. Let's see if that much of space is enough for you. If not, I'll increase the space.

**Comment by pijiey2** [comment]
> > I see. Alright no problem. If the issues is solved later, please added back the expended toggle, because i used it to make the title and artist location center. 🫡 Not shift up to the navigation bar
> 
> In the settings in the next update you can find a setting which will add extra space on the top. Let's see if that much of space is enough for you. If not, I'll increase the space.

Noted and thanks!

**Comment by aneesh1122** [comment]
> > > I see. Alright no problem. If the issues is solved later, please added back the expended toggle, because i used it to make the title and artist location center. 🫡 Not shift up to the navigation bar
> > 
> > 
> > In the settings in the next update you can find a setting which will add extra space on the top. Let's see if that much of space is enough for you. If not, I'll increase the space.
> 
> Noted and thanks!

you're welcome. Let me know if you need anything else. If it's possible for me I'll do it.

**Comment by aneesh1122** [comment]
Go to settings -> miscellaneous. In this page you will find "Android Head Unit". Enable "Extra space at top" and tell me if the spacing is enough.

**Comment by pijiey2** [comment]
> Go to settings -> miscellaneous. In this page you will find "Android Head Unit". Enable "Extra space at top" and tell me if the spacing is enough.

Alright mate 🫡

**Comment by pijiey2** [comment]
> Go to settings -> miscellaneous. In this page you will find "Android Head Unit". Enable "Extra space at top" and tell me if the spacing is enough.

I think we need more

![PXL_20240706_232955878](https://github.com/fast4x/RiMusic/assets/173869342/59186ca5-5997-466c-844e-e707179f764a)
Before

![PXL_20240706_232933051](https://github.com/fast4x/RiMusic/assets/173869342/5226b816-a30d-41f2-882d-4f80f288b8d1)
After

**Comment by aneesh1122** [comment]
> I think we need more

It's far away from your status bar now. Isn't that enough?

**Comment by pijiey2** [comment]
> > I think we need more
> 
> It's far away from your navigation bar now. Isn't that enough?

Yep, looks good now, thanks man

**Comment by aneesh1122** [comment]
> > > I think we need more
> > 
> > 
> > It's far away from your navigation bar now. Isn't that enough?
> 
> Yep, looks good now, thanks man

you're welcome. I'm working on something. maybe you'll like it.

**Comment by aneesh1122** [comment]
> please added back the expended toggle, because i used it to make the title and artist location center.

You only want it at centre? Bottom is not good?

**Comment by pijiey2** [comment]
> > please added back the expended toggle, because i used it to make the title and artist location center.
> 
> You only want it at centre? Bottom is not good?

Android head unit in my car always on landscape mode. It's look nice with expended toggle on.

**Comment by aneesh1122** [comment]
> > > please added back the expended toggle, because i used it to make the title and artist location center.
> > 
> > You only want it at centre? Bottom is not good?
> 
> Android head unit in my car always on landscape mode. It's look nice with expended toggle on.

What if you use the expanded player and it brings everything to the bottom instead of the center?

**Comment by pijiey2** [comment]
> > > > please added back the expended toggle, because i used it to make the title and artist location center.
> > > 
> > > 
> > > You only want it at centre? Bottom is not good?
> > 
> > 
> > Android head unit in my car always on landscape mode. It's look nice with expended toggle on.
> 
> What if you use the expanded player and it brings everything to the bottom instead of the center?

Yeah, i could try 😆

**Comment by aneesh1122** [comment]
> > > > > please added back the expended toggle, because i used it to make the title and artist location center.
> > > > 
> > > > 
> > > > You only want it at centre? Bottom is not good?
> > > 
> > > 
> > > Android head unit in my car always on landscape mode. It's look nice with expended toggle on.
> > 
> > What if you use the expanded player and it brings everything to the bottom instead of the center?
> 
> Yeah, i could try 😆

https://github.com/fast4x/RiMusic/assets/45353488/25751c3e-07ce-4826-aa23-cb3114a89c63

How is this?

**Comment by pijiey2** [comment]
It's look clean, go for it then 👍🏻

**Comment by aneesh1122** [comment]
try the new custom version and tell me if it's working fine. I also added a new landscape layout so try that out too

**Comment by pijiey2** [comment]
> try the new custom version and tell me if it's working fine. I also added a new landscape layout so try that out too

wheres the link? sorry im new to github. didnt see any custom version at the release pages

**Comment by pijiey2** [comment]
> try the new custom version and tell me if it's working fine. I also added a new landscape layout so try that out too

aightt thanks, will update later :)

**Comment by pijiey2** [comment]
![PXL_20240709_223314614](https://github.com/fast4x/RiMusic/assets/173869342/25ed0ce1-369b-46fd-b347-66c0386708fa)

Wow, the landscape layout is beautiful. Now imma stick with this

**Comment by aneesh1122** [comment]
> ![PXL_20240709_223314614](https://github.com/fast4x/RiMusic/assets/173869342/25ed0ce1-369b-46fd-b347-66c0386708fa)
> 
> Wow, the landscape layout is beautiful. Now imma stick with this

That's great. I've worked hard on this one. Enjoy.

You can disable "show thumbnail" and use the expanded player icon to bring down the song's name and other things. Try that and show me how it's looking

**Comment by pijiey2** [comment]
![PXL_20240919_022149428~2](https://github.com/user-attachments/assets/14abae5a-f767-4613-8cd1-92a0733a5bcf)
![PXL_20240919_022124718](https://github.com/user-attachments/assets/70a35e7c-bace-4ad8-811c-f00be2e62892)

My man, im in latest ver. Is there any way to fix this? Both type , essential and modern

**Comment by aneesh1122** [comment]
In modern player. long tap the playing album cover. a box will appear. There will be 2 sliders. 1st slider is your now playing album cover distance from the edge and the 2nd slider is distance between album covers.

**Comment by pijiey2** [comment]
> In modern player. long tap the playing album cover. a box will appear. There will be 2 sliders. 1st slider is your now playing album cover distance from the edge and the 2nd slider is distance between album covers.

Alright, will try it! Thanks!

**Comment by aneesh1122** [comment]
> > In modern player. long tap the playing album cover. a box will appear. There will be 2 sliders. 1st slider is your now playing album cover distance from the edge and the 2nd slider is distance between album covers.
> 
> Alright, will try it! Thanks!

Here's the video

https://github.com/user-attachments/assets/b2ca7761-b318-42d7-bd8d-e98f2ee2f720

adjust according to your needs
