### ISSUE TITLE
Skip song if not found 

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#2498]
### Description

With these errors

-An unknown playback error occurred
– The requested video ID was not found

the music stops.

It would be good if, in the event of these errors, the player would automatically jump to the next song in the queue, with a simultaneous notification as to which song was skipped. To possibly delete the song to keep his library clean.

This way you could listen to music without interruption and not have to open the app to start playback again.

### Suggested Solution

X

**Comment by fast4x** [comment]
Implemented, available from version 0.6.41

**Comment by siggi1984** [comment]
thanks bro, for the implementation

**Comment by fast4x** [comment]
You are welcome
