### ISSUE TITLE
[Bug] Song are beeing randomly skipped while played

### ISSUE THREAD

**Issue by Uneccessary** [fast4x/RiMusic#2499]
### Steps to reproduce the bug

1. Listen to a random Playlist with many Songs
2. You will realize that it sometimes songs are just skipped while they play

### Expected behavior

Songs play normal as supposed to be.

### Actual behavior

Songs are randomly skip after 10s-1mins when played.

### RiMusic version

0.6.40.1

### Android version

Android 12

### Additional information

Could this be related to this?

https://www.androidpolice.com/youtube-videos-skip-to-end-if-you-use-an-ad-blocker/

**Comment by fast4x** [comment]
Skip if an error occur...

**Comment by Uneccessary** [comment]
I don't consider as beeing fixed at all, in fact this happen with specific songs over and over again. Just for e.g. Bones by Imagine Dragons, but when you skip back the Song plays normal as supposed to be.
