### ISSUE TITLE
Translate issue on french language

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#25]
### Steps to reproduce the bug

Some text are in English or in other languages, it's mixed 

### Expected behavior

It's supposed to be in French 

### Actual behavior

In settings, song playlist (in All over the menu)

### Screenshots/Screen recordings

![IMG_20231022_004121](https://github.com/fast4x/RiMusic/assets/63956787/931cb789-8a13-4be5-86a8-2101779535e7)
![IMG_20231022_004104](https://github.com/fast4x/RiMusic/assets/63956787/76ff2c75-50d3-4a67-9e8d-fba92848dcc4)

### RiMusic version

0.6.5

### Android version

12

**Comment by fast4x** [comment]
I'm sorry for the issue, I'll correct it. Thanks for the feedback.

**Comment by NEVARLeVrai** [comment]
> I'm sorry for the issue, I'll correct it. Thanks for the feedback.

No problem, it's on all the ui, u can check

**Comment by fast4x** [comment]
Improved, available from version 0.6.6

**Comment by NEVARLeVrai** [comment]
If u need help I can help you with French language it's my native language

**Comment by fast4x** [comment]
Of course I'm happy, you can contribute in two ways:
you create a fork, edit the strings.xml file and create a pull request.
Or you download the strings.xml file, fix it and upload it as an attachment here.
[Link at strings.xml](https://github.com/fast4x/RiMusic/tree/master/app/src/main/res/values-fr)

**Comment by NEVARLeVrai** [comment]
Okay I will fork tomorrow and look in that

**Comment by NEVARLeVrai** [comment]
I assume you used Google translate, because some translations are right but not good, I will look in it and patch for you

**Comment by NEVARLeVrai** [comment]
Also do you have discord? So we can talk easier I have many suggestions for the app because , certain design or ergonomics of app are not very well done

**Comment by fast4x** [comment]
> I assume you used Google translate, because some translations are right but not good, I will look in it and patch for you 

Yes, I used Google or others similar, I preferred to enter some basic languages including French. You can change the language as you like

**Comment by fast4x** [comment]
> Also do you have discord? So we can talk easier I have many suggestions for the app because , certain design or ergonomics of app are not very well done

I don't use discord at the moment, i prefer that your suggestions are included here on Github, so that I always have them listed.

**Comment by NEVARLeVrai** [comment]
done i made it

**Comment by NEVARLeVrai** [comment]
done i made a pull
