### ISSUE TITLE
Some albums doesn't show any songs

### ISSUE THREAD

**Issue by AxmanaleX** [fast4x/RiMusic#2500]
### Steps to reproduce the bug

1 Search an album (#TWICE)
2 Click on the album
3 it doesn't show any song.
![Screenshot_2024-06-26-17-23-27-202-edit_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/124070334/5c8014f0-2ba8-4752-9e40-f7a70f3bd59a)

### Expected behavior

1 Search an album (#TWICE)
2 Click on the album
3 It should show the album songs
![Screenshot_2024-06-26-17-24-07-271_com android chrome](https://github.com/fast4x/RiMusic/assets/124070334/e782745a-403d-4764-b50a-46d058164f7c)

### Actual behavior

1 Search an album (#TWICE)
2 click on the album
3 it doesn't show any songs available

### RiMusic version

0.6.40.1

### Android version

11

**Comment by fast4x** [comment]
Fixed, available from version 0.6.41
