### ISSUE TITLE
Weird display of cover blur setting in player

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#2501]
### Steps to reproduce the bug

1. In Player settings pick Background colors -> Blurred song cover
2. Play any song, long tap on the cover to show the bar with background blur setting
3. Look down :D 

![Screenshot_20240627_131324](https://github.com/fast4x/RiMusic/assets/76595855/51dc815d-ebac-4623-8099-dbc3b0dda2a0)

### Expected behavior

The numbers at the bottom of the bar showing the degree of blurring should either be removed, as they are very small and hard to see, or made in increments of every 5 (0, 5, 10, and so on).

### Actual behavior

All 50 numbers overlap with each other

### RiMusic version

0.6.40.1

### Android version

Android 13

**Comment by aneesh1122** [comment]
I removed the values since you can already see the blur amount inside the circle.

Should I create a pull request? @fast4x

**Comment by fast4x** [comment]
Yes and link this ticket

**Comment by aneesh1122** [comment]
> Yes and link this ticket 

Done
