### ISSUE TITLE
[Feature]: Adding an outline for buttons in the player

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#2502]
### Description

In some circumstances, such as shown in the screenshot, it's hard to see the player control buttons because they blend into the background.

![Screenshot_20240627_135210](https://github.com/fast4x/RiMusic/assets/76595855/e3be26ad-140b-4823-9363-31f9082b7b5f)

### Suggested Solution

I suggest adding the ability to enable an outline for player control buttons for better visibility, as @aneesh1122 has already done for song lyrics.

**Comment by aneesh1122** [comment]
What theme are you using?

Why do you have that weird background behind the lyrics? Shouldn't it be clean?

**Comment by KOLIWAN** [comment]
> What theme are you using?
> 
> Why do you have that background behind the lyrics? Shouldn't it be clean?
> 
> Why don't you disable transparent action bar? It will solve those visibility issues

I use dynamic theme, background shouldn't be clean because when you disable Show thumbnail option, lyrics shown like at the screenshot. Actually I've copied your settings preset as you've shown here https://github.com/fast4x/RiMusic/issues/2461#issuecomment-2187112002 :)

Definitely disable transparent action bar solves the issue, but anyway transparent action bar looks much nicer

**Comment by aneesh1122** [comment]
> because when you disable Show thumbnail option, lyrics shown like at the screenshot.

It should be clean. So, dark mode or light mode?

Also send the song's link.

What player background are you using? I want to recreate your situation and see why you have that lyrics background.

**Comment by KOLIWAN** [comment]
> > because when you disable Show thumbnail option, lyrics shown like at the screenshot.
> 
> It should be clean. So, dark mode or light mode?
> 
> Also send the song's link.
> 
> What player background are you using? I want to recreate your situation and see why you have that lyrics background.

Dark mode
Background colors -> blurred song cover
https://music.youtube.com/watch?v=Msqg2BPTlMI

**Comment by aneesh1122** [comment]
Dude, you're using 'Background progress bar' for the Player. Should have told me that before.

Anyways, I added an option to enable black gradient to improve visibility. Try that out when the next update is out.

**Comment by KOLIWAN** [comment]
> Dude, you're using 'Background progress bar' for the Player. Should have told me that before.
> 
> Anyways, I added an option to enable black gradient to improve visibility. Try that out when the next update is out.

Thanks man, sorry for that, i totally forgot about background progress bar, I didn't even noticed it

**Comment by KOLIWAN** [comment]
> Dude, you're using 'Background progress bar' for the Player. Should have told me that before.
> 
> Anyways, I added an option to enable black gradient to improve visibility. Try that out when the next update is out.

Gradient at the bottom solves this issue and looks nice, thanks you man

**Comment by aneesh1122** [comment]
@fast4x close this issue as completed
