### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Uattam11** [fast4x/RiMusic#2503]
### Description

Add the option to login YouTube music, Spotify, and Jio Saavn.
Add music Quality upto 320kbps

### Suggested Solution

Add the option to login YouTube music, Spotify, and Jio Saavn.
Add music Quality upto 320kbps

### Alternatives

Blackhole is a clear alternative. Intune is another app with you login option.
320kbps quality is avaliable in blackhole and intune

### Additional Context

Add option to select music service country.

**Comment by fast4x** [comment]
Sorry isn't planned, you can use only Piped with privacy login.
