### ISSUE TITLE
[Feature]: is it possible to set the default language for lyrics?

### ISSUE THREAD

**Issue by chengliubrother** [fast4x/RiMusic#2505]
### Description

bro is it possible to set the default language for lyrics?  Like I want simplified Chinese but everytime the default is traditional Chinese, so I had to switch it every time.

### Suggested Solution

idk

**Comment by fast4x** [comment]
Yes it's planned, soon.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.42

**Comment by Loughty** [comment]
@fast4x 

Sorry, where is the option? Or is it selected automatically based on the language of the application? If so, it's not working for Spanish, but I want to be sure

**Comment by fast4x** [comment]
Go to 3 dots menu after enabled lyrics > translate > select language...

**Comment by Loughty** [comment]
> Go to 3 dots menu after enabled lyrics > translate > select language...

Mmm... I don't see it

https://github.com/fast4x/RiMusic/assets/52808915/cdb4c041-5f4e-470f-9381-6c61fcba3e82

I try with both, synchronized and unsynchronized lyrics

![WhatsApp Image 2024-07-08 at 11 33 35 AM](https://github.com/fast4x/RiMusic/assets/52808915/214c2f8a-82b0-47c4-a99a-4db282eba686)

I try deleting my cache, but it's the same, I also try with both: RiMusic and ViMusic interface
