### ISSUE TITLE
Album "Stolen Dance (Hypertechno)" by Macon does not load

### ISSUE THREAD

**Issue by twistqj** [fast4x/RiMusic#2506]
### Steps to reproduce the bug

1. Search for album "Stolen Dance (Hypertechno)"
2. Select album by Macon

### Expected behavior

The album image should load including the song(s).

### Actual behavior

The preview thumbnail is shown but otherwise it behaves as before the v.0.6.40.1 update with the API change fix.

### Screenshots/Screen recordings

![rimusic_stolen_dance_hypertechno_album_page](https://github.com/fast4x/RiMusic/assets/169496940/b5fa26a9-8bd1-4aa7-be69-629438a4d38d)
![rimusic_stolen_dance_hypertechno_album_not_loading](https://github.com/fast4x/RiMusic/assets/169496940/fd6751c6-d95e-4f9e-a685-ee1ae93bea64)

### RiMusic version

v0.6.40.1

### Android version

14

### Additional information

This might be related to the YTM-API change.

**Comment by fast4x** [comment]
Hi, fixed and available from version 0.6.41
![Screenshot_2024-06-27-12-40-48-380_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/7aeed9c2-669d-4b0f-9f8a-d2e627bfd3b3)

**Comment by fast4x** [comment]
Look... 🥳
https://github.com/fast4x/RiMusic/assets/1484476/d24380b5-f70d-4700-9f99-2ab174369f9d

**Comment by twistqj** [comment]
Do you know why it happens for certain albums and for others not?

**Comment by twistqj** [comment]
> Look... 🥳 https://github.com/fast4x/RiMusic/assets/1484476/d24380b5-f70d-4700-9f99-2ab174369f9d

I think the visualisation looks cool! Is it new?

**Comment by fast4x** [comment]
In the change introduced by YTM, there is information that is not always present and you do not know which ones are in advance. So when it happens that RiMusic expects a type of information and that album is not there, it goes wrong. Just tell me what is the album or playlist that doesn’t load and fix.

The fix is also recognized by other albums that lack the same information. In practice we instruct RiMusic not to expect that information especially if it is missing

**Comment by fast4x** [comment]
> > Look... 🥳 https://github.com/fast4x/RiMusic/assets/1484476/d24380b5-f70d-4700-9f99-2ab174369f9d
> 
> I think the visualisation looks cool! Is it new?

Is totally new implementation with 36 type of effects...

**Comment by twistqj** [comment]
> Is totally new implementation with 36 type of effects...

This sounds like much effort you (and [aneesh1122](https://github.com/aneesh1122)) have put into all these updates.

**Comment by fast4x** [comment]
Yeah, you’re right, and the results show.
