### ISSUE TITLE
Error en las reproducción online 

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#2508]
### Steps to reproduce the bug

1. Ve a un artista y reproduce (Álbum o sencillo).
2. Reproduce cualquier canción o video en línea.
3. Aparece un enunciado y no permite reproducir canciones o videos en linea.

### Expected behavior

1. Ve a un artista y reproduce (Álbum o sencillo).
2. Reproduce cualquier canción en línea.
3. Se reproduce correctamente.

### Actual behavior

Me dirijo a alguna canción o video en línea y no deja reproducir correctamente.

### Screenshots/Screen recordings

![Screenshot_20240627-062854](https://github.com/fast4x/RiMusic/assets/170132242/93df4101-0505-42d6-aec2-c0c324f7c9a1)

### Logs

N/A

### RiMusic version

0.6.40.1

### Android version

Android 14

### Additional information

Paso casi lo mismo que la actualización anterior, agradecería que se arreglará este problema. Gracias! 🙇🏽‍♂️

**Comment by fast4x** [comment]
link to album?

**Comment by Alaneeedu** [comment]
Tampoco :(

**Comment by Alaneeedu** [comment]
> enlace al álbum?

Tampoco:(

**Comment by fast4x** [comment]
it work
![Screenshot_2024-06-27-20-20-10-485_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/6f0ab8d3-1154-483b-8aaa-1dbef895b875)

wait new version

**Comment by Alaneeedu** [comment]
Gracias 🙇🏽‍♂️
