### ISSUE TITLE
Reorder play list

### ISSUE THREAD

**Issue by pst007x** [fast4x/RiMusic#251]
### Steps to reproduce the bug

Go to playlist
Select padlock
Reorder list

### Expected behavior

List should reorder and new order be remembered 

### Actual behavior

List resets and order not saved

### Screenshots/Screen recordings

![Screenshot_20231218_224501](https://github.com/fast4x/RiMusic/assets/6573564/e5637728-ceff-41e3-a3b5-e7f53bbdee9b)
![Screenshot_20231218_224447](https://github.com/fast4x/RiMusic/assets/6573564/2c23ec89-61fc-4a47-87f3-2c827a974548)
![Screenshot_20231218_224434](https://github.com/fast4x/RiMusic/assets/6573564/14af5351-854a-43df-9b30-c92b09aa0763)

### Logs

None

### RiMusic version

0.6.13

### Android version

13

### Additional information

I have reinstalled several times however same issue where reordering of playlist fails to retain order.
Android 13 Samsung S23 Ultra

**Comment by pst007x** [comment]
Image 1 original list
Image 2 changing order
Image 3 order resets after leaving page

1. Padlock unlock
2. Reorder
3. Padlock locked
4. Leave page
5. Return order has reset

**Comment by fast4x** [comment]
Fixed, available from version 0.6.20

**Comment by pst007x** [comment]
0.6.20 isn't available to download, only 0.6.19
Do you know when the fix will be released?
Cheers

**Comment by ikanakova** [comment]
> 0.6.20 isn't available to download, only 0.6.19 Do you know when the fix will be released? Cheers

Releases of new versions are usually on Friday night.

**Comment by pst007x** [comment]
Latest version hasn't fixed issue. Same problem.

**Comment by fast4x** [comment]
Reorder in playlist Is possible only when enabled sort for position and in ascendente mode.

**Comment by pst007x** [comment]
> Reorder in playlist Is possible only when enabled sort for position and in ascendent mode.

As far as I can tell it is in ascending mode, and padlock enabled. It does change position, but then returned to original (pre changed) position when leaving and returning back to playlist.

Plus some strange behaviour, as when you select to move the songs, they start to no longer align under your finger. Often jumping further up or down the list. Very odd 🤔

Thanks

**Comment by pst007x** [comment]
When reordering I've noticed that weekend you move the second song to a new position the first song resets back to its original position.

**Comment by fast4x** [comment]
Has the playlist been imported or created and then added songs from albums?

**Comment by pst007x** [comment]
> Has the playlist been imported or created and then added songs from albums?

No not imported, created within the app. I have tried deleting and creating a new one after doing a fresh installation, but same thing.

**Comment by pst007x** [comment]
1. Uninstalled
2. Cleaned phone junk files and any residual files
3. Downloaded latest app
4. Installed
5. Same issue

Thanks

**Comment by pst007x** [comment]
Are there any logs that I could post to help resolve this bug?
