### ISSUE TITLE
[Feature]: Adding support for soundcloud music 

### ISSUE THREAD

**Issue by Sahl1** [fast4x/RiMusic#2510]
### Description

like in sound cloud ihave a ton of music artist where you cant get their music from youtube. so having souncloud support will be helpful for most people

### Suggested Solution

like since rimusic have newpipe support or piped synchronization. if its possible to get music from soundcloud in rimusic like a seperate category.

### Additional Context

in newpipe you can get music from soundcloud as a seperate category. so that but combined with normal youtube music

**Comment by fast4x** [comment]
Unfortunately requires a registration and therefore in RiMusic there is no access other than piped.
