### ISSUE TITLE
Visualizer stops

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#2515]
### Steps to reproduce the bug

1. Enable visualizer
2. Select a song
3. Activate visualizer

### Expected behavior

The visualizer should play uninterrupted.

### Actual behavior

The visualizer stops after about 10 seconds, only the animation is continued.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/54811436/f3bdcba0-edc4-44a9-89be-cf25aa85a1d6

### RiMusic version

commit 33acbe6ed92ce0

### Android version

14

### Additional information

Recorded on my AVD.

**Comment by fast4x** [comment]
In next version is totally new with 36 effects
