### ISSUE TITLE
Playlists Button

### ISSUE THREAD

**Issue by srozyy** [fast4x/RiMusic#2521]
### Steps to reproduce the bug

Tap Playlists in any UI view (right, left, bottom, top).

### Expected behavior

When I press the Playlists section it shouldn't be delayed for long.

### Actual behavior

When I want to access the "Playlists" page in the menu, it shows a delay.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/172110441/4432f5c0-ad9a-4979-bf71-98b5529dbc56

### RiMusic version

0.6.42

### Android version

Android 14

### Additional information

Have a nice day!

**Comment by fast4x** [comment]
How much playlists number do you have?

**Comment by srozyy** [comment]
> How much playlists number do you have?

I don't remember the number when I took a screen recording, currently it is zero. if you watch the video carefully, it says zero to the right of the Playlists title.  I don't know if I misunderstood the question, but I didn't understand its relationship with the number of playlists.

**Comment by fast4x** [comment]
It doesn’t matter what you think, it’s very important that you give me the news I asked. This way I can understand where is problem.
