### ISSUE TITLE
Duplicate monthly playlists

### ISSUE THREAD

**Issue by Cuchurrumin19** [fast4x/RiMusic#2524]
### Steps to reproduce the bug

1. Go to the playlists section
2. Multiple monthly playlists are found even when I have disabled the option to create them

### Expected behavior

Should show only lists that you have created yourself

### Actual behavior

Show duplicate monthly lists

https://github.com/fast4x/RiMusic/assets/167647063/1ab81f34-c192-4458-a1b1-ce6b53cc3b0d

### RiMusic version

0.6.41

### Android version

Android 12

### Additional information

I love this app :3

**Comment by fast4x** [comment]
Were they created even if they were disabled?

**Comment by Cuchurrumin19** [comment]
> Were they created even if they were disabled?

Yeah.
I do not know why
![Screenshot_2024-06-29-01-25-35-07_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/167647063/d41c48df-366c-4005-8f18-a7ebc53563ee)

**Comment by fast4x** [comment]
Ok I'll check it soon

**Comment by Cuchurrumin19** [comment]
> Ok I'll check it soon

Thank you very much! :3

**Comment by curious-liberal** [comment]
Yes, I've discovered this bug too although my monthly playlists are enabled. I really enjoy the feature and it's not a particularly bad bug as it makes no difference to the end user whatsoever really but I thought I'd let you  know. Great job on the app by the way!!

**Comment by fast4x** [comment]
Try to enable and disable it again, after this delete all duplicated monthly playlist.
