### ISSUE TITLE
[Feature]: Widget for home screen

### ISSUE THREAD

**Issue by AlexIhmisviha** [fast4x/RiMusic#2526]
### Description

I noticed that the app lacks a widget to control music from the home screen.
It may be a good idea to make a simple widget that only serves to change songs and pause.

### Suggested Solution

One thing that would seem interesting to me would be to make a widget following the rules of Material You, or simply do it with your own style.

### Additional Context

Until now I think there is no app of this type that has an addon like this.
This would be primarily with user comfort in mind, obviously, but if it were created with Material You as a base it would also be a pretty nice visual upgrade to the home screen.
Although this does not mean that if it is done with its own style it can also provide a sufficiently aesthetic touch for the home screen on Android.

**Comment by Tre916** [comment]
Yep a widget with play/pause, previous, next, and favorite toggle would be fantastic.

**Comment by FarhanGz** [comment]
Yes, I request it to someone who makes widgets using kwgt, and he said Rimusic cannot be detected because there is no playback support

**Comment by fast4x** [comment]
Implemented available from version 0.6.51
