### ISSUE TITLE
When song lyrics are turned on, the visualizer disappears

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#2527]
### Steps to reproduce the bug

1. Play the song
2. Turn on visualizer 
3. Open lyrics 
4. Close lyrics
5. Visualizer disappeared, need to turn it on manually

https://github.com/fast4x/RiMusic/assets/76595855/c7e7e3c9-3509-4d41-acc0-f62a313b010a

### Expected behavior

If the visualizer was previously enabled, it should reappear after closing the song lyrics

### Actual behavior

After closing the song lyrics, the previously enabled visualizer disappears, you need to re-enable it

### RiMusic version

0.6.41

### Android version

Android 13

### Additional information

This bug is especially annoying because the buttons to switch visualizer modes are on top of thumbnail, and it's very easy to miss a button, the song lyrics will turn on, and after exiting the song lyrics the visualization disappears and has to be turned on again :(

**Comment by fast4x** [comment]
It’s not a bug, how do you read lyrics in the middle of the moving chart?

**Comment by KOLIWAN** [comment]
> It’s not a bug, how do you read lyrics in the middle of the moving chart?

No, I mean when you turn close the lyrics, if there was turned on visualizer before, it has to be shown

**Comment by fast4x** [comment]
Ah ok it's feature...

**Comment by fast4x** [comment]
Actually, if you turn on lyrics, the visualizer is disabled and vice versa, then it has to be reactivated manually.
