### ISSUE TITLE
Strange functioning of visualizer modes 34, 35 and 36

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#2528]
### Steps to reproduce the bug

1. Play song
2. Choose visualization mode 34-36 

https://github.com/fast4x/RiMusic/assets/76595855/b52ba4da-4f86-4dc6-afef-49d7da747056

### Expected behavior

Thumbnail in modes 34-36 shouldn't be as overcompressed. Also, probably in mode 36 thumbnail should not be stretched to the whole screen 

### Actual behavior

In the center of visualization modes 34 and 35 there is a small thumbnail of the song. It looks good, but it's heavily compressed, which makes it eye-catching. Mode 36 stretches the thumbnail to the whole screen, and it is still heavily compressed, so it looks unattractive. 

### RiMusic version

0.6.41

### Android version

Android 13

**Comment by aneesh1122** [comment]
Fixed
