### ISSUE TITLE
Bottom gradient does not work in landscape mode

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#2529]
### Steps to reproduce the bug

1. Turn on bottom gradient 
2. Play song
3. Enter landscape mode

https://github.com/fast4x/RiMusic/assets/76595855/7bd7a9e5-d436-4460-8c7d-57f6c3c599f1

### Expected behavior

Expected to see bottom gradient both in portrait and landscape modes if enabled

### Actual behavior

Bottom gradient doesn't work in landscape mode

### RiMusic version

0.6.41

### Android version

Android 13

### Additional information

I suppose this bug could affect Android Auto users as normally they use app in landscape mode

**Comment by aneesh1122** [comment]
In landscape mode the gradient is from the top since that's where the title and artist's name are present.

**Comment by kris20030705** [comment]
Not working in material theme too(dark mode).

> In landscape mode the gradient is from the top since that's where the title and artist's name are present.

**Comment by aneesh1122** [comment]
> Not working in material theme too(dark mode).
> 
> > In landscape mode the gradient is from the top since that's where the title and artist's name are present.
> 
> 

It's working.

**Comment by aneesh1122** [comment]
I've removed the gradient and added a constant shade of black/white according to the theme.

https://github.com/fast4x/RiMusic/pull/2537#issuecomment-2198253618

**Comment by kris20030705** [comment]
> I've removed the gradient and added a constant shade of black/white according to the theme.
> 
> [#2537 (comment)](https://github.com/fast4x/RiMusic/pull/2537#issuecomment-2198253618)

Why gradient theme is the only theme that is awesome..! Other looks uncompleted..!

**Comment by aneesh1122** [comment]
> > I've removed the gradient and added a constant shade of black/white according to the theme.
> > 
> > [#2537 (comment)](https://github.com/fast4x/RiMusic/pull/2537#issuecomment-2198253618)
> 
> Why gradient theme is the only theme that is awesome..! Other looks unfinished..!

This black shade/gradient works only if you're using blurred cover background.

It won't even get the option if you're using any other backgrounds.
