### ISSUE TITLE
Альбомы бесконечно грузятся

### ISSUE THREAD

**Issue by rogal1k410** [fast4x/RiMusic#2531]
### Steps to reproduce the bug

Открывал альбомы,но в один момент они перестали грузиться.

### Expected behavior

Показ всех песен из альбома.

### Actual behavior

Бесконечная загрузка.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/174168011/00d2d286-6a42-42cd-909d-cb5089745734

### RiMusic version

0.6.38 by fast4x

### Android version

Андроид 14

**Comment by fast4x** [comment]
Use latest version 0.6.41 it's fixed from 0.6.39
