### ISSUE TITLE
Albums come out that do not exist or do not have songs 

### ISSUE THREAD

**Issue by Emi1309-45** [fast4x/RiMusic#2532]
### Steps to reproduce the bug

I was going to listen to an album but it tells me it doesn't have songs or it doesn't exist 

### Expected behavior

![Screenshot_20240629-000350](https://github.com/fast4x/RiMusic/assets/174170270/91d752ec-48dc-4bd7-aa3b-839ff380e9a8)

### Actual behavior

This has happened to me several times I hope you fix it please 

### RiMusic version

0.6.40

### Android version

Android 11

**Comment by KOLIWAN** [comment]
Update the app, it was fixed already since version 0.6.40.1

**Comment by georgethemarmot** [comment]
I have the same issue on 0.6.40.1
It seems the issue is present when selecting albums that are less known.

**Comment by twistios** [comment]
Please tell which album does not load then fast4x can fix that album and the fix will also make different albums also work.
You then have to update to a newer version. 0.6.41 is already released on Github, FDroid will still take some time it looks like.

**Comment by ikanakova** [comment]
0.6.41 is now also on F-Droid.

**Comment by twistios** [comment]
Even though my F-Droid-App is set to refresh every day, it did not show me version 0.6.41, only 0.6.40.1. I had to refresh myself to see it.
(I am installing RiMusic via automatic update from Github)
