### ISSUE TITLE
Long press lyrics button in action bar to enter fullscreen lyrics

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#2535]
### Description

This suggestion combines two in one.

1. When you disable thumbnail for lyrics there's no way to enter fullscreen lyrics in case you want to. So this suggestion propose long pressing the lyrics button in bottom action bar to directly enter fullscreen lyrics. Then a new separate fullscreen lyrics button will not be needed.

2. Even if someone don't use disabled thumbnail lyrics. It was a bit of unpleasant experience to enable lyrics from bottom action bar and then enter fullscreen from thumbnail button. Now it'll be easier to use with one hand and more consistent experience as you can use same button for both tasks.

**Comment by aneesh1122** [comment]
May I know why you still want to use old full screen lyrics?

Me and fast4x almost deleted the old full screen lyrics. I kept it for people who are using this app the old way

**Comment by fast4x** [comment]
Old fullscreen lyrics will be replaced by new full lyrics with many other improvements in the future. Example, when full lyrics hide timeline or other features.

**Comment by aneesh1122** [comment]
> Old fullscreen lyrics will be replaced by new full lyrics with many other improvements in the future. Example, when full lyrics hide timeline or other features.

I hope you'll keep 'expanded Player' separately. That's what I always use even if I haven't activated lyrics.

I mean, look at this
![Screenshot_2024-06-29-21-29-34-608_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/45353488/2a94d43a-c2b9-4ddc-a2ba-41903700d755)

**Comment by NikunjKhangwal** [comment]
> May I know why you still want to use old full screen lyrics?
> 
> Me and fast4x almost deleted the old full screen lyrics. I kept it for people who are using this app the old way

Fullscreen lyrics are more practical for me.

1. It has darker background so text stays in focus. I prefer it when reading complicated lyrics (such as hip-hop). Also i don't want to manually turn off fluid gradient everytime from settings.
2. Larger lyrics area (i don't use expanded player because i use background for play button and thus not a fan of padding as mentioned earlier)

**Comment by NikunjKhangwal** [comment]
> Old fullscreen lyrics will be replaced by new full lyrics with many other improvements in the future. Example, when full lyrics hide timeline or other features.

That's the opposite of my ancient suggestion lol #677
Here i prefer timeline with lyrics

**Comment by fast4x** [comment]
Ok, right so full will enabled from settings for who want it.
Thanks for explaining.

**Comment by aneesh1122** [comment]
> 1. It has darker background so text stays in focus. I prefer it when reading complicated lyrics (such as hip-hop). Also i don't want to manually turn off fluid gradient everytime from settings.

you know that you can change color of lyrics as well as add different outline to it? With all these options I had zero visibility problems. try different colors and outlines.

> 2\. Larger lyrics area (i don't use expanded player because i use background for play button and thus not a fan of padding as mentioned earlier)

I've added extra space if you're using any play button other than the disabled one. You'll get it in the next update.

**Comment by NikunjKhangwal** [comment]
> you know that you can change color of lyrics as well as add different outline to it? With all these options I had zero visibility problems. try different colors and outlines.

That's probably because you use blurred background. Since you got the glass effect, the lyrics pop out on screen. They look weird when used with plain background. See for yourself:
![IMG_20240630_075446.jpg](https://github.com/fast4x/RiMusic/assets/99175083/3776f70f-fdfc-4f41-a526-213f29036a8d)


> I've added extra space if you're using any play button other than the disabled one. You'll get it in the next update.

I see. Definitely better

**Comment by NikunjKhangwal** [comment]
Besides using bold outlines and fancy colors kind of beat the purpose of using a simpler background don't you think?

**Comment by aneesh1122** [comment]
> > you know that you can change color of lyrics as well as add different outline to it? With all these options I had zero visibility problems. try different colors and outlines.
> 
> That's probably because you use blurred background. Since you got the glass effect, the lyrics pop out on screen. They look weird when used with plain background. See for yourself:
> ![IMG_20240630_075446.jpg](https://github.com/fast4x/RiMusic/assets/99175083/3776f70f-fdfc-4f41-a526-213f29036a8d)
> 
> 
> > I've added extra space if you're using any play button other than the disabled one. You'll get it in the next update.
> 
> I see. Definitely better

Don't use outlines. There's an option to disable that. It was added for blurred backgrounds. With a plain background you don't really need any outline.

Or you can use the accent color with the simple outline.

Glow outline works best with white lyrics which you'll get if you use the dark theme. I'm planning to remove 'theme' color and add both white and black color so that you can have white lyrics even if you're using light theme

**Comment by aneesh1122** [comment]
> Besides using bold outlines and fancy colors kind of beat the purpose of using a simpler background don't you think?

White text + glow outline looks great even with simple backgrounds.

Just switch to the dark theme for some time and see how white + glow looks like.

**Comment by NikunjKhangwal** [comment]
The screenshots include examples without using outlines too, they still look out of place. Also I've tried everything already, i always try all the new stuff in every update. It's simple, i just don't prefer outlines and different colors/highlights. I love the way it is now, simple thin black/white lyrics.

But anyway now that you've mentioned you increased space for button then i guess i can say goodbye to fullscreen lyrics.

**Comment by NikunjKhangwal** [comment]
And if that's the case then i would like to change the suggestion request too. It would be nice to have a setting to change behaviour of lyrics button in action bar so it not just toggle lyrics but expand the screen automatically when lyrics are enabled and revert it to original when lyrics are disabled.

**Comment by aneesh1122** [comment]
> The screenshots include examples without using outlines too, they still look out of place. Also I've tried everything already, i always try all the new stuff in every update. It's simple, i just don't prefer outlines and different colors/highlights. I love the way it is now, simple thin black/white lyrics.
> 
> But anyway now that you've mentioned you increased space for button then i guess i can say goodbye to fullscreen lyrics.

Switch to the dark theme for a moment and try the white lyrics. Use glow or don't use any outline at all. 

Even now you can get black lyrics. Don't use any outline at all. That's as simple as it gets.

You can adjust the text size too. I haven't touched the previous sizes.

Btw you'll get the extra space only if you're not using the 'Disabled' button.

**Comment by NikunjKhangwal** [comment]
> Switch to the dark theme for a moment and try the white lyrics. Use glow or don't use any outline at all.

I already did bro and yes it's better but as mentioned earlier i don't prefer any highlights including glow. It's good but not better than plain style for me.

> Even now you can get black lyrics. Don't use any outline at all. That's as simple as it gets.

Yeah that's what I'm using.

> You can adjust the text size too. I haven't touched the previous sizes.

Medium is good for me.

> Btw you'll get the extra space only if you're not using the 'Disabled' button.

That's what needed. I use default button.

Anyway as mentioned I'm ok with fullsceen departure now so we should end this debate.

**Comment by aneesh1122** [comment]
> And if that's the case then i would like to change the suggestion request too. It would be nice to have a setting to change behaviour of lyrics button in action bar so it not just toggle lyrics but expand the screen automatically when lyrics are enabled and revert it to original when lyrics are disabled

You know, I wanted to have the lyrics only in the expanded player but then I have to adapt this app for everyone. So, CHOICES.

**Comment by NikunjKhangwal** [comment]
> You know, I wanted to have the lyrics only in the expanded player

So basically what I'm saying?

**Comment by aneesh1122** [comment]
> > You know, I wanted to have the lyrics only in the expanded player
> 
> So basically what I'm saying?

Yeah but people don't like changes. That's why I added the expanded player as an option.

I like how it looks with the cover image background so I made it a mode instead of keeping it exclusive to lyrics.

**Comment by aneesh1122** [comment]
> > you know that you can change color of lyrics as well as add different outline to it? With all these options I had zero visibility problems. try different colors and outlines.
> 
> That's probably because you use blurred background. Since you got the glass effect, the lyrics pop out on screen. They look weird when used with plain background. See for yourself:
> ![IMG_20240630_075446.jpg](https://github.com/fast4x/RiMusic/assets/99175083/3776f70f-fdfc-4f41-a526-213f29036a8d)
> 
> 
> > I've added extra space if you're using any play button other than the disabled one. You'll get it in the next update.
> 
> I see. Definitely better

Btw how did you get black lyrics + black outline?

For the light theme you should get white outline.

**Comment by NikunjKhangwal** [comment]
> For the light theme you should get white outline.

I'm not sure. It's just normal theme based outline

**Comment by aneesh1122** [comment]
> > For the light theme you should get white outline.
> 
> I'm not sure. It's just normal theme based outline

Okay, tell me this

Theme?
Theme Mode?
Lyrics Color?
Lyrics Outline?

**Comment by aneesh1122** [comment]
> > For the light theme you should get white outline.
> 
> I'm not sure. It's just normal theme based outline

btw would you look at this 

https://github.com/fast4x/RiMusic/assets/45353488/299c548d-eab7-4e4a-9e95-e87823553baa

**Comment by NikunjKhangwal** [comment]
> Theme? Theme Mode? Lyrics Color? Lyrics Outline?

Dynamic, System, Theme, Theme

**Comment by NikunjKhangwal** [comment]
> btw would you look at this

Exactly what I was talking about, Nice job. Also good thing the animation was already added in latest version so it works smoothly.

**Comment by aneesh1122** [comment]
> > btw would you look at this
> 
> Exactly what I was talking about, Nice job. Also good thing the animation was already added in latest version so it works smoothly.

this is the debug app. The release apk works much more smoothly. Tell me a song and I'll show you how it looks like with fluid cover background.

**Comment by NikunjKhangwal** [comment]
Cool

**Comment by aneesh1122** [comment]
> Cool

Unfortunately I found some problems so had to close the pull request. I'll work on it later and do a new pull request later.

**Comment by NikunjKhangwal** [comment]
Ofc. Take your time

**Comment by aneesh1122** [comment]
alright, Now I can't find any Issues so it's fine. If I find any bugs I'll fix it.

Enjoy ✌️

**Comment by NikunjKhangwal** [comment]
Thanks man

**Comment by aneesh1122** [comment]
> Thanks man

You're welcome
