### ISSUE TITLE
Rimusic

### ISSUE THREAD

**Issue by Phr01** [fast4x/RiMusic#2541]
### Description

__

### Suggested Solution

Como eu posso fazer a sincronização com Piped no aplicativo Rimusic?

**Comment by fast4x** [comment]
Simple,go to https://piped.video and create an account 
Go in RiMusic miscellaneous settings, Piped section and add your account info.

That's all.

**Comment by fast4x** [comment]
Oh hell I look

**Comment by fast4x** [comment]
Maybe you have previous versions, not latest 0.6.41

**Comment by fast4x** [comment]
try to disable... and enable again
