### ISSUE TITLE
RiMusic

### ISSUE THREAD

**Issue by athala12** [fast4x/RiMusic#2544]
### Steps to reproduce the bug

The Album of any artist didn't show up the songs

### Expected behavior

This should happen show up the songs of album, but any artist didn't show up the song

### Actual behavior

This happened when i click the albums, but the songs didn't showed up

### Screenshots/Screen recordings

![Screenshot_2024-06-30-09-34-04-31_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/174224072/8c244c2e-97b8-4730-82be-47eb735b11db)

### RiMusic version

0.6.39

### Android version

Android 11

**Comment by cMattw** [comment]
use the latest version

**Comment by KOLIWAN** [comment]
Is was fixed since the version 0.6.40.1

**Comment by athala12** [comment]
> Is was fixed since the version 0.6.40.1

when i'm used the latest version of this, why sometimes force close? any recommendation to fix it?

**Comment by fast4x** [comment]
use latest 0.6.41
