### ISSUE TITLE
Volume controller

### ISSUE THREAD

**Issue by yos4mr** [fast4x/RiMusic#2556]
### Description

It would be great if within the application you could control the volume of the music only, keeping the device and other apps' volume as it was.

### Suggested Solution

A volume controller for songs, without affecting or changing the volume for all apps in general.

**Comment by ALMIGHTY-VC** [comment]
May u try long pressing your play button while playing the song on your song player(note not minimized one)

**Comment by yos4mr** [comment]
Thanks, I didn't know it had that function integrated 😸

**Comment by ALMIGHTY-VC** [comment]
> Thanks, I didn't know it had that function integrated 😸

Welcome i think now's the time to update the feature list

**Comment by ALMIGHTY-VC** [comment]
Or idk if possible with every new version release fast4x mentions the changes he implemented a bot which would take the new implemented features summarize the thread's concept and update it on wiki or accessible page would be convenient

**Comment by twistios** [comment]
> > Thanks, I didn't know it had that function integrated 😸
> 
> Welcome i think now's the time to update the feature list

My pull-request about that got merged today so at least one can see it now in the Feature list.
Some other Thing: Maybe something like a User manual is required, it could be in the Wiki.

**Comment by ALMIGHTY-VC** [comment]
> > > Thanks, I didn't know it had that function integrated 😸
> > 
> > 
> > Welcome i think now's the time to update the feature list
> 
> My pull-request about that got merged today so at least one can see it now in the Feature list. Some other Thing: Maybe something like a User manual is required, it could be in the Wiki.

Nice bro thats a well needed thing for all of us and yeah i checked the wiki it wasnt there

**Comment by twistios** [comment]
I also created a new wiki-page about how to use it.
