### ISSUE TITLE
Improvement on Modern Control button

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#2558]
### Description

Been long time since I used Modern Control style
This are reason why I didnt use Essential Control style
・Favorite button isn't on the same height as song title
・Dedicated Loop button
Kinda disappointed since shadow are added in the player (i forgot when)
but I dont care at that moment as long as the function remain the same

### Suggested Solution

- [ ] **Disable Modern Control button shadow when "Thumbnail Type" set to "Essential"**
Enable/Disable Control button's shadow based on Thumbnail Type
- [ ] **Rework/Disable "Play Button" options when "Control style" set to "Modern"**
"Modern" style doesnt work as expected, unlike when its set to "Essential"
"Modern" + "Disabled" looks bit wierd
"Essential" + "Wavy Circle" result in wierd Play Button's background color combination

### Additional Context

"Modern" + "Disabled"
![Screenshot](https://github.com/fast4x/RiMusic/assets/45221211/c74987fc-b9f4-4b57-9c1f-1a5767a0ddfd)

**Comment by aneesh1122** [comment]
why does your shadow looks so bad? It's looking good in my case.

**Comment by faustaahmad** [comment]
I dont know why it looks like that

**Comment by aneesh1122** [comment]
> I dont know why it looks like that Also this was "Essential" + "Wavy Circle" ![Screenshot](https://private-user-images.githubusercontent.com/45221211/344479353-1301b394-9d2c-4d8e-9bda-5efed53d9942.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NjUyOTYsIm5iZiI6MTcxOTc2NDk5NiwicGF0aCI6Ii80NTIyMTIxMS8zNDQ0NzkzNTMtMTMwMWIzOTQtOWQyYy00ZDhlLTliZGEtNWVmZWQ1M2Q5OTQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE2Mjk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYmNlYWFjY2M5NGRlNzY3ODllMzJlODY4MzUxOTY1ODZmNDViNmUxMjRlZTRhYTk2ZGQ2MmUzOTkzZWRjMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NV0HTpNxzLPd_8Fq3DSOnNm_-p6NsrFXPAiEuP4I76s)

I think this is how it's designed.

**Comment by faustaahmad** [comment]
@aneesh1122 I dont think so, "Essential" + "Wavy Circle" is supposed to be paired with "Match theme" background in the past
But since they added more background options, that happens
![Screenshot](https://github.com/fast4x/RiMusic/assets/45221211/e76da103-7447-49e5-a3f4-464432c7ce77)

**Comment by faustaahmad** [comment]
Also additional context for the shadow, added in the past (v0.6.35)
Someone did create an Issue in #1910 about it
<table><tr align="center">
<td><b>
0.6.34
</b><image src=
"https://github.com/fast4x/RiMusic/assets/45221211/137c27b1-d073-4738-bf52-64c5b0c99290"></image></td>
<td><b>
0.6.35+
</b><image src=
"https://github.com/fast4x/RiMusic/assets/45221211/f30d8c6c-b93e-4373-afd8-4091715f6826"></image></td>
</tr></table>

0.6.35 Dynamic theme are broken iirc

**Comment by aneesh1122** [comment]
I think I can fix the essential controls but can't do anything about the modern one.

The shadow ratio must be in 1:1 ratio hence the square box was added.

**Comment by aneesh1122** [comment]
I fixed wavy circle for both type of controls but the shadow will look bad in your mobile. From what I heard shadows will work only with android 11 and above.

Hey, you can use essential controls if you don't want those ugly shadows.
