### ISSUE TITLE
Cant click on three dots inside Lyrics (Landscape)

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#2559]
### Steps to reproduce the bug

・Landscape
・Disable thumbnail
・Enable lyrics

![Screenshot](https://github.com/fast4x/RiMusic/assets/45221211/91d6a353-a889-4267-849a-2a45c6d7533d)

### Expected behavior

Three dots should be clickable

### Actual behavior

Cant click three dots since it get overlayed by android's navigation bar

### RiMusic version

0.6.41

### Android version

Android 11

**Comment by aneesh1122** [comment]
@fast4x is there anyway I can tell the app that the user is using a navigation bar so that I can add padding specifically for those users?

**Comment by fast4x** [comment]
I don't understand, what you mean?

**Comment by aneesh1122** [comment]
> I don't understand, what you mean?

Don't worry. I've fixed it.
