### ISSUE TITLE
RiMusic Crash

### ISSUE THREAD

**Issue by Chavarro1** [fast4x/RiMusic#2560]
### Steps to reproduce the bug

Este bug ocurre mientras escucha música dentro o fuera de la aplicación, si llevas un rato dentro de ésta, se cierra por sí sola

### Expected behavior

Debería funcionar sin ningún cierre forzado de la aplicación mientras se escucha música 

### Actual behavior

RiMusic se cierra solo mientras escucho música 

### Logs

2024-06-30T13:21:17.941:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 y5.a.v(SourceFile:38) 
	 d7.a.i(SourceFile:9) 
	 v7.J.run(SourceFile:95) 
	 A7.i.run(SourceFile:239) 
	 C7.k.run(SourceFile:3) 
	 C7.a.run(SourceFile:96) 

### RiMusic version

0.6.41

### Android version

Android 12 (Nusantara Custom ROM)

**Comment by fast4x** [comment]
Do you have check for update enabled? Try to disable...

**Comment by fast4x** [comment]
Maybe it's fixed, available from version 0.6.42

**Comment by Chavarro1** [comment]
Thanks!, I disabled the automatic update check and it works 👍

**Comment by fast4x** [comment]
Oookkk maybe I have understand tha problem.
