### ISSUE TITLE
Lupa de búsqueda en AndroidAuto 

### ISSUE THREAD

**Issue by Maxays** [fast4x/RiMusic#2563]
### Description

En android auto no aparece la lupa para hacer búsqueda de canciones, artistas o albums

### Suggested Solution

Implementar en siguiente versión la lupa para android auto.

### Alternatives

Implementar búsqueda por voz para android auto 

### Additional Context

Al tener que realizar la búsqueda por el móvil entorpece la jugabilidad de la app en android auto

**Comment by fast4x** [comment]
Implemented
