### ISSUE TITLE
Frequent Crashes when lyrics are used and you skip around in the song

### ISSUE THREAD

**Issue by HydeZero** [fast4x/RiMusic#2566]
### Steps to reproduce the bug

1. Run the app
2. Play a song
3. Open lyrics
4. Tap lyrics to move around
5. Crash

### Expected behavior

The app shouldn't crash

### Actual behavior

The app crashes. Sometimes if you just let lyrics sit, it will crash after a bit.

### Logs

2024-06-29T11:19:55.171:	java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	 q0.k.a(SourceFile:125) 
	 n0.f.onPreDraw(SourceFile:34) 
	 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1204) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4723) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1153) 
	 android.view.Choreographer.doFrame(Choreographer.java:1079) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-29T11:19:55.674:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{c3dc047 u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-29T14:14:37.635:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7fe33ac u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-29T14:17:54.703:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{57f1db9 u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-29T14:24:48.381:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 x5.a.t(SourceFile:38) 
	 W6.a.k(SourceFile:9) 
	 o7.J.run(SourceFile:95) 
	 C1.a.run(SourceFile:15) 
	 v7.j.run(SourceFile:3) 
	 v7.a.run(SourceFile:96) 

2024-06-29T15:40:41.914:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{54a7338 u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-29T15:45:10.371:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{817e549 u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-29T15:47:50.127:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 x5.a.t(SourceFile:38) 
	 W6.a.k(SourceFile:9) 
	 o7.J.run(SourceFile:95) 
	 C1.a.run(SourceFile:15) 
	 v7.j.run(SourceFile:3) 
	 v7.a.run(SourceFile:96) 

2024-06-29T15:57:43.939:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e6ec9e4 u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-29T15:59:55.529:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b82b4c0 u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-29T18:21:35.242:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 x5.a.t(SourceFile:38) 
	 W6.a.k(SourceFile:9) 
	 o7.J.run(SourceFile:95) 
	 C1.a.run(SourceFile:15) 
	 v7.j.run(SourceFile:3) 
	 v7.a.run(SourceFile:96) 

2024-06-30T00:10:16.001:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{c0b89b8 u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-30T09:28:02.583:	java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	 q0.k.a(SourceFile:125) 
	 n0.f.onPreDraw(SourceFile:34) 
	 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1204) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4723) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1153) 
	 android.view.Choreographer.doFrame(Choreographer.java:1079) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-30T09:40:17.579:	java.lang.RuntimeException: Could not copy bitmap to parcel blob.
	 android.graphics.Bitmap.nativeWriteToParcel(Native Method) 
	 android.graphics.Bitmap.writeToParcel(Bitmap.java:2301) 
	 android.os.Parcel.writeParcelable(Parcel.java:2596) 
	 android.os.Parcel.writeValue(Parcel.java:2497) 
	 android.os.Parcel.writeValue(Parcel.java:2374) 
	 android.os.Parcel.writeArrayMapInternal(Parcel.java:1310) 
	 android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843) 
	 android.os.Bundle.writeToParcel(Bundle.java:1389) 
	 android.os.Parcel.writeBundle(Parcel.java:1379) 
	 android.support.v4.media.MediaMetadataCompat.writeToParcel(Unknown Source:2) 
	 android.support.v4.media.session.r.M(SourceFile:16) 
	 it.fast4x.rimusic.service.PlayerService.p(SourceFile:112) 
	 q2.t.c(SourceFile:15) 
	 j2.g.handleMessage(SourceFile:237) 
	 android.os.Handler.dispatchMessage(Handler.java:102) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-30T09:40:18.207:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b38d9ce u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-30T13:28:27.894:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 y5.a.v(SourceFile:38) 
	 d7.a.i(SourceFile:9) 
	 v7.J.run(SourceFile:95) 
	 A7.i.run(SourceFile:239) 
	 C7.k.run(SourceFile:3) 
	 C7.a.run(SourceFile:96) 

2024-06-30T13:42:21.276:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{898230a u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-30T15:50:57.528:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{6912d0b u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-30T18:31:10.143:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 y5.a.v(SourceFile:38) 
	 d7.a.i(SourceFile:9) 
	 v7.J.run(SourceFile:95) 
	 A7.i.run(SourceFile:239) 
	 C7.k.run(SourceFile:3) 
	 C7.a.run(SourceFile:96) 

2024-06-30T18:31:11.644:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{fbe241a u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-06-30T18:33:40.395:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 y5.a.v(SourceFile:38) 
	 d7.a.i(SourceFile:9) 
	 v7.J.run(SourceFile:95) 
	 A7.i.run(SourceFile:239) 
	 C7.k.run(SourceFile:3) 
	 C7.a.run(SourceFile:96) 

### RiMusic version

0.6.41

### Android version

Android 14

### Additional information

Some lyrics are edited on the app (fix syncing/lyric issues)

The most important crash details are the ones marked 6-30-2024.

Pardon the long logs.

**Comment by fast4x** [comment]
next version will have improved debug info..

**Comment by fast4x** [comment]
Maybe it's fixed, available from version 0.6.42

**Comment by HydeZero** [comment]
Thanks, will update when 0.6.42 releases.
