### ISSUE TITLE
se me agregan muchas playlist del mes de mayo y las quiero borrar por que ya son demasiadas, no entiendo por que solo de mayo y mayo y mayo si mayo ya paso

### ISSUE THREAD

**Issue by chequegod** [fast4x/RiMusic#2568]
### Steps to reproduce the bug

Muchas playlist de mayo que no quiero

### Expected behavior

solo se deberia de agregar una playlist de mayo

### Actual behavior

en vez de eso, ya tengo como 40 playlist de mayo que yo ni si quiera hice

### Screenshots/Screen recordings

![Screenshot_20240630_210916](https://github.com/fast4x/RiMusic/assets/174291669/66171ef6-e938-4700-b060-5827c0398578)

### RiMusic version

0.6.33

### Android version

android 13

### Additional information

enserio me molesta que tengo como 70 playlist del mes de mayo y lo peor es que todas tienen lo mismo y se agregan solas

**Comment by Glich440** [comment]
Have you tried updating to the latest version?
Translation: ¿Has probado con la última versión?

**Comment by Loughty** [comment]
Si vas a Ajustes > Selecciones rápidas, y bajas a la opción que dice "Mostrar Listas de reproducción mensuales", podrás desactivar esa función completamente. Te puede servir en lo que resuelven ese error (en caso de que no este resuelto ya con la última actualización).
