### ISSUE TITLE
Improvement for Show next song queue

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#2569]
### Description

- [ ] **Add arrow `›` as separator after each song's column**
Nice little Indicator and cosmetic purpose
![NextUpArrow](https://github.com/fast4x/RiMusic/assets/45221211/1829ded9-4695-4948-934b-f6b67b945aef)
- [ ] **Respect font type**
Currently bugged, also it shrink after change font type (then goes normal after switch song)
- [ ] **Song Title has more bold level** or use same typeset as Queue
![NextUpArrowAfter](https://github.com/fast4x/RiMusic/assets/45221211/ab061481-367b-4e3c-83a5-b33374f2dbd5)
- [ ] **Clickable, skip to that song directly**
- [ ] **More column**
![NextUpArrowColumn](https://github.com/fast4x/RiMusic/assets/45221211/17e0204b-0c57-4bb8-aeb9-773da1df6f91)

> **About the arrow**
> ・Align all the aroow first according to screen width, centered depends on orientation
> ・Distance between arrow & Cover icon
> My image use same px as distance between leftmost Cover icon & x=0 (leftmost coordinate)
> It turns out to be around 22px in 720p resolution

**More Idea if needed**
- [ ] **Gestures**
・Right swipe, Show Next songs, arrow pointed to the right
・Left swipe, Show Prev songs, arrow pointed to the left
- [ ] ~~**Scrollable**~~

### Suggested Solution

This are purely an Idea, just hoping that it could get implemented in the future
Thanks for the hard work

**Comment by fast4x** [comment]
more column isn't possible because depends by display size..
