### ISSUE TITLE
Swipe feature in current playlist(queue list)

### ISSUE THREAD

**Issue by Its-Tony** [fast4x/RiMusic#2570]
### Description

It would be great if we can have swipe feature in current playlist(queue list).

### Suggested Solution

If we swipe to left it should remove song from current playlist(queue list)and for swipe to right add to favorite.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.42

**Comment by Its-Tony** [comment]
Thank you @fast4x, you are really fast.

**Comment by fast4x** [comment]
My name is Fast... Fast4x... ahahaha LOL
