### ISSUE TITLE
The sound controller resets everytime. 

### ISSUE THREAD

**Issue by Dark0Echo** [fast4x/RiMusic#2577]
### Steps to reproduce the bug

Keep pressing down the play button on the player (standard one, not the minimized one). And then a sound controller comes up. Change anything, it doesn't stay same on the next song. 

### Expected behavior

The sound controller should keep it's setting same throughout the whole song queue. 

### Actual behavior

It doesn't, although it shows that it is like how you setup in your previous song, but it isn't actually working that way. Everytime I change a song it resets. 

### RiMusic version

"0.6.41" 

### Android version

"Android 11" 

### Additional information

I don't know if it works normally (without headphones). But it doesn't work with my headphone and I don't think it's a headphone issue.

**Comment by twistios** [comment]
I can confirm this bug. Tested without Headphones.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.42

**Comment by fast4x** [comment]
Fixed, available from version 0.6.43
