### ISSUE TITLE
YT Music playlist import 

### ISSUE THREAD

**Issue by TheHurricaneRider** [fast4x/RiMusic#2578]
### Description

Hey guys, I've just started using RiMusic and I'm importing my yt music playlists. I love the app so far but one thing I find to be a nuisance is that I can't click on an artist when listening to a song.

If I go to the artist page I can play the song and it shows as liked in my playlist that I can click the artist to go to the artist page. Any way to fix this?
![Screenshot_20240702-005329](https://github.com/fast4x/RiMusic/assets/174354801/2a471a2e-fd19-4d12-8c08-12f3817b6932)
![Screenshot_20240702-005351](https://github.com/fast4x/RiMusic/assets/174354801/a927db5f-daad-4553-b2ad-dee3ebf5e9c3)
![Screenshot_20240702-005354](https://github.com/fast4x/RiMusic/assets/174354801/c1b00d87-267a-41bf-a9a6-20197349a0bd)

### Suggested Solution

If the songs I imported.can allow me to click artist so I can easily follow them

**Comment by fast4x** [comment]
Click depend from artist/album code, if available it can be clicked...
