### ISSUE TITLE
[Feature]: Thin Bar Timeline

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#2582]
### Description

When we hold and drag the default timeline it temporarily transforms into a different style which is similar to Fat Bar but thinner. Can we get this thin bar as a separate timeline style as well?

![IMG_20240701_213008](https://github.com/fast4x/RiMusic/assets/99175083/f52690ce-f508-42c6-9dc4-b2003c921eed)
![IMG_20240701_213024](https://github.com/fast4x/RiMusic/assets/99175083/a26b395e-7568-4624-8bd3-7e754da1dc07)

### Suggested Solution

Looks much cleaner than Fat Bar for me

**Comment by fast4x** [comment]
Implemented, available from version 0.6.42

**Comment by NikunjKhangwal** [comment]
Thanks

**Comment by aneesh1122** [comment]
> Thanks

Good. You're finally learning. Keep it up 😂😂
