### ISSUE TITLE
Thumbnail in notifications are low quality

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#2583]
### Steps to reproduce the bug

.

### Expected behavior

Thumbnails in notifications should be the same as they're in player screen.

### Actual behavior

They're low quality for some reason even though player screen is fine.
![IMG_20240701_221705](https://github.com/fast4x/RiMusic/assets/99175083/4e2e4942-7bda-4c6b-89a3-520f3623ffb6)
![IMG_20240701_221638](https://github.com/fast4x/RiMusic/assets/99175083/ee6f4c82-0cbe-4dd8-a32b-9ef9cd2854b5)

I cross-checked with other music players but it's not the case with them
![IMG_20240701_221616](https://github.com/fast4x/RiMusic/assets/99175083/485dc0f5-9cfc-48e9-93ac-4873b67b2775)

### RiMusic version

0.6.41

### Android version

Android 12

**Comment by fast4x** [comment]
It can't be improved, sorry

**Comment by NikunjKhangwal** [comment]
Ok, no problem
