### ISSUE TITLE
Dark theme uses wrong accent color

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2592]
### Description

![GridArt_20240702_134802161](https://github.com/fast4x/RiMusic/assets/45353488/8de9d0cb-ed7e-4abd-aa33-9faab67ffa97)

Left is Light theme. It uses correct accent color from the thumbnail.

Right is Dark theme. It's completely wrong.

### Suggested Solution

Use same accent color for both dark and light theme

**Comment by aneesh1122** [comment]
@fast4x pls don't ignore my ideas just because I had an argument with someone.

How I behave with someone else should affect things between us.

**Comment by fast4x** [comment]
I don’t ignore anyone, things have priorities.

**Comment by Vishcot** [comment]
@fast4x i agree..accent color is picking up the wrong colours most of the time in dynamic theming.. please fix this if possible 🙏🏻
