### ISSUE TITLE
Spotify playlist share

### ISSUE THREAD

**Issue by pathania07** [fast4x/RiMusic#2593]
### Description

I know that there are no plans for adding Spotify login for now(It should be implemented like spotube whenever it comes i.e. automatic artists and playlists sync)
However there should be an option to find your Spotify playlist on rimusic by using links etc.

### Suggested Solution

Copy the link of your Spotify playlist and paste it into rimusic and it opens your playlist.

**Comment by fast4x** [comment]
I'll check if possible, thanks for the request.

**Comment by aneesh1122** [comment]
I'm posting it anyways. Might be useful. There are 2 ways to do it.

**This is the long method**

We can import .CSV files to RiMusic to import playlists. So

1) use exportify. Login your Spotify ID there and export your playlist.
2) RiMusic can also support platforms other than youtube by accepting .CSV files with columns "Title" "Artists" "Album"
3) copy "Title" "Artists" "Album" from .CSV exported from exportify and paste it to a new .CSV.
4) upload that CSV to RiMusic
5) Now RiMusic can take Title+Artist or Title+Album, search the song and put the top result in the playlist.

**Now the short method**

1) Transfer songs from Spotify to YouTube
2) share that new YouTube Playlists' link to RiMusic
3) do this

https://github.com/fast4x/RiMusic/assets/45353488/7dd0bcca-88a3-4d43-b589-5e2a594caade

4) you don't have to repeat this process if you want to update the playlist. Just do this

https://github.com/fast4x/RiMusic/assets/45353488/30a46c45-aae1-49f1-af51-d0ab91b9e686

**Comment by aneesh1122** [comment]
Now, how can you transfer playlists from Spotify to YouTube?

1) Tunemymusic : supports transfer of 500 songs at once for free. If you have >500 songs, just copy 1-500 songs in a playlist, 500-1000 to an another playlist and so on.
Now transfer every playlists with 500 songs to YouTube. You can transfer to the same YouTube playlist every time.

2) use [https://github.com/sigma67/spotify_to_ytmusic](spotify_to_ytmusic)

There are no limits. Process can be automated so you don't have to select multiple options everytime. It's very easy to do in PC. Needs a bit of work in android.

I use termux and I transfer 4 playlists almost daily from Spotify to YouTube.

This is all I do and the playlists are transferred in approx 5 mins

https://github.com/fast4x/RiMusic/assets/45353488/55e0c439-5736-49ab-948a-57ee13d5e4a3

**Comment by fast4x** [comment]
Simple method is to use https://soundiiz.com

Free account permit to transfer much playlists.

**Comment by pathania07** [comment]
@aneesh1122 Just to make sure I'm doing it alright can you tell from where can I import the CSV file in rimusic currently I'm doing this and the app crashes as soon as I click on the file
![Uploading Screenshot_2024-07-02-17-34-54-64_91b67804b5fb3353a77fb824d6bb0b50.jpg…]()

**Comment by aneesh1122** [comment]
> Simple method is to use https://soundiiz.com
> 
> Free account permit to transfer much playlists.
> 
> 

Tunemymusic has the highest free transfer limit as far as I know. It permits 500 songs at a time.

Soundiiz limits to 200 songs at a time I think.

**Comment by aneesh1122** [comment]
> @aneesh1122 Just to make sure I'm doing it alright can you tell from where can I import the CSV file in rimusic currently I'm doing this and the app crashes as soon as I click on the file
> ![Uploading Screenshot_2024-07-02-17-34-54-64_91b67804b5fb3353a77fb824d6bb0b50.jpg…]()
> 

Right now you can import only those playlists which you have exported from RiMusic or maybe ViMusic

**Comment by fast4x** [comment]
@aneesh1122 @pathania07 Import is only fro playlist that have been exported from RiMusic. From ViMusic only backup are importable...

**Comment by pathania07** [comment]
@fast4x I guess we have got a new feature request

**Comment by aneesh1122** [comment]
> @fast4x I guess we have got a new feature request 

And that is?

**Comment by pathania07** [comment]
> And that is?

Import of playlist from .csv files of Spotify although I guess adding Spotify api would be more easier.(I don't know much about coding just some little html and js).

**Comment by aneesh1122** [comment]
> 
> > And that is?
> 
> Import of playlist from .csv files of Spotify although I guess adding Spotify api would be more easier.(I don't know much about coding just some little html and js).

Anything that requires login will not be implemented (except piped which is privacy friendly)

**Comment by pathania07** [comment]
> > > And that is?
> > 
> > 
> > Import of playlist from .csv files of Spotify although I guess adding Spotify api would be more easier.(I don't know much about coding just some little html and js).
> 
> Anything that requires login will not be implemented (except piped which is privacy friendly)

What about importing CSV files

**Comment by pathania07** [comment]
> > > And that is?
> > 
> > 
> > Import of playlist from .csv files of Spotify although I guess adding Spotify api would be more easier.(I don't know much about coding just some little html and js).
> 
> Anything that requires login will not be implemented (except piped which is privacy friendly)

How about giving users a choice if they want to login or not. At the end I respect your decision though
