### ISSUE TITLE
Phone's status bar not showing properly 

### ISSUE THREAD

**Issue by OTT-KHE** [fast4x/RiMusic#2595]
### Steps to reproduce the bug

Expand lyrics panel 

### Expected behavior

Showing status bar in White

### Actual behavior

Showing status bar in black

### Screenshots/Screen recordings

![Screenshot_2024-07-02-15-38-15-995_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/128558330/8c4803e3-909c-40af-a05d-09f7cd02405c)

### RiMusic version

Latest 0.6.41

### Android version

Android 12

**Comment by OTT-KHE** [comment]
It works properly in dark mode 
![Screenshot_2024-07-02-15-44-54-006_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/128558330/b4106f22-119e-4eef-93f6-59232ba36326)

**Comment by aneesh1122** [comment]
Why don't you try the new lyrics UI?
