### ISSUE TITLE
Songs don't load at some point

### ISSUE THREAD

**Issue by assier08** [fast4x/RiMusic#2596]
### Steps to reproduce the bug

Go to an artist 
Swipe down
Songs stop loading

### Expected behavior

All the artist songs should load 

### Actual behavior

After a certain song, the rest of the songs do not appear (With artists that have 100 songs or more, for example, this don't happen with Måneskin)

### Screenshots/Screen recordings

![Screenshot_2024-07-02-17-23-19-239_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/172515042/80cf5017-9e0d-491e-957f-9b3974a981dc)

### RiMusic version

0..6.41

### Android version

Android 14

### Additional information

The same problem happens with bands like Panic! At the disco, Simple Plan, Smash Mouth...

**Comment by twistios** [comment]
I also tested with "Fall Out Boy" and can observe the same problem.
The same happens for example for "Panic! At The Disco", but not for "Maneskin".
It seems like it is a problem with the number of songs.

**Comment by aneesh1122** [comment]
> This problem may have happened due to the YouTube Music API change, which occurred a few weeks ago.

Nope. This problem existed from a long time
#1604

**Comment by twistios** [comment]
It seems to me that it is because of a Limit of 100 songs (or some other value depending on settings or other factors).
As Maneskin has less songs, it does not happen for them.

**Comment by assier08** [comment]
> It seems to me that it is because of a Limit of 100 songs (or some other value depending on settings or other factors). As Maneskin has less songs, it does not happen for them.

It could be, but it doesn't make sense,  why would you put a limit of songs?

**Comment by twistios** [comment]
I just counted for "Smash Mouth" and it is also 100.

**Comment by assier08** [comment]
> I just counted for "Smash Mouth" and it is also 100.

You're right, I just counted for "Simple Plan" and after the 99th or 100th song the rest don't appear

**Comment by aneesh1122** [comment]
@fast4x this bug is still there

**Comment by twistios** [comment]
I have investigated this issue a bit and it seems that Innertune gives the first 100 songs (if it is even this much) and then continuation does not work at all so this is why it is 100 songs.
