### ISSUE TITLE
Songs do not download.

### ISSUE THREAD

**Issue by Dani3l9765** [fast4x/RiMusic#2598]
### Steps to reproduce the bug

1. Go to the album "Rage Against the Machine" by the band of the same name.
2. Add songs like "Bombtrack" or "Killing in the Name" to a playlist.
3. Download the songs.
4. Look at the error.

### Expected behavior

The songs should download.

### Actual behavior

The songs seem to start the download process but do not complete. So far, I've only encountered errors with those specific songs.

### Screenshots/Screen recordings

![Screenshot_2024-07-02-10-04-47-133_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/150991300/2d4df58a-eb83-4199-95d7-4cf777fed4eb)

### RiMusic version

0.6.41

### Android version

Android 13

**Comment by fast4x** [comment]
Error?
