### ISSUE TITLE
Turkish  language

### ISSUE THREAD

**Issue by senolfndk** [fast4x/RiMusic#26]
### Description

Can you add Turkish language?

### Suggested Solution

Can you add Turkish language?

**Comment by fast4x** [comment]
Sure, are you available to translate from English to Turkish?

**Comment by senolfndk** [comment]
> Elbette, İngilizce'den Türkçe'ye çeviri yapabilir misiniz?

I'm not an expert on this subject

**Comment by fast4x** [comment]
No problem, the translation will be available from the next app version.

**Comment by fast4x** [comment]
Added, available from version 0.6.6
Thanks for your request
