### ISSUE TITLE
idk what's wrong xd

### ISSUE THREAD

**Issue by Dani3l9765** [fast4x/RiMusic#2601]
### Steps to reproduce the bug

1. Go to album "Golpe Avisa" by Cartel de Santa
2. Play any song
3. Error

### Expected behavior

Should pkay the song

### Actual behavior

I don't even know wtf is going on xd

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/150991300/f2f85527-b914-4b9d-b1d2-093ce9cac4a4

### RiMusic version

0.6.41

### Android version

Android 13

**Comment by twistios** [comment]
I had a similar problem with a playlist, it skipped many songs. But once it was done, it did not happen again (also I did not try to reproduce it), also previously skiped songs could be played.

**Comment by fast4x** [comment]
skip occur if any playback error is in progress
