### ISSUE TITLE
My Question: In which folder are downloaded songs saved?

### ISSUE THREAD

**Issue by claxcian** [fast4x/RiMusic#2603]
### Description

When download a song which folder is stored?

### Suggested Solution

Only my question

**Comment by fast4x** [comment]
Download is internal caching system in player and can't be exported.

**Comment by faustaahmad** [comment]
For me, Android 11
It saved without song's name, but you could still able to play them
`/storage/emulated/0/Android/data/it.fast4x.rimusic/files/downloads`

**Comment by claxcian** [comment]
Wouldn't it be nice to be able to save in a folder so you can share?
--- 𝘾𝙡𝙖𝙪𝙙𝙞𝙤 𝘾𝙞𝙖𝙣𝙙𝙧𝙞𝙣𝙞 ---

Il Mer 3 Lug 2024, 02:36 Faust#2997 ***@***.***> ha scritto:

**Comment by fast4x** [comment]
Unfortunately not, because it is illegal, you can listen to music but not download it and use it in other contexts. RiMusic is not a pirate music downloader but a streaming music player granted by YTM.

**Comment by claxcian** [comment]
Ok thanks
--- 𝘾𝙡𝙖𝙪𝙙𝙞𝙤 𝘾𝙞𝙖𝙣𝙙𝙧𝙞𝙣𝙞 ---

Il Mer 3 Lug 2024, 07:56 Rino Russo ***@***.***> ha scritto:
