### ISSUE TITLE
[Feature]: Explicit Label in Albums, not just artist page

### ISSUE THREAD

**Issue by HydeZero** [fast4x/RiMusic#2605]
### Description

I've noticed that on the artist page, explicit songs are marked as such. On their respective albums, the explicit label is nowhere to be seen.

![20240702_171254](https://github.com/fast4x/RiMusic/assets/128327411/6c36c25b-5462-4e26-ab23-7094b7d6f766)
Artist Page (songs marked as explicit)

![Screenshot_20240702_171605](https://github.com/fast4x/RiMusic/assets/128327411/cd9462f2-426f-49e2-bb19-8767973d2fe4)
Album Page (songs NOT marked as explicit)

This seems to be an inconsistency between the two items. Most streaming services, including YouTube Music (what this uses), mark the songs as explicit on the album page as well.

### Suggested Solution

Add explicit labels to album pages as well as artist pages.

![Screenshot_20240702_171605](https://github.com/fast4x/RiMusic/assets/128327411/4c623f58-0795-4bc0-9178-04ef51e23cb6)
Something like this, to match the layout on the song page (edited with Microsoft Paint)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.42

**Comment by HydeZero** [comment]
I'm closing this issue since it's implemented. Feel free to re-open if needed.
