### ISSUE TITLE
1:1 or 9:16 options

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#2607]
### Description

Right now YouTube Music videos are automatically put into 9:16 like youtube player.

### Suggested Solution

Although this has good quality and good use, I think it is a good idea that it is optional to be 1:1 or 9:16 and that the user can choose which size is best for them.

why add two options?  because people like me who see our songs on the lock screen get distorted

![Screenshot_2024-07-02-21-13-22-186_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/72ab74f7-c1a1-418d-a96d-10345bdd02b3)
![Screenshot_2024-07-02-21-13-32-421_lockscreen](https://github.com/fast4x/RiMusic/assets/159836335/1ae23454-2661-4241-8c1e-eb9533d41033)

### Additional Context

Also, certain songs in 9:16 size have a bug that in blurred background they are badly cropped, so I think it would be a solution

![Screenshot_2024-07-02-21-04-43-566_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/0d50ba3f-e2cb-4943-a0bd-8be6a4ee5fe0)
![Screenshot_2024-07-02-21-04-59-728_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/3609dd43-4148-4aa6-9e81-79f704824df4)

**Comment by JeePopuwu** [comment]
by the way to ask Anesh how he is doing #2074

**Comment by aneesh1122** [comment]
> by the way to ask Anesh how he is doing #2074

😅
I tried but I couldn't do it. We have to wait until fast4x completes his pending works and get to this one

**Comment by fast4x** [comment]
Videos have image in 16/9 generally

**Comment by aneesh1122** [comment]
> Videos have image in 16/9 generally

But RiMusic is cropping the thumbnail

**Comment by aneesh1122** [comment]
> Videos have image in 16/9 generally

But RiMusic is cropping the thumbnail

**Comment by fast4x** [comment]
> > Videos have image in 16/9 generally
> 
> But RiMusic is cropping the thumbnail

Yes, but based on original thumbnail... if original is 16/9... it remain...

**Comment by aneesh1122** [comment]
> Videos have image in 16/9 generally

But RiMusic is cropping the thumbnail

**Comment by aneesh1122** [comment]
Actual thumbnail
![maxresdefault.jpg](https://github.com/fast4x/RiMusic/assets/45353488/7b4ac212-31d6-4b13-8500-73058fd93a7c)

Thumbnail in RiMusic
![Screenshot_2024-07-03-13-18-12-552_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/45353488/e653f175-a54b-4e3c-9ade-9c18395f3408)


RiMusic is cropping images from all the sides

**Comment by fast4x** [comment]
Implemented video support, available from version 0.6.50
