### ISSUE TITLE
Notification progress bar not showing properly 

### ISSUE THREAD

**Issue by Romanludju** [fast4x/RiMusic#2621]
### Steps to reproduce the bug

1. I play the song
2. And see the notification shade

### Expected behavior

The progress bar should be there 

### Actual behavior

Doesn't have that progress bar 

### Screenshots/Screen recordings

![Screenshot_20240704-075445](https://github.com/fast4x/RiMusic/assets/49837296/25e192fd-15a5-485a-b7ae-967ffe1e12b4)

### RiMusic version

Latest

### Android version

Android 10

**Comment by Alaneeedu** [comment]
Quizás sea por la versión de Androide, un conocido tiene Android 10 y le pasa lo mismo pero seamos honestos, ya es una versión algo anticuada, probablemente sea por ello (tengo Androide 14 y la barra se puede visualizar correctamente)

**Comment by Alaneeedu** [comment]
Quizás sea por la versión de Androide, un conocido tiene Android 10 y le pasa lo mismo pero seamos honestos, ya es una versión algo anticuada, probablemente sea por ello (tengo Androide 14 y la barra se puede visualizar correctamente)

**Comment by fast4x** [comment]
Not reproduced..
