### ISSUE TITLE
Lyrics visibility issue.(New layout)

### ISSUE THREAD

**Issue by Its-Tony** [fast4x/RiMusic#2622]
### Steps to reproduce the bug

Choose new lyrics layout in Light and dark theme, play any song with black and white song color you will find the problem.

### Expected behavior

Lyrics should be visible without eye strain.

### Actual behavior

Lyrics are barely readable.(Cause eye strain)

### Screenshots/Screen recordings

![Screenshot_2024-07-04-08-17-08-069_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/172184183/5786f8dc-2010-4e7c-9871-fbe1609027d9)
In above screenshot using light theme, you can see completely non readable text here.
![Screenshot_2024-07-04-08-09-51-091_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/172184183/d77750d1-049c-42fd-8dce-185a1c7b6581)
Same problem in above(Light theme)
![Screenshot_2024-07-04-08-15-02-494_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/172184183/01472399-8980-4641-81ea-6524de1e3be9)
Dark theme. Cause eye strain
![Screenshot_2024-07-04-08-13-39-427_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/172184183/7c2af89e-0aa5-46bc-b04e-ee6331bdea18)
In above snap, you can see there is some darkness added in background which make text more visible. @aneesh1122  I was telling you to add blur + darkness.(Hope you understand what I mean)

### RiMusic version

0.6.41

### Android version

Android 11

**Comment by aneesh1122** [comment]
Okay. I'll inform @aneesh1152 😂😂

**Comment by aneesh1122** [comment]
Okay, let's get serious. If I add darkness it will affect the lyrics visibility of light theme + dark background.

Here's what you can do

https://github.com/fast4x/RiMusic/assets/45353488/c9e8ec81-ea53-4f8b-8667-6d427c0a021e

The highlight option will be available from the next update.

**Comment by aneesh1122** [comment]
Highlight won't improve the visibility of surrounding lyrics lines so outline is the best way imo.

This is how white shade looks on black background. Imagine having this shade on the whole screen. Won't look good. Right?
![Screenshot_2024-07-04-09-35-02-879_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/45353488/19c6b45e-46bb-4aa3-993f-bcbf7e4d46f8)

Suggest me a way which will solve everyone's problem and I'll try to do it.

**Comment by Its-Tony** [comment]
Add optional solid colour as lyrics background.

**Comment by aneesh1122** [comment]
Okay I'll add an optional black or white background. I don't think white background will look good but at least people will have the choice.

Can't do that now since fast4x asked me not to change anything in lyrics or player until the next release.

**Comment by aneesh1122** [comment]
https://github.com/fast4x/RiMusic/assets/45353488/8a19db37-78d7-4c8c-9d77-df05edf8a35e

https://github.com/fast4x/RiMusic/assets/45353488/087523ee-89f2-438d-9774-4bf2925eb0a8

@fast4x the changes are not much. You can even add it manually if you want to. Should I create a pull request?

**Comment by fast4x** [comment]
Pull request after nee release, please...

**Comment by aneesh1122** [comment]
> Pull request after new release, please...

Okay 😅
