### ISSUE TITLE
Full Screen Lyrics "Default"

### ISSUE THREAD

**Issue by Snyret** [fast4x/RiMusic#2626]
### Description

Add the option to display lyrics at full screen mode by default in the settings.

### Suggested Solution

Could be added as an on/off toggle inside the player section of settings.

**Comment by aneesh1122** [comment]
You mean this?

https://github.com/fast4x/RiMusic/assets/45353488/29f9d2fd-e5d1-4008-8e12-c4b45e182518

**Comment by fast4x** [comment]
Use new expanded lyrics...

**Comment by aneesh1122** [comment]
> > You mean this?
> > 
> > https://github.com/fast4x/RiMusic/assets/45353488/29f9d2fd-e5d1-4008-8e12-c4b45e182518
> > 
> > 
> 
> No, I mean this.
> 
> ![Screenshot_20240705_121450.jpg](https://github.com/fast4x/RiMusic/assets/139090371/9118492a-20cf-4450-b7e2-f1a540259eb8)

Why don't you use the new full screen lyrics?
