### ISSUE TITLE
Ancora nessun album

### ISSUE THREAD

**Issue by St3v3do3** [fast4x/RiMusic#2628]
### Steps to reproduce the bug

Vai all'artista. 
Scegli l'artista (nel mio caso "Eclipse")
Seleziona "Album"

### Expected behavior

Vengono visualizzati tutti gli album del gruppo.

### Actual behavior

Ritorna l'errore "Ancora nessun album"

### Screenshots/Screen recordings

![Screenshot_20240704_201240](https://github.com/fast4x/RiMusic/assets/165193578/059aeb89-cbc6-4c54-aa54-c6b73164ba34)
![Screenshot_20240704_201247](https://github.com/fast4x/RiMusic/assets/165193578/df247631-e9ed-42ba-aef2-b1d0257d69ea)

### RiMusic version

0.6.41

### Android version

Android 14

**Comment by fast4x** [comment]
Vi guardo stasera, grazie

**Comment by fast4x** [comment]
Fixed, available from version 0.6.42
