### ISSUE TITLE
Unsynchronized lyrics does not use the same outline as synchronized lyrics

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#2630]
### Steps to reproduce the bug

1. Enable glow outline
2. Switch to unsynchronized lyrics 

### Expected behavior

Unsynchronized lyrics should use the same outline as synchronized lyrics. When I use glow outline, the lyrics should not have any outline at all. Because there's nothing to highlight in unsynchronized lyrics.

### Actual behavior

Unsynchronized lyrics uses rainbow outline even though I've set it to glow outline. The lyrics should not have any outline at all.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/160244930/2a25e6f6-3d94-45fc-a554-a270669c5db0

### RiMusic version

0.6.41

### Android version

Android 14

**Comment by aneesh1122** [comment]
From the next update unsynced lyrics will also have glow. If you don't want them to glow just don't choose the glow option. For the consistency sake I added glow to both synced and unsynced.

**Comment by cMattw** [comment]
> From the next update unsynced lyrics will also have glow. If you don't want them to glow just don't choose the glow option. For the consistency sake I added glow to both synced and unsynced.

Unsynchronized lyrics should not glow since there's nothing to highlight there. It should not have any outline when glow outline is on.

**Comment by aneesh1122** [comment]
> > From the next update unsynced lyrics will also have glow. If you don't want them to glow just don't choose the glow option. For the consistency sake I added glow to both synced and unsynced.
> 
> Unsynchronized lyrics should not glow since there's nothing to highlight there. It should not have any outline when glow outline is on. 

Then disable the glow? If the user chose glow he will have the glow. You don't want it to glow but there's someone who would want that.

**Comment by cMattw** [comment]
> > > From the next update unsynced lyrics will also have glow. If you don't want them to glow just don't choose the glow option. For the consistency sake I added glow to both synced and unsynced.
> > 
> > Unsynchronized lyrics should not glow since there's nothing to highlight there. It should not have any outline when glow outline is on. 
> 
> Then disable the glow? If the user chose glow he will have the glow. You don't want it to glow but there's someone who would want that.
> 

Maybe having a separate outline option for each lyric type would be a good idea

**Comment by aneesh1122** [comment]
> > > > From the next update unsynced lyrics will also have glow. If you don't want them to glow just don't choose the glow option. For the consistency sake I added glow to both synced and unsynced.
> > > 
> > > Unsynchronized lyrics should not glow since there's nothing to highlight there. It should not have any outline when glow outline is on. 
> > 
> > Then disable the glow? If the user chose glow he will have the glow. You don't want it to glow but there's someone who would want that.
> > 
> 
> Maybe having a separate outline option for each lyric type would be a good idea

Don't worry. I've removed the glow option for unsynced lyrics.

You'll have to wait for another week though since @fast4x asked me not to do any new pull requests related to the player and lyrics.

**Comment by aneesh1122** [comment]
Regarding separate options for different types of lyrics, what's that you want in unsynced which shouldn't be there for synced? Maybe I'll add it if I think the idea is good.

**Comment by aneesh1122** [comment]
@fast4x close this as completed
