### ISSUE TITLE
Ola

### ISSUE THREAD

**Issue by Luiz098135** [fast4x/RiMusic#2631]
### Description

H

### Suggested Solution

Compartilhamento de playlist 

### Alternatives

H

### Additional Context

H

**Comment by KOLIWAN** [comment]
What do you mean?

**Comment by fast4x** [comment]
Spam

**Comment by MigoWithTigo** [comment]
He is talking about sharing playlists created in the app. It could be a great feature.

Indeed, we could copy to the clipboard the links to the songs, as NewPipe does, or even create a file following that idea.

**Comment by KOLIWAN** [comment]
> He is talking about sharing playlists created in the app. It could be a great feature.
> 
> Indeed, we could copy to the clipboard the links to the songs, as NewPipe does, or even create a file following that idea.

You can export your playlist to .csv and send to your friend
