### ISSUE TITLE
"Go to Album" does not work

### ISSUE THREAD

**Issue by sharunkumar** [fast4x/RiMusic#2632]
## Steps to Reproduce

1. Go to Songs -> Downloaded
2. Play a Song
3. Click on Mini Player
4. Click on the action bar to open the currently playing playlist
5. Long press a song and click on a song in the playlist
6. Click on "Go to Album"

### Expected

Album page opens

### Actual

Nothing happens

## Screen Recording

https://github.com/fast4x/RiMusic/assets/715417/9365d980-efa0-47a3-8ad8-5b59f982cd53

## Other Details

RiMusic Version: 0.6.41

**Comment by twistios** [comment]
Actually it can be that it seems like it does nothing as the album is opened BELOW the playlist/player.

**Comment by sharunkumar** [comment]
> Actually it can be that it seems like it does nothing as the album is opened BELOW the playlist/player.

Hmmm, even if it does, it's still a bug 🤔
Should appear at the top
