### ISSUE TITLE
Bug en la etiqueta "Explicito"

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#2638]
### Steps to reproduce the bug

1. Reproduce algún tema que contenga contenido explicito.
2. Aparece la etiqueta de explicito en medio del texto del tema.

### Expected behavior

1. Reproduce un tema que contenga contenido explicito.
2. La etiqueta (Explicito) aparece del lado izquierdo correctamente.

### Actual behavior

Cuándo reproduces un tema con algún contenido explicito esta etiqueta aparece en medio del tema.

### Screenshots/Screen recordings

![Screenshot_20240705-163728~2](https://github.com/fast4x/RiMusic/assets/170132242/005b77dc-1fb3-4675-9486-be30b81a692a)
![Screenshot_20240705-163821~2](https://github.com/fast4x/RiMusic/assets/170132242/28c74da7-8dde-40a9-beae-bbf93eda49c1)

### Logs

N/A

### RiMusic version

0.6.42

### Android version

Android 14

### Additional information

OJO: EN ESRA ACTUALIZACION LAS CANCIONES DESCARGADAS APARECEN SIN LA ETIQUETA DE EXPLICITO A MENOS QUE SE BORREN Y SE VUELVAN A DESCARGAR PERO EL PROCEDIMIENTO ES MUY TEDIOSO,  AGRADECERÍA QUE ESTOS ERRORES SE CORRIGIERAN PARA LA SIGUIENTE ACTUALIZACIÓN, GRACIAS! 🙇🏽‍♂️

**Comment by aneesh1122** [comment]
I'll try to fix this @fast4x

**Comment by aneesh1122** [comment]
![Screenshot_2024-07-06-14-46-36-834_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/45353488/e634976b-18f2-4741-bbd8-9d73b5b9d9ed)

Fixed

**Comment by fast4x** [comment]
resolved repo sync issues?

**Comment by aneesh1122** [comment]
> resolved repo sync issues?

yeah. I'll do the pull requests in a few minutes. I need to check things first.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.43
