### ISSUE TITLE
Visualizer bugged in 0.6.42

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#2639]
### Steps to reproduce the bug

1. have visualizer enabled on a previous version (0.6.41)
2. update to version 0.6.42
3. try to activate visualizer on a song

### Expected behavior

Something happens (the visualizer is shown).

### Actual behavior

Not working, I had to disable and enable it to make it work again.

### RiMusic version

0.6.42

### Android version

14

### Additional information

Maybe it is required that this happens.
Maybe one also need other config-options etc. to create the right setting for this to occur.

**Comment by twistios** [comment]
I did a thing that is a little careless: I installed KB5039302 Windows update which is reported to lead to reboots in connection with virtualisation. Guess what qemu/the android emulator is... 😅.
Now I am not able to properly use the emulator anymore.

**Comment by fast4x** [comment]
Visualizer work 
https://github.com/fast4x/RiMusic/assets/1484476/489e227b-2e10-4af7-884d-fa6c7ab636c2

**Comment by fast4x** [comment]
> I did a thing that is a little careless: I installed KB5039302 Windows update which is reported to lead to reboots in connection with virtualisation. Guess what qemu/the android emulator is... 😅.
> Now I am not able to properly use the emulator anymore.
> 
> I wanted to reproduce this bug by downloading the old version on the AVD via Github on Chrome but shortly after I select the no-account-button my physical device crashes.

Windows? RiMusic exists only for Android.
In the future would be multiplatform...

**Comment by twistios** [comment]
> Visualizer work https://github.com/fast4x/RiMusic/assets/1484476/489e227b-2e10-4af7-884d-fa6c7ab636c2

It does work but I had to disable and enable it again to make it work again.

**Comment by fast4x** [comment]
> > Visualizer work https://github.com/fast4x/RiMusic/assets/1484476/489e227b-2e10-4af7-884d-fa6c7ab636c2
> 
> It does work but I had to disable and enable it again to make it work again.
> 

but in android or emulator?

**Comment by twistios** [comment]
I am using Windows for running Android Studio and there I run the AVD (android virtual device). My Windows machine crashes/reboots when I do certain activities on the emulator.

**Comment by twistios** [comment]
It works on Android physical device.

**Comment by fast4x** [comment]
Visualizer work 
https://github.com/fast4x/RiMusic/assets/1484476/489e227b-2e10-4af7-884d-fa6c7ab636c2

Ok, please open ticket ONLY for Android physical devices, other type not supported.

**Comment by fast4x** [comment]
There are no reports other than yours, it could be a specific issue for your device.

**Comment by twistios** [comment]
I thought that this is maybe something similar as #2268.

**Comment by fast4x** [comment]
No it's different
