### ISSUE TITLE
Settings button bug

### ISSUE THREAD

**Issue by hle-cer** [fast4x/RiMusic#264]
### Steps to reproduce the bug

When I tap a different tab like "Albums", "Artists" etc. the settings icon changes.

### Expected behavior

The settings button shouldn't change the icon

### Actual behavior

The settings button changes its icon to download button.

### Screenshots/Screen recordings

![ResizedImage_2023-12-22_21-14-43_2408](https://github.com/fast4x/RiMusic/assets/125770922/071ca2ed-1a87-4897-a05f-0e17352aae90)

### RiMusic version

0.6.14

### Android version

Android 14

**Comment by fast4x** [comment]
Hi, it’s not a bug but reporting a new version you can download. It’s a test i did today, 
If you try again now you shouldn’t see it until the next version is released.
