### ISSUE TITLE
RI Music country restrictions

### ISSUE THREAD

**Issue by GNBD** [fast4x/RiMusic#2641]
### Steps to reproduce the bug

If you install RImusic in Korea, the app does not work.  To use this app in Korea, you need an overseas VPN.  However, this raises issues because it is inconvenient to use a VPN every time.  I tried using the proxy function, but it doesn't work.

### Expected behavior

The song should be searched and played...

### Actual behavior

All functions, including song search and music streaming, do not work.

### RiMusic version

Lasted

### Android version

Android 14

**Comment by fast4x** [comment]
YouTube music original work?

**Comment by GNBD** [comment]
> YouTube music original work?

probably won't work.

I think I just found out why it doesn't work.
