### ISSUE TITLE
No aparece la etiqueta "Explicito" correctamente.

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#2642]
### Steps to reproduce the bug

1. Reproduce cualquier canción.
2. Se reproduce pero no aparecen las etiquetas de contenido explicito en todas las canciones que lo son.

### Expected behavior

Reproduce todas las canciones con la etiqueta de explicito correctamente.

### Actual behavior

Reproduce el contenido explicito con etiqueta correctamente.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/170132242/f944bed4-c2ed-47d6-864a-623f4a23903f

### RiMusic version

0.6.42

### Android version

Android 14

### Additional information

N/A

**Comment by fast4x** [comment]
#2638

**Comment by fast4x** [comment]
Fixed available from version 0.6.43
