### ISSUE TITLE
Add haptic feedback to swiping songs similar to the feedback present in the mini player.

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#2645]
### Description

Add haptic feedback to swiping songs similar to the feedback present in the mini player.

### Suggested Solution

![Screenshot_20240706-113034](https://github.com/fast4x/RiMusic/assets/136909951/c49a9cb4-e585-4938-a140-691d9db70010)

**Comment by aneesh1122** [comment]
This was already in my plans. Github is giving me problems but as soon as I get it fixed I'll start working on it

**Comment by aneesh1122** [comment]
Implemented :)
