### ISSUE TITLE
Song Quality Upgrade 

### ISSUE THREAD

**Issue by Dark0Echo** [fast4x/RiMusic#2646]
### Description

I noticed a downgrade of quality in music while playing here compared to playing it in the YouTube music. Can you upgrade the song quality so that it will play like YouTube music? 

### Suggested Solution

Maybe upgrade the player or something, because once I downloaded a song from another source with a bit rate of 320kb/s. And I played it in two different player and sure enough one sounds pretty bad compared to the other one. 

### Additional Context

It maybe or maybe not only happened when I played the song with my earbuds. I am not sure if it's a problem with my earbuds, maybe not because if I play the same song in YouTube music it's much more clearer. Btw I set my music quality to high in the settings too.

**Comment by Dark0Echo** [comment]
@fast4x umm, say something. Is the problem related to my earbuds (headphone) or the rimusic player?

**Comment by fast4x** [comment]
But in RiMusic anything is changed...

**Comment by Dark0Echo** [comment]
@fast4x sorry I didn't get what you are trying to say. Can it be fixed or is it impossible to fix? Btw did you notice the downgrade of quality too?

**Comment by twistios** [comment]
> But in RiMusic anything is changed...

I guess fast4x meant "nothing".

**Comment by Dark0Echo** [comment]
@fast4x The version change has nothing to do with it. I just confirmed it's same in latest version (0.6.42) and the last one (0.6.41) too. If you want me to check in other version's I can do that too.

**Comment by aneesh1122** [comment]
> @fast4x Now I know why the quality in songs is different. If I play a song in the YouTube Music website from my mobile, it's exactly the same as RiMusic (which is pretty bad). But if I play it from the YouTube Music app it's much more clearer. Can you tell why it's like this and can you somehow fix it?

long tap on the thumbnail and look at the Itag. if it's 251 then that's the highest quality you can get for free anywhere. This is true also for YT Music official app.

There are some rare cases like [this](https://github.com/fast4x/RiMusic/issues/1698) one where the higher quality is available for free but because of API limitations RiMusic won't stream that quality.

**Comment by Dark0Echo** [comment]
![Screenshot_2024-07-06-21-59-35-58_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/168585902/27cdbe3d-f3a9-4eff-bb81-1145e8400b5f)
@aneesh1122 then it means that it can't stream in more higher quality then it's already doing? But if it's true for YouTube Music too( like you said) then the quality in RiMusic and YouTube Music should be same?

**Comment by aneesh1122** [comment]
> ![Screenshot_2024-07-06-21-59-35-58_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/168585902/27cdbe3d-f3a9-4eff-bb81-1145e8400b5f)
> @aneesh1122 then it means that it can't stream in more higher quality then it's already doing? But if it's true for YouTube Music too( like you said) then the quality in RiMusic and YouTube Music should be same? 

You can check the streaming quality in YT music too by enabling stats for nerds. See if it's using 251 or some other audio stream

**Comment by Dark0Echo** [comment]
![Screenshot_2024-07-06-22-15-29-25_801c3494cc30bc6d615367769f98046d](https://github.com/fast4x/RiMusic/assets/168585902/a77a68e5-1563-45b0-8fa2-830cfea9bed7)

@aneesh1122 It's 251 in YouTube Music too 🙂. But the difference is pretty big to notice even if you only hear it once.

**Comment by aneesh1122** [comment]
> ![Screenshot_2024-07-06-22-15-29-25_801c3494cc30bc6d615367769f98046d](https://private-user-images.githubusercontent.com/168585902/346285514-a77a68e5-1563-45b0-8fa2-830cfea9bed7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyODMwMDYsIm5iZiI6MTcyMDI4MjcwNiwicGF0aCI6Ii8xNjg1ODU5MDIvMzQ2Mjg1NTE0LWE3N2E2OGU1LTE1NjMtNDViMC04ZmEyLTgzMGNmZWE5YmVkNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxNjE4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTlhMjljYjhkNDg0YTdhYzNmYjI3OWVlMDQxMjY3ODExY2Q4NmIzOGFjMDQ2ODJmNmE3NTIzODNkMDMxNDBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OrDe5oUKUWljqZuGhrr3m7YLnRVTfXuP4OCJxLjKzTc)
> 
> @aneesh1122 It's 251 in YouTube Music too 🙂. But the difference is pretty big to notice even if you only hear it once.

are you sure about this? maybe you were streaming in 140 mp4a before? That's the only reason I can think behind difference in quality(I never noticed a difference between mp4a and opus though),

maybe request for an option to choose between opus and mp4a.

**Comment by Dark0Echo** [comment]
> > ![Screenshot_2024-07-06-22-15-29-25_801c3494cc30bc6d615367769f98046d](https://private-user-images.githubusercontent.com/168585902/346285514-a77a68e5-1563-45b0-8fa2-830cfea9bed7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyODMwMDYsIm5iZiI6MTcyMDI4MjcwNiwicGF0aCI6Ii8xNjg1ODU5MDIvMzQ2Mjg1NTE0LWE3N2E2OGU1LTE1NjMtNDViMC04ZmEyLTgzMGNmZWE5YmVkNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxNjE4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTlhMjljYjhkNDg0YTdhYzNmYjI3OWVlMDQxMjY3ODExY2Q4NmIzOGFjMDQ2ODJmNmE3NTIzODNkMDMxNDBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OrDe5oUKUWljqZuGhrr3m7YLnRVTfXuP4OCJxLjKzTc)
> > @aneesh1122 It's 251 in YouTube Music too 🙂. But the difference is pretty big to notice even if you only hear it once.
> 
> are you sure about this? maybe you were streaming in 140 mp4a before? That's the only reason I can think behind difference in quality(I never noticed a difference between mp4a and opus though),
> 
> maybe request for an option to choose between opus and mp4a.

Nope, I'm pretty much sure it's like how I reported it. Correct me if I'm wrong, maybe the loudness is the key. You know like how it's -0.5db in YouTube Music and 6.48db in RiMusic

**Comment by aneesh1122** [comment]
> > > ![Screenshot_2024-07-06-22-15-29-25_801c3494cc30bc6d615367769f98046d](https://private-user-images.githubusercontent.com/168585902/346285514-a77a68e5-1563-45b0-8fa2-830cfea9bed7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyODMwMDYsIm5iZiI6MTcyMDI4MjcwNiwicGF0aCI6Ii8xNjg1ODU5MDIvMzQ2Mjg1NTE0LWE3N2E2OGU1LTE1NjMtNDViMC04ZmEyLTgzMGNmZWE5YmVkNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxNjE4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTlhMjljYjhkNDg0YTdhYzNmYjI3OWVlMDQxMjY3ODExY2Q4NmIzOGFjMDQ2ODJmNmE3NTIzODNkMDMxNDBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OrDe5oUKUWljqZuGhrr3m7YLnRVTfXuP4OCJxLjKzTc)
> > > @aneesh1122 It's 251 in YouTube Music too 🙂. But the difference is pretty big to notice even if you only hear it once.
> > 
> > are you sure about this? maybe you were streaming in 140 mp4a before? That's the only reason I can think behind difference in quality(I never noticed a difference between mp4a and opus though),
> > 
> > maybe request for an option to choose between opus and mp4a.
> 
> Nope, I'm pretty much sure it's like how I reported it. Correct me if I'm wrong, maybe the loudness is the key. You know like how it's -0.5db in YouTube Music and 6.48db in RiMusic

![Screenshot_2024-07-06-22-05-58-505_it.fast4x.rimusic.debug-edit.jpg](https://github.com/fast4x/RiMusic/assets/45353488/35a248ae-c25b-49ae-978e-15327091befb)

Play with this

**Comment by Dark0Echo** [comment]
@aneesh1122 I was literally gonna say that it worked with "Loudness normalization" turned on. And you commented it.

**Comment by aneesh1122** [comment]
> @aneesh1122 I was literally gonna say that it worked with "Loudness normalization" turned on. And you commented it.

this app has a lot of customizations. you should play with them.
