### ISSUE TITLE
DO IMPROVEMENT IN TIME LINE BAR

### ISSUE THREAD

**Issue by STRANGERXI** [fast4x/RiMusic#2648]
### Description

![Screenshot_2024-07-06-14-36-30-94_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/136695834/c8cd9578-5e80-41b4-874c-1efbe6d702f0)

The TIMELINE BAR is getting to much invisible in the player.

### Suggested Solution

![IMG_20240706_143953](https://github.com/fast4x/RiMusic/assets/136695834/06a3b725-52d3-45d1-8ff0-d5143715b5d8)

Pls make it bold or eye-catching to view timeline.

**Comment by fast4x** [comment]
Disable Timeline Transparent in settings 

![Screenshot_2024-07-06-11-19-40-105_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/368cb1d9-12f0-4472-8ed6-4f3bbe96c2d0)

**Comment by aneesh1122** [comment]
> Pls make it bold or eye-catching to view timeline

Pls go to settings and change theme mode to 'Light'. you will get white outline. I did not factor 'System' theme mode while coding. I'll do that later.

as for timeline, do what fast4x told.

**Comment by aneesh1122** [comment]
https://github.com/fast4x/RiMusic/assets/45353488/36def50d-e25f-4c77-b7e8-18890c53289b
Do this if you want to use the light theme.

https://github.com/fast4x/RiMusic/assets/45353488/9a12f6d0-1fdf-481a-83ae-79a229cd2c42

You can also enable the gradient for better visibility
