### ISSUE TITLE
Options for choosing song quality 

### ISSUE THREAD

**Issue by mohandan1** [fast4x/RiMusic#265]
### Description

There must option for choosing song quality.

### Suggested Solution

At least three options for choosing quality of songs will be helpful......

**Comment by fast4x** [comment]
Right now the quality is high, would you like an option to reduce it?

**Comment by fast4x** [comment]
Implemented, available from version 0.6.15

**Comment by NeeRaj-2401** [comment]
@fast4x is it possible to extend this functionality to a little bit more and choose/set quality based on network connectivity (wifi/mobile)

**Comment by fast4x** [comment]
Of course, but we are always tied to the availability of the quality that YouTube offers. If there is no lower quality version, the available version is returned.

**Comment by NeeRaj-2401** [comment]
Yep, but they have included the functionality in official YTM app itself. So its more likely to have audio quality options

**Comment by fast4x** [comment]
Yep, it's just implemented in next version of RiMusic
