### ISSUE TITLE
Lyrics are not being fetched when 'E' is present

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2650]
### Steps to reproduce the bug

https://github.com/fast4x/RiMusic/assets/45353488/fe5c6719-6101-442e-85a1-009aa0228a2e

### Expected behavior

Lyrics should be fetched

### Actual behavior

No lyrics found

### RiMusic version

0.6.42

### Android version

Android 13

**Comment by fast4x** [comment]
Yes right, I'll fix

**Comment by fast4x** [comment]
Fixed, available from version 0.6.43

**Comment by aneesh1122** [comment]
> Fixed, available from version 0.6.43

Thanks man
