### ISSUE TITLE
Swipe to remove does not work

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#2652]
### Steps to reproduce the bug

1. Play a song
2. Open play queue
3. Swipe a song to remove it

### Expected behavior

Song is removed from queue.

### Actual behavior

Song stays in queue.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/54811436/db792868-22fd-479b-88d5-bfecd50a2015

### RiMusic version

0.6.42

### Android version

14

**Comment by aneesh1122** [comment]
Correction : Swipe to delete doesn't work when songs position is unlocked

https://github.com/fast4x/RiMusic/assets/45353488/44ced1fe-869d-420e-a7d9-3a46e11d28cc

**Comment by aneesh1122** [comment]
Btw you can use gradient to improve the visibility

https://github.com/fast4x/RiMusic/assets/45353488/db9902bf-3335-46a1-a52f-c0cc7b22bc5a

**Comment by fast4x** [comment]
Fixed, available from version 0.6.43

**Comment by aneesh1122** [comment]
> Fixed, available from version 0.6.43

Will there be a custom version this week? Some of the bugs actually affect the overall experience of the app.

**Comment by fast4x** [comment]
maybe
