### ISSUE TITLE
App UI laggy

### ISSUE THREAD

**Issue by u-daygupta** [fast4x/RiMusic#2655]
### Steps to reproduce the bug

Opening any playlist or holding a song for more options

### Expected behavior

No delay in it opening or atleast not enough to be noticeable

### Actual behavior

There's approx a 2 second delay in selecting and it actually playing. doesn't seem to affect playing songs. 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/121250333/48d53c19-19fb-4a7d-9d29-b5b20332c5c5

### RiMusic version

0.6.42

### Android version

Android 14

**Comment by fast4x** [comment]
Improved, available from version 0.6.43
