### ISSUE TITLE
Useless Expand Button? 

### ISSUE THREAD

**Issue by Dark0Echo** [fast4x/RiMusic#2658]
### Steps to reproduce the bug

I don't know, it just appeared when I first opened the app. 

### Expected behavior

It should work like it meant to. You know like, expand the player

### Actual behavior

Does nothing at all. And I can't find the settings to turn it off either (maybe I missed it?).

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/168585902/4009e182-9769-4262-a788-423c78da36c0

### RiMusic version

"0.6.42" 

### Android version

"Android 11"

**Comment by aneesh1122** [comment]
C'mon man, at least don't call it useless 🥹
I've worked the whole week on this.

If you really want to know what does this  expanded player do,

1) disable "show thumbnail for lyrics" in settings
2) enable lyrics
3) then use the 'expanded Player' button

**Comment by Dark0Echo** [comment]
> C'mon man, at least don't call it useless 🥹 I've worked the whole week on this.
> 
> If you really want to know what does this expanded player do,
> 
> 1. disable "show thumbnail for lyrics" in settings
> 2. enable lyrics
> 3. then use the 'expanded Player' button
> 
> There are some places I forget to disable the expanded player button and I'm fixing it right now.

Now that I used it, I can it looks pretty good 😊 👍. Btw I said useless because it did literally nothing at all when I clicked it at first, no hard feeling bro. So, can you make it so that it will not appear without me turning off the "Show thumbnail for lyrics" option, because it has no purpose at all then.

**Comment by aneesh1122** [comment]
> can you make it so that it will not appear without me turning off the "Show thumbnail for lyrics" option

I've fixed that just now



> it has no purpose at all then

it did have a purpose though. If it wasn't for this bug you wouldn't have known about this new lyrics player UI 😂

**Comment by aneesh1122** [comment]
> > C'mon man, at least don't call it useless 🥹 I've worked the whole week on this.
> > If you really want to know what does this expanded player do,
> > 
> > 1. disable "show thumbnail for lyrics" in settings
> > 2. enable lyrics
> > 3. then use the 'expanded Player' button
> > 
> > There are some places I forget to disable the expanded player button and I'm fixing it right now.
> 
> Now that I used it, I can it looks pretty good 😊 👍. Btw I said useless because it did literally nothing at all when I clicked it at first, no hard feeling bro. So, can you make it so that it will not appear without me turning off the "Show thumbnail for lyrics" option, because it has no purpose at all then.

you should also try this


https://github.com/fast4x/RiMusic/assets/45353488/6ace26d2-b965-48fc-b006-fabb62c84084

**Comment by Dark0Echo** [comment]
> > can you make it so that it will not appear without me turning off the "Show thumbnail for lyrics" option
> 
> I've fixed that just now
> 
> > it has no purpose at all then
> 
> it did have a purpose though. If it wasn't for this bug you wouldn't have known about this new lyrics player UI 😂

It's like "Failed Successfully" 🤣
