### ISSUE TITLE
Double Song name

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#266]
### Steps to reproduce the bug

Disable scrolling text in settings:
![Screenshot_20231223_160327](https://github.com/fast4x/RiMusic/assets/104271365/15dbf75c-1235-4d8d-8f23-7973de8a66c9)

Go in the player:
![20231223_160408](https://github.com/fast4x/RiMusic/assets/104271365/c9a53348-42f6-40c5-8315-7af1d26a45b5)

### Expected behavior

The artist shouldn't get replaced by the song name

### Actual behavior

The artist name is replaced by the song name

### RiMusic version

0.6.14

### Android version

Android 14 One UI 6

### Additional information

Also there is another bug where the "Pin Bar" disappears when you hold on it to seek.

in my opinion instead of the big bar becoming smaller the white tiny bar should get bigger like the "Bodied Bar"

And at the beggining its weird how it apears like an line:
![Screenshot_20231223_161156](https://github.com/fast4x/RiMusic/assets/104271365/4ae5a177-06c8-4479-850f-8d2639e43c50)

It should be an circle like that:
![Screenshot_20231223_161146](https://github.com/fast4x/RiMusic/assets/104271365/7ca7aba0-eabd-4c9d-a1f3-adece07d8f11)

**Comment by fast4x** [comment]
Initial effect isn't circle but deformed line.
Improved horizontal drag effect.
Available from version 0.6.15
