### ISSUE TITLE
Text outline problem. 

### ISSUE THREAD

**Issue by Dark0Echo** [fast4x/RiMusic#2660]
### Steps to reproduce the bug

1. Select "Blurred song cover" from Background color option. 
2. Turn on "Enable text outline" option. 
3. Select "modern" for the header option (album and artist header).

### Expected behavior

The artist name should be outlined. 

### Actual behavior

The outline is shifted to the right. 

### Screenshots/Screen recordings

![Screenshot_2024-07-06-23-53-56-49_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/168585902/a4ebf838-6c82-4847-84f8-233f00c3061d)

### RiMusic version

"0.6.42" 

### Android version

"Android 11"

**Comment by Dark0Echo** [comment]
Btw I forgot to mention that it works if you select "modern" for your header option.

**Comment by aneesh1122** [comment]
I've fixed this bug. You'll get it in the next update
