### ISSUE TITLE
Import playlist from other apps

### ISSUE THREAD

**Issue by AdrianoCastilhoCavalcante** [fast4x/RiMusic#2662]
### Description

 an option to import a playlist from YouTube/Spotify is the only thing missing for the app to become perfect

### Suggested Solution

Import a playlist from YouTube/Spotify just by sharing its link

**Comment by aneesh1122** [comment]
you can import from youtube

**Comment by ALMIGHTY-VC** [comment]
We can use scripts to convert playlist from spotify to ytmusic and then to ri i think they are available on github

**Comment by aneesh1122** [comment]
> We can use scripts to convert playlist from spotify to ytmusic and then to ri i think they are available on github

The biggest problem is transferring songs from Spotify to YT. After that it's easy peazy

I use spotify_to_ytmusic and it's accurate most of the times

**Comment by ALMIGHTY-VC** [comment]
> > We can use scripts to convert playlist from spotify to ytmusic and then to ri i think they are available on github
> 
> The biggest problem is transferring songs from Spotify to YT. After that it's easy peazy
> 
> I use spotify_to_ytmusic and it's accurate most of the times

I once used a random website which i got when i shifted from spotify to vi music it required me to login in both of the spotify and yt music account and took 10+ mins to import and export the playlist amd being a website i had to keep my browser on and phoen idle the whole time to keep the process running

**Comment by aneesh1122** [comment]
> > > We can use scripts to convert playlist from spotify to ytmusic and then to ri i think they are available on github
> > 
> > The biggest problem is transferring songs from Spotify to YT. After that it's easy peazy
> > 
> > I use spotify_to_ytmusic and it's accurate most of the times
> 
> I once used a random website which i got when i shifted from spotify to vi music it required me to login in both of the spotify and yt music account and took 10+ mins to import and export the playlist amd being a website i had to keep my browser on and phoen idle the whole time to keep the process running

Yeah you have to login in both Spotify and YT music that's why it will never be implemented in RiMusic.

**Comment by skylhub** [comment]
I have asked chatGPT to adapt Spotify csv to RIMusic CSV as per [https://github.com/fast4x/RiMusic/wiki/FAQs#what-is-the-csv-file-structure-for-importing-a-playlist-in-library](url) but now I do not know where to upload it

**Comment by ALMIGHTY-VC** [comment]
> I have asked chatGPT to adapt Spotify csv to RIMusic CSV as per [https://github.com/fast4x/RiMusic/wiki/FAQs#what-is-the-csv-file-structure-for-importing-a-playlist-in-library](url) but now I do not know where to upload it

Bruh rimusic currently only supports exporting not importing LOL

**Comment by ALMIGHTY-VC** [comment]
> > > I have asked chatGPT to adapt Spotify csv to RIMusic CSV as per [https://github.com/fast4x/RiMusic/wiki/FAQs#what-is-the-csv-file-structure-for-importing-a-playlist-in-library](url) but now I do not know where to upload it
> > 
> > 
> > Bruh rimusic currently only supports exporting not importing LOL
> 
> Support also import but songs code are different in Spotify. Use a service to transfer playlist from Spotify to YTM, after share it with RiMusic and import.

Import through backup or import seperate playlist
