### ISSUE TITLE
next in line

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#2664]
### Description

Just in this update they brought actions very similar to Spotify (which we love)

### Suggested Solution

but I feel it would be better if:

If the list buttons were swapped, the heart button, put it next in the queue, and next in the queue heart/like

![Picsart_24-07-06_14-44-11-535](https://github.com/fast4x/RiMusic/assets/159836335/03f2c7ad-391e-4bf4-ac66-e70fb267a6e5)
![Picsart_24-07-06_14-44-33-503](https://github.com/fast4x/RiMusic/assets/159836335/0f4aefed-c849-44d2-aa60-f1c745b23aad)

and the tail ones also changed from left to right, and from right to left.

![Picsart_24-07-06_14-44-53-010](https://github.com/fast4x/RiMusic/assets/159836335/d2886f2e-9187-48aa-b18b-fa994138b2d4)

### Alternatives

That's more or less how we at Spotify are used to it, and personally I think it's the best way to accommodate it.  It is personal belief.  or make a button to choose actions.  anyway THANKS FOR THE UPDATE

**Comment by JeePopuwu** [comment]
Correction: the last thing is to change the like button to “next song” and the delete button to stay as it is.

**Comment by fast4x** [comment]
Inside queue?

**Comment by JeePopuwu** [comment]
> ¿Cola dentro?

What was the part where I didn't understand x,d?

**Comment by JeePopuwu** [comment]
> ¿Hablas de listas de reproducción o canciones en cola...?

both

**Comment by JeePopuwu** [comment]
> ¿Hablas de listas de reproducción o canciones en cola...?

In the playlist, or the main list, I want the "like" button to be replaced with a "next in queue" button, and the "next in queue" button to function as the like/heart button.In the song queue, the like/heart button should act as the "next in queue" button, and the remove from queue action should remain as it currently is.
