### ISSUE TITLE
[Feature]: remove selected songs from playlist

### ISSUE THREAD

**Issue by Tre916** [fast4x/RiMusic#2668]
### Description

Currently you can only delete 1 song at a time from a playlist through tap+hold. Even if you select multiple, when you go to delete it tells you it's going to delete the whole playlist.
![Screenshot_20240706-154207~3](https://github.com/fast4x/RiMusic/assets/171737855/7f6dc06d-a848-456d-8cef-f55dfe054f9e)
![Screenshot_20240706-154248](https://github.com/fast4x/RiMusic/assets/171737855/1e437af1-9273-4d9c-8956-fa937e6705b6)

### Suggested Solution

Make a "delete from playlist" option that responds to the selected items. 

### Alternatives

Allow us to customize what the new swipe functions on the playlists do and let "remove from playlist" be an option.

**Comment by aneesh1122** [comment]
@fast4x I tried to implement "swipe left to remove from playlist" and I was able to implement it for local playlists but for piped playlists songs are not deleting through left swipe. will you look at the code?

**Comment by aneesh1122** [comment]
In the new update you can swipe left to delete from playlists. Please close this issue as completed and create a new bug issue about checkmark not working

**Comment by Tre916** [comment]
The swipe left is working!
