### ISSUE TITLE
Automatic Playlist merge with other Devices ?

### ISSUE THREAD

**Issue by BitBlockv6** [fast4x/RiMusic#2669]
### Description

Hello,
first i have to say thank you for this brilliant app.

Can I ask how to get the right app actions to automate the process of export and import the playlists via adb.
Because i want a daily merge of my Playlists on 3 - 4 Devices. I plan to merge the .db files central on the Openwrt Router and than push and import these merged playlists. If its possible to merge .db files i dont know i will have to use google for that.

Any answers would be nice (just a question)
thanks ....

### Suggested Solution

just a question

### Alternatives

just a question

### Additional Context

just a question

**Comment by fast4x** [comment]
Hi thanks, you must use piped account and sync in any device.
https://piped.video
