### ISSUE TITLE
Couldn't find a playable audio format

### ISSUE THREAD

**Issue by LEOSCHUMY** [fast4x/RiMusic#2672]
### Steps to reproduce the bug

#2475 is not working, neither in 0.6.41, neither 0.6.42 (clean install,  but It doesn't works)

### Expected behavior

Play song  (see previous issue)

### Actual behavior

Error message (see previous issue)

### RiMusic version

0.6.42

### Android version

Android 14

**Comment by fast4x** [comment]
Not related to RiMusic...
