### ISSUE TITLE
[Feature]:  RiMusic on OpenAPK

### ISSUE THREAD

**Issue by mobilenetworkltd** [fast4x/RiMusic#2674]
### Description

Hey,

I'm running a open source repo for Android apps at https://www.openapk.net and I would like to have RiMusic listed in the repo. Please review the listing at https://www.openapk.net/rimusic/it.fast4x.rimusic/

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

### Suggested Solution

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )

**Comment by fast4x** [comment]
Hi, thanks, a question: You track user info when download from repo?

**Comment by mobilenetworkltd** [comment]
Hi, no.

**Comment by fast4x** [comment]
Thanks, I'll add your download banner in project home.

**Comment by mobilenetworkltd** [comment]
It is awesome Rino. Thank you. I would be glad if you have some feedback about our site and will greatly appreciate some suggestions.

**Comment by fast4x** [comment]
Done, available on project page and website from version 0.6.43
Thanks to @mobilenetworkltd

**Comment by fast4x** [comment]
@mobilenetworkltd 
It would be very nice if the app description kept the original formatting. In the case of RiMusic it is very compressed and without formatting.
Is that something I can fix?

![2024-07-08_14h36_23](https://github.com/fast4x/RiMusic/assets/1484476/af629702-6a04-4f6b-bd0c-16a027862dfc)

**Comment by mobilenetworkltd** [comment]
I have fixed it for you.

**Comment by fast4x** [comment]
> I have fixed it for you.

Great! Thank you

**Comment by mobilenetworkltd** [comment]
You are welcome.
