### ISSUE TITLE
Bug in pacman

### ISSUE THREAD

**Issue by Glich440** [fast4x/RiMusic#2675]
### Steps to reproduce the bug

1. Open Pacman minigame

### Expected behavior

The Pacman spirte apears in the correct place

### Actual behavior

The Pacman sprite appears offset downward from the actual position

### Screenshots/Screen recordings

![Screenshot_20240707-170548_RiMusic](https://github.com/fast4x/RiMusic/assets/76230780/4dc1ba86-c767-472a-8102-941a2d7178ff)

### RiMusic version

0.6.42 & 0.6.41

### Android version

Android 14

**Comment by fast4x** [comment]
Sorry i don't understand, please explain better.
