### ISSUE TITLE
[Feature]: New Design Ideas

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [fast4x/RiMusic#2677]
### Description

While Dribbbling saw these designs and i liked them too want to see them in rimusic if possible. 
![IMG_20240707_224206](https://github.com/fast4x/RiMusic/assets/112297620/72a5a8be-deaf-4268-813f-9ced1c7368e7)
![b26cae12970d602aa4b0a051ac6a6275](https://github.com/fast4x/RiMusic/assets/112297620/2d05711f-7b60-4528-b47e-25124a907849)

### Suggested Solution

Its made by Siddhart Chakraborty and presented on Dribbble.com

### Additional Context

Additionally :- The new update is buttery smooth when yeah still get the error of ri skipping songs on a streak

**Comment by fast4x** [comment]
It’s cute but it’s common, it’s part of many streaming apps. RiMusic aims to differentiate itself with an uncommon interface.
