### ISSUE TITLE
Bug: Background Colours > match theme

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#2679]
### Steps to reproduce the bug

Go to background colours and then select match theme.

Playing next song is changing bottom bar and icon colours but background colour is not changing. 

Minimising player and reopening it only changing background colour.

Please check it.

https://github.com/fast4x/RiMusic/assets/148480722/52ddc9c3-1982-4981-bc7e-d528de172a0a

### Expected behavior

...

### Actual behavior

...

### RiMusic version

6.42

### Android version

Android 14

**Comment by Vishcot** [comment]
i agree 👍 @fast4x

**Comment by privacyfreak84** [comment]
Agreed @fast4x
