### ISSUE TITLE
Duplicate timestamp with wavy timeline

### ISSUE THREAD

**Issue by DanielSevillano** [fast4x/RiMusic#268]
### Steps to reproduce the bug

Activate wavy timeline and grab the bar in the player.

### Expected behavior

The timestamp text should be updated while grabbing the bar, just like with the other timeline styles.

### Actual behavior

A second row of text is shown below the first one, instead of updating it.

### Screenshots/Screen recordings

<img src="https://github.com/fast4x/RiMusic/assets/68847306/792da226-6cbd-4612-a6bd-fd9c995e4eaa" width="200px"/>

### RiMusic version

0.6.14

### Android version

Android 13

### Additional information

Additionally, the beginning of the bar isn't rounded when it's paused and it looks weird.

**Comment by fast4x** [comment]
Fxed, available from version 0.6.15
