### ISSUE TITLE
Icon name inconsistency in settings page

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#2680]
### Steps to reproduce the bug

....

### Expected behavior

...

### Actual behavior

...

### Screenshots/Screen recordings

![IMG_20240708_081733](https://github.com/fast4x/RiMusic/assets/148480722/52ae5e28-8d4d-46d8-a71d-62fc5ab2a5a8)

### RiMusic version

6.42

### Android version

Android 14

**Comment by fast4x** [comment]
Not confirmed, go to top...

![Screenshot_2024-07-08-04-56-59-088_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/11fcbac7-3e71-445a-bd55-74852f20bf33)

**Comment by SureshTimma** [comment]
I want names also...but names are showing full length!

**Comment by fast4x** [comment]
I want.... you should... but what you mean for names...?

**Comment by SureshTimma** [comment]
> I want.... you should... but what you mean for names...?

Name should show upto some length after that dots should show

**Comment by aneesh1122** [comment]
> Name should show upto some length after that dots should show

nope. It's fine the way it is.

**Comment by ikanakova** [comment]
I agree with @aneesh1122. It shouldn't shorten words with regard to translations.
