### ISSUE TITLE
Exportar canciones de una plataforma

### ISSUE THREAD

**Issue by Jackfire51** [fast4x/RiMusic#2681]
### Description

¿Qué tal? Espero que estén bien, la verdad RiMusic me está encantando demasiado, es una aplicación increíble, aunque sería genial si hubiese una opción que me permita exportar mis playlist o mis favoritos por ejemplo desde Spotify a RiMusic ya que en mi caso tengo muchas y si sería bastante complejo pasarlas a su app, pero les recalco RiMusic me ha dejado maravillado, es una aplicación asombrosa

De ante mano muchas gracias, y espero que les vaya muy bien ❤

### Suggested Solution

Agregar alguna opción que permita exportar playlist o favoritos de una app a RiMusic

### Additional Context

Los quiero mucho 💕

**Comment by fast4x** [comment]
Hello, thank you very much for your kindness. Unfortunately there is no way to do it directly. You can use an online tool like https://soundiiz.com/ to copy your playlists from Spotify to YouTube Music, then you can import them into RiMusic.
