### ISSUE TITLE
Piped settings grayed out

### ISSUE THREAD

**Issue by reeg33** [fast4x/RiMusic#2683]
### Steps to reproduce the bug

1. Go to settings/misc
2. Activate piped sync

### Expected behavior

I think i should be able to give my piped credentials here

### Actual behavior

But controls are all grayed out. Am i missing something ?(Could be me, I'm new to Rimusic)

Thx

### Screenshots/Screen recordings

![Screenshot_20240708-141807](https://github.com/fast4x/RiMusic/assets/37613599/17cf4b90-5837-42a4-951d-b0160d287a02)

### RiMusic version

0.6.42

### Android version

Android 13

**Comment by twistios** [comment]
I am able to activate this menu and it is not greyed. So I guess it is not normal like you experience it.

**Comment by fast4x** [comment]
I'll improve this, i don't know why it happens

**Comment by fast4x** [comment]
Improved, available from version 0.6.43
