### ISSUE TITLE
App is not recognising as music app on my phone

### ISSUE THREAD

**Issue by SureshTimma** [fast4x/RiMusic#2686]
### Description

I want to play a song, it's showing music apps on my phone but RI music is not showing.

https://chatgpt.com/share/d75a3d17-e6c7-401b-8587-0f2b80eae3d0

### Suggested Solution

Check about chatgpt solution

**Comment by fast4x** [comment]
Improved, available from version 0.6.43

**Comment by SureshTimma** [comment]
https://github.com/user-attachments/assets/5148c3c9-6c70-4dc7-bb7f-de224cf8a035

Still not showing...
