### ISSUE TITLE
[Feature]: don't allow swipong right in favorites list

### ISSUE THREAD

**Issue by teacupmaps** [fast4x/RiMusic#2688]
### Description

in the app, swiping right adds or removes a song from favorites. this feature is also active in the favorites list, where it removes the song from the list. I did it accidentally and couldn't see which song was removed

### Suggested Solution

disable the gesture in the favorites list. maybe also display the song name in the popup that says the song was removed

### Alternatives

add an undo button to the popup message "Song removed from favorites"

**Comment by SLS8** [comment]
Yes, it happens to me often too. An option to disable adding to favorites this way would be best. There already is a button for it. Or at least require that the gesture is much longer, half the screen maybe. If you accidentally move the finger two pixels, it thinks you performed swiping

**Comment by aneesh1122** [comment]
@fast4x



> display the song name in the popup that says the song was removed

I've added this.



> add an undo button to the popup message "Song removed from favorites"

but I could not do this one. Please add undo button for Pop Ups whenever something is deleted using swipe gesture.

> An option to disable adding to favorites this way would be best. There already is a button for it.

There is a button for everything. Swipe gesture is only there to do things quicker.



> Or at least require that the gesture is much longer, half the screen maybe.

There are 2 gestures so 50% would be too much. I added 25% threshold. That should be enough. There won't be any accidental swipes while scrolling too.



> If you accidentally move the finger two pixels, it thinks you performed swiping

Blame Google for this. They think it's a feature that if you're swiping fast it will override any threshold parameters and perform the task.
