### ISSUE TITLE
Albums/playlist not loading

### ISSUE THREAD

**Issue by SacredGenius07** [fast4x/RiMusic#2694]
### Steps to reproduce the bug

1. Go to search
2. Search any song
3. Open album/playlist tab
4. Choose any album/playlist

### Expected behavior

If we open any album/playlist from global search it should load.

### Actual behavior

If we open any album/playlist from global search it doesn't load. A error is shown.

### Screenshots/Screen recordings

![Screenshot_2024-07-09-11-16-29-874_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/121882028/a3ee4d53-7106-41ab-a3b9-e4f7a8bbd70d)

### RiMusic version

v0.6.40 by fast4x

### Android version

11

**Comment by fast4x** [comment]
It's fixed from 0.6.41, use latest version 0.6.42

**Comment by SacredGenius07** [comment]
> It's fixed from 0.6.41, use latest version 0.6.42

That's u so much for replying, and thank you so so much for creating such an amazing app (⁠◔⁠‿⁠◔⁠)

**Comment by fast4x** [comment]
Thanks
