### ISSUE TITLE
Visualizer 34 uses previous image

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#2696]
### Steps to reproduce the bug

1. Have visualizer activated in settings
2. Play a song in a playlist
3. Activate visualizer 34
4. Go to next song

### Expected behavior

It should use the cover image of the current song.

### Actual behavior

It uses the image of the previous song.

### Screenshots/Screen recordings

![Screenshot_20240709_101114](https://github.com/fast4x/RiMusic/assets/54811436/b589de88-f043-48f2-b94e-00922d3a9f4e)
![Screenshot_20240709_101157](https://github.com/fast4x/RiMusic/assets/54811436/7fc47f0d-e588-469f-bed6-ac32d468aab4)

### RiMusic version

0.6.42

### Android version

14

### Additional information

It does not happen all the time.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.43
