### ISSUE TITLE
[Feature]: Possible to choose actions when swiping left or right?

### ISSUE THREAD

**Issue by aaylnx** [fast4x/RiMusic#2699]
### Description

This is a feature request to have the option to customize the swipe left or swipe right actions for songs in the current queue.

### Suggested Solution

I am so glad to see swiping back!

Maybe this is a feature request, or maybe it's just a question, but is there a way to choose the action when swiping left or right? 

Currently, swiping left removes from the queue, and swiping right adds to favorites. For me, the swipe left action is just fine, but I would love an option to swipe right and add to next in the queue.

Maybe the ability to do this is already in the settings and I'm not seeing it. If it's not, then choosing the actions when swiping left/right is a feature request.

Thanks for all your work!

**Comment by JeePopuwu** [comment]
what I ask for in #2664

**Comment by aaylnx** [comment]
> what I ask for in #2664

Nice. Ok. I did not know this was the way it was in Spotify, but my podcast player, Pocket Casts, has that for the default for queues.

Swipe left = remove/delete
Swipe right = moved to next in queue

**Comment by aneesh1122** [comment]
Adding option to choose actions is too much work. I've changed it to right swipe to 'Play next' and left swipe to 'Delete' in queue and Like won't be an option in swipe gesture anymore

**Comment by ikanakova** [comment]
> Adding option to choose actions is too much work. I've changed it to right swipe to 'Play next' and left swipe to 'Delete' in queue and Like won't be an option in queue swipe gesture anymore

If I do a swipe left is there any way to undo or confirm it to prevent someone from doing it by mistake?
