### ISSUE TITLE
androidtv no focus when using remote while playback

### ISSUE THREAD

**Issue by kajdo** [fast4x/RiMusic#270]
### Steps to reproduce the bug

Search for a playlist
Start playing
Try to navigate through available ui buttons

### Expected behavior

Visual indicator of the current selected ui element

### Actual behavior

No indication ... No possibility to select pause or next

### RiMusic version

latest

### Android version

android tv (mibox3)

**Comment by DarkCrypt** [comment]
This issue can be closed as it's part of the discussion in #158. Check out that issue if you want to learn how to navigate and play music on Android TV.
