### ISSUE TITLE
Music videos 

### ISSUE THREAD

**Issue by pathania07** [fast4x/RiMusic#2700]
### Description

As ri music stream songs from YouTube music is it also possible to add music videos on rimusic.

### Suggested Solution

Video button to watch music videos with quality option

**Comment by ikanakova** [comment]
There are other apps for YouTube videos, such as NewPipe. This is a music app and should remain so.

**Comment by pathania07** [comment]
It was just a suggestion. thanks tho.
Can you also check out #2634

**Comment by Godfrey3402** [comment]
it could be amazing like if it could have the song and video tabs

**Comment by pathania07** [comment]
> it could be amazing like if it could have the song and video tabs

Well the dev said they are not gonna implement it so I don't think it'll happen. What do you think about having animated thumbnails

**Comment by fast4x** [comment]
Implemented video support, available from version 0.6.50
