### ISSUE TITLE
Play next doesn't work

### ISSUE THREAD

**Issue by FireFlamesBoy** [fast4x/RiMusic#2705]
### Steps to reproduce the bug

When you long tap on a song for opening options and then you click on play next it just doesn't play next. For some reason after some time it always happens on my device and I have tried newer and older versions. Sometimes it gives a message saying "1 song was excluded" instead of adding a song to play next 

### Expected behavior

Playing the chosen song next on queue

### Actual behavior

The song doesn't enter on next or doesn't enter the queue at all I guess

### RiMusic version

 v0.6.42

### Android version

Android 12

### Additional information

Samsung a01/ a015m; one ui core 4.1

**Comment by fast4x** [comment]
Go in settings and change time in exclude song with duration limit.
![Screenshot_2024-07-10-18-42-03-543_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/f946b3af-3f19-4b68-9324-d72d7d051d0e)

**Comment by FireFlamesBoy** [comment]
Oh thanks for letting me know! I  my case there was something wrong in the app, maybe residual from past versions. I had to uninstall and try to clean any residual files. But now I know which settings to keep! And IT'S WORKING!😁
