### ISSUE TITLE
Unexpected closure 

### ISSUE THREAD

**Issue by Kreathorx** [fast4x/RiMusic#2706]
### Steps to reproduce the bug

Just update to the latest version of the app and from then on the error proceeds

### Expected behavior

Let it work without unexpected closures 

### Actual behavior

Listening to any song the application closes without prior notice 

### RiMusic version

0.6.42

### Android version

Android 14

**Comment by fast4x** [comment]
Add here debug from settings miscellaneous

**Comment by fast4x** [comment]
Please download, try new custom version and send new log.
https://github.com/fast4x/RiMusic/tree/master/customVersion
