### ISSUE TITLE
This song cannot be played due to server restrictions

### ISSUE THREAD

**Issue by GARGVLA** [fast4x/RiMusic#2707]
### Steps to reproduce the bug

1. Search by the song
2. Click on the song
3. App doesn't play the song
4. Show the error "This song cannot be played due to server restrictions"

### Expected behavior

The song should start playing 

### Actual behavior

The song doesn't start playing and shows the error "This song cannot be played due to server restrictions"

### Screenshots/Screen recordings

![Screenshot_20240710_161039](https://github.com/fast4x/RiMusic/assets/175253248/e3450c4c-af5f-438c-8c13-260f747cc557)

### RiMusic version

0.6.40.1

### Android version

Android 14

**Comment by fast4x** [comment]
Age restriction...

**Comment by GARGVLA** [comment]
> Age restriction...

What abou the other songs? They all playing fine and they are all age restricted

**Comment by fast4x** [comment]
it depend by popup in YouTube Music
