### ISSUE TITLE
[Request] Help Me If is possible please

### ISSUE THREAD

**Issue by Fxzito** [fast4x/RiMusic#2710]
### Description

Just a request

### Suggested Solution

Could any of the Rimusic programmers help me? I use an old version of the app and the albums no longer work due to the YTM API update, but I can't update because the latest version is lagging too much on my device. If anyone could help me, I would like to know Please update the API of this version to a functional one so that albums can appear again. if possible 

Sorry for bad english i used Google Translator Im from Brazil :⁠-⁠P

### Alternatives

The version of app is 
![Screenshot_2024-07-11-00-35-50-905_com android chrome-edit](https://github.com/fast4x/RiMusic/assets/175277258/7942f866-ea87-4358-94c5-7e9f90237acd)

**Comment by fast4x** [comment]
Hello, isn't possible because version is much old, sorry.
Can you explain to me what in particular is wrong with your device?

**Comment by Fxzito** [comment]
I understand the version is very old, but thanks anyway. 
Well, the latest version keeps lagging a lot on my device for some reason that I don't know. The old version is very smooth and has no lag. I believe it is due to the most recent customizations added to the new version of the app that did not exist in this older version.

**Comment by Fxzito** [comment]
I will continue using the old version even without the albums working because it is still possible to listen to the songs, thank you very much for trying to help me.
