### ISSUE TITLE
I finally found the 2nd mystery box

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2711]
### Steps to reproduce the bug

https://github.com/fast4x/RiMusic/assets/45353488/848cde04-1b20-45f3-962b-d1f3848e8187

### Expected behavior

It looks cool

### Actual behavior

:)

### RiMusic version

0.6.42

### Android version

Android 13 HyperOS

**Comment by fast4x** [comment]
It's seen to be a bug.. not mistery box

**Comment by aneesh1122** [comment]
> It's seem to be a bug.. not mistery box

I know that. I was just joking 😅

**Comment by fast4x** [comment]
So, do you have found 2nd mistery? ahahah

**Comment by aneesh1122** [comment]
> So, do you have found 2nd mistery? ahahah

So, what's my reward? 😅😅
https://github.com/fast4x/RiMusic/assets/45353488/fda7fda3-4e2d-4ed6-88c2-b90490ff0d0e

**Comment by drago-bit** [comment]
I haven't found it, yet. 😭
