### ISSUE TITLE
Pleyer action bar buttons not selectable on Android TV

### ISSUE THREAD

**Issue by betmobil** [fast4x/RiMusic#2713]
### Steps to reproduce the bug

_On Android TV with dpad remote_
1. play a song
2. go to player
3. try to select any of enabled action bar buttons

### Expected behavior

Buttons get selected and are clickable.

### Actual behavior

Only selected part is the action bar itself (the thing behind buttons that opens queue) and buttons are not selectable in any way with the remote (it works with mouse connected to the TV)

### RiMusic version

0.6.42

### Android version

TV+ OS 5.2.0

### Additional information

Easiest option I can think of to fix this issue is to add a **TV mode** button in the settings that will just disable the _Player action bar_ as a button and will enable all buttons in the action bar including the _Arrow_ button to still be able to access queue. 
- I know TVs are not target devices for this app, but most other things work fine or are not essential so just fixing this would make this app acceptable TV audio streaming app expanding its user base.

**Comment by aneesh1122** [comment]
I think if opening queue by tapping on the action bar is disabled it can work with TV. I'll add an option to disable it and try it in my android TV.

btw are you using custom version? If yes, which layout are you using?

**Comment by aneesh1122** [comment]
Fixed

**Comment by betmobil** [comment]
I was using just stock rimusic out of the box. Thanks for updating! :)

**Comment by aneesh1122** [comment]
> I was using just stock rimusic out of the box. Thanks for updating! :)

Try 'layout 2'. It's in the settings. It's much better. Make sure that the thumbnail size is set to 'expanded'. Play with the rest of the settings.
