### ISSUE TITLE
Volume Controller resets every app session. 

### ISSUE THREAD

**Issue by Dark0Echo** [fast4x/RiMusic#2715]
### Steps to reproduce the bug

.. 

### Expected behavior

.. 

### Actual behavior

.. 

### RiMusic version

"0.6.42" 

### Android version

"Android 11" 

### Additional information

#2577

**Comment by fast4x** [comment]
You mean volume for device or app?

**Comment by Dark0Echo** [comment]
> You mean volume for device or app?

For the app. For example If I set it to 0.5 in one session it remains same for the rest of that app session.
![Screenshot_2024-07-11-22-12-20-44_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/168585902/7f207b58-04ed-41cc-b654-7f6c90837be6)
But if I close the app and clear it from the recent task and then open it again. The volume controller shows that it's like how I set it up before but it doesn't actually works that way. 
![Screenshot_2024-07-11-22-16-08-01_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/168585902/9a1d3501-da9c-4357-8d89-9446cd483f01)
What I meant is it gets to it's default value in every app session.

**Comment by fast4x** [comment]
Ok, fixed, available from version 0.6.43

**Comment by Dark0Echo** [comment]
> Ok, fixed, available from version 0.6.43

Can you add a reset button too? So that if the users wants to they can reset the value to it's default.

**Comment by fast4x** [comment]
Just click on left icon... it set both volume to app default...

**Comment by Dark0Echo** [comment]
> Just click on left icon... it set both volume to app default...

You know what, you should add something like a tutorial for this app 😄. I mean there are so many features(which is very good) and I am pretty much sure most of the users doesn't know anything at all about those features.

**Comment by fast4x** [comment]
Yes should be great to have a tutorial, it require a lot of time... You want write it?

**Comment by Dark0Echo** [comment]
> Yes should be great to have a tutorial, it require a lot of time... You want write it?

I'm very very interested to contribute in this app. But I am having a pretty serious exam going on right now, after the exam ends I will try it.

**Comment by fast4x** [comment]
Ok you will always be welcome. Best wishes for your exam.
