### ISSUE TITLE
THE APP AUTOMATICALLY EXIT WHEN IM PLAYING SONGS

### ISSUE THREAD

**Issue by dblockredaron** [fast4x/RiMusic#2717]
1. WHEN I OPEN THE APP AND PLAY SOME SONGS THE APP WILL AUTOMATICALLY EXITS I DONT KNOW WHY

### Expected behavior

Nothing

### Actual behavior

Nothing

### Screenshots/Screen recordings

Nothing

### Logs

2024-07-12T02:38:10.824:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 A5.a.u(SourceFile:38) 
	 g7.a.i(SourceFile:9) 
	 y7.J.run(SourceFile:95) 
	 D7.i.run(SourceFile:239) 
	 F7.k.run(SourceFile:3) 
	 F7.a.run(SourceFile:96) 

### RiMusic version

0.6.40.1

### Android version

Android 9

**Comment by twistios** [comment]
Please go to `Settings > Miscellaneous > Debug`. Enable "Enable debug logs". Then try to reproduce the bug. Then return to the same position in settings and copy the crash log to clipboard with the corresponding button. Please then post the copied log here.

**Comment by dblockredaron** [comment]
> Please go to `Settings > Miscellaneous > Debug`. Enable "Enable debug logs" (you have then to restart the app). Then try to reproduce the bug. Then return to the same position in settings and copy the crash log to clipboard with the corresponding button. Please then post the copied log here.

**Comment by aneesh1122** [comment]
> DONE

where's the log?

**Comment by dblockredaron** [comment]
2024-07-12T02:38:10.824: java.io.IOException: Too many open files
sun.nio.ch.IOUtil.makePipe(Native Method)
sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57)
sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36)
A5.a.u(SourceFile:38)
g7.a.i(SourceFile:9)
y7.J.run(SourceFile:95)
D7.i.run(SourceFile:239)
F7.k.run(SourceFile:3)
F7.a.run(SourceFile:96)

**Comment by twistios** [comment]
@aneesh1122 
It is in the first post.

**Comment by twistios** [comment]
You should check #2560.

**Comment by dblockredaron** [comment]
heres the log

2024-07-12T02:38:10.824:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 A5.a.u(SourceFile:38) 
	 g7.a.i(SourceFile:9) 
	 y7.J.run(SourceFile:95) 
	 D7.i.run(SourceFile:239) 
	 F7.k.run(SourceFile:3) 
	 F7.a.run(SourceFile:96)

**Comment by aneesh1122** [comment]
> heres the log
> 
> 2024-07-12T02:38:10.824: java.io.IOException: Too many open files sun.nio.ch.IOUtil.makePipe(Native Method) sun.nio.ch.PollSelectorImpl.(PollSelectorImpl.java:57) sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) A5.a.u(SourceFile:38) g7.a.i(SourceFile:9) y7.J.run(SourceFile:95) D7.i.run(SourceFile:239) F7.k.run(SourceFile:3) F7.a.run(SourceFile:96)

https://github.com/fast4x/RiMusic/issues/2640#issuecomment-2212343702

**Comment by dblockredaron** [comment]
yo twistios i check yo recommendation and i do it but i still couldn't fix the bug
i already disabled automatic update check
and also i update the app to the latest version

**Comment by aneesh1122** [comment]
> yo twistios i check yo recommendation and i do it but i still couldn't fix the bug
> i already disabled automatic update check
> and also i update the app to the latest version 

Try the custom version. That's the latest

**Comment by twistios** [comment]
You should also try to reboot your phone.

**Comment by fast4x** [comment]
Maybe i have understand this critical error.

**Comment by fast4x** [comment]
Please download, try new custom version and send new log.
https://github.com/fast4x/RiMusic/tree/master/customVersion
