### ISSUE TITLE
[Feature]: Exclude favorites and playlists songs from Radio

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2725]
### Description

Whenever I start the radio most of the suggested songs are already in my favorites and playlists and I rarely get to discover new, good and related songs. 

### Suggested Solution

Please add an option to exclude songs which are present in favorites or local playlists. RiMusic can then remove those songs from queue.

Please don't use 'Songs : All' list for filtering because those songs are random. excludedSongs should be from favorites or local playlists.

**Comment by fast4x** [comment]
This is implemented... songs are removed with discover...
