### ISSUE TITLE
[Feature]: Enhance Color Picker for Customized Theme

### ISSUE THREAD

**Issue by AstroLightz** [fast4x/RiMusic#2728]
### Description

The current color picker for the 'Customized' theme only allows selecting colors from a color wheel. There is no option to enter a specific color value.

### Suggested Solution

Add an input field next to the color preview to allow users to enter RGB and/or HEX values. This will enable users to specify the exact color they want for their theme.

**Comment by fast4x** [comment]
For now isn't planned... sorry
