### ISSUE TITLE
Player not playing and mini player not changing to regular player

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#2730]
### Steps to reproduce the bug

Again a random bug. But both happend at the same time (at least it seems like it did).

### Expected behavior

Player plays and expands regularly.

### Actual behavior

See videos.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/f8c5b2c5-f606-4651-9161-674c29e1b955

https://github.com/user-attachments/assets/ef375e86-6a1b-46e0-bc0c-487ad4f74046

### RiMusic version

0.6.43

### Android version

14

### Additional information

Might be a network issue or server problem or similar for the player-not-reacting issue.

**Comment by aneesh1122** [comment]
I get this problem of "mini player not opening" when I pause the song, do some other things for while keeping the app in background for like 10-15 mins and come back to the app

**Comment by twistios** [comment]
Maybe it is the same for me. But I am not sure.

**Comment by fast4x** [comment]
In first video, song aren't loaded, so it can't be reproduced...

**Comment by KOLIWAN** [comment]
> Maybe it is the same for me. But I am not sure.

I have the same. I suppose it happens when you pause the music, minimize the app for some time and then return to it

**Comment by twistios** [comment]
> In first video, song aren't loaded, so it can't be reproduced...

I did have a network connection at that time. Also as it can be seen from the video I can not switch to next or previous song.
