### ISSUE TITLE
Songs are skipped even if there is no delay in loading

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2731]
### Steps to reproduce the bug

https://github.com/user-attachments/assets/f6d4b189-f7b4-4473-8a51-905b9f742e4b

### Expected behavior

It shouldn't skip if the songs are loaded properly

### Actual behavior

It slips the song

### RiMusic version

0.6.43

### Android version

Android 13 HyperOS

**Comment by fast4x** [comment]
Song are skipped if an error occur...

**Comment by aneesh1122** [comment]
> Song are skipped if an error occur...

But there is no error. The song is playing perfectly

**Comment by fast4x** [comment]
Error not show...

**Comment by fast4x** [comment]
Now I’ll focus on something else. I don’t want to get stuck.

**Comment by aneesh1122** [comment]
> Error not show... 

Well, the song is skipped automatically as you can see in the video I've uploaded.

I don't use delay mode so it's no problem for me. I had this problem so thought of letting you know

**Comment by fast4x** [comment]
Yes thanks

**Comment by aneesh1122** [comment]
> Yes thanks 

You're welcome

**Comment by twistios** [comment]
> > Error not show...
> 
> Well, the song is skipped automatically as you can see in the video I've uploaded.
> 
> I don't use delay mode so it's no problem for me. I had this problem so thought of letting you know

In the first frame or so of the video I can see that you have 10 set for the meadly (delay?) mode in player controls. I also got skips with values > 0.

**Comment by twistios** [comment]
https://github.com/user-attachments/assets/acc0da97-0607-4bfd-908c-9d5475cc5012


https://github.com/user-attachments/assets/e3317bc6-3351-4ebe-93c6-1d3a8ad4d370

**Comment by fast4x** [comment]
Fixed, available from version 0.6.44

**Comment by aneesh1122** [comment]
> Fixed, available from version 0.6.44

Thanks
