### ISSUE TITLE
Crash: java.lang.NullPointerException: Attempt to invoke virtual method [...] on a null object reference

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#2732]
### Steps to reproduce the bug

A random crash. Probably it has something to do with playback beeing stop.

### Expected behavior

Not Crash.

### Actual behavior

A `java.lang.NullPointerException` Crash.

### Logs

<details><summary>Details</summary>
<p>

````
2024-07-13T00:29:45.760:	java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	 s0.k.a(SourceFile:125) 
	 p0.f.onPreDraw(SourceFile:34) 
	 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1204) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4723) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1153) 
	 android.view.Choreographer.doFrame(Choreographer.java:1079) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
````

</p>
</details> 

### RiMusic version

0.6.43

### Android version

14

**Comment by fast4x** [comment]
Your kog not talk about nothing, i can't get reproduce this bug.

**Comment by fast4x** [comment]
I'll add a workaround for log to add other info

**Comment by fast4x** [comment]
Please download, try new custom version and send new log.
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by fast4x** [comment]
Do you have background cover in player? If yes, change it without cover. The problem would be in blur effect...

**Comment by twistios** [comment]
I am using background cover. This crash did not happen since then, it might need some more time.

**Comment by twistios** [comment]
> I am using background cover. This crash did not happen since then, it might need some more time. So I also can not post a new crash log with the customVersion.

Correction, currently I am NOT using background cover.

**Comment by fast4x** [comment]
Use Blurred background?

**Comment by twistios** [comment]
Background: Match song cover

**Comment by fast4x** [comment]
try with other background not from cover...

**Comment by fast4x** [comment]
Feedback?

**Comment by twistios** [comment]
I was first using dynamic theme and also this one does work based on cover so it is not enough to use background from theme. So then I changed to Modern Black.
But anyway, this crash only happened once until now so I have no idea if it was fixed by the customVersion or the settings or it is just rare.

**Comment by twistios** [comment]
Update: A null pointer crash just now. I think the app was not playing any songs before (I was just checking the settings). Will post the log soon.

**Comment by twistios** [comment]
<details><summary>Details</summary>
<p>

````
2024-07-15T10:22:53.498:	java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	 s0.k.a(SourceFile:125) 
	 p0.f.onPreDraw(SourceFile:34) 
	 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1204) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4723) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1153) 
	 android.view.Choreographer.doFrame(Choreographer.java:1079) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
````

</p>
</details>

**Comment by fast4x** [comment]
where happen this?

**Comment by twistios** [comment]
> Update: A null pointer crash just now. I think the app was not playing any songs before (I was just checking the settings, switched for a short periode to dynamic and then back to Modern black, maybe I was on the home screen but I did not play a song). The crash then did happen when I returned from background by clicking on the app-icon. I think it opened the settings page where I was before. Will post the log soon.

**Comment by twistios** [comment]
I was able to find `p0.f.onPreDraw` in the decompiled APK. 
![Screenshot from 2024-07-16 22-47-07](https://github.com/user-attachments/assets/0bc40008-513d-4f17-a5bb-585dc4f0af23)

I know it is kind of useless, but anyway. :smiley: 
Or maybe not, for example I guess it crashes here: `kVar.a(kVar.f27108b)` (`s0.k.a(SourceFile:125)`). And based on the code it seems to be related to images.

**Comment by twistios** [comment]
Yesterday I also improved the decompiled code section a bit (by hand). So here is the code section again (names are based on what it does/is):
<details><summary>Details</summary>
<p>

````java
public /* synthetic */ OnPreDrawListenerImpl(int i8, Object obj) {
        this.f26049s = i8; // 0 or 1
        this.layout = obj; // CoordinatorLayout (CoordinatorLayoutV2)
    }

    public final boolean onPreDraw() {
        switch (this.f26049s) {
            case 0:
                CoordinatorLayoutV2 cLayout = (CoordinatorLayoutV2) this.layout;
                HandlerCompatClass handlerCompatClassVar = cLayout.handlerCompatClassVar;
                ImageReader imageReader = handlerCompatClassVar.imageReader;
                if (imageReader != null) {
                    imageReader.close();
                }
                handlerCompatClassVar.imageReader = null;
                handlerCompatClassVar.a(handlerCompatClassVar.hashTableClass);
                cLayout.viewGroup.getViewTreeObserver().removeOnPreDrawListener(this);
                cLayout.f26058f = false;
                return true;
            default: // 1
                ((CoordinatorLayout) this.layout).p(0);
                return true;
        }
    }
````

</p>
</details>

**Comment by twistios** [comment]
I was finally able to capture the exception on a screencapture.
It was playing "Levels" by Avichii before it stopped on it's own. As it can be seen from the video, there is no notification. And it shows "Starstruck" as the current playing song. I think this is the song that was playing when I put the app into background.
The play time is the one of "Starstruck", so the one for "Levels" was not shown yet. The crash happened multiple songs after putting to background. The NullPointerException then happened when I clicked on the app icon I think and there is NO log of when the music stopped on it's own.

https://github.com/user-attachments/assets/6d9d9025-0c85-4cb5-a3b8-fce13e66e940

**Comment by twistios** [comment]
I got the same crash with 0.6.44. This time the phone did not have network access and all songs were cached. It might be that it tried to connect to a Wifi-AP, but it was not connected to the internet. Also the crash happend in the background.

<details><summary>Details</summary>
<p>

````
2024-07-21T23:41:11.955:	java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	 s0.k.a(SourceFile:125) 
	 p0.f.onPreDraw(SourceFile:34) 
	 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1204) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4723) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1153) 
	 android.view.Choreographer.doFrame(Choreographer.java:1079) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
````

</p>
</details>
