### ISSUE TITLE
Option to disable shadow in Modern control button

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#2733]
### Description

`.blur` doesnt work for Android 11 or below
`.dropShadow` doesnt work for non-rectangular vector
Perhaps that's why it looks wierd on my device (Control:Modern, PlayButton:Disabled)

### Suggested Solution

**Add an Option to disable shadow in Modern control buttons**
Based on #2579, blocking `Icon(...)` with IF statement wouldnt affect anything but should disable the shadow (blurred black colored Icon)

Android 11 or below would looks like this due no `.blur` applied
![](https://github.com/fast4x/RiMusic/assets/45221211/c74987fc-b9f4-4b57-9c1f-1a5767a0ddfd)

Also unsure why the wavy circle shadow looks bad on Android 11 or below
Perhaps reduce the opacity or increase the blur or  spread of `.dropShadow`
![](https://github.com/user-attachments/assets/3af0af99-2105-4c0f-aac8-ef344b7a7033)

### Alternatives

Use `Color.Transparent` in `Icon(...)` instead of blocking it entirely

Idk if blocking `.doubleShadowDrop` in [`CustomElevateButton.kt`](https://github.com/aneesh1122/RiMusic/blob/master/app/src/main/kotlin/it/fast4x/rimusic/ui/components/themed/CustomElevateButton.kt) will affect many things or not

### Additional Context

Shadow in Modern button exist since v0.6.35 https://github.com/fast4x/RiMusic/commit/9632a76a5182809ffd2ffdf2afb11175c6916711

**Comment by aneesh1122** [comment]
1) I don't think shadows will ever be removed because it's a part of modern controls

2) as you can see in the screenshots in that page there's a different shadow for <Android 12 for wavy circle. Why it's not working for your device I don't know. I'll look into it later.

**Comment by faustaahmad** [comment]
> Why don't you play with values yourself and come up with a proper blur and spread values according to you?

Idk how to do it, I did learn python couple years ago but dont even know what to do with it

**Comment by aneesh1122** [comment]
> > Why don't you play with values yourself and come up with a proper blur and spread values according to you?
> 
> Idk how to do it, I did learn python couple years ago but dont even know what to do with it

This isn't python though.

As I said, I'll try to fix the wavy circle shadow but won't remove the shadows completely.

**Comment by faustaahmad** [comment]
> I don't think shadows will ever be removed because it's a part of modern controls

Yes I know, but I dont want to use Essential style
I like using Modern one since it first released but the shadow making it looks wierd

Looking at the code, the cause are likely to be
`.doubleShadowDrop` that's used in Thumbnail.kt, Modern.kt, CustomElevateButton.kt
`.Icon(...)` that's used in Modern.kt
`.dropShadow` in wavy circle

Sorry if I couldnt help, Idk how to do it

**Comment by aneesh1122** [comment]
> > I don't think shadows will ever be removed because it's a part of modern controls
> 
> Yes I know, but I dont want to use Essential style
> I like using Modern one since it first released but the shadow making it looks wierd
> 
> Looking at the code, the cause are likely to be
> `.doubleShadowDrop` that's used in Thumbnail.kt, Modern.kt, CustomElevateButton.kt
> `.Icon(...)` that's used in Modern.kt
> `.dropShadow` in wavy circle
> 
> Sorry if I couldnt help, Idk how to do it
> 

I never said that I can't remove it. I know how to remove it. Fast4x doesn't want shadows to be removed. If he gives his approval I'll make the shadows optional.

**Comment by fast4x** [comment]
Isn't planned to remove shadow.
But in the future would be nice to work on new simple control buttons without any effect, if interest, create a separate ticket for feature request, please.
