### ISSUE TITLE
Sound controller resets every app session. 

### ISSUE THREAD

**Issue by abrar-wadud** [fast4x/RiMusic#2736]
### Steps to reproduce the bug

1. Make any changes in the sound controller. (Specially in the 4th slider). Which comes up after holding down the play button in the player.
2. Then pause the music and close the app. Also clear it from recent task and clear it's notification. 
3. Then go back to the app and play a song. 

### Expected behavior

The sound controller slider should be same and act like that across different app sessions.

### Actual behavior

Although it shows that the slider is same as the previous app session but it doesn't work that way. It always resets to (1.0).

### RiMusic version

"0.6.43" 

### Android version

"Android 11" 

### Additional information

To notice the difference much more clearly set the slider value to less then (0.3). When you open the app second time it will show you like how you set it up before. For example if you set it to (0.3) before, then it will show you (0.3). But the actual value it works resets to is (1.0).

**Comment by Dark0Echo** [comment]
@fast4x you said that you fixed it in this version 😕

**Comment by fast4x** [comment]
For me it work now, explain better what you want!

**Comment by Dark0Echo** [comment]
I want the volume controller to be same even if I close the app and open again.

**Comment by fast4x** [comment]
In my dev devices it work...

**Comment by Dark0Echo** [comment]
Can you confirm that it works with headphones too?

**Comment by fast4x** [comment]
In my devices it work...

**Comment by Dark0Echo** [comment]
🙁🙁🙁

**Comment by fast4x** [comment]
Sorry, i haven't other to do for now

**Comment by aneesh1122** [comment]
> In my devices it work... 

Working fine on my device too. I can't reproduce this bug.

Maybe uninstalling and then installing again will fix this.

**Comment by Dark0Echo** [comment]
> > In my devices it work...
> 
> Working fine on my device too. I can't reproduce this bug.
> 
> Maybe uninstalling and then installing again will fix this.

Nah, still got the bug. Maybe try bringing the slider almost down to 0 and then increase your mobile volume. Then maybe when you open the second time you will notice the difference?? I wouldn't have problem even if it were to reset to 0.5 which is it's default value. But it resets to 1.0 which is too much sound for me.

**Comment by fast4x** [comment]
Okay, it’s already better, you’re giving extra details, so I’m working on something else for now. As soon as I have time, I’ll look at exactly what you said.
