### ISSUE TITLE
Synced Lyrics Bug: App keeps Crashing

### ISSUE THREAD

**Issue by Avejac** [fast4x/RiMusic#2739]
### Steps to reproduce the bug

Click on lyrics button
Select the synced option

### Expected behavior

Continuous play till the song ends/changes track

### Actual behavior

The app force closes

### RiMusic version

0.6.40.1

### Android version

Android 14

**Comment by fast4x** [comment]
Fo you have a background in player based on cover?
If yes, try to change background type, restart app and try again
