### ISSUE TITLE
Select language to translate lyrics is missing

### ISSUE THREAD

**Issue by Feigash** [fast4x/RiMusic#2743]
### Steps to reproduce the bug

1. Click the translate button.
2. Click the 3 dots to the right.
3. No button to change the language of

https://github.com/user-attachments/assets/8168a5e1-b44c-4c8d-a222-beb6a4be0729

 the translation.

### Expected behavior

It should show something to change the language of the translated lyric

### Actual behavior

It does not show the feature

### RiMusic version

0.6.43

### Android version

Android 12

**Comment by aneesh1122** [comment]
Use new lyrics layout

https://github.com/user-attachments/assets/fd647327-9b3f-4cb4-aa52-392cee6fadb6

**Comment by Feigash** [comment]
Oh, I didn't know... Thank you so much!

**Comment by aneesh1122** [comment]
> Oh, I didn't know... Thank you so much!

Try this too
![Screenshot_2024-07-14-15-55-01-840_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/91a1f9d1-50cf-40f9-a285-8fbfaf32fa57)

**Comment by fast4x** [comment]
Fixed, now multi language selection it's available with thubnail enabled in player, available from version 0.6.44
