### ISSUE TITLE
Pitch and tempo button

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#2745]
### Description

Pitch and tempo controls text are barely readable
![Screenshot_20240714-135243_Pixel Launcher](https://github.com/user-attachments/assets/79674cd0-d614-4a3a-9969-17fd58a754e6)

### Suggested Solution

Make the text color to white

**Comment by aneesh1122** [comment]
I think the numbers should be removed. You can already see the value inside the circle anyways

**Comment by fast4x** [comment]
> I think the numbers should be removed. You can already see the value inside the circle anyways

Not remove, numbers can be disabled...

**Comment by aneesh1122** [comment]
> Not remove, numbers can be disabled

for them it's all same. It's different for those who are coding. so, should I disable them?

**Comment by fast4x** [comment]
Yes tey to disable from properties.

**Comment by aneesh1122** [comment]
> Yes try to disable from properties.

you want them as an option inside the app? I think those numbers are not needed so it can be simply disabled. I don't understand what you mean by 'Properties'

**Comment by fast4x** [comment]
No disable without option
