### ISSUE TITLE
Can't change keyboard while searching in app

### ISSUE THREAD

**Issue by Its-Tony** [fast4x/RiMusic#2746]
### Steps to reproduce the bug

1. Open search option in RiMusic
2.  Try to change keyboard using spacebar or globe icon.

### Expected behavior

Popup with available keyboards should appear

### Actual behavior

Pop-up of available keyboards disappear quickly 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/94c4faf3-0fe3-4ac3-a2e1-91d1ebbcfe23

### RiMusic version

0.6.43

### Android version

Android 11

**Comment by Its-Tony** [comment]
@fast4x same problem still persist in v 0.6.44 . It isn't fixed.

**Comment by fast4x** [comment]
Isn't a bug of RiMusic...
