### ISSUE TITLE
Problem with the lyrics translade

### ISSUE THREAD

**Issue by Evanszca** [fast4x/RiMusic#2753]
### Steps to reproduce the bug

I go to the lyrics, touching the album cover, and click the lyrics button to spanish

### Expected behavior

I expected that the lyrics of the song will pass from inglish to spanish

### Actual behavior

But instead the lyrics still in inglish 

### RiMusic version

0.6.43

### Android version

Android 13

**Comment by fast4x** [comment]
It work for me look this
https://github.com/user-attachments/assets/5d89ebf4-8266-41f9-a571-7a0dbf226244

**Comment by aneesh1122** [comment]
First disable this in settings

![Screenshot_2024-07-15-11-08-19-276_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/5acd2262-91f1-4d5f-9354-b02d885ab798)

**Comment by fast4x** [comment]
I think that this must be set disabled by default...

**Comment by aneesh1122** [comment]
> I think that this must be set disabled by default...

Yeah. I think it's time we make people use this new lyrics layout.

**Comment by Evanszca** [comment]
Thank you, i solve the bug 😁
