### ISSUE TITLE
Autoskip

### ISSUE THREAD

**Issue by JuandaRoman** [fast4x/RiMusic#2762]
### Steps to reproduce the bug

Nothing really, I kept the default settings that I have on my cell phone

### Expected behavior

Las canciones no deberían saltarse de esta manera; deberían reproducirse completamente para poder disfrutarlas bien.

Songs should not be skipped in this way; they should be played completely in order to enjoy them properly.

### Actual behavior

No estoy seguro si es un error o una nueva función de la aplicación, pero mi problema es que cuando reproduzco una canción aleatoria, después de unos segundos, la canción se cambia automáticamente a la siguiente en la lista de reproducción. Esto es muy molesto porque no he podido escuchar ninguna canción completa. Me gustaría saber si es una función o un error y cómo podría solucionarlo. 

I'm not sure if it's a bug or a new feature of the app, but my problem is that when I play a random song, after a few seconds, the song automatically switches to the next song in the playlist. This is very annoying because I have not been able to listen to any song completely. I would like to know if this is a feature or a bug and how I could fix it.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/e48f6163-ddd2-4d1b-aa6b-092f3e5bdba1

### RiMusic version

0.6.43

### Android version

Android 11

**Comment by aneesh1122** [comment]
#2731

**Comment by fast4x** [comment]
Fixed, available from version 0.6.44
