### ISSUE TITLE
Infinit queue glitch

### ISSUE THREAD

**Issue by Lukilei** [fast4x/RiMusic#2764]
### Steps to reproduce the bug

Go to the player and open the queue. Now click on the miniplayer in the lower part, click on the queue again etc.

### Expected behavior

The miniplayer shouldn't be openable.

### Actual behavior

You can open the miniplayer and open the queue again.

### RiMusic version

0.6.43

### Android version

11

**Comment by fast4x** [comment]
Fixed, available from version 0.6.44
