### ISSUE TITLE
Unable to import a publicaly shared YT music playlist to a existing local playlist

### ISSUE THREAD

**Issue by harshitv804** [fast4x/RiMusic#2765]
### Steps to reproduce the bug

Exact steps I followed:
1. copy the link of the YT music playlist. open RiMusic, go to "go to link" tab, paste the URL and search.
2.  Now the playlist shows up, click the "add to playlist" button and select a local playlist. as shown in the images below:
![image](https://github.com/user-attachments/assets/da1b567f-0378-46b7-acdd-f0bc173ad479)
![image](https://github.com/user-attachments/assets/5f105d11-a3d0-4a03-bae9-d099e04108f7)
3. now an alert pops saying "Done", then when i go back to library, its not added to the local playlist. Also IDK what does this button does:
![image](https://github.com/user-attachments/assets/2fae10ba-0f98-4fe7-aa02-c2e25bf930a4)
even I tried clicking that then the app just closes and nothing happens.

### Expected behavior

when I click the add to playlist button and choose the local playlist it all the songs inside that public playlist should be added to the local playlist. there is other option "Import playlist", where its working good but it separately creates a local playlist with its name but I just want to add to the existing playlist. Also a bookmark button for the playlist would be nice as ViMusic has that option. 
Thank you

### Actual behavior

when I click the add to playlist button and choose the local playlist it all the songs inside that public playlist are not being added to the local playlist. it alerts as "Done" but no update is seen. what I had to do is, first import the public playlist as save it locally, then I had to from it to the other local playlist. so its really taking time to add it. kindly request you to resolve this issue.

### Screenshots/Screen recordings

added images in steps to reproduce the bug.

### RiMusic version

0.6.43

### Android version

Android 13

**Comment by fast4x** [comment]
Fixed, available from version 0.6.44

**Comment by harshitv804** [comment]
> Fixed, available from version 0.6.44

Thanks, waiting for the next release. 
❤️ from India 🇮🇳

**Comment by RoronoaZoro030102** [comment]
Where's link tab menu in rimusic
