### ISSUE TITLE
My phone does not recognize Ri Music as a music application

### ISSUE THREAD

**Issue by Cuchurrumin19** [fast4x/RiMusic#2766]
### Steps to reproduce the bug

My phone does not recognize Ri Music as a music application, the equalizer does not work because of that

https://github.com/user-attachments/assets/5b41543e-8705-4f5f-a31c-e65671d7e102

### Expected behavior

That the cell phone recognizes Ri Music as a music application

### Actual behavior

It doesn't

### RiMusic version

0.6.43

### Android version

Android 12

### Additional information

Is there something that can be done?  please
My cell phone is a Realme 7

**Comment by fast4x** [comment]
RiMusic isn't a music player but an app for streaming music from YouTube...

**Comment by Cuchurrumin19** [comment]
> RiMusic isn't a music player but an app for streaming music from YouTube Music...

I understand that, but for some reason my device's equalizer doesn't work with Ri Miusic and external equalizers saturate the sound a lot :c.  I have tested the app on other devices and the equalizer works normally

**Comment by fast4x** [comment]
It means that the device does not allow the use of the equalizer... In the future i'll add internal equalizer... maybe.
