### ISSUE TITLE
Save Playlist - Guardar lista de reproducción

### ISSUE THREAD

**Issue by Willy2222** [fast4x/RiMusic#2767]
### Steps to reproduce the bug

1- Open Playlist (once expanded)
2- Add to Playlist
3- In some resolutions, the subsequent menu does not appear below

***************************************

1- Abrir Lista de reproducción (una vez desplegada)
2- Añadir a la lista de reproduccion
3- En algunas resoluciones no aparece el siguiente menú debajo.

### Expected behavior

Bug - Error 

### Actual behavior

In some small screen resolutions:
When attempting to save a playlist using "add to a new playlist," the subsequent menu with its options does not appear below.

*****************

En ciertas resoluciones de pantalla:
Cuando se intenta guardar una lista de reproducción con "añadir a una nueva lista de reproducción" 
no aparece el siguiente menú debajo con sus opciones.

### RiMusic version

0.6.43

### Android version

8.1.0

**Comment by fast4x** [comment]
Add a video please

**Comment by fast4x** [comment]
try set menu as list, same result?

Name of setting is wrong, Sorry 
![Screenshot_2024-07-17-20-54-23-280_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/e5790c2c-2459-4f85-b2b5-3030091fcd5a)

**Comment by Willy2222** [comment]
Yes, same result...

**Comment by fast4x** [comment]
I've added an improvement, after new release please send me feedback if it work, available from version 0.6.44

**Comment by Willy2222** [comment]
Desde ya, quiero expresar mi profundo agradecimiento por su dedicación. Admiro enormemente su trabajo y esfuerzo. Le envío un cordial saludo

****************************************

From now on, I want to express my deep gratitude for your dedication. I greatly admire your work and effort. I send you warm regards.

**Comment by fast4x** [comment]
Thank you are very kind
