### ISSUE TITLE
App crash while lyrics are opened

### ISSUE THREAD

**Issue by ClestonMoura** [fast4x/RiMusic#2768]
### Steps to reproduce the bug

1. Search for Tick Tock by Joji (at least that's what I was listening to when the bug happened)
2. Play the song and open the lyrics (full screen)
3. Wait until the app closes on it's own

### Expected behavior

App should not crash

### Actual behavior

App is crashing

### RiMusic version

0.6.43

### Android version

Android 13

### Additional information

Smartphone: POCO F5

**Comment by fast4x** [comment]
Try to use expanded player layout instead of old lyrics in full screen mode

**Comment by ClestonMoura** [comment]
Uploading Screenrecorder-2024-07-16-16-08-46-752~3.mp4…

Here's a video for more context...

**Comment by ClestonMoura** [comment]
https://github.com/user-attachments/assets/a598399f-4883-4828-a98b-ccba2c2d8241

Here's a video for more context...

**Comment by fast4x** [comment]
Try this, go to miscellaneous settings, enable debug log.
Restart app, open lyrics again, when crash, reopen app, go to miscellaneous settings, click con Copy crash log and paste here...

**Comment by aneesh1122** [comment]
> 2024-07-16T16:21:04.779: java.io.IOException: Too many open files sun.nio.ch.IOUtil.makePipe(Native Method) sun.nio.ch.PollSelectorImpl.(PollSelectorImpl.java:57) sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) A5.a.u(SourceFile:38) g7.a.i(SourceFile:9) y7.J.run(SourceFile:95) D7.i.run(SourceFile:239) F7.k.run(SourceFile:3) F7.a.run(SourceFile:96)

Try new lyrics layout. Go to settings and disable 'show thumbnail for lyrics'. If you want bigger lyrics window use expanded player.

**Comment by ClestonMoura** [comment]
> > 2024-07-16T16:21:04.779: java.io.IOException: Too many open files sun.nio.ch.IOUtil.makePipe(Native Method) sun.nio.ch.PollSelectorImpl.(PollSelectorImpl.java:57) sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) A5.a.u(SourceFile:38) g7.a.i(SourceFile:9) y7.J.run(SourceFile:95) D7.i.run(SourceFile:239) F7.k.run(SourceFile:3) F7.a.run(SourceFile:96)
> 
> Try new lyrics layout. Go to settings and disable 'show thumbnail for lyrics'. If you want bigger lyrics window use expanded player.
> 
>  Screenrecorder-2024-07-17-01-06-13-507.mp4

I'll give it a try. Thanks!

**Comment by ClestonMoura** [comment]
> > 2024-07-16T16:21:04.779: java.io.IOException: Too many open files sun.nio.ch.IOUtil.makePipe(Native Method) sun.nio.ch.PollSelectorImpl.(PollSelectorImpl.java:57) sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) A5.a.u(SourceFile:38) g7.a.i(SourceFile:9) y7.J.run(SourceFile:95) D7.i.run(SourceFile:239) F7.k.run(SourceFile:3) F7.a.run(SourceFile:96)
> 
> Try new lyrics layout. Go to settings and disable 'show thumbnail for lyrics'. If you want bigger lyrics window use expanded player.
> 
>  Screenrecorder-2024-07-17-01-06-13-507.mp4

It worked. But now there's a new problem. If I keep the lyrics open and move the app to the background, the music stop. But if I close the lyrics before moving to the background, it keeps playing

**Comment by aneesh1122** [comment]
> > > 2024-07-16T16:21:04.779: java.io.IOException: Too many open files sun.nio.ch.IOUtil.makePipe(Native Method) sun.nio.ch.PollSelectorImpl.(PollSelectorImpl.java:57) sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) A5.a.u(SourceFile:38) g7.a.i(SourceFile:9) y7.J.run(SourceFile:95) D7.i.run(SourceFile:239) F7.k.run(SourceFile:3) F7.a.run(SourceFile:96)
> > 
> > Try new lyrics layout. Go to settings and disable 'show thumbnail for lyrics'. If you want bigger lyrics window use expanded player.
> > 
> >  Screenrecorder-2024-07-17-01-06-13-507.mp4
> 
> It worked. But now there's a new problem. If I keep the lyrics open and move the app to the background, the music stop. But if I close the lyrics before moving to the background, it keeps playing

Could you please post a video?

**Comment by ClestonMoura** [comment]
> > > > 2024-07-16T16:21:04.779: java.io.IOException: Too many open files sun.nio.ch.IOUtil.makePipe(Native Method) sun.nio.ch.PollSelectorImpl.(PollSelectorImpl.java:57) sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) A5.a.u(SourceFile:38) g7.a.i(SourceFile:9) y7.J.run(SourceFile:95) D7.i.run(SourceFile:239) F7.k.run(SourceFile:3) F7.a.run(SourceFile:96)
> > > 
> > > 
> > > Try new lyrics layout. Go to settings and disable 'show thumbnail for lyrics'. If you want bigger lyrics window use expanded player.
> > > Screenrecorder-2024-07-17-01-06-13-507.mp4
> > 
> > 
> > It worked. But now there's a new problem. If I keep the lyrics open and move the app to the background, the music stop. But if I close the lyrics before moving to the background, it keeps playing
> 
> Could you please post a video?



> > > > 2024-07-16T16:21:04.779: java.io.IOException: Too many open files sun.nio.ch.IOUtil.makePipe(Native Method) sun.nio.ch.PollSelectorImpl.(PollSelectorImpl.java:57) sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) A5.a.u(SourceFile:38) g7.a.i(SourceFile:9) y7.J.run(SourceFile:95) D7.i.run(SourceFile:239) F7.k.run(SourceFile:3) F7.a.run(SourceFile:96)
> > > 
> > > 
> > > Try new lyrics layout. Go to settings and disable 'show thumbnail for lyrics'. If you want bigger lyrics window use expanded player.
> > > Screenrecorder-2024-07-17-01-06-13-507.mp4
> > 
> > 
> > It worked. But now there's a new problem. If I keep the lyrics open and move the app to the background, the music stop. But if I close the lyrics before moving to the background, it keeps playing
> 
> Could you please post a video?

I don't think I can. I tried to reproduce that second bug, but nothing happened. It's just working now. I think it was a network issue with my wifi...

**Comment by aneesh1122** [comment]
> > > > > 2024-07-16T16:21:04.779: java.io.IOException: Too many open files sun.nio.ch.IOUtil.makePipe(Native Method) sun.nio.ch.PollSelectorImpl.(PollSelectorImpl.java:57) sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) A5.a.u(SourceFile:38) g7.a.i(SourceFile:9) y7.J.run(SourceFile:95) D7.i.run(SourceFile:239) F7.k.run(SourceFile:3) F7.a.run(SourceFile:96)
> > > > 
> > > > 
> > > > Try new lyrics layout. Go to settings and disable 'show thumbnail for lyrics'. If you want bigger lyrics window use expanded player.
> > > > Screenrecorder-2024-07-17-01-06-13-507.mp4
> > > 
> > > 
> > > It worked. But now there's a new problem. If I keep the lyrics open and move the app to the background, the music stop. But if I close the lyrics before moving to the background, it keeps playing
> > 
> > Could you please post a video?
> 
> 
> 
> > > > > 2024-07-16T16:21:04.779: java.io.IOException: Too many open files sun.nio.ch.IOUtil.makePipe(Native Method) sun.nio.ch.PollSelectorImpl.(PollSelectorImpl.java:57) sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) A5.a.u(SourceFile:38) g7.a.i(SourceFile:9) y7.J.run(SourceFile:95) D7.i.run(SourceFile:239) F7.k.run(SourceFile:3) F7.a.run(SourceFile:96)
> > > > 
> > > > 
> > > > Try new lyrics layout. Go to settings and disable 'show thumbnail for lyrics'. If you want bigger lyrics window use expanded player.
> > > > Screenrecorder-2024-07-17-01-06-13-507.mp4
> > > 
> > > 
> > > It worked. But now there's a new problem. If I keep the lyrics open and move the app to the background, the music stop. But if I close the lyrics before moving to the background, it keeps playing
> > 
> > Could you please post a video?
> 
> I don't think I can. I tried to reproduce that second bug, but nothing happened. It's just working now. I think it was a network issue with my wifi...

Maybe. I'm glad it's working fine for you now.

**Comment by fast4x** [comment]
Actual full lyrics will be removed.
