### ISSUE TITLE
No RiMusic in Android Auto's list

### ISSUE THREAD

**Issue by brunoli49** [fast4x/RiMusic#2772]
### Steps to reproduce the bug

Starting AA : no RiMusic

### Expected behavior

RiMusic should appear in AA

### Actual behavior

In AA settings, I don't see RiMusic in app list.

### RiMusic version

0.6.43

### Android version

Android 14

**Comment by fast4x** [comment]
Must enable it Miscellaneous settings...

![Screenshot_2024-07-17-13-09-19-493_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/0c0be726-457c-4bec-9dad-8782dc32258c)

**Comment by fast4x** [comment]
Look... 
https://github.com/fast4x/RiMusic/wiki/FAQs#why-does-android-auto-not-see-rimusic

**Comment by brunoli49** [comment]
oh thanks. So sorry 😊.  "Miscellaneous settings" were not really visible with dark mode...

**Comment by fast4x** [comment]
Enjoy with RiMusic and your Android Auto.
