### ISSUE TITLE
Traducción de las letras en idioma distinto al configurado

### ISSUE THREAD

**Issue by Nisselle** [fast4x/RiMusic#2774]
### Pasos para reproducir el error

1. Primero me dirigí a elegir la canción que deseaba escuchar 
2. Luego le di click para ver la letra de la canción 
3. Luego seleccione para traducir la canción pero se traduce en el idioma inglés en lugar del español que es con el uso la aplicación 

### Comportament sperat

Espero que al igual que en actualizaciones anteriores se traduzca las letras de las canciones al español

### Comportament real

Se traducen las letras de las canciones en un idioma distinto (inglés) al que tengo configurado en la aplicación (español)

### Capturas de pantalla/Grabaciones de pantalla

https://github.com/user-attachments/assets/34ff8e6b-e361-4ccb-82f9-6ebf677c8db8

![Screenshot_20240717-075523](https://github.com/user-attachments/assets/ec29479a-c0ef-4882-aeeb-5582b3d5f4e6)

### Log

_Nu răspuns_

### Versión RiMusic

0,6,43

### Versión de Android

Android 11

### Informații suplimentare

Si el idioma que deseó la traducción es del inglés al español, en vez de cambiar al español la misma letra en ingles se mantiene en el inglés al presionar la opción de traducción

**Comment by aneesh1122** [comment]
https://github.com/fast4x/RiMusic/issues/2743#issuecomment-2227204258
