### ISSUE TITLE
Floating search bar is hidden behind the minimised player 

### ISSUE THREAD

**Issue by sidsharths1245** [fast4x/RiMusic#2780]
### Steps to reproduce the bug

Open the app

### Expected behavior

The floating search button should be on top of the minimised player 

### Actual behavior

The floating search bar is hidden behind the minimised player

### Screenshots/Screen recordings

![Screenshot_20240718-041521](https://github.com/user-attachments/assets/9f0da341-d548-4dfe-afd6-6383ea529b51)

### RiMusic version

0.6.43

### Android version

Android 13

**Comment by fast4x** [comment]
Move it where you want by holding it down
