### ISSUE TITLE
Dynamic theme not working 

### ISSUE THREAD

**Issue by Randomguy369** [fast4x/RiMusic#2781]
### Steps to reproduce the bug

Go to settings > User interface > Theme > Dynamic

### Expected behavior

Dynamic theme should be getting applied after switching songs

### Actual behavior

Dynamic theme isn't applied after switching songs , closing the player and then opening it again applies  it

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/8bf991a1-1234-469d-95af-c86fe011ad2f

![Screenshot_2024-07-18-07-44-17-51_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/c537c14c-739f-47d0-930b-88169b8acafe)

### RiMusic version

0.6.43

### Android version

Android 14

**Comment by privacyfreak84** [comment]
Same issue here for several months, along with the material you theme bug

**Comment by fast4x** [comment]
Fixed, available from version 0.6.44
