### ISSUE TITLE
[Feature]: Skip songs with volume buttons

### ISSUE THREAD

**Issue by MirkoDL** [fast4x/RiMusic#2784]
### Description

I would like to have the ability to change songs using the volume buttons.

### Suggested Solution

With the screen off, holding volume up will switch to the next song, volume down to the previous song

### Alternatives

Alternatively you could use the "shake" gesture, I would like to be able to use it with the screen off though

**Comment by fast4x** [comment]
Implemented, available from version 0.6.44

**Comment by MirkoDL** [comment]
Hi, thank you for the excellent and very fast work.
I think it would be better though if to skip a song using the volume keys, this would only happen on long press (3 seconds for example).
Right now, having the option enabled, I can't otherwise turn up the volume of the audio on the phone.
Is it possible to make this modification?

**Comment by fast4x** [comment]
Unfortunately you can not at least for now, but you can turn up the volume by pausing the player. The song switch is active if you are listening to a song, pausing instead the keys adjust the volume.
