### ISSUE TITLE
New lyrics style

### ISSUE THREAD

**Issue by mohandan1** [fast4x/RiMusic#279]
### Description

I think There should be a different style for showing lyrics.in current style, words are too small and not so much attractive and also,we can't see full lyrics and can't jump on by clicking on synced lyrics...

### Suggested Solution

Lyrics style like Spotify and yt music app would be great if possible 

### Alternatives

Or,lyrics should be shown full NOW PLAYING page like apple music and other apps instead of showing on cover only....

**Comment by fast4x** [comment]
Hi, you mean it would be better to see the lyrics at full screen?

**Comment by mohandan1** [comment]
Yup👍

**Comment by fast4x** [comment]
Implemented, available from version 0.6.15
