### ISSUE TITLE
Translation problem 

### ISSUE THREAD

**Issue by lilunknown** [fast4x/RiMusic#2791]
### Steps to reproduce the bug

1. Choose language: Portuguese 
2. Then choose a song of your choice, whatever language it is
3. Click on the letters button
4. After translation 

### Expected behavior

When clicking on the translate option, it should translate into my language, but otherwise it doesn't translate.

### Actual behavior

I went to listen to the artist lil peep, chose the song in question and clicked on the translation option and it didn't work... And that wasn't just with him but **with all** the songs .

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/a739c61f-f5dd-43af-87c1-dfbe0eb2546b

### RiMusic version

0.6.43

### Android version

Android 12

### Additional information

Celular xiaomi redmi note 9 pro

**Comment by fast4x** [comment]
Try ths, set another language in app, restart app
Set portuguese lang, try to translate.

Suggetion for you, instead classic layout, use blurred background cover without thumbnail, and use expanded view in player

**Comment by aneesh1122** [comment]
Do this

https://github.com/fast4x/RiMusic/issues/2743#issuecomment-2227204258

**Comment by fast4x** [comment]
Improved, now you can select any language for translation... available soon in version 0.6.44
