### ISSUE TITLE
[Feature]: Filter option to show both cached and downloaded songs

### ISSUE THREAD

**Issue by soumiknandi** [fast4x/RiMusic#2793]
### Description

Add a new filter option on songs screen to show both cached and downloaded songs. Currently either i can select downloaded songs or cached songs but unable to select both at the same time.

### Suggested Solution

Either enable multi select for downloaded and cached option in filter or add a new filter option.

**Comment by fast4x** [comment]
Unified cached and downloaded sections in home songs, available from version 0.6.47
