### ISSUE TITLE
[feature]: button paste in "link search"

### ISSUE THREAD

**Issue by lebgdeyoutube** [fast4x/RiMusic#2794]
### Description

Why not add a “paste” button in the song search section via a link
It saves a lot of time if you have a lot of links to paste 
![Screenshot_2024-07-19-05-18-45-141_it fast4x rimusic-edit](https://github.com/user-attachments/assets/0313928f-f3f6-4dbe-ae34-08e7e52bef67)

### Suggested Solution

next to the other buttons (so refocus the others in the center)

**Comment by fast4x** [comment]
Yes nice idea, thanks

**Comment by aneesh1122** [comment]
> Yes nice idea, thanks 

Can you implement copying the clipboard automatically?

**Comment by fast4x** [comment]
Should be better a button, not an automatic paste

**Comment by aneesh1122** [comment]
> Should be better a button, not an automatic paste

It will reduce the steps. Everyone chooses to open a link from search only if they have something in their clipboard. You're only making things easy for them.

**Comment by fast4x** [comment]
Ok

**Comment by fast4x** [comment]
Implemented, added button and automatic paste when open go to link page, available from version 0.6.44
