### ISSUE TITLE
In Android Auto their is no quick selection or home menu, and the RiMusic doesn't seem to provide new music

### ISSUE THREAD

**Issue by oualidA** [fast4x/RiMusic#2796]
### Steps to reproduce the bug

Connect to android auto with RiMusic, only the already visionized musics are showing

### Expected behavior

Possibility to search or access other music, or found a music from the Head unit 

### Actual behavior

the RiMusic on the car work as it as offlined, no possibility to see or select new music like (the quick selection window in phone)
can't search by artist or other, the list remain empty.
althought connectivity isn't an issue, the RiMusic works fine on the phone

### RiMusic version

v0.6.43

### Android version

Android 14

**Comment by fast4x** [comment]
Android Auto have much limitations in numbers of song that can be displayed. Search it's a nice feature, thanks for the idea.
