### ISSUE TITLE
Ajout fonctionnalités 

### ISSUE THREAD

**Issue by SamusQc** [fast4x/RiMusic#2799]
### Description

Est-ce que ce serait possible d'ajouter une fonction pour transférer nos playlists de musique vers Rimusic

### Suggested Solution

Ajouter une fonction de transfert de musique ou de playlists

**Comment by fast4x** [comment]
From Youtube Music is already possible, share the playlist with RiMusic and click on the import button. If you use other platforms you need to transfer playlists to YouTube Music.
