### ISSUE TITLE
Atomix Virtual dj 

### ISSUE THREAD

**Issue by BSJ33** [fast4x/RiMusic#2800]
### Description

Hello ! It's possible insert rimusic in the software atomix virtual dj ? Make à live mix ?

### Suggested Solution

Link rimusic on virtual dj

**Comment by fast4x** [comment]
Hi, you cannot use RiMusic as a music source for other applications.

**Comment by BSJ33** [comment]
C'est bien dommage

Le ven. 19 juil. 2024, 16:54, Rino Russo ***@***.***> a
écrit :

**Comment by fast4x** [comment]
Tell me more about Atomic dj

**Comment by BSJ33** [comment]
Atomique virtual.dj est un logiciel de mix en live et il y a la possibilité de jouer en live des sons venant de soundcloud etc.... un lien vers votre serveur serai super
