### ISSUE TITLE
Error when viewing lyrics and spontaneous closures 

### ISSUE THREAD

**Issue by Kou-tester** [fast4x/RiMusic#2801]
### Steps to reproduce the bug

1:Sometimes when you play the song and change it or even when you put the song in full screen it closes spontaneously 
2: when trying to translate the lyrics, it does not translate and they only move a little to the left 

### Expected behavior

The spontaneous closure occurs after playing some playlist

### Actual behavior
it happens every 1 hour I think or if it is not spontaneous 
.

### RiMusic version

version 0.6.43

### Android version

Android 14

**Comment by Kou-tester** [comment]
change the language of the app and restart but the lyrics problem has not been solved

**Comment by aneesh1122** [comment]
Do this
https://github.com/fast4x/RiMusic/issues/2743#issuecomment-2227204258

**Comment by fast4x** [comment]
You use lyrics in full screen?

**Comment by fast4x** [comment]
Maybe it's fixed, available from version 0.6.44
