### ISSUE TITLE
Errores en la nueva versión.

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#2804]
### Steps to reproduce the bug

1. No estoy seguro si solo a mi me pasa pero la animación de carga siempre está activa, no es mala pero en lo personal no me agrado y espero puedan implementar una opción para activar o quitarla manualmente.
2. El audio es distinto, cuando reproduzco música el altavoz del dispositivo o auriculares se escucha más de el lado izquierdo.
3. La nueva función implementada de cambio de canciones con el control de volumen esta increíble pero presenta errores puesto que quiero subir o bajar volumen con pantalla encendida y cambia de canción, mi dispositivo es un Motorola g84 y tiene está función predeterminada.
4. Falta optimización en la aplicación, últimamente estaba muy lenta desde la última versión y ahora es más notorio el retraso.
5. La nueva función implementada con el icono de estrella no se puede desactivar (Quizás la allá pero me puse a indagar y no encontré una solución).
6. ¡Gracias por brindar este reproductor tan increíble! Llevo meses usándolo y en verdad que no me arrepiento de haberlo usado, es tan increíble notar los cambios que esté reproductor va haciendo. 😸

### Expected behavior

N/A

### Actual behavior

N/A

### Screenshots/Screen recordings

N/A

### Logs

N/A

### RiMusic version

0.6.44

### Android version

Android 14

### Additional information

Esperó con ansias la nueva actualización! ¡Gracias! 😸

**Comment by fast4x** [comment]
4 Where do you notice a lot of slowness?

**Comment by Alaneeedu** [comment]
> 4 ¿Dónde notas mucha lentitud?

En la cola de reproducción, tiene mucho congelamiento al deslizar o inclusive desde la búsqueda en linea las canciones o artistas se me congela, creí que era mi dispositivo pero inclusive le subi la frecuencia de actualización de la pantalla a 120hz y aún así tengo complicaciones con ello 😔

**Comment by fast4x** [comment]
Decrease max numbers of songs in queue, it seems to be a memory full. 
Enable Debug in miscellaneous settings, and send log.

**Comment by Alaneeedu** [comment]
> Disminuya la cantidad máxima de canciones en la cola; parece que la memoria está llena. Habilite la depuración en configuraciones diversas y envíe el registro.

Al parecer solo funciona en álbumes, intenté desde una lista de reproducción con al menos 240 canciones y tiene lag, inclusive con un EP con 9 canciones tiene congelamiento

**Comment by fast4x** [comment]
enable debug, use app and after a period, paste here the log
