### ISSUE TITLE
[Feature]: add option to change look of artist portrait

### ISSUE THREAD

**Issue by chelIey** [fast4x/RiMusic#2807]
### Description

the current (new?) way of displaying artist profile images crops much of the photo with two garish gradients while simultaneously providing a harsh border with the menu when set anywhere but the bottom of the screen
![Screenshot_20240720_021600](https://github.com/user-attachments/assets/382331fc-1de6-49e2-b3d7-bf3660725fe7)
![Screenshot_20240720_021510](https://github.com/user-attachments/assets/8f49e43d-564e-4bea-8acd-6f85aea6a254)
![Screenshot_20240720_021447](https://github.com/user-attachments/assets/32adbc7e-b706-44cb-ae61-7d465957444f)

### Suggested Solution

add an option to display the artist's profile image on the profile page as a smaller square (or even a circle) that can lay above the name, so it can be seen without any cropping - much like the album cover in the player.

### Additional Context

ideally this would also be done with the 'artists' tab, as the current circle crop often crops out the corners of the image that the artists provide - especially for those who like to use their latest album as their profile image.
![Screenshot_20240720_022141](https://github.com/user-attachments/assets/e11431de-bd6c-40e0-9d23-c8c51815bfe0)

**Comment by fast4x** [comment]
Thanks for idea but artist page it's ok
