### ISSUE TITLE
For you not updating 

### ISSUE THREAD

**Issue by Randomguy369** [fast4x/RiMusic#2808]
### Steps to reproduce the bug

Quick picks > for you

### Expected behavior

Last played or most played songs should be updating in the for you tab

### Actual behavior

Only the first song is getting updated in the for you tab and the other songs which are shown there , I haven't even listened them , they are there from the start

### Screenshots/Screen recordings

![Screenshot_2024-07-20-07-45-10-21_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/cdc1457f-4612-47ff-a382-7a0eca176ef4)
![Screenshot_2024-07-20-07-48-39-13_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/19dcb49f-a373-42bd-a04a-e98b7c9a0fc9)

### RiMusic version

0.6.44

### Android version

Android 14

**Comment by twistios** [comment]
As you can read from the screenshot, it says "Last played", not "Most Played". Just a note.

**Comment by twistios** [comment]
I think that the songs in "For you" are not expected to be songs you already listened to but recommendations based on what the setting is (last played/most played/random). But if it is not changing, then something seems wrong.

**Comment by Randomguy369** [comment]
> I think that the songs in "For you" are not expected to be songs you already listened to but recommendations based on what the setting is (last played/most played/random). But if it is not changing, then something seems wrong.

As per my knowledge , quick picks is for the recommendations but the for you tab particularly includes, the most viewed/recent/random whatever you choose, whenever am listening to a song the first song of the for you tab changes to that and all others remain the same , moreover those songs are no where close to what i have been listening to
