### ISSUE TITLE
Songs are auto switching 

### ISSUE THREAD

**Issue by SacredGenius07** [fast4x/RiMusic#2810]
### Steps to reproduce the bug

Play a song 

### Expected behavior

If I open the player in previous versions then songs were not auto switching 

### Actual behavior

The songs keep switching in 1 sec

### RiMusic version

0.6.44

### Android version

11

### Additional information

It's because of the medley option u get while holding play/pause. The songs don't switch If I keep the player minimised.

**Comment by SacredGenius07** [comment]
> Yes it's normal, this feature work in this way

Can't I switch it off or something cause my player is generally maximized, it's kinda annoying 😐

**Comment by fast4x** [comment]
Set Medley duration to 0, tap and hold play/pause button and set Medley time...0

**Comment by SacredGenius07** [comment]
> Set Medley duration to 0, tap and hold play/pause button and set Medley time...0

That's the problem the minimum it goes is 1 and on 1 it just keep switching it's kinda funny. Why would anyone need a 1 sec switch time😅
![Screenshot_2024-07-20-14-16-53-688_it fast4x rimusic](https://github.com/user-attachments/assets/e20c6c5c-3a7c-4ecc-897d-a18fc7c6c8a6)

**Comment by twistios** [comment]
You can set it to zero by tapping the hourglass symbol.

**Comment by SacredGenius07** [comment]
> You can set it to zero by tapping the hourglass symbol.

Thank u sooooo much, can u also tell what does blur  effect do?

**Comment by twistios** [comment]
You can use cover as background via settings. With the blur setting, you can change how strong the applied blurring effect is. Zero is no blur. You can also disable the thumbnail such that there only is the background.

**Comment by SacredGenius07** [comment]
Thanks 🙏🏻
