### ISSUE TITLE
[Feature]: Being able to remove the new star button "Remove liked and playlist song from queue"

### ISSUE THREAD

**Issue by lebgdeyoutube** [fast4x/RiMusic#2811]
### Description

Being able to delete the new button which allows you to delete liked and playlist titles in the queue. the button is in "player action bar". You can delete all the buttons except him from the settings (unless you deactivate everything, then even this button disappears)
![Screenshot_2024-07-20-05-46-09-973_it fast4x rimusic-edit](https://github.com/user-attachments/assets/71908084-cb5c-4d07-ad24-898ca3de390e)

![Screenshot_2024-07-20-05-45-34-246_it fast4x rimusic-edit](https://github.com/user-attachments/assets/5b3d7dd2-af0b-412c-af8b-3bb14bea9bf1)

### Suggested Solution

Add parameter

**Comment by fast4x** [comment]
Ok

**Comment by fast4x** [comment]
Implemented, available from version 0.6.45
