### ISSUE TITLE
Expanded Player Button Missing

### ISSUE THREAD

**Issue by drago-bit** [fast4x/RiMusic#2812]
### Steps to reproduce the bug

After the update, the Expanded Player Button was present, but missing after a restart. Also, can't find any option to enable it in the settings.

### Expected behavior

Expanded player button should present in the action bar.

### Actual behavior

On updating, expanded player button present in the action bar, but missing after a restart.

### Screenshots/Screen recordings

![Screenshot_2024-07-20-10-51-41-034_it fast4x rimusic-edit](https://github.com/user-attachments/assets/ba64d538-17a2-4f40-9738-ab9bb6cf2fec)

### RiMusic version

0.6.44

### Android version

Android 14

### Additional information

Great update by the way.

**Comment by fast4x** [comment]
![Screenshot_2024-07-20-09-01-27-248_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/928a1068-1068-44fd-b93c-64411d17b570)

disable

**Comment by drago-bit** [comment]
That option was already disabled in the player. But I found what was the actual problem.

'**Show thumbnail for lyrics**' should be disabled first.

![IMG_20240720_151920.jpg](https://github.com/user-attachments/assets/82923704-68c5-4f67-a9dd-c3f1bb518bc9)

By the way, where can I find that '**Status for the nerds**'?  🤠

**Comment by aneesh1122** [comment]
> Status for the nerds

Disable 'show thumbnail'

**Comment by aneesh1122** [comment]
@fast4x the reason why 'expandedplayer' icon was visible initially and not later is because you forgot to change the rememberpreference of expandedlyrics in playermodern file

**Comment by fast4x** [comment]
@aneesh1122 So .. correct you ..
