### ISSUE TITLE
Can't reorder the songs

### ISSUE THREAD

**Issue by Squad8991** [fast4x/RiMusic#2813]
### Steps to reproduce the bug

Go to playlist 
Try to reorder the songs

### Expected behavior

Songs should reorder 

### Actual behavior

Nothing happened 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/3efc1b2b-6f00-4507-a2c1-f582435bc315

### RiMusic version

0.6.44

### Android version

Android 11

**Comment by twistios** [comment]
Also it feels harder to remove songs from playlists compared to previous versions. It seems related so I am posting this here.

https://github.com/user-attachments/assets/490b1bc4-8f83-4f0a-9074-2ef18600de2e

**Comment by twistios** [comment]
It seems like you have to release the finger from the screen for more than a half second or so after you moved the playlist before you can remove a song.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.45

**Comment by fast4x** [comment]
Now can download custom version 
https://github.com/fast4x/RiMusic/tree/master/customVersion
