### ISSUE TITLE
Song skip in normal player

### ISSUE THREAD

**Issue by Wander42** [fast4x/RiMusic#2814]
### Steps to reproduce the bug

as far as i know this happens with everything but i experienced it with the album: The way of all flesh by Gojira i started the album got through the first two tracks and then it randomly started doing this i noticed it doesnt when in mini player however.

### Expected behavior

not skip the songs

### Actual behavior

it does anyways in normal player

### Screenshots/Screen recordings

Uploading Screen_Recording_20240720_024459.mp4…

### RiMusic version

current

### Android version

Android 14

**Comment by fast4x** [comment]
What version you use?

**Comment by Wander42** [comment]
0.6.44 the current one

**Comment by DavidDiaz377** [comment]
the same thing happened to me. I was able to solve it by reducing the "medley duration" to zero. You can access this option by holding down the "play" / "pause" button. I hope it works for you.

**Comment by Wander42** [comment]
YES THANK YOU that works perfectly, will i have to fix this like everytime i open the app or should it stay the same (im 99% itll stay but just wanna make sure)

**Comment by DavidDiaz377** [comment]
You're welcome! You are correct, it is not necessary to fix every time you enter the application.
