### ISSUE TITLE
[Feature]: Be able to transfer playlist from Deezer or Spotify

### ISSUE THREAD

**Issue by adan0701** [fast4x/RiMusic#2815]
### Description

I use Deezer before I found this app then I wanted to transfer my Deezer playlist to here but I didn't find a way to do that. I believe it is clear my English is not very good.

### Suggested Solution

If it possible do it in the same way than you do with playlist on YouTube music

**Comment by fast4x** [comment]
You can use https://soundiiz.com/ for transfer to youtube music, after this you can share it with RiMusic and import

**Comment by cheUriBuddy** [comment]
If you ever feel like to move your playlist from one platform to another then :-
TracklistPro (https://tracklist.pro/) is a simple and efficient tool that lets you transfer playlists effortlessly between Spotify, Apple Music, YouTube Music, and more, ensuring your music stays intact without the hassle of rebuilding from scratch.
