### ISSUE TITLE
Flickering, text and seekbar not readable

### ISSUE THREAD

**Issue by AndiLeni** [fast4x/RiMusic#2817]
### Steps to reproduce the bug

Switch between songs and have a look at the new fullscreen background covers in the player.

### Expected behavior

The text must be readable and the seekbar be usable.

### Actual behavior

Switching between the songs causes the background images to flicker and resize. 
The new fullscreen image background prevents the user from reading the current title and using the seekbar as it is not visible in most cases (dark text on dark background). 

### Screenshots/Screen recordings

Video demonstrating the flicker:
https://github.com/user-attachments/assets/b22c035f-8897-4790-b9a7-5e7778a4fcfb

UI elements not readable and hence not usable.
![807](https://github.com/user-attachments/assets/52edc919-2c3e-4bbc-b3cf-1c9ab533112d)

### RiMusic version

0.6.44

### Android version

Android 12

### Additional information

Please consider reverting this UI change or make an option to go back to the "not-fullscreen-cover".

**Comment by aneesh1122** [comment]
Same song, same theme and all that
![Screenshot_2024-07-20-17-46-52-320_it.fast4x.rimusic.jpg](https://github.com/user-attachments/assets/c60d0c29-4fe1-4a21-aa26-a87a98951374)

**Comment by AndiLeni** [comment]
@aneesh1122 

> that's not a flicker. The thumbnail needs to be loaded so it's keeping a placeholder until the thumbnail is loaded.
It is, but not the loading of the image itself than rather the rersizing of the images. First the placeholder is loaded, than the cover image is loded as a small image and then the cover image is stretched to fill the whole screen. See my video, especially at the end you can cleary see how the images change their size.
It is simply not visually appealing.

> as for visibility problems, go to setting and enable "Show Bottom Gradient" or "Enable Text Outline"
That is a workaround but not a fix. I do not want black text with a white border on a black background, the text itself should be white for good readability.
Also your screenshot shows very well that there is something wrong, as the icons do not get a border and are still nearly invisible due to their color.

**Comment by aneesh1122** [comment]
> See my video, especially at the end you can cleary see how the images change their size.\nIt is simply not visually appealing.

Yeah that's weird. That never happened to me. You're not even using an old device. I'm using A13 and the image is directly cropped.
@fast4x pls look into this

> the text itself should be white for good readability.

Why don't you use the dark theme? The text will be white, it looks much more pleasing IMO.

![Screenshot_2024-07-20-18-53-08-254_it.fast4x.rimusic.debug.jpg](https://github.com/user-attachments/assets/64212235-e8c6-43bf-a684-dc8319b3ec4d)

No problems white background too
![Screenshot_2024-07-20-18-53-53-775_it.fast4x.rimusic.debug.jpg](https://github.com/user-attachments/assets/171bc6f4-d45b-411e-89d6-3aa0cde5c70c)

**Comment by AndiLeni** [comment]
> Why don't you use the dark theme? The text will be white, it looks much more pleasing IMO.

I do use the dark mode, bot only at night.
But then I have the same issue with bright cover images 😅

![Screenshot_20240720-153022](https://github.com/user-attachments/assets/dba7bd55-625d-4d47-9150-ac45e8aa919c)

**Comment by aneesh1122** [comment]
> > Why don't you use the dark theme? The text will be white, it looks much more pleasing IMO.
> 
> I do use the dark mode, bot only at night.
> But then I have the same issue with bright cover images 😅
> 
> ![Screenshot_20240720-153022](https://github.com/user-attachments/assets/dba7bd55-625d-4d47-9150-ac45e8aa919c)
> 

Enable 'bottom gradient' from settings

**Comment by aneesh1122** [comment]
> > Why don't you use the dark theme? The text will be white, it looks much more pleasing IMO.
> 
> I do use the dark mode, bot only at night.
> But then I have the same issue with bright cover images 😅
> 
> ![Screenshot_20240720-153022](https://github.com/user-attachments/assets/dba7bd55-625d-4d47-9150-ac45e8aa919c)
> 

![Screenshot_2024-07-20-19-25-24-806_it.fast4x.rimusic.jpg](https://github.com/user-attachments/assets/d3131fce-ce44-40f7-ba43-5b0dd9e943c5)

**Comment by AndiLeni** [comment]
@fast4x this issue is not resolved. 
The main cause of this issue still persists and was not resolved, only workarounds were presented. 

You should have a look at the flickering and resizing images.

**Comment by fast4x** [comment]
Will be resolved at the most appropriate time
