### ISSUE TITLE
Can't add playlist to another playlist 

### ISSUE THREAD

**Issue by Squad8991** [fast4x/RiMusic#2819]
### Steps to reproduce the bug

Go to playlist 
Click on add to playlist 

### Expected behavior

Playlist should be able to added to another playlist 

### Actual behavior

Screen freezes

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/386d9d7b-a78e-44ba-aa8e-5459b275e211

### RiMusic version

0.6.44

### Android version

Android 11

**Comment by fast4x** [comment]
Fixed, available from version 0.6.45

**Comment by fast4x** [comment]
Now can download custom version 
https://github.com/fast4x/RiMusic/tree/master/customVersion
