### ISSUE TITLE
Visual bug in fake audio bar

### ISSUE THREAD

**Issue by PPereaC** [fast4x/RiMusic#2820]
### Steps to reproduce the bug

Hello. There is a visual bug in fake audio bar. There is like a grey line blinking all the time. Can you solve it? Thanks :).

### Expected behavior

:)

### Actual behavior

:)

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/75190929-2651-4e8b-9507-465967a6de1b

### RiMusic version

Last version

### Android version

Android 13

**Comment by AndiLeni** [comment]
Probably related to #2818

**Comment by twistios** [comment]
The grey line is supposed to be the loading-animation when the song is loading, but I should not be there while playing the music.

**Comment by fast4x** [comment]
Removed animation in timeline, available from version 0.6.45

**Comment by Vishcot** [comment]
> Removed animation in timeline, available from version 0.6.45

we want it early, if possible..it is annoying..can we get it fixed earlier?

**Comment by fast4x** [comment]
Maybe, I'm working on a fastidious bug, if resolved soon, I'll create a custom version.
