### ISSUE TITLE
No instance is available to access piped

### ISSUE THREAD

**Issue by ZandrexV** [fast4x/RiMusic#2822]
### Steps to reproduce the bug

1. Go to log in with your piped account in the "Activate synchronization with Piped" section"
2. When you put your account, you will need to put an instance (which there is NONE) and without that instance it does not let you access. (If you keep it on to that option, you will always get the "No instances found" error.)

### Expected behavior

that there is some kind of instance like kavin.rocks, drgns.space, among others (full list in https://github.com/TeamPiped/Piped/wiki/Instances)

### Actual behavior

Unfortunately, no instance is available.

### Screenshots/Screen recordings

![20240720_122404](https://github.com/user-attachments/assets/794988b1-fe99-4a59-b9d9-93374eee5268)

### RiMusic version

0.6.44

### Android version

Android 6.1

**Comment by fast4x** [comment]
If play any songs, work?
Data connection work?

**Comment by ZandrexV** [comment]
> ¿Funciona si reproduzco alguna canción? ¿ Funciona la conexión de datos?
No, neither. And I restarted my internet several times and it didn't work.

https://github.com/user-attachments/assets/e99cb30e-10d5-43d2-b9af-a561cf4ef6d9
