### ISSUE TITLE
Couldn't find a playable audio format

### ISSUE THREAD

**Issue by Hikari2w2** [fast4x/RiMusic#2823]
### Steps to reproduce the bug

Search a youtube video song (Dayone Dayone from *namirin)

Play the song

It won't play the song, I'm getting this message instead: "couldn't find a playable audio format"
![Screenshot_2024-07-20-11-34-35-136_it fast4x rimusic](https://github.com/user-attachments/assets/f21821b4-9bed-4297-934d-caf8303c1cb3)

### Expected behavior

Search a YouTube video song (Dayone Dayone from *namirin)

Play the song

The song should be playing properly 

### Actual behavior

Some music videos won't reproduce at all.

### RiMusic version

0.6.44

### Android version

11

### Additional information

I already tried by changing the audio quality to High, low, automatic, etc.

**Comment by fast4x** [comment]
I'll debug it

**Comment by sanga000** [comment]
I have reported the same problem before #2301

**Comment by fast4x** [comment]
Fixed, available from version 0.6.47

**Comment by Hikari2w2** [comment]
It's not fixed 🫤

**Comment by luke-jr** [comment]
RiMusic literally can't play a single song (not even the "Most played song" suggestions) for me
