### ISSUE TITLE
Shadow effect looks bad

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#2824]
### Description

![Screenshot_2024-07-20-20-53-23-456_it fast4x rimusic](https://github.com/user-attachments/assets/35aa253f-4713-4d22-9d28-2073d6d1bb4e)

### Suggested Solution

Can we reduce/disable shadow behind buttons. They look awful.

**Comment by aneesh1122** [comment]
off topic - why you don't have thumbnail in your player? It's Impossible according to my codes.

**Comment by sayyid5416** [comment]
> off topic - why you don't have thumbnail in your player? It's Impossible according to how I coded.

I don't know. It's been like this since latest update, maybe cache issue _(If you guys not having this)_ _(I didn't bother to find out 😅)_

**Comment by aneesh1122** [comment]
> > off topic - why you don't have thumbnail in your player? It's Impossible according to how I coded.
> 
> I don't know. It's been like this since latest update, maybe cache issue _(If you guys not having this)_ _(I didn't bother to find out 😅)_

It's not a cache issue. A few weeks ago I added an option to disable thumbnail. In this update fast4x made that a default option. He also made 'blurred song cover' a default option so it's surprising that one thing changed for you and the another one didn't.

Anyways, go to settings and enable 'show thumbnail' to get back the thumbnail.

**Comment by sayyid5416** [comment]
Got the thumbnail back. Thanx. Btw I still think there should b e a way reduce/disable shadow. It's too harsh.

**Comment by aneesh1122** [comment]
> Got the thumbnail back. Thanx. Btw I still think there should b e a way reduce/disable shadow. It's too harsh.

You can also change buttons. Use essential buttons

**Comment by ALMIGHTY-VC** [comment]
> off topic - why you don't have thumbnail in your player? It's Impossible according to how I coded.

What does the star button does??

**Comment by aneesh1122** [comment]
> > off topic - why you don't have thumbnail in your player? It's Impossible according to how I coded.
> 
> What does the star button does?? 

It removes songs you've liked or added to playlists from your queue.

Since RiMusic doesn't consider your listening history while playing radio, you can find many songs you've already listened to.

**Comment by ALMIGHTY-VC** [comment]
> > > off topic - why you don't have thumbnail in your player? It's Impossible according to how I coded.
> > 
> > 
> > What does the star button does??
> 
> It removes songs you've liked or added to playlists from your queue.
> 
> Since RiMusic doesn't consider your listening history while playing radio, you can find many songs you've already listened to.

Oh it suddenly popped up so didnt knew about it got it thanks

**Comment by sayyid5416** [comment]
@fast4x Its still same, why closed?

**Comment by fast4x** [comment]
Will be done in the future with new controls type.
