### ISSUE TITLE
[Feature]: queue list is laggy

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#2825]
### Description

Queue list is laggy whenever i open it, there is no smooths scrolling

### Suggested Solution

Please improve performance issues

**Comment by fast4x** [comment]
How much songs number have in queue?

**Comment by Logan7899** [comment]
> How much songs number have in queue?

Default

**Comment by fast4x** [comment]
try to decrease

**Comment by Logan7899** [comment]
Still laggy

**Comment by fast4x** [comment]
ok
