### ISSUE TITLE
Song titles not visible in dynamic background

### ISSUE THREAD

**Issue by Jeanhzo** [fast4x/RiMusic#2828]
### Steps to reproduce the bug

Dynamic Cover Background

### Expected behavior

Colors opposite to the background

### Actual behavior

Titles are not visible

### Screenshots/Screen recordings

![Screenshot_2024-07-20-12-24-51-056_it fast4x rimusic-edit](https://github.com/user-attachments/assets/d60fdba6-88fd-4795-bb4a-4a6559a52284)

### RiMusic version

0.6.44

### Android version

12

**Comment by isjustlucas** [comment]
Change your app color theme
