### ISSUE TITLE
App keeps stopping.

### ISSUE THREAD

**Issue by agenericsavvy11** [fast4x/RiMusic#2832]
### Steps to reproduce the bug

Installed latest stable, tried to open.

### Expected behavior

Should have opened.

### Actual behavior

Instead, closes and says ' Ri music keeps stopping '

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/e01e883c-1909-48bb-bdfa-63d89b5ec3fa

### RiMusic version

0.6.44

### Android version

13

**Comment by fast4x** [comment]
Check permissions for app

**Comment by fast4x** [comment]
it's first time that you install RiMusic?

**Comment by ALMIGHTY-VC** [comment]
Need the logs bro i think you might be getting prompts with rimusic keeps crashing there you will be able to find logs or different os have different method to obtain logs you have to find yours. 
but you wont regret going through this hassle i can tell ya its a very good music streaming all

**Comment by agenericsavvy11** [comment]
> Need the logs bro i think you might be getting prompts with rimusic keeps crashing there you will be able to find logs or different os have different method to obtain logs you have to find yours. but you wont regret going through this hassle i can tell ya its a very good music streaming

does matlog app is enough?

**Comment by agenericsavvy11** [comment]
> it's first time that you install RiMusic?

no, used to have A14. It worked fine. But had to switch to A13 (cuz A14 RAM consuming).

**Comment by agenericsavvy11** [comment]
> Check permissions for app

nah, same story.

**Comment by ALMIGHTY-VC** [comment]
Try the custom version

**Comment by agenericsavvy11** [comment]
> Try the custom version

tried custom version too, same thing

**Comment by agenericsavvy11** [comment]
Update:
I did give permissions the first time but the app didn't open. Gave it another go in latest version yesterday, granted permissions and it works now. 🤞🏽
