### ISSUE TITLE
Option to swap functionality between Prev/Next and –5/+5

### ISSUE THREAD

**Issue by AryanSaraf** [fast4x/RiMusic#2833]
### Description

An option in the settings to swap the functionality of the arrow buttons (controls): press left arrow to go to the start of the song / previous song or press right arrow to go to the next song, and press and hold left or right arrow to skip 5 seconds backwards or forwards, respectively.

### Suggested Solution

On toggling said option, I wish to be able to simply press the arrow buttons once to move backwards and forwards by 5 seconds while a long press takes me to the previous and next song.

**Comment by fast4x** [comment]
It's just implemented...
