### ISSUE TITLE
Broken restore

### ISSUE THREAD

**Issue by Max-More** [fast4x/RiMusic#2834]
### Steps to reproduce the bug

1. Create a backup
2. Restore the backup created

### Expected behavior

When the backup is restored it should have  settings preferences, liked songs, playlists. 

### Actual behavior

Only the settings preferences get restored. 

### RiMusic version

0.6.44

### Android version

13

### Additional information

Restoring the same RiMusic backup file to ViMusic works as it intended, adds the favourites, playlists and settings.

**Comment by fast4x** [comment]
Settings isn't included in backup, it work normally.

**Comment by Max-More** [comment]
What about the favourites and playlists?

**Comment by Max-More** [comment]
> Settings isn't included in backup, it work normally.

What about the favourites and playlists?

**Comment by fast4x** [comment]
i have restored without problems...

**Comment by Max-More** [comment]
> i have restored without problems...

Sorry for the trouble, i guess i opened the app back up too soon
