### ISSUE TITLE
[Feature]: a tab for recently removed favorites 

### ISSUE THREAD

**Issue by Max-More** [fast4x/RiMusic#2839]
### Description

Because of the gesture to like and remove like while scrolling in the favorites sometimes a song gets accidentally removed. 
It's not easy to catch the pop up before it fades

### Suggested Solution

a tab for recently removed favorites. Just 10 would be more than enough.

**Comment by aneesh1122** [comment]
There shouldn't be any accidental swipes since I made sure that gestures work only when you swipe it horizontally. It won't trigger if you swipe with any angle.
