### ISSUE TITLE
[Feature]: Sapere quale è la durata totale delle canzoni in una playlist

### ISSUE THREAD

**Issue by jaki444** [fast4x/RiMusic#284]
### Description

Ciao, sarebbe bello se riuscisi a fare nelle playlist una parte che segna la somma totale delle durata delle canzoni nella playlist

### Suggested Solution

quando premi su una playlist ti da la lista di canzoni te potresti mettere che in fondo o in cima venga scritta la somma totale della durata della playlist.

**Comment by fast4x** [comment]
Carina come idea, ok.

**Comment by fast4x** [comment]
Implementato, disponibile dalla versione 0.6.15

Implemented, available from version 0.6.15

**Comment by fast4x** [comment]
Riapro il ticket perché in alcune situazioni si prese un bug che crasha l'app.

I reopen the ticket because in some situations you caught a bug that crashed the app.

**Comment by jaki444** [comment]
okay grazie mille. un ultima cosa, se vuoi scrivere sono in inglese è ok, lo capisco non ti preoccupare. Dimmi te se vuoi ti scrivo anche io in inglese almeno da fare capire a tutti le richieste che ti faccio.

**Comment by fast4x** [comment]
Si è meglio in inglese così tutti possono leggere.

**Comment by jaki444** [comment]
all right

**Comment by fast4x** [comment]
Do you can try this custom version 0.6.16.1 with fix of total playtime on playlist and return feedback?
Should not go wrong by opening a playlist in library and show total play time near songs count.

https://rimusic.xyz/download/app-release.apk

**Comment by fast4x** [comment]
Implemented, available from version 0.6.17
