### ISSUE TITLE
Rimusic

### ISSUE THREAD

**Issue by SamusQc** [fast4x/RiMusic#2840]
### Steps to reproduce the bug

Quand je tante d'ouvrir l'application un message apparaît qui dit que l'application " plante continuellement"

### Expected behavior

L'application devrait s'ouvrir normalement 

### Actual behavior

L'application ne s'ouvre pas et plante continuellement et pourtant j'ai un Google pixel 8
![Screenshot_20240720-204848](https://github.com/user-attachments/assets/7fe196cb-6a33-4639-a45d-cd399555959e)

### RiMusic version

0.6.43

### Android version

Android 14

**Comment by fast4x** [comment]
Click on details, copy log and past here please
