### ISSUE TITLE
Static "downloading" bar 

### ISSUE THREAD

**Issue by Jeanhzo** [fast4x/RiMusic#2841]
### Steps to reproduce the bug

The download progress bar does not advance, it remains static

### Expected behavior

The bar advances and disappears when finished

### Actual behavior

Okay

### Screenshots/Screen recordings

![Screenshot_2024-07-20-20-01-21-889_it fast4x rimusic](https://github.com/user-attachments/assets/a221e970-854f-4d43-abca-8933fa3022b4)

### RiMusic version

0.6.44

### Android version

12

**Comment by fast4x** [comment]
Song with long duration will download slowly
