### ISSUE TITLE
Discover button strange behavior

### ISSUE THREAD

**Issue by KOLIWAN** [fast4x/RiMusic#2843]
### Steps to reproduce the bug

1) There is no way to disable new Discover button, option in settings duplicates the button in the player, i.e. turns Discover off and on, it is expected that turning Discover on/off in settings will show/hide the button in the player

Discover turned on in settings:
![Screenshot_20240721_112842](https://github.com/user-attachments/assets/6f34623c-858d-4bf1-a5bc-2f44cdfbcb70)

Discover enables in player:
![Screenshot_20240721_112846](https://github.com/user-attachments/assets/e711423a-6a03-4b1d-b3cb-517e8207aafa)

Discover turned off in settings:
![Screenshot_20240721_112828](https://github.com/user-attachments/assets/d4274673-3a45-4f6e-a288-9fd3eb2549a2)

Discover disables in player:
![Screenshot_20240721_112834](https://github.com/user-attachments/assets/d7da24bc-c321-4248-88e0-fe3473cc99d3)

2) Also, if you press the Discover button in the player, it clears the queue, removing your favorite tracks and tracks from playlists. However, if you turn off Discover, the previous playlist is not restored. I don't know if this is intended or not, but it looks inconvenient

### Expected behavior

Expected to have an option to disable Discover button

Expected to restore queue after disabling Discover in Player

### Actual behavior

Discover feature isn't finished 

### RiMusic version

0.6.44

### Android version

Android 13

**Comment by fast4x** [comment]
In new version 0.6.44 will be an option to disable from action bar

**Comment by KOLIWAN** [comment]
> In new version 0.6.44 will be an option to disable from action bar

0.6.45 I suppose.. :)

**Comment by fast4x** [comment]
Ooohhh yes sorry 😂😂

**Comment by fast4x** [comment]
Now can download custom version 
https://github.com/fast4x/RiMusic/tree/master/customVersion
