### ISSUE TITLE
Playlist reorder feature not available

### ISSUE THREAD

**Issue by saumayrustagi** [fast4x/RiMusic#2844]
### Steps to reproduce the bug

Create any playlist  
I have created a playlist from album  
and I have imported my ViMusic Playlist

### Expected behavior

The songs in the playlist should show 2 horizontal bars above/below the download icon

### Actual behavior

No such bars are displayed

### Screenshots/Screen recordings

![Screenshot_2024-07-21_10-05-51](https://github.com/user-attachments/assets/c3707b60-c23a-456e-864d-27278ed7fb54)

### RiMusic version

0.6.44

### Android version

Android 11

**Comment by fast4x** [comment]
Just fixed, available from version 0.6.45

**Comment by aneesh1122** [comment]
> Just fixed, available from version 0.6.45

What was the issue? Was it because of playlist indicator?

**Comment by fast4x** [comment]
SwipeToDismissBox inside SwipeableContent have created issue.

**Comment by aneesh1122** [comment]
> SwipeToDismissBox inside SwipeableContent have created issue.

Okay

**Comment by fast4x** [comment]
Now can download custom version 
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by saumayrustagi** [comment]
> Now can download custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

I did try the customVersion apk and it seems the issue remains unfixed.

![Screenshot_2024-07-22_13-19-53](https://github.com/user-attachments/assets/d3cc3068-5f0a-48f4-afb5-392367749ae9)

Could you also test from your side?

**Comment by saumayrustagi** [comment]
Ok, then just a heads up that this feature works in the current 0.6.43 release on F-Droid.

![Screenshot_2024-07-22_13-51-22](https://github.com/user-attachments/assets/5bf16ab3-5204-4af7-bf64-2531826df69b)


I am closing this issue. But please document this ascending position information.

**Comment by fast4x** [comment]
Yes bug it's related 0.6.44 abd fixed in 0.6.45

Now to create a document for RiMusic it's much complex, it require much time. 

In the future will be created.
