### ISSUE TITLE
Alternative albums and album/song information not showing up after the latest update.

### ISSUE THREAD

**Issue by anoojjo** [fast4x/RiMusic#2846]
### Steps to reproduce the bug

1.Scroll down to any album

### Expected behavior

Alternative version and album information should show up

### Actual behavior

Now it just seems to be loading endlessly

### Screenshots/Screen recordings

![Screenshot_20240721_131128](https://github.com/user-attachments/assets/397dfb32-69c3-4c3a-a9d0-70f8b00346e7)

### RiMusic version

0.6.44

### Android version

Android 14

**Comment by fast4x** [comment]
Fixed, available from version 0.6.45

**Comment by fast4x** [comment]
Now can download custom version 
https://github.com/fast4x/RiMusic/tree/master/customVersion
