### ISSUE TITLE
piped sync broken

### ISSUE THREAD

**Issue by rsssxd** [fast4x/RiMusic#2848]
### Steps to reproduce the bug

Log in to your piped account from settings

### Expected behavior

rimusic application pulls search results and music from piped.

### Actual behavior

rimusic still pulls search results and music from YouTube music.

### RiMusic version

0.6.44

### Android version

Android 14

**Comment by fast4x** [comment]
Piped is used to sync playlists to or from piped instance, the results search are always from YouTube music.
