### ISSUE TITLE
Personal Order in playlist 

### ISSUE THREAD

**Issue by nomenamecom** [fast4x/RiMusic#2849]
### Description

Hi!!

I would like to order the songs in the different playlist as I like and be able to change when I like. Changing the first for the fitfh, for example 

Many thanks!

### Suggested Solution

Be able to change the order moving to the final position or setting the final number

**Comment by fast4x** [comment]
You can order now by set ascended mode and position method, like this
![Screenshot_2024-07-21-16-19-18-495_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/f2bda95f-2dd3-4bdd-ad02-d51a5da93785)

**Comment by nomenamecom** [comment]
I can order by differents concepts. But I would like to move songs and set the order that I want. In your case, I would like to move the song "BAILAR CONTIGO" to the position of the song "Pepas". And the song "Pepas" to the end. Is that possible?
Many thanks

**Comment by fast4x** [comment]
Yes, tap and hold on first song, move in the new position. Same operation for others...

**Comment by nomenamecom** [comment]
I tried, but if I tap and hold I see a new menu but I can't move the song 
I attached the version I have 
Maybe depends on the version of Android? I have MIUI 14 based on Android 12. 

Thanks!

![Screenshot_2024-07-21-17-24-29-406_it fast4x rimusic](https://github.com/user-attachments/assets/d1ab02bb-9458-49a0-be6e-3eb915cf75ae)
![Screenshot_2024-07-21-17-24-22-744_it fast4x rimusic](https://github.com/user-attachments/assets/87608fcd-4a21-4204-9106-3659c8c3dcfe)

**Comment by fast4x** [comment]
Sorry, this bug it's Just fixed and will be available in next version, sorry.

**Comment by fast4x** [comment]
Now can download custom version 
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by nomenamecom** [comment]
I don't know what happened but it doesn't run. I tried to uninstall and install, delete and do again. Delete the temp files, reboot....and bad luck. I will try with the next version or after trying more options :)
