### ISSUE TITLE
Alternative albums no longer appear

### ISSUE THREAD

**Issue by Kaynem706** [fast4x/RiMusic#2850]
### Steps to reproduce the bug

Just go to any album that has an alternative album and you will see that the alternative album wont show ,i saw it on more life album by drake

### Expected behavior

The albums should show alternative album 

### Actual behavior

The albums alternative doesn't show

### RiMusic version

0.6.44

### Android version

Android 14

**Comment by fast4x** [comment]
Fixed, available from version 0.6.45

**Comment by fast4x** [comment]
Now can download custom version 
https://github.com/fast4x/RiMusic/tree/master/customVersion
