### ISSUE TITLE
Se cierra al poner las letras 

### ISSUE THREAD

**Issue by Victor332lop** [fast4x/RiMusic#2851]
### Steps to reproduce the bug

Use las letras y se cierra solo

### Expected behavior

Deberia dsr las letras normalmente

### Actual behavior

Se crashea la app y se cierra despues de 3 musicas

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/d612f5ac-e31c-4203-ac87-aeaad4eaff57

### RiMusic version

0.6.44

### Android version

Android 8.1 oreo

**Comment by fast4x** [comment]
Enable log debug in miscellaneous settings, after crash copy and paste here crash log please

**Comment by andercard0** [comment]
Hi, here it is the log after crash

2024-07-21T11:44:16.501:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 A5.a.u(SourceFile:38) 
	 i7.a.n(SourceFile:9) 
	 A7.L.run(SourceFile:113) 
	 A7.z0.run(SourceFile:195) 
	 H7.k.run(SourceFile:3) 
	 H7.a.run(SourceFile:96)

**Comment by fast4x** [comment]
Good, now can disable, I'll try to fix
