### ISSUE TITLE
歌曲缓冲报错

### ISSUE THREAD

**Issue by berrychiao** [fast4x/RiMusic#2852]
### Steps to reproduce the bug

当网络延迟较高时，点击播放某首歌会报错，内容是未知错误。但是，当我点击播放并马上点击暂停时，等待缓冲几秒，就能够正常播放了。

### Expected behavior

当网络延迟较高时，点击播放某首歌会报错，内容是未知错误。但是，当我点击播放并马上点击暂停时，等待缓冲几秒，就能够正常播放了。

### Actual behavior

当网络延迟较高时，点击播放某首歌会报错，内容是未知错误。但是，当我点击播放并马上点击暂停时，等待缓冲几秒，就能够正常播放了。

### RiMusic version

0.6.44

### Android version

ad 12

**Comment by fast4x** [comment]
Ok I'll try to increase timeout

**Comment by fast4x** [comment]
Improved, available from version 0.6.45
