### ISSUE TITLE
Some settings reset after EVERY update

### ISSUE THREAD

**Issue by Uneccessary** [fast4x/RiMusic#2858]
### Steps to reproduce the bug

1. Update the app
2. Check your configured settings

### Expected behavior

Settings should be properly migrated into the new version of RiMusic without modifying the user preferences.

### Actual behavior

With every update some settings are reseted to their default values

### RiMusic version

0.6.44

### Android version

Android 12, Android 14

**Comment by fast4x** [comment]
Which one?

**Comment by Uneccessary** [comment]
It differs with each and every update, but this time it was the background of the player and open the player in minimized view, there was also a third setting which reseted but I forgot abt it.

I'm using ViMusic Mode, this might be related.

**Comment by fast4x** [comment]
In this case it's normal because i've changed any settings...

**Comment by Uneccessary** [comment]
Sorry, wdym by "In this case it's normal because i've changed any settings..."? Do you mean you change the default settings for ViMusic mode which will overwrite users-preferences?

**Comment by fast4x** [comment]
Maybe by changing the default it will be reset, I’ll try to understand better.

**Comment by Uneccessary** [comment]
Ah, minimized view for lyrics also changed to "disabled" after the recent updated.
