### ISSUE TITLE
Recently listened Sorting

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#286]
### Description

It would be cool a new sorting option that sorts by what you listened. This will help peoples to relisten a song even after they forgot the name but remember that they listened recently in the playlist

### Suggested Solution

Add an recently listened sorting that shows the songs by the order you listened them

### Additional Context

The last listened song from the Playlist is the first

**Comment by fast4x** [comment]
But in Playlist or Home songs?

**Comment by OrangeZXZ** [comment]
> But in Playlist or Home songs?

both would be cool but I was talking obout the playlists

**Comment by fast4x** [comment]
Perfect, thanks for details

**Comment by DeadSecTr** [comment]
Please add a Playlist sort function like Newest/Oldest so that the newly added songs are automaticly on the top/botton in the list.

Thx for the great app

**Comment by fast4x** [comment]
Implemented Sorting by position (most recent = highest position)
Available from version 0.6.18

Now, I’m going to insert the order according to the last heard...

**Comment by fast4x** [comment]
Implemented sorting option by listened
Available from version 0.6.18
![Screenshot_20240118_221532](https://github.com/fast4x/RiMusic/assets/1484476/432d72f7-0275-43cd-96ef-e225e44b30c3)

**Comment by OrangeZXZ** [comment]
> ![Screenshot_20240118_221532](https://github.com/fast4x/RiMusic/assets/1484476/432d72f7-0275-43cd-96ef-e225e44b30c3)
> 

The UI looks sick! (a bit messy right now but it's ok)

**Comment by fast4x** [comment]
Yes, however live makes better, for the moment it’s okay.
