### ISSUE TITLE
[Feature]: Increase Volume by Swiping on thumbnail

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [fast4x/RiMusic#2863]
### Description

By swiping up and down on the right side of thumbnail we can change the volume levels(of the device) and how about by swiping on the upper left side of the thumbnail hmm.. We can like a song and swiping on the down side of left thumbnail we can download it?. 

### Suggested Solution

-

### Alternatives

Alternative can be shifting the thumbnail below the notch removing the arrow and ri music logo(add it anywhere) on the music player screen and adding a volume slider below because the current one is hidden behind play button not too convenient. 

### Additional Context

I have experienced some visual glitches too will report them one by one. New update also added a player slider animation not a big fan of it though kinda distracts me

**Comment by fast4x** [comment]
Much complicated and not for all users

**Comment by ALMIGHTY-VC** [comment]
> Much complicated and not for all users

Oh 👌 feel free to mark it as not planned
