### ISSUE TITLE
Not possible to play lists

### ISSUE THREAD

**Issue by edumdq82** [fast4x/RiMusic#2865]
### Steps to reproduce the bug

Create a Playlist 
Try to play it

### Expected behavior

All the songs in the playlist should be played and a button should be shown in order to do it.

### Actual behavior

No button appears and if you press any song in the playlist to start, it's only this song played.

### Screenshots/Screen recordings

![Screenshot_2024-07-22-07-31-57-74_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/b98271f9-ae66-4d98-b96e-1c5dec16f747)

### RiMusic version

0.6.44 by fast4x

### Android version

14

**Comment by fast4x** [comment]
All songs or up to the set limit, are added to the queue, you do not need a button.

**Comment by edumdq82** [comment]
https://github.com/user-attachments/assets/f662c61d-29ef-4401-80cd-2852a462575e

**Comment by fast4x** [comment]
Try changing maximum number of songs in queue from UI settings

**Comment by edumdq82** [comment]
This option is set to 500 by default.
Yahoo Mail: Busca, organiza, conquista 
 
  El lun, jul 22, 2024 a 19:38, Rino ***@***.***> escribió:   


Try changing maximum number of songs in queue from UI settings

**Comment by fast4x** [comment]
Try to change with other options...

**Comment by edumdq82** [comment]
It is set to 500

![Screenshot_2024-07-22-20-23-01-63_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/fc28314d-7d4f-4b06-961e-f856c94a161a)

**Comment by fast4x** [comment]
decrease, restart and try play song
