### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by Fxrrcrxdsccexxe** [fast4x/RiMusic#2866]
Hello, 
How to restore inner tune data in Ri music

_Originally posted by @Fxrrcrxdsccexxe in https://github.com/fast4x/RiMusic/issues/1971#issuecomment-2242140094_

**Comment by fast4x** [comment]
I'm working on a project that will permit it, wait.
When will be available 
https://github.com/fast4x/InnerTune2RiMusic

**Comment by Fxrrcrxdsccexxe** [comment]
How to download song on local phone storage

**Comment by fast4x** [comment]
Isn't possible
