### ISSUE TITLE
Translation lyrics ask me target language everytime

### ISSUE THREAD

**Issue by Kurrode** [fast4x/RiMusic#2869]
### Steps to reproduce the bug

1) Open any song
2) Press the translate button and choose a language 
3) Press the button again, multiple times 

### Expected behavior

You press the translate button and you only choose the preferred target language once.

### Actual behavior

Everytime I hit the button, a screen to choose the target language appears.

This is annoying since I use this feature for language learning and I have to translate back and forth.

### RiMusic version

0.6.44

### Android version

14

**Comment by fast4x** [comment]
yes and you can click in default...

**Comment by Kurrode** [comment]
> In previous version lyrics translation in multi language isn't available 

So there's no way I can avoid choosing the target language everytime?

**Comment by twistios** [comment]
It looks like it stays in prefered language as long as lyrics is not disabled. Then when it is disabled, it is in prefered language again by selecting the language again.

**Comment by Kurrode** [comment]
@fast4x I really need to be able to tap back and forth between original and translation. 

There could be an option to change translation target language by holding the translation button.
