### ISSUE TITLE
[Feature]: use (musixmatch free) or YT transcript for lyrics

### ISSUE THREAD

**Issue by Atharv-Pathak-14** [fast4x/RiMusic#287]
### Description

As the title says..... Kugou don't have lyrics for all songs (limited) and sometimes gives wrong lyrics

### Suggested Solution

Use something like musixmatch or yt transcript like simple music use 
This one :- https://github.com/maxrave-dev/SimpMusic
If possible

**Comment by fast4x** [comment]
Hi, thanks for your suggestion.

**Comment by fast4x** [comment]
Musixmatch is a paid service that offers a free but very limited option, about 2000 texts in one day.

**Comment by Atharv-Pathak-14** [comment]
> Musixmatch is a paid service that offers a free but very limited option, about 2000 texts in one day.

Yea I know that but the app i mentioned also has a option to sync lyrics from YouTube transcript also I don't think the developer pay for the musixmatch as many users use that app

**Comment by fast4x** [comment]
Okay, I wanted to tell you what the restriction is on that service.

**Comment by Atharv-Pathak-14** [comment]
> Okay, I wanted to tell you what the restriction is on that service.

Ok 👌

**Comment by KGriss** [comment]
It could be much better to get synchronized lyrics for a lot more songs using alternative sources (maybe putting a switch in settings to chose which source to use between Musixmatch, YT or Kugou?)

**Comment by fast4x** [comment]
Implemented, added new provider lyrics LrcLib.net.
Available from version 0.6.28.1
