### ISSUE TITLE
Remove favorites and playlist from queue button is missing the option to be removed

### ISSUE THREAD

**Issue by Kurrode** [fast4x/RiMusic#2871]
### Steps to reproduce the bug

.

### Expected behavior

I should be able to remove the star button from the bar

### Actual behavior

.

### Screenshots/Screen recordings

This is the button I'm talking about:

![Screenshot_2024-07-22-14-28-36-396_it fast4x rimusic_1_1](https://github.com/user-attachments/assets/598d15fa-3e97-4a29-930c-3e448e239c1c)

All the other buttons have the option to be turned off:

![Screenshot_2024-07-22-14-31-21-355_it fast4x rimusic_1](https://github.com/user-attachments/assets/55a1163a-471f-4390-a0ca-dcb06a3e9718)

### RiMusic version

0.6.44

### Android version

14

**Comment by fast4x** [comment]
Download custom version please, it's just implemented

**Comment by Kurrode** [comment]
> Download custom version please, it's just implemented 

What custom version?

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion
