### ISSUE TITLE
Disabling the star icon doesn't put removed songs back in the playlist

### ISSUE THREAD

**Issue by Kurrode** [fast4x/RiMusic#2872]
### Steps to reproduce the bug

Open any album where you have a favorite song and play any song.

### Expected behavior

When toggling the button off, the favorite songs should be back in the queue.

### Actual behavior

When toggling the button off, the favorite songs should aren't back in the queue.

### Screenshots/Screen recordings

![Screenshot_2024-07-22-14-28-36-396_it fast4x rimusic_1_1](https://github.com/user-attachments/assets/20a253e9-98f1-48ee-b556-4bfd91777e24)

### RiMusic version

0.6.44

### Android version

14

**Comment by fast4x** [comment]
It put from forward songs...

**Comment by aneesh1122** [comment]
It doesn't hide them. It removes them
