### ISSUE TITLE
not a single song in the app is working! SEND HELP

### ISSUE THREAD

**Issue by flxblkct** [fast4x/RiMusic#2874]
### Steps to reproduce the bug

go to any song, any album, any playlist
click the play button
song won't play and the timeline keeps buffering
songs can't be downloaded either
the below message appears on screen when I click on next song 

### Expected behavior

songs should play normally

### Actual behavior

timeline buffering 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/3fc6ac2a-9128-4be4-9dcf-54dbbbce23a3

![Screenshot_20240722_154328](https://github.com/user-attachments/assets/abee09ba-13e2-4836-82b8-a1907553b3f0)

### RiMusic version

0.6.44

### Android version

Android 14

### Additional information

this is funny because the latest version fixed the ONLY issue I had (dynamic theme) and yet I can't play anything now 😭😂

note: I use VPN with the app cause YT Music is blocked where I live

**Comment by fast4x** [comment]
Anything changes have been added, it's same like before. 
Use a proxy instead a vpn

**Comment by flxblkct** [comment]
I enabled a proxy from miscellaneous tab and it didn't work, when I launch the app I see the screenshot below

![Screenshot_20240722_214130](https://github.com/user-attachments/assets/344e636d-6e41-49ad-b7d3-45539b071efc)


disabling monthly playlist creation from UI tab didn't work either

changing the DNS also didn't work

I went back to using VPN but this time I changed the region and it worked for specific countries (it's a bit buggy but the songs are playable now)

the previous versions worked well with VPN turned on from ANY location so I don't know why my VPN is acting up with this latest version of RiMusic
