### ISSUE TITLE
Error when adding multiple songs to playlist

### ISSUE THREAD

**Issue by gutierrezja** [fast4x/RiMusic#2875]
### Steps to reproduce the bug

1. We go to the songs screen and/or some playlists.
2. Click on three points to access the menu, click on selection or Deselect to enable check boxes.
3. Add selected songs to a playlist (Error does nothing, and does not add the songs)
4. The only way to do it is to add songs one by one, Opening the song menu.

### Expected behavior

Add checkbox selected songs to song list

### Actual behavior

The app darkens the screen and freezes.

### Screenshots/Screen recordings

https://mega.nz/file/KtZh3J4Q#oroxzUrrquWYAJcPLGqIHkh4-6IR8zV-4NQrGP4yDmc

### RiMusic version

0.6.44

### Android version

Android 13

**Comment by fast4x** [comment]
Download custom version, it's fixed
