### ISSUE TITLE
[Feature]: Widget

### ISSUE THREAD

**Issue by Tanujairam-TG** [fast4x/RiMusic#288]
### Description

I request you to add widget feature for easy access to music in home screen.  

### Suggested Solution

Program a feature to add widget

**Comment by Tanujairam-TG** [comment]
![IMG_20231229_182754](https://github.com/fast4x/RiMusic/assets/88611197/edf8ed8f-cc94-437e-98e6-45b6f384996d)
I am expecting like this sir.

**Comment by OrangeZXZ** [comment]
quick widget idea

![image](https://github.com/fast4x/RiMusic/assets/104271365/f3da2fe7-8506-4422-bb5e-7a93a510d9f3)

**Comment by senolfndk** [comment]
![Ekran görüntüsü 2024-04-07 221640](https://github.com/fast4x/RiMusic/assets/52818836/c9452c0c-e508-4b73-aed8-17b01243f44d)

**Comment by Tre916** [comment]
Favorite button is a must! All of these mock-ups look great!
