### ISSUE TITLE
[Feature]: Fade option play/pause

### ISSUE THREAD

**Issue by lebgdeyoutube** [fast4x/RiMusic#2881]
### Description

Add a fade option when the music starts or stops. Being able to select the fade time in milliseconds
(If it helps, this option is available in the open source "metro" application which I told you about for the crossfade)
![Screenshot_2024-07-23-00-39-34-235_io github muntashirakon Music-edit](https://github.com/user-attachments/assets/3c13c66a-9f7c-4ff1-95e5-e790b08a64ed)

### Suggested Solution

add a cursor

**Comment by JeePopuwu** [comment]
I need!!
![357c3db9659f9649f959915bfce6dab3](https://github.com/user-attachments/assets/f7b71651-6387-4bae-88c7-d9b504a5ef7b)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.45

**Comment by JeePopuwu** [comment]
> Implementado, disponible a partir de la versión 0.6.45

THANKS FAAAASSTTTT
