### ISSUE TITLE
[Feature]: Automatic pause/play when sound is at 0

### ISSUE THREAD

**Issue by lebgdeyoutube** [fast4x/RiMusic#2882]
### Description

Add an option to pause music when sound is 0, and restart music when sound is on 
(If it helps, this option is available in the open source "metro" application which I told you about for the crossfade)
![Screenshot_2024-07-23-00-46-21-318_io github muntashirakon Music-edit](https://github.com/user-attachments/assets/145bd6f4-4503-4db7-ab98-7c4cf6cfd39a)

### Suggested Solution

add an option

**Comment by MrAshish74** [comment]
> ### Description
> Add an option to pause music when sound is 0, and restart music when sound is on (If it helps, this option is available in the open source "metro" application which I told you about for the crossfade) ![Screenshot_2024-07-23-00-46-21-318_io github muntashirakon Music-edit](https://private-user-images.githubusercontent.com/55501633/351132600-145bd6f4-4503-4db7-ab98-7c4cf6cfd39a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMzcwNDYsIm5iZiI6MTcyMjEzNjc0NiwicGF0aCI6Ii81NTUwMTYzMy8zNTExMzI2MDAtMTQ1YmQ2ZjQtNDUwMy00ZGI3LWFiOTgtN2M0Y2Y2Y2ZkMzlhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDAzMTkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3N2EzNjU5ZTA5OTdkOGQzYWUyZTBkZmMyMDI2OTM4MTkxYTQxYWE2ZGYwYTE3OWM0ZTc3MjIyYTAxZmQyMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dGv3drivXiX01FUqzNsZ-zra4BAFvMVodHiQXsDDRw4)
> 
> ### Suggested Solution
> add an option
> 
> ### Alternatives
> _No response_
> 
> ### Additional Context
> _No response_

It's Not Working With Me and
Other things Are Happening after this 
Like If I Down Volume App Closes Itself, 
When I Press Device Volume Up Button Volume Goes Down Not Up.

**Comment by SacredGenius07** [comment]
> > ### Description
> > Add an option to pause music when sound is 0, and restart music when sound is on (If it helps, this option is available in the open source "metro" application which I told you about for the crossfade) ![Screenshot_2024-07-23-00-46-21-318_io github muntashirakon Music-edit](https://private-user-images.githubusercontent.com/55501633/351132600-145bd6f4-4503-4db7-ab98-7c4cf6cfd39a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMzcwNDYsIm5iZiI6MTcyMjEzNjc0NiwicGF0aCI6Ii81NTUwMTYzMy8zNTExMzI2MDAtMTQ1YmQ2ZjQtNDUwMy00ZGI3LWFiOTgtN2M0Y2Y2Y2ZkMzlhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDAzMTkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3N2EzNjU5ZTA5OTdkOGQzYWUyZTBkZmMyMDI2OTM4MTkxYTQxYWE2ZGYwYTE3OWM0ZTc3MjIyYTAxZmQyMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dGv3drivXiX01FUqzNsZ-zra4BAFvMVodHiQXsDDRw4)
> > ### Suggested Solution
> > add an option
> > ### Alternatives
> > _No response_
> > ### Additional Context
> > _No response_
> 
> It's Not Working With Me and Other things Are Happening after this Like If I Down Volume App Closes Itself, When I Press Device Volume Up Button Volume Goes Down Not Up.

Yep same with me, 
how do I turn it off I don't see the option

**Comment by fast4x** [comment]
There isn't a option...
Download latest version, this feature will be developed soon

**Comment by fast4x** [comment]
Implemented, available from version 0.6.46
