### ISSUE TITLE
[Feature]: Search button for all options

### ISSUE THREAD

**Issue by lebgdeyoutube** [fast4x/RiMusic#2884]
### Description

Add the option search button for all categories (currently only the first 2) and be able to search in all the options category rather than just one
![Screenshot_2024-07-23-00-51-15-198_it fast4x rimusic-edit](https://github.com/user-attachments/assets/3f45e161-a9bd-4647-a0c6-517b017985ff)
![Screenshot_2024-07-23-00-50-24-711_it fast4x rimusic-edit](https://github.com/user-attachments/assets/01ee2059-b27b-4e17-b3e5-ee14d85ef6e4)

### Suggested Solution

add a button

**Comment by fast4x** [comment]
Not make sense if there are few options in a page
