### ISSUE TITLE
Method exceeds compiler instruction limit

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#2885]
### Steps to reproduce the bug

1. run app
2. play song (PlayerModern)
3. observe logcat-output

### Expected behavior

No issue with compiler.

### Actual behavior

````
Method exceeds compiler instruction limit: 18380 in void it.fast4x.rimusic.ui.screens.player.PlayerModernKt.PlayerModern(androidx.navigation.NavController, it.fast4x.rimusic.ui.screens.player.PlayerSheetState, androidx.compose.material3.SheetState, androidx.compose.ui.Modifier, androidx.compose.foundation.shape.RoundedCornerShape, kotlin.jvm.functions.Function0, androidx.compose.runtime.Composer, int, int)
````

### RiMusic version

commit 1e0617685d38ad

### Android version

14

### Additional information

This is hard to do in a pull-request of me, as @fast4x and @aneesh1122 are both working on ModernPlayer.
This requires a change of ~1000 lines of code. It is easiest to extract some methods, like I already tried to do in https://github.com/twistios/RiMusic/commit/eb2e9842edfb1d1855d75c1ba2ab7a3028158044 (but then I noticed that there were new PlayerModern-commits).

**Comment by aneesh1122** [comment]
@fast4x the debug app is crashing even if I make minor changes. The signed apk is working perfectly. It's very frustrating because signed apk takes a lot of time to build and it's not easy to implement things in app this way.

Please look into this.

**Comment by fast4x** [comment]
ok, @aneesh1122 Discover feature... must change name... user confusing it with Discovery... new music...

**Comment by aneesh1122** [comment]
> ok, @aneesh1122 Discover feature... must change name... user confusing it with Discovery... new music...

Well, it actually helps in discovering new music so the name is right.

If you make discover work only with radio no one will create new issues.

**Comment by fast4x** [comment]
oooooooooookkk
