### ISSUE TITLE
[Feature]: Replace pop UPs with Android ones ( toasts )

### ISSUE THREAD

**Issue by lebgdeyoutube** [fast4x/RiMusic#2886]
### Description

For a better design and better integration, why not replace the pop UP with that of Android? like that:
![toast](https://github.com/user-attachments/assets/0572b392-7d98-4dad-9dd1-c58d67f61c3a)

### Suggested Solution

For that, I found a link that might who could help
https://developer.android.com/guide/topics/ui/notifiers/toasts?hl=fr

**Comment by fast4x** [comment]
it's much standard....

**Comment by aneesh1122** [comment]
> it's much standard....

The present pop ups look very outdated. It spoils the elegant look of this app.

Popups should be very subtle. It shouldn't disturb the user.

I tried to change the toast but I don't know where you're using resources from. I couldn't even find the drawables you're using for toasts.

**Comment by fast4x** [comment]
Attention, not to use standard toast... another elegant ok

**Comment by aneesh1122** [comment]
> Attention, not to use standard toast... another elegant ok

I can design a toast which is elegant but I'm not able to find resources you've used. I could only reduce the size of texts in toast. Couldn't find a way to change toast size, icon size or position.

**Comment by fast4x** [comment]
Learn about actual component smartToast
https://github.com/vincent-series/smart-show?tab=readme-ov-file

**Comment by ALMIGHTY-VC** [comment]
> > Attention, not to use standard toast... another elegant ok
> 
> I can design a toast which is elegant but I'm not able to find resources you've used. I could only reduce the size of texts in toast. Couldn't find a way to change toast size, icon size or position.

Yes the lyrics not available popup seems a little bit disturbing it can be improved too

**Comment by aneesh1122** [comment]
> > > Attention, not to use standard toast... another elegant ok
> > 
> > I can design a toast which is elegant but I'm not able to find resources you've used. I could only reduce the size of texts in toast. Couldn't find a way to change toast size, icon size or position.
> 
> Yes the lyrics not available popup seems a little bit disturbing it can be improved too

If the icons are removed, the pop up is shifted a little to the bottom, it will look much better

**Comment by fast4x** [comment]
> > > > Attention, not to use standard toast... another elegant ok
> > > 
> > > I can design a toast which is elegant but I'm not able to find resources you've used. I could only reduce the size of texts in toast. Couldn't find a way to change toast size, icon size or position.
> > 
> > Yes the lyrics not available popup seems a little bit disturbing it can be improved too
> 
> If the icons are removed, the pop up is shifted a little to the bottom, it will look much better

can disable from settings

**Comment by aneesh1122** [comment]
> > > > > Attention, not to use standard toast... another elegant ok
> > > > 
> > > > I can design a toast which is elegant but I'm not able to find resources you've used. I could only reduce the size of texts in toast. Couldn't find a way to change toast size, icon size or position.
> > > 
> > > Yes the lyrics not available popup seems a little bit disturbing it can be improved too
> > 
> > If the icons are removed, the pop up is shifted a little to the bottom, it will look much better
> 
> can disable from settings 

You're misunderstanding us man. We want pop ups because it's useful. All we are saying is it can be made to look better.

No offence but the pop ups you've implemented are like those ads you get in your face when you're watching something.

**Comment by fast4x** [comment]
ahahahaahah ok I'll change it

**Comment by ALMIGHTY-VC** [comment]
> ahahahaahah ok I'll change it

Feel free to ask about it to us in discussion

**Comment by fast4x** [comment]
I would to use Snackbar

https://m3.material.io/components/snackbar/overview

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/discussions/2925

**Comment by fast4x** [comment]
Implemented, available from version 0.6.45
