### ISSUE TITLE
Theme bug Material you / pitch black

### ISSUE THREAD

**Issue by lebgdeyoutube** [fast4x/RiMusic#2888]
### Steps to reproduce the bug

When we select the material you theme , then dark in "theme mode", it works but when you update the application, for example by changing the system language or by changing the option "thumbnail size", the theme changes from dark to pitch black, but the option is still on "dark" and not on "pitch black"

1. Go to settings > UI 
2. Theme > Material You
3. Theme mod > Dark
4. App language > ( changes with another language )
5. the theme changes from dark to pitch black 

( this happens with dark or light theme of my phone )

![Screenshot_2024-07-22-23-23-45-161_it fast4x rimusic-edit](https://github.com/user-attachments/assets/94e16ebd-616d-407c-8552-6c6875c8499b)
![Screenshot_2024-07-22-23-24-02-389_it fast4x rimusic-edit](https://github.com/user-attachments/assets/abb895a2-95a9-4de8-a8ab-deb4665a6fda)
![Screenshot_2024-07-22-23-25-40-265_it fast4x rimusic-edit](https://github.com/user-attachments/assets/0a17ec69-7a1d-4a34-b3c5-52b58bd74614)

### Expected behavior

should not change the theme 

### Actual behavior

change the theme to pitch black

### RiMusic version

0.6.44

### Android version

Android 14

**Comment by privacyfreak84** [comment]
This issue will probably never be addressed. I've been complaining about it for months, and every issue has gone seemingly ignored

**Comment by fast4x** [comment]
Improved available from version 0.6.60
