### ISSUE TITLE
i cant move song in the playlist

### ISSUE THREAD

**Issue by pokeshadow89** [fast4x/RiMusic#2890]
### Steps to reproduce the bug

1 go to any playlist
2 tap in a song
3 open de reproducer
4 open de list of playlist
5 try to move any song
6 you cannot move the songs

### Expected behavior

the songs we can move

### Actual behavior

the songs we cannot move when i listen a playlist

### RiMusic version

v0.6.4.4

### Android version

Android 12

**Comment by JeePopuwu** [comment]
try custom version
