### ISSUE TITLE
Se cierra o se quita la cancion

### ISSUE THREAD

**Issue by keoo12** [fast4x/RiMusic#2891]
### Steps to reproduce the bug

pues solo empiezo a escuchar musica y de repente se cierra la aplicacion puede o no cerrarse o cerrarce en 10 min o mas, y otra es que las ultimas cancion que descargo al momento de presionar en la cancion se cierra la app pero con las primeras o las de enmedoo no pasa eso

### Expected behavior

es una hermosa app pero esperaria que no pasaran esos errores como que nunca se me cerrara la app o que si pueda escuchar la musica sin tener que buscarla

### Actual behavior

se cierra la app y no me deja escuchar las ultimas canciones amenos que la busque

### RiMusic version

0.6.35

### Android version

android 14

### Additional information

la mejor app para escuchar musica gratis

**Comment by fast4x** [comment]
Use latest version, your 0.6.35 it's too old

**Comment by keoo12** [comment]
> Utilice la última versión, la 0.6.35 es demasiado antigua

la acabo de actualizar a la 0.6.44 y sigue sin dejarme escuchar las ultimas canciones amenos de que las busque
