### ISSUE TITLE
next music does not work in favorites and download 

### ISSUE THREAD

**Issue by lebgdeyoutube** [fast4x/RiMusic#2892]
### Steps to reproduce the bug

1. Go to favorites or download music 
2. Play any music 
3. Click next 

### Expected behavior

The next music should be played 

### Actual behavior

The next music is not playing 

### Screenshots/Screen recordings

![IMG_20240723_060321](https://github.com/user-attachments/assets/5aa49d5b-b7d2-46de-ba99-ccb44139ab72)
![Screenshot_2024-07-23-06-01-51-075_it fast4x rimusic-edit](https://github.com/user-attachments/assets/59ded9bf-3b20-4f6c-a1e2-c4e8e375735b)

### RiMusic version

0.6.44

### Android version

Android 14

### Additional information

I also tried enabling or disabling the buttons on the screens but it doesn't work.

**Comment by fast4x** [comment]
Screen 2 it's shuffle mode for preferites

**Comment by lebgdeyoutube** [comment]
ok thanks, I just realized that this happens when the option " remove liked and playlist songs from queue" is activated, So perhaps we should make an exception to this option for favorite titles, download categories and playlists? 
![Screenshot_2024-07-23-06-28-09-577_it fast4x rimusic-edit](https://github.com/user-attachments/assets/16e5fe26-2336-43eb-b4f0-62461fb1a9b6)

**Comment by fast4x** [comment]
Disable it, stop

**Comment by aneesh1122** [comment]
> Disable it, stop

Is it possible to make it work only with radio?

**Comment by aneesh1122** [comment]
> So perhaps we should make an exception to this option for favorite titles, download categories and playlists?

That was the whole point of creating this option. To remove liked and playlist songs. Why should there be an exception?

**Comment by lebgdeyoutube** [comment]
> > So perhaps we should make an exception to this option for favorite titles, download categories and playlists?
> 
> That was the whole point of creating this option. To remove liked and playlist songs. Why should there be an exception?

Because if we launch a playlist, there will only be one music that can be played from all song in the playlist, the same if we want to listen to the music that we have put in favorites. but it doesn't matter because you just have to deactivate the option

**Comment by aneesh1122** [comment]
> > > So perhaps we should make an exception to this option for favorite titles, download categories and playlists?
> > 
> > That was the whole point of creating this option. To remove liked and playlist songs. Why should there be an exception?
> 
> Because if we launch a playlist, there will only be one music that can be played from all song in the playlist, the same if we want to listen to the music that we have put in favorites. but it doesn't matter because you just have to deactivate the option 

Well, when I was creating 'discover' I wanted it to work only with discovery. Right now it works everywhere. Maybe create a feature request to make it work only with radio.
