### ISSUE TITLE
app tries to access sensors (orientation, movement, etc) as soon as I open the app

### ISSUE THREAD

**Issue by imgalaxyhunter** [fast4x/RiMusic#2896]
### Steps to reproduce the bug

install the app on GrapheneOS with "Allow Sensors permission to apps by default" off, open the app

### Expected behavior

I don't think it should ask for sensors?

### Actual behavior

it asks for sensors permission

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/ecc83b06-e5de-4997-95d9-4f1856059eda

### RiMusic version

0.6.41

### Android version

Android 14 GrapheneOS

**Comment by aneesh1122** [comment]
This app also has landscape mode so maybe that's why it's asking for orientation sensor?

**Comment by imgalaxyhunter** [comment]
> This app also has landscape mode so maybe that's why it's asking for orientation sensor?

it will already switch automatically if you have auto-rotate on

**Comment by fast4x** [comment]
Sensor asked is orientation for shake option

**Comment by imgalaxyhunter** [comment]
> Sensor asked is orientation for shake option

thanks

**Comment by fast4x** [comment]
I checked, in fact the sensor was always enabled even if used only with the active option. I fixed it.

**Comment by fast4x** [comment]
Available from version 0.6.45
