### ISSUE TITLE
Song cover Blur issue 

### ISSUE THREAD

**Issue by Its-Tony** [fast4x/RiMusic#2898]
https://github.com/user-attachments/assets/0c8024a3-ed5a-4d9e-9a11-6b01bbddb2c7

### Steps to reproduce the bug

Play any song. If you choose blur for lyrics background, blur is always applied even if you are not in lyrics mode.

### Expected behavior

Song cover image shouldn't be blur while we are not in lyrics mode. It should show song cover without any blur. Blur effect should be applicable only in lyrics.

### Actual behavior

Song cover is always blur if you choose blurring.

### RiMusic version

0.6.44

### Android version

Android 11

### Additional information

@aneesh1122 Sir, please look into this issue.

**Comment by aneesh1122** [comment]
Fix kar diya hu bhai. Agle update m ek option hoga settings Mein "no blur when lyrics is disabled"
