### ISSUE TITLE
[Feature]: Original icon

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#29]
### Description

Wouldn't it be better if the RiMusic app icon was the Play Next Button (https://www.flaticon.com/free-icon/play-next-button_61175), since it resembles the letters RI? Play Button is used by too many apps as their icon.

### Suggested Solution

Then the app icon would be much more original.

**Comment by fast4x** [comment]
Yes, you're right, it could be prettier. Let's try to change it. I'll try to change it in the next version, I'll wait for your feedback later, ok?

**Comment by NEVARLeVrai** [comment]
> Yes, you're right, it could be prettier. Let's try to change it. I'll try to change it in the next version, I'll wait for your feedback later, ok?

https://www.flaticon.com/free-icon/play_748134

This icon better in green also for rimusic

**Comment by ikanakova** [comment]
Tomorrow I will work on another icon idea and send here. Maybe others should join in besides us, and then we'll choose which one we like the most.

**Comment by ikanakova** [comment]
Logo:

<img src="https://github.com/fast4x/RiMusic/assets/38765251/359b8551-b983-469e-81e0-54d811ac5b3f" alt="rimusic_logo" width="500">

Icon:

<img src="https://github.com/fast4x/RiMusic/assets/38765251/b1cb511f-e62a-48cd-8d7d-c2fd2aaaf4d9" alt="rimusic_icon" width="150">

**Comment by NEVARLeVrai** [comment]
> Logo:
> 
> <img src="https://github.com/fast4x/RiMusic/assets/38765251/359b8551-b983-469e-81e0-54d811ac5b3f" alt="rimusic_logo" width="500">
> 
> Icon:
> 
> <img src="https://github.com/fast4x/RiMusic/assets/38765251/b1cb511f-e62a-48cd-8d7d-c2fd2aaaf4d9" alt="rimusic_icon" width="150">
> 
> 
> 

Center the text pls

**Comment by ikanakova** [comment]
> Center the text pls

like this?

<img alt="rimusic_logo2" width="500" src="https://github.com/fast4x/RiMusic/assets/38765251/3969244f-06d4-4307-b76e-c913e50a321a">

**Comment by NEVARLeVrai** [comment]
> > Center the text pls
> 
> like this?
> 
> <img alt="rimusic_logo2" width="500" src="https://github.com/fast4x/RiMusic/assets/38765251/3969244f-06d4-4307-b76e-c913e50a321a">
> 

Yeahh separates the text from the logo a little, it's too close

**Comment by NEVARLeVrai** [comment]
> > Center the text pls
> 
> like this?
> 
> <img alt="rimusic_logo2" width="500" src="https://github.com/fast4x/RiMusic/assets/38765251/3969244f-06d4-4307-b76e-c913e50a321a">
> 

Yeahh separates the text from the logo a little, it's too close

**Comment by ikanakova** [comment]
> Yeahh separates the text from the logo a little, it's too close

Done + changed proprietary font Calibri to open source font Open Sans:

<img alt="rimusic_logo-v3" width="500" src="https://github.com/fast4x/RiMusic/assets/38765251/ab6ea21e-3a25-4f2f-ba3f-af17fe547679">

**Comment by ikanakova** [comment]
> changed proprietary font Calibri to open source font Open Sans

But I'll probably still be looking for a more rounded one.

**Comment by NEVARLeVrai** [comment]
Look clean u can use Segoe UI? From win11

**Comment by NEVARLeVrai** [comment]
And use Segoe UI

**Comment by fast4x** [comment]
Try this alternative font https://similarfont.io/2-google-fonts-similar-to-segoe-ui

**Comment by ikanakova** [comment]
I'll look at Noto Sans and I quite like this: https://fonts.google.com/specimen/Varela+Round

**Comment by fast4x** [comment]
> I'll look at Noto Sans and I quite like this: https://fonts.google.com/specimen/Varela+Round

I like

**Comment by NEVARLeVrai** [comment]
Yep look good

________________________________

**Comment by ikanakova** [comment]
Varela Round:

<img src="https://github.com/fast4x/RiMusic/assets/38765251/6aea4791-cc34-4c6c-858b-ed94dca3c59b" alt="rimusic_logo-v41" width="500">

Noto Sans:

<img src="https://github.com/fast4x/RiMusic/assets/38765251/35ac9ed9-f258-4ad6-9c49-98f6e182aec1" alt="rimusic_logo-v42" width="500">

**Comment by fast4x** [comment]
Not bad, move the text a bit to the left and it's ok

**Comment by ikanakova** [comment]
> Not bad, move the text a bit to the left and it's ok

You mean Varela Round or Noto Sans version?

**Comment by fast4x** [comment]
For me, ok Noto.

**Comment by ikanakova** [comment]
Maybe the fonts in svg are showing badly, I'd better send a png tonight.

**Comment by fast4x** [comment]
Ops! You are right! 
Varela font is better.
Excuse me, can you change, please?

**Comment by fast4x** [comment]
Wow! Non vedo l'ora di provarlo!

**Comment by ikanakova** [comment]
> Wow! Tonight i try it

Great 😊

**Comment by fast4x** [comment]
![Screenshot_20231024_225918](https://github.com/fast4x/RiMusic/assets/1484476/a8b19364-540c-4b2d-9a51-5cdd679f9c65)

Splashscreen with new icon

**Comment by dainvincible1** [comment]
> ![Screenshot_20231024_225918](https://user-images.githubusercontent.com/1484476/277803841-a8b19364-540c-4b2d-9a51-5cdd679f9c65.png)
> 
> Splashscreen with new icon

looks great

**Comment by fast4x** [comment]
Added, available from next version.
Updated project homepage

**Comment by fast4x** [comment]
> PNG:
> <img src="https://github.com/fast4x/RiMusic/assets/38765251/4dca9b81-c609-42ca-9678-af976b07de12" alt="rimusic_logo-v5" width="500">
> 
> [SVG](https://github.com/fast4x/RiMusic/assets/38765251/d457bab9-e420-4967-9fb6-e6224007883a)
> 

Do you feel like creating an icon with the logo above and the RiMusic text below as wide as the logo above?

I would like to insert it in the splashscreen.
