### ISSUE TITLE
[Feature]: Pause listen History

### ISSUE THREAD

**Issue by NeeRaj-2401** [fast4x/RiMusic#290]
### Description

for some people(like me) who don't like to store any kind of history, Just like pause/clear Search history, 

### Suggested Solution

an option to pause/clear all played songs.

**Comment by fast4x** [comment]
Hi, you can disabile by settings -> Other tab

**Comment by NeeRaj-2401** [comment]
Yeah that only pause/clear search history,  i am talking about the history of songs which we listen to, 
the list which comes when we go on "songs" tab, can we have option to dissable that

**Comment by fast4x** [comment]
Of course, please open a feature request. Thanks for the suggestion.

**Comment by fast4x** [comment]
Sorry the feature request is this!
 Lol 🤣

**Comment by fast4x** [comment]
Implemented, available from version 0.6.47
