### ISSUE TITLE
hola quisiera pedir ayuda con un problema en la aplicación 

### ISSUE THREAD

**Issue by chequegod** [fast4x/RiMusic#2900]
### Steps to reproduce the bug

lo que pasa es que la aplicación se cierra de forma inesperada asi nada mas

### Expected behavior

no se por que se cierra asi de la nada 

### Actual behavior

estoy escuchando musica y de pronto se cierra

### RiMusic version

0.6.42

### Android version

13

**Comment by fast4x** [comment]
Add details please too generic ticket
