### ISSUE TITLE
Dejo de funcionar en estos días RiMusic no permite escuchar las canciones 

### ISSUE THREAD

**Issue by SpaceXAlndro** [fast4x/RiMusic#2901]
### Steps to reproduce the bug

1.Abrir la app
2.Reproducir una canción 
3.Salio el error 

### Expected behavior

Eh debería poder reproducir las canciones y no lo hace

### Actual behavior

Solo se queda estático y no deja reproducir ,Me saca de la app
![Screenshot_2024-07-23-14-29-36-248_it fast4x rimusic](https://github.com/user-attachments/assets/adf428ca-63bc-465c-a35b-f7c4ae6dc922)

### Screenshots/Screen recordings

![Screenshot_2024-07-23-14-20-54-644_it fast4x rimusic](https://github.com/user-attachments/assets/13867118-1ffc-428b-9d7d-0aaef8dec98f)

### RiMusic version

0.6.4

### Android version

Android 13

### Additional information

Por favor pido alguna solución útilizo mucho esta app gracias me gustaría que solucionaran no se que hacer

**Comment by fast4x** [comment]
Improved, it depend from your location
Available from version 0.6.45
