### ISSUE TITLE
The app closes by itself

### ISSUE THREAD

**Issue by Iralybb** [fast4x/RiMusic#2902]
### Steps to reproduce the bug

1-open the app
2- Listen to music
3- the app just closes

### Expected behavior

The app should be able to stay open playing music without closing, whether it is open or in the background

### Actual behavior

Regardless of whether I have the app open in the foreground or background, after a while listening to music it closes unexpectedly

### RiMusic version

0.6.44

### Android version

Android 11

**Comment by fast4x** [comment]
Enable debug in miscellaneous settings, after crash copy and paste here crash log
