### ISSUE TITLE
No me deja escuchar algunas canciones directamente

### ISSUE THREAD

**Issue by keoo12** [fast4x/RiMusic#2907]
### Steps to reproduce the bug

primero ve voy a "descargado" y hasta cierta musica para abajo cada que pulso para reproducirla me cierra la app pero si presiono para reproducir una cancion antes de cierta cancion si me deja sin problemas

### Expected behavior

esperaria que no se me cerrara la app cada que quiero

### Actual behavior

se me cierra y para escuchar la musica debo de buscarla 

### RiMusic version

0.6.44

### Android version

android 14

### Additional information

mas bien es una pregunta, en el apartado de "todo" no me aparecen todas las canciones que salen en "descargado", porque?

**Comment by fast4x** [comment]
Enable debug in miscellaneous settings and paste here log after crash, please.
