### ISSUE TITLE
Crash on loading imported playlist 

### ISSUE THREAD

**Issue by i186e** [fast4x/RiMusic#291]
### Steps to reproduce the bug

1) Import playlist using share > Rimusic
2) Save as local playlist
3) Return to load local playlist
4) App crash

### Expected behavior

Meant to load the playlist

### Actual behavior

Crashes on clicking on the playlist logo

### RiMusic version

Latest

### Android version

Android 14 QPR1

### Additional information

Might be due to the size of the playlist - has 1000+ songs.

**Comment by fast4x** [comment]
Yeah, it could be the playlist, can you give me the playlist link?

**Comment by DeadSecTr** [comment]
Same for me.

Crashes at any createt Playlist by click on it

Also the Region changer (World Button on the top right) doesnt work...it does nothing

**Comment by i186e** [comment]
https://music.youtube.com/playlist?list=PLYM4lGRtjAtc_XpD9hqt2j57kqTvXKEmk&si=XsuoRMRLPpBggo8U

**Comment by i186e** [comment]
Accidental closing, apologies.

**Comment by i186e** [comment]
@fast4x update: I reinstalled version 0.16.4 and tried to load the playlist, it loaded it so ig it's not the playlist, maybe check if anything specific might have changed for the latest version updated hours ago?

Thanks.

**Comment by fast4x** [comment]
Ok thanks for suggestion, I'll check It.

**Comment by DeadSecTr** [comment]
Same with liked songs in lib.

**Comment by shahidshafique** [comment]
Can confirm its happening with liked songs

**Comment by fast4x** [comment]
Please try this https://rimusic.xyz/download/app-release.apk
