### ISSUE TITLE
[Feature]: Disable swipe left to remove from playlist

### ISSUE THREAD

**Issue by antomanc** [fast4x/RiMusic#2910]
### Description

I am trying to find a way to disable the swipe left to remove a song feature, but it seems to be missing. It's very annoying because it's easy to miss-swipe while trying to scroll down and delete a song accidentally.

### Suggested Solution

Add an option to just disable the feature or add a confirm tap on the delete icon after the swipe.

**Comment by aneesh1122** [comment]
> Add an option to just disable the feature

You can disable it from settings.

**Comment by fast4x** [comment]
Disable swipe to action in UI settings
