### ISSUE TITLE
[Feature]: Sort by youtube playlist

### ISSUE THREAD

**Issue by teoshibin** [fast4x/RiMusic#2914]
### Description

The order of the playlist is different compared to youtube playlist, is it a limitation or intentional design decision? or does the feature exist but hidden somewhere.

### Suggested Solution

sort by yt playlist

**Comment by fast4x** [comment]
It's a sequential list that api return, haven't number by default...

**Comment by ImGGAAVVIINN** [comment]
> It's a sequential list that api return, haven't number by default...

Is there a way to make it follow playlist order at this point?

**Comment by fast4x** [comment]
Example please

**Comment by ImGGAAVVIINN** [comment]
When a playlist on YouTube is ordered as

- song 1
- song 2
- song 3

Is it currently possible for RiMusic to import the playlist as

- song 1
- song 2
- song 3

Instead of something like

- song 2
- song 1
- song 3

Which is default behaviour

**Comment by fast4x** [comment]
Ok ill check it with your info, thanks
