### ISSUE TITLE
It keeps on crashing when i pause it for more then a minute or open it while a sog is playing

### ISSUE THREAD

**Issue by Julian1535** [fast4x/RiMusic#2915]
### Steps to reproduce the bug

.

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

.

### Logs

.

### RiMusic version

.

### Android version

Idk

### Additional information

.

**Comment by fast4x** [comment]
required more description or paste rimusic log, enable it in miscellaneour settings..

**Comment by Julian1535** [comment]
> required more description or paste rimusic log, enable it in miscellaneour settings..

What do i do i don't get what you said

**Comment by twistios** [comment]
For how to get logs see here:
https://github.com/fast4x/RiMusic/wiki/FAQs#how-do-i-get-log-files-in-case-of-a-crash

**Comment by fast4x** [comment]
nice
