### ISSUE TITLE
No more playlist :(

### ISSUE THREAD

**Issue by dolexuwu** [fast4x/RiMusic#2917]
### Steps to reproduce the bug

1. Go to library
2. Choose a playlist
3. Choose a song
4. Click next or random
5. It will bring you back to the same song 

### Expected behavior

The following song would be played

### Actual behavior

My song repeats :-1

### RiMusic version

0.6.44

### Android version

13

**Comment by Sahl1** [comment]
Before playing the song make sure to click the star icon on the bottom left of the player

**Comment by Ao1Pointblank** [comment]
That button really needs a toggle. It's the "whoops no more music" button rn lol. I pretty much only listen to playlists since YouTube radios and suggestions are pretty bad without an account.

**Comment by dolexuwu** [comment]
thanks dude, works again!

**Comment by dolexuwu** [comment]
Heya!, ur las update is bugged. I can't click on basic buttons n' options.
I'll show ya:
1. I click in "chill"
2. I swipe up
3. I click in rises da moon
4. I click in da song n' he takes me out

**Comment by dolexuwu** [comment]
fix it please, I can't see the lyrics :(
