### ISSUE TITLE
Écouter les titres qui se trouvent sur mon smartphone

### ISSUE THREAD

**Issue by pascalj972** [fast4x/RiMusic#2918]
### Description

Pouvez vous remettre l option pour écouter mes titres de mon smartphone ?

### Suggested Solution

Option pour écouter les titres qui se trouvent sur mon smartphone

**Comment by fast4x** [comment]
You can find them in home > songs

https://github.com/user-attachments/assets/8bbb51af-1e1a-47b6-8e63-820908c76423
