### ISSUE TITLE
opening the player skips songs

### ISSUE THREAD

**Issue by teacupmaps** [fast4x/RiMusic#2919]
### Steps to reproduce the bug

1. play any song
2. press the player bar

### Expected behavior

the song continues playing

### Actual behavior

songs start skipping as if I pressed the next button every second

### RiMusic version

0.6.44

### Android version

Android 10

**Comment by fast4x** [comment]
Check Medley duration in player by long tap on play/pause button

**Comment by teacupmaps** [comment]
it's 1

**Comment by fast4x** [comment]
reset or move to 0 by click on hourglass,

**Comment by teacupmaps** [comment]
thank you

**Comment by fast4x** [comment]
You are welcome
