### ISSUE TITLE
Crash if lyrics are open for more than a couple minutes 

### ISSUE THREAD

**Issue by lake-effect** [fast4x/RiMusic#2929]
### Steps to reproduce the bug

1. Play a song
2. Tap to view lyrics
3. Scroll down following the music
4. App suddenly crashes

### Expected behavior

App shouldn't crash 

### Actual behavior

App closes without warning 

### Screenshots/Screen recordings

![Screenshot_20240725-222924](https://github.com/user-attachments/assets/e0f33ee1-50ca-4b3c-8821-f7d3e31fa1b9)

### Logs

[RiMusic log 2f75e4f74b90.txt](https://github.com/user-attachments/files/16386888/RiMusic.log.2f75e4f74b90.txt)

### RiMusic version

0.6.44

### Android version

Android 14

**Comment by Timotit** [comment]
I have the same problem.
