### ISSUE TITLE
Crash on Liked, Downloaded Playlists

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#293]
### Steps to reproduce the bug

1. Tap on Liked/Downloaded Playlist

### Expected behavior

Dosen't crash

### Actual behavior

Crash

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/104271365/1b126e5a-caaa-4cba-af10-2bb93828e903

### Logs

I could give logs if someone tels me how

### RiMusic version

0.6.15

### Android version

Android 14 with One UI 6

### Additional information

I tried to instal the app on my samsung secure folder and it worked untill i used my database maybe i have too mutch songs liked

**Comment by fast4x** [comment]
how many songs you have

**Comment by OrangeZXZ** [comment]
> how many songs you have 

more that 600

**Comment by shahidshafique** [comment]
its crashing for me as well less than 50 liked  songs

**Comment by fast4x** [comment]
Try this please:
Settings > Audio quality format > Switch to medium and try favorites or downloads songs again

**Comment by shahidshafique** [comment]
> Try this please: Settings > Audio quality format > Switch to medium and try favorites or downloads songs again

i changed the audio quality format to medium crash still happening for me .

**Comment by OrangeZXZ** [comment]
> i changed the audio quality format to medium crash still happening for me . 

mee too

**Comment by fast4x** [comment]
Maybe I understand the problem, I’m preparing an apk version that should not crash, please try it. Soon I’ll attach the link to download it from https://rimusic.xyz

**Comment by fast4x** [comment]
Ready, try this https://rimusic.xyz/download/app-release.apk

**Comment by OrangeZXZ** [comment]
> Ready, try this https://rimusic.xyz/download/app-release.apk

The patch works thx! so what caused that?

**Comment by shahidshafique** [comment]
> Ready, try this https://rimusic.xyz/download/app-release.apk

its working fine now thanks

**Comment by fast4x** [comment]
Thank you very much!
The cause is the calculation of the total time of the songs in the playlists, introduced with the latest version.

**Comment by fast4x** [comment]
I better check the calculation for the next version.
Now I publish the official update
