### ISSUE TITLE
no se pueden mover las canciones que están en la cola

### ISSUE THREAD

**Issue by pokeshadow89** [fast4x/RiMusic#2930]
### Steps to reproduce the bug

1 elige varias canciones
2 abre la cola
3 trata de cambiar el orden de las canciones y no se podrá
4 tampoco se puede eliminar moviéndola de forma horizontal

### Expected behavior

antes se podían mover las canciones de la cola, fuera de forma horizontal y vertical

### Actual behavior

ahora ya no se puede

### RiMusic version

v0.6.4.4

### Android version

Android 12

**Comment by fast4x** [comment]
Try custom version it's just fixed
