### ISSUE TITLE
App gatting crash 

### ISSUE THREAD

**Issue by mohandan1** [fast4x/RiMusic#294]
It was a great update.but after updating app,it's crashing when clicking on device's files or saved playlists,which are not downloaded.

https://github.com/fast4x/RiMusic/assets/135564025/1059e6d9-22ef-4617-96b7-85446dfc2b0f

### Expected behavior

App might not crashed

### Actual behavior

App crashed

### RiMusic version

0.6.15

### Android version

Android 12

**Comment by fast4x** [comment]
Are you sure you granted permission to read local songs?

**Comment by fast4x** [comment]
How many songs do you have?

**Comment by fast4x** [comment]
Please try this https://rimusic.xyz/download/app-release.apk

**Comment by SveinAu** [comment]
Working for me. Hade the same problem.

**Comment by fast4x** [comment]
Perfect, thanks for feedback

**Comment by mohandan1** [comment]
Yes,I granted permission and I have about 300 local songs.

**Comment by mohandan1** [comment]
It's working now, thanks 🙏

**Comment by fast4x** [comment]
perfect thanks for feedback
