### ISSUE TITLE
It always plays the next song

### ISSUE THREAD

**Issue by Chicotes55** [fast4x/RiMusic#2942]
### Steps to reproduce the bug

1 open Ri music 
2 play a song 

### Expected behavior

Listen to the desired song

### Actual behavior

It always plays the next song and then next and then next song...

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/d0b3497b-c26e-4dba-aef9-71e012fec328

![Screenshot_20240726-235029](https://github.com/user-attachments/assets/cd87c4ec-3b79-42fb-8781-f3139697db2c)

### RiMusic version

0.6.44

### Android version

Android 9

**Comment by cMattw** [comment]
It's the medley feature. Click the medley icon to reset it.

**Comment by Chicotes55** [comment]
Oh you're right, thanks
