### ISSUE TITLE
Se cambian solas las canciones sin parar al abrir el menú de la canción 

### ISSUE THREAD

**Issue by Pan-decoco** [fast4x/RiMusic#2943]
### Steps to reproduce the bug

Cuando pones una canción si abres el menú de la canción se cambian solas y sin parar y si desplegas abajo la miniatura deja de cambiarse las canciones 

### Expected behavior

Que puedas ver el menú de las canciones en grande sin que se cambie sola 

### Actual behavior

Se cambian solas las canciones y sin parar al poner el menú de la canción 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/3a105bd7-4214-4d2a-a826-f0bbdfd50d13

### RiMusic version

0.6.44

### Android version

Android 

### Additional information

Cuando el menú de la canción está en pausa se dejan de cambiar las canciones pero si quitas la pausa vuelven a cambiar las canciones sin control

**Comment by Cuchurrumin19** [comment]
Presiona el botón de pausa por un par de segundos, al hacer eso te va a aparecer  un menú, si «Medley duration» no aparece en 0 puede que ese sea el problema, de ser así pulsa el icono con el reloj de arena y listo :3
