### ISSUE TITLE
changing volume while playing a song causes crash

### ISSUE THREAD

**Issue by AstroLightz** [fast4x/RiMusic#2950]
### Steps to reproduce the bug

1. Start a song
2. Try to change volume

### Expected behavior

Change volume without crashing.

### Actual behavior

Most of the time, it leads to a crash.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/0b3ddac7-3f0b-4aac-badd-20598e8e9166

https://github.com/user-attachments/assets/d0a2aea2-eae1-4c61-9341-fd8f7123da58

### Logs

[rimusic_crash.log](https://github.com/user-attachments/files/16401593/rimusic_crash.log)

### RiMusic version

0.6.45

### Android version

Android 14

### Additional information

Only occurs when playing music. Occurs outside the app when playing in background.

**Comment by AstroLightz** [comment]
I forgot to mention that when the app crashes this way, it tends to set the volume of whatever device you're playing audio out of (Headphones, phone speakers, etc) to 0.

**Comment by fast4x** [comment]
Disable to disable pause song when volume is zero

**Comment by AstroLightz** [comment]
> Try to disable pause song when volume is zero

I'm looking through the settings page to find that, but I'm not seeing it. Which settings page is it under?

**Comment by aneesh1122** [comment]
> Try to disable pause song when volume is zero 

The behaviour is different in my case. When I increase the volume the app decreases the volume. When I hold the play button and increases the device volume from slider the volume is fixed.

Btw I could not find the option to disable pause song when volume is zero.

**Comment by siggi1984** [comment]
> ### Steps to reproduce the bug
> 
>     1. Start a song
> 
>     2. Try to change volume
> 
> 
> ### Expected behavior
> 
> Change volume without crashing.
> ### Actual behavior
> 
> Most of the time, it leads to a crash.
> ### Screenshots/Screen recordings
> Record_2024-07-27-17-52-09.mp4
> Record_2024-07-27-17-56-09.mp4
> ### Logs
> 
> [rimusic_crash.log](https://github.com/user-attachments/files/16401593/rimusic_crash.log)
> ### RiMusic version
> 
> 0.6.45
> ### Android version
> 
> Android 14
> ### Additional information
> 
> Only occurs when playing music. Occurs outside the app when playing in background.

Same problem

**Comment by Wander42** [comment]
man im getting tired of almost every update having a crash for random things, youd think theyd test this stuff

**Comment by KOLIWAN** [comment]
I have the same issue, app crashes if I press volume up/down

`2024-07-28T13:03:10.119: java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
  a.a.m(SourceFile:57) 
  C0.e.L(SourceFile:69) 
  h2.s.onAdjustVolume(SourceFile:3) 
  android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1657) 
  android.os.Handler.dispatchMessage(Handler.java:106) 
  android.os.Looper.loopOnce(Looper.java:226) 
  android.os.Looper.loop(Looper.java:313) 
  android.app.ActivityThread.main(ActivityThread.java:8762) 
  java.lang.reflect.Method.invoke(Native Method) 
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

2024-07-28T13:03:23.545: java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
  a.a.m(SourceFile:57) 
  C0.e.L(SourceFile:69) 
  h2.s.onAdjustVolume(SourceFile:3) 
  android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1657) 
  android.os.Handler.dispatchMessage(Handler.java:106) 
  android.os.Looper.loopOnce(Looper.java:226) 
  android.os.Looper.loop(Looper.java:313) 
  android.app.ActivityThread.main(ActivityThread.java:8762) 
  java.lang.reflect.Method.invoke(Native Method) 
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

2024-07-28T13:03:58.315: java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
  a.a.m(SourceFile:57) 
  C0.e.L(SourceFile:69) 
  h2.s.onAdjustVolume(SourceFile:3) 
  android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1657) 
  android.os.Handler.dispatchMessage(Handler.java:106) 
  android.os.Looper.loopOnce(Looper.java:226) 
  android.os.Looper.loop(Looper.java:313) 
  android.app.ActivityThread.main(ActivityThread.java:8762) 
  java.lang.reflect.Method.invoke(Native Method) 
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

2024-07-28T13:04:21.561: java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
  a.a.m(SourceFile:57) 
  C0.e.L(SourceFile:69) 
  h2.s.onAdjustVolume(SourceFile:3) 
  android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1657) 
  android.os.Handler.dispatchMessage(Handler.java:106) 
  android.os.Looper.loopOnce(Looper.java:226) 
  android.os.Looper.loop(Looper.java:313) 
  android.app.ActivityThread.main(ActivityThread.java:8762) 
  java.lang.reflect.Method.invoke(Native Method) 
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

2024-07-28T13:04:35.816: java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
  a.a.m(SourceFile:57) 
  C0.e.L(SourceFile:69) 
  h2.s.onAdjustVolume(SourceFile:3) 
  android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1657) 
  android.os.Handler.dispatchMessage(Handler.java:106) 
  android.os.Looper.loopOnce(Looper.java:226) 
  android.os.Looper.loop(Looper.java:313) 
  android.app.ActivityThread.main(ActivityThread.java:8762) 
  java.lang.reflect.Method.invoke(Native Method) 
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

2024-07-28T13:04:58.408: java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
a.a.m(SourceFile:57) 
  C0.e.L(SourceFile:69) 
  h2.s.onAdjustVolume(SourceFile:3) 
  android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1657) 
  android.os.Handler.dispatchMessage(Handler.java:106) 
  android.os.Looper.loopOnce(Looper.java:226) 
  android.os.Looper.loop(Looper.java:313) 
  android.app.ActivityThread.main(ActivityThread.java:8762) 
  java.lang.reflect.Method.invoke(Native Method) 
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

2024-07-28T13:05:12.442: java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
  a.a.m(SourceFile:57) 
  C0.e.L(SourceFile:69) 
  h2.s.onAdjustVolume(SourceFile:3) 
  android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1657) 
  android.os.Handler.dispatchMessage(Handler.java:106) 
  android.os.Looper.loopOnce(Looper.java:226) 
  android.os.Looper.loop(Looper.java:313) 
  android.app.ActivityThread.main(ActivityThread.java:8762) 
  java.lang.reflect.Method.invoke(Native Method) 
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

2024-07-28T13:05:27.857: java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
  a.a.m(SourceFile:57) 
  C0.e.L(SourceFile:69) 
  h2.s.onAdjustVolume(SourceFile:3) 
  android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1657) 
  android.os.Handler.dispatchMessage(Handler.java:106) 
  android.os.Looper.loopOnce(Looper.java:226) 
  android.os.Looper.loop(Looper.java:313) 
  android.app.ActivityThread.main(ActivityThread.java:8762) 
  java.lang.reflect.Method.invoke(Native Method) 
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

2024-07-28T13:05:42.887: java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
  a.a.m(SourceFile:57) 
  C0.e.L(SourceFile:69) 
  h2.s.onAdjustVolume(SourceFile:3) 
  android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1657) 
  android.os.Handler.dispatchMessage(Handler.java:106) 
  android.os.Looper.loopOnce(Looper.java:226) 
  android.os.Looper.loop(Looper.java:313) 
  android.app.ActivityThread.main(ActivityThread.java:8762) 
  java.lang.reflect.Method.invoke(Native Method) 
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`
  
https://github.com/user-attachments/assets/f8cb59ee-815e-49c6-948a-20ba7ac68cf1

Also somehow at the volume "tray" you can see it shows icon of TV (I'm not connected to a TV or something), it happens only in new version of RiMusic
Option to pause/stop songs with volume buttons is disabled

**Comment by AstroLightz** [comment]
For me, the "TV" icon is labeled as RiMusic, so I'm assuming that's related to the "mute volume to pause" option.
![Screenshot_2024-07-27-21-27-02-21_50ecd26a21c2c56ce608de5e94733463](https://github.com/user-attachments/assets/0936d156-8c60-4597-807a-d8018a7b035b)

**Comment by massimostanzione** [comment]
Android 13: _not_ happening when modifying volume level via "Multimedia Output" in the upper notification menu, so it seems to be specific of the volume buttons.

**Comment by AstroLightz** [comment]
Looks like it was fixed. Thanks fast4x.
