### ISSUE TITLE
Bad atualization

### ISSUE THREAD

**Issue by Aloevera8194** [fast4x/RiMusic#2951]
### Steps to reproduce the bug

I cant UP the volume nor read the lirics because the aplicativo bugs after the last atualization...0.6.45

### Expected behavior

Thank you for Thais app... I love It. 
Please make a way tô share a playlist in app... 
We love you

### Actual behavior

Always when i UP volume or ser the lirics the app shut down

### RiMusic version

0.6.45

### Android version

Android 14

### Additional information

Thanks

**Comment by fast4x** [comment]
Download latest version please
