### ISSUE TITLE
When i try to turn the volume up or down a tv thing pops up and it says rimusic. When i turn that up slightly or down the app crashes

### ISSUE THREAD

**Issue by Julian1535** [fast4x/RiMusic#2952]
### Steps to reproduce the bug

Play a song and try to turn up the volume

### Expected behavior

. 

### Actual behavior

.

### Screenshots/Screen recordings

![Screenshot_20240727_180216](https://github.com/user-attachments/assets/24cc7f11-c199-475c-a6d1-ef183ea905d0)

### Logs

. 

### RiMusic version

.

### Android version

.

### Additional information

.

**Comment by fast4x** [comment]
Download latest version please
