### ISSUE TITLE
Fallo al subir el volumen 

### ISSUE THREAD

**Issue by benito-33** [fast4x/RiMusic#2953]
### Steps to reproduce the bug

Solo tienes que abrir la aplicación, empezar a escuchar una canción y cuando intentas subir el volumen desde el botón del dispositivo, este hace que se reinicie la aplicación y te saque de ella no dejandote ajustar el volumen.

### Expected behavior

Debería suceder que si subes el volumen desde el botón del dispositivo este suba en vez de sacarte de la aplicación y reiniciar el volumen.

### Actual behavior

Cuando abres la aplicación, todo va normal hasta que empiezas a escuchar una canción e intentas subir el volumen con el botón de aumentar el volumen del dispositivo, momento en el que la aplicación se cierra y se reinicia, no dejando subir el volumen.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/b8ee2cab-88d4-45c7-b3c9-120527c8c2b2

### RiMusic version

O.6.45

### Android version

Android 14

**Comment by fast4x** [comment]
Download latest version please
