### ISSUE TITLE
Volume trouble

### ISSUE THREAD

**Issue by OscarCL98** [fast4x/RiMusic#2954]
### Steps to reproduce the bug

1- I lowered the volume a little
2- The music was silenced with one or two clicks

The volume never was the same in my phone and the app.

The app closes if I insist on move the volume with the buttons in my phone.

I use a Poco M6 Pro

### Expected behavior

The volume should decrease gradually 

### Actual behavior

The volume acts in a weird way

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/3a73532c-42bd-4b6f-a9f7-57c6195c1bad

### Logs

2024-07-27T18:55:20.723:	java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 C0.e.L(SourceFile:69) 
	 h2.s.onAdjustVolume(SourceFile:3) 
	 android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1663) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:222) 
	 android.os.Looper.loop(Looper.java:314) 
	 android.app.ActivityThread.main(ActivityThread.java:8671) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 

### RiMusic version

0.6.45

### Android version

Android 14, HyperOs 1.0.3.0

**Comment by fast4x** [comment]
Download latest version please
