### ISSUE TITLE
Volumen

### ISSUE THREAD

**Issue by dxsker** [fast4x/RiMusic#2956]
### Steps to reproduce the bug

al reproducir una música y querer modificar el volumen mediante los botones del dispositivo la música se pausa y no deja subir ni bajar el volumen si no es desde la misma pantalla 

https://github.com/user-attachments/assets/b7397396-5a18-4c93-bc7c-7c27fdc93db3

### Expected behavior

El comportamiento de los botones del volumen debería ser subir y bajar el volumen 

### Actual behavior

Los botones de bajar y subir volumen solo lo bajan asta un punto en donde la música se pausa y si se des pausa se repite el ciclo

### RiMusic version

0.6.45

### Android version

Android 12

**Comment by fast4x** [comment]
Download latest version please
