### ISSUE TITLE
Crashed while adjusting volume

### ISSUE THREAD

**Issue by Ashubnx** [fast4x/RiMusic#2958]
### Steps to reproduce the bug

While playing song adjusted volume and app just crashed(closed) 

### Expected behavior

Crashed or closed

### Actual behavior

Wanted to increas volume but it close whole app

### Logs

2024-07-28T07:09:04.652:	java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 C0.e.L(SourceFile:69) 
	 h2.s.onAdjustVolume(SourceFile:3) 
	 android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1658) 
	 android.os.Handler.dispatchMessage(Handler.java:111) 
	 android.os.Looper.loopOnce(Looper.java:238) 
	 android.os.Looper.loop(Looper.java:357) 
	 android.app.ActivityThread.main(ActivityThread.java:8090) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026) 

2024-07-28T07:10:08.920:	java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 C0.e.L(SourceFile:69) 
	 h2.s.onAdjustVolume(SourceFile:3) 
	 android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1658) 
	 android.os.Handler.dispatchMessage(Handler.java:111) 
	 android.os.Looper.loopOnce(Looper.java:238) 
	 android.os.Looper.loop(Looper.java:357) 
	 android.app.ActivityThread.main(ActivityThread.java:8090) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026) 

2024-07-28T07:23:09.819:	java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 C0.e.L(SourceFile:69) 
	 h2.s.onAdjustVolume(SourceFile:3) 
	 android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1658) 
	 android.os.Handler.dispatchMessage(Handler.java:111) 
	 android.os.Looper.loopOnce(Looper.java:238) 
	 android.os.Looper.loop(Looper.java:357) 
	 android.app.ActivityThread.main(ActivityThread.java:8090) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026) 

2024-07-28T07:23:42.487:	java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 C0.e.L(SourceFile:69) 
	 h2.s.onAdjustVolume(SourceFile:3) 
	 android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1658) 
	 android.os.Handler.dispatchMessage(Handler.java:111) 
	 android.os.Looper.loopOnce(Looper.java:238) 
	 android.os.Looper.loop(Looper.java:357) 
	 android.app.ActivityThread.main(ActivityThread.java:8090) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026) 

2024-07-28T07:23:50.836:	java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 C0.e.L(SourceFile:69) 
	 h2.s.onAdjustVolume(SourceFile:3) 
	 android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1658) 
	 android.os.Handler.dispatchMessage(Handler.java:111) 
	 android.os.Looper.loopOnce(Looper.java:238) 
	 android.os.Looper.loop(Looper.java:357) 
	 android.app.ActivityThread.main(ActivityThread.java:8090) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026) 

### RiMusic version

0.6.45

### Android version

Android 12

**Comment by fast4x** [comment]
Download latest version please

**Comment by Ashubnx** [comment]
Godspeed
