### ISSUE TITLE
Comportamiento erróneo con el volumen (Actualización rota).

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#2959]
### Steps to reproduce the bug

1. Reproduzca cualquier canción (Expulsa de la aplicación).
2. Suba o baje el volumen (Expulsa de la aplicación).
3. Actualización rota (Cualquier acción que se realiza expulsa al inestante).

### Expected behavior

Reproducción y uso fluido.

### Actual behavior

Actualización completamente rota.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/04e01ffb-6491-4047-b8ff-de866a36d098

### Logs

N/A

### RiMusic version

0.6.45

### Android version

Android 14

### Additional information

Las novedades son increíbles pero que pena que la actualización está completamente rota :(

**Comment by fast4x** [comment]
Download latest version please
