### ISSUE TITLE
Can u add french emojis on crowdin?

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#296]
### Description

Can u add french emojis on crowdin?

### Suggested Solution

.

**Comment by NEVARLeVrai** [comment]
Also u added me in Portuguese Brazilian but it's not really "the same" on some translations, then I don't really know this side of this variant of the Portuguese language

**Comment by fast4x** [comment]
> Also u added me in Portuguese Brazilian but it's not really "the same" on some translations, then I don't really know this side of this variant of the Portuguese language

Isn’t the Portuguese - Brazilian language code correct?

**Comment by fast4x** [comment]
Sure, you confirm that when you set up system language, you see the one with emojis?

**Comment by fast4x** [comment]
Added french and Romanian With emoji

**Comment by NEVARLeVrai** [comment]
> > Also u added me in Portuguese Brazilian but it's not really "the same" on some translations, then I don't really know this side of this variant of the Portuguese language
> 
> Isn’t the Portuguese - Brazilian language code correct?

I wasn't talking about that but forget it, it doesn't matter

**Comment by NEVARLeVrai** [comment]
> Sure, you confirm that when you set up system language, you see the one with emojis?

Yes![Screenshot_2023-12-30-20-48-17-338_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/63956787/131e1b5d-d2d8-4902-9a5e-e9f704383ae5)

**Comment by fast4x** [comment]
Added french and Romanian With emoji

With the next update should settle
