### ISSUE TITLE
Crashing and stuff

### ISSUE THREAD

**Issue by JustShade04** [fast4x/RiMusic#2960]
### Steps to reproduce the bug

1. Open the app
2. Play any song
3. Press volume up or down
4. The song just volumes down and the app crashes

### Expected behavior

Normal volume up and down control stuff

### Actual behavior

The volume goes down no matter if I pressed volume up or volume down, and the app crashes when the volume reaches the bottom. 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/1babfa16-f4e5-49c8-9d6c-124ae9acf9fd

### Logs

2024-07-28T09:28:20.411:	java.lang.ClassCastException: it.fast4x.rimusic.service.PlayerService cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 C0.e.L(SourceFile:69) 
	 h2.s.onAdjustVolume(SourceFile:3) 
	 android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1659) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8348) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028) 

### RiMusic version

0.6.45

### Android version

Android 13

**Comment by fast4x** [comment]
Download latest version please
