### ISSUE TITLE
App closes when volume down

### ISSUE THREAD

**Issue by TheCibrik** [fast4x/RiMusic#2961]
### Steps to reproduce the bug

I opened the app, played a song, turned up the volume on my phone, the app closed, just like that.

### Expected behavior

I was hoping that when I pressed the "volume up" button the app wouldn't close 

### Actual behavior

When I increased the volume with the button, the application closed.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/0245b549-204d-48b2-ba64-bb4e717d5ce2

### RiMusic version

v.0.6.45

### Android version

Android 13

**Comment by MrAshish74** [comment]
Same Happening with Me.
First In My device Songs Are Changing Themselves, 
then This also Started.

**Comment by SureshTimma** [comment]
Yes same with me.

Android 14

**Comment by SureshTimma** [comment]
@fast4x 
Thank you for latest update 46.1 
Problem got solved

**Comment by MrAshish74** [comment]
Yes Thanks
