### ISSUE TITLE
Auto Song's Changes & Closing.

### ISSUE THREAD

**Issue by MrAshish74** [fast4x/RiMusic#2962]
### Steps to reproduce the bug

Open Player Play A Song
& then This Happens With me.

### Expected behavior

It Have To Not Change Song Itself.

### Actual behavior

Song's Are Changing Automatically In My Device (Redmi 9)
And Sometimes App Close Itself After Opening it.

### Screenshots/Screen recordings

Quality is Low Because of Reduced size.

https://github.com/user-attachments/assets/40ab5074-df82-435c-9bc7-36902d0062c8

### RiMusic version

0.6.45

### Android version

Android 10  ):

**Comment by fast4x** [comment]
You have Medley mode enabled, long press in play button in player and tap on hourglass to disable it

**Comment by MrAshish74** [comment]
Ok I'll try
