### ISSUE TITLE
App se cierra y se detiene

### ISSUE THREAD

**Issue by Nisselle** [fast4x/RiMusic#2963]
### Steps to reproduce the bug

1. Entro a la app
2. Elijo una canción para reproducirla
3. Intento subirle el volumen 
4. En vez de subir el volumen lo baja 
5. Se detiene la app y se cierra al bajarse todo el volumen (el cual debería subir)

### Expected behavior

Que se suba el volumen en lugar de bajarse y que no se cierre o se detenga

### Actual behavior

Baja el volumen en vez de subir al presionar el botón de subir

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/4040119a-d8c0-42e8-8df1-5744f21828dd

### RiMusic version

0.6.45

### Android version

Android 11

### Additional information

Ya pobre reiniciando el celular, usar el RiMusic en otros celulares y hacer lo mismo y en todos pasa el mismo error, esto empezo a pasar exclusivamente con esta nueva versión que instale.

**Comment by Kou-tester** [comment]
me pasa exactamente lo mismo, solo q a mi se me desconecta el audifono al cerrarse la app

**Comment by fast4x** [comment]
Download latest version please
