### ISSUE TITLE
the app closes and the sound is bugged 

### ISSUE THREAD

**Issue by Kou-tester** [fast4x/RiMusic#2964]
### Steps to reproduce the bug

1. i was listening Devil in a new dress by Kanye and suddenly the sound bugged and the app closed

### Expected behavior

This has already happened 4 times since I updated 

### Actual behavior

When the sound is bugged (I need headphones) it appears as if I did not have headphones and then it goes black and closes

### RiMusic version

version 0.6.45

### Android version

Android 14

**Comment by vedgar** [comment]
For me, it crashes every time I change the volume (newest version). :(

**Comment by fast4x** [comment]
Fixed, available from version 0.6.45.1
