### ISSUE TITLE
Your app have volume Key issues . 

### ISSUE THREAD

**Issue by ksnprogrammer** [fast4x/RiMusic#2966]
### Steps to reproduce the bug

1.Go app
2.Play music
3 Volume adjust 

### Expected behavior

It's must showing only normal volume 

### Actual behavior

it's showing mirroring volume 

### Screenshots/Screen recordings

![Screenshot_20240728_105818_it fast4x rimusic](https://github.com/user-attachments/assets/d1c7ed25-c726-45b3-b813-9928821cc2c0)

### RiMusic version

0.6.45

### Android version

Android 10

### Additional information

I think it's mirroring volume

**Comment by fast4x** [comment]
Fixed, available from version 0.6.45.1
