### ISSUE TITLE
New discover option bug

### ISSUE THREAD

**Issue by testandreport** [fast4x/RiMusic#2967]
### Steps to reproduce the bug

Go to UI settings
Activate Discover - Removes liked and playlist songs from queue
Now every Playlist is useless and plays only the first selected song (queue with only this song)
Every song of an album, that is liked or in a playlist is excluded as well.

If this behaviour is intended then close this ticket. But for me this global option makes no sense, I can already discover new stuff on the Quick Picks page and regularly want to hear my playlists.

The discover button in the player seems to do the same thing. The option gets activated by clicking the star and gets deactivated by clicking again (without restoring the original queue).

### Expected behavior

I expect this setting only to affect the discovery page / "For You" area

OR

This option should only be available in the player and ONLY affect the current queue (and disable itself after clicking on it)

### Actual behavior

Currently this seems to affect all queues.

### RiMusic version

0.6.45

### Android version

Android 14

**Comment by fast4x** [comment]
Discover is intended for listening songs that you don't know, not new music... 
New music songs are present in Quick Picks page

**Comment by fast4x** [comment]
Feature will be limited to new songs from radio feature...

**Comment by fast4x** [comment]
Implemented, now discover removes liked and playlist songs only from radio.
Available from version 0.6.46
