### ISSUE TITLE
la aplicación se traba y se cierra sola

### ISSUE THREAD

**Issue by chepegod** [fast4x/RiMusic#2969]
### Steps to reproduce the bug

estoy escuchando música y la aplicación de pronto se cierra, también se cierra al estar viendo las letras de las canciones 

### Expected behavior

no deberia de pasar nada de eso, no entiendo por que se cierra de una forma inesperada

### Actual behavior

escuchaba musica y se cerro, veia una letra de una canción y se cerri

### RiMusic version

0.6.44

### Android version

Android 13

**Comment by fast4x** [comment]
Fixed, available from version 0.6.45.1
