### ISSUE TITLE
Song's Changes Automatically.

### ISSUE THREAD

**Issue by MrAshish74** [fast4x/RiMusic#2973]
### Steps to reproduce the bug

Open App Play Any Song.

### Expected behavior

Song's Have To Play.

### Actual behavior

Whenever Click On A Song To Play
They're Changing Automatically.

### Screenshots/Screen recordings

This Is The Screen Recording Of This Issue (proof).

https://github.com/user-attachments/assets/a9caad39-6ad1-4f89-ad0d-094371669f4e

### RiMusic version

0.6.45.1

### Android version

Android 10  :)

### Additional information

When I Open App & Play A Song This Song Doesn't Play It Change Auto & Don't Stop Till I Pause 2 - 3 Time , Close It To mini Player Or Close App.

**Comment by cMattw** [comment]
It's the medley feature. Long press the play button and click the medley duration icon to disable it.
