### ISSUE TITLE
Song doesn't play completely ,the song plays for 30 seconds then start again continously 

### ISSUE THREAD

**Issue by Kaynem706** [fast4x/RiMusic#2974]
### Steps to reproduce the bug

I just played a song

### Expected behavior

The song should play completely til its finished 

### Actual behavior

The song restarts every 30 seconds

### RiMusic version

0.6.45.1

### Android version

14

**Comment by hashtagbrowns** [comment]
when you hold the play button, do you see a slider with an hourglass icon ⌛️? it may be set to 30
