### ISSUE TITLE
Songs are glitching 

### ISSUE THREAD

**Issue by nelsonsiby2345** [fast4x/RiMusic#2975]
### Steps to reproduce the bug

Some songs are glitching and skipping the songs short portions 

### Expected behavior

Songs have to play without glitching and skipping 

### Actual behavior

skipping short seconds of the songs 

### RiMusic version

0.6.45

### Android version

Android 12

**Comment by fast4x** [comment]
Maybe you have Medley mode enabled

**Comment by nelsonsiby2345** [comment]
How do I disable it

**Comment by nelsonsiby2345** [comment]
https://github.com/user-attachments/assets/1753cb6e-c642-4e66-a8f8-e9f981349629

This is what happening

**Comment by fast4x** [comment]
Try to disable audio fade

**Comment by fast4x** [comment]
long tap in play button reset medley mode by click on hourglass

**Comment by aneesh1122** [comment]
Disable this
![Screenshot_2024-07-30-15-01-55-633_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/d8e81bac-4c6e-4b0e-80df-592464dfd120)
