### ISSUE TITLE
`parseInt` crash setting "next in queue" number

### ISSUE THREAD

**Issue by headquarter8302** [fast4x/RiMusic#2976]
### Steps to reproduce the bug

1. Open settings 
2. Set next in queue display to the maximum number, 9
3. Crash

### Expected behavior

The setting to apply, or not apply

### Actual behavior

The app crashed, and no way to revert the setting

### Logs

2024-07-28T17:43:10.488:	java.lang.NumberFormatException: For input string: "9
    "
	 java.lang.Integer.parseInt(Integer.java:797) 
	 java.lang.Integer.parseInt(Integer.java:915) 
	 S6.t0.h(SourceFile:453) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1480) 
	 androidx.compose.animation.a.f(SourceFile:225) 
	 androidx.compose.animation.a.b(SourceFile:429) 
	 e7.o.a(SourceFile:802) 
	 C6.k.i(SourceFile:306) 
	 e0.a.i(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 g0.f.c(SourceFile:149) 
	 D3.b.m(SourceFile:55) 
	 e0.a.e(SourceFile:44) 
	 e0.a.m(SourceFile:9) 
	 J.n0.h(SourceFile:253) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1480) 
	 P6.q.i(SourceFile:307) 
	 e0.a.i(SourceFile:52) 
	 f3.c.b(SourceFile:958) 
	 f3.c.a(SourceFile:321) 
	 O6.G.h(SourceFile:457) 
	 e0.a.d(SourceFile:44) 
	 A6.s.i(SourceFile:199) 
	 W.p.M(SourceFile:438) 
	 W.p.T(SourceFile:137) 
	 W.p.p(SourceFile:244) 
	 W.p.K(SourceFile:32) 
	 W.t.w(SourceFile:22) 
	 W.t0.t(SourceFile:102) 
	 W.r0.b(SourceFile:515) 
	 J0.d0.doFrame(SourceFile:7) 
	 J0.b0.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1648) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1129) 
	 android.view.Choreographer.doFrame(Choreographer.java:1045) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8893) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

### RiMusic version

0.6.45.1

### Android version

Android 14

**Comment by headquarter8302** [comment]
Possible related issues: #2997 #3004

**Comment by fast4x** [comment]
Download a custom version please, try if it work, thanks
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by headquarter8302** [comment]
It's working as intended now

**Comment by fast4x** [comment]
perfect, thanks
