### ISSUE TITLE
Unintentional fade-in, presumably

### ISSUE THREAD

**Issue by KeknanXD** [fast4x/RiMusic#2978]
### Steps to reproduce the bug

(! Fade audio has to be turned off to notice this !)
1. Pause the music
2. Play it again
Alternatively:
1. Fast forward/rewind a song you're currently listening to

### Expected behavior

The song just continues playing immediately.

### Actual behavior

Fade-in effect comes in for a fraction of a second.

### Screenshots/Screen recordings

![Screenshot_20240728_115818](https://github.com/user-attachments/assets/e48781d6-47eb-4dbd-8f8c-61ce04fdeb55)

https://github.com/user-attachments/assets/fd375550-9660-48ed-b94c-b664729f9e55

https://github.com/user-attachments/assets/d106babe-c546-4008-be78-0ee3b2f0b258

### RiMusic version

v0.6.45

### Android version

Android 12

### Additional information

I currently cannot install v0.6.46 yet, so maybe it's fixed there. I'll post it regardless in case this issue persists like the previous issue I posted.

**Comment by KeknanXD** [comment]
Videos fail to show up for some reason. Awesome! I'll try reuploading them somehow.

https://github.com/user-attachments/assets/f3715bd3-3cf4-4713-a863-b0cb8e8dc121


https://github.com/user-attachments/assets/8ed7b891-8787-40d4-8d54-4241df7ebefc

**Comment by KeknanXD** [comment]
There we go.

**Comment by fast4x** [comment]
Fast forward/rewind a song you're currently listening to

Fade isn't supported for fast forwards...

**Comment by KeknanXD** [comment]
Okay yeah true, I just noticed myself, but why does it fade in still? I turned that off and whenever I pause or rewind, it does that anyway.

**Comment by fast4x** [comment]
steange

**Comment by RevanthSurapaneni** [comment]
> Okay yeah true, I just noticed myself, but why does it fade in still? I turned that off and whenever I pause or rewind, it does that anyway.

for me i turned off fade, but when i skip to next song it fades in anyway :(

**Comment by fast4x** [comment]
if restart app fade continue?

**Comment by RevanthSurapaneni** [comment]
> if restart app fade continue?

I don't know about the other person,  but I've tried the two newest releases with the fade feature and it still happens.  I tried the custom version since one of the devs told me to download it from another issue I opened, still happens. 

By the way it only happens when I manually pause fast forward or skip to next song. If the song changes automatically after the current song is over , there's no fade in (I have the fade setting disabled)

**Comment by fast4x** [comment]
it's normal only when you click pause/play

**Comment by KeknanXD** [comment]
So I downloaded the most recent version sometime ago and that issue does apply to fast forwarding now, but not rewinding. Huh?
But here's the catch: It only does this when you _tap_ on a certain point, not _swipe._ When you swipe to a certain point, it's fine, but when you tap, it does the fade in thing even though I fully disabled that feature. Weird.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.46
