### ISSUE TITLE
Can't play album

### ISSUE THREAD

**Issue by KeknanXD** [fast4x/RiMusic#2979]
### Steps to reproduce the bug

1. Go to any release that has more than one track
2. Play a song
3. Skip to the prior/next or let it play until the end

### Expected behavior

The prior/next should play.

### Actual behavior

You're stuck in the same song. It's the only one listed in the queue.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/ea9e7b2e-45dd-4825-8fd8-186a56f8b2f9

### RiMusic version

v0.6.44; v0.6.45

### Android version

Android 12

### Additional information

Can't install v0.6.46 yet, it might be fixed there. But this is an issue that I've had since v0.6.44, so I think it's best to bring this to attention.

**Comment by fast4x** [comment]
Disable discover button , bottom left... it clean queue by preferite and song in playlist

**Comment by KeknanXD** [comment]
OOOOHHHHHH I see now, alright that fixed the album and queue issue. Thanks lol
