### ISSUE TITLE
Download song without cover.

### ISSUE THREAD

**Issue by SveinAu** [fast4x/RiMusic#298]
### Steps to reproduce the bug

If you download a song offline and have not play before you are offline you will not have a cover. 

### Expected behavior

No song cover 

### Actual behavior

Black cover. No photo

### RiMusic version

Last

### Android version

Android 14

**Comment by DeadSecTr** [comment]
What?

**Comment by fast4x** [comment]
Make sure your image cache is configured in the settings, in case the amount of space increases.

**Comment by SveinAu** [comment]
Ok. Thanks

**Comment by fast4x** [comment]
Resolved?

**Comment by SveinAu** [comment]
No. It not a big deal.:))
