### ISSUE TITLE
Can't add any songs to queue

### ISSUE THREAD

**Issue by KeknanXD** [fast4x/RiMusic#2980]
### Steps to reproduce the bug

1. Hold on a song
2. Select "play next" or "add to queue"

### Expected behavior

The song you selected is part of the queue now

### Actual behavior

The song you selected doesn't show up

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/b34efe2c-510d-43ae-8b83-f3a5ac56952b

### RiMusic version

v0.6.45

### Android version

Android 12

### Additional information

I cannot install v0.6.46 yet, it might be fixed there. I can recall that being an issue for quite a while, though. So it's best to bring it to attention, I believe.

**Comment by fast4x** [comment]
Bottom left, disable discover button... it remove from queue preferite and song in playlist

**Comment by KeknanXD** [comment]
Got it, works now. Thanks!
