### ISSUE TITLE
Wrong Version number in update message

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#2984]
### Steps to reproduce the bug

1. Have an old version installed
2. Have Check for Updates enabled
3. Close App
4. Open App.

### Expected behavior

The correct Version should be 0.6.45.1.

### Actual behavior

Version is 0.6.46.

### Screenshots/Screen recordings

![Screenshot_20240728_150937](https://github.com/user-attachments/assets/9c6a3fbc-5489-4cb7-b8c3-1235b538a828)

### RiMusic version

0.6.44

### Android version

14

**Comment by fast4x** [comment]
Fixed, thanks
