### ISSUE TITLE
Issues with the cover and lyrics

### ISSUE THREAD

**Issue by Afuckingtomato** [fast4x/RiMusic#2985]
### Steps to reproduce the bug

Activate and disactivate fading edge

### Expected behavior

The lyrics should show

### Actual behavior

I activated the fading edge option and I didn't like it and I removed it, now the cover appears cut off at the bottom and I can't see the lyrics, I've tried everything and it doesn't come off and when I keep the cover pressed, only 2 options appear that don't I know what they are for

### Screenshots/Screen recordings

![Screenshot_20240728_090245](https://github.com/user-attachments/assets/eeec90f2-1b2e-44f8-acee-898d8d5e8e58)
![Screenshot_20240728_090249](https://github.com/user-attachments/assets/e958e8a9-06eb-4ce3-97e0-a541dbc34f31)

### RiMusic version

0.6.45 and 0.6.45.1

### Android version

Android 14

**Comment by aneesh1122** [comment]
1) disable showing the next songs in the player. It will fix cutting the thumbnail bottom. I'll fix this problem later but for now this is the workaround.

2) for lyrics, make sure that "show thumbnail for lyrics" is disabled in settings.

3) those 2 sliders work in the carousel view.

https://github.com/user-attachments/assets/116d2ff6-078c-4ab6-b7ce-41a051b43fcc

**Comment by ALMIGHTY-VC** [comment]
> 1. disable showing the next songs in the player. It will fix cutting the thumbnail bottom. I'll fix this problem later but for now this is the workaround.
> 2. for lyrics, make sure that "show thumbnail for lyrics" is disabled in settings.
> 3. those 2 sliders work in the carousel view.
> 
>  Screenrecorder-2024-07-28-19-02-58-392.mp4

Offtopic but i dont have any option for fading edge in settings and also about carousel view something im missing?

**Comment by aneesh1122** [comment]
> > 1. disable showing the next songs in the player. It will fix cutting the thumbnail bottom. I'll fix this problem later but for now this is the workaround.
> > 2. for lyrics, make sure that "show thumbnail for lyrics" is disabled in settings.
> > 3. those 2 sliders work in the carousel view.
> > 
> >  Screenrecorder-2024-07-28-19-02-58-392.mp4
> 
> Offtopic but i dont have any option for fading edge in settings and also about carousel view something im missing? 

Use modern player

**Comment by ALMIGHTY-VC** [comment]
> > > 1. disable showing the next songs in the player. It will fix cutting the thumbnail bottom. I'll fix this problem later but for now this is the workaround.
> > > 2. for lyrics, make sure that "show thumbnail for lyrics" is disabled in settings.
> > > 3. those 2 sliders work in the carousel view.
> > > 
> > > Screenrecorder-2024-07-28-19-02-58-392.mp4
> > 
> > 
> > Offtopic but i dont have any option for fading edge in settings and also about carousel view something im missing?
> 
> Use modern player

Okay

**Comment by ALMIGHTY-VC** [comment]
> > > > 1. disable showing the next songs in the player. It will fix cutting the thumbnail bottom. I'll fix this problem later but for now this is the workaround.
> > > > 2. for lyrics, make sure that "show thumbnail for lyrics" is disabled in settings.
> > > > 3. those 2 sliders work in the carousel view.
> > > > 
> > > > Screenrecorder-2024-07-28-19-02-58-392.mp4
> > > 
> > > 
> > > Offtopic but i dont have any option for fading edge in settings and also about carousel view something im missing?
> > 
> > 
> > Use modern player
> 
> Okay

Got it thanks
