### ISSUE TITLE
Useless Downloading indicators 

### ISSUE THREAD

**Issue by ksnprogrammer** [fast4x/RiMusic#2986]
### Steps to reproduce the bug

1.Search music and clicked download icon . then all songs of list showing downloading proses icon . 

### Expected behavior

Only downloading icon show select song 

### Actual behavior

But happen all songs showing downloading but few minutes after download one song .

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/47ff70aa-d11d-4fa4-af50-f522acf0ec5b

![Screenshot_20240728_185127_it fast4x rimusic](https://github.com/user-attachments/assets/197af197-7874-4e56-93a9-ffc445e044d2)

I'm very glad about your bug fixing react. keep  
 it anymore and make The app incredible . ❤️
Do your best . Good luck . we are waiting for new features and new creations
 

### RiMusic version

0.6.45.1

### Android version

Android 10

**Comment by fast4x** [comment]
Fixed, available from version 0.6.46
