### ISSUE TITLE
Star icon

### ISSUE THREAD

**Issue by Lllum** [fast4x/RiMusic#2989]
### Steps to reproduce the bug

Open the music player and long press the star icon in the bottom left

### Expected behavior

I don't even know what it's supposed to do 😭

### Actual behavior

Just turns off the app 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/7acd6d89-78d2-4023-b3a2-327a2d61130f

### RiMusic version

0.6.45.1

### Android version

14

**Comment by aneesh1122** [comment]
post the crash log

**Comment by Juggalage** [comment]
I've been able to reproduce the same bug, consistently here's my crash log.

2024-07-28T12:03:48.857:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 U6.m.a(SourceFile:230) 
	 w.A.b(SourceFile:34) 
	 y.f1.u(SourceFile:283) 
	 r7.a.l(SourceFile:9) 
	 J7.D.B(SourceFile:79) 
	 J7.g.o(SourceFile:105) 
	 J7.g.E(SourceFile:33) 
	 J7.g.l(SourceFile:17) 
	 C0.H.u(SourceFile:71) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:959) 
	 android.os.Handler.dispatchMessage(Handler.java:100) 
	 android.os.Looper.loopOnce(Looper.java:232) 
	 android.os.Looper.loop(Looper.java:317) 
	 android.app.ActivityThread.main(ActivityThread.java:8592) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by SureshTimma** [comment]
What is the use of star icon?

**Comment by aneesh1122** [comment]
> ### Steps to reproduce the bug
> 
> Open the music player and long press the star icon in the bottom left
> 
> ### Expected behavior
> 
> I don't even know what it's supposed to do 😭
> 
> ### Actual behavior
> 
> Just turns off the app 
> 
> ### Screenshots/Screen recordings
> 
> 
> https://github.com/user-attachments/assets/7acd6d89-78d2-4023-b3a2-327a2d61130f
> 
> 
> 
> ### Logs
> 
> _No response_
> 
> ### RiMusic version
> 
> 0.6.45.1
> 
> ### Android version
> 
> 14
> 
> ### Additional information
> 
> _No response_

Change the message type to essential. The player doesn't have the navigation bar that's why it's crashing.

**Comment by fast4x** [comment]
This is discover feature that removes liked and playlist song from radio... it's available and fixed in next version 0.6.46

**Comment by aneesh1122** [comment]
> This is discover feature that removes liked and playlist song from radio... it's available and fixed in next version 0.6.46

One thing to notice here is that modern smart message required bottom navigation bar and the player doesn't have it that's why the smart message crashed here.

**Comment by fast4x** [comment]
Yes, I replaced the defective library, improved everything and now it seems stable.

**Comment by aneesh1122** [comment]
> Yes, I replaced the defective library, improved everything and now it seems stable.

Thanks :)
