### ISSUE TITLE
Actualización aún rota.

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#2991]
### Steps to reproduce the bug

1. Agradezco el esfuerzo que pusieron para mejorar el uso pero desgraciadamente aún no puedo reproducir nada en mi dispositivo, no puedo realizar absolutamente nada.

### Expected behavior

Reproducción y acciónes sin problemas.

### Actual behavior

La actualización aún está completamente rota.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/3bb033a5-0e24-4e11-81ac-55e015222e68

### Logs

2024-07-28T11:27:12.146:	java.lang.NumberFormatException: For input string: "2
    "
	 java.lang.Integer.parseInt(Integer.java:797) 
	 java.lang.Integer.parseInt(Integer.java:915) 
	 b7.b1.h(SourceFile:1297) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 B7.a.l(SourceFile:1244) 
	 J.n0.h(SourceFile:123) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 j.h(SourceFile:143) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 T.R0.i(SourceFile:1441) 
	 e0.a.i(SourceFile:52) 
	 O.W.i(SourceFile:170) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.f2.a(SourceFile:113) 
	 T.V0.b(SourceFile:56) 
	 T.I0.i(SourceFile:214) 
	 e0.a.i(SourceFile:52) 
	 T.X0.i(SourceFile:258) 
	 e0.a.i(SourceFile:52) 
	 T.C0.a(SourceFile:52) 
	 B.s0.i(SourceFile:1462) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.q0.a(SourceFile:395) 
	 D.i.i(SourceFile:2526) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.U.a(SourceFile:616) 
	 J0.A1.i(SourceFile:250) 
	 e0.a.i(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.A1.i(SourceFile:213) 
	 e0.a.i(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.p.p(SourceFile:203) 
	 W.t.k(SourceFile:32) 
	 W.t0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.t.l(SourceFile:9) 
	 W.t.c(SourceFile:3) 
	 A6.i.b(SourceFile:1387) 
	 J0.x.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.B1.c(SourceFile:10) 
	 J0.B1.h(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 A6.i.b(SourceFile:1356) 
	 J0.x.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:22066) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3290) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2687) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9776) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:952) 
	 android.view.Choreographer.doFrame(Choreographer.java:882) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326) 
	 android.os.Handler.handleCallback(Handler.java:1000) 
	 android.os.Handler.dispatchMessage(Handler.java:104) 
	 android.os.Looper.loopOnce(Looper.java:242) 
	 android.os.Looper.loop(Looper.java:362) 
	 android.app.ActivityThread.main(ActivityThread.java:8407) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992) 

2024-07-28T11:27:16.810:	java.lang.NumberFormatException: For input string: "2
    "
	 java.lang.Integer.parseInt(Integer.java:797) 
	 java.lang.Integer.parseInt(Integer.java:915) 
	 b7.b1.h(SourceFile:1297) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 B7.a.l(SourceFile:1244) 
	 J.n0.h(SourceFile:123) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 j.h(SourceFile:143) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 T.R0.i(SourceFile:1441) 
	 e0.a.i(SourceFile:52) 
	 O.W.i(SourceFile:170) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.f2.a(SourceFile:113) 
	 T.V0.b(SourceFile:56) 
	 T.I0.i(SourceFile:214) 
	 e0.a.i(SourceFile:52) 
	 T.X0.i(SourceFile:258) 
	 e0.a.i(SourceFile:52) 
	 T.C0.a(SourceFile:52) 
	 B.s0.i(SourceFile:1462) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.q0.a(SourceFile:395) 
	 D.i.i(SourceFile:2526) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.U.a(SourceFile:616) 
	 J0.A1.i(SourceFile:250) 
	 e0.a.i(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.A1.i(SourceFile:213) 
	 e0.a.i(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.p.p(SourceFile:203) 
	 W.t.k(SourceFile:32) 
	 W.t0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.t.l(SourceFile:9) 
	 W.t.c(SourceFile:3) 
	 A6.i.b(SourceFile:1387) 
	 J0.x.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.B1.c(SourceFile:10) 
	 J0.B1.h(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 A6.i.b(SourceFile:1356) 
	 J0.x.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:22066) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3290) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2687) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9776) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:952) 
	 android.view.Choreographer.doFrame(Choreographer.java:882) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326) 
	 android.os.Handler.handleCallback(Handler.java:1000) 
	 android.os.Handler.dispatchMessage(Handler.java:104) 
	 android.os.Looper.loopOnce(Looper.java:242) 
	 android.os.Looper.loop(Looper.java:362) 
	 android.app.ActivityThread.main(ActivityThread.java:8407) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992) 

2024-07-28T11:27:23.820:	java.lang.NumberFormatException: For input string: "2
    "
	 java.lang.Integer.parseInt(Integer.java:797) 
	 java.lang.Integer.parseInt(Integer.java:915) 
	 b7.b1.h(SourceFile:1297) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 B7.a.l(SourceFile:1244) 
	 J.n0.h(SourceFile:123) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 j.h(SourceFile:143) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 T.R0.i(SourceFile:1441) 
	 e0.a.i(SourceFile:52) 
	 O.W.i(SourceFile:170) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.f2.a(SourceFile:113) 
	 T.V0.b(SourceFile:56) 
	 T.I0.i(SourceFile:214) 
	 e0.a.i(SourceFile:52) 
	 T.X0.i(SourceFile:258) 
	 e0.a.i(SourceFile:52) 
	 T.C0.a(SourceFile:52) 
	 B.s0.i(SourceFile:1462) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.q0.a(SourceFile:395) 
	 D.i.i(SourceFile:2526) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.U.a(SourceFile:616) 
	 J0.A1.i(SourceFile:250) 
	 e0.a.i(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.A1.i(SourceFile:213) 
	 e0.a.i(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.p.p(SourceFile:203) 
	 W.t.k(SourceFile:32) 
	 W.t0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.t.l(SourceFile:9) 
	 W.t.c(SourceFile:3) 
	 A6.i.b(SourceFile:1387) 
	 J0.x.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.B1.c(SourceFile:10) 
	 J0.B1.h(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 A6.i.b(SourceFile:1356) 
	 J0.x.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:22066) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3290) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2687) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9776) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:952) 
	 android.view.Choreographer.doFrame(Choreographer.java:882) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326) 
	 android.os.Handler.handleCallback(Handler.java:1000) 
	 android.os.Handler.dispatchMessage(Handler.java:104) 
	 android.os.Looper.loopOnce(Looper.java:242) 
	 android.os.Looper.loop(Looper.java:362) 
	 android.app.ActivityThread.main(ActivityThread.java:8407) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992) 

2024-07-28T11:27:38.917:	java.lang.NumberFormatException: For input string: "2
    "
	 java.lang.Integer.parseInt(Integer.java:797) 
	 java.lang.Integer.parseInt(Integer.java:915) 
	 b7.b1.h(SourceFile:1297) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 B7.a.l(SourceFile:1244) 
	 J.n0.h(SourceFile:123) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 j.h(SourceFile:143) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 T.R0.i(SourceFile:1441) 
	 e0.a.i(SourceFile:52) 
	 O.W.i(SourceFile:170) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.f2.a(SourceFile:113) 
	 T.V0.b(SourceFile:56) 
	 T.I0.i(SourceFile:214) 
	 e0.a.i(SourceFile:52) 
	 T.X0.i(SourceFile:258) 
	 e0.a.i(SourceFile:52) 
	 T.C0.a(SourceFile:52) 
	 B.s0.i(SourceFile:1462) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.q0.a(SourceFile:395) 
	 D.i.i(SourceFile:2526) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.U.a(SourceFile:616) 
	 J0.A1.i(SourceFile:250) 
	 e0.a.i(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.A1.i(SourceFile:213) 
	 e0.a.i(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.p.p(SourceFile:203) 
	 W.t.k(SourceFile:32) 
	 W.t0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.t.l(SourceFile:9) 
	 W.t.c(SourceFile:3) 
	 A6.i.b(SourceFile:1387) 
	 J0.x.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.B1.c(SourceFile:10) 
	 J0.B1.h(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 A6.i.b(SourceFile:1356) 
	 J0.x.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:22066) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3290) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2687) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9776) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:952) 
	 android.view.Choreographer.doFrame(Choreographer.java:882) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326) 
	 android.os.Handler.handleCallback(Handler.java:1000) 
	 android.os.Handler.dispatchMessage(Handler.java:104) 
	 android.os.Looper.loopOnce(Looper.java:242) 
	 android.os.Looper.loop(Looper.java:362) 
	 android.app.ActivityThread.main(ActivityThread.java:8407) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992) 

2024-07-28T11:27:45.250:	java.lang.NumberFormatException: For input string: "2
    "
	 java.lang.Integer.parseInt(Integer.java:797) 
	 java.lang.Integer.parseInt(Integer.java:915) 
	 b7.b1.h(SourceFile:1297) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 B7.a.l(SourceFile:1244) 
	 J.n0.h(SourceFile:123) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 j.h(SourceFile:143) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 T.R0.i(SourceFile:1441) 
	 e0.a.i(SourceFile:52) 
	 O.W.i(SourceFile:170) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.f2.a(SourceFile:113) 
	 T.V0.b(SourceFile:56) 
	 T.I0.i(SourceFile:214) 
	 e0.a.i(SourceFile:52) 
	 T.X0.i(SourceFile:258) 
	 e0.a.i(SourceFile:52) 
	 T.C0.a(SourceFile:52) 
	 B.s0.i(SourceFile:1462) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.q0.a(SourceFile:395) 
	 D.i.i(SourceFile:2526) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.U.a(SourceFile:616) 
	 J0.A1.i(SourceFile:250) 
	 e0.a.i(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.A1.i(SourceFile:213) 
	 e0.a.i(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.p.p(SourceFile:203) 
	 W.t.k(SourceFile:32) 
	 W.t0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.t.l(SourceFile:9) 
	 W.t.c(SourceFile:3) 
	 A6.i.b(SourceFile:1387) 
	 J0.x.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.B1.c(SourceFile:10) 
	 J0.B1.h(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 A6.i.b(SourceFile:1356) 
	 J0.x.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:22066) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3290) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2687) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9776) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:952) 
	 android.view.Choreographer.doFrame(Choreographer.java:882) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326) 
	 android.os.Handler.handleCallback(Handler.java:1000) 
	 android.os.Handler.dispatchMessage(Handler.java:104) 
	 android.os.Looper.loopOnce(Looper.java:242) 
	 android.os.Looper.loop(Looper.java:362) 
	 android.app.ActivityThread.main(ActivityThread.java:8407) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992) 

2024-07-28T11:27:49.517:	java.lang.NumberFormatException: For input string: "2
    "
	 java.lang.Integer.parseInt(Integer.java:797) 
	 java.lang.Integer.parseInt(Integer.java:915) 
	 b7.b1.h(SourceFile:1297) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 B7.a.l(SourceFile:1244) 
	 J.n0.h(SourceFile:123) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 j.h(SourceFile:143) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 T.R0.i(SourceFile:1441) 
	 e0.a.i(SourceFile:52) 
	 O.W.i(SourceFile:170) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.f2.a(SourceFile:113) 
	 T.V0.b(SourceFile:56) 
	 T.I0.i(SourceFile:214) 
	 e0.a.i(SourceFile:52) 
	 T.X0.i(SourceFile:258) 
	 e0.a.i(SourceFile:52) 
	 T.C0.a(SourceFile:52) 
	 B.s0.i(SourceFile:1462) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.q0.a(SourceFile:395) 
	 D.i.i(SourceFile:2526) 
	 e0.a.i(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.U.a(SourceFile:616) 
	 J0.A1.i(SourceFile:250) 
	 e0.a.i(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.A1.i(SourceFile:213) 
	 e0.a.i(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.p.p(SourceFile:203) 
	 W.t.k(SourceFile:32) 
	 W.t0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.t.l(SourceFile:9) 
	 W.t.c(SourceFile:3) 
	 A6.i.b(SourceFile:1387) 
	 J0.x.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.B1.c(SourceFile:10) 
	 J0.B1.h(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 A6.i.b(SourceFile:1356) 
	 J0.x.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:22066) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3290) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2687) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9776) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:952) 
	 android.view.Choreographer.doFrame(Choreographer.java:882) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326) 
	 android.os.Handler.handleCallback(Handler.java:1000) 
	 android.os.Handler.dispatchMessage(Handler.java:104) 
	 android.os.Looper.loopOnce(Looper.java:242) 
	 android.os.Looper.loop(Looper.java:362) 
	 android.app.ActivityThread.main(ActivityThread.java:8407) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992) 

### RiMusic version

0.6.45.1

### Android version

Android 14

### Additional information

Esperaré con paciencia la siguiente actualización, ¡gracias!

**Comment by aneesh1122** [comment]
Have you changed something in show next songs in player?

Do this, maybe this will solve the problem otherwise uninstall and then reinstall the app

https://github.com/user-attachments/assets/0d5b44fa-6cce-41b3-9b00-1f72f9181cdc

Don't press enter. Just put the value and leave it.

**Comment by fast4x** [comment]
I'll try to understand what is the problem

**Comment by fast4x** [comment]
feedback please error occur also with custom version?

**Comment by Alaneeedu** [comment]
> Descargar versión personalizada

Paso lo mismo, tuve que borrar la app y reinstalar, funciona pero no me deja personalizar del todo la app, tiene bugs por pequeños ratos, anoche decidí instalar una versión Antigua y prefiero la 0.6.41, agradezco que se esfuercen por brindarnos lo mejor pero al agregarle muchas cosas la app se congela mucho y se entiende, tiene muchas novedades que no cualquier reproductor gratuito brinda pero de tantos cambios esto llega a pasar. ¡Gracias por todo! Estaré en espera de uns buena versión 🙇🏽‍♂️
