### ISSUE TITLE
New interface is very hard to read (black text over a dark background)

### ISSUE THREAD

**Issue by githubisviolatingthegpl** [fast4x/RiMusic#2993]
### Steps to reproduce the bug

1. Play some music where the album art is kind of dark (like dark red)
    * example: https://music.youtube.com/watch?v=OZpo1hzzCoU
2. Time stamp and some other interface elements are black on dark read and are very difficult to read (see screenshot)
![Screenshot_20240728-140210](https://github.com/user-attachments/assets/4b4f5fe8-ed0b-478e-bcce-fe868d7b295c)

### Expected behavior

The best-case scenario would be to use some kind of outline font that is equally readable with any kind of background. Otherwise, have some kind of black bar or other background element to make the text more readable.

### Actual behavior

The timestamps are very difficult to read, even with glasses on.

### RiMusic version

0.6.44

### Android version

Android 14

**Comment by githubisviolatingthegpl** [comment]
Just FYI, I found that I could change the background in settings. :D

**Comment by aneesh1122** [comment]
> Just FYI, I found that I could change the background in settings. :D

while you were there did you also find the option to have outline and bottom gradient which improves visibility?

**Comment by fast4x** [comment]
Can customize all...
