### ISSUE TITLE
Adjust the smart message/toast box size according to the text length

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#2995]
### Description

![IMG_20240729_024006](https://github.com/user-attachments/assets/ca20aafb-4c87-4369-93ca-c04df2ef50df)

Please keep the box size dynamic so that it can get big or small according to the text length.

### Suggested Solution

Change box size based on text length

**Comment by fast4x** [comment]
Where is this delete feature?

**Comment by fast4x** [comment]
Implemented, available from version 0.6.46

**Comment by aneesh1122** [comment]
> Where is this delete feature?

Sorry for being late. This smart message appears when the song is deleted from a playlist using swipe gestures.

You've figured it out and implemented it already. Thanks man.

**Comment by aneesh1122** [comment]
> Where is this delete feature?

Sorry for being late. This smart message appears when the song is deleted from a playlist using swipe gestures.

You've figured it out and implemented it already. Thanks man.
