### ISSUE TITLE
Annoying error when clicking back on the albums and singles tab

### ISSUE THREAD

**Issue by obitopy** [fast4x/RiMusic#2996]
### Steps to reproduce the bug

in the albums or singles tab when you download everything and enter the album or single and then you go back everything comes out and returns to the artists tab and you have to download everything to go back to that album or single

### Expected behavior

https://github.com/user-attachments/assets/c54bdf92-4a7c-4f88-afc4-86eecdb522ab

### Actual behavior

https://github.com/user-attachments/assets/b70319e0-b01e-4371-9862-43d295b54fa5

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/ad2aaf36-6ba9-428d-9266-956e582c4c5a

### RiMusic version

v.0.6.45.1

### Android version

Android 13

### Additional information

in the albums or singles tab when you download everything and enter the album or single and then you go back everything comes out and returns to the artists tab and you have to download everything to go back to that album or single

https://github.com/user-attachments/assets/c6988c37-17f9-4223-a026-e1f89f6fe48a

**Comment by fast4x** [comment]
Will be improved in the future

**Comment by obitopy** [comment]
The error continues, they just need to correct that so that the application is perfect, I'll show you an example of what I'm referring to.

https://github.com/user-attachments/assets/71c1202d-5afa-4da4-a806-63a85476f871


https://github.com/user-attachments/assets/74dfe5d7-63e9-4700-a0b7-14eafa408f48

**Comment by fast4x** [comment]
Yes i understand, it will be improved when navigation system will be stable.
