### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by jssj0** [fast4x/RiMusic#2997]
### Steps to reproduce the bug

Simply running the player. Listening to music causes song stuttering and crashing.

### Expected behavior

Music should play smoothly and the player should not crash repeatedly.

### Actual behavior

Song stuttering and app crashing.

### RiMusic version

0.6.45.1

### Android version

Android 13

### Additional information

I am not able to provide other information because the problem can't be tracked, or I am not aware of how to track it. But this was not a problem in version 0.6.44. since 0.6.45 there have been issues.

**Comment by lebgdeyoutube** [comment]
there is a crash when displaying pop UPs (which is not displayed)

**Comment by fast4x** [comment]
Set message type to essential in ui settings, try if crash.

**Comment by jssj0** [comment]
Here is a bug crash report. Maybe this will help:

2024-07-29T02:37:56.020:	java.lang.NumberFormatException: For input string: "1
    "
	 java.lang.Integer.parseInt(Integer.java:797) 
	 java.lang.Integer.parseInt(Integer.java:915) 
	 S6.t0.h(SourceFile:453) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1480) 
	 androidx.compose.animation.a.f(SourceFile:225) 
	 androidx.compose.animation.a.b(SourceFile:429) 
	 e7.o.a(SourceFile:802) 
	 C6.k.i(SourceFile:306) 
	 e0.a.i(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 g0.f.c(SourceFile:149) 
	 D3.b.m(SourceFile:55) 
	 e0.a.e(SourceFile:44) 
	 e0.a.m(SourceFile:9) 
	 J.n0.h(SourceFile:253) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1480) 
	 P6.q.i(SourceFile:307) 
	 e0.a.i(SourceFile:52) 
	 f3.c.b(SourceFile:958) 
	 f3.c.a(SourceFile:321) 
	 O6.G.h(SourceFile:457) 
	 e0.a.d(SourceFile:44) 
	 A6.s.i(SourceFile:199) 
	 W.p.M(SourceFile:438) 
	 W.p.T(SourceFile:137) 
	 W.p.p(SourceFile:244) 
	 W.p.K(SourceFile:32) 
	 W.t.w(SourceFile:22) 
	 W.t0.t(SourceFile:102) 
	 W.r0.b(SourceFile:515) 
	 J0.d0.doFrame(SourceFile:7) 
	 J0.b0.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:923) 
	 android.view.Choreographer.doFrame(Choreographer.java:847) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8779) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

RiMusic crashing whenever I try to open the Player Appearance in Settings.

How do I role back to version 0.6.44????

**Comment by fast4x** [comment]
Ok nice thanks for the log

**Comment by jssj0** [comment]
Now the app crashing for everything...Is it possible for me to role back to version 0.6.44 without losing all my music???

**Comment by fast4x** [comment]
Wait today i send to you a custom version please try if fixed

**Comment by jssj0** [comment]
Thank you.

**Comment by fast4x** [comment]
Download a custom version please, try if it work, thanks
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by jssj0** [comment]
It works! Thank you! 👍

**Comment by fast4x** [comment]
wow Amazing thanks

**Comment by jssj0** [comment]
Yes, the music still stutters at the beginning, midway, and at the end of songs playing. Also, a strange dragging sound while music plays, and rapid speed increase at beginning of song play as well. It seems almost as if after version 0.6.44 there are strange new issues. But at least it has not crashed so far.

**Comment by jssj0** [comment]
It is already set to disabled. I still have the same issues.

**Comment by fast4x** [comment]
try, enable and re disable

**Comment by jssj0** [comment]
Tried that before. But tried it again at your suggestion and it is still speeding up and randomly stuttering.

**Comment by fast4x** [comment]
control the playback values from the menu in the player, press play button and change preferences

**Comment by jssj0** [comment]
I was just doing that when I opened this and saw you suggested I should try that. So far, it looks like that may have done the trick. I will still need to monitor the app as I listen to more music. I will update later today. Thanks for your help.

**Comment by jssj0** [comment]
I uninstalled and rolled back to version 0.6.44. No matter what I tried the music kept stuttering, scraping sounds at end of songs, spurts of speed ups during playback, hiccups at start of songs and other weirdness at the end of songs.

I lost all my downloads but thankfully I had an old database backup from July 16th. So not all of my song titles and Playlists were lost.

I'm not sure if I want to upgrade after version 0.6.44 because now I am terrified that this will be a problem for me. Since I don't know why it could not be resolved. Is it my phone? Which is an old Samsung A03s reissued in 2023. Or is it something else I am not aware of? I will stick with version 0.6.44. Everything is back to normal. Except for the Settings app. It appears that I can't move the bottom bar to the left side where I always had it for UI, Player Appearance, etc. It stays at the bottom no matter what. There used to be a setting to switch left or right side of screen. It's not longer there. Always something, lol. At least the player plays my music normally again. That's all I wanted. Thanks for the assist as much as you could. I appreciated the custom version.

**Comment by aneesh1122** [comment]
![Screenshot_2024-07-30-15-01-55-633_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/b334bfdc-e733-479c-98cf-99d0c9b12352)

Disable this and try again

**Comment by jssj0** [comment]
That may have been a big culprit. I had that setting enabled in version 0.6.45.1

I decided to leave it turned off though when I rolled back to 0.6.44 even though it worked fine in this version.

**Comment by aneesh1122** [comment]
> That may have been a big culprit. I had that setting enabled in version 0.6.45.1
> 
> I decided to leave it turned off though when I rolled back to 0.6.44 even though it worked fine in this version.

So try the new custom version and keep this setting off and see if the problem is solved?

**Comment by jssj0** [comment]
> > That may have been a big culprit. I had that setting enabled in version 0.6.45.1
> > I decided to leave it turned off though when I rolled back to 0.6.44 even though it worked fine in this version.
> 
> So try the new custom version and keep this setting off and see if the problem is solved?

I will not be reinstalling any newer versions on this phone as I am switching phones. Honestly I do not trust updating because I had so many issues. If what you suggested was even really the culprit, as I was already in the process of trying your posted suggestion, then I will test it on my new phone with that setting turned on with the updated version and we shall see.

**Comment by jssj0** [comment]
I've decided to update again. Only because as a tech person, I felt I should try to help in resolving this issue because it was never "officially" resolved on my end.

I have reinstalled version 0.6.45.1 (custom) that Fastx sent me. So far the sound issue has disappeared, but the app is now crashing intermittently. I have turned on the crash report feature and will post the crash data when it happens again.

**Comment by jssj0** [comment]
Here is the latest crash log:

2024-07-30T23:21:40.284:	java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	 t0.k.a(SourceFile:125) 
	 q0.f.onPreDraw(SourceFile:34) 
	 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1121) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4442) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:923) 
	 android.view.Choreographer.doFrame(Choreographer.java:852) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8779) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

2024-07-30T23:34:24.971:	java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	 t0.k.a(SourceFile:125) 
	 q0.f.onPreDraw(SourceFile:34) 
	 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1121) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4442) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:923) 
	 android.view.Choreographer.doFrame(Choreographer.java:852) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8779) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

...Along with:

2024-07-30 21:26:06:202 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-30 21:38:46:961 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-30 23:28:10:652 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-30 23:34:32:579 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs

I hope this helps.

**Comment by aneesh1122** [comment]
> Here is the latest crash log:
> 
> 2024-07-30T23:21:40.284:	java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
> 	 t0.k.a(SourceFile:125) 
> 	 q0.f.onPreDraw(SourceFile:34) 
> 	 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1121) 
> 	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4442) 
> 	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116) 
> 	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885) 
> 	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301) 
> 	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309) 
> 	 android.view.Choreographer.doCallbacks(Choreographer.java:923) 
> 	 android.view.Choreographer.doFrame(Choreographer.java:852) 
> 	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283) 
> 	 android.os.Handler.handleCallback(Handler.java:942) 
> 	 android.os.Handler.dispatchMessage(Handler.java:99) 
> 	 android.os.Looper.loopOnce(Looper.java:226) 
> 	 android.os.Looper.loop(Looper.java:313) 
> 	 android.app.ActivityThread.main(ActivityThread.java:8779) 
> 	 java.lang.reflect.Method.invoke(Native Method) 
> 	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
> 	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 
> 
> 2024-07-30T23:34:24.971:	java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
> 	 t0.k.a(SourceFile:125) 
> 	 q0.f.onPreDraw(SourceFile:34) 
> 	 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1121) 
> 	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4442) 
> 	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116) 
> 	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885) 
> 	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301) 
> 	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309) 
> 	 android.view.Choreographer.doCallbacks(Choreographer.java:923) 
> 	 android.view.Choreographer.doFrame(Choreographer.java:852) 
> 	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283) 
> 	 android.os.Handler.handleCallback(Handler.java:942) 
> 	 android.os.Handler.dispatchMessage(Handler.java:99) 
> 	 android.os.Looper.loopOnce(Looper.java:226) 
> 	 android.os.Looper.loop(Looper.java:313) 
> 	 android.app.ActivityThread.main(ActivityThread.java:8779) 
> 	 java.lang.reflect.Method.invoke(Native Method) 
> 	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
> 	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 
> 
> ...Along with:
> 
> 2024-07-30 21:26:06:202 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
> 2024-07-30 21:38:46:961 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
> 2024-07-30 23:28:10:652 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
> 2024-07-30 23:34:32:579 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
> 
> I hope this helps.

When does it exactly happen? Is it random?

**Comment by jssj0** [comment]
Yes, random. This time I was navigating back into the app and once I did it crashed. The previous time, before I enabled the crash log, it crashed while a song was paused on the open screen.

**Comment by jssj0** [comment]
I am still experiencing random crashing. Not sure why. If it helps I can turn back on the crash log in settings and keep posting each crash report. Otherwise I am at a loss.

The music is playing without issue so I am glad for that. Hopefully the next update will fix the crashing.
