### ISSUE TITLE
No deja entrar al menú de apariencia ni deja abrir el reproductor

### ISSUE THREAD

**Issue by Alextar117** [fast4x/RiMusic#2998]
### Steps to reproduce the bug

Abra el menu de configuración y abre apariencia, con el otro solo abre el reproductor

### Expected behavior

Que pueda cambiar la apariencia y abrir el reproductor

### Actual behavior

Deja de funcionar la aplicación 

### RiMusic version

Última version

### Android version

Android 14

**Comment by fast4x** [comment]
I don't understand
