### ISSUE TITLE
When toggle lyrics button app get crashed 

### ISSUE THREAD

**Issue by Gauravchaubey66** [fast4x/RiMusic#3001]
### Steps to reproduce the bug

1. Play any song
2. Toggle lyrics
3. Change song

https://github.com/user-attachments/assets/4d4ba802-b8f0-48d8-8a50-26fc2deb282e

### Expected behavior

This should show lyrics and shouldn't crash 

### Actual behavior

It's not showing lyrics and getting crash

### RiMusic version

0.6.45.1

### Android version

Android 13

### Additional information

I tried again reinstalling app but still its happening

**Comment by fast4x** [comment]
Require that you paste here RiMusic log, please enable in miscellaneous settings and after crash paste log here.

**Comment by Gauravchaubey66** [comment]
> Require that you paste here RiMusic log, please enable in miscellaneous settings and after crash paste log here.
2024-07-29T14:35:39.432:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.L.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:223) 
	 android.os.Looper.loop(Looper.java:324) 
	 android.app.ActivityThread.main(ActivityThread.java:8407) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1059)

**Comment by Gauravchaubey66** [comment]
2024-07-29T14:35:39.432:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.L.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:223) 
	 android.os.Looper.loop(Looper.java:324) 
	 android.app.ActivityThread.main(ActivityThread.java:8407) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1059)

**Comment by fast4x** [comment]
Try to set message type to essential in ui settings

**Comment by fast4x** [comment]
Download a custom version please, try if it work, thanks
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Gauravchaubey66** [comment]
> Download a custom version please, try if it work, thanks
> https://github.com/fast4x/RiMusic/tree/master/customVersion

I don't know why but unable to download custom version 😑

**Comment by Gauravchaubey66** [comment]
@fast4x I don't know that this is implemented like this or its a bug but when any song hasn't lyrics it's showing nothing 
https://github.com/user-attachments/assets/0b12d53a-e661-4173-9bd1-74a15a743b21

**Comment by Gauravchaubey66** [comment]
And crashed issue is fixed its not crashing I don't know how 😄

**Comment by fast4x** [comment]
perfect, thanks

**Comment by fast4x** [comment]
I'll check it
