### ISSUE TITLE
Setting the automatic timer to a song of 1 hour or more stops the application.

### ISSUE THREAD

**Issue by ZandrexV** [fast4x/RiMusic#3002]
### Steps to reproduce the bug

1. Go play a song that lasts an hour or more (for example: relaxing music) 
2. Set the automatic timer at any time 
3. The app will crash (and be careful, because that doesn't happen with short songs)

### Expected behavior

That the automatic timer can be set as before this update.

### Actual behavior

It crashes when setting the timer to a long song.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/278dec41-b8b5-4112-a278-473ede80a21b

### RiMusic version

v0.6.45.1

### Android version

Android 6.1 & Android 8.1

**Comment by fast4x** [comment]
Require that you paste here RiMusic log, please enable in miscellaneous settings and after crash paste log here.

**Comment by ZandrexV** [comment]
> Requiere que pegues aquí el registro de RiMusic, habilítalo en configuraciones varias y después de la falla, pega el registro aquí.


2024-07-29T06:31:23.701:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 B7.a.l(SourceFile:162) 
	 b7.s0.i(SourceFile:72) 
	 W.p.M(SourceFile:438) 
	 W.p.T(SourceFile:137) 
	 W.p.p(SourceFile:244) 
	 W.p.K(SourceFile:32) 
	 W.t.w(SourceFile:22) 
	 W.t0.t(SourceFile:102) 
	 W.r0.b(SourceFile:515) 
	 J0.d0.doFrame(SourceFile:7) 
	 J0.b0.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:909) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:686) 
	 android.view.Choreographer.doFrame(Choreographer.java:619) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
	 android.os.Handler.handleCallback(Handler.java:739) 
	 android.os.Handler.dispatchMessage(Handler.java:95) 
	 android.os.Looper.loop(Looper.java:148) 
	 android.app.ActivityThread.main(ActivityThread.java:7406) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ZandrexV** [comment]
@fast4x I downloaded the customized version and I see that this error does not appear. Have you fixed it from there first?
![Screenshot_20240729-065504](https://github.com/user-attachments/assets/cc60b7cd-9f30-4f93-8f47-12715e0473a6)

**Comment by ZandrexV** [comment]
But yes, when entering and exiting the application I get the time of the video on the timer and not the time I set as preference.
![Screenshot_20240729-065846](https://github.com/user-attachments/assets/dee94758-1737-4de1-82fd-dafbd2060678)

**Comment by fast4x** [comment]
ok
