### ISSUE TITLE
Option For Stream From Spotify 

### ISSUE THREAD

**Issue by Ashubnx** [fast4x/RiMusic#3003]
### Description

We can use playlist saved from Spotify

### Suggested Solution

Maybe you can use Spotify web or web SDK don't know much about bt surely it would be helpfull

### Alternatives

Some of mg playlist saved in Spotify it would be helpfull to use it in RIMUSIC too.

### Additional Context

If the playlist support can't be added just try to have Spotify web stream support coz some songs doesnt appear on youtube

**Comment by fast4x** [comment]
You must transfer Spotify playlists to YouTube music, after you can share and import in RiMusic
