### ISSUE TITLE
Integrate Shazam

### ISSUE THREAD

**Issue by The-Annie** [fast4x/RiMusic#3008]
### Description

Integrate Shazam into the song search bar so we can immediately analyze the song there and the name of the song came up in the search

### Suggested Solution

I described everything in detail in the description

**Comment by ALMIGHTY-VC** [comment]
> ### Description
> Integrate Shazam into the song search bar so we can immediately analyze the song there and the name of the song came up in the search
> 
> ### Suggested Solution
> I described everything in detail in the description
> 
> ### Alternatives
> _No response_
> 
> ### Additional Context
> _No response_

I think it can work more like a plugin thing because not everybody needs it and also increases the apps storage making it less lightweight and he  has already starred a git repo audire which i think hes working on

**Comment by aneesh1122** [comment]
> he has already starred a git repo audire which i think hes working on

Bro even knows what his crush ate for dinner 😂

**Comment by fast4x** [comment]
Unfortunately is a payment service and require login.

**Comment by ALMIGHTY-VC** [comment]
> > he has already starred a git repo audire which i think hes working on
> 
> Bro even knows what his crush ate for dinner 😂

Nuh nuh i follow means github has a inbuilt activity stalker XD
