### ISSUE TITLE
Cache (by download) don't working

### ISSUE THREAD

**Issue by dtkiro** [fast4x/RiMusic#301]
### Steps to reproduce the bug

1. Make sure cache (by download) is enabled in settings
2. Create a playlist
3. Add songs
4. Download the songs in the playlist
5. Disconnect from the internet
6. Close RiMusic
7. Open RiMusic and try playing the downloaded songs in the playlist in the "download" tab

### Expected behavior

Songs are expected to play when offline.

### Actual behavior

RiMusic displays a message that there was an unknown error when trying to play songs without a connection.

### Screenshots/Screen recordings

I apologize for the quality of the video... 

https://github.com/fast4x/RiMusic/assets/123248061/cfd0270a-5d5f-4cf1-b12a-9cc2785effd2

### RiMusic version

0.6.15.1

### Android version

Android 13

### Additional information

I don't know if there is any influence, but I use a custom rom, I use the **Project Elixir**.

**Comment by fast4x** [comment]
Have you test version 0.6.15.1 ?

**Comment by fast4x** [comment]
Try this:
- enable player cache
- restart RiMusic
- create playlist
- add songs and download

Send me feedback please.

**Comment by dtkiro** [comment]
> Have you test version 0.6.15.1 ?

Yes! The test was carried out on the most current version, I ended up making a mistake when typing the version number, I apologize for the mistake.

**Comment by dtkiro** [comment]
> Try this:
> - enable player cache
> - restart RiMusic
> - create playlist
> - add songs and download
> 
> Send me feedback please.

Okay, I'll try that!

**Comment by dtkiro** [comment]
> Try this:
> - enable player cache
> - restart RiMusic
> - create playlist
> - add songs and download
> 
> Send me feedback please.

Hey, here again! Here is the real-time test:

https://github.com/fast4x/RiMusic/assets/123248061/3a41030a-d869-418a-97e0-87f2203ed755

**Comment by fast4x** [comment]
Nice, I'll check It thanks

**Comment by dtkiro** [comment]
> Nice, I'll check It thanks

Hey, I have a new update! After trying a few things, I realized that the attachment issue from my previous answer... Even though RiMusic displays that the songs are not downloaded, just go to the settings and open the "cache by player" options and click on the one that is already selected, the downloaded songs will be possible to listen to offline after that.

**Comment by fast4x** [comment]
may be that the problem was related to that setting.
