### ISSUE TITLE
[Feature]: Make Playlists visible when going to a youtube.com/channel/ URL

### ISSUE THREAD

**Issue by Ao1Pointblank** [fast4x/RiMusic#3010]
### Description

When using the Go to Link search option, it does allow non-artist channels to be searched and selected. 
This *would* be very handy for importing multiple playlists from friends' (or your own) youtube channel, **IF** the channel page showed playlists (yes, they are public playlists)

### Suggested Solution

surely there is a way to support non-artist/non-"topic" channels as well, and import them from links such as:
``https://www.youtube.com/channel/ID`` or
``https://www.youtube.com/@USERNAME``

### Additional Context

![Screenshot_20240729-101335](https://github.com/user-attachments/assets/99813aa6-73a1-4853-aac5-b128c3f7509e)

**Comment by fast4x** [comment]
Implemented partially only channel it's possible for now.
Available from version 0.6.46
