### ISSUE TITLE
Device equalizer turns off when changing songs

### ISSUE THREAD

**Issue by guerreropirata99** [fast4x/RiMusic#3011]
### Steps to reproduce the bug

1. Changing songs manually deactivates the device's equalizer

### Expected behavior

When changing songs, the device's equalizer should remain activated.

### Actual behavior

It happens when changing songs manually in the player

### RiMusic version

All versions

### Android version

Android 12

**Comment by AstroLightz** [comment]
This seems to apply to the "Playback Audio" slider as well.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.46
