### ISSUE TITLE
Fade Audio is "disabled", but still enabled (~100ms)

### ISSUE THREAD

**Issue by ru4sdevil** [fast4x/RiMusic#3013]
### Steps to reproduce the bug

1. Go to settings-> Ui -> Player -> Fade Audio
2. Change to "Disabled"
3. Play any song, preferably without delays at the start

### Expected behavior

There should be no audio fading when "Disabled" is selected

 

### Actual behavior

Fading is audible

### RiMusic version

0.6.45.1

### Android version

Android 12 (MIUI 14)

**Comment by RevanthSurapaneni** [comment]
Same issue here

**Comment by fast4x** [comment]
Ok I'll try to fix

**Comment by fast4x** [comment]
Fixed, available from version 0.6.46
