### ISSUE TITLE
[Help needed]: How does the "for you", "by most played song" section work?

### ISSUE THREAD

**Issue by frenchy82** [fast4x/RiMusic#3015]
### Description

Thank you for this great software that I have been using for a week, a real pleasure!

I have not found any help for my question which must surely seem very basic to you

I do not understand how the selection "for you", "most played song" works
I have the impression that this represents the last songs listened  or the most listened songs during the last use.

### Suggested Solution

Shouldn't it be the most listened to since the beginning of RiMusic use or since a specific period(week, month ...)? 

Thank you for your help

**Comment by twistios** [comment]
I don't know what it is exactly supposed to do, but I can tell you a bit about what it does.

Currently the app does not use number of plays of a song but instead the amount of time listened to a song. So if a song is long then it has higher weight.

It seems like it shows the song that is most played for that day.

**Comment by fast4x** [comment]
Hi, your question is interesting, I'll check it

**Comment by frenchy82** [comment]
Thanks a lot !

**Comment by fast4x** [comment]
Fixed, available from version 0.6.46
