### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by effessgee** [fast4x/RiMusic#3017]
### Steps to reproduce the bug

When I pulled up the lyrics. 

### Expected behavior

Should relay lyrics with the song. 

### Actual behavior

The app crashed, abruptly closed and wiped off the screen. 

### RiMusic version

Latest, updated yesterday. 

### Android version

Android 12

### Additional information

It's happening more frequently now after the update. Should I reinstall another version for Android 12? Any suggestions?

**Comment by twistios** [comment]
Please goto settings, enable debug log. Exit the app and open the app again. Reproduce the crash, then go to the debug section and past crash log here.

**Comment by twistios** [comment]
Probably you should just try the custom  version. It fixes some issue related to crashing with lyrics.
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by ALMIGHTY-VC** [comment]
A10 user here the normalnversion also did the same to me but the custom version works perfectly fine
