### ISSUE TITLE
Salvar download em cartão de memória ou pendrive 

### ISSUE THREAD

**Issue by alexsprado** [fast4x/RiMusic#3018]
### Description

Queria saber se existe a possibilidade de salvar os downloads em mídia externa (cartão de memória ou pendrive por exemplos), ajudaria muito quem tem pouco espaço de armazenamento nativo

### Suggested Solution

Queria saber se existe a possibilidade de salvar os downloads em mídia externa (cartão de memória ou pendrive por exemplos), ajudaria muito quem tem pouco espaço de armazenamento nativo

### Alternatives

Queria saber se existe a possibilidade de salvar os downloads em mídia externa (cartão de memória ou pendrive por exemplos), ajudaria muito quem tem pouco espaço de armazenamento nativo

### Additional Context

Queria saber se existe a possibilidade de salvar os downloads em mídia externa (cartão de memória ou pendrive por exemplos), ajudaria muito quem tem pouco espaço de armazenamento nativo

**Comment by fast4x** [comment]
Hi, unfortunately isn't not possible
