### ISSUE TITLE
Songs in "Offline" playlist don't load on app startup

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#3019]
### Steps to reproduce the bug

1. Have "Cache" section of songs-menu selected
2. Close app
3. Start app

### Expected behavior

The songs are loaded.

### Actual behavior

The cached songs are not loaded. They are loaded when one first switches to for example "Favorites" first, then when returned, the songs are loaded.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/dc8d3b82-2d30-497a-b039-29f68acb104b

### RiMusic version

0.6.45.1 custom version

### Android version

14

### Additional information

This bug exists for many versions now.
I started to debug it. The reason why it does not work is that `binder` is `null` in the filter-part of the section.
When one returns to "Cache" again, `binder` is not `null` anymore.

**Comment by twistios** [comment]
I don't yet understand when `binder` gets non-null. For example if one does the same steps with "Favorites", the `binder` is also `null`, but when switching to `cache` the `binder` is now non-null. Somewhere between this, `binder` gets non-null.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.46.
Your intuition was correct

**Comment by twistios** [comment]
The same issue seems to be with the "downloaded" tab. It is now a new variant: on start it shows the downloaded and then after switching of tabs also the cached songs are shown.
