### ISSUE TITLE
Crashed when switch lyrics to karaoke

### ISSUE THREAD

**Issue by hilmymajid791** [fast4x/RiMusic#3021]
### Steps to reproduce the bug

just enable debug in app settings

### Expected behavior

Enable lyrics (karaoke) from lyrics setting

### Actual behavior

App crashed when i switch to lyrics(karaoke)

### Logs

2024-07-30T08:32:50.821:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.K.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:959) 
	 android.os.Handler.dispatchMessage(Handler.java:100) 
	 android.os.Looper.loopOnce(Looper.java:232) 
	 android.os.Looper.loop(Looper.java:317) 
	 android.app.ActivityThread.main(ActivityThread.java:8501) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) 

### RiMusic version

v0.6.45.1

### Android version

Android 14

**Comment by fast4x** [comment]
Today i send you a custom version to try

**Comment by fast4x** [comment]
Try new custom version, enable in ui settings pause on volume zero and change songs with volume keys.
and verify if crash occur inside lyrics or in other point...
thanks
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by faustaahmad** [comment]
Can confirm Syncronized lyrics working on CustomVersion
~~just the popup feels wierd unlike the past version, perhaps lacking font weight/semi-bold idk~~

**Comment by fast4x** [comment]
Amazing thanks for feedback

**Comment by Latinlee** [comment]
Same problem.



2024-07-30T16:31:29.856:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 J5.a.u(SourceFile:38) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 G1.a.run(SourceFile:173) 
	 Q7.k.run(SourceFile:3) 
	 Q7.a.run(SourceFile:96)

**Comment by twistios** [comment]
@Latinlee this is not exactly the same problem as it is a different error. See also #2851.
