### ISSUE TITLE
Shuffle button seems to be allways activate on the player (autoshuffle in player)

### ISSUE THREAD

**Issue by frenchy82** [fast4x/RiMusic#3023]
### Steps to reproduce the bug

Choose a music, goto the player
On the player the shuffle button is lit whether you are using it or not.

### Expected behavior

If you have not selected random music, the shuffle button shoud be gray as the others buttons

### Actual behavior

Same as description 

### RiMusic version

0.6.45.1

### Android version

Android 12

**Comment by aneesh1122** [comment]
Shuffle is not a toggle. It is a button which activates every time you choose it.

**Comment by frenchy82** [comment]
Sorry, but in English it's not so easy for me :)
But it's just a problem of appearance. Whether you activate or not the random, the button keeps the same appearance, the same color, so we can't know if it's activated or not.

If we take the loop button for example, there is no this visual problem

**Comment by aneesh1122** [comment]
> Sorry, but in English it's not so easy for me :)
> But it's just a problem of appearance. Whether you activate or not the random, the button keeps the same appearance, the same color, so we can't know if it's activated or not.
> 
> If we take the loop button for example, there is no this visual problem

You can't activate the shuffle. You can just use it as many times as you want to rearrange songs.

For example, let's say a machine has 5 balls of different colors and there's a 'shuffle' button on it. Every time you press the 'shuffle' button the balls will be rearranged. The balls won't be continuously shuffled. It's a button which does things one time.

**Comment by frenchy82** [comment]
OK, i do understand.
thanks for this explanation

**Comment by fast4x** [comment]
In fact, there is an autoshuffle function but the player does not have it. It’s present in the player in the notification area. In that case it can be activated or deactivated. I implement it!

**Comment by aneesh1122** [comment]
> In fact, there is an autoshuffle function but the player does not have it. It’s present in the player in the notification area. In that case it can be activated or deactivated. I implement it!

What does autoshuffle exactly do?

**Comment by fast4x** [comment]
When enabled, shuffle next song...

**Comment by aneesh1122** [comment]
> When enabled, shuffle next song... 

So everytime song changes it will shuffle the songs next in queue?
