### ISSUE TITLE
Tap to show unsynchronized lyrics and vice versa

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#3028]
### Description

Previous version of RiMusic already has this feature. It might've been removed when the new expanded lyrics got implemented. Currently, when there is no synchronized lyrics, the screen stays blank and you have to change it to unsynchronized lyrics through the three dot menu.

### Suggested Solution

Add a clickable text to switch to unsynchronized lyrics when synchronized lyrics are unavailable and vice versa.
![Untitled4_20240730235109](https://github.com/user-attachments/assets/4b863a9d-686c-48ad-a2d2-1d20e48ad3ed)

### Alternatives

When synchronized lyrics aren't available, automatically switch to unsynchronized lyrics and vice versa.

**Comment by fast4x** [comment]
Lyrics section have many secrets placed, discover it with new layout, not use old layout. It's hour to change with new lyrics features.

**Comment by cMattw** [comment]
> Lyrics section have many secrets placed, discover it with new layout, not use old layout. It's hour to change with new lyrics features.
> 
> 

I am using the new layout, and it removed the feature that was in previous versions of RiMusic. ![Screenshot_2024-07-31-11-19-44-214_it.fast4x.rimusic.jpg](https://github.com/user-attachments/assets/b263cf63-b9ab-48fc-95b9-8bc395a22b6b)

I'm talking about this. It's not available in the new layout. It would just be really convenient if you brought the click to show unsynchronized lyrics feature back.

**Comment by cMattw** [comment]
> [Screenshot_2024-07-31-11-19-44-214_it.fast4x.rimusic.jpg](https://github.com/user-attachments/assets/b263cf63-b9ab-48fc-95b9-8bc395a22b6b)

this was RiMusic version 0.6.38
