### ISSUE TITLE
En última versión de RiMusic v0.6.45.1 by fast4x, al iniciar la reproducción de la letra de una canción, se cierra RiMusic.

### ISSUE THREAD

**Issue by antoqueH** [fast4x/RiMusic#3031]
### Steps to reproduce the bug

Pulso en comando reproducir letra de una canción 

### Expected behavior

Se reproduce la letra de la canción 

### Actual behavior

Se cierra RiMusic

### RiMusic version

v0.6.45.1 

### Android version

13

**Comment by aneesh1122** [comment]
custom version

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion
