### ISSUE TITLE
Crash and Unstable on Xiaomi phones

### ISSUE THREAD

**Issue by BeepStation** [fast4x/RiMusic#3033]
### Steps to reproduce the bug

1st bug :Go to downloads and click on any song 
2nd bug :When you click on subtitles on any song

### Expected behavior

1. When you click on the downloaded song it plays 
2. When you click on the lyrics it shows lyrics

### Actual behavior

1. Clicking on the downloaded song  it does not play
2. Clicking on the lyrics causes the app to crash

### Screenshots/Screen recordings

![IMG_20240731_000329](https://github.com/user-attachments/assets/675d433a-14c9-4aa6-ae5c-91164659a74f)

### RiMusic version

0.6.45.1

### Android version

Android 14

### Additional information

Device Name: Redmi 12C
Chip: Helio G85
Android 14 
HyperOS 1.0.5.0

**Comment by aneesh1122** [comment]
use custom version

**Comment by twistios** [comment]
The second bug probably is already fixed in the custom version (#3021).

About the other one I an not sure.
For this issue you should enable debug mode in settings, restart app, reproduce the error (I.e. go to downloaded and try to play the song) and then copy debug log and past it here (Crash log probably does not help for this).

**Comment by twistios** [comment]
> use custom version

I was not typing fast enough.

**Comment by aneesh1122** [comment]
> The second bug probably is already fixed in the custom version (#3021).
> 
> About the other one I am not sure.
> For this issue you should enable debug mode in settings, restart app, reproduce the error (I.e. go to downloaded and try to play the song) and then copy debug log and past it here (Crash log probably does not help for this).
> 

Fast4x should use a bot now which will comment "use custom version" if it detects lyrics and crash in the same issue 😂😂

**Comment by BeepStation** [comment]
> The second bug probably is already fixed in the custom version (#3021).
> 
> About the other one I am not sure. For this issue you should enable debug mode in settings, restart app, reproduce the error (I.e. go to downloaded and try to play the song) and then copy debug log and past it here (Crash log probably does not help for this).
