### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by darkza** [fast4x/RiMusic#3034]
### Description

How to automatically sync between devices. ive i play on smartphone and switch to the car would be great to have the same ❤️ music and suggestions. Piped so far doesnt work for this.afik only playlist is shared to pipe.

### Suggested Solution

any option to automatically write a playlist of all hearted songs and upload to piped so that the other device can play on and also write to the same piped playlist?

**Comment by aneesh1122** [comment]
afaik the liked songs aren't considered in song radio. For radio you are just an unlogged guy who has no listening history. piped works somewhat. If you add a lot of songs at once it won't be synced.

**Comment by aneesh1122** [comment]
> okay that means that i heart the songs is more or less useless? so this doesn't make any difference for ri music sugessting me "songs i might like"?

Yeah. There's no unofficial YT music app which considers your listening history while suggesting you songs.

There's an app which I don't know if I should name but its UI looks a lot like spotify. The dev claims that after you login and send your listening history to Google it will improve your app suggestions but even after using that app for so long similar songs were suggested.

**Comment by darkza** [comment]
Oh great thanks for Explaining!
Seems to be one more reason that ❤️ Songs should translate in a Playlist that you choose. say one that syncs with piped.
Would be great that if u have more devices and regardless witch one you are using all your liked songs get captured.

Talking about Piped, its connected but under "playlists" everything is empty , also pressing +playlist and giving it a title doesn't change this.

**Comment by darkza** [comment]
![Screenshot_2024-07-31-16-48-08-063_it fast4x rimusic](https://github.com/user-attachments/assets/08dbf35d-3588-4545-826c-2f43bcaeb879)

**Comment by aneesh1122** [comment]
> Talking about Piped, its connected but under \"playlists\" everything is empty , also pressing +playlist and giving it a title doesn't change this.

1) restart the app after logging in to piped in RiMusic.
2) maybe you're not using same instance in piped web and RiMusic.

**Comment by darkza** [comment]
Yes ive logged out and in in settings then forceclosed the app task, works now! kind of... trying to mark all favourites at once and put in in the piped playlist. not possible looks like...

**Comment by aneesh1122** [comment]
> Yes ive logged out and in in settings then forceclosed the app task, works now! kind of... trying to mark all favourites at once and put in in the piped playlist. not possible looks like...

You can't add a lot of songs at once in piped playlist and sync it. Maybe like 1-2 songs.
