### ISSUE TITLE
Error: Failed to copy to Clipboard

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#3035]
### Steps to reproduce the bug

Create many debug log entries, like crashes and so on.

### Expected behavior

Debug log can be copied to Clipboard.

### Actual behavior

Copying fails.

### Screenshots/Screen recordings

![Screenshot_20240730_211911](https://github.com/user-attachments/assets/305ee131-d886-4b7d-b5a8-d95a2cc8c418)

### RiMusic version

0.6.45.1 custom version

### Android version

14

### Additional information

I already got a ridiculous amount of crashes in my app install, so now the crash log for example is > 2^16 characters (this log can still be copied).
It looks like the debug log is now >2^20 characters long. It makes sense that there is a maximum limit that it supports, but somehow it should be prevented from happening (at least have a better error message).

**Comment by twistios** [comment]
I think I will add the error message if I am able to find out how to do it.

**Comment by fast4x** [comment]
No, thi is a log and must be added in log not in form

**Comment by fast4x** [comment]
log is deleted always you disable...

**Comment by twistios** [comment]
T

> No, thi is a log and must be added in log not in form

The problem if this issue is that the log can not be accessed so it makes sense to show (at least) some message via the toast notification.

**Comment by fast4x** [comment]
It's not usable in debug so not make sense

**Comment by fast4x** [comment]
Improved
