### ISSUE TITLE
Fade on start of tracks

### ISSUE THREAD

**Issue by marsand-v3** [fast4x/RiMusic#3036]
### Steps to reproduce the bug

play a song

### Expected behavior

The song must begin without fade

### Actual behavior

the song start with fade 

### RiMusic version

actual version

### Android version

android 10

**Comment by twistios** [comment]
Probably the same as #3013.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.46

**Comment by marsand-v3** [comment]
> Fixed, available from version 0.6.46

thanks a lot

**Comment by marsand-v3** [comment]
when will the update be available?

**Comment by fast4x** [comment]
Thursday

**Comment by marsand-v3** [comment]
> Thursday

ok thanks
