### ISSUE TITLE
Crashes on local files

### ISSUE THREAD

**Issue by XGhostRX** [fast4x/RiMusic#3040]
### Steps to reproduce the bug

I went into songs and the app kept closing

### Expected behavior

Loading Played Songs

### Actual behavior

Unexpected closures constantly Unexpected closures constantly

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/ac2e4635-5d4c-4362-8f78-9bc55bf527f7

### RiMusic version

0.6.45.1

### Android version

Android 10

**Comment by Glich440** [comment]
Can you try to add the crash logs?

**Comment by XGhostRX** [comment]
2024-07-31T08:58:19.062:	java.lang.NullPointerException
	 a7.l.u(SourceFile:644) 
	 a7.l.i(SourceFile:13) 
	 M7.K.a(SourceFile:73) 
	 M7.g.a(SourceFile:18) 
	 M7.D.u(SourceFile:51) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 G1.a.run(SourceFile:173) 
	 Q7.k.run(SourceFile:3) 
	 Q7.a.run(SourceFile:96) 

2024-07-31T08:58:48.258:	java.lang.NullPointerException
	 a7.l.u(SourceFile:644) 
	 a7.l.i(SourceFile:13) 
	 M7.K.a(SourceFile:73) 
	 M7.g.a(SourceFile:18) 
	 M7.D.u(SourceFile:51) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 G1.a.run(SourceFile:173) 
	 Q7.k.run(SourceFile:3) 
	 Q7.a.run(SourceFile:96) 

2024-07-31T08:59:33.496:	java.lang.NullPointerException
	 a7.l.u(SourceFile:644) 
	 a7.l.i(SourceFile:13) 
	 M7.K.a(SourceFile:73) 
	 M7.g.a(SourceFile:18) 
	 M7.D.u(SourceFile:51) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 G1.a.run(SourceFile:173) 
	 Q7.k.run(SourceFile:3) 
	 Q7.a.run(SourceFile:96)

**Comment by XGhostRX** [comment]
Find out more
And this happens when you try to load music from the device

Uploading SVID_20240731_091702_1.mp4…

**Comment by XGhostRX** [comment]
Find out more
And this happens when you try to load music from the device
https://github.com/user-attachments/assets/fa2a47b0-201c-4ff2-81f7-43879fdb15da

**Comment by fast4x** [comment]
Open app, go to local and try if are visible

**Comment by XGhostRX** [comment]
Nope, it's still the same
They don't charge me the songs and it closes anyway.

https://github.com/user-attachments/assets/61964723-70d5-4b03-a99b-a8a5570fed10

**Comment by XGhostRX** [comment]
I don't know why it is, but it's likely because of the large number of local songs I have stored on my phone
I use a huawei p30 lite MAR-LX3A

**Comment by fast4x** [comment]
Try to enable debug in miscellaneous settings, restart and after crash go again in settings and copy crash log... paste here the two types of log, please

**Comment by XGhostRX** [comment]
2024-07-31 13:09:54:563 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-31 13:10:02:780 INFO: l -  sdk int 29
2024-07-31 13:10:13:653 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-31 13:10:14:439 INFO: l -  sdk int 29
2024-07-31 13:10:20:729 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-07-31T13:10:10.535:	java.lang.NullPointerException
	 a7.l.u(SourceFile:644) 
	 a7.l.i(SourceFile:13) 
	 M7.K.a(SourceFile:73) 
	 M7.g.a(SourceFile:18) 
	 M7.D.u(SourceFile:51) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 G1.a.run(SourceFile:173) 
	 Q7.k.run(SourceFile:3) 
	 Q7.a.run(SourceFile:96) 

2024-07-31T13:10:18.589:	java.lang.NullPointerException
	 a7.l.u(SourceFile:644) 
	 a7.l.i(SourceFile:13) 
	 M7.K.a(SourceFile:73) 
	 M7.g.a(SourceFile:18) 
	 M7.D.u(SourceFile:51) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 G1.a.run(SourceFile:173) 
	 Q7.k.run(SourceFile:3) 
	 Q7.a.run(SourceFile:96)

**Comment by XGhostRX** [comment]
I'm still waiting for them to fix it :/

**Comment by fast4x** [comment]
You have tried latest version 0.6.46?

**Comment by XGhostRX** [comment]
Yes, and nothing at all

**Comment by XGhostRX** [comment]
Yes, and nothing at all

https://github.com/user-attachments/assets/3ff9e578-cf64-406e-a682-a0bb4372f9d8

![Screenshot_20240803_110648_it fast4x rimusic](https://github.com/user-attachments/assets/a511ea72-5e28-4a96-8824-7051db090851)
[logs.txt](https://github.com/user-attachments/files/16481216/logs.txt)
I put the whole record in a notepad because my browser freezes if I put it here

**Comment by Its-Tony** [comment]
It is a bug started from last two versions, I was to create new issue about it. Player doesn't play music from local files. Nothing happens on tapping song files.

https://github.com/user-attachments/assets/8a1d680d-3870-4635-b4f6-ad852e4cb6e7
@fast4x

**Comment by XGhostRX** [comment]
I recently realized that using another phone. 
But I hope that this will be solved.
