### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Ry4k0** [fast4x/RiMusic#3041]
### Steps to reproduce the bug

Click on the cover for  lyrics

### Expected behavior

.

### Actual behavior

It crashed

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/3fb08ec9-563e-439c-aadd-9c60f625f5f4

### RiMusic version

0.6.45.1

### Android version

14

**Comment by aneesh1122** [comment]
Use custom version

**Comment by aneesh1122** [comment]
Use custom version

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion
