### ISSUE TITLE
Song is changing without  pressing

### ISSUE THREAD

**Issue by Ry4k0** [fast4x/RiMusic#3042]
Uploading video_20240731_193230.mp4…

### Steps to reproduce the bug

Go to next song even without pressing

### Expected behavior

.

### Actual behavior

.

### RiMusic version

0.6.45.1

### Android version

14

**Comment by fast4x** [comment]
I don't understand

**Comment by arthurprudenteres** [comment]
He's talking about medley duration, this is a non-intuitive feature.

**Comment by arthurprudenteres** [comment]
> How do you think it should be?

Disabled by default to minimize this kind of "problem"

**Comment by fast4x** [comment]
Yes it's just disabled by default, i've fixed a bug in the next version.
