### ISSUE TITLE
the app closes when listening to music

### ISSUE THREAD

**Issue by Kou-tester** [fast4x/RiMusic#3045]
### Steps to reproduce the bug

I was listening to a playlist and it just closes by itself

### Expected behavior

What I noticed is that it closes when the screen is turned off.

### Actual behavior

Maybe every 3 minutes or so of having the screen off the app closes

### RiMusic version

version 0.6.45.1

### Android version

Android 14

**Comment by Kou-tester** [comment]
The error only happens with local files

**Comment by fast4x** [comment]
Try to enable debug in miscellaneous settings, restart and after crash go again in settings and copy crash log... paste here

**Comment by fast4x** [comment]
paste the two types of log please

**Comment by fast4x** [comment]
Fixed available from version 0.6.49
