### ISSUE TITLE
The app crashes when I open the lyrics of the song

### ISSUE THREAD

**Issue by ysfcdr** [fast4x/RiMusic#3047]
### Steps to reproduce the bug

1. Pick a music 2. Open lycirs 3. App crash

### Expected behavior

Open the lyrics of the song

### Actual behavior

App crash

### RiMusic version

0.6.45.1 

### Android version

Android 14 / One Ui 6.1

**Comment by sharunkumar** [comment]
+1 happens to me too

**Comment by fast4x** [comment]
try custom version

**Comment by abhiae** [comment]
> try custom version 

what's custom version?

**Comment by twistios** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by sharunkumar** [comment]
@fast4x custom version works 👍 
can you release the fix in master?

**Comment by fast4x** [comment]
Ues, on Thursday

**Comment by twistios** [comment]
> Yes, on Thursday

Isn't that today?

**Comment by fast4x** [comment]
Sorry, Friday...
