### ISSUE TITLE
Cierre de la aplicación

### ISSUE THREAD

**Issue by Jesus1800377** [fast4x/RiMusic#3049]
### Steps to reproduce the bug

1. Ponga una canción 
2. Dar click en la foto de la canción 
3. Colocar la letra sincronizada
4. Después de una o 2 canciones se cierra la aplicación 

### Expected behavior

Escuchar musica seguida con letra sincronizada 

### Actual behavior

Cierre forzado de la aplicación 

### RiMusic version

0.6.45.1

### Android version

Android 12

**Comment by fast4x** [comment]
try custom version

**Comment by twistios** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion
