### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by OwenD30** [fast4x/RiMusic#305]
### Description

Let the user change to the font used in ViMusic or use one from storage.

### Suggested Solution

Have a setting in the appearance tab

### Alternatives

No alternatives

**Comment by fast4x** [comment]
Actual font Is Rubik, while ViMusic’s is Poppins

**Comment by fast4x** [comment]
The idea is good though different font size family will be required. .

**Comment by fast4x** [comment]
I can enter an option to choose the font from those available in the app.

- ViMusic Poppins
- RiMusic Rubik

**Comment by OwenD30** [comment]
Having the option to choose between the two would be great. Also, having a way for a user to select a font file on their device would be wonderful.

**Comment by fast4x** [comment]
> Having the option to choose between the two would be great. Also, having a way for a user to select a font file on their device would be wonderful.
> 
> Thanks for all your hard work!

A font consists of 6 files that contain different sizes of the same font. So from the device you should upload 6 files and not just one.

**Comment by fast4x** [comment]
Added font selection in appearance settings rubik/poppins.
Available from version 0.6.17
