### ISSUE TITLE
Lyrics 

### ISSUE THREAD

**Issue by Hyperjoker2511** [fast4x/RiMusic#3052]
### Steps to reproduce the bug

Play any song
Open lyrics 
3 to 5 sec later app crashes

### Expected behavior

Lyrics should play

### Actual behavior

App crashing 

### RiMusic version

0.6.43

### Android version

Android 6

### Additional information

Always crashing when opening lyrics

**Comment by twistios** [comment]
Ok, this is a new variant, because in 0.6.43 the issue with the lyrics did not yet exist I think.

**Comment by abhiae** [comment]
> @Hyperjoker2511 you should check [How do I get log files in case of a crash?](https://github.com/fast4x/RiMusic/wiki/FAQs#how-do-i-get-log-files-in-case-of-a-crash)
> 
> You can then post the crash log here.

Crash Log
2024-08-01T21:17:18.352:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.L.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:959) 
	 android.os.Handler.dispatchMessage(Handler.java:100) 
	 android.os.Looper.loopOnce(Looper.java:232) 
	 android.os.Looper.loop(Looper.java:317) 
	 android.app.ActivityThread.main(ActivityThread.java:8592) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by twistios** [comment]
This seems to be the same error as in the new version so probably you should try custom version.

https://github.com/fast4x/RiMusic/tree/master/customVersion
