### ISSUE TITLE
Moving Player position is hard in modern player

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#3054]
### Steps to reproduce the bug

1. Activate modern player
2. Disable thumbnail 
3. Start playlist
4. Try to move player position

### Expected behavior

Player position can be changed without a problem.

### Actual behavior

It actually is very hard to do.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/0291811c-3395-442c-be09-11f834c8b537

### RiMusic version

0.6.45.1 custom version

### Android version

14

**Comment by fast4x** [comment]
protects you from unwanted song changes

**Comment by twistios** [comment]
I don't understand what you mean with "protects you from unwanted song change" and how this has something to do with it. Currently the song would change when you want to change player position.

**Comment by twistios** [comment]
Sometimes it works to change position by tapping, but sometimes it opens lyrics, I.e. the expected and actual feedback does not match AND also it is a bit unpredictable.

**Comment by twistios** [comment]
Sometimes dragging also works but I don't understand why. Holding and the dragging does not seem to be working all the time for example if this is the intended gesture.

**Comment by aneesh1122** [comment]
*sigh*

https://github.com/user-attachments/assets/fdf6b8b5-8b0a-4e18-8010-c0936a749b99

**Comment by twistios** [comment]
Yeah, it works if thumbnail is enabled like in the video.

**Comment by aneesh1122** [comment]
> Yeah, it works if thumbnail is enabled like in the video.

https://github.com/user-attachments/assets/b319742d-6f4e-4a0c-bef0-20a5e73d3914

**Comment by twistios** [comment]
Sometimes it works fine, but sometimes just not.

https://github.com/user-attachments/assets/1eaa6cef-155f-4ef7-87fc-122cec644705


https://github.com/user-attachments/assets/1446ca3c-4d59-4282-a06b-809da82bc520

**Comment by aneesh1122** [comment]
> Sometimes it works fine, but sometimes just not.
> 
> https://github.com/user-attachments/assets/1eaa6cef-155f-4ef7-87fc-122cec644705
> 
> 
> https://github.com/user-attachments/assets/1446ca3c-4d59-4282-a06b-809da82bc520
> 
> 

C'mon man. You are supposed to touch on the seekbar. Don't just randomly touch anywhere outside the seekbar and expect it to work.

In my video it's working 100% of the time. You're doing it wrong.

**Comment by twistios** [comment]
Especially when it is at the beginning of the song.

**Comment by twistios** [comment]
What I am saying is not that it does not work from a technical view but usability.

**Comment by twistios** [comment]
Maybe in the area of the player time bar it should not be possible to do the song swipe action.

**Comment by twistios** [comment]
Maybe should have been a feature request instead.
