### ISSUE TITLE
Crash on Long Press Next Song in Queue

### ISSUE THREAD

**Issue by andrewteg** [fast4x/RiMusic#3055]
### Steps to reproduce the bug

1. Have "Show next song queue" enabled in Settings => Player Appearance (tested with 1/2/3 in "Show Next two Songs" box.
2. Start Song
3. Go to Player
4. Long Press any of the next songs showing.
5. RiMusic crashes.

### Expected behavior

I was not sure what to expect, but did not expect a crash. I think I was hoping after changing the number to 2/3 it would popup an option to delete like the trash can when the number is 1.

### Actual behavior

RiMusic crashed.  Sometimes it will restore with the song and playlist in tact, and sometimes will not have a playlist active.

### Screenshots/Screen recordings

Long press on Burn the Ships or I'll Find You causes the crash in this example.

Side note: clicking/tapping or long press on the arrow next to Burn the Ships will scroll the next queue area back to the next song if I've scrolled through that area to see future songs in the queue so that seems functional.

![Screenshot_20240801-135419](https://github.com/user-attachments/assets/3e66c266-66cc-4f68-a1d3-64444fda39ec)

### Logs

pulled a logcat from adb. I'm on [GrapheneOS](https://grapheneos.org/) FWIW.

[logcat.txt](https://github.com/user-attachments/files/16460340/logcat.txt)

### RiMusic version

0.6.45.1

### Android version

Android 14

### Additional information

As noted in logs, I'm on [GrapheneOS](https://grapheneos.org/) FWIW.

**Comment by aneesh1122** [comment]
Use new custom version. It has already been fixed.

btw long tap on a song will add it to play next.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.46
