### ISSUE TITLE
App crashes when trying to download new lyrics

### ISSUE THREAD

**Issue by SelzS0da** [fast4x/RiMusic#3057]
### Steps to reproduce the bug

play a song you haven't downloaded lyrics from and tap the lyrics icon, wait a few seconds and then the app closes

### Expected behavior

should not crash

### Actual behavior

app crash

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/0f290761-ace7-4fcf-823a-47a6677ee0da

### Logs

2024-07-10T15:32:25.331:	java.lang.IllegalStateException: Recording currently in progress - missing #endRecording() call?
	 android.graphics.RenderNode.beginRecording(RenderNode.java:446) 
	 android.graphics.RenderNode.beginRecording(RenderNode.java:465) 
	 s0.f.b(SourceFile:1) 
	 s0.g.G(SourceFile:4) 
	 s0.b.e(SourceFile:55) 
	 I0.C0.j(SourceFile:138) 
	 I0.y.dispatchDraw(SourceFile:102) 
	 android.view.View.draw(View.java:23212) 
	 android.view.View.updateDisplayListIfDirty(View.java:22076) 
	 android.view.View.draw(View.java:22940) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4529) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290) 
	 android.view.View.updateDisplayListIfDirty(View.java:22067) 
	 android.view.View.draw(View.java:22940) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4529) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290) 
	 android.view.View.updateDisplayListIfDirty(View.java:22067) 
	 android.view.View.draw(View.java:22940) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4529) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290) 
	 android.view.View.updateDisplayListIfDirty(View.java:22067) 
	 android.view.View.draw(View.java:22940) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4529) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290) 
	 android.view.View.updateDisplayListIfDirty(View.java:22067) 
	 android.view.View.draw(View.java:22940) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4529) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290) 
	 android.view.View.updateDisplayListIfDirty(View.java:22067) 
	 android.view.View.draw(View.java:22940) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4529) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290) 
	 android.view.View.draw(View.java:23212) 
	 com.android.internal.policy.DecorView.draw(DecorView.java:836) 
	 android.view.View.updateDisplayListIfDirty(View.java:22076) 
	 android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682) 
	 android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688) 
	 android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786) 
	 android.view.ViewRootImpl.draw(ViewRootImpl.java:4582) 
	 android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4293) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3520) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2289) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8958) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:985) 
	 android.view.Choreographer.doFrame(Choreographer.java:916) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:346) 
	 android.os.Looper.loop(Looper.java:475) 
	 android.app.ActivityThread.main(ActivityThread.java:7950) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 

2024-07-29T13:41:10.758:	java.lang.IllegalStateException
	 m2.b.h(SourceFile:6) 
	 q2.x.h(SourceFile:6) 
	 q2.x.g(SourceFile:34) 
	 g6.a.X(SourceFile:94) 
	 O6.G.l(SourceFile:306) 
	 d0.a.g(SourceFile:44) 
	 d0.a.l(SourceFile:9) 
	 B.p.e(SourceFile:378) 
	 d0.a.e(SourceFile:52) 
	 V.c.a(SourceFile:233) 
	 E.J.b(SourceFile:248) 
	 C.l.e(SourceFile:104) 
	 E.N.e(SourceFile:477) 
	 d0.a.e(SourceFile:52) 
	 V.c.a(SourceFile:233) 
	 f0.f.f(SourceFile:149) 
	 E.o0.f(SourceFile:87) 
	 E.J.d(SourceFile:105) 
	 B.x.e(SourceFile:1069) 
	 d0.a.e(SourceFile:52) 
	 B.x.e(SourceFile:869) 
	 d0.a.e(SourceFile:52) 
	 V.c.N(SourceFile:15) 
	 V.p.p(SourceFile:203) 
	 V.t.k(SourceFile:32) 
	 V.s0.a(SourceFile:43) 
	 V.n.a(SourceFile:5) 
	 V.n.a(SourceFile:5) 
	 V.n.a(SourceFile:5) 
	 V.t.l(SourceFile:9) 
	 F0.H.i(SourceFile:22) 
	 F0.H.h(SourceFile:120) 
	 F0.C.m0(SourceFile:160) 
	 E.V.b(SourceFile:34) 
	 C.r.b(SourceFile:21) 
	 a.a.r0(SourceFile:25) 
	 C.s.e(SourceFile:609) 
	 B.x.e(SourceFile:954) 
	 F0.E.g(SourceFile:74) 
	 H0.u.b(SourceFile:38) 
	 p0.W.i(SourceFile:1) 
	 H0.A.b(SourceFile:15) 
	 B.I.i(SourceFile:99) 
	 H0.A.b(SourceFile:15) 
	 A0.b.a(SourceFile:431) 
	 com.google.android.material.datepicker.c.y(SourceFile:56) 
	 g0.t.a(SourceFile:52) 
	 g0.u.c(SourceFile:140) 
	 H0.m0.a(SourceFile:3) 
	 H0.K.s0(SourceFile:133) 
	 H0.K.b(SourceFile:91) 
	 B.v.g(SourceFile:256) 
	 H0.u.b(SourceFile:38) 
	 B.I.i(SourceFile:99) 
	 H0.A.b(SourceFile:15) 
	 B.I.i(SourceFile:99) 
	 H0.A.b(SourceFile:15) 
	 A0.b.a(SourceFile:431) 
	 com.google.android.material.datepicker.c.y(SourceFile:56) 
	 g0.t.a(SourceFile:52) 
	 g0.u.c(SourceFile:140) 
	 H0.m0.a(SourceFile:3) 
	 H0.K.s0(SourceFile:133) 
	 H0.K.b(SourceFile:91) 
	 u.m.g(SourceFile:24) 
	 H0.u.b(SourceFile:38) 
	 u.B.i(SourceFile:240) 
	 H0.A.b(SourceFile:15) 
	 p0.p.i(SourceFile:1) 
	 H0.A.b(SourceFile:15) 
	 B.s0.d(SourceFile:39) 
	 F0.y.i(SourceFile:8) 
	 H0.A.b(SourceFile:15) 
	 A0.b.a(SourceFile:431) 
	 com.google.android.material.datepicker.c.y(SourceFile:56) 
	 g0.t.a(SourceFile:52) 
	 g0.u.c(SourceFile:140) 
	 H0.m0.a(SourceFile:3) 
	 H0.K.s0(SourceFile:133) 
	 H0.K.b(SourceFile:91) 
	 u.f.g(SourceFile:58) 
	 H0.u.b(SourceFile:38) 
	 B.I.i(SourceFile:99) 
	 H0.A.b(SourceFile:15) 
	 A0.b.a(SourceFile:431) 
	 com.google.android.material.datepicker.c.y(SourceFile:56) 
	 g0.t.a(SourceFile:52) 
	 g0.u.c(SourceFile:140) 
	 H0.m0.a(SourceFile:3) 
	 H0.K.s0(SourceFile:133) 
	 H0.K.b(SourceFile:91) 
	 B.d.g(SourceFile:86) 
	 B.g0.g(SourceFile:40) 
	 H0.u.b(SourceFile:38) 
	 B.I.i(SourceFile:99) 
	 H0.A.b(SourceFile:15) 
	 A0.b.a(SourceFile:431) 
	 com.google.android.material.datepicker.c.y(SourceFile:56) 
	 g0.t.a(SourceFile:52) 
	 g0.u.c(SourceFile:140) 
	 H0.m0.a(SourceFile:3) 
	 H0.K.s0(SourceFile:133) 
	 H0.K.b(SourceFile:91) 
	 B.v.g(SourceFile:256) 
	 H0.u.b(SourceFile:38) 
	 B.I.i(SourceFile:99) 
	 H0.A.b(SourceFile:15) 
	 B.b0.i(SourceFile:115) 
	 H0.A.b(SourceFile:15) 
	 A0.b.a(SourceFile:431) 
	 com.google.android.material.datepicker.c.y(SourceFile:56) 
	 g0.t.a(SourceFile:52) 
	 g0.u.c(SourceFile:140) 
	 H0.m0.a(SourceFile:3) 
	 H0.K.s0(SourceFile:133) 
	 H0.K.b(SourceFile:91) 
	 N6.N.e(SourceFile:962) 
	 F0.E.g(SourceFile:74) 
	 H0.u.b(SourceFile:38) 
	 A0.b.a(SourceFile:431) 
	 com.google.android.material.datepicker.c.y(SourceFile:114) 
	 g0.t.a(SourceFile:52) 
	 g0.u.c(SourceFile:140) 
	 H0.m0.a(SourceFile:3) 
	 H0.K.s0(SourceFile:133) 
	 H0.F.M(SourceFile:17) 
	 H0.F.N(SourceFile:18) 
	 H0.T.c(SourceFile:8) 
	 H0.T.m(SourceFile:138) 
	 H0.T.j(SourceFile:90) 
	 I0.y.x(SourceFile:36) 
	 I0.y.dispatchDraw(SourceFile:17) 
	 android.view.View.draw(View.java:23212) 
	 android.view.View.updateDisplayListIfDirty(View.java:22076) 
	 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513) 
	 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486) 
	 android.view.View.updateDisplayListIfDirty(View.java:22032) 
	 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513) 
	 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486) 
	 android.view.View.updateDisplayListIfDirty(View.java:22032) 
	 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513) 
	 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486) 
	 android.view.View.updateDisplayListIfDirty(View.java:22032) 
	 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513) 
	 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486) 
	 android.view.View.updateDisplayListIfDirty(View.java:22032) 
	 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513) 
	 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486) 
	 android.view.View.updateDisplayListIfDirty(View.java:22032) 
	 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513) 
	 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486) 
	 android.view.View.updateDisplayListIfDirty(View.java:22032) 
	 android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682) 
	 android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688) 
	 android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786) 
	 android.view.ViewRootImpl.draw(ViewRootImpl.java:4582) 
	 android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4293) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3520) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2289) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8958) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:985) 
	 android.view.Choreographer.doFrame(Choreographer.java:916) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:346) 
	 android.os.Looper.loop(Looper.java:475) 
	 android.app.ActivityThread.main(ActivityThread.java:7950) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 

2024-07-31T16:35:31.066:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.K.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:346) 
	 android.os.Looper.loop(Looper.java:475) 
	 android.app.ActivityThread.main(ActivityThread.java:7950) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 

2024-07-31T16:39:07.730:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.K.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:346) 
	 android.os.Looper.loop(Looper.java:475) 
	 android.app.ActivityThread.main(ActivityThread.java:7950) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 

2024-07-31T16:48:51.772:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.K.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:346) 
	 android.os.Looper.loop(Looper.java:475) 
	 android.app.ActivityThread.main(ActivityThread.java:7950) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 

2024-07-31T16:50:13.633:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.K.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:346) 
	 android.os.Looper.loop(Looper.java:475) 
	 android.app.ActivityThread.main(ActivityThread.java:7950) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 

2024-07-31T16:50:38.451:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.W.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:346) 
	 android.os.Looper.loop(Looper.java:475) 
	 android.app.ActivityThread.main(ActivityThread.java:7950) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 

2024-07-31T16:50:51.188:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.W.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:346) 
	 android.os.Looper.loop(Looper.java:475) 
	 android.app.ActivityThread.main(ActivityThread.java:7950) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 

2024-08-01T16:27:36.290:	java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	 t0.k.a(SourceFile:125) 
	 q0.f.onPreDraw(SourceFile:34) 
	 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3494) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2289) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8958) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:985) 
	 android.view.Choreographer.doFrame(Choreographer.java:916) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:346) 
	 android.os.Looper.loop(Looper.java:475) 
	 android.app.ActivityThread.main(ActivityThread.java:7950) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 

2024-08-01T16:28:02.061:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.K.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:346) 
	 android.os.Looper.loop(Looper.java:475) 
	 android.app.ActivityThread.main(ActivityThread.java:7950) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 

### RiMusic version

0.6.45.1

### Android version

13

### Additional information

this also happens when you wanna pick new lyrics from lrclib.net

**Comment by RouhT4ner** [comment]
It happens to me too

**Comment by aneesh1122** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by fast4x** [comment]
Try custom version please
