### ISSUE TITLE
Playback speed sometimes too fast for some sections

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#3061]
### Steps to reproduce the bug

1. Listen to an affected song (I don't know the condition)
2. Observe playback speed

### Expected behavior

Normal playback speed (when not changed in settings)

### Actual behavior

Some portions of some songs are faster than they should be.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/05ed65f7-d7a5-43aa-9f45-cde55a467d66

https://github.com/user-attachments/assets/d5b6fa3a-b2f1-47eb-9371-3dac24e96b88

### RiMusic version

0.6.45.1 custom version

### Android version

14

### Additional information

I have put the same youtube video at the same position as reference. I hope the increase in speed is noticeable.

**Comment by PaolaAtilano** [comment]
I have the same problem with some songs, the beginning of the song starts to fast, but as it progresses the speed returns to normal, I revised the speed settings and it was in the normal 1.0x the entire time

**Comment by twistios** [comment]
I also had it for some songs at the beginning. I think it can happen at any position.

**Comment by zatnas** [comment]
I have cleareed my song cache and downloaded songs then stopped and started the application, but the issue still persists.

Version 0.6.46

**Comment by twistios** [comment]
I was able to capture a video that had shown me that actually the time is running faster in the app if the issue happens than real time.

**Comment by twistios** [comment]
@fast4x maybe I know what is happening: Skip Silence. The skipping/beeing to fast goes away if "Skip Silence" is deactivated.

<details><summary>A demo video</summary>
<p>

https://github.com/user-attachments/assets/0f5951bd-1be1-42cd-8ed0-cd66e12241bb

</p>
</details>

**Comment by twistios** [comment]
Maybe this is actually #3128.

**Comment by fast4x** [comment]
wait... 47 version...

**Comment by twistios** [comment]
Withe the finer skip silence control this seems to be fixed.
