### ISSUE TITLE
Error en las letra

### ISSUE THREAD

**Issue by IsraelV21-b** [fast4x/RiMusic#3065]
### Steps to reproduce the bug

Al ingresar a las letras del tema sincronizados se sale de la app continuamente 

### Expected behavior

Esto deberia de arreglarse

### Actual behavior

Espero se solucione pronto ya que es una excelente app 

### RiMusic version

0.6.45.1

### Android version

Android 13

### Additional information

Cada que pongo una musica el sonido se buguea al iniciar el tema en todas las intros de todos los temas

**Comment by fast4x** [comment]
Download custom version 
https://github.com/fast4x/RiMusic/tree/master/customVersion
