### ISSUE TITLE
Automatic update opens 404 page

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#3066]
### Steps to reproduce the bug

1. Have an old version installed
2.Check for updates enabled
3. Close the app
4. Open app
5. Select download latest version from github"

### Expected behavior

Normal download possible.

### Actual behavior

404 page is opened.

### Screenshots/Screen recordings

![Screenshot_20240802_195809_Firefox](https://github.com/user-attachments/assets/d89f4468-4165-494b-89e7-9270ce7d8191)

### RiMusic version

0.6.45.1 custom version

### Android version

14

### Additional information

https://github.com/fast4x/RiMusic/releases/download/v0.6.46/app-release.apk

This is the url that does not work. It seems like the apk now has a new name.

**Comment by twistios** [comment]
Probably this needs to be fixed by renaming the apk or for future updates inside the app.

**Comment by fast4x** [comment]
Yes it's new name of apk, I'll fix it

**Comment by fast4x** [comment]
Fixed, available from version 0.6.47
