### ISSUE TITLE
[Feature]: improve the ui color vs bg color contrast

### ISSUE THREAD

**Issue by shahriarlabib000** [fast4x/RiMusic#3067]
### Description

It really hard to see the ui maybe there should be more clear contrast.
Most often I can't notice if i have added a music to the favorite or not
Here is an example 
![Screenshot_2024-08-03-00-13-01-785_it fast4x rimusic](https://github.com/user-attachments/assets/6fd48aab-afdb-4405-b8c0-b4f3badb31eb)
![Screenshot_2024-08-03-00-13-04-340_it fast4x rimusic](https://github.com/user-attachments/assets/2a6e3d05-1abf-42b2-acc8-b48942c3175f)

### Suggested Solution

Please improve the contrast

### Alternatives

The contrast or ui looks fine or better on the notification bar

**Comment by twistios** [comment]
You can enable outline for (most) text.

**Comment by shahriarlabib000** [comment]
No not text but the heart/favorite button

**Comment by shahriarlabib000** [comment]
Another example 
![Screenshot_2024-08-03-00-27-43-831_it fast4x rimusic](https://github.com/user-attachments/assets/2b39e6ba-6bcd-48eb-ae75-ac406237bff4)

![Screenshot_2024-08-03-00-27-41-105_it fast4x rimusic](https://github.com/user-attachments/assets/91ff2775-dc23-4129-aac9-1d9e0cd25e2b)

**Comment by aneesh1122** [comment]
Use bottom gradient

**Comment by shahriarlabib000** [comment]
Not sure what you are referring to.pls tell where to find it

**Comment by aneesh1122** [comment]
> Not sure what you are referring to.pls tell where to find it

![Screenshot_2024-08-03-00-59-07-555_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/94606643-962f-4a53-8676-911cef154db2)

**Comment by shahriarlabib000** [comment]
Doesn't quite fix it for me as the image is blurred. And I personally think it would look better if its blurred and the favorite button still being easily recognizable will look better thats why i proposed the feature 
![Screenshot_2024-08-03-01-35-44-518_it fast4x rimusic](https://github.com/user-attachments/assets/fc5ae9ef-202f-4bfb-a3bf-a61472848f78)
![Screenshot_2024-08-03-01-35-38-920_it fast4x rimusic](https://github.com/user-attachments/assets/0bf165f6-c18e-4926-bf38-57c6ab2045c9)

**Comment by aneesh1122** [comment]
> Doesn't quite fix it for me as the image is blurred. And I personally think it would look better if its blurred and the favorite button still being easily recognizable will look better thats why i proposed the feature 
> ![Screenshot_2024-08-03-01-35-44-518_it fast4x rimusic](https://github.com/user-attachments/assets/fc5ae9ef-202f-4bfb-a3bf-a61472848f78)
> ![Screenshot_2024-08-03-01-35-38-920_it fast4x rimusic](https://github.com/user-attachments/assets/0bf165f6-c18e-4926-bf38-57c6ab2045c9)
> 
> Tho I'd say it looks better than before 

I'll think of something until then use this workaround.

Btw you prefer blurred album cover over unblurred? Well that's new

**Comment by shahriarlabib000** [comment]
Yeah i think it looks better and thank you very much
