### ISSUE TITLE
[Feature]: remember last played song

### ISSUE THREAD

**Issue by mohandan1** [fast4x/RiMusic#307]
### Description

Is it possible to add a feature to remember last played song on re-opening the app after closing app from background and show as NOW PLAYING like ytm and Spotify.....
If possible, then it would be very helpful and we will not have to bother to search that song again

### Suggested Solution

When we open the app, it remember the last played song and it appears as 'NOW PLAYING'.

**Comment by NeeRaj-2401** [comment]
Is it diff from Settings > UI > Persistent Queue ?

**Comment by mohandan1** [comment]
I didn't know about this feature.....
Thanks 👍

**Comment by fast4x** [comment]
Solved?

**Comment by NeeRaj-2401** [comment]
Yes @fast4x

**Comment by mohandan1** [comment]
Yes
