### ISSUE TITLE
Function of synchronizing lyrics in music and transferring music from YT Music to RiMusic

### ISSUE THREAD

**Issue by AXN-Developers** [fast4x/RiMusic#3070]
### Description

Hello, I found the app quite interesting. One suggestion I have is to be able to transfer the music from YT Music to RiMusic and also to be able to synchronize the lyrics with the music. The truth is I see a lot of potential in the app and I will be on the lookout for updates, I hope they improve it, Thanks :)

### Suggested Solution

Make it a friendly and potential app for users.

**Comment by fast4x** [comment]
Exolore app it have much then you want, I'm sure...
I attend your feedback
