### ISSUE TITLE
Problema de la notificación de reproducción de audio

### ISSUE THREAD

**Issue by DevJRFR** [fast4x/RiMusic#3071]
### Steps to reproduce the bug

1. Reproducir una canción dentro de la app. 2. Dejar la aplicación ejecutándose en segundo plano. 3. pausar la canción desde el panel de notificaciones. 4.Continuar la canción desde el panel de notificaciones 

### Expected behavior

Al momento de continuar la canción , debería sonar lo que estaba reproduciendo.

### Actual behavior

La canción sigue pero sin sonido. (Todo desde afuera de la aplicación)

### RiMusic version

0.6.45.1

### Android version

Android 12

**Comment by fast4x** [comment]
Please download latest version 0.6.46
