### ISSUE TITLE
Music syncing causes the app to stop

### ISSUE THREAD

**Issue by AXN-Developers** [fast4x/RiMusic#3073]
### Steps to reproduce the bug

As I saw that they responded, I managed to find the option to synchronize lyrics with music so I activated it

### Expected behavior

What happened is that out of nowhere the playback stopped and now when I want to activate it it tells me "RiMusic Has Stopped" and it also appeared recently that "RiMusic is not responding"

### Actual behavior

The truth is I don't know if my device is 32-bit.

### Screenshots/Screen recordings

![Uploading Screenshot_20240802-135407.png…]()

### RiMusic version

0.6.45.1

### Android version

Android 10

### Additional information

I don't know if it is an internal problem with my device or my device does not support the function.

**Comment by AXN-Developers** [comment]
Sorry for the English, I'm using a translator, I'm Spanish speaking, I'm sorry.

**Comment by aneesh1122** [comment]
Use latest version maybe?

**Comment by AXN-Developers** [comment]
I am using the latest version

**Comment by aneesh1122** [comment]
> I am using the latest version 

0.6.45.1 is not the latest version
