### ISSUE TITLE
App crashes when opening lyrics

### ISSUE THREAD

**Issue by Dantoza** [fast4x/RiMusic#3075]
### Steps to reproduce the bug

When I click on the album image to see the lyrics, the app crashes I have Xiaomi redmi note 12

### Expected behavior

THe app should show lyrics

### Actual behavior

The app crashes

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/dd316480-e644-4066-a3d8-2da0351659b5

### RiMusic version

0.6.45.1

### Android version

Android 14

**Comment by twistios** [comment]
The bug is probably already fix in release 0.6.46.

**Comment by fast4x** [comment]
Download latest version please
