### ISSUE TITLE
the application closes automatically  

### ISSUE THREAD

**Issue by Jheymilson123** [fast4x/RiMusic#3077]
### Steps to reproduce the bug

First I went to a song then in the part of synchronizing the lyrics with the song the application closed automatically  

### Expected behavior

I should synchronize the lyrics with the song  

### Actual behavior

the application closes automatically  

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/ae677274-aff7-479a-869a-afd430068c45

### RiMusic version

0.6.45.1

### Android version

Android 14

### Additional information

and they could optimize it a little more so that when browsing the application it doesn't feel slow

**Comment by twistios** [comment]
You should try the latest release 0.6.46.
