### ISSUE TITLE
Like function

### ISSUE THREAD

**Issue by zulabio** [fast4x/RiMusic#3081]
### Description

A like button next to the download button of the songs, on the main page and the album page, not on the playback screen, so it is easier to add several songs to the "favorite songs" 

### Suggested Solution

![IMG-20240802-WA0013](https://github.com/user-attachments/assets/c5ba3547-6874-40c8-9565-4323cc84d92e)
![IMG-20240802-WA0014](https://github.com/user-attachments/assets/85756094-15fe-4827-a98b-c5dd8c71e85c)

In the marked sections there is a simple heart or like button to easily add albums and songs to the "favorite songs" section. 

### Alternatives

Any solution that needs to add favorite songs is easier 

### Additional Context

It's tedious to have to open or press and hold songs to add them to favorites

Thank you for your fantastic work.

**Comment by fast4x** [comment]
Hi, thanks

**Comment by fast4x** [comment]
Added horizontal swipe in albums in search results page, bookmark and add in queue.
Available from version 0.6.47
