### ISSUE TITLE
A simple likeA simple likeA 

### ISSUE THREAD

**Issue by LUCASalonz7** [fast4x/RiMusic#3082]
### Description

I suggest an easier "like" in the application interface, since it is uncomfortable to have to enter the song to like whose song (depending on where you are in the application)

### Suggested Solution

Put an option to like next to the title of the song this to like without having to enter the song this so that if you are new to this application and want to add your favorite songs quickly you can do it.

### Alternatives

Whatever solves this problem for new or old users 

### Additional Context

![Logopit_1722634974188](https://github.com/user-attachments/assets/f81ec98d-8100-40dc-a68f-2f0f5fbf6a5b)

**Comment by faustaahmad** [comment]
Hold the song

**Comment by twistios** [comment]
There is also a swip-action for this.

**Comment by gauze756** [comment]
Unnecessary and hard to understand issue. We can close this I presume. Instead consider this is a possible solution #3118

**Comment by fast4x** [comment]
Yes

**Comment by gauze756** [comment]
Close issue please.
