### ISSUE TITLE
Guardar la canción que queda al cerrar la aplicación 

### ISSUE THREAD

**Issue by AldoLara** [fast4x/RiMusic#3085]
### Description

Me pasa que cuando estoy escuchando música y ya de cierro la aplicación y la vuelvo abrir la canción que estaba escuchando ya no está y el mini reproductor de la aplicación de quita

### Suggested Solution

Que cuando abra la aplicación se ponga en el mini reproductor la canción que estaba escuchando antes de cerrar la aplicación

**Comment by fast4x** [comment]
Enable persistent queue in ui settings
