### ISSUE TITLE
Hello!!

### ISSUE THREAD

**Issue by PabloMan47** [fast4x/RiMusic#3086]
### Description

It would be great to add an option to disable these icons in the title. I know the "Essential" mode, but I don't like the centered titles
![IMG-20240802-WA0042](https://github.com/user-attachments/assets/e22ec8ea-aca4-4436-ab94-aef62af1f655)

### Suggested Solution

something like this
![retouch_2024080222491989](https://github.com/user-attachments/assets/7804fe59-89c9-4845-8cb5-c3524d334ba1)

### Alternatives

At least an option to change the title position

### Additional Context

Thats all!

**Comment by fast4x** [comment]
Implemented, available from version 0.6.47

**Comment by ALMIGHTY-VC** [comment]
Also the disabled play button with outline looks weird how about making it without outline and giving it shadow

**Comment by fast4x** [comment]
Can add here a screenshot please?

**Comment by ALMIGHTY-VC** [comment]
> Can add here a screenshot please?

![Screenshot_2024-08-06-14-38-46-197_it fast4x rimusic](https://github.com/user-attachments/assets/40098965-245a-4ee5-b22d-5eafa675a409)
Its probably weird due to uneven outlines
