### ISSUE TITLE
Cómo puedo hacer para q me aparezcan musicas

### ISSUE THREAD

**Issue by Dekaloln** [fast4x/RiMusic#3087]
### Steps to reproduce the bug

..

### Expected behavior

Poder acceder a una cuenta para escuchar música 

### Actual behavior

No me aparece alguna opción para poder incluir musicas

### Screenshots/Screen recordings

![Screenshot_20240802-235048](https://github.com/user-attachments/assets/c589ec50-ac79-4dad-8e73-98d6a622909a)
![Screenshot_20240802-235041](https://github.com/user-attachments/assets/6e567519-9446-4724-80eb-c1afd7808252)

### Logs

..

### RiMusic version

0.6.43

### Android version

Android 13

### Additional information

Tengo ese problema de no poder acceder a ninguna canción

**Comment by fast4x** [comment]
Maybe your data connection is limited, try to use a proxy.
