### ISSUE TITLE
Queue list opens unintentionally

### ISSUE THREAD

**Issue by gauze756** [fast4x/RiMusic#3089]
### Steps to reproduce the bug

- Have gesture navigation enabled on your phone
- Open any music in rimusic
- Swipe up from the bottom of the screen as if you want to open recent apps
- -queue screen opens unintentionally

### Expected behavior

- Don't open queue list with a swipe or have an option to disable it
- Instead use tap to bottom action bar to open queue or enable and use arrow button on bottom action bar

### Screenshots/Screen recordings

> "Tap to open queue" setting does not make a difference

https://github.com/user-attachments/assets/eddf28ae-ed07-44dc-a6b8-916b412b000a

### RiMusic version

0.6.45.1

### Android version

Android 13
.

Edit: cleared clutter and made it clearer to read

**Comment by fast4x** [comment]
In player appearance settings, disable Tap to open queue

**Comment by gauze756** [comment]
> In player appearance settings, disable Tap to open queue

Already disabled.

**Comment by fast4x** [comment]
So, how would you to orn queue in your opinion?

**Comment by gauze756** [comment]
> So, how would you to orn queue in your opinion?

1. Provide an option to enable or disable to swipe up to open queue
2. Use **already implemented** tap to bottom action bar to open queue > Tap to open queue
3. Use **already implemented** use arrow button on bottom action bar `by enabling "Arrow button" under Settings>Player Appearence>Player Action Bar`

**Comment by fast4x** [comment]
Ok it make sense, thanks

**Comment by fast4x** [comment]
Implemented, available from version 0.6.47
