### ISSUE TITLE
Disable horizontal swipe doesn't work when…

### ISSUE THREAD

**Issue by gauze756** [fast4x/RiMusic#3090]
### Steps to reproduce the bug

Background colors>blurred song cover
Disable show thumbnail
Enable "disable horizontal swipe"
Open any song
Swipe left or right

### Expected behavior

Since "disable horizontal swipe" is enabled player ui should not behave in contradiction.

### Actual behavior

Horizontal swipe works regardless of "disable horizontal swipe" setting when blurred song cover is enabled and show thumbnail is disabled.

### RiMusic version

0.6.46

### Android version

Android 13

**Comment by aneesh1122** [comment]
Okay I'll remove this option from modern player.

You can go back to essential player if you want to disable horizontal swipe
