### ISSUE TITLE
Fade audio doesn't work when start button is pressed to pause on mini player

### ISSUE THREAD

**Issue by gauze756** [fast4x/RiMusic#3091]
### Steps to reproduce the bug

- Enable fade audio
- Play any song
- Press pause on mini player
- Press start to play it again
- **Notice** how when resuming audio on mini player fade works
- Test fade by pressing the play button on normal player or notification panel to see the difference

### Expected behavior

..

### Actual behavior

..

### RiMusic version

0.6.46

### Android version

Android 13

**Comment by gauze756** [comment]
#3088

**Comment by fast4x** [comment]
Fixed, available from version 0.6.49
