### ISSUE TITLE
no "playlists you might like" with "for you by most played song"

### ISSUE THREAD

**Issue by frenchy82** [fast4x/RiMusic#3094]
### Steps to reproduce the bug

In quick picks, if for you by most played song is selected there is no "playlists you might like" section

If you select by last played song, this section is visible

### Expected behavior

You should have visible "playlists you might like" with all sorts of "for you"

### Actual behavior

as the desciption

### RiMusic version

RiMusic 0.6.46

### Android version

android 12

**Comment by twistios** [comment]
I can kind of confirm that this happens sometimes except that it does not happen on the same selection every time (it changes).
I was able to get the playlist-section back by refreshing via swiping down from the top.

**Comment by frenchy82** [comment]
Strange, If I uninstall and then reinstall rimusic it works again 
But if I then restore the backup of my data it no longer works, can't have playlists you might like with for you by most played songe.

**Comment by frenchy82** [comment]
Why this bug report is closes ?
This is not working. Playlists you might like is not visible with the most played songe activate.
it's a shame as it's a ver usefull function
