### ISSUE TITLE
Playback error with some tracks, on Youtube plays normally

### ISSUE THREAD

**Issue by marsand-v3** [fast4x/RiMusic#3095]
### Steps to reproduce the bug

1) search playlist "jmlab"
2) select "Focal audio test"
3) play tracks 4 and 5

### Expected behavior

tracks 4 and 5 should play normally

### Actual behavior

tracks don't play and appear error 

### Screenshots/Screen recordings

![Screenshot_20240803-123936](https://github.com/user-attachments/assets/a20f31bb-cab3-4734-8740-35745e9b4831)

### RiMusic version

latest

### Android version

10

**Comment by gauze756** [comment]
#2823 duplicate

**Comment by fast4x** [comment]
Can you share any link to this songs please?

**Comment by marsand-v3** [comment]
https://music.youtube.com/watch?v=IwOObGWbP40




Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: Rino Russo ***@***.***>
Data: 03/08/24 13:37 (GMT+01:00)
A: fast4x/RiMusic ***@***.***>
Cc: marsand-v3 ***@***.***>, Author ***@***.***>
Oggetto: Re: [fast4x/RiMusic] Playback error with some tracks, on Youtube plays normally (Issue #3095)


Can you share any link to this songs please?

**Comment by gauze756** [comment]
> Can you add here any link to this song please?

https://music.youtube.com/watch?v=xCQGT3D8uEA
https://music.youtube.com/watch?v=x5eXS2BYKL8
https://music.youtube.com/watch?v=7SHY5pWDgxo
https://music.youtube.com/watch?v=7j6fEY9C7-s

**Comment by fast4x** [comment]
Thank you very much, your links allowed me to fix a bug that was present for a long time, thanks!
Fixed, available from version 0.6.47

**Comment by marsand-v3** [comment]
https://music.youtube.com/playlist?list=PLpszlaVYHIX5k6l8A37ivnnt-Gq-zMs3F

**Comment by marsand-v3** [comment]
![Screenshot_20240806-173617](https://github.com/user-attachments/assets/51754c4a-2a41-4075-af76-20ab18882b54)

https://music.youtube.com/playlist?list=PLpszlaVYHIX5k6l8A37ivnnt-Gq-zMs3F
