### ISSUE TITLE
Expand player on default

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#3096]
### Description

You'll only really click the "Expand Player" button on the player action bar once. So why not just add an option in the settings to expand the player by default.

### Suggested Solution

Add an option or a toggle in the appearance settings to expand the player by default instead of having the button on the action bar.

**Comment by aneesh1122** [comment]
That's not true. I use modern player so for carousel I often expand player and then disable it.

Anyways, you can just expand it once and disable the toggle from settings if you want.

**Comment by cMattw** [comment]
> Anyways, you can just expand it once and disable the toggle from settings if you want.

I didn't know that you could do that. I guess I haven't been looking enough. Thanks, my suggestion is solved.
