### ISSUE TITLE
github download 

### ISSUE THREAD

**Issue by SolitaireRocket** [fast4x/RiMusic#3099]
### Steps to reproduce the bug

When trying to install the apk release it says error in package analysis  
also says foss 
![Screenshot_20240803_084335_ZArchiver](https://github.com/user-attachments/assets/23c20a9f-428a-4c8c-8eae-5f7878061efd)

### Expected behavior

Update 

### Actual behavior

.

### RiMusic version

the new version 

### Android version

Android 14

**Comment by gauze756** [comment]
Currently installed app may have different signature based on where it was first installed. If you had the app first installed from f-droid official repository you may not be able to install it from another source which is github in this instance. 

**_Provide more information before you open another issue by the way._**

**Comment by twistios** [comment]
There are now different "product flavors". The reason for this is that the app is now available for the accrescent which supports [unattended updates](https://accrescent.app/features#unattended-updates). So the variant for this app store does not have the "check for updates enable" button. 
Also see https://github.com/fast4x/RiMusic/issues/3066. So updating from version before 0.6.47 to the latest version have to be performed manually now I guess.

**Comment by fast4x** [comment]
> There are now different "product flavors". The reason for this is that the app is now available for the accrescent which supports [unattended updates](https://accrescent.app/features#unattended-updates). So the variant for this app store does not have the "check for updates enable" button. 
> Also see https://github.com/fast4x/RiMusic/issues/3066. 
> 
> So updating from version before 0.6.47 to the latest version have to be performed manually now I guess.

Nice, can you add this in faq please?

**Comment by twistios** [comment]
https://github.com/fast4x/RiMusic/wiki/FAQs#breaking-changes-in-0646
