### ISSUE TITLE
[Feature]: Shapes of album

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#31]
### Description

Shapes of album, in currently playing
![IMG_20231023_221702](https://github.com/fast4x/RiMusic/assets/63956787/4b043875-d5da-4f72-91f2-ffde35061b31)

### Suggested Solution

I want better options for rounding the album image, because it is not rounded enough, and also too big 
![IMG_20231023_221925](https://github.com/fast4x/RiMusic/assets/63956787/fa6c9df7-7067-4371-9c3b-9b5b1962c5c7)

More like this not too big, like vimusic and much rounded u see the red circle rounded like this, and also center more currently playing.... Like vimusic

**Comment by NEVARLeVrai** [comment]
I made tomorrow something you cloud more understand what I mean

**Comment by NEVARLeVrai** [comment]
I will also try made a new icon for rimusic because I don't like too much and send it to you, to know your feedback if u like it

**Comment by NEVARLeVrai** [comment]
?

**Comment by ikanakova** [comment]
If I understand correctly what you mean - rounded corners for albums. I think it would be nice if someone who chooses rounded thumbnail in the settings should also have rounded albums.

**Comment by NEVARLeVrai** [comment]
Yeah I choose but don't Working

**Comment by fast4x** [comment]
Ok for rounded edges and relative settings, but RiMusic doesn't have to become ViMusic.

**Comment by fast4x** [comment]
I try to customize the size of the player.

**Comment by fast4x** [comment]
Fixed rounded shape
Added Small, Medium and Big thumbnail player settings

**Comment by NEVARLeVrai** [comment]
Available on the new version?

**Comment by NEVARLeVrai** [comment]
Also cloud u add additional translation? So I can complete translation.

**Comment by fast4x** [comment]
Ah ok!
I've committed new strings, update your fork and send new pull request.

**Comment by fast4x** [comment]
Normally you can update all strings after new release.

**Comment by NEVARLeVrai** [comment]
> Normally you can update all strings after new release.

Ok I fork tomorrow, I tell you if there are always translations missing so you add them to the file

**Comment by fast4x** [comment]
There are new features in development, I don't know if I can put them in the next release, so I can't know at the moment what other entries there will be to translate.

**Comment by NEVARLeVrai** [comment]
Ok np 👍

________________________________
