### ISSUE TITLE
Change font style and change play/pause background 

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#310]
### Description

Font style does not look attractive and also play/pause background is not attractive 
![Screenshot_20231231-201702](https://github.com/fast4x/RiMusic/assets/120176369/7d78bd7f-abd0-42c5-a630-4ae260a11cec)

Also add a feature to add our Google account 

### Suggested Solution

Choose the font style like mundial or One ui 6.0 font style and play/pause button background should be according to album colors like in Original ViMusic
![Screenshot_20231231-202128~2](https://github.com/fast4x/RiMusic/assets/120176369/0f2c9942-7c93-4779-9e33-b83a075fd3d6)

### Additional Context

Please fix all these design flaws and it will be a perfect app

**Comment by ikanakova** [comment]
I disagree, I like the current font. This one is too thick and the whole album title text won't fit.

**Comment by OrangeZXZ** [comment]
> I disagree, I like the current font. This one is too thick and the whole album title text won't fit.

I think he meant the color of the text should be white

**Comment by ikanakova** [comment]
>> I disagree, I like the current font. This one is too thick and the whole album title text won't fit.
> 
> I think he meant the color of the text should be white

Ah, in that case I agree, I think white font would be nicer if the buttons are white too.

**Comment by fast4x** [comment]
Album colors, you mean that the color is based on the background of the album cover?

**Comment by OrangeZXZ** [comment]
> Album colors, you mean that the color is based on the background of the album cover?

he means that the dinamic color should be applied to play button and other grey ui

**Comment by Logan7899** [comment]
> Album colors, you mean that the color is based on the background of the album cover?

Yes, I mean dynamic color for adaptive background on music player because grey ui stands odd and also breaks design consistency and it was according to album colors in previous version and also miniplayer play/pause button

**Comment by fast4x** [comment]
Fixed color on Dynamic theme
Available from version 0.6.17

**Comment by fast4x** [comment]
Available on version 0.6.16.1
