### ISSUE TITLE
Return to Player via Miniplayer fails after pause when returning from background.

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#3100]
### Steps to reproduce the bug

It is one of those random bugs where it it not exactly clear what happend.
Here are some approximate steps:

1. Start app
2. Play song
3. pause song
4. go to background
5. wait
6. return to app via task manager
7. App opens in Player
8. Try to continue playing, fails
9. Reduce to miniplayer
10. Random stuff
11. Try to open player via mini-player

### Expected behavior

Mini-player opens player

### Actual behavior

Some grey overlay opens and the player does not open. If I click somewhere else, the overlap goes away and it is like I have not clicked on the mini-player.

### Screenshots/Screen recordings

<details><summary>The overlay</summary>
<p>

![rimusic_miniplayer-overlay_issue](https://github.com/user-attachments/assets/5a2359c7-cd8a-4758-bfd7-e7ed9dd10947)

</p>
</details> 

<details><summary>When clicking somewhere else when overlay is shown</summary>
<p>

![rimusic_miniplayer-overlay_issue_returning](https://github.com/user-attachments/assets/390b4724-97bf-4e9b-997c-63ae3e9a1bce)

</p>
</details> 

### RiMusic version

0.6.46 commit f2466c63f821fe21

### Android version

14

### Additional information

This issue already happend on older release versions.
This issue happend while I was debugging some other error. I was not able to find a breakpoint in PlayerModern that I can set such that it gets hit. It seems like the PlayerModern-code does not get launched in this case.

**Comment by twistios** [comment]
It looks like this is because the notification disappears before that.

**Comment by twistios** [comment]
Is it possible to recover from this state correctly or at least restart normally?

**Comment by fast4x** [comment]
I'll try

**Comment by TT-392** [comment]
For anyone coming across this issue, enabling the option: "Persistent queue" in RiMusic's settings will allow you to at least resume playback when this happens.
