### ISSUE TITLE
Una posible mejora que recomiendo

### ISSUE THREAD

**Issue by Yosoloquieromusica** [fast4x/RiMusic#3101]
### Description

Las canciones que están en el dispositivo se deberían de ver con tan solo permitirle acceso al almacenamiento correspondiente 

### Suggested Solution

Una sugerencia que tengo es que se puedan ver todas las canciones que hay en el dispositivo con tan solo permitirle acceso al almacenamiento

**Comment by fast4x** [comment]
It's just implemented... now it work so
