### ISSUE TITLE
localhost as host :enhancement:

### ISSUE THREAD

**Issue by Wjxfi** [fast4x/RiMusic#3105]
For Tor lol

**Comment by fast4x** [comment]
Instead use 127.0.0.1

**Comment by fast4x** [comment]
No no it's interesting. Can you explain better the error that gives you and why tor wants localhost? Let me understand better, maybe give me some indication on what to install and how to reproduce the error.

**Comment by fast4x** [comment]
Try this:
127.0.0.1:9050 mode SOCKS

**Comment by fast4x** [comment]
I can't implement it, it seems not supported in okHttp
