### ISSUE TITLE
Descargas.

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#3109]
### Steps to reproduce the bug

1. Realiza la descarga de alguna canción de tu agradó.
2. Presiona el icono de descarga y espera.
3. La descarga no se realiza correctamente.
4. El icono tiene bugs, aparece y desaparece la descarga en curso.

### Expected behavior

1. Se realizan las tareas de descarga correctamente sin bugs.

### Actual behavior

1. La descarga no se completa correctamente y se queda congelada la descarga.

### Screenshots/Screen recordings

N/A

### Logs

N/A

### RiMusic version

0.6.46

### Android version

Android 14

### Additional information

OJO: Muy pocas ocasiones se pueden descargar algunas canciones y si lo hace el proceso para finalizar la descarga es de 6 minutos aproximadamente.
Inclusive si descargo un álbum el proceso es demasiado lento. (He borrado la app y vuelto a instalar pero es el mismo resultado)

**Comment by fast4x** [comment]
You gotta give me an example, like go here and hit download.
