### ISSUE TITLE
No artist name

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#311]
### Steps to reproduce the bug

1. Go to search
2. Than search a song like Move it 2 drum by hardwell
3. There you will notice that there is no artist's name

### Expected behavior

Artist's name should appear

### Actual behavior

No artist name
![Screenshot_20231231-201702](https://github.com/fast4x/RiMusic/assets/120176369/1d0714f4-9a35-43fc-8427-776ed555c25c)

### RiMusic version

0.6.15.1

### Android version

Android 14

**Comment by ikanakova** [comment]
I think this is related to issue #267

**Comment by fast4x** [comment]
Fixed, available from version 0.6.16

**Comment by Logan7899** [comment]
> Fixed, available from version 0.6.16

But the latest version 0.6.15.1

**Comment by fast4x** [comment]
In fact, the next version will be 0.6.16
