### ISSUE TITLE
Crear cuenta

### ISSUE THREAD

**Issue by lucky311230** [fast4x/RiMusic#3111]
### Description

He estado buscando y no encuentro una función para crear una cuenta y que así mis datos estén a salvo si quiero instalar esto en otro telefono

### Suggested Solution

Sería bueno que se implementara esto para guardar mi información en la nube

**Comment by fast4x** [comment]
There is no login with Google, you can use only one piped account if you want.

**Comment by Jose7723** [comment]
No me reproduce la canciones. Me dice que tengo q iniciar sesión. Y no se dónde

**Comment by fast4x** [comment]
now you can login with Google go in miscellaneous settings
