### ISSUE TITLE
Yo wassup

### ISSUE THREAD

**Issue by Jcarz100204** [fast4x/RiMusic#3114]
### Description

So Vultures 2  dropped and some songs were reworked after the release but in the app they dont update could you guys make something about it???

### Suggested Solution

Make the albuns be update

**Comment by fast4x** [comment]
Hi, i can add a sync functionality like playlist.

**Comment by aneesh1122** [comment]
Do albums also need to be updated? @fast4x

**Comment by fast4x** [comment]
In some cases they are updated with later tracks, I have not had similar situations so I do not know if it is really necessary

**Comment by aneesh1122** [comment]
@Jcarz100204 are the reworked tracks available in YouTube music?

**Comment by Jcarz100204** [comment]
They re getting there soons as realesed

**Comment by aneesh1122** [comment]
> They re getting there soons as realesed

I just checked, yt music and RiMusic has the same songs. If yt music doesn't include reworked tracks then RiMusic won't either

**Comment by Jcarz100204** [comment]
This album has a music called "maybe" that late turned into forever and shortened, the music is on RiMusic but in the album maybe its still there

**Comment by aneesh1122** [comment]
> This album has a music called "maybe" that late turned into forever and shortened, the music is on RiMusic but in the album maybe its still there

The song "forever" exists in both YT music and RiMusic and they both have the same song duration.

RiMusic gets songs from YT Music so in RiMusic you'll only get what's there in YT music

**Comment by Jcarz100204** [comment]
Wrong music bro, but if you say so i believe in u

**Comment by aneesh1122** [comment]
> Wrong music bro, but if you say so i believe in u

It can be fixed only if there are any differences between music you get in YT music and in RiMusic.

If there are any differences you have to explain it because by simply looking there seems to be no difference but I've not played the songs.

**Comment by Jcarz100204** [comment]
The mixing of the songs

**Comment by Jcarz100204** [comment]
Yo so just coming to say that the music actually updated just didnt chaged the name

**Comment by fast4x** [comment]
I've checked this functionality, confirm rhat album is autosync always.

**Comment by Jcarz100204** [comment]
Just gotta download it again and it updates

**Comment by aneesh1122** [comment]
> Just gotta download it again and it updates

You should have mentioned that you've downloaded those songs. No wonder you were having old versions
