### ISSUE TITLE
Error al traducir las letras de las canciones 

### ISSUE THREAD

**Issue by Saint-97** [fast4x/RiMusic#3115]
### Steps to reproduce the bug

Entrar a la app, reproducir cualquier canción, en el reproductor dar click para poner las letras, en el recuadro donde aparece la letra, dar click en los tres puntos, ahí aparecerá la opción de traducir, procede a traducir la letra a cualquier idioma, una vez traducida, desplazar la letra hacia abajo y con el tiempo la app se congelara, después saltara el error de Android que la app no responde.

### Expected behavior

El comportamiento esperado es que uno pueda leer la letra al compás de la canción.

### Actual behavior

Se congela la app y se cierra 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/35e4bf52-3f89-4e71-9849-872b1e672b52

### RiMusic version

0.6.44

### Android version

Android 12

### Additional information

Echo desde un poco x3 pro

**Comment by fast4x** [comment]
Your version is old

**Comment by Saint-97** [comment]
0.6.46 también está el bug

**Comment by twistios** [comment]
I think the language you have used is Spanish but I am not sure as the text seems to be not the same.

This is with 0.6.46.

![Screenshot_20240805_151635](https://github.com/user-attachments/assets/232ab5b6-ceb4-4d88-8be5-b18f49229ad5)

**Comment by Saint-97** [comment]
Si, es español, y la letra es la misma pero en mi caso está el /r después de cada estrofa, es curioso la verdad, tengo un pocophone x3 pro no se si eso tenga algo que ver, si el desarrollador lee esto, creo que el error esta en activar la letra de las canciones y no específicamente al traducir.
