### ISSUE TITLE
Notification music player Dynamic theme

### ISSUE THREAD

**Issue by GhostRider011** [fast4x/RiMusic#3117]
### Description

I have seen the color combination of the album or music cover on the music player on the notification bar in samsung music. Would like to see that here. Really makes a big difference where the whole app matches the music cover

### Suggested Solution

Please consider my request

**Comment by aneesh1122** [comment]
It's already in RiMusic. Use dynamic theme

**Comment by GhostRider011** [comment]
Its not just the music player. The player in the notifications panel as well. Is it there?

**Comment by aneesh1122** [comment]
> The player in the notifications panel as well

I'm using a xiaomi device and I do have color according to the album cover and I think it depends upon your mobile's brand since sometimes notification color and player color differs.

**Comment by GhostRider011** [comment]
> > The player in the notifications panel as well
> 
> I'm using a xiaomi device and I do have color according to the album cover and I think it depends upon your mobile's brand since sometimes notification color and player color differs.

Oh I see. I am using a samsung device. Well thanks for clarifying asw. 👍 dunno why I cant have it
