### ISSUE TITLE
[Feature]: Add actions for selected songs

### ISSUE THREAD

**Issue by gauze756** [fast4x/RiMusic#3118]
### Description

There is an option to select songs on album pages by pressing 3 horizontal dots under album name. However there is no option to do anything with selected songs.

### Suggested Solution

Give options to user after selecting songs under albums.
Options might be:

1. Add selected songs to playlist
2. "Like" selected songs
3. Enqueue

**Comment by fast4x** [comment]
Look![Screenshot_2024-08-06-07-27-25-676_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/dd454641-ab1a-45c8-8e34-a174ebb62d84)
