### ISSUE TITLE
No me funciona el buscador en mi HUAWEI Nova 9SE

### ISSUE THREAD

**Issue by JonacZ04** [fast4x/RiMusic#3120]
### Steps to reproduce the bug

Le di click en buscar y no me permite escribir 

### Expected behavior

Debería escribir lo que estoy buscando 

### Actual behavior

No funcionó 

### Screenshots/Screen recordings

No funcionó 

### RiMusic version

0.6.46

### Android version

12

**Comment by fast4x** [comment]
Too generic info, please explain better
