### ISSUE TITLE
Idea! ❤️

### ISSUE THREAD

**Issue by Unknown1122331** [fast4x/RiMusic#3123]
### Description

Account option.

### Suggested Solution

I would like it to implement the accounts option, basically being able to create an account to save the data, and the configuration that the user adapts to their own style. I know it's hard to implement things like this but I would really like it since I love the application but I have other devices and it is very tiring to go through the songs one by one.

**Comment by gauze756** [comment]
Use piped account for syncing songs?

**Comment by fast4x** [comment]
If you mean google YTM account, isn't planned. Can connect a piped account and sync over all devices.
