### ISSUE TITLE
[Feature]: add option to change app icon color

### ISSUE THREAD

**Issue by helsingi** [fast4x/RiMusic#3124]
### Description

Hi, would be nice to have the option to change the color of the app icon. Some apps have that option such as the Fossify.org apps and it's a very cool customization feature! I hope you can add it!

### Suggested Solution

![Screenshot_20240804-231736_Trebuchet](https://github.com/user-attachments/assets/f5b96bd0-025b-4f88-bbe2-bdaaa62bb148)

**Comment by fast4x** [comment]
In RiMusic app logo follow colors in dynamic mode

**Comment by helsingi** [comment]
> In RiMusic app logo follow colors in dynamic mode

no, I mean the app Icon not the logo. The app icon is always green now. I am suggesting customizing it.

**Comment by helsingi** [comment]
![Screenshot](https://github.com/user-attachments/assets/8cf6a11f-a701-4a75-8a72-dc685f042e50)

**Comment by fast4x** [comment]
Isn't, planned, sorry.

**Comment by cMattw** [comment]
at that point they might as well just add the ability to change the app name

**Comment by helsingi** [comment]
@cMattw > at that point they might as well just add the ability to change the app name

That's already possible by using [LawnChair](https://github.com/LawnchairLauncher/lawnchair)

**Comment by cMattw** [comment]
> That's already possible by using [LawnChair](https://github.com/LawnchairLauncher/lawnchair)

I was being sarcastic
