### ISSUE TITLE
Does not show the album cover on some of the downloaded songs.

### ISSUE THREAD

**Issue by AXN-Developers** [fast4x/RiMusic#3127]
### Steps to reproduce the bug

I decided to try download mode to try it out and see what it was like.

### Expected behavior

I discovered that as I returned the songs from nowhere the cover art did not appear.

### Actual behavior

At that moment I honestly don't know if it is an error in the app, a bug or cache problems.

### Screenshots/Screen recordings

![Screenshot_20240804-163827](https://github.com/user-attachments/assets/5229507a-45d1-4c95-8ae8-f198281cdcb5)

### RiMusic version

0.6.46

### Android version

Android 10

**Comment by fast4x** [comment]
Disable thumbnail, not occur because image is in the background.
