### ISSUE TITLE
Skip silence has no minimum duration to skip

### ISSUE THREAD

**Issue by yonatan8070** [fast4x/RiMusic#3128]
### Steps to reproduce the bug

1. Disable UI > Skip silence
2. Play Out of Tartarus by Darren Korb
3. Skip to 1:00
4. Listen to how the track sounds normally
5. Enable UI > Skip silence
6. Play Out of Tartarus by Darren Korb again
7. Skip to 1:00
8. Listen to how it sounds now

### Expected behavior

Skip silence should have a (possibly configurable) minimum silence time to avoid skipping very short silent parts of the track.

### Actual behavior

The small silent part of the track gets skipped, breaking the track's beat

### RiMusic version

0.6.46

### Android version

Android 13

### Additional information

If a minimum silence duration setting isn't desired, I think that 750ms to 1500ms would be a good default to use. However, testing is required.

**Comment by fast4x** [comment]
This isn't a bug, it's a new feature...

**Comment by yonatan8070** [comment]
In cases where a song goes silent for several seconds, I agree it's a great feature. But in cases where the silence is really short I think it sounds wrong (like in the song I referenced)

**Comment by fast4x** [comment]
Implemented, available from verson 0.6.47
