### ISSUE TITLE
Songs not play at all when the v2ray http VPN on 

### ISSUE THREAD

**Issue by Lalithagala** [fast4x/RiMusic#3130]
### Steps to reproduce the bug

Song not playing at all (I use http and v2ray VPN ) but It was worked before 

### Expected behavior

Song might be play as normal 

### Actual behavior

If I click on the song it doesn't play just keeping the template nothing happened 

### Screenshots/Screen recordings

![Screenshot_20240805-191356](https://github.com/user-attachments/assets/4fc87925-2400-478b-9911-04bce8ee4571)

### RiMusic version

Latest 

### Android version

Android 10

**Comment by fast4x** [comment]
Check your vpn location, it seems not work with YT Music

**Comment by Lalithagala** [comment]
My VPN location usually Singapore and usa didn't had any issues before but after few updates it's seems not working at all

**Comment by fast4x** [comment]
I haven't changed anything related data  connection

**Comment by Tribbtsz** [comment]
It seems to be an issue with the API interface. The same problem has occurred on Vitune and Vimusic (they use the same api). There is a discussion [here](https://github.com/25huizengek1/ViTune/issues/398#issue-2438082264), and the conclusion is that it is related to the VPN location.

**Comment by fast4x** [comment]
Have you tried proxy connection instead of vpn?

Perhaps in next version there's an improvement, wait for it.

**Comment by Tribbtsz** [comment]
i have tried some proxies using Clash(meta core) and also tested some different protocol:
| location  | protocol | rimusic,vitune,vimusic | yt/ytm |
|--------|--------|--------|--------|
|US | vless | y | y|
|US | hysteria2| y | y|
|US | vmess| y | y|
|US| trojan(self-hosted)|-|y|
|US | hysteria2(self-hosted) |-|y|
| Tokyo|vless |y | y|
| Tokyo|hysteria2|y | y|
|Tokyo| vmess| y | y|
|Singapore|vless|y|y|
|Singapore|hysteria2|y|y|
|Singapore| vmess| y | y|
---
Additionally, some of the above results include tests with different operators (in China). My self-hosted nodes might not have more secure and private strategies, but up until today, I've been using them to normally access rimusic/vitune/vimusic. Given these results, it doesn't seem to be simply attributable to the location of the nodes?

**Comment by fast4x** [comment]
Of course it could, it would be interesting to have a log of debub from RiMusic.
I have to try to implement it in the communication module.

**Comment by Tribbtsz** [comment]
I'm not sure if this will be helpful: I tried to use the command ```adb logcat *:E | findstr it.fast4x.rimusic``` to output the logs. When an abnormal proxy was used, the following content appeared in the logs:
```
08-09 21:04:02.797  2093  2379 E ActivityManagerWrapper: getRecentTasks: taskId=1055   userId=0   baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=it.fast4x.rimusic/.MainActivity }
08-09 21:05:47.729   714   812 E BufferQueueDebug: [Splash Screen it.fast4x.rimusic#0](this:0xb4000071ecdcb8d0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Splash Screen it.fast4x.rimusic#0'
08-09 21:05:47.793  3432  6128 E SuggestManager: openApp name = it.fast4x.rimusic
08-09 21:05:47.824  2093  2379 E ActivityManagerWrapper: getRecentTasks: taskId=1056   userId=0   baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=it.fast4x.rimusic/.MainActivity }
08-09 21:05:48.037   714   813 E BufferQueueDebug: [it.fast4x.rimusic/it.fast4x.rimusic.MainActivity#0](this:0xb4000071ecaac8d0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'it.fast4x.rimusic/it.fast4x.rimusic.MainActivity#0'
08-09 21:06:01.151   714   812 E BufferQueueDebug: [it.fast4x.rimusic/it.fast4x.rimusic.MainActivity#1](this:0xb4000071fa4478d0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'it.fast4x.rimusic/it.fast4x.rimusic.MainActivity#1'
08-09 21:06:02.049  1438  1631 E NotificationService: Package has already queued 5 toasts. Not showing more. Package=it.fast4x.rimusic
08-09 21:06:02.084  1438  1631 E NotificationService: Package has already queued 5 toasts. Not showing more. Package=it.fast4x.rimusic08-09 21:06:05.752  1438  1452 E NotificationService: Package has already queued 5 toasts. Not showing more. Package=it.fast4x.rimusic
08-09 21:06:05.781  1438  4052 E NotificationService: Package has already queued 5 toasts. Not showing more. Package=it.fast4x.rimusic
```
