### ISSUE TITLE
Acount

### ISSUE THREAD

**Issue by victorinyo2** [fast4x/RiMusic#3133]
### Description

I would like to see the login function implemented.

### Suggested Solution

I would like a login to make it easier to save playlists. For example, if I change my phone, I lose all my saved songs, but if this option existed it would be easier to keep the playlist.

### Alternatives

An alternative to login would be to be able to download a file with all this information and be able to import it into the application more easily, this without login is very difficult to implement.

**Comment by twistios** [comment]
The has support for piped-login.

**Comment by fast4x** [comment]
Google login isn't planned because it require proprietary library.
