### ISSUE TITLE
Equalizer

### ISSUE THREAD

**Issue by XGhostRX** [fast4x/RiMusic#3135]
### Steps to reproduce the bug

I would like to know which equalizer is compatible with the player

https://github.com/user-attachments/assets/dc7e61c8-65c0-4a83-ae1d-dd861487e9bb

### Expected behavior

View equalizer options

### Actual behavior

Ask me for a possible app
But I don't know which one
Any suggestions? 

### Logs

2024-08-05 15:55:18:328 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs

### RiMusic version

0.6.46

### Android version

Android 10

### Additional information

Use huawei p30 lite MAR-LX3A

**Comment by twistios** [comment]
The app uses the system equivalizer of the phone. I should be located at `Sounds and vibration > Sound quality and effects` menu (I don't know if this is the english name). The location depends on the phone.

Based on the notification that is shown in the screenshot it seems like it does not find the Equalizer. Maybe your phone does not have one. It can be that it then won't work. Maybe fast4x or aneesh1122 knows something about this.

**Comment by XGhostRX** [comment]
I think the same app should have one

**Comment by fast4x** [comment]
In the future will be added but i don't know if it will be compatible with certain devices.
