### ISSUE TITLE
Own equalizer from the app

### ISSUE THREAD

**Issue by XGhostRX** [fast4x/RiMusic#3137]
### Description

I would recommend that this app have its own equalizer
Since most apps for this have ads and most don't even work

https://github.com/user-attachments/assets/54b2d26f-b13b-4477-ac11-02002927ab28

### Suggested Solution

An equalizer from the app
Avoid problems with others that don't work either

### Alternatives

Problems in searching for an incompatible equalizer app are avoided 

### Additional Context

Difficulty in looking for an equalizer that does work

**Comment by fast4x** [comment]
Maybe depend by your device?

**Comment by XGhostRX** [comment]
Sadly

**Comment by gauze756** [comment]
Use wavelet. [Wavelet](https://github.com/Pittvandewitt/Wavelet)

**Comment by XGhostRX** [comment]
Recently I found an app with more features called "Flat Equalizer"
But thanks anyway 👍
