### ISSUE TITLE
Pasar musicas desde spotify

### ISSUE THREAD

**Issue by Edd-by02** [fast4x/RiMusic#3139]
### Description

He visto que se puede exportar listas de reproduccion aunque aun no descubro como importarlas y he tenido que pasar musica por musica desde spotify

### Suggested Solution

Pongan una funcion que facilite el crear listas de musica o poder importar desde spotify

**Comment by fast4x** [comment]
https://www.tunemymusic.com/transfer/spotify-to-youtube-music

https://soundiiz.com/tutorial/spotify-to-youtube-music

You have to transfer playlist to YouTube Music and can share with RiMusic and import.
