### ISSUE TITLE
Synchronized Song Lyrics

### ISSUE THREAD

**Issue by TheLionWarrior** [fast4x/RiMusic#3141]
### Steps to reproduce the bug

1. Play a song.
2. Open the song .
3. Select lyrics button and select the 3 points.
4. Select synchronized lyrics.
5. The application closes suddenly.

### Expected behavior

It is expected to hear and read the lyrics of the song.

### Actual behavior

The application crash when selecting synchronized lyrics .

### Screenshots/Screen recordings

[https://drive.google.com/file/d/1aMuppvBVjh_8Al5d2zE7FKbATTN1HuUy/view?usp=drivesdk](url)

### RiMusic version

0.6.45.1

### Android version

13

**Comment by fast4x** [comment]
Use latest version 0.6.46
