### ISSUE TITLE
Cached songs tab

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [fast4x/RiMusic#3144]
### Steps to reproduce the bug

Go to cached tab

### Expected behavior

It should load only the cached songs

### Actual behavior

It does nothing

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/9f5e694c-dca4-4ba9-baf9-58ddaa57bfb9

### RiMusic version

0.6.46

### Android version

Miui 11 a10

### Additional information

Need it broooo

**Comment by twistios** [comment]
I also noticed that. But it looked to me that I had to do something that it happened, but not sure what exactly.

Also it seems to be not exactly the same, as the number of songs is not the same.

**Comment by fast4x** [comment]
Maybe total number of cached is equal total of songs..

**Comment by twistios** [comment]
@fast4x 
![Screenshot_20240806_113745](https://github.com/user-attachments/assets/6e082e9c-aa97-4725-9468-1d7bbbf781a1)

**Comment by fast4x** [comment]
Ah ok I'll check it

**Comment by twistios** [comment]
I think it also includes partially cached songs.

**Comment by fast4x** [comment]
Today i fix it

**Comment by twistios** [comment]
It looks like even `binder?.cache?.isCached` returns `true` even if it says **not** 100% in stats for nerds.

**Comment by twistios** [comment]
It seems like you did some rewrite (to fix #3019) that includes that the check for beeing fully cached is not done anymore.

**Comment by fast4x** [comment]
Yes, it's fixed in ...47

**Comment by ALMIGHTY-VC** [comment]
Bruh my cached songs tab DÆD i mean now its not visible now?!😅

**Comment by fast4x** [comment]
Yes cached is inside downloaded tab
