### ISSUE TITLE
Una canción no se reproduce 

### ISSUE THREAD

**Issue by JossGor** [fast4x/RiMusic#3145]
### Steps to reproduce the bug

Buscando el álbum Better Of Dead de Josh A la canción Suicidal Thoughts la canción lanza un error.

### Expected behavior

Debería tardar máximo 1 segundo en comenzar la reproducción 

### Actual behavior

El temporizador de la canción y del álbum están en 0 y tarda más de 10 segundos en aparecer el mensaje de error

### Screenshots/Screen recordings

![Screenshot_20240806_030531](https://github.com/user-attachments/assets/db91e075-b39b-4ef5-a071-c93b12143a87)

### RiMusic version

0.6.44

### Android version

Android 13

**Comment by twistios** [comment]
You should update to 0.6.46.
