### ISSUE TITLE
Oh no

### ISSUE THREAD

**Issue by Snaydhersito** [fast4x/RiMusic#3146]
### Steps to reproduce the bug

First: look for a song that gives you a warning that it does have content regarding a controversial topic. second: it won't let you play it and it won't play anything, it won't even let you download it

### Expected behavior

No

### Actual behavior

No se

### Screenshots/Screen recordings

![Screenshot_20240806_041407_YouTube Music](https://github.com/user-attachments/assets/853bb792-4dfd-478f-a97f-1c567b7974a6)
![Screenshot_20240806_041308](https://github.com/user-attachments/assets/2c375f28-ce7e-495b-9595-0ab104643615)

### Logs

La vdd no se

### RiMusic version

v0.6.46.

### Android version

Android 12

### Additional information

As you will notice, on YouTube Music it warns me and gives me the option to ignore the notice and play the song, however on Vimusic it doesn't let you play the song or download it.

**Comment by fast4x** [comment]
It's normal.
Attention you have mentioned ViMusic and not RiMusic...
