### ISSUE TITLE
Saran

### ISSUE THREAD

**Issue by ghyvpine** [fast4x/RiMusic#315]
### Description

Saran fitur

### Suggested Solution

Sepertinya jika bisa login akun google akan jadi bagus seperti inner tune dan samp music

### Alternatives

Mungkin kau bisa minta sumber kepada mereka

### Additional Context

Tidak ada

**Comment by Logan7899** [comment]
Description

Feature suggestions
Suggested Solution

It looks like if you can log in to your Google account it will be good like inner tune and samp music
Alternatives

Maybe you can ask them for sources
Additional Context

There isn't any

**Comment by fast4x** [comment]
Actually isn't planned a Google login

**Comment by DeadSecTr** [comment]
Please dont implement any google crap

**Comment by fast4x** [comment]
Sorry, thanks for the request anyway

**Comment by ikanakova** [comment]
❓ Why are there no plans to implement Google/YouTube login?

➡️ Implementing Google/YouTube login would require a Google tracker for authentication, which would invade the privacy of all users. In addition, it would probably not be possible to publish the app on F-Droid.

**Comment by ikanakova** [comment]
Explanation also in [FAQ](https://github.com/fast4x/RiMusic/wiki/FAQs#-why-are-there-no-plans-to-implement-googleyoutube-login).
