### ISSUE TITLE
Continuous play in playlists 

### ISSUE THREAD

**Issue by ramon3971** [fast4x/RiMusic#3150]
### Steps to reproduce the bug

I create a playlist 
From my downloaded music I add the songs to the newly created playlist 
Then I go to my playlists and the songs do not play automatically when I press the next song button it plays the same song again 

### Expected behavior

When playing a playlist, all the songs it contains are played without any problem 

### Actual behavior

Only the song you select plays and when it's finished it starts again 
To clarify, the loop option is not selected.

### RiMusic version

0.6.44

### Android version

Android 13

**Comment by cheeslyanger** [comment]
Same

**Comment by jsuelwald** [comment]
This seems to be fixed in https://github.com/fast4x/RiMusic/releases/tag/v0.6.46 

Running that currently on Samsung Galaxy Fold 5.

**Comment by TB1333** [comment]
Just created a github account to post the exactly same bug. 😄
