### ISSUE TITLE
Bugs when disabling battery optimization

### ISSUE THREAD

**Issue by XGhostRX** [fast4x/RiMusic#3151]
### Steps to reproduce the bug

To disable battery optimization for this app, the player notification still appears after you stop listening to music and go out normally

### Expected behavior

That the app closes completely when you leave

### Actual behavior

Player notification keeps popping up when you stop playing music and exit normally

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/7da2a790-6966-4aba-87d2-fd53b4061c7f

### RiMusic version

0.6.46

### Android version

Android 10

### Additional information

The player notification appears constantly even if I don't use the app

**Comment by fast4x** [comment]
Enable close player background in ui settings

**Comment by XGhostRX** [comment]
I think it's the option to disable battery optimization
