### ISSUE TITLE
No reproduce la siguiente cancion 

### ISSUE THREAD

**Issue by Lensiod** [fast4x/RiMusic#3153]
### Steps to reproduce the bug

No reproduce la siguiente canción igual si esta en una lista de reproducción solo reproduce en bucle la misma canción solo reproduce otra canción si cambio manualmente. Gracias por leer que tengas un lindo día 

### Expected behavior

Que se pueda arreglar el problema 

### Actual behavior

Y actualmente no puedo escuchar mi reproducción de forma tranquila 

### RiMusic version

0.6.45.1 by fast4x

### Android version

Android 14

### Additional information

Solo reproduce la misma canción sin importar que se ponga otra canción en cola de reproducción

**Comment by fast4x** [comment]
Maybe loop is enabled?

**Comment by Lensiod** [comment]
No esta habilitado

**Comment by fast4x** [comment]
wait for new release
