### ISSUE TITLE
Music acceleration

### ISSUE THREAD

**Issue by cristianderudi** [fast4x/RiMusic#3160]
### Steps to reproduce the bug

Play Music

### Expected behavior

The music should flow without accelerations.

### Actual behavior

Plays sped-up music randomly in parts.

### RiMusic version

v0.6.46

### Android version

Android 11

**Comment by fast4x** [comment]
Long tap on player/pause button and set to default all sliders

**Comment by cristianderudi** [comment]
> Long tap on player/pause button and set to default all sliders

Thank you for your response. I did as you instructed, but the problem persists

**Comment by cMattw** [comment]
turn off the "Skip silence" option on ui settings

**Comment by cristianderudi** [comment]
> turn off the "Skip silence" option on ui settings

Thank you, it seems to be working for now.
