### ISSUE TITLE
Rimusic 

### ISSUE THREAD

**Issue by Razul79** [fast4x/RiMusic#3163]
### Steps to reproduce the bug

1- cuando estoy en otras apps mientras escucho la música y quiero entrar a la app por medio del reproductor se cierra el reproductor 
2- quiero saber si lo puedo arreglar con la confirmación o es solo un bug 

### Expected behavior

Que me redirija a la app y no se cierre 

### Actual behavior

Que me abra la app y no se detenga la música 

### Screenshots/Screen recordings

Se detiene la música cuando quiero entrar a la app mediante el reproductor flotante cuando salgo de la app 

### RiMusic version

v0.6.46

### Android version

Android 10 con Miui 12

### Additional information

Se detiene la música después de un tiempo

**Comment by fast4x** [comment]
Enable invincible service in miscellanous settings
