### ISSUE TITLE
Importar Canciones

### ISSUE THREAD

**Issue by Juniior01** [fast4x/RiMusic#3164]
### Description

Importing files and URLs, etc. in the Rimusic application would be a great idea 

### Suggested Solution

That you can import a playlist, with file url, etc.

### Alternatives

Or simply be able to transfer the likes from vimusic to rimusic

### Additional Context

I don't want to play all my songs again

**Comment by fast4x** [comment]
All it's just available:

1. import playlist from youtube/youtube music share it from youtube music to RiMusic
2. copy link url, go to search > go to link
3. from ViMusic export a backp and in RiMusic restore this backup
All done
