### ISSUE TITLE
App crash at the end of the songs list

### ISSUE THREAD

**Issue by Frozi334** [fast4x/RiMusic#3165]
### Steps to reproduce the bug

1. Go to the favourite songs
2. Scroll to the end of the list 
3. Select any song and try to play it

### Expected behavior

A song should play as if I pressed it at the start of the list

### Actual behavior

When I scroll to the end and tap on a song to play, the app crashes

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/18af0500-9631-4b71-8dcb-c4c86906d32d

### Logs

![Screenshot_2024-08-07-23-58-24-029_com miui bugreport-edit](https://github.com/user-attachments/assets/8fc9e553-87e7-4464-8bc9-6ecccfa3668e)

### RiMusic version

0.6.46

### Android version

Android 14

**Comment by twistios** [comment]
You can get the log as a text after you enable debug mode in settings, reproduce the crash and then go to the location in settings again where debug gets enabled. There you can copy the crash log to the clip board.

**Comment by Frozi334** [comment]
Now the app doesn't want to load songs 💀

Here are the logs:

**Comment by twistios** [comment]
Sorry, I was not clear enough with what I meant. There are two types of logs: debug logs and crash logs. In case of a crash, the crash log is most useful. So please attach this log too.

The debug log is also impressive as it shows an amount of errors that I have not yet seen before.

**Comment by Frozi334** [comment]
No, no. I understood. But the bug somehow disappeared, so I have no idea what was that exactly. But for now, I guess I'm having a problem with the downloading songs. When I try to use my WiFi, they doesn't load at all, but when I use my phone internet, then everything is normal. It's strange because I haven't had this problem  before.

**Comment by Frozi334** [comment]
2024-08-09 00:48:57:161 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs

**Comment by Frozi334** [comment]
New logs

https://disk.yandex.ru/i/GJDazm6cS8qCGA

**Comment by Frozi334** [comment]
I think I know the reason. I'm from Russia and YouTube is mostly blocked here. I guess when the app tries to load a song, it fails... only VPN helps 😔

**Comment by twistios** [comment]
You can also try this:
https://github.com/fast4x/RiMusic/wiki/FAQs#where-can-find-free-proxy-list

**Comment by Frozi334** [comment]
Yeah, thank you. Also want to mention that your app is awesome. One of the most stable and well-designed. Keep it up, my friend 😎
