### ISSUE TITLE
App closes automatically 

### ISSUE THREAD

**Issue by AndresVega21** [fast4x/RiMusic#3166]
### Steps to reproduce the bug

I try to use the app.apk to have the experience as a listening user, but the app closes automatically at any time. I hope they can fix this as soon as possible. Thank you!

### Expected behavior

This happens when you are about to start or finish listening to a song 

### Actual behavior

This happens when you are about to start or finish listening to a song 

### RiMusic version

0.6.46

### Android version

Android 13

**Comment by fast4x** [comment]
Enable log in miscellaneous settings and after crash paste log here please
