### ISSUE TITLE
Charts Feature is not working.

### ISSUE THREAD

**Issue by coolswapnil** [fast4x/RiMusic#3167]
### Steps to reproduce the bug

1. Go to Settings -- Quick Picks -- Enable Show Charts feature.
2. Come out of settings and go to Quick Picks of player.
3. Nothing is visible or shown in charts (Only Chart text is there nothing else)

### Expected behavior

When charts feature is enabled it should show some sort of list of top artist, trending songs and top music videos etc. based on the region/country.
Sample screenshot from YouTube is attached
![Screenshot_2024-08-08-10-57-03-498_com google android apps youtube music](https://github.com/user-attachments/assets/49cc3243-1ba1-4173-b41a-82c840428578)

### Actual behavior

Nothing is visible in Charts, just Charts 
![IMG_20240808_110741](https://github.com/user-attachments/assets/10abea73-9f58-448a-9b0a-1faf51314953)
text can be seen.

### Screenshots/Screen recordings

![Screenshot_2024-08-08-10-57-03-498_com google android apps youtube music](https://github.com/user-attachments/assets/e64165b1-7edd-45c0-bef6-0631b7021f78)
![IMG_20240808_110741](https://github.com/user-attachments/assets/31a9d932-20d1-4ec6-94ac-48ff8e1bc11f)

### RiMusic version

v0.6.46

### Android version

Android 14

**Comment by fast4x** [comment]
What's app in the screenshot?

**Comment by aneesh1122** [comment]
> What's app in the screenshot?

YouTube music

**Comment by fast4x** [comment]
> > What's app in the screenshot?
> 
> YouTube music

ok i understand, it's other api... I'll check it

**Comment by fast4x** [comment]
Implemented country charts, available from version 0.6.47

**Comment by aneesh1122** [comment]
> Implemented country charts, available from version 0.6.47

Thanks man :)

**Comment by coolswapnil** [comment]
Thanks 😊

**Comment by fast4x** [comment]
> Thanks 😊

You are welcome
