### ISSUE TITLE
Player Music Title and Artist Name Automatic Adaptability on the Theme of Song to be Readable 

### ISSUE THREAD

**Issue by Emben17** [fast4x/RiMusic#3169]
### Description

Whenever I play a music with a blurred thumbnail background along with song having a dark thumbnail the music title and the artist name is not readable because it is built-in to be just black in color.

### Suggested Solution

I suggest you make the song title and the artist name to be adaptable to the theme of the song thumbnail or color to be readable due to the background choice is blurred song cover. Thank you

**Comment by twistios** [comment]
There exists the "text outline" feature.
