### ISSUE TITLE
i found the fonts

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#317]
### Description

Hey i appreciate your work, Actually I am custom rom user and i found a font that matches your app and also one issue when i open app the start up screen is black ehere the icon shows when you open up app. This creates a tonal inconsistent as you are using your app in light mode but the app startup screen is black.
![Screenshot_20240102-222854_RiMusic](https://github.com/fast4x/RiMusic/assets/120176369/18f2b0e4-e32b-463b-bd65-258463b70223)
![Screenshot_20240102-222538_Twist Music]
![Screenshot_20240102-223519_RiMusic](https://github.com/fast4x/RiMusic/assets/120176369/c3dc2319-3ab6-488f-bc41-7e050a84e957)

Thia font is called cookie run

### Suggested Solution

Hope you fix the problem for more minimalistic look

### Additional Context

Thank you. I appreciate that you always reads feedback from your user😄😄

**Comment by ikanakova** [comment]
Cookie Run is not multilingual enough according to the [picture](https://fontswan.com/wp-content/uploads/Cookie_Run_Font-5.webp), for example there is no Czech "Č".

**Comment by ikanakova** [comment]
I think either this issue or #305 could end because they are duplicates. Or both and create a new discussion on font suggestions.
They should comply that they will support the languages the application is translated into and be under the Open Font License (OFL).

**Comment by fast4x** [comment]
> @fast4x I think either this issue or #305 could be closed because they are duplicates or both issue and create a new discussion on font suggestions.
> Suggested fonts should at least support the languages the application is translated into. And be under the Open Font License (OFL).

Sure, create the discussion.

**Comment by ikanakova** [comment]
> > @fast4x I think either this issue or #305 could be closed because they are duplicates or both issue and create a new discussion on font suggestions.
> > Suggested fonts should at least support the languages the application is translated into. And be under the Open Font License (OFL).
> 
> Sure, create the discussion.

OK, discussion created - #349
