### ISSUE TITLE
Cannot disable shuffle

### ISSUE THREAD

**Issue by boubasse** [fast4x/RiMusic#3170]
### Steps to reproduce the bug

1. Go in a playlist / album
2. Play a song
3. Click on the shuffle button to deactivate

### Expected behavior

The shuffling feature should deactivate when clicking on it to avoid playing songs in random order

### Actual behavior

The shuffle stays activated when clicking on the button ...

### RiMusic version

0.6.46

### Android version

Android 14

**Comment by twistios** [comment]
If you open a song via a playlist, the songs should be in order.
Also see #3023.

**Comment by fast4x** [comment]
It's one time shuffle, permanent shuffle will be developed soon
