### ISSUE TITLE
Add no lyrics found instead of showing a pop 

### ISSUE THREAD

**Issue by Gauravchaubey66** [fast4x/RiMusic#3171]
### Description

When ever some songs lyrics not found it's showing lyrics not found in a pop that is good but placing a text as before  lyrics not found is more convenient for user along with improvement in ui experience .
![Screenshot_20240808_153624](https://github.com/user-attachments/assets/8ffe68f1-3747-4a38-8464-d0ae8cde9f0f)

### Suggested Solution

Add text in the place of lyrics when there is no lyrics found of that song .

### Additional Context

And that pop up only shows first te when we go through that song for second time its blank nothing shows

**Comment by fast4x** [comment]
This popu can be disabled by settings.
