### ISSUE TITLE
Me salta que la canción no puede ser reproducida 

### ISSUE THREAD

**Issue by Julan2** [fast4x/RiMusic#3172]
### Steps to reproduce the bug

1. Buscar el tema 
2. Seleccionar el tema 
3. Salta el error al intentar reproducir la canción.

### Expected behavior

1. Buscar el tama 
2. Seleccionar el tema 
3. Que la canción se reproduzca sin inconvenientes 

### Actual behavior

1. Buscar el tema 
2. Seleccionar el tema 
3. Salta el error al intentar reproducir la canción.

### Screenshots/Screen recordings

![Screenshot_20240808_103557](https://github.com/user-attachments/assets/509d84c0-94cd-4bcf-aa25-0c13c243a5ed)

### RiMusic version

0.6.46

### Android version

Android 12

### Additional information

Me podrían ayudar por favor 😸

**Comment by fast4x** [comment]
Wait for new release 0.6.47, it seems to be fixed
