### ISSUE TITLE
[Feature]: Request Interlingua language translation at Crowdin

### ISSUE THREAD

**Issue by softinterlingua** [fast4x/RiMusic#3173]
### Description

I'm very interested to translate RiMusic to Interlingua (lang code:ia) but unfortunately Crowdin does not support officially this language so i need to request to add it as a "custom language". 

### Suggested Solution

I want to request to add Interlingua (as a custom language) for RiMusic translation.

If needed you can use this data:
Language name: Interlingua
The dialect of: Latin
Crowdin code: ia
Three letters code: ina
Locale code: ia (if country code is required, use ia-FR)
Text direction: Left to right
Plural forms: one, other

### Additional Context

Crowdin support team sent me this guide:  (https://support.crowdin.com/changing-target-languages/?q=custom%20language) 

This formula was used to enable [our Mastodon apps translations](https://crowdin.com/project/mastodon/ia), which also uses Crowdin to manage it.

As a reference, you have another apps translated by us in [our X account](https://x.com/softinterlingua). 

Thank you in advance.

**Comment by fast4x** [comment]
Hi, done, Interlingua is ready for translation, thanks for interest.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.47
