### ISSUE TITLE
Error in translation file (string xml)

### ISSUE THREAD

**Issue by frenchy82** [fast4x/RiMusic#3178]
### Steps to reproduce the bug

In riMusic you can choose "For You", **"Random"**. It's the third choice with "For You"

But in the file "string.xml", i think it's the key "**by_casual_played_song**"

So what should be the real  key. Random or casual song? Because it's different for translation

In french the translation should be wrong. it is currently "par les titres joués recemment"  (By recently played titles)

I don't know if i should correct the french translation  from "random" or "casual played song"

### Expected behavior

See the description

### Actual behavior

.

### RiMusic version

RiMusic 0.6.46

### Android version

android 12

**Comment by faustaahmad** [comment]
iirc, I did change the translation into "Random"
Because it'll actually refresh song recommendations to different songs when you used that mode (by_casual_played_song)
unlike the other mode (By Most/Last Played)

Feel free to change the translation in Crowdin

**Comment by frenchy82** [comment]
I've made the proposal in crowdin ("en mode aléatoire)" but I found out that it has been discussed for at least 3 months.
How can I get this wrong translation reviewed?

**Comment by faustaahmad** [comment]
Sorry for tagging @NEVARLeVrai
Im not a native French, so could you help out with this translation issue?

**Comment by NEVARLeVrai** [comment]
What issue ?

**Comment by NEVARLeVrai** [comment]
> Sorry for tagging @NEVARLeVrai
> Im not a native French, so could you help out with this translation issue?

Wait I look into it I was busy

**Comment by NEVARLeVrai** [comment]
by_casual_played_song

If you translate it is "par les titres joués récemment" Do you prefer "aléatoire"?

**Comment by NEVARLeVrai** [comment]
I approved the translation

**Comment by NEVARLeVrai** [comment]
I approved the translation

**Comment by NEVARLeVrai** [comment]
> Sorry for tagging @NEVARLeVrai
> Im not a native French, so could you help out with this translation issue?

**Comment by NEVARLeVrai** [comment]
> iirc, I did change the translation into "Random"
> Because it'll actually refresh song recommendations to different songs when you used that mode (by_casual_played_song)
> unlike the other mode (By Most/Last Played)
> 
> Feel free to change the translation in Crowdin


I just saw, after when I translate, I don't really test the application in parallel so it's complicated to have the context too, but it's good I accepted the translation

**Comment by frenchy82** [comment]
Thanks a lot !
