### ISSUE TITLE
Problemas en la reproducción de musicas 

### ISSUE THREAD

**Issue by Favito17** [fast4x/RiMusic#3179]
### Steps to reproduce the bug

La verdad no hize nd solo estaba reproduciendo mis musicas como siempre y descubriendo nuevas musicas

### Expected behavior

Yo espero que me solucionen el problema ya que me encantó esta aplicación 

### Actual behavior

Estaba escuchando mis musicas y al momento de reproducir otra música como tal me apareció un texto que decía:  " EL IDENTIFICADOR DEL VIDEO NO SE CORRESPONDE CON EL QUE SOLICITO " Y CAMBIO A OTRA MUSICA Y ME APARECE LO MISMO solo puedo escuchar las musicas que descargue 

### Screenshots/Screen recordings

![Uploading Screenshot_20240809-110
![Uploading Screenshot_20240809-110234.jpg…]()
234.jpg…]()

### Logs

Adb logcat 

### RiMusic version

v0.6.44

### Android version

Android 12

### Additional information

Después de un tiempo estando reiniciando la aplicación vuelve a reproducirse las musicas normal pero de ahí vuelta otra vez vuelve el problema .....gracias

**Comment by fast4x** [comment]
update version please

**Comment by Favito17** [comment]
> Actualice la versión por favor

Ahora me sale esta canción no puede ser reproducida debido a restricciones del servidor
