### ISSUE TITLE
Cant click songs in "on device" category

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#3180]
### Steps to reproduce the bug

・Navbar → Songs
・Click "On device"
・Try clicking a song there
Folder and back button still clickable

### Expected behavior

Could click the song

### Actual behavior

Could not click the song

### RiMusic version

0.6.46

### Android version

Android 11

### Additional information

Workaround before this issue got fixed
Songs → Shuffle icon

**Comment by twistios** [comment]
Still in 0.6.47.1 customVersion 2.
