### ISSUE TITLE
Canzoni "slittano"

### ISSUE THREAD

**Issue by St3v3do3** [fast4x/RiMusic#3181]
### Steps to reproduce the bug

Ascoltando l'ultimo album di Alice Cooper le tracce slittano (appena inizia una canzone passa alla successiva).

https://music.youtube.com/playlist?list=OLAK5uy_lksmI_UTKBv8pbGlU98NiJqZxDpck-vVM

### Expected behavior

Le tracce vengono riprodotte dall'inizio alla fine.

### Actual behavior

Le tracce vengono "saltate"

### RiMusic version

Versione 0.6.46

### Android version

Android 14

**Comment by fast4x** [comment]
Tieni premuto il tasto play/pause, dopo clicca sulla clessidra in modo da resettare la modalità Medley.
Inoltre disattiva la funzione salta silenzio nelle impostazioni.

**Comment by St3v3do3** [comment]
Ho disattivato salta silenzio ma tenendo premuto il pulsante play/pause non
vedo nessuna clessidra
Stefano Zambon
Via Roma 37/A
39100 Bolzano

Il Ven 9 Ago 2024, 19:10 Rino Russo ***@***.***> ha scritto:

**Comment by fast4x** [comment]
![Screenshot_2024-08-09-20-21-43-599_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/83ac3996-4dbc-46bb-8b29-3271af83e2d5)

**Comment by St3v3do3** [comment]
Risolto grazie mille!
Stefano Zambon
Via Roma 37/A
39100 Bolzano

Il Ven 9 Ago 2024, 20:22 Rino Russo ***@***.***> ha scritto:

**Comment by fast4x** [comment]
Prego
