### ISSUE TITLE
Request for downloaded songs to be saved on the external storage location 

### ISSUE THREAD

**Issue by KingJJ2007** [fast4x/RiMusic#3182]
### Description

My device storage is quite low,and I can't really afford to buy a new device 😔,so,I'd love if I could save my downloaded music on my SD card.
Thanks,love your application.

### Suggested Solution

Add a feature in the settings to move all downloaded songs to the SD card and save future songs on the SD card.

**Comment by aneesh1122** [comment]
Not planned

**Comment by fast4x** [comment]
Unfortunately isn't possible because songs are managed from player and isn't exportable in other location. 
RiMusic is a streaming player for YTM, not a downloader.

**Comment by aneesh1122** [comment]
> Unfortunately isn't possible because songs are managed from player and isn't exportable in other location. 

Hey fast, when is the new update coming?
