### ISSUE TITLE
Videos don't show in playlists

### ISSUE THREAD

**Issue by AstroLightz** [fast4x/RiMusic#3187]
### Steps to reproduce the bug

1. Open a playlist containing a video song, not a regular one (the ones with the song icon next to them in the player).

### Expected behavior

The video song should appear

### Actual behavior

They do not show

### Screenshots/Screen recordings

Notice how it says 29 (There are 29 songs in this playlist), but only 3 are shown.

![Screenshot_2024-08-09-19-58-48-18_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/342dd250-ce4e-46d5-990a-416623545a7c)

### RiMusic version

0.6.47

### Android version

Android 14

**Comment by cMattw** [comment]
Can confirm, happens to me too

**Comment by fast4x** [comment]
soon I'll build a custom version that you can try

**Comment by fast4x** [comment]
Please download and try custom version, send feedback please.
 
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by cMattw** [comment]
> Please download and try custom version, send feedback please.
>  
> https://github.com/fast4x/RiMusic/tree/master/customVersion

It's fixed on the custom version. Thanks for the quick fix
