### ISSUE TITLE
Error in the mini player

### ISSUE THREAD

**Issue by Wonky-png** [fast4x/RiMusic#3190]
### Steps to reproduce the bug

Error 1
-When you use the player and change the song by swiping, the player closes abruptly each time and switches to the mini player. 
Error 2
-When I updated the app everything worked normally, but if I wanted to switch from the mini player to the full screen, the app closes completely. 

### Expected behavior

When you launch the app, selecting a music should display the full player, but only launch the mini player. 

### Actual behavior

Instead of the app closing when you click there, it should display the player in full screen. 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/0bd2d562-789f-426b-97b2-d7138c69c2ff

### Logs

2024-08-09T19:42:53.374:	android.content.res.Resources$NotFoundException: File res/Dg.webp from xml type xml resource ID #0x7f0700d4
	 android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1633) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2738) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2711) 
	 android.content.res.Resources.getXml(Resources.java:1517) 
	 a.a.f0(SourceFile:59) 
	 B3.a.i(SourceFile:631) 
	 s7.o.n(SourceFile:717) 
	 a6.b.c(SourceFile:261) 
	 s7.o.t(SourceFile:1339) 
	 E6.l.e(SourceFile:255) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 A6.i.e(SourceFile:198) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 F6.d.g(SourceFile:442) 
	 e0.a.g(SourceFile:52) 
	 O.U.g(SourceFile:170) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.R1.a(SourceFile:113) 
	 T.S0.b(SourceFile:56) 
	 T.G0.g(SourceFile:214) 
	 e0.a.g(SourceFile:52) 
	 T.U0.g(SourceFile:258) 
	 e0.a.g(SourceFile:52) 
	 T.A0.a(SourceFile:52) 
	 A6.z.g(SourceFile:1206) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.p0.a(SourceFile:395) 
	 A6.X.g(SourceFile:1216) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.T.a(SourceFile:627) 
	 J0.x1.g(SourceFile:250) 
	 e0.a.g(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.x1.g(SourceFile:213) 
	 e0.a.g(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.q.p(SourceFile:203) 
	 W.u.k(SourceFile:32) 
	 W.u0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.u.l(SourceFile:9) 
	 W.u.c(SourceFile:3) 
	 B.j0.b(SourceFile:529) 
	 J0.w.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.y1.c(SourceFile:10) 
	 J0.y1.m(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 B.j0.b(SourceFile:498) 
	 J0.w.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:21785) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3678) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3947) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3225) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11121) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1938) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1946) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1226) 
	 android.view.Choreographer.doFrame(Choreographer.java:1089) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1892) 
	 android.os.Handler.handleCallback(Handler.java:971) 
	 android.os.Handler.dispatchMessage(Handler.java:107) 
	 android.os.Looper.loopOnce(Looper.java:206) 
	 android.os.Looper.loop(Looper.java:296) 
	 android.app.ActivityThread.main(ActivityThread.java:9170) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1018) 
Caused by:	java.io.FileNotFoundException: Corrupt XML binary file
	 android.content.res.AssetManager.nativeOpenXmlAsset(Native Method) 
	 android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:1264) 
	 android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1614) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2738) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2711) 
	 android.content.res.Resources.getXml(Resources.java:1517) 
	 a.a.f0(SourceFile:59) 
	 B3.a.i(SourceFile:631) 
	 s7.o.n(SourceFile:717) 
	 a6.b.c(SourceFile:261) 
	 s7.o.t(SourceFile:1339) 
	 E6.l.e(SourceFile:255) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 A6.i.e(SourceFile:198) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 F6.d.g(SourceFile:442) 
	 e0.a.g(SourceFile:52) 
	 O.U.g(SourceFile:170) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.R1.a(SourceFile:113) 
	 T.S0.b(SourceFile:56) 
	 T.G0.g(SourceFile:214) 
	 e0.a.g(SourceFile:52) 
	 T.U0.g(SourceFile:258) 
	 e0.a.g(SourceFile:52) 
	 T.A0.a(SourceFile:52) 
	 A6.z.g(SourceFile:1206) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.p0.a(SourceFile:395) 
	 A6.X.g(SourceFile:1216) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.T.a(SourceFile:627) 
	 J0.x1.g(SourceFile:250) 
	 e0.a.g(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.x1.g(SourceFile:213) 
	 e0.a.g(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.q.p(SourceFile:203) 
	 W.u.k(SourceFile:32) 
	 W.u0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.u.l(SourceFile:9) 
	 W.u.c(SourceFile:3) 
	 B.j0.b(SourceFile:529) 
	 J0.w.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.y1.c(SourceFile:10) 
	 J0.y1.m(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 B.j0.b(SourceFile:498) 
	 J0.w.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:21785) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3678) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3685) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3947) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3225) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11121) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1938) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1946) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1226) 
	 android.view.Choreographer.doFrame(Choreographer.java:1089) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1892) 
	 android.os.Handler.handleCallback(Handler.java:971) 
	 android.os.Handler.dispatchMessage(Handler.java:107) 
	 android.os.Looper.loopOnce(Looper.java:206) 
	 android.os.Looper.loop(Looper.java:296) 
	 android.app.ActivityThread.main(ActivityThread.java:9170) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1018) 

### RiMusic version

0.6.47

### Android version

Android 13

**Comment by Marcelo1565** [comment]
Same error

**Comment by aneesh1122** [comment]
1) maybe uninstalling and then reinstalling the app will solve the problem

2) Change the favourite button to 'Essential' and check if the error is gone

**Comment by Marcelo1565** [comment]
I tested it here and it didn't work. It happened in the new version.

**Comment by aneesh1122** [comment]
> I tested it here and it didn't work. It happened in the new version.

Are you sure you've changed the favorite button to essential?

**Comment by Marcelo1565** [comment]
Yes, all of my config is on essential

**Comment by aneesh1122** [comment]
> Yes, all of my config is on essential

Another guy had the same error and it is solved by changing the favorite button to essential.

![Screenshot_2024-08-10-10-50-31-915_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/69510366-313a-4e9c-b049-2f0365012cb1)

btw I'm talking about this button.

If you've selected 'essential' there and it's still crashing then post the crash log

**Comment by Marcelo1565** [comment]
I reinstalled the app again and when I tried to reproduce the same bug with the favorite button, the bug wasn't appearing, so I think it's fixed for me at least. Thank you for your help. And sorry for the incovenience...

**Comment by Marcelo1565** [comment]
Hey, I was doing my reconfig, when I change the background color config and it crashed. It looks like this bug is a error between the favorite button and the background color.

**Comment by aneesh1122** [comment]
> Hey, I was doing my reconfig, when I change the background color config and it crashed. It looks like this bug is a error between the favorite button and the background color.

If you use "Blurred song cover" + any favorites button except essential it will crash the app.

**Comment by aneesh1122** [comment]
Please download and try custom version, send feedback please.

https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Marcelo1565** [comment]
Working greatly, no error with the two options, thank you!

**Comment by fast4x** [comment]
Nice thanks
