### ISSUE TITLE
Consistent sliders

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#3191]
### Description

The new update introduced a new slider for the minimum silence length and I think it looks really good. The app would look a little more consistent if that were used throughout the ui and the player screen.

### Suggested Solution

Change the sliders on the player screen to look more consistent and modern.

Here's the slider for the minimum silence length 
![Screenshot_20240810-084158](https://github.com/user-attachments/assets/37fa95bd-8f2a-49b0-be4a-1a4523914658)

The player sliders could look like this, it looks so much cleaner and better.
![Untitled6_20240810084652](https://github.com/user-attachments/assets/b818abeb-cc65-4d74-ab4c-1eb82988d22f)

### Additional Context

Here's a comparison
![Untitled6_20240810084658](https://github.com/user-attachments/assets/663de378-a49c-4688-83a3-364c14d4031b)

**Comment by fast4x** [comment]
Ok nice idea

**Comment by fast4x** [comment]
Implemented, available from version 0.6.48
