### ISSUE TITLE
Can't change the like button 

### ISSUE THREAD

**Issue by Andre3557** [fast4x/RiMusic#3192]
### Steps to reproduce the bug

Go to the appearance section, look for the appearance section of the like button, then select another style and when you change it, open the player 

### Expected behavior

The appearance of the like button should change to the selection 

### Actual behavior

When you change the appearance of the button and open the player, the application closes and the music stops playing. 

### RiMusic version

O.6.47

### Android version

Android 14

**Comment by aneesh1122** [comment]
Change the favourite button to 'Essential' and check if the error is gone

**Comment by aneesh1122** [comment]
Please download and try custom version, send feedback please.

https://github.com/fast4x/RiMusic/tree/master/customVersion
