### ISSUE TITLE
Songs missing in new update 

### ISSUE THREAD

**Issue by Squad8991** [fast4x/RiMusic#3193]
### Steps to reproduce the bug

Go to any playlist 

### Expected behavior

All the songs should be available 

### Actual behavior

Some songs are missing,refer the numbers from screenshot

### Screenshots/Screen recordings

![IMG_20240810_074823](https://github.com/user-attachments/assets/23aebe2c-26c7-40a6-855c-cfc9893055d2)

### RiMusic version

0.6.47

### Android version

Android 11

**Comment by fast4x** [comment]
Ok soon I'll create a custom version that you can try

**Comment by SunsetSamu** [comment]
I have the same issue, my playlists turned from 300 songs to 100 😭

**Comment by fast4x** [comment]
Please download and try custom version, send feedback please.
 
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by KOLIWAN** [comment]
I had the same issue, also player crashed when I tried to play any song. Custom version solved both issues 🤔

**Comment by MyszeqPL** [comment]
I had this issue, the Custom version did fix it, thanks!

**Comment by cMattw** [comment]
> Please download and try custom version, send feedback please.
>  
> https://github.com/fast4x/RiMusic/tree/master/customVersion

wow that was fast
