### ISSUE TITLE
Error de reproducción 

### ISSUE THREAD

**Issue by Badapesil** [fast4x/RiMusic#3195]
### Steps to reproduce the bug

inicias la aplicación con normalidad, en el momento de reproducir una canción, aparece que no se encuentra algún "formato de audio compatible"

### Expected behavior

al reproducir una canción recomendada o que haya Sido una búsqueda, se debe reproducir con normalidad 

### Actual behavior

Aparece la leyenda "no se pudo encontrar un formato de audio compatible", el cual no desaparece no cerrada la aplicación, hay que forzar la detención desde ajustes 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/99376292-203f-43a9-bc38-7ce1812198c8

### RiMusic version

0.6.47

### Android version

Android 11

**Comment by fast4x** [comment]
This isn't a bug, it mean that isn't available audio version but only video version of song.

**Comment by Badapesil** [comment]
el problema, es que hay canciones en las que esto no aparece, luego, quiero
poner la misma canción y en ocasiones si aparece, siendo con las mismas
canción

**Comment by fast4x** [comment]
It not depend by RiMusic
