### ISSUE TITLE
i get an error i can play anysong any more

### ISSUE THREAD

**Issue by Godfrey3402** [fast4x/RiMusic#3197]
### Steps to reproduce the bug

just when i search anysong i cant download even i cant lesten to the song i keep getting error

### Expected behavior

the app should play the song

### Actual behavior

not playing the songs

### Screenshots/Screen recordings

![Screenshot_20240810-064828](https://github.com/user-attachments/assets/801ba8fe-c592-4ea8-97de-008ce07b404b)

### RiMusic version

0.6.47

### Android version

Android 14

**Comment by fast4x** [comment]
Try new custom version

**Comment by fast4x** [comment]
This isn't a bug, it mean that isn't available audio version but only video version of song.
