### ISSUE TITLE
Strange look on Nokia 6.1

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#32]
### Steps to reproduce the bug

1. Install apk on Nokia 6.1.
2. Play song.
3. Buttons and progress bar are not visible.

### Expected behavior

The same look as for example on Android 13 or an incompatibility warning.

### Actual behavior

Strange look on Nokia 6.1 (Android 10).

### Screenshots/Screen recordings

<img width="250" src="https://github.com/fast4x/RiMusic/assets/38765251/88feb4c6-a793-4a3b-b83d-a6151b566472">
<img width="250" src="https://github.com/fast4x/RiMusic/assets/38765251/730d1d78-1169-4557-978c-9c4ee44042c7">
<img width="250" src="https://github.com/fast4x/RiMusic/assets/38765251/a0a60a32-d27e-4a79-a6d7-64e4e16788a8">
<img width="250" src="https://github.com/fast4x/RiMusic/assets/38765251/220294d6-e1f4-49c2-9a82-35eecb684696">
<img width="250" src="https://github.com/fast4x/RiMusic/assets/38765251/9736af80-f13f-4a3a-b206-cf42a8c097df">
<img width="250" src="https://github.com/fast4x/RiMusic/assets/38765251/b4247f4c-c0cd-405f-a8ff-030d6e28dd8e">

</div>

### RiMusic version

0.6.5

### Android version

Android 10

### Additional information

It's OK on Samsung A53 (Android 13).

**Comment by fast4x** [comment]
This bug Is caused by thumbnail size on the player. From version 0.6.6 just set Thunbnail size = Small (or Medium if supported) on settings Player Page.
