### ISSUE TITLE
Minhas músicas 

### ISSUE THREAD

**Issue by Phr01** [fast4x/RiMusic#3200]
### Steps to reproduce the bug

Vá em " playlists " e entre qualquer playlist 

### Expected behavior

A minha playlist principal tem 203 músicas, mas só está aparecendo 37 músicas

### Actual behavior

.

### Screenshots/Screen recordings

![Screenshot_20240810_092641](https://github.com/user-attachments/assets/c4156382-9916-48ca-a15f-d49584d58a00)
![Screenshot_20240810_092635](https://github.com/user-attachments/assets/39dc5043-ddeb-48f6-bcbd-e7376b853f31)

### RiMusic version

0.6.47

### Android version

Android 14

### Additional information

Só aconteceu isso depois da atualização mais recente

**Comment by Willy2222** [comment]
Exactly, I have playlists created by me with many musical themes and when I enter to play, only very few songs are displayed.

**Comment by aneesh1122** [comment]
Download the latest version

**Comment by Phr01** [comment]
Mas é exatamente a versão mais recente que está com esse problema

**Comment by Willy2222** [comment]
Solucionado, genial, gracias y los admiro..

**Comment by Phr01** [comment]
Obrigado
