### ISSUE TITLE
Unexpected Song plays after click on Song.

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#3203]
### Steps to reproduce the bug

1. Set sorting to date played descending
2. Play not the first song for some time, song list reorders
3. Play some other song (in the affected area)

### Expected behavior

The selected song plays.

### Actual behavior

A different song plays.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/3219d2f9-f6af-440c-9ba9-53787423f469

### RiMusic version

0.6.47.1 customVersion 2

### Android version

14

**Comment by aneesh1122** [comment]
Restart the app

**Comment by twistios** [comment]
Does not help.

**Comment by twistios** [comment]
https://github.com/user-attachments/assets/5a7061be-3145-4347-8a5a-f28fa05e014a

**Comment by fast4x** [comment]
Check if in notification area, shuffle mode is enabled

**Comment by twistios** [comment]
It is like this.

![Screenshot_20240810_233232](https://github.com/user-attachments/assets/fd76a059-aa97-44ad-9a53-c76a2b3d5a6e)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.48

**Comment by fast4x** [comment]
Download new custom version 
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by twistios** [comment]
Currently it does not happen, but also it seems that the reordering of the list does not happen when playing a song, so the move does not happen such that the issue can not be tested currently.
