### ISSUE TITLE
Playback

### ISSUE THREAD

**Issue by anonymous2420** [fast4x/RiMusic#3204]
### Steps to reproduce the bug

Keep listening for two songs 

### Expected behavior

The queue should continue to play the songs

### Actual behavior

After playing two songs continuously, queue is again starting from the song ,which I have already listened before the two songs

### RiMusic version

Latest

### Android version

Android 14

**Comment by ImpenetrableNoble** [comment]
@fast4x Hi Fast, 

I have been having this playback issue as well apparently whenever I relaunch onto other apps like Google docs for example, suddenly your Rimusic app stops playing from the media output. This has been happening to me twice.

**Comment by fast4x** [comment]
Check if you have loop enabled

**Comment by ara2404** [comment]
If loop is enabled,either one song should be played repeatedly or songs queue should start from beginning.. but I have been facing this issue in the middle of queue... After listening two songs .... Again the song which is before that already played songs has been started playing...!

**Comment by fast4x** [comment]
Ok I'll check it

**Comment by ara2404** [comment]
> @fast4x Hi Fast,
> 
> I have been having this playback issue as well apparently whenever I relaunch onto other apps like Google docs for example, suddenly your Rimusic app stops playing from the media output. This has been happening to me twice.

Yes that's true as well

**Comment by aneesh1122** [comment]
@fast4x This problem happens only with modern player. I tried to see what was causing this problem but I couldn't find anything.

**Comment by fast4x** [comment]
Ok I'll look into

**Comment by fast4x** [comment]
Try new custom version

**Comment by anonymous2420** [comment]
> Ok I'll check it

The bug still exists...for every two songs in the queue...the songs before that...starts playing again...this has been repeating for every two songs in modern player(I have been using modern player type bcz of radio extension of queue ends)...pls fix this bug ASAP in modern player....!

**Comment by fast4x** [comment]
I can't reproduce this bug

**Comment by aneesh1122** [comment]
> I can't reproduce this bug

Use modern player. Put the app in the background and change the song using the next button in the notification bar. Songs are repeating after the 3rd song.

**Comment by fast4x** [comment]
I understand, but i don't have this bug...

**Comment by aneesh1122** [comment]
> I understand, but i don't have this bug...

This bug is only with modern player. I've posted the video above. You'll get the bug if you do exactly that.

Make sure that you are putting the app in the background and changing the song using the notification bar.

By background I mean that you have to minimize the app and then change the song from the notification bar.

**Comment by fast4x** [comment]
oooooooookkkkkkkk i try again...

**Comment by anonymous2420** [comment]
> oooooooookkkkkkkk i try again...

Tnx in advance,I am waiting ❤️

**Comment by aneesh1122** [comment]
> oooooooookkkkkkkk i try again...

Do exactly this

https://github.com/user-attachments/assets/216d5755-c52e-49b5-9996-202bd2488048

**Comment by anonymous2420** [comment]
> > oooooooookkkkkkkk i try again...
> 
> Do exactly this
> 
>  VID_20240818_180245.mp4 
> After 'is it love' if you press next it is playing 'one in a million' again

That's need to be fixed?

**Comment by aneesh1122** [comment]
> > > oooooooookkkkkkkk i try again...
> > 
> > Do exactly this
> > 
> >  VID_20240818_180245.mp4 
> > After 'is it love' if you press next it is playing 'one in a million' again
> 
> That's need to be fixed?

This is not the fix.

I'm telling him how to get the bug because he is not able to reproduce the bug from his side.

I'm requesting him to fix this bug like you.

I tried to fix this bug myself but I couldn't fix it. Me and @fast4x fixed all the bugs with modern player and I believe this is the only thing left to be fixed.

**Comment by anonymous2420** [comment]
> > > > oooooooookkkkkkkk i try again...
> > > 
> > > 
> > > Do exactly this
> > > VID_20240818_180245.mp4
> > > After 'is it love' if you press next it is playing 'one in a million' again
> > 
> > 
> > That's need to be fixed?
> 
> This is not the fix.
> 
> I'm telling him how to get the bug because he is not able to reproduce the bug from his side.
> 
> I'm requesting him to fix this bug like you.
> 
> I tried to fix this bug myself but I couldn't fix it. Me and @fast4x fixed all the bugs with modern player and I believe this is the only thing left to be fixed.

Yes,I have also not found any other bugs with modern player other than this,please try to fix this one final bug related to modern player..😄🥲

**Comment by fast4x** [comment]
I think it's fixed, i've improved any actions, soon available custom version

**Comment by fast4x** [comment]
Try custom please

**Comment by aneesh1122** [comment]
> Try custom please

Nothing seems to be changed in the custom version 😅

The same problem is still there.

Are you able to reproduce the bug from your end?

**Comment by fast4x** [comment]
I have done all possible, soon I'll make a video...

**Comment by aneesh1122** [comment]
> I have done all possible, soon I'll make a video...

Okay

**Comment by aneesh1122** [comment]
> > > > > oooooooookkkkkkkk i try again...
> > > > 
> > > > 
> > > > Do exactly this
> > > > VID_20240818_180245.mp4
> > > > After 'is it love' if you press next it is playing 'one in a million' again
> > > 
> > > 
> > > That's need to be fixed?
> > 
> > This is not the fix.
> > 
> > I'm telling him how to get the bug because he is not able to reproduce the bug from his side.
> > 
> > I'm requesting him to fix this bug like you.
> > 
> > I tried to fix this bug myself but I couldn't fix it. Me and @fast4x fixed all the bugs with modern player and I believe this is the only thing left to be fixed.
> 
> Yes,I have also not found any other bugs with modern player other than this,please try to fix this one final bug related to modern player..😄🥲

Custom ready to download
https://github.com/fast4x/RiMusic/tree/master/customVersion

Try this.

**Comment by fast4x** [comment]
Fixed available from version 0.6.49

**Comment by anonymous2420** [comment]
> Fixed available from version 0.6.49

Thankyou... Waiting for the release 😎❤️

**Comment by aneesh1122** [comment]
> > Fixed available from version 0.6.49
> 
> Thankyou... Waiting for the release 😎❤️

Try the new custom version and check if it's fixed. You don't have to wait for the release.

**Comment by anonymous2420** [comment]
> > > Fixed available from version 0.6.49
> > 
> > 
> > Thankyou... Waiting for the release 😎❤️
> 
> Try the new custom version and check if it's fixed. You don't have to wait for the release.

Ok...! Tnq
