### ISSUE TITLE
Number of songs too high

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#3205]
### Steps to reproduce the bug

I don't know the conditions for this big to happen.

### Expected behavior

Number of songs correct.

### Actual behavior

The number of songs is way higher than expected.

### Screenshots/Screen recordings

<details><summary>Details</summary>
<p>

![Screenshot_20240810_174450](https://github.com/user-attachments/assets/269f29b1-3cdb-4f78-a2f5-541f69d1b260)
![Screenshot_20240810_174445](https://github.com/user-attachments/assets/6d0c4efa-66d1-4b29-b8a1-8bb0fe5185b3)

</p>
</details> 

### RiMusic version

0.6.47.1 customVersion 2

### Android version

14

### Additional information

The screenshot shows that the hidden song only counts as 1 song while the two songs count as 10.

**Comment by twistios** [comment]
I got some new info: the issue seems to be related with sorting by date played.

**Comment by fast4x** [comment]
Not reproduced
https://github.com/user-attachments/assets/1ce99426-ddf5-410c-83af-832f006fdeb9

**Comment by twistios** [comment]
This is what happens if I tab a song (shuffle not activated with date played sorting). As one can see there are some songs multiple times but in list they are only once.
![Screenshot_20240810_233554](https://github.com/user-attachments/assets/da235a42-96d4-41d9-b51e-8f400ae5fe86)

**Comment by twistios** [comment]
It does not seem to happen if the sorting is different, at least it did not happen with it.

**Comment by fast4x** [comment]
I tried and haven't reproduced this bug...

**Comment by twistios** [comment]
Maybe this is related to #3203.

**Comment by twistios** [comment]
https://github.com/user-attachments/assets/ca797151-266b-4355-a091-22d698ed6f77

**Comment by fast4x** [comment]
Ok reproduced... I'll fix it thanks for details

**Comment by fast4x** [comment]
Fixed, available from version 0.6.48

**Comment by fast4x** [comment]
Download new custom version 
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by twistios** [comment]
This issue I'd fixed with the newest customVersion.
