### ISSUE TITLE
Still "Couldn't find a playable audio format" for some tracks

### ISSUE THREAD

**Issue by testandreport** [fast4x/RiMusic#3206]
### Steps to reproduce the bug

Examples:
https://music.youtube.com/watch?v=daI0CFZa9Ww
https://music.youtube.com/watch?v=Q6CuFkhNijc
https://music.youtube.com/watch?v=UtoVx8KYdUU

Played well some time ago (don't remember which version). Now only silence and error popup

### Expected behavior

The track should play like in YT Music.

### Actual behavior

The counter stays at 0.00 and an error pops up. 

### RiMusic version

0.6.47.1

### Android version

Android 14

### Additional information

Thank you for your continuous great work / support.

**Comment by ara2404** [comment]
Yes I have been facing same issue

**Comment by faustaahmad** [comment]
Try playing it again or restart the app
Sometimes it does work
Tried using favorite to add the song to the favorite list
Then replay bunch of times till it works

**Comment by fast4x** [comment]
Try new custom version

**Comment by fast4x** [comment]
This means that there are no audio files available but only video. RiMusic currently does not support videos.

**Comment by Godfrey3402** [comment]
> This means that there are no audio files available but only video. RiMusic currently does not support videos.
> 

Please add video feature 😭😭😭😭😭
