### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by PabloMan47** [fast4x/RiMusic#3207]
### Steps to reproduce the bug

In the album page, I have a little problem.
The album shows the year of realise twice
![Screenshot_20240810-130224](https://github.com/user-attachments/assets/ba3153c0-150e-4b58-8188-38ccfb6ce6a5)

### Expected behavior

it must show the name of the artist and year, like this one
![IMG-20240810-WA0103](https://github.com/user-attachments/assets/c8781f93-9031-4a0f-8563-df482ceccd67)

### Actual behavior

well that's it

### RiMusic version

0.6.47.1

### Android version

Android 12

**Comment by fast4x** [comment]
Yes it's an old bug in api that is just fixed. You must enter in album, should be fix by self
