### ISSUE TITLE
Lost Option 

### ISSUE THREAD

**Issue by Wonky-png** [fast4x/RiMusic#3209]
### Steps to reproduce the bug

I don't know how to reproduce this bug exactly but it seems to happen by switching between the RiMusic interface and the Vimusic interface 

### Expected behavior

The disappeared option is "MaintainKeep the player minimized"  Which, when deactivated, prevents it from starting down when you change a song

### Actual behavior

The option disappears in the Vimusic interface and it is activated automatically and if you return to the RiMusic interface this option does not appear again being uncomfortable sometimes and you need to reinstall the app

### Screenshots/Screen recordings

I really like the app, I attach two caps, one on my primary device and one on the secondary 
![Screenshot_20240810_151906_edit_514051631628254](https://github.com/user-attachments/assets/d02537f2-6c96-495a-859d-69ab556c15ea)
![Screenshot_20240810-151012](https://github.com/user-attachments/assets/bb486152-9989-4384-b0d3-46cc145325b4)

### RiMusic version

0.6.47.1

### Android version

Android 13

### Additional information

This error is not that annoying but if I could know why it happens it would be great thanks

**Comment by aneesh1122** [comment]
are you using 'modern' player?

**Comment by Wonky-png** [comment]
> ¿Estás usando un reproductor "moderno"?
Yes, since I first set up the app

**Comment by aneesh1122** [comment]
> > ¿Estás usando un reproductor "moderno"?
> Yes, since I first set up the app

When you switch to the 'modern' player, the app will automatically disable minimizing the player and hide the option.

**Comment by aneesh1122** [comment]
https://github.com/user-attachments/assets/0dc4e0d9-e65e-4e37-a4fe-6b4999ea83bc

**Comment by Wonky-png** [comment]
> Grabador de pantalla-2024-08-11-03-13-12-38.mp4

Hey, thank you I thought it was a bug it saddens me a little to know that I will no longer be able to change the music for gestures but thank you it was somewhat awkward that it closes :)

**Comment by aneesh1122** [comment]
> change the music for gestures

What do you mean that you can't change the music using gestures?

**Comment by Wonky-png** [comment]
> > change the music for gestures
> 
> What do you mean that you can't change the music using gestures?

I just didn't know how to refer to that but it's changing music by sliding your finger Between one song and another.

**Comment by aneesh1122** [comment]
> > > change the music for gestures
> > 
> > What do you mean that you can't change the music using gestures?
> 
> I just didn't know how to refer to that but it's changing music by sliding your finger Between one song and another. 

In modern player you can swipe vertically to change songs

**Comment by Wonky-png** [comment]
> > > > change the music for gestures
> > > 
> > > 
> > > What do you mean that you can't change the music using gestures?
> > 
> > 
> > I just didn't know how to refer to that but it's changing music by sliding your finger Between one song and another.
> 
> In modern player you can slide vertically to change songs

Yes, I love that feature it tastes a little bitter to me not being able to have it without minimizing the player 🫠

Uploading SVID_20240810_224526_1.mp4…

**Comment by aneesh1122** [comment]
>  
> 
> > > > > change the music for gestures
> > > > 
> > > > 
> > > > What do you mean that you can't change the music using gestures?
> > > 
> > > 
> > > I just didn't know how to refer to that but it's changing music by sliding your finger Between one song and another.
> > 
> > In modern player you can slide vertically to change songs
> 
> Yes, I love that feature it tastes a little bitter to me not being able to have it without minimizing the player 🫠
> 
> Uploading SVID_20240810_224526_1.mp4…
> 
> 

Video is not properly uploaded

**Comment by Wonky-png** [comment]
> > > > > > change the music for gestures
> > > > > 
> > > > > 
> > > > > What do you mean that you can't change the music using gestures?
> > > > 
> > > > 
> > > > I just didn't know how to refer to that but it's changing music by sliding your finger Between one song and another.
> > > 
> > > 
> > > In modern player you can slide vertically to change songs
> > 
> > 
> > Yes, I love that feature it tastes a little bitter to me not being able to have it without minimizing the player 🫠
> > Uploading SVID_20240810_224526_1.mp4…
> 
> Video is not properly uploaded


https://github.com/user-attachments/assets/ec0dbe01-cef3-4f2a-8eb4-b19e9e3f0b93

**Comment by aneesh1122** [comment]
> > > > > > > change the music for gestures
> > > > > > 
> > > > > > 
> > > > > > What do you mean that you can't change the music using gestures?
> > > > > 
> > > > > 
> > > > > I just didn't know how to refer to that but it's changing music by sliding your finger Between one song and another.
> > > > 
> > > > 
> > > > In modern player you can slide vertically to change songs
> > > 
> > > 
> > > Yes, I love that feature it tastes a little bitter to me not being able to have it without minimizing the player 🫠
> > > Uploading SVID_20240810_224526_1.mp4…
> > 
> > Video is not properly uploaded
> 
> 
> https://github.com/user-attachments/assets/ec0dbe01-cef3-4f2a-8eb4-b19e9e3f0b93
> 
> 

Uninstall and then reinstall the app. Maybe that will fix the problem. Make a backup before doing that.

**Comment by Wonky-png** [comment]
> If that doesn't solve the problem then uninstall and then reinstall the app. Maybe that will fix the problem. Make a backup before doing that.

Yep, I did that at first but when I updated it happened again

**Comment by aneesh1122** [comment]
> > If that doesn't solve the problem then uninstall and then reinstall the app. Maybe that will fix the problem. Make a backup before doing that.
> 
> Yep, I did that at first but when I updated it happened again 
> 

See, I'm clearing the data and changed player to modern. I did nothing else and the player is not getting minimized.

I don't know what's wrong with your device.

https://github.com/user-attachments/assets/78ff3449-26d8-450b-92f8-588acae7012a

**Comment by Wonky-png** [comment]
> > > Si eso no resuelve el problema, desinstala y vuelve a instalar la aplicación. Tal vez eso solucione el problema. Haz una copia de seguridad antes de hacerlo.
> > 
> > 
> > Sí, lo hice al principio, pero cuando actualicé, volvió a suceder.
> 
> Mira, estoy borrando los datos y cambié el reproductor a moderno. No hice nada más y el reproductor no se minimiza.
> 
> No sé qué le pasa a tu dispositivo.
> 
>  Vídeo_20240811_112859.mp4

You came to the same conclusion as me... I don't know :) but to give you a little more context I'm using an honor 90 lite with the magicOS 7.2 customization layer based on Android 13 (Thank you very much for the help, I'm giving the essential player a chance and it's a matter of getting used to it)

**Comment by aneesh1122** [comment]
#3215 this guy's problem got solved by doing what I asked you to do.

Are you sure you're doing everything right? Just clear all the data and choose the modern player without changing anything else.

**Comment by Wonky-png** [comment]
> #3215 El problema de este chico se solucionó haciendo lo que le pedí que hiciera.
> 
> ¿Estás seguro de que lo estás haciendo todo bien? Borra todos los datos y elige el reproductor moderno sin cambiar nada más.

Yes I did but works temporarily so I opted to reinstall the app instead of updating on it and no problem yetYes I did but works temporarily so I opted to reinstall the app instead of updating on it and no problem yet 🙂‍↕️

**Comment by aneesh1122** [comment]
> > #3215 El problema de este chico se solucionó haciendo lo que le pedí que hiciera.
> > 
> > ¿Estás seguro de que lo estás haciendo todo bien? Borra todos los datos y elige el reproductor moderno sin cambiar nada más.
> 
> Yes I did but works temporarily so I opted to reinstall the app instead of updating on it and no problem yet 🙂‍↕️

That's great. If you get this problem again tell me what you changed so that I can look into it.

**Comment by Its-Tony** [comment]
Same problem with me if I change songs using vertically scrolling song cover, player got minimized suddenly. Clear data fix it temporarily. Mostly happens(or start happening) when we slide song cover from above to bottom(previous song.)

**Comment by kapitan-Prodigy** [comment]
Same, cleared data and fixed it only temporarily.

**Comment by aneesh1122** [comment]
Does it start getting minimized automatically after sometime without changing anything in the settings?

**Comment by Its-Tony** [comment]
I don't know how but now it is working fine it occurs occasionally.

**Comment by Its-Tony** [comment]
What is the use of these slider, I can't see any change by sliding these sliders 
![Uploading Screenshot_2024-08-12-09-31-32-549_it.fast4x.rimusic.jpg…]()
@aneesh1122

**Comment by aneesh1122** [comment]
> What is the use of these slider, I can't see any change by sliding these sliders
> ![Screenshot_2024-08-12-09-31-32-549_it fast4x rimusic](https://github.com/user-attachments/assets/da359f48-f691-4b3c-ba63-705d2339fbb6)
> 
> @aneesh1122 

https://github.com/user-attachments/assets/2a7b6ff1-99f3-46e5-801c-13da21279569

1st slider = distance of playing album cover from top

2nd slider = distance between pages

**Comment by SergyManuto** [comment]
> > @aneesh1122
> 
>  VID_20240812_094030.mp4 
> 1st slider = distance of playing album cover from top
> 
> 2nd slider = distance between album covers

how to see the playback by album, I only see the playback by song and it does not allow to modify the distance.

**Comment by aneesh1122** [comment]
> how to see the playback by album, I only see the playback by song

....what?



> it does not allow to modify the distance

It does. do exactly what I'm doing in the video
