### ISSUE TITLE
Android Auto - Voice commands

### ISSUE THREAD

**Issue by LEOSCHUMY** [fast4x/RiMusic#321]
### Steps to reproduce the bug

In auto try "Hey Google, play (Song) on Rimusic"

### Expected behavior

Play _Song_

### Actual behavior

At the begin It seems working, assistant responds: "Ok, asking RiMusic to play _song_."

Then the assistant alerts with
"Sorry, something went wrong. Try opening the app to continue

### RiMusic version

0.6.15.1

### Android version

Android 14

### Additional information

Android Auto: 10.9.634644-release

Smartphone: Xiaomi Poco X3 Pro

**Comment by fast4x** [comment]
Hi, thanks for feedback. I'll check it

**Comment by LEOSCHUMY** [comment]
Just for clarification, unlike #322 , this issue also happens with vimusic app (I will try to catch the logs as soon as possible)

**Comment by sayyid5416** [comment]
@fast4x Why was this issue closed? Is there any specific reason?

**Comment by OrangeZXZ** [comment]
> @fast4x Why was this issue closed? Is there any specific reason?

I think he looked for a solution and it needs too mutch développement

**Comment by fast4x** [comment]
Voice command require Google platform proprietary service. Can't add to RiMusic, of you have other news explain me. I'm sorry.

**Comment by sayyid5416** [comment]
> Voice command require Google platform proprietary service. Can't add to RiMusic, of you have other news explain me. I'm sorry.

I have an idea, but it may involve a lot of development work. You could add an 'extensions' function where users can download extensions and enable specific features. This would also solve the issue with YouTube login.

**Comment by fast4x** [comment]
I’ll run some tests to see if there’s a chance.

**Comment by sayyid5416** [comment]
> I’ll run some tests to see if there’s a chance.

Thank you. I really appreciate that you are willing to try.

**Comment by sayyid5416** [comment]
@fast4x Since you are willing to try this out, can you reopen this issue?

**Comment by fast4x** [comment]
Sure

**Comment by sayyid5416** [comment]
> Sure, but not like a bug it's a new feature.

It's still closed!

**Comment by kot7k** [comment]
Hi, just discovered this app thank you for this. For me this is also a must, i wanted this app for being able to select the song my daugther asks me to play while driving. As it is now, i can't do it unless my wife is also in the car and select it manually ^^U. It would be much apreciated.

**Comment by fast4x** [comment]
I will try

**Comment by havfu** [comment]
I hope it will be 'add to list' when i said'i liked this song',but google assisant response'Sorry, something went wrong. ....'

**Comment by sayyid5416** [comment]
Since YT Login was added earlier, I'm positive that now this function could also be added.
