### ISSUE TITLE
An "unsupported audio" error is displayed.

### ISSUE THREAD

**Issue by LocoKevin** [fast4x/RiMusic#3210]
### Steps to reproduce the bug

Play the song, wait for it to play and wait for the error to appear.
![Screenshot_20240810_160103](https://github.com/user-attachments/assets/a2b43e0c-5ebc-4930-b5b4-db8ce6c978f9)
![Screenshot_20240810_160043](https://github.com/user-attachments/assets/e6ec5b11-ad90-424e-9b55-0466f641ef10)

### Expected behavior

That the music plays without this error appearing.

### Actual behavior

Out of the blue the error occurred, previously it was perfectly audible. 

### RiMusic version

0.6.47.1

### Android version

Android 14

**Comment by fast4x** [comment]
Add link to the songs

**Comment by LocoKevin** [comment]
> Añadir enlace a las canciones

How do I do it?

**Comment by EliasNavaXD** [comment]
The same thing happens to me too!

**Comment by EliasNavaXD** [comment]
How can you solve the problem it is somewhat annoying that you cannot 😥

**Comment by fast4x** [comment]
> How can you solve the problem it is somewhat annoying that you cannot 😥

It can be solved with patience
