### ISSUE TITLE
Crash issues

### ISSUE THREAD

**Issue by SharkyBeAre** [fast4x/RiMusic#3211]
### Steps to reproduce the bug

I know that when I activate the letters this error occurs and when I exit the app, or even being inside the app, it crashes.

### Expected behavior

It's happened to me since the last updates 

### Actual behavior

That's all

### Screenshots/Screen recordings

https://youtu.be/EWQ2HuK0sVc

### Logs

[Log_2024-08-10_18-57-30.txt](https://github.com/user-attachments/files/16571170/Log_2024-08-10_18-57-30.txt)

https://paste.evolution-x.org/lVEvBw

### RiMusic version

0.6.47.1

### Android version

Android 14

**Comment by SharkyBeAre** [comment]
https://paste.evolution-x.org/6XtZkT

**Comment by fast4x** [comment]
Try with another song
