### ISSUE TITLE
Opção de adicionar na playlist

### ISSUE THREAD

**Issue by Ewertonjp90** [fast4x/RiMusic#3213]
### Description

Seria muito interessante se fosse possível realizar o comando de adicionar uma música em playlist na tela de reprodução de bloqueio, assim como é possível favoritar e fazer download.

### Suggested Solution

Um botão de inserir na playlist com as opções de escolha de qual inserir.

**Comment by fast4x** [comment]
You say
Um botão de inserir na playlist com as opções de escolha de qual inserir.

It's just possible add songs in playlists... by select and add
