### ISSUE TITLE
Music player collapsing

### ISSUE THREAD

**Issue by kapitan-Prodigy** [fast4x/RiMusic#3215]
### Steps to reproduce the bug

1. Have "player type" set as "modern"
2. Have the player open
3. Swipe up or down to change song

### Expected behavior

3. Swipe up or down to change song
4. Player stays on screen

### Actual behavior

When swiping up or down to change song, the player collapses forcing you to press on mini player each time to access player. 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/3a000756-0af8-4812-a57d-b4f1f373196c

### RiMusic version

0.6.47.1

### Android version

Android 14

**Comment by fast4x** [comment]
Up and down is used to swipe player and other  sections.

**Comment by aneesh1122** [comment]
Do exactly this and tell me if it's solved

https://github.com/user-attachments/assets/c654f60b-147a-4479-93ca-015ac02f6173

Do a backup before clearing data

**Comment by kapitan-Prodigy** [comment]
@aneesh1122 it solved the problem, thank you.

**Comment by SergyManuto** [comment]
The problem is the option "Persistent queue" in "UI" menu when is enable, maybe u can fix it
