### ISSUE TITLE
Minor Issues with Charts UI

### ISSUE THREAD

**Issue by coolswapnil** [fast4x/RiMusic#3216]
### Steps to reproduce the bug

1. Enable Charts feature from Settings -- Quick Picks.
2. Go to Player -- Quick Picks -- Scroll down -- Global Charts Can be seen.
3. Scroll down and open Tending Songs, Top Music List and Top Artist section one by one.

### Expected behavior

There are 3 issues i found in Charts
1. Open Trending song list, in album text it shows Trending 20 Songs Global/country.
2. Same thing can be seen with Top Music Videos, in album text it shows 100 songs.
6. Top Artist section shows 4 rows in which artists name is there

### Actual behavior

1. Trending songs list shows 16 songs only.
2. Top Music videos list shows around 70 songs only.
3. Only 2 rows can be seen with artist names.

### Screenshots/Screen recordings

![Screenshot_2024-08-11-16-21-02-802_it fast4x rimusic-edit](https://github.com/user-attachments/assets/42faf19a-2857-4d4e-92e3-525d70876fbe)
![Screenshot_2024-08-11-16-21-25-686_it fast4x rimusic-edit](https://github.com/user-attachments/assets/b360fdf1-0dcd-44ba-b1e9-6c60f9697209)
![Screenshot_2024-08-11-16-21-43-001_it fast4x rimusic-edit](https://github.com/user-attachments/assets/7f736959-79f1-4f16-9500-3abb60b83243)
![Screenshot_2024-08-11-16-29-57-241_com google android apps youtube music-edit](https://github.com/user-attachments/assets/a651d49c-ae49-43d0-b702-7c4b00e2a73f)

### RiMusic version

0.6.47.1

### Android version

Android 14

**Comment by faustaahmad** [comment]
There are issues with parsing audio format/quality in Youtube videos, so that's why it display less songs
See that playlist from share button

This issue wont happen if all the songs on those playlist/album came from youtube music

**Comment by coolswapnil** [comment]
Understood about Top music videos.
What about other 2 issues?

**Comment by fast4x** [comment]
I've checked it and there are 24 songs without id code valid, so RiMusic exclude it.
