### ISSUE TITLE
[Feature]: Add Lyric Romanization Feature

### ISSUE THREAD

**Issue by ghost** [fast4x/RiMusic#3217]
### Description

For listening foreign songs lyrics should be in Romanized letters instead of orignal song language.

### Suggested Solution

I have seen this repo which provide this feature
https://github.com/surfbryce/beautiful-lyrics 
Feature can be provided in translation section.

**Comment by faustaahmad** [comment]
Duplicate #385

**Comment by privacyfreak84** [comment]
It should be an option, not the default in my opinion

**Comment by fast4x** [comment]
Implemented, available from version 0.6.60
