### ISSUE TITLE
Android Auto - Stuck on select albums

### ISSUE THREAD

**Issue by LEOSCHUMY** [fast4x/RiMusic#322]
### Steps to reproduce the bug

Sometimes, using the App into Android Auto, it doesn't work.
On AA display, select one Album and press play

### Expected behavior

Play album (in Vimusic it works)

### Actual behavior

The app remains stuck in search.

### Logs

https://pastebin.com/4zFAkprj

### RiMusic version

0.6.15.1

### Android version

Android 14

### Additional information

Android Auto: 10.9.634644-release

Smartphone: Xiaomi Poco X3 Pro

**Comment by fast4x** [comment]
Thanks for log, I'll check it

**Comment by fast4x** [comment]
I think is fixed, available from version 0.6.26
