### ISSUE TITLE
[Feature]: what is the max of songs, albums you can add in your account

### ISSUE THREAD

**Issue by enomao44** [fast4x/RiMusic#3220]
### Description

what is max of albums you can add to your account, for example in deezer i had a max of 2000. and if you can specify max of songs in favs, max of songs in a playlist... Im not asked for any account login, i can have an account in computer and phone sync?

### Suggested Solution

info about

**Comment by twistios** [comment]
RiMusic itself seems to have no (own) limit. Probably there is some limit based on your RAM and memory because of the database.
I currently have >2k songs in total. I don't know if there are limits in piped.

**Comment by twistios** [comment]
*pretty sure there is somewhere some number based limit i.e. based on int or long size also.

**Comment by fast4x** [comment]
In theory YtM limit is 5000

**Comment by enomao44** [comment]
could be possible to get some more specific information? so is not really limit on rimusic but is limited by youtube 5000 albums? i really like to enjoy collect and save albums and have in a app a large number makes so easy to combine and search for specific music.

**Comment by fast4x** [comment]
yes is a limit on YTM that make sense...

**Comment by enomao44** [comment]
could be possible to make it much unlimited or very high the limit of albums saved in the app?

**Comment by twistios** [comment]
@enomao44 have you reached the limit already? I have not yet checked if there even is one (currently, maybe needs to be reduced to YTM limit once YTM login gets fully implemented).

**Comment by enomao44** [comment]
no, i would try it if i knew the limit is bigger
