### ISSUE TITLE
Sign in 

### ISSUE THREAD

**Issue by Neladdams** [fast4x/RiMusic#3221]
### Description

Create an account to access the app so you can save your personal settings 

### Suggested Solution

Create an account to access the app so you can save your personal settings

**Comment by twistios** [comment]
The app supports piped login which allows syncing of (certain?) playlists and maybe songs. I have not tested this feature yet.
Appearance settings and similar can currently not be synced.

**Comment by Neladdams** [comment]
So if I switch phones and install the app on another phone, will I have my playlists on the new phone?

**Comment by twistios** [comment]
You need a piped account for this to work. Also as I said, I don't know if it really works.

**Comment by fast4x** [comment]
> So if I switch phones and install the app on another phone, will I have my playlists on the new phone? 

Yes

**Comment by Neladdams** [comment]
The piped option doesn't work. Would there be any possibility to log in to RiMusic? 
Thank you

**Comment by fast4x** [comment]
No, RiMusic haven't login.
