### ISSUE TITLE
The Pacman easter egg doesn't work

### ISSUE THREAD

**Issue by BeepStation** [fast4x/RiMusic#3223]
### Steps to reproduce the bug

Click multiple times on RiMusic Logo

### Expected behavior

Pacman

### Actual behavior

Crappy pacman with weird graphical issues

### Screenshots/Screen recordings

![Screenshot_2024-08-11-23-40-53-053_it fast4x rimusic](https://github.com/user-attachments/assets/a9b297c8-63af-4a08-b26c-41335eab8812)

### RiMusic version

0.6.46

### Android version

Android 14

### Additional information

Replace it with a new easteregg please like a doodlejump it would great

**Comment by fast4x** [comment]
Will be removed in the future
