### ISSUE TITLE
audio format unknow

### ISSUE THREAD

**Issue by marsand-v3** [fast4x/RiMusic#3224]
### Steps to reproduce the bug

go to song https://music.youtube.com/watch?v=Pt1qIM1vjVQ and play

### Expected behavior

song play normally

### Actual behavior

song don't play and appear error "Couldn't find a playable audio format"

### Screenshots/Screen recordings

![Screenshot_20240811-195747](https://github.com/user-attachments/assets/c7d5a9c8-9ef9-49b0-9886-02d8870210c8)

### Logs

-

### RiMusic version

latest

### Android version

10

### Additional information

-

**Comment by marsand-v3** [comment]
on youtube plays normally

**Comment by faustaahmad** [comment]
Try custom version, perhaps

**Comment by fast4x** [comment]
I think that would be solved in next version if it's a bug.

**Comment by fast4x** [comment]
Try new custom version
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by marsand-v3** [comment]
Hi,
by setting the audio quality to "high" the error persists.
Thank you
   Sandro M.


Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: Rino Russo ***@***.***>
Data: 12/08/24 18:50 (GMT+01:00)
A: fast4x/RiMusic ***@***.***>
Cc: marsand-v3 ***@***.***>, Author ***@***.***>
Oggetto: Re: [fast4x/RiMusic] audio format unknow (Issue #3224)


Try new custom version
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by fast4x** [comment]
Isn't an error, not exists an audio version in high quality format, set automatic and maybe it work if it exists.

**Comment by marsand-v3** [comment]
Ok, thank you.
I have a question:
by setting the audio quality to automatic, is  the best available quality always used by default?
Thanks in advance...

Inviato dal mio Galaxy


-------- Messaggio originale --------
Da: Rino Russo ***@***.***>
Data: 14/08/24 14:15 (GMT+01:00)
A: fast4x/RiMusic ***@***.***>
Cc: marsand-v3 ***@***.***>, Author ***@***.***>
Oggetto: Re: [fast4x/RiMusic] audio format unknow (Issue #3224)


Isn't an error, not exists an audio version in high quality format, set automatic and maybe it work if it exists.

**Comment by fast4x** [comment]
Yes the best possible
