### ISSUE TITLE
se cae la aplicación 

### ISSUE THREAD

**Issue by pigevic** [fast4x/RiMusic#3225]
### Steps to reproduce the bug

sali de la aplicación para escuchar la música en el segundo plano, pero después de la segunda canción se cierra completamente la aplicación.

### Expected behavior

tendría que reproducirse la música desde el segundo plano sin problemas 

### Actual behavior

se corta la música de repente 

### RiMusic version

la última 

### Android version

REDMI 12

### Additional information

mada

**Comment by faustaahmad** [comment]
Misceláneo → Ignorar la optimización de la batería
