### ISSUE TITLE
Bug visual

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#3228]
### Steps to reproduce the bug

C/R

### Expected behavior

C/R

### Actual behavior

There is a visual bug that causes music, instead of playing the correct song, to play the one above

https://github.com/user-attachments/assets/b6f0b774-cb6d-46cc-a633-ad6de37bb31b

Also when you enter there is a bug from the old download version.  or at least for me

![Screenshot_2024-08-11-21-27-17-718_it fast4x rimusic](https://github.com/user-attachments/assets/cb3f1821-91a0-4689-989a-d66e9e3e63c0)
![Screenshot_2024-08-11-21-27-22-880_it fast4x rimusic](https://github.com/user-attachments/assets/adb839dc-101e-4c3c-bede-db8b69261857)

### Screenshots/Screen recordings

C/R

### RiMusic version

0.6.47.1

### Android version

Android 13

**Comment by twistios** [comment]
The second bug seems to be a "reincarnation" of an already fixed bug.
About the first one: Are you using sort by date played?

**Comment by fast4x** [comment]
Tey custom version

**Comment by JeePopuwu** [comment]
> El segundo error parece ser una "reencarnación" de un error ya corregido. Acerca del primero: ¿estás usando la clasificación por fecha de juego?

Yes, but I only get this error in music, because in playlist when I play by listening time there is no this bug

**Comment by twistios** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by JeePopuwu** [comment]
> https://github.com/fast4x/RiMusic/tree/master/customVersion
> 
> También den su opinión si funciona.

still the same error
