### ISSUE TITLE
Broken Titles

### ISSUE THREAD

**Issue by Wander42** [fast4x/RiMusic#3229]
### Steps to reproduce the bug

Ive noticed this mainly on Metropolis Pt.2 by Dream Theater, every song on this album bar the last two has a "scene number"

### Expected behavior

every song should have the scene number and if not i should be able to change it.

### Actual behavior

half of them are missing and if i want to add a colon ":" i cant.

### Screenshots/Screen recordings

![Screenshot_20240811_224624](https://github.com/user-attachments/assets/626d7934-ca80-430a-a99f-f455cbc2cec2)

### RiMusic version

V0.6.47.1

### Android version

Android 14

**Comment by fast4x** [comment]
Title change with long tap on song and click in change title.
