### ISSUE TITLE
Exportar favoritos de otras aplicaciones de streaming

### ISSUE THREAD

**Issue by KPO1221** [fast4x/RiMusic#3230]
### Description

Buenas creadores,me encantó su aplicación,pero tengo una incomodidad,ya que quiero escuchar mis canciones favoritas y tener las sugerencias que tengo en el Spotify,y me gustaría que pusieran una forma o manera de pasar mis me gusta de Spotify a RiMusic sin tener que hacerlo manual,para algunas personas con muchas canciones en me gusta

### Suggested Solution

En le apartado de favoritos añadir la opción "exportar me gustas de otras apps" y permitir moverl los me gustas de una app a RiMusic

### Alternatives

No creo que haya alternativa a esto

**Comment by fast4x** [comment]
Hi thanks, you must to transfer playlist from Spotify to YTM and after share it with RiMusic, finally import...
