### ISSUE TITLE
Listas de reproducción 

### ISSUE THREAD

**Issue by BANDA55** [fast4x/RiMusic#3234]
### Description

No sé puede ordenar bien las cansiones de una lista de reproducción 
![Screenshot_20240812-070509](https://github.com/user-attachments/assets/9fd94839-c53a-4001-b13b-0a122eca8651)

### Suggested Solution

Que uno mismo pueda mover una casion y poder ponerle antes o después de cualquier otra casion de su lista de reproducción

**Comment by fast4x** [comment]
You can do it, you have to select the sorting by location, unlock the lock and move the songs
