### ISSUE TITLE
Cuenta

### ISSUE THREAD

**Issue by Mo1ses654** [fast4x/RiMusic#3236]
### Description

En mi opinión debería estar la opción de poder crearse un cuenta o ingresar con nuestra cuenta de Google o de alguna otra plataforma para poder hacer una cuenta y que cuando haga alguna actualización de la app podamos recuperar rápidamente nuestros datos con nuestra cuenta

### Suggested Solution

Mi solución sugerida es que se pueda crear una cuenta o iniciar sesión con una cuenta de Google, Facebook o alguna otra

**Comment by fast4x** [comment]
Login to YTM isn't planned, but you can use a piped account and sync all playlists to various devices...
