### ISSUE TITLE
[Feature]: For You as Playlist or Now Playing

### ISSUE THREAD

**Issue by andrewteg** [fast4x/RiMusic#3237]
### Description

I set For You to random and it's great as I usually get some songs I want to hear. Sometimes I get a bunch and was looking for a way to make those 20 songs a playlist or add them as Now Playing. Is that possible?

Originally a discussion question at https://github.com/fast4x/RiMusic/discussions/3196

### Suggested Solution

Possibly add a "Play" button to the For You area next to the -> to choose?  If that replaced Now Playing with the songs in For You it could then be added to the Playlist, Shuffled/Sorted, etc.

I'm sure the devs may have a better/easier/more integrated idea, too!

### Alternatives

Long press each song and Enqueue individually.

**Comment by twistios** [comment]
Enqueueing individually already works.

**Comment by andrewteg** [comment]
> Enqueueing individually already works.

Right, I understood Alternatives as the best current workaround.  The enhancement/request would be being able to add all 20 or so "For You" songs to the Now Playing as the list in the Player.

**Comment by twistios** [comment]
"Alternative" is also for the case that a person has multiple ideas so that they can be split cleanly from the preferred idea. But a workaround seems also valid to me as it can better explain the idea.

**Comment by fast4x** [comment]
Implemented as playing now, it can add to playlists from queue...
Available from version 0.6.48
