### ISSUE TITLE
On device songs not playing on tapping them

### ISSUE THREAD

**Issue by HiroDane** [fast4x/RiMusic#3239]
### Steps to reproduce the bug

1. try to play any "on device" song by tapping the song from the songs tab. 

### Expected behavior

the song should start playing with the rest of the songs in the folder in the queue.

### Actual behavior

Nothing happens.

### RiMusic version

v0.6.47.1

### Android version

Android 13

### Additional information

This happened after I uninstalled and re-installed the app because it wasn't updating filenames that had been renamed from file manager. I also don't understand how the app can have my history retained from months back even after I uninstalled it and then re-installed it. I would like to do a clean install but don't know how.

**Comment by twistios** [comment]
Same issue as #3180.

**Comment by twistios** [comment]
A "clean install" option would also be useful for testing.

**Comment by aneesh1122** [comment]
It's a known issue. The only workaround for now is

![IMG_20240812_215718.jpg](https://github.com/user-attachments/assets/4114da5a-531b-46da-94d8-b02a3f099e20)

**Comment by fast4x** [comment]
Just fixed, available from version 0.6.48
Maybe i'll build a custom version..
