### ISSUE TITLE
Inaccurate file size on local songs

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#3242]
### Steps to reproduce the bug

・Play any local songs
・Trigger stats for nerds

### Expected behavior

Local songs has correct filesize

### Actual behavior

The size is lower than expected

### Screenshots/Screen recordings

![Screenshot_20240813-032452](https://github.com/user-attachments/assets/748bd079-6515-480d-8b1e-4e1d560f9ada)
![Screenshot_20240813-032659_MiXplorer](https://github.com/user-attachments/assets/3350c155-8eea-4f95-a4f3-75a058bc1342)

### RiMusic version

0.6.47.1 (49) https://github.com/fast4x/RiMusic/commit/ff57a1fb2042c3ae57d5ec29cde6815aa485b42c

### Android version

Android 11

### Additional information

Songs used: https://gofile.io/d/AIJrRz (any local songs would work)

**Comment by twistios** [comment]
I was, after serveral tries able to get my AVD to show the file (for some reason it did not want to do it for some time and then it worked after I opened the folder in the files app). As fast4x does not publish most of the code for the custom versions until the main release, I can only test on 0.6.47.1 normal version and not the custom version.
I am going to see if I can find some hints.

**Comment by twistios** [comment]
So the value based on which the displayed value gets calculated is `210069` (210kB).
This comes from here: `Format(songId=local:1000000035, itag=0, mimeType=audio/mp4, bitrate=227919, contentLength=210069, lastModified=1723580352, loudnessDb=null)`.
Based on the code I assume that it tries to find the info of the song based on the id. But once it is fetched from where ever, the information seems to be stored in the database so it gets harder to track this down.
