### ISSUE TITLE
audio error 

### ISSUE THREAD

**Issue by joaquidk** [fast4x/RiMusic#3245]
### Steps to reproduce the bug

Error in the music of a Juice wrld album. Specifically in the music "All girls aré the same" del álbum "Goodbye & Good Riddance (5 Years anniversary edition)"

### Expected behavior

Music played with correct audio 

### Actual behavior

Music with bad audio 

### Screenshots/Screen recordings

![Screenshot_20240813-005648](https://github.com/user-attachments/assets/1eccd36c-2723-4838-bed0-640830b2a401)

### RiMusic version

0.6.47.1

### Android version

Android 11

### Additional information

The damaged music only appears on that album (Goodbye & Good Riddance (5 Year Anniversary edition). On another album by the same singer, the song is played normally..

**Comment by fast4x** [comment]
Try custom version
