### ISSUE TITLE
Albums

### ISSUE THREAD

**Issue by Snow72219** [fast4x/RiMusic#3246]
### Description

Puedes agregar una opción para ordenar los álbumes por artista porfa

### Suggested Solution

Nada

### Alternatives

Nada

### Additional Context

Nada

**Comment by fast4x** [comment]
Look
![Screenshot_2024-08-13-13-57-29-689_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/d5f87576-f0be-4f2a-86fa-716e1ca69e2c)

just long tap on down/up arrow to show order menu
