### ISSUE TITLE
Floating search button issue 

### ISSUE THREAD

**Issue by Sankeerthan13** [fast4x/RiMusic#3247]
### Steps to reproduce the bug

1.Go to Ui  -> User Interface ( ViMusic ) 
2. Select and Deselect " Show floating search icon " option.

### Expected behavior

The Floating search icon must Vanish.

### Actual behavior

Floating search icon stays right there irrespective of the Choice 

### Screenshots/Screen recordings

![IMG_20240813_142630](https://github.com/user-attachments/assets/44617d84-33ec-46dd-82a7-81f740ddf61e)

![IMG_20240813_142402](https://github.com/user-attachments/assets/1da294c4-be60-4c6b-8bcf-93fd2bbe287e)

### RiMusic version

v0.6.47.1

### Android version

Android 13

**Comment by aneesh1122** [comment]
Don't select ViMusic UI

**Comment by fast4x** [comment]
You can move floating icon where you want just long tap on it and move...
