### ISSUE TITLE
Improvements in support for listening to audio videos

### ISSUE THREAD

**Issue by XGhostRX** [fast4x/RiMusic#3252]
### Description

There are certain problems trying to listen to some YouTube videos in the app

https://github.com/user-attachments/assets/4ecb1d72-a06d-488c-aa9d-33026ecb9875

### Suggested Solution

I think that in the next updates they should make most of the videos listenable as audio

### Additional Context

Compatibility issues

**Comment by fast4x** [comment]
Isn't an optimization, actually RiMusic not support videos.

**Comment by XGhostRX** [comment]
> Isn't an optimization, actually RiMusic not support videos.

In fact, if you can listen as audio

https://github.com/user-attachments/assets/b8b3d7eb-ca1d-403d-ab70-136ca1fb30cd

So what is that option for?

**Comment by fast4x** [comment]
If you select a video, an audio-only version of the same video is played. So if there are no audio versions of the video, nothing can be played.

**Comment by XGhostRX** [comment]
Well, I think that should be improved, because in some videos with audio they have compatibility problems
And I tried it in another app

**Comment by twistios** [comment]
It seems like some videos don't offer an audio-only version. That means that there is no video in it, only the audio. In your case @XGhostRX it may be a music video but it is still a video.

**Comment by XGhostRX** [comment]
> Parece que algunos vídeos no ofrecen una versión solo de audio.
> 
> La versión de solo audio significa que no contiene video, solo audio. En tu caso@XGhostRXPuede ser un video musical, pero sigue siendo un video. Y tal vez no exista una versión solo de audio.

Well, that needs to be improved as I said.

**Comment by fast4x** [comment]
In the future will add video support
