### ISSUE TITLE
Problema con la carátula de la música 

### ISSUE THREAD

**Issue by NormanMeneses** [fast4x/RiMusic#3253]
### Steps to reproduce the bug

1. Reproducir una música que no tiene carátula.
2. Reproducir una música que sí tiene carátula.
3. Error: se queda sin carátula. Solo el logo de RiMusic 

### Expected behavior

Que cambie a la carátula de la música que está reproduciendo.

### Actual behavior

No cambia la carátula.

### RiMusic version

0.6.44

### Android version

Android 11

**Comment by fast4x** [comment]
Use latest version please.

**Comment by NormanMeneses** [comment]
Gracias, pero continúa el bug en la versión 0.6.47.1
