### ISSUE TITLE
No option to reorder the songs in playlist

### ISSUE THREAD

**Issue by samyakmishra** [fast4x/RiMusic#3256]
### Steps to reproduce the bug

Open a playlist that you imported
There is no option to reorder the songs in the playlist 

### Expected behavior

There should be an option on the right hand side to drag and change the order of the songs 

### Actual behavior

There is no option to drag and change the order of songs 

### Screenshots/Screen recordings

![Screenshot_2024-08-14-15-41-57-432_it fast4x rimusic-edit](https://github.com/user-attachments/assets/b07ba0b5-1b5f-4cc1-a2b3-29a54f645563)

### RiMusic version

v0.6.47.1

### Android version

Android 14

**Comment by twistios** [comment]
This is not a bug in the sense that it is not possible for any playlist.
Currently there is only the open to shuffle the positions of the songs permanently. Manual reordering currently only works in the queue.

So this rather is a feature request.

**Comment by samyakmishra** [comment]
I'm sorry. 
I'll write it in the feature request, then
