### ISSUE TITLE
Problem with songs

### ISSUE THREAD

**Issue by OriginalJuani** [fast4x/RiMusic#3258]
### Steps to reproduce the bug

I went to the songs tab and in the "show/hide hidden songs" (the button with an eye) part, when I click on show, more than 500 songs are shown, when only the ones I heard should be shown, I suppose. The number of songs I listened to is not more than 50.

### Expected behavior

Show the songs I heard I guess.

### Actual behavior

Shows a lot of songs that I don't know or even remotely listen to.

### RiMusic version

0.6.47.1

### Android version

Android 13

**Comment by OriginalJuani** [comment]
> All songs are hidden except those with at least 1 second of listening

I'm sorry but I don't have a good understand of English and I don't know what you mean, I never listened to those songs, not even for a second. Could you explain it more broadly? Thanks and greetings, you made a great fork of ViMusic.

**Comment by fast4x** [comment]
The hidden songs have a minimum of listening time, even if you do not remember having listened to them, maybe the song was opened and you changed it immediately.

**Comment by OriginalJuani** [comment]
> The hidden songs have a minimum of listening time, even if you do not remember having listened to them, maybe the song was opened and you changed it immediately.

yeah, that could be in a lot of cases, but there is a bit more complex, in this case, I installed the latest version of RiMusic (I had uninstalled it before) and imported a playlist of 50 songs that I had previously, at that moment in "hidden" the 50 songs on my playlist appeared, which is not a problem, but the problem is that when I put a single song on, suddenly 500 more songs by other artists that I don't know or listen to appeared in the hidden tab, there is no way I listened to 500 songs for less than a second because I only clicked in one song, I only played one song, I hope my explanation is more concise now, thanks and greetings.

**Comment by fast4x** [comment]
I'll go into its details

**Comment by OriginalJuani** [comment]
thanks, its really nice to have a dev that worries abt his app
