### ISSUE TITLE
A list of improvements that could help in my opinion.

### ISSUE THREAD

**Issue by OriginalJuani** [fast4x/RiMusic#3259]
### Description

Well, some of the improvements I think that can be make are to be able to disable the "Piped", "Pinned Playlists" and "Monthly Playlists" etc on "Playlists" page (more customization), being able to activate, deactivate, leave fixed etc the floating button of "search", and having more control of the songs, like deleting them from the history, delete them from hidden, not only be able to hide them, etc.

### Suggested Solution

1- Be able to disable the "Piped", "Pinned Playlists" and "Monthly Playlists" options on the "Playlists" page, simply for more customization.
2- Be able to deactivate the floating search button or leave it fixed, since it can be annoying without wanting to press the search button and move it around.
3- Being able to easily delete songs from the "all" tab (in songs), since they can only be hidden and when they are hidden you cannot delete them, maybe configure that if you swipe to the left (which plays that song as the next one in the queue) or on the right (which saves the song as a favorite) to be able to configure it so that one of those two deletes the song from where it is placed. To give an example, it could be how it is done in the playlists, if you slide the song to the left it is deleted from the playlist.

**Comment by fast4x** [comment]
ok thanks

**Comment by OriginalJuani** [comment]
> ok thanks

Thanks to you for practically creating the application, the truth is that it is an incredible job and it is very nice to be able to collaborate with ideas, greetings

**Comment by fast4x** [comment]
1 implemented
2 just present
3 implemented delete from home songs
alla available from version 0.6.49

**Comment by OriginalJuani** [comment]
you are the fucking goat 😭

**Comment by fast4x** [comment]
I don't understand what you mean

**Comment by OriginalJuani** [comment]
oh, goat means "greatest of all time", it is usually used in popular slang as a compliment or something like that, it's like telling you "you're a genius"

**Comment by fast4x** [comment]
Oh my God, thanks a lot. 
I'm a normal person... with a passion... 🤩😜
