### ISSUE TITLE
Can't access some contents 

### ISSUE THREAD

**Issue by Guybrush3pw00d** [fast4x/RiMusic#3260]
### Steps to reproduce the bug

I was trying to play this content

https://music.youtube.com/watch?v=1MlfMOO2BkM

by RiMusic (v0.6.47.1, just downloaded from Github and updated to no avail as the 'problem' persist). Given that it isn't shown among the results for a search made within RiMusic, I've searched for it directly from my browser then shared the result.

### Expected behavior

I expected it to play just fine after adding it to my playlist but this wasn't the case.

### Actual behavior

It just gets stuck loading forever. 

### RiMusic version

0.6.47.1

### Android version

A13

**Comment by fast4x** [comment]
RiMusic currently does not support video, this means that if YTM don’t have the audio version of a video, nothing will be played.

**Comment by Guybrush3pw00d** [comment]
First of all thanks for your prompt and clear follow-up. I expected sonthehing like that and that was the reason why I've used the quotation marks around the word "problem".
I'd like that I'm not arguing about anything: RiMusic is ALREADY a great piece of programming but I was wondering if such a feature could be added in some way.
It often happens to me to have videos I don't care for but I just want to listen to the music with the screen off and by VLC I do it 'simply' (please note the quotation marks, again!) by clicking "Play as audio".
I expect it involves some kind of real-time transcodiing and/or demuxing. It also need to be noted that to some extent adding such a feature means denaturalising the funding idea behind RiMusic so I would understand if such a feature wouldn't ever been scheduled.
Have a nice day and thanks for everything, anyway. :)

**Comment by fast4x** [comment]
Video support is planned for the future, but i don't know when.

**Comment by Guybrush3pw00d** [comment]
Thanks. I'll patiently wait for it. It would be a great addition, at least I believe so. Have a nice day! :)
