### ISSUE TITLE
Cant return to original youtube song playlist after searching song inside

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#3262]
### Steps to reproduce the bug

・Open RiMusic
・Search → Online → any just make sure it has Playlists
・Click one of the Playlists
・Click on small search button
・Search for any

### Expected behavior

After done using search, songs inside youtube playlist should return to original

### Actual behavior

After done using search, other songs that doesnt match search keyword gone until reinitialize that youtube playlist (back button → click on that playlist)

### RiMusic version

0.6.47.1 https://github.com/fast4x/RiMusic/commit/ff57a1fb2042c3ae57d5ec29cde6815aa485b42c

### Android version

Android 11

### Additional information

Workaround before it get fixed
Import the playlist then search from there

**Comment by fast4x** [comment]
Fixed, available from version 0.6.49
