### ISSUE TITLE
Why YT Music login isn't implemented?

### ISSUE THREAD

**Issue by AsuToki360** [fast4x/RiMusic#3263]
### Description

Just like the title says, why is it not implemented and why is isn't planned? I hear uploaded music in YT Music, and I want to try a nice client that has customisations and etc etc, but I checked on the issues that it's not planned.

And I have no idea how Piped works and no idea if you can upload your own music in there just like YT Music does.

### Suggested Solution

I wish this app had Google account support, since I mostly hear my uploaded songs in YT Music.

**Comment by fast4x** [comment]
YouTube login requires adding proprietary library and track your privacy. Isn't planned. If you want sync your playlists, can use a piped account.
