### ISSUE TITLE
Suggestion for UI Enhancement

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#3269]
After a long time, I’m finally sharing a suggestion again 🙂.

I would like to suggest an optional UI improvement, based on the mockup video I've provided. Currently, the tab control elements are permanently positioned at the top of the music list. This means that when scrolling down, the controls become inaccessible, which can be frustrating, especially with long song lists. 

To improve usability, I propose that the basic control elements remain visible at the top of the screen, even when scrolling down the song list. Only the tabs should be hidden during scrolling for better visibility. When the user scrolls back up, the tabs should reappear immediately, allowing for easy navigation between them.

This change would enhance user experience by providing continuous access to the controls while still keeping the interface clean and functional.

I hope this idea finds some support.

Greetings too all ✌🏼.

---

_The left side shows how it is now. The right side shows how I envision it:_

https://github.com/user-attachments/assets/fa0857f2-fb49-4913-960a-ded28195d0e5

**Comment by fast4x** [comment]
Hello @dAtA-TRoN ok

**Comment by fast4x** [comment]
it's cool

**Comment by dAtA-TRoN** [comment]
It’s crucial that we have visual feedback in the form of a scrollbar so we can easily assess how long the list is. I’m sure others have brought this up before, but I wanted to emphasize it again. Without this indicator, navigating through a long list of songs can feel disorienting.

**Comment by fast4x** [comment]
Implemented fixed header in home songs, for now...
Available from version 0.6.48

**Comment by dAtA-TRoN** [comment]
> Implemented fixed header in home songs, for now...
> Available from version 0.6.48

Wow, as fast as you always are!

![Jurassic-Park-Игры-анимация-гифки-3178902.gif](https://github.com/user-attachments/assets/59c9c45c-cc71-450b-a276-be8fff557560)
