### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by Shivam-G732** [fast4x/RiMusic#3270]
### Steps to reproduce the bug

The app suddenly crahes when play some song in background and it happens everytime when i open app and play songs in background without any reason and i have very stable internet but this problem exist and have latest ANDRIOD 14 and some time when we are on app the app also crashes and suddenly song automatically stops

### Expected behavior

App can work smoothly without any interruption app can be optimised

### Actual behavior

Very laggy , very frequently crashes on latest devices 

### RiMusic version

v0.6.47.1

### Android version

Andriod 14

**Comment by Shivam-G732** [comment]
2024-08-15T19:09:37.772:	java.lang.IllegalStateException
	 n2.b.h(SourceFile:6) 
	 r2.x.h(SourceFile:6) 
	 r2.x.g(SourceFile:34) 
	 a6.c.E(SourceFile:94) 
	 I6.P0.q(SourceFile:170) 
	 e0.a.f(SourceFile:44) 
	 e0.a.q(SourceFile:9) 
	 B.n.g(SourceFile:355) 
	 e0.a.g(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 E.L.b(SourceFile:248) 
	 D.m.e(SourceFile:104) 
	 B6.L.g(SourceFile:448) 
	 e0.a.g(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 g0.f.c(SourceFile:149) 
	 E.l0.c(SourceFile:87) 
	 E.L.d(SourceFile:105) 
	 A6.Y.g(SourceFile:873) 
	 e0.a.g(SourceFile:52) 
	 A6.Y.g(SourceFile:641) 
	 e0.a.g(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.q.p(SourceFile:203) 
	 W.u.k(SourceFile:32) 
	 W.u0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.u.l(SourceFile:9) 
	 G0.H.i(SourceFile:22) 
	 G0.H.h(SourceFile:121) 
	 G0.C.H(SourceFile:160) 
	 E.T.a(SourceFile:34) 
	 D.q.b(SourceFile:21) 
	 D.r.b(SourceFile:62) 
	 s7.o.l1(SourceFile:23) 
	 D.s.g(SourceFile:639) 
	 A6.Y.g(SourceFile:758) 
	 G0.E.g(SourceFile:74) 
	 I0.u.a(SourceFile:38) 
	 q0.Y.i(SourceFile:1) 
	 I0.A.a(SourceFile:15) 
	 B.c0.i(SourceFile:117) 
	 I0.A.a(SourceFile:15) 
	 B.D.i(SourceFile:99) 
	 I0.A.a(SourceFile:15) 
	 B0.b.a(SourceFile:363) 
	 e1.c.y(SourceFile:56) 
	 h0.t.a(SourceFile:52) 
	 h0.u.c(SourceFile:140) 
	 I0.m0.a(SourceFile:3) 
	 I0.K.s0(SourceFile:133) 
	 I0.K.a(SourceFile:91) 
	 B.d.g(SourceFile:86) 
	 B.x.g(SourceFile:40) 
	 I0.u.a(SourceFile:38) 
	 w.K0.i(SourceFile:50) 
	 I0.A.a(SourceFile:15) 
	 q0.Y.i(SourceFile:1) 
	 I0.A.a(SourceFile:15) 
	 B.D.i(SourceFile:99) 
	 I0.A.a(SourceFile:15) 
	 B0.b.a(SourceFile:363) 
	 e1.c.y(SourceFile:114) 
	 h0.t.a(SourceFile:52) 
	 h0.u.c(SourceFile:140) 
	 I0.m0.a(SourceFile:3) 
	 I0.K.s0(SourceFile:133) 
	 I0.F.N(SourceFile:17) 
	 I0.F.O(SourceFile:18) 
	 I0.T.c(SourceFile:8) 
	 I0.T.m(SourceFile:138) 
	 I0.T.j(SourceFile:90) 
	 J0.w.v(SourceFile:36) 
	 J0.w.dispatchDraw(SourceFile:17) 
	 android.view.View.draw(View.java:24291) 
	 android.view.View.updateDisplayListIfDirty(View.java:23111) 
	 android.view.View.draw(View.java:23985) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4597) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4349) 
	 android.view.View.updateDisplayListIfDirty(View.java:23099) 
	 android.view.View.draw(View.java:23985) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4597) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4349) 
	 android.view.View.updateDisplayListIfDirty(View.java:23099) 
	 android.view.View.draw(View.java:23985) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4597) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4349) 
	 android.view.View.updateDisplayListIfDirty(View.java:23099) 
	 android.view.View.draw(View.java:23985) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4597) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4349) 
	 android.view.View.updateDisplayListIfDirty(View.java:23099) 
	 android.view.View.draw(View.java:23985) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4597) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4349) 
	 android.view.View.updateDisplayListIfDirty(View.java:23099) 
	 android.view.View.draw(View.java:23985) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4597) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4349) 
	 com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1057) 
	 android.view.View.draw(View.java:24291) 
	 com.android.internal.policy.DecorView.draw(DecorView.java:1047) 
	 android.view.View.updateDisplayListIfDirty(View.java:23111) 
	 android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:748) 
	 android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:754) 
	 android.view.ThreadedRenderer.draw(ThreadedRenderer.java:861) 
	 android.view.ViewRootImpl.draw(ViewRootImpl.java:5567) 
	 android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5242) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4339) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2811) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10277) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1752) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1761) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1272) 
	 android.view.Choreographer.doFrame(Choreographer.java:1139) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1735) 
	 android.os.Handler.handleCallback(Handler.java:1013) 
	 android.os.Handler.dispatchMessage(Handler.java:101) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:328) 
	 android.app.ActivityThread.main(ActivityThread.java:9210) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)

**Comment by twistios** [comment]
This seems to be the same issue as I have already reported some time ago. #2729
