### ISSUE TITLE
build with Kotlin 2.0.10 stuck

### ISSUE THREAD

**Issue by XilinJia** [fast4x/RiMusic#3273]
### Steps to reproduce the bug

upgrade Kotlin to 2.0.10 or 2.0.0, build, the build process is stuck in compiledebugkotlin

### Expected behavior

should complete

### Actual behavior

build process is stuck in compiledebugkotlin

### RiMusic version

0.6.47.1

### Android version

all

### Additional information

Likely not an issue of your project.  Perhaps you noticed it and it's why you didn't upgrade to 2.0.0?

I filed an issue with Kotlin at: https://youtrack.jetbrains.com/issue/KT-70715/build-stuck-in-compiledebugkotlin

Nice project BTW.

**Comment by fast4x** [comment]
I had realized that there was some problem so I’m taking time to update

**Comment by fast4x** [comment]
> Nice project BTW
Thanks

**Comment by fast4x** [comment]
Fixed with kotlin 2.0.20

**Comment by XilinJia** [comment]
Yes, just tested. got some errors on named arguments. rid of those and it built through. Great.
