### ISSUE TITLE
music control from the Lock screen 

### ISSUE THREAD

**Issue by Nyova-ws** [fast4x/RiMusic#3276]
### Description

With this new feature, you'll be able to handle your music without unlocking your phone. From the lock screen, you'll have shortcut to play, pause, change songs, and adjust the volume. This way, enjoying your playlists will be easier and faster, without interruptions or complications. Perfect for when you're on the move or just want to change clothes without wasting time. Play your music in the most practical way! 

### Suggested Solution

User interface on lock screen: Persistent notifications: Implements a persistent notification showing play/pause controls (next, previous, and volume control). This can be done using a MediaStyle on Android or the notification framework on iOS. Operating System Integration:Android: Use the MediaSessionCompat class to communicate with the system and update media controls on the lock screen. Make sure you set the MediaSession to the correct states to make the buttons work well.iOS: Deploy MPNowPlayingInfoCenter and MPRemoteCommandCenter to update song information and handle remote control events (such as play, pause, and skip) from the lock screen. Permissions and Settings: Ask the user to turn on the media controls on the lock screen from the app settings, if not enabled by default. Make sure you handle notification and audio permissions well so the functionality runs smoothly. Testing and optimization: Test functionality across different versions of the operating system to ensure compatibility. Optimize resource usage so the app doesn't consume much battery when it's in the background or on the lock screen.

**Comment by TanishMoral11** [comment]
Hey @Nyova-ws @fast4x 
This Feature is Already Present In This App 
So Kindly Close This Issue
