### ISSUE TITLE
RiMusic keeps stopping

### ISSUE THREAD

**Issue by agusz-source** [fast4x/RiMusic#3277]
### Steps to reproduce the bug

Just open RiMusic and it automatically stops

### Expected behavior

The app should open correctly I think

### Actual behavior

Instead, if you open RiMusic the app closes and You get a message saying "RiMusic keeps stopping" with two options, one to close app an the other to view app info

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/0d363d6b-a2f7-461c-abb4-51ef18c5e9fa

sorry for the quality or the watermark

### RiMusic version

v0.6.47.1

### Android version

Android 14

### Additional information

I don't have root
I dont know if it is useful  , but I have a stock ROM, but installed from SamFW (so it's not 100% official, let's say)

**Comment by faustaahmad** [comment]
Try custom version
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by agusz-source** [comment]
> Try custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

I tried it but it doesn't works, idk

**Comment by faustaahmad** [comment]
Try to disable battery optimization from settings
