### ISSUE TITLE
Video Search not working

### ISSUE THREAD

**Issue by Gaxi2** [fast4x/RiMusic#328]
### Steps to reproduce the bug

1. Open app.
2. Click search icon on top right corner.
3. Search song (e.g, sawre).
4. Select videos category.
5. The results won't load.

### Expected behavior

It should give list of songs in video categories after I make a search.

### Actual behavior

It keeps loading and never shows any list only in videos category. Remember it works sometimes but sometimes just keeps loading. 
Like if I search **"sawre"** or **"s a w r e"**, it keeps loading 
but if I search **"s a w a r a"** it loads the results which are somewhat accurate. 

### RiMusic version

0.6.15.1

### Android version

Android 13

### Additional information

Please fix ASAP.

**Comment by fast4x** [comment]
But, video playback is not currently supported

**Comment by fast4x** [comment]
I've tested with other search term like Deep House and results show.
I'll check It for YouTube api results.

**Comment by Gaxi2** [comment]
> But, video playback is not currently supported

I think there is a misunderstanding, I am not talking about video playback but the videos section which shows after we search a term. In my case, terms like sawre, or other long multiple word terms are getting stuck on loading in the video section only.

**Comment by Gaxi2** [comment]
> I've tested with other search term like Deep House and results show.
> I'll check It for YouTube api results.

Yeah that's the issue here. It works with some words and gets stuck with some others. I hope you will fix this asap. Thanks

**Comment by fast4x** [comment]
Thank you for the positive feedback, I will try to fixare the problem if possible.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.18
