### ISSUE TITLE
NO ME PERMITE REPRODUCIR CANCIONES

### ISSUE THREAD

**Issue by JQdV** [fast4x/RiMusic#3280]
### Steps to reproduce the bug

Cuando intento reproducir alguna canción, esta al principio sí me permite escucharla por lo menos 3 minutos, per en un punto se pausa la música y no me permite seguir reproduciendo ninguna canción. Cuando esto me sucede me salta un letrero el cual dice: "No se pudo encontrar un formato de audio compatible".

### Expected behavior

La aplicación me permitiría escuchar las canciones sin ningún problema por el tiempo que desee.

### Actual behavior

La aplicación no me permite escuchar ninguna canción y se mantiene estatica en el reproductor con el letrero parpadeando constantemente.

### RiMusic version

0.6.47.1

### Android version

Android 9

**Comment by fast4x** [comment]
It means that there are no versions of the song with only audio

**Comment by Cruguer** [comment]
Tengo el mimo comportamiento, pero es solo en algunas canciones. 
![Screenshot_2024-10-20-06-35-56-053_it fast4x rimusic](https://github.com/user-attachments/assets/115fc4ba-6972-4cf8-8e75-ddcd311839bf)

**Comment by fast4x** [comment]
I can't solve it sorry
