### ISSUE TITLE
 Translation button not asking language everytime

### ISSUE THREAD

**Issue by Kurrode** [fast4x/RiMusic#3281]
### Description

The translation button asks for target language everytime and the menu gets back up even when you swipe to go back

### Suggested Solution

Translation button translates to default language if pressed once, then to the original language and then to the default language and so on.

To change language you'll need to hold down the button.

### Additional Context

Please, I desperately need this feature to works like this because I use songs to learned languages and I need to switch back and forth fast.

**Comment by faustaahmad** [comment]
Cant go back unless pressing one of the options, cant even go back with `back` button on my end

I would suggest adding the default translation language to the settings/menu, less action needed when translation need to be used

Holding the translation button to change default translation language also good to have, but it'd lack user documentation (like sort by, blur strengh, and carousel view, etc if any)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.50
