### ISSUE TITLE
Las canciones no se descargan

### ISSUE THREAD

**Issue by ItsHiroLeo** [fast4x/RiMusic#3283]
### Steps to reproduce the bug

1. voy a una cancion 2. toco el boton de descargar 3. por algún motivo no se descarga la cancion o album 

### Expected behavior

las canciones o albumes deberian de descargarse con normalidad

### Actual behavior

en lugar de descargar la cancion o audio, se queda cargando infinitamente

### Screenshots/Screen recordings

![Screenshot_20240815_222450](https://github.com/user-attachments/assets/06f82a35-4518-4f61-8107-b0f393b64f29)

### RiMusic version

v0.6.46

### Android version

Android 13

**Comment by fast4x** [comment]
Use latest version please
