### ISSUE TITLE
Local Device music files not playing 

### ISSUE THREAD

**Issue by ksnprogrammer** [fast4x/RiMusic#3287]
### Steps to reproduce the bug

1. Songs
2. On device
3.  select music folder
4. click music on device 
![Screenshot_20240816_210749_it fast4x rimusic](https://github.com/user-attachments/assets/b454fa3b-c344-46c5-8f4d-ca3bdfd6d447)

### Expected behavior

Play the device music file

### Actual behavior

But not playing music

### RiMusic version

0.6.47.1

### Android version

Android 10

**Comment by fast4x** [comment]
Just fixed and available in version 0.6.48
