### ISSUE TITLE
Error al reproducir 

### ISSUE THREAD

**Issue by Sebastian-coder07** [fast4x/RiMusic#3289]
### Steps to reproduce the bug

Al reproducir una canción funciona con normalidad, al cabo de un tiempo se detiene la música y arroja un mensaje diciendo que no se encontró archivo de música y pasa con varias canciones, para detener este mensaje y poder reproducir me toca cerrar la app y abrirla al cabo de un tiempo

### Expected behavior

Reproducir con normalidad 

### Actual behavior

Detiene la reproducción 

### Screenshots/Screen recordings

![Screenshot_2024-08-16-14-00-39-111_it fast4x rimusic](https://github.com/user-attachments/assets/4e3b2092-dbe1-43a5-95a7-28923bd83085)

### RiMusic version

0.6.47.1

### Android version

Android 13

**Comment by fast4x** [comment]
Try with latest version please

**Comment by Sebastian-coder07** [comment]
Sigue sucediendo y ocurre más cuando está activado la opción cola persistente, al cerrar y abrir la app sale el error con las frecuencia
