### ISSUE TITLE
[Feature]: Add Persian language support

### ISSUE THREAD

**Issue by CUMOON** [fast4x/RiMusic#329]
### Description

I would like to request the addition of Persian language support. There are many Persian speakers who would appreciate being able to use the project in their own language.

### Suggested Solution

Add Persian language support to crowdin

**Comment by fast4x** [comment]
Added, thank you for request.

**Comment by fast4x** [comment]
We keep the ticket open until the next release.

**Comment by fast4x** [comment]
From next version, your name is added on About page in app and on Github project page.
Thanks for your Persian translation

**Comment by fast4x** [comment]
Available on version 0.6.16.1
