### ISSUE TITLE
Audio Files

### ISSUE THREAD

**Issue by Scrat80** [fast4x/RiMusic#3290]
### Steps to reproduce the bug

Try playing M4A or OPUS audio file

### Expected behavior

Should play

### Actual behavior

No reaction from app. Not even a message saying file is unsupported.

### RiMusic version

Current

### Android version

Android 14

**Comment by fast4x** [comment]
You mean about local file?

**Comment by Scrat80** [comment]
As in on device.

**Comment by faustaahmad** [comment]
Could you provide step on how to reproduce the problem?
You could play local songs in RiMusic, but need to access them inside RiMusic (Songs → On Device)

**Comment by Scrat80** [comment]
1) Get an M4A and/or OPUS file
2) Make sure RiMusic sees the file(s)
3) Try playing song(s)

Music downloaded from YouTube has zero issues playing.

**Comment by faustaahmad** [comment]
`.m4a` is a container (not codec) as it may contain unsupported audio codec inside
https://wikipedia.org/wiki/Comparison_of_video_container_formats
Somehow my device could play `.opus` file (sample3.opus) from https://filesamples.com/formats/opus

**Comment by fast4x** [comment]
@Scrat80 RiMusic is totally compatible with YouTube/Music codec and containers. As mentioned by @faustaahmad other formats aren't supported because not directly connected with streaming arguments.
