### ISSUE TITLE
"Show/Hide hidden songs" bug.

### ISSUE THREAD

**Issue by OriginalJuani** [fast4x/RiMusic#3291]
### Steps to reproduce the bug

-Download RiMusic (Last version but the bug is still in previous versions).
-Open RiMusic.
-Go to "Songs".
-There are no hidden songs in the "hidden" part since I didn't listen to any.
-Listen to just one song (the more you listen the more songs later appear hidden).
-Go to "Songs" again.
-Now in "Songs" are a minimum of 50 songs in "hidden" (its just my case, idk if in another cases are 20, 100, etc).
-I just listen one of those 50 songs, they arent supposed to be there. 

### Expected behavior

Only the songs that I listen to should be shown, and they should not be "hidden" by default, since all songs are supposed to be shown except those that you hide manually.
-Only the songs I listened to would be shown.
-They would be shown in "Hide hidden songs" by default, unless I hide them, where there they should be shown in "Show hidden songs".

### Actual behavior

First of all, those songs are not supposed to be hidden, since they were never hidden, so they should be shown in the tab regardless of whether the songs are hidden or not, and of the specific bug I am writing about, songs that I have never heard are shown.
-Songs are "hidden" by default.
-Songs that I have never heard are shown.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/2fec8506-1175-4c6c-b4c3-e0e72d5b7563

### RiMusic version

v0.6.48

### Android version

Android 13

### Additional information

I had already posted this bug a few days ago, but with the release of the new version (0.6.48) and the fact that I previously had written it quite poorly, I decided to close the topic and reopen it now well done.

**Comment by OriginalJuani** [comment]
I hope it can be solved, its the only major bug that I found out, ignoring that, the app is great

**Comment by OriginalJuani** [comment]
UPDATE: I also noticed that they are recommended topics in reference to the song (for example, I tried listening to a court song from a club and 50 more court songs from the same club and others appeared)

**Comment by fast4x** [comment]
This isn't a bug, songs not listened are automatically hidden.
