### ISSUE TITLE
[Feature]: Provide essential info in Crowdin Translation

### ISSUE THREAD

**Issue by Clyde6790pGIT** [fast4x/RiMusic#3295]
### Description

Please provide PROPER context in Crowdin Strings, I have reported this before but it has been closed without it getting solved.

### Suggested Solution

Please provide info on where each strng is used by commenting on Crowdin where it is used
Ex: "This string is used when you increase the lyric size"

### Alternatives

Make a github wiki containing info of each string and provide pictures or context just like in the suggested solution

### Additional Context

I am a native speaker of Filipino that can translate English to Filipino, problem is that in my language, the context of the sentence HEAVILY changes the entire sentence, which can cause horrible translations or translations that don't relate ANYTHING to where it is used, and this can be the same case for other languages too, I do not have the time to go surfing in the app to find where each string is used as my time is limited and I only work during weekends.

**Comment by fast4x** [comment]
Hi i don't have the time to add context fir all strings. Sorry.

**Comment by faustaahmad** [comment]
Add 'em by yourself, I did add some context in the comments for some of the strings

**Comment by OriginalJuani** [comment]
Taking advantage of the topic being brought on, I wanted to let you know that even though the Spanish translation is already 100% complete, it is not completely correct, since some translations do not mean the same thing in Spanish as they do in English, I just wanted to let you know to see if they could accept some new change requests despite already being at 100% (I say this as a native Spanish speaker), thanks and greetings

**Comment by fast4x** [comment]
Hi, of course you can correct the translation even if it is complete. On the contrary I propose you to become a proofreader on Crowdin so that you can correct and approve that you are a native speaker.

**Comment by OriginalJuani** [comment]
That idea seems perfect to me, I hope I can help with the translation to spanish correcting it, thank you

**Comment by fast4x** [comment]
> That idea seems perfect to me, I hope I can help with the translation to spanish correcting it, thank you 
> 

Done, now you can change and approve your translation.

**Comment by OriginalJuani** [comment]
Thank you very much, I had a good time correcting some errors, haha.

**Comment by OriginalJuani** [comment]
Update: After 4 hours reviewing each of the texts, finally the Spanish translation is 100% corrected (great work by those who translated into Spanish previously btw, most things only had minimal errors) 🥳 🎉

**Comment by fast4x** [comment]
Great, thanks

**Comment by Clyde6790pGIT** [comment]
> Add 'em by yourself, I did add some context in the comments for some of the strings

Thanks for providing the context, it really helped me with translation

**Comment by OriginalJuani** [comment]
> > Add 'em by yourself, I did add some context in the comments for some of the strings

thanks, that really helped in some cases when the traduction can be ambiguous

**Comment by maboroshin** [comment]
## How to search the context of a translation

1. Open context on Crowdin. In this example, the ID (or key) is "my_playlist_top".

![image](https://github.com/user-attachments/assets/041a52af-0b94-4042-91d5-7206a0e90040)

----

2. Search GitHub for the ID and filter by "code". In the example, it is located in "HomeLibrary.kt and UiSettings.kt". You will find them in home, library, and UI settings. This is estimated.

In this project, "strings.xml" is a translation file. The location can't be assumed from this file. This search method can't be used for projects where the only search results are translated files.

![image](https://github.com/user-attachments/assets/34515cb7-1fe8-405a-a3b5-e5ceeacbe994)

Searching for "light" will return irrelevant files. In these cases, search for "string.light" in the Android project. These filter strings vary from project to project. There are also examples without "string." It means that there are examples of "/light" in the code in the same Andoroid project. In other words, it can be difficult to find. So, it's more reliable to search for long IDs without "string.

----
3. There are strings with arguments. There are cases that can be read and understood. In the above example, the "%s" would be numbers.

`(R.string.my_playlist_top).maxTopPlaylistItems.number)`

So, translate this.

`My Top 10`

Change "10" back to "%s" and register it as a translation.

**Comment by maboroshin** [comment]
Related:

* `Clean cached congs` : wrong spell
* `Clean cached songs` : corect

See : https://github.com/fast4x/RiMusic/issues/1820
----

* `By Casual played song` : means : Random song selection at regular intervals

See : https://github.com/fast4x/RiMusic/issues/3178 https://github.com/fast4x/RiMusic/issues/1533
