### ISSUE TITLE
Playlist (cover)

### ISSUE THREAD

**Issue by Luna3003** [fast4x/RiMusic#3296]
### Description

Portada para Playlist 

### Suggested Solution

Podría agregarle al sistema la opción de poner una portada a la Playlist, también seleccionar varias canciones a la vez y pasrlas a una Playlist. 
Eso sería todo, excelente aplicación.

### Alternatives

Tener la opción de acceder a la galería del dispositivo para poner la portada deseada.

### Additional Context

Esto ayudaría a la satisfacción de los usuarios para su personalización.

**Comment by fast4x** [comment]
Hi, for songs you can already do this by selecting multiple songs and putting them in playlists or a new one. You can also export the queue to a playlist.
![Screenshot_2024-08-17-12-32-06-324_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/29557ba5-8ef4-4775-ba71-9ed9090b12be)
