### ISSUE TITLE
Player bug

### ISSUE THREAD

**Issue by kris20030705** [fast4x/RiMusic#3298]
### Steps to reproduce the bug

![Screenshot_20240817-143751_RiMusic](https://github.com/user-attachments/assets/0812a67b-a7a5-4a71-ba22-133247fddc59)

Maybe i am not able to understand or this is a bug..but it keep skipping songs automatically eventhou I didnt press next button..and i tired on lowest(skipping songs in seconds) and highest(next songs in the middle of the song)
There is not option to off this

### Expected behavior

Plays song til last..!

### Actual behavior

Auto skipping song

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/fd9c62a3-088f-49e8-8d32-57800f7cf55d

### RiMusic version

6.4.8(50)

### Android version

Android 13

**Comment by fast4x** [comment]
Yes set to 0 or click to hourglass

**Comment by kris20030705** [comment]
> Yes set to 0 or click to hourglass

not able to set 0 using that slider..!
i though double click on slider might reset it
clicking hourglass worked..

**Comment by fast4x** [comment]
Fixed, available from version 0.6.49
