### ISSUE TITLE
Unresolved case of crashes when listening to local songs on some devices

### ISSUE THREAD

**Issue by XGhostRX** [fast4x/RiMusic#3299]
### Steps to reproduce the bug

Search for songs from your device

### Expected behavior

Be able to listen to local songs

### Actual behavior

The same unexpected closures

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/a7086675-4058-473a-a718-e669da1623ca

### Logs

[log.txt](https://github.com/user-attachments/files/16644414/log.txt)

### RiMusic version

0.6.48

### Android version

Android 10

### Additional information

I use a huawei p30 lite MAR-LX3A
So far, no update solves the problem

**Comment by fast4x** [comment]
You have songs with same id, rhis actually cause the crash. I'll add a check to prevent double song id.

**Comment by fast4x** [comment]
Fixed available from version 0.6.49
