### ISSUE TITLE
Option for now playing skin

### ISSUE THREAD

**Issue by dns24** [fast4x/RiMusic#33]
### Description

There's no issue with the stock ui of now playing in rimusic, but it'd be good if there's an option to chose back default like back in vimusic

### Suggested Solution

Adding between stock vimusic and default rimusic now playing skin.

**Comment by fast4x** [comment]
Are you talking about the size of the image in now playing?

Can you give me an example about your request?

**Comment by fast4x** [comment]
Maybe you would like to customize the now playing screen?
Example: 

- Simple skin > thumbnail size, label centered...
- Advanced skin 
- Musician skin

is this?

**Comment by NEVARLeVrai** [comment]
> Maybe you would like to customize the now playing screen?
> Example: 
> 
> - Simple skin > thumbnail size, label centered...
> - Advanced skin 
> - Musician skin
> 
> is this?
> 

You could, that would be an interesting option

**Comment by NEVARLeVrai** [comment]
> Maybe you would like to customize the now playing screen?
> Example: 
> 
> - Simple skin > thumbnail size, label centered...
> - Advanced skin 
> - Musician skin
> 
> is this?
> 

You could, that would be an interesting option

**Comment by OrangeZXZ** [comment]
@fast4x im not sure if this issue is still valid since now you have RiMusic and ViMusic style menus

**Comment by fast4x** [comment]
Yes, it's much old... and not actual.
