### ISSUE TITLE
[Feature]: Like switch in notification bar

### ISSUE THREAD

**Issue by nocd** [fast4x/RiMusic#330]
### Description

Like switch would be handy for user for toggling favorite status of song when screen is locked or when app is closed

### Suggested Solution

Add like switch in notification bar

**Comment by fast4x** [comment]
Hi, is under development.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.17

**Comment by fast4x** [comment]
Hello, keep the ticket open until the next release. Will be close during release.
