### ISSUE TITLE
Does not appear in Android Auto, HyperOS, Poco F3

### ISSUE THREAD

**Issue by harverto** [fast4x/RiMusic#3307]
### Steps to reproduce the bug

Hi, the app does not appear at Customize apps at Android Auto.
My device is a HyperOS Poco F3 1.0.2.0 TKHEUXM
All apps and system is fully updated.
Tried with developer mode with no results.

### Expected behavior

App should be at Customize apps an Android Auto.

### Actual behavior

Does not appear in the list.

### RiMusic version

0.6.47.1

### Android version

13 TKQ1.221114.001

**Comment by fast4x** [comment]
Have enabled it in miscellanous settings?

**Comment by harverto** [comment]
Ups, I hadn't seen the lower settings menus.
Thanks and sorry for the inconvenience
