### ISSUE TITLE
[Feature]: Hide file extensions on local files

### ISSUE THREAD

**Issue by Davutha** [fast4x/RiMusic#331]
### Description

I absolutely love the local files function, it's such a good addition but it would be better if the app could hide the file extension or read the metadata besides the art cover
![Screenshot_2024-01-05-18-48-06-020_com android chrome-edit](https://github.com/fast4x/RiMusic/assets/68203036/3137e79c-3bed-48ba-a500-71032b929425)

### Suggested Solution

Maybe using the file metadata instead of the file name itself would fix the problem.

**Comment by fast4x** [comment]
Ok, thanks for request.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.17

**Comment by fast4x** [comment]
Available on version 0.6.16.1
