### ISSUE TITLE
[Feature]: Vi theme default theme setting

### ISSUE THREAD

**Issue by kris20030705** [fast4x/RiMusic#3311]
### Description

Vi default theme is sh*t..!

### Suggested Solution

Can you apply this setting as default
![Screenshot_20240818-174917_RiMusic](https://github.com/user-attachments/assets/a66288b7-38b3-443f-8644-b1912b6363c9)

Setting:
![Screenshot_20240818-175112_RiMusic](https://github.com/user-attachments/assets/ab64f031-0e74-4dc4-88f1-c36e4887ae8e)
![Screenshot_20240818-175116_RiMusic](https://github.com/user-attachments/assets/e9d9bec4-6488-422d-ae94-c3192092505a)
![Screenshot_20240818-175127_RiMusic](https://github.com/user-attachments/assets/5f884ebe-0c42-4eb2-8d8d-eb12a0b62f83)
![Screenshot_20240818-175131_RiMusic](https://github.com/user-attachments/assets/c4e64964-8ab2-4f8f-93c2-02a1f8292e8e)
![Screenshot_20240818-175134_RiMusic](https://github.com/user-attachments/assets/6fd083b3-e8d6-432a-afe1-9528d4f1b5c9)

**Comment by kris20030705** [comment]
Or maybe default theme from viMusic

**Comment by fast4x** [comment]
Ok I'll try to set your settings in ViMusic mode by default.

**Comment by kcryptonian** [comment]
Please do, his UI settings is cool. I like it.

**Comment by fast4x** [comment]
> Please do, his UI settings is cool. I like it.

Sure

**Comment by kris20030705** [comment]
> @kris20030705 can you export and send me your current settings for this?

RiMusic doesn't have ability to export setting..!
It only export favorited songs and playlist..

**Comment by kcryptonian** [comment]
I think it does. I've never had to test it before though.

**Comment by kcryptonian** [comment]
> > @kris20030705 can you export and send me your current settings for this?
> 
> RiMusic doesn't have ability to export setting..! It only export favorited songs and playlist..

I think it does. But I've never have to test it though.
![Screenshot_20240819_180607](https://github.com/user-attachments/assets/95b2bae3-7c48-4ae5-af49-747b29098093)

**Comment by kcryptonian** [comment]
> > @kris20030705 can you export and send me your current settings for this?
> 
> RiMusic doesn't have ability to export setting..! It only export favorited songs and playlist..

You're right.
@fast4x are we having settings export anytime soon?

**Comment by fast4x** [comment]
Implemented, available from version 0.6.49

**Comment by fast4x** [comment]
> are we having settings export anytime soon?

No

**Comment by twistios** [comment]
> are we having settings export anytime soon?

@kcryptonian
I already asked for this in a feature request (#2684). I checked myself how hard it is to implement it and currently it definitely is not easily doable.

**Comment by aneesh1122** [comment]
In this setting you are using the modern player with carousel enabled. Don't you think you should also keep the expanded player button in the action bar at the very least to have the carousel view?
