### ISSUE TITLE
Glitchy Playlist Arrangement

### ISSUE THREAD

**Issue by stickboiadah** [fast4x/RiMusic#3314]
### Steps to reproduce the bug

Go onto a playlist
Unlock it
Try to move a song around.

### Expected behavior

One song should move into its spot.

### Actual behavior

It glitches out either blanking out or move other songs around it.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/2d02d2db-305b-4a37-8cf8-480e3c707a0e

### RiMusic version

0.6.48

### Android version

Android 13

### Additional information

This issue has been occurring over several updates.

**Comment by twistios** [comment]
Also see #2344.

**Comment by stickboiadah** [comment]
I don't know what happened but now I can arrange playlists again, all the bugs are now gone. Thanks 🙏
