### ISSUE TITLE
Some alac codec songs are not playable

### ISSUE THREAD

**Issue by ShubhamPru** [fast4x/RiMusic#3316]
### Steps to reproduce the bug

Download this alac song- ( https://gofile.io/d/SgZu5Z )
And play in on device

### Expected behavior

All format song should be played 

### Actual behavior

Some alac songs are not producing sound though the player keeps on going

### RiMusic version

v0.6.48

### Android version

Android 13

**Comment by fast4x** [comment]
All default are supported.
