### ISSUE TITLE
Quejas 

### ISSUE THREAD

**Issue by ArmijosMj** [fast4x/RiMusic#3317]
### Description

Para mayor facilidad una interfaz en las músicas descargadas donde estén todas las músicas y ordenadas alfabéticamente y con la opción de aleatorio para apagar o prender y mayor facilidad en eliminar músicas en el partido de todo porque hay músicas qué no me gustan
![Screenshot_20240818_230552](https://github.com/user-attachments/assets/e5f52973-2323-4ae0-93bf-96127d47f498)
 y aun siguen saliendo allí y es molesto solucionalo por favor 

### Suggested Solution

Que las músicas estén ordenadas alfabéticamente y con su barra de letras para encontrar una músicas más rápido 

> qué se eliminen las músicas de el parado "todo" porque es molesto 

> qué exista el botón aleatorio par prender y apagar dentro de el reproductor 

> qué creen un wiget

> solunar el error que sale que no se reproduce la música por un error

**Comment by fast4x** [comment]
You can order as you want by holding down the arrow

**Comment by fast4x** [comment]
Implemented delete song from home songs , available from version 0.6.49
