### ISSUE TITLE
Unexpected interruptions in the last song on an album

### ISSUE THREAD

**Issue by XGhostRX** [fast4x/RiMusic#3318]
### Steps to reproduce the bug

Play the last song in an album

### Expected behavior

Normal playback

### Actual behavior

Which is sometimes interrupted and then switched to another song unexpectedly after a few seconds.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/24979bbf-1397-4f4d-9601-2a9e9848c132

### RiMusic version

0.6.48

### Android version

Android 10

### Additional information

It happens when I launch the app, after clearing the cache.
And you may have trouble storing the cache again, after clearing them.

**Comment by fast4x** [comment]
Not reproduced, maybe before you have started radio from album. This cause automatic adding related songs

**Comment by XGhostRX** [comment]
> No se reproduce, tal vez antes de que hayas comenzado la radio desde el álbum. Esto provoca que se agreguen automáticamente las canciones relacionadas.

Hmmm...

**Comment by XGhostRX** [comment]
I'll try to be clear.
The last song on an album is interrupted for a few seconds and then switched to another out of nowhere.
And that doesn't touch anything

https://github.com/user-attachments/assets/3d80dcfb-7a95-4f9b-a894-8354de525b1d

**Comment by fast4x** [comment]
Check if you have Medley enabled, long tap on pause player button like in the picture and set to 0 medley mode.
![Screenshot_2024-08-19-12-59-55-270_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/7332f9de-1e44-40f6-9ce9-b92f7877acb8)

**Comment by XGhostRX** [comment]
> Check if you have Medley enabled, long tap on pause player button like in the picture and set to 0 medley mode. ![Screenshot_2024-08-19-12-59-55-270_it.fast4x.rimusic-edit.jpg](https://private-user-images.githubusercontent.com/1484476/359078617-7332f9de-1e44-40f6-9ce9-b92f7877acb8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjY3OTcsIm5iZiI6MTcyNDA2NjQ5NywicGF0aCI6Ii8xNDg0NDc2LzM1OTA3ODYxNy03MzMyZjlkZS0xZTQ0LTQwZjYtOWNlOS1iOTJmNzg3N2FjYjguanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMTEyMTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ3YjdjOGY1ODQxNGI4NWQ5NjdmODE3MTE1Y2ZjMTVjMDc5YThlMWExZjViNTQ1MzRlNjdkMjI2NTgxZTA5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uKuJiJO8PDWKQ5adSMoHeky5_jHqk8rXlzTQYiAzJX8)

I was already at 0
And yet, it's the same

https://github.com/user-attachments/assets/b0590b39-d0f3-4429-b94b-e0ddb814c58c

I also think I did more research
That happens when I clean the cache

**Comment by fast4x** [comment]
It is normal for the cache to be cleared by the system cleaner.

Try set cache location private in Data settings.
