### ISSUE TITLE
Ui Bugs

### ISSUE THREAD

**Issue by RABINGG** [fast4x/RiMusic#3320]
### Steps to reproduce the bug

NA

### Expected behavior

NA

### Actual behavior

1. Bring back cached section in songs which is removed in recent update.
2. Why song change gesture is vertical swipe in player. It should be horizontal swipe right.
3. I am experiencing so much crashes recently.  Interacting/clearing the media player in notification panel, starting radio. Sometimes without reasons.
4. The new modern queue is unclear with some of the pallete in dynamic theme.
5. Provide a option to check for updates manually. The implementation only check when it starts and can't check or update the app without restarting. 

### Logs

2024-08-19T18:39:25.804:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{4b386a5 u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-08-19T18:40:02.516:	java.lang.IllegalStateException
	 n2.b.h(SourceFile:6) 
	 r2.x.l(SourceFile:7) 
	 I6.U.v(SourceFile:105) 
	 I6.U.e(SourceFile:22) 
	 c5.b.v(SourceFile:70) 
	 c5.b.e(SourceFile:28) 
	 A7.w.v(SourceFile:249) 
	 d7.a.k(SourceFile:9) 
	 w7.J.run(SourceFile:113) 
	 J0.b0.h0(SourceFile:7) 
	 J0.a0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

### RiMusic version

0.6.48

### Android version

Android 14

### Additional information

Crash logs for crashing during starting radio is attached

**Comment by aneesh1122** [comment]
2) this is why it's vertical. Horizontal would not make sense here. Right? 

https://github.com/user-attachments/assets/07ff3f77-9baf-4e45-b884-b68d8f1acb6f

4) you have to pay some examples so that I can improve it

**Comment by RABINGG** [comment]
@aneesh1122 
2. Thanks for the clarification that makes sense but this doesn't works when expanded lyrics is enabled.

**Comment by aneesh1122** [comment]
> @aneesh1122 
> 2. Thanks for the clarification that makes sense but this doesn't works when expanded lyrics is enabled.

Yeah I have it disabled. I always have expanded player enabled so I don't really need the expanded lyrics toggle.

**Comment by fast4x** [comment]
1. Why bring back? Cached was included in downloaded section...

**Comment by fast4x** [comment]
3. fixed available from version 0.6.49

**Comment by fast4x** [comment]
Implemented manual check update available from version 0.6.49

**Comment by RABINGG** [comment]
> 2. this is why it's vertical. Horizontal would not make sense here. Right?
> 
>  Screenrecorder-2024-08-19-18-58-28-577.mp4 
> 4. you have to give some examples so that I can improve it

PFA
![Screenshot_20240820_112055](https://github.com/user-attachments/assets/00001f9a-1eb7-414a-b853-f06bae52651a)

**Comment by RABINGG** [comment]
> > > 2. this is why it's vertical. Horizontal would not make sense here. Right?
> > > 
> > > Screenrecorder-2024-08-19-18-58-28-577.mp4
> > > 4. you have to give some examples so that I can improve it
> > 
> > 
> > @aneesh1122
> > 4. PFA
> > ![Screenshot_20240820_112055](https://private-user-images.githubusercontent.com/100079543/360827704-00001f9a-1eb7-414a-b853-f06bae52651a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTI2OTYsIm5iZiI6MTcyNDQxMjM5NiwicGF0aCI6Ii8xMDAwNzk1NDMvMzYwODI3NzA0LTAwMDAxZjlhLTFlYjctNDE0YS1iODUzLWYwNmJhZTUyNjUxYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxMTI2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODAyZWY5MjJmZmYxZDE5ZWRkYmY5NjhjZGM5NmJkZjNmYTdmMmZkZjRkODEzMzBmMmY4NzFjODFlMDBkZDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XCgSKpskfidM-boeUXxfdIZVaDXwCRIS9AK7DeXt9ns)
> > ![Screenshot_20240823_152312](https://private-user-images.githubusercontent.com/100079543/360884499-4626af32-e5a6-4dee-baaa-90e92a30baf3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTI2OTYsIm5iZiI6MTcyNDQxMjM5NiwicGF0aCI6Ii8xMDAwNzk1NDMvMzYwODg0NDk5LTQ2MjZhZjMyLWU1YTYtNGRlZS1iYWFhLTkwZTkyYTMwYmFmMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxMTI2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWU5YWY1NGQ2OGE0ZDQxMzJjNDA4MGVkYmU1OTgyNTY4ZWU2NzU4OTk3Y2NiNGM2MjBmOWExODdjZTM5OWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0NhKDnIf5CEAssA9OrryDYsRPPXmuBmN9dl68_9B7hg)
> 
> Have you tried the dark theme?

@aneesh1122
Better in dark mode.

**Comment by aneesh1122** [comment]
> > > > 2. this is why it's vertical. Horizontal would not make sense here. Right?
> > > > 
> > > > Screenrecorder-2024-08-19-18-58-28-577.mp4
> > > > 4. you have to give some examples so that I can improve it
> > > 
> > > 
> > > @aneesh1122
> > > 4. PFA
> > > ![Screenshot_20240820_112055](https://private-user-images.githubusercontent.com/100079543/360827704-00001f9a-1eb7-414a-b853-f06bae52651a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTI2OTYsIm5iZiI6MTcyNDQxMjM5NiwicGF0aCI6Ii8xMDAwNzk1NDMvMzYwODI3NzA0LTAwMDAxZjlhLTFlYjctNDE0YS1iODUzLWYwNmJhZTUyNjUxYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxMTI2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODAyZWY5MjJmZmYxZDE5ZWRkYmY5NjhjZGM5NmJkZjNmYTdmMmZkZjRkODEzMzBmMmY4NzFjODFlMDBkZDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XCgSKpskfidM-boeUXxfdIZVaDXwCRIS9AK7DeXt9ns)
> > > ![Screenshot_20240823_152312](https://private-user-images.githubusercontent.com/100079543/360884499-4626af32-e5a6-4dee-baaa-90e92a30baf3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTI2OTYsIm5iZiI6MTcyNDQxMjM5NiwicGF0aCI6Ii8xMDAwNzk1NDMvMzYwODg0NDk5LTQ2MjZhZjMyLWU1YTYtNGRlZS1iYWFhLTkwZTkyYTMwYmFmMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxMTI2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWU5YWY1NGQ2OGE0ZDQxMzJjNDA4MGVkYmU1OTgyNTY4ZWU2NzU4OTk3Y2NiNGM2MjBmOWExODdjZTM5OWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0NhKDnIf5CEAssA9OrryDYsRPPXmuBmN9dl68_9B7hg)
> > 
> > Have you tried the dark theme?
> 
> @aneesh1122
> Better in dark mode. 

Use the dark mode. It's also much easier for your eyes.

**Comment by RABINGG** [comment]
> > > > > 2. this is why it's vertical. Horizontal would not make sense here. Right?
> > > > > 
> > > > > Screenrecorder-2024-08-19-18-58-28-577.mp4
> > > > > 4. you have to give some examples so that I can improve it
> > > > 
> > > > 
> > > > @aneesh1122
> > > > 4. PFA
> > > > ![Screenshot_20240820_112055](https://private-user-images.githubusercontent.com/100079543/360827704-00001f9a-1eb7-414a-b853-f06bae52651a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTI2OTYsIm5iZiI6MTcyNDQxMjM5NiwicGF0aCI6Ii8xMDAwNzk1NDMvMzYwODI3NzA0LTAwMDAxZjlhLTFlYjctNDE0YS1iODUzLWYwNmJhZTUyNjUxYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxMTI2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODAyZWY5MjJmZmYxZDE5ZWRkYmY5NjhjZGM5NmJkZjNmYTdmMmZkZjRkODEzMzBmMmY4NzFjODFlMDBkZDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XCgSKpskfidM-boeUXxfdIZVaDXwCRIS9AK7DeXt9ns)
> > > > ![Screenshot_20240823_152312](https://private-user-images.githubusercontent.com/100079543/360884499-4626af32-e5a6-4dee-baaa-90e92a30baf3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTI2OTYsIm5iZiI6MTcyNDQxMjM5NiwicGF0aCI6Ii8xMDAwNzk1NDMvMzYwODg0NDk5LTQ2MjZhZjMyLWU1YTYtNGRlZS1iYWFhLTkwZTkyYTMwYmFmMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxMTI2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWU5YWY1NGQ2OGE0ZDQxMzJjNDA4MGVkYmU1OTgyNTY4ZWU2NzU4OTk3Y2NiNGM2MjBmOWExODdjZTM5OWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0NhKDnIf5CEAssA9OrryDYsRPPXmuBmN9dl68_9B7hg)
> > > 
> > > 
> > > Have you tried the dark theme?
> > 
> > 
> > @aneesh1122
> > Better in dark mode.
> 
> Use the dark mode. It's also much easier for your eyes.

That seems to be a excuse instead of fixing.
