### ISSUE TITLE
[Feature]: RiMusic community

### ISSUE THREAD

**Issue by kcryptonian** [fast4x/RiMusic#3321]
### Description

I want you to create an online community for RiMusic either on Discord or Telegram or both, where fans & users of RiMusic can interact and even help each other in navigating the intricacies of the app. 
I feel like RiMusic has grown a lot and it's only logical there's a community for it. You can even be posting the changelogs of new version releases over there. Members can exchange RiMusic settings too.
I feel many people would also want something like this. In fact some noobs question can be answered by other members without the noob having to come and open an issue here in GitHub 

### Suggested Solution

Create a Discord server or telegram group chat with channel too, then add a link for joining in RiMusic app settings. Make a enthusiastic, active and helpful person (s) as admin in case you'll be too busy man it yourself alone.

**Comment by privacyfreak84** [comment]
Or on Lemmy

**Comment by fast4x** [comment]
> Or on Lemmy

This?
https://lemmy.ml/

**Comment by fast4x** [comment]
Ok, between Discord, Telegram which one do you think can reach more people? Maybe Telegram?

**Comment by twistios** [comment]
For lemmy, [this](https://join-lemmy.org/) seems to be the Website of the project. I think that it is part of the Fediverse "platform". There seem to be many different instances for example also https://lemmy.world/. The Website type is something like reddit.

**Comment by twistios** [comment]
[This](https://join-lemmy.org/instances) seems to be the place to find all servers.

**Comment by dAtA-TRoN** [comment]
What's wrong with Reddit?

**Comment by aneesh1122** [comment]
> Ok, between Discord, Telegram which one do you think can reach more people? Maybe Telegram?

Discord

**Comment by fast4x** [comment]
> What's wrong with Reddit?

Can try in the future

**Comment by fast4x** [comment]
I'm creating group in Telegram, after I'll look into Discord...

**Comment by fast4x** [comment]
Who should be an administrator? :)

**Comment by fast4x** [comment]
Telegram group https://t.me/rimusic_app

**Comment by eddisch** [comment]
I could be a admin, just saying

**Comment by fast4x** [comment]
> I could be a admin, just saying

You know very well RiMusic and all features?

**Comment by aneesh1122** [comment]
> > I could be a admin, just saying
> 
> You know very well RiMusic and all features?
> 
> 

And the most important thing is to be active. I don't know if I'll be very active that's why I did not volunteer.

**Comment by eddisch** [comment]
> > I could be a admin, just saying
> 
> You know very well RiMusic and all features?

Well i know features but i dont know how to code rlly so ehh

**Comment by fast4x** [comment]
> > > I could be a admin, just saying
> > 
> > You know very well RiMusic and all features?
> 
> Well i know features but i dont know how to code rlly so ehh

It's ok, You don’t have to be a programmer who knows the code. You just need to be prepared on the topics and give suggestions on how to solve or support on problems using the app. If there is no solution you can ask the user to create a ticket on GitHub to fix the bug .

**Comment by eddisch** [comment]
well i know how to do that

> > > > I could be a admin, just saying
> > > 
> > > 
> > > You know very well RiMusic and all features?
> > 
> > 
> > Well i know features but i dont know how to code rlly so ehh
> 
> It's ok, You don’t have to be a programmer who knows the code. You just need to be prepared on the topics and give suggestions on how to solve or support on problems using the app. If there is no solution you can ask the user to create a ticket on GitHub to fix the bug .

**Comment by fast4x** [comment]
Great, your account name on Telegram?

**Comment by kcryptonian** [comment]
> Ok, between Discord, Telegram which one do you think can reach more people? Maybe Telegram?

Telegram, IMO.

**Comment by fast4x** [comment]
> > Ok, between Discord, Telegram which one do you think can reach more people? Maybe Telegram?
> 
> Telegram, IMO.

ok just active

**Comment by eddisch** [comment]
@Eddisch

**Comment by fast4x** [comment]
https://www.reddit.com/r/RiMusicApp/ reddit ready

**Comment by aneesh1122** [comment]
> https://www.reddit.com/r/RiMusicApp/ reddit ready

add website,github and telegram links in reddit

**Comment by fast4x** [comment]
I've tried but post was  deleted by reddit filter... I'll check as it work

**Comment by aneesh1122** [comment]
> I've tried but post was  deleted by reddit filter... I'll check as it work

That's strange. You should be able to post whatever link you want. I'm not much experienced with reddit though.

**Comment by TheBy2007** [comment]
> Who wants to be an administrator? :)

can i be? i know not that well the features but i know more than half so..

**Comment by TheBy2007** [comment]
> > > > I could be a admin, just saying
> > > 
> > > 
> > > You know very well RiMusic and all features?
> > 
> > 
> > Well i know features but i dont know how to code rlly so ehh
> 
> It's ok, You don’t have to be a programmer who knows the code. You just need to be prepared on the topics and give suggestions on how to solve or support on problems using the app. If there is no solution you can ask the user to create a ticket on GitHub to fix the bug .

ohh i know that

> I'm creating group in Telegram, after I'll look into Discord...

can i help you on the discord group?

**Comment by twistios** [comment]
@TheBy2007 Discord group exists now https://discord.gg/y7NJwdwXEM
