### ISSUE TITLE
[Refactor]: Remove commented code.

### ISSUE THREAD

**Issue by lucaslrt** [fast4x/RiMusic#3325]
### Description

Hello there! I've forked the project to contribute a little, then I realized that there's a bunch of commented code. Is it okay to remove only the ones that are not logging?

### Suggested Solution

Remove non-log comment codes.

**Comment by fast4x** [comment]
Hello thanks, for now it is advisable to keep everything because the code is constantly changing and it is faster to restore or compare pieces of code.
