### ISSUE TITLE
Crash when accessing Miscellaneous settings

### ISSUE THREAD

**Issue by zalatx** [fast4x/RiMusic#3327]
### Steps to reproduce the bug

Open the app
Tap on Menu at the top right hand corner
Tap on settings
Tap on the Miscellaneous tab at the bottom.

### Expected behavior

Miscellaneous options are shown (among them, activate the Android auto support)

### Actual behavior

App crashes

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/3190cd27-8e91-4663-a8d9-283f99576dc8

### RiMusic version

0.6.48

### Android version

Android 14 One UI 6.1

**Comment by fast4x** [comment]
Try to click on App info, maybe contain log to paste here.

**Comment by zalatx** [comment]
Hi, I reinstalled 6.46 and it worked fine, I activated AA support and used it for few hours. Now I have updated to 6.48 and I do not find the issue.
Sorry this was before reading hot to retrieve the log.

**Comment by fast4x** [comment]
No problem, you are welcome
