### ISSUE TITLE
[Feature]: Add edit Author inside "Update Title"

### ISSUE THREAD

**Issue by lucaslrt** [fast4x/RiMusic#3331]
### Description

Some musics don't have author's name.

### Suggested Solution

I want to create a feature that the user can also edit the author inside the "Update Title" option.
![WhatsApp Image 2024-08-20 at 14 12 52](https://github.com/user-attachments/assets/2b2c9fb5-614b-4738-a875-cb35ce899765)
![WhatsApp Image 2024-08-20 at 14 18 06](https://github.com/user-attachments/assets/589ca512-f6c3-4072-9974-4da039574b75)

**Comment by fast4x** [comment]
Hi, it's just implemented and available from version 0.6.49
