### ISSUE TITLE
Lyrics save

### ISSUE THREAD

**Issue by HyterX** [fast4x/RiMusic#3332]
### Description

Make lyrics savable so we can use them offline

### Suggested Solution

Make lyrics in cache

**Comment by fast4x** [comment]
Lyrics is saved in database, what you mean?

**Comment by fast4x** [comment]
Not make sense because require space in database...

**Comment by twistios** [comment]
Is it not possible because of too large size or could this be optional?

**Comment by fast4x** [comment]
Automatic download is never a good thing because it takes up space almost without user control
