### ISSUE TITLE
[Feature]: Not artist page

### ISSUE THREAD

**Issue by Addriann1577** [fast4x/RiMusic#3335]
### Description

After using the app for a while I just can say it is nearly perfect, but I found out about a feauture which I thought it would already being  implemented.

The thing is, creating playlist is such a dull and hard work to do, so to make it easier I would suggest to add a simple menu to with some useful features every time you long press a single. I also found out that if you are in an artist discography, add a song, and head back to the discography menu, it would just send you back to the artist main page).

### Suggested Solution

it would be cool if you could just  go back to the singles and albums menu to the very song you opened up (it had been so helpful to not lose track). Finally I would suggest to update the playlist marker right before you add it ( because it is so anoying to add a song, go back and don't se the green icon, so confusing

**Comment by faustaahmad** [comment]
Sorry, but your wording are confusing
Perhaps this are what you meant (just wanted to make it more understandable)
### Feature Request:
・Long press menu on Artist's Album and Single

### Bugs?
・Artist (overview) → Album/Single → go to one of 'em → Press back button
**Current behaviour:** redirected to Artist (overview)
**Desired behaviour:** redirected to Artist (Album/Single)

・Playlist indicator doesnt get updated directly after adding songs to playlist
**Current behaviour:** need to refresh before playlist marker appear (scroll up/down list, go back, ...)
**Desired behaviour:** Playlist indicator show up after songs added to playlist
