### ISSUE TITLE
No cortar la reproducción de la música 

### ISSUE THREAD

**Issue by Noeliiarp26** [fast4x/RiMusic#3338]
### Description

Me gustaría que cuando me saliera de la app y la cerrará no se me borrara la canción que estaba escuchando y tener que escuchar otra distinta al darle al modo aleatorio 

### Suggested Solution

B

### Alternatives

D

### Additional Context

S

**Comment by fast4x** [comment]
Must enable permanent queue in ui settings

**Comment by Noeliiarp26** [comment]
Thanks🙏🏻🙏🏻
