### ISSUE TITLE
En la pantalla de bloqueo 

### ISSUE THREAD

**Issue by Noeliiarp26** [fast4x/RiMusic#3339]
### Steps to reproduce the bug

Al reproducir una canción hay veces que en la pantalla de bloqueo no sale que estás escuchando la música.

### Expected behavior

H

### Actual behavior

D

### Screenshots/Screen recordings

L

### Logs

S

### RiMusic version

S

### Android version

S

### Additional information

S

**Comment by fast4x** [comment]
Not reproduced sorry
