### ISSUE TITLE
Özellik  - Scrolling similar songs

### ISSUE THREAD

**Issue by cngzkar11** [fast4x/RiMusic#334]
### Description

1 _ Herhangi bir şarkı arayıp açtığımızda şarkı bittiğinde benzer şarkıları çalmaya devam etsin. (sonsuz akış) spotify'daki gibi. 
~~2 _ Kullanıcı girişi yapabilmeliyiz~~.

### Suggested Solution

1 _ Herhangi bir şarkı arayıp açtığımızda şarkı bittiğinde benzer şarkıları çalmaya devam etsin. (sonsuz akış) spotify'daki gibi. 
~~2 _ Kullanıcı girişi yapabilmeliyiz.~~

**Comment by fast4x** [comment]
Kullanıcı’nın girişi şu anda amaçlanan bir işlev değildir.

**Comment by fast4x** [comment]
Hello, now you can listen to similar songs like this:

1. Set Tips based on last song played on Quick Pics settings
2. Click on the last song played, (the first in Quick Pics) the next ones are based on that.
