### ISSUE TITLE
Add option to import music from Dezzer 

### ISSUE THREAD

**Issue by kdpzu** [fast4x/RiMusic#3346]
### Description

Dezzer stopped being free about a year ago, it would be nice if they added the option to import your songs from Dezzer to RiMusic , Many people used it and it might be a useful option. 

### Suggested Solution

A good solution would be to add an option where you log into your Dezzer account and your songs will be transferred to the app. 

### Alternatives

In case it is not possible due to the difference in platforms, the application should search for the songs from the "videos" service of the RiMusic app.

### Additional Context

That's my suggestion, I hope it can be of some use.

**Comment by fast4x** [comment]
You must transfer your playlists to YouTube Music and from it can share and import in RiMusic.
