### ISSUE TITLE
Grid view in playlists screen

### ISSUE THREAD

**Issue by deepu2** [fast4x/RiMusic#3349]
### Description

The grid view looks convoluted and messy, I would like a list view. I've searched the issues and the settings but couldn't find this specific option, point me in the direction if there is one. Thanks for the application :P

### Suggested Solution

List view in the playlists screen without scrolling text.

### Alternatives

I've tried using different thumbnail sizes.

**Comment by fast4x** [comment]
Hi, albums, artists and playlists are all in grid mode.

**Comment by fast4x** [comment]
Is not a priority
