### ISSUE TITLE
No me permite reproducir música 

### ISSUE THREAD

**Issue by efrainve** [fast4x/RiMusic#3353]
### Steps to reproduce the bug

Seleccione la canción y dice que no se puede reproducir 

### Expected behavior

Lo ideal era que se reproduzca la canciones normalmente como lo estaba haciendo 

### Actual behavior

Me sale una advertencia de que no coincide el vídeo con la solicitud 

### Screenshots/Screen recordings

![Screenshot_2024-08-22-14-10-53-496_it fast4x rimusic](https://github.com/user-attachments/assets/a70dd00f-b5b0-455a-a0a1-86db77bb9af7)
![Screenshot_2024-08-22-14-10-53-496_it fast4x rimusic](https://github.com/user-attachments/assets/2ee80573-da88-459d-91dd-094be5d4f6a6)

### RiMusic version

0.6.48

### Android version

Android 14

**Comment by fast4x** [comment]
Where do you live?

**Comment by efrainve** [comment]
Venezuela! Ya se arregló la falla

**Comment by efrainve** [comment]
Persiste la falla pero solo con algunas canciones, las cuales no permite reproducir

**Comment by efrainve** [comment]
Por favor, si me pueden ayudar a solucionar dicho error

**Comment by fast4x** [comment]
It does not depend on the app but on the availability of the audio song. When your problem happens it means that there are no audio versions but only video. Currently, however, the app does not support videos.
