### ISSUE TITLE
songs always repeat 

### ISSUE THREAD

**Issue by Souuz4** [fast4x/RiMusic#3355]
### Steps to reproduce the bug

put on the music and after that turn off the device (cell phone) the player will automatically play only 2 songs, always repeating them 

### Expected behavior

the songs should be changing 

### Actual behavior

Não entendi a pergunta 

### RiMusic version

0.6.48

### Android version

Android 13

**Comment by aneesh1122** [comment]
Install the latest custom version

**Comment by fast4x** [comment]
It's fixed and available from version 0.6.49

**Comment by ThePhoDit** [comment]
I am experiencing the same behavior in v0.6.49.2. Songs in playlist play normally but then at a random point it starts to loop two specific songs. Does not happen with the app in foreground (or at least it didn't happen to me).

**Comment by Souuz4** [comment]
yes, and it's still happening to me in version 0.6.52, even activating the supreme services that drains the battery a lot doesn't help at all
