### ISSUE TITLE
songs changed by themselves without stopping 

### ISSUE THREAD

**Issue by Souuz4** [fast4x/RiMusic#3356]
### Steps to reproduce the bug

put the music and leave the application in the background, after that in the notification bar activate the random selection version, in the 1st song that passes it will work normally, from the second one the application keeps changing the songs without stopping 

### Expected behavior

I should just change the music, but it keeps choosing music endlessly 

### Actual behavior

music exchange 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/2a9bacd1-273b-49ca-af81-794b13593a7b

### RiMusic version

0.6.48

### Android version

Android 13

### Additional information

Samsung a14 5g, brasil

**Comment by AquamarineDreams** [comment]
Same issue here

**Comment by AquamarineDreams** [comment]
@Souuz4 Achei o problema
![Screenshot_2024-08-22-20-39-47-379_org mozilla firefox](https://github.com/user-attachments/assets/ce157aae-10a8-482f-b77f-f0bb274c0e23)
![Screenshot_2024-08-22-20-40-50-539_it fast4x rimusic-edit](https://github.com/user-attachments/assets/88bc987f-1967-47fd-9de6-4b361b98d1e2)

**Comment by Souuz4** [comment]
> @Souuz4 I found the problem > ![Screenshot_2024-08-22-20-39-47-379_org mozilla firefox](https://github.com/user-attachments/assets/ce157aae-10a8-482f-b77f-f0bb274c0e23) > ![Screenshot_2024-08-22-20-40-50-539_it fast4x rimusic-edit](https://github.com/user-attachments/assets/88bc987f-1967-47fd-9de6-4b361b98d1e2)

 Thanks, I'll check it out

**Comment by fast4x** [comment]
Slider bug it's fixed and available from version 0.6.49
