### ISSUE TITLE
Can't play 

### ISSUE THREAD

**Issue by tangyuemo** [fast4x/RiMusic#3360]
### Steps to reproduce the bug

play

### Expected behavior

Never appeared before

### Actual behavior

It started appearing yesterday

### Screenshots/Screen recordings

![Screenshot_2024-08-23-15-50-31-275_it fast4x rimusic](https://github.com/user-attachments/assets/da9fe20b-5231-4d66-8f30-9c932b3f849e)

### RiMusic version

0.6.48

### Android version

ane14

**Comment by tangyuemo** [comment]
![Screenshot_2024-08-23-15-50-24-815_it fast4x rimusic](https://github.com/user-attachments/assets/fe03c9f0-547f-42cb-8612-f71a30d42103)

**Comment by aneesh1122** [comment]
Try without VPN
