### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#3366]
### Steps to reproduce the bug

I'm sorry, but I have no idea
・Was playing this guy songs when standby/idle
> https://music.youtube.com/channel/UC2WK1yUBAX3-Qu3wwxJAP-Q
> Loop queue on, Loop song off, shuffle on

・Somehow a song "YUI - Again" managed to get through the queue

・Before/when it get played, RiMusic crash after unknown duration passed
・I was wondering why the stop in the middle, so I check my phone
・Replay that song/queue, then same thing happens again
> If I didnt play the song/queue, it doesnt crash

・Try log the crash
・Delete "YUI - Again" from the queue
・Playing normally for now (who knows when it'll crash)
・Report this issue

### Expected behavior

Shouldnt crash

### Actual behavior

Crash randomly

### Logs

```
2024-08-23T23:17:06.847:	android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY[787])
	 android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method) 
	 android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:1217) 
	 android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790) 
	 android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88) 
	 v3.i.b(SourceFile:3) 
	 p3.i.o(SourceFile:8) 
	 h6.p.r(SourceFile:11) 
	 E6.A.a(SourceFile:97) 
	 J0.u.run(SourceFile:24) 
	 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
	 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
	 java.lang.Thread.run(Thread.java:923) 
```

### RiMusic version

0.6.48 https://github.com/fast4x/RiMusic/commit/05ab7cb463fa6253c73e1d061a606c6f6cfbbf21

### Android version

Android 11

**Comment by fast4x** [comment]
I've played songs of this artist without issue. Maybe you have a problem in database.
