### ISSUE TITLE
A good chunk of albums/releases fail to load

### ISSUE THREAD

**Issue by KeknanXD** [fast4x/RiMusic#3367]
### Steps to reproduce the bug

1. Click on a release

### Expected behavior

The release shows up as well as the details and track list

### Actual behavior

Everything fails to load
Alternatively, releases you saved are still able to display the track list, but the rest fails to show up

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/7c4bbc55-8c9b-49d3-a6e3-b5e481e8404c

![Screenshot_20240823_195132](https://github.com/user-attachments/assets/41e4988b-fe58-47af-ae1b-18d2ebb26add)

https://github.com/user-attachments/assets/abf110eb-c290-4887-97bd-eb2a40cf0707

### RiMusic version

0.6.48

### Android version

Android 12

### Additional information

Weirdly enough, this does not apply to every release. Some work as always. Here's an example:

https://github.com/user-attachments/assets/3031f9a5-85bb-4f6a-8257-4e4de4833d6c

**Comment by Cold1203** [comment]
Try a VPN, I had this issue yesterday and now with a VPN it's functioning normally

**Comment by fast4x** [comment]
After try vpn, enable debug and after a couple of time paste here the log.
