### ISSUE TITLE
Thumbnail size option is broken on the "Essential" player type

### ISSUE THREAD

**Issue by FixItKit** [fast4x/RiMusic#3368]
### Steps to reproduce the bug

1. Set the player type to "Essential" (it is set to "Essential" by default).
2. Open any song.

### Expected behavior

The thumbnail size should match what has been selected in the settings.

### Actual behavior

The thumbnail size is the same regardless of the selected option.

### RiMusic version

0.6.49

### Android version

Android 13

**Comment by fast4x** [comment]
Add a screenshot please

**Comment by fast4x** [comment]
and what's screenshot size?

**Comment by stickboiadah** [comment]
I use Biggest size usually but even for me it's bigger than usual.

**Comment by aneesh1122** [comment]
Are you sure you're changing the "Thumbnail Size" and not the "Size of Carousel"?

**Comment by drago-bit** [comment]
I can confirm that, this bug exists.

Like whatever size we selected in the settings it doesn't reflect in the actual player, and size stays as the 'Biggest'.

**Comment by aneesh1122** [comment]
This bug is only with the essential player.

**Comment by fast4x** [comment]
Fixed, available from next version

**Comment by fast4x** [comment]
Try latest version
