### ISSUE TITLE
Albums not loading

### ISSUE THREAD

**Issue by spencerharmon** [fast4x/RiMusic#3369]
### Steps to reproduce the bug

Navigate to an album not previously loaded and find that it does not load. Albums already loaded in the past still load but album art no longer works.

![Uploading Screenshot_20240823-153318.png…]()

### Expected behavior

Songs and album art should load. 

### Actual behavior

Cannot load new albums. 

### RiMusic version

v0.6.48

### Android version

Android 11

**Comment by JeePopuwu** [comment]
X2

**Comment by A3the4** [comment]
same problem here

**Comment by fast4x** [comment]
Use latest version please

**Comment by Cold1203** [comment]
Maybe try erasing cache (not data), and route the app with a VPN

**Comment by spencerharmon** [comment]
@fast4x I thought this is the latest version in f-droid. I updated today. I can try the .49 version when I'm not traveling unless you can push the new release. 

@Cold1203 thanks for the tip. I cleared cache, but no luck. I'm not using a VPN at the moment but I can try that. Is there a geo-locked feature that affects this that you're aware of?

**Comment by Cold1203** [comment]
@spencerharmon I'm no developer myself, but the official developer told me in a issue that I had pretty similar to yours that maybe there is some problem whit your geographic location and the server or provider of the music, (This is not related to the app itself) I had this one song (STFU - Pink Guy) that said "Not available in this region" so maybe that's the issue. But with a VPN it plays normally

**Comment by fast4x** [comment]
FDroid have different time to publish new version, normally one week after new release.

**Comment by JeePopuwu** [comment]
I am using the newest version and it is the one where the bug occurs
![Screenshot_2024-08-23-18-41-24-380_it fast4x rimusic](https://github.com/user-attachments/assets/e70a0c87-15ab-4e46-be87-76a5e1869824)
![Screenshot_2024-08-23-18-41-35-515_com miui securitycenter](https://github.com/user-attachments/assets/80c1648c-e9f8-41fd-b689-c0aeb3e660ef)

**Comment by Keepcallin00** [comment]
Same here, Android 11 too

**Comment by NikunjKhangwal** [comment]
#2064 probably related

**Comment by fast4x** [comment]
Ok I'll check it

**Comment by spencerharmon** [comment]
@fast4x many thanks for taking a look!

**Comment by spencerharmon** [comment]
Wanted to update that I installed v0.6.49.2 from GitHub apk and this is fixed. Thanks again!
