### ISSUE TITLE
RiMusic's launcher shortcuts don't work

### ISSUE THREAD

**Issue by FixItKit** [fast4x/RiMusic#3370]
### Steps to reproduce the bug

I tried opening RiMusic's shortcuts in my launcher.

### Expected behavior

The shortcut should work and open the selected part of RiMusic.

### Actual behavior

The shortcuts don't work.

### RiMusic version

0.6.49

### Android version

Android 13

**Comment by fast4x** [comment]
Yes confirmed

**Comment by fast4x** [comment]
Fixed, available from version 0.6.50
