### ISSUE TITLE
Is there a way where i can put a file on my phine into one of my playlists

### ISSUE THREAD

**Issue by Julian1535** [fast4x/RiMusic#3373]
### Description

.

### Suggested Solution

.

### Alternatives

.

**Comment by fast4x** [comment]
Explain better please

**Comment by faustaahmad** [comment]
Hold the songs (if exist) → Add to playlist

**Comment by Julian1535** [comment]
> Explain better please

Like i bought the deluxe days before rodeo on my phone so its a file and am i able to import the file into rimusic so those files can be on my playlist

**Comment by fast4x** [comment]
I don't think, you can add album from search.
