### ISSUE TITLE
Automatic song download

### ISSUE THREAD

**Issue by Plawro** [fast4x/RiMusic#3374]
### Steps to reproduce the bug

1. Play a song
2. Song automatically downloads

### Expected behavior

In settings, tick "Always download song on play", if not turned on, download the song only when I click the download button

### Actual behavior

Song automatically downloads when played

### RiMusic version

0.6.49

### Android version

Android 13

**Comment by fast4x** [comment]
Song is cached automatically if you listen it, alternatively can download it manually
