### ISSUE TITLE
Album art and title disappears when opening them

### ISSUE THREAD

**Issue by AstroLightz** [fast4x/RiMusic#3375]
### Steps to reproduce the bug

1. Go to an album you saved
2. Open it

### Expected behavior

The album title and art should display

### Actual behavior

While still on the page:
- Album art disappears

After you leave the page and go back the albums menu:
- album art, title, and year disappear

### Saved Album
![Screenshot_2024-08-23-22-42-57-09_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/f10b6d87-ed0e-4ae0-9391-a699324b228d)
### Infinite Loading
![Screenshot_2024-08-23-22-48-38-11_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/f71d8fe7-4960-47cd-aa2b-ce201fb08dcf)

### RiMusic version

v0.6.49

### Android version

Android 14

### Additional information

Additionally, albums not saved get stuck in an infinite loading cycle. (They don't load).

**Comment by hle-cer** [comment]
same here

**Comment by fast4x** [comment]
Fixed, available from next version available soon today.
