### ISSUE TITLE
Una mejor interfaz 

### ISSUE THREAD

**Issue by Victor332lop** [fast4x/RiMusic#3376]
### Description

Que venga por defecto la interfaz que yo tengo así llamará la atención de las personas y se verá más bonito :3

### Suggested Solution

Como en las siguientes fotos quiero que se vea ya que es las llamativo y atraerá el interés de la gente 

### Alternatives

:3

### Additional Context

![Screenshot_20240824-002515](https://github.com/user-attachments/assets/c6576b6b-1055-4d6b-bfbc-15e323caae71)
![Screenshot_20240824-002539](https://github.com/user-attachments/assets/47a9e046-584a-46e3-ae10-506f927ca73c)

**Comment by fast4x** [comment]
You can configure as you want, check in settings player appearance
