### ISSUE TITLE
Can't load full catalog

### ISSUE THREAD

**Issue by Keepcallin00** [fast4x/RiMusic#3377]
### Steps to reproduce the bug

1. Go to Larry June
2. Scroll through albums
3. Click on "The Great Escape" or "2 P'z on a Pod"
4. App is not loading the album 

### Expected behavior

The app should be able to load every album from any artist

### Actual behavior

The app can't load every album, try with any random artist and some albums load some others can't load 

![Screenshot_20240824-003122](https://github.com/user-attachments/assets/9e14846d-d910-41fa-a9f2-0d1491cf3851)

### RiMusic version

0.6.49

### Android version

Android 11

**Comment by fast4x** [comment]
Fixed, available from next version available soon today.

**Comment by Keepcallin00** [comment]
Thank you so much 🤩🙌🏻
