### ISSUE TITLE
Funcionalidad de achicar o agrandar miniatura, tamaño de la miniatura 

### ISSUE THREAD

**Issue by JuanConde27** [fast4x/RiMusic#3378]
### Steps to reproduce the bug

Configuración 
Apariencia 
Achicar miniatura al pausar 
Escoger el tamaño de la miniatura 

### Expected behavior

Debería de funcionar correctamente las dos funcionalidades 

### Actual behavior

Desde la última versión la función de achicar o agrandar miniatura al pausar dejo de funcionar, funcionalidad de escoger el tamaño de la miniatura en el reproductor también dejo de funcionar, se queda en tamaño gigante fijo 

### RiMusic version

Última versión 

### Android version

Andorid 14

**Comment by fast4x** [comment]
Fixed in player, available from next version available soon today.
