### ISSUE TITLE
Only single songs appearing available. All albums produce no tracklist when opened from any list following search queries.

### ISSUE THREAD

**Issue by Trawley-Dawdger** [fast4x/RiMusic#3379]
### Steps to reproduce the bug

1. Search artist or album title or combinatiom
2. Select desired artist or album from results
3. If artist select album from discography

### Expected behavior

Album page opens
Tracklist loads
Select action from available to play, que or add to playlist

### Actual behavior

Generic loading screen appears and never resolves

### RiMusic version

0.6.49

### Android version

12

**Comment by fast4x** [comment]
Fixed, available from next version available soon today.
