### ISSUE TITLE
Albums no cargan

### ISSUE THREAD

**Issue by Nisselle** [fast4x/RiMusic#3380]
### Steps to reproduce the bug

1. Abro la app
2. Busco un artista
3. Le doy click en la sección de álbumes
4. Le doy click a cualquier álbum y se queda cargando y nunca se termina de cargar

### Expected behavior

Que al seleccionar un album se cargue por completo y no solo se quede cargando por muchos minutos

### Actual behavior

Se queda cargando por minutos y minutos y nunca se termina de cargar

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/0899eb6a-b02d-4142-91ee-ca2bec5952e2

### RiMusic version

0.6.49

### Android version

Android 11

### Additional information

Me he quedado más de 5 minutos esperando que carguen los albums y nunca se termina de cargar, no se llega a cargar ni la portada, ni el nombre del artista y álbum. Y tampoco es mi conexión ya que mi internet funciona muy bien con otras aplicaciones sin problema alguno de carga

**Comment by teemue** [comment]
Ditto

**Comment by fast4x** [comment]
Fixed, available from next version available soon today.
