### ISSUE TITLE
Gli album non caricano 

### ISSUE THREAD

**Issue by Gaetanstar** [fast4x/RiMusic#3381]
### Steps to reproduce the bug

Apri l' app e seleziona un qualsiasi album 

### Expected behavior

L' app dovrebbe aprire l'album 

### Actual behavior

L' app carica all' infinito senza fare vedere l'album 

### RiMusic version

0.6.49

### Android version

Android 13

**Comment by fast4x** [comment]
Fixed, available from next version available soon today.
