### ISSUE TITLE
Modern player minimizes the player

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#3383]
### Steps to reproduce the bug

https://github.com/user-attachments/assets/60640782-f44d-42e3-8440-612fcb769486

### Expected behavior

Player is not minimized

### Actual behavior

Player is minimized

### RiMusic version

0.6.49

### Android version

Android 13 HyperOS

**Comment by fast4x** [comment]
Keep player minimized work outside of it...
https://github.com/user-attachments/assets/c22fbc80-1203-4fea-b426-6ae1dfe48463

**Comment by aneesh1122** [comment]
> Keep player minimized work outside of it...
> https://github.com/user-attachments/assets/c22fbc80-1203-4fea-b426-6ae1dfe48463
> 
> 

Dude just watch the video. In the carousel if I change the song the player is getting minimized. It shouldn't happen.

I disabled minimizing the player if modern player is selected but in the last update you disabled the code.

Please fix this.
