### ISSUE TITLE
Carátulas discos desaparecen por el logotipo de Rimusic

### ISSUE THREAD

**Issue by YodaGi** [fast4x/RiMusic#3384]
### Steps to reproduce the bug

Nada al visualizar los álbumes guardados, desaparece la carátulas del álbum 

### Expected behavior

Pues que la carátulas del álbum no se cambie por el logotipo de rimusic
![Screenshot_2024-08-24-12-10-53-615_it fast4x rimusic](https://github.com/user-attachments/assets/b3e714cf-bc20-4dfe-a02b-8bd799675e18)

### Actual behavior

![Screenshot_2024-08-24-12-10-59-852_it fast4x rimusic](https://github.com/user-attachments/assets/49eeb0e3-abec-4e8d-893d-9d1fc8a45475)

### Screenshots/Screen recordings

![Screenshot_2024-08-24-12-05-41-822_it fast4x rimusic](https://github.com/user-attachments/assets/4d18fb52-13fc-4a94-8377-05e1e2f8add6)

### RiMusic version

0.6.48

### Android version

Android 12 sobre Miui 13

**Comment by YodaGi** [comment]
Me a funcionado mal desde hace dos días, llevaba 15 días y sin problemas

**Comment by fast4x** [comment]
Fixed, available from next version available soon today.

**Comment by YodaGi** [comment]
Sigue igual, bueno peor porque ahora no se cargan las canciones de los
álbumes.

**Comment by fast4x** [comment]
Nust download latest version

**Comment by YodaGi** [comment]
Si ya la había descargado, pero sigue igual, las carátulas de los álbumes
guardados se quitan y sale el logotipo de Rimusic

**Comment by YodaGi** [comment]
Todo bien, ha vuelto a funcionar, ya no desaparecen las carátulas de los
álbumes y cargan bien las canciones. Instale la última versión desde el
programa Rimusic y parece que ha funcionado, antes descárgaba las versiones
desde la web. Gracias
