### ISSUE TITLE
Unexpected closures still unresolved

### ISSUE THREAD

**Issue by XGhostRX** [fast4x/RiMusic#3386]
### Steps to reproduce the bug

When trying to listen to local music

### Expected behavior

Normal playback

### Actual behavior

Same old closures

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/6ec4efad-1171-4a59-95f5-d05ff05fdb20

### Logs

2024-08-27T13:46:16.612:	java.lang.NullPointerException
	 P6.o.u(SourceFile:966) 
	 P6.o.k(SourceFile:13) 
	 C7.O.a(SourceFile:73) 
	 C7.h.a(SourceFile:18) 
	 C7.H.u(SourceFile:51) 
	 g7.a.i(SourceFile:9) 
	 z7.J.run(SourceFile:113) 
	 A7.d.run(SourceFile:229) 
	 G7.k.run(SourceFile:3) 
	 G7.a.run(SourceFile:96) 

### RiMusic version

0.6.49.1

### Android version

Android 10

### Additional information

Another update that didn't fix this issue

**Comment by twistios** [comment]
Did you get an output in the crash log?
See [this](https://github.com/fast4x/RiMusic/wiki/FAQs#how-do-i-get-log-files-in-case-of-a-crash) for how to get the crash log.

**Comment by XGhostRX** [comment]
> Did you get an output in the crash log? See [this](https://github.com/fast4x/RiMusic/wiki/FAQs#how-do-i-get-log-files-in-case-of-a-crash) for how to get the crash log.

[log.txt](https://github.com/user-attachments/files/16766886/log.txt)

**Comment by twistios** [comment]
<details><summary>This is the error stack trace</summary>
<p>

````
java.lang.NullPointerException
	 P6.o.u(SourceFile:966) 
	 P6.o.k(SourceFile:13) 
	 C7.O.a(SourceFile:73) 
	 C7.h.a(SourceFile:18) 
	 C7.H.u(SourceFile:51) 
	 g7.a.i(SourceFile:9) 
	 z7.J.run(SourceFile:113) 
	 A7.d.run(SourceFile:229) 
	 G7.k.run(SourceFile:3) 
	 G7.a.run(SourceFile:96) 
````

</p>
</details> 

I am also adding this so that it can be seen easily.

**Comment by XGhostRX** [comment]
> This is the error stack trace
> I am also adding this so that it can be seen easily.

2024-08-27T13:46:16.612:	java.lang.NullPointerException
	 P6.o.u(SourceFile:966) 
	 P6.o.k(SourceFile:13) 
	 C7.O.a(SourceFile:73) 
	 C7.h.a(SourceFile:18) 
	 C7.H.u(SourceFile:51) 
	 g7.a.i(SourceFile:9) 
	 z7.J.run(SourceFile:113) 
	 A7.d.run(SourceFile:229) 
	 G7.k.run(SourceFile:3) 
	 G7.a.run(SourceFile:96)

**Comment by twistios** [comment]
@XGhostRX I already posted this. You can expand my comments via the small triangle.

**Comment by XGhostRX** [comment]
> Este es el seguimiento de la pila de errores
> ```
> java.lang.NullPointerException
> 	 P6.o.u(SourceFile:966) 
> 	 P6.o.k(SourceFile:13) 
> 	 C7.O.a(SourceFile:73) 
> 	 C7.h.a(SourceFile:18) 
> 	 C7.H.u(SourceFile:51) 
> 	 g7.a.i(SourceFile:9) 
> 	 z7.J.run(SourceFile:113) 
> 	 A7.d.run(SourceFile:229) 
> 	 G7.k.run(SourceFile:3) 
> 	 G7.a.run(SourceFile:96) 
> ```
> 
> También agrego esto para que se pueda ver fácilmente.

I see that so far there is no solution to the unexpected closures :/

**Comment by fast4x** [comment]
try latest please

**Comment by XGhostRX** [comment]
> try latest please

That mistake is never going to be resolved, sorry
