### ISSUE TITLE
Album issue

### ISSUE THREAD

**Issue by Vahro-nop** [fast4x/RiMusic#3387]
### Steps to reproduce the bug

1. Click on any album in the app
2. Album don't Load and no songs appear

### Expected behavior

This happened to me before and an update fixed it the I tried that but I didt work and when clicking an album no songs appear so it doesn't let me listen the all the songs on the album

### Actual behavior

When click on an album i can see or Listen to the songs on the album because the album don't Load

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/f9abcf8e-0bde-4780-b0ca-c9ddff9a7089

![Screenshot_20240824_100402](https://github.com/user-attachments/assets/c3c59754-d885-49ba-96f8-cf8524133de7)

### Logs

It don't crash from the bug I'm dealing with but the I'm on or of the app the app sometimes crashes and some song dont appear when i search it up or it does but don't let me play the song.

### RiMusic version

v0.6.48

### Android version

Android 14

### Additional information

When I'm Listening to a song on or of the app sometimes crashes.

**Comment by fast4x** [comment]
Download latest version it's fixed https://github.com/fast4x/RiMusic/releases/latest
