### ISSUE TITLE
Default page option not working

### ISSUE THREAD

**Issue by AstroLightz** [fast4x/RiMusic#3389]
### Steps to reproduce the bug

1. Set the Default Page option to "Playlists"
2. Close the app and reopen, or exit settings

### Expected behavior

The selected Default page should be shown (ex. Playlists)

### Actual behavior

The Songs page is always shown instead. It does not matter what you switch it to.

### RiMusic version

v0.6.49.1

### Android version

Android 14

**Comment by fast4x** [comment]
Only playlists page or also all?

**Comment by AstroLightz** [comment]
All of them.

**Comment by fast4x** [comment]
Fixed available from version 0.6.50

**Comment by OriginalJuani** [comment]
bro is locked in, 3 UPDATES in 2 days, dawg, keep with the good job

**Comment by fast4x** [comment]
Bro if an update is necessary it is done. The last one (0.6.49.2) is not mandatory and is not advertised.
