### ISSUE TITLE
Playback error when reopen the app

### ISSUE THREAD

**Issue by ndavid3** [fast4x/RiMusic#339]
### Steps to reproduce the bug

1. Open the app and start a music 
2. Close the app, and swipe out from last used apps list
3. (The music still playing) New stop the music and swipe out the player from notifications 
4. Reopen the app and try to play a music and you will get playback error

### Expected behavior

Play music without error

### Actual behavior

Does not play music

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/113303831/94f7da27-fda4-433e-9910-e3c8e3c0fe71

The video is speeded up, to get the size under 10 MB

### RiMusic version

0.6.16

### Android version

Android 14

**Comment by fast4x** [comment]
Oh, thanks for details.

**Comment by fast4x** [comment]
Info, option to close background player is enabled?

**Comment by ndavid3** [comment]
> Info, option to close background player is enabled?

if it's enabled, if it's not it's happen the same

**Comment by fast4x** [comment]
Ok

**Comment by ndavid3** [comment]
> Ok

If it's enabled, and i stop the music before close the app, then doesn't get the error after reopen

**Comment by ndavid3** [comment]
It seems that this error happen only when I close the app without stopping the music before

**Comment by ndavid3** [comment]
With the new update in that situation crashes the app

**Comment by fast4x** [comment]
The bug has not been fixed yet

**Comment by fast4x** [comment]
Hi, try to set invincible service on settings
 https://github.com/fast4x/RiMusic/wiki/FAQs#-why-does-it-close-after-some-time-i-have-paused

**Comment by ndavid3** [comment]
> Hi, try to set invincible service on settings
>  https://github.com/fast4x/RiMusic/wiki/FAQs#-why-does-it-close-after-some-time-i-have-paused

Doesn't help
I used ViMusic and it is still installed, there was no such problem

**Comment by fast4x** [comment]
I'm sorry

**Comment by ndavid3** [comment]
> I'm sorry

Oh, no problem, I just want to help as much as I can
