### ISSUE TITLE
Import playlist

### ISSUE THREAD

**Issue by anonymous2420** [fast4x/RiMusic#3391]
### Description

Please add a new feature,where we can add or import playlist through playlist link,from other music playlists which we created like,from YouTube music, Spotify etc.
This feature is available in black hole apk,please try to add this feature,so that we don't need to again create a new playlist ..thank you❤️

### Suggested Solution

Feature would be like adding/importing playlist using playlist link

**Comment by aneesh1122** [comment]
> from YouTube music

You can already do that

> spotify

Transfer songs from spotify's playlist to YT's playlist using any site of your choice. There are many.

**Comment by anonymous2420** [comment]
> > from YouTube music
> 
> You can already do that
> 
> > spotify
> 
> Transfer songs from spotify's playlist to YT's playlist using any site of your choice. There are many.

Yeah ,I know that, but is there any option of importing playlists from other music platforms into RI Music..?

**Comment by aneesh1122** [comment]
> > > from YouTube music
> > 
> > You can already do that
> > 
> > > spotify
> > 
> > Transfer songs from spotify's playlist to YT's playlist using any site of your choice. There are many.
> 
> Yeah ,I know that, but is there any option of importing playlists from other music platforms into RI Music..?

Directly? No.

**Comment by anonymous2420** [comment]
> > > > from YouTube music
> > > 
> > > 
> > > You can already do that
> > > > spotify
> > > 
> > > 
> > > Transfer songs from spotify's playlist to YT's playlist using any site of your choice. There are many.
> > 
> > 
> > Yeah ,I know that, but is there any option of importing playlists from other music platforms into RI Music..?
> 
> Directly? No.

Yeah, there is no feature of importing playlists through playlist link which we created in other music platforms like YT music,but this feature is there in black hole apk, please try to add this feature...!

**Comment by aneesh1122** [comment]
> > > > > from YouTube music
> > > > 
> > > > 
> > > > You can already do that
> > > > > spotify
> > > > 
> > > > 
> > > > Transfer songs from spotify's playlist to YT's playlist using any site of your choice. There are many.
> > > 
> > > 
> > > Yeah ,I know that, but is there any option of importing playlists from other music platforms into RI Music..?
> > 
> > Directly? No.
> 
> Yeah, there is no feature of importing playlists through playlist link which we created in other music platforms like YT music,but this feature is there in black hole apk, please try to add this feature...!

Man, I already told you that you can import playlists from yt music.

Spotify playlist import will never be added in this app. This question has been asked a lot of times and the response from fast has always been the same.

**Comment by anonymous2420** [comment]
> > > > > > from YouTube music
> > > > > 
> > > > > 
> > > > > You can already do that
> > > > > > spotify
> > > > > 
> > > > > 
> > > > > Transfer songs from spotify's playlist to YT's playlist using any site of your choice. There are many.
> > > > 
> > > > 
> > > > Yeah ,I know that, but is there any option of importing playlists from other music platforms into RI Music..?
> > > 
> > > 
> > > Directly? No.
> > 
> > 
> > Yeah, there is no feature of importing playlists through playlist link which we created in other music platforms like YT music,but this feature is there in black hole apk, please try to add this feature...!
> 
> Man, I already told you that you can import playlists from yt music.
> 
> Spotify playlist import will never be added in this app. This question has been asked a lot of times and the response from fast has always been the same.

Wait... where is the option of importing playlists from yt music into RI Music..?😬

**Comment by aneesh1122** [comment]
> > > > > > > from YouTube music
> > > > > > 
> > > > > > 
> > > > > > You can already do that
> > > > > > > spotify
> > > > > > 
> > > > > > 
> > > > > > Transfer songs from spotify's playlist to YT's playlist using any site of your choice. There are many.
> > > > > 
> > > > > 
> > > > > Yeah ,I know that, but is there any option of importing playlists from other music platforms into RI Music..?
> > > > 
> > > > 
> > > > Directly? No.
> > > 
> > > 
> > > Yeah, there is no feature of importing playlists through playlist link which we created in other music platforms like YT music,but this feature is there in black hole apk, please try to add this feature...!
> > 
> > Man, I already told you that you can import playlists from yt music.
> > 
> > Spotify playlist import will never be added in this app. This question has been asked a lot of times and the response from fast has always been the same.
> 
> Wait... where is the option of importing playlists from yt music into RI Music..?😬

Method 1:
Go to yt music, share the playlist, you can find RiMusic in the list of apps to which you can share.

Method 2:
Paste the link of playlist, then do this

https://github.com/user-attachments/assets/4ac35928-daaa-4066-a3fc-134d83c4324d

**Comment by anonymous2420** [comment]
> > > > > > > > from YouTube music
> > > > > > > 
> > > > > > > 
> > > > > > > You can already do that
> > > > > > > > spotify
> > > > > > > 
> > > > > > > 
> > > > > > > Transfer songs from spotify's playlist to YT's playlist using any site of your choice. There are many.
> > > > > > 
> > > > > > 
> > > > > > Yeah ,I know that, but is there any option of importing playlists from other music platforms into RI Music..?
> > > > > 
> > > > > 
> > > > > Directly? No.
> > > > 
> > > > 
> > > > Yeah, there is no feature of importing playlists through playlist link which we created in other music platforms like YT music,but this feature is there in black hole apk, please try to add this feature...!
> > > 
> > > 
> > > Man, I already told you that you can import playlists from yt music.
> > > Spotify playlist import will never be added in this app. This question has been asked a lot of times and the response from fast has always been the same.
> > 
> > 
> > Wait... where is the option of importing playlists from yt music into RI Music..?😬
> 
> Method 1: Go to yt music, share the playlist, you can find RiMusic in the list of apps to which you can share.
> 
> Method 2: Paste the link of playlist, then do this
> 
>  VID_20240825_003813.mp4

This is what,i have asked for before...it's working thank you❤️
