### ISSUE TITLE
Mistakes in albums and singles

### ISSUE THREAD

**Issue by Teleposse** [fast4x/RiMusic#3393]
### Steps to reproduce the bug

When you go to an artist and try to open an album or single (it doesn't matter which method you use if you also try to open it)
It doesn't load or show anything

### Expected behavior

It should load and display all the songs etc

### Actual behavior

but it stays on the loading screen and it's not my connection's fault.

### Screenshots/Screen recordings

![IMG_20240824_203251](https://github.com/user-attachments/assets/5a8268ef-2b3e-49a0-9f5a-46d5abdd5eb9)

### RiMusic version

0.6.48

### Android version

Android 12

**Comment by aneesh1122** [comment]
Download the latest version

**Comment by Teleposse** [comment]
> Download the latest version

If I do this, will everything be deleted?Reset?
