### ISSUE TITLE
Views /streams in songs (I NEED IT) (and sorry for my english)

### ISSUE THREAD

**Issue by Teleposse** [fast4x/RiMusic#3394]
### Description

(Since I'm new I tried to comment on it but it gets deleted idk it doesn't let me see it and it seems to have disappeared)
The point is that the visits that we have in this application count as Youtube visits (normal yt not music) since in most players the visits count.

### Suggested Solution

In many awards etc you need votes, etc and visits, we all want our favorites to win but it would be much more comfortable to listen to it from here and not have to watch it as if it were a video.This would be more convenient, the application would be used more and we wouldn't have to bother with the YouTube screen not turning off,adds And everything would be better in general :D P.S.: The sooner the better and please let us know 🗣️🗣️

**Comment by fast4x** [comment]
RiMusic simple read data from YouTube/YouTube Music, isn't planned that view of artist/song will increment statistics.

**Comment by Teleposse** [comment]
> RiMusic simple read data from YouTube/YouTube Music, isn't planned that view of artist/song will increment statistics.
> 
> But you want views statistics in song?

I didn't understand you well, I mean that when I listened to the song once it counts as having watched the YouTube video of the song once, I don't know if I was understood.

**Comment by fast4x** [comment]
Isn't possible sorry

**Comment by Teleposse** [comment]
> Isn't possible sorry

Why?😭😭
