### ISSUE TITLE
local files not working 

### ISSUE THREAD

**Issue by Kou-tester** [fast4x/RiMusic#3395]
### Steps to reproduce the bug

When trying to play my local files they just don't work

### Expected behavior

I also want to put a song from my local files in a playlist but I can't interact with them. 

### Actual behavior

The other thing is that some songs from the local files that I previously put in my playlist get buggy covers and then the other songs in the playlist appear without cover art.

### Screenshots/Screen recordings

![Screenshot_2024-08-24-14-57-40-866_it fast4x rimusic](https://github.com/user-attachments/assets/c7c9131a-2b78-4d22-b699-2fa253c96e73)
(This is what I mean, the cover just disappears)

### RiMusic version

version 0.6.49.1

### Android version

Android 14

**Comment by fast4x** [comment]
Enable debug in miscellaneous settings and paste here the log after a couple of time
