### ISSUE TITLE
[Feature]: Update the app in the app itself

### ISSUE THREAD

**Issue by odamaasio** [fast4x/RiMusic#3396]
### Description

It will be interesting instead of the download being made in an external application to be performed in RiMusic itself, as it happens in several open source apps. 

Example
App Seal:
![Screenshot_20240818-184635_Seal](https://github.com/user-attachments/assets/791ccc99-d4a5-4822-a937-ddbfaf1fd4de)

### Suggested Solution

When the update of the app arrives on github, automatically appear in RiMusic that has a new version available and the user click to update and the update is performed in the app itself (RiMusic), without leaving the app and without opening the browser externally.

**Comment by faustaahmad** [comment]
You could use [Obtainium](https://github.com/imranr98/obtainium)
I'm still using it, great app for updating/installing bunch of open-source apps

**Comment by fast4x** [comment]
Auto update isn't planned for privacy reason.

**Comment by bebotette** [comment]
> You could use [Obtainium](https://github.com/imranr98/obtainium) I'm still using it, great app for updating/installing bunch of open-source apps

I can't seem to add rimusic to obtainium. What's the right link?

**Comment by faustaahmad** [comment]
@bebotette enable "Retain release order from older API"
Idk why I have that enabled

**Comment by DarkCrypt** [comment]
Duplicate of #555.

Was implemented and then changed because of F-Droid in #400.

**Comment by DarkCrypt** [comment]
> I can't seem to add rimusic to obtainium. What's the right link?

Use the main repo URL. Obtainium automatically checks for apks within the GitHub Releases page.

RiMusic: `https://github.com/fast4x/RiMusic`

Or you can import RiMusic into Obtainium [here](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22it.fast4x.rimusic%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Ffast4x%2FRiMusic%22%2C%22author%22%3A%22fast4x%22%2C%22name%22%3A%22RiMusic%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Afalse%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22useLatestAssetDateAsReleaseDate%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22RiMusic%C2%A0is%20a%C2%A0multilingual%C2%A0Android%20application%20for%20streaming%20music%20from%20YouTube%20Music.%5C%22%7D%22%2C%22overrideSource%22%3A%22GitHub%22%7D) which is the same as PR #3637 without the graphic.
