### ISSUE TITLE
Escuchar brevemente una canción 

### ISSUE THREAD

**Issue by Noeliiarp26** [fast4x/RiMusic#3399]
### Description

Cuando estoy escuchando mis canciones favs y busco una que no es de mis favs, me gustaría que dándole a la portada de la canción de mostrará 15 segundos para saber si te gusta. Ya que si le doy se me quita mi lista de producción🙏🏻 gracias

### Suggested Solution

P

### Alternatives

A

### Additional Context

H

**Comment by fast4x** [comment]
You can set Medley mode to 15s

**Comment by fast4x** [comment]
Look
https://github.com/user-attachments/assets/ee96344f-4de8-48ed-b686-6d269610217a

**Comment by Noeliiarp26** [comment]
Graciasss🙏🏻. Pero de todas formas se me quita la canción q estoy escuchando y se pone la que quería escuchar solo un poco.
