### ISSUE TITLE
[Question]: what does this option do in the album section 

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#34]
### Description

![IMG_20231026_092245](https://github.com/fast4x/RiMusic/assets/127825700/2fba23c3-bade-44d2-bf78-a8d74739926e)

### Suggested Solution

.

### Additional Context

I'm using the latest debug

**Comment by fast4x** [comment]
Is Enquee

**Comment by ikanakova** [comment]
> Is Enquee
>
> Temporarily inserted, I'm considering other icons.
> Suggestion?

I think it should be on the right side with the other icons.

**Comment by fast4x** [comment]
> Icon of the entire album/playlist: https://thenounproject.com/icon/play-queue-1287553/
> 
> If it was possible to select individual tracks, which would be great! ➕ in the icon

Create a new issue for feature :)

**Comment by fast4x** [comment]
> I think it should be on the right side with the other icons.

Okay, we can see what it looks like on the right

**Comment by ikanakova** [comment]
I looked on ionic and they don't have any similar one there, but I'm happy to make one (similar to the one I posted) in SVG if there's interest. In the end I think 1 will be enough for this and my feature request #35 🙂

**Comment by fast4x** [comment]
Great

**Comment by ikanakova** [comment]
Created using ionicons:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/22e86e6f-05cd-478b-a0c4-19c9ef8d9d85" width="120">

**Comment by fast4x** [comment]
icon replaced, thanks! 
Available from version 0.6.6

**Comment by fast4x** [comment]
![Screenshot_20231026_171308](https://github.com/fast4x/RiMusic/assets/1484476/9b1e34f5-c63b-4802-aefa-3670db549c74)
