### ISSUE TITLE
Playlist Songs Repeats

### ISSUE THREAD

**Issue by CallmeDefender** [fast4x/RiMusic#3402]
### Steps to reproduce the bug

Playlist songs repeats kindly fix this issue in new update. And also frequent app crash with high battery usage

### RiMusic version

0.6.49.2

### Android version

Android 12

**Comment by fast4x** [comment]
Too generic, explain better please, send any screenshots.

**Comment by CallmeDefender** [comment]
![Screenshot_20240825-101707_Device care](https://github.com/user-attachments/assets/b2566c38-406b-45e3-bd29-940fcfee6671)
![Screenshot_20240825-101554_Device care](https://github.com/user-attachments/assets/4ec1d915-1cec-4308-bfac-c834108bfcef)

**Comment by fast4x** [comment]
Decrease max songs in queue and use minimal functionality in player
