### ISSUE TITLE
se crashea al mover una canción en la lista de cola

### ISSUE THREAD

**Issue by pokeshadow89** [fast4x/RiMusic#3403]
### Steps to reproduce the bug

elegir una playlist
ir a mover el orden de las canciones
mover alguna canción y se crashea

### Expected behavior

antes se podían mover sin problemas (0.4.8.0)

### Actual behavior

se crashea

### RiMusic version

v0.6.49.2

### Android version

Android 12

**Comment by fast4x** [comment]
Decrease max songs in queue by ui settings

**Comment by fast4x** [comment]
Fixed available from version 0.6.50
