### ISSUE TITLE
Sync Piped playlist empties the playlist

### ISSUE THREAD

**Issue by Generator** [fast4x/RiMusic#3405]
### Steps to reproduce the bug

1. Create a new Piped playlist
2. Add songs to Piped playlist
3. Sync playlist

### Expected behavior

Sync playlists with Piped instance

### Actual behavior

Playlists on Piped shows "0 videos", when try to sync or open on other device the list is empty.

### RiMusic version

0.6.49.2

### Android version

Android 14

**Comment by fast4x** [comment]
Enable log in miscellaneous settings and afte a couple of time paste here log.
