### ISSUE TITLE
Audio Quality not as good as Innertune

### ISSUE THREAD

**Issue by vivekanandan-ks** [fast4x/RiMusic#3408]
### Steps to reproduce the bug

Play any music with quality high.
Compare it with quality high in Innertune app.

### Expected behavior

Quality should have been same since both uses YTmusic and YT APIs

### Actual behavior

But somehow the audio quality is poor in RiMusic. My guess is that it have something to do with format/bitrate.

### RiMusic version

0.6.49.2

### Android version

11

### Additional information

Kindly do compare with multiple songs and ull realise the change in quality. My guess is that it has something to do with the format or bitrate difference.

**Comment by vivekanandan-ks** [comment]
I tried doing that, but still the quality is not on par with innertune. What's the codec, format and sample rate u are using?

**Comment by fast4x** [comment]
The file is the same, the difference is that RiMusic shows less information.
