### ISSUE TITLE
Artist button not working 

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#341]
### Steps to reproduce the bug

1. Select any song
2. Play that song
3. Under the song name title, the artist name will be displayed
4. Tap on that you will see that button is greyed out.
5. Change song than comeback to that song you will find the artist button is not greyed out.

### Expected behavior

The button should show the artist name when we tap first time

### Actual behavior

But it was greyed out and to activate it you have to change song

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/120176369/f8cce250-a16e-4107-b596-bae4755a46b7

### RiMusic version

0.6.16

### Android version

Android 14

### Additional information

I loved your app and I appreciate that you continued the legacy of VImusic but need some finishing touches and also please fix grey ui in dynamic theme

**Comment by fast4x** [comment]
Album and artist nane are enabled if related song have correct info. When not, links are disable, not Is a bug.

**Comment by fast4x** [comment]
Try holding on the name, if it is ok it will display

**Comment by Logan7899** [comment]
Done

**Comment by fast4x** [comment]
I could show a message when the info is missing, without disable text. What do you think?

**Comment by fast4x** [comment]
Added warning icon when album and/or artist info are missed

Available from version 0.6.17

**Comment by fast4x** [comment]
Available on version 0.6.16.1
