### ISSUE TITLE
App crashes whenever i try to move songs in que

### ISSUE THREAD

**Issue by Julian1535** [fast4x/RiMusic#3412]
### Steps to reproduce the bug

 .

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

.

### Logs

.

### RiMusic version

.

### Android version

.

### Additional information

.

**Comment by twistios** [comment]
Duplicate of #3403.

**Comment by fast4x** [comment]
Fixed available from version 0.6.50
