### ISSUE TITLE
After listening to songs the entire app will freeze and then crash when i try to open it again

### ISSUE THREAD

**Issue by Julian1535** [fast4x/RiMusic#3413]
### Steps to reproduce the bug

. 

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

.

### Logs

.

### RiMusic version

.

### Android version

.

### Additional information

.

**Comment by twistios** [comment]
Please add log:
https://github.com/fast4x/RiMusic/wiki/FAQs#how-do-i-get-log-files-in-case-of-a-crash
