### ISSUE TITLE
Video Feature 

### ISSUE THREAD

**Issue by Jetliarm** [fast4x/RiMusic#3415]
### Description

It would be great if RiMusic could let us play videos from youTube, not just the audio. sometimes we want to watch music videos or live performances right in the app without switching to youTube just like simp music have
![Screenshot_20240826-015541](https://github.com/user-attachments/assets/0d80cd5b-60b2-4df3-970f-f9de2e560028)

### Suggested Solution
add a button to switch between audio and video when playing youTube links.

.

### Alternatives

.

### Additional Context

.

**Comment by fast4x** [comment]
What's app is in the thumbnail?

**Comment by Jetliarm** [comment]
simp music

**Comment by fast4x** [comment]
Implemented video support, available from version 0.6.50
