### ISSUE TITLE
Brasilian portuguese translation is still wrong

### ISSUE THREAD

**Issue by AquamarineDreams** [fast4x/RiMusic#3416]
### Steps to reproduce the bug

**Not a bug**

### Expected behavior

Three months ago I opened an issue to report that the pt-br translation was wrong in several places.
[#2127]

You said to go to Crowdin and fix it. So I downloaded the string.xml file and fixed the wrong translations I reported, some other that I didn't included in my bug report, and fixed some parts so it would work better in portuguese. I basically suggested a change for every single string [569 at the time].

Three months later, and basically none of my changes were applied, wich I understand since I suggested lots of things. But even the mistranslated parts that I included on my bug report were not changed.

### Actual behavior

Brasilian portuguese translation is still wrong

### RiMusic version

0.6.49.2

### Android version

Android 14

**Comment by twistios** [comment]
Don't download it and do pull request, instead you should edit the texts on the crowdin page.

**Comment by maboroshin** [comment]
Perhaps the developer has approved the mistranslation. 

See https://github.com/fast4x/RiMusic/issues/2127#issuecomment-2143465416

If there are no vandals, there is no need to use approval.
