### ISSUE TITLE
Does not show songs from albums

### ISSUE THREAD

**Issue by ifz5** [fast4x/RiMusic#3419]
### Steps to reproduce the bug

Go to an artist 
Go to an album by that artist
The album doesn't open, it doesn't show any songs from that album

### Expected behavior

When choosing the artist's album, the songs from that album should appear.

### Actual behavior

The album doesn't open, it doesn't show any songs from that album

### Screenshots/Screen recordings

![Screenshot_2024-08-25-22-12-52-816_it fast4x rimusic](https://github.com/user-attachments/assets/d74bd161-2b39-456f-9b62-f8f1a85a49b3)

### RiMusic version

0.6.48

### Android version

Android 13

**Comment by fast4x** [comment]
Update to latest release

**Comment by ifz5** [comment]
I have already updated it and the songs in the albums are now visible.
Thank you very much for the support.
Best regards!
