### ISSUE TITLE
Certain songs in playlists disappear from playlist after update

### ISSUE THREAD

**Issue by AstroLightz** [fast4x/RiMusic#3422]
### Steps to reproduce the bug

1. Open up a playlist

### Expected behavior

All songs that were in the playlist should be in there.

### Actual behavior

For some playlists, some songs disappear after loading them. You can add them back in, but they disappear again when you open the playlist up.

### RiMusic version

v0.6.49.2

### Android version

Android 14

**Comment by twistios** [comment]
I guess an example for a playlist and the songs that trigger that issue would be helpful.
