### ISSUE TITLE
Rimusic

### ISSUE THREAD

**Issue by Codpress** [fast4x/RiMusic#3423]
### Steps to reproduce the bug

Şarkıcı ismini aradım albümleri listeledim albümlere tıkladım albümlerin içeriği ekran görüntüsündeki gibi

### Expected behavior

The content of the albums is not visible in searches, the songs are not listed

### Actual behavior

Artists should be able to list songs on albums

### Screenshots/Screen recordings

![Screenshot_20240826_080056](https://github.com/user-attachments/assets/f916d135-0940-4b8f-b44d-36de90a01a63)

### RiMusic version

0.6.48

### Android version

Android 14

**Comment by fast4x** [comment]
Update to latest release
