### ISSUE TITLE
Artist's albums are not showing 

### ISSUE THREAD

**Issue by Ishan007-raymond** [fast4x/RiMusic#3424]
### Steps to reproduce the bug

https://github.com/user-attachments/assets/8a123749-8fa1-4604-afdd-a0c0ee5beb1d

### Expected behavior

![Screenshot_2024-08-26-10-58-42-71_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/ce219083-33b1-4e58-a27b-343f01df8508)

### Actual behavior

![Screenshot_2024-08-26-10-56-39-13_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/7d4c4903-c77a-40fa-b51d-43105ada02cc)

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/d02e8b97-b8a6-486e-8fe4-627bccdb47a6

### RiMusic version

0.6.49

### Android version

Android 11

### Additional information

All albums, singles should be shown

**Comment by justin012og** [comment]
Same issue here

**Comment by fast4x** [comment]
Update to latest release

**Comment by Ishan007-raymond** [comment]
Awesome, thanks for the update!
