### ISSUE TITLE
playing queue interrupted

### ISSUE THREAD

**Issue by enomao44** [fast4x/RiMusic#3427]
### Description

when you are listening music and you stop it for a while then you cannot resume at the point you where? im losing all the queue i prepared. There is some option to keep what i was playing before?

### Suggested Solution

 even if i have to start the song from 00:00 when i was interrupted or continue at the exact moment i interrupted?

**Comment by twistios** [comment]
Persistent queue maybe?

**Comment by enomao44** [comment]
this is already a feature inside settings?

**Comment by twistios** [comment]
![Screenshot_20240829_104007](https://github.com/user-attachments/assets/8f11f41c-d735-4d2a-9f18-5d446686913a)
