### ISSUE TITLE
Album page not working. It keeps loading

### ISSUE THREAD

**Issue by justin012og** [fast4x/RiMusic#3428]
### Steps to reproduce the bug

I went to search bar
Searched an artist
Went to albums 
Opened his album and it just kept loading nothing showed

### Expected behavior

When i open an album i expect songs to show 

### Actual behavior

It just kept loading and stuck there 

### Screenshots/Screen recordings

![Screenshot_20240826-101521](https://github.com/user-attachments/assets/898f2952-e7ed-4ccc-a34d-1b279ad5dbca)

### RiMusic version

0.6.48

### Android version

9

**Comment by broadcastyourseb** [comment]
Same behaviour with version 0.6.48. I just install the latest version 0.6.49.2 and everything is fine again.
I assume this issue could be closed.
