### ISSUE TITLE
White corners in home dropdown.

### ISSUE THREAD

**Issue by betmobil** [fast4x/RiMusic#3432]
### Steps to reproduce the bug

1. Open the app
2. Tap on three lines in upper right corner in portrait mode

### Expected behavior

The dropdown should be fully gray

### Actual behavior

Dropdown is gray woth white rounded corners

### Screenshots/Screen recordings

![Screenshot_20240826-150752](https://github.com/user-attachments/assets/dc054f3b-d3e0-4798-9c60-7da030415f03)

### RiMusic version

0.6.49.1

### Android version

Android 10

### Additional information

My theme settings are dark dynamic.

**Comment by twistios** [comment]
I am not able to increase the size of the emulator large enough so that I can see this there. On my phone I think I was able to see it.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.50
