### ISSUE TITLE
[Feature]: Improve Android TV banner

### ISSUE THREAD

**Issue by Generator** [fast4x/RiMusic#3433]
### Description

[Currently the TV banner is very basic](https://github.com/fast4x/RiMusic/blob/master/app/src/main/res/mipmap-xhdpi/ic_banner.png) and only shows a red rectangle on Android TV  

![rimusic_banner](https://github.com/user-attachments/assets/df0b44ea-4879-4e57-bb67-4ed7eb351e0f)

### Suggested Solution

[Similar to mobile icon](https://github.com/fast4x/RiMusic/blob/master/app/src/main/res/mipmap-xhdpi/ic_launcher.webp) showing the icon and "RiMusic" text

**Comment by fast4x** [comment]
> @fast4x The [banner](https://github.com/fast4x/RiMusic/blob/master/assets/design/banner_tv_foreground.svg) is ready, it just need to set it up. Maybe [this](https://forum.godotengine.org/t/android-how-to-setup-the-tv-banner/68060) will help.

Thanks

**Comment by fast4x** [comment]
Updated, available from version 0.6.50

**Comment by DavidDiaz377** [comment]
How to get RiMusic on smart tv?

**Comment by fast4x** [comment]
Open browser internet, ho to GitHub page, download apk and install, should be work this solution.

**Comment by DavidDiaz377** [comment]
amazing, thanks for the solution!
