### ISSUE TITLE
[Feature]: Follow the song in the playlist display

### ISSUE THREAD

**Issue by ifz5** [fast4x/RiMusic#3435]
### Description

If I'm on song number 15 in my playlist, the playlist display remains at the beginning. The playlist doesn't scroll down with the songs, it stays static.

### Suggested Solution

As the songs in the playlist scroll down, the display for that playlist should continue to play the song that is currently playing, so you know where you are in the playlist.

**Comment by fast4x** [comment]
It's normal, your songs scroll in the queue not in playlist.

**Comment by ifz5** [comment]
And couldn't it sync with the song that's currently playing so you don't have to search for the song that's playing?

**Comment by fast4x** [comment]
You can use Locate button...
![Screenshot_2024-08-27-11-15-55-249_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/8230630d-0fb6-4542-950e-0baae680b856)

**Comment by ifz5** [comment]
![IMG_20240827_231416](https://github.com/user-attachments/assets/2b99392d-29cb-42df-a076-5ac3e32e56f2)
That song is not in that part of the playlist, it is further down and I have to look for it myself and it would be nice if it appeared first. What I am saying is that the song that is playing should always appear first so I know what part of the playlist I am in.

Best regards
