### ISSUE TITLE
After downloading music album and artist page not accessable

### ISSUE THREAD

**Issue by kris20030705** [fast4x/RiMusic#3436]
### Steps to reproduce the bug

How to import YouTube playlists?

Method 1:
Go to yt music, share the playlist, you can find RiMusic in the list of apps to which you can share.

Method 2:
Copy the link of playlist, then do this

All I followed was this but after download completed, Album and Artist page not accessable..!

### Expected behavior

Able to access artist and album page so I can play songs from specific artist..!

### Actual behavior

![Screenshot_20240826-211701_RiMusic](https://github.com/user-attachments/assets/79ed18d3-d9c2-432d-a59c-d5ece4f12ac4)

### RiMusic version

Latest

### Android version

Android 13

**Comment by fast4x** [comment]
Improved, available from version 0.6.56
