### ISSUE TITLE
Optimización (Más fluidez)

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#3438]
### Steps to reproduce the bug

Solamente me gustaría que optimizaran la app debido a que tanta actualización la hace lenta, un ejemplo es la cola de reproducción o cuando busco alguna canción en específico pero se encuentra en una cola larga se congela, inclusive si le quitó canciones a la cola de reproducción se congela con las pocas que allan, no creo que sea mi dispositivo puesto que tengo demasiado espacio disponible y es Androide 14, es muy incómodo no poder buscar alguna canción con más fluidez en la cola y no solo eso. Existen otros detalles pero esos no me molestan tanto.

### Expected behavior

N/A

### Actual behavior

N/A

### Screenshots/Screen recordings

N/A

### Logs

N/A

### RiMusic version

Ultima

### Android version

Android 14

### Additional information

N/A

**Comment by fast4x** [comment]
I'll check it for improvements.
