### ISSUE TITLE
Posible mejora y solución de un problema 

### ISSUE THREAD

**Issue by Freddgonzk** [fast4x/RiMusic#3441]
### Description

Solo quisiera agradecer por tan increíble aplicación y sugerir una nueva opción que mejoraría la experiencia. Me gustaría poder ordenar las canciones de las playlist a gusto, ya que me sucede mucho que añado una nueva canción a una playlist, y permanece de última, y me gustaría poder editar en qué parte específica de la playlist poner las canciones, o sea, poder cambiarlas de posición a gusto.

### Suggested Solution

Por otro lado hay un problema que siempre tengo, y es que la app a veces se cierra inesperadamente sin razón alguna, cosa que es molesta porque suele ocurrir a mitad de canción. Solo me gustaría que pudieran arreglar ese error. De ahí en más me parece una app perfecta.

**Comment by fast4x** [comment]
Hi, thank you, you can order the playlist as you wish. You can also move the songs by selecting the sort by position and unlock the lock.
![Screenshot_2024-08-27-13-06-36-444_it.fast4x.rimusic.jpg](https://github.com/user-attachments/assets/52578ed7-31c5-427e-b7ea-4abfc6af0fba)

**Comment by Freddgonzk** [comment]
Uploading Screenrecorder-2024-08-27-11-28-14-951.mp4…

Muchas gracias, no tenía idea (soy nuevo usando la app) aunque de todos modos sigue ocurriendo el error de que la app se cierra inesperadamente cuando intento mover una canción

**Comment by fast4x** [comment]
Thanks, it's fixed and available from version 0.6.50
