### ISSUE TITLE
Songs automatically skipping

### ISSUE THREAD

**Issue by thurdnoob** [fast4x/RiMusic#3443]
### Steps to reproduce the bug

Searched a song,
Plaued it,
It auromatically plays the next song after playing for 1-2 seconds,
This keeps on skipping 

### Expected behavior

The song should play,

### Actual behavior

It is automatically skipped, and keeps on skipping

### RiMusic version

0.6.49.2

### Android version

Android 14

**Comment by twistios** [comment]
Maybe you have meadly mode enabled. I think this is the default behaviour.
You can deactivate it by long tapping on the play icon in the player and then tapping the hour glass symbole to reset it to zero.
@fast4x maybe this option should be set to zero by default.

**Comment by fast4x** [comment]
Yes it's set to 0 by default, was a bug Just fixed
