### ISSUE TITLE
Volume not changing when screen is locked (maybe on NothingOS only)

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#3444]
### Steps to reproduce the bug

I don't really know how to reproduce the bug

### Expected behavior

Allow the volume to be changed when the screen is locked

### Actual behavior

Volume cannot be changed when the screen is locked

### RiMusic version

0.6.49.2

### Android version

Android 14 Nothing OS

### Additional information

I have a Nothing phone. This may only happen to me because Nothing phones have this feature where it won't allow you to change the media volume when there is no media playing and the screen is locked. Version 0.6.48 works fine, I can change the volume when playing music even when it's locked. But I can't do that anymore with version 0.6.49, something might have changed. I also noticed that the app wasn't recognised as a media player. I also tested other media apps and it works fine.

**Comment by twistios** [comment]
For me it is possible to change the volume on One UI 6.1 (Android 14) with 0.6.49.2. So it might be true, that this is only related to the Nothing OS variant.

**Comment by fast4x** [comment]
I'll check it

**Comment by cMattw** [comment]
This has been fixed with the latest Nothing OS update
