### ISSUE TITLE
桌面歌词

### ISSUE THREAD

**Issue by lxc0527** [fast4x/RiMusic#3446]
### Description

能搞个桌面歌词吗，真的很想要

### Suggested Solution

能搞个桌面歌词吗，真的很想要

**Comment by twistios** [comment]
What is desktop lyrics? (this is what I get with a translator)
Currently there is not desktop version of RiMusic, only apk (Android Phone and Tablet, Android Auto and TV with many problems).
It is planed to add a desktop variant in the future but this is only a long term plan based on my understanding.

If it is something else, please tell.
