### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by Alexander743286** [fast4x/RiMusic#3447]
### Descripción

- Solo que el color de la notificación de la aplicación de música Rimusic cambia de color según la cancelación o el álbum

- Sólo que el color de notificación de la aplicación de música Rimusic cambia de color según la canción o el álbum

- Apenas a cor da notificação do aplicativo de música Rimusic muda de cor dependiente da música ou álbum

### Soluție sugestatăă

Nada todo está muy bien 
Nothing everything is fine 
Nada, está tudo muito bom 

### Alternativas

_Nu răspuns_

### Suplimentar de context

_Nu răspuns_

**Comment by JeePopuwu** [comment]
Ya lo hace pero debes configurarlo bro
![Screenshot_2024-08-27-12-45-19-158_it fast4x rimusic](https://github.com/user-attachments/assets/74ccfba3-2df1-410f-9d86-486a9c70ee47)

**Comment by twistios** [comment]
The notification color does not change for me, maybe because of dark mode.
It seems that JeePopuwu understood the problem as it beeing inside the player, but the notification is not in the player.
Isn't the notification managed by Android?

**Comment by Alexander743286** [comment]
No sé sobre Android creo que tengo el 12
Pero nomás le digo que agregan una configuración para que la aplicación
modifique el color de la notificación de acuerdo al álbum o la canción que
esté sonando
