### ISSUE TITLE
incomplete albums

### ISSUE THREAD

**Issue by ifz5** [fast4x/RiMusic#3451]
### Steps to reproduce the bug

There are albums that are missing songs, they are not complete.

### Expected behavior

I've noticed that in Bryan Adams' discography there are incomplete albums. Maybe there are more artists who don't have complete albums.

### Actual behavior

Artists' albums should be complete.

### Screenshots/Screen recordings

![Screenshot_2024-08-27-23-31-04-724_it fast4x rimusic](https://github.com/user-attachments/assets/cfecc147-d29a-4120-a42b-87793a99ac66)
For example, this album is missing songs.

### RiMusic version

0.6.49.2

### Android version

Android 13

**Comment by fast4x** [comment]
Another example please?

**Comment by ifz5** [comment]
![Screenshot_2024-08-28-09-22-04-954_it fast4x rimusic](https://github.com/user-attachments/assets/2a06f40e-44c6-43d8-b479-98b0123cc63c)
![Screenshot_2024-08-28-09-20-00-444_it fast4x rimusic](https://github.com/user-attachments/assets/1d74be2f-e536-42ae-bbf8-a4f953ec489b)
And I think I've seen more...
