### ISSUE TITLE
Playlist deleted

### ISSUE THREAD

**Issue by jairdm97** [fast4x/RiMusic#3454]
### Steps to reproduce the bug

I have not idea, one Day Just saw my playlist are deleted

### Expected behavior

This should happen: When I oush playlist option, should be around 5 diferente playlist 

### Actual behavior

Mi playlist are deleted

### Screenshots/Screen recordings

![Screenshot_20240827_233733_it fast4x rimusic](https://github.com/user-attachments/assets/751dfa32-0225-4e23-b2ec-dbe5499f3836)

### RiMusic version

0.1.5

### Android version

Android 12

### Additional information

.

**Comment by fast4x** [comment]
upgrade your version to latest please
