### ISSUE TITLE
Albums error

### ISSUE THREAD

**Issue by N0be84** [fast4x/RiMusic#3456]
### Steps to reproduce the bug

I can't see the songs of some albums or even the picture
![Screenshot_2024-08-28-11-43-33-169_it fast4x rimusic](https://github.com/user-attachments/assets/07b285c6-7b56-49e9-955a-9391b9fa2586)

### Expected behavior

See the songs inside the albums

### Actual behavior

Can't see the songs inside the albums

### Screenshots/Screen recordings

![Screenshot_2024-08-28-11-43-33-169_it fast4x rimusic](https://github.com/user-attachments/assets/85707148-df1b-466e-a3e7-151fa2cd3b09)

### RiMusic version

0.6.58

### Android version

Android 14

**Comment by twistios** [comment]
Version 0.6.58 does not exist yet so I assume it is 0.6.48.
Please first update to latest version (currently 0.6.49.1 or 0.6.49.2), then please report back if it is solved.
