### ISSUE TITLE
Vi Music interface showing when Ri Music Interface selected

### ISSUE THREAD

**Issue by Patronza** [fast4x/RiMusic#3459]
### Steps to reproduce the bug

1. Went to settings... User Interface
2. Selected Interface in Use: Vi Music. Vi Music mode activates as normal with menus on left side of screen.
3. Select Ri Music again and does not change back to menus on the bottom.
4. Have closed app, restarted phone, cleared cache.

### Expected behavior

User interface should go back to Ri Music look with text and menu items facing normal left to right orientation.

### Actual behavior

Stays on Vi Music interface with menus on left side of screen.

![Screenshot_20240828-220623](https://github.com/user-attachments/assets/bf0f7c7b-3e21-4f1c-9d92-0813a1225694)

### Screenshots/Screen recordings

![Screenshot_20240828-215511](https://github.com/user-attachments/assets/8447b4c4-c899-4f41-adcf-8319c10cf015)

### RiMusic version

0.6.49.1

### Android version

14

**Comment by fast4x** [comment]
When change ui mode, the settings are reset
