### ISSUE TITLE
Search a song should be in middle

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#346]
### Description

Search a song text should be in middle right just before quick picks

https://github.com/fast4x/RiMusic/assets/120176369/fe3f7b61-7667-40fb-8390-ee017351d6a8

### Suggested Solution

It will make the app more finished

**Comment by fast4x** [comment]
So the search field should also be centered, it's correct?

**Comment by Logan7899** [comment]
> So the search field should also be centered, it's correct?

I am just asking if you can do it

**Comment by fast4x** [comment]
Of course, I was just asking you to confirm if I understood correctly.

**Comment by fast4x** [comment]
Improved, available from now version 0.6.16.1
