### ISSUE TITLE
All songs that I listen are automatically downloaded.

### ISSUE THREAD

**Issue by aevern** [fast4x/RiMusic#3461]
### Steps to reproduce the bug

I listen to a song that I have not yet downloaded. This causes the song to be automatically downloaded and added to the downloads page.

### Expected behavior

I listen to the song and it is only stored in the cache. It is only permanently downloaded if i manually do this.

### Actual behavior

All songs I listen to for almost it's entirety are downloaded and added to the downloads page.

### RiMusic version

0.6.48 and 0.6.49.2

### Android version

android 14

### Additional information

I've already tried uninstalling and reinstalling, but the issue persists. 
I've been having this issue for the last few versions of the app.

**Comment by twistios** [comment]
Downloading and Caching is actually almost the same. This is the reason why downloaded and cached section are now united.
A song is automatically cached if you listen to a song for long enough. You can restrict how many songs get cached by changing the storage limit for it in the settings. If then there are too many songs, the least recently listened song gets replaced by the new song.

**Comment by aevern** [comment]
I understand that downloading and caching is practically the same thing. The problem is mostly that they are added to the downloads page and I don't know if they will still be replaced (as the normal caching entails) or if they are accidentality added to the downloads list that doesn't get replaced.

**Comment by twistios** [comment]
If you want that no cached song gets deleted, you can set the storage limit to unlimited (or what ever works for you) such that it then behaves mostly like downloaded. To make it even more like downloaded, change the cache location to private cache (this settings change will delete all current cached songs).
If you do not like, that it gets automatically cached, you should open a feature request.

**Comment by twistios** [comment]
As far as I remember, cached and downloaded list are internally distinct, so cached songs belong to cache and downloaded to downloaded.

**Comment by twistios** [comment]
If the song gets added to the downloaded tab while listening, then most likely it got cached.

**Comment by aevern** [comment]
Ok, I think I understand.
Thank you for the quick replies.
