### ISSUE TITLE
App Crashing 

### ISSUE THREAD

**Issue by Sankeerthan13** [fast4x/RiMusic#3464]
### Steps to reproduce the bug

Enqueue some songs and open the Queue . Try to change the playing order or position of a Song in the Queue

### Expected behavior

Song's position or playing order must Change as adjusted.

### Actual behavior

App Closes itself and takes you to Home screen.

### Logs

2024-08-29T00:16:12.617:	java.lang.NoSuchMethodError: No virtual method removeFirst()Ljava/lang/Object; in class Ljava/util/ArrayList; or its super classes (declaration of 'java.util.ArrayList' appears in /apex/com.android.art/javalib/core-oj.jar)
	 V5.a.a(SourceFile:1) 
	 A1.d.b(SourceFile:90) 
	 V5.i.u(SourceFile:101) 
	 g7.a.i(SourceFile:9) 
	 z7.J.run(SourceFile:113) 
	 J0.d0.h0(SourceFile:7) 
	 J0.c0.doFrame(SourceFile:10) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1449) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1089) 
	 android.view.Choreographer.doFrame(Choreographer.java:998) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431) 
	 android.os.Handler.handleCallback(Handler.java:942) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8296) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) 

### RiMusic version

v0.6.49.2

### Android version

Android 13

**Comment by fast4x** [comment]
Duplicate #3462
it's fixed and available from version 0.6.50
