### ISSUE TITLE
About tab for albums/Singles

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#347]
### Description

I have seen this in innertune where each albums/singles were provided with information from Wikipedia 
![Polish_20240108_085322166](https://github.com/fast4x/RiMusic/assets/120176369/7a3b28d2-7c9c-4afa-a4a9-a3fceb4cd70d)

### Suggested Solution

If you can please add this feature 

### Additional Context

I have done little bit of Photoshop to demonstrate how would it look like

**Comment by fast4x** [comment]
Nice, I check the possibility of inserting it. Thanks

**Comment by fast4x** [comment]
I haven't found this feature...

**Comment by 25huizengek1** [comment]
YouTube has had descriptions for albums, but a few weeks ago they started disappearing and I'm pretty sure they removed them entirely.

**Comment by 25huizengek1** [comment]
Scratch that they are there again... (even in the official app)

**Comment by fast4x** [comment]
Yes, i see empty description.

**Comment by 25huizengek1** [comment]
@fast4x Here is an example:

![image](https://github.com/fast4x/RiMusic/assets/50515369/07e958c2-1092-4f5a-b191-4f7d031ab344)

**Comment by fast4x** [comment]
oh yes

**Comment by fast4x** [comment]
@25huizengek1  Found in album browseId not in playlistpage...

Available from version 0.6.33

**Comment by fast4x** [comment]
Implemented, available from version 0.6.34
