### ISSUE TITLE
Consecutive playback fails consistently

### ISSUE THREAD

**Issue by lake-effect** [fast4x/RiMusic#3473]
### Steps to reproduce the bug

1. Install latest version
2. Search an artist
3. Follow an artist
4. Play an album from that artist

### Expected behavior

1. Album should play in sequence 

### Actual behavior

1. First song plays (sometimes)
2. Second song does not play
3. "Unknown error" or "The returned id was not the same as the one requested" is reported

### Screenshots/Screen recordings

![Screenshot_20240828-191749](https://github.com/user-attachments/assets/37a30e47-b162-4988-917a-98960ffeb69d)
Screenshot of the "id returned is different than the one requested" error

### Logs

[RiMusic log a07a6a90f427.txt](https://github.com/user-attachments/files/16792100/RiMusic.log.a07a6a90f427.txt)

### RiMusic version

6.49.1

### Android version

Android 14

**Comment by twistios** [comment]
I have tried with the same album and it worked fine. Also the song on the screenshot is not the second song of the album (I have started with the first song).

**Comment by lake-effect** [comment]
It doesn't matter if it's the second song, it's any consecutive song play. Force quit + restarting the app allows for playback again, but then the error recurs the next time a new track is requested.

I don't know why it works for you, but as you can see from the logs, it clearly doesn't work.

Maybe this is a clue?

```
08-29 02:30:53.478 22615 22670 I System.out: mediaItem requests Player response PlayerResponse(playabilityStatus=PlayabilityStatus(status=LOGIN_REQUIRED), playerConfig=null, streamingData=null, videoDetails=null)
08-29 02:30:53.880 22615 24287 E LoadTask: Unexpected exception loading stream
08-29 02:30:53.880 22615 24287 E LoadTask:   C6.t0
```

**Comment by fast4x** [comment]
Login required... this is the error

**Comment by twistios** [comment]
Why does it require login for this person and not for me @fast4x?

**Comment by fast4x** [comment]
I don't know

**Comment by lake-effect** [comment]
Is this something where Google thinks my traffic is suspicious, or I should be in a different region or something?

**Comment by fast4x** [comment]
At the moment I can’t answer you, but I will improve the log so that we understand the causes of the problem. Be patient.

**Comment by lake-effect** [comment]
Just a quick update: as of yesterday the problem spontaneously resolved. I suspect that Google was simply restricting my requests for some reason.
