### ISSUE TITLE
Reorder song

### ISSUE THREAD

**Issue by notaiva** [fast4x/RiMusic#3475]
### Steps to reproduce the bug

Play any song
Then reorder one of the song

### Expected behavior

Can play when reordering song

### Actual behavior

Crash

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/f31a0ed3-d158-41b6-a38c-7291bc1e8af6

### RiMusic version

0.6.49.2

### Android version

Android 14

**Comment by twistios** [comment]
Duplicate of #3403.
The fix will be available from next version 0.6.50.
