### ISSUE TITLE
Reproducción aleatoria en rimusic

### ISSUE THREAD

**Issue by eriftuygh** [fast4x/RiMusic#3479]
### Steps to reproduce the bug

Quer activar reproducir aleatoriamente 

### Expected behavior

Pongo una canción ,pongo reproducción aletoria y no funciona

### Actual behavior

No podía desactivarlo ,pero no estaba funcional 

### Screenshots/Screen recordings

Siempre activado 
![Screenshot_20240829-062913](https://github.com/user-attachments/assets/bf3588ed-d225-4916-aa22-501d1d21fdf5)

### RiMusic version

V0.6.49.2.by fast4x

### Android version

12

**Comment by fast4x** [comment]
Shuffle is one time click, in the future will be developed new shuffle mode
