### ISSUE TITLE
Latest version 0.6.49.2 is missing on Accrescent

### ISSUE THREAD

**Issue by neunzehnachtneun** [fast4x/RiMusic#3480]
### Steps to reproduce the bug

1. Open accrescent
2. Tap Rimusic
3. See only available version is 0.6.49.1

### Expected behavior

Version 0.6.49.2 should be available via Accrescent.

### Actual behavior

Version 0.6.49.2 is missing, while it is available via IzzyOnDroid.

### RiMusic version

0.6.49.1

### Android version

Android 14

### Additional information

Accrescent 0.23.0

**Comment by twistios** [comment]
0.6.49.2 is not a normal update, see #2179 (i.e. [here](https://github.com/fast4x/RiMusic/issues/2179#issuecomment-2308444207)).
