### ISSUE TITLE
[Bug] The action bar is off-screen in landscape mode on a tablet

### ISSUE THREAD

**Issue by SomebodyYouProbablyDontKnow** [fast4x/RiMusic#3484]
### Steps to reproduce the bug

1. Play any song on a Tablet in landscape mode
2. The action bar will be off-screen

### Expected behavior

The action bar is within the screen and accessible

### Actual behavior

The action bar is outside the screen and mostly inaccessible

### Screenshots/Screen recordings

![actionbarbug](https://github.com/user-attachments/assets/7094343f-0729-41d8-a802-d1a74b53b172)
![actionbarbug2](https://github.com/user-attachments/assets/4de88e44-47c7-4088-8a10-aa9b1ac61a4a)

### RiMusic version

0.6.49.2

### Android version

Android 12

### Additional information

You can barely see it at the bottom of the screen

**Comment by aneesh1122** [comment]
Are you using a tablet? Try modern player

**Comment by faustaahmad** [comment]
I'm not using tablet, but some buttons are inaccessible in landscape orientation including the action bar (next queue visible)

Overlapping with navbar, could use gesture as workaround
![](https://github.com/user-attachments/assets/3f57cde4-5d00-4d96-8888-7ece63c3fb6b)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.54
