### ISSUE TITLE
Add Widgets

### ISSUE THREAD

**Issue by AXN-Developers** [fast4x/RiMusic#3485]
### Description

Sugiero que para la próxima actualización añadan widgets del reproductor.

### Suggested Solution

-

### Alternatives

-

### Additional Context

-

**Comment by twistios** [comment]
It seems we now have ~14 widget requests.

**Comment by fast4x** [comment]
We try to develop... lol

**Comment by ALMIGHTY-VC** [comment]
> It seems we now have ~14 widget requests.

Time to combine all of them in a discussion to get on everyone's same side

**Comment by ALMIGHTY-VC** [comment]
> > It seems we now have ~14 widget requests.
> 
> Time to combine all of them in a discussion to get on everyone's same side about the designs and also for suggestions

**Comment by fast4x** [comment]
Implemented available from version 0.6.51

**Comment by ALMIGHTY-VC** [comment]
:0h thats fast🚴三
