### ISSUE TITLE
I was kicked out of the telegram group

### ISSUE THREAD

**Issue by DavidDiaz377** [fast4x/RiMusic#3487]
### Steps to reproduce the bug

As soon as the new version came out, I found out about the existence of the Telegram group, which I joined. Within a minute of joining, and without violating ethical standards of behavior, an administrator expelled me.

### Expected behavior

I would like to join again, since I usually like to stay informed about all the news about the app, and I consider the telegram group to be a great source of learning.

### Actual behavior

.

### Screenshots/Screen recordings

.

### Logs

.

### RiMusic version

. 

### Android version

.

### Additional information

Thank you very much for reading, I hope this can be resolved, and my apologies for filing it as a bug, I couldn't find a more suitable way to make my statement.

**Comment by twistios** [comment]
If you are the . user, then this is why.

**Comment by DavidDiaz377** [comment]
I am the user .
Sorry, I didn't want to pretend to be a troll. My username is "." because I care about my security when entering the various groups on Telegram. I never wanted my username to be misinterpreted, it is only for the reason mentioned above. I remain at the disposal of what you tell me regarding the username. I'm sorry fast4x, developers and the rest of the community.

**Comment by fast4x** [comment]
try again please

**Comment by DavidDiaz377** [comment]
I try again and the message "it seems that this chat does not exist" continues. Dear fast4x, I would not like to bother you with such an inconvenience, if I cannot log in again it is not a problem, and I still thank you for everything you have done.

**Comment by fast4x** [comment]
I'll try to unbun but your username isn't recognized like good

**Comment by DavidDiaz377** [comment]
My username is no longer "." It is now "DLD"

**Comment by fast4x** [comment]
Great!

**Comment by fast4x** [comment]
> My username is no longer "." It is now "DLD"

Join thw group

**Comment by DavidDiaz377** [comment]
Thanks fast4x! Sorry for the time spent on my inconvenience, I appreciate everything you have done.
