### ISSUE TITLE
Error: ui del sistema 

### ISSUE THREAD

**Issue by Nain504** [fast4x/RiMusic#3488]
### Steps to reproduce the bug

Al reproducir una canción, por primera vez al entrar a la app, aparece el error del sistema "ui del sistema sea detenido" al abrir la app otra vez no vuelve a suceder, hasta que se reinicia la app

### Expected behavior

Escuchar una canción sin que aparezca ese error

### Actual behavior

El marcado anteriormente

### RiMusic version

v0.6.50

### Android version

Android 12

### Additional information

Mi dispositivo es un Motorola E22

**Comment by fast4x** [comment]
Enable debug in miscellaneous settings, restart app and paste here the log please
