### ISSUE TITLE
RiMusic Video

### ISSUE THREAD

**Issue by Jetliarm** [fast4x/RiMusic#3489]
### Steps to reproduce the bug

When I try to play videos in a playlist, the videos don’t start playing automatically. I have to open the options, and the video pops up instead of just playing on its own. The videos should automatically play one after the other once the playlist starts.

### Expected behavior

it should automatically play video 

### Actual behavior

.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/1724571a-67ca-40af-96d3-3a2caae8ae65

### RiMusic version

0.6.50

### Android version

Android 13

**Comment by fast4x** [comment]
Actually video is an option of a song...
