### ISSUE TITLE
Fondo degradado dinámico y cola de reproducción.

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#3490]
### Steps to reproduce the bug

Solamente es un pequeño error pero en lo personal es algo molesto, al seleccionar "Fondo degradado dinámico del tema o portada" el reproductor marcha bien pero al momento de seleccionar la cola de reproducción y bajar para indagar alguna canción tiene constante congelamiento sin embargo selecciono otro tema y el congelamiento se desaparece por completo, no tendría problemas con esto pero el reproductor se ve simple.

### Expected behavior

N/A

### Actual behavior

N/A

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/87cf0bcd-68d5-4126-8b2c-6c86f1054863

https://github.com/user-attachments/assets/b97cf7ef-2bb1-4460-89c2-8ec1dbf73117

### Logs

N/A

### RiMusic version

0.6.50

### Android version

Android 14 

### Additional information

Espero puedan solucionar este pequeño detalle 😿

**Comment by fast4x** [comment]
Ok ill check it
