### ISSUE TITLE
Only one song in for you section

### ISSUE THREAD

**Issue by frenchy82** [fast4x/RiMusic#3492]
### Steps to reproduce the bug

Open rimusic in for you section there is Only one song

### Expected behavior

This section should have several songs

### Actual behavior

As description 

### RiMusic version

0.6.50

### Android version

Android 12

**Comment by twistios** [comment]
I think fast4x fixed that already. Maybe available today with custom version or with next version 0.6.51.

**Comment by fast4x** [comment]
Fixed, download custom version please.
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by frenchy82** [comment]
Thanks, works great now

**Comment by fast4x** [comment]
perfect
