### ISSUE TITLE
In impostazioni "Altro" chiude l'app.

### ISSUE THREAD

**Issue by Steu1981** [fast4x/RiMusic#3496]
### Steps to reproduce the bug

1. Menu impostazioni (settings)
2. Altro (other)

### Expected behavior

Dovrebbe aprirsi il menù "altro"

### Actual behavior

Invece l'app va in crash e si chiude.

![Screenshot_2024-08-31-17-28-45-016_it fast4x rimusic-edit](https://github.com/user-attachments/assets/fe6269c9-49b4-4bf3-aca6-758c78af7346)

### Logs

![Screenshot_2024-08-31-17-40-20-291_com miui bugreport-edit](https://github.com/user-attachments/assets/a1252770-7307-496b-a73f-66064273cc3d)

### RiMusic version

0.6.50

### Android version

Android 14

### Additional information

Hyper OS by Xiaomi

**Comment by fast4x** [comment]
Your security file is corrupted, must reinstall.

**Comment by Steu1981** [comment]
Grazie 👍🏻

Il sab 31 ago 2024, 20:53 Rino Russo ***@***.***> ha scritto:
