### ISSUE TITLE
Can't see anything with the new UI

### ISSUE THREAD

**Issue by BoneMarrow10** [fast4x/RiMusic#3499]
### Steps to reproduce the bug

Choose any music with white art cover

### Expected behavior

I can read all the UI element without it clashing with the art cover

### Actual behavior

I can't see anything

### Screenshots/Screen recordings

![Screenshot_20240901-014510](https://github.com/user-attachments/assets/326f0a24-069d-45d7-9780-a30e66896e74)

### RiMusic version

0.6.50

### Android version

Android 12

**Comment by fast4x** [comment]
Go to appearance settings and set as you prefer

**Comment by aneesh1122** [comment]
Enable action bar gradient

**Comment by veloal** [comment]
_It allowing the user to customize it at will_

examples with the same configuration.
white and black covers

![Screenshot_20240903_004615_it fast4x rimusic](https://github.com/user-attachments/assets/b13efbc0-f7bb-4cf5-854a-4dd894ad233d)
![Screenshot_20240903_004603_it fast4x rimusic](https://github.com/user-attachments/assets/96a4a815-9be0-45ec-b740-aa29bf1fc4a5)
