### ISSUE TITLE
[Feature]: Select songs to add to the queue / bookmark / playlist

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#35]
### Description

Select individual songs to add to the queue from an album / artist.

### Suggested Solution

Long press to display the bar (Start radio etc.) and in it select Check item to display 🔲 and mark ✅ the ones we want and then confirm with the icon (#34) / bookmark / playlist / ♥️ (top right).

**Comment by fast4x** [comment]
Implemented, available from version 0.6.15
