### ISSUE TITLE
[Feature]: Notification of updates differently

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#350]
### Description

I think it's confusing when the settings icon changes when an update is available.

### Suggested Solution

It would be great if it was possible to turn on/off update notifications in the settings.

With app notifications turned on, the notification would pop up when the app is launched and clicking on it would take one to the settings - About where the New Version... would be as it is now.

If the app wasn't updated there was always a bar in the settings - About, but no update bar appeared in the other settings tabs and no update notification has appeared when notifications are turned off.

### Alternatives

A different way of notifying of updates than changing the icon.

### Additional Context

In version 0.6.15.1 icon is different than in issue #264 which is even more confusing.

**Comment by fast4x** [comment]
Yes, you are right the current is not the correct solution.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.20
