### ISSUE TITLE
Play buttons are not displayed with the "Essential" control style and with the gradient background color options

### ISSUE THREAD

**Issue by FixItKit** [fast4x/RiMusic#3501]
### Steps to reproduce the bug

1. Set the control style to "Essential"
2. Set the background colors to "Gradient from song cover" or "Gradient from theme"
3. Select a play button.
4. Go to the player.
Switch the song if the play button is visible.

### Expected behavior

The play buttons should be displayed.

### Actual behavior

The play buttons aren't displayed. Only the pause icon is shown for any of them.

### RiMusic version

0.6.50

### Android version

Android 13

**Comment by fast4x** [comment]
Send a screenshot or mini video please

**Comment by aneesh1122** [comment]
> > Send a screenshot or mini video please
> 
> I updated the steps to reproduce the bug.

Play button is properly visible for me. You'll have to upload a screenshot or recording if you want it to be fixed
