### ISSUE TITLE
RiMusic freezes when swiping down in the queue

### ISSUE THREAD

**Issue by FixItKit** [fast4x/RiMusic#3502]
### Steps to reproduce the bug

Make sure swiping down is enabled.
1. Open any song
2. Open the queue
3. Swipe down the song

### Expected behavior

The app should not freeze.

### Actual behavior

The app freezes.

### RiMusic version

0.6.50

### Android version

Android 13

**Comment by fast4x** [comment]
Upload a video please

**Comment by fast4x** [comment]
How many songs have in your queue?

**Comment by fast4x** [comment]
Yiu are sure that isn't your device?
