### ISSUE TITLE
Disable Floating Search Button Not Working

### ISSUE THREAD

**Issue by Conqueror666** [fast4x/RiMusic#3503]
### Steps to reproduce the bug

shown in video

### Expected behavior

shown in video

### Actual behavior

shown in video

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/a1d74361-5588-450f-9c95-3a4cdbb86397

### RiMusic version

newest version 

### Android version

14

**Comment by fast4x** [comment]
Fixed, avalable from version 0.6.51
