### ISSUE TITLE
There is a bug when opening the artist album, it freezes and does not show the album with the songs

### ISSUE THREAD

**Issue by Yordi10000** [fast4x/RiMusic#3505]
### Steps to reproduce the bug

click on album

### Expected behavior

All the songs that belong to said album should be shown

### Actual behavior

it freezes and does not show the album songs

### Screenshots/Screen recordings

![Screenshot_2024-08-31-21-02-11-701_it fast4x rimusic](https://github.com/user-attachments/assets/778272c9-7bcb-4fce-81e4-fe6e599c563e)

### RiMusic version

0.6.48

### Android version

14

**Comment by fast4x** [comment]
Use latest version it's just fixed
