### ISSUE TITLE
Album cover

### ISSUE THREAD

**Issue by LhAlaniz** [fast4x/RiMusic#3506]
### Steps to reproduce the bug

Save album to favorites

### Expected behavior

The album was saved correctly but then the cover was deleted, and now when I search for a new album the cover and the songs do not appear either.
![Screenshot_20240831_210951 (1)](https://github.com/user-attachments/assets/72f86d12-5c34-4f35-9dd5-1ad58ce926ab)

### Actual behavior

It plays individual songs fine, and also displays the song art, but it doesn't work with albums.
![Screenshot_20240831_210951 (1)](https://github.com/user-attachments/assets/6104a533-d22f-4162-a2b2-53d755f75001)

### RiMusic version

6.47.1

### Android version

Android 14

### Additional information

My Internet is very good and fast with a capacity of 100 Mbps

**Comment by fast4x** [comment]
Use latest version it's just fixed
