### ISSUE TITLE
Pressing the previous track in the notification and from Bluetooth device should play the track from the beginning 

### ISSUE THREAD

**Issue by jksekai** [fast4x/RiMusic#3507]
### Description

In the newer version, pressing the previous track button from the notification directly plays the previous track in the queue, while it is its purpose, changing it to play track from beginning on first press and then pressing it again to switch the track would be an improvement. 
![InShot_20240901_132537652](https://github.com/user-attachments/assets/c791c7ce-0cbd-4c43-a8a4-ddcad5bcc3a5)

### Suggested Solution

It would be better if it played the current track from beginning when pressing previous button, and pressing it again should finally take it to the previous track (previously only before the song progressed to around 5 seconds) 

### Alternatives

adding a special backward or rewind button could solve the issue as well, but it might not solve previous track playing from a Bluetooth device control (earphones) 

### Additional Context

this feature already existed but was changed in v0.6.49.1

**Comment by fast4x** [comment]
It's normal, go to previous when listen time is short

**Comment by jksekai** [comment]
> It's normal, go to previous when listen time is short

the goes to the previous track no. matter how much the song has been listened

**Comment by fast4x** [comment]
What should you want?

**Comment by jksekai** [comment]
> What should you want?

**Comment by jksekai** [comment]
> What should you want?

! [player example ] (https://github.com/user-attachments/assets/2fac0684-8f72-463d-80ea-6b3d25b7ccbe)
when the song has progressed enough (around more than 5 seconds) pressing the previous should play the track from beginning, pressing previous twice or if the music hasn't progressed over 5 seconds it should take it to the previous track.
