### ISSUE TITLE
When searching for a song the music section does not work

### ISSUE THREAD

**Issue by PIXIE-KEVIN** [fast4x/RiMusic#351]
### Steps to reproduce the bug

When searching for a song and going to the videos section it does not load. Also calling that section videos in Spanish is wrong, it would be better to put YouTube or something like that.

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

![Screenshot_20240108-025734](https://github.com/fast4x/RiMusic/assets/30191559/38202b77-0219-4ad1-baf2-61c1929bede2)

### RiMusic version

0.6.16

### Android version

Android 12

### Additional information

That is one of the important functions of the app, that video section. Please fix it, thanks in advance

**Comment by ikanakova** [comment]
duplicity to #328

**Comment by fast4x** [comment]
Fixed, available from version 0.6.18
