### ISSUE TITLE
Error la music se cambio sola sin razon

### ISSUE THREAD

**Issue by Spectre-lives** [fast4x/RiMusic#3510]
### Steps to reproduce the bug

El error me aparece asi pense que tenia algo activado pero no cuando estoy en el modo escuchar music se cambia sola al sonar la music en los minutos 7,8,9 o menos y eso que no tiene activado la opcion de agitar para cambiar de music ni la opcion de volumen de cambio de music

### Expected behavior

La music se reprodusca normal sin cambiarse de music almenos que que termine 

### Actual behavior

La music apenas va en el minuto 7,8,9 o menos y ya cambia por si solo esto sucede con todas las music q escucho 

### Screenshots/Screen recordings

![SmartSelect_20240901_083640](https://github.com/user-attachments/assets/0ad9074b-e215-45d5-a62c-b0c95a9f7b2b)

En ese modo cambia 

### Logs

No incluye otro solo e visto ese error

### RiMusic version

"0.6.50

### Android version

Android 12 

### Additional information

Cambia sin tener activado el modo agitar para cambiar

**Comment by fast4x** [comment]
maybe you have Medley mode enabled, hold play button and click on hourglass

**Comment by Spectre-lives** [comment]
@fast4x gracias parcero ya se me soluciono en la buena y sigue asi con la app. esta re mela la verdad con con cada actualizacion van mejorando.😃
