### ISSUE TITLE
Problemas reproducción de Álbumes 

### ISSUE THREAD

**Issue by 1RobinGOD** [fast4x/RiMusic#3512]
### Steps to reproduce the bug

Diríjase a cualquir álbum de cualquier artista, y el problema es que el álbum no carga ninguna canción, comprobé mi conexión a interner y ese no es el problema.

### Expected behavior

Debería de cargar cualquier álbum 

### Actual behavior

Esto ocurrió en lugar en cargar los álbumes de manera correcta.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/0878cd20-dd28-44cc-9a85-869013b2a9fc

### RiMusic version

0.6.48

### Android version

Android 11

**Comment by fast4x** [comment]
update to the latest version it's just fuxed
