### ISSUE TITLE
No me aparecen las recomendaciones de la última canción que he escuchado

### ISSUE THREAD

**Issue by Vic931** [fast4x/RiMusic#3514]
### Steps to reproduce the bug

1.Abrí mi app de RiMusic
2. En el apartado "Selecciones rápidas"

### Expected behavior

Esperaba que mostrase las canciones recomendadas para así escucharlas, en la anterior versión a esta nueva si aparecían. 

### Actual behavior

Me aparece un espacio en negro donde deberían estar las canciones recomendadas y no puedo verlas, y eso que tengo las opciones activas para que sean visibles. 

### Screenshots/Screen recordings

![Screenshot_20240901_181117_it fast4x rimusic](https://github.com/user-attachments/assets/5a5a3c1d-b09e-4a56-8ce4-af11fe831b94)

### RiMusic version

0.60.50

### Android version

Android 12

### Additional information

Apartir de la versión recién lanzada 0.60.50 no me aparecen las recomendaciones de canciones y antes de esta versión si aparecían, estaría fenomenal que lo arreglaran☝🏻

**Comment by fast4x** [comment]
Download custom version it's just fixed and available from version 0.6.51

**Comment by Vic931** [comment]
Donde puedo encontrar la versión 0.6.51? Porque no me aparece -------- Mensaje original --------De: Rino Russo ***@***.***>Fecha: lun., 2 de septiembre de 2024 1:00 a. m.Para: fast4x/RiMusic ***@***.***>CC: Vic931 ***@***.***>, Author ***@***.***>Asunto: Re: [fast4x/RiMusic] No me aparecen las recomendaciones de la última canción que he escuchado (Issue #3514)
Download custom version it's just fixed and available from version 0.6.51

**Comment by fast4x** [comment]
0.6.51 will be available next Friday 
Now can download custom version with many fix.

https://github.com/fast4x/RiMusic/tree/master/customVersion
