### ISSUE TITLE
Recopilación de canciones anual

### ISSUE THREAD

**Issue by Vic931** [fast4x/RiMusic#3515]
### Description

Soy nuevo en RiMusic y no se si exista la opción que te dice todo una recopilación de las canciones, artistas o álbumes que has escuchado cada año, en esos meses de diciembre,  es algo como Spotify tiene implementado (Spotify Wrapped) . Estaría genial que lo agregarán en caso de que no esté (o amenos qué ya esté, repito soy nuevo). 

### Suggested Solution

Solo es una sugerencia que haría más atractiva la app✨

### Alternatives

N/A

### Additional Context

N/A

**Comment by fast4x** [comment]
Hi there is a monthly playlist.

**Comment by twistios** [comment]
And there also is the statistics menu.
