### ISSUE TITLE
Función de cuenta asociada

### ISSUE THREAD

**Issue by Jhuvert** [fast4x/RiMusic#3516]
### Description

Saludos mis estimados ante todo quiero decir que es una excelente aplicación pero deberían de dar la opción de poder agregar alguna cuenta preferiblemente asociada al Gmail para que se guarde el historial de cada quien preferiblemente el de Youtube para que sea más cómodo encontrarse las canciones que uno normalmente escucha y así hacer que sea más intuitiva la app sin más que agregar me despido

### Suggested Solution

Solo la de agregar una cuenta que guarde el historial de los gustos de cada usuario

**Comment by fast4x** [comment]
Login with YouTube isn't planned, can use piped account for sync.
