### ISSUE TITLE
Multiple Bugs Found : Songs can't be found more on Artist and Video Mode is entirely broken

### ISSUE THREAD

**Issue by SUFandom** [fast4x/RiMusic#3519]
### Steps to reproduce the bug

For Artist Music Page issue

1. Open RiMusic
2. Search any artist song that has way more songs, visit 
3. Check their song libraries, scroll down until to the bottom just loading and stuck

For video:
1. Find music video (any)
2. Select a music video
3. Try to minimize

### Expected behavior

Music Page issue:

I can freely scroll down until the end of the song list that the singer made

Videos: I can freely play video easily and switch back easily to music

### Actual behavior

Music issue:

Loading stuck, can't load other songs

Videos:

Sometimes can clip or doesn't play, or sometimes would skip to a certain time frame (it's random)

### RiMusic version

0.6

### Android version

Android 14

### Additional information

Config is on Private, cache cleared, even data cleared

**Comment by postcanonical** [comment]
probably YouTube started to block API calls sonehow.

**Comment by twistios** [comment]
The "just loading and stuck" issue is already known but I for example have not yet investigated the cause. The number of songs before it stops loading is 100.

**Comment by twistios** [comment]
Also please add full version code, as 0.6 is not very useful on it's own.

**Comment by SUFandom** [comment]
oh sorry, its `0.6.50`

**Comment by twistios** [comment]
Currently the app Version code only changes on the 3rd (or 4rd if existing) position.
