### ISSUE TITLE
[Feature]: add a dislike button 

### ISSUE THREAD

**Issue by Jgth6** [fast4x/RiMusic#3523]
### Description

It would be nice to add a dislike button 

### Suggested Solution

It would be useful so you don't have to listen to the song you don't like because the algorithm recommend it

**Comment by fast4x** [comment]
Implemented available from version 0.6.56

**Comment by haernerdy** [comment]
Hello! I'm not able to locate the dislike button that was implemented. Great job, by the way! 👏

**Comment by fast4x** [comment]
dislike it's same button... like, disllike, remove
