### ISSUE TITLE
Deberian borrar 

### ISSUE THREAD

**Issue by Maycoljhustyn** [fast4x/RiMusic#3525]
### Description

Cada vez que abro la pestaña videos se sale y me envia a youtube

### Suggested Solution

Yo sugiero que borren eso de que se salga y me ponga el video de youtube a lo de antes 
Osea
Que solo la musica y no el video despues de todo la app es para escuchar musica no para ver videos

**Comment by JeePopuwu** [comment]
Lo de video es opcional en ajustes

Y borrar una característica que sirve no ayuda mucho
