### ISSUE TITLE
Arreglar la cola

### ISSUE THREAD

**Issue by Noeliiarp26** [fast4x/RiMusic#3527]
### Description

Me gustaría que arreglarais la cola de las canciones. Cuando le doy a poner a la cola no se pone exactamente la siguiente canción. Estaría bien que después se reproduciera está y después continúe.

### Suggested Solution

K

**Comment by JeePopuwu** [comment]
Supongo que te refieres la cola tipo Spotify.

La cola de esa y está son diferentes porque cuando pones reproducir siguiente, literalmente se pone la que tú pones en reproducir siguiente

**Comment by SharkyBeAre** [comment]
Simplemente tienes que darle a iniciar radio, aunque si estaría muy buena una opción de que automáticamente se inicie la radio
