### ISSUE TITLE
Video 

### ISSUE THREAD

**Issue by Alanpa1** [fast4x/RiMusic#3528]
### Description

Video playing should be shown on thumbnail..
Now when I open player of video it don't show Control button and timeline bar ..

### Suggested Solution

..

### Alternatives

.

### Additional Context

.

**Comment by fast4x** [comment]
Send a screenshot or video please

**Comment by Alanpa1** [comment]
When I play from video it redirect me to YouTube to play video..
So my suggestion is if we play video then it should be play on thumbnail area ..it would be nice👍👍

**Comment by Alanpa1** [comment]
Uploading screen-20240903-135101 (1).mp4…

**Comment by Alanpa1** [comment]
https://github.com/user-attachments/assets/a03c99bc-dbae-449e-9f42-6c3b75f9aac3

**Comment by fast4x** [comment]
video not uploaded is in error

**Comment by Alanpa1** [comment]
Video I uploaded

**Comment by fast4x** [comment]
Yes video visible now, thumbnail isn't correct location, because it can be disabled and not permit full screen view when rotate device.
In the future maybe it can improved but not for now, thanks.
