### ISSUE TITLE
random album outside of your albums

### ISSUE THREAD

**Issue by enomao44** [fast4x/RiMusic#3529]
### Description

i think could be cool and fun an option to get some random album from all the albums available on the app not just from your albums lists, even to have some random choice or very good to discover some music.

### Suggested Solution

to have the button of random album

**Comment by fast4x** [comment]
Explain better please, in albums list there is a dice button...

**Comment by enomao44** [comment]
yeah there is in albums list but i mean a random album between all millions and database from the app

**Comment by fast4x** [comment]
You mean albums section in online search results?

**Comment by enomao44** [comment]
yeah to find some random album among all the albums of the app

**Comment by enomao44** [comment]
reminds me to something fun to do when you could go to a big albums store and start to sort on unknown artists albums, vinyls and just pick one randomly to discover this album. It is a nice way to discover.

**Comment by fast4x** [comment]
Implemented available from version 0.6.51
![Screenshot_20240903_110237](https://github.com/user-attachments/assets/67881552-9a0a-457f-b9fc-213ae66aa1c8)

**Comment by enomao44** [comment]
but this is just from the same artist no?

**Comment by enomao44** [comment]
doesnt have to be inside any search in specific, i mean without typing anything have the chance to find a full random album without any reference, with a button on home for example that gives me a random album from all the database for ex 110M albums on the database? so a random album among this 110M of albums.

**Comment by fast4x** [comment]
ahahaha ok I'll try to check if possible

**Comment by enomao44** [comment]
okey cool xd

**Comment by enomao44** [comment]
i didnt mean random album in artist overview, i meant random album over all the millions of albums of the database
