### ISSUE TITLE
Add to Playlist button of Player Action Bat

### ISSUE THREAD

**Issue by coolswapnil** [fast4x/RiMusic#3539]
### Steps to reproduce the bug

Open Settings -- Player Appearance -- Enable Add to playlist button from Player Action Bar section.
Play any songs -- Open Playing song in -- Click on Add to playlist button.

### Expected behavior

Add to playlist button opens menu with selected style (Grid or list)
![Screenshot_2024-09-04-18-36-07-505_it fast4x rimusic](https://github.com/user-attachments/assets/f76bd272-5c06-4992-91ba-e5d7f6c6f4ec)

### Actual behavior

Add to playlist should open playlist available in player and let user select a playlist in which new songs needs to be added.
![Screenshot_2024-09-04-18-36-23-813_it fast4x rimusic](https://github.com/user-attachments/assets/f6b4e462-d92f-45c0-a3e2-9ff0aba6adc4)

### RiMusic version

0.6.50

### Android version

14

**Comment by Abhijit-Guragain** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
