### ISSUE TITLE
Unable to close Videoplayer when opend from Song view

### ISSUE THREAD

**Issue by materialred** [fast4x/RiMusic#3541]
### Steps to reproduce the bug

1. Open a Song with a Video
2. Klick on the open Video Button
3. Select one Video
4. Try to close the Video

### Expected behavior

There should be a way to close the Video

### Actual behavior

Unable to Close the Playing Video

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/99a4215d-ff3f-471a-ab14-8429268fe310

### RiMusic version

0.6.50

### Android version

Android 15 QPR1 Beta 1, Android 13

**Comment by fast4x** [comment]
Improved, now can switch from vide to audio player, available from version 0.6.51
