### ISSUE TITLE
Repetitive playlist 

### ISSUE THREAD

**Issue by AilenAriadne** [fast4x/RiMusic#3544]
### Steps to reproduce the bug

Finish 3 songs in a Playlist. everytime when after playing 3 songs it plays the last two again. How can I fix this? 

### Expected behavior

that the playlist sounds good according to its order 

### Actual behavior

The playlist does follow the order but when the 3 songs finish it gets stuck and the last two are repeated. 

### RiMusic version

0.6.48

### Android version

Android 14

**Comment by fast4x** [comment]
Upgrade to latest version 0.6.50

**Comment by twistios** [comment]
Even if you have the same problem as me, it could be because of another source. So it can be that it is already fixed for your case.

**Comment by fast4x** [comment]
In my case i haven't this bug, it work. From your log issue maybe is caused by lookahead scope.
