### ISSUE TITLE
No aparecen las canciones de apartado de Recomendaciones 

### ISSUE THREAD

**Issue by efrainveg** [fast4x/RiMusic#3549]
### Steps to reproduce the bug

1. Ingreso a la app RiMusic 
2. En el apartamento de Recomendaciones solo aparece una canción anteriormente aparecerían varias canciones para elegir 
![Screenshot_2024-09-04-18-31-58-365_it fast4x rimusic](https://github.com/user-attachments/assets/b6a64fea-2d5c-4808-bcd0-668f14113401)

### Expected behavior

Al ingresar a la app debería aparecer en el apartamento de Recomendaciones varias canciones para elegir sin embargo aparece solo una y que un espacio en blanco como se puede observar en la imagen 

### Actual behavior

No aparecen las canciones de la pestaña de Recomendaciones 
![Screenshot_2024-09-04-18-31-58-365_it fast4x rimusic](https://github.com/user-attachments/assets/1cf4eac3-d965-4127-827a-71ff5d59eacd)

### RiMusic version

0.6.50

### Android version

Android 14

**Comment by fast4x** [comment]
Listen another song
