### ISSUE TITLE
What if there was Google login option

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#355]
### Description

To improve suggestions and to import playlist gaccount must be needed
![Polish_20240108_203228956](https://github.com/fast4x/RiMusic/assets/120176369/54b1abca-fcd8-4a80-907d-33e97ec9e03a)

### Suggested Solution

You can add this feature or do vote. I also musixmatch for translation of lyrics and better synced lyrics. Idea from SimpMusic:https://github.com/maxrave-dev/SimpMusic#data

**Comment by Logan7899** [comment]
![Uploading Screenshot_20230909-211331_SimpMusic.png…]()

**Comment by Logan7899** [comment]
![Screenshot_20240108-213358](https://github.com/fast4x/RiMusic/assets/120176369/7f62320b-17cd-4ee2-b208-2f14f2d5e819)
![Screenshot_20240108-213348](https://github.com/fast4x/RiMusic/assets/120176369/0d330dc3-5028-4212-be62-c39528253221)

**Comment by ikanakova** [comment]
Isn't planned see #315

**Comment by Logan7899** [comment]
> Isn't planned see #315

It would be great to implement as it will improve the recommendation system of RIMusic

**Comment by ikanakova** [comment]
>>Isn't planned see https://github.com/fast4x/RiMusic/issues/315

>It would be great to implement as it will improve the recommendation system of RIMusic

I think it would complicate the release via F-Droid and not everyone wants Google trackers.

(OT: @fast4x I think there should be a check box in the Issue template for the feature request:
"I made sure that there are no existing issues (open or closed) related to this feature request.")

**Comment by fast4x** [comment]
> > > Isn't planned see #315
> 
> > It would be great to implement as it will improve the recommendation system of RIMusic
> 
> I think it would complicate the release via F-Droid and not everyone wants Google trackers.
> 
> (OT: @fast4x I think there should be a check box in the Issue template for the feature request: "I made sure that there are no existing issues (open or closed) related to this feature request.")

Not everyone would read it...

**Comment by Logan7899** [comment]
> > > Isn't planned see #315
> 
> > It would be great to implement as it will improve the recommendation system of RIMusic
> 
> I think it would complicate the release via F-Droid and not everyone wants Google trackers.
> 
> (OT: @fast4x I think there should be a check box in the Issue template for the feature request: "I made sure that there are no existing issues (open or closed) related to this feature request.")

You didn't understand. Users can log in their respective account if they want their yt music playlist and better Recommendation. In the image there is a option called Bett recommendations. This would only work when the user is logged in their respective google account and also they can turn it if if they only want their saved playlist😀😀

**Comment by ikanakova** [comment]
> You didn't understand. Users can log in their respective account if they want their yt music playlist and better Recommendation. In the image there is a option called Bett recommendations. This would only work when the user is logged in their respective google account and also they can turn it if if they only want their saved playlist😀😀

It doesn't work that way, if it would be an option to log in to Google, it would have to implement a Google tracker for authentication for all users, even those who don't log in to a Google account.

**Comment by ikanakova** [comment]
> Not everyone would read it...
Probably true, but at least some people would respect that... Plus, you could automatically shut down issues that violate it.

**Comment by fast4x** [comment]
> > Not everyone would read it...
> 
> Probably true, but at least some people would respect that... Plus, you could automatically close issues that violate it.

Of course, but it is appropriate to dialogue with people and explain the reasons why something cannot be done.

**Comment by ikanakova** [comment]
> > > Not everyone would read it...
> > 
> > 
> > Probably true, but at least some people would respect that... Plus, you could automatically close issues that violate it.
> 
> Of course, but it is appropriate to dialogue with people and explain the reasons why something cannot be done.

I agree. I meant you could write " duplicity to..." and close the issue.

**Comment by Logan7899** [comment]
> @fast4x I wrote an [explanatory comment in # 315](https:// github.com/fast4x/RiMusic/issues/315#issuecomment-1881645548), so this issue may be closed.

You can use Piped account to log in for ex: Kevin Rock Official I think I wrote that right and also it is used by LibreTube and video recommendations are very good. Why don't you use it for RIMusic. No privacy at risk and the problem starting to arise is that whenever u listen to a song of particular the songs are repetitive in queue. For ex: My favourite artist is A and I listen the song of A artist than the queue of that song is same if listen the another of A artist. It should be different. But not that's why I am suggesting this feature

**Comment by Logan7899** [comment]
> > @fast4x I wrote an [explanatory comment in # 315](https:// github.com/[/issues/315](https://github.com/fast4x/RiMusic/issues/315)#issuecomment-1881645548), so this issue may be closed.
> 
> You can use Piped account to log in for ex: Kevin Rock Official I think I wrote that right and also it is used by LibreTube and video recommendations are very good. Why don't you use it for RIMusic. No privacy at risk and the problem starting to arise is that whenever u listen to a song of particular the songs are repetitive in queue. For ex: My favourite artist is A and I listen the song of A artist than the queue of that song is same if listen the another of A artist. It should be different. But not that's why I am suggesting this feature

![Uploading Screenshot_20240109-011636.png…]()
