### ISSUE TITLE
Notifications 

### ISSUE THREAD

**Issue by Akoltxd** [fast4x/RiMusic#3551]
### Steps to reproduce the bug

There are times when the player in my notification bar disappears and the music stops, that's very annoying 

### Expected behavior

All

### Actual behavior

All

### Screenshots/Screen recordings

All

### Logs

All

### RiMusic version

I forgot which one I have 

### Android version

I also forgot

**Comment by fast4x** [comment]
Enable invincible mode in miscellaneous settings
