### ISSUE TITLE
Discord entegration add

### ISSUE THREAD

**Issue by Sxinar** [fast4x/RiMusic#3555]
### Description

Merhaba discordda RiMusic ile dinlediğimiz müzikler esitlenebilir

### Suggested Solution

Merhaba discordda RiMusic ile dinlediğimiz müzikler esitlenebilir

**Comment by Clyde6790pGIT** [comment]
Merhaba, geliştirici discord entegrasyonu eklemeyeceklerini, ancak uygulamanın “https://github.com/dead8309/Kizzy” bunu etkinleştirebileceğini belirtti.
- DeepL kullanılarak çevrilmiştir.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.52
