### ISSUE TITLE
YouTube bot alert

### ISSUE THREAD

**Issue by rsssxd** [fast4x/RiMusic#3557]
Hello, because of the VPN I use, YouTube is showing me a bot warning and asking me to sign in. Rimusic not working.

### Logs

![IMG_20240905_142257_208](https://github.com/user-attachments/assets/7f6e65d8-9db2-4751-9420-950ccf8b5712)

### Android version

Android 14 GrapheneOS

**Comment by fast4x** [comment]
Hi, use a proxy instead vpn.
