### ISSUE TITLE
Followed Artists New Releases not showing

### ISSUE THREAD

**Issue by Ao1Pointblank** [fast4x/RiMusic#3558]
### Steps to reproduce the bug

In quick picks settings, both of these options are activated:
Show New Albums
Show New Albums from your artists

However, my artists are not showing new albums

### Expected behavior

New albums (and singles?) from the artists I follow should show below the trending new albums.

### Actual behavior

No followed artist albums, not even a header for that category on the quick picks page. 

I've been using this app for a long time; this feature has never worked for me. I thought for a while it was still a feature in development, but after reading some closed issue reports, I know only some people experience this bug. 

Is it perhaps caused by following too many artists? (I have 56 bookmarked)

I would like to help solve this issue. Is there anything in particular I should look for in logs w/ adb?

### RiMusic version

0.6.50

### Android version

Android 14 Graphene OS

**Comment by fast4x** [comment]
You are sure that new songs exists from your preferite artist?

**Comment by Ao1Pointblank** [comment]
> You are sure that new songs exists from your preferite artist?

Yep, like I said, I've been using this app for a long time and have quite a lot of followed artists. I only found out about the new releases from other sources; I definitely am not being notified.

The issue appears similar to what this user reported, except I don't even see the header:
https://github.com/fast4x/RiMusic/issues/1327
