### ISSUE TITLE
music doesn't pause on notification player

### ISSUE THREAD

**Issue by moonslayers** [fast4x/RiMusic#3559]
### Steps to reproduce the bug

Open app 
Play a random song
Exit the app
Pause the song in the notification player

### Expected behavior

To stop the music o start music playing

### Actual behavior

Icon change to play icon but music keeps playing 
The music pause until I open the app

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/1fba6478-24b4-4271-85c9-183859e876a7

### RiMusic version

0.6.50

### Android version

13

### Additional information

Xiaomi 13 note
Miui 14.0.7

**Comment by fast4x** [comment]
Check permissions

**Comment by moonslayers** [comment]
![Screenshot_2024-09-06-06-53-27-413_com google android permissioncontroller](https://github.com/user-attachments/assets/cd920831-61ed-4826-bc63-0c4bef6faa79)

These are its permissions, still not working

**Comment by moonslayers** [comment]
Is it fixed already?
