### ISSUE TITLE
No se puede reproducir la musica 

### ISSUE THREAD

**Issue by Favito17** [fast4x/RiMusic#3561]
### Steps to reproduce the bug

Simplemente este error ya me viene apareciendo en cada una de las actualizaciones, pensé que lo hiban a corregir pero nada , es un poco tedioso estar escuchando normal la música y que de la nada cambies y te salga ese error 

### Expected behavior

.

### Actual behavior

.tengo que estar reiniciando la aplicación hasta que se pueda reproducir la musica

### Screenshots/Screen recordings

![Screenshot_20240905-121228](https://github.com/user-attachments/assets/c8ea45b7-655c-489e-b240-6d9e9fd86e63)

### Logs

.

### RiMusic version

V0.6.50

### Android version

Android 12

### Additional information

Espero logren solucionarlo

**Comment by fast4x** [comment]
Wait for next version
