### ISSUE TITLE
The application closes after opening it 

### ISSUE THREAD

**Issue by marcheeel** [fast4x/RiMusic#3563]
### Steps to reproduce the bug

1. Open the app 
2. Go to playlist
3. Play any song, by clicking it or pressing random
4. After a few seconds the app closes and stops playing music 

Sometimes it also happens even if you don't play music or do anything, just by opening it.

### Expected behavior

The app works normally 

### Actual behavior

The app closes after a few seconds of opening it 

### RiMusic version

0.6.50

### Android version

Android 14

### Additional information

I've already tried clearing the cache (as the system recommended it after closing the app a couple of times). I've also tried restarting the device and forcing the app to close, but it doesn't fix it.

**Comment by fast4x** [comment]
Enable debug in miscellaneous settings and after a crash copy and here the crash log.
