### ISSUE TITLE
I can't disable the music video

### ISSUE THREAD

**Issue by qpzmc** [fast4x/RiMusic#3565]
### Steps to reproduce the bug

Searched a song and played it from the "videos" section

### Expected behavior

I wanted it to be displayed like:
![Screenshot_20240905_174644](https://github.com/user-attachments/assets/d0ca93bc-45a9-425c-9f65-0f8dc0787aac)

### Actual behavior

but instead, the music video appears instead:
![Screenshot_20240905_173447](https://github.com/user-attachments/assets/c5805749-544a-4dd9-abc6-e86a4a8d73b6)

### Screenshots/Screen recordings

I already went to the settings but the only video related setting I found is already turned off:
![Screenshot_20240905_173505](https://github.com/user-attachments/assets/7b3fc005-4619-4bca-bef0-b23cf4db7fe1)

I know this is probably a really dumb question, I'm so sorry, but I'm not very good with these things. Thank you for your time in advance.

### RiMusic version

0.6.50

### Android version

Android 14

**Comment by fast4x** [comment]
Download custom version or wait new version tonight.

**Comment by qpzmc** [comment]
thank you so much :)))
