### ISSUE TITLE
Audio interruption for less than a second

### ISSUE THREAD

**Issue by Sebasio-dotcom** [fast4x/RiMusic#3567]
### Steps to reproduce the bug

The bus is show up when putting the app or other apps on background, also when turning off the screen. 
### Expected behavior

Songs should not be interrupted

### Actual behavior

Songs get interrupted for a moment, could be related to optimization

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/3956d74c-5a08-44d2-add1-0b324ca8d076

### RiMusic version

0.6.50

### Android version

Android 12

**Comment by fast4x** [comment]
I don't understand, explain better please.

**Comment by twistios** [comment]
> I don't understand, explain better please.

@fast4x it stops playing for a very short time ~ second 9.

**Comment by fast4x** [comment]
Medley mode... disable it
