### ISSUE TITLE
Pitch black theme mode not working on app startup

### ISSUE THREAD

**Issue by Randomguy369** [fast4x/RiMusic#3568]
### Steps to reproduce the bug

Settings > UI > Theme Mode > Pitch Black

### Expected behavior

While opening the app the pitch black theme mode should be there 

### Actual behavior

While opening the app pitch black theme mode isn't there , it applies only after playing a song 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/547bd482-ce08-40ee-b7e0-36652b306086

### RiMusic version

0.6.50

### Android version

Android 14

**Comment by twistios** [comment]
"Pitch Black" does not exist. There is "Modern Black" and "Pure Black". I have tested with both of them and it works as expected.
Please provide more information, for example the actual theme and other appearance settings and your System theme.

**Comment by Randomguy369** [comment]
![Screenshot_2024-09-07-07-41-28-13_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/1d30b289-d202-45cd-b83c-e49bb45ecb31)

As you can see here , the theme is dynamic and theme mode is pitch black

**Comment by twistios** [comment]
Ah sorry, I read "theme". I was testing with "System" for theme mode.

**Comment by twistios** [comment]
It looks like I can confirm your bug at least with these two specific settings from you.
<details><summary>Video example</summary>
<p>

https://github.com/user-attachments/assets/246d5067-b400-45c1-b260-e7f15047fbd1

</p>
</details>

**Comment by Randomguy369** [comment]
Hey! This bug is still there in the latest version

**Comment by twistios** [comment]
The bug is still opened (it is not closed), neither marked with "fixed" nor has fast4x (the maintainer) answered yet. So neither fast4x has not fixed it yet nor was there notable progress on this bug.
I currently do not have much time to look into it so you have to wait until it gets fixed someday.

**Comment by fast4x** [comment]
Improved available from version 0.6.60
