### ISSUE TITLE
I can't download music after the last version 

### ISSUE THREAD

**Issue by PH554** [fast4x/RiMusic#3570]
### Steps to reproduce the bug

Search for a song 
Click on the download icon 
And wait for the music to download to listen to it offline

### Expected behavior

The song should download instantly, to listen to it offline 

### Actual behavior

The music doesn't download and stays in a download loop that doesn't stop, but the problem is that this does not occur with all songs, only with one song in common 

### RiMusic version

0.6.50

### Android version

Android 13

**Comment by fast4x** [comment]
Add a video please

**Comment by PH554** [comment]
For some reason, it stopped happening I managed to download the music that I was not downloading, I'm sorry for any inconvenience

**Comment by PH554** [comment]
> Add a video please

For some reason, it stopped happening I managed to download the music that I was not downloading, I'm sorry for any inconvenience, I am a new user of your app, and this occurred to me, but it corrected itself, but by the speed of service, I saw that I can trust you, next time, it will be a bug that will occur to me every time.
