### ISSUE TITLE
Add Apple Music Lyrics Style

### ISSUE THREAD

**Issue by LIGHTxDREAM** [fast4x/RiMusic#3571]
### Description

I hear many people  mean on facebook, on instagram, on twitter, on telegram, on discord everyone say its apple music alternative and I think so too but I only cant find the apple's lyrics system like it's highlight every word on song lyrics and it's awesome so I just want not me actually many people want but I just love to see apple lyrics system on RiMusic I hope its will ad on next update soon 

### Suggested Solution

I want that on next update 'developer' add apple lyrics system and make an option to enable it because some low end phone can crash if they are already enable by default.

### Alternatives

I request to add apple lyrics system and its awesome

### Additional Context

Its pretty good if 'developer' add apple lyrics system people will like it

**Comment by fast4x** [comment]
You can highlight the sentence but not the single word.

**Comment by twistios** [comment]
The synchronised lyrics only provide timestamps per line. So we can not easily implement this. I guess for apple lyrics they use some kind of "word detection" on the audio. It might be that we could also do something like this but it would probably require much computations and is definitely not easy to implement.

**Comment by LIGHTxDREAM** [comment]
Iam Also Happy With Highlight a sentence. It will more understandable song lyrics. I hope on next update "developer" add highlight every sentence. (Lot of thanks for understand me)

**Comment by twistios** [comment]
RiMusic can only provide what is available via the lyrics service. If the lyrics service only has synchronised lyrics that have lines in a not useful way then we can not do anything about it. So it is not possible to highlight based on sentences or whatever requirement if it is not already fulfilled.
RiMusic does provide synchronised lyrics were available and sometimes only unsynchronized ones or even none are available.

**Comment by LIGHTxDREAM** [comment]
I understand.  Thanks for listen to me I really appreciate it. Thank you.

**Comment by ALMIGHTY-VC** [comment]
Well just additional info this project supports enhanced lyrics word synced lyrics
https://github.com/moehmeni/syncedlyrics?tab=readme-ov-file
