### ISSUE TITLE
L'auteur de la chanson n'est pas le bon

### ISSUE THREAD

**Issue by Ask1ew** [fast4x/RiMusic#3572]
### Steps to reproduce the bug

Importer une playlist public depuis un compte Youtube.
Écouter une chanson de cette playlist.

### Expected behavior

Avoir l'artiste au lieu du pseudo du créateur de la playlist 

### Actual behavior

Pseudo du créateur de la playlist.
Ici dans les captures, l'artiste est : Lomepal et l'auteur de la playlist est Askiew
La musique fonctionne quand même 

### Screenshots/Screen recordings

![Screenshot_20240906_160229](https://github.com/user-attachments/assets/e527ce30-6779-44a8-94ca-7df895bc880e)
![Screenshot_20240906_160204](https://github.com/user-attachments/assets/a38e51f7-c1ed-482e-80e9-a948a315302a)

### RiMusic version

0.6.50

### Android version

Android 14

**Comment by fast4x** [comment]
Sorry, but i don't understand, explain better please.

**Comment by Ask1ew** [comment]
J'ai importé une playlist youtube de ma propre confection. Toutes mes musiques de cette playlist ont pour auteur Askiew sans exception. Pour autant, l'auteur devrait s'actualiser avec la chanson pour ressortir le vrai auteur du titre.

**Comment by fast4x** [comment]
The song data updates when you sync the playlist.

**Comment by Ask1ew** [comment]
Ça fait déjà plusieurs semaines que c'est ainsi. Sur le même principe les albums du mois créé automatiquement ne mettent pas à jour les titres. Peut être que je loupé quelque chose... Est ce qu'il y a un bouton pour forcer la synchronisation dans ces cas là ?

**Comment by fast4x** [comment]
The monthly playlist is not scheduled to be synchronized because it is a collection of songs played in the previous month.

**Comment by Ask1ew** [comment]
Même en forçant la synchronisation de la playlist de base, les auteurs ne changent pas.
