### ISSUE TITLE
Widgets didn't work

### ISSUE THREAD

**Issue by SharkyBeAre** [fast4x/RiMusic#3575]
### Steps to reproduce the bug

When placing the widget on the home screen, it shows me a message that the content could not be displayed.

### Expected behavior

Since the widget is installed, it does not work

### Actual behavior

.

### Screenshots/Screen recordings

![IMG-20240906-WA0011](https://github.com/user-attachments/assets/0341a86a-c75c-40bf-882e-d4709a7f370c)

### RiMusic version

0.6.51

### Android version

Android 13

**Comment by SharkyBeAre** [comment]
![IMG-20240906-WA0008](https://github.com/user-attachments/assets/be2c2aaa-a16e-4c0f-8a1c-5c7c08c811fb)

**Comment by fast4x** [comment]
Open RiMusic, play a song, it change?

**Comment by twistios** [comment]
I think it is supposed to look this way.

<details><summary>Example</summary>
<p>

![Screenshot_20240907_103046_One UI Home](https://github.com/user-attachments/assets/7e52eaaa-e208-42ba-93c2-39f86fcaf9a6)

</p>
</details>

**Comment by SharkyBeAre** [comment]
> Open RiMusic, play a song, it change?

Nope, nothing change, I even force closed the app and re-played a song but it's still the same

**Comment by SharkyBeAre** [comment]
> I think it is supposed to look this way.
> 
> Example
> ![Screenshot_20240907_103046_One UI Home](https://private-user-images.githubusercontent.com/54811436/365354035-7e52eaaa-e208-42ba-93c2-39f86fcaf9a6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MjAyNDQsIm5iZiI6MTcyNTcxOTk0NCwicGF0aCI6Ii81NDgxMTQzNi8zNjUzNTQwMzUtN2U1MmVhYWEtZTIwOC00MmJhLTkzYzItMzlmODZmY2FmOWE2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDE0MzkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYzBhZTI2NTViODNmOTUxNzk1OTNmZWUyYjZjOTdlZTYxNGI0NzhjM2FhNjQzYWRhOTUxOGUwYTI5MWQ3YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gyjh9AA3Ae2B2D_E73PEUhMG8lAr483qdn9fRZUn1ww)

Yes, I have another phone and it does work on that one and looks like it does on yours.

**Comment by twistios** [comment]
I was testing how the widget can be improved and I got the same appearance as you SharkyBeAre. It happend when it Container code that is not compatible with widgets. In your case it maybe is something different.

**Comment by twistios** [comment]
@SharkyBeAre something that you can test is to remove the widget and add it again. The reason it might work is that restarting the app does not do much about the widget.
I also saw that the widget did not get updated when I changed the code in my test.

**Comment by SharkyBeAre** [comment]
I tested it and it continues the same way, even if I remove and put the widget again it still doesn't show me anything.

**Comment by fast4x** [comment]
try to start app

**Comment by fast4x** [comment]
Ok, I'll check it
