### ISSUE TITLE
Songs Randomly In Imported Community Playlists Have The Playlist Creator As The Artist

### ISSUE THREAD

**Issue by All-Chronical** [fast4x/RiMusic#3576]
### Steps to reproduce the bug

Look up a community playlist. Viewing it while browsing perfectly shows each song of the playlist having the correct artist for that song. Upon saving/importing the playlist to the library, randomly the artist's names of majority of the songs are changed to the name of the playlist maker.

### Expected behavior

![Screenshot_20240906_175200](https://github.com/user-attachments/assets/797d3228-3641-4b4f-9317-ab2e2f565389)

### Actual behavior

![Screenshot_20240906_175048](https://github.com/user-attachments/assets/1d2d009e-9ae4-4fae-b046-88df6f86b3c8)

(AC333 is the name of the playlist creator)

### RiMusic version

0.6.5

### Android version

Android 14

**Comment by k3nethh** [comment]
How did you fix this?

**Comment by All-Chronical** [comment]
> How did you fix this?

From what I can tell this is an issue on playlists with multiple contributors. What I did, was I copied over the playlist with a single contributor, updated the app, reimported the playlist, and it's "fixed". 
It's a workaround but haven't had any issues since.
