### ISSUE TITLE
Unresolved 

### ISSUE THREAD

**Issue by XGhostRX** [fast4x/RiMusic#3579]
### Steps to reproduce the bug

When trying to listen to local music

### Expected behavior

Normal playback

### Actual behavior

The same crashes as always

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/6760215b-03da-4ed6-b7ce-53c171b9ad54

### Logs

2024-09-06T21:33:13.172:	java.lang.NullPointerException
	 B7.Z.s(SourceFile:966) 
	 B7.Z.h(SourceFile:13) 
	 r8.L.a(SourceFile:73) 
	 r8.h.a(SourceFile:18) 
	 r8.E.s(SourceFile:51) 
	 U7.a.l(SourceFile:9) 
	 n8.M.run(SourceFile:113) 
	 A2.f.run(SourceFile:114) 
	 v8.j.run(SourceFile:3) 
	 v8.a.run(SourceFile:96) 

### RiMusic version

0.6.51

### Android version

Android 10

### Additional information

So far there is no solution to that problem

**Comment by fast4x** [comment]
You have a song that it's cause of crash

**Comment by XGhostRX** [comment]
?

**Comment by fast4x** [comment]
If crash in local songs, it's caused by one song that RiMusic not recognize. Log doesn't help to find it... sorry.

**Comment by XGhostRX** [comment]
So there is no solution 🤦‍♂️

**Comment by XGhostRX** [comment]
This is when I say:
Do you find it so difficult to optimize the app to avoid those mistaken? 🤦‍♂️
