### ISSUE TITLE
Update Checker | BUG 🐛

### ISSUE THREAD

**Issue by drago-bit** [fast4x/RiMusic#3581]
### Steps to reproduce the bug

**For this bug to exist, there should be an update in the queue.**

Go to Settings > Misc > Check Update
Press the **Check Update** button

### Expected behavior

If there is an update, the pop up should come up and stay as such, until a user input is made.

### Actual behavior

Currently, it's just flashes and impossible to give an input. This issue was present in the previous two updates as well. Attached a screen recording for convenience.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/a8cb3e52-7e87-4979-94b5-b2bf6057be64

### RiMusic version

0.6.51

### Android version

Android 14

### Additional information

Thanks for the app by the way. 🤗

**Comment by fast4x** [comment]
Wow I'll check it, thanks

**Comment by twistios** [comment]
I can confirm this for version 0.6.50.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.52
