### ISSUE TITLE
[Feature]: Remove Background Usage

### ISSUE THREAD

**Issue by Selva543350** [fast4x/RiMusic#3582]
### Description

i dont know why, but when i pause the song for sometime and leaves the app it stucks, only if i closes the app completely and reopened it then it is working, but i know there is option called ignore battery optimization , but it uses more battery then usual usage because of background usage, so please fix that

### Suggested Solution

Reduce the battery usage from background as well as frontground

**Comment by twistios** [comment]
If "ignore battery optimization" is enabled, then it makes sense that it uses more battery than when this option is not enabled as this way the system can not handle the app in a normal way.
There is also the option "invincible service" which is a stronger version of "ignore battery optimization" which sometimes works better than only "ignore battery optimization".
Probably it kills a part of the app, i.e. the player background service such that it gets stuck.
