### ISSUE TITLE
Rimusic keeps crashing

### ISSUE THREAD

**Issue by KingK2-gif** [fast4x/RiMusic#3584]
### Steps to reproduce the bug

1. I click on the app.
2. I play my liked songs

### Expected behavior

Suppose to run the app properly and play my songs freely

### Actual behavior

It keeps crashing or it let's me in but after a couple of songs it keeps saying requested video id doesnt match.

### Screenshots/Screen recordings

![Screenshot_20240907_081517_One UI Home](https://github.com/user-attachments/assets/e967ad97-79eb-4887-87c4-338e66ef7326)

### RiMusic version

0.6.51

### Android version

Android 14

**Comment by fast4x** [comment]
Enable debug in miscellaneous settings, after crash pasta here the crash log

**Comment by KingK2-gif** [comment]
Yeah I did enable debug already

**Comment by KingK2-gif** [comment]
I'm trying to do it again but it won't let me go to the miscellaneous setting it would just crash again 😩 😪

**Comment by KingK2-gif** [comment]
Ok I just downloaded the rimusic application the one without my vimusic database and it working properly now so I think it has something to do with the vi music data. But now I don't have any of my songs lol

**Comment by KingK2-gif** [comment]
Ok I just put my vimusic database on rimusic and it's working fine now and I turned on debug so I'll let you know. Hopefully I don't get the requested video id doesnt match problem again because I think that also is one of the causes
