### ISSUE TITLE
Conectar con Spotify 

### ISSUE THREAD

**Issue by danielperro** [fast4x/RiMusic#3587]
### Description

Que se pueda conectar con otros servicios de música como Spotify o YouTube Music para poder usar las mismas playlist sin necesidad de crearlas de nuevo

### Suggested Solution

Poder iniciar sesión con YouTube Music o Spotify

**Comment by twistios** [comment]
Login to YT and Spotify will not happen (at least this is the current "policy"). Also RiMusic is not really compatible with Spotify.

Sync from Spotify to RiMusic is possible via export and then import to YTM and from there to RiMusic. A "two-way" sync is implemented with piped login.

**Comment by pookdeveloper** [comment]
I'm trying to use this URL to import a playlist but it doesn't work. Is there any way to import it?

https://open.spotify.com/playlist/3yJf6pwvilY5txST6ZqflL?si=a6324c26b0b54f8e
