### ISSUE TITLE
Need to close the app with back button. 

### ISSUE THREAD

**Issue by AfafAsyraf** [fast4x/RiMusic#3589]
### Steps to reproduce the bug

Clicking back button to close app didn't work

### Expected behavior

Close the app

### Actual behavior

Didn't close the app

### RiMusic version

0.6.49.2

### Android version

14

### Additional information

Or create press back again to close the app.

**Comment by faustaahmad** [comment]
Close the app?
Close background player: Enabled
Got to recents, then swipe RiMusic out from there

Problem with back button is that you'll need to press it tons of times (so I dislike using it)

**Comment by fast4x** [comment]
![Screenshot_2024-09-08-13-23-22-430_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/d882eb2b-07dc-4afb-8f99-cb044fb9da00)
