### ISSUE TITLE
Option to disable skipping tracks via swiping up or down on the player thumbnail 

### ISSUE THREAD

**Issue by Toiletmason** [fast4x/RiMusic#3590]
### Description

Option to disable skipping tracks via swiping up or down on the player thumbnail. There used to be an option, and maybe there still is, but I can't find it and search doesn't either. 

### Suggested Solution

Put an option so swiping on the thumbnail does nothing.

**Comment by aneesh1122** [comment]
Change player to essential from settings.

**Comment by aneesh1122** [comment]
> Why not a simple button in settings to disable this? 
> 
> Like any other 1000 things there in Rimusic

Why do you want to use modern player if you don't want to use swipe? 

The reason why I implemented modern player is because I wanted to see what's the next song by swiping.

It has to be vertical because of the Carousel.
