### ISSUE TITLE
New albums not loading and old ones are losing their titles/images

### ISSUE THREAD

**Issue by Shlorby** [fast4x/RiMusic#3592]
### Steps to reproduce the bug

I wa using the app and it was working well for a long time. I transferred to this app from vimusic because vimusic had the same issue. When I go to an album that I have not listened to before, the songs, title or image of the album do not load. In the albums that I saved previously, the title and cover page are deleted. 

### Expected behavior

When I click on a new album, the title, cover image and songs should load. The same should happen to albums that I have saved.

### Actual behavior

When I click on a new album, the titles, songs and the cover image does not load. When I click on old albums that had the image saved previously, the image gets deleted and so does the title.

### Screenshots/Screen recordings

![Screenshot_20240907_203721](https://github.com/user-attachments/assets/d810f728-0f4f-4913-a652-dbdce2cb6779)
![Screenshot_20240907_203711](https://github.com/user-attachments/assets/4e394b74-dae1-4407-9b54-023af9cc54f8)
![Screenshot_20240907_203706](https://github.com/user-attachments/assets/48c75e48-4557-4c37-89e3-0d72b8655c58)

### RiMusic version

v0.6.47.1

### Android version

13

**Comment by twistios** [comment]
Update to latest version and report back what happened.

**Comment by Rensen242** [comment]
Hi All, had the same issue for some weeks and Update To v0.6.51 fixed it.

Thanks for your great work !

Rensen
