### ISSUE TITLE
Crash when allowing files to be read 

### ISSUE THREAD

**Issue by joaquo619** [fast4x/RiMusic#3593]
### Steps to reproduce the bug

Go to songs > list On the device> Allow Files to Read and Closed 

### Expected behavior

Show up the music on my phone 

### Actual behavior

The app closes.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/0cf9ac6b-ab75-4d9f-b212-dc9434a5ca4e

### Logs

2024-09-08T02:40:17.111:	java.lang.NullPointerException
	 B7.Z.s(SourceFile:966) 
	 B7.Z.h(SourceFile:13) 
	 r8.L.a(SourceFile:73) 
	 r8.h.a(SourceFile:18) 
	 r8.E.s(SourceFile:51) 
	 U7.a.l(SourceFile:9) 
	 n8.M.run(SourceFile:113) 
	 A2.f.run(SourceFile:114) 
	 v8.j.run(SourceFile:3) 
	 v8.a.run(SourceFile:96) 

2024-09-08T02:40:20.968:	java.lang.NullPointerException
	 B7.Z.s(SourceFile:966) 
	 B7.Z.h(SourceFile:13) 
	 r8.L.a(SourceFile:73) 
	 r8.h.a(SourceFile:18) 
	 r8.E.s(SourceFile:51) 
	 U7.a.l(SourceFile:9) 
	 n8.M.run(SourceFile:113) 
	 A2.f.run(SourceFile:114) 
	 v8.j.run(SourceFile:3) 
	 v8.a.run(SourceFile:96) 

### RiMusic version

0.1.6

### Android version

Android 10

### Additional information

I have all my music in my internal storage, not in a specific folder, some files whose names have links to web pages. I also have rar files

**Comment by twistios** [comment]
Version 0.1.6 probably does not even exist. If not yet done, update to latest version 0.6.51 and report back with what happened.

**Comment by fast4x** [comment]
It's a permission issue that not depend bu RiMusic, sorry.
