### ISSUE TITLE
Multi-select adding to existing playlist freezes the app

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#3597]
### Steps to reproduce the bug

Same as #3596, except that the playlist has to already exist.

### Expected behavior

The selected songs are added.

### Actual behavior

The app freezes and no song is added.

### Screenshots/Screen recordings

<details><summary>Video example</summary>
<p>

https://github.com/user-attachments/assets/d225a69c-d76c-4610-a866-005b95d84a0f

</p>
</details> 

### RiMusic version

0.6.51

### Android version

14

### Additional information

Related to #3596. Found while testing for the related bug.

**Comment by twistios** [comment]
This is what happens if you wait for longer:

<details><summary>Screenshot with more info</summary>
<p>

![Screenshot_20240908_144855](https://github.com/user-attachments/assets/a10aff6e-a100-4538-b40f-a839cbbf0ac7)


</p>
</details>

**Comment by twistios** [comment]
It seems to get unstuck after the message so I is "lagging" very much.

**Comment by twistios** [comment]
It seems to work when selecting from a playlist instead of the songs tab.

**Comment by faustaahmad** [comment]
> This is what happens if you wait for longer:
> 
> <details><summary>Screenshot with more info</summary><p><image src="https://private-user-images.githubusercontent.com/54811436/365439000-a10aff6e-a100-4538-b40f-a839cbbf0ac7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTg2NDcsIm5iZiI6MTcyNTgxODM0NywicGF0aCI6Ii81NDgxMTQzNi8zNjU0MzkwMDAtYTEwYWZmNmUtYTEwMC00NTM4LWI0MGYtYTgzOWNiYmYwYWM3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDE3NTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNTE1MDdlMmNlMjNmOWMxNGI4MWRjZTQ1MDFlMjJmODZiMTQ0NGY4OGVkMTU3MDZlMDQ4MjYxMThjNjc5NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D6itOGuluwk56g818cq-v-AdDjHlkqjJ3dAxCkeKDFw"></image></p>
</details> 

This popup always happens on my side when "Add to Playlist" are bugged (not full)

<details><summary>Bugged Add to Playlist (not full)</summary><p><image src="https://github.com/user-attachments/assets/9bf5f5cf-4b2e-4053-8bf1-fe80b450a59a"></image></p></details> 

<details><summary>Same popup happens when trying to add</summary><p><image src="https://github.com/user-attachments/assets/6ba8c903-1455-46d8-b7e1-6a1d3887fc2a"></image></p></details> 

Workaround: enqueue selected songs, then add to playlist from queue list

**Comment by twistios** [comment]
It seems that this part of the issue got fixed.
