### ISSUE TITLE
The outline border of "favourites" and "offline" is not showing in pure black theme 

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#36]
### Steps to reproduce the bug

Go to playlist and see "favourites" and "offline"

### Expected behavior

There should be a outline border like in dynamic theme 

### Actual behavior

No outline border 

### Screenshots/Screen recordings

![IMG_20231026_152439](https://github.com/fast4x/RiMusic/assets/127825700/386dc744-8295-4c3b-88c0-8ee9185cab15)
![IMG_20231026_152916](https://github.com/fast4x/RiMusic/assets/127825700/a6dd418d-c2a8-432b-b489-7ae773088db9)

### RiMusic version

Latest debug 

### Android version

11

**Comment by fast4x** [comment]
![Screenshot_20231026_171052](https://github.com/fast4x/RiMusic/assets/1484476/97f61932-f75c-4717-b36f-804bc2f63c9d)

Fixed available from version 0.6.6

**Comment by dainvincible1** [comment]
> ![Screenshot_20231026_171052](https://user-images.githubusercontent.com/1484476/278389478-97f61932-f75c-4717-b36f-804bc2f63c9d.png)
> 
> Fixed available from version 0.6.6

thanks
