### ISSUE TITLE
Mejorar las canciones nuevas

### ISSUE THREAD

**Issue by Noeliiarp26** [fast4x/RiMusic#3600]
### Description

No me salen las canciones ni todos los álbumes nuevos que sacan mis artistas favoritos como en Spotify. 

### Suggested Solution

L

**Comment by JeePopuwu** [comment]
Eso ya es depende del artista si sube en todas sus plataformas o no

Por ejemplo kessoku band apenas saca en Spotify saca en Youtube así que es más culpa de tu artista xd
