### ISSUE TITLE
Widget for home screen 

### ISSUE THREAD

**Issue by HWdriver** [fast4x/RiMusic#3601]
### Description

It's a shame how this isn't implemented yet

### Suggested Solution

Add a widget

**Comment by twistios** [comment]
It is with the latest version but very barebone and with many known issues.

**Comment by HWdriver** [comment]
> It is with the latest version but very barebone and with many known issues.

I can't even find the widget in the list. I got the app from Fdroid

**Comment by twistios** [comment]
Fdroid does not yet offer the latest version that is published on github. You either have to wait some time (I guess about 2 weeks) or download it via github.

**Comment by twistios** [comment]
I don't know about the other app stores.

**Comment by twistios** [comment]
https://apt.izzysoft.de/fdroid/index/apk/it.fast4x.rimusic/

This offers it already, I think it is related to fdroid.

**Comment by HWdriver** [comment]
Thanks

**Comment by HWdriver** [comment]
> It is with the latest version but very barebone and with many known issues.

Will it be updated soon?  Maybe reduce the space it takes up and have it show the last played song?

**Comment by fast4x** [comment]
Can download from Accrescent app store, https://accrescent.app
