### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Teleposse** [fast4x/RiMusic#3602]
### Steps to reproduce the bug

I wanted to update the application, but I don't know if that has happened. I get the following message
(The first one says if I want to update and the second one says it is not installed or something like that, you can check it if you want)

### Expected behavior

Update

### Actual behavior

A message that is not clear to me if it has been done or not

### Screenshots/Screen recordings

![IMG_20240908_155649](https://github.com/user-attachments/assets/593e2c39-c3d2-4c1b-8057-ca10c9a5e9c5)
![IMG_20240908_155640](https://github.com/user-attachments/assets/d93b2628-6b44-4850-9c32-cdf4b47bc15f)

### RiMusic version

0.6.48?

### Android version

Android 12

**Comment by twistios** [comment]
Go to Settings->About.
If you are using the github version, it should currently say 0.6.51 if it was updated correctly. Fdroid does not yet offer this version, but izzyondroid does, about the others I am not sure.

**Comment by twistios** [comment]
The messages you see are probably from the Android system. If you do not have the latest version, go to settings and check for updates again. Or manually download it via the release-page of the update.

**Comment by Teleposse** [comment]
I tried it twice, but the same thing happens to me.
![IMG_20240909_205342](https://github.com/user-attachments/assets/5e273eaa-cb43-46df-b4ed-4414c4c40797)
![IMG_20240909_205356](https://github.com/user-attachments/assets/06657228-7a21-44a6-a232-b3ef8ac085fc)
![IMG_20240909_205410](https://github.com/user-attachments/assets/5911624c-b4b0-4bef-8971-6ef061e015bf)
![IMG_20240909_205428](https://github.com/user-attachments/assets/fdf51fb8-31e9-4044-8d34-a863f934577d)
![IMG_20240909_205438](https://github.com/user-attachments/assets/899ba7c0-8e51-49de-a620-b29de1737890)
