### ISSUE TITLE
Use of piped account 

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#361]
### Description

See I understand fully that we cannot use Google trackers but can we use Piped accounts

### Suggested Solution

![Screenshot_20240109-011636](https://github.com/fast4x/RiMusic/assets/120176369/8dc48fa5-5b28-4385-9130-93dacf3b0e20)
![Screenshot_20240109-012700]
(https://github.com/fast4x/RiMusic/assets/120176369/1f2cb4ee-581d-437b-99c4-8176bf8896f4)
![Screenshot_20240109-012841](https://github.com/fast4x/RiMusic/assets/120176369/1c4f3c24-3489-4fe9-9172-cee39edf7a97)

This is LibreTube which uses piped api to show us video and video recommendations are pretty dammn good. Each user can select the piped server according to their region and create piped account.
Can we just user it??

### Additional Context

🥺 Please don't deny this

**Comment by DeadSecTr** [comment]
I think there is no need to add any Login function,cuz we can backup our Playlists in a file...

**Comment by ikanakova** [comment]
This is a duplicity again (#278), please @Logan7899 search the issue first before creating another one. @fast4x can you please close this issue.

**Comment by Logan7899** [comment]
> This is a duplicity again (#278), please @Logan7899 search the issues first before creating another one. @fast4x could you please close this issue.

Myy bad my bad. I wil do research
