### ISSUE TITLE
RiMusic keeps crashing when i change the song's position in a playlist

### ISSUE THREAD

**Issue by CaterpillarZipbomber** [fast4x/RiMusic#3613]
### Steps to reproduce the bug

1. open a playlist
2. unlock the position lock (if not already unlocked)
3. try to put a song up or down in the playlist

if the song starts to disappear when you move it, it should close the app when you move it past a song

### Expected behavior

The song should change place in the playlist

### Actual behavior

RiMusic closed and after retrying it closes again with a popup saying "RiMusic keeps crashing"

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/877c200e-7fda-48fd-9df7-9a1c09e9313f

### RiMusic version

0.6.49.2

### Android version

Android 14 

### Additional information

the playlist contains 40 songs

**Comment by twistios** [comment]
If it is the same as #3542 then you can simply download latest version.
