### ISSUE TITLE
A feature about queue in Rimusic

### ISSUE THREAD

**Issue by Omkar1GH** [fast4x/RiMusic#3615]
### Description

We should be able to change or edit the queue while listening to music 
[Rimusic feature add.pdf](https://github.com/user-attachments/files/16933597/Rimusic.feature.add.pdf)

### Suggested Solution

The listener should be able to edit the queue.   Like if a Pearson listening to music want to listern a song which is at 10th position in queue he should be able to edit and place it on 4th position or any position as he/she wishes 

### Alternatives

The vimusic has this feature. Listeners can edit the queue of songs as he wants
![image](https://github.com/user-attachments/assets/ba20b165-55b5-45f5-b90d-2600b86455cd)

### Additional Context

We can't able to edit the queue of songs while  listening to the song in the Rimusic app

**Comment by twistios** [comment]
This is already available. You just need to unlock the order, then you can do it the same way as ViMusic does.

**Comment by Omkar1GH** [comment]
Thanks brother I didn't noticed

**Comment by Omkar1GH** [comment]
I understand I didn't noticed it earlier. I'm sorry if I wasted ur time
