### ISSUE TITLE
Deep Link

### ISSUE THREAD

**Issue by Frank-161** [fast4x/RiMusic#3617]
### Description

Create deep links to share on Instagram stories that redirect to the RiMusic app.

### Suggested Solution

Maybe connected RiMusic to Firebase so you can create the deep links

### Alternatives

![Screenshot_20240909_131632_Instagram](https://github.com/user-attachments/assets/ab52eafe-5d5c-40bb-b4ff-13f7336fbfa7)

**Comment by fast4x** [comment]
RiMusic not have a server it'a an app installed on local.

**Comment by fast4x** [comment]
Firebase require login tracking system...
