### ISSUE TITLE
Se traba mi celular completo

### ISSUE THREAD

**Issue by danniel-contreras** [fast4x/RiMusic#3618]
### Steps to reproduce the bug

Cambie el tema, y mostrar ocultar algunos botones

### Expected behavior

Mi telefono  no responde y se reinicia

### Actual behavior

Mi telefono  no responde y se reinicia

### RiMusic version

0.6.49.2

### Android version

HONOR X8a Android 12

**Comment by zef126** [comment]
I think English is better for bug reporting...

**Comment by fast4x** [comment]
This occur when?
