### ISSUE TITLE
[Feature]: Reset to Default Option in Every Section

### ISSUE THREAD

**Issue by tiwna16** [fast4x/RiMusic#3619]
### Description

The App has so many customization opposition in app.One of the reason why we all love it.But sometimes after customizing the User Interface/Player Appearance/Data/Misc ,We feel like the default settings of the section was much more better.But Currently,There isn't any reset to default option in those sections of settings.

### Suggested Solution

An Option of reset to default in **every section** of the settings. If we gonna take the example Player Interface,Let's take there has an option at last in the section which can reset the Player Interface to default.

### Additional Context

It's already implemented in the Quick Picks section.
Please implement it in every section of the settings.

**Comment by fast4x** [comment]
Implemented in ui and appearance settings, other settings are minimal...
Available from version 0.6.52

**Comment by tiwna16** [comment]
> Implemented in ui and appearance settings, other settings are minimal... Available from version 0.6.52

Appreciate it.
Thanks a lot❤
