### ISSUE TITLE
Back/Play-Stop/Forward button bouncing

### ISSUE THREAD

**Issue by DeadSecTr** [fast4x/RiMusic#362]
### Steps to reproduce the bug

When a song is playing, and you jump forward or backward on the waveform, the rewind/play-stop/forward button bounces up and down

See att.video

### Expected behavior

This should i thing not do

### Actual behavior

See above

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/90558189/a7d8734c-f146-462f-8d53-5124561af8b7

### RiMusic version

0.6.16.1

### Android version

Android 13

**Comment by ikanakova** [comment]
I'm having the same problem on Android 14. Additionally, the wavy timeline takes longer to start music after skipping than the default timeline.

**Comment by DeadSecTr** [comment]
Yup...can confirm that

**Comment by fast4x** [comment]
> Sto riscontrando lo stesso problema su Android 14 (versione 0.6.15.1). Inoltre, la timeline ondulata impiega più tempo per avviare la musica dopo il salto rispetto alla timeline predefinita.

It depend by timeline internal calculate, time to wavy timeline equals 2x normal timeline

**Comment by fast4x** [comment]
Fixed bounced, available from version 0.6.18

**Comment by DeadSecTr** [comment]
LEGEND!

**Comment by fast4x** [comment]
@DeadSecTr tieni aperto il ticket in modo che lo chiudo al rilascio della prossima versione...
