### ISSUE TITLE
Searching in downloads

### ISSUE THREAD

**Issue by zef126** [fast4x/RiMusic#3621]
### Description

We can search in the downloaded titles without internet connection.

### Suggested Solution

Create a special place for downloads with a searching bar only for them.

### Alternatives

To sort better the download but it will not be better than a searching bar.

### Additional Context

When we try to find a download in a place without connection, it is super long if it isn't on the top because we must scroll slowly to find it.

**Comment by twistios** [comment]
Do you mean this? Or something else?
![Screenshot_20240910_093008](https://github.com/user-attachments/assets/c560765e-6992-42c8-9e5a-adeb937f4609)
