### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by watchdog-20** [fast4x/RiMusic#3627]
### Description

a slider that pops up when loudness normalization is turned on 
![Screenshot_20240910-164622](https://github.com/user-attachments/assets/b90822db-b49e-440d-b9d8-85531d3944f9)

### Suggested Solution

When the loudness normalization is toggled
You would be able to adjust the gain up or down with a slider 
![Screenshot_20240910-165253](https://github.com/user-attachments/assets/4113dd4a-f732-488a-b5a1-fc95411899f4)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.52
