### ISSUE TITLE
Error al agregar música local a la lista de reproducción 

### ISSUE THREAD

**Issue by NormanMeneses** [fast4x/RiMusic#3629]
### Steps to reproduce the bug

1. Canciones 
2. Busco los archivos de música local
3. Menu de tres puntos (...)
4. Seleccionar/Deseleccionar 
5. Selecciono el archivo de música a agregar 
6. Menu de tres puntos (...)
7. Agregar a lista de reproducción 

### Expected behavior

Agregar a la lista el nuevo archivo 

### Actual behavior

No lo agrega y genera un error 

### Screenshots/Screen recordings

![Screenshot_2024-09-10-18-20-02-105_it fast4x rimusic](https://github.com/user-attachments/assets/653a5a2c-faa5-4109-ab67-d37f7c7d5dc7)

### RiMusic version

0.6.51

### Android version

Android 11

**Comment by fast4x** [comment]
Fixed, available from version 0.6.52
