### ISSUE TITLE
Can't Download Song

### ISSUE THREAD

**Issue by aputtt** [fast4x/RiMusic#363]
### Steps to reproduce the bug

1.I opened the RiMusic app
2.Then I play any song 
3.I opened the music player
4.I clicked the download button at the bottom left

### Expected behavior

The download should start immediately and be able to play music without the internet

### Actual behavior

But instead the application suddenly forces close and says "RiMusic has been stopped" And the music stops

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/133711959/cb0e303e-cab0-411b-a877-c8351de322d1

### Logs

Sorry I don't understand how

### RiMusic version

0.6.16.1

### Android version

Android 11

### Additional information

This happens on all songs and this is no exception, I hope you can fix it soon. I really like your music app so thank you

**Comment by fast4x** [comment]
Try to set new size of cache player and cache download on cache settings.

Close, reopen and try again.

**Comment by fast4x** [comment]
Feedback please
