### ISSUE TITLE
Alternative versions 

### ISSUE THREAD

**Issue by papi2006** [fast4x/RiMusic#3631]
### Description

It would be great if there was an option where you could view alternative versions of a song (slow, fast, remix, instrumental).Thank you and the app is excellent .

An example:

![Screenshot_20240910-234014](https://github.com/user-attachments/assets/95fe1c5c-5c4b-4f14-981c-324bb23b8450)

### Suggested Solution

A possible solution that I suggest would be to add an option to the playlist that appears for each song, right there, about the alternative versions of the song that is being played.

A demonstration:

![Screenshot_20240910-235124](https://github.com/user-attachments/assets/fd5dd12a-c9a5-41f7-b8f8-de1ec7757024)

### Additional Context

It would be great to add that option because sometimes it's a bit overwhelming to be able to search for alternative versions of each song and it would be easier and faster to have it all in one click.

**Comment by fast4x** [comment]
This is because it was a feature request from several people.
