### ISSUE TITLE
[Feature]: RiMusic playlists

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#3635]
### Description

RiMusic could have custom playlists that do not have the 5k songs limit.

### Suggested Solution

The playlist should behave mostly the same as a normal playlist.
- playing a number of random songs should be the minimum (this would probably also work for a ridiculous amount of songs)
- maybe normal behavior if small enough (I.e. compatible to normal playlists and could replace them for custom playlists)

### Alternatives

Playing from multiple playlists at once.

### Additional Context

As it seems to be possible for the songs tab and also for queue it seems to work, it probably is not very hard to implement.
Maybe database has to be modified to support these playlists.
Maybe both options should be implemented.

**Comment by aneesh1122** [comment]
you can change the playlist limit yourself. search for 5000 and change it to whatever number you want. I did not do it because this will result in slowing down the app and those people who are using ancient devices won't have a good experience.

**Comment by twistios** [comment]
I think the "shuffle playlist"-playlist variant should be less of a problem for old devices.

**Comment by fast4x** [comment]
Playlist not have limit of 5000 songs, YTM have this limit ..

**Comment by fast4x** [comment]
Btw shuffle from multiple playlists at once sounds great. Would be added a shuffle songs in home playlists.

**Comment by aneesh1122** [comment]
> Playlist not have limit of 5000 songs, YTM have this limit ..

https://github.com/fast4x/RiMusic/issues/1590#issuecomment-2067788728

You said it's 5000 here so that's what I was going with. Have you increased the limit?

**Comment by aneesh1122** [comment]
> Btw shuffle from multiple playlists at once sounds great. Would be added a shuffle songs in home playlists.

So if I go to pinned playlists and select shuffle, songs from all the pinned playlists will be shuffled and put in queue. Right? That will be awesome.

**Comment by twistios** [comment]
> It's limit to timeout reading operation for YTM music playlist...

So "RiMusic" playlists would not have the timeout problem or does this also happen for them?

**Comment by fast4x** [comment]
> > Btw shuffle from multiple playlists at once sounds great. Would be added a shuffle songs in home playlists.
> 
> So if I go to pinned playlists and select shuffle, songs from all the pinned playlists will be shuffled and put in queue. Right? That will be awesome.

Yes would be very nice

**Comment by fast4x** [comment]
I'll try to implement today

**Comment by fast4x** [comment]
Implemented cross shuffle songs  between playlists, available from version 0.6.52
