### ISSUE TITLE
Going to previous track ALWAYS plays the previous song instead of restarting the current song

### ISSUE THREAD

**Issue by u-daygupta** [fast4x/RiMusic#3636]
### Steps to reproduce the bug

1. Play a song
2. Skip forward
3. Skip back after a majority of the song is finished

### Expected behavior

The song restarts

### Actual behavior

The previous song plays

### RiMusic version

0.6.51

### Android version

Android 14

**Comment by fast4x** [comment]
wait for next release maybe it's fixed
