### ISSUE TITLE
[Feature]: Import playlist from spotify.

### ISSUE THREAD

**Issue by Sahil-Rajoria** [fast4x/RiMusic#3638]
### Description

Please, i request you to add the feature in RiMusic app to import playlists from spotify by login. It is very difficult to create playlist of 300+ songs again in RiMusic.

### Suggested Solution

Blackhole and spotube have this feature and working perfectly. But i want to use RiMusic.

**Comment by fast4x** [comment]
Hello, isn't possible in direct mode, can transfer playlists to YTM and import in RiMusic.
