### ISSUE TITLE
Lyrics and thumbnails won't download 

### ISSUE THREAD

**Issue by HWdriver** [fast4x/RiMusic#3639]
### Steps to reproduce the bug

Downloading from playlists and listening from downloaded songs without internet the lyrics and thumbnails don't show up. 

### Expected behavior

That they do work

### Actual behavior

They don't 

### RiMusic version

Latest on GitHub. Nov 11 iirc

### Android version

14

**Comment by HWdriver** [comment]
Not Nov 11th, it is the latest version released last week that I have

**Comment by fast4x** [comment]
Normally lyrics download manually as song.

**Comment by HWdriver** [comment]
> > > Normally lyrics download manually as song.
> > 
> > 
> > So I have to manually download the lyrics to each song?
> > And what about the thumbnails?
> > And also some tracks won't download
> 
> yes
> 
> thumbnail it's diwnloaded when playing first time... for now...
> 
> download not start but same song play normally?

Sorry I didn't get you

Could you refrase it?

**Comment by fast4x** [comment]
`So I have to manually download the lyrics to each song?`

**yes**


`And what about the thumbnails?`

**thumbnail is downloaded at first listen, for now**


`And also some tracks won't download`

**Some songs are not downloaded but played?**

**Comment by fast4x** [comment]
Must enable lyrics type

**Comment by HWdriver** [comment]
> Must enable lyrics type

How?

**Comment by fast4x** [comment]
Tap on thumbnail or click on lyrics button in action bar inside player.

**Comment by HWdriver** [comment]
> Tap on thumbnail or click on lyrics button in action bar inside player.

So I have to view the lyrics once and they'll be available offline?

**Comment by fast4x** [comment]
Yes
