### ISSUE TITLE
Download button in notification/swipe down area

### ISSUE THREAD

**Issue by DeadSecTr** [fast4x/RiMusic#364]
### Description

Do we really need this button here? I mean, one might accidentally hit download/delete while trying to like, causing unnecessary mobile data usage. In my opinion, just the like/heart symbol would be absolutely sufficient.

### Suggested Solution

Remove the download button in the notification/swipe down area 

### Additional Context

![Screenshot_20240109-015656](https://github.com/fast4x/RiMusic/assets/90558189/5ff4cbd8-2e6c-48da-b67e-f534ee1131e0)

**Comment by Logan7899** [comment]
Where are ü now @fast4x

**Comment by fast4x** [comment]
I can make buttons optional by settings. So those who don’t want them can disable.

**Comment by fast4x** [comment]
Added setting options to enable/disable like and download button on background player.
Available from version 0.6.17
