### ISSUE TITLE
Shuffle mode of artists

### ISSUE THREAD

**Issue by Londoner777** [fast4x/RiMusic#3640]
### Description

Hello there! I really like your app its beautiful! Is it possible to make a shuffle mode for the all of the artists on which you have subscribed? Like in random position took one or more songs from any of artists and shuffle them? Thank you for your work!

### Suggested Solution

Im not a programmer unfortunately (

**Comment by fast4x** [comment]
Implemented, it work with all artists songs in RiMusic database, available from version 0.6.52

**Comment by Londoner777** [comment]
Thank you!
