### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Teleposse** [fast4x/RiMusic#3641]
### Steps to reproduce the bug

The update is not downloaded, even though I get a notification every time I enter the application. 

### Expected behavior

Update

### Actual behavior

No update😔

### Screenshots/Screen recordings

![IMG_20240912_164229](https://github.com/user-attachments/assets/e2cbb233-2b48-4291-8304-4bf4a14bae89)
![IMG_20240912_164246](https://github.com/user-attachments/assets/b983a066-a8f5-457f-ab08-bb7b79fb4cba)
![IMG_20240912_164308](https://github.com/user-attachments/assets/88d72483-8af6-4e5d-a6d8-c47e5fd89bfa)
![IMG_20240912_164317](https://github.com/user-attachments/assets/211b0900-3754-4c43-b573-7ca79f508c0d)
![IMG_20240912_164328](https://github.com/user-attachments/assets/34c04c45-2e70-4870-9f5a-9707c9962394)

### RiMusic version

0.6.48?

### Android version

Android 12

**Comment by fast4x** [comment]
You have to update the app from the same source, so it won’t work.

**Comment by Teleposse** [comment]
> You have to update the app from the same source, so it won’t work.

I have tried all the Options several times (in fact there is one that has a 404 error, the last one, the one with the moon, and it still doesn't work for me. For now I continue using the version without updating
