### ISSUE TITLE
Favorite button in Android Auto stops reflecting favorite status after a few uses/songs

### ISSUE THREAD

**Issue by Tre916** [fast4x/RiMusic#3642]
### Steps to reproduce the bug

Once launched into Android Auto and songs are playing, after playing and toggling favorite status on like 5-20 songs the favorite button will stop showing songs as favorited. It seems like the button still will favorite songs, but you have to have the app open and look at the phone to check if the song has been favorited, it also doesn't seem to let you un-favorite songs when it's stuck like this.

### Expected behavior

Favorite button should toggle between a full and outlined heart shape to indicate a song is favorited or not.

### Actual behavior

After between 5-20 the button will function as a "favorite on" button if you check in the app on the phone but will not show a full heart indicating the song has been favorited in Android Auto until the app has been closed and Android Auto disconnected and re-connected.

### RiMusic version

0.6.51

### Android version

Android 14

**Comment by fast4x** [comment]
Ill try to reproduce
