### ISSUE TITLE
I can't listen to any new songs 

### ISSUE THREAD

**Issue by thecat840** [fast4x/RiMusic#3646]
### Steps to reproduce the bug

I try to search for any song (that has not been previously downloaded) and I get "no compatible audio format found"

### Expected behavior

No compatible audio format found

### Actual behavior

This happened instead of playing the song 

### Screenshots/Screen recordings

![Screenshot_20240912-195841](https://github.com/user-attachments/assets/c5323dd7-ca27-4d0f-8b01-e9ad078cf470)

### RiMusic version

0.6.51

### Android version

Android 13

### Additional information

I have checked on another device and the same thing happens to me, so I rule out that it is a problem only with my cell phone.

**Comment by id8547854** [comment]
gg rip

**Comment by fast4x** [comment]
Try use vpn or proxy
