### ISSUE TITLE
Cannot import backup on Android tv

### ISSUE THREAD

**Issue by Jak61** [fast4x/RiMusic#3647]
### Steps to reproduce the bug

I'd like to import a backup from my phone to RiMusic on my google tv but is says I have no apps to do so. I have 'solid explorer' installed and the backup file is in the download folder on google tv.
Is there a way to do this.
Thanks

### Expected behavior

no response

### Actual behavior

no response

### RiMusic version

0.6.51

### Android version

Google tv with chromecast. Latest update installed

**Comment by fast4x** [comment]
Copy file into directory on Google tv, open RiMusic, go to directory and click on backup file.

**Comment by Jak61** [comment]
Thanks for your reply. If you mean the RiMusic directory I cannot access it. It's kinda locked. Do you know a file explorer that could give me access to apps directory?

I'll keep trying 
Thanks

**Comment by fast4x** [comment]
FX File Explorer
