### ISSUE TITLE
Audios don't load

### ISSUE THREAD

**Issue by laloespana6** [fast4x/RiMusic#3648]
### Steps to reproduce the bug

I selected an audio and it gives error while playing

### Expected behavior

The audio should play

### Actual behavior

Mark that the audio was not found

### Screenshots/Screen recordings

![Screenshot_2024-09-13-01-18-57-986_it fast4x rimusic](https://github.com/user-attachments/assets/54d1f388-e74f-4ff1-911f-10bb39a8389f)

### RiMusic version

0.6.51

### Android version

Android 13

**Comment by fast4x** [comment]
Try use von or proxy

**Comment by id8547854** [comment]
No google account = no access youtube music.

**Comment by fast4x** [comment]
What?

**Comment by id8547854** [comment]
Google hard block free proxy protocol.
Clear vds - work.
My ip - no work.
