### ISSUE TITLE
Option to hide explicit content

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#3651]
### Description

An option to hide explicit content would be nice, for example when listening to music with your children.

### Suggested Solution

X

**Comment by ALMIGHTY-VC** [comment]
Check miscellaneous>parental controls wen???

**Comment by fast4x** [comment]
> Check miscellaneous>parental controls wen???

Yes it's partially implemented, I had forgotten...

**Comment by fast4x** [comment]
i'll check now

**Comment by fast4x** [comment]
Parental control implementation completed, available from version 0.6.52
Thank you for remembering
