### ISSUE TITLE
Broken \n when refetching songs.

### ISSUE THREAD

**Issue by betmobil** [fast4x/RiMusic#3652]
### Steps to reproduce the bug

1. start a song 
2. try to refetch it

### Expected behavior

\n makes newline

### Actual behavior

\n is viewed as text

### Screenshots/Screen recordings

![Screenshot_20240913-202714](https://github.com/user-attachments/assets/c02c6d63-66c8-485e-ae68-82e43f8af0bc)

### RiMusic version

0.6.51

### Android version

Android 10

**Comment by fast4x** [comment]
Next version it's fixed
