### ISSUE TITLE
Home bar

### ISSUE THREAD

**Issue by Alanpa1** [fast4x/RiMusic#3657]
### Description

Please my idea is 
Remove Artist and Album from Home navigation bar 
And add it on Playlist bar
![Screenshot_20240914-070234~2](https://github.com/user-attachments/assets/ae018e97-b261-47df-93ec-7b5aba5ea833)
Make it like this and make options for use to choose between this and other which already in Ri music . please 

### Suggested Solution

..

### Alternatives

.

### Additional Context

.

**Comment by Alanpa1** [comment]
Please make this as I feel Very simple with that button 
![Screenshot_20240914-070642~2](https://github.com/user-attachments/assets/3a5506a8-67c6-4fe9-81ed-0735fb8ff7d4)

**Comment by Alanpa1** [comment]
Remove Artist and Album and add it on Playlist tab it would be nice

**Comment by Alanpa1** [comment]
And make this one modern 
![Screenshot_20240914-070234~2](https://github.com/user-attachments/assets/f4001095-f58f-4fcf-b761-6bb46e244418)

**Comment by aneesh1122** [comment]
I don't think it's a good idea but it's upto fast4x

**Comment by fast4x** [comment]
It not make sense because artist and album are not playlists.

**Comment by fast4x** [comment]
> And make this one modern 
> ![Screenshot_20240914-070234~2](https://github.com/user-attachments/assets/f4001095-f58f-4fcf-b761-6bb46e244418)
> 

this is user interface of Simp Music
