### ISSUE TITLE
Add songs to playlist from the playlist's section

### ISSUE THREAD

**Issue by Kratosgado** [fast4x/RiMusic#3658]
### Description

we can't add multiple songs to a playlist simultaneously, even 2 gives an error about it stopping the main ui thread
![Screenshot_20240913_032604](https://github.com/user-attachments/assets/27e12a17-4a1a-4e81-a292-4d12d7a54fa8)

### Suggested Solution

When we open a playlist, it is easier to add songs to the playlist from there by selecting them from the songs list screen. 
and also being able to select multiple songs and adding it to a playlist would be better.

**Comment by fast4x** [comment]
Use latest version it's fixed
