### ISSUE TITLE
Blur slider still uses the old slider

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#3659]
### Steps to reproduce the bug

Hold the player screen

### Expected behavior

It should use the new slider

### Actual behavior

It still uses the old slider

### Screenshots/Screen recordings

![Screenshot_20240914-133830](https://github.com/user-attachments/assets/8b408fcc-cf1e-4171-894f-84cd6b6dd2b8)

### RiMusic version

0.6.52

### Android version

Android 14

### Additional information

I think you should remove the blur slider when you hold the player screen since there's already a blur slider when you hold the play/pause button

**Comment by aneesh1122** [comment]
I'm taking a break from developing but when I get back to it I'll add some things to that box.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.53

**Comment by fast4x** [comment]
> I'm taking a break from developing but when I get back to it I'll add some things to that box.

Done
