### ISSUE TITLE
'Show song cover' is not applying 

### ISSUE THREAD

**Issue by mohandan1** [fast4x/RiMusic#366]
### Steps to reproduce the bug

Appearance > lock screen >show song cover

### Expected behavior

Song cover should show on lock screen as wallpaper 

### Actual behavior

Song cover is not showing on lock screen.

### RiMusic version

0.6.16.1

### Android version

Android 12

### Additional information

Song cover is not showing as lockscreen wallpaper..

**Comment by Logan7899** [comment]
Bro there is no such option

**Comment by fast4x** [comment]
Not applicable.

**Comment by mohandan1** [comment]
![Uploading Screenshot_20240109_133753.jpg…]()

**Comment by ikanakova** [comment]
From [Reddit](https://www.reddit.com/r/AndroidQuestions/comments/xyqo0j/lockscreen_cover_art_for_android_12/):
> So it turns out that Android had that feature. From Android 5 through Android 10. [Android 11 removed it, without explanation and despite protest](https://9to5google.com/2020/08/02/android-11-lockscreen-art/). (See also: [r/androidapps](https://www.reddit.com/r/androidapps/)/comments/i1ej83/-/)

**Comment by fast4x** [comment]
> ![Uploading Screenshot_20240109_133753.jpg…]()
> 

![Screenshot_2024-01-09-09-34-06-331_lockscreen.jpg](https://github.com/fast4x/RiMusic/assets/1484476/b8c66f3e-67c5-48ee-ab43-3c39686d52dc)

This Is on Android 13 and same in Android 10 bit not in Android 11 unfortunatly

**Comment by fast4x** [comment]
> Explanation also in [FAQ](https://github.com/fast4x/RiMusic/wiki/FAQs#-why-no-longer-show-album-art-on-the-locksceen-on-android-since-version-11).

good

**Comment by mohandan1** [comment]
But I have Android 12.....!!

**Comment by ikanakova** [comment]
> But I have Android 12.....!!

Because Android removed it in version 11, it hasn't been available since version 11.
