### ISSUE TITLE
Queue max songs

### ISSUE THREAD

**Issue by PN88NP** [fast4x/RiMusic#3665]
### Steps to reproduce the bug

Go to any artist profile and play the song .you can see that music is played but the queue for the next songs is limited

### Expected behavior

All the songs should be shown in the queue 

### Actual behavior

Only limited songs are shown in the queue

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/3f14dca8-e288-4dc1-bdcf-21bb651cc70a

### RiMusic version

RiMusic v0.6.52

### Android version

Android 13

### Additional information

There is an other issue. Sometimes when a song is added to favourite the song doesn't get listed at the top

**Comment by fast4x** [comment]
set limit from ui settings

**Comment by PN88NP** [comment]
It doesn't work even though I set a limit

**Comment by PN88NP** [comment]
> set limit from ui settings

It doesn't work even though I set a limit
