### ISSUE TITLE
Can't find the way to import CSV files into RiMusic

### ISSUE THREAD

**Issue by Spikes443** [fast4x/RiMusic#3672]
### Steps to reproduce the bug

Well I have this playlist of all music I had downloaded, had to reset the app and was hoping I could get all music back by just importing back the CSV file I exported days earlier, I can't find the 'import' option anywhere 

### Expected behavior

I've tried reading through all issues but I haven't got a clear solution yet, I thought maybe sharing the csv file to the RiMusic it might work but the app doesn't pop up as an option to share the file

### Actual behavior

The file either has the option to open with some pdf reader or text editing app so I'm certain this might not be the way of doing it 

### RiMusic version

0.6.48

### Android version

Android 10

### Additional information

I know you guys may have addressed this situation quite a lot but I simply don't know how to do it or if there's any external sort of thing I might need for it to actually work, anyways since I read a lot of issues regarding this theme I may already have stumbled upon the solution but couldn't understand it or flew completely over my head

**Comment by aneesh1122** [comment]
![IMG_20240915_020211_661.jpg](https://github.com/user-attachments/assets/f7c85e20-da7d-465d-b620-c68c899d587c)

Use this icon

**Comment by Subhi06** [comment]
it is responding that the app stops it
