### ISSUE TITLE
Descarga de Canciones Mejorada

### ISSUE THREAD

**Issue by Yaelmp** [fast4x/RiMusic#3674]
### Description

Cuando escuchas una canción completa se descarga y se guarda en el cache, pero si por algún motivo borras el cache de RIMUSIC se pierden esas canciones.

### Suggested Solution

Qué las canciones que sean descargas de cache, aparezca un botón o algo así que te indique si la quieres descargar para siempre o la quieres mantener en el cache de la aplicación 

### Additional Context

En el apartado de "descargas" ay un problema, no se pueden borrar fácilmente las canciones porque se traba, debería a ver un botón para borrar las canciones.

**Comment by fast4x** [comment]
It’s normal, the cache is temporary, in order not to delete songs you have to download them from the download button.
