### ISSUE TITLE
Playing previous songs

### ISSUE THREAD

**Issue by Addriann1577** [fast4x/RiMusic#3680]
### Steps to reproduce the bug

This bug seems to occur randomly after playing a few songs.

### Expected behavior

When playing should jump into the next song

### Actual behavior

When a song ends and is about to play the next one in queue usually it does not jump into the next song but into a previous track and begin to play the songs repeatedly.

### RiMusic version

0.52

### Android version

14

**Comment by Someoneoutrfsk** [comment]
It's been happening to me too.
