### ISSUE TITLE
Songs duplicate in albums

### ISSUE THREAD

**Issue by Kurrode** [fast4x/RiMusic#3681]
### Steps to reproduce the bug

Open any album

### Expected behavior

There is one song per title

### Actual behavior

There are multiple copies of some songs

### Screenshots/Screen recordings

![Screenshot_2024-09-15-19-57-24-471_it fast4x rimusic](https://github.com/user-attachments/assets/8ca1ea85-394c-4440-9fc8-90c1daf6a6ea)

### RiMusic version

0.6.52

### Android version

Android 14

**Comment by Kurrode** [comment]
@fast4x At least give me the option to remove songs locally from albums

**Comment by fast4x** [comment]
after will sync again...

**Comment by Imdniyf** [comment]
> after will sync again...

What does that even mean?

**Comment by Kurrode** [comment]
> after will sync again...

a?

**Comment by gastbr** [comment]
Same here. It only happens to me in one specific album. The bug fixes when the whole app data is deleted, but I don't want to lose the rest of my saved info. The bug reappears when the data is restored.

**Comment by gastbr** [comment]
I managed to quickfix it locally by manually modifying the .db file generated at exportation, deleting the song registers at SongAlbumMap by running this SQL line on the DB:

`DELETE FROM SongAlbumMap WHERE albumId = (SELECT id FROM Album WHERE title = 'album_title' AND authorsText='artist_name');`

_(If you use that SQL, don't forget to change album_title and artist_name for the one you're trying to fix)._

Restoring this modified database fixes the problem, but the app soon messes up another album. Good news is it's always only one album that is messed up, so I keep doing this until the broken album is one I don't care too much about.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.60
