### ISSUE TITLE
[Feature]: Improvement in music player Idea

### ISSUE THREAD

**Issue by OriginalJuani** [fast4x/RiMusic#3684]
### Description

The idea is to put an option so that the player is the same as the original ViMusic (which has a much more fluid swipe down animation and the player touches the bottom of the screen).

### Suggested Solution

The solution would be an option to make the player look like this (I am reffering to the bottom player and the swipe down animation):

https://github.com/user-attachments/assets/6837b00d-a674-42a6-a5b8-2281456b8c2b

This is what it looks like in RiMusic (there is no swipe down animation and the player does not touch the bottom of the screen):

https://github.com/user-attachments/assets/03d06b06-e573-48a1-95af-3e72e4bcc918

**Comment by fast4x** [comment]
Already customizable in any aspect, you can create exactly what you mean as ViMusic player.

**Comment by OriginalJuani** [comment]
oh thanks! I dont see the option to make that the player touches the bottom of the screen or that it has an animation when sliding down, could you help me?

**Comment by fast4x** [comment]
Go to ui settings, switch to ViMusic mode or go to player appearance settings, change player type and much much more

**Comment by OriginalJuani** [comment]
> Go to ui settings, switch to ViMusic mode or go to player appearance settings, change player type and much much more

I looked at all the RiMusic settings being in ViMusic and RiMusic theme and I can't make any of them look like ViMusic (the player touching the bottom of the screen and the slide down animation), the only options that appear are "Player Position" (select if the position of the player is bottom or top), "Player Type" (which changes how the main player looks) etc, but there is no option that changes if the player touches the bottom of the screen, greetings and I would appreciate if you can help :>

**Comment by contact-maximux** [comment]
add auto lyric mode, so that I can listen song with lyric without pressing lyric button after every song

**Comment by ALMIGHTY-VC** [comment]
So you mean when the music is paused on the miniplayer and you play it. It ahould go to the bottom i. E like out of your display and the the full screen player animation should pop up from the bottom sliding towards the top

**Comment by ALMIGHTY-VC** [comment]
> add auto lyric mode, so that I can listen song with lyric without pressing lyric button after every song

Please make a seperate request for it this allows you and other users to suggest improvement and discuss about the suggestions/bugs in a organized way.
