### ISSUE TITLE
Broken RPC

### ISSUE THREAD

**Issue by Clyde6790pGIT** [fast4x/RiMusic#3694]
### Steps to reproduce the bug

Enable Discord RPC
Listen to a song

### Expected behavior

RPC works correctly, and does not fall behind and loads images quickly

### Actual behavior

RPC works horribly, pictures do not load, and is super late.

### Screenshots/Screen recordings

![Screenshot_20240917-073343_Discord](https://github.com/user-attachments/assets/be7bc33a-6a08-4b27-b7e4-274c8b780bd5)

### RiMusic version

Latest FOSS Release

### Android version

Android 14

**Comment by fast4x** [comment]
For now images are not supported

**Comment by OrangeZXZ** [comment]
I noticed that it takes time to disappear after app closing (idk if it can be patched)

**Comment by faustaahmad** [comment]
> I noticed that it takes time to disappear after the app is closed (I don't know if this can be fixed).

It takes quite long time, and cant be re-initialized by restarting RiMusic
Idk how to consistently trigger it, perhaps by going offline

**Comment by Clyde6790pGIT** [comment]
The Kizzy https://github.com/dead8309/Kizzy RPC app handles the song rpc better and has a Spotify RPC appearance in it as well

**Comment by Loughty** [comment]
> For now images are not supported

Hi, exist the possibility of show the song without the empty image frame meanwhile (only the text with the song's name and artist)? or with a placeholder image?
