### ISSUE TITLE
Se pierde la configuración cuando cambia el tema 

### ISSUE THREAD

**Issue by NormanMeneses** [fast4x/RiMusic#3696]
### Steps to reproduce the bug

1. Ir a ajustes 
2. UI
3. Interfaz en uso 

### Expected behavior

Solo cambie el tema. La interfaz

### Actual behavior

Se pierde toda la configuración como los botones de abajo. Se reset la configuración.

### RiMusic version

0.6.52

### Android version

Android 11

**Comment by fast4x** [comment]
Yes
