### ISSUE TITLE
Podcast

### ISSUE THREAD

**Issue by Frank-161** [fast4x/RiMusic#3697]
### Description

Thanks for the app 👍 I see that not all YouTube podcasts appear and it is not so easy to search for them

### Suggested Solution

It would be great to have a section on the podcast home page, for example: quick selection, songs, podcast and more. Thanks for everything 👍

**Comment by fast4x** [comment]
let me an example please

**Comment by Rm-fr-y** [comment]
I am having the same issue, an example is the Waveform Podcast by MKBHD.
