### ISSUE TITLE
Weird logo display on splash screen.

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#37]
### Steps to reproduce the bug

1. Open RiMusic-Debug (latest from Actions)
2. Splash screen (see Screenshot)

### Expected behavior

uncut logo

### Actual behavior

badly cropped logo

### Screenshots/Screen recordings

![Screenshot_20231026-122643](https://github.com/fast4x/RiMusic/assets/38765251/f6aa92be-5d09-4a89-8559-9c7813bc0e36)

### RiMusic version

0.6.6

### Android version

Android 10

### Additional information

I think there should be an app icon on the splash screen and the text MUSIC below it (as logo only vertically). I'll make it if you want, but probably not until Sunday night.

**Comment by fast4x** [comment]
Confirmed, it was fixed yesterday and will be available in version 0.6.6

**Comment by fast4x** [comment]
![IMG-20231026-WA0000.jpg](https://github.com/fast4x/RiMusic/assets/1484476/9728a031-7ae4-4fe3-b155-924ba78d7bf7)

**Comment by fast4x** [comment]
Committed logo icons, can try with new

**Comment by fast4x** [comment]
![Screenshot_20231026_151301](https://github.com/fast4x/RiMusic/assets/1484476/10914137-62b9-4ba7-9085-7769fe43fbe0)

**Comment by NEVARLeVrai** [comment]
U realsed 0.6.6 I didn't saw it ?

**Comment by fast4x** [comment]
The release is done every Friday

**Comment by NEVARLeVrai** [comment]
I don't see it in realse

**Comment by NEVARLeVrai** [comment]
> The release is done every Friday 

Today so ?

**Comment by fast4x** [comment]
Yes, i'm preparing release 0.6.6
