### ISSUE TITLE
Random playing from albums

### ISSUE THREAD

**Issue by enomao44** [fast4x/RiMusic#3706]
### Description

a random playing of the albums you have in your account. a shuffle playlist of all the albums mixed in your account. right now is just to have one random album to play.

### Suggested Solution

to have a playlist mixed of all your albums

**Comment by fast4x** [comment]
![Screenshot_2024-09-18-13-36-42-275_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/9ab0638e-1135-4030-972b-e1880d90d374)

use dice in albums

**Comment by enomao44** [comment]
but this goes to only one album, what i mean is if you have 500 albums that makes a random shuffle playlists of all tracks of the albums

**Comment by fast4x** [comment]
ah ok

**Comment by fast4x** [comment]
Implemented, available from version 0.6.55
