### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by viik420** [fast4x/RiMusic#371]
### Steps to reproduce the bug

App crashes after I pause the song or I go back to home screen when nothing is playing.

### Expected behavior

It should just stay in the state like I left.

### Actual behavior

App crashes when trying to open it

### RiMusic version

0.6.16.1

### Android version

13

**Comment by fast4x** [comment]
Ok, thanks i'll check it

**Comment by eqoffical** [comment]
same thing
https://github.com/fast4x/RiMusic/assets/125155438/99f77e39-052d-41a6-a9ae-1085015fe256

**Comment by fast4x** [comment]
Activate invincible mode (set without restriction) in settings > other

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/wiki/FAQs#-why-does-it-close-after-some-time-i-have-paused

**Comment by faustaahmad** [comment]
In my end
Disable battery optimization does fix the issue, but...
When I tried to click the song, it crashed

RiMusic ~> Play unplayable song (Trifonic - Lies) ~> Press Home
RiMusic again ~> Not crash if disabled battery optimization
Press any song ~> Crashed

The player got minimized (or perhaps crashed) when I press RiMusic after Home ~> RiMusic
0.6.16.1 & 0.6.17

Is this a different issue perhaps?
Also Trifonic - Lies unplayable even in 0.6.17 unless manually changed sound quality to Low

**Comment by fast4x** [comment]
Try to put the quality in automatic

**Comment by faustaahmad** [comment]
Automatic does work, but **need restart**
I suggest to add confirmation window if user choose automatic
OR make it seamless 😎
IF possible, REMOVE Automatic choice in favor of **"Prefer High/Medium/Low Quality"** & add some feature description like Minimum Listening time

Prefer High (Auto High > Medium > Low > Unknown)
Prefer Medium (Auto Medium > Low > High > Unknown)
Prefer Low (Auto Low > Medium > High > Unknown)
\*Unknown if there's no High Medium Low, then auto choose available audio stream

**Comment by viik420** [comment]
> Activate invincible mode (set without restriction) in settings > other

Already enabled, doesn't make any difference. It didn't get killed by battery optimization, it crashed

**Comment by fast4x** [comment]
Set automatic mode on audio quality format and try again 

Report feedback please
