### ISSUE TITLE
Incomplete screen in current play Music V0.6.52

### ISSUE THREAD

**Issue by zZ30MaxZz** [fast4x/RiMusic#3712]
### Steps to reproduce the bug

1. Go to play any Music
2. Enable screen rotation
3. Click current Music play
4. Screen incomplete, buttons 

![Screenshot_2024-09-18-18-36-55-393_it fast4x rimusic-edit](https://github.com/user-attachments/assets/9efef391-db44-4d55-8416-d0235be6cead)

### Expected behavior

Expected complete screen in horizontal screen

### Actual behavior

I can't see complete buttons in horizontal screen as smartphone, smart TV and PC apk
![Screenshot_2024-09-18-18-36-55-393_it fast4x rimusic-edit](https://github.com/user-attachments/assets/9521f10f-364d-4dee-8a58-c4bbc5710ee1)

![17267032826381808163864934083164](https://github.com/user-attachments/assets/3f72f8c5-918a-4365-b392-b9a4403a7591)

### RiMusic version

0.6.52

### Android version

Android 13

**Comment by aneesh1122** [comment]
Use modern player in smart tv and PC

**Comment by zZ30MaxZz** [comment]
The problem is also present on mobile devices

![Screenshot_2024-09-18-18-36-55-393_it fast4x rimusic-edit](https://github.com/user-attachments/assets/d543067d-3903-4fa8-8a19-11476f4a3414)


> Use modern player in smart tv and PC
