### ISSUE TITLE
easier way to album

### ISSUE THREAD

**Issue by enomao44** [fast4x/RiMusic#3718]
### Description

when you search a song and then list of songs appear you cannot go to the album of this song from the same list, tapping the song there is no option

### Suggested Solution

can go from the list directly to the album, would be much faster and useful

**Comment by twistios** [comment]
![Screenshot_20240919_232713](https://github.com/user-attachments/assets/4e7d3c1f-212e-4a45-a3e8-ebab27f37f6f)
You can hold the song then a menu appears with the option "Go to album".

**Comment by enomao44** [comment]
on a search results?

**Comment by twistios** [comment]
https://github.com/user-attachments/assets/930fa4b0-5ff4-489a-bbb8-ae3d0f818c5a

See the video what to do.

**Comment by enomao44** [comment]
aaa okey i might be on another previous version. cool

**Comment by fast4x** [comment]
Implemented, available from version 0.6.55
