### ISSUE TITLE
Incorrect duration in Discord RPC

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#3719]
### Steps to reproduce the bug

I'm sorry, but I dont know how to reproduce it
I have no songs with 08:20 duration
Played song with 06:40 duration before playing [this song](https://music.youtube.com/watch?v=pzwkfKqBhhM) (05:30)

I dont think that song caused this problem

### Expected behavior

Display correct duration in Discord RPC

### Actual behavior

Incorrect duration
Sometimes incorrect current duration (xx:xx/duration) after finished a song due to delay
Change/Replaying song will reset start duration (with delay obviously)

### Screenshots/Screen recordings

![](https://github.com/user-attachments/assets/09e017a6-c76b-42c3-ba2b-3df99281eb03)

### RiMusic version

0.6.52

### Android version

Android 11

**Comment by fast4x** [comment]
Improved, available from version 0.6.55
