### ISSUE TITLE
Error de búsqueda 

### ISSUE THREAD

**Issue by Pato63746899** [fast4x/RiMusic#3726]
### Steps to reproduce the bug

Lo que pasó fue que no me deja buscar yo busco y se queda buscando la canción para siempre 

### Expected behavior

Que busque la canción que quiero

### Actual behavior

No la busca si no que se queda cargando para siempre 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/79ad3dfa-0ea8-4f5d-8570-c1399405fb65

Eso es lo que pasa y está así 

### RiMusic version

0.6.52

### Android version

Android 12

**Comment by fast4x** [comment]
Don't use vpn
