### ISSUE TITLE
Metadata Not loding

### ISSUE THREAD

**Issue by Lio-gif** [fast4x/RiMusic#3734]
### Steps to reproduce the bug

1. Take a mp3 File and edit the metadata 
2. (idk If important do that for 2 or 3 files) also Same on metadata on evry file 
3. Add the Songs to a Playlist

### Expected behavior

Metadata should Show for all 3 songs

### Actual behavior

It Shows the metadata for only one of the 3 songs

### Screenshots/Screen recordings

![IMG_20240920_210758](https://github.com/user-attachments/assets/37d29aa0-9a8b-4497-833d-356abbf43d4d)
![IMG_20240920_210742](https://github.com/user-attachments/assets/8e4b38a9-622f-45f3-998d-beb620389b68)

### RiMusic version

0.6.53

### Android version

14

**Comment by fast4x** [comment]
Go in home songs, hold the song, click on Update, fixed?

**Comment by Lio-gif** [comment]
> Go in home songs, hold the song, click on Update, fixed?

Yes thx
