### ISSUE TITLE
Última versión mala

### ISSUE THREAD

**Issue by Blanki7** [fast4x/RiMusic#3735]
### Steps to reproduce the bug

voy al buscador, busco la canción, me sale q cambie de categoría o clave y no me sale ninguna 

### Expected behavior

ya descargue su versión más reciente ehh igual sale lo mismo 😔

### Actual behavior

nose

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/c975c4b6-9948-4ff0-bb0a-616953411030

### Logs

nose

### RiMusic version

v0.6.53

### Android version

Android 14

### Additional information

nada ua

**Comment by fast4x** [comment]
After search change section
