### ISSUE TITLE
[Feature]: use gtk4 maybe qt6 for linux version

### ISSUE THREAD

**Issue by olumolu** [fast4x/RiMusic#3736]
### Description

Having gtk4 libadwaita makes system integrated like a native app.
And with qt it is also good though but with qt it does not look good on gnome but in kde gtk apps are good looking.
Qt need to work on make it more native.
But make sure you use gtk4

### Suggested Solution

Use gtk4 this support all major language.

**Comment by fast4x** [comment]
There isn't a linux version, actual development it's Android native with planned desktop app for Windows and Linux.
