### ISSUE TITLE
RiMusic  NECESITA ALMACENAMIENTO EXTERNO

### ISSUE THREAD

**Issue by Balloom** [fast4x/RiMusic#3738]
### Description

No encuentro alguna opción donde pueda guardar los datos de la app en el almacenamiento externo, es decir, que pueda descargar canciones y que su peso no sea almacenado en el almacenamiento interno si no en el externo 

### Suggested Solution

crear una opción donde permita esa función, creo que para personas que poseemos poco espacio de almacenamiento sería una gran herramienta.

### Additional Context

No quiero que pueda descargar las canciones directamente en el almacenamiento externo, si no que el peso de las descargas sea allí, no se si me explico bien

**Comment by fast4x** [comment]
Not possible, not exists.
