### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#374]
### Description

I liked that you made it in between but that's too offset

### Suggested Solution

![Screenshot_20240109-233212](https://github.com/fast4x/RiMusic/assets/120176369/2084f0f5-c0ea-4141-b241-3dcd1b026b81)
Please make it upto white row

### Additional Context

Can you add search box from #368

**Comment by fast4x** [comment]
#368 in progress...

**Comment by fast4x** [comment]
Added background on search bar and other search on songs list
Available from version 0.6.17
