### ISSUE TITLE
Songs change to the next song after 30 seconds 

### ISSUE THREAD

**Issue by Kaynem706** [fast4x/RiMusic#3741]
### Steps to reproduce the bug

Play any song in an album and the song will change to the next song after 30 seconds

### Expected behavior

The songs should play completely 

### Actual behavior

Songs change to another song after the seconds ,the song doesn't play completely 

### RiMusic version

0.6.53

### Android version

Android 14

### Additiona response 

Please fix it as soon as you can because right now i cant really listen to music

**Comment by fast4x** [comment]
tap and hold play button in player and click on hourglass, disable medley mode

**Comment by Kaynem706** [comment]
Thank you it worked
