### ISSUE TITLE
Statistics improvement

### ISSUE THREAD

**Issue by Anonymous-forreal** [fast4x/RiMusic#3744]
### Description

I believe that statistics option was better previously when it was more detailed like how much time we've listened and what songs ,top artists etc . It would be better if it was changed to as it was before the update.

### Suggested Solution

The solution would be to change the statistics option to how it was before the update.

**Comment by fast4x** [comment]
You’re right I forgot to reset the listening time.

**Comment by fast4x** [comment]
> In the previous version they didn't tell you how much you had heard, now it's better because it's numbered

it was

**Comment by fast4x** [comment]
> You’re right I forgot to add the listening time.

**Comment by fast4x** [comment]
Fixed, added missed listening time, availablr from version 0.6.54
