### ISSUE TITLE
App refuses to open, crashes on launch

### ISSUE THREAD

**Issue by Juggalage** [fast4x/RiMusic#3746]
### Steps to reproduce the bug

1. Open app

### Expected behavior

App should open and work as normal

### Actual behavior

App immediately crashes

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/5918bf72-a7eb-4028-b8da-83ff91cf1381

### Logs

Unable to retrieve crash log

### RiMusic version

0.6.53

### Android version

Android 14

### Additional information

App worked fine yesterday, updated to most recent version today, and now app won't work.

**Comment by Juggalage** [comment]
Fixed the issue by uninstalling and re-installing. Unfortunately, this sent me back to a really old backup.

![chopcrycover.jpg](https://github.com/user-attachments/assets/348ed69f-fcf1-4634-8f9f-092a1d0ac4bc)

Guess that's my fault for not saving backups more often.

**Comment by fast4x** [comment]
Next time click on App Info After crash and paste here this log.
