### ISSUE TITLE
My app have a problem with to reproduce

### ISSUE THREAD

**Issue by Fanz3rr** [fast4x/RiMusic#3749]
### Steps to reproduce the bug

1. I enter to rimusic
2. Shearch the music
3. I listen the music
4. The music aren't stop and i can't listen other music 

### Expected behavior

Example: i should of listened all the music and the next musics 

### Actual behavior

Actual behavior: the music are stopped in a time and when try to listen other music i can't and then works again as if nothing had happened. 

### Screenshots/Screen recordings

![Screenshot_20240921_172627_it fast4x rimusic](https://github.com/user-attachments/assets/25782dd3-20c9-4090-8c4f-7668706c9bfa)

### RiMusic version

0.6.53

### Android version

Android 10

### Additional information

In times the problem does not appear
But in time i can't to finish to listen the music

**Comment by fast4x** [comment]
Not use vpn

**Comment by Fanz3rr** [comment]
No i not use vpn
Mi phone is a huawei but in moments stop the music
