### ISSUE TITLE
Duplicate songs in albums 

### ISSUE THREAD

**Issue by Kaynem706** [fast4x/RiMusic#3750]
### Steps to reproduce the bug

Play any song and then go to the album and tap play next(for the whole album) and only the first song of the album will play and it will create a duplicate of the first song

### Expected behavior

The whole album should play and no duplicate should appear in the album 

### Actual behavior

When you tap play next on the album only the first song plays and the first song somehow creates a duplicate 

### Screenshots/Screen recordings

![Screenshot_20240922_075420](https://github.com/user-attachments/assets/0a2fe2c2-5c06-4b0d-bd67-fd1c5a348f99)

### RiMusic version

0.6.53

### Android version

Android 14

**Comment by fast4x** [comment]
Send video please

**Comment by LiftedStarfish** [comment]
The same thing happened to an entire album for me.  I have no clue what causes it, and I can't figure out how to reverse it.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.60
