### ISSUE TITLE
rpc broken (wrong song duration, song showing like playing when paused

### ISSUE THREAD

**Issue by ChickensioDev** [fast4x/RiMusic#3755]
### Steps to reproduce the bug

connect discord and rimusic
play any song
pause it and see

### Expected behavior

when song is played, it should show correct total duration
and when paused, the player should pause in rpc as well or not show anything

### Actual behavior

instead it shows 8:20 for all songs (the song in screenshot actual duration is 2:42. the timeline is also at above 3 minutes cause it keeps moving forward even when paused)
timeline continues moving forward when paused

### Screenshots/Screen recordings

![image](https://github.com/user-attachments/assets/c57663f6-6da4-453d-9987-88e17670dc35)

### RiMusic version

latest (0.6.53)

### Android version

android 13

**Comment by fast4x** [comment]
Yes you are right, Discord will be improved
