### ISSUE TITLE
Ayuda

### ISSUE THREAD

**Issue by Alexkromo08** [fast4x/RiMusic#3761]
### Description

Me pueden apoyar a decirme cómo cambio dónde guardar las canciones descargadas? Ya que por default las guarda en mi memoria del teléfono y quiero guardarlas en mi micro USB gracias!!

### Suggested Solution

Solo saber cómo cambiar el almacenamiento

**Comment by fast4x** [comment]
Hello isn't possible, sorry

**Comment by Alexkromo08** [comment]
Aaa ok tks
