### ISSUE TITLE
The app crashed

### ISSUE THREAD

**Issue by Ikergian23** [fast4x/RiMusic#3764]
### Steps to reproduce the bug

1 abrir la aplicación 

### Expected behavior

La aplicación debería ejecutarse con normalizados y no crashear

### Actual behavior

La app crasheó en lugar de ejecutarse y abrirse normalmente 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/4df70d50-46ec-4e4f-8039-e1df1537b334

### RiMusic version

0.6.52

### Android version

Android 13

### Additional information

Aveces al crashear al app me aparece un cartel del sistema que dice "Rimusic continúa fallando"

**Comment by fast4x** [comment]
Try latest version please

**Comment by Gaarco** [comment]
![IMG_20240925_212223.jpg](https://github.com/user-attachments/assets/0d3c31bc-e92c-4e56-a24f-ca74acb08e49)

This is the log, not sure if it's of help since it's obfuscated

**Comment by Gaarco** [comment]
I'm still experiencing the problem on app version 0.6.54

**Comment by fast4x** [comment]
Hold app icon and click on songs, crash?

**Comment by Gaarco** [comment]
No, it crashes in the following scenarios:

- Open app normally 
- Hold app icon and click on playlist
- Successfully open the app and click on playlist from the bottom menu

**Comment by fast4x** [comment]
So, in the playlists... interesting, I'll check it.

**Comment by fast4x** [comment]
You have Piped enabled?

**Comment by Gaarco** [comment]
Yes, but disabling that option doesn't change anything for me.
I also tried toggling all the options related to the playlists one at a time but nothing changed.

**Comment by fast4x** [comment]
I'm building a custom version with debug message, soon.

**Comment by fast4x** [comment]
Try this, open app, enable debug in miscellaneous settings, restart app, go to playlists, after crash open app and go miscellaneous settings, copy crash log and send me it.

**Comment by Gaarco** [comment]
It's the same I sent in a previous message:

```
2024-09-29T15:17:57.810:	java.lang.NullPointerException: c.getString(index) must not be null
	 f4.e.g(SourceFile:17) 
	 C7.n.b(SourceFile:1864) 
	 e4.k.r(SourceFile:214) 
	 e4.k.g(SourceFile:13) 
	 f4.b.a(SourceFile:9) 
	 c4.z.p(SourceFile:9) 
	 e4.l.r(SourceFile:137) 
	 B8.a.k(SourceFile:9) 
	 V8.O.run(SourceFile:113) 
	 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	 java.lang.Thread.run(Thread.java:1012) 

```

**Comment by fast4x** [comment]
But this isn't a RiMusic internal crash log

**Comment by fast4x** [comment]
> Yes, that's where I copied from

in what language you use RiMusic?

**Comment by Gaarco** [comment]
Italian

**Comment by fast4x** [comment]
In serata preparo una versione custom da provare, ho fatto alcune ottimizzazioni. Ti avviso appena pronta.

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion
Try this

**Comment by Gaarco** [comment]
I have the exact same error:

```

2024-09-29T22:04:58.550:	java.lang.NullPointerException: c.getString(index) must not be null
	 f4.e.g(SourceFile:17) 
	 C7.n.b(SourceFile:1917) 
	 e4.k.r(SourceFile:214) 
	 e4.k.g(SourceFile:13) 
	 f4.b.a(SourceFile:9) 
	 c4.z.p(SourceFile:9) 
	 e4.l.r(SourceFile:137) 
	 B8.a.i(SourceFile:9) 
	 V8.O.run(SourceFile:113) 
	 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	 java.lang.Thread.run(Thread.java:1012) 

```

**Comment by fast4x** [comment]
ne faccio un'altra subito attendi

**Comment by fast4x** [comment]
riprova a scaricare la nuova custom

**Comment by Gaarco** [comment]
Ho provato la custom, ma il risultato è lo stesso.
Ho anche provato a clonare il repo, e lanciare l'app da android studio sul mio telefono, ma con questa modalità non da nessun problema.
Ho anche resettato tutte le impostazioni dell'app, ma niente.

**Comment by fast4x** [comment]
Credo che dipenda da qualcosa che da fastidio sul tuo device.

**Comment by Gaarco** [comment]
Cancellando tutti i dati dell'app si è risolto il problema, a questo punto non penso sia dato dal device

**Comment by fast4x** [comment]
Potevano esserci dei dati monchi nel db che causavano il problema, sarebbe interessante capire quali.
