### ISSUE TITLE
Reproducción en modo offline

### ISSUE THREAD

**Issue by z4ifer** [fast4x/RiMusic#3766]
### Steps to reproduce the bug

No reproduce en modo offline 

### Expected behavior

Reproducción en modo offline 

### Actual behavior

Se pausa la reproducción 

### RiMusic version

Ultima versión

### Android version

Android 13

### Additional information

Estoy en el campo y a veces la señal de mi operador no es buena.

La consulta es si ya reproduce en modo offline, que me guíen por donde lo puedo hacer.

Si no lo hace, por favor incluirlo en las versiones siguientes.

**Comment by fast4x** [comment]
Offline work for cached or downloaded songs...
