### ISSUE TITLE
When we select multiple songs fom Playlist or queue there isn't any option 

### ISSUE THREAD

**Issue by Omkar1GH** [fast4x/RiMusic#3767]
### Steps to reproduce the bug

1. Go to any Playlists or queue
2. Then click on select or deselect option 
3. When you select multiple songs there isn't any next option what to do with those selected songs like adding to another Playlists etc...

### Expected behavior

When u select multiple songs user should get the options llike add to Playlist, remove from Playlist or add to queue etc...

### Actual behavior

When I select multiple songs I should get option of add to  Playlist ,add to queue and other options 

### Screenshots/Screen recordings

![Screenshot_20240924-181142](https://github.com/user-attachments/assets/cd87ac52-3315-46d5-a525-3770a28556e9)

### RiMusic version

V0.6.53

### Android version

Android 12

### Additional information

If I select multiple songs from I should have a option next what to do

**Comment by fast4x** [comment]
after select click on three dots and click on action

**Comment by Omkar1GH** [comment]
![Screenshot_20240925-214228](https://github.com/user-attachments/assets/2b2ee413-f1cf-4532-b02d-cede2484504d)


There isn't any actions button after selecting multiple songs

**Comment by fast4x** [comment]
add to playlist, export, are actions... what you mean?

**Comment by Omkar1GH** [comment]
When I click on add to Playlist option not only selected songs also the other songs which are in gets add
