### ISSUE TITLE
Error en la lista de reproducción 

### ISSUE THREAD

**Issue by ifz5** [fast4x/RiMusic#3768]
### Steps to reproduce the bug

Voy a Artistas.
Voy a canciones.
Escojo la primera canción para que vaya reproduciendo la lista de canciones del artista.

### Expected behavior

Debería cargar todas las canciones del artista que he elegido para reproducirlas en mi lista de reproducción.

### Actual behavior

Sólo carga 11 canciones en la lista de reproducción, y cuando acaba vuelve a la primera.

### Screenshots/Screen recordings

![IMG_20240924_172720](https://github.com/user-attachments/assets/a3b29c97-5a20-4bac-97ea-94252423561e)

### RiMusic version

0.6.53

### Android version

Android 13

**Comment by fast4x** [comment]
Explain better please i don't understnd sorry

**Comment by ifz5** [comment]
En cuanto escojo las canciones de un artista y le doy al play en la primera canción, se supone que deberían estar todas las canciones en cola que tiene ese artista y debería reproducirlas. En cambio sólo aparecen 11 y cuando acaban vuelve a la primera canción.
Gracias

**Comment by fast4x** [comment]
You find 11 because where you launched one there are 11. The fact that it resumes is due to the active repetition, disables the loop in the queue.
