### ISSUE TITLE
App doesn't work with WiFi 

### ISSUE THREAD

**Issue by edumdq82** [fast4x/RiMusic#3772]
### Steps to reproduce the bug

Open the app (while you're connected to a WiFi network)
Try to navigate by different screens, artists, search, play music, etc.

### Expected behavior

Normally it should work: open recommendations in the main screen, open artists, albums, receive results from a search or play music.

### Actual behavior

Nothing is shown in any screen nor any music is played.

### RiMusic version

0.6.53

### Android version

Android 14

### Additional information

If you use a VPN connection or use a mobile data connection it works normally.

By suggestions in Telegram I tried to open YouTube Music and it works always. Maybe the problem started when I installed an app to watch YouTube without adds but I'm not sure.

It's even more strange that in my wife's mobile the problem is the same but she didn't do anything in her phone.

Mobiles restarted, turn off and turn on. App reinstalled, app downgrade. Router restarted. Nothing seems to work.

**Comment by fast4x** [comment]
Sorry, not depend by app.

**Comment by edumdq82** [comment]
I add information, I install the app on my work mobile phone and it works normally. Unbelievable!

I also made a full reset of my personal mobile phone and the app doesn't work...

It's a real pity! I have to use a VPN network when I want to use the app at home

**Comment by knighthat** [comment]
Sounds to me like a firewall problem. Try these:

1. Try changing your phone's local IP address. 
2. Remove any apps related to blocking internet traffic (you mentioned factory reset, so I don't think this is necessary anymore)
3. Factory reset your modem

**Comment by aneesh1122** [comment]
> I add information, I install the app on my work mobile phone and it works normally. Unbelievable

Using the same WIFI?

**Comment by edumdq82** [comment]
> Sounds to me like a firewall problem. Try these:
> 
>     1. Try changing your phone's local IP address.
> 
>     2. Remove any apps related to blocking internet traffic (you mentioned factory reset, so I don't think this is necessary anymore)
> 
>     3. Factory reset your modem

I have already performed a Factory Reset in my router.

I have never had any app blocking my internet traffic.... At least that I know of.

Anyway, I had already factory reset my mobile phone as well.

The IP, I don't know how to change it, but it's possible that a failure comes because my internet operator uses CGNAT technology...

Although it shouldn't be a problem as I've been using the app for over a month without any problems.

I think that, for some reason, when I installed an app to watch YouTube without ads something changed in my mobile or in my router (or in both) and that's why the app stopped working properly. On the other hand, I don't understand why the same thing happened on my wife's mobile, but on my work mobile I can use RiMusic without any problems using the same WIFI network.

It's a real mystery...

**Comment by edumdq82** [comment]
> > I add information, I install the app on my work mobile phone and it works normally. Unbelievable
> 
> Using the same WIFI?

Yes, I don't know what is happened...

The only difference I see is that my mobile and my wife's mobile are Oneplus and my work mobile is an Oppo...

Same WIFI different results... Same problem in my wife's mobile and my mobile without do anything in her phone...

It is really strange...

**Comment by fast4x** [comment]
Sorry but not depend by app.

**Comment by knighthat** [comment]
As @fast4x said, this is not our fault. But I can help you narrow down the faulty device:

1. Will RiMusic work with other WiFi networks
2. (If you can) Replace your modem with another one.

If any of the solutions fixes the issue. Then you know your modem is the culprit.

**Comment by knighthat** [comment]
> Sorry but not depend by app.

Can you add "not our fault" tag?. We can close down some of these with that tag. Thank you!

**Comment by edumdq82** [comment]
> > Sorry but not depend by app.
> 
> Can you add "not our fault" tag?. We can close down some of these with that tag. Thank you!

Could you please tell me how I can add a tag, or do I just close the topic as done?

**Comment by fast4x** [comment]
I do

**Comment by knighthat** [comment]
> Could you please tell me how I can add a tag, or do I just close the topic as done?

I was talking to repo's owner. Sorry for the confusion
