### ISSUE TITLE
Cant play music sometimes

### ISSUE THREAD

**Issue by KingK2-gif** [fast4x/RiMusic#3773]
### Steps to reproduce the bug

Listen to some songs then it just doesn't play the next song.

### Expected behavior

It should play the song normally

### Actual behavior

It doesn't play the next song sometimes it says couldn't play song or something. Then I press the start and pause button constantly so that it can strat working again and sometimes that doesn't even work so I resort to having to force stop the app then open it back up just to listen to a couple of songs normally before it does it again.

### Screenshots/Screen recordings

![Screenshot_20240924_204704](https://github.com/user-attachments/assets/4aed0df2-2919-4652-be28-3dca16eaa031)

### Logs

2024-09-08T10:29:14.746:	java.lang.IllegalStateException
	 G2.b.g(SourceFile:6) 
	 K2.A.h(SourceFile:6) 
	 K2.A.g(SourceFile:34) 
	 A0.d.x(SourceFile:94) 
	 t7.y.h(SourceFile:120) 
	 e0.b.h(SourceFile:52) 
	 p7.B.h(SourceFile:111) 
	 e0.b.h(SourceFile:52) 
	 W6.D.g(SourceFile:90) 
	 e0.b.e(SourceFile:44) 
	 e0.b.g(SourceFile:9) 
	 T.X1.a(SourceFile:563) 
	 p7.q0.h(SourceFile:86) 
	 e0.b.h(SourceFile:52) 
	 W.e.a(SourceFile:233) 
	 h6.F.h(SourceFile:319) 
	 h6.F.i(SourceFile:400) 
	 t7.G.n(SourceFile:205) 
	 e0.b.f(SourceFile:44) 
	 e0.b.n(SourceFile:9) 
	 B.o.h(SourceFile:423) 
	 e0.b.h(SourceFile:52) 
	 W.e.a(SourceFile:233) 
	 E.L.b(SourceFile:249) 
	 C.l.e(SourceFile:104) 
	 E.O.h(SourceFile:369) 
	 e0.b.h(SourceFile:52) 
	 W.e.a(SourceFile:233) 
	 g0.g.c(SourceFile:149) 
	 E.o0.c(SourceFile:84) 
	 E.L.d(SourceFile:105) 
	 B.w.h(SourceFile:779) 
	 e0.b.h(SourceFile:52) 
	 B.w.h(SourceFile:392) 
	 e0.b.h(SourceFile:52) 
	 W.e.N(SourceFile:15) 
	 W.r.p(SourceFile:203) 
	 W.v.k(SourceFile:34) 
	 W.t0.a(SourceFile:45) 
	 W.p.a(SourceFile:5) 
	 W.p.a(SourceFile:5) 
	 W.p.a(SourceFile:5) 
	 W.v.l(SourceFile:9) 
	 G0.G.i(SourceFile:22) 
	 G0.G.h(SourceFile:121) 
	 G0.B.O(SourceFile:160) 
	 E.V.a(SourceFile:34) 
	 C.q.b(SourceFile:21) 
	 C.r.h(SourceFile:840) 
	 B.w.h(SourceFile:660) 
	 G0.D.g(SourceFile:74) 
	 I0.u.a(SourceFile:38) 
	 q0.U.i(SourceFile:1) 
	 I0.A.a(SourceFile:15) 
	 B.G.i(SourceFile:99) 
	 I0.A.a(SourceFile:15) 
	 B0.b.a(SourceFile:244) 
	 h0.r.f(SourceFile:56) 
	 h0.u.a(SourceFile:52) 
	 h0.v.d(SourceFile:140) 
	 I0.m0.a(SourceFile:3) 
	 I0.L.s0(SourceFile:133) 
	 I0.L.a(SourceFile:91) 
	 B.u.g(SourceFile:85) 
	 I0.u.a(SourceFile:38) 
	 B.G.i(SourceFile:99) 
	 I0.A.a(SourceFile:15) 
	 B.G.i(SourceFile:99) 
	 I0.A.a(SourceFile:15) 
	 B0.b.a(SourceFile:244) 
	 h0.r.f(SourceFile:56) 
	 h0.u.a(SourceFile:52) 
	 h0.v.d(SourceFile:140) 
	 I0.m0.a(SourceFile:3) 
	 I0.L.s0(SourceFile:133) 
	 I0.L.a(SourceFile:91) 
	 u.o.g(SourceFile:24) 
	 I0.u.a(SourceFile:38) 
	 u.H.i(SourceFile:246) 
	 I0.A.a(SourceFile:15) 
	 q0.n.i(SourceFile:1) 
	 I0.A.a(SourceFile:15) 
	 B.q0.g(SourceFile:30) 
	 G0.x.i(SourceFile:8) 
	 I0.A.a(SourceFile:15) 
	 B0.b.a(SourceFile:244) 
	 h0.r.f(SourceFile:56) 
	 h0.u.a(SourceFile:52) 
	 h0.v.d(SourceFile:140) 
	 I0.m0.a(SourceFile:3) 
	 I0.L.s0(SourceFile:133) 
	 I0.L.a(SourceFile:91) 
	 u.h.g(SourceFile:58) 
	 I0.u.a(SourceFile:38) 
	 B.G.i(SourceFile:99) 
	 I0.A.a(SourceFile:15) 
	 B0.b.a(SourceFile:244) 
	 h0.r.f(SourceFile:56) 
	 h0.u.a(SourceFile:52) 
	 h0.v.d(SourceFile:140) 
	 I0.m0.a(SourceFile:3) 
	 I0.L.s0(SourceFile:133) 
	 I0.L.a(SourceFile:91) 
	 B.d.g(SourceFile:86) 
	 B.e0.g(SourceFile:40) 
	 I0.u.a(SourceFile:38) 
	 B.G.i(SourceFile:99) 
	 I0.A.a(SourceFile:15) 
	 B0.b.a(SourceFile:244) 
	 h0.r.f(SourceFile:56) 
	 h0.u.a(SourceFile:52) 
	 h0.v.d(SourceFile:140) 
	 I0.m0.a(SourceFile:3) 
	 I0.L.s0(SourceFile:133) 
	 I0.L.a(SourceFile:91) 
	 B.u.g(SourceFile:256) 
	 I0.u.a(SourceFile:38) 
	 B.G.i(SourceFile:99) 
	 I0.A.a(SourceFile:15) 
	 B.Z.i(SourceFile:115) 
	 I0.A.a(SourceFile:15) 
	 B0.b.a(SourceFile:244) 
	 h0.r.f(SourceFile:56) 
	 h0.u.a(SourceFile:52) 
	 h0.v.d(SourceFile:140) 
	 I0.m0.a(SourceFile:3) 
	 I0.L.s0(SourceFile:133) 
	 I0.L.a(SourceFile:91) 
	 T.e1.h(SourceFile:900) 
	 G0.D.g(SourceFile:74) 
	 I0.u.a(SourceFile:38) 
	 B0.b.a(SourceFile:244) 
	 h0.r.f(SourceFile:114) 
	 h0.u.a(SourceFile:52) 
	 h0.v.d(SourceFile:140) 
	 I0.m0.a(SourceFile:3) 
	 I0.L.s0(SourceFile:133) 
	 I0.F.N(SourceFile:17) 
	 I0.F.O(SourceFile:18) 
	 I0.U.c(SourceFile:8) 
	 I0.U.m(SourceFile:138) 
	 I0.U.j(SourceFile:90) 
	 J0.x.x(SourceFile:36) 
	 J0.x.dispatchDraw(SourceFile:17) 
	 android.view.View.draw(View.java:25180) 
	 android.view.View.updateDisplayListIfDirty(View.java:24036) 
	 android.view.View.draw(View.java:24907) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4780) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538) 
	 android.view.View.updateDisplayListIfDirty(View.java:24022) 
	 android.view.View.draw(View.java:24907) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4780) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538) 
	 android.view.View.updateDisplayListIfDirty(View.java:24022) 
	 android.view.View.draw(View.java:24907) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4780) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538) 
	 android.view.View.updateDisplayListIfDirty(View.java:24022) 
	 android.view.View.draw(View.java:24907) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4780) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538) 
	 android.view.View.updateDisplayListIfDirty(View.java:24022) 
	 android.view.View.draw(View.java:24907) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4780) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538) 
	 android.view.View.updateDisplayListIfDirty(View.java:24022) 
	 android.view.View.draw(View.java:24907) 
	 android.view.ViewGroup.drawChild(ViewGroup.java:4780) 
	 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538) 
	 com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1185) 
	 android.view.View.draw(View.java:25180) 
	 com.android.internal.policy.DecorView.draw(DecorView.java:1167) 
	 android.view.View.updateDisplayListIfDirty(View.java:24036) 
	 android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:768) 
	 android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:774) 
	 android.view.ThreadedRenderer.draw(ThreadedRenderer.java:872) 
	 android.view.ViewRootImpl.draw(ViewRootImpl.java:6055) 
	 android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5710) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4799) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3291) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11329) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1153) 
	 android.view.Choreographer.doFrame(Choreographer.java:1079) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8918) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-09-14T14:19:35.478:	java.lang.IllegalStateException
	 G2.b.g(SourceFile:6) 
	 K2.A.h(SourceFile:6) 
	 K2.A.g(SourceFile:34) 
	 T7.c0.r(SourceFile:94) 
	 W3.a.j(SourceFile:249) 
	 b7.A.i(SourceFile:120) 
	 e0.b.i(SourceFile:52) 
	 b7.B.g(SourceFile:180) 
	 e0.b.e(SourceFile:44) 
	 e0.b.g(SourceFile:9) 
	 j.g(SourceFile:143) 
	 e0.b.e(SourceFile:44) 
	 e0.b.g(SourceFile:9) 
	 T.P0.i(SourceFile:394) 
	 e0.b.i(SourceFile:52) 
	 O.a0.i(SourceFile:170) 
	 e0.b.i(SourceFile:52) 
	 W.e.b(SourceFile:150) 
	 T.T1.a(SourceFile:113) 
	 T.T0.b(SourceFile:735) 
	 T.F0.i(SourceFile:219) 
	 e0.b.i(SourceFile:52) 
	 T.V0.i(SourceFile:260) 
	 e0.b.i(SourceFile:52) 
	 T.z0.a(SourceFile:52) 
	 B.k.i(SourceFile:1349) 
	 e0.b.i(SourceFile:52) 
	 W.e.b(SourceFile:150) 
	 J0.o0.a(SourceFile:395) 
	 D.i.i(SourceFile:536) 
	 e0.b.i(SourceFile:52) 
	 W.e.b(SourceFile:150) 
	 androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.a(SourceFile:619) 
	 J0.u1.i(SourceFile:250) 
	 e0.b.i(SourceFile:52) 
	 W.e.a(SourceFile:233) 
	 J0.u1.i(SourceFile:213) 
	 e0.b.i(SourceFile:52) 
	 W.e.N(SourceFile:15) 
	 W.r.p(SourceFile:236) 
	 W.r.K(SourceFile:32) 
	 W.v.w(SourceFile:24) 
	 W.t0.t(SourceFile:108) 
	 W.r0.b(SourceFile:508) 
	 J0.b0.doFrame(SourceFile:34) 
	 J0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1688) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1154) 
	 android.view.Choreographer.doFrame(Choreographer.java:1070) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:9063) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-09-17T11:17:01.727:	java.lang.IllegalStateException
	 G2.b.g(SourceFile:6) 
	 K2.A.h(SourceFile:6) 
	 K2.A.g(SourceFile:34) 
	 T7.c0.r(SourceFile:94) 
	 W3.a.j(SourceFile:249) 
	 b7.A.i(SourceFile:120) 
	 e0.b.i(SourceFile:52) 
	 b7.B.g(SourceFile:180) 
	 e0.b.e(SourceFile:44) 
	 e0.b.g(SourceFile:9) 
	 j.g(SourceFile:143) 
	 e0.b.e(SourceFile:44) 
	 e0.b.g(SourceFile:9) 
	 T.P0.i(SourceFile:394) 
	 e0.b.i(SourceFile:52) 
	 O.a0.i(SourceFile:170) 
	 e0.b.i(SourceFile:52) 
	 W.e.b(SourceFile:150) 
	 T.T1.a(SourceFile:113) 
	 T.T0.b(SourceFile:735) 
	 T.F0.i(SourceFile:219) 
	 e0.b.i(SourceFile:52) 
	 T.V0.i(SourceFile:260) 
	 e0.b.i(SourceFile:52) 
	 T.z0.a(SourceFile:52) 
	 B.k.i(SourceFile:1349) 
	 e0.b.i(SourceFile:52) 
	 W.e.b(SourceFile:150) 
	 J0.o0.a(SourceFile:395) 
	 D.i.i(SourceFile:536) 
	 e0.b.i(SourceFile:52) 
	 W.e.b(SourceFile:150) 
	 androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.a(SourceFile:619) 
	 J0.u1.i(SourceFile:250) 
	 e0.b.i(SourceFile:52) 
	 W.e.a(SourceFile:233) 
	 J0.u1.i(SourceFile:213) 
	 e0.b.i(SourceFile:52) 
	 W.e.N(SourceFile:15) 
	 W.r.p(SourceFile:236) 
	 W.r.K(SourceFile:32) 
	 W.v.w(SourceFile:24) 
	 W.t0.t(SourceFile:108) 
	 W.r0.b(SourceFile:508) 
	 J0.b0.doFrame(SourceFile:34) 
	 J0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1688) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1154) 
	 android.view.Choreographer.doFrame(Choreographer.java:1070) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:9063) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-09-19T09:16:23.409:	java.lang.IllegalStateException
	 G2.b.g(SourceFile:6) 
	 K2.A.h(SourceFile:6) 
	 K2.A.g(SourceFile:34) 
	 T7.c0.r(SourceFile:94) 
	 W3.a.j(SourceFile:249) 
	 I7.u0.i(SourceFile:30) 
	 W.r.M(SourceFile:438) 
	 W.r.T(SourceFile:137) 
	 W.r.p(SourceFile:244) 
	 W.r.K(SourceFile:32) 
	 W.v.w(SourceFile:24) 
	 W.t0.t(SourceFile:108) 
	 W.r0.b(SourceFile:508) 
	 J0.b0.doFrame(SourceFile:34) 
	 J0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1688) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1154) 
	 android.view.Choreographer.doFrame(Choreographer.java:1070) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:9063) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

### RiMusic version

V0.6.53

### Android version

Android 14

**Comment by knighthat** [comment]
Is it happening on v0.6.53 exclusively or on older versions as well? 

YouTube is cracking down third-party clients right now so you may experience hiccups between songs

**Comment by KingK2-gif** [comment]
> Is it happening on v0.6.53 exclusively or on older versions as well? 
> 
> YouTube is cracking down third-party clients right now so you may experience hiccups between songs

It's happening on the current version v0.6.53 it's also been do that with older versions before I update them but I guess the bug gets passed down to the newer one

**Comment by knighthat** [comment]
It could've been YouTube sending out phony responses. I experienced this right at the time where YouTube started blocking third-party clients (Invidious, Piped, etc.) 

One thing I did that reduced the time I encounter this problem was that I changed DNS to cloudflare. But on Reddit, people reported that removing DNS is the solution. So your millage may vary

**Comment by KingK2-gif** [comment]
How do you change the dns

**Comment by knighthat** [comment]
> How do you change the dns

It depends on the phone and the OS you're using. I suggest you go search on Google for more answers

**Comment by KingK2-gif** [comment]
Ok thanks
