### ISSUE TITLE
No reproduce la canción que seleccionó sino otra de las que tengo

### ISSUE THREAD

**Issue by MAXSP4** [fast4x/RiMusic#3775]
### Steps to reproduce the bug

Cuando presión sobre un de mis canciones, reproduce una canción pero esa está varias canciones más abajo de la que presiono o no es la del titulo

### Expected behavior

Espero que a lo que presione en la canción reproduzca la canción que quiero escuchar no es un problema grave pero si quiero dar click y que se reproduzca la canción que seleccionó 

### Actual behavior

Presiono en la canción pero reproduce canciones de más adelante no la que seleccionó 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/2a9c8c36-2950-40bf-873f-1523f03c402e

### RiMusic version

0.6.53

### Android version

Android 14

**Comment by fast4x** [comment]
maybe you have fixed shuffle enabled, in top icon with two arrows
