### ISSUE TITLE
Cant search words after `#`

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#3779]
### Steps to reproduce the bug

・Press search
・Search for anything but with added `#` at random position
or could search for `#####`
・Words after first/leftmost `#` will be excluded from the query

### Expected behavior

Can search `#` 

### Actual behavior

Words after `#` excluded from the query

### Screenshots/Screen recordings

`####` results in empty search query
![](https://github.com/user-attachments/assets/438aec11-96d2-4d0b-9eae-f09a5d5097ee)

### RiMusic version

0.6.52

### Android version

Android 11

### Additional information

If possible, please check other symbols too

**Comment by knighthat** [comment]
can you give me an example of a valid song that contains `#` in the title?

**Comment by faustaahmad** [comment]
> can you give me an example of a valid song that contains `#` in the title?

I dont know any song with `#` on its title
Often I need to use `#` as a keywords to search in youtube video
For example: _"CC#2 OST Arknights"_

**Comment by knighthat** [comment]
Thank you for the example. I'll review it once I have time

**Comment by knighthat** [comment]
@faustaahmad I have implemented a fix to this, the video you gave as the example is now searchable on the platform. Please wait for the next release
 
<img src="https://github.com/user-attachments/assets/8bcaa605-6807-4708-8c55-a9e9644848b7" alt="Screenshot_20240929_182659" width=240px />

**Comment by fast4x** [comment]
Fixed, available from version 0.6.55

**Comment by knighthat** [comment]
@fast4x this is even worst than my implementation, mine turns any string into url-safe string, yours outright deletes those characters, please reconsider this implementation #3826.

<p align="center">
<img src="https://github.com/user-attachments/assets/1af1be42-b813-4123-8d45-3a0eef82a847" width=240px />
</p>

**Comment by fast4x** [comment]
It's just implemented and available from version 0.6.55
