### ISSUE TITLE
Sobre las cola

### ISSUE THREAD

**Issue by Noeliiarp26** [fast4x/RiMusic#3781]
### Description

Como pongo una canción la siguiente. Me doy a poner en la cola y no se pone

### Suggested Solution

Ñ

### Alternatives

V

### Additional Context

G

**Comment by fast4x** [comment]
I don't understand

**Comment by Noeliiarp26** [comment]
Que la opción de poner a la cola no sirve. Cuando le doy la canción que seleccioné no se pone la siguiente
