### ISSUE TITLE
The music instead of changing to the next song goes back to the previous song  

### ISSUE THREAD

**Issue by Maycoljhustyn** [fast4x/RiMusic#3787]
### Steps to reproduce the bug

Whenever I go and change the song, the notification or when I turn off the phone, it goes back one song and repeats and does not change to the next song. 

### Expected behavior

The app does not change songs as a notification or with headphones 

### Actual behavior

Please fix it 

### RiMusic version

0.6.53

### Android version

Android 11

**Comment by Atmosujk** [comment]
i experienced the same problem

**Comment by twistios** [comment]
This problem is known and already reported many times and currently there is no fix for it (especially also as we don't really know why it happens and I didn't investigate the issue enough yet).

**Comment by twistios** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Maycoljhustyn** [comment]
still with the same problem
