### ISSUE TITLE
Crash when playing from Songs tab on restart

### ISSUE THREAD

**Issue by anxiouslelimo** [fast4x/RiMusic#379]
### Steps to reproduce the bug

Play a song from "Songs" tab.
Pause and close the app
Reopen the app
Play the song from "Songs' tab

### Expected behavior

Song should play

### Actual behavior

App crashes

### RiMusic version

0.6.16.1

### Android version

Android 11

**Comment by fast4x** [comment]
This is very interesting, thank you.

**Comment by fast4x** [comment]
Tried, I don’t have the error, I try to check on previous Android.

**Comment by fast4x** [comment]
Hi, https://github.com/fast4x/RiMusic/wiki/FAQs#-why-does-it-close-after-some-time-i-have-paused

**Comment by fast4x** [comment]
Solved?

**Comment by fast4x** [comment]
Perfect! Thanks you for feedback.
