### ISSUE TITLE
Shows hour listened instead of just Top 10

### ISSUE THREAD

**Issue by mariuslohoho** [fast4x/RiMusic#3792]
### Description

Just like vi music, make an option to show the hours listened, if theres already a setting for it, i cant find it bruh

### Suggested Solution

Add option to show hours listened on song cover just like vimusic

**Comment by aneesh1122** [comment]
I think hours listened should be replaced with number of plays

**Comment by mariuslohoho** [comment]
Tbh i would like to see both options

**Comment by aneesh1122** [comment]
> Tbh i would like to see both hours and plays

A 10 minute song will be counted as the most listened to in that case.

I'm interested to know how many times I've heard that song.

Maybe have a threshold that it will be counted as listened to if you hear it for at least 30 seconds.

**Comment by fast4x** [comment]
You can this info in statistics page

**Comment by mariuslohoho** [comment]
I dont see it is it because of im using the vi music interface or i have a setting off?
