### ISSUE TITLE
Latest version of app no longer displays as audio source

### ISSUE THREAD

**Issue by ndesai510** [fast4x/RiMusic#3793]
### Steps to reproduce the bug

Not sure what this is called, but in previous versions of the app, on my car stereo, when I select Bluetooth, I get a display of various apps that I can stream from.  VLC, Symfonium, RiMusic, etc.

On version 6.53, this no longer displays as a source to play from.  On my wife's phone, which is running version 6.41,i see RiMusic.

I am not referring to Android Auto.that works fine still, but the regular Bluetooth connection does not display RiMusic as a source anymore. 

### Expected behavior

See above

### Actual behavior

See above

### RiMusic version

0.6.53

### Android version

14

### Additional information

Used to work, no longer does.

**Comment by fast4x** [comment]
RiMusic use device Bluetooth to play it... RiMusic isn't a source... not have a server...
