### ISSUE TITLE
Lastest Version Fail to open on android 14.

### ISSUE THREAD

**Issue by cecrevier** [fast4x/RiMusic#3795]
### Steps to reproduce the bug

The lastest version 0.6.52 fail to open on android 14 on Samsung Galaxy S24 Ultra.
"RiMusic keeps stopping"

### Expected behavior

working

### Actual behavior

"RiMusic keeps stopping"

### RiMusic version

0.6.52

### Android version

ANdroid 14

**Comment by cecrevier** [comment]
Samething with the last version 0.6.53

**Comment by fast4x** [comment]
Much strange, remember what was last page before crash?

**Comment by fast4x** [comment]
Try latest version please

**Comment by cecrevier** [comment]
Hello,
Yes now it fixed. It work with the 0.6.54 version.

Thanks

**Comment by fast4x** [comment]
Perfect, thanks for feedback.
