### ISSUE TITLE
Falta de animación.

### ISSUE THREAD

**Issue by Jendrik-men** [fast4x/RiMusic#3798]
### Description

Los colores del reproductor en modo dinámica son muy muertos.
Desearía que hubiera una opción adicional en la que se pueda bajar la música al dispositivo.

### Suggested Solution

Deberían agregar más colores al modo dinámico del la interfaz y reproductor, ya que colores como el rojo y amarillo y otros parecidos no salen.
En cuanto a descargar las músicas al dispositivo sería una muy buena opción para quienes queremos asegurar la música que más escuchamos.

### Alternatives

Una de más alternativa, es que sí es posible agregar una colores dinámicos a la interfaz del app, y también que los colores del reproductor sean del color de la carátula de la música que se escucha en ese momento.

### Additional Context

En cuanto las descargas de música de la app al dispositivo móvil debieran integrar esa opción aparte de las que ya se encuentran.

**Comment by fast4x** [comment]
Download externally isn't planned. For colors can use custom colors in appearance settings.
