### ISSUE TITLE
[Feature]: Custom playlist images and dynamic colors playlist

### ISSUE THREAD

**Issue by jaki444** [fast4x/RiMusic#380]
### Description

EN:It would be nice to add the option that holding down on a playlist would allow you to change the cover image to one on the device or to any cover of a song in the playlist. It would be nice because if I choose a certain order in the playlist then to get a certain image I have to change the order. Another nice thing would be if the playlist square could have a thin or thicker border that changes color based on the song if there is the theme enabled to create more contrast. Of course by playlists I mean user-created playlists not the ones you search for.

ITA:Sarebbe bello aggiungere l'opsione che tenendo premuto su una playlist permetta di cambiare immagine di copertina con una presente nel dispositivo o con una quasiasi cover di una canzone presente nella playlist. Sarebbe bello perche se sceglo un determinato ordine nella playlist poi per avere una determinata immagine devo cambiare l'ordine. Una altra cosa carina sarebbe che il quadratino delle playlist potesse avere un bordo sottile o piu spesso che cambia colore in base alla canzone se c'è il tema attivato per creare piu contrasto. Ovviamente con playlist intendo le playlist create dagli utenti.

### Suggested Solution

EN:a solution would be that how much you holding down there is a customize playlist cover option and if pressed it opens up a little menu that makes you choose whether to put images from the device or one present in the playlist.

ITA:una soluzione potrebbe essere che quanto si tiene premuto c'è un'opzione di personalizzazione della copertina della playlist e se premuta apre un piccolo menu che fa scegliere se mettere immagini dal dispositivo o una presente nella playlist.

**Comment by fast4x** [comment]
Nice request! In part the ticket is duplicated compared to #135

**Comment by OrangeZXZ** [comment]
@fast4x i think this issue can be closed since we have custom images for albums

**Comment by fast4x** [comment]
Thanks for help...

**Comment by jaki444** [comment]
no, i wrote custom image for playlist. i didn't write custom image for albums
