### ISSUE TITLE
Fade songs

### ISSUE THREAD

**Issue by edumdq82** [fast4x/RiMusic#3802]
### Description

Add the possibility to change songs with a fade

### Suggested Solution

Add a "party mode" to made this fading change of songs (playing to be a DJ)

**Comment by fast4x** [comment]
Just present 
![Screenshot_2024-09-28-13-25-42-461_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/55c53eb5-8975-47eb-8685-b895e98eb305)
