### ISSUE TITLE
Ignorer les debut 

### ISSUE THREAD

**Issue by titi26** [fast4x/RiMusic#3808]
### Description

Bonjour, se serai bien d'avoir une option a activer pour ignorer les début de chanson sans musique , car j'ai activer ignorer le silence mais sa me met toujours les début ou ya rien 

### Suggested Solution

Faire une option pour ignorer les début de chanson ou ta pas de musique

**Comment by fast4x** [comment]
Fixed skip silence, available from version 0.6.56
