### ISSUE TITLE
"Like" button

### ISSUE THREAD

**Issue by Nighty360** [fast4x/RiMusic#3811]
### Steps to reproduce the bug

1.open rimusic 
2.click on settings 
3.click on appearance 
4.slide to the "like" button setting 
5.choose the "broken" setting 
6.see that it doesn't look good.

![Screenshots_2024-09-28-18-53-00](https://github.com/user-attachments/assets/eb8aeed4-61c3-444c-b33a-12cbb3b3ae22)

### Expected behavior

That should look well structured.

### Actual behavior

It looks bad.

### RiMusic version

0.6.54 by fast4x

### Android version

Android 12

**Comment by fast4x** [comment]
is broken...

**Comment by twistios** [comment]
![Screenshot_20240930_164140_Firefox](https://github.com/user-attachments/assets/607167b4-cc2d-477f-8d77-8343544ea2aa)

Is it supposed to look like this? The color is missing in the top left corner (part of the heart symbol I assume) but not where the heart is broken.
