### ISSUE TITLE
[Feature]: import playlists

### ISSUE THREAD

**Issue by RAAHIMSARFARAZ** [fast4x/RiMusic#3819]
### Description

Hi, I am a new user of ri music and using it for a little while, I like its features alot but I think that a feature that it's missing is its ability to import playlists from other major apps like Spotify, etc. Or I might have just missed it if it is in the app but so far from what I've seen it does not have an import option of playlist it does have an option to export which is convenient. But yeah! Other than that I like this app very much, keep up the good work! 

### Suggested Solution

And yeah I have any other issue than the import playlist so I hope that gets added in the next update or so, also i checked the "already exists" page and aside from me not understanding other languages I think this was not mentioned so I decided to fill this form out, other than that I hope this gets acknowledged. Thank you!

**Comment by aneesh1122** [comment]
> it's missing

It's not missing. It's just not planned.

use any way you want to transfer songs from spotify to youtube and then you can easily import playlists from youtube to RiMusic
