### ISSUE TITLE
Can't Play/Download Some Songs (add option auto selecting format available)

### ISSUE THREAD

**Issue by anxiouslelimo** [fast4x/RiMusic#382]
### Steps to reproduce the bug

1. Search Ranjish Hi Sahi
2. The third song in suggestions (https://music.youtube.com/watch?v=Ux7jQVb96Ts) duration 9:38
3. Play/Download

### Expected behavior

The song should play/download

### Actual behavior

If play - "Couldn't find a playable audio format"
If download - the icon endlessly spins

### Screenshots/Screen recordings

![WhatsApp Image 2024-01-11 at 09 39 05](https://github.com/fast4x/RiMusic/assets/115996455/81653ca9-3d78-4d3e-a55d-cd1a4ad5260d)
![WhatsApp Image 2024-01-11 at 09 39 17](https://github.com/fast4x/RiMusic/assets/115996455/c29055f5-0ff1-49e5-b924-e2b174d01d46)

### RiMusic version

0.6.16.1

### Android version

Android 11

**Comment by fast4x** [comment]
Hi, it's not a bug , depend on audio quality available for that song.
If you set audio quality to level Medium on settings, song play.

![Screenshot_2024-01-11-07-51-17-297_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/26983393-1587-4ce5-af88-01c376a40799)

**Comment by fast4x** [comment]
RIMusic work with highest audio quality by default, but any song are available only in lowest audio quality.

**Comment by fast4x** [comment]
I'll add an option for auto selecting max playable format available.

I change title of ticket, thanks for report.

**Comment by fast4x** [comment]
Added option in settings for automatic max audio quality available. Improved  also download with same option. 
Available from version 0.6.17
