### ISSUE TITLE
Artist Page Songs

### ISSUE THREAD

**Issue by AfafAsyraf** [fast4x/RiMusic#3821]
### Description

When clicking on artist page theres 5 songs in songs page when played it played only 5 songs. 

### Suggested Solution

Why not played all songs from the artist maybe shuffled it. 

### Alternatives

Yes I know I can click songs and it will show all artist song just wanna make it simple and click songs from artist page and played all the artist song
![Screenshot_20240930-004008](https://github.com/user-attachments/assets/ccf83110-9253-49be-942b-8de715d3a749)

**Comment by fast4x** [comment]
Is a preview, can play all from all artist songs list
![Screenshot_2024-09-29-20-07-57-243_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/d46ae667-2349-4c2b-b018-e93240e3ff8e)

**Comment by AfafAsyraf** [comment]
I know as stated but it can be faster when playing from the preview all
songs.
