### ISSUE TITLE
Plantage on android 6.0.1

### ISSUE THREAD

**Issue by Combi13** [fast4x/RiMusic#3822]
### Steps to reproduce the bug

Click on song

### Expected behavior

Plantage

### Actual behavior

???

### Logs

2024-09-29T18:54:50.319:	java.lang.IllegalStateException: The offset was read before being initialized. Did you access the offset in a phase before layout, like effects or composition?
	 V.w.g(SourceFile:26) 
	 C.U.b(SourceFile:972) 
	 J0.O.j(SourceFile:7) 
	 J0.A.g1(SourceFile:17) 
	 J0.A.a0(SourceFile:30) 
	 C6.m.a(SourceFile:1130) 
	 i0.s.f(SourceFile:56) 
	 i0.v.a(SourceFile:52) 
	 i0.w.d(SourceFile:136) 
	 J0.m0.a(SourceFile:3) 
	 J0.L.q0(SourceFile:86) 
	 J0.L.r0(SourceFile:117) 
	 J0.L.a0(SourceFile:6) 
	 H0.V.e(SourceFile:15) 
	 C.s.b(SourceFile:40) 
	 C.u.b(SourceFile:838) 
	 J0.O.j(SourceFile:7) 
	 B6.g.a(SourceFile:1133) 
	 i0.s.f(SourceFile:56) 
	 i0.v.a(SourceFile:52) 
	 i0.w.d(SourceFile:136) 
	 J0.m0.a(SourceFile:3) 
	 J0.L.n(SourceFile:103) 
	 J0.L.p0(SourceFile:123) 
	 J0.u.a0(SourceFile:44) 
	 H0.V.k(SourceFile:26) 
	 e6.d.b(SourceFile:714) 
	 J0.O.j(SourceFile:7) 
	 J0.A.g1(SourceFile:17) 
	 J0.A.a0(SourceFile:30) 
	 H0.V.f(SourceFile:68) 
	 C.U.b(SourceFile:1618) 
	 J0.O.j(SourceFile:7) 
	 J0.A.g1(SourceFile:17) 
	 J0.A.a0(SourceFile:30) 
	 C6.m.a(SourceFile:1130) 
	 i0.s.f(SourceFile:56) 
	 i0.v.a(SourceFile:52) 
	 i0.w.d(SourceFile:136) 
	 J0.m0.a(SourceFile:3) 
	 J0.L.q0(SourceFile:86) 
	 J0.L.r0(SourceFile:117) 
	 J0.L.a0(SourceFile:6) 
	 H0.V.e(SourceFile:15) 
	 C.s.b(SourceFile:40) 
	 C.t.b(SourceFile:22) 
	 J0.O.j(SourceFile:7) 
	 B6.g.a(SourceFile:1133) 
	 i0.s.f(SourceFile:56) 
	 i0.v.a(SourceFile:52) 
	 i0.w.d(SourceFile:136) 
	 J0.m0.a(SourceFile:3) 
	 J0.L.n(SourceFile:103) 
	 J0.L.p0(SourceFile:123) 
	 J0.u.a0(SourceFile:44) 
	 H0.V.f(SourceFile:68) 
	 C.U.b(SourceFile:1618) 
	 J0.O.j(SourceFile:7) 
	 J0.A.g1(SourceFile:17) 
	 J0.A.a0(SourceFile:30) 
	 C6.m.a(SourceFile:1130) 
	 i0.s.f(SourceFile:114) 
	 i0.v.a(SourceFile:52) 
	 i0.w.d(SourceFile:136) 
	 J0.m0.a(SourceFile:3) 
	 J0.L.q0(SourceFile:86) 
	 J0.F.R(SourceFile:35) 
	 J0.U.m(SourceFile:214) 
	 J0.U.j(SourceFile:90) 
	 K0.w.x(SourceFile:36) 
	 K0.w.dispatchDraw(SourceFile:17) 
	 android.view.View.draw(View.java:16498) 
	 android.view.View.updateDisplayListIfDirty(View.java:15491) 
	 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3609) 
	 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3589) 
	 android.view.View.updateDisplayListIfDirty(View.java:15451) 
	 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3609) 
	 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3589) 
	 android.view.View.updateDisplayListIfDirty(View.java:15451) 
	 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3609) 
	 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3589) 
	 android.view.View.updateDisplayListIfDirty(View.java:15451) 
	 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3609) 
	 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3589) 
	 android.view.View.updateDisplayListIfDirty(View.java:15451) 
	 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3609) 
	 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3589) 
	 android.view.View.updateDisplayListIfDirty(View.java:15451) 
	 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3609) 
	 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3589) 
	 android.view.View.updateDisplayListIfDirty(View.java:15451) 
	 android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281) 
	 android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287) 
	 android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322) 
	 android.view.ViewRootImpl.draw(ViewRootImpl.java:2630) 
	 android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2449) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2082) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1128) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6104) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:858) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:670) 
	 android.view.Choreographer.doFrame(Choreographer.java:606) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844) 
	 android.os.Handler.handleCallback(Handler.java:739) 
	 android.os.Handler.dispatchMessage(Handler.java:95) 
	 android.os.Looper.loop(Looper.java:148) 
	 android.app.ActivityThread.main(ActivityThread.java:5513) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

2024-09-29T18:55:01.720:	java.lang.IllegalStateException: The offset was read before being initialized. Did you access the offset in a phase before layout, like effects or composition?
	 V.w.g(SourceFile:26) 
	 C.U.b(SourceFile:972) 
	 J0.O.j(SourceFile:7) 
	 J0.A.g1(SourceFile:17) 
	 J0.A.a0(SourceFile:30) 
	 C6.m.a(SourceFile:1130) 
	 i0.s.f(SourceFile:56) 
	 i0.v.a(SourceFile:52) 
	 i0.w.d(SourceFile:136) 
	 J0.m0.a(SourceFile:3) 
	 J0.L.q0(SourceFile:86) 
	 J0.L.r0(SourceFile:117) 
	 J0.L.a0(SourceFile:6) 
	 H0.V.e(SourceFile:15) 
	 C.s.b(SourceFile:40) 
	 C.u.b(SourceFile:838) 
	 J0.O.j(SourceFile:7) 
	 B6.g.a(SourceFile:1133) 
	 i0.s.f(SourceFile:56) 
	 i0.v.a(SourceFile:52) 
	 i0.w.d(SourceFile:136) 
	 J0.m0.a(SourceFile:3) 
	 J0.L.n(SourceFile:103) 
	 J0.L.p0(SourceFile:123) 
	 J0.u.a0(SourceFile:44) 
	 C6.m.a(SourceFile:1154) 
	 i0.s.f(SourceFile:56) 
	 i0.v.a(SourceFile:52) 
	 i0.w.d(SourceFile:136) 
	 J0.m0.a(SourceFile:3) 
	 J0.L.q0(SourceFile:86) 
	 J0.L.r0(SourceFile:117) 
	 J0.L.a0(SourceFile:6) 
	 H0.V.l(SourceFile:18) 
	 D.u.l(SourceFile:238) 
	 D.s.b(SourceFile:131) 
	 H0.A.j(SourceFile:41) 
	 D.t.j(SourceFile:3) 
	 H0.C.j(SourceFile:14) 
	 B6.g.a(SourceFile:1133) 
	 i0.s.f(SourceFile:56) 
	 i0.v.a(SourceFile:52) 
	 i0.w.d(SourceFile:136) 
	 J0.m0.a(SourceFile:3) 
	 J0.L.n(SourceFile:103) 
	 J0.L.p0(SourceFile:123) 
	 J0.u.a0(SourceFile:44) 
	 H0.V.k(SourceFile:26) 
	 e6.d.b(SourceFile:714) 
	 J0.O.j(SourceFile:7) 
	 J0.A.g1(SourceFile:17) 
	 J0.A.a0(SourceFile:30) 
	 H0.V.f(SourceFile:68) 
	 C.m.b(SourceFile:155) 
	 J0.O.j(SourceFile:7) 
	 J0.A.g1(SourceFile:17) 
	 J0.A.a0(SourceFile:30) 
	 C6.m.a(SourceFile:1130) 
	 i0.s.f(SourceFile:114) 
	 i0.v.a(SourceFile:52) 
	 i0.w.d(SourceFile:136) 
	 J0.m0.a(SourceFile:3) 
	 J0.L.q0(SourceFile:86) 
	 J0.F.R(SourceFile:35) 
	 J0.U.m(SourceFile:214) 
	 J0.U.j(SourceFile:90) 
	 K0.w.x(SourceFile:36) 
	 A5.g.run(SourceFile:1123) 
	 android.os.Handler.handleCallback(Handler.java:739) 
	 android.os.Handler.dispatchMessage(Handler.java:95) 
	 android.os.Looper.loop(Looper.java:148) 
	 android.app.ActivityThread.main(ActivityThread.java:5513) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

### RiMusic version

0.6.54.1

### Android version

Android 6.0.1

**Comment by fast4x** [comment]
try custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Combi13** [comment]
Sorry but i have same issue with last version. 
0.6.55

**Comment by fast4x** [comment]
Not reproducible bug, sorry.
