### ISSUE TITLE
Fechando automático ao reproduzir alguma música

### ISSUE THREAD

**Issue by Ytalol43** [fast4x/RiMusic#3828]
### Steps to reproduce the bug

1. Abra o app
2. Aperte em qualquer música para reproduzi-la
3. App será encerrado abruptamente

### Expected behavior

O app deveria abrir o reprodutor e reproduzir a música normalmente

### Actual behavior

Envés disso, ele fecha abruptamente e pode não iniciar novamente, tendo que limpar o cache do app ou forçar a parada do mesmo

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/e404e42b-aabc-4336-a259-e8f2bc9565c5

### Logs

2024-09-30T10:30:50.173:	android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7fa66cf6
	 android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:292) 
	 android.content.res.Resources.getResourcePackageName(Resources.java:2347) 
	 it.fast4x.rimusic.service.PlayerMediaBrowserService.e(SourceFile:19) 
	 V7.o.r(SourceFile:343) 
	 B8.a.i(SourceFile:9) 
	 V8.O.run(SourceFile:113) 
	 K5.q.run(SourceFile:232) 
	 d9.j.run(SourceFile:3) 
	 d9.a.run(SourceFile:96) 

2024-09-30T10:30:53.560:	android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7fa66cf6
	 android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:292) 
	 android.content.res.Resources.getResourcePackageName(Resources.java:2347) 
	 it.fast4x.rimusic.service.PlayerMediaBrowserService.e(SourceFile:19) 
	 V7.o.r(SourceFile:343) 
	 B8.a.i(SourceFile:9) 
	 V8.O.run(SourceFile:113) 
	 K5.q.run(SourceFile:232) 
	 d9.j.run(SourceFile:3) 
	 d9.a.run(SourceFile:96) 

2024-09-30T10:30:57.309:	android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7fa66cf6
	 android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:292) 
	 android.content.res.Resources.getResourcePackageName(Resources.java:2347) 
	 it.fast4x.rimusic.service.PlayerMediaBrowserService.e(SourceFile:19) 
	 V7.o.r(SourceFile:343) 
	 B8.a.i(SourceFile:9) 
	 V8.O.run(SourceFile:113) 
	 K5.q.run(SourceFile:232) 
	 d9.j.run(SourceFile:3) 
	 d9.a.run(SourceFile:96) 

2024-09-30T10:31:01.346:	android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7fa66cf6
	 android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:292) 
	 android.content.res.Resources.getResourcePackageName(Resources.java:2347) 
	 it.fast4x.rimusic.service.PlayerMediaBrowserService.e(SourceFile:19) 
	 V7.o.r(SourceFile:343) 
	 B8.a.i(SourceFile:9) 
	 V8.O.run(SourceFile:113) 
	 K5.q.run(SourceFile:232) 
	 d9.j.run(SourceFile:3) 
	 d9.a.run(SourceFile:96) 

2024-09-30T10:31:03.508:	android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7fa66cf6
	 android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:292) 
	 android.content.res.Resources.getResourcePackageName(Resources.java:2347) 
	 it.fast4x.rimusic.service.PlayerMediaBrowserService.e(SourceFile:19) 
	 V7.o.r(SourceFile:343) 
	 B8.a.i(SourceFile:9) 
	 V8.O.run(SourceFile:113) 
	 K5.q.run(SourceFile:232) 
	 d9.j.run(SourceFile:3) 
	 d9.a.run(SourceFile:96) 

2024-09-30T10:31:05.205:	android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7fa66cf6
	 android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:292) 
	 android.content.res.Resources.getResourcePackageName(Resources.java:2347) 
	 it.fast4x.rimusic.service.PlayerMediaBrowserService.e(SourceFile:19) 
	 V7.o.r(SourceFile:343) 
	 B8.a.i(SourceFile:9) 
	 V8.O.run(SourceFile:113) 
	 K5.q.run(SourceFile:232) 
	 d9.j.run(SourceFile:3) 
	 d9.a.run(SourceFile:96) 

2024-09-30T10:31:08.925:	android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7fa66cf6
	 android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:292) 
	 android.content.res.Resources.getResourcePackageName(Resources.java:2347) 
	 it.fast4x.rimusic.service.PlayerMediaBrowserService.e(SourceFile:19) 
	 V7.o.r(SourceFile:343) 
	 B8.a.i(SourceFile:9) 
	 V8.O.run(SourceFile:113) 
	 K5.q.run(SourceFile:232) 
	 d9.j.run(SourceFile:3) 
	 d9.a.run(SourceFile:96) 

2024-09-30T10:31:24.692:	android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7fa66cf6
	 android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:292) 
	 android.content.res.Resources.getResourcePackageName(Resources.java:2347) 
	 it.fast4x.rimusic.service.PlayerMediaBrowserService.e(SourceFile:19) 
	 V7.o.r(SourceFile:343) 
	 B8.a.i(SourceFile:9) 
	 V8.O.run(SourceFile:113) 
	 K5.q.run(SourceFile:232) 
	 d9.j.run(SourceFile:3) 
	 d9.a.run(SourceFile:96) 

2024-09-30T10:31:26.333:	android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7fa66cf6
	 android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:292) 
	 android.content.res.Resources.getResourcePackageName(Resources.java:2347) 
	 it.fast4x.rimusic.service.PlayerMediaBrowserService.e(SourceFile:19) 
	 V7.o.r(SourceFile:343) 
	 B8.a.i(SourceFile:9) 
	 V8.O.run(SourceFile:113) 
	 K5.q.run(SourceFile:232) 
	 d9.j.run(SourceFile:3) 
	 d9.a.run(SourceFile:96) 

2024-09-30T10:31:27.731:	android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7fa66cf6
	 android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:292) 
	 android.content.res.Resources.getResourcePackageName(Resources.java:2347) 
	 it.fast4x.rimusic.service.PlayerMediaBrowserService.e(SourceFile:19) 
	 V7.o.r(SourceFile:343) 
	 B8.a.i(SourceFile:9) 
	 V8.O.run(SourceFile:113) 
	 K5.q.run(SourceFile:232) 
	 d9.j.run(SourceFile:3) 
	 d9.a.run(SourceFile:96) 

### RiMusic version

0.6.54.1

### Android version

Android 14

### Additional information

Testei o app em outros dois dispositivos, um com Android 9.0 e outro com Android 11 Go. O erro não ocorreu nesses dispositivos

**Comment by p054888** [comment]
I had this issue to, solved my problem.
1st - Backup
2nd - uninstall
3rd - installed 0.6.54
4th - restore backup
no sure

**Comment by Ytalol43** [comment]
Thanks man, It was a good temporary solution 😀👍

**Comment by Marcelo1565** [comment]
Aconteceu o mesmo comigo, foi logo depois da atualização para 0.6.54.1. Infelizmente 😕.

This also happened to me, it was after the update to 0.6.54.1. Unfortunately 😕.
