### ISSUE TITLE
Visualizer permission popup broke

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#383]
### Steps to reproduce the bug

1. Enable Visualizer (any) & dont forget to grant mic permission
2. Disable permission directly from app settings
3. Enjoy broken visualizer permission popup

### Expected behavior

You know lah, need popup if not granted

### Actual behavior

No popup, idk if mic permission really needed here

### RiMusic version

0.6.16.1

### Android version

Android 11

### Additional information

2019 Samsung device

**Comment by OrangeZXZ** [comment]
Tried and yeah it spams the "You need mike permission" it should only show 1 time

**Comment by fast4x** [comment]
Popup comes out or doesn’t come out? 
try with the latest version released

**Comment by faustaahmad** [comment]
Still same no popup, should I do clean install of app first?

**Comment by fast4x** [comment]
Try reinstall latest version 0.6.19

**Comment by faustaahmad** [comment]
Tried after clean install (uninstal > restart phone > install) no popup
Also it seems like my rom (OneUI stock rom) always set all permission to deny unless the app itself ask for it

**Comment by fast4x** [comment]
would be fixed, available from version 0.6.20
