### ISSUE TITLE
[Feature]: Spotify playlist to rimusic playlist

### ISSUE THREAD

**Issue by Wyattt34** [fast4x/RiMusic#3830]
### Description

I wanna add my Spotify playlist to rimusic but I can't because I have a lot of song it's like 2000+ and I don't have time for that please add this feature

### Suggested Solution

Solution is to add like other apps sync to make our day faster

### Additional Context

Also downloading song is taking so long

**Comment by fast4x** [comment]
Hi, can transfer to YTM and import in riMusic.
