### ISSUE TITLE
Formato de Audio incompatible 

### ISSUE THREAD

**Issue by Azbemus** [fast4x/RiMusic#3831]
### Steps to reproduce the bug

Únicamente reproduzco canciones, y me sale un mensaje que dice "no se puede encontrar un formato de audio compatible"
Sin embargo, algunas canciones si las reproduce. 

### Expected behavior

Debería reproducirse de manera normal, ya que lo hacía así anteriormente 

### Actual behavior

Me salió un mensaje que decía formato de audio incompatible 

### Screenshots/Screen recordings

![Screenshot_20240930_090735_it_fast4x_rimusic_MainActivity](https://github.com/user-attachments/assets/0fc1c34b-4fd1-4140-bc51-183abaca5b1f)

### RiMusic version

"0.6.54.1" 

### Android version

Android 14

### Additional information

![Screenshot_20240930_091505_it_fast4x_rimusic_MainActivity](https://github.com/user-attachments/assets/7d551304-5c39-4f3c-b25d-138a8494fd59)
![Screenshot_20240930_091513_it_fast4x_rimusic_MainActivity](https://github.com/user-attachments/assets/0cad5037-f579-444b-9869-06036b999a15)
![Screenshot_20240930_091521_it_fast4x_rimusic_MainActivity](https://github.com/user-attachments/assets/482a90c4-d5d1-46d2-9b9b-90f8b9f5f950)

Se puede ver como en la última captura si se reproduce normal

**Comment by fast4x** [comment]
Improved, available from version 0.6.55
