### ISSUE TITLE
Better shuffle and playlist options 

### ISSUE THREAD

**Issue by Jhonsilva953** [fast4x/RiMusic#3832]
### Description

Make some changes to the playlist and the shuffle option 

### Suggested Solution

I have an idea of having an option to lock the songs in the Shuffle option, because many times when we shuffle the songs, there are some that are in the right place, but every time I shuffle the songs they go back to a bad place, and it could also have  An option to move songs from the "downloaded" and "all" playlists

### Alternatives

![52 Sem Título](https://github.com/user-attachments/assets/b564ec37-90c0-48f5-a372-0f1bcaf28d8f)
![53 Sem Título_20240930144617](https://github.com/user-attachments/assets/a4968a98-80ca-494f-a6e7-5f9884f7db85)

**Comment by knighthat** [comment]
Can you explain the "right place" and "bad place"?

As far as my understanding, you're talking about ordering the playlist. "Shuffle" to me means play in random

**Comment by Jhonsilva953** [comment]
I'll give you an example, like I want the song "heaven can't wait" to be
3rd in the queue, but every time I shuffle the song, the song keeps
changing places, so I have to keep moving it,I want to lock the songs in
the places I want so that when I shuffle them they don't move from the
place in the queue where I want them to be.

Em ter., 1 de out. de 2024 14:30, Knight Hat ***@***.***>
escreveu:

**Comment by knighthat** [comment]
Sounds like you want a shuffled and ordered positions at the same time. That defeats the whole purpose of shuffling.

Furthermore, having an algorithm rearrange positions after shuffle will put more stress on the battery

Anyway, I don't see this feature's really worth the effort. We only have a handful amount of devs and not many of them are actively developing new things. But maybe in the future, I'll take a look again and see what I can do
