### ISSUE TITLE
Algunas canciones no se reproducen

### ISSUE THREAD

**Issue by Alexsa-lang** [fast4x/RiMusic#3835]
### Steps to reproduce the bug

Hay canciones que no se reproducen..me sale "no se puede encontrar un formato de audio compatible"

### Expected behavior

Deberia reproducir toda canción 

### Actual behavior

Ya se vuelve un problema que molesta si me pudieran ayudar les agradecería 

### RiMusic version

Versión 6.54.1

### Android version

Xiaomi 9c

### Additional information

A

**Comment by fast4x** [comment]
Bug not reproducible
