### ISSUE TITLE
Force close when try to access playlist

### ISSUE THREAD

**Issue by rafianwars** [fast4x/RiMusic#3836]
### Steps to reproduce the bug

1. Go to app
2. Press playlist tab
3. Force close

I think there's a bug in playlist

### Expected behavior

1. No force close
2. Can access playlist which i made before

### Actual behavior

1. Force close
2. Can't identify where's the troubled or bugged playlist

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/14e0e3f7-a745-4816-8c6e-64a50b05a27a

### RiMusic version

v.0.6.54

### Android version

android 12

### Additional information

Crash log:

2024-08-01T22:34:29.447:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.K.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8322) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038) 

2024-08-02T17:53:29.916:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 U6.m.a(SourceFile:230) 
	 w.A.b(SourceFile:34) 
	 y.f1.u(SourceFile:283) 
	 r7.a.l(SourceFile:9) 
	 J7.D.B(SourceFile:79) 
	 J7.g.o(SourceFile:105) 
	 J7.g.E(SourceFile:33) 
	 J7.g.l(SourceFile:17) 
	 C0.H.u(SourceFile:71) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8322) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038) 

2024-08-02T17:53:58.081:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 U6.m.a(SourceFile:230) 
	 w.A.b(SourceFile:34) 
	 y.f1.u(SourceFile:283) 
	 r7.a.l(SourceFile:9) 
	 J7.D.B(SourceFile:79) 
	 J7.g.o(SourceFile:105) 
	 J7.g.E(SourceFile:33) 
	 J7.g.l(SourceFile:17) 
	 C0.H.u(SourceFile:71) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8322) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038) 

2024-08-02T18:02:35.628:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.j0.u(SourceFile:68) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8322) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038) 

2024-08-02T18:06:54.048:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.j0.u(SourceFile:68) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8322) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038) 

2024-08-03T09:10:43.795:	java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to it.fast4x.rimusic.MainActivity
	 a.a.m(SourceFile:57) 
	 b7.K.u(SourceFile:41) 
	 r7.a.l(SourceFile:9) 
	 J7.K.run(SourceFile:113) 
	 J0.c0.h0(SourceFile:7) 
	 J0.b0.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8322) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038) 

2024-08-03T09:10:55.389:	java.lang.IllegalStateException
	 n2.b.j(SourceFile:6) 
	 r2.x.h(SourceFile:6) 
	 r2.x.g(SourceFile:34) 
	 f2.c.m(SourceFile:94) 
	 W6.C0.h(SourceFile:145) 
	 e0.a.d(SourceFile:44) 
	 e0.a.h(SourceFile:9) 
	 C.i.m(SourceFile:98) 
	 e0.a.e(SourceFile:44) 
	 e0.a.m(SourceFile:9) 
	 B.p.i(SourceFile:380) 
	 e0.a.i(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 E.L.b(SourceFile:248) 
	 D.n.e(SourceFile:104) 
	 A6.s.i(SourceFile:419) 
	 e0.a.i(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 g0.f.c(SourceFile:149) 
	 E.n0.c(SourceFile:87) 
	 E.L.d(SourceFile:105) 
	 B.x.i(SourceFile:1046) 
	 e0.a.i(SourceFile:52) 
	 B.x.i(SourceFile:817) 
	 e0.a.i(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.p.p(SourceFile:203) 
	 W.t.k(SourceFile:32) 
	 W.t0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.t.l(SourceFile:9) 
	 G0.H.i(SourceFile:22) 
	 G0.H.h(SourceFile:120) 
	 G0.C.H(SourceFile:160) 
	 E.V.b(SourceFile:34) 
	 D.r.b(SourceFile:21) 
	 D.s.b(SourceFile:62) 
	 q8.m.S(SourceFile:23) 
	 D.t.i(SourceFile:639) 
	 B.x.i(SourceFile:934) 
	 G0.E.g(SourceFile:74) 
	 I0.u.b(SourceFile:38) 
	 q0.X.i(SourceFile:1) 
	 I0.A.b(SourceFile:15) 
	 B.h0.i(SourceFile:117) 
	 I0.A.b(SourceFile:15) 
	 B.H.i(SourceFile:99) 
	 I0.A.b(SourceFile:15) 
	 A6.k.a(SourceFile:1060) 
	 U1.c.y(SourceFile:56) 
	 h0.t.a(SourceFile:52) 
	 h0.u.c(SourceFile:140) 
	 I0.n0.a(SourceFile:3) 
	 I0.L.s0(SourceFile:133) 
	 I0.L.b(SourceFile:91) 
	 B.d.g(SourceFile:86) 
	 B.B.g(SourceFile:40) 
	 I0.u.b(SourceFile:38) 
	 w.L0.i(SourceFile:50) 
	 I0.A.b(SourceFile:15) 
	 q0.X.i(SourceFile:1) 
	 I0.A.b(SourceFile:15) 
	 B.H.i(SourceFile:99) 
	 I0.A.b(SourceFile:15) 
	 A6.k.a(SourceFile:1060) 
	 U1.c.y(SourceFile:114) 
	 h0.t.a(SourceFile:52) 
	 h0.u.c(SourceFile:140) 
	 I0.n0.a(SourceFile:3) 
	 I0.L.s0(SourceFile:133) 
	 I0.F.M(SourceFile:17) 
	 I0.F.N(SourceFile:18) 
	 I0.U.c(SourceFile:8) 
	 I0.U.m(SourceFile:138) 
	 I0.U.j(SourceFile:90) 
	 J0.x.w(SourceFile:36) 
	 B2.r.run(SourceFile:1207) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8322) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038) 

2024-08-06T11:58:37.881:	java.io.IOException: Too many open files
	 sun.nio.ch.IOUtil.makePipe(Native Method) 
	 sun.nio.ch.PollSelectorImpl.<init>(PollSelectorImpl.java:57) 
	 sun.nio.ch.PollSelectorProvider.openSelector(PollSelectorProvider.java:36) 
	 C5.a.u(SourceFile:38) 
	 l7.a.m(SourceFile:9) 
	 E7.L.run(SourceFile:113) 
	 E7.z0.run(SourceFile:195) 
	 L7.k.run(SourceFile:3) 
	 L7.a.run(SourceFile:96) 

2024-08-10T19:56:54.418:	android.content.res.Resources$NotFoundException: File res/go.webp from xml type xml resource ID #0x7f0700d9
	 android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1245) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2538) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2514) 
	 android.content.res.Resources.getXml(Resources.java:1332) 
	 a.a.f0(SourceFile:59) 
	 W6.X.m(SourceFile:1689) 
	 a6.b.c(SourceFile:245) 
	 N6.j1.e(SourceFile:236) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 s7.o.t(SourceFile:1345) 
	 E6.l.e(SourceFile:255) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 A6.i.e(SourceFile:198) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 F6.d.g(SourceFile:442) 
	 e0.a.g(SourceFile:52) 
	 O.U.g(SourceFile:170) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.R1.a(SourceFile:113) 
	 T.S0.b(SourceFile:56) 
	 T.G0.g(SourceFile:214) 
	 e0.a.g(SourceFile:52) 
	 T.U0.g(SourceFile:258) 
	 e0.a.g(SourceFile:52) 
	 T.A0.a(SourceFile:52) 
	 A6.z.g(SourceFile:1206) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.p0.a(SourceFile:395) 
	 A6.X.g(SourceFile:1216) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.T.a(SourceFile:627) 
	 J0.x1.g(SourceFile:250) 
	 e0.a.g(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.x1.g(SourceFile:213) 
	 e0.a.g(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.q.p(SourceFile:203) 
	 W.u.k(SourceFile:32) 
	 W.u0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.u.l(SourceFile:9) 
	 W.u.c(SourceFile:3) 
	 B.j0.b(SourceFile:529) 
	 J0.w.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.y1.c(SourceFile:10) 
	 J0.y1.m(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 B.j0.b(SourceFile:498) 
	 J0.w.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:21120) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3501) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2770) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2275) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9002) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1182) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:972) 
	 android.view.Choreographer.doFrame(Choreographer.java:895) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1164) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8322) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038) 
Caused by:	java.io.FileNotFoundException: Corrupt XML binary file
	 android.content.res.AssetManager.nativeOpenXmlAsset(Native Method) 
	 android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:1114) 
	 android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1229) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2538) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2514) 
	 android.content.res.Resources.getXml(Resources.java:1332) 
	 a.a.f0(SourceFile:59) 
	 W6.X.m(SourceFile:1689) 
	 a6.b.c(SourceFile:245) 
	 N6.j1.e(SourceFile:236) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 s7.o.t(SourceFile:1345) 
	 E6.l.e(SourceFile:255) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 A6.i.e(SourceFile:198) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 F6.d.g(SourceFile:442) 
	 e0.a.g(SourceFile:52) 
	 O.U.g(SourceFile:170) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.R1.a(SourceFile:113) 
	 T.S0.b(SourceFile:56) 
	 T.G0.g(SourceFile:214) 
	 e0.a.g(SourceFile:52) 
	 T.U0.g(SourceFile:258) 
	 e0.a.g(SourceFile:52) 
	 T.A0.a(SourceFile:52) 
	 A6.z.g(SourceFile:1206) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.p0.a(SourceFile:395) 
	 A6.X.g(SourceFile:1216) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.T.a(SourceFile:627) 
	 J0.x1.g(SourceFile:250) 
	 e0.a.g(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.x1.g(SourceFile:213) 
	 e0.a.g(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.q.p(SourceFile:203) 
	 W.u.k(SourceFile:32) 
	 W.u0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.u.l(SourceFile:9) 
	 W.u.c(SourceFile:3) 
	 B.j0.b(SourceFile:529) 
	 J0.w.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.y1.c(SourceFile:10) 
	 J0.y1.m(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 B.j0.b(SourceFile:498) 
	 J0.w.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:21120) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3501) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2770) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2275) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9002) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1182) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:972) 
	 android.view.Choreographer.doFrame(Choreographer.java:895) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1164) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8322) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038) 

2024-08-10T19:57:08.671:	android.content.res.Resources$NotFoundException: File res/go.webp from xml type xml resource ID #0x7f0700d9
	 android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1245) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2538) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2514) 
	 android.content.res.Resources.getXml(Resources.java:1332) 
	 a.a.f0(SourceFile:59) 
	 W6.X.m(SourceFile:1689) 
	 a6.b.c(SourceFile:245) 
	 N6.j1.e(SourceFile:236) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 s7.o.t(SourceFile:1345) 
	 E6.l.e(SourceFile:255) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 A6.i.e(SourceFile:198) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 F6.d.g(SourceFile:442) 
	 e0.a.g(SourceFile:52) 
	 O.U.g(SourceFile:170) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.R1.a(SourceFile:113) 
	 T.S0.b(SourceFile:56) 
	 T.G0.g(SourceFile:214) 
	 e0.a.g(SourceFile:52) 
	 T.U0.g(SourceFile:258) 
	 e0.a.g(SourceFile:52) 
	 T.A0.a(SourceFile:52) 
	 A6.z.g(SourceFile:1206) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.p0.a(SourceFile:395) 
	 A6.X.g(SourceFile:1216) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.T.a(SourceFile:627) 
	 J0.x1.g(SourceFile:250) 
	 e0.a.g(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.x1.g(SourceFile:213) 
	 e0.a.g(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.q.p(SourceFile:203) 
	 W.u.k(SourceFile:32) 
	 W.u0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.u.l(SourceFile:9) 
	 W.u.c(SourceFile:3) 
	 B.j0.b(SourceFile:529) 
	 J0.w.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.y1.c(SourceFile:10) 
	 J0.y1.m(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 B.j0.b(SourceFile:498) 
	 J0.w.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:21120) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3501) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2770) 
	 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2275) 
	 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9002) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1182) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:972) 
	 android.view.Choreographer.doFrame(Choreographer.java:895) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1164) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:211) 
	 android.os.Looper.loop(Looper.java:300) 
	 android.app.ActivityThread.main(ActivityThread.java:8322) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038) 
Caused by:	java.io.FileNotFoundException: Corrupt XML binary file
	 android.content.res.AssetManager.nativeOpenXmlAsset(Native Method) 
	 android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:1114) 
	 android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1229) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2538) 
	 android.content.res.Resources.loadXmlResourceParser(Resources.java:2514) 
	 android.content.res.Resources.getXml(Resources.java:1332) 
	 a.a.f0(SourceFile:59) 
	 W6.X.m(SourceFile:1689) 
	 a6.b.c(SourceFile:245) 
	 N6.j1.e(SourceFile:236) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 s7.o.t(SourceFile:1345) 
	 E6.l.e(SourceFile:255) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 A6.i.e(SourceFile:198) 
	 e0.a.d(SourceFile:44) 
	 e0.a.e(SourceFile:9) 
	 F6.d.g(SourceFile:442) 
	 e0.a.g(SourceFile:52) 
	 O.U.g(SourceFile:170) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 T.R1.a(SourceFile:113) 
	 T.S0.b(SourceFile:56) 
	 T.G0.g(SourceFile:214) 
	 e0.a.g(SourceFile:52) 
	 T.U0.g(SourceFile:258) 
	 e0.a.g(SourceFile:52) 
	 T.A0.a(SourceFile:52) 
	 A6.z.g(SourceFile:1206) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.p0.a(SourceFile:395) 
	 A6.X.g(SourceFile:1216) 
	 e0.a.g(SourceFile:52) 
	 W.c.b(SourceFile:150) 
	 J0.T.a(SourceFile:627) 
	 J0.x1.g(SourceFile:250) 
	 e0.a.g(SourceFile:52) 
	 W.c.a(SourceFile:233) 
	 J0.x1.g(SourceFile:213) 
	 e0.a.g(SourceFile:52) 
	 W.c.O(SourceFile:15) 
	 W.q.p(SourceFile:203) 
	 W.u.k(SourceFile:32) 
	 W.u0.a(SourceFile:43) 
	 W.n.a(SourceFile:5) 
	 W.n.a(SourceFile:5) 
	 W.u.l(SourceFile:9) 
	 W.u.c(SourceFile:3) 
	 B.j0.b(SourceFile:529) 
	 J0.w.setOnViewTreeOwnersAvailable(SourceFile:7) 
	 J0.y1.c(SourceFile:10) 
	 J0.y1.m(SourceFile:19) 
	 androidx.lifecycle.w.a(SourceFile:23) 
	 androidx.lifecycle.x.a(SourceFile:217) 
	 B.j0.b(SourceFile:498) 
	 J0.w.onAttachedToWindow(SourceFile:120) 
	 android.view.View.dispatchAttachedToWindow(View.java:21120) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3501) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508) 
	 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3508)

**Comment by knighthat** [comment]
here's your problem `Caused by: java.io.FileNotFoundException: Corrupt XML binary file`. 

Export your database > reinstall app > import  database

**Comment by rafianwars** [comment]
Done doing it and still happening
Maybe an option to delete playlist from other places or menu will help

https://github.com/user-attachments/assets/74260676-f4a0-48c0-9bc0-c29030d01313

**Comment by knighthat** [comment]
Can you create another playlist to see if it happens again?

**Comment by lemonadeforlife** [comment]
Still facing this issue
