### ISSUE TITLE
Poder tener 1 cuenta 

### ISSUE THREAD

**Issue by Faxxs002** [fast4x/RiMusic#3837]
### Description

Poder tener 1 cuenta o algo algo parecido 

### Suggested Solution

Poder tener 1 cuenta o algo así para que desde esa cuenta poder tener 1 link que te deje acceder a las playlist que tenga: un decir es tener 1 cuenta de tiktok y poner ese link para que la gente pueda acceder a ese playlist de musicas si lo pueden agregar esta bueno ❤️

### Alternatives

Una alternativa sería que solo pudiéramos copiar un link de esa playlist

**Comment by fast4x** [comment]
Hi use piped account https://piped.video
