### ISSUE TITLE
Sync piped no work

### ISSUE THREAD

**Issue by Username-253** [fast4x/RiMusic#3838]
### Steps to reproduce the bug

How does synchronization with piped work? I have connected my account. But if you delete the application and install it again, then when you log into your piped account, nothing happens, the songs are not synchronized and the settings are not either. You have to add songs again.

### Expected behavior

songs should be synchronized and settings too.

### Actual behavior

songs need to be added again. And configure the applications again.

### RiMusic version

v0.6.54.1

### Android version

14

**Comment by fast4x** [comment]
Too generic info, try enable debug, do anything with piped functionality and send log.

**Comment by Username-253** [comment]
> Слишком общая информация, отправьте отладку, сделайте что-нибудь с конвейерной функцией и отправьте журнал.

I'll tell you in more detail: 
1. Installed the application and started using it.
2. Added 100 tracks to the library.
3. Connected your Piped account.
4. Deleted the application.
5. Installed the application again (downloaded the latest version).
6. I logged into my Piped account, but the previously added tracks did not appear.
