### ISSUE TITLE
Swipe with angle will start prev/next song

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#384]
### Steps to reproduce the bug
With this kind of swipe: `(`, `⟨`, `⟩`, `)`, ⤵️ will play prev/next song
Often short distance swipe trigger the gesture (too sensitive)

### Expected behavior
Decided by last swipe line
Swipe down `⟨` equal to `⬋`+`⬊`
Last swipe `⬊` close to vertical line, minimize player
If the last swipe close to vertical line, minimize player
If the last swipe close to horizontal line, play prev/next song

If the last swipe has very short distance, use 2nd last swipe to decide

### Actual behavior
Swipe with angle will play prev/next song

### RiMusic version

0.6.16.1 ~ 0.6.21

### Android version

Android 11

**Comment by OrangeZXZ** [comment]
I can't get the same bug could you try recording it?

**Comment by faustaahmad** [comment]
> I can't get the same bug could you try recording it?

Changed title & description

**Comment by fast4x** [comment]
Improved, available from version 0.6.23

**Comment by faustaahmad** [comment]
Closing this as it has been improved significantly to prevent accidental change on song
