### ISSUE TITLE
Show video uploads on artist's page

### ISSUE THREAD

**Issue by jksekai** [fast4x/RiMusic#3841]
### Description

there should be a special uploaded videos section on the artist's page, 

### Suggested Solution

along with albums and singles, there should be videos tab which shows normal YouTube videos. this content will be played just like how videos play from search results 

### Additional Context

this feature will be useful since some smaller artists might release tracks only as videos, and having thesebvideos directly on their page will make the videos easier to find.

**Comment by knighthat** [comment]
I don't think this will come true any time soon. Videos on YTM is limited to music related topics only.

You can easily verify this by changing the url of a video to `music.youtube.com`. Some of them will display a message saying that the video is unavailable

![video_not_available](https://github.com/user-attachments/assets/297bb0c5-9131-41fb-9d03-7773ae751727)
