### ISSUE TITLE
[Feature]: why fresh install UI such, is there any reason for that specific default ui settings

### ISSUE THREAD

**Issue by AverageOpenSourceEnjoyer** [fast4x/RiMusic#3842]
### Description

The default UI of freshly installed app seems kind of less friendly than the vimusic, is there any reason for keeping such ui, it might discourage new users.

### Suggested Solution

New default settings for UI.

**Comment by knighthat** [comment]
Would you mind sharing your dissatisfaction? Which element of the RiMusic UI is unfriendly?

**Comment by fast4x** [comment]
Hi, RiMusic is born from ViMusic, it offers the possibility to take a very similar look to it with many new features with a new idea for internal page navigation.

**Comment by fast4x** [comment]
It's also true that ViMusic users can set appearance as preferred, after installation. It's same way...

**Comment by ALMIGHTY-VC** [comment]
Time for a onboarding session for new users to Rimusic!?

**Comment by knighthat** [comment]
You can always switch back to ViMusic interfacr. Go to Settings > UI (first tab) > (scroll down) change interface from RiMusic to ViMusic

**Comment by fast4x** [comment]
I don't have much time for video tutorials,new users can go to telegram group tutorial section

**Comment by knighthat** [comment]
You're welcomed to be the first one to make it. Try something easy like navigation and move on from there
