### ISSUE TITLE
When Playing a Song from playlist the song plays but after the 3rd song it jumps back to last 2 song and plays it again then reaching the 3rd song it continues the same way.

### ISSUE THREAD

**Issue by ApexNinja789** [fast4x/RiMusic#3844]
### Steps to reproduce the bug

1. Make a playlist.
2. Add min 20 songs.
3. Play from the first song.
4. Forward the song until the jumping back behaviour happens.
5. After this happens all the songs play with this issue.

### Expected behavior

In a playlist song should play simultaneously without repetition.

### Actual behavior

But on playing the song it plays the songs on reaching 3rd song jumps back to previous 2 songs and then plays on reaching 3rd song again it continues and then does the same

### RiMusic version

0.6.54.1

### Android version

Android 14

### Additional information

Please fix the problem.

**Comment by knighthat** [comment]
can you give me a screen record of the problem. I can't reproduce it

https://github.com/user-attachments/assets/96a1605b-8ecd-4fb5-8e35-f5c19b40205f

**Comment by aneesh1122** [comment]
Use the latest custom version

**Comment by aneesh1122** [comment]
> can you give me a screen record of the problem. I can't reproduce it
> 
> https://github.com/user-attachments/assets/96a1605b-8ecd-4fb5-8e35-f5c19b40205f
> 
> 

He wasn't clear with the steps. You have to put the app in background or lock the screen. Do this while the player is not minimized.

**Comment by ApexNinja789** [comment]
Do this by putting the player in the background or lock the screen also can be done by changing the songs from notification bar player

**Comment by aneesh1122** [comment]
> Do this by putting the player in the background or lock the screen also can be done by changing the songs from notification bar player.
> 
> Sorry for not being clear earlier.

..... didn't I tell him to do exactly that before?

Anyways, did you try the latest custom version?

https://github.com/fast4x/RiMusic/tree/master/customVersion

For some people their bug is solved with this custom version
