### ISSUE TITLE
Text turns grey

### ISSUE THREAD

**Issue by Shmoon1111** [fast4x/RiMusic#3846]
### Steps to reproduce the bug

After closing the app and opening it the text turns grey.

### Expected behavior

What should happen is the text should be to what I put it as which is white.

### Actual behavior

The text turns grey.

### Screenshots/Screen recordings

![Screenshot_20241001_170957](https://github.com/user-attachments/assets/814dc90c-1d64-4887-b777-12666258e3d4)

### Logs

.

### RiMusic version

0.6.54.1

### Android version

Android 14

### Additional information

.

**Comment by fast4x** [comment]
What's your theme?

**Comment by Shmoon1111** [comment]
It's custom theme

**Comment by Shmoon1111** [comment]
> What's your theme?

It's custom theme
