### ISSUE TITLE
Add some music if possible

### ISSUE THREAD

**Issue by Axel289123** [fast4x/RiMusic#3852]
### Description

I really like the music "Am I Losing You" by Bobby Vinton, I would like to know if you could add it please, I appreciate it. 

### Suggested Solution

Add music to your recommendations or search list

### Alternatives

If you can't, it's okay

**Comment by knighthat** [comment]
Hey, the song is searchable on the app

<p align="center">
<img src="https://github.com/user-attachments/assets/cd6770d6-223a-4fc9-845c-4dc111a8e975" width=240px />
</p>
