### ISSUE TITLE
Problem with Discord RPC connection

### ISSUE THREAD

**Issue by Codefilia** [fast4x/RiMusic#3853]
### Steps to reproduce the bug

1. Go into settings and look for the alp settings option 
2. Activate the Discord connection option and press connect

### Expected behavior

It should show on screen the option to connect to Discord with the app 

### Actual behavior

Only a blank screen appears. No options present.

### Screenshots/Screen recordings

![Screenshot_20241002-105445](https://github.com/user-attachments/assets/a7a027ad-9220-43ff-ac1e-5dd056b4cfc2)

### RiMusic version

0.6.54

### Android version

Android 14

**Comment by faustaahmad** [comment]
try update or uninstall update your browser webview

**Comment by fast4x** [comment]
next update will be improved
