### ISSUE TITLE
search function does not serve useful results

### ISSUE THREAD

**Issue by BuZZ-dEE** [fast4x/RiMusic#3854]
### Steps to reproduce the bug

I search for: "starz deeza ragga twins pyro", but the music / video I'm searching for is not in the result (don't know how long I have to scroll). 
https://youtu.be/bLOGgp8-xtc?si=s6F4yzLTqxnZo6aS
If I search the same string on YouTube, I have it in the beginning of the results.

### Expected behavior

Find this https://youtu.be/bLOGgp8-xtc?si=s6F4yzLTqxnZo6aS

### Actual behavior

https://youtu.be/bLOGgp8-xtc?si=s6F4yzLTqxnZo6aS
Is not in the search result

### Screenshots/Screen recordings

![Screenshot_20241002-205947](https://github.com/user-attachments/assets/8bb5ac40-5547-492d-a28e-f7abd6357ad2)

### RiMusic version

0.6.52

### Android version

Android 14

**Comment by fast4x** [comment]
I'll check it

**Comment by knighthat** [comment]
This video is not supported by YouTube Music

<p align="center">
<img src="https://github.com/user-attachments/assets/e48e2e52-a10b-488b-91ff-c21970bf65bc" width=240px />
</p>

You can check if video is supported by YouTube Music by changing the url of that video from `www.youtube.com/watch?v={video_id}` to `music.youtube.com/watch?v={video_id}`. If the result is as shown above, then there's no way we can show it to you in RiMusic

**Comment by fast4x** [comment]
This link go to a video, if you try to share with RiMusic, there is an error. I'll check this error but possibly that video isn't available for RiMusic...

**Comment by BuZZ-dEE** [comment]
@fast4x is it not possible to just play the sound of that video?

**Comment by fast4x** [comment]
Not always

**Comment by knighthat** [comment]
> @fast4x why it needs to be supported by YouTube Music if I want to play only the sound in RiMusic?
> 
> Is it not possible to just play the sound of that video?

At the moment, no!

**Comment by BuZZ-dEE** [comment]
> Not always

Why not?

**Comment by BuZZ-dEE** [comment]
@fast4x why I can listen to this [video](https://www.youtube.com/watch?v=dGCCj2Wh4L0&t=6) in RiMusic? Where is the difference?

**Comment by fast4x** [comment]
Api used by RiMusic can't do this... sorry

**Comment by BuZZ-dEE** [comment]
I would like to understand why some videos available in YouTube Music and some are not.
