### ISSUE TITLE
Imported playlists have wrong artist

### ISSUE THREAD

**Issue by k3nethh** [fast4x/RiMusic#3856]
### Steps to reproduce the bug

1. Import playlist from yt music
2. Save to new playlist

### Expected behavior

Artists names are correct

### Actual behavior

Every songs artist is set to playlist creator

### Screenshots/Screen recordings

Playlist from link
![Screenshot_20241002_204842](https://github.com/user-attachments/assets/edd1338b-cc73-4423-9af0-6a0e211b5a11)
Playlist in library
![Screenshot_20241002_204859](https://github.com/user-attachments/assets/059f921b-ce01-42b0-a16a-6b5528948bd6)

### RiMusic version

0.6.54.1

### Android version

14

**Comment by knighthat** [comment]
what software did you use to do the import?

**Comment by fast4x** [comment]
Fixed, available from version 0.6.55
