### ISSUE TITLE
Reproducción de toda la busque de un cantante 

### ISSUE THREAD

**Issue by stv90** [fast4x/RiMusic#3857]
### Description

Si buscas un cantante... Todas la canciones de ese cantante que se reproduzca automáticamente en la cola de reproducción 

### Suggested Solution

Reproducir todas las canciones de una búsqueda

**Comment by fast4x** [comment]
Just do it from songs page in artist page

**Comment by stv90** [comment]
> Simplemente hazlo desde la página de canciones en la página del artista.

Si pero si no tienes el artista agregado no lo puede hacer..! La idea es que cuando busque un cantante puedas reproducir todo lo que buscaste sobre el cantante... Que se cree como una lista de reproducción automática de lo que buscaste sin tener que hacer la lista de reproducción

**Comment by fast4x** [comment]
You don't have to create playlist, when show an artist click any songs, other songs sane artist will be added in queue ..
