### ISSUE TITLE
[Feature]: Add an option to auto-skip a song on error/playback issue

### ISSUE THREAD

**Issue by jem0n** [fast4x/RiMusic#3859]
### Description

Currently the player just stops when it encounters an error in playing a song.

### Suggested Solution

Have an option to auto-skip to a next song when the player encounters a playback error.

**Comment by fast4x** [comment]
Before was developed and removed because isn't necessary.

**Comment by knighthat** [comment]
I can take a look into this problem. But it's gonna be a while. 

I did notice one thing, once the block is happening, you can't do much because YTM will block most if not any upcoming requests from your device and force you on a '**cooldown**' timer.

**Comment by jem0n** [comment]
> Before was developed and removed because isn't necessary.

I have RiMusic always playing in the background and every time it encounters a "Couldn't find a playable audio format" error, which from my understanding is partly because RiMusic doesn't support video formats or maybe some other error, it will just stop playing. It can be a quite a hassle when it happens multiple times a day especially while driving when the player encounters this error while connected to Android Auto. Having the option to just auto-skip a song whenever the player encounters a playback error should solve this problem and will allow the user to have a seamless/continuous music playback.

**Comment by knighthat** [comment]
I have the same issue too, but I was lucky to have enough time to test, once YTM starts sending out phony response, the only option is to wait until the "cooldown" to stop. Unless you hit the song that you downloaded, the queue will be skipped entirely.

Furthermore, hitting YTM server with multiple requests in short amount of time only worsen the "cooldown" thing. I suggest you to store a few songs on your device so when the "cooldown" starts, switch to it for a couple of songs before coming back to the online playlist.

As stated before, I'll take a look into this problem but it's not our first priority, so it'll be a while before it's "fixed". I hope you understand.

**Comment by fast4x** [comment]
Next version have a little new improvements on streaming decoder. I hope it goes better.

**Comment by fast4x** [comment]
Implemented autoskip if error occur, available from version 0.6.56
