### ISSUE TITLE
[Feature]: Disable swiping down the mini-player

### ISSUE THREAD

**Issue by Crowerade** [fast4x/RiMusic#386]
### Description

It would be nice if one could disable from the settings swiping down the music that is currently playing in order to stop it and delete all the queue.
I'm requesting this because I find myself swiping down inadvertently too many times and deleting my entire queue

### Suggested Solution

Add a setting for disabling swiping down the music currently playing.

**Comment by fast4x** [comment]
You mean the mini player at the bottom?

**Comment by fast4x** [comment]
Implemented, available from version 0.6.23
