### ISSUE TITLE
My player is not working after lastest update 

### ISSUE THREAD

**Issue by Salmanulappu** [fast4x/RiMusic#3860]
### Steps to reproduce the bug

player is crashing 

### Expected behavior

It should be working 

### Actual behavior

Crashing 

### Screenshots/Screen recordings

Crashing 

### Logs

Crashing 

### RiMusic version

0.6.54.1

### Android version

Android 15

### Additional information

Crashing

**Comment by knighthat** [comment]
can you explain in depth? Is there any error message? Did the player crash or the whole app?

**Comment by maxdrew-1** [comment]
Same situation can't load any music upon opening the app

**Comment by maxdrew-1** [comment]
2024-10-04 14:31:59:994 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
