### ISSUE TITLE
[Feature]: Setting to adjust song quality or bitrate

### ISSUE THREAD

**Issue by PK-8484** [fast4x/RiMusic#3862]
### Description

There should be an option in settings to change the quality at which song plays, similar to spotify.

### Suggested Solution

Option in settings to change bitrate at which a track plays.

**Comment by fast4x** [comment]
It's not necessary because automatically select best audio quality available. Before was implemented and successfully replaced.

**Comment by PK-8484** [comment]
I think it will be very useful when we want to listen to songs but cannot afford to spend too much data. As in my case I am outdoor most of the time so can't use wifi and i need mobile data for my other work. So it would be nice if i could save data while listening to songs

**Comment by fast4x** [comment]
Actually if you don't use video, max song is 4MB. But if is much important for you, i can restore functionality.
