### ISSUE TITLE
Error al seguir las musicas

### ISSUE THREAD

**Issue by keoo12** [fast4x/RiMusic#3866]
### Steps to reproduce the bug

Cualquier cancion que pongo y acaba se regresa 2 canciones antes

### Expected behavior

Deberia de pasar que la cancion acaba y sigue la siguiente y siguiente

### Actual behavior

se atrasa dos canciones

### RiMusic version

0.6.54

### Android version

android 14

**Comment by fast4x** [comment]
Wait for new version, maybe it's just fixed.

**Comment by ANGELROX-X** [comment]
Fixed , nice
