### ISSUE TITLE
Be able to Transfer songs from other applications to RiMusic

### ISSUE THREAD

**Issue by Kakona734** [fast4x/RiMusic#3867]
### Description

I was wanting to transfer all my songs and playlists from Spotify to RiMusic but I realized that it couldn't be done and I was quite surprised, I thought it could be done

### Suggested Solution

It would be great if they implemented that function so it would be much easier to go from Spotify or another application to RiMusic

### Alternatives

I don't know

**Comment by knighthat** [comment]
unfortunately, we are not planning to make such implementation

**Comment by fast4x** [comment]
Can transfer all to YouTube music and import from it.
