### ISSUE TITLE
Lyrics Romanization

### ISSUE THREAD

**Issue by github-jl14** [fast4x/RiMusic#3868]
### Description

add a lyrics romanization on songs

### Suggested Solution

add an option on the three dot menu on the player activity named as "Show romanized Lyrics" or something else like that. after clicking that option, a pop up selection will show listing these things: "Auto", "Off"  ```add a message on the bottom part of the pop up saying that they can customize the romanized lrcs on "Settings>`where you wanna place it`"

in the "Player Appearance" section in Settings (or other place you want to place the settings for the layout of romanized lrc), add a option to customize how the user wants to see the romanized lrcs. (romanized alone  or the shrinked orig lrc text on top and bigger romanized text on bottom)

i think you can ask or check [surfbryce](https://www.github.com/surfbryce)'s [beautiful-lyrics](https://www.github.com/surfbryce/beautiful-lyrics) repo for what they use for their lrc romanization on their player.

### Alternatives

if there is no sites for synced romanized lyrics, i think you can use Genius for the unsynchronized, romanized lrc

### Additional Context

![Screenshot_20241004-151225~2](https://github.com/user-attachments/assets/958913f1-4335-4909-b25b-f00d9783b79a)
![Screenshot_20241004-151253~2](https://github.com/user-attachments/assets/3abcffec-7f73-45a9-a0ba-f6f0067393cb)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.60
