### ISSUE TITLE
The app closes by itself when trying to play a song 

### ISSUE THREAD

**Issue by xGeanx** [fast4x/RiMusic#3869]
### Steps to reproduce the bug

I installed the app update and when I entered and played a song, the app closed itself for no apparent reason, which means I couldn't use the app. I would like to know how to fix this problem. 

### Expected behavior

That the app worked correctly without errors 

### Actual behavior

The app closes suddenly without being able to use it at any time and it is tedious since it is an app that I use daily.

### RiMusic version

0.6.54.0.1

### Android version

Android 14

**Comment by wilsoncajisaca** [comment]
Due to a somewhat big change that has been made, it is now necessary to uninstall the app and reinstall it. Remember to back up all your music, from (Settings - Data - Save backup)

**Comment by fast4x** [comment]
Try custom version please

**Comment by mchugh19** [comment]
> Due to a somewhat big change that has been made, it is now necessary to uninstall the app and reinstall it. Remember to back up all your music, from (Settings - Data - Save backup)

Found this after the crashy update. Might it be possible to display this info as a popup on open when needed? Not everyone is likely to find out that this is required.
