### ISSUE TITLE
Playing in car

### ISSUE THREAD

**Issue by francislupen** [fast4x/RiMusic#3871]
### Description

In the car, when I press the play, forward or backward button for the first time, it doesn't work. I have to press play on my phone first, and from there it does play and change songs. In other apps like Amazon Music or Spotify, when I press the forward or backward button on the steering wheel, it does start playing the song.

### Suggested Solution

I don't know what the solution could be, I don't know how the app works internally, maybe leaving the current song in the foreground all the time as an option

**Comment by fast4x** [comment]
Hello, your car Bluetooth device is older?

**Comment by francislupen** [comment]
Hello! ^_^

Indeed, the car's Bluetooth is old (2007), but I'm testing and I think the problem is with my phone (Pixel 8a).

The problem is that the play/resume works fine (in this case with BT headphones), but if I open and listen to Instagram and then watch a YouTube video, when I go back into the RiMusic app the Play button doesn't play the song, I have to select another one. I'm attaching a video.

With the car it's a little different than with the headphones. Going to the car I turn on RiMusic, look for a playlist and press play, I pause it (I did this with Amazon music and Spotify) I put the phone in my pocket, I get in the car and when it's connected I press the steering wheel controls and it doesn't play the song (with the other apps it does), then I take out my phone, go into RiMusic and what I see in the attached video happens to me. I have to press the random arrow button to continue with another song. Once the music starts, the buttons on the car remote to skip the song do work.

It's as if the song in RiMusic loses connection and I can't find where it was playing.

Sorry for the long text.

Thank you very much!

**Comment by sthienard** [comment]
Hello, I have the same problem in my car, the automatic resumption of playback does not work. I don't have this problem with Player Pro (Android). Regards

**Comment by fast4x** [comment]
Try now
