### ISSUE TITLE
About not working

### ISSUE THREAD

**Issue by Anonymous-forreal** [fast4x/RiMusic#3876]
### Steps to reproduce the bug

Whenever i go to settings and click on About the app crashes and closes . If im playing a song at that time it also stops

### Expected behavior

About feature from settings should open and i should be able to access it

### Actual behavior

App crashes

### RiMusic version

0.6.55

### Android version

11

**Comment by fast4x** [comment]
Please, enable debug in miscellaneous settings, close and reopen app, go to about, after crash go again to miscellaneoud setting and copy crash log. 
Paste here crash log

**Comment by Anonymous-forreal** [comment]
2024-10-05T14:23:32.386: android.content.res.Resources$NotFoundException:
Resource ID #0x0
  android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:285)
  android.content.res.Resources.getValue(Resources.java:1533)
  v7.b.d0(SourceFile:43)
  a.b.l(SourceFile:195)
  com.google.crypto.tink.shaded.protobuf.o0.h(SourceFile:484)
  j8.p.F(SourceFile:833)
  g8.l.g(SourceFile:71)
  f0.b.g(SourceFile:52)
  X.e.a(SourceFile:233)
  h0.g.f(SourceFile:149)
  g8.m.o(SourceFile:58)
  f0.b.h(SourceFile:44)
  f0.b.o(SourceFile:9)
  K.n0.e(SourceFile:144)
  f0.b.f(SourceFile:44)
  f0.b.e(SourceFile:9)
  androidx.compose.animation.a.a(SourceFile:1397)
  v.e.g(SourceFile:269)
  f0.b.g(SourceFile:52)
  j7.h.b(SourceFile:937)
  j7.h.a(SourceFile:228)
  W7.G.e(SourceFile:449)
  f0.b.f(SourceFile:44)
  F.P.g(SourceFile:139)
  X.r.N(SourceFile:438)
  X.r.U(SourceFile:137)
  X.r.p(SourceFile:244)
  X.r.L(SourceFile:32)
  X.v.w(SourceFile:23)
  X.t0.t(SourceFile:109)
  X.r0.a(SourceFile:508)
  K0.a0.doFrame(SourceFile:34)
  K0.Y.doFrame(SourceFile:48)
  android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
  android.view.Choreographer.doCallbacks(Choreographer.java:809)
  android.view.Choreographer.doFrame(Choreographer.java:740)

android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
  android.os.Handler.handleCallback(Handler.java:938)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loop(Looper.java:246)
  android.app.ActivityThread.main(ActivityThread.java:8506)
  java.lang.reflect.Method.invoke(Native Method)

com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2024-10-06T20:41:56.543: android.content.res.Resources$NotFoundException:
Resource ID #0x0
  android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:285)
  android.content.res.Resources.getValue(Resources.java:1533)
  v7.b.d0(SourceFile:43)
  a.b.l(SourceFile:195)
  com.google.crypto.tink.shaded.protobuf.o0.h(SourceFile:484)
  j8.p.F(SourceFile:833)
  g8.l.g(SourceFile:71)
  f0.b.g(SourceFile:52)
  X.e.a(SourceFile:233)
  h0.g.f(SourceFile:149)
  g8.m.o(SourceFile:58)
  f0.b.h(SourceFile:44)
  f0.b.o(SourceFile:9)
  K.n0.e(SourceFile:144)
  f0.b.f(SourceFile:44)
  f0.b.e(SourceFile:9)
  androidx.compose.animation.a.a(SourceFile:1397)
  v.e.g(SourceFile:269)
  f0.b.g(SourceFile:52)
  j7.h.b(SourceFile:937)
  j7.h.a(SourceFile:228)
  W7.G.e(SourceFile:449)
  f0.b.f(SourceFile:44)
  F.P.g(SourceFile:139)
  X.r.N(SourceFile:438)
  X.r.U(SourceFile:137)
  X.r.p(SourceFile:244)
  X.r.L(SourceFile:32)
  X.v.w(SourceFile:23)
  X.t0.t(SourceFile:109)
  X.r0.a(SourceFile:508)
  K0.a0.doFrame(SourceFile:34)
  K0.Y.doFrame(SourceFile:48)
  android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
  android.view.Choreographer.doCallbacks(Choreographer.java:809)
  android.view.Choreographer.doFrame(Choreographer.java:740)

android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
  android.os.Handler.handleCallback(Handler.java:938)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loop(Looper.java:246)
  android.app.ActivityThread.main(ActivityThread.java:8506)
  java.lang.reflect.Method.invoke(Native Method)

com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2024-10-06T20:42:13.643: android.content.res.Resources$NotFoundException:
Resource ID #0x0
  android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:285)
  android.content.res.Resources.getValue(Resources.java:1533)
  v7.b.d0(SourceFile:43)
  a.b.l(SourceFile:195)
  com.google.crypto.tink.shaded.protobuf.o0.h(SourceFile:484)
  j8.p.F(SourceFile:833)
  g8.l.g(SourceFile:71)
  f0.b.g(SourceFile:52)
  X.e.a(SourceFile:233)
  h0.g.f(SourceFile:149)
  g8.m.o(SourceFile:58)
  f0.b.h(SourceFile:44)
  f0.b.o(SourceFile:9)
  K.n0.e(SourceFile:144)
  f0.b.f(SourceFile:44)
  f0.b.e(SourceFile:9)
  androidx.compose.animation.a.a(SourceFile:1397)
  v.e.g(SourceFile:269)
  f0.b.g(SourceFile:52)
  j7.h.b(SourceFile:937)
  j7.h.a(SourceFile:228)
  W7.G.e(SourceFile:449)
  f0.b.f(SourceFile:44)
  F.P.g(SourceFile:139)
  X.r.N(SourceFile:438)
  X.r.U(SourceFile:137)
  X.r.p(SourceFile:244)
  X.r.L(SourceFile:32)
  X.v.w(SourceFile:23)
  X.t0.t(SourceFile:109)
  X.r0.a(SourceFile:508)
  K0.a0.doFrame(SourceFile:34)
  K0.Y.doFrame(SourceFile:48)
  android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
  android.view.Choreographer.doCallbacks(Choreographer.java:809)
  android.view.Choreographer.doFrame(Choreographer.java:740)

android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
  android.os.Handler.handleCallback(Handler.java:938)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loop(Looper.java:246)
  android.app.ActivityThread.main(ActivityThread.java:8506)
  java.lang.reflect.Method.invoke(Native Method)

com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by knighthat** [comment]
what language are you using?

**Comment by Anonymous-forreal** [comment]
I am using English language

**Comment by yannabgrall** [comment]
I have the exact same issue.
Using the english langage on version 0.6.55, on a pixel 5, running GrapheneOS.
I can provide logs aswel, if needed.

**Comment by knighthat** [comment]
> I have the exact same issue.
> Using the english langage on version 0.6.55, on a pixel 5, running GrapheneOS.
> I can provide logs aswel, if needed.

Please do

**Comment by yannabgrall** [comment]
> Please do

Here's the crash log dump :

2024-10-10T05:49:31.265:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:254) 
	 android.content.res.Resources.getValue(Resources.java:1456) 
	 v7.b.d0(SourceFile:43) 
	 a.b.l(SourceFile:195) 
	 com.google.crypto.tink.shaded.protobuf.o0.h(SourceFile:484) 
	 j8.p.F(SourceFile:833) 
	 g8.l.g(SourceFile:71) 
	 f0.b.g(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 g8.m.o(SourceFile:58) 
	 f0.b.h(SourceFile:44) 
	 f0.b.o(SourceFile:9) 
	 K.n0.e(SourceFile:144) 
	 f0.b.f(SourceFile:44) 
	 f0.b.e(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.g(SourceFile:269) 
	 f0.b.g(SourceFile:52) 
	 j7.h.b(SourceFile:937) 
	 j7.h.a(SourceFile:228) 
	 W7.G.e(SourceFile:449) 
	 f0.b.f(SourceFile:44) 
	 F.P.g(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:23) 
	 X.t0.t(SourceFile:109) 
	 X.r0.a(SourceFile:508) 
	 K0.a0.doFrame(SourceFile:34) 
	 K0.Y.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1015) 
	 android.view.Choreographer.doFrame(Choreographer.java:941) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389) 
	 android.os.Handler.handleCallback(Handler.java:959) 
	 android.os.Handler.dispatchMessage(Handler.java:100) 
	 android.os.Looper.loopOnce(Looper.java:232) 
	 android.os.Looper.loop(Looper.java:317) 
	 android.app.ActivityThread.main(ActivityThread.java:8623) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
	 com.android.internal.os.ExecInit.main(ExecInit.java:50) 
	 com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) 
	 com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369) 

2024-10-10T07:22:22.948:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:254) 
	 android.content.res.Resources.getValue(Resources.java:1456) 
	 v7.b.d0(SourceFile:43) 
	 a.b.l(SourceFile:195) 
	 com.google.crypto.tink.shaded.protobuf.o0.h(SourceFile:484) 
	 j8.p.F(SourceFile:833) 
	 g8.l.g(SourceFile:71) 
	 f0.b.g(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 g8.m.o(SourceFile:58) 
	 f0.b.h(SourceFile:44) 
	 f0.b.o(SourceFile:9) 
	 K.n0.e(SourceFile:144) 
	 f0.b.f(SourceFile:44) 
	 f0.b.e(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.g(SourceFile:269) 
	 f0.b.g(SourceFile:52) 
	 j7.h.b(SourceFile:937) 
	 j7.h.a(SourceFile:228) 
	 W7.G.e(SourceFile:449) 
	 f0.b.f(SourceFile:44) 
	 F.P.g(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:23) 
	 X.t0.t(SourceFile:109) 
	 X.r0.a(SourceFile:508) 
	 K0.a0.doFrame(SourceFile:34) 
	 K0.Y.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1015) 
	 android.view.Choreographer.doFrame(Choreographer.java:941) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389) 
	 android.os.Handler.handleCallback(Handler.java:959) 
	 android.os.Handler.dispatchMessage(Handler.java:100) 
	 android.os.Looper.loopOnce(Looper.java:232) 
	 android.os.Looper.loop(Looper.java:317) 
	 android.app.ActivityThread.main(ActivityThread.java:8623) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
	 com.android.internal.os.ExecInit.main(ExecInit.java:50) 
	 com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) 
	 com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)

**Comment by knighthat** [comment]
@yannabgrall thanks

**Comment by fast4x** [comment]
Fixed, available from version 0.6.56.1 today...
