### ISSUE TITLE
Unknown Error occurs randomly upon playing next song.

### ISSUE THREAD

**Issue by DKMellow** [fast4x/RiMusic#3879]
### Steps to reproduce the bug

1. Play any song from a queue.
2. Start pressing next song.
3. Unknown error will eventually occur stopping the song from playing.

### Expected behavior

Song plays without errors.

### Actual behavior

A red message stating unknown error appears stopping the song from playing.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/edfcad76-77ca-414e-96da-f13b7d78c0cf

### Logs

[05_10-12-06-36_347.zip](https://github.com/user-attachments/files/17265767/05_10-12-06-36_347.zip)

### RiMusic version

v0.6.55

### Android version

Android 14 Graphene OS

### Additional information

Going back and forth one song allows the song on which the error occured to play.

**Comment by hsp1020** [comment]
RIMUSIC is very good. But it is difficult to use due to this bug. Please fix it.

**Comment by tayuriv** [comment]
0.6.56 still actual problem

**Comment by chriskeeble** [comment]
I'm getting the same error even when not clicking next song, just playing an album for example. Has occurred for last 3 releases.

**Comment by tayuriv** [comment]
![Screenshot_2024-10-14-00-17-00-767_it fast4x rimusic](https://github.com/user-attachments/assets/f0f59832-ea4c-43d7-bf44-a6e3a70ea11e)
![Screenshot_2024-10-14-00-16-56-637_it fast4x rimusic](https://github.com/user-attachments/assets/9e9006b7-4918-4ff3-9f3e-62b67a4ad6d5)
![Screenshot_2024-10-14-00-16-33-403_it fast4x rimusic](https://github.com/user-attachments/assets/574d35d8-6e11-4cfe-bb85-fc1ca78e46f6)
0.6.56.1
android 11
