### ISSUE TITLE
Error downloading 

### ISSUE THREAD

**Issue by Scottisen4k** [fast4x/RiMusic#3880]
### Steps to reproduce the bug

1 I accidentally downloaded my monthly playlist and it got stuck, 2 I deleted all the downloads from that playlist and I had to download all my songs separately 3 it says that the songs are being downloaded 

### Expected behavior

Download songs without fail 

### Actual behavior

It stays with the downloading symbol and does not work 

### Screenshots/Screen recordings

![Screenshot_20241005-091317](https://github.com/user-attachments/assets/96489237-5aee-47fc-9908-344935b0d71b)
![Screenshot_20241005-091330](https://github.com/user-attachments/assets/ff70c515-e4e6-4631-8fd1-d273a8008441)

### RiMusic version

0.6.55

### Android version

Android 13

**Comment by fast4x** [comment]
Improved, available from version 0.6.56
