### ISSUE TITLE
Downloads are paused

### ISSUE THREAD

**Issue by TkJess0987** [fast4x/RiMusic#3884]
### Steps to reproduce the bug

I went to download a song and it stops by itself and won't let me download it anymore. I have to keep closing the application every now and then.

### Expected behavior

Shouldn't they just play by themselves if I pause them, right?

### Actual behavior

D

### Screenshots/Screen recordings

Y

### RiMusic version

0.6.55

### Android version

Android 14

### Additional information

Just fix it please

**Comment by fast4x** [comment]
Send link to a song please

**Comment by fast4x** [comment]
Improved, available from version 0.6.56
