### ISSUE TITLE
The skip silence button doesn't work

### ISSUE THREAD

**Issue by TkJess0987** [fast4x/RiMusic#3885]
### Steps to reproduce the bug

When you activate the function to skip silences, the song goes crazy, it becomes fast, I don't understand why, but I hope they fix it. 

### Expected behavior

That only the final time of the songs is omitted when you are silent obviously 

### Actual behavior

Not working:(

### RiMusic version

0.6.55

### Android version

Android 14

**Comment by fast4x** [comment]
Have set minumun time?

**Comment by fast4x** [comment]
Fixed skip silence, available from version 0.6.56
