### ISSUE TITLE
Crashes upon opening playlist tab

### ISSUE THREAD

**Issue by C4-x** [fast4x/RiMusic#3886]
### Steps to reproduce the bug

1. Open the App
2. click on playlist tab

### Expected behavior

Should open playlist tab showing all the playlists 

### Actual behavior

App crashes

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/d79dac3e-4600-42dd-a9f0-897cce9e1f59

### Logs

[Logs.zip](https://github.com/user-attachments/files/17268700/Logs.zip)

### RiMusic version

0.6.55

### Android version

Android 12

**Comment by fast4x** [comment]
I can't reproduce this error

**Comment by fast4x** [comment]
Try to backup database, delete all your playlist, restart app and go playlists... if crash not occur the problem is your data

**Comment by harsh-jha** [comment]
this is happening with me as well. it has started since 2 days ago.
i have cleared cache, deleted storage data and reinstalled after uninstalling several times.

https://github.com/user-attachments/assets/6473640b-5f8d-4268-8c8a-3ac9eaeee127

**Comment by C4-x** [comment]
> Try to backup database, delete all your playlist, restart app and go playlists... if crash not occur the problem is your data

It turns out it doesn't crash if I don't have my database attached as soon as I attach my database it crashes, how may I fix this?
How can I fix the error in the database please suggest.

**Comment by harsh-jha** [comment]
> > Try to backup database, delete all your playlist, restart app and go playlists... if crash not occur the problem is your data
> 
> It turns out it doesn't crash if I don't have my database attached as soon as I attach my database it crashes,
> 
> The problem was some playlists pointing to a null value, deleting those occurances in the database solved the problem Thanks

hi there, how can we edit the db and find out null pointers outside of the application. if you can let me know perhaps i can do the same

**Comment by fast4x** [comment]
So you have a null playlist id in database?

**Comment by C4-x** [comment]
> > > Try to backup database, delete all your playlist, restart app and go playlists... if crash not occur the problem is your data
> > 
> > It turns out it doesn't crash if I don't have my database attached as soon as I attach my database it crashes,
> > 
> > The problem was some playlists pointing to a null value, deleting those occurances in the database solved the problem Thanks
> 
> hi there, how can we edit the db and find out null pointers outside of the application. if you can let me know perhaps i can do the same 

Search for SQLite editor on playstore, Delete the ones with null browseid
![Screenshot_20241007-175430_SQLite Editor.jpg](https://github.com/user-attachments/assets/197fddc6-7f89-4647-af80-b36ac47fb5bd)

**Comment by C4-x** [comment]
> So you have a null playlist id in database?

Refer to this please 

![Screenshot_20241007-175430_SQLite Editor.jpg](https://github.com/user-attachments/assets/b9a5a47d-6dcc-475c-a59b-7d4cb2521110)

**Comment by harsh-jha** [comment]
@C4-x thanks for the help. i see all the playlist with nulls in them, which is very odd.
![Screenshot_20241007-083445](https://github.com/user-attachments/assets/0bb0a1e6-c937-4d40-afd1-d1f9e56a60d4)

**Comment by C4-x** [comment]
> @C4-x thanks for the help. i see all the playlist with nulls in them, which is very odd.
> ![Screenshot_20241007-083445](https://github.com/user-attachments/assets/0bb0a1e6-c937-4d40-afd1-d1f9e56a60d4)
> 

That seems very odd 😕 
I guess you'll have to remove all of them hope you have them on YouTube on some other account, 
I have migrated my playlists from Spotify to Yt music which, I then imported to Rimusic, to avoid problems like this.

**Comment by fast4x** [comment]
BrowseId is only for online playlist, in other will be always null. Check nulla for id

**Comment by harsh-jha** [comment]
@fast4x thanks for the response and for maintaining this application

can you please elaborate what is meant by "online playlist"?
none of the songs in any of these are from local storage from device, if that's what you meant.

**Comment by fast4x** [comment]
There is a check for this possible issue, wait please.
