### ISSUE TITLE
Bug ao trocar de música pelas notificações

### ISSUE THREAD

**Issue by itzDoug** [fast4x/RiMusic#3891]
### Steps to reproduce the bug

quando eu troco de música pelas notificações, de vez enquanto, ao pular duas músicas volta para as duas anteriores trocadas

### Expected behavior

deveria ir pulando de música, e não voltar

### Actual behavior

voltou duas músicas ao invés de ir para a próxima

### RiMusic version

0.6.55

### Android version

Android 14

**Comment by fast4x** [comment]
Check your queue maybe it's duplicated
