### ISSUE TITLE
Problemas de reproducción a largos plazos de tiempo

### ISSUE THREAD

**Issue by Aetherimpact802** [fast4x/RiMusic#3893]
### Steps to reproduce the bug

Problemas de reproducción a largos plazos de tiempo y a veces al presionar una canción te sale el mensaje problemas de reproducción y toca volver a presionar otra vez para que comience a reproducir la canción 

### Expected behavior

Que la canción se pueda reproducir a largos plazos de tiempo y que no muestra error de reproducción al presionar una canción 

### Actual behavior

Problemas de reproducción a largos plazos de tiempo y a veces al presionar una canción te sale el mensaje problemas de reproducción y toca volver a presionar otra vez para que comience a reproducir la canción 

### Screenshots/Screen recordings

![Screenshot_2024-10-07-04-15-27-064_it fast4x rimusic](https://github.com/user-attachments/assets/330be6fa-392e-4b53-a955-699eb4fa6c0f)

### RiMusic version

En todas versión 

### Android version

Android 11

**Comment by fast4x** [comment]
Hold song and click on update

**Comment by Aetherimpact802** [comment]
Does that fix the permanent error, or is it just like clicking on the song
again?

**Comment by fast4x** [comment]
There's an activity to fix this
