### ISSUE TITLE
Skip silence does not respect the set minimum and skips silence in between notes

### ISSUE THREAD

**Issue by Ich-kann-lesen** [fast4x/RiMusic#3899]
### Steps to reproduce the bug

1.Enable skip silence (minimum duration appears to be irrelevant)
2. Play a song e.g. Lord Willin' by Logic (happens on a lot of songs)

### Expected behavior

The song plays at normal speed with silences longer than the defined minimum being skipped.

### Actual behavior

Some intros and outros play back faster and the rhythm is messed up. This seems to be because tiny pauses in between notes are skipped.

### RiMusic version

0.6.55

### Android version

14

**Comment by fast4x** [comment]
Fixed skip silence, available from version 0.6.56
