### ISSUE TITLE
[Feature]: Option to select items on the Quick picks tab / hide the entire tab

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#39]
### Description

Option to choose what the home tab will be - Quick picks or Playlists etc.

Whether to display Tips, Related albums, Similar artists in Quick picks.

### Additional Context

Especially for non-English songs, the Quick picks Tips sometimes show songs that have nothing to do with the last played at all.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.21
