### ISSUE TITLE
Erratic speed up at song start

### ISSUE THREAD

**Issue by aithonai** [fast4x/RiMusic#3902]
### Steps to reproduce the bug

Go to downloaded songs and play music

### Expected behavior

Play the song as usual, with no erratic speed up

### Actual behavior

The song have an erratic start, the bug appear un some songs, just speed up at the start like 5, 6 seconds, then play as usual with no errors

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/6def9dab-0548-4198-b0d2-9890370bf11a

### RiMusic version

0.6.55

### Android version

Android 11

### Additional information

I love the app, go ahead 🤠

**Comment by VARTIK-ARSH** [comment]
@fast4x @aithonai  **should i start the work on it .**

**Comment by fast4x** [comment]
Hi,  if you understand the problem, you can contribute. Thank you.

**Comment by fast4x** [comment]
> @fast4x @aithonai  **should i start the work on it .**

Hi,  if you understand the problem, you can contribute. Thank you.

**Comment by fast4x** [comment]
I tried but bug not reproducible in my device

**Comment by aithonai** [comment]
> I tried but bug not reproducible in my device

You tried playing a downloaded music?, but that you downloaded a week ago?

**Comment by aithonai** [comment]
I will try to reinstall the app.

**Comment by fast4x** [comment]
Yes i've played a months ago downloaded songs without issues.

**Comment by fast4x** [comment]
I'll try maniac song

**Comment by aithonai** [comment]
> I'll try maniac song

Well, I reinstalled the app, it works normally when I download a music, y saved my downloaded files in a zip, I will put them inside the app again to see if error appears

**Comment by fast4x** [comment]
You have skip silence enabled?

**Comment by aithonai** [comment]
> You have skip silence enabled?

Yes.

**Comment by fast4x** [comment]
Try without it, maybe bug is in skip silence.

**Comment by fast4x** [comment]
Fixed skip silence, available from version 0.6.56
