### ISSUE TITLE
No reproduce videos

### ISSUE THREAD

**Issue by CarlosAmadorMx** [fast4x/RiMusic#3906]
### Steps to reproduce the bug

1 buscar una canción 
2 ir a la sección de videos
3 reproducir el video

### Expected behavior

Se espera ver el video

### Actual behavior

Reproduce el audio del vídeo 
![Screenshot_20241008_133652](https://github.com/user-attachments/assets/7638d7de-3d8e-4904-a067-52bf1386948b)

### Screenshots/Screen recordings

Pues lo que se espera al reproducir un video se espera que se pueda ver el video 
![Screenshot_20241008_133652](https://github.com/user-attachments/assets/b9a512b9-6ad6-48f4-83d5-fd92f1b56679)

### RiMusic version

V0.6.55

### Android version

Android 14

**Comment by fast4x** [comment]
Must enable video in player settings, after from player click on video icon...
