### ISSUE TITLE
Cover art doesn't change on visualiser

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#3909]
### Steps to reproduce the bug

1. Play a song
2. Open visualiser
3. Change song

### Expected behavior

The cover art should change on the visualiser when the next song is playing

### Actual behavior

The visualiser stays the same. It has to be closed and opened again to change the cover art

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/f91d23eb-29b2-43a8-9905-a9901ca58bcc

### RiMusic version

0.6.55

### Android version

Android 14

### Additional information

The background also doesn't load, as seen on the video.

**Comment by cMattw** [comment]
I've already reported this, I don't know why it got closed

**Comment by aneesh1122** [comment]
Give it some time. It doesn't change instantly

**Comment by fast4x** [comment]
was fixed and now it occur again

**Comment by aneesh1122** [comment]
> > Give it some time. It doesn't change instantly
> 
> necessary improve

for the meantime use RiMusic logo as the placeholder until the next song's thumbnail is loaded

**Comment by fast4x** [comment]
Fixed, available from version 0.6.56
