### ISSUE TITLE
Search bar improvements

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#391]
### Description

The current search bar isn't that good looking
![Screenshot_20240113-093546](https://github.com/fast4x/RiMusic/assets/120176369/c1c7fce6-ab36-43c6-ae65-b5aeb5128a21)

### Suggested Solution

Slim down the search bar and text
![Picsart_24-01-13_09-37-32-714](https://github.com/fast4x/RiMusic/assets/120176369/79ee0a80-76c6-46e0-9372-9baad27308d8)

### Additional Context

Please see issue #345

**Comment by ikanakova** [comment]
I think search bar is fixed (#374), isn't it @fast4x?

**Comment by fast4x** [comment]
> improvement to search bar is in #368

Is differenti, him ask for decrease the size of the character in search bar.

**Comment by fast4x** [comment]
Improved search field
Available from version 0.6.18

**Comment by faustaahmad** [comment]
When you press `Clear` button or delete the words quickly, the recommendation wont disappear
Is this a feature?

**Comment by fast4x** [comment]
Yes

**Comment by faustaahmad** [comment]
IMO still looks a bit... wierd
It goes like this
```
(      ...                )
( ..............          )
```
Consider to make it like this
```
(      ...                )
(      .............      )
(     ..............      )
(     ...............     )
(.........................)
```
Optional, add a little bit of inner shadow before the end of side border ``(~>shad         shad<~)``

![](https://github.com/fast4x/RiMusic/assets/45221211/848ab9e3-48a9-473c-9786-6f81699e782e)

**Comment by faustaahmad** [comment]
~~Add improvement on search inside songs list too~~
Consider removing it^, since its redundant and can search music in library with only 1 additional tap via main search button

**Comment by fast4x** [comment]
Search box has many tabs with different search, i can only adjust left margin inside tab.
I don't want clone other app... RiMusic must have their personality.

**Comment by faustaahmad** [comment]
I think I'm bad at explaining stuff with words only
What I mean by left & right margin/space are this
```
┌ left border
│ ┌ search box ┐  ┌ right border
(┬[ ┆...        ]┬)
 │  │            └ right margin
 │  └ align suggestion
 └ left margin
```
```
Current style
([ search box ])
([   ty       ])
([ typing     ])
([typing......])
([ing.........])
   typing suggestion

Youtube style
( [search box ] )
( [typing...  ] )
( [ing........] )
   typing suggestion

Suggested style (kinda prefer youtube style tbh, simple)
( [ search box ] )
( [  ty        ] )
( [  typing    ] )
( [  typing..  ] )
( [ typing.... ] )
( [typing......] )
( [ing.........] )
     typing suggestion
```
Hope with this, can see clear imagination of what I described on my previous comment
\- left & right margin/space
\- typing behavior
\- align search with suggestion

I think suggested style will still maintain the current behavior
Sorry if my comment contains any offensive wording
Thanks again 👍

**Comment by fast4x** [comment]
You’re not offensive, thank you. I just wanted to say that ok for the changes the important thing is to keep the personality of RiMusic.

**Comment by faustaahmad** [comment]
@fast4x please open this issue again if you still willing to implement it
Thanks

**Comment by fast4x** [comment]
Search bar can't have priority.

**Comment by faustaahmad** [comment]
> <s>Add improvement on search inside songs list too</s>
Consider removing it^, since its redundant and can search music in library with only 1 additional tap via main search button

Perhaps, not removing it was better options, just need bit more left & right margin/padding for cleaner looks
![](https://github.com/fast4x/RiMusic/assets/45221211/1ec69a76-f750-48df-9c81-614f76b6808c)
![](https://github.com/fast4x/RiMusic/assets/45221211/36025b69-48c8-437a-b720-d434cb6485b7)
