### ISSUE TITLE
Background play not working 

### ISSUE THREAD

**Issue by Crod102** [fast4x/RiMusic#3916]
### Steps to reproduce the bug

1. Play a song 
2. Exit the app 
3. Song stops playing 

### Expected behavior

When exiting the app the song you're listening to should keep playing 

### Actual behavior

When you exit the app the song your listening to stops playing 

### RiMusic version

0.6.55

### Android version

Android 14

**Comment by fast4x** [comment]
Enable in ui settings background player...

**Comment by Crod102** [comment]
You're talking about the "close background player" setting in the UI settings right?

**Comment by fast4x** [comment]
your Android version?
