### ISSUE TITLE
Song reproduces incorrectly

### ISSUE THREAD

**Issue by woskkdmsosid** [fast4x/RiMusic#3917]
### Steps to reproduce the bug

Play a song (depends on which)
See error

### Expected behavior

Reproduce correclty

### Actual behavior

Some parts of the song speed up or repeat 

### Screenshots/Screen recordings

music video from yt has flashing lights
https://github.com/user-attachments/assets/aa5aee71-f6e4-42a3-b7b6-4a23c0dd60d5

https://github.com/user-attachments/assets/9ee0a0dc-ddf3-4515-b0ce-bd134cab41b6

### RiMusic version

6.55

### Android version

android 13

**Comment by woskkdmsosid** [comment]
heres the error video

https://github.com/user-attachments/assets/53e295c3-68a1-4d8b-8807-5797828eabfb

**Comment by fast4x** [comment]
This is not the video but the audio version of video...
Enable video and play with video button on player action bar
