### ISSUE TITLE
Show hours listened to a song

### ISSUE THREAD

**Issue by mariuslohoho** [fast4x/RiMusic#3918]
### Description

In vi music you can see the hours listened on a song, but I cannot find it in rimusic
![Screenshot_20241010_201013](https://github.com/user-attachments/assets/ca643318-825a-4ecb-92b7-75f9be1368d2)

### Suggested Solution

please add the option to show hours listened in the statistics page

**Comment by fast4x** [comment]
You can found in songs page, look video...

https://github.com/user-attachments/assets/39efe09a-eedc-4e1f-9542-e298dde7a150

**Comment by aneesh1122** [comment]
> You can found in songs page, look video...
> 
> https://github.com/user-attachments/assets/39efe09a-eedc-4e1f-9542-e298dde7a150
> 
> 

He wants to see the total listened hours of each song.

**Comment by fast4x** [comment]
> > You can found in songs page, look video...
> > 
> > https://github.com/user-attachments/assets/39efe09a-eedc-4e1f-9542-e298dde7a150
> > 
> > 
> 
> He wants to see the total listened hours of each song.

Him said...
_In vi music you can see the hours listened on a song, but I cannot find it in rimusic_

**Comment by mariuslohoho** [comment]
Thank you, i apologise for my ignorance
