### ISSUE TITLE
Text turns grey

### ISSUE THREAD

**Issue by Shmoon1111** [fast4x/RiMusic#3919]
### Steps to reproduce the bug

Open the app.

### Expected behavior

Text should be to what color I put to

### Actual behavior

Turns grey. Everytime I open the app after closing it the text becomes grey instead of the white that i have to put it back to white everytime i open the app so i can actually see the text since the app is already in a dark grey color close to black.

### Screenshots/Screen recordings

![Screenshot_20241001_170957](https://github.com/user-attachments/assets/b0bda2dc-a196-4de5-899c-7eb096cca26d)

### RiMusic version

0.6.54.1 latest

### Android version

Android 14

### Additional information

.

**Comment by fast4x** [comment]
Resync album and update to latest version
