### ISSUE TITLE
When playing all the songs of an artist it only plays 9 songs and plays back to the beginning, in some artists it only plays 5 songs and plays again from the beginning.

### ISSUE THREAD

**Issue by Yordi10000** [fast4x/RiMusic#3923]
### Steps to reproduce the bug

![Screenshot_2024-10-11-10-24-58-269_it fast4x rimusic](https://github.com/user-attachments/assets/c315e8bd-7048-482b-816f-9c38743f7a8c)
![Screenshot_2024-10-11-10-24-42-158_it fast4x rimusic](https://github.com/user-attachments/assets/58b9a389-6b00-4b73-bab5-3eba733ad578)
![Screenshot_2024-10-11-10-24-33-155_it fast4x rimusic](https://github.com/user-attachments/assets/e0d298fd-f6d1-425e-ad94-b2cb531c1d12)

### Expected behavior

It should play all the songs by an artist and not just play a few and go back to the beginning.

### Actual behavior

play 5 or 9 songs and go back to the beginning

### RiMusic version

0.6.55

### Android version

14

**Comment by fast4x** [comment]
Check if you have repeat enabled...

**Comment by Yordi10000** [comment]
No tengo habilitada la repetición
