### ISSUE TITLE
App crashes directly

### ISSUE THREAD

**Issue by woskkdmsosid** [fast4x/RiMusic#3924]
### Steps to reproduce the bug

Enter app
Play music or open settings
App crashes

### Expected behavior

Play music or open settings 

### Actual behavior

App crashed

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/f0a59505-9a76-4662-988c-8badd9846a4f

### RiMusic version

6.56 (custom version)

### Android version

android 13

**Comment by fast4x** [comment]
Do not report bugs on the debug version
