### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by DavidDiaz377** [fast4x/RiMusic#3925]
### Steps to reproduce the bug

The app crashes when I open it. I've been using v0.6.55 for a while now, but this problem started yesterday and still persists.

### Expected behavior

That it does not close when opening the application.

### Actual behavior

The application crashes instantly upon opening it.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/fa05c3e2-3c79-46f0-85a3-2bd879fab0f8

### Logs

I can't copy the logs, because it crashes as shown in the video

### RiMusic version

v0.6.55

### Android version

Android 14

### Additional information

After several days of working correctly, it started to fail and I still don't know how to fix the fault.

**Comment by fast4x** [comment]
wait new release, remove and reinstall
