### ISSUE TITLE
All explicit songs play except "We Are Fucking Fucked" by Muse

### ISSUE THREAD

**Issue by HeyHeyHeyStockpile** [fast4x/RiMusic#3926]
### Steps to reproduce the bug

1. Search for "We Are Fucking Fucked"
2. Click the song

### Expected behavior

The song starts playing, just like other songs, including explicit ones, such as "Shame" by System Of A Down and Wu-Tang Clan

### Actual behavior

Error: This song cannot be played due to server restrictions

### RiMusic version

0.6.55

### Android version

Android 11

**Comment by woskkdmsosid** [comment]
tested and it happens

**Comment by fast4x** [comment]
Isn't an app bug, but restriction by YTM

**Comment by HeyHeyHeyStockpile** [comment]
Actually Shame is somehow not rated Explicit, but Psycho, also by Muse, does play.
