### ISSUE TITLE
[Feature] Improve App Logo

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#393]
<details><summary>
<s><b>- Resolution improvement</b></summary>
<ul>Current 130×130 looks too blurry even though my phone has low resolution too
If possible, use SVG
Alternatively, use higher resolution PNG (even ViMusic use 512×512 icon)
</ul></s></details>

- **Adjust padding on Light themed Icon**
<ul>No wonder it looks wierd for me, blurry logo
<br>My suggestion is to add a bit of drop shadow on Light themed icon, so the logo can popup a bit more</br>
A Gradient Icon like <a href="https://icon.kitchen/i/H4sIAAAAAAAAA1WQQYvCMBCF%2F8vstQt213WxVxFPgqA38TBNJtNg2kgaFSn9704iil7CzCPvfS8Z4ILuTD1UA2gMx11DLUFl0PVUgOHd7SQr2BaZoICaF975IMrX1KjyX4lmeI398c2zVehsx3JJURcpZN%2B2wZykbFAuRcVE0i9b%2FURxQG3Fl12r5yL1VCKXH%2Bgs%2FSRp9kvT%2BZ9I2LHEV9%2BzyZi6LI0hFeV5QI4uGBPZ8Aa1zg0HiP4EVTkpIFhuhJPG2sfo28fsyGR1lLjW67NLf7UXjA7eakmzvpfzSjUcxjuPxsn8TgEAAA%3D%3D">this one</a> would be good too</ul>
<ul><table><thead>
<tr><th>mimmap-hdpi</th>
<th>ic_launcher</th>
<th>ic_logo</th></tr></thead>

<tbody><tr><td>square</td>
<td><img src="https://raw.githubusercontent.com/fast4x/RiMusic/master/app/src/main/res/mipmap-hdpi/ic_launcher.webp"></img></td>
<td><img src="https://raw.githubusercontent.com/fast4x/RiMusic/master/app/src/main/res/mipmap-hdpi/ic_logo.webp"></img></td></tr>

<tr><td>rounded</td>
<td><img src="https://raw.githubusercontent.com/fast4x/RiMusic/master/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp"></td>
<td><img src="https://raw.githubusercontent.com/fast4x/RiMusic/master/app/src/main/res/mipmap-hdpi/ic_logo_round.webp"></td>
</tr></tbody></table></ul>

- **Adaptive Icon**
Customizable dark background color
Customizable Light background color

**Comment by ikanakova** [comment]
We have the logo in svg (https://github.com/fast4x/RiMusic/assets/design), but it probably needs to be fixed in the application somehow.

**Comment by faustaahmad** [comment]
ViMusic used 512×512 PNG icon, idk how they do it
But it seems like it wont be able to support adaptive icon

**Comment by fast4x** [comment]
I'll check

**Comment by fast4x** [comment]
> We have the logo in svg (https://github.com/fast4x/RiMusic/tree/master/assets/design), but it probably needs to be fixed in the application somehow.

 but it probably needs to be fixed in the application somehow.

**Comment by faustaahmad** [comment]
Updated description, sorry for the confusion
It shouldn't be a resolution problem, but rather style & padding issue that make the Light version of the icon looks wierd (atleast for me)
While the dark/black one are much better

**Comment by ikanakova** [comment]
I'll look into it and try to make a thicker version while keeping the icon design.

**Comment by ikanakova** [comment]
I made the outline of the icon more massive:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/60eb9599-cf26-421e-bea9-e45a7a35cf01" width="50">
The icon is made according to the Adaptive icons manual (see #160), so shadows cannot be used, they probably depend on the system settings.

**Comment by ikanakova** [comment]
> Customizable dark background color
> Customizable Light background color

The background can probably be optional. Icons in SVG have transparent backgrounds, but I'm not sure how to program that in Android.

**Comment by faustaahmad** [comment]
> I made the outline of the icon more massive

I mean the white logo are too close to the border, need a bit more padding/space to match dark version of app icon (both circle & square of light version)

> The background can probably be optional. Icons in SVG have transparent backgrounds, but I'm not sure how to program that in Android.

I know very little about programming, but some app can have dynamic background icon or even with color picker.
simplest version was dark/light themed icon which this app already have, but only light mode enabled by default
![Screenshot_20240118-214419_Kvaesitso](https://github.com/fast4x/RiMusic/assets/45221211/7e5a3ee6-c470-4acb-80ea-5f3eaa80a983)
Not a fan of Light icon & the dark version on my launcher are green, instead of dark (Padding on the logo looks similar to dark mode version)

**Comment by fast4x** [comment]
@ikanakova This seems to be done

**Comment by fast4x** [comment]
Implemented, available from version 0.6.19
