### ISSUE TITLE
The app closes when playing or doing absolutely nothing

### ISSUE THREAD

**Issue by Kou-tester** [fast4x/RiMusic#3933]
### Steps to reproduce the bug

1. I go into the application 2. I press the button to play 3. it closes 4. Also it happens if I just leave the screen still, it closes automatically 

### Expected behavior

the app closes by itself 

### Actual behavior

I can't even play songs

### RiMusic version

0.6.56

### Android version

Android 14

**Comment by twistios** [comment]
The issue probably gets fixed by reinstalling the app, so do that if you can.

**Comment by fast4x** [comment]
try enable debug before play a song and after crash send here crash log

**Comment by twistios** [comment]
It seems that fast4x found the problem (if it is the same for everyone). He will probably fix it tomorrow.

**Comment by fast4x** [comment]
Download custom version please https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Kou-tester** [comment]
> try enable debug before play a song and after crash send here crash log
I can't enter to settings to enable the debug

**Comment by fast4x** [comment]
download custom version please linked here
