### ISSUE TITLE
Downloads don't work properly

### ISSUE THREAD

**Issue by Yurisouza30** [fast4x/RiMusic#3935]
### Steps to reproduce the bug

1. Go to music then favorites
2. Click download all and confirm

### Expected behavior

It should download all of the songs in your favorites.

### Actual behavior

It only downloads a few songs then stops, and if you click in download all again, the downloaded list clears (deletes all downloaded songs on it's own).

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/de55a503-384a-4c83-8cf8-47cfc0f85a20

### RiMusic version

0.6.56

### Android version

Android 13

**Comment by Jacoblightning** [comment]
I was experiencing this bug with the last version. I ended up downloading every song manually.

**Comment by Pope-23** [comment]
Similar when downloading all songs in playlists.

**Comment by Yurisouza30** [comment]
> I was experiencing this bug with the last version. I ended up downloading every song manually.

Even manually downloading one by one doesn't work for me

**Comment by Anonymous-forreal** [comment]
This is also an issue for me and another issue i experience is that the app also freezes when i click download all so i have to close app . When i go back to it, the songs won't be downloaded.

**Comment by Anonymous-forreal** [comment]
Even manually downloading doesn't work for me now

**Comment by markndennis** [comment]
Me too can't download all favorites and even some individual doesn't work

**Comment by markndennis** [comment]
Thank you for prompt attention to this.

**Comment by fast4x** [comment]
You're welcome
