### ISSUE TITLE
Tiny Bugs

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#3937]
### Steps to reproduce the bug

~~Bug 1: Seekbar Freezing~~
~~- Play a song.~~
~~- Tap on the seekbar.~~
~~- The current time freezes.~~

**Bug 2: Double Tap to Go Back**
- Go to Settings.
- Tap the back button.
- It takes two taps to go back.

**Bug 3: Persistent Back Button**
- Go to Settings.
- Use the back gesture.
- The back button at the top left doesn't disappear.

**Bug 4: Playback with no audio** (happens sometimes)
- Play a song.
- Listen with the screen closed.
- Skip a song using my earbuds or volume controls (not Rimusic Ones).
- No audio is heard, and I need to activate the screen to hear it.

~~Bug 5: Fluid background doesn't change colors~~
~~- Play a song with Dynamic effects and~~ ~~Theme or Album Color Fluid Background.~~
~~- Background has the wrong color.~~

**Bug 6 (not really?): << button plays song when paused**
- Play a song and pause.
- Press <<.
- Song Replays.

### Expected behavior

~~Bug 1:~~
~~- The current time should display correctly and not freeze.~~

**Bug 2:**
- One press only on the button should take you back.

**Bug 3:**
- The back button should disappear if we go back with the gesture.

Bug 4:
- Audio should be heard with the app in background and the screen closed.

~~Bug 5:~~
~~- Theme and Album Color Fluid~~ ~~Background should refresh the colors on every song.~~

**Bug 6:**
- Song should replay only when not paused.

### Actual behavior

~~Bug 1:~~
~~- The current time stops updating.~~

**Bug 2:**
- The button requires two presses to register.

**Bug 3:**
- The back button does not disappear when returning with the gesture.

**Bug 4:**
- Song plays with no audio until the screen is on.

~~Bug 5:~~
~~- Theme and Album Color Fluid~~ ~~Background has the wrong color.~~

**Bug 6:**
- Song replays even when paused.

### Screenshots/Screen recordings

**Bug 1:**
https://github.com/user-attachments/assets/fdf260c5-f1aa-4313-bfaa-65120247be41

**Bug 2:**
https://github.com/user-attachments/assets/c4d8d716-5111-402e-a08c-02661bd187a2

**Bug 3:**
https://github.com/user-attachments/assets/960b7a28-0dac-4a31-875e-d584138a99ed

**Bug 4:**
Can't record

**Bug 5:**
https://github.com/user-attachments/assets/61ae8fec-32a9-4fcf-be78-d652bd97c284

**Bug 6:**
https://github.com/user-attachments/assets/84135c47-5ed7-45b9-b626-b68e6808efe3

### RiMusic version

0.5.56

### Android version

Android 14

**Comment by knighthat** [comment]
what phone were you using at the time of recording?

**Comment by OrangeZXZ** [comment]
> what phone were you using at the time of recording?

Samsung Galaxy S22 Ultra

**Comment by knighthat** [comment]
Thanks

**Comment by fast4x** [comment]
These bugs still present?

**Comment by OrangeZXZ** [comment]
> These bugs still present?

Yes and there are new ones too i should make a new issue

**Comment by knighthat** [comment]
You can edit the post, it's not closed yet

**Comment by OrangeZXZ** [comment]
> You can edit the post, it's not closed yet

Updated it; added two bugs, and one isn't really a bug—or maybe it is?

**Comment by knighthat** [comment]
> Bug 4: Playback with no audio

Update the song, this happened on 0.5.59. Segments of song without audio are saved to cache, that's why it remains after update.

> Bug 6 (not really?): << button plays song when paused

Shouldn't the song starts playing when you forward, backward, restart it? I thought keeping the song paused after that kinda annoying because I have to press play again

**Comment by OrangeZXZ** [comment]
> Shouldn't the song starts playing when you forward, backward, restart it? I thought keeping the song paused after that kinda annoying because I have to press play again

Imo, every button has a purpose, and it is strange to say that the rewind button also plays.
Also, on cassettes, the rewind function didn't play back. (and we often compare things to irl objects)
I often rewind the song before closing it (as a reflex), but it starts the song back, and it is a bit annoying. (maybe just add an option to disable playing after song skip or rewind if paused)

**Comment by knighthat** [comment]
> Imo, every button has a purpose, and it is strange to say that the rewind button also plays.

I often use RiMusic while driving so having to press as least button as possible is preferable. It's just a personal opinion

> maybe just add an option to disable playing after song skip or rewind if paused

Yea, I'll see if I can add an option to the setting,

**Comment by OrangeZXZ** [comment]
Bugs 1 and 2 have been patched in 0.6.61

**Comment by OrangeZXZ** [comment]
> Bugs 1 and 2 have been patched in 0.6.61

Bug 5 is also better but can maybe be improved.

**Comment by OrangeZXZ** [comment]
> Bugs 1 and 2 have been patched in 0.6.61.

Bug 2 just came back, but it happens less often.

**Comment by knighthat** [comment]
Hi, can you update the post to reflect what's still happening? 

Bug no. 2 maybe because you tap it too fast. Please allow it some time to process

**Comment by OrangeZXZ** [comment]
> Hi, can you update the post to reflect what's still happening? 
> 
> Bug no. 2 maybe because you tap it too fast. Please allow it some time to process

done
