### ISSUE TITLE
Crash while opening settings 

### ISSUE THREAD

**Issue by anoojjo** [fast4x/RiMusic#3939]
### Steps to reproduce the bug

Click Settings 

### Expected behavior

Should open ' Settings '

### Actual behavior

App just keeps crashing 

### RiMusic version

0.6.56

### Android version

Android 14

**Comment by wunder20v** [comment]
The same for me

**Comment by fast4x** [comment]
Download custom version please https://github.com/fast4x/RiMusic/tree/master/customVersion
