### ISSUE TITLE
Wrong language selected

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#394]
### Steps to reproduce the bug

.

### Expected behavior

If I put french it put french Emojies if It put system language it also put french Emojies instead of french without Emojies 

### Actual behavior

Should select the good language

### Screenshots/Screen recordings

![Screenshot_2024-01-13-12-09-33-318_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/f9fe7fa1-a6fe-4b02-b568-a497c88c91bc)
![Screenshot_2024-01-13-12-09-28-826_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/1bc29f14-acac-439b-9a82-cd436293ef45)
![Screenshot_2024-01-13-12-09-24-197_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/ed063a88-8fae-4750-aac8-12cfc898fea7)

### RiMusic version

0.6.17

### Android version

A12 MIUI 14

**Comment by fast4x** [comment]
ok then there is the same bug that the Romanian had

**Comment by fast4x** [comment]
Fixed, available from version 0.6.18
