### ISSUE TITLE
Always AMOLED + Idea for Themes

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#3940]
### Description

When using the Dynamic theme with Pitch Black colors, the dark background is only used after playing a song (not after opening the app). This also happens when the album art is not loaded.

### Suggested Solution

Make the background always dark, even when not playing a song or if the artwork is missing.

### Alternatives

I think that Dynamic mode and pitch black could be separated as a checkbox that applies to any theme and color.
That way we can have, as an example:
Material You + Pitch Black + Dynamic colors

We can see this as layers:
Layer 3: Dynamic colors (contain only accent colors)
Layer 2: Pitch Black (contains only background colors)
Layer 1: Material You (contains all the colors)

If this is correctly integrated, the settings should look like this:
Theme
- Default
- Material You
- Customized

Theme Mode
- Light
- Dark (Default Dark but can be overlapped by pitch black)
- System

Pitch Black □ (Disabled when Light is used but keeps its state that way System works)

Dynamic Colors □ (overlaps Material You, Customized colors, or Rimusic Colors)

### Additional Context

![SmartSelect_20241012_025613](https://github.com/user-attachments/assets/a2a3f667-8eac-4463-b1cc-9a36cc107ada)

**Comment by fast4x** [comment]
Colors was improved, available from version 0.6.61
