### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by JavierProxy** [fast4x/RiMusic#3941]
### Steps to reproduce the bug

Click on the three bars at the top right corner and then on settings/click on the song currently playing or click on whatever song

### Expected behavior

Opening the settings / opening the song player

### Actual behavior

The app crashes

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/d6d28364-0f8a-495b-b853-8185bc6fcd50

https://github.com/user-attachments/assets/1d8240b3-f7a1-436d-907b-a406dcc31cf3

### Logs

I can't open settings

### RiMusic version

0.6.56

### Android version

Android 14

### Additional information

The app can still play music, but only if the song player doesnt open or in the app notifications

**Comment by hle-cer** [comment]
yup same here

**Comment by fast4x** [comment]
Download custom version please https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by drago-bit** [comment]
Same for me as well. Will try the custom version and update.

**Comment by JavierProxy** [comment]
> Download custom version please https://github.com/fast4x/RiMusic/tree/master/customVersion

thanks, it worked for me
