### ISSUE TITLE
No anda la app 😭

### ISSUE THREAD

**Issue by Victor332lop** [fast4x/RiMusic#3942]
### Steps to reproduce the bug

Lo que pasa es que se me sale la app poner la música o hacer algo 😭

### Expected behavior

Debe andar normal la app 😕 

### Actual behavior

Se sale la app al entrar a una música o a los ajustes de la app

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/1d7b462e-d655-4f5b-aa31-312ebabb2f65

### Logs

.

### RiMusic version

La última 0.5.56;o algo así (perdón me olvidé 😞)

### Android version

Android 10 💚💚

### Additional information

Solo quiero que ya ande, no quiero se borren mis playlist 😞( es mi app favorita)

**Comment by B7712** [comment]
Aquí también me está pasando lo mismo. 😔

Android 13

**Comment by B7712** [comment]
Leí un poco con la traducción de Google, y probablemente lo arreglen mañana o en 2 días. Lo bueno es que a muchos les está pasando lo mismo y esto ayuda a que los desarrolladores lo arreglen. 
Así que toca que ser paciente.

**Comment by fast4x** [comment]
Download custom version please https://github.com/fast4x/RiMusic/tree/master/customVersion
