### ISSUE TITLE
Actualizar automáticamente 

### ISSUE THREAD

**Issue by Noeliiarp26** [fast4x/RiMusic#3943]
### Description

Porfavor que se actualice la app sola. Es horrible estar actualizandola cada semana o así. Es realmente necesario.

### Suggested Solution

R

### Alternatives

G

**Comment by woskkdmsosid** [comment]
En Ajustes y Misceláneo hay un ajuste para comprobar actualizaciónes disponibles, te lo recomiendo activar

**Comment by Noeliiarp26** [comment]
Lo tengo activado graciasss
