### ISSUE TITLE
No me deja entrar a la app, dice que la aplicación se a detenido, pero con la versión anterior si corre correctamente, pdta el nuevo logo está cool!!

### ISSUE THREAD

**Issue by JEncidso** [fast4x/RiMusic#3945]
### Steps to reproduce the bug

Instalé la nueva versión .56 
Entré a la app 
No me deja entrar 
Se detiene al apo

### Expected behavior

Debería de entrar correctamente 

### Actual behavior

Esto ocurrió en vez de entrar con normalidad a la app

### RiMusic version

0.6.56

### Android version

Android 6

**Comment by fast4x** [comment]
Download custom version please https://github.com/fast4x/RiMusic/tree/master/customVersion
