### ISSUE TITLE
No me deja entrar a la aplicación

### ISSUE THREAD

**Issue by efrainveg** [fast4x/RiMusic#3949]
### Steps to reproduce the bug

1. Al ingresar a la app y seleccionar una música para escuchar la aplicación se cierra automáticamente, también pasa al intentar ingresar en los ajustes. No hay manera de usar la app y poder escuchar música.

Nota: el nuevo logo está lindo

### Expected behavior

Al colocar una música deberia reproducirse sin ningún problema 

### Actual behavior

Lo que ocurre en lugar de reproducirse la canción es que la app se cierra 

### RiMusic version

0.6.56

### Android version

Android 14

**Comment by fast4x** [comment]
Download custom version please https://github.com/fast4x/RiMusic/tree/master/customVersion
