### ISSUE TITLE
[Feature]: Themed app icon

### ISSUE THREAD

**Issue by rusty-snake** [fast4x/RiMusic#3950]
### Description

Support for themed app icons on Android 13+.

### Suggested Solution

Support for themed app icons on Android 13+.

### Alternatives

N/A

### Additional Context

I'm not sure if RiMusic supported it in the past or if the old icon just had less divergating colors but after the last update (0.6.56) I noticed a green blob.

**Comment by fast4x** [comment]
Try custom version https://github.com/fast4x/RiMusic/tree/master/customVersion
