### ISSUE TITLE
The repeat button doesn't stay turned on when you click on other song

### ISSUE THREAD

**Issue by Frozi334** [fast4x/RiMusic#3952]
### Steps to reproduce the bug

1. Click on a song
2. Exit the song page and click on other song

### Expected behavior

When you click on the other song from your list, the repeat button suppose to be turned on.

### Actual behavior

When you click on the other song from your list, the repeat button is turned off.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/5e2d023f-5682-4b13-9d2d-08683eebe990

### Logs

No available logs

### RiMusic version

0.6.56

### Android version

Android 13

**Comment by fast4x** [comment]
Fixed, available from version 0.6.63
