### ISSUE TITLE
Las canciones no descargan 

### ISSUE THREAD

**Issue by Ghuste** [fast4x/RiMusic#3954]
### Steps to reproduce the bug

1.Al descargar la nueva actualización, no me dejaba reproducir ninguna canción, y eso que estaban descargadas. Me tocó desinstalar la aplicación, la volví a instalar en apk, al instalar la aplicación le presione al botón de descargar todas las canciones y algunas descargaron, pero algunas se quedaron sin descargar, pensé que era mi internet pero intenté descargar otras canciones y si se podia, 

### Expected behavior

Cuando presione el botón de descargar todo se descarguen todas las canciones 

### Actual behavior

No sé descargan, además por ese error no se dejan descargar las demás canciones 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/8e2d1a02-4999-43df-932a-327aa3fdea1f

### RiMusic version

V0.6.56

### Android version

Android 13

### Additional information

Gracias por la app, espero que lo arreglen gracias 🫂

**Comment by fast4x** [comment]
But it play?
