### ISSUE TITLE
I cant either open the player or the options

### ISSUE THREAD

**Issue by Jcarz100204** [fast4x/RiMusic#3955]
### Steps to reproduce the bug

I cant open the music player or open the configurations

### Expected behavior

It shoul open normal ig

### Actual behavior

It crahsed

### RiMusic version

The newer

### Android version

Android 14

**Comment by NOBELLIST** [comment]
There should be a custtom version that has them fixed, i have it but i forgor the link, you should find the link through on of the older bug reports

**Comment by fast4x** [comment]
Here custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by StraggleCraft** [comment]
Custom version does not fix my issue
![Screenshot_20241012_145107](https://github.com/user-attachments/assets/ed8592f1-a5a0-4894-8045-d4b706672995)

**Comment by fast4x** [comment]
Reinstall

**Comment by Jcarz100204** [comment]
I cant download the custom version💀

**Comment by fast4x** [comment]
there is new version, download 0.6.56.1

**Comment by Jcarz100204** [comment]
Where?

**Comment by fast4x** [comment]
Here
https://t.me/rimusic_app

**Comment by Jcarz100204** [comment]
Thank bro, its alright now
