### ISSUE TITLE
Xd

### ISSUE THREAD

**Issue by dxsker** [fast4x/RiMusic#3956]
### Steps to reproduce the bug

al querer abrir los ajustes de la aplicación se cierra, desde q lo actualice está pasando esto 

### Expected behavior

deberes abrir la configuración 

### Actual behavior

me crashear la aplicación 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/70d0052e-40ad-40e6-b4b9-4f280a48ba74

### RiMusic version

0.6.56

### Android version

Android 12

**Comment by NOBELLIST** [comment]
[there is an custom version that fast4x linked in the older bug report about the same damned topic. Please atleast find them. No, i wont type in your language. And how wide is your phone or the recored is fucked?]

**Comment by dxsker** [comment]
@NOBELLIST Sorry, I'm new to the platform and I didn't check all the devices, and thanks for the information.
