### ISSUE TITLE
ramdomization in artists tab

### ISSUE THREAD

**Issue by Najib314** [fast4x/RiMusic#3958]
### Steps to reproduce the bug

the random button added in the artists tab is a very great feature, this i now the only way i listen music

Unfortunately, it seems that the algorythm randomizes only the 8 or 10 first artists in alphabetic order, and never goes to the others.

For people like me who have more artists (110 in my case), it is unfortunate, and remove a part of the amazing added value of this feature

the algorythm shouls add let's say 1 to 5 songs to the queue for all the followed artists, which would make it much more enjoyable

### Expected behavior

randomize all the followed artists in a row

### Actual behavior

randomize only the first followed artists in alphabetic order

### RiMusic version

0.6.56

### Android version

android 14

**Comment by knighthat** [comment]
Thanks for reporting, I might know where the bug is. Will push a bug in a few hours

**Comment by Najib314** [comment]
Thank you very much !!!!!
