### ISSUE TITLE
Crashes everywhere in the newest version

### ISSUE THREAD

**Issue by Tophatcatt** [fast4x/RiMusic#3961]
### Steps to reproduce the bug

Do anything.

### Expected behavior

It does something.

### Actual behavior

It crashes

### RiMusic version

0.6.56

### Android version

Android 11

**Comment by knighthat** [comment]
Did you remove old version before installing new one?

**Comment by Tophatcatt** [comment]
> Did you remove old version before installing new one?

No. Would that have changed anything?

**Comment by bellatrix-8** [comment]
https://github.com/user-attachments/assets/193d756b-d013-4c47-be55-0016b8400a4e

**Comment by knighthat** [comment]
> > Did you remove old version before installing new one?
> 
> No. Would that have changed anything?

Most of the time, yes.

**Comment by fast4x** [comment]
Download custom version https://github.com/fast4x/RiMusic/tree/master/customVersion
