### ISSUE TITLE
Falla en el apartado "lista de reproducción"

### ISSUE THREAD

**Issue by DavidDiaz377** [fast4x/RiMusic#3963]
### Steps to reproduce the bug

Open the app and go to playlists

### Expected behavior

It should not be closed, allowing the user to enjoy them.

### Actual behavior

It closes when entering the section.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/51dd6571-fe00-4040-873a-94e272b4eb43

### Logs

2024-10-12T15:55:00.092:	java.lang.NullPointerException: c.getString(index) must not be null
	 f4.e.k(SourceFile:17) 
	 C7.l.b(SourceFile:1519) 
	 i4.h.r(SourceFile:208) 
	 i4.h.h(SourceFile:13) 
	 f4.b.a(SourceFile:9) 
	 c4.C.q(SourceFile:9) 
	 i4.e.r(SourceFile:44) 
	 B8.a.g(SourceFile:9) 
	 V8.N.run(SourceFile:107) 
	 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	 java.lang.Thread.run(Thread.java:1012) 

2024-10-12T16:04:11.116:	java.lang.NullPointerException: c.getString(index) must not be null
	 f4.e.k(SourceFile:17) 
	 C7.l.b(SourceFile:1519) 
	 i4.h.r(SourceFile:208) 
	 i4.h.h(SourceFile:13) 
	 f4.b.a(SourceFile:9) 
	 c4.C.q(SourceFile:9) 
	 i4.e.r(SourceFile:44) 
	 B8.a.g(SourceFile:9) 
	 V8.N.run(SourceFile:107) 
	 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	 java.lang.Thread.run(Thread.java:1012) 

### RiMusic version

v.0.6. 56 & v.0.6. 56 Custom

### Android version

Android 14

### Additional information

In v0.6.56, it is not possible to play music or access settings, in addition to the bug mentioned in this report. In the custom version, it is possible to play music and there is no crash when opening settings.

**Comment by fast4x** [comment]
you have a troubled playlist inside database, uninstall and reinstall
