### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by KaivanM2008** [fast4x/RiMusic#3964]
### Steps to reproduce the bug

Play any song on the RiMusic app or try to open settings

### Expected behavior

It should play songs / open settings as per your action

### Actual behavior

App crashes when you try to play song or open settings (device : galaxy A34 5G)

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/a1216b67-c9dc-4eec-8f0a-f2851ba1560a

### RiMusic version

0.6.56

### Android version

Android 14

**Comment by Mai1839** [comment]
After the last update the app keeps crashing when I try to open the settings or play a song

**Comment by bellatrix-8** [comment]
No crashes on clean install but my favorites list is gone.

**Comment by fast4x** [comment]
Download custom version https://github.com/fast4x/RiMusic/tree/master/customVersion
