### ISSUE TITLE
Search button overlaps with mini player

### ISSUE THREAD

**Issue by mariuslohoho** [fast4x/RiMusic#3966]
### Steps to reproduce the bug

Home screen

### Expected behavior

Search button further up

### Actual behavior

![Screenshot_20241012_204251](https://github.com/user-attachments/assets/2b0760c4-6d5c-4b1a-8e3f-ab4ee1e40e42)

### RiMusic version

0.65

### Android version

Android 14

**Comment by fast4x** [comment]
long press on it and move where you want
