### ISSUE TITLE
v0.6.56 crashes on Android v7.1.2 again

### ISSUE THREAD

**Issue by pi99y** [fast4x/RiMusic#3967]
### Steps to reproduce the bug

Just try to open the app on Android v7.1.2

### Expected behavior

Should not crash.

### Actual behavior

It crashes immediately when you press the app icon, no UI is ever visible, just crash "Stopped working".

### RiMusic version

v0.6.56

### Android version

Android v7.1.2

### Additional information

* I opened #2243 a while ago when the app started crashing on Android v7.1.2
* A few versions back (around v0.6.50) it started working again. YAY!
* Version 0.6.55 is the last working version
* v0.6.56 started crashing again

Something in 0.6.56 is breaking the Android 7.1.2 compatibility. Please try to pinpoint the problem, as this was already once fixed around version 0.6.50 (maybe a version or two before).

**Comment by knighthat** [comment]
Hi, did you uninstall old version before installing new one?

**Comment by fast4x** [comment]
Download custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by pi99y** [comment]
> Hi, did you uninstall old version before installing new one?

No, I just updated. Uninstalling would mean loosing my favorites & settings etc...

**Comment by pi99y** [comment]
> Download custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

404: Not Found

**Comment by knighthat** [comment]
> No, I just updated. Uninstalling would mean loosing my favorites & settings etc...

Unfortunately, that's the risk of using custom versions (unofficial releases). 

Unless you have special tool that can extract database from the app without opening it, I don't think you can recover your data.

You can try installing previous custom version that work.

Or from now on, please backup  your database frequently, once a week because that's our automated build schedule

**Comment by fast4x** [comment]
download latest release

**Comment by pi99y** [comment]
@fast4x Unfortunately v0.6.56.1 still crashes on Android v7.1.2 in the same way. I cleared app storage & cache after upgrading.

The last working version is v0.6.55.

**Comment by fast4x** [comment]
you have piped enabled?

**Comment by fast4x** [comment]
Send a screenshot of information page from your device

**Comment by pi99y** [comment]
@fast4x In v0.6.55 "enable piped sync." is OFF. v0.6.56.1 doesn't start so I assume there is the same.

![tablet_info_pt1](https://github.com/user-attachments/assets/45d4cbb5-efcc-4fe1-8b57-a9b85b3b691d)
![tablet_info_pt2](https://github.com/user-attachments/assets/4bb7c0b4-0c6b-46c1-a84f-d5600d9b6515)
(and there is no Android update available for my device)

**Comment by pi99y** [comment]
This was not fixed by the last version, please reopen @fast4x

**Comment by fast4x** [comment]
Try new latest release please

**Comment by pi99y** [comment]
@fast4x unfortunately v .57 crashes in the same way

**Comment by fast4x** [comment]
try latest 57.1

**Comment by knighthat** [comment]
@pi99y Hi! I know this one could be a lot to do but since your problem is so specific, we don't have enough data to pin point the problem, but can you use Android Studio with the debug version to give us access to the log

Please follow this instruction to build debug version of this app:

1. Download [Android Studio](https://developer.android.com/studio)
2. After installation, clone our project with 

```sh
git clone --depth 1 https://github.com/fast4x/RiMusic
```

3. Run Android Studio, select cloned repo as the project to start
4. Create a configuration (it's important to have everything setup like mine)

<details>
  <summary>How to create configuration</summary>
  
  ![Screenshot_20241021_120833](https://github.com/user-attachments/assets/82ca6047-3278-40d4-9073-e6676b21196a)
  
   ![Screenshot_20241021_120619](https://github.com/user-attachments/assets/ad926a77-c506-4851-bcac-a3cd7f2ca706)
  
  ![Screenshot_20241021_120634](https://github.com/user-attachments/assets/5c2266ad-6d8f-4192-99f9-3044c0b8d3f5)

  ![Screenshot_20241021_120653](https://github.com/user-attachments/assets/37bdfd2e-fb5f-411d-8f96-edc31ff90e60)

  ![Screenshot_20241021_120656](https://github.com/user-attachments/assets/a5bb096c-ce25-4849-b333-04f69f789abf)  
</details>

5. Connect your phone

> You need debug mode to be turned on on your phone. Please follow [this guide](https://developer.android.com/studio/debug/dev-options) for details

7. Enable logs

<details>
  <summary>How to enable logs</summary>
  
  Please pay attention to the selected device

  ![image](https://github.com/user-attachments/assets/c1fa6290-1e85-4759-aefd-65073583f724)

</details>

8. Run the app
9. Copy error from logs

> Once the is run and crashed, the log will spit out lots (and I mean a lot) of texts, please copy everything and paste it here. 

10. Upload it here

> Please use [Pastebin](https://pastebin.com/) or [markdown spoiler](https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287) to prevent log pollution

Thank you for doing this, it will help us have a more in-depth of the problem you're facing and hopefully we can fix it in the near future.

**Comment by pi99y** [comment]
I will report back. :hourglass_flowing_sand:

**Comment by pi99y** [comment]
Currently stuck on "connect your phone" step. You see my "phone" is an android SBC and the A.Studio is not detecting it. Maybe it's the cable... looking for replacement but I can't find another USB A to USB A in house... everything is USB C on one end.
I've connected android devices to computer through adb before, so I'm probably not failing there.
I'll need some more time...

**Comment by twistios** [comment]
Check if you can connect your phone with this cable for image transfer. If this works, then the cable is working.

**Comment by pi99y** [comment]
Connection through USB doesn't work even with a new cable I bought.
**I have however managed to connect through LAN via adb connect.** :fireworks: 

@knighthat @twistios 
What's unclear now is:
- do I install the debug apk on android device?
- when you say "run the app" does it mean on the android device or through AStudio with "run" icon?

**Comment by pi99y** [comment]
Yay! @knighthat 
https://pastebin.com/Z4cdy67D

the log is slightly longer since I ran the app twice, the second one was with "run Debug" config, the first time I'm not sure (that's why I re-run it)

Does this help you?

**Comment by fast4x** [comment]
Compliments to all

**Comment by pi99y** [comment]
So the new logo causes it to crash? :)

**Comment by knighthat** [comment]
Did you completely remove old version before installing the new one?

**Comment by fast4x** [comment]
> Did you completely remove old version before installing the new one?

I think that logo is missed or corrupted in mipmap legacy folder

**Comment by knighthat** [comment]
It is. But the problem seems like Android refused to install new assets when you update it. Sometimes uninstall and reinstall it fixes this problem

**Comment by pi99y** [comment]
@fast4x @knighthat Reporting that v.58.1 did not solve the issue

**Comment by fast4x** [comment]
yep i know,  thanks for feedback

**Comment by knighthat** [comment]
we have yet to find the root cause of this problem. Please be patient

**Comment by arthurlutz** [comment]
Using `adb logcat` I get the following error : 

```
11-06 08:53:43.028 10831 10831 W ResourceType: Failure getting entry for 0x7f0f0003 (t=14 e=3) (error -75)
11-06 08:53:43.029 10831 10831 D AndroidRuntime: Shutting down VM
11-06 08:53:43.032 10831 10831 E AndroidRuntime: FATAL EXCEPTION: main
11-06 08:53:43.032 10831 10831 E AndroidRuntime: Process: it.fast4x.rimusic, PID: 10831
11-06 08:53:43.032 10831 10831 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{it.fast4x.rimusic/it.fast4x.rimusic.MainActivity}: android.content.res.Resources$NotFoundException: Resource "it.fast4x.rimusic:mipmap/ic_logo" (7f0f0003) is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f0f0003 a=-1 r=0x7f0f0003}
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Resource "it.fast4x.rimusic:mipmap/ic_logo" (7f0f0003) is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f0f0003 a=-1 r=0x7f0f0003}
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2602)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:2540)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java:296)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.graphics.drawable.LayerDrawable.applyTheme(LayerDrawable.java:324)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:2549)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.content.res.Resources.getDrawable(Resources.java:806)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.content.Context.getDrawable(Context.java:458)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at B1.a.b(SourceFile:1)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at q.N0.g(SourceFile:237)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at k.z.q(SourceFile:55)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at k.z.z(SourceFile:17)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at k.z.e(SourceFile:8)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at k.h.a(SourceFile:21)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at androidx.activity.ComponentActivity.onCreate(SourceFile:33)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreate(SourceFile:1)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at it.fast4x.rimusic.MainActivity.onCreate(SourceFile:2)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6251)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
11-06 08:53:43.032 10831 10831 E AndroidRuntime: 	... 9 more
11-06 08:53:43.034   589  2556 W ActivityManager:   Force finishing activity it.fast4x.rimusic/.MainActivity
```

**Comment by arthurlutz** [comment]
If anyone else is having trouble downgrading to 0.6.55, you can downgrade using `adb install` with the following options : 

```
adb install -d -r ~/Downloads/app-foss-release.apk
```

(This gives me access to my playlists etc, but version 0.6.55, for me at least, cannot play any music, the error logs says https://pastebin.com/wvBubBXS but I'm not sure this should be reported as a new issue, if anyone thinks otherwise please tell me)

Looking forward to an upgrade that works on my device... And kudos to all people involved in the developement of RiMusic, thanks for all the fish.

**Comment by fast4x** [comment]
Maybe next version 0.6.59 solve this

**Comment by pi99y** [comment]
> Maybe next version 0.6.59 solve this

Unfortunately it does not, same behavior as before - crash before start.

**Comment by fast4x** [comment]
Maybe I've found a solution, in progress..

**Comment by pi99y** [comment]
> Maybe I've found a solution, in progress..

I've tested version 0.6.60 and sadly it still crashes. Hope you'll be able to find a fix.

Just out of curiosity... would reverting logo (for test purposes only) back to v0.6.50 solve the crash?

**Comment by arthurlutz** [comment]
Awesome ! Congrats ! Confirmed to be working on my device ! :tada:

**Comment by pi99y** [comment]
Indeed! Congratulations @fast4x and the team, working on Android 7 again! :clap:

**Comment by fast4x** [comment]
Thanks a lot to all.
