### ISSUE TITLE
0.6.56 immediately crashes

### ISSUE THREAD

**Issue by Dayvip** [fast4x/RiMusic#3968]
### Steps to reproduce the bug

Try to open any menu, song, option... The app immediately closes. My android version is 14

### Expected behavior

Open the desired menu, song... 

### Actual behavior

The app crashes and closes immediately

### RiMusic version

0.6.56

### Android version

14

**Comment by knighthat** [comment]
Did you uninstall old version before installing new one?

**Comment by Dayvip** [comment]
No, I just updated my app with the new version.

**Comment by fast4x** [comment]
try uninstall and install latest version

**Comment by Dayvip** [comment]
Now I have just done that with 0.6.56.1, and everything works fine. Thank you for your great work!

**Comment by fast4x** [comment]
wow thanks, amazing feedback.

**Comment by Dayvip** [comment]
Your welcome, continue like this, I love your app!!
