### ISSUE TITLE
Error after the Update 

### ISSUE THREAD

**Issue by JoshGMR** [fast4x/RiMusic#3969]
### Steps to reproduce the bug

After starting the app there is a chance that it will close for no reason, and when you start it and click on the mini player it will always close, also when I enter the settings section this happens.

### Expected behavior

The app should obviously not close. 

### Actual behavior

It closes for no apparent reason 

### Logs

I can't post the error logs because the app won't let me go into settings.

### RiMusic version

0.6.56

### Android version

10

**Comment by Nisselle** [comment]
Me pasa justamente el mismo error

**Comment by fast4x** [comment]
Download custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Nisselle** [comment]
Muchas gracias, ya lo descargue y me funciona bien
