### ISSUE TITLE
BUG on 0.6.56 - APP crashes when i click on miniplayer

### ISSUE THREAD

**Issue by JustCucho** [fast4x/RiMusic#3973]
### Steps to reproduce the bug

**1.** Run the _RiMusic_ application
**2.** Play _any song_
**3.** _Click_ on the _miniplayer_
**4.** The _app_ will _crash_

### Expected behavior

What should happen would be that the miniplayer is activated and you can see the cover of the song and the options to see the queue of next songs, the like button, the download option, video, loop, etc.

### Actual behavior

When you "click" on the miniplayer the app crashes, preventing you from accessing the miniplayer

### RiMusic version

0.6.56

### Android version

14

### Additional information

I installed the new version hours ago

**Comment by fast4x** [comment]
Download custom version https://github.com/fast4x/RiMusic/tree/master/customVersion
