### ISSUE TITLE
[Feature]: Small adjustment in Mini Player UI

### ISSUE THREAD

**Issue by coolswapnil** [fast4x/RiMusic#3974]
### Description

Can you please decrease space between Bottom navigation bar and Mini player to make of bit astetic.

At present there is big 
![IMG_20241013_121817](https://github.com/user-attachments/assets/2554858b-62cb-47c2-8f0b-06e5e22ac0df)
space between Navigation bar and Mini player which look bit weird.

### Suggested Solution

Decrease the space between Bottom navigation bar and Mini Player.

**Comment by fast4x** [comment]
yes

**Comment by fast4x** [comment]
Improved, available from version 0.6.56.1 today...
