### ISSUE TITLE
No Song Cover Gradient in the Player

### ISSUE THREAD

**Issue by Rit-y** [fast4x/RiMusic#3977]
### Description

![Screenshot_20241013_151530](https://github.com/user-attachments/assets/729fcbfa-3f7b-4360-9a47-1fea639316c6)
![Screenshot_20241013_151535](https://github.com/user-attachments/assets/1b5fb0f7-db26-4cdb-a82f-101dd8487d83)

As seen in the above screenshots, even when I've selected the background color to be gradient from the song cover, it doesn't show any.
The Theme is Material You and theme mode is  Pitch Black

### Suggested Solution

make the gradient thing available for my specific theme choices as well please

**Comment by NOBELLIST** [comment]
Try and restart the app. It does that for me and i just restarted it and it worked

**Comment by Rit-y** [comment]
It didn't for me :<

**Comment by Rit-y** [comment]
@fast4x still not been addressed

**Comment by fast4x** [comment]
Next version

**Comment by Rit-y** [comment]
> Next version

Man its still not working and on top of that 

![Screenshot_20241110_100731.jpg](https://github.com/user-attachments/assets/5afc9991-979f-4f52-bb49-522852a59d42)

![Screenshot_20241110_100717.jpg](https://github.com/user-attachments/assets/e49a3b4f-4539-460a-8b42-c72ebd38cc39)



This crap

**Comment by Rit-y** [comment]
@fast4x bruh

**Comment by Rit-y** [comment]
@fast4x I'm sorry for pestering you but all of the above mentioned problems still exist when you've explicitly stated that it'll be solved in the "next update" :/
