### ISSUE TITLE
Duplicate songs in some albums

### ISSUE THREAD

**Issue by hle-cer** [fast4x/RiMusic#3982]
### Steps to reproduce the bug

Click on an album (or sometimes you have to listen to the album for a while and then reopen it)

### Expected behavior

there should be no duplicate songs

### Actual behavior

some (or all) songs are duplicated

### Screenshots/Screen recordings

![Screenshot_20241013-160133](https://github.com/user-attachments/assets/55c91708-6526-4ac6-8a2f-9db15defcdd8)

### RiMusic version

0.6.56.1

### Android version

Android 14

**Comment by fast4x** [comment]
update album

**Comment by hle-cer** [comment]
right, and how do I update the whole album

**Comment by fast4x** [comment]
enter in album remove bookmark and bookmark again

**Comment by hle-cer** [comment]
alright, that worked thanks!

**Comment by fnr1r** [comment]
It didn't work for me. It'd be easier if there was an option for it (just like for songs), that way users won't have to mess with the DB to fix it.
