### ISSUE TITLE
Accounts.

### ISSUE THREAD

**Issue by Idksam77** [fast4x/RiMusic#3983]
### Description

I thought maybe you guys could add an account. Cause it would be much easier for me and probably many other people to switch from different devices. So I'm thinking of like adding like email phone number so you could sign into the account so it would save all the progress you have on the other device. So I wouldn't or we wouldn't have to search up. Or make a whole new playlist.

### Suggested Solution

Make an account feature Addi didn't like a phone number or like an email so you could sign in easily and it will save all the progress you have on that account so you can sign on other devices.

### Alternatives

Another way is maybe you guys could add a QR Code so you could scan it on the other device. So all the playlist history, everything on the settings are transferred to the other device.

### Additional Context

Some issues I have without the account feature that I'm talking about is it's really hard to figure out each song that I made a playlist of so I'm gonna have to make a playlist over again and like if I add another song to that playlist. I'm gonna have to figure out. What song it added

**Comment by pi99y** [comment]
... but such account feature should be optional please, I fully expect all my settings to be used locally unless explicitly stated.

**Comment by NOBELLIST** [comment]
Isnt backups a pseudo-account? A file that you can put on another phone to transfer each song and playlist, thaats how i got my 400+ list from vimusic to rimusic. If there was an account, make it have a guest feature so its a optional thing.

**Comment by fast4x** [comment]
Nothing will be developed related to account, only account possible is a piped account.
