### ISSUE TITLE
Artists tab defaults to bottom of list, not top

### ISSUE THREAD

**Issue by Juggalage** [fast4x/RiMusic#3984]
### Steps to reproduce the bug

Go to the artists tab

### Expected behavior

Should be defaulted to the top of the list

### Actual behavior

Actually starts at the bottom of the list

### Screenshots/Screen recordings

![Screenshot_20241013-103252](https://github.com/user-attachments/assets/94518f71-6953-4812-87a0-b517c04fadbc)

### RiMusic version

V0.6.56.1

### Android version

Android 14

### Additional information

The bug occurs whether you open the app or switch between tabs, even if you left the tab at the top of the list.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.59
