### ISSUE TITLE
song queue

### ISSUE THREAD

**Issue by Amethsyt1** [fast4x/RiMusic#3986]
### Steps to reproduce the bug

1: search up a song
2: play it
3: check the queue

### Expected behavior

previously when a song was searched up and played there would be 50 more songs in the queue

### Actual behavior

now when a song is searched up and pkayed there is only one song in the queue (the one that was searched up) 

### RiMusic version

0.6.56.1

### Android version

Android 10

**Comment by woskkdmsosid** [comment]
you might have went onto an album with only 1 song and that's why you only have 1 song

**Comment by Amethsyt1** [comment]
no i didn't go to the album, i went to the 'videos'  option

**Comment by Amethsyt1** [comment]
> you might have went onto an album with only 1 song and that's why you only have 1 song

no i didn't go to the album, i went to the 'videos' option

**Comment by github-jl14** [comment]
did you try the "start radio" on menu? well, thats a temporary solution if it will work for you. the devs might be busy tho

**Comment by Amethsyt1** [comment]
> ![Screenshot_20241014-003628.png](https://private-user-images.githubusercontent.com/118164738/376052177-5def34fe-a21f-4075-b24e-38722b925c30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NDExMjYsIm5iZiI6MTcyODg0MDgyNiwicGF0aCI6Ii8xMTgxNjQ3MzgvMzc2MDUyMTc3LTVkZWYzNGZlLWEyMWYtNDA3NS1iMjRlLTM4NzIyYjkyNWMzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxNzMzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2JlZjMwOTljNjFmOTNkMDRkY2NlYWM5ODZjZDQ4MjA4N2E4MGU1ZDFkNGE5NWJjMTA2MTE4NWNkN2FmMWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VpNGYZ6QIB7GlbeB5U-jA62EKDl-vheApS1Sq_mrYuk)
> 
> did you try the "start radio" on menu? well, thats a temporary solution if it will work for you. the devs might be busy tho
> 
> alternatively, you might wanna try the custom version coz so far, i have no bugs encountered there

i did that and now it works, thanks

**Comment by Amethsyt1** [comment]
> ![Screenshot_20241014-003628.png](https://private-user-images.githubusercontent.com/118164738/376052177-5def34fe-a21f-4075-b24e-38722b925c30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NDExMjYsIm5iZiI6MTcyODg0MDgyNiwicGF0aCI6Ii8xMTgxNjQ3MzgvMzc2MDUyMTc3LTVkZWYzNGZlLWEyMWYtNDA3NS1iMjRlLTM4NzIyYjkyNWMzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxNzMzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2JlZjMwOTljNjFmOTNkMDRkY2NlYWM5ODZjZDQ4MjA4N2E4MGU1ZDFkNGE5NWJjMTA2MTE4NWNkN2FmMWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VpNGYZ6QIB7GlbeB5U-jA62EKDl-vheApS1Sq_mrYuk)
> 
> did you try the "start radio" on menu? well, thats a temporary solution if it will work for you. the devs might be busy tho
> 
> alternatively, you might wanna try the custom version coz so far, i have no bugs encountered there

i did that and now it works, thanks
