### ISSUE TITLE
Option for update prompts to show only when available for my setup (e.g. FDroid)

### ISSUE THREAD

**Issue by chriskeeble** [fast4x/RiMusic#3989]
### Description

Constantly being bombarded with "update available" when it's not yet available through my distribution platform (e.g. F-Droid) results in effectively having a permanent "update available" notice displaying whenever I use RiMusic.

### Suggested Solution

Either give users an option to turn off update notifications, or recognise which distribution platform the user installed RiMusic through, or provide a "dismiss for 7 days" type option. Ant of these would help.

**Comment by fast4x** [comment]
Disable check update in miscellaneous settings

**Comment by chriskeeble** [comment]
Thank you.  Not sure how I missed that option!
