### ISSUE TITLE
The app closes when you finish your playlist, the songs don't reset, it just closes the app :(

### ISSUE THREAD

**Issue by TkJess0987** [fast4x/RiMusic#3994]
### Version of RiMusic

0.6.56.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

I open the app and as I said it closes when you finish any playlist 

### What was your expectation?

?

### What more can you tell us? (Optional)

?

### Logs (Optional)

?

**Comment by knighthat** [comment]
Please double your battery settings, Android 14 will kill background apps if you don't allow it explicitly. You can set this in **Settings** > **Misc** > **Ignore battery optimization**, or even **Invincible service** if necessary.

Please post your log here, **Settings** > **Misc** > **Copy log to clipboard**. You might need to enable debug logs and reproduce the bug
