### ISSUE TITLE
No descarga las músicas 

### ISSUE THREAD

**Issue by Littleh0t** [fast4x/RiMusic#3997]
### Version of RiMusic

0.6.56 versión personalizada 

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abrí rimusic 
2. Empecé a buscar canciones 
3. Las descargué 
4. Algunas simplemente no se descargan
![Screenshot_20241014-020126_One UI Home](https://github.com/user-attachments/assets/087d35ba-5f37-4a21-9982-9efdaf464f2b)

### What was your expectation?

Todo iba bien hasta la última actualización 

### What more can you tell us? (Optional)

Todo normal, pero algunas canciones solo no se descargan y quedan dando vueltas 

### Logs (Optional)

.

**Comment by fast4x** [comment]
update to latest version

**Comment by Littleh0t** [comment]
No me aparece actualización alguna
