### ISSUE TITLE
Song sorting option in playlists

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#4]
### Description

I would like to see the option to sort songs across all playlists (local, favorites, etc).

see the screenshot.

### Suggested Solution

#
![Screenshot_20230910-031000](https://github.com/fast4x/RiMusic/assets/103368536/eb3d2c81-342c-4327-80d3-ae58c9287781)

**Comment by fast4x** [comment]
I keep the new #45 and close this
