### ISSUE TITLE
Player is not responding to back gestures

### ISSUE THREAD

**Issue by coolswapnil** [fast4x/RiMusic#4001]
### Version of RiMusic

0.6.56.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on Songs, Artists, Albums or Playlist from nav bar
3. Use back gestures (full screen gesture) to return back to default screen or exist the app.
4. Apps stays in opened scren, no action is performed.

https://github.com/user-attachments/assets/59228229-6acb-41be-ac10-16013cc6052f

### What was your expectation?

Using back gestures should exist the app after reaching the default screen set.

**Comment by coolswapnil** [comment]
One more thing:
I even tried with system navigation set to Buttons (instead of Gesture), issue is there as well.

**Comment by tiwna16** [comment]
I am also facing the same issue from **current & some of the previous versions**.
Hope,Developers gonna find out the solution of this bug soon.

**Comment by knighthat** [comment]
I noticed this as well, as far as my finding, there's nothing that handle the back button to exit the app. I'll see if I can add one later on. Thanks for reporting

**Comment by kalahu** [comment]
YouTube playlist import is not working.
