### ISSUE TITLE
Playback just doesn't work + 5 years worth of music gone (I'm not joking)

### ISSUE THREAD

**Issue by gedragen17** [fast4x/RiMusic#4002]
### Version of RiMusic

0.56.1

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### What was your expectation?

Play any song, if it is silent on one part it just skips it, I disabled the option of skipping silent sections btw

### What more can you tell us? (Optional)

Play any song, if it is silent on one part it just skips

Also the fact that all of my data through the 5 years of using the v/r imusic apps progress had been wiped sucks as well.

**Comment by OrangeZXZ** [comment]
You never backed up the database?

**Comment by gedragen17** [comment]
Wish I did but I didn't get a chance too. I was stupid and just installed the update thinking it would the same process as usual. Last time I backed up the data was back when I transferred over to ri from vi

**Comment by knighthat** [comment]
It was pretty foolish of you not to backup your database when installing new version of custom version. 

You can download it, but YouTube is actively preventing you from doing it, songs that are replied with `login required` or any status other than `OK` will not be played/downloaded

We don't give you option to login because we believe it violates privacy foundation. But until I can find a way work around this problem, there's nothing I can do on this situation.

> Always backup your database

**Comment by OrangeZXZ** [comment]
> We don't give you option to login because we believe it violates privacy foundation. But until I can find a way work around this problem, there's nothing I can do on this situation.
> 
> > Always backup your database

I wonder if a feature that creates automatic saves in a folder could be added.

That way we don't really need to worry

Peoples who want to sync it could use a drive or something.

**Comment by knighthat** [comment]
> I wonder if a feature that creates automatic saves in a folder could be added.

I can see this feature being introduced in the future. But there are 2 things you should take into consider

- We are kinda short on devs. We have like what, 2-3 devs working on it actively, with the size of this project, it is not even enough to fix bugs, let alone making new features
- Having a timer running constantly is a battery killer, and I myself think that you don't need to back it up that frequently, unless you add/remove hundreds of songs daily. It's better to just save it after you finish making changes, or set a "reminder" on your calendar to do so

**Comment by OrangeZXZ** [comment]
> > I wonder if a feature that creates automatic saves in a folder could be added.
> 
> I can see this feature being introduced in the future. But there are 2 things you should take into consider
> 
> - We are kinda short on devs. We have like what, 2-3 devs working on it actively, with the size of this project, it is not even enough to fix bugs, let alone making new features
> - Having a timer running constantly is a battery killer, and I myself think that you don't need to back it up that frequently, unless you add/remove hundreds of songs daily. It's better to just save it after you finish making changes, or set a "reminder" on your calendar to do so

Maybe changing the working method?

1 Update per Week can be for bugs and translation
And Every 3 weeks - 1 month for features
