### ISSUE TITLE
Error al reproducir y descargar canciones 

### ISSUE THREAD

**Issue by xkabg** [fast4x/RiMusic#4017]
### Version of RiMusic

0.6.56.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abrir RiMusic
2. Buscar algunas canciones
3. Reproducir canción saldrá error
4. Al darle descargar canción aparece error también 

### What was your expectation?

Poder reproducir las canciones y poder descargarlas sin que tenga tantos problemas de error

### What more can you tell us? (Optional)

Le di en reproducir en algunas de las canciones y me aparece que error desconocido también al momento de descargar las canciones sigue apareciendo de descarga.

### Logs (Optional)

![Screenshot_20241016_093105](https://github.com/user-attachments/assets/c2bf130d-ae65-4fd4-99d5-31dbfac2a36b)
![Screenshot_20241016_093050](https://github.com/user-attachments/assets/120641a4-0221-4b5c-9eb5-a10bfb1f95f1)

**Comment by FPKZtwotwo** [comment]
Isso tbm acontece comigo
