### ISSUE TITLE
Unknown Error Bug/Error

### ISSUE THREAD

**Issue by storm-27** [fast4x/RiMusic#4019]
### Version of RiMusic

Newest Ver. Till Oct 16th (App crashing in About page)

### Android version

14

### I've done these:

- [x] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on a song
3. Unknown Error (Or) Media cannot be played.

### What was your expectation?

For the song to play normally.

### What more can you tell us? (Optional)

I don't know, but for some reason, all Youtube Music based players are not working for me suddenly today. I use RiMusic and Vimusic, but both were not working, ViMusic showed error called something can't use video id, I tried other forks like ViTune, and ViMusic Custom Ver, but it still showed me the same errors.

I saw a problem someone had in ViMusic, and they said to change DNS and restart the app.
I did that and it still didn't work.
I don't know if it's my network problem, phone problem, or YT Music API problem 
My phone model is Poco M6 Pro, And I am in India(I don't know if my region helps, but just incase if it's a network issue.)
Hope this is resolved.
![Screenshot_2024-10-16-23-32-16-473_it fast4x rimusic](https://github.com/user-attachments/assets/7885dff2-9a4d-4e1e-8b42-53feb6526a1e)

### Logs (Optional)

Can't find em. :/

**Comment by tayuriv** [comment]
same thing, I think It's issue of YT music cuz when I was listening music on my pc using YT music music can be stopped randomly

**Comment by ErickMontesDK** [comment]
I have the same problem
