### ISSUE TITLE
Erro no download 

### ISSUE THREAD

**Issue by FPKZtwotwo** [fast4x/RiMusic#4021]
### Version of RiMusic

0.6.56.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on download button
4. And it is not downloading 

### What was your expectation?

That the download was completed

**Comment by knighthat** [comment]
dupplicate #4012
