### ISSUE TITLE
"Moods and genres" isn't displayed on the Quick Picks page

### ISSUE THREAD

**Issue by FixItKit** [fast4x/RiMusic#4036]
### Version of RiMusic

0.6.56.1

### Android version

13

### Tell us how you trigger this bug

1. Open RiMusic.
2. "Moods and genres" is missing.

### What was your expectation?

"Moods and genres" should be displayed on the Quick Picks page.

**Comment by fast4x** [comment]
it display normally, take me info about it, i can't reproduce this bug

**Comment by fast4x** [comment]
Or if available, let me debug log

**Comment by fast4x** [comment]
Stop please

**Comment by fast4x** [comment]
I can't reproduce your bug sorry
