### ISSUE TITLE
"This song cannot be played due to server restrictions" and Associated Crash

### ISSUE THREAD

**Issue by anxiouslelimo** [fast4x/RiMusic#404]
### Steps to reproduce the bug

1. Search for killing in the name
2. Play the second or third song from the search list
3. Error "This song cannot be played due to server restrictions"
4. Exit the app to recents
5. Open the app. App crashes

### Expected behavior

The song should play

### Actual behavior

Error "This song cannot be played due to server restrictions"

### Screenshots/Screen recordings

![rimusic crash](https://github.com/fast4x/RiMusic/assets/115996455/b8f7bda5-6d79-41ed-a1ac-bae68c06dc5d)

### RiMusic version

0.6.17

### Android version

11

**Comment by fast4x** [comment]
I tried now but I didn’t get the error. I try to understand better, eventually I send you a custom version that I ask you to try.

**Comment by fast4x** [comment]
For the moment, I’ll put it as resolved.

**Comment by fast4x** [comment]
> The server restriction still exists right?

Yes

**Comment by fast4x** [comment]
Server restriction not related RiMusic. I'm sorry.

**Comment by fast4x** [comment]
I can try to add workaround, ok.

**Comment by Tre916** [comment]
I've had this happen with many more random songs, but that whole Rage Against the Machine album is the only entire album that gets that treatment.

If there is a workaround that could be implemented it would be fantastic.

**Comment by fast4x** [comment]
in next version there is a crash report feature for debug...

**Comment by Tre916** [comment]
> in next version there is a crash report feature for debug...

For me it doesn't crash, it just doesn't play the songs and doesn't seem to skip them either.

**Comment by fast4x** [comment]
auto skip not implemented

**Comment by fast4x** [comment]
Implemented auto skip if error occur...
