### ISSUE TITLE
The action bar has no background when the background colors are set to be a gradient

### ISSUE THREAD

**Issue by ghost** [fast4x/RiMusic#4041]
### Version of RiMusic

0.6.56.1

### Android version

13

### Tell us how you trigger this bug

1. Open RiMusic.
2. Open settings.
3. Find the option named "Background colors".
4. Set it to "Gradient from song cover" or "Gradient from theme".

### What was your expectation?

It should have a background unless the user has disabled it.

**Comment by fast4x** [comment]
In settings disable transparent color for acton bar
