### ISSUE TITLE
Bug depuis nouvelle version 6.56

### ISSUE THREAD

**Issue by chezwam83** [fast4x/RiMusic#4042]
### Version of RiMusic

0.6.56.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Play music

### What was your expectation?

Le média ne se lance pas.

### What more can you tell us? (Optional)

A chaque nouveau titre Message suivant : le média ne peut pas être lu.

**Comment by fredvellieux** [comment]
I have the same problem. RiMusic stopped playing anything this morning (no sound) I de installed it, installed the latest apk. "Le média ne peut pas être lu". Android 14, Nothing Phone 2.

**Comment by fast4x** [comment]
wait it's YouTube nusic that have blocked all

**Comment by Chmarco1733** [comment]
> bloqué

Bonjour, peut-on faire quelque chose ? Merci 😉

**Comment by fast4x** [comment]
Try custom version please 
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Chmarco1733** [comment]
Yes .....thank
