### ISSUE TITLE
Login required to play this media

### ISSUE THREAD

**Issue by ZeroDarkness31** [fast4x/RiMusic#4044]
### Version of RiMusic

0.6.56.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on music
3. Boom! Login required to play this media
![Screenshot_20241017_133612](https://github.com/user-attachments/assets/e856e23b-b26c-4cc0-a246-f70084edda41)

### What was your expectation?

I need help

**Comment by knighthat** [comment]
Hi, this is not our fault, YT is actively blocking playback unless you use their app

**Comment by ZeroDarkness31** [comment]
Okay, thank you for taking the time to respond🙏

**Comment by CrystaliteID** [comment]
Is this because RiMusic doesn't have the YouTube Login feature? Other YTM Alternative that can login with YouTube account doesn't have this issue.

**Comment by ParsaGachkar** [comment]
Is there anyway we can authenticate? Or rimusic is just blocked?

**Comment by knighthat** [comment]
> Is there anyway we can authenticate? Or rimusic is just dead?

Definitely not dead, it's harder to play songs. We're finding another way.

We don't offer login feature because it violates our privacy beliefs
