### ISSUE TITLE
"unknown error/media cannot be played" bug

### ISSUE THREAD

**Issue by KeknanXD** [fast4x/RiMusic#4045]
### Version of RiMusic

0.6.56.1

### Android version

12

### I've done these:

- [x] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. open RiMusic
2. click on any song (that **isn't cached** or **downloaded**)
3. "unknown error/media cannot be played" bug occurs
Alternatively, if the song does work, let it play or skip to a certain part. The aforementioned bug can recur.

### What was your expectation?

That I can listen to whatever I feel like without being forced to interfere almost every time.

### What more can you tell us? (Optional)

You can bypass this issue by forcing the app to play the same song over and over again until it works - and when it does work, jump all over the song until the analytics tell you it's 100% cached (tip for the readers: press and hold on the cover to view analytics). Alternatively, you can just download the song and the issue is pretty much gone.

https://github.com/user-attachments/assets/38211e04-000d-4b5d-805b-e9f0d45a07ff

https://github.com/user-attachments/assets/bce78d7a-8660-4e3e-9bf6-3619f79385d9

However, it's **really** annoying not being able to listen to something while keeping the phone locked unless I download, and I don't want to download every song I like.

**Comment by knighthat** [comment]
This is YT blocking you from playing, we're finding a workaround to this problem

**Comment by KeknanXD** [comment]
Oh, how come?

**Comment by via80HD** [comment]
Same issue on android v 14 (Moto G 5G)

**Comment by GurrenLagann114** [comment]
> This is YT blocking you from playing, we're finding a workaround to this problem

So basically just like happend with NewPipe months ago.

**Comment by MacReyhan** [comment]
It's not fixed

**Comment by MacReyhan** [comment]
Why did author closed this?

**Comment by knighthat** [comment]
This shouldn't be marked as "fixed". The correct tag should be " not our fault" because it's YT blocking you not us

**Comment by GurrenLagann114** [comment]
No need to be a jackass

**Comment by Kevinbk458** [comment]
> Esto no debería marcarse como "arreglado". La etiqueta correcta debería ser "no es culpa nuestra", porque es YouTube el que te bloquea a ti, no nosotros.

Disculpa me está pasando lo mismo, hay manera de evitar esto, es un problema general o solo ciertos usuarios?

**Comment by mdoymar** [comment]
Hola a mi me pasa igual, he intentado desinstalarlo y volverlo a instalar y aún haci no funciona, alguien sabe como arreglar este error?problema es media cannot be played music

**Comment by MacReyhan** [comment]
This cannot be fixed. YT is blocking everyone.

**Comment by fast4x** [comment]
Today would be a version with many fixes and improvements.

**Comment by Smit-Sharma** [comment]
When will this update come,will it fix this youtube blocking issue,and will it come today

**Comment by KeknanXD** [comment]
Still not fixed in v0.6.58 unfortunately... though it's telling me more explicitly what the issue is now; I should login now.
Will it resolve in time or is this permanent (YouTube being YouTube still)? Sorry if I and many others sound like broken records here, I know it's very exhausting to deal with.

**Comment by Carlosxsz** [comment]
> Lamentablemente, la versión 0.6.58 aún no se ha solucionado... aunque ahora me dice de forma más explícita cuál es el problema; debería iniciar sesión ahora. ¿ Se resolverá con el tiempo o es permanente (YouTube sigue siendo YouTube)? Lo siento si yo y muchos otros parecemos discos rayados, sé que es muy agotador lidiar con esto.

Hola amigo creo que lo que tienes que hacer es meterte en configuración e ir a la sección de "Misceláneo" y donde dice iniciar sesión en yt music lo haces. 
Bueno eso a mí me funcionó la verdad no sé si sea para todos

**Comment by GurrenLagann114** [comment]
> Hola amigo creo que lo que tienes que hacer es meterte en configuración e ir a la sección de "Misceláneo" y donde dice iniciar sesión en yt music lo haces. Bueno eso a mí me funcionó la verdad no sé si sea para todos

Answering in spanish to an english comment  be like:

**Comment by knighthat** [comment]
> Still not fixed in v0.6.58 unfortunately... though it's telling me more explicitly what the issue is now; I should login now. Will it resolve in time or is this permanent (YouTube being YouTube still)? Sorry if I and many others sound like broken records here, I know it's very exhausting to deal with.

I'm still developing alternative ways to play songs without logging. Just pushed #4166, it'll be the temporary solution until real solution is found. Let's hope the owner accepts this

**Comment by KeknanXD** [comment]
Alright, thank you for letting us know.

**Comment by CoderYoshua** [comment]
The problem still occur today I just donwload the app and I've been say to say "blocked by YouTube" so there is still no fix then? Imran how come people get block even they don't even logged in

**Comment by fast4x** [comment]
I don't know internal policy of YouTube Music. RiMusic offer login feature but if you're blocked for a reason, I'm afraid can't solve.

**Comment by KeknanXD** [comment]
That was a while ago. Just install v0.6.59 and you're good.

**Comment by 94Lopes** [comment]
> That was a while ago. Just install v0.6.59 and you're good.

Dude, thank you so much, I had installed with fdroid and for some reason it only goes up to v0.6.57.1

**Comment by KeknanXD** [comment]
no problem lol

**Comment by 54tyeb54** [comment]
Bonsoirs ça revient le même problème 0.6.67
