### ISSUE TITLE
[Feature]: Editable Searches (From Search Results Page)

### ISSUE THREAD

**Issue by via80HD** [fast4x/RiMusic#4048]
### Description

So as of now, lets pretend I want to search for Bryan Adams but Im not the smartest person so I accidentally spell it Ryan Adams & click search....if I wanted to just edit the Ryan Adams I have already typed to add a b to the front, I wont be able to. Wnat I would have to do is click the back arrow &  back out then retype the whole thing & hope I can spell correctly that time. Hopefully I didn't make that too confusing. I have attached a screen recording of the issue to better show/explain the issue here.

https://github.com/user-attachments/assets/5ac28974-0285-4b1a-bab0-dbe63cf00048

### Suggested Solution

Make search terms editable, similar to how search engines work.

**Comment by fast4x** [comment]
Just implemented in 0.6.57
