### ISSUE TITLE
A bunch of issues I'm experiencing

### ISSUE THREAD

**Issue by HWdriver** [fast4x/RiMusic#4049]
### Version of RiMusic

Latest

### Android version

14

### I've done these:

- [x] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1: Rotating to landscape and back restarts the track
2: every 3 or so tracks being played while the screen is off would restart till I manually skip from the app 
3: sometimes I'd minimize the player and it will pause and never unpause
4: some songs won't download.
 

### What was your expectation?

The obvious

**Comment by VARTIK-ARSH** [comment]
@HWdriver @fast4x can i start the work , if there is any type of description pls provide.

**Comment by HWdriver** [comment]
> @HWdriver @fast4x can i start the work , if there is any type of description pls provide.

description like what? how i achieved these bugs?

**Comment by VARTIK-ARSH** [comment]
what are the bug or where are you getting these bug.

**Comment by HWdriver** [comment]
> what are the bug or where are you getting these bug.

When I rotate my phone the track restarts when on the app. 

When listening with the screen off it repeats the last 3 or so songs instead of moving to the next one. I have to manually go in the app and skip

Some songs won't download. No matter how much I try

And sometimes I pause the music, minimize the player and try to maximize it or unpause. It doesn't do it.

**Comment by VARTIK-ARSH** [comment]
Ok pls assign me I wil do as much i can .

**Comment by HWdriver** [comment]
> Ok pls assign me I wil do as much i can .

How do I assign?

**Comment by VARTIK-ARSH** [comment]
@fast4x pls assign the project.

**Comment by fast4x** [comment]
No, after new release, you can clone repository, fix all and send pull request, your name will be added in credits.

**Comment by VARTIK-ARSH** [comment]
Ok let me do it .

**Comment by fast4x** [comment]
Yes remember wait new release...

**Comment by HWdriver** [comment]
> Yes remember wait new release...

How long would it take?

**Comment by fast4x** [comment]
tonight

**Comment by HWdriver** [comment]
> tonight

Cool thanks

**Comment by VARTIK-ARSH** [comment]
> Yes remember wait new release...

Ok
