### ISSUE TITLE
playback error 

### ISSUE THREAD

**Issue by RUDRAXS** [fast4x/RiMusic#4050]
### Version of RiMusic

0.6.56.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on a song
3. Click on next to change song
4. Boom! Crash happens 
5. 
![Screenshot_20241018-131702](https://github.com/user-attachments/assets/2786f841-dd02-45d5-bb02-8484f211813c)

### What was your expectation?

fix this bugs . it's not playing next songs . .

### What more can you tell us? (Optional)

I clicked next to play another song . Then it's saying  "Media cannot be played"  .. app also Stops suddenly .. so irritating  .. My device - Motorola G54 (Android 14)

**Comment by itsluminous** [comment]
same for me
samsung galaxy s21, android 14.

It does not show error for all songs.
And when it shows error, wait for like 10 seconds and try again, then it works.

It feels like we see error when buffer is not ready.

**Comment by vepman** [comment]
> same for me samsung galaxy s21, android 14.
> 
> It does not show error for all songs. And when it shows error, wait for like 10 seconds and try again, then it works.
> 
> It feels like we see error when buffer is not ready.

Yes, here the same.

**Comment by itsluminous** [comment]
seems to be working perfectly in latest release

**Comment by fast4x** [comment]
thanks for feedback
