### ISSUE TITLE
Coda persistente non funziona

### ISSUE THREAD

**Issue by claxcian** [fast4x/RiMusic#4060]
### Version of RiMusic

0.6.57

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Ora quando esci dalla app chiuda la coda, e quando riapri la app non la avvia, anche con l'impostazione cosa persistente attiva.
Con la precedente versione non accadeva.

Inoltre dalla 0.6.56 da molto spesso errore formato non valido e ore non si avvia la canzone o si blocca a metà.

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Mi aspetto che anche se chiudo la app premendo 2 volte il tasto indietro la cosa non si interrompa

**Comment by fast4x** [comment]
Servono altri dettagli tipo in che modalità sei...

**Comment by claxcian** [comment]
Che vuol dire in quale modalità sei?
In tutte le modalità, se esco lui ferma la riproduzione e cancella la coda. Anche con coda persistente attiva.

**Comment by fast4x** [comment]
RiMusic/ViMusic

**Comment by claxcian** [comment]
Rimusic

**Comment by claxcian** [comment]
anche in modalità vimusic lo fa

**Comment by fast4x** [comment]
> anche in modalità vimusic lo fa

ottimo, verifico appena possibile, grazie

**Comment by fast4x** [comment]
Improved, available from version 0.6.61
