### ISSUE TITLE
Download area

### ISSUE THREAD

**Issue by N4SH3-RGB** [fast4x/RiMusic#4063]
### Description

That there is a tab or window related to downloads, and that there is a filter for downloaded and not downloaded.

### Suggested Solution

A filter of downloaded and non-downloaded songs.

### Alternatives

A filter to search for songs you don't download and downloaded

**Comment by N4SH3-RGB** [comment]
:)

**Comment by fast4x** [comment]
In downloaded tab there are only downloaded songs
