### ISSUE TITLE
Songs are not downloaded

### ISSUE THREAD

**Issue by PedroH654** [fast4x/RiMusic#4065]
### Version of RiMusic

0.6.57

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Enter RiMusic
2. Click on download some song 
3. And the bug occurs 

### Submit a video

https://github.com/user-attachments/assets/cc539fed-0c7d-4152-84ae-3bb6531c088c

### What was your expectation?

That the songs would be downloaded normally 

### What more can you tell us? (Optional)

The strange thing is that this bug also causes that, when clicking to download a song, it starts downloading all the others from a certain playlist, that when you scroll the screen the downloads start to disappear and appear

**Comment by Xanx1n** [comment]
I'm experiencing the same thing.

**Comment by fast4x** [comment]
Read release notes please
