### ISSUE TITLE
Application closing by itself when opening the "About" screen

### ISSUE THREAD

**Issue by metademaravilha** [fast4x/RiMusic#4066]
### Version of RiMusic

0.6.57

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on the 3 bars in the top right corner
3. Click on settings
4. On the "UI" tab, scroll down the page until you find the option "interface in use"
5. Change the option from "Rimusic" to "ViMusic"
6. Now, in the navigation tab buttons, press in "About" tab
7. Boom! Crash happens.

### What was your expectation?

I just wanted to see the information about the app.

### What more can you tell us? (Optional)

The application simply closes by itself and instantly, you press the "About" tab and the application closes by itself and instantly.

**Comment by fast4x** [comment]
Nice indications, I'll check it thanks

**Comment by metademaravilha** [comment]
You're welcome ^^

**Comment by fast4x** [comment]
Fixed available from version 0.6.61
