### ISSUE TITLE
Song doesn't download and it stops downloading randomly

### ISSUE THREAD

**Issue by CaterpillarZipbomber** [fast4x/RiMusic#4068]
### Version of RiMusic

0.6.57

### Android version

14

### I've done these:

- [ ] Uninstall old build before installing a new one
- [x] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1 Open a playlist
2 Download a song (doesnt matter if in the song interface or the playlist menu)

### Submit a video

I cant upload a video because it's too long and passes over 20 megabytes

### What was your expectation?

I clicked on download and in the Playlist menu it shows first the downloading animation, then shows that the song is not downloaded and in the music interface it shows that the song is not downloaded, that it is downloaded and that it's downloading

### What more can you tell us? (Optional)

The song starts "downloading" but doesn't actually download, and casually stops showing signs of download.

**Comment by BesidesManthan** [comment]
I've also faced the same issue and fun fact the older version have such a higher download speed that my 3k songs got downloaded under andhour but it took 30 min for the new one to download 100 songs needs improvement asap @fast4x

**Comment by CaterpillarZipbomber** [comment]
i know right? its so annoying that it takes forever for 1 song when like 2
versions ago was 1 song every 3 seconds

Il Sab 19 Ott 2024, 8:41 PM Manthan Garg ***@***.***> ha
scritto:

**Comment by fast4x** [comment]
Download speed for now can't increase

**Comment by BesidesManthan** [comment]
Heyy there are still issues in downloading too and the speed as you mentioned we'll wait for that though

**Comment by fast4x** [comment]
download work better, speed ... I'll check if possible to increase speed, but I think no...

**Comment by BesidesManthan** [comment]
> download work better, speed ... I'll check if possible to increase speed, but I think no... 
I'm a user from India I actually have a playlist of 2929 songs and I need them downloaded in the previous versions it took only an hour to download them all but in this current one it took a whole night and still left like 600 songs out of the downloads

**Comment by fast4x** [comment]
ok i'll try to investigate about it, thanks for details.

**Comment by BesidesManthan** [comment]
Just a heads up the playlist isn't download to its full extent too like I have 2929 and it only downloads upto 1k
