### ISSUE TITLE
The application doesn't even open for me

### ISSUE THREAD

**Issue by Teleposse** [fast4x/RiMusic#4070]
### Version of RiMusic

Idk

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Right now when I try to make the complaint I get a lot of text and I don't understand what's happening, when before it didn't appear (when I sent Bugs or ideas)
I already made a lot of complaints before and they closed them without the problem being solved, I don't know how to update ri music, not from the app or from the web.Now it won't open and it's been like this for two days now.
I've been having problems for about a month or more, which I've already hung up, like it doesn't let me see albums. It also closes automatically and happens daily every few songs,I try to ignore it but they don't save it in my history either. I know I have more to say but I can't even open it to see what I have left to comment on.

### What was your expectation?

Sorry if it is misspelled

### What more can you tell us? (Optional)

I've been having problems for about a month or more, which I've already hung up, like doesn't let me see albums. It also closes automatically and happens daily every few songs,I try to ignore it but they don't save it in my History either. I know I have more to say but I can't even open it to see what I have left to comment on.I hope at least this comes ,even though I have a lot of problems with the app, I still love it and I think it's very good and that it will be very big, that's why I recommend it to everyone, I'm already at 5 recommended and 2 downloaded,I don't know if I said something online, I think I did too. PLEASE DO SOMETHING

**Comment by fast4x** [comment]
try latest please

**Comment by Teleposse** [comment]
> try latest please

I already said that it doesn't let me update it in any way, and I'm not going to uninstall it because there's no way to create an account to save the playlists.

**Comment by fast4x** [comment]
you can make a backup of database

**Comment by twistios** [comment]
As you are using fdroid it seems, test if you can get a crash log via the scoop app.

**Comment by Teleposse** [comment]
> As you are using fdroid it seems, test if you can get a crash log via the scoop app. If you have trouble updating, then probably because you installed via a different source than from where you downloaded the update.

IS scoop a app,is in play store? Is there any way I can uninstall it and then install it and have everything be saved?

**Comment by fast4x** [comment]
Make a backup from settings, remove app, install new form GitHub, restore previous backup. Restart app.

**Comment by Teleposse** [comment]
> Make a backup from settings, remove app, install new from GitHub, restore previous backup. Restart app.
Do you mean uninstall and start again?

**Comment by twistios** [comment]
Create a backup, uninstall your installed version of RiMusic, download latest version from Github, install this version and then restore the backup. Then restart the app.

**Comment by fast4x** [comment]
Yep, make a backup, uninstall, reinstall and restore backup.

**Comment by Teleposse** [comment]
> Yep, make a backup, uninstall, reinstall and restore backup.

I cant open it

**Comment by fast4x** [comment]
Hold on icon launcher and click on copy crash log, paste here

**Comment by Teleposse** [comment]
![IMG_20241128_170017](https://github.com/user-attachments/assets/e8fcdded-332c-4fcf-9772-c4660ac640bb)
