### ISSUE TITLE
Error al reproducir y descargar musica 

### ISSUE THREAD

**Issue by xkabg** [fast4x/RiMusic#4071]
### Version of RiMusic

0.6.57

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abrir RiMusic
2. Reproducir o descargar una canción 
3. Seguir intentando descargar o reproducir 
4. Aparece el error al reproducir y no descarga las canciones 

### Submit a video

https://github.com/user-attachments/assets/d1b88570-2937-4f11-b5d4-62e4528a44fb

![Screenshot_20241019_094342](https://github.com/user-attachments/assets/bad2bc12-e2c4-4f8a-9a76-77076d4dfd1e)

### What was your expectation?

Podes escuchar las canciones sin error y que al momento de descargarlas no se quedara fallando.

### What more can you tell us? (Optional)

Que antes funcionaba bien la aplicación al reproducir las canciones pero ahora siempre sale ese error y siempre hay canciones que no se descargan y van 3 actualizaciones donde no se pudo resolver este problema

**Comment by Trollitubs** [comment]
El error aún existe, incluso con al versión actual

**Comment by Musikaplus7** [comment]
Hola amigos de RI MUSIC... vayan ajustes misa es y pongan un correocorreo de la cuenta de Gmail. De su YouTube music lo activtiba, dales de RI music, vuelve a entrar y LISTO ya se puede descargar la música, ya como ven cuando deseas reproducir una canción en el. Lado izquierdo aparece el logo de YouTube y YouTube music.. Peor ayuden para no poner esa cuenta youtu.be music se paga

**Comment by Musikaplus7** [comment]
> ### Versión de RiMusic
> 0.6.57
> 
> ### Versión de Android
> 14
> 
> ### He hecho esto:
> * [x] Desinstale la compilación antigua antes de instalar una nueva
> * [x] Comprobé los problemas de apertura sobre mi problema similar.
> 
> ### Cuéntanos cómo desencadenas este error
> 1. Abrir RiMusic
> 2. Reproducir o descargar una canción
> 3. Seguir intentando descargar o reproducir
> 4. Aparece el error al reproducir y no descarga las canciones
> 
> ### Enviar un vídeo
>  Grabación de pantalla 20241019 094657.mp4 
> ![Captura de pantalla_20241019_094342](https://private-user-images.githubusercontent.com/178647314/378100421-bad2bc12-e2c4-4f8a-9a76-77076d4dfd1e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5OTIwMDksIm5iZiI6MTcyOTk5MTcwOSwicGF0aCI6Ii8xNzg2NDczMTQvMzc4MTAwNDIxLWJhZDJiYzEyLWUyYzQtNGY4YS05YTc2LTc3MDc2ZDRkZmQxZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwMTE1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOWYzNTBkNTk2NWVjYWEyZTE1NWQ5NDhmODhhZGEzOGRjZGMxZjYyM2VlOTgwNmQyZTYzZjg2M2RkZDNhYmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jMO-Kc3mv1kbPksrMGNvffs3aKRqLJM7lXS7KMRERd4)
> 
> ### ¿Cuál era tu expectativa?
> Podes escuchar las canciones sin error y que al momento de descargarlas no se quedara fallando.
> 
> ### ¿Qué más nos puedes contar? (opcional)
> Que antes funcionaba bien la aplicación al reproducir las canciones pero ahora siempre sale ese error y siempre hay canciones que no se descargan y van 3 actualizaciones donde no se pudo resolver este problema
> 
> ### Registros (opcional)
> _Sin respuesta_

Mira mi comentario encontré una solución, tu refuerza este comentario,
