### ISSUE TITLE
ALL button doesn't allow to play all songs

### ISSUE THREAD

**Issue by karimhsa** [fast4x/RiMusic#4072]
### Version of RiMusic

0.6.57

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Choose Songs
3. Select ALL button to show all songs, I mean songs in cache + downloaded songs.
4. But in ALL there are not al songs...

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I think there should be all songs in the device, in cache and downloaded ones.

### What more can you tell us? (Optional)

This is what I see in my device when I go to Songs section:

ALL button: 1170 songs
FAVORITES button: 20 songs
IN CACHE button: 15 songs
DOWNLOADED button: 1521 songs

So, I think when we select ALL button is because we want to play a list (shuffle mode) with cache + downloaded songs... so it should have 1521+15 = 1536 songs... but there are only 1170 songs.

**Comment by fast4x** [comment]
All excluded other...
