### ISSUE TITLE
Erro no donwload das músicas 

### ISSUE THREAD

**Issue by REDdeadof** [fast4x/RiMusic#4077]
### Version of RiMusic

Bom dia, vim reportar um erro que meu aplicativo anda tendo sobre o donwload das músicas, elas simplesmente não baixam. Não sei se foi alguma configuração que mexi ou o próprio APK, mas gostaria que pudessem audar

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

O APK é excelênte

**Comment by fast4x** [comment]
Hi I'll check for bug
