### ISSUE TITLE
How do I extract the music files so I can listen on my other music players?

### ISSUE THREAD

**Issue by HWdriver** [fast4x/RiMusic#4078]
### Version of RiMusic

Latest

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

not a bug but a question. it didn't sound right as an enhancement

### What was your expectation?

¯\_(ツ)_/¯

**Comment by fast4x** [comment]
Hi, no isn't planned.

**Comment by HWdriver** [comment]
> Hi, no isn't planned.

Why not?

**Comment by fast4x** [comment]
RiMusic isn't a songs downloader
