### ISSUE TITLE
Navigation Bar buttons don't have enough padding (vertical mode)

### ISSUE THREAD

**Issue by Ao1Pointblank** [fast4x/RiMusic#4079]
### Version of RiMusic

0.6.57.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Go to UI settings
3. scroll down to navigation bar settings
4. change to "left"
5. Buttons in nav bar will be crammed too close to the main content of the app, resulting in accidental presses. 

### Submit a video

![Screenshot_20241020-111301_1_1](https://github.com/user-attachments/assets/b5212948-04e9-4d50-971d-141e109c36c8)
 Here you can see the cramped area highlighted in green and also see the padding on the left of the button is greater than the padding on the right. 

### What was your expectation?

there should be enough padding between Navy bar buttons and main window content (albums/playlist squares for example), so that I don't accidentally open an album or playlists while using nav bar

### What more can you tell us? (Optional)

This affects both icon+text and just icon mode of the navbar. in horizontal mode, the padding is still missing but accidental clicks are less likely due to app layout. This started after ~v6.56

**Comment by fast4x** [comment]
Improved, available from version 0.6.61
