### ISSUE TITLE
Short and concise description of your bug

### ISSUE THREAD

**Issue by Mickael81** [fast4x/RiMusic#4081]
### Version of RiMusic

0.6.57.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Lorsque je fais "retour pour fermer l'application", j'ai remarqué que la notification en bas de l'écran (ici en bleu) n'était pas traduite. Il en est de même pour les notifications en rouge qui mentionne une erreur. La notification n'est pas dans la langue sélectionnée dans les paramètres de RiMusic. Est-il possible de corriger ce petit problème de traduction ?
![Screenshot_20241020_204355](https://github.com/user-attachments/assets/421153c6-0721-4918-a738-2afe2e5b42e8)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

J'espérais que mon problème puisse être résolu.

**Comment by fast4x** [comment]
Hi, of course will be fixed soon, thanks

**Comment by fast4x** [comment]
Fixed, available from version 0.6.61

**Comment by Mickael81** [comment]
Great! Many thanks! 🙂👍
