### ISSUE TITLE
Can't search, nor go into settings

### ISSUE THREAD

**Issue by Zetonium** [fast4x/RiMusic#4083]
### Version of RiMusic

v0.6.57.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open the app
2. It's missing the settings, and search for new music buttons

### Submit a video

 N/A

### What was your expectation?

That I can use the app as expected 

### What more can you tell us? (Optional)

I can't uninstall the app since I can't get my backup due to the fact I can't go into settings
This has been the case since about 3 updates ago, and I was hoping it would fix itself
![Screenshot_20241020_231431](https://github.com/user-attachments/assets/9baadbac-eae8-4e03-9fef-f574c53256b3)

### Logs (Optional)

N/A

**Comment by twistios** [comment]
For some reason the top-bar is missing for you. Because of that you can obviously not enter the settings.

**Comment by twistios** [comment]
You can use the search via the app-context menu. Hold the app-icon. It will show serval options including search.

**Comment by filixu** [comment]
I had this problem as well up until recently. I found that the solution and it was to turn the ui from vimusic, back to ri music. 

But in order to reach the settings, I went to an artist's page by holding on a song, and finding the settings there in the original spot.

**Comment by Zetonium** [comment]
This one worked! Thanks.

**Comment by twistios** [comment]
Most settings of ViMusic mode can be applied in RiMusic mode as well.
