### ISSUE TITLE
Download unsuccessful

### ISSUE THREAD

**Issue by JorgeClimber** [fast4x/RiMusic#4085]
### Version of RiMusic

0.6.56.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

After downloading songs for some time, the download option starts to fail, even after trying hours after.

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

.

**Comment by twistios** [comment]
Try latest version, some download problems where solved there.
