### ISSUE TITLE
New songs are unable to be cached when switch to new version

### ISSUE THREAD

**Issue by Nuibance** [fast4x/RiMusic#4090]
### Version of RiMusic

0.6.57.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Click on new songs
Press download button or finish the song

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

To be able to cached or downloaded

### What more can you tell us? (Optional)

When I click it is says size and bitrate unknown i don't know if that helps

**Comment by Nuibance** [comment]
The cache works on 0.6.57

**Comment by twistios** [comment]
The situation where size and bitrate are unknown does not happen with all songs. Songs where it is not like this the app should be able to download them.

**Comment by fast4x** [comment]
There is a bug in song format, will be fixed in next version
