### ISSUE TITLE
Can import playlist

### ISSUE THREAD

**Issue by Lio-gif** [fast4x/RiMusic#4094]
### Version of RiMusic

0.6.56

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on import playlist 
3. Cant chose CSV file

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

the Playlist on my libary

### What more can you tell us? (Optional)

Hawk tuah 🥺🙅🧏

**Comment by tiwna16** [comment]
I wanted to report about it also so Thanks buddy.I am facing the same issue.

I saved Favourites & Downloads **.csv** files in my Main (**Internal**) Directory.Still now,**Can't able to** select those files through Library Section **Import** Button.

But **Interestingly** "Restore from Backup" In Data Settings Section is able to identify the Database.csv file from the same directory & able to backup like previous working versions.

**Comment by Lio-gif** [comment]
> I wanted to report about it also so Thanks buddy.I am facing the same issue.
> 
> I saved Favourites & Downloads **.csv** files in my Main (**Internal**) Directory.Still now,**Can't able to** select those files through Library Section **Import** Button.
> 
> But **Interestingly** "Restore from Backup" In Data Settings Section is able to identify the Database.csv file from the same directory & able to backup like previous working versions.

Thanks i had a debug Version lying around and imported the playlist there (older Version) and Made a Backup thx

**Comment by nomenamecom** [comment]
Lio-Gif, I have the same problem. I cannot import de CSV backup lists. It recognizes on the file but impossible to chose. I can import the backup of config and followed, but not the lists os song individually

If I understood you installed an old version and could import. After that, update the version?
The problem is loosing all the personal configuration of the app, isn't it?

Thanks!!

**Comment by Lio-gif** [comment]
> Lio-Gif, I have the same problem. I cannot import de CSV backup lists. It recognizes on the file but impossible to chose. I can import the backup of config and followed, but not the lists os song individually
> 
> If I understood you installed an old version and could import. After that, update the version? The problem is loosing all the personal configuration of the app, isn't it?
> 
> Thanks!!

You could also Export an Backup with all your setings Install an old Version import setings and playlists

**Comment by nomenamecom** [comment]
In setup/data/restore?

I saw that personal preferences (color, lyrics, display...) are not saved. 

![IMG_20241026_143229](https://github.com/user-attachments/assets/b3f2dcc7-1841-40a4-abe0-682861d222f0)

Just for understanding (I will restore). Is it here where you say?

Thanks!!
