### ISSUE TITLE
Future of RiMusic

### ISSUE THREAD

**Issue by jayb-g** [fast4x/RiMusic#4098]
Amazing app. Mostly better than paid alternatives out there. Some things have to be improved and issues are already created by users for them. One thing that bothers me is not being sure how sustainable it is in the long run, ie is it legal or can it banned in future like other FOSS YouTube clients in the past? Or under what circumstances it can just stop working?(even without having any legal issues)

**Comment by fast4x** [comment]
I don't know when it stop, RiMusic isn't a pirate client, it work only if YTM want that work like all others alternative client similar app.

RiMusic is an app developed as a fork of ViMusic for passion. There is no idea of making money and it does not allow the export of downloaded music. The only difference is that as in other similar apps advertising is not present. There will just YTM add it directly into songs. RiMusic will be there as long as YTM wants it like all other similar apps.

**Comment by fast4x** [comment]
> You mean there's no advertising/tracking in RiMusic as well, right?

Exactly, future of RiMusic and similar depend by YTM limitations now and in the future.

**Comment by dAtA-TRoN** [comment]
> LibreTube seems good. How does it compare to/better/worse than newpipe?

Just try it for yourself 🤷🏻‍♂️🙂.

**Comment by TheRedCyclops** [comment]
> grayjay is not open source. Also I like kinda minimalistic UI and features of newpipe.
> 
> LibreTube seems good. How does it compare to/better/worse than newpipe?
Grayjay is open source https://gitlab.futo.org/videostreaming/grayjay
