### ISSUE TITLE
Statistics, Video search and Discovery page not working.

### ISSUE THREAD

**Issue by Timotit** [fast4x/RiMusic#410]
### Steps to reproduce the bug

Statistics page:
1. Click on the statistics button
2. The statistics are automatically deleted
3. It only shows the songs that I listened to a few minutes ago
Video search:
1. Type something into the search
2. Click on videos
3. Keeps loading forever
Discovery page:
1. Click on Discovery
2. It says "An error occured" and doesn't load.

### Expected behavior

Statistics shouldn't get reset everytime I launch the app. I should be able to search for videos. The Discovery tab should work.

### Actual behavior

.

### RiMusic version

0.6.17

### Android version

Android 13

**Comment by fast4x** [comment]
Check settings Min listening time

**Comment by fast4x** [comment]
Statistica bug not reproduced.
