### ISSUE TITLE
Problems with music and continuation 

### ISSUE THREAD

**Issue by Jhonsilva953** [fast4x/RiMusic#4104]
### Version of RiMusic

0.6.571.v

### Android version

7.1 - 7.1.2

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1.The song ends, but instead of going to the next song, it goes to the previous song. 

2.The app starts to stop working out of nowhere, like the songs don't play, I can't choose the songs, and it's as if the app has crashed. 

### Submit a video

I can't send videos because the problem happens out of nowhere

### What was your expectation?

I wish it would happen this week, I'm really addicted to this app and I can't live without it.

### What more can you tell us? (Optional)

The songs are starting to go into repeat songs, and

**Comment by fast4x** [comment]
Fixed, available from version 0.6.63
