### ISSUE TITLE
A música não é reproduzida / erro desconhecido

### ISSUE THREAD

**Issue by pedrinfal** [fast4x/RiMusic#4108]
### Version of RiMusic

0.6.57.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Quero baixar e ouvir as minhas músicas como antes, amo o app de vocês

### What more can you tell us? (Optional)

Toda vez que clico em alguma música, ela não toca e nem baixa

**Comment by fast4x** [comment]
Download latest version please.

**Comment by pedrinfal** [comment]
Ok bro

Em sáb., 26 de out. de 2024, 18:15, Rino Russo ***@***.***>
escreveu:
