### ISSUE TITLE
I can't listen to any song

### ISSUE THREAD

**Issue by Carlos353478** [fast4x/RiMusic#4109]
### Version of RiMusic

0.6.57.1

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

I cant listen any song just the song that a have installed  

### What was your expectation?

let the problem be resolved

### What more can you tell us? (Optional)

Anything thats all

### Logs (Optional)

I don't know how

**Comment by Neto-afk** [comment]
I'm also suffering from the same problem, any song I try to listen to, it doesn't work.
![Screenshot_2024-10-23-23-56-36-760_it fast4x rimusic-edit](https://github.com/user-attachments/assets/52b87aa2-d105-4463-8f0b-8ac8e726ffe9)
![Screenshot_2024-10-23-23-57-02-926_it fast4x rimusic-edit](https://github.com/user-attachments/assets/22b5ead1-10f2-41b2-adc0-e4a97782c2d6)
![Screenshot_2024-10-23-23-57-32-332_it fast4x rimusic-edit](https://github.com/user-attachments/assets/8f3fd6a5-87fe-4de9-8074-f777ba481346)

**Comment by gagankj** [comment]
Same problem

**Comment by theinsidersandrush** [comment]
I have a same problem too!

**Comment by acceleratzz** [comment]
Same problem

**Comment by sergonbay** [comment]
Same problem for me. Thanks.

**Comment by ShaikAli65** [comment]
Same problem, even the VI music is saying "requested id does match ..."

**Comment by Poulpiks** [comment]
Same

**Comment by tayuriv** [comment]
same

**Comment by L3mon-Cat** [comment]
Vi music and all of its forks not working. I think the problem is with YT music

**Comment by Pierdark** [comment]
Same problem.

**Comment by Cresh680** [comment]
Also having the same issue getting songs to play when I click the play button. 
![Screenshot_20241024_055023](https://github.com/user-attachments/assets/96b98baf-381c-4d51-a9d1-46b74f5b2e73)

**Comment by Nandkishor01** [comment]
> Vi music and all of its forks not working. I think the problem is with YT music

Yeah ytmusic Is forcing login onto everyone so all vimusic/forks that allowed songs to play without login are suffering from the error. It goes away if you login into google account.

**Comment by SmoothButt** [comment]
> > Vi music and all of its forks not working. I think the problem is with YT music
> 
> I think It could be fixed by signing in by piped (Not sure, haven't tried).

Just tried out, still doesn't work.

**Comment by Nandkishor01** [comment]
> Just tried out, still doesn't work.

If you can't wait for A Workaround I think you should consider switching to ones that has login like piped or innertune. (Tho I wouldn't do it)

**Comment by Nandkishor01** [comment]
> I think one possible solution would be to implement something like [Aurora Dispenser](https://gitlab.com/AuroraOSS/aurora-dispenser) for anonymous login.

Seems interesting Let's see what fast4x and other devs do, I might try it when I'll get back home.

**Comment by toasterofbread** [comment]
Fetching YouTube streams still works using the normal /player method when using an [IOS context](https://github.com/anandnet/Player-Response/blob/940439ef88e2da49718f287dfda910a21d437541/lib/const.dart#L21) (this is the one that seems to be used by Harmony Music, which is why that still works). See the corresponding fix I implemented for SpMp (which is experiencing the same issue) [here](https://github.com/toasterofbread/ytm-kt/commit/ce99c539af10f299a635fbc073b273245119730e). I'd bet on YouTube patching this sooner or later though.

The latest release of NewPipeExtractor (v0.24.2) also works.

**Comment by fast4x** [comment]
Thanks for details

**Comment by Cresh680** [comment]
![Uploading Screenshot_20241026_073930.jpg…]()
