### ISSUE TITLE
No se pueden reproducir los medios/ error desconocido 

### ISSUE THREAD

**Issue by skinnyexe13** [fast4x/RiMusic#4110]
### Version of RiMusic

0.6.57

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

A.abri la aplicación 
B.trate de escuchar una canción 
C.salia un mensaje que dice no se puede encontrar un formato de audio compatible 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

https://github.com/user-attachments/assets/da18897d-9265-4376-a54c-5c7a1a660e8d

### What was your expectation?

Hice click en una canción para escucharla y sale un mensaje que dice  no se puede encontrar un formato de audio compatible 

### What more can you tell us? (Optional)

Cada vez que voy a entrar a escuchar una canción dice que no se puede encontrar un formato de audio compatible

**Comment by fast4x** [comment]
wait for fix
