### ISSUE TITLE
SONG CANNOT BE PLAYED

### ISSUE THREAD

**Issue by Kennyrogerspot** [fast4x/RiMusic#4111]
### Version of RiMusic

0.6.56.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3.
4. Click on B
5. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Nothing happens

**Comment by Giocraft125** [comment]
I have the same issue

**Comment by lividhen** [comment]
Just started having the same issue. Newpipe, piped and invidious seem to be unaffected.

**Comment by aneesh1122** [comment]
> Just started having the same issue. Newpipe, piped and invidious seem to be unaffected.

Newpipe is working. Thanks for the info

Which instance of insidious and piped is working?

**Comment by lividhen** [comment]
My own instances, was just saying the scrapers are working, sorry! Piped and invidious public instances have been having their own IP ban and rate limiting issues so I'm not sure if any are working at the moment 😓

**Comment by aneesh1122** [comment]
> My own instances, was just saying the scrapers are working, sorry! Piped and invidious public instances have been having their own IP ban and rate limiting issues so I'm not sure if any are working at the moment 😓

Well, none of the public instances are working. I'm not sure how NewPipe is working.

Harmony is also working

**Comment by josemrs** [comment]
It's happening to me too

**Comment by fast4x** [comment]
Download latest version please.

**Comment by josemrs** [comment]
Installed 0.6.58.1 from GitHub still happening.
Cache and data reset, not working

**Comment by josemrs** [comment]
Working now. I had to uninstall and install it again.

Thanks
