### ISSUE TITLE
ERROR al intentar reproducir musica

### ISSUE THREAD

**Issue by Tomiastt** [fast4x/RiMusic#4114]
### Version of RiMusic

0.6.56.1

### Android version

8.1

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abro RiMusic
2. Reproduzco una cancion
3. Me sale un error "Media cannot be played" o "Error desconocido"
4. No se puede escuchar musica

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Que me solucionen el problema

**Comment by fast4x** [comment]
Fix in progress
