### ISSUE TITLE
Song cannot be playing 

### ISSUE THREAD

**Issue by Andi1278910** [fast4x/RiMusic#4115]
### Version of RiMusic

0.6.56.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on music
3. Play
4. Media cannot be play

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I clicked and error

### What more can you tell us? (Optional)

error

### Logs (Optional)

![Screenshot_2024-10-24-22-59-25-552_it fast4x rimusic](https://github.com/user-attachments/assets/bcece26f-16f8-4883-953a-018d13908cdb)

**Comment by RealSlyR** [comment]
I am still facing the same issue please help :(

**Comment by fast4x** [comment]
App is latest?

**Comment by chriskeeble** [comment]
This is not fixed in 0.6.57.1 

The issue is now occurring on EVERY song I try to play.  I have cleared all caches.

**Comment by chriskeeble** [comment]
This appears to be fixed in v0.6.58.1 - thank you.

**Comment by Broplsletmein** [comment]
![Screenshot_2024-11-06-01-36-59-095_it fast4x rimusic](https://github.com/user-attachments/assets/86664d51-3ef7-4158-a013-db818195bb4a)
Instead of media cannot be played it shows song cannot be played now

**Comment by nightfury05** [comment]
i have same issue

**Comment by fast4x** [comment]
Maybe in your location is locked without login.

**Comment by nightfury05** [comment]
> Maybe in your location is locked without login.

im logged in in yt music

**Comment by fast4x** [comment]
Try disconnect, restart app and reconnect

**Comment by TheHall11** [comment]
Version 0665 and it shows song cannot be played to multiple songs. It was playing fine until i updated to  the latest version! Anyone found any solution?

**Comment by fast4x** [comment]
download preview version release with fix grom telegram group

**Comment by TheHall11** [comment]
> download preview version release with fix grom telegram group

Ok will do that thanks! I just downgraded to 0664 and it plays fine now

**Comment by KabirADnan41** [comment]
![Screenshot_20250111-093635](https://github.com/user-attachments/assets/5d680131-fd02-4289-80c0-b1cc939bdfeb)


I am still facing the same problem version 0.6.66

**Comment by KabirADnan41** [comment]
![Screenshot_20250111-093858](https://github.com/user-attachments/assets/5c30f9e6-c7a0-4932-834d-10c3572b24d9)
  

I am still facing the same problem version 0.6.66

**Comment by fast4x** [comment]
but you use vpn?
if you use version 64 again, it work?

**Comment by homeostashish** [comment]
Facing same issue. "Song cannot be played".

**Comment by BunTymofiy** [comment]
Facing the same issue. I tried a bunch of versions, from 6.6.0 to 6.6.7 and none of them work. It plays about 30 seconds of the song and stops. No vpn, no add blocker. Tried on LTE and wifi. Nothing works.

**Comment by fast4x** [comment]
try to use login only for browse in account settings

**Comment by BunTymofiy** [comment]
Tried that too. Still getting this
![Screenshot_20250123-012240.png](https://github.com/user-attachments/assets/e092c33a-8b34-4f39-b7c8-98e47aa9256a)

![Screenshot_20250123-012238.png](https://github.com/user-attachments/assets/ceb15071-c36c-4d1f-8b6e-20f2d28a76d9)
