### ISSUE TITLE
La música no se reproduce 

### ISSUE THREAD

**Issue by Mikicarlitos** [fast4x/RiMusic#4116]
### Version of RiMusic

0.6.57

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Reproduzco cualquier canción y me arroja mensaje de que no está disponible 
3. Click on B
4. Boom! Crash happens

### Submit a video

https://github.com/user-attachments/assets/c3608b27-5325-434b-9db5-38b5bd51c03a

### What was your expectation?

Reproducir mi música normalmente

**Comment by fast4x** [comment]
Fix in progress

**Comment by XGhostRX** [comment]
A todo mundo le pasa
Y sinceramente las actualizaciones sólo están de relleno
