### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CalebXLZ** [fast4x/RiMusic#4117]
### Version of RiMusic

0.6.55

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abri RiMusic
2. Hice click en una cancion
3. Boom! error desconocido 
![Screenshot_20241024-151200](https://github.com/user-attachments/assets/e4cf511a-549e-4177-8026-918b3813090b)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

esperaba que se solucionara

### What more can you tell us? (Optional)

no me deja reproducir ninguna cancion, me aparece que es un error desconocido (media cannot be played/ ha ocurrido un error de reproducción desconocido), tenia una versión antigua asi que pense que era por eso, instale la mas reciente y me sigue apareciendo lo mismo. Tampoco me deja descargar las músicas
![Screenshot_20241024-151200](https://github.com/user-attachments/assets/d698b048-72cc-4823-a5d0-7bea7b69a4fc)

### Logs (Optional)

.

**Comment by fast4x** [comment]
Fix in progress

**Comment by knighthat** [comment]
YT is actively blocking third-party clients, that's why you get this message. I just pushed #4122, let's hope that the owner accept it

**Comment by fast4x** [comment]
Yep will be accepted, i want only look how to solve alternative like Piped and similar.
