### ISSUE TITLE
My app dont download the songs

### ISSUE THREAD

**Issue by kkkkkkkkk6** [fast4x/RiMusic#4118]
### Version of RiMusic

0.6.57.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click to download teh song
3. The download fails

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

This bug will fixed soon

**Comment by fast4x** [comment]
Fix in progress

**Comment by knighthat** [comment]
YT is actively blocking third-party clients, that's why you get this message. I just pushed #4122, let's hope that the owner accept it
