### ISSUE TITLE
Music Player UI Grow and Shrink Depending on Thumbnail Size Setting

### ISSUE THREAD

**Issue by BoneMarrow10** [fast4x/RiMusic#412]
### Steps to reproduce the bug

1. Go to settings, Appearance, change Thumbnail size

### Expected behavior

The music player UI shouldn't change depending the thumbnail size

### Actual behavior

The music player UI grow and shrink when the thumbnail size changed

### Screenshots/Screen recordings

![Screenshot_20240115-033045](https://github.com/fast4x/RiMusic/assets/156551596/d2fe2332-8b1d-4963-ada7-28ef5c968cd4)
![Screenshot_20240115-033049](https://github.com/fast4x/RiMusic/assets/156551596/abc6d955-d976-47c5-aecd-f3ff195d2492)
![Screenshot_20240115-033057](https://github.com/fast4x/RiMusic/assets/156551596/1d9c03ee-cc10-4f04-a59e-3098ed7af07d)
![Screenshot_20240115-033101](https://github.com/fast4x/RiMusic/assets/156551596/6abb9151-0b11-4130-9dcf-b8b9a32e855b)
![Screenshot_20240115-033107](https://github.com/fast4x/RiMusic/assets/156551596/77b07377-b92e-435c-85af-1e8d1852c71b)
![Screenshot_20240115-033116](https://github.com/fast4x/RiMusic/assets/156551596/fada516b-ed67-4a13-b920-fb62069e5155)
![Screenshot_20240115-033123](https://github.com/fast4x/RiMusic/assets/156551596/549fae9b-656c-4957-8600-a018444ca9af)
![Screenshot_20240115-033126](https://github.com/fast4x/RiMusic/assets/156551596/b9988683-f5be-4128-b41d-b9b893ff378f)

### RiMusic version

0.6.17

### Android version

Android 12

**Comment by fast4x** [comment]
It’s a feature, not a bug.

**Comment by Logan7899** [comment]
> It’s a feature, not a bug.

Yaa
