### ISSUE TITLE
playback unknown error

### ISSUE THREAD

**Issue by elguapoita** [fast4x/RiMusic#4120]
### Version of RiMusic

0.6.57.1

### Android version

9

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on song
3. Click on the song's play button
4. Boom! Crash happens(it gives a unknown playback error)

### Submit a video

https://github.com/user-attachments/assets/e4008363-ba0e-4e7f-8570-560e1089b840

### What was your expectation?

i thought that this update would fix that infamous error

**Comment by knighthat** [comment]
YT is actively blocking third-party clients, that's why you get this message. I just pushed #4122, let's hope that the owner accept it

**Comment by elguapoita** [comment]
I saw the latest release but what can i do if i don't have a ym account?That means that i can use the app only For browsing without logging?

**Comment by knighthat** [comment]
we're planning on splitting the app for difference purposes. 1 uses Google login system and 1 continues with FOSS. I just pushed another PR #4166, this will let you use Piped as an alternative until we find different solution
