### ISSUE TITLE
Stop posting known issues

### ISSUE THREAD

**Issue by Donald-Win** [fast4x/RiMusic#4124]
### Description

Honestly people, it is not hard to see that everybody is reporting the same issues over and over again. There is no need to spam the guys that work to maintain this app.

### Suggested Solution

If you must add more information add a comment to one of the already opened tickets. For the most part just saying the same as everybody else is counter productive and people that could potential fix issues will be wasting time reading the same thing over and over again instead of time solving issues.

**Comment by stickboiadah** [comment]
Finally, someone said it.

**Comment by aneesh1122** [comment]
LOL. There are already 4 bug reports after this. You expect a lot of these people. I had to close the telegram group topics to stop people from spamming.

They started sending me DMs asking why the app is not working.

**Comment by Donald-Win** [comment]
I wouldn't say I was expecting much at all. Apparently too much tho.

Thanks for all your efforts aneesh (and other developers/contributers) Sorry you have to put up with idiots

**Comment by Donald-Win** [comment]
Not much point in leaving this open. People don't read anyway

**Comment by Donald-Win** [comment]
Closed
