### ISSUE TITLE
No funciona xd 

### ISSUE THREAD

**Issue by Tavoxdxd** [fast4x/RiMusic#4125]
### Version of RiMusic

O.6.57.1

### Android version

9

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Pues habri la app e intente agregar una canción a mis favoritos y cuando la intenté escuchar me decía error de ay hoy también lo mismo Ise una copia de seguridad y borre la app y volví a descargar la versión más reciente de ay Intnte con versiónes anteriores y nada y ahora no soño no mw deja escuchar canciones si no tambien ni me deja escuchar mi fsvorito

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Que si me pueden solucionar mi problema porque ya e usado la aplicación casi más 6 meses y me encanta y no quiero cambiar de app

**Comment by Donald-Win** [comment]
https://github.com/fast4x/RiMusic/issues/4124#issue-2612571166
