### ISSUE TITLE
No puedo escuchar musica por que no carga

### ISSUE THREAD

**Issue by Dilanfgg4142** [fast4x/RiMusic#4127]
### Description

No puedo escuchar música, me dice que no pido cargar y nunca carga la música que quiero escuchar

### Suggested Solution

Quiero que me carmen las músicas 

### Alternatives

No se como puedo arreglarlo

### Additional Context

Ayuda

**Comment by mahurutu** [comment]
Buenas, a mí me funciona solo las canciones que descargué previamente, creo que lo han chapado amigo

**Comment by Tabris1777** [comment]
Yo estoy igual el mismo error

**Comment by Donald-Win** [comment]
https://github.com/fast4x/RiMusic/issues/4124#issue-2612571166
