### ISSUE TITLE
App doesn't let me listen to music 

### ISSUE THREAD

**Issue by Shadow3352** [fast4x/RiMusic#4129]
### Version of RiMusic

v0.6.51

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. It was like 3 days ago that the app doesn't let me listen to music 
2. It sais "unknown error" every time I try to play a song 

### Submit a video

![Screenshot_20241024_190657](https://github.com/user-attachments/assets/b2c13fe6-9cf1-4a92-bc13-e8d8de298624)
 

### What was your expectation?

I expect to be fixed cause I really need to listen to some music

**Comment by aneesh1122** [comment]
> I expect to be fixed cause I really need to listen to some music

Say please

**Comment by Donald-Win** [comment]
https://github.com/fast4x/RiMusic/issues/4124#issue-2612571166
