### ISSUE TITLE
Pop's biggest hits

### ISSUE THREAD

**Issue by wunder20v** [fast4x/RiMusic#413]
### Steps to reproduce the bug

https://github.com/fast4x/RiMusic/assets/156642707/6e5382f5-0d51-4bbf-b2f6-ee1eafbeb0b9

### Expected behavior

The playlist should load

### Actual behavior

It does not load

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/156642707/b24ca55f-7d2b-4312-879d-4f64f142c667

### RiMusic version

0.6.17

### Android version

Android 13

**Comment by fast4x** [comment]
These are playlists that are not made available to apps outside YTM.

**Comment by 25huizengek1** [comment]
That is just not true, this IS a bug. You can still fetch it, but YouTube tends to return a lot of songs for these playlists, because on YouTube they behave as 'infinite' playlists. When you fetch those infinite playlists you literally have to wait until you get rate-limited, because RiMusic currently tries to fetch them all.

In my fork I thought a good point to stop fetching is when duplicate songs start appearing, or when a max depth threshold is reached. Maybe RiMusic should do the same?

**Comment by 25huizengek1** [comment]
Yes I did, as I stated. What have you already tried though?

**Comment by wunder20v** [comment]
![Screenshot_2024-01-15-17-04-37-63_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/156642707/9d9fc0fd-b2c0-468e-8e10-526e3785e861)

**Comment by wunder20v** [comment]
It works now but idk

**Comment by wunder20v** [comment]
I've just waited an eternity

**Comment by 25huizengek1** [comment]
Yes it is. Either pagination should be supported, or you could just account for this case, like I said.

**Comment by fast4x** [comment]
Then since you have experience and say it’s a bug, you can fix it with a pull request.

**Comment by dtomvan** [comment]
@fast4x Just use `git cherry-pick`. From man git-cherry-pick(1):

Given one or more existing commits, apply the change each one introduces, recording a new commit for each. This requires your working tree to be clean (no modifications from the HEAD commit).

This way you can "import" the relevant additions to your repo, if you want to reuse @25huizengek1 's code.

**Comment by fast4x** [comment]
@dtomvan thanks for suggestions

**Comment by fast4x** [comment]
@anxiouslelimo i confirm, it load only 100 songs with fix by @25huizengek1 https://github.com/fast4x/RiMusic/pull/419 but is but it’s much faster

**Comment by fast4x** [comment]
> @fast4x Is it because of max depth threshold as mentioned by @25huizengek1 ? Couldn't this be resolved?

Currently the maxdepth is fixed at the maximum possible value, so the "problem" is not that.
