### ISSUE TITLE
Error in music playback

### ISSUE THREAD

**Issue by EnzoAugier** [fast4x/RiMusic#4131]
### Version of RiMusic

0.6.57.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

"I want to play songs and I can't, I get the following messages: 'media cannot be played' and 'an unknown playback error has occurred.' It's not the usual error where after a few clicks it works again; this time it never plays the songs. It doesn't let me play any song, only the ones I've already downloaded."

![Screenshot_20241024_203448](https://github.com/user-attachments/assets/ec1f7ae1-22d1-4b06-adfe-bc6e495a5930)
![Screenshot_20241024_203143](https://github.com/user-attachments/assets/ebf4da66-4e82-4b44-8b78-58e0c9d84df4)

### What was your expectation?

Listen to music :(

**Comment by CMOISDEAD** [comment]
I am also experiencing this bug since a few days ago, I have already updated and deleted the data and it is still the same.

**Comment by Donald-Win** [comment]
https://github.com/fast4x/RiMusic/issues/4124#issue-2612571166

**Comment by Maikcs** [comment]
A mí también me pasó lo mismo, ya intente actualizando lo, borrandolo y volviendo lo a instalar y aún no consigo resolverlo

**Comment by Alis0312** [comment]
Me está pasando lo mismo no sé que hacer para solucionarlo, uso mucho está aplicación

**Comment by aneesh1122** [comment]
Yeah, the app is not able to play any songs. We are aware of it because of countless and  useless issues created by people like you.

Do you have errors in reading words? Can't you see that there are so many issues created already?

**Comment by EnzoAugier** [comment]
hey, relax, don't disrespect me because I didn't do it to you, i'm just informing about a bug, that's all, my God

**Comment by aneesh1122** [comment]
> hey, relax, don't disrespect me because I didn't do it to you, i'm just informing about a bug, that's all, my God

Can't you see that the same bug has been reported many times already? Why are you wasting other's time as well as yours?

Close this issue
