### ISSUE TITLE
RiMusic 

### ISSUE THREAD

**Issue by Carlosj25** [fast4x/RiMusic#4132]
### Version of RiMusic

0.57.1version

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Media not be played

**Comment by Jacoblightning** [comment]
I think this is google's attempt at fighting back.

**Comment by Donald-Win** [comment]
https://github.com/fast4x/RiMusic/issues/4124#issue-2612571166
