### ISSUE TITLE
Reproducir canción sale media ca not be played

### ISSUE THREAD

**Issue by ghost** [fast4x/RiMusic#4134]
### Version of RiMusic

0.6.57.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
![Screenshot_20241024-201808](https://github.com/user-attachments/assets/57e5591f-8f8d-4526-965b-9d113356473e)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Esperar ero nada

### What more can you tell us? (Optional)

Solamente eso

**Comment by ramonjpg** [comment]
Misma situación, desinstalé anterior e instalé la nueva y sigue sin funcionar, y muestra este mismo error.
