### ISSUE TITLE
No me deja escuchar musica 

### ISSUE THREAD

**Issue by MrWhiteGg** [fast4x/RiMusic#4135]
### Version of RiMusic

v0.6.57.1 by fast4x

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on "Degenere - Myke Towers
3. Click on "gimme a second - peso pluma" 
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Me metí a la app y luego me metí a buscar una canción, cuando la encontré la seleccióne y me decía error, entonces le di en descargar pera ver si funcionaba, luego lo volví a intentar pero me volvió a decir "error en reproducción", luego probé con otra canción que ya tenía en mi biblioteca, y si mi funcionó, pero para solucionar el problema del principio, descargue la versión más actual, pero cuando entre, me volvió a mandar error (no se que decía el error) y cuando volví a intentar con una de mi biblioteca pero tampoco me dejó y tampoco me puedo ver la letra de las canciones

**Comment by YUUBBD** [comment]
X2

**Comment by YUUBBD** [comment]
Encima hice todo lo que me dice pero igual sigue sin andar

**Comment by YUUBBD** [comment]
![Screenshot_2024-10-24-21-58-38-051](https://github.com/user-attachments/assets/4749ffa1-f605-482b-96a1-48d732fc4c3d)

**Comment by aneesh1122** [comment]
What's the problem with you? Can't you see that there are many issues created already about the same bug?

Developers are already working hard in fixing the bugs. Don't bother them more by creating useless issues.

**Comment by XGhostRX** [comment]
> ¿Qué problema tienes? ¿No ves que ya se han creado muchos problemas relacionados con el mismo error?
> 
> Los desarrolladores ya están trabajando arduamente para corregir los errores. No los molestes más creando problemas inútiles.

Bonita respuesta que das (sarcasmo)

**Comment by XGhostRX** [comment]
> What's the problem with you? Can't you see that there are many issues created already about the same bug?
> 
> Developers are already working hard in fixing the bugs. Don't bother them more by creating useless issues.

Nice answer you give (sarcasm)

**Comment by nubesurrealista** [comment]
You guys don't understand how open source works, you sound like spoiled children complaining and demanding that your problems be fixed. Read carefully: this project has no guarantees and no commitment to you, the developer will do whatever he wants, the problem you are complaining about is Google's fault and will be fixed in a future update, if only you knew how to read, you would know that.

**Comment by YUUBBD** [comment]
Come on, you piece of shit, I know that there is no guarantee in an open source application and that it is Google's fault, I just say it so you can see that it is not just one of those who complain.

**Comment by YUUBBD** [comment]
I would like to see it fixed as it is a good app and it would be nice if the community of this app was more understanding with those who don't know.

**Comment by YUUBBD** [comment]
Okay, okay, shut your ass up! Nobody asked for your opinion

**Comment by fast4x** [comment]
> Come on, you piece of shit, I know that there is no guarantee in an open source application and that it is Google's fault, I just say it so you can see that it is not just one of those who complain.

Hi, in this community education is required, there is no room for those who do not show up educated. 
**So please be educated and patient.**

**Comment by YUUBBD** [comment]
Yes, yes, whatever you say, I didn't ask for your opinion either.

**Comment by YUUBBD** [comment]
If I could answer you in Spanish and you could understand, not even your mother would be saved, you fucking idiot.

**Comment by YUUBBD** [comment]
Aneesh1122 ban

**Comment by nubesurrealista** [comment]
> Yes, yes, whatever you say, I didn't ask for your opinion either.

Is the dev -.- You demand respect, and you disrespect the dev...

**Comment by YUUBBD** [comment]
It wasn't me who was disrespectful, you came all aggressive to insult me, I just posted that I wasn't doing it and that was it.

**Comment by fast4x** [comment]
> It wasn't me who was disrespectful, you came all aggressive to insult me, I just posted that I wasn't doing it and that was it. 

Stop please, we can help with your request, but with respect.

**Comment by YUUBBD** [comment]
Lo siento fast4x no volveré a publicar acá

**Comment by YUUBBD** [comment]
Sorry fast4x I won't post here again
