### ISSUE TITLE
No puedes descargar ni escuchar canciones que no tengas descargadas

### ISSUE THREAD

**Issue by Nikolas1627** [fast4x/RiMusic#4136]
### Description

No puedes descargar música ni escucharlas, salta el letrero en la parte baja de la pantalla que te avisa "sin conexión" cuando en realidad si tienes conexión, es un error de la aplicación 

### Suggested Solution

.

### Alternatives

.

### Additional Context

.

**Comment by aneesh1122** [comment]
What's the problem with you? Can't you see that there are many issues created already about the same bug?

Developers are already working hard in fixing the bugs. Don't bother them more by creating useless issues.

**Comment by Nikolas1627** [comment]
Me ayudas?
