### ISSUE TITLE
The bug is fixed. Wait for the new release tonight. Don't create unnecessary bug reports.. El error está solucionado. Espere el nuevo lanzamiento esta noche. No cree informes de errores innecesarios.

### ISSUE THREAD

**Issue by aneesh1122** [fast4x/RiMusic#4138]
### Description

.

### Suggested Solution

.

**Comment by aneesh1122** [comment]
https://github.com/user-attachments/assets/3ff1f934-d704-4e77-8044-1dc1e34d284b

**Comment by Soapbosnia** [comment]
Hello there, any news about the "sort by date" bug regarding the "Downloaded" playlist? The issue has been there for months, and it seems like my issue has been ignored.

**Comment by Elevere** [comment]
> Screenrecorder-2024-10-24-22-32-20-274.mp4

Which UI is that? RiMusic or ViMusic?

**Comment by aneesh1122** [comment]
> 
> 
> > Screenrecorder-2024-10-24-22-32-20-274.mp4
> 
> Which UI is that? RiMusic or ViMusic?

It's MiMusic 😂😂

Join telegram group and search for carousel

**Comment by aneesh1122** [comment]
> Hello there, any news about the "sort by date" bug regarding the "Downloaded" playlist? The issue has been there for months, and it seems like my issue has been ignored.

While talking about previous issues you should mention its ticket number

**Comment by Heiromagnus** [comment]
How to fix the bug?

**Comment by Elevere** [comment]
> > > Screenrecorder-2024-10-24-22-32-20-274.mp4
> > 
> > 
> > Which UI is that? RiMusic or ViMusic?
> 
> It's MiMusic 😂😂
> 
> Join telegram group and search for carousel

Lol, thanks for your insight ✌️

**Comment by L3mon-Cat** [comment]
By tonight, which timezone's tonight is it?/

**Comment by ikanakova** [comment]
> By tonight, which timezone's tonight is it?/

Central European Time, I think.

**Comment by nubesurrealista** [comment]
People definitely don't read and have a shitty attitude. They don't even take an active part in the community and they make a circus, what a shame and frustration.

**Comment by SmoothButt** [comment]
Thanks for all your work devs. I don't know how to code but I find it hella interesting how you all work together on such a thing. Don't listen to all those soab who trash talk like you were their dogs, they are dumb asf and were probably educated by brainless shit.
Thanks for your work guys, keep it up 💪👊

**Comment by Soapbosnia** [comment]
> > Hello there, any news about the "sort by date" bug regarding the "Downloaded" playlist? The issue has been there for months, and it seems like my issue has been ignored.
> 
> While talking about previous issues you should mention its ticket number

Really sorry, not too familiar with GitHub, the ticket number is #2178

**Comment by aneesh1122** [comment]
> > > Hello there, any news about the "sort by date" bug regarding the "Downloaded" playlist? The issue has been there for months, and it seems like my issue has been ignored.
> > 
> > While talking about previous issues you should mention its ticket number
> 
> Really sorry, not too familiar with GitHub, the ticket number is #2178 

Fast is busy with something else. I'll ask him if it's possible after he is not occupied with something.

**Comment by SmoothButt** [comment]
> ![Screenshot_2024-10-26-00-15-15-892_com.reddit.frontpage-edit.jpg](https://github.com/user-attachments/assets/26381342-5a62-45bb-9817-6441c89b0e5a)
> 
> @fast4x I agree. These lazy people don't deserve shit

totally understand you all with all the shit mouth but please don't do that I need your app in my life and I don't work in programmation 💀. dw there still are some good guys who love what you do and who aren't spoiled. keep up the good work you all are genius 👍
