### ISSUE TITLE
Couldn't Find A Audio Playback

### ISSUE THREAD

**Issue by Apra-PhobiC** [fast4x/RiMusic#4140]
### Version of RiMusic

0.6.57

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Playback Is Stopped.

**Comment by aneesh1122** [comment]
It's fixed. Close this issue.

**Comment by Apra-PhobiC** [comment]
Now The Problem Is "Song Cannot Be Played"

**Comment by aneesh1122** [comment]
> Now The Issue Is "Song Cannot Be Played"

I'm one of the contributors and I have used the fixed app and I know that it's working. Use your brain and see all the issues created before you and close this issue. I don't know why I had to repeat myself.

**Comment by Apra-PhobiC** [comment]
![Screenshot_2024-10-25-13-10-39-985_it fast4x rimusic](https://github.com/user-attachments/assets/0adedb8c-babe-4d81-9dad-1959a5dbc1df)
Facing This, What Can I Do Now? Installed The Latest Version..

**Comment by aneesh1122** [comment]
> What Can I Do Now?

Do nothing. If you decide to do something you'll end up wasting someone's time 😂

I ain't telling you what to do cuz you won't understand anyways.

**Comment by Arcxngel** [comment]
Podrías intentar explicar y dejar de ser tan engreído, el está pidiendo ayuda

**Comment by Apra-PhobiC** [comment]
> > What Can I Do Now?
> 
> Do nothing. If you decide to do something you'll end up wasting someone's time 😂
> 
> I ain't telling you what to do cuz you won't understand anyways.

If Don't Wanna Help Then Don't,, Why You're Being Rude.. If I Could Understand What You Are Saying, Then Why Should I Seek Help?? Such A Dumbass.. Don't Know How To Explain The Solution..
