### ISSUE TITLE
Error desconocido 

### ISSUE THREAD

**Issue by Dream393** [fast4x/RiMusic#4141]
### Description

Ayúdame a arreglar este problema del error desconocido 

### Suggested Solution

Quiero que me arreglen este problema 😔

### Alternatives

Me está saliendo error desconocido 

### Additional Context

Al momento que abrí la aplicación de RiMusic, entre a mis músicas favoritas que e seleccionado, tengo pocas descargas afuera de la aplicación, el punto esque me aparece ''error desconocido'' lo cual eso me incomoda, no quiero irme a buscar otra aplicación para escuchar mis músicas favoritas 😢

**Comment by aneesh1122** [comment]
Can you read? I've told everyone in both English and Spanish that the bug is fixed. Why did you create a new issue?

You really like wasting time, don't you?

**Comment by Dream393** [comment]
Según tu está solucionado, pero Ami no me sale nada de solucionado, aparte no estoy perdiendo tiempo, solo necesito que me arreglen este problema, te lo tomas a pecho este comentario ¿no?

**Comment by aneesh1122** [comment]
> Según tu está solucionado, pero Ami no me sale nada de solucionado, aparte no estoy perdiendo tiempo, solo necesito que me arreglen este problema, te lo tomas a pecho este comentario ¿no?

I'm one of the contributors and I have the fixed app which you'll get tonight. I know that the problem is fixed

You are wasting everyone's time because this problem has been reported already. Why did you think it was a good idea to report a problem which has been reported countless times already?

**Comment by Dream393** [comment]
Entonces no soy el único que tengo este mismo problema?
Porque Ami me sale error desconocido aún

**Comment by aneesh1122** [comment]
> Entonces no soy el único que tengo este mismo problema?
> Porque Ami me sale error desconocido aún 

Dude. I give up. Do whatever you want. It's like talking to a wall

**Comment by Dream393** [comment]
Pero porque me tratas asi, osea solo quiero que me expliques porque no entiendo muy bien, poreso te digo que no soy el único que está pasando este problema?

**Comment by Jksl22** [comment]
> Pero porque me tratas asi, osea solo quiero que me expliques porque no entiendo muy bien, poreso te digo que no soy el único que está pasando este problema?
> 

1. El problema lo tienen todos.
2. Ya se abrió, varias horas antes, un reporte (issue) sobre este tema. Aun así, varias personas han escrito el mismo reporte sin darse el tiempo de leer los reportes previos. Esto provoca que los desarrolladores pierdan tiempo leyendo un problema repetido.
3. La persona con la que estabas discutiendo previamemte se molestó contigo porque, en un reporte previo de él, ya anunció que solucionó el problema y estará disponible en la próxima actualización. Si te hubieras dado el tiempo de leer te habrias dado cuenta.
