### ISSUE TITLE
[MINOR BUG] Leftover info text in Developers credit part

### ISSUE THREAD

**Issue by betmobil** [fast4x/RiMusic#4142]
### Version of RiMusic

0.57.1 - latest

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on Settings
3. Click on About
4. Scroll down
6. The Developer names are not ordered alphabeticly as it states in subinfo of the section

### What was your expectation?

The names are ordered in mentioned order.

### What more can you tell us? (Optional)

As far as I see it is ordered by number of commits.

**Comment by betmobil** [comment]
A bug is a bug. A bug requires bug report.
If I knew how kotlin works I would fix it myself, but I don't, and for someone who knows it's a 2 minute fix. 
So don't act like this ain't a bug "worthy" of reporting.
Fix it if it's so minor or keep it to yourself.

**Comment by aneesh1122** [comment]
NOOOO...my name will shift to 3rd position if it's arranged in alphabetical order

**Comment by ikanakova** [comment]
I think "In alphabetical order" should be removed and the order left as is.

**Comment by Elevere** [comment]
> A bug is a bug. A bug requires bug report. If I knew how kotlin works I would fix it myself, but I don't, and for someone who knows it's a 2 minute fix. So don't act like this ain't a bug "worthy" of reporting. Fix it if it's so minor or keep it to yourself.

Nah i don't mind about not being in the correct order. In fact, my name is NOT on the list in the app who contributed to translate the app. So what? Why would i bother publishing an issue just because the name is not alphabetically correct?

**Comment by betmobil** [comment]
> > A bug is a bug. A bug requires bug report. If I knew how kotlin works I would fix it myself, but I don't, and for someone who knows it's a 2 minute fix. So don't act like this ain't a bug "worthy" of reporting. Fix it if it's so minor or keep it to yourself.
> 
> Why would i bother publishing an issue just because the name is not alphabetically correct?
>
- First of all if you're not noting wrong things and adding new things with new bugs to the app, that is not called development, just bloating. I can't belive I need to explain that.
- Second, translators are in separeted group to the developera. 

If none of you will say something smart, just don't say it. If you think a **bug** is not worthy of being a **issue**, great for you.

**Comment by aneesh1122** [comment]
It's alright guys. He did say it's a minor bug. It's not like dev has to consider every bug reports and work on it. Let it be

**Comment by Elevere** [comment]
> > > A bug is a bug. A bug requires bug report. If I knew how kotlin works I would fix it myself, but I don't, and for someone who knows it's a 2 minute fix. So don't act like this ain't a bug "worthy" of reporting. Fix it if it's so minor or keep it to yourself.
> > 
> > 
> > Why would i bother publishing an issue just because the name is not alphabetically correct?
> 
> * First of all if you're not noting wrong things and adding new things with new bugs to the app, that is not called development, just bloating. I can't belive I need to explain that.
> * Second, translators are in separeted group to the developera.
> 
> If none of you will say something smart, just don't say it. If you think a **bug** is not worthy of being an **issue**, great for you.

Fine.

**Comment by fast4x** [comment]
Order is in commit number, I'll change it in alphabetical order

**Comment by fast4x** [comment]
Fixed
