### ISSUE TITLE
Music not Playing

### ISSUE THREAD

**Issue by Rocky696** [fast4x/RiMusic#4143]
### Version of RiMusic

0.6.57.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on music
3. Then I got a yellow notification saying "Song cannot be played"
![Screenshot_20241025_091245](https://github.com/user-attachments/assets/b966cd53-d810-4b12-96fe-f91eba70caed)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I clicked next song and happened the same problem

**Comment by aneesh1122** [comment]
![Screenshot_2024-10-25-14-22-19-033_com.github.android-edit.jpg](https://github.com/user-attachments/assets/765b8315-dbdc-40b7-8ea1-bcae4b2456a9)

Smh 🤦

**Comment by Rocky696** [comment]
Sorry bro I saw your post but I didn't know that my issue was similar. Thanks

**Comment by aneesh1122** [comment]
> Sorry bro I saw your post but I didn't know that my issue was similar. Thanks 

So...close the issue?
