### ISSUE TITLE
No se reproducen los medios / no descarga

### ISSUE THREAD

**Issue by Killer7420** [fast4x/RiMusic#4145]
### Version of RiMusic

0.6.56

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on any music
3. Error, and no download
4. Again and again

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

 Una reproducción normal 

### What more can you tell us? (Optional)

Siempre reproducía sin problemas la música. Ahora no reproduce nada ni descarga. Es raro

**Comment by isjustlucas** [comment]
me too

**Comment by nomenamecom** [comment]
I have the same problem 
This is the message. It happens with a lot of songs, lists...and it stops after a few songs. It's complicated to listen 5 songs continuously

Thanks!

![Uploading Screenshot_2024-10-25-15-27-43-391_it.fast4x.rimusic.jpg…]()

**Comment by Donald-Win** [comment]
https://github.com/fast4x/RiMusic/issues/4124#issue-2612571166

Thanks to you other three for not opening a new issue.
