### ISSUE TITLE
Entra a la aplicación Rimusic y cuando quiero escuchar una música me sale un mensaje abajo que dice media cannot be played

### ISSUE THREAD

**Issue by Sbd-0** [fast4x/RiMusic#4146]
### Version of RiMusic

0.6.57.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1 The problem that the Rimusic application gives me is that it does not let me play the songs. 2 media cannot be played.

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I want you to fix my problem and that would be very satisfying

### What more can you tell us? (Optional)

No, there's nothing, that's all. It's the only problem I have that doesn't let me play the songs.

**Comment by Sbd-0** [comment]
I want you to fix the problem I have in the Rimusic application with the message that says media cannot be played

**Comment by nubesurrealista** [comment]
Delete this bullshit. Unnecessary

**Comment by aneesh1122** [comment]
> I want you to fix the problem I have in the Rimusic application with the message that says media cannot be played 

No. The dev is lazy like you. He won't fix your problem. Go learn coding and fix it yourself

**Comment by Donald-Win** [comment]
https://github.com/fast4x/RiMusic/issues/4124#issue-2612571166
