### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by wunder20v** [fast4x/RiMusic#415]
### Steps to reproduce the bug

![Screenshot_2024-01-15-13-00-14-11_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/156642707/e9cbfc03-e84e-412f-9ad5-bfb7339f4f5c)

### Expected behavior

It should be german

### Actual behavior

It Is english 

### RiMusic version

0.6.17

### Android version

Android 13

**Comment by fast4x** [comment]
Hello, it is not a bug, it depends on the translation made by the collaborator. If it is not updated well, you can fix it on Crowdin and become a collaborator of the project.

[Go to Crowdin translation page](https://crowdin.com/project/rimusic)
