### ISSUE TITLE
Je propose mon aide pour résoudre l'erreur inconnue 

### ISSUE THREAD

**Issue by evsdroid** [fast4x/RiMusic#4151]
### Version of RiMusic

0.6.57.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Écouter la musique 
3. Erreur inconnue 
Le problème c'est bien Youtube qui bloque 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

J'aimerais apporter mon aide pour résoudre le problème 

### What more can you tell us? (Optional)

Comme beaucoup de monde plus possible d'écouter a cause d'une erreur inconnue il s'agit bien de Youtube qui vous bloque.

Si je fait dans les option écouter avec.. et que je sélectionne Youtube ou YouTube  Music il ouvre la musique dans Youtube ou YouTube Music et cela fonctionne. Le problème c'est seulement quand on lit avec le flux audio a partir de l'application RiMusic.

Je vais essayer de mon côté de voir qu'est ce qui bloque (lien périmé, problème d'authentification sur Youtube ou YouTube Music, ou bien autre chose)

Merci beaucoup pour cette application

**Comment by Donald-Win** [comment]
https://github.com/fast4x/RiMusic/issues/4124#issue-2612571166

**Comment by sebastienfi** [comment]
Same here.
