### ISSUE TITLE
No se descargan ni se reproducen las canciones 

### ISSUE THREAD

**Issue by Sebarawin** [fast4x/RiMusic#4152]
### Version of RiMusic

0.6.47.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Trato de oír o descargar músicas y no se reproducen 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need t

Uploading VID_20241025_132054.mp4…

### What was your expectation?

Poder descargar mi música

**Comment by Donald-Win** [comment]
https://github.com/fast4x/RiMusic/issues/4124#issue-2612571166
