### ISSUE TITLE
I'm trying to download songs, but it won't download

### ISSUE THREAD

**Issue by Someoneoutrfsk** [fast4x/RiMusic#4154]
### Version of RiMusic

0.6.57.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on the download button
3. Wait a little 
4. The notification " Download failed" appear and I can't download the music.

### Submit a video

I've recorded a video, but my GitHub isn't letting me post.

### What was your expectation?

To download the music

**Comment by Donald-Win** [comment]
https://github.com/fast4x/RiMusic/issues/4124#issue-2612571166

**Comment by Someoneoutrfsk** [comment]
> [#4124 (comment)](https://github.com/fast4x/RiMusic/issues/4124#issue-2612571166)

I'm sorry, I didn't knew, I was just having a problem and wanted it to be solved, no need to call us that want to have the bug fixed "idiots" I've seen ur comment, so I'm sorry, I didn't knew, and sorry to all developers.

**Comment by aneesh1122** [comment]
> > [#4124 (comment)](https://github.com/fast4x/RiMusic/issues/4124#issue-2612571166)
> 
> I'm sorry, I didn't knew, I was just having a problem and wanted it to be solved, no need to call us that want to have the bug fixed "idiots" I've seen ur comment, so I'm sorry, I didn't knew, and sorry to all developers.

Didn't you see other bug reports before creating yours?

The one who wants bugs solved ain't idiots but people who see that the bug is already reported and they report the same bug anyways are idiots for sure.

**Comment by Someoneoutrfsk** [comment]
Tô bem honest, I really haven't seen it before I've put the issue, I'm sorry.
