### ISSUE TITLE
The songs don't play 

### ISSUE THREAD

**Issue by rmglsnts** [fast4x/RiMusic#4155]
### Version of RiMusic

0.6.57.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Search for a song
3. Don't play
4. Get an error message 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

It suppose to play the song.

**Comment by Donald-Win** [comment]
https://github.com/fast4x/RiMusic/issues/4124#issue-2612571166

**Comment by aneesh1122** [comment]
Are you dumb? Can't you see that the bug is reported already? Are you too lazy to see the same bug has been reported a couple of times already?

**Comment by KeknanXD** [comment]
aneesh you are being a ginormous asshole take it easy
