### ISSUE TITLE
No se reproduce

### ISSUE THREAD

**Issue by Noeliiarp26** [fast4x/RiMusic#4156]
### Version of RiMusic

0.6.57.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Antes me iba perfecto pero ya no se me reproduce nada. Pasa igual en mi otro móvil. No se cómo se borra la actualización actual para probar la anterior, ya que en ella si me iba.

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

J

### What more can you tell us? (Optional)

Intentad arreglarlo por favor. Volver a Spotify con todos los anuncios de nuevo sería horrible.

**Comment by Noeliiarp26** [comment]
No había visto que a todo el mundo le pasaba lo mismo. Perdón por comentar otro bug🙏🏻

**Comment by aneesh1122** [comment]
¿puedes leer? ¿No ves que el error ya ha sido reportado un par de veces? la gente como tu realmente no merece nada

**Comment by Noeliiarp26** [comment]
Lee tú también tio

**Comment by GurrenLagann114** [comment]
English guys, english

**Comment by woskkdmsosid** [comment]
> English guys, english

dont care about that theyre randomly fighting uhh

**Comment by Josue883** [comment]
No me deja escuchar musica
