### ISSUE TITLE
Tracks get removed from favourites on play

### ISSUE THREAD

**Issue by Ehiffi** [fast4x/RiMusic#4160]
### Version of RiMusic

latest

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on favourite track
3. Boom its no longer favourite

### Submit a video

https://github.com/user-attachments/assets/7ba2cd19-98b3-4c15-9844-eb344f70422f

### What was your expectation?

App should not remove tracks from favourites for no reason I guess

**Comment by Nuibance** [comment]
It's doing that with cached and all songs

**Comment by Ehiffi** [comment]
Well that behaviour wasn't present in previous versions, so why only now it works lite this. Or its how it should behave?

**Comment by Nuibance** [comment]
If you play it long enough it should come back. Happened with me

**Comment by Ehiffi** [comment]
> If you play it long enough it should come back. Happened with me
Nope, doesn't do that

**Comment by Ehiffi** [comment]
Well that behaviour wasn't present in previous versions, so why only now it works lite this. Or its how it should behave?

**Comment by Ehiffi** [comment]
I actually found out it removes every track you play, even if its in all category

**Comment by Ehiffi** [comment]
https://github.com/user-attachments/assets/5d4038f2-8369-4372-9f80-b38ee60397da

**Comment by FDJfunktionar** [comment]
I'm having this happen as well.

**Comment by Nighty360** [comment]
me too

**Comment by XGhostRX** [comment]
The same thing happens to me even in the ones I listen to. 
Even the change of song when swiping left from there doesn't even work.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.58.1
