### ISSUE TITLE
Whenever i try to listen to a song it just says. Logging in is required to listen to this song. (without login)

### ISSUE THREAD

**Issue by Julian1535** [fast4x/RiMusic#4162]
### Version of RiMusic

Newest one

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1 play on sight by kanye west

### Submit a video

![Screenshot_20241025_153220](https://github.com/user-attachments/assets/8d675bb2-c6d9-42a1-a095-56ba370a7016)

### What was your expectation?

.

### What more can you tell us? (Optional)

.

### Logs (Optional)

.

**Comment by Reizaru404** [comment]
Starting with this version, you need to log in to your YTMusic account to listen to any songs. You can do this in the settings in the "other" section.
P.s.: This was written in the update description.

**Comment by i00** [comment]
It is a bug.. Because I click the log on button in the settings, log in to my google account, and it just takes me to the YouTube page with me signed in in your in app browser.. It never registers in the app that I actually logged on (I have even restarted my phone), and then when I click on the log in button, it just takes me to my already signed in page to select a YT profile linked to my account.. Maybe this is a bug with your program if you have multiple YT profiles?

**Comment by isantamaria80** [comment]
I confirm, the login does not work

**Comment by milesmcclane** [comment]
> This is not a bug! Starting with this version, you need to log in to your YTMusic account to listen to any songs. You can do this in the settings in the "other" section. P.s.: This was written in the update description.

I do t have a ytmusic account. Is this now necessary? I’m signed in to my piped account and I’m seeing the same issues.

**Comment by jfmcbrayer** [comment]
Requiring a login should be considered a regression, if not a bug. Consider only using the YTM API for browsing and use NewPipeExtractor for play/download.

**Comment by milesmcclane** [comment]
Needing to create and log in to a Google account to use this app completely defies the point of the app for me. I hope a solution can be found. 

> Requiring a login should be considered a regression, if not a bug. Consider only using the YTM API for browsing and use NewPipeExtractor for play/download.

**Comment by aneesh1122** [comment]
> It is a bug.. Because I click the log on button in the settings, log in to my google account, and it just takes me to the YouTube page with me signed in in your in app browser.. It never registers in the app that I actually logged on (I have even restarted my phone), and then when I click on the log in button, it just takes me to my already signed in page to select a YT profile linked to my account.. Maybe this is a bug with your program if you have multiple YT profiles?

After login, do this
1) search in the search bar "music.youtube.com"
2) open the first video
3) open the description
4) open YouTube music link
5) after the YouTube music page opens, close the app from taskbar

**Comment by aneesh1122** [comment]
> Requiring a login should be considered a regression, if not a bug. Consider only using the YTM API for browsing and use NewPipeExtractor for play/download.

This is the only solution now. You can only wait for the non-login fix to come if there is any.

**Comment by TuDigitadorPorUnDiaPIPIPI** [comment]
You just have to follow the steps and after that there is no other problem, nor is it something out of this world to log in.

**Comment by anselmotrejo** [comment]
For now, just follow the steps listen.

**Comment by NolanGames0** [comment]
I updated and followed all steps and it is still not playing songs.

**Comment by jfmcbrayer** [comment]
> This is the only solution now. You can only wait for the non-login fix to come if there is any.

Yes, I realize this is the solution that was chosen, and that a correct solution would take more time. That's why I am pointing in the general direction of a correct solution.

**Comment by milesmcclane** [comment]
> You just have to follow the steps and after that there is no other problem, nor is it something out of this world to log in.

I imagine a large amount of people are like me, and use privacy focussed front end apps like this  precisely to _avoid_ having to sign in to companies like Google. I dont have a Google account to sign in with even if I wanted to. 
It may not be ‘something out of this world’ for you - but it will be the end of the app for many.

**Comment by mimi519** [comment]
> ### Versión de RiMusic
> El más nuevo
> 
> ### Versión para Android
> 7.0
> 
> ### He hecho esto:
> * [x]  Desinstalar la compilación anterior antes de instalar una nueva
> * [x]  Comprobado problemas de apertura acerca de mi problema similar
> 
> ### Cuéntanos cómo desencadenas este error
> 1 juego a la vista por kanye west
> 
> ### Presentar un vídeo
> ![Screenshot_20241025_153220](https://private-user-images.githubusercontent.com/155791102/380331119-8d675bb2-c6d9-42a1-a095-56ba370a7016.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDA2NjQsIm5iZiI6MTcyOTk0MDM2NCwicGF0aCI6Ii8xNTU3OTExMDIvMzgwMzMxMTE5LThkNjc1YmIyLWM2ZDktNDJhMS1hMDk1LTU2YmEzNzBhNzAxNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMDU5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjNlZDAwYjc4NDEzZjVkNjA1MmQ5YzE0MTJhYjlmY2Q4YmU2YmNjZTcxZDJjYjE0ZDQ1Y2EzYzVjODE0YTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.V5x6pQM2Wr8KgF9LH6R6c7JL2TPbid9EPV68m5j8d2s)
> 
> ### ¿Cuál era su expectativa?
> .
> 
> ### ¿Qué más nos puedes decir? (Opcional)
> .
> 
> ### Registros (opcional)
> .
si hay que iniciar sesión en otra app para que quiero esta app, ya me pondría la otra y me ocupa menos. lo bueno de rimusic era no tener que iniciar sesión ni dar informacion, entre comillas claro.

**Comment by mimi519** [comment]
> > Es un bicho.. Debido a que hago clic en el botón de inicio de sesión en la configuración, iniciar sesión en mi cuenta de Google, y solo me lleva a la página YouTube conmigo iniciado sesión en su navegador en la aplicación.. Nunca se registra en la aplicación en la que realmente he iniciado sesión (incluso he reiniciado mi teléfono), y luego cuando hago clic en el botón de inicio de sesión, solo me lleva a mi página ya iniciada para seleccionar un perfil YT vinculado a mi cuenta.. Tal vez esto es un error con su programa si usted tiene múltiples perfiles YT?
> 
> Después de iniciar sesión, haga esto
> 
> 1. buscar en la barra de búsqueda "music.youtube.com"
> 2. abrir el primer vídeo
> 3. abrir la descripción
> 4. abrir enlace de música YouTube
> 5. después de que se abra la página de música del YouTube cierre la aplicación desde la barra de tareas

yo no tengo crome, y el móvil me dice que para ello el crome, de verdad estamos en un código abierto para evitar Google y compañía y la solución es poner más cosas de Google?

**Comment by chriskangr** [comment]
for me it's just a matter of ownership and not payment and that's why I chose this great app. I'm sad now that I can't use it and I already went to another app. Anyway thanks to fast4x and the participants for their offer. I'll be around and if anything changes I'll be happy to come back here. For now I'm looking ways to convert my playlists to put them in a good app.

**Comment by fast4x** [comment]
Download latest version please.

**Comment by chriskangr** [comment]
That`s it BRAVISSIMO **fast4x** !!!

**Comment by fast4x** [comment]
Thanks

**Comment by milesmcclane** [comment]
> Download latest version please.

Fantastic. Thanks!

**Comment by mimi519** [comment]
ya la baje, y todo okMIGUELI -------- Mensaje original --------De: milesmcclane ***@***.***>Fecha: sáb., 2 nov. 2024 11:10Para: fast4x/RiMusic ***@***.***>Cc: mimi519 ***@***.***>, Comment ***@***.***>Asunto: Re: [fast4x/RiMusic] Whenever i try to listen to a song it just says. Logging in is required to listen to this song. (without login) (Issue #4162)

Download latest version please.

Fantastic. Thanks!

**Comment by bodyky** [comment]
There is a fix for those whose login doesn't work, as it previously didn't for me also. If you have a second profile on your account, then you should remove the second one, as the app cannot select automatically the default account. 

I had a main google account, and set up a secondary one a while back. I removed the secondary one and then used the login function and now RiMusic works as intended.
