### ISSUE TITLE
Las canciones no comienzan

### ISSUE THREAD

**Issue by AyFyB14** [fast4x/RiMusic#4163]
### Version of RiMusic

0.6.44

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abri RiMusic
2. Le di para que comiencen las canciones
3. Ninguna de las canciones suena

### Submit a video

>

https://github.com/user-attachments/assets/ad9588a7-8f07-4696-8119-42e7fe997166

### What was your expectation?

Pensaba q era un error de mi móvil, pero después de reiniciar el móvil seguía sin funcionar,.

**Comment by fast4x** [comment]
download latest

**Comment by AyFyB14** [comment]
Como hago eso
