### ISSUE TITLE
[Feature]: without login 

### ISSUE THREAD

**Issue by ThaMasEagle** [fast4x/RiMusic#4164]
### Description

Hey @fast4x  love your app too much. So I was looking apps like ones like Forked from vimusic all bypass the required login from like Vitune, maybe If you can look in that. I feel like people love this app because you don't require any login and Customization. 

### Suggested Solution

Look in to forked from vimusic apps like yours, like Vitune that some how it works without login

**Comment by fast4x** [comment]
Hi, I'll look into code, considering that also this way would be blocked soon. Dev say that is experimental for this motivation i think.

**Comment by offbeat-stuff** [comment]
new pipe and yt-dlp didnot require an update so why does this app require one?

**Comment by fast4x** [comment]
Implemented, available from version 0.6.58.1

**Comment by ALMIGHTY-VC** [comment]
Can we atleast login using microg??

**Comment by fast4x** [comment]
I don't know now, I'll check it next time
