### ISSUE TITLE
Album Art is getting cut off on an 8-inch tablet.

### ISSUE THREAD

**Issue by ogjapaw** [fast4x/RiMusic#4165]
### Version of RiMusic

0.6.58

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Play a Song

### Submit a video

![Screenshot_2024-10-26-06-14-07-278_it fast4x rimusic](https://github.com/user-attachments/assets/a05f0ea1-44d7-462a-947e-a36ad5147d3f)
![Screenshot_2024-10-26-06-18-19-547_it fast4x rimusic](https://github.com/user-attachments/assets/5a7963d2-1989-4b09-af98-a89bfc91e3c7)

### What was your expectation?

symmetrical square

### What more can you tell us? (Optional)

no change even thumbnail size is reduced. enabling fading edge setting compensate for this bug.

**Comment by OrangeZXZ** [comment]
Does this issue happen on both types of thumbnails?

**Comment by ogjapaw** [comment]
> Does this issue happen on both types of thumbnails?

yes both in Modern Thumbnail and Essential Thumbnail.

but this issues is only for setting the Player Type to Modern.
for Essential Player Type it is normal.

**Comment by aneesh1122** [comment]
Can you try the latest version?

**Comment by ogjapaw** [comment]
> Can you try the latest version?

![Screenshot_2024-12-24-02-08-01-855_it fast4x rimusic](https://github.com/user-attachments/assets/e412686e-e085-4449-b98a-0b199c1d21a6)

it is now fixed
