### ISSUE TITLE
Favorites kinda broken

### ISSUE THREAD

**Issue by Wasabiiiiiii** [fast4x/RiMusic#4169]
### Version of RiMusic

0.6.58

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

open Rimusic
favorite any song
go to favorites
click on song 
song disappears in favorites despite you favoriting it

### Submit a video

https://github.com/user-attachments/assets/a0fcfbc0-67d3-4062-931f-d515135ec238

### What was your expectation?

i expected the favorites to work, idk what exactly you're asking 

### What more can you tell us? (Optional)

refavoriting the song brings it back but tapping on the song to play it just makes it disappear instead of keeping it in the favorites

**Comment by Nuibance** [comment]
#4160 duplicate

**Comment by fast4x** [comment]
yep

**Comment by fast4x** [comment]
Fixed, available from version 0.6.58.1
