### ISSUE TITLE
The playlist export doesn't work, I don't know why, and YouTube doesn't let me play songs either, even if I'm using my account.

### ISSUE THREAD

**Issue by TkJess0987** [fast4x/RiMusic#4170]
### Version of RiMusic

0.6.58

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

> 

### What was your expectation?

That everything will work fine as before 🥲

### What more can you tell us? (Optional)

:(

### Logs (Optional)

:(

**Comment by Nuibance** [comment]
#4160 duplicate

**Comment by Lllum** [comment]
I had the same issue, but force stopping the app fixed it, maybe try doing that

**Comment by fast4x** [comment]
Do what say @Lllum
