### ISSUE TITLE
Malfunctioning application 

### ISSUE THREAD

**Issue by Jhonsilva953** [fast4x/RiMusic#4171]
### Version of RiMusic

0.6.571.v

### Android version

7.1 - 7.1.2

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

The application is stopping working, out of nowhere my songs don't start and freeze, and all the songs I try to download stop working and always give an error, the download fails and the other songs stop,Several songs are no longer playing 

### Submit a video

![Screenshot_2024-10-25-21-36-03-017_com mi android globallauncher-edit](https://github.com/user-attachments/assets/96b8cd19-f9db-4a81-a5eb-d80f534e8505)
![Screenshot_2024-10-25-16-05-01-287_it fast4x rimusic-edit](https://github.com/user-attachments/assets/0a8af47d-4dd3-42f5-a8a0-90e3a32426f7)

### What was your expectation?

I wish it would happen this week, I'm really addicted to this app and I can't live without it.

**Comment by fast4x** [comment]
download latest
