### ISSUE TITLE
Add a workaround for playing songs that doesn't require logging in to YTM

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#4172]
ViTune also faced this issue. Here's how it was fixed:  https://github.com/25huizengek1/ViTune/issues/499

Is it possible to implement such a solution in RiMusic? Many of us don't wish to login to google services) don't have google accounts for privacy reasons

**Comment by fast4x** [comment]
work in progress

**Comment by looowizz** [comment]
Would it be possible to implement something similar to Aurora Store's anonymous google accounts? Just an idea :P

**Comment by JeePopuwu** [comment]
Many people like the YouTube account

**Comment by fast4x** [comment]
Implemented, available from version 0.6.58.1

**Comment by privacyfreak84** [comment]
Hmm, still doesn't work
