### ISSUE TITLE
I dont find YTM login

### ISSUE THREAD

**Issue by Kanelera** [fast4x/RiMusic#4173]
### Version of RiMusic

0.6.58

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Dont find YTM login
3. Cant listen music
4. Sad :(

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

.

### What more can you tell us? (Optional)

So i think dumb persons like me need tutorials for new updates and how it works it will be so pro if you do that :p

**Comment by Nuibance** [comment]
Setting and go to data

**Comment by Kanelera** [comment]
> Setting and go to data

I dont find it :(

**Comment by Alis0312** [comment]
> > Setting and go to data
> 
> I dont find it :(

On the screen that appears as soon as you enter, look for the three-line icon at the top right corner and select the last option, "Settings." Inside, go to the "Miscellaneous" menu, and you'll find the option to log in.

**Comment by julianM2000** [comment]
> > > Configuración y acceso a datos
> > 
> > 
> > No lo encuentro :(
> 
> En la pantalla que aparece nada más entrar, busca el icono de tres líneas en la esquina superior derecha y selecciona la última opción, “Configuración”. Dentro, ve al menú “Miscelánea” y encontrarás la opción para iniciar sesión.

Yo instalé la nueva versión pero el botón desapareció de confirmación [
![IMG-20241026-WA0002](https://github.com/user-attachments/assets/2ddcad77-48a4-431f-8ac3-fd6ba7211cdb)

**Comment by mimi519** [comment]
> > > Configuración e ir a datos
> > 
> > 
> > No lo encuentro :(
> 
> En la pantalla que aparece tan pronto como entras, busca el icono de tres líneas en la esquina superior derecha y selecciona la última opción, "Configuración". En el interior, ve al menú "Misceláneo", y encontrarás la opción de iniciar sesión.

no funciona, lo hice y entre y no sirve, además que no entiendo que haya que entrar en otra aplicación que hace lo mismo, para eso directamente lo hago todo en YouTube

**Comment by Kanelera** [comment]
I dont find the Miscellaneous settingsss

**Comment by Kanelera** [comment]
OK i find it im.dumb XDDD sorry and thankyou
