### ISSUE TITLE
Whenever i try to play any song that i dont have added to my playlist it just says cannot play due to server restrictions

### ISSUE THREAD

**Issue by Julian1535** [fast4x/RiMusic#4174]
### Version of RiMusic

.

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

.

### What more can you tell us? (Optional)

![Screenshot_20241025_193811](https://github.com/user-attachments/assets/9165938b-9f64-4693-9a14-e604fa098b14)

**Comment by Cresh680** [comment]
I was getting that and then tried the log into to youtube music through the app and it just provides a black screen. 
![Screenshot_20241025_205516](https://github.com/user-attachments/assets/71062642-777f-4c64-b501-d927e282031b)

**Comment by JoshGMR** [comment]
I logged in after several attempts and it still didn't let me play the music.

**Comment by fast4x** [comment]
yt work in your country?

**Comment by JoshGMR** [comment]
Yeah

**Comment by fast4x** [comment]
wait next version
