### ISSUE TITLE
NO PUEDO ESCUCHAR NADA 

### ISSUE THREAD

**Issue by thecat840** [fast4x/RiMusic#4175]
### Version of RiMusic

0.6.58

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click Any song without downloading
3. It tells me I need to log in to continue 
4. Login with YouTube 
5. I restart the app and it asks me to log in again 
>

### What was your expectation?

Being able to listen to my music

**Comment by fast4x** [comment]
login yt from miscellaneous settings
