### ISSUE TITLE
Short and concise description of your bug

### ISSUE THREAD

**Issue by Oxma27** [fast4x/RiMusic#4176]
### Version of RiMusic

0.57.1 

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

Uploading Screenrecorder-2024-10-25-21-27-00-262.mp4…

### What was your expectation?

Que se pudiera escuchar música, pero sigue igual 

### What more can you tell us? (Optional)

No se puede escuchar música desde hace una semana, porfavor arreglen este bug rápido 

### Logs (Optional)

Media cannot be played

**Comment by fast4x** [comment]
download latest
