### ISSUE TITLE
Error con las canciones en favoritos

### ISSUE THREAD

**Issue by Nico-2220** [fast4x/RiMusic#4178]
### Version of RiMusic

0.6.58

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Obviamente espere que el problema se solucionará pero al volver a la última versión seguía igual, el problema es que en la versión anterior a la 0.6.58 cuando selecciono una canción que no tengo descargada no puedo escucharla y al actualizarla en la versión 0.6.58 al seleccionar una canción guardada en favoritos la aplicación quita la canción seleccionada de favoritos

**Comment by fast4x** [comment]
yep

**Comment by fast4x** [comment]
Fixed, available from version 0.6.58.1
