### ISSUE TITLE
Short and concise description of your bug

### ISSUE THREAD

**Issue by JoshGMR** [fast4x/RiMusic#4181]
### Version of RiMusic

0.6.58

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
3. Find a new song (outside my playlist)
4. I started it 
5. I get a playback error and it asks me to log in with yt music
6. Home section on yt music
7. It keeps giving me the error "media cannot be played"

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Being able to listen to songs outside of my playlist 

### What more can you tell us? (Optional)

I chose a new song and it wouldn't let me play it, then I searched for other random songs and it wouldn't let me play either, it only lets me play the downloaded songs and the yt music login interface not very intuitive

**Comment by fast4x** [comment]
login it's mandatory read release note 0.6.58

**Comment by JoshGMR** [comment]
I did it before all

**Comment by fast4x** [comment]
wait next version
