### ISSUE TITLE
[Feature]: Login with other apps

### ISSUE THREAD

**Issue by JoshGMR** [fast4x/RiMusic#4182]
### Description

I would like to be able to log in with my Spotify because I use it more than yt music and my playlists are on it, or at least be able to skip the playlists.

### Suggested Solution

A section similar to that of yt music with a login with Spotify even if only for the transfer of the playlists

**Comment by aneesh1122** [comment]
What's easier?

1) transferring songs from Spotify to yt yourself and then importing to RiMusic

Or

2) developer adding Spotify support?

Just because yt login was implemented doesn't mean every type of login will be implemented. There was a strong reason for yt login.
