### ISSUE TITLE
I can't login to YouTube music

### ISSUE THREAD

**Issue by DuckyMcLucky** [fast4x/RiMusic#4183]
### Version of RiMusic

0.6.58

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Press on settings
3. Press on misc
4. Press login
5. Login on opened window
6. Close and restart rimusic
7. Open rimusic again
8. Try playing music, doesn't work because I'm not logged in

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically.

[](https://github.com/user-attachments/assets/cc6ee901-d42e-44af-8c92-984e940c5227)

### What was your expectation?

I expected to be able to play music

### What more can you tell us? (Optional)

Maybe it doesn't work because YouTube opens? Idk mqn

**Comment by L3mon-Cat** [comment]
Mine works normally, try to delete youtube using ADB and UDT.

**Comment by DuckyMcLucky** [comment]
> Mine works normally, try to delete youtube using ADB and UDT.

I have no idea what ADB or UDT are, please tell me what they are

**Comment by L3mon-Cat** [comment]
> > Mine works normally, try to delete youtube using ADB and UDT.
> 
> I have no idea what ADB or UDT are, please tell me what they are
In simple terms they are things that can delete in built system applications without rooting the phone. Just try disabling youtube, no need to do all this.

**Comment by DuckyMcLucky** [comment]
> > > Mine works normally, try to delete youtube using ADB and UDT.
> > 
> > 
> > I have no idea what ADB or UDT are, please tell me what they are
> > In simple terms they are things that can delete in built system applications without rooting the phone. Just try disabling youtube, no need to do all this.

I've already tried disabling the app, it doesn't seem to do anything
Also just wondering, is it supposed to open YouTube music when you press login?

**Comment by aswindk** [comment]
> ### Version of RiMusic
> 0.6.58
> 
> ### Android version
> 14
> 
> ### I've done these:
> * [x]  Uninstall old build before installing a new one
> * [x]  Checked opening issues about my similar problem
> 
> ### Tell us how you trigger this bug
> 1. Open RiMusic
> 2. Press on settings
> 3. Press on misc
> 4. Press login
> 5. Login on opened window
> 6. Close and restart rimusic
> 7. Open rimusic again
> 8. Try playing music, doesn't work because I'm not logged in
> 
> ### Submit a video
> If you are on Android, please download a screen recorder and record your screen while you duplicating the problem as describe above.
> 
> > You may need to use Github App to be able to upload video - size limit is 10 MB.
> 
> If you are on Desktop, drag video into this box and it will be uploaded automatically.
> 
>  1000000063.mp4 
> ### What was your expectation?
> I expected to be able to play music
> 
> ### What more can you tell us? (Optional)
> Maybe it doesn't work because YouTube opens? Idk mqn
> 
> ### Logs (Optional)
> _No response_

Try Force stopping the app and re-open again..mine worked that way

**Comment by aswindk** [comment]
> ### Version of RiMusic
> 0.6.58
> 
> ### Android version
> 14
> 
> ### I've done these:
> * [x]  Uninstall old build before installing a new one
> * [x]  Checked opening issues about my similar problem
> 
> ### Tell us how you trigger this bug
> 1. Open RiMusic
> 2. Press on settings
> 3. Press on misc
> 4. Press login
> 5. Login on opened window
> 6. Close and restart rimusic
> 7. Open rimusic again
> 8. Try playing music, doesn't work because I'm not logged in
> 
> ### Submit a video
> If you are on Android, please download a screen recorder and record your screen while you duplicating the problem as describe above.
> 
> > You may need to use Github App to be able to upload video - size limit is 10 MB.
> 
> If you are on Desktop, drag video into this box and it will be uploaded automatically.
> 
>  1000000063.mp4 
> ### What was your expectation?
> I expected to be able to play music
> 
> ### What more can you tell us? (Optional)
> Maybe it doesn't work because YouTube opens? Idk mqn
> 
> ### Logs (Optional)
> _No response_

Open app info and Force stop the app. Open again. This worked for me

**Comment by knighthat** [comment]
you can press back twice in home screen to force quit. (it's my implementation 😉)

**Comment by DuckyMcLucky** [comment]
> > ### Version of RiMusic
> > 0.6.58
> > ### Android version
> > 14
> > ### I've done these:
> > 
> > * [x]   Uninstall old build before installing a new one
> > * [x]   Checked opening issues about my similar problem
> > 
> > ### Tell us how you trigger this bug
> > 
> > 1. Open RiMusic
> > 2. Press on settings
> > 3. Press on misc
> > 4. Press login
> > 5. Login on opened window
> > 6. Close and restart rimusic
> > 7. Open rimusic again
> > 8. Try playing music, doesn't work because I'm not logged in
> > 
> > ### Submit a video
> > If you are on Android, please download a screen recorder and record your screen while you duplicating the problem as describe above.
> > > You may need to use Github App to be able to upload video - size limit is 10 MB.
> > 
> > 
> > If you are on Desktop, drag video into this box and it will be uploaded automatically.
> > 1000000063.mp4
> > ### What was your expectation?
> > I expected to be able to play music
> > ### What more can you tell us? (Optional)
> > Maybe it doesn't work because YouTube opens? Idk mqn
> > ### Logs (Optional)
> > _No response_
> 
> Open app info and Force stop the app. Open again. This worked for me

tried this, did not work
thanks for taking the time to reply, though
