### ISSUE TITLE
Every time I go to a music the application tells me this song cannot be played due to server restrictions and you need to start the section to listen to this content

### ISSUE THREAD

**Issue by Kappaclyms** [fast4x/RiMusic#4185]
### Version of RiMusic

0.6.58d

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens
5. 
![Screenshot_2024-10-26-00-24-05](https://github.com/user-attachments/assets/fe1a1e20-748d-4ae3-af61-f125afb4447d)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Nose

### What more can you tell us? (Optional)

Haaaa

**Comment by senolfndk** [comment]
Same problem

**Comment by senolfndk** [comment]
Same problem

**Comment by fast4x** [comment]
other songs play?
