### ISSUE TITLE
Without music

### ISSUE THREAD

**Issue by Hernan13XD** [fast4x/RiMusic#4186]
### Version of RiMusic

0.6.57.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open rimusic 
2. Search for a song 
3. Play the song 
4. Error

### What was your expectation?

That I could listen to my music or download it and listen 

### What more can you tell us? (Optional)

It doesn't let me listen to any music

**Comment by fast4x** [comment]
download latest

**Comment by Hernan13XD** [comment]
> Descargar la última versión

Siempre actualizo al app y nada
