### ISSUE TITLE
No me aparece el botón de configuración 

### ISSUE THREAD

**Issue by julianM2000** [fast4x/RiMusic#4187]
### Version of RiMusic

Última versión 

### Android version

13

### I've done these:

- [ ] Uninstall old build before installing a new one
- [ ] Checked opening issues about my similar problem

### Tell us how you trigger this bug

No me aparece el botón de configuración  ayuda
![IMG-20241026-WA0002](https://github.com/user-attachments/assets/cb7950fe-ed1a-4d61-9b4a-9d4039642ebe)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically
![IMG-20241026-WA0002](https://github.com/user-attachments/assets/6eb244c8-36a9-4d9d-bcaf-025cdcbb88fa)

### What was your expectation?

:c

### What more can you tell us? (Optional)

.

### Logs (Optional)

..

**Comment by fast4x** [comment]
You don't have top bar

**Comment by julianM2000** [comment]
> No tienes barra superior

Y como lo soluciono o como entro a configuración? :c no quiero perder mis playlist

**Comment by fast4x** [comment]
I prepare a custom version for you, i hope solve. Your configuration it's corrupted.
