### ISSUE TITLE
No reproduce la música 

### ISSUE THREAD

**Issue by juanct-sudo** [fast4x/RiMusic#4188]
### Description

Cuando busco una canción no se reproduce, me aparece error solo la misma que tengo descargada si me deja reproducir mi música 
![Screenshot_20241026_003809](https://github.com/user-attachments/assets/60e6001b-35f2-49aa-a4ba-2d72318fe677)

### Suggested Solution

Pues que me mandé la aplicación sin errores pq la verdad si es muy buena la aplicación pero con esos errores muy mal 

### Alternatives

O que me envien la actualización sin errores por favor 

### Additional Context

Pues solo eso , que la aplicación cada que busco una canción me aparece error y la que tengo descargada si me deja reproducirla

**Comment by fast4x** [comment]
Download latest and login

**Comment by juanct-sudo** [comment]
Ya tengo la última versión, pero paso lo mismo, y como se inicia sesión?
