### ISSUE TITLE
Cómo se inicia sesión en remusic

### ISSUE THREAD

**Issue by Handel1793** [fast4x/RiMusic#4189]
### Version of RiMusic

0.6.58

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Descargue su aplicación y cuando pongo una música me dice inicia sesión y nose donde lo hago eso

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Poder escuchar música 

### What more can you tell us? (Optional)

Pues lo desinstale y no hago nd más pero por favor ayúdenme

**Comment by NAKILEV** [comment]
Intenté esto y me funcionó: Después de loggearte en yt busca "google link", podras entrar a google atravez de algun video que tenga el link, cuando estés en el buscador entra a la página de youtube music.
Ahí no se exactamente que hacer, pero prueba entrar a un video, entrar a tu perfil (ya deberías estar loggeado ahí también) y dar el botón de "abrir app"; cuando hagas todo eso puedes salir, y ya en rimusic, en la sección de youtube te saldrá "disconected", si quieres reinicias la app, pero ya debe estar listo. Pruébalo a ver si te funciona.

**Comment by Handel1793** [comment]
Que es instancia personalizada de pided?

**Comment by fast4x** [comment]
Download latest version please.
