### ISSUE TITLE
Compressed audio quality with audio quality set to high 

### ISSUE THREAD

**Issue by LeRaptoriito** [fast4x/RiMusic#4191]
### Version of RiMusic

0.6.58

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Connect YouTube Account 
3. Launch music
4. Weird audio quality

### What was your expectation?

Having the same audio quality as before the mandatory YouTube Account 

### What more can you tell us? (Optional)

Since a YouTube Account is mandatory for listening to music, the audio quality is kinda weird, it feels like the audio is compressed. For musics that were downloaded before the update their quality is still nice but streamed musics and new downloaded musics have weird quality. My audio quality setting is at high.

**Comment by darkza** [comment]
i also descovered days before nothing worked anymore without login that sometimes the quality was at 50kbs

**Comment by fast4x** [comment]
Quality available is max 160k
