### ISSUE TITLE
I'm having an "unknown read error" problem ( I can't listen to any music anymore)  

### ISSUE THREAD

**Issue by Oosn** [fast4x/RiMusic#4194]
### Version of RiMusic

0.6.57.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on a song
3. a message appears "music cannot be played" 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I want to listen my music

### What more can you tell us? (Optional)

I can't listen to any music, even the one on my playlist

**Comment by moussa86** [comment]
same song cannot be played

**Comment by bellehop** [comment]
The error displayed "Media cannot be played" before, now it is the error "Song cannot be played". Either way, no songs are playing from my Libra except Cached songs.

**Comment by fast4x** [comment]
Download latest version please.

**Comment by bellehop** [comment]
Not available on F-Droid as yet.
![Screenshot_20241026-175151](https://github.com/user-attachments/assets/4adbf7ce-c6b5-4b4c-a274-55c461bcb8c9)

**Comment by fast4x** [comment]
Of course, FDroid require 1-2 weeks
