### ISSUE TITLE
Exporting Playlists Is Corrupted

### ISSUE THREAD

**Issue by coopershaw1116** [fast4x/RiMusic#4195]
### Version of RiMusic

0.6.85

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click the export playlists button 
3. Choose where to save the file
4. Click the import playlist button
5. Enjoy as it doesnt let you tap on the file that it just made.
![Screenshot_20241026_202744_Files](https://github.com/user-attachments/assets/b8fcc4b4-ddbd-4694-ad85-d0e613407cc5)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

It was supposed to import the exported playlist

### What more can you tell us? (Optional)

Even after clearing all data from RiMusic and uninstalling and reinstalling the same and older versions i couldnt get it to work

**Comment by fast4x** [comment]
Download latest version please
