### ISSUE TITLE
pedía inicio sesión para escuchar música no descargada y descargar música que no estuviera descargada

### ISSUE THREAD

**Issue by mimi519** [fast4x/RiMusic#4196]
### Version of RiMusic

0.6.47.1

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. busque una canción no descargada y no podía descargar
3. error source
4. pide inicio de sesion
5. si podía guardarla en listas mias
6. si podía escuchar lo descargado
7. actualice a la versión rimusic 0.6.58 y seguía igual
8. desinstale y reinstale ambas varias veces y todo sigue igual, o peor pues se borraron las descargadas
9. mi móvil es un Huawei p20 sistema EMUI versión 12. y así ha funcionado muy bien hasta ayer
10. ya no se que hacer y me canse de buscar

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

que volviera a como estaba hasta hace 2 dias

### What more can you tell us? (Optional)

no se que sesión hay que iniciar y por que ahora hay que iniciar sesión, menos mal que tenía copia de las listas de canciones, pero como borre y volví a Instalar, lo descargado ya no lo tengo y no lo puedo escuchar, solo tengo las listas y no escucho nada, y voy a tener que volver a escuchar los anuncios de spotyfy y a escuchar la música que ellos quieren

### Logs (Optional)

![Screenshot_20241026_114647_it fast4x rimusic](https://github.com/user-attachments/assets/3793db59-6abd-4694-967a-7cc5705a57db)
![Screenshot_20241026_114625_it fast4x rimusic](https://github.com/user-attachments/assets/3f9ca17a-c068-4c52-813d-d2d4de546222)
![Screenshot_20241026_114705_it fast4x rimusic](https://github.com/user-attachments/assets/361f4261-130a-40c4-b31b-82e983a8aca3)
![Screenshot_20241026_114711_it fast4x rimusic](https://github.com/user-attachments/assets/40bdf382-07fd-4e72-af69-184a70bb1ce5)

**Comment by mimi519** [comment]
![Screenshot_20241026_142357_it fast4x rimusic](https://github.com/user-attachments/assets/64a23c30-af14-4201-920f-b89303aa8df8)

**Comment by Miguelrimusic** [comment]
A mi me pasó el otro dia. Lo solucioné accediendo a ajustes (3 barras en la esquina superior derecha de la aplicación), después té desplazas hacia la derecha en la barra de opciones de abajo hasta llegar a Miscelania y la abres. Allí encontraras el acceso a YouTube Músic y es donde has de iniciar sesión.
Espero que te funcione.
Salut!!

**Comment by mimi519** [comment]
> A mi me pasó el otro dia. Lo solucioné accediendo a ajustes (3 barras en la esquina superior derecha de la aplicación), después té desplazas hacia la derecha en la barra de opciones de abajo hasta llegar a Miscelania y la abres. Allí encontraras el acceso a YouTube Músic y es donde has de iniciar sesión. Espero que te funcione. Salut!!

lo que no quería era tener que iniciar sesión en YouTube, ya lo han arreglado con la versión 0.6.58.1,
pero gracias de todas formas

**Comment by fast4x** [comment]
Try custom version please download https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by mimi519** [comment]
ya se soluciono con la versión 0.6.58.1, graciasMIGUELI -------- Mensaje original --------De: Rino Russo ***@***.***>Fecha: mar., 29 oct. 2024 10:51Para: fast4x/RiMusic ***@***.***>Cc: mimi519 ***@***.***>, Author ***@***.***>Asunto: Re: [fast4x/RiMusic] pedía inicio sesión para escuchar música no descargada y descargar música que no estuviera descargada (Issue #4196)
Try custom version please download https://github.com/fast4x/RiMusic/tree/master/customVersion
