### ISSUE TITLE
In Last update no music launch

### ISSUE THREAD

**Issue by Paul75** [fast4x/RiMusic#4198]
### Version of RiMusic

0.6.58

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Chose any music and not launch

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.
![Screenshot_20241026_134534_it.fast4x.rimusic.jpg](https://github.com/user-attachments/assets/2626237b-7ad4-4c4f-9213-962e252a1799)

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Chose any music and not launch

**Comment by diwas7777** [comment]
Goto setting -> misc -> connect youtube music
