### ISSUE TITLE
no se puede oír online ni descargar en versiones anteriore

### ISSUE THREAD

**Issue by mimi519** [fast4x/RiMusic#4200]
### Version of RiMusic

0.6. 47.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. busco canción o line y no permite
3. error source
4. y si actualizo tengo el problema de inicio sesion

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

por favor solucionen lo, si no tendré que desistalar

### What more can you tell us? (Optional)

por favor solucionenlo

**Comment by woskkdmsosid** [comment]
descarga la 6.48

**Comment by woskkdmsosid** [comment]
> descarga la 6.48

https://github.com/fast4x/RiMusic/releases/tag/v0.6.58

**Comment by mimi519** [comment]
el problema esta en que ni iniciando sesión, además de que no puedo iniciar sesion, por que no tengo el navegador crome ni lo voy a poner, además si no he actualizado por que no me dejo seguir igual. si esto no se arregla lo quitare

**Comment by mimi519** [comment]
> > descarga la 6.48 y inicia sesion con yt music en ajustes misceláneos
> 
> https://github.com/fast4x/RiMusic/releases/tag/v0.6.58

también falla y no estoy de acuerdo con iniciar sesión en otro sitio, para eso directamente quito esta aplicación y me voy a otra

**Comment by mimi519** [comment]
> descarga la 6.48, y inicia sesion con yt music en ajustes misceláneos

el problema esta en que ni iniciando sesión, además de que no puedo iniciar sesion, por que no tengo el navegador crome ni lo voy a poner, además si no he actualizado por que no me dejo seguir igual. si esto no se arregla lo quitare

**Comment by mimi519** [comment]
![Screenshot_20241026_142357_it fast4x rimusic](https://github.com/user-attachments/assets/c8fad569-4965-42a7-a1d2-0bd97cf70b5a)

**Comment by mimi519** [comment]
Este es el error de la 6.47.1

**Comment by fast4x** [comment]
Download latest version please.
