### ISSUE TITLE
All my music disappeared

### ISSUE THREAD

**Issue by vierfax** [fast4x/RiMusic#4201]
### Version of RiMusic

0.6.56

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [x] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Uninstall RiMusic
3. Install RiMusic
4. Boom! Music gone

### What was your expectation?

I expected to fix error by uninstalling and keep all my music

### What more can you tell us? (Optional)

I uninstalled because music could not be played after installing previous builds

**Comment by diwas7777** [comment]
Uninstalling will remove any song you have unless you create a backup file and import it manually after reinstalling

**Comment by mimi519** [comment]
> ### Versión de RiMusic
> 0.6.56
> 
> ### Versión para Android
> 7.0
> 
> ### He hecho esto:
> * [x]  Desinstalar la compilación anterior antes de instalar una nueva
> * [x]  Comprobado problemas de apertura acerca de mi problema similar
> 
> ### Cuéntanos cómo desencadenas este error
> 1. Open RiMusic
> 2. Uninstall RiMusic
> 3. Install RiMusic
> 4. Boom! Music gone
> 
> ### Submit a video
> _No response_
> 
> ### What was your expectation?
> I expected to fix error by uninstalling and keep all my music
> 
> ### What more can you tell us? (Optional)
> I uninstalled because music could not be played after installing previous builds
> 
> ### Logs (Optional)
> _No response_

como usuario te recomiendo hacer copia seguridad cada vez que hagas cambios y además actualizar en vez de desistalar para instalar la nueva version

**Comment by vierfax** [comment]
> Uninstalling will remove any song you have unless you create a backup file and import it manually after reinstalling

Some kind of heads up would've been nice lol

**Comment by diwas7777** [comment]
> > Uninstalling will remove any song you have unless you create a backup file and import it manually after reinstalling
> 
> Some kind of heads up would've been nice lol

lol 😂 But uninstalling is android thing not rimusic so no blaming here ig

Remember to always keeps backup of music playlist and also of setting 

Note: Music playlist backup like downloaded music can be taken from the respective page

**Comment by mimi519** [comment]
> > > La desinstalación eliminará cualquier canción que tenga a menos que cree un archivo de copia de seguridad e importe manualmente después de reinstalar
> > 
> > 
> > Algún tipo de cabeza arriba habría sido agradable ja
> 
> lol 😂 Pero la desinstalación es cosa android no rimusic así que no culpar aquí ig
> 
> Recuerde mantener siempre la copia de seguridad de la lista de reproducción de música y también de la configuración
> 
> Nota: La copia de seguridad de la lista de reproducción de música como la música descargada se puede tomar de la página respectiva

yo hago copias de seguridad y restauró las distintas listas, pero no está descargadas y con el problema nuevo de inicio sesión o que el la edición anterior tampoco va pues me quede son poder usar el programa,  se puede hacer algo sin tener que abrir cuenta en YouTube?

**Comment by vierfax** [comment]
> > > Uninstalling will remove any song you have unless you create a backup file and import it manually after reinstalling
> > 
> > 
> > Some kind of heads up would've been nice lol
> 
> lol 😂 But uninstalling is android thing not rimusic so no blaming here ig
> 
> Remember to always keeps backup of music playlist and also of setting
> 
> Note: Music playlist backup like downloaded music can be taken from the respective page

Note blaming, more like a suggestion. If it's so easy to lose ALL YOUR MUSIC just by doing something so usual as deleting a failing to reinstall, maybe a heads up in the app is in order.

**Comment by mimi519** [comment]
> > > > > La desinstalación eliminará cualquier canción que tenga a menos que cree un archivo de copia de seguridad e importe manualmente después de reinstalar
> > > > 
> > > > 
> > > > Algún tipo de cabeza arriba habría sido agradable ja
> > > 
> > > 
> > > lol 😂 Pero la desinstalación es cosa android no rimusic así que no culpar aquí ig
> > > Recuerde mantener siempre la copia de seguridad de la lista de reproducción de música y también de la configuración
> > > Nota: La copia de seguridad de la lista de reproducción de música como la música descargada se puede tomar de la página respectiva
> > 
> > 
> > yo hago copias de seguridad y restauró las distintas listas, pero no está descargadas y con el problema nuevo de inicio sesión o que el la edición anterior tampoco va pues me quede son poder usar el programa,  se puede hacer algo sin tener que abrir cuenta en YouTube?
> 
> install older version for now until developers add feature to not have to login to do everything and disable check for updates

he puesto otra vez la versión que funcionaba hasta el día 18 seguro, ya que ahí hice la última copia, pero como la copia no guarda las descargadas que en mi caso eran todas, las listas no sirven pues en la versión anterior no te piden ineciar sesión pero no te deja descargar por lo que no puedo escuchar nada, y esto lo han hecho ellos sin que yo hiciera nada, anoche fui a escuchar una canción que no tenía descargada y no me dejo, sin hacer ninguna actualización ya que yo las tenia cortadas las actualización automatica

**Comment by diwas7777** [comment]
> > > > Uninstalling will remove any song you have unless you create a backup file and import it manually after reinstalling
> > > 
> > > 
> > > Some kind of heads up would've been nice lol
> > 
> > lol 😂 But uninstalling is android thing not rimusic so no blaming here ig
> > 
> > Remember to always keeps backup of music playlist and also of setting
> > 
> > Note: Music playlist backup like downloaded music can be taken from the respective page
> 
> Not blaming, more like a suggestion. If it's so easy to lose ALL YOUR MUSIC just by doing something so usual as deleting a failing app to reinstall, maybe a heads up in the app is in order.

i think after adding login feature they are trying to make persistent playlist or sync playlist with youtube

Or they can simply let us choose download folder 📁 for local save

**Comment by mimi519** [comment]
> > > > > La desinstalación eliminará cualquier canción que tenga a menos que cree un archivo de copia de seguridad e importe manualmente después de reinstalar
> > > > 
> > > > 
> > > > Algún tipo de cabeza arriba habría sido agradable ja
> > > 
> > > 
> > > lol 😂 Pero la desinstalación es cosa android no rimusic así que no culpar aquí ig
> > > Recuerde mantener siempre la copia de seguridad de la lista de reproducción de música y también de la configuración
> > > Nota: La copia de seguridad de la lista de reproducción de música como la música descargada se puede tomar de la página respectiva
> > 
> > 
> > No culpar, más bien una sugerencia. Si es tan fácil perder TODA SU MÚSICA simplemente haciendo algo tan habitual como eliminar una aplicación que falla para reinstalar, tal vez una advertencia en la aplicación está en orden.
> 
> Creo que después de agregar la función de inicio de sesión están tratando de hacer una lista de reproducción persistente o sincronizar la lista de reproducción con youtube
> 
> O simplemente pueden dejarnos elegir la carpeta de descarga 📁 para guardar localmente

como se puede hacer lo de descarga en carpeta local?

**Comment by fast4x** [comment]
Download latest version please.
