### ISSUE TITLE
se va a poder usar rimusic, sin tener que abrir cuenta en YouTube, en el futuro? 

### ISSUE THREAD

**Issue by mimi519** [fast4x/RiMusic#4203]
### Version of RiMusic

0.6.47.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. no tengo cuenta en YouTube
3. no la voy a tener
4. no quiero redes sociales

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

que hagan lo posible para no tener que abrir cuentas en otros sitios

### What more can you tell us? (Optional)

una explicación de por que hay que abrir cuenta e iniciar sesión, no estaría mal, aunque no la abrire

**Comment by fast4x** [comment]
Download latest version please.
