### ISSUE TITLE
The songs still repeat 

### ISSUE THREAD

**Issue by PedroH654** [fast4x/RiMusic#4205]
### Version of RiMusic

0.6.58

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Open RiMusic
Put the music playlist
Turn off your phone
Boom! After 3 songs pass, instead of going to 4, back to 2

### Submit a video

There is no way to record with the screen off

### What was your expectation?

That the whole playlist would be played, without repeating the songs in the middle of the queue, only after the last song

### What more can you tell us? (Optional)

The strange thing is that this bug occurs, only with the screen off, but when the screen is on or open in the app, it does not occur.
For this bug to occur, the screen has to be off, and the app in the background (NOTE: the problem is not the battery optimizations, as they are already turned off and the "invincible server" is activated.

### Logs (Optional)

2024-10-25 17:49:10:820 DEBUG: MainApplication - Log habilitado em /data/user/0/it.fast4x.rimusic/files/logs
2024-10-25 17:49:13:074 DEBUG: MainApplication - Log habilitado em /data/user/0/it.fast4x.rimusic/files/logs
2024-10-25 17:49:13:531 DEBUG: c - CheckMonthlyPlaylist false
2024-10-25 17:49:13:759 DEBUG: c - CheckMonthlyPlaylist true
2024-10-25 17:49:13:760 DEBUG: c - SongsMostPlayed null
2024-10-25 17:49:13:798 DEBUG: c - CheckMonthlyPlaylist true
2024-10-25 17:49:13:799 DEBUG: c - SongsMostPlayed 0

**Comment by PedroH654** [comment]
And I left the screen off during the whole process, because the bug only occurs with the screen off

**Comment by Loogi9** [comment]
I have the same problem, it also happens when it plays in background.

**Comment by Loogi9** [comment]
The bug also occurs when the app is in background.
https://github.com/user-attachments/assets/5ed44654-a773-452a-b3af-1429e3c2d547

**Comment by Ask1ew** [comment]
I have the same problem on Android 14 with the 0.6.58.1 ri music version

**Comment by PedroH654** [comment]
> O bug também ocorre quando o aplicativo está em segundo plano. https://github.com/user-attachments/assets/5ed44654-a773-452a-b3af-1429e3c2d547

The problem is that this bug gets in the way too much, as I spend most of my time with the app in the background/with the screen off 😅😅

**Comment by fast4x** [comment]
Fixed, available from version 0.6.63
