### ISSUE TITLE
No me aparece la opción de inicio de sesion

### ISSUE THREAD

**Issue by Maunds** [fast4x/RiMusic#4206]
### Version of RiMusic

La última versión 

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

No me deja reproducir la música 
Ni me aparece la opción de inicio de sesión 

### Submit a video

Nada

### What was your expectation?

Nada

### What more can you tell us? (Optional)

Ninguna 

### Logs (Optional)

Nada

**Comment by fast4x** [comment]
Download latest version please.
