### ISSUE TITLE
ITS STILL NOT PLAYING SONG EVEN I VE BEEN LOG IN TO YT

### ISSUE THREAD

**Issue by Kennyrogerspot** [fast4x/RiMusic#4208]
### Version of RiMusic

0.6.58

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. log in
3. still dont play music

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

i log in through yt music and then restart the app and still says "logging in to play songs"

**Comment by dis-Is-Fine** [comment]
You need to restart the app for it to work. If you did restart the app and it's still not working, try to force shutdown trough your phone settings app or restart your phone, then it will work.

**Comment by Juggalage** [comment]
> You need to restart the app for it to work. If you did restart the app and it's still not working, try to force shutdown trough your phone settings app or restart your phone, then it will work.

Tried all of these and it still doesn't work for me.

**Comment by AzoSBear** [comment]
I temporarily fixed it like this

https://github.com/fast4x/RiMusic/issues/4217#issuecomment-2439682459

**Comment by fast4x** [comment]
Download latest version please.
