### ISSUE TITLE
No me reproduce ninguna cancion, absolumente ninguna

### ISSUE THREAD

**Issue by Vixohrm** [fast4x/RiMusic#4212]
### Version of RiMusic

0.6.57.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Música abierta
2. Haga clic en A
3. Haga clic en B
4. ¡Boom! El accidente ocurre.

### Submit a video

Si está en Android, descargue una grabadora de pantalla y grabe su pantalla mientras
duplicar el problema como se describe anteriormente. > Es posible que deba usar la aplicación Github para poder cargar video: el límite de tamaño es de 10 MB.

Si está en el escritorio, arrastre el video a este cuadro y se cargará automáticamente 

https://github.com/user-attachments/assets/1b64fd82-e4a1-446c-9f82-6f225bf5761b

### What was your expectation?

Esperar respuesta

### What more can you tell us? (Optional)

No me reproduce ninguna canción, intente las soluciones y aun nada

### Logs (Optional)

![Screenshot_20241026_122418](https://github.com/user-attachments/assets/e4601bfe-2584-4d9c-8cc5-ca04c155f613)

**Comment by danniel-contreras** [comment]
Actualiza a la versión 0.6.58 e inicia sesión con YouTube music en el apartado de miscelaneo

**Comment by fast4x** [comment]
Download latest version please.
