### ISSUE TITLE
Su Android Auto non riproduce la musica

### ISSUE THREAD

**Issue by claxcian** [fast4x/RiMusic#4213]
### Version of RiMusic

0.6.58

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Su Android auto da ancora errore per la riproduzione 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Mi aspetto che funzioni

**Comment by fast4x** [comment]
Download latest version please.
