### ISSUE TITLE
Liked songs reset the "liked" tag

### ISSUE THREAD

**Issue by KeknanXD** [fast4x/RiMusic#4214]
### Version of RiMusic

0.6.58

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Go to ANY previously liked song (download/cached/neither doesn't matter)
2. Let it play
-> "Like" tag will unmark itself out of the blue

### Submit a video

https://github.com/user-attachments/assets/d4f077b6-b15a-4b11-842d-c850ed1de5f9

### What was your expectation?

That nothing will happen

### What more can you tell us? (Optional)

For those simply reading this: The songs here work because I downloaded them a long time ago. Please don't ask how I got them to play.

https://github.com/user-attachments/assets/52c0f8c5-821a-489b-935c-b9310b9535c6

There's also this: The like tag keeps unmarking itself until the infamous "media can't be played" pop-up message appears in songs that are neither downloaded nor cached.

**Comment by Daniel-VW** [comment]
Yes, i got the same problem. I lost my complete favorit songs list because of this bug. Please fix it guys.

**Comment by tayuriv** [comment]
same

**Comment by fast4x** [comment]
Fixed, available from version 0.6.58.1
