### ISSUE TITLE
La mayoria de canciones ya no se reproducen, cuando pongo una nunca suena, solo hay algunas que siguen funcionando normal pero el resto no

### ISSUE THREAD

**Issue by Luisk2810** [fast4x/RiMusic#4215]
### Version of RiMusic

0.6.57

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens
5. 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Que todas las canciones se reprodujeran, no solo algunas

**Comment by fast4x** [comment]
Download latest version please.
