### ISSUE TITLE
login opens YouTube instead of YouTube music

### ISSUE THREAD

**Issue by DuckyMcLucky** [fast4x/RiMusic#4217]
### Version of RiMusic

0.6.58

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Press on settings
3. Press on misc
4. Log in
5. YouTube opens instead of YouTube music 
6. I cannot log in

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

https://github.com/user-attachments/assets/acca0f8b-1d08-464b-b6f7-ef26049b39ef

### What was your expectation?

I expected for it to open yt music

**Comment by AzoSBear** [comment]
I also had this issue.

The temporary way I resolved it was linking the YouTube music website to one of my own videos. 
Then I logged out and logged back in and it sent me back to YouTube. I then clicked the link to YouTube Music and closed and reopened RiMusic and could listen to music.

**Comment by fast4x** [comment]
Download latest version please.

**Comment by DuckyMcLucky** [comment]
> I also had this issue.
> 
> The temporary way I resolved it was linking the YouTube music website to one of my own videos. Then I logged out and logged back in and it sent me back to YouTube. I then clicked the link to YouTube Music and closed and reopened RiMusic and could listen to music.

THANK YOU OH MY GOD
