### ISSUE TITLE
No me deja descargar canciones y me dise que deba de iniciar sesión o que es mi red pero mi red esta bien pero nose que hacer

### ISSUE THREAD

**Issue by Isain-08** [fast4x/RiMusic#4220]
### Version of RiMusic

0.6.58

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1:ingresa a rimusic 
2:cuando busque una canción la puse para que se reprodusiera
3:no se reprodujo nada 
4:me llego dos mensajes uno rojo y uno amarillo el rojo diciendo que no se podía por fallas de red o por otras cosas pero mi red esta bien por que le agarra para otra aplicaciones
Y el amarillo diciendo que inicie sesión 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Poder escuchar mi música 

### What more can you tell us? (Optional)

![Screenshot_20241026-130117](https://github.com/user-attachments/assets/22c0a963-f737-4ec0-a60d-3b2561306caa)
Ese mensaje siempre me aparece y no se reproducción la música aparate de que no le puedes dar la x ya que aun asi nose quita y es muy molesto 

Uploading Recorder_26102024_130643.mp4…

**Comment by fast4x** [comment]
Download latest version please.

**Comment by Laea-idk** [comment]
Ayuda no se q paso pero trate de descargar una canción pero me salía error desconocido ahora no puedo descargar ninguna canción, las q tengo descargadas desde antes si, pero ahora no y mi Internet está bien 
![Screenshot_20241026_235813_it fast4x rimusic](https://github.com/user-attachments/assets/3bcee5b1-6856-41d4-8085-e1d61f0528e3)
