### ISSUE TITLE
Cant login on Youtube Music if YT account have multiple channels

### ISSUE THREAD

**Issue by nmariscal86** [fast4x/RiMusic#4223]
### Version of RiMusic

0.6.58

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on Settings, Misc, Connect to Youtube Music
3. Complete the Google Login with 2FA
4. Ask which Youtube channel gonna be used
5. List videos like a browser (briefly appears a popup asking for Restart App)
6. Restart App and Connect to YouTube Music still appear even trying to reboot device

### What was your expectation?

I expected to login but couldnt

### What more can you tell us? (Optional)

I have and addtional device on Android 12 but with a Google Account without channels and that device worked like it is without any trouble.

**Comment by fast4x** [comment]
Go to telegram group, topic tutorial
