### ISSUE TITLE
Rimusic

### ISSUE THREAD

**Issue by Sm0kF** [fast4x/RiMusic#4224]
### Version of RiMusic

v0.6.30

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. No reproduce música

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Que se solucionará el problema

**Comment by Sm0kF** [comment]
La app rimusic dejo de funcionar no reproduce música

**Comment by fast4x** [comment]
Download latest version please.
