### ISSUE TITLE
It doesn't play music

### ISSUE THREAD

**Issue by cristianderudi** [fast4x/RiMusic#4225]
### Version of RiMusic

0.6.58.1

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Since I downloaded the last update, it no longer plays anything and throws an error. The version I downloaded is 0.6.58.1.

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Play music

**Comment by fast4x** [comment]
poor info explain better or try to enable yt login and connect

**Comment by cristianderudi** [comment]
I experienced an issue after updating the app while listening to music. An error, indicated first by a yellow and then a red notification, prevented any song playback. Enabling YT login has resolved the issue. Is this a recent feature? I do not recall configuring it previously.
Thanks!

**Comment by fast4x** [comment]
YtM recently has blocked listening without login, so login would be mandatory.

**Comment by MeiRos** [comment]
ViTune can still play music without login. @fast4x

**Comment by fast4x** [comment]
I know, also partially RiMusic

**Comment by Atmosujk** [comment]
Man, I feel very frustrated with this application, I always update this application routinely hopes that various bugs have been resolved, but what I get is a variety of the same bugs and some new bugs.

**Comment by fast4x** [comment]
Great if you don't like it don't use it
