### ISSUE TITLE
Adding playlist to a currently created playlist 

### ISSUE THREAD

**Issue by abdulkarimx1** [fast4x/RiMusic#423]
### Description

Whenever you search for a playlist using the search, it allows you to create a local playlist for it instead giving ability to add it to a current playlist ( that you already created ) 

### Suggested Solution

Would it be possible to add the whole playlist directly to a current playlist without selecting each song in the playlist? 

https://github.com/fast4x/RiMusic/assets/105733146/3e5de7d9-83bb-4fca-bbac-3b9541bf48fe

**Comment by fast4x** [comment]
Yes it's possible.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.18
