### ISSUE TITLE
no reproduce nada (recién actualizado)

### ISSUE THREAD

**Issue by Hildorien66** [fast4x/RiMusic#4230]
### Version of RiMusic

La version anterior empezó a dar error constante; nueva versión no reproduce NADA.

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Que funcionara

### What more can you tell us? (Optional)

Si no funciona, desinstalo.

**Comment by jo-0609xy** [comment]
No Reproduce nada está dando mucho problema

**Comment by nubesurrealista** [comment]
Debes iniciar sesión con Google para evitar esos problemas.

**Comment by jo-0609xy** [comment]
En qué parte de Ri music inicio seción

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fast4x** [comment]
In miscellaneous settings there's a yt login

**Comment by Hildorien66** [comment]
Desinstalo. Prefiero Spotify, tendrá publicidad, pero por lo menos hace lo que se espera...

**Comment by kdejeqq** [comment]
> Uninstall it. I prefer Spotify, there will be advertising, but at least it does what we expect...

Pff.... Really you are really rude to the developers of RiMusic.... Your remarks are not constructive.. Moreover RiMusic is an alternative to Spotify so in the end it comes down to the same thing.... Personally I will continue to use RiMusic. Why exactly did you open this issue?

**Comment by Miguelrimusic** [comment]
A mi me pasó el otro dia. Lo solucioné accediendo a ajustes (3 barras en la esquina superior derecha de la aplicación), después té desplazas hacia la derecha en la barra de opciones de abajo hasta llegar a Miscelania y la abres. Allí encontraras el acceso a YouTube Músic y es donde has de iniciar sesión.
Espero que te funcione.
Salut!!
