### ISSUE TITLE
I can't download songs 

### ISSUE THREAD

**Issue by Yxck9** [fast4x/RiMusic#4232]
### Version of RiMusic

0.6.56.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on a songs 
3. Song don't playing 

### Submit a video

This what app say it to me 
![Screenshot_20241027_025458](https://github.com/user-attachments/assets/77ec4066-591c-4d61-912d-1ab9edce612f)

### What was your expectation?

.

### What more can you tell us? (Optional)

I say after I click on a song after research or a random song, the song doesn't play 

### Logs (Optional)

.

**Comment by fast4x** [comment]
Update to latest release please
