### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by Ksmzvdjek** [fast4x/RiMusic#4235]
### Description

Hola buenas noches primero que nada gracias a todo el personal por crear tan magnífica aplicación sin duda es increíble por todas las funciones que ofrece la verdad que es mejor que todas las que e probado...
Pero hay un problema, que hace que la aplicación a pesar de ser tan buena pase a ser mala,  o que la convierta en una mala aplicación, y que simplemente dejes de usarla.

### Suggested Solution

El grave problema que tiene, es que no cuenta con un formato compatible para reproducir video ya que la mayoría de las canciones que he buscado vienen en formato de video y está app no las puede reproducir...

Se pone un recuadro amarillo con un letrero que dice:  NO SE PUDO ENCONTRAR UN FORMATO DE AUDIO COMPATIBLE

Y eso es justamente lo que me encantaría que agregaran en la próxima actualización, un formato que pueda leer cualquier formato de audio y video o múltiples formatos para que reproduzca cualquier audio o vídeo que esté dentro de esta aplicación.

### Alternatives

Ojalá puedan agregar los formatos que usa YouTube Music o parecidos para que puedan leer toda clase de audio y video

### Additional Context

De antemano muchas gracias por todo espero y me puedan apoyar con ello para la siguiente actualización

**Comment by fast4x** [comment]
Update to latest version please, thanks
