### ISSUE TITLE
obligación de iniciar sesión sino muchos mensajes molestos

### ISSUE THREAD

**Issue by mimi519** [fast4x/RiMusic#4238]
### Version of RiMusic

0 6.58

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. tocó una canción no descargada 
3. aparecen múltiples mensajes continuos de tiene que iniciar y error 
4 no hay forma de quitarlos mensajes salvo que inicies sesion
5. no quiero tener que estar conectado a otra app para escuchar musica

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

que no se tenga que iniciar sesión para escuchar música que no te hayas descargado previamente

### What more can you tell us? (Optional)

si para usar una app, tengo que conectarme a otra, me quedo con la otra o me vuelvo a spotyfy, y ahorro tener una app en el movil
![Screenshot_20241027_000010_it fast4x rimusic](https://github.com/user-attachments/assets/7e6584bc-efc2-47d2-aeb2-a2bfe74ec0e2)
![Screenshot_20241026_235209_it fast4x rimusic](https://github.com/user-attachments/assets/0b2416bc-00ef-426f-9717-38486fd0b150)
![Screenshot_20241026_235039_it fast4x rimusic](https://github.com/user-attachments/assets/389b26d4-2377-4ad7-8363-5483701ac218)
![Screenshot_20241026_231630_it fast4x rimusic](https://github.com/user-attachments/assets/b030d5f1-18ef-4475-8dab-15ed5a15483e)
![Screenshot_20241026_231130_it fast4x rimusic](https://github.com/user-attachments/assets/9253084f-c85b-49cf-93f3-e4779c4b1fbb)
![Screenshot_20241026_201624_it fast4x rimusic](https://github.com/user-attachments/assets/849843bd-d1b4-498b-8f6f-9434d0419002)

**Comment by fast4x** [comment]
Update to latest version please

**Comment by mimi519** [comment]
buenas como veras en las fotos que subí, tengo la última versión, le doy a actualizar y no actualizaMIGUELI -------- Mensaje original --------De: Rino Russo ***@***.***>Fecha: dom., 27 oct. 2024 10:05Para: fast4x/RiMusic ***@***.***>Cc: mimi519 ***@***.***>, Author ***@***.***>Asunto: Re: [fast4x/RiMusic] obligación de iniciar sesión sino muchos mensajes molestos (Issue #4238)
Update to latest version please

**Comment by mimi519** [comment]
> Update to latest version please

como ves en las fotos enviadas, esta en la última versión 0.6.58, y le doy a actualizar y me dice que esta actualizado,

**Comment by fast4x** [comment]
latest is 0.6.58.1

**Comment by Ao1Pointblank** [comment]
Same issue. I am on 0.6.58.1 downloaded straight from github, and uncached songs won't play without signing into a YouTube account, which I think defeats one of the advantages of rimusic.

**Comment by mimi519** [comment]
ok ahora si gracias

**Comment by mimi519** [comment]
ok ahora si gracias

**Comment by Ao1Pointblank** [comment]
> Same issue. I am on 0.6.58.1 downloaded straight from github, and uncached songs won't play without signing into a YouTube account, which I think defeats one of the advantages of rimusic.

I think I fixed it in 0.6.58.1 by switching playback quality from High to Automatic, and then force stopping the app.

**Comment by mimi519** [comment]
buenas y gracias antetodotodo se soluciono con la versión que han sacado para solucionarlo la 0.6.58.1MIGUELI -------- Mensaje original --------De: Ao1Pointblank ***@***.***>Fecha: dom., 27 oct. 2024 14:41Para: fast4x/RiMusic ***@***.***>Cc: mimi519 ***@***.***>, State change ***@***.***>Asunto: Re: [fast4x/RiMusic] obligación de iniciar sesión sino muchos mensajes molestos (Issue #4238)

Same issue. I am on 0.6.58.1 downloaded straight from github, and uncached songs won't play without signing into a YouTube account, which I think defeats one of the advantages of rimusic.

I think I fixed it in 0.6.58.1 by switching playback quality from High to Automatic, and then force stopping the app.
