### ISSUE TITLE
No carga la música 

### ISSUE THREAD

**Issue by juanct-sudo** [fast4x/RiMusic#4240]
### Description

Ya avía dejado una queja, la música no responde necesito una solución ya.

### Suggested Solution

Pues que me solucionen el problema 

### Alternatives

Arreglen el problema 

### Additional Context

También ayer deje una queja y jamás me solucionaron nada, ya desistanle la aplicación y la volví a descargar y nada

**Comment by fast4x** [comment]
Update to latest version please

**Comment by josemrs** [comment]
Not working on latest version.

**Comment by fast4x** [comment]
Try custom version please download https://github.com/fast4x/RiMusic/tree/master/customVersion
