### ISSUE TITLE
Player in notification tray keep showing playing without sound even after player in app is closed

### ISSUE THREAD

**Issue by RahulRoy13** [fast4x/RiMusic#4241]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Play a song 
3. Minimize the player without pausing the song
4. Swipe down the notification tray
5. Try to close the notification tray player it wont respond even pausing wont respond.
6. Touch the heart icon or seek the seeker then it goes away

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

https://github.com/user-attachments/assets/ee58ede5-2090-4ce1-a05b-579306a39ebb

### What was your expectation?

Notification player should either close or get paused. If it get paused then we could resume the song from there.

**Comment by fast4x** [comment]
Player in notification is a service independent, I'll improve

**Comment by RahulRoy13** [comment]
Thanks for the response😊😊😊

**Comment by fast4x** [comment]
Thank you for your kindness.

**Comment by fast4x** [comment]
Improved, now notification will be removed when mini player swiping down, available from version 0.6.59

**Comment by RahulRoy13** [comment]
> Improved, now notification will be removed when mini player swiping down, available from version 0.6.59

Damn, you guys are quick🔥
