### ISSUE TITLE
Listening time of a song stays at 0 min

### ISSUE THREAD

**Issue by adrianobattilana** [fast4x/RiMusic#4245]
### Version of RiMusic

0.6.58.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on my playlist and sort it by Listening time 
3. Song New Orleans is sinking by The Tragically Hip had a listening time of 24 min. Now after updating the app is 0. Despite listening to it again, it stays at 0.
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Listening time to progress correctly

**Comment by fast4x** [comment]
Poor info

**Comment by adrianobattilana** [comment]
How can I show it to you? What I can tell you is that listening time of this song went from 24 to 0 minutes and it is still at 0. No other way to show it. What other info do you need?

**Comment by fast4x** [comment]
have you tried to close player and reopen?

**Comment by adrianobattilana** [comment]
Yep multiple times
 I also tried to force it stop

**Comment by adrianobattilana** [comment]
![Screenshot_2024-10-30-00-21-47-01_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/d68a6cb9-7483-46ab-bddc-9614078319cd)

![Screenshot_2024-10-30-00-21-36-49_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/d97b6468-7c95-415a-b10d-6581f319fbf4)


Found a way to prove it to you. The song is (as it should be) topping my overall stats. But in my playlist it still shows 0 minutes listening time. So yeah things don't add up. Please fix it.
