### ISSUE TITLE
Media cannot be played

### ISSUE THREAD

**Issue by Matrix-Black** [fast4x/RiMusic#4252]
### Version of RiMusic

0.6.57.1

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens 

### Submit a video

Sorry, I don't speak much English and I use the translator for longer sentences, the problem occurs when I search for a song that I haven't downloaded, I play it and it doesn't work, much less download it.

### What was your expectation?

Espero encontrar solución y disculpen la molestia, no sé cómo solucionarlo

### What more can you tell us? (Optional)

Sorry, I don't speak much English and I use the translator for longer sentences, the problem occurs when I search for a song that I haven't downloaded, I play it and it doesn't work, much less download it.

### Logs (Optional)

Desconozco cómo acceder al registro

**Comment by fast4x** [comment]
Update yo the latest version please

**Comment by SleepyScribe** [comment]
I had to do this.

1. Backup.
2. Uninstall.
3. Reinstall.
4. Sign in on RiMusic.
5. Quit RiMusic.
6. Open RiMusic.
7. Restore backup.

**Comment by fast4x** [comment]
Try custom version please download https://github.com/fast4x/RiMusic/tree/master/customVersion
