### ISSUE TITLE
android auto does not work with youtube login.

### ISSUE THREAD

**Issue by veloal** [fast4x/RiMusic#4253]
### Version of RiMusic

latest

### Android version

9

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

no songs can be listened to except downloaded songs.

with the songs that can't be listened it resets the listening time statistics, all set to 0 minutes 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

it works as it is now

### What more can you tell us? (Optional)

application with the youtube login works fine

**Comment by fast4x** [comment]
Update to the latest version please

**Comment by veloal** [comment]
sorry. i'm using the latest version, v0.6.58.1

the application works as if nothing has happened in the last few days. it works perfectly. 

but not with android auto. only downloaded songs are played, the rest are not played and the listening time statistics are broken.

**Comment by nomenamecom** [comment]
Try to disable android auto in miscellaneous and disable as a developer. Try again to enable as a developer on Android Auto and other apps and enable android auto on miscellaneous. It happened to me and it fixed it!

**Comment by veloal** [comment]
fixed, thanks.
