### ISSUE TITLE
YTM issue cantine play media, important précision?

### ISSUE THREAD

**Issue by Potiron** [fast4x/RiMusic#4254]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Choose parameters miscellanous
3. Click on connect to YTM
4. Restart RIMusic / play a song

### Submit a video

[Screenshot_2024-10-27-19-43-08-321_it fast4x rimusic-edit](https://github.com/user-attachments/assets/83aac185-152e-4c67-84ab-ae090549653a)

### What was your expectation?

Since I own 2 Youtube account,maybe the connection to rimusic cant be done?

**Comment by fast4x** [comment]
Go to Telegram group > tutorial section

**Comment by Potiron** [comment]
Thanks it works.
One of my account dont give good result. Im using thé other one
![Screenshot_2024-10-27-21-55-54-014_it fast4x rimusic](https://github.com/user-attachments/assets/de470154-0766-4bad-aa6b-8c8fd6967ff6)

Thanks you!
