### ISSUE TITLE
Short and concise description of your bug

### ISSUE THREAD

**Issue by TheCibrik** [fast4x/RiMusic#4256]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on random song
4. Boom! It doesn't sound

### Submit a video

https://github.com/user-attachments/assets/d575ec51-8cef-4f39-ac68-b38081f1a4b2

### What was your expectation?

Being able to listen to my music quietly

### What more can you tell us? (Optional)

happens is that I can't listen to any songs, only the ones I have downloaded, and when I try to download them it doesn't work.

**Comment by fast4x** [comment]
try to logon on yt from miscellaneous settings
