### ISSUE TITLE
Application refuses to log into YouTube

### ISSUE THREAD

**Issue by manuel09** [fast4x/RiMusic#4257]
### Version of RiMusic

0.6.58.1

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on youtube login
3. rimusic open a tab yotube login 
4. i'm log in 
5. close the tab youtube 
6. after restarting the app, it continues to ask me to connect to YouTube

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I expected that the application would have logged into YouTube after restarting the app

### What more can you tell us? (Optional)

YouTube is seeing the login, i'm login but even after restarting the app, it continues to ask me to connect to YouTube , and rimusic deleted some many music when click play song

**Comment by PaolaAtilano** [comment]
I have the same issue :(
