### ISSUE TITLE
Songs are disappearing 

### ISSUE THREAD

**Issue by ghost** [fast4x/RiMusic#4258]
### Version of RiMusic

Newest

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on song
3. Song disappears from all 

### What was your expectation?

So it don't disappear, before newest version it didn't happen

**Comment by aneesh1122** [comment]
> Newest

![maxresdefault.jpg](https://github.com/user-attachments/assets/fcb91fbd-6f67-434e-b161-5a9309f91799)
