### ISSUE TITLE
Duplicate songs

### ISSUE THREAD

**Issue by N4SH3-RGB** [fast4x/RiMusic#4259]
### Version of RiMusic

0.6.58.1

### Android version

12

### I've done these:

- [x] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. I add some music album 
3. I'm looking for another album and the songs are duplicated.

### Submit a video

https://github.com/user-attachments/assets/c0c99f2d-b1d5-4b0b-a34c-bec289a7beea

### What was your expectation?

Any solutions or recommendations 

### What more can you tell us? (Optional)

Those albums are not like that, meaning you don't have songs with the same name.

**Comment by fast4x** [comment]
Check if songs are duplicated in yt

**Comment by Jit-Halder** [comment]
@fast4x the songs are not duplicated in yt but they are shown duplicated in rimusic I am facing the same issue.
