### ISSUE TITLE
Desconexión del Bluetooth de mi celular Xiaomi Redmi Note 9 con mi intercomunicador T-COM SC

### ISSUE THREAD

**Issue by DTunjano** [fast4x/RiMusic#4260]
### Version of RiMusic

0.6.58

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Se estable la conexión por medio de bluetooth entre el intercomunicador y el celular.
2. Abro la app de RiMusic.
3. Reproduzco cualquier canción de mi lista.
4. Reproducen por máximo 2 canciones; ocurre la desconexión entre los dispositivos.

### Submit a video

https://github.com/user-attachments/assets/304e4f36-b9d6-4ab7-8022-af5d339b7d78

Situándonos en la parte de las notificaciones del celular, cerca al símbolo del bluetooth, se observa una barra con batería (Intercomunicador), al momento de reproducir una canción, se desconecta rápidamente.

> Nota: Esto realmente sucede por lo que indica el sistema: "Su dispositivo no soporta la grabación de sonidos del sistema mientras se usan los audífonos". Subo el video a modo de ejemplo visual sobre lo que sucede con el problema que describo en el titulo de esta issue.

### What was your expectation?

La reproducción normal de musica, sin que ocurra una desconexión entre los dispositivos

### Importante
Cabe mencionar que llevo tiempo usando esta app, sin embargo, este problema solo se ha presentado en las versiones posteriores a la 0.6.50, siendo esta (0.6.50) la primera versión de la app que descargué y no me presentaba dicho problema de desconexión entre los dispositivos.

Por otro lado, ya comprobé que es la **app** la que afecta la conexión entre los dispositivos, pues he probado con dos reproductores de música diferentes (Mi Music  y Spotify) y en ninguno de estos ocurre la desconexión cuando los uso.

`De antemano agradezco su ayuda. Gracias por desarrollar y mantener esta aplicación ❤️`

**Comment by fast4x** [comment]
Thanks, RiMusic not use Bluetooth, it's used by system.
