### ISSUE TITLE
Sólo me permite reproducir canciones guardadas en la caché

### ISSUE THREAD

**Issue by DumbIsa42** [fast4x/RiMusic#4261]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [ ] Uninstall old build before installing a new one
- [ ] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abrir RiMusic
2. Tocar una música que no está guardada en la caché
3. Tocar en una música que está guardada en una caché

### Submit a video

https://github.com/user-attachments/assets/98256a9e-46c4-4b29-b43a-62b659deb0ed

### What was your expectation?

pues no funciona xd

### What more can you tell us? (Optional)

como algo opcional que tal vez sea útil:  a un amigo mío no le pasa este error porque él tiene las canciones descargadas, mas no las tiene descargadas en la caché

**Comment by fast4x** [comment]
Maybe you must login on yt from miscellaneous settings

**Comment by DumbIsa42** [comment]
Holy sh*t, it worked 

thanks a lot! and so sorry for bothering you  (-_-")
