### ISSUE TITLE
[Feature]:  ✅ The app is all working! 

### ISSUE THREAD

**Issue by bauldihr** [fast4x/RiMusic#4262]
The application is working normally! ✅👍🏼

✅ I would like to thank you for fixing the bugs. It is a team that is perfectly dedicated and the idea of syncing with YouTube Music was excellent and I believe that it resulted in the functioning of Ri Music. 

✅ I just have to thank you for your effort and dedication. I have nothing to complain about, but being part of this application is at its best. 

❗Tip in case I help someone: If you have an application installed and need to update it, uninstall it and install it again.

❗ I synced YouTube Music without Android Auto enabled. 

❗I had restored the application to default settings.

I'M HERE TO TRY TO HELP IN SOME WAY.

**Comment by privacyfreak84** [comment]
Any way to get it working without logging in to YTM? It still doesn't work

**Comment by fast4x** [comment]
@bauldihr thanks, if you want help users, can join to telegram group and do answers.

**Comment by privacyfreak84** [comment]
> If you are using 0.6.58.1 probably in your country is mandatory login.

ViTune works though for some reason 🤔

**Comment by fast4x** [comment]
Try custom version please download https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by privacyfreak84** [comment]
Works with custom version. Thanks!
