### ISSUE TITLE
No se descargan canciones nuevas

### ISSUE THREAD

**Issue by keoo12** [fast4x/RiMusic#4263]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Buscar una cancion
2. Darle en el icono de descargar

### Submit a video

![Screenshot_20241027_223232](https://github.com/user-attachments/assets/5e5082ef-e63c-488e-b5fc-9ae83b810c16)

### What was your expectation?

Esperaba que se descargara correctamente

### What more can you tell us? (Optional)

Pues no se descarga, me sale la notificacion de que no se ha podido descargar

**Comment by fast4x** [comment]
You can play it normally?

**Comment by keoo12** [comment]
Si puedo escuchar canciones normalmente

**Comment by CERS23** [comment]
A mí tampoco me funciona la descarga de canciones nuevas ni me deja reproducir canciones que no tenga descargadas, solo puedo reproducir las que ya tenía descargadas antes de la última actualización

**Comment by Butt3rs** [comment]
Bonjour, ont ne peu plus lire aucune chansons à part celle qui ont déjà été téléchargé auparavant.
       Cordialement,
