### ISSUE TITLE
No sé puede escuchar música 

### ISSUE THREAD

**Issue by Sm0kF** [fast4x/RiMusic#4264]
### Version of RiMusic

v.6.58.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. No reproducía la musica

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Que el problema se solucionará 

### What more can you tell us? (Optional)

Solamente no reproduce la música, es la segunda vez arreglen eso

**Comment by fast4x** [comment]
Try to login in yt from miscellaneous settings
