### ISSUE TITLE
Contenido no reproducido

### ISSUE THREAD

**Issue by Elias11190** [fast4x/RiMusic#4268]
### Version of RiMusic

0.6.58.1

### Android version

9

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Play music error

### Submit a video

![Screenshot_20241028-060357](https://github.com/user-attachments/assets/3d4b36c0-4498-444d-a9ea-e5883542b614)
The songs can't be played, whatever I select it won't play or download 

### What was your expectation?

solution

**Comment by fast4x** [comment]
try to login to ytm from miscellaneous settings

**Comment by fast4x** [comment]
Try custom version please download https://github.com/fast4x/RiMusic/tree/master/customVersion
