### ISSUE TITLE
Some songs playing and some songs showing error "Songs can't be played"

### ISSUE THREAD

**Issue by Divakaran505** [fast4x/RiMusic#4272]
### Version of RiMusic

v0.6.58.1 by fast4x

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically
![Screenshot_2024-10-28-22-39-36-09_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/8fba1fc2-16d1-4e32-8906-4f548efd7924)

Pls note:- I'm always to Play songs in online 

### What was your expectation?

Pls solve this issue, Regularly I'm getting

**Comment by fast4x** [comment]
try to login to ytm from miscellaneous settings

**Comment by fast4x** [comment]
Try custom version please download https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Divakaran505** [comment]
Thanks for your support and it is working now
