### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by Snyret** [fast4x/RiMusic#4275]
### Version of RiMusic

0.6.58.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Log into YouTube music
3. App crashes
4. App now crashes upon entry

### What was your expectation?

The app at least opening

### What more can you tell us? (Optional)

I logged into YouTube music when the 0.6.58 build was released, it crashed, then I updated the apk to the 0.6.58.1 build. Haven't uninstalled yet because all my data would be lost.

**Comment by fast4x** [comment]
enable debug log and after crash send crash log please

**Comment by knighthat** [comment]
you can downgrade it, try older versions to backup your data

**Comment by fast4x** [comment]
wait for next version
