### ISSUE TITLE
Download failing

### ISSUE THREAD

**Issue by BesidesManthan** [fast4x/RiMusic#4276]
### Version of RiMusic

06.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on music
3. Click on download
4. Download failed!

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I expected my playlist to be downloaded but It didn't 

### What more can you tell us? (Optional)

Some specific artists like kendrik and Eminem songs fail to download I personally observed it but still it might be a coincidence

**Comment by fast4x** [comment]
try to login to ytm from miscellaneous settings

**Comment by BesidesManthan** [comment]
> try to login to ytm from miscellaneous settings 

Did this multiple time nothing works I guess the new download manager implement got some kind of a glitch or a bug as far as I remember you told that you've added a new download manager

**Comment by fast4x** [comment]
yep, but I think the problem is another, change audio quality from settings and try again.

**Comment by BesidesManthan** [comment]
> yep, but I think the problem is another, change audio quality from settings and try again.

I'll try though

**Comment by fast4x** [comment]
ok wait for next release

**Comment by Aditysan55** [comment]
Hii... Deva
I am facing the issue of download error it says "download failed" I have updated the app from tithun snd uninstalled md reinstalled it but it doesn't seem to work though please can you look forward to t and reply me about it Sir/Ma'am ?
