### ISSUE TITLE
Downloads are not working I can't download for some reason please fix it :(

### ISSUE THREAD

**Issue by TkJess0987** [fast4x/RiMusic#4278]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

:(

### Logs (Optional)

:(

**Comment by Butt3rs** [comment]
Bonjour, j'ai le même problème impossible de téléchargé les titres et de lire ceux qui ne sont pas enregistré il demande une connexion pour pouvoir lire les fichier. Merci de réglé le problème rapidement. Merci 

Uploading Screen_Recording_20241029_055739.mp4…

**Comment by fast4x** [comment]
Try custom version please download https://github.com/fast4x/RiMusic/tree/master/customVersion
