### ISSUE TITLE
ERROR EN TEMPORIZADOR DE APAGADO

### ISSUE THREAD

**Issue by Tarso644** [fast4x/RiMusic#4279]
### Version of RiMusic

0.6.57.1

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Iniciar reproducción
3. Temporizador de apagado.
4. Seleccionar un tiempo de apagado.
5. El tiempo pasa, Pero la reproducción continúa.
6. El tiempo se desfasa al cambiar las canciones.
7.

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Que la reproducción se apague.

**Comment by fast4x** [comment]
Update to latest version please
