### ISSUE TITLE
Customizing action bar buttons

### ISSUE THREAD

**Issue by abdulkarimx1** [fast4x/RiMusic#428]
### Description

Action bar is very functional in app, but a little basic ( respectfully ) 

### Suggested Solution

Ability to add / configure quick actions (i.e add to playlist icon without clicking 3 dots menu ) or ( removing arrow button on player )
![Screenshot_20240118-014512_RiMusic](https://github.com/fast4x/RiMusic/assets/105733146/50111cae-caa6-429d-aa58-608770197994)

**Comment by fast4x** [comment]
Hello, there might be a space problem if you add many actions. Do you think a number of 6 customizable actions will suffice?

**Comment by abdulkarimx1** [comment]
> Hello, there might be a space problem if you add many actions. Do you think a number of 6 customizable actions will suffice?

I appreciate your kind reply and the huge efforts you are putting in this great app ! 
Regarding the action buttons though, i think that 6 options / buttons will be more than enough;
-maybe a button to quickly add the song to playlist instead accessing it through the 3 dots menu?  
- And being able to remove the arrow button?? ( With all respect its Little Annoying in my very humble opinion )

**Comment by ikanakova** [comment]
> I appreciate your kind reply and the huge efforts you are putting in this great app ! Regarding the action buttons though, i think that 6 options / buttons will be more than enough; -maybe a button to quickly add the song to playlist instead accessing it through the 3 dots menu?
> 
>     * And being able to remove the arrow button?? ( With all respect its Little Annoying in my very humble opinion )

I think hiding the arrow button should be optional.

And as for the action buttons, it would be best if everyone could choose which extra buttons they will / will not display and the rest would be under the three dots.

**Comment by fast4x** [comment]
> > I appreciate your kind reply and the huge efforts you are putting in this great app ! Regarding the action buttons though, i think that 6 options / buttons will be more than enough; -maybe a button to quickly add the song to playlist instead accessing it through the 3 dots menu?
> > And being able to remove the arrow button?? ( With all respect its Little Annoying in my very humble opinion )
> 
> Penso che nascondere il pulsante freccia dovrebbe essere facoltativo.
> 
> E per quanto riguarda i pulsanti di azione, sarebbe meglio se tutti potessero scegliere quali pulsanti extra visualizzeranno o non visualizzeranno e il resto sarebbe sotto i tre punti.

Yes, i like

**Comment by fast4x** [comment]
> > Hello, there might be a space problem if you add many actions. Do you think a number of 6 customizable actions will suffice?
> 
> I appreciate your kind reply and the huge efforts you are putting in this great app ! Regarding the action buttons though, i think that 6 options / buttons will be more than enough; -maybe a button to quickly add the song to playlist instead accessing it through the 3 dots menu?
> 
> * And being able to remove the arrow button?? ( With all respect its Little Annoying in my very humble opinion )

Thank you very much for appreciation.
There are also good collaborators in the project.

Everything you requested in the ticket will be developed soon.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.19
