### ISSUE TITLE
Shuffle in playlist in Android Auto

### ISSUE THREAD

**Issue by Baviera10** [fast4x/RiMusic#4282]
### Description

The button to shuffle songs in playlists has disappeared in Android Auto.

Android 14
Versión V 0.6.58.1

### Suggested Solution

I think the button appeared in previous versions

### Alternatives

Could a single shuffle button be useb for all selelections?

**Comment by fast4x** [comment]
Yes i've removed it, reinserted in future release, i'm working on new player service.

**Comment by Baviera10** [comment]
Ok, thanks for your quick response

**Comment by rafalele71** [comment]
Thank you, I miss shuffle button a lot in Android Auto. 

It would be nice to have the option to set shuffle as the playback mode in Android Auto. As it worked before, you had to select it every time you entered Android Auto and the first song in the selected playlist or album would always start to play.

**Comment by fast4x** [comment]
Implemented available from version 0.6.59

**Comment by rafalele71** [comment]
Thank you

**Comment by darkza** [comment]
Also hearing always the same song. any option in AA to have more "suggested songs" or "new releases"playlist

**Comment by fast4x** [comment]
next version include shuffle mode in AA
