### ISSUE TITLE
Every time I open the application, it always exits by itself. it's been like that for several days 

### ISSUE THREAD

**Issue by Shanatttt** [fast4x/RiMusic#4289]
### Version of RiMusic

v0.6.58

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open Rimusic
2. Boom! Crash happens

### Submit a video

https://github.com/user-attachments/assets/89a21fd0-d06c-4ae8-bdd3-8f0ea9c6d6ba

### What was your expectation?

Hopefully there are no more bugs, and I can play songs again. I'm comfortable using Rimusic but these past few days I've been disappointed after the update 

### What more can you tell us? (Optional)

Previously, every time I wanted to scroll down to see the bottom playlist, suddenly the application would exit by itself. I've restarted my phone and the app, but it's still like that, After that the application cannot be opened

**Comment by Shanatttt** [comment]
There is something wrong...
The app version is v0.6.58.1

By the way, I have previously activated debug mode

**Comment by knighthat** [comment]
How much do you value your database? 

If it's **OK** to rebuild, uninstall the app and reinstall it. Or downgrade version

If it's **NOT OK**, you can try [custom version](https://github.com/fast4x/RiMusic/blob/master/customVersion/app-foss-release.apk)

If none of that works, you can try my [kbuild](https://github.com/knighthat/RiMusic/releases). But **WARNING**, this version is unstable and should only be used for debugging or temporary fix to the current issue

**Comment by Stzyxh** [comment]
I know what the Problem is. You can See in the Video that the playlist page is opened. It crahes because there is a bug that couses the app to crah when opening this page. Try to quickly open another page in the tine when the app isn't crashed

**Comment by knighthat** [comment]
Sometimes the database got corrupted. If you remove and reinstall the app it'll erase database

**Comment by Shanatttt** [comment]
I've tried all the versions you recommended, but the bug is still the same :')
then I downgraded to v0.6.58, Initially the app worked fine... But when I added songs from the device.. the same bug appeared again. 
I reinstalled, and it improved again... Then the same bug appeared again
Do I have to keep reinstalling? But it's very troublesome...
Moreover, when I backed up and used the backup again, some of the songs I saved disappeared from the playlist, and there were also playlists that were lost

**Comment by fast4x** [comment]
wait for new version
