### ISSUE TITLE
Delete downloaded song not working.

### ISSUE THREAD

**Issue by abdulkarimx1** [fast4x/RiMusic#429]
### Steps to reproduce the bug

1; download any song using the app.
2; open library section and navigate to downloads tab.
3; click on song download button.

### Expected behavior

The excepted behavior is the song gets removed from the downloads section whenever toggling the button and when exiting the downloads tab and entering again, the song should be removed ( supposed to ? ) 

### Actual behavior

The button keeps changing between ( white filled ) and ( outlined grey ) and doesn't remove the song from the downloads section, EXCEPT if you deleted all songs from the top right corner ( doesn't make sense if you want to use the app daily and depend on offline downloads ) 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/105733146/005203a2-f5d6-4298-a19e-c33b8a921d7c

### RiMusic version

Latest version ( used apk from github bugs - playlist crash bug thread ) 

### Android version

Android 14

**Comment by fast4x** [comment]
It’s strange, it seems like a problem writing to the download cache. Try changing the size of the download cache and minimizing the player cache from the cache settings. Close and reopen the app

**Comment by fast4x** [comment]
> Latest version ( used apk from github bugs - playlist crash bug thread )
Yes fix are in the next release

**Comment by fast4x** [comment]
For playlist crash test this custom version https://rimusic.xyz/download/

**Comment by abdulkarimx1** [comment]
> For playlist crash test this custom version https://rimusic.xyz/download/

Yes actually I'm already using this version since i searched in the bugs/enhancements before i open a new thread.
regarding the delete button, I tried to lower player cache  as you suggested ( since i was testing to max every option in settings which could affected / broke something.

**Comment by abdulkarimx1** [comment]
> It’s strange, it seems like a problem writing to the download cache. Try changing the size of the download cache and minimizing the player cache from the cache settings. Close and reopen the app

Appreciate your patience in all discussion we had today.

So I tried to reset the cache settings to default/ force stopping app and relaunching it, unfortunately doesn't help. Not sure what could be the issue though.

Also;
Having the same icon for both download / delete from downloads will make it harder for the user to differentiate whether he downloaded the song or not. Will it be suitable for a good improvement to change the downloaded song icon to a tick ( ✔️ ) icon for example? Hope these suggestions will provide the app with more polished UI.

Thanks a lot !

**Comment by fast4x** [comment]
Download have two icons, 
- on song item:
- - filled = downloaded
- - outline = download
- on function for download all:
- - filled = to download all
- - outline = to delete all downloaded

**Comment by abdulkarimx1** [comment]
> Download have two icons,
> 
> * on song item:
> * * filled = downloaded
> * * outline = download
> * on function for download all:
> * * filled = to download all
> * * outline = to delete all downloaded

That's true, but the thing is, it's sometimes stuck on a single state ( for example that the song is already downloaded → filled ) but in fact it's not downloaded ( and vice versa ) that's what i mean.

**Comment by fast4x** [comment]
also icon can filled when is cached by player but not downloaded....
Can set cache player to minimum size or disable it by settings
