### ISSUE TITLE
YouTube Music login doesn't let me play music, if the YT account has two profiles 

### ISSUE THREAD

**Issue by stalyn-sampedro** [fast4x/RiMusic#4290]
### Version of RiMusic

0.6.58.1

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Settings 
3. Miscellaneous 
4. YouTube Music Login
5. Login with an Account that has two profiles 
6. Restart app
7. Boom! Crash happens

### What was your expectation?

Stream music, but no

### What more can you tell us? (Optional)

So, I did all the steps specified in the last update about Login to YT musicein order to work.
However, it didn't.
Tried couple times, it didn't work.
When I logged in, it showed me first profile selection screen. And when selected, it logged to YouTube instead of YouTube Music.
I tried with **another** YouTube account, with only one profile, then **it worked**. It did logged to YouTube Music, and everything worked.
However the two accounts bug still exist, so I leave that out there to some with the same problem.

**Comment by twistios** [comment]
From telegram group Tutorials-Section:

> #howto login to YouTube if you have multiple channels/accounts with the same email id

> After login, do this
> 1) search in the search bar "music.youtube.com"
> 2) open the first video
> 3) open the description
> 4) open YouTube music link
> 5) after the YouTube music page opens, close the app from taskbar

**Comment by Einhander1** [comment]
Unfortunately, the steps rely on a YouTube music link to be there in the description. This is not always the case.

**Comment by twistios** [comment]
See this screenshots:

<details><summary>Step 1</summary>
<p>

![Tutorial_multiple_accounts_1](https://github.com/user-attachments/assets/863dd866-aeb9-4a1f-ba1f-b28fd3a4d840)

</p>
</details> 

<details><summary>Step 2</summary>
<p>

![Tutorial_multiple_accounts_2](https://github.com/user-attachments/assets/db9813fe-fc60-4973-9f92-375053ad38b5)

</p>
</details>

**Comment by AndiLeni** [comment]
I can confirm this issue. Using a YouTube account with multiple profiles does not work.

**Comment by twistios** [comment]
@AndiLeni It does work, you simply have to follow the steps I have posted.

**Comment by AndiLeni** [comment]
@twistios I tried following your steps but the loaded page can not be navigated on my device. I only get shown the profile page. 

Nonetheless, these steps should not be necessary or be documented in the readme or as a helper Text inside the app then the login is performed. Having this piece of information only in a GitHub issue is not ideal 😅

**Comment by twistios** [comment]
@AndiLeni Currently most users ask questions in the telegram group and there is a tutorial section and FAQ section. In the tutorial section this information is included.

**Comment by twistios** [comment]
@AndiLeni you first have to select an account before applying the other steps.

**Comment by Einhander1** [comment]
Those pictures were far more helpful. Found the exact video with the YouTube music link. For those who are still having difficulty finding it, Search for mrm50KbvGnk
That is the exact video with the music.youtube.com link.
