### ISSUE TITLE
Song "Temptation" stops at a certain moment

### ISSUE THREAD

**Issue by woskkdmsosid** [fast4x/RiMusic#4291]
### Version of RiMusic

0.6.58.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Reproduce song "Temptation"
3. Skip to the end
4. Error pops up 
5. A different error pops up: says "El contenido no se puede reproducir"

### Submit a video

(video is compressed)
https://github.com/user-attachments/assets/f1b23bdd-8324-4717-8093-f3397e12f42b

### What was your expectation?

Song should reproduce

### What more can you tell us? (Optional)

It doesnt happen everytime and i think only on this song

**Comment by woskkdmsosid** [comment]
And yes, sorry for writing the other error on spanish, its what it is

**Comment by fast4x** [comment]
Try to update or delete song
