### ISSUE TITLE
Media cannot be played 

### ISSUE THREAD

**Issue by DerH17** [fast4x/RiMusic#4293]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on a song
3. "Media cannot be played"
4. This happened with the 99% of my playlist.

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Media can be played

**Comment by SolsticeSpectrum** [comment]
I had similar issue and it was because I was on 0.6.57, are you sure you're on 0.6.58.1? You can check in Settings->About

**Comment by QuentinCG** [comment]
Thanks, worked for me too with latest.
Strange I didn't get the update automatically.

https://github.com/fast4x/RiMusic/releases/download/v0.6.58.1/app-foss-release.apk

**Comment by bauldihr** [comment]
Mark as problem solved, bro

**Comment by DerH17** [comment]
Ready. Thanks a lot for the support.
