### ISSUE TITLE
Button to play random song in songs tab doesn't work on a fresh start. 

### ISSUE THREAD

**Issue by ShoyebOP** [fast4x/RiMusic#4297]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Close RiMusic. 
2. Force stop RiMusic(just to be specific).
3. Open RiMusic. 
4. Go to songs tab from bottom menu. 
5. Tap the randomizer button. 

### Submit a video

https://github.com/user-attachments/assets/4ba21e07-e96c-4842-9755-2ee67b1b56f1

### What was your expectation?

A random music should start playing from the list. 

### What more can you tell us? (Optional)

The button only doesn't work on a fresh start. Also the same button in the playlists does work. And after using the button in play list or doing any other actions fixes the button but after closing and reopening the app breaks the button again.

**Comment by Soapbosnia** [comment]
Can confirm.

**Comment by twistios** [comment]
It is a known bug and I know why it happens (in the code) but I have not yet found a good solution for it. Maybe I will find one soon.
