### ISSUE TITLE
APP crashes

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#43]
### Steps to reproduce the bug

The APP sometimes crashes when you tap on the artist Name.

### Expected behavior

See screen recording

### Actual behavior

https://github.com/fast4x/RiMusic/assets/103368536/d9856d5d-3a00-449c-8623-782d5e6ed4d1

### RiMusic version

0.6.6

### Android version

Android 12

**Comment by fast4x** [comment]
Fixed, available from version 0.6.7
