### ISSUE TITLE
App closing after going to 'about' tab

### ISSUE THREAD

**Issue by Tdukewarrior** [fast4x/RiMusic#4301]
### Version of RiMusic

0.6.58

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on settings 
3. Click on about tab( with Vimusic interface)
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I clicked on the 'about tab' and the app closes

### Logs (Optional)

2024-10-31 19:37:44:273 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-10-31 19:37:44:603 DEBUG: c - CheckMonthlyPlaylist false
2024-10-31 19:37:44:763 DEBUG: c - CheckMonthlyPlaylist false
2024-10-31 19:37:44:842 DEBUG: c - CheckMonthlyPlaylist true
2024-10-31 19:37:44:843 DEBUG: c - SongsMostPlayed null
2024-10-31 19:37:44:909 DEBUG: c - CheckMonthlyPlaylist true
2024-10-31 19:37:44:909 DEBUG: c - SongsMostPlayed 0
2024-10-31 19:37:44:926 DEBUG: c - CheckMonthlyPlaylist true
2024-10-31 19:37:44:927 DEBUG: c - SongsMostPlayed 0

**Comment by twistios** [comment]
Please also add the crash log. You only send the debug log and as this is a crash (seems so), crash log is more useful (you do not need to remove the debug log).

**Comment by Tdukewarrior** [comment]
Here's the crash logs:

2024-10-31T23:20:56.978:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:252) 
	 android.content.res.Resources.getValue(Resources.java:1439) 
	 N9.d.J(SourceFile:43) 
	 M8.a.h(SourceFile:195) 
	 B0.d.e(SourceFile:486) 
	 i4.b.a(SourceFile:801) 
	 d8.b.k(SourceFile:146) 
	 f0.b.k(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 d8.c.r(SourceFile:108) 
	 f0.b.f(SourceFile:44) 
	 f0.b.r(SourceFile:9) 
	 K.m0.j(SourceFile:144) 
	 f0.b.e(SourceFile:44) 
	 f0.b.j(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.k(SourceFile:269) 
	 f0.b.k(SourceFile:52) 
	 h2.t.b(SourceFile:937) 
	 h2.t.a(SourceFile:228) 
	 h8.j.j(SourceFile:531) 
	 f0.b.e(SourceFile:44) 
	 F.P.k(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1341) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:952) 
	 android.view.Choreographer.doFrame(Choreographer.java:878) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326) 
	 android.os.Handler.handleCallback(Handler.java:1000) 
	 android.os.Handler.dispatchMessage(Handler.java:104) 
	 android.os.Looper.loopOnce(Looper.java:242) 
	 android.os.Looper.loop(Looper.java:362) 
	 android.app.ActivityThread.main(ActivityThread.java:8448) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992) 

2024-10-31T23:21:41.207:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:252) 
	 android.content.res.Resources.getValue(Resources.java:1439) 
	 N9.d.J(SourceFile:43) 
	 M8.a.h(SourceFile:195) 
	 B0.d.e(SourceFile:486) 
	 i4.b.a(SourceFile:801) 
	 d8.b.k(SourceFile:146) 
	 f0.b.k(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 d8.c.r(SourceFile:108) 
	 f0.b.f(SourceFile:44) 
	 f0.b.r(SourceFile:9) 
	 K.m0.j(SourceFile:144) 
	 f0.b.e(SourceFile:44) 
	 f0.b.j(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.k(SourceFile:269) 
	 f0.b.k(SourceFile:52) 
	 h2.t.b(SourceFile:937) 
	 h2.t.a(SourceFile:228) 
	 h8.j.j(SourceFile:531) 
	 f0.b.e(SourceFile:44) 
	 F.P.k(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1341) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:952) 
	 android.view.Choreographer.doFrame(Choreographer.java:878) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326) 
	 android.os.Handler.handleCallback(Handler.java:1000) 
	 android.os.Handler.dispatchMessage(Handler.java:104) 
	 android.os.Looper.loopOnce(Looper.java:242) 
	 android.os.Looper.loop(Looper.java:362) 
	 android.app.ActivityThread.main(ActivityThread.java:8448) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)

**Comment by twistios** [comment]
Please update to 0.6.58.1 and report back what happens.

**Comment by knighthat** [comment]
most likely because of the update. If you can export your database, please do. After that, uninstall and reinstall latest version, then import database

**Comment by fast4x** [comment]
it seems a missed icon used in about...

**Comment by Tdukewarrior** [comment]
Still the same problem even after updating to 0.6.58.1

**Comment by Tdukewarrior** [comment]
I just uninstalled the app and installed the 0.6.58.1 version

**Comment by knighthat** [comment]
can you install [my build](https://github.com/knighthat/RiMusic/releases/tag/weekly-kbuild) and confirms the problem still exists?

> You may need to remove RiMusic from your phone before installing this version

**Comment by Tdukewarrior** [comment]
Yes the problem still persists with your build and now even the 'misc' tab is blank.
![Screenshot_20241101-075815](https://github.com/user-attachments/assets/95649e4e-2bec-48ee-ac83-d9f6863b9888)

**Comment by Tdukewarrior** [comment]
> can you install [my build](https://github.com/knighthat/RiMusic/releases/tag/weekly-kbuild) and confirms the problem still exists?
> 
> > You may need to remove RiMusic from your phone before installing this version

How do I completely remove RiMusic from my device?

**Comment by knighthat** [comment]
> even the 'misc' tab is blank.

I intentionally removed it because it causes trouble with what I'm doing,

> How do I completely remove RiMusic from my device?

Traditional uninstall is sufficient

---

Your situation pretty similar to #3967 and 1 more but I couldn't find the ID. We have yet to find out what's the culprit because it hasn't occur on any of the dev devices (so far), even when we try to replicate it.

**Comment by Tdukewarrior** [comment]
Ok is there anyway I could help?

**Comment by knighthat** [comment]
not really, we'll have to keep shooting until the problem goes away (hopefully)

**Comment by Tdukewarrior** [comment]
Ok. I am still able to use the app and listen to music so you can close this thread. If any other issue shows up I'll put up another thread.
Thanks for all the help

**Comment by knighthat** [comment]
I just pushed some changes to this [build](https://github.com/knighthat/RiMusic/releases/tag/weekly-kbuild). Can you install it and confirm the problem is gone?

**Comment by Tdukewarrior** [comment]
Yep. It's working now. Only is 'misc' tab is missing which I guess you already know abt. But now I am able to go to the 'about' tab without the app closing.

**Comment by knighthat** [comment]
> Only is 'misc' tab is missing which I guess you already know abt

Yes I removed it, will be added in the future, after I get it sorted

> But now I am able to go to the 'about' tab without the app closing.

Thank you for being patient and willing to test solutions

**Comment by Tdukewarrior** [comment]
> Thank you for being patient and willing to test solutions. Always happy to help.Just lmk when you've fixed the 'misc'
Tab.
Thank you for promptly responding to my issue
Keep up the good work.👍

**Comment by knighthat** [comment]
Will do, but if I forgot, you can always check my release tab, build is uploaded automatically every Sunday GMT

**Comment by Tdukewarrior** [comment]
Ok Thank you

**Comment by Tdukewarrior** [comment]
👍
