### ISSUE TITLE
RiMusic is no longer compatible with Android Auto

### ISSUE THREAD

**Issue by Mickael81** [fast4x/RiMusic#4307]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

When I connected my phone to my vehicle, I noticed that the app no ​​longer appeared in the Android Auto menu. Can you tell me how to fix this? Thanks a lot for your help!

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I hope the app will be compatible with Android Auto again

**Comment by fast4x** [comment]
Enable it in miscellaneous settings

**Comment by Mickael81** [comment]
Thank you very much for your reply. 👍
I thought this feature was enabled by default.

**Comment by fast4x** [comment]
In next version not in actual...

**Comment by nomenamecom** [comment]
It happened the same to me, and as a tip for other users I disabled in miscellaneous and disabled as a developer in android auto. After that, I enabled both of them and it run. I used precisely yesterday and it was amazing be able listening without any problem! Thanks a lot cracks!!

**Comment by fast4x** [comment]
Thanks for hack

**Comment by fast4x** [comment]
Update to latest release, Android Auto is auto enabled by default

**Comment by anddam** [comment]
I am on 0.6.76 and I cannot see the app on my Peugeot 2019, I tried both cable and wireless.

Going into the phone Settings > Android Auto > Customize launcher I can see several apps to be shown in the Android Auto screen on the car but RiMusic is not in that list but I can find other foss apps in that list (Jellyfin an VLC for example).

Where can I check Android Auto is actually enabled on my app?

**Comment by KayConsultancy** [comment]
> I am on 0.6.76 and I cannot see the app on my Peugeot 2019, I tried both cable and wireless.
> 
> Going into the phone Settings > Android Auto > Customize launcher I can see several apps to be shown in the Android Auto screen on the car but RiMusic is not in that list but I can find other foss apps in that list (Jellyfin an VLC for example).
> 
> Where can I check Android Auto is actually enabled on my app?

I am also not seeing it on my adroid auto with 0.6.76 version any help?

**Comment by ikanakova** [comment]
This application is [no longer maintained](https://github.com/fast4x/RiMusic/blob/master/README.md#-important). If you have problems, try another one, e. g. a fork Kreate.
