### ISSUE TITLE
cuando quiero descargar una cancion me sale error desconocieo

### ISSUE THREAD

**Issue by nieleal** [fast4x/RiMusic#4309]
### Version of RiMusic

0.6.55

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

https://github.com/user-attachments/assets/27ab09fd-f61a-4f9d-9106-193ad487c8f4

### What was your expectation?

quese arreglafa

**Comment by fast4x** [comment]
Your version is too old update to latest please
