### ISSUE TITLE
[Feature]: Account 

### ISSUE THREAD

**Issue by bauldihr** [fast4x/RiMusic#4312]
### Description

I would like to try to understand why when I log in to YT Music on Ri Music, right after there is an unknown device connected (Nexus 5) to my Google account. I noticed that, when integrating YT Music with Ri Music, soon after the unknown device connects to my account. 
I don't do any other type of login other than this that causes this situation to happen. 
Hugs! 

### Suggested Solution

Check this situation

### Alternatives

N/A

**Comment by knighthat** [comment]
Hi, I'm not sure if I understand your situation. Especially this part:

> I noticed that, when integrating YT Music with Ri Music, soon after the unknown device connects to my account.

What happens afterward? What do you expect from this action?

**Comment by aneesh1122** [comment]
RiMusic is using a simple Google login without any Google libraries to keep it Foss and nexus 5 is the default Google device IIRC.

**Comment by bauldihr** [comment]
> Olá, não tenho certeza se entendi sua situação. Especialmente esta parte:
> 
> > Notei que, ao integrar o YT Music com o Ri Music, logo em seguida o dispositivo desconhecido se conecta à minha conta.
> 
> O que acontece depois? O que você espera dessa ação?

Não aconteceu nada, apenas vi esse dispositivo.

**Comment by bauldihr** [comment]
> O RiMusic está usando um login simples do Google, sem nenhuma biblioteca do Google para mantê-lo. O Foss e o Nexus 5 são os dispositivos padrão do Google, se não me engano.

But is it really normal?

**Comment by bauldihr** [comment]
> Hi, I'm not sure if I understand your situation. Especially this part:
> 
> > I noticed that, when integrating YT Music with Ri Music, soon after the unknown device connects to my account.
> 
> What happens afterward? What do you expect from this action?

Nothing happened, I just saw this device connected to my account. My account is still normal, I didn't see any suspicious activity with my Google account, but I didn't quite understand this issue of the Nexus 5 and Foss with login. It's just that, when I log in to YT Music on Ri Music, right after that a Nexus 5 device appears connected to my account.
