### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by nelsonsiby2345** [fast4x/RiMusic#432]
### Steps to reproduce the bug

1 go to library
2 clicking on custom playlist
3 Then app is crash

### Expected behavior

Open the playlist I Created 

### Actual behavior

Then app crash instead of opening the playlist 

### RiMusic version

0.6.17

### Android version

Android 12

**Comment by fast4x** [comment]
Hello, it's a bug fixed in new release, now you can download a custom version without the error.

Download from https://rimusic.xyz/download
