### ISSUE TITLE
Error desconocido 

### ISSUE THREAD

**Issue by XxReyezzz** [fast4x/RiMusic#4320]
### Version of RiMusic

v0.6.49.2

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Que funcionará

**Comment by twistios** [comment]
Version 0.6.49.2 is pretty old so I guess you should update to the latest version. Probably today or tomorrow version 0.6.59 will be released.

So whatever your problem is, maybe it is solved already in a newer version.
Otherwise, please explain your problem better.
