### ISSUE TITLE
Problem playing songs

### ISSUE THREAD

**Issue by francispa** [fast4x/RiMusic#4322]
### Description

Songs are not playing 

### Suggested Solution

Version change does not work 

### Alternatives

Thank you

### Additional Context

I'm on the version 0.6.57.1 When I want to play a song it does not play and tells me "Madia cannot be played"
![SmartSelect_20241101_174911](https://github.com/user-attachments/assets/f118b7b0-b358-4725-a32c-3af719286711)

**Comment by Adam69003** [comment]
Same for me. Latest version downloaded without any New changes. The bug IS still here

**Comment by Adam69003** [comment]
> > Same for me. Latest version downloaded without any New changes. The bug IS still here
> 
> Clear application data. Then log in to account

Witch account are you speaking about ? YT music ? 
I didn't find the file related to the app in my storage
![Screenshot_2024-11-02-17-50-38-523_com google android documentsui](https://github.com/user-attachments/assets/5ee2daa5-4faf-4954-abc1-ed4d3f23141a)

**Comment by JesusRoblesL** [comment]
A ver, yo arreglé el problerma de la siguiente manera:
1- Fuí a Rimusic, Ajustes, Misceláneo y ahí activé la casilla "Enable YoutubeMusic Login"
2- Instalé en mi movil la app de Youtube Music.
3- Me logué en ella con mi usuario y contraseña de Gmail, es decir, el mismo que Gmail, Youtube, Photos, Drive y tal...
4- Volví a abrir Rimusic y ya funcionaba.
Disfrutad.

**Comment by JesusRoblesL** [comment]
I fixed the problem in the following way:
1- I went to Rimusic, Settings, Miscellaneous and there I activated the "Enable YoutubeMusic Login" box
2- I installed the Youtube Music app on my smartphone.
3- I logged in with my Gmail username and password, that is, the same as Gmail, Youtube, Photos, Drive and such...
4- I opened Rimusic again and it was working.
Enjoy.
