### ISSUE TITLE
[Feature]: Account Questions 

### ISSUE THREAD

**Issue by bauldihr** [fast4x/RiMusic#4325]
### Description

I would like to try to understand why when I log in to YT Music on Ri Music, right after there is an unknown device connected (Nexus 5) to my Google account. I noticed that, when integrating YT Music with Ri Music, soon after the unknown device connects to my account.
I don't do any other type of login other than this that causes this situation to happen.

Nothing happened, I just saw this device connected to my account. My account is still normal, I didn't see any suspicious activity with my Google account, but I didn't quite understand this issue of the Nexus 5 and Foss with login. It's just that, when I log in to YT Music on Ri Music, right after that a Nexus 5 device appears connected to my account.

So much so that if I disconnect the Nexus 5, it connects again, but as soon as I open the application.

Hugs, always! 

### Suggested Solution

.

### Alternatives

.

### Additional Context

.

**Comment by fast4x** [comment]
RiMusic not send device type, so it's basic device name
