### ISSUE TITLE
No puedo escuchar musica sin internet

### ISSUE THREAD

**Issue by Elvicius** [fast4x/RiMusic#4328]
### Version of RiMusic

CustomVersion

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

No puedo escuchar musica sin internet

### Submit a video

No puedo escuchar musica sin internet

### What was your expectation?

No puedo escuchar musica sin internet

### What more can you tell us? (Optional)

No puedo escuchar musica sin internet

**Comment by knighthat** [comment]
is the song downloaded on your device?

**Comment by Elvicius** [comment]
Cuando no tengo internet, me saca de la app

**Comment by knighthat** [comment]
thanks for your response, I pushed a fix at #4339. Please wait until next release
