### ISSUE TITLE
Add a tab with proxy

### ISSUE THREAD

**Issue by Crayz310** [fast4x/RiMusic#433]
### Description

Tab with proxy settings

### Suggested Solution

The thing is that in some countries (unfortunately mine is also on this list) yt music does not work.
According to this the app does not work as intended.
It would be good if there were proxy settings inside the app.
Because using third-party applications with proxy for the sake of listening is very not convenient.

### Alternatives

Using third-party proxy applications

### Additional Context

I really hope you add a feature like this.

**Comment by fast4x** [comment]
Hello, I am sorry that you have these problems in your area. Ok, I plan the development of the required functionality.
Thanks

**Comment by ikanakova** [comment]
Perhaps @SuhasDissa would agree to use his solution: https://github.com/vfsfitvnm/ViMusic/pull/1089

**Comment by fast4x** [comment]
Interesting, I try to look at its pull if compatible with RiMusic

**Comment by Crayz310** [comment]
> Hello, I am sorry that you have these problems in your area. Ok, I plan the development of the required functionality. Thanks

When approximately will this update come out?

**Comment by fast4x** [comment]
> > Hello, I am sorry that you have these problems in your area. Ok, I plan the development of the required functionality. Thanks
> 
> When approximately will this update come out?

Tonight

**Comment by fast4x** [comment]
> Interesting @SuhasDissa, I try to look at its pull if compatible with RiMusic

@SuhasDissa 
I started from your code on the ViMusic pull request, I just made a few small changes and entered your code. It works without problems, thank you. I’ll put your name as a contributor in the app.  Thank you

**Comment by fast4x** [comment]
Implemented, available from version 0.6.18
Settings Tab Other

**Comment by Crayz310** [comment]
> Implemented, available from version 0.6.18 Settings Tab Other

When is the actual build coming out?

**Comment by fast4x** [comment]
Tonight

**Comment by fast4x** [comment]
Releases are scheduled every Friday

**Comment by Crayz310** [comment]
> Releases are scheduled every Friday

And the approximate time (UTC)

**Comment by fast4x** [comment]
Approximate UTC 21:00 / 22:00
