### ISSUE TITLE
Problemas de reproducción 

### ISSUE THREAD

**Issue by Aetherimpact802** [fast4x/RiMusic#4330]
### Version of RiMusic

0.6.58.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Al terminar la reproducción de una canción La aplicación se cierra solo y no se puede volver a abrir solo borrando todos los datos o desinstalando y volviendo a instalarla se puede entrar a la aplicación 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Que no se cierre la aplicación 

### What more can you tell us? (Optional)

La versión más reciente tiene muchas fallas que las versiones anteriores no estaban por favor revisar la aplicación a fondo y corregir estos fallos lo antes posible para futuras versiones

**Comment by knighthat** [comment]
can you provide a video and logs?
