### ISSUE TITLE
App stops working when you pause music on lock screen

### ISSUE THREAD

**Issue by Turbo-Peugeot** [fast4x/RiMusic#4331]
### Version of RiMusic

0.6.58.1

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Play song
3. Lock screen
4. Pause music with Bluetooth device
5. Try to unpause (not working)
6. Unlock phone and unpause in the app (not working)
7. Restart app (works again)

### Submit a video

Not possible

### What was your expectation?

Supposed to pause and unpause via Bluetooth device on lock screen

**Comment by fast4x** [comment]
It seems to be solved in next version 0.6.59, report if it work after release, thanks

**Comment by Vishcot** [comment]
> It seems to be solved in next version 0.6.59, report if it work after release, thanks

update when?

**Comment by fast4x** [comment]
next Friday if all ok
