### ISSUE TITLE
Is it possible to stream on a connected speaker without having advertising because it is not premium

### ISSUE THREAD

**Issue by Mikkaddo** [fast4x/RiMusic#4336]
### Description

I would like to connect RIMUSIC to my SONOS S1 smart speaker. Thank you in advance

### Suggested Solution

I would like to connect RIMUSIC to my SONOS S1 smart speaker. Thank you in advance

**Comment by twistios** [comment]
If your speaker supports Bluetooth, then you can already simply connect via that.

**Comment by Mikkaddo** [comment]
It's a SONOS S1 speaker, a priori it needs to connect to wifi. I didn't find a bluetooth connection for him. In fact, ideally would be a small icon that allows you to cast on the speaker once connected. What's curious is that even if you have connected it to the YT Music account in SONOS, it can't find the playlists. In any case, for the rest, your application is great. Thank you all

________________________________

**Comment by twistios** [comment]
RiMusic currently does not support YTM sync (it seems that this is a part of your question).

**Comment by twistios** [comment]
If the Sonos App is required for streaming, then there is a high probability that RiMusic can not do anything about your problem.

**Comment by twistios** [comment]
It seems that your speaker does not support Bluetooth and we can not change the Sonos App, the only possible way would be via a local music library.
As RiMusic stores the (cached and downloaded) songs encrypted, RiMusic can not be added in a network storage.
So it seems that your request is not possible.

**Comment by MicDan00** [comment]
Hi, same question for Sonos Beam system. In fact, Rimusic should have a function, like in Spotify, to list all audio systems connected on the same local network at home, to choose which one to play on and stream RiMusic on. Can devs team have a look at this proposal?
Thanks
