### ISSUE TITLE
getting an error song can't be played

### ISSUE THREAD

**Issue by olumolu** [fast4x/RiMusic#4337]
### Version of RiMusic

0.6.57.1 (64)

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on play a mucic
4. Song cant be played

### Submit a video

![IMG_20241103_232530218~2](https://github.com/user-attachments/assets/2c05d109-3b0c-423a-b369-9367314c6c7c)

### What was your expectation?

i clicked on play and after sometime showing song cant be played

### What more can you tell us? (Optional)

Installed from fdroid

**Comment by razor-sama** [comment]
I am facing the same issue as OP.

**Comment by knighthat** [comment]
are you logged in?

**Comment by AlexIs387** [comment]
Update to the latest listed here:

https://github.com/fast4x/RiMusic/releases/tag/v0.6.58.1

**Comment by jahidulislamjahid** [comment]
Facing the same issue as OP, and yes I'm on the latest version which is 0.6.58.1 please kindly resolve the issue.
