### ISSUE TITLE
Ripristinare l'ordine originale delle playlist

### ISSUE THREAD

**Issue by Puxio** [fast4x/RiMusic#434]
### Description

Quando si aggiunge una playlist questa viene ordinata e non si può ripristinare l'ordine originale.

### Suggested Solution

Si potrebbe aggiungere un bottone per visualizzarla secondo l'ordine originale

**Comment by fast4x** [comment]
Ciao, ti riferisci ad una playlist online che importi con il pulsante + ?

**Comment by Puxio** [comment]
Sì esattamente, importando la playlist online questa viene ordinata e non è più possibile importare l'ordine originale.

**Comment by fast4x** [comment]
I'll try it

**Comment by Puxio** [comment]
Quando li carica sono nell'ordine giusto

**Comment by fast4x** [comment]
Give me a feedback, resync the playlist from the playlist internal menu. 
Is the original order restored?

**Comment by Puxio** [comment]
​No, the default sorting order (alphabetical descending) remains set

**Comment by fast4x** [comment]
Ok thanks

**Comment by fast4x** [comment]
Fixed one bug in playlist sync, now sync reset original sort order.
New version are new sorting options https://github.com/fast4x/RiMusic/issues/286
