### ISSUE TITLE
The music doesn't play, the app says "unknow error" and i have resinstalled the app several times, but the error remains.

### ISSUE THREAD

**Issue by whotfisrose** [fast4x/RiMusic#4340]
### Version of RiMusic

0.6.49.2

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. I open RiMusic
2. I play any song
3. The song doesn't work
4. The error appears

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

pls fix it

**Comment by martkol** [comment]
The latest published version is 6.48.1, isn't it?

**Comment by twistios** [comment]
The latest published version is 0.6.58.1.
