### ISSUE TITLE
About page crashes 

### ISSUE THREAD

**Issue by mariuslohoho** [fast4x/RiMusic#4342]
### Version of RiMusic

0.6.58.1

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on settings
3. Click on about
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

No crash

### What more can you tell us? (Optional)

Maybe some files are missing? 
Also I'm using vimusid ui layout if that matters

### Logs (Optional)

2024-11-03T23:22:47.158:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:261) 
	 android.content.res.Resources.getValue(Resources.java:1513) 
	 N9.d.J(SourceFile:43) 
	 M8.a.h(SourceFile:195) 
	 B0.d.e(SourceFile:486) 
	 i4.b.a(SourceFile:801) 
	 d8.b.k(SourceFile:146) 
	 f0.b.k(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 d8.c.r(SourceFile:108) 
	 f0.b.f(SourceFile:44) 
	 f0.b.r(SourceFile:9) 
	 K.m0.j(SourceFile:144) 
	 f0.b.e(SourceFile:44) 
	 f0.b.j(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.k(SourceFile:269) 
	 f0.b.k(SourceFile:52) 
	 h2.t.b(SourceFile:937) 
	 h2.t.a(SourceFile:228) 
	 h8.j.j(SourceFile:531) 
	 f0.b.e(SourceFile:44) 
	 F.P.k(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1153) 
	 android.view.Choreographer.doFrame(Choreographer.java:1069) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by fast4x** [comment]
Fixed in next version 0.6.59
