### ISSUE TITLE
Where is the Invasor Album by artist Rodrigo Zin!!?

### ISSUE THREAD

**Issue by Rzinn167** [fast4x/RiMusic#4343]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

I go to ri music.
And I search for the artist Rodrigo Zin and go to songs.
But I can't find the songs from his album "Invasor".
There are only songs from the live show he did, but that's not the one I want to hear.
Please fix this problem.

### Submit a video

https://github.com/user-attachments/assets/ba786f3e-acf5-411c-835c-493dff759a1e

### What was your expectation?

In the next update, I will be able to listen to the songs from Rodrigo Zin's album "invasor".

### What more can you tell us? (Optional)

.

### Logs (Optional)

.

**Comment by twistios** [comment]
The album is also not shown on YTM so RiMusic can not do anything about it. If you have a YT link, you can paste it in the URL-Search of RiMusic and there use the audio-icon for the audio version.
