### ISSUE TITLE
Problemas en interfaz de la aplicación 

### ISSUE THREAD

**Issue by Aetherimpact802** [fast4x/RiMusic#4344]
### Version of RiMusic

0.6.58.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abre RiMusic
2. Click en ajustes 
3. Click en interfaz 
4. Click en interfaz de vimusic
5. Click en acerca de 
6. La aplicación se cierra 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

https://github.com/user-attachments/assets/41da5cb8-7b86-4c60-91f4-dd228fcaf558

### What was your expectation?

no debería de cerrar la aplicación 

### Logs (Optional)

2024-11-03T00:34:51.188:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216) 
	 android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96) 
	 android.content.res.Resources.getValue(Resources.java:1345) 
	 N9.d.J(SourceFile:43) 
	 M8.a.h(SourceFile:195) 
	 B0.d.e(SourceFile:486) 
	 i4.b.a(SourceFile:801) 
	 d8.b.k(SourceFile:146) 
	 f0.b.k(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 d8.c.r(SourceFile:108) 
	 f0.b.f(SourceFile:44) 
	 f0.b.r(SourceFile:9) 
	 K.m0.j(SourceFile:144) 
	 f0.b.e(SourceFile:44) 
	 f0.b.j(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.k(SourceFile:269) 
	 f0.b.k(SourceFile:52) 
	 h2.t.b(SourceFile:937) 
	 h2.t.a(SourceFile:228) 
	 h8.j.j(SourceFile:531) 
	 f0.b.e(SourceFile:44) 
	 F.P.k(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:888) 
	 android.view.Choreographer.doFrame(Choreographer.java:816) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078) 
	 android.os.Handler.handleCallback(Handler.java:873) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loop(Looper.java:201) 
	 android.app.ActivityThread.main(ActivityThread.java:6810) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 

2024-11-03T00:49:33.962:	java.lang.IllegalArgumentException: Progress percentage must be within 0.0f inclusive to 1.0f inclusive. Value: 1.0000697
	 N9.d.p(SourceFile:33) 
	 i4.c.h0(SourceFile:1921) 
	 h8.s.a(SourceFile:235) 
	 i4.l.s(SourceFile:1446) 
	 k8.l0.k(SourceFile:30) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:888) 
	 android.view.Choreographer.doFrame(Choreographer.java:816) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078) 
	 android.os.Handler.handleCallback(Handler.java:873) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loop(Looper.java:201) 
	 android.app.ActivityThread.main(ActivityThread.java:6810) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 

2024-11-03T20:19:53.008:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216) 
	 android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96) 
	 android.content.res.Resources.getValue(Resources.java:1345) 
	 N9.d.J(SourceFile:43) 
	 M8.a.h(SourceFile:195) 
	 B0.d.e(SourceFile:486) 
	 i4.b.a(SourceFile:801) 
	 d8.b.k(SourceFile:146) 
	 f0.b.k(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 d8.c.r(SourceFile:108) 
	 f0.b.f(SourceFile:44) 
	 f0.b.r(SourceFile:9) 
	 K.m0.j(SourceFile:144) 
	 f0.b.e(SourceFile:44) 
	 f0.b.j(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.k(SourceFile:269) 
	 f0.b.k(SourceFile:52) 
	 h2.t.b(SourceFile:937) 
	 h2.t.a(SourceFile:228) 
	 h8.j.j(SourceFile:531) 
	 f0.b.e(SourceFile:44) 
	 F.P.k(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:888) 
	 android.view.Choreographer.doFrame(Choreographer.java:816) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078) 
	 android.os.Handler.handleCallback(Handler.java:873) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loop(Looper.java:201) 
	 android.app.ActivityThread.main(ActivityThread.java:6810) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 

2024-11-03T22:06:16.170:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216) 
	 android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96) 
	 android.content.res.Resources.getValue(Resources.java:1345) 
	 N9.d.J(SourceFile:43) 
	 M8.a.h(SourceFile:195) 
	 B0.d.e(SourceFile:486) 
	 i4.b.a(SourceFile:801) 
	 d8.b.k(SourceFile:146) 
	 f0.b.k(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 d8.c.r(SourceFile:108) 
	 f0.b.f(SourceFile:44) 
	 f0.b.r(SourceFile:9) 
	 K.m0.j(SourceFile:144) 
	 f0.b.e(SourceFile:44) 
	 f0.b.j(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.k(SourceFile:269) 
	 f0.b.k(SourceFile:52) 
	 h2.t.b(SourceFile:937) 
	 h2.t.a(SourceFile:228) 
	 h8.j.j(SourceFile:531) 
	 f0.b.e(SourceFile:44) 
	 F.P.k(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:888) 
	 android.view.Choreographer.doFrame(Choreographer.java:816) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078) 
	 android.os.Handler.handleCallback(Handler.java:873) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loop(Looper.java:201) 
	 android.app.ActivityThread.main(ActivityThread.java:6810) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 

2024-11-03T23:08:05.881:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216) 
	 android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96) 
	 android.content.res.Resources.getValue(Resources.java:1345) 
	 N9.d.J(SourceFile:43) 
	 M8.a.h(SourceFile:195) 
	 B0.d.e(SourceFile:486) 
	 i4.b.a(SourceFile:801) 
	 d8.b.k(SourceFile:146) 
	 f0.b.k(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 d8.c.r(SourceFile:108) 
	 f0.b.f(SourceFile:44) 
	 f0.b.r(SourceFile:9) 
	 K.m0.j(SourceFile:144) 
	 f0.b.e(SourceFile:44) 
	 f0.b.j(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.k(SourceFile:269) 
	 f0.b.k(SourceFile:52) 
	 h2.t.b(SourceFile:937) 
	 h2.t.a(SourceFile:228) 
	 h8.j.j(SourceFile:531) 
	 f0.b.e(SourceFile:44) 
	 F.P.k(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:888) 
	 android.view.Choreographer.doFrame(Choreographer.java:816) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078) 
	 android.os.Handler.handleCallback(Handler.java:873) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loop(Looper.java:201) 
	 android.app.ActivityThread.main(ActivityThread.java:6810) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 

2024-11-03T23:13:15.774:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216) 
	 android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96) 
	 android.content.res.Resources.getValue(Resources.java:1345) 
	 N9.d.J(SourceFile:43) 
	 M8.a.h(SourceFile:195) 
	 B0.d.e(SourceFile:486) 
	 i4.b.a(SourceFile:801) 
	 d8.b.k(SourceFile:146) 
	 f0.b.k(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 d8.c.r(SourceFile:108) 
	 f0.b.f(SourceFile:44) 
	 f0.b.r(SourceFile:9) 
	 K.m0.j(SourceFile:144) 
	 f0.b.e(SourceFile:44) 
	 f0.b.j(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.k(SourceFile:269) 
	 f0.b.k(SourceFile:52) 
	 h2.t.b(SourceFile:937) 
	 h2.t.a(SourceFile:228) 
	 h8.j.j(SourceFile:531) 
	 f0.b.e(SourceFile:44) 
	 F.P.k(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:888) 
	 android.view.Choreographer.doFrame(Choreographer.java:816) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078) 
	 android.os.Handler.handleCallback(Handler.java:873) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loop(Looper.java:201) 
	 android.app.ActivityThread.main(ActivityThread.java:6810) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 

2024-11-04T00:08:36.110:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216) 
	 android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96) 
	 android.content.res.Resources.getValue(Resources.java:1345) 
	 N9.d.J(SourceFile:43) 
	 M8.a.h(SourceFile:195) 
	 B0.d.e(SourceFile:486) 
	 i4.b.a(SourceFile:801) 
	 d8.b.k(SourceFile:146) 
	 f0.b.k(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 d8.c.r(SourceFile:108) 
	 f0.b.f(SourceFile:44) 
	 f0.b.r(SourceFile:9) 
	 K.m0.j(SourceFile:144) 
	 f0.b.e(SourceFile:44) 
	 f0.b.j(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.k(SourceFile:269) 
	 f0.b.k(SourceFile:52) 
	 h2.t.b(SourceFile:937) 
	 h2.t.a(SourceFile:228) 
	 h8.j.j(SourceFile:531) 
	 f0.b.e(SourceFile:44) 
	 F.P.k(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:888) 
	 android.view.Choreographer.doFrame(Choreographer.java:816) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078) 
	 android.os.Handler.handleCallback(Handler.java:873) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loop(Looper.java:201) 
	 android.app.ActivityThread.main(ActivityThread.java:6810) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 

2024-11-04T00:12:47.869:	java.lang.IllegalArgumentException: Progress percentage must be within 0.0f inclusive to 1.0f inclusive. Value: 1.0000597
	 N9.d.p(SourceFile:33) 
	 i4.c.h0(SourceFile:1921) 
	 h8.s.a(SourceFile:235) 
	 i4.l.s(SourceFile:1446) 
	 k8.l0.k(SourceFile:30) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:888) 
	 android.view.Choreographer.doFrame(Choreographer.java:816) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078) 
	 android.os.Handler.handleCallback(Handler.java:873) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loop(Looper.java:201) 
	 android.app.ActivityThread.main(ActivityThread.java:6810) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 

2024-11-04T00:13:21.756:	java.lang.IllegalArgumentException: Progress percentage must be within 0.0f inclusive to 1.0f inclusive. Value: 1.00001
	 N9.d.p(SourceFile:33) 
	 i4.c.h0(SourceFile:1921) 
	 h8.s.a(SourceFile:235) 
	 i4.l.s(SourceFile:1446) 
	 k8.l0.k(SourceFile:30) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:888) 
	 android.view.Choreographer.doFrame(Choreographer.java:816) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078) 
	 android.os.Handler.handleCallback(Handler.java:873) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loop(Looper.java:201) 
	 android.app.ActivityThread.main(ActivityThread.java:6810) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 

2024-11-04T00:20:44.692:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216) 
	 android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96) 
	 android.content.res.Resources.getValue(Resources.java:1345) 
	 N9.d.J(SourceFile:43) 
	 M8.a.h(SourceFile:195) 
	 B0.d.e(SourceFile:486) 
	 i4.b.a(SourceFile:801) 
	 d8.b.k(SourceFile:146) 
	 f0.b.k(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 d8.c.r(SourceFile:108) 
	 f0.b.f(SourceFile:44) 
	 f0.b.r(SourceFile:9) 
	 K.m0.j(SourceFile:144) 
	 f0.b.e(SourceFile:44) 
	 f0.b.j(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.k(SourceFile:269) 
	 f0.b.k(SourceFile:52) 
	 h2.t.b(SourceFile:937) 
	 h2.t.a(SourceFile:228) 
	 h8.j.j(SourceFile:531) 
	 f0.b.e(SourceFile:44) 
	 F.P.k(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:888) 
	 android.view.Choreographer.doFrame(Choreographer.java:816) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078) 
	 android.os.Handler.handleCallback(Handler.java:873) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loop(Looper.java:201) 
	 android.app.ActivityThread.main(ActivityThread.java:6810) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by fast4x** [comment]
Fixed available from version 0.6.59
