### ISSUE TITLE
App language selection missing values

### ISSUE THREAD

**Issue by martkol** [fast4x/RiMusic#4349]
### Version of RiMusic

all

### Android version

all

### Description of this bug

**Azerbaijani** (100% translated) and **Tamil** are not available in the language selection. 
The values would also be missing in the strings XML files.

**Persian** is available for selection in the app but not available on Crowdin and therefore only English.

**Comment by fast4x** [comment]
yes

**Comment by fast4x** [comment]
Tamil is translated as minimal

**Comment by fast4x** [comment]
Fixed available from version 0.6.59
