### ISSUE TITLE
My praise for the app ✅ + Delay in song lyrics 

### ISSUE THREAD

**Issue by bauldihr** [fast4x/RiMusic#4353]
### Version of RiMusic

0.6.58.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

✅ First of all, I would like to really thank you for providing the best in building this application. I'm just loving it from the heart. Just a small delay in synchronizing the lyrics with the music composer. In the previous version, it was flawless! 

### Submit a video

https://github.com/user-attachments/assets/61dcf634-58f0-4295-8c28-0d2becd8edb6

### What was your expectation?

That the lyrics sync with the singer of the song. 

### What more can you tell us? (Optional)

__

### Logs (Optional)

___

**Comment by twistios** [comment]
For this song it seems to be slightly too early. Also if the lyrics match exactly depends on if the lyrics are actually for this version of the song or a different one (that was just similar enough).

https://github.com/user-attachments/assets/76371c87-49c9-42a8-9902-2319239499b2
