### ISSUE TITLE
Press once again to exit

### ISSUE THREAD

**Issue by Sinisterf1** [fast4x/RiMusic#4356]
### Version of RiMusic

4.9.2

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on any playlist 
3. Use back gesture
4. It shows "press again to exit" again and again whenever i use back gesture of my phone(android)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

https://github.com/user-attachments/assets/f08c071a-294a-4537-8b89-0c56785f7f5b

### What was your expectation?

I want it to go back to home page in only one back gesture

### What more can you tell us? (Optional)

The message "click again to exit" is appearing again and again when I use back gesture of the android 

### Logs (Optional)

2024-11-05 19:29:28:937 DEBUG: MainApplication - Log enabled at /data/user/0/it.vfsfitvnm.Apple/files/logs

**Comment by fast4x** [comment]
This is fixed in the next version
