### ISSUE TITLE
Traduction de Crowdin non prise en compte

### ISSUE THREAD

**Issue by Mickael81** [fast4x/RiMusic#4358]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Bonjour,

J'ai essayé d'apporter ma contribution à la traduction via Crowdin mais force est de constater que les améliorations de traduction que j'ai proposé dans ma langue n'ont pas été prises en compte dans la dernière mise à jour de l'application RiMusic... 
Est-ce normal ? À quoi est-ce dû ? Comment puis-je savoir si les suggestions de traduction ont bien été prises en compte sur Crowdin ou si elles ont été refusées ?

### What was your expectation?

J'aimerais améliorer la traduction de RiMusic

### What more can you tell us? (Optional)

J'ai déjà réussi à traduire une autre application publiée sur GitHub et qui utilise Weblate pour la traduction et j'aurais aimé pouvoir faire de même pour RiMusic avec Crowdin. 

L'utilisation de Crowdin ou de Weblate pour traduire une application semble être différente.

**Comment by ikanakova** [comment]
If it is a new translation, the suggestions are directly implemented in the application. If they are changes to an existing and approved translation, they are implemented after the changes are approved by the language proofreader. Unfortunately, some languages no longer have a proofreader to approve changes.

**Comment by fast4x** [comment]
I'll try to investigate with French Proofreader, eventually you want to became a proofreader for your language?

**Comment by Mickael81** [comment]
Hello and thank you very much for your help. 
Yes, with your agreement I would like to be a proofreader for French. I noticed that the application was well translated. For the moment, there are no major modifications to the translation but simply some improvements.

**Comment by Mickael81** [comment]
My account name in Crowdin is Mickael_Binos

**Comment by fast4x** [comment]
Done, make good use, thanks, i've added you in translators in project page, will be visible with next release

**Comment by Mickael81** [comment]
Thank you very much! 🙂👍
