### ISSUE TITLE
App is acting offline 

### ISSUE THREAD

**Issue by Sihu502** [fast4x/RiMusic#436]
### Steps to reproduce the bug

Opening the app

### Expected behavior

It should load up the music 

### Actual behavior

But it's all just blank 

### Screenshots/Screen recordings

![Screenshot_20240118-231747](https://github.com/fast4x/RiMusic/assets/157068015/b7bd05ec-6648-4fc0-97ba-4d3e26cead81)

### RiMusic version

V0.6.17

### Android version

Android 12

### Additional information

I really don't know what to do

**Comment by fast4x** [comment]
Try to play a Song, close and reopen.

**Comment by Logan7899** [comment]
@fast4x when you will release new version of RIMusic. It has been a week

**Comment by fast4x** [comment]
> @fast4x when you will release new version of RIMusic. It has been a week

Releases are scheduled every Friday

**Comment by fast4x** [comment]
Tonight 21/22 UTC
