### ISSUE TITLE
Bring Back This Feature!

### ISSUE THREAD

**Issue by brosteque** [fast4x/RiMusic#4361]
### Description

Recently, the new update make this one useful feature that i always used, is gone. I hope that the developer can bring back this feature or atleast make the toggle on the option.

### Suggested Solution

Bring this feature into songs main display.

![Screenshot_2024-11-01-11-56-55-51_91b67804b5fb3353a77fb824d6bb0b50_1](https://github.com/user-attachments/assets/7c0688b0-2a03-4b52-ad59-492d82b19169)

(into here) 
![Screenshot_2024-10-28-15-54-52-01_91b67804b5fb3353a77fb824d6bb0b50_1](https://github.com/user-attachments/assets/1c991b9d-2ed3-434d-a822-80185665b612)

and also bring back the hide feature
![Screenshot_2024-10-28-15-54-59-61_91b67804b5fb3353a77fb824d6bb0b50_1](https://github.com/user-attachments/assets/7e529831-580c-4838-a952-c41178f778a9)

**Comment by fast4x** [comment]
Is it a command or a kind request?
