### ISSUE TITLE
When I click the shuffle button in the songs tab it doesn't do anything 

### ISSUE THREAD

**Issue by Anshuman2259** [fast4x/RiMusic#4362]
### Version of RiMusic

0.6.58.1

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on songs
3. Click on shuffle on top
4. Boom! Nothing happens

### What was your expectation?

It should have played a random song from the songs tab and shuffled the rest

**Comment by ShoyebOP** [comment]
Already issued and completed #4297
