### ISSUE TITLE
[Feature]: Disable Recommended Songs in Playlist

### ISSUE THREAD

**Issue by burakerdem** [fast4x/RiMusic#4363]
### Description

There are at least 4-5 songs in every playlist that I didn't save in. I think these are recommended songs based on the playlist. Is it possible to disable those "recommended songs" in playlists?

### Suggested Solution

A setting would be great to disable recommended songs in playlists.

**Comment by fast4x** [comment]
Simple, disable from icon in playlist 
![Screenshot_20241106_180549](https://github.com/user-attachments/assets/7896fc4e-f5be-4853-a183-499ab04971ea)
