### ISSUE TITLE
Unable to play songs !? Audio Quality format was set to high.

### ISSUE THREAD

**Issue by subhajitkrchaki** [fast4x/RiMusic#4364]
### Version of RiMusic

0.6.58.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Contributors will fix that probably 

### What more can you tell us? (Optional)

It showing song can't be played
![Screenshot_2024-11-06-20-35-25-213_it fast4x rimusic](https://github.com/user-attachments/assets/7b03e0bc-9cce-4bce-b70a-8137f8d60144)

**Comment by fast4x** [comment]
Try set to auto

**Comment by Alonely0** [comment]
I can reproduce it (been hit by it for like two weeks), and auto does indeed fix it.

**Comment by fast4x** [comment]
Wait next release
