### ISSUE TITLE
Import Database/Restore Database Feature

### ISSUE THREAD

**Issue by K2-2K** [fast4x/RiMusic#4367]
### Description

If you have vimusic or vitune then you can import your database from the files and have your playlists all organised immediately (I'm sure you know this) maybe the feature actually exists but I don't know...

### Suggested Solution

I would like the import database feature (or restore as you'd like to call it) to be added to this app as i think it would vastly improve the functionality, as of right now I can't find that feature but if it exists please do let me know.

**Comment by twistios** [comment]
It seems that you found the menu-option for it.

**Comment by K2-2K** [comment]
Yes I was just having trouble navigating lol
