### ISSUE TITLE
Allow to sort playlist however we want

### ISSUE THREAD

**Issue by K2-2K** [fast4x/RiMusic#4368]
### Description

We can drag our favourite songs IN the playlist and sort them according to our wants, and not rely on filters to sort our songs in our playlists, this would make thr user experience much more enhanced.

### Suggested Solution

Instead of relying on filters like "date added" to sort the playlist, a feature where you could drag and sort songs (like you do in the queue) according to your needs would be a great feature, so we could have our pre sorted playlist that doesn't need to be changed in the queue. Thank you for the app and I hope you consider this. (Also Idk if this is just me but the app is a bit laggy when in the queue and animations are a bit choppy, might just be my a32 4g which is pretty old tho)

**Comment by fast4x** [comment]
Just possible, hold arrow button and sort as you want.

**Comment by K2-2K** [comment]
That's only by filters, I'm not sure you know what I mean, I meant that in the playlist you can drag and drop songs and sort them that way instead of relying on filters and the arrow, but i tried what you said and it didn't allow me to drag and drop in the order i wanted.

**Comment by K2-2K** [comment]
Nvm found it took a while 💀

**Comment by singhh9596** [comment]
It's already there. What my concern is, the playlists I imported were not in the same order as I have in my youtube app.
