### ISSUE TITLE
Idea: make a pc app

### ISSUE THREAD

**Issue by K2-2K** [fast4x/RiMusic#4369]
### Description

Although this should be done later in development once you are comfortable with the mobile app, many other people would love a polished pc app for rimusic but again this is an idea.

### Suggested Solution

This is an idea to create a pc version for rimusic as it is one of the most functional music apps i have ever encountered, hope you this about this in the future, a pc version would be pretty cool, with a the features of the android app and more.

**Comment by fast4x** [comment]
Hi, it's working progress, can seek development in telegram group
