### ISSUE TITLE
Idea 

### ISSUE THREAD

**Issue by GreenmoonYunn** [fast4x/RiMusic#4370]
### Description

Being able to customize the cover of the playlist, being able to choose an image from our gallery. Something like Spotify. Also when we enter an artist, similar or related artists could appear at the bottom. 

### Suggested Solution

So far, nothing very clear has been achieved.

**Comment by Abhinavreddy-B** [comment]
Playlist custom thumbnail feature done in PR #4411, lets wait till moderators to merge
