### ISSUE TITLE
No funcionan las canciones

### ISSUE THREAD

**Issue by ALOMSEM** [fast4x/RiMusic#4371]
### Version of RiMusic

0.6.56.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on Music
3. No found

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

No se reproduce la musica

### What more can you tell us? (Optional)

Cualquier canción que no me descarge cuando funcionaba no funciona

**Comment by acdc14** [comment]
Prueba utilizando la calidad del audio en `auto` hasta el siguiente release.

**Comment by twistios** [comment]
Probably you should update to the latest version also.

**Comment by Noel-P3** [comment]
Actualiza la app con el ultimo release, justo me paso lo mismo.

**Comment by ALOMSEM** [comment]
Gracias me ha funcinado
