### ISSUE TITLE
[Feature]: Only refresh Quick Picks when the app is cold-started or on demand

### ISSUE THREAD

**Issue by lepa22** [fast4x/RiMusic#4380]
### Description

Currently, the _Quick Picks_ page of the app is automatically refreshed when the app is first opened (cold-started) and every time a user revisits the _Quick Picks_ page after visiting another page. This has two disadvantages:

1. The app feels slow because it has to reload the whole _Quick Picks_ page every time the user returns to it.
2. A user might be interested in the suggested songs/artists in the _Quick Picks_ page, but will lose them if they visit another page and return to _Quick Picks_.

### Suggested Solution

What I suggest as the solution is to only refresh the _Quick Picks_ page only when the app is cold-started or on demand, when the user explicitly refreshes using the pull down gesture.

This way the app will feel much faster, since when a user revisits the _Quick Picks_ page after having visited another page the content will already be there; no empty parts on the page, loading icons, etc. And this will also save users some frustration when they get some nice picks that won't be lost from navigating elsewhere.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.60
