### ISSUE TITLE
Song page issue and playlist issue

### ISSUE THREAD

**Issue by K2-2K** [fast4x/RiMusic#4385]
### Version of RiMusic

v0.6.58.1 by fast4x

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on songs page
3. Song list is always at the bottom and have to click the arrow to go up (always)

For the other bug:
1. Open rimusic
2. Click on playlist page
3. Click on selected playlist
4. Arrow is always pointing at bottom and I have to click again (although a minor bug) and doesn't stay up when I get into the app again.

### Submit a video

https://github.com/user-attachments/assets/82413485-5d45-4de6-8a0a-b0d21e3078e2

https://github.com/user-attachments/assets/e669ea60-ab3a-4107-91b4-3d5bbc595fbe

### What was your expectation?

Idk what to put here

**Comment by fast4x** [comment]
It's fixed available from version 0.6.59

**Comment by K2-2K** [comment]
When will that be available?

**Comment by twistios** [comment]
Normally should be released this weekend (for most updates it is 11PM-1AM central european time on friday).

**Comment by K2-2K** [comment]
Alright thanks 👍

**Comment by K2-2K** [comment]
Issue still persists :( even with the new version that was released today
