### ISSUE TITLE
Pitch black theme doesnt apply until you click on a song and exit player 

### ISSUE THREAD

**Issue by woskkdmsosid** [fast4x/RiMusic#4388]
### Version of RiMusic

0.6.58.1

### Android version

13

### I've done these:

- [ ] Uninstall old build before installing a new one
- [ ] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Default dark mode is used
3. Play song
4. Exit player
5. App changes to pitch black mode

### Submit a video

https://github.com/user-attachments/assets/2f75ec16-33d0-418b-ad3f-79fe8b72850b

### What was your expectation?

App should start on pitch black mode

### What more can you tell us? (Optional)

Its annoying

**Comment by fast4x** [comment]
Improved available from version 0.6.60
