### ISSUE TITLE
quality of image in notification 

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#4393]
### Version of RiMusic

0.6.59

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic and go to music notification, it won't have good quality
2. Go to the lock screen and it will not show a cover

![Screenshot_2024-11-08-16-11-18-745_it fast4x rimusic](https://github.com/user-attachments/assets/ff656a50-e221-448a-8e51-ce218d1a0272)
![Screenshot_2024-11-08-16-11-47-364_lockscreen](https://github.com/user-attachments/assets/b7366e08-9a2f-4a6e-be87-1a2f6f872a10)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Fixed

### What more can you tell us? (Optional)

D

### Logs (Optional)

D

**Comment by twistios** [comment]
I can confirm the low-quality problem for covers in the notification. It seems to only happen for direct YTM songs, but not for YT songs. The cover-problem does not happen for me.

**Comment by Donald-Win** [comment]
Also experiencing quality issues with the album art here. The music widget that I use on my homescreen draws the album art from the notification and is now low resolution. It has previously always been high quality uo until this version

https://github.com/user-attachments/assets/95f7e08f-9a36-4609-a000-4cbb58af4ef1

Other than this (which is nothing in the scheme of things) latest version rocks! Thanks Devs

**Comment by fast4x** [comment]
Improved, available from version 0.6.60

**Comment by Donald-Win** [comment]
> Improved, available from version 0.6.60

Awesome. Thanks.
