### ISSUE TITLE
Reproduce otra canción de la lista del artista.

### ISSUE THREAD

**Issue by Willy2222** [fast4x/RiMusic#4394]
### Version of RiMusic

0 6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Seleccionar artista.
3. Canciones de ese artista 
4. Click en algúna canción de la lista (que no sea el primero)
5. SE REPRODUCE EL PRIMERO - ERRÓNEAMENTE 

### Submit a video

No video 

### What was your expectation?

Que reproduzca la canción exacta que clickeo 

### What more can you tell us? (Optional)

No

### Logs (Optional)

No

**Comment by fast4x** [comment]
Fixed, available from version 0.6.60
