### ISSUE TITLE
Artist click on song first one plays no matter which song pressed

### ISSUE THREAD

**Issue by Nuibance** [fast4x/RiMusic#4399]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on Artist
3. Click on Any song except the top one
4. Top Song plays

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Play the song i have selected.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.60
