### ISSUE TITLE
French language issue (center text on playlists)

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#44]
### Steps to reproduce the bug

In playlist interface

### Expected behavior

hors ligne and favoris text is shifted 

### Actual behavior

It must be centered with the icons

### Screenshots/Screen recordings

![Screenshot_2023-10-27-20-20-27-703_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/48846c32-7eab-47d5-bae1-34ddc98351a3)

### RiMusic version

0.6.6

### Android version

12

**Comment by fast4x** [comment]
Isn't a bug, it's the same in other languages.
But it's a good idea center text with icon and background.

**Comment by NEVARLeVrai** [comment]
> Isn't a bug, it's the same in other languages.
> But it's a good idea center text with icon and background.

If u can do it's better

**Comment by fast4x** [comment]
Sure

**Comment by fast4x** [comment]
Implemented, available from version 0.6.7
