### ISSUE TITLE
Settings is gone in ViMusic mode

### ISSUE THREAD

**Issue by Julian1535** [fast4x/RiMusic#4400]
### Version of RiMusic

Newest one

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

. 

### What more can you tell us? (Optional)

https://github.com/user-attachments/assets/78732ac8-161c-483a-8864-d837452fff65

**Comment by fast4x** [comment]
You must specify that use ViMusic mode, I'm not a magician.

**Comment by Julian1535** [comment]
What i don't get what your saying.

**Comment by Julian1535** [comment]
Nevermind i get it now it's in rimusic

**Comment by fast4x** [comment]
You use RiMusic in ViMusic ui mode

**Comment by fast4x** [comment]
I'll check it soon

**Comment by Julian1535** [comment]
Ok thank you

**Comment by Julian1535** [comment]
I found the settings

**Comment by fast4x** [comment]
where is?

**Comment by fast4x** [comment]
Redesigned vertical navigation bar, available from version 0.6.60
