### ISSUE TITLE
[Feature]: Add the function to, when a playlist ends, restart to the beginning of the playlist 

### ISSUE THREAD

**Issue by PedroH654** [fast4x/RiMusic#4403]
### Description

When a certain playlist of a number of songs runs out, reaches the last song in the playlist, starts again to the beginning of the playlist (activating this function through the settings) 

### Suggested Solution

I saw that a function was added to put more songs when a playlist/queue ends, I want a function like this, but repeating the whole playlist of new new tools in an unlimited way or with a number of repetitions that the person wants the playlist to repeat 

### Alternatives

I wish we had the choice between letting random songs pass after the queue/playlist ends (already added) or between repeating the whole playlist again

**Comment by fast4x** [comment]
Can use repeat mode
