### ISSUE TITLE
Monthly playlist identically 

### ISSUE THREAD

**Issue by Dxcosta** [fast4x/RiMusic#4404]
### Version of RiMusic

0.6.59 stable

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

A few days ago I noticed that some monthly playlists appeared, but they are all identical with the same number of songs and the number of playlists generated was around 20.
![Screenshot_20241108-232455_RiMusic](https://github.com/user-attachments/assets/6b2cf151-cdc7-48fb-b486-56ef359483ca)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

May this number of playlists decrease to just their respective month

**Comment by fast4x** [comment]
it continues to create new?

delete all and try again

**Comment by Dxcosta** [comment]
Apparently not only those that it created automatically I will do it and
then let you know The idea of having monthly playlists isn't bad, I really
liked the idea, but I think it was this bug that generated too many
playlists.

Em sáb., 9 de nov. de 2024, 05:53, Rino Russo ***@***.***>
escreveu:

**Comment by fast4x** [comment]
Yep i agree, in my devices this error not occur.
