### ISSUE TITLE
Me rebota las músicas cuando mi cuenta está activada

### ISSUE THREAD

**Issue by SoyArtemis** [fast4x/RiMusic#4405]
### Version of RiMusic

La última versión

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click en la música 
3. Click y boom me rebota para la pantalla de inicio
4. Eso pasa cuando mi cuenta de YouTube está activada cuando la desactivo ya no tengo ese problema

### Submit a video

No tengo

### What was your expectation?

Nada la verdad 

### What more can you tell us? (Optional)

Bueno el problema es básicamente que cuando inició sesión con mi cuenta de YouTube music no me deja reproducir músicas me rebotan las músicas pero desactivo la opción y ahora me permite escuchar música, lo mismo pasa si activo la opción sin colocar mi cuenta.

### Logs (Optional)

2024-11-08 23:10:41:695 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs

**Comment by haernerdy** [comment]
I had the same issue, but it's working now after logging out and disabling the YouTube Music option

**Comment by fast4x** [comment]
exactly disconnect ytm account
