### ISSUE TITLE
Impossibile ascoltare musica

### ISSUE THREAD

**Issue by St3v3do3** [fast4x/RiMusic#4412]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Seleziona una qualsiasi traccia di un qualsiasi artista
3.Ritornano errori come da screenshot
![Screenshot_2024-11-09-11-28-20-984_it fast4x rimusic](https://github.com/user-attachments/assets/2ba5d251-8f5c-4eca-b870-a97d95517a6c)
![Screenshot_2024-11-09-11-27-42-099_it fast4x rimusic](https://github.com/user-attachments/assets/c47a017e-c28e-408b-81a5-ee38f48cd1b9)

### Submit a video

Mi spiace ma non so come fare il video.

### What was your expectation?

Ascoltare le tracce selezionate

### What more can you tell us? (Optional)

Provato più volte ma niente. Anche riavviando il dispositivo.

**Comment by fast4x** [comment]
Prova a disconnettere ytm e disattivare nelle impostazioni Escludi brani in base alla durata

**Comment by St3v3do3** [comment]
Adesso funziona. Il problema era nell'esclusione dei brani perché YTM lo
avevo già disabilitato come da messaggio pinnato su TG. Grazie mille!
Stefano Zambon
Via Roma 37/A
39100 Bolzano

Il sab 9 nov 2024, 13:54 Rino Russo ***@***.***> ha scritto:

**Comment by fast4x** [comment]
Perfetto, ricordi se l'esclusione l'avevi attivato tu in passato?

**Comment by St3v3do3** [comment]
Sinceramente non ricordo ma non mi sembra di aver fatto qualcosa su quel
flag
Stefano Zambon
Via Roma 37/A
39100 Bolzano

Il sab 9 nov 2024, 15:06 Rino Russo ***@***.***> ha scritto:
