### ISSUE TITLE
Already turned off YTM login but the problem continues

### ISSUE THREAD

**Issue by qpzmc** [fast4x/RiMusic#4414]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [x] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Some songs don't play even when turning off the YTM login

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

https://github.com/user-attachments/assets/810ee662-be3e-4220-abd8-0dff1dfb958f

### What was your expectation?

The song playing

### What more can you tell us? (Optional)

Thank you very much for your time and dedication to this project, besides this problem, this is a great update ❤️

### Logs (Optional)

I tired to copy the log, but I got the message "Log unavailable" for both the log and the crash log.

**Comment by fast4x** [comment]
Have you logged out and disabled ytm login?

**Comment by fast4x** [comment]
Next version have an improvement, wait.

**Comment by qpzmc** [comment]
> Have you logged out and disabled ytm login?

I did, but thank you very much for the improvement ☺️
