### ISSUE TITLE
Las letras bien odenadas 

### ISSUE THREAD

**Issue by Victor332lop** [fast4x/RiMusic#4418]
### Version of RiMusic

0.6.59

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Abro una música 
3. Pongo para ver las letras 
4. Las letras se ven algo desordenadas 
![Screenshot_20241109-131226](https://github.com/user-attachments/assets/ed1976c8-4bae-4e6f-a500-e8bcf51b49a8)

### Submit a video

Yo creo que se debería ver así 🤓☝️(la ft tiene la desicronizada )
![Screenshot_20241109-131226](https://github.com/user-attachments/assets/ad8f2dce-9b79-44d3-a06a-e1edd6d5c58c)

### What was your expectation?

.

### What more can you tell us? (Optional)

La 2da foto desincronizada y la primera es con contra sincronizada

**Comment by Victor332lop** [comment]
Perdón, está debe ser la foto 😓
![Screenshot_20241109-131242](https://github.com/user-attachments/assets/9b3b1d68-e94e-480d-9ed4-bd304f9451b7)

**Comment by fast4x** [comment]
Decrease font size and alignment
