### ISSUE TITLE
La aplicación no funciona en dispositivo con Android 7

### ISSUE THREAD

**Issue by Aetherimpact802** [fast4x/RiMusic#4422]
### Version of RiMusic

0.6.59

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abre RiMusic
2.  No abre y sale reinicia la aplicación 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Poder usar la en esta versión de Android

**Comment by fast4x** [comment]
Maybe I've found solution, wait please, thanks
