### ISSUE TITLE
Imágenes de la portada en la barra de notificaciones pixeleada, pantalla de bloqueo y con la "e" antes del nombre del tema

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#4423]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abriri el reproductor.
2. Reproducir cualquier tema.
3. La imagen de las portadas en las notificaciones están pixeladas, en verde y con una "e" antes del título 

N/A

### What was your expectation?

La barra de notificaciones no se vea con la portada pixeleada, ni con la "e" antes del título 

### What more can you tell us? (Optional)

N/A

### Logs (Optional)

N/A

**Comment by Alaneeedu** [comment]
![Screenshot_20241109-115343~2](https://github.com/user-attachments/assets/a3f15a75-2296-4cd1-bcd6-1bb7c2cfb6a1)
![Screenshot_20241109-115359~2](https://github.com/user-attachments/assets/81c4aa32-b8f0-45d0-b3ff-8171412f8ae0)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.60
