### ISSUE TITLE
Settings is gone in rimusic mode. I reset to deafult settings amd now i can't do anything cause the settimgs is gone

### ISSUE THREAD

**Issue by Julian1535** [fast4x/RiMusic#4424]
### Version of RiMusic

.

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

.

### What more can you tell us? (Optional)

.

### Logs (Optional)

.

**Comment by knighthat** [comment]
do you mind taking a screen shot or post a video of the problem?

**Comment by Julian1535** [comment]
I'm sorry yes i will. There is no settings button.

https://github.com/user-attachments/assets/0f19e0c3-8dee-4a24-8aac-ba6a00b24d33

**Comment by fast4x** [comment]
Redesigned vertical navigation bar, available from version 0.6.60
