### ISSUE TITLE
"Explicit" Songs issue in the notification bar.

### ISSUE THREAD

**Issue by RisottoDou** [fast4x/RiMusic#4426]
### Version of RiMusic

0.6.59 (latest)

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Play a song with the "E" label
3. The notification bar shows the title with an "e:" before the name of the song.

### What was your expectation?

The title showing normally.

### What more can you tell us? (Optional)

![Screenshot_20241109-163626](https://github.com/user-attachments/assets/507012c2-d375-412d-bdc9-5434cc9bf208)
![Picsart_24-11-09_16-37-19-764~2](https://github.com/user-attachments/assets/4ddf3b8e-f4a0-4bf2-a589-42975ac8137b)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.60
