### ISSUE TITLE
Unreadable text and Icons on Dynamic + Pure Dark Theme

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#4428]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic.
2. Go to Settings.
3. Select Dynamic Colors or Material You.
4. Select Pure Dark Colors.
5. Unredable text (because it is too dark)
6. Sometimes the bug happens only after playing a song.

### Submit a video

![Screenshot_20241110_000520](https://github.com/user-attachments/assets/41a70633-9cde-4470-abd3-1bff8c8f1100)

### What was your expectation?

Text should be white or a whiter shade of the color.

**Comment by fast4x** [comment]
Improved in the next release
