### ISSUE TITLE
I can't play any song that is not downloaded.

### ISSUE THREAD

**Issue by SharkyBeAre** [fast4x/RiMusic#4436]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on any song you don't have downloaded
3. Nothing happens
4. A semi-black screen

### Submit a video

It has nothing to do with the YTM login, I tried reinstalling from scratch, but after a couple of hours, the same thing happened again.

https://github.com/user-attachments/assets/6e3790aa-0ba5-4234-b5fd-94e55060886f

### What was your expectation?

If you need the log, I'll be happy to upload it.

**Comment by Potiron** [comment]
Got the issue too, even on the 2 previous versions.

Connected to YTM.

**Comment by fast4x** [comment]
Disconnect and disable yt login. Restart

**Comment by SharkyBeAre** [comment]
> Disconnect and disable yt login. Restart

Nope, not work

**Comment by Potiron** [comment]
For me as SharkyBeAre.
Disconnected and yt login disabled and restart.
Still same issue

**Comment by SharkyBeAre** [comment]
> Disconnect and disable yt login. Restart

Solved
