### ISSUE TITLE
smooth transitioning between songs

### ISSUE THREAD

**Issue by Dantoza** [fast4x/RiMusic#4437]
### Description

Spotify has this feature where x seconds before the song ends, the other one starts playing quietly, then louder and louderand the first one slowly tunes down. X can be modified

### Suggested Solution

It would be nice to have this feature implenanted

**Comment by aneesh1122** [comment]
It's definitely not a request so how much are you willing to pay?

**Comment by Dantoza** [comment]
I don't understand what are pou saying? I just requested a feature to be implemented

**Comment by aneesh1122** [comment]
> I don't understand what are you saying? I just requested a feature to be implemented

I didn't feel like it was a request. It felt more like a command.

**Comment by Dantoza** [comment]
I am sorry if you felt like this, it was not my intention, all respect for you devs

**Comment by fast4x** [comment]
Spotify isn't an inspiration, so the features will be developed if useful, but Not because they are present in external applications.

**Comment by Dantoza** [comment]
Okay, thank you for an answer.Sorry for misunderstandings before, respect you in every way

**Comment by aneesh1122** [comment]
> Okay, thank you for an answer.Sorry for misunderstandings before, respect you in every way

what you are asking for is called 'Crossfade' and it's already planned.
