### ISSUE TITLE
Cannot hear not downloaded songs

### ISSUE THREAD

**Issue by woskkdmsosid** [fast4x/RiMusic#4441]
### Version of RiMusic

0.6.59

### Android version

13

### I've done these:

- [ ] Uninstall old build before installing a new one
- [ ] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Play song
3. Song stops

### Submit a video

https://github.com/user-attachments/assets/c43f2893-aa4f-46a3-98da-5ca69ea644ff

### What was your expectation?

Song playing 

### What more can you tell us? (Optional)

On horizontal mode the app becomes unusable and i have to switch to vertical mode to use the app

**Comment by C4-x** [comment]
Same problem with me.

**Comment by RyanWalkz** [comment]
Same issue with me after I updated the app to the latest version.

**Comment by RyanWalkz** [comment]
Same issue with me after I updated the app to the latest version.

**Comment by Henry3344** [comment]
0.6.59, the same problem, I have tried: 
clearing the cache and reopening
uninstalling the software and reinstalling
and logging in to the YTM account again
but now it is unusable.

**Comment by fast4x** [comment]
Disconnect and disable ytm login, restart app

**Comment by Gaush737w85** [comment]
I already did it, but it still doesn't work. Only the downloaded songs and albums can be listened to.

**Comment by knighthat** [comment]
please use this [pre-release build](https://github.com/fast4x/RiMusic/releases/tag/custom-version)  or my custom [kbuild](https://github.com/knighthat/RiMusic/releases/tag/weekly-kbuild) to test if problem persists

**Comment by Henry3344** [comment]
> I already did it, but it still doesn't work. Only the downloaded songs and albums can be listened to. 
> 
> 

Well, I tried logging back into the YTM account, but that didn't work. Finally, after I tried clicking on the settings in the software and clicking on restore to defaults, it returned to normal, and I wasn't logged into any account, just a suggestion, if you have tried anything and nothing works, try restoring the software's settings to default
