### ISSUE TITLE
Tracks are steadily skipping

### ISSUE THREAD

**Issue by Cresh680** [fast4x/RiMusic#4445]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Open Player 
Select a track from an artist 
Players starts skipping around all random songs 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

https://github.com/user-attachments/assets/f501dccb-362f-4019-a930-0b2226645417

### What was your expectation?

For it to work?

**Comment by fast4x** [comment]
Disconnect and disable ytm login, after restart app
