### ISSUE TITLE
Background Player Settings Missing from Player Appearance Section

### ISSUE THREAD

**Issue by tiwna16** [fast4x/RiMusic#4446]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on Settings 
3. Click on Player Appearance Section
4. Background Player Customization Options are missing

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

There was clearly Background Player Customization Options in Player Appearance Section in previous vers.So,I can expect to see those options in current & upcoming versions also.

**Comment by Mendes1972** [comment]
Cant listen to any music, "went wrong" all the times

**Comment by aneesh1122** [comment]
post screenshots

**Comment by fast4x** [comment]
@tiwna16 
![Screenshot_2024-11-11-01-11-45-905_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/ff555695-8acc-4e7f-a0e1-8b11ee81d7d9)

not true

**Comment by tiwna16** [comment]
![Screenshot_2024-11-18-11-17-01-145_com mi android globallauncher-edit](https://github.com/user-attachments/assets/6545834f-1ad3-4a0e-a241-f99f073df2f7)

So,How can i disable this download option in the notification icon? I can able to disable these in previous versions.
