### ISSUE TITLE
Songs order

### ISSUE THREAD

**Issue by Baviera10** [fast4x/RiMusic#4448]
### Description

It is proposed to teach ramdom order of songs instead of the established order 

### Suggested Solution

Not alphabetical order or other options. The proposal is to automatically  change and show a queue of songs resulting from indicating ramdom order.

**Comment by aneesh1122** [comment]
> ### Description
> It is proposed to teach ramdom order of songs instead of the established order
> 
> ### Suggested Solution
> Not alphabetical order or other options. The proposal is to automatically change and show a queue of songs resulting from indicating ramdom order.
> 
> ### Alternatives
> _No response_
> 
> ### Additional Context
> _No response_

why don't you just shuffle?

**Comment by Baviera10** [comment]
Siento no haberme explicado bien, me propuesta es que, en una playlist o
algún, o algun album, etc. Cuando se indique escuchar música en aleatorio,
se pueda ver el listado del orden por el que se va a escuchar las
canciones, de modo que el usuario pueda ver que canciones siguen a la que
se este escuchando en ese momento.

**Comment by fast4x** [comment]
Hold arrow button and select your order

**Comment by Baviera10** [comment]
Glad to hear it!
