### ISSUE TITLE
Missing translation on crowdin

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#445]
### Steps to reproduce the bug

Missing this translation on crowdin, also could you remove french emojis because it's too much work for me I can't, sometimes I do Portuguese and English, it takes me too long 

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

![Screenshot_2024-01-20-07-48-31-512_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/64a57127-a006-478d-9165-ae21ae7e6389)

### RiMusic version

0.6.18

### Android version

A12 MIUI 14

**Comment by fast4x** [comment]
ok I check the translation and remove the French version with emoji. It stays on Crowdin and gets removed in app

**Comment by fast4x** [comment]
@OrangeZXZ I have to remove the Romanian with emo?

**Comment by fast4x** [comment]
> @OrangeZXZ I have to remove the Romanian with emo?

ok

**Comment by NEVARLeVrai** [comment]
> > @OrangeZXZ I have to remove the Romanian with emo?
> 
> ok

Also don't forget add missing translation on crowdin

**Comment by fast4x** [comment]
Fixed, just available on Crowdin

**Comment by NEVARLeVrai** [comment]
> Fixed, just available on Crowdin

I'm blind ? I don't see it

**Comment by NEVARLeVrai** [comment]
Forget what I say I founded it
