### ISSUE TITLE
You can't play music even if you have a YouTube account, it doesn't let you download and the song has errors. 

### ISSUE THREAD

**Issue by TkJess0987** [fast4x/RiMusic#4454]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens
5.

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Please fix it:(

### What more can you tell us? (Optional)

:(

### Logs (Optional)

:(

**Comment by Soapbosnia** [comment]
Can confirm. I tried logging out and back in and it didn't work, the solution for me was disabling YouTube login completely.

**Comment by fast4x** [comment]
Yep disabling yt login

**Comment by knighthat** [comment]
please use this [pre-release build](https://github.com/fast4x/RiMusic/releases/tag/custom-version)  or my custom [kbuild](https://github.com/knighthat/RiMusic/releases/tag/weekly-kbuild) to test if problem persists

**Comment by woskkdmsosid** [comment]
For a better explained solution i went to miscellaneous settings and disconnected my ytmusic account, disabled the feature and closed the app. After opening back i got to hear online songs
