### ISSUE TITLE
Empty song list

### ISSUE THREAD

**Issue by X-Dean** [fast4x/RiMusic#446]
### Steps to reproduce the bug

![Screenshot_20240120_104908](https://github.com/fast4x/RiMusic/assets/26165963/67ddaa4a-a04a-42a0-ad36-e0ea393b5c4b)
![Screenshot_20240120_104924](https://github.com/fast4x/RiMusic/assets/26165963/219c1f84-40b5-4d20-9f94-f54c30a17b92)
![Screenshot_20240120_104932](https://github.com/fast4x/RiMusic/assets/26165963/39772176-647a-4c07-9225-9bf12fa75e09)
![Screenshot_20240120_104939](https://github.com/fast4x/RiMusic/assets/26165963/0a188bf2-2b00-462d-96e9-4bfd064c557e)
![Screenshot_20240120_104947](https://github.com/fast4x/RiMusic/assets/26165963/3923885f-ef51-4d37-9a15-a79b531d8a7f)

### Expected behavior

I should see songs and play them

### Actual behavior

I see nothing

### RiMusic version

0.6.18

### Android version

Android 14

**Comment by fast4x** [comment]
In the statistics you see the songs you listen to if you exceed the minimum listening time that you can change in the settings.

For searching there are no problems, I attach you screenshot. Check proxy settings, close and reopen the app
![Screenshot_2024-01-20-11-34-35-994_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/31b69f23-1d26-4931-891f-2947ca2e63e2)

**Comment by X-Dean** [comment]
It looks like the Youtube Music is not available at my country. Is there any possibility to use youtube.com as feeder ?
if not please close this bug as not a bug.

**Comment by fast4x** [comment]
Hi, you can try to set a public proxy, go to the settings > Other Tab

Here a sample list where you can try to set one of them.

https://www.proxynova.com/proxy-server-list/

After set proxy, restart RiMusic
