### ISSUE TITLE
Slow in the recent version

### ISSUE THREAD

**Issue by XGhostRX** [fast4x/RiMusic#4462]
### Version of RiMusic

0.6.59 - Normal

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Suffering from slowness that even responds

### Submit a video

https://github.com/user-attachments/assets/46baea42-6a3a-4fd1-ab04-25b791dc4a2b

### What was your expectation?

Fluidity 

### What more can you tell us? (Optional)

Update with more unforeseen events

**Comment by fast4x** [comment]
Seems to be solved in the next version.
