### ISSUE TITLE
[Question] what's this new YT music login? 

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#4464]
Came back to this repo after a time. Now it has yt music login. What's it for?

**Comment by aneesh1122** [comment]
A few weeks ago youtube started restricting people from listening to the songs without login. Many similar apps like Innertune also suffered from this problem.

The quickest workaround was to implement yt login but now you can listen to songs without login.

**Comment by aneesh1122** [comment]
> Not Harmony Music... It play without login

Bold of you to assume I'm talking about harmony music when I haven't even mentioned it above.

Yeah it played songs without login but even that had to be fixed. It's just harmony music fixed itself before yt completely restricted music streaming without login.

**Comment by sayyid5416** [comment]
> A few weeks ago youtube started restricting people from listening to the songs without login. Many similar apps like Innertune also suffered from this problem.
> 
> The quickest workaround was to implement yt login but now you can listen to songs without login.

Oh, thanks for explaining. I thought it was added so we could sync playlists and favorites to and fro in realtime 😁
