### ISSUE TITLE
Action buttons are not visible with default thumbnail settings

### ISSUE THREAD

**Issue by singhh9596** [fast4x/RiMusic#4467]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Choose any song and play

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

readable font and action buttons

### What more can you tell us? (Optional)

I had to reduce the size of the thumbnail from the settings but when i backed up my data and restored it on my other device settings were not restored on my other device. Moreover, if some new user move to ri and see the player ui in action gonna dislike it.

**Comment by twistios** [comment]
Settings can currently not beeing saved or restored.
