### ISSUE TITLE
No se reproduce la música 

### ISSUE THREAD

**Issue by Noeliiarp26** [fast4x/RiMusic#4470]
### Version of RiMusic

0.6.57.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Le doy a reproducir una canción y no funciona y se pasa a otra y otra...

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Fj

**Comment by Caracaco** [comment]
Same problem

**Comment by fast4x** [comment]
Version it's much old update to the latest.

**Comment by knighthat** [comment]
most likely #4420 problem, please install latest version

**Comment by Noeliiarp26** [comment]
No me sale ninguna nueva actualización

**Comment by knighthat** [comment]
#4420 was merged after the release of 0.6.59, please wait until next update.

In the mean time, you can use [pre-release](https://github.com/fast4x/RiMusic/releases/tag/custom-version) build or my custom [kbuild](https://github.com/knighthat/RiMusic/releases/tag/weekly-kbuild)

**Comment by Noeliiarp26** [comment]
Thank you🙏🏻🙏🏻🙏🏻
