### ISSUE TITLE
The truth is just a little more optimization, I have a high-end cell phone and the application It's a little slow, that's all 

### ISSUE THREAD

**Issue by TkJess0987** [fast4x/RiMusic#4471]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

:)

### What more can you tell us? (Optional)

:)

**Comment by OrangeZXZ** [comment]
Please provide more informations.

Do you think the app is lagging?
If yes, please specify where that way is easier to patch.

**Comment by knighthat** [comment]
would be better if you have videos comparing speed between old versions and newer ones

**Comment by veloal** [comment]
> would be better if you have videos comparing speed between old versions and newer ones

In my case #2483, in version 0.6.59 it is still happening. Otherwise, it works very well.
