### ISSUE TITLE
The songs don't work

### ISSUE THREAD

**Issue by JoshGMR** [fast4x/RiMusic#4472]
### Version of RiMusic

0.6.59

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Being able to listen to songs not downloaded

### What more can you tell us? (Optional)

Every time I start any song that is not downloaded, after a few seconds it will close or the app will crash

**Comment by OrangeZXZ** [comment]
Did you log in with a YouTube account?

YouTube login is necessary for songs to load.

If it doesn't work, try logging out and then logging back in.

**Comment by JoshGMR** [comment]
Yes, I did it a few weeks ago, works...but in the new update the songs just
crash

**Comment by OrangeZXZ** [comment]
Could you try reinstalling the app? (Don't forget the database.)

**Comment by JoshGMR** [comment]
Yes, before install a update I make a backup and delete the app

**Comment by OrangeZXZ** [comment]
Oh, I see. Then I hope the bug gets patched in the next update.

**Comment by JoshGMR** [comment]
Thanks buddy, Im sure that will do it

**Comment by fast4x** [comment]
Can try to send log

**Comment by knighthat** [comment]
please use this [pre-release build](https://github.com/fast4x/RiMusic/releases/tag/custom-version)  or my custom [kbuild](https://github.com/knighthat/RiMusic/releases/tag/weekly-kbuild) to test if problem persists

**Comment by WhistlingZephyr** [comment]
I came across https://github.com/fast4x/RiMusic/issues/4454#issuecomment-2467892743 and found that completely disabling YouTube Music login lets me play songs again.

**Comment by jerohnimaux** [comment]
> I came across [#4454 (comment)](https://github.com/fast4x/RiMusic/issues/4454#issuecomment-2467892743) and found that completely disabling YouTube Music login lets me play songs again.

This solved it for me too
