### ISSUE TITLE
Go to link causes crash

### ISSUE THREAD

**Issue by mariuslohoho** [fast4x/RiMusic#4487]
### Version of RiMusic

0.6.59

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on search
3. Click on go to link
4. Click paste and search
5. Crashes

### What was your expectation?

Click search and video/song plays

### What more can you tell us? (Optional)

I click on search, the song shows in the player, but fails to load. Then the player crashes (app haven't crashed yet) When i try to click search again for a few times, the app finally crashes

### Crash Log

2024-11-03T23:22:47.158:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:261) 
	 android.content.res.Resources.getValue(Resources.java:1513) 
	 N9.d.J(SourceFile:43) 
	 M8.a.h(SourceFile:195) 
	 B0.d.e(SourceFile:486) 
	 i4.b.a(SourceFile:801) 
	 d8.b.k(SourceFile:146) 
	 f0.b.k(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 d8.c.r(SourceFile:108) 
	 f0.b.f(SourceFile:44) 
	 f0.b.r(SourceFile:9) 
	 K.m0.j(SourceFile:144) 
	 f0.b.e(SourceFile:44) 
	 f0.b.j(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.k(SourceFile:269) 
	 f0.b.k(SourceFile:52) 
	 h2.t.b(SourceFile:937) 
	 h2.t.a(SourceFile:228) 
	 h8.j.j(SourceFile:531) 
	 f0.b.e(SourceFile:44) 
	 F.P.k(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1153) 
	 android.view.Choreographer.doFrame(Choreographer.java:1069) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-11-03T23:27:16.134:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:261) 
	 android.content.res.Resources.getValue(Resources.java:1513) 
	 N9.d.J(SourceFile:43) 
	 M8.a.h(SourceFile:195) 
	 B0.d.e(SourceFile:486) 
	 i4.b.a(SourceFile:801) 
	 d8.b.k(SourceFile:146) 
	 f0.b.k(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 d8.c.r(SourceFile:108) 
	 f0.b.f(SourceFile:44) 
	 f0.b.r(SourceFile:9) 
	 K.m0.j(SourceFile:144) 
	 f0.b.e(SourceFile:44) 
	 f0.b.j(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.k(SourceFile:269) 
	 f0.b.k(SourceFile:52) 
	 h2.t.b(SourceFile:937) 
	 h2.t.a(SourceFile:228) 
	 h8.j.j(SourceFile:531) 
	 f0.b.e(SourceFile:44) 
	 F.P.k(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1153) 
	 android.view.Choreographer.doFrame(Choreographer.java:1069) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-11-04T07:16:13.762:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2f1bee2 u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-11-05T16:23:37.987:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3b44ebf u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-11-07T08:26:34.781:	java.lang.IllegalStateException
	 I2.c.k(SourceFile:6) 
	 M2.z.l(SourceFile:7) 
	 A7.c.a(SourceFile:263) 
	 O.A.h(SourceFile:129) 
	 Z8.o.h(SourceFile:129) 
	 Z8.n.v(SourceFile:12) 
	 C8.a.i(SourceFile:9) 
	 W8.M.run(SourceFile:107) 
	 K0.a0.v0(SourceFile:7) 
	 K0.Z.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-11-07T15:47:56.759:	java.lang.IllegalStateException
	 I2.c.k(SourceFile:6) 
	 M2.z.l(SourceFile:7) 
	 A7.c.a(SourceFile:263) 
	 O.A.h(SourceFile:129) 
	 Z8.o.h(SourceFile:129) 
	 Z8.n.v(SourceFile:12) 
	 C8.a.i(SourceFile:9) 
	 W8.M.run(SourceFile:107) 
	 K0.a0.v0(SourceFile:7) 
	 K0.Z.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-11-08T23:30:00.695:	android.content.res.Resources$NotFoundException: Resource ID #0x0
	 android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:261) 
	 android.content.res.Resources.getValue(Resources.java:1513) 
	 N9.d.J(SourceFile:43) 
	 M8.a.h(SourceFile:195) 
	 B0.d.e(SourceFile:486) 
	 i4.b.a(SourceFile:801) 
	 d8.b.k(SourceFile:146) 
	 f0.b.k(SourceFile:52) 
	 X.e.a(SourceFile:233) 
	 h0.g.f(SourceFile:149) 
	 d8.c.r(SourceFile:108) 
	 f0.b.f(SourceFile:44) 
	 f0.b.r(SourceFile:9) 
	 K.m0.j(SourceFile:144) 
	 f0.b.e(SourceFile:44) 
	 f0.b.j(SourceFile:9) 
	 androidx.compose.animation.a.a(SourceFile:1397) 
	 v.e.k(SourceFile:269) 
	 f0.b.k(SourceFile:52) 
	 h2.t.b(SourceFile:937) 
	 h2.t.a(SourceFile:228) 
	 h8.j.j(SourceFile:531) 
	 f0.b.e(SourceFile:44) 
	 F.P.k(SourceFile:139) 
	 X.r.N(SourceFile:438) 
	 X.r.U(SourceFile:137) 
	 X.r.p(SourceFile:244) 
	 X.r.L(SourceFile:32) 
	 X.v.w(SourceFile:24) 
	 X.t0.t(SourceFile:108) 
	 X.r0.a(SourceFile:508) 
	 K0.b0.doFrame(SourceFile:34) 
	 K0.Z.doFrame(SourceFile:48) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:1153) 
	 android.view.Choreographer.doFrame(Choreographer.java:1069) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-11-08T23:30:01.511:	android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d02bbd8 u0 it.fast4x.rimusic/.service.PlayerService}
	 android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315) 
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-11-12T08:09:46.150:	java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	 jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) 
	 jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) 
	 jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) 
	 java.util.Objects.checkIndex(Objects.java:359) 
	 java.util.ArrayList.get(ArrayList.java:434) 
	 a4.t.v(SourceFile:81) 
	 a4.t.j(SourceFile:13) 
	 e.i.v(SourceFile:67) 
	 H8.a.k(SourceFile:9) 
	 b9.N.run(SourceFile:107) 
	 K0.Z.w0(SourceFile:7) 
	 K0.Y.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by Abhinavreddy-B** [comment]
Was it specific to 1 particular song/album? if so can you share that here.
And could you please attach a video recording of the bug
