### ISSUE TITLE
Search and sort option in all playlists

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#45]
### Description

A search and sort option in all playlists would be cool. So that you can find the song you are looking for faster in playlists with 500+ songs and don't have to scroll up and down for minutes.

### Suggested Solution

*

**Comment by fast4x** [comment]
Yes, it's a good idea

**Comment by dainvincible1** [comment]
you can search songs from playlist in library section in search bar

**Comment by fast4x** [comment]
Yes, maybe it is interesting to be able to search within the playlist where you are.

**Comment by dainvincible1** [comment]
> Yes, maybe it is interesting to be able to search within the playlist where you are.

yes, that will also be helpful

**Comment by fast4x** [comment]
Added inline search on all playlists and songs list
Available from version 0.6.9
