### ISSUE TITLE
Falla al reproducir música aún iniciado sesión 

### ISSUE THREAD

**Issue by Yokcerpr** [fast4x/RiMusic#4504]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Abrí la aplicación como normalmente inicie sesión en You tube todo bien ahí configure la aplicación luego intento reproducir una canción y me marca que la acción no es soportada 

### Submit a video

![Screenshot_2024-11-13-08-49-32-399_it fast4x rimusic](https://github.com/user-attachments/assets/7bf399c4-f8d4-44d6-838e-52c78ace484d)

### What was your expectation?

Que me ayuden a solucionar este error con la anterior versión no pasaba eso 

### What more can you tell us? (Optional)

Pues le digo inicie sesión y todo configure hasta reinicie mi dispositivo y no sé puede reproducir nada 

### Logs (Optional)

No

**Comment by twistios** [comment]
@fast4x login in 0.6.59 does not really work.

**Comment by fast4x** [comment]
wait next release it's just improved
