### ISSUE TITLE
play is given, the player starts but then exits the player and the music does not play 

### ISSUE THREAD

**Issue by Odinonline** [fast4x/RiMusic#4506]
### Version of RiMusic

V0.6.59

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abra RiMusic
2. Clique em A 
3. Clique em B
4. Estrondo! Crash acontece

### Submit a video

Bug no reprodutor

https://github.com/user-attachments/assets/3273ec42-68e3-4aad-b0d7-0f9950235738

### What was your expectation?

Solução adoro app de vcs

### What more can you tell us? (Optional)

Bugs

### Logs (Optional)

Solution

**Comment by fast4x** [comment]
Try to login in ytm from miscellaneous settings

**Comment by NOBELLIST** [comment]
I turned off ytm login and the songs were working again?!
