### ISSUE TITLE
Piped Instance selection does not want to close

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#4514]
### Version of RiMusic

0.6.59 (commit 6b824a55)

### Android version

14

### Tell us how you trigger this bug

1. Clean install of RiMusic
2. Open Settings > Misc
3. Activate "Enable piped synchronization"
4. Select button "Change Instance"
5. In the menu, select "kavin.rocks libre" (tested instance, any instance should probably work) and then menu closes
6. Switch to Data-Settings
7. Return to Misc-Settings

### What was your expectation?

The instance selection "drop down" should not open again.

### What more can you tell us? (Optional)

The "drop down" for selection of an instance reappears after returning from another settings page, even if piped was disabled in the meantime. 
The bug stops once the settings are exited.
It returns in the same way when you click on the piped instance selection button again.

**Comment by Abhinavreddy-B** [comment]
is this solved?

**Comment by twistios** [comment]
I only opened the bug report, I was working on something else at that moment.

**Comment by twistios** [comment]
I think I can confirm the fix.
