### ISSUE TITLE
[Feature]: Android Auto Radio Start Button

### ISSUE THREAD

**Issue by Juanseolop** [fast4x/RiMusic#4515]
### Description

Is it possible to implement the Start Radio button for any song in Android Auto? It would be very comfortable and would give the player a lot of versatility.

### Suggested Solution

Add the radio start button to android auto

**Comment by fast4x** [comment]
Do you prefer an icon or item in songs list? 
Example 

- start radio
- song
- song
- song
- song

**Comment by Juanseolop** [comment]
![PXL_20241114_130216933.jpg](https://github.com/user-attachments/assets/d6c98680-3ae8-4951-b411-cd6def669818)

Instead of the download button it is more useful in Android Auto the button to start the radio of the song

**Comment by Juanseolop** [comment]
In that case implementing a new button with the radio would be enough

**Comment by fast4x** [comment]
Implemented, available from version 0.6.60

**Comment by Juanseolop** [comment]
Thank you very much for your work. A pleasure to collaborate as much as possible with small suggestions

**Comment by Juanseolop** [comment]
Thank you very much for your work. A pleasure to collaborate as much as possible with small suggestions
