### ISSUE TITLE
Músicas parecem não funcionar

### ISSUE THREAD

**Issue by Wadle44** [fast4x/RiMusic#4516]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abra o app RiMusic
2. Clique em alguma música
3. Espere, a tela diminuiu o brilho?
4. Boom! Player não carrega a música 

### Submit a video

https://github.com/user-attachments/assets/66d4189e-ce36-4293-96ac-a8251b37a481

### What was your expectation?

Expectativa... Bem... Era a música tocar.

### What more can you tell us? (Optional)

Quero deixar uma nota que antes mesmo de estar logado no YT, este bug já acontecia, e quando logado, não fez nenhuma diferença... Ah! O app também tem um bug de não sair de um menu que você entrou.

**Comment by knighthat** [comment]
PR #4425 fixed this problem. Please wait until next update

**Comment by isjustlucas** [comment]
me too, only the downloaded musics play

**Comment by Carlos353478** [comment]
Me too just the songs downloaded
