### ISSUE TITLE
Hi, I'm here, it's not an app error, it's just to ask why the website is not working, I get an error 404 page not found

### ISSUE THREAD

**Issue by TkJess0987** [fast4x/RiMusic#4517]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

:(

### What more can you tell us? (Optional)

:(

**Comment by fast4x** [comment]
Thanks, was an error in update process, now it's ok.
