### ISSUE TITLE
Music bugging and mu

### ISSUE THREAD

**Issue by Jhonsilva953** [fast4x/RiMusic#4518]
### Version of RiMusic

0.6.59

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

The rimuisc is totally bugged, my songs are changing places, I can't download the songs, even though I'm logged into YouTube Music, it's also when I try to play a song,It just starts playing random songs and changes without me controlling it 

### Submit a video

https://github.com/user-attachments/assets/e367bb9c-fc9f-4299-bd47-3d277c795b0c

### What was your expectation?

I wish it would happen this week, I'm really addicted to this app and I can't live without it.

**Comment by fast4x** [comment]
You said "The rimuisc is totally bugged, my songs are changing places, I can't download".

Wrong approach...

**Comment by Jhonsilva953** [comment]
I didn't understand, and now the problem has only gotten worse, now the
songs are no longer playing, everything is frozen, the app is unusable.

Em qui., 14 de nov. de 2024, 09:53, Rino Russo ***@***.***>
escreveu:
