### ISSUE TITLE
Music recommendation

### ISSUE THREAD

**Issue by ghost** [fast4x/RiMusic#452]
### Description

With Spotify, music recommendations are displayed at the end of a playlist, which you can then add to a playlist or play next, for example.

I know that YouTube also offers this based on the currently playing song.

This implementation would be cool in RiMusic to discover new music that suits your taste.

### Suggested Solution

*

**Comment by ikanakova** [comment]
This is already being resolved here #153

**Comment by fast4x** [comment]
Implemented, available from version 0.6.19

**Comment by siggi1984** [comment]
Somehow I'm blind or just don't see the function.

**Comment by fast4x** [comment]
![Screenshot_2024-01-26-18-15-11-298_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/ad9cb874-842c-4156-b6c0-c0530cdcf800)

![Screenshot_2024-01-26-18-15-48-357_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/808c3747-3152-4002-aa3c-b3db62eadf47)

Is in playlist and for now add 6 recommandations

**Comment by siggi1984** [comment]
> ![Screenshot_2024-01-26-18-15-11-298_it.fast4x.rimusic-edit.jpg](https://private-user-images.githubusercontent.com/1484476/300056106-ad9cb874-842c-4156-b6c0-c0530cdcf800.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NTA3NjUsIm5iZiI6MTcwNjQ1MDQ2NSwicGF0aCI6Ii8xNDg0NDc2LzMwMDA1NjEwNi1hZDljYjg3NC04NDJjLTQxNTYtYjZjMC1jMDUzMGNkY2Y4MDAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMTQwMTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWYxYmJlOGEzMzRjMWE4ZjlkMjY4MzkxMmQ0ZGE0YWQ4ZDhjODM0NDY1NDcxMzU2Y2E5NDJkMjhjNjFlMjExNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wclBL8Dd6Ckhxb9bqONEu5j4rS77wDZsjmHjaJBI544)
> 
> ![Screenshot_2024-01-26-18-15-48-357_it.fast4x.rimusic-edit.jpg](https://private-user-images.githubusercontent.com/1484476/300056127-808c3747-3152-4002-aa3c-b3db62eadf47.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NTA3NjUsIm5iZiI6MTcwNjQ1MDQ2NSwicGF0aCI6Ii8xNDg0NDc2LzMwMDA1NjEyNy04MDhjMzc0Ny0zMTUyLTQwMDItYWEzYy1iM2RiNjJlYWRmNDcuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMTQwMTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2ZhYTNhNmE5ZTdlMmQ0ZTY4YzUwYWEyOWE4NjRiNDRlMWZiZDdjZjhiMjhlYWJiYjMyMjI3YzQwMjQ4YjRjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f7B-ufC3ZxYwjbSF52BR2z18Owvtv_66QLIW24Or7-o)
> 
> Is in playlist and for now add 6 recommandations

Okay, this implementation is good. But I had actually thought about it a little differently. 

I think this developer here has done it very well.
https://github.com/25huizengek1/ViMusic

Let me show you a screenshot.

**Comment by siggi1984** [comment]
Maybe you can take a look at it. Personally, I think it's very well done.

https://github.com/25huizengek1/ViMusic/issues/63
