### ISSUE TITLE
I try to play a song but it plays another one 

### ISSUE THREAD

**Issue by mango-kiro** [fast4x/RiMusic#4520]
### Version of RiMusic

0.58.1

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

I try to play a song but it plays another one 
even when I try to save or add to favorites and playlist
(i am connected on YT)

### What was your expectation?

.

**Comment by fast4x** [comment]
Your version is old, uograde
