### ISSUE TITLE
choose of a song 

### ISSUE THREAD

**Issue by 88bharath** [fast4x/RiMusic#4521]
### Description

https://github.com/user-attachments/assets/41daadf1-f65b-4c08-84a6-0e73e476c3a3

When I click any song that song is not playing. But first song is playing.

### Suggested Solution

Which song when we click that song need to play.

### Alternatives

In floating screen time line can't scroll. Kindly clear it also

**Comment by fast4x** [comment]
Your version is old, upgrade please

**Comment by twistios** [comment]
> Your version is old, upgrade please

@fast4x There also is this new bug in 0.6.59. You said you fixed that in 0.6.60.
