### ISSUE TITLE
Now playing icon resolution has degraded.

### ISSUE THREAD

**Issue by jayb-g** [fast4x/RiMusic#4523]
The first thing I noticed after trying RiMusic for the first time was that it had high resolution background for now playing notification. Even amazon music(and probably other music services too doesn't have that). And it wasn't a big deal but I liked that it had high res.

But after recent update(or maybe some time later) I started noticing low resolution background in now playing notification of RiMusic as well. Is it intentional? Or there is a setting for it? Am I missing something ? 

RiMusic version: 0.6.59
Android OS: AOSP 15

It was working fine in the previous version of RiMusic. Or maybe in AOSP14.

**Comment by fast4x** [comment]
In the next version there's an improvement in notification area.
