### ISSUE TITLE
Nada funciona

### ISSUE THREAD

**Issue by Kou-tester** [fast4x/RiMusic#4524]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. me meto en un album o reproduzco alguna cancion no descargada
2. simplemente NO se reproduce

### What was your expectation?

quiero que se reproduzca, ademas no me deja ni siquiera descargar albums o canciones 

### What more can you tell us? (Optional)

ya desvincule y vincule YT Music, desinstalé la app y la volvi a instalar, borre los datos y caché y nada, el problema sigue

**Comment by pichulon3432** [comment]
Me too hapens bro, try reproduce some song and no working, not reproduce

**Comment by Carlos353478** [comment]
Me too

**Comment by fast4x** [comment]
Disconnect and disable ytm login, restart app
