### ISSUE TITLE
Bug in modern player

### ISSUE THREAD

**Issue by Ly-vie** [fast4x/RiMusic#4525]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. I switch from essential player to modern player
2. I press expand player
3. Then the bug will appear
![Screenshot_20241115-084153_RiMusic](https://github.com/user-attachments/assets/b3a586b2-d025-48d4-bed1-8fed7285936c)
![Screenshot_20241115-084157_RiMusic](https://github.com/user-attachments/assets/56563754-66b0-4bc1-878b-9ac18ff4dd3e)

### Submit a video

https://github.com/user-attachments/assets/f0c6187d-8aec-41ce-94ff-857143ad12a4

### What was your expectation?

Ofcourse i expect the bug will be fix obviously

### What more can you tell us? (Optional)

N/a

### Logs (Optional)

N/a

**Comment by twistios** [comment]
The video does not work (at least for me). And from your description and screenshots it does not really get clear what you want to say.

**Comment by aneesh1122** [comment]
Long tap on the thumbnail and then adjust the first slider according to your display

**Comment by Ly-vie** [comment]
> Long tap on the thumbnail and then adjust the first slider according to your display

Thanks for the information, it work
