### ISSUE TITLE
Add option of import list reproduction

### ISSUE THREAD

**Issue by pichulon3432** [fast4x/RiMusic#4526]
### Description

Its posible add option to import list reproduction or playlist of apps extern like youtube music, spotify, etc, you can you do that?

### Suggested Solution

I dont know, its only suggest

**Comment by twistios** [comment]
You can share playlists with RiMusic from YTM. Other platforms have to be first transfered to YTM.

**Comment by fast4x** [comment]
Extra yt/ytm isnt' planned, sorry.
