### ISSUE TITLE
Start Radio option missing in Android Auto

### ISSUE THREAD

**Issue by carlozvv** [fast4x/RiMusic#4527]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Connect to Android Auto
3. Play any song
4. Select options
5. Start Radio option is missing 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Start Radio option

### What more can you tell us? (Optional)

In this version doesn't work. In previous version worked fine. Latest version has better compatibility with Android Auto, but the start Radio option is missing.

**Comment by twistios** [comment]
It seems that this gets solved in the changes  related to this issue. https://github.com/fast4x/RiMusic/issues/4515
