### ISSUE TITLE
Compact navigation version

### ISSUE THREAD

**Issue by Crayz310** [fast4x/RiMusic#454]
### Description

Add a compact navigation option of 3-4 icons at the bottom in the style of Spotify or Yandex Music.
The point is that it would look more elegant and practical on devices with small screens.

### Suggested Solution

Add a compact navigation option of 3-4 icons at the bottom in the style of Spotify or Yandex Music. 

### Alternatives

np

**Comment by fast4x** [comment]
Do you can upload a screenshot for Yandex Music, please?

**Comment by Crayz310** [comment]
> Do you can upload a screenshot for Yandex Music, please?

![image](https://github.com/fast4x/RiMusic/assets/84406707/c1ce23c8-153e-472c-aa04-0e2a5da96a5d)

**Comment by gauze756** [comment]
Is this still considered or we can flag is as Not Planned.

**Comment by fast4x** [comment]
not planned

**Comment by gauze756** [comment]
Close it please
