### ISSUE TITLE
How do I stop the theme color from changing every time I play a song? 

### ISSUE THREAD

**Issue by TkJess0987** [fast4x/RiMusic#4540]
### Version of RiMusic

0.6.60

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

Uploading VID_20241115_171943.mp4…

### What was your expectation?

:(

**Comment by aneesh1122** [comment]
Video isn't uploaded properly

**Comment by Abhinavreddy-B** [comment]
I think I have seen this bug. 

Steps to reproduce:
1. Set theme as pure dark
2. Set player background as gradient from song cover
3. Now on playing any song or when song changes, the theme keeps changing to dynamic.

Note: the theme shown in settings is still same but the app colours change

**Comment by TkJess0987** [comment]
I found the error When I set the player background as the cover gradient,
the dynamic theme is set, that is, it is activated even though I have the
custom theme.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.61
