### ISSUE TITLE
Show next song queue displays the current song, not the next song

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#4547]
### Version of RiMusic

0.6.60

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Play something 
3. View the player

### Submit a video

https://github.com/user-attachments/assets/cd320989-af82-442b-94e3-cf292c5cd537

### What was your expectation?

It's supposed to display the next song, not the current song

**Comment by luxdev01** [comment]
Same here
