### ISSUE TITLE
Albums with over 100 songs stop at 100.

### ISSUE THREAD

**Issue by Wingzzzzy** [fast4x/RiMusic#455]
### Steps to reproduce the bug

By using the sonic frontiers ost https://music.youtube.com/playlist?list=OLAK5uy_lOAxYeEvS5RGiRcq6BFGvBE2AUZcEMhwE it stops at 100 songs where there should be 150.

### Expected behavior

The user should see 150 songs

### Actual behavior

Only shows 100

### RiMusic version

0.6.16

### Android version

Android 13 MiUi 14

**Comment by Wingzzzzy** [comment]
It also a problem in the original ViMusic hoping at least this project can fix it.

**Comment by fast4x** [comment]
Hello, unfortunately I saw that it is not a bug, however it is something that I deepen.

**Comment by Wingzzzzy** [comment]
Hey thanks for talking a look at it as i love ViMusic well now RiMusic. and to be honnest its kinda a pain to search for tracks in game ost. Hope you can make it so more songs can be showned.
________________________________

**Comment by xkill** [comment]
I have the same bug. On ViMusic it loads all the song, but not on RiMusic.

Link to a sample playlist:
https://m.youtube.com/playlist?list=PLdfPSC8OOrQL1uVv5-GLO-fEqJUe2_Vys
