### ISSUE TITLE
When using fluid gradeint from song cover it gets mixed with the last song and completly changes the color of everything not just the expanded player

### ISSUE THREAD

**Issue by Julian1535** [fast4x/RiMusic#4550]
### Version of RiMusic

. 

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

https://github.com/user-attachments/assets/900884bd-6983-410f-a9f9-d78841f6b66c

### What was your expectation?

.

### What more can you tell us? (Optional)

.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.61
