### ISSUE TITLE
Artist name doesnt update in norifications tab

### ISSUE THREAD

**Issue by woskkdmsosid** [fast4x/RiMusic#4552]
### Version of RiMusic

0.6.60

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Play song
3. Change song
4. Artist name only changes in the app

### Submit a video

I will upload photos instead

### What was your expectation?

Get the real song artists

### What more can you tell us? (Optional)

After ending the song just stopped and updated its info to the correct one

**Comment by woskkdmsosid** [comment]
![Screenshot_2024-11-16-17-44-19-084_com miui home](https://github.com/user-attachments/assets/fb106422-37d0-484e-ace2-59ab325e8235)

**Comment by woskkdmsosid** [comment]
![Screenshot_2024-11-16-17-44-25-095_it fast4x rimusic](https://github.com/user-attachments/assets/0ce6886c-c925-4b81-8d31-467f1356e1c9)

**Comment by fast4x** [comment]
I don't understand
