### ISSUE TITLE
Background colors has some issue

### ISSUE THREAD

**Issue by Rocky0035** [fast4x/RiMusic#4554]
### Version of RiMusic

0.6.60

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Set the background color to Fluid gradient from song cover
3. Play a song and skip to next song
4. The colors of previous is shown on the screen
5. I need to minimise the player and open the song again to see the colour of current song 

https://github.com/user-attachments/assets/a0915058-a919-40a1-a55c-142747474944

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I was expecting it to be fixed like in the v0.6.58

**Comment by fast4x** [comment]
Fixed, available from version 0.6.61
