### ISSUE TITLE
Copia de seguridad

### ISSUE THREAD

**Issue by Baviera10** [fast4x/RiMusic#4555]
### Version of RiMusic

0.6.59

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Al reponer la copia de seguridad, fallo al reproducir música,  hubo que desinstalar completamente la app y volver a instalarla. Menos mal que tenía guardadas las canciones de mis play list, supongo que habré perdido algunas, pero pocas. He actualizado a la 0.6.60, pero miedo me da hacer copia de seguridad

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Que funcione bien la copia de seguridad

### What more can you tell us? (Optional)

Lo probé dos veces y en ambos casos, pasó lo mismo

**Comment by fast4x** [comment]
You have a problem inside your data
