### ISSUE TITLE
Player Info Shows Song Quality as Medium Even Though I Set It To High

### ISSUE THREAD

**Issue by Kurumii-ii** [fast4x/RiMusic#4560]
### Version of RiMusic

0.6.60

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Set Song Quality To High
3. Play Any Song
4. Player Info Shows Song Quality as Medium

## ScreenShots : 
![Screenshot_2024-11-17-16-19-54-791_it fast4x rimusic](https://github.com/user-attachments/assets/49615adc-6efd-4d45-867f-11a34712ed9c)
![Screenshot_2024-11-17-16-21-36-637_it fast4x rimusic](https://github.com/user-attachments/assets/464ea19b-f592-482a-856c-165658d7cf94)
![Screenshot_2024-11-17-16-22-59-266_it fast4x rimusic](https://github.com/user-attachments/assets/91f151d5-8510-496e-a6bc-0053262e2533)
![Screenshot_2024-11-17-16-36-08-773_it fast4x rimusic](https://github.com/user-attachments/assets/544349a6-097b-4bfb-bc57-a53462104308)

### What was your expectation?

High Quality Song Should Be Played

**Comment by fast4x** [comment]
It because is max quality available inside your db, you have update song if you want rescan for new quality

**Comment by Rocky0035** [comment]
![Screenshot_2024_1118_104821](https://github.com/user-attachments/assets/1f0f81dd-38f4-4d4f-9cce-4043aa87c5de)
Yeah even I'm facing same issue. It was not the case with previous update and also facing issue issue with background colors.

**Comment by Kurumii-ii** [comment]
> It because is max quality available inside your db, you have update song if you want rescan for new quality
![Screenshot_2024-11-18-15-27-59-393_it fast4x rimusic](https://github.com/user-attachments/assets/06c13cc1-896f-4902-a752-6e4d696a08a7)

By updating the song and rescanning for new quality, do u mean that i should delete the cached song in the pic above and play the songs again

**Comment by fast4x** [comment]
You must update from hold on song and tap in update menu item

**Comment by twistios** [comment]
The maximum song quality depends on the song and what is available. It seems that high quality (> ~140kpbs) is now only available with YTM login.

**Comment by Kurumii-ii** [comment]
> The maximum song quality depends on the song and what is available. It seems that high quality (> ~140kpbs) is now only available with YTM login.

YTM login is broken idk why i couldn't play any song when i logged in my ytm acc

**Comment by Kurumii-ii** [comment]
Just figured out i had to clear the song cache before logging in YTM acc or else the songs wouldn't play at all. Thx for trying to help me

**Comment by Kurumii-ii** [comment]
Just figured out i had to clear the song cache before logging in YTM acc or else the songs wouldn't play at all. Thx for trying to help me
