### ISSUE TITLE
Cache doesn't work anymore

### ISSUE THREAD

**Issue by SmoothButt** [fast4x/RiMusic#4569]
### Version of RiMusic

0.6.60

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Listen to any song not in cache
3. The song isn't automatically downloaded into cache
4. Boom

### What was your expectation?

To get every music that I listen to in cache

### What more can you tell us? (Optional)

I already did :
- Uninstall and reinstall an older version and a new version
- Cleared the cache
- Put the cache limitation to max
- Looked at other options

**Comment by fast4x** [comment]
Explain better please

**Comment by SmoothButt** [comment]
> Explain better please

nvm work again idk what happened 🤷‍♂️
