### ISSUE TITLE
No sé corrigió el siguiente bug. 

### ISSUE THREAD

**Issue by Willy2222** [fast4x/RiMusic#4571]
### Version of RiMusic

0 6.60

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

First of all, thank you for the fantastic work you do. It is a highly appreciated application. 

The bug persists in version 0.6.59 although it was supposedly fixed. 

1 - Go to any artist.
2 - Song 
3 - click on any song in the list other than the first one. 
4 - Always play the first one. MISTAKENLY. 

5 - Sorry, Google translation..... GREETINGS to the programmers.
Comentarios

................

Ante todo gracias por el trabajo fantástico que realizan. Es una aplicación muy apreciada. 

El bug persiste de la versión 0.6.59 aunque supuestamente se había solucionado. 

1 -  Ir a cualquier artista.
2 - Cancion 
3 - click en cualquier canción de la lista que no sea la primera. 
4 - Reproduce siempre la primera. ERRÓNEAMENTE. 

5 - SALUDO a los programadores. 

### Submit a video

No video 

### What was your expectation?

Que reproduzca la canción exacta que clickeo.

### What more can you tell us? (Optional)

-

### Logs (Optional)

-

**Comment by fast4x** [comment]
Is not tru, i've tried now and it work....

**Comment by Willy2222** [comment]
> Is not true, i've tried now and it work....

Fast4x , estoy intentando subir el video, ojalá lo puedas ver qué persiste el problema.
.
Luego de elegir el artista, no en la lista inmediata, sinó ir al ícono canciones...  Que se despliegan más .... Click en alguna canción (no la primera) y Ahí sucede

**Comment by fast4x** [comment]
Ah ok I've tried from overview, sorry, I'll fix soon.

**Comment by Willy2222** [comment]
Gracias por tán buen trabajo..
.
Por acá, mí única manera de ayudar es informando de algún bug. 
.
Gran saludo.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.61
