### ISSUE TITLE
Icon remove suggestion

### ISSUE THREAD

**Issue by nikun-sahu** [fast4x/RiMusic#4574]
### Description

![Screenshot_2024-11-19-01-45-26-172_it fast4x rimusic-edit](https://github.com/user-attachments/assets/a4d259b4-bead-4967-938b-a4bf97c23fe9)

### Suggested Solution

Remove this icons from this page....i have accidentally deleted some songs by clicking on them and it also look ennoying

**Comment by fast4x** [comment]
Before delete downloads popup show...

**Comment by woskkdmsosid** [comment]
This should be behind a switch ngl
