### ISSUE TITLE
Opzioni sparite nell'ultima versione

### ISSUE THREAD

**Issue by CiccioDerole** [fast4x/RiMusic#4576]
### Version of RiMusic

0.6.60

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Sono sparite alcune vecchie opzioni:
- riduci miniatura quando in pausa
- disattiva swipe orizzontale per cambiare canzone

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Non so se mi sono perso qualcosa e sono state volutamente levate, ma credo siano interessanti e utili e quindi vorrei riaverle

### What more can you tell us? (Optional)

Inoltre, riguardo allo swipe orizzontale, nel player su si scorre dall'alto  verso il basso sulla copertina della canzone, il player cambia canzone. L'animazione è simile a quella del carosello, però io ho quella funzione disattivata.

**Comment by fast4x** [comment]
Lo swipe orizzontale è nel tipo player essential mentre quello verticale nel modern

**Comment by CiccioDerole** [comment]
Ah si ora ho visto che cambiando il tipo di player riappaiono anche le due opzioni. Avevo disinstallato l'app e poi quando lho reinstallata non mi sono ricordato di cambiare la tipologia di player. Scusa allora😅

**Comment by fast4x** [comment]
Figurati
