### ISSUE TITLE
Las músicas se skipean automáticamente de la nada 

### ISSUE THREAD

**Issue by TamakyTamagotchy** [fast4x/RiMusic#4579]
### Version of RiMusic

0.6.60

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

English:
First of all, this app is fantastic, but I have a problem, and I’ll proceed to explain it. When I’m listening to music, it opens in the music player (I’m not sure what to call it, but you can see it in the video). If I stay on that interface, the music skips on its own without me doing anything. In previous versions, this issue didn’t exist, but from version 5.58 onward, this bug appeared. I hope you can fix it and continue with your project.

---

Español:
Primero que nada, esta aplicación es fantástica, pero tengo un problema, y procederé a explicarlo. Cuando estoy escuchando música, se abre la música en el reproductor (no sé cómo llamarlo, pero en el vídeo se ve). Si me mantengo en esa interfaz, la música se salta sola sin hacer nada. En versiones anteriores, este problema no existía, pero desde la versión 5.58 en adelante, apareció este error. Espero que puedan arreglarlo y sigan con su proyecto.

### Submit a video

[vídeo de prueba, espero haberlo puesto bien](https://drive.google.com/file/d/1FRXwi_w-wAzfwtdINDAkR4oUL9pjjYbs/view?usp=drivesdk)

### What was your expectation?

Simplemente quería ver la letra de las música, pero eso sí si se sale de ahí deja de pasar el bug, eso sí si se mantiene en esa pantalla aún en segundo plano sigue skipeandose

### What more can you tell us? (Optional)

Puede seguir ocurriendo ese bug aún en segundo plano si se sigue en esa pantalla

**Comment by fast4x** [comment]
Maybe you have medley mode enabled
