### ISSUE TITLE
The theme remains bugged

### ISSUE THREAD

**Issue by bauldihr** [fast4x/RiMusic#4582]
### Version of RiMusic

0.6.60

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

I've disabled, deactivated and activated YTM, but the app doesn't sync with any, much less with "modern black". 

### Submit a video

Version in which the theme worked smoothly: 0.6.58.1 

https://github.com/user-attachments/assets/14ee5c44-f974-483a-b8b7-a4c1c0889066

Version 0.6.60

https://github.com/user-attachments/assets/5cff1c89-30ba-42a3-a88f-8264a52a10be

### What was your expectation?

That the colors work according to the chosen theme

### What more can you tell us? (Optional)

I also don't know what the difference is according to the guidance between deactivating and disabling. So much so that, lim I disabled YTM, tested it, it didn't work.

**Comment by fast4x** [comment]
What you mean by theme and ytm login?

**Comment by bauldihr** [comment]
> O que você quer dizer com tema e login ytm?

You told me to do this disable, deactivate and restart. Last time I reported the same bug, you directed me to do it with YTM.

**Comment by Abhinavreddy-B** [comment]
Fixed in #4577 


Available from version 0.6.61

**Comment by fast4x** [comment]
> > O que você quer dizer com tema e login ytm?
> 
> You told me to do this disable, deactivate and restart. Last time I reported the same bug, you directed me to do it with YTM. 

Ah ok I didn’t understand
