### ISSUE TITLE
High data usage even without playing music

### ISSUE THREAD

**Issue by TicTecOfficial** [fast4x/RiMusic#4588]
### Version of RiMusic

0.6.60

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

- open app
- listen to (downloaded) music for 5 minutes
- pause 
- come back 6 hours later
- 7GB-16GB data used.

### What was your expectation?

i pause music, im not supposed to be using any more data. simple.

**Comment by TicTecOfficial** [comment]
I'd also like to mention that the app is still running in the background through all this time (and is using up a **LOT** of battery. and i don't know why.

**Comment by twistios** [comment]
I think this is not a regular behaviour. Are you sure this is the data used by RiMusic? For my phone I have a usage of 4.5GB for RiMusic in one month (and the reason is mostly because most of the songs where not cached I listed to because I had to reinstall the app).

**Comment by TicTecOfficial** [comment]
I'm fully sure this is caused by RiMusic. My data usage settings say the amount of data used by each individual app. and RiMusic topped that list by 30GB. Only reason why it didn't go further because it used up my entire month's quota

**Comment by twistios** [comment]
I guess it only happens with a special settings config, so this is how it didn't happen before.
As a next step, I guess it will be useful if you could post your settings of RiMusic. You can just send screenshots of your settings (there are many). Or if you know exactly what you changed compared to default only those.
Also it will be useful if you can add more info what exactly you were doing, I.e. via which steps you used to start the playback and if this song was the first song.
Also, have you done the same steps already before or did this problem only happen once?

**Comment by twistios** [comment]
You also said in your first post, that the huge data usage happened in specific hours. So do you know how much it was before that happened? Because it is possible that it did not happen "in one go".

**Comment by TicTecOfficial** [comment]
I’ll post my settings later today, but I can guarantee that there aren’t
any settings that looked like it would’ve helped (let alone be related to
my issue by any means), believe me i checked.

I’m not really sure as to how much more info I can add; I download a song,
go back to the songs tab (which is partially broken as every song i listen
to just vanishes out of existence and comes back whenever it wants to) and
pick the song I downloaded. I’m done listening so I pause the song, come
back to listen a few hours later, I come to my SMS app to find a notice
saying that (large amount) of data had been used up.

**Comment by TicTecOfficial** [comment]
regarding the specific hours, RiMusic used that much data within 7 hours of
the app running in the background. All with RiMusic running in a single,
unterminated task.

**Comment by twistios** [comment]
My device only gives me exact statistics per month. How do you get them?

**Comment by TicTecOfficial** [comment]
certain phones (in my case, huawei) have the ability to show per-app data
usage, not sure about yours though.

**Comment by fast4x** [comment]
I have monitored my app, i haven't found  any data consuming is app and service not running.
