### ISSUE TITLE
Perfect! just one more tweaks..🥂

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#4589]
### Description

Proper left side alignment:
(Red dots for non aligned left side of each other)
![Screenshot_20241121-130105](https://github.com/user-attachments/assets/19d69635-1ca9-4930-b29e-c396fa0cd791)

### Suggested Solution

please align the same 🙏🏻 @fast4x

**Comment by woskkdmsosid** [comment]
what about the tabs (like quick picks)

**Comment by Vishcot** [comment]
> what about the tabs (like quick picks)
idk, i feel they are aligned.

**Comment by fast4x** [comment]
Improved, available from version 0.6.61
