### ISSUE TITLE
[Feature]: skip

### ISSUE THREAD

**Issue by YashSoPro** [fast4x/RiMusic#4592]
### Description

add so we can skip 10 sec in past and future we have to go through whole slider 

### Suggested Solution

add sonif we click on background or thumbnail 2 times it skips if we tap on left it goes in past if we tap on right it goes in future 

### Alternatives

just add

### Additional Context

no

**Comment by Abhinavreddy-B** [comment]
it already exists, you have to long press on 'Play next' symbol. it will skip 5 seconds

**Comment by YashSoPro** [comment]
> it already exists, you have to long press on 'Play next' symbol. it will skip 5 seconds

thx didn't knew
