### ISSUE TITLE
No audio output on Android Auto

### ISSUE THREAD

**Issue by Baviera10** [fast4x/RiMusic#4593]
### Version of RiMusic

V0.6.60

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Conectivo the Phone to the car. In other apps there is no audio problema, only in RiMusic

### Submit a video

..

### What was your expectation?

It worked fine before. Maybe something went wrong when reactivating the random mode

### What more can you tell us? (Optional)

.

### Logs (Optional)

.

**Comment by fast4x** [comment]
I don't understand what you mean

**Comment by ikanakova** [comment]
I think he means that in the latest version of RiMusic for Android Auto the albums tab, playlist etc. show no data.

**Comment by fast4x** [comment]
Show no data if nodata in app

**Comment by Baviera10** [comment]
Nothing comes out of the speakers, the songs progress but nothing
comes out of the speakers when I select rimusic in android auto

**Comment by fast4x** [comment]
Search for new songs, maybe this song are video from old rimusic version when was this issue

**Comment by Baviera10** [comment]
Please close Issue #4593 my description is wrong
