### ISSUE TITLE
Player Sound Bug/Audio not working on background

### ISSUE THREAD

**Issue by R7anTL** [fast4x/RiMusic#4595]
### Version of RiMusic

0.6.60

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

When going outside the app or turn lock screen and move the song slider or backward/forward the song, it just stops giving audio; need to go get into the app to restore the sound, but the songs remain playing all the time 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Hope check the audio player.

### What more can you tell us? (Optional)

Before version 0.6.57 never had missing audio/ audio bug

**Comment by fast4x** [comment]
Sorry, but this isn't reproducible
