### ISSUE TITLE
Duplicated Songs

### ISSUE THREAD

**Issue by Weichei0** [fast4x/RiMusic#4596]
### Version of RiMusic

0.6.60

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on an album specifically The Smiths' "The Queen is Dead"
3. Boom! 10 songs became 17? somehow...

### Submit a video

![Screenshot_20241122-083131](https://github.com/user-attachments/assets/73fe9dfe-2b2f-410a-9488-12436ef3c066)

### What was your expectation?

For it to hopefully be fixed 🤞🏽, I have put of listening to this album for months in the wait of it to be fixed, and sadly it never did so hopefully something can be done about in.

### What more can you tell us? (Optional)

Still don't entirely know if this is a personal thing, but I haven't yet seen anyone complain about it which is weird cuz this album is decently popular.

**Comment by fast4x** [comment]
Remove bookmark, search and bookmark again

**Comment by rugwed** [comment]
I am also able to see this on an album. It wasn't showing up duplicates until yesterday. I have tried removing it from the library, adding it back, unfollowing the artist but it didn't help.

![Screenshot_20241129-022737](https://github.com/user-attachments/assets/6e99737e-cf8e-4eef-ae67-001d8dde6dce)
