### ISSUE TITLE
Some song that came out today friday at midnight cant find it 

### ISSUE THREAD

**Issue by jlumbierres** [fast4x/RiMusic#4598]
### Version of RiMusic

0.6.60

### Android version

8.1

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Maybe its a bug or maybe not but the song no show up in any of the both artist (aka Martin Garrix - Jex) 
Make Told You So apparear

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

That like last week friday songs apparear at 00:01 midnight as expected release

### What more can you tell us? (Optional)

I wanna listen that song...

**Comment by twistios** [comment]
![Screenshot_20241122_144809.jpg](https://github.com/user-attachments/assets/c9915e27-c6b5-461d-af48-ec48d85d5f5d)

I can find that song in the search.

**Comment by twistios** [comment]
![Screenshot_20241122_144927.jpg](https://github.com/user-attachments/assets/82319e79-7a57-41d0-8341-f2afa270017a)

On Martin Garrix Artist Page, it is listed as single.
