### ISSUE TITLE
On Android Auto, shuffle mode doesn`t work

### ISSUE THREAD

**Issue by Baviera10** [fast4x/RiMusic#4599]
### Version of RiMusic

0.6.60

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

My previos diagnosis was wrong, what happens in that when you put a playlist in shuffle mode in Android Auto, the Playlist do not run

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

.

### What more can you tell us? (Optional)

.

### Logs (Optional)

.

**Comment by Baviera10** [comment]
I tried that and the moment I choose random, it stops working (in
Android Auto only)

**Comment by fast4x** [comment]
interesting, have tried 0.6.61?

**Comment by Baviera10** [comment]
Not, now i download it and see it, thanks

**Comment by Baviera10** [comment]
Anyway, I go into AA, select RiMusic/songs, mark the first song and
when it starts playing, I select random/next song and it doesn't
progress

**Comment by Baviera10** [comment]
Funcionando!! Gracias!!

**Comment by Baviera10** [comment]
V0.6.62
