### ISSUE TITLE
[Feature]: Enhance Artist and Album Views to Include All Saved Songs

### ISSUE THREAD

**Issue by ErickMontesDK** [fast4x/RiMusic#4605]
### Description

Currently, the Artist and Album views only display favorited items. It would be helpful to also show all artists and albums with at least one saved song in the library. This would allow users to explore their collection better and notice patterns, like an artist with many songs or albums they might not have marked as favorites but are worth revisiting. Including the number of songs per artist/album would add even more value.

### Suggested Solution

Add two sections in both views:

1. "Favorites" for marked items.
2. "All" for all artists/albums with at least one saved song, along with a song count.

### Alternatives

Using filters instead of sections is a simpler approach but might not feel as organized.

### Additional Context

This feature helps users discover overlooked content and organize their library efficiently, such as identifying duplicate albums or artists they’ve saved multiple songs from but haven't explored further.

**Comment by knighthat** [comment]
I have a suggestion. Instead of clogging the `Artists` and `Albums` tabs, we can make a section in `Statistics` page, where listened **artists** and **album** of each period or all time are listed.

**Comment by fast4x** [comment]
> I have a suggestion. Instead of clogging the `Artists` and `Albums` tabs, we can make a section in `Statistics` page, where listened **artists** and **album** of each period or all time are listed.

I think it makes sense to develop it as the user indicated. Adding it to statistics will only be useful to users who love statistics.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.62

**Comment by knighthat** [comment]
I don't like it, I have songs from hundreds of of artists and albums. But most of them only have 1 hit. This implementation will literally polute my albums and artists page

**Comment by fast4x** [comment]
will be a feature in addition with artists and albums in playlist or favorites listened...

**Comment by fast4x** [comment]
work in progress...
