### ISSUE TITLE
Incorrect status bar color in player

### ISSUE THREAD

**Issue by AstroLightz** [fast4x/RiMusic#4606]
### Version of RiMusic

0.6.61

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open app with dark mode on. Status is white
2. Play any song.
3. In player, status is black.

Reversed effect on light mode.

### Outside player (ex. Settings)
![Screenshot_2024-11-22-23-29-43-27_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/37f61741-d907-481e-b2c0-125ad9731180)

### Player
![Screenshot_2024-11-22-23-29-34-25_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/9d0cc75f-4a3f-40c0-9783-62bb6c03d783)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

The status would be the same color in the player as outside the player.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.62
