### ISSUE TITLE
Excellent update ✅

### ISSUE THREAD

**Issue by bauldihr** [fast4x/RiMusic#4607]
### Description

You are great with the development of the app I just want to thank you for taking the time to bring out the best in this app. This shows that human beings, just as you are, are reflections of your inner elegance. Thank you! ✅✅✅✅✅

Now, a question: I held the screen and this appeared. What does it mean? 
![Screenshot_2024-11-23-01-31-03-063_it fast4x rimusic](https://github.com/user-attachments/assets/deb03b26-d1e0-4c7c-bca0-ac3454a294d9)

### Suggested Solution

Thanks 

### Alternatives

Thanks 

### Additional Context

Thanks

**Comment by fast4x** [comment]
Thanks a lot, with these slider you can change carousel effect configuration as covers distance, blur level etc... try it and enjoy effects.

**Comment by twistios** [comment]
You will only see a difference with the carousel settings if it is enabled.
