### ISSUE TITLE
Some songs are not playing from playlist

### ISSUE THREAD

**Issue by Ashubnx** [fast4x/RiMusic#4608]
### Version of RiMusic

0.6.61

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on playlist
3. Click on song
4. And it closes whole playlist or song or sometimes app crashes

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

https://github.com/user-attachments/assets/cee0e0f2-4dc1-4bae-99a0-4c21b9c52493

### What was your expectation?

Songs to play without whole app crashing or playlist to stop

### What more can you tell us? (Optional)

This issue is also there in other devices I used running 12 or 13 Android virsion

**Comment by knighthat** [comment]
1. Did you reload the song? Go to `Songs` tab > find, open song's menu by click and hold the song > update
2. Search this song again and play directly from search result.

> If you can play the song from search result, go back to `Songs` tab and delete old song. Its ID probably got replaced by YT so you can't play it

**Comment by Ashubnx** [comment]
Is there any option to update full playlist coz I have to update minimum
100 songs

**Comment by knighthat** [comment]
None of them is playable?

**Comment by Ashubnx** [comment]
I can't go check song by song.. it would take hours is there any shortcut
to update songs make the process faster.

**Comment by knighthat** [comment]
Currently there's no way to mass update.

I experienced this before and it only happened to a few songs because YTM changed song's ID

**Comment by Ashubnx** [comment]
Ok, I'll check it out.

**Comment by fast4x** [comment]
Not reproducible

**Comment by Ashubnx** [comment]
Ok, thanks for the reply.

**Comment by fast4x** [comment]
You are welcome
