### ISSUE TITLE
Delete song from playlist

### ISSUE THREAD

**Issue by DrewVix** [fast4x/RiMusic#4612]
### Version of RiMusic

0.6.61

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

If you delete a song from a playlist, a song from the end of playlist go to posición 1 and it stays there forever

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Delete a song from a playlist and the structure of the playlist stays same

**Comment by knighthat** [comment]
Do you mind posting a video?

**Comment by DrewVix** [comment]
https://github.com/user-attachments/assets/efe32fce-0f56-4d67-af60-c90b65437b1a

Here is the video, I was checking the functionality but didnt find anything

**Comment by DrewVix** [comment]
Perfect, dude. I'm an Android developer, but I'm not too specialized in Compose and it takes me longer than normal to review this type of bugs. I'll keep you updated on anything.

**Comment by knighthat** [comment]
let me know if you found anything related, I'll keep you posted also

**Comment by fast4x** [comment]
Sorry, but i not have undestand the problem, if i delete a song from playlist it's deleted without problem...

**Comment by knighthat** [comment]
@fast4x Sort the playlist by "descending position" > delete a song > a song from bottom of the list jumps to top

**Comment by fast4x** [comment]
Ah ok i haven't look for this, sorry

**Comment by knighthat** [comment]
so, I did some poling and found that this piece causes the problem

```kotlin
Database.asyncTransaction {
    move(playlistId, positionInPlaylist, Int.MAX_VALUE)
    delete(SongPlaylistMap(song.id, playlistId, Int.MAX_VALUE))
}
```

Why? Idk. But I made a separate query 

```sql
DELETE FROM SongPlaylistMap WHERE playlistId = :playlistId AND songId = :songId
```

Which fixes the problem

---

But I'm not done yet. Deleting a record creates a gap in position, for now, there's no problem, but I'm looking for a way to recalibrate the position after the deletion

If you have any idea, please comment below

**Comment by knighthat** [comment]
idk, this piece of code is really old, it was made by the guy who made ViMusic

![Screenshot_20241129_004454](https://github.com/user-attachments/assets/cb2be17b-2282-46ea-9d4c-d90b5c05ce46)

![Screenshot_20241129_004527](https://github.com/user-attachments/assets/ac1c8ed0-9325-47f4-9bcb-94aca35ce8de)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.62

**Comment by DrewVix** [comment]
Thank you guys!

**Comment by knighthat** [comment]
@fast4x did you make an algo to recalibrate the position?
