### ISSUE TITLE
Error when clicking "favorite 200" in playlist while music is playing

### ISSUE THREAD

**Issue by Figim** [fast4x/RiMusic#4614]
### Version of RiMusic

0.6.61

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. You have been using RiMusic for some time
3. Play music and click Favorite 200 in the playlist
4. Boom! Crash happens

### Submit a video

I couldn't open the app because it crashes and there is no video here. I went from widgets to albums and then copied the crash log from settings😁

I am using a customized theme. I have cleared the application data, restored it again and the error does not repeat. You try, maybe it will happen. But backup your data

### What was your expectation?

No error when you open favorite 200 while the music is playing

### What more can you tell us? (Optional)

2024-11-16T07:14:07.688:	java.lang.NullPointerException
	 C8.J.b(SourceFile:334) 
	 O.C.e(SourceFile:129) 
	 h9.u.i(SourceFile:129) 
	 h9.n.s(SourceFile:12) 
	 J8.a.k(SourceFile:9) 
	 e9.L.run(SourceFile:107) 
	 K0.a0.q0(SourceFile:7) 
	 K0.Z.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2024-11-23T17:25:09.679:	java.lang.NullPointerException
	 B8.I.b(SourceFile:323) 
	 O.C.i(SourceFile:129) 
	 g9.u.i(SourceFile:129) 
	 g9.n.t(SourceFile:12) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 K0.Z.q0(SourceFile:7) 
	 K0.Y.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2024-11-23T17:25:12.337:	java.lang.NullPointerException
	 B8.I.b(SourceFile:323) 
	 O.C.i(SourceFile:129) 
	 g9.u.i(SourceFile:129) 
	 g9.n.t(SourceFile:12) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 K0.Z.q0(SourceFile:7) 
	 K0.Y.doFrame(SourceFile:10) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:866) 
	 android.view.Choreographer.doFrame(Choreographer.java:792) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2024-11-23T17:25:14.806:	java.lang.NullPointerException
	 B8.I.b(SourceFile:323) 
	 O.C.i(SourceFile:129) 
	 g9.u.i(SourceFile:129) 
	 g9.n.t(SourceFile:12) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 K0.Z.q0(SourceFile:7) 
	 K0.Y.doFrame(SourceFile:10) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:866) 
	 android.view.Choreographer.doFrame(Choreographer.java:792) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2024-11-23T17:25:17.116:	java.lang.NullPointerException
	 B8.I.b(SourceFile:323) 
	 O.C.i(SourceFile:129) 
	 g9.u.i(SourceFile:129) 
	 g9.n.t(SourceFile:12) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 K0.Z.q0(SourceFile:7) 
	 K0.Y.doFrame(SourceFile:10) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:866) 
	 android.view.Choreographer.doFrame(Choreographer.java:792) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2024-11-23T17:25:19.650:	java.lang.NullPointerException
	 B8.I.b(SourceFile:323) 
	 O.C.i(SourceFile:129) 
	 g9.u.i(SourceFile:129) 
	 g9.n.t(SourceFile:12) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 K0.Z.q0(SourceFile:7) 
	 K0.Y.doFrame(SourceFile:10) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:866) 
	 android.view.Choreographer.doFrame(Choreographer.java:792) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2024-11-23T17:25:22.287:	java.lang.NullPointerException
	 B8.I.b(SourceFile:323) 
	 O.C.i(SourceFile:129) 
	 g9.u.i(SourceFile:129) 
	 g9.n.t(SourceFile:12) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 K0.Z.q0(SourceFile:7) 
	 K0.Y.doFrame(SourceFile:10) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:866) 
	 android.view.Choreographer.doFrame(Choreographer.java:792) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2024-11-23T17:25:24.669:	java.lang.NullPointerException
	 B8.I.b(SourceFile:323) 
	 O.C.i(SourceFile:129) 
	 g9.u.i(SourceFile:129) 
	 g9.n.t(SourceFile:12) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 K0.Z.q0(SourceFile:7) 
	 K0.Y.doFrame(SourceFile:10) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:866) 
	 android.view.Choreographer.doFrame(Choreographer.java:792) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2024-11-23T17:25:27.105:	java.lang.NullPointerException
	 B8.I.b(SourceFile:323) 
	 O.C.i(SourceFile:129) 
	 g9.u.i(SourceFile:129) 
	 g9.n.t(SourceFile:12) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 K0.Z.q0(SourceFile:7) 
	 K0.Y.doFrame(SourceFile:10) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:866) 
	 android.view.Choreographer.doFrame(Choreographer.java:792) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2024-11-23T17:25:38.921:	java.lang.NullPointerException
	 B8.I.b(SourceFile:323) 
	 O.C.i(SourceFile:129) 
	 g9.u.i(SourceFile:129) 
	 g9.n.t(SourceFile:12) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 K0.Z.q0(SourceFile:7) 
	 K0.Y.doFrame(SourceFile:10) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:866) 
	 android.view.Choreographer.doFrame(Choreographer.java:792) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2024-11-23T17:25:57.294:	java.lang.NullPointerException
	 B8.I.b(SourceFile:323) 
	 O.C.i(SourceFile:129) 
	 g9.u.i(SourceFile:129) 
	 g9.n.t(SourceFile:12) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 K0.Z.q0(SourceFile:7) 
	 K0.Y.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2024-11-23T17:25:59.720:	java.lang.NullPointerException
	 B8.I.b(SourceFile:323) 
	 O.C.i(SourceFile:129) 
	 g9.u.i(SourceFile:129) 
	 g9.n.t(SourceFile:12) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 K0.Z.q0(SourceFile:7) 
	 K0.Y.doFrame(SourceFile:10) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:866) 
	 android.view.Choreographer.doFrame(Choreographer.java:792) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2024-11-23T17:26:45.126:	java.lang.NullPointerException
	 B8.I.b(SourceFile:323) 
	 O.C.i(SourceFile:129) 
	 g9.u.i(SourceFile:129) 
	 g9.n.t(SourceFile:12) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 K0.Z.q0(SourceFile:7) 
	 K0.Y.run(SourceFile:3) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

2024-11-23T17:26:47.506:	java.lang.NullPointerException
	 B8.I.b(SourceFile:323) 
	 O.C.i(SourceFile:129) 
	 g9.u.i(SourceFile:129) 
	 g9.n.t(SourceFile:12) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 K0.Z.q0(SourceFile:7) 
	 K0.Y.doFrame(SourceFile:10) 
	 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106) 
	 android.view.Choreographer.doCallbacks(Choreographer.java:866) 
	 android.view.Choreographer.doFrame(Choreographer.java:792) 
	 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092) 
	 android.os.Handler.handleCallback(Handler.java:938) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:226) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by knighthat** [comment]
I'm not sure if I understand "Favorite 200", you mean "Top 200" songs? 

If you'd like to do a little experiment. Backup your database > reset database > Use the app for couple weeks to accumulate "Favorite 200" > attempt to recreate problem

**Comment by knighthat** [comment]
Do you mind telling me which language you're using. I suspect 1 of the strings is missing from your language pack

**Comment by twistios** [comment]
I also am/was able to trigger a similar bug. The app is set to "English". It could (in my case maybe) be caused by #4619.
For me it is triggered by going to "Top 10" section. The app has to be started in a songs-section that is neither favorites, top 10 nor local songs.

**Comment by fast4x** [comment]
If possible attach here a backup of your database. I'll use for debug directly.

**Comment by knighthat** [comment]
You mean 10m and below causes error or 10m and above?
