### ISSUE TITLE
Low Resolution Music Cover on Android Auto

### ISSUE THREAD

**Issue by AdidasGamer** [fast4x/RiMusic#4616]
### Version of RiMusic

0.6.61

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Connet to Android Auto
3. Play a Music
4. Music Cover is in Low Resolution

### Submit a video

![Screenshot_20241123-112018](https://github.com/user-attachments/assets/b68deaaa-cb8d-4713-bea4-343a259bcb07)
![Screenshot_20241123-112056](https://github.com/user-attachments/assets/2ed81b21-c82f-4fa0-b67c-f8bf42209d57)

### What was your expectation?

The Music cover would be in it's normal resolution

**Comment by knighthat** [comment]
reset song by following these steps:

1. Go to `Songs` tab
2. Find, tap and hold song to open song's menu
3. Press Update > confirm update
4. Check if problem persists

**Comment by Tre916** [comment]
I'm having this same issue but I know the full rez cover art is present because the default android player in the notification shade has the full rez art. If I didn't know any better I would say that the app is presenting the blurred cover art that is used as the background of the in-app player.

**Comment by knighthat** [comment]
@Tre916 please post pictures of the problem.

**Comment by AdidasGamer** [comment]
![Screenshot_20241129_124446](https://github.com/user-attachments/assets/9bb8842d-5a43-4307-bac5-1baf87e1354c)
![Screenshot_20241129_124459_One UI Home](https://github.com/user-attachments/assets/cfcc8b90-cb4b-4505-b572-0b32f0766a5d)
![389203470-2ed81b21-c82f-4fa0-b67c-f8bf42209d57](https://github.com/user-attachments/assets/5fd65a09-1fe1-40c4-bf1d-6c43721e9121)
Both in App and Notification Panel are showing the full resolution cover art, except Android Auto that is showing the low resolution cover

**Comment by egpheel** [comment]
I'm also having this issue. Not on all songs (but on most) though so I'm not sure what the reason is.

**Comment by knighthat** [comment]
@egpheel If you can, please remove cache to let the app download the thumbnail again

**Comment by egpheel** [comment]
> @egpheel If you can, please remove cache to let the app download the thumbnail again

I tried that and had the same results unfortunately

**Comment by knighthat** [comment]
that's weird, I thought this problem was fixed long time ago. I'll have to take a look at it again, but it'll take a while because my schedule is packed

**Comment by egpheel** [comment]
> that's weird, I thought this problem was fixed long time ago. I'll have to take a look at it again, but it'll take a while because my schedule is packed

Sounds good to me. If it helps, I only get bad resolution on android auto. It's fine everywhere on my phone.

**Comment by carlozvv** [comment]
Hi. Happy new year. Same problem here. Android Auto shows all covers with low resolution. May you check what happen? Thanks.

**Comment by fast4x** [comment]
try with update song, maybe you have image cached in low resolution by first time when bug was present

**Comment by egpheel** [comment]
> try with update song, maybe you have image cached in low resolution by first time when bug was present

Hi, I did try several times but the problem persists

**Comment by carlozvv** [comment]
Update song doesn't work. Last version v0.6.67 same problem. Tested with clean installation. Problem persists.
