### ISSUE TITLE
Loading from DB not properly working in HomeSongs

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#4619]
### Version of RiMusic

0.6.61 (custom version) or current latest commit in my master branch

### Android version

14

### Tell us how you trigger this bug

1. Open RiMusic
2. Open "Songs" section
3. Switch between different tabs (all, favourites, cached)

### Submit a video

https://github.com/user-attachments/assets/83436349-141f-4acd-8518-229c4664a845

### What was your expectation?

The songs should be correctly loaded

### What more can you tell us? (Optional)

This is a regression from 0.6.60 to 0.6.61.
Sometimes the songs don't load at all or only an incorrect number of songs is shown. When clicking on a song, it then only shows the correct amount of songs.

**Comment by knighthat** [comment]
I think this is a new recommendation system. It's supper annoying imo

**Comment by twistios** [comment]
I assume it has something to do with your pull request https://github.com/fast4x/RiMusic/pull/4603 @knighthat

**Comment by twistios** [comment]
Just so it is clear, this is happening nor in regular 0.6.61 but 0.6.61 custom version I got from fast4x. It also happens with the latested released changes.

**Comment by knighthat** [comment]
PR #4603 just got merged few hours ago so I don't think it made it way to any release version yet. Besides, I didn't touch the queue system. I'll take a look and do some comparison

**Comment by twistios** [comment]
It got merged 13h ago and I got the custom version from fast4x himself. As I said, it also happens with the released/public changes from the Repo in the debug build I made.

**Comment by knighthat** [comment]
Idk if you made any changes on your end, but I cloned fresh repo straight from github then compiled it and I couldn't seem to recreate the problem.

Here's the queue after my PR

https://github.com/user-attachments/assets/030c42e8-b90e-42d6-8dc9-83d73e5ac311

Here's the video before all of my changes

https://github.com/user-attachments/assets/c90e09ab-9a82-4299-9ff5-b29a665ff22a

> Did you reset all settings to default?

**Comment by twistios** [comment]
The queue is correct, the menu is not. I showed the queue to show that the menu is incorrect. In the video you can also see, that it shows 69 for cached while zero are loaded. As it can be seen from the video, I have ~1000 cached songs but at some point it claims that it is ~3000.

**Comment by twistios** [comment]
The queue is correct, the menu is not. I showed the queue to show that the menu is incorrect. In the video you can also see, that it shows 69 for cached while zero are loaded. As it can be seen from the video, I have ~1000 cached songs but at some point it claims that it is ~3000.

**Comment by knighthat** [comment]
Confirmed! I'm looking into it right now

**Comment by twistios** [comment]
The funny thing is it says something like 3000 songs for cached and a similar but different value for all (which is correct), so somehow, this number is related but not the same. When it shows the same for favourites and cached, then it really is the same value, so I don't understand it.

**Comment by twistios** [comment]
This bug also has an interesting side effect: top 10 is fully broken.

<details><summary>Showcase for Top 10 Bug</summary>
<p>

https://github.com/user-attachments/assets/8a0ac161-f844-4062-93c6-06b5b7eae509

</p>
</details>

**Comment by knighthat** [comment]
I noticed that too, if you spam it by changing from "all", "favorite", etc. it'll show content from another tab (racing condition). Can't believe I let it slip right through.

A patch is in development. Will push to upstream soon

**Comment by knighthat** [comment]
> The funny thing is it says something like 3000 songs for cached and a similar but different value for all (which is correct), so somehow, this number is related but not the same. When it shows the same for favourites and cached, then it really is the same value, so I don't understand it.

3000 is how many songs existed in the database, if you take a look at the code [HERE](https://github.com/fast4x/RiMusic/blob/db92bcb9bcc9731bcd7ed37399ae98a7d4332201/composeApp/src/androidMain/kotlin/it/fast4x/rimusic/ui/screens/home/HomeSongs.kt#L408-L433) and [HERE](https://github.com/fast4x/RiMusic/blob/db92bcb9bcc9731bcd7ed37399ae98a7d4332201/composeApp/src/androidMain/kotlin/it/fast4x/rimusic/ui/screens/home/HomeSongs.kt#L448-L466) you'll see that the query is actually query most if not all records from database, then perform sort after the fetch. With the current implementation of showing [how many songs were fetched](https://github.com/fast4x/RiMusic/blob/db92bcb9bcc9731bcd7ed37399ae98a7d4332201/composeApp/src/androidMain/kotlin/it/fast4x/rimusic/ui/screens/home/HomeSongs.kt#L511), it's normal to see large number of songs while not seeing anything on screen

**Comment by knighthat** [comment]
@twistios I just push a small change [HERE](https://github.com/knighthat/RiMusic/tree/stable-homesongs). Idk if Git and Github let you cross pull branches from another project. But it'd be helpful if you can give me some feedback on this

**Comment by twistios** [comment]
I can clone your repo and then checkout the branch. But not today.

**Comment by knighthat** [comment]
take your time

**Comment by twistios** [comment]
It seems that I can confirm the fix for the problem.

@knighthat about that you asked me to help you or check something, is it still required and if yes, what should I test?
