### ISSUE TITLE
Crash when scrolling to bottom of Playlists tab in Library page.

### ISSUE THREAD

**Issue by AstroLightz** [fast4x/RiMusic#4620]
### Version of RiMusic

0.6.61

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Go to the Library page
3. Make sure you're on the Playlists tab, and have enough playlists that you need to scroll to see them all.
4. Scroll to the bottom.
5. Crash

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I would scroll to the bottom and be able to access playlists there.

### What more can you tell us? (Optional)

I tested this with only a few playlists (Not enough to scroll), and there's no issues.

### Logs (Optional)

2024-11-23T12:49:46.816:	java.lang.NullPointerException: c.getString(index) must not be null
	 h4.e.m(SourceFile:17) 
	 G7.k.b(SourceFile:193) 
	 k4.g.t(SourceFile:208) 
	 k4.g.l(SourceFile:13) 
	 h4.b.a(SourceFile:9) 
	 e4.D.q(SourceFile:7) 
	 k4.d.t(SourceFile:44) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	 java.lang.Thread.run(Thread.java:1012)

**Comment by knighthat** [comment]
I have 51 playlists, 3 playlists on each line. I scroll down to the bottom and nothing happens

**Comment by fast4x** [comment]
Maybe there's a song in error without id, i've added a workaround to exclude this condition.
Available from version 0.6.62
