### ISSUE TITLE
Error sorting explicit and non-explicit songs alphabetically

### ISSUE THREAD

**Issue by 97carmine** [fast4x/RiMusic#4623]
### Version of RiMusic

0.6.61

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Sort songs alphabetically
3. Songs that contain the E for explicit use that letter in the order and not the name of the song

### Submit a video

![Screenshot_20241123-213737_RiMusic](https://github.com/user-attachments/assets/b525ea24-a9d4-46b5-bc1e-79a4bb0f7e10)

### What was your expectation?

Songs should be arranged alphabetically

**Comment by knighthat** [comment]
Confirmed, I'm looking into it right now

**Comment by 97carmine** [comment]
Please consider reopen

While the issue has been resolved in playlists, it has not been resolved in the "default lists" of the Songs app such as All, Favorites, Cached and Downloaded.
