### ISSUE TITLE
Change of music

### ISSUE THREAD

**Issue by bauldihr** [fast4x/RiMusic#4624]
### Version of RiMusic

0.6.61.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

When I change music, the music I had already changed returns. Example:

Music X 
>>
Music Y
>>
Music X

Instead of going to Z, it goes back to X (illustrating example)

### Submit a video

.

### What was your expectation?

.

### What more can you tell us? (Optional)

.

### Logs (Optional)

.

**Comment by twistios** [comment]
There is no version 0.6.61.1, only 0.6.61.
About your bug, this is a known bug (at least a variant of it). If you are not able to bring us the "enlightment" for this bug what exactly needs to happen for it to appear, we will not be able to fix it (we can not reproduce this bug reliably so we can not fix it).
A workaround is to use essential player instead of modern player.

**Comment by bauldihr** [comment]
It's the essential

**Comment by twistios** [comment]
You get this problem with "essential player"?

**Comment by bauldihr** [comment]
No. I don't. Not at all, this problem happens when I change music using the phone's notifications.

**Comment by bauldihr** [comment]
What should I do, bro? Wait for an update?

**Comment by twistios** [comment]
If this bug annoys you too much, use essential player otherwise just use it as before. The bug also happens for me but very rarely now.

We currently can not fix this problem.

**Comment by bauldihr** [comment]
> Se esse bug te incomoda muito, use o essential player, senão use-o como antes. O bug também acontece comigo, mas muito raramente agora.
> 
> No momento, não podemos corrigir esse problema.

![Screenshot_2024-11-28-13-07-39-865_it fast4x rimusic](https://github.com/user-attachments/assets/e3804da7-1b8a-4f9b-b8d6-cb0bfdbda334)

The bug happens here @fast4x @twistios When I change the song, it returns to the one that was already listened to/skipped. If I listen to/skip song A, it goes to B, but instead of being song C, it returns to A. This happens the same way when I return/go back to the previous song.

**Comment by fast4x** [comment]
Ah ok it's a know bug
