### ISSUE TITLE
[Translation]: Some string are missing from Crowdin

### ISSUE THREAD

**Issue by Figim** [fast4x/RiMusic#4626]
### Description

I noticed that some strings are not in Crowdin

### Suggested Solution

Add them to Crowdin

### Alternatives

The application does not support the  letter ( İ )
In main titles, this letter is shown as ( I ). It's wrote ( İ ) in Crowdin, and rightly so. For the Azerbaijani language. This is not a translation bug. The application does not display this letter in some area

![Screenshot_20241124-095205](https://github.com/user-attachments/assets/6313f219-6014-40e0-9f79-39a972a5f12c)
![Screenshot_20241124-095153](https://github.com/user-attachments/assets/32273d8f-e3b8-4bde-8efb-2ab66e50af89)
![Screenshot_20241124-095227](https://github.com/user-attachments/assets/9f4049a8-839a-4cab-91c6-70071db5a8d6)
![Screenshot_20241124-095217](https://github.com/user-attachments/assets/39827ac0-8fe9-4eb4-bd89-e57f553a439e)
![Screenshot_20241124-124157](https://github.com/user-attachments/assets/341bb10e-eadc-442d-975f-dc52ef2e4f1b)

### Additional Context

![IMG_20241124_093722_825](https://github.com/user-attachments/assets/c6694e2f-a6fd-45f1-aba8-5f51a59527c5)
![IMG_20241124_093722_805](https://github.com/user-attachments/assets/29e9df6c-67c5-4d43-b253-f08c0da3ce27)
![IMG_20241124_093723_313](https://github.com/user-attachments/assets/f04fb192-1c32-4538-9701-8bb971415096)
![IMG_20241124_093723_154](https://github.com/user-attachments/assets/f46c1fc3-0e2c-44cd-b424-e56584b5b35e)

**Comment by fast4x** [comment]
Thanks for details

**Comment by fast4x** [comment]
Fixed missed translations, available from version 0.6.62

**Comment by fast4x** [comment]
> Strings do not exist in Crowdin

Look...Fixed missed translations, available from version 0.6.62
