### ISSUE TITLE
[Feature]: Welcome words when entering the application

### ISSUE THREAD

**Issue by Figim** [fast4x/RiMusic#4627]
### Description

"Good morning" message when the user opens the application in the morning. Very Afternoon, Evening

**Also Welcome**

### Suggested Solution

Also some questions and words to the user
1. What do you want to listen to today? Etc

### Alternatives

YouTube music offers them

### Additional Context

![Screenshot_20241124-154532_SimpMusic](https://github.com/user-attachments/assets/6cd3a093-6f79-41cd-abeb-23f6fb6c4b7d)

**Comment by fast4x** [comment]
Why it's a feature that you like?

**Comment by fast4x** [comment]
Ok I'll implement it

**Comment by fast4x** [comment]
Implemented, available from version 0.6.62
