### ISSUE TITLE
Button does not respond

### ISSUE THREAD

**Issue by woskkdmsosid** [fast4x/RiMusic#4629]
### Version of RiMusic

0.6.61

### Android version

13

### I've done these:

- [ ] Uninstall old build before installing a new one
- [ ] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Turn "show thumbnail for lyrics" on
3. Play song
4. Click the lyrics button or thumbnail of song
5. Click the fullscreen lyrics button
6. Kaboom nothing happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I clicked fullscreen lyrics so it would give me fullscreen lyrics DUHH

### What more can you tell us? (Optional)

kaboom

**Comment by fast4x** [comment]
Thanks for reporting, lyrics fullscreen mode it's deprecated, use modern settings in appearance settings.
