### ISSUE TITLE
[Feature]: Translated lyrics from Lyricstranslate.com

### ISSUE THREAD

**Issue by DucksInParks** [fast4x/RiMusic#463]
### Description

Automated translations aren't good and can't translate to any desired language

### Suggested Solution

Would be very great if you scraped lyricstranslate.com [(read more info about scraping it here)](https://lyricstranslate.com/en/forum/suggestions/api-developers) and allowed users to use it to see translated lyrics. The lyrics in LyricsTranslate are manually translated by volunteers, and so many songs are translated into many languages.

**Comment by fast4x** [comment]
Hi, do you have any news about the availability of free APIs to use?

**Comment by fast4x** [comment]
Adminitrator forum Say:
Please keep in mind that we pay for lyrics licensing, so licensed content from the site pages should not be used.
If you're interested in lyrics API, you can contact musixmatch.com for their terms of API usage.

**Comment by DucksInParks** [comment]
The translations are written and owned by the volunteers (unless when released under a less restrictive license). I believe the original lyrics are the ones they are licensed, which don't need to be scrapped for this feature.

**Comment by DucksInParks** [comment]
See here: https://lyricstranslate.com/en/copyrights

I doubt the authors will have any problem with this, especially if their usernames are included.

**Comment by fast4x** [comment]
This is a doubt:
Lyrics on Lyricstranslate.com are licensed through Musixmatch.

**Comment by fast4x** [comment]
Implemented, added new provider lyrics LrcLib.net.
Available from version 0.6.28.1
