### ISSUE TITLE
No se conecta con datos móviles

### ISSUE THREAD

**Issue by Kreathorx** [fast4x/RiMusic#4631]
### Version of RiMusic

0.6.61

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1 se abre rimusic
2.no se conecta
![Screenshot_20241124_121557](https://github.com/user-attachments/assets/6a97e2fc-d9ab-4f4c-b976-ff59b46564c3)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Que puedan solucionar, ya que es la única app que nos se conecta a Internet por datos móviles

**Comment by fast4x** [comment]
I think that is a your specific issue

**Comment by Kreathorx** [comment]
Que opción me pueden brindar, es la única app que tengo en el teléfono que no se conecta a datos móviles, en WiFi funciona sin problemas 😔

**Comment by fast4x** [comment]
Your device is?

**Comment by Kreathorx** [comment]
Desinstalé la app, instale una versión anterior y ya funciona con normalidad
