### ISSUE TITLE
The settings button does not appear in the app

### ISSUE THREAD

**Issue by EliasNavaXD** [fast4x/RiMusic#4635]
### Version of RiMusic

0.6.61

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. The settings button does not appear in the top corner of the app.
![Screenshot_20241124-223339](https://github.com/user-attachments/assets/caf2a62c-00ae-47e1-9de0-140a811a853d)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

that the configuration button appears normally

### What more can you tell us? (Optional)

This error appeared since version 0.6.60. I thought they solved it but when I updated to the most recent version, the configuration button still did not appear. Now I cannot make any configuration.

**Comment by Milton86cmd** [comment]
the same thing happens to me too
![Screenshot_20241124_225443](https://github.com/user-attachments/assets/d0e2181b-7808-4cf6-a26c-06fed1c777ed)

**Comment by fast4x** [comment]
Scroll up vertical navigation menu

**Comment by knighthat** [comment]
@fast4x why'd you want to move those buttons to the bottom?

**Comment by fast4x** [comment]
Because i like it to the bottom, it's different from others ViMusic forks

**Comment by knighthat** [comment]
LOL

**Comment by EliasNavaXD** [comment]
https://github.com/user-attachments/assets/6b7af215-60d9-4b9f-86ef-f870d9cb4b1b


> Desplácese hacia arriba por el menú de navegación vertical

How do I do it?

**Comment by EliasNavaXD** [comment]
> Sí, no puedo entender cómo, por cierto, todavía no está solucionado, así que no sé por qué está marcado como completado.

I already reported it again in the new version and I still get this error
