### ISSUE TITLE
[Feature]: agregarle la opción de buscar canción en la barra de notificación 

### ISSUE THREAD

**Issue by Alfa0796** [fast4x/RiMusic#4636]
### Description

En la barra de notificación me gustaría que se pudiera buscar la canción sin necesidad de entran ala app como una lupa para buscar desde ahi

### Suggested Solution

Al activar una opción que se habilite la opción buscar desde barra de notificación y aparezca en la parte de abajo o arriba de la notificación buscar cancion

### Alternatives

Poner buscar con vos la cancion

### Additional Context

Bueno es una sugerencia

**Comment by Alfa0796** [comment]
Sería bueno

**Comment by fast4x** [comment]
Ok I'll try

**Comment by fast4x** [comment]
Implemented, available from version 0.6.62
