### ISSUE TITLE
Not able to listen to songs online

### ISSUE THREAD

**Issue by knova9** [fast4x/RiMusic#4637]
### Version of RiMusic

0.6.61

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on any music that's not downloaded
3. Doesn't play
4. Try to download it
5. Download failed
6. If a downloaded music comes in the queue, it plays

### Submit a video

https://github.com/user-attachments/assets/04da7ae4-eced-43ce-ae08-394de5c9c52e

### What was your expectation?

To listen to songs online and download them

**Comment by fast4x** [comment]
Maybe you must login in ytm in your country

**Comment by knova9** [comment]
> Maybe you must login in ytm in your country

YTMusic In RiMusic or In The YTMusic App?

**Comment by knova9** [comment]
> > Maybe you must login in ytm in your country
> 
> YTMusic In RiMusic or In The YTMusic App?

Ayy bro I disconnected and connected YTM again it worked thansk

**Comment by knova9** [comment]
Hey @fast4x it's happening again and now not even log out and logging in can't help
