### ISSUE TITLE
[Feature]:  Add "Use Sd Card" feature for user's who have low little amount of storage

### ISSUE THREAD

**Issue by JimJam-arch** [fast4x/RiMusic#4644]
### Description

It's somewhat a struggle for me and other's alike to have ri-music going as far as getting large amount of storage through your phone. Suggesting that transferring files to Sd Card can help resolve the issue.

### Suggested Solution

Just a "Use Sd Card" like the feature from yt music is a very concised amount of information from a non-developer person.

**Comment by fast4x** [comment]
Not possible sorry, it require high system permissions that RiMusic don't want to request for privacy.
