### ISSUE TITLE
"Change Cover" option not working properly

### ISSUE THREAD

**Issue by Davutha** [fast4x/RiMusic#4647]
### Version of RiMusic

0.6.61

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Select any album 
3. Click on "change cover"
4. Change the cover
5. Custom album cover isn't displaying on miniplayer/full player
6. The cover resets to default after reopening the app

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

The custom cover should be displayed on the player and save after closing the app

### What more can you tell us? (Optional)

I also tried using Twitter/Discord/Google image links

![Screenshot_2024-11-25-20-10-11-067_it fast4x rimusic](https://github.com/user-attachments/assets/25cb0280-0a36-4079-bc3d-911b1a19c656)
![Screenshot_2024-11-25-20-10-03-426_it fast4x rimusic](https://github.com/user-attachments/assets/69a8ab80-2419-4288-a63e-cd472f37c5b3)

**Comment by Davutha** [comment]
forgot to post this pic
![Screenshot_2024-11-25-20-21-40-433_it fast4x rimusic](https://github.com/user-attachments/assets/02365237-74e3-40c1-9281-4b05809ff5bc)

**Comment by fast4x** [comment]
Remember that must flag custom value field when change url of cover, without flag custom value, cover will be overwritten.

**Comment by Davutha** [comment]
with the custom value field activated the custom cover doesn't even show on the album screen

**Comment by fast4x** [comment]
> with the custom value field activated the custom cover doesn't even show on the album screen, I used the option in the first 2 screenshots

Look 

https://github.com/user-attachments/assets/b2684d64-2e64-4f43-81b4-6888cbc92f8f
