### ISSUE TITLE
Short and concise description of your bug

### ISSUE THREAD

**Issue by KindlyOnes** [fast4x/RiMusic#4649]
### Version of RiMusic

0.6.61 (69)

### Android version

5.0.1

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on a song or
3. Click on a album or
4. Click on search
5. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I know My phone is old. It would be really good for me if the app works.

### What more can you tell us? (Optional)

My Device Samsung  S4 i9500
Android version Lollipop 5.0.1 (21)

### Logs (Optional)

[crash1.txt](https://github.com/user-attachments/files/17910315/crash1.txt)
[crash2.txt](https://github.com/user-attachments/files/17910320/crash2.txt)

**Comment by twistios** [comment]
Some of the errors from your debug log I have seen already (json token problem). So I assume this error at least can probably be fixed.

Where do you experience this error (what are you trying to do)?

As your Android version is older than Android 7, there are already features of RiMusic that are not compatible, and I think they are already disabled in incompatible Android versions.

**Comment by twistios** [comment]
By the way, latest version is 0.6.61.

**Comment by KindlyOnes** [comment]
> Some of the errors from your debug log I have seen already (json token problem). So I assume this error at least can probably be fixed.
> 
> Where do you experience this error (what are you trying to do)?
> 
> As your Android version is older than Android 7, there are already features of RiMusic that are not compatible, and I think they are already disabled in incompatible Android versions.

The app closes or crashes right after opening a song.

**Comment by KindlyOnes** [comment]
> By the way, latest version is 0.6.61.

I corrected it, I wrote it wrong.

**Comment by fast4x** [comment]
Crash 2 contain an error of your device for OUT OF MEMORY, it occur when device memory is full...

**Comment by twistios** [comment]
I checked the specification of the device (family) and it has 2GB of RAM. This is not much but I guess RiMusic should still work if any modern app works. On my device, RiMusic currently needs 170MB.

**Comment by fast4x** [comment]
> I checked the specification of the device (family) and it has 2GB of RAM. This is not much but I guess RiMusic should still work if any modern app works. On my device, RiMusic currently needs 170MB.

Correct, but you must consider total of process in device memory...

**Comment by fast4x** [comment]
I've improved cached quick pics based oh error in crash 1

**Comment by KindlyOnes** [comment]
@fast4x 

Hello

I didn't want to open a new base for such an old device. It is not possible to download audio from the app. I always get a download failed error. Some of them even allow you to download without logging in. Also YouTube music login is not working, if that is necessary. I don't have the original YouTube app on my device. But I can install it. 

Everything is working fine. Thanks again.
