### ISSUE TITLE
Title sorting in the favorites playlist

### ISSUE THREAD

**Issue by ghost** [fast4x/RiMusic#465]
### Description

I would also like to have this sorting option in the favorites playlist. That way you would always have the most recently liked song at the top.

See screenshot.

### Suggested Solution

![Screenshot_20240121-133255_1](https://github.com/fast4x/RiMusic/assets/157226228/7c0c1aad-7574-4e64-abc9-bc9c9de4e761)

**Comment by ikanakova** [comment]
I like it. Except I'd replace the arrow with a heart.

**Comment by fast4x** [comment]
Hi, this option on playlist sort for position number into playlist.
Perhaps you are referring to the first icon that sorts songs according to the last heard?
![2024-01-21_15h59_19](https://github.com/fast4x/RiMusic/assets/1484476/9da30c71-9ffc-4429-a3bd-e9e8870c9a5a)

**Comment by Seryoga1984** [comment]
I think the favorited song should always be at the top of the favorites, regardless of when it was added to the library.

**Comment by fast4x** [comment]
But the favorite list already has all the favorite songs

**Comment by Seryoga1984** [comment]
> But the favorite list already has all the favorite songs

I think we're talking past each other.
Okay, not to cause any more confusion.  I'll try to explain it in pictures. The sorting function from screenshot 1.
I would like to see in the favorites Screenshot 2.

![298382962-7c0c1aad-7574-4e64-abc9-bc9c9de4e761](https://github.com/fast4x/RiMusic/assets/157226228/ec072729-0ea3-4800-a01f-64a58cf6f388)


![Screenshot_20240121-174114](https://github.com/fast4x/RiMusic/assets/157226228/831a902b-62b1-450f-a044-cf21d8e0ceb8)

**Comment by fast4x** [comment]
LOL, done available from version 0.6.19
