### ISSUE TITLE
Option to disable deleting songs by swiping to the side

### ISSUE THREAD

**Issue by Diavolo2** [fast4x/RiMusic#4650]
### Description

It would be interesting to have an option to disable the option to delete songs from the playlist by swiping to the side, I always accidentally delete a random song when I'm going through the songs. 

### Suggested Solution

When this option is activated, you no longer delete songs by swiping to the side, but rather by holding and clicking "delete"

### Additional Context

Imagine you have a playlist of more than 300 songs and you accidentally delete one in the middle of the playlist, you will never know which song you deleted

**Comment by twistios** [comment]
You can already disable "Swipe for action".
