### ISSUE TITLE
It stops working every so often

### ISSUE THREAD

**Issue by Teleposse** [fast4x/RiMusic#4660]
### Version of RiMusic

Last 

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Try to Open RiMusic
2. I cant :/

### Submit a video

It doesn't open for me, at first, when I downloaded rimusic for the first time it worked perfectly until one day it stopped opening, I tried everything but it didn't work for me, so, on my own, not knowing what to do,Due to the lack of response, I uninstalled ri music myself and reinstalled it (it was expensive but I did it) and I had to start over (I have a playlist of +400 songs and +24h between them all, with some songs With more than 1 hour and a half listened to
I redid everything with plenty of time and in less than two weeks it happened to me again and I lost everything. I don't want to have to strain myself again and wait in vain for the next time in less than two days Crashes again.Please help me.

I already opened one but because of how slow they were to respond and I don't blame them, but I was expecting something better than "uninstall"

### What was your expectation?

Make something work

### What more can you tell us? (Optional)

I'm fed up, please I don't want to start over, at least tell me how to not have to start from scratch every time I reinstall it.

**Comment by twistios** [comment]
Where did you download RiMusic from? Github, F-Droid, Accresscent?

In case you have downloaded from Github, download version 0.6.61 from Github and install this version.

In case it is F-Droid, either wait until 0.6.61 is available or uninstall the F-Droid version and install 0.6.61 from Github. As you can not open the app, you can not export your database you in this case you will lose your data again. Alternativly you can add the IzzyOnDroid-Repo to F-Droid and install 0.6.61 from there.

In case of Accresscent, currently it is the same as with F-Droid (normally it is faster than F-Droid).

**Comment by fast4x** [comment]
Try hold on icon launcher and copy crash log

**Comment by Teleposse** [comment]
> Where did you download RiMusic from? Github, F-Droid, Accrescent?
> 
> In case you have downloaded from Github, download version 0.6.61 from Github and install this version.
> 
> In case it is F-Droid, either wait until 0.6.61 is available or uninstall the F-Droid version and install 0.6.61 from Github. As you can not open the app, you can not export your database, in this case you will lose your data again. Alternatively you can add the IzzyOnDroid-Repo to F-Droid and install 0.6.61 from there. But I don't know if IzzyOnDroid and F-Droid version are compatible.
> 
> In case of Accrescent, currently it is the same as with F-Droid (normally it is faster than F-Droid).

OpenApk
It doesn't let me even update
In the old one I sent several screenshots, can you see them?The same thing happens to me, I don't know if I'm the only one. Please help me because I love listening to music ALL day and I can't, I have to watch it on YT and I can only do it when I'm sitting down.

**Comment by twistios** [comment]
Based on https://github.com/fast4x/RiMusic/issues/4070 it could seem that you are actually using F-Droid or why else did you show the F-Droid screen?

If you really downloaded it from OpenApk, then download 0.6.61 from there and install it (I.e. update).

In case updating this way does not work, you either installed from a different source or OpenApk breaks it or maybe it already is the latest version of the app.

After updating or the failing of that, please send a screenshot of the app context menu (hold the icon on your Android launcher to show the context menu).

**Comment by twistios** [comment]
![Screenshot_20241127_112716_One UI Home.jpg](https://github.com/user-attachments/assets/befd4513-1fa6-4a28-81f6-f42a1aab3218)

In case it looks like this (I.e. the last icon has these two squares stack on top of each other) then you have 0.6.61 installed. Depending on why the update failed, the update problem has to be solved in a matching way. If you downloaded it from the wrong source, download from correct source or wait until it provides the latest version.

In case the installation got totally broken, uninstall the app, download from Github (instead of OpenApk or F-Droid/...). You will lose your playlist and so on again, but then you are finally on a version that the "RiMusic Team" has proper controll of (and can fix if it breaks, but this is not a guarantee that it might break also for the Github version as it did when the app id changed).

**Comment by twistios** [comment]
Based on the screenshot in #4070, you are not using 0.6.61. Please update your app based on my hints in https://github.com/fast4x/RiMusic/issues/4660#issuecomment-2503498272.

**Comment by Teleposse** [comment]
> Based on the screenshot in #4070, you are not using 0.6.61. Please update your app based on my hints in [#4660 (comment)](https://github.com/fast4x/RiMusic/issues/4660#issuecomment-2503498272).

It won't let me update
I searched for how to download it on GitHub, as you said, but I can't find it. I'll also leave you screenshots of the attempt.
It says that it could not be updated
![IMG_20241128_170545](https://github.com/user-attachments/assets/504054aa-6840-4cd7-9a42-daf656cc9bc9)

**Comment by twistios** [comment]
You can find all releases from Github at https://github.com/fast4x/RiMusic/releases. The latest version can be found at the top of this webpage. Or here is a link to the current version: https://github.com/fast4x/RiMusic/releases/tag/v0.6.61.
The apk-link is https://github.com/fast4x/RiMusic/releases/download/v0.6.61/app-foss-release.apk.

You said that you downloaded from OpenApk. And it is possible that the version from OpenApk is incompatible with the Github version. So download 0.6.61 from OpenApk.

**Comment by Teleposse** [comment]
Is this the first one where it says assets?

**Comment by twistios** [comment]
"Assets" is the set of attached files in a release on Github. An android app file has `.apk` as file extension. As the names suggest, the other two files are the source code of the app. So yes, the first item is the installation file.
Try if this file works, we need to find out what version you have installed exactly.

**Comment by twistios** [comment]
I just checked, OpenApk serves the Github-file, so it should be compatible.

**Comment by Teleposse** [comment]
> "Assets" is the set of attached files in a release on Github. An android app file has `.apk` as file extension. As the names suggest, the other two files are the source code of the app. So yes, the first item is the installation file. Try if this file works, otherwise we need to find out what version you have installed exactly.

I tried to update with the app installed, but it didn't work so I try to all the links,and it didnt work.So Ithought I was installing the app from the beginning, I uninstalled ri music and tried it from all the links and none of them worked, it kept saying it :(

**Comment by twistios** [comment]
> I uninstalled ri music and tried it from all the links

So is RiMusic currently installed or not? If it is not currently installed, then there is a serious problem. Otherwise the installation file is just not compatible with your installed version.

**Comment by Teleposse** [comment]
> > I uninstalled ri music and tried it from all the links
> 
> So is RiMusic currently installed or not? If it is not currently installed, then there is a serious problem. Otherwise the installation file is just not compatible with your installed version.

Neither with the application already installed nor uninstalled.
 P.S.: Thank you for all the time you are spending helping me, I really appreciate it.

**Comment by twistios** [comment]
1. Is RiMusic currently installed?
2. What is your device model? (vendor, device name)

**Comment by Teleposse** [comment]
When I tried it the first time it was installed, then I uninstalled it to see if it worked and it didn't work either. Oppo A 54 5G with ColorOs, is that what you are referring to?

**Comment by Teleposse** [comment]
>1. When I tried it the first time it was installed, then I uninstalled it to see if it worked and it didn't work either. So no,its uninstalled.
2.Oppo A 54 5G with ColorOs, is that what you are referring to?
3.I want to listen to music because I'm on a little trip, even if it's just for a little while, so where do I set it up even if it's just temporary?
If this time it takes even less time to fail, because it takes less time to stop working, I'm going to notice you

**Comment by twistios** [comment]
Based on my research, your phone should have Android 11 (or later) installed. 
If you are using ColorOS 7, then this corresponds to Android 10. I assume that you misinterpreted the ColorOS version for the Android version.

**Comment by Teleposse** [comment]
I updated it the day before yesterday, I have 13.0 if I'm not mistaken, can you answer 3.? It's just temporary, not for long

**Comment by twistios** [comment]
With which file was it possible to install the app?

**Comment by Teleposse** [comment]
> With which file was it possible to install the app?

Idk ill try

**Comment by twistios** [comment]
How did you take the screen shot here https://github.com/fast4x/RiMusic/issues/4070#issuecomment-2506427384? Did you uninstall it after the screenshot?

**Comment by Teleposse** [comment]
> How did you take the screenshot here [#4070 (comment)](https://github.com/fast4x/RiMusic/issues/4070#issuecomment-2506427384)? Did you uninstall it after the screenshot?

Yes,No matter how you tried, it wouldn't open.

**Comment by twistios** [comment]
If the app does not even install when there is no other version of it installed, then I can not help you anymore. If you are able to install any version of RiMusic, then maybe I can help you again.

**Comment by Teleposse** [comment]
> If the app does not even install when there is no other version of it installed, then I can not help you anymore. If you are able to install any version of RiMusic, then maybe I can help you again.

Sorry and thx u

**Comment by Teleposse** [comment]
> You can find all releases from Github at https://github.com/fast4x/RiMusic/releases. The latest version can be found at the top of this webpage. Or here is a link to the current version: https://github.com/fast4x/RiMusic/releases/tag/v0.6.61. The apk-link is https://github.com/fast4x/RiMusic/releases/download/v0.6.61/app-foss-release.apk.
> 
> The permanent link to the latest version is https://github.com/fast4x/RiMusic/releases/latest.
> 
> You said that you downloaded from OpenApk. And it is possible that the version from OpenApk is incompatible with the Github version. So download 0.6.61 from OpenApk.

After trying for almost an hour I managed to download the app and I downloaded or updated it from the last link you sent me.Do I do anything else?

**Comment by twistios** [comment]
So it installed successfully? If it works now, then be happy and enjoy.
Else, if it crashes in the app, use settings to enable crash log or copy crash log from context menu (if it does not want to start, this is the only option in this case). Paste the log here.
