### ISSUE TITLE
[Feature]: YT Music?

### ISSUE THREAD

**Issue by TTVScaredAND** [fast4x/RiMusic#4662]
### Description

songs that are blocked by YT

### Suggested Solution

I don't know if the title is understandable, but my idea is that the songs that are blocked by YT (for example "Jordan - Remix (Myke Towers ft. Ryan Castro and Ñengo Flow" or "Calimano - SOMBRA PR ft. PRESSURE"
They can be played through YT Music to avoid removing them from YT itself, I don't know if I understand myself, but my idea would be to change the sources from which the music is taken.

### Alternatives

Use YT Music or Soundcloud (i think) to listen to the music that are blocked by YT

**Comment by fast4x** [comment]
If a music is blocked there's a motivation, so isn't make sense try to listen from other source.
