### ISSUE TITLE
A proper landscape mode player

### ISSUE THREAD

**Issue by HWdriver** [fast4x/RiMusic#4663]
### Description

The current one is squished and awful. And I'd like to have my phone on the desk horizontally and control music 

### Suggested Solution

Have the controls on the side or something and the cover art and lyrics on another side

**Comment by fast4x** [comment]
this is horrible for you?
![Screenshot_2024-11-27-07-54-23-588_it.fast4x.rimusic.debug.jpg](https://github.com/user-attachments/assets/eca7d94b-57e2-4fde-85a5-afed9a25cc02)

**Comment by fast4x** [comment]
Have tried with essential and modern player in settings?

**Comment by HWdriver** [comment]
> Have tried with essential and modern player in settings?

Player type is set to modern

**Comment by fast4x** [comment]
Perfect
