### ISSUE TITLE
Download unsuccessful 

### ISSUE THREAD

**Issue by PrintHelio** [fast4x/RiMusic#4664]
### Version of RiMusic

0.6.61

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on Download music
3. Not downloading 
4. Showing Download Failed

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

It also happened previously, i already faced the download failed problem, but somehow i reinstall the app, clearing data, somehow that solve my issues, though i lost my all music data

**Comment by fast4x** [comment]
Login to ytm in miscellaneous settings

**Comment by knighthat** [comment]
Download is not supported when you're not logged in, unless the song is fully cached

**Comment by twistios** [comment]
> it depend by location...

Seems to be true, I can download also partially cached songs.
