### ISSUE TITLE
Short and concise description of your bug

### ISSUE THREAD

**Issue by Ikerpin** [fast4x/RiMusic#4669]
### Version of RiMusic

0.4version

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens
5. You can't download music 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Algo bueno 

### What more can you tell us? (Optional)

A veces no se podía descargar músicas por el error de di music 

### Logs (Optional)

No puedo iniciar cesión

**Comment by Ikerpin** [comment]
Gracias por arreglar el error

**Comment by Ikerpin** [comment]
Está es la mejor aplicación

**Comment by Ikerpin** [comment]
Para mí fue un error de la aplicación

**Comment by fast4x** [comment]
Install latest version, after installed hold icon  and copy crash log, paste here please

**Comment by knighthat** [comment]
version 0.4? That's as old as dinosaurs 

> Gracias por arreglar el error

is it resolved for you? If yes, please close the thread

**Comment by Donald-Win** [comment]
Short and concise comment.

(LOL. Sorry, tongue in cheek. Take with good humor)
