### ISSUE TITLE
Music controls don't work properly on Modern Controls

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#4670]
### Version of RiMusic

0.6.61 - custom

### Android version

14

### I've done these:

- [ ] Uninstall old build before installing a new one
- [x] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic.
2. Play a song.
3. Listen to it for more than 2 seconds.
4. Press "<<".
5. The previous song is played instead of just restarting the current song.

1. Open RiMusic.
2. Play a song or two.
3. Pause the song.
4. Press "<<".
5. The music just plays back and the "<<" is disabled.

### Submit a video

https://github.com/user-attachments/assets/9358e0a0-eab8-4557-bfbb-685d6b99e02f

### What was your expectation?

When pressing "<<" after 2 or more seconds, it should restart the song. When pressing it before that, it should go to the previous song.

**Comment by aneesh1122** [comment]
In simple terms, the behavior of modern controls previous button is different from that of essential controls.

**Comment by OrangeZXZ** [comment]
> In simple terms, the behavior of modern controls previous button is different from that of essential controls.

Exactely

**Comment by knighthat** [comment]
I think the timer is 3 seconds. And not 3 seconds of the song, 3 seconds of listening time

**Comment by aneesh1122** [comment]
> I think the timer is 3 seconds. And not 3 seconds of the song, 3 seconds of listening time

we are just overcomplicating things.

using essential controls : If you press the previous button the current song will start from the beginning. if you've listened to the song for under 3 seconds and press the previous song button the previous song will be played.

using modern controls : no matter what you do, if you press the previous button it will always start the previous song. if you are listening to the first song in the queue and press the previous button, it will do nothing.

**Comment by OrangeZXZ** [comment]
> > I think the timer is 3 seconds. And not 3 seconds of the song, 3 seconds of listening time
> 
> we are just overcomplicating things.
> 
> using essential controls : If you press the previous button the current song will start from the beginning. if you've listened to the song for under 3 seconds and press the previous song button the previous song will be played.
> 
> using modern controls : no matter what you do, if you press the previous button it will always start the previous song. if you are listening to the first song in the queue and press the previous button, it will do nothing.

Then the modern one will not have the "start from the beginning"?
Because this is the only thing missing and i tought it was a bug.

**Comment by aneesh1122** [comment]
> > > I think the timer is 3 seconds. And not 3 seconds of the song, 3 seconds of listening time
> > 
> > we are just overcomplicating things.
> > 
> > using essential controls : If you press the previous button the current song will start from the beginning. if you've listened to the song for under 3 seconds and press the previous song button the previous song will be played.
> > 
> > using modern controls : no matter what you do, if you press the previous button it will always start the previous song. if you are listening to the first song in the queue and press the previous button, it will do nothing.
> 
> Then the modern one will not have the "start from the beginning"?
> Because this is the only thing missing and i tought it was a bug.

When did I say it's not a bug.

I just wanted to clear up everything so that there won't be any confusion. The way you've written your bug report is very confusing.

**Comment by OrangeZXZ** [comment]
> I just wanted to clear up everything so that there won't be any confusion. The way you've written your bug report is very confusing.

I see. Sorry about that. I was making it while being crowded in a tramway. 😄

**Comment by knighthat** [comment]
I guess it time to have a wiki or some shit. Things are getting way more complex and it'd be great to have some document to rely on

**Comment by OrangeZXZ** [comment]
> Song restart only within in first 3 seconds of listening, after it goes to the previous.
> When button << is disabled, please take a look in queue... example song is a first in list when << is disabled...?

Yes, it is first. (So maybe this is normal.)

**Comment by OrangeZXZ** [comment]
> I personally think this duration should be 10 seconds or let the user decide the duration.

I feel the same way.

**Comment by fast4x** [comment]
Consider that 3 seconds is predefined player, I'll look for customize it.
RiMusic will go into space with all the available setting options. ahahahah

**Comment by aneesh1122** [comment]
> Consider that 3 seconds is predefined player, I'll look for customize it.
> RiMusic will go into space with all the available setting options. ahahahah

I've implemented it already 😎

**Comment by fast4x** [comment]
> > Consider that 3 seconds is predefined player, I'll look for customize it.
> > RiMusic will go into space with all the available setting options. ahahahah
> 
> I've implemented it already 😎
> 

oh shit, where i don't remember...

**Comment by aneesh1122** [comment]
> > > Consider that 3 seconds is predefined player, I'll look for customize it.
> > > RiMusic will go into space with all the available setting options. ahahahah
> > 
> > I've implemented it already 😎
> > 
> 
> oh shit, where i don't remember...

I haven't done the pull request. I was looking for bugs. I think it's fine now.

**Comment by OrangeZXZ** [comment]
> I need a tester 😂

I don't mind using a custom version to test
