### ISSUE TITLE
Better 3 dots idle

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#4671]
### Description

While testing the 0.6.61 custom version, I noticed these three dots reacting to the music.

My friend said that it would be better if the three values went to 0 or a default value when paused. That way, they wouldn't have random sizes, and it would look better.

![IMG_20241127_175742_610](https://github.com/user-attachments/assets/7fef8fd3-578c-48bf-a44b-2e2dafa21b5c)

### Suggested Solution

Make the three dots values go to 0 or a default value when paused. That way, they don't have random sizes, and it looks better.

**Comment by fast4x** [comment]
Thank to your friend 😂
