### ISSUE TITLE
RiMusic crashes when opening and showing Playlists

### ISSUE THREAD

**Issue by chriskeeble** [fast4x/RiMusic#4672]
### Version of RiMusic

0.6.61

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click button Playlists
3. Boom! Crash happens
4. Open RiMusic again 
5. Crash happens immediately 

### Submit a video

https://github.com/user-attachments/assets/e47d193c-e0e8-48ea-92a0-e9eee3dc80c5

### What was your expectation?

RiMusic would open without crashing.

### What more can you tell us? (Optional)

If I long press the app icon and select songs I can then open RiMusic, but the crash happens if I then press playlists. It then occurs every time I try and open the app (even if I long press and choose to copy but report to clipboard).

2024-11-27T19:10:54.382:	java.lang.NullPointerException: c.getString(index) must not be null
	 h4.e.m(SourceFile:17) 
	 G7.k.b(SourceFile:193) 
	 k4.g.t(SourceFile:208) 
	 k4.g.l(SourceFile:13) 
	 h4.b.a(SourceFile:9) 
	 e4.D.q(SourceFile:7) 
	 k4.d.t(SourceFile:44) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	 java.lang.Thread.run(Thread.java:1012) 

### Logs (Optional)

2024-11-27T19:10:54.382:	java.lang.NullPointerException: c.getString(index) must not be null
	 h4.e.m(SourceFile:17) 
	 G7.k.b(SourceFile:193) 
	 k4.g.t(SourceFile:208) 
	 k4.g.l(SourceFile:13) 
	 h4.b.a(SourceFile:9) 
	 e4.D.q(SourceFile:7) 
	 k4.d.t(SourceFile:44) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	 java.lang.Thread.run(Thread.java:1012) 

2024-11-27 19:10:53:525 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-27 19:10:53:844 DEBUG: c - CheckMonthlyPlaylist false
2024-11-27 19:10:54:163 DEBUG: c - CheckMonthlyPlaylist false
2024-11-27 19:10:54:223 DEBUG: c - CheckMonthlyPlaylist false
2024-11-27 19:10:57:294 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-27 19:10:57:569 DEBUG: c - CheckMonthlyPlaylist false
2024-11-27 19:10:57:811 DEBUG: c - CheckMonthlyPlaylist false
2024-11-27 19:10:57:866 DEBUG: c - CheckMonthlyPlaylist false
2024-11-27 19:17:54:043 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-27 19:17:56:152 DEBUG: c - CheckMonthlyPlaylist false
2024-11-27 19:17:59:785 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs

2024-11-27T19:10:54.382:	java.lang.NullPointerException: c.getString(index) must not be null
	 h4.e.m(SourceFile:17) 
	 G7.k.b(SourceFile:193) 
	 k4.g.t(SourceFile:208) 
	 k4.g.l(SourceFile:13) 
	 h4.b.a(SourceFile:9) 
	 e4.D.q(SourceFile:7) 
	 k4.d.t(SourceFile:44) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	 java.lang.Thread.run(Thread.java:1012) 

2024-11-27T19:10:58.028:	java.lang.NullPointerException: c.getString(index) must not be null
	 h4.e.m(SourceFile:17) 
	 G7.k.b(SourceFile:193) 
	 k4.g.t(SourceFile:208) 
	 k4.g.l(SourceFile:13) 
	 h4.b.a(SourceFile:9) 
	 e4.D.q(SourceFile:7) 
	 k4.d.t(SourceFile:44) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	 java.lang.Thread.run(Thread.java:1012) 

2024-11-27T19:17:56.345:	java.lang.NullPointerException: c.getString(index) must not be null
	 h4.e.m(SourceFile:17) 
	 G7.k.b(SourceFile:193) 
	 k4.g.t(SourceFile:208) 
	 k4.g.l(SourceFile:13) 
	 h4.b.a(SourceFile:9) 
	 e4.D.q(SourceFile:7) 
	 k4.d.t(SourceFile:44) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	 java.lang.Thread.run(Thread.java:1012)

**Comment by fast4x** [comment]
wait for next version maybe it's fixed

**Comment by chriskeeble** [comment]
Thank you, I'll let you know if it resolves.

**Comment by chriskeeble** [comment]
Hi @fast4x - unfortunately this is still not fixed in v0.6.62 which I've just downloaded from GitHub, installed and run - I can still open the app by long hold and pressing Albums, but as soon as I click Playlists it crashes again. If I can help you debug in anyway please let me know? I'm quite technical so feel free to ask me for a copy of the database, etc. if needed.

**Comment by fast4x** [comment]
Hi, yep, send a copy of database, I'll check it directly.

**Comment by chriskeeble** [comment]
Thanks. DB attached.

**Comment by chriskeeble** [comment]
[rimusic_20241130074906.zip](https://github.com/user-attachments/files/17964885/rimusic_20241130074906.zip)

**Comment by fast4x** [comment]
Your backup is corrupted or not created by RiMusic.

**Comment by chriskeeble** [comment]
Hi Rino,

It is created by RiMusic - but then I zipped it.

Here is the original (unzipped) file.

**Comment by chriskeeble** [comment]
It is created by RiMusic - it was zipped as you can't upload a .db file to Github.

I've just emailed the .db file to you as well.
