### ISSUE TITLE
App crashes when long pressing on song in library

### ISSUE THREAD

**Issue by Cam42exe** [fast4x/RiMusic#4676]
### Version of RiMusic

0.6.61

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Long press on a song in your library (works with and without showing all)
4. Boom! Crash happens (sometimes, normally works a couple of times before the first crash after reboot. After that pretty much all the time.)

### Submit a video

File Size unfortunately too large. However, I have it uploaded to YouTube: (https://youtu.be/DqhKPnYuHR8?si=lOcgLppiAFSi9R8Q)

### What was your expectation?

Probably shouldn't crash, so I don't have to force close through task manager.

### What more can you tell us? (Optional)

I have around 2200 Songs in my library, maybe a problem?

### Logs (Optional)

2024-11-28 06:42:04:422 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-28 06:42:04:774 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue
2024-11-28 06:42:15:992 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-11-28 06:42:16:355 DEBUG: H - PlayerServiceModern QueuePersistentEnabled Saved queue

**Comment by fast4x** [comment]
Hi, please copy crash log here

**Comment by Cam42exe** [comment]
There is none, the app didn‘t realize it crashed.

**Comment by fast4x** [comment]
Try this, enable debug in miscellaneous settings. Cause crash, after that go in miscellaneous and tap on crash log...

**Comment by fast4x** [comment]
Wait new version next friday

**Comment by Cam42exe** [comment]
Did it already. And tried it multiple times. I always get there is no error protocol (freely transcribed from German) in this blue purple-ish color.Am 28.11.2024 13:50 schrieb Rino Russo ***@***.***>:
Try this, enable debug in miscellaneous settings. Cause crash, after that go in miscellaneous and tap on crash log...

**Comment by Cam42exe** [comment]
Ok, hopefully it works.
> Wait new version next friday

**Comment by Cam42exe** [comment]
It still persists, even after updating to two new versions.

**Comment by fast4x** [comment]
Not crash in your case but freeze... 
When open menu what click?

**Comment by Cam42exe** [comment]
Same as the Main Post. And with the new update a couple hours ago, I get placed right at the top of the library instead of staying at the position.
