### ISSUE TITLE
Some playlists in mood & genre section in the "discover" section keeps loading

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#468]
### Steps to reproduce the bug

Go to "discover" 

Some of the mood & genres keep loading 

### Expected behavior

It should load the playlist

### Actual behavior

it keeps loading the playlist

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/127825700/130a42f3-5678-4f0b-846c-63b213da9051

### RiMusic version

v0.6.18

### Android version

android 11

**Comment by fast4x** [comment]
Hello, it also happens if you search for the playlist, it does not depend on RiMusic unfortunately. We tried to figure out the reason and tried to fix it, but so far it doesn’t look like a bug.
