### ISSUE TITLE
[Feature]: Viewing playlists on Android Auto

### ISSUE THREAD

**Issue by Mickael81** [fast4x/RiMusic#4681]
### Description

Hello,
On my smartphone, I put a photo for the different artist playlists that I created.
I noticed that on Android Auto, the display is only available in list mode.
It would have been interesting to display these playlists in grid mode like on the mobile.
A grid mode display with a photo would surely be more pleasant.
I hope you can improve this feature on a future version.

### Suggested Solution

Playlist display should be customized (grid mode or list mode)

**Comment by fast4x** [comment]
Unfortunately Android Auto not permit to list in grid mode, so isn't possible sorry.

**Comment by Mickael81** [comment]
Too bad. Thanks for your feedback.
