### ISSUE TITLE
El reproductor presenta fallas en la reproducción y colores del temas presentan errores.

### ISSUE THREAD

**Issue by Alaneeedu** [fast4x/RiMusic#4684]
### Version of RiMusic

0.6.61

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abre Ri Music.
2. Presenta errores en la reproducción en curso .
3. Cada que se realiza el cambio de alguna canción desde la barra de notificaciones, pantalla de bloqueo, reproducción de un álbum o cola de reproducción se repiten las canciones sin alguna razón.

### Submit a video

Uploading VID-20241128-WA0014.mp4…

### What was your expectation?

Las canciones continuaran sin repetirse cada tres canciones al realizar cambios

### What more can you tell us? (Optional)

N/A

### Logs (Optional)

N/A

**Comment by Alaneeedu** [comment]
Uploading VID-20241128-WA0014.mp4…

**Comment by Alaneeedu** [comment]
Uploading VID-20241128-WA0014.mp4…

**Comment by Alaneeedu** [comment]
Los colores de los temas presentan errores continuamente, cada que se realiza un cambio de canción los colores de la portada anterior se quedan, es decir, si una portada es color azul y el siguiente tema tiene la portada de color rojo, se queda el color azul en el tema, deberían trabajar mucho los temas ya que han estado presentando muchos problemas.

**Comment by fast4x** [comment]
Video not show
