### ISSUE TITLE
Screens/Modes/Menus can not be navigated to directly

### ISSUE THREAD

**Issue by ManDay** [fast4x/RiMusic#4687]
### Version of RiMusic

0.6.61

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

As an example: If you open Search, search, and edit your search subsequently, you are in "Search mode" and no longer on your home screen. Now assume you want to return to the RiMusic home screen:

Pressing the "Arrow Left"/"Back" button will step you backwards through the history of what you have searched and only in the last step return you to the home screen. There is no immediate way to navigate to the home screen.

The lack of direct navigation seems to be a general issue with the app which makes it hard to use. I think that as a rule of thumb, every non-transient screen/mode (e.g. not the search prompt itsself, *but* the search results) should be accessible, without "recovering it" from the "back-history".

### What was your expectation?

To be able to navigate to any screen/mode with a clearly defined, short sequence of navigation steps.

**Comment by ManDay** [comment]
I did try that and nothing happend. Since your comment, I've tried this again and after about 5 clicks it returns to the home screen, if I click fast enough. When clicking slower, you get an easter egg... A bit unpredictable and not sufficient in my opinion.

**Comment by twistios** [comment]
https://github.com/user-attachments/assets/1da52607-565b-46fb-bb29-bc158978875b

See the video.

**Comment by ManDay** [comment]
I don't understand what you are trying to illustrate with the video, as you do not seem to adress the situation which I mention.

When I'm somewhere "deep" in the context of a search (in the following video I performed 2 subsequent searches, taking me about 4 modals "deep" in), there is no way to return to the home screen immediately. Tapping or long-tapping the RiMusic banner at the top just spawns a different mini-game easter eggs. I have to press the "back" button repeatedly to return to the home screen. Depending on how "deep" I am in the hirarchy, this can be dozens of times.

https://github.com/user-attachments/assets/edf1baf7-2028-4727-b83a-58056d9c019e
