### ISSUE TITLE
Like button not working properly

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#469]
### Steps to reproduce the bug

Like a song
(it doesnt indicate that the song is liked) 

### Expected behavior

After liking a song, it should indicate that the song is liked 

### Actual behavior

The like button doesnt indicate that the song is liked but the song gets saved in the saved songs list 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/127825700/38fdabe4-93d5-4a46-9e3e-c18cef69f51f

### RiMusic version

v0.6.18

### Android version

android 11

**Comment by fast4x** [comment]
Fixed, available from version 0.6.19
