### ISSUE TITLE
Duplicates in play next and queue highlighting

### ISSUE THREAD

**Issue by curious-liberal** [fast4x/RiMusic#4693]
### Version of RiMusic

0.6.62

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Play any song to start a radio
3. Skip to at least the second song in queue
4. Hold down any song above the current playing song in the queue (usually this means a song that's already been played but playing it isn't part of the criteria)
5. Select "Play next"
6. Bug 1: song is duplicated and inserted below current song as opposed to moved in queue
7. Play the next song
8. Bug2: since you have duplicates of the same song, both are highlighted (see screenshot below)
![Screenshot_20241130-002811](https://github.com/user-attachments/assets/ee03f534-9449-4d5a-a53a-37d026d2e547)

### Submit a video

https://github.com/user-attachments/assets/c57b643d-f2d6-4994-b26d-63988e0eae19

### What was your expectation?

Song moves position in queue to next song

**Comment by fast4x** [comment]
Tried but not reproduced

**Comment by curious-liberal** [comment]
> Tried but not reproduced

Thank you for looking at this, glad to know it's not affecting other devices. I'll close this now
