### ISSUE TITLE
[Feature]: privacy

### ISSUE THREAD

**Issue by Unknow135** [fast4x/RiMusic#4695]
### Description

Please please focus on your privacy like how can you access gallery without even permission please add a feature to ask for a access to gallery and other services first before access them 

### Suggested Solution

So when I opened your app and click on playlist` and clicked on option I came across the option change the thumbnail I thought I should but as soon as click on that it open my gallery and I don't think I remember giving it permission to access my gallery like do you know how big of a privacy concern this is

### Alternatives

Overall you just need to ask for permission such as accessed this access that and even tell user what are you going that permission for it is a simple as that like if you were to ask me first like re music wants to access your gallery allow or deny it.simple yet it shows that you can trust that app and it won't access your information without your permission

### Additional Context

All and all if it was as simple as that but even if you didn't think about please just add it the file please add this feature cause there are way way many people who are genuinely concern about their privacy you might be thinking that it is very easier to just directly access why make it major it's not about making it easier it's about gaining trust please otherwise without that anyone would think that is just some malware app that doesn't respect privacy and all
Thanks for listening
Hope you do it for the community sake

**Comment by lithium-hypercube** [comment]
RiMusic does not access your gallery when you edit a thumbnail, it uses android's photo picker and only has access to the picture you select.

**Comment by aneesh1122** [comment]
![Screenshot_2024-11-30-16-04-57-767_com.google.android.providers.media.module-edit.jpg](https://github.com/user-attachments/assets/a957fadb-fb71-4991-8889-c52f333f8e43)

I miss the times when people knew how to read
