### ISSUE TITLE
Artists Library Tab Not Displaying All Saved Artists in Library

### ISSUE THREAD

**Issue by ErickMontesDK** [fast4x/RiMusic#4696]
### Version of RiMusic

0.6.62

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Enter to Artist Page
3. Select Library Tab
4.There is no change between tabs

### Submit a video

https://github.com/user-attachments/assets/2595cfe5-e0f3-4904-9ac8-04b37aed03d4

### What was your expectation?

Display all the artist saved in my Library

### What more can you tell us? (Optional)

This new feature works perfectly on the Albums screen; the issue only occurs on the Artists screen. Regarding the problem, that would be all.

As an extra note, I want to take a moment to thank and congratulate you for the amazing work you’ve done. It’s truly admirable how consistent and attentive you’ve been with this project, always considering feedback from everyone. RiMusic has become my top music app, even above Spotify.

**Comment by fast4x** [comment]
Ok

**Comment by fast4x** [comment]
Look 
https://github.com/user-attachments/assets/92c00c13-42a8-44b0-86d8-d2196f6357cb

**Comment by aneesh1122** [comment]
> Look 
> https://github.com/user-attachments/assets/92c00c13-42a8-44b0-86d8-d2196f6357cb
> 
> 

I also have this problem. Should I send you my database file?

**Comment by aneesh1122** [comment]
> ### Version of RiMusic
> 
> 0.6.62
> 
> ### Android version
> 
> 12
> 
> ### I've done these:
> 
> - [X] Uninstall old build before installing a new one
> - [X] Checked opening issues about my similar problem
> 
> ### Tell us how you trigger this bug
> 
> 1. Open RiMusic
> 2. Enter to Artist Page
> 3. Select Library Tab
> 4.There is no change between tabs
> 
> 
> 
> ### Submit a video
> 
> 
> https://github.com/user-attachments/assets/2595cfe5-e0f3-4904-9ac8-04b37aed03d4
> 
> 
> 
> ### What was your expectation?
> 
> Display all the artist saved in my Library
> 
> ### What more can you tell us? (Optional)
> 
> This new feature works perfectly on the Albums screen; the issue only occurs on the Artists screen. Regarding the problem, that would be all.
> 
> As an extra note, I want to take a moment to thank and congratulate you for the amazing work you’ve done. It’s truly admirable how consistent and attentive you’ve been with this project, always considering feedback from everyone. RiMusic has become my top music app, even above Spotify.
> 
> ### Logs (Optional)
> 
> _No response_

It only works when you change the sorting option to 'Artist'

**Comment by fast4x** [comment]
wow nice indication

**Comment by aneesh1122** [comment]
> wow nice indication 

If it's not possible to show all the library artists when sorting option is 'Date Added' then I think 'Library' tab should be hidden when 'Date Added' sorting is selected.

**Comment by fast4x** [comment]
I'll try

**Comment by twistios** [comment]
I guess that it can also be fixed via the sql querry.

**Comment by twistios** [comment]
Maybe I found the solution already.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.63

**Comment by twistios** [comment]
@fast4x As mentioned in my draft pull request #4711, this fix only solves the problem of the missing artists but not that the sorting is broken with this sorting method.
