### ISSUE TITLE
Lag on songs list and taps not responding on said list 

### ISSUE THREAD

**Issue by NOBELLIST** [fast4x/RiMusic#4699]
### Version of RiMusic

Latest 0.6.62

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open rimusic
2. Songs list lags and take 10 to 15 fps off
3. Some if not all songs are unclickable and randomly get clicked
4. Feel my phone heat up for no reason 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

A stable 60 fps on my old redmi phone like before, and the ability to click songs 

### What more can you tell us? (Optional)

The lag appears to be becuase i have like 600 songs on my songs list. Last build 0.6.61 didnt have any issues.

**Comment by fast4x** [comment]
Improved now playing indicator, maybe is the cause of lag, available from version 0.6.63

**Comment by NOBELLIST** [comment]
ITS THE ALBUM COVER I REPEAT IS THE ALBUM COVER THAT LAGS

**Comment by NOBELLIST** [comment]
i only realized cus i was off line and the list is at full 60 fps
