### ISSUE TITLE
Playlist can't be imported. App closes when CSV file is selected.

### ISSUE THREAD

**Issue by MathanJoseph** [fast4x/RiMusic#4701]
### Version of RiMusic

0.6.61

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on Playlist 
3. Click on import playlist
4. Select CSV file
5. Crash happens

### Submit a video

https://github.com/user-attachments/assets/3cee1e9a-4fa2-4cfb-a5c2-40d12d2cf078

### What was your expectation?

For my playlist to be imported.

### Logs (Optional)

2024-11-30T14:18:15.838:	java.lang.NullPointerException
	 l8.I.l(SourceFile:129) 
	 B8.p0.c(SourceFile:86) 
	 G7.i.run(SourceFile:1247) 
	 G7.i.run(SourceFile:92) 
	 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	 java.lang.Thread.run(Thread.java:1012)

**Comment by aneesh1122** [comment]
Post your crash log. What you've posted is the normal log.

**Comment by fast4x** [comment]
Attach playlist file here please

**Comment by MathanJoseph** [comment]
[patt.csv](https://github.com/user-attachments/files/17967168/patt.csv)

**Comment by MathanJoseph** [comment]
> Attach playlist file here please
[patt.csv](https://github.com/user-attachments/files/17967171/patt.csv)

Playlist file

**Comment by fast4x** [comment]
File is totally incompatible, you can import file format specific
Look file format here
https://github.com/fast4x/RiMusic/wiki/FAQs#what-is-the-csv-file-structure-for-importing-a-playlist-in-library

**Comment by MathanJoseph** [comment]
> File is totally incompatible, you can import file format specific Look file format here https://github.com/fast4x/RiMusic/wiki/FAQs#what-is-the-csv-file-structure-for-importing-a-playlist-in-library

Ok thank you
