### ISSUE TITLE
Cannot add music and Sync to the playlists of YouTube Music from RiMusic

### ISSUE THREAD

**Issue by rajinstar** [fast4x/RiMusic#4702]
### Version of RiMusic

0.6.62

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on Playlist Option
3. Go to any playlist that add from YouTube Music through Link
4. Add any song to that playlist. 
5. Boom, songs that I add to the playlists does not sync and add to the YouTube Music's Playlist.

### What was your expectation?

I expect that when I add any songs using RiMusic through my playlist that I add from YouTube Music through a link, it will automatically sync to YouTube Music, just like when I add any songs to the playlists from YouTube Music, then it will automatically add to RiMusic. I just want these features so that I can add songs to the playlists using RiMusic to YouTube Music.

**Comment by aneesh1122** [comment]
Who said you can? Where is it written that you can sync your YouTube playlists from RiMusic?

**Comment by rajinstar** [comment]
@aneesh1122, You can add playlists from YT Music by copying the link from YT Music and add that link to RiMusic and import the playlists. Then when I add music to the YouTube Music playlist then it will automatically be available in the RiMusic. I just want to add any music to the playlists in RiMusic and sync it to YT Music. So that I can switch between my Laptop and Phone for listening music.

**Comment by aneesh1122** [comment]
> @aneesh1122, You can add playlists from YT Music by copying the link from YT Music and add that link to RiMusic and import the playlists. Then when I add music to the YouTube Music playlist then it will automatically be available in the RiMusic. I just want to add any music to the playlists in RiMusic and sync it to YT Music. So that I can switch between my Laptop and Phone for listening music.

I'm asking you again. Where is it written that you can use RiMusic to sync your YouTube playlists? You can only import playlists from yt.

You can't just think of something and assume that it's possible in RiMusic. Use some common sense.

**Comment by rajinstar** [comment]
My mistake 😔. Sorry. But can't you add these features to RiMusic. 🥺
