### ISSUE TITLE
Error opening "my top 20" if "Exclude song with duraton limit" is enabled

### ISSUE THREAD

**Issue by Figim** [fast4x/RiMusic#4704]
### Version of RiMusic

0.6.62

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Finally listen to 1 song
3. Set the "Exclude song with duraton limit" option to any value
4. Click on the My Top 20 page👇
5. Boom! Crash happens

**_

> I'm sorry!
> 
> This is the real reason for the error

_**

### Submit a video

https://github.com/user-attachments/assets/4e33ec28-8a31-40f3-ab9e-244412ef0872

### What was your expectation?

If the "Exclude song with duraton limit" option is enabled, when opening "my top 20", the application does not crash and the page opens

### What more can you tell us? (Optional)

2024-11-30T10:13:14.928:	java.lang.NullPointerException
	 B8.I.a(SourceFile:324) 
	 l8.U.t(SourceFile:35) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 l9.a.run(SourceFile:127) 

2024-11-30T10:13:17.318:	java.lang.NullPointerException
	 B8.I.a(SourceFile:324) 
	 l8.U.t(SourceFile:35) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 l9.a.run(SourceFile:127) 

2024-11-30T10:13:20.309:	java.lang.NullPointerException
	 B8.I.a(SourceFile:324) 
	 l8.U.t(SourceFile:35) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 l9.a.run(SourceFile:127) 

2024-11-30T10:13:42.245:	java.lang.NullPointerException
	 B8.I.a(SourceFile:324) 
	 l8.U.t(SourceFile:35) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 l9.a.run(SourceFile:127) 

2024-11-30T10:13:47.285:	java.lang.NullPointerException
	 B8.I.a(SourceFile:324) 
	 l8.U.t(SourceFile:35) 
	 I8.a.k(SourceFile:9) 
	 d9.L.run(SourceFile:107) 
	 l9.a.run(SourceFile:127) 

### Logs (Optional)

No

**Comment by knighthat** [comment]
Still can't reproduce it

**Comment by fast4x** [comment]
file zip not valid

**Comment by fast4x** [comment]
ah ok thanks
