### ISSUE TITLE
Bug in the updated version 0.6.62 

### ISSUE THREAD

**Issue by BXSIL77** [fast4x/RiMusic#4707]
### Version of RiMusic

0.6.62

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on playlist 
3. Open playlist 
4. Boom! Crash happens there like it will star blinking 
5. After that when we take music or song option there will no songs even if we listened many songs 

### Submit a video

Situation 

https://github.com/user-attachments/assets/674b24a0-35ad-41a8-b0f6-8c23fd3eeca0

### What was your expectation?

I love this application but i hope you can find a solution on this 

### What more can you tell us? (Optional)

I hope if we turn off the storage of download we can also remove the symbol of downloading from the app as a part of customisation.
![IMG_20241130_190352_804](https://github.com/user-attachments/assets/70070d5b-f704-4871-904d-2b668505da65)

**Comment by Wander42** [comment]
so ik i dont have the answer for this but ive been having a problem getting to settings as it doesnt appear anymore on my screen, do you mind showing me how to get to them now? i heard its something like scrolling on the side bar or something like this attached vid.

https://github.com/user-attachments/assets/1a1d1f53-6317-479a-95da-bcedc4798192

**Comment by BXSIL77** [comment]
U need to clear the data and take again from first then only it will come
back there is no any another option i have tried it.

It is gone from side because there is an option in settings to remove
settings symbol from there, but there is no any other option after that.

**Comment by fast4x** [comment]
Send crash log please

**Comment by Wander42** [comment]
> U need to clear the data and take again from first then only it will come back there is no any another option i have tried it. It is gone from side because there is an option in settings to remove settings symbol from there, but there is no any other option after that. >

thanks for that man, hope your issue gets resolved too!
