### ISSUE TITLE
Infinite radio mode 

### ISSUE THREAD

**Issue by ghost** [fast4x/RiMusic#472]
### Description

If the user starts a radio mode with X tracks. The playlist created by Youtube with radio mode has a certain number of tracks, it is not an infinite playlist. So my idea is that once all the tracks in the playlist the user has created with radio mode have been listened to, another radio mode is automatically started with the last track played from the playlist and that the new playlist is merged with the old playlist and the tracks are simply appended to the end of the playlist to give the user a sense of continuity without any user interaction required.

### Suggested Solution

*

**Comment by fast4x** [comment]
Hi, interesting idea

**Comment by siggi1984** [comment]
> ### Description
> 
> If the user starts a radio mode with X tracks. The playlist created by Youtube with radio mode has a certain number of tracks, it is not an infinite playlist. So my idea is that once all the tracks in the playlist the user has created with radio mode have been listened to, another radio mode is automatically started with the last track played from the playlist and that the new playlist is merged with the old playlist and the tracks are simply appended to the end of the playlist to give the user a sense of continuity without any user interaction required.
> ### Suggested Solution
> 
> 
> ### Alternatives
> 
> _No response_
> ### Additional Context
> 
> _No response_

That sounds interesting, an infinite radio, cool.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.47
