### ISSUE TITLE
The error still persists that the configuration button does not appear in the side navigation bar

### ISSUE THREAD

**Issue by EliasNavaXD** [fast4x/RiMusic#4721]
### Version of RiMusic

0.6.62

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
The settings button does not appear in the navigation bar and nowhere
![1733004661641](https://github.com/user-attachments/assets/365bc25b-3bdd-466a-83b4-f52ea84941e7)

### Submit a video

https://github.com/user-attachments/assets/8ea12856-e713-4b72-a796-6326f461872b

### What was your expectation?

that the configuration button appears normally

### What more can you tell us? (Optional)

This problem has been appearing to me since version 0.60 until the recent version that I already downloaded. I thought they were going to solve it but the problem persists. Days before I reported this error and they just told me to scroll in the navigation bar, I tried it and it didn't work, now I can't do any configuration.

**Comment by fast4x** [comment]
Swipe up vertical navigation bar

**Comment by EliasNavaXD** [comment]
> Desliza hacia arriba la barra de navegación vertical


https://github.com/user-attachments/assets/e23ffa06-1f6c-4921-b399-646f5b87869b

**Comment by EliasNavaXD** [comment]
> > Desliza hacia arriba la barra de navegación vertical
> 
>  Grabación de pantalla 20241130 173707.mp4

not working

**Comment by Vic931** [comment]
The same thing happens to me, I've been with this problem for several weeks, I thought it was the only one.
I hope they solve it soon

https://github.com/user-attachments/assets/ca5c3560-4ed5-492a-b485-30c3b15083bf

**Comment by EliasNavaXD** [comment]
> A mi me pasa lo mismo, llevo varias semanas con este problema, pensé que era el único. Espero que lo solucionen pronto
> 
>  SVID_20241130_173058_1.mp4

and I thought I was the only one

**Comment by Milton86cmd** [comment]
I just downloaded the latest version to see if the error was solved but the configuration button still does not appear, I thought it was the only one
![Screenshot_20241130_205338](https://github.com/user-attachments/assets/2dd3eb25-74f1-4f19-b6e2-cb723afa3112)

**Comment by fast4x** [comment]
swipe up navigation bar

**Comment by EliasNavaXD** [comment]
they closed the issue🫤

**Comment by Vic931** [comment]
We have to wait for an upcoming update to see if they really fixed it. We can't do anything else 😐

**Comment by EliasNavaXD** [comment]
> We have to wait for an upcoming update to see if they really fixed it. We can't do anything else 😐

There is a possible way to solve the error, I was downloading the developer version of the app and that was when the configuration button appeared by sliding down in the navigation bar, but I don't know if it is stable because when changing the transition animations the settings button disappeared again and when I tried to swipe down on the navigation bar it didn't appear anymore, it's not very stable but it can help a little although I'm not very happy that they didn't fix a simple bug.
I already have 3 versions waiting for the error to be solved.

**Comment by fast4x** [comment]
Good indication thanks

**Comment by d-pv** [comment]
Same here. Furthermore, I have the nav bar as horizontal (I think it's vimusic style), but since settings do not appear, I cannot change the navbar...
@fast4x, indications of swiping the navbar does not help (neither in @Vic931 video, neither in my case, swiping Left-right).

It is possibly **related to the Spanish language!!**, since the three of have the app in spanish.
Will try to change the phone language to see if it helps and post the reply.

**Comment by d-pv** [comment]
Nah, changed the Phone language settings to English US and settings not showing yet...
