### ISSUE TITLE
Al querer borrar una canción descargada se crashea. 

### ISSUE THREAD

**Issue by Willy2222** [fast4x/RiMusic#4722]
### Version of RiMusic

0.6.62

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abra RiMusic
2. Ir a canciones descargadas 
3. Click en el icono borrar. 
4. Se cierra la aplicación. 

### What was your expectation?

Que se borre y no se cierre

**Comment by fast4x** [comment]
clean data from settings

**Comment by fast4x** [comment]
Fixed, available from version 0.6.62.1
