### ISSUE TITLE
Cuando descargo se me sale la app

### ISSUE THREAD

**Issue by Jonathanx3** [fast4x/RiMusic#4724]
### Version of RiMusic

O.6.62

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

https://github.com/user-attachments/assets/00e348b6-0411-4777-ad12-612265ab2bb6

### What was your expectation?

Hice click en descargar todo lo del álbum y se cerró la app lo mismo pasa si descargo 3 canciones separadas

**Comment by fast4x** [comment]
enable debug and send crash log

**Comment by fast4x** [comment]
Fixed, available from version 0.6.62.1
