### ISSUE TITLE
Samsung does not display song covers as lock screen wallpaper

### ISSUE THREAD

**Issue by Figim** [fast4x/RiMusic#4731]
### Version of RiMusic

0.6.62

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic in Samsung. Maybe android 12
2.  Settings, Appearance 
3. Turn on the song cover
4. Lock the screen
5. You can see the samsung wallpaper, not the song cover

### Submit a video

https://github.com/user-attachments/assets/29b321da-1bc8-4307-96f5-0ba5b30c6064

### What was your expectation?

Show song cover when Samsung locks the screen

### What more can you tell us? (Optional)

I don't know

### Logs (Optional)

No

**Comment by OrangeZXZ** [comment]
Do you have another app that successfully does the same thing?

Because I have a Samsung, and normally this feature is not compatible with it.

**Comment by OrangeZXZ** [comment]
> > Do you have another app that successfully does the same thing?
> > 
> > Because I have a Samsung, and normally this feature is not compatible with it.
> 
> Solution found for Samsung:
> App: https://play.google.com/store/apps/details?id=com.lstapps.musiclivewallpaper
> 
> **What does the app do?**
> 
> 1. **You grant "Custom Notification Permission" to the app on the device". However, RiMusic does not support this**
> 
> 2. **The App then allows you to change the default wallpaper using Samsung's "Live Wallpaper" system app.** (Usually like a wallpaper app)
> 
> ![Screenshot_20241206-181612_Settings](https://github.com/user-attachments/assets/a399674f-f61d-4632-b638-19d66118ef19)
> 
> 
> 
> 3. **Then you open the following option** 
> 
> ![Screenshot_20241206-182332_Music Live Wallpaper](https://github.com/user-attachments/assets/9b2845e6-5b92-49fc-b77a-6bc772d1deaa)
> 
> **If RiMusic does these three functions, this feature will work on Samsung**😊. **Note**: This app is not dependent on the feature you added
> 
> Video: Soon this application will change your wallpaper live
> 
> https://github.com/user-attachments/assets/249d086f-9510-4fc9-a5ec-aebb61032752
> 
> 
> https://github.com/user-attachments/assets/7a9a453b-5189-4e88-bb11-c98b8d9fa26e
> 
> 
> 
> ![Screenshot_20241206-184908_Permission controller](https://github.com/user-attachments/assets/cbb87897-74e5-493e-b65b-5892506afe80)
> 
> 
> 

It was announced on the Telegram group that today's update normally adds this feature.

**Comment by OrangeZXZ** [comment]
> Will it be fixed in the next version?

Maybe

**Comment by fast4x** [comment]
in previous yes?

**Comment by fast4x** [comment]
you mean in 0.6.63?

**Comment by fast4x** [comment]
Ok, I'll add notification compatibility module, so you can switch. 
Can you try a custom version and send feedback? When ready I'll inform you.

**Comment by fast4x** [comment]
Ready, try this custom version, in ui settings there is a notification Type, set to advanced, restart app.
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by fast4x** [comment]
with advanced notification type?
