### ISSUE TITLE
App se cierra al intentar descargar 

### ISSUE THREAD

**Issue by Nisselle** [fast4x/RiMusic#4735]
### Version of RiMusic

0.6.62

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abri RiMusic
2. Hice click en descargar canción 
3. Se cerró al instante luego de dar click en descargar 

### Submit a video

Si está en Android, descarga una grabadora de pantalla y grabe su pantalla mientras
duplicar el problema como se describe anteriormente.

> Es posible que necesites usar la aplicación Github para poder cargar videos; el límite de tamaño es de 10 MB.

Si está en el escritorio, arrastre el video a este cuadro y se cargará automáticamente

https://github.com/user-attachments/assets/65ef3e29-482a-4c49-83eb-b41bbb1ba895

### What was your expectation?

Esperaba que al hacer click en descargar se descargara sin problema alguno 

### What more can you tell us? (Optional)

Intente descargar varias canciones y con todas me pasa el mismo error

### Logs (Optional)

2024-12-01T03:46:01.528:	java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
	 e4.C.a(SourceFile:30) 
	 d4.Z.i3(SourceFile:6) 
	 G7.I.y1(SourceFile:15) 
	 G7.c.y1(SourceFile:8) 
	 l8.b0.b(SourceFile:155) 
	 C9.z.b(SourceFile:365) 
	 Y3.V.a(SourceFile:118) 
	 z.S0.t(SourceFile:131) 
	 I8.a.k(SourceFile:9) 
	 d9.E.D(SourceFile:81) 
	 d9.l.r(SourceFile:101) 
	 d9.l.E(SourceFile:33) 
	 d9.l.k(SourceFile:17) 
	 D0.K.y0(SourceFile:51) 
	 D0.K.L(SourceFile:32) 
	 x.j.L(SourceFile:111) 
	 D0.h.h(SourceFile:157) 
	 D0.h.h(SourceFile:136) 
	 D0.h.h(SourceFile:136) 
	 D0.h.h(SourceFile:136) 
	 D0.h.h(SourceFile:136) 
	 D0.h.h(SourceFile:136) 
	 W3.c0.s(SourceFile:36) 
	 D0.x.n(SourceFile:141) 
	 K0.v.K(SourceFile:83) 
	 K0.v.l(SourceFile:383) 
	 K0.v.dispatchTouchEvent(SourceFile:76) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844) 
	 com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488) 
	 com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871) 
	 android.app.Activity.dispatchTouchEvent(Activity.java:4175) 
	 k.v.dispatchTouchEvent(SourceFile:3) 
	 com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446) 
	 android.view.View.dispatchPointerEvent(View.java:14617) 
	 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6324) 
	 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6118) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5605) 
	 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5662) 
	 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5628) 
	 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5780) 
	 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5636) 
	 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5837) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5609) 
	 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5662) 
	 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5628) 
	 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5636) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5609) 
	 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8469) 
	 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8420) 
	 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8367) 
	 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8604) 
	 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220) 
	 android.os.MessageQueue.nativePollOnce(Native Method) 
	 android.os.MessageQueue.next(MessageQueue.java:335) 
	 android.os.Looper.loop(Looper.java:222) 
	 android.app.ActivityThread.main(ActivityThread.java:8019) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) 

2024-12-01T03:46:04.252:	java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
	 e4.C.a(SourceFile:30) 
	 d4.Z.i3(SourceFile:6) 
	 G7.I.y1(SourceFile:15) 
	 G7.c.y1(SourceFile:8) 
	 l8.b0.b(SourceFile:155) 
	 C9.z.b(SourceFile:365) 
	 Y3.V.a(SourceFile:118) 
	 z.S0.t(SourceFile:131) 
	 I8.a.k(SourceFile:9) 
	 d9.E.D(SourceFile:81) 
	 d9.l.r(SourceFile:101) 
	 d9.l.E(SourceFile:33) 
	 d9.l.k(SourceFile:17) 
	 D0.K.y0(SourceFile:51) 
	 D0.K.L(SourceFile:32) 
	 x.j.L(SourceFile:111) 
	 D0.h.h(SourceFile:157) 
	 D0.h.h(SourceFile:136) 
	 D0.h.h(SourceFile:136) 
	 D0.h.h(SourceFile:136) 
	 D0.h.h(SourceFile:136) 
	 D0.h.h(SourceFile:136) 
	 W3.c0.s(SourceFile:36) 
	 D0.x.n(SourceFile:141) 
	 K0.v.K(SourceFile:83) 
	 K0.v.l(SourceFile:383) 
	 K0.v.dispatchTouchEvent(SourceFile:76) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844) 
	 com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488) 
	 com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871) 
	 android.app.Activity.dispatchTouchEvent(Activity.java:4175) 
	 k.v.dispatchTouchEvent(SourceFile:3) 
	 com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446) 
	 android.view.View.dispatchPointerEvent(View.java:14617) 
	 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6324) 
	 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6118) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5605) 
	 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5662) 
	 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5628) 
	 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5780) 
	 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5636) 
	 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5837) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5609) 
	 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5662) 
	 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5628) 
	 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5636) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5609) 
	 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8469) 
	 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8420) 
	 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8367) 
	 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8604) 
	 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220) 
	 android.os.MessageQueue.nativePollOnce(Native Method) 
	 android.os.MessageQueue.next(MessageQueue.java:335) 
	 android.os.Looper.loop(Looper.java:222) 
	 android.app.ActivityThread.main(ActivityThread.java:8019) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.62.1
