### ISSUE TITLE
L' app si chiude quando cerco di scaricare le canzoni

### ISSUE THREAD

**Issue by LoryGH** [fast4x/RiMusic#4737]
### Version of RiMusic

0.6.62

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Per scaricare la musica della playlist va direttamente in crash

### Submit a video

https://github.com/user-attachments/assets/9d73980a-eb35-449a-9343-2aebcc09eff0

### What was your expectation?

Ho cliccato su scarica e poi l'app si chiude

**Comment by fast4x** [comment]
Fixed, available from version 0.6.62.1

**Comment by LoryGH** [comment]
È già uscita la versione senza il bug?

**Comment by fast4x** [comment]
Ciao non ancora, uscirà stasera cerco di risolvere qualche altro bug importante e poi faccio il rilascio della nuova versione intermedia.

**Comment by LoryGH** [comment]
Ok, grazie
