### ISSUE TITLE
Can't download (It closes)

### ISSUE THREAD

**Issue by Jabwss** [fast4x/RiMusic#4738]
### Version of RiMusic

0.6.62

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

Nothing else you understood 

### What was your expectation?

Nothing else to say

### What more can you tell us? (Optional)

Nothing else

**Comment by fast4x** [comment]
Fixed, available from version 0.6.62.1
