### ISSUE TITLE
Download a playlist bug

### ISSUE THREAD

**Issue by rodas00789** [fast4x/RiMusic#4746]
### Version of RiMusic

0.6.62

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Search a artist
3. Click on a playlist
4. Click on download all songs 
5. Confirm your choise 
6. the app crashes and closes

### What was your expectation?

I want to download an entire playlist

**Comment by fast4x** [comment]
Fixed, available from version 0.6.62.1
