### ISSUE TITLE
Thumbnail on CDs

### ISSUE THREAD

**Issue by HWdriver** [fast4x/RiMusic#4749]
### Description

I think putting the thumbnail on the CD would look nice. 

### Suggested Solution

Just like the thumbnail is on the vinyl you can have it on the cd
![eminem-the-eminem-show-cd-dvd-02-original-pressing-used-950649](https://github.com/user-attachments/assets/310aa263-791a-4e1a-a2c0-5f245bceb7a6)
Just like the photo

**Comment by Maguz0** [comment]
I like 💡 the question Is ITS POSIBLE?

**Comment by fast4x** [comment]
Implemented, available from version 0.6.63

**Comment by HWdriver** [comment]
> Implemented, available from version 0.6.63

When will it release?

**Comment by fast4x** [comment]
Next friday

**Comment by HWdriver** [comment]
> Next friday

So today? Or 1 week? 
It can go both ways

**Comment by twistios** [comment]
It will be today or this weekend.
