### ISSUE TITLE
Merge all "New Crowdin updates in #..."  into one string in release changelog

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#475]
### Description

Current behaviour
- New Crowdin updates in #...
- New Crowdin updates in #...
- New Crowdin updates in #...
- ...
- ..

### Suggested Solution

Merge into 1 string, so it doesnt spam new line/dots in release changelog
- New Crowdin updates in #... #... #... ...

### Alternatives

Idk if crowdin support this
New translation PR to track commits, similar to how NewPipe handle translation (although they are using weblate)

**Comment by fast4x** [comment]
Done
