### ISSUE TITLE
Lag! 

### ISSUE THREAD

**Issue by NOBELLIST** [fast4x/RiMusic#4750]
### Version of RiMusic

0.6.62.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Check on songs list
3. Lag
4. Click on song
5. Song doesnt open 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Normal 60 fps and songs opening and playing

### What more can you tell us? (Optional)

It seems that the album covers the blame for the lag. When im offline and the album covers and unloaded it seems to work just fine.

**Comment by fast4x** [comment]
Try to increase image cache in settings

**Comment by fast4x** [comment]
Try version 0.6.62.2

**Comment by NOBELLIST** [comment]
Increasing the image cache did help thanks
