### ISSUE TITLE
Crash when scrolling through long lists of songs 

### ISSUE THREAD

**Issue by jksekai** [fast4x/RiMusic#4751]
### Version of RiMusic

0.6.62.1

### Android version

12

### I've done these:

- [x] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. open songs list
3. make sure the list is long enough (700~ in my case) 
4. Boom! Crash happens

### Submit a video

https://github.com/user-attachments/assets/02783ab6-7931-4cf7-8fc6-c951d33c8b63

### What was your expectation?

to be able to scroll lag free and to actually work rather than crashing. 

### What more can you tell us? (Optional)

if the items are around 200, it shouldn't crash, at least in my case

### Logs (Optional)

[Ri music crash long.txt](https://github.com/user-attachments/files/17972763/Ri.music.crash.long.txt)

**Comment by fast4x** [comment]
Attached log not seem to be a crash lo but debug log

**Comment by jksekai** [comment]
> Attached log not seem to be a crash lo but debug log
oop here's it
 ![ri music crash log .txt](https://github.com/user-attachments/files/17975586/ri.music.crash.log.txt)

**Comment by fast4x** [comment]
Try this custom version if crash https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by jksekai** [comment]
> Try this custom version if crash https://github.com/fast4x/RiMusic/tree/master/customVersion

yes now it no longer crashes

**Comment by fast4x** [comment]
Perfect, thanks for feedback
