### ISSUE TITLE
The settings button completely disappears on the ViMusic UI

### ISSUE THREAD

**Issue by Cihcoycyi463** [fast4x/RiMusic#4752]
### Version of RiMusic

0.6.62.1

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Bug Only Occurs when UI is on ViMusic style
1. Open RiMusic
2. Click on the Settings Icon
3. Click on the UI category
4. Turn off the 'Show The Search Button On The Navigation Bar' setting
5. It completely gets rid of the settings icon and there is no way to go back to the settings page

### Submit a video

![Screenshot_20241201-210211~2](https://github.com/user-attachments/assets/88d8e402-4384-4011-b2a2-a71054d68918)
![Screenshot_20241201-210232~2](https://github.com/user-attachments/assets/8d76ea28-e39e-4dfe-bd53-73e4feee07af)
![Screenshot_20241201-210250~2](https://github.com/user-attachments/assets/7156c678-966c-4e0b-a535-33c209372a1f)

### What was your expectation?

I believe when you turn this option off, the setting icon would normally move location.

**Comment by fast4x** [comment]
Download e try this custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by EliasNavaXD** [comment]
> ### Versión de RiMusic
> 0.6.62.1
> 
> ### Versión de Android
> 15
> 
> ### He hecho esto:
> * [x] Desinstale la compilación antigua antes de instalar una nueva
> * [x] Comprobé los problemas de apertura sobre mi problema similar.
> 
> ### Cuéntanos cómo desencadenas este error
> El error solo ocurre cuando la interfaz de usuario está en estilo ViMusic
> 
> 1. Abrir RiMusic
> 2. Haga clic en el icono de Configuración
> 3. Haga clic en la categoría UI
> 4. Desactivar la configuración 'Mostrar el botón de búsqueda en la barra de navegación'
> 5. Elimina por completo el ícono de configuración y no hay forma de volver a la página de configuración.
> 
> ### Enviar un vídeo
> ![Captura de pantalla_20241201-210211~2](https://private-user-images.githubusercontent.com/190327040/391416906-88d8e402-4384-4011-b2a2-a71054d68918.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxOTEwNzYsIm5iZiI6MTczMzE5MDc3NiwicGF0aCI6Ii8xOTAzMjcwNDAvMzkxNDE2OTA2LTg4ZDhlNDAyLTQzODQtNDAxMS1iMmEyLWE3MTA1NGQ2ODkxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMTUyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2I4MmVlYjMyM2MyMzRlOTFiMDE0NjE2NjkyYzZmMzYyZjQxYzQ2MDNhYWE4NTRjMzI2YTZjYzdkYjY0YWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.O7FAwCyfXGICNPio5C-EEW9z1gWmHH9-6qlrx4xD2-s) ![Captura de pantalla_20241201-210232~2](https://private-user-images.githubusercontent.com/190327040/391416907-8d76ea28-e39e-4dfe-bd53-73e4feee07af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxOTEwNzYsIm5iZiI6MTczMzE5MDc3NiwicGF0aCI6Ii8xOTAzMjcwNDAvMzkxNDE2OTA3LThkNzZlYTI4LWUzOWUtNGRmZS1iZDUzLTczZTRmZWVlMDdhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMTUyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmRiYjhlZTIzMmE1YzYxYWI0MDcwNTE0M2YyNDIzZTY2NThlMjZlY2YyMTc4MGUyZTJjM2ZjZjg2ZGZhZDQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ghqQn4onDXSoV3Z3P6I9zlPVISOTR5AborQw5fbPJ5k) ![Captura de pantalla_20241201-210250~2](https://private-user-images.githubusercontent.com/190327040/391416908-7156c678-966c-4e0b-a535-33c209372a1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxOTEwNzYsIm5iZiI6MTczMzE5MDc3NiwicGF0aCI6Ii8xOTAzMjcwNDAvMzkxNDE2OTA4LTcxNTZjNjc4LTk2NmMtNGUwYi1hNTM1LTMzYzIwOTM3MmExZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMTUyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGIxMWIyMTg4YzRlMTNjMDE4NThjYTQ3ZWNhODAyNmI2MGI1NDZhOTQxYjYyOGNmNmU3NTBkZWE5MTgxNDYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.a7iVuUFPDwPCnwX9EpleIDrW-MQcPI0n9uIiysK93l0)
> 
> ### ¿Cuál era tu expectativa?
> Creo que cuando desactivas esta opción, el ícono de configuración normalmente se moverá de ubicación.
> 
> ### ¿Qué más nos puedes contar? (opcional)
> _Sin respuesta_
> 
> ### Registros (opcional)
> _Sin respuesta_

This error has been happening to me for 3 versions and until today I cannot make any configuration

**Comment by EliasNavaXD** [comment]
> Descargue y pruebe esta versión personalizada https://github.com/fast4x/RiMusic/tree/master/customVersion

error 404 appears
![Screenshot_20241202-205712_Chrome](https://github.com/user-attachments/assets/038733eb-e4a0-48bf-b3a1-c280bcde4395)

**Comment by EliasNavaXD** [comment]
> > Descargue y pruebe esta versión personalizada https://github.com/fast4x/RiMusic/tree/master/customVersion
> 
> aparece el error 404 ![Captura de pantalla_20241202-205712_Chrome](https://private-user-images.githubusercontent.com/136876035/391777464-038733eb-e4a0-48bf-b3a1-c280bcde4395.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxOTEzNjIsIm5iZiI6MTczMzE5MTA2MiwicGF0aCI6Ii8xMzY4NzYwMzUvMzkxNzc3NDY0LTAzODczM2ViLWU0YTAtNDhiZi1iM2ExLWMyODBiY2RlNDM5NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMTU3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjJiMjhhNmI4YjY1MzcwNDFhOGUwYjRjNWVkMmY0NjdkZDc2MTcxNDc1ZTYwOGI3MGZmMDdkY2FiOThiNDY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.a7KnATTvPWtlG1YnIm7J4jkLziEAyAjsoUu5E9Bht74)

En este link app-foss-release.apk

**Comment by fast4x** [comment]
download latest release 0.6.62.2
