### ISSUE TITLE
Non scarica le canzoni

### ISSUE THREAD

**Issue by LoryGH** [fast4x/RiMusic#4753]
### Version of RiMusic

0.6.62.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Quando provo a scaricare le canzoni ora non va più in crash, ma non le scarica

### Submit a video

https://github.com/user-attachments/assets/c529e377-2938-4b8a-85b8-998c0aefccaf

### What was your expectation?

Ho cliccato su scarica e poi non si scaricano

**Comment by fast4x** [comment]
Effettua login
