### ISSUE TITLE
Play button for playlists like in spotify

### ISSUE THREAD

**Issue by Googaa0082** [fast4x/RiMusic#4755]
### Description

Theres no play button for playlists in app like in spotify. I have to select a song from playlist in order to start that playlist. (Image below of RiMusic)

![Screenshot_20241202_135600](https://github.com/user-attachments/assets/69693356-9cc4-4732-bb6f-c66d85e70d53)

### Suggested Solution

Need button like in spotify (image below)
![Screenshot_20241202_135035](https://github.com/user-attachments/assets/d6c74b1a-0a8e-4336-a129-ea8e3b396ff9)

**Comment by fast4x** [comment]
What's difference there's with play and click on song?

**Comment by Googaa0082** [comment]
The difference is that play button randomely picks a song from playlist and starts from there

**Comment by aneesh1122** [comment]
> The difference is that play button randomely picks a song from playlist and starts from there 

Use shuffle button

**Comment by aneesh1122** [comment]
> Brother i dont think you get what i mean.
> In RiMusic we must first click on a specific song to start the playlist. Choosing the first song is annoying...
> But in spotify, by clicking play button it randomely picks the first song from the playlist for us and starts playlist from there (considering shuffle is turned on, if shuffle is turned off then the play button starts to play the playlist in sequence)
> 
> This is the reason why spotify have a play button

![Screenshot_2024-12-03-11-37-00-488_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/edf86a62-0726-4013-8904-ee240c430568)
