### ISSUE TITLE
Disappeared lyrics button for see complete screen

### ISSUE THREAD

**Issue by nomenamecom** [fast4x/RiMusic#4756]
### Version of RiMusic

0.6.62.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

See lyrics complete screen

### What more can you tell us? (Optional)

Some version ago was able to see the lyrics close to a complete screen. Now I couldn't see

I hope have the possibility and use about 90% of the screen (some version ago was around 50%)

It would be fine search in more library's

Thanks for your effort and support!
![Screenshot_2024-12-02-11-17-13-954_it fast4x rimusic](https://github.com/user-attachments/assets/9db79802-3c3f-41b6-8351-4718626347da)

**Comment by aneesh1122** [comment]
Stop using the old lyrics layout. Use the new one.

**Comment by nomenamecom** [comment]
Sorry, I have searched and I didn't find it. Where can I change the layout?
![Screenshot_2024-12-02-17-16-20-857_it fast4x rimusic](https://github.com/user-attachments/assets/b10fb3ab-669f-4206-939f-8d2969e12b47)

**Comment by aneesh1122** [comment]
I don't know what's it called in your language but in English you have to

1) disable 'show thumbnail for Lyrics'
2) enable 'expanded lyrics'

**Comment by nomenamecom** [comment]
Thanks!!!

Much better. And I could change the color, size of bar...etc 

Great change!

**Comment by aneesh1122** [comment]
> Thanks!!!
> 
> Much better. And I could change the color, size of bar...etc 
> 
> Great change!

Go at the end of settings and you can choose to disable components like the song's title when the lyrics are active.

**Comment by nomenamecom** [comment]
Fantastic. Bigger the space for reading

Thanks a lot!

**Comment by nomenamecom** [comment]
.
