### ISSUE TITLE
Manually change song title on clientside

### ISSUE THREAD

**Issue by sanga000** [fast4x/RiMusic#476]
### Description

It'd be great to be able to change the name of a song manually on clientside. This is especially useful for YT videos which tend to have overly long or not very useful names.

Long names in particular is problematic as there's no way to see the full name without actively listening to the song *and* waiting for the text to scroll. If you're listening to game or movie OST it's very easy to end up with a playlist with the exact same name visible in the playlist menu where there's no way to distinguish which is which since the actual song name is at the end of the video name.

### Suggested Solution

Add an extra button to a song/video's long press menu that allows the user to change its name locally. It might be useful if there's a small symbol to indicate a song's name has been changed and is not the actual name found on YT or YT music

### Alternatives

Perhaps a method to display full name even when in a list (i.e. all menus)

**Comment by fast4x** [comment]
Hello, next release have this option in albums, I'll add It also on song.

**Comment by fast4x** [comment]
For icon to indicate updated name, you can add some initial character like # _ - @

**Comment by fast4x** [comment]
Implemented, available from version 0.6.19

**Comment by fast4x** [comment]
Hi, I'll close it with new release...
