### ISSUE TITLE
[Feature]: UI Optimizations

### ISSUE THREAD

**Issue by tm-pst** [fast4x/RiMusic#4761]
### Description

Greetings Devs!
First of all, thanks for the great app! Its been of great use not only to me also to other people!
So, the recent updates have been feature packed and have also made the experience of using the app really great! However, some places do fall off from this.
Firstly, the UI in the lyrics settings menu. With the addition of various options, it has become a bit cluttered. Hence, I'd like to request for a **Grouping of the lyrics settings**, into groups like, _Lyrics Customisation, Translation_ and so on.
![IMG_20241202_212325](https://github.com/user-attachments/assets/507e22cf-67bd-4294-9665-1df96c635141)

 Moreover, if these were arranged in a **grid format** just like the song info menu, it would look great! 
![Screenshot_2024-12-02-21-16-44-233_it fast4x rimusic](https://github.com/user-attachments/assets/0eec64ed-4a70-4ab2-8e83-d77659d1beb5)
Then, the **animations**, it would be great if these were also optimized!

### Suggested Solution

-Grouping of Lyrics Settings and Grid format implementation
-Animations optimization 

### Alternatives

Im just a user, i might not know better, so its all in your hands devs!

### Additional Context

None

**Comment by fast4x** [comment]
Hi thanks, one question related animation optimization, what you mean exactly?

**Comment by tm-pst** [comment]
Okay so while using the expanded, there is a small bouncy animation in the essential player, while in the modern one it looks a bit jittery. This happens while opening the lyrics. Moreover, if there was a way to get the background of the gesture bar to match the app's theming settings(eg: fluid gradient theme, gradient and booked song cover), it would make the player look real good.

**Comment by fast4x** [comment]
Can set backgrounds player as you want in appearance settings

**Comment by tm-pst** [comment]
Okay thanks!
