### ISSUE TITLE
Android Auto and shuffle

### ISSUE THREAD

**Issue by Baviera10** [fast4x/RiMusic#4762]
### Version of RiMusic

0.6.62.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open AA
2.Open RiMusic
3. Click Song
4. Click on three points
5. Click on Shuffle
6. And the songs start to be  presented on screem a before it starts playing it switches to nex and so on

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

.

### What more can you tell us? (Optional)

.

**Comment by fast4x** [comment]
Shuffle in AA is used to enable a random song playing from queued songs. If a song is skipped, cause is relate a wrong cached song or error in song. Try to disable skip in error in ui settings

**Comment by Baviera10** [comment]
Fixed! Thanks

**Comment by fast4x** [comment]
Great thanks
