### ISSUE TITLE
Playlist or Queue Backstepping 1 or 2 Songs

### ISSUE THREAD

**Issue by lspranger05** [fast4x/RiMusic#4771]
### Version of RiMusic

0.6.62.2

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on song, playlist, album, or shuffle. 
3. Songs begin playing
4. Boom! Crash happens - when transitioning songs it will either skip backward one or two songs instead of forward. 
OR 
5. Click on next song button from now playing notification on lock screen. 
6. Boom! Crash happens - when transitioning songs it will either skip backward one or two songs instead of forward. 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I clicked on next, so I figured it would play what was next in the queue, but it jumped backward. 

### What more can you tell us? (Optional)

Usually only happens when screen is turned off but music is playing. The bug only happens with screen-on on the lockscreen when pressing skip forward on the now playing notification. 

Also only started happening after 0.6.61 update.   

### Logs (Optional)

2024-12-03T15:41:23.176:	android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service it.fast4x.rimusic/.service.modern.PlayerServiceModern
	 android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54) 
	 android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50) 
	 android.os.Parcel.readParcelableInternal(Parcel.java:4882) 
	 android.os.Parcel.readParcelable(Parcel.java:4864) 
	 android.os.Parcel.createExceptionOrNull(Parcel.java:3064) 
	 android.os.Parcel.createException(Parcel.java:3053) 
	 android.os.Parcel.readException(Parcel.java:3036) 
	 android.os.Parcel.readException(Parcel.java:2978) 
	 android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6457) 
	 android.app.ContextImpl.startServiceCommon(ContextImpl.java:2002) 
	 android.app.ContextImpl.startForegroundService(ContextImpl.java:1967) 
	 android.content.ContextWrapper.startForegroundService(ContextWrapper.java:847) 
	 F1.c.b(SourceFile:1) 
	 D8.F.k0(SourceFile:7) 
	 V3.x0.d(SourceFile:42) 
	 V3.r0.run(SourceFile:92) 
	 L2.E.M(SourceFile:26) 
	 U2.D.execute(SourceFile:8) 
	 C5.g.s(SourceFile:50) 
	 M5.s.run(SourceFile:668) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-12-03T15:41:23.176:	android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service it.fast4x.rimusic/.service.modern.PlayerServiceModern
	 android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54) 
	 android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50) 
	 android.os.Parcel.readParcelableInternal(Parcel.java:4882) 
	 android.os.Parcel.readParcelable(Parcel.java:4864) 
	 android.os.Parcel.createExceptionOrNull(Parcel.java:3064) 
	 android.os.Parcel.createException(Parcel.java:3053) 
	 android.os.Parcel.readException(Parcel.java:3036) 
	 android.os.Parcel.readException(Parcel.java:2978) 
	 android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6457) 
	 android.app.ContextImpl.startServiceCommon(ContextImpl.java:2002) 
	 android.app.ContextImpl.startForegroundService(ContextImpl.java:1967) 
	 android.content.ContextWrapper.startForegroundService(ContextWrapper.java:847) 
	 F1.c.b(SourceFile:1) 
	 D8.F.k0(SourceFile:7) 
	 V3.x0.d(SourceFile:42) 
	 V3.r0.run(SourceFile:92) 
	 L2.E.M(SourceFile:26) 
	 U2.D.execute(SourceFile:8) 
	 C5.g.s(SourceFile:50) 
	 M5.s.run(SourceFile:668) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

2024-12-03T21:33:20.205:	android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service it.fast4x.rimusic/.service.modern.PlayerServiceModern
	 android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54) 
	 android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50) 
	 android.os.Parcel.readParcelableInternal(Parcel.java:4882) 
	 android.os.Parcel.readParcelable(Parcel.java:4864) 
	 android.os.Parcel.createExceptionOrNull(Parcel.java:3064) 
	 android.os.Parcel.createException(Parcel.java:3053) 
	 android.os.Parcel.readException(Parcel.java:3036) 
	 android.os.Parcel.readException(Parcel.java:2978) 
	 android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6457) 
	 android.app.ContextImpl.startServiceCommon(ContextImpl.java:2002) 
	 android.app.ContextImpl.startForegroundService(ContextImpl.java:1967) 
	 android.content.ContextWrapper.startForegroundService(ContextWrapper.java:847) 
	 F1.c.b(SourceFile:1) 
	 D8.F.k0(SourceFile:7) 
	 V3.x0.d(SourceFile:42) 
	 V3.r0.run(SourceFile:92) 
	 L2.E.M(SourceFile:26) 
	 U2.D.execute(SourceFile:8) 
	 C5.g.s(SourceFile:50) 
	 M5.s.run(SourceFile:668) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by knighthat** [comment]
It happened to me too, but it's a little tricky because it happened once after 5hr+ of listening time

**Comment by fast4x** [comment]
Send crash log please

**Comment by lspranger05** [comment]
2024-12-03T15:41:23.176:	android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service it.fast4x.rimusic/.service.modern.PlayerServiceModern
	 android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54) 
	 android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50) 
	 android.os.Parcel.readParcelableInternal(Parcel.java:4882) 
	 android.os.Parcel.readParcelable(Parcel.java:4864) 
	 android.os.Parcel.createExceptionOrNull(Parcel.java:3064) 
	 android.os.Parcel.createException(Parcel.java:3053) 
	 android.os.Parcel.readException(Parcel.java:3036) 
	 android.os.Parcel.readException(Parcel.java:2978) 
	 android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6457) 
	 android.app.ContextImpl.startServiceCommon(ContextImpl.java:2002) 
	 android.app.ContextImpl.startForegroundService(ContextImpl.java:1967) 
	 android.content.ContextWrapper.startForegroundService(ContextWrapper.java:847) 
	 F1.c.b(SourceFile:1) 
	 D8.F.k0(SourceFile:7) 
	 V3.x0.d(SourceFile:42) 
	 V3.r0.run(SourceFile:92) 
	 L2.E.M(SourceFile:26) 
	 U2.D.execute(SourceFile:8) 
	 C5.g.s(SourceFile:50) 
	 M5.s.run(SourceFile:668) 
	 android.os.Handler.handleCallback(Handler.java:958) 
	 android.os.Handler.dispatchMessage(Handler.java:99) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:8919) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by fast4x** [comment]
Great! Thanks

**Comment by lspranger05** [comment]
UPDATE: after uninstalling version 0.6.61 and installing 0.6.62.2 I have not been able to replicate the bug.
