### ISSUE TITLE
Unable to view lyrics in this current update 

### ISSUE THREAD

**Issue by Chandramauli-Arm64** [fast4x/RiMusic#4773]
### Version of RiMusic

0.6.62.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically
![Screenshot_2024-12-03-20-47-09-36_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/user-attachments/assets/28cd882d-0ebc-492c-8427-959c780d2c90)

### What was your expectation?

After this update when I just got to see the lyrics it was unable to load it.

**Comment by knighthat** [comment]
were you able to view lyrics on this specific song on previous version?

**Comment by Chandramauli-Arm64** [comment]
> were you able to view lyrics on this specific song on previous version?

When I re-done the method again and again it solved but some certain songs do not show lyrics as in case you can see the attached screenshot.@knighthat

**Comment by knighthat** [comment]
not all songs have lyrics

**Comment by Chandramauli-Arm64** [comment]
> not all songs have lyrics

Yeah! I Noticed that.

**Comment by knighthat** [comment]
thank you

**Comment by Chandramauli-Arm64** [comment]
> thank you

Your welcome 😁
