### ISSUE TITLE
If you click the shuffle button in Artists and Albums, Playlist, the  player fragment will repeat

### ISSUE THREAD

**Issue by Figim** [fast4x/RiMusic#4774]
### Version of RiMusic

0.6.62.2

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

A) **Two strangely or similar bugs for artists**
**Bug 1**
1. Open RiMusic
2. Go to the **Artists** section
3. Click the **Shuffle** button
4. Close the **mini** **player**
5. Now, if you click on one of the artists, the **player will open automatically**.  

**Bug 1.1** Close the mini player. When you click the follow button, the player opens

**Bug 2**
1. Repeat the above 3 steps
2. The main player is sliding. Press and hold the mini player
3. Then go back to the mini player again with the back button
4. Close the mini player
5.  The player does not close and opens automatically

**B) Bug for albums**
1. Go to the Albums section
2. Click the shuffle button
3. Close the mini player
4. Then open one of the albums
5. Mini player opens automatically

C) **Bug for playlist**
1. Go to playlist section
2. Click the Shuffle button
3. **Let the music play for 10 seconds**
4. Close the mini player
5. It was reopened

### Submit a video

**Artist secton bug 1 and 1.1**

https://github.com/user-attachments/assets/7b3585b5-a20f-4cdb-a6c8-028899a5abf7

**Artist section bug 2**

https://github.com/user-attachments/assets/8e96b0b8-37a9-4725-bb23-6709e589e0f2

**Album secton bug**

https://github.com/user-attachments/assets/6f9d0305-2b7e-41c8-bd06-e031af06ef5e

**Bug for playlists**

https://github.com/user-attachments/assets/4a85d2ce-2976-4d6c-9c14-30869ed545c5

### What was your expectation?

When I repeat the above steps, the player does not restart 

### What more can you tell us? (Optional)

To better understand the bugs, close and reopen the application when repeating each bug in the application

### Logs (Optional)

Is there a need?

**Comment by knighthat** [comment]
3 bugs refer to the same problem. I noticed this while working on the locator. The player is not properly killed.

### What I've found (for devs)

After the ExoPlayer is closed manually. `ExoPlayer#isReleased` is not posted as true, `Player#curentMediaItem` sometimes shows last playing song instead of `null`

**Comment by knighthat** [comment]
well they all have the same result, player doesn't close properly

**Comment by fast4x** [comment]
I can't reproduce the bug, if you don't want close mini player, disable close by swiping in ui settings.

**Comment by knighthat** [comment]
I can confirm that it happens. You need to go to artist or album tab > click shuffle to start player > close shuffle by swiping down > select a random artist > player pops back up.


https://github.com/user-attachments/assets/dc0fa42d-d218-414f-a121-14e70391abe7

**Comment by knighthat** [comment]
mine wasn't even played and the bug still occurred

**Comment by fast4x** [comment]
Fixed, available from version 0.6.63
