### ISSUE TITLE
Error when clicking cube icon next to album in search result

### ISSUE THREAD

**Issue by Figim** [fast4x/RiMusic#4776]
### Version of RiMusic

0.6.62.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Search an artist
3. Go to artist section
4. Scroll up
5. Click the cube icon next to the album
6. Error

### Submit a video

https://github.com/user-attachments/assets/b2709590-99d7-4bdb-b152-d05fd7068f73

### What was your expectation?

No error when I click on the cube next to the album in artist section

### What more can you tell us? (Optional)

2024-12-03T21:15:31.999:	java.lang.IllegalArgumentException: Random range is empty: [0, 0).
	 U8.d.c(SourceFile:71) 
	 C9.z.b(SourceFile:303) 
	 M9.i.b(SourceFile:112) 
	 Y3.V.a(SourceFile:118) 
	 z.S0.t(SourceFile:131) 
	 I8.a.k(SourceFile:9) 
	 d9.E.D(SourceFile:81) 
	 d9.l.r(SourceFile:101) 
	 d9.l.E(SourceFile:33) 
	 d9.l.k(SourceFile:17) 
	 D0.K.y0(SourceFile:51) 
	 D0.K.L(SourceFile:32) 
	 x.j.L(SourceFile:111) 
	 D0.h.h(SourceFile:157) 
	 D0.h.h(SourceFile:136) 
	 D0.h.h(SourceFile:136) 
	 D0.h.h(SourceFile:136) 
	 D0.h.h(SourceFile:136) 
	 W3.c0.s(SourceFile:36) 
	 D0.x.n(SourceFile:141) 
	 K0.v.K(SourceFile:83) 
	 K0.v.l(SourceFile:383) 
	 K0.v.dispatchTouchEvent(SourceFile:76) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597) 
	 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923) 
	 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597) 
	 com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1016) 
	 com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1962) 
	 android.app.Activity.dispatchTouchEvent(Activity.java:4265) 
	 k.v.dispatchTouchEvent(SourceFile:3) 
	 com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:974) 
	 android.view.View.dispatchPointerEvent(View.java:15335) 
	 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7815) 
	 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7588) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6922) 
	 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979) 
	 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945) 
	 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7143) 
	 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953) 
	 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7200) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926) 
	 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979) 
	 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945) 
	 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953) 
	 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926) 
	 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10400) 
	 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10248) 
	 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10204) 
	 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10532) 
	 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259) 
	 android.os.MessageQueue.nativePollOnce(Native Method) 
	 android.os.MessageQueue.next(MessageQueue.java:335) 
	 android.os.Looper.loopOnce(Looper.java:186) 
	 android.os.Looper.loop(Looper.java:313) 
	 android.app.ActivityThread.main(ActivityThread.java:8669) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

### Logs (Optional)

No

**Comment by fast4x** [comment]
Fixed, available from version 0.6.63
