### ISSUE TITLE
Player crashes because of swears

### ISSUE THREAD

**Issue by whitewolf1o1o** [fast4x/RiMusic#4778]
### Version of RiMusic

0.6.62.2

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

I Opened RiMusic
Searched Fuck tha police by N.W.A
Clicked on play 
And It doesnt play the song and where ever I click, it crashes. I went to other songs, the song won't play if there are swears in the title

### Submit a video

https://github.com/user-attachments/assets/edc5f26f-d77a-4e26-8c8a-ed312706a508

### What was your expectation?

I expected it to play the music

### What more can you tell us? (Optional)

I believe it is because of the swears in the title (fuck), because I've checked other songs with swears and they dont work

**Comment by fast4x** [comment]
This isn't a crash but the song can't be played due to require login maybe, so login to youtube music from miscellaneous settings

**Comment by whitewolf1o1o** [comment]
> This isn't a crash but the song can't be played due to require login maybe, so login to youtube music from miscellaneous settings

I logged in once but it still didn't play
