### ISSUE TITLE
Downloaded icon not refresh after clear downloaded command

### ISSUE THREAD

**Issue by akrogun** [fast4x/RiMusic#478]
### Steps to reproduce the bug

1. Library / Playlist, select a playlist
2. Clear downloaded
3. Downloaded icon still solid white (theme on my phone is dark)

### Expected behavior

This should empty downloaded icon (blank box)

### Actual behavior

This happen instead solid box downloaded icon

### RiMusic version

0.6.18

### Android version

Android 10

**Comment by fast4x** [comment]
Hi, icon remain solid when Song Is cached by player. Try this, create a new playlist with some Song, click download all and After click remove all downloaded.

**Comment by akrogun** [comment]
There are no differences between downloaded and cached. They share same icon

**Comment by fast4x** [comment]
> There are no differences between downloaded and cached. They share same icon

Yes, you are right, could use a different icon for cached...

**Comment by ikanakova** [comment]
> > There are no differences between downloaded and cached. They share same icon
> 
> Yes, you are right, could use a different icon for cached...

Couldn't the cached songs be treated like the downloaded ones? I don't think it matters to the user if he downloaded the song manually or if it was automatically cached when he wants to delete it.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.47

**Comment by OrangeZXZ** [comment]
@fast4x @akrogun I believe this can be closed?

**Comment by fast4x** [comment]
This is actually present?

**Comment by OrangeZXZ** [comment]
This issue was about download icons that stay activated after complete deletion. I haven't seen the issue since, but I could be wrong.

**Comment by fast4x** [comment]
Yea also i haven't seen, I'll close it
