### ISSUE TITLE
Bug no reprodutor de música

### ISSUE THREAD

**Issue by Wadle44** [fast4x/RiMusic#4780]
### Version of RiMusic

0.6.62.2

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abra o Rimusic
2. Clique em uma música 
3. Pronto, bug feito!

### Submit a video

https://github.com/user-attachments/assets/bed5ac38-a0f0-4d1a-b795-5a3f9071834f

### What was your expectation?

Minha expectativa era que a música tocasse

### What more can you tell us? (Optional)

Bem, não é a primeira vez que este erro acontece mas... Acontece. Uhh, eu já estava logado no YT Music, tentei desligar mas nada adiantava.

### Logs (Optional)

2024-12-04T01:21:40.316:	C8.g
	 ya.b.h(SourceFile:428) 
	 j6.c.a(SourceFile:105) 
	 C5.f.run(SourceFile:45) 
	 java.lang.Thread.run(Thread.java:1012)

**Comment by Wadle44** [comment]
Desculpe a demora. Eu fiz o que você disse mas não adiantou :/

**Comment by fast4x** [comment]
RiMusic have an error with code 403, this is login required...

**Comment by Wadle44** [comment]
Então... Eu acabei limpando os dados do Rimusic, e funcionou, não me importo muito de perder as músicas eu acho elas novamente, se esse problema acontecer eu volto 🤙

**Comment by Wadle44** [comment]
Atualização: O app voltou a apresentar problemas ao tocar música, com login ou não.
