### ISSUE TITLE
My settings and statistic option isnt available

### ISSUE THREAD

**Issue by Anonymous-forreal** [fast4x/RiMusic#4787]
### Version of RiMusic

0.6.62.1

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

![Screenshot_20241204-190848](https://github.com/user-attachments/assets/0ce0eb3c-7bc3-422e-8196-389d9c3ebd90)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

To find settings and statistic option

**Comment by Anonymous-forreal** [comment]
Done.
It would be good if you add listening time and something like wrapped.

**Comment by fast4x** [comment]
Yep it's planned
