### ISSUE TITLE
Música con una mejor calidad de sonido 

### ISSUE THREAD

**Issue by Carlosnapa** [fast4x/RiMusic#4793]
### Description

Me gustaría que la música sea en tipo de formato flac se que la aplicación es una forma gratis de escuchar música pero sería muy buena idea y además una forma mas dinámica en la pantalla y en los ajustes no digo que se copien de Spotify o tidal pero sería una buena referencia para su interfaz 

### Suggested Solution

Música con mejor calidad de formato si es posible, y inicio más dinámico como sus ajustes 

### Alternatives

Si la música no se puede mejor prefiero el inicio más dinámico 

### Additional Context

Quiero escuchar música que mejor calidad y que l interfaz sea mas bonita se que es mucho pedir pero sería genial

**Comment by fast4x** [comment]
Quality is medium possible and available for free. If you want increase quality, get premium pad service from YouTube Music or many others.
You must remember that RiMusic isn't a pirate software.
