### ISSUE TITLE
Author's name doesn't match real name 

### ISSUE THREAD

**Issue by Ask1ew** [fast4x/RiMusic#4796]
### Version of RiMusic

0.62.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open Ri Music
2. Use a youtube playlist link to make your playlist
3. See the Author in playlist that doesn't match the real name Author. By default it takes the name of the Author of the playlist but not the name of the Author of the song.
![Screenshot_20241204_215606](https://github.com/user-attachments/assets/9e104df4-3320-478a-a215-5a0852501617)

### What was your expectation?

Make it works again

### What more can you tell us? (Optional)

The others song that have the right name is because i put manually the song into the playlist

**Comment by fast4x** [comment]
Try to update song...

**Comment by Ask1ew** [comment]
It's already done ! 
I don't make a ticket juste because it is not update.
I force it to update but nothing change...

**Comment by Ask1ew** [comment]
It's not complete ! 
It didn't work like i said before !
Sorry for my english i you don't understand...
