### ISSUE TITLE
[Feature]: Search button

### ISSUE THREAD

**Issue by dorky4th** [fast4x/RiMusic#4801]
### Description

Hi devs, I suggest putting search button because I can't seem to find it or there is no really a search button on the newly updated version. I can still pretty much search a song I just need to long press the app and then I can see that search bar that I'm looking, but I hope in the next update I can finally see a search button on inside the app

### Suggested Solution

H

### Alternatives

B

### Additional Context

J

**Comment by fast4x** [comment]
Search is visible always...

**Comment by dorky4th** [comment]
> Search is visible always...

I mean inside the app, I can't seem to find the search button I need to long press the app everytime for me to see that search bar, because I can't seem to find the search button inside the app if there was really a search button.

**Comment by fast4x** [comment]
Search icon is in top, update your version, if you use ViMusic mode, enable also Search icon in ui settings

**Comment by dorky4th** [comment]
> Search icon is in top, update your version, if you use ViMusic mode, enable also Search icon in ui settings

Idk man, but I use rimusic mode and it's also the latest version, but the only prob is there is no search button even the settings are gone, the app still works fine.
