### ISSUE TITLE
When you play a video from Watch History, the queue is empty.

### ISSUE THREAD

**Issue by Figim** [fast4x/RiMusic#4803]
### Version of RiMusic

0.6.62.2

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Go to watch History
3. Play music
4. The queue is empty

### Submit a video

https://github.com/user-attachments/assets/5abe51ad-cebc-4917-af6b-83b025b86673

### What was your expectation?

Restore queue when playing video from Watch History

### What more can you tell us? (Optional)

Nothing

### Logs (Optional)

?

**Comment by twistios** [comment]
This is essentially **not** a bug. As you clicked on the song (and not added it to the queue) you started a new queue based on the selection.
I am not sure how the queue is supposed to be created in this case so I don't know if it should be only a single song as in your case.
