### ISSUE TITLE
Button to Restart?

### ISSUE THREAD

**Issue by CollegeTimeOhNo** [fast4x/RiMusic#4808]
### Description

So after you connect to youtube music it says restarting is required, with no consistent way to actually restart the app so youtube music connects. Perhaps a button just for restarting issues in general but also so youtube music can be connected consistently for people? Asking after I realized I'm not alone in the "restarting required" message never going away despite what i try after connecting youtube music.

### Suggested Solution

A button in the settings, preferably in "Misc" with "Check for Updates" and "Connect to Youtube Music" to "Restart the App" so connecting to youtube music can work and other issues may be quickly resolved too?

### Alternatives

Otherwise add a restart button to the youtube music login area, other areas that require restarting after a change have a button to Restart Player. Or maybe a little info button, like the i in thw circle, near the youtube music button for how to actually connect it and Restart it since it is not abundantly clear.

### Additional Context

No other context, but thank you guys for working on the app! This is my only gripe with it.

**Comment by twistios** [comment]
If the message does not go away after restart (and maybe additional force close before that), then it has not worked. This happens in case you have multiple accounts in one email.

**Comment by CollegeTimeOhNo** [comment]
Hi! I actually did both of those, a restart, a force close, and just reinstalling the app as a whole! And I made this email specifically for the app, and it still happens. I suggest the restart button as a possible permanent fix because it gives the app whatever it needs exactly to fix it, and would probably help if any bugs that needed a restart ever occured! But i also understand, I don't know much about coding or how apps work, it just seemed like a good suggestion in my mind.

**Comment by CollegeTimeOhNo** [comment]
? Sorry I just woke up, reading comprehension is bad, I mentioned it in the message before this one that I did that, no? Anyway, I didn't mean to write this as if I'm looking for help, I kinda gave up on figuring it out atm, but I thought it'd be a useful function for problems like this and maybe any other that could happen!

**Comment by fast4x** [comment]
Sure, but restart button = close and reopen app...
