### ISSUE TITLE
Short and concise description of your bug

### ISSUE THREAD

**Issue by SveinAu** [fast4x/RiMusic#4810]
### Version of RiMusic

0.6.62.1

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Mini player tre dots. And have not been before. Can't turn it off

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

It is consistent

**Comment by fast4x** [comment]
Disable now playing indicator
