### ISSUE TITLE
downloaded songs not recognized by Android Auto 

### ISSUE THREAD

**Issue by Tre916** [fast4x/RiMusic#4815]
### Version of RiMusic

0.6.62.2

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Navigate to songs section of Android Auto observe zero songs listed as downloaded.

### Submit a video

![IMG_20241206_145508](https://github.com/user-attachments/assets/abe045fb-db88-4574-84b8-09b912650d5e)

You can see the count in the app vs on the AA screen.

### What was your expectation?

it would match the downloaded songs count in the phone app 

### What more can you tell us? (Optional)

It also doesn't play immediately so I don't think it's actually playing the downloaded songs. I think it's streaming them.

This has been ongoing for a while but you guys have been knocking out so many other issues, that now it's worth addressing.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.63.1
