### ISSUE TITLE
Crash when trying to play any song.

### ISSUE THREAD

**Issue by MaxweIlCatDEV** [fast4x/RiMusic#4817]
### Version of RiMusic

0.6.63

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on any song
3. Boom! Crash happens

### Submit a video

https://github.com/user-attachments/assets/5d815598-c40c-4f8b-b0dd-beebc06a668c

### What was your expectation?

Play this song for me pls...

### What more can you tell us? (Optional)

**Device:** Samsung
**OneUI:** 6.1

The problem was introduced in this update.
The problem only appears if clean installation.
Updating from old version to new one does not cause crash.

### Logs (Optional)

Logcat error:

**AndroidRuntime**
`FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 19124
android.app.RemoteServiceException$CannotPostForegroundServiceNotificationException: Bad notification for startForeground
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2297)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2619)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

**Comment by fast4x** [comment]
Please try this custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by MaxweIlCatDEV** [comment]
> Please try this custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

Still crashing with same error

`2024-12-07T21:16:35.761:	android.app.RemoteServiceException$CannotPostForegroundServiceNotificationException: Bad notification for startForeground
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2297) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2619) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:9063) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) `

**Comment by fast4x** [comment]
Fixed, available from version 0.6.63.1
