### ISSUE TITLE
the app closes when playing any song :(

### ISSUE THREAD

**Issue by TkJess0987** [fast4x/RiMusic#4819]
### Version of RiMusic

0.6.63

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

https://github.com/user-attachments/assets/ec712545-f11b-4bed-a1e8-60949e40eea3

### What was your expectation?

:(

**Comment by fast4x** [comment]
Enable debug and after crash send crash log.

**Comment by MaxweIlCatDEV** [comment]
> Enable debug and after crash send crash log.

I opened issues with (probably) same bug earlier.
I also attached log from logcat.
I will also attach crash log from my app here:

`2024-12-07T16:22:57.254:	android.app.RemoteServiceException$CannotPostForegroundServiceNotificationException: Bad notification for startForeground
	 android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2297) 
	 android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 
	 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2619) 
	 android.os.Handler.dispatchMessage(Handler.java:106) 
	 android.os.Looper.loopOnce(Looper.java:230) 
	 android.os.Looper.loop(Looper.java:319) 
	 android.app.ActivityThread.main(ActivityThread.java:9063) 
	 java.lang.reflect.Method.invoke(Native Method) 
	 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588) 
	 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) `

**Comment by MaxweIlCatDEV** [comment]
> ### Version of RiMusic
> 0.6.63

Install previous release, then update it.
This should be a temporary solution.

**Comment by fast4x** [comment]
Please try this custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by aneesh1122** [comment]
> Please try this custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

The bug is still there

**Comment by fast4x** [comment]
Fixed, available from version 0.6.63.1

**Comment by TkJess0987** [comment]
Sorry if I keep being persistent with this but they haven't fixed the
animation when you choose a song since they added Now playing indicator

**Comment by fast4x** [comment]
Send video what you mean exactly
