### ISSUE TITLE
Theme black modern not use the material you colorschemes

### ISSUE THREAD

**Issue by ynoalberto** [fast4x/RiMusic#4820]
### Version of RiMusic

0.6.63

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

I open the settings of the app am when I Select the black modern theme I can't Selecto option yo use material you colorscheme 

### Submit a video

https://github.com/user-attachments/assets/9b12cfa3-4c0e-419c-b22b-e644d72b72c8

### What was your expectation?

When I Select the theme black modern the app not use the material you colorscheme

### What more can you tell us? (Optional)

In older Versions I could to use material you colorscheme with the black modern theme

**Comment by fast4x** [comment]
Black modern and material are two different themes with separate color schemes.

**Comment by ynoalberto** [comment]
I remember that in older Versions the modern theme adaptes with the material you colorscheme of android. But it's okay, sorry to bother you.

**Comment by fast4x** [comment]
Was a bug... 😊

**Comment by ynoalberto** [comment]
Ok
