### ISSUE TITLE
App crashing when music is started to play

### ISSUE THREAD

**Issue by storm-27** [fast4x/RiMusic#4829]
### Version of RiMusic

0.6.63 (Latest Version. Till Dec 5th)

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on a song
3. Boom! Crash happens

### What was your expectation?

It plays music 

### What more can you tell us? (Optional)

It directly crashes, no errors, no nothing, just closes the app and doesn't leave any logs or anything.

### Logs (Optional)

No logs :/
(Prob gonna temp switch to old version till this is fixed)

**Comment by storm-27** [comment]
Video couldn't be added as it exceeds memory

**Comment by Rocky0035** [comment]
+1 
There's no error or anything shown it directly takes me back to the home screen when I tap on the songs. Fix it ASAP. #4137

**Comment by knighthat** [comment]
are you on custom version by any chance?

**Comment by aneesh1122** [comment]
> Fix it ASAP

Say please and developers might just think about fixing it.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.63.1

**Comment by storm-27** [comment]
> are you on custom version by any chance?

Nope, the official version only
