### ISSUE TITLE
Wierd inconsistent artist icon inside player menu

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#483]
### Steps to reproduce the bug

I thought this was new feature, I think this was a bug when I tried to play different songs
- Play a song & go to player
- Click player `⋮` three dots
- Wierd looking & Inconsistent artist icon

### Expected behavior

I dont know

### Actual behavior

Not all artist are visible
- visible on 1 artist (youtube music)
- Invisible on 2 or more artist
- invisible for youtube channel (unsure if they have youtube music too)

### Screenshots/Screen recordings

<table>
<thead>
  <tr>
    <th>1 Artist</th>
    <th>Youtube channel</th>
    <th>2 or more Artist</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><img src=https://github.com/fast4x/RiMusic/assets/45221211/2c6bf815-a224-466f-8e82-ca1916c1294e""></img></td>
    <td><img src="https://github.com/fast4x/RiMusic/assets/45221211/a9608d45-79a0-4195-b858-90215971c4e8"></img></td>
    <td><img src="https://github.com/fast4x/RiMusic/assets/45221211/fdff2fb9-f01b-4d8c-b5bd-215149e45c94"></img></td>
  </tr>
</tbody>
</table>

### RiMusic version

0.6.18

### Android version

Android 11

**Comment by fast4x** [comment]
Suggestions for new aspect?

**Comment by faustaahmad** [comment]
I dont know... still no Idea
Perhaps place the profile picture in the player itself (near the artist name)
It may looks wierd as the menu doesnt have 👥 icon like player & download/cache icon is placed near the artist name
Also if there are multiple artist involved, it would clutter the space. Unless folder-like icon, which hard to see because of small

not showing artist profile pict is okay for me

[BUG] I realized that if there are 2 or more people involved
There'll be no "More from ...."
Should I create another issue for this one too?

**Comment by fast4x** [comment]
> Non lo so... Ancora nessuna idea Forse posizionare l'immagine del profilo nel lettore stesso (vicino al nome dell'artista) Può sembrare strano in quanto il menu non ha 👥 un'icona come il lettore e l'icona di download / cache è posizionata vicino al nome dell'artista Inoltre, se ci sono più artisti coinvolti, ingombrerebbe lo spazio. A meno che non si tratti di un'icona simile a una cartella, che è difficile da vedere a causa delle piccole
> 
> Non mostrare l'immagine del profilo dell'artista va bene per me
> 
> [BUG] Mi sono reso conto che se ci sono 2 o più persone coinvolte non ci sarà nessun "Altro da...." Devo creare un altro problema anche per questo?

More of... show only if are present authors info in response api...

**Comment by faustaahmad** [comment]
> It seem to work.. of there are authors info
Doesnt work for me, sometimes work on ViMusic app but often doesnt
unsure how to take the log too

**Comment by fast4x** [comment]
Do you have other info?

**Comment by faustaahmad** [comment]
> Do you have other info?

Maybe...
**Auto romanization of artist name**
This was screenshot when I search for songs from artist/va name that has been romanized by youtube (I think)
All the songs has broken/unavailable artist beside some that are inside my songs library & parsed (YUI, Ikimonogatari, MONOGATARI Series, ...)
<table><tbody>
<tr><th>Search query: `minori chihara monochrome`
<img src="https://github.com/fast4x/RiMusic/assets/45221211/36fb7683-9859-4105-8a14-08d4f3f79415"></img>
</th></tr>
</tbody></table>

**Songs wont have artist in their info menu before you play 'em, but some wont make the artist visible even if you play 'em**
Always happens for me
<table>
<thead><tr>
<th colspan=2>Need to play before it's visible</th>
</tr></thead>
<tbody><tr>
<th><img src="https://github.com/fast4x/RiMusic/assets/45221211/c26584ac-423b-4b97-8d82-ad8ca2b1e86d"></img></th>
<th><img src="https://github.com/fast4x/RiMusic/assets/45221211/4e9d43a8-d5fa-4d70-af41-7dabbcdacc37"></img></th>
</tr></tbody>
</table>

**Songs are not found inside Artists songs list**
The Thunder Rolls (The Long Version) artist isnt parsed in my end, though The Thunder Rolls got parsed just fine.
I didnt even see the long version in State of Mine songs list
I couldnt find 啟航 in MSR's songs list too
idk if that was the issue

Hope this help.

**Comment by faustaahmad** [comment]
Closing this issue since the feature disabled/discontinued
