### ISSUE TITLE
Album appears as "null" in notification player

### ISSUE THREAD

**Issue by MedieroAF** [fast4x/RiMusic#4831]
### Version of RiMusic

0.6.63

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Play any song
3. Click on the album icon, loading it
4. Restart player

### What was your expectation?

The name of the album should appear beside the names of the artists in the notification player. It should also be present in Android Auto. In the player, instead of "[Artist] | [Album]", you get [Artist] | null". In Android Auto, there's no text in the album field.

### What more can you tell us? (Optional)

I believe this only happens when you load the album, as I've tried to search songs I've never listened to and the album name appears just fine. (by loaded albums I mean those that appear in Albums -> Library, and that have the cover image and release date loaded)

**Comment by knighthat** [comment]
are you on custom version by any chance?

**Comment by MedieroAF** [comment]
> are you on custom version by any chance?

No, I use the versions provided here.

**Comment by knighthat** [comment]
here where?

**Comment by fast4x** [comment]
Fixed, available from version 0.6.63.1
