### ISSUE TITLE
Yt music link not opening in Ri music app .

### ISSUE THREAD

**Issue by HITEN2007** [fast4x/RiMusic#484]
### Steps to reproduce the bug

I want to open Ri music with a YouTube music link 

### Expected behavior

It should be open in Ri music as I have not installed YouTube music . And Link is even opening in Ri music .

### Actual behavior

But after the app opens the music does not plays

### RiMusic version

0.6.18

### Android version

Android 11

### Additional information
I am not a Techy guy but I found this mistake So I thought I should Inform .
_No response_

**Comment by fast4x** [comment]
Please send some screenshot of how to share link tò RiMusic.

**Comment by fast4x** [comment]
Bug not reproduced, it work perfect.
When you share link from youtube music by browser internet like chrome or other, share link from menu of browser. It work.
If use yt music app you can share normally from inside app.

**Comment by HITEN2007** [comment]
I shared a link from Vi music and the link was also opening in vi music but
when i tried it to open in ri music , it was not opening  .

**Comment by fast4x** [comment]
Write here the link please

**Comment by HITEN2007** [comment]
https://music.youtube.com/watch?v=x0oZZgpSq8M   , here is the link .
