### ISSUE TITLE
The menu does not open when you press and hold the thumbnail

### ISSUE THREAD

**Issue by Figim** [fast4x/RiMusic#4840]
### Version of RiMusic

0.6.63.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Press and hold the thumbnail
3. Previously, the menu was opened
4. Now the menu does not open

### Submit a video

The video for this is hilarious😂

### What was your expectation?

Open the menu when you press and hold the thumbnail

### What more can you tell us? (Optional)

No

### Logs (Optional)

No

**Comment by aneesh1122** [comment]
Why do you need the menu?

**Comment by aneesh1122** [comment]
> > Why do you need the menu?
> 
> It was just there before, I say maybe it doesn't work by mistake. 😁

Nope. I disabled it when it is not required. Enable fading edge or use carousel to have the menu back.

**Comment by aneesh1122** [comment]
Do you use telegram?
