### ISSUE TITLE
[Feature]: Option to translate to the default language without a prompt

### ISSUE THREAD

**Issue by Egezenn** [fast4x/RiMusic#4848]
### Description

In the player, when you enable `show thumbnail for lyrics` setting, you always have to select the language you want to translate to.

### Suggested Solution

Could add an option to set the default language to translate to (someone might want the whole ui in their native language however they might enjoy the translations in English or a language they're learning).
Translate without prompt when only clicked and show the prompt only if the user wants to translate to some other language by pressing longer.

**Comment by aneesh1122** [comment]
You can set the default language. Just select a language from the languages menu and everytime you enable the translation it will be translated to that language unless you change the language again

**Comment by Egezenn** [comment]
I think I've given insufficient context.
The button in the picture I've provided always prompts me to which language to translate to. The configuration is:
Player type: Essential
Show thumbnail for lyrics: On
![image](https://github.com/user-attachments/assets/9538da02-6dda-4645-97c0-0b211315e60a)

**Comment by aneesh1122** [comment]
> I think I've given insufficient context.
> The button in the picture I've provided always prompts me to which language to translate to. The configuration is:
> Player type: Essential
> Show thumbnail for lyrics: On
> ![image](https://github.com/user-attachments/assets/9538da02-6dda-4645-97c0-0b211315e60a)
> 
Okay, that makes sense but this old lyrics layout will be removed in the future so I don't know if it there's any point in improving it.

Why don't you disable 'show thumbnail for lyrics'?

**Comment by Egezenn** [comment]
> will be removed in the future
Oh. That's a bummer. I didn't know.

Every so often I reset my settings so I'm up to date with the newest defaults :D. But I kind of didn't like the *new* one because I felt that it's just soulless without the cover art accompanying it and it being completely transparent.

**Comment by aneesh1122** [comment]
> > will be removed in the future
> 
> Oh. That's a bummer. I didn't know.
> 
> Every so often I reset my settings so I'm up to date with the newest defaults :D. But I kind of didn't like the *new* one because I felt that it's just soulless without the cover art accompanying it and it being completely transparent.

You can use your album cover as the player background and use the new lyrics layout.

https://github.com/user-attachments/assets/b95d9444-b50f-4029-b788-a494cd95f613

**Comment by Egezenn** [comment]
Well, I think we're on a clash of aesthetics :D
Here's a summary of why I wouldn't use and don't like the configuration you've provided:

- Covers being a background especially when it gets cropped from sides (blurred is okay for the ambiance, thanks for reminding me of the setting, I was looking for something alike)
- Cover itself being shown again
- Sometimes covers as a background just makes the UI elements undistinguishable & creates artifacts that aren't easy to the eye (at least mine)
- The whole player changing for lyrics

You could say I'm a man simplicity :D I was even reluctant to enabling dynamic theming at first :p

**Comment by Egezenn** [comment]
Okay, I caved in and switched my settings to modern & disabled the thumbnail option. Although I miss the cover the handy translate button, I'll admit that the new UI is far better!
I'm closing this request as you've said it's not maintained & will be removed. I'll make a FR for the old layout's features in the future :)
