### ISSUE TITLE
[Feature]: Customizing swipe actions

### ISSUE THREAD

**Issue by Egezenn** [fast4x/RiMusic#4849]
### Description

On the queue and the favorites you can swipe:
- from left to add it after the current song to the queue
- from right to delete the song from the queue (in queue) / delete the favorite (favorites) / favorite (any other place)

However it could be better if the user could select something else for themselves.

Personally I don't mind the current actions but from time to time I've accidentally deleted my favorites.

### Suggested Solution

A setting to set the swipes for each context.

### Alternatives

Suggestion above might be too much work, instead there could be an option change the deletion action to something like start radio from that song.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.65
