### ISSUE TITLE
[Feature]: Player action bar settings is missing start radio action

### ISSUE THREAD

**Issue by Egezenn** [fast4x/RiMusic#4850]
### Description

Start radio action is missing from the player action bar.

### Suggested Solution

Updating the section for the player action bar in settings by adding start radio action.

**Comment by fast4x** [comment]
Implemented start radio button in action bar, available from version 0.6.64

**Comment by Egezenn** [comment]
Now that I think about it this was too broad :x I'll edit the issue to comply.
Thanks for your work!
