### ISSUE TITLE
Discovery state doesn't get updated on player when it's toggled from queue

### ISSUE THREAD

**Issue by Egezenn** [fast4x/RiMusic#4851]
### Version of RiMusic

0.6.63 (haven't seen any changes regarding this from the latest release)

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Have a player by playing any song
3. Open the queue
4. Toggle discovery state from there
5. Go back to the player, the state of it is not changed

### What was your expectation?

Discovery state to update on the player

**Comment by aneesh1122** [comment]
You have to start the radio again after enabling the discover icon

**Comment by Egezenn** [comment]
This is not about it applying the discovery behavior to the current playlist. The button on the queue and player are not synced when it's changed from the queue.

**Comment by aneesh1122** [comment]
> This is not about it applying the discovery behavior to the current playlist. The button on the queue and player are not synced when it's toggled from the queue.

Okay my bad. Sorry about that. Yeah you're right. The discover logo isn't updating after it's enabled in the queue page.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.64
