### ISSUE TITLE
Media cannot be properly paused by TWS touch controls

### ISSUE THREAD

**Issue by RadAnshLad** [fast4x/RiMusic#4852]
### Version of RiMusic

0.6.63.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. RiMusic runs in background playing music
2. Taps on the side of TWS earbuds
3. Audio is paused
4. Then after 3-4 sec it starts to play again
(Note:the TWS used here is a semi generic earbud call cosmo buds x200) 

### Submit a video

https://github.com/user-attachments/assets/431ab77f-c1a9-4da5-b76b-978b50254750

For some reason it is continuous in the vid but actually pauses for me in my buds for 3-4 sec

### What was your expectation?

I expected it to pause normally but it doesn't

**Comment by fast4x** [comment]
Check if in settings have auto start play enabled

**Comment by RadAnshLad** [comment]
Where can I find this setting
