### ISSUE TITLE
Unable to delete Playlists. 

### ISSUE THREAD

**Issue by ahmark-new** [fast4x/RiMusic#4853]
### Version of RiMusic

0.6.63.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Go to Playlists section. 
3. Open one of your Playlist. 
4. Click on 3 dots. 
5. Click on delete. 
6. Then Confirm delete.

### Submit a video

https://github.com/user-attachments/assets/93038dc8-232d-4a2c-b13f-3cb7b4d693e1

### What was your expectation?

I expected it to delete that Playlist. 

### What more can you tell us? (Optional)

After clicking on delete, the animation was played but the Playlist was still there.

**Comment by Abhinavreddy-B** [comment]
aren't monthly playlists automatically created? i dont think we can delete it manually

**Comment by ahmark-new** [comment]
I'm talking about Playlist manually created by me.

**Comment by fast4x** [comment]
Not reproduced delete work normally
