### ISSUE TITLE
The songs get downloaded in medium quality even if it is selected high quality in the settings

### ISSUE THREAD

**Issue by 69chaman69** [fast4x/RiMusic#4854]
### Version of RiMusic

0.6.63.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

That the songs will get downloaded in high quality

**Comment by fast4x** [comment]
Compared to YouTube premium, quality offer in free plan is medium.
