### ISSUE TITLE
To obfuscate or not to obfuscate

### ISSUE THREAD

**Issue by knighthat** [fast4x/RiMusic#4855]
### Description

So, I was reading the document of these build parameters:

```gradle
isMinifyEnabled = true
isShrinkResources = true
```

then I found this [article](https://developer.android.com/build/shrink-code).

I generally don't have any problem with shrink code and optimization (I'm for this actually). But there's a section that I don't see the point - [Obfuscate your code](https://developer.android.com/build/shrink-code#obfuscate). 

Here's an example provided in the article:

```
androidx.appcompat.app.ActionBarDrawerToggle$DelegateProvider -> a.a.a.b:
androidx.appcompat.app.AlertController -> androidx.appcompat.app.AlertController:
    android.content.Context mContext -> a
    int mListItemLayout -> O
    int mViewSpacingRight -> l
    android.widget.Button mButtonNeutral -> w
    int mMultiChoiceItemLayout -> M
    boolean mShowTitle -> P
    int mViewSpacingLeft -> j
    int mButtonPanelSideLayout -> K
```

As you can see, class name and variable name are reduced to a single letter (most of the time) for smaller size and to hide code.

But the question is, how much of a convenience are you willing to sacrifice to achieve a better size. I ran my tests and the difference is ~1-2MB (~5-8%).

### Suggested Solution

To disable obfuscation, simply add `-dontobfuscate` to `composeApp/proguard-rules.pro` file and compile new code

### Additional Context

Obfuscating code in an opensource project is... let's say... ridiculous thing to do since it makes the debugging way harder than it should be.

**Comment by knighthat** [comment]
one example of code obfuscation makes it harder to debug is #4694

**Comment by fast4x** [comment]
Obfuscation is used only for decreasing size...
In an open source project there's complete source available for inspection.

**Comment by knighthat** [comment]
> Obfuscation is used only for decreasing size... In an open source project there's complete source available for inspection.

that's literally what I said, the obfuscated APK is only 1-2MB smaller, but the log is way harder to read to debug. 

My question was: **Is it really that beneficial to trade a couple MB worth of space for a harder to read debug log?**

**Comment by fast4x** [comment]
Isn't necessary to increase size of apk for reading log better.
