### ISSUE TITLE
cuando cierro la aplicación sigue estando la notificación en la barra de notificaciones aunque ya no esté reproduciendo algo

### ISSUE THREAD

**Issue by pokeshadow89** [fast4x/RiMusic#4861]
### Version of RiMusic

6.63.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1-selecciono una canción
2-salgo de la aplicación (cerrándola dede el administrador de tareas)
3-voy a la barra de notificaciones y ahí sigue la notificación 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

que lleguen a quitar ese error, no es primordial, pero llega a ser algo molesto ya que ante no estaba

### What more can you tell us? (Optional)

este error no ocurría de la 6.58.1 para abajo

**Comment by fast4x** [comment]
Check if close background player is enabled in ui settings.
