### ISSUE TITLE
[Feature]: I have a question for you 

### ISSUE THREAD

**Issue by bauldihr** [fast4x/RiMusic#4862]
### Description

1. Is it normal to download a song and keep going back to the beginning of the created playlist? Or is it a bug? One more question: 

2. Sometimes with YouTube Music it works, and sometimes without YouTube Music it works, for both cases? 

https://github.com/user-attachments/assets/1d70ddcc-7e87-4007-9b34-a59d19e7a76a

### Suggested Solution
.

### Alternatives

.

### Additional Context

.

**Comment by fast4x** [comment]
It's a bug
