### ISSUE TITLE
Bug: whenever i select a song the song list scrolls all the way up.... And the app also feels laggy since recent update 

### ISSUE THREAD

**Issue by nikhilhaRI234** [fast4x/RiMusic#4865]
### Version of RiMusic

V0.6.63.1 

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Play a song 
3. Boom! The list scrolls up

### Submit a video

https://github.com/user-attachments/assets/45668d15-121e-4a3f-b7ee-d11b4add3497

### What was your expectation?

New update focusing on quality of life like less laggy and more bug free instead of more features

**Comment by nikhilhaRI234** [comment]
Me again someone on my previous report said to disable animation which worked but now the new song playing animation freaking out.... Add feature that a button to disable that animation... I didn't liked it on the first place makes the app look less simplicity 😭😭

https://github.com/user-attachments/assets/fcd5f737-7749-4b91-adbd-f9eb7b4ae96c

**Comment by fast4x** [comment]
Go in ui settings > now playing indicator, select disabled

**Comment by nikhilhaRI234** [comment]
The scroll to the top thingy still happening sometimes... I think it's a app bug not a thing triggered by animation.... Disabling animation helped a little but it is not the fix.

**Comment by fast4x** [comment]
Download custom version

**Comment by nikhilhaRI234** [comment]
The scroll to the top thingy still happening sometimes... I think it's a app bug not a thing triggered by animation.... Disabling animation helped a little but it is not the fix.

**Comment by nikhilhaRI234** [comment]
there is a debug and a another one too...which one

**Comment by nikhilhaRI234** [comment]
tried and the custom one also has it.

**Comment by fast4x** [comment]
this version https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by nikhilhaRI234** [comment]
> this version https://github.com/fast4x/RiMusic/tree/master/customVersion

Tried it... Here's my experience : app runs smoother for first few song in the list and lags when we go down some songs... Also the part that list scrolls up is still happning

**Comment by nikhilhaRI234** [comment]
Anyone there? I think I will download the older versoions
