### ISSUE TITLE
Select multiple songs 

### ISSUE THREAD

**Issue by Jhonsilva953** [fast4x/RiMusic#4871]
### Description

I would love it if there was an option to choose multiple songs, both to add to the playlist at once and to delete, because I have an old playlist list, but I wanted to remove some songs,But it will take a long time to delete the songs I want to remove.

### Suggested Solution

So I just think I should use that mark option and unmark the songs to be able to delete more than one song from the playlist, and to be able to add more than one as well. 

### Alternatives

I don't know any other alternative 

### Additional Context

The problem is that it takes hours to delete the songs from each one.

**Comment by fast4x** [comment]
Yep, tap on there dots menu and click on Select/Deselect
