### ISSUE TITLE
sort songs 

### ISSUE THREAD

**Issue by SoyBlitz** [fast4x/RiMusic#4878]
### Description

to clarify it is not a complaint but an opinion that they can add soon 

### Suggested Solution

he thought that they should sort the songs in alphabetical order because it is very inconvenient to search for them and that they are watered the truth I hope they implement it very soon thanks

**Comment by aneesh1122** [comment]
Tell them to install the app first and use it for a bit before requesting for anything.

1) In the songs tab hold the arrow icon and choose 'Title'

2) In playlists

![Screenshot_2024-12-11-02-50-38-268_it.fast4x.rimusic-edit.jpg](https://github.com/user-attachments/assets/08257a8c-fc00-4d7c-9f88-0388880efa3c)


Tap this to bring the sorting options and choose 'Title'
