### ISSUE TITLE
Music Playback Error

### ISSUE THREAD

**Issue by Spatial89** [fast4x/RiMusic#4879]
### Version of RiMusic

0.6.63.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Start playing music
3. The playback keeps skipping songs after playing for about 5 seconds.

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

The music to continue in the same song until it ends

**Comment by fast4x** [comment]
You have medley mode enabled, tap and hold play button, click on hourglass to reset medley duration.
