### ISSUE TITLE
I can't click on songs in Playlist

### ISSUE THREAD

**Issue by Julian1535** [fast4x/RiMusic#4881]
### Version of RiMusic

Newest one

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

https://github.com/user-attachments/assets/abc5fd66-ab33-40b1-9d49-76b94825393c

 

### What was your expectation?

.

**Comment by fast4x** [comment]
Download custom version https://github.com/fast4x/RiMusic/tree/master/customVersion
