### ISSUE TITLE
Problemas al descargar canciones (nuevamente)

### ISSUE THREAD

**Issue by Jen-Tesfaye** [fast4x/RiMusic#4887]
### Version of RiMusic

0.6.63.1

### Android version

8.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on buscador
3. Click on descargar canción 
4. Descarga fallida
![Screenshot_20241211-164329](https://github.com/user-attachments/assets/4d5bcb16-1f05-41f8-894d-cde00f80a99c)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Siempre que instalo la nueva actualización, tiene este inconveniente. Lanzan otra actualización (después de haber tenido ese fallo) y sí puedo hacerlo.

**Comment by fast4x** [comment]
login to YouTube music

**Comment by Jen-Tesfaye** [comment]
> Iniciar sesión en YouTube Music

Hola, sí. Lo he hecho. También la he desconectado y nuevamente, volver a iniciar la sesión.
