### ISSUE TITLE
[Feature]: Spotify playlist import

### ISSUE THREAD

**Issue by Chimeraaaaaz** [fast4x/RiMusic#4892]
### Description

was just wondering if people who migrated from Spotify, like me, were able to import their playlists to this app, would be a really helpful since playlists that took over a year to put together with over 10 hours of music r really hard to just add 1 by 1

### Suggested Solution

-

### Additional Context

if it means that I have to give permission to access my account, me and I'm sure that a lot of others would accept it, since we can revoke the permission after we done importing

**Comment by fast4x** [comment]
Not possible because songs codes are different, you can use online tool to trasfer data from Spotify to YTM and you can import in RIMusic
