### ISSUE TITLE
The miscellaneous button on the navigation bar is laggy.

### ISSUE THREAD

**Issue by lacshire** [fast4x/RiMusic#4903]
### Version of RiMusic

0.6.63.1

### Android version

9

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on settings
3. Click on the miscellaneous button on the navigation bar.
4. I have to wait about three seconds for the miscellaneous button configuration to load. The only lag is with that specific button.
![Screenshot_20241213_153314](https://github.com/user-attachments/assets/b59cdd49-88a9-4de2-9a86-ca7fd288a982)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Fix the miscellaneous button on the settings navigation bar

**Comment by fast4x** [comment]
Is caused by logins accounts, moved to specific tab in settings, now misc load fast. Available from version 0.6.65
