### ISSUE TITLE
The covers of the songs appear cut off on Tablet Devices

### ISSUE THREAD

**Issue by EliasNavaXD** [fast4x/RiMusic#4905]
### Version of RiMusic

0.6.64

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. select the song
3. The cover appears incomplete
![Screenshot_20241213-213133](https://github.com/user-attachments/assets/64918b7e-c290-4798-873b-ecba8282ad98)

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

make the song cover look complete as on cell phones

### What more can you tell us? (Optional)

I tried to make the cover visible by setting the thumbnail size to small but the cover still looks incomplete, in addition to the fact that the app interface looks very strange on Tablets.

**Comment by EliasNavaXD** [comment]
Making the interface of cellular devices the same as that of tablets would be more comfortable, I was browsing the application interface and it really looks very strange, there are spaces that look very open in relation to the buttons and other things.

**Comment by EliasNavaXD** [comment]
Does this mean that the problem has already been solved?

**Comment by aneesh1122** [comment]
> Does this mean that the problem has already been solved?

Can you try the latest version?

**Comment by EliasNavaXD** [comment]
> > ¿Significa esto que el problema ya está solucionado?
> 
> ¿Puedes probar la última versión?

I already tried the latest version, the error was successfully solved👌
