### ISSUE TITLE
Hidden songs got "unhidden"

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#4909]
### Version of RiMusic

0.6.64

### Android version

14

### Tell us how you trigger this bug

1. Have RiMusic installed with 0.6.63 with some songs hidden
2. Update to 0.6.64
3. Open "songs" tab

### What was your expectation?

The hidden songs should remain hidden

### What more can you tell us? (Optional)

I checked in the debugger, that all songs at least `totalPlayTimeMs` = 0 (also those that where hidden previously).

**Comment by twistios** [comment]
I was able to reproduce it with the db-file that I created before the update.

**Comment by fast4x** [comment]
Fixed, avaiable from version 0.6.65
