### ISSUE TITLE
Rimusic Comes out when pressing the radio play button

### ISSUE THREAD

**Issue by 337-sehzade** [fast4x/RiMusic#4912]
### Version of RiMusic

0.6.64 by fast4x

### Android version

9

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on Play radio in history of songs that have been listened to
3. Boom! Crash happens

### Submit a video

https://github.com/user-attachments/assets/b3ae103c-d034-4ed6-a7a9-045a28af0460

### What was your expectation?

Next update this bug is gone

### What more can you tell us? (Optional)

I clicked The radio play button from the history of songs that I have listened to, but suddenly the application exits by itself,even though previously it had never happened like this

### Logs (Optional)

https://github.com/user-attachments/assets/f32a5cce-369f-402f-b739-0a2a3e4ed53b

**Comment by 337-sehzade** [comment]
Please asap for the upgrade

**Comment by fast4x** [comment]
click on info in dialog when crash, paste here the log

**Comment by fast4x** [comment]
Fixed, try custom version https://github.com/fast4x/RiMusic/tree/master/customVersion
