### ISSUE TITLE
You can't download music or albums. They said they fixed the bug but it still persists. 

### ISSUE THREAD

**Issue by Gaush737w85** [fast4x/RiMusic#4916]
### Version of RiMusic

0.6.64 by fast4x

### Android version

15

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

1

### What more can you tell us? (Optional)

ª

### Logs (Optional)

ª

**Comment by fast4x** [comment]
this bug is not reproduced
