### ISSUE TITLE
"Song cannot be played" message when I try to play any song

### ISSUE THREAD

**Issue by DuckyMcLucky** [fast4x/RiMusic#4920]
### Version of RiMusic

0.6.64

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Try to play a song
3. "Song cannot be played"
4. This isn't shown in the video, but then it says "An unknown playback error has occured"

### Submit a video

https://github.com/user-attachments/assets/abd17161-ec1b-4a85-8086-b2f09e8efb3c

### What was your expectation?

I expected to be able to play the music

**Comment by SmoothButt** [comment]
Exactly the same issue for me

**Comment by aneesh1122** [comment]
Disable youtube login

**Comment by SmoothButt** [comment]
> Disable youtube login

worked thanks a lot

**Comment by Sankeerthan13** [comment]
> Disable youtube login

Worked but now songs are playing in medium quality. 
Any method to fix this ?

**Comment by Mickael81** [comment]
![2024_12_17_18.06.18.jpg](https://github.com/user-attachments/assets/7340b5d5-e9f2-44a8-857d-3c53ff75a171)

I have exactly the same problem. ☹️

**Comment by CollegeTimeOhNo** [comment]
Having this problem but only with a handful of song. Cleared cache and reloaded songs, but no dice
