### ISSUE TITLE
Una canción no se puede reproducir no se si es esa en especial llamada "Fuck that" Nicki nicole

### ISSUE THREAD

**Issue by Cremadepan** [fast4x/RiMusic#4929]
### Version of RiMusic

0.6.64

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on song
3. Dont play
4. Skip automatically the song 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Que se reproduciera pero quedó igual

### What more can you tell us? (Optional)

Pues que también e intentado instalada sin embargo tampoco deja.

**Comment by fast4x** [comment]
disable skip on error in ui settings
