### ISSUE TITLE
[Feature]: Please add support for android tablets

### ISSUE THREAD

**Issue by farzana840** [fast4x/RiMusic#493]
### Description

The app works on tablets and large screen devices but it isn't optimised for it. The player looks bad and the buttons become unclickale due to their positioning. The padding looks off. Needs a bit of fixing
![Screenshot_20240125_135011](https://github.com/fast4x/RiMusic/assets/68196826/a0e4d737-08f9-4a4e-bb64-47226768f626)
. Only The player needs optimisation, the rest of the app is okay on tablets.  Thanks for this amazing app, really appreciate your work !

### Suggested Solution

Fixing the paddings and ppsitioning

**Comment by fast4x** [comment]
Hello, 
great feedback for tablet optimization!
Thanks for appreciation.

**Comment by fast4x** [comment]
How would you like to see it? Can you please add some details?

**Comment by farzana840** [comment]
> How would you like to see it? Can you please add some details?

Sure! For the landscape mode, you should really prefer the dual panel layout, half of the screen is player and the other half is the upcoming song list queue. That would make the most of the screen real estate  without making things cluttered.  The play will have the visualiser and the lyrics inside the album art and controls beneath it. Kinda like here: 
![b8ea6fcfe990cddd6e6a65fc7ee660fc](https://github.com/fast4x/RiMusic/assets/68196826/cf936c3c-bb91-4bca-80e8-503a75dd8c2c)

For the portrait view you should lessen the gap between song title and controls and possible bring them together. The visualiser can go to the bottom where it won't hinder the screen. See here : 

https://github.com/fast4x/RiMusic/assets/68196826/afc9e8e2-6ed9-468c-95c4-7920c6c42f4b

It doesn't look cluttered right? Cause there is no unnecessary space or padding. Trim em out. That should do it. 
This was just my take, feel free to design it your own way ;)
Again, thanks a lot for your work!

**Comment by fast4x** [comment]
So really revolutionary! LOL Thanks

**Comment by fast4x** [comment]
How many inches does your screen have?

**Comment by farzana840** [comment]
> How many inches does your screen have?

10.5 inch screen. Samsung galaxy tab a8

**Comment by fast4x** [comment]
Thanks for your suggestions

**Comment by farzana840** [comment]
> Thanks for your suggestions

Looking forward to the next release. Have a great day

**Comment by fast4x** [comment]
Small general improvement to aspect of player.
It’s just a first optimization.
Available from version 0.6.19
Ticket remain opened for next development...

**Comment by peat80** [comment]
If the landscape player gets a well deserved redesign, please make it non touch friendly too.
This way android tv users would also benefit.

Keep up the good work. 😎👌


Related Issue:
#158
