### ISSUE TITLE
Só reproduz músicas em cache ou baixadas

### ISSUE THREAD

**Issue by Ytalol43** [fast4x/RiMusic#4932]
### Version of RiMusic

0.6.64

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abra o app
2. Clique em qualquer música que não esteja baixada ou em cache
3. A música não será reproduzida deixando uma mensagem "a mídia não pode ser reproduzida" "erro desconhecido"

https://github.com/user-attachments/assets/bf4e401e-bf9f-4f83-928d-8f069dbbb2f7

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Era para a música ser reproduzida normalmente

**Comment by fast4x** [comment]
Disconnect ytm login and disable it
