### ISSUE TITLE
Cant open some playlist links

### ISSUE THREAD

**Issue by farzana840** [fast4x/RiMusic#494]
Uploading Screen_Recording_20240125_144255.mp4…

![Screenshot_20240125_143859](https://github.com/fast4x/RiMusic/assets/68196826/b5ed89d7-54df-426c-bdf8-b62158443eb0)

### Steps to reproduce the bug

Open this link in the rimusic app : https://music.youtube.com/playlist?list=PLrrmz_8mii2reFIs5z8jT-pIY7CcNcPwN&si=dRTro9oH8M8gkiPi

### Expected behavior

It should open the playlist

### Actual behavior

It keeps loading indefinitely. Other playlist open easily while this one doesn't. It also doesn't open the vimusic app.

### Screenshots/Screen recordings

Uploading Screen_Recording_20240125_144255.mp4…

### RiMusic version

0.6.18

### Android version

Android 13

### Additional information

Samsung tab a8

**Comment by ikanakova** [comment]
I think it's related to the issue #484

**Comment by fast4x** [comment]
@ikanakova No, because #484 load without problems, it could be related to the geographical area.
The link in this ticket does not load...

**Comment by ikanakova** [comment]
> @ikanakova No, because #484 load without problems, it could be related to the geographical area. The link in this ticket does not load...

Oh, I have an older version of F-Droid so I didn't even try it. From the description, it looked like the same problem to me. However, you're right in version 0.6.16.1 #484 also loads for me, but this #494 doesn't either.
