### ISSUE TITLE
The application does not open. 0.6.64

### ISSUE THREAD

**Issue by Enjavier** [fast4x/RiMusic#4944]
### Version of RiMusic

0.6.64 

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Boom! Crash happens

https://github.com/user-attachments/assets/f5cbfee9-2247-442d-b4e1-f32d30035ba6

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

No more. 

### What more can you tell us? (Optional)

I try to open the app after the latest update. A problem occurs, and it closes again. To open it, I press and hold and access it through the widget options. After that, I don’t encounter any issues. The app works normally except for the opening error.

**Comment by fast4x** [comment]
Try this custom version please 
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Donald-Win** [comment]
Issue seems to be fixed for me using custom version provided. 

Thanks
