### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Lllum** [fast4x/RiMusic#4949]
### Version of RiMusic

0.6.64

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

.

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

.

### What more can you tell us? (Optional)

All the songs I have downloaded in my playlist work but anything else doesn't work so does that mean I'm blocked? And if so what can I do to fix it or do I just wait?

**Comment by twistios** [comment]
Disable YTM login if enabled and restart the app.

**Comment by Lllum** [comment]
> Disable YTM login if enabled and restart the app.

It workeddddd thank you so much :))
