### ISSUE TITLE
RiMusic closes immediately

### ISSUE THREAD

**Issue by baddieizme** [fast4x/RiMusic#4961]
### Version of RiMusic

Newest version

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

As you can see in the video, whenever I try to open the app, it just pops up and closes immediately. It needed to long press in able to opened.

### Submit a video

https://github.com/user-attachments/assets/54dd4481-adf2-4b78-8131-6567b2943701

### What was your expectation?

The app needs to behave like what an app supposed to do when opened.

**Comment by fast4x** [comment]
Try this custom version 
https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by Rocky0035** [comment]
> Try this custom version https://github.com/fast4x/RiMusic/tree/master/customVersion

Custom version is working properly

**Comment by fast4x** [comment]
great

**Comment by Butt3rs** [comment]
Bonsoir, j'ai le même soucis sur Android impossible d'ouvrir l'application normalement, obligé de resté appuyé longuement sur l'icône et la soit faire une recherche ou allé dans la playlist etc pour pouvoir lire les musiques.

**Comment by fast4x** [comment]
> Bonsoir, j'ai le même soucis sur Android impossible d'ouvrir l'application normalement, obligé de resté appuyé longuement sur l'icône et la soit faire une recherche ou allé dans la playlist etc pour pouvoir lire les musiques.
> 

same think, download custom version
