### ISSUE TITLE
Es normal?

### ISSUE THREAD

**Issue by Baviera10** [fast4x/RiMusic#4964]
### Version of RiMusic

0.6.64

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Ver capturas de pantalla

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically
![Screenshot_20241218_204300_Device care](https://github.com/user-attachments/assets/4d1f52c0-0ccb-4dcd-8821-5a45d52190fc)
![Screenshot_20241218_204159_Device care](https://github.com/user-attachments/assets/ee33a725-fcdb-4678-97cc-665f9751b3af)

### What was your expectation?

Se puede corregir?

**Comment by fast4x** [comment]
yep, animations and much thinks can require more battery.
