### ISSUE TITLE
I can't play any song that isn't in my Playlist

### ISSUE THREAD

**Issue by Julian1535** [fast4x/RiMusic#4969]
### Version of RiMusic

Newest one

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

.

**Comment by fast4x** [comment]
disconnect and disable ytm login

**Comment by Vishcot** [comment]
> disconnect and disable ytm login 

still not working...

**Comment by fast4x** [comment]
try version from telegram group
