### ISSUE TITLE
"Hidden" option hides downloaded songs

### ISSUE THREAD

**Issue by hollywooddchi** [fast4x/RiMusic#4979]
### Version of RiMusic

v0.6.64 custom version (I had the ab-end bug)

### Android version

7.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Within the 'Songs' Tab, the 'All' subsection has a "hidden" feature which, I assume, has cached songs from previous searches but were not selected for download and saved locally. Thereby, hiding songs from view but still there should the user change their mind. 
The feature is useful, but has an issue. If you decide to show and download a song from the hidden filtered songs, when the "Hide" icon is re-enabled, the newly downloaded song is hidden again despite the fact it exists on your device. The result creates a count mismatch between the 'All' and 'Downloaded' subsections when the list is in "hidden" mode. I'm not using 'Favorites', 'Cached' & 'On Device' subsections within the 'Songs' tab.

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I'm expecting the two subsections to be equal count and viewable.

### What more can you tell us? (Optional)

It's difficult to say when this problem starting occuring. It may have always existed and I never noticed until now. The new feature of auto population of 'Artists' and 'Albums' tabs from downloaded songs has created a few new annoyance bugs but I don't believe is related to the "hidden" song flag that fails get unflagged after being downloaded.

**Comment by fast4x** [comment]
Isn't annoying, fixed downloaded songs tab
