### ISSUE TITLE
hello world. my downloaded tab has thousands of undownloaded songs 

### ISSUE THREAD

**Issue by NOBELLIST** [fast4x/RiMusic#4982]
### Version of RiMusic

0.6.64 customver

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

i dont know if its a bug or something else 

### Submit a video

https://github.com/user-attachments/assets/07be934a-8bb8-473c-aa37-5076db5fd9f9

### What was your expectation?

the downloaded tab shows me all the downloaded songs but not the undownloaded ones including the most random songs

**Comment by twistios** [comment]
This is a bug. The bug is basically the same as there was for 0.6.64 (regular release) for the "all" tab.

**Comment by fast4x** [comment]
Fixed, available from 0.6.65
