### ISSUE TITLE
Operating Error Crash

### ISSUE THREAD

**Issue by Farid-MS** [fast4x/RiMusic#4988]
### Version of RiMusic

v0.6.64

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Select Song
3. Boom! Crash happens

### Submit a video

https://github.com/user-attachments/assets/341eaf8d-e83f-4006-be61-d5f859d13e2c

### What was your expectation?

Fix Compatibility Error

### What more can you tell us? (Optional)

I am running the App on your Samsung Galaxy S21 Ultra phone, running Android 14 and One UI 6.1

**Comment by fast4x** [comment]
Fixed, available from version 0.6.65
