### ISSUE TITLE
Missing translation 

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#499]
### Steps to reproduce the bug

Can u add this missing translation ? It's not on crowdin 

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

![IMG_20240126_181855](https://github.com/fast4x/RiMusic/assets/63956787/9ddb8ed8-3d1d-4ec8-886d-34ace414e2ad)

### RiMusic version

0.6.19

### Android version

A12 MIUI 14

**Comment by NEVARLeVrai** [comment]
also sytem languague put french with emojies

**Comment by fast4x** [comment]
Fixed, just available on crowdin

**Comment by faustaahmad** [comment]
Just wait for next version for translation issue, can be late sometimes
Unless no available translation for your language, then u can request to add one & help translate 'em via crowdin

**Comment by NEVARLeVrai** [comment]
> Fixed, just available on crowdin 

![IMG_20240127_104346.jpg](https://github.com/fast4x/RiMusic/assets/63956787/06c0bffe-9a3d-4280-9e40-2caa5557b495)

Also there I think I translated quality ? But here it don't apply

**Comment by NEVARLeVrai** [comment]
@fast4x Is it possible to implement a search system in the settings? This way it avoids having to search for a parameter for a long time that you can't find.

**Comment by NEVARLeVrai** [comment]
@fast4x Is it possible to implement a search system in the settings? This way it avoids having to search for a parameter for a long time that you can't find.

**Comment by fast4x** [comment]
Maybe isn't translated on Crowdin, I'll check It, thanks

**Comment by fast4x** [comment]
> @fast4x Is it possible to implement a search system in the settings? This way it avoids having to search for a parameter for a long time that you can't find. 

Great idea, please create a task, thanks

**Comment by NEVARLeVrai** [comment]
> > @fast4x Is it possible to implement a search system in the settings? This way it avoids having to search for a parameter for a long time that you can't find.
> 
> Great idea, please create a task, thanks

Done I made it

**Comment by NEVARLeVrai** [comment]
> > @fast4x Is it possible to implement a search system in the settings? This way it avoids having to search for a parameter for a long time that you can't find. 
> 
> Great idea, please create a task, thanks 

Can u add this ![Screenshot_2024-02-09-10-55-41-739_it.fast4x.rimusic.png](https://github.com/fast4x/RiMusic/assets/63956787/b934223e-8d1d-45ca-a6c2-ccb0eb581641)

![Screenshot_2024-02-09-10-55-26-306_it.fast4x.rimusic.png](https://github.com/fast4x/RiMusic/assets/63956787/88e78635-9b0c-4f7c-bc2d-bd1f4e5ce6f1)

Missing on crowdin

**Comment by NEVARLeVrai** [comment]
> > @fast4x Is it possible to implement a search system in the settings? This way it avoids having to search for a parameter for a long time that you can't find. 
> 
> Great idea, please create a task, thanks 

![Screenshot_2024-02-10-11-36-54-415_it.fast4x.rimusic.png](https://github.com/fast4x/RiMusic/assets/63956787/377267c7-ab1a-4f4a-ab2f-24364d606230)

![Screenshot_2024-02-10-11-36-47-922_it.fast4x.rimusic.png](https://github.com/fast4x/RiMusic/assets/63956787/ecc4ff3a-3505-4fd9-b2a3-509dd69f75ea)

Also this
Default page
Use front type

**Comment by fast4x** [comment]
Don't use same old ticket please, it's more difficulty remember it.

**Comment by NEVARLeVrai** [comment]
> Don't use same old ticket please, it's more difficulty remember it.

Ok

**Comment by fast4x** [comment]
> > Don't use same old ticket please, it's more difficulty remember it.
> 
> Ok

Thanks you
