### ISSUE TITLE
Wrong icon in notification

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#5]
### Steps to reproduce the bug

The error is not tragic, but for the sake of order I mentioned it.

Open the APP and listen to music as normal. look in the notification and you will see it.

see the screenshot

### Expected behavior

the correct icon should be displayed.

### Actual behavior

an incorrect icon is displayed

### Screenshots/Screen recordings

![Screenshot_20230910-192416_1](https://github.com/fast4x/RiMusic/assets/103368536/624166d0-43a5-4fc3-8d9e-d561dce7503c)

### RiMusic version

0.1.5

### Android version

Android 12

**Comment by fast4x** [comment]
Please, if ViMusic is running, close it and try with RiMusic new version

**Comment by siggi1984** [comment]
I don't have ViMusic installed on my phone at all.  I only listen with RiMusic.

**Comment by fast4x** [comment]
Should be fixed, available in next release 0.6.4

**Comment by siggi1984** [comment]
After the last update the error is back.

**Comment by fast4x** [comment]
I’m sorry, I’ll fix it

**Comment by fast4x** [comment]
Fixed, available from version 0.6.7
