### ISSUE TITLE
[Feature]: Redesigned UI Concept

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#50]
### Description

I would like to propose a redesign for the UI of RiMusic. I am a fan of the app, but I think the current menus are not as user-friendly as they could be. I have created a redesign using Paint.net, which is inspired by RiMusic, ViMusic, and YouTube Music.

![image](https://github.com/fast4x/RiMusic/assets/104271365/0f696ea5-ecae-47dd-a596-fe0ee0368d2c)
![image](https://github.com/fast4x/RiMusic/assets/104271365/56ca9a3b-1f35-420c-ba1b-1ccdb07c9da8)
![image](https://github.com/fast4x/RiMusic/assets/104271365/08443313-aab4-40ad-a409-bd996f2e30e2)
![image](https://github.com/fast4x/RiMusic/assets/104271365/c93b26c4-5975-44d8-8ec1-6c2fea87a631)
![image](https://github.com/fast4x/RiMusic/assets/104271365/86dc794f-62ba-41fb-9988-a586ebc7681b)

### Suggested Solution

Player:
Changed the disposition of certain elements to feel less filled and added the share button next to the heart for fast sharing
Made the bottom line rounder and added a line to show that it can be pulled up

Songs list:
Moved the random order button to the bottom line and centered the "to the top" button so that it is reachable with both hands
Added a heart icon to the album cover to easily identify liked music

Music Options:
Rearranged the buttons, added the music length, and made it rounder

Quick Picks and other similar menus:
Centered and enlarged the name for easy reading

Moved the search button to the top to fill the missing spot
Playlist:
Removed the round "add playlist" button and made it like the favorites and offline buttons
Centered the arrange playlist buttons

Bottom player:
Made it rounder and made the seekbar more visible

### Additional Context

I am not a programmer, so I cannot contribute to the development of RiMusic. However, I believe that my redesign would be a valuable addition to the app. I am happy to provide any additional information or redesigns if you need.

**Comment by fast4x** [comment]
Wow! It’s a very nice job, I love it! Your contribution is welcome.

**Comment by NEVARLeVrai** [comment]
> Wow! It’s a very nice job, I love it! Your contribution is welcome.

What now ? So new UI ?

**Comment by fast4x** [comment]
It is an abstract concept, a model, a vision

**Comment by NEVARLeVrai** [comment]
> It is an abstract concept, a model, a vision

My friend can do it again for all over the ui he has time lol if you are ever interested

**Comment by OrangeZXZ** [comment]
> > It is an abstract concept, a model, a vision
> 
> My friend can do it again for all over the ui he has time lol if you are ever interested 

Yes I don't mind remaking the Concept if there are mistakes, and i also have time to make aditional ideas like settings, etc...

But if he doesn't plan to use it it's fine because im not the owner of the fork

**Comment by fast4x** [comment]
Everyone is free to express a concept, try to improve, it is an added value.
This concept is fine, if you have another idea, go!

**Comment by fast4x** [comment]
Would be great if you add font name, size, background and foreground color code etc...

**Comment by ikanakova** [comment]
>Would be great if you add font name, size, background and foreground color code etc...

It should be a [Multilingual font](https://localizely.com/blog/multilingual-fonts/), otherwise it could be a problem in languages other than English and ideally open source for a future release on F-Droid.

**Comment by fast4x** [comment]
Yes, it could actually be a problem. However, the choice of font can be made by the user...

**Comment by fast4x** [comment]
Partially implemented, improved layout, removed many floating buttons and changed to buttons.
The miniplayer has also been improved.

**Comment by OrangeZXZ** [comment]
I just got an idea where the Songs List d'osent open all the way up for easy reach

![image](https://github.com/fast4x/RiMusic/assets/104271365/fb63c240-c7cc-43ac-a79b-152d39075f2c)

**Comment by OrangeZXZ** [comment]
> It should be a [Multilingual font](https://localizely.com/blog/multilingual-fonts/), otherwise it could be a problem in languages other than English and ideally open source for a future release on F-Droid.

I fond a cool font that can be tested Im not sure if it is an [Multilingual font](https://localizely.com/blog/multilingual-fonts/) but i think it would look great.

Google Font: [Rubik](https://fonts.google.com/specimen/Rubik)
Github: [Rubik](https://github.com/googlefonts/rubik)

**Comment by ikanakova** [comment]
I took a cursory look at the glyps and I think it's multilingual 🙂 And I like it.

**Comment by fast4x** [comment]
Let’s do one thing, i try it directly on RiMusic and evaluate it. It may also be an additional font to change from the settings.

I attach a screenshot just ready 😉

**Comment by OrangeZXZ** [comment]
It would be possible to create a discussion made to show UI concepts instead of comunicate il an issue?

**Comment by fast4x** [comment]
Sure, area discussions are just available, you can create it
