### ISSUE TITLE
player

### ISSUE THREAD

**Issue by senolfndk** [fast4x/RiMusic#502]
### Steps to reproduce the bug

middle button bleeds to the right and doesn't match the exact album color

### Expected behavior

middle button bleeds to the right and doesn't match the exact album color

### Actual behavior

middle button bleeds to the right and doesn't match the exact album color

### Screenshots/Screen recordings

![Screenshot_20240126-232142](https://github.com/fast4x/RiMusic/assets/52818836/1b2b43da-fbe6-46c9-a645-577a49094200)

### RiMusic version

0.6.19

### Android version

android 12

### Additional information

middle button bleeds to the right and doesn't match the exact album color

**Comment by fast4x** [comment]
Try to increase thumbnail size on appearance settings

**Comment by fast4x** [comment]
Background on play button is new feature...

**Comment by senolfndk** [comment]
> Try to increase thumbnail size on appearance settings

**Comment by senolfndk** [comment]
> Try to increase thumbnail size on appearance settings

https://github.com/fast4x/RiMusic/assets/52818836/b4e91c8d-fba8-4627-b7f9-90f99e1166a9

**Comment by senolfndk** [comment]
> Background on play button is new feature...

Hmm ok

**Comment by NEVARLeVrai** [comment]
> Background on play button is new feature...

Also could u look in it but player on a small screen like my mother's phone the buttons are very small and it's just almost impossible to click on them

**Comment by fast4x** [comment]
Interestly, I'll fix it, thanks


How many inch have smartphone?

**Comment by ndavid3** [comment]
I have the same problem, the player buttons are not simetric
6.7" with default settings in app

![Screenshot_20240127_121902.jpg](https://github.com/fast4x/RiMusic/assets/113303831/d15558f8-7842-486f-ab26-e83ace89ca60)

**Comment by fast4x** [comment]
I’m preparing a custom version that I’ll upload here later.

**Comment by fast4x** [comment]
Please, try this custom version, and after send feedback.
Download from website https://rimusic.xyz/download/

**Comment by senolfndk** [comment]
> Lütfen bu özel sürümü deneyin ve geri bildirim gönderdikten sonra. https://rimusic.xyz/download/ web sitesinden indirin[](https://rimusic.xyz/download/)
the link does not open

**Comment by fast4x** [comment]
I'm afraid but i confirm that link work

**Comment by senolfndk** [comment]
![Ekran görüntüsü 2024-01-28 040315](https://github.com/fast4x/RiMusic/assets/52818836/258d70e2-952a-4fe7-87e0-0ddd53133866)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.20
