### ISSUE TITLE
Sort songs by recently played

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#505]
### Description

Currently we have 4 type of sorting
Left to Right
- Last/Recently played (idk this one, long press doesnt pop any info)
- Listening duration
- Name/Alphabet
- Date added (new/old)

### Suggested Solution

Songs list can be sorted into recently played, it'll benefit Quick Picks too since current "By Last played song" behavior desnt work as expected

### Alternatives

close this issue x_x

### Additional Context

![Screenshot_20240127-070429](https://github.com/fast4x/RiMusic/assets/45221211/472e95f8-b2f3-4567-b06b-f7a452195b17)

**Comment by fast4x** [comment]
I don't understand

**Comment by faustaahmad** [comment]
Edited

**Comment by fast4x** [comment]
Last played sort it's just available.
Last played in song list match with Quick Picks after played it...

**Comment by fast4x** [comment]
Improved most and last played
Available from version 0.6.20
