### ISSUE TITLE
Inconsistent font width/style inside Album/Playlist

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#508]
### Steps to reproduce the bug

Both Rubik & Poppins has similar style, so idk if it was width or style difference
All album-like & playlist, song title was on normal font width
While Songs list & Tips (Quick Picks) has bold font width

### Expected behavior

They should have same font width (except on player)

### Actual behavior

They have different width

### Screenshots/Screen recordings

<table>
<tbody><tr>
<th>Songs list<img src="https://github.com/fast4x/RiMusic/assets/45221211/3bd76e52-84b5-4ed8-8779-f9c8460f9bae"></img></th>
<th>Album<img src="https://github.com/fast4x/RiMusic/assets/45221211/5870bdcf-638c-4d20-8217-dd7bd4797534"></img></th>
<th>Artist songs<img src="https://github.com/fast4x/RiMusic/assets/45221211/4688559f-6a88-4498-b193-05d9f6556b0d"></img></th>
<th>Library Playlist<img src="https://github.com/fast4x/RiMusic/assets/45221211/a656ac2d-8428-438b-a1f2-c2eccec7aa51"></img></th>
</tr></tbody>
<tbody><tr>
<th>Quick Picks<img src="https://github.com/fast4x/RiMusic/assets/45221211/1ab6c692-b050-4d42-854e-f85b96d77c0c"></img></th>
<th>Statistics<img src="https://github.com/fast4x/RiMusic/assets/45221211/844f880e-aff4-497d-a95c-658b21b8fcac"></img></th>
<th>Player Playlist<img src="https://github.com/fast4x/RiMusic/assets/45221211/91f5c161-c798-462f-82ea-c578b74b8b75"></img></th>
<th><img src=""></img></th>
</tr></tbody>
</table>

### RiMusic version

0.6.19

### Android version

Android 11

**Comment by fast4x** [comment]
Fixed, available from version 0.6.20
