### ISSUE TITLE
[Feature]: Tooltips for UI buttons

### ISSUE THREAD

**Issue by ghost** [fast4x/RiMusic#509]
### Description

There are many icons/buttons in the UI, and it's hard to know/remember what they're all for.

For example:
![IMG_20240127_124115](https://github.com/fast4x/RiMusic/assets/2385329/4ba3feb6-d963-4014-84e3-a8402d64662a)

Instead of needing to check the wiki all the time, it'd be nice to have tooltips/popups that name/describe each button.

### Suggested Solution

The tooltip/popup should appear when long-pressing on a button. It should appear in a position such that it's easily visible, especially for fat-fingered users (either a good distance from the button being pressed, or at the top or bottom of the screen).

### Alternatives

There's an FAQ entry in the wiki that describes icons: https://github.com/fast4x/RiMusic/wiki/FAQs#-icon-explanation

However:
- It requires leaving the app to view, so you're constantly switching back and forth
- It doesn't appear to be up-to-date
- It's hard to read in dark mode (black icons on a dark BG)

**Comment by sayyid5416** [comment]
Much needed

**Comment by fast4x** [comment]
Implemented, available from version 0.6.32
