### ISSUE TITLE
[Feature]: Add Romanian as a Language

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#51]
### Description

I would like Romanian to be added that way i can work on it

### Suggested Solution

- Add the language "Romanian"

**Comment by fast4x** [comment]
- Download this file https://github.com/fast4x/RiMusic/blob/master/app/src/main/res/values/strings.xml  
- Open it with a text editor, not Word or similar Word processor
Translate the text 
- Attach updated file here

How to translate, example:
<string name="cancel">**Cancel**</string>
Translate only text container from >......<

**Comment by fast4x** [comment]
- Download this file https://github.com/fast4x/RiMusic/blob/master/app/src/main/res/values/strings.xml  
- Open it with a text editor, not Word or similar Word processor
Translate the text 
- Attach updated file here

How to translate, example:
<string name="cancel">**Cancel**</string>
Translate only text contained from >......<

**Comment by NEVARLeVrai** [comment]
> - Download this file https://github.com/fast4x/RiMusic/blob/master/app/src/main/res/values/strings.xml  
> - Open it with a text editor, not Word or similar Word processor
> Translate the text 
> - Attach updated file here
> 
> How to translate, example:
> `<string name="cancel">text to be translated</string>`
> Translate only text contained from >......<
> 
> 

U can add the folder an XML file so he can pull and I explain how do it its my friend

**Comment by fast4x** [comment]
Ah ok!

**Comment by ikanakova** [comment]
I recommend this program to translate strings.xml file: https://github.com/SubtitleEdit/XmlContentTranslator

**Comment by NEVARLeVrai** [comment]
> I recommend this program to translate strings.xml file: https://github.com/SubtitleEdit/XmlContentTranslator It also integrates the Google Translator.

I edit directly on the file in github

**Comment by ikanakova** [comment]
> I edit directly on the file in github

I used to too, but then I came across this app. Now you just download the xml, translate - it's perfect for non-programmers - and edit (replace all) the xml.

**Comment by fast4x** [comment]
> > * Download this file https://github.com/fast4x/RiMusic/blob/master/app/src/main/res/values/strings.xml
> > * Open it with a text editor, not Word or similar Word processor
> >   Translate the text
> > * Attach updated file here
> > 
> > How to translate, example:
> > `<string name="cancel">text to be translated</string>`
> > Translate only text contained from >......<
> 
> U can add the folder an XML file so he can pull and I explain how do it its my friend

Added!

**Comment by OrangeZXZ** [comment]
I finished the Romanian Translation
