### ISSUE TITLE
[Feature]: Pause scrolling song title at end

### ISSUE THREAD

**Issue by BWPanda** [fast4x/RiMusic#510]
### Description

When enabled (which is the default setting), long song titles scroll slowly right to left so you can read them. However as soon as they reach the end they jump back quickly to the beginning. This is jaring and can make it hard to read...

### Suggested Solution

When the scrolling text reaches the end, it should pause for a second or two, before jumping back to the beginning.

### Alternatives

Alternatively, I've seen other players where, once the text reaches the end, it starts scrolling back the other way. But I believe it does still have a pause.

**Comment by fast4x** [comment]
Implemented reverse scrolling text on player, available from version 0.6.20
