### ISSUE TITLE
Option toggle lyrics triggers on every blank area on modern player when background is set to "blurred song cover"

### ISSUE THREAD

**Issue by Egezenn** [fast4x/RiMusic#5103]
### Version of RiMusic

0.6.65.1

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

When you tap an area that has no elements you trigger the toggle lyric action.

### What was your expectation?

Action to only trigger when it's tapped on the thumbnail, as it's description suggests.

**Comment by Egezenn** [comment]
I guess this is related to #1142? 
Maybe we could expand the trigger area but not to work on everywhere?

**Comment by aneesh1122** [comment]
You must be using the 'blurred song cover' as the background

**Comment by aneesh1122** [comment]
Fixed. Now if you have enabled the option to show thumbnail then touching anywhere out of the thumbnail will not enable/disable lyrics.
