### ISSUE TITLE
[Feature]: Open yt link in app

### ISSUE THREAD

**Issue by claxcian** [fast4x/RiMusic#5109]
### Description

Is possible to open yt link in app automatic?

### Suggested Solution

Is i click in a yt music link and open in app

**Comment by 6XChen** [comment]
![Screenshot_20241229_211840_Settings.png](https://github.com/user-attachments/assets/e3ce2f79-4c87-42d2-aea6-4b602fb4c416)

Ez

**Comment by 6XChen** [comment]
![Screenshot_20241229_211910_Settings.png](https://github.com/user-attachments/assets/4f76d8e1-1d67-40eb-ac6d-734cd6420d4d)

> ![Screenshot_20241229_211840_Settings.png](https://github.com/user-attachments/assets/e3ce2f79-4c87-42d2-aea6-4b602fb4c416)
> 
> Ez
