### ISSUE TITLE
[FEATURE] : Search System in Settings

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#511]
### Description

A search system in settings

### Suggested Solution

A search system in the settings to be able to find the settings you are looking more fast and flexible. Like in android settings

![Screenshot_2024-01-27-10-50-33-329_com android settings](https://github.com/fast4x/RiMusic/assets/63956787/8e1d4427-9e3c-439a-b72a-80ac220d5317)

**Comment by fast4x** [comment]
Implemented in ui and appearance settings, available from version 0.6.26
