### ISSUE TITLE
Video player on supported lists

### ISSUE THREAD

**Issue by abdulkarimx1** [fast4x/RiMusic#512]
### Description

Video tab doesn't play videos, only shows thumbnail of the video.

### Suggested Solution

Would it be possible to make the player support also video codecs implemented in the app so user can watch video directly from video tab 

### Alternatives

![Screenshot_20240127-140509_RiMusic](https://github.com/fast4x/RiMusic/assets/105733146/3d4de39a-0931-4b41-b0da-17e9fb84ff5e)

**Comment by ikanakova** [comment]
https://github.com/fast4x/RiMusic/wiki/FAQs#-how-to-play-video
