### ISSUE TITLE
Playing external storage videos from the player

### ISSUE THREAD

**Issue by abdulkarimx1** [fast4x/RiMusic#513]
### Description

We can't play videos on external storage from player.

### Suggested Solution

Would it be possible to implement a feature were we can play external storage videos ( offline videos ) directly from rimusic? I believe this feature will be very convenient and will make users rest from always switching between apps just to play a video

**Comment by ikanakova** [comment]
This is **music** player. Videos are not planned yet, see [FAQ](https://github.com/fast4x/RiMusic/wiki/FAQs#-how-to-play-video).
