### ISSUE TITLE
[BUG] : Weird player size on low screen size

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#514]
### Steps to reproduce the bug

On phones with a small screen the buttons are too small 

### Expected behavior

Normally it should fit a good size depending on the screen size 

### Actual behavior

They are too small so quite complicated to click on my mom's phone

### Screenshots/Screen recordings

![Screenshot_20240127-110352_110544](https://github.com/fast4x/RiMusic/assets/63956787/47e408a1-eca0-4110-b892-a47d4dc99e08)
![Screenshot_20240127-110440_110540](https://github.com/fast4x/RiMusic/assets/63956787/020da5cd-2ac7-4e5a-996d-5122de3c5d92)

### RiMusic version

0.6.19

### Android version

A7 EMUI 5.0.3

**Comment by 6XChen** [comment]
![Screenshot_20240127_173206.png](https://github.com/fast4x/RiMusic/assets/104673054/08896a26-32c7-427b-9e19-ae52f9424a6c)

Try to set it in thumbnail size

**Comment by fast4x** [comment]
I’m preparing a custom version that I’ll upload here later.

**Comment by NEVARLeVrai** [comment]
> Please, try this custom version, and after send feedback.
> Download from website https://rimusic.xyz/download/

![IMG_20240127_194041.jpg](https://github.com/fast4x/RiMusic/assets/63956787/55ae4126-8ce2-4dd4-9469-018458edd100)

Sorry my camera is a little dirty

**Comment by fast4x** [comment]
Okay, so the problem is the new bottom bar...

**Comment by NEVARLeVrai** [comment]
> Okay, so the problem is the new bottom bar...

This was already before so the buttons adapt to the size of the page, what you can do for small screens to have larger buttons? Or do something customizable for small screens?

**Comment by fast4x** [comment]
I'll try to change bottom bar with low resolution display...

**Comment by fast4x** [comment]
Custom version updated, try please, would be improved now
Download from website https://rimusic.xyz/download/

**Comment by NEVARLeVrai** [comment]
> Custom version updated, try please, would be improved now
> Download from website https://rimusic.xyz/download/

![IMG_20240128_123219.jpg](https://github.com/fast4x/RiMusic/assets/63956787/0155cbb7-3c53-45ae-88c0-0763499ea3d5)

Look fine now

**Comment by fast4x** [comment]
Yes, i agree, Will be done, thanks

**Comment by fast4x** [comment]
Fixed, available from version 0.6.20
