### ISSUE TITLE
Modern black

### ISSUE THREAD

**Issue by wunder20v** [fast4x/RiMusic#517]
### Steps to reproduce the bug

Go to settings, click appearance, click theme modern black

### Expected behavior

It should be all black.

### Actual behavior

![Screenshot_2024-01-27-13-57-40-03_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/156642707/d9d2de69-fe30-4fa4-84d7-3453b992a490)

### RiMusic version

0.6.19

### Android version

Android 14

**Comment by fast4x** [comment]
Hi, total black Is Pure black. Modern has green color combination.

**Comment by wunder20v** [comment]
I mean de lower bar, it's not black

**Comment by fast4x** [comment]
![Screenshot_2024-01-27-14-24-50-551_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/1484476/4a0a79d2-72e5-4013-b421-419792138b6c)

Look this is actual Pure black theme.

**Comment by wunder20v** [comment]
Can't you do the same for modern black, that would look better.

**Comment by fast4x** [comment]
Of course it is possible, but what would be the difference with Pure Black?

**Comment by wunder20v** [comment]
It Is okay

**Comment by fast4x** [comment]
I'll try it

**Comment by fast4x** [comment]
Please, try this custom version, and after send feedback.
Download from website https://rimusic.xyz/download/

**Comment by wunder20v** [comment]
It doesn't work, the app keeps quitting

**Comment by fast4x** [comment]
But does the app not open or go wrong when you do something?

**Comment by wunder20v** [comment]
When I play a song

**Comment by fast4x** [comment]
Check permissions...

**Comment by wunder20v** [comment]
I have granted all permissions
