### ISSUE TITLE
Can't download cached song

### ISSUE THREAD

**Issue by 1xFF** [fast4x/RiMusic#521]
### Steps to reproduce the bug

1. Listen to entirety of song
2. Once added to cache, try to download it

### Expected behavior

To move songs that are cached into the downloaded page.

### Actual behavior

Download button is completely unresponsive and stuck in "downloaded" state.

### RiMusic version

0.6.19

### Android version

GrapheneOS 2024011600 (Android 14 r20)

### Additional information

Unless cache is set to unlimited, cache is temporary.
Even if a song is cached, you might want to ensure it never gets removed locally by moving it to downloaded.

**Comment by fast4x** [comment]
Isn't possible, cached isn't downloaded, if you want to download decrease or disable cache player and use download function.

**Comment by 1xFF** [comment]
That may be the case now, but I don't think that should be the intended behavior. 
Because:
1. You can't download a song if you've EVER listened to it before, this is extremely confusing for the user
2. The download button gives no feedback to the user as to why it's not working
3. Cache ideally stores songs recently or frequently played so they don't have to get pulled from the internet, whereas downloaded is user specified songs to never remove from the cache if it's full (I know its not actually the cache but that's the idea behind it.) These are both systems that should be able to work at the same time.

If this isn't fixed then I think either downloaded or cached should be disabled by default, as the download feature is practically inoperable with cache enabled.

**Comment by fast4x** [comment]
It's normally that if you want control on Song  download it's necessary to disable automatic cache used by player...

**Comment by 1xFF** [comment]
I understand that now, but a user has no way of knowing that's how RiMusic works. The problem is the default settings come with cache enabled AND there is still a download button that doesn't work.

***If these features can't work at the same time then they shouldn't be enabled at the same time.***


But having cache and downloaded at the same time is both possible and normal in other apps, it should be implemented in RiMusic. YouTube music for example caches songs as you listen to them, but you can download playlists for permanent offline play.

**Comment by ikanakova** [comment]
> I understand that now, but a user has no way of knowing that's how RiMusic works. The problem is the default settings come with cache enabled AND there is still a download button that doesn't work.
> 
> If these features can't work at the same time then they shouldn't be enabled at the same time.
> 
> But having cache and downloaded at the same time is both possible and normal in other apps, it should be implemented in RiMusic. YouTube music for example caches songs as you listen to them, but you can download playlists/songs for permanent offline play.

That's why I think that downloading and caching should be completely merged and called downloading to cache so that users are not confused with the classic downloading e.g. to mp3. And if a song is downloaded to the cache then it can be manually deleted with the download button and if I want to download a song to the cache, I can also do it with the button. And I can choose whether to download songs manually + automatically or just manually.

I don't agree with downloading music e.g. to mp3, I think RiMusic shouldn't be used for that, because it's an application for listening to music and not downloading.

**Comment by fast4x** [comment]
> > I understand that now, but a user has no way of knowing that's how RiMusic works. The problem is the default settings come with cache enabled AND there is still a download button that doesn't work.
> > 
> > If these features can't work at the same time then they shouldn't be enabled at the same time.
> > 
> > But having cache and downloaded at the same time is both possible and normal in other apps, it should be implemented in RiMusic. YouTube music for example caches songs as you listen to them, but you can download playlists/songs for permanent offline play.
> 
> That's why I think that downloading and caching should be completely merged and called downloading to cache so that users are not confused with the classic downloading e.g. to mp3. And if a song is downloaded to the cache then it can be manually deleted with the download button and if I want to download a song to the cache, I can also do it with the button. And I can choose whether to download songs manually + automatically or just manually.
> 
> I don't agree with downloading music e.g. to mp3, I think RiMusic shouldn't be used for that, because it's an application for listening to music and not downloading.

Okay, you’ve convinced me, let’s move towards the unification of the two things that become "saved songs"

**Comment by fast4x** [comment]
Thanks anyway for the idea, but it’s not planned, It Will be come unified.
