### ISSUE TITLE
Toolbar offcentres

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#522]
### Steps to reproduce the bug

1. Select any song
2. Click on download
3. Toolbar offcentres 

### Expected behavior

Toolbar should stayed at his position 

### Actual behavior

But it offcentres 

### Screenshots/Screen recordings

Before:
![Screenshot_20240127-230543~2](https://github.com/fast4x/RiMusic/assets/120176369/700e028d-21c8-4f3e-a6d3-2b0888713f08)

After:
![Screenshot_20240127-230549~2](https://github.com/fast4x/RiMusic/assets/120176369/1bd336ca-e113-4810-b253-457f7470278c)

### RiMusic version

0.6.19

### Android version

14

### Additional information

Although toolbar offcentres but i cmes to centre where it shoul be

**Comment by fast4x** [comment]
Try this custom version
https://rimusic.xyz/download

**Comment by Logan7899** [comment]
> Try this custom version https://rimusic.xyz/download

It is crashing

**Comment by fast4x** [comment]
Retry, updated

**Comment by fast4x** [comment]
Fixed, available from version 0.6.20

**Comment by faustaahmad** [comment]
Tested on latest dev build (link above)

![Screenshot_20240128-213658](https://github.com/fast4x/RiMusic/assets/45221211/96898388-32ee-4667-85ae-d8a4dcf4db8a)
![Screenshot_20240128-214010](https://github.com/fast4x/RiMusic/assets/45221211/c5eeccb3-dc24-4843-a043-a1090912f914)
