### ISSUE TITLE
[Feature]: The logo and notification section of the song album can be like Spotify

### ISSUE THREAD

**Issue by LeonDayi** [fast4x/RiMusic#523]
### Description

The logo and notification section of the song album can be like Spotify. This way the song album logo will look better.
![IMG_20240127_202906](https://github.com/fast4x/RiMusic/assets/157779988/eb8148f2-c68c-4309-967b-86645eda98fd)

### Suggested Solution

The logo and notification section of the song album can be like Spotify. We can still see if we like the song or not.

**Comment by Logan7899** [comment]
> ### Description
> The logo and notification section of the song album can be like Spotify. This way the song album logo will look better. ![IMG_20240127_202906](https://private-user-images.githubusercontent.com/157779988/300195876-eb8148f2-c68c-4309-967b-86645eda98fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNzg3MjAsIm5iZiI6MTcwNjM3ODQyMCwicGF0aCI6Ii8xNTc3Nzk5ODgvMzAwMTk1ODc2LWViODE0OGYyLWM2OGMtNDMwOS05NjdiLTg2NjQ1ZWRhOThmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxODAwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWEyYjhjZGM5MzA3MzE2Y2YwYjVhMjM5OWI2YjVlZDQ2M2QzMzc4MzFhMzI3ZjZkNjQwN2FlZTdiNzFhYTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d05s30aaHzVa3pa3lWB-VGDzUi7jFKUbBBkloZiGl68)
> 
> ### Suggested Solution
> The logo and notification section of the song album can be like Spotify. We can still see if we like the song or not.
> 
> ### Alternatives
> _No response_
> 
> ### Additional Context
> _No response_

I know Spotify is good but the problem is that if you change the logo like Spotify the app will loose its originality and also  notification sections are different os
![Screenshot_20240127-233254](https://github.com/fast4x/RiMusic/assets/120176369/f6a446bc-dcc0-4b8a-aa4d-5530cdf6438b)

I hope you understood

**Comment by fast4x** [comment]
RiMusic isn't Spotify

**Comment by fast4x** [comment]
Thanks anyway for the idea, but it’s not planned.
