### ISSUE TITLE
The location of the Back - Play/Pause - Forward buttons is broken

### ISSUE THREAD

**Issue by LeonDayi** [fast4x/RiMusic#524]
### Steps to reproduce the bug

I did not do anything.

### Expected behavior

The location of the Back - Play/Pause - Forward buttons is broken. It should line up with the line showing how many minutes the song is and what minute it is in, and match the current theme by removing the slight white area behind Play/Pause. 
![Ekran görüntüsü 2024-01-27 205624](https://github.com/fast4x/RiMusic/assets/157779988/a8ed0ca8-da6e-4f87-8a30-99a693683bab)

### Actual behavior

The location of the Back - Play/Pause - Forward buttons is broken. There was no problem in the previous version, but this problem appeared in the new version. 
![IMG_20240127_200950](https://github.com/fast4x/RiMusic/assets/157779988/ca763918-ea23-423f-b583-3515fc874fd6)

### RiMusic version

0.6.19

### Android version

Android 8/EMUI 8

**Comment by fast4x** [comment]
Try this custom version please
https://rimusic.xyz/download
Send feedback please

**Comment by fast4x** [comment]
Fixed, available from version 0.6.20
