### ISSUE TITLE
Set tap Lyrics enabled when using "ViMusic" interface

### ISSUE THREAD

**Issue by Uneccessary** [fast4x/RiMusic#525]
### Steps to reproduce the bug

1. play any song
2. Click on the thumnail
3. Nothing happens

### Expected behavior

1. Play any song
2. Click on the thumbnail
3. Lyrics will be loaded just like in ViMusic

### Actual behavior

Lyrics doesn't load when clicking on the thumbnail when using ViMusic interface

### RiMusic version

0.6.19

### Android version

Android 11

**Comment by ikanakova** [comment]
This is not a bug. You have to enable it in the settings:
![Screenshot_20240127_204156_1](https://github.com/fast4x/RiMusic/assets/38765251/7b28f2e0-f55f-4e6d-81a2-e9a01e08cbd4)

**Comment by Uneccessary** [comment]
My bad, sorry. I literally looked through all settings multiply times and did not see this, suggestion: It auto-enables when choosing ViMusic as interface.

**Comment by fast4x** [comment]
Ok, Will be done.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.20
