### ISSUE TITLE
[Feature]: Need a lot improvement. Vi music still holds my heart 

### ISSUE THREAD

**Issue by Rajeshwarraj** [fast4x/RiMusic#528]
### Description

This App and it's functionalities are awesome in comparison to Vimusic but it's design, in-app animations are horrible. It has so many bugs and sometimes crashes eventually. I am really impressed that Vi music is continuing it's journey in the name of Ri Music. But Vi music is generally known for it's simple interface and clutter free design, it's good that you have added an option to download music but I don't think it is that practical for me. Cache-ing works for me and so for most!

### Suggested Solution

I just wanna say please make this clean and replace those horrible in-app animations and provide an option to change that green colour. I know it's Ri Music's theme but it's annoying. Try to make this app simple Instead of this rocketry simulation. I am Impressed overall because by the time I am writing this review, Ri music ages only 5 months. So, I guess it's kinda cool. Good Luck to devs!

**Comment by Logan7899** [comment]
> ### Description
> This App and it's functionalities are awesome in comparison to Vimusic but it's design, in-app animations are horrible. It has so many bugs and sometimes crashes eventually. I am really impressed that Vi music is continuing it's journey in the name of Ri Music. But Vi music is generally known for it's simple interface and clutter free design, it's good that you have added an option to download music but I don't think it is that practical for me. Cache-ing works for me and so for most!
> 
> ### Suggested Solution
> I just wanna say please make this clean and replace those horrible in-app animations and provide an option to change that green colour. I know it's Ri Music's theme but it's annoying. Try to make this app simple Instead of this rocketry simulation. I am Impressed overall because by the time I am writing this review, Ri music ages only 5 months. So, I guess it's kinda cool. Good Luck to devs!
> 
> ### Alternatives
> _No response_
> 
> ### Additional Context
> _No response_

Yaa you are right. I think @fast4x needs to add finishing touches before adding new features

**Comment by fast4x** [comment]
Hi, thank you for your sincerity. 
Can you give me an example of horrible animation in the app? 
And instead of the color green, what color would you like?

**Comment by siggi1984** [comment]
> ### Description
> 
> This App and it's functionalities are awesome in comparison to Vimusic but it's design, in-app animations are horrible. It has so many bugs and sometimes crashes eventually. I am really impressed that Vi music is continuing it's journey in the name of Ri Music. But Vi music is generally known for it's simple interface and clutter free design, it's good that you have added an option to download music but I don't think it is that practical for me. Cache-ing works for me and so for most!
> ### Suggested Solution
> 
> I just wanna say please make this clean and replace those horrible in-app animations and provide an option to change that green colour. I know it's Ri Music's theme but it's annoying. Try to make this app simple Instead of this rocketry simulation. I am Impressed overall because by the time I am writing this review, Ri music ages only 5 months. So, I guess it's kinda cool. Good Luck to devs!
> ### Alternatives
> 
> _No response_
> ### Additional Context
> 
> _No response_

Then you should take a look at this fork, which has a super new function and is still simple and sleek at the same time.
