### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by kapitan-Prodigy** [fast4x/RiMusic#529]
### Steps to reproduce the bug

When player is stopped for 3-5 minutes, the app crashes. As well as when connected to a Bluetooth device gets disconnected and reconnects, app tends to crash there much more frequently. 

### Expected behavior

Media continues to play once Bluetooth is reconnected

### Actual behavior

App crashes everytime you try and play current song. 

### RiMusic version

0.6.19

### Android version

Android 14

**Comment by fast4x** [comment]
Hi
https://github.com/fast4x/RiMusic/wiki/FAQs#-why-does-the-app-close-automatically-after-i-pause-it-for-a-while

**Comment by kapitan-Prodigy** [comment]
Invincible service is enabled. I'll disconnect and reconnect to Bluetooth within 1-2 minutes and the player will dissappear and when opening the app through recent apps, it'll crash and restart.

**Comment by fast4x** [comment]
Ok I'll check it

**Comment by fast4x** [comment]
Added new permission for android 14, available from 0.6.20
