### ISSUE TITLE
Sorting alphabetically in playlists is case sensitive

### ISSUE THREAD

**Issue by CheeseFort** [fast4x/RiMusic#530]
### Steps to reproduce the bug

When playlists saved to the library are sorted alphabetically, they are sorted case sensitive. Because songs are usally named in title case, it can be hard to notice. The best way to see this behavior is with a song that starts with a lowercase letter. It will appear at the end on the playlist following all the uppercase songs.

### Expected behavior

I assume sorting alphabetically is not supposed to be case sensitive, and arange songs a-z ignoring case. (Or z-a if its set to desending)

### Actual behavior

Playlists are actually sorted A-Z, then a-z (I don't know how non-letter characters figure into that). This can produce strange behavior like the aforementioned lowercase songs appearing at the end of the playlist. Another example I can give is "A Man Without Love" appearing *before* "A Man for All Seasons" even though W (without) is *after* F (for) in the alphabet. 

### Screenshots/Screen recordings

![signal-2024-01-27-23-19-32-230](https://github.com/fast4x/RiMusic/assets/110061484/719013ee-3a62-4bf1-91ff-2753438fe044)

### RiMusic version

0.6.19

### Android version

13

**Comment by fast4x** [comment]
Fixed, available from version 0.6.20
