### ISSUE TITLE
Some changes

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#531]
### Description

1. App animations:
App opening splash screen and animations im VIMusic

https://github.com/fast4x/RiMusic/assets/120176369/7a27fb89-e220-4ba6-830c-131011c95065

App opening splash screen and animations in RIMusic:

https://github.com/fast4x/RiMusic/assets/120176369/6ecb0afe-4159-4ba2-97df-71996528ba24

2. Instead showing artist images in three dot, u can show it in artist box
![Picsart_24-01-27_23-44-15-614](https://github.com/fast4x/RiMusic/assets/120176369/f394c738-0cd9-430b-9ea2-b3248027432f)

3.toolbar also goes up when swiping up queue
![Picsart_24-01-28_00-19-36-962](https://github.com/fast4x/RiMusic/assets/120176369/3a8cac37-af57-4345-8337-ff79ae61086a)

4.pleae fix the player buttons
![Picsart_24-01-28_00-05-58-678](https://github.com/fast4x/RiMusic/assets/120176369/dd897e88-eaa8-42c7-9b02-de620ef5734c)

### Suggested Solution

I hope you liked it

### Additional Context

Thanx

**Comment by fast4x** [comment]
Tell me if I understand:
- 1, White colore on splashscreen and white default - theme
- 2, great image in artists box
- 3, would you like the text in the buttons
- 4, i don't understand

**Comment by fast4x** [comment]
Feedback please

**Comment by Logan7899** [comment]
> Tell me if I understand:
> 
> * 1, White color on splashscreen and white default - theme and same animations on sliding pages
> * 2, great image in artists box
> * 3, would you like the text in the buttons
> * 4, i don't understand

1. Yes
2. That sounds cool
3. No when you swipe up the toolbar, the text should be shown below according to their specific function and only icons at their original position
4. The play/pause button are are very huge and colors are very dark

**Comment by fast4x** [comment]
- 4, have you tryed custom version of today?
https://rimusic.xyz/ download

**Comment by Logan7899** [comment]
> * 4, have you tryed custom version of today?
>   https://rimusic.xyz/download

It is crashing when i click on song

**Comment by Logan7899** [comment]
> * 4, have you tryed custom version of today?
>   https://rimusic.xyz/download


https://github.com/fast4x/RiMusic/assets/120176369/769d966c-c9cb-45d5-b366-0fcdbe74f784

It is crashing!!!

**Comment by fast4x** [comment]
But app not have any permissions ...

**Comment by Logan7899** [comment]
> But app not have any permissions ...

Granted all permission but still not working
Droid fy version is fine af

**Comment by OrangeZXZ** [comment]
1. It would be nice to have the boot animation background same color as the app (Also changing with the Dynamic colors)
2. I was going to ask for this there is my vision of it
![image](https://github.com/fast4x/RiMusic/assets/104271365/ca849bac-2e2d-4bd3-8553-4df559a0a44a)
3. Could be a cool setting
4. Honestly i love the huge play buttons (I use rectangular buttons maybe add a setting for the size but not sure?) but yeah it is too dark

**Comment by OrangeZXZ** [comment]
> 2. I was going to ask for this there is my vision of it
Could also be in the menu (also remove the artist buttons in the menu when doing this and the playlist make it clickable at the top)
![image](https://github.com/fast4x/RiMusic/assets/104271365/18ff3889-47a7-4d89-8111-e8d3e052f933)
