### ISSUE TITLE
Pull down to refresh

### ISSUE THREAD

**Issue by abdulkarimx1** [fast4x/RiMusic#534]
### Description

Sometimes user wants to refresh quick picks ( either to listen to new songs or when a network connectivity change occurs ) so he have to leave application and open it again to refresh the list 

### Suggested Solution

Would it be possible to add a pull down to refresh feature so user can stay in app and just update the quick picks ( to get refreshed songs or fix when network connectivity change occurs) 

### Alternatives

Or implementing a refresh button ?

**Comment by fast4x** [comment]
Hello, yes it's great feature.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.30
