### ISSUE TITLE
RiMusic should have an account opening feature

### ISSUE THREAD

**Issue by LeonDayi** [fast4x/RiMusic#535]
### Description

RiMusic should have an account opening feature. I'm sure this feature will make the application stand out even more.

### Suggested Solution

In this way, when we delete the application or open it on another device (computer, TV or tablet, etc.), we can easily access our data (songs we listen to, library playlists, etc.) instantly.

**Comment by fast4x** [comment]
Hello, unfortunately it is not planned for privacy reasons.

**Comment by 6XChen** [comment]
Use the backup feature in settings 🙃

**Comment by siggi1984** [comment]
If this wish were implemented here, we would have the desired function.

**Comment by LeonDayi** [comment]
> Merhaba, gizlilik nedeniyle maalesef planlanmamaktadır.

Apple Music, Spotify and YouTube Music etc. The account opening feature is used and there are no problems.

**Comment by ikanakova** [comment]
>> Merhaba, gizlilik nedeniyle maalesef planlanmamaktadır.
> 
> Apple Music, Spotify and YouTube Music etc. The account opening feature is used and there are no problems.

So use the official apps of these organisations. This is the FOSS app used by people who care about privacy.

**Comment by fast4x** [comment]
@ikanakova perché non lo inserisci nelle FAQ?

**Comment by ikanakova** [comment]
> @ikanakova why you don’t put it in FAQ?

It's already there: https://github.com/fast4x/RiMusic/wiki/FAQs#-why-are-there-no-plans-to-implement-googleyoutube-login

**Comment by fast4x** [comment]
Not the same, here user request login to RiMusic profile... Not YT..

**Comment by ikanakova** [comment]
> Not the same, here user request login to RiMusic profile... Not YT..

I think it can either be done by google account or by using Piped etc. #278
