### ISSUE TITLE
Maybe it can help to patch visualizer

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#537]
### Steps to reproduce the bug

U enable visualizer and he freeze after a while or he not working 

### Expected behavior

To fix the issue just need to make ur phone lags and sometimes visualizer work with no issue weird

 here a video How to fix the problem for a while @fast4x 

### Actual behavior

U alerady know that visualizer is freezing but I found a way so that it works correctly

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/63956787/d7979335-8944-4e1d-8f24-195108285c17

### RiMusic version

0.6.19

### Android version

A12 MIUI 14

### Additional information

Maybe it can help you fix it IDK, but also sometimes when I go off the app or make the sound to 0 sometimes visualizer worked with no issues

**Comment by fast4x** [comment]
Impressive, thanks i try it

**Comment by NEVARLeVrai** [comment]
> Impressive, thanks i try it

Once I managed to make it work without any problem for 3 minutes but I don't know I can't do it anymore

**Comment by fast4x** [comment]
I couldn’t avoid the freeze, i'm afraid

**Comment by NEVARLeVrai** [comment]
> I couldn’t avoid the freeze, i'm afraid

🤷, it's weird

**Comment by OrangeZXZ** [comment]
I noticed that the visualizer freezes à lot more often when having the queue menu up. Dose it have a detection that makes it stop?

Also not sure but it crashes at sudden bpm changes and fast parts

**Comment by fast4x** [comment]
Yes, it’s a bug inside the visualizer.

**Comment by NEVARLeVrai** [comment]
> Yes, it’s a bug inside the visualizer.

Also the visualizer make randomly crash the app

**Comment by fast4x** [comment]
Improved, available from version 0.6.20 
I made some changes, it looks more stable

**Comment by NEVARLeVrai** [comment]
> Improved, available from version 0.6.20 
> I made some changes, it looks more stable

https://youtu.be/onuqnOmXF5E?si=YWylWNWw14b0gFgK

Here some other footage of me making visualizer work more than 30s
