### ISSUE TITLE
Player Colors and Buttons

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#541]
### Description

Since the last update there was a lot of new customisations settings but there are some other things that changed or need to be changed in my opinion:

## Inconsistent colors:
![image](https://github.com/fast4x/RiMusic/assets/104271365/9792a1f1-2ec1-424d-ab2a-9f0f04b720a4)
1. The player buttons should be white (or a brighter color) because they feel like unpressed buttons, and it is harder to see also the button background color is too dark (It should have the same color as the bottom bar)

![image](https://github.com/fast4x/RiMusic/assets/104271365/0f86d627-b102-47bd-b158-198f6ba85884)
2. I think the hearth should do the same thing as for the bottom icons (it should be colored when off and white when also keep the unfilled hearth when off)

## Inconsistent bottom bar:
![image](https://github.com/fast4x/RiMusic/assets/104271365/99b3155e-f2b9-4364-bdd3-081ba45ed0a8)
1. The download button takes a lot of the space and that makes the buttons slightly offcentered also the white bar is not rounded but i think this is already known

2. A friend of mine said that the bottom bar should not be opened when clicking on it because he opens it by accident (Also this is useless because we have the "Arrow Up" button and we can drag up)

## Inconsistent Seekbar:
![image](https://github.com/fast4x/RiMusic/assets/104271365/2bc76110-641d-4728-9bde-98ab05943b93)
1. I like that the pin bar is not starting from nothing but also why dose it add 3 seconds to the song and start at 0:03
I think a way to fix this is make the bar by default at 0:03 (maybe 0:04/0:05 it would be nicer) and when the song is after that time then start moving the bar

2. Another problem with the bar is when you hold on it it disappears it should just move to the finger without animations or maybe make biger the tiny bar like the fat bar

![image](https://github.com/fast4x/RiMusic/assets/104271365/4b79d4f3-337e-437c-a6d1-21b82ce64e60)
3. I think the name, artists, etc... should be a bit more centered because it is hard to seek with the bar and press the buttons if they are so close to the edge of the screen

**Comment by OrangeZXZ** [comment]
> relate to point 1
> talking about dynamic theme?

yes the colored buttons looks good on the dark theme but not on the Dynamic si i think it would be nice in white + make that button less dark

**Comment by fast4x** [comment]
In new version, dynamic look like this...
![Screenshot_20240130_180159](https://github.com/fast4x/RiMusic/assets/1484476/9f80ddc4-1447-45f7-9b2f-a23b9e9da54f)

**Comment by fast4x** [comment]
Inconsistent colors 1,2 
Inconsistent bottom bar 1,2
improved

**Comment by fast4x** [comment]
Inconsistent Seekbar 1,2 for now not possible

**Comment by fast4x** [comment]
Inconsistent Seekbar 3
Improved
Available from version 0.6.20
