### ISSUE TITLE
Ошибка при подключении

### ISSUE THREAD

**Issue by NikitaGut** [fast4x/RiMusic#542]
### Steps to reproduce the bug

1.Войти в приложение
2.Открыть раздел с музыкой

### Expected behavior

Должны появится треки

### Actual behavior

Вечная загрузка

### RiMusic version

0.6.19

### Android version

Android 11

### Additional information

Захожу через мобильный интернет (через sim карту), оператор МегаФон и ничего не работает. Через Wi-Fi всё работает

**Comment by fast4x** [comment]
Здравствуйте, к сожалению это проблема соединения с оператором телефона

**Comment by ikanakova** [comment]
Проверьте, не работает ли он с прокси.
