### ISSUE TITLE
Playlist upper bar

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#544]
### Description

The top bar for Favorites, downloads, etc... playlists are a bit off and here is what it should look like:

### Suggested Solution

Curently it looks like this:
![Ri Favorites](https://github.com/fast4x/RiMusic/assets/104271365/60ab2144-efbb-4e33-8b31-e96dbc9656be)

But it needs to look more like this
![Ri Playlist](https://github.com/fast4x/RiMusic/assets/104271365/5026a0a3-ce2c-4425-9fd6-42249bdfcbec)

The icon should have the background box like in the playlists section also text and picture should be more centered and the color should match the Dynamic theme

### Alternatives

Also the "Smart shuffle" should work on these playlist as well

And these icons should be reunite into one icon that opens an pop-out with all the stortings (icons and text)
![image](https://github.com/fast4x/RiMusic/assets/104271365/982d87e3-3d74-4d5b-8fed-7a87df25415f)

**Comment by ikanakova** [comment]
> And these icons should be reunite into one icon that opens an pop-out with all the stortings (icons and text) ![image](https://private-user-images.githubusercontent.com/104271365/300735557-982d87e3-3d74-4d5b-8fed-7a87df25415f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDgwMDUsIm5iZiI6MTcwNjYwNzcwNSwicGF0aCI6Ii8xMDQyNzEzNjUvMzAwNzM1NTU3LTk4MmQ4N2UzLTNkNzQtNGQ1Yi04ZmVkLTdhODdkZjI1NDE1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwOTQxNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjY4MTI4NjIxNGUzN2NjOTE5MmZjOGViM2E0MGVjZjMwNjc5N2ZkZDBjNzY2ODc2YTQ2OWY4NGM0ZDBkODgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I-e47VLztxU7WH05HXjM7_fZukO7OfWcdsEzIYkZtlI)

I've been thinking this would be cool, too.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.20

**Comment by fast4x** [comment]
Relate to:
**And these icons should be reunite into one icon that opens an pop-out with all the stortings (icons and text)
image**

Please create a specific ticket, thanks

**Comment by ikanakova** [comment]
> Relate to: **And these icons should be reunite into one icon that opens an pop-out with all the stortings (icons and text) image**
> 
> Please create a specific ticket, thanks

Done #551
