### ISSUE TITLE
Tiny hotbox on some songs

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#545]
### Steps to reproduce the bug

Go in the listening statistics

### Expected behavior

Have a big hitbox like in the Quick Picks

### Actual behavior

Has a tiny hitbox

### Screenshots/Screen recordings

![Ri Hitbox](https://github.com/fast4x/RiMusic/assets/104271365/e1c5d7ac-97ce-4456-8999-0bd9d202e35e)

### RiMusic version

0.6.19

### Android version

Android 14

**Comment by fast4x** [comment]
Fixed, available from version 0.6.20
