### ISSUE TITLE
Please move the play button on the now playing screen back to the middle

### ISSUE THREAD

**Issue by Lllum** [fast4x/RiMusic#549]
### Steps to reproduce the bug

Updated the app to the latest version 

### Expected behavior

The play, back, and next buttons should be aligned in the middle 

### Actual behavior

The next, and play buttons shifted to the side of the screen

### Screenshots/Screen recordings

![Screenshot_20240130-185359](https://github.com/fast4x/RiMusic/assets/156969262/99c6c3ce-30a1-4a9f-a0e7-769b2c33c1f9)

### RiMusic version

0.6.19

### Android version

8.1.0

**Comment by fast4x** [comment]
Hello, yes it's just fixed and available from next version 0.6.20
