### ISSUE TITLE
[Feature]: Sort menu

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#551]
### Description

All sorting icons should be reunite into one icon that opens an pop-out with all the stortings (icons and text).
![300735557-982d87e3-3d74-4d5b-8fed-7a87df25415f](https://github.com/fast4x/RiMusic/assets/38765251/27b4357e-407c-44db-bc73-53fc4a7fa1c8)

### Suggested Solution

Sort icons unified under one icon, which could either look like this one from the ionicons:
<img src="https://raw.githubusercontent.com/fast4x/RiMusic/master/assets/ionicons/funnel.svg" width="80">

Or:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/686bfc8f-908e-40ac-a1d4-e979751da80b" width="100">

### Additional Context

Edit: The text may possibly be taken from [FAQ icon explanation](https://github.com/fast4x/RiMusic/wiki/FAQs#-icon-explanation)

**Comment by OrangeZXZ** [comment]
> ### Description
> 
> All sorting icons should be reunite into one icon that opens an pop-out with all the stortings (icons and text).
> ![300735557-982d87e3-3d74-4d5b-8fed-7a87df25415f](https://github.com/fast4x/RiMusic/assets/38765251/27b4357e-407c-44db-bc73-53fc4a7fa1c8)
> 
> 
> ### Suggested Solution
> 
> Sort icons unified under one icon, which could either look like this one from the ionicons:
> <img src="https://raw.githubusercontent.com/fast4x/RiMusic/master/assets/ionicons/funnel.svg" width="80">
> 
> Or:
> <img src="https://github.com/fast4x/RiMusic/assets/38765251/686bfc8f-908e-40ac-a1d4-e979751da80b" width="100">
> 
> 
> ### Alternatives
> 
> _No response_
> 
> ### Additional Context
> 
> _No response_

I like both but the first one could be hard to guess

**Comment by ikanakova** [comment]
> > ### Description
> > All sorting icons should be reunite into one icon that opens an pop-out with all the stortings (icons and text).
> > ![300735557-982d87e3-3d74-4d5b-8fed-7a87df25415f](https://private-user-images.githubusercontent.com/38765251/300927269-27b4357e-407c-44db-bc73-53fc4a7fa1c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NDEzMTUsIm5iZiI6MTcwNjY0MTAxNSwicGF0aCI6Ii8zODc2NTI1MS8zMDA5MjcyNjktMjdiNDM1N2UtNDA3Yy00NGRiLWJjNzMtNTNmYzRhN2ZhMWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE4NTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhODkyZGE0ZTUyMGI0YjI0NjM1MjkxNzkyNzZkNjUzZjgwYjg4YjVhNmFjODNhNGYwOGVlZjY1YmNkY2M5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DHCD1FDErwet4q3lGBLxUB9Qo04veImGMtG-0UewWDg)
> > ### Suggested Solution
> > Sort icons unified under one icon, which could either look like this one from the ionicons:
> > <img alt="" width="80" src="https://raw.githubusercontent.com/fast4x/RiMusic/master/assets/ionicons/funnel.svg">
> > Or:
> > <img alt="" width="100" src="https://private-user-images.githubusercontent.com/38765251/300927626-686bfc8f-908e-40ac-a1d4-e979751da80b.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NDEzMTUsIm5iZiI6MTcwNjY0MTAxNSwicGF0aCI6Ii8zODc2NTI1MS8zMDA5Mjc2MjYtNjg2YmZjOGYtOTA4ZS00MGFjLWExZDQtZTk3OTc1MWRhODBiLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE4NTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZDk3NGEzYTQ0OGRmMWViZmZlMTBlYzQxNmVmZjQwYzE5YWNhNjQ4Y2ViMWJiMmUwODBkYTdlMzkxYTc3ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7yWmoZ_qlsgPF32Q-b3sFEbdNFSi-o253LPeUwzQDBM">
> > ### Alternatives
> > _No response_
> > ### Additional Context
> > _No response_
> 
> I like both but the first one could be hard to guess

I created the second one based on what the icons look like when you type "sort icon" into Google. The first one is a classic filter icon, which is used for filtering and sorting in a lot of apps, but for me it means more of a filter.

**Comment by OrangeZXZ** [comment]
> > > ### Description
> > > All sorting icons should be reunite into one icon that opens an pop-out with all the stortings (icons and text).
> > > ![300735557-982d87e3-3d74-4d5b-8fed-7a87df25415f](https://private-user-images.githubusercontent.com/38765251/300927269-27b4357e-407c-44db-bc73-53fc4a7fa1c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NDEzMTUsIm5iZiI6MTcwNjY0MTAxNSwicGF0aCI6Ii8zODc2NTI1MS8zMDA5MjcyNjktMjdiNDM1N2UtNDA3Yy00NGRiLWJjNzMtNTNmYzRhN2ZhMWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE4NTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhODkyZGE0ZTUyMGI0YjI0NjM1MjkxNzkyNzZkNjUzZjgwYjg4YjVhNmFjODNhNGYwOGVlZjY1YmNkY2M5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DHCD1FDErwet4q3lGBLxUB9Qo04veImGMtG-0UewWDg)
> > > ### Suggested Solution
> > > Sort icons unified under one icon, which could either look like this one from the ionicons:
> > > <img alt="" width="80" src="https://raw.githubusercontent.com/fast4x/RiMusic/master/assets/ionicons/funnel.svg">
> > > Or:
> > > <img alt="" width="100" src="https://private-user-images.githubusercontent.com/38765251/300927626-686bfc8f-908e-40ac-a1d4-e979751da80b.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NDEzMTUsIm5iZiI6MTcwNjY0MTAxNSwicGF0aCI6Ii8zODc2NTI1MS8zMDA5Mjc2MjYtNjg2YmZjOGYtOTA4ZS00MGFjLWExZDQtZTk3OTc1MWRhODBiLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE4NTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZDk3NGEzYTQ0OGRmMWViZmZlMTBlYzQxNmVmZjQwYzE5YWNhNjQ4Y2ViMWJiMmUwODBkYTdlMzkxYTc3ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7yWmoZ_qlsgPF32Q-b3sFEbdNFSi-o253LPeUwzQDBM">
> > > ### Alternatives
> > > _No response_
> > > ### Additional Context
> > > _No response_
> > 
> > I like both but the first one could be hard to guess
> 
> I created the second one based on what the icons look like when you type "sort icon" into Google. The first one is a classic filter icon, which is used for filtering and sorting in a lot of apps, but for me it means more of a filter.

if we keep that logic yes it is better

**Comment by ikanakova** [comment]
> if we keep that logic yes it is better

which one?

**Comment by OrangeZXZ** [comment]
> > if we keep that logic yes it is better
> 
> which one?

the first

**Comment by ikanakova** [comment]
I like the second one better 😀 I guess I have first one associated with filtering rather than sorting...

**Comment by DeadSecTr** [comment]
Please implement it soon...cuz the buttons in the playlist ist way tooo overloaded :(

It breaks the Awsome look from RiMusic imo

Thanks for the best music app so far!

**Comment by ikanakova** [comment]
@fast4x If you like the other one better, I can add it to the icons folder tomorrow.

**Comment by fast4x** [comment]
> @fast4x Which one do you like better? If you like the second one better, I can add it to the icons folder tomorrow.

Second 😋

**Comment by ikanakova** [comment]
> > @fast4x Which one do you like better? If you like the second one better, I can add it to the icons folder tomorrow.
> 
> Second 😋

Icon added #607 😉

**Comment by DeadSecTr** [comment]
When will this available?

**Comment by fast4x** [comment]
will be without icon from version 0.6.22

**Comment by fast4x** [comment]
Implemented
