### ISSUE TITLE
Play/pause button not centred

### ISSUE THREAD

**Issue by BWPanda** [fast4x/RiMusic#553]
### Steps to reproduce the bug

Play a song.

### Expected behavior

The Play/Pause button should be centered between the Previous & Next buttons.

### Actual behavior

The Play/Pause button is too far to the right, sitting closer to the Next button than it does to the Previous button.

### Screenshots/Screen recordings

![IMG_20240131_125650](https://github.com/fast4x/RiMusic/assets/2385329/cef20143-623a-4d4a-82cc-36f3dd8f58d5)

### RiMusic version

0.6.19

### Android version

Android 14

**Comment by BWPanda** [comment]
I've also just noticed that the 3 buttons (Previous, Play/Pause, Next) as a group aren't centred below the progress bar:

![image](https://github.com/fast4x/RiMusic/assets/2385329/d3d464d8-a135-44bf-8452-de2367109458)

**Comment by ikanakova** [comment]
Fixed, see #524 and #549.
