### ISSUE TITLE
Improve Discovery

### ISSUE THREAD

**Issue by Radtrix** [fast4x/RiMusic#554]
### This is a place to give new ideas for the discovery channel!

**Comment by ikanakova** [comment]
Fixed, see #524 and #549.

**Comment by fast4x** [comment]
Hello, your system language?
Quick Picks Page show?

**Comment by Radtrix** [comment]
Yes.
![Screenshot_20240131_105458](https://github.com/fast4x/RiMusic/assets/103896460/7d69d54a-90dd-4a76-ac87-32100e67f308)

**Comment by fast4x** [comment]
Ok, it's curious, I'll check It soon

**Comment by Radtrix** [comment]
Thanks, really appreciate it!

**Comment by fast4x** [comment]
hello, your geographical area?

**Comment by Radtrix** [comment]
Canada, Ontario

**Comment by fast4x** [comment]
I’m creating a custom version, please try it

**Comment by fast4x** [comment]
Ready, try this custom download from website
https://rimusic.xyz/download/

**Comment by Radtrix** [comment]
That works, thanks!

**Comment by fast4x** [comment]
I use this ticket for improving discovery.

**Comment by Radtrix** [comment]
Do you want me to change my original  error report as to not confuse anyone,  or keep it the same?

**Comment by Radtrix** [comment]
When listening to music for an extended time, I enjoy exploring various genres (like radio stations offer). Is it possible to add a discovery feature to select multiple genres and generate a playlist with the different genres?

Thanks again for your amazing support and amazing app!

**Comment by fast4x** [comment]
> Quando ascolto musica per un tempo prolungato, mi piace esplorare vari generi (come offrono le stazioni radio). È possibile aggiungere una funzione di scoperta per selezionare più generi e generare una playlist con i diversi generi?
> 
> Thanks again for your amazing support and amazing app!

Create a ticket specific with your suggestions. I will try...

**Comment by fast4x** [comment]
Implemented, enable language in discovery content. In your case, you can disable by UI settings and it work.

Available from version 0.6.20
