### ISSUE TITLE
[Enhancement]: Internal In-App Updater

### ISSUE THREAD

**Issue by DarkCrypt** [fast4x/RiMusic#555]
### Description

This would be a major improvement over the present implementation.

An internal in-app updater provides functionality to obtain app updates within the app without the need for users to use an external source. This provides a much better user experience, relieves stress on the user, and is also the quickest way to provide users with updates.

*This would also need Android TV support.

### Suggested Solution

To attempt to help with this, I tried to find solutions (in Kotlin) to hopefully make this easier to implement. The listed solutions (all from GitHub) avoid Google Play Core libraries.

Libraries
- [biscuit](https://github.com/arpitmx/bitscuit-library) - An android library to update your app in just 3 lines of code.
- [AppUpdate](https://github.com/azhon/AppUpdate/blob/main/README-EN.md) - An interesting android library which also has a demo app.

Apps
- [CloudStream](https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/utils/InAppUpdater.kt) (Android Mobile, Tablet, and TV) - Link to in-app updater file.
- [Streamflix](https://github.com/stantanasi/streamflix/blob/main/app/src/main/java/com/tanasi/streamflix/utils/InAppUpdater.kt) (Android TV) - Link to in-app updater file. Implemented own style by referencing from CloudStream.

### Alternatives

Other ways to obtain updates:
1. Present implementation
2. Manually download from GitHub releases
3. F-Droid
4. IzzyOnDroid
5. ApkUpdater
6. Obtainium

*ApkUpdater is the best option for updating on Android TV at this time.

### Additional Context

The present in-app updater isn't a proper internal in-app updater. It sends the user to repo releases within a browser for manual download and install.

**Comment by fast4x** [comment]
Thanks for suggestions, I'll try to implement soon if compatible with actual permissions.

**Comment by DarkCrypt** [comment]
You're welcome friend! I sincerely appreciate all your hard work and dedication to this project.

If these options don't work out for some reason, I'll continue looking.

**Comment by fast4x** [comment]
@DarkCrypt work perfectly AppUpdate! Thanks.
Implemented check, download and install in app...
Available from version 0.6.20

**Comment by DarkCrypt** [comment]
@fast4x 
That's fantastic! I'm excited to try this out when it's time, glad I could help!
