### ISSUE TITLE
[Feature]: Artist download

### ISSUE THREAD

**Issue by Radtrix** [fast4x/RiMusic#560]
### Description

A way to download top songs from artist from their artist page in search.

### Suggested Solution

I would like there to be a button or option that downloads the artists top songs. 

### Alternatives

A button that downloads every song an artist has made. Only problem with this could be repeat songs, like two versions of the same song.

### Additional Context

When I am downloading my offline playlist, I normally go to an artist's albums, and put every song they made in a playlist. 
If I know the artist well, I download every song (doesn't matter how many there are).
If I don't know the artist, I download my favorite songs from them, then delete the rest.

There is an overview of all an artist's songs in the songs tab, but no way to add them all in a playlist.  These also contain multiple versions of the same song. 

This should be the last time I bother you for new features, and I know what I am asking is super hard, maybe even impossible, so thank you so much for being amazing! :)

**Comment by fast4x** [comment]
No, but why do you say that you disturb? You are Benevento like everyone else and I thank you for the ideas you suggest. This feature is interesting, it will be developed soon.
