### ISSUE TITLE
back button not working when minimizing the app

### ISSUE THREAD

**Issue by Sheepmister** [fast4x/RiMusic#562]
### Steps to reproduce the bug

n/a

### Expected behavior

i cant exit the app using back button

### Actual behavior

n/a

### Screenshots/Screen recordings

n/a

### Logs

n/a

### RiMusic version

latest

### Android version

android 14 derpfest gsi

### Additional information

n/a

**Comment by fast4x** [comment]
![Screenshot_20240201_095928](https://github.com/fast4x/RiMusic/assets/1484476/1d93eb73-2f2d-4aea-8a08-971afab8062c)
Enable from UI settings

**Comment by Sheepmister** [comment]
> ![Screenshot_20240201_095928](https://private-user-images.githubusercontent.com/1484476/301445798-1d93eb73-2f2d-4aea-8a08-971afab8062c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Nzg4MjIsIm5iZiI6MTcwNjc3ODUyMiwicGF0aCI6Ii8xNDg0NDc2LzMwMTQ0NTc5OC0xZDkzZWI3My0yZjJkLTRhZWEtOGEwOC05NzFhZmFiODA2MmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMDkwODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzYyNzI3YTkyNzE1MDFkZGRmMTY5NTc1ZDRhYjQyNzkyNjYzN2Q4YzJjNTgyYjYxNjliOGMxNTFlMzY4NGI0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z2ZyJ_d-hB-Pc2Zt8_xckYt1cPV-U2YfPUgNCkeq3A4) Enable from UI settings

thank you sir its working now ,,btw may i ask is this app legal cause i can do like what youtube music has to pay

**Comment by fast4x** [comment]
The app is legal because it is opensource and uses APIs that are published by YouTube and YouTube Music. RiMusic is just one of thousands of apps that play music from YT.

**Comment by fast4x** [comment]
Added in Wiki page https://github.com/fast4x/RiMusic/wiki/FAQs#-is-rimusic-a-legal-app
