### ISSUE TITLE
Tap on a line of lyrics (synchronized) to jump back

### ISSUE THREAD

**Issue by Tafim27** [fast4x/RiMusic#563]
### Description

I hope you get it. It's same as what Spotify has. Sometimes I have to go back to a part but doing that by the timeline is a bit hard.

### Suggested Solution

So I think making it similar to what Spotify has would be a great feature. Or probably a distinct feature on the settings where I can enable/disable it anytime!

**Comment by fast4x** [comment]
#208 same request

**Comment by fast4x** [comment]
Implemented, available from version 0.6.21
