### ISSUE TITLE
Local Files function is not working as intended 

### ISSUE THREAD

**Issue by Davutha** [fast4x/RiMusic#565]
### Steps to reproduce the bug

Scroll to Library, go to On Device, and play any local songs.

### Expected behavior

The song will play fully without issues.

### Actual behavior

The song is not "found" and the song wont play. This happens to any song and sometimes the app will crash instead of giving the error.

### Screenshots/Screen recordings

![Screenshot_2024-02-01-14-43-30-978_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/68203036/595895c0-a7c1-4020-b816-6ef434d1d23f)
![Screenshot_2024-02-01-14-43-13-224_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/68203036/fcf526e9-1374-422e-9aa7-035d0b649395)

### RiMusic version

0.6.19

### Android version

Android 13 (MIUI 14)

### Additional information

The local music can be found with a file explorer and can be played with a normal mp3 player

**Comment by fast4x** [comment]
Check permissions for access files

**Comment by fast4x** [comment]
Bug confirmed, I'll check It, thanks

**Comment by fast4x** [comment]
Fixed, available from version 0.6.20
