### ISSUE TITLE
ri (v0.6.19) doesn't play local (smartphone)music

### ISSUE THREAD

**Issue by jlljeanluc** [fast4x/RiMusic#566]
### Steps to reproduce the bug

1. Go to "on device"
2. Clic a song

### Expected behavior

Play my songs

### Actual behavior

Message is "**local music file not found**" on all songs

### Screenshots/Screen recordings

![Screenshot_20240201-185658](https://github.com/fast4x/RiMusic/assets/111149206/109756e3-49b1-4086-80dc-2cc173ae77f2)

### RiMusic version

0.6.19

### Android version

Android 14

**Comment by fast4x** [comment]
Bug confirmed, I'll check It, thanks

**Comment by fast4x** [comment]
Fixed, available from version 0.6.20

**Comment by jlljeanluc** [comment]
thank you  👍
