### ISSUE TITLE
Wierd timeline graphics at ~1% progress

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#570]
### Steps to reproduce the bug

Especially Wavy & Fat bar
Zoom in to leftmost part of the timeline
<table><tbody><tr>
<th><img src="https://github.com/fast4x/RiMusic/assets/45221211/bd0ba26c-cd9d-4c61-b28b-f7ce81c0a985"></img></th>
<th><img src="https://github.com/fast4x/RiMusic/assets/45221211/2e141eac-0c93-488e-824d-8331ad5733af"></img></th>
<th><img src="https://github.com/fast4x/RiMusic/assets/45221211/b057504c-19b9-4ec5-bc8a-616bf16cf6e6"></img></th>
</tr></tbody></table>

### Expected behavior

Fat bar ~> Left side masked into timeline (not outside)
Wavy ~> Left side masked into proper shape (static rounded or something...)

### RiMusic version

0.6.19

### Android version

Android 11

### Additional information

Some suggestion regarding customization for timeline name
- Wavy <s>timeline</s>
- <s>Fat bar</s> ~> Fill
- Pin <s>bar</s>

If possible, add settings to customize timeline button shape & corner/roundness
Timeline button: Round, Square, etc (star, arrow, or something...)
Timeline corner/roundness (just like Thumbnail roundness)

<s>This ain't feature request, sorry</s>

**Comment by fast4x** [comment]
But this isn't a bug, you requested features... :)

**Comment by faustaahmad** [comment]
Please Zoom in on leftmost part of the timeline pictures, or do I need to crop the image?
I cant explain it with words
<s>I shouldn't add Additional info in the first place anyway</s>

**Comment by fast4x** [comment]
For now ok so.
