### ISSUE TITLE
Music recommendation

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#575]
### Description

With Spotify, music recommendations are displayed at the end of a playlist, which you can then add to a playlist or play next, for example.

I know that YouTube also offers this based on the currently playing song.

This implementation would be cool in RiMusic to discover new music that suits your taste.

https://github.com/25huizengek1/ViMusic

I think this developer has implemented it well. See screenshot.

Such an implementation would be cool for RiMusic.

### Suggested Solution

![300268387-bc0c17e1-8e8f-4367-b8bf-e51aab1fa4d1](https://github.com/fast4x/RiMusic/assets/103368536/5c2d6924-9895-4282-901b-94a59bb57c0c)

**Comment by fast4x** [comment]
RiMusic have just same feature... do you want extension of it?

**Comment by siggi1984** [comment]
> RiMusic have just same feature... do you want extension of it?

Yes, an extension would be good.
