### ISSUE TITLE
Can't download songs more than 10 minutes approx.

### ISSUE THREAD

**Issue by Dafrawys** [fast4x/RiMusic#577]
### Steps to reproduce the bug

1-Go to Warda
2-Like and download any song more than 10 mins 
3-Notice that after some time automatically reverts to no downloaded.

### Expected behavior

The song Should be downloaded and ready to play as always

### Actual behavior

The song is not downloaded and When I press Download nothing happens

### RiMusic version

0.6.20

### Android version

Andoid 14

**Comment by fast4x** [comment]
Do you have clicked on download icon?
