### ISSUE TITLE
Discovery

### ISSUE THREAD

**Issue by Radtrix** [fast4x/RiMusic#578]
### Steps to reproduce the bug

Go to Discovery

### Expected behavior

Page should show

### Actual behavior

Error

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/103896460/3668d5c5-a7e1-40d1-a72e-0239c85a11eb

### RiMusic version

0.6.20

### Android version

Android 14

**Comment by fast4x** [comment]
You are from Canada, disable language in Discovery by UI settings.
Pay attention https://github.com/fast4x/RiMusic/issues/554#issuecomment-1920191896
