### ISSUE TITLE
Music Recommendation is looping

### ISSUE THREAD

**Issue by ValentinLeTallec** [fast4x/RiMusic#579]
### Steps to reproduce the bug

- Go to a playlist with music recommendation enabled or enable it (sometime it's enough for the looping to start)
- Try to download all song in the playlist

### Expected behavior

The songs from the original playlist are downloaded

### Actual behavior

Songs from music recommendation start to loop and the download struggle (it works again if music recommendation is disabled)

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/48032747/15910422-090f-49f6-afe3-20b3cda00d5c

### RiMusic version

6.20 (also present in 6.19)

### Android version

Android 8

**Comment by fast4x** [comment]
I have disabled smart recommendations if download all actions occur, so looping is not visible.
In the future smart recommendations will be improved more.

Available from version 0.6.21
