### ISSUE TITLE
[Feature]: Configure the number of song recommended through music recommendation

### ISSUE THREAD

**Issue by ValentinLeTallec** [fast4x/RiMusic#580]
### Description

The new music recommendation feature is quite cool and I would like to be able to configure the frequency of recommendation.

### Suggested Solution

Add a setting "Recommend a new song for every N song in the playlist".
If possible, it would be interesting for N to be a decimal number, which would allow to not be limited to one recommendation per song in the original playlist. (N=0.5 would then mean recommending two song for every song in the playlist).

**Comment by fast4x** [comment]
Hi, will be possible set up to 20 recommandations but in random position, for now. Could that be enough?

**Comment by ValentinLeTallec** [comment]
Hi, I don't really care about the position, but it would but nice if the number of recommendation can be relative to the number of song in the playlist instead of a fixed number. (I think it's currently the case).

Though, being able to raise the absolute number of recommendations is OK too if the other solution adds too many difficulties.

**Comment by fast4x** [comment]
For now I can add from 1 to 20 recommendations.

**Comment by ValentinLeTallec** [comment]
Ok, that's already nice ^^
Thanks 😊

**Comment by fast4x** [comment]
Implemented, available from version 0.6.21
