### ISSUE TITLE
Issue #251 unable to reorder playlist v0.6.20

### ISSUE THREAD

**Issue by pst007x** [fast4x/RiMusic#581]
### Steps to reproduce the bug

1. Create a playlist
2. Reorder list
3. Leave and list resets to original
4. Unable to remember reordered list

### Expected behavior

List should reorder 

### Actual behavior

List does not reorder 

Strange behaviour as songs jump about and do not line up with finger selection When reordering I've noticed that when you move the second song to a new position the first song resets back to its original position.

### Screenshots/Screen recordings

This was closed in #251 however issue isn't fixed.

### RiMusic version

0.6.20

### Android version

13

**Comment by fast4x** [comment]
Has the playlist been imported or created and then added songs from albums?

Try reorder in playlist imported, send feedback please.

Maybe i understand...

**Comment by pst007x** [comment]
Playlist was created, not imported, then some added from album.

**Comment by pst007x** [comment]
I can't see any options too import a playlist only restore backup

**Comment by DeadSecTr** [comment]
> I can't see any options to import a playlist only restore backup

![Screenshot_20240203-052441.png](https://github.com/fast4x/RiMusic/assets/90558189/5ee5a5fa-ffc6-4872-886e-ff80b230ca31)

You can import playlist from youtube/youtube music

**Comment by fast4x** [comment]
Or from the online search, go to the Playlist Tab, select the playlist and press +
![Screenshot_2024-02-03-10-06-17-323_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/be199fc5-d89d-4e8b-92c0-b8eb543dd9bb)

**Comment by fast4x** [comment]
I think I solved
Fixed, available from version 0.6.21

**Comment by fast4x** [comment]
IMPORTANT, not work with existing playlist... will be work with new playlist

**Comment by fast4x** [comment]
I will a feature with renumbering all songs in playlist, this fix playlist wich not work

**Comment by fast4x** [comment]
Again 🥇 , I added the Renumber Songs feature that fixes sorting in the playlists I had the problem

**Comment by pst007x** [comment]
> Again 🥇 , I added the Renumber Songs feature that fixes sorting in the playlists I had the problem

Cool thanks for the work. Special.

**Comment by pst007x** [comment]
> > I can't see any options to import a playlist only restore backup
> 
> ![Screenshot_20240203-052441.png](https://private-user-images.githubusercontent.com/90558189/302012668-5ee5a5fa-ffc6-4872-886e-ff80b230ca31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNTI1NzYsIm5iZiI6MTcwNzM1MjI3NiwicGF0aCI6Ii85MDU1ODE4OS8zMDIwMTI2NjgtNWVlNWE1ZmEtZmZjNi00ODcyLTg4NmUtZmY4MGIyMzBjYTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDAwMzExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZGMyMGZjMjA0ZjkyMTkwYTIyM2Q1OWQ5NTBmYzMwODY1OTNmYmUzOGQ3YTI1MTlmNmVmMTE2ZjI1NDhmMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LMvgwHZpxWL5xf2ZYHnDXlgUBTK8As0v0UHyu2nzaEM)
> 
> You can import playlist from youtube/youtube music

Odd. I don't have that option: online. I've installed the version from here, is there a different version? Cheers

**Comment by fast4x** [comment]
New release on Friday

**Comment by DeadSecTr** [comment]
> New release on Friday 


Today?

**Comment by fast4x** [comment]
Yes soon
