### ISSUE TITLE
Unable to edit lyrics 

### ISSUE THREAD

**Issue by Tafim27** [fast4x/RiMusic#584]
### Steps to reproduce the bug

Opened a song that has synchronized lyrics. I tapped on the bottom right "three dotted" button and tapped on edit lyrics.

### Expected behavior

There should've been a "save" or "done" button to save the changes I've made.

### Actual behavior

I don't see any "save" or "done" or any button at all anywhere.

### RiMusic version

0.6.20

### Android version

Android 11

**Comment by DeadSecTr** [comment]
Is there...but way too much on the bottom...![Screenshot_20240203-210702.png](https://github.com/fast4x/RiMusic/assets/90558189/287c4c84-ac9a-4a66-ac42-71edc9a2f1a7)
