### ISSUE TITLE
Bottom bar and play button size

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#585]
### Description

With the new UI i noticed some changes in play buttons and bottom bar (I also saw that this is because on tiny screens the UI is messed up)

### Suggested Solution

I think it would be nice a feature that lets you change the size of thise things

### Additional Context

Also with the new bar the bottom icons are too separated and too close to the screen edge + not centered

![SmartSelect_20240203_122600](https://github.com/fast4x/RiMusic/assets/104271365/52336dfa-654c-4e38-a2de-010b72a7d575)

In the queue it looks nice to be honest but it has to change size with the bottom bar to be consistent
![SmartSelect_20240203_122611](https://github.com/fast4x/RiMusic/assets/104271365/97513a18-d90a-42d7-a750-8475bc262d3d)

**Comment by OrangeZXZ** [comment]
Maybe also chose between 3 spacing for the text and seekbar in the player
3 options:
- Close to the edge
- A bit centered
- More Centered

**Comment by fast4x** [comment]
Fixed off centerer icons, available from version 0.6.21

**Comment by fast4x** [comment]
Improved also bottom bar in queue

**Comment by fast4x** [comment]
> Magari anche scelto tra 3 spaziature per il testo e seekbar nel lettore 3 opzioni:
> 
> * Close to the edge
> * A bit centered
> * More Centered

Would you like to change the vertical spacing between the artist line and the seekbar?
I understand?

**Comment by OrangeZXZ** [comment]
> > Magari anche scelto tra 3 spaziature per il testo e seekbar nel lettore 3 opzioni:
> > 
> > * Close to the edge
> > * A bit centered
> > * More Centered
> 
> Would you like to change the vertical spacing between the artist line and the seekbar?
> I understand?

between the edge of the screan an the seekbar but the other could be cool too

**Comment by fast4x** [comment]
> > > Magari anche scelto tra 3 spaziature per il testo e seekbar nel lettore 3 opzioni:
> > > 
> > > * Close to the edge
> > > * A bit centered
> > > * More Centered
> > 
> > 
> > Would you like to change the vertical spacing between the artist line and the seekbar?
> > I understand?
> 
> tra il bordo dello screan e il seekbar, ma anche l'altro potrebbe essere fresco

But actual spacing from edge is related to thumbnail size...

**Comment by OrangeZXZ** [comment]
> > > > Magari anche scelto tra 3 spaziature per il testo e seekbar nel lettore 3 opzioni:
> > > > 
> > > > * Close to the edge
> > > > * A bit centered
> > > > * More Centered
> > > 
> > > 
> > > Would you like to change the vertical spacing between the artist line and the seekbar?
> > > I understand?
> > 
> > tra il bordo dello screan e il seekbar, ma anche l'altro potrebbe essere fresco
> 
> But actual spacing from edge is related to thumbnail size...

i didn't noticed sorry
