### ISSUE TITLE
[Feature]: Lyrics Translation

### ISSUE THREAD

**Issue by Yashvanth343** [fast4x/RiMusic#59]
### Description

Lyrics Translation

### Suggested Solution

Lyrics Translation

**Comment by ikanakova** [comment]
I think the only way this would be possible is if instead of pulling lyrics from KuGou, the app pulled lyrics from something like [Lyrics Translations](https://lyricstranslate.com/). Unfortunately, Lyrics Translations doesn't have an API, so it probably can't be implemented in RiMusic.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.8
