### ISSUE TITLE
Some more changes

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#591]
### Description

1. The album size comparatively is short as comparatively small as compared to Vi Music.
![Screenshot_20240203-220408](https://github.com/fast4x/RiMusic/assets/120176369/632c90d2-0f9e-4611-b6f7-2e09247dbc54)
![Screenshot_20240203-220405](https://github.com/fast4x/RiMusic/assets/120176369/76e5abfb-0b6e-482c-be39-bf13abe01f7a)

2. The thumbnail roundness also changes of search bar. I like no edge thumbnail roundness but with that option enabled the search bar looks awful. Please fix and make search bar left centered and big.

3. I have an solution to fix the toolbar off centering. By moving the download button in three dot menu as a option and replacing the download button in toolbar with sleep timer. Hope you liked.

4. The previous version toolbar height was good but now it look compressed and the white bar on the toolbar looks very odd and weird which was good in previous version.

5. The colour of the toolbar is different and when u open the queue, the toolbar colour is different.
![Screenshot_20240203-220408](https://github.com/fast4x/RiMusic/assets/120176369/62c076d3-f0e8-4c1e-bc62-d56ddd82cb87)
![Screenshot_20240203-221328](https://github.com/fast4x/RiMusic/assets/120176369/9c87ca3f-2c82-4148-82e2-08c4b5af4b17)

6. The progess bar's progression time is placed in center
RiMusic
![Screenshot_20240203-220408~2](https://github.com/fast4x/RiMusic/assets/120176369/bdfc6867-2913-4162-be59-c2d28806ea35)

Vimusic 
![Screenshot_20240203-220408~2](https://github.com/fast4x/RiMusic/assets/120176369/5cf737f7-49b4-4e8c-8385-79212a29b151)

### Suggested Solution

Hope you find something new

### Additional Context

You are doing great work in adding features but i think this app reached it stage where nore features are not required instead it requires optimisation as it crashes very frequently which i noticed. I fouvare playing music then stop it and open another app for half hour and then come back even though invincible service is on it will still crash.

**Comment by fast4x** [comment]
Related point 1, you can change thumbnail size on appearance settings

**Comment by fast4x** [comment]
2, you can change or disable by settings

**Comment by fast4x** [comment]
3, I'll check It

**Comment by fast4x** [comment]
4 actual size Is needed for maximum compatibility with all display size.
In the future, can change size by settings.

**Comment by fast4x** [comment]
5, colors are inverted, from player and queue...

**Comment by fast4x** [comment]
6 i don't understand, can you explain?

**Comment by ikanakova** [comment]
6 I think he means that the times under the progress bar used to be all right and left, but now they're in the middle.

**Comment by fast4x** [comment]
And don't like?

**Comment by ikanakova** [comment]
I personally liked it the way it was before.

**Comment by fast4x** [comment]
Ok so already in two you do not like, change as before.

**Comment by Logan7899** [comment]
> 2, you can change or disable by settings

![Screenshot_20240204-081434](https://github.com/fast4x/RiMusic/assets/120176369/eb5c04b0-04ef-4758-b93f-b8ed3489b62f)
![Screenshot_20240204-081458](https://github.com/fast4x/RiMusic/assets/120176369/aa1b5f6d-02d7-4068-a2f8-4fb7f8c6ccc3)

**Comment by Logan7899** [comment]
> ### Description
> 1. The album size comparatively is short as comparatively small as compared to Vi Music.
>    ![Screenshot_20240203-220408](https://private-user-images.githubusercontent.com/120176369/302048533-632c90d2-0f9e-4611-b6f7-2e09247dbc54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMTUwNjEsIm5iZiI6MTcwNzAxNDc2MSwicGF0aCI6Ii8xMjAxNzYzNjkvMzAyMDQ4NTMzLTYzMmM5MGQyLTBmOWUtNDYxMS1iNmY3LTJlMDkyNDdkYmM1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwMjQ2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjY1NjFlY2QyNmJiY2M2NWZlZmM5YTk5ZDdlZTUxODFmNjhmZTMwZmNmYjQ0NDljNGY0NTU2OTNlYjMzZWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5tbQu1OYqvWUGRsFFjrIRpz2W8bvguDaAkcEtWKU8rA)
>    ![Screenshot_20240203-220405](https://private-user-images.githubusercontent.com/120176369/302048544-76e5abfb-0b6e-482c-be39-bf13abe01f7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMTUwNjEsIm5iZiI6MTcwNzAxNDc2MSwicGF0aCI6Ii8xMjAxNzYzNjkvMzAyMDQ4NTQ0LTc2ZTVhYmZiLTBiNmUtNDgyYy1iZTM5LWJmMTNhYmUwMWY3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwMjQ2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGZkYTkxOGFlYzA0OGI0NzRmMDlkNzE5YzgxOWFiYjJjOTg1ZDJjMzBjYWUyOTdlNWUxZWYxMmRmY2RhM2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._C7zsVWHV6azhgUhPr82_wpahNQm4MLDRuHNuNpCUew)
> 2. The thumbnail roundness also changes of search bar. I like no edge thumbnail roundness but with that option enabled the search bar looks awful. Please fix and make search bar left centered and big.
> 3. I have an solution to fix the toolbar off centering. By moving the download button in three dot menu as a option and replacing the download button in toolbar with sleep timer. Hope you liked.
> 4. The previous version toolbar height was good but now it look compressed and the white bar on the toolbar looks very odd and weird which was good in previous version.
> 5. The colour of the toolbar is different and when u open the queue, the toolbar colour is different.
>    ![Screenshot_20240203-220408](https://private-user-images.githubusercontent.com/120176369/302048905-62c076d3-f0e8-4c1e-bc62-d56ddd82cb87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMTUwNjEsIm5iZiI6MTcwNzAxNDc2MSwicGF0aCI6Ii8xMjAxNzYzNjkvMzAyMDQ4OTA1LTYyYzA3NmQzLWYwZTgtNGMxZS1iYzYyLWQ1NmRkZDgyY2I4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwMjQ2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmYxMDRkMTA1OTNlNzQxNjcxMWMyOTc5YjVkZTgyZmI0NjI3M2E0OTk4MmEwNWVkZDgzYzc4YjY5MjM0ODc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H67Wt049aCV32bUJJx7HC2LjqIknaPunTMYNNnvGs_8)
>    ![Screenshot_20240203-221328](https://private-user-images.githubusercontent.com/120176369/302048911-9c87ca3f-2c82-4148-82e2-08c4b5af4b17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMTUwNjEsIm5iZiI6MTcwNzAxNDc2MSwicGF0aCI6Ii8xMjAxNzYzNjkvMzAyMDQ4OTExLTljODdjYTNmLTJjODItNDE0OC04MmUyLTA4YzRiNWFmNGIxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwMjQ2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzA0NzM1N2U0Zjk5OTc4NmMwZDcxYTA4MWZkNDIzMWQyNzYzMTE4YTgyMmZlZjcxZDA2NTkxYjdiNGY0OTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o7sY3Y2iQmrTgzZYB7nn5qABsH_rhk8WyO-Tdrj-iVY)
> 6. The progess bar's progression time is placed in center
>    RiMusic
>    ![Screenshot_20240203-220408~2](https://private-user-images.githubusercontent.com/120176369/302073353-bdfc6867-2913-4162-be59-c2d28806ea35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMTUwNjEsIm5iZiI6MTcwNzAxNDc2MSwicGF0aCI6Ii8xMjAxNzYzNjkvMzAyMDczMzUzLWJkZmM2ODY3LTI5MTMtNDE2Mi1iZTU5LWMyZDI4ODA2ZWEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwMjQ2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2Q0YjA1OWIxYzcxNDRiZGJkMjQxYmQ5OTAxMDkyMzFhZmMzM2VjNGE5OGQzYWIzZDQwNTFlMGRmY2M2MzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QDNz5T9QG6hncRccHFb-FflUaOhIoIgMpbVOjlCSuv0)
> 
> ViMusic
![Screenshot_20240203-220405~2](https://github.com/fast4x/RiMusic/assets/120176369/67ccf401-2c9f-4ad4-a6f4-3a00c1197ab4)

> 
> ### Suggested Solution
> Hope you find something new
> 
> ### Alternatives
> ### Additional Context
> Thx

**Comment by fast4x** [comment]
4 and 6 done, available from version 0.6.21

**Comment by faustaahmad** [comment]
@fast4x when the issue still persist (not end all)
Please just open those issues, maybe <s>strikethrough</s> the closed issues if it's bullet points or even change the title

I would say nice job on making the UI centered but...
My screen is 720p but forgot about the height
![Screenshot_20240210-233619](https://github.com/fast4x/RiMusic/assets/45221211/ee4493d2-295c-4a9c-b65a-07243890f828)

**Comment by fast4x** [comment]
What exactly would you like?

**Comment by faustaahmad** [comment]
Look at the bottom bar
Does it looks alright?
Utility wise, I'm not complaining
But when I see this, more annoying than seeing it not properly aligned

**Comment by fast4x** [comment]
The interface looks clean to me, the height of the toolbar seems consistent to me.
I check the speed of the scrolling text and decrease it a little.

**Comment by faustaahmad** [comment]
I mean most left & right icon need a little bit more center, how do I put it...
This kinda bad looking
<table><tr>
<td>🔁</td>
<td></td><td></td>
<td>🔀</td>
<td></td><td></td>
<td>🔼</td>
</tr></table>

This better
<table><tr>
<td></td><td>🔁</td><td></td>
<td>🔀</td>
<td></td><td>🔼</td><td></td>
</tr></table>
