### ISSUE TITLE
Link opening

### ISSUE THREAD

**Issue by DeadSecTr** [fast4x/RiMusic#593]
### Description

Please implement that we can open youtube music/youtube links with RiMisic.

### Suggested Solution

Click on received link from YtMusic to open song with RiMusic

**Comment by fast4x** [comment]
Is Just implemented share link from YT/YTM

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/c06645da-00bc-4754-ab58-175751493ef0

**Comment by DeadSecTr** [comment]
Bro...not share with rimusic,i mean if one become a youtube music link via whatsapp oder any messenger then click on that link to open with rimusic

**Comment by fast4x** [comment]
Bro... Copy link and go to search > Go to link, paste link and enjoy

**Comment by DeadSecTr** [comment]
https://github.com/fast4x/RiMusic/assets/90558189/c772d8b1-90ce-4ab5-bf7e-5e9a7c932603

**Comment by OrangeZXZ** [comment]
You can go to the app settings and enable "Open Links" and then chose the links to open it will automatically open links on click if you dont have this feature activated on YTMusic or YT![Screenshot_20240204_123042_Settings.jpg](https://github.com/fast4x/RiMusic/assets/104271365/327eb51b-7fcd-4d80-ba50-3087105a0a56)

**Comment by fast4x** [comment]
Look...

https://github.com/fast4x/RiMusic/assets/1484476/b9f842ca-e9f8-4f7d-a777-7a3d24113f12

https://music.youtube.com/watch?v=WE4wn-PEDYc

**Comment by OrangeZXZ** [comment]
> Look...
> 
> https://github.com/fast4x/RiMusic/assets/1484476/b9f842ca-e9f8-4f7d-a777-7a3d24113f12
> 
> https://music.youtube.com/watch?v=WE4wn-PEDYc

I also didn't knew this feature 😅 at least i know now

**Comment by fast4x** [comment]
Lol, eh you read the changelog in new releases
