### ISSUE TITLE
It doesn't have some songs from provider Aditya music India and other english movie songs also pls add them

### ISSUE THREAD

**Issue by Manideepvelchuri** [fast4x/RiMusic#594]
### Steps to reproduce the bug

Go to search
Type Dj tillu song 

### Expected behavior

First song named DJ tillu by Aditya music 

### Actual behavior

But all songs of Aditya music not found 

### RiMusic version

0.6.20

### Android version

Android 12

**Comment by OrangeZXZ** [comment]
Songs can be listened on YT Music as a video or as a song?

**Comment by OrangeZXZ** [comment]
you can try looking at the "video" section after searching![SmartSelect_20240204_122651.jpg](https://github.com/fast4x/RiMusic/assets/104271365/b3603c67-45af-457f-81b8-996a2c5d0fda)
