### ISSUE TITLE
Album Icon instead of pictures

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#596]
### Description

The like, downloaded, local, ect... has now at the top the last 4 songs added but i think there is a better way to do it.

### Suggested Solution

Look now:
![SmartSelect_20240203_122512](https://github.com/fast4x/RiMusic/assets/104271365/323caa46-ecfe-4fdd-b441-0d382f73311a)
This is not bad but if there aren't songs in the Playlist the icon is shown as before.

Instead do this:
![SmartSelect_20240203_122448](https://github.com/fast4x/RiMusic/assets/104271365/abf6bfe8-4bbd-4c93-bbd0-bee7922a7a6d)
It will look better in my opinion and prevent this thing I said before

**Comment by fast4x** [comment]
Implemented, available from version 0.6.21
