### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#600]
### Steps to reproduce the bug

1. Open the app
2. Use it for a while
3. Exit the app with the home button
4. Listen to a bit of background playback
5. Reopen the app after a while

### Expected behavior

Should open where I left off

### Actual behavior

Crashes and exits

### RiMusic version

0.6.20

### Android version

Android 14

**Comment by VINULA2007** [comment]
> Try disable battery optimization in settings

I'll try

**Comment by fast4x** [comment]
...and enable invincible service from settings > Other

**Comment by VINULA2007** [comment]
> ...and enable invincible service from settings > Other

Thanks
It doesn't crash  now
