### ISSUE TITLE
why proxy not working 

### ISSUE THREAD

**Issue by Spaceshiprace** [fast4x/RiMusic#603]
### Steps to reproduce the bug

Hi, So I'm trying to set proxy and its not working ??? am I doing something wrong I really don't know how that works I need some help  please anyone tell me how I can set proxy 

### Expected behavior

its not working when I set it

### Actual behavior

It should work

### Logs

idk

### RiMusic version

0.6.20

### Android version

Android 12

### Additional information
I need that proxy feature cause (yt music not available in my damn country)

**Comment by fast4x** [comment]
Pay attention in what is the type of proxy.
All parameters must be configured exactly, server ip, port, type of proxy
After set paramaters, RiMusic must be restart

**Comment by Spaceshiprace** [comment]
Please can you guide step by step how I can done that because I am a d dumb ass in that

**Comment by Spaceshiprace** [comment]
I just tired and I set everything in it's place then I restart the app its says an erro or something like (Not working) please help

**Comment by fast4x** [comment]
![Screenshot_20240204_191713](https://github.com/fast4x/RiMusic/assets/1484476/37abe754-2a21-4f4c-a002-3406a05f0324)

Sure, example from this list http://free-proxy.cz/en/proxylist/country/all/socks/ping/all
- filter proxy type socks4/5
- get the proxy you want to use 
- set type socks
- set ip by list
- set port by list

restart RiMusic

Would be work...

**Comment by Spaceshiprace** [comment]
I did these steps literally that what I got :

![Screenshot_2024-02-04-19-41-32-050_it fast4x rimusic_1](https://github.com/fast4x/RiMusic/assets/156727749/479ba7f0-b89e-447d-886c-6f1a1f2b9e01)

**Comment by fast4x** [comment]
Maybe proxy list Is unreachble from your geographic area.

**Comment by fast4x** [comment]
Try from this
https://geonode.com/free-proxy-list

**Comment by Spaceshiprace** [comment]
same again "an error has occurred"

**Comment by fast4x** [comment]
Try this condiguration

185.25.205.141	
80	
HTTP

**Comment by Spaceshiprace** [comment]
finally ! it works God bless your soul dude ❤️

**Comment by fast4x** [comment]
Glad I could help.
