### ISSUE TITLE
[Feature]: Scrobbling Support

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#61]
### Description

[Last.fm scrobbling](https://www.last.fm/api/scrobbling) or other similar services.
Last.fm scrobbling enables e.g. Spotube, VLC,...

### Suggested Solution

The ability to track and share the music you're listening to.

**Comment by ikanakova** [comment]
Might help - https://github.com/kawaiiDango/pScrobbler
Unfortunately I can't program, so I can't do it myself 😔

**Comment by ikanakova** [comment]
I'm closing this issue because probably implementing this feature would require last.fm tracker.

**Comment by ikanakova** [comment]
I'm closing this issue because probably implementing this feature would require last.fm tracker.

**Comment by GithubUser452** [comment]
ListenBrainZ and Libre.m can be 2 open source options.
