### ISSUE TITLE
Show release year in player

### ISSUE THREAD

**Issue by Lolozweipunktnull** [fast4x/RiMusic#610]
### Description

With many songs, I'm interested in when they were released. It's currently very difficult to find out in the app (you have to search for the album in the album tab). It would be very nice if it were easier to see the year directly in the player.

### Suggested Solution

(For me) I think it would be best if the year was displayed somewhere near to the artist and song title or possibly above the song cover.

### Alternatives

I guess for many people the year is not that interesting, so maybe you could make it optional in the settings. 
And even if the year was displayed in the info that appears when you tap and hold on the album cover, I'd be happy 😊.

**Comment by fast4x** [comment]
Currently displayed in the context menu, other you can not do
