### ISSUE TITLE
Android Auto support is broken from v 0.6.19 onward

### ISSUE THREAD

**Issue by BabyBenefactor** [fast4x/RiMusic#611]
### Steps to reproduce the bug

- Connect to Android Auto
- Open apps
- Tap RiMusic, and see that it keeps showing a blank screen and eventually an Android Auto error message (This app can't be opened right now)

### Expected behavior

The app should launch normally.
Version 0.6.18 does this.

### Actual behavior

Blank screen and an error message.

### RiMusic version

0.6.20

### Android version

Android 14

### Additional information

After a bit of trial and error I found that somewhere between 0.6.18 and the 0.6.19 a change was made which broke Android Auto support.
Using F-Droid builds. The latest from Github Releases also does not work.

If you need more info I'll be happy to help

**Comment by KondaShivaradhan** [comment]
+1 this is true. exact same issue

**Comment by fast4x** [comment]
Between 18 and 19 changes a lot, the 19 includes the new Android 14 platform.
I'll check it, thanks for the feedback

**Comment by fast4x** [comment]
Hi, please try this custom version download from rimusic website, send me feedback please.
https://rimusic.xyz/download

**Comment by BabyBenefactor** [comment]
Thanks for your fast reply. I tested it just now and it is still a blank screen. Maybe it works for @KondaShivaradhan ?

**Comment by fast4x** [comment]
In the evening I will make another custom version to try.

**Comment by fast4x** [comment]
New custom version ready, see you tomorrow then. Thank you for your feedback.

**Comment by BabyBenefactor** [comment]
Is it the same download link?

**Comment by fast4x** [comment]
> Is it the same download link?

Yes

**Comment by fast4x** [comment]
![Screenshot_20240205_213218](https://github.com/fast4x/RiMusic/assets/1484476/ef3a8090-de1a-46e7-a36b-12ebd51dc21b)

seems to work...

**Comment by KondaShivaradhan** [comment]
Damn! thats a good looking UI. when is the official update?

**Comment by fast4x** [comment]
Friday

**Comment by fast4x** [comment]
Can try it from this link, thi is a custom version for test in your android auto
https://rimusic.xyz/download

**Comment by Danielo1739** [comment]
Same +1

**Comment by BabyBenefactor** [comment]
Yes issue fixed - amazing work.

Closing

**Comment by fast4x** [comment]
Thanks for feedback

**Comment by fast4x** [comment]
Available from version 0.6.21
