### ISSUE TITLE
long songs can't be downloaded fully

### ISSUE THREAD

**Issue by Spaceshiprace** [fast4x/RiMusic#617]
### Steps to reproduce the bug

So, I click to download this certain song and its just keeps loading and loading and it doesn't show that the song are downloaded, when I click on the songs its actually downloaded but not full

Additional Notes : I don't really know why if is it because I'm using Proxy or because of the songs length I don't even know if it has something to do with that its so damn confusing !?

### Expected behavior

It should be downloaded like other songs

### Actual behavior

its not downloading (its the first time I'm facing this issue)

### Screenshots/Screen recordings
I face this issue with these two songs in the screenshots The only thing I noticed that both of them are quite long
![Screenshot_2024-02-05-23-31-32-679_it fast4x rimusic_1](https://github.com/fast4x/RiMusic/assets/156727749/826f4f4a-29ff-43eb-911f-b674212e1245)
![Screenshot_2024-02-06-10-24-08-474_it fast4x rimusic_1](https://github.com/fast4x/RiMusic/assets/156727749/fc280c53-641f-4d61-9297-5e1c92b170c3)

### Logs

idk

### RiMusic version

0.6.20

### Android version

Android 12

### Additional information

I think there's something about the length of the songs that it can't be downloaded fully

**Comment by fast4x** [comment]
I'm afraid but not a bug in RiMusic, maybe limitation on song

**Comment by Spaceshiprace** [comment]
what is that ?

**Comment by Spaceshiprace** [comment]
can you please explain ???

**Comment by fast4x** [comment]
RiMusic processes the length of the song it receives. It cannot evaluate if it is wrong, so it is not a bug of RiMusic.

**Comment by Spaceshiprace** [comment]
why it receives it wrong ?

**Comment by Spaceshiprace** [comment]
I have to point out that when I download it did download but the issue is that not downloading it fully and also not showing that downloaded icon

**Comment by fast4x** [comment]
I understand, paste link of Song please.

**Comment by Spaceshiprace** [comment]
Here is it the song in the first screenshot
https://music.youtube.com/watch?v=0JYqz9yEn78

**Comment by Spaceshiprace** [comment]
while I'm waiting for your response about the link you request, I can give another example of the issue it might help.. In this screenshot as you see a 8 min song downloaded successfully while a 11 min song doesn't
![Screenshot_2024-02-06-18-30-31-192_it fast4x rimusic_1](https://github.com/fast4x/RiMusic/assets/156727749/ee48b714-c2b3-433a-a680-a0a951391216)

**Comment by Spaceshiprace** [comment]
Any response here

**Comment by cledsupper** [comment]
I tried playing a long song without downloading before which worked as I expect, so it seems to be an youtube buffer side effect.

**Comment by Spaceshiprace** [comment]
@cledsupper did you mean that its yt music issue not RiMusic 
I also tried Innertune and I downloaded the song in the first screenshot above and It works perfectly
So what's that mean ?

**Comment by fast4x** [comment]
I said that I deepen the problem

**Comment by fast4x** [comment]
Try to set audio quality low, close, reopen and try download again

**Comment by Spaceshiprace** [comment]
> Try to set audio quality low, close, reopen and try download again

I did and it did downloaded successfully, but that doesn't mean that the issue is fixed right ?

**Comment by fast4x** [comment]
Yes, automatic normally decides which is the best quality every time

**Comment by Spaceshiprace** [comment]
but when it was set to Automatic it didn't downloaded but when I set it to High it downloaded

**Comment by fast4x** [comment]
it means that in that specific case, the version of the song with high quality was damaged...

**Comment by Spaceshiprace** [comment]
I understand now, I have to say thanks to you again 🙌❤️
