### ISSUE TITLE
[Feature]: Predictive back

### ISSUE THREAD

**Issue by Moodzz1** [fast4x/RiMusic#618]
### Description

Add support for android 14 (13?) predictive back gesture.

### Suggested Solution

N/A

**Comment by fast4x** [comment]
It’s already been implemented, what’s missing is animation.

**Comment by Quinxxxx** [comment]
Can you add the missing animation? Would be appreciated.

**Comment by Jak2k** [comment]
Dupe of #198

**Comment by OrangeZXZ** [comment]
@fast4x i think this one can be closed (because we have the animations)

**Comment by fast4x** [comment]
yep
