### ISSUE TITLE
Artist Changes

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#619]
### Description

It would be great if u add a follow button instead small save icon and show subscribers count in artist page

### Suggested Solution

![Picsart_24-02-06_09-28-23-384](https://github.com/fast4x/RiMusic/assets/120176369/80d9b6e7-ab4b-499a-ac39-dc0af4b02a35)

### Additional Context

Thanks

**Comment by Logan7899** [comment]
@fast4x

**Comment by fast4x** [comment]
Implemented, available from version 0.6.22
