### ISSUE TITLE
When the playlist contains a "deleted song", the app crashes on background play

### ISSUE THREAD

**Issue by NoMorePizza** [fast4x/RiMusic#620]
### Steps to reproduce the bug

1. Start listening to any playlist on background containing a song that has its original source deleted.

### Expected behavior

When there is a deleted song in the playlist, the app should pause the playlist, and the user has to manually skip it, or the app should automatically jump over the deleted song and continue playing.

### Actual behavior

But instead, the app just crashes and I have to open the playlist again.

### Screenshots/Screen recordings

![20240206_140703](https://github.com/fast4x/RiMusic/assets/132079771/387a59a4-c5a5-427a-bae0-46634f9573ad)

### RiMusic version

v0.6.20

### Android version

Android 14

**Comment by fast4x** [comment]
Uhhh nice bug, i'll fix it, thanks

**Comment by fast4x** [comment]
Do you have link of this song?

**Comment by NoMorePizza** [comment]
https://music.youtube.com/watch?v=T2-E2iH01rs

**Comment by fast4x** [comment]
I’m sorry but I just tried the link and it opens in RiMusic

**Comment by fast4x** [comment]
Do you add link to playlist wich contain deleted song, please?

**Comment by NoMorePizza** [comment]
It's my playlist in RiMusic and there is not an option to share it.

**Comment by fast4x** [comment]
Ah ok so your local playlist, ok important this, thanks

**Comment by fast4x** [comment]
You have A14, test link open with new version 0.6.21

**Comment by NoMorePizza** [comment]
I have A52s. When you clicked that link, did the song play normally? Because that song doesn't play on ViMusic either. If you try to open in browser, it says "video not available". Problem is not that it doesn't open, but song with deleted source or other issue crashes the app.

Here is a public playlist that has some songs that don't work, song called "The Cape of Good Hope" for example.

https://youtube.com/playlist?list=PL_LfVsFJiCL45XE82GQ8CjGAadrZrNc6e

**Comment by fast4x** [comment]
Ok i will check the problem

**Comment by NoMorePizza** [comment]
Btw, when you clicked that that link, did it open the song or just a RiMusic app? Because for me it only opens the app, not the song.

**Comment by fast4x** [comment]
Paste the link in search > Go To Link tab is same wich share link to RiMusic.
try if it work

**Comment by NoMorePizza** [comment]
Ok, it works that way, but if I set YouTube Music links to open directly in RiMusic in the app settings, then it just opens the app and not the song. That's the issue.

**Comment by fast4x** [comment]
You Will teu It with new version, if bug persist i Will check It After

**Comment by ikanakova** [comment]
I have the same problem in v0.6.22. I think it happens if the internet briefly fails and the song is not yet cached or the song in my playlist is deleted (it doesn't happen with playlists where there is an option to sync with the original playlist). In my opinion, it should skip to the next song when there is an outage for a song, but instead the app crashes. After restarting it works as it should.
It happens really rarely especially when I'm driving so I can't reproduce the error and send the log.
