### ISSUE TITLE
[Feature]: Option to filter out explicit songs

### ISSUE THREAD

**Issue by AnotherRandomGitHubAccount** [fast4x/RiMusic#621]
### Description

A way to filter out explicit songs, global and or as a playlist filter option, so i can play random songs / my playlists around family

### Suggested Solution

Probably a show/hide explicit songs button on the left of all the playlist sorting options, and/or an option to disable them entirely in the settings menu.

### Alternatives

Maybe autoskip for explicit songs? (it would be more "hacky" but probably easier to implement)

### Additional Context

Nothing really, but thanks for taking the time to read this! 😄

**Comment by OrangeZXZ** [comment]
@fast4x @AnotherRandomGitHubAccount I believe the "parental control" feature is already implemented, so this issue can be closed?

**Comment by fast4x** [comment]
It's partially implemented

**Comment by fast4x** [comment]
Parental control implementation completed, available from version 0.6.52
