### ISSUE TITLE
Can't go to album or artist from downloaded song

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#622]
### Steps to reproduce the bug

1. Download a song
2. Play it 

### Expected behavior

The artist and name should take you to the artist's page or to the album 

### Actual behavior

Artist name and song title is grayed out and nothing happens when I tap on it

### Screenshots/Screen recordings

![Screenshot_2024-02-06-23-09-41-560_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89296867/29c6d506-b786-4e90-9e75-676191625aff)

### RiMusic version

0.6.20

### Android version

Android 14

### Additional information

@fast4x could you tell where to get version 0.6.21?

**Comment by fast4x** [comment]
New version every Friday

**Comment by fast4x** [comment]
Try to change Song to forward and return

**Comment by VINULA2007** [comment]
> Try to change Song to forward and return

Doesn't work

**Comment by VINULA2007** [comment]
> > Try to change Song to forward and return
> 
> Doesn't work

It only happens to downloaded songs though

**Comment by fast4x** [comment]
Ok I'll check it
