### ISSUE TITLE
Song cannot be played due to server restrictions

### ISSUE THREAD

**Issue by Spaceshiprace** [fast4x/RiMusic#624]
### Steps to reproduce the bug

Two song from the same album has the same issue
What is that even mean

### Expected behavior

It should work normally 

### Actual behavior

It says "Song cannot be played due to server restrictions"

### Screenshots/Screen recordings

![Screenshot_2024-02-06-21-39-19-921_it fast4x rimusic_1](https://github.com/fast4x/RiMusic/assets/156727749/6b3acca9-d2b0-452c-9cf2-396e7907858e)

### RiMusic version

0.6.20

### Android version

Android 12

### Additional information

I'm using a proxy

**Comment by DarkCrypt** [comment]
@Spaceshiprace 
Referencing the above screenshot...

Click the 3 dot menu (top right corner) -> Listen on (bottom of menu) -> Listen on Piped or Listen on Invidious. The song will open and play in your browser.

@fast4x 
Following the above instructions, when going back to RiMusic the app crashes and also if you minimize the app and reopen.

**Comment by fast4x** [comment]
@Spaceshiprace link of Song?

**Comment by Spaceshiprace** [comment]
https://music.youtube.com/watch?v=0J3_arOc_A8

**Comment by Spaceshiprace** [comment]
ttps://music.youtube.com/watch?v=0J3_arOc_A8

**Comment by Spaceshiprace** [comment]
> @Spaceshiprace link of Song?

I closed this issue accidentally, anyway here is the link
https://music.youtube.com/watch?v=0J3_arOc_A8

**Comment by Spaceshiprace** [comment]
@fast4x please can you response if there's any fix for this issue
