### ISSUE TITLE
Crashing Problem 

### ISSUE THREAD

**Issue by rusunny123** [fast4x/RiMusic#627]
### Steps to reproduce the bug

1 ) When Running app in background...if i want to close the player from notification bar and again open the app...the app Crashes
2 ) App Crashes when Clicking Multiple Time in Setting and back button 

### Expected behavior

Described in Video 

### Actual behavior

Described in Video 

### RiMusic version

Leatest Version 

### Android version

Android 9

### Additional information

Video link 🔗 https://m.sunnys.workers.dev/1:/TheGdriveXbot/Screenrecord_2024-02-07-17-15-21.mp4

_No response_

**Comment by rusunny123** [comment]
https://github.com/fast4x/RiMusic/assets/73994046/61bad918-c03e-4c91-a1c2-f48e19227efd

**Comment by rusunny123** [comment]
Video Link 🔗

https://m.sunnys.workers.dev/1:/TheGdriveXbot/Screenrecord_2024-02-07-17-15-21.mp4

my video size is 14 mb so I had to give link because guitar don't support video upper then 10 MB

**Comment by fast4x** [comment]
Check if you have enabled from settings:
- invincible service
- close background player

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/wiki/FAQs#-why-does-the-app-close-automatically-after-i-pause-it-for-a-while

**Comment by rusunny123** [comment]
https://github.com/fast4x/RiMusic/assets/73994046/347ec6fe-44a1-48b7-907b-fe9b28c72b7a

**Comment by rusunny123** [comment]
same problem sir 
do difference
video link

https://m.sunnys.workers.dev/1:/TheGdriveXbot/Screenrecord_2024-02-07-19-01-29.mp4

**Comment by rusunny123** [comment]
> https://github.com/fast4x/RiMusic/wiki/FAQs#-why-does-the-app-close-automatically-after-i-pause-it-for-a-while


https://m.sunnys.workers.dev/1:/TheGdriveXbot/Screenrecord_2024-02-07-19-01-29.mp4

**Comment by fast4x** [comment]
Error there is if you disable notification?
I' don't understand, explain please, thanks

**Comment by fast4x** [comment]
You have android 9 ok, i will check remove from notification logic

**Comment by rusunny123** [comment]
> You have android 9 ok, i will check remove from notification logic

I'll also test the app with my brothers Android 13 phone....if face same problem I'll let you know
