### ISSUE TITLE
[Feature]: Discord Rich Precence

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#63]
### Description

Discord Rich Precence feature in app

### Suggested Solution

Discord Rich Precence

**Comment by NEVARLeVrai** [comment]
Is it possible ?

**Comment by OrangeZXZ** [comment]
I think ViMusic had an tiny start on that but not a big one

**Comment by NEVARLeVrai** [comment]
@fast4x it's this still open?

**Comment by fast4x** [comment]
yes

**Comment by kkduds** [comment]
this would be awesome

**Comment by NEVARLeVrai** [comment]
> yes
Is this feature still open? Or still an "idea" ? @fast4x

**Comment by fast4x** [comment]
maybe willbe implemented soon

**Comment by fast4x** [comment]
Implemented, available from version 0.6.52
