### ISSUE TITLE
server restriction problem

### ISSUE THREAD

**Issue by Spaceshiprace** [fast4x/RiMusic#631]
### Steps to reproduce the bug

Some specific songs cannot be played due to server restriction

### Expected behavior

It should play

### Actual behavior

it didn't 

### RiMusic version

0.6.20

### Android version

Android 12

### Additional information

I have closed another issue report about this same problem accidentally So I'm reporting again because the issue doesn't fixed yet

**Comment by fast4x** [comment]
Server restrction not depend by RiMusic, i'm afraid.

**Comment by Spaceshiprace** [comment]
Ok, but why you afraid

**Comment by fast4x** [comment]
Not afraid, i'm sorry.

**Comment by Spaceshiprace** [comment]
I think you English broke like Me 😅

**Comment by fast4x** [comment]
Absolutely yes, 😂😂😂

**Comment by Spaceshiprace** [comment]
@fast4x I want to ask a question I been looking for an answer Anywhere but I can't find (out RiMusic)

**Comment by Spaceshiprace** [comment]
@fast4x
So I installed innertune And I tried to set Proxy URL in the settings but I can't Understand How I can do it
Did you havr any Idea How I can set a Proxy URL its gonna be So helpful for me plzzzz 🥹

**Comment by Spaceshiprace** [comment]
So as you see in this screenshot I get a Proxy URL for a free proxy website but when I insert the port

**Comment by fast4x** [comment]
Remove http:// and write
proxycrime.com add : add port Number, example:
proxycrime.com:2342

**Comment by Spaceshiprace** [comment]
@fast4x 
For example this site : http://free-proxy.cz/en/web-proxylist/
its just gaves the URLS without Port Number
You know what I mean

**Comment by fast4x** [comment]
If Port non present, are 80

**Comment by Spaceshiprace** [comment]
Ah Ok, Thank you so much ❤️
