### ISSUE TITLE
Albums Loading endlessly

### ISSUE THREAD

**Issue by Spaceshiprace** [fast4x/RiMusic#633]
### Steps to reproduce the bug

I search for the album in the screenshot, I click on it, It keeps loading endlessly without showing up the songs in it

### Expected behavior

Showing The songs on the album

### Actual behavior

loading endlessly 

### Screenshots/Screen recordings

![Screenshot_2024-02-07-19-50-10-731_it fast4x rimusic_1](https://github.com/fast4x/RiMusic/assets/156727749/81441118-861f-4f68-928b-60441b253a0c)

### RiMusic version

0.6.20

### Android version

Android 12

### Additional information

The album Link :
https://music.youtube.com/playlist?list=OLAK5uy_m1qv3ZOZaffqcXyHWAFQ5QNz08O_k3pLE

**Comment by fast4x** [comment]
I've loaded It now without probkem.
![Screenshot_2024-02-07-21-06-07-285_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/a3548080-5434-4949-9cf9-578c88fd378f)

**Comment by Spaceshiprace** [comment]
Did you using a proxy

**Comment by fast4x** [comment]
No, I don’t need it

**Comment by fast4x** [comment]
If you Need a proxy, try to change it with another. Would be work

**Comment by Spaceshiprace** [comment]
Don't Pay mind, It fixed I don't know what happened I think the app crashs for a while and it back to work. Sorry to bothering you ❤️

**Comment by fast4x** [comment]
No problem, thank you for the feedback.
