### ISSUE TITLE
Show the time of when the sleep timer ends.

### ISSUE THREAD

**Issue by Tafim27** [fast4x/RiMusic#635]
### Description

Show the actual time (e.g. 3:52 PM rn) of the targeted time of sleep timer.

### Suggested Solution

While setting sleep timer there should be the actual time shown of when the timer will stop. Also it'd be great if we could manually set timer. I mean as of now we can only set 5/10/15…

**Comment by fast4x** [comment]
Manual sleep timer Is Just implemented, click on time icon and would be set.
![Screenshot_2024-02-08-14-06-24-891_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/11bcd477-df1e-4edb-a6f0-47cfb7cb3792)

**Comment by fast4x** [comment]
But you can set duration step up to 2 hours

**Comment by fast4x** [comment]
Ok

**Comment by faustaahmad** [comment]
Sleep timer ≠ Alarm
Also better change your title into "Custom sleep timer duration" or just open new issue about that

**Comment by fast4x** [comment]
Implemented, added time when sleep timer ends up.
Available from version 0.6.22
