### ISSUE TITLE
on device media permission issue

### ISSUE THREAD

**Issue by fakebhai** [fast4x/RiMusic#636]
### Steps to reproduce the bug

open RiMusic go to "On device" in "Library" it shows "On device require read media permission" 

### Expected behavior

List of on device audio/songs

### Actual behavior

can't see any songs due to permission issues

### Screenshots/Screen recordings

![Screenshot_2024_0208_174400](https://github.com/fast4x/RiMusic/assets/101493467/dd5d4f0b-17f2-4842-a95d-d3f02ae93f3e)
![Screenshot_2024_0208_174411](https://github.com/fast4x/RiMusic/assets/101493467/6d513d14-0c0f-4612-a0d5-059b80b16bd1)

I even checked on app manager just to be sure (I haven't touched anything)
![Screenshot_2024_0208_175115](https://github.com/fast4x/RiMusic/assets/101493467/e368e827-bab8-495b-9620-486d68b5a26c)

### RiMusic version

0.6.20

### Android version

Android 12

### Additional information

I haven't touched anything. I originally downloaded it from Droid-ify (F-Droid). it was working fine few updates before. I haven't seen any folder picker options in app either.
it could be reproduced in both 0.6.19 and 0.6.20

**Comment by fakebhai** [comment]
![Screenshot_2024_0208_181112.jpg](https://github.com/fast4x/RiMusic/assets/101493467/192aa656-ca79-496b-9fa4-89d9f8088b18)

currently I downgraded it to 0.6.18 which is working as intended

**Comment by fakebhai** [comment]
![image](https://github.com/fast4x/RiMusic/assets/101493467/acdbd9e1-1c5a-4257-80e2-c6c27cb93db1)
maybe you should revert it

**Comment by fast4x** [comment]
You have Android 12 and it doesn’t work even if you have granted permissions?

**Comment by fast4x** [comment]
Soon I publish a custom version, try and tell me if it works, thanks

**Comment by fakebhai** [comment]
> https://rimusic.xyz/download/
> try this custom version, send me feedback, thanks

yes it worked.

**Comment by fakebhai** [comment]
> You have Android 12 and it doesn’t work even if you have granted permissions?

it only asked for microphone permission in official versions of 0.6.19 and 0.6.20

**Comment by fast4x** [comment]
Perfect, available from version 0.6.21
