### ISSUE TITLE
Random crashing 

### ISSUE THREAD

**Issue by VThakur08** [fast4x/RiMusic#638]
### Steps to reproduce the bug

While searching song and tapping to play app force closes and after relaunch its works normal 

### Expected behavior

Song should play 

### Actual behavior

Force closing 

### RiMusic version

0.6.20

### Android version

14

**Comment by fast4x** [comment]
Try to enable Invincible service in settings and set disable battery optimization

**Comment by VThakur08** [comment]
I tried on adding Rimusic on exception on battery so my system is not force
closing it.
Everytime I search any song or playlist and after selecting it's force
closing.
Apart from this everything works fine.
You guys made superb app

**Comment by fast4x** [comment]
Try to increased player cache size in settings, restart app

**Comment by fast4x** [comment]
Try this custom version https://rimusic.xyz/download

**Comment by VThakur08** [comment]
Okay thanks troubleshooting was worked
