### ISSUE TITLE
[Feature]: Google Account Sign In and Musixmatch translation 

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#640]
### Description

1. I hope that I could make playlist directly in my YouTube music account and save favourites to it while also saving the listening history and it will remove the need to backup the app
2. Also the Musixmatch translations are much more accurate than google translate translations

### Suggested Solution

There is a app called SimpMusic
https://github.com/maxrave-dev/SimpMusic
That had implemented these features

**Comment by fast4x** [comment]
1. Google login isn't planned https://github.com/fast4x/RiMusic/wiki/FAQs#-why-are-there-no-plans-to-implement-googleyoutube-login
2. Musixmatch is a paid service, unusable

**Comment by VINULA2007** [comment]
Is there any other ytm client (except SimpMusic) that has these features?

**Comment by fast4x** [comment]
I don't know
