### ISSUE TITLE
Unable to open RiMusic by link

### ISSUE THREAD

**Issue by addy419** [fast4x/RiMusic#642]
### Steps to reproduce the bug

1. Enable open by default for youtube music links
2. Click on a youtube music link in any other app (e g. whatsapp)

### Expected behavior

Should open the link and start playing the song.

### Actual behavior

Only opens RiMusic and does nothing, neither the song page opens, not does it automatically start playing. It just opens the main screen.

### RiMusic version

0.6.20

### Android version

Android 13 Graphene OS

### Additional information

Sharing the link with the android context menu tp RiMusic works fine. It just doesn't open the links by default like ViMusic

**Comment by DeadSecTr** [comment]
I mentioned this also...but the dev doesnt understand what i mean :D

**Comment by fast4x** [comment]
Ok I'll check it

**Comment by faustaahmad** [comment]
As far as I'm using RiMusic
Open in Browser ≠ Share
Share will play/import the song most of the time
Open in Browser is the culprit
