### ISSUE TITLE
Visualizer freezes

### ISSUE THREAD

**Issue by theswordsgame** [fast4x/RiMusic#643]
### Steps to reproduce the bug

Enable visualizer, play music, and turn on visualizer 

### Expected behavior

It works normally

### Actual behavior

At certain points (mostly when it starts to peak) the visualizer freezes

### RiMusic version

0.6.20

### Android version

Android 14

**Comment by fast4x** [comment]
Hi, it's a know bug.

**Comment by theswordsgame** [comment]
Ok good to know
