### ISSUE TITLE
Adding local files to playlist

### ISSUE THREAD

**Issue by u-daygupta** [fast4x/RiMusic#646]
### Steps to reproduce the bug

1. Select a local file
2. Add it to a playlist

### Expected behavior

song added to playlist

### Actual behavior

nothing, no errors or it showing up in my playlist

### RiMusic version

0.6.20

### Android version

Android 13

### Additional information

Is this just not supported or bugged? it's not a deal breaker but I don't want to keep trying to do it only to be told that it isn't actually implemented yet. Thanks in advance, great work on the app.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.21
