### ISSUE TITLE
[Feature]: download all cached songs as mp3 media.

### ISSUE THREAD

**Issue by aRandomMenno** [fast4x/RiMusic#649]
### Description

Hello! I really like this app and recently I found an old mp3 player and I want to put all the music I have played over the time using your app to that mp3 player.
So the basic idea is that there is an option to download all played songs in the cache to mp3 in one go. 
I do think this might be a little difficult.

Thank you already!

### Suggested Solution

You could add an option in the settings under the `song cache (by player)` with an option to download all cached songs to mp3.
Or you could add an option under `library` then `cached` to download all cached songs to mp3.

**Comment by fast4x** [comment]
I'm sorry but RiMusic isn't downloader, Just player with internal download feature.
