### ISSUE TITLE
[Feature]: New Player Interface

### ISSUE THREAD

**Issue by Yashvanth343** [fast4x/RiMusic#65]
### Description

![Screenshot_2023-11-02-21-16-32-74_1c96baa6fc3a4338d23fd334c3c04599](https://github.com/fast4x/RiMusic/assets/72242474/9b2527e4-74f6-45ff-a9ae-e85b67dbd834)

### Suggested Solution

source: https://github.com/KRTirtho/spotube/

**Comment by fast4x** [comment]
Fine.
What's icon from left before download?

**Comment by ikanakova** [comment]
> What's icon from left before download?

It is alternative track sources - other versions of the same song.

**Comment by OrangeZXZ** [comment]
This is very well done! I like the non-flat background, but I find the theme a bit too transparent (I think the recent UI use only flat UI). There are also a lot of buttons, which can make the interface feel cluttered. I'm not saying that the buttons are bad, but I think they could be improved. For example, the "Lyrics" button takes up a lot of space, even though not all songs have lyrics. It might be better to make this button smaller or to hide it by default. (The cover art can already be tapped to view lyrics.)

**Comment by fast4x** [comment]
Yes, it is correct not to exaggerate you risk a lot. I don’t like to recreate a theme that already exists in other applications. I like the basic idea, a different button, a different seekbar, are interesting ideas.

**Comment by senolfndk** [comment]
You can have a player and design similar to this
![Screenshot_20231103-130600_Oto Music](https://github.com/fast4x/RiMusic/assets/52818836/2c1efc21-c0e7-4c29-b00b-9f6f2a71b202)
![Screenshot_20231103-130620_Oto Music](https://github.com/fast4x/RiMusic/assets/52818836/35b3755a-4d25-4e03-9e3e-a21501852938)

**Comment by fast4x** [comment]
Yes, it is compatible with functionality to customize the appearance of the player

**Comment by fast4x** [comment]
It would be nice to use a new set icons, with a new more modern.
Ideas?
@ikanakova @senolfndk @Yashvanth343 @OrangeZXZ @siggi1984 @DanielSevillano @dainvincible1

**Comment by senolfndk** [comment]
> Yeni ve daha modern bir simge seti kullanmak güzel olurdu. Fikirler mi? @ikanakova @senolfndk @Yashvanth343 @OrangeZXZ @siggi1984 @DanielSevillano @dainvincible1 @NEVARLeVrai

yes

**Comment by ikanakova** [comment]
I like the current [ionicons](https://ionic.io/ionicons), but I think it would be great if the user had the choice to have them outline/file/sharp and make it consistent throughout the app.
It would also be cool if the app was skinnable:
- in a minimal look there would be an album image, song and artist info (with links to go to album, artist) + previous, play/pause, next buttons
- (optionally) there would be another bar with favourite buttons, etc. and three dots with other things like start radio, etc.
- (optionally) a bar with info about the next song/s - maybe that one could be to the right of the album.

**Comment by ikanakova** [comment]
> it would be great if the user had the choice to have them outline/file/sharp and make it consistent throughout the app.

If that would be difficult to implement, we could do a poll.

BTW it would be good to merge all the issues about player interface into one and pin that one eventually.

**Comment by fast4x** [comment]
Learn more about ionicons

**Comment by OrangeZXZ** [comment]
> BTW it would be good to merge all the issues about player interface into one and pin that one eventually.

I created a Discussion about this everyone can post things related to UI there

**Comment by Yashvanth343** [comment]
Just a suggestion to have a player interface like this...

**Comment by OrangeZXZ** [comment]
> Just a suggestion to have a player interface like this... 

Sorry i was a bit too harsh i just like to give opinions
