### ISSUE TITLE
[Feature]: Better on device media filtering. 

### ISSUE THREAD

**Issue by aRandomMenno** [fast4x/RiMusic#650]
### Description

I recently found out that this app can also play music that I have downloaded to my device. but I also have all harry potter Ebooks on my device. however all these are not in order. 

### Suggested Solution

The basic idea is that when you click on you see all the different folders the music is in, a bit like file explorer. 
What I also would like to see is that you can select certain folders to not be shown in that menu. this could be another small icon at the top with shuffle and the current filters. The button could bring up a small menu that you which folders are shown and which aren't then by tapping the a folder it make the text strikethrough and now that folder will no longer be shown. 

This is an example and you can implement it however you want.

**Comment by faustaahmad** [comment]
### Alternatives
Import Folder (non-recursive) as playlist/album
Import ~> SAF/FolderPicker ~> Confirm ~> Profit
Import (recursive) ~> same but all songs inside sub⁵folder below would be scanned & added

**Comment by OrangeZXZ** [comment]
@fast4x @aRandomMenno If this is not planned, it could be closed?

**Comment by fast4x** [comment]
Isn't planned
