### ISSUE TITLE
[Feature]: Automatically add songs you play to a specific playlist. And auto download, (possibly?).

### ISSUE THREAD

**Issue by aRandomMenno** [fast4x/RiMusic#651]
### Description

When you play a song I would like the song to be added to a specific playlist after a certain amount of time. Could be the same timings as minimum playback duration before it gets added to quick picks. 
As for the auto downloading, it would be approximately the same as for the playlists. 

### Suggested Solution

When playing a songs after the interval it can be downloaded and added to a playlist individually toggleable. This could be under the `other` settings.

**Comment by fast4x** [comment]
For now isn't possible, maybe in the future with smart playlist feature.

**Comment by aRandomMenno** [comment]
Ahh okay. Then i'll make a python script to do it for me.
