### ISSUE TITLE
[Feature]: more personalized music experience 

### ISSUE THREAD

**Issue by mohandan1** [fast4x/RiMusic#654]
### Description

Right now,In tips,we gets limited personalized music like if I play some pop then all recommendations becomes pop and like this if I listen malyalam songs,all recommendations shows malyalam songs.like this in most played,it shows most played genre but we listens a lot genres.

### Suggested Solution

Is it possible to add various personalized genre and artist playlists and radio based on my music preferences like ytm and Spotify?

### Additional Context
![Screenshot_20240210_092012](https://github.com/fast4x/RiMusic/assets/135564025/c4e32253-0592-4d89-b03e-8615a119aa0b)

**Comment by fast4x** [comment]
Hi, I can’t add the feature identical to Spotify because RiMusic depends on the content it receives from YTM. But I can try to improve the suggestions.

**Comment by mohandan1** [comment]
Thanks,this screenshot was just to explain what I was wanting to say.

**Comment by OrangeZXZ** [comment]
Youtube has custom Playlists like this but you need to be log in it could be a feature but hard to implement right now (I think) also it destroys the concept of RiMusic that is listen without acounts or subscription
