### ISSUE TITLE
[Feature]: SOME FINISHING TOUCHES

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#655]
### Description

1. Make the *corners of the toolbar rounded* and the bar rounded and little bit increase the size just like in yt music
(* = optional)
![image](https://github.com/fast4x/RiMusic/assets/120176369/7d12807f-de3b-4ed0-be89-51ea05fb2ee0)

2. The two bars looks weird
![Screenshot_20240210-134448](https://github.com/fast4x/RiMusic/assets/120176369/572ac8c6-304d-4d99-bce6-867ebebf2be8)

3. Can you make wavy timeline little thin 

4. Add an option to add sleep timer in the toolbar for quick access.

### Suggested Solution

Also please take a look on crashes 

### Additional Context

U DID A GREAT JOB IN FIXING AND ADDING  ALL THE USERS REQUESTS IN THE LATEST VERSION. HATS OFF!!

**Comment by fast4x** [comment]
1. I don't understand, what you mean for toolbar corners...

**Comment by faustaahmad** [comment]
I would prefer current style of toolbar/bottom bar
Personal preference, only like rounded icon & tiny bit rounded corner in screen
Perhaps square circle? Wont look so bad tbh, but I still prefer current style

![Screenshot_20240211-010324_ Via](https://github.com/fast4x/RiMusic/assets/45221211/bd85119a-0673-404f-9218-9ae781b6159d)
Square circle

**Comment by Logan7899** [comment]
> 1. I don't understand, what you mean for toolbar corners...
> 2. You mean I have to remove the bar?

![Polish_20240211_083246602~2](https://github.com/fast4x/RiMusic/assets/120176369/d68072c7-1758-44cd-aeeb-8979d7e2e84a)

**Comment by Logan7899** [comment]
Something like this

**Comment by Logan7899** [comment]
> 1. I don't understand, what you mean for toolbar corners...
> 2. You mean I have to remove the bar?

Yaa you have to remove dark toolbar bar

**Comment by Logan7899** [comment]
Before
![Screenshot_20240211-124448](https://github.com/fast4x/RiMusic/assets/120176369/6c883ee5-fd8a-4484-ab2f-02df337c81f4)

After
![Polish_20240211_125004018](https://github.com/fast4x/RiMusic/assets/120176369/4340362a-2d4e-45f5-b305-589da8358840)

Instead of search icon, you replace it with permanent search bar

**Comment by fast4x** [comment]
I also like the current style

**Comment by Logan7899** [comment]
> I also like the current style

Btw it is optional

**Comment by Logan7899** [comment]
> > 1. I don't understand, what you mean for toolbar corners...
> > 2. You mean I have to remove the bar?
> 
> ![Polish_20240211_083246602~2](https://private-user-images.githubusercontent.com/120176369/303895899-d68072c7-1758-44cd-aeeb-8979d7e2e84a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NDI1MjQsIm5iZiI6MTcwNzY0MjIyNCwicGF0aCI6Ii8xMjAxNzYzNjkvMzAzODk1ODk5LWQ2ODA3MmM3LTE3NTgtNDRjZC1hZWViLTg5NzlkN2UyZTg0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwOTAzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTg0Y2NkMTQxMzE2YTYyMjVmZThjOTVlZDVmOGM5OTAwMmUzMjA2OWYyNGE0MmYzYjI0ZDc1NWU0OTdmNTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rfe3u3rqS3Ith6xCDKse9ssUnh-usv3PpTCxe2oskwg)

@fast4x  what about this

**Comment by fast4x** [comment]
Added configurable sleep timer button on toolbar, available from version 0.6.22

**Comment by fast4x** [comment]
Ok for optional rounded toolbar

**Comment by Logan7899** [comment]
> Ok for optional rounded toolbar

will you be adding this feature

**Comment by fast4x** [comment]
> > Ok for optional rounded toolbar
> 
> will you be adding this feature
> 

Yes disabled by default, enable it from appearance settings

**Comment by Logan7899** [comment]
> > > Ok for optional rounded toolbar
> > 
> > 
> > will you be adding this feature
> 
> Yes disabled by default, enable it from appearance settings

since the community is growing you should create a telegram channel

**Comment by ikanakova** [comment]
> since the community is growing you should create a telegram channel

As I wrote here #461 I don't think the telegram is a good idea.

**Comment by Logan7899** [comment]
@fast4x please add pull down to refresh

**Comment by fast4x** [comment]
Under development

**Comment by fast4x** [comment]
All implementable was implemented. Available from version 0.6.23
