### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#657]
### Steps to reproduce the bug

Switching from another app to rimusic through recent apps

### Expected behavior

The app should open

### Actual behavior

The app crashed randomly

### Logs

FATAL EXCEPTION: DefaultDispatcher-worker-12
Process: it.fast4x.rimusic, PID: 25313
java.lang.IllegalStateException
	at sb.e.x0(SourceFile:1)
	at u3.z.l(SourceFile:1)
	at u8.z.r(SourceFile:30)
	at u8.z.i(SourceFile:13)
	at na.r.o(SourceFile:157)
	at na.d1.a(SourceFile:177)
	at na.c1.r(SourceFile:1)
	at u9.a.j(SourceFile:1)
	at ka.j0.run(SourceFile:1)
	at l.j.run(SourceFile:14)
	at qa.i.run(SourceFile:1)
	at qa.a.run(SourceFile:92)
	Suppressed: pa.h: [v1{Cancelling}@6a8c6d4, Dispatchers.IO]

### RiMusic version

0.6.21

### Android version

Android 12

**Comment by fast4x** [comment]
Hi, look this
https://github.com/fast4x/RiMusic/wiki/FAQs#-why-does-the-app-close-automatically-after-i-pause-it-for-a-while

**Comment by NikunjKhangwal** [comment]
That's weird. It doesn't happen in any other music app I've used. Disabling battery optimization is usually enough. But good to see at least there's a workaround.

**Comment by fast4x** [comment]
RiMusic requires user participation, no permission is used if the user does not enable it.

**Comment by NikunjKhangwal** [comment]
That makes sense
