### ISSUE TITLE
[Question]: import a Spotify playlist - .sjon -

### ISSUE THREAD

**Issue by JvM-nl** [fast4x/RiMusic#658]
### Description

Hi and thx for this very nice android app.
Is it possible to import a Spotify playlist ?
I have export my account data using the [Spotify account page ](https://accounts.spotify.com/nl/login?continue=https%3A%2F%2Fwww.spotify.com%2Fus%2Faccount%2Fprivacy%2F).
Now I have a zip with .sjon files ,but how can I import them in RiMusic

### Suggested Solution

Have a option to import Spotify data , because you can easy export it in spotify

**Comment by fast4x** [comment]
Hi, thanks, do you can attach here a playlist file? I'll check It if possible.

**Comment by andreapanontin** [comment]
I have one such file: [Playlist1.json](https://github.com/fast4x/RiMusic/files/14298541/Playlist1.json). I hope it helps :)

In the meantime thanks for all the work :)

**Comment by fast4x** [comment]
Unfortunately it is not possible because the codes of the songs change. You can import the playlist using a converter and then from YTM you can share it with RiMusic.
