### ISSUE TITLE
Synced lyrics scrolls in a weird way on tablet (large display issue?)

### ISSUE THREAD

**Issue by hakimifr** [fast4x/RiMusic#659]
### Steps to reproduce the bug

**Steps to reproduce:**
1. Open RiMusic
2. Play any music with synced lyrics, and toggle it

### Expected behavior

it scrolls properly

### Actual behavior

it does not scroll as it should (it scrolls properly on my phone)

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/67860246/c3553979-93b8-48ea-9d93-75907b1854e6

### RiMusic version

0.6.21

### Android version

Android 14, OneUI 6.0

**Comment by fast4x** [comment]
Hi, display inch? 
Can you explain me, if bug occur after a few minutes or immediately?

**Comment by Hakimi0804** [comment]
> Hi, display inch?

11 inch

> Can you explain me, if bug occur after a few minutes or immediately?

immediately

**Comment by faustaahmad** [comment]
Can confirm that's feels _flickering_ on 0.6.21 & non 11 inch screen, same problem but less flicker distance when change into next verse
Both on landscape/potrait orientation
Can change the title? "Synchronized lyrics flicker while playing"

**Comment by fast4x** [comment]
Try with new. version 0.6.29

**Comment by hakimifr** [comment]
> Try with new. version 0.6.29

It's working now with 0.6.29, thanks!

https://github.com/fast4x/RiMusic/assets/67860246/b8ca2789-81f9-4bcf-84f0-d827acb5d382

**Comment by fast4x** [comment]
Thanks for feedback
