### ISSUE TITLE
Cant save empty string on Lyrics

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#660]
### Expected behavior
Ability to save/confirm Lyrics even if it's empty string (not space)

### Actual behavior
Cant confirm if empty string
![Screenshot_20240210-234115](https://github.com/fast4x/RiMusic/assets/45221211/66996bf3-1adc-4eb6-aac8-b89b034435cc)

### RiMusic version

0.6.21

### Android version

Android 11

**Comment by fast4x** [comment]
Excuse me, but empty lyrics what's the use... If empty = empty why save It?

**Comment by fast4x** [comment]
Can't be bug... Empty Is empty... Lyrics empty = empty... 😂

**Comment by faustaahmad** [comment]
> Excuse me, but empty lyrics what's the use... If empty = empty why save It?

To make that text appear when there's no Lyrics 🤣
![Screenshot_20240210-235157](https://github.com/fast4x/RiMusic/assets/45221211/91e86a3e-24a7-4cdb-b72c-33c618b231ed)

**Comment by fast4x** [comment]
🤣🤣🤣🤣 explain me exactly what do you do

**Comment by faustaahmad** [comment]
Let me edit the pict a bit...
Done

**Comment by fast4x** [comment]
So, what i to do?

**Comment by faustaahmad** [comment]
Can save/confirm even the string is empty, that's it

**Comment by fast4x** [comment]
Implemented, available from version 0.6.22
