### ISSUE TITLE
Improve Back to top button

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#662]
### Steps to reproduce the bug

- Play music
Scroll up or press `^` go to playlist
FOCUS bottom right corner

- Scroll down in any songs list
FOCUS on bottom right corner

### Expected behavior

VISIBLE and better position

### Actual behavior

Icon blending, quite hard to spot if not focused enough
Icon position are ... yeah, why it's so high 

### Screenshots/Screen recordings

![](https://github.com/fast4x/RiMusic/assets/45221211/c8d33844-d9c6-430e-9d51-295acf1f758f)

![](https://github.com/fast4x/RiMusic/assets/45221211/45a7df28-acad-4d6f-badc-55ec2da11cbe)

### RiMusic version

0.6.21

### Android version

Android 11

**Comment by fast4x** [comment]
interesting

**Comment by kapitan-Prodigy** [comment]
> interesting
Maybe add a pill around the arrow for better visibility and less likely for accidental presses to the media behind arrow.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.22

**Comment by faustaahmad** [comment]
@fast4x edited title & description, turns out back to top button _barely visible_ in any songs list
