### ISSUE TITLE
[Feature] Sync about artist with selected language

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#663]
### Description

<table><tr>
<th>IDN RiMusic</th>
<th>IDN YouTube Music</th>
</tr><tr>
<td><img src="https://github.com/fast4x/RiMusic/assets/45221211/83d6cbf5-2365-4093-8ef9-084859bf5dca"></img></td>
<td><img src="https://github.com/fast4x/RiMusic/assets/45221211/06714d49-6134-4de1-b95e-4350eaf0ee95"></img></td>
</tr></table>

Also please add wikipedia link if possible

**Comment by fast4x** [comment]
Implemented, translation button in artist overview. Feature similar lyrics tanslation.
Available from version 0.6.22

**Comment by faustaahmad** [comment]
Cant parse the official translation?

**Comment by fast4x** [comment]
Seem no
