### ISSUE TITLE
Spotify, Apple Music You can add your favorite music and playlists in applications such as by connecting your account.

### ISSUE THREAD

**Issue by aydin0106** [fast4x/RiMusic#664]
### Description

Merhabalar, öncelikle geliştirdiğiniz aplikasyon çok güzel. Emeklerinize sağlık. Uygulamaya eklemenizi istediğim özellik Spotify, Apple Music, Amazon Music vs. gibi uygulamalarda olan beğenilen(favori) şarkılarımızı, çalma listelerimi direk uygulamaya ekliyebilmemizi sağlamanız, hesabımızı bağlandıktan sonra direk senkronize olması. Eklerseniz çok memnum olurum. Teşekkürler, başarılar. 

### Suggested Solution

Şimdiden teşekkür ederim.

**Comment by faustaahmad** [comment]
> Hello, first of all, the application you developed is very nice. Thank you for your efforts. The feature I want you to add to the application is Spotify, Apple Music, Amazon Music etc. Enabling us to add our favorite songs and playlists from applications such as directly to the application, and it will be synchronized directly after connecting our account. I would be very grateful if you add it. Thank you and success.
> 
> Translated with Google

First of all, RiMusic is based on ViMusic
They use YouTube and YouTube Music as source for songs
I dont think it's possible to implement without a dedicated server (for sync)

My suggestion to solve your problem 
\- Using 3rd party apps/website to sync your own playlist
\- Download all those songs into your phone storage
\- An algorithm to parse those playlist/songs & convert it into Youtube playlist/song
