### ISSUE TITLE
Search bar updates

### ISSUE THREAD

**Issue by Shi-Min-Yeoh** [fast4x/RiMusic#668]
### Description

Hi, 
I truly love ur app, it's the best
However I would love to have a different design of search bar 

### Suggested Solution

maybe replacing the coloured search bar with just one line ? Tq

**Comment by fast4x** [comment]
Hi thanks, explain better please, you want permanent visibile search bar?

**Comment by Shi-Min-Yeoh** [comment]
Sorry if I can't explain clearly as English is not my first language.
For the search bar on the search page, the original design is kinda like a box with background color
I just think it would be lovely if just make the search bar background become transparent and adding the border only on the bottom
Tq

**Comment by fast4x** [comment]
Implemented, search bar with bottom line, available from version 0.6.22

**Comment by Shi-Min-Yeoh** [comment]
Thanks ☺️
