### ISSUE TITLE
Crossfade 

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#671]
### Description

Crossfade music when changing song or it changes itself.

### Suggested Solution

Spotify, Black player, stellio, gaana uses this crossfade. and its really good to have.

**Comment by Vishcot** [comment]
@fast4x actually i was looking for an available repository for crossfade like spotify, so i found this in 100% Kotlin, can this work? 

https://github.com/andriiginting/crossfade-player 

and even it is available in javascript and css as well other than kotlin.

**Comment by fast4x** [comment]
Hi, I'll check It if compatible, thanks

**Comment by fast4x** [comment]
isn't compatible, I'll develop it soon

**Comment by fast4x** [comment]
Implemented crossfade songs effect, available from version 0.6.34

**Comment by Vishcot** [comment]
> Implemented crossfade songs effect, available from version 0.6.34

Woopps! Seriously? 
Thankyou so much, thanks a lotttt 🫡🫡

Just one more question, does it crossfade if we manually click on another song? 
Or only does when one song ends and another in queue starts playing?

**Comment by fast4x** [comment]
> > Implemented crossfade songs effect, available from version 0.6.34
> 
> Woopps! Seriously? Thankyou so much, thanks a lotttt 🫡🫡
> 
> Just one more question, does it crossfade if we manually click on another song? Or only does when one song ends and another in queue starts playing?

YES!

**Comment by Vishcot** [comment]
> Of corse there may be bugs that I then go to fix

No issues, someone once said "bugs are a part of development" haha! 😂
