### ISSUE TITLE
 [Feature]: hamburger menu in player (three dots) accessible from bottom

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#672]
### Description

hamburger menu in player (three dots) accessible from bottom

### Suggested Solution

hamburger menu in player (three dots) accessible from bottom

**Comment by fast4x** [comment]
Hi, but only from bottom or also from bottom?

**Comment by Vishcot** [comment]
> Hi, but only from bottom or also from bottom?

i didn't get you, but i meant is if possible, shift three dots menu to the bottom for easier access to "start radio".
![Screenshot_20240212-003907](https://github.com/fast4x/RiMusic/assets/136909951/51d7da94-b973-45d4-aba8-64031452192a)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.22
