### ISSUE TITLE
[Feature]: Not opening player screen if click on a song

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#673]
### Description

Not opening player screen if click on a song

### Suggested Solution

Not opening player screen if click on a song

**Comment by fast4x** [comment]
Hi, i don't understand.

**Comment by Vishcot** [comment]
> Hi, i don't understand.

hello, i meant if possible add a toggle to Enable force minimized player ( Keeps the player minimized even when another track is played.)

**Comment by fast4x** [comment]
Ahhhhhh ok... 😊

**Comment by fast4x** [comment]
Implemented by default without toggle in settings, available from version 0..22
