### ISSUE TITLE
App closes automatically when clicked on a song

### ISSUE THREAD

**Issue by manwiththeplan001** [fast4x/RiMusic#674]
### Steps to reproduce the bug

1. Open app
2. Search and choose a song to play
3. The app then closes automatically.

### Expected behavior

The song shoud play flawlessly

### Actual behavior

The app closes, if we repeat the steps as mentioned above, only the third attempt is sucessful.

### RiMusic version

0.6.21

### Android version

11

**Comment by fast4x** [comment]
Hi, look this for invincible service and disable battery optimization
https://github.com/fast4x/RiMusic/wiki/FAQs#why-does-the-app-close-automatically-after-i-pause-it-for-a-while
