### ISSUE TITLE
Visualizer not working 

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#675]
### Steps to reproduce the bug

1. Open app
2. Search any song
3. Click on visualizer

### Expected behavior

The visualizer should work flawlessly 

### Actual behavior

It stops working after couple of seconds

### Screenshots/Screen recordings

![Screenshot_20240211-130224](https://github.com/fast4x/RiMusic/assets/120176369/83c21138-5b93-4c25-a575-bd0d048584d6)

https://github.com/fast4x/RiMusic/assets/120176369/a793d6ab-f433-445b-9742-68bfe6924918

### RiMusic version

6.21.0

### Android version

Android 14

**Comment by Th3-C0der** [comment]
It's Working Perfectly For Me, Can You Describe How It Stopped Working?

**Comment by Logan7899** [comment]
It stops after couple minutes

**Comment by Th3-C0der** [comment]
Yes, I Am Facing The Same Problem Sometimes It Automatically Stops After Few Seconds, And The Only Way To Get It Working Is By Restarting The App.

**Comment by Logan7899** [comment]
> Yes, I Am Facing The Same Problem Sometimes It Automatically Stops After Few Seconds, And The Only Way To Get It Working Is By Restarting The App.
I think it is not optimised well

**Comment by fast4x** [comment]
Yes it's a know bug

**Comment by fast4x** [comment]
Improved visualizer, available from version 0.6.37
