### ISSUE TITLE
Some suggestions I thought of

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#676]
### Description

- [ ] 1. Ability to add song on multiple playlist at once. I mean a multiselect feature for that. Sometimes you want to add some songs on multiple playlist which is hard as it is now.

- [ ] 2. Ability to manage (renaming and deleting) playlist directly from library. Managing playlist by opening it all the time is kinda hard. It'd be great if there was a few things we could manage just from the library without opening playlist.

- [x] 3. Ability to see on which playlist/s a song is added on. Sometimes when I listen to certain songs I wonder if I already added that song on certain playlist. To find that out I need to open that certain playlist as of now. (There's another way…but that's not that easy either) So I'd like to be able to see on which playlist a song is added when I tap on "add to playlist".

- [ ] 4. Ability to set custom "quick pick" song. The most played song or the latest played song doesn't always help with quick picks. It'd be better to be able to select song manually for quick picks.

- [ ] 5. There ain't any warning for when clearing search history. Would've been fine if there was an auto backup feature already. Since that's not the case it might be kinda troublesome for some if they lose search history by mistakenly clicking on "Clear search history".

### Below suggestions aren't that good/important enough. But I'm sharing because still might be sometime useful.

- [ ] 6. Make the Discovery tab vertically scrollable instead of horizontal. I personally don't feel good to scroll this horizontally. I guess that's because I'm used to Android device and almost everything in Android is vertically scrollable that's why.

- [ ] 7. Ability to copy song title by "tap and hold". This is needed mostly for the songs that are of a language that I don't know how to write. This is probably needed other times as well but not much.

- [x] 8. Make only full screen mode lyrics clickable. (sounds like it might be a hard task…) Not really much needed. But when "toggle lyrics" feature is enabled it becomes a habit to click on the thumbnail to toggle lyrics. So on that occasion if the lyrics is clickable on the thumbnail then it's hard to toggle.

### Additional Context

I checked beforehand if anything I wrote here has been already suggested. Sorry if I missed.

**Comment by fast4x** [comment]
Wow, a lot of implementation.

**Comment by fast4x** [comment]
Other i can't devlop
