### ISSUE TITLE
[Feature]: Basic controls when lyrics are expanded

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#677]
### Description

Similar to how Spotify does it. Song title on top, controls at bottom and lyrics in middle for the rest of screen.

![Screenshot_2024-02-11-22-10-18-264_com spotify music](https://github.com/fast4x/RiMusic/assets/99175083/75659b4c-d483-4757-bf9a-a88678c3b70a)

### Suggested Solution

Show music progress bar & play/pause button below lyrics when lyrics are expanded. Additionally you can add previous and next buttons as well but they're less important.

**Comment by NikunjKhangwal** [comment]
Dev, Is there any plan of adding timeline (progress bar) on expanded lyrics screen as well? If not i can close this issue.

**Comment by aneesh1122** [comment]
@fast4x close this issue
