### ISSUE TITLE
long song download

### ISSUE THREAD

**Issue by megoo1997** [fast4x/RiMusic#678]
### Steps to reproduce the bug

When downloading a long song, it downloads part of the song and play back stop

https://github.com/fast4x/RiMusic/assets/159720948/20d6be6a-7e0a-4579-bad9-7ab05f3f6792

### Expected behavior

shoud when downloading a long music, it download full song not part.
and playback not stop.
like this video

https://github.com/fast4x/RiMusic/assets/159720948/79050242-a3a3-4736-ab04-4d8fd97a9477

### Actual behavior

this happened instead of download full song

### RiMusic version

0.6.21

### Android version

android 14

**Comment by fast4x** [comment]
Hi, add link of a long Song please.

**Comment by megoo1997** [comment]
ok bro ,
https://music.youtube.com/watch?v=1pcUSlnNcbE

**Comment by fast4x** [comment]
Try to set minimum quality audio from settings and try again tò download.

**Comment by megoo1997** [comment]
i already chaged quality high , normal and low , no change.
still buged.

**Comment by megoo1997** [comment]
i think any song its duration more than 10 minutes It contains the same error..

**Comment by fast4x** [comment]
Yes you are right.
Now song is downloading also with is more slowly specific song.
Other are downloaded fast.

in a few minutes i link to you a custom version, try it and send me feedback.
Thanks

**Comment by megoo1997** [comment]
ok bro, i am waiting..
thamk u

**Comment by fast4x** [comment]
Downloaded song without problem.
Try this custom version
https://rimusic.xyz/download

**Comment by megoo1997** [comment]
bro i try it for a while
download song is fixed, thanks for that..
but download speed is very very slow and take some time
thank u

**Comment by fast4x** [comment]
Thanks you for feedback

**Comment by megoo1997** [comment]
thanks..
but can i make download speed faster?

**Comment by fast4x** [comment]
Depend by geographic area and type of quality available. Try to set low quality...

**Comment by megoo1997** [comment]
ok but just so u know the song after 20 minutes not download..
and speed when download only its very slow ilke this screen..
![Screenshot_20240212_001720](https://github.com/fast4x/RiMusic/assets/159720948/4688d746-e019-4323-b9d3-de2a71fd9b63)
