### ISSUE TITLE
French language

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#68]
### Steps to reproduce the bug

Some translation is missing 

### Expected behavior

Some translation are missing in settings

### Actual behavior

Cloud u add it ?

### RiMusic version

0.6.7

### Android version

A12

**Comment by fast4x** [comment]
Have you updated your fork?

**Comment by NEVARLeVrai** [comment]
Oh no

**Comment by fast4x** [comment]
Ok, update your fork from Git -> Update project and translate it
