### ISSUE TITLE
LEFT SWIPE to DELETE & RIGHT SWIPE to play NEXT

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#680]
### Description

LEFT SWIPE to DELETE & RIGHT SWIPE to PLAY NEXT in Favourites! 
and it would feel so nice, if it also gives a haptic feedback while swiping right or left similar to Spotify.

![Screenshot_20240212-004916](https://github.com/fast4x/RiMusic/assets/136909951/fe9472b2-82fa-487a-96f1-11746bd2e7c8)

### Suggested Solution

LEFT SWIPE to DELETE & RIGHT SWIPE to play NEXT in Favourites

**Comment by Vishcot** [comment]
and it would feel so nice, if it also gives a haptic feedback while swiping right or left similar to Spotify.

**Comment by VINULA2007** [comment]
It could be annoying if I did it accidentally

**Comment by fast4x** [comment]
It's Just available similar feature swipe tò action in playlist
