### ISSUE TITLE
Whole Black Theme but with dynamic color in player portion

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#682]
### Description

Another option of Whole Black Theme throughout the app but at the same time dynamic colors according to album art in player screen, similar to what spotify / ymusic has.

### Suggested Solution

will look more clean and beautiful.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.25

**Comment by dAtA-TRoN** [comment]
> Implemented, available from version 0.6.25

https://github.com/fast4x/RiMusic/assets/71184627/694bf9bf-e042-4086-b738-6e952b36fa93

**Comment by fast4x** [comment]
LOL
