### ISSUE TITLE
download speed very slow

### ISSUE THREAD

**Issue by mohamed-magdy2214** [fast4x/RiMusic#683]
### Steps to reproduce the bug

hi
the speed when download song its very slow  and take som time untill finish download
thats for download only, playback play for full speed.

### Expected behavior

the download speed must to be full speed

### Actual behavior

this happened for download speed

### Screenshots/Screen recordings

![WhatsApp Image 2024-02-12 at 00 59 14_0bc4dace](https://github.com/fast4x/RiMusic/assets/108136012/9da91f17-e3fd-4639-ba04-3b7d9bda6458)

### RiMusic version

0.6.21

### Android version

android 13

**Comment by fast4x** [comment]
You use proxy?

**Comment by mohamed-magdy2214** [comment]
no bro, but I try to use it but it gives to me the same result

**Comment by fast4x** [comment]
With other songs same time?

**Comment by mohamed-magdy2214** [comment]
no, the short songs were downloaded quickly and used full speed of download speed.

**Comment by fast4x** [comment]
in fact, could be a geographical problem, from me the song download very fast

**Comment by mohamed-magdy2214** [comment]
if it geographical problem, it will be in all songs the short and long songs  but, I have this problem only with long songs

**Comment by ikanakova** [comment]
Could it be related to YouTube throttling all requests for its streams? Viz https://github.com/TeamNewPipe/NewPipe/pull/9948.

**Comment by fast4x** [comment]
I’ll try to understand the problem better
