### ISSUE TITLE
Synchronized Lyrics broken/paused

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#684]
### Steps to reproduce the bug

SPAM/Double click same verse inside synchronized lyrics
Clicking on current verse wont trigger the bug/pause
Congrats, it's paused now

### Expected behavior

Normally change verse as the timer goes up

### Actual behavior

Timer goes up but Lyrics are paused stuck on last clicked verse

### RiMusic version

0.6.21

### Android version

Android 11

### Additional information

Rate limit the click under the hood?
example: can only click same verse every 1s or so...

**Comment by fast4x** [comment]
It’s normal that by clicking a verse, the song starts from the associated time
