### ISSUE TITLE
Cached Songs are being deleted

### ISSUE THREAD

**Issue by Khaledsame** [fast4x/RiMusic#687]
Hey.
I like you app very much, But every time there is an update for the app, All Cached songs delete by it self.

**Comment by fast4x** [comment]
Hi thanks, increase player cache in settings

**Comment by fast4x** [comment]
Your Android version?

**Comment by Khaledsame** [comment]
Yes, the android version, and it deletes it after any update to the app, and i have increased it to it's maxmium, and each update it just deletes all cached songs by it self.

**Comment by Khaledsame** [comment]
@zereft01 yeah that happened to me too after the final update

**Comment by fast4x** [comment]
Check cache space in settings...

**Comment by zereft01** [comment]
I have given it 512 MB of cache..

**Comment by fast4x** [comment]
and much space is occupied...?

**Comment by zereft01** [comment]
Currently it is using 0 MB of cache, because when I don't open the app in a few hours it deletes itself.
When I open it again I don't have any songs in the cache....

**Comment by zereft01** [comment]
Thanks to you, I hope they can solve it. It's a great app.

**Comment by fast4x** [comment]
Thanks, I’ll definitely fix it.
Also with new feature planner, for manual  cache clear.

**Comment by zereft01** [comment]
Sure, I'll review it when that version is available. Thanks

**Comment by fast4x** [comment]
Available from version 0.6.23

**Comment by Khaledsame** [comment]
Ok thank you , and i hope it works.

**Comment by fast4x** [comment]
If it doesn’t work yet don’t worry I’ll keep looking for the bug

**Comment by zereft01** [comment]
Very good, maybe when the next version comes out I'll let you know how it goes.
 We will keep in touch here.

**Comment by zereft01** [comment]
Hi, I have tried version 0.6.23 and the problem persists...

**Comment by Khaledsame** [comment]
Please reopen the issue, to just be a reminder.

**Comment by fast4x** [comment]
i don't understand I'll check again

**Comment by fast4x** [comment]
try custom version from website please
https://rimusic.xyz/download

**Comment by Khaledsame** [comment]
Ok, I'll try it for the day and get back to you, Thank U.

**Comment by zereft01** [comment]
Understood, I'll try it and let you know later. Thank you

**Comment by zereft01** [comment]
I already tried it and the same thing keeps happening. And sorry for my inglish I do not speiak inglish.

**Comment by Khaledsame** [comment]
Yeah, Me too, But it seems to be working after changing the ROM for An Android 14 Version, And it seems to be working for me now.
