### ISSUE TITLE
How About Vertical swipe based songs Change?

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#688]
### Description

Vertical swipe based song Changes when swiping up or down on player ( with haptic feedback (if you prefer) ) . it is more convenient while changes songs of our library as well as in radio queues..

![Screenshot_20240212-165348](https://github.com/fast4x/RiMusic/assets/136909951/9fa2b83b-ddff-41dd-9eee-6d4e75d8021b)

### Suggested Solution

Vertical swipe based songs Change also with haptics feedback
similar example: Resso (byte dance product) gained popularity because of Tiktok's intuitive style of changing songs and quick access.

**Comment by ikanakova** [comment]
I find the current solution - horizontal swipe much more logical... But if it were optional, it would probably be great for some users.

**Comment by fast4x** [comment]
Verticale swipe in player is captured by show queue... I'm not sure if it's possible.

**Comment by Vishcot** [comment]
> Vertical swipe in player is captured by show queue... I'm not sure if it's possible.

i have two ideas for this, if you like: 

what if queue will be accessed through tapping? 
like: ( whenever we tap the queue area, it automatically gets up and then we can do whatever we do in that particular portion? ) 


OR! 


queue will be accessed through right to left swipe like hungama music app does! just swipe left and queue comes out from the left side and then we can do things we would like.

**Comment by ikanakova** [comment]
This is RiMusic, a fork of ViMusic. I doubt most users would be thrilled with these changes unless it was optional. Unless it can be made optional, I don't think the logic of vertical and horizontal swipes should change.

**Comment by fast4x** [comment]
Ideas are welcome, but this isn't planned. Thanks for your idea.
