### ISSUE TITLE
[Feature]: add email

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#690]
### Description

I would like to suggest adding the option to include an extension to input the email address. I know that some users may not like this (and as I am new, I am not aware of the reason why it hasn't been implemented yet).It would be very helpful for certain users to be able to input their email accounts and thus save the songs they download.

### Suggested Solution

Since Rimusic is based on Youtube Music, I believe implementing this option should be straightforward. Thank you in advance.

**Comment by fast4x** [comment]
Hi, thanks for your request, but isn't planned.
Look this for reason https://github.com/fast4x/RiMusic/wiki/FAQs#why-there-are-no-plans-to-implement-google-or-youtube-login
