### ISSUE TITLE
Not able to enable read access to device storage

### ISSUE THREAD

**Issue by adhithya1994** [fast4x/RiMusic#691]
### Steps to reproduce the bug

Clicked the 'On the device' tab

### Expected behavior

It should show MP3 files in the device

### Actual behavior

Pop-up shows 'read access to be granted for the device'.
Which was worked well in previous versions

### Screenshots/Screen recordings

![Screenshot_2024-02-13-06-56-45-231-edit_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159859813/f171625e-e7b5-489c-875d-ab9f31383ead)

### RiMusic version

0.6.21

### Android version

Android 12

**Comment by fast4x** [comment]
Hi, try this custom version, it should work.
Download from RiMusic website https://rimusic.xyz/download
Send me feedback please.

**Comment by adhithya1994** [comment]
I installed the Version 0.6.22, now its working, thank you for the quick response

![Screenshot_2024-02-13-13-32-16-838-edit_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159859813/a71172d4-4269-433d-b837-627788bd1aa2)

**Comment by fast4x** [comment]
> I installed the Version 0.6.22, now its working, thank you for the quick response
> 
> ![Screenshot_2024-02-13-13-32-16-838-edit_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159859813/a71172d4-4269-433d-b837-627788bd1aa2)
> 
> 

Attention, is a custom version 0.6.21 , next Friday Will be version 0.6.22
