### ISSUE TITLE
Crash after confirm edit lyrics on full screen mode

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#692]
### Steps to reproduce the bug

• Play any songs
• Trigger lyrics
• Toggle full screen lyrics
• Click three dots on bottom right corner
• Edit Lyrics → Confirm
• Crash

### Expected behavior

Lyrics saved

### Actual behavior

Crash & doesnt save the lyrics

### RiMusic version

0.6.21

### Android version

Android 11

### Additional information

This a feature request, please lower song title location on full screen lyrics since currently they are too close to statusbar

**Comment by fast4x** [comment]
Fixed, available from version 0.6.22
