### ISSUE TITLE
[Feature]: Refresh quick picks manually

### ISSUE THREAD

**Issue by 77-77SP** [fast4x/RiMusic#693]
### Description

Hi, First of all thank you for your amazing work and dedication.

I would like to suggest adding a manual refresh button for quick picks.

### Suggested Solution

A refresh button located near the **Tips** tab in the **Quick Picks** which upon pressing would provide recommendation for the current song. When no song is currently played the button would be grayed out. When there is no internet connection the button will be also grayed out.

I think it might solve possible future issues with the recommendation feature such as denial-of-service issue with the **tips by last played song** due to the large requests made to the server. A user who enables the **tips by last played song** might listen to many songs but would only like to see tips for a few which means all the recommendation requests for the other songs are unnecessary.

Other issue it might solve is that sometimes due to network issues, recommendation tips will not refresh or give an error. Currently, when it happens to me, I need to either restart the app or cycle back and forth between songs.

Many thanks.

**Comment by fast4x** [comment]
Hi, thank you.
This feature is under development

**Comment by fast4x** [comment]
Implemented, available from version 0.6.30
