### ISSUE TITLE
[Feature]: last fm scrobel Support 

### ISSUE THREAD

**Issue by Lio-gif** [fast4x/RiMusic#694]
### Description

Last fm Support so i can track What i am Hearing 

### Suggested Solution

Maybe combin IT with the Statistics tab

**Comment by ikanakova** [comment]
duplicity to #61

**Comment by fast4x** [comment]
At the moment there is not much information on how to develop it

**Comment by OrangeZXZ** [comment]
@fast4x @Lio-gif This isn't planned, so could it be closed?

**Comment by fast4x** [comment]
It's marked as to close before next release
