### ISSUE TITLE
[Feature]: Multiple Selections

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#695]
### Description

Selecting multiple songs at one could be really handy to add several songs to favorites or a playlist 

### Suggested Solution

Multiple selection ability with a options window popped up after clicking a button

**Comment by fast4x** [comment]
Hi this feature is just available from albums, and from version 0.6.22 also in playlists...

**Comment by VINULA2007** [comment]
![Screenshot_2024-02-17-10-55-10-794_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89296867/d033a7dd-10e5-4bcf-b039-b82ee562ff7f
Still not available for playlists

**Comment by VINULA2007** [comment]
And is there a way to turn off swipe gesture thingy 
![Screenshot_2024-02-17-11-00-51-813_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89296867/64905893-a772-4a8f-bba3-2167610e0c5e)

**Comment by fast4x** [comment]
> ![Screenshot_2024-02-17-10-55-10-794_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89296867/d033a7dd-10e5-4bcf-b039-b82ee562ff7f)
> Still not available for playlists

Yes, you’re right I’m wrong yet there is no selection in the playlist.

I'll add soon

**Comment by fast4x** [comment]
> And is there a way to turn off swipe gesture thingy 
> ![Screenshot_2024-02-17-11-00-51-813_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/89296867/64905893-a772-4a8f-bba3-2167610e0c5e)
> 

I add it soon

**Comment by fast4x** [comment]
Implemented, enable/disable from Other settings > Swipe to action, by default is enabled.
Available from version 0.6.23

**Comment by fast4x** [comment]
Implemented selectable songs in all playlists
