### ISSUE TITLE
Horizontal Gestures for changing songs only on Album Art Area

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#696]
### Description

Horizontal gestures (swiping right or left inside player) for changing songs only on Album Art Area as this will prevent from unintentional right swipes ( which eventually changes songs ) while swiping downward to minimise the player.

### Suggested Solution

Horizontal gestures (swiping right or left inside player) for changing songs only on Album Art Area as this will prevent from unintentional right swipes ( which eventually changes songs ) while swiping downward to minimise the player.

**Comment by OlimitLolli** [comment]
Yeah, it often happens that when i want to skip within a song I skip the whole song because i click slightly over or under the bar

**Comment by Vishcot** [comment]
> Yeah, it often happens that when i want to skip within a song I skip the whole song because i swipe slightly over or under the bar

yeah, it is happening quite often for me as well.

**Comment by fast4x** [comment]
I will try to improve the sensitivity of gestures in the player.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.22
