### ISSUE TITLE
[Feature]: automatic selection of synchronised lyrics

### ISSUE THREAD

**Issue by jaki444** [fast4x/RiMusic#698]
### Description

It would be nice to have the option that when we activate the lyrics display (if the option in the settings is activated) it shows if the synchronised one is available and if it is not available then it shows the unsynchronised one.

### Suggested Solution

add an option that automatically selects the lyrics mode in the settings. you could do this by putting a small control when the lyrics class is activated

**Comment by fast4x** [comment]
This is implemented
