### ISSUE TITLE
when touching the synchronised lyrics, they de-synchronise

### ISSUE THREAD

**Issue by jaki444** [fast4x/RiMusic#699]
### Steps to reproduce the bug

if I touch the synchronised lyrics at the bottom desyncroniserrano the same thing happens if I spam the lyrics.

### Expected behavior

In addition to the audio going at some point, the lyrics should also go.

### Actual behavior

lyrics remains stuck where it was when you tap on the lyrics 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/123010345/be5b1fd0-9446-4618-b491-23521edd3d0c

### RiMusic version

0.6.21

### Android version

android 13

**Comment by faustaahmad** [comment]
Duplicate #684
