### ISSUE TITLE
added link to artist page

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#7]
### Description

Clicking on the artist's name in the song player below the title should take you to the artist's page. Without the current detours.

Would such a function be possible.

### Suggested Solution

*
![Uploading Screenshot_20231001-004337.jpg…]()

**Comment by fast4x** [comment]
Uploaded screenshot is damaged, can you re upload, please?

**Comment by siggi1984** [comment]
![Screenshot_20231003-095835](https://github.com/fast4x/RiMusic/assets/103368536/9fc63e06-4580-4d65-b4ba-ee5d891f0fda)

**Comment by fast4x** [comment]
Thanks

**Comment by fast4x** [comment]
Feature implemented, available in next release.

**Comment by siggi1984** [comment]
Does not work, can click on the artist name as much as I want nothing happens

**Comment by fast4x** [comment]
have you tried clicking on different points of the artist's name, in different songs? Android version?

**Comment by siggi1984** [comment]
> have you tried clicking on different points of the artist's name, in different songs? Android version?

I have tried umpteen songs and clicked around at various points without a reaction.

Android 12

**Comment by fast4x** [comment]
Ok, your device type?
I try to understand problem.

**Comment by dainvincible1** [comment]
for me it works when there is a single artist but if there are more than one artist then no reaction is there

https://github.com/fast4x/RiMusic/assets/127825700/463e1853-cffc-40f5-878d-69f9d998a2ba

**Comment by fast4x** [comment]
Yes, I confirm that with more than one artist there is no reaction because he can not open more than one artist page at the same time.
It would be nice to be able to choose which one to open.

There is another condition in which there is no reaction, when the song does not have the artist code, there is no reaction, there can not be because the artist has only the name and not the code that serves to identify it.

These are unofficial songs, not by the original artist, copies.

**Comment by fast4x** [comment]
I change the coloring of the artist name if the song does not have the artist code.
I try to handle the case with more than one artist, choosing which one to open.

**Comment by fast4x** [comment]
I found the bug that disables the click to the artist page.

**Comment by fast4x** [comment]
@dainvincible1 @siggi1984 There were some conditions where artist information was not handled
Fixed on v0.6.3 published now

**Comment by siggi1984** [comment]
Works now.  Thank you for your work.
Well done 👍
