### ISSUE TITLE
Can't play when mobile data is enabled

### ISSUE THREAD

**Issue by jazznfunk** [fast4x/RiMusic#700]
### Steps to reproduce the bug

1. turn off Wi-Fi
2.. turn on mobile data
3. open RiMusic
4. try to play some song

### Expected behavior

it is expected to app act normally as on Wi-Fi

### Actual behavior

RiMusic hangs up / closes/ shows "an unknown playback error has occoured. Restart app please"

### RiMusic version

0.6.20

### Android version

Android 12

### Additional information

Samsung SM-G970U

**Comment by fast4x** [comment]
I'm sorry but not have idea, not depend from rimusic.

**Comment by ikanakova** [comment]
Have you checked that the use of the data is allowed  (Settings - Applications - Rimusic - Data usage)?

What's your mobile network 2G, 3G, 4G, 5G?

What is the mobile IP address on the mobile network and Wi-Fi? IPv4 or IPv6?

**Comment by jazznfunk** [comment]
Thank You for answers.
Yes, data is not restricted, There is good coverage and 4G network. I think it's IPv4.
On WiFi app works just fine.

**Comment by ikanakova** [comment]
And music.youtube.com works the same on Wi-Fi and data? Doesn't it require a captcha on the data, for example?

**Comment by jazznfunk** [comment]
Yes, music.youtube.com works as expected. Tested in duckduckgo browser on mobile data.

**Comment by ikanakova** [comment]
Did you try after the message "an unknown playback error has occoured. Restart app please" force stop app in Settings > Applications > Rimusic > Force stop?

If so, I would try changing the DNS on the data network to google DNS: 8.8.8.8 and 8.8.4.4 in Settings > More connection settings > Private DNS.
