### ISSUE TITLE
Menu pop-up idea

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#701]
### Description

I was using youtube and noticed this sick menu i think it could be similar on RiMusic

![Screenshot_20240213_165923_YouTube](https://github.com/fast4x/RiMusic/assets/104271365/440cec67-2768-4f9f-941a-d42672318322)

### Suggested Solution

Replace this blocky menu

![Screenshot_20240213_165813](https://github.com/fast4x/RiMusic/assets/104271365/5863f5f5-8bb7-423f-8c90-75485e28dda6)

With something rounder

![Screenshot_20240213_165923_YouTube](https://github.com/fast4x/RiMusic/assets/104271365/f6d632ac-5658-4f76-9fe0-2e2973d0de4e)

3 Solution in "Alternatives"

### Alternatives

Aditional idea:
Somme pop-up (multiple choises) like languages, visualiser look, etc.. could be the same pop-up menu as the menu from the player (because the pop-up used now i think it is better only for confirmation and information while the menu is for choises and you can add icons that gose well with the choises)

**Comment by OrangeZXZ** [comment]
> Somme pop-up (multiple choises) like languages, visualiser look, etc.. could be the same pop-up menu as the menu from the player (because the pop-up used now i think it is better only for confirmation and information while the menu is for choises and you can add icons that gose well with the choises)

Some more examples :
- Artists pop-up
- App language pop-up
- Visualizer style pop-up
- Delete queue pop-up (not the confirmation since it is an Yes, No Choise)

In short all the "multiple choises" and not the confirmations, errors, informational pop-up (like "You need to activate that")

**Comment by fast4x** [comment]
You’re saying replace popups with context menus

**Comment by OrangeZXZ** [comment]
> You’re saying replace popups with context menus?

yeah some pop-ups would be better as an context menu

**Comment by fast4x** [comment]
Can you please tell me where you would like to implement

**Comment by OrangeZXZ** [comment]
> Can you please tell me where you would like to implement

Clear queue options and maybe artists im not sure if there are other (Maybe the pop-up in settings like visualizer styles, default page, etc... if it dosen't look bad)

Basically anything that isn't a Yes or No pop-up

**Comment by OrangeZXZ** [comment]
> > Can you please tell me where you would like to implement
> 
> Clear queue options and maybe artists im not sure if there are other (Maybe the pop-up in settings like visualizer styles, default page, etc... if it dosen't look bad)
> 
> Basically anything that isn't a Yes or No pop-up
> 
> Edit: oh yeah also the sort options since now it is merged in one icon

And icons like on Youtube would be nice to identify faster thing's maybe also making the burger menu float like on youtube instead of taking all the screen

**Comment by fast4x** [comment]
> Edit: oh yeah also the sort options since now it is merged in one icon

New version 0.6.22 not have sorting icons but name selector...
![Screenshot_20240215_173132](https://github.com/fast4x/RiMusic/assets/1484476/d0e4f648-87f4-48fe-be97-eeb27f2368c4)

**Comment by fast4x** [comment]
Ok i understand, i like idea

**Comment by fast4x** [comment]
First implementation:
Implemented context menu and new improved selectable songs in albums include #695 
Available from version 0.6.22

**Comment by fast4x** [comment]
Implemented, also in new menu sorting order 💯

**Comment by fast4x** [comment]
Of course available from version 0.6.22

**Comment by fast4x** [comment]
More implementations available from version 0.6.23

**Comment by fast4x** [comment]
Last implemented in version 0.6.26
