### ISSUE TITLE
miniplayer in queue

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#702]
### Description

on Youtube Music when you go in the queue the cover gose to the top in a mini player like in this screenshot.

![SmartSelect_20240213_173415_YouTube Music](https://github.com/fast4x/RiMusic/assets/104271365/6409428d-abbf-4e95-8ef0-7ee8c9d9ed65)

### Suggested Solution

add mini player at the top of queue (maybe same size as the bottom bar that way the animation looks cooler maybe?)

### Alternatives

Also like on YT Music the mini player has the background of the song and not the background of the queue (verry important detail in my opinion)

also add a similar animation if posible? i mean it is only a linear movement and shrink between 2 places but it make navigating mutch smoother (and more responsible when slowly pull up the queue since the animation adapt to the position of the queue top)

**Comment by aneesh1122** [comment]
this can also be closed. right?

**Comment by OrangeZXZ** [comment]
> this can also be closed. right?

Yes, we have the down player when looking in the queue. Thanks for remembering me. You are doing God's work.

**Comment by aneesh1122** [comment]
> > this can also be closed. right?
> 
> Yes, we have the down player when looking in the queue. Thanks for remembering me. You are doing God's work.

I'm looking for some issues to fix. Figured I should look at the oldest issues.
