### ISSUE TITLE
Update Settings look

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#703]
### Description

The settings aren't that bad but there is a thing that bothers me a bit

There is a screen of 2 settings in RiMusic
![SmartSelect_20240213_173719](https://github.com/fast4x/RiMusic/assets/104271365/444e70ff-b2aa-49f2-9b55-5e42ba64c288)

If I want to disable Visualizer i need to press on it and set on off (it works but could be better)

There are some settings on my samsung device
![SmartSelect_20240213_213748_Settings](https://github.com/fast4x/RiMusic/assets/104271365/a77dfc53-4a8c-4ae5-bed0-91d6e9479c6d)

Even if there are more choice "off" is not one if I want to turn off I simply press the right switch and it turns gray (i find this mutch better)

You can also press the left part to chose the option but only if it is turned on and not grey

### Suggested Solution

Add switches on settings that have an "Off" in the pop-up options

Also similar options like what should be shown in the bottom bar or butons in the android player should be merged as an multiple choise pop-up with checkboxes
(will be mutch more lighter to the eyes) these dont need an switch since deselecting all means "off"

**Comment by fast4x** [comment]
Ok i understand

**Comment by fast4x** [comment]
I would like to make it pop-up, if off the setting type choice is not visible. If turned on, I can select the type. You like it?

**Comment by fast4x** [comment]
Will be developed with #679

**Comment by aneesh1122** [comment]
and this?

**Comment by OrangeZXZ** [comment]
> and this?



> and this?

I'm going to close it because we can choose directly in the player
