### ISSUE TITLE
Songs still missing artist/duration from playlist after updating

### ISSUE THREAD

**Issue by LordGarySugar** [fast4x/RiMusic#704]
### Steps to reproduce the bug

1. Install an older app version (0.6.14)
2. Add a song to a playlist
3. Upgrade to latest version (0.6.21)
(Additional actions tried that have no effect)
1. Delete songs from playlist
2. Clear app cache
3. Re-add same song to playlist
(Additional actions tried that have no effect)
1. Delete song from playlist
2. Export database
3. Delete app & reinstall
4. Re-import database
5. Re-add songs

### Expected behavior

Songs appear with artist and duration when app has been updated

### Actual behavior

Songs are missing artist and duration is replaced by views

### Screenshots/Screen recordings

![20240213_204742](https://github.com/fast4x/RiMusic/assets/116962238/510bb104-2c4a-4086-91f1-3aa322eba970)
![Screenshot_20240213_204706](https://github.com/fast4x/RiMusic/assets/116962238/371acde6-fcfa-41bb-99fd-044cf7c7a1bf)

### RiMusic version

0.6.21

### Android version

Android 10 / Android 14

### Additional information

The songs have the correct artist and duration listed in the search function, but are stuck in my playlist with this data missing.

**Comment by fast4x** [comment]
I don't understand why install an obsolete version.

**Comment by LordGarySugar** [comment]
> I don't understand why install an obsolete version.

I installed an older version to try to work out why it happened originally. Since I have upgraded versions, a few songs are stuck with the artist missing with no way to refresh the database without wiping everything.
