### ISSUE TITLE
Playlist showing album art of last selected playlist

### ISSUE THREAD

**Issue by LordGarySugar** [fast4x/RiMusic#705]
### Steps to reproduce the bug

1.Open a playlist
2.Open another

### Expected behavior

Album art grid should match the top 4 songs in playlist

### Actual behavior

Album art grid shown is from the last opened playlist

### Screenshots/Screen recordings

![Screenshot_20240213_205610](https://github.com/fast4x/RiMusic/assets/116962238/08361d6d-d340-460c-bf57-5c37767d9086)
![Screenshot_20240213_205615](https://github.com/fast4x/RiMusic/assets/116962238/8c131b36-d0ed-4ce1-81a2-a12ac9118c7b)

### RiMusic version

0.6.21

### Android version

Android 14

**Comment by fast4x** [comment]
Fixed, available from version 0.6.23
