### ISSUE TITLE
Missing translation strings in crowdin

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#708]
### Description

Can use this issue to track missing strings in crowdin

**Inside Appearance**
• [Use font type](https://github.com/fast4x/RiMusic/issues/499#issuecomment-1936968096)

**Other → Enable update menu**
• Ask

**Other**
• CHECK UPDATE
• SCREEN

### Suggested Solution

Dont close this issue to prevent duplicate
Hide unrelated discussion to prevent clutter
I'll try to update the list every so often

**Comment by fast4x** [comment]
I apologize, as I said to @NEVARllvrai before, we work on separate tasks because it becomes difficult to keep them in mind.

Implemented, available from version 0.6.22
