### ISSUE TITLE
[Feature]: Song download

### ISSUE THREAD

**Issue by GamerKing1403** [fast4x/RiMusic#71]
### Description

I just wanted to know what is the current situation on song downloads. Downloaded songs are the only thing that is stopping from switching to this app.

### Suggested Solution

Adding Download Feature

**Comment by siggi1984** [comment]
> ### Description
> 
> I just wanted to know what is the current situation on song downloads. Downloaded songs are the only thing that is stopping from switching to this app.
> ### Suggested Solution
> 
> Adding Download Feature
> ### Alternatives
> 
> _No response_
> ### Additional Context
> 
> _No response_

https://github.com/fast4x/RiMusic/issues/15

**Comment by fast4x** [comment]
Hi, the download feature is under development.
From version 0.6.7 you can already see if the song you are listening to is downloaded completely.
From next version you can also filter the downloaded songs in various places of the app

Development will continue until the download functionality is complete.

![Screenshot_2023-11-03-16-46-54-142_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/1484476/f7580681-ff93-4b08-a2b7-3c747096be5e)
![Screenshot_2023-11-03-16-50-21-768_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/1484476/11e1d16f-0a4d-42ad-a9e9-b53f46fe42da)

**Comment by GamerKing1403** [comment]
Okk perfect. Thanks

**Comment by dainvincible1** [comment]
> Hi, the download feature is under development. From version 0.6.7 you can already see if the song you are listening to is downloaded completely. From next version you can also filter the downloaded songs in various places of the app
> 
> Development will continue until the download functionality is complete.
> 
> ![Screenshot_2023-11-03-16-46-54-142_it fast4x rimusic](https://user-images.githubusercontent.com/1484476/280338038-f7580681-ff93-4b08-a2b7-3c747096be5e.jpg) ![Screenshot_2023-11-03-16-50-21-768_it fast4x rimusic](https://user-images.githubusercontent.com/1484476/280338044-11e1d16f-0a4d-42ad-a9e9-b53f46fe42da.jpg)

i think it'll be better if downloaded songs are downloaded in cache or exo file rather than mp3

**Comment by fast4x** [comment]
Yes, it's downloaded in exo cache not externally.

**Comment by ikanakova** [comment]
> Yes, it's downloaded in exo cache not externally.

Then some other button would be better.

**Comment by fast4x** [comment]
You mean use a different button?

**Comment by ikanakova** [comment]
> You mean use a different button?

Yes, one that doesn't make users think it's a classic download.

**Comment by NEVARLeVrai** [comment]
In 0.6.8 the button doesn't work?, also it missing in big player and mini player

**Comment by fast4x** [comment]
In the release notes we talk about download status not that you can download..

This ticket are in progress...

**Comment by fast4x** [comment]
The download functionality is in pre-release, it will obviously be improved.

**Comment by fast4x** [comment]
Download feature added.
Available from 0.6.10

**Comment by fast4x** [comment]
At the moment there is a bug that does not allow to remove the download.

**Comment by fast4x** [comment]
Improvements will be available to next version
