### ISSUE TITLE
[Feature]: adding playlists to playlists

### ISSUE THREAD

**Issue by OlimitLolli** [fast4x/RiMusic#713]
### Description

it would be more convenient if you can add a playlist to another playlist, so you don't have to add each song idividually

### Suggested Solution

add a button in the 3 dots menu (where you can edit a playlist) with which you can add a playlist to another

**Comment by fast4x** [comment]
Adding playlist in other playlist would be adding all songs from first?

**Comment by OlimitLolli** [comment]
Yes

**Comment by fast4x** [comment]
Ok

**Comment by fast4x** [comment]
This feature Is Just available in albums...

**Comment by fast4x** [comment]
Implemented, available from version 0.6.22 (in three dots > context menu)
