### ISSUE TITLE
Replace kugou.com synchronized lyrics

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#715]
### Description

I don't realy know kugou.com but i think maybe there is a better api for synchronized lyrics

### Suggested Solution

Replace kugou lirics and replace with something better if there is one

**Comment by ikanakova** [comment]
Wouldn't it help to be inspired by this app: https://github.com/TecCheck/FastLyrics?

**Comment by fast4x** [comment]
interesting

**Comment by fast4x** [comment]
#463 #267

**Comment by fast4x** [comment]
Implemented, added new provider lyrics LrcLib.net.
Available from version 0.6.28.1
