### ISSUE TITLE
[Feature]: Ad the shuffel icon

### ISSUE THREAD

**Issue by Lio-gif** [fast4x/RiMusic#718]
### Description

Ad the shuffel icon from vi music Interface to ri music interface

### Suggested Solution

Maybe Change IT to a Basic play icon

**Comment by ikanakova** [comment]
> Ad the shuffel icon from vi music Interface to ri music interface

The Shuffle icon in the RiMusic is. Don't yout have it disabled in Settings - Appearance - Player action bar - Show Shuffle button?

> Maybe Change IT to a Basic play icon

Changing the appearance of RiMusic to ViMusic is also done in the Appearance settings (the first choice).

**Comment by Lio-gif** [comment]
Yeah but i realy Like the ri music Player Interface but i Always used the shuffel Button to start playing my playlist

**Comment by ikanakova** [comment]
> Yeah but i realy Like the ri music Player Interface but i Always used the shuffel Button to start playing my playlist

There is always a Shuffle button <img src="https://raw.githubusercontent.com/fast4x/RiMusic/master/assets/ionicons/shuffle.svg" width="20"> in the top bar of the playlist, no matter if the look is RiMusic or ViMusic. But at least I can see it, both in the Library and Discovery playlists.

**Comment by fast4x** [comment]
Hi all, in fact the action bar has no effect in ViMusic mode, I do the fix

**Comment by fast4x** [comment]
Enable the action bar for ViMusic or just add the shuffle button

**Comment by fast4x** [comment]
I also enabled the action bar for ViMusic so the user can choose the buttons to add

**Comment by fast4x** [comment]
Available from version 0.6.22

**Comment by fast4x** [comment]
![Screenshot_20240215_121522](https://github.com/fast4x/RiMusic/assets/1484476/45b14bd4-a74e-4f6d-a30d-ffed700d1210)

**Comment by Vishcot** [comment]
@fast4x did you add this Go-to-top Button as well? if not, shall you please add this Go-to-top arrow button and i also like more of the minimised player next and pause only buttons and icons vimusic has, as you can see in screenshot below.

(Just one more thing..whether the upcoming changes will be according to me or not, 
you guys deserves a massive respect 🙏🏻 ! you've beaten professional players in terms of music streaming! Thank you so much for giving us this beautiful player! i am glad that you guys initiated this project! i always wanted this kind of player which has everything i ever wanted ) thankyou 🙏🏻❤️


[Screenshot_20240215-201725_1.png](https://github.com/fast4x/RiMusic/assets/136909951/9f603fc9-c22a-43f2-b77f-5eba55da6683)

**Comment by fast4x** [comment]
Done, available from version 0.6.22

**Comment by Vishcot** [comment]
> > @fast4x did you add this Go-to-top Button as well? if not, shall you please add this Go-to-top arrow button and i also like more of the minimised player seek bar ( not having dot at the end of it ) next and pause only buttons and icons vimusic has, as you can see in screenshot below.
> > 
> > (Just one more thing..whether the upcoming changes will be according to me or not, 
> > you guys deserves a massive respect 🙏🏻 ! you've beaten professional players in terms of music streaming! Thank you so much for giving us this beautiful player! i am glad that you guys initiated this project! i always wanted this kind of player which has everything i ever wanted ) thankyou 🙏🏻❤️
> > 
> > 
> > [Screenshot_20240215-201725_1.png](https://github.com/fast4x/RiMusic/assets/136909951/9f603fc9-c22a-43f2-b77f-5eba55da6683)
> > 
> > 
> 
> THX i think it all started with me being bored of ViMusic and giving A LOT of advice to make the player more modern and with a lot of feature but all the credit is going to @fast4x because making updates every month would drive me crazy 😀

whoever is anyhow connected to this project in its development! God bless you all guys ❤️ keep up the good work 🙏🏻🙏🏻

**Comment by fast4x** [comment]
Thank you very much, the credit goes to all users and all active collaborators. For me RiMusic is passion, but for its development I use [SCRUM](https://en.wikipedia.org/wiki/Scrum_(software_development)) as a working method, the same method I use at work.
