### ISSUE TITLE
[Feature]: Unifying the Add to playlist icon

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#719]
### Description

Somewhere there is a icon <img src="https://raw.githubusercontent.com/fast4x/RiMusic/master/assets/ionicons/add.svg" width="20"> icon and somewhere there is a icon <img src="https://github.com/fast4x/RiMusic/assets/38765251/f0440d0b-f897-4ce6-b591-c225863f4ad6" width="20">.

### Suggested Solution

I think there should be the same icon everywhere.

**Comment by fast4x** [comment]
Can you give me an example of where I can find the second one?

**Comment by ikanakova** [comment]
In the songs pop-up menu in albums, playlists,...
![unnamed](https://github.com/fast4x/RiMusic/assets/38765251/135e0915-ccf2-45d7-a6f3-f105cb69aaa7)

**Comment by fast4x** [comment]
Thank you

**Comment by fast4x** [comment]
I've changed icon + with this https://www.flaticon.com/free-icon/add-list_7794603?term=add+to+playlist&page=1&position=2&origin=search&related_id=7794603 relate to add in playlist or new playlist buttons

**Comment by ikanakova** [comment]
> I've changed icon + with this https://www.flaticon.com/free-icon/add-list_7794603?term=add+to+playlist&page=1&position=2&origin=search&related_id=7794603 relate to add in playlist or new playlist buttons

I'll make a similar one out of Ionicons.

**Comment by fast4x** [comment]
You are free to create the icons you like best.

**Comment by ikanakova** [comment]
Added icon. I edited the playlist icon in case it was needed here, but I think it could be removed since it's not even next to the albums:
![Screenshot_20240215_154904](https://github.com/fast4x/RiMusic/assets/38765251/eb8fdcf5-17a0-4a31-bbcf-98a0e8526bd7)

**Comment by fast4x** [comment]
Added, available from version 0.6.22
