### ISSUE TITLE
Next song name and buttons below are overlapping when the song name is big

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#72]
### Steps to reproduce the bug

click on the player then see below. sometimes its overlapping when the next song name is big

### Expected behavior

next song name and buttons below shouldn't overlap

### Actual behavior

next song name and buttons below are overlapping

### Screenshots/Screen recordings

![image](https://github.com/fast4x/RiMusic/assets/127825700/147d2d8b-04c0-46d4-b642-aea74340e819)

### RiMusic version

0.6.7

### Android version

android 11

**Comment by fast4x** [comment]
Fixed, available from version 0.6.8
