### ISSUE TITLE
Bad readability of notification area badge

### ISSUE THREAD

**Issue by Gaarco** [fast4x/RiMusic#720]
### Steps to reproduce the bug

Reproducible only with certain songs.

1. Search for "Over My Head" Robben Ford
2. Play the song
3. Open the notification area

### Expected behavior

The buttons should be clearly visible

### Actual behavior

The buttons are not clearly distinguishable from the cover

### Screenshots/Screen recordings

![rimusic](https://github.com/fast4x/RiMusic/assets/9869590/7bc72dd1-e81c-49d7-9989-da4602c5c71b)

### RiMusic version

0.6.21

### Android version

13

**Comment by OrangeZXZ** [comment]
> ### Steps to reproduce the bug
> 
> Reproducible only with certain songs.
> 
> 1. Search for "Over My Head" Robben Ford
> 2. Play the song
> 3. Open the notification area
> 
> ### Expected behavior
> 
> The buttons should be clearly visible
> 
> ### Actual behavior
> 
> The buttons are not clearly distinguishable from the cover
> 
> ### Screenshots/Screen recordings
> 
> ![rimusic](https://github.com/fast4x/RiMusic/assets/9869590/7bc72dd1-e81c-49d7-9989-da4602c5c71b)
> 
> 
> ### Logs
> 
> _No response_
> 
> ### RiMusic version
> 
> 0.6.21
> 
> ### Android version
> 
> 13
> 
> ### Additional information
> 
> _No response_

What brand of phone do you use?

**Comment by OrangeZXZ** [comment]
> ### Steps to reproduce the bug
> 
> Reproducible only with certain songs.

Other songs have colored text too?

**Comment by NEVARLeVrai** [comment]
> > ### Steps to reproduce the bug
> > 
> > Reproducible only with certain songs.
> > 
> > 1. Search for "Over My Head" Robben Ford
> > 2. Play the song
> > 3. Open the notification area
> > 
> > ### Expected behavior
> > 
> > The buttons should be clearly visible
> > 
> > ### Actual behavior
> > 
> > The buttons are not clearly distinguishable from the cover
> > 
> > ### Screenshots/Screen recordings
> > 
> > ![rimusic](https://github.com/fast4x/RiMusic/assets/9869590/7bc72dd1-e81c-49d7-9989-da4602c5c71b)
> > 
> > 
> > ### Logs
> > 
> > _No response_
> > 
> > ### RiMusic version
> > 
> > 0.6.21
> > 
> > ### Android version
> > 
> > 13
> > 
> > ### Additional information
> > 
> > _No response_
> 
> What brand of phone do you use?

It's a Xiaomi

**Comment by OrangeZXZ** [comment]
> It's a Xiaomi 

do you have colored text as well?

**Comment by NEVARLeVrai** [comment]
> > It's a Xiaomi 
> 
> do you have colored text as well?

No, it's probably a Redmi running Android 13 or 14 with MIUI 14 because the thing at the bottom left is too far down 
![Screenshot_2024-02-15-17-57-21-655-edit_com.sony.songpal.mdr.jpg](https://github.com/fast4x/RiMusic/assets/63956787/78406f20-6982-4330-96db-1a732da3b768)

**Comment by Gaarco** [comment]
Yes, all the songs have colored text and the color varies by song.
Brand is POCO with MIUI 14.

**Comment by NEVARLeVrai** [comment]
> Yes, all the songs have colored text and the color varies by song.
> Brand is POCO with MIUI 14.

Android version? I think it's a MIUI issues it will get patch with hyper os

**Comment by OrangeZXZ** [comment]
> > > It's a Xiaomi 
> > 
> > do you have colored text as well?
> 
> No, it's probably a Redmi running Android 13 or 14 with MIUI 14 because the thing at the bottom left is too far down 
> ![Screenshot_2024-02-15-17-57-21-655-edit_com.sony.songpal.mdr.jpg](https://github.com/fast4x/RiMusic/assets/63956787/78406f20-6982-4330-96db-1a732da3b768)
> 
> 

Maybe forcing white text on certains xiaomi devices is possible?

**Comment by NEVARLeVrai** [comment]
> > > > It's a Xiaomi 
> > > 
> > > do you have colored text as well?
> > 
> > No, it's probably a Redmi running Android 13 or 14 with MIUI 14 because the thing at the bottom left is too far down 
> > ![Screenshot_2024-02-15-17-57-21-655-edit_com.sony.songpal.mdr.jpg](https://github.com/fast4x/RiMusic/assets/63956787/78406f20-6982-4330-96db-1a732da3b768)
> > 
> > 
> 
> Maybe forcing white text on certains xiaomi devices is possible?

It's a MIUI problem in versions with Android above 12 it's caused by the system UI and miui bluetooth, it's patched on hyper os

**Comment by NEVARLeVrai** [comment]
On Spotify, Deezer, Amazon do you have the same issue if yes it's a MIUI issue

**Comment by OrangeZXZ** [comment]
> Yes, all the songs have colored text and the color varies by song.
> Brand is POCO with MIUI 14.

If fast4x cant patch this I think the only options would be to:
- wait for update
- ask xiaomi directly
- reset the phone (for the worst cases)

**Comment by NEVARLeVrai** [comment]
> > Yes, all the songs have colored text and the color varies by song.
> > Brand is POCO with MIUI 14.
> 
> If fast4x cant patch this I think the only options would be to:
> - wait for update
> - ask xiaomi directly
> - reset the phone (for the worst cases)

Make a feedback report about notification to Xiaomi yes

**Comment by NEVARLeVrai** [comment]
![Screenshot_2024-02-15-18-05-24-525_it.fast4x.rimusic.png](https://github.com/fast4x/RiMusic/assets/63956787/4197d4f3-90c3-443a-a0c0-103a62e66503)

Don't have this issue on my Xiaomi Mi 10T with A12 and MIU 14.0.4 MIXM also EOL, because on MIUI 14 with a13 they changed the notification style. Normally in hyper os it should be patched

**Comment by fast4x** [comment]
I tried and confirm that it is a bug on Xiaomi from MIUI 12 onwards

**Comment by Gaarco** [comment]
Yes I confirm, I received the update to HyperOS and I no longer have this problem.
Thanks, I'm closing
