### ISSUE TITLE
Download Button, confirm before download single

### ISSUE THREAD

**Issue by Indelibleimprint** [fast4x/RiMusic#723]
### Description

Download Button for individual songs is to easy to accidently push.

View Offline artists, Singles, Albums songs downloaded within artist page. If that makes sense. 

### Suggested Solution

Move the download button for the songs somewhere where it won't be accidently be pushed.

Make a prompt so that you can cancel if you accidently push the download song button while offline you have it for playlists and stuff but not for individual songs. ☺️

Make it so when you download albums they go to the artist page and you can view that artist offline and all of they're songs downloaded will be included.

**Comment by fast4x** [comment]
The goal of the single download is just to be able to quickly download the songs. Entering a confirmation means making the button useless.

**Comment by OrangeZXZ** [comment]
> The goal of the single download is just to be able to quickly download the songs. Entering a confirmation means making the button useless.

maybe an option to not download directly in the settings

**Comment by fast4x** [comment]
Yes it's an idea, implement it?

**Comment by OrangeZXZ** [comment]
> Yes it's an idea, implement it?

I dont install often the confirmation would be bether in my case

**Comment by fast4x** [comment]
Sure, by default it is disabled
