### ISSUE TITLE
Does not show new albums or songs from my bookmarked artists

### ISSUE THREAD

**Issue by GithubUser452** [fast4x/RiMusic#724]
### Steps to reproduce the bug

Make share "show new albums from your artists" is on then follow some artists and go to quick picks section.

### Expected behavior

Show new publications from my artists.

### Actual behavior

Does not show new publications from my artists.

### RiMusic version

0.6.21

### Android version

Android 11

**Comment by fast4x** [comment]
Hello, have you checked if among the news in Discovery your artist comes out?

**Comment by GithubUser452** [comment]
> Hello, have you checked if among the news in Discovery your artist comes out?

No, it doesn't show.
Shouldn't be separated ?

**Comment by GithubUser452** [comment]
> > Hello, have you checked if among the news in Discovery your artist comes out?
> 
>Hi
> No, it doesn't show.
> Shouldn't be separated ?

**Comment by fast4x** [comment]
News from your artista show only when Is available from Discovery...

**Comment by GithubUser452** [comment]
> News from your artists show only when Is available from Discovery...

Does it include Single song ? Or just it shows albums ?
Is there a separate tab from artists news who I have bookmarked, in Discovery ?

**Comment by fast4x** [comment]
No only albums even if they have one song.

**Comment by GithubUser452** [comment]
> No only albums even if they have one song.

Is it possible to implement Single songs news ?

**Comment by fast4x** [comment]
I can see if it’s possible, but I can’t assure you.

**Comment by GithubUser452** [comment]
> I can see if it’s possible, but I can’t assure you.

Can I open a Feature Request for that ?

**Comment by fast4x** [comment]
Yes, and close this. Thanks you
