### ISSUE TITLE
APP crashes in the statistics area

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#73]
### Steps to reproduce the bug

APP crashes in the statistics area

Watch the screen video

### Expected behavior

https://github.com/fast4x/RiMusic/assets/103368536/4b305f95-5c52-4bd5-8566-6d838cfe1a54

### Actual behavior

*

### RiMusic version

0.6.7

### Android version

Android 12

**Comment by siggi1984** [comment]
Oh, I forgot to mention that the error occurs in the statistics playlists area

**Comment by fast4x** [comment]
Checking the problem, thanks for the detail.

**Comment by fast4x** [comment]
can you send me youtube playlist id?

**Comment by siggi1984** [comment]
The error is not only with YouTube playlists the error is also with your own locally created playlists

**Comment by fast4x** [comment]
Uhm ok, i try to better understand the issue

**Comment by fast4x** [comment]
Crashes yet?

**Comment by siggi1984** [comment]
> Crashes yet?

Unfortunately, yes.

**Comment by fast4x** [comment]
Try this on version 0.6.11 please

**Comment by fast4x** [comment]
Please try with version 0.6.11
