### ISSUE TITLE
Singles News

### ISSUE THREAD

**Issue by GithubUser452** [fast4x/RiMusic#730]
### Description
#724 #20
Implementation of a separate tab to show new Singles (and albums together) from bookmarked artists

### Suggested Solution

Something like "What's new" on Spotify

**Comment by siggi1984** [comment]
Cool idea. Such a function would be really cool to keep up to date with new music.

**Comment by fast4x** [comment]
This is unnecessary

**Comment by GithubUser452** [comment]
> This is unnecessary

When you followed several artist, How can you follow their music updates?

**Comment by GithubUser452** [comment]
> Found it in home...

Unfortunately does not possible to find all there.
