### ISSUE TITLE
Offline tab of android auto not behaving like expected

### ISSUE THREAD

**Issue by btomaselli** [fast4x/RiMusic#731]
### Steps to reproduce the bug

Open rimusic on android auto
Go to offline tab
Downloaded music not showing up/available

### Expected behavior

All offline music, previously cached and manually downloaded, should be available at the offline tab of android auto

### Actual behavior

Very few music shows up, not reflecting what I've downloaded

### RiMusic version

0.6.21

### Android version

android 14

### Additional information

While using rimusic on Android auto,  I've realized that the offline tab wasn't behaving like expected. Only a few music were being listed and my  downloaded music wasn't available there

Further investigating, I think I understood what is happening. Being a fork of vimusic, the offline portion of that app was built by caching music that was played previously, and rimusic reflects that: some music that I listened ended up on the offline tab, but not all. But why?

I think because your enhancement of user download is cached on a separate folder, different from the player cache folder. When I play for the first time a downloaded song, the app reads it straight from the downloaded folder, not caching it on the player cache folder. That way downloaded music never shows on the offline tab of android auto, because the player never caches it to the player cache folder

I've tested that hypothesis by erasing one downloaded music that refused to show up on the offline tab, and playing it again straight from YouTube music to force cache it on the player cache. And bam, it showed up on the offline tab

So my recommendation is to rework the offline tab conditions, so it reads from both the player cache folder and user downloaded folder. That way it will show all offline music to the user

**Comment by fast4x** [comment]
Hello thank you for all the information and for the tests you did.

**Actually downloaded song isn't implemented on Android Auto, will be done... Some of the songs you listen to are cached by the player.**

**Comment by btomaselli** [comment]
Really? I thought it was implemented, since there is the download button at the far right of the AA player screen. But no hurry, I'll buffer everything on the player cache for the time being

Anyways, keep up the good work. Awesome app you made so far and your proactivity towards all feedback makes it even better every release

Thank you

**Comment by fast4x** [comment]
Thanks you!

**Comment by fast4x** [comment]
I've added downloaded songs in android auto, can you test it?

**Comment by btomaselli** [comment]
Is there any settings that I must change for it to show up? Nothing changed on the ui, still only favorites and offline in the Playlists tab

0.6.22 here

**Comment by fast4x** [comment]
You didn’t answer my question, I asked you if you want to test it, if so, you can download new version

**Comment by btomaselli** [comment]
Oh I thought you already released it lol

Of course, I can test it for you. Count me in!

Let me know which apk to download that have those AA improvements

**Comment by fast4x** [comment]
Lol, ok soon write here link

**Comment by fast4x** [comment]
Try this custom version, download from website
https://rimusic.xyz/download

**Comment by btomaselli** [comment]
didn't work

did a clean install, deleted previous version and didn't restored any data, just enabled AA in settings

on playlists tab it was listed the new "downloaded" category, but as soon as I click it returned the generic AA error "RiMusic seems to be not working at the moment", and the default back button on the upper left side of the screen

this take me back to the playlists tab, and all options work: from there I can listen to the favorites, offline and custom playlist without fault, except the new downloaded option

**Comment by fast4x** [comment]
Ok thanks for details, I'll investigate

**Comment by sayyid5416** [comment]
Wow, I just tested this, and it's broken for me too.

**Comment by btomaselli** [comment]
Tried that new release 0.6.23, and it also didn't work 

same error as before.

**Comment by fast4x** [comment]
Implemented downloaded songs in Android Auto, available from version 0.6.24

**Comment by fast4x** [comment]
yes
