### ISSUE TITLE
Setting to disable horizontal swipe does not work

### ISSUE THREAD

**Issue by kptmx** [fast4x/RiMusic#737]
### Steps to reproduce the bug

enable disabling horizontal swipe in settings

### Expected behavior

disable horizontal swipe

### Actual behavior

swipe still works

### RiMusic version

0.6.22

### Android version

Android 10

**Comment by fast4x** [comment]
I'll fix soon with custom version

**Comment by fast4x** [comment]
Fixed, available from version 0.6.23

**You can download custom version 0.6.22 from link with fixed issue,
https://rimusic.xyz/download**
