### ISSUE TITLE
Cannot open Indian YouTube curated playlist

### ISSUE THREAD

**Issue by Scripterr** [fast4x/RiMusic#739]
### Steps to reproduce the bug

1. Open app.
2. Go to any Indian YouTube music curated playlist. 
3. Open the playlist.

### Expected behavior

The playlist open and you can play any song.

### Actual behavior

The playlist don't open and loads infinitely.

### Screenshots/Screen recordings

![Screenshot_20240217_040412](https://github.com/fast4x/RiMusic/assets/42364681/b2d0031f-cf3a-45f6-9e66-56061b20662d)

### RiMusic version

0.6.22

### Android version

Android 14

**Comment by fast4x** [comment]
Hello, I checked and you are right, I check the problem.

**Comment by fast4x** [comment]
Partially fixed, now most load whitout problem
