### ISSUE TITLE
download speed for high quality music

### ISSUE THREAD

**Issue by megoo1997** [fast4x/RiMusic#740]
### Steps to reproduce the bug

when i try to download song with high quality , download speed decreases( just for long songs its 10 minutes and higher) .
medium and low quality working full without any pronlem

### Expected behavior

must use full download speed when download song in high quality like medium and low qality

### Actual behavior

download speed for high quality songs

### Screenshots/Screen recordings

![Screenshot_20240217_003100](https://github.com/fast4x/RiMusic/assets/159720948/204b24c7-db4f-472e-aeea-0dd397ae9405)
![Screenshot_20240217_004632](https://github.com/fast4x/RiMusic/assets/159720948/5119c617-e7ad-4ce1-a1fe-9730ddbf85ce)

### RiMusic version

0.6.22

### Android version

android 14

**Comment by fast4x** [comment]
Download Speed not seem to be related a RiMusic bug

**Comment by fast4x** [comment]
Add here link of song please

**Comment by megoo1997** [comment]
https://music.youtube.com/watch?v=Cj9uqsfY4y4

just bug for long song in high quality audio
