### ISSUE TITLE
Slow scrolling when browsing local playlists with more than 20 songs

### ISSUE THREAD

**Issue by Rikiub** [fast4x/RiMusic#742]
### Steps to reproduce the bug

1. Go to a local playlist with more of 20 added songs
2. Scroll and notice that it is laggy and slow.

### Expected behavior

Smooth scrolling in local playlists.

### Actual behavior

Slow/laggy scrolling in local playlists.

### RiMusic version

v0.6.22

### Android version

Android 13

### Additional information

I have searched for large playlists with more than 100 songs and the performance is good, is smooth. That only happens with local playlists.

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/e5f05fe3-0392-4134-a1f0-7c0ff7b3ddd2

Hello, I do not see the problem, explain better, thanks

**Comment by Rikiub** [comment]
I think it's because I have a low-end phone, but the problem only happens with local playlists, which seems weird to me.

I can't get smooth screen recordings with this phone, but I hope you notice the difference.

### Local

> Crunky scrolling.

https://github.com/fast4x/RiMusic/assets/114118274/b0f53220-74c0-48d0-9566-ec63d21c5551

### External

> Without screen recording is very smooth.

https://github.com/fast4x/RiMusic/assets/114118274/a9112e2a-71c6-4538-adba-6b5510eeaa26

**Comment by fast4x** [comment]
Thanks for details, I'll check it
