### ISSUE TITLE
Customizing Album Art Isn't Working as Intended

### ISSUE THREAD

**Issue by Davutha** [fast4x/RiMusic#743]
### Steps to reproduce the bug

Go to an album
Check the Customize Album option
Change the album art
Exit the app/go to the other versions section/play any track

### Expected behavior

The customized album art should stay there

### Actual behavior

The album art resets to the default one

### Screenshots/Screen recordings

![Screenshot_2024-02-11-01-08-14-981_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/68203036/13e54c91-6367-40b0-adde-cb0a3e86144d)
![Screenshot_2024-02-11-01-08-33-491_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/68203036/e7c232e0-9fdd-49b1-8154-34494e443112)
![Screenshot_2024-02-11-01-08-06-532_it fast4x rimusic-edit](https://github.com/fast4x/RiMusic/assets/68203036/f777678f-c90c-4419-a4de-ba92b7039b4f)

### RiMusic version

0.6.22

### Android version

Android 13 (MIUI 14)

### Additional information

I already posted this issue but with the track name issue (it was somehow fixed in this update for me)

**Comment by fast4x** [comment]
Ok, I'll check It soon

**Comment by Davutha** [comment]
is the problem fixed?

**Comment by fast4x** [comment]
Not yet

**Comment by Davutha** [comment]
ok

**Comment by Davutha** [comment]
the bug is still present in last update
