### ISSUE TITLE
[Feature]: Show name embedded on song except the name of the file

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#744]
### Description

Then name of the file may contain tags from the downloader and what not
So showing embedded name is much cleaner

### Suggested Solution

Showing the embedded name except the file name

**Comment by fast4x** [comment]
Where?

**Comment by VINULA2007** [comment]
On on-device songs

**Comment by fast4x** [comment]
Implemented, available from version 0.6.23 #795
