### ISSUE TITLE
sorting order not working in on-device songs list

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#745]
### Steps to reproduce the bug

1. Go to On-device songs
2. Change sorting order 

### Expected behavior

Should change the order of songs

### Actual behavior

Does nothing

### RiMusic version

0.6.22

### Android version

Android 14

**Comment by fast4x** [comment]
Fixed by #749, available from version 0.6.24

**Comment by VINULA2007** [comment]
Can I get the APK early ??

**Comment by fast4x** [comment]
If I can, I do a custom version in the evening or tomorrow

**Comment by fast4x** [comment]
APK ready you can download from website same version 0.6.22
https://rimusic.xyz/download
