### ISSUE TITLE
[Feature]: Add blacklist to On-device list

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#746]
### Description

App adds voice records from Whatsapp and other apps to the on device list

### Suggested Solution

Add blacklisting ability to on device list

**Comment by OrangeZXZ** [comment]
Maybe a whitelist will be better I think peoples that use local songs have the songs in one specific folder

**Comment by VINULA2007** [comment]
> Maybe a whitelist will be better I think peoples that use local songs have the songs in one specific folder

I'm a bit messy so I don't know

**Comment by fast4x** [comment]
Implemented, available from version 0.6.23
