### ISSUE TITLE
Some Finishings Here an there..for Clean Ui.

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#748]
### Description

All the features it must have, it already have..
all i am about to say, the sharp points here and there left..after last update like :

1. search text is moving out from the left, looks odd

![Screenshot_20240217-151502](https://github.com/fast4x/RiMusic/assets/136909951/a20cd34c-9ba9-489e-b5de-861fd8ff5908)

2. 3 dot menu is not aligned with the timeline seek bar.

![Screenshot_20240217-151229](https://github.com/fast4x/RiMusic/assets/136909951/bc633a0d-c800-4b3d-a347-8219f9573489)

3. Album square ( consists 4 album art together) is not aligned with the outer rectangular box. equal margin issue mainly.

![Screenshot_20240217-151048](https://github.com/fast4x/RiMusic/assets/136909951/1bff11dc-abdc-48d6-8887-0fe18d15c242)

4. these icons are not aligned horizontally.

![Screenshot_20240217-152345](https://github.com/fast4x/RiMusic/assets/136909951/f9ee23b5-e3c9-4678-8caf-515070a11f21)

5. how about instead of this icon adding this animation or similar.

![Screenshot_20240217-153718.png](https://github.com/fast4x/RiMusic/assets/136909951/a93356cc-c6bd-4ef6-bfc5-cceecc9e01a4)

like: https://icons8.com/icon/wgEWOAimcv4d/audio-wave

Rest is all set and lovely thanks for givings us .22 update. 🙏🏻

### Suggested Solution

mentioned above

**Comment by fast4x** [comment]
Nice, thanks.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.23

Point 2, is a 24 pixel icon and 3 dots are centered from border...
Point 5, i've changed musical notes with musicbars animated, same showed in queue...
