### ISSUE TITLE
Top app bar content and alignment

### ISSUE THREAD

**Issue by DanielSevillano** [fast4x/RiMusic#75]
### Steps to reproduce the bug

Open the app in Spanish.

### Expected behavior

The top app bar text should always show the search icon and the alignment should be revised.

### Actual behavior

* When the top app bar text is too long, it squishes or hides the search icon.
<img src="https://github.com/fast4x/RiMusic/assets/68847306/161ffcfb-8640-4aea-ae73-4d295db945c6" width="200px"/>
<img src="https://github.com/fast4x/RiMusic/assets/68847306/1d556add-5845-48dc-9085-45e34d7e4014" width="200px"/>

* When the app is in landscape mode, the text isn't centered and the search icon isn't at the end.
<img src="https://github.com/fast4x/RiMusic/assets/68847306/9ba4b88a-61d3-4672-a007-5fdf65ebe3df" height="200px"/>

### RiMusic version

0.6.7

### Android version

Android 13

### Additional information

Additionally, the vertical alignment of the top app bar itself seems off to me. I think that it looks better when it's vertically aligned with the settings icon, as in ViMusic.

<img src="https://github.com/fast4x/RiMusic/assets/68847306/73d7388a-4a8c-4d18-8bd7-b10f2205f30a" width="200px"/>

**Comment by fast4x** [comment]
The text and icon in app bar are centered relative to the vertical scrolling space.

I recommend reducing the length of the translated text where possibile.

I will fix lenght text and alignment of the settings icon to the text.

**Comment by fast4x** [comment]
I try to align text and icon on the right side

**Comment by fast4x** [comment]
Fixed, available from version 0.6.8
