### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by lima2303** [fast4x/RiMusic#755]
### Description

Excuse me, could you please make this swipe to show more options in the songs on the playlist optional? It usually gets in the way of scrolling. Thanks for reading (sorry for the bad english).
![Screenshot_20240217_192902](https://github.com/fast4x/RiMusic/assets/156343914/84939079-3d0c-483a-92b6-f0b81125addf)
![Screenshot_20240217_193140](https://github.com/fast4x/RiMusic/assets/156343914/e356d2ce-650b-450d-a450-d4e3b312dbe5)

### Suggested Solution

.

**Comment by fast4x** [comment]
Hi, yes it's Just implemented and available from version 0.6.23

**Comment by lima2303** [comment]
> Hi, yes it's Just implemented and available from version 0.6.23

thank you so much! :))
