### ISSUE TITLE
Roll-back favorite blank button

### ISSUE THREAD

**Issue by Corotyest** [fast4x/RiMusic#756]
### Description

Hello, good afternoon.
I loving the way RiMusic is taking, a lot of updates since the release and I am of the first ones to try it, well job.
Excuse me, but I had to say it. Okey then, I prefer the other favorite button, it gave more feedback to know if the song is or not favorited, I tend to confuse since the change, because i don't really know if I already favorited that song.
Thanks beforehand...

Best regards,
Corotyest.

### Suggested Solution

Roll-back the favorite button OR implement an option to change it.

**Comment by fast4x** [comment]
Hello, are you talking about the color of the button that does not make you understand if the song is preferred or not?

**Comment by Corotyest** [comment]
YES. That's it!

**Comment by faustaahmad** [comment]
I dont mind if the colour being monochromatic, since it suit the theme better
Say the dynamic colour became blue, it would feel wierd if there's red ❤️

**Comment by Corotyest** [comment]
> Yup...i think also the /favorite/like button should be Red

Red? No, I mean blank, the inside of it then when it is liked red or white, any color.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.23
