### ISSUE TITLE
French language translation missing ?

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#76]
### Steps to reproduce the bug

In settings, in cache tab

### Expected behavior

A translation are there but couldn't find in the XML file

### Actual behavior

Can't find "Moutilisé" ? In the file and the translation means nothing, I couldn't  understand it

### Screenshots/Screen recordings

![Screenshot_2023-11-04-01-47-34-143-edit_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/5eae1afa-be0f-41e6-9fd0-4d0e483673c1)

### RiMusic version

0.6.7

### Android version

A12

**Comment by NEVARLeVrai** [comment]
![Screenshot_2023-11-04-01-56-08-112_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/63956787/d63ad3a0-b95b-48ba-b53c-48545a8f27e9)

Also why translation don't apply there ?

**Comment by fast4x** [comment]
Heavy etc.. will be available soon.

**Comment by fast4x** [comment]
M..outilisé it's a bug, fix It.

Thanks

**Comment by NEVARLeVrai** [comment]
> M..outilisé it's a bug, fix It.
> 
> Thanks

I need to do something? Translate it?

**Comment by fast4x** [comment]
No, I don't think

**Comment by fast4x** [comment]
No, I don't think

**Comment by fast4x** [comment]
Fixed Mo... available from version 0.6.8
