### ISSUE TITLE
Can't load Featured playlists 

### ISSUE THREAD

**Issue by rupeshsaha** [fast4x/RiMusic#760]
### Steps to reproduce the bug

1.Open app
2.Go to Discovery
3.Choose indie india or other frommood and genres.
4.Try to open any playlist from the "featured playlist "section 
5.Most of them doesn't load

### Expected behavior

Featured playlist should load

### Actual behavior

Most of the featured playlist doesn't load

### Screenshots/Screen recordings

![Screenshot_20240218-193349](https://github.com/fast4x/RiMusic/assets/155124334/7187fab7-430b-40bf-a7f9-580a873fd163)
![Screenshot_20240218-193353](https://github.com/fast4x/RiMusic/assets/155124334/a41e35b0-8c01-4d1e-aab5-f2143e727077)

### RiMusic version

0.6.22

### Android version

Android 13

**Comment by fast4x** [comment]
Depend by geographic area and YouTube music api results.
