### ISSUE TITLE
Better shuffle 

### ISSUE THREAD

**Issue by Sobbi50** [fast4x/RiMusic#764]
### Steps to reproduce the bug

Go in a playlist and try it

### Expected behavior

Shuffle always gives you the same songs, improve this please 

### Actual behavior

It gives same song

### RiMusic version

0.6.22

### Android version

13

**Comment by fast4x** [comment]
Hi, version 0.1.5 not exists

**Comment by Sobbi50** [comment]
> Hi, version 0.1.5 not exists

Just fixed

**Comment by fast4x** [comment]
Ah ok
