### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by wunder20v** [fast4x/RiMusic#765]
### Description

Add charts

### Suggested Solution

Can you please add charts like youtube music.

**Comment by fast4x** [comment]
Chart for show what?

**Comment by dAtA-TRoN** [comment]
> Chart for show what?

I believe he's referring to song charts, which are playlists featuring currently trending music.

**Comment by fast4x** [comment]
So charts as statistics? It would take an example of what you mean because statistics already have this kind of information.

**Comment by dAtA-TRoN** [comment]
He probably means a standard playlist featuring the currently most popular songs played on the radio of the selected country (via the language settings in the options). This likely requires tapping into the YouTube Music API to retrieve the current mainstream hits. Clear now? It's simply about providing a list of the current top hits, probably under the "discover" tab, as a fixed, non-manually editable playlist.

**Comment by fast4x** [comment]
User have added request and he's gone

**Comment by fast4x** [comment]
Implemented, available from version 0.6.41
