### ISSUE TITLE
[Feature]: Option to keep the floating search button on place.

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#766]
### Description

The floating search bar at the bottom right in vi music style disappears when swiping up.

### Suggested Solution

I personally like to always keep the search button there so that's my request.

**Comment by Nikks84** [comment]
Yes, 
We can be easy and convenient to use to find songs or disable an optional enable in settings.

**Comment by fast4x** [comment]
Implemented search tab, available from version 0.6.23

**Comment by NikunjKhangwal** [comment]
Thanks a lot dev. Also why don't you add donation/sponsor links in app? People can support you for your amazing work.

**Comment by fast4x** [comment]
Thank you, the idea is interesting but I don’t do it for money, I do it for passion.

**Comment by NikunjKhangwal** [comment]
I see, i appreciate your passion. Keep up the good work. 👏🏼
