### ISSUE TITLE
Place the online search button below "discovery"

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#770]
### Description

If that's done then we won't have to scroll back up always.

### Suggested Solution

I meant here: 

![Screenshot_20240219-113737](https://github.com/fast4x/RiMusic/assets/85461823/68272fe5-70aa-42cf-8a62-1fcc70c19175)

Also if possible show the online search button on playlists as well. Probably here…
![Screenshot_20240219-114649.jpg](https://github.com/fast4x/RiMusic/assets/85461823/62532c34-7555-4867-a2e9-8177352d4481)

**Comment by NikunjKhangwal** [comment]
You could use the ViMusic interface btw

**Comment by fast4x** [comment]
back button Will be present always.. like in playlist...

**Comment by fast4x** [comment]
Implemented search tab, available from version 0.6.23

**Comment by fast4x** [comment]
But i think, Is good idea to enable/disable search tab by settings?

**Comment by fast4x** [comment]
Ok I'll add in settings

**Comment by fast4x** [comment]
Added i ui settings
