### ISSUE TITLE
playlist collapsing

### ISSUE THREAD

**Issue by SivAs1234** [fast4x/RiMusic#773]
### Steps to reproduce the bug

App can't resume play back after closed app. Have to  start from first song of the playlist.

### Expected behavior

Expected to start the song where I left

### Actual behavior

Starting from first song of playlist

### RiMusic version

0.6.21

### Android version

Android 14

**Comment by fast4x** [comment]
Enable in settings persistent queue and resume playback

**Comment by fast4x** [comment]
Any other details?

**Comment by SivAs1234** [comment]
For example, in Spotify if I close app with a song paused. Even after a day that song will remain from the same spot I paused and the playlist too. In RI music it's gone and I have to open playlist and start from first

**Comment by fast4x** [comment]
In this version i've fixed a bug in persistent queue. If enable it, you have solved, next time open RiMusic, start from last position.
