### ISSUE TITLE
Some long songs can't be downloaded

### ISSUE THREAD

**Issue by abdiel-rg** [fast4x/RiMusic#775]
### Steps to reproduce the bug

1. Look up a long song like "Rhapsody in Blue" by George Gershwin.
2. Press the download button.
3. Play the song while offline

### Expected behavior

The song, no matter how long it is, should be downloaded on its entirety and the icon should update to the correct (white) one.

### Actual behavior

It plays part of the song but gets cuts about halfway. It keeps that part downloaded regardless of the amount of times the download button has been pressed. It also shows a gray download icon in the song list as if the song isn't downloaded completely.

### Screenshots/Screen recordings

![Screenshot_20240219_085549](https://github.com/fast4x/RiMusic/assets/54369065/24f60210-50c2-4cda-9f79-991029ac7c67)

![Screenshot_20240219_085618](https://github.com/fast4x/RiMusic/assets/54369065/796cc77d-adad-4a6c-aff4-8ba7c795d6b1)

### RiMusic version

0.6.22

### Android version

Android 14

### Additional information

_Would like this issue to be deleted or my name removed just for privacy reasons, if it isn't too much to ask._

**Comment by Nebula-Mechanica** [comment]
I confirm this problem, it's especially important when trying to download mixes. Cached mixes work fine
