### ISSUE TITLE
can't sort playlist by date added

### ISSUE THREAD

**Issue by u-daygupta** [fast4x/RiMusic#777]
### Steps to reproduce the bug

1. open a playlist
2. check sorting options

### Expected behavior

An option to sort playlist by date added (not position, which im confused as to it's meaning)

### Actual behavior

No such option

### Screenshots/Screen recordings

![Screenshot_20240219-215034](https://github.com/fast4x/RiMusic/assets/121250333/18fa6117-2e23-4c15-b334-0072f8431e9b)

### RiMusic version

0.6.22

### Android version

Android 13

**Comment by faustaahmad** [comment]
@DeadSecTr recently implemented, so expect some bugs
Not everyone has time to test for bug, that's why this repo always open to any issue
The author of this repo seems to prioritize _new_ feature first despite its barely functional than make existing stable, but it'll get fixed sooner or later anyway...

**Comment by fast4x** [comment]
> Can confirm that too.
> 
> Playlist sort is broken...(newest update also) 
> 
> Song being randomly sorted after "Sort" click
> 
> Donno why...another apps like innertune can this without problem,i mean thats a simple function of a Music Player/Stream app...

Can you test and report the bug if you want, you are free.

**Comment by fast4x** [comment]
I don’t see any bugs in the sorting of the songs. If the sorting by location doesn’t work, you have to renumber the songs... renumber menu...

Playlist sorting by date added not exists, if you want open or change this ticket in feature.

Thanks
