### ISSUE TITLE
[Feature] : player improvement

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#78]
### Description

An improvement of the player 

### Suggested Solution

It would be nice if the player didn't move regardless of the size of the album cover.

**Comment by NEVARLeVrai** [comment]
![IMG_20231104_174111](https://github.com/fast4x/RiMusic/assets/63956787/0c3d6502-cf3e-4cc0-b4a6-a840c2431bd7)
![Screenshot_2023-11-04-17-37-46-505_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/307880ff-2925-4962-a51c-fa03ff966994)
![Screenshot_2023-11-04-17-40-03-532_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/64446a9f-9a8e-4ff6-8a16-aeb6657f13a1)
![Screenshot_2023-11-04-17-37-35-718_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/0fc0e92e-1926-4f50-87ab-e3f3041daa6e)

**Comment by NEVARLeVrai** [comment]
also add like button on miniplayer 
![image](https://github.com/fast4x/RiMusic/assets/63956787/ca0b5dec-75c7-4eca-9909-8de65d29884c)

**Comment by NEVARLeVrai** [comment]
also u can remove entrain de lire... its usless

**Comment by fast4x** [comment]
You mean when skip between songs?

**Comment by NEVARLeVrai** [comment]
> You mean when skip between songs?

when u change album size text move and we have so much space between its look ugly

**Comment by fast4x** [comment]
Ok, same size...

**Comment by NEVARLeVrai** [comment]
> Ok, same size...

But did u Understand what I'm saying like not that I mean text follow album size and move and make so much space between what I want that album size change but text still centered but don't really move ?, and for mini player add like button also

**Comment by NEVARLeVrai** [comment]
Or that the album remains centered in the middle if you see what I mean I don't really know how to explain

**Comment by NEVARLeVrai** [comment]
Or that the album remains centered in the middle if you see what I mean I don't really know how to explain

**Comment by NEVARLeVrai** [comment]
![IMG_20231104_202325.jpg](https://github.com/fast4x/RiMusic/assets/63956787/15e3d46a-3b08-4a6a-9cc2-7f8da021c30b)

Like this

**Comment by NEVARLeVrai** [comment]
For mini player ![IMG_20231104_202755.jpg](https://github.com/fast4x/RiMusic/assets/63956787/3d9b38f3-28ef-43d0-8662-6d66d7d874ae)

**Comment by NEVARLeVrai** [comment]
U understand what I mean ?

**Comment by fast4x** [comment]
Yes, it's available from version 0.6.8
