### ISSUE TITLE
Inconsistend options in the burger menu

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#781]
### Description

I think that some options shouldn't be pop-ups and the arangement is not perfect

### Suggested Solution

Add an arrow to "Play With" and the "Timer" also make rhem oppen like the "Add to playlist"

![Screenshot_20240220_064036](https://github.com/fast4x/RiMusic/assets/104271365/204f2d06-6a8c-40f8-a9a1-db460b94dd5c)

Try arranging them in this order:
- Listen with
- Add to playlist
- Radio
- Change name
- Sleep timer
- Equalisator

**Comment by fast4x** [comment]
I keep the current order, add the sub menu on Listen.

**Comment by Logan7899** [comment]
@fast4x Instead you acn add download option burger menu
