### ISSUE TITLE
[Feature]: Option to floating start radio button bottom right side.(keep position)

### ISSUE THREAD

**Issue by Nikks84** [fast4x/RiMusic#782]
### Description

Floating start radio button bottom right side. On artist page Like vi music disappeared when scrolling up.

### Suggested Solution

It's can be convenient the button keep there.
So that's my request.

Thanx for your dedication for this project welldone 👍🏻

**Comment by fast4x** [comment]
Fixed, available from version 0.6.23
No option in settings.

**Comment by Nikks84** [comment]
Ok thanks.. 😊
