### ISSUE TITLE
Send likes/downloads as playlist

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#784]
### Description

My friend wanted me to send him my Playlist but my playlist is actualy my likes. The problem is i can't send that

### Suggested Solution

Add a way to convert likes/downloaded into a playlist
or
Add a way to send likes/downloaded as a playlist link
or maybe
Make a selection menu to select anything and then you can export in a new playlist

**Comment by fast4x** [comment]
@OrangeZXZ @ikanakova You are strong! 😉

**Comment by Lolozweipunktnull** [comment]
Maybe an easier option to develop is to write a text file with the video IDs like ViMusic almost implemented: https://github.com/vfsfitvnm/ViMusic/issues/523

I think it would be enough for most people, even if it is not elegant.

**Comment by fast4x** [comment]
I would be develop better

**Comment by fast4x** [comment]
Implemented share RiMusic playlist via export/import file from RiMusic

**Comment by fast4x** [comment]
Other export/import playlist under development

**Comment by fast4x** [comment]
Implemented selectable export in playlist, cached, downloaded and preferites.
Available from version 0.6.24
