### ISSUE TITLE
Move finder button

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#785]
### Description

I find the actual placement not logical

### Suggested Solution

Move it next to the search button

![Screenshot_20240220_100916](https://github.com/fast4x/RiMusic/assets/104271365/b2500901-9266-4bae-9e33-a9f558510c87)

**Comment by fast4x** [comment]
First idea is much simple.

**Comment by OrangeZXZ** [comment]
> First idea is much simple.

Could you also change the song icon like in the queue maybe always show the animated icon en if you dont press the finder (that way the finder just moves to the song) Also make other songs text less white to really show the song that is playing

**Comment by fast4x** [comment]
Implemented, available from version 0.6.23
No style changed for songs list
