### ISSUE TITLE
shortcut to favorites directly from HomeScreen ?

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#787]
### Description

![Screenshot_20240220-175135](https://github.com/fast4x/RiMusic/assets/136909951/38bcc890-fadc-4f22-be44-d21c1d0ac830)

### Suggested Solution

adding a quick shortcut to directly to favorite songs..

**Comment by Warden20** [comment]
The idea would be a shortcut for the home screen that automatically plays favorite songs. 
I like this idea
