### ISSUE TITLE
How About Favorites like this ? 

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#788]
### Description

Only consider favorites (downloads are already well in there place!)
refer this:

![Screenshot_20240220-175402](https://github.com/fast4x/RiMusic/assets/136909951/5bbe50a0-484f-478d-ab12-057d1c8dba4e)

### Suggested Solution

isn't this will make easy to us to fav or unfav?

**Comment by fast4x** [comment]
Hi, next version have like/unlike with empty/not empty icon Heart

**Comment by OrangeZXZ** [comment]
> Explain better, please, what you mean.

I think he wants an hearth like the fast download icon

I think it would be nice but as an option that replace download maybe because there would be too many icons

**Comment by OrangeZXZ** [comment]
> and how about adding this kind of toggle for downloading songs in lists at once and for all songs ? will make it more simple and well explanatory.
> 
> ![Screenshot_20240220-234851](https://github.com/fast4x/RiMusic/assets/136909951/6bcbf554-eecf-49df-bdf7-334d4d404a4e)
> 

he can do a toggle icon but i think there is an reason for not having it right now maybe data usage or accidental use but it can have an warning pop-up in my opinion

**Comment by OrangeZXZ** [comment]
> he can do a toggle icon but i think there is an reason for not having it right now maybe data usage or accidental use but it can have an warning pop-up in my opinion

Oh yeah i know why "if you have some song downloaded but everyone the buton should be on or off?" i think it should be on and remove all instaled if we press but then if you want to reinstall everything then you need to uncheck and check it redownload songs and use data

**Comment by OrangeZXZ** [comment]
> > he can do a toggle icon but i think there is an reason for not having it right now maybe data usage or accidental use but it can have an warning pop-up in my opinion
> 
> Oh yeah i know why "if you have some song downloaded but everyone the buton should be on or off?" i think it should be on and remove all instaled if we press but then if you want to reinstall everything then you need to uncheck and check it redownload songs and use data

I think when pressing the button you should have an pop-up with options:
- Download all
- Delete all
- Inverse Downloaded/Undownloaded

**Comment by fast4x** [comment]
> > > he can do a toggle icon but i think there is an reason for not having it right now maybe data usage or accidental use but it can have an warning pop-up in my opinion
> > 
> > Oh yeah i know why "if you have some song downloaded but everyone the buton should be on or off?" i think it should be on and remove all instaled if we press but then if you want to reinstall everything then you need to uncheck and check it redownload songs and use data
> 
> I think when pressing the button you should have an pop-up with options:
> - Download all
> - Delete all
> - Inverse Downloaded/Undownloaded

Nice idea

**Comment by OrangeZXZ** [comment]
> > > Explain better, please, what you mean.
> > 
> > hi, first of all thanks for considering, 
> > download icon in Rimusic is at good place no need to change.
> > as per the screenshot you can see above,
> > i was thinking that it would be so convenient if we place   filled/ empty heart after every song in list so that we can easily remove or add songs to favorites, also where we search songs for quick adding. see this below :
> > 
> > ![Screenshot_20240220-234223](https://github.com/fast4x/RiMusic/assets/136909951/e4023d88-68e9-4f8c-bf07-1e616fc43bb0)
> > 
> 
> Aaaahhhhhhh ookkk now i've understand, nice idea, I'll check space of item...

try adding download next to it because it will feel off

**Comment by Vishcot** [comment]
so many comments! sorry didn't be able to join, was out of station just came back! yeah! i was saying that by adding fav icons after song title will give us ease of access to favorite a song or remove it from library @fast4x and @OrangeZXZ i feel download button is at the right position in my opinion, why aligning it next to  favourites icon?

**Comment by Vishcot** [comment]
![Screenshot_20240224-200559.png](https://github.com/fast4x/RiMusic/assets/136909951/f6b5cb78-2a04-4baa-b03b-8318c71fc44c)

what does this do? Is it related to this trail?

**Comment by fast4x** [comment]
Is horizontal swipe in playlist... If enabled, you can swipe to reveal action...

**Comment by OrangeZXZ** [comment]
> Is horizontal swipe in playlist... If enabled, you can swipe to reveal action...![Screenshot_2024-02-24-15-42-20-566_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/13fb72ac-663c-49b4-96a6-33ddb1239e9d)
> 
> 

could you also add it for favorites downloaded and more?

**Comment by Vishcot** [comment]
> Is horizontal swipe in playlist... If enabled, you can swipe to reveal action...![Screenshot_2024-02-24-15-42-20-566_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/13fb72ac-663c-49b4-96a6-33ddb1239e9d)
> 
> 

we really need this feature in favorites and downloads as well! really important! 🙏🏻🙏🏻

**Comment by fast4x** [comment]
Implemented menu to action in all playlists, available from version 0.6.24
