### ISSUE TITLE
Create smart playlists

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#79]
### Description

Creating smart playlists, i.e. you create a playlist with certain prerequisites and when listening to music, the songs are automatically added to the playlist when the prerequisites are met.

It's a bit difficult to explain, but I saw it on an offline player and thought it was a really cool feature.

If you like the idea you could have a look at it.

### Suggested Solution

https://github.com/moritz-weber/mucke

**Comment by fast4x** [comment]
Interesting

**Comment by siggi1984** [comment]
I have just discovered a fork of ViMusic that has already added a similar function. Maybe it will help you. 

https://github.com/25huizengek1/ViMusic/releases/tag/v0.5.5

![Screenshot_20231112-003627_1](https://github.com/fast4x/RiMusic/assets/103368536/32e79f9c-cb8b-43d3-b49d-fbdc520018cc)

But I would extend it to top 50 or even 100.

**Comment by OrangeZXZ** [comment]
> I have just discovered a fork of ViMusic that has already added a similar function. Maybe it will help you.
> 
> https://github.com/25huizengek1/ViMusic/releases/tag/v0.5.5
> 
> ![Screenshot_20231112-003627_1](https://private-user-images.githubusercontent.com/103368536/282270328-32e79f9c-cb8b-43d3-b49d-fbdc520018cc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTM4MzIsIm5iZiI6MTcxMDE1MzUzMiwicGF0aCI6Ii8xMDMzNjg1MzYvMjgyMjcwMzI4LTMyZTc5ZjljLWNiOGItNDNkMy1iNDlkLWZiZGM1MjAwMThjYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxMDM4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWFmYTgzZTRjYmIwNDJmOTE4MjlmMzI1OGQ0NTczOTIzY2U5NjAyM2EwZDQzNzc3ZTkzZTMyNGI1MWEwNTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.leFaK4AOkGHobUbMJawLEc2Sk7ZOdLA7v-9Hqz9lwgs)
> 
> In the settings there is even the option to extend the "My Top" as required.
> 
> I personally think this function is great.

@fast4x since now we have the my top 10 or more this is already done but im not sure

Maybe not if you want to add an playlist option like (add every liked music that has this artist in it or more)
