### ISSUE TITLE
Animation/warning while swipe removing song from queue

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#790]
### Description

This swipe to remove song from queue it's really…what do I call it…
Actually nvm I forgot the suitable word for it. Anyway, what I mean is because of this feature I end up removing song without even realizing. Sometimes when I'm trying to reorder queue I end up removing song because of this. Sometimes while casually scrolling.

### Suggested Solution

Either show animation of swiping. So that I can stop swiping if I accidentally started to. Or keep a warning for it. Though the former idea seems better imo.

### Alternatives

Or maybe just (if possible) lower the sensitivity of swipe in this case?

**Comment by fast4x** [comment]
On queue Will be available swipe to action like actual in Playlist.

**Comment by fast4x** [comment]
Yes

**Comment by fast4x** [comment]
Implemented swipe to action in queued songs
Available from version 0.6.24

**Comment by jmgarvey** [comment]
Is it possible when "Swipe to action" is turned off in the menu to revert to the previous behavior.

**Comment by fast4x** [comment]
Previous with only swipe gesture?

**Comment by jmgarvey** [comment]
Current behavior for swipe with "swipe to action" brings up the menu to (possibly) remove the song from queue. If you turn off "swipe to action", currently a swipe does nothing. I think it would be nice to remove the song from the queue instead.

**Comment by fast4x** [comment]
ok

**Comment by fast4x** [comment]
You are right, but some person would prefer to delete with swipe gesture, it's can enabled/disabled by settings.

**Comment by jmgarvey** [comment]
Doesn't locking the playlist accomplish all of those things? If it's locked I don't want to swipe to remove. If it's unlocked and "swipe to action" is off I would like to swipe to remove.

**Comment by fast4x** [comment]
It's a good idea

**Comment by fast4x** [comment]
Implemented delete song from queue with horizontal swipe if queue not locked and swipe to action disabled.
Available from version 0.6.26
