### ISSUE TITLE
[Feature]: Split versions/Login support 

### ISSUE THREAD

**Issue by Aspect250** [fast4x/RiMusic#791]
### Description

As mentioned by many many people before me
#315 #344 #355 #640 #690 #761 
We want to be able to login and use services like importing from other services, syncing playlists although implementing those features requires the use of trackers as you all have said 
>Implementing Google or YouTube login would require a Google tracker for authentication, which would invade the privacy of all users. Additionally, the app wouldn't met requirements to be published in F-Droid.

And that's a a totally valid reason to deny the implementation of it and respect your decision  but hear me out. 

### Suggested Solution

Innertune had different versions one was foss and another with proprietary libraries [Here](https://github.com/z-huang/InnerTune/wiki/App-Versions) what I am kinda proposing is that you can have split versions one that fully foss like what you have right now and one with trackers and such implemented for use of features like login support. This should satisfy the privacy crowd (with the foss version) and the people who want features such as login support for syncing playlists (with yt with a non foss? version) without deny one for the other.

### Additional Context

I have thought about it and my main worry is It may complicate the development of RiMusic you would be maintaining two versions of the app and although not completely different still different versions and given that this is essentially a hobby project for you and isn't your livelihood or something I don't want to put any presume on you that may affect your work here.

To be clear I'm not a developer and just because it worked for innertune doesnt mean it can work for RiMusic as well.

Even if this is rejected still love the app and hope to see it continue developing through into the future.

**Comment by fast4x** [comment]
Thanks you, making multiple versions of RiMusic takes a very long time and I don’t have that time. I’m sorry, I have to tell you, it’s not possible at least for now.

**Comment by ikanakova** [comment]
I think this should be mainly an app for those who don't want to share everything about themselves with Google (because those who don't mind can use the official Youtube Music...) And the way to solve the sharing of playlists in that case is to import/export a list of url addresses see feature request #784 or using Piped etc. see feature request #278

**Comment by Aspect250** [comment]
@fast4x As I suspected, I don't wanna make this app to be a chore for you to develop, and that's a completely fair response.

**Comment by Aspect250** [comment]
@ikanakova 
>I think this should be mainly an app for those who don't want to share everything about themselves with Google (because those who don't mind can use the official Youtube Music...) 

I agree, but as I said, there have been many people who want to see some kind of integration with Google, and it can be extremely useful for crossplatform/device play to have a sync feature. And to those who don't mind, they can use the official YTM app. I disagree YTM is a closed sourced app, and even with Revanced/ Extended to mod it, its usability is limited for many users and that's why many users look for alternatives like RiMusic with good features.

> And the way to solve the sharing of playlists in that case is to import/export a list of url addresses see feature request #784 or using Piped etc. see feature request #278

Having a piped would be good, although given that the vast majority of my playlists on YTM are all private, it would be a huge hassle to unprivate them to move into the app.


@fast4x have you considered doing a small side app that's independent of rimusic that we could import and export aka sync with the Google.

A very simple app where all we do is log in to sync our playlists via database backup/import

Something like [this](https://github.com/RLAlpha49/Anilist-Manga-Updater) python script but it can go both ways
