### ISSUE TITLE
Toolbar updates

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#793]
### Description

Some changes to toolbar

### Suggested Solution

Before;
![Screenshot_20240220_225418](https://github.com/fast4x/RiMusic/assets/120176369/84639d70-5556-48cc-b988-6e2e81a774ef)

After;
![Polish_20240220_224537530](https://github.com/fast4x/RiMusic/assets/120176369/8bab10a5-c8df-4f3b-a141-195b1cac785a)

![Polish_20240220_224247049](https://github.com/fast4x/RiMusic/assets/120176369/57cf48ed-54c7-4b14-af27-311cd16523a4)

### Additional Context

I hope you find this helpful

**Comment by Logan7899** [comment]
@fast4x make toolbar little bit smaller and make them corresponding to dark toolbar

**Comment by fast4x** [comment]
Dark when dark theme Is selected

**Comment by Logan7899** [comment]
> Dark when dark theme Is selected

I mean queue

**Comment by fast4x** [comment]
Colors from player and queue are Just inverted... Is a feature...

**Comment by Logan7899** [comment]
> Colors from player and queue are Just inverted... Is a feature...

You didn't understood. I do not mean color i mean only toolbar in queue and now playing screen

**Comment by fast4x** [comment]
It depend by theme... You probably use default or dynamic

**Comment by Logan7899** [comment]
> It depend by theme... You probably use default or dynamic

Brother i meant by icons on toolbar not theme. Icons are going to edge of the screen

**Comment by Logan7899** [comment]
> > It depend by theme... You probably use default or dynamic
> 
> Brother i meant by icons on toolbar not theme. Icons are going to edge of the screen

There i have given solution

**Comment by fast4x** [comment]
Slightly increased the distance of the icons from the edges.

Available from version 0.6.23
