### ISSUE TITLE
"My Top x"-Playlist

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#796]
### Description

The "My Top x" playlist is an automatic playlist that is created based on listening behavior, similar to the already integrated statistics, only that a playlist is automatically created from it (the number of songs can be freely selected in the settings). I saw this on a ViMusic fork and think it's really cool.

Maybe you can have a look at it.

https://github.com/25huizengek1/ViMusic

![Screenshot_20240220-204141](https://github.com/fast4x/RiMusic/assets/103368536/21cf2086-bf9d-428e-88e0-18b3bdc4c6d8)
![Screenshot_20240220-204132](https://github.com/fast4x/RiMusic/assets/103368536/635006e3-98bb-40cf-945c-f0b04be3fa66)

### Suggested Solution

*

**Comment by fast4x** [comment]
Implemented, available from version 0.6.24

**Comment by siggi1984** [comment]
> Implemented, available from version 0.6.24

Thank you

**Comment by fast4x** [comment]
You are welcome

**Comment by siggi1984** [comment]
Many thanks for the implementation, unfortunately the function didn't quite turn out as I thought. I thought it would be like

https://github.com/25huizengek1/ViTune

Maybe you just have a look at it. Maybe you will get the function just like that.
