### ISSUE TITLE
Adding minimal-bold player while driving

### ISSUE THREAD

**Issue by abdulkarimx1** [fast4x/RiMusic#800]
### Description

Some people don't have Android auto supported car / screen which makes the default player very hard to navigate while driving.

### Suggested Solution

Adding minimal-bold player with big buttons to enable easier navigations between songs ( if possible ) 
![adm-controls](https://github.com/fast4x/RiMusic/assets/105733146/2f5a7b89-319b-4b89-a8c0-528a5deefa29)

**Comment by fast4x** [comment]
Can swipe Song

**Comment by OrangeZXZ** [comment]
> Can:
> - swiping left/right change song
> - swiping up open queue
> - swiping down minimize player or close queue

maybe it is possible if you add custom play buton sizes. I would also love a big play buton but just for feel and look

**Comment by fast4x** [comment]
BIG mean to create trooble when use in device with low display resolution
