### ISSUE TITLE
[BUG] Swipe to change song still works even when it is disabled in settings

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#802]
How to reproduce:
1. Go to settings --> Appearance
2. Enable 'disable horizontal swipe'
3. Play song and swipe horizontally
4. Song changes anyway

It even happens upon restarting the app

**Comment by privacyfreak84** [comment]
The song only changes when I swipe on the album art. Still, I don't think that's supposed to happen if the option is disabled

**Comment by fast4x** [comment]
Just fixed and available from new version 0.6.23

**Comment by fast4x** [comment]
Yes, similar and it's Just fixed in new version 0.6.23

**Comment by privacyfreak84** [comment]
Thanks!
