### ISSUE TITLE
[BUG] App crashes going to another app, then coming back and playing a song

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#803]
Well, its a little more complicated than that.
What actually happens is:
1. I play a song OR I simply have the app open
2. I go to another app
3. I come back to RiMusic
4. If I had a song playing, then the player disappears. If I didn't have a song playing, the screen remains unchanged
5. I click to play on another song
6. App crashes

In relation to point number 4: If I had a song playing, then the player disappears, but it can be brought back by clicking the back button on the android navigation menu. BUT even when I bring the player back and try to play another song, the app still crashes

Note- Every time I tried to play another song, I did so by selecting a song from the 'Tips' section of the 'Quick Picks' tab

**Comment by OrangeZXZ** [comment]
I wanted to report random app crashes but i didn't knew the reason

**Comment by fast4x** [comment]
Enable invincible service and optimize battery permission in settings

**Comment by fast4x** [comment]
> I also wanted to report random app crashes but i didn't knew the reason

Invincible service

**Comment by OrangeZXZ** [comment]
> Enable invincible service and optimize battery permission in settings

I did that and noticed that it still crash and not save the last queue i had sometimes

**Comment by fast4x** [comment]
So it crashes when it tries to save the queue...

**Comment by privacyfreak84** [comment]
> Enable invincible service and optimize battery permission in settings

Both invincible service and disable battery optimization for RiMusic are enabled. The issue still occurs

**Comment by fast4x** [comment]
What's your device and android version?

**Comment by privacyfreak84** [comment]
Samsung galaxy a30s, android 11. I have followed all the instructions for android 11 on dontkillmyapp

**Comment by NikunjKhangwal** [comment]
You can share the crash log so maybe dev get more relevant information and find the problem

**Comment by privacyfreak84** [comment]
Here are the logs:

FATAL EXCEPTION: DefaultDispatcher-worker-11
Process: it.fast4x.rimusic, PID: 16559
java.lang.IllegalStateException
	at v8.i1.W(SourceFile:1)
	at u3.y.l(SourceFile:1)
	at t8.z.u(SourceFile:30)
	at t8.z.g(SourceFile:13)
	at ma.r.n(SourceFile:157)
	at ma.d1.a(SourceFile:177)
	at ma.c1.u(SourceFile:1)
	at t9.a.k(SourceFile:1)
	at ja.j0.run(SourceFile:1)
	at l.j.run(SourceFile:14)
	at pa.i.run(SourceFile:1)
	at pa.a.run(SourceFile:92)
	Suppressed: oa.h: [v1{Cancelling}@bbe9976, Dispatchers.IO]


And 



FATAL EXCEPTION: main
Process: it.fast4x.rimusic, PID: 18235
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{733ada8 u0 it.fast4x.rimusic/it.vfsfitvnm.vimusic.service.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2269)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by fast4x** [comment]
I think is just fixed in next version.

**Comment by privacyfreak84** [comment]
Thanks!

**Comment by privacyfreak84** [comment]
Thanks. Works fine now!

**Comment by fast4x** [comment]
You are welcome 🤗
