### ISSUE TITLE
Persistent Queue does not rememeber enqueued songs after app restart

### ISSUE THREAD

**Issue by dollarSignUsername** [fast4x/RiMusic#805]
### Steps to reproduce the bug

1. open app, go to library --> favorites --> shuffle
2. all items enqueue correctly and start playing first song
3. go to device homescreen - music continues playing in the background
4. swipe up from the task manager and swipe (close) Ri Music app away - music stops playing
5. open Ri Music again - app does not remember what was enqueued & playing before close

### Expected behavior

5. open Ri Music again - app brings back queue of songs as it was before closing at teh bottom of the screen and current song is ready to unpause & resume playing

### Actual behavior

5. open Ri Music again - app does not remember what was enqueued & playing before close

### RiMusic version

0.6.22

### Android version

Android 14

### Additional information

There's a setting for persistent queue which seems to be ignored - this is reproducible with it both on and off. I also granted app permission to notification just in case, but it did not fix it. There is also a setting to close background player, which if turned off does remember the queue, but only if the music keeps playing. If song is paused and then app closed, it forgets the queue.
Compared to spotify which upon app restart has the last playing song at the bottom ready to unpause.

Other than this small issue I absolutely love the app :)

**Comment by fast4x** [comment]
Fixed, available from version 0.6.23

**Comment by fast4x** [comment]
Fixed, available from version 0.6.24
