### ISSUE TITLE
App crashing while scrolling through quick picks

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#81]
### Steps to reproduce the bug

scroll quick picks

### Expected behavior

should not crash app

### Actual behavior

app is crashing 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/127825700/c3724ca3-b872-4f12-8d6b-1c9d31480bd4

### RiMusic version

0.6.7

### Android version

android 11

**Comment by fast4x** [comment]
it always happens?

**Comment by dainvincible1** [comment]
> it always happens?

no, not always.

**Comment by fast4x** [comment]
Ok, thanks i will check it

**Comment by dainvincible1** [comment]
> Ok, thanks i will check it

thanks

**Comment by fast4x** [comment]
Crashes yet?

**Comment by dainvincible1** [comment]
> Crashes yet?

no, i dont see any crashes yet. i think its fixed

**Comment by fast4x** [comment]
Perfect!
