### ISSUE TITLE
Sort by option 

### ISSUE THREAD

**Issue by Knsravan** [fast4x/RiMusic#810]
### Description

Create a option to sort downloaded songs asper latest download or date of the song downloaded 

### Suggested Solution

Create a sort by option to easily access songs but not only by alphabetic order also as per date of the song downloaded and by asending as well as desecding

**Comment by OrangeZXZ** [comment]
I think we could also show the songs not downloaded at the bottom in alfabetic order

**Comment by fast4x** [comment]
This part I can manage later because cached and downloaded will be unified
