### ISSUE TITLE
Share/Open with fullscreen behavior

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#814]
### Steps to reproduce the bug

Anything that can trigger share popup/window (Share song link, Open with or Listen in, Search lyrics, etc...)

### Expected behavior

UI doesnt change height (not fullscreen)
Try open youtube and share, UI wont change to fullscreen even when statusbar gone

### Actual behavior

UI change to fullscreen

### Screenshots/Screen recordings

![](https://github.com/fast4x/RiMusic/assets/45221211/cfce8807-0363-4885-ab67-aac79df1fbf1)

### RiMusic version

0.6.22

### Android version

Android 11

### Additional information

One UI

**Comment by OrangeZXZ** [comment]
> UI change to fullscreen

Can you explain better "UI Fullscreen"

You are talking about the app or the sare samsung UI?

**Comment by OrangeZXZ** [comment]
> You are talking about the app or the sare samsung UI?

Also there is a screenshot of android 14 with one ui 6.0

If the problem is on my screenshot too can you pls tell me?

![Screenshot_20240224_100246_IntentResolver.jpg](https://github.com/fast4x/RiMusic/assets/104271365/38a8fb70-3f0d-4b29-8556-1dbe338c8d1c)

**Comment by faustaahmad** [comment]
Yours doesnt have statusbar present, should be
Like when pressing share or "open with" buttom, screen go fullscreen & UI got updated

It's not a problem, just wierd responsive UI behaviour

**Comment by fast4x** [comment]
But screen not go in full screen after share something...

**Comment by fast4x** [comment]
I'm sorry but i don't understand

**Comment by faustaahmad** [comment]
**Focus on statusbar**
<table>
<tr>
<th><image src="https://github.com/fast4x/RiMusic/assets/45221211/d3e098ff-25a3-4b29-ad36-abed31376a7f">Normal height + statusbar</image></th>
<th><image src="https://github.com/fast4x/RiMusic/assets/45221211/debd46b8-677f-4c24-b6b0-7c8476fba031">Capped height at fullscreen</image></th>
</tr>
</table>

The height always got updated, unlike most of apps that I used (only statusbar hidden, no change in UI height)
