### ISSUE TITLE
Make topmost button in playlist actually useful

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#815]
### Steps to reproduce the bug

Song > Play/Click > Drag up for playlist
Then try to drag down with that button to <s>close the playlist</s> open the statusbar

### Expected behavior

Close the playlist even when scrolling far down

### Actual behavior

Blocked by statusbar, so it get pulled down instead 

### Screenshots/Screen recordings

![](https://github.com/fast4x/RiMusic/assets/45221211/5261ce34-32a1-49b4-ae7b-982f6ba9ffd3)

### RiMusic version

0.6.22

### Android version

Android 11

### Additional information

Perhaps make it invisible when dragged up
OR limit playlist height under statusbar
OR just remove that cosmetic, if they arent doing much

**Comment by fast4x** [comment]
It's a pure cosmetic...

**Comment by OrangeZXZ** [comment]
Thank you for asking it i think that the queue should only open to the bottom of the status bar

Also the line is cosmetic to show that it is an drag menu YT Apps use those visuals
