### ISSUE TITLE
Player stopped for unknown reason 

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#817]
### Steps to reproduce the bug

Don't really know. My only guess is problem with internet connection. I can't really guess anything else. 

### Expected behavior

Keep playing song smoothly.

### Actual behavior

Suddenly stopped with "An unknown playback error has occurred" dialogue in the thumbnail.

### Screenshots/Screen recordings

![Screenshot_20240223-214632](https://github.com/fast4x/RiMusic/assets/85461823/f31cfdc9-3456-4dda-ac40-9999f2837896)

### RiMusic version

0.6.22

### Android version

Android 11

**Comment by fast4x** [comment]
Would be recover by click again on play/pause
