### ISSUE TITLE
Please Add A search button on the lower right hand side for easy access.

### ISSUE THREAD

**Issue by Genuineuserhubro** [fast4x/RiMusic#818]
### Description

Just like vimusic, please give a search button(magnifying glass button) for easy search access. 
You guys made a suupppeerrr good app keep it moving ... Thank you people 🙂

### Suggested Solution

By adding a search button on the lower right hand side of the app on every page (homescreen and everywhere)

**Comment by Nikks84** [comment]
See this #766

**Comment by Genuineuserhubro** [comment]
Oh thanks 😊
You guys are doing a great job , I know you have already heard that but ... I can't stop myself from saying it 🙂🤝

**Comment by fast4x** [comment]
Thaaaanksssss a lot
