### ISSUE TITLE
Bottom nav

### ISSUE THREAD

**Issue by owencz1998** [fast4x/RiMusic#82]
### Description

Please Add a option for a bottom navigation bar as the side one has always sucked in my opinion:)

### Suggested Solution

..

### Alternatives

..

### Additional Context

..

**Comment by fast4x** [comment]
I respect that, but I don’t agree that it sucks.

**Comment by NEVARLeVrai** [comment]
> I respect that, but I don’t agree that it sucks.

I'm not much of a fan either when it's on side, I preferred it up or down.Or you can put an option to be able to choose

**Comment by fast4x** [comment]
Si potrebbe essere una soluzione futura

**Comment by sayyid5416** [comment]
It's related to #852

**Comment by sayyid5416** [comment]
> > It's related to #852
> 
> Well really #852 is related to this one as I published this 4 months ago and yours 11 days lol

If `a` is related to `b`, then `b` is also related to `a`. So what's your point 🤷

**Comment by owencz1998** [comment]
I was messing around, but hey, I guess we all have bad days. 🤦‍♂️

**Comment by lovelilke** [comment]
什么时候能改成底部导航栏啊 这样侧面导航栏用着不喜欢

**Comment by fast4x** [comment]
目前还不可能

**Comment by sayyid5416** [comment]
> Implemented top bar navigation, available from version 0.6.29

Wow thanks

**Comment by fast4x** [comment]
Also implemented bottom bar, available from version 0.6.29
