### ISSUE TITLE
Icons in lirics mode

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#821]
### Description

I think the show full screen lirics button is hiding errors and it is weird placed

But I've got a solution!
![SmartSelect_20240223_210906](https://github.com/fast4x/RiMusic/assets/104271365/d15c41f6-1190-48c8-bb74-70559b7e5256)

### Suggested Solution

Move the full lirics at the bottom left and the translate next to the burger menu button

**Comment by fast4x** [comment]
Nice

**Comment by fast4x** [comment]
Implemented, available from version 0.6.23
