### ISSUE TITLE
Reverse Confirm and Cancel

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#823]
### Description

I often Cancel instead of Confirming because the buttons are switched and all other aps is the opposite

![SmartSelect_20240224_001918](https://github.com/fast4x/RiMusic/assets/104271365/dd4383a5-49e7-4f5a-9811-3de52fca1e1e)

### Suggested Solution

Pls reverse Confirm and Cancel positions

**Comment by fast4x** [comment]
Done, available from version 0.6.24
