### ISSUE TITLE
Checklist style pop-up for Player action bar Settings

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#824]
### Description

I think Player action bar Settings should be unified in one button that shows an checklist style pop-up (or maybe still using the on of switches) like the languages pop-up to prevent taking unnecessary space like in this picture

![SmartSelect_20240224_001734](https://github.com/fast4x/RiMusic/assets/104271365/8cd556bd-4020-46a1-ac65-6d1006f6e95c)

### Suggested Solution

Unify Player action Bar settings into one button with a pop-up

You can maybe unify other similar things like quick picks settings
![SmartSelect_20240224_002817](https://github.com/fast4x/RiMusic/assets/104271365/8a9575fd-a707-42a6-957a-043192b6f442)

### Additional Context

Also an option to let the user chose what Playlist to show or not example:

- Show Likes
- Show Downloaded
- Show Cached
- Show In Device
- Show Created Playlist

Because i dont use the In Device Playlist, Also il hide Created Playlist because I don't have any

!!! If you add this feature it is useles to remove them otomaticaly (example: Cached Playlist) !!!

**Comment by fast4x** [comment]
Improved space between settings and added show/hide playlists type buttons in appearance settings.
Available from version 0.6.25
