### ISSUE TITLE
Tiny changes for the Playlist buttons

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#825]
### Description

I have some tiny things that bother me about the icons in the playlists:
- The finder should be switched with the search to feel more natural (my opinion)
- The icons on top of that should end at the same spot as the ones below

![SmartSelect_20240224_003510](https://github.com/fast4x/RiMusic/assets/104271365/00d0d610-44a1-46e6-b566-3b3d5904087f)

### Suggested Solution

- Swi5ch the place of the finder button to be at the left of search
- Make the icons at the top of search end at the same point as the icons below

### Additional Context

The tiny search bar got upgraded I think and it is perfect like this:
![SmartSelect_20240224_004358](https://github.com/fast4x/RiMusic/assets/104271365/b53ea7ba-146a-4873-b959-a71132eca77e)

Could you use the same for other search bars? Since it works so well it could be better that the line in the normal search

**Comment by OrangeZXZ** [comment]
> What about this?
> I'd personally like those buttons placed like this:
> ![1708753740849.jpg](https://github.com/fast4x/RiMusic/assets/85461823/5b9723a1-9f4c-45cb-b1a0-4a88913f05e9)
> 
> Also about search feature I think it should show as pop-up and close after the search is done. Or tapped somewhere else than the search box.
> 
> I'd like to know if my idea is good enough.

The placement is weird but the pop-up and the search closing is a very good idea!

**Comment by OrangeZXZ** [comment]
> > The placement is weird but the pop-up and the search closing is a very good idea!
> 
> I guess yeah…different opinions…but I don't like the current placement as well.
> 
> And yeah search feature being the way I suggested would be really great I think.

we could swap the arrangement ant the search icons?

**Comment by OrangeZXZ** [comment]
> > we could swap the arrangement ant the search icons?
> 
> I'm not sure if I understood your question. 
> 
> Do you mean the "sorting feature" by "the arrangement"?
> I mean this: ![Screenshot_20240224-195533.jpg](https://github.com/fast4x/RiMusic/assets/85461823/94c147c2-c98f-487b-9fda-6a3cb3c96827)
> 
> If so then yeah. Swapping places of "search icon" and "sorting feature" seems good enough to me. 
> 
> 
> 
> 
> 
> Or are you only asking what should be done with search icon?
> Meaning this: ![Screenshot_20240224-194920.jpg](https://github.com/fast4x/RiMusic/assets/85461823/5a7a66db-ec5a-48a5-8487-a42d85930df2)
> 
> If that's the question then I think it should be a little more towards the sorting feature.
> 
> Like probably in one of these spots: ![Screenshot_20240224-195216.jpg](https://github.com/fast4x/RiMusic/assets/85461823/297fcee9-f121-4cdc-bd7e-21ba3cc9ccce)
> 
> Or in the leftmost part of playlists.
> 
> 
> 
> Sorry if I got the question wrong in both of my guesses!!!
> 
> 
> Btw in short imo the search icon should be somewhere in the leftmost side (because then it'd be accessible most of the time) or just somewhere that we can get access to it anytime.
> 
> Like in the left or a floating button like "back to top" button. 
> I feel like I'm making things difficult. But the only thing I want about the search feature is it being easily accessible.
> 
> (Sorry, a little outta topic. But is it just me or does everyone prioritize the search feature a lot? Even though I don't really use it much this feature is actually really helpful.)

i mean like this i dont mind if it gets changed like this + the search button would be at the same side as the normal search

![Screenshot_20240224_151704.jpg](https://github.com/fast4x/RiMusic/assets/104271365/208745a6-c647-4501-a1df-a279f0ed94b8)

**Comment by fast4x** [comment]
Improved, without last suggested swap... :) available from version 0.6.24

**Comment by fast4x** [comment]
![Screenshot_20240310_202133](https://github.com/fast4x/RiMusic/assets/1484476/e582cd9f-8884-44c2-bb02-f281b300ac5e)

Now

**Comment by OrangeZXZ** [comment]
> ![Screenshot_20240310_202133](https://github.com/fast4x/RiMusic/assets/1484476/e582cd9f-8884-44c2-bb02-f281b300ac5e)
> 
> Now

maybe swith the search and the find button

**Comment by fast4x** [comment]
ok

**Comment by fast4x** [comment]
Done
![Screenshot_20240310_202723](https://github.com/fast4x/RiMusic/assets/1484476/95bbed09-8b8a-4d03-921c-802e48e09db1)

**Comment by OrangeZXZ** [comment]
> Done
> ![Screenshot_20240310_202723](https://github.com/fast4x/RiMusic/assets/1484476/95bbed09-8b8a-4d03-921c-802e48e09db1)
> 

what is the star and the lock?

**Comment by fast4x** [comment]
In user playlist classic lock for reorder, and star is new pinned playlist released in 0.6.25

**Comment by fast4x** [comment]
Done 
![Screenshot_20240310_203348](https://github.com/fast4x/RiMusic/assets/1484476/83e6b1b8-c468-44dc-8b07-66b773dd3fe1)

**Comment by OrangeZXZ** [comment]
> Done 
> ![Screenshot_20240310_203348](https://github.com/fast4x/RiMusic/assets/1484476/83e6b1b8-c468-44dc-8b07-66b773dd3fe1)
> 

I wonder if the order of the icons could flip when you change the bar position (left right) to be similar for left hand users

**Comment by fast4x** [comment]
It is appropriate to make a specific ticket because it requires a lot of precision work

**Comment by OrangeZXZ** [comment]
> It is appropriate to make a specific ticket because it requires a lot of precision work

Il make one then

**Comment by OrangeZXZ** [comment]
> > I wonder if the order of the icons could flip when you change the bar position (left right) to be similar for left hand users
> 
> I was talking about that as well. Won't it be better if most useful buttons were placed on the side in a row.

I think it is fine like that but there are too mutch buttons maybe it would be necessary to unify/move some

**Comment by OrangeZXZ** [comment]
> Yeah like when download/delete download can be unified. "Shuffle" and "Suggested songs" can be unified as well I think. 

Yes you can unify Download by making a pop-up and you could do the same for the smart recommandation & Shuffle

**Comment by OrangeZXZ** [comment]
> Yes you can unify Download by making a pop-up and you could do the same for the smart recommandation & Shuffle

im going to make a new issue for that

**Comment by fast4x** [comment]
> > Yes you can unify Download by making a pop-up and you could do the same for the smart recommandation & Shuffle
> 
> im going to make a new issue for that

It is not yet the time to unify downloads.

**Comment by fast4x** [comment]
Unifying the two icons implies rewriting a delicate and substantial part of the code.  I am working on the code with as much priority as possible so as not to create bugs. Probably the best choice will be to add a single icon in the menu with unified logic.

**Comment by OrangeZXZ** [comment]
> It is not yet the time to unify downloads.

I had an idea:

No songs downloaded : Unfilled icon (off) also asks if the user wants to download all the songs
Some songs are downloaded : Filed version of the icon (on) when pressed it asks if the user wants to download the rest of songs or if he wants to delete the downloaded songs
All the songs are downloaded : Filled version of the icon (on) when pressed it asks if the user wants to delete all the downloaded songs

for the "Some songs are downloaded" we could also create a new icon 1/2 filled/unfilled
![image](https://github.com/fast4x/RiMusic/assets/104271365/3217d9e5-26bb-4f31-a7d9-2a1fa06dead2)

Im gonna make a new issue for that

**Comment by fast4x** [comment]
@ikanakova

**Comment by ikanakova** [comment]
> > It is not yet the time to unify downloads.
> 
> I had an idea:
> 
> No songs downloaded : Unfilled icon (off) also asks if the user wants to download all the songs Some songs are downloaded : Filed version of the icon (on) when pressed it asks if the user wants to download the rest of songs or if he wants to delete the downloaded songs All the songs are downloaded : Filled version of the icon (on) when pressed it asks if the user wants to delete all the downloaded songs
> 
> for the "Some songs are downloaded" we could also create a new icon 1/2 filled/unfilled ![image](https://private-user-images.githubusercontent.com/104271365/311543740-3217d9e5-26bb-4f31-a7d9-2a1fa06dead2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTQxNzQsIm5iZiI6MTcxMTAxMzg3NCwicGF0aCI6Ii8xMDQyNzEzNjUvMzExNTQzNzQwLTMyMTdkOWU1LTI2YmItNGYzMS1hN2Q5LTJhMWZhMDZkZWFkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQwOTM3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWNjNjAzZjM0Zjk5ODRjNzQzYjE0OGFhNmFjNzAzOTE2MjhhZmFmMWMxMDE2ZThhMjAwNDc1M2E4ZGZhMDczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Eg2uzabCCKxfLAFCHlpC8VyArDsgRLsA_5IwEFMYsLg)
> 
> Im gonna make a new issue for that

My suggestion in a https://github.com/fast4x/RiMusic/issues/953#issuecomment-2011752015
