### ISSUE TITLE
New Playlist button in Libraries

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#826]
### Description

I think that the new playlist button could be upgraded and I find it verry ugly when it is single in a corner (plus could be hard to tell)

Instead there is a quick concept the button is similar to the Like, Download, ... playlists:
![SmartSelect_20240224_004630](https://github.com/fast4x/RiMusic/assets/104271365/b62830e3-848d-432e-b897-eaf738e13b84)

### Suggested Solution

Replace the borring new playlist button with a big button that resembles a playlist and stays on the top right of user created playlists

**Comment by OrangeZXZ** [comment]
![SmartSelect_20240224_005825.jpg](https://github.com/fast4x/RiMusic/assets/104271365/81030800-1cba-41f9-86c1-e75f13ee7256)

There is also this search icon that could be pressed better in the Songs section

**Comment by fast4x** [comment]
Implemented, avalable from version 0.6.24
