### ISSUE TITLE
Tiny space that could be used

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#827]
### Description

There is a tiny gap between text and the hearth that could be used to show more text (maybe just not make it too close to the heart)

![SmartSelect_20240224_010118](https://github.com/fast4x/RiMusic/assets/104271365/2dabcb6e-e6a1-4446-a2e3-ce8506d1a7c1)

### Suggested Solution

Make text a bit longer while using that tiny gap

**Comment by fast4x** [comment]
Improved, available from version 0.6.24
