### ISSUE TITLE
Crashes on On-device songs 

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#828]
### Steps to reproduce the bug

Go-to one device through library and swipe around to see if the music comes back

### Expected behavior

Should show songs in the device

### Actual behavior

Crashes the app without showing any sings of it recognizing any song on my device 

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/89296867/b35d464c-7bac-47bd-b8bb-caac2dc9a239

### Logs

![Uploading Screenshot_2024-02-24-08-38-33-704_com.miui.bugreport.jpg…]()

### RiMusic version

0.6.23

### Android version

Android 14

**Comment by VINULA2007** [comment]
![Screenshot_2024-02-24-08-44-44-417_com miui home](https://github.com/fast4x/RiMusic/assets/89296867/89236631-b893-4c7f-aba3-79bdc4372265)

**Comment by fast4x** [comment]
Try to remove permission folders and add again.

**Comment by VINULA2007** [comment]
![Screenshot_2024-02-24-13-06-06-198_com miui bugreport](https://github.com/fast4x/RiMusic/assets/89296867/49415423-80b2-4444-ba7f-d1b9adb1d6db)
Doesn't Work

> Try to remove permission folders and add again.

It doesn't work

**Comment by fast4x** [comment]
Thanks for details, I'll send you a custom version to try

**Comment by fast4x** [comment]
Did the previous version work?

**Comment by VINULA2007** [comment]
> Did the previous version work?

It worked without a hitch

**Comment by fast4x** [comment]
Hi, can you try this custom version please?
https://rimusic.xyz/download

**Comment by VINULA2007** [comment]
> Hi, can you try this custom version please? https://rimusic.xyz/download

It still crashes

https://github.com/fast4x/RiMusic/assets/89296867/4f07b0b4-6887-49c9-b8f8-377805383b84

Now it doesn't even go to the on-device page

![Screenshot_2024-02-25-07-38-16-089_com miui bugreport](https://github.com/fast4x/RiMusic/assets/89296867/37844c0a-1a06-4ace-87d1-759c123d8e8c)
And it still gives the same error

**Comment by VINULA2007** [comment]
> Hi, can you try this custom version please? https://rimusic.xyz/download

It still crashes

https://github.com/fast4x/RiMusic/assets/89296867/4f07b0b4-6887-49c9-b8f8-377805383b84

Now it doesn't even go to the on-device page

![Screenshot_2024-02-25-07-38-16-089_com miui bugreport](https://github.com/fast4x/RiMusic/assets/89296867/37844c0a-1a06-4ace-87d1-759c123d8e8c)
And it still gives the same error

**Comment by fast4x** [comment]
Ok maybe i understand where is the error, but strange much strange.

**Comment by fast4x** [comment]
Try again this new custom version, please
https://rimusic.xyz/download

**Comment by JZITNIK-github** [comment]
@fast4x I've been able to reproduce this. When you create an empty file (0 bytes) ending with .mp3 and then open the on device it will crash. It's because the file is corrupted (empty). Sorry, I didn't think about this problem when I created my PR. I'm not able to fix this till Friday but I'm thinking of just putting a try catch in the code to prevent crashing.

**Comment by VINULA2007** [comment]
> Try again this new custom version, please https://rimusic.xyz/download

Page kinda refuses to load

![Screenshot_2024-02-25-21-33-32-205_org mozilla firefox](https://github.com/fast4x/RiMusic/assets/89296867/cdb821ad-706a-4111-b22b-27399f5e745d)

**Comment by JZITNIK-github** [comment]
The website is working for me.

**Comment by fast4x** [comment]
> @fast4x I've been able to reproduce this. When you create an empty file (0 bytes) ending with .mp3 and then open the on device it will crash. It's because the file is corrupted (empty). Sorry, I didn't think about this problem when I created my PR. I'm not able to fix this till Monday but I'm thinking of just putting a try catch in the code to prevent crashing.

hi, I've just added try catch in custom version

**Comment by fast4x** [comment]
> > Try again this new custom version, please https://rimusic.xyz/download
> 
> Page kinda refuses to load
> 
> ![Screenshot_2024-02-25-21-33-32-205_org mozilla firefox](https://github.com/fast4x/RiMusic/assets/89296867/cdb821ad-706a-4111-b22b-27399f5e745d)
> 

have you tryed again?

**Comment by VINULA2007** [comment]
> > > Try again this new custom version, please https://rimusic.xyz/download
> > 
> > 
> > Page kinda refuses to load
> > ![Screenshot_2024-02-25-21-33-32-205_org mozilla firefox](https://private-user-images.githubusercontent.com/89296867/307604853-cdb821ad-706a-4111-b22b-27399f5e745d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDUyNzEsIm5iZiI6MTcwODk0NDk3MSwicGF0aCI6Ii84OTI5Njg2Ny8zMDc2MDQ4NTMtY2RiODIxYWQtNzA2YS00MTExLWIyMmItMjczOTlmNWU3NDVkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDEwNTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OGRiNTk5MjEyNDg3ODkzNDg4MzkzNThlNjk2ZDBhZTFiODcxYzU2ZmZiNGJlYTJiNjg3NGJkYmRkNGRhZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4rn0mP4iS0y4CJePADvS1cJEzAOB-HDzzJMNcNYo7So)
> 
> have you tryed again?

Yeah, I've tried and it works but takes a while to load

**Comment by JZITNIK-github** [comment]
> > > > Try again this new custom version, please https://rimusic.xyz/download
> > > 
> > > 
> > > Page kinda refuses to load
> > > ![Screenshot_2024-02-25-21-33-32-205_org mozilla firefox](https://private-user-images.githubusercontent.com/89296867/307604853-cdb821ad-706a-4111-b22b-27399f5e745d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDUyNzEsIm5iZiI6MTcwODk0NDk3MSwicGF0aCI6Ii84OTI5Njg2Ny8zMDc2MDQ4NTMtY2RiODIxYWQtNzA2YS00MTExLWIyMmItMjczOTlmNWU3NDVkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDEwNTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OGRiNTk5MjEyNDg3ODkzNDg4MzkzNThlNjk2ZDBhZTFiODcxYzU2ZmZiNGJlYTJiNjg3NGJkYmRkNGRhZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4rn0mP4iS0y4CJePADvS1cJEzAOB-HDzzJMNcNYo7So)
> > 
> > have you tryed again?
> 
> Yeah, I've tried and it works but takes a while to load

How many songs do you have?

**Comment by VINULA2007** [comment]
176

> > > > > Try again this new custom version, please https://rimusic.xyz/download
> > > > 
> > > > 
> > > > Page kinda refuses to load
> > > > ![Screenshot_2024-02-25-21-33-32-205_org mozilla firefox](https://private-user-images.githubusercontent.com/89296867/307604853-cdb821ad-706a-4111-b22b-27399f5e745d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDUyNzEsIm5iZiI6MTcwODk0NDk3MSwicGF0aCI6Ii84OTI5Njg2Ny8zMDc2MDQ4NTMtY2RiODIxYWQtNzA2YS00MTExLWIyMmItMjczOTlmNWU3NDVkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDEwNTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OGRiNTk5MjEyNDg3ODkzNDg4MzkzNThlNjk2ZDBhZTFiODcxYzU2ZmZiNGJlYTJiNjg3NGJkYmRkNGRhZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4rn0mP4iS0y4CJePADvS1cJEzAOB-HDzzJMNcNYo7So)
> > > 
> > > 
> > > have you tryed again?
> > 
> > 
> > Yeah, I've tried and it works but takes a while to load
> 
> How many songs do you have on your device?

**Comment by JZITNIK-github** [comment]
I have 100 songs on my phone and it works fine. It takes like 2 seconds to load. I'll try to optimize the on device page even more on Wednesday.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.24
