### ISSUE TITLE
Place these buttons above or just a little higher

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#829]
### Description

While editing lyrics the "confirm" and "cancel" button being at the top instead of bottom.

### Suggested Solution

![1708757390918](https://github.com/fast4x/RiMusic/assets/85461823/9eb74c8a-787e-4bd3-a092-a5c6205008df)

Probably I'm not really clear enough. But should be enough to understand I guess?

### Alternatives

Or maybe just fix those buttons again and idk make them appear a little higher. I mean how it's like now I have to tap on back button again to "confirm". See:
![1708757408685](https://github.com/fast4x/RiMusic/assets/85461823/f406a44c-51d0-46d2-8cdd-794b133b0d40)

**Comment by OrangeZXZ** [comment]
You mean the buttons are too close to the bottom for you?

**Comment by fast4x** [comment]
Improved, available from version 0.6.24
