### ISSUE TITLE
Automatic backup function

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#83]
### Description

I know a backup function is already available but an automatic backup function like Blackhole would be very useful or a time-controlled e.g. automatic backup once a day, it would also be cool if you could specify your cloud as the storage location for the backup file. In case you change your phone or tablet or it gets stolen or broken, you would always have a backup file to restore.

### Suggested Solution

*

**Comment by KondaShivaradhan** [comment]
Im up! I wanted to open a new feature request for this specific feature. I can handle all the backed services but I lack skills in Android. Does anyone want to team up?
 Things I will handle
- Backend
- cloud database
- hosting 
- Backend will also be an opensource repo

I want help with
- Android Things
- linking the backend with the UI.
I don't know much about android

**Comment by KondaShivaradhan** [comment]
@fast4x @siggi1984 what do you guys think?

**Comment by fast4x** [comment]
is active but not priority
