### ISSUE TITLE
Remove the plat button padding

### ISSUE THREAD

**Issue by Toiletmason** [fast4x/RiMusic#830]
### Description

We have the options to change the shape, but removing it would be nice.
![ResizedImage_2024-02-24_00-47-08_9310](https://github.com/fast4x/RiMusic/assets/23698116/5a525e56-efbf-4efe-9bc0-6781f4b84c5f)

### Suggested Solution

Make it the color of the background based on the theme.

**Comment by OrangeZXZ** [comment]
> Make it the color of the background based on the theme.

I think instead of making it the color of the background it is easier to just remove it like the skip and unskip buttons

Also good idea!

**Comment by fast4x** [comment]
Implemented disable button type, available from version 0.6.25
