### ISSUE TITLE
Disable swiping left and right on thumbnails to skip tracks

### ISSUE THREAD

**Issue by Toiletmason** [fast4x/RiMusic#832]
### Description

I do it on accident most of the time and it's pretty annoying. 

### Suggested Solution

If like to not be able to skip tracks accidentally.

**Comment by OrangeZXZ** [comment]
There is an option to disable and it was already discussed that sometime we would add maybe an animation like on mail apps when you swipe left or right

**Comment by OrangeZXZ** [comment]
> add maybe an animation like on mail apps when you swipe left or right to prevent it being accidental

Like that to show the action and give the user an confirmation without an pop-up

![Screen_Recording_20240224_102536_GitHub_1.gif](https://github.com/fast4x/RiMusic/assets/104271365/9a3de01d-7f34-4544-b83e-298936a74057)
