### ISSUE TITLE
Android Auto like a song do not work

### ISSUE THREAD

**Issue by MightyShadow702** [fast4x/RiMusic#839]
### Steps to reproduce the bug

1. Open RiMusic in Android Auto
2. Play any Song
3. Try to like this Song

### Expected behavior

I would except the song after this would be at my liked songs and / or also the symbol should change. I tried it with many songs from some playlists, I do not know if it works in the other direction too, so unlike a song or something like this.

### Actual behavior

It do nothing, no song where I tried is in my liked list, also in the UI of android auto, the symbol do not change

### RiMusic version

0.6.22

### Android version

Android 14

### Additional information

Car: Hyundai Ioniq vFL

**Comment by fast4x** [comment]
I will fix it

**Comment by fast4x** [comment]
Implemented, like and download button action. Like now it's ok but in download there is a bug on update icon state.
Available from version 0.6.27
