### ISSUE TITLE
The option of sorting in the favorites playlist

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#840]
### Description

In my opinion, the option of sorting in the favorites playlist should be removed and the favorites playlist should be treated in the same way as Spotify and YouTube Music, i.e. in the same way as ViMusic.

![Screenshot_20240224-195119](https://github.com/fast4x/RiMusic/assets/103368536/45e86d01-39aa-413e-b024-cf2aa6632dce)

### Suggested Solution

#

**Comment by OrangeZXZ** [comment]
> ### Description
> 
> In my opinion, the option of sorting in the favorites playlist should be removed and the favorites playlist should be treated in the same way as Spotify and YouTube Music, i.e. in the same way as ViMusic.
> 
> ![Screenshot_20240224-195119](https://github.com/fast4x/RiMusic/assets/103368536/45e86d01-39aa-413e-b024-cf2aa6632dce)
> 
> 
> ### Suggested Solution
> 
> #
> 
> ### Alternatives
> 
> _No response_
> 
> ### Additional Context
> 
> _No response_

you mean see them in the order you added?

**Comment by siggi1984** [comment]
> > ### Description
> > In my opinion, the option of sorting in the favorites playlist should be removed and the favorites playlist should be treated in the same way as Spotify and YouTube Music, i.e. in the same way as ViMusic.
> > ![Screenshot_20240224-195119](https://private-user-images.githubusercontent.com/103368536/307545094-45e86d01-39aa-413e-b024-cf2aa6632dce.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MDMzMDIsIm5iZiI6MTcwODgwMzAwMiwicGF0aCI6Ii8xMDMzNjg1MzYvMzA3NTQ1MDk0LTQ1ZTg2ZDAxLTM5YWEtNDEzZS1iMDI0LWNmMmFhNjYzMmRjZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxOTMwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDNhMWI3OTczNjkzMGFjZmNlMDEwZjg1MzEyMmYxNDI1Nzc0OTNlZjZjOGI0ZDA3ZDJkZWI5NmRjZjg2YzEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-pHoD9c2c_hmNgBVGXwXvP5goGUHhbEqd3aGEW2OfyU)
> > ### Suggested Solution
> > 
> > ### Alternatives
> > _No response_
> > ### Additional Context
> > _No response_
> 
> you mean see them in the order you added?

Yes exactly the currently liked song should always be at the top regardless of when it was added to the library

**Comment by OrangeZXZ** [comment]
> Yes exactly the currently liked song should always be at the top regardless of when it was added to the library

![SmartSelect_20240224_203348.jpg](https://github.com/fast4x/RiMusic/assets/104271365/e6b558f0-05a5-4a42-931b-21d5cf5bcd72)

You can try taping on the text and chose the "Date Aded" option that way the newest song is at the top if not tap the arrow next to it

It this is still not working that means it's a bug and needs to be patched and not removed since a lot of peoples and me included use other sorting verry often

**Comment by siggi1984** [comment]
> > Yes exactly the currently liked song should always be at the top regardless of when it was added to the library
> 
> ![SmartSelect_20240224_203348.jpg](https://private-user-images.githubusercontent.com/104271365/307545545-e6b558f0-05a5-4a42-931b-21d5cf5bcd72.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MDM5MjMsIm5iZiI6MTcwODgwMzYyMywicGF0aCI6Ii8xMDQyNzEzNjUvMzA3NTQ1NTQ1LWU2YjU1OGYwLTA1YTUtNGE0Mi05MzFiLTIxZDVjZjViY2Q3Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxOTQwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGY1ODk1MDU3ZmU2ZDhhMjkxM2MzOTk4MGNjMGQyMjAxZTgzMzBhZDE4ZTJlNjQ3MzczNzQ5Yjg5YjU1ZDFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CDvbJaeddIrG2gPEqUhBr2HWfe7oHwahfAAeuEKbfro)
> 
> You can try taping on the text and chose the "Date Added" option that way the newest song is at the top if not tap the arrow next to it
> 
> If this is still not working that means it's a bug and needs to be patched and not removed since a lot of peoples and me included use other sorting verry often

I know the function, but then the songs are sorted after being added to the library and not after being added to the playlist. Basically, I think the favorites playlist should be handled in the same way as ViMusic. We have a sorting option in all other playlists and song areas

**Comment by OrangeZXZ** [comment]
> I know the function, but then the songs are sorted after being added to the library and not after being added to the playlist. Basically, I think the favorites playlist should be handled in the same way as ViMusic. We have a sorting option in all other playlists and song areas

you mean the songs keeps the place even when unliking and liking back?

Then we should add extra verifications to always add at the top and not keep the place like it was before

**Comment by siggi1984** [comment]
> > I know the function, but then the songs are sorted after being added to the library and not after being added to the playlist. Basically, I think the favorites playlist should be handled in the same way as ViMusic. We have a sorting option in all other playlists and song areas
> 
> you mean the songs keeps the place even when unliking and liking back?
> 
> Then we should add extra verifications to always add at the top and not keep the place like it was before

My English is not very good but if I have understood you correctly. This could be a solution.

**Comment by siggi1984** [comment]
> > > I know the function, but then the songs are sorted after being added to the library and not after being added to the playlist. Basically, I think the favorites playlist should be handled in the same way as ViMusic. We have a sorting option in all other playlists and song areas
> > 
> > 
> > you mean the songs keeps the place even when unliking and liking back?
> > Then we should add extra verifications to always add at the top and not keep the place like it was before
> 
> My English is not very good but if I have understood you correctly. This could be a solution.

Just take a look at the favorites playlist function in ViMusic. I think then you will understand what I mean.

**Comment by OrangeZXZ** [comment]
@fast4x for this one you need to always add the Liked song at the top in the "Date Added" sorting if you unlike then like back

**Comment by fast4x** [comment]
Yes thanks

**Comment by fast4x** [comment]
Implemented, available from version 0.6.23
@siggi1984 @OrangeZXZ  Thank you because I forgot to develop the sort by data liked, now added in all playlists and in songs tab in home

**Comment by siggi1984** [comment]
> Implemented, available from version 0.6.23 @siggi1984 @OrangeZXZ Thank you because I forgot to develop the sort by data liked, now added in all playlists and in songs tab in home

Okay, I'm curious to see how it works. You probably mean from version 6.24.
Version 6.23 was released on Friday.🙂🙂🙂🙂

**Comment by fast4x** [comment]
ahahahahaah correct 0.6.24
