### ISSUE TITLE
Double tap to like

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#843]
### Description

I think that a fast double tap to like on the song picture can be a great way to make easier likes on android auto and also giving another way of liking (I also got this random from yt shorts and tiktok)

### Suggested Solution

add a double tap feature to like it also gets turned off if you turn off gestures to skip songs

**Comment by fast4x** [comment]
Implemented, available from version 0.6.24

**Comment by Vishcot** [comment]
shall you please add this feature to the list as well? is that possible like double clicking on this list of songs in favorites for quick add & remove? 

![Screenshot_20240225-232925.png](https://github.com/fast4x/RiMusic/assets/136909951/60c22224-b6cd-43b5-a2ad-0e0fa02e9c63)

**Comment by fast4x** [comment]
explain better

**Comment by OrangeZXZ** [comment]
> explain better

double tap on the playlist feature to be added

**Comment by fast4x** [comment]
maybe, but it's confirmed?

**Comment by OrangeZXZ** [comment]
> maybe, but it's confirmed? 

it can be double tap on songs for easy like too si idk

**Comment by Vishcot** [comment]
> maybe, but it's confirmed? 

double tap anywhere on the thumbnail (except in player) like search list, playlist or in favorites..will favourite or un-favorite song.
