### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by gun4qmm7h** [fast4x/RiMusic#845]
### Steps to reproduce the bug

Open library then go to favorite then click on any song. This happens randomly so I also added the logs as well then the crash happen.

### Expected behavior

Not to crash

### Actual behavior

Crash

### Logs

--------- switch to main
1708830377.144 22883 22883 W .fast4x.rimusic: type=1400 audit(0.0:25648): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=402 scontext=u:r:untrusted_app:s0:c253,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=it.fast4x.rimusic
1708830377.177 22883 22883 I ExoPlayerImpl: Init 46c71b6 [AndroidXMedia3/1.2.1] [oriole, Pixel 6, Google, 34]
1708830377.196 22883 22883 W MediaSessionCompat: Couldn't find a unique registered media button receiver in the given context.
1708830377.357 22883 22883 I MediaBrowserService: No root for client com.android.systemui from service android.service.media.MediaBrowserService$ServiceBinder$1
1708830383.147 22883 22969 D ProfileInstaller: Installing profile for it.fast4x.rimusic

### RiMusic version

0.6.23

### Android version

Grapheneos 14

**Comment by fast4x** [comment]
Your system Is GrapheneOS i haven't tested. But crash occur with Android Auto? From log  i understand this...

**Comment by fast4x** [comment]
Try to enable invincible service and remove battery optimization

**Comment by gun4qmm7h** [comment]
I have remove battery optimization and it seems to be working without any crashing. It does happen randomly so im not sure if its fully fix. Also what is invincible services and how do I enable it?

**Comment by alexou2** [comment]
I have the same issue sometimes when i click on a button. The app will crash if I click on the settings button too much times.

**Comment by fast4x** [comment]
From home click on settings button and crash?

**Comment by alexou2** [comment]
I need to click a bunch of times on the settings/back button and it will crash
