### ISSUE TITLE
Inconsistency when Displaying the Playlist View after Enabling the Arrow Button

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#847]
### Description

In the current version of the app, there is an inconsistency when displaying the playlist view in the fullscreen mode of the player. By default, users can swipe up the bottom bar with the player controls to access the playlist view, indicated by the middle white pill icon. 

![ZomboDroid_25022024082605](https://github.com/fast4x/RiMusic/assets/71184627/6fa57171-55cc-4101-aa26-05dce10f62a5)

However, there is also an option to display an additional arrow symbol in the bottom bar. Upon activating this feature, the middle white pill icon remains, allowing both swiping up the bar and tapping the arrow symbol to open the playlist. This results in inconsistency when displaying the playlist view.

![ZomboDroid_25022024082701](https://github.com/fast4x/RiMusic/assets/71184627/4872f86a-a5f4-4993-839b-520352614904)

### Suggested Solution

After activating the arrow symbol, swiping up the player controls bar should no longer be possible. Instead, the playlist should only be accessible by tapping the arrow symbol. To visually clarify this, the white pill icon should disappear after activating the arrow symbol. This will make the display of the playlist view more logical.

![ZomboDroid_25022024090549](https://github.com/fast4x/RiMusic/assets/71184627/66b63dc9-f76e-4fe6-a9ba-13b987aea355)

**Comment by fast4x** [comment]
Nice

**Comment by OrangeZXZ** [comment]
> After activating the arrow symbol, swiping up the player controls bar should no longer be possible. Instead, the playlist should only be accessible by tapping the arrow symbol. To visually clarify this, the white pill icon should disappear after activating the arrow symbol. This will make the display of the playlist view more logical.

I use often both and it would be horrible to use just one for me...

Maybe add a new on off switch to activate the pill and if on it allows pulling up

**Comment by dAtA-TRoN** [comment]
> > After activating the arrow symbol, swiping up the player controls bar should no longer be possible. Instead, the playlist should only be accessible by tapping the arrow symbol. To visually clarify this, the white pill icon should disappear after activating the arrow symbol. This will make the display of the playlist view more logical.
> 
> I often use both and it would be horrible to use just one for me...
> 
> Maybe add a new on off switch to activate the pill and if on it allows pulling up
> 

Here's the improved English translation:

I could live with that as well. Personally, I always enable the arrow button so I don't accidentally swipe, as I don't want to use that feature. Therefore, from my perspective, it would be better to avoid input errors. But as I said, I would be completely satisfied with your solution. I believe the appropriate setting would be something like 'disable swiping to show playlist.' If the pill symbol also disappears, then I think we'll all be happy.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.24

**Comment by dAtA-TRoN** [comment]
> Implemented, available from version 0.6.24

![proxy-image(1)-02.jpeg](https://github.com/fast4x/RiMusic/assets/71184627/68a7395b-f176-480a-9170-5ed72c50d897)

**Comment by fast4x** [comment]
No, I’m just a project manager. LOL 😆

**Comment by fast4x** [comment]
No, it means that in my working life I am project manager, so in RiMusic I organize the best possible analysis, evaluation and development times. There are things that can be developed very quickly while others require more time.

**Comment by dAtA-TRoN** [comment]
Well, that means you're kind of a wizard after all 😌.

**Comment by fast4x** [comment]
Thanks
