### ISSUE TITLE
Crash on shuffling

### ISSUE THREAD

**Issue by Nathanwoodburn** [fast4x/RiMusic#848]
### Steps to reproduce the bug

1. Open playlists
2. Select any playlist
3. Press shuffle
4. Crashes then redo steps and it works. 

### Expected behavior

It shouldn't crash and start the playlist. 

### Actual behavior

When you start a playlists from shuffle the app will randomly crash. 

### RiMusic version

0.6.23

### Android version

Android 13

**Comment by fast4x** [comment]
Open app, play some seconds one song, ho tò playlist and shuffle, there Is a error?

**Comment by Nathanwoodburn** [comment]
Don't think so. I can't seem to reproduce it at the moment. Just happened when there wasn't any previous song queue.

**Comment by Cloudimperial** [comment]
It happens at random times on my Android 11. Here is how it happens. Attached a clip

https://github.com/fast4x/RiMusic/assets/161277586/0b8b7ff9-7795-44c8-925c-f7233636d633

**Comment by Nathanwoodburn** [comment]
> It happens at random times on my Android 11. Here is how it happens. Attached a clip

Thanks. The problem seemed to never show up when I tried to record it
