### ISSUE TITLE
Option to flip the sidebar from left to right

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#850]
### Description

The main navigation within the app is done through the sidebar, which is currently positioned exclusively on the left. Personally, I find this position a bit inconvenient as I always have to use my second hand for navigation. Therefore, it would be great if we had the option to flip the sidebar from the left to the right side.

### Suggested Solution

Add a toggle switch within the app options that allows flipping the main navigation sidebar consistently across all page menus within the app from the left to the right side. That would standardize the user experience for both right and left-handed individuals.

Here are two example illustrating the proposed feature, once from the main screen and once from the app settings:

![ZomboDroid_25022024110113](https://github.com/fast4x/RiMusic/assets/71184627/fff7afd3-8f1e-4fdd-9917-ea473f507524)

![ZomboDroid_25022024110046](https://github.com/fast4x/RiMusic/assets/71184627/63b47153-dbea-4652-abbc-a51a1927ef3a)

**Comment by OrangeZXZ** [comment]
> ### Description
> 
> The main navigation within the app is done through the sidebar, which is currently positioned exclusively on the left. Personally, I find this position a bit inconvenient as I always have to use my second hand for navigation. Therefore, it would be great if we had the option to flip the sidebar from the left to the right side.
> 
> ### Suggested Solution
> 
> Add a toggle switch within the app options that allows flipping the main navigation sidebar consistently across all page menus within the app from the left to the right side. That would standardize the user experience for both right and left-handed individuals.
> 
> Here are two example illustrating the proposed feature, once from the main screen and once from the app settings:
> 
> ![ZomboDroid_25022024110113](https://github.com/fast4x/RiMusic/assets/71184627/fff7afd3-8f1e-4fdd-9917-ea473f507524)
> 
> ![ZomboDroid_25022024110046](https://github.com/fast4x/RiMusic/assets/71184627/63b47153-dbea-4652-abbc-a51a1927ef3a)
> 
> 
> ### Alternatives
> 
> _No response_
> 
> ### Additional Context
> 
> _No response_

This is a really good idea! It will also be good for peoples that use the left hand

**Comment by fast4x** [comment]
You mean support for RTL layout direction
#506

**Comment by dAtA-TRoN** [comment]
I'm not sure exactly what you mean as English is not my native language. My intention was to implement what I depicted in the mockups. I just want to move the main navigation of the app, specifically the sidebar tabs, from the left to the right side. It would be great if that's doable, but I also realize it might involve significant effort. I have only a layman's understanding of programming, so I'm not sure if it's feasible. If there are still uncertainties, please let me know, and I'll try to describe it more clearly.

**Comment by dAtA-TRoN** [comment]
> This is a really good idea! It will also be good for peoples that use the left hand

Yes, I must admit that I didn't express myself quite clearly, as it was easier for me to explain it this way. I also use the app with my right hand. It would have been more accurate to say that I find it more practical to place the sidebar tabs on the right side instead of the left, simply because I operate the app with my right hand. However, I thought it might come across as arrogant or know-it-all if I immediately suggested reversing the entire app navigation. I assume the original creator of the app had their reasons for it (or they're simply left-handed 🫣😅). Therefore, I thought it might be more polite to phrase it the way I did. Nevertheless, regardless of how, this customization option would be beneficial for everyone, as each user could adjust the sidebar tabs according to their preference.

**Comment by fast4x** [comment]
ok thanks for nice details.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.24

**Comment by dAtA-TRoN** [comment]
> Implemented, available from version 0.6.24

Cool, I'm really pleased that you actually implemented the idea. And so quickly too. Awesome man 👏🏼🤩!

**Comment by fast4x** [comment]
Thanks, also #852

**Comment by dAtA-TRoN** [comment]
> Thanks, also #852
Very very nice!

**Comment by senolfndk** [comment]
maybe in the bottom navigation bar

**Comment by senolfndk** [comment]
could be bottom navigation bar

**Comment by senolfndk** [comment]
Can you add bottom navigation bar option?

**Comment by fast4x** [comment]
bottom or top in future, I don't know when.
