### ISSUE TITLE
"View playlist" button does nothing

### ISSUE THREAD

**Issue by CodeShakingSheep** [fast4x/RiMusic#851]
### Steps to reproduce the bug

1. Copy any YouTube Music Playlist link, e.g. https://music.youtube.com/playlist?list=RDCLAK5uy_kWiJXUNLZM9EyS3GBGznl1ku8_cOos97U&playnext=1&si=Fk--a_2JW1OPnpxd to the search field in RiMusic.
2. Hit "View playlist" button.

### Expected behavior

The playlist should be displayed in RiMusic and should be available for importing it.

### Actual behavior

Nothing happens when hitting the "View playlist" button.

### Screenshots/Screen recordings

![Screenshot_20240225-092138](https://github.com/fast4x/RiMusic/assets/19874562/2b370aa5-b8e1-4b7f-b0f7-2698e4eab915)

### RiMusic version

0.6.22

### Android version

Android 14

### Additional information

Thanks for this app :)

**Comment by OrangeZXZ** [comment]
You should use the link option at the left

**Comment by CodeShakingSheep** [comment]
Why does it even show the "View Playlist" button in the first place if it's unusable? It's a bit confusing. To improve UX I have the following suggestions. 

1. Showing a hint when entering a link
If it's a link, it would be great to show a hint, such as "Looks like you've been entering a link. Please select "Link" on the left side and run the search again.". 

OR

2. Automatically open the link tab
Instead of showing a hint, the app could detect a link being entered, automatically open the link tab and paste the Url to the search field there.

What do you think about it @fast4x?

**Comment by fast4x** [comment]
You are right!
I forgot that there was still the button, I immediately remove it. Because it was replaced by the tab Go to link

**Comment by fast4x** [comment]
Fixed, available from version 0.6.24
