### ISSUE TITLE
UI Improvement ideas

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#852]
### Suggested Ideas
- [x] When adding a song to a playlist, a list of all playlists appears. Show an icon next to playlists where the song has already been added for quick visual confirmation.
- [x] In playlists, there is an icon that allows us to hold and change the position of any song. It comes in handy when sorting the playlist by `Manual Position`. However, it's useless in other sorting types. I suggest showing it only for `Manual Position` sorting.

<br>

- [x] Provide an option to display only icons in the sidebar instead of text. The vertical orientation of text in contrast to the horizontal layout of the rest of the application can be disorienting for users.
- [x] Add tooltips for all buttons in UI to enhance user understanding. https://github.com/fast4x/RiMusic/issues/509
- [x] Allow users to customize the placement of sidebar buttons. For instance, users should be able to position the sidebar at the:
    - [x]  **_top_**, 
    - [x] **_bottom_**, or 
    - [x] **_Left, Right side_**
- [x] Change text of sorting by '**position**' to **'Manual'** to make it more clear.

**Comment by fast4x** [comment]
Implemented navigation bar position to left/right by ui settings
Available from version 0.6.24

**Comment by fast4x** [comment]
This: On the 'Quick Tips' page, update the label text from 'Tips' to 'For You' to make it more clear.
You can change translation of text "Tips" in Crowdin

**Comment by fast4x** [comment]
Thus: When adding a song to a playlist, a list of all playlists appears. Enhance user experience by incorporating an icon next to playlists where the song has already been added, providing quick visual confirmation.

Do you can explain better, please?

**Comment by fast4x** [comment]
Implemented navigation bar type with only icon or icon and text. Change it in ui settings.
Available from version 0.6.24

**Comment by fast4x** [comment]
Well, details always make a difference.

**Comment by dAtA-TRoN** [comment]
> Well, details always make a difference.

Just as an example you probably already know: Here's how YouTube has addressed it with its playlists, using checkboxes next to each playlist.

![Screenshot_2024-02-29-21-51-18-78_f9ee0578fe1cc94de7482bd41accb329-01.jpeg](https://github.com/fast4x/RiMusic/assets/71184627/e13ba18d-3d1d-44ce-9589-6ca59d79303e)

**Comment by sayyid5416** [comment]
@fast4x Also, it would be much better if we mark the task as completed in this ‘feature request’ after it’s been implemented. That way, it would be easier to track which features have already been added.

**Comment by dAtA-TRoN** [comment]
@sayyid5416 

> Thanks @dAtA-TRoN for providing the ss to explain it.

My pleasure.

**Comment by fast4x** [comment]
Top and bottom bar position will be available next versions

**Comment by fast4x** [comment]
> @fast4x Also, it would be much better if we mark the task as completed in this ‘feature request’ after it’s been implemented. That way, it would be easier to track which features have already been added.

Sure, there are 2 task to complete

**Comment by sayyid5416** [comment]
Why close this? Some items are still pending!

**Comment by sayyid5416** [comment]
@fast4x  Why close this? Some items are still pending!

**Comment by sayyid5416** [comment]
## Added new item to list
- Allow users to rearrange items of the navigation bar

**Comment by sayyid5416** [comment]
## Added 2 more items to feature request:
- Change text of sorting by '**position**' to **'Manual'** to make it more clear.
- In playlists, there is an icon that allows us to hold and change the position of any song. It comes in handy when sorting the playlist by ‘Position.’ However, it becomes redundant in other sorting types. I suggest hiding it when the playlist is sorted by other methods, such as title, date etc

**Comment by fast4x** [comment]
Implemented top bar navigation, available from version 0.6.29

**Comment by sayyid5416** [comment]
> Implemented top bar navigation, available from version 0.6.29

You rock 🔥

![SchoolOfRockJackBlackGIF](https://github.com/fast4x/RiMusic/assets/78584556/49709581-45d7-4395-a692-a3a405d53714)

**Comment by sayyid5416** [comment]
btw, can you provide a custom version so I could provide feedback

**Comment by dAtA-TRoN** [comment]
![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/3d77f254-7f99-48be-86c2-4f13f56cca6d)

**Comment by fast4x** [comment]
> btw, can you provide a custom version so I could provide feedback

Feedback after release, I'm sorry.

**Comment by sayyid5416** [comment]
> > btw, can you provide a custom version so I could provide feedback
> 
> Feedback after release, I'm sorry.

that's totally fine, will wait for it

**Comment by fast4x** [comment]
Also implemented bottom bar, available from version 0.6.29

**Comment by dAtA-TRoN** [comment]
> Also implemented bottom bar, available from version 0.6.29

F I N A L L Y ! ! !

https://github.com/fast4x/RiMusic/assets/71184627/2f07f952-8151-4e06-825d-a490efcfba7a

**Comment by sayyid5416** [comment]
Thanks. This feature will be very useful.

Can you take a look at this one, it's very annoying 😅
![Screenshot_2024-04-26-02-54-15-228_com microsoft emmx-edit](https://github.com/fast4x/RiMusic/assets/78584556/ce584fdd-aa36-4e53-9d13-3657431325f2)

**Comment by fast4x** [comment]
What's icon?

**Comment by sayyid5416** [comment]
> Which icon?

![IMG_20240426_053508_911](https://github.com/fast4x/RiMusic/assets/78584556/6134005f-be06-4421-99fe-02eaa90c37a1)

👆 This one.

**Comment by dAtA-TRoN** [comment]
> > Which icon?
> 
> ![IMG_20240426_053508_911](https://github.com/fast4x/RiMusic/assets/78584556/6134005f-be06-4421-99fe-02eaa90c37a1)
> 
> 👆 This one.

AAAAhhh I see my playlist 🤩🫠😬!!

And yes, what about the manual sorting function? Is that a mockup, and can users not sort the songs themselves (yet), or is it already possible somehow? If so, then I would have needed this function recently. Because I noticed that in my favorites list, two songs had to be re-added because YouTube Music had once again shifted them internally. While it's relatively quick to fix, it's still annoying because my default filter I use in my 'favorites' list is 'date favorited'. Over time, users like my get very used to the existing order since the newest tracks are always listed at the top, and they're not as overplayed as the other songs. However, if songs have to be re-added due to the problem I've described earlier (thanks, YouTube Music 🙄), it's inevitably change the existing order of the 'date favorited' filter. Older songs are now listed at the top, which is frustrating from my perspective. I would wish to be able to manually correct this afterwards.

**Comment by sayyid5416** [comment]
This icon should be visible only in `Manual Position` sorting.

In all other sortings - This icon should be hidden.

**Comment by dAtA-TRoN** [comment]
> This icon should be visible only in `Manual Position` sorting.
> 
> In all other sortings - This icon should be hidden.

🫵🏼😏👌🏼

**Comment by fast4x** [comment]
> This icon should be visible only in `Manual Position` sorting.
> 
> In all other sortings - This icon should be hidden.

yes you are right

**Comment by dAtA-TRoN** [comment]
So, I've just double-checked. It seems that this sorting function isn't available in the standard playlists. It would be wonderful if it could be added in the future 🛐.

**Comment by fast4x** [comment]
>  In playlists, there is an icon that allows us to hold and change the position of any song. It comes in handy when sorting the playlist by Manual Position. However, it's useless in other sorting types. I suggest showing it only for Manual Position sorting.

Implemented, available from version 0.6.32

**Comment by fast4x** [comment]
Implemented icon for song presence in playlist, available from version 0.6.32

**Comment by sayyid5416** [comment]
@fast4x 
1. That icon to rearrange songs not showing up in `descending` sorting of `Manual`. It's only showing in ascending sorting.
2. Playlist presence song feature: not working for me. Is there some settings for it?

**Comment by fast4x** [comment]
> @fast4x 
> 1. That icon to rearrange songs not showing up in `descending` sorting of `Manual`. It's only showing in ascending sorting.
> 2. Playlist presence song feature: not working for me. Is there some settings for it?

it's normal reorder work in ascending order.... 1,2,3,4

**Comment by sayyid5416** [comment]
> it work...
> 
> ![Screenshot_2024-04-26-22-18-55-709_it.fast4x.rimusic-edit.jpg](https://private-user-images.githubusercontent.com/1484476/326103561-12dd790d-6b78-4772-8839-ceee817b9aa4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOixZTA0MzBhNjg2YWIwNDUwNzI1NGM5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IoaY1LsxvxDP1Vf5N_6iP9mdbaIuO4NlsuMghefLaJI)

It's not showing for me
![image](https://github.com/fast4x/RiMusic/assets/78584556/8f2f86b6-d2a3-499f-ab65-76de27c4a65e)

<br>

> it's normal reorder work in ascending order.... 1,2,3,4

Why though?

**Comment by fast4x** [comment]
it work...

![Screenshot_2024-04-26-22-18-55-709_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/12dd790d-6b78-4772-8839-ceee817b9aa4)

Because natural position into playlist go from 1 to bigger...

**Comment by sayyid5416** [comment]
I reinstalled the latest version from release page. But this tick icon is still not showing for me. Are you sure you are using the latest version you released and not some unreleased version?

![ConfusedGIF](https://github.com/fast4x/RiMusic/assets/78584556/1998f02d-e8e4-4541-a2d3-52a5cfc503d0)

**Comment by fast4x** [comment]
last release..

**Comment by sayyid5416** [comment]
@dAtA-TRoN Can you test if your app is showing this icon?

**Comment by aneesh1122** [comment]
> @dAtA-TRoN Can you test if your app is showing this icon?

Well, it's not only you. I'm also not able to see that icon

**Comment by dAtA-TRoN** [comment]
> @dAtA-TRoN Can you test if your app is showing this icon?

@sayyid5416

For me it seems to work. Have you tried out different songs yet?

![Screenshot_2024-04-27-04-44-13-43_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/797b809a-098e-4dee-a99e-ca6d369abcf6)

**Comment by aneesh1122** [comment]
> > @dAtA-TRoN Can you test if your app is showing this icon?
> 
> @sayyid5416
> 
> For me it seems to work. Have you tried out different songs yet?
> 
> ![Screenshot_2024-04-27-04-44-13-43_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/797b809a-098e-4dee-a99e-ca6d369abcf6)
> 
> 

Works only when the menu style is set as 'list'

**Comment by dAtA-TRoN** [comment]
> Works only when the menu style is set as 'list'

I see. Well, I don't use anything else.

**Comment by fast4x** [comment]
I'm sorry, you are right, I'll develop also in grid style.

**Comment by sayyid5416** [comment]
Oh, that was the reason; I use grid menu style. I was going nuts over this.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.33
