### ISSUE TITLE
Shuffle-play loops the track

### ISSUE THREAD

**Issue by Cloudimperial** [fast4x/RiMusic#855]
### Steps to reproduce the bug

1. Go to a playlist.
2. Click on shuffle-play button.

### Expected behavior

"Now Playing" Screen gets popup, after the song completes it should play the next song in the queue.

### Actual behavior

Next song doesn't play, it loops the song forever

### Screenshots/Screen recordings

![Screenshot_20240226-102846](https://github.com/fast4x/RiMusic/assets/161277586/12150905-35ea-4b16-a694-e53b9cae62ee)

https://github.com/fast4x/RiMusic/assets/161277586/7843a65a-dced-4e0e-ac00-ea30900170d9

### RiMusic version

0.6.23

### Android version

Android 11

**Comment by JZITNIK-github** [comment]
You have turned on the track loop feature. When you have that on it will play the songs over and over again. 
If you don't want to loop the songs, turn this off at the bottom:
![image](https://github.com/fast4x/RiMusic/assets/72742578/137d46d7-7192-43d6-a828-0a59a72bbaa6)

**Comment by Cloudimperial** [comment]
> You have turned on the track loop feature. When you have that on it will play the songs over and over again. 
> If you don't want to loop the songs, turn this off at the bottom:
> ![image](https://github.com/fast4x/RiMusic/assets/72742578/137d46d7-7192-43d6-a828-0a59a72bbaa6)
> 
> 

I see, how do i turn it off so that it will not be a default when i shuffle-play?

**Comment by JZITNIK-github** [comment]
It will stay disabled until you turn it on again.
