### ISSUE TITLE
[Feature]: Share Playlist (fix file permission)

### ISSUE THREAD

**Issue by claxcian** [fast4x/RiMusic#857]
### Description

It would be nice to be able to share the created playlist with RiMusic

### Suggested Solution

The button to share the playlist details should be added. So that 2 users who use RiMusic can exchange their playlists

**Comment by claxcian** [comment]
Yes but is not the same

**Comment by fast4x** [comment]
The same of what? RiMusic haven't a technological infrastructure, is just a simple app to play music. Can share playlist with other user sending playlist exported as file. Destination user can made import in their playlists.

**Comment by claxcian** [comment]
Sorry i don't see the export button to playlist. I think export total in data section

**Comment by fast4x** [comment]
Inside playlist, 3 dots menu icon you found Export playlist.

**Comment by claxcian** [comment]
I try to export, and it's ok, but import i don't select the file, i don't pick up. Do you tray? Thanks

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/wiki/FAQs#what-is-the-csv-file-structure-for-importing-a-playlist-in-library

**Comment by claxcian** [comment]
![Screenshot_20240302_215417_Files](https://github.com/fast4x/RiMusic/assets/46830063/38aead36-bd5f-42cb-ad74-fd9b56579997)

**Comment by claxcian** [comment]
This file was created by Rimusic before but don't pick to import..

**Comment by fast4x** [comment]
Try to move or create the file to Downloads, tell me if it makes you select

**Comment by fast4x** [comment]
Your Android version?

**Comment by claxcian** [comment]
Android 14. I just try to move the file to download folder but don't working

**Comment by fast4x** [comment]
Ok, potrebbe essere un problema di permessi di lettura, appena pronto ti invio una versione custom da provare.

**Comment by claxcian** [comment]
Ok grazie

**Comment by claxcian** [comment]
Ho provato anche nella root ma non funziona

**Comment by fast4x** [comment]
ok grazie verifico subito

**Comment by fast4x** [comment]
Prova questa version custom
https://rimusic.xyz/download

**Comment by claxcian** [comment]
Ora funziona.

L'ho scritto anche in altro topic che questa versione ha continui crash quando chiudi la app e a riapri. Forse la playlist persistente che io attiva

**Comment by fast4x** [comment]
Ok verifico anche l'altra condizione

**Comment by fast4x** [comment]
Prova a disattivare la coda persistente per capire se crasha lo stesso. Fammi sapere, grazie.

**Comment by claxcian** [comment]
Togliendo quella impostazione è ok. Infatti crashava all'avvio della app.

**Comment by fast4x** [comment]
Perfetto, approfondisco

**Comment by fast4x** [comment]
> Prova questa version custom
> https://rimusic.xyz/download

Scarica nuovamente la custom vedi se risolve

**Comment by claxcian** [comment]
Si ci fa.
Tu prova ad aprire la musica. Stoppare. Uscire dalla app e chiudere anche il player che hai nelle notifiche e quando la apri va in crash.
Inoltre se chiudo la app dai processi quando la riapro la coda non viene riproposta.

**Comment by fast4x** [comment]
È assurdo, io non l'errore... e dai logs non evidenzio errori.
Devo capire meglio in che punto...

**Comment by fast4x** [comment]
A breve te ne mando un'altra versione, provala per favore, non salverà la coda perchè isolo una routine, verifica se crasha lo stesso. A tra poco

**Comment by fast4x** [comment]
Puoi scaricare

**Comment by fast4x** [comment]
Ok forse ho capito...

**Comment by fast4x** [comment]
Prova la nuova custom https://rimusic.xyz/download

**Comment by claxcian** [comment]
Ok adesso Ok. 👍

**Comment by fast4x** [comment]
PERFETTO, grazie.

**Comment by sayyid5416** [comment]
@fast4x I see there are many issues which have been _**fixed**_ or _**implemented**_ but they are still `open`. Is there any specific reason for that?

**Comment by fast4x** [comment]
No, maybe I didn’t notice, you can close them if you want and you can.

**Comment by fast4x** [comment]
ahhh consider closing only those who do not have the label. I close them in the release...

**Comment by sayyid5416** [comment]
Oh I get it now. `Implemented` label is for those issues/feature requests which have been implemented and not yet released.

Thanks for clarifying.

**Comment by fast4x** [comment]
same for Fixed
