### ISSUE TITLE
Enhance Music Library Organization with the Archive Feature

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#858]
### Describtion

This unique feature aims to enhance the organization of personal music libraries. The Archive would appear as a new tab in the sidebar menu, addressing a common issue faced by many users: navigating through the library often leads to encountering old artists, albums, songs or playlists that are rarely listened to. This surplus of music clutters the collection, making it challenging to maintain clarity and overview. The Archive function allows users to hide these items without deleting them, preserving memories. By providing an option in the context menu, users can archive artists, albums, songs, or playlists. The Archive, accessible via the sidebar menu, follows a similar structure to the main app control (sidebar menu). It enables users to play music or add it to playlists, while separating its accessibility from the main library area, thus ensuring better organization and overview.

### Suggested Solution

• Introduce a new "Archive" tab in the sidebar menu of the music player app.

• Allow users to select items (artists, albums, songs, or playlists) and archive them from the context menu.

• Ensure that archived items are not deleted but hidden from the main library view, preserving user data and memories.

• Design the Archive tab with a similar structure to the main app control (sidebar menu), allowing users to navigate and interact with archived items easily.

• Provide options within the Archive tab to play archived music or add it to playlists.

**Comment by fast4x** [comment]
Too impactful

**Comment by dAtA-TRoN** [comment]
Thank you for the clear answer. I had already suspected as much.
