### ISSUE TITLE
Adding New Releases Tab in Home

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#861]
### Description

Adding New Releases Tab in Home so that we can quickly see whats new in the market..

### Suggested Solution

adding new Releases tab below quick picks, 
specially one for new albums released & one tab for trending songs.

like this one: 
![Screenshot_20240226-224651](https://github.com/fast4x/RiMusic/assets/136909951/2fc1bd5d-1513-447d-a604-b20e025d3f05)

**Comment by fast4x** [comment]
New from preferred artists is just in home...

**Comment by fast4x** [comment]
Maybe you mean unifying the  Discovery with Quick Pips tab?

**Comment by Vishcot** [comment]
> Maybe you mean unifying the  Discovery with Quick Pips tab?

i am talking about the discovery of new releases as mentioned above..like which new songs are trending this week by region & new albums which are just launched ( also region specific)

 ![Screenshot_20240226-224651.png](https://github.com/fast4x/RiMusic/assets/136909951/448061f6-9912-4e5e-ab38-8b75c26963fb)

**Comment by fast4x** [comment]
The home already has many functions, this weighs a lot.
