### ISSUE TITLE
Re-designing Search bar 

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#862]
### Description

Re-designing Search bar as current one looks very much odd 

### Suggested Solution

Search bar like this: 
![Screenshot_20240226-225304](https://github.com/fast4x/RiMusic/assets/136909951/37b66267-e28c-42e9-97df-d7db7e92acc6)

rather than this :
![Screenshot_20240226-224932](https://github.com/fast4x/RiMusic/assets/136909951/0e2c25df-d2c6-4115-bb32-381f087b5e71)

**Comment by fast4x** [comment]
Improved, available from version 0.6.24
