### ISSUE TITLE
Crashes on play/startup

### ISSUE THREAD

**Issue by QLegare** [fast4x/RiMusic#863]
### Steps to reproduce the bug

-If app is open in background re-opening it will crash it
-pause using external device (ie. Bluetooth headset or car stereo), when you press play whether on phone or external device it will crash

### Expected behavior

-app will reload last open page and song from cache or open fresh on home page
-play music previously paused

### Actual behavior

-App opens briefly and crashes a second later, on re-open works perfectly fine

-app crashes and current song disappears on re-open

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/161372159/19a4c62d-e41b-4f89-b1d2-fd485996bc4c

### RiMusic version

0.6.22

### Android version

Android 14

### Additional information

Galaxy s21 5g

**Comment by QLegare** [comment]
There seems to be a time delay with the background issue I haven't seemed to figure out how to duplicate. I'm not sure if it's random, or happens after a certain number of other apps are open or whether it's after a certain amount of time

**Comment by fast4x** [comment]
enable invincible service and battery optimization in settings tab miscellaneous
