### ISSUE TITLE
Most listened songs doesn't work

### ISSUE THREAD

**Issue by Timotit** [fast4x/RiMusic#864]
### Steps to reproduce the bug

1. Listen to a few songs
2. Check the most listened songs
3. Only the songs I listened to today show up

### Expected behavior

It should save every song I've listened to

### Actual behavior

Only shows songs that I listened to today

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/127035886/a8d462c4-ea09-417f-a2fd-4da0ee75e775

### RiMusic version

0.6.23

### Android version

Android 13

**Comment by fast4x** [comment]
I  thing it's been fixed, available from version 0.6.24

**Comment by fast4x** [comment]
Im sorry but i don't have any minimal idea other then.
