### ISSUE TITLE
scrub through a song via lyrics doesn't work

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#865]
### Steps to reproduce the bug

Open up lyrics on player and tap on the non highlighted part of the synced lyrics

### Expected behavior

Song should go to that time

### Actual behavior

Does nothing

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/89296867/d2ac42cd-5937-4005-8c71-54be8332b9e3

### RiMusic version

0.6.23

### Android version

Android 14

**Comment by VINULA2007** [comment]
@fast4x could you add a toggle to turn that "improvement" on and off
Plz

**Comment by fast4x** [comment]
Implemented, enable/disable in player appearance settings Player/Fullscreen/Both
Available from version 0.6.28.1
