### ISSUE TITLE
persistent queue ain't working 

### ISSUE THREAD

**Issue by VINULA2007** [fast4x/RiMusic#866]
### Steps to reproduce the bug

1. Turn on persistent queue
2. Play a song and pause it
3. Go to recents menu and remove it
4. Go back to the app

### Expected behavior

Should keep the last played song 

### Actual behavior

Don't keep the last played song

### RiMusic version

0.6.23

### Android version

Android 14

**Comment by VINULA2007** [comment]
https://github.com/fast4x/RiMusic/assets/89296867/44dc1589-5644-459c-994d-c46053c82d61

**Comment by fast4x** [comment]
Fixed, available from version 0.6.24
