### ISSUE TITLE
I would like to help be a translator for the Rimsuic application I speak Spanish 

### ISSUE THREAD

**Issue by Theangelmartinez13** [fast4x/RiMusic#867]
### Description

I would like to help be a translator for the Rimsuic application I speak Spanish 

### Suggested Solution

I would like to help be a translator for the Rimsuic application I speak Spanish 

### Alternatives

I would like to help be a translator for the Rimsuic application I speak Spanish 

### Additional Context

I would like to help be a translator for the Rimsuic application I speak Spanish

**Comment by fast4x** [comment]
Hi thanks, go to Crowdin abd translate https://crowdin.com/project/rimusic/invite?h=73f0e6b64be1c64a8aebd467d286cf851925330
