### ISSUE TITLE
Material theme when? 

### ISSUE THREAD

**Issue by Ichiro786** [fast4x/RiMusic#868]
### Description

Would love to see Material U theme, the app is already perfect and its is beautiful and it's ui is also Smooth and good.

**Comment by fast4x** [comment]
I haven't idea...

**Comment by Ichiro786** [comment]
> It's already here. However, the app takes a different, more playful approach: the coloring doesn't correspond to your launcher's background image, but to the album art of the track you're currently playing.
> 
> Settings > UI > Theme > Dynamic
> 
> ![IMG_20240227_172708.jpg](https://github.com/fast4x/RiMusic/assets/71184627/f99764d8-935b-4dc7-86c7-4a80a9046bad)
> 
> 

Yep I know that and tried it aswell but the dynamic theme doesn't support amoled and I wish it could also respond to background image

**Comment by Ichiro786** [comment]
> I haven't idea...

Ooh.. it's okay and btw here are some ui tweaks that I made -
![Untitled180_20240227194227.png](https://github.com/fast4x/RiMusic/assets/158778170/da7b5333-106a-4ac8-bf2d-d23130760b12)

![Untitled179_20240227185912.png](https://github.com/fast4x/RiMusic/assets/158778170/4063c308-935b-4932-8899-653e2bcea292)

You can compare them with the current one and I think these will be more like minimalistic

**Comment by fast4x** [comment]
But the first one lacks titles

**Comment by Ichiro786** [comment]
> But the first one lacks titles

Yep.. ur right but u can make the changes what u think fits there like the search in quick pics currently is at the top and it takes time to reach there (I'm lazy) and if there's a search button in bottom (like mine) it would be more reachable.. and btw why don't u make a discord server of Rimusic ? It would be easy to talk there.

**Comment by fast4x** [comment]
Last version have search tab to bottom left, if you want float search icon, you can switch to ViMusic ui mode in the settings.
Discord is egual to use discussion section in project.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.30

**Comment by fast4x** [comment]
![giphy (7)](https://github.com/fast4x/RiMusic/assets/1484476/7853e6de-0b33-4901-b5a5-c6c39120be2c)
