### ISSUE TITLE
Crash / UI scrolling not smooth

### ISSUE THREAD

**Issue by Gulubabu1** [fast4x/RiMusic#869]
### Steps to reproduce the bug

This app some time crash and app UI scrolling not smooth.

### Expected behavior

Smooth perform

### Actual behavior

Need more stable and fix the issue , soon need update please because love this app

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/127394019/a715f87f-363d-4374-b0e1-1d64ee9c7cb9

### Logs

Need more stable and fix the issue , soon need update please because love this app

### RiMusic version

0.6.23

### Android version

Android version 9 and 12

### Additional information

Need more stable and fix the issue , soon need update please because love this app.
         Please fix the problem and provide a update soon.

**Comment by fast4x** [comment]
Do yiu habe enabled invincible service and battery optimization in miscellaneous/other settings?
