### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by DeadSecTr** [fast4x/RiMusic#871]
### Steps to reproduce the bug

Just use it and see...

### Expected behavior

Please remove the unnecessary frills from this great app and let it be what it once was."

### Actual behavior

unusable

### RiMusic version

last

### Android version

13

### Additional information

RiMusic was a really good music app before 3-4 updates ago..because it really focused on listening to music and it was on "Point"

And not like now, at the moment, stuffed with unnecessary features and adjustments that nobody needs!

That's why it's become so unreliable lately and crashes regularly...

What's definitely missing... is a synchronization function with Piped! 
It would make it much easier for users who want to switch to Rimusic or vice versa...

I've recently started using Harmony Music, which I really like because it supports Piped sync and only has the essential settings/functions that a music player/streamer needs!

I appreciate the effort put into this work a lot. I know it took a lot of work and time to code it... but please, developer, don't implement everything that is desired, as it deviates from what RiMusic was intended to be or was.

This is my personal opinion and experience report...

**Comment by ikanakova** [comment]
I think this belongs in the discussion rather than here where you put it too, so this issue can be closed.

**Comment by fast4x** [comment]
Thank you, but I would like to point out that your judge is a little exaggerated. It all boils down to the fact that Piped doesn’t sync...

**Comment by dAtA-TRoN** [comment]
Certainly, here's a refined version in English:

I'd like to take a moment to commend the developer. Frankly, I fail to see the validity of the criticisms. In my opinion, RiMusic is nothing short of brilliant. Previously, I relied on ViMusic and had hoped for an alternative. With ViMusic stagnant for over a year and bugs becoming increasingly prevalent, RiMusic has been a breath of fresh air for me. Its consistent updates and bug fixes are greatly appreciated. Moreover, how can one complain about too many features? No one is obligated to utilize them all. I can only urge the developer to persist in their current trajectory. RiMusic remains my most frequently used app. Keep up the outstanding work!

**Comment by fast4x** [comment]
> I'd like to take a moment to commend the developer. Frankly, I fail to see the validity of the criticisms. In my opinion, RiMusic is nothing short of brilliant. Previously, I relied on ViMusic and had hoped for an alternative. With ViMusic stagnant for over a year and bugs becoming increasingly prevalent, RiMusic has been a breath of fresh air for me. Its consistent updates and bug fixes are greatly appreciated. Moreover, how can one complain about too many features? No one is obligated to utilize them all. I can only urge the developer to persist in their current trajectory. RiMusic remains my most frequently used app. Keep up the outstanding work!

Honored, thank you very much.

**Comment by ikanakova** [comment]
> I'd like to take a moment to commend the developer. Frankly, I fail to see the validity of the criticisms. In my opinion, RiMusic is nothing short of brilliant. Previously, I relied on ViMusic and had hoped for an alternative. With ViMusic stagnant for over a year and bugs becoming increasingly prevalent, RiMusic has been a breath of fresh air for me. Its consistent updates and bug fixes are greatly appreciated. Moreover, how can one complain about too many features? No one is obligated to utilize them all. I can only urge the developer to persist in their current trajectory. RiMusic remains my most frequently used app. Keep up the outstanding work!

Beautifully written and I agree 100% with everything.
