### ISSUE TITLE
Custom Feature - Standard duration of seconds between songs

### ISSUE THREAD

**Issue by Snehaasree** [fast4x/RiMusic#875]
### Description

Pls add a feature where a **certain amount of seconds** can be set between songs. For instance in a playlist of 10 songs each song would play after a gap of 4-6 seconds.

### Suggested Solution

This feature can be placed in the 3 dot option of the playlist where one can set the duration of seconds (from 1-6) that one wants between the current song and the next song

**Comment by Snehaasree** [comment]
Well, the *outro* of some songs are not gradually *reduced to silence* at
its end. The song ends at the last second of the timeline bar and
immediately the next track starts playing. This transition between songs
feels like one overlapping the other and sounds ugly.

This is just a personal preference...if you could add this feature it would
be much appreciated.

**Comment by fast4x** [comment]
Thanks for the explanation. But if it was present in the player you could set it when you want and not only in the playlist. What do you think?

**Comment by Snehaasree** [comment]
Yes that would definitely be a better option for me!

**Comment by fast4x** [comment]
Implemented, available from version 0.6.25

**Comment by Snehaasree** [comment]
Thank you for implementing this feature!
