### ISSUE TITLE
Add Playlist Export

### ISSUE THREAD

**Issue by BitBlockv6** [fast4x/RiMusic#878]
### Description

I use the app on many devices with sadly different playlists and it would be great to Export the playlists so i can merge the playlists myself and sync them. If its possible to save a  playlist on youtube-music it would be the easiest way to stay in sync with multiple devices dont know if its possible. 

I want to say thank you for that great app i found a lot of new great music and the UI and extra settings are great too.
Keep up the great work. 

### Suggested Solution

Sync Playlists with in-app function Not just the .db Export or an account based solution.

**Comment by fast4x** [comment]
This feature is just implemented in next version 0.6.24
