### ISSUE TITLE
Change placement of "Change Title" button

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#879]
### Description

I believe this button is not that much needed. So it having a distinct button doesn't seem good to me.

### Suggested Solution

I think it should be placed somewhere there:

![1709236385297](https://github.com/fast4x/RiMusic/assets/85461823/2441fb76-2d80-4358-b0e1-18581efb4ef5)

### Additional Context

Also I think "Equalizer" shouldn't have a button here as well. Equalizer should only exist in the settings. It's just my personal opinion anyway.

**Comment by dAtA-TRoN** [comment]
Why would one even need this button? What's the purpose of changing song titles for streamed music? It makes sense for local files, but otherwise? Nonetheless, I agree; I think the suggestion is definitely a good one.

**Comment by fast4x** [comment]
Without a button how do you close equalizer temporarily while being active in the settings?

**Comment by fast4x** [comment]
Yes it's needed, in the future i think to improve equalizer.
