### ISSUE TITLE
Streamlined Copy Functionality for Song Lyrics

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#883]
### Description

Currently, the process of copying song lyrics within the app is somewhat cumbersome. Users typically must navigate to the "Edit Lyrics" button, then access the context menu by tapping and holding the text for a short duration, followed by selecting "Select All" and then "Copy". This workflow could be streamlined by introducing a direct copy button for song lyrics.

### Suggested Solution

A new button, positioned below the "Edit Lyrics" button, could enable users to copy song lyrics with a single tap. This solution would significantly enhance user experience and save time, especially for those who frequently extract lyrics from the app.

![1709264746035](https://github.com/fast4x/RiMusic/assets/71184627/8c091952-d959-42d9-8c17-ec7cc695874a)

The provided mockup serves just as a general reference for where this feature could be integrated. However, alternative suggestions for placement are welcome.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.24

**Comment by dAtA-TRoN** [comment]
> Implemented, available from version 0.6.24

Okay, now you're really showing off, aren't you 😏?

**Comment by fast4x** [comment]
Yes, I’m always the same 💯
