### ISSUE TITLE
Custom Playlist Cover Images

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#884]
### Description

Previously, RiMusic automatically generated a collage using the covers of four different albums within a playlist. With this new feature, users can now add a personalized touch by selecting their own custom cover image for their playlists.

![IMG_20240301_115450](https://github.com/fast4x/RiMusic/assets/71184627/374a03e6-951a-419e-884b-5b6cbb5ea227)

### Suggested Solution

To access this feature, users can simply tap on the three-dot menu within the playlist and select "Choose Custom Cover" from the context menu.

Of course, that's just an example. Others likely have a better understanding of how and where to implement such things than I do.

**Comment by ikanakova** [comment]
I think it could be handled similarly to albums - entering the url of the cover.

**Comment by dAtA-TRoN** [comment]
> I think it could be handled similarly to albums - entering the url of the cover.

I would prefer to have a feature enabling the upload of images from the local image gallery. This would allow us to generate beautiful images using AI, akin to what I've already done for the mockup, to use as cover pages.

**Comment by ikanakova** [comment]
> > I think it could be handled similarly to albums - entering the url of the cover.
> 
> I would prefer to have a feature enabling the upload of images from the local image gallery. This would allow us to generate beautiful images using AI, akin to what I've already done for the mockup, to use as cover pages.

I agree with creating your own images (even without using AI, after all I prefer to rely on my intelligence 😀 ) but for transferability between devices a link would be better. You could always use https://imgbb.com/ your own website etc.

**Comment by dAtA-TRoN** [comment]
> I agree with creating your own images (even without using AI, after all I prefer to rely on my intelligence 😀 ) but for transferability between devices a link would be better. You could always use https://imgbb.com/ your own website etc.

I have no clue about the technical execution. I'm just the arrogantly spoiled user who tends to make overly unrealistic demands 😅👀...

**Comment by cMattw** [comment]
![Screenshot_2024-03-23-15-06-45-231_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/160244930/f09d9bd4-60e3-4e8a-9022-6c99a1980118)

or it could apply cover image directly from YouTube music, since it already fetches the image (just at a very low resolution)

**Comment by dAtA-TRoN** [comment]
> or it could apply cover image directly from YouTube music, since it already fetches the image (just at a very low resolution)

What do you exactly mean by that 🤔?

**Comment by cMattw** [comment]
> > or it could apply cover image directly from YouTube music, since it already fetches the image (just at a very low resolution)
> 
> What do you exactly mean by that 🤔?

like, if a playlist has a cover art on youtube music. The app should apply the cover art automatically when you import it to your playlist

**Comment by dAtA-TRoN** [comment]
> like, if a playlist has a cover art on youtube music. The app should apply the cover art automatically when you import it to your playlist

Sounds nice, as long as it can also be exchanged manually.
