### ISSUE TITLE
Suggest saving a full album on the download section please 

### ISSUE THREAD

**Issue by Azzman1984** [fast4x/RiMusic#885]
### Description

Hello here can I suggest bookmarking a downloaded album for offline use and put it on the library section please

### Suggested Solution

Here's the album I downloaded 

![Screenshot_20240301_113247](https://github.com/fast4x/RiMusic/assets/150800081/bb272240-3046-4dc8-8714-03109f514839)

And here's a screenshot of what I think full bookmark for offline use full album should be.. that this section

![Screenshot_20240301_113426](https://github.com/fast4x/RiMusic/assets/150800081/adb46362-0140-4118-99e6-f37e0aca8798)

**Comment by ikanakova** [comment]
Library is for playlists and even downloaded songs / favourites is a playlist in a way. I think putting a bunch of other stuff in there already could start to get confusing.

**Comment by fast4x** [comment]
Is the same action if bookmark album and click on download all. You can find album with full downloaded songs in albums tab.
