### ISSUE TITLE
Make sure the songs on the playlist r in the right order

### ISSUE THREAD

**Issue by Azzman1984** [fast4x/RiMusic#886]
### Description

Hello there, I put a playlist so I could download for offline use so I could download and listen but the songs r not in the proper right order as it suppose to be

Here's a screenshot of the album
![Screenshot_20240301_112240](https://github.com/fast4x/RiMusic/assets/150800081/587ec074-1764-4c79-9c0a-08eec621655f)

And here's a screenshot of the playlist but the songs r not in the right order as they suppose to
![Screenshot_20240301_112312](https://github.com/fast4x/RiMusic/assets/150800081/1ecbb35e-84ba-4620-81d7-b3ceaedb4f2d)

### Suggested Solution

I would like it when u add a full album, song or EP to a playlist then it would play the playlist in the right proper order as it suppose to be

**Comment by ikanakova** [comment]
You have to change the order from Title ↓ to Position ↑

**Comment by ikanakova** [comment]
@Azzman1984 You can also move and renumber the tracks to sort them to your liking.
I think if it works as it should. Can this issue be closed.
