### ISSUE TITLE
Cool Android TV Design

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#887]
### Description

I was at a barber and seen a TV with a player like this:
![20240301_155445](https://github.com/fast4x/RiMusic/assets/104271365/51856bd5-4d8c-433b-8422-76732148ae33)

I liked the way next songs are shown and i think it would look good on tv and on cars

### Suggested Solution

Add something similar to the screenshot for TV android auto and Horizontal phones as an option

**Comment by fast4x** [comment]
Great! LOL I like your approach

**Comment by dAtA-TRoN** [comment]
Hahaha, what a totally unexpected response! I was certain he'd start grumbling by now, given how complex the task appeared to me 😁.

**Comment by fast4x** [comment]
> Hahaha, what a totally unexpected response! I was certain he'd start grumbling by now, given how complex the task appeared to me 😁.

It’s not easy, I can’t develop it soon.
