### ISSUE TITLE
[Feature]: RiMusic UI Concept V2

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#89]
### Description

This is a updated version for my [RiMusic UI Concept V1](https://github.com/fast4x/RiMusic/issues/50#issue-1966673023) with new and improved ideas.

Player:
![image](https://github.com/fast4x/RiMusic/assets/104271365/29ad4f8a-8dab-4678-b12a-9354e7e1c48c)
Player menu:
![image](https://github.com/fast4x/RiMusic/assets/104271365/d6b5e864-3bc3-4761-89ee-b9d991e04ba8)
Songs list:
![image](https://github.com/fast4x/RiMusic/assets/104271365/8c4d3f19-1708-46fb-b757-c50ca465f43f)

### [Part 2](https://github.com/fast4x/RiMusic/issues/89#issuecomment-1807933641)
~~More coming soon ( Quick Pics, Playlist, Search, etc... )~~

Where i got my ideas?
- [RiMusic UI Concept V1](https://github.com/fast4x/RiMusic/issues/50#issue-1966673023)
- [ViMusic](https://github.com/vfsfitvnm/ViMusic)
- [YouTube Music](https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.music&hl=fr&gl=US)
- [Android 14 Player Concept](https://github.com/fast4x/RiMusic/discussions/70#discussioncomment-7474987)

Font:
Since i used [Paint.net](https://getpaint.net/) to edit screenshot from RiMusic, ViMusic, YTMusic there are multiple fonts but i choose [Rubik](https://fonts.google.com/specimen/Rubik) for the font because it is simple and clean

If there are mistakes or better ideas dont hesitate to tell me!
Also fore more informations look at "Suggested Solution" or ask me!

### Suggested Solution

What I've changed compared to the [RiMusic UI Concept V1](https://github.com/fast4x/RiMusic/issues/50#issue-1966673023):

Player:
- I added an arrow on the top to close the player
- I used the ViMusic album cover since it takes less space ( It looks cleaner )
- I removed the "Now Playing" ( It looks cleaner )
- I've made the "Artist" a bit less BIG and used a slightly les White color to différenciante from the name of the song ( It looks cleaner )
- I added the hearth button and download button next to the song informations ( Idea took from [Android 14 Player Concept](https://github.com/fast4x/RiMusic/discussions/70#discussioncomment-7474987) )
- I've made the seekbar less long ( It looks better and prevent moving the finger all the way on the screen )
- I used the same buttons style as the [Android 14 Player Concept](https://github.com/fast4x/RiMusic/discussions/70#discussioncomment-7474987)
- I added a line to the bottom bar to indicate that you can drag it up and made it rounder ( Idea took from [YouTube Music](https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.music&hl=fr&gl=US) )
- Added the artist from the next song
- Removed the "Repeat playing" button and added in the "Song list"

Player menu:
- Like the player i added "Download song" next to like and made them centered 
- I added a line to the menu to indicate that you can drag it down and made it rounder ( Idea took from [YouTube Music](https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.music&hl=fr&gl=US) )
- Rearranged the buttons ( "Go to Album, etc..." ) ( It makes more sense to me )

Music list:
- Made the list not open all the way up for more reachability ( It can open all the way up if we slide up a second time )
- I added a line to the list to indicate that you can drag it up or down and made it rounder ( Idea took from [YouTube Music](https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.music&hl=fr&gl=US) )
- I added the like and downloaded indicators ( only visual not clickable ) they show if the song is liked / downloaded
- I replaced the "Randomise" floating button with a floating menu that includes "Randomise" and "Repeat playing" buttons
- The "Lock" button stays in the bottom bar

### Additional Context

Other important Information and ideas:
- In the bottom bar of the "Player" the text ( witch is in red ) should not be clickable because it can prevent users from opening the "Songs list"
![image](https://github.com/fast4x/RiMusic/assets/104271365/883a531a-feca-4ca4-bbba-98d5221ff32a)
- If the song name is too long the text should scroll slowly ( Idea from a [friend](https://github.com/NEVARLeVrai) )

**Comment by NEVARLeVrai** [comment]
🤓👍

**Comment by senolfndk** [comment]
Ok man, this interface looks very stylish. 😍👌

**Comment by senolfndk** [comment]
You can do this

**Comment by dainvincible1** [comment]
this looks very goood 👌

**Comment by OrangeZXZ** [comment]
> If you want some special icons, I'll make them if it's not too complicated. Especially the downloaded cache icon we should definitely come up with something else.

Since I just used screenshots and conected them like legos i d'idint changed icons or font but i could add the icons if I have them in png or jpeg format

**Comment by fast4x** [comment]
So, if I understand correctly, everyone likes it! 😋☺️😂

**Comment by ikanakova** [comment]
> Since I just used screenshots and conected them like legos i d'idint changed icons or font but i could add the icons if I have them in png or jpeg format

That would be fine. But it would be great if they were similar to [ionicons](https://ionic.io/ionicons) or other foss icon pack (if we stop using ionicons completely) and I just reworked them a bit - I don't dare to do big modifications to svg.

**Comment by fast4x** [comment]
I would keep the ionicons icons.

**Comment by ikanakova** [comment]
I thought the download (cache) icon might be like this:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/6dbe610b-7f83-4fdc-b75b-fa520ce19701" width="10%">

**Comment by fast4x** [comment]
I don’t like it much...

**Comment by ikanakova** [comment]
> I don’t like it much...

OK, I can't think of anything else yet. Maybe somebody can suggest something. But I don't think it should look exactly like the download icon.

**Comment by fast4x** [comment]
> > I don’t like it much...
> 
> OK, I can't think of anything else yet. Maybe somebody can suggest something. But I don't think it should look exactly like the download icon.

we can test it and see the effect it does

**Comment by fast4x** [comment]
> > I don’t like it much...
> 
> OK, I can't think of anything else yet. Maybe somebody can suggest something. But I don't think it should look exactly like the download icon.

it seems more for a PC software than for a multimedia app

**Comment by ikanakova** [comment]
I also created an equalizer icon when @OrangeZXZ has it in the design:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/d444e8f5-65f8-4d83-a5bf-f4cbf940cfc6" width="10%">
And as another option:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/a7315bd8-1504-4e49-8d3b-db105cd7b943" width="10%">

**Comment by ikanakova** [comment]
> > > I don’t like it much...
> > 
> > 
> > OK, I can't think of anything else yet. Maybe somebody can suggest something. But I don't think it should look exactly like the download icon.
> 
> it seems more for a PC software than for a multimedia app

I was inspired by this [icon](https://wordpress.org/plugins/aruba-hispeed-cache/).

**Comment by senolfndk** [comment]
![Screenshot_20231108-012559_AIMP.jpg](https://github.com/fast4x/RiMusic/assets/52818836/2ce2dc02-ab45-4733-b474-c4144b355169)

**Comment by ikanakova** [comment]
> ![Screenshot_20231108-012559_AIMP.jpg](https://user-images.githubusercontent.com/52818836/281199600-2ce2dc02-ab45-4733-b474-c4144b355169.jpg)

Could you describe it more? If it's a design you created yourself like @OrangeZXZ or an app you like? But in that case it would be good to write what you specifically like, because to prevent RiMusic from becoming a copy of another app.

The suggestion of @OrangeZXZ is great not only in the idea, but also in the way he described his idea nicely.

**Comment by senolfndk** [comment]
> > ![Screenshot_20231108-012559_AIMP.jpg](https://user-images.githubusercontent.com/52818836/281199600-2ce2dc02-ab45-4733-b474-c4144b355169.jpg)
> 
> Daha fazla tarif edebilir misiniz? Eğer bu kendi yarattığınız bir tasarımsa@OrangeZXZveya beğendiğiniz bir uygulama? Ancak bu durumda, RiMusic'in başka bir uygulamanın kopyası olmasını önlemek için özellikle neyi beğendiğinizi yazmanız iyi olacaktır.
> 
> Önerisi@OrangeZXZsadece fikri açısından değil, aynı zamanda fikrini güzelce anlatması açısından da harika.

Just an idea
![281199600-2ce2dc02-ab45-4733-b474-c4144b355169](https://github.com/fast4x/RiMusic/assets/52818836/bccdedb2-cb13-4ca1-a9d0-fac09a6b6ca8)

**Comment by OrangeZXZ** [comment]
### Part 2

Playlists:
![image](https://github.com/fast4x/RiMusic/assets/104271365/0f859232-19a1-42ea-bda2-dea452048952)
Quick picks:
![image](https://github.com/fast4x/RiMusic/assets/104271365/0080aba1-3b3f-4e89-a89a-7abd90c928d0)
Search:
![image](https://github.com/fast4x/RiMusic/assets/104271365/9d67ead6-e2d6-4a6a-8e36-b7958a3df350)

If there are mistakes or better ideas dont hesitate to tell me!
Also fore more informations look at "Suggested Solution" or ask me!

### Suggested Solution

What I've changed:

Playlists:
- I added a background to the settings and statistics
- I centered the sidebar on the top and made the selected category bigger
- I centered and added a background for the Playlists rearrangement buttons
- I centered the Playlists and added a big New Playlist Button
- I added a line to the bottom bar to indicate that you can pull up
- I added the same 3 player buttons in the bottom bar

Quick picks:
- I added a background to the settings and statistics
- I centered the sidebar on the top and made the selected category bigger
- I added a line to the bottom bar to indicate that you can pull up
- I added the same 3 player buttons in the bottom bar

Search:
- I added a background to the back button
- I centered the sidebar on the top and made the selected category bigger
- i centered the searches
- I added a line to the bottom bar to indicate that you can pull up
- I added the same 3 player buttons in the bottom bar

### Additional Context

The new UI is already very good!
I think now instead of making Concept Part 3 Il make little UI Improvements for already existing things and post all my opinions in part 3.

**Comment by dainvincible1** [comment]
looks beautiful 👍

**Comment by fast4x** [comment]
Changed default font to Rubik, available from version 0.6.15

**Comment by senolfndk** [comment]
progress bar ![Screenshot_20231228-142232_AIMP.jpg](https://github.com/fast4x/RiMusic/assets/52818836/a598618a-526e-42f1-bdd5-97ddfe23bb92)

**Comment by senolfndk** [comment]
![Ekran görüntüsü 2023-12-28 141826](https://github.com/fast4x/RiMusic/assets/52818836/93294f86-7bb7-446f-b83f-2d67b4b09880)

**Comment by senolfndk** [comment]
Theme options ![Screenshot_20240106-221942_VK X.jpg](https://github.com/fast4x/RiMusic/assets/52818836/1d5f769e-e03a-4a9b-b6a8-49aeca541b29)

![Screenshot_20240106-222055_VK X.jpg](https://github.com/fast4x/RiMusic/assets/52818836/a56fb41e-66e8-425e-a753-266b35a652e3)

![Screenshot_20240106-221834_VK X.jpg](https://github.com/fast4x/RiMusic/assets/52818836/160f0637-30c8-4cba-a3da-c552af5227d1)

**Comment by OrangeZXZ** [comment]
> Theme options

Yeah 2 colors fade option for the Dinamic theme would be nice

**Comment by senolfndk** [comment]
![Screenshot_20240106-223026_VK X.jpg](https://github.com/fast4x/RiMusic/assets/52818836/00adbdc7-9c45-4067-b590-1accfeb16ead)

![Screenshot_20240106-223051_VK X.jpg](https://github.com/fast4x/RiMusic/assets/52818836/9b857ca5-4a3b-4d16-813d-c54f95b1b1b3)

**Comment by senolfndk** [comment]
https://github.com/fast4x/RiMusic/assets/52818836/0f6cc488-ab4b-4f74-865a-cd2bc6c42f1f

**Comment by senolfndk** [comment]
https://github.com/fast4x/RiMusic/assets/52818836/180d150c-f2ad-483f-95ea-c622a48a19fe

**Comment by senolfndk** [comment]
![20240106_231517](https://github.com/fast4x/RiMusic/assets/52818836/cc3932b4-c9bc-4f0f-aae1-d6657ad2ae12)

**Comment by senolfndk** [comment]
![20240108_222642.jpg](https://github.com/fast4x/RiMusic/assets/52818836/312fb1e1-7567-4b57-9c03-68f707db5e28)

player button background 🤔

**Comment by senolfndk** [comment]
![20240108_222642.jpg](https://github.com/fast4x/RiMusic/assets/52818836/312fb1e1-7567-4b57-9c03-68f707db5e28)

player button background 🤔

**Comment by OrangeZXZ** [comment]
> player button background 🤔

Yeah this is an error to patch

**Comment by senolfndk** [comment]
![Screenshot_20240109-231110_AIMP.jpg](https://github.com/fast4x/RiMusic/assets/52818836/9f4e7b32-7cc0-4f3c-971f-3962108b3bb3)

**Comment by fast4x** [comment]
I close this why we can use discussion
