### ISSUE TITLE
Swipe haptic feedback!

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#890]
### Description

Loved this Swipe-Song Feature, it made so much easy to add and remove songs! just a one more improvement, can you add a very minimal haptic feedback, as swipe feels very slippery. with haptic makes it will act more reliable and promising, ( it works like you are about to do an action - CAUTION ⚠️ ! ) 

### Suggested Solution

same as above..

![Screenshot_20240302-023909.png](https://github.com/fast4x/RiMusic/assets/136909951/717f3615-c998-424d-8d6e-546004213e48)

**Comment by Vishcot** [comment]
and if possible @fast4x , 
please consider these three more changes :

1.put a condition of swiping one song at a time! 
i mean, Only one song at a time can be swiped either right or left..
( no multiple songs at a time ) 
as seen in the above screenshot.


2. adding same swipe gestures into search results as well if possible! 

and,
3. will be again what i started this feature request with..
haptic for these gestures ( only if somehow possible and doesn't requires alot of efforts! ) 

thanks 🙏🏻 🙏🏻

**Comment by fast4x** [comment]
I'll implement new swipe action menu with other effect.

**Comment by Vishcot** [comment]
> I'll implement new swipe action menu with other effect.

i don't get you, new action menu ?

**Comment by fast4x** [comment]
Yes, I think to add new swiping effects

**Comment by Vishcot** [comment]
Hi dev, did you find any solution on haptics or the new kind of swiping gestures you were talking about? 
Because if you're not planning to implement this, i have bug.
Actually for me to play next, doesn't work at all..see this:

**Comment by Vishcot** [comment]
https://github.com/fast4x/RiMusic/assets/136909951/20979baa-f57f-4261-b30d-b323d7616505

**Comment by fast4x** [comment]
Hi, but what's the bug?

**Comment by Vishcot** [comment]
Also the same issue is with the favourite icon: 
After clicking favourite button, it doesn't add into the favourites library..
Expected behaviour: after clicking that heart ❤️ icon, song should be added into favorite library, but for some songs it is not getting added! 

https://github.com/fast4x/RiMusic/assets/136909951/0f0750e3-4c4a-4519-ab11-ee87c71db5ac

**Comment by fast4x** [comment]
try this, add like, exit from favourites, re enter, it show?

**Comment by Vishcot** [comment]
> try this, add like, exit from favourites, re enter, it show? 

Nope, i even tried app close..
It shows, but you can't guess when, 
Even force closing app / clearing cache doesn't make it show. It randomly comes after some here and there swipes and song changes..and not for all songs..
Only a few specific videos and music i have encountered this issue with.

**Comment by Vishcot** [comment]
> I'll implement new swipe action menu with other effect.

Hi, @fast4x any update on this as well? 
Can we expect that it is going to be implemented soon?

**Comment by fast4x** [comment]
Implemented swipe and haptic feedback, available from version 0.6.42
