### ISSUE TITLE
A list of UI Inconsistancies

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#892]
# Inconsistencies:
- [x] I don't know what you call them, but take a look in ss, All icons looks same
- [x] If no song is present _(as in ss)_, Those headings should not be present, they do not look good
<img src="https://github.com/fast4x/RiMusic/assets/78584556/f3dc8ee1-0964-4e85-a054-538e3808eb12" alt="Image" width="200">

<br>
<br>
<br>

# About
RiMusic 0.6.24
Android 14

**Comment by fast4x** [comment]
yes icon actually are all the same @ikanakova can try create a various icons for statistics?

**Comment by ikanakova** [comment]
@fast4x Sure, but I don't have my PC with me until Monday, so I won't do it until Tuesday at the earliest.

**Comment by fast4x** [comment]
Of course, when you can, I appreciate your willingness.

**Comment by fast4x** [comment]
Improved empty statistics, available from version 0.6.25

**Comment by ikanakova** [comment]
New stats icons #937

**Comment by fast4x** [comment]
Implemented, available from version 0.6.25
@ikanakova thanks

**Comment by sayyid5416** [comment]
Thanks for the fast response 😄
