### ISSUE TITLE
Feedback on Latest Update and Request for Adjustment

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#893]
### Description

Thank you for the latest update – truly great work 👏🏼🙂! I noticed something regarding the modified function with the arrow button in the player, which leads to the playlist. After opening the playlist using it, the pill icons at the top and bottom of the playlist are still visible, as shown in the attached image. These icons shouldn't be displayed once the arrow button is activated since they serve no function and are only confusing.

![IMG_20240301_204644](https://github.com/fast4x/RiMusic/assets/71184627/b3010dd2-7e30-4982-af48-eb15e5be956c)

### Suggested Solution

It would be appreciated if you could remove them in the next update, similar to the pill in the player view. Thanks in advance!

**Comment by Vishcot** [comment]
it is working as per your requirements, have a look

..![Screenshot_20240302-023512.png](https://github.com/fast4x/RiMusic/assets/136909951/45e66a5c-28ef-48ed-9d22-16612d534030)

**Comment by dAtA-TRoN** [comment]
@Vishcot I'm aware that it works, which is great. I just wanted to point out that the pill graphics should also disappear in the playlist view (see image).

**Comment by Vishcot** [comment]
> @Vishcot I'm aware that it works, which is great. I just wanted to point out that the pill graphics should also disappear in the playlist view (see image).

ohh yeah i see! thanks for the clarity! 😊

**Comment by dAtA-TRoN** [comment]
> ohh yeah i see! thanks for the clarity! 😊

You're welcome.
