### ISSUE TITLE
[Feature]: import playlists form text file

### ISSUE THREAD

**Issue by alexou2** [fast4x/RiMusic#895]
### Description

> i am currently stuck using Spotify and i want to switch to ri music. It would be great if i could just transfer my playlists and songs. 

### Suggested Solution

Add a feature to import songs and playlists from a text file containing the link to the song or its name and artist. 

### Additional Context

Yt music users could also have the option to sign in to directly import their songs.

**Comment by ikanakova** [comment]
To import from a Spotify playlist, you can use an external YouTube Music import page (e.g. Soundiiz, etc.). The Youtube Music playlist can then be easily imported into RiMusic using the url. The only condition is that playlist must be public.

> Yt music users could also have the option to sign in to directly import their songs.

There are no plans to sync directly with YouTube via login - [FAQ - Why there are no plans to implement Google or YouTube login?](https://github.com/fast4x/RiMusic/wiki/FAQs#why-there-are-no-plans-to-implement-google-or-youtube-login)

**Comment by fast4x** [comment]
Also with last version RiMusic you can create a file csv with songs info from YouTube and import in playlist. Export a RiMusic playlist for file fields format.
