### ISSUE TITLE
Correct search icon symmetry

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#898]
### Description

Search icon inside search feature are off symmetry

### Suggested Solution

Correct the position

**Comment by dAtA-TRoN** [comment]
What do you mean? Can you post a screenshot?

**Comment by faustaahmad** [comment]
@dAtA-TRoN 
![](https://github.com/fast4x/RiMusic/assets/45221211/1a03a588-606a-4062-9046-b7910ca7de23)

**Comment by dAtA-TRoN** [comment]
Strangely, it scales correctly for me:

![Screenshot_2024-03-03-05-39-24-58_91b67804b5fb3353a77fb824d6bb0b50-01.jpeg](https://github.com/fast4x/RiMusic/assets/71184627/7d15be79-3646-417c-968a-8b4d4758f2a7)

**Comment by faustaahmad** [comment]
This problem related to default system Font size
It align perfectly when I set it to Smallest (uncomfortable for me)
Search box has dynamic Height relative to font size

**Comment by fast4x** [comment]
Improved, available from version 0.6.25
