### ISSUE TITLE
Hold backspace/delete button to clear text input

### ISSUE THREAD

**Issue by faustaahmad** [fast4x/RiMusic#899]
### Description

QoL deleting search query faster
Like hold for 1s to delete all, instead of clicking clear all button which has more distance than backspace button in one hand mode

### Suggested Solution

Implement only in search query
It would be disaster if applied in lyrics as some keyboard doesnt support `undo` `redo` feature

**Comment by fast4x** [comment]
Implemented, available from version 0.6.25
