### ISSUE TITLE
Publication at F-Droid

### ISSUE THREAD

**Issue by siggi1984** [fast4x/RiMusic#9]
### Steps to reproduce the bug

You should publish your app on F-Droid to increase distribution and awareness.

### Expected behavior

If you add the piped feature and the possibility to log in to the piped account. In my opinion your app is very future proof. 

### Actual behavior

*

### RiMusic version

0.1.5

### Android version

Android 12

**Comment by fast4x** [comment]
The log in feature requires investment in a hardware infrastructure which is not currently planned. Still, it's a nice feature.

**Comment by fast4x** [comment]
Publication on f-droid is planned, thank you for your suggestion.

**Comment by fast4x** [comment]
I've started the process of publishing on FDroid

**Comment by fast4x** [comment]
Also published on F-Droid.
