### ISSUE TITLE
[Feature]: Automatic download songs or download a whole playlist

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#90]
### Description

I would like an option that downloads songs automatically instead of using the download button or maybe add a button to download a whole playlist

### Suggested Solution

option that downloads songs automatically instead of using the download button or add a button to download a whole playlist

**Comment by fast4x** [comment]
Currently the song is automatically downloaded while listening.

**Comment by ikanakova** [comment]
>> Currently the song is automatically downloaded while listening.
> 
> Maybe a way to deactivate the automatic downloads, I think that would be helpful.

I disagree, automatic downloads should definitely be retained.

**Comment by ikanakova** [comment]
> I think the user should have an option.

What I meant was that in addition to automatic downloads (streamed songs always have to be cached automatically), there should be an option to manually download songs, albums and playlists. And at the same time it would be great if it would be possible to manually delete downloaded cache = songs.

**Comment by fast4x** [comment]
> > >> Currently the song is automatically downloaded while listening.
> > > 
> > > Maybe a way to deactivate the automatic downloads, I think that would be helpful.
> > 
> > I disagree, automatic downloads should definitely be retained.
> 
> I think the user should have an option.

Yeah, it wouldn’t be bad

**Comment by fast4x** [comment]
> > I think the user should have an option.
> 
> What I meant was that in addition to automatic downloads (streamed songs always have to be cached automatically), there should be an option to manually download songs, albums and playlists. And at the same time it would be great if it would be possible to manually delete downloaded cache = songs.

This is by default, but someone might need to avoid automatic download for disk space reasons, so an option to disable it would be useful.

**Comment by fast4x** [comment]
From version 0.6.8 will be possible to enable or disable automatic download in cache.
Default it's enabled likes now.

**Comment by siggi1984** [comment]
I don't see the option or am I blind???

**Comment by fast4x** [comment]
This ticket has not been completed, it is in progress...

**Comment by siggi1984** [comment]
> This ticket has not been completed, it is in progress...

Okay no problem. I just thought I had overlooked something because the feature was announced for version 0.6.8 but as I said no problem all good I neither wait patiently.

A great app, keep it up.

**Comment by fast4x** [comment]
The download functionality is in pre-release, it will obviously be improved.

**Comment by fast4x** [comment]
Added dowload button of the entire playlist.
Available from version 0.6.10

**Comment by OrangeZXZ** [comment]
Oh yeah there is an feature about download that i had in mind and i think it's pointless to create a new issue.

In the player when the song is downloaded the bottom download icon doesn't change to tell it's downloaded

I think it would be better if the icon check if the song is downloaded sometimes and changes without needing to do something else

**Comment by fast4x** [comment]
Exactly, the operation of the next version behaves as you say.

**Comment by fast4x** [comment]
Implemented

**Comment by OrangeZXZ** [comment]
> Implemented

Could you add the button also to the Liked songs?

**Comment by fast4x** [comment]
Download of all?

**Comment by OrangeZXZ** [comment]
> Download of all?

Yeah download all the liked songs because i dont use playlists anymore
