### ISSUE TITLE
Dislike button

### ISSUE THREAD

**Issue by drybin24** [fast4x/RiMusic#900]
### Description

Ability to dislike songs/artists. 

### Suggested Solution

These songs/artists will not be played once user press the button "dislike".

In Spotify it's called "hide this song"
![IMG_20240302_032012](https://github.com/fast4x/RiMusic/assets/74720460/c307a18a-7c4f-489b-ba70-ba694fb41c38)

### Alternatives

This button has to be next to each song (maybe in the three-dot
![Screenshot_2024-03-02-03-26-08-43](https://github.com/fast4x/RiMusic/assets/74720460/b89eade5-3a65-4abb-ac76-4792a3e470e4)
 menu)

**Comment by fast4x** [comment]
is present in Songs snd Quick Pics ![Screenshot_2024-03-02-08-09-28-545_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/690fcf0a-aae9-4fe5-ac91-84dd92f79307)

**Comment by fast4x** [comment]
Implemented in preferites, downloaded and cached playlist in library, available from version 0.6.25

**Comment by fast4x** [comment]
Also added show/hide hidden songs in songs list

**Comment by drybin24** [comment]
> is present in Songs snd Quick Pics ![Screenshot_2024-03-02-08-09-28-545_it.fast4x.rimusic.jpg](https://github.com/fast4x/RiMusic/assets/1484476/690fcf0a-aae9-4fe5-ac91-84dd92f79307)
> 
> 

I assume that some tweaks have to be done in the settings in order to be able to see "hide" button, right?

I just don't see it in the Songs and Quick Picks by default

**Comment by drybin24** [comment]
https://github.com/fast4x/RiMusic/assets/74720460/d41bdaa3-8e1d-44c2-bc1e-6c3fab0a5f37
