### ISSUE TITLE
[Feature]: Configurable Dark Mode Themes with Dynamic Theme Setting

### ISSUE THREAD

**Issue by GourabMCFC** [fast4x/RiMusic#902]
### Description

Currently, when the "Dynamic Theme" option is selected and the user's device enters dark mode, the application switches to a single predefined dark background. This offers limited flexibility for users who have a preference for different shades or styles of dark backgrounds. It would be a great enhancement to allow users to choose from multiple predefined dark background options to better suit their preferences.

![SS1](https://github.com/fast4x/RiMusic/assets/113615146/2e00d7ab-f893-4205-9401-5187b1e9a9a4)

Adding the ability for users to choose their preferred dark mode background theme from a list of predefined options. This would allow users to personalize their experience.

Benefits:
**Enhanced User Experience**: Users gain more control over the look and feel of RiMusic in dark mode, leading to a more personalized experience.
**Improved Battery Life (AMOLED Screens):** A "Pure Black" theme ,already available as a standalone option, could be offered to maximize battery savings on devices with AMOLED screens.

**Desired Result**

![SS2](https://github.com/fast4x/RiMusic/assets/113615146/02f4a990-e346-4d9d-8d8b-1cf92cf218bd)

### Suggested Solution

1. Add a new setting section under "User Interface" to manage the dark mode background theme preference.
2. Create a dropdown menu or similar interface element that lists available theme options such as (Pure Black/Modern Black)
3. Store the user's selection and seamlessly apply it whenever they are in dark mode with the "Dynamic Theme" setting enabled.

![SS](https://github.com/fast4x/RiMusic/assets/113615146/17bbfefd-e039-449a-bf82-debb53a88c28)

**Comment by fast4x** [comment]
Implemented, available from version 0.6.25

**Comment by GourabMCFC** [comment]
> Implemented, available from version 0.6.25

Thank You !!!!
