### ISSUE TITLE
Sidebar Search: Redundancy Removal & Enhanced User Experience

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#905]
### Description

In the current version of RiMusic, the search function is duplicated when activated in the sidebar, leading to a cumbersome user experience. These suggestions aim to eliminate unnecessary redundant functionality and optimize the sidebar search to streamline user navigation.

![IMG_20240302_093318](https://github.com/fast4x/RiMusic/assets/71184627/122615b7-a19a-497a-b84c-d2a7cac4efd6)

### Suggested Solution

**1. Removal of Unnecessary Redundant Search Functionality:** The search function at the top of the screen should automatically hide when the sidebar search is activated. This reduces unnecessary redundancy and enhances clarity.

![IMG_20240302_101105](https://github.com/fast4x/RiMusic/assets/71184627/8162e965-3523-4c53-98a1-35c727f609a5)

**2. Redirect Sidebar Search to Search Bar Page:** Currently, sidebar search leads to an intermediary page, while top-of-screen search allows direct searching in the search bar. I propose that sidebar search adopts the same functionality as top-of-screen search. Users should be directed straight to the search bar without having to navigate through an intermediary page.

![1709371210764](https://github.com/fast4x/RiMusic/assets/71184627/b4330813-fa93-40da-8bc9-1a0f2fae9a15)

Implementing these improvement suggestions would significantly enhance the user experience when using the search function in the RiMusic sidebar.

**Comment by dAtA-TRoN** [comment]
> Or rather I'm not that good in organizing thoughts in right order.

I'm not either, thanks ChatGPT 😁.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.25

Point 2 for now isn't possible.

**Comment by Vishcot** [comment]
> Implemented, available from version 0.6.25
> 
> Point 2 for now isn't possible.

i hope someday it will be implemented, as point number 2 is so much more convenient..❤️ i also needed this style..

**Comment by fast4x** [comment]
it's the same if i add search before or after statistics icon?

**Comment by dAtA-TRoN** [comment]
> it's the same if i add search icon before or after statistics icon?

@fast4x Yes, if I understand you correctly, it would indeed be the same. The statistics icon in the sidebar also acts as a shortcut leading to an entirely different page, so it behaves differently from the other tabs, similar to how it would with the search. However, I believe the placement of the search icon at the bottom of the sidebar is important since the search function is frequently used. I hope that clarifies things regarding your question. If not, please feel free to ask again 😅.

**Comment by fast4x** [comment]
Implemented point 2 LOL available from version 0.6.25

**Comment by dAtA-TRoN** [comment]
> Implemented point 2 LOL available from version 0.6.25

For real 😱!? Hahaha that's AWESOME!! -Now I can't wait for the next update 😁.

**Comment by fast4x** [comment]
Real? Absolutely yes! i found a solution... that's all ahahaahah
