### ISSUE TITLE
Creating a New Playlist and Selecting Multiple Playlists in the Player View

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#907]
### Description

Currently in the RiMusic app, users can add songs to a playlist by tapping the "Add to Playlist" button in the player view and then selecting an existing playlist:

![Screenshot_2024-03-02-12-20-44-75_91b67804b5fb3353a77fb824d6bb0b50](https://github.com/fast4x/RiMusic/assets/71184627/bfb3b0e4-2762-47f7-bfc8-cd25d1c8a668)

However, it would be beneficial to allow users to create new playlists directly from this view. Additionally, integrating checkboxes next to the existing playlists would enable users to select multiple playlists simultaneously. This enhancement would improve user experience and streamline the music organization process. Taking cues from the YouTube app, I propose a similar functionality integration into RiMusic. Below is a screenshot illustrating the YouTube solution:

![Screenshot_2024-03-02-12-17-57-69_ee8807d2de22f1831269d80920e33a3b](https://github.com/fast4x/RiMusic/assets/71184627/54d6766c-a530-44e9-98c1-81a4673985ef)

### Suggested Solution

- Introduce a "New Playlist" button obove or below the list of existing playlists in the player view.

- Upon tapping "New Playlist," a popup window or separate view should prompt users to enter the name of the new playlist.

- Implement checkboxes next to the existing playlists to facilitate the selection of multiple playlists at once.

- After users have either created new playlists or selected existing ones, they should be able to add songs to the selected playlists by confirming their selection.

Incorporating these features into the player view would enhance user experience and make RiMusic an even more versatile music streaming platform.

**Important:**
The proposal should be aligned with the suggestion from #852 to maintain coherence within RiMusic. The suggested enhancement reads:

_"When adding a song to a playlist, a list of all playlists appears. Enhance user experience by incorporating an icon next to playlists where the song has already been added, providing quick visual confirmation."_

**Comment by fast4x** [comment]
This feature is in development and is already present in albums and playlists.

**Comment by dAtA-TRoN** [comment]
> This feature is in development and is already present in albums and playlists.

Awesome 😲!

**Comment by fast4x** [comment]
Implemented menu with playlists and new playlist.
Available from version 0.6.25

#852 for now i cannot develop it

**Comment by dAtA-TRoN** [comment]
😱 Cooool!

**Comment by dAtA-TRoN** [comment]
> Implemented menu with playlists and new playlist.
> Available from version 0.6.25

😱 Cooool!

> #852 for now i cannot develop it

It's okay, you're already doing so much!
