### ISSUE TITLE
[BUG]: Album shapes

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#91]
### Steps to reproduce the bug

Rotate phone when app open

### Expected behavior

The shapes of album should not change

### Actual behavior

Album shapes reset to none after rotate the phone, if I restart app he go back to the preset selected

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/63956787/7e8b0d3d-a5d9-4fd8-9155-2d10d2e75564

### RiMusic version

0.6.7

### Android version

A12

**Comment by NEVARLeVrai** [comment]
> Is under then scroll up...

I didn't understand

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/assets/1484476/c85b8396-e32f-42b9-89f3-210326eb867b

**Comment by NEVARLeVrai** [comment]
I put shape heavy and after rotate it goes to none that not normal ?

**Comment by fast4x** [comment]
Oh oh I didn’t quite understand

**Comment by NEVARLeVrai** [comment]
> Oh oh I didn’t quite understand

did u understood now ? it will be fix?

**Comment by fast4x** [comment]
Not in 0.6.8

**Comment by NEVARLeVrai** [comment]
> Not in 0.6.8

It causes the problem when you turn the screen and when you change the size of the album

**Comment by NEVARLeVrai** [comment]
> Not in 0.6.8

It causes the problem when you turn the screen and when you change the size of the album

**Comment by fast4x** [comment]
Yes, I’m going to understand what the reason is, it shouldn’t happen.

**Comment by fast4x** [comment]
OK, fixed, available from 0.6.9
