### ISSUE TITLE
Dynamic PureBlack Theme

### ISSUE THREAD

**Issue by xSynthetic-wave** [fast4x/RiMusic#910]
### Description

Please make it possible to use the pure black theme but with the dynamic colors from the thumb.

### Suggested Solution

When we use the dynamic theme the colors change depending on the song thumbnail, but when we use the pure black theme the colors always remain the same. What I suggest is to combine the best of both worlds where we have the pure black theme (more comfortable on the eyes and better for some screens) with dynamic colors. 

We've already seen some other APPs out there show that this is possible and that it would make the app UI even better.

**Comment by fast4x** [comment]
Implemented, available from version 0.6.25
