### ISSUE TITLE
[Feature]: Related songs like YouTube music

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#911]
### Description

When a song is playing in YT music, there are **two tabs** for the next song: 1st tab showing **_"up next"_** which is basically the current list of songs being played. 2nd tab is **_"related songs"_**, which shows songs which are similar or related to currently playing song.

I think that's a great approach to discover more songs similar to currently playing song.

**Comment by dAtA-TRoN** [comment]
Isn't that the same as 'start the radio'?

**Comment by sayyid5416** [comment]
> Isn't that the same as 'start radio'?

Actually, they're not quite the same. 'Start radio' typically initiates a playlist based on the current song, whereas 'related songs' provides a broader selection of tracks related to the current one, giving you more control over your listening experience. It's like 'start radio' casts a narrower net while 'related songs' casts a wider one, offering you more options to choose from.

If you give YouTube Music a try, you'll quickly notice how it offers a superior experience compared to simply starting a radio. Its feature set and convenience make it a standout choice. Give it a shot and see the difference for yourself!

**Comment by dAtA-TRoN** [comment]
I see. Maybe I'll check it out sometime.

**Comment by fast4x** [comment]
This feature takes a long time to develop. It’s not a given that it’s possible because the APIs don’t necessarily allow it.

**Comment by sayyid5416** [comment]
> This feature takes a long time to develop. It’s not a given that it’s possible because the APIs don’t necessarily allow it.

I guessed it. I just created this feature request for the sake of logging the functionality. Maybe someone else can contribute later, or you can implement in future.
