### ISSUE TITLE
Persistent queue doesn't seem to be fixed

### ISSUE THREAD

**Issue by dollarSignUsername** [fast4x/RiMusic#913]
### Steps to reproduce the bug

Hi, back with the same bug from #805 and #866
exact same reproduction steps - I went and toggled the option on and off multiple times. Half the time it remembers the que, half if does not. 

### Expected behavior

Qur of songs is remembered when app is restarted (after being swiped out from task manager) 

### Actual behavior

Que is not persistently remembered. I have a screen recording but it exceeds upload limits. 

### RiMusic version

0.6.24

### Android version

Android 14

**Comment by fast4x** [comment]
Ok I'll check specific issuefor Android 14

**Comment by fast4x** [comment]
try this custom version
https://rimusic.xyz/download

**Comment by dollarSignUsername** [comment]
I tried, no improvement

**Comment by fast4x** [comment]
Try again new custom

**Comment by dollarSignUsername** [comment]
Again, no change in behavior. I'm starting to think it may be me 😅

**Comment by fast4x** [comment]
you are most fast, wait for first save 25/30 seconds, after close and reopen

**Comment by dollarSignUsername** [comment]
Ok, that worked. I let the first song play for a bit, then paused and killed the app. Restarted app, song is there at the bottom. I skipped to the next one, played for 2 seconds, paused and killed the app. Restarted, and it was back on the first song where I left off the first time. Does it have anything to do with the min playback duration setting?

**Comment by fast4x** [comment]
I could make the queue refresh rate configurable, what do you think?
