### ISSUE TITLE
App crashing randomly - A14

### ISSUE THREAD

**Issue by abdulkarimx1** [fast4x/RiMusic#916]
### Steps to reproduce the bug

- App crashing randomly when leaving app ( all battery restrictions removed from android settings and in app )
- mini player ( Android 14 ) is not getting pinned ( keeps getting removed from status bar ) 

### Expected behavior

The app shouldn't crash when being opened after some time and the mini player should be always present ( like yt music / any media player app ) 

### Actual behavior

The app get crash and I don't know the reason.

### Logs

https://paste.evolution-x.org/CljZZT

### RiMusic version

Lastest version on github

### Android version

Android 14

**Comment by dAtA-TRoN** [comment]
Delete the cache. Then try again.

**Comment by abdulkarimx1** [comment]
> Delete the cache. Then try again.

This is a clean app install and no cache saved

**Comment by fast4x** [comment]
You have Android 14 try to disable persistent code

**Comment by fast4x** [comment]
mini player ( Android 14 ) is not getting pinned ( keeps getting removed from status bar )

Disable swiping down in ui settings

**Comment by abdulkarimx1** [comment]
> mini player ( Android 14 ) is not getting pinned ( keeps getting removed from status bar )
> 
> Disable swiping down in ui settings

Unfortunately that didn't help..

**Comment by fast4x** [comment]
Your system is a custom ROM?

**Comment by abdulkarimx1** [comment]
> Your system is a custom ROM?

Not sure if it's related but yes, it happened on several roms tho not a single one, it's not consistent but it's repeating randomly.

**Comment by fast4x** [comment]
ok

**Comment by abdulkarimx1** [comment]
> ok

Turning off the option of invincible service / clearing cache of the app, seems to help and now it's not repetitively crashing, everything works good for now. 
Appreciate your help !
