### ISSUE TITLE
New Releases

### ISSUE THREAD

**Issue by Indelibleimprint** [fast4x/RiMusic#917]
### Description

Could you add a "New Releases" spot of your followed artists? Makes it much easier to find new music by the artists you love!!

### Suggested Solution

I'm not sure where to put it but I trust you! Your doing such a great job!! 

### Alternatives

Not sure what to put here as I'm new to GitHub for asking for stuff! 😅

**Comment by fast4x** [comment]
There is already, you find it in the home when there are news about your artists followed
