### ISSUE TITLE
Songs are paused and can't be resumed

### ISSUE THREAD

**Issue by Simon-Sonnleitner** [fast4x/RiMusic#918]
### Steps to reproduce the bug

1. Play any Song
2. Call somebody on WhatsApp or your default call app

### Expected behavior

Either the music stops and but you can resume again (like you can with YouTube music , or the standard YouTube app) or the music doesn't stop and continues playing (although I haven't experienced this behavior with any other music app).

### Actual behavior

The app shows that it is continues playing, but no sound can be heard. After you tab the pause button once the timeline jumps back to the second the call popped up and you can tab the pause button again, but nothing happens, the music won't resume.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/113847208/f136e551-dd2d-4f7d-a6e8-9c37dfaad818

https://github.com/fast4x/RiMusic/assets/113847208/673a4107-73f2-4f05-aa1c-d6c3163ad9ea

### RiMusic version

0.6.24

### Android version

Android 14, One UI 6.0

**Comment by fast4x** [comment]
Enable invincible service and optimization battery in miscellaneous settings

**Comment by Simon-Sonnleitner** [comment]
It is and was enabled while I recorded the videos

**Comment by Simon-Sonnleitner** [comment]
Yes any songs in the app, other apps work, like YouTube music.
I've read a view times, that this happens because the speakers can't be used simultaneously by two different apps, but this is obviously wrong, as i can play music with YT music...

**Comment by fast4x** [comment]
Sorry but i don't understand.

**Comment by Simon-Sonnleitner** [comment]
Yeah, sorry my bad, just ignore the second sentence, it was just in my mind in the moment of typing.

**Comment by fast4x** [comment]
try with next version

**Comment by Simon-Sonnleitner** [comment]
Sorry for not responding, I was quite busy the last few days.
I just updated to the newest version 0.6.25 and the issue still persists.

**Comment by Simon-Sonnleitner** [comment]
@fast4x It still doesn't work in version 0.6.31.
