### ISSUE TITLE
"ViMusic" option not working in "Interface in Use"

### ISSUE THREAD

**Issue by asxhelr657** [fast4x/RiMusic#919]
### Steps to reproduce the bug

1. Open RiMusic app.
2. Go to Settings.
3. Go to UI settings.
4. Scroll down to the 'User Interface' section.
5. Select 'Interface in Use'.
6. Choose 'ViMusic'.

### Expected behavior

The "ViMusic" interface should be selected and change to ViMusic interface.

### Actual behavior

The interface doesn't change to ViMusic interface

### RiMusic version

0.6.24

### Android version

Android 11

**Comment by Nikks84** [comment]
It's changing in my case.
Clear the app cache in app info then try..

**Comment by sayyid5416** [comment]
It's working fine for me.

**Comment by asxhelr657** [comment]
> It's changing in my case. Clear the app cache in app info then try..

I tried it and it still doesn't work. I even deleted RiMusic data, and I don't notice any visual difference. I'm not sure why. I'm considering that it's possible that the Interface in use option applies very minimal changes that I can't notice, but I'm not sure.

**Comment by sayyid5416** [comment]
> > It's changing in my case. Clear the app cache in app info then try..
> 
> I tried it and it still doesn't work. I even deleted RiMusic data, and I don't notice any visual difference. I'm not sure why. I'm considering that it's possible that the Interface in use option applies very minimal changes that I can't notice, but I'm not sure.

There are not many changes which happens. Only few things.

**Comment by Nikks84** [comment]
> > > It's changing in my case. Clear the app cache in app info then try..
> > 
> > 
> > I tried it and it still doesn't work. I even deleted RiMusic data, and I don't notice any visual difference. I'm not sure why. I'm considering that it's possible that the Interface in use option applies very minimal changes that I can't notice, but I'm not sure.
> 
> There are not many changes which happens. Only few things.

Yes @sayyid5416 but @asxhelr657 You did not notice player change before and after applying vi music interface ?

**Comment by asxhelr657** [comment]
> > > > It's changing in my case. Clear the app cache in app info then try..
> > > 
> > > 
> > > I tried it and it still doesn't work. I even deleted RiMusic data, and I don't notice any visual difference. I'm not sure why. I'm considering that it's possible that the Interface in use option applies very minimal changes that I can't notice, but I'm not sure.
> > 
> > 
> > There are not many changes which happens. Only few things.
> 
> Yes @sayyid5416 but @asxhelr657 You did not notice player change before and after applying vi music interface ?

Apologies, I had understood that interface in use completely modified the RiMusic interface so that it was more similar to that of ViMusic. I hadn't noticed the change in the player!
