### ISSUE TITLE
manual adding of sync lyrics

### ISSUE THREAD

**Issue by Learner00100** [fast4x/RiMusic#923]
### Steps to reproduce the bug

.

### Expected behavior

.

### Actual behavior

kindly look into the this
https://github.com/vfsfitvnm/ViMusic/issues/1471#issuecomment-1976246865

### RiMusic version

.

### Android version

.

**Comment by Learner00100** [comment]
> you have tried in RiMusic?

Now it's actually working.
I pasted for unsync lyrics tab, we need to click sync lyrics then paste it works

**Comment by fast4x** [comment]
Perfect
