### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ThaMasEagle** [fast4x/RiMusic#924]
### Steps to reproduce the bug

1. open 
2. Play a while 
3. crashes after a while with old data and a clean data

### Expected behavior

Should not Crash

### Actual behavior

Crashing

### RiMusic version

0.6.24

### Android version

Android 12

### Additional information

people in general, say you should make new data of your own  without crashing but is this not suppose to accommodate the old data, please make it stop crashing even if I start a new data gives me the same issue

**Comment by fast4x** [comment]
Do you have enabled invincible service and battery optimization?

**Comment by ThaMasEagle** [comment]
> Do you have enabled invincible service and battery optimization?

okay will try
