### ISSUE TITLE
[Feature]: Better implementation of 'Song Cache'

### ISSUE THREAD

**Issue by sayyid5416** [fast4x/RiMusic#925]
# Description

<img src="https://github.com/fast4x/RiMusic/assets/78584556/dbf3876b-5716-47bd-8bba-02d3279782d3" alt="User-uploaded image" width="400">

Currently the 'Song Cache size' restricts the size of all cached songs, which is beneficial, but it could be enhanced for better management.

# Suggested Solution

Split this setting into two separate settings:

- **Song Cache**: This setting controls the size of songs cached, excluding those saved in 'Library > Cached'.
- **Saved Songs Cache**: This setting specifically manages the size of songs saved in 'Library > Cached'.

# Benefit

The proposed split will offer more precise control over cached songs. For instance, in my case, nearly 0.5GB is occupied by 'song cache', but only 28 songs are saved in 'Library > Cached'. The rest of the cache comprises songs I haven't finished. With separate settings, I can allocate different sizes for finished and unfinished songs. For example, if I set 1GB for 'saved songs cache', only songs present in 'Library > Cached' will contribute to it. Additionally, I can allocate 100 MB (for instance) to unfinished songs, ensuring better management of my cache space.

**Comment by fast4x** [comment]
Song cache in new version will be without limit and manual clean from preferites playlist and data settings

**Comment by sayyid5416** [comment]
> and manual clean from preferites playlist and data settings

what do you mean by this?

**Comment by fast4x** [comment]
this
![Screenshot_2024-03-04-20-38-44-329_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/ac61af1c-0e9b-4b23-83e0-e318cbe10c37)

**Comment by fast4x** [comment]
and this
![Screenshot_2024-03-04-20-40-00-256_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/3fbd6d72-7bc3-4d6e-8c4f-2f3ffe79997a)

**Comment by sayyid5416** [comment]
So, basically you are saying there will be no limits for cache in future! but why did you changed this?

Isn't it good that we can control the size?

**Comment by fast4x** [comment]
Yes, there was a request for functionality to empty the cache manually. I’m curious to see the reaction of users, if they are happy I will leave the two modes.

**Comment by fast4x** [comment]
I can also enter the two modes now, what do you think?

**Comment by sayyid5416** [comment]
There is already an option to set the 'song cache' to `unlimited`, You can leave it like that, and add a button clear the cache.

But my this feature request is not about that.

**Comment by fast4x** [comment]
![Screenshot_20240304_215421](https://github.com/fast4x/RiMusic/assets/1484476/622ae0ef-2e7d-4af5-877c-3288aafd13ce)

Added manual clean.

Your request is interesting, but there is a problem, the player automatically caches. It means that the preset size is only one. 
Erasing cannot be automatic but manual. Imagine two different buttons clearing the cache based on your favorite songs.

**Comment by sayyid5416** [comment]
> there is a problem, the player automatically caches. It means that the preset size is only one. 

That seems like an issue.

Btw, we can already track the songs which are 100% cached, right! If that's right, then I've an idea _(although I don't know much about android programming)_:
- When your app is calculating the cache size, calculate the 100% cached songs differently than the unfinished songs cache.
- You can implement the delete button for both kinds of cache _(I don't know how you have implemented the functionality of delete button)_.
- Or alternatively, you can move 100% cached songs to a different folder after they are finished.

**Comment by fast4x** [comment]
I'll check it

**Comment by sayyid5416** [comment]
> I think it would be cool if songs that are cached at 100% would be treated as songs downloaded. And until they are cached to 100% they would be taken as not downloaded or cached to 0%. In my opinion, it doesn't matter to the user if the songs are manually downloaded or automatically cached, what matters is that they can play the song offline. So if technically possible, downloaded and cached could be completely merged everywhere including settings.

Yes, 100% cached songs should be treated differently than the ones who are still in progress _(this feature request is about that)_

No, Merging 100% cached songs with downloaded songs would be a horrible idea. Cached songs changes time to time based on listening behaviour and the cache limit set by user, while downloaded songs are the ones which user wants to stay downloaded until he manually delete them. So they should stay in different categories. It's one of the best features of this app.

**Comment by fast4x** [comment]
Imagine not knowing that the cache is managed by the player, that it is cached or that it is downloaded manually, it is still a song downloaded...

**Comment by sayyid5416** [comment]
> Imagine not knowing that the cache is managed by the player, that it is cached or that it is downloaded manually,

I guess everyone have this much common sense, specially when they both are put in different categories in Library.

> it is still a song downloaded...

Yes it is. But isn't it better to know which songs I downloaded willingly and which songs got cached? 

Suppose I've downloaded most of my favourite songs downloaded, and I listens to them on shuffle. Also, I listen to some other songs too, which I don't want to put with my favourite downloaded songs to populate them with songs which I listened to just 1 or 2 times.

If they are cached in different categories, I've the option to have my favourite downloaded songs different from the ones I listened just once or twice.

**Comment by ikanakova** [comment]
> > Imagine not knowing that the cache is managed by the player, that it is cached or that it is downloaded manually,
> 
> I guess everyone have this much common sense, specially when they both are put in different categories in Library.
> 
> > it is still a song downloaded...
> 
> Yes it is. But isn't it better to know which songs I downloaded willingly and which songs got cached?
> 
> Suppose I've downloaded most of my favourite songs downloaded, and I listens to them on shuffle. Also, I listen to some other songs too, which I don't want to put with my favourite downloaded songs to populate them with songs which I listened to just 1 or 2 times.
> 
> If they are cached in different categories, I've the option to have my favourite downloaded songs different from the ones I listened just once or twice.

I understand, but I don't like the idea of having 1 button to delete the (manual) cache (i.e. downloaded) and another button to manually delete the (automatic) cache, etc.

But maybe a solution could be that after merging the automatic and manual cache, an option would appear in the settings - I want two different playlists for downloaded and cached.

**Comment by ikanakova** [comment]
And I wouldn't mind if the memory size setting remained split. I'd just change the name `downloaded` to `manually cached` to make it clear that it's a cache and not some file downloaded to the device (mainly to make it clear to new users).
But I would be happy if I could delete a playlist/song etc manually regardless if it is automatically or manually cached = there would be one icon for that.

**Comment by fast4x** [comment]
@ikanakova @sayyid5416 
Keeping separate or uniting in one voice is not bad because it would give you the freedom to choose according to your own ideas.

**Comment by sayyid5416** [comment]
Basically:
1. Consider "**Cached**" a smart playlist, and
2. Consider "**Downloaded**" a playlist which contains all the manually downloaded songs from all over RiMusic.

**Comment by ikanakova** [comment]
> Basically:
> 
> 1. Consider "Cached" a smart playlist, which contains latest songs user was listening to. --> User should be able to put a limit on how many songs can be cached.
> 2. Consider "Downloaded" a playlist which contains all the manually downloaded songs from all over RiMusic. --> there should not be a limit on this because user is downloading the song willingly and manually.

So except for the playlist, which would be separate for the downloaded and separate for the cache, the manual and automatic caches would actually be merged, am I understanding this correctly?

**Comment by sayyid5416** [comment]
> > Basically:
> > 
> > 1. Consider "Cached" a smart playlist, which contains latest songs user was listening to. --> User should be able to put a limit on how many songs can be cached.
> > 2. Consider "Downloaded" a playlist which contains all the manually downloaded songs from all over RiMusic. --> there should not be a limit on this because user is downloading the song willingly and manually.
> 
> So except for the playlist, which would be separate for the downloaded and separate for the cache, the manual and automatic caches would actually be merged, am I understanding this correctly?

I'm unable to understand you properly! Can you kindly describe it in a little bit depth?

**Comment by sayyid5416** [comment]
> there will be one button that will download/delete downloaded songs and also delete 100% cached songs.
 
By that "one button", do you mean this button or some other button?
<img src="https://github.com/fast4x/RiMusic/assets/78584556/34d1300c-367a-4dfd-8fa9-447afe268543" alt="Description of the image" width="300px">

<br>

> Less than 100% cached songs would be as if they were 0% and maybe there could be an empty cache button in the settings as fast4x suggested but that would only delete the non 100% cache, because I think 100% downloaded cache should be deleted manually e.g. in the playlist.

That would be great. 

<br>

To summarise:
- If someone want to delete only one song from cache _(either from `cached` or from `downloaded`)_, they delete it using `delete` button on that song _(the one in the above screenshot)_ _(It's already present)_
- If someone want to delete **_all songs_** from `downloaded` or `cached` playlist, _**`clear all` button should be present in both `cached` and `downloaded` songs playlists**_ _(it's already present in `downloaded` songs playlist btw)_
- If someone wants to delete unfinished cache songs, this should done from the settings. _(more on it in next point)_
- There should be only two types of limits: **1.** Unfinished songs cache, and **2.** Completely Cached songs. Also, a button to clear them _(as fast4x already shown in ss in prev post)_.

**Comment by ikanakova** [comment]
> By that "one button", do you mean this button or some other button?

I mean this button.

**Comment by sayyid5416** [comment]
@fast4x I think this request is not implemented yet. Was this closed by mistake?

**Comment by fast4x** [comment]
Yes sorry
