### ISSUE TITLE
Song doesn't play when play button is clicked 

### ISSUE THREAD

**Issue by FaqatZubair1** [fast4x/RiMusic#927]
### Steps to reproduce the bug

Turn off the queue loop
Turn off the song loop
Play any album or playlist with only one song in it
When the song finishes, click the play button from notification or on the app

### Expected behavior

The song should play

### Actual behavior

Song doesn't play

### RiMusic version

0.6.24

### Android version

Android 14

### Additional information

The same bug was seen in vimusic

**Comment by fast4x** [comment]
With all off, nothing play...
