### ISSUE TITLE
"Cancel" and "Pause/Resume" buttons for downloading

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#928]
### Description

There are times when we try to download any song but it won't complete download and keep loading (try to download the song) no matter what's done. (probably uninstalling and reinstalling would fix this problem though!? But that's not really right solution I think…)

Also some songs that are long can't be downloaded in which same thing happens.

### Suggested Solution

I think there should be "cancel" button for downloading and if possible "pause/resume" as well.

### Alternatives

Or maybe just warning pop-up before download. But I'd prefer a "cancel" button instead I think.

**Comment by NikunjKhangwal** [comment]
+1
The issue happened with me. A cancel button would prevent this.
#1138

**Comment by NikunjKhangwal** [comment]
Just wanted to mention it's not necessary to implement this in app itself but a cancel button can also be added to app notification. Whichever one is easier to implement as both would serve the same purpose.
Something like this:-
![Picsart_24-03-20_13-33-55-680](https://github.com/fast4x/RiMusic/assets/99175083/b0ecc4fb-a9e0-4756-8104-93ee0952fe21)

**Comment by fast4x** [comment]
Cancel occur if re click on downloading icon...
