### ISSUE TITLE
Customizable Accent Colors

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#930]
### Description

![ZomboDroid_05032024104841-01](https://github.com/fast4x/RiMusic/assets/71184627/b99c09c1-7b03-4257-89c5-97c589135c83)

I propose adding the functionality for users to select custom accent colors within the app. Currently, the app's accent color changes dynamically based on the album cover of the currently playing song when the "dynamic" color scheme is activated, but only while the music is playing. It would be beneficial for users to have the option to choose their own accent color independently of the selected color scheme, including within the "dynamic" mode when no music is playing.

### Suggested Solution

1. Implement a setting option in the app's settings menu for custom accent colors.

2. Provide a color selection palette, allowing users to choose their preferred accent color.

3. Integrate the selected accent color into the default color scheme of the app, as well as all other color schemes, including the dynamic mode.

4. Update the UI elements of the app to reflect the selected accent color consistently.

5. Ensure that the custom accent color displays consistently and user-friendly

### Additional Context

Implementing this feature would offer users more flexibility to personalize their app experience, enhancing the overall user interface customization.

**Comment by fast4x** [comment]
Implemented customized colors theme, available from version 0.6.34

**Comment by dAtA-TRoN** [comment]
> Implemented customized colors theme, available from version 0.6.34

![proxy-image(2).gif](https://github.com/fast4x/RiMusic/assets/71184627/9ab9acc0-5b99-4823-a44a-8372b3efaaa5)

**Comment by fast4x** [comment]
![giphy](https://github.com/fast4x/RiMusic/assets/1484476/3ef2d966-810e-48b5-9910-36a37d7dbacb)
