### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sasha980** [fast4x/RiMusic#932]
### Steps to reproduce the bug

After re-entering the application it crashes, gives an error and then again normally, reboots.
and so on every time.

### Expected behavior

No

### Actual behavior

No

### Screenshots/Screen recordings

No

### Logs

No

### RiMusic version

0.6.24

### Android version

Android 13

### Additional information

After re-entering the application it crashes, gives an error and then again normally, reboots.
and so on every time.

**Comment by fast4x** [comment]
Enable invincible service and battery optimization in miscellaneous settings
