### ISSUE TITLE
Save currently playing queue as new playlist

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#934]
### Description

I mean sometimes we add some songs on queue depending on our mood or situation or whatever. And we might need that same queue again later. But we will need to do that in a harder way.

### Suggested Solution

So I think it'd be great if there was an option to save "currently playing queue" as a new playlist. It would save the hard work. Not that I hate doing that hard work. But sometimes it can be useful to me as well. And I bet it might be more useful for many others though…

**Comment by dAtA-TRoN** [comment]
Could be useful 🤔...

**Comment by fast4x** [comment]
Implemented new queue with context menu, partial/full save songs in playlist or new playlist, export partially o full to file.
Available from version 0.6.25

**Comment by dAtA-TRoN** [comment]
> Implemented new queue with context menu, partial/full save songs in playlist or new playlist, export partially o full to file.
> Available from version 0.6.25

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/6a8a4748-3720-4d92-bade-7f2420414015)
