### ISSUE TITLE
Crashing when opening 'on device' category

### ISSUE THREAD

**Issue by dreamAviator** [fast4x/RiMusic#936]
### Steps to reproduce the bug

1. Go to the library tab and open 'on device'
2. App crashes

### Expected behavior

The app shouldn't crash

### Actual behavior

The app crashes

### RiMusic version

0.6.23

### Android version

Android 12

### Additional information

Maybe I have just too many local audio files?

**Comment by fast4x** [comment]
On device songs require access file permission

**Comment by dreamAviator** [comment]
The app always had the file permission

**Comment by fast4x** [comment]
Upload a log if possible

**Comment by dreamAviator** [comment]
How do I get the logs?
