### ISSUE TITLE
[FEATURE]: Player Notification controls

### ISSUE THREAD

**Issue by NEVARLeVrai** [fast4x/RiMusic#94]
### Description

Mini player improvement by adding like and download icon ?

### Suggested Solution

Adding like and download icon in mini player to be able to like and download music more quickly directly from the lock screen for example 
![Screenshot_2023-11-10-19-43-19-097-edit_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/63956787/ff8fab96-8abd-441c-96ff-73664396eb1a)

**Comment by NEVARLeVrai** [comment]
That would be really interesting, it's very useful and I find it more ergonomic when, for example, you're listening to music and you don't want to unlock the phone to like music or download it

**Comment by NEVARLeVrai** [comment]
And for player if u can move that arrow because it is too close to the corner

**Comment by NEVARLeVrai** [comment]
![IMG_20231110_194620](https://github.com/fast4x/RiMusic/assets/63956787/9b437df9-48e4-4823-83d7-b49e8a97a4a3)

**Comment by NEVARLeVrai** [comment]
If u add and fix that should be good !

**Comment by fast4x** [comment]
Fixed icon on player.
Adding new custom icon on background player will be next versions.

**Comment by NEVARLeVrai** [comment]
> Fixed icon on player.
> Adding new custom icon on background player will be next versions.

Do you will add for mini player icon like and download?

**Comment by NEVARLeVrai** [comment]
Also when u will add ? For mini player?

**Comment by fast4x** [comment]
I’m working on it, there are some bugs that are complicated to handle. A little patience.

**Comment by NEVARLeVrai** [comment]
> I’m working on it, there are some bugs that are complicated to handle. A little patience.

Ok

**Comment by NeeRaj-2401** [comment]
> Also when u will add ? For mini player?

Can u please rename the issue with something as, player Notification controls etc.

Cause miniplayer is something that is within the app when you swipe down the main player screen.

**Comment by fast4x** [comment]
Implemented like button, available from version 0.6.17

**Comment by fast4x** [comment]
Implemented download button, available from version 0.6.17

**Comment by fast4x** [comment]
Available on version 0.6.16.1
