### ISSUE TITLE
How will the search suggestions be like this?

### ISSUE THREAD

**Issue by Nikks84** [fast4x/RiMusic#941]
### Description

As if we know that suggestions for searching any songs appear. How about the pictures/thumbnail of the songs also appear in the suggestion like ss.
![Screenshot_2024-03-06-19-34-59-19](https://github.com/fast4x/RiMusic/assets/160481076/a1335fe3-3d13-489c-ab8e-ae2edc9f0cbf)

### Suggested Solution

This is my personal suggestion.
An additional section for displaying songs picture/thumbnail in search suggestions and directly play them in suggestions section & not type whole song name or no tap in search suggestions then scrolling which one play & song search  suggestions keywords displayed as its.
If possible this feature helps to user to easily play song  in search section.

Hope you understand from the ss

**Comment by fast4x** [comment]
you can play the song from the search results by clicking on it

**Comment by sayyid5416** [comment]
This is actually a good request

**Comment by Nikks84** [comment]
Yes e

> you can play the song from the search results by clicking on it

Exactly but songs thumbnail apper like ss is more easy & helpful to play directly displaying in suggestions As the other music streaming platforms rather than enter song name & tap on search results then play.  
 Oh my English is not good, so I can't explain it any better way

**Comment by fast4x** [comment]
Okay now I understand, excuse my ignorance.
My english isn't better then your...

**Comment by Nikks84** [comment]
Still not understand what  i am trying to say

**Comment by fast4x** [comment]
Don’t worry I understand

**Comment by Nikks84** [comment]
Okay then what's your primary language?

**Comment by fast4x** [comment]
Italian

**Comment by dAtA-TRoN** [comment]
I wish that artists would be displayed in the same way when searching for them. This means having a circular artist image with the Name attached to it that directly links to their artist overview page:

![Screenshot_2024-03-10-21-19-18-57_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/048226fe-ceeb-4715-b7ad-5cd69c419efd)

**Comment by Nikks84** [comment]
> I wish that artists would be displayed in the same way when searching for them. This means having a circular artist image with the Name attached to it that directly links to their artist overview page:
> 
> ![Screenshot_2024-03-10-21-19-18-57_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://private-user-images.githubusercontent.com/71184627/311541906-048226fe-ceeb-4715-b7ad-5cd69c419efd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjE5ODEsIm5iZiI6MTcxMDEyMTY4MSwicGF0aCI6Ii83MTE4NDYyNy8zMTE1NDE5MDYtMDQ4MjI2ZmUtY2VlYi00NzE1LWI3YWQtNWNkNjljNDE5ZWZkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDAxNDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MjU2M2YyYzkzMzM3ZDljMmJjMDBjOTM4YTYxM2RlNWFmMTg3OTRjNjUyMzI3OTA5MDJhOGIyYmI3YWE1OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y8Ay-zjLXLShL4H3SZOt_P0BoYrDyaHYHYJ4ak77PYc)

Yes absolutely

**Comment by Nikks84** [comment]
Do you working on it?

**Comment by fast4x** [comment]
not yet

**Comment by Nikks84** [comment]
> not yet

Ohh

**Comment by fast4x** [comment]
Implemented, available from version 0.6.44
