### ISSUE TITLE
Disabling Animation for Minimized Player When Swipe-Down Gesture is Deactivated

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#948]
### Description

When the option...

![Screenshot_2024-03-06-18-35-48-73_ee4e2c77f5dd6d2e03bdeacf38a89f81](https://github.com/fast4x/RiMusic/assets/71184627/33b6cb2b-07c1-4537-b4c9-feea62a4786c)

...is activated, the behavior of the minimized player becomes unexpected. Despite the activation, the player still responds to swipe-down gestures and remains at two different heights, resulting in an inconsistent user experience. Check a look:

https://github.com/fast4x/RiMusic/assets/71184627/a2eb6a78-ed53-4827-8d24-2b66e0ebd7e0

My proposal is to maintain the minimized player in a static position and deactivate the animation for swipe-down gestures once the mentioned option is enabled.

### Suggested Solution

Deactivate the animation for swipe-down gestures when the option "Disable swiping down: Avoid closing the player and cleaning the queue by swiping down while it is minimized" is enabled. This adjustment ensures the player remains in a fixed position, providing users with a consistent experience.

### Additional Context

The inconsistent animation behavior of the minimized player with swipe-down gestures is confusing and hampers the application's usability. Implementing this refinement ensures a consistent user experience for all users and aligns with user preferences.

**Comment by dAtA-TRoN** [comment]
You are crazy man. You code faster than your shadow can keep up with!

**Comment by fast4x** [comment]
I’m probably a little crazy ahahah.
