### ISSUE TITLE
Some songs r not playing due to server

### ISSUE THREAD

**Issue by Azzman1984** [fast4x/RiMusic#949]
### Steps to reproduce the bug

Go to a song
Click play on song 
Song doesn't play and says "This Song cannot be played due to server restrictions

### Expected behavior

Click on the song, press play and plays the song as normal

### Actual behavior

Clicks play on the song and instead it says "This Song cannot be played due to server restrictions."

### Screenshots/Screen recordings

![Screenshot_20240306_175754](https://github.com/fast4x/RiMusic/assets/150800081/5bbac186-27e0-49b9-9a35-5e84369dbbc2)

### RiMusic version

0.6.24

### Android version

Android 13

**Comment by ikanakova** [comment]
You better post a link to the song too.

**Comment by Azzman1984** [comment]
> You better post a link to the song too.

Here's the link https://music.youtube.com/watch?v=ISEIxaPsp_I

**Comment by dAtA-TRoN** [comment]
Perhaps because it's explicit content?

**Comment by ikanakova** [comment]
> It might be attributed to its potentially explicit content. Just a speculative guess, as I'm unfamiliar with the song.

That's right. The video won't even show up in my browser when I'm not logged in, because it may be inappropriate for some users. So it's not a RiMusic bug.

**Comment by SeerBlazeJ** [comment]
There are some songs which are not explicit and yet can not be played, like this : 
![Screenshot_20240307_210839](https://github.com/fast4x/RiMusic/assets/109931301/9ec48343-7659-47ad-8363-ae1e31cc84be)
