### ISSUE TITLE
Found another lyrics provider.

### ISSUE THREAD

**Issue by Learner00100** [fast4x/RiMusic#950]
### Description

Another lyrics source

### Suggested Solution

For some Indian songs, lyrics not available in kogu.
Also musixmatch can't display (even in its own app-not Authorize to display lyrics of current song) so it's not show in rimusic also.

Where https://github.com/KRTirtho/spotube ,
Use Spotify or jiosavam as lyrics provider, which is provide lyrics for most songs.
Even synced lyrics they provide.
Kindly look on that repo for implementation.
And include this source also if possible.

Also implement a condition like, if kogu enabled, Frist it's try to display form them , if failed then it's automatically switch to next provider.

Also in fetch again option, give a text filed so that we can change song name or artist because some some have incorrect spelling so lyrics won't able to fetch using fetch again option

**Comment by Logan7899** [comment]
@fast4x see this

**Comment by ikanakova** [comment]
@Logan7899 I don't think its necessary to mention him, fast4x reads every issue.

**Comment by fast4x** [comment]
I looked for some information about this provider, from his site it doesn’t have a free version. There are some questions in the web but with not precise answers. Are you sure that the song codes are the ones used by YTM? Are you sure that it gives the possibility to use lyrics for free?

**Comment by Learner00100** [comment]
> I looked for some information about this provider, from his site it doesn’t have a free version. There are some questions in the web but with not precise answers. Are you sure that the song codes are the ones used by YTM? Are you sure that it gives the possibility to use lyrics for free?

I guess it use Spotify lyrics database, as it requires Spotify login.
Also the song I tested only show lyrics in this app and Spotify.
Musixmatch have limitations on API based only, you can check simpmusic app implementation for musixmatch(they use alternate method).

Also in Rimusic ,what is current provider for unsync lyrics?

**Comment by fast4x** [comment]
Same of ViMusic original

**Comment by Learner00100** [comment]
> Same of ViMusic original YT

So for both sync and unsync lyrics using kogu provider

**Comment by VINULA2007** [comment]
https://github.com/Lambada10/SongSync
This app gets lyrics straight from Spotify 
https://lrclib.net/db-dumps
And this a offline database for many lyrics

**Comment by fast4x** [comment]
Ok thanks, see you later.

**Comment by Learner00100** [comment]
> Implemented, added new provider lyrics LrcLib.net. Available from version 0.6.28.1

Oh nice, waiting for new version.
Let's see lrclib will have lyrics for Indian songs, I suggested the repo in issue, because it fetch from Spotify which have many lyrics.

But early waiting for new update with new implementation.
Thanks

**Comment by VINULA2007** [comment]
> Implemented, added new provider lyrics LrcLib.net. Available from version 0.6.28.1

Give a round of applause

**Comment by VINULA2007** [comment]
> Implemented, added new provider lyrics LrcLib.net. Available from version 0.6.28.1

Getting a custom version?

**Comment by fast4x** [comment]
No custom, today new release 0.6.28.1

**Comment by VINULA2007** [comment]
> No custom, today new release 0.6.28.1

Can't find it 😞

**Comment by fast4x** [comment]
Of course, today will be released
