### ISSUE TITLE
Need for a scrolbar, changing queue bug

### ISSUE THREAD

**Issue by SeerBlazeJ** [fast4x/RiMusic#951]
### Description

1. We need a proper scrollbar to scroll through large Playlist 
2. While changing the order of the queue there are difficulties and quite a few bugs, which come to nmotice especially in larger queues. The issue is that while taking a song up, the list doesn't move up properly, resulting in a mess in queue.
3. (optional) Missing optimisation for a tablet
4. It would be great if you add widgets which can be added to home screen

### Suggested Solution

1. Add a scrollbar like samsung music (much better than other music apps)
2. queue order changing needs to be made as smooth as spotify
3. It would be great if you optimise app further for tablet
4. Widgets would be great, especially if they are interactive and have the ability to become the control of music themselves (much better if you even add an option to open a playlist directly)

**Comment by SeerBlazeJ** [comment]
Also, swipe gesture gets enables every now and than, it gets irritating, please decrease the sensitivity of it.

**Comment by dAtA-TRoN** [comment]
> Also, swipe gesture gets enables every now and than, it gets irritating, please decrease the sensitivity of it.

I've noticed that as well. Especially when I'm scrolling through longer playlists, I often unintentionally activate swipe gestures. It would be nice if the sensitivity/threshold could be dialed down a bit.

**Comment by fast4x** [comment]
> Add a scrollbar like samsung music (much better than other music apps)
I don't know samsung music

> queue order changing needs to be made as smooth as spotify
RiMusic isn't Spotify and don't developed based on it

> It would be great if you optimise app further for tablet
Some have already been done, in your case what exactly are you referring to?

> Widgets would be great, especially if they are interactive and have the ability to become the control of music themselves (much better if you even add an option to open a playlist directly)
Yes, but in the future

**Comment by SeerBlazeJ** [comment]
> > Add a scrollbar like samsung music (much better than other music apps)
> > > I don't know samsung music
> > > > For samsung music's scrollbar, I'll attach a pic.
https://github.com/fast4x/RiMusic/assets/109931301/1cc37eaa-6004-4eca-b082-9727e330b498
> 
> > queue order changing needs to be made as smooth as spotify
> > > RiMusic isn't Spotify and don't developed based on it
 Sure, it is not developped like spotify but atleast you can get rid of bugs, ill attach a video of the bug, it can be obviously seen...
https://github.com/fast4x/RiMusic/assets/109931301/4c63bd6a-4181-42a7-a64b-7e1253638673
> 
> > It would be great if you optimise app further for tablet
> > > Some have already been done, in your case what exactly are you referring to?
> > > > Also agreed about tablets, much more optimised than some other apps, but the visualiser is not working properly It's video will also be attached by me below ( and yes have given the permission for microphone)
https://github.com/fast4x/RiMusic/assets/109931301/ea890bb4-6f08-401e-b861-bb149326eebe
> 
> > Widgets would be great, especially if they are interactive and have the ability to become the control of music themselves (much better if you even add an option to open a playlist directly)
> > > Yes, but in the future

> Also you see the artists of many songs are not chodo even though if I search for songs individually I can see them but these ones I downloaded from your service only and I do not see the artist name please fix that one

> One more request, a feature to crossfade tracks would give your app a premium finish (It is my favourite feature in any music streaming service)





> totally appreciate the hard work you have done in making this app and it is also much better than some private alternative like Saavn and wynk music but some minor fixes can make it better than even YouTube music itself. Keep it up!😊

**Comment by dAtA-TRoN** [comment]
@SeerBlazeJ 

Why do you post links to the videos and images when they can be easily embedded here?

https://github.com/fast4x/RiMusic/assets/71184627/e87c3c90-917d-4f09-89db-c3c86b527f8d

**Comment by sayyid5416** [comment]
> @SeerBlazeJ
> 
> Why do you post links to the videos and images when they can be easily embedded here!?
> 
> ![4_5947497766052696280-ezgif.com-video-to-gif-converter(1).gif](https://private-user-images.githubusercontent.com/71184627/310960856-c081ded6-7992-4e84-a1fe-551aae580875.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjkyNzgsIm5iZiI6MTcwOTgyODk3OCwicGF0aCI6Ii83MTE4NDYyNy8zMTA5NjA4NTYtYzA4MWRlZDYtNzk5Mi00ZTg0LWExZmUtNTUxYWFlNTgwODc1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE2MjkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMTNiODNhZjdmN2ViODNiMjk5OTU5YmFhNGZhOGFlYWE5MzQ0Yjc5YWEwZjdiYmZjNjQ5NGUxZDUyMDU5NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T_4wOV8u4CM8lifvL2tbgVEZKBlhULcOSidvjHTEfoE) [ ![4_5947497766052696280-ezgif.com-video-to-gif-converter(1).gif](https://private-user-images.githubusercontent.com/71184627/310960856-c081ded6-7992-4e84-a1fe-551aae580875.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjkyNzgsIm5iZiI6MTcwOTgyODk3OCwicGF0aCI6Ii83MTE4NDYyNy8zMTA5NjA4NTYtYzA4MWRlZDYtNzk5Mi00ZTg0LWExZmUtNTUxYWFlNTgwODc1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE2MjkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMTNiODNhZjdmN2ViODNiMjk5OTU5YmFhNGZhOGFlYWE5MzQ0Yjc5YWEwZjdiYmZjNjQ5NGUxZDUyMDU5NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T_4wOV8u4CM8lifvL2tbgVEZKBlhULcOSidvjHTEfoE) ](https://private-user-images.githubusercontent.com/71184627/310960856-c081ded6-7992-4e84-a1fe-551aae580875.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjkyNzgsIm5iZiI6MTcwOTgyODk3OCwicGF0aCI6Ii83MTE4NDYyNy8zMTA5NjA4NTYtYzA4MWRlZDYtNzk5Mi00ZTg0LWExZmUtNTUxYWFlNTgwODc1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE2MjkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMTNiODNhZjdmN2ViODNiMjk5OTU5YmFhNGZhOGFlYWE5MzQ0Yjc5YWEwZjdiYmZjNjQ5NGUxZDUyMDU5NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T_4wOV8u4CM8lifvL2tbgVEZKBlhULcOSidvjHTEfoE) [ ](https://private-user-images.githubusercontent.com/71184627/310960856-c081ded6-7992-4e84-a1fe-551aae580875.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjkyNzgsIm5iZiI6MTcwOTgyODk3OCwicGF0aCI6Ii83MTE4NDYyNy8zMTA5NjA4NTYtYzA4MWRlZDYtNzk5Mi00ZTg0LWExZmUtNTUxYWFlNTgwODc1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE2MjkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMTNiODNhZjdmN2ViODNiMjk5OTU5YmFhNGZhOGFlYWE5MzQ0Yjc5YWEwZjdiYmZjNjQ5NGUxZDUyMDU5NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T_4wOV8u4CM8lifvL2tbgVEZKBlhULcOSidvjHTEfoE)

Dude, This gif is scary and creepy af.

**Comment by fast4x** [comment]
Ok thank you for the ideas, you have to consider that Spotify will always be the benchmark for the music world. This does not mean that functionality can be added to RiMusic because it is not a clone

**Comment by dAtA-TRoN** [comment]
> But where do you find these images? ahahaha

In the deepest depths of the internet 🤣🤣🤣.

**Comment by SeerBlazeJ** [comment]
> > @SeerBlazeJ
> > Why do you post links to the videos and images when they can be easily embedded here!?


> Bro, I am not a veteran in GitHub

**Comment by dAtA-TRoN** [comment]
> Bro, I am not a veteran in GitHub

Glad, that i could help.

**Comment by fast4x** [comment]
Implemented crossfade songs effect, available from version 0.6.34
