### ISSUE TITLE
Download button 

### ISSUE THREAD

**Issue by surajak** [fast4x/RiMusic#953]
### Description

When clicking download button icon,  for already downloaded song, it deleted downloaded song. This is not intended.

### Suggested Solution

It should show a pop up that song is already downloaded. And should not deleted song from local storage.

**Comment by ikanakova** [comment]
When a song is already downloaded the icon looks different than when it's not (downloaded: <img src="https://raw.githubusercontent.com/fast4x/RiMusic/master/assets/ionicons/download.svg" width="20"> X not downloaded: <img src="https://raw.githubusercontent.com/fast4x/RiMusic/master/assets/ionicons/outline/download-outline.svg" width="20"> , so I think the popup is unnecessary in this case. It's a different situation for download/delete all, where the app asks if the user really wants it, but for individual songs I'm all about making sure downloads and deletes happen without unnecessary delays.

**Comment by dAtA-TRoN** [comment]
Perhaps incorporating an optional "Are you sure you want to delete this download?" message could be the solution for him.

**Comment by fast4x** [comment]
The solution is definitely the popup but it would make the quick download useless...

**Comment by fast4x** [comment]
Confirm, it's a work useless because song can be downloaded again immediately.

**Comment by sayyid5416** [comment]
I completely agree. Additional confirmations seem unnecessary considering the distinct icons already in place. Moreover, rectifying an accidental deletion merely requires a single click.

**Comment by abdulkarimx1** [comment]
> Confirm, it's a work useless because song can be downloaded again immediately.

I already opened an " enhancement " earlier regarding this confusion of the button if you remember 😁, some people get confused because of them ( especially when trying to make them work from Android player since it doesn't always work - meaning when downloading/deleting from downloads in status bar ) that's why i suggested Earlier ( if possible for sure ) to make the download button left as it is and add a tick ( ✅ ) button so user can differentiate whether it's downloaded or not.

**Comment by ikanakova** [comment]
>> Confirm, it's a work useless because song can be downloaded again immediately.
> 
> I already opened an " enhancement " earlier regarding this confusion of the button if you remember 😁, some people get confused because of them ( especially when trying to make them work from Android player since it doesn't always work - meaning when downloading/deleting from downloads in status bar ) that's why i suggested Earlier ( if possible for sure ) to make the download button left as it is and add a tick ( ✅ ) button so user can differentiate whether it's downloaded or not.

But that would be even more confusing, I think, because this is not a classic download to a file but a manual download of a song to the cache, so I think it should not behave as if something is being downloaded, but it should behave the same as if a song is automatically downloaded to the cache (as I suggest in issue #).

**Comment by surajak** [comment]
My suggestion is, After downloading the song can that download symbol be change something like 'correct mark'. Defining that song is downloaded. So confusion can be minimised. So user will see a down side arrow⬇️ when song is not downloaded, and a correct mark ✅ when it downloaded. So it will make quick download quick because no pop ups.

**Comment by surajak** [comment]
Other option, don't make the switch to work for download and delete, only download, even if, one clicks again song will not delet but checks if it's downloaded or not if not,download it, if yes do nothing.

**Comment by sayyid5416** [comment]
Current implementation is good enough in my opinion. But still, if you want to do something, looks of download icon can be improved.

**Comment by fast4x** [comment]
Any idea for new download icons?

**Comment by sayyid5416** [comment]
maybe something like this?

![image](https://github.com/fast4x/RiMusic/assets/78584556/2e4cddd3-0781-4675-846b-5e2a7f4cbd44)

**Comment by dAtA-TRoN** [comment]
> maybe something like this?
👌🏼👌🏼👌🏼
https://github.com/fast4x/RiMusic/assets/71184627/e2919165-e054-4803-8091-86aa7ab4ffe9

**Comment by dAtA-TRoN** [comment]
> maybe something like this?

👌🏼👌🏼👌🏼
https://github.com/fast4x/RiMusic/assets/71184627/d9030e48-e853-4512-afce-766b6b331576

**Comment by fast4x** [comment]
> maybe something like this?
> 
> ![image](https://github.com/fast4x/RiMusic/assets/78584556/2e4cddd3-0781-4675-846b-5e2a7f4cbd44)
> 

Too big in height

**Comment by sayyid5416** [comment]
> > maybe something like this?
> > ![image](https://private-user-images.githubusercontent.com/78584556/311242696-2e4cddd3-0781-4675-846b-5e2a7f4cbd44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MDk4MzEsIm5iZiI6MTcwOTkwOTUzMSwicGF0aCI6Ii83ODU4NDU1Ni8zMTEyNDI2OTYtMmU0Y2RkZDMtMDc4MS00Njc1LTg0NmItNWUyYTdmNGNiZDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE0NTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMDRmMDAwZDIyY2U3NjJmZDkwNmNkMmJlYjZmMmU5MWQyMDAxYWJkODgzMDBkNWFlMzhjMDcxZTE5NjZhYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UJWjOz1_XnvTLwPnLIINhft02kkhRK47OYU6TdnFBpA)
> 
> Too big in height

It's just an idea for ikanakova

**Comment by abdulkarimx1** [comment]
> > maybe something like this?
> > ![image](https://private-user-images.githubusercontent.com/78584556/311242696-2e4cddd3-0781-4675-846b-5e2a7f4cbd44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MTAzMjgsIm5iZiI6MTcwOTkxMDAyOCwicGF0aCI6Ii83ODU4NDU1Ni8zMTEyNDI2OTYtMmU0Y2RkZDMtMDc4MS00Njc1LTg0NmItNWUyYTdmNGNiZDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE1MDAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NDE0ZTRkMmRmN2ZkNjZjMzg1NDc2MmRlYWI4NTg5MTcxZTA5ZWNiOGE5M2U4NjAzMTk0N2FmYjdkMWQyMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rDtkbA0YZmpAtwVavKuMowtgxyD7mKVnTYl6SnZ8g2s)
> 
> Too big in height

How about using chrome-like icons ? [https://images.app.goo.gl/qwqLexDnb1xcVyyk9](url)

**Comment by ikanakova** [comment]
> I don't know! @ikanakova do you think you can improve the download icons?

I will definitely make it similar and compatible with the current icons. But now I'm on vacation in Slovenia and Italy so when I come back I'll do it.

**Comment by fast4x** [comment]
Enjoy holiday

**Comment by ikanakova** [comment]
> Enjoy holiday

Thank you

**Comment by ikanakova** [comment]
@fast4x could you please assign me this one as well

**Comment by ikanakova** [comment]
- undownloaded ("uncached") song / playlist: <img src="https://raw.githubusercontent.com/fast4x/RiMusic/master/assets/ionicons/outline/download-outline.svg" width="30">
- downloaded ("cached") song / playlist: <img src="https://github.com/fast4x/RiMusic/assets/38765251/651fc121-9025-424c-84ee-52470aff83bf" width="30">
- partially downloaded playlist: <img src="https://github.com/fast4x/RiMusic/assets/38765251/57a799d8-5e77-47ab-98ad-61f7a233c40f" width="30">


What do you think?

**Comment by abdulkarimx1** [comment]
> * undownloaded ("uncached") song / playlist: <img alt="" width="30" src="https://raw.githubusercontent.com/fast4x/RiMusic/master/assets/ionicons/outline/download-outline.svg">
> * downloaded ("cached") song / playlist: <img alt="" width="30" src="https://private-user-images.githubusercontent.com/38765251/315232573-651fc121-9025-424c-84ee-52470aff83bf.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTQ5MDUsIm5iZiI6MTcxMTAxNDYwNSwicGF0aCI6Ii8zODc2NTI1MS8zMTUyMzI1NzMtNjUxZmMxMjEtOTAyNS00MjRjLTg0ZWUtNTI0NzBhZmY4M2JmLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA5NTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNGU3MWI0MTA2ZmI3NWMyOWYzZTJmZTU4ZTk2MzdiNmE1YmE2MmEzZTdkOTEzNmIzYjE2MTVmZGIzNzI3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EhLwgKQzuNWHpBYUcqv7ZAcx3gYqyKbgd95dzmFd09k">
> * partially downloaded playlist: <img alt="" width="30" src="https://private-user-images.githubusercontent.com/38765251/315232845-57a799d8-5e77-47ab-98ad-61f7a233c40f.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTQ5MDUsIm5iZiI6MTcxMTAxNDYwNSwicGF0aCI6Ii8zODc2NTI1MS8zMTUyMzI4NDUtNTdhNzk5ZDgtNWU3Ny00N2FiLTk4YWQtNjFmN2EyMzNjNDBmLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA5NTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMDM4MTAxYTg0ZGFjYmQ2ZmUxM2E1NjlmMjM4ZmYwODQ0NzZmMTkzYzYwOTRkYzk1ZTM5NGI4NDA2MDU3NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9g4Ym-VebElYtn4N2xyq75y-KGio5to-sL_ethKCWNg">
> 
> What do you think?

That looks great !

**Comment by fast4x** [comment]
Nice

**Comment by dAtA-TRoN** [comment]
Wow, looks cool!

**Comment by sayyid5416** [comment]
> * undownloaded ("uncached") song / playlist: <img alt="" width="30" src="https://raw.githubusercontent.com/fast4x/RiMusic/master/assets/ionicons/outline/download-outline.svg">
> * downloaded ("cached") song / playlist: <img alt="" width="30" src="https://private-user-images.githubusercontent.com/38765251/315232573-651fc121-9025-424c-84ee-52470aff83bf.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjIyODAsIm5iZiI6MTcxMTAyMTk4MCwicGF0aCI6Ii8zODc2NTI1MS8zMTUyMzI1NzMtNjUxZmMxMjEtOTAyNS00MjRjLTg0ZWUtNTI0NzBhZmY4M2JmLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDExNTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYmExZWVlNGRmYTZhMzIzYzQ3NzZiYmRjNWIzNzRlY2VmODhmODdhM2UwOWQ2ZTk5ZmNmN2E0ZGQ2MDViN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.00PjEnRjSJUHqiznT6PY8bq0MHB8cvDSvwggT79uDXI">
> * partially downloaded playlist: <img alt="" width="30" src="https://private-user-images.githubusercontent.com/38765251/315232845-57a799d8-5e77-47ab-98ad-61f7a233c40f.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjIyODAsIm5iZiI6MTcxMTAyMTk4MCwicGF0aCI6Ii8zODc2NTI1MS8zMTUyMzI4NDUtNTdhNzk5ZDgtNWU3Ny00N2FiLTk4YWQtNjFmN2EyMzNjNDBmLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDExNTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOTc2MTkyZGE4ZWE2ODg0NTEzZTQ1MTZhMzMyN2ZiMWRmOTEyNzkyYzg3ZjUyOWNkMGY0MjhmMjNhODM5MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FA-7xQ9asSteqd4UKyj23z-QN1lNtnB1fF-4l6uNIkU">
> 
> What do you think?

Wow. Those looks great

**Comment by ikanakova** [comment]
Thank you 😊

**Comment by fast4x** [comment]
Added... available from version 0.6.27 it's very very very nice...

**Comment by SureshTimma** [comment]
> Added... available from version 0.6.27 it's very very very nice... 

Which time GMT do you release update?

**Comment by fast4x** [comment]
Friday UTC 15:00 - 22:00

**Comment by ikanakova** [comment]
Fixed the download icons:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/60009852-8074-4550-88f5-80b458b7ead6" width="25">
<img src="https://github.com/fast4x/RiMusic/assets/38765251/275825a9-51d3-46c8-90cf-e71870b9ebcc" width="25">
Is this good enough?

**Comment by dAtA-TRoN** [comment]
> Is this good enough?

I guess so.

**Comment by ikanakova** [comment]
#1218
