### ISSUE TITLE
[Feature]: Using DLNA™ technology to push media content to TV connected to the same Wi-Fi network

### ISSUE THREAD

**Issue by NguyenTrongThinh** [fast4x/RiMusic#954]
### Description

Instead of playing music on my phone I want to play it on TV or a sound system via DLNA. 

### Suggested Solution

Add a "cast" button to choose to play on another device or phone.

### Alternatives

Ability to export downloaded songs to an external folder to use other software to cast to TV

**Comment by fast4x** [comment]
Hi, cast require proprietary library added in RiMusic and it's not planned.
