### ISSUE TITLE
Download button..!

### ISSUE THREAD

**Issue by kris20030705** [fast4x/RiMusic#960]
### Steps to reproduce the bug

Download button

### Expected behavior

Music, lyrics + art album

### Actual behavior

Only music downloading not album art

### RiMusic version

0.1.5

### Android version

Android 9

**Comment by dAtA-TRoN** [comment]
> The latest version is 0.6.24 and 0.6.25 is about to come in few hours.

I can't wait, seriously!

**Comment by Nikks84** [comment]
> > The latest version is 0.6.24 and 0.6.25 is about to come in few hours.
> 
> I can't wait, seriously!

Dev be like : keep some patience 😄

**Comment by dAtA-TRoN** [comment]
> Dev be like : keep some patience 😄

https://github.com/fast4x/RiMusic/assets/71184627/3a710fc2-b9c1-44c3-a4e3-d83e53117893

**Comment by Nikks84** [comment]
😂😂😂 that was  funny

**Comment by KrisTamang** [comment]
> You should update the app. The latest version is 0.6.24 and 0.6.25 is about to come in few hours.

Still didnt fixed..!
Album art keep erasing..!

**Comment by KrisTamang** [comment]
See..!?

**Comment by KrisTamang** [comment]
https://github.com/fast4x/RiMusic/assets/107674915/a0127622-b31c-4756-bc3d-6fc265c82038

See...!!

**Comment by fast4x** [comment]
Album art is cached...
