### ISSUE TITLE
Amendment Proposal: Adjustment to Dynamic Themes

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#964]
### Description

Following the latest update, it appears that the Dynamic Theme underwent changes. Two new Pure Black themes, PureBlack and Modern PureBlack, seem to have been introduced. Consequently, the Dynamic Theme now appears pitch black, which, in my view, may be a misstep.

### Suggested Solution

Either revert the Dynamic Theme to its original brightness or introduce an additional theme that maintains the brightness of the standard theme while retaining dynamic color elements.

### Additional Context

A pitch-black Dynamic Theme could potentially disrupt the user experience, especially for those accustomed to the previous brightness level. A more balanced solution would involve a theme with dynamic colors that does not adopt the extreme darkness of the new Pure Black themes.

**Comment by fast4x** [comment]
modern and pure black there were already, I have changed background in black mode...

**Comment by dAtA-TRoN** [comment]
Ah, I understand. It would be wonderful if you could provide a variant similar to the previous one, more like "dark" rather than pitch black. I really enjoyed the dynamic colors in the previous dark mode. However, I'm not particularly fond of pitch black. Nonetheless, I must commend you on the update; it's once again fantastic work 😃!

**Comment by fast4x** [comment]
Implemented, available from version 0.6.26
