### ISSUE TITLE
Fine-tune "total time queued songs in player"

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#965]
### Description

"Song Time Left" and "Queue Total Time" being together doesn't look that good to me. I think "Song Time Left" is better to stay there. But the "Queue Total Time" should be somewhere else. Ideally around the same place but without making it look crowded. Which seems hard.

### Suggested Solution

You could place the time somewhere else. Like one of these marked places: 
![Screenshot_20240308-230247](https://github.com/fast4x/RiMusic/assets/85461823/01da984a-5ed8-46fa-8618-cef42f37d781)

Look at these:
![InCollage_20240308_234144357](https://github.com/fast4x/RiMusic/assets/85461823/375752b5-95d2-401c-b555-49e1bf596997)

(sorry for bad editing btw)
I personally think it looks best placed above thumbnail (just as I thought it would) and looks the worst placed between thumbnail and song title.

**Comment by fast4x** [comment]
Adding a row in layout create mismatch inconsistency.

**Comment by fast4x** [comment]
Yes is possible but I have to be careful of so many possible bugs. I'll try to put under image.

**Comment by fast4x** [comment]
Improved, moved under thumbnail.
Available from version 0.6.26
