### ISSUE TITLE
Disappearance of play symbol background following today's update

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#966]
### Steps to reproduce the bug

1. Launch the RiMusic application on your device.

2. Navigate to the page containing playback controls, while using the "Dynamic," "PureBlack," or "ModernBlack" theme.

3. Observe the absence of the play symbol's background.

4. Attempt to choose a different design for the play symbol from the menu. Note the inability to do so.

### Expected behavior

The play symbol should include its background as a design element. Users should be able to select different designs for the play symbol from the menu, thereby customizing its appearance to their preference.

### Actual behavior

The play symbol's background is missing, impacting the visual appeal of the design. Furthermore, the feature to select various designs does nothing.

### RiMusic version

0.6.25

### Android version

Android 13

### Additional information

Following today's update, it has come to my attention that the play symbol's background is missing, specifically in the "Dynamic," "PureBlack," and "ModernBlack" themes of the RiMusic app. This results in the loss of a visually appealing design element. Additionally, the option to select various designs for the play symbol from the menu is no longer functional, impacting user-friendliness and aesthetic appeal.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.26
