### ISSUE TITLE
[Feature]: To Add "Added Date" as Sort Order

### ISSUE THREAD

**Issue by PitchAbyss** [fast4x/RiMusic#968]
### Description

Sort Order to Show Latest Added Songs On Top

### Suggested Solution

Sort Order to Show Latest Added Songs On Top

**Comment by fast4x** [comment]
Last added where?

**Comment by PitchAbyss** [comment]
> Last added where?

Sir when we add a song to play list it should appear on top "sort as latest added"

**Comment by fast4x** [comment]
Thanks for details

**Comment by PitchAbyss** [comment]
> Thanks for details

hi sir i just noticed that when i go under cached section this option is all ready there but cant see for play lists

![photo_2024-04-14_16-03-48](https://github.com/fast4x/RiMusic/assets/13099434/33d507bd-5a4e-435d-acd2-d6259d457b48)

**Comment by fast4x** [comment]
I'll check it

**Comment by PitchAbyss** [comment]
> I'll check it 

Thankyou

**Comment by fast4x** [comment]
Implemented, available from version 0.6.32

**Comment by PitchAbyss** [comment]
> Implemented, available from version 0.6.32

You are the bestttt thankyou sooo much sir
