### ISSUE TITLE
Border around buttons.

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#97]
### Steps to reproduce the bug

1. Start app.
2. Play song.

### Expected behavior

Centered and proportioned borders around the buttons.

### Actual behavior

I don't know if this is intentional or a bug. But the border around the play button is too wide, while the border around the next and previous buttons is too small and it looks to me like the next/previous buttons aren't quite centered.

### Screenshots/Screen recordings

![Screenshot_20231111_141955](https://github.com/fast4x/RiMusic/assets/38765251/82ac5fe5-05ec-4112-9f31-ea012efc3b6a)

### RiMusic version

0.6.8

### Android version

Android 13

### Additional information

Samsung A53

**Comment by dainvincible1** [comment]
in the previous version the border for all three was kind of same and it looked very empty kind of. for me this wide play/ pause looks really better

**Comment by ikanakova** [comment]
> in the previous version the border for all three was kind of same and it looked very empty kind of. for me this wide play/ pause looks really better

Or it could be optional if the border is to be visible.

**Comment by fast4x** [comment]
Ok, improve It next version

**Comment by fast4x** [comment]
Fixed, available from version 0.6.9
