### ISSUE TITLE
Difficulty in Identifying New Player Controls in Lyric View

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#970]
### Steps to reproduce the bug

1. Launch the application and navigate to the Lyric view.

2. Attempt to locate and identify the new player controls.

3. Switch between different theme options to assess visibility.

### Expected behavior

The new player controls should be easily distinguishable, irrespective of the selected theme. Furthermore, in the dynamic theme, the colors of these controls should adapt based on the current song, which is currently not occurring.

### Actual behavior

Difficulty in discerning player controls, particularly evident in the dynamic, PureBlack, and ModernBlack themes.

### Screenshots/Screen recordings

![IMG_20240308_193807](https://github.com/fast4x/RiMusic/assets/71184627/0c364037-480c-42e4-9afa-581485b83a62)

### RiMusic version

0.6.25

### Android version

Android 13

**Comment by fast4x** [comment]
Yes i'll try to improve

**Comment by fast4x** [comment]
Fixed, available from version 0.6.26

**Comment by dAtA-TRoN** [comment]
> Fixed, available from version 0.6.26

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/26c93143-ae68-444a-bb8f-6e0b271bbe29)

**Comment by Nikks84** [comment]
> ### Steps to reproduce the bug
> 1. Launch the application and navigate to the Lyric view.
> 2. Attempt to locate and identify the new player controls.
> 3. Switch between different theme options to assess visibility.
> 
> ### Expected behavior
> The new player controls should be easily distinguishable, irrespective of the selected theme. Furthermore, in the dynamic theme, the colors of these controls should adapt based on the current song, which is currently not occurring.
> 
> ### Actual behavior
> Difficulty in discerning player controls, particularly evident in the dynamic, PureBlack, and ModernBlack themes.
> 
> ### Screenshots/Screen recordings
> ![IMG_20240308_193807](https://private-user-images.githubusercontent.com/71184627/311334015-0c364037-480c-42e4-9afa-581485b83a62.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NTEwNTMsIm5iZiI6MTcwOTk1MDc1MywicGF0aCI6Ii83MTE4NDYyNy8zMTEzMzQwMTUtMGMzNjQwMzctNDgwYy00MmU0LTlhZmEtNTgxNDg1YjgzYTYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDAyMTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYjMyNTgwNDhlNjY5MzFiYzdmMTU0ZWQ1YWI5NjBlYWQ0OTMwYTQ2N2EwNGVlYmFmN2IyZDE5OGQ4OGE3ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ah4nkvtRmXYf9CQnSYBagQ84FlsjG0K75bAfJkrIrbE)
> 
> ### RiMusic version
> 0.6.25
> 
> ### Android version
> Android 13
And also do not know what is happening to you or not that but when you are changing the song, sometime is proper working but most of the automatically click translating the lysics.

**Comment by fast4x** [comment]
Fixed click on translate button, available from version 0.6.26

**Comment by fast4x** [comment]
#1032
