### ISSUE TITLE
Shake phone to change song

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#972]
### Description

Is it possible?
I've seen some players having this feature. While it can be troublesome if the sensitivity is low then it won't be much of a problem I think.

### Additional Context

It might be possible but I had another wish. Is it possible to make it like so that when we shake once it'll change to next song. But when shaken twice it'll change back to previous song.

**Comment by fast4x** [comment]
ahahahahahah this is fantastic

**Comment by OrangeZXZ** [comment]
> ### Description
> 
> Is it possible?
> I've seen some players having this feature. While it can be troublesome if the sensitivity is low then it won't be much of a problem I think.
> 
> ### Additional Context
> 
> It might be possible but I had another wish. Is it possible to make it like so that when we shake once it'll change to next song. But when shaken twice it'll change back to previous song. 

Personally i won't use it since samsung has te ability to skip/unskip when holding the volume up/down but this is a fun feature

**Comment by fast4x** [comment]
Implemented, for now once shake change then song.
Available from version 0.6.29

**Comment by SureshTimma** [comment]
> Implemented, for now once shake change then song. Can enable/disable by ui > player section settings, default disabled.
> Available from version 0.6.29


At what time do you release update?

**Comment by fast4x** [comment]
Today release will be ready between 18:00 - 22:00 UTC
