### ISSUE TITLE
Proposal for Icon Revision in the RiMusic App

### ISSUE THREAD

**Issue by dAtA-TRoN** [fast4x/RiMusic#973]
### Description

I've noticed that the icons for Albums and Singles both look like side-viewed CDs, which can be confusing and make it difficult to quickly tell the tabs apart.

![IMG_20240308_210203-01.jpeg](https://github.com/fast4x/RiMusic/assets/71184627/520bff47-9e62-4028-9830-040515567e33)

### Suggested Solution

I stumbled upon an image that could be a good example for a new Album icon. Just a heads-up, I understand it might need some tweaks to fit better with the RiMusic app's design. This is just a starting point. We can definitely look into other options too, but I thought it'd be helpful to have something to begin with, given the challenge of finding the right icon in this particular case.

![sketch1709927935137](https://github.com/fast4x/RiMusic/assets/71184627/c60dc172-2e8a-4c44-95d5-0842603d6a6b)

### Additional Context

I believe prioritizing user experience and ensuring seamless navigation within the RiMusic app is crucial. Revising this icon aims to enhance usability and improve user satisfaction.

**Comment by ikanakova** [comment]
@fast4x could you please assign me this one as well

**Comment by ikanakova** [comment]
My suggestion for a new album icon::
<img src="https://github.com/fast4x/RiMusic/assets/38765251/a47eeed7-fc36-4897-8ebc-61e0ddf47502" width="250">

**Comment by dAtA-TRoN** [comment]
> My suggestion for a new album icon::
> <img src="https://github.com/fast4x/RiMusic/assets/38765251/a47eeed7-fc36-4897-8ebc-61e0ddf47502" width="250">
> 

Awesome!

**Comment by ikanakova** [comment]
Create pull request #1149

**Comment by ikanakova** [comment]
Improved album icon:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/b9ad8cc9-ba9a-4f6a-9e3d-eac9cba94fff" width="25">

**Comment by dAtA-TRoN** [comment]
> Improved album icon

I think that needs to be changed so that the CD only comes out half as much as it does now, so that the icon has enough space to be displayed large enough. In the current version of RiMusic, the symbol is too small in the sidebar.

**Comment by ikanakova** [comment]
> > Improved album icon
> 
> I think that needs to be changed so that the CD only comes out half as much as it does now, so that the icon has enough space to be displayed large enough. In the current version of RiMusic, the symbol is too small in the sidebar.

It's supposed to be an LP 😁 And when I shrink the protruding disc, you can't tell what it is anymore...

**Comment by dAtA-TRoN** [comment]
> It's supposed to be an LP 😁 And when I shrink the protruding disc, you can't tell what it is anymore...

Perhaps, but whether it's a CD or vinyl doesn't really matter. Both formats are popular and widely recognized. What truly matters is whether the icon's dimensions align and appear consistent, right?

**Comment by ikanakova** [comment]
I think it's more of a bug in the import between svg and vector drawable, because the whole icon is smaller in proportion.

A shrunken icon:
<img src="https://github.com/fast4x/RiMusic/assets/38765251/2ae2be9a-3897-4ea4-a3bc-9e149404f2d3" width="25">

**Comment by dAtA-TRoN** [comment]
Yeah, that's clearly a mug now. How about if there's simply no CD/vinyl sticking out at all? I think that would be the best. What do you think?

**Comment by ikanakova** [comment]
> Yeah, that's clearly a mug now 😆👌🏼. How about if there's simply no CD/vinyl sticking out at all? I think that would be the best. What do you think?
> 
> Edit:
> 
> Or you could just depict the CD inside the cover square and omit the musical note symbol. That would be another option.

<img src="https://github.com/fast4x/RiMusic/assets/38765251/2c908aee-4ebe-4057-a193-c638c7d2de2c" width="25">
<img src="https://github.com/fast4x/RiMusic/assets/38765251/2004e173-9ab8-4ffd-a12a-8c317fea83ca" width="25">

**Comment by dAtA-TRoN** [comment]
Finde ich tatsächlich beide sehr gut, und du?

**Comment by dAtA-TRoN** [comment]
Sorry for my German. I've edited it 😂.

**Comment by ikanakova** [comment]
> I actually find both very good, and you?

Me too. Now choose just one...
![ChoicesSesamoGIF](https://github.com/fast4x/RiMusic/assets/38765251/499338e0-c1a5-4789-bd86-4517d74d8fe9)

**Comment by ikanakova** [comment]
> Sorry for my German. I've edited it 😂.

Deepl also translates German into Czech 😆 So no problem.

**Comment by dAtA-TRoN** [comment]
> Me too. Now choose just one...

This honor should go to you 🫵🏼.

**Comment by ikanakova** [comment]
> > Me too. Now choose just one...
> 
> This honor should go to you 🫵🏼.

I think I like the first one a bit more.

**Comment by dAtA-TRoN** [comment]
> I think I like the first one a bit more.

Great. So be it.

**Comment by ikanakova** [comment]
#1218

**Comment by fast4x** [comment]
Implemented, available from version 0.6.28
