### ISSUE TITLE
Add an account

### ISSUE THREAD

**Issue by LopenantMan** [fast4x/RiMusic#974]
### Description

I can't listen to some of the videos that I open through the app, they tell me that "the original source has been deleted."

### Suggested Solution

The ability to add an account

**Comment by OrangeZXZ** [comment]
> ### Description
> 
> I can't listen to some of the videos that I open through the app, they tell me that "the original source has been deleted."

On age restricted vidéos? If that is the problem i think it can be patched without acount just need a little bypass

**Comment by dAtA-TRoN** [comment]
Only if the API permits it. Otherwise, it's not possible. Certain features, such as accessing lossless audio files, require an account and cannot be circumvented. These are behind the paywall.

**Comment by ikanakova** [comment]
Age restricted videos are somehow solved by NewPipe without logging in. And I'd be careful about logging in - someday Google might decide to block accounts that use alternative apps like Facebook sometimes does.

**Comment by fast4x** [comment]
Indeed, i agree.

**Comment by dAtA-TRoN** [comment]
Good point.

**Comment by dAtA-TRoN** [comment]
> Hey, I think you should pin an issue that is requesting this feature. So that many users notice it before creating new issues about it.

![26 - Meme.gif](https://github.com/fast4x/RiMusic/assets/71184627/f95de470-24d4-46b4-af8e-7e87c76f8ab1)

**Comment by OrangeZXZ** [comment]
@fast4x i have an idea for this

I saw ViTune using Piped acounts to save playlist and mutch more
![SmartSelect_20240317_230308.jpg](https://github.com/fast4x/RiMusic/assets/104271365/8e30f80e-b3e3-4bf6-93ac-2973b0f9bb55)

**Comment by fast4x** [comment]
For now no login...
