### ISSUE TITLE
Total listening time on Player

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#977]
### Description

I think the total listening time on the player is not well placed and i took some time to get what it was

![SmartSelect_20240309_015554](https://github.com/fast4x/RiMusic/assets/104271365/ead18620-3215-4e32-9e84-175a56fa2504)

### Suggested Solution

I think the time could be moved in the queue bottom bar next to the songs nuber (at the right of it)

![SmartSelect_20240309_015605](https://github.com/fast4x/RiMusic/assets/104271365/2c8f8e1a-ee90-492d-b952-4d15059e9c6a)

### Additional Context

I also think that the icon is useles because the begining time and the end time dosen't have icons and it being at the middle+ changing every second is enought

Maybe add a "-" like on youtube?

**Comment by OrangeZXZ** [comment]
Youtube "-" :
![Screenshot_20240309_021413_YouTube.jpg](https://github.com/fast4x/RiMusic/assets/104271365/ea48cc1d-2ca9-47d5-ac3f-6536a225f3f2)

I also notic3d that on youtube is next to the end time instead of the midle

I personally like it in the midle but it could be next to it too

**Comment by fast4x** [comment]
Now total time is under thumbnail and remaining time is like first

**Comment by fast4x** [comment]
> Youtube "-" :
> ![Screenshot_20240309_021413_YouTube.jpg](https://github.com/fast4x/RiMusic/assets/104271365/ea48cc1d-2ca9-47d5-ac3f-6536a225f3f2)
> 
> I also noticed that on youtube it is next to the end time instead of the middle
> I personally like it in the middle but i wont hate it next to the end time

To right separate by / ?

**Comment by OrangeZXZ** [comment]
> > Youtube "-" :
> > ![Screenshot_20240309_021413_YouTube.jpg](https://github.com/fast4x/RiMusic/assets/104271365/ea48cc1d-2ca9-47d5-ac3f-6536a225f3f2)
> > 
> > I also noticed that on youtube it is next to the end time instead of the middle
> > I personally like it in the middle but i wont hate it next to the end time
> 
> To right separate by / ?

yes

**Comment by fast4x** [comment]
Let's try

**Comment by fast4x** [comment]
Let's try again

**Comment by OrangeZXZ** [comment]
> > Let's try
> 
> What about keeping the "song total time" in middle and "time left", "time elapsed" in the right and left sides. 

If I understood corecly
I think this would be weird is like naming Point A : Start, Point B : 24 km remaining and Length : Destination

**Comment by OrangeZXZ** [comment]
> > > Let's try
> > 
> > What about keeping the "song total time" in middle and "time left", "time elapsed" in the right and left sides. 
> 
> If I understood corecly
> I think this would be weird is like naming Point A : Start, Point B : 24 km remaining and Length : Destination

I think doing it like youtube but instead of left put it to the right because the end of the seekbar is at the left is the best choice because it prevent the other timer being at the middle (also preventing UI movements)

Just adding "-" and "/" will be enough for the user to understand what it is

**Comment by OrangeZXZ** [comment]
> > If I understood corecly
> > I think this would be weird is like naming Point A : Start, Point B : 24 km remaining and Length : Destination
> 
> What I meant was something like this:
> ![InCollage_20240309_192801827.jpg](https://github.com/fast4x/RiMusic/assets/85461823/a01acefe-bcc1-4efb-baaf-eb23a1e2cd33)

yeah i find it weird the song length in the middle because the end point should be next to the end not in the middle

**Comment by fast4x** [comment]
Implemented, available from version 0.6.26
![Screenshot_20240311_020831](https://github.com/fast4x/RiMusic/assets/1484476/8cfbedd4-dd23-4d63-8403-cdbc828df1da)

**Comment by OrangeZXZ** [comment]
> > Implemented, available from version 0.6.26
> > ![Screenshot_20240311_020831](https://github.com/fast4x/RiMusic/assets/1484476/8cfbedd4-dd23-4d63-8403-cdbc828df1da)
> > 
> 
> Neat.
> But just as I thought I don't like "song time left" being similar to YouTube. 

then maybe add it to the middle like before with the "-" and the total time put it bellow the album art but at the top of the song name in the middle?

**Comment by fast4x** [comment]
Done
![Screenshot_20240311_121132](https://github.com/fast4x/RiMusic/assets/1484476/fa89e4b7-2bf5-43af-8a7c-7ac8667bd21f)

**Comment by fast4x** [comment]
slightly increased
![Screenshot_20240311_122330](https://github.com/fast4x/RiMusic/assets/1484476/88c91df0-906e-4e88-ab2a-035569e11524)

**Comment by fast4x** [comment]
28 min isn'm 1 our... format time is automatic...

**Comment by fast4x** [comment]
total time like this: 132:09:10 hh:mm:dd become 6d 4h 35s
is example...

**Comment by fast4x** [comment]
is good to read...

**Comment by OrangeZXZ** [comment]
> > total time like this: 132:09:10 hh:mm:dd become 6d 4h 35s
> > is example...
> > 
> > 
> 
> I don't get it…forget this…

28m is easier to the eyes that 28:00

**Comment by fast4x** [comment]
Create a specific ticket for the future.
