### ISSUE TITLE
Merge select buttons

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#979]
### Description

I think select buttons could be merged

### Suggested Solution

When in select mode the Select button is the deselect button

### Additional Context

Im talking about the button in the queue

Idk if there are other select buttons not merged

**Comment by dAtA-TRoN** [comment]
>I think select buttons could be merged

>When in select mode the Select button is the deselect button

Like this?

![IMG_20240309_070556-01.jpeg](https://github.com/fast4x/RiMusic/assets/71184627/9a2970c4-3fa7-4f95-8dce-8853f13b2a17)
