### ISSUE TITLE
Shows bad default language after application installation

### ISSUE THREAD

**Issue by ikanakova** [fast4x/RiMusic#98]
### Steps to reproduce the bug

1. Installing the application
2. Start the application
3. Go to settings

### Expected behavior

If the system language is Czech, the language settings are either "Czech" or "System".

### Actual behavior

Although the app is in Czech, the language box shows English.

### Screenshots/Screen recordings

![Screenshot_20231111_143109](https://github.com/fast4x/RiMusic/assets/38765251/f12a43d7-2e19-4d3e-94e7-cd64f96677d1)

### RiMusic version

0.6.8

### Android version

Android 13

**Comment by fast4x** [comment]
Bug confirmed

**Comment by fast4x** [comment]
Fixed, available from version 0.6.9
