### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by lilunknown** [fast4x/RiMusic#980]
### Description

It's a song transition feature that Spotify currently has, it's called a ### **gradual transition** or ### **crossfade**. It is a very useful feature for those who like to listen without pauses. I ask you to evaluate and if possible Implement in the app.
![Screenshot_20240303-201504_Spotify](https://github.com/fast4x/RiMusic/assets/162065067/3504a96b-ef33-4e2f-a22b-777d1b19b787)

### Suggested Solution

.

### Alternatives

.

### Additional Context

.

**Comment by Nikks84** [comment]
https://github.com/fast4x/RiMusic/issues/875#issue-2159551818

See this is already implemented this release 0.6.25
You can choose  how much pause in between songs change it in ui settings

**Comment by dAtA-TRoN** [comment]
@Nikks84

That's not quite what he's getting at. Here's a more elaborate explanation.

https://github.com/fast4x/RiMusic/assets/71184627/d59aba80-58c2-4b4b-b9b3-a3bfa1e7367a

While it would be absolutely fantastic to have this feature incorporated into RiMusic, I doubt that fast4x can execute it so seamlessly. As a layman, this feature appears quite complex in terms of feasibility to me.

**Comment by Nikks84** [comment]
> @Nikks84
> 
> That's not what he meant. Here's a more elaborate explanation.
> 
>  Crossfading.between.Songs.in.Spotify.mp4 
> While it would be absolutely fantastic to have this feature incorporated into RiMusic, I doubt that fast4x can execute it so seamlessly. As a layman, this feature appears quite complex in terms of feasibility to me.
> 
> And here's an audio example showcasing how songs transitions smoothly with a preset 6-second crossfade:
> 
>  Crossfade.Audio.Example.mp4 
> > You can choose how much pause in between songs
> 
> Essentially, it's quite the contrary. It's not about the pause between the songs, but rather about their 

Oh... Well I had to explain something else.

**Comment by fast4x** [comment]
it's much complex, but I'll try to use a workaround...

**Comment by fast4x** [comment]
Implemented crossfade songs effect, available from version 0.6.34
