### ISSUE TITLE
Add start radio option persistent queue songs.

### ISSUE THREAD

**Issue by Nikks84** [fast4x/RiMusic#981]
### Description

![Screenshot_2024-03-09-09-41-31-09](https://github.com/fast4x/RiMusic/assets/160481076/203c3b91-944b-4854-b309-e8f9b90a4169)

How will be the start radio option in persistent queue in every songs when long click on songs same like show in main player 3 dot menu.

### Suggested Solution

Could be helpful for us to start radio in every song just like this release play as next option in  persistent queue songs.

**Comment by fast4x** [comment]
Nice

**Comment by fast4x** [comment]
Implemented, available from version 0.6.29
Maybe I forgot to activate it at all points, check in the new version, thanks.

**Comment by Nikks84** [comment]
https://github.com/fast4x/RiMusic/assets/160481076/72ecc541-739c-48d0-a447-a4393b1bf081

Sorry  but it is not visible in this release 0.6.29 on next queued songs I mean next 50 upcoming queued songs .

**Comment by SureshTimma** [comment]
What is the use of Radio option? Please clarify..

**Comment by fast4x** [comment]
I'll check it

**Comment by Nikks84** [comment]
> What is the use of Radio option? Please clarify..

Radio option play Songs related to the song you are listening to or the songs of a similar artist are suggested, if I am not wrong then

**Comment by fast4x** [comment]
Fixed also in queued songs, available from version 0.6.30
