### ISSUE TITLE
[BUG] App crashes after exiting the app while playing a song

### ISSUE THREAD

**Issue by privacyfreak84** [fast4x/RiMusic#982]
Similar to #803. The issue still seems unresolved.

While playing a song, then exiting the app, the song stops playing. When the app is reopened, the mini player disappears (it can, for some reason, be brought back by pressing the 'back' button in Android's navigation menu).
After this, when I attempt to play another song, the app crashes.

Logs:

```
FATAL EXCEPTION: DefaultDispatcher-worker-11
Process: it.fast4x.rimusic, PID: 6119
java.lang.IllegalStateException
	at a9.n1.I0(SourceFile:1)
	at u3.y.m(SourceFile:1)
	at y8.z.u(SourceFile:30)
	at y8.z.l(SourceFile:13)
	at ra.r.q(SourceFile:157)
	at ra.d1.b(SourceFile:177)
	at ra.c1.u(SourceFile:1)
	at y9.a.k(SourceFile:1)
	at oa.j0.run(SourceFile:1)
	at l.j.run(SourceFile:14)
	at ua.i.run(SourceFile:1)
	at ua.a.run(SourceFile:92)
	Suppressed: ta.h: [v1{Cancelling}@b98e598, Dispatchers.IO]
```
Android version: 11
BTW I have invincible service enabled and battery optimisations disabled. I have followed all the steps for Samsung Android 11 on don'tkillmyapp.com

**Comment by dAtA-TRoN** [comment]
@privacyfreak84

Try this:
Settings -> Miscellaneous -> Service Lifetime

![IMG_20240309_074930.jpg](https://github.com/fast4x/RiMusic/assets/71184627/745ce5b0-0b5e-47a1-9109-c9fa3439a7f4)

Try the first option. If it is not helping, then try the second option.

**Comment by privacyfreak84** [comment]
> Try this:
> Settings -> Miscellaneous -> Service Lifetime
> 
> ￼
> 
> Try the first option. If it is not helping, then try the second option.

Already done that

**Comment by Nikks84** [comment]
> > Try this:
> > Settings -> Miscellaneous -> Service Lifetime
> > ￼
> > Try the first option. If it is not helping, then try the second option.
> 
> Already done that

1. Clear app info cache or  Restart your device

**Comment by privacyfreak84** [comment]
> Clear app info cache or Restart your device

The issue persists after doing both

**Comment by claxcian** [comment]
Anche me Rino

Me too Rino

**Comment by fast4x** [comment]
Android 11?

**Comment by claxcian** [comment]
Android 14

**Comment by fast4x** [comment]
Assurdo

**Comment by claxcian** [comment]
A me lo fa a volte, sua quando non  è in play sia quando è in riproduzione. Apri l'icona e si chiude subito perché va in crash. Non so come posso aiutarti ancora

**Comment by privacyfreak84** [comment]
Android 11

**Comment by claxcian** [comment]
Se apri la app dopo un po che non la usi va subito in crash. La riapri e si apre

**Comment by fast4x** [comment]
Sei sicuro di avere attivato invincible service e disattivato ottimizzazione batteria?

**Comment by claxcian** [comment]
Si. Vimusic non ci fa

**Comment by privacyfreak84** [comment]
Yes, invincible service is enabled and battery optimisation is disabled

**Comment by Vishcot** [comment]
It is crashing for me as well, anywhere sometimes opening app, sometimes when i search something..but after every few clicks it crashes.. I'll try to record a crash. But it's unpredictable when it will crash next time.
Mine Android 14.

**Comment by fast4x** [comment]
ok, I'm waiting for that

**Comment by Vishcot** [comment]
> ok, I'm waiting for that

Out of two i was able to record one repetitive crashing bug! 

Many times when i open app, 
library - favourites - i see all songs are showing as not downloaded which also indicates me it hoing to get crash the on the next song click.
And just after clicking any song it crashes..
Then I reopen app and it shows all songs are downloaded and then all songs work fine! 
See this vr:

https://github.com/fast4x/RiMusic/assets/136909951/2dacfdca-5ea5-4548-89b4-7149ea223e02

I will try to record a search related to another crash bug also, if i would be able to predict specifically on which steps it is getting crashed.

**Comment by claxcian** [comment]
https://github.com/fast4x/RiMusic/assets/46830063/1264a5cb-b122-4b93-89d0-08f36e1f61bb

Se apro la app dopo un po di tempo fa così. Se riciclo si apro regolarmente

**Comment by privacyfreak84** [comment]
Solved in latest version and by enabling persistent queue. Closing
