### ISSUE TITLE
[Feature]: Blurred cover background?

### ISSUE THREAD

**Issue by gigiboeru** [fast4x/RiMusic#984]
### Description

As much as I like the dark/pure black theme, I'd love to see the option to use the song/album cover as blurred background (maybe similar to how Poweramp looks). 

### Suggested Solution

Use the cover as blurred background - maybe add various blur intensity, saturation, brightnerss sliders/options.

**Comment by fast4x** [comment]
The idea is nice but it feels like turning the app into a graphics app...

**Comment by fast4x** [comment]
Indeed

**Comment by gigiboeru** [comment]
It will not interfere with the simple interface. Just see it as having some color in the background. It can also be made to look like a gradient. Even a simple color fill would look nice. I've seen this requested by other users as well.

**Comment by fast4x** [comment]
Improved player and background mode, available from version 0.6.35

**Comment by gigiboeru** [comment]
That's some good news!

**Comment by fast4x** [comment]
I think we have... found solution for all devices... yeah!

https://github.com/fast4x/RiMusic/assets/1484476/66fa5e30-0301-4dae-ad8f-78261278c534

**Comment by NightFly88** [comment]
> Ik denk dat we... een oplossing hebben gevonden voor alle apparaten... ja!
> 
>  Schermopname_20240516_161555.mp4

Very nice, but will there be an option to turn it off? 😂😂
