### ISSUE TITLE
Quick pics position change

### ISSUE THREAD

**Issue by Nikks84** [fast4x/RiMusic#985]
### Description

how will be quick pics position change to be near tips in present he looks very odd Since search icon move  to bottom side bar see this ss You do not think?
 
![IMG_20240309_143346](https://github.com/fast4x/RiMusic/assets/160481076/69299d30-a4b9-4eec-8e8d-37b17c258687)

### Suggested Solution

And if you change it, you will be in the empty space. Could be use for showing app logo just like main player thumbnail above.

**Comment by fast4x** [comment]
If I understand, replace the Quick Pics title with the app logo?

**Comment by Nikks84** [comment]
Yes sure..

**Comment by fast4x** [comment]
Implemented, available from version 0.6.30
