### ISSUE TITLE
Default Color Option

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#988]
### Description

In Default theme you have the green color and in the Dynamic by default you have a weird color

### Suggested Solution

Add an option that let you put an hex value to modify the Default color

In the Default theme you can change the green to resemble more your phone colors (instead of having material you)

In the Dynamic you will have a welcoming color instead of that weird blue (when the last song is not saved)

### Additional Context

This will make the app more customisable and make it go well with the phone theme if the user wants

**Comment by OrangeZXZ** [comment]
> Or maybe a "color code input" feature if possible?

you mean a color hue?

**Comment by dAtA-TRoN** [comment]
Duplicate #930

**Comment by OrangeZXZ** [comment]
> Duplicate #930

my bad 😄

**Comment by dAtA-TRoN** [comment]
> my bad

We all make mistakes 🤗.

**Comment by OrangeZXZ** [comment]
> Duplicate #930

also duplicate to #104

**Comment by fast4x** [comment]
Implemented customized colors theme, available from version 0.6.34
