### ISSUE TITLE
Remove similar edit icons

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#991]
### Description

I think that using the 3 same icons for 3 diferent options is a bit weird

### Suggested Solution

create 3 new icons for:
- Modify Title : T icon with the pen on top (to resemble text)
- Edit autors : Person with the pen on top
- Edit image : Image icon with a pen on top

**Comment by ikanakova** [comment]
@fast4x If you agree with this, could you somehow assign me an issue (+ another where an icon change is required) so I can easily find it 🙂

**Comment by dAtA-TRoN** [comment]
@ikanakova Are you responsible for the graphics here? Could you please take a look at this? #973

**Comment by OrangeZXZ** [comment]
> @ikanakova Are you responsible for the graphics here? Could you please take a look at this? #973

yes @ikanakova makes the icons that are missing and i think they are always great!

**Comment by ikanakova** [comment]
> @ikanakova Are you responsible for the graphics here? Could you please take a look at this? #973

Yeah, I'll take a look.

**Comment by dAtA-TRoN** [comment]
> Yeah, I'll take a look.

Cool!

**Comment by fast4x** [comment]
yes i agree

**Comment by ikanakova** [comment]
- Modify Title: <img src="https://github.com/fast4x/RiMusic/assets/38765251/e4c5518e-ea26-4491-bd4d-40a2eb7be24d" width="30">
- Edit image: <img src="https://github.com/fast4x/RiMusic/assets/38765251/e770c33c-dcad-4e6f-8900-ad93fbe88d8a" width="30">
- Edit autors: <img src="https://github.com/fast4x/RiMusic/assets/38765251/34a1499f-9836-4e65-9c93-651bda604cd8" width="30">

**Comment by OrangeZXZ** [comment]
> - Modify Title: <img src="https://github.com/fast4x/RiMusic/assets/38765251/e4c5518e-ea26-4491-bd4d-40a2eb7be24d" width="30">
> - Edit image: <img src="https://github.com/fast4x/RiMusic/assets/38765251/e770c33c-dcad-4e6f-8900-ad93fbe88d8a" width="30">
> - Edit autors: <img src="https://github.com/fast4x/RiMusic/assets/38765251/34a1499f-9836-4e65-9c93-651bda604cd8" width="30">
> 
> 

looks nice just not sure about putting them in boxes and maybe make the pen overlap more?

**Comment by ikanakova** [comment]
> looks nice just not sure about putting them in boxes and maybe make the pen overlap more?

- Modify Title: <img src="https://github.com/fast4x/RiMusic/assets/38765251/4d92894c-4630-4ea7-a38f-32b11fe61002" width="30">
- Edit image: <img src="https://github.com/fast4x/RiMusic/assets/38765251/d0a17bdb-4222-4a68-9849-f6a420e24c98" width="30">
- Edit autors: <img src="https://github.com/fast4x/RiMusic/assets/38765251/9e99ccc8-7682-402e-9e2a-101705e015a5" width="30">

What about this version?

**Comment by OrangeZXZ** [comment]
> > looks nice just not sure about putting them in boxes and maybe make the pen overlap more?
> 
> - Modify Title: <img src="https://github.com/fast4x/RiMusic/assets/38765251/4d92894c-4630-4ea7-a38f-32b11fe61002" width="30">
> - Edit image: <img src="https://github.com/fast4x/RiMusic/assets/38765251/d0a17bdb-4222-4a68-9849-f6a420e24c98" width="30">
> - Edit autors: <img src="https://github.com/fast4x/RiMusic/assets/38765251/9e99ccc8-7682-402e-9e2a-101705e015a5" width="30">
> 
> What about this version?
> 

they are better but it would be nice to have a outline on the pen like in between the person also the tip of the pen should be on the icon (on the text icon the pen is pointing at nothing)

For the image and artists it is good but i think it could be placed with the tip on the person body and on the tiny mountain

**Comment by ikanakova** [comment]
I've thought about this at length, and I think the idea of overlaying the pencil over the picture (image/artist/title) isn't a good idea, because in colors less bold than black it might be hard to distinguish what's a pencil and what's an picture. I like the version with the frame, but I still want to improve it.

**Comment by ikanakova** [comment]
- Modify Title: <img src="https://github.com/fast4x/RiMusic/assets/38765251/014f55c3-9065-4b14-91f0-1483c4b7a3a0" width="30">
- Edit image: <img src="https://github.com/fast4x/RiMusic/assets/38765251/949a9fb8-c05e-4d21-ae1e-62134e66e694" width="30">
- Edit autors: <img src="https://github.com/fast4x/RiMusic/assets/38765251/9c5fccfb-9dae-4043-a5fc-69482f97c0b1" width="30">

**Comment by ikanakova** [comment]
> * Modify Title: <img alt="" width="30" src="https://private-user-images.githubusercontent.com/38765251/315952043-014f55c3-9065-4b14-91f0-1483c4b7a3a0.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTkzMTcsIm5iZiI6MTcxMTA5OTAxNywicGF0aCI6Ii8zODc2NTI1MS8zMTU5NTIwNDMtMDE0ZjU1YzMtOTA2NS00YjE0LTkxZjAtMTQ4M2M0YjdhM2EwLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5MTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNmE3NjZlYTgzNDEyNDgwNjk3NmE3ZTk1ODBhNDI1Nzg2MzNhNjFkYTRmNTgwZDgzNDY3MmM3OTg3NjlmNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xlNk5kCb6V9LJo5N3C7PKPxN7YmrJu8oUvRIxvm4rn4">
> 
> * Edit image: <img alt="" width="30" src="https://private-user-images.githubusercontent.com/38765251/315952051-949a9fb8-c05e-4d21-ae1e-62134e66e694.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTkzMTcsIm5iZiI6MTcxMTA5OTAxNywicGF0aCI6Ii8zODc2NTI1MS8zMTU5NTIwNTEtOTQ5YTlmYjgtYzA1ZS00ZDIxLWFlMWUtNjIxMzRlNjZlNjk0LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5MTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNmQ0OTQ4ZTk1ZmE2YzFhMTEzYTk1YmQ3YWU4M2RlNzFlNWE4YWY1ZjRlZGQzNTk2NGU0NWU2MzkyZGJiM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GrhCfiQbrEmY7FSRwwEfbHxzq38mDXHBa66B8SvzR8Y">
> 
> * Edit autors: <img alt="" width="30" src="https://private-user-images.githubusercontent.com/38765251/315952054-9c5fccfb-9dae-4043-a5fc-69482f97c0b1.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTkzMTcsIm5iZiI6MTcxMTA5OTAxNywicGF0aCI6Ii8zODc2NTI1MS8zMTU5NTIwNTQtOWM1ZmNjZmItOWRhZS00MDQzLWE1ZmMtNjk0ODJmOTdjMGIxLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5MTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MDAyZDIyMmJhNWM4ODU4ODZmNTc2ODdjOWNiYWQ4MDYzMjlmMjE3ZWY2ZjYzMDNhNDAxYzM5OTM2MGI5NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WWZz_pqtyt8BsMu8TE0y6mX7XPBbp5cmSN2QTAo7P_g">

The pencil is a little bigger. I think even on an icon this small you can see what's on it, plus they look similar so they look nice under each other.


I suppose the Modify Title will be used to rename the playlist too.

**Comment by OrangeZXZ** [comment]
> > * Modify Title: <img alt="" width="30" src="https://private-user-images.githubusercontent.com/38765251/315952043-014f55c3-9065-4b14-91f0-1483c4b7a3a0.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDE2MTAsIm5iZiI6MTcxMTEwMTMxMCwicGF0aCI6Ii8zODc2NTI1MS8zMTU5NTIwNDMtMDE0ZjU1YzMtOTA2NS00YjE0LTkxZjAtMTQ4M2M0YjdhM2EwLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5NTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YzQ0NTYxN2M5OWFiZDRhMWU0N2ZmNjgxZmMwMDdhMzM1YTZmZDAzNTY1NzE4NjU4NTdlY2M3Mzk5MTQzNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fV47FeFsB0rWUVHJ0coFEX-y0F_r6PMV6xASu4s_SJQ">
> > * Edit image: <img alt="" width="30" src="https://private-user-images.githubusercontent.com/38765251/315952054-9c5fccfb-9dae-4043-a5fc-69482f97c0b1.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDE2MTAsIm5iZiI6MTcxMTEwMTMxMCwicGF0aCI6Ii8zODc2NTI1MS8zMTU5NTIwNTQtOWM1ZmNjZmItOWRhZS00MDQzLWE1ZmMtNjk0ODJmOTdjMGIxLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5NTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZjUwZDVmYWY2NmJjMTM3MGVkYzNmYTQ3MWVhMWMxYmZkZjc1NzlhZDZmZDIyZWUxNGRlYmRiMTc4NTZiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6SLPAx5QxAN_mBRs-Rwv6L197Y8_7MM8MXRswF-cWiQ">
> > * Edit autors: <img alt="" width="30" src="https://private-user-images.githubusercontent.com/38765251/315952051-949a9fb8-c05e-4d21-ae1e-62134e66e694.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDE2MTAsIm5iZiI6MTcxMTEwMTMxMCwicGF0aCI6Ii8zODc2NTI1MS8zMTU5NTIwNTEtOTQ5YTlmYjgtYzA1ZS00ZDIxLWFlMWUtNjIxMzRlNjZlNjk0LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5NTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNWNlYzdhOTkxODZkMjkyYzFlNWU3MWY4MWI3YTRhMWQ4OWY2ZTNmYzM1OTdmOGIxM2I0MWYyMTFmMDEzMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q2WOU4esulhHaBFz170i3o-2U4pTpF5Ic5JkZqm0j0g">
> 
> The pencil is a little bigger. I think even on an icon this small you can see what's on it, plus they look similar so they look nice under each other.
> 
> I suppose the Modify Title will be used to rename the playlist too.

i think that is better only the image icon is not centered like the others

**Comment by ikanakova** [comment]
> > The pencil is a little bigger. I think even on an icon this small you can see what's on it, plus they look similar so they look nice under each other.
> > I suppose the Modify Title will be used to rename the playlist too.
> 
> i think that is better only the image icon is not centered like the others

That's because the frame and pencil are always in the same place, and a centered image would overlap the pencil or I'd have to make it smaller, and smaller probably wouldn't look good.

**Comment by ikanakova** [comment]
So if you agree, I'll create a pull request with the new edit icons.

**Comment by OrangeZXZ** [comment]
> So if you agree, I'll create a pull request with the new edit icons.

i agree in just a tiny personal thing it would bother

**Comment by ikanakova** [comment]
Created PR #1156

**Comment by fast4x** [comment]
Implemented, available from version 0.6.27

**Comment by SureshTimma** [comment]
> Implemented, available from version 0.6.27

@fast4x eagerly waiting for update

**Comment by ikanakova** [comment]
New version of Edit autors to match artist icon in https://github.com/fast4x/RiMusic/issues/1176#issuecomment-2017569743
<img src="https://github.com/fast4x/RiMusic/assets/38765251/e8657e57-8f8a-4099-be71-12c04e7e9595" width="25">

**Comment by ikanakova** [comment]
#1218
