### ISSUE TITLE
Proxy works for a while and stops (repeatedly)

### ISSUE THREAD

**Issue by Spaceshiprace** [fast4x/RiMusic#992]
### Steps to reproduce the bug

everytine I get a proxy from free proxy sites it works only for a while of time and its shutting down

### Expected behavior

To work normally

### Actual behavior

It works only for a while of time

### RiMusic version

0.6.25

### Android version

Android 12

### Additional information

It was working for without this issue in the past week, until I start facing thia annoying issue.. I just don't know what happened !? maybe its the proxy configurations
Please help

**Comment by fast4x** [comment]
You can just try another proxy

**Comment by Spaceshiprace** [comment]
I tried a lot of proxies its so rare to find one that actually works
did you have any proxy configuration that works all the time

**Comment by fast4x** [comment]
Visit wiki section faq

**Comment by Spaceshiprace** [comment]
New York Proxies is the only ones that works for me what's that mean ?

**Comment by fast4x** [comment]
It means that that proxy is up and running. Many of them run for a while, it’s important to find the right one.
