### ISSUE TITLE
Swipe to close player menu

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#994]
### Description

While there are so many swiping features it's not possible to swipe down and close the player menu. I mean this:
![Screenshot_20240309-223830](https://github.com/fast4x/RiMusic/assets/85461823/b3264da1-7155-4e8b-a493-38e01955822a)

By "swiping down" I mean swiping just as the arrow mark is shown in the ss above.

### Suggested Solution

Implement swipe to close player menu. (Sorry if what I'm calling it ain't correct.)

**Comment by fast4x** [comment]
you mean horizontal line like in queue?

**Comment by fast4x** [comment]
ok i understand you talk about gesture for close menu...

**Comment by fast4x** [comment]
No it's ok

**Comment by fast4x** [comment]
Of course, in the meantime the menu is closed by clicking on another external point.

**Comment by fast4x** [comment]
Arrow is better.

**Comment by fast4x** [comment]
Implemented arrow down button on top menu for closing it, available from version 0.6.26

**Comment by sayyid5416** [comment]
It's not working on 0.6.26

**Comment by fast4x** [comment]
Not gesture but click down arrow button

**Comment by sayyid5416** [comment]
> Not gesture but click down arrow button

1. That button is very small.
2. That button is pretty useless, as you can already click anywhere outside of context menu to close it.

**Comment by fast4x** [comment]
i can increase size, but click outside close it

**Comment by sayyid5416** [comment]
> i can increase size, but click outside close it

I think this button is totally unnecessary. clicking outside can already close it.
