### ISSUE TITLE
Some Finishings..

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#998]
### Description

Refer ss:

And hey, now i don't have much complaints or requests about this player, you've catered every feature in an amazing way! This was all i wanted since my childhood days! Thankyou to all of you guys ❤️❤️ whosoever gave so much of their efforts in this project! You guys deserves salute 🫡🫡🫡

### Suggested Solution

1. There is two search icons always ( looks messy ) if you enable search from settings..
 
![Screenshot_20240310-094130](https://github.com/fast4x/RiMusic/assets/136909951/50860fa1-a0cb-4da5-9c66-516375ef1aa8)

2. There is also two menu icons, in player if you enable menu icon in player settings.

![Screenshot_20240310-094223](https://github.com/fast4x/RiMusic/assets/136909951/8da3ae9d-4ca6-4db7-94a2-318f8a566a26)

3. Also if possible shall you enable swipe up gesture even if arrow icon is enabled? As i saw if arrow icon is disabled, swipe up on queue works well! But if you enable arrow icon, swipe gesture is disabled!

![Screenshot_20240310-094248](https://github.com/fast4x/RiMusic/assets/136909951/fbbfa645-85c0-438e-8c34-96e6bec0ff5d)

**Comment by dAtA-TRoN** [comment]
> About point 1 I think both should stay. Because it's not really causing any problem, is it? Moreover, you can consider the search icon on playlist as a backup one. Don't you agree?

I have to disagree. It's unnecessarily redundant and confusing.

**Comment by dAtA-TRoN** [comment]
>1. There is two search icons always ( looks messy ) if you enable search from settings..

Actually, this was already changed in one of the recent updates. When you activate the search in the sidebar, the search at the top of the screen should disappear. Check if you can update.

**Comment by dAtA-TRoN** [comment]
> > > About point 1 I think both should stay. Because it's not really causing any problem, is it? Moreover, you can consider the search icon on playlist as a backup one. Don't you agree?
> > 
> > I have to disagree. It's unnecessarily redundant and confusing. 
> > 
> 
> Yeah I figured and so edited my comment later.

I have also edited my comment. You answer too quickly 😂.

**Comment by dAtA-TRoN** [comment]
> But on user created/imported playlists there is only one search icon. Only playlists provided from the app needs improvement.

I just checked now. I don't have a sidebar within my playlists at all. How can that be? Check ss.

![Screenshot_2024-03-10-06-48-02-23_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/7776da9c-69b6-41c8-80f4-35f9a6616951)

**Comment by dAtA-TRoN** [comment]
> I think it's because you're keeping \"Navigation bar position\" Left. When I saw this screenshot I had guessed it might be because of that and it certainly is.\n\nfast4x is gonna need to work on this as well…

Ah, very good! We've discovered something new again 😁. I think I'll later submit a proper request about that 👌🏼.

**Comment by dAtA-TRoN** [comment]
>Yup. Do that.
Aye 🫡!

**Comment by fast4x** [comment]
Yup in favourites, cached, my top, and downloaded icon search is redundant. I'll fix.
Missing sidebar I haven't this bug.

**Comment by Vishcot** [comment]
> Yup in favourites, cached, my top, and downloaded icon search is redundant. I'll fix.
> Missing sidebar I haven't this bug. 

Even in mine, it is there..![Screenshot_20240310-135440.png](https://github.com/fast4x/RiMusic/assets/136909951/07c1f54d-7218-4636-99d7-69e1db5ed289)

**Comment by dAtA-TRoN** [comment]
Hahaha, now you're faster than one can open a new request 😂. I've noticed the issue with the missing sidebar. To encounter it, you need to display the sidebar on the right side and navigate to different playlists. I'll open a report for this when I'm home later.

**Comment by fast4x** [comment]
Faster? Oookkkkk Here I am the second! I'll look at the bug right away oookkkk. We are faster, We are RiMusic legion! 😂

**Comment by dAtA-TRoN** [comment]
> Faster? Oookkkkk Here I am the second! I'll look at the bug right away oookkkk. We are faster, We are RiMusic legion! 😂

https://github.com/fast4x/RiMusic/assets/71184627/c9536725-95b1-40bb-bd3e-c45f3b9b748b

**Comment by fast4x** [comment]
Fixed sidebar in preferites, available form verson 0.6.26

**Comment by dAtA-TRoN** [comment]
> Fixed sidebar in preferites, available form verson 0.6.26

What exactly did you fix now? The thing I just painstakingly created the comparison for?

![ZomboDroid_10032024101613.jpg](https://github.com/fast4x/RiMusic/assets/71184627/265708f4-7be3-4be2-a18c-e58126993100)

**Comment by fast4x** [comment]
I have been fixed width page when sidebar is to right.

**Comment by fast4x** [comment]
Fixed also search icon duplcity

**Comment by dAtA-TRoN** [comment]
> Fixed also search icon duplcity

💪🏼

**Comment by Vishcot** [comment]
> Fixed also search icon duplcity

Did you also fix menu icon duplicity in the player, if we like to enable the menu button at the bottom?

**Comment by dAtA-TRoN** [comment]
There is option in settings to turn off the below one. I commented way above. Read again.

It's likely about redundancy once more. Having two switches on a single screen that perform the same function is unnecessary and confusing. Therefore, it would be ideal if fast4x could transform this into an "either/or" scenario. If one prefers the menu button at the top, then it won't be available at the bottom, and vice versa.

**Comment by Vishcot** [comment]
> > Did you also fix menu icon duplicity in the player, if we like to enable the menu button at the bottom? 
> 
> There is option in settings to turn off the below one. I commented way above. Read again.

I already read that, but i was the one who asked for the menu button option to be in the bottom for the first time.
For me it is more convenient to have that icon in the bottom so I don't want to disable it from the bottom. 😂😂

**Comment by Vishcot** [comment]
> > I already read that, but i was the one who asked for the menu button option to be in the bottom for the first time.
> > For me it is more convenient to have that icon in the bottom so I don't want to disable it from the bottom. 😂😂
> 
> I see…my bad.

Na na, everyone is contributing, efforts won't go unrecognised! Especially when you have these levels of great developers like a rimusic has..🫡

**Comment by fast4x** [comment]
Improved menu button in player, when active in action bar button, isn't visible on top page.
Available from version 0.6.26

**Comment by dAtA-TRoN** [comment]
> Improved menu button in player, when active in action bar button, isn't visible on top page.
> Available from version 0.6.26

https://github.com/fast4x/RiMusic/assets/71184627/d41364fd-fe0f-4ed4-9509-2cbf52a25eab

**Comment by fast4x** [comment]
![ohmygod](https://github.com/fast4x/RiMusic/assets/1484476/c84f3d86-5989-495f-b623-6169fb0ca0c1)
