### ISSUE TITLE
Import .db doesn't import settings! 

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#999]
### Steps to reproduce the bug

1. Go to settings, export backup 
2. Import backup
3. Only music database will get imported.
4. Settings will be as it is.

### Expected behavior

Settings and database both should be imported..

### Actual behavior

It crashes after importing and when we open it again it only imports our music.

### RiMusic version

0.6.25

### Android version

Android 14

**Comment by dAtA-TRoN** [comment]
Perhaps implementing a checklist popup when initiating a backup, where users can select precisely what they wish to include in the backup.

**Comment by dAtA-TRoN** [comment]
Good point.

**Comment by fast4x** [comment]
Backup not contain settings. For crash in import I'll see it soon.

**Comment by fast4x** [comment]
Crash in import occur not all time, i've check it and it occur after succeded restore, in the future i'll check it better.

**Comment by fast4x** [comment]
For now not

**Comment by OrangeZXZ** [comment]
I know the fact that if you have spaces or special characters it will not work also sometimes when the db dosent have .db at the end it also dosent work

I think a way of preventing this is to automaticaly rename the file before sending it to the app

**Comment by fast4x** [comment]
Selection file is managed by system, files not .db can't select by file selection dialog
